### ISSUE TITLE
Use not only device language, but also keyboard settings to detect default language-specific filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#100]
Example:

Device language: German
Keyboard languages: English, German, Russian

In this case we should enable russian and german filters by default.

**Comment by Revertron** [comment]
This will probably help:
http://stackoverflow.com/questions/14775218/how-can-i-know-keyboard-language-en-fr

**Comment by ameshkov** [comment]
Done
