### ISSUE TITLE
Make VPN autopause disabled by default for newer devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1000]
For Android 6.0 and newer we should make `pref.vpn.disable.pause` checked by default.

I've been testing it for quite some time and it seems to be working just ok.

**Comment by TPS** [comment]
I've been using it this way on both my 4.4.2 & 7.0 for a long time & never experienced an issue from it, directly.  The only think I'd suggest is maybe a periodic cache flush - sometimes a bad DNS entry (I think) makes into the cache (mostly due to weak signal), & toggling AG's status resolves it.

**Comment by ameshkov** [comment]
There're some issues with simply enabling `pref.vpn.disable.pause`.

For instance, it also controls auto pause in the case of tethering. I guess we should separate these things in two different low-level flags.

And one more thing. VPN does not mess with Tethering in a case of Android 7.1. We should test it on other firmware though, Samsung for instance.

**Comment by ameshkov** [comment]
Also, we should apply complicated routes all the time in this case as we won't be able to re-setup the VPN routes without restarting it.

**Comment by ameshkov** [comment]
It appears, that for now the only devices we can do it for are Nexus and Pixel with Nougat.

**Comment by TPS** [comment]
> It appears, that for now the only devices we can do it for are Nexus and Pixel with Nougat.

I've been doing this w/ non-GPhones regularly.  Why'd you specify them?

> Also, we should apply complicated routes all the time in this case as we won't be able to re-setup the VPN routes without restarting it.

I never turn on that Low-level Setting (except as a test a while ago & then turned it back off, as it seemed to cause problems similar to #737) & everything seems fine w/o it, even across multiple (wifi) networks, but I'll re-enable to try & see what effect it has, if you want me to?

**Comment by ameshkov** [comment]
> I've been doing this w/ non-GPhones regularly. Why'd you specify them?

We disable auto-pause functionality if both of the following conditions are true:

1. A device does not suffer from the tethering issue.
2. A device does not suffer from power saving mode issue.

In both cases, we need to pause protection automatically.

For instance, Samsung with Nougat suffers from the tethering issue.

> I never turn on that Low-level Setting (except as a test a while ago & then turned it back off, as it seemed to cause problems similar to #737)

Actually, using complicated routes is preferable. Filtering LAN addresses might cause issues with a lot of apps. That's why by default we are in fact using "complicated routes" except some rare cases with old Android versions/devices.

**Comment by ameshkov** [comment]
Auto-pause disabled by default for new Nexus and Pixel devices. Also, there are some improvements that will help it function properly if a user opts to disable it manually.

**Comment by ameshkov** [comment]
@vozersky we need to re-test Samsung tethering issue with `pref.vpn.ipv4.complex` enabled

**Comment by vozersky** [comment]
@ameshkov 
with disabled pause and `pref.vpn.ipv4.complex` enabled there  is still no internet connection in the mobile hotspot network on galaxy s7

**Comment by vozersky** [comment]
I've just updated S7 to the latest firmware, and tethering works now.

* Galaxy S7 Firmware: G930FXXU1DQB7/G930FOXE1DQB1/G930FXXU1DQB3
* Adguard 2.9 Beta

**Comment by ameshkov** [comment]
Firmware version?

**Comment by ameshkov** [comment]
@vozersky check OnePlus as well

**Comment by ameshkov** [comment]
Let's reopen this issue then.

**Comment by vozersky** [comment]
Tethering also works fine on OnePlus 3.

**Comment by ameshkov** [comment]
What about power saving? No issues?

**Comment by ameshkov** [comment]
Ok then, let's do it for all devices with Nougat.

**Comment by vozersky** [comment]
Yeah, didn't find any power saving issues on galaxy s7 (mid powersaving mode)
