### ISSUE TITLE
Angry birds fight - does not load

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1003]
https://play.google.com/store/apps/details?id=com.rovio.angrybirdsfight&hl=ru
Game doesn't loading until `cloud.rovio.com` is not added to HTTPS exclusion list.
<details>

![image](http://imagizer.imageshack.com/img922/6650/RTPptz.jpg)
</details>

**Comment by ameshkov** [comment]
@nkartyshov could you please check it?

**Comment by nkartyshov** [comment]
@ameshkov The apps works fine with last beta version.
