### ISSUE TITLE
Ads from YouTube app(var 11.47.57).

### ISSUE THREAD

**Issue by hiseka** [AdguardTeam/AdguardForAndroid#1007]
Ads from YouTube app.
Please fix it. TT

i'm sorry. I can not speak English. I used Google Translator.

phone - nexus 6p 32gb
os - android 7.1.1
root - no root(pure)
YouTube app var - 11.47.57
luncher - nova luncher

**Comment by Bluscream** [comment]
@hiseka https://blog.adguard.com/en/how-to-block-ads-on-youtube-for-android/

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/621
