### ISSUE TITLE
Microsoft Solitaire Collection app - ads.

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardForAndroid#1016]
Microsoft Solitaire Collection app - ads.

<details>

![screenshot_2017-01-06-13-04-51](https://cloud.githubusercontent.com/assets/23258533/21739512/65c97530-d4a5-11e6-9741-5b556423c526.png)

</details>

<details>

 "androidVersion" : "6.0 (sdk=23)",
  "applicationId" : "1169832a59e45b08",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "HUAWEI BTV-W09",
  "deviceSpeedRank" : 119,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 14, 11, 211 ],
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "DEFAULT",
 "installerPackage" : null,
  "kernelVersion" : "3.10.94",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-2/base.apk",
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",

</details>

Ticket ID: 1215963

**Comment by ameshkov** [comment]
It seems that this rule helps:
`||taboola.com^$app=com.microsoft.microsoftsolitairecollection`

**Comment by ameshkov** [comment]
@seanl-adg could you please take a look?
It this rule helps, let's simply add it to the mobile ads filter.

**Comment by ameshkov** [comment]
@seanl-adg ?

**Comment by seanl-adg** [comment]
@ameshkov I can't reproduce ads. Is it appear after playing game for certain time?

**Comment by ameshkov** [comment]
@seanl-adg not sure:( what about taboola requests? Do you see them in the log file?

**Comment by seanl-adg** [comment]
I don't see it in HTTP request log at all.
