### ISSUE TITLE
Adguard doesn't switch to standby mode when internet connection is off

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1019]
Steps user took to reproduce:

"1. Wi-Fi is off, reboot phone.
2. AdGuard asks for VPN connection.
3. Accepted VPN connection.
4. AdGuard begins to filtering phone (Wi-Fi is still off).

When I use AdGuard app and manually turn off filtering then after I turn on Wi-Fi AdGuard service won't start at all and I must again use AdGuard app to start it manually.

When I skip and don't use AdGuard app to manually stop filtering then:

5. Turned Wi-Fi on, Adguard still filtering my phone.
6. Turned Wi-Fi off, Adguard goes back to standby mode.
7. Turned Wi-Fi on, Adguard begins to filtering my phone.

On Android 6.0.1 after phone reboot AdGuard service behave always normal!"

Logs are available here: 1485773

Original thread with more details: https://forum.adguard.com/index.php?threads/18521/

**Comment by nkartyshov** [comment]
adguard-java-code/review/AJC-CR-145

**Comment by ameshkov** [comment]
We want to disable autopause by default in v2.9: #1000 

It'd be better if user just enables `pref.vpn.disable.pause` flag, it'll fix the issue.
