### ISSUE TITLE
Amazon version and update channels

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#102]
There should not be any update channel for Amazon version of Adguard. All versions should use release channel.

All updates should be handled by Amazon app.

**Comment by TPS** [comment]
As [I mentioned earlier](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-148307777), Amazon seems to treat the beta as a separate app (sort of).  Is it possible, then, to have official release OR beta release installed, then you folks push appropriate updates to _each_, & let Amazon handle the updating?

**Comment by ameshkov** [comment]
I doubt you'll be able to install beta and release versions along on one device.

> Is it possible, then, to have official release OR beta release installed, then you folks push appropriate updates to each, & let Amazon handle the updating

Yep, that's what we'd like to to do.

**Comment by TPS** [comment]
Nono, I mean a user would choose 1 or the other (given appropriate invites from you all ;), & then either would handled independently —  more or less how a user chooses to flip that beta/release toggle for the website version.

I'd happily reinstall the "Test" version if I got invites to updates at same time as beta website versions.  But the lag between 1 & the other defeats that purpose, right?

**Comment by ameshkov** [comment]
> I'd happily reinstall the "Test" version if I got invites to updates at same time as beta website versions. But the lag between 1 & the other defeats that purpose, right?

The main problem here is that we don't yet push Test versions along with website beta release. But that's not intentional, just need some time to get used to amazon:)

**Comment by Revertron** [comment]
Hid the channels for amazon builds.

**Comment by TPS** [comment]
@ameshkov @Revertron Thanks for the updated test invite!  I've updated to it & (as a bonus :wink:) ran into [a complicated point 5 in my odd notes](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-140069504). ☺

**Comment by TPS** [comment]
@ameshkov @Revertron The test build is < the current release update I'm getting prompted for: .231 vs .240.  Also, I've not received _any_ test builds in between.…

**Comment by ameshkov** [comment]
@TPS .240 is a new release, there were not any tests between RC and actual release.

**Comment by ameshkov** [comment]
Hm, wait, you've got that notification on amazon version right?

Maybe we should have disabled notifications also..

**Comment by TPS** [comment]
@ameshkov @Revertron Notifications are fine, but then you gotta remember to keep test ≥ release by keeping both updated & sending test invites.  When I receive the notification to update from test to release, I _do_ have to report something's a bit off, right?  Or do you see this differently than I do? (I see this conceptually, e.g., how NoScript's dev build rolls out: the last dev build before a release build is practically identical _except_ for the logic to keep on the dev update mechanism.  Is it meant to be same here?)

**Comment by ameshkov** [comment]
We have pushed .240 to stable in Amazon, it just takes some time to go through review process.

@Revertron I still think we should ignore update info until "forced" flag isn't true.

**Comment by TPS** [comment]
.240 _is_ live on Amazon, just not on testing build.  The latest there is .231, I think, but since they're interrelated on Amazon's backend, one _will_ update the other [with strange side effects](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-140069504).

**Comment by ameshkov** [comment]
Is it possible to somehow disable test build when you update to newer stable?

**Comment by TPS** [comment]
Other than overwrite via update, or uninstall/reinstall, I don't see how.…  I'm not sure what you mean?

**Comment by ameshkov** [comment]
I mean disable test build in amazon underground

**Comment by TPS** [comment]
I'm not running Underground, just plain Appstore, disable what, again?

**Comment by ameshkov** [comment]
There was an Appstore app?:) I've always though they have replaced it with Underground:)

**Comment by ameshkov** [comment]
Ok, I mean you have "test build" in your apps list.
Could you simply remove it from the list?

**Comment by ameshkov** [comment]
As test and prod are separate build this will fix the update issue.
And when new test build is ready you can remove the stable one.

**Comment by TPS** [comment]
Underground is a replacement for the Google release of the regular Amazon (shopping) app, but to successfully run Amazon-bought apps, 1 must run Appstore, also.  They complement each other (if you want them both), but don't completely overlap functionally.

Test & release _are_ separate builds, but, [as mentioned](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-140069504), 1 overwrites the other & licensing is entirely separate.  That's why I was hoping that everything release would be also published test, though not other way around.

**Comment by ameshkov** [comment]
That's rather hard to do:)

The only way to change this once and forever is to have different beta and release package names.
Then we can even have public "beta" app on amazon.

**Comment by TPS** [comment]
I'm missing something.  Is this an Amazon restriction to not allow 2 identical apps to be published simultaneously.  Else, I'm thinking it's simple to have a release published under each ASIN simultaneously.…

**Comment by ameshkov** [comment]
It always take some time for them to review&publish new version.

Also every new test build is a real pain, you have to create new test manually, select testers, select devices, wait until binary is checked and such.

I mean really, publishing new stable version is easier than this:)

**Comment by TPS** [comment]
You'd think they'd make it easier for a _test_, which, after all, is opt-in, so testers are willing for risk, anyway.

I read there will be an urgent update soon, so I'll wait to see how _it_'s released & do that, probably.

**Comment by TPS** [comment]
@ameshkov @Revertron Thanks for the tester invite to .140! ☺  I think I've found an Appstore snafu, so am in contact with them about it.  As soon as that gets resolved, I'll install & get on our way. :smiley:

**Comment by ameshkov** [comment]
Disabled app update check for amazon build. With the current scheme it is too confusing.

**Comment by ameshkov** [comment]
@TPS i have pushed new release (2.1.267) to test in Amazon.

Could you please take a look at it once it is available?
If it's ok I will also push it to stable.

**Comment by TPS** [comment]
@ameshkov Send me the invite ASAP — [I really hope it fixes the major issues I'm having.](https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-153383133) :pray:

**Comment by ameshkov** [comment]
Test is submitted, I guess we should simply wait now

**Comment by ameshkov** [comment]
@TPS as I see in Amazon interface test update is available.

Now I've added this test properly and there is no need in re-inviting you:)

**Comment by ameshkov** [comment]
@TPS so how is the new test build? Can we push it to release?

**Comment by TPS** [comment]
@ameshkov Other than https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-153383133 , looks great (& the new test releas_ing_ worked perfectly!)

**Comment by ameshkov** [comment]
Thank you!:) Pushing it then.

**Comment by TPS** [comment]
@ameshkov For the many recently closed issues, I've received no _beta_ updates, not through Amazon nor directly (I run 1 each, as you may remember).  Have none actually been released?  I seem to remember a beta being mentioned in 1 of the recently completed issues.…

**Comment by ameshkov** [comment]
We are closing the issue when it's fixed in the code, it is not tied to a release.

But your question is just in time, release is here:
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/2.1.319

Should be available through amazon soon, now it is in "Publishing" status.

**Comment by TPS** [comment]
Got both, thanks!

**Comment by ameshkov** [comment]
@TPS btw, how do you check for Amazon updates?

Does appstore updates the app automatically or do you check invite link every time?

Here is a thread on our forum when one of beta testers has some issues with getting new beta via amazon:
http://forum.adguard.com/showthread.php?8074-Adguard-for-Android-Beta-version-2-1-319

**Comment by TPS** [comment]
I use Appstore app to check updates via "My Apps" → Refresh or simply just go to app listing.  The update notified there several hours, even after I got Amazon e-mail notification & the website version did (as you predicted).  That's just Amazon being slow, I think.  Have your forum Amazon beta folks try now;  if they can't get it, though I have, have them contact Amazon customer service.

**Comment by ameshkov** [comment]
@TPS thank you! I think it's just Amazon is slow indeed, let's see what happens with the next beta.

**Comment by TPS** [comment]
I notice you're updating the changelog on Amazon for the release builds.  Would it be possible to do the same for the _test_ builds?  I'd sure like to know what changed, so I can test it!

(Just received the Amazon notification for a new test, but Appstore hasn't caught up yet.  I'll keep you all posted.)

**Comment by ameshkov** [comment]
There's no such field there.

Yet there is a field named "What to test", we usually put changelog there.

**Comment by TPS** [comment]
I'm confused.…  Do you run the latest Appstore app?  Each app has 2 tabs now where there used to be just "Description"; the other is "Release Notes."  (On the website, it's a section called "Latest Updates: What's new in version" x.xx.)  You all have been using "Release Notes" (aptly) for that release's changelog, though only for the release build (http://smile.amazon.com/dp/B0158CTKR8), but not yet the test (http://smile.amazon.com/dp/B0158CTQ2C/).

I actually have never knowingly seen the field "What to test" nor its contents.…  Where does it appear?

**Comment by ameshkov** [comment]
Frankly I don't know, I see it in developer's interface only. Very amazon i must say.
