### ISSUE TITLE
Better ad blocking in some app if the same request is blocked by DNS request blocking

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#1021]
When certain domains are blocked, how it is handled by the app is different if it is blocked as usual and if it is blocked by DNS request blocking.

For example, com.xmobile.wowradio app shows an interstitial ad when starting the app.
If googleads.g.doubleclick.net domain is blocked by a usual url blocking rules, it shows an empty popup with black screen. If I enable DNS request blocking, the popup is not being opened at all.

Why does it happen?
Can we adjust our blocking methods so that empty popups are not shown? Can we add a modifier for a filter rule to change the blocking method?

**Comment by ameshkov** [comment]
> Why does it happen?

The difference is that in case of DNS-level ad blocking, it looks like a network error to the app.
In the case of regular ad blocking, it looks like a server error (status=500).

**Comment by ameshkov** [comment]
> Can we adjust our blocking methods so that empty popups are not shown? Can we add a modifier for a filter rule to change the blocking method?

Server error is often enough, apart from some rare cases.

Btw, what if you disable https filtering. Do you see that empty popup?
