### ISSUE TITLE
Manual VPN connections crashing when AG enabled 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardForAndroid#1022]
Adguard doesn't allow using other VPN connections (manually created). They start and then fail shortly because AG starts. 
This doesn't happen with VPN apps, only manually created connections. 

13:29
[debug (9).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/706475/debug.9.txt)

Ticket: 1051039

**Comment by ameshkov** [comment]
For some reason AG fails to detect running legacy VPN tunnel, and that's why it restarts itself immediately.

This is a bug for sure.

**Comment by Revertron** [comment]
Done.
