### ISSUE TITLE
[Filtering] Google ads are not blocked completely in apps

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1023]
For example: Bubble Blast 2 
https://play.google.com/store/apps/details?id=com.magmamobile.game.BubbleBlast2

`https://googleads.g.doubleclick.net/mads/gma?carrier=`
Should be blocked by `/googleads.`
It is marked as blocked in filtering log, but really it is loaded
http://imagizer.imageshack.com/img922/79/BB0OjX.png

Related issue in filters(with a log):
https://github.com/AdguardTeam/AdguardFilters/issues/4078
My log and HAR:
[adguard.har.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/706787/adguard.har.txt)
[adguard.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/706788/adguard.txt)

**Comment by ameshkov** [comment]
`||googleads.g.doubleclick.net/mads/gma?carrier=$replace=/\<script\>[\s\S]*\<\/script\>/,important`

**Comment by Alex-302** [comment]
Thanks.
But why not $replace rules are applied with different code, than ads=***1***?

**Comment by ameshkov** [comment]
@Alex-302 that's just how it works:)
