### ISSUE TITLE
mail.ukr.net visual bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1024]
URL: https://mail.ukr.net/touch#msglist

Screenshot: https://forum.adguard.com/index.php?attachments/screenshot_2017-01-14-14-28-55-png.6833/

This happens after logging in. For login/password PM me.

Looks like the problem is caused by HTTPS filtering.

Forum thread:
https://forum.adguard.com/index.php?threads/18676/#post-122619

**Comment by ameshkov** [comment]
I doubt it. It's more likely that the issue is caused by unnecessary injection @Alex-302

**Comment by Alex-302** [comment]
Not reproduced on my side.

**Comment by nkartyshov** [comment]
Source: https://forum.adguard.com/index.php?threads/%D0%92%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82-%D0%BA%D1%83%D1%81%D0%BE%D0%BA-%D0%BA%D0%BE%D0%B4%D0%B0-%D0%BF%D0%BE%D0%B2%D0%B5%D1%80%D1%85-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%BD%D0%B0-%D0%BF%D0%BE%D1%87%D1%82%D0%B5.18676/

**Comment by nkartyshov** [comment]
Done, review AJC-CR-187.
