### ISSUE TITLE
electricquilt.com - can't add something to cart

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1025]
http://electricquilt.com/online-shop/jelly-roll-quilt-magic/
can't add something to cart.
Response header is absent.
Fiddler say `HTTP/1.0 200 This buggy server did not return headers`

In Windows repository:
https://github.com/AdguardTeam/AdguardForWindows/issues/1498

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/1037
