### ISSUE TITLE
IPv4 mapped addresses bypass VPN

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#1026]
**Edit[ameshkov]:** cause for this issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/1026#issuecomment-303241856

----

There are many users reporting this. A user have to enable some low-level ipv6 settings (`pref.vpn.ipv6.disable`, `pref.vpn.ipv6.bypass`, `pref.proxy.block.ipv6`) to have all ads blocked.

A user have sent logs. The user is using a mobile carrier 'SK Telecom'. The user tested an app `com.dcinside.app` while collecting logs below.

----
**Local HTTP proxy mode** - ads were not blocked
[adguard3.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/710782/adguard3.log.txt)

**Local HTTP proxy mode & pref.proxy.block.ipv6 enabled** - The internet connection is completely broken. When the user turns off the Adguard protection, the internet connection remains broken, and the user have to disable and re-enable cellular data to connect to the internet.
[adguard4.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/710784/adguard4.log.txt)

**Local VPN mode & DNS request filtering enabled** - almost all ads are blocked except some.
[adguard5.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/710785/adguard5.log.txt)

**Local VPN mode & DNS request filtering enabled & pref.vpn.ipv6.disable enabled** - 
All ads are blocked.
[adguard6.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/710786/adguard6.log.txt)

**Local VPN mode & DNS request filtering enabled & pref.vpn.ipv6.bypass enabled** - Ad blocking result is the same as the case of _local VPN mode & DNS request filtering enabled_, i.e. enabling _pref.vpn.ipv6.bypass_ does not make any difference.
[adguard7.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/710787/adguard7.log.txt)

**Comment by ameshkov** [comment]
Here are some thoughts about it.

1. In adguard5.log I see DNS requests to `dcinside.com` subdomains, but I don't see actual connections and requests further.
2. On the contrary, in adguard6.log I see both DNS requests and actual connections.

The only thing I have in mind is that `dcinside.com` are resolved to some local IPv6 addresses, hence not covered by AG routing.

Here is what we should do to check if I am right:

1. Extend DNS requests logging. We should also log DNS response content.
2. Change default routing for IPv6 network and cover local addresses as well.

**Comment by seanl-adg** [comment]
Let me know when a new build comes out!

**Comment by ameshkov** [comment]
Necessary changes will be available in the beta version.

Most of all I am interested in this case: **Local VPN mode & DNS request filtering enabled**

**Comment by ameshkov** [comment]
@seanl-adg is there any update on this issue with the new beta version release?

**Comment by ameshkov** [comment]
Reassigned to v2.10

**Comment by seanl-adg** [comment]
The same user have sent another set of logs.

Configurations were the same, the tested app is `com.dcinside.app` and the mobile carrier's name is SK Telecom.

----
**Local HTTP proxy mode** - ads were not blocked, there is no sign of blocking in the filtering log too.
[1.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/989491/1.txt)

**Local HTTP proxy mode & pref.proxy.block.ipv6 enabled** - The internet connection is completely broken. When the user turns off the Adguard protection, the internet connection remains broken, and the user have to disable and re-enable cellular data to connect to the internet.
[2.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/989494/2.txt)

**Local VPN mode & DNS request filtering enabled** - Google ads are blocked. An ad which should be blocked by `||dcinside.com/api/_ad_search_link.php^` wasn't blocked. Some other ads weren't blocked.
[3.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/989495/3.txt)
![3](https://cloud.githubusercontent.com/assets/22858651/25895044/3cc3a65e-35b9-11e7-9775-3282248bd761.png)

**Local VPN mode & DNS request filtering enabled & pref.vpn.ipv6.disable enabled** - 
All ads are blocked.
[4.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/989496/4.txt)
![4](https://cloud.githubusercontent.com/assets/22858651/25895053/3f839e94-35b9-11e7-8baf-a6b1e1020a55.png)

**Comment by ameshkov** [comment]
The log is so freaking weird, as if the whole 121.* subnet was not filtered.

**Comment by ameshkov** [comment]
Okay, I've got an idea.

Here are some key points:

1. By default, we add the following IPv6 route: `2000::/3` which covers all the public IPv6 addresses.
2. I see 6-4 and 4-6 tunnel network interfaces in the log (`ip6tnl0` and `sit0`).
3. I see that `m.dcinside.com` is resolved to `121.125.60.186`
4. I don't see any connections to `121.*` subnet in the log as if nothing was routed through the VPN

What if IPv4 packets are being sent over a 4-6 tunnel. In this case, `121.125.60.186` would have been mapped to `0:0:0:0:0:FFFF:797D:3CBA` and therefore it would have bypassed our IPv6 route (see point 1)?

To check the idea we should add one more route for IPv6 to cover IPv4-mapped addresses.

**Comment by ameshkov** [comment]
@seanl-adg could you please ask user to test it with the latest beta version (and with default low-level settings)?

I've added IPv4-mapped addresses to VPN routes, so if I was right, the issue should be resolved now.

**Comment by ameshkov** [comment]
@seanl-adg anything new?

**Comment by ameshkov** [comment]
It appears that my hack does not work (IPv4-mapped route was transformed to IPv4 anyway), I will look for a better solution.
```
06-22 20:53:11.328 604-665/? E/Netd: parsePrefix failed for destination 0.0.0.0/96 (Invalid argument)
```

**Comment by ameshkov** [comment]
Added `::8000:0:0/81`.

**Comment by ameshkov** [comment]
@seanl-adg here is a newer build with proper routes:
[adguard_2.9.125_dev.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1102882/adguard_2.9.125_dev.apk.zip)

Could you please ask people who suffer from the issue to test it?

**Comment by ameshkov** [comment]
No updates for quite some time, closing it.

**Comment by ameshkov** [comment]
Reopened due to https://github.com/AdguardTeam/AdguardForAndroid/issues/1393#issuecomment-325589102

**Comment by ameshkov** [comment]
@veronikasav 
> Ticket ID: 1620465

Please ask the user if he's ready to try a test build and collect logs for us?

**Comment by veronikasav** [comment]
@ameshkov The user is ready. Which log exactly should we ask to collect?

**Comment by evgeniy-ADG** [comment]
@ameshkov

**Comment by vozersky** [comment]
@veronikasav @evgeniy-ADG Adguard's "record everything" level log, just make sure not to send it to support from the app itself, but export it using the new beta's export feature and send by mail

**Comment by ameshkov** [comment]
Guys, the test build will be ready today

**Comment by ameshkov** [comment]
Here you are:
[adguard_issue1026_test1.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1284444/adguard_issue1026_test1.apk.zip)

**IMPORTANT:** I need to get the "record everything"-level log with this test build

**Comment by evgeniy-ADG** [comment]
sent to the customer

**Comment by ameshkov** [comment]
@evgeniy-ADG anything?

**Comment by ameshkov** [comment]
Please reopen if any new information appears
