### ISSUE TITLE
Getting rid of tumblr ads?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1028]
I have already unpinned the certificate but still see sponsored tweets etc.

**Comment by TPS** [comment]
This issue seems to duplicate 1 or more of https://github.com/AdguardTeam/AdguardFilters/issues?q=tumblr, else likely should be filed _there_, anyway, right, @Bluscream?

**Comment by Bluscream** [comment]
I don't know since its a app and not a website

**Comment by TPS** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/1634?

**Comment by Bluscream** [comment]
Its closed tho

**Comment by TPS** [comment]
I figure @ameshkov or @Alex-302 will steer this right when they get to it. ☺

**Comment by ameshkov** [comment]
Yep, we have to reopen that issue.

**Comment by Alex-302** [comment]
@Bluscream @TPS please check the rule from
https://github.com/AdguardTeam/AdguardFilters/issues/1634

**Comment by Bluscream** [comment]
No success even after restarting the protection and clearing tumblrs cache
