### ISSUE TITLE
Update "blocked" pages markup

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1029]
Pages are now responsive and retina-ready.

[Archive-fixed.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/729987/Archive-fixed.zip)

**Comment by nkartyshov** [comment]
Done, review: AJC-CR-154

**Comment by Bluscream** [comment]
Please don't hardcode them yn  s

**Comment by ameshkov** [comment]
@Bluscream this is about Android, so they are saved in the `apk` resources.
