### ISSUE TITLE
Firewall feature requests

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#1031]
please add:

1. a background data restrictions in firewall. similar to the "noroot data firewall application by simple good mobile".
this helps to block so many android sneaky system apps which stole data in the background. they can still access internet in foreground...

2. adguard request user to set rules when an app launched and trying to access to the internet and rules are: allow, block background and block which can be chosen from notification.

3. a button for firewall app management in home next to the manage license.

4. a button to disable firewall to let users use another firewall (not sure if it's possible...).

thanks in advance.

**Comment by ameshkov** [comment]
> a button to disable firewall to let users use another firewall (not sure if it's possible...).

The purpose of having firewall features in AG is that you can't use other VPN-based firewall app along with AG:(

**Comment by ameshkov** [comment]
> a button for firewall app management in home next to the manage license.

It'd be better to review this feature request after v3.0 release as there'll be a major redesign.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
