### ISSUE TITLE
All browser and app traffic is blocked after some time of using Adguard

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1033]
Original thread:
https://forum.adguard.com/index.php?threads/18960/

Logs are at 1495952

**Comment by vbagirov** [comment]
The user claims that disabling Adguard prevents the issue from recurring. Anything else we might do here or ask the user for?

**Comment by nkartyshov** [comment]
@vbagirov I found Dr. Web in apps list. Maybe ask user turned off the app.
