### ISSUE TITLE
Neuronation app - randomly appearing certificate notification

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#1034]
**Steps to reproduce:**

Install the [app](https://play.google.com/store/apps/details?id=air.nn.mobile.app.main&hl=ru) 
Settings -> HTTPS filtering
Install the certificate

After accepting Adguard certificate the notification appears again and again randomly

Screenshot: http://prnt.sc/e2nbwv

Disabling HTTPS filtering for this app helps

User ID: 1140661

**Comment by nkartyshov** [comment]
done
