### ISSUE TITLE
HSTS 

### ISSUE THREAD

**Issue by devwhatsapp** [AdguardTeam/AdguardForAndroid#1035]
Hi

Adguard Installed

Certificate installed using - [https://github.com/AdguardTeam/AdguardForAndroid/issues/334#issuecomment-231746426](url)

Currently apps using https are working fine , but chrome or internet showing hsts issue - [http://i.imgur.com/JQ0EtGB.jpg](url)

Please help

Edit #1 - Actually I just realized that app ads are not being blocked at all.

**Comment by vozersky** [comment]
@devwhatsapp hi! what exactly error did you see in browser?
