### ISSUE TITLE
[Feature request] [Firewall] An option to disable/enable selected hosts sources for a particular site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1036]
An option to disable/enable selected hosts sources for a particular site. For example lets say forbes detects adguard. Lets say I disable easylist and forbes cannot detect the adblocker. But the ads are still blocked with other lists such as Peter Lowe's list. But the problem here is that easylist is disabled on all sites and Peter Lowe's list will miss ads on other sites. In short an option to disable easylist on one site, but easylist is enabled on the rest of the sites.

ID: 1496347

**Comment by vozersky** [comment]
moved to filters
