### ISSUE TITLE
[Idea] Change "Filter DNS requests" algorithm

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1038]
Here is what AG currently does:
1. It uses VPN API to change system DNS to some fake IP address (121.121.121.121).
2. AG intercepts requests to these fake IP addresses and check if a host is blocked or not.
3. If the host is not blocked, we redirect request back to the real DNS server.

**Problems**

1. Changing VPN settings might cause issues with the Download Manager app: https://github.com/AdguardTeam/AdguardForAndroid/issues/597#issuecomment-275905961
2. We have to keep an eye on current DNS settings and refresh it's configuration from time to time.

**Solution**

1. Do not use fake IP addresses at all. Just filter all requests to `XXX:53`
2. Also, we'd better return `NXDOMAIN` instead of `127.0.0.1`

**Comment by ameshkov** [comment]
@Revertron @nkartyshov guys, I need your expertise. What do you think about suggested change?

**Comment by ameshkov** [comment]
Reminder: @bendingtime is willing to test this change: https://github.com/AdguardTeam/AdguardForAndroid/issues/597#issuecomment-276701043

**Comment by Revertron** [comment]
I can not remember it exactly, but there was some problem with _not setting DNS_ at all, but if we set DNS server/s that we got from DHCP, I think we can do it.

**Comment by ameshkov** [comment]
@Revertron I am not sure if it would be OK. It seems, that making literally any change to the DNS settings causes that Download Manager issue.

> but there was some problem with not setting DNS at all

Was it? I mean we don't do it by default and it works ok.

**Comment by Revertron** [comment]
Argh!!! No! The main problem is that we have to set DNS server outside _home network_, because otherwise all DNS requests will go around VPN.

**Comment by ameshkov** [comment]
Good catch, now I got it!

I guess, the other option would be to explicitly add DNS servers addresses to the VPN routes.

**Comment by Revertron** [comment]
But if the user has DNS server 192.168.1.1 (a home router) and has some another service on the router, it will make some problems, and we would be better to not filter local area connections.

**Comment by ameshkov** [comment]
You have a point indeed.

**Comment by ameshkov** [comment]
There is a problem with refactoring DNS filtering in light of this issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/1000

Also, frankly, I like the current scheme more:) If only there was no download manager issue. On the other hand, I can't reproduce this issue in my case. Maybe it's gone already?

**Comment by bendingtime** [comment]
@ameshkov It means that there will be no solution till now?

**Comment by ameshkov** [comment]
@bendingtime waiting for @Revertron opinion on this.

Meanwhile, I can create a test build and see how it goes. It won't take much time.

Btw, what type of device do you have?

**Comment by bendingtime** [comment]
Oneplus3T

thx in advance

2017-02-14 13:33 GMT+01:00 Andrey Meshkov <notifications@github.com>:

**Comment by ameshkov** [comment]
@bendingtime and what's the exact Android version?

**Comment by bendingtime** [comment]
7.0

2017-02-14 13:37 GMT+01:00 Andrey Meshkov <notifications@github.com>:

**Comment by TPS** [comment]
> Meanwhile, I can create a test build with proposed scheme and see how it goes. It won't take much time.

Why not implement the alternative algorithm, but enable it _only_ via Low-level Setting for those of us on the ß-builds willing to try it?  That way, you'll get enough in-the-wild data to see if it's worth deploying more widely.

**Comment by bendingtime** [comment]
Fair enough, what should I do to test it?

**Comment by TPS** [comment]
> On the other hand, I can't reproduce this issue in my case. Maybe it's gone already?

I don't run into this w/ GPlay or GDrive anymore, but AG still blocks phone software updates from my phone manufacturer & offline translation packages for GTranslate.

**Comment by Revertron** [comment]
> I don't run into this w/ GPlay or GDrive anymore, but AG still blocks software updates from my phone manufacturer & offline translation packages for GTranslate.

I think that is the problem with some filter rule.

**Comment by ameshkov** [comment]
@bendingtime bad news. It seems, that DNS filtering is impossible unless we configure DNS settings.

The problem is that DNS requests to the default DNS server are not routed through the VPN whatever routes configuration I try.

I guess the only way left is to continue nagging Google about this issue:
https://code.google.com/p/android/issues/detail?id=213341
https://code.google.com/p/android/issues/detail?id=33666

**Comment by bendingtime** [comment]
@ameshkov So back to kicking google...in the double o's :)
