### ISSUE TITLE
Feature request: add "dark" theme

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#104]
User request

**Comment by TPS** [comment]
+1 :+1:  Yes, _please_!

**Comment by Nick-White** [comment]
+1 Our AMOLED screens will thank you.

**Comment by ameshkov** [comment]
Huh, there're 3 of you already, that's unexpected:)

Ok, we'll take this into account when we do the app redesign.

**Comment by TPS** [comment]
Good job the whole 3 of us! I know we represent thousands, nay, _meeeeelions_!  :clap: :tada: :birthday: … :stuck_out_tongue_winking_eye:

**Comment by JonnyRedHed** [comment]
Good news to here this is something the devs are thinking about.  A material design dark theme inc maybe also one for black AMOLED screens.

**Comment by TPS** [comment]
@Nick-White did bring that up, also.…  As much actual black as possible works best for AMOLED, @AdguardTeam.

**Comment by JonnyRedHed** [comment]
I have an AMOLED so that would be good.  But sometimes I do also prefer a dark grey.  Black with very white test can also hurt ones eyes.  If the text is toned down, then black AMOLED will work better in low light and at night.

**Comment by Bluscream** [comment]
3.0 will be the huge UI overhaul i assume?

**Comment by ameshkov** [comment]
You can take a look:
https://blog.adguard.com/en/adguard-android-3-0-first-glance/

**Comment by TPS** [comment]
I hafta say, that post is ___VERY___ pretty, & the sheer # of commenters promising purchasing the lifetime license must be quite encouraging. ☺

**Comment by Bluscream** [comment]
yeah xD

**Comment by JonnyRedHed** [comment]
When are we seeing the Dark material themes for Android and the Windows software?  2018 now.

**Comment by JonnyRedHed** [comment]
We are all still waiting for dark themes across windows and android.

**Comment by ameshkov** [comment]
Well, you can get it on Android right now in the beta version:
https://github.com/AdguardTeam/AdguardForAndroid/releases

And on Windows, you'll get it right when the v7.0 reaches the nightly channel.
