### ISSUE TITLE
Swype keyboard - the HTTPS issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1040]
The app doesn't load language list unless the HTTPS filtering for it is disabled:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22624507/2fbb6e24-eb86-11e6-8589-880a9eb3b458.png)

</details>

https://play.google.com/store/apps/details?id=com.nuance.swype.dtc&hl=en
https://play.google.com/store/apps/details?id=com.nuance.swype.trial&hl=en

**Comment by vozersky** [comment]
@evgeniy-ADG can't reproduce.

**Comment by evgeniy-ADG** [comment]
I was able to reproduce it on my phone. Seemed to work after HTTPS had been disabled. Here's the ticket: 1317328

**Comment by nkartyshov** [comment]
I added this app in httpsexclusion
