### ISSUE TITLE
Ecobee app - the HTTPS filtering issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1041]
https://play.google.com/store/apps/details?id=com.ecobee.athenamobile&hl=en

![screenshot_20170203-173658](https://cloud.githubusercontent.com/assets/15856304/22624858/9971755c-eb90-11e6-81ba-da2e0ad13114.png)

**Comment by vozersky** [comment]
@evgeniy-ADG  can't reproduce. Https-filtering is not a culprit here. Where does it come from? Details?

**Comment by evgeniy-ADG** [comment]
1442915, costomer reported that disaling HTTPS helps.

**Comment by nkartyshov** [comment]
I added this app in httpsexclusion
