### ISSUE TITLE
[Feature request] Add start\stop protection button to notification

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#1045]
Hi,

Could you please add buttons in notification dropdown to conveniently start/pause Adguard? So that we don't have to open Adguard app itself to do so, like what for example Hotspot Shield is doing.

Thanks.

**Comment by vozersky** [comment]
@snhv hi! thanks for the request. 

If you press on start protection/pause on notification, HotspotShield opens the app interface anyway though. 

I think we might even be able to do it without opening the app. 

<details><summary>This is how it looks in HSS:</summary>

![screenshot_20170210-173822](https://cloud.githubusercontent.com/assets/17472907/22830812/f1c757cc-efb8-11e6-9005-ba537ae96eb9.png)

</details>

**Comment by Revertron** [comment]
I think we can add a button like "Turn On/Turn Off" to notification, it would be relatively easy.

**Comment by ameshkov** [comment]
Dup of #1614
