### ISSUE TITLE
Compatibility with other VPN apps

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1046]
* ZenMate 2.4.6 revokes VPN rights from other VPN using apps. 
Reported to devs.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1044

**Comment by ameshkov** [comment]
What about other apps? Let's have a compatibility table.

**Comment by vozersky** [comment]
Since you can only have one VPN  connection at a time on Android,  let's define what we call a "compatibility" first. Switching VPN rights from 3rd party app to Adguard and visa-versa without any trouble?

**Comment by ameshkov** [comment]
Let's define "Compatible" as "no issues having both apps installed".
So, Zenmate and Hotspot are clearly incompatible then.

**Comment by vozersky** [comment]
Hotspot is actually fine

**Comment by ameshkov** [comment]
Nevertheless, I guess you got the idea:)

**Comment by KozelElena** [comment]
We have got several complaints about the compatibility with Dr.Web's firewall:

Adguard works fine in VPN mode, but after enabling HTTP proxy mode in Adguard and VPN in Dr. Web the internal error occurs. 

Adding Adguard to exceptions of Dr.Web didn't help
We have logs for both cases.

Ticket IDs: 1531838, 1534510

**Comment by ameshkov** [comment]
> Adguard works fine in VPN mode, but after enabling HTTP proxy mode in Adguard and VPN in Dr. Web the internal error occurs.

You should also disable filtering for DrWeb completely (in the apps management), have you done it?

**Comment by Michael23456** [comment]
forwarded to the customers 1531838 and 1534510. Waiting for results

**Comment by OlegSUP** [comment]
User 1531838:
Отключил как вы и советовали полностью фильтрацию для доктор веб, не
помогло. конфликт так и остался.

**Comment by Darina655** [comment]
User 1531838: Disabled HTTPS filtering for Dr. Web
Nothing has changed.

**Comment by ameshkov** [comment]
@vozersky need you to test it.

**Comment by vozersky** [comment]
was able to reproduce:

[adguard (4).log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/937065/adguard.4.log.zip)


STR:
1. Install Adguard and activate protection (VPN mode).
2. Install [Dr. Web](https://play.google.com/store/apps/details?id=com.drweb.pro&hl=en), activate trial license and enable firewall.
3. Now configure manual proxy and try to enable protection in Adguard.

Expected result: Protection activated.
Actual result: error: "An error occured during this operation. Please try again later..."

**Comment by ameshkov** [comment]
Assigned to v2.10
