### ISSUE TITLE
kr.mappers.AtlanSmart - map does not load

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#1047]
App link:
https://play.google.com/store/apps/details?id=kr.mappers.AtlanSmart

https://apkpure.com/3d%EC%A7%80%EB%8F%84-%EC%95%84%ED%8B%80%EB%9E%80-%EB%82%B4%EB%B9%84%EA%B2%8C%EC%9D%B4%EC%85%98/kr.mappers.AtlanSmart

With Adguard enabled: <details>

![](https://cloud.githubusercontent.com/assets/22858651/22846745/4f7ba27e-f02c-11e6-879d-e423b0036644.png)

</details>

Disabled: 

<details>

![](https://cloud.githubusercontent.com/assets/22858651/22846748/5a7a3a28-f02c-11e6-9605-e4fc209259c0.png)

</details>
Even if all filters are disabled and HTTPS filtering for the app is disabled, the map does not load.
If I disable Ad blocking for the app in Apps Management section, the map loads.

**Comment by ameshkov** [comment]
@seanl-adg does the app have any ads?

**Comment by seanl-adg** [comment]
The app does not have ads. It has some trackers (crashlytics)

**Comment by nkartyshov** [comment]
I disabled ad-blocking filter for app. 
@Alex-302 Please, add rule `||crashlytics.com^$app=kr.mappers.AtlanSmart` in Mobile Filters.

**Comment by ameshkov** [comment]
@nkartyshov it won't work anyways if ad blocking is disabled.

What is the culprit?

**Comment by Alex-302** [comment]
@nkartyshov 
> Please, add rule ||crashlytics.com^$app=kr.mappers.AtlanSmart in Mobile Filters.

this app works on my side only when ad blocking is disabled for this app.

**Comment by nkartyshov** [comment]
The problem is not the correct http request. The request contains an extra space.

**Comment by nkartyshov** [comment]
Done, Review AJC-CR-169
