### ISSUE TITLE
rchat app - can't block ads

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1050]
https://play.google.com/store/apps/details?id=net.devking.randomchat.android
Screenshots:
<details>

![screenshot_20170211-061622](https://cloud.githubusercontent.com/assets/15856304/22861712/c4a28368-f128-11e6-8ee6-f5a5206f4a17.png)
![screenshot_20170211-054202](https://cloud.githubusercontent.com/assets/15856304/22861713/c62be33c-f128-11e6-9c83-1a15cffdb6ef.png)
</details>
They are using nonstandard ports. Tried to add `10606,11000,1130,12401,12403,15151,5220,8200`, but the app is not working in this case.

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/4361

**Comment by ameshkov** [comment]
Let's re-test it once new version is ready.

**Comment by Alex-302** [comment]
ok, waiting for it

**Comment by ameshkov** [comment]
@Alex-302 how is it now?

**Comment by Alex-302** [comment]
Ads are blocked.
