### ISSUE TITLE
TouchPal app ads

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardForAndroid#1051]
With the last update of  TouchPal app ads appear on top of all windows.

TouchPal should have access to the Internet. The icon on the desktop redirects to a webpage.

![screen shot 2017-02-14 at 6 14 19 am](https://cloud.githubusercontent.com/assets/25342327/22915266/a45a084a-f27e-11e6-955f-ef914665b5f2.png)

![screen shot 2017-02-14 at 6 14 38 am](https://cloud.githubusercontent.com/assets/25342327/22915146/dd4d388a-f27d-11e6-9761-93ed4da4be7b.png)
![screen shot 2017-02-14 at 6 14 50 am](https://cloud.githubusercontent.com/assets/25342327/22915148/e05acaba-f27d-11e6-8e8e-66b6a7d5e41f.png)

https://play.google.com/store/apps/details?id=com.cootek.smartinputv5&hl=en
Filters 2, 3, 4, 14, 1, 11
versionName" : "2.8.76
androidVersion" : "5.1

Customer ID 670455

**Comment by vozersky** [comment]
@oprotsyk  https://github.com/AdguardTeam/AdguardFilters
