### ISSUE TITLE
Samsung Theme store shows SSL error after updating to Nougat

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1059]
Old issues:
https://github.com/AdguardTeam/AdguardForAndroid/issues/571

User report:
https://forum.xda-developers.com/showpost.php?p=71102412&postcount=2131

**Comment by nkartyshov** [comment]
@vozersky Please, check this problem. I cannot reproduce.

**Comment by vozersky** [comment]
@nkartyshov 
Can't reproduce with Adguard 2.8.76 on s7
"Samsung Themes" works fine.
