### ISSUE TITLE
Integrate common URL filtering library

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/AdguardForAndroid#1061]
We have an URL filtering library in development, now it's a good time to start integrating it into android code.

**Comment by ameshkov** [comment]
How is it going with the JNI adapters?

**Comment by hmage** [comment]
So far no big problems, things are going smoothly. 

Talked with @sfionov how to do it properly and we agreed that since we haven't decided how to keep code from two different repositories talking to each other yet, I'll just duplicate a copy of URL filtering library into android repository and then remove the duplicates once we decide on repository hierarchy.

**Comment by ameshkov** [comment]
Done (branch feature/1061).

Result:
1. Basic rules matching is considerably faster now.
2. Memory usage is more or less the same. However, no more java heap allocations should be better for overall performance.
3. This is the first step to have a single centralized filtering engine which will be used by all AG versions.
