### ISSUE TITLE
Add "Bulk change" item to the Apps Management menu

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1063]
Here is what we need:

1. Add "Bulk change" item below the "Settings" item.
2. Tapping "Bulk change" brings up a dialog:
<details>

![online mockup 2c wireframe 26 ui prototyping tool c2 b7 moqups 2017-02-22 00-58-21](https://cloud.githubusercontent.com/assets/5947035/23186954/0c0b7fb6-f89a-11e6-8090-ef003186c300.png)
</details>

**`Preference`** can be 
* `Enabled`
* `Cellular data`
* `Wi-Fi data`
* `Cellular data when screen is off`
* `Wi-Fi data when screen is off`
* `Firewall notifications`

**`Status`** is either `Enabled` or `Disabled`

**`Apps filter`** can be:
`All apps`
`Browsers`
`Not browsers`

**Comment by TPS** [comment]
Implements #911/#928?

**Comment by ameshkov** [comment]
@TPS yup, this covers both, thank you for linking those issues!

**Comment by nkartyshov** [comment]
done
