### ISSUE TITLE
Add brotli support

### ISSUE THREAD

**Issue by confessor-adguard** [AdguardTeam/AdguardForAndroid#1064]
Details: https://github.com/AdguardTeam/AdguardForWindows/issues/1545

**Comment by ameshkov** [comment]
I guess we'd better do this in CoreLibs

**Comment by TPS** [comment]
@ameshkov Is there a corresponding issue in CoreLibs someplace?  I may have some data to relay that may increase the priority of this, @ least for Android.

**Comment by TPS** [comment]
Nm, I found https://github.com/AdguardTeam/CoreLibs/issues/8
