### ISSUE TITLE
[enhancement] date stamp release notes

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1065]
Now it's 'yesterday' which is not informative

![image](https://cloud.githubusercontent.com/assets/15856304/23213858/4914db7a-f915-11e6-8f0b-d3c0a4ec92d5.png)

**Comment by ameshkov** [comment]
@vozersky it makes sense to change the wording.

**Comment by vozersky** [comment]
fixed

**Comment by vbagirov** [comment]
Changed the wording.

We can use specific dates instead of words like 'yesterday', 'recently' etc. in the future.
