### ISSUE TITLE
Add "License key" activation intent support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1066]
Here is an example:

```
adb shell am broadcast -a com.adguard.android.LICENSE_KEY -n com.adguard.android/.LicenseKeyBroadcastReceiver -e LicenseKey [key_is_here]
```

**What's important, we need it to be implemented in v2.8 as well!**

* `com.adguard.android.LICENSE_KEY` - Action.
* `LicenseKeyBroadcastReceiver` - broadcast receiver class name.

@nkartyshov also, do not show "Get premium" onboarding screen when Adguard is activated already.

**Comment by TPS** [comment]
Will this work for both Amazon & website versions?

**Comment by ameshkov** [comment]
I guess I should explain why do we need it.

The only purpose of this intent is to provide a way to automate Adguard activation. This is important for distributors and retailers, selling AG. Currently, a manager have to explain and maybe even manually enter a license key for a customer, while the whole process could be easily automated.

**Comment by TPS** [comment]
So, this means sales _directly_ from you all, via distributor/retailer account?
 
However, if they chose to do so, they'd could keep up an Amazon subscription, through its own mechanism?  (I could see such businesses, from [_their own_ Amazon account](https://www.amazon.com/b2b/info/features?layout=landing), selling/giving away kind-of gift subscriptions, in conjunction w/ or as bonus for their own product.)

**Comment by ameshkov** [comment]
> So, this means sales directly from you all, via distributor/retailer account?

Not directly. Normally, a distributor signs a contract with us and acquires license keys, then it sells keys to its partners (retailers or whatever). So, this feature is requested by the retailers to make managers life easier.

> However, if they chose to do so, they'd could keep up an Amazon subscription, through its own mechanism?

It works a bit differently. I reckon you don't have anything like that in the US, so I'll try to explain you the whole process.

Imagine you go to a Bestbuy to choose a new smartphone. You've found one that suits you best, and after that, a manager offers you something in addition. It might be insurance, support service, hardware, software or whatever.

So, in the case I am talking about, manager tries to upsell you an "improvement package", which might include insurance, initial phone setup and installation of the necessary software and maybe something more. The software package includes both free and paid apps (usually with a discount to the regular price), whatever retailer thinks to be necessary. The whole process of setting a device up and installing/activating all the software is rather time-consuming, so they are trying to make it as automatic as possible.

**Comment by TPS** [comment]
> I reckon you don't have anything like that in the US

I think, as other examples, a US device manufacturer would bake AG into the ROM as pre-installed, or an app-package developer/retailers would link AG,  & then distribute perhaps giftcodes/license-key for 1 year subscription or some such, as you mentioned.

However, in the case of such _also_ incorporating Amazon ecosystem, many might wish to go Appstore/Underground route, which is why I asked.  (Not to get in way of _this_ method, but to put potential Amazon method on radar.)

**Comment by ameshkov** [comment]
> I think, as other examples, a US device manufacturer would bake AG into the ROM as pre-installed, or an app-package developer/retailers would link AG, & then distribute perhaps giftcodes/license-key for 1 year subscription or some such, as you mentioned.

Yep, possible, didn't think about it that way:)

> However, in the case of such also incorporating Amazon ecosystem, many might wish to go Appstore/Underground route, which is why I asked.

It seems to me, that Amazon ecosystem is currently used solely by Amazon:)

**Comment by TPS** [comment]
> It seems to me, that Amazon ecosystem is currently used solely by Amazon:)

I dunno, all my non-Google, non-Amazon devices have @ least 1 Amazon app pre-installed, & they all advertise either [Underground](https://www.amazon.com/gp/feature.html?docId=1003016361) or [Alexa](http://phx.corporate-ir.net/phoenix.zhtml?c=176060&p=irol-newsArticle&ID=2062557) pretty heavily, each of which heavily uses Amazon's payment system.

Just an idea, anyway. ☺

**Comment by nkartyshov** [comment]
done
