### ISSUE TITLE
Add "Watchdog period" advanced setting

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1067]
Caused by this:
https://forum.xda-developers.com/showpost.php?p=71106062&postcount=2134
id 1471897

The problem is, that in some cases nothing helps, Android does kill Adguard from time to time.

We might implement an optional solution, some sort of a "watchdog", checking if Adguard process is running periodically.

Section: `Advanced`
Name: `Watchdog period`
Default value: `0 (disabled)`
Possible values: integer

Looks like:
*Watchdog period*
Current: 60 sec.
Period to check if Adguard is still running. Please mind, that it might cause extra battery usage.

**Comment by Revertron** [comment]
Done, review is AJC-CR-173.

**Comment by Revertron** [comment]
Done.
