### ISSUE TITLE
Notification on a new app installation

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/AdguardForAndroid#1069]
We could display a notification when a new app is installed, from where users can choose whether Adguard should block ads in the app. We can display some text like `do you want adguard to block ads in this app?`
This can be a convenient solution for user needs like this - https://www.reddit.com/r/Adguard/comments/5uys91/adguard_android_app_how_to_set_default_not_to/

Inspired by a behavior of `ES file explorer`: when a new app is installed, it displays a notification saying something like `New app installed! Tab here to analyze the app`

**Comment by ameshkov** [comment]
Personally, I like the idea. However, we should think how to make AG insights really useful for a user.

I see two options here:

1. Display this notification after some time, when we have collected enough data about the app.
2. Get the information about the app from our server.

**Comment by TPS** [comment]
There are apps I _know_ I want to run offline *only*, so adding an option to notify whether blocking all traffic from a newly installed app (_before_ 1st run) would be excellent.

**Comment by r0lZ** [comment]
I second this suggestion.  Adaway has that feature, and I miss it in Adguard.  It's very useful to quickly configure the firewall and ad blocking of the newly installed app. 
I don't see the reason to delay the notification, as ameshkov suggests.  Usually, we want to block adds anyway,  and we know if mobile data and/or wifi should be allowed, so there is no need to wait.  However, a delay might be useful, as long as it is configurable, and can be set to 0.
Please implement it.  Thanks in advance!

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379

**Comment by temp272** [comment]
@ameshkov I'd advise against adding this feature. If you give a notification each time a new app is installed or reinstalled it'll definitely annoy users. Nobody needs to be interrupted like this. This behaviour should not be default, it could be an optional features that users can enable inside the app or you may even remind them to enable it after sometime after AdGuard is installed. 

And don't take UX inspirations from ES file explorer its UX was not the best, in fact I'd say it never followed Android UX guidelines properly. That app was really annoying with its notifications. 

Notifications are annoying, they disturb the user from what they are currently doing, nobody wants them.
