### ISSUE TITLE
Add com.google.android.apps.authenticator2 to net exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#107]
http://forum.adguard.com/showthread.php?7283-Adguard-for-Android-Beta-version-2-1-191&p=63529&viewfull=1#post63529

**Comment by TPS** [comment]
@ameshkov @Revertron I actually recommend **heavily** _against_ this, as Authenticator is designed to be be run solely offline, & it is actually an excellent idea to have a firewall to _prevent_ any network access whatsoever — it enhances security!  This is 1 specific major reason I love this firewall. ☺

**Comment by ameshkov** [comment]
@AwesomeDonkey what do you think about @TPS comment?

**Comment by AwesomeDonkey** [comment]
Hmmm, I guess TPS is right.

**Comment by ameshkov** [comment]
Ok then, unless AG does not break authenticator, let's leave it:)
