### ISSUE TITLE
Adg blocks internet access with Mobile network

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#1070]
Adg blocks internet access when the customer is using mobile network, Wi-fi works fine

the same issue with proxy mode and VPN 

no internet in the applications and browsers while using ADG

Screenshot:
<details>

![screenshot_2017-02-21-12-23-27](https://cloud.githubusercontent.com/assets/22892774/23382899/b0db9132-fd4c-11e6-8093-4b85aac6adb0.png)

</details>

[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/805188/debug.1.txt)

>21:53 – доступ к сайту google.com при включённом Wi-Fi – доступ есть

>21:54 – доступ к сайту google.com при выключенном Wi-Fi (через мобильную сеть) – доступа нет

>21:55 – доступ к сайту google.com при выключенном Wi-Fi (через мобильную сеть) через сторонний браузер – доступа нет

LogCat is here:
Ticket ID: 1062749

**Comment by ameshkov** [comment]
We should ask user to check it with the beta version when it's out.
I expect it to be ready tomorrow.

**Comment by ameshkov** [comment]
@Yana-SUP @vozersky 

Beta version is out. Please ask user to test with it and to collect debug log as well

**Comment by Yana-SUP** [comment]
@ameshkov 
Done, waiting for the results
Thank you

**Comment by ameshkov** [comment]
@Yana-SUP is there any update?

**Comment by Bohdan-SUP** [comment]
No reply yet. I'll ask again.

**Comment by ameshkov** [comment]
Reassigned to v2.10 for now, waiting for the response

**Comment by evgeniy-ADG** [comment]
> Проверил на бета-версии (2.9.17), всё аналогично, связи нет.

1062749

**Comment by ameshkov** [comment]
@evgeniy-ADG I need debug log with version 2.9.70.

**Comment by ameshkov** [comment]
Oh, and one more thing. Check the obvious first -- does he have "Restrict Background Data" enabled?

**Comment by Yana-SUP** [comment]
@ameshkov asked the user, waiting for the reply

**Comment by ameshkov** [comment]
Closed as "cannot repro"
