### ISSUE TITLE
kr.co.nowcom.mobile.afreeca - app freezes on launch

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#1071]
Play store link: https://play.google.com/store/apps/details?id=kr.co.nowcom.mobile.afreeca

Steps to reproduce:
 1. Install and launch the app.
 1. It will try to display an interstitial ad. There will be a black screen with a loading spinner. 
 1. The app freezes. I have to escape by pressing the home button and tab it again in 'recently used apps' to use the app.

Disabling 'Ad blocking' and 'HTTPS filtering' for the app in 'App Details' section doesn't make any change. Disabling the app from routing eliminates the issue.

**Comment by nkartyshov** [comment]
I cannot found problem with this app.

@seanl-adg What filters do you use?

**Comment by seanl-adg** [comment]
Hi, indeed the problem seems to be gone. I was using Android 6.0.1 and Adguard 2.8 version. Maybe something has changed in this app or updating Adguard to 2.9 has resolved the issue.
