### ISSUE TITLE
Experimental HTTP2 protocol implementation

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#1072]
Add experimental HTTP2 (h2) protocol implementation using CoreLibs. 
Since we don't have HTTPS interception in CoreLibs yet, it may work using existing SSL MITM code.

**Comment by war59312** [comment]
Should mark yourself as Adguard member in your github prefs. So it's obvious your not just another random user. ;)

Thanks

**Comment by sfionov** [comment]
Will be fixed in https://github.com/AdguardTeam/CoreLibs/issues/5
