### ISSUE TITLE
Navigation drawer should be accessible from any activity

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1079]
Left-to-right swipe should bring it up wherever you are.

Guidelines:
> To facilitate access to the navigation drawer on navigation hubs, all screens that correspond to an entry in your navigation drawer should show the navigation drawer indicator next to the application icon in the action bar. Touching the app icon causes the navigation drawer to slide in from the left.

> All other lower-level screens show the traditional Up indicator next to the application icon. The drawer is still accessible with an edge-swipe, but is not featured in the action bar.

**Comment by Revertron** [comment]
This one is already merged, can I close it?

**Comment by ameshkov** [comment]
All good
