### ISSUE TITLE
Filtering log does not work after protection restart

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1082]
Steps to reproduce:
1. Enable filtering log
2. Disable Adguard protection
3. Enable it back

Expected results:
Filtering log works, new events go there.

Actual result:
Filtering log does not work any more

**Comment by Revertron** [comment]
Done, review here: AJC-CR-181

**Comment by Revertron** [comment]
Fixed, merged.
