### ISSUE TITLE
Save filtering log state

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1083]
Currently, it is not saved, so when you exit AG and get back to it, log stays disabled.

We might need to add a warning, that enabled filtering log might use some extra resources.

**Comment by Revertron** [comment]
Is it okay to show a short Toast?

**Comment by Revertron** [comment]
Done, review here: AJC-CR-181

**Comment by Revertron** [comment]
Fixed, merged.
