### ISSUE TITLE
Disable https filtering for Skype app by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1085]
They use ssl pinning anyway.

**Comment by Bluscream** [comment]
What does that mean for people using SSL unpinning?

**Comment by nkartyshov** [comment]
@ameshkov What wrong with app? It have already disabled https filtering.

**Comment by ameshkov** [comment]
> What does that mean for people using SSL unpinning?

You'll have to enable SSL filtering for this app manually (if unpinning really works for it).

> @ameshkov What wrong with app? It have already disabled https filtering.

Ops, my bad.

**Comment by Bluscream** [comment]
So i have to add all apps manually that use a pinned cert?

**Comment by ameshkov** [comment]
To add? You'll have to enable https filtering explicitly for those apps.

**Comment by ameshkov** [comment]
> So i have to add all apps manually that use a pinned cert?

It depends on type of pinning.

If this is Nougat-pinning, you shouldn't do anything, it'd be enough to move cert to the system storage.

If it is the app's own pinning, you'll have sort things out manually with each app. They all use different types of pinning and that's the problem.

Moreover, it'd be better to create separate issues about every app, so that we could back you up and check it on our side.
