### ISSUE TITLE
Kaspersky Safe Kids app - HTTPS filtering compatiblity issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1089]
![image](https://cloud.githubusercontent.com/assets/15856304/23609215/9b517f60-0275-11e7-9fbe-87e2d7a4965c.png)

Disabling the HTTPS filtering for this app in the Apps management section and restarting the protection helped. The app: [link](https://play.google.com/store/apps/details?id=com.kaspersky.safekids&hl=ru).
ID 1119644

**Comment by nkartyshov** [comment]
Added in https exclusion
