### ISSUE TITLE
GDrive files upload might be broken by https filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1094]
Here is what I've found in the log file:
```
04:07:12.751 [pool-2-thread-789] WARN  c.a.f.proxy.BaseHttpProxyServer - TCP id=104585 Error processing request http://www.googleapis.com/upload/drive/v2/files?uploadType=resumable&mode=backup&fields=id%2Cmd5Checksum&upload_id=AEnB2UqUnHjWqusoxz1hQJ2klHIgbBBZ3-Q5dl2n2tptKmiVgP6Uub0SjAK9fRcMgvJN68Z5w9CTqxHR7IhZl1bfxwuBSFQRmkfz981TCjvgsSu-1ObgWN4: java.io.IOException Internal TLS error, this could be an attack
```

**Comment by ameshkov** [comment]
Cannot yet reproduce, reassigned to v2.10

**Comment by TPS** [comment]
Can y'all reconfirm whether Drive upload works w/ current ß?  I'm not sure if it's AG proper or something else in my setup.…

**Comment by TPS** [comment]
I'm on Android 7.0/Nougat, so no HTTPS filtering.  _That_ shouldn't make a difference, correct?

**Comment by zebrum** [comment]
@TPS  that is correct.

**Comment by TPS** [comment]
So, now I'm on Oreo, & GDrive upload _still_ doesn't work.  Which troubleshooting steps should I take?

**Comment by TheHasagi** [comment]
@TPS 

Check with other DNS providers or switch off DNS filtering. I guess something wrong with your carrier. Does it easily reproducible with WIFI?

**Comment by TPS** [comment]
Actually, I use *only* wifi, & either OpenDNS (mostly) or AGDNS.  I'll try turning off DNS filtering (though that's the majority & fastest I have of AG filtering, due to my setup) whenever I next run into this intermittently.
