### ISSUE TITLE
Log Whitelisting UI Inconsistencies

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1096]
Since #11, whitelisting from the filtering log has some unclarity:

- [x] ~~Filters thus generated end up in `Settings/User Filter` rather than `Settings/Whitelist`, which'd be the obvious place to locate such.~~  Confusion resolved via https://github.com/AdguardTeam/AdguardForAndroid/issues/1096#issuecomment-286452834

- [ ] It's unclear whether such filters defined from log are applied immediately, or AG toggling is required 1st.  When editing `Settings/User Filter` (& presumably `Settings/Whitelist`?), there's @ least a quick ___(≥ ½ sec)___ pop-up box showing <kbd>Refreshing Filters</kbd> or some such.

**Comment by ameshkov** [comment]
> Filters thus generated end up in Settings/User Filter rather than Settings/Whitelist, which'd be the obvious place to locate such.

The difference is that whitelist is for whitelisting whole websites, while user filter allows creating more specific rules. The rules created by the filtering log are quite specific and configurable, so they don't fit the whitelist.

> It's unclear whether such filters defined from log are applied immediately, or AG toggling is required 1st. When editing Settings/User Filter (& presumably Settings/Whitelist?), there's @ least a quick pop-up box showing Refreshing Filters or some such.

Huh, don't you see the same popup in the filtering log? I've just tried adding a rule through it and "loading" popup was there.

**Comment by TPS** [comment]
> The difference is that whitelist is for whitelisting whole websites, while user filter allows creating more specific rules.

I _did_ notice that, but when whitelisting an entire site globally, which is much of what I've done, [User] Whitelist is more apropos, right?
>  "loading" popup was there.

Maybe my phone is too fast?  Just tried it, & something blinks by, almost too quickly to tell.…  Was _that_ it?  What did it say?!

**Comment by ameshkov** [comment]
> I did notice that, but when whitelisting an entire site globally, which is much of what I've done, [User] Whitelist is more apropos, right?

Adding `example.org` to the whitelist won't unblock ALL the requests to `example.org`, it will unblock all requests sent FROM `example.org`.

I admit there it might sound weird, though:)

> Maybe my phone is too fast? Just tried it, & something blinks by, almost too quickly to tell.… Was that it? What did it say?!

Huh, even on Pixel I see it:) However, it is fast indeed:)

**Comment by TPS** [comment]
In that case, maybe you might need to make that box (very short-) timed,  ½-sec @ least.  After that, I can count this fixed. ☺

**Comment by ameshkov** [comment]
But why, if it works so fast that you don't see it, it is even better.

It's just you're for too long with the program to suspect an issue here:) Regular users won't even think that rule was not applied:)

**Comment by TPS** [comment]
That's possibly true, but visual feedback is better, right?  Besides, in all other aspects of UI, it _does_ have a recognizable notification when a setting is changed/applied.

**Comment by ameshkov** [comment]
What about a toast? Do you see it there?

**Comment by TPS** [comment]
Yep, I see the toast saying, "Rule added successfully."  Maybe that should read, "Rule _applied_ successfully"?  That, to me, would mean "added _& activated_," so that'd work, too.

**Comment by ameshkov** [comment]
Btw, just in case, wanna help us with English proofreading?:)

**Comment by TPS** [comment]
Absolutely yes! 😁  You all don't generally need it, but I'll file when I see it.

**Comment by ameshkov** [comment]
It is really easy to do:) Just sign up on https://adguard.oneskyapp.com/ and change or comment on any string there.

**Comment by TPS** [comment]
The way 1Sky ia setup, once the translation is approved (like English) , no more strings oe edits are shown or allowed. 🤦

**Comment by ameshkov** [comment]
@TPS yeah, for some reason strings were finalized. Fixed it.

**Comment by TPS** [comment]
1Sky's mobile interface is aggravating, & using the desktop 1 via mobile's bugged, so I'll get to my laptop eventually & play around.

Thanks for opening it up, @ameshkov.  I'll probably close this after I submit there. ☺

**Comment by ameshkov** [comment]
@TPS huh, you were right after all:)
https://github.com/AdguardTeam/AdguardForAndroid/issues/1124

**Comment by TPS** [comment]
@ameshkov: @Revertron [doesn't believe so](https://github.com/AdguardTeam/AdguardForAndroid/issues/1124#issuecomment-289015075), though.…

**Comment by Revertron** [comment]
Yep, I've proved that the rules are applied normally.

**Comment by ameshkov** [comment]
Yup

**Comment by TPS** [comment]
Thanks! 🙇
