### ISSUE TITLE
Faq UI is broken on Android 5.1.1 when you highlight text

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1097]
http://images.vfl.ru/ii/1488717044/dee11f59/16337432.png

Just take a quick look, is it possible to fix quickly?

**Comment by Revertron** [comment]
![screenshot_1489422392](https://cloud.githubusercontent.com/assets/105154/23864391/afa1a59c-0812-11e7-9aba-f13aed3580b7.png)
Fixed like this. Screen from emulator.
