### ISSUE TITLE
App details activity is very slow now

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1099]
Watch the video attached to the post:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=59270176

**Comment by Revertron** [comment]
I'm unable to see this on my device, but I've run method tracing.
It shows, that we run too much of `getDefaultRules()` - it can be cached without consequences (and it has an impact on SettingsFirewallFragment, when going back from FirewallPackageFragment), and `httpsFilteringService.isCaCertificateInstalled()` - it can be the main problem in FirewallPackageFragment. The checking of all installed certificates is CPU expensive...

**Comment by Revertron** [comment]
isCaCertificateInstalled() - speed up by x7,5.
getDefaultRules() - cached, will be much faster now.
