### ISSUE TITLE
AG-Android fails AG Test page 😱

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1102]
While I'm running AG VPN, all lists active (except `Useful ads) & up-to-date, http://static.adguard.com/test.html tells me, "Looks like Adguard is disabled:("

Is the bug AG or the page?

**Comment by ameshkov** [comment]
Yeah, test pages appears to be outdated:)

I've updated it and the english filter, check it in an hour or so

**Comment by war59312** [comment]
Still says "Looks like Adguard is disabled:(" 9 hours later.

And looks like you need a space after disabled ;)

Running AdGuard 6.1.**322**.1698, to fix the local adguard bug with chrome 58.

All filters report up to date.

**Comment by TPS** [comment]
@war59312 You must be running an AG other than Android, but, @ameshkov, I agree that the page is still broken exactly as it was before. 😞

**Comment by ameshkov** [comment]
My bad guys, should be good in a few minutes

**Comment by war59312** [comment]
@TPS, whoops yeah, just realized I posted in Android section. Was on Windows machine.

@ameshkov, thank you Sir. Success, "Adguard is enabled!".
