### ISSUE TITLE
Can't download media content in Viber

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardForAndroid#1103]
Impossible to download media in Viber - infinite downloading sign.
Android beta version 2.8.76. Issue remains the same after update to 2.9.17.
Could be solved via turning off HTTPS filtering.

First complaint - user 1521993.

**Comment by ameshkov** [comment]
@zebrum can you reproduce it?

**Comment by deLumren** [comment]
User 1115588 also complains that he can't **upload** media on Beta version 2.9.17

**Comment by ameshkov** [comment]
Problem:
`Cannot read HTTP request Http request method is invalid ALLOC`

**Comment by ameshkov** [comment]
Added `media.api.viber.com` to default SSL whitelist.

**Comment by OlegSUP** [comment]
Another trouble with Viber
User:
"в приложение viber если включена защита
по умолчанию, то невозможно получать
фотографии в чате и перейти в магазин
вайбера"

Logs, time 14.21:
[debug (11).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/893060/debug.11.txt)


Ticket ID: 1331840

**Comment by ameshkov** [comment]
@OlegSUP ask user to update to the latest Adguard release candidate.

**Comment by OlegSUP** [comment]
@ameshkov Done

**Comment by Bohdan-SUP** [comment]
Still happens even with 2.9.64 for user 713686:
[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/905106/debug.1.txt)

@ameshkov please have a look

**Comment by ameshkov** [comment]
@Bohdan-SUP does it help to disable https filtering for viber? Can you reproduce it yourself?

**Comment by Bohdan-SUP** [comment]
I can't reproduce it at all (both media and sticker shop open up), yet 1331840 and 713686 have it.

Disabling HTTPS filtering helps. Anything useful in logs?

**Comment by ameshkov** [comment]
Nah, not really. Let's put Viber to https exclusions in v2.10 then.

**Comment by nkartyshov** [comment]
done
