### ISSUE TITLE
Add an annotation to "Google Play services" app details

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1106]
This app is used to load Google ad network ads. We'd better warn people about it explicitly.

We should add a warning for all the apps sharing the same UID as "com.google.android.gms".
The warning should be placed under the "General" settings section.

Text:
```
This package can be used by third-party apps to load Google ads. Disabling ad blocking may result in unblocking some of the in-app ads.
```

**Comment by Revertron** [comment]
Done.
