### ISSUE TITLE
Add long press app shortcuts

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1111]
Opportunity to choose an option by touching and holding the app to pop up few useful shortcuts.

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24067983/9cc837c4-0b8c-11e7-856d-9abdd835c801.jpeg)

</details>

Ticket ID:1144878

**Comment by Wiredframe** [comment]
Also it would be great to launch AdGuard when long pressing the icon in the toggle panel.

**Comment by ameshkov** [comment]
@Wiredframe moved your feature request to a separate issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1351

**Comment by ameshkov** [comment]
We'll target Oreo in v2.12 so I guess it's time to add app shortcuts:
https://developer.android.com/guide/topics/ui/shortcuts

Ideas for app shortcuts:

* Start/stop protection
* Outbound proxy on/off
* Filtering log
* Apps management
* Settings

Anything else?

**Comment by carlylemiii** [comment]
@ameshkov check for filter updates? but only if you plan on making the app shortcuts user customizable, I don't think that one's a good default if you only do four :)

**Comment by ameshkov** [comment]
Good idea, added to the list

**Comment by nkartyshov** [comment]
@ameshkov I need icons for protection stop, outbound proxy off and AdGuard Assistant. 
That icons should be 96 dip.

**Comment by nkartyshov** [comment]
Done

**Testing instructions:**
1. Take device with version the 7.1.1 or newer
2. Install AdGuard
3. Go to the apps list
4. Long press on the AdGuard icon

**Expected result:**
The shortcut menu should appear

**Comment by ameshkov** [comment]
@nkartyshov app shortcuts menu does not disappear after choosing anything there (Android P DP3). Why could it be?

**Comment by nkartyshov** [comment]
I don't know. Motorola e4 have the same behavior, shortcuts don't disappear. I think it depends on firmware. And api for shortcuts does not have methods for such behavior at all.

**Comment by zebrum** [comment]
@nkartyshov there is no outbound proxy option in shortcut.

**Comment by TPS** [comment]
Is there a possibility to backport/decrease version compatibility to 7.0?  Most of my, e.g., Google apps have long-press shortcuts, so I think it's incorrect to limit to 7.1+.

**Comment by ameshkov** [comment]
@TPS that must be something else. ShortcutManager is added in API level 25 only: https://developer.android.com/reference/android/content/pm/ShortcutManager

**Comment by TPS** [comment]
🤷 It's [Nova Launcher, &c, that supports shortcuts since Android 5.1](https://m.androidcentral.com/app-shortcuts-nova-launcher-little-taste-nougat), which I suppose is [API level 22](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels), so I have them.
