### ISSUE TITLE
[2.9] An attempt to get a license from within the app makes Adguard crash when there's no browser installed

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1112]
Например если на телефоне не окажется не одного браузера,а ты жмёшь
получить лицензию на сайте, или вводишь ключ, а пишет ключ не действует
перейдите на сайт, ты жмёшь перейти и вылазит ошибка адгуард и он крашится
и не включается,если браузера стоит например гугл хром,он спокойно
перебрасывает на оф сайт

![screenshot_2017-03-18-15-03-06](https://cloud.githubusercontent.com/assets/15856304/24079074/2ab5f78c-0c88-11e7-9308-8573ae34b9bd.png)

ID 1143570

**Comment by Revertron** [comment]
Fixed.
