### ISSUE TITLE
[2.9] 'Learn more' button link resolves to an undefined page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1113]
It resolves here: https://m.adguard.com/ru/%7B0%7D/purchase.html

STR:

1. Try to activate the app with and expired key:

![image](https://cloud.githubusercontent.com/assets/15856304/24079089/ed8ed0b2-0c88-11e7-8543-4b726a34838b.png)

2. Click Learn more:

![image](https://cloud.githubusercontent.com/assets/15856304/24079094/036d27bc-0c89-11e7-8bad-2ea3f7b94e59.png)

 3. See this:

![image](https://cloud.githubusercontent.com/assets/15856304/24079096/16f82ee4-0c89-11e7-9e28-692019381ca9.png)

**Comment by Revertron** [comment]
Fixed, review AJC-CR-199
