### ISSUE TITLE
Consider changing Premium to Mobile in License screens

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#1115]
Some users find it confusing that they need either a Premium or a **Mobile** license to have those nice features in the app.
Maybe consider wording change?

<details>

![photo_2017-03-20_19-06-30](https://cloud.githubusercontent.com/assets/14153331/24112129/30b3d982-0da1-11e7-9372-ceceb6ac887a.jpg)

![photo_2017-03-20_19-12-07](https://cloud.githubusercontent.com/assets/14153331/24112130/30fd266e-0da1-11e7-9e1e-f43e83807902.jpg)

</details>

**Comment by TPS** [comment]
I'd think the other way around: Change all "Mobile" → "Premium", because 1 can already run Mobile as Free, but Premium license = extra features.

**Comment by Bohdan-SUP** [comment]
The thing is we have both Mobile and Premium license on the website - that may be confusing.

**Comment by TPS** [comment]
Is Mobile & Premium licensing actually 2 different things?  If so, make it clear what's meant by each, preferably everyplace 1 is mentioned, specify what the other means, also (in _that_ context).  Else, IMHO, stick w/ Premium consistently.

**Comment by ameshkov** [comment]
Yeah, Mobile covers android only, while Premium covers Android+Desktop.

However, I don't think we should change the naming here in light of the changes to the licensing that we have in mind (we'd like to go the same way as 1Password eventually -- have a one-for-all-devices subscriptions instead of a strict devices limit).

**Comment by Bohdan-SUP** [comment]
@ameshkov I'd appreciate more details then :)

**Comment by TPS** [comment]
@ameshkov So, something like current Amazon model, but over all device _types_?

**Comment by TPS** [comment]
#436?

**Comment by ameshkov** [comment]
@TPS yeah, something like what 1Password does (they did a transition from license keys to a subscription model).
