### ISSUE TITLE
TechMedia app - missing ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1119]
Ads leftover on my side and our customer has this issue.

Screenshot: 

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24182029/6ad5461a-0ec7-11e7-948f-d767afdcb0fe.png)

</details>

Steps to reproduce the issue:

1. Open TechMedia (Habrahabr) 
https://play.google.com/store/apps/details?id=ru.habrahabr
2. Check feeds

Adguard filters: English, Russian, Spyware, Social media, Annoyances, Mobile ads

Ticket ID:636610

**Comment by ameshkov** [comment]
It seems that it can't be removed with a simple requests blocking:(

**Comment by TPS** [comment]
Possible whenever #34 lands?

**Comment by ameshkov** [comment]
@TPS nah, it's just the banner place is hardcoded and we simply cannot change the app styles.

**Comment by TPS** [comment]
Cheaters. 😉 @ least they don't keep wasting bandwidth.
