### ISSUE TITLE
Issue with downloading from Google Play when connection speed is 50+ Mbit (Sony XPeria Z1C)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#112]
What could we try:

1. Increase MAX_CONGESTION_WINDOW to 256 * 1024
2. Disable ads filtering for Download Manager and see how it goes

**Comment by TPS** [comment]
I can't imagine any downside to (2) at all, but (1) seems to be highly user-environment dependent.  Changing that is a kludge that'll probably break when some1 else hits e.g., 500 Mbit, right?

**Comment by Revertron** [comment]
It works good with current settings. We did it! :)

**Comment by ameshkov** [comment]
> Changing that is a kludge that'll probably break when some1 else hits e.g., 500 Mbit, right?

I think that device capable of reaching 500 Mbit without AG will be powerfull enough to reach 300-400 Mbit with us.

> It works good with current settings. We did it! :)

@Revertron so do you suggest increasing default MTU to 9k?
