### ISSUE TITLE
missed ads in the app Themes for Plus Messenger https://play.google.com/store/apps/details?id=es.rafalense.themes

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1122]
missed ads in the app Themes for Plus Messenger
https://play.google.com/store/apps/details?id=es.rafalense.themes
![image](https://cloud.githubusercontent.com/assets/25711093/24286235/e7632b96-107c-11e7-8fa2-1b5747687de5.png)

![image](https://cloud.githubusercontent.com/assets/25711093/24286240/ea29e59a-107c-11e7-8d84-f9296d23b1a6.png)

Adguard filters: English, Russian, Spyware, Social media, Annoyances, Mobile ads
Adguard version: 2.8.76
Ticket ID:1138191

**Comment by ameshkov** [comment]
It should be reported to AdguardFilters

**Comment by Michael23456** [comment]
will re-open it in AdguardFilters

**Comment by Michael23456** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/4676
