### ISSUE TITLE
Android O: check if running VpnService is foreground or background

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1123]
According to https://developer.android.com/preview/features/background.html we might need to keep AG notification visible.

However, maybe they already keep running VpnService in foreground, we'd better check it.

**Comment by vozersky** [comment]
Looks like we stil run in the background on Android O.

<details><summary>Screenshot</summary>

![screenshot_20170703-145026](https://user-images.githubusercontent.com/17472907/27791731-3553f4c6-5fff-11e7-8374-abd508234e2a.png)

@ameshkov should we implement this [method](https://developer.android.com/preview/features/background.html#migration)?

**Comment by ameshkov** [comment]
I meant that we should test it with AG notification completely disabled.

**Comment by ameshkov** [comment]
Should re-test it when we start targeting SDK level 26
