### ISSUE TITLE
Disabling auto-pause on Android Nougat may cause significant slowdown

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1126]
The problem is that when autopause is disabled, we add IPv6 routes even when IPv6 network is not really available.

Having IPv6 routes without real IPv6 access might cause some websites and apps misbehavior.

What should we do:
1. Add `pref.vpn.disable.reconfigure` flag, that will be disabled by default.
2. When this flag is disabled, even when auto-pause is disabled, AG will keep an eye on the current network configuration and reconfigure VPN when connectivity changes.

What's important, instead of keeping an eye on network type (cellular <-> wi-fi switches), we should also check if IPv6 is available.

**Comment by ameshkov** [comment]
Review ID: AJC-CR-203

**Comment by TPS** [comment]
Is this suppose to cause `pref.vpn.disable.pause` to be ignored?  I'm getting the notification of AG _disabling_ everytime my wifi connection blinks.… Report sent under user 1122984

**Comment by ameshkov** [comment]
That's a mistake indeed.

**Comment by ameshkov** [comment]
Fixed, wait for the next RC plz.
