### ISSUE TITLE
Can these numbers be real?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1128]
Is skype really causing that much traffic? :o
![](https://puu.sh/uX3U2/6003a06b96.png)

**Comment by Alex-302** [comment]
Please upload the log of HTTP requests.

**Comment by Bluscream** [comment]
Where do i find them?

**Comment by Alex-302** [comment]
https://kb.adguard.com/en/android/solving-problems/log

Which filters are you using?

**Comment by Bluscream** [comment]
I sent a report with the link of this issue as description

**Comment by Bohdan-SUP** [comment]
@Alex-302 the log in question:
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/868841/debug.txt)

**Comment by Alex-302** [comment]
@Bluscream it is too small. Also, it is not a log of HTTP requests, it is full log.

**Comment by Bluscream** [comment]
I just followed the steps on the website you provided

**Comment by ameshkov** [comment]
Why closing, what was it after all?

The numbers are just crazy, how's that possible?

**Comment by Bluscream** [comment]
@ameshkov haven't you seen the email conversation?

**Comment by ameshkov** [comment]
Nope, missed it

**Comment by Bluscream** [comment]
If there would be a ticket id i could send it to you :c

**Comment by vbagirov** [comment]
@Bluscream when you send a message to support, there should be an autoreply that contains your helpdesk ID. You can use it to reference your ticket without exposing any private information.

**Comment by Bluscream** [comment]
![](https://puu.sh/v1dm4/8afbf4a22f.jpg) i dont see any id

**Comment by Bluscream** [comment]
Nvm i found it thanks, 1326210
