### ISSUE TITLE
[Request] Add firewall widgets

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1129]
Id like to see some firewall related AG widgets, like "Toggle WIFI for all apps", etc

Also Firewall widgets on a "per app" base would be nice (example: Lucky Patcher)

**Comment by ameshkov** [comment]
Assigned to v4.0. We'd better reconsider the widgets we have after the redesign.

**Comment by vozersky** [comment]
merged into #3378
