### ISSUE TITLE
Can't login to Firefox Sync

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1130]
![](https://puu.sh/uYKlx/116d520c06.png)

Detailed system info can be found at the report with a link to this gh issue

**Comment by Bluscream** [comment]
Adding ```
oauth.accounts.firefox.com
accounts.firefox.com
``` to the https whitelist fixed it

**Comment by ameshkov** [comment]
We should update default https exclusions list:
https://github.com/AdguardTeam/HttpsExclusions/commit/5304127b06627f9d42ec132b6aa7efabd40670ba

**Comment by ameshkov** [comment]
Added
