### ISSUE TITLE
[Suggestion] Restrict Beta Tester licenses to beta versions only

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1133]
https://github.com/AdguardTeam/AdguardForWindows/issues/1636

**Comment by TPS** [comment]
AFAICT, this is automatic on Android, @ least w/ Amazon (#102) versions.

**Comment by Bluscream** [comment]
![](https://puu.sh/uZ1zA/09fd8e5c33.png)

**Comment by TPS** [comment]
Yep, I don't have that toggle via the Amazon ß.

**Comment by ameshkov** [comment]
It makes sense, thank you!

**Comment by Bluscream** [comment]
Also disable opt-out of participation programs.

**Comment by 4222** [comment]
Referred to this thread by support as I've submitted a feature request related to this open issue.

Ideally it should just prompt the user to switch to the beta release cycle upon entry of a beta key. There will be cases where one needs to roll back to a stable release (e.g. latest beta release introduces a critical issue), as such the software must not prevent the user from reverting to a stable-release cycle.

Regarding [Bluscream's comment last 27/3](https://github.com/AdguardTeam/AdguardForAndroid/issues/1133#issuecomment-289326895):
> Also disable opt-out of participation programs.

It is unclear what the "anonymous security-related information" entails, however even if clarity is provided, disabling opt-out of participation programmes will potentially exclude people with sensitive information on their units from participating in the beta test --- this will be unfortunate as individuals valuing privacy and security are exactly the people you want beta testing the software.

**Comment by Bluscream** [comment]
I woukd nit want anyone to use paid software for free if he would not want to help testing.

**Comment by ameshkov** [comment]
> Ideally it should just prompt the user to switch to the beta release cycle upon entry of a beta key. 

I've just examined the backend code and it appears that if an app is activated with a beta-key, it will receive beta versions updates whichever channel you select in the app. However, in the case of the Android version, you can simply ignore newer versions and not install them.

**Comment by ameshkov** [comment]
So I guess we can mark this as resolved?

**Comment by Bluscream** [comment]
Hmm, what about the progams to help you finding bugs and improving the whole service?

**Comment by Bluscream** [comment]
![](https://puu.sh/vLh8y/494d8b5fd7.png)

**Comment by ameshkov** [comment]
@Bluscream 

> Hmm, what about the progams to help you finding bugs and improving the whole service?

You mean "help us" opt-in? It is completely voluntary and, frankly, we have enough volunteers already:)

**Comment by Bluscream** [comment]
Why do you even give out beta licenses anymore then?

**Comment by ameshkov** [comment]
> Why do you even give out beta licenses anymore then?

Why not? Beta testers help worth it:)

**Comment by Bluscream** [comment]
If they are not using any of the "help adguard" features, where are they useful for you?

**Comment by ameshkov** [comment]
> If they are not using any of the "help adguard" features, where are they useful for you?

To test beta versions and reports bugs apparently:)

**Comment by Bluscream** [comment]
If that's enough for you, sure :)

**Comment by 4222** [comment]
@ameshkov 

> I've just examined the backend code and it appears that if an app is activated with a beta-key, it will receive beta versions updates whichever channel you select in the app. However, in the case of the Android version, you can simply ignore newer versions and not install them.

Given this, happy to close the issue
