### ISSUE TITLE
Improve DNS settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1134]
Instead of just a low-level pref.vpn.dns, we could improve DNS settings and provide people with an option to choose from a pre-defined list of DNS servers.

Eventually, we could add DNSCrypt support.

## UI

Raw mockups:
https://app.moqups.com/ameshkov/lfmli7Cikw/view/page/a68657938

Icons:
[dns_icons.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1124689/dns_icons.zip)

### DNS Filtering

Main screen:
<details>

![adguard for android - dns filtering moqups 2017-07-05 15-58-36](https://user-images.githubusercontent.com/5947035/27865349-eb3f4ce4-619a-11e7-8ed9-68aed8081633.png)
</details>

#### Description
1. DNS Filtering is disabled by default.
2. Do not gray out controls when it's disabled, users should be able to change anything.
3. Help icon leads to a knowledge base article describing what DNS filtering is.

#### Regular DNS:
<details>

![adguard for android - dns filtering moqups 2017-07-05 15-58-46](https://user-images.githubusercontent.com/5947035/27865351-ed6aba3a-619a-11e7-99b1-24611d0c6ae7.png)
</details>

#### Description
Please note how "Custom DNS settings" item is divided into two parts. The switch is tappable independently of the "Custom DNS" part.
Tap on the "Custom DNS Settings" brings up this dialog window:
![adguard for android - dns filtering moqups 2017-07-05 15-59-03](https://user-images.githubusercontent.com/5947035/27865579-cdfb08c0-619b-11e7-9e9b-71b5a2d6d469.png)
You cannot enable "Custom DNS settings" unless the user enters servers addresses.

####  DNSCrypt:
<details>

![adguard for android - dns filtering moqups 2017-07-05 15-58-55](https://user-images.githubusercontent.com/5947035/27865353-ef167ef0-619a-11e7-84a6-b194adb0279e.png)
</details>

1. LEARN MORE button leads to https://dnscrypt.org/

**Comment by TPS** [comment]
#1053, #1006, &c?

**Comment by TPS** [comment]
Since miscellaneous DNS RFEs are collecting here, could there be a way to determine what app/site/whatever *made* a DNS request & have that put into the `Filtering Log` details?

**Comment by ameshkov** [comment]
> app/site/whatever made a DNS request & have that put into the Filtering Log details

Unless an app actually does this request. Nobody does it, though. Instead they "ask" an OS for the host's IP address and OS makes a DNS request to find it out.

**Comment by TPS** [comment]
IC: So, in general, the _OS_ would show as the source.  Anyway to track via different mechanism who's asking the OS?  &, whenever it can be determined by whatever method, to note that in logs?  Problem is, DNS requests "leak," even from apps that are ostensibly blocked from mobile/wifi data, & that _can_ be used for tracking via, e.g., [specially crafted host/DNS requests](https://www.grc.com/dns/dns.htm).

**Comment by ameshkov** [comment]
> whenever it can be determined by whatever method, to note that in logs?

Nope, unfortunately.

> that can be used for tracking via, e.g., specially crafted host/DNS requests.

It will anyway be a request for a subdomain, so it should be easy to block such.

**Comment by TPS** [comment]
>> specially crafted host/DNS requests

> request for a subdomain, so it should be easy to block such

How, if DNS address is custom generated, per app/page context?

**Comment by ameshkov** [comment]
> How, if subdomain/DNS address is custom generated, per app/page context?

By blocking all subdomains of a given second-level domain name

**Comment by TPS** [comment]
Shrewd trackers would simply block that by making that part of important domain — so, e.g., image.example.com, www.example.com, whatever.example.com, imageS.examples.com & myriad other _useful_ subdomains, interspersed w/ fgkgsdhy.example.com, ahg.example.com jtdgjtgghftyy.example.com, *random-letter-conglomerate*.example.com, &c for nefarious purposes.

I've _seen_ something quite like this for ad-serving/tracking.

----

What syntax is used for blocking subdomains, while whitelisting randomized useful 1s?

**Comment by ameshkov** [comment]
> What syntax is used for blocking subdomains, while whitelisting randomized useful 1s?

Something like that.

Blocking subdomains:
`*.example.org`

Unblock useful domain:
`@@||www.example.org`

**Comment by ameshkov** [comment]
Here is the very first mockup of the DNS module page:

<details>

![adguard for android - dns c2 b7 moqups f0 9f 94 8a 2017-04-21 14-38-47](https://cloud.githubusercontent.com/assets/5947035/25275911/56dfe688-26a0-11e7-8138-7a70aea02084.png)
</details>

@nkartyshov please start with the UI part, this mockup should be enough for the first days.

**Comment by nkartyshov** [comment]
Implemented, review AFA-CR-2

**Comment by ameshkov** [comment]
@nkartyshov let's also add "Response IP" to the filtering log

**Comment by ameshkov** [comment]
@nkartyshov if user uses a DNSCrypt server, DNSCrypt tab should be chosen automatically when he or she enters custom DNS settings.

**Comment by ameshkov** [comment]
Done

**Comment by TPS** [comment]
@ameshkov For the record, _what_ all was implemented?  A lot of ideas were put through here.

**Comment by ameshkov** [comment]
@TPS everything from the first post:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1134#issue-217065786

**Comment by ameshkov** [comment]
@TPS if you wanna try it, new build is here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1289#issuecomment-316101772

**Comment by TPS** [comment]
> if you wanna try it, new build is here: https://github.com/AdguardTeam/AdguardForAndroid/issues/1289#issuecomment-316101772

@ameshkov I'm _very_ tempted, but I run the Amazon ß exclusively now.  Can they be run side-by-side (w/ 1 disabled)?  Or should I wait for the update via Appstore?

**Comment by ameshkov** [comment]
@TPS nope, it can't:(

**Comment by TPS** [comment]
'S'alright, I just got an update notification from Amazon.  I'll just wait for that to actually update (usually several hours later 😐).

**Comment by ameshkov** [comment]
@nkartyshov I forgot about two important things. 

1. The lists of pre-defined DNS servers are too short now, we should add more servers.
2. We should improve "Custom DNS server" dialog, let people add DNSCrypt resolvers manually:

![adguard for android - dns filtering c2 b7 moqups f0 9f 94 8a 2017-07-18 19-49-11](https://user-images.githubusercontent.com/5947035/28329394-57510f10-6bf2-11e7-974c-e8d973b3c8f4.png)

**Comment by ameshkov** [comment]
The last thing left to do -- change the matching algorithm. We don't need the full-scale matching for the DNS filtering, so we'd better replace it with something relatively simple.

Basically, we need to support the very basic syntax described in these two sections:

* https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-syntax
* https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#special-characters

**Comment by ameshkov** [comment]
Done

**Comment by TPS** [comment]
@AdguardTeam I just wanted to mention how impressed I am with the work that was done in this issue.  It's really extraordinary! 👏

**Comment by ameshkov** [comment]
Thank you:)
