### ISSUE TITLE
Slow update responses

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1140]
What is being used to check for updates?
Github reminds me of updates hours before the app even finds one after manual checking sometimes, aren't you using the github api to check for and download updates?

**Comment by ameshkov** [comment]
> What is being used to check for updates?

AG just checks for updates once in 24 hours.

**Comment by Bluscream** [comment]
That's a answer to a different question :D

**Comment by ameshkov** [comment]
> Github reminds me of updates hours before the app even finds one after manual checking sometimes

It's just we roll it out on github first, and then add it to our server:)

**Comment by Bluscream** [comment]
Why don't use Github' releases API endpoint to check for updates?

**Comment by ameshkov** [comment]
Why bother, we already have our own API used for all the apps.

It's just we don't want to rely on a third-party API for such a sensitive thing.

**Comment by Bluscream** [comment]
True :)
