### ISSUE TITLE
[Question/Request] Add cloud sync for user filters on Android

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardForAndroid#1141]
Is there a plan to add user filter syncing for Android devices like it is planned for implementation for Windows? (See https://github.com/AdguardTeam/AdguardForWindows/issues/439)
If no - I think it would be a great idea!

**Comment by ameshkov** [comment]
Moreover, it is planned to be cross-platform.

**Comment by TPS** [comment]
#134?

**Comment by ameshkov** [comment]
Yep, duplicate
