### ISSUE TITLE
Notification delay problem for Google services

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1142]
Description:
https://forum.adguard.com/index.php?threads/notification-delay-problem-for-google-services.20280/

I suppose, it's not a bad idea to disable filtering for `com.google.android.gsf.login` by default.

**Comment by ameshkov** [comment]
The list of apps I'd like to check:
`com.google.android.gms`
`com.google.android.gsf`
`com.google.android.gsf.login`
`com.google.android.backuptransport`

**Comment by ameshkov** [comment]
Admob is integrated into `com.google.android.gms` (Google Play services).
https://android-developers.googleblog.com/2013/10/google-play-services-40.html

So, disabling for `com.google.android.gsf.login` and `com.google.android.backuptransport` shouldn't be a probelm. Not sure about the other two.

**Comment by ameshkov** [comment]
I've made a quick check: created a new app with AdMob and checked which apps are used to download the ads metadata.

After all, both are involved:
`com.google.android.gms`
`com.google.android.gsf`

So, we'll leave them filtered, and disable AG for the other two.

**Comment by ameshkov** [comment]
Ok, not that fast. It appears, that unblocking any of these packages leads to unblocking some of the doubleclick requests. Rolled it back.

**Comment by ameshkov** [comment]
After all, I was able to reproduce this issue with Gmail. We'd better take a closer look now.

**Comment by ameshkov** [comment]
Might be caused by different low-level settings.

**Comment by ameshkov** [comment]
There're some similar complaints on XDA.

What's common: they all have Samsung

**Comment by vozersky** [comment]
I've actually spent pretty much time Samsung Galaxy s7 hoping to reproduce it, but no luck.

**Comment by ameshkov** [comment]
@vozersky need you to come up with the mixed DNS/default approach instruction.

I suppose it should be a neat workaround for people suffering from this issue.

**Comment by ameshkov** [comment]
@vozersky please check this out:
https://forum.adguard.com/index.php?threads/notification-delay-problem-for-google-services.20280/#post-138571

What's my take on this:

1. The problem occurs on cellular data only.
2. It may be required to switch Wi-Fi/Cellular a few times for the issue to start occurring.
3. "FCM Push Notification Tester" app might come in handy to debug the issue.

@vozersky please try reproducing it one more time, the issue is really important.

**Comment by vozersky** [comment]
will do
I wonder if this can be a specific service provider related issue

**Comment by ameshkov** [comment]
More information about it here:
https://forum.adguard.com/index.php?threads/notification-delay-problem-for-google-services.20280/page-2

Temporary solution -- switch APN to IPv4. We're still looking for the cause of the issue.

**Comment by ameshkov** [comment]
It appears they have quite a few issues with IPv6:
https://www.reddit.com/r/ipv6/comments/3wfpn2/i_am_getting_sick_of_lorenzos_attitude_to_ipv6/
https://www.reddit.com/r/Android/comments/4091cr/disabling_ipv6_to_fix_delayed_push_notifications/
https://android.stackexchange.com/questions/107119/push-notifications-for-google-hangouts-unreliable-on-wifi

And VPN presence seems to catalyze these issues sometimes.

**Comment by ameshkov** [comment]
Here's why it affects Samsung phones more often:
http://lists.cluenet.de/pipermail/ipv6-ops/2015-June/010634.html

**Comment by ameshkov** [comment]
Reassigned to v2.10, it may take more time to tackle this issue.

**Comment by Revertron** [comment]
May I declare this thread as another official Samsung's hate thread? :)

**Comment by ameshkov** [comment]
Too early for that:) It concerns other Android devices too, just not that often.

**Comment by MR-Diamond** [comment]
I've carefully read the whole discussion > https://forum.adguard.com/index.php?threads/notification-delay-problem-for-google-services.20280/

I have the same issue with delayed push notifications.:
Firstly notice that the issue only occurs when I am connected with mobile data, no issue occurs when I am connected with wifi.
**The APN of my carrier was already set to ipv4 only** (for what is worth, my carrier doesn’t provide a public IP address: they “mask” IP addresses under NAT).
I've also tried to exempt apps from battery optimization, but if was an issue with Doze, I would face the same issue with wifi.
The issue only occurs when the screen is off.

**As reported by other users, I excluded Google Play Services from AdGuard: now notifications are instant**.
In AdGuard I also enable https filtering and DNS protection: if I disable these features I still experience delayed push notifications: I am totally sure that by excluding google play services from AdGuard solve the issue of delayed notifications.
I'm currently running  AdGuard 2.10.155 RC (I've bought a lifetime license) on Android Nougat 7.1.1 on an Xperia X Compact phone up-to-date.
Let me know if I can do some other test.

**Comment by MR-Diamond** [comment]
I encountered again the issue about delayed notifications: I switched on wifi for a while, then back to mobile data, then the issue of delayed push notifications was back :-[

Then I exempted Google Account Manager, Google Services Framework and Google Backup Transport from AdGuard: no luck.

Then I disabled AdGuard protection: no luck.
Then I disabled the VPN itself from Android's settings, but again no luck.

Then, by keep AdGuard and VPN disabled, I rebooted the phone and then enabled AdGuard and VPN again: in this way push notifications are again instant (Google Services still excluded).

I had the issue of delayed push notifications before to exclude Google Play Services from AdGuard, since I bought my phone (15 September): this issue was always reproducible.

Before to declare that excluding Google Play Services was a reliable solution, I’ve  done tests for some days: during this period I didn’t encountered the issue of delayed notifications.

Seems that the VPN or AdGuard trigger some issue when the connection change from wifi to mobile data? I have VPN set to "always on".

**Comment by ameshkov** [comment]
@MR-Diamond I've been to the US for two weeks recently and was using a T-Mobile sim card while being there. So while being there I have once encountered the very same issue with GCM connections being broken when AG VPN is up and running.

I've tried disabling filtering for Google Play Services but it didn't help. The issue was gone once I connected to Wi-Fi and then back to LTE, and after that, I couldn't reproduce it anymore.

Anyways, I've saved all the logs, hopefully, I'll understand it better once I analyze them.

**Comment by MR-Diamond** [comment]
I have an update about this issue:

I wiped cache and data of AdGuard, then uninstalled AdGuard, reboot my phone, reinstalled AdGuard from scratch and then I no longer found the issue with delayed notifications.

**Comment by MR-Diamond** [comment]
I barely use WiFi; in these days, instead, I use it more often.
Well, I still found this issue (while on WiFi): I excluded again Google Play Services in AdGuard, and push notifications are instant again; I can say it for sure, since I've done various tests.
My router (provided by my ISP) has IPV6 disabled.

**Comment by vozersky** [comment]
@MR-Diamond Hi! Both gmail notification and account sync problems? Is it on the same device?

**Comment by MR-Diamond** [comment]
Yes: the issue occurs both with the email client and with account sync, on the same device.
But I also noticed that randomly occurs: sometime, when I keep Google Play Services filtered by AdGuard, I receive instant notifications, and sometime, like in these days, I didn't receive notifications, and if I exclude Google Play Services in AdGuard, the issue doesn't occurs. Very odd.

**Comment by ameshkov** [comment]
The issue is really mysterious.

Are you sure disabling HTTPS filtering for Google Play Services does not help?

**Comment by MR-Diamond** [comment]
I didn't disabled HTTPS filtering, since I didn't enabled this option (because I read that HTTPS filtering doesn't works for the applications developed for Nougat): I just excluded Google Play Services from the apps section of AdGuard (I don't know the exact english grammar, since for me AdGuard is in italian).
However I have the DNS filtering enabled, and seems help to filter ADS in the applications also if I excluded Play Services from AdGuard.
Currently I'm using AdGuard 2.10.176.

**Comment by ameshkov** [comment]
> because I read that HTTPS filtering doesn't works for the applications developed for Nougat

It's handled automatically so don't worry:)

**Comment by ameshkov** [comment]
> However I have the DNS filtering enabled, and seems help to filter ADS in the applications also if I excluded Play Services from AdGuard.

AG is able to block ads even with excluded GPs, it's just I don't like that something slips through :(

I guess instead of excluding the whole app, we could exclude just the "Google Cloud Messaging" IP addresses and see how it goes.

I'll supply more details when I finally have time to get back to v2.11 issues.

**Comment by MR-Diamond** [comment]
Well, for what is worth: I installed another app: Wakelock Detector, and I noticed that by excluding Play Services from AdGuard, I see ads in this app also if DNS protection is enabled; so I turned on HTTPS  filtering and I still see ads from Wakelock Detector. So, you're right: exclude Google Play Services from AdGuard is not acceptable workaround :-)

**Comment by MR-Diamond** [comment]
In the meantime, can I try to do something? Maybe can I try to insert mtalk.google.com (which should be related to the Google Cloud Messaging) by going in the "white list" section of AdGuard? Or maybe I also should add some other domain?

**Comment by MR-Diamond** [comment]
> insert mtalk.google.com  in the "white list" section of AdGuard?

Nope, this didn't helped.

**Comment by ameshkov** [comment]
Find `pref.ipv4.routes.excluded` in the low-level settings
Add `74.125.205.0/24` there

**Comment by MR-Diamond** [comment]
Ok: I've added such option, and added back again Google Play Services to filtering.
Your suggestion seems that solved this issue, but I will confirm this after some days of tests.

**Comment by ameshkov** [comment]
Fingers crossed:

**Comment by MR-Diamond** [comment]
In these days (on WiFi and also on mobile data) I didn't missed any notifications: they arrive instantly as usual, as when I exempted Google Play Services from AdGuard.

On this page, [I see that you said](#issuecomment-290681453):
>After all, I was able to reproduce this issue with Gmail. We'd better take a closer look now

Did you also tried by adding 74.125.205.0/24 to `pref.ipv4.routes.excluded`?

**Comment by MR-Diamond** [comment]
Darn... I found again this issue :-[
As reported here https://forum.adguard.com/index.php?threads/notification-delay-problem-for-google-services.20280/ this time, from AdGuard, I exempted Google Account Manager, and is like to exempt Google Play Services: I don't miss push notifications, but obviously I see ads in apps...

**Comment by ameshkov** [comment]
As I understand, it's unclear what exact IP ranges should be excluded, GCM can be using different ones. What bothers me is that you have that issue with IPv4 addresses and this is not typical.

Anyway, we'll experiment more with this when the new beta arrives.

**Comment by ameshkov** [comment]
It took us some time, but finally, the new beta has arrived:)

@MR-Diamond are you still suffering from that issue?

**Comment by MR-Diamond** [comment]
> @MR-Diamond are you still suffering from that issue?

Yep: I updated AdGuard to 2.11.31 Beta and I still found such port open.

**Comment by MR-Diamond** [comment]
Sorry I think that I mixed up the issues :-)
If you referring to delayed notifications, I will let you know in these days after a batch of tests.
