### ISSUE TITLE
HTTPs filtering breaks some functionality in OLX/slando app 

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1143]
HTTPs filtering breaks some functionality in OLX/slando app 
if you set some filters in the app and press search it shows error
link in google play https://play.google.com/store/apps/details?id=ua.slando
![image](https://cloud.githubusercontent.com/assets/25711093/24496071/e914ca0e-153f-11e7-8924-926713bf9cb0.png)
If HTTPs is disabled it's working fine
the issue is on both release and beta android 5.1 and 7.0
VPN
customerID: 1056374

**Comment by nkartyshov** [comment]
done
