### ISSUE TITLE
Wrong behavior in sports.ru app because of https filtering 

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardForAndroid#1144]
При включенной https-фильтрации для [приложения sports.ru](https://play.google.com/store/apps/details?id=ru.sports) при попытке перехода по любой ссылке (в новостях, статьях, статусах) открывает веб-страницу, вместо открытия этих ссылок в самом приложении.
[Пример статьи](https://www.sports.ru/tribuna/blogs/memfut/1226792.html), практически в самом начале ссылка на другую.
Статусы (прямойсейчас) любые, где есть ссылки на материалы.
Версия adguard 2.9.60 rc

**Comment by ameshkov** [comment]
Хм, надо же, а я еще удивлялся, зачем они так сделали:)

**Comment by ameshkov** [comment]
Но мне кажется так всегда было, не только в RC

**Comment by dtitbd** [comment]
Да, я просто на всякий случай указал.
Уже их поддержку затерроризировал, почему ссылки открываются в браузере, а вон оно как оказалось.

**Comment by ameshkov** [comment]
А, не, некоторые ссылки у них реально в браузере открываются. На Android 7 хттпс фильтрация для их приложения не работает же, так что я без нее пользуюсь.

Пока, в качестве временного решения, можно спокойно отключить хттпс фильтрацию для их приложения, ничего лишнего не пролезет.

**Comment by dtitbd** [comment]
Да, так и сделал.
Не открываются в принципе ссылки в комментариях (но они обещали скоро сделать их поддержку) и профили пользователей. Их я в описание и не включил.

**Comment by nkartyshov** [comment]
Добавил в https исключения
