### ISSUE TITLE
Выбор загрузки файла

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1146]
У меня предложение по улучшению. Когда я захожу в настрйоки adguard, собственный фильтр и нажимаю выбрать файл с телефона. У меня очень маленький выбор загрузки файла (скрин 1), но почему-то на других сайтах, когда я гружу, то выбор больше - скрин 2. Я не могу загрузить правило, т.к. его просто не могу найти. Можете сделать выбор такой же, как на скрине 2?
https://ru.files.fm/u/yevheqbr
http://file.karelia.ru/zvkd47/

**Comment by ameshkov** [comment]
@Revertron ?

**Comment by ameshkov** [comment]
![1](https://cloud.githubusercontent.com/assets/5947035/24591149/445164ac-1803-11e7-943b-59cb18678ac6.png)
![2](https://cloud.githubusercontent.com/assets/5947035/24591150/44536aae-1803-11e7-8ee3-846ba75e83fb.png)

**Comment by Revertron** [comment]
May be we need to use Intent.ACTION_GET_CONTENT instead of Intent.ACTION_OPEN_DOCUMENT.
Need some testing.

**Comment by ministr91** [comment]
@ameshkov, ревертон англичанин?
@Reverton, ну так давай я протестирую. Скажи что надо куда добавить

**Comment by ameshkov** [comment]
@ministr91 это на нашей стороне, в следующих бетах потестим.

**Comment by ameshkov** [comment]
Done in #1279
