### ISSUE TITLE
Meta-RFE: Please add milestones or clarifying labels to all open issues

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1147]
Recently, thanks to @dennisfong86 [bumping it](https://github.com/AdguardTeam/AdguardForAndroid/issues/533#issuecomment-290984873), I was reminded of #533.  I realized part of the problem for the issue (which seems simple enough, given #201 has been implemented) is that, though _likely_ accepted (it has <kbd>UI</kbd> label, after all), [it _hadn't_ been `Milestone`d](https://github.com/AdguardTeam/AdguardForAndroid/issues/533#issuecomment-290991742), & would possibly be forgotten 'til later.

I propose @AdguardTeam goes back & `Milestone` all appropriate issues, & keep those updated for these & new issues. <kbd>[___This search finds all issues that are___ __not__](https://github.com/AdguardTeam/AdguardForAndroid/issues?utf8=%E2%9C%93&q=no%3Amilestone%20is%3Aopen%20-label%3Aquestion%20-label%3A%22waiting%20for%20data%22%20-label%3Abug):</kbd>
* Closed
* `Milestone`d
* Labeled:
  - <kbd>Question</kbd>
  - <kbd>Waiting for Data</kbd>
  - <kbd>Bug</kbd>

**Comment by ameshkov** [comment]
Going through all 250 issues will take quite some time:)

Although, the idea is great and I completely support it! @vozersky i need you to assist me on this:)

**Comment by TPS** [comment]
Honestly, going through the 74 that are currently open is plenty, though, if you want to go through the closed 1s for historical reasons for whatever reason, be my guest. 😁

**Comment by TPS** [comment]
@AdguardTeam I just wanted to bump this issue, just as reminder to try to add `Milestone`s to the many new /recent issues & the older 1s, also.  I've kept the original-post criteria & search updated (as well as the count in the _previous_ post 😉), so that tool should make these issues much easier to triage.

**Comment by vozersky** [comment]
@TPS the grand issue cleanup&and sorting campaign is coming soon :)

**Comment by TPS** [comment]
That's _excellent_ news; if there's anything _(else 😜)_ I can do to help, please just _ask_!

**Comment by TPS** [comment]
@AdguardTeam I just wanted to bump this issue, just as reminder to try to add `Milestone`s to the many new/recent issues & the older 1s, also.  I've kept the original-post criteria & search updated (as well as the count in the _3rd_ post 😉), so that tool should make these issues much easier to triage.

**Comment by ameshkov** [comment]
Working on it.

What we're doing right now:
1. Handling all the new unlabeled issues
2. Cleaning up old unanswered questions (in process)
3. Setting up stricter rules on bug reports/questions.

Regarding milestones, we do the feature requests and bugs review every time we plan a major release and assign milestones.

**Comment by ameshkov** [comment]
So we'll have 2.11 and 3.0 for now, everything else will be assigned later

**Comment by TPS** [comment]
Maybe not _yet_ close until those "else" assigned?

**Comment by ameshkov** [comment]
> Maybe not yet close until those "else" assigned?

I've closed all the obsolete/duplicate/etc issues.

All other issues were marked properly (bug/feature request + priority). When we will be planning the next update, we'll consider its priority.
