### ISSUE TITLE
Trim string when user enters new domain or rule into Whitelist/User filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1150]

**Comment by TPS** [comment]
Example?  I don't quite understand, but I feel this is something I'd find useful. 🤔

**Comment by ameshkov** [comment]
When you enter a new rule into the user filter, it won't work if you add extra spaces in the beginning of the rule.

**Comment by nkartyshov** [comment]
Done, review AFA-CR-81
