### ISSUE TITLE
Перевод и расширение FAQ

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1152]
Я зашел в раздел фильтры и был удивлен, что некоторые фильтры не переведены. Можете их перевести? https://ru.files.fm/u/gj8fxf4z
Также хотелось бы более расширенное FAQ, взять хотя бы те скрины, которые я кинул. Что такое killer reek? Тут два варианта: или занести это в FAQ или описание дополнить непосредственно в фильтрах, чтобы было понятно

**Comment by ministr91** [comment]
Да и еще вопрос, как загрузить фото сюда?

**Comment by ameshkov** [comment]
Аа, ну грузи хотя бы на imgur.com:)

**Comment by ameshkov** [comment]
Наши фильтры все переведены, а всякие сторонние - их не на что переводить:)

**Comment by ministr91** [comment]
Почему нельзя их перевести? Я же кинул скрины. Там англ.язык, можно же рус сделать, да и пояснить, для чего они 
![_20170404_140445](https://cloud.githubusercontent.com/assets/22351242/24724179/dd340642-1a52-11e7-986c-cf82f9d7fb84.JPG)
![_20170404_140459](https://cloud.githubusercontent.com/assets/22351242/24724181/dd36e060-1a52-11e7-9940-55716370bd86.JPG)
![_20170404_140513](https://cloud.githubusercontent.com/assets/22351242/24724180/dd34aeda-1a52-11e7-8b6f-b0281a3faf5f.JPG)

**Comment by ministr91** [comment]
Это же не трудно, всего-лишь пояснить для чего они нужны и перевести. Эти 3 выше

**Comment by ministr91** [comment]
@ameshkov

**Comment by ameshkov** [comment]
Ну вот мне кажется, что их переводом должны авторы этих фильтров озаботиться.

Но они почему-то этого не делают.

**Comment by ministr91** [comment]
@ameshkov здесь же не сложно, может сделаете перевод?

**Comment by ameshkov** [comment]
В любом случае мы этим займемся после того как работу по категоризации фильтров проделаем.

Сейчас они одним списком выводятся, это очень неудобно.

**Comment by ministr91** [comment]
Хорошо, но можешь как-нибудь пометить эту тему, чтобы не забыть? Тэг там поставить ну м открыть ее @ameshkov

**Comment by ameshkov** [comment]
Ага, записал
