### ISSUE TITLE
Cannot block ads in Moscow subway wi-fi network

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1154]
Since auth.wi-fi.ru и static0.wi-fi.ru are excluded from filtering as local domains

**Comment by ameshkov** [comment]
They are not excluded. It's just wi-fi.ru is located inside of the LAN.

**Comment by ameshkov** [comment]
Suggested solution: make a new advanced preference with network names, for which we filter LAN.

**Comment by ameshkov** [comment]
Done
