### ISSUE TITLE
Ads not blocked in Flipboard

### ISSUE THREAD

**Issue by cadoan** [AdguardTeam/AdguardForAndroid#1155]
Hi,

I hope this is the right place to report this issue.  I wanted to give feedback as a beta tester.

Ads aren't blocked inside Flipboard.  This applies to both inside the main app and inside articles.

Cheers,
Chris

**Comment by ameshkov** [comment]
Thank you and sorry for the late reply!

You're almost right, ads should be reported to AdguardFilters repo.
Moved it there:
https://github.com/AdguardTeam/AdguardFilters/issues/4757
