### ISSUE TITLE
Do not apply cosmetic filters to the pages whitelisted by a $document exception

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdguardForAndroid#1157]
related to https://github.com/AdguardTeam/AdguardForWindows/issues/1574

**Comment by TPS** [comment]
Conversely, other adblockers allow 1 to independently toggle cosmetic/network blocking for a site/request/whatever.  Is that possible w/ AG?

**Comment by ameshkov** [comment]
Of course, it's done by $elemhide modifier.

The point of this issue is a bit different, it's about applying rules to iframes nested inside of a whitelisted page.

**Comment by ameshkov** [comment]
Will be handled by the CoreLibs
