### ISSUE TITLE
Punctuation mistake in settings

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1159]
Забыли точку поставить в настройках. Везде стоят точки, а в портах нет 

<details>

![280a0172-1e26-11e7-8143-f39a28753ba2](https://cloud.githubusercontent.com/assets/17472907/24872480/43db39a2-1e26-11e7-9fbb-b609b6c6eca5.png)

<details>

**Comment by nkartyshov** [comment]
Исправил для Английской и Русской локализации.
