### ISSUE TITLE
Amazon version - user complaints on high memory usage

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#116]
> the memory usage is more than DOUBLE than the regular version of Adguard 

@Revertron could you please check it?
That's really weird, how could it be possible?

**Comment by ameshkov** [comment]
![c060e8a860c1840d80076ba12707551b](https://cloud.githubusercontent.com/assets/5947035/10588308/1c3bbbcc-76ae-11e5-8103-e8b5123f6e26.jpg)
![a85e772aa68cb0a7b408a1b18e662346](https://cloud.githubusercontent.com/assets/5947035/10588309/1d134dda-76ae-11e5-8390-ff9f19ddff77.jpg)
![73262865446e9d25e58e901ba2d195b1](https://cloud.githubusercontent.com/assets/5947035/10588312/1ef717b2-76ae-11e5-85a0-2f74f8544a0c.jpg)

**Comment by ameshkov** [comment]
There should be a way to unload amazon service

**Comment by TPS** [comment]
@ameshkov @Revertron _This_ is 1 downside of using _any_ Amazon-purchased app, though I think this _might_ only be with those that contain any in-app purchasing.  I actually use Greenify &/or CleanMaster's 1-Tap Hibernate to kill AppStore when I don't need it active.  That specifically has no bad effect on AG, though it'll just reload it when it checks licensing.  (Google Play apps do much the same via Google Services, so it's irrelevant in that sense to me.)

**Comment by Revertron** [comment]
Amazons service is started by static methods and it is stored in private static variable. There is no method to stop it or unload it.

**Comment by ameshkov** [comment]
@Revertron am I right that this amazon process is simply shared between all apps from amazon appstore?

**Comment by Revertron** [comment]
I doubt that. We use that code from their SDK, and this code and data isn't garbage collected at all.

**Comment by ameshkov** [comment]
Ok then. Closing this issue as we can't do anything anyway.
