### ISSUE TITLE
Reddit app comments sometimes are not loaded with https filtering enabled

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1160]
Reddit comments sometimes are not loaded with https filtering enabled
the link in play store:
https://play.google.com/store/apps/details?id=com.reddit.frontpage&hl=en
Customer's message: "Latest beta of Adguard and Reddit official app results in comments not being loaded at all, or not in a timely manner. Turning Adguard protection off immediately solves the problem. If Adguard is disabled and re-enabled, it doesn't block ads in the official Reddit app until
a reboot."
CustomerID: 1524207
Customer's phone is on Android 7.1
App version 2.9.60
Filters: 2, 3, 4, 14, 5, 11 
Tested it on Android 5, haven't noticed performance issues, but sometimes comments are not loaded
![image](https://cloud.githubusercontent.com/assets/25711093/24830988/5b9a1a42-1c99-11e7-870b-c7ac779df8d8.png)

**Comment by ameshkov** [comment]
@Michael23456 ask him to check filters updates in an hour or try this rule manually:
`@@||api.branch.io^$app=com.reddit.frontpage`

**Comment by Michael23456** [comment]
forwarded to the customer

**Comment by ameshkov** [comment]
One more rule could've caused issues,  removed it:
https://github.com/AdguardTeam/AdguardFilters/commit/1afa09975868150bb981570a74c8007f1c7202e0

**Comment by Michael23456** [comment]
Just tested it on my Meizu m3s( android 5.1) seems to work fine now. Will see results from the customer.

**Comment by KozelElena** [comment]
For me, it worked fine now (Meizu m2 android 5.1). 
Forwarded the last rule to our customer.

**Comment by ameshkov** [comment]
@KozelElena the rule is in the mobile filter already, so it should be enough for him to check filters updates.

**Comment by Darina655** [comment]
Got the answer from the client "Performance has certainly improved, but in some cases, comments still won't load (at all). The app is overall definitely slower than without Adguard.

**Comment by ameshkov** [comment]
@Darina655 does it help to disable https filtering for the app?

**Comment by Darina655** [comment]
@ameshkov on my side all the comments are visible even if https is on

**Comment by ameshkov** [comment]
@Darina655 same on my side, what I meant is performance issues, maybe without https filtering user won't have that slowdown?
