### ISSUE TITLE
VK messages - cannot send photo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1162]
**More info:**
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=60249316

@nkartyshov please check it, we may need to update the app if there is a bug with it.

**Comment by nkartyshov** [comment]
@ameshkov I haven't problem with upload photos in vk app on last Adgaurd version.

**Comment by nkartyshov** [comment]
@ameshkov Can I close this task?
