### ISSUE TITLE
Объявления - «Из рук в руки» app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1164]
Application doesn't work even without HTTPS filteing and with disabled filters.
An error: "Сеть недоступна"
https://play.google.com/store/apps/details?id=com.arvifox.hibiny&hl=en
Adguard 2.9.64
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/4774

**Comment by nkartyshov** [comment]
Adding an application to the https exclusion solved the problem.
