### ISSUE TITLE
Add support for domain.* TLD matching

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1169]
It is really easy to do, so why not?

**Comment by Itsnothectic** [comment]
Would be a good reason to ditch iOS for Android :)

**Comment by BooBerry** [comment]
Assuming AG for Windows, Mac and the browser extensions don't support it already, why not them too? ;)

There's sites with multiple domains, sadly. Google's an example, as are more "shady" sites I've heard about like Avax, which seems to change domains a lot.

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/CoreLibs/issues/48
