### ISSUE TITLE
can't access eu.battle.net  and hearthstone app

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1170]
can't access eu.battle.net  and hearthstone app
![image](https://cloud.githubusercontent.com/assets/25711093/25066020/2dab9414-2223-11e7-973c-2e8aaeeed6b5.png)

the issus with eu.battle.net is reproduced 20:58
CustomerID:1093966
[debug (9).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/923799/debug.9.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/923801/state.txt)
PS: is not reprodued on Meizu m3s (android 5.1)

**Comment by ameshkov** [comment]
Duplicate, resolved in v2.9
