### ISSUE TITLE
Change Finnish default filter list from Wiltteri to Juvander's

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardForAndroid#1171]
According to User 1543777 default Adguard filter for Finnish Language - Witteri is outdated.
Their GH page - https://github.com/wiltteri/ - was not updated for 2 years. And the filter itself was not updated since last December.

Instead they suggest we start using List by Ilpo Juvander available here:
http://adb.juvander.net/Finland_adb.txt
Which is being actively updated (Current version is from 2017-4-10).

Here is current state of Android Finnish filter:

}, {
    "groupId" : 2,
    "filterId" : 116,
    "name" : "Wiltteri",
    "description" : "Finnish supplement list for EasyList",
    "homepage" : "https://github.com/wiltteri/",
    "version" : "1.0.1.70",
    "expires" : 86400,
    "timeUpdated" : "2016-12-02T20:06:37+0400",
    "subscriptionUrl" : "https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt",
    "languages" : [ "fi" ],
    "displayNumber" : 124
  }, {

**Comment by Alex-302** [comment]
I think, `Juvander's Adblock List for Finland` should be added as separated filter.

**Comment by ameshkov** [comment]
@Alex-302 please move this issue to AdguardFilters then.

**Comment by Alex-302** [comment]
@ameshkov but this issue is actual for Android only. These both filters are available for all other products.

**Comment by ameshkov** [comment]
Ah, sorry, now I get it.

**Comment by nkartyshov** [comment]
We have already added this filter in the task: #1225
