### ISSUE TITLE
cityguide.probki.net - Adguard breaks maps downloading

### ISSUE THREAD

**Issue by Joss** [AdguardTeam/AdguardForAndroid#1172]
2.9.64 (all setting by default, VPN, +DNS filtering)

Apps affected by this bug:
net.probki.bgeo
net.probki.geonet
cityguide.probki.net

Users can't download maps from cityguide ftp servers.

[fulllog.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/924589/fulllog.zip)

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/995

The only solution: disable AG completely for these apps.

Moreover, filtering is disabled for these apps by default.

**Comment by Joss** [comment]
Yes, it was disabled, but it didn't helped (probably because DNS filtering). Only Adguard shutdown helps with the issue.
