### ISSUE TITLE
Reinitialize VpnService when newly installed app should not be filtered

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1173]
Let's imagine that traffic filtering is disabled by default for the PayPal app.

So, here's how the issue looks like:
1. Start AG protection
2. Install PayPal app
3. Open it

Expected result:
App should've been excluded from VPN.

Actual result:
App's traffic goes through VPN

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-40
