### ISSUE TITLE
RFC/E: Evaluate & implement potentially "new" (¿¡!?) adblocking techniques

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1174]
Reading through the press, they seem like hype to me, but you folks are the experts. Both are under MIT license:
- https://github.com/storey/fbAdHighlighter/
- https://github.com/citp/ad-blocking/

**Comment by ameshkov** [comment]
Yep, I've seen it. Here is my comment on this:
https://forum.adguard.com/index.php?threads/the-future-of-ad-blocking-an-analytical-framework-and-new-techniques.20950/#post-133769

**Comment by TPS** [comment]
So, more of a v99.× iteration of #249 for when Google releases the [Quantum](https://research.google.com/pubs/QuantumAI.html) [Pixel](https://madeby.google.com/phone/) ≈ GQubit? 😂  Don't forget to send me that ß in 2100 or so: _I_ should be uploaded to my GDrive by then. 🙃

**Comment by ameshkov** [comment]
Given how fast things are developed nowadays it might happen earlier:)

**Comment by TPS** [comment]
Apparently, it only took 9 years.  Congrats,
@MaximTop on https://github.com/maximtop/ai-blocker-experiment!
