### ISSUE TITLE
Adguard Traffic Management does not count Play Market updates

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardForAndroid#1177]
User 1544271 wants to know why traffic from updating applications via Play Market is not counted in Adguard statistics.

You can find numbers in his ticket.

**Comment by ameshkov** [comment]
Play app is in the list apps for which filtering is disabled by default.

We do it to solve possible issues with DNS filtering and apps updates downloads. However, user may easily enable it back in the apps management section.

**Comment by Alex-KS02** [comment]
Really.. Thanks a lot! I was sure that all apps are filtered by default and even didn't check it :-)
Have a nice day!
