### ISSUE TITLE
Constant requests to a tracking server causes CPU overuse

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1179]
The easiest way to reproduce this issue is to block `api.segment.io`, install LastPass and monitor the filtering log. It constantly tries to contact that server. Also `mixpanel.com` is rather aggressive.

For now I've changed the rule to `||api.segment.io/v1/` so that it didn't work when HTTPS filtering cannot be used to emulate server's response.

**Possible solutions**

In any case, we should implement some sort of a rate limiter. For instance, if 10 similar requests are blocked within a short period of time, we should mark `domain-endpoint` pair as "limited".

The rate limiting strategy may differ depending on the filtering mode.

1. VPN mode -- reset the connection immediately once it is received from the TUN.
2. Proxy + auto mode -- that's tricky, I am not sure yet what's the proper way to handle it.

It's worth noticing, that mixpanel detects DNS-level blocking and does not try to connect to their server:
https://github.com/mixpanel/mixpanel-android/blob/bf7cdd554ae8e2ab8dd2954472e697f8efdc2a22/src/main/java/com/mixpanel/android/util/HttpService.java#L34

**Comment by ameshkov** [comment]
Again, mixpanel detects response code 500 and does not make another try:
https://github.com/mixpanel/mixpanel-android/blob/bf7cdd554ae8e2ab8dd2954472e697f8efdc2a22/src/main/java/com/mixpanel/android/util/HttpService.java#L147

**Comment by TPS** [comment]
Are you saying these requests are generated by the app/browser _itself_ or just whatever site that's being hosted?  E.g., _I_ regularly run Lastpass as my primary browser, but I don't see these requests in my filtering log.  Did I miss something?

Anyway, I'd like to volunteer to test whatever you'd like me to, here.  Will my lack of HTTPS filtering be a problem?

**Comment by ameshkov** [comment]
> Are you saying these requests are generated by the app/browser itself or just whatever site that's being hosted?

Talking about LastPass app only, not the browser. Yeah, if you block `api.segment.io`, it'll repeat request to it all the time.

**Comment by ameshkov** [comment]
Same issue with Kinopoisk app:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1218

**Comment by ameshkov** [comment]
Here is what I did:

1. If HTTPS connection is blocked at the handshake stage, we add the pair of app name and remote endpoint address to the cache of blocked endpoints.
2. Next time when this app tries to contact that endpoint, we won't spend time on parsing ClientHello and block it right away.
3. This "blocking" looks different from the side of the app -- instead of SSL error, it now receives a network error (connection reset).
4. The whole procedure takes almost no time, so it practically solves CPU overuse issue.

Review ID: AFA-CR-10

**Comment by TPS** [comment]
Oddly, for me, DNS blocking seems sufficient, as I rarely see the requests mentioned in the Filtering Log.  However, if I'd like to test this via LastPass, how would I proceed?

**Comment by ameshkov** [comment]
> Oddly, for me, DNS blocking seems sufficient, as I rarely see the requests mentioned in the Filtering Log. However, if I'd like to test this via LastPass, how would I proceed?

DNS blocking solves the issue completely, indeed. That solution we need for the case when DNS blocking is not used.

**Comment by ameshkov** [comment]
Reopened issue because of a bug -- requests blocked by "cache" aren't recorded to the app stats.

**Comment by ameshkov** [comment]
Done
