### ISSUE TITLE
Fix filtering log toolbar layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1180]
Screenshot:
![photo - google photos 2017-04-21 13-16-16](https://cloud.githubusercontent.com/assets/5947035/25273535/d0a20d72-2694-11e7-854f-499651f0ced5.png)

**Comment by nkartyshov** [comment]
Fixed.

**Comment by zebrum** [comment]
nexus 7 still the same problem

**Comment by nkartyshov** [comment]
Fixed
