### ISSUE TITLE
Adguard 2.9.64 Proxy mode failure with custom OpenVPN server

### ISSUE THREAD

**Issue by sz4bi** [AdguardTeam/AdguardForAndroid#1183]
Hi

I am using Adguard 2.9.64 on my Nexus 6 (LineageOS 14.1, Android 7.1.2). The phone is rooted, so Adguard is running in Proxy mode. My router is running an OpenVPN server on port 443 to fool my mobile phone ISP's traffic filtering policy. So with Adguard On with automatic Local Http Proxy mode the connection is made to the VPN server, but after the connection established something cause a soft reset, initiating a reconnection to the VPN server.

I tried to exclude my dynamic dns (OpenVPN server) name from the filtering, but nothing changed.
Any ideas?

[adguard.log](https://github.com/AdguardTeam/AdguardForAndroid/files/949705/adguard.txt)

![screenshot_20170423-143535](https://cloud.githubusercontent.com/assets/2352817/25313689/d6bed5fa-2833-11e7-9fd1-fb14207b533c.png)

**Comment by ameshkov** [comment]
Hi! What if you disable Adguard for the `de.blinkt.openvpn` app, does the issue go away?

**Comment by ameshkov** [comment]
You can do it in the apps management settings section

**Comment by sz4bi** [comment]
Sorry for bothering, that was the problem. I am new to Adguard and I have never used that menu before... Thank you.

**Comment by ameshkov** [comment]
No worries, I guess we should disable AG for the openvpn app by default.

**Comment by ameshkov** [comment]
Added to the default exceptions list
