### ISSUE TITLE
Compatibility issues with TutoTOONS apps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1184]
Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=60750689

Apps:
https://play.google.com/store/apps/dev?id=6493980387780624296

It might be enough to add tutotoons.com to the SSL whitelist.

**Comment by nkartyshov** [comment]
Added in whitelist https://github.com/AdguardTeam/HttpsExclusions/commit/ded7e3da2ae1cb617ef9206df3cc77971d964540
