### ISSUE TITLE
Clarification: Unblocking specific requests for blocked app?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1187]
It occurs to me that I've _never_ seen discussion on:

If I've an app mobile-/wifi-blocked via firewall, is it possible to whitelist specific requests from that app?  If so, what syntax would be necessary (e.g., `$important,app=`, or just 1 or the other)?  Else, I'd like to request the capability to do so.

Here's a real world example: I've no need for [CleanMaster](http://play.google.com/store/apps/details?id=com.cleanmaster.mguard) to access online except in 2 cases:  weather & AV updates.  Everything else, to me, just wastes bandwidth.  Right now, my solution is to restricted it completely to wifi.  But better would be to full data-block it, & whitelist just those 2 specific requests, still though _only_ for wifi (next step from #202).  Is it possible?

**Comment by ameshkov** [comment]
Firewall rules are applied independently, so you can't unblock it that way.

> Is it possible?

I guess instead of using the firewall, you can use a different approach.

Block all CleanMaster requests:
`*$app=com.cleanmaster.mguard`

Unblock those you want to still work:
`@@||example.org^$app=com.cleanmaster.mguard`

**Comment by TPS** [comment]
I'll hafta try it.

I think [you mentioned before](https://github.com/AdguardTeam/AdguardForAndroid/issues/908#issuecomment-286454622) that `$app=com.cleanmaster.mguard` = `*$app=com.cleanmaster.mguard`, correct?  _(Just cleaner in the list.)_

Will `@@||example.org^` w/o `$app=` work, or would it need `$important`?  _(CM apps overlap in blocked/whitelisted items, & it's just convenient.)_

**Comment by ameshkov** [comment]
> correct?

Yep.

> Will @@||example.org^ w/o $app= work, or would it need $important?

Exception rules generally have higher priority than basic blocking rules.

Something like that:
`exception rule with $important` > `basic rule with $important` > `exception rule` > `basic rule`

**Comment by TPS** [comment]
Thanks.  I just wasn't sure of order-of-operation of `@@` vs. `$app`.

I'm assuming, based on [what you mentioned earlier](https://github.com/AdguardTeam/AdguardForAndroid/issues/1187#issuecomment-298331753), that `Firewall data block` > `exception rule with $important`?

**Comment by ameshkov** [comment]
> I'm assuming, based on what you mentioned earlier, that Firewall data block > exception rule with $important?

Yeah, you can say that.

**Comment by TPS** [comment]
Just FYI. this worked amazingly well.  If you want me to list what I did, let me know. 😁
