### ISSUE TITLE
Features listed on the website are not listed clearly

### ISSUE THREAD

**Issue by Itsnothectic** [AdguardTeam/AdguardForAndroid#1188]
So I will ask my questions here.

1) Can the http proxy mode be used along with a separate system hosts file and also a VPN to block ads in Apps?

2) Lets say I have some hosts blocked in etc/hosts will adguard also use this along with the DNS Filter and the hostname.* rules?

3) If Adguard for Android uses Adguards DNS do these get routed through the VPN so my IP is hidden from the DNS server?

I think "Otherwise" should be replaced with "On non-rooted devices" and should specify if it works with systemless root such as Magisk. 

https://adguard.com/en/adguard-android/overview.html

For Example Adaway doesnt work with Magisk but an Adblock module for Magisk does.

**Comment by ameshkov** [comment]
> Can the http proxy mode be used along with a separate system hosts file and also a VPN to block ads in Apps?

Yeah, it can.

> Lets say I have some hosts blocked in etc/hosts will adguard also use this along with the DNS Filter and the hostname.* rules?

Nope, but it will be applied anyway. There will be no DNS request for a host blocked in the hosts file.

> If Adguard for Android uses Adguards DNS do these get routed through the VPN so my IP is hidden from the DNS server?

There is no way to hide your requests from a DNS server, otherwise, it couldn't respond to them.  You might want to hide your DNS requests from other parties, though, for instance, from your ISP. This can be achieved by using encrypted DNS (DNSCrypt).

> I think "Otherwise" should be replaced with "On non-rooted devices" and should specify if it works with systemless root such as Magisk.

Could you please explain more about Magisk? Does it allow to change proxy settings system-wide?

**Comment by Itsnothectic** [comment]
Doesnt adguard already use DNSCrypt though?

Magisk is a systemless-root I dont know what that is exaxctly but it allows Googles SafetyNet to pass so you can use AndroidPay and you can still modify the system files and have SU.

Not all root apps are compatible with systemless root.

**Comment by ameshkov** [comment]
> Doesnt adguard already use DNSCrypt though?

It is possible to use AG DNS through DNSCrypt, but on Android you cannot simply use DNSCrypt itself.

Furthemore, AG for Android does not use AG DNS at all, we'd like to provide such an opportunity: #1134
