### ISSUE TITLE
[Feature request] Allow export option for User filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#119]

**Comment by Nick-White** [comment]
+1

Will it also apply for exclusion list?

**Comment by ameshkov** [comment]
In fact this issue may be considered as a duplicate for what we plan for AG 4.0:
https://github.com/AdguardTeam/AdguardForAndroid/milestones/4.0

We want to introduce user profiles thus you'll have an opportunity to export/import whole settings (of the current profile).

**Comment by justinliao7928** [comment]
+1 
Looking forward. :)

**Comment by TPS** [comment]
Included in #133, I suppose.

**Comment by ameshkov** [comment]
Dup of #1279
