### ISSUE TITLE
Suggest enabling "HTTPS filtering" on the main screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1190]
People do not realize what capabilities are provided by the HTTPS filtering.

We should at least inform them about it on the main screen.

One it's done, we no more need the warning message on the navigation sidebar.

**Comment by ameshkov** [comment]
Later, current UI just does not let us add anything like that:(

**Comment by Revertron** [comment]
Done in review `463`, but the main screen will be reworked one more time...

**Comment by ameshkov** [comment]
This needs to be part of "feature discovery" process, we'll discuss it later.
