### ISSUE TITLE
Subscription status description is misleading

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1191]
Adguard 2.9.70

Go to "License Status" and press "Refresh license status" 
this wording (about subscription renewal) has to be changed:

<details>

![screenshot_2017-04-25-17-30-00](https://cloud.githubusercontent.com/assets/17472907/25387923/07d64efa-29d5-11e7-9f91-2de5915fd9a4.png)

</details>

**Comment by TPS** [comment]
>this wording (about subscription renewal) has to be changed

@vozersky Why?  It seems _very_ clear & precise to me.

**Comment by vozersky** [comment]
@TPS 
Because apparently it makes people think there is some kind of automatic sub renewal after the week of trial period. 
The previous screen (License status) has a correct phrase: "License is valid until ..."

**Comment by TPS** [comment]
Ahh, the _trial_ language got lost, IC. 🤦

**Comment by ameshkov** [comment]
Trial period was always 7 days for Android app.

**Comment by vozersky** [comment]
@ameshkov the wording is still misleading, it's not about duration

**Comment by ameshkov** [comment]
It looks as if Adguard is activated with Amazon subscription. Isn't it?

**Comment by vozersky** [comment]
Nope, it's not. Just a free trial.

**Comment by ameshkov** [comment]
That's really bad, we should fix it in the patch for v2.9

**Comment by nkartyshov** [comment]
@ameshkov @vozersky 
Fixed to 'Your license is valid until {day_month_year}. Thank you for being our customer!'

**Comment by ameshkov** [comment]
@nkartyshov the problem is not in the phrase

**Comment by nkartyshov** [comment]
Done, review AFA-CR-19

**Comment by ameshkov** [comment]
Now it looks as if it was activated with a license key. No "activate" button.

**Comment by nkartyshov** [comment]
Why is there no "activation" button? You have button "Activate Premium" in Adguard Premium screen if you activate license key. 

This screen we showing if app activated  at Amazon store.

**Comment by ameshkov** [comment]
What in the world has Amazon to do with this

**Comment by ameshkov** [comment]
@nkartyshov you have 4 different states:

1. No license, no trial (regular build)
2. No license, no trial (amazon build)
3. Active trial period
4. Active license
5. Active subscription

**Comment by nkartyshov** [comment]
We showing License Key screen in 1,2,3,4 state.
Subscription screen showing in 5 state, but We showing license key screen if subscription expired.

**Comment by ameshkov** [comment]
@nkartyshov this is obviously wrong behavior

**Comment by ameshkov** [comment]
@vozersky is it done?

**Comment by vozersky** [comment]
@ameshkov yep, @nkartyshov has fixed it

**Comment by nkartyshov** [comment]
Fixed, Review AFA-CR-31

**Comment by nkartyshov** [comment]
done
