### ISSUE TITLE
Speedtest app ping is now +100ms

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1192]
Problem: speedtest uses port 8080 for checking ping.
This port is now filtered by AG.
Adguard's tunnel implementation adds 100ms to the very first packet processing (which should be fixed).

**Comment by evgeniy-ADG** [comment]
Does it affect other speed test results?

**Comment by ameshkov** [comment]
It shouldn't, only the ping value.

**Comment by ameshkov** [comment]
Review ID: AFA-CR-6
