### ISSUE TITLE
AquaMail app error

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardForAndroid#1193]
In AquaMail app, when HTTPS is enabled, the app won't connect to exchange server.

A link to the app https://play.google.com/store/apps/details?id=org.kman.AquaMail&hl=en
This app is paid on the customer's side. 

Logs are attached to the ticket.

Ticket number(1549008)
Adguard version: 2.9
Filters: 2, 3, 4, 1, 11 
HTTPS filtering: on
filteringQuality" : SPEEDY

**Comment by nkartyshov** [comment]
@Darina655  Can you ask user add the url **pet-net.ru** in https white list, please?

**Comment by nkartyshov** [comment]
Problem solved
