### ISSUE TITLE
Rework the HTTPS filtering settings section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1194]
Mockup:
https://app.moqups.com/ameshkov/lfmli7Cikw/view/page/a599a916a

**Main changes**

1. If HTTPS filtering is disabled, all the settings should be grayed out.

2. "On/Off" switch now installs the certificate.
If the certificate is installed, it just changes the "Filter HTTPS" flag value.
If the certificate is not installed, it generates & installs it first.

3. Certificate status now shows a brief description of the current certificate state.

Possible values:

* `Not installed`
* `Installed into the User certificates store`
* `Installed into the System certificates store`

Possible descriptions:

* Android N+, user store: `AdGuard can filter HTTPS in most of the browsers. Regular apps cannot be filtered due to Android restrictions.`
* Android N+, system store or Android M or older: `AdGuard can filter HTTPS in most of the apps.`
* Not installed: `AdGuard cannot filter HTTPS.`

**Comment by seba2282** [comment]
I don't know. If it is the same, I have monit in Android notifications about differrent certificate without Android system cerificates. And I clear it and after reboot telephone I have the same.

**Comment by ameshkov** [comment]
@seba2282 that's okay, Android just notifies you that you have a custom certificate installed.

**Comment by ameshkov** [comment]
@nkartyshov 
1. Styles are different from the mockup
2. The app crashes when I tap "Learn more"

**Comment by nkartyshov** [comment]
done
