### ISSUE TITLE
Adguard does not filter HTTPS connection with TLS 1.0 servers

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1195]
<details>

![image](http://i91.fastpic.ru/big/2017/0428/31/8f60410c68db80650e181da8862d8031.jpg)
</details>

Log:
https://rocld.com/y2wtw
or
[adguard.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/964731/adguard.txt)

**Comment by vozersky** [comment]
reproduced

**Comment by Alex-302** [comment]
the same issue
https://www.gtavicecity.ru/gta-san-andreas/gta-san-andreas-cheats-pc.html

<details>

![image](http://i46.fastpic.ru/big/2017/0505/2d/571e5bd97dcf93ed60bc320251d1192d.jpg)
</details>

**Comment by Alex-302** [comment]
another one:
https://nplus1.ru/news/2017/05/25/subtitles
https://forum.adguard.com/index.php?threads/nplus1-ru.22130/

**Comment by ameshkov** [comment]
It seems that AG does not trust Let's Encrypt certificates

**Comment by Alex-302** [comment]
and Comodo
https://github.com/AdguardTeam/AdguardForAndroid/issues/1195#issuecomment-299442247
but only on Android

**Comment by ameshkov** [comment]
Ok, I got it, the culprit is TLS version, AG refuses to downgrade to TLSv1.0, while actually it should be allowed.

**Comment by ameshkov** [comment]
Done, review ID: AFA-CR-20
