### ISSUE TITLE
Wi-Fi calling doesn't work (T-Mobile)

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1197]
>  I have had this problem on a note 7 aтв s7 edge and now s8 galaxy phone. When I answer a
> call the other party has difficulty hearing me. When I disable Adguard or switch off wifi, the call improves significantly. Is there a way to let Adguard avoid Wi-Fi calling? All awhile with carrier T-Mobile.
> 

  "deviceName" : "samsung SM-G950U",
  "dnsFilteringEnabled" : true,
  "enabledFilterIds" : [ 2, 3, 4, 14, 11 ],
  "iconType" : "LOW_PRIORITY",
  "proxySetupManualMode" : false,
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":false,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "upstreamProxySettings" : null,
  "versionName" : "2.8.76",

ID, logs: 1224805

**Comment by TPS** [comment]
#233, originally, but it's back, I guess. 😖

**Comment by ameshkov** [comment]
> "versionName" : "2.8.76",

@evgeniy-ADG please ask him to install 2.9 first and then report back if Wi-Fi calling is still an issue

**Comment by vozersky** [comment]
@evgeniy-ADG any updates?

**Comment by evgeniy-ADG** [comment]
no updates, the customer replied that he'll check and get back by he didn't. we have another issue here: 1288741, with logs and description, have a look pls.

**Comment by ameshkov** [comment]
> no updates, the customer replied that he'll check and get back by he didn't. we have another issue here: 1288741, with logs and description, have a look pls.

Should be filed as a new issue (Wi-Fi calling Verizon)

**Comment by evgeniy-ADG** [comment]
okay will do
