### ISSUE TITLE
MiniMiniplus.pl

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardForAndroid#1199]
Adquard blocks videos on miniminiplus.pl . Can you add fix ? AQ should block adds, but player without ads should be unblocked. Is it possible ?

**Comment by vozersky** [comment]
@seba2282 

can't reproduce, for example,  http://www.miniminiplus.pl/filmy/z/rybka-minimini is played fine
which video is blocked for you? 
what filters do you use?

**Comment by vozersky** [comment]
btw, we usually discuss filtering related issues here: https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by seba2282** [comment]
With filtering DNS, without is ok. But I added one user filter for adocean and blocked ads on this site : ||adocean.pl/*ad.xml$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,important

**Comment by vozersky** [comment]
"Filter DNS requests" doesn't affect those videos for me, can you send us logs? 

@Alex-302 assist please

**Comment by seba2282** [comment]
How can I add this logs, if with filtering dns AQ blocks videos ; without filtering DNS + user filter ||adocean.pl/ad.xml$replace=/(<VAST[\s\S]?>)[\s\S]*</VAST>/$1</VAST>/,important - AQ blocks ads, but videos work fine without ads in players ?

**Comment by seba2282** [comment]
I have monit : 
![screenshot_2017-05-06-18-30-27](https://cloud.githubusercontent.com/assets/16944478/25774513/78278642-3290-11e7-9b60-c6cf352eb4c8.png)

And options filtering dns and https. I know, AQ blocks AdOcean and Gemius. I have question. Can AQ Team add anti adblocker for AQ products (Android, Extensions for Browsers, Windows) ? I want, AQ should definitely block all ads.

**Comment by seba2282** [comment]
I added
@@||tvn.adocean.pl
@@||cdntvn.pl
||redcdn.pl
to my filters and temporally I fixed my problem. :) All videos now works without ads. :)

**Comment by seba2282** [comment]
Without exclussions on user's filters. 
Turn on : 
![screenshot_2017-05-17-10-10-40](https://cloud.githubusercontent.com/assets/16944478/26144571/a30da236-3ae9-11e7-9e43-9f79496a6a2b.png)
and : 
![screenshot_2017-05-17-10-10-53](https://cloud.githubusercontent.com/assets/16944478/26144589/b5aba5d2-3ae9-11e7-8208-1a9db0052499.png)

miniminiplus.pl/filmy and turn on some video. And you should see it : 
![screenshot_2017-05-17-10-11-37](https://cloud.githubusercontent.com/assets/16944478/26144635/e4db0640-3ae9-11e7-9053-f3d9f28f2835.png)
If add @@||tvn.adocean.pl and @@||cdntvn.pl It will work. 
Please add filters from certificate it for Adquard Android (example KAD). And reek killer isn't continuing, I think, so waiting for your dedicated Adquard Anti Adblock killer/protector. 

Best Regards

**Comment by vozersky** [comment]
> If add @@||tvn.adocean.pl and @@||cdntvn.pl It will work.
Please add filters from certificate it for Adquard Android (example KAD)

@Alex-302 could you please assist with filtering rules here? can we add those exclusions?


@seba2282 thanks for letting us know! and about anti adblock scripts: please use our [Annoyances](https://blog.adguard.com/en/annoyances-filter/) filter

**Comment by seba2282** [comment]
@vozersky Without DNS filtering we don't need any rule. I think, AQ Team should block all domain with ads (adocean, redcdn, etc) and they should integrated hiding and scripting anti adblock protection for AQ in filter for all versions AQ (extension, android, windows, etc). They should remove aak (reek), because it isn't continuing. It is my sugest. I try generally block adocean, gemius, and more, because popups are frustrating and sometimes after clieck ads we go to infected site.

**Comment by Alex-302** [comment]
It is not a good idea to remove adocean.pl from DNS filter.
Added to Mobile filter
```
@@||tvn.adocean.pl^$domain=miniminiplus.pl
||adocean.pl/ad.xml$domain=miniminiplus.pl,replace=/"enabled":true\,/"enabled":false\,/i,important
```
check these rules

**Comment by seba2282** [comment]
![screenshot_2017-05-18-10-02-49](https://cloud.githubusercontent.com/assets/16944478/26192263/483518d0-3bb1-11e7-98e9-fcd805ab1339.png)

![screenshot_2017-05-18-10-02-28](https://cloud.githubusercontent.com/assets/16944478/26192280/52c0832a-3bb1-11e7-932a-d7b426c2f422.png)

**Comment by Alex-302** [comment]
try without $domain:
`@@||tvn.adocean.pl`

**Comment by seba2282** [comment]
?? 
![screenshot_2017-05-18-10-52-33](https://cloud.githubusercontent.com/assets/16944478/26194355/6b710df2-3bb8-11e7-815a-8fb52c789c7e.png)
![screenshot_2017-05-18-10-53-27](https://cloud.githubusercontent.com/assets/16944478/26194366/76354780-3bb8-11e7-8671-5f9190ac5daf.png)

or wait few minutes

**Comment by seba2282** [comment]
![screenshot_2017-05-18-10-57-04](https://cloud.githubusercontent.com/assets/16944478/26194506/e72e2b64-3bb8-11e7-992d-f0b872f6394c.png)
![screenshot_2017-05-18-10-57-37](https://cloud.githubusercontent.com/assets/16944478/26194519/ee6bc15c-3bb8-11e7-83fc-c702e2e45185.png)

**Comment by seba2282** [comment]
@Alex-302 , did you added any rules for miniminiplus.pl ? I delete all rules and testing without user's filters and videos are blocking. I wrote, if I enable dns filtering, rules type @@||tvn.adocean.pl and @@||cdntvn.pl work for me. But I don't know when will plan show me ad as short popup. I think, if domain connected with redcdn.pl, popup will show. With analyze code site, player with video is as cdntvn. I think that.

**Comment by Alex-302** [comment]
tvn.adocean.pl is used for a lot of sites without issues. With DNS filtering it is impossible to make domain specific exclusion, so I can't add that exclusion.
But you can disable DNS filtering.

**Comment by seba2282** [comment]
Hmmm... User's filters work. I added two rules (tvn.adocean.pl and cdntvn.pl) and minimini+ working with dns. Did you never analyze site with activing dns filtering in AQ Android ?

**Comment by seba2282** [comment]
Without dns filtering I have it always : 
![screenshot_2017-05-18-17-38-08](https://cloud.githubusercontent.com/assets/16944478/26210755/f3b47284-3bf0-11e7-9b94-e58cb0192699.png)
and 
![screenshot_2017-05-18-10-57-37](https://cloud.githubusercontent.com/assets/16944478/26210783/071e21a8-3bf1-11e7-8f3e-d986c8a9f61a.png)
I am waiting on anti adblocker protector by AQ.

**Comment by altokarev** [comment]
seba2282 commented 8 hours ago:
> About Firefox... I have a question about Firefox Android. Why Adguard, Ublock Origin or etc not block blocking video ads by redcdn.pl domain on example miniminiplus.pl ? I see all time big popup with this video ads. Is it bug in Firefox or in blockers ? Sorry my question.
@Alex-302 pls take a look. Thanks.

**Comment by Alex-302** [comment]
I need sample url.

**Comment by seba2282** [comment]
Ok. You need Firefox Android + Adguard extension. Reek filter and acceptable ads disabled, all filters activated. And testing miniminiplus.pl/filmy . After few time you will see big popup ads video.

**Comment by seba2282** [comment]
Few films video maybe any problem but after...

**Comment by vozersky** [comment]
Please do not discuss filtering issues in the product repo.
@altokarev move it to the [appropriate repo](https://github.com/AdguardTeam/AdguardFilters), thanks.

**Comment by altokarev** [comment]
#5558
