### ISSUE TITLE
Add more filter subscriptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#12]
We should add all popular filter subscriptions (like EasyList, Fanboys and such).

**Comment by hajosattila** [comment]
Which version do you expect this request, 3.0?
only good Hungarian filter: 

https://ajnasz.hu/adblock

abp://subscribe/?location=https://ajnasz.hu/adblock/recent&title=Ajnasz.hu%20Subscription%20List%20-%20Adblock%20lista

Sorry for my bad English
