### ISSUE TITLE
[Feature request] Add an option to "Browse" file system for a file to import to user filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#120]
@Revertron do you know any simple-to-integrate component for file system browsing?

**Comment by Alexey71** [comment]
Как успехи?, 3 месяца почти прошло

**Comment by ameshkov** [comment]
Пока не то чтобы сильно успешно.

@Revertron так что, не подскажешь какой-нибудь простой компонент, который можно интегрировать?

**Comment by Alexey71** [comment]
К релизу не ожидать,  видимо)

**Comment by ameshkov** [comment]
Ну не к ближайшему точно:)

**Comment by TPS** [comment]
My 2¢: I use https://github.com/openintents/filemanager as a stand-alone, & I understand they intentionally designed the source to be easy to work with.  Maybe it might be helpful?

**Comment by ameshkov** [comment]
@TPS thanks for the link!

It is easy to integrate with this app indeed:
http://stackoverflow.com/questions/8496482/how-do-i-browse-the-filesystem-in-android-using-a-third-party-component

But that's in case if this file manager is already installed. Bundling their code into our app seems to be an overkill.

We may also use this component:
https://github.com/dibakarece/AndroidFileExplorer

Or just implement the file browser by ourselves:
http://www.christophbrill.de/en_US/how-to-create-a-android-file-browser-in-15-minutes/

That's really weird Android still does not provide a standard component for this.

**Comment by TPS** [comment]
You're welcome, of course.  Why don't you all provide the correct intents, anyway, if/when implementing the above code, so that those of us who prefer _our own_ installed file browser can use it, maybe toggled via a new setting?

>That's really weird Android still does not provide a standard component for this.

I think the closest available is detailed starting from http://developer.android.com/guide/topics/providers/document-provider.html

**Comment by ameshkov** [comment]
> You're welcome, of course. Why don't you all provide the correct intents, anyway, if/when implementing the above code, so that those of us who prefer our own installed file browser can use it, maybe toggled via a new setting?

This intent is not standard, it is specific to the OI File manager. We can send it or not, it just does not solve the issue. For instance, what if I don't have a file manager app at all?

> I think the closest available is detailed starting from 
> http://developer.android.com/guide/topics/providers/document-provider.html

Too much abstractions there. What we all need is simple "OpenFileDialog" component.

**Comment by TPS** [comment]
>This intent is not standard, it is specific to the OI File manager.

I'm not sure.…  Reading through https://github.com/openintents/filemanager/blob/master/FileManager/AndroidManifest.xml, this relevant-looking section seems generic enough:
```xml
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <data android:scheme="file" />
</intent-filter>
```

Other apps that implement an "Open File" mechanism (mostly office programs — Google Docs & related, OfficeSuite, PDFMax, &c) seem to call that intent, I think, & the Android (4.4) system responds with a dialog that gives whatever file manager as an _options_:
![File dialog from http://www.addictivetips.com/android/lesser-known-android-4-4-kitkat-features/](http://cloud.addictivetips.com/wp-content/uploads/2013/11/Android-4.4-KitKat-Lesser-Known-Features-Advanced-File-Picker-02.png)
A file manager would show up in the section where Gallery & Photos appear in the lower left of the above.

**Comment by ameshkov** [comment]
@TPS hm, you may be right (shame on me then:)), we'll check it.

**Comment by TPS** [comment]
The intent could also be
```
intent:#Intent;action=android.intent.action.GET_CONTENT;type=*/*;launchFlags=0x1000000;end 

ACTION:android.intent.action.GET_CONTENT 
DATA:null 
TYPE:*/* 

FLAGS:
FLAG_ACTIVITY_PREVIOUS_IS_TOP
```

I'll see what else I dig up.

**Comment by Alexey71** [comment]
Привет. Как дела с кнопкой?)

**Comment by ameshkov** [comment]
@Alexey71 спасибо, что напомнил:) планирую на v2.6.
Translation: thanks for the reminder. I've assigned it to v2.6 now.


@TPS time to learn russian eh? github reactions are hilarious:)

**Comment by TPS** [comment]
Well, GTranslate usually works (enough ;) for me to get a clue, but
>Привет. Как дела с кнопкой?)

above GTranslated to "Hey.  How's the button ? )"  Big help! :confounded:

**Comment by ameshkov** [comment]
Translation is correct, he means "How's the Browse button":)

**Comment by TPS** [comment]
:bulb: :exclamation:

**Comment by Revertron** [comment]
Done! :-)
