### ISSUE TITLE
Free version - add a choice of the main browser to use

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1200]
We have a request to add an option to choose one main browser to be filtered. For example, Google Chrome is marked as filtered by default, but if I am using Opera Mini, this feature is almost useless.

Ticket ID: 1549624

**Comment by vozersky** [comment]
@KozelElena 
The thing is, Opera Mini is not supported since it routes all traffic through Opera servers.
All normal browsers are filtered even in free version, you don't have to choose anything.
