### ISSUE TITLE
nh.smart.nhallonepay - https filtering issue

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#1201]
The app does not launch.
If I exclude the app from https filtering, the app launches.
Play store link: https://play.google.com/store/apps/details?id=nh.smart.nhallonepay
 - This app is a banking app.
 - To launch this app, it requires installing another app com.ahnlab.v3mobileplus

**Comment by nkartyshov** [comment]
@seanl-adg The com.ahnlab.v3mobileplus is banking app?

**Comment by seanl-adg** [comment]
no, it is a 'security' app.

**Comment by nkartyshov** [comment]
added
