### ISSUE TITLE
Make "Filter DNS requests" work on rooted devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1203]
We should find a way to apply DNS filtering on the rooted device.

Here is the easiest way: start up a UDP server and set Android to use it as a DNS server.
What's important, we can actually reuse this approach for the VPN-based DNS filtering (redirect DNS requests to this local UDP server).

**Comment by nkartyshov** [comment]
Added, review AFA-CR-2
