### ISSUE TITLE
ivideon app - https filtering issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1204]
https://play.google.com/store/apps/details?id=com.ivideon.client&hl=ru

> I've been having an issue with a live camera feed app called Ivideon.
> The app has been streaming video up until last month or so. I raised
> a bug report with the Ivideon team and we've found that adguard was
> stopping the streams. Strangely, older versions of Ivideon did work
> with adguard. To fix the issue, I've turned off HTTPS filtering for
> the Ivideon app in adguard. I'm just wondering what the issue could
> be?

ID: 1372866

**Comment by nkartyshov** [comment]
Added app in https exclusion
