### ISSUE TITLE
Show filter names in state.txt instead their IDs

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1205]
because some users use too many filters
"enabledFilterIds" : [ 2, 3, 14, 10, 1, 6, 7, 8, 9, 13, 5, 11, 15, 102, 103, 104, 105, 108, 109, 111, 112, 113, 114, 121, 116, 222, 216, 217, 211, 218, 223, 226, 224, 227 ],

**Comment by nkartyshov** [comment]
done
