### ISSUE TITLE
Grab app - can't connect to the server

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1206]
Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25580204/85c1ff88-2e87-11e7-9eda-1f130a63c999.png)

</details>
Tried to disable all filters, HTTPS filtering, switching filtering mode and quality - without result.
Log without HTTPS filtering:

[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/970759/adguard.log.txt)

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/4903

**Comment by nkartyshov** [comment]
Added domain **grabtaxi.com** in https white list.
