### ISSUE TITLE
I can't navigate this site with adguard protection enabled

### ISSUE THREAD

**Issue by Snake87r** [AdguardTeam/AdguardForAndroid#1207]
Hello, after 5 second you open the page appear an advice,  "it look like your using an adblocker" and i can't read the page..
This is the webpage:
http://www.lesyt.xyz/novels/tsa/tsa-ch-66/

This is the protection they use:
https://blockadblock.com
https://blockadblock.com/blockadblock_basic_script.php

They say they block adguard and other program..

**Comment by seanl-adg** [comment]
Next time please post such issues in https://github.com/AdguardTeam/AdguardFilters :)
