### ISSUE TITLE
speedtest app - Adguard distorts the speedtest results

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1208]
Скорость по Wi-Fi до 80 М/бит, с adguard 40-45 М/бит. Других программ фильтрации нет.
Когда отключаю все фильтры - скорость не меняется. Алгоритм фильтрации изначально стоит Быстрый алгоритм.
Попробовал закачку через uTorrent с вкл Adguard - скорость нормальная.

Лог в тикете 1128606, см. письма от 27 и 28 апреля.

  "versionName" : "2.9.70",
  "deviceName" : "THL thl 5000",
  "enabledFilterIds" : [ 2, 3, 4, 1, 11 ],
  "filteringQuality" : "SPEEDY",
   "sslMitmConfiguration" :
 {\"mitmListMode\":\"WHITELIST\",\"filterEvCertificates\":true,\"mitmList\":\"1496 domains\",\"certificateInstalledToSystemStorage\":false}",
  "org.zwanoo.android.speedtest;version=3.2.29

**Comment by TPS** [comment]
Related to #1192 & #741.

Is HTTPS filtering active? Does turning it off help?  I suppose #501 _might_ need re-examining.

GTranslate of the above, for those of us who can't Russian:
>Speed ​​over Wi-Fi up to 80 M / bit, with adguard 40-45 M / bit. There are no other filtration programs.
When I turn off all filters - the speed does not change. The algorithm of filtering is initially worth a fast algorithm.
Tried to download via uTorrent from on Adguard - the speed is normal.
>
>The log in the ticket is 1128606, see letters dated April 27 and 28.

Is that mostly right?  The part I understand least is "The algorithm of filtering is initially worth a fast algorithm." 🤔

**Comment by evgeniy-ADG** [comment]
@TPS The customer uses the Speedy filtering mode, he doesn't have any other apps for traffic filtering and disabling filters changes nothing. The only thing that helps is quitting Adguard.

There's another complaint that might be related (not sure though): https://github.com/AdguardTeam/AdguardForAndroid/issues/1213

**Comment by ameshkov** [comment]
@evgeniy-ADG we cannot do anything with that.

The situation will improve once new tcp stack library is ready:
https://github.com/AdguardTeam/CoreLibs/issues/9
