### ISSUE TITLE
Add editing option to the Android version

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1210]
We've got a request about adding an editing option to the mobile version instead of deleting and adding the mistyped domain, for example.

Ticket ID:1550230

**Comment by TPS** [comment]
Related to #308 & #828.

**Comment by uBlock-user** [comment]
Yes, a very needed option apparently.

**Comment by TPS** [comment]
> I guess that's about both user filter & whitelist?

@ameshkov Really, _anyplace_ we can add (freeform) to a list, present & future.

**Comment by TPS** [comment]
When in filter-editing mode (either from filtering-log or anyplace else), it'd be great to have additional toggles like `$important` for `$image`, `$script`, &c.

**Comment by ameshkov** [comment]
Duplicate of #1279
