### ISSUE TITLE
com.zenstudios.alienpinball - network issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1211]
Can't start the game.
Current behaviour:

<details>

![image](http://i47.fastpic.ru/big/2017/0505/a1/2c574eca52354fe794e3d84400ee21a1.jpg)
</details>

Expected:
<details>

![image](http://i89.fastpic.ru/big/2017/0505/7d/0d9b652e6b9ef21cfe19e2d08d42f77d.jpg)
</details>

Adding `zenstudios.com` th HTTPS exclusions seems to be helps, but this domain is not HTTPS, alco $document exclusion doesn't help.

https://forum.adguard.com/index.php?threads/android-zen-studio-apps.21453/

**Comment by nkartyshov** [comment]
Added domain zenstudios.com in https whitelist.
