### ISSUE TITLE
Сделать нормальный поиск

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1212]
Adguard версия 2.9, настройки приложения и далее поиск. Искать что либо вообще неудобно, скрины ниже я прикрепил. Я ввожу текст и напрочь отсутствует черная линия, непонятно, то ли я ввожу, то ли прога зависла. Последний скрин - это как должно быть
![screenshot_2017-05-07-20-43-48](https://cloud.githubusercontent.com/assets/22351242/25783552/82eb862e-3366-11e7-928f-53c3fe5bde28.png)
![screenshot_2017-05-07-20-43-53](https://cloud.githubusercontent.com/assets/22351242/25783553/88049ba0-3366-11e7-888b-4a443db480cd.png)
![screenshot_2017-05-07-20-46-14](https://cloud.githubusercontent.com/assets/22351242/25783554/8c4eeaee-3366-11e7-97cd-da4cceaafdb3.png)

**Comment by ministr91** [comment]
@ameshkov

**Comment by ameshkov** [comment]
А это какая версия андроида?

**Comment by ministr91** [comment]
Nexus 5 Android 4.4.4

**Comment by ministr91** [comment]
Я бы обновил свой Android до 6 версии, но интерфейс что 5, что 6 просто ужасен, поэтому остаюсь на 4.4.4

**Comment by ameshkov** [comment]
В четвертом дроиде уже мало что сделать, интерфейсные библиотеки на них не особо расчитаны. И так там костылей стоит под четверку достаточно:)

**Comment by Revertron** [comment]
Самое интересное то, что мы специально задаем цвет курсора в том поле. Почему-то он не применяется системой.

**Comment by ministr91** [comment]
@Reverton, вот именно, почему так? Можешь исправить? Или скажи что мне сделать надо, чтобы исправить, я могу потестить

**Comment by ministr91** [comment]
@ameshkov и @Revertron есть идеи?

**Comment by ameshkov** [comment]
Если бы было легко исправить, мы бы давно сделали. Но раз стандартные подходы не работают, мы забили, нет возможности тратить несколько дней на мелкий фикс для 4.X когда у нас и так завал с более серьезными задачами.
