### ISSUE TITLE
Viber and WhatsApp file transferring speed slows down

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1213]
File transferring via Viber and WhatsApp is slow due to Adguard. It drops from 100 Mbps to 14-17 Mbps according to the customer. The ping increases from 2-3 ms to 98-102 ms. The issue occurs with both HQ and Speedy modes.

You can find a debug log here: 1237702

  "versionName" : "2.9.70
  "deviceName" : "asus ASUS_Z00AD",
  "deviceSpeedRank" : 92,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 14, 10, 1, 11 ],
  "filteringQuality" : "SPEEDY",
  "proxyMode" : false

**Comment by ameshkov** [comment]
It's possible on a slow device (plus #1192 issue is what's responsible for ping).

Will be better once https://github.com/AdguardTeam/CoreLibs/issues/9 is finished

**Comment by evgeniy-ADG** [comment]
The customer insists that it didn't get better. The new set of logs here: 1237702 (August 3, 23:03).

**Comment by ypetruk** [comment]
Update from the user (ID:1237702)
device : Asus ZenFone2 ZE551ML 
until a particular moment, everything worked just fine
the only enhancement is that ping is no longer 100 ms but 7-10
The download speed is 92 мбит/сек. 
transmission speed has gotten worse

**Comment by altokarev** [comment]
There will be a new beta build with a new network stack implemented next week. Maybe this will help to fix an issue.

**Comment by ypetruk** [comment]
Комментарий от ticket ID:1237702
Сейчас обновился до актуальной бета-версии.
-скорость загрузки при использовании Adguard сохраняется на уровне 94 мбит/сек, а иногда возрастает до 96-98 мбит/сек.
-пинг при использовании Adguard с 2-3 мс до 4 мс.
-скорость передачи при использовании Adguard составляет 75-80 мбит/сек вместо 94-98 мбит/сек без использования Adguard.
То есть ситуация немного улучшилась, но не до конца.
Когда я покупал ваш продукт таких проблем не было. То есть нужна доработка. Измерение скорости осуществлялось приложением Speedtest.
-- Show HTML message --
