### ISSUE TITLE
Create a filter for redirects from mobile providers 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1217]
Create a separate filter in with sites with mobile operator subscriptions. 
Ad websites make a redirect to such paid mobile subscriptions.

Ticket ID: 1557763

**Comment by Bluscream** [comment]
A new face in the team? Welcome ;)

**Comment by vozersky** [comment]
We used to discuss it some time ago. Not sure if this could be done with filtering rules though.
I think, this kind of websites should go directly to Safebrowsing database.

**Comment by TPS** [comment]
@vozersky #80?

**Comment by ameshkov** [comment]
Dup of #80
