### ISSUE TITLE
[Feature request] Show current license key somewhere in "License" screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#122]

**Comment by TPS** [comment]
I suppose this means the website (non-Amazon) versions — or do those use a license key internally, also? (I'm thinking of that part of #93 that deals with listing Amazon license in AdGuard account website.…)

**Comment by ameshkov** [comment]
We have different "manage license" views for amazon-activated and license-activated.

**Comment by vozersky** [comment]
we do now
