### ISSUE TITLE
Rules constructor ignores referer

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1221]
For example, go to echo.msk.ru and try to unblock st.top100.ru
Current behaviour:
<details>

![image](http://imagizer.imageshack.com/img922/2199/aoBzPl.jpg)
</details>
Expected:

```
@@||st.top.ru^$domain=echo.msk.ru
```
Filtering log record:
`TCP id=1000522 GET ads=1 "http://st.top100.ru/top100/top100.js" 500 24 2ms "http://echo.msk.ru/" `

**Comment by nkartyshov** [comment]
Done, review AFA-CR-15
