### ISSUE TITLE
Cannot apply specific rules to the AMP websites

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1222]
The page URL looks like this:
```
https://www.google.com/amp/mobile.reuters.com/article/amp/idUSKCN18A0TU
```

Even though the site is mobile.reuters.com, AG sees it as google.com. I guess we should introduce special rules for the AMP websites.

**Comment by seanl-adg** [comment]
The main content is contained in an iframe of domain `mobile-reuters-com.cdn.ampproject.org`, so `domain` modifiers and such can still be used. We just need new rules for the website.
