### ISSUE TITLE
Firewall UI inconsistency

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1224]
When Firewall is disabled, its settings are grayed out. However, if you go to the main screen and then back to Firewall settings, they are active again. 

Also, per-app settings in App Management are still active when the Firewall is disabled - a bug or 'by design'?

**Comment by vozersky** [comment]
reproduced

**Comment by TPS** [comment]
It _might_ be useful to have firewall settings accessible, even when disabled (to change, &c), but it'd ve nice to have a banner on each screen, _saying_ "Firewall is disabled. Enable?"

**Comment by zebrum** [comment]
a lot of mess with all those checkboxes in Apps Management - Settings: they are not applied at all 	
frequently. 
e.g. go to Apps Management - Settings - uncheck any of Defaults checkboxes, then go back and see there are no changing in firewall settings. Again go to Settings - Adguard did not save changes you made. But If you wait about a minute not going anywhere from the first settings screen the changes will be applied.

**Comment by TPS** [comment]
WFM, @zebrum: I don't see that @ all.

**Comment by zebrum** [comment]
@TPS it's easy to reproduce.
On the other hand when you change settings with Bulk change option, they are applying correctly.

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-69
