### ISSUE TITLE
Add Juvander's Adblock List

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1225]
https://adb.juvander.net/Finland_adb.txt

**Comment by nkartyshov** [comment]
added, review AFA-CR-8

**Comment by ameshkov** [comment]
@nkartyshov according to @TommiHynynen's [comment](https://github.com/AdguardTeam/AdguardFilters/issues/3718#issuecomment-301895575) we'd better have Juvander's list used as a default filter for Finnish people (instead of Wiltteri)

**Comment by nkartyshov** [comment]
I added Juvander's list as a default filter for Finnish people and I removed Wiltteri filter.
