### ISSUE TITLE
CM Security caused an Aadguard restart

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1226]
> The filtering log is showing that URLs that are normally blocked, weren't. I also noticed that, while running CMAV/CM Security Master/whatever-it-calls-itself, AG notification icon suddenly went away, & a toast saying "AG is starting up" (or equivalent) popped up. AG is whitelisted w/ CMAV.

com.cleanmaster.security;version=4.0.0
Adguard 2.9.70

Please check logs: 1122984

**Comment by vozersky** [comment]
@nkartyshov could you please assist with this?

**Comment by ameshkov** [comment]
@vozersky can you reproduce it?

**Comment by vozersky** [comment]
@ameshkov I wasn't. 

`00:46:35.602 [main] INFO  c.a.a.f.vpn.FilteringVpnService - On trim memory to 10
00:46:35.603 [main] INFO  com.adguard.android.ServiceManager - Trim memory 10 called`

This is the reason Adguard was restarted, I think




@evgeniy-ADG what exactly were the customer doing with `com.cleanmaster.security` when he experienced it?

**Comment by TPS** [comment]
>what exactly were the customer doing with com.cleanmaster.security when he experienced it?

I'm the customer, @AdGuardTeam, so AMA! 😁

I'd just updated to latest version of CMAV (now called "CM Security Master" 😶), & was in process of opening it when this happened.

**Comment by TPS** [comment]
It just happened again. Y'all should be receiving report momentarily.

**Comment by OlegSUP** [comment]
New logs attached in ticket 1122984.

**Comment by TPS** [comment]
… &, again, just now.  This time, I was CM Private Browsing (#18) BestBuy.com

**Comment by TPS** [comment]
I just realized that my connection seems faster since AG auto-reconnect.  Is it possible this is connected to #1202?

**Comment by ameshkov** [comment]
I guess we'll need to get logcat log

**Comment by TPS** [comment]
Next time I have it happen, I'll try that.  (I haven't attempted logcat on this phone yet.)

**Comment by TPS** [comment]
Since many updates to CMAV, I can't replicate anymore, so recommend closing.

**Comment by vozersky** [comment]
please let us know if it happens again
