### ISSUE TITLE
Adguard does not block app ads on mobile data mode again

### ISSUE THREAD

**Issue by mozkan007** [AdguardTeam/AdguardForAndroid#1228]
Hi @ameshkov I am sorry to reopened this issue [issue992](https://github.com/AdguardTeam/AdguardForAndroid/issues/992) you have solved it but it happens again.I am using Adguard v2.9.70 and it blocks app ads and website ads on chrome successfully on wifi mode.However when I use Adguard on mobile data mode, it blocks website ads on chrome in the same way but it does not block any app ads.I enabled Adguard DNS on pref. setting and also I use filtering log to block domains which cause this issue but the case does not change.

**Comment by vozersky** [comment]
@mozkan007 I've reopened #992 , please discuss the issue there
