### ISSUE TITLE
Https filtering breaks yandex apps

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1229]
so far we know about: yandex.Maps and yandex.Transport

ticket id 1544081, 1561239, 1561605, 1029341

Adg 2.9.70

disable https filtering helps.

**Comment by ameshkov** [comment]
Major

**Comment by vozersky** [comment]
any updates?

**Comment by ameshkov** [comment]
Assigned to v2.9 R2

**Comment by nkartyshov** [comment]
Added apps in https exclusions. Review AFA-CR-7.

**Comment by ameshkov** [comment]
This is good old "we cannot detect underlying protocol properly" issue.

**Comment by ameshkov** [comment]
Resovled by https://github.com/AdguardTeam/HttpsExclusions/commit/8ab3f66b8337648736390ee7734acacf4c6dfdd2
