### ISSUE TITLE
[Feature Enhancement] (Functional) Shortcut should be allowed in [either, both] hotseat & folders

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#123]
This is especially important in smaller devices — i.e., those of us who _aren't_ carrying around an UHD TV & calling it a "mobile device." :wink:

**Comment by ameshkov** [comment]
As I know it's impossible to put a widget to a folder

**Comment by TPS** [comment]
Well, I have several in folders (on the hotseat ☺) right now: Greenify's Hibernate Now & CleanMaster's App Boxes, 1-Tap Boost, & Hibernate.  Perhaps check them out?

**Comment by ameshkov** [comment]
These are not widgets but "Shortcuts". The difference is that shortcuts aren't interactive.

**Comment by TPS** [comment]
Ok, then could we get a shortcut without the interaction, but with the same functionality as the widget, for the reasons above?

**Comment by ameshkov** [comment]
It is possible, why not. The only question is how to create shortcut properly. CM just creates the shortcut right after app first run. I am not sure if this is a good way.

Also we'll need to draw the proper icon and choose the name. We won't be able to change the icon (as I've said, shortcut is not interactive).

**Comment by TPS** [comment]
All of CM's shortcuts can be recreated via the menu in the appropriate section *in* the app, so the same should be doable with AG.  As for icon & name, just straight AG icon with :recycle: or similar overlay, named "Toggle AdGuard" should do, but do let the marketing folks @ it. ☺

**Comment by TPS** [comment]
It occurs to me, if you want the interaction that's lost when converting from widget to functional shortcut (if the icon popping up in the notification bar _isn't_ enough), do what the CM family does: animated screen overlays!  They don't have to be full-screen like most of theirs, but the initial part of their animations usually starts with animating over the shortcut itself, which wouldn't be (very? ;) tacky.

**Comment by ameshkov** [comment]
Overlays is a good idea, you're right.

Also full-screen is an easy solution - it's hard to detect where shortcut is located so animation shouldn't be linked to the shortcut. I suppose it could be a progress bar overlay or something like that.

**Comment by TPS** [comment]
Basically, the equivalent of the widget as an overlay, perhaps: AdGuard shield going from white → yellow → green on activation, & vice versa for deactivation.  N.B.:  Requires a new permission, I think, for drawing on the screen.

**Comment by ameshkov** [comment]
One more shortcut request:
http://forum.xda-developers.com/showpost.php?p=66095100&postcount=886

**Comment by Revertron** [comment]
The shortcut is working well.

**Comment by calisro** [comment]
Shortcut is perfect. Thanks!

**Comment by TPS** [comment]
I want to thank @AdguardTeam on accomplishing this so well! :bow:

**Comment by TPS** [comment]
I forgot to ask:  [Are overlays still planned?](#issuecomment-157066255)

**Comment by TPS** [comment]
Also, while on airplane mode, shortcut turns off VPN, but won't turn it on.…

**Comment by ameshkov** [comment]
> Also, while on airplane mode, shortcut turns off VPN, but won't turn it on.…

In theory, on airplane mode VPN won't start anyway (even with a main button).

> I forgot to ask: Are overlays still planned?

Nope, progress dialog is just too annoying

**Comment by TPS** [comment]
Actually, this is my primary use for the widget, because of #520.

**Comment by ameshkov** [comment]
> Actually, this is my primary use for the widget, because of #520.

Just guessing, but maybe switching "pref.vpn.disable.pause" could help

**Comment by TPS** [comment]
As detailed in #520, not enough.…  Is there anyway to have the shortcut work precisely the same as widget in this instance.

**Comment by ameshkov** [comment]
> As detailed in #520, not enough.… Is there anyway to have the shortcut work precisely the same as widget in this instance?

I meant that it could help with starting app in airplane mode. So it does not help?

**Comment by TPS** [comment]
OIC, I've that option permanently on, anyway, but, no, it seems not to fix it. 😞
