### ISSUE TITLE
Show filters which blocked an element in the Filtering log

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1230]
**Original request**
We've got a request to show filter name with the rule that blocked an ad or element
Ticket ID: 1203834

**What should be done**

First of all, you should change FilterService.getAllEnabledRules so that it returned Map<Integer, List<String>> instead of a plain list. Pass the list down to the nativeUrlFilter which provides `addRule(ruleText, filterId)` method. For the DNS filtering, there are two different filter lists: user filter and simplified domain names filter.

**Comment by nkartyshov** [comment]
Done, review AFA-CR-58
