### ISSUE TITLE
Create a small dragging widget

### ISSUE THREAD

**Issue by Elenve** [AdguardTeam/AdguardForAndroid#1231]
Screenshot: 

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26271942/ba76e422-3d15-11e7-9171-d12bf1c45180.png)

</details>

Ticket ID: 1558554

**Comment by TPS** [comment]
I personally find these _less_ clear than the existing style, so I vote for this to be an _additional_, than _replacement_, widget.

**Comment by TPS** [comment]
@ameshkov This implemented in latest ß as *only* widget.…  Ick.  Could we get the other back, perhaps additionally? 🙇

**Comment by zzebrum** [comment]
@TPS yep, that is a bug, thank you! I'll create a new task.

**Comment by vozersky** [comment]
merged into #3378
