### ISSUE TITLE
no adguard icon on VPN notification

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1232]
no adguard icon on VPN notification (android 5.1)

![image](https://cloud.githubusercontent.com/assets/25711093/26274503/ef088bee-3d53-11e7-81d1-8e495c824d34.png)
[debug (90).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1016035/debug.90.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1016036/state.txt)
CustomerID:1325165

**Comment by vozersky** [comment]
Can't reproduce on Meizu M3s Flyme 5.1.12.1G, Android 5.1
@Michael23456 
STR?
Does customer have some kind of custom theme\launcher etc.?

**Comment by Michael23456** [comment]
waiting for an answer from the customer

**Comment by Michael23456** [comment]
@vozersky the customer is using Classic Theme from Next Launcher
https://play.google.com/store/apps/details?id=com.gtp.nextlauncher

**Comment by ameshkov** [comment]
I guess it is the launcher's issue, not ours.
