### ISSUE TITLE
Feature request: split internet consumption statistics for wifi and Mobile internet

### ISSUE THREAD

**Issue by vtargonskyi** [AdguardTeam/AdguardForAndroid#1233]
Do you have any plans for implementing this feature?

From user: "Привет! В Андроид 7 в Контроле трафика
прекратили отражать информацию о
ежедневном расходе трафика в целом по
всем приложениям и по каждой
программе отдельно. В качестве
улучшения предлагаю дополнить вашу
программу статистикой расхода
трафика как за 1 день, так и выбранный
период раздельно по мобильной сети и
WiFi, как например это сделано в
приложении Traffic Monitor из Google Play. В этом
случае пользователям не придется
устанавливать дополнительно к вашей
Adguard программу для учета трафика.
Сейчас у вас трафик учитывается
трафик без разделения по WiFi и
мобильной сети."

Ticket ID: 1562265

**Comment by TPS** [comment]
#202?

**Comment by vozersky** [comment]
yep, duplicates #202
