### ISSUE TITLE
Samsung Pay Gear - unable to add a card

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1234]
com.samsung.android.samsungpay.gear;version=1.3.1703

> Не привязывается банковская карта в приложении Samsung Pay Gear при попытке зарегистрировать карту через часы Samsung Gear S3 frontier. Пишет 'Ошибка, повторите позднее'. Все решается отключением

TRNSLT: Cannot bind a credit card to Samsung Pay on Gear S3 Frontier watch, the "Error, please try again later" message appears. Disabling Adguard fixes it.

ID: 1561649

**Comment by evgeniy-ADG** [comment]
>

**Comment by vozersky** [comment]
Waiting for more details

**Comment by ameshkov** [comment]
No news
