### ISSUE TITLE
Allow multiple filters to be enabled as language-specific at once

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1235]
Related task: https://github.com/AdguardTeam/AdguardFilters/issues/5066

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-35

**Comment by vbagirov** [comment]
Three filters should be enabled automatically when Polish language is detected - 216, 217, 238.

**Comment by ameshkov** [comment]
Why cookies?

**Comment by vbagirov** [comment]
Should be 117 instead of 217 @nkartyshov

**Comment by ameshkov** [comment]
No it should not

**Comment by vbagirov** [comment]
Only 216 and 238 then.

**Comment by nkartyshov** [comment]
done
