### ISSUE TITLE
Seven Knight game gets a connection error with Adguard enabled

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1236]
Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26004083/43903ed6-373d-11e7-9c6f-44ab0a7c9295.png)
</details>
How to reproduce:
install, sign in, wait for update, then launch the game.
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/4997

Tried to exclude from HTTPS filtering, but it did not help:
```
control.kochava.com
crashreport.netmarble.com
graph.facebook.com
ltm.netmarble.com
marbleproduct.netmarble.com
mobileapi.netmarble.com
mobileauth.netmarble.com
netmarbleslog.netmarble.com
nmss.gcdn.netmarble.com
popup.netmarble.com
sknightsgb-config.netmarble.com
sknightsgb.gcdn.netmarble.com
```
Filters are disabled.

**Comment by vozersky** [comment]
@zebrum please check if disabling adblocking\https filtering helps

**Comment by zebrum** [comment]
@vozersky disabling https filtering doesn't help. Game works only if protection disabled.

**Comment by ameshkov** [comment]
If disabling ad blocking does not help, it might be that the game uses some protocol, which is simply incompatible with Adguard.

**Comment by ameshkov** [comment]
Does it work with any other VPN app (opera max for instance)?

**Comment by zebrum** [comment]
checked with tunnelbear VPN - the same problem.
In this case we should exclude the app's traffic from filtering by default?

**Comment by ameshkov** [comment]
Yeah, I guess that's the only way

**Comment by zebrum** [comment]
@nkartyshov please disable filtering for the game.

**Comment by nkartyshov** [comment]
done
