### ISSUE TITLE
Use swipe gestures to update filters

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#1237]
>Если можно, сделайте в будущих версиях Adguard, чтобы обновление фильтров происходило не только кнопкой «Обновить», но и свайпом вниз на главном экране приложения. Как обновляются страницы в браузере хром или клиенте ForPDA, Kate Mobile - это очень удобно! По привычке пытаюсь свайпнуть вниз в Adguard для обновления, а нет такого способа.

Ticket ID: 1079388

**Comment by vozersky** [comment]
merged into #3378
