### ISSUE TITLE
Change of plans - let's do HTTPs filtering first

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#124]
That's the most wanted feature at the moment.
So I suggest reordering our milestones and forcing AG 3.0 development.

**Comment by TPS** [comment]
Duplicate for #21, other than increase in priority?

**Comment by ameshkov** [comment]
Yep, we are thinking about reordering tasks. HTTPs filtering seems to be the most wanted feature now, so maybe it's better to delay other tasks. 

Everybody wants us to remove youtube ads:)

**Comment by ameshkov** [comment]
I have updated milestones section.

Updated due dates to something more realistic.
Reordered issues.

HTTPS filtering is now planned on the closest milestone - **version 2.5**.
Working on it, other issues are postponed.
