### ISSUE TITLE
Support "VPN Always-on" feature in Android O 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1240]
Starting from Android O users can enable "Always-ON" feature for any given VPN connection including Adguard.

<details>

![](https://cloud.githubusercontent.com/assets/5947035/26502830/07c1a54c-4247-11e7-9a1e-89e17aacf623.png)
</details>

Upon changing VPN properties Adguard's VPN service receives some commands from Android which at the moment it cannot parse.

**Comment by ameshkov** [comment]
Reassigned to v2.10 as implementing what I want requires some translators work.

The only problem I have is that when I switch that option on or off, AG goes to pause with a message like "Paused due to third-party VPN". 

**What should we do:**
1. Change the message text, it should be just "due to a third-party VPN" (not sure what should we do).
2. Add a "Start" button to that notification.

**Comment by ameshkov** [comment]
This clause is actually about the "always-on" feature only:
> The VpnService of VPN apps must now call its startForeground() method after launch. Because the Android system starts a VPN app's service directly, transitioning to the foreground is the app's responsibility. Android O shuts down VPN apps that don't transition the VPN service to the foreground.

So, I guess if "always-on" VPN feature is enabled, we should react on the empty intent Android sends us and start it immediately. We need to test it though.

**Comment by ameshkov** [comment]
One more thing -- if an app filtering is disabled in AG, this app won't have network access when you have the "always-on" enabled.

**Comment by TPS** [comment]
> if an app filtering is disabled in AG, this app won't have network access when you have the "always-on" enabled.

Alway-on has same behavior in Android < O? Anyway *that*'s a bit of a deal-breaker:  Those apps (often system) are usually 1s that only _function_ when AG filtering is _disabled_, right?
  Hopefully, https://github.com/AdguardTeam/CoreLibs/issues/9 will solve _that_, too.

**Comment by ameshkov** [comment]
> Alway-on has same behavior in Android < O? Anyway that's a bit of a deal-breaker: Those apps (often system) are usually 1s that only function when AG filtering is disabled, right?

We disable it by default for the apps that are broken by mere VPN presence, so the new TCP stack won't fix it. Examples: all kinds of MMS apps (this issue is specific to some US cellular providers), apps that use FTP protocol, etc. Another option -- by default we disable it for other VPN apps so that they could be used along with AG in Proxy+Root mode.

 You sure can enable it back in the apps management settings.

**Comment by TPS** [comment]
I guess I'll hafta wait & see if anything breaks for me when #760 lands.

**Comment by TPS** [comment]
["Block connections without VPN" toggle](https://github.com/AdguardTeam/AdguardForAndroid/issues/760#issuecomment-304323352) is somewhat of workaround for this, maybe.

I guess I'll hafta wait & see if anything breaks for me when #760 lands.

**Comment by ameshkov** [comment]
One more issue with it. When I have "block connections without VPN" enabled and reboot the device, cellular data won't work. Nothing helps except disabling always-on and rebooting device again.

I didn't check toggling airplane mode on and off, might worth a try. Overall, looks like an Android bug.

**Comment by ameshkov** [comment]
> "Block connections without VPN" toggle is somewhat of workaround for this, maybe.

That's what causes the issue.

I mean when "block connections without VPN" is enabled, connections are actually blocked for the apps, which are deliberately excluded from VPN by Adguard itself.

Frankly, I find this behavior rather weird, worth filing a bug report.

**Comment by Bluscream** [comment]
Any news here? ^~^

**Comment by ameshkov** [comment]
@Bluscream Android bugs are stil here, other than that AG is compatible

**Comment by Bluscream** [comment]
![](https://i.imgur.com/X91K9Hz.png)

**Comment by ameshkov** [comment]
Oreo only

**Comment by Bluscream** [comment]
What? Why does my android have this then if its unusable?

**Comment by ameshkov** [comment]
On older Android version an app needs to be a device admin, while on Oreo you can configure it for any VPN app you want.

**Comment by Bluscream** [comment]
You are laready requesting root at some point, so nothing wrong with having ag as device admin. Atleast better than these shady preinstalled device admins ^^

---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v.4.2.0

**Comment by ameshkov** [comment]
> You are already requesting root at some point, so nothing wrong with having ag as device admin. Atleast better than these shady preinstalled device admins ^

It'll take some time to develop all this stuff, and knowing that Oreo does not require it I'd like to avoid it

**Comment by Bluscream** [comment]
I would even force ag to be device admin if i could. It's already even a system app on my devices ^^

**Comment by ameshkov** [comment]
Leaving the task open for now, just to review it later
