### ISSUE TITLE
Change Adguard notification text so that it looked better on Andoird 6.0+

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1241]
The problem is more or less described on the screenshot:

<details>

![photo - google photos 2017-05-26 21-46-14](https://cloud.githubusercontent.com/assets/5947035/26508297/e3328e88-425c-11e7-9613-aa2ee97baa0a.png)
</details>

**Please note, that you should not reuse old strings for new notifications. Let people translate it properly**.

Depending on the current protection status, we should show different types of notifications.

### Protection is started

![adguard for android - notifications moqups 2017-07-26 15-21-56](https://user-images.githubusercontent.com/5947035/28620592-42fb81ba-7216-11e7-9323-672dadd88fab.png)

Stats string:
`Blocked: 321 of 1000 ● Saved: 1.84 MB of 32.21 MB`

Means that AG has blocked 321 requests of 1000 processed and bandwidth savings estimate is 1.84 MB of 32.21 MB.

Stats should be counted from the app startup (just use a static field to store it).
This notification should be used in all filtering modes (vpn, proxy+manual, proxy+auto).

### Preparing to start protection

![adguard for android - notifications moqups 2017-07-26 15-37-03](https://user-images.githubusercontent.com/5947035/28621072-5f26940e-7218-11e7-8ae9-b74439f485da.png)

### Proxy + manual when proxy is not yet set up

Special case when proxy mode is manual setup, but the user has not yet configured proxy for the wi-fi connection:
![adguard for android - notifications moqups 2017-07-26 15-41-23](https://user-images.githubusercontent.com/5947035/28621216-eaa94fbc-7218-11e7-83b5-2a0dbd4cc792.png)

**Comment by ameshkov** [comment]
Issues with the current implementation:

1. Statistics is always unavailable when you start protection first time.
2. Let's change the text:

`Blocked: 321 of 13K ● Data saved: 1.84 MB`

We should change the way we format numbers. Use K for thousands, M for millions, etc.

3. Instead of `Statistics are not available yet`, we should let the user know that stats he'll see is for the current session. So use this text instead: `No statistics recorded yet`

**Comment by Revertron** [comment]
Done.

**Comment by ameshkov** [comment]
Got feedback:
> Also, minor feedback, if I may: The text, "Blocked: x of y" I think needs reworking. I eventually figured out what it meant, but I think to the average user, they're going to see that as x ads out of y ads blocked, not x requests out y requests blocked, and wonder why so many ads/trackers aren't being blocked.

I must admit it makes sense, we should re-think it.

**Comment by ameshkov** [comment]
Here is my proposal.

**Notification text:**
https://uploads.adguard.com/up04_m4078.png

**Apps Management**
Change `One day` to `Today` so that it showed stats from 00:00 only.

**Comment by carlylemiii** [comment]
Do the stats refresh daily on the notification, or does it say something else other than Today if going dor multiple days?

**Comment by ameshkov** [comment]
> Do the stats refresh daily on the notification, or does it say something else other than Today if going for multiple days?

It'll always show the current today's stats. In 00:00 it'll be restarted.

**Comment by nkartyshov** [comment]
done
