### ISSUE TITLE
VPN Master compatibility

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1244]
The case is:
* no root
* manual proxy setting (as in the instruction)
* was checked with Wi-Fi
* everything works fine with VPN Master disabled
* as soon as VPN Master is enabled - ads cannot be filtered.

https://play.google.com/store/apps/developer?id=VPN+Master

Ticket ID: 1104069

**Comment by ameshkov** [comment]
> manual proxy setting (as in the instruction)

@vozersky we should do something with that instruction -- manual proxy won't work, only the automatic one.

**Comment by zebrum** [comment]
@ameshkov 
This is what we have right now in android faq: 

_Manual mode

This approach may not work in some situations. It depends on your firmware and the actual VPN app. For some cases traffic bypasses manually configured proxy._

Maybe we should just make a list of VPN apps which are working with Adguard manual proxy settings?

**Comment by ameshkov** [comment]
@zebrum if only I knew:)
