### ISSUE TITLE
Reconfiguring iptables on package add/replace leads to no internet

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1245]
Log with the issue attached:
[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1034526/adguard.log.txt)

Here is what's going on:

1. 21:29 -- 21:30 - new app is installed or updated, AG reconfigures iptables redirect
2. 21:30 -- 21:42 - no connections are accepted by the proxy server (it's unclear to me what exactly was broken, though)
3. 21:43 -- AG was restarted manually, everything works as it should

@vozersky I need you to try reproducing the issue. @Alexey71 is the one who's experiencing the issue, ask him questions if you have any.

**Comment by ameshkov** [comment]
What's important is that the app being added must be on the list of exceptions (filtering disabled by default).

For instance, a VPN app like Opera Max should work.

**Comment by ameshkov** [comment]
At least we should not reconfigure it for the apps updates.

The problem is that it fires `PACKAGE_ADDED` even for the update:
```
08:10:59.625 [main] INFO  c.a.a.receivers.PackageReceiver - Package receiver received android.intent.action.PACKAGE_REMOVED for org.blackmart.market
08:10:59.750 [main] INFO  c.a.a.receivers.PackageReceiver - Package receiver received android.intent.action.PACKAGE_ADDED for org.blackmart.market
08:10:59.860 [main] INFO  c.a.a.receivers.PackageReceiver - Package receiver received android.intent.action.PACKAGE_REPLACED for org.blackmart.market
```

**Comment by nkartyshov** [comment]
Fixed the problem of reconfiguration a proxy when updating an application. But I can reproduce problem with broken down connection. @vozersky Please, try to reproducing.

**Comment by nkartyshov** [comment]
Fixed
