### ISSUE TITLE
Add "Battery" information to AG

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1246]
With the battery stats reworked in Android O there's no more visible information about CPU time / data usage in the app's battery usage details.

So, it is now completely unclear for a user why does Android counts that amount of battery usage towards this or that app. It's more or less okay for most of the apps, but not for us. It is crucial for us to provide an alternative, to show what real battery usage is.

Mockups:
https://app.moqups.com/ameshkov/lfmli7Cikw/view/page/a27757852

Here is how it should look like:

![](https://uploads.adguard.com/up04_geltx.png)

Scrolled down:
![](https://uploads.adguard.com/up04_hrc6t.png)

**Comment by ameshkov** [comment]
It causes [more](https://www.reddit.com/r/Adguard/comments/6wdd4x/80oreo_adguard_is_running_in_the_background/) and [more](https://www.reddit.com/r/GooglePixel/comments/6wti98/does_anyone_have_battery_usage_like_this_from/) questions from Oreo users, so let's do it in v2.10.

**Comment by ameshkov** [comment]
Useful info:

1. Getting current power profile: https://stackoverflow.com/questions/22285179/query-for-battery-capacity
2. To estimate the CPU time we should use `/proc/[pid]/stat` (should be accessible for our own process) (why didn't we do it in WebBatteryTester btw?)
3. To get the network usage we can use https://github.com/AdguardTeam/WebBatteryTester/blob/master/app/src/main/java/com/adguard/webbatterytester/Utils.java#L180

Point 3 is tricky, though, as when the network is changed, the stats will also change. We may need to find a better way to extract the data usage numbers.

**Comment by ameshkov** [comment]
Actually, we cannot use `/proc/net/dev` (point 3) as it is aggregated stats. We should instead calc traffic stats by ourselves.

Also, we should collect stats "since last charge", so we should monitor `ACTION_POWER_CONNECTED`.

One more issue -- we should save intermediate state between AG runs.

**Comment by carlylemiii** [comment]
@ameshkov here are my suggestions:

When AdGuard is on, [Android's] battery and data usage statistics don’t [represent the actual] ~~present the real~~ situation. Due to the filtering, Android counts the other apps' consumption as AdGuard’s, which leads to [an] overestimation of AdGuard’s share and conversely [to] an underestimation of other apps' consumption rates.

AdGuard's own battery usage is determined by the [Adguard] app's CPU usage and [is] calculated with a simple formula. To estimate the real battery usage[,] we use the coefficients from the device's power profile and data on the CPU usage from the "proc/stat" file.

**Comment by ameshkov** [comment]
Thank you!

**Comment by ameshkov** [comment]
@Revertron additional changes:

Add description to the breakdown points:
https://uploads.adguard.com/up04_kd1lj.png

Change the technical explanation text a bit:
```
AdGuard's own battery usage is determined by the AdGuard app's own usage of CPU, mobile and Wi-Fi data, and is calculated with a simple formula. To estimate the real battery usage, we use the coefficients from the device's power profile and data on the CPU usage from the "proc/stat" files.
```

**Comment by ameshkov** [comment]
And two more paragraphs to the technical explanation:

> The formula we use is the same as the one used by Android in the battery stats. The difference is that, unlike Android, we know what part of the data usage belongs to AdGuard, and what part is the other apps' traffic.

**Comment by Revertron** [comment]
Done.
