### ISSUE TITLE
Prepare an issue template for this repo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1247]
Like what we have in AdguardFilters:
https://github.com/AdguardTeam/AdguardFilters/issues/5135

For inspiration look at the issue templates here:

* https://bugs.chromium.org/p/chromium/issues/list
* https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/new/

**Comment by vozersky** [comment]
added
