### ISSUE TITLE
Turbo mode in Yandex Browser is broken by HTTPS filtering

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1248]
Reproduced with Ukrainian provider.
Exclude:
```
tech1-cdn.com
tech2-cdn.com
fireball.mipn-solutions.net
```

**Comment by nkartyshov** [comment]
Resovled by [AdguardTeam/HttpsExclusions@ f1f162](https://github.com/AdguardTeam/HttpsExclusions/commit/f1f1621f9279657d6e07ec0cb3c78705f6f642d3)
