### ISSUE TITLE
Watchdog period help text bad grammar

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1250]
Not sure about other translations, but the help text

"Starts a safe-guard service service in another process, that is checking, if main service is alive and restarts it, if necessary. Zero disables it."

is not a proper English sentence.

Here is a suggestion:

"Starts a safe-guard service service in another process, which checks if the main service is alive and restarts it, if necessary. Zero disables it."

**Comment by ameshkov** [comment]
Current version is a bit different:
https://adguard.oneskyapp.com/collaboration/translate/project/project/13597/language/1#/?keyword=31673817

```
Starts a safeguard service in another process, which checks, if main service is alive and restarts it, if necessary. Zero disables it.
```

Your version is better, though, thank you!
