### ISSUE TITLE
usps.com and lendingclub.com random failure to load

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1251]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
usps.com and lendingclub.com random failure to load
https://www.usps.com/
https://www.lendingclub.com/site/home
the issue doesn't persist when adg is disabled
[adguard (2).log.zip](https://github.com/AdguardTeam/AdguardFilters/files/1034198/adguard.2.log.zip)
 
is not reproduced on Meizu m3s.
Screenshot:

![image](https://cloud.githubusercontent.com/assets/25711093/26529217/ce2d3498-43c4-11e7-9e80-b0e0bc2a6dcb.png)
![image](https://cloud.githubusercontent.com/assets/14153331/26563782/519d8c76-44e0-11e7-9519-e19de3bc34de.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | chrome
Adguard version: | 2.9.70

Ticket ID(if exists): 1387734

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

------

Original issue with the logs and user's comments:
https://github.com/AdguardTeam/AdguardFilters/issues/5143

**Comment by zebrum** [comment]
I'm able to reproduce it with 2.9.70
but sites are loading fine with 2.9.111 android 7.1.1 on nexus 9

**Comment by zebrum** [comment]
it's ok now on 2.10.56
