### ISSUE TITLE
Bug - Grab cannot connect server

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#1252]
Hi,

With Adguard's filtering, Grab (grab.com - a ridesharing service) fails to load. It says it cannot connect to server. Whitelisting Grab from Adguard solves the issue. Please kindly fix. Thank you.

**Comment by vozersky** [comment]
@snhv hi! Does disabling HTTPS filtering help? Or it works only if you don't route traffic through Adguard at all?

**Comment by snhv** [comment]
Yes disabling HTTPS filtering also helps. But I think it's not a graceful solution.

**Comment by vozersky** [comment]
@snhv sure thing, we'll find an exact domain we have to exclude, thanks for reporting the issue

**Comment by nkartyshov** [comment]
We already had a problem with this app and We already has exclude domain grabtaxi.com.

@snhv Can you see this a domain in your https whitelist?

**Comment by snhv** [comment]
Hi @nkartyshov , not in https whitelist for me, and I've never meddled with it.

**Comment by ameshkov** [comment]
@snhv it's just in Adguard's beta version, not in the current stable.

Temporary solution would be to disable HTTPS filtering specifically for this app (apps management -> find grab -> uncheck https filtering for it)

**Comment by snhv** [comment]
Thanks @ameshkov @nkartyshov , I've just seen the other thread on this issue.
