### ISSUE TITLE
Yahoo mail is not working with Agd 2.9.111

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1256]
Yahoo mail is not working with Agd 2.9.111
disabling HTTPS filtration for the app didn't help.
with HTTPS enabled
![image](https://cloud.githubusercontent.com/assets/25711093/26750987/e6cbff44-4837-11e7-92c6-a937b19c6917.png)
with HTTPS disabled
![image](https://cloud.githubusercontent.com/assets/25711093/26750989/ea309618-4837-11e7-8bf7-c706029a0851.png)
CustomerID: 1448020
Androind 5.1 (meizu m3s)/ android 7.1.2 (Google Pixel XL)
filters: rus, eng, mobile, experimental, annoyance, social, spyware, experimental

**Comment by ameshkov** [comment]
@vozersky can you reproduce it?

**Comment by vozersky** [comment]
reproduced
looks like some rule in Annoyances filter is the culprit
@Alex-302 please assist

**Comment by Alex-302** [comment]
It works in my device

<details>

![image](http://imagizer.imageshack.com/img922/4261/DIX5m4.png)
</details>

**Comment by vozersky** [comment]
Can't reproduce it anymore.
Looks like it has been fixed. 

@Michael23456 and again, this kind of problems should go to Adguard filters repo

**Comment by kbahlyk** [comment]
Yahoo Mail issues again
new logs in the ticket
Ticket ID - 1448020

"Basically, with Adguard enabled, Yahoo mail's app cannot function. You should see in the logs that I had it enabled, tried checking mail and nothing happened. I tried to sign out and sign in even and it wouldn't let me. Then I disabled Adguard and it worked fine. This only began happening in one of the most recent updates, so something broke Yahoo Mail."

**Comment by whatinthenameofgod** [comment]
So it doesn't happen constantly. It seems to only happen after the device sleeps or isn't active but it's definitely AdGuard.

**Comment by vozersky** [comment]
@kbahlyk @whatinthenameofgod does this happen without annoyances filter?

**Comment by whatinthenameofgod** [comment]
Yeah, played around without annoyances filter and it appears so.

**Comment by whatinthenameofgod** [comment]
Still ongoing. Would be nice to have this revisited. It's annoying to have to disable adguard to check for mail.

**Comment by ameshkov** [comment]
@vozersky please take care of it

**Comment by zebrum** [comment]
can not reproduce on 2.9.70 or 2.9.135
but there is a problem on 2.9.111

adding rule `@@||geo.yahoo.com$app=com.yahoo.mobile.client.android.mail` fixed the problem.

**Comment by ameshkov** [comment]
That's odd, are you sure no issues in 2.9.135?

**Comment by zebrum** [comment]
that's strange - after reinstalling Adguard 2.9.135 the issue is reproducible again

**Comment by ameshkov** [comment]
@Alex-302 let's add the rule mentioned above to the mobile filter.

**Comment by zebrum** [comment]
@Alex-302 @ameshkov wait. That's not the culprit now. I'm trying to find out what is. 
Btw I was not able to update from .111 to .135

**Comment by zebrum** [comment]
@whatinthenameofgod try to add this rule to user filter and check yahoo mail app:

`@@||bats.video.yahoo.com$app=com.yahoo.mobile.client.android.mail`

**Comment by whatinthenameofgod** [comment]
Just added. I'll update you.

**Comment by whatinthenameofgod** [comment]
This seems to be working now. Haven't run into the same error since.

**Comment by zebrum** [comment]
@Alex-302 please add the rule to the mobile filter 

`@@||bats.video.yahoo.com$app=com.yahoo.mobile.client.android.mail`

**Comment by Alex-302** [comment]
Done
