### ISSUE TITLE
Firefox nightly 64bit is not recognized as a browser

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1257]
Adguard is not filtering traffic for Firefox nightly 64bit
here is the link to download the browser https://archive.mozilla.org/pub/mobile/nightly/latest-date-android-aarch64/fennec-55.0a1.multi.android-aarch64.apk

is Not reproduced on meizu m3s( android 5.1)

collected full logs:
[debug (9).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1049565/debug.9.txt)
[state (42).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1049566/state.42.txt)
CustomerID: 1566043

**Comment by TPS** [comment]
_Any_ traffic or just HTTPS? Ff does need separate cert installed.…

**Comment by Michael23456** [comment]
the customer says that any traffic. We tried to install the certificate for the Firefox, but it didn't help.

**Comment by ameshkov** [comment]
`org.mozilla.fennec_aurora` package should be added to the browsers list.

**Comment by ameshkov** [comment]
Done

**Comment by naroznyv** [comment]
Thank !
