### ISSUE TITLE
Verizon wifi calls, texts, mms fail completely in HTTP proxy mode (auto)

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1258]
It's a request from https://github.com/AdguardTeam/AdguardFilters/issues/5001

***Description***: missed ads in CellMapper, WiFi Password, CornerFly (android 7)

ad in CornerFly still displayed after clearing the cache. CellMapper and WiFi Password had boxes for the ads with the error like symbol but the ads didn't display this particular time.

CornerFly https://play.google.com/store/apps/details?id=com.flyperinc.cornerfly&hl=en
WiFi Password https://play.google.com/store/apps/details?id=com.farproc.wifipassword&hl=en

This is resolved by blocking IPv6, but creates other issues for this particular situation.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/25711093/26022754/c86c3a9c-37b5-11e7-8a9e-94d292269613.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 7
Adguard version: | 2.9.70
Adguard mode (Android): | HTTP proxy mode (auto)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 11, 211 

Ticket ID(if exists): 1403048

**Comment by TPS** [comment]
Related to #958 @ all?

**Comment by carlylemiii** [comment]
Doesn't seem related in the slightest bit. That said, this is two separate issues.

1) HTTP proxy misses IPv6 ads - duplicate/already being worked on
2) blocking IPv6 entirely blocks Verizon WiFi Calling - expected, because WiFi Calling uses IPv6

This issue/question should be closed.

**Comment by TPS** [comment]
More #142, #295, or #580, then?

**Comment by carlylemiii** [comment]
My original issue, the ads being missed in those apps, is because of #580.

**Comment by ameshkov** [comment]
> This is resolved by blocking IPv6, but creates other issues for this particular situation.

If I get it right, the culprit is blocking IPv6?

The only solution will be for us to add full-scale IPv6 support in the proxy mode. This is planned already -- https://github.com/AdguardTeam/AdguardForAndroid/issues/580

Temporary solution -- try changing APN type to IPv4 only. Although, it might not work for Verizon.

**Comment by ameshkov** [comment]
Closed as dup of #580
