### ISSUE TITLE
Adg blocks internet access with Mobile network

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1260]
Adg blocks internet access with Mobile network (Android 4.4.2)
with Wifi internet is working

got a log here:
[state (55).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1050358/state.55.txt)
[debug (15).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1050359/debug.15.txt)

CustomerID: 518650

**Comment by vozersky** [comment]
@nkartyshov could you please check the log file?

**Comment by altokarev** [comment]
@Revertron examined the logs - seems there no connections after enabling a VPN, as if the system doesn't redirect them to our TUN.
