### ISSUE TITLE
Low upload speed with Adg enabled

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1261]
Low upload speed with Adg enabled
The customer was using SpeedTestNet app
Connected to WiFi network

without Adguard:
<details>

![image](https://cloud.githubusercontent.com/assets/25711093/26763034/ac0268f8-4954-11e7-95c8-b3422ab2d184.png)

</details>

with Adguard:

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26763038/bf221ef6-4954-11e7-85cb-933f0e0797e8.png)
![image](https://cloud.githubusercontent.com/assets/25711093/26763041/c7a78552-4954-11e7-8278-348b04c914df.png)
![image](https://cloud.githubusercontent.com/assets/25711093/26763043/ce5aec72-4954-11e7-8e5b-e62e38676ccd.png)
![image](https://cloud.githubusercontent.com/assets/25711093/26763045/d56c0e6a-4954-11e7-980b-e0895d8b6fb6.png)

</details>

CustomerID: 1569287

**Comment by Michael23456** [comment]
what do we need to ask?

**Comment by Alex-302** [comment]
Just for comparison:

<details>

![image](https://cloud.githubusercontent.com/assets/8361299/26763131/321d69d2-4956-11e7-9a78-4712b9132598.png)

</details>

**Comment by Michael23456** [comment]
this is from my phone:

<details>

![image](https://cloud.githubusercontent.com/assets/25711093/26763256/7372fb3e-4958-11e7-9bfe-dca848d5519b.png)

</details>

**Comment by ameshkov** [comment]
Don't ask anything, we should re-test it once new network stack library is integrated in Android.

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/1325
