### ISSUE TITLE
High ping with Adg

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1262]
High ping with Adg on 4G and Wifi

with ang enabled:
![image](https://cloud.githubusercontent.com/assets/25711093/26764903/3a60e6c8-4979-11e7-9ad3-e7a726621b67.png)

If disabled:
![image](https://cloud.githubusercontent.com/assets/25711093/26764906/45dc28dc-4979-11e7-9a55-f03aaaa1d184.png)

the issue persists only in versions 2.9.70 and later
[state (85).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1050679/state.85.txt)
[debug (20).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1050680/debug.20.txt)
CustomerID:1393535

**Comment by Alex-302** [comment]
Try 2.9.111 beta. It was fixed in https://github.com/AdguardTeam/AdguardForAndroid/issues/1192

**Comment by Michael23456** [comment]
forwarded to the custoemer

**Comment by ameshkov** [comment]
Closed as duplicate
