### ISSUE TITLE
Add more malware domains from adblockpus website

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1263]
We've got a request to add more malware domains from adblockpus website.
Ticket ID: 1553302

**Comment by vozersky** [comment]
@KozelElena What exactly do you mean? Malware Domains subscription?

**Comment by TPS** [comment]
Maybe that or perhaps #13?

**Comment by KozelElena** [comment]
Sorry for a delayed reply. Firstly, he wanted us to check not only for our updates but for downloaded by the URL as well. And, as I understand, it's https://github.com/AdguardTeam/AdguardForAndroid/issues/13

For now we don't have any replies for him.

**Comment by vozersky** [comment]
yeah, let's just stick to #13
