### ISSUE TITLE
startpage.com - HTTPS is not filtered in Ghostery browser

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1265]
Original issue:
https://forum.adguard.com/index.php?threads/startpage-com-huge-ad-areas-missed-android.22296/#post-139915

@vozersky please check it on our side.

**Comment by vozersky** [comment]
I don't see any issues with HTTPS filtering in Ghostery & there are no ads on startpage.com for me either

**Comment by ameshkov** [comment]
Ask DrDidi in Telegram to collect logs then

**Comment by vozersky** [comment]
after the browser reinstall everything's went back to normal
