### ISSUE TITLE
Paranoid Mode - Disable networking while VPN is off

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1266]
Can ag have a option to disable networking on shutdown or update installation reenable it after the vpn got connected? So no trackers and stats will send in that time :)

**Comment by ameshkov** [comment]
Yeah, here it is:
#1240 
#760

**Comment by Bluscream** [comment]
@ho

**Comment by TPS** [comment]
#520 has much relevant discussion re: older devices.
