### ISSUE TITLE
Ultimate Ninja Blazing - connection error

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1269]
Exclude
```
nrbnares-channel-or-jp.global.ssl.fastly.net
```

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/5285

**Comment by ameshkov** [comment]
Resolved by https://github.com/AdguardTeam/HttpsExclusions/commit/4f2fd325cd2f0808fded563d5210a725ad7f58b2
