### ISSUE TITLE
No internet connection in OK app with HTTPS enabled

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1270]
No internet connection in OK app with HTTPS enabled
<details>

![image](https://user-images.githubusercontent.com/25711093/27012011-a28c0cc6-4ed0-11e7-95de-677ba56c9254.png)
</details>
CustomerID: 1285938

logs:
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1066520/state.txt)
[debug (28).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1066521/debug.28.txt)

**Comment by zebrum** [comment]
reproduced.
@nkartyshov please assist.

**Comment by ameshkov** [comment]
@zebrum we need logs with "record everything" level

**Comment by zebrum** [comment]
I will ask user to record logs.

**Comment by zebrum** [comment]
here they are: 
[adguard.log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1075146/adguard.log.zip)

**Comment by ameshkov** [comment]
Resolved via https://github.com/AdguardTeam/HttpsExclusions/commit/714a5ae2fb90aff41cf4a2e36704a3d8ae30fd12
