### ISSUE TITLE
Adguard disables by itself

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1271]
Adguard disables by itself
got logs:

[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1066541/state.txt)
[debug (30).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1066542/debug.30.txt)

issue time = 10.26

CustomerID: 1248045

**Comment by vozersky** [comment]
@Michael23456 Adguard doesn't turn itself off, so the issue name is kind of misleading.

**Comment by vozersky** [comment]
@Michael23456 The only thing I can see in the log is that Android system kills Adguard here, make sure **it is** properly whitelisted in battery optimization etc. 

We would need to have **LogCat** to understand more.

**Comment by TPS** [comment]
#1264?

**Comment by vozersky** [comment]
@TPS wow, misclick, soz

**Comment by TPS** [comment]
@vozersky 'S'ok, but this duplicates #1264, or unrelated?

**Comment by vozersky** [comment]
@TPS not sure yet

**Comment by Michael23456** [comment]
we are still waiting for an answer from the customer to get a LogCat

**Comment by vozersky** [comment]
obsolete
