### ISSUE TITLE
HTTPS filtering is breaking Nimses app functionality

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1273]
HTTPS filtering is breaking Nimses app functionality
https://play.google.com/store/apps/details?id=com.nimses&hl=en
<details>

![image](https://user-images.githubusercontent.com/25711093/27013322-6397d6d4-4eea-11e7-8dc5-1c14d12cde0f.png)
</details>
CustomerID:1277354

**Comment by zebrum** [comment]
confirmed
need to exclude com.nimses from https filtering @nkartyshov

**Comment by vozersky** [comment]
@Michael23456  they use certificate pinning, won't fix, tell the user to disable https filtering for the app, we will exclude it in the next build

**Comment by Michael23456** [comment]
forwarded to the customer

**Comment by ameshkov** [comment]
Disabled by default for this app since new build
