### ISSUE TITLE
Sniper Fury game cannot start when AG is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1275]
Link:
https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftFWHM

**Comment by ameshkov** [comment]
@vozersky assist please on testing & figuring what's the problem.

1. Install, reproduce
2. Try disabling ad blocking for the app. 
3. If it helps -- unblock requests from the filtering log one by one

**Comment by vozersky** [comment]
@zebrum

**Comment by zebrum** [comment]
there are 2 blocked requests, unblocking them doesn't help so far. I've tried this rules: 

@@||z.moatads.com
@@||578756.gameloft.com/un/index.ppp?ad=ingamenative

**Comment by ameshkov** [comment]
Done

**Comment by Alex-302** [comment]
@zebrum It seems this app can be removed from HTTPS exclusions
https://github.com/AdguardTeam/AdguardFilters/issues/14471#issuecomment-398004998
Could you please check it?
