### ISSUE TITLE
Google Play images are broken in Proxy+Auto mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#128]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=43878044

1. Check if you can reproduce this.
2. If not - contact user and find out which settings/filters he uses.

**Comment by gshumihin** [comment]
Cant reproduce it with 2.1.240.
Contacted to user.

**Comment by gshumihin** [comment]
No responce from user.
Still can't reproduce on my side.
