### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#1280]
Two suggestions:

1) ability to create custom groups and change settings for all apps in the group (not like the current way of all apps; modified vs unmodified) 
2) a "Manage Apps" option in the floating menu that comes up after tapping "Touch to manage the
network" notification message

Ticket id: 1573860

**Comment by vozersky** [comment]
@veronikasav Please make separate issues for different and not connected to each other requests. Also, we really need better descriptions. 

1. Might be partially covered if we will introduce User profiles in future. Anyway, please describe the situatuion when it might be useful. 

2. I didn't really get the idea, do you mean our notification? (Adguard filtering all the connections)
