### ISSUE TITLE
Add EasyList Lithuanian filter

### ISSUE THREAD

**Issue by Angel497** [AdguardTeam/AdguardForAndroid#1281]
Hello could you create a Lithuanian filter for android thank you.

> please add https://github.com/EasyList-Lithuania/ 
> edited by vozersky

**Comment by vozersky** [comment]
Hi! I don't think we are not going to develop our own Lithuanian filter at this moment, but we should be able to add EasyList Lithuanian filter to Adguard for Android

**Comment by vozersky** [comment]
@Alex-302 what do you think?

**Comment by Alex-302** [comment]
@vozersky use search

<details>

![image](http://imagizer.imageshack.com/img922/6092/EFilHO.png)
</details>

**Comment by Angel497** [comment]
I really appreciate that if you could thank you for your hard work.

2017 birž. 14 16:26 "Vladimir Ozersky" <notifications@github.com> rašė:

**Comment by vozersky** [comment]
@Alex-302 we do discuss Android application here

**Comment by Angel497** [comment]
Yeah it will be OK thank you.

2017 birž. 14 16:29 "Edy Pyp" <mafiozas18@gmail.com> rašė:

**Comment by vozersky** [comment]
@nkartyshov please add https://github.com/EasyList-Lithuania/

**Comment by Angel497** [comment]
Again thank you for your help.

2017 birž. 14 16:36 "Vladimir Ozersky" <notifications@github.com> rašė:

**Comment by nkartyshov** [comment]
Added, review AFA-CR-34
