### ISSUE TITLE
DNS via SOCKS4a/SOCKS5 proxy

### ISSUE THREAD

**Issue by tsurf2017** [AdguardTeam/AdguardForAndroid#1282]
Hello. I found that AdGuard can't route DNS queries through SOCKS4a/SOCKS5, so it causes dns leak.
I know about `pref.vpn.dns` but it isn't that I need.
Can you add this feature, please?

**Comment by vozersky** [comment]
@tsurf2017 hi! you can use [DNSCrypt](https://dnscrypt.org/)

**Comment by vozersky** [comment]
@tsurf2017 hi! true, that makes sense, thank you

**Comment by ameshkov** [comment]
Yeah, AG is able to forward TCP traffic to SOCKS4/5 proxy, but not UDP indeed, and it's quite hard to implement technically.

Although, we're planning to add DNSCrypt support in the next major update, which should solve the issue partially.

**Comment by pou-chi** [comment]
> AG is able to forward TCP traffic to SOCKS4/5 proxy
Can't find how to do that in latest beta.

**Comment by ameshkov** [comment]
@pou-chi 

> Can't find how to do that in latest beta.

Sorry for the late reply. Go to Settings -> Proxy settings

**Comment by ameshkov** [comment]
Duplicate of #1357
