### ISSUE TITLE
User filter import: puts rules in random order

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1283]
Report:
https://forum.adguard.com/index.php?threads/bug-user-filter-import-puts-rules-in-random-order.22561/

<details><summary>Screenshot:</summary>

![issu](https://user-images.githubusercontent.com/28726429/27144990-95be7768-513c-11e7-9b97-d925c36d0f26.png)

</details>

**Comment by ameshkov** [comment]
Dup of #1279
