### ISSUE TITLE
teletoonplus.pl blocked videos and detecting AG

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardForAndroid#1284]
This topic is the same for all AG products (extensions or Android). Look : 
![screenshot_2017-06-14-19-54-55](https://user-images.githubusercontent.com/16944478/27147090-d6fc16c8-513b-11e7-9d47-607b34aae152.png)

**Comment by vozersky** [comment]
Hi! 
Filtering problems should be reported to Filters repo, I've created an issue: https://github.com/AdguardTeam/AdguardFilters/issues/5337 
could you please specify what filters are you using?

**Comment by seba2282** [comment]
All filters without reek and without acceptable ads.

**Comment by vozersky** [comment]
please discuss at AdguardTeam/AdguardFilters#5337
well, try disabling third-party filters (not Adguard's)
