### ISSUE TITLE
Some banking apps to exclude

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1287]
- `de.number26.android` - [https://play.google.com/store/apps/details?id=de.number26.android&hl=en](url)

- `com.chase.sig.android` - https://play.google.com/store/apps/details?id=com.chase.sig.android&hl=en

- `com.wf.wellsfargomobile` - https://play.google.com/store/apps/details?id=com.wf.wellsfargomobile&hl=en

- `com.bnpp.easybanking` - https://play.google.com/store/apps/details?id=com.bnpp.easybanking&hl=en

- `com.discoverfinancial.mobile` - https://play.google.com/store/apps/details?id=com.discoverfinancial.mobile&hl=en

- `mobi.societegenerale.mobile.lappli` - https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli&hl=en

- `de.commerzbanking.mobil` - https://play.google.com/store/apps/details?id=de.commerzbanking.mobil&hl=en

- `com.db.mm.deutschebank` - https://play.google.com/store/apps/details?id=com.db.mm.deutschebank&hl=en

- `com.usbank.mobilebanking` - https://play.google.com/store/apps/details?id=com.usbank.mobilebanking&hl=en

- `com.infonow.bofa` - https://play.google.com/store/apps/details?id=com.infonow.bofa&hl=en

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/issues/27

**Comment by ameshkov** [comment]
Done
