### ISSUE TITLE
Integrate with the new network stack

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1289]
Time to try it:
https://github.com/AdguardTeam/CoreLibs/issues/9

**Comment by ameshkov** [comment]
@sfionov any idea on how can we measure average CPU usage of an Android process?

It'd be great if you provide a simple shell script doing that, so that @AdguardTeam/qa-team could use it to compare the old and new implementations.

**Comment by sfionov** [comment]
@ameshkov @AdguardTeam/qa-team https://gist.github.com/sfionov/0021f9cfd244bf5168c9c8683e6dfc37

**Comment by nkartyshov** [comment]
Added new stack in VPN. Review AFA-CR-32.

**Comment by ameshkov** [comment]
Here's what left to do:

1. Review the bandwidth stats reporting functionality, it does not seem to work properly at the moment. I also need you to help @vozersky to test it manually (add a new test case for it).
2. Add a "global" restart function. Instead of showing "you need to restart protection" toast, we'd better do it silently in background and show "Protection was restarted to apply new settings" toast instead. Please mind, that we should throttle calls to this "apply new settings" method.
3. Remove the deprecated classes.

**Comment by ameshkov** [comment]
Current build crashes when I try to edit a rule in the user filter

**Comment by ameshkov** [comment]
Must not forget about testing recording the pcap file.

**Comment by ameshkov** [comment]
@nkartyshov 
> I also need you to help @vozersky to test it manually (add a new test case for it).

Please come up with testing instruction.

We should also compare CPU usage with the current stable version:
https://gist.github.com/sfionov/0021f9cfd244bf5168c9c8683e6dfc37

**Comment by ameshkov** [comment]
Here is a build with the new network stack:
[adguard_new_network_stack.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1156378/adguard_new_network_stack.apk.zip)

**Comment by nkartyshov** [comment]
Native TCP/IP stack

```
user: 19.66s, sys: 3.31s
user: 19.72s, sys: 3.31s
user: 19.76s, sys: 3.32s
user: 19.80s, sys: 3.32s
user: 19.84s, sys: 3.32s
user: 19.90s, sys: 3.34s
user: 19.95s, sys: 3.34s
user: 20.15s, sys: 3.51s
user: 20.43s, sys: 3.73s
user: 20.69s, sys: 3.97s
user: 20.97s, sys: 4.21s
user: 21.21s, sys: 4.42s
user: 21.46s, sys: 4.61s
user: 21.71s, sys: 4.83s
user: 21.92s, sys: 5.07s
user: 22.14s, sys: 5.29s
user: 22.36s, sys: 5.47s
user: 22.53s, sys: 5.60s
user: 22.80s, sys: 5.81s
user: 23.03s, sys: 6.07s
user: 23.22s, sys: 6.30s
user: 23.37s, sys: 6.59s
user: 23.49s, sys: 6.91s
user: 23.69s, sys: 7.14s
user: 23.88s, sys: 7.35s
user: 24.03s, sys: 7.60s
user: 24.24s, sys: 7.83s
user: 24.44s, sys: 8.04s
user: 24.61s, sys: 8.28s
user: 24.64s, sys: 8.28s
user: 24.75s, sys: 8.32s
```

java tcp/ip stack

```
user: 11.77s, sys: 2.44s
user: 12.10s, sys: 2.64s
user: 12.22s, sys: 2.67s
user: 12.29s, sys: 2.68s
user: 12.41s, sys: 2.70s
user: 12.48s, sys: 2.70s
user: 12.67s, sys: 2.78s
user: 13.68s, sys: 3.26s
user: 14.45s, sys: 3.61s
user: 15.18s, sys: 4.02s
user: 16.00s, sys: 4.41s
user: 16.68s, sys: 4.79s
user: 17.40s, sys: 5.23s
user: 18.12s, sys: 5.57s
user: 18.83s, sys: 5.93s
user: 19.50s, sys: 6.32s
user: 20.17s, sys: 6.70s
user: 20.48s, sys: 6.89s
user: 21.40s, sys: 7.59s
user: 22.52s, sys: 8.40s
user: 23.56s, sys: 9.18s
user: 24.52s, sys: 9.89s
user: 25.43s, sys: 10.57s
user: 26.46s, sys: 11.13s
user: 27.44s, sys: 11.71s
user: 28.39s, sys: 12.28s
user: 29.40s, sys: 12.78s
user: 30.38s, sys: 13.32s
user: 30.86s, sys: 13.55s
user: 30.98s, sys: 13.61s
user: 31.11s, sys: 13.65s
user: 31.23s, sys: 13.68s
user: 31.35s, sys: 13.73s
user: 31.54s, sys: 13.78s
```

**Comment by ameshkov** [comment]
### Overall

New network stack:
```
user: 5.09
sys: 5,01
sum: 10.1
```

Old network stack:
```
user: 19.77
sys: 11.34
sum: 31.11
```

**New network stack performance is more than x3 times better.**
