### ISSUE TITLE
Adguard + OpenVPN breaks connection while switching the networks

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1292]
### Description

User uses OpenVPN + Adguard in HTTP proxy mode. User mentioned that Adguard works in local proxy mode and don't monitor network connections.

To restore the Internet user must to perform the following manipulations: close OpenVPN and Adguard apps > start OpenVPN app > start Adguard.

User is wondering whether it's possible to make Adguard to track over the network state (or the current VPN connection) and switch the local proxy with a delay?

Using `pref.vpn.disable.pause` and adding OpenVPN to exceptions didn't help.
___

### Expected behaviour

Establish connection to the internet using OpenVPN + Adguard in HTTP proxy mode even while switching the networks.

### Actual behaviour

While switching the networks (e.g., Wi-Fi > 3G) OpenVPN reconnects, but Adguard don't. As result - no Internet.
___

### Adguard log files

[1093966_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1109266/1093966_logs.zip)

### Enviroment
Adguard version: 2.9.111
Android version: 6.0.1
Device: Xiaomi Redmi Note 4

Customer ID: 1093966

**Comment by vozersky** [comment]
STR?

**Comment by ameshkov** [comment]
> User is wondering whether it's possible to make Adguard to track over the network state (or the current VPN connection) and switch the local proxy with a delay?

Temporary solution would be to use Tasker.

> To restore the Internet user must to perform the following manipulations: close OpenVPN and Adguard apps > start OpenVPN app > start Adguard.

I wonder why does it matter which app was started first. Need more information on OpenVPN configuration.

@vozersky need repro

**Comment by vozersky** [comment]
@altokarev where’s state.txt? got ticket id?

**Comment by altokarev** [comment]
Updated.

**Comment by altokarev** [comment]
User provided us with a config file: [zelgray.tk.test_adguard.ovpn.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1111726/zelgray.tk.test_adguard.ovpn.zip)

**Comment by zebrum** [comment]
@altokarev please ask user to set manual proxy in Adguard settings and set up proxy 127.0.0.1:8080 in Open VPN settings. 
I can not reproduce the issue neither on android 7 with root nor android 6 with manual proxy in Adguard (no root).

**Comment by altokarev** [comment]
Didn't help. Tried it before. User mentioned it just couldn't establish the connection to the websites that listed in routeing in OpenVPN.

**Comment by zebrum** [comment]
@altokarev please ask user is it any better on the latest AG version?

I'm using openVPN on my phone and so far no problem.

**Comment by altokarev** [comment]
A user just reported that the issue has been resolved a few versions ago.
