### ISSUE TITLE
Adguard breaks internet connection over wifi

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1294]
Adguard breaks internet connection for over wifi

[state (39).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1100501/state.39.txt)
[debug (27).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1100502/debug.27.txt)

version: 2.9.111
VPN-mode

here is the video of the issue: https://drive.google.com/file/d/0B2-2TUti8XRGUEZubklyaXQxcVE/view?usp=drive_web

and a link for the app: https://play.google.com/store/apps/details?id=net.daum.android.map&hl=ko

CustomerID:1488728

**Comment by ameshkov** [comment]
@seanl-adg could you please take a look? Could it be caused by ad blocking?
