### ISSUE TITLE
[Feature Request] Suggestion For Improved Auto Update

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardForAndroid#1295]
Can you please implement Phonegap Build (github.com/phonegap-build) to handle updates.
Another git hub project called DuckieTV uses it with their android app, and it has made the update process completely stream line.
For example, upon opening the app Phonegap Build automatically checks for updates, and if found then asks whether to ignore or update and restart, after this there is no additional action required by the user.
Thanks

**Comment by vozersky** [comment]
@zero77 Hi! Thanks for the request.

Ok, so we have three steps to go through when a new update is available:
- hit the update button under the changelog
- wait for a new build to download
- press install on Android update dialogue window

screenshots:
<details><summary>step 1</summary>

![image](https://user-images.githubusercontent.com/17472907/27651587-84e0b374-5c41-11e7-8cf0-f0e1ec33fe99.png)

</details>

<details><summary>step 2</summary>

![image](https://user-images.githubusercontent.com/17472907/27651596-8bfa63ee-5c41-11e7-9079-9ef982beeccc.png)

</details>

<details><summary>step 3</summary>

![image](https://user-images.githubusercontent.com/17472907/27651599-8f79f2c8-5c41-11e7-94ed-1ee9b91170ea.png)

</details>

I agree we should think about improving the update process, but I really doubt we need a 3rd party library for it. I will check how it works anyway.

**Comment by ameshkov** [comment]
> I will check how it works anyway.

Yep, please take a look, it's interesting what's the difference in their case.

**Comment by zero77** [comment]
I mean something more stream line instead of downloading an apk separately then manually installing it, each time there’s an update.

Preferably, something completely automated that runs in the background and just notifies the user with the change log when complete.

I just suggested Phonegap Build because it is able to achieve this.

Although, yes its better still if its possible to achieve this without using a 3rd party library.

**Comment by ameshkov** [comment]
> Preferably, something completely automated that runs in the background and just notifies the user with the change log when complete.

That's just how it works right now, I am surprised that it's different in your case.

**Comment by ameshkov** [comment]
I mean AG monitors updates, downloads the apk and runs it. The only thing you have to do is tap "Update" and after apk was downloaded tap "Install"

**Comment by zero77** [comment]
Yes, that’s what I mean, get rid of the tapping "Update" and "Install".

**Comment by TPS** [comment]
Given #597, maybe take this opportunity to implement downloading this entirely internally, à la [Yalp Store](https://github.com/yeriomin/YalpStore) or [APKPure](https://m.apkpure.com/apkpure-app.html)?

Bonus to using same approach to sidestep #597 entirely by configurably _always_ using this reimplemented downloader whenever possible.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3192
