### ISSUE TITLE
Yandex apps show security alert notifications on startup

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1296]
### Description

Alert has been seen in [Market](https://play.google.com/store/apps/details?id=ru.yandex.market) and [Weather](https://play.google.com/store/apps/details?id=ru.yandex.weatherplugin) apps

### STR:

1. Download and install [Yandex Market](https://play.google.com/store/apps/details?id=ru.yandex.market)
2. Start the app.

### Expected behaviour

The app starts smoothly

### Actual behaviour

Alert notification is shown:

<details><summary>Screenshot:</summary>

![pasted image at 2017_06_26 20_45-1](https://user-images.githubusercontent.com/17472907/27564374-dabeafca-5adf-11e7-9c8c-5b4e974a41e5.png)

</details>
<br>

### Enviroment
**HTTPS filtering is enabled**
Adguard version: 2.9.111 Beta
Android version: any version lower than 7.0

**Comment by ameshkov** [comment]
Disabled https filtering for these apps by default
