### ISSUE TITLE
Сan't log into public wi-fi networks

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1297]
### Description

User can't log on to several public wi-fi sites (e.g. Tim Hortons public wi-fi), unless he disables Adguard.

Tried to whitelist the sites that the system tries to connect (e.g. http://connectivitycheck.gstatic.com or http://login.datavaletwifi.com), but gets the message that `not a valid website`.

There is no problem on private wi-fi.
___

### Expected behaviour

Successfully log into the gateway and get an access to the Internet.

### Actual behaviour

The device connects to the wi-fi, but the connection to the verification site times out with no response.
___

### Adguard log files

[1470818_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1105539/1470818_logs.zip)

### Enviroment
**HTTPS filtering is disabled**
Adguard version: 2.9.70
Android version: 6.0.1
Device: Blackberry DTEK50

Customer ID: 1470818

**Comment by vozersky** [comment]
@altokarev 
isn't this a filtering rules issue?
have you tried disabling the filters?  like spyware in particular
or all of them, just for testing purposes

**Comment by ameshkov** [comment]
@altokarev does it help to disable Adguard for `com.blackberry.infrastructure` (BlackBerry Hub+ Services) in the Apps management?

**Comment by altokarev** [comment]
User couldn't work it out and ignored our instructions. He returned back later with other questions.
