### ISSUE TITLE
Custom filter subscriptions (add by URL)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#13]
https://github.com/AdguardTeam/AdguardForAndroid/issues/13#issuecomment-378999446

**Comment by TPS** [comment]
#12 could be enhanced by this issue's implementation including a "Submit for review to add to public directory" or some such.… ☺

**Comment by ameshkov** [comment]
There's a difference between https://github.com/AdguardTeam/AdguardForAndroid/issues/12 and this one.

We serve all popular filter subscriptions (like EasyList and such) from our server:
http://adguard.com/en/filter-rules.html?id=101

This version of EasyList is transformed a bit to be 100% compatible with Adguard. We also validate every change to EasyList and fix some errors automatically.

One more bonus from this is that we don't need to download whole filter to check if it has changed.

**Comment by TPS** [comment]
I understand they're different.  I'm saying that URLs submitted via this mechanism could benefit #12 if there's a checkbox (default off, probably, & with comment field → maybe a beta APK feature?) to submit URL to AdGuard devs to review for inclusion in later releases.

**Comment by ameshkov** [comment]
Now I got it, thank you! Looks too complicated to me.

Maybe simpler solution? We can add a comment like this:
"If you want this subscription to be included to default list report it to us here (link to github or our website)."

**Comment by TPS** [comment]
That's, of course, simpler, but much less likely to produce results.  Given volume of URLs custom-added & then submitted should be very low, submissions should be high-enough quality that the complication be worth the effort.…

**Comment by ameshkov** [comment]
Depends on what result do we want. Normally we proxify & transform only known subscriptions which are currently supported.

**Comment by uBlock-user** [comment]
Just for clarification, will this include HOSTS file too ?

**Comment by ameshkov** [comment]
> Just for clarification, will this include HOSTS file too ?

Nope, hosts will be supported as part of the "DNS" module.

**Comment by TPS** [comment]
> Nope, hosts will be supported as part of the "DNS" module.

Even online `HOSTS`-file subscriptions?

**Comment by ameshkov** [comment]
@TPS I don't mean we won't do it:) What I am saying is that hosts-files integration should be implemented as a part of the DNS part of AG as hosts might be used not just for blocking something, but for redirection or for enforcing safe search in some search engines.

**Comment by uBlock-user** [comment]
You mean you will add it in the DNS section ?

**Comment by ameshkov** [comment]
> You mean you will add it in the DNS section of the app ?

Yeah. And they'll be used as real hosts file, not just as a list of domains to block.

**Comment by TPS** [comment]
>>You mean you will add it in the DNS section of the app ?
>
>Yeah. And they'll be used as real hosts file, not just as a list of domains to block.

Then will the "Simplified Domain Names Filter" subscription be moved here, as well?

**Comment by ameshkov** [comment]
> Then will the "Simplified Domain Names Filter" subscription be moved here, as well?

Nope, it is different. This is a "filter" with filtering rules syntax support, and not a list of domains.

**Comment by TPS** [comment]
Then [its blurb](https://github.com/AdguardTeam/AdguardDNS/blob/7349d40f8189d9eeb6635cb081ab28f18b264c5c/Filters/filter.template#L6) (from AGDNS repo, no less) confuses me mightily:
> Decsription: Filter composed from several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy) ___and simplified specifically to be better compatible with DNS-level ad blocking___.

P.S.: "De<kbd>sc</kbd>ription,"  of course!

**Comment by ameshkov** [comment]
The good thing about AG DNS is that it understands basic rules syntax.

Regarding the "simplified" part: some of the unsupported modifiers are stripped, it blocks only ad servers and does not contain rules which are not applicable (cosmetic, js, rules that block `some/location/` instead of a domain).

**Comment by Anonymous142** [comment]
This seems to be the most important, basic issue...
It's already been over 2 years... I'd like to get this feature before Android 10.0.

**Comment by uBlock-user** [comment]
Won't happen before v3.0.

**Comment by TPS** [comment]
Just a note for @AdguardTeam's sanity: Don't forget the disclaimer, "We don't support any sort of shenanigan that anything you add may do to your AG instance, device, or yourself.  You have been warned!  Take it up with the filter maintainer, & don't forgot about `Settings > User Filter` overrides [w/ a link to the KB on that]."

Or whatever that does the same job.  The list from https://github.com/AdguardTeam/AdguardForAndroid/issues/1818#issuecomment-378945048 gave me a distinct sinking feeling of impending doom! 😱

**Comment by ameshkov** [comment]
Good idea, thank you!
