### ISSUE TITLE
User filter import doesn't work on Nexus 9

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1300]
STR:
- go to user filter
- press import, choose file

expected result: Filtering rules are added to UF
actual result: Adguard is not responding

**Comment by ameshkov** [comment]
Exact Android version?
Log?

**Comment by nkartyshov** [comment]
We have problem with npe when call onActivityResult in SettingsActivity, because method getSupportFragmentManager().getFragments() returns null fragment.

I added condition on npe.

**Comment by nkartyshov** [comment]
Link to the same problem: https://stackoverflow.com/questions/44281397/getsupportfragmentmanager-getfragments-npe

**Comment by vozersky** [comment]
fixed
