### ISSUE TITLE
Invalid file types still can be imported to the UF

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1301]
Should we allow only .txt files to be uploaded to user filter?

**Comment by vozersky** [comment]
at least **.png** and **.pdf** can be imported at the moment
beta 2.9.132

**Comment by ameshkov** [comment]
@vozersky please attach a couple of invalid files you were using.

**Comment by ameshkov** [comment]
@Revertron I added a check in the current version, but it didn't help.

**Comment by zebrum** [comment]
[Enable+HTTPS+Filtering+on+Android+Nougat.pdf](https://github.com/AdguardTeam/AdguardForAndroid/files/1112501/Enable.HTTPS.Filtering.on.Android.Nougat.pdf)
.png from archive: [Screenshot_2017-06-28-19-55-32.png.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1112535/Screenshot_2017-06-28-19-55-32.png.zip)

**Comment by nkartyshov** [comment]
done
