### ISSUE TITLE
Browsers with no network security configuration

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1304]
Besides the list of browsers, we should also support the list of browsers which do not trust user certificates and not provide a network security configuration like this:
https://chromium.googlesource.com/chromium/src.git/+/lkcr/chrome/android/java/res/xml/network_security_config.xml

What needs to be done:

1. Install every browser from that list
2. Check the browser app's target SDK version (apps management -> find app -> scroll down to tech info -> check Target SDK version).
3. **If target SDK version** is 24 or more, write it down
4. Run it and check if HTTPS websites are opened okay

Fill the table:

Package name | Target SDK | HTTPS filtering support (yes/no) |
--------------- | ------------ | ---------------|
com.android.chrome|28|yes
com.chrome.beta|28|yes
com.chrome.canary|28|yes
com.chrome.dev|28|yes
org.chromium.chrome|28|yes
com.brave.browser|27|yes
com.hsv.freeadblockerbrowser|27|yes
com.microsoft.emmx|27|yes
com.yandex.browser|27|yes
com.yandex.browser.alpha|27|yes
com.yandex.browser.beta|27|yes
com.sec.android.app.sbrowser|26|yes
com.sec.android.app.sbrowser.beta|26|yes
com.yandex.browser.lite|26|yes
jp.co.fenrir.android.sleipnir|26|yes
jp.co.fenrir.android.sleipnir_black|26|yes
jp.co.fenrir.android.sleipnir_test|26|yes
jp.hazuki.yuzubrowser|26|yes
org.mozilla.fennec|26|yes
org.mozilla.fennec_aurora|26|yes
cn.mozilla.firefox|23|yes
mobi.browser.flashfox|23|yes
mobi.browser.flfoxpro|23|yes
org.adblockplus.browser|23|yes
org.iron.srware|23|yes
org.mozilla.firefox|23|yes
org.mozilla.firefox_beta|23|yes
com.android.browser|22|yes
com.droid.browser|22|yes
com.vionika.firephoenix|21|yes
com.feedback.browser.wjbrowser|27|no
com.ghostery.android.ghostery|27|no
com.mmbox.xbrowser.pro|27|no
com.opera.browser|27|no
com.opera.browser.beta|27|no
mark.via.gp|27|no
nu.tommie.inbrowser|27|no
org.mozilla.focus|27|no
acr.browser.barebones|26|no
acr.browser.lightning|26|no
com.cloudmosa.puffinFree|26|no
com.mx.browser|26|no
com.nhn.android.search|26|no
org.easyweb.browser|26|no
com.ninnix96.pyrope.browser|25|no
com.cloudmosa.puffin|24|no
com.htc.sense.browser|24|no
jp.ddo.pigsty.HabitBrowser|24|no
com.amazon.cloud9|23|no
com.apn.mobile.browser|23|no
com.apn.mobile.browser.cherry|23|no
com.asus.browser|23|no
com.mokee.yubrowser|23|no
com.rtsw.easydownloader|23|no
com.swe.atego.browser|23|no
com.UCMobile.intl|23|no
com.UCMobile.intl.x86|23|no
nextapp.atlas|23|no
org.cyanogenmod.gello.browser|23|no
com.browser.Speed|22|no
com.explore.web.browser|22|no
com.ilegendsoft.mercury|22|no
com.linkbubble.playstore|22|no
com.metalasfook.nochromo|22|no
explore.web.browser|22|no
free.reddit.news|22|no
reddit.news|22|no
com.apusapps.browser|21|no
com.apusapps.browser.turbo|21|no
com.nubelacorp.javelin|21|no
mark.via|21|no
mobi.mgeek.browserfaster|21|no
ru.mail.amigo|21|no
com.appdream.cloud|20|no
internetexplorer.browser.webexplorer|20|no
com.baidu.browser.inter|19|no
com.baidu.browserhd.inter|19|no
com.jiubang.browser|19|no
com.rocket.browser|19|no
com.uc.browser.en|19|no
net.fast.web.browser|19|no
com.ninesky.browser|18|no
jp.ddo.pigsty.Habit_Browser|18|no
me.android.browser|18|no
com.cleanmaster.security|17|no
com.cmcm.armorfly|17|no
com.dolphin.browser.android.elex|17|no
com.dolphin.browser.express.web|17|no
com.dolphin.browser.id|17|no
com.dolphin.web.browser.android|17|no
com.ksmobile.cb|17|no
mobi.mgeek.TunnyBrowser|17|no
org.tint|17|no
com.boatbrowser.tablet|16|no
com.dolphin.browser.zero|16|no
mobi.mgeek.DolphinTranslate|16|no
mobi.mgeek.mypdf|16|no
mobi.mgeek.ScreenCut|16|no
com.dolphin.browser.engine|15|no
com.boatbrowser.free|14|no
com.boatbrowser.free.addon.gc|14|no
com.boatbrowser.free.addon.twitter|14|no
com.boatgo.browser|14|no
com.boatgo.license.key|14|no
ru.yandex.shell|14|no
com.jbak.superbrowser|13|no
com.mx.browser.tablet|13|no
com.opera.browser.classic|13|no
com.opera.browser.extension|13|no
com.opera.browser.pwa|13|no
com.opera.browser.yandex|13|no
com.opera.browses|13|no
com.opera.mini.android|13|no
com.opera.mini.android.yandex|13|no
com.uc.browser.hd|11|no
com.dolphin.browser.addons.skitch|8|no
com.tencent.ibibo.mtt|8|no
mobi.mgeek.DolphinFM|8|no
mobi.mgeek.eBaySearch|8|no
mobi.mgeek.tabswitcher|8|no
mobi.mgeek.YoutubeSearch|8|no
com.boatbrowser.free.addon.en|7|no
com.boatbrowser.free.addon.fb|7|no
com.boatbrowser.free.addon.ip|7|no
com.boatbrowser.free.addon.pm|7|no
com.boatbrowser.free.addon.th|7|no
com.boatbrowser.free.addon.us|7|no
com.boatbrowser.license.key|7|no
com.dolphin.addons.evernotesshare|7|no
com.fevdev.nakedbrowser|7|no
com.fevdev.nakedbrowserpro|7|no
mobi.mgeek.BookmarksWidget|7|no
com.dolphin.browser.addons.box|6|no
com.dolphin.theme.ocean|5|no
mobi.mgeek.alex|5|no
mobi.mgeek.brightness|5|no
mobi.mgeek.DolphinReader|5|no
mobi.mgeek.MorningCoffee|5|no
mobi.mgeek.shinyshake|5|no
mobi.mgeek.showi|5|no
mobi.mgeek.TabHistory|5|no
mobi.mgeek.TabMixPlus|5|no
mobi.mgeek.tabreload|5|no
mobi.mgeek.textadjust|5|no
mobi.mgeek.TunnyBrowser.Theme.EnNightModeV10|5|no
mobi.mgeek.UltimateFlag|5|no
mobi.mgeek.whois|5|no
com.dolphin.addons.dropbox|4|no
com.dolphin.addons.pocket|4|no
com.dolphin.battery.saver|4|no
com.dolphin.browser|4|no

Here is the list of registered browsers you should test:
<details>

```
// List of browsers supported by AdGuard
acr.browser.barebones
acr.browser.lightning
cn.mozilla.firefox
com.amazon.cloud9
com.android.browser
com.android.chrome
org.cyanogenmod.gello.browser
com.apn.mobile.browser
com.appdream.cloud
com.asus.browser
com.baidu.browser.inter
com.baidu.browserhd.inter
com.boatbrowser.free
com.boatbrowser.license.key
com.boatbrowser.tablet
com.boatgo.browser
com.chrome.beta
com.chrome.dev
com.chrome.canary
com.chrome.deviceextras.samsung
com.cleanmaster.security
com.cloudmosa.puffin
com.cloudmosa.puffinFree
com.dolphin.browser
com.dolphin.browser.android.elex
com.dolphin.browser.engine
com.dolphin.browser.express.web
com.dolphin.browser.id
com.dolphin.browser.zero
com.dolphin.web.browser.android
com.droid.browser
com.explore.web.browser
com.fevdev.nakedbrowser
com.fevdev.nakedbrowserpro
com.ghostery.android.ghostery
com.htc.sense.browser
com.ilegendsoft.mercury
com.jbak.superbrowser
com.jiubang.browser
com.ksmobile.cb
com.linkbubble.playstore
com.metalasfook.nochromo
com.mmbox.xbrowser.pro
com.mx.browser
com.mx.browser.tablet
com.ninesky.browser
com.nubelacorp.javelin
com.opera.browser
com.opera.browser.beta
com.opera.browser.classic
com.opera.browser.yandex
com.opera.mini.android
com.opera.mini.android.yandex
com.rocket.browser
com.sec.android.app.sbrowser
com.sec.android.app.sbrowser.beta
com.swe.atego.browser
com.tencent.ibibo.mtt
com.uc.browser.en
com.uc.browser.hd
com.UCMobile.intl
com.UCMobile.intl.x86
com.vionika.firephoenix
com.yandex.browser
com.yandex.browser.alpha
com.yandex.browser.beta
explore.web.browser
internetexplorer.browser.webexplorer
jp.ddo.pigsty.Habit_Browser
jp.ddo.pigsty.HabitBrowser
me.android.browser
mobi.browser.flashfox
mobi.browser.flfoxpro
mobi.mgeek.TunnyBrowser
net.fast.web.browser
nextapp.atlas
nu.tommie.inbrowser
org.adblockplus.browser
org.easyweb.browser
org.chromium.chrome
org.mozilla.fennec
org.mozilla.fennec_aurora
org.mozilla.firefox
org.mozilla.firefox_beta
org.tint
ru.mail.amigo
ru.yandex.shell
// Boat browser add-ons (https://github.com/AdguardTeam/AdguardForAndroid/issues/187)
com.boatbrowser.free.addon.fb
com.boatbrowser.free.addon.gcp
com.boatbrowser.free.addon.th
com.boatbrowser.free.addon.ip
com.boatbrowser.free.addon.pm
com.boatbrowser.free.addon.us
com.boatbrowser.license.key
com.boatbrowser.free.addon.twitter
com.boatbrowser.free.addon.en
com.boatgo.license.key
// Dolphin browser add-ons (https://github.com/AdguardTeam/AdguardForAndroid/issues/187)
com.dolphin.addons.dropbox
com.dolphin.addons.evernotesshare
com.dolphin.addons.pocket
com.dolphin.battery.saver
com.dolphin.browser.addons.box
com.dolphin.browser.addons.skitch
com.dolphin.browser.engine
com.dolphin.browser.express.web
com.dolphin.theme.ocean
com.dolphin.web.browser.android
mobi.mgeek.alexa
mobi.mgeek.BookmarksWidget
mobi.mgeek.brightness
mobi.mgeek.browserfaster
mobi.mgeek.DolphinFM
mobi.mgeek.DolphinReader
mobi.mgeek.DolphinTranslate
mobi.mgeek.eBaySearch
mobi.mgeek.MorningCoffee
mobi.mgeek.mypdf
mobi.mgeek.ScreenCut
mobi.mgeek.shinyshake
mobi.mgeek.showip
mobi.mgeek.TabHistory
mobi.mgeek.TabMixPlus
mobi.mgeek.tabreload
mobi.mgeek.tabswitcher
mobi.mgeek.textadjust
mobi.mgeek.TunnyBrowser.Theme.EnNightModeV10
mobi.mgeek.UltimateFlag
mobi.mgeek.whois
mobi.mgeek.YoutubeSearch
mark.via
// https://play.google.com/store/apps/details?id=com.rtsw.easydownloader
com.rtsw.easydownloader
// https://github.com/AdguardTeam/AdguardForAndroid/issues/316
jp.co.fenrir.android.sleipnir
jp.co.fenrir.android.sleipnir_test
jp.co.fenrir.android.sleipnir_black
// https://github.com/AdguardTeam/AdguardForAndroid/issues/449
com.apusapps.browser
com.apusapps.browser.turbo
// https://github.com/AdguardTeam/AdguardForAndroid/issues/488
org.iron.srware
// https://github.com/AdguardTeam/AdguardForAndroid/issues/537
com.browser.Speed
// https://github.com/AdguardTeam/AdguardForAndroid/issues/708
com.opera.browser.pwa
// https://github.com/AdguardTeam/AdguardForAndroid/issues/757
com.opera.browser.extension
// http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=58805939
com.opera.browses
// https://github.com/AdguardTeam/AdguardForAndroid/issues/808
com.ninnix96.pyrope.browser
// https://github.com/AdguardTeam/AdguardForAndroid/issues/862
com.cmcm.armorfly
// https://github.com/AdguardTeam/AdguardForAndroid/issues/922
com.mokee.yubrowser
com.brave.browser
// https://github.com/AdguardTeam/AdguardForAndroid/issues/1285
jp.hazuki.yuzubrowser
// https://github.com/AdguardTeam/AdguardForAndroid/issues/1303
com.yandex.browser.lite
// https://github.com/AdguardTeam/AdguardForAndroid/issues/1426
reddit.news
// https://github.com/AdguardTeam/AdguardForAndroid/issues/1530
com.microsoft.emmx
// https://github.com/AdguardTeam/AdguardForAndroid/issues/1660
com.hsv.freeadblockerbrowser
// https://github.com/AdguardTeam/AdguardForAndroid/issues/1821
com.feedback.browser.wjbrowser
```
</details>

**Comment by sfionov** [comment]
"com.android.browser" may be not the original AOSP browser but browser customized by firmware vendor, inherited from dark ages android.

**Comment by ameshkov** [comment]
@sfionov most likely to be old and not targeting SDK 25, so we can count it as supporting HTTPS filtering right away.

**Comment by ameshkov** [comment]
How it goes guys?

**Comment by zebrum** [comment]
it goes slowly but still it goes

**Comment by ameshkov** [comment]
> Could not find information about these browsers:

How so?

Here's opera mini for instance:
https://play.google.com/store/apps/details?id=com.opera.mini.android

**Comment by ameshkov** [comment]
@nkartyshov 

Also, don't forget to update the default HTTPS filtering settings in AG with the information we now know.

**Comment by ameshkov** [comment]
Also, don't forget that Firefox-based browsers have their own way of checking HTTPS certificates and they don't rely on Android for that.

**Comment by ameshkov** [comment]
@nkartyshov for `com.opera.*` -- use the same as for other browsers.
`com.android.browser` and `com.droid.browser` are old chrome-based browsers, they do support https filtering.

**Comment by nkartyshov** [comment]
Updated
