### ISSUE TITLE
[Feature Request] New Filter Lists

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardForAndroid#1305]
Can you please add these new filter lists, also can you look at adding some of the lists used by uBlock and dns66 (github.com/julian-klode/dns66).

Thanks

https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

**Comment by vozersky** [comment]
@AdguardTeam/filters-maintainers Please check if it's any good

**Comment by zero77** [comment]
Yes I have used them all and they each block lots of additional adds.

**Comment by ameshkov** [comment]
Regarding Steven Black:
https://github.com/AdguardTeam/AdguardDNS/issues/148#issuecomment-311228763

We'll add an option to import hosts file eventually, but frankly, most of the public hosts files quality is questionable.

**Comment by zero77** [comment]
yes, I don’t use the Steven Black lists but, I do use the other recommended ones there.
The option to add your own lists would be excellent.

**Comment by TPS** [comment]
> The option to add your own lists would be excellent.

@zero77 That's #13, currently milestoned for <kbd>[3.0](https://github.com/AdguardTeam/AdguardForAndroid/milestone/2)</kbd>.

**Comment by ameshkov** [comment]
Dup of #13
