### ISSUE TITLE
Rework Firewall functions for Adguard

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardForAndroid#1306]
After installation of a new app Adguard should detect it and ask for desired settings. 

It should be similar to NetGuard that blocks all new apps and then gives a notification for the app it blocked, which I can click to configure that app. 

Ticket ID: 1583184

**Comment by vozersky** [comment]
It makes sense

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1069

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
