### ISSUE TITLE
[Feature request] Make it one string per rule for User filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1307]
Currently UF looks like a mess:

<details><summary>Screenshot</summary>

![pic](https://forum.adguard.com/index.php?attachments/screenshot_20170629-173603-png.9026/)

</details>

Maybe it would be nice to make it one string per rule or distinguish rules in some different way.

Original thread: 
https://forum.adguard.com/index.php?threads/22229/#post-142904

**Comment by ameshkov** [comment]
I've tried a few different ways of doing it, but Android's native "EditText" control is rather unstable.

**Comment by Alex-302** [comment]
@ameshkov is it possible to change background color for even/odd rules? It would be more convenient to work with them.

**Comment by ameshkov** [comment]
In the data grid -- yes. In the textarea control -- I'd better avoid changing it.

**Comment by Alex-302** [comment]
I mean the data grid only.
But it is unnecessary. I forgot about reworked user filter with checkboxes.
