### ISSUE TITLE
Update fails on Android N

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1308]
android 7 
crashed while updating from beta .111 to beta .133

`android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.adguard.android/cache/adguard.apk exposed beyond app through Intent.getData()`

**Comment by ameshkov** [comment]
There're also a lot of complaints from people using Android O

**Comment by mgrep** [comment]
The same here, the update from beta .111 to beta .133 adguard freezes and I can only close the app and if I launch the app afterwards it is not updated.
I have to explicitly remove beta .111 before installing beta .133

**Comment by ameshkov** [comment]
Could you please reproduce the issue and get AG log from the device?

Here are the possible log locations:
https://kb.adguard.com/en/android/solving-problems/log

I'd just like to compare it with what we have to check if it is the same problem or something new.

**Comment by nkartyshov** [comment]
fixed
