### ISSUE TITLE
Adguard doesn't write log files

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1310]
Нашел интересный баг на adguard 2.9.70. Nexus 5 android 4.4.4. Я захожу в настройки, память и очистить данные кэша. После чистки я захожу в adguard, включаю лог веб запросов, HAR, перезагружаю, воспроизвожу проблему, ставлю логи в обычном режиме и в той папке, где должны быть логи, их нет. Просто нет. Там только файл cache, с которым нельзя ничего сделать. Далее я перезагружаю телефон и делаю все тоже самое, логи появляются. Может и на других версиях Android такое, нужно проверить. Могу записать видео. Если на других версиях такого нет, значит только на Android 4.4.4, а если так, то не думаю, что будете исправлять этот баг и надобность в видео тоже отпадает

**Comment by vozersky** [comment]
@zebrum нужно понять, в чем причина

**Comment by ameshkov** [comment]
После чистки кэша нужно перезапускать Adguard.

**Comment by vozersky** [comment]
Не уверен, что это связано с очисткой кэша. @ministr91 можешь на своей стороне проверить?

**Comment by zebrum** [comment]
у меня не повторилось на 4.4.2.

**Comment by ministr91** [comment]
@vozersky, что проверять? У меня есть эта проблема. @smeshkov написал,  что после чистки нужно перезапускать устройство. Можно исправить эту проблему и не перезапускать устройство каждый раз после чистки кэша?

**Comment by vozersky** [comment]
@ministr91 Нет, если такое поведение исключительно после очистки кэша, то это не проблема.

**Comment by ministr91** [comment]
@vozersky, исключительно после очистки кэша. Почему это не проблема? Я очищаю кэш, спустя какое-то время хочу сделать лог запросов, но не могу из-за этой проблемы

**Comment by ministr91** [comment]
@vozersky, @ameshkov, почему нельзя решить эту проблему?

**Comment by ameshkov** [comment]
@ministr91 потому что это не наша проблема, а андроида, он слишком тихо очищает кэш, мы не можем отдетектить это событие.

**Comment by ministr91** [comment]
@ameshkov как тихо? Я нажимаю очистить и кэш 1 раз очищается весь и все.

**Comment by ameshkov** [comment]
Тихо всмысле приложение не уведомляется
