### ISSUE TITLE
CM Security Master for Android - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1311]
CM Security Master for Android seems to detect Adguard as a malicious app. We may want to report it somewhere:

![screenshot_20170703-113730](https://user-images.githubusercontent.com/15856304/27789174-22cdb2e8-5ff4-11e7-9087-a3eed625cacd.png)

https://play.google.com/store/apps/details?id=com.cleanmaster.security&hl=ru

**Comment by vozersky** [comment]
@zebrum  we have to report this FP

**Comment by zebrum** [comment]
reported.
