### ISSUE TITLE
First string is imported as a rule even if it is a comment.

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1313]
Adguard beta 2.9.133

It seems that if comment string goes first in .txt file it will be imported as a rule.

<details>

![screenshot_20170629-174040](https://user-images.githubusercontent.com/23637588/27801342-25d5f98c-6026-11e7-9b6e-44cdcf7b8937.png)

</details>

**Comment by ameshkov** [comment]
Cannot reproduce, need a link to that problematic file

**Comment by zebrum** [comment]
[rules.txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1122392/rules.txt.zip) or just https://www.dropbox.com/s/pxfynu8hycunewh/rules.txt?dl=0

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-55
