### ISSUE TITLE
Captured HAR is invalid

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1314]
[adguard.7z.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1120151/adguard.7z.txt)

<details>

![image](http://imagizer.imageshack.com/img922/4237/LujwXz.png)
</details>

It can be fixed in Linux by
```
iconv -f utf-8 -t utf-8 -c adguard.har > adguard.har
tr < adguard.har -d '\000' > filtered.har
```

Is it possible to fix HAR while capturing?

**Comment by nkartyshov** [comment]
@Alex-302 Yes, we can remove special symbols in har file

**Comment by nkartyshov** [comment]
done, review AFA-CR-63
