### ISSUE TITLE
Introduce a "user profile". Each "profile" should have an independent set of settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#132]
Linked issues (read comments there):
https://github.com/AdguardTeam/AdguardForAndroid/issues/268
https://github.com/AdguardTeam/AdguardForAndroid/issues/176

**Comment by Bohdan-SUP** [comment]
Is it first step towards Parental Control?

**Comment by ameshkov** [comment]
Nah, it does not solve the main problem - it is very hard to protect the app from the user:)
