### ISSUE TITLE
Wi-Fi calling Verizon issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1321]
> When I switched from using a Verizon Samsung S5 with Android 6 to a **Verizon LG G5 with Android 7**: wifi calling stops working when running Adguard and only starts working again when I disable Adguard and restart my G5. The issue has persisted for about two months despite my changing a lot of settings. I saw that Verizon wifi uses many different IP addresses and URL, but all URL ends with domain myvzw.com, so I added that domain to my whitelist, and there was no effect. Yesterday, I enabled detailed logging while wifi calling was blocked and hopefully, that is attached here. **When I try to make a call, I get a message from the OS like "you cannot make phone calls in airplane mode. disable airplane mode in order to make a call"**. It's like Adguard is preventing the OS from realizing that wifi calling is operational.  
> I tried using the beta Adguard releases with no effect. 
> 

  "androidVersion" : "7.0 (sdk=24)",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "dnsFilteringEnabled" : true,
  "enabledFilterIds" : [ 2, 3, 4, 14, 10, 1, 6, 9, 11, 15, 211 ],
  "filteringQuality" : "FULL",
  "iconType" : "DEFAULT",
  "proxyMode" : false,
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":false,\"mitmList\":\"2129 domains\",\"mitmListMode\":\"WHITELIST\",\"filterEvCertificates\":false}",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:45429; Traffic saved:1186838528;",
  "upstreamProxySettings" : null,
  "userfilter" : "",
  "versionName" : "2.9.133",

ID, logs: 1288741

**Comment by ameshkov** [comment]
Relevant discussion:
https://community.verizonwireless.com/thread/907073

It seems that Verizon uses `141.207.*.232` addresses for Wi-Fi calling.

@evgeniy-ADG please ask the user to do the following:

1. Settings -> Advanced -> Low-level
2. Find and tap on `pref.vpn.ipv4.routes.excluded`
3. Add a new line there:
    `141.207.0.0/16`

Please let me know if it helps.

**Comment by evgeniy-ADG** [comment]
done.

**Comment by ameshkov** [comment]
@evgeniy-ADG did it help?

**Comment by evgeniy-ADG** [comment]
Sorry. It helped.

**Comment by ameshkov** [comment]
@nkartyshov we should add one more route to the default exclusions, see here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1321#issuecomment-314417215

**Comment by nkartyshov** [comment]
added
