### ISSUE TITLE
Moscow subway and custom DNS settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1322]
It seems that UDP packets to DNS servers different from regular are dropped in the Moscow subway (at least according to the log).

I guess we won't be able to fix this, but at least AdGuard should not crash.

### Steps to reproduce

1. Visit Moscow :)
2. Go down to the subway
3. Enable custom DNS. You can use regular DNS or DNSCrypt, it does not matter.
4. Connect to the subway Wi-Fi (MT_FREE) and try using the internet

### Expected behavior
You are able to surf the internet.

### Actual behavior
Nothing loads;
Eventually, Adguard crashes due to `Too many open files` issue.;

### Your environment
Property | Value
------- | ---------
Adguard version | 2.10 dev build
Adguard filtering mode | VPN
Device model | Google Pixel
Operating system and version | Android 8 DP
Rooted or not? | Not rooted
Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? | Nothing

**Comment by ameshkov** [comment]
It crashes because SO_TIMEOUT is ignored for the DNS requests:
https://stackoverflow.com/questions/15337845/how-to-achieve-timeout-handling-in-blocking-datagramchannel-without-using-select

> Not a bug. The read methods in SocketChannel (and DatagramChannel) do not support timeouts. If you need the timeout functionality then use the read methods of the associated Socket (or DatagramSocket) object.

**Comment by ministr91** [comment]
Что надо сделать?

**Comment by ministr91** [comment]
Неделю назад все было в норме

**Comment by ameshkov** [comment]
Ничего, это не про релизную версию, а про девелоперский билд

**Comment by TPS** [comment]
_(Related to #41 & #1154, I suppose.)_

**Comment by ameshkov** [comment]
> (Related to #41 & #1154, I suppose.)

Nah, that's something new :)

**Comment by ameshkov** [comment]
Fixed. The problem was not in the subway network, but in our code, extra zero byte in the request. 

Review ID:
AFA-CR-49
