### ISSUE TITLE
Add Avito app to SSL exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1324]
They've enabled SSL pinning

**Comment by nkartyshov** [comment]
cannot reproduce

**Comment by nkartyshov** [comment]
Need to add domain `avito.ru` in HTTPS whitelist.

**Comment by ameshkov** [comment]
That's too much, let's add the app to exclusions

**Comment by nkartyshov** [comment]
done
