### ISSUE TITLE
Low upload speed with Adg enabled

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardForAndroid#1325]
- Connected to WiFi network and mobile network
- In the screenshot, the first two tests in the list with AdGuard enabled, the next two are off. 
- Software: NetPerform from Vodafone

<details><summary>Screenshot:</summary>

![screenshot_20170715-022209](https://user-images.githubusercontent.com/28784344/28239480-c238ddf0-6975-11e7-9b7e-b4681e97e95b.png)

</details>

* Adguard version: 2.9.70
* Adguard filtering mode:  Proxy(manual)
* Device model: Samsung SM-G935F
* Operating system and version: Android 7.0
* CustomerID: 1316642

**Comment by ameshkov** [comment]
Please ask the user if he is ready to test a dev build? We have improved the network stack in the new version, but it's not yet ready for beta test. I can send a dev build, though.

**Comment by ameshkov** [comment]
If he is, the new build is ready

**Comment by ypetruk** [comment]
asked, waiting for the user`s reply

**Comment by ypetruk** [comment]
the user responded that he`s ready

**Comment by ameshkov** [comment]
Here it is then:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1289#issuecomment-316101772

**Comment by ypetruk** [comment]
<details><summary>Screenshot:</summary>

![screenshot_20170719-164857](https://user-images.githubusercontent.com/28784344/28392007-daefa196-6ce8-11e7-97a2-badf62658748.png)

</details>

Downloaded, installed, and that's what the user sees now (the screenshot)
 he tried to enable the local HTTP proxy, but alas - other applications can not go online

**Comment by ameshkov** [comment]
@ypetruk my bad, I've updated (same link) that build and it should now work okay.

**Comment by ypetruk** [comment]
ticket ID: 1076761
when advised to try a new dev build, another user has got the same issue:
<details><summary>Screenshot:</summary>

![screenshot_2017-07-24-15-24-01-833](https://user-images.githubusercontent.com/28784344/28521294-a1ea894c-707b-11e7-9fc1-01a760ac11bc.jpeg)

</details>

**Comment by ameshkov** [comment]
That's odd, let's wait till the beta version is ready then

**Comment by ypetruk** [comment]
Are there any time frames for a new beta version to be released?

**Comment by ameshkov** [comment]
@ypetruk yep, this week.

**Comment by ypetruk** [comment]
@ameshkov thank you! :)

**Comment by ameshkov** [comment]
@ypetruk 
plz ask users to test the latest beta version

**Comment by ypetruk** [comment]
@ameshkov  sent the links and asked to test it!

**Comment by ameshkov** [comment]
@ypetruk any update?

**Comment by ypetruk** [comment]
@ameshkov no, no replies from the customers

**Comment by The-Commissioner** [comment]
Maybe they already uninstalled it. :(
I don't blame them.

**Comment by ameshkov** [comment]
Reopen it if there's new information

**Comment by vitbortnik** [comment]
ID: 1076761
>Hello,
I have tried with this version but still issue exist. please
see below images. Notice speed shown at upper left corner.

<details><summary>Screenshot1:</summary>

![image](https://user-images.githubusercontent.com/30041399/31137614-752b6dc8-a874-11e7-8556-5748a5387b95.png)

</details>

<details><summary>Screenshot2:</summary>

![image](https://user-images.githubusercontent.com/30041399/31137627-7c598e40-a874-11e7-8022-1d275293b076.png)


</details>

**Comment by ameshkov** [comment]
Guys, this looks like a fluctuation to me.
