### ISSUE TITLE
Investigate the possibilities of blocking ads in the FB app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1326]
Reddit thread:
https://www.reddit.com/r/Android/comments/6mt61u/your_facebook_messenger_app_is_about_to_be_filled/dk7x39t/?context=3

Reddit post about hidden settings:
https://www.reddit.com/r/Android/comments/6gsn5m/turn_off_messenger_my_day_on_latest_version_root/

**Comment by ameshkov** [comment]
@vozersky get a rooted device, unlock FB dev settings, uncheck the "SSL pinning" there and then check if HTTPS filtering works for the app. Don't forget that in case of an Android N+ device you'll also have to move certificate to the system store.

**Comment by nkartyshov** [comment]
@ameshkov The FB Messenger works fine, if SSL pinning is disabling in internal settings.

**Comment by nkartyshov** [comment]
@ameshkov The FB Messenger works fine, if SSL pinning is disabling in internal settings.

**Comment by ameshkov** [comment]
Does it mean that we can actually filter SSL for it?

**Comment by ameshkov** [comment]
Is it required to move certificate to the system store?

**Comment by nkartyshov** [comment]
Yes, I moved certificate to the system store and enable https filtering for app.

**Comment by ameshkov** [comment]
And what about regular FB app?

**Comment by nkartyshov** [comment]
The same as the FB messenger.

**Comment by ameshkov** [comment]
Plz record a HAR file

**Comment by nkartyshov** [comment]
@ameshkov The HAR file and the log file
[adguard_logs_2.10.105_2709_1422.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1336907/adguard_logs_2.10.105_2709_1422.zip)

**Comment by nkartyshov** [comment]
Not a very reliable approach, in the new version of the FB it is not possible to open the hidden settings. But I do not see ads in the application with Https filtering enabled.

**Comment by ameshkov** [comment]
> But I do not see ads in the application with Https filtering enabled.

Does HTTPS filtering work without tweaking settings?

**Comment by nkartyshov** [comment]
Yes, it is not filtered without tweaking settings.

**Comment by nkartyshov** [comment]
But maybe I do not see the advertisement, because I have a new account.

**Comment by ameshkov** [comment]
To sum up -- in the new version of the FB apps there is no possibility to disable SSL pinning?

**Comment by nkartyshov** [comment]
@ameshkov Yes

**Comment by ameshkov** [comment]
That's unfortunate :(

**Comment by carlylemiii** [comment]
They've kept the menu available in Messenger, though, with access to most settings (not the SSL one) not available if not a Fb employee. So I wonder if that one will stick around?
