### ISSUE TITLE
Feature Request: allow to enable/disable multiple filters at once

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1328]
E.g. you toggle some filters and then you are offered a choice to apply all the changes (for example, a panel at the bottom).

Original thread: https://forum.adguard.com/index.php?threads/23261/#post-144644

**Comment by ameshkov** [comment]
I don't know guys, with the new design planned for v3.0 it would be really useless.

**Comment by vozersky** [comment]
not really applicable since we have filter groups now
