### ISSUE TITLE
Delay in website loading while in simplified domains filter

### ISSUE THREAD

**Issue by bendingtime** [AdguardTeam/AdguardForAndroid#1329]
Hi while loading any link from gazeta.pl website on chrome there is a few seconds delay between tap and actual website loading.

### Steps to reproduce

1. Set adblock to simplified domain filter,
2. Set it to block all apps,
3. Enable https filtering,
4. Open website. www.gazeta.pl
5. Tap any link on that website.

### Expected behavior

I expect that browser would go immediately to link I tapped.
### Actual behaviour

I have to wait few second which look like browser hanged.

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

1273363
### Your environment

* Adguard version: 2.9.135
* Adguard filtering mode: VPN/ Simplified domain filter with battery saving tweaks enabled in advanced settings
* Device model: OnePlus3T
* Operating system and version: Android 7.1.2
* Rooted or not? NOT
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NOPE

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #5742](https://github.com/AdguardTeam/AdguardFilters/issues/5742) via [**ZenHub**](https://www.zenhub.com/)
