### ISSUE TITLE
Export/import all profile's settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#133]
First of all, we should have a settings backup format so that we could make a decision whether to allow settings import or not. 

Something like that:
```
{
    version: "2.9.135", // Adguard version
    protocolVersion: 1, // Protocol version (if this version is different in the backup file -- do not import it)
    enabledFilters: [ 1,2,3 ],
    userFilter: "here goes the user filter content",
    whitelist: "here goes the whitelist content",
    preferences: { "pref key" : "pref value"  },
    advancedPreferences: { "pref key": "pref value" },
    ....
    // what else?
}
```

Importing a file should lead to protection restart.

**Comment by Michael23456** [comment]
I would to like see function to Import
& Export the settings configured. Or anything which is customize
manually not set in default or be able to split by default & users
section. e.g. LOW LEVEL SETTINGS, https blacklist and whitelist.
Understand that if anyone report issue on https issue, adguard will
add and release it on update, but there maybe more which we can
customize it yourself hence splitting in default, and user section,
hence we can also backup all user section self added filtering, not
affecting the default apps update and being overwritten too. Hope to
see more splitting between system default and user section, hence our
own customization will not be overwritten upon any app updates
CustomreID:1490298

**Comment by TPS** [comment]
I suppose this would be preparatory for #108/#134, as well as making debug (pre-ß) builds easier to test.

**Comment by Revertron** [comment]
It will be right to save all settings in JSON format instead of SharedPreferences, because why we need so many convertations from XML to objects and to json again?
Could we give the user already saved json with config instead of converting it?

**Comment by ameshkov** [comment]
@Revertron I suppose that it does not matter much what format we choose if it works:)

**Comment by TPS** [comment]
Just as thought: built-in back- & foreward compatibility would probably be essential, especially for ß-testing.

**Comment by Revertron** [comment]
Yes, @TPS, I've thought about it. We need compatibility, not inability to import old config to new versions of app.

**Comment by TPS** [comment]
Would it be possible to extend this to the builtin Google app-settings backup?  _(If so, yes, I understand, it needs a new issue! 😜)_

**Comment by ameshkov** [comment]
> Would it be possible to extend this to the builtin Google app-settings backup? (If so, yes, I understand, it needs a new issue! 😜)

Do you mean [this](https://developer.android.com/guide/topics/data/autobackup.html#Files)? 

If I am getting it right, AG should be already compatible as it is enabled by default. Isn't it?

**Comment by ameshkov** [comment]
> Apps that target Android 6.0 (API level 23) or higher automatically participate in Auto Backup.

I wonder why don't I see AG among the backed up apps..

**Comment by TPS** [comment]
Of course, since AG _isn't_ GPlay-approved, maybe it doesn't get the backup benefit.…

**Comment by ameshkov** [comment]
@TPS yup, filed: https://github.com/AdguardTeam/AdguardForAndroid/issues/1396

> Of course, since AG isn't GPlay-approved, maybe it doesn't get the backup benefit.…

I see some test apps I've build myself there, so I doubt GPlay is necessary.

**Comment by ameshkov** [comment]
@Revertron there should be a progress dialog when you import settings.

**Comment by ameshkov** [comment]
@Revertron proxy settings are not exported

**Comment by Revertron** [comment]
Made a dialog and fixed proxy settings import.
