### ISSUE TITLE
Lost Kingdom app issue- Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardForAndroid#1330]
When Adguard enabled the app Lost Kingdom (https://play.google.com/store/apps/details?id=com.ftt.lostkaos&hl=ko) doesn't work properly - it doesn't let the user login
when https filtration for this app disabled- still doesn't work properly
but when the app is whitelisted - it works properly ( login process )
Adguard for Android
version: 2.9.135
enabled filters : 2, 3, 4, 14, 10, 11, 102, 211
filtering quality: full
Ticket ID: 1597829

**Comment by vozersky** [comment]
@ypetruk does it work if you disable all filters but keep protection enabled?

**Comment by vozersky** [comment]
filtering issue most likely

**Comment by ypetruk** [comment]
it works well when all filters are disabled but having protection still enabled ( but I couldn't log out of the application to log in once more - because of the language hindrances)

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #5744](https://github.com/AdguardTeam/AdguardFilters/issues/5744) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zebrum** [comment]
I was not able to run the game with all filters disabled. Only when https filtering and ad blocking are turned off the game works fine.  @ypetruk  For now, please ask user to exclude the game from filtering in Apps management settings.

with other VPN (pure vpn) game works fine.

and @nkartyshov will check what can be done.

**Comment by nkartyshov** [comment]
App added in the ad blocking exclusions
