### ISSUE TITLE
Add support for browsers cloned by the "App Cloner"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1333]
[App Cloner](https://play.google.com/store/apps/details?id=com.applisto.appcloner&hl=en) generates package name by changing the last character in the package name to the next ASCII character.

`com.opera.browser` -> `com.opera.browses`
`com.opera.mini.native` -> `com.opera.mini.nativf`

Free AG version cannot detect a cloned browser as it looks for an exact match in the list of known browsers.

We should change the index a bit and ignore the last character while doing a lookup.

**Comment by nkartyshov** [comment]
Done, review AFA-CR-57
