### ISSUE TITLE
Google Apps stop working with "No network" error

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1334]
### Expected behavior
No network error while using YouTube app, Facebook Messenger, Adsense and other apps.

### Actual behaviour
Apps like Facebook Messenger and Adsense stop working with "No network" error. This is happening even after user whitelisted those apps.

<details><summary>Screenshot:</summary>

![screenshot_20170716-225025](https://user-images.githubusercontent.com/28726429/28379590-e191251e-6cbc-11e7-80ec-266521009e51.png)

</details>

[1182498_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1159875/1182498_logs.zip)

### Customer ID 
1182498

### Your environment

* Adguard version: 2.9.135
* Adguard filtering mode: VPN
* Device model: OnePlus 5
* Android 7.1.1
* Not rooted
* No task killer/cleaner apps. No other apps are using VPN. Adguard is whitelisted on the
battery optimization (Doze).

**Comment by altokarev** [comment]
There is one more case on our forum. Original thread: https://forum.adguard.com/index.php?threads/youtube-issues.23498/

[1599135_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1159888/1599135_logs.zip)

**Comment by ameshkov** [comment]
Got it. I need more logs of this issue ,though.

**Comment by ameshkov** [comment]
Promoted to `P1: Critical`, we'll have to release a hotfix for v2.9R2 that will fix the issue.

**Comment by ameshkov** [comment]
One more report:
https://forum.adguard.com/index.php?threads/adguard-is-blocking-google-apps-internet-access.23634/

**Comment by ypetruk** [comment]
Logs in the Ticket ID:1601169

**Comment by ypetruk** [comment]
more logs in Ticket ID: 1594079

**Comment by altokarev** [comment]
[1601169_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1169358/1601169_logs.zip)

**Comment by ameshkov** [comment]
@ypetruk @altokarev please ask people to try the latest build: https://adguard.com/apkb

**Comment by veronikasav** [comment]
Customer feedback:

"So I have downloaded the latest beta and I have updated the filters and it looks that it finally works ok. By the way, maybe it's useful for you to know that the bug didn't allow to pay on Google play. So I'm happy that finally, you have fixed it."

Ticket ID: 1600755

**Comment by ypetruk** [comment]
the beta is not working either https://adguard.com/apkb
Ticket ID: 1406620

**Comment by ameshkov** [comment]
Logs?

**Comment by psych** [comment]
I am experiencing the same error/problem when using Chrome on Android (using Lineage OS, but also stock android). Any website I navigate to https or not causes chrome to display "err_connection_refused" error. Interestingly, it doesn't seem to affect their built in browser on Lineage OS which continues to connect to the internet and does not display the "no internet" error. Stopping and restarting protection using the green button solves the problem temporarily. I am also on the latest beta as recommended above.

Will try and obtain logs.

**Comment by ameshkov** [comment]
@psych 
> using Lineage OS but also happened using stock Android

I've examined the log and this is another issue for sure: #1345 

For some unknown reason, Lineage OS starts dropping AG connections after some time. To understand what's going on we need to take a look at the system logs. Here's how to get them:
https://kb.adguard.com/en/android/solving-problems/logcat

**Comment by ameshkov** [comment]
It still happens from time to time. We should temporary remove `||app-measurement.com^` to solve the issue. Uncomment it once the new update goes live.

**Comment by Bohdan-SUP** [comment]
Anything we can suggest in the meantime?

**Comment by ameshkov** [comment]
@Bohdan-SUP update filters:
https://github.com/AdguardTeam/AdguardFilters/commit/cf4609b02757b726aa5487a43b0dee3dd5bbb9ec

**Comment by carlylemiii** [comment]
Not sure if this is the same issue, but the Google Home app won't load anything with HTTPS filtering enabled. There was an update to that app today because of new products, so I'm not sure if it's related or it's always been that way.

Regardless, having AdGuard disabled allows it to work, as does disabling just HTTPS filtering, but as soon as everything is filtered, there's a looping animation that eventually ends in "No connection".

https://www.dropbox.com/sh/gtd5t6xh97mg1g6/AADUAs4LrfQTpwGsIdlvOViba?dl=0

**Comment by ameshkov** [comment]
@carlylemiii 
Filed a new issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1515

**Comment by carlylemiii** [comment]
Google Maps has displayed the no connection error probably half a dozen times so far since I've switched over to proxy mode.

[adguard_logs_2.10.186_2501_1431.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1665593/adguard_logs_2.10.186_2501_1431.zip)

But since it seems you implemented a temporary fix back in August, not sure if it's related.

**Comment by ameshkov** [comment]
CoreLibs filtering engine is coming soon, closing this issue in favor of the new one: https://github.com/AdguardTeam/CoreLibs/issues/182
