### ISSUE TITLE
Toggle to turn off/on all user filters & whitelist for debugging

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1335]
@AdGuardTeam

Like @ the filtering _log_, I'd like a toggle on each of user filterlist & whitelist to aid filter debugging.

Related to #1328, possibly duplicates #1277, & really should've been included in #1279. 

### Steps to reproduce

1. I want to debug a potential filtering problem, but I don't know if it's from 1 of my many filters/whitelist, or AG's.
2. 1st step, then, would be to turn off all userlists & reload app/page.

### Expected behavior

I should have a toggle across top of user filters & whitelist to do this.

### Actual behavior

There isn't! 😭

### Your environment

* Adguard version: 2.9.135, Amazon ß
* Adguard filtering mode: VPN
* Device model: Nextbit (now Razer) Robin
* Operating system and version Android 7.1.1
* Not Rooted
* Any other apps, &c? N/A

**Comment by ameshkov** [comment]
We should keep this in mind while implementing the redesigned v3.0

**Comment by nkartyshov** [comment]
done
