### ISSUE TITLE
Fix widget behavior on Galaxy Tab S2

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1337]
On Galaxy Tab S2 TM-813 running Android 7.0 the green widget will stop Adguard but not restart it. The standard black widget works but you can't add it to a group.

### Steps to reproduce

1. Launch Adguard
2. Disable the filtering by tapping the green widget
3. Tap it once again
4. It does nothing, according to the customer's report

### Expected behavior

Tap on a widget should enable the protection

### Actual behavior

It does nothing. 

### Your environment

* Adguard version: ?
* Adguard filtering mode: VPN / Proxy(manual/auto) ?
* Device model: Galaxy Tab S2 TM-813
* Operating system and version 7.0
* Rooted or not? ?
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

The customer refuses to send logs so we have to figure this out without it somehow.

**Comment by ameshkov** [comment]
No logs, no fix

**Comment by ameshkov** [comment]
@vozersky just in case, please check if it works properly on the test device

**Comment by vozersky** [comment]
can't reproduce
checked on both available Samsung devices, Galaxy s7 with 7.0 and old SM-T310 with 4.4.2, widgets work fine
