### ISSUE TITLE
BlackBerry KEYone issue: protection lost when clearing AdGuard from recent apps.

### ISSUE THREAD

**Issue by Wiredframe** [AdguardTeam/AdguardForAndroid#1338]
Since the latest beta clearing AdGuard from the recent apps screen turns off protection. Even when setting a notification icon. This just happened since the newest beta 2.9.136. Also auto start doesn't work anymore.

I'm on Android 7.1.1 BlackBerry KEYone.

Hope for a fix.

**Comment by ameshkov** [comment]
I am 99.99% sure this is not caused by the update as it is just a tiny hotfix and it has nothing to do with the app's lifecycle.

Recent notification issue sounds as if it was caused by the firmware, I've seen such cases before when swiping the app from the recent apps caused killing the app's process.

Anyway, I need to take a look at Adguard's log to tell you more. Could you please reproduce the issue and grab the log file?

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by Wiredframe** [comment]
It's definitely killing the app and yes, there was an OTA update yesterday :( Any idea how this could be fixed?

Thanks!

**Comment by Wiredframe** [comment]
I discovered that autostart after reboot indeed works and AdGuard will not be killed since AdGuard is not present in the recent apps screen. But as soon as I open AdGuard and then clear the recent apps it's being killed.

**Comment by ameshkov** [comment]
> PS. I sent you the log.

What's your customer ID? I need it to find the log

**Comment by ameshkov** [comment]
One more thing to try: settings -> advanced -> watchdog period, set it to 10 seconds. Adguard will monitor itself and restart if the process is killed for any reason.

Also, I guess it makes sense to report this issue to the manufacturer as this is not a normal behavior.

**Comment by Wiredframe** [comment]
Hi Andrey,

thanks again for reaching out to me, I am glad you want to help. But I really believe it’s an OS thing since the newest update from BlackBerry. Other apps show the same behaviour, like music apps that stop playback. That didn’t happen before.

I already tried what you’re guessing here, didn’t work.

Thanks

Ulf

Von: Andrey Meshkov [mailto:notifications@github.com]
Gesendet: Sonntag, 30. Juli 2017 22:44
An: AdguardTeam/AdguardForAndroid
Cc: Ulf Schuster; Author
Betreff: Re: [AdguardTeam/AdguardForAndroid] Protection lost when clearing AdGuard from recent apps. (#1338)


One more thing to try: settings -> advanced -> watchdog period, set it to 10 seconds. Adguard will monitor itself and restart if the process is killed for any reason.

Also, I guess it makes sense to report this issue to the manufacturer as this is not a normal behavior.

**Comment by ameshkov** [comment]
@Wiredframe got it, thank you!
