### ISSUE TITLE
Make the log stop scrolling when reading it

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1339]
Please also make a way so that when you scroll down from the top, the list pauses scrolling. So updates are above, but only scroll bar moves, and text remains static. Very frustrating reading updates / creating rules when it keeps moving.

**Comment by ameshkov** [comment]
@Revertron if it is easy to do, let's do it right away. If it's not, please re-assign it to v3.0

**Comment by Revertron** [comment]
By quick duckduckgoing (whooh) I've found a way, needs some testing.

**Comment by ameshkov** [comment]
@nkartyshov problems with the current implementation:

1. It does not auto-scroll AT ALL now. Staying in a top-position should be a special case.
2. Events count is no more limited (why so??)

**Comment by ameshkov** [comment]
@Revertron 
isn't it done already?

**Comment by Revertron** [comment]
Yep, it's done.
