### ISSUE TITLE
Make AdGuard to block ad with devices connected by tethering.

### ISSUE THREAD

**Issue by TetherAd** [AdguardTeam/AdguardForAndroid#1342]
Hi, Hope it will be clear, sorry english is not my native language.

I use adguard on a rooted phone, and enabled proxy mode filtrering.

I also added a HTTP proxy.

Using my phone, it's perfect, there no ad, and internet see my proxy ip, not my real ip provided by my carrier.

But when using tethering (wifi or usb), I expected my laptop to not show any ad, and to have internet via the proxy in adguard. But that not the case.

I assume this is normal with vpn mode because adguard is desactivated using tethering, but by proxy mode, it is normal ?

If yes, I think it would be a good feature for next release.

Thank you for this great app, keep up the good word !

**Comment by vozersky** [comment]
@TetherAd hey! It's not going to work this way, unfortunately.  For safety reasons, Android starts a separate network when you use tethering.
