### ISSUE TITLE
 $replace rule was applied to the page, other rules is not applied to the code

### ISSUE THREAD

**Issue by ilvjyw** [AdguardTeam/AdguardForAndroid#1343]
My environment
Adguard version: 2.9.135
Adguard filtering mode: VPN
Device model: Lenovo ZUK Z2
Android 6.0.1 rooted
!-----------------------------------
Please use Android or IOS user-agent access
website:http://m.baidu.com/
user rule:
baidu.com##[id^="tab_news"],#bottom
baidu.com$replace=/B.init/fuck/
if delete replace rule You can see the element hidden is OK!

**Comment by nkartyshov** [comment]
@ilvjyw Yes, it is bug in version 2.9.135. 
But will needs try reproduce this on next beta version.

**Comment by ilvjyw** [comment]
@nkartyshov 2.9.136 have the same bug

**Comment by ameshkov** [comment]
@ilvjyw resolved in the latest beta version
