### ISSUE TITLE
Consider adding a redirection feature

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1344]
Would you consider adding a redirection feature equivalent to 'www.example.com 123.456.79763' in the hosts file? It exists in Adaway but requires root.
In some countries, websites are blocked/redirected based on DNS query

The use case:

> Let's say I want to reach abc.def.com[http://abc.def.com]
> When I want to access that website the DNS response to my device is faked,  and I'm directed to an advert instead (long story short,  the ISP injects adverts/warnings on some websites )Google dns is unfortunately banned too,  so i have to use the dns server my isp provides. 
I used the hosts file to overcome this issue in the past. 
The phone used the address in the /etc/hosts file and never queried the dns server.

**Comment by ameshkov** [comment]
> In some countries, websites are blocked/redirected based on DNS query

Using DNSCrypt would solve the issue.

Redirecting via hosts file is still possible, it is not an adaway feature, you can use it along with AG no prob
