### ISSUE TITLE
Resolve .onion domains when Tor integration is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1346]
We can pass traffic through Orbot's proxy, but .onion domains are still unusable.

Possible solution: intercept DNS requests, resolve .onion domains to a private IP and pass .onion domain to SOCKS or HTTPS proxy instead of that private IP.

**Comment by ameshkov** [comment]
Needs to be checked with new CoreLibs that supports sending UDP over SOCKS5

**Comment by sfionov** [comment]
Feature request is created in CoreLibs repo:
https://github.com/AdguardTeam/CoreLibs/issues/1386

**Comment by pedroapero** [comment]
Note: it looks like CloudFlare is now hosting a DOH onion service: https://blog.cloudflare.com/welcome-hidden-resolver/
Might be suitable for Tor integration also.
