### ISSUE TITLE
Add `Код Доступа Mail.Ru` app to HTTPS exceptions

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1347]
https://play.google.com/store/apps/details?id=ru.mail.auth.totp - `ru.mail.auth.totp`

This app is used to run two-factor authentication.

**Comment by ameshkov** [comment]
Same for Google Authenticator I guess

**Comment by nkartyshov** [comment]
added

**Comment by Alex-302** [comment]
The similar app:
https://play.google.com/store/apps/details?id=com.authy.authy&hl=ru
Please exclude it.

**Comment by ameshkov** [comment]
What about Google Authenticator?

**Comment by nkartyshov** [comment]
@ameshkov I excluded Google Authenticator from https filtering

**Comment by nkartyshov** [comment]
@Alex-302 done
