### ISSUE TITLE
Deleting a single rule from a search result removes all rules from the User Filter

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1348]
### Steps to reproduce

1. Add rules `aaa` and `bbb` to the User Filter
2. Search for rule `bbb`
3. Tap on the rule from a search result and delete it

### Expected behavior
Deleting a single rule will delete only one rule that tapped

### Actual behavior
Deleting a single rule from a search result removes all rules from the User Filter

<details><summary>Screenshot:</summary>

![screenshot_20170728-151735](https://user-images.githubusercontent.com/28726429/28716864-10a64ca2-73a8-11e7-88f9-77ef9054fded.png)

</details>

### Your environment

* Adguard version: 2.9.136
* Adguard filtering mode: VPN
* Device model: Nexus 5X
* Android 7.1.2
* Not rooted
* No other apps installed

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-61
