### ISSUE TITLE
filter wont block

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#1349]
im trying to use this rule to block all .bid domains and it doesnt work

||www.*.bid$app=com.adguard.dns

**Comment by ameshkov** [comment]
Do you have DNS filtering enabled?
Does it help to remove the `app` modifier?

**Comment by jo2dan23** [comment]
yes dns filtering is enabled. and no i tried without the apl modifier also. sorry should have mentioned that

**Comment by jo2dan23** [comment]
on latest version also. should have included that in title

**Comment by ameshkov** [comment]
I am not sure about `www`, try without it:
```
||*.bid$app=com.adguard.dns
```

**Comment by jo2dan23** [comment]
didnt work

**Comment by TPS** [comment]
@jo2dan23 I use `.bid^$important`.…  Does _that_ help?
