### ISSUE TITLE
Test Adguard and My JDownloader

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#135]
From xda:
> i have only one question: is possible to use app like myjdownloader when adguard is active?
> i tried using both the vpn or the http mode (i have samsung g4 with root), but even changing the port address in http, the app doesn't communicate with the myjdownloader server anymore.

http://forum.xda-developers.com/showpost.php?p=63475934&postcount=318

**Comment by gshumihin** [comment]
My jdownloader can't connect to its own server while adguard is active.

**Comment by gshumihin** [comment]
Here is log:
https://www.dropbox.com/s/etwh6kv9i5twkow/adguard.log

**Comment by Revertron** [comment]
It is making a series of requests like this:
```
POST /my/listdevices?sessiontoken=bccadb93c1a428fba5f396d262da4c701a22725d&rid=1446212275912&signature=38a2190ff3229893a26b364815316bed5110b2e9480a515194f6651f141692dd HTTP/1.1
Content-Length: 0
Host: api.jdownloader.org
Accept-Encoding: gazeisp
User-Agent: MyJDownloader Android App (Version: 0.8.39 Build 20151028 / playstore) (Android 5.1; samsung / SM-G920F)
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
```
The Accept-Encoding header is using some weird encoding type: gazeisp. We are getting the response like this:
```
HTTP/1.1 200 OK
Server: AppWork GmbH NIO-Engine
Access-Control-Allow-Origin: *
Transfer-Encoding: chunked
Content-Type: application/aesjson-server; charset=utf-8
Connection: close
```
And giving response like this to the client:
```
HTTP/1.1 200 OK
Server: AppWork GmbH NIO-Engine
Access-Control-Allow-Origin: *
X-Adguard-Filtered: Adguard for Android 1.0
Transfer-Encoding: chunked
Content-Type: application/aesjson-server; charset=utf-8
Connection: close
```
The jdownloader doesn't like the response from us, but I don't know why yet.

**Comment by Revertron** [comment]
Will test with adding it to network exclusion list tomorrow.

**Comment by gshumihin** [comment]
With My Jdownloader exluded from filtration everything works fine. 
Hopefully, we'll release next beta version this monday :)
