### ISSUE TITLE
full path for urls doesnt show in log for certain apps

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#1350]
if i open up youtube on Android 6.0 it shows the full path of all the urls the YouTube app is trying to reach. on 7.0 all it shows is the domain. and there is not the same amount of requests from the YouTube app itself on 7.0 mostly  dns.. ishis a bug on 7.0 or adguard?

**Comment by Revertron** [comment]
May be, you've enabled DNS filtering on the device with 7.0?

**Comment by jo2dan23** [comment]
yeah I have but dns filtering is enabled on the 6.0 one too

**Comment by jo2dan23** [comment]
i just tried disabling it. nothing changed

**Comment by jo2dan23** [comment]
another example is when i click on a item in ebay and scroll to bottom there is sponsored ads by google.  i cannot block those on 7.0 but on 6.0 it shows me what specific url is hosting the ads. hopefully someome understands what im trying to explain. @ameshkov

**Comment by ameshkov** [comment]
I guess you're talking about HTTPS requests.

The problem is that not every request can be decrypted due to this:
https://blog.adguard.com/en/android-nougat-release-and-what-does-it-mean-for-adguard-users/

**Comment by jo2dan23** [comment]
but that should.mean https filtering should be disabled then for ebay app doesnt it? because it says it automatically disables apps designed for android n.

**Comment by jo2dan23** [comment]
it still lets me block https requests in ebay app meaning https filtering isn't disabled for it. so maybe its an adguard bug that doesnt detect its made for 7.0?

**Comment by ameshkov** [comment]
> mean https filtering should be automatically disabled then for ebay app on 7.0 doesnt it?

IF ebay app targets SDK level 24 or newer.

Also, it is still able to detect the target domain, it just cannot decrypt it.

**Comment by ameshkov** [comment]
Examine the "event type" field. HTTPS Tunnel means that there's no HTTPS filtering, just using the domain name. Web request means that it's decrypted.
