### ISSUE TITLE
Open AdGuard by long-pressing on the tile icon

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1351]
Just like you can open Wi-Fi settings by long-pressing on the Wi-Fi toggle.

The same should work for the Oubound Proxy toggle -- long-pressing should bring up the outbound proxy settings.

**Comment by fazlee712** [comment]
There are a lot of apps that let you make custom tiles to do any action you want on tap/long tap/double tap, etc. Is it not possible to do a similar thing here?

**Comment by Revertron** [comment]
https://developer.android.com/reference/android/service/quicksettings/TileService.html#ACTION_QS_TILE_PREFERENCES

The doc says that in Android O we may get the ComponentName that "caused the preferences to be opened", but as always in products of Google - we get a ComponentName that points to the Activity that is started (but we know what activity we are in!). It can not indicate what tile exactly was long-tapped.

And, there is no way to set two different Activities to wait for long taps from different tiles. I've tried, but they just do not work. May be Android is going mad in that case.
