### ISSUE TITLE
Controlling Adguard from keyboard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1352]
Here is the issue description:
https://forum.adguard.com/index.php?threads/android-tv.6428/page-2#post-145980

It's hard to control AG from the keyboard - no elements highlighting and such.

We can test it with Bluetooth keyboard or with an emulator (which one?).

@vozersky could you please emulate it somehow?

**Comment by arc909** [comment]
I have a Sony Bravia TV (KD-65X8500E) with Android TV (Android 7, Kernel 3.10.79, build BRAVIA_ATV2_PA-user 7.0 NRD91N.S42 1.6.0.25.08.1.00 release keys).

I have a lifetime subscription of Adguard for Android for my S8+ & happy to help with testing to get Adguard working on Android TV.

**Comment by ameshkov** [comment]
Duplicates #2611
