### ISSUE TITLE
Open links in a webview

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1355]
Instead of opening a web browser, we should open links in a webview.

Just like Gmail or Telegram does (with an option to open it in a browser).

**Comment by TPS** [comment]
Actually,  that's pretty much what most of the browsers on your list do, too.  Does this mean AG will have to be added there, too?

**Comment by Revertron** [comment]
No.

**Comment by ameshkov** [comment]
Talking about links inside of the app. Instead of offering to open a browser, we should open them in a webview. Like what's done by Gmail app when you click a link there.

**Comment by Revertron** [comment]
Done. Merged.
