### ISSUE TITLE
[Feature request] - Blocking ads only during cellular connection

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardForAndroid#1359]
The user suggested the app to have ad blocking while using cellular and no ad blocking while using wifi. 

> In apps management, I can only let the app access de internet via cellular or wifi. Or I can turn ad blocking on/off.

Ticket ID:1464042

**Comment by ameshkov** [comment]
Why does he need such a feature? Sounds rather odd

**Comment by wandererme** [comment]
Some games let you advance faster if you allow them to show you ads (short videos). 
If you play any of these games it might be useful to turn ad blocking off, however, they do tend to use too much data, so it would be useful for the ad blocking be off only while using the data plan. When using wifi there is no data limit (usually) so it's ok to download those video ads.

**Comment by vozersky** [comment]
let's keep it as a feature request for now

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
