### ISSUE TITLE
Add more detailed description about Filtering method

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#136]
It is not quite clear what's the difference between Simplified, High-speed and High-quality.
At least we could add the description to faq.

**Comment by Revertron** [comment]
Done. Made it as hints in dialog.

**Comment by TPS** [comment]
I would actually like a more detailed explanation than the hints in the dialog. Is it in the FAQ with more detail?

**Comment by ameshkov** [comment]
We're working on a knowledge base now, it will be described in detail there.
