### ISSUE TITLE
Portuguese translation update

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#1360]
### Expected behavior

Correct tranlation in English: `Protection is enabled`

### Actual behavior

Incorrect translation in Portuguese: `Proteção|Ativado` in Brasil and `A protecção esta|ativada` in Portugal locals (Adding a space in place of | would be a correction).

### Customer ID - 1608471

**Comment by ameshkov** [comment]
@vbagirov could you please take a look?

**Comment by vbagirov** [comment]
@Bohdan-SUP fixed. The translators missed the space before the phrase.
