### ISSUE TITLE
Add Simple Bank app to HTTPS exclusions

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#1361]
The Simple Bank app (com.banksimple) does not allow sign-in when HTTPS
filtering is enabled. 

Link to the app: https://play.google.com/store/apps/details?id=com.banksimple&hl=en
Filters: 2, 3, 4, 14, 11 
Version: 2.9.136
HTTPS is on

Ticket ID: 1403048

**Comment by nkartyshov** [comment]
excluded
