### ISSUE TITLE
Site detect I'm using an adblocker and I can't see the content inside

### ISSUE THREAD

**Issue by Snake87r** [AdguardTeam/AdguardForAndroid#1362]
When visiting this site:
http://www.kuronotranslations.com

I receive the message "It looks like you're using an ad blocker" and I have to disable adguard to see the site (they use this script to block adguard https://blockadblock.com/blockadblock_basic_script.php)

When visiting this other site:
https://lesyt.xyz/post/376

I receive this message: "Adblock detected!", I can see the content but they see i use Adblock and spamming to become a pro user and pay..
I think they use this script https://blockadblock.com/blockadblock_basic_script.php

### Your environment
* Adguard version: 2.9.136
* Adguard filtering mode: VPN
* Device model: Sony Xperia Z4 Tablet
* Operating system and version (e.g. Android 7.0)
* Not Rooted

**Comment by vozersky** [comment]
@Snake87r have you tried our Annoyances filter?

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #6062](https://github.com/AdguardTeam/AdguardFilters/issues/6062) via [**ZenHub**](https://www.zenhub.com/)
