### ISSUE TITLE
Additional firewall options - traffic limiter

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1363]
User asked to implement an option to throttle bandwidth per app while on cellular data. To set a limit for apps that are mainly used on Wi-Fi, but you want to be able to use them on cellular data without eating up all traffic.

Also, a user asked about being able to see how many traffic an app is using while on a cellular network and a separate Wi-Fi section.

**Comment by ameshkov** [comment]
Duplicate of #3226 #3227
