### ISSUE TITLE
Sometimes Google search is blocked with Adguard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1364]
It seems the issue is rare.

### Steps to reproduce

1. Try to search something on google.com

### Expected behavior
Search is successful.

### Actual behavior
User is banned by Google, until protection is enabled.
#### The same issue with Adguard for Windows.
![image](http://imagizer.imageshack.com/img922/571/hXahbR.png)

### Your environment

* Adguard version: 2.10.9b
* Adguard filtering mode: VPN
* Operating system and version: 5.11
* Rooted
* All filters and DNS are disabled.

[Full log + tun.pcap](https://github.com/AdguardTeam/AdguardForAndroid/files/1212674/logs.zip)
Video:
https://mega.nz/#!hUlRnKTR!LkLrWXmUsXgMtTPmbvpzrJmWOIGM9hL6Dps468BYwHU

**Comment by Revertron** [comment]
The IP was your real? Not some sort of proxy, or Tor?

**Comment by Alex-302** [comment]
IP is real. When the issue starts, it can be fixed only by turning off protection.

**Comment by ameshkov** [comment]
It is almost impossible to fix, the issue is not on our side:(
