### ISSUE TITLE
Incorrect message when checking proxy (2.10.10b)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1365]
### Steps to reproduce

1. Check proxy

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://slack-imgs.com/?c=1&url=http%3A%2F%2Fimagizer.imageshack.com%2Fimg922%2F8964%2F7dfwDw.png)

</details>

**Comment by Revertron** [comment]
Fixed. Removed dialog title, as we show some other dialogs without it.
