### ISSUE TITLE
Side menu "Settings" button doesn't work at the second level of the section

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1366]
This is a quite annoying issue:

### Steps to reproduce

1. Go to "settings" -> "general"
2. Open the side menu and press "settings"

### Expected behavior
Main settings window is opened (1 step back)

### Actual behavior
Nothing happens

**Comment by Revertron** [comment]
General or any other section must have <- back button, not the Hamburger menu.

**Comment by ameshkov** [comment]
> General or any other section must have <- back button, not the Hamburger menu.

As I understand, it won't work with the current implementation (will work in v3.0)

**Comment by Revertron** [comment]
It may be complicated with our fragments implementation now, but I think it's doable.

**Comment by vozersky** [comment]
Also, related scenario:

1. Go to "settings" -> "general"
2. Open the side menu and press "filtering log"
3. Open the side menu and press "settings"

Expected behavior:
You are taken to the main settings window.

Actual behavior:
You are taken back to the second level section ( in this case: "settings" -> "general")

**Comment by ameshkov** [comment]
> It may be complicated with our fragments implementation now, but I think it's doable.

I suppose that we'd better implement the easiest thing (getting back to settings via side-bar menu) and leave the normal navigation for v3.0

**Comment by nkartyshov** [comment]
fixed
