### ISSUE TITLE
Extended search in the filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1369]
Allow to filter log records by:
- package name;
- whitelisted(сonsider package name, if check-box is selected);
- blocked(сonsider package name, if check-box is selected);
- third-party.

**Comment by nkartyshov** [comment]
done

**Comment by karina-archazh** [comment]
Could you please specify about third-party option?
Is it available when disabling the first two in the dialog box?

**Comment by karina-archazh** [comment]
Also fix the header buttons - they should always be displayed.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA: 
-Reinstall AG
-Examine new filtering in the filtering log (There are 2 more search options: Third/First-party requests. Modified, Blocked and Removed elements are wrapped in the "Blocked or Modified" option)

**Comment by Alex-302** [comment]
`Blocked and modified requests` filter is inconvenient, because when you try to find non-blocked requests and enable this filter, modified requests are also hidden, but they can be an ad or something other you want to block.
Better make just `Blocked requests` or `Blocked requests`+`Modified requests` filters.

**Comment by ameshkov** [comment]
Added a new feature request: https://github.com/AdguardTeam/AdguardForAndroid/issues/2623
