### ISSUE TITLE
Adguard doesn't respond when protection is restarting in root-proxy mode

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1370]
### Steps to reproduce

1. apply any new settings, which cause protection restart
2. press 'back' button to go to main screen of Adguard app

### Expected behavior

Protection restarts after applying new settings
### Actual behavior

Adguard hangs for a while and sometimes you get  OS message 'Application doesn't respond'

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 2.10.12b
* Adguard filtering mode: root proxy
* Device model: nexus
* Operating system and version Android 5, android 7
* Rooted or not? root

[debug (2).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1222571/debug.2.txt.zip)

**Comment by Revertron** [comment]
Fixed.
