### ISSUE TITLE
Displaced titles in the 'Statistics' tab of the 'DNS' screen

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1371]
### Actual behavior

<details><summary>Screenshot:</summary>

![screenshot_2017-08-14-19-07-59](https://user-images.githubusercontent.com/23637588/29280604-88db9b1c-8124-11e7-8249-2f612e965be5.png)

</details>

Adguard beta 2.10.12

The problem exists in different translations.

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-76
