### ISSUE TITLE
Blocks messaging in OK app with HTTPS filtering ON

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1372]
### Steps to reproduce

1. Turn off all filters
2. Enable HTTPS filtering
3. Proceed to the Messaging

### Expected behavior
Messaging works with no issues

### Actual behavior
You can't reach Messaging. Infinite loading.

<details><summary>Screenshot:</summary>

![2017-08-15 16 36 49](https://user-images.githubusercontent.com/28726429/29318243-ed2a140a-81d7-11e7-900a-c17eeefa0fc2.jpg)
</details>

### Customer ID 
1604579

### Your environment

* Adguard version: 2.9.136
* Adguard filtering mode: VPN
* Device model: Nexus 5
* Android 5.1.1
* HTTPS filtering enabled

**Comment by Revertron** [comment]
It seems that something is not in tact with HTTPS in OK app. We need to investigate, find problematic domain and whitelist it if possible.

**Comment by altokarev** [comment]
I've got a log (18:34): [debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1225185/debug.txt)

**Comment by nkartyshov** [comment]
Can you try reproduce this in last beta version?
I think it's worth trying to add a domain `api.ok.ru` in https whilte list

**Comment by altokarev** [comment]
Have notified the customer. Thanks!

**Comment by ameshkov** [comment]
@altokarev did it help?

**Comment by altokarev** [comment]
The latest beta didn't help.

We're trying to add `api.ok.ru` to the exceptions, but user told us that exceptions window is restricted to edit. That's weird. Still investigating an issue.

**Comment by nkartyshov** [comment]
I was mistake in domain name, need add domain `tamtam.chat` in https whitelist

**Comment by altokarev** [comment]
Thanks!

But the user has some difficulties with adding domains to HTTPS exceptions. He'll wait for our next beta with such exception inside.

**Comment by nkartyshov** [comment]
Added in whitelist AdguardTeam/HttpsExclusions@ded7e3d

**Comment by altokarev** [comment]
The problem is still here. Ticket ID 1030934.

**Comment by ameshkov** [comment]
OK added to the https exclusions list
