### ISSUE TITLE
No internet connection when DNScrypt  and 'record everything' logging level are enabled

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1375]
### Steps to reproduce

1. Turn on Record everything logging level in Advanced settings
2. Turn on  Adguard DNS 
3. Set up any custom DNScrypt server

### Expected behavior

There is internet connection in all apps
### Actual behavior

No internet connection at all.

### Your environment

* Adguard version: 2.10.16 beta
* Adguard filtering mode: Proxy(auto)
* Reproducible on android 7
* Rooted

**Comment by nkartyshov** [comment]
Fixed, review AFA-CR-78
