### ISSUE TITLE
The Onion (theonion.com) does not work with Adguard enabled

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1379]
### Steps to reproduce

1. Open Chrome Incognito (to make sure there's no cache interfering) (Adguard disabled)
2. Go to theonion.com
3. Page loads just fine
4. Enable Adguard
5. Pull to refresh
6. "Please upgrade your browser" error message

### Expected behavior

Ads on The Onion should be blocked.

### Actual behavior

Site does not work at all.

<details><summary>Screenshot:</summary>

![screenshot_20170816-131222](https://user-images.githubusercontent.com/29067983/29378505-f40e83ac-8284-11e7-896a-8383a2ebec65.png)
![screenshot_20170816-131240](https://user-images.githubusercontent.com/29067983/29378506-f410c9dc-8284-11e7-9c3e-964cfbed6a2e.png)

</details>

### Your environment

* Adguard version: 2.9.136
* Adguard filtering mode: VPN / Proxy(manual/auto) VPN with HTTPS cert installed to System
* Device model: (e.g. Google Pixel) Pixel XL
* Operating system and version (e.g. Android 7.1.2) 7.1.2
* Rooted or not? Yes, not using rooted features besides installing cert
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Just Google Connectivity Services, which is disabled

Here's the log with full logging enabled: 

https://my.pcloud.com/publink/show?code=XZvdjoZzSGg1MdMxsuRQGtKVb1a8hKHiPIk

**Comment by zebrum** [comment]
can not reproduce on latest beta, but the issue reproducible on 2.9.136 even if no filters are enabled. 
checked with chrome, firefox and opera.

**Comment by zebrum** [comment]
@carlylemiii please update to the latest beta via beta channel in Settings - Advanced.

**Comment by carlylemiii** [comment]
@zebrum Not sure if it was maybe fixed for a short time, but this is an issue on 2.10.56 beta. Please re-open.

**Comment by nkartyshov** [comment]
Fixed. The site was broken, because AdGuard injected content script in comments.
