### ISSUE TITLE
Tethering/hotspot is falsely detected (MIUI, Zenfone2)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#138]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=43988533

https://www.youtube.com/watch?v=KXmUG37KpAo&feature=youtu.be

From 4pda:
> Когда выключаю Передачу данных (на ночь), то Adguard ругался, что я включил Режим модема и фильтрации не будет (причем это уведомление появляется 2 раза подряд, примерно через 15-20 секунд, после выключения передачи данных), утром включаю Передачу данных, и опять выскакивает это уведомление. Вручную захожу в adguard и перезапускаю Защиту.

**Comment by vbagirov** [comment]
Also happens with WiFi enabling/disabling.

**Comment by justinliao7928** [comment]
Same bug happened on ASUS Zenfone2 (ZE551ML) with WiFi enabling/disabling.

**Comment by ameshkov** [comment]
@justinliao7928 hi! could you please collect logs for us to analyze this issue?

The problem is that current stable version does not print enough information to the log file, so you'd better use another build:
http://static.adguard.com/android/release/adguard_issue154.apk

Steps to collect logs:
1. Install the apk linked above
2. Reproduce the issue with tethering/hotspot notification
3. Go to Adguard - Menu - Send Feedback
4. Post here the ticket ID you'll get in an autoreply email

**Comment by justinliao7928** [comment]
Hello,

Here's the detailed steps that I proceeded.

1. Uninstall old ADG ( 2.1.267 RC)
2. Install provided special apk file and enter my key
3. Reboot to make local VPN filter working
4. Turn on ADG protection and set log level to "Record Everything"
5. Reproduce the issue with notification by cycling WiFi toggle or Mobile
data toggle several times.
(lots of notifications! lol)
6. Send feedback (and I received a ticket ID)

*Ticket ID: *CWI-235-88722

Thanks. :)


2015-11-09 21:34 GMT+08:00 Andrey Meshkov <notifications@github.com>:

**Comment by vbagirov** [comment]
More logs: KQD-119-73569

**Comment by vbagirov** [comment]
More relevant tickets: WTC-489-23087

**Comment by Bohdan-SUP** [comment]
More logs:
XQA-863-55686

**Comment by ameshkov** [comment]
In case of MIUI the problem is that it always has a USB network interface with IPv4 interface:
```
usbnet0 (usbnet0) [usbnet0][5][/10.0.2.15] isUp = false
```

But anyway, we should not detect that because that interface is not active.

**Comment by vbagirov** [comment]
This user still encounters the same problem even with 2.1.319 version: OFS-517-32825

**Comment by justinliao7928** [comment]
More log #GWB-888-76064 (Zenfone2)

![p_20151212_024105](https://cloud.githubusercontent.com/assets/5909288/11752342/0a2a872e-a07a-11e5-93ef-0532aab5524b.jpg)

**Comment by vbagirov** [comment]
New ticket ID for Zenfone 2 problem: QLH-799-60348

**Comment by ameshkov** [comment]
Fixed this.

We should not detect tethering for "usbX" network interfaces.
The only netif we are interested in is "rndis0".

**Comment by ameshkov** [comment]
@justinliao7928 could you please check it in the latest beta? Is it good now?

**Comment by justinliao7928** [comment]
Tried new 2.1.338.
It's gooooooood!!!

**Comment by ameshkov** [comment]
Finally:) Thank you for checking it @justinliao7928 !
