### ISSUE TITLE
Add Allow / Deny / Notify option to firewall / apps management section

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1386]
ADGUARD works differently to all other firewalls. Rather than Allow / Deny / Notify, it is geared to only deny. So you allow an app, it connects, then you enable filtering, you must now watch it closely and block bad connections.

Instead, there needs to be a way to NOT allow all, and get requests in filtering log > rejected log > and here choose which application connections are authorised. E.g. Allow GMAIL :443 *.1e100.net
All other connections are blocked.
Or: Allow GMAIL : 443 *
All connections to https are now permitted.

Rather than 10001 being allowed by default with "Allow All" (default) for
when fixing "Allow" button.

Make sense?
Allow = allow all
Deny = deny all
Notify/Prompt = reject all connections until rule is added to accept
connection to x.x.x.x:53 or :80 :8080 :443 :5353 :1900 etc....
So x.x.x.x equals any server: - mail.example.com:143,25,110,995,993
All other connections will be rejected, UNTIL or UNLESS, a rule is created with them.

So instead of BLOCK only button in a filter, you need the second filter for all Notify/Prompt apps and have "ALLOW..." button to customise the rule for permitted connections.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
