### ISSUE TITLE
Remember search/filter selection and scroll location

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1387]
When searching and click on an app from results, please Remember search/filter selection and scroll location, so resumes to the same place. Otherwise, you must then search again, scroll, scroll, scroll.

SRT:
1. Click on really, go into app's firewall/filtering
settings 
2. Then go back. Search results lost! 

If I search Play, then it should resume to the last place. Just like proposed log searching feature, or
filter apps by..., filter log by..., etc.

**Comment by vozersky** [comment]
merged into #3379
