### ISSUE TITLE
Add a low-level setting to override system DNS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#139]
Name: **pref.vpn.dns**
Default value: empty
Allows to set a number of DNS servers (separated by a coma).

**Comment by TPS** [comment]
Yes, _please_!   Can this (hopefully) be extended to proxy, also?

**Comment by ameshkov** [comment]
Ops, it looks like the #117 is a duplicate now, I'll close it.

**Comment by ameshkov** [comment]
> Can this (hopefully) be extended to proxy, also?

Nah, upstream proxy is a bit different thing. It's good that you've reminded me about it. With low-level settings section it is rather and fast simple to add it as we don't need to spend time on messing with UI:)

**Comment by vbagirov** [comment]
Relevant ticket: CJW-173-81900

Adguard doesn't work with a particular WiFi network, unless DNS filtering is enabled manually.
'About phone' screenshots: 
http://screencast.com/t/XFSDTBoScR
http://screencast.com/t/XFSDTBoScR

**Comment by ameshkov** [comment]
@vbagirov looks like a different issue to me. Please file a new bug report.

**Comment by vbagirov** [comment]
@ameshkov new bug report is filed: #174

**Comment by TPS** [comment]
> Nah, upstream proxy is a bit different thing

@ameshkov I just re-read [that](#issuecomment-152300632), & realized I was possibly misunderstood.  I think you thought I was referring to #51, but what I _actually_ meant that, since the _name_ of the option is __`pref.vpn.dns`__, it seems likely it's a VPN-*only* option.…  Will it possible to use with AG proxy-mode, for those who don't/can't use VPN?

**Comment by ameshkov** [comment]
> Will it possible to use with AG proxy-mode, for those who don't/can't use VPN?

No, there's no easy way to do it in proxy mode.

> Also, will we able to setup separate IPv4 & IPv6 DNS servers?

Why could you possible need this?

**Comment by TPS** [comment]
In the Windows systems I'm used to, IPv4 & IPv6 DNS is setup separately, &, if 1 is left out, it defaults to the *connection*'s default for that protocol — it won't attempt to route the request to the otherwise-configured DNS server.  Is this not the same under Android?

**Comment by ameshkov** [comment]
But that's not IPv4/v6 DNS, it is just primary and secondary DNS server.

**Comment by TPS** [comment]
In Windows, IPv4 & IPv6 _each_ have separate configuration with an arbitration number (_not_ just primary & secondary) of DNS servers.  Typically, shouldn't AG need to be _told_ which DNS servers can handle IPv4 or IPv6?  Or will any requests sent to each server in the list until an answer received?

**Comment by ameshkov** [comment]
> Typically, shouldn't AG need to be told which DNS servers can handle IPv4 or IPv6?

You don't know which address the host has.It is DNS server who tells you:)

**Comment by TPS** [comment]
:bulb: So, it's all unified in Android! NM, then, except, that we'll be able to provide either/both IPv4 & IPv6 addresses for this pref?

**Comment by ameshkov** [comment]
> So, it's all unified in Android!

No, why, it is unified everywhere. I guess in Windows they've divided settings into IPv4&IPv6 for some UX purposes. In our case it just won't be separated.

**Comment by TPS** [comment]
In Windows, apparently, there's been separate IPv4 & IPv6 stacks (enabled/installed individually, even), with their own settings, which DNS falls under.

**Comment by TPS** [comment]
>It is DNS server who tells you:)

I suppose that's true for AG, because you all may have coded it that way, but I think the complete answer is a bit more involved.  I understood it to be more like explained @ https://superuser.com/questions/403716/how-do-client-applications-know-to-use-ipv4-or-ipv6 so does the underlying Android OS influence this in anyway?

**Comment by ameshkov** [comment]
@TPS 
> I understood it to be more like explained

The explanation is the same: OS does a DNS request, requesting both A and AAAA records and depending on the response it uses either IPv4 or IPv6. It does not depend on the DNS host address.

**Comment by Revertron** [comment]
I made it!
Set DNS line by line, as other lists.
