### ISSUE TITLE
Adguard does not resume protection occasionally

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1393]
More info & user reports here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1358

**Testing instructions:**

For Nougat+: install another VPN-based app, enable it, check that AG protection is paused. Wait a bit, then disable that VPN, check that AG protection is restarted.

For older devices: the same case + check that AG is paused/resumed properly when there is no network access.

**Comment by veronikasav** [comment]
> У меня при включенной программе в фоновом режиме отключается интернет,а программа становится на паузу.
При отключении программы, интернет "летает".
Да, ещё, когда обратно включаю программу и работаю с смартфоном все нормально. Но когда отложу телефон минут на десять появляется сообщение "интернет не доступен".

[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1253985/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1253986/state.txt)

Ticket ID: 1554258

**Comment by TPS** [comment]
I've had this happen, too, in spite of the watchdog/safeguard service, but mostly only notice it when my external Tasker-like app restarts AG unexpectedly. 🤷

**Comment by veronikasav** [comment]
I connected wifi adblock working well. But it doesn't work when I use
mobile data(celluar).

[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1259570/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1259569/state.txt)

**Comment by ameshkov** [comment]
@veronikasav 

> 1554258
Has nothing to do with this task. Might be the known issue with Redmi settings (should whitelist AG there).

> 1620465
Also has nothing to do with this issue. Seems to be related to this:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1026

**Comment by ameshkov** [comment]
Fixed in pull-requests/21

We returned receiver registration to the app manifest, but it will be used on older Android versions only. For Android N+ we use dynamically registered receiver only.
