### ISSUE TITLE
French translation update

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#1397]
Incorrect translation in French: there should be a space between "est" and "désactivé"

<details>

![image](https://user-images.githubusercontent.com/14153331/29609556-45ad6784-8800-11e7-9a90-21be286b11bf.png)

</details>

Customer ID - 1450588

**Comment by ameshkov** [comment]
@vbagirov 
please assist

**Comment by vbagirov** [comment]
Fixed in OneSky.

**Comment by vbagirov** [comment]
And the whole French translation has been updated.
