### ISSUE TITLE
When AG revoked by another VPN, we should periodically check if we can start it back

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1399]
Otherwise, we're getting stuck in the "paused" state

**Comment by ameshkov** [comment]
This may cause unreliable behavior when the user disconnects AG manually. Should think more about it.

**Comment by Bluscream** [comment]
Or when the protection was ended through a service call ^

**Comment by ameshkov** [comment]
Hm, it's done in the prev builds
