### ISSUE TITLE
Bixby app - HTTPS filtering compatibility

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1400]
http://www.samsung.com/global/galaxy/apps/bixby/voice/

When Adguard is filtering the traffic of Bixby Voice, Bixby doesn't work when I am holding Bixby button to talk to her. It says that there is a connection problem. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29663199-b68aebc0-88d2-11e7-9610-bd2f1b8111ae.png)

![image](https://user-images.githubusercontent.com/15856304/29663214-c30cb09a-88d2-11e7-880b-005e6c1274e6.png)

</details>

### Your environment

* Adguard version: 2.9
* Adguard filtering mode: VPN
* Device model: Samsung SM-G955F
* Operating system and version 7.0
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? None

**Comment by ameshkov** [comment]
Yay, we found somebody who actually uses Bixby!

**Comment by nkartyshov** [comment]
@evgeniy-ADG Can you ask user about package name for Bixby app?

**Comment by ameshkov** [comment]
@nkartyshov 
why? just check the test Galaxy device we have

**Comment by nkartyshov** [comment]
@ameshkov Because We haven't Bixby on S7.
And we have problems with installing Bixby on samsung S7

**Comment by evgeniy-ADG** [comment]
We have another customer who uses it. The package names which I found in state are:

com.samsung.android.bixby.agent
com.samsung.android.bixby.es.globalaction
com.samsung.android.bixby.agent.dummy 
com.samsung.android.bixby.voiceinput 
com.samsung.android.bixby.plmsync; 
com.samsung.android.bixby.wakeup

Have asked, will update as soon as I hear back.

**Comment by evgeniy-ADG** [comment]
Nope, it's the same customer but from the different email.

>. I found that if i whitellist /disable HTTPS Bixby, the phone starts to get very unresponsive /laggy . This laggy /unresponsive behavior is at times unpredictable. /intermittent  /on and off.? One moment  device is  lagging andsuddenly it starts getting smoother just to get laggy again...! 

Can it be because that Bixby has multiple packages which we cannot whitelist from the Apps management section?

**Comment by nkartyshov** [comment]
Added all package names for Bixby app

@evgeniy-ADG No, we show all installed applications. It is possible that the user excludes only one package name from six.
