### ISSUE TITLE
"Request trial" should require an email

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1401]
1. When a user clicks "Request trial", we should show an alert dialog asking him to enter the email address.
2. The dialog should also explain, that this email will be used to create the AG personal account so that he could manage AG license keys.
3. Save this email in preferences and autofill email field into the "Send Feedback" form.
4. We should also use the same field to save the email entered into the "Send Feedback" form.
5. Preference should not be "exportable"

@Dariamag need strings from you.

**Draft:**
Title: Request trial

Input (email). Validate the entered email.
Text: The email will be used to create the AdGuard personal account so that you could manage your devices and licenses.

Button1: OK
Button2: Cancel

**Comment by Dariamag** [comment]
@ameshkov Title: Request trial
Enter your email address 
Check the entered email
The email will be used to activate trial version and register the personal account where you can manage your AdGuard keys and subscriptions.

Activate
Cancel

**Comment by carlylemiii** [comment]
Suggestion for more standard English:

"**This** email will be used to activate **a** trial version and register **a** personal account where you can manage your Ad**g**uard **license** keys and subscriptions.

**Comment by ameshkov** [comment]
@carlylemiii 

> Adguard

We decided to use AdGuard as a brand name everywhere after all.

**Comment by Revertron** [comment]
Done.

**Comment by zebrum** [comment]
`autofill email field into the "Send Feedback" form` doesn't work in latest beta 2.10.51

**Comment by Revertron** [comment]
Fixed.
