### ISSUE TITLE
Minor grammar error in DNS/Proxy Settings on latest beta (2.10.16)

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1402]
Domain Name Servers (DNS) are the ~~Internets~~ **internet's** equivalent of a phone book.

A proxy server is basically another computer ~~which~~ **that** serves as a hub through which internet requests are processed. You can set up ~~AdGuard~~ **Adguard** to route all your device traffic through any proxy.

**Comment by Revertron** [comment]
Fixed, uploaded to OneSkyApp.
