### ISSUE TITLE
Optimize DNS filtering statistics write

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1404]
### Steps to reproduce

The method tracing shows that if you try to open 2-3 different sites in a raw, our statistics writing mechanism is doing too much work. Especially:
Mediator.postDnsStatisticsUpdateEvent() and PreferencesServiceImpl.getDnsRequestProcessed().

### Expected behavior
These methods should throttle their work and not use much CPU time.

### Actual behavior

DNS filtering statistics writing mechanism is doing too much work.

<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/105154/29678884-8780ed60-8900-11e7-8e79-e54ecfe2542b.png)
</details>

### Customer ID 
Me

### Your environment

* Adguard version: 2.10.27
* Adguard filtering mode: proxy auto & vpn (on emulator)
* Device model: Sony Xperia XZ
* Operating system and version 7.1
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
The easiest way to fix this is to throttle calls that save statistics.

**Comment by ameshkov** [comment]
Resolved in pull-requests/12
