### ISSUE TITLE
Feature Request: Search in Filtering Log

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardForAndroid#1408]
Hello, I was wondering if it is possible to include a search icon on the 'Filtering Log' page just as there is one under Settings > User Filter / Apps Management. I sometimes find the need to search the log for an app / URL and have to scroll down. Would be convenient to have it there. Thank you!

### Your environment

* Adguard version: 2.9.135
* Adguard filtering mode: VPN
* Device model: (e.g. Google Pixel) : Redmi Note 3
* Operating system and version (e.g. Android 7.1.2) : MIUI Global 8.5 | Stable [ 8.5.2.0 (MHOMIED) ] Android Version: 6.0.1 MMB29M
* Rooted or not? Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
Hi! It's done already in the latest beta

**Comment by clementine123** [comment]
Ok, many thanks :)
