### ISSUE TITLE
Does the HAR file capture data sent via websockets?

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1409]
bobthedarkhacker asked:
> When I open the file I see “Response body was not recorded” Is there a way to turn that on? Is there a way to only record a certain app’s traffic instead of everything? Does the pcap file have websockets full information or similarly truncated? Is there a way to export the adguard certificate so I can read the https packets in the pcap file? Thanks!

**Comment by ameshkov** [comment]
> When I open the file I see “Response body was not recorded” Is there a way to turn that on?

Not at the moment.

> Is there a way to only record a certain app’s traffic instead of everything?

Sure, just disable Adguard for all apps save for the app you want to record.
If you want to see the traffic unchanged, disable all the ad blocking filters in AG also.

> Does the pcap file have websockets full information or similarly truncated? 

`pcap` has the full info.

> Is there a way to export the adguard certificate so I can read the https packets in the pcap file?

In the next beta version, there will be an "Export settings" button in General. It exports all the app settings including the certificate's private key. However, it won't be enough to decrypt the captured pcap.

I guess the easier way to do the research would be to use Fiddler as an upstream proxy:

0. Set up Fiddler and install its certificate
1. Install the latest AG beta
2. Go to settings -> proxy settings
3. Set it to Fiddler's IP:port
