### ISSUE TITLE
Improve HAR recording

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1410]
Currently long responses, media and images are not recorded. Sometimes it is impossible to re-ask requests and load content, and this HAR is useless.
Is it possible to allow to record everything?(add some option for this?). Resulting file can be large, so I suggest to add сustomizable timeout for HAR recording or/and add [separate]notification about it.

**Comment by ameshkov** [comment]
Btw, it might've been working that way in the CoreLibs implementation
