### ISSUE TITLE
Incorrectly displaying chosen DNS when custom DNS is set up

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1416]
### Steps to reproduce

1. In DNS settings set up custom DNS manually 

<details><summary>Screenshot:</summary

![photo_2017-08-31_14-22-11](https://user-images.githubusercontent.com/23637588/29920786-d029cefe-8e57-11e7-8a8c-00ce92d55998.jpg)

</details>
2. Protection will be restarted, go back to main DNS settings screen and see: 

### Actual behavior
<details><summary>Screenshot:</summary>

![screenshot at aug 31 14-26-04](https://user-images.githubusercontent.com/23637588/29920918-5d9eb074-8e58-11e7-989d-cd0d3983a155.png)

</details>

It looks like system DNS was chosen. But actually manual DNS settings were applied correctly if you check in browser.

And in settings we also see:
<details><summary>Screenshot:</summary>

![photo_2017-08-31_14-33-03](https://user-images.githubusercontent.com/23637588/29921198-6655b8ba-8e59-11e7-9ae9-72dbd2a05b23.jpg)

</details>

### Your environment

* Adguard version: 2.10.51
* Adguard filtering mode: Proxy(auto)
* Operating system and version Android 7.1.1
* Rooted

**Comment by nkartyshov** [comment]
fixed
