### ISSUE TITLE
Can't update the app from 2.10.16b to 2.10.51b

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1417]
### Steps to reproduce

1.Download latest release [beta](adguard.com/apkb)
2.Install it
3.Try to update to v2.10.51b

### Expected behavior

Updated successfully
### Actual behavior

AdGuard fails

[adguard_logs_3108_1524.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1267216/adguard_logs_3108_1524.zip)

### Your environment

* Adguard version:2.10.51
* Device model: Xiaomi Redmi 3s
* Operating system and version 6.0.1

**Comment by ameshkov** [comment]
Fixed
