### ISSUE TITLE
Line app - the HTTPS compatibility issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1418]
https://play.google.com/store/apps/details?id=jp.naver.line.android

The LINE app can't work properly when HTTPS Filtering enabled. It can't sync messages across devices and sends messages. Android OS: 7.0

**Comment by ameshkov** [comment]
@nkartyshov just add the app to the list of exceptions

**Comment by nkartyshov** [comment]
done
