### ISSUE TITLE
Bypassing IPv6 traffic while using WiFi

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#142]
On T-Mobile and AT&T.

Quote from log: 
Device is using Wi-Fi, but Mobile network is IPv6 enabled. Bypassing IPv6 traffic.

HOT-869-99180

**Comment by ameshkov** [comment]
I suppose the problem is that user has IPv6 enabled on both Wi-Fi and Mobile network.
Due to #43 we bypass IPv6 when we detect Wi-Fi is in use AND mobile network has IPv6 address.

It appears that we should also check if Wi-Fi has an IPv6 address and if it is - we should filter IPv6.

**Comment by ameshkov** [comment]
No updates on this issue, clear milestone.
