### ISSUE TITLE
2.10.56 beta crashes on Android 6.0.1

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1421]
**STR:**

1. Open side-menu and choose "Enable HTTPS-filtering for better blocking quality"

**Actual result:** 

Adguard crashes.

[adguard_logs_0109_1331.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1269995/adguard_logs_0109_1331.zip)

**Comment by nkartyshov** [comment]
fixed
