### ISSUE TITLE
Search icon disappearing in Apps management

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#1422]
In the apps management screen the search icon disappears everytime you tap on one of the apps.

![before](http://i.imgur.com/Umb03Wr.png)

![after](http://i.imgur.com/Xj9KILg.png)

![](http://i.imgur.com/NWOhYZg.png)

**Comment by Revertron** [comment]
This is normal. It's like firstly you are in the list, and then you are in app's settings.

**Comment by Bluscream** [comment]
Its annoying as hell tho ^^

**Comment by ameshkov** [comment]
We'll get rid of the two-screens layout eventually.
