### ISSUE TITLE
css filter's bug

### ISSUE THREAD

**Issue by wellser** [AdguardTeam/AdguardForAndroid#1425]
when i visit this site :

 https://m.baidu.com/s?word=linux&ts=4033925&t_kt=0&ie=utf-8&rsv_iqid=2019498619&rsv_t=ba70n286S+Wx7jAFOouS1fG2QyW+Lp7YE3m/k4HwUeGaDbLtO2L2&sa=ib&rsv_pq=2019498619&rsv_sug4=6107&inputT=895&ss=100

you can see a advertisment named "广告", after i recheck the code , i find it contains a div which has a css named "ec_ad_results".
next step , i use this rule "||baidu.com^##.ec_ad_results" to block it , but i find it does not work.
i find some answer about this on the internet , it seems that ,beacuse of the div using a style named "!important" , so it can take the rule to be invalid .

please , fix this bug.

**Comment by vozersky** [comment]
@AdguardTeam/filters-maintainers please assist on this one

**Comment by Alex-302** [comment]
The rule `||baidu.com^##.ec_ad_results` is invalid.
Use following: `baidu.com##.ec_ad_results`

**Comment by wellser** [comment]
i try it again as you said.but , i am using this rule:
baidu.com##.ec_wise_ad,.ec_adv_last,.ec_ad_results,.ec_wise_ad
and visit this site:

https://m.baidu.com/s?word=linux&ts=4033925&t_kt=0&ie=utf-8&rsv_iqid=2019498619&rsv_t=ba70n286S+Wx7jAFOouS1fG2QyW+Lp7YE3m/k4HwUeGaDbLtO2L2&sa=ib&rsv_pq=2019498619&rsv_sug4=6107&inputT=895&ss=100

these advertisments named "广告", still randomly appear again.

what i mean is that HTML elements which have a style "!important" can make my rules to be invalid, is it a bug?

**Comment by Alex-302** [comment]
Try these rules instead previous
```
baidu.com##.ec_wise_ad
baidu.com##.ec_adv_last
baidu.com##.ec_ad_results
```

**Comment by wellser** [comment]
![image](https://user-images.githubusercontent.com/31441377/30048532-34041d40-9249-11e7-840c-32946068a61d.png)
![image](https://user-images.githubusercontent.com/31441377/30048555-4f4bd930-9249-11e7-9334-8a3e6d5aa895.png)
as your way,but it does not work again.

**Comment by Alex-302** [comment]
Ah, got it.
Please check:
```
baidu.com#$#.ec_wise_ad { position: absolute!important; left: -3000px!important; }
baidu.com#$#.ec_adv_last { position: absolute!important; left: -3000px!important; }
baidu.com#$#.ec_ad_results  { position: absolute!important; left: -3000px!important; }
```

**Comment by wellser** [comment]
en...
you use #$# ,not ##.
so it works now ,
but , when i use ##. , it does not work actrually , it is a bug.
i have many rules writing by ##.
i can not convert these rules one by one.
so , i hope you can disolve this problem. please fix it~

**Comment by Alex-302** [comment]
It is not a bug, at least not Adguard's bug. Safari can do it.
