### ISSUE TITLE
beta 2.10 - wrong units, translation

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1429]
I suggest you rename "BANDWIDTH SAVED" to "DATA SAVED". You are confusing units here e.g. Mbps with MB. Bandwith is rate of data transmission. ID: 1117961

**Comment by ameshkov** [comment]
Makes sense :)

**Comment by vozersky** [comment]
I think we've already discussed this a week ago and agreed to change to "data saved" :)

**Comment by ameshkov** [comment]
@vozersky talking about main view now, not the notification

**Comment by Revertron** [comment]
done.
