### ISSUE TITLE
Minor Suggestions for Various Wordings throughout AdGuard

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1430]
Filtering of ~~the~~ HTTPS traffic greatly improves blocking quality on most ~~of the Internet~~ websites.

AdGuard can filter HTTPS in most ~~of the~~ **internet** browsers. Regular apps built for Nougat+ cannot be filtered due to Android restrictions.

AdGuard can filter HTTPS in most ~~of the~~ apps.

Ad~~g~~**G**uard certificate is installed. (this is a toast message)

Starts a safeguard service in another process, which checks **(no comma)** if the main service is alive and restarts it, if necessary. Zero disables it.

Domain Name Servers (DNS) are the ~~I~~**i**nternet's equivalent of a phone book. They maintain a directory of domain names and translate them to Internet Protocol (IP) addresses.  **This seems like a bad definition though and is just copy pasted from the first Google result for DNS word for word; from more digging, it seems like Domain Name System is the more widely recognized meaning (see https://www.pcmag.com/encyclopedia/term/41620/dns and https://en.wikipedia.org/wiki/Domain_Name_System for example). But at the least, internet being lowercase is more commonplace.**

Changing these advanced settings can be harmful to the stability, security **(add comma)** and performance of AdGuard.

Launch AdGuard at system start **(add hyphen)** up. (this one's arguable, but you use the hyphen in another string, so best to be consistent, and hyphen looks cleaner)

The maximum size of the data packet ~~, which~~ **that** is used in **the** local VPN.

**Comment by ameshkov** [comment]
Yay, thank you!

Btw, you can suggest it directly here: https://adguard.oneskyapp.com/collaboration/project?id=13597

If you decide to change anything there, add a comment so that @aalpatkina were notified and could approve it.

**Comment by carlylemiii** [comment]
I can definitely do that for these and for other future things I notice (I'm a *huge* grammar snob). :-)

The only problem is that I cannot figure out how, ha.

~~Every time I click here

![image](https://user-images.githubusercontent.com/29067983/30133207-a21ad6be-9318-11e7-8a94-d9559b8a5648.png)

it takes me to this page

![image](https://user-images.githubusercontent.com/29067983/30133233-baf6236e-9318-11e7-8d49-c5a1d120ddc1.png)

You can see in the first image that I am indeed logged in, but I'm always brought to that second page; I never manage to get anywhere where it looks like I can actually change anything.~~ Suggestions?

Actually, okay, I think I'm getting somewhere once I changed the setting at the top from English -> English to English -> English-US; so it seems I'd be editing/correcting the US English, then, but how does the source English get fixed? Sorry for the dumb questions - but I'd love to help and I figure it'll be faster once I have the know-how than writing Github issues!

**Comment by ameshkov** [comment]
ah, got it, somebody has "finalized" almost all the strings there

**Comment by ameshkov** [comment]
I'll unfinalize them so that you could change anything

**Comment by ameshkov** [comment]
Btw, if you send me an email to am at adguard.com, I can grant you "Reviewer" status there, so that you could approve strings manually.

**Comment by carlylemiii** [comment]
Did so!

Sorry, how do I navigate to edit just plain old English? I can only figure out "translate" pages, so like https://adguard.oneskyapp.com/collaboration/translate/project/project/13597/language-from/1/language/547/#/ for example, but I don't want to translate - I want to edit the original. Right?

And if I do edit the original English, do I make the same change for English (US), or is that automatic? This is all new to me, but I definitely want to make those changes; I'm a diehard AdGuard fan now, so improving the app even further will make me happy :-)

**Comment by ameshkov** [comment]
English -> English translation IS actually editing original:)

**Comment by ameshkov** [comment]
https://adguard.oneskyapp.com/collaboration/translate/project/project/13597/language-from/1/language/1/#/

**Comment by ameshkov** [comment]
To apply the changes, click the "Approve" button on your translation variant.

**Comment by ameshkov** [comment]
Oh, btw, could you plz take a look at this: https://github.com/AdguardTeam/AdguardForAndroid/issues/1246

I suspect that the phrases I used in the mockups might be not good enough:)

**Comment by carlylemiii** [comment]
@ameshkov so cool, I took care of 'em all except the toast message:

Adguard certificate is installed.

(Should have capital G - maybe that's in your code somewhere?)

**Comment by ameshkov** [comment]
@carlylemiii thank you!

@Revertron please download the updated English strings from oneskyapp and check what's with `Adguard certificate is installed `

**Comment by Revertron** [comment]
done.
