### ISSUE TITLE
Add Wealthfront to excluded apps

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1431]
Wealthfront (https://play.google.com/store/apps/details?id=com.wealthfront) needs to be added to the HTTPS exclusions list (or ad blocking entirely). It is an investment app that errors out:

https://imgur.com/MEydBQ7

It works fine with HTTPS disabled for the app, but filtering probably isn't needed for this app anyway (as is the case for many other banking apps).

**Comment by nkartyshov** [comment]
done
