### ISSUE TITLE
Update Filters option in AG Browser Extension

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardForAndroid#1432]
Can you add an option to update the filters in the menu option of the browser extension? Currently, one has to open the AG settings and only then can update them. Thanks!

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardBrowserExtension #850](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/850) via [**ZenHub**](https://www.zenhub.com/)
