### ISSUE TITLE
Filtering Log in AG Browser Extension

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardForAndroid#1433]
Clicking on the search icon opens the Filtering Log page. However, it does not list the entries until it is refreshed. Can you implement this feature so that when the search icon is clicked, the log should display the list without being reloaded (just like uBO). Moreover, can the Filtering Log page be opened in a browser tab instead of the current window? Thanks!

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardBrowserExtension #851](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/851) via [**ZenHub**](https://www.zenhub.com/)
