### ISSUE TITLE
strange toast message, etc...

### ISSUE THREAD

**Issue by Meatbox** [AdguardTeam/AdguardForAndroid#1434]
Adguard version: 2.10
Adguard filtering mode: Proxy(auto)
Device model: LG-F350S(G Pro 2)
Operating system and version Android 4.4.2
Rooted

After install 2.10 version, strange toast message is showing intermittently
"cannot establish vpn (app not prepared)"

and if turn on protection and off, network is not working.

Previous versions(2.9) did not show the above problem

**Comment by ameshkov** [comment]
Hm, wow. Could you please collect AG logs?

**Comment by Meatbox** [comment]
version 2.10.56 log
[https://pastebin.com/raw/FzG5jHCR](https://pastebin.com/raw/FzG5jHCR)

version 2.9.136 log
[https://pastebin.com/raw/bbAtY0uj](https://pastebin.com/raw/bbAtY0uj)

This is the log when the protection is turned off.
The network does not work when I turn off protection in the 2.10.56 version

The strange toast message did not appear because I reinstalled the application. If it comes later, I'll leave a log.

**Comment by ameshkov** [comment]
> This is the log when the protection is turned off.

I'd need to see the log recorded when this toast was shown.

**Comment by vozersky** [comment]
obsolete
