### ISSUE TITLE
nzherald.co.nz - video is broken by AdGuard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1435]
### Steps to reproduce

1. Open http://www.nzherald.co.nz/world/news/article.cfm?c_id=2&objectid=11915943

### Expected behavior
Player works

### Actual behavior

<details>

![image](https://user-images.githubusercontent.com/30041399/30225137-0fb6b84c-94da-11e7-8545-08c16f6ba899.png)
</details>

With/without filters. `@@||nzherald.co.nz^$document` does not help, only disabling AG.

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/6655

**Comment by ameshkov** [comment]
It sends `Accept-Encoding:identity;q=1, *;q=0`, and we are mistakenly adding `gzip` there.

**Comment by ameshkov** [comment]
Resolved in pull-requests/65
