### ISSUE TITLE
Ads on Mako TV

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardForAndroid#1437]
Ads in Mako TV, logs attached

Screenshots:
(https://qcrm.supportyourapp.com/message/attachment/1471299/Screenshot_20170905-014330.png)
(https://qcrm.supportyourapp.com/message/attachment/1471300/Screenshot_20170905-014334.png)

### Customer ID 
1455606

### Your environment

* Android version: 7.1.1 (sdk=25)
* Adguard version: 2.9.136
* Device model: OnePlus ONEPLUS A5000

**Comment by ameshkov** [comment]
@darkulish hi! this should've been filed to the AdguardFilters repo: https://github.com/AdguardTeam/AdguardFilters

Could you plz move it?

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardFilters #6714](https://github.com/AdguardTeam/AdguardFilters/issues/6714) via [**ZenHub**](https://www.zenhub.com/)
