### ISSUE TITLE
Livejournal app broken by filtering

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#144]
The app is working if filtering  is disabled in firewall 
Exclusion didn't helps - @@||l-api.livejournal.com/__api/$document
https://github.com/AdguardTeam/ExperimentalFilter/issues/879
https://play.google.com/store/apps/details?id=com.livejournal.android
CKM-330-40143
SZR-870-62965

**Comment by ameshkov** [comment]
@Alex-302 could you please check it in the latest beta?

We now detect HTML content properly so the issue should be gone.

**Comment by Alex-302** [comment]
Works fine now.

**Comment by ameshkov** [comment]
Nice, thank you
