### ISSUE TITLE
[Question/Bug] Proxy Mode blocking access to open Wi-Fi?

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1440]
I am running the latest public-facing beta.

Should Android OS be set up for ad blocking? By default, it is enabled for adblocking in AdGuard, but from the user-facing log, something is being blocked that I'm guessing shouldn't, because I can't connect to the WiFi network. If I disable AdGuard, and try reconnecting, I am able to. So I don't know if a certain package or URL or something needs to be whitelisted for the connectivity check, or what. 

https://www.dropbox.com/sh/hoi9a1lenk7xr45/AACBGr3jfuT_JqRW-KEppplLa?dl=0

**Comment by carlylemiii** [comment]
Addendum: Apparently I wrote in months ago and something in the Experimental filter was the issue and I requested it be looked into or removed, if that's any help. I'll disable experiemental for now, but I'd hate to see this get moved into a stable filter. :-)

**Comment by ameshkov** [comment]
Thanks for reporting it! We'll fix it:
https://github.com/AdguardTeam/AdguardFilters/issues/6798
