### ISSUE TITLE
Ads are coming up in 'Appsales'

### ISSUE THREAD

**Issue by entryton** [AdguardTeam/AdguardForAndroid#1441]
When I use appsales, I am seeing the default ads even when I had adguard enabled

**Comment by zebrum** [comment]
@entryton hi!
 is this the app: https://play.google.com/store/apps/details?id=net.tsapps.appsales&hl=en ?
also, provide us with some additional information:

- AdGuard version
- filtering mode (VPN or proxy)
- filters enabled
- screenshots with missed ads

Thank you

**Comment by entryton** [comment]
Yes, that is the app.
I'm using the latest beta of adguard.
Please see attached screenshots for escaped ads and other details.


On Sep 14, 2017 2:43 PM, "Marie" <notifications@github.com> wrote:

@entryton <https://github.com/entryton> hi!
is this the app: https://play.google.com/store/apps/details?id=net.tsapps.
appsales&hl=en ?
also, provide us with some additional information:

   - AdGuard version
   - filtering mode (VPN or proxy)
   - filters enabled
   - screenshots with missed ads

Thank you

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardForAndroid/issues/1441#issuecomment-329423011>,
or mute the thread

**Comment by zebrum** [comment]
please attach all screenshots on github page. 
so far I can not reproduce the issue. Need more details about AdGuard settings on your phone

**Comment by TPS** [comment]
I also use AppSales regularly, but don't see ads.  I'm not even HTTPS-blocking nor rooted.  I suppose y'all can close this pending further info.
