### ISSUE TITLE
EV cert filtering checkbox rarely works

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1446]
Steps to reproduce

1. Latest beta
2. HTTPS cert installed to System store
3. Try disabling or enabling EV cert filtering
4. It works maybe 10% of the time with no rhyme or reason I can figure out. Doesn't seem to matter whether AdGuard is running or not. As soon as I leave the HTTPS menu and go back in, the checkbox has been reverted to whatever it was previously. Only once in a blue moon does Adguard "restart to apply change in settings"

### Your environment

* Adguard version: 2.10.56 beta
* Adguard filtering mode: VPN / Proxy(manual/auto) VPN
* Device model: (e.g. Google Pixel) That's the one!
* Operating system and version (e.g. Android 7.1.2) 8.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

Logs, though I don't know if they include app information/debugging or just what's being filtered? 'Cause it's not a filtering issue but an app issue I'm running into. Regardless, here they are :)

https://www.dropbox.com/s/0jye4ohmyltuz60/adguard_logs_1509_1411.zip?dl=0

**Comment by ameshkov** [comment]
I've tried it on my non-rooted device with the certificate installed into the user store and didn't encounter any issues.

I wonder if it's caused by the certificate being installed to the system store?

**Comment by ameshkov** [comment]
@nkartyshov could you please check it?

**Comment by nkartyshov** [comment]
@ameshkov It is bug. Https filtering screen don't have the listener on the do not filter ev checkbox

**Comment by nkartyshov** [comment]
fixed
