### ISSUE TITLE
If IP is blocked by ISP, it is impossible to connect to the site even with via a Proxy

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1449]
[logs.7z.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1309186/logs.7z.txt)

**Comment by ameshkov** [comment]
The problem is in the `RemoteAddressProbe.isAddressAvailable` method.

To work properly this method should use the same outbound proxy while doing the IP availability check.

**Comment by ameshkov** [comment]
Fixed in adguard-android/pull-requests/83
