### ISSUE TITLE
Make Adguard not use WiFi manager when WiFi is disabled.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#145]
Currently it causes Android to believe WiFi module is enabled and consume battery resource. 
More details here RHE-555-44387

**Comment by TPS** [comment]
Maybe this a feature, rather than bug, as per last Q&A from  https://github.com/AdguardTeam/AdguardForAndroid/issues/196#issuecomment-160109535?
>>& what's the practical difference between toggling OS wifi/mobile via system vs. firewall?

>If you toggle it on OS level, app will be aware that network is not accessible. When you disable it on firewall level - it won't be (until it gets the error when trying to get online)

**Comment by ameshkov** [comment]
Frankly, I suppose this issue is outdated and no more relevant.
