### ISSUE TITLE
When HAR, pcap or "record everything" log level is enabled - show a permanent notification

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/AdguardForAndroid#1450]
При включении журнала фильтрации не плохо было бы выводить какое-то дополнительное уведомление в строке состояния / шторке о том что это функция включена. А то иной раз забываю его выключить, и он остаётся включенным не один день.

**Comment by ameshkov** [comment]
Ну я кстати его вообще постоянно держу включенным

**Comment by ameshkov** [comment]
Мы там предупреждаем, что он память/cpu жрет, но это мы от греха немножк преувеличиваем:) На деле это небольшая проблема.

**Comment by Alex-302** [comment]
> дополнительное уведомление в строке состояния

про полный лог и HAR тоже не помешало бы

**Comment by ameshkov** [comment]
Ну вот полный лог и HAR это да, могут диск забить и плохо влияют на производительность

**Comment by ameshkov** [comment]
И pcap еще

**Comment by zovihuxij** [comment]
Ну лишним не будет, для меня было бы полезно, если бы выводилось уведомление на подобии как выводится при включение вышестоящего прокси.

**Comment by ameshkov** [comment]
@nkartyshov given that the TRACE-level logging level of CoreLibs is quite slow, we'd better do it in v2.12.

The notification text:
`AdGuard might be working slow as one of the following features are enabled: full logging, capturing HAR or PCAP.`

Buttons: `Disable`

**Comment by nkartyshov** [comment]
**Testing instructions:**
1. Choose logging-level is Record everything or HAR file recording or PCAP file recording or all those params 
2. Starting protection 

**Expected result:**
A warning notification about slow work will appear

**Comment by vozersky** [comment]
The notification doesn't disapperar, when you disable "Record everything" log or HAR file recording or PCAP file recording @nkartyshov
