### ISSUE TITLE
DnsFilter should properly process trailing dots

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1453]
Check this out:
```
11:48:53.161 [pool-2-thread-1342] DEBUG com.adguard.android.FilteringLog - DNS id=3511 question=csi.gstatic.com.	0	IN	A answer=A: 172.217.17.35 (ttl=136)
A: 216.58.212.163 (ttl=136)
A: 216.58.212.227 (ttl=136)
A: 172.217.19.195 (ttl=136)
A: 172.217.20.67 (ttl=136)
A: 172.217.20.99 (ttl=136)
A: 216.58.209.99 (ttl=136)
A: 216.58.212.195 (ttl=136)
A: 172.217.17.67 (ttl=136)
A: 216.58.201.163 (ttl=136)
A: 172.217.18.131 (ttl=136)
A: 216.58.211.99 (ttl=136)
A: 172.217.17.131 (ttl=136)
A: 172.217.17.99 (ttl=136)
A: 216.58.212.131 (ttl=136)
A: 216.58.209.131 (ttl=136)
```

`question=csi.gstatic.com.` contains trailing dot and this does not allow `||csi.gstatic.com^` block this request.

We should strip trailing dots.

**Comment by nkartyshov** [comment]
@adguard We filter the domain name without a dot, but we write down the domain name with a dot in the log.

**Comment by ameshkov** [comment]
@nkartyshov it's not clear to me then why didn't it work for @TPS

**Comment by ameshkov** [comment]
See here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/511#issuecomment-330124740

**Comment by nkartyshov** [comment]
Because he used not correct rule. In the log file I found line:
> Rule ||csi.gstatic.com^$empty,important is unsupported due to Unknown option empty

**Comment by ameshkov** [comment]
We have `||csi.gstatic.com^` in the simplified domain names filter and it didn't work

**Comment by nkartyshov** [comment]
@ameshkov Domain ```csi.gstatic.com``` in exclusions, because westernunion.com is broken
> westernunion.com is broken https://forum.adguard.com/index.php?threads/22700/ https://forum.adguard.com/index.php?threads/westernunion-com.22897/

@Alex-302 Can we remove the domain ```csi.gstatic.com``` from the exclusions for the simplified domain names filter?

**Comment by Alex-302** [comment]
@nkartyshov but westernunion.com is popular.

**Comment by nkartyshov** [comment]
@Alex-302 But It work fine with rule ```||csi.gstatic.com^``` in the custom filter.

**Comment by TPS** [comment]
Do the exclusions override User Filters, too?  Because that's where I had non-`$empty` version, also.  Doesn't explain https://github.com/AdguardTeam/AdguardForAndroid/issues/511#issuecomment-330124740, either.

**Comment by nkartyshov** [comment]
> We filter the domain name without a dot, but we write down the domain name with a dot in the log.
The ```csi.gstatic.com``` is not filtered, because it is in exceptions.
