### ISSUE TITLE
No internet after disabling DNS settings

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1456]
### Steps to reproduce
1. Enable any non-system DNS server in DNS settings of AdGuard
2. Start AdGuard in automatic proxy mode
3. Disable the main switch in DNS settings
4. Internet is not working (after restart of protection)

### Expected behavior
Internet must be working

### Actual behavior
DNS names are not resolved at all

### Customer ID 
Me

### Your environment
* Adguard version: 2.10.79
* Adguard filtering mode: proxy auto
* Device model: Sony Xperia XZ
* Operating system and version: 7.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by nkartyshov** [comment]
fixed
