### ISSUE TITLE
Enable IPv6 connectivity on protection stop if 'pref.proxy.block.ipv6' is enabled

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1457]
### Steps to reproduce
1. Enable AdGuards protection in root proxy mode
2. Disable protection
3. Try to enable TunnelBears VPN
4. It will not start

### Expected behavior
VPN in TunnelBear should work with AdGuard in root proxy mode

### Actual behavior
TunnelBear is not working even after AdGuards protection stop.
BUT: On the CM12 (Android 5.1.1) TunnelBear works perfectly with AdGuard in root-proxy mode.

### Customer ID 
Me

### Your environment
* Adguard version: 2.10.79
* Adguard filtering mode: Proxy auto
* Device model: Sony Xperia XZ
* Operating system and version: 7.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? TunnelBear

**Comment by Revertron** [comment]
I've compared the `iptables -L` output before and after our protection start. The only thing that is changed after is this table left:
```
Chain ADGUARD_OUTPUT (0 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere             owner UID match u0_a334
RETURN     all  --  anywhere             anywhere             owner UID match u0_a256
RETURN     all  --  anywhere             anywhere             owner UID match u0_a41
RETURN     all  --  anywhere             anywhere             owner UID match u0_a56
RETURN     all  --  anywhere             anywhere             owner UID match u0_a249
RETURN     all  --  anywhere             anywhere             owner UID match u0_a351
RETURN     all  --  anywhere             anywhere             owner UID match u0_a247
RETURN     all  --  anywhere             anywhere             owner UID match radio
```
But I doubt that it can prevent VPN from starting.

**Comment by Revertron** [comment]
Only on my phone this problem is seen.

**Comment by Revertron** [comment]
Okay, I've found the cause - it can not connect if we are blocking IPv6 connectivity.
And there is a small problem - we are not restoring it on protection stop.

**Comment by ameshkov** [comment]
The first one is expected.
What for the second one -- we should restore it only in the case if we have blocked it before, not every time.
