### ISSUE TITLE
Browsing Security step on the initial tutorial

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#146]
Skip button does not disable "Browsing Security".
Also I don't see why this feature is still "premium", let's make it free.

**Comment by TPS** [comment]
>Also I don't see why this feature is still "premium", let's make it free.

@ameshkov Is it still planned to make "Browsing Security" free?  Else, is there any status change for the _original_ issue?

**Comment by ameshkov** [comment]
@TPS yeah, why not.

> Else, is there any status change for the original issue?

Sorry for my bad memory, what's the original issue?

**Comment by TPS** [comment]
>#### Browsing Security step on the initial tutorial #146
>ameshkov commented on Oct 29, 2015
>>Skip button does not disable "Browsing Security".

@ameshkov I thought this was probably fixed months ago.…

**Comment by ameshkov** [comment]
It's just should be done simultaneously.
First - make browsing security feature free.
Second - make "skip" button disable it.

Now it's disabled by default.
