### ISSUE TITLE
https://m.avito.ru/ - content won't load 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1463]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

https://github.com/AdguardTeam/AdguardFilters/issues/6620

***Description***:
* **Current behaviour**: The user reports that he no longer can use the site as the messages won't load. Disabling filters won't help, works only when AdGuard is disabled.

>Проблема с мобильным сайтом Авито , не прогружаются сообщения, написанные в Личный кабинет, скриншот прилогаю, время 10 - 55

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30108794-6ec0884c-930c-11e7-83a9-daf7ba19d67a.png)

</details>

***Steps to reproduce the problem***:

1. Login to avito mobile version
2. You need to have some communication history with other users, I assume. It won't load.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Samsung Internet
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2, 3, 4, 14, 1, 11
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On Default
AdGuard DNS:                        | true
Helpdesk ID (if exists):            | 1150428

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
@evgeniy-ADG please move to the filters repo

**Comment by Alex-302** [comment]
Originally it was posted in filters
https://github.com/AdguardTeam/AdguardFilters/issues/6620
not reproduced on my side.

**Comment by ameshkov** [comment]
@vozersky plz check it

**Comment by zebrum** [comment]
can't reproduce on latest beta too
