### ISSUE TITLE
Headers are not translated after swithcing the language

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1464]
<details>

![photo_2017-09-22_13-38-07 3](https://user-images.githubusercontent.com/17472907/30742210-c814e744-9fa0-11e7-91f6-9b6db465ffe4.jpg)
![photo_2017-09-22_14-15-55](https://user-images.githubusercontent.com/17472907/30742211-c815eb8a-9fa0-11e7-87f2-eab30ea32251.jpg)

</details>

**Comment by nkartyshov** [comment]
fixed
