### ISSUE TITLE
Protection erroneously restarting when going into HTTPS settings menu

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1467]
### Steps to reproduce

1. Go into HTTPS Filtering Settings
2. Select the slider for EV cert filtering
3. Protection is restarted, as expected
4. Leave menu
5. Go back in
6. Protection restarted even without touching that slider. It'll do that every single time then.

</details>

### Your environment

* Adguard version: 2.10.92 beta
* Adguard filtering mode: VPN
* Device model: Google Pixel XL
* Operating system and version: Android 8.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Yes, but not running
* Logs: https://www.dropbox.com/s/0t8hybzfdw7r47v/adguard_logs_2209_1041.zip?dl=0

**Comment by Revertron** [comment]
Fixed.

**Comment by vozersky** [comment]
Still can reproduce this issue on samsung s7 and google pixel, only if `Do not filter websites with EV certificates` is on

**Comment by ameshkov** [comment]
Is it still there?

**Comment by carlylemiii** [comment]
I can't reproduce anymore, tried both with cert installed to the user and system cert stores (separately, of course).

**Comment by ameshkov** [comment]
It should've been fixed, just not marked. Thanks for checking!
