### ISSUE TITLE
When switching from VPN to Auto Proxy, Protection "restarts" but mode doesn't change

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1468]
### Steps to reproduce

1. Be running VPN mode
2. Change in advanced settings to be in auto proxy mode
3. Protection will "restart" but then it's still in VPN mode

So either it should restart in the new mode, or it shouldn't restart. It's currently misleading, but either of those two options would rectify.

</details>

### Your environment

* Adguard version: 2.10.92 beta
* Adguard filtering mode: Auto Proxy or VPN
* Device model: Google Pixel XL
* Operating system and version: Android 8.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Yes, but not running

**Comment by ameshkov** [comment]
Fixed in adguard-android/pull-requests/110
