### ISSUE TITLE
Auto Proxy mode causes Wi-Fi Calling to fail for Verizon Wireless

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1469]
### Steps to reproduce

This is how I narrowed it down to being proxy mode:

1. Run Wi-Fi Calling (in airplane mode, doubt that matters, but necessary for Verizon because otherwise with even the slightest signal, the phone tries to stick to the macro cellular network instead of the wifi connection)
2. Send a text message or make a phone call. Success for both.
3. Enable AdGuard VPN mode.
4. Repeat (2). Success again.
5. Enable AdGuard Proxy mode.
6. Repeat (2).
7. Messages fail, a call attempt might look like it works at first, but then it will error out and say "No response, timed out". Retrying says "radio off" and "turn off airplane mode or connect to a wireless network to make a call"

</details>

### Your environment

* Adguard version: 2.10.92 beta
* Adguard filtering mode: Auto Proxy
* Device model: Google Pixel XL
* Operating system and version: Android 8.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Yes, but not running
* Logs: https://www.dropbox.com/s/jrcyj0ikq7h7k82/adguard_logs_2209_1105.zip?dl=0

**Comment by ameshkov** [comment]
Oh, I know what to do here

**Comment by ameshkov** [comment]
We should exclude some IP ranges of AT&T, T-Mobile and Verizon

**Comment by Revertron** [comment]
@carlylemiii Is it possible to say when exactly you've tried to call? The log file is very long.

**Comment by carlylemiii** [comment]
@Revertron Not this long after, no. I'll reproduce and upload a new log in a bit.

**Comment by ameshkov** [comment]
@Revertron you don't need the log. What you need is to take a look at the `vpn_ipv4_routes_exclusions.txt` file

**Comment by Revertron** [comment]
Implemented for autoproxy mode exclusion of IPs & subnets like in VPN mode. It should help.

**Comment by carlylemiii** [comment]
Oddly enough, this problem came back.

https://www.dropbox.com/s/vai4mfafqdia8oo/adguard_logs_2.10.108_0210_1116.zip?dl=0

Failed call was right before I exported these logs.

**Comment by ameshkov** [comment]
@Revertron plz take a look

**Comment by Revertron** [comment]
But you are using the old version of Adguard: 2.10.92.

**Comment by carlylemiii** [comment]
No, I am using the stable. You can see that in the name of the ZIP of logs.

**Comment by Revertron** [comment]
It's very odd. You have two log files in that archive:
adguard.2017-10-01.log and adguard.log
The last one (without the date) must be the last log, for the current day.
But in that log I see only starting of 2.10.92 (many times).

**Comment by ameshkov** [comment]
You're confusing something, the log is from .108

**Comment by ameshkov** [comment]
Guys, I just realized that Wi-Fi calling on Verizon might be using IPv6 (here's the old issue by @carlylemiii #1258).

However, I see no IPv6 connections at all in the log:(

**Comment by carlylemiii** [comment]
Would it help to have another log where it works in VPN mode but then fails in Proxy mode, as in my original steps to reproduce?

**Comment by ameshkov** [comment]
> Would it help to have another log where it works in VPN mode but then fails in Proxy mode, as in my original steps to reproduce?

Yeah, it might help us understand what's wrong.

One more thing to try: settings -> advanced -> low-level -> find `pref.ports` and change it to `80,443`

**Comment by carlylemiii** [comment]
11:51, successful call over Wi-Fi Calling, VPN mode.
11:52, failed connection/call over Wi-Fi Calling, Auto Proxy mode. "No response, timed out"

https://www.dropbox.com/s/z6i3jatn6u5nc5a/adguard_logs_2.10.108_0210_1152.zip?dl=0

I don't see just a pref.ports; did you mean pref.filtered.ports, and you mean you want me to take everything out of it except those two ports?

**Comment by ameshkov** [comment]
Yeah, `pref.filtered.ports `

**Comment by carlylemiii** [comment]
That did not help.

**Comment by ameshkov** [comment]
@Revertron can we build a simple version that will filter `2000::/3` range only ?

**Comment by Revertron** [comment]
[adguard-v2.10.110-wifi-call-test.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1349702/adguard-v2.10.110-wifi-call-test.zip)
Here it is.

**Comment by ameshkov** [comment]
@carlylemiii could you please try it?

**Comment by carlylemiii** [comment]
Tried it, no such luck.

**Comment by ameshkov** [comment]
Reassigned to v2.11, seems to be quite complicated:(

**Comment by carlylemiii** [comment]
So I don't know if it'll help diagnose the issue...but this was originally fixed in 2.10.104, which I just rolled back to, and it works again. Somehow between 104 and 110 a regression seems to have happened. Or is it possible that commit somehow didn't make it into the final build? I'm sure you've thought of that...but you never know. :)

**Comment by ameshkov** [comment]
As I recall, something didn't work for you in .104. IPv6 filtering maybe?

**Comment by carlylemiii** [comment]
Ah, yes. That is right. Back to your comments about IPv6 and this being complicated. Sorry :(

**Comment by carlylemiii** [comment]
This might be just as much work, but I don't know:

Would it be possible to diagnose what gets blocked and reset it upon disabling proxy mode, or is that exactly just as much work as figuring out how the two can coexist together in general? What I mean is even after disabling proxy mode, WiFi calling doesn't work without a restart, and it would be nice if I could switch modes without essentially necessitating a system restart on a daily basis (as I go to or from location where WiFi calling is necessary).

If not feasible, I understand. :-)

**Comment by Revertron** [comment]
Hm, I think that this is exactly the same problem as I have with Tunnel Bear.
The strange thing is that on one device it works perfectly, but on another it needs a restart to start working (after AdGuard's auto proxy was used).

**Comment by DrSuSE** [comment]
Not sure if there is anything I can do/test/provide to contribute to a resolution, but I am experiencing this issue as well.

**Comment by ameshkov** [comment]
Guys, one more question.

Does it help to disable AdGuard for Android OS?

Here's what you should do:

1. Apps Management -> Find "Android OS" -> tap on it
2. On the details screen, uncheck "Enabled" box
3. Protection will be restarted automatically, check Wi-Fi calling now.

**Comment by carlylemiii** [comment]
Actually, yeah. That works. Is that a resolution in and of itself (will ads slip through now?) or does that just narrow down the issue?

**Comment by ameshkov** [comment]
Yeah, that seems to be a resolution for this particular issue. It seems that filtering "Android OS" in the proxy mode sometimes cause absolutely mysterious issues.

> will ads slip through now?

Nope, they should not.

The question is -- what should we do now. We have three options:

1. Disable "Android OS" filtering in all modes by default. This is a safe option, and it may help solve some crazy issues.
2. Disable "Android OS" filtering in the proxy+root mode only by default.
3. Keep the filtering enabled by default and write a knowledge base article about that.

Tbh, I am tending to the first solution. Let's wait a bit and see if you face any drawbacks.

**Comment by DrSuSE** [comment]
I just re-setup Adguard to test this... initially speaking it seems good.
I will report back after some time and use.

If it continues to work, I would say at least #2, but probably #1 is best.
#3 will just lead to frustration for your team and users (especially new
users/potential subscribers).

**Comment by carlylemiii** [comment]
@ameshkov This is not actually the solution. :/ (Because of https://github.com/AdguardTeam/AdguardForAndroid/issues/1679)

**Comment by ameshkov** [comment]
@DrSuSE are you on Android 8.1 as well?

**Comment by DrSuSE** [comment]
Yes, Pixel 2XL running 8.1

**Comment by ameshkov** [comment]
Magisk?

**Comment by DrSuSE** [comment]
Yes.

On Jan 7, 2018 4:49 PM, "Andrey Meshkov" <notifications@github.com> wrote:

Magisk?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardForAndroid/issues/1469#issuecomment-355855498>,
or mute the thread

**Comment by ameshkov** [comment]
Uh, got it. So we need to wait for #1679 then. Thank you, guys!

**Comment by DrSuSE** [comment]
I might be missing something (sorry, in bed sick on lots of drugs)... what
are we saying isn't working or needs testing/confirmation?

**Comment by carlylemiii** [comment]
@DrSuSE IPv6 filtering doesn't work with Magisk and 8.1 and proxy mode. So until it does, we don't know if not filtering Android OS actually works for this.

**Comment by DrSuSE** [comment]
Gotcha... I can only say that Adguard was blocking my Wi-Fi calling
capabilities before the idea to disable Android OS in Adguard Apps
Management and now Wi-Fi Calling works with the "Enabled" box unchecked.

On Jan 7, 2018 5:25 PM, "carlylemiii" <notifications@github.com> wrote:

@DrSuSE <https://github.com/drsuse> IPv6 filtering doesn't work with Magisk
and 8.1 and proxy mode. So until it does, we don't know if not filtering
Android OS actually works for this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardForAndroid/issues/1469#issuecomment-355857997>,
or mute the thread

**Comment by ameshkov** [comment]
Huh, so it might've helped after all:)

@DrSuSE @carlylemiii guys, what exact Magisk version do you have? You see, Magisk issues depend on the version, some versions do mess with IPv6, others not.

**Comment by DrSuSE** [comment]
Magisk 15.2, Magisk 5.5.3.

**Comment by carlylemiii** [comment]
Or it's just that IPv6 wasn't being filtered. I'm using 15.2 as well.

**Comment by DrSuSE** [comment]
Sorry, that was supposed to be

Magisk 15.2, Magisk Manager 5.3.

**Comment by carlylemiii** [comment]
@DrSuSE 5.5.3 is the Manager version you should be on with Magisk 15.2.

**Comment by DrSuSE** [comment]
Right, I was just clarifying because I failed to type the word "Manager" in
my original reply.

**Comment by carlylemiii** [comment]
Ah, I see that now. You typod the number in your correction is why I was confused haha

**Comment by DrSuSE** [comment]
Geeez... Okay, I've had enough of typing under medication. Sorry about
that, haha. Thanks for catching it.

I'll put the phone down until tomorrow.

**Comment by carlylemiii** [comment]
Resolved in https://github.com/AdguardTeam/AdguardForAndroid/issues/1679

**Comment by ameshkov** [comment]
Thx, no idea why I was hesitating with this:)

Now we need to figure what IP range should be excluded in #1570 and we're all good.

**Comment by ameshkov** [comment]
@carlylemiii hi! We're going to introduce some changes in the next nightly build (it will be available today).

Could you please try it and check if this new version does not break Wi-Fi calling in auto-proxy mode again?

**Comment by ameshkov** [comment]
Test build: https://uploads.adguard.com/up04_7spsr_adguard_wifi_calling.apk

**Comment by carlylemiii** [comment]
@ameshkov I am sorry, but I no longer have my device rooted. I took a job that disallows it, so I use VPN mode now.

**Comment by ameshkov** [comment]
@carlylemiii huh, that's a pity :(

Hopefully, the new solution will work anyways. Disabling AG for Android OS helped so there is hope. In the new build, we removed IP routes from exclusions, and instead, we added `uid=1000` to exclusions.

PS: just so that we could keep track of linked issue, here is a detailed explanation of this bug and what was causing it: https://github.com/AdguardTeam/AdguardForAndroid/issues/2550

**Comment by carlylemiii** [comment]
@ameshkov are there updated various adb commands like in https://github.com/AdguardTeam/AdguardForAndroid/issues/1679 that I could do unrooted to emulate AdGuard setting up? Maybe I was the only Verizon user using auto-proxy mode and it's not even worth it, but I thought I'd ask :)

**Comment by ameshkov** [comment]
@carlylemiii nope, that requires full root access:( 

> Maybe I was the only Verizon user using auto-proxy mode and it's not even worth it, but I thought I'd ask :)

Well, the issue exists with any operator, not just Verizon. That's why we are trying another solution - it should work well with every operator and hopefully in both VPN and proxy mode.

**Comment by DrSuSE** [comment]
I use wifi calling, Verizon, local auto proxy mode, etc.  Just need someone to install this test build and make a wifi call to see if it works?

**Comment by ameshkov** [comment]
@DrSuSE that would be awesome!

Here's what you need to do in order to test it:
1. Install the new build. If this is not a clean install, please make sure that you do the following:
2. Go to settings -> advanced -> low-level settings, and click "Reset settings" there.
3. Go to apps management -> tap on the menu button there -> tap "Reset settings"
4. Check if wi-fi calling works

**Comment by DrSuSE** [comment]
Sorry for the delay, ended up being a hectic day. 

Installed, performed the listed reset steps, made some calls and Wi-Fi calling engaged without issue. 

Rebooted and tried another call to make sure. 

Seems ok as far as some quick testing goes.

**Comment by ameshkov** [comment]
@DrSuSE this is great news, thank you for testing it!

Finally, we found a proper solution to that bug.
