### ISSUE TITLE
Implement pref.app.exclusions low-level setting

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#147]
Coma-separated list of package names:
pref.app.exclusions=system,some.app.package

There will be no filtering for these apps.
In case of proxy - no redirect.
In case of VPN - we'll use vpn api to exclude them (supported since Lollipop)

**Comment by ameshkov** [comment]
Send this build to user:
http://4pda.ru/forum/index.php?showtopic=601691&st=3500#entry44034921

**Comment by TPS** [comment]
@ameshkov Could this eventually be turned into a flag in the firewall screen?  Or the ability to turn the AdGuard shield gray (like you all do for the builtin exclusions)?

**Comment by ameshkov** [comment]
In future versions - it should be there. But this involves re-designing the Firewall screens.
