### ISSUE TITLE
 Communication permission in firewall notification

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#1478]
Hello. I have a request. It is troublesome because communication
permission in firewall notification is instantaneous. I want to select
the time to allow communication when I allow communication. For
example 1 minute 10 minutes 1 hour. I usually want to shut off
communication, but I do not want to ask permission again for one hour
while using the application and using it. Thank you for considering the improvement of the function.

### Customer ID 
1633863

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
