### ISSUE TITLE
Separation of mobile data/Wi-Fi usages in app management section

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#1479]
Dear Devs. Would you please separate mobile data/Wi-Fi usages in app
management section? As you know, Android system counts as Adguard has
consumed all traffic when adguard is enabled. So I hope to see my
"Mobile Data Usages" per app through adguard's app management tab.

### Customer ID 
1549618

**Comment by ameshkov** [comment]
We will definitely do it
