### ISSUE TITLE
Two notification while using Orbot

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1482]
If you disconnect through "Connected to Tor via Orbot" notification and then reconnect through the proxy menu, you will have both "connected" and "disconnected" notifications at the same time.

<details><summary>Screenshots:</summary>

![photo_2017-09-26_23-58-20](https://user-images.githubusercontent.com/17472907/30884071-e56fed60-a316-11e7-8a41-796c6f90ced6.jpg)
![photo_2017-09-26_23-58-26](https://user-images.githubusercontent.com/17472907/30884070-e56025e2-a316-11e7-80be-64a82e58eb9a.jpg)

</details>

**Comment by Revertron** [comment]
Fixed.

**Comment by Revertron** [comment]
Fixed.
