### ISSUE TITLE
If "block ads in apps" is disabled, we should gray out "Ad blocking" setting in the per-apps settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1484]
Apps Management -> App details

**Comment by nkartyshov** [comment]
done

**Comment by ameshkov** [comment]
Issues:

* Switching checkboxes is very slow
* "Enabled" box does not work at all
* Disabling and enabling "ad blocking" makes "https filtering" editable for apps that target nougat

**Comment by ameshkov** [comment]
Done
