### ISSUE TITLE
Adguard revokes VPN access rights if protection is enabled

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1490]
**STR:**
1. Try to connect to VPN through system settings.

**Expected result:**
Connection is established, Adguard is paused until you resume protection.

**Actual result:**
Adguard restarts it's VPN shortly after the the connection is established.

**Video:**
https://drive.google.com/file/d/0B5uODhmUA5OaRm1CZl9iamc2Tms/view

Works fine If you stop the protection before connecting to VPN.

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1022 no?
