### ISSUE TITLE
[request] please add additional polish lang. filters

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#1491]
Adguard For Android don't including `Adblock & uBlock polish filters - Adguard supplement` and `Polish filters - social` in filters list. Thanks

https://github.com/MajkiIT/polish-ads-filter/blob/master/adblock_social_filters/adblock_social_list.txt

https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock_adguard.txt

**Comment by zebrum** [comment]
moved to https://github.com/AdguardTeam/AdguardFilters/issues/6961
