### ISSUE TITLE
Wrong units in the battery stats graph

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1494]
We're confusing mA with mAh (мА·ч) here:

![image](https://user-images.githubusercontent.com/15856304/31008837-2498c20c-a50e-11e7-82a9-b6f5d8b4f12a.png)

USER ID OF THE ORIGINAL REPORTER: 1471268

> В батарее мА - это все же ток, моментальная величина. В нашем случае это все же мА/ч , потраченная емкость батареи.

### Your environment

* Adguard version: 2.10.94
* Adguard filtering mode: VPN 
* Device model: motorola XT1580
* Operating system and version: Android 6.0.1

**Comment by nkartyshov** [comment]
done
