### ISSUE TITLE
adguard android 2.10.108 bug

### ISSUE THREAD

**Issue by medoiq** [AdguardTeam/AdguardForAndroid#1497]
an again i have same bug with this version I use ad guard in proxy mode with root and when disconnect internet ad guard closes
android 4.4.2
rooted with king root

**Comment by ameshkov** [comment]
Could you please attach AdGuard's log to this issue?

Settings -> Advanced -> Export logs and system info

**Comment by medoiq** [comment]
[adguard_logs_2.10.108_0110_2219.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1347476/adguard_logs_2.10.108_0110_2219.zip)

**Comment by nkartyshov** [comment]
@medoiq Try to set the WatchDog interval to 10 seconds and set the notification icon to the 'Default icon'.
