### ISSUE TITLE
AG v2.10. A missed Traditional Chinese translation, "add rule".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1499]
@ameshkov
@aalpatkina

Hi,
1. In the past, I completed translating "add rule" to Traditional Chinese translations.
![Image of Yaktocat](https://i.imgur.com/wMPZn3o.png)

But the button of "add rule" in AG v2.10 is still English, not Traditional Chinese.
![Image of Yaktocat](https://i.imgur.com/A8ljzA1.jpg)

Please update it next time.
Maybe anew take translations from oneskyapp because I updated a few of translations.

2. And then what does this mean?
loading time? Or loading times?
Время или количество раз?
![Image of Yaktocat](https://i.imgur.com/ZaNhKX0.png)

Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov
@aalpatkina 

Hi, thank you.
But you forgot to answer my 2nd question.

loading "time"? Or loading "times"?
Время или количество раз?

Thanks for your great work!

**Comment by aalpatkina** [comment]
Hi,
Sorry!

The use of the plural "times" is here correct. It means that Removing ads and tracking action takes place each and every time.

**Comment by syokkendesuyo** [comment]
Japanese is also similar.
AdGuard : 2.10.110
![2362222](https://user-images.githubusercontent.com/5967134/31132864-dbe51aa4-a898-11e7-85e6-a341b8c88c24.png)

**Comment by aalpatkina** [comment]
@lancelot-moon 
 Or it also can be explained in such a way:
"when ads are removed and tracking is prevented, then browser pages and apps will have faster loading times"
However the use of form "loading times" is here correct.

**Comment by Revertron** [comment]
fixed.
