### ISSUE TITLE
Add "Too many filters" alert to the "Ad Blocker" settings section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#15]

**Comment by TPS** [comment]
For the record, what *is* the filter limit? Is this including all subscriptions or just custom filters?

**Comment by ameshkov** [comment]
We'll set it to 50k filter rules. Mobile version is very sensitive to the number of filter rules, you'll feel the difference if you enable unoptimized English filter.

**Comment by Nick-White** [comment]
Does it crash or just slow down? Because I think there are many cases where slowdowns would be acceptable (given the alternatives). 

Will it be a warning or enforced (I hope not because it limits power users)?

**Comment by ameshkov** [comment]
Depends on the device's ram it may go either out of memory (for devices with 512 ram for instance) or just slow down.

Anyway we won't set a hard limit, just want to alert user that using too many filters may be a bad idea.

**Comment by vozersky** [comment]
obsolete
