### ISSUE TITLE
Minor UI issue in traffic stats screen

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1500]
I'm on 2.10 stable, Pixel XL, Oreo.

The date August 26 is being partially cut off:

https://imgur.com/fRjWEqM

**Comment by carlylemiii** [comment]
Also should the valleys on the graph be visible? It looks like they go below the x-axis at some points. Not sure if that's an issue or not?

**Comment by Revertron** [comment]
Fixed.
