### ISSUE TITLE
Whitelist is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1504]
Whitelisting is not working. Element hiding is not disabled, when domain is added to whitelist.
Exclusion works(added to mobile filter):
```
stevengoh.com#@#.header-ad
```

### Steps to reproduce

1. Go to stevengoh.com

### Actual behavior
Blank screen.

Original issue:
https://forum.adguard.com/index.php?threads/adguard-v2-10-whitelist-english-filter-android.25567/#post-154072

### Your environment

* Adguard version: 2.10

**Comment by vozersky** [comment]
reproduced

**Comment by ameshkov** [comment]
This might be happening due to `Connection: Upgrade` header, which is invalid btw. Anyway, should be tested.

**Comment by nkartyshov** [comment]
@ameshkov It's not because of Connection: Upgrade header.

**Comment by ameshkov** [comment]
This is a CoreLibs bug, found it

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/90

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/131`
