### ISSUE TITLE
Sporadic "cannot obtain a connection to the server" message for MyChart app

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1505]
https://play.google.com/store/apps/details?id=epic.mychart.android&hl=en

### Steps to reproduce

1. You basically just click around in different activities in the app until you get the connection error message.
2. You likely won't be able to test this because you will need a MyChart account.

### Expected behavior

Successful connection always.

### Actual behavior

Sometimes the error message "MyChart cannot obtain a connection to the server even though you have an Internet connection" will appear. I think this doesn't happen when SSL filtering is disabled.

There have never been any ads, trackers, anything blocked for this app, so I would say it's probably safe to disable filtering altogether, but you make that call. It's an application for one's own access to one's own medical record, so it makes sense there wouldn't be things that need to be blocked.

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: Auto Proxy
* Device model: Google Pixel XL
* Operating system and version: Android 8.0.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

[adguard_logs_2.10.108_0210_0916.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1399837/adguard_logs_2.10.108_0210_0916.zip)

The error message was seen just before export.

**Comment by nkartyshov** [comment]
done
