### ISSUE TITLE
"Filter auto-update period" display error (Japanese)

### ISSUE THREAD

**Issue by syokkendesuyo** [AdguardTeam/AdguardForAndroid#1508]
### Steps to reproduce

1.Change language to Japanese
2.Settings(設定) --> General(一般設定) --> Filter auto-update period(フィルタの自動更新頻度)

### Expected behavior

English: 1hour 2hours 3hours ... 
Japanese 1時間 2時間 3時間 ...

### Actual behavior

Units(hours/時間) are not displayed.
1時間 2 3 ...

<details><summary>Screenshot:</summary>

[27199051](https://user-images.githubusercontent.com/5967134/31132587-1b30bee4-a898-11e7-8e64-66258870781f.png)

</details>

### Your environment

* Adguard version: 2.10.110 (Acquired from translation moderator)
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus5X
* Operating system and version: 8.0.0
* Rooted or not? : not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? : no

### ID of oneskyapp
#27199051

**Comment by Revertron** [comment]
Found the problem, fixed.
