### ISSUE TITLE
Incorrect calculation result of "App Details "screen

### ISSUE THREAD

**Issue by syokkendesuyo** [AdguardTeam/AdguardForAndroid#1509]
### Steps to reproduce

1.Apps Management --> Select any app (ex:Chrome)

### Expected behavior
ex: 52%
(Probably the correct display)

### Actual behavior

5211%
(Bug?)

<details><summary>Screenshot:</summary>
![ad](https://user-images.githubusercontent.com/5967134/31136571-a5459e32-a8a3-11e7-94a9-7504a4e504d5.png)

</details>

### Your environment

* Adguard version: 2.10.110 (Acquired from translation moderator)
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus5X
* Operating system and version: 8.0.0
* Rooted or not? : not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? : no

**Comment by Revertron** [comment]
We've been incorrectly getting total transferred data from database. Fixed.
