### ISSUE TITLE
Error in description of "Export settings" (Japanese)

### ISSUE THREAD

**Issue by syokkendesuyo** [AdguardTeam/AdguardForAndroid#1510]
### Steps to reproduce

1.Change language to Japanese(日本語)
2.Settings(設定) --> General(一般設定) --> Export settings(設定をエクスポート)

### Expected behavior

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
**設定をエクスポート**
設定をファイルにエクスポートします
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

### Actual behavior

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
**設定をエクスポート**

設定をファイルにエクスポートします
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

<details><summary>Screenshot:</summary>
![#39685046](https://user-images.githubusercontent.com/5967134/31136817-330b4942-a8a4-11e7-8aac-d43095a86e55.png)

</details>

### Your environment

* Adguard version: 2.10.110 (Acquired from translation moderator)
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus5X
* Operating system and version: 8.0.0
* Rooted or not? : not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? : no

### ID of OneSky
#39685046

**Comment by Revertron** [comment]
As I can see, the actual and expected behaviors are the same.
But the summary in oneskyapp is shorter:
設定をファイルにエクスポート
instead of:
設定をファイルにエクスポートします

Setting the last one as correct. If it is...
