### ISSUE TITLE
Error in description of "Proxy settings" (Japanese)

### ISSUE THREAD

**Issue by syokkendesuyo** [AdguardTeam/AdguardForAndroid#1511]
### Steps to reproduce

1.Change language to Japanese
2.Settings(設定) --> Proxy settings(プロキシ設定)

### Expected behavior

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
プロキシを追加
サーバーのアドレスと資格情報を入力しプロキシに接続する
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

### Actual behavior

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
プロキシを追加
サーバーのアドレスと資格情報を入力しプ
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

<details><summary>Screenshot:</summary>

![38657676](https://user-images.githubusercontent.com/5967134/31137174-6404bd7a-a8a5-11e7-995c-23230c8130c8.png)

</details>

### Your environment

* Adguard version: 2.10.110 (Acquired from translation moderator)
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus5X
* Operating system and version: 8.0.0
* Rooted or not? : not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? : no

### ID of OneSky
#38657676

**Comment by Revertron** [comment]
It is fixed in oneskyapp, we need just to download it.
