### ISSUE TITLE
Error in "Ad Blocker" (Japanese)

### ISSUE THREAD

**Issue by syokkendesuyo** [AdguardTeam/AdguardForAndroid#1512]
### Steps to reproduce

1.Change language to Japanese(日本語)
2.Settings(設定) --> Ad Blocker(広告ブロックフィルタ)

### Expected behavior

- 英語フィルター
- スパイウェアフィルター
etc...

### Actual behavior

- 英語フィルター。
- スパイウェアフィルター。
etc...
( "。" is unnecessary )

<details><summary>Screenshot:</summary>
![ad](https://user-images.githubusercontent.com/5967134/31137570-99a90b92-a8a6-11e7-9112-edc84b188363.png)

</details>

### Your environment

* Adguard version: 2.10.110 (Acquired from translation moderator)
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus5X
* Operating system and version: 8.0.0
* Rooted or not? : not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? : no

**Comment by Revertron** [comment]
We need help from @mmigi, as the names of the filters are in server database...

**Comment by Revertron** [comment]
fixed.
