### ISSUE TITLE
Old translation remaining (Japanese)

### ISSUE THREAD

**Issue by syokkendesuyo** [AdguardTeam/AdguardForAndroid#1513]
### OneSky
#12033397
old: Low Level Settings --> Low Level Settings
new: Low Level Settings --> 高度な設定

#2362235
old: 自動 (rootを取得している必要あり)
new: 自動 (root権限が必要です)

#2479772
old: rootを取得している必要はありますか？
new: root権限が必要ですか？

### Your environment

* Adguard version: 2.10.110 (Acquired from translation moderator)
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus5X
* Operating system and version: 8.0.0
* Rooted or not? : not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? : no

**Comment by aalpatkina** [comment]
The corrections have been made.

Thanks.
