### ISSUE TITLE
Can't sign up with "Be My Eyes" with HTTPS filtering enabled

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1518]
https://play.google.com/store/apps/details?id=com.bemyeyes.bemyeyes

Having AdGuard HTTPS filtering enabled causes the app to incorrectly display a message that the app is out of date and can't be used.

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: VPN
* Device model: Google Pixel XL
* Operating system and version: Android 8.0
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

Logs/screenshot:

![screenshot_20171006-131710](https://user-images.githubusercontent.com/29067983/31292803-666d6a3e-aa9a-11e7-811f-274a7d62a8b1.png)

[adguard_logs_2.10.108_0610_1319.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1363576/adguard_logs_2.10.108_0610_1319.zip)

**Comment by nkartyshov** [comment]
@carlylemiii Do you have this problem if you disabled https filtering?

**Comment by carlylemiii** [comment]
Nope.

**Comment by carlylemiii** [comment]
Jesus. I have this in my new emails, from the CTO of that company. I mean I guess I did have to give them an email to sign up but it is still really discomforting how I was reached out to without first contacting them.

> I can see in our server logs that you are trying to use Be My Eyes on Android - with mixed success. The problem is that we are strict wrt. to security by enforcing that our own SSL certificates are used to ensure that the data is transferred fully encrypted from our app to our server. 

> AdGuard tries to circumvent this by installing another root certificate on our phone, which allows them to intercept (and filter) data. We do not allow this.

**Comment by ameshkov** [comment]
Impressive:) I guess we should disable HTTPS filtering for the app by default.

**Comment by nkartyshov** [comment]
Added this app to https filtering exclusions.
