### ISSUE TITLE
[Bug] Not Starting After Reenabling WIFI

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardForAndroid#1519]
Adguard doesn't automatically start after wifi has been disabled and then reenabled.

For better stability, is it worth having a second process that monitors the main adguard process and restarts it if it has stopped and there's an internet connection available.

Thanks

### Steps to reproduce

1.Adguard is enabled and working
2.Disable wifi
3.Adguard is automatically disabled
4.Enable wifi
5.Adguard is still disabled

### Expected behavior

I presume adguard should automatically start when wifi is reenabled and an internet connection is available.

### Actual behavior

Its not automatically starting.

### Your environment

* Adguard version:Newest beta
* Adguard filtering mode: VPN
* Device model: LG G3
* Operating system and version Android 6
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?
No

**Comment by ameshkov** [comment]
We have a second process -- it's called "Watchdog period"

**Comment by ameshkov** [comment]
Could you plz reproduce the issue and attach Adguard's log?

**Comment by zero77** [comment]
Thanks for the speedy response, and is this the log you mean.
https://pastebin.com/9Q83rLX1

**Comment by ameshkov** [comment]
@zero77 no, you can export it from the app (settings -> advanced -> export logs and system info)

**Comment by zero77** [comment]
It seems to only be happening when the wifi has been disabled for a while it works fine when the wifi has only been disabled for a shorter period of time.

https://pastebin.com/emA4C84a

**Comment by ameshkov** [comment]
What I see in the log.

**AdGuard was swiped away from recent apps:**
```
14:58:46.478 [main] INFO  com.adguard.android.ServiceManager - Task removed called
```

**Shortly after that connectivity change event was received and AdGuard was killed by Android soon after that.**
```
14:58:50.593 [main] INFO  c.a.android.filtering.filter.e - Device screen state changed to false
14:58:52.120 [main] INFO  c.a.a.r.NetworkStateReceiver - Start NetworkStateReceiver on action android.net.conn.CONNECTIVITY_CHANGE
14:58:52.832 [main] INFO  c.a.a.r.NetworkStateReceiver - Handle network connectivity change
14:58:52.833 [main] INFO  com.adguard.android.ui.utils.o - Start VPN auto restart check
14:58:52.864 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet0 connected = false
14:58:53.095 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet1 connected = false
14:58:53.263 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet8 connected = false
14:58:53.263 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet3 connected = false
14:58:53.264 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet2 connected = false
14:58:53.264 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet4 connected = false
14:58:53.265 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet6 connected = false
14:58:53.265 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet5 connected = false
14:58:53.265 [main] INFO  c.a.android.filtering.commons.d - Interface: rev_rmnet7 connected = false
14:58:53.266 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet0 connected = false
14:58:53.266 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet1 connected = false
14:58:53.267 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet3 connected = false
14:58:53.267 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet2 connected = false
14:58:53.268 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet4 connected = false
14:58:53.268 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet6 connected = false
14:58:53.269 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet5 connected = false
14:58:53.269 [main] INFO  c.a.android.filtering.commons.d - Interface: rmnet7 connected = false
14:58:53.269 [main] INFO  c.a.android.filtering.commons.d - Interface: tun0 connected = true
14:58:53.270 [main] INFO  com.adguard.android.ui.utils.o - VPN is connected, do not autostart
14:58:53.328 [main] INFO  com.adguard.android.ui.utils.o - Finished VPN auto restart check
14:58:53.405 [main] INFO  c.a.a.r.NetworkStateReceiver - Current active network info: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "ssid", roaming: false, failover: false, isAvailable: true, network type: 1]
14:58:53.488 [main] INFO  c.a.a.r.NetworkStateReceiver - Network WIFI connected. State=CONNECTED.
14:58:53.547 [main] INFO  c.a.android.filtering.filter.e - Connected to network type=1
```

**WatchDog process is initialized in an hour**
```
15:41:49.109 [main] INFO  c.a.android.AdguardApplication - AdGuard application creating... Process name: AdGuard.WatchDog
15:41:49.121 [main] INFO  com.adguard.android.b - Initializing ServiceLocator for com.adguard.android.AdguardApplication@99d499
```

My questions to @nkartyshov:
1. Is it okay that WatchDog writes log to the very same location as the main AG process? Wouldn't it be better to call it "watchdog.log"?
2.  I suppose when user contacts support service (with send logs checked), the watchdog.log should be sent along with `adguard.log` contents

**Comment by ameshkov** [comment]
@zero77 I need to know when exactly have it happened last time? I see nothing suspicious in the log, protection was paused, then started back automatically once net connection was available again

**Comment by zero77** [comment]
I was trying to replicate it again today before I posted the log although this time it worked correctly.

Although, when it doesn’t work correctly it seems to be when the wifi has been disabled for a longer period of time, I think around an hour or more.

**Comment by nkartyshov** [comment]
@ameshkov I think it is good idea. But what we will writing to the 'watchdog.log'?

**Comment by Revertron** [comment]
But I've made it specially like that, to write the Watchdog's logs to our main log file.
It is easier to find all starts of the application processes there, in one file.

**Comment by ameshkov** [comment]
@zero77 the only idea I have is that it's Android misbehavior, but I can't say for sure unless I see the logcat with the issue reproduced

**Comment by ameshkov** [comment]
> But I've made it specially like that, to write the Watchdog's logs to our main log file.
> It is easier to find all starts of the application processes there, in one file.

I am just afraid of a possible misbehavior on the log file rollover

**Comment by nkartyshov** [comment]
@ameshkov What could happen during the log file rollover?

**Comment by zero77** [comment]
Ok thanks, I will keep an eye on it and next time the wifi has been disabled for a while and it happens I will post a log.

**Comment by Revertron** [comment]
Watchdog process successfully writes all its logs to the main log, there is not need to separate it from main process.
