### ISSUE TITLE
Viber is totally blocked (again) using adguard android.

### ISSUE THREAD

**Issue by TetherAd** [AdguardTeam/AdguardForAndroid#1521]
Hi,

Seems you don't like viber there ^^

Doesn't work at all with latest adguard (was ok before).

Thank you.

PS : it work when I desactivate viber on the adguard firewall for sure.

**Comment by nkartyshov** [comment]
I have viber and it work fine for last release version. 
@TetherAd Can you record log?

**Comment by TetherAd** [comment]
Hi,

Seems to work now, can't reproduce the problem, sorry.

And log record was not enabled sorry.

Thanks.

**Comment by nkartyshov** [comment]
@TetherAd That's all right.
