### ISSUE TITLE
DNS based on the current network or the ability to configure regular and dnscrypt custom servers simultaneously.

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#1522]
Latest settings improvements over proxy and dns are great 👍 but I'd
like to configure dns based on the current network or the ability to
configure regular and dnscrypt custom servers simultaneously. Actually
when at home I use an in lan server but when outside I use Google one
so my custom servers are 10.x.y.z (private address which becomes
unreachable outside home) and 8.8.8.8 (which acts as a failover on
primary so it gets used when in an unsafe place).

Ticket ID: 1638609

**Comment by Riekr** [comment]
I had to stick with system dns as failover between primary and secondary dns does not work resulting in the inability to resolve addresses outside my home network

**Comment by ameshkov** [comment]
We do provide an option to configure a fallback in the low level settings
