### ISSUE TITLE
Proxy mode with Magisk 14.2 takes 2+ minutes to enable

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1527]
I always hesitate whether issues should be written up as new, but as part of this fix, please investigate the latest Magisk build (14.2) with Android 8.0 (for me it's on a Pixel XL). Not sure if it's AdGuard or Magisk's fault, but automatic configuration takes about five *minutes* with Magisk instead of SuperSU, and it totally locks AdGuard up:

![screenshot_20171006-185234](https://user-images.githubusercontent.com/29067983/31302660-28f82c46-aac9-11e7-8708-68c833947dc5.png)

![screenshot_20171006-185244](https://user-images.githubusercontent.com/29067983/31302662-2c12f2b2-aac9-11e7-9dd1-585cd34e3b19.png)

[adguard_logs_2.10.108_0610_1855.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1364143/adguard_logs_2.10.108_0610_1855.zip)

I suspect more and more people will migrate to Magisk now with Chainfire's official retirement from SuperSU, so please don't brush off! (Not that you guys would...the development and response from dev for this app is truly outstanding.)

**Comment by carlylemiii** [comment]
Few more details in https://github.com/AdguardTeam/AdguardForAndroid/issues/1516

**Comment by altokarev** [comment]
There is one more case with delayed start in the support. Ticket ID 1073779.

Galaxy Note 5(SM-N920C)@Android 7.0.

**Comment by nkartyshov** [comment]
@carlylemiii  We implemented a small hack for the MagiskSU.
Can you install the app and check start proxy?

The app with hack for the MagiskSU:
https://www.dropbox.com/s/kmo7h56tfs9ahwg/adguard-android.apk

**Comment by Revertron** [comment]
@carlylemiii We did another fix, can you test a new build?
https://www.dropbox.com/s/kyxahx9c4s0jd82/adguard-v2.10.126.apk

**Comment by carlylemiii** [comment]
@Revertron Yeah, I'll test later tonight. I'll need to re-root, as I migrated back to SuperSU, but I don't mind doing so.

**Comment by carlylemiii** [comment]
No improvement, at least not perceptively. Lots of "Adguard was granted superuser rights" toasts, as well.

https://www.dropbox.com/s/op8yb82bovdbyaj/adguard_logs_2.10.126_1210_2022.zip?dl=0

**Comment by ameshkov** [comment]
@carlylemiii what if you disable "clear youtube data"?

**Comment by ameshkov** [comment]
@carlylemiii one more build for you:)

https://uploads.adguard.com/up04_lqeb7_adguard_2.10.132.apk

Besides fixing the issue (hopefully) we've extended logging in proxy mode. So if it does not work again, could you please collect debug-level log?

**Comment by carlylemiii** [comment]
Will do!

**Comment by carlylemiii** [comment]
Hmm. So I thought to give the device time to "warm up" so to speak, and waited about five minutes till after boot to enable protection. Protection started immediately. That was with autostart not enabled.

Then, set it autostart, restarted my phone, entered my PIN, and let it do its thing. That log is attached.

It was about two minutes (from my watching the clock, not looking at my logs) after the AdGuard protection starting notification appeared that AdGuard first requested SU permissions. Then four more times, so five times altogether, and about three minutes altogether for protection to start.

Lastly, once protection finally starts, I can disable and re-enable protection and it does so immediately. It's just that initial start-up.

[adguard_logs_2.10.132_1310_1713.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1384140/adguard_logs_2.10.132_1310_1713.zip)

**Comment by ameshkov** [comment]
Hm, that's it, something is not okay on the device boot (and that's when we were able to reproduce it on our side).

**Comment by ameshkov** [comment]
However, it now starts okay on our device:)

**Comment by carlylemiii** [comment]
So is this a Magisk issue? Did you try with a Pixel? (I believe you have one?)

**Comment by ameshkov** [comment]
No, it's not rooted, we were testing on 6P

**Comment by ameshkov** [comment]
I think I understand what's going on. AG tries to start protection *before" boot event is sent by OS, so Magisk is not fully initialized at that moment.

**Comment by ameshkov** [comment]
Actually, although the first start was rather slow, nothing really bad this time.

`17:10:51.258` -- started
`17:10:52.970` -- loaded all the rules and finished with building the filtering engine. This process takes some time the first time
`17:10:53.276` -- finished initializing https filtering configuration (loads certs, etc)
`17:11:25.937` -- finished initial root access request, as I understand, Magisk initialization takes place here
`17:11:49.302` -- finished setting up all the iptables rules

**Comment by carlylemiii** [comment]
I believe somewhere around 17:08:XX would have been when I first saw the notification. I'm going off memory, at this point, but the request for root access happened about two minutes after the AdGuard notification first appeared. Do the logs not reflect anything sooner than 17:10:51.258?

**Comment by ameshkov** [comment]
Yeah, you're right

`17:08:21.600` -- AG checks root access the very first time and it takes forever
`17:10:51.123` -- finished that first check

**Comment by ameshkov** [comment]
Let's try again, I'll remove that unnecessary initial check.

**Comment by ameshkov** [comment]
Here you are:
https://uploads.adguard.com/up04_4c2x2_adguard_2.10.133.apk

**Comment by carlylemiii** [comment]
From watching my phone's clock:

~19:00 - device boot
~19:02 - AdGuard notification first appears
~19:07 - Android message that AdGuard is not responding, asks to wait or close (I click wait)
~19:08 - AdGuard is granted root permissions
~19:09 - granted again
~19:10 - granted three more times
~19:11 - AdGuard protection has successfully started

[adguard_logs_2.10.133_1310_1913.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1384264/adguard_logs_2.10.133_1310_1913.zip)

**Comment by ameshkov** [comment]
```
19:03:02.390 [pool-2-thread-1] DEBUG com.adguard.android.g.c - Checking for the root access
19:08:23.424 [pool-2-thread-1] DEBUG com.adguard.android.c.h - Command result 14.2:MAGISKSU (topjohnwu), uid=0(root) gid=0(root) groups=0(root) context=u:r:su:s0
```

Initial root access check takes 5 minutes :(

**Comment by ameshkov** [comment]
@carlylemiii there's a low-level flag "pref.boot.startup.delay", could you please try setting it to something huge (120000 for instance)?

**Comment by ameshkov** [comment]
@carlylemiii aaand one more build:)

https://uploads.adguard.com/up04_a4jmx_adguard_2.10.135.apk

I've changed a bit the part of code responsible for requesting root access. If it does not help, please let me know what exact version of Magisk Manager do you use. Root access request goes through it, so it may be that we'll be able to reproduce it if we have exact same versions of magisk AND manager.

**Comment by carlylemiii** [comment]
Do you want me to test in conjunction with that low-level flag or separately?

**Comment by ameshkov** [comment]
> Do you want me to test in conjunction with that low-level flag or separately?

Separately would be better

**Comment by carlylemiii** [comment]
Seems better.

8:17-8:18 boot
almost 8:19 AdGuard notification appears
8:20 all background apps loaded
8:20 kernel manager and AdGuard first granted su permissions
8:21-22 AdGuard three more times granted, then starts

So given the time frame that everything else starts up in, I think this is maybe acceptable? At least to me. Since the kernel manager gets permission the same time, it does not seem like AdGuard is doing anything bad. There was also never any Android system dialog telling me AdGuard wasn't responding, so that's good.

For reference, I'm now on 14.3 Magisk w/ 5.4.0 for Magisk Manager.

https://www.dropbox.com/s/qw7iegqgbcsdwsj/adguard_logs_2.10.135_1510_0822.zip?dl=0

**Comment by ameshkov** [comment]
Yay!

**Comment by ameshkov** [comment]
Yes, seems to be resolved

**Comment by ameshkov** [comment]
We have another problem now, though. The command we've tried to execute was required to detect if it's magisk or not.

According to the log command now takes ~1 minute when it's executed for the first time:
```
08:18:58.932 [pool-2-thread-1] DEBUG com.adguard.android.g.c - Trying to check for the root access
08:21:07.705 [pool-2-thread-1] DEBUG com.adguard.android.c.h - Command output: uid=0(root) gid=0(root) groups=0(root) context=u:r:su:s0
```

**Comment by ameshkov** [comment]
I'll try to change the way we do this check, maybe it'll help

**Comment by ameshkov** [comment]
@carlylemiii here you are:
https://uploads.adguard.com/up04_vqefj_adguard_2.10.136.apk

In this new build I returned the root type check but changed it a bit, and I hope it won't mess with magisk anymore.

**Comment by carlylemiii** [comment]
Here are logs. I did it twice just for fun, to see if using the "Hide Magisk Manager" option causes any more trouble. The earlier log is normal, the later is with Magisk Manager hidden.

https://www.dropbox.com/s/rqwf6m296n2z5ef/adguard_logs_2.10.136_1510_1138.zip?dl=0

https://www.dropbox.com/s/2i0578ak479a7m9/adguard_logs_2.10.136_1510_1142.zip?dl=0

**Comment by ameshkov** [comment]
Great, seems to be resolved finally.

Initial root check after the device boot seems to be quite slow, but I guess this is how Magisk works.

**Comment by ameshkov** [comment]
Just for the future readers: the issue seems to have been caused by executing `su -v` under `su`. 

No idea why tho, maybe some unexpected loop inside of Magisk manager.
