### ISSUE TITLE
Add "Firefox Rocket" to the known browsers list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1528]
http://www.androidpolice.com/2017/10/09/mozilla-testing-another-new-browser-called-firefox-rocket-specifically-indonesia/

Also check if it has network security config.

**Comment by TPS** [comment]
https://play.google.com/store/apps/details?id=org.mozilla.rocket

----
Apparently, Firefox Focus nor Klar are included, either!  Could they be added, along w/ Rocket?
https://play.google.com/store/apps/details?id=org.mozilla.klar
https://play.google.com/store/apps/details?id=org.mozilla.focus

**Comment by ameshkov** [comment]
> Apparently, neither Firefox Focus nor Klar are included, either! Could they be added, along w/ Rocket?

Focus is on the list, but we've missed klar. Why would they give it another package name? :(

**Comment by TPS** [comment]
I think Klar is only EU or Germany (& F-droid 😉), to comply w/ default usage data sending: Klar is default off, Focus is default on.

It's the only notable difference _I_ found, anyway.

**Comment by nkartyshov** [comment]
added
