### ISSUE TITLE
Adguard cannot update filters if Magisk Xposed is enabled.

### ISSUE THREAD

**Issue by redirectr00t** [AdguardTeam/AdguardForAndroid#1529]
Install this through recovery:

https://forum.xda-developers.com/xposed/unofficial-systemless-xposed-t3388268

Adguard for Android is not able to update filter lists in any build, to solve the issue is necessary to disable the module and reboot.

**Comment by ameshkov** [comment]
@redirectr00t 

Is it still so on v2.10.176?

**Comment by ameshkov** [comment]
Reopend if there's any new info

**Comment by redirectr00t** [comment]
Is fixed, not occur anymore.

**Comment by ameshkov** [comment]
Thank you!
