### ISSUE TITLE
Compatibility issue with MEGA app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1531]
https://play.google.com/store/apps/details?id=mega.privacy.android.app

Can't log in with HTTPS filtering enabled

Full log:
[adguard.log](https://github.com/AdguardTeam/AdguardForAndroid/files/1381990/adguard.log)

<details>

![image](https://user-images.githubusercontent.com/8361299/31538826-6f0c4cd0-b00f-11e7-8d3d-c8e2b7e5be07.png)
</details>

**Comment by nkartyshov** [comment]
done
