### ISSUE TITLE
DNS filtering does't work in autoproxy mode + IPv6 system DNS

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1533]
### Steps to reproduce

1. in Advanced settings - Local HTTP Proxy enabled in automatic mode
2.  DNS filtering enabled, any custom DNS server is chosen

### Expected behavior
domains are processed by DNS in filtering log. 

### Actual behavior
no domains processed by DNS in filtering log, statistics doesn't change. 

<details><summary>logs</summary>

[adguard_logs_2.10.126_1310_1552.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1382724/adguard_logs_2.10.126_1310_1552.zip)

</details>

### Your environment

* Adguard version: 2.10.126
* Adguard filtering mode:  Proxy(auto)
* Operating system and version: andoid 5,6,7
* Rooted

**Comment by ameshkov** [comment]
Isn't it a duplicate?

**Comment by sfionov** [comment]
#1354 will probably fix this but for now another workaround could be found IMHO

**Comment by zebrum** [comment]
reproduced on mobile connection also

**Comment by ameshkov** [comment]
It does not matter, what matters is what DNS servers are set in your system settings

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/AdguardForAndroid/issues/1354
