### ISSUE TITLE
cannot connect to corporate email server (exchange)

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#1534]
hello,

I'm having trouble connecting to my corporate email server (exchange) through aquamail for example,

I had to disable ad-blocking for aquamail in order to connect to it,
so it seems that something in adguard should be blocking it,

any suggestions? 

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 2.10
* Adguard filtering mode: VPN / Proxy(manual/auto) proxy (auto)
* Device model: (e.g. Google Pixel) moto e & lg g2
* Operating system and version (e.g. Android 7.1.2) kitkat (4.4)
* Rooted or not? rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? no

**Comment by ameshkov** [comment]
> I had to disable ad-blocking for aquamail in order to connect to it,

Have you tried disabling HTTPS filtering for it?

**Comment by patrickdrd** [comment]
correct, disabling https works, but is this the recommended solution?
what if my email client includes ads/tracking etc.?
for example, aquamail included flurry in its latest version,
is it sure that they're not https?

p.s. add another issue: I cannot understand why the app has to restart after **exporting** the settings,
with the message "settings were applied successfully" ??? 
I repeat: I did not import settings, I export them!

**Comment by Revertron** [comment]
@patrickdrd The restart was fixed, it will go to the next RC.

**Comment by patrickdrd** [comment]
alright, thanks!

any info on corporate accounts then? is this issue generic? I mean, does it happen for everyone else and
in order to use adguard we have to disable https filtering for our email clients when we have corporate accounts in them?

**Comment by patrickdrd** [comment]
not only aquamail, I guess this applies to all email clients that support exchange,
e.g. I should disable https filtering to type/bluemail as well
(even though I don't use this one as much)

thanks!

**Comment by patrickdrd** [comment]
a better idea is adding the company's server to https filtering (by the way this text popup needs a better interface) as discussed here:
https://forum.adguard.com/index.php?threads/cannot-connect-to-corporate-email-server-exchange.26017/

**Comment by carlylemiii** [comment]
> any info on corporate accounts then? is this issue generic? I mean, does it happen for everyone else and in order to use adguard we have to disable https filtering for our email clients when we have corporate accounts in them?

> I guess this applies to all email clients that support exchange,

I don't have HTTPS filtering disabled for Nine. No issues for me in the past year+ that I've been using AdGuard.
