### ISSUE TITLE
filter log to show only blocked requests?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#1535]
I think showing only blocked requests in the filter would be nice,
giving us the option to show everything and only that results in too much clutter

**Comment by lancelot-moon** [comment]
No, that's bad.
You don't understand that filtering log helps to find missed ad domains.

**Comment by patrickdrd** [comment]
ok then, an option should be added for both, like a filter, as discussed here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1369

**Comment by Bohdan-SUP** [comment]
User 1553302 suggested the following:
> display blocked events, dns events or all events

**Comment by clementine123** [comment]
I too believe that the filtering log should show each and every request and not just the blocked entries. Please do not remove this useful feature.

**Comment by FlyPigsFly** [comment]
I wanted to throw my comment out here about this feature request and to clear up a misunderstanding with an earlier comment.

The filtering log should always show all events.

The request though is to have the ability to "filter the filter." If I had the ability to filter the filter I could easily...

1.) Set filter to show blocked requests only. This makes it easier to discover a rule that blocked a request and is blocking content that is a false positive or user wanted content.

2.) Set filter to show allowed requests. If I'm seeking out content to block, showing allowed requests only helps narrow down the specific request or content I want to block.

3.) Show DNS requests only. Sometimes other users and I are only interested in DNS requests. Sure you can see the domains pulling content but narrowing it down to DNS requests only is a lot shorter list then showing all requests.

Filtering log should contain a drop down menu with options "Blocked, Allowed or DNS." People have also requested to sort by applications and their requests. That could be quite cumbersome to list every app in a drop down menu. So maybe we could add a search function instead. "+Blocked" keyword to show blocked events and "Blocked" keyword to show events for an application name 'Blocked' if the user has that named application installed. "+" To help differentiate between showing block requests and requests from application blocked rather then both.

**Comment by Nzzyme** [comment]
Yes, an excellent idea.

**Comment by lancelot-moon** [comment]
@ameshkov 
When will I want the log to only show blocked requests?
For making custom rules for solving anti-adblock, I will only check blocked requests.
But I operate this in the more powerful log of AdGuard for Windows.

However, your suggestions are good!

The under are my thought for the log.
Divide now Filtering log to HTTP(S) Requests Log and DNS Requests Log.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1706

In AdGuard Pro for iOS, the DNS Requests of trackers and analytics according to Disconnect database are shown by bright red (but I suggested to use dull yellow).
https://github.com/AdguardTeam/AdguardForiOS/issues/620

In AdGuard for Android, the background of allowed requests are green, and the background of blocked requests are red.
I don't know if AdGuard team will let the background of DNS Requests of trackers and analytics be shown by another color in AdGuard for Android, such like what in AdGuard Pro for iOS...
(I think they can also let the background of DNS Requests of trackers and analytics be shown by yellow if they realize the feature in AdGuard for Android.)

Well, just some suggestions for the improvement for now log from different users.
Maybe AdGuard team can try to listen users' voice.

**Comment by ameshkov** [comment]
Possible in the current version
