### ISSUE TITLE
[Feature Request/Help] Create a simple Magisk module to install HTTPS cert to system store

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1539]
Hi!

In order to streamline cert installation to the system store, I wanted to explore using Magisk Mount to do this automatically using a Magisk template (https://github.com/topjohnwu/magisk-module-template). This so that it's done without mounting system r/w, trying to tiptoe around SafetyNet, etc. And it will also make installing the cert after system updates easier.

I tried doing that myself (my cert is not in the actual system/etc/security/cacerts folder in this ZIP, for purposes of GitHub):

[Magisk-AdGuard-CACert-Template-carlylemiii.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1389313/Magisk-AdGuard-CACert-Template-carlylemiii.zip)

The ZIP installs in Magisk just fine, and upon reboot, I can see my AdGuard Personal CA under Trusted credentials (System) in Android settings, and my cert appears to be in the right place when I look for it in a file manager (including 0644 permissions). But I go into AdGuard HTTPS settings, and it tells me that the cert is not installed.

So, I guess this "issue" is twofold:

1) It would be wicked sweet if AdGuard made/maintained a proper module instead of my hackjob (by maintained, I mean there would have to be some basic instructions for users needing to put their own crt in the ZIP, and occasionally template updates are made for new versions of Magisk, so eventually the same ZIP would no longer work)
2) I'm not sure if there's something with AdGuard that needs changed to handle the cert being installed by means of Magic Mount?

**Comment by ameshkov** [comment]
Hm, but what's wrong with the `Move Cert` app approach? It seems to be working and it does not depend on a specific root app.

**Comment by carlylemiii** [comment]
D'oh! The last time I tried Move Certs was before there was official Pixel support for Magisk. I had been using Move Certs with SuperSU but continued assuming it did not work with Magisk. I abandon this idea unless in the future it truly becomes incompatible.

Carry on... (I am shaking my head at myself for all that work ha ha). :-)

**Comment by carlylemiii** [comment]
One question, barely related, but not worth an issue:

Why does AdGuard not recognize the cert as being installed into system if the device isn't rooted? e.g., if you push it there via TWRP, or do it while rooted and then un-root. Not a realistic case, really, but I'm just curious.

**Comment by ameshkov** [comment]
It does not even try to check it if there's no root:
```
        if (LiteRootUtils.isRooted()) {
            LOG.info("Checking if our certificate is installed to system store");
            boolean installedToSystemStorage = isCertificateInstalledToSystemStorage(rootCertKeyPair);
```

**Comment by ameshkov** [comment]
There's no specific reason for it, it's just the probability is too low:)
