### ISSUE TITLE
question about filters coverage

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#1540]
I've got checked
"english filter, spyware filter, social media filter, annoyances filter, mobile ads filter"

(I don't use dns filtering),

do I need "simplified domain names filter" or everything is included in the above filters?

I can see simplified includes easylist and easyprivacy, are these included in the other filters?

thanks

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? 
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by ameshkov** [comment]
> do I need "simplified domain names filter" or everything is included in the above filters?

Not really, those are enough.  SDNF is supposed to be used for DNS-level blocking mostly.

> I can see simplified includes easylist and easyprivacy, are these included in the other filters?

English filter is a fork of EasyList.
EasyPrivacy is not included, Spyware filter is what we maintain.
