### ISSUE TITLE
Connection Issue with HTTPS filtering enabled for Jodel

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1544]
Not sure if it's just something that needs to be unblocked or if it's SSL filtering in its entirety.

App is https://play.google.com/store/apps/details?id=com.tellm.android.app&hl=en

![screenshot_20171017-014246](https://user-images.githubusercontent.com/29067983/31675551-9fae3ba0-b32a-11e7-85ba-98172a41ca6f.png)

[adguard_logs_2.10.136_1710_0143.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1391688/adguard_logs_2.10.136_1710_0143.zip)

Also curious about this request, if it's in the log itself and there's more detail available. Looks like something I'd expect to be blocked, but maybe the domain and request URL are misleading to me, the layman:

![screenshot_20171017-014404](https://user-images.githubusercontent.com/29067983/31675615-c57ce71e-b32a-11e7-94fa-d4154830478d.png)

**Comment by vozersky** [comment]
does it help if you disable all the filters (but protection is still on)?

**Comment by carlylemiii** [comment]
Nope.

**Comment by nkartyshov** [comment]
done
