### ISSUE TITLE
Wakelock (caused by GCM_RECONNECT) prevents devices from sleeping

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#1547]
well, I noticed (after a couple of days of usage) that AG is draining my battery and downloading data in the background when phone is supposed to be sleeping.
At first I wasn't sure it was AG, so I started with unistalling all recent apps I installed and came to the conclusion that AG was the culprit and I've already applied for a refund.
I use BetterBatteryStats for my battery monitoring, cleaning battery stats (from android settings) before each run and I found out that even in the "lightest" configuration (block ads only in browsers and simplified mode), AG still wakes up my phone,
here are the relevant screenshots:
https://i.imgur.com/HwCP1Yd.png
https://i.imgur.com/9VRSsPD.png

When I uninstalled AG, all these wakelocks (I'm referring to the ones with screen off) were gone!

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: VPN / Proxy(manual/auto): proxy (auto)
* Device model: (e.g. Google Pixel) Moto E/ Lg g2
* Operating system and version (e.g. Android 7.1.2) Kitkat
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? no

**Comment by ameshkov** [comment]
The only suspicious thing I see is KitKat didn't have Doze and it might be related.

@vozersky could you plz try reproducing it on a KitKat device + AG in proxy mode?

**Comment by patrickdrd** [comment]
I'm trying VPN now and it seems a bit better so far at least

**Comment by ameshkov** [comment]
And that's really weird, VPN has more limitations on KitKat -- you cannot truly disable filtering for an app (it's supported since Lollipop).

**Comment by ameshkov** [comment]
On the other hand, there's a difference in how VPN works, it's less likely to cause any compatibility issues.

**Comment by patrickdrd** [comment]
nope, seemed better, but still enough wakelocks, uninstalled again

**Comment by patrickdrd** [comment]
since uninstalling I completed one quarter of an hour without any wakelock, which was impossible with AG, amazing!

**Comment by patrickdrd** [comment]
@ameshkov I could use greenify to hibernate AG, would it help?

**Comment by ameshkov** [comment]
Relevant:
https://forum.xda-developers.com/showpost.php?p=74329111&postcount=2824

@patrickdrd wait a bit till we do the tests on our side.

**Comment by ameshkov** [comment]
@Revertron here are battery stats and logs with the issue reproduced:
[adguard_logs_2.10.155_0911_2256.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1477852/adguard_logs_2.10.155_0911_2256.zip)
[Battery.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1477853/Battery.zip)

@vozersky we still need to collect more info. Here is the instruction you can use: http://4pda.ru/forum/index.php?showtopic=601691&st=10540#entry66773541

**Comment by ameshkov** [comment]
Tons of GCM_RECONNECT intents in the battery stats are caused by small idle connection TTL (30 seconds at the moment).

What should we do:
1. @sfionov  please fix the connection TTL issue, local TCP stack must not impose any restrictions on it and just repeat after endpoints.
2. @Revertron start using the updated CoreLibs once it is available.

**Comment by ameshkov** [comment]
Wakelocks stats:
https://gist.github.com/ameshkov/ceede41202c76c0b9452a73599b63ea2

Quick analysis: every `GCM_RECONNECT` was causing additional `GCM_READ`, `net_scheduler` and `com.whatsapp.gcm.RegistrationIntentService:launch`.

However, it is not the same as reported on xda, I will open additional issue for that one: https://github.com/AdguardTeam/AdguardForAndroid/issues/1592
