### ISSUE TITLE
Adaptive icon support

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1548]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by altokarev** [comment]
Ticket ID 1668746 also requested such a feature.

**Comment by nkartyshov** [comment]
Testing instructions: 
1. Install Adguard on device with Android Oreo (8+)

Expected result:
The AdGuard app icon should have the same icon style as the other apps

**Comment by ameshkov** [comment]
Please check why icon is blurred on Redmi 4X
