### ISSUE TITLE
Yandex.Transoprt did not work with AdGuard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1549]
Original issue
https://github.com/AdguardTeam/AdguardFilters/issues/7144

Reproduced on Android 5.1.1, HTTPS filtering is enabled, all filters  are disabled.
Full log:
[adguard.log](https://github.com/AdguardTeam/AdguardFilters/files/1398064/adguard.log)
[dnscrypt.log](https://github.com/AdguardTeam/AdguardFilters/files/1398065/dnscrypt.log)

**Comment by Alex-302** [comment]
[adguard_no-dns_https-off.log](https://github.com/AdguardTeam/AdguardForAndroid/files/1399098/adguard_no-dns_https-off.log)
[adguard_no-dns_https-on.log](https://github.com/AdguardTeam/AdguardForAndroid/files/1399099/adguard_no-dns_https-on.log)

**Comment by ameshkov** [comment]
Guys, this one is important

**Comment by Alex-302** [comment]
No one can reproduce it. The logs are mine.
Original issue
https://github.com/AdguardTeam/AdguardFilters/issues/7144

**Comment by ameshkov** [comment]
There was an issue in v2.9

**Comment by nkartyshov** [comment]
I cannot find problem with the domain `spdy3.maps.rostaxi.org` in the user logs.
This domain was added to the whitelist in 2.9 RC2

**Comment by ameshkov** [comment]
Maybe the user has edited the whitelist, it will explain why his whitelist differs from the default one.

@Alex-302 just ask him to reset settings to default.
