### ISSUE TITLE
Update Adguard's privacy policy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#155]
https://adguard.com/en/privacy.html#android

1. Device name (when you do license check) is in fact a concatenation of device manufacturer name and device model name.
2. Why "Contact support"? It is "Send Feedback"
3. Missed some important properties being sent when user contacts support:
3.1. Device name (the same as in point 1)
3.2. Android kernel version
4. Google Play purchase ID (if any). Should be replaced with "Amazon purchase ID"

Also russian translation is wrong.

**Comment by ameshkov** [comment]
One more thing about it:
When browsing security is enabled, Adguard periodically does a latency check for the list of browsing security servers. Look at #161 for example request.

Nothing is being sent in these requests, but anyway we should mention them.

**Comment by vbagirov** [comment]
All the changes are commited.
