### ISSUE TITLE
Multiple proxies, DNS on the main screen

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#1550]
Hi there Adguard! I have two requests hopefully you will consider
implementing.
1) multiple proxies instead of just one default. 
2) Like what you did with moving DNS to the main screen with app management
and log. Maybe proxy would make sense to be there all

Ticket ID:  1532279

**Comment by ameshkov** [comment]
1. Could you please elaborate on this one? We allow having multiple proxies added in the "proxy settings".

2. Yeah, it's possible indeed, we just haven't decided yet.

**Comment by computer777** [comment]
Sure,
A user on your forum pointed out though, that this probably wouldn't be ideal for adguard.
But,anyway, since you have proxying as an option is there a possibility you guys would take it a step further and introduce proxy chaining into your app?

**Comment by TPS** [comment]
Isn't this accomplished via #51?

**Comment by ameshkov** [comment]
@computer777 sorry for the late reply. I might be misunderstanding again, but in my understanding what "outbound proxy settings" provide IS proxy chaining as you can set up an upstream proxy.

**Comment by computer777** [comment]
Please close.
