### ISSUE TITLE
Snapchat is not compatible with AdGuard HTTPS filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1553]
> Snapchat will not send or receive chat, at random on different networks. the recent updates didn't fix it, but as disabling adguard fixed it. ID: 1647276, HTTPS in Whitelist mode, 2.10.108" release

I could not find the app [here](https://github.com/AdguardTeam/HttpsExclusions/blob/master/android.txt) but it's been mentioned in the discussion https://github.com/AdguardTeam/AdguardForAndroid/issues/469, is it already in the exceptions? If so, where it can be found?

**Comment by ameshkov** [comment]
Yeah, it is in the default list of exceptions already

**Comment by evgeniy-ADG** [comment]
Where can I see that list, is it available here, on GitHub?

**Comment by ameshkov** [comment]
Nope. The only way is to check the "enabled" option value after the app clean install.
