### ISSUE TITLE
[feature request] Block video ads in Official YouTube App

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#1555]
### Steps to reproduce
1. Install and Open Official YouTube App 
https://play.google.com/store/apps/details?id=com.google.android.youtube
2. You will see random Ads post videos links.

### Expected behavior
Ads  should be blocked - removed.

### Actual behavior
Ads with videos are listed.

### Your environment
* Adguard version: 2.10.108 (Premium)
* Adguard filtering mode: VPN + DNS (DNScrypt: openDNS)
* Device model: Samsung Galaxy J5 2017 (SM-J530F)
* Operating system and version: Android 7.0 Official (not rooted)

**Comment by ameshkov** [comment]
> Operating system and version: Android 7.0 Official (not rooted)

https://blog.adguard.com/en/android-nougat-release-and-what-does-it-mean-for-adguard-users/

Unfortunately, that's not possible.

**Comment by FadeMind** [comment]
@ameshkov thanks for explanation. Regards.
