### ISSUE TITLE
Alisa is broken in Yandex.Browser alpha

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1557]
Browser build with Alisa:
http://4pda.ru/forum/index.php?showtopic=473341&st=4720#entry66220094

I guess we should add a new domain to the HTTPS exclusions.

**Comment by nkartyshov** [comment]
I cannot reproduce. Alisa use domain `wss://voiseservices.yandex.net/uni.ws`, but AdGuard do not blocking this domain.

**Comment by nkartyshov** [comment]
Original thread: http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=66221920

**Comment by ameshkov** [comment]
@nkartyshov just add `voiseservices.yandex.net` to the HTTPS exclusions just in case.

**Comment by nkartyshov** [comment]
Added https://github.com/AdguardTeam/HttpsExclusions/commit/eca56d4ea0fb7bba3364d68f5999da04d96211c1
