### ISSUE TITLE
Internet is not working after switching from Local HTTP proxy(root) to VPN

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1558]
### Steps to reproduce

1. Setup Local HTTP proxy(auto, root)
2. Check Internet - it works
3. Switch to VPN
4. Check Internet - it does not work.

AdGuard 2.10.142, Android 5.1.1
Full log(Proxy, then VPN)
[adguard (3).log](https://github.com/AdguardTeam/AdguardForAndroid/files/1407192/adguard.3.log)

**Comment by vozersky** [comment]
@Alex-302 try updating the app to 2.10.150 pls, can't reproduce on 5.1.1

**Comment by Alex-302** [comment]
The same. It seems that AdGuard does not restore proxy settings after disabling protection.

**Comment by Revertron** [comment]
Fixed.

**Comment by nkartyshov** [comment]
The same problem on Nexus 5 with Lollipop

**Comment by nkartyshov** [comment]
fixed
