### ISSUE TITLE
[Features Request] SNI Encryption Support

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardForAndroid#1559]
For enhanced privacy and security can you please add encrypted SNI (Server Name Indication) support.
Thanks

**Comment by Revertron** [comment]
Eventually, after the servers will support it, we will support it :)

**Comment by zero77** [comment]
@Revertron 
What about adding proxy support or something along those lines.

**Comment by Revertron** [comment]
We already have proxy and Tor support.

**Comment by zero77** [comment]
Can you use a proxy or Tor at the same time as the adguard vpn.

**Comment by Revertron** [comment]
Sure.

**Comment by ameshkov** [comment]
The SNI encryption is a highly debatable topic. There is a guy who files the SNI encryption draft and it's been rejected all the time. The thing is that there's no way to completely hide the SNI, it defeats its purpose. The proposed "fronting service" solution means more complicated infrastructure and does not actually let you get rid of the plain SNI, just mitigates it.

**Comment by ameshkov** [comment]
To sum it up, there is no specification of the SNI encryption, just a single draft, which is rather debatable.
