### ISSUE TITLE
https ошибка при загрузке скрипта

### ISSUE THREAD

**Issue by sergii333** [AdguardTeam/AdguardForAndroid#1560]
При включении https в настройках, режет этот скрипт <script language="Javascript" src="http://script.pravoslavie.ru/icon.php"></script>
отсюда http://days.pravoslavie.ru/script/icon.htm

кэш обязательно чистить и вкл/выкл AG

при выключении https нормально показывает скрипт...

видео https://yadi.sk/mail/?hash=L3yqZHktoMhOwggirij%2BcX6a2KxAt6Z2aSSvtJYUwjg%3D&uid=23077022

сам скрипт в кириллице, https://script.pravoslavie.ru/cache_icon/advanced=1.ls
если в utf не режет...

для теста http://profi-rus.narod.ru/share42/days.html

**Comment by Revertron** [comment]
Значит и православию пора выходить из тёмных веков и научиться работать с UTF-8.

**Comment by sergii333** [comment]
Все равно AG режет, если добавить UTF <script language="Javascript" src="http://script.days.ru/icon.php?advanced=1&encoding=u"></script>
