### ISSUE TITLE
Start using Notification Channels

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1561]
I'm not sure all what use cases there are, but a good one I see is 

1) General AdGuard notification

2) AdGuard updates notification

With Notification Channels in Oreo, one could block 1) to tidy up notifications but allow 2) so the user knows when an update exists

I'm sure there would be other good uses but that's what I came up with :-)

**Comment by ameshkov** [comment]
My thoughts on possible channels:

`Control notifications` -- the main notification, outbound proxy notification
`Firewall notifications` -- when we finally make it work on Android N+
`General notifications` -- updates, what else?

**Comment by Revertron** [comment]
I think there is no need to differentiate our notifications.

**Comment by ameshkov** [comment]
> I think there is no need to differentiate our notifications.

Why? As I understand, this is the only way for people to have the permanent notification hidden without hiding other notifications.

**Comment by ameshkov** [comment]
In light of #1618 we might need to start using notification channels sooner or later.

Unfortunately, it requires targeting Oreo, and I'd better postpone it -- it'll bring quite a lot of issues caused by the new behavior towards foreground services.

**Comment by sviperz** [comment]
> In light of #1618 we might need to start using notification channels sooner or later.

So, are there any solutions available now on Oreo+ versions of Android to have notification _without_ status bar icon? Right now the notification is also showing on the lock screen which is undesirable behavior to be honest.

Sorry for asking this here, but #1618 is closed.

**Comment by carlylemiii** [comment]
Just set "On the lock screen" to be "Don't show notifications at all" for AdGuard.

**Comment by carlylemiii** [comment]
And for hiding the status bar icon, set AdGuard to Notification without icon.

**Comment by sviperz** [comment]
> Just set "On the lock screen" to be "Don't show notifications at all" for AdGuard.

Of course, thanks.

> And for hiding the status bar icon, set AdGuard to Notification without icon.

Yes, this option is available, but not a good solution for any app, since Android can stop AdGuard any time. Still, seems like the only option we have at the moment.

**Comment by carlylemiii** [comment]
> Yes, this option is available, but not a good solution for any app, since Android can stop AdGuard any time. Still, seems like the only option we have at the moment.

I think that's more an issue if you select "None" (and AdGuard even gives you a warning regarding that). Over the course of three of four devices and ≥Nougat (maybe Marshmallow? Idr what the S7 shipped with, which is when I started using AdGuard), I've never had AdGuard stop on me with having the low-priority notification.

**Comment by sviperz** [comment]
> And for hiding the status bar icon, set AdGuard to Notification without icon.

Well, that's exactly what was discussed in #1618 - _Notification without icon_ option doesn't work as expected on Oreo+ Android. There is still a permanent icon in the status bar with this option.

**Comment by carlylemiii** [comment]
@sviperz there's also a workaround mentioned there, though, which is still functional as of the March security update, so it hasn't been removed yet, as @ameshkov suggested might happen. For the time being, you should be able to accomplish what you're looking to do.

**Comment by sviperz** [comment]
@carlylemiii fair enough. Works even without reboot. But hopefully you guys will start targeting SDK level 26 and all its features like notification channels at least in the foreseeable future.

**Comment by sviperz** [comment]
BTW, Google will require targeting recent API level for all new and updated apps later this year - https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

> In order to provide users with the best Android experience possible, the Google Play Console will require that apps target a recent API level:
> 
> - **August 2018:** New apps required to target API level 26 (Android 8.0) or higher.
> - **November 2018:** Updates to existing apps required to target API level 26 or higher.
> - **2019 onwards:** Each year the targetSdkVersion requirement will advance. Within one year following each Android dessert release, new apps and app updates will need to target the corresponding API level or higher.

So, seems like moving forward is inevitable.

**Comment by carlylemiii** [comment]
@sviperz, AdGuard is not on the Google Play Store.

**Comment by sviperz** [comment]
Oh, well, that's true. And now that's all, I have nothing else as arguments, you won) Anyway, finger crossed you guys find your way to evolve.

**Comment by carlylemiii** [comment]
I want to see it happen too - I opened this issue, and I'm not on the AdGuard team!

**Comment by admitrevskiy** [comment]
More issues we should solve to targeting Android P:

1) Start using ContextCompat.startForegroundService(Context context, Intent intent) for services that are necessary to work in the foreground.

2) According to this we should replace IntentServices by JobInentServices:
https://developer.android.com/about/versions/oreo/background#services

3)The ANR dialogue appears when something is preventing the main UI thread from responding.
When this happens in Android Oreo or below, the ANR dialogue is shown to the user to let them know.
Now, in Android P, the application will just crash without any kind of notification for the user.

4) Moreover we have to increase targetSdk for Content Blocker: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html
