### ISSUE TITLE
Restart device = adguard for android not start automatically

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#1563]
### Steps to reproduce
1. **Restart device.** (Not Power Off)

### Expected behavior
Adguard will startup automatically with system.

### Actual behavior
Adguard need to be turned on manually.

### Your environment
* Adguard version: 2.10.108 (Premium)
* Adguard filtering mode: VPN + DNS (DNScrypt: openDNS)
* Device model: Samsung Galaxy J5 2017 (SM-J530F)
* Operating system and version: Android 7.0 Official (not rooted)

**Comment by ameshkov** [comment]
Could you please export & attach logs here? Settings -> Advanced -> Export Logs

**Comment by FadeMind** [comment]
@ameshkov here it is:
[adguard_logs_2.10.108_2510_1810.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1415316/adguard_logs_2.10.108_2510_1810.zip)

**Comment by vozersky** [comment]
@FadeMind how does 2.10.164 work? still reproducible?

**Comment by FadeMind** [comment]
@vozersky  2.10.164 works as expexted (for now). If issue will return I will feedback ASAP). 
For now > **RESOLVED/FIXED**
