### ISSUE TITLE
Filtering Log Not Cleared

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardForAndroid#1564]
### Expected behavior
Filtering log should be cleared when the delete icon is tapped.

### Actual behavior
At times, tapping the delete icon does not clear the filtering log.

I have made a video for your reference please view the video file at this page:

http://www.yourfilelink.com/get.php?fid=1426147

### Your environment
* Adguard version: 2.10.108
* Adguard filtering mode: VPN
* Device model: Xiaomi Redmi Note 3
* Operating system and version: MIUI Global 8.5 (Android 6.0.1 MMB29M)
* Rooted or not? Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NA

**Comment by clementine123** [comment]
Not sure what changed, but strangely I don't see this issue happen again. Maybe just a one off case. Will continue to monitor and report if reproduced again.

**Comment by vozersky** [comment]
@clementine123 thanks for the update, closed for now then
