### ISSUE TITLE
Disable secondary "Blocking ads and trackers"

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardForAndroid#1565]
can you add an option to disable secondary "blocking ads and trackers"
notification

### Customer ID 
1649503

**Comment by altokarev** [comment]
@iverkhohliad, secondary? Which one exactly?

Could you please provide us with a screenshot?

Thanks.

**Comment by iverkhohliad** [comment]
Asked user for a schreenshot. Awaiting for it.

**Comment by vozersky** [comment]
@iverkhohliad @altokarev 

![image](https://user-images.githubusercontent.com/17472907/32891583-2bb59154-cae4-11e7-956b-af48d144e904.png)

**Comment by vozersky** [comment]
you can disable it of course, 
`settings-> general -> notification icon -> none`
but it's better to keep it, since Android will reduce our priority and might kill our process without it
