### ISSUE TITLE
 Vodafone Calling in proxy+root mode

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardForAndroid#1566]
For me in proxy mode Vodafone WiFi Calling does not work.
No problem in VPN mode.

(Logs attached in the ticket)

### Customer ID 
1644026

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: Proxy
* Operating system and version (Android 7.0)

**Comment by ameshkov** [comment]
We need to figure out what IPv6 addresses Vodafone uses for Wi-Fi calling and exclude them by default.

Here's what we need from the user:

1. Install the latest nightly build: https://agrd.io/android_nightly
2. Go to settings -> advanced -> set logging level to "record everything"
3. Reproduce the issue
4. Go to settings -> advanced -> export logs

We will need this log file.

**Comment by vitbortnik** [comment]
logs available at ticket ID 1152540

**Comment by sfionov** [comment]
User has no `netmgrd`, so it is not easy to determine IPv6 prefix to exclude.

**Comment by ameshkov** [comment]
Any idea on what we can export to figure what's wrong?

**Comment by sfionov** [comment]
Seems that we need more info about network configuration of user's device.
At least, output of the following commands in `adb shell` is needed:
- `ip addr`
- `ip rule`
- `ip route`
- `ip -6 route`

**Comment by ameshkov** [comment]
@admitrevskiy need your help with this.

I suppose we need to write the output of these commands when the transparent proxy starts up.
Also, fix the line breaks in the iptables output.
