### ISSUE TITLE
bccard.com, local.gosi.go.kr are not accessible with the HTTPS filtering enabled 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1567]
https://github.com/AdguardTeam/AdguardFilters/issues/7221

**Comment by ameshkov** [comment]
Add them to HTTPS exclusions

**Comment by nkartyshov** [comment]
Added https://github.com/AdguardTeam/HttpsExclusions/commit/3a8219e8785d3a39e0f7bc435849455ebd5acc3e
