### ISSUE TITLE
Отсутствует экранная клавиатура в Edge

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardForAndroid#1569]
При активации фильтрации Adguard в браузере Microsoft Edge (https://play.google.com/apps/testing/com.microsoft.emmx/) перестает выскакивать клавиатура по нажатию на текстовые поля. Как пример, невозможно войти в свой аккаунт на сайте mobile.twitter.com или wp-seven.ru. При отключённом Adguard проблема не наблюдается.

[debug (6).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1422244/debug.6.txt)
Ошибка воспроизведена в 11.21.

### Customer ID 
1267493

### Your environment

* Adguard version: 2.10.142
* Adguard filtering mode: VPN
* Device model: HUAWEI VNS-L21
* Operating system and version: Android 7.0

**Comment by zebrum** [comment]
can not reproduce
@ashvets-sup ask user to update to 2.10.155

in General settings export settings in file and attach it here

**Comment by ADeerslayer** [comment]
I'm that user.
I have updated Adguard to the latest beta, but bug hasn't disappeared.
I changed the phone to Xiaomi Redmi Note 4 Qualcomm, tested the bug on MIUI 8 and MIUI 9. It appears everywhere.
Here's a file with settings.
[adguard_settings_2.10.155_3010_2003.json.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1428134/adguard_settings_2.10.155_3010_2003.json.txt)

**Comment by zebrum** [comment]
@ADeerslayer what keyboard do you use?

**Comment by ADeerslayer** [comment]
@zebrum Google Keyboard.
Version: 6.6.22.171938909, 20170915.

**Comment by ADeerslayer** [comment]
@zebrum I have just checked, Swiftkey keyboard also doesn't work properly.
Maybe, I need to add, that if I collapse Edge and then return to it, the keyboard begins to work, but only on the site, which is shown right now. If I switch to another site (without collapsing Edge), the bug will appear again.

**Comment by zebrum** [comment]
@ADeerslayer also update AdGuard to 2.10.155 please.

**Comment by ADeerslayer** [comment]
@zebrum I have already updated.

**Comment by zebrum** [comment]
add this rule to user filter and check again.

`@@||microsoft.com^$app=com.microsoft.emmx`

**Comment by ADeerslayer** [comment]
@zebrum Nothing changed.

**Comment by ADeerslayer** [comment]
The bug has been fixed by the latest update for Edge browser. You can close the issue.
