### ISSUE TITLE
Estonian build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#157]
Estonian translation is almost ready.

Could you please build a version with estonian language so that translator could check how is it?

Post the link to the apk here in comments.

**Comment by Revertron** [comment]
Done. The translation was added and will be updated as all others.

**Comment by ameshkov** [comment]
apk link?

**Comment by Revertron** [comment]
https://cdn.adguard.com/public/Adguard/Android/adguard-android-issue157.apk

**Comment by Laurisade** [comment]
Thanks!

**Comment by Laurisade** [comment]
I've installed it. However I do not see Estonian language in the language list. Could you check please?

**Comment by Revertron** [comment]
Give 5 minutes...

**Comment by Revertron** [comment]
https://cdn.adguard.com/public/Adguard/Android/adguard-android-issue157.apk?r=1
Our build system didn't include such recent commit :) Try this one.

**Comment by Laurisade** [comment]
Odd. Still can not find Estonian language there :/

**Comment by ameshkov** [comment]
@Revertron ?

**Comment by Revertron** [comment]
@Laurisade try this link:
https://cdn.adguard.com/public/Adguard/Android/adguard-android-issue157.apk?r=2
Tested well :)

**Comment by Laurisade** [comment]
Thanks :)!

**Comment by Laurisade** [comment]
I've updated the language file with some fixes here and there. If you could also update it in your end for new release then that would be great :)! 
Thanks for special build!

**Comment by ameshkov** [comment]
Done
