### ISSUE TITLE
Import of previously exported settings is buggy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1571]
It is very likely to be caused by proguard.

Problematic file (removed `key_https_ca_key`, license key info and proxies passwords from it though):
[adguard_settings_2.10.143_2810_1250.json.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1424783/adguard_settings_2.10.143_2810_1250.json.zip)

Problems (DNS=null, empty proxies list):
<details>

![2017-10-29 06 19 46](https://user-images.githubusercontent.com/5947035/32140442-30d0d44a-bc71-11e7-9b45-a70376360a9e.jpg)

![2017-10-29 06 19 51](https://user-images.githubusercontent.com/5947035/32140444-351c69c4-bc71-11e7-89d7-f6b8c943bbe7.jpg)
</details>

**What's also bothers me is that we allow importing invalid settings. It shouldn't work like that.**

This should be fixed before v2.10 patch release.

**Comment by nkartyshov** [comment]
I have fixed this problem in the version 2.10.150.

**Comment by ameshkov** [comment]
No, you did not I have reproduced it in v2.10.155.

**Comment by ameshkov** [comment]
Also you didn't address my comment in bold

**Comment by Revertron** [comment]
Okay, the import thing is not broken, as I have found right now.
The de/serializing of Proxy settings is broken by proguard. You can check it now - create some new proxy config. and try to backup settings. You will see obfuscated property names.

P.S.: Your test file is from a debug build, I think.

**Comment by Revertron** [comment]
Fixed, pull-request 189.
