### ISSUE TITLE
Update the apk signature

### ISSUE THREAD

**Issue by IzzySoft** [AdguardTeam/AdguardForAndroid#1575]
Just a note: MD5 is deprecated for signing. Here's a report from `apksigner` on the latest `.apk` from `releases/`:

    ERROR: JAR signer ADGUARD.RSA: Failed to verify JAR signature META-INF/ADGUARD.RSA against META-INF/ADGUARD.SF: java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5.

Nothing show-stopping, but often "deprecated" becomes "unsupported" shortly thereafter :wink:

**Comment by TPS** [comment]
@ameshkov I understand [updating the certificate "with APK signature scheme v2 and that are running on devices supporting the latest signature scheme (Android 7.0 and newer) are protected against" the recent Janus vuln.](https://www.guardsquare.com/en/blog/new-android-vulnerability-allows-attackers-modify-apps-without-affecting-their-signatures)  Maybe increase priority?

**Comment by IzzySoft** [comment]
Good point, @TPS – but the issue of the MD5 signature will still remain. As far as I understand the underlying cause it is the *signing key* using the deprecated MD5 algorithm. And unless someone comes up with a method to "upgrade" that key to something more recent and safe, this might be hard to solve – as replacing the key would make it impossible to seamlessly update to the first version using that key (signature check will fail).

I gladly learn differently, of course (i.e. that such a "key upgrade" would be possible).

**Comment by TPS** [comment]
@IzzySoft The best tutorial I've seen is https://guardianproject.info/2015/12/29/how-to-migrate-your-android-apps-signing-key/ .  I suppose (neglecting the Amazon Appstore version, for which I've no idea of the key requirements), AG might have it a touch _easier_ than most apps to update the key, since it's mostly self-distributed.

**Comment by IzzySoft** [comment]
@TPS Yes, I've seen that. But that actually migrates the app, not the signing key – which is why so many devs hesitate (the "next version" would have a new package name, which means effectively it's a different app; so not only the ratings are lost, but one also has to implement data migration). All not an issue if you simply add v2 signing with the same key (which is how I've interpreted your original comment above). And AFAIK you cannot use a different key for that – same issue, signature mismatch.

TL;DR: I've not heard there's any way to actually upgrade *the signing key* itself.

**Comment by TPS** [comment]
@IzzySoft I'm understanding you to say that upgrading the signing key per the OS or app distributor is what's difficult. I figure that's mostly irrelevant for AG, since they'll just workaround via newly signed app's setup.  (Again, I don't know how Amazon's handled.)

**Comment by IzzySoft** [comment]
What I'm saying is if you switch the signing key (the key the app is signed with), Android will not accept the next version as an update – so while AG currently uses the package name `com.adguard.android`, it could not do that with a new key (those already using AG couldn't update to that new version then). So the new version then would need a different package name, thus not be offered as update to those already using the current version. Or, alternatively, had first to uninstall the old version (losing its data/configuration) and then install the new one). All said in the GuardianProject article you've linked.

As for Amazon: Same as with all app stores/repositories, it probably wouldn't accept updates using a different signing key. I'm sure Playstore doesn't – but that's not an issue here as AG is not present there.

PS: Looks a bit strange if one upvotes (all) his own comments; if you'd disagree to a comment, you wouldn't post it in the first place, would you? :wink:

**Comment by TPS** [comment]
AG has fully functional import/export of settings, so I expect it'll be pretty seamless no matter how @AdGuardTeam decides to proceed.

**Comment by ameshkov** [comment]
> What I'm saying is if you switch the signing key (the key the app is signed with), Android will not accept the next version as an update – so while AG currently uses the package name com.adguard.android

This is a huge issue btw, and I am not sure what should we with it.

**Comment by IzzySoft** [comment]
@ameshkov according to a study I recently read, this is an issue affecting 60..80% of all apps on Playstore (which are even hit harder as switching to a different package name to them means losing all ratings) – so I honestly wonder that Google didn't come up with any advice. They can't expect all those apps switching to a different package name. And this issue hasn't just come up recently, but lingers for a couple of years already – so next to wonder is why developers aren't pressing them hard (or if they do, why we didn't notice that).

But as my ranting certainly does us no good: maybe we could win some dev with high reputation to officially approach Google for advice – and then publish that advice for the benefit of all, e.g. on his/her own blog?

PS: on rooted devices with Xposed, there's e.g. XInstaller to work around the issue: tell it to ignore certificate switch, upgrade, tell it to no longer ignore – done … Unfortunately that's not an approach we could tell the average user to take.

**Comment by Revertron** [comment]
> Failed to verify JAR signature META-INF/ADGUARD.RSA
Do you want a surprise? We **have no** META-INF/ADGUARD.RSA file in our builds. Where did you get that build?

**Comment by ameshkov** [comment]
@Revertron why, that's legit, we have no ADGUARD.RSA so that's why it has failed to verify:)

**Comment by ameshkov** [comment]
> But as my ranting certainly does us no good: maybe we could win some dev with high reputation to officially approach Google for advice – and then publish that advice for the benefit of all, e.g. on his/her own blog?

This is not a problem for apps in the Play Store so I doubt Google will care about it.

**Comment by ameshkov** [comment]
@Revertron so what about the double-signature you told me in private? Does it mean that we can solve the issue without breaking the update?

**Comment by Revertron** [comment]
Double signature has nothing to do with MD5 signing, it is already done.

**Comment by ameshkov** [comment]
Oh, my bad, I should've read the issue description more carefully

**Comment by ameshkov** [comment]
@Revertron updated the issue name.

Cannot confirm the MD5 issue, but there are still some problems detected:
```
$ ./apksigner verify ~/Downloads/adguard_2.10.176.apk
WARNING: META-INF/services/sun.net.spi.nameservice.NameServiceDescriptor not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.

```

**Comment by Revertron** [comment]
I see, this guy is opening this kind of issues in many projects:
https://github.com/zxing/zxing/issues/900
But he admits, that he is not an android developer. Then, I think, that he is checking signature by some weird jarsigner (may be from Java 9.0), and it guves him this kind of errors.

We must rely on a signer from Android SDK, and it gives us pretty good results:
```
D:\android-sdk-windows\build-tools\26.0.2>apksigner verify -v D:\Temp\adguard.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Number of signers: 1
```
No cries about MD5, see? :)

**Comment by ameshkov** [comment]
The key length is a valid concern, though.

At the moment, AG uses RSA2048 key, and it is not weak or deprecated so we have no problem with it.

Anyway, let's use this issue to deal with https://www.guardsquare.com/en/blog/new-android-vulnerability-allows-attackers-modify-apps-without-affecting-their-signatures

**Comment by Revertron** [comment]
> Applications that have been signed with APK signature scheme v2 and that are running on devices supporting the latest signature scheme (Android 7.0 and newer) are protected against the vulnerability.

So, AdGuard is not vulnerable, as we are signing by v2 scheme already.
And there is no way to protect older devices, that do not understand v2, anyway.

**Comment by IzzySoft** [comment]
@Revertron 

> Do you want a surprise? We have no META-INF/ADGUARD.RSA file in our builds. Where did you get that build?

Surprise for you: https://github.com/AdguardTeam/AdguardForAndroid/releases. And the `.apk` files ***do*** have a `META-INF/ADGUARD.RSA` – at least up to v2.9.70 (with v2.10.* you are correct, that file is no longer there). Contents of `META-INF`: `ADGUARD.RSA`, `ADGUARD.SF`, `MANIFEST.MF`. Check for yourself.

@ameshkov 

> This is not a problem for apps in the Play Store so I doubt Google will care about it.

Why shouldn't it be? If they're still using MD5, it affects them. And the numbers I gave were about apps on Playstore.

> But you admit, that you are not an android developer. Then, I think, you are checking signature by some weird jarsigner (may be from Java 9.0, am I right?), and it gives you this kind of errors.

As you might know, I'm running an F-Droid repo (for those apps not (yet) meeting F-Droid's inclusion policy). So "some weird jarsigner" is the official `apksigner` used by fdroidserver. And that gives me (on v2.9.70 – at about the time I opened this issue):

```
$ apksigner verify adguard_2.9.70.apk
DOES NOT VERIFY
ERROR: JAR signer ADGUARD.RSA: Failed to verify JAR signature META-INF/ADGUARD.RSA against META-INF/ADGUARD.SF: java.security.SignatureException: Algorithm constraints check failed on disabled algorithm: MD5.
```

Interestingly, and I'd very much like what you've changed in the meantime, the MD5 warning is gone with v2.10.176:

```
$apksigner verify adguard_2.10.176.apk
WARNING: META-INF/services/sun.net.spi.nameservice.NameServiceDescriptor not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
```

@Revertron 

> I see, @IzzySoft, you are opening this kind of issues in many projects

For the reason given; there are 250+ apps in my repo, so more than one of them is affected. For the same reason I'd very much like to hear what change might have cured it on your end, so I might spread the word for others to benefit. Doubling the size of the APK probably was not what solved it :wink:

Then, finally, as I see the issue solved, I'd say with the explanation of how it was solved it can be closed.

**Comment by Revertron** [comment]
Thank you for the explanation. Can I have a look to your repo? :)

The solution was clearly one of the:
1. Transition from Maven to Gradle build system.
2. Update of Android SDK and build tools.

But no change in certificates and keys was made.

**Comment by IzzySoft** [comment]
@Revertron Sure: https://apt.izzysoft.de/fdroid/ (AdGuard is the only non-open-source app in it actually; I took it in about a year ago as ad blocking clearly is "digital self-defense" and Google expelled them all from its store, so users need a place to get their protectors). The repo is known to the F-Droid team and they even recommend it here and there. I make my contributions to F-Droid as well (code-wise for fdroidserver and recently also for the apps' Metadata in fdroiddata, both over at GitLab).

Thanks for sharing your solution! Will check with the other projects to let them know.

**Comment by ameshkov** [comment]
@IzzySoft sorry for the confusion and thank you for reporting the issue!

> The solution was clearly one of the:

We've switched to the new build tools right after v2.9.70 so I guess that's what solved the issue.

**Comment by IzzySoft** [comment]
@ameshkov No problem. I should have been clear from the beginning how I came upon the issue, that'd have avoided most of the confusion I guess.
