### ISSUE TITLE
Support for upstream VPNs along side AdGuard

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardForAndroid#1576]
Can you please look at adding support for upstream VPN services with non rooted devices, at the same time as Adguard is running by using ovpn files, as open vpn does.

Thanks

**Comment by Revertron** [comment]
You are not realizing how much work this will demand.

**Comment by zero77** [comment]
I had no idea, maybe theres an easier way to run a VPN service on a non rooted device, at the same time as Adguard is running.

**Comment by ameshkov** [comment]
It'd be rather easy to do if OpenVPN ever implements this:
https://community.openvpn.net/openvpn/ticket/577

**Comment by zero77** [comment]
I have asked for support of that feature and it doesn’t look like it will happen, (socks5 server port) github.com/schwabe/ics-openvpn/issues/795

Although, there is in built support for using a custom DNS server, which would allow traffic to be routed through the AdGuard app.

But it would be more limited than the socks5 option .

**Comment by TPS** [comment]
Related: #775

**Comment by ameshkov** [comment]
Coming in a shape of AdGuard VPN:)
