### ISSUE TITLE
Long Press to Edit/Delete Individual User Filter

### ISSUE THREAD

**Issue by clementine123** [AdguardTeam/AdguardForAndroid#1580]
On the "User Filter" page, if one has to edit/remove a particular user filter, currently you have to click on the menu (three dots) and then select "Edit filter". On the next page, observing the following two issues:

1. Unable to scroll down easily (free smooth scrolling is required here).
2. If one has to remove the filter that is on the last line of this page, it is very difficult. That is, one has to scroll all the way down and tap on the last line. However, doing so brings up the keyboard and you cannot see what is being edited/removed as the filter text rule is behind the keyboard.

### Steps to reproduce
1. Open AdGuard -> Menu -> Settings -> User Filter
2. Tap on the menu (three dots) -> Edit filter

### Expected behavior
If one has to edit/remove a user filter, just long tapping on a particular filter should show the options to Edit/Delete that filter rule.

### Actual behavior
See point 2 above.

### Your environment
Adguard version: 2.10.108
Adguard filtering mode: Local VPN
Device model: Xiaomi Redmi Note 3
Operating system and version: Android Version: 6.0.1 MMB29M [MIUI Global 8.5 | Stable [ 8.5.7.0 (MHOMIED) ]
Rooted or not? Not rooted
Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? N/A

**Comment by ameshkov** [comment]
First of all, you can edit and delete individual rules by tapping on the rule.

What for the "Edit mode" issues, it'd be too hard to fix. You see, we already use the default "TextEdit" Android component, there's nothing lighter than it provided:(

**Comment by clementine123** [comment]
Oh yes, I just looked and was able to long press and edit/delete the individual user filter. Not sure, why it did not appear earlier. Sorry for this. Nothing to fix then :)
