### ISSUE TITLE
Custom DNScrypt - no traffic is observed at the server (Wireshark)

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#1581]
"If a custom dnscrypt server is specified, all DNS stops working and no
traffic is observed at the server (using wireshark). non-custom
dnscrypt servers work ok."

Can we do anything with that?

Ticket ID: 1654817

**Comment by ameshkov** [comment]
@veronikasav most likely something is wrong with the custom DNSCrypt configuration.

I guess the user might be interested in the dnscrypt log:

1. Settings -> Advanced -> Switch logging level to "record everything"
2. Start protection
3. Reproduce the issue
4. Settings -> Advanced -> Export logs
5. Unzip and look for dnscrypt.log file there
