### ISSUE TITLE
Consider using NXDOMAIN instead of 127.0.0.1

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1582]
Redirecting blocked domains to 127.0.0.1 may interfere with a local web server.

Why don't we use NXDOMAIN?

**Comment by Revertron** [comment]
It is recommended to use 0.0.0.0 as unexisting address:
https://github.com/StevenBlack/hosts#we-recommend-using-0000-instead-of-127001

**Comment by sfionov** [comment]
@Revertron On Linux, connecting to 0.0.0.0 means connecting to 127.0.0.1.
```
$ ping 0.0.0.0
PING 0.0.0.0 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.031 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.038 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.045 ms
$ lynx --dump 0.0.0.0
                               Welcome to nginx!
```

**Comment by Revertron** [comment]
I know, but those are linuxes :)
In windows you have:
```
C:\Users\Revertron>ping 0.0.0.0

Pinging 0.0.0.0 with 32 bytes of data:
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.
PING: transmit failed. General failure.

Ping statistics for 0.0.0.0:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```
Just tried `ping 0.0.0.0` in adb shell - it converts the address to `127.0.0.1` :(

**Comment by Revertron** [comment]
Done with NXDOMAIN answer.

**Comment by ameshkov** [comment]
There's no TTL in the response:
https://tools.ietf.org/html/rfc2308

**Comment by ameshkov** [comment]
> 5 - Caching Negative Answers

>   Like normal answers negative answers have a time to live (TTL).  As
>   there is no record in the answer section to which this TTL can be
>   applied, the TTL must be carried by another method.  This is done by
>   including the SOA record from the zone in the authority section of
>   the reply.  When the authoritative server creates this record its TTL
>   is taken from the minimum of the SOA.MINIMUM field and SOA's TTL.
>   This TTL decrements in a similar manner to a normal cached answer and
>   upon reaching zero (0) indicates the cached negative answer MUST NOT
>   be used again.

**Comment by Revertron** [comment]
Fixed.

**Comment by TPS** [comment]
Question:  If I use AG to block an IP address/range directly, is there _any_ way to force it to block like 1 does domains which now give `NXDOMAIN` & previously responded `127.0.0.1`? I find such blocking much more efficient, as once either of those responses are received, the requesting app quits asking, but other blocking often causes myriad repeated requests.  Is it possible to route IP addresses/ranges through the DNS module to do so?

**Comment by ameshkov** [comment]
Blocking IP addresses with a $network rule is different, it is not DNS-level blocking.

> Is it possible to route IP addresses/ranges through the DNS module to do so?

Nope, it's just too different. DNS works with domain names, not IP addresses.

**Comment by TPS** [comment]
I've got a request in the kb repo to get full details, but what's `$network`'s syntax, in short?  Would it prevent request flooding like I described?

**Comment by ameshkov** [comment]
> Would it prevent request flooding like I described?

Depends on the app. Usually, it's not, the app will try to repeat the tracking request a few times.

Moreover, with DNS filtering the app also tries that, but you don't see it because the DNS response is cached by the OS, and these repeated requests are going nowhere.

**Comment by TPS** [comment]
> but you don't see it because the DNS response is cached by the OS, and these repeated requests are going nowhere.

That's the behavior I'm trying to force, but I don't suppose the OS has a cache for seemingly dead IPs/ranges.
