### ISSUE TITLE
$important modifier doesn't override other rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#1584]
### Steps to reproduce

1. Add these rules:
`@@||reddit.com^$generichide,genericblock`
`@@||reddit.com^$elemhide,important`
2. Go here - https://www.reddit.com/

### Expected behavior

I think only rule with `important` modifier should be applied, like it is in AdGuard for Windows.

### Actual behavior

For one request `@@||reddit.com^$elemhide,important` is applied, for others `@@||reddit.com^$generichide,genericblock`

<details><summary>Screenshot:</summary>

![im1](https://user-images.githubusercontent.com/29142494/32615067-00affdca-c56f-11e7-910d-ab431ba37159.png)
![im2](https://user-images.githubusercontent.com/29142494/32615083-0dd5f626-c56f-11e7-859c-8f34adbdb31c.png)

</details>

### Your environment

* Adguard version: 2.10.164
* Adguard filtering mode: VPN
* Device model: LG G3
* Operating system and version: Android 6.0
* Rooted or not? Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by ameshkov** [comment]
@AdamWr in fact, this is by design :(

You see, `$elemhide` rules are applied to the requests with the "Document" type only. It simply cannot be applied to other requests.
`$generiblock` on the contrary are applied to all other requests.
