### ISSUE TITLE
A bug in the user filter of AdGuard for Android v2.10?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1585]
@ameshkov
@AdamWr

Hi,

This is my user filter in AdGuard for Android v2.10.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Vmyretf.png)
</details><br/>

And then I surely cancelled the check of the rule (||adservice.google.com^).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XGmVKBh.png)
</details><br/>

I left AdGuard for Android v2.10 and closed it in the background.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cT5N1ZG.png)
</details><br/>

Finally, I reopened AdGuard for Android v2.10 and reviewed my user filter.
I found that the check of the rule (||adservice.google.com^) is still ticked.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qpujArc.png)
</details><br/>

Why does AdGuard not save my change in the user filter?
Is it a bug?

https://github.com/AdguardTeam/AdguardForAndroid/issues/1520

That's why I didn't notice that the rule (||aotter.net^) was still ticked at that time after I surely cancelled the check of the rule. 
So I wrongly reported to AdamWr.
Yesterday, I modified the article.
> After adding ||aotter.net^$third-party in my user filter, ads are Not blocked.
Sorry AdamWr, 
Before you added tkmftc.aotter.net in Mobile ads filter, the ad was not blocked.
I didn't notice that although I cancelled to tick aotter.net in advance in my user filter at that time, the rule (||aotter.net^) was still ticked after I reopened AdGuard.
A bug.
I saw the ad was blocked because aotter.net is blocked in my user filter.
It was not because the rule "||aotter.net^$third-party" was working.

Thanks.

**Comment by zebrum** [comment]
so far i can not reproduce the issue, but will keep an eye on it.

**Comment by lancelot-moon** [comment]
@zebrum

You didn't do it according to my steps.
1. Open AdGuard. Don't need to enable AdGuard Protection.
2. Go to the user filter. Cancel a rule.
3. Click your android device's "Back button" for leaving AdGuard.
4. The important step!
Click your android device's "Menu button" for totally clearing AdGuard in the background.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cT5N1ZG.png)
</details><br/>

5. Reopen AdGuard. Go to the user filter. AdGuard didn't save my change in the user filter.

**Comment by zebrum** [comment]
yeah, you are right ) the main point is to use back button to exit the app.

**Comment by lancelot-moon** [comment]
No, the issue happened when clicking your android device's "Menu button" for totally clear AdGuard in the background.
The change in the user filter isn't saved.

**Comment by nkartyshov** [comment]
Fixed
