### ISSUE TITLE
Currently selected language displays as the default language, instead of systems

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1588]
### Steps to reproduce

1. Set the system language to English
2. Switch to Russian (or any other language)
3. Scroll to the top of the languages to default language (it will be Russian too)
4. Switch the language

### Expected behavior
There should indicate the right system language as the default language

### Actual behavior
Currently selected language displays as the default language, instead of systems

<details><summary>Video:</summary>

https://uploads.adguard.com/up01_qnwi8_device-2017-11-14-125720.mp4

</details>

### Your environment

* Adguard version: 2.10.164
* Adguard filtering mode: VPN
* Device model: Google Nexus 5X
* Android 8.0.0
* Not rooted

**Comment by Revertron** [comment]
Fixed.
