### ISSUE TITLE
LastPass stats for "Saved Bandwidth" is enormous

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#159]
It's like 70% saved.

@gshumihin please check what is blocked there?

I suspect that *maybe* LastPass goes mad because of ad&tracking blocking and constantly repeats ad&tracking requests.

**Comment by gshumihin** [comment]
Full log here:
https://www.dropbox.com/s/s6db55zqp7na3h1/adguard.log?dl=0

**Comment by ameshkov** [comment]
great, now analyze it.

**Comment by gshumihin** [comment]
Here is part of log, requests from LastPass app:
18:51:32.022 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13762 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.030 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13763 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.098 [pool-2-thread-1905] DEBUG com.adguard.android.FilteringLog - TCP id=13764 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.111 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13765 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.167 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13766 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.186 [pool-2-thread-1798] DEBUG com.adguard.android.FilteringLog - TCP id=13767 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.253 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13768 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.261 [pool-2-thread-1902] DEBUG com.adguard.android.FilteringLog - TCP id=13769 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.329 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13770 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.339 [pool-2-thread-1902] DEBUG com.adguard.android.FilteringLog - TCP id=13771 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.412 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13772 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.418 [pool-2-thread-1798] DEBUG com.adguard.android.FilteringLog - TCP id=13773 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.505 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13774 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.509 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13775 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.578 [pool-2-thread-1902] DEBUG com.adguard.android.FilteringLog - TCP id=13776 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.587 [pool-2-thread-1798] DEBUG com.adguard.android.FilteringLog - TCP id=13777 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.703 [pool-2-thread-1902] DEBUG com.adguard.android.FilteringLog - TCP id=13778 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.719 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13779 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.813 [pool-2-thread-1902] DEBUG com.adguard.android.FilteringLog - TCP id=13780 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.825 [pool-2-thread-1798] DEBUG com.adguard.android.FilteringLog - TCP id=13781 CONNECT ads=1 analytics.localytics.com 0 78
18:51:32.900 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13782 CONNECT ads=1 analytics.localytics.com 0 517
18:51:32.903 [pool-2-thread-1798] DEBUG com.adguard.android.FilteringLog - TCP id=13783 CONNECT ads=1 analytics.localytics.com 0 517
18:51:33.009 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13784 CONNECT ads=1 analytics.localytics.com 0 78
18:51:33.027 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13785 CONNECT ads=1 analytics.localytics.com 0 78
18:51:33.100 [pool-2-thread-1902] DEBUG com.adguard.android.FilteringLog - TCP id=13786 CONNECT ads=1 analytics.localytics.com 0 517
18:51:33.165 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13787 CONNECT ads=1 analytics.localytics.com 0 517
18:51:33.200 [pool-2-thread-1798] DEBUG com.adguard.android.FilteringLog - TCP id=13788 CONNECT ads=1 analytics.localytics.com 0 78
18:51:33.264 [pool-2-thread-1905] DEBUG com.adguard.android.FilteringLog - TCP id=13789 CONNECT ads=1 analytics.localytics.com 0 78
18:51:33.294 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13790 CONNECT ads=1 analytics.localytics.com 0 517
18:51:33.362 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13791 CONNECT ads=1 analytics.localytics.com 0 517
18:51:33.371 [pool-2-thread-1905] DEBUG com.adguard.android.FilteringLog - TCP id=13792 CONNECT ads=1 analytics.localytics.com 0 78
18:51:33.428 [pool-2-thread-1647] DEBUG com.adguard.android.FilteringLog - TCP id=13793 CONNECT ads=1 analytics.localytics.com 0 78
18:51:35.474 [pool-2-thread-1905] DEBUG com.adguard.android.FilteringLog - TCP id=13795 CONNECT ads=1 analytics.query.yahoo.com 0 232
18:51:35.541 [pool-2-thread-1900] DEBUG com.adguard.android.FilteringLog - TCP id=13797 CONNECT ads=1 analytics.query.yahoo.com 0 78

34 requests to analytics.localytics.com in 1 minute
