### ISSUE TITLE
Separate "blocked ads" and "blocked trackers" in the app stats (preparing for v3.0)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1590]
For now, we should do it on the underlying level, we won't show it anywhere.

We do it now as in v3.0 we need to have these two counters separated.

Blocked request is tracker if it's blocked by one of the following filters: 3, 118, 215, 212, 239

**Comment by ameshkov** [comment]
Done

**Comment by ameshkov** [comment]
Ops, sorry, not done:(

**Comment by Revertron** [comment]
Now it's done :)
