### ISSUE TITLE
Add xmlhttprequest filter rule modifier support

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1593]
Add `xmlhttprequest` filter rule modifier support.

At the moment we can't use rules like this: `||piguiqproxy.com^$third-party,xmlhttprequest`.

### Related report
https://github.com/AdguardTeam/AdguardFilters/issues/7648

**Comment by ameshkov** [comment]
Should be resolved in CoreLibs:
https://github.com/AdguardTeam/CoreLibs/issues/139
