### ISSUE TITLE
Check 2.10.164 -> 2.10.171 update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1595]
There're a couple of reports that update messes up with the app settings or even breaks the app.

I guess to test it properly you should first use 2.10.164 for some time and then try updating.

**Comment by TPS** [comment]
Related to #1604 or discussion @ https://github.com/AdguardTeam/AdguardForAndroid/commit/c2364660e54169e847ff6883a4617b40ee1218c8?

**Comment by ameshkov** [comment]
Nope, there were a few complains in the telegram channel, no details yet:(

**Comment by vozersky** [comment]
can't reproduce, could this be connected to google drive sync?

**Comment by TPS** [comment]
I think I happen to have this, also, after exporting, uninstalling, reinstalling, & importing. I've sent a "Report Everything" bug report via the app, tagged w/ @TPS.  Can you find it?  Does it help?

**Comment by vozersky** [comment]
@TPS about amazon version crashes, right? just found it, let's see

**Comment by vozersky** [comment]
@TPS 2.10.175 is now available at Amazon store, could you please check whether it changes anything or not?

**Comment by vozersky** [comment]
@TPS  https://github.com/AdguardTeam/AdguardForAndroid/issues/1608 yep, your log files helped a lot, thank you!

**Comment by vozersky** [comment]
fixed
