### ISSUE TITLE
Gerrit pages takes a very long time to load

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1598]
When AdGuard is enabled, gerrit pages takes a very long time to load. The pages appear to be stuck on the screen "loading gerrit code review". The page eventually loads after 1-2 minutes. With AdGuard disabled, the page loads in a few seconds. Cache has been cleared between test runs.

Example URL: https://android-review.googlesource.com/#/c/platform/frameworks/base/+/403274/
Another example, different domain: https://review.lineageos.org/#/c/193206/

### Actual behavior

Loading page hangs.

[screenshot](https://i.imgur.com/2xI0qqC.png)

</details>

Adguard version:2.10.171
source: https://www.reddit.com/r/Adguard/comments/7c33ns/bug_gerrit_code_review_pages_takes_ages_to_load/

**Comment by nkartyshov** [comment]
Fixed https://github.com/AdguardTeam/HttpsExclusions/commit/20b6db2aa2d595101ff82b3f9018ac7da7c393db

**Comment by ameshkov** [comment]
That's quite a weird fix, let's do it properly

**Comment by nkartyshov** [comment]
Bug, moved to CoreLibs:
https://github.com/AdguardTeam/CoreLibs/issues/167
