### ISSUE TITLE
wikia.com can't be reached if enabling AdGuard (Family) DNS or Open NIC (Regular or DNScrypt) in AdGuard's list of Public DNS providers in DNS filtering.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1599]
@ameshkov 

Hi,

With AdGuard for Android v2.10:

wikia.com can't be reached if enabling AdGuard (Family) DNS or Open NIC server (Regular or DNScrypt) in AdGuard's list of Public DNS providers in DNS filtering.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/V78WwqU.png)
</details><br/>

I decided to NOT use the Open NIC server in AdGuard's list of Public DNS providers in DNS filtering.
I used the custom OpenNIC DNS server which I got from https://www.opennic.org/.
52.230.17.182 (ns6.sg): 99.87% uptime
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/h8VrXFt.png)
</details><br/>

wikia.com can be normally reached!
And then I tried all Regular DNS servers and some DNScrypt servers in AdGuard's list of Public DNS providers in DNS filtering.
Everything is ok, except for AdGuard (Family) DNS or Open NIC server (Regular or DNScrypt) in AdGuard's list of Public DNS providers in DNS filtering.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/64B9pZt.jpg)
</details><br/>

With AdGuard Pro for iOS:

I enabled AdGuard DNS server.
wikia.com can be normally reached.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/rA4W3Al.jpg)
</details><br/>

1. Why?
Is there something wrong with DNS filtering when using the default AdGuard (Family) DNS or Open NIC servers (Regular or DNScrypt) of AdGuard for Android?

2.  I used my custom OpenNIC server.
Everything is fine.
But yours caused that wikia.com can't be reached.
What default Open NIC server in the list does AdGuard use?

Thanks.

**Comment by ameshkov** [comment]
@lancelot-moon cannot reproduce it.

I don't like the "BAD_CONFIG" error, maybe something is wrong with the servers connectivity?
Could you please check it again?

**Comment by lancelot-moon** [comment]
Hi,

When I did the test at that time, wikia.com can't be reached if enabling AdGuard (Family) DNS or Open NIC (Regular or DNScrypt) in AdGuard's list of Public DNS providers in DNS filtering.

Afterwards, one week ago, I did the same test again wikia.com could be reached if enabling AdGuard (Family) DNS.

But wikia.com still can't be reached if enabling Open NIC (Regular or DNScrypt) in AdGuard's list of Public DNS providers in DNS filtering.

Try Open NIC (both Regular and DNScrypt) in your default list.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cY8L8Wn.png)
</details><br/>

wikia.com still can't be reached.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/yl5I840.png)
</details><br/>

And then I used the custom OpenNIC DNS server which I got from https://www.opennic.org/.
52.230.17.182 (ns6.sg): 99.87% uptime
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/h8VrXFt.png)
</details><br/>

wikia.com can be normally reached!

What default Open NIC server in your list does AdGuard use?

B/R

**Comment by ameshkov** [comment]
You're right, we use some old config for the OpenNIC server:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1632
