### ISSUE TITLE
Intercept abp:subscribe and subscribe.adblockplus.org URLs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#16]
When we finish with other tasks from 2.3 Milestone, we should also implement this.

When user tries to open abp:subscribe URL in his browser - intercept this and offer him to add this filter to Adguard.

**Comment by TPS** [comment]
Just as a thought, could this be implemented as an Android intent, or would it be done when AG parses the documents on the way to display in browser?

**Comment by ameshkov** [comment]
With subscribe.adblockplus.org it's enough to intercept the request.
With abp:subscribe - I don't yet know. I hope that there is a way to register custom protocol handler in Android.

**Comment by TPS** [comment]
Should this be closed in favor of https://github.com/AdguardTeam/CoreLibs/issues/219, or left open for the Android-specific bits (like intents or custom protocol support)?

**Comment by ameshkov** [comment]
@TPS yep, thanks for the tip:)
