### ISSUE TITLE
Without all ad filters, ads were still blocked by Simplified domain names filter even I didn't choose AdGuard (Family) DNS server for DNS filtering.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1600]
@ameshkov
@vozersky
@AdamWr

Hi,

I disabled ALL ad filters and ONLY enabled DNS filtering.
After enabling AdGuard Protection (VPN mode) with AdGuard (Family) DNS server for DNS filtering, ads domains in Simplified domain names filter are blocked, which is normal.

However, why are ads still blocked by Simplified domain names filter when I doesn't choose AdGuard (Family) DNS server in my DNS filtering?

No matter what I used any DNS servers in the default DNS servers list (except for AdGuard (Family) DNS server) or my custom DNS server, ads were still blocked by Simplified domain names filter.

I used a custom OpenNIC DNS server.
52.230.17.182 (ns6.sg): 99.79% uptime
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7tYQTfo.png)
</details><br/>

I viewed the Filtering Log.
Some ads domains were blocked.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/GzVrXMO.png)
</details><br/>

They were still blocked by Simplified domain names filter even I didn't choose AdGuard (Family) DNS server in my DNS filtering.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/dolchRf.png)
</details><br/>

Why?
The situation is different with the behavior of AdGuard Pro for iOS's DNS filtering.
If we don't choose AdGuard (Family) DNS server in AdGuard Pro for iOS, for example: Google DNS, there is no ad blocked in DNS Requests Log.

Honestly, the DNS filtering of AdGuard for Android is very strange, especially when I use AdGuard (Family) DNS server or Open NIC servers (Regular or DNScrypt) in the default list!

It causes that I am unable to visit wikia.com.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1599

I ever used an app which introduces foods stores with their addresses.
When I clicked one store's address, it called Google Map app.
But Google Map app was unable to normally show the location of that store under DNS filtering enabled.
After I disabled DNS filtering, it became ok with only local VPN and ad filters.

B/R

**Comment by lancelot-moon** [comment]
Does Simplifed domain names filter always work in the backgroud even if disabling Simplifed domain names filter and not using AdGuard DNS server?

**Comment by ameshkov** [comment]
It works implicitly when you have "DNS blocking" enabled, that's what this setting is about. Disable it if you don't want it to work.
