### ISSUE TITLE
Visual glitch with Amazon version activation

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1603]
**STR:**
- Install and open the Amazon version of Adguard
- Press "Get Adguard Premium"

**Actual behavior:**
The menu from regular version opens for a second:

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/17472907/33075451-8d98d3d2-ceda-11e7-9d7c-6fa5681587d1.png)

</details>

And then it is automatically changed to an Amazon version menu:

<details><summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/17472907/33075576-0e284d8e-cedb-11e7-9a75-6717c0684a9d.png)

</details>

<br>
**Video:**

https://uploads.adguard.com/up05_28arn.mp4  see 0:10 - 0:22

**Comment by vozersky** [comment]
important issue with activation: https://github.com/AdguardTeam/AdguardForAndroid/issues/1604

**Comment by nkartyshov** [comment]
done
