### ISSUE TITLE
Amazon test (beta) version activation issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1604]
### Steps to reproduce
1. Install and open the Amazon version of Adguard
2. Wait for a few seconds until Premium is activated automatically
3. Go to the License menu and reset the key

### Actual behavior
You can't activate premium anymore, even after reinstalling the app

**Comment by nkartyshov** [comment]
I canot reproduce this problem.
If the license key is reset, the agent will not update the license key automatically. But you can re-enter it and activate the license.

**Comment by TPS** [comment]
Oy, why go through the steps of intentionally breaking a working license key? 😖  If this happened to me, somehow, I'd back my settings up, force quit, & then clear data from App Settings.  Then checking License Status (i.e., letting it sync w/ Appstore app) _should_ fix license, & then I'd restore settings backup.
