### ISSUE TITLE
Protection is restarted when you open HTTPS filtering menu

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1605]
### Steps to reproduce

_**Certificate should not be installed into the system**_
1. Open settings -> HTTPS filtering
2. Wait for a sec, don't touch anything.

### Expected behavior
Nothing happens

### Actual behavior
Protection is restarted

### Your environment
* Adguard version: 2.10.171

**Comment by ameshkov** [comment]
Done, should be tested now
