### ISSUE TITLE
Unable to connect to free wi-fi networks (Blackberry)

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1606]
> The problem is still related to Adguard blocking mostly datavalet and gstatic - the services that most wi-fi providers use to validate the connection. 
If I disable Adguard, I can connect to any free wifi service. With Adguard
enabled most of them just hang up.

The customer reported that he's unable to connect to McDonald's and Canadian Tire free hotspots, logs with time markers are available here: 1470818

### Customer ID 
1470818

### Your environment

* Adguard: 2.10.164
* Android: 6.0.1
* Subscriptions: , 3, 4, 14, 11, 203
* HTTPS: Off
* Filterng mode: VPN
* Method: Full

**Comment by ameshkov** [comment]
@evgeniy-ADG sorry for the late reply.

Could you please ask him to record a full log? Also, I'll need to know when exactly did it happen.

**Comment by evgeniy-ADG** [comment]
We have logs, please check here: 1470818

**Comment by ameshkov** [comment]
This might be a blackberry-specific thing.

1. I don't see any connections from the captiveportallogin app. Usually, there're requests to `generate_204` URL.
2. I see that the remote https connections are intercepted and changed to `securelogin.arubanetworks.com` (so the Wi-Fi indeed wants the user to authorize first).

Could you please ask him if he has the same issue with any other VPN app (like noroot firewall for instance).
