### ISSUE TITLE
Filtering log search issues

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1610]
**1.** 

### Steps to reproduce
1. Search for any word which should show up when visiting a site. 
2. Now open the site and check filtering log again.
3. Now remove the search request and search for the same word again and it

### Actual behavior

 Search result is only shown when you re-type the request

**2**

### Actual behavior

 you can't clean the log when the search request is in the search field
(you actually can, but you will not see the result until you go back\delete the request)

**Comment by nkartyshov** [comment]
fixed
