### ISSUE TITLE
How to blocked url completely

### ISSUE THREAD

**Issue by dba007** [AdguardTeam/AdguardForAndroid#1611]
1.Settings -->HTTPS Filtering --> Enable(On)
2.Settings --> User Filter --> Add rule:
addons.mozilla.org/en-US/firefox/addon/tab*
3.open browser enter url:
https://addons.mozilla.org/en-US/firefox/addon/tab-auto-refresh/

still accessible, this url not blocked.
but the Filtering log display state is blocked.
In fact, it's not blocked.

* Adguard filtering mode: VPN
* Operating system and version (Android 6.0.1)

**Comment by dba007** [comment]
adguard version:2.10.175

**Comment by ameshkov** [comment]
@dba007 add an $empty modifier:
`||addons.mozilla.org/en-US/firefox/addon/tab$empty`

By default, AG does not to block the whole tabs and just block the sub-requests (sent from the page).

**Comment by dba007** [comment]
thank you!
this key $empty can meet my needs.

I found another problem.
AG does not stop protection immediately when the network is disconnected.
When connection success to the network, AG does not start protection immediately.
Disconnect and connect network AG will be delayed for a period of time to detect changes in the network.

**Comment by clementine123** [comment]
@dba007 I am facing the same issue with my phone. This seems to be specific to certain phones as this is not observed on my sister's phone. Earlier versions of AG used to start protection as soon as the WiFi/mobile data connection was established.

**Comment by TPS** [comment]
@dba007, @clementine123: Try adjusting  Settings → Advanced → Low level Settings → `pref.boot.startup.delay`, `pref.vpn.disable.pause`, _&/or_ `pref.vpn.disable.reconfigure` to see whether the delays can be skipped or are mandatory.

**Comment by ameshkov** [comment]
@dba007 @clementine123 the delay depends on how fast Android notifies AdGuard about the connectivity change so it's not we can control.

@TPS is right, though. You can simply disable this behavior and see how it works out.
