### ISSUE TITLE
Extend AdGuard notification -- show an "Assistant" button

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1614]
Here's how I see it:
<img width="1027" alt="up04_y8wiz_adguard_for_android_-_quick_settings__moqups" src="https://user-images.githubusercontent.com/5947035/33257534-8a32498a-d367-11e7-8a17-e0bc0f17b066.png">

**Comment by Revertron** [comment]
1. We will need good system of determining "used" apps. Be it foreground, or that used most traffic - we will need to decide.
2. For "used" sites we will need to determine loaded HTML-documents, not some scripts or pictures.
3. As for GUI part - we can do it as a dialog over a transparent activity.

**Comment by Revertron** [comment]
Implemented.

**Comment by ameshkov** [comment]
We need to make some changes.

1. The app details activity is currently opened in a weird way. The apps management is opened first, and only then we open the app details. This is wrong, there should be a way to open the app details screen directly.
2. Sometimes Assistant dialog also brings up the app main activity as well.
3. Apps/websites should be sorted by the last activity time;
4. Change the action dialogs layout to this:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3OExlLU5oNDhjYW8/components-dialogs-updates5.png

5. Here's the layout we need for the dialogs: https://uploads.adguard.com/up04_9873j_Adguard_for_Android_-_Quick_Settings__Moqups_.png
    Also, depending on the app settings, we will need to show "unblock network access" and "remove from the whitelist" options.

6. We need to have blocked network connections in the filtering log. I suggest calling `postNetworkRequestBlockedEvent` with a text "Blocked by the firewall settings" instead of the filtering rule text.

7. Change the text we have in the apps/websites list. Instead of "used N secs ago" print "Last activity: 5 seconds ago": https://uploads.adguard.com/up04_embaz_Adguard_for_Android_-_Quick_Settings__Moqups_.png

**Comment by ameshkov** [comment]
Icons for the options in item 5:
[assistant_icons.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1711187/assistant_icons.zip)

**Comment by ameshkov** [comment]
Done
