### ISSUE TITLE
Integrate AdGuard for Android with reporting web tool

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1615]
We need to implement this once we have a working Assistant of some sort (see https://github.com/AdguardTeam/AdguardForAndroid/issues/1614).

Link to the Reports repo: https://github.com/AdguardTeam/ReportsWebApp

This issue is to be elaborated on later.

**Comment by ameshkov** [comment]
We should change the way "Send Feedback"  works.

Instead of the current form, we should draw just a single combobox with the following options:

* `Missed Ad or Tracker`
* `Incorrect Blocking`
* `Bug`
* `Feature Request`
* `Other`

The first two should open the reporting tool.

**Comment by Revertron** [comment]
Done, merged.
