### ISSUE TITLE
Notify users when they disable Base filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1617]
Some users don't realize how important is English filter for proper filtering. We should immediately show a warning-like red text when a user disables English filter in Ad Blocker settings. It should say "English filter is necessary for quality filtering!" right under the "English filter" heading.

**Comment by Revertron** [comment]
May be we need to rename it properly? Not "English", but something like "Universal"?

**Comment by Revertron** [comment]
Sorry, didn't mean to close right away :)

**Comment by vbagirov** [comment]
It will be renamed eventually, but we still need to have a memo for those who try to disable it.

**Comment by lancelot-moon** [comment]
> May be we need to rename it properly? Not "English", but something like "Universal"?

I agree!
"Universal" is a good idea.

**Comment by ameshkov** [comment]
Agree with @Revertron, renaming is much easier.

**Comment by lancelot-moon** [comment]
May you early put the filters' strings on oneskyapp?
The now translations of filters are not good.
Some of them are even Simplified Chinese, but they're used in Traditional Chinese language file.
https://github.com/AdguardTeam/AdguardForiOS/issues/500

**Comment by ameshkov** [comment]
Yep, @Mizzick does a huge "AdguardFilters" rework and moving all the filters meta data to oneskyapp is a part of it.

**Comment by lancelot-moon** [comment]
Большое, спасибо!
@aalpatkina
May you send a notification to translators after finishing moving the strings of filters to oneskyapp?
Just tell us where the area of filters for various platforms is on oneskyapp.
Thanks for your great work!

**Comment by aalpatkina** [comment]
@lancelot-moon 
Of course, you'll receive all the necessary information in the newsletter.

**Comment by lancelot-moon** [comment]
@aalpatkina 
In Website reports.adguard.com on oneskyapp, this should be "AdGuard Pro for iOS", right?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NScb93K.png)
</details><br/>

**Comment by vbagirov** [comment]
@lancelot-moon please try to stay on topic, this is definitely a completely different issue. But answering your question, there's no straight incorrect variant here, both `AdGuard for iOS Pro` and `AdGuard Pro for iOS` are acceptable.

**Comment by TPS** [comment]
Now that the name is changed to "AdGuard Base filter," could this issue title be updated?  TIA! 🙇🏾‍♂️

**Comment by vozersky** [comment]
merged into #3378
