### ISSUE TITLE
Android 8.1: AdGuard icon is visible even when "Notification without icon" is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1618]
Just got Android 8.1 pre-release and got this issue. No idea what has changed yet.

I am sure that we can fix it, though, as it behaves normally in other apps.

**Comment by ameshkov** [comment]
https://issuetracker.google.com/issues/69842394

**Comment by ameshkov** [comment]
> This is intentional, to reduce the occurrence of the system 'apps are using battery' notification. If the importance of a channel is set to MIN or NONE, it will be bumped to LOW when a foreground notification is posted to it, unless the user has explicitly changed the importance

**Comment by Nemi5150** [comment]
For what it is worth, I followed the instructions in comment #3 on the link that you have in here to the Google bug and it changed the behavior for adguard in Android 8.1 on a pixel 2XL to work the way it used to in Android 8.0.

**Comment by aav7fl** [comment]
@Nemi5150 

Thanks for the comment! That fixed my notification as well.

**Comment by ameshkov** [comment]
They've updated the documentation:
https://developer.android.com/reference/android/app/NotificationManager.html#IMPORTANCE_MIN

> Min notification importance: only shows in the shade, below the fold. This should not be used with Service.startForeground since a foreground service > is supposed to be something the user cares about so it does not make semantic sense to mark its notification as minimum importance. If you do this > as of Android version O, the system will show a higher-priority notification about your app running in the background.

Basically, it means that the workaround you're using will be removed in the future updates.

Maybe, this issue will be resolved when we start targeting SDK level 26 and start using notifications channels: #1561
