### ISSUE TITLE
One tap for enabling or disabling user filter. (feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1620]
In the user filter, maybe some rules are enabled, and others are disabled.
Wish one tap for enabling or disabling user filter.
(Keep the last status of rules enabled and rules disabled in user filter, such like the user filter of AdGuard for Windows.)
Thanks.

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/1335
