### ISSUE TITLE
Please improve the layout of custom DNS servers setting (feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1621]
@ameshkov

Hi,
The under content is my wishful layout for custom DNS servers setting.
Just a suggestion.
Feel free.
Please don't mind.

I wan to intuitively see **DNS server name, IP addresses and description even servers location** on screen.
I don't want to scroll down here.
It only shows System default, 1 custom DNS server's information and 1 Public DNS provider's information on screen.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/AFrRe8j.png)
</details><br/>

Simply click the area of custom DNS setting or Public DNS provider for jumping a pop-up window or the next screen for selecting a DNS server.

For custom DNS settings:
Please give max size of 20 custom DNS servers.
We add, delete or edit the profiles of custom DNS servers here.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vyvmKvM.png)
</details><br/>

For Public DNS providers:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fB61to8.png)
</details><br/>

For Public DNScrypt DNS providers:
I also don't want to scroll down here.
It only shows 1 DNScrypt DNS provider's information on screen.
Simply click it for jumping a pop-up window or the next screen for selecting a DNScrypt DNS server.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/bAEK53M.png)
</details><br/>

Thanks a lot!

**Comment by ameshkov** [comment]
> I wan to intuitively see DNS server name and IP addresses on screen.

Makes sense, but please note, that "System DNS" IP address depends on the current ISP.

For instance, you'll see different addresses when you're on Wi-Fi and on mobile.

**Comment by lancelot-moon** [comment]
Yes, please.

For System default DNS, let AdGuard automatically detect the current DNS and show the current DNS IP address on screen.

When using cellular network, AdGuard shows ISP's DNS IP address.
When using Wi-Fi network, AdGuard shows modem's DNS IP address.
When connecting to a real VPN server with AdGuard local HTTP proxy mode, AdGuard shows VPN provider's DNS IP address.

**Comment by lancelot-moon** [comment]
> It only shows System default, 1 custom DNS server's information and 1 Public DNS provider's information on screen.

Almost forget to say, please also show server location on screen, except for server name, ip and description.
The location of server affects network speed.
In your list, there are location informations.
https://github.com/dyne/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

**Comment by lancelot-moon** [comment]
@ameshkov 

May you change the layout of DNS settings as my suggestions since there are more improvements in v3?

I wan to intuitively see **DNS server name, IP addresses and description even servers location on screen**.
I don't want to scroll down here.
It only shows System default, 1 custom DNS server's information and 1 Public DNS provider's information on screen.

Thanks.

**Comment by TPS** [comment]
@lancelot-moon Are you testing 3.0.56ƞ?  Is it sufficient for this?

**Comment by lancelot-moon** [comment]
No, still the same DNS module with v2.12.
Andrey said we have to wait for new CoreLibs module.
New DNS settings will be bound in new CoreLibs module.

**Comment by lancelot-moon** [comment]
Outdated.
