### ISSUE TITLE
FAQ articles are not accessible when AdGuard is switched to Japanese

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1622]
### Steps to reproduce

1. Switch to Japanese
2. Go to AdGuard > FAQ > Click on any article
3. See what is on the screenshot

### Expected behavior

Articles are fully accessible

### Actual behavior

They are not

<details><summary>Screenshot:</summary>

![screenshot_20171201-200809](https://user-images.githubusercontent.com/15856304/33496736-0c16b354-d6d4-11e7-921b-c83c9cb90744.png)

</details>

### Your environment

* Adguard version: 2.10.176
* Motorola phone

**Comment by nkartyshov** [comment]
fixed
