### ISSUE TITLE
Некорректное отображение иконки в шторке уведомления

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1623]
Стоит Android 4.4.4, Nexus 5, adguard 2.10.176.
Сверху некорректно отображается знак, буквы некоторые внизу скрыты. Хотелось бы вообще убрать надпись блокировано, сэкономлено и сделать как было на 2.9.136

**Comment by ministr91** [comment]
![screenshot_2017-12-02-02-25-16](https://user-images.githubusercontent.com/22351242/33507878-ed91638a-d6ff-11e7-97c8-5984547ac8a3.png)

**Comment by ministr91** [comment]
Это не критично, проблема потом исчезает сама собой. Это только при первом запуске новой версии, потом все отображается в линию сплошную

**Comment by ministr91** [comment]
Или в столбик, но уже раскрытый

**Comment by ameshkov** [comment]
Сильно специфично, мы не можем подо все экраны подогнать.

Но буду знать, что в 4.4 такое случается.
