### ISSUE TITLE
Preview opens an EN version of KB article instead of RU

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1624]
При открытии FAQ статья про прокси на английском, можно ее перевести? Adguard 2.10.176

**Comment by ministr91** [comment]
![screenshot_2017-12-02-16-14-22](https://user-images.githubusercontent.com/22351242/33515996-8d7e1b4a-d773-11e7-86a1-584834eb6ac8.png)
![screenshot_2017-12-02-16-14-30](https://user-images.githubusercontent.com/22351242/33515998-9230c5c0-d773-11e7-9e07-dfbc08c65d5e.png)

**Comment by ameshkov** [comment]
Вот он:
https://kb.adguard.com/ru/android/solving-problems/adguard-outbound-proxy

Возможно, что у нас ссылка кривая в программе, ее надо будет исправить.

**Comment by nkartyshov** [comment]
Fixed
