### ISSUE TITLE
Translate DNSCrypt servers descriptions

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1625]
Перевести описание серверов на русский

**Comment by ministr91** [comment]
![screenshot_2017-12-02-16-23-25](https://user-images.githubusercontent.com/22351242/33516080-18b3d334-d775-11e7-9192-f09d74283ade.png)

**Comment by lancelot-moon** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1574

Eh, it's the same with mine.

**Comment by ameshkov** [comment]
@lancelot-moon oh, and according to the comment there we cannot translate them:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1574#issuecomment-341072045

Good catch, thank you!

**Comment by ministr91** [comment]
@ameshkov зачем закрывать? Перевод в версии 2.11 будет?

**Comment by ministr91** [comment]
Как я понял, вы не можете их перевести? Но почему?  Ведь приложение ваше и наверняка в коде можно сделать перевод. Эта ситуация как с фильтрами. Например, adblock killer. Он не ваш, но перевод снизу написать можно, так почему здесь нельзя?

**Comment by ameshkov** [comment]
Очень неудобно их переводить, они вытаскиваются из центрального хранилища DNSCrypt, и часто меняются. Переведем - потом переводы пропадут.
