### ISSUE TITLE
Перевод фильтров в антибаннере на русский

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1626]
Много непонятных фильтров. Например, adblock killer. Что это за фильтр? Для чего он? Хотя бы краткое описание. 
List-KR вообще не переведен
Adguard 2.10.176

**Comment by ministr91** [comment]
![screenshot_2017-12-02-16-27-05](https://user-images.githubusercontent.com/22351242/33516098-8f907340-d775-11e7-9886-8284e6305960.png)
![screenshot_2017-12-02-16-27-10](https://user-images.githubusercontent.com/22351242/33516099-9368bbb2-d775-11e7-968d-1fba8a0dfc19.png)

**Comment by ameshkov** [comment]
Мы добавим описание для них (название не для всех нужно переводить), но позже маленька. Работаем над тем чтобы базу в порядок привести.

Закрываю как дубликат (есть такая задача во внутреннем трекере).

**Comment by ministr91** [comment]
@ameshkov в 2.11 будет исправлено?

**Comment by ameshkov** [comment]
Не, а они переведены разве вообще?

Посмотри тут:
https://adguard.oneskyapp.com/
