### ISSUE TITLE
AdGuard does not start back automatically after OpenVPN is disabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1628]
Here is the issue description:
https://forum.xda-developers.com/showpost.php?p=74698770&postcount=2924

Logs attached:
[adguard_logs_2.10.176_0112_0930.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1525156/adguard_logs_2.10.176_0112_0930.zip)

**Comment by sviperz** [comment]
The same when using VPN Client Pro app. AG remains in paused state when VPN Client Pro disconnects.

AG version: 2.11.31 Beta
AG filtering mode: VPN
Device: Google Pixel 2016
OS: Android 8.1.0
No root

**Comment by Eugene-Savenko** [comment]
The same behavior here 1222602, AdGuard won't start back after a 3rd-party VPN is disabled, with 2.11 and 2.12.1 η versions. Please check for logs.

**Comment by nkartyshov** [comment]
The user uses ZenMate Vpn, which conflicts with other vpn applications. 
Link on the issue https://github.com/AdguardTeam/AdguardForAndroid/issues/1044#issuecomment-278330380
