### ISSUE TITLE
Crash: BadTokenException: Unable to add window -- token android.os.BinderProxy@448be4f0 is not valid

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1631]
**Added by @ameshkov:**
AdGuard crashes with the following error:
```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@448be4f0 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:532) ~[na:0.0]
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259) ~[na:0.0]
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69) ~[na:0.0]
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2838) ~[na:0.0]
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238) ~[na:0.0]
	at android.app.ActivityThread.access$800(ActivityThread.java:135) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:136) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5001) ~[na:0.0]
	at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) ~[na:0.0]
	at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
```

Logs:
[adguard_logs_2.10.176_0412_0429.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1526155/adguard_logs_2.10.176_0412_0429.zip)

**Original issue text:**
крашится приложение. Не открывался 1 сайт, решил, что дело в adguard, потому что с ПК все открывалось. Хотел выключить защиту и посмотреть, откроется ли сайт. Нажал на знак adguard, но вместо этого белый экран, потом сменился на черный и уведомление - приложение не отвечает - подождать или закрыть. Нажал закрыть, потом спокойно зашел в adguard, вкл. защиту и на сайт спокойно зашел. 
Adguard 2.10.176, Nexus 5. 
Нажал на выгрузку логов. http://my-files.ru/ag6gkc

**Comment by ministr91** [comment]
Опять эта проблема. Поиск стал медленнее идти и телефон стал глючить. На 2.9.136 такого не было
Вот видео снял, чтобы понятнее было. Оно небольшое, посмотри до конца http://my-files.ru/kodkph

**Comment by ministr91** [comment]
Это бонус к лагам
![screenshot_2017-12-04-04-43-53](https://user-images.githubusercontent.com/22351242/33532841-c7e5a522-d8a5-11e7-9c1b-01fbe8f28486.png)

**Comment by ministr91** [comment]
@ameshkov  а в чем проблема? Серьезная? Будет еще 1 экстренное обновление приложения или только в 2.11 исправите?

**Comment by ameshkov** [comment]
@ministr91 только в 2.11, и пока не знаю в чем точно проблема.

**Comment by ministr91** [comment]
@vozersky @evgeniy-ADG @nkartyshov @Revertron @zebrum @Alex-302 @vitalkanev подключайтесь к проблеме тоже

**Comment by vitalkanev** [comment]
Я? Я не имею телефона! Я разбираюсь в расширении только! :man_facepalming:

**Comment by vbagirov** [comment]
@ministr91 зачем всех пинговать то. Не делайте так больше.

**Comment by ministr91** [comment]
@vbagirov  хорошо, не буду. Все равно никто не пришел(

**Comment by nkartyshov** [comment]
@ministr91 А нотификация была в шторке при первом открытие приложений?

**Comment by ministr91** [comment]
@nkartyshov 3 месяца прошло. Когда я только открыл браузер в 1-й раз, все с приложением adguard было нормально, значок висел в шторке.

**Comment by nkartyshov** [comment]
@ministr91 Понятно, но ошибка очень не странная. В новой версии приложение будут исправления это проблемы, сможете проверить?

**Comment by nkartyshov** [comment]
@ministr91 Новая nightly версия: https://agrd.io/android_nightly

**Comment by ministr91** [comment]
@nkartyshov, нашли в чем была проблема? Эта ошибка появляется очень редко и я не смогу сказать, исчезла она или нет.

**Comment by nkartyshov** [comment]
@ministr91 Можно сказать, что нашли, но она может быть и не связана с работой приложения. По стек трейсу видно, что она возникла в момент запуска и это могут быть проблемы системы. Но мы постарались исправить её у себя. Почему она возникает можно почитать [тут](https://stackoverflow.com/questions/18662239/android-view-windowmanagerbadtokenexception-unable-to-add-window-on-buider-s#18665887) (статья на английском) Попробуйте последний nightly билд, если она опять появится сообщите нам.

**Comment by nkartyshov** [comment]
Могу закрыть задачу?

**Comment by ministr91** [comment]
@nkartyshov да, закрывай.
