### ISSUE TITLE
Update the OpenNIC server address

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1632]
We use some outdated IP addresses in the default config:
`192.95.54.3`
`192.95.54.1`

We'd better use something from the list:
https://servers.opennic.org/

For instance these:
https://servers.opennic.org/edit.php?srv=ns1.any.dns.opennic.glue
https://servers.opennic.org/edit.php?srv=ns3.any.dns.opennic.glue
https://servers.opennic.org/edit.php?srv=ns5.any.dns.opennic.glue

**Comment by nkartyshov** [comment]
done
