### ISSUE TITLE
AdGuard Sometimes Fails to Restart when Switching Mobile Data <-> WiFi

### ISSUE THREAD

**Issue by Hazbelll** [AdguardTeam/AdguardForAndroid#1637]
### Steps to reproduce

1. Use the device as normal, uptime of around 1 - 2 days usually.
2. Switch from using Mobile Data to WiFi or vice versa.
3. Check for the VPN icon within the status bar.
4. Providing there is no icon within step 3, open AdGuard to see it's reported itself as "Disabled". Manually re-enabling it works and continues as expected until the issue occurs again.

### Expected behavior

AdGuard should always restart itself when switching between network types, regardless of scenario.

### Actual behavior

Sometimes, AdGuard doesn't restart itself, remaining disabled until the user manually re-enables it from within the App. This appears to occur after 1 - 2 days or more of system uptime, but might be coincidence. This issue has occurred on both Android 7.1.1 and Android 8.0.0.

<details><summary>Screenshot:</summary>

</details>
N/A

### Customer ID 

1688853

### Your environment

* Adguard version: **2.10.176**
* Adguard filtering mode: **VPN**
* Device model: **OnePlus 3T (A3003)**
* Operating system and version **Android 8.0.0 (OxygenOS 5.0.0 ROM)**
* Rooted or not? **Not Rooted**
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? **No**

**Comment by vozersky** [comment]
[logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1542503/logs.zip)

**Comment by Revertron** [comment]
This error is not fatal, the app didn't crash. No additional useful info in the log.

**Comment by Hazbelll** [comment]
Hold up, I omitted some valuable information from my original post, sorry.

I forgot to mention that I have AdGuard set to have no badge/notification in the Status Bar (Yes I know it warns you about it possibly getting killed), but had also set AdGuard to **Not Optimised** in Battery Settings. OxygenOS' "Aggressive Doze" is also Disabled.

Perhaps that's why and there's no solid workabout for it without at least the notification? Not too sure seeing as this bug only occurs upon network changes, although might link into why I've only exhibited the behaviour after as memory serves, least 24 hours of uptime.

**Comment by ameshkov** [comment]
@Hazbelll we have a history with OxyOS and it's weird behavior:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1385

First of all, it appears, that "pinning" AdGuard might be necessary for it to work properly. Could you please do it and check if it helps?

**Comment by Hazbelll** [comment]
Yesterday I tried rebooting my phone, opening AdGuard, checking for updates then left it and within the first few hours of uptime, this issue occured, so doesn't seem any significant amount of system uptime contributes here and most likely related to opening the foreground app then leaving it.

Wouldn't surprise me if OxygenOS were to be the culprit, especially in its later incarnations (Such as the Oreo ordeal). I shall try as you ask and get back to you soon.

**Comment by worstperson** [comment]
Just want to note that I see  a similar issue with proxy mode on Lineage OS with network switchovers. On my WiFi only S3 it happens about once a week, while it happens more frequently on my friends S5 w/ mobile network. Shows up as an 'X' over the WiFi icon and resolves immediately after restarting adguard. Adguard is set to not optimised in the battery settings and we use the notification. Adguard stays enabled when the issue occurs.

**Comment by Hazbelll** [comment]
So far so good. AdGuard is still going after these few days whilst being "pinned" in the Recents App list without issue.

**Comment by ameshkov** [comment]
> Shows up as an 'X' over the WiFi icon and resolves immediately after restarting adguard.

This sounds different from what @Hazbelll had, so I'd better close the original issue.

Let's continue the discussion, though. Maybe I'll need to open another one.

@worstperson 
Do you and your friends use AdGuard in VPN or proxy mode?
