### ISSUE TITLE
More banking apps to exclude

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1638]
https://play.google.com/store/apps/details?id=com.finansbank.mobile.cepsube
https://play.google.com/store/apps/details?id=com.garanti.cepsubesi&hl
https://play.google.com/store/apps/details?id=com.freecharge.android
https://play.google.com/store/apps/details?id=com.cathaybk.mymobibank.android

**Comment by vozersky** [comment]
requested to exclude from https filtering,
two banking apps and and some payment app

**Comment by nkartyshov** [comment]
Added

**Comment by BlazDT** [comment]
https://play.google.com/store/apps/details?id=com.fortuneo.android
