### ISSUE TITLE
A simple DNS servers speed test tool (feature request)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1639]
Well, a simple DNS servers speed test tool is an extra function.
Do the speed test for all selected DNS servers (default and custom) in AdGuard.
Let users know which DNS server is faster.
I think it's a plus (add points) for AdGuard...

**Comment by ameshkov** [comment]
It's a bit out of scope for us, that's why priority is set to "Low".

**Comment by lancelot-moon** [comment]
Yes, I understand.
That's why I said it's extra function.
But the speed test tool is thoughtful (a sweetie) for AdGuard users.
It's ok that the priority is low.
You do according to your plan.
If it's possible, hope that the DNS servers speed test tool will be in both Android and iOS version of AdGuard.

Thanks.

**Comment by vozersky** [comment]
too out of scope for us after all

**Comment by lancelot-moon** [comment]
@ameshkov 
https://block.blokada.org/post/2018/06/15/features-vote-results/
From Blokada's features vote results, speed test got not bad upvotes.
(Well, AG already had some features which are listed there.)

**Comment by lancelot-moon** [comment]
@vozersky 
You keep the feature request of speed monitor.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1492

But this feature request of simple DNS servers speed test tool is abandoned...

**Comment by TPS** [comment]
@lancelot-moon Possibly better to fold this into #1492, anyway, as perhaps similar backend could be used.
