### ISSUE TITLE
AdGuard  expose an open port (security risks)

### ISSUE THREAD

**Issue by Giova84** [AdguardTeam/AdguardForAndroid#1640]
I land here after the suggestion of a friend of mine :-)
I also discovered that adguard expose an open port on the ip address: no probs when the ip is private or on lan. but when is public... I can "attack" the phone of my friend by send a continuos ping on this port on his public ip - this also occurs for me: by sending this continuous ping os such port the battery drains very fastly, maybe this battery drain occurs due to the fact that this port is "linked" to adguard.
IMHO this is an high priority ticket.

screenshot proof, is the first port in this image
http://picpaste.com/screenshot.png

**Comment by ameshkov** [comment]
In theory, it *should* be relatively easy to fix so I'll assign it to v2.11.

**Comment by Revertron** [comment]
Hm, the picture (http://picpaste.com/screenshot.png) does not open :(

**Comment by Revertron** [comment]
The problem is: our ipv6_proxy mode is creating transparent proxy, that listens on all the interfaces, and there is no way to set it to localhost only.
We can only disable traffic to this port from other interfaces by iptables rules.

**Comment by ameshkov** [comment]
As I understand, this port looks open even when AG is in VPN mode.

**Comment by Giova84** [comment]
Sorry: maybe i misunderstood.
In the changelogs for AdGuard 2.11.81 I can read "[Fixed] AdGuard exposes an open port #1640", but such port still results open, I mean that I can still ping such port, is ok?

**Comment by Giova84** [comment]
Sorry for the very long reply!
I don't use any VPN (except AdGuard itself, on Android), I checked the open port by scanning my phone using nmap.
