### ISSUE TITLE
AdGuard blocks voice recognition in Microsoft Edge for Android

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1641]
### Steps to reproduce

1. Activate AdGuard
2. Open Microsoft Edge
3. Try to use voice recognition in the search bar to search anything
4. A "Security error" message will appear on the screen

### Expected behavior
Browser should recognize your voice and create an appropriate search query

### Actual behavior
Browser will fail to recognize your voice and return a "security error" message

<details><summary>Screenshot:</summary>

Not available for this issue

</details>

### Customer ID 
Client: 1685438
Repro: 1691619

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung SM-G935F
* Operating system and version: Android 7.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: Nothing installed

**Comment by ameshkov** [comment]
@vozersky 100% caused by SSL filtering of some Cortana domain.

We need to get the log.

**Comment by akmAa** [comment]
Issue happens at 4:33PM (16:33).

[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1568282/debug.txt)

**Comment by ameshkov** [comment]
Domains that could be causing it:
```
api.cognitive.microsoft.com
otf.msn.com
websockets.platform.bing.com
```

@akmAa could you please try adding these domains to the HTTPS exclusions list one by one and check if any of them helps?

**Comment by akmLaVx** [comment]
User has been notified.

**Comment by ameshkov** [comment]
@akmLaVx any update?

**Comment by akmLaVx** [comment]
@ameshkov Not yet. I've notified the user but no updates so far. Will reinstall Edge manually and see if this helps if user will remain inactive until Friday.

**Comment by nkartyshov** [comment]
@ameshkov The exclusions those domains solves the problem, as well as disabling the https filtering

**Comment by nkartyshov** [comment]
Fixed https://github.com/AdguardTeam/HttpsExclusions/commit/c5c77f50002d600649b011ea545d14f7e850dac8
