### ISSUE TITLE
Yandex Browser false statistics

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1642]
Seems that AdGuard is blocking its requests and this spins the blocked requests counter

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/33928133-74b113ce-dfed-11e7-9759-6729ca40e551.png)

![image](https://user-images.githubusercontent.com/15856304/33928147-7e1e9972-dfed-11e7-977a-9a4a1744b4f5.png)

</details>

### Customer ID 
1353661, check for logs

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Subscriptions: "English filter", "Spyware filter", "Social media filter", "Russian filter", "Mobile Ads filter"
* HTTPS: On, whitelist, user storage
* Device model: Xiaomi Redmi Note 3
* Operating system and version - 6.0.1
* Rooted or not? N/A
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? N/A

**Comment by ameshkov** [comment]
This is 100% not about blocking, some error is made in the way AG counts statistics.

Could you please ask the user to record debug log for us?

Something like that:
1. Clear statistics in the apps mgmt
2. Switch logging level to record everything
3. Use the app and check apps mgmt from time to time
4. Once he or she sees the spike in Ya browser data, export logs via advanced settings

**Comment by zebrum** [comment]
@evgeniy-ADG does the problem persist?

**Comment by evgeniy-ADG** [comment]
@zebrum I have no idea.

**Comment by vitbortnik** [comment]
@zebrum 
The user bought a new phone. 
So this is not a problem anymore.
