### ISSUE TITLE
Compatibility issue: Calendar Mail.Ru app - "Synchronize" shows error

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1643]
### Steps to reproduce

1. Install Calendar Mail.Ru - https://play.google.com/store/apps/details?id=ru.mail.calendar
2. Turn DNS filtering ON (DNSCrypt)
3. Open app, if it opens, try to synchronise it

### Expected behavior
App should work with no errors

### Actual behavior
App tries to route to `https://mobile-auth/..` and indicates various connection errors, including `ERR_NAME_NOT_RESOLVED`.

Adding to exceptions doesn't help, even turning the protection OFF can't help. Only full uninstalling AdGuard from device helps.

<details><summary>Screenshots:</summary>

![screenshot_20171213-142643](https://user-images.githubusercontent.com/28726429/33947709-2f61d3b4-e036-11e7-8270-2f91637b6dc0.jpg)

![screenshot_20171213-142649](https://user-images.githubusercontent.com/28726429/33947710-312a3010-e036-11e7-94ee-6ceab54d3893.jpg)

</details>

### Logs
[state (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556109/state.1.txt)
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556110/debug.txt) (14:27)
[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556111/debug.1.txt) (14:31)

### Customer ID 
1150428

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy J5
* Operating system and version: Android 7.1.1
* DNS filtering - DNSCrypt (AdGuard DNS)

**Comment by ameshkov** [comment]
This `mobile-auth` thing is specific to users configuration and cannot be reproduced on my side.

Also, the full uninstall requirement is complete nonsense.

However, there's an "error" shown on calendar synchronize, it goes away if you disable https filtering for the app.

**Comment by akmAa** [comment]
The user has sent additional logs, this time with HTTPS filtering disabled.

Timecodes:
1 - 13:44
2 - 13:45
[debug_1344.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1587386/debug_1344.txt)
[debug_13456.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1587387/debug_13456.txt)

**Comment by ameshkov** [comment]
@akmAa plz ask him to disable AdGuard for Calendar app completely (apps mgmt -> app details -> uncheck enabled).
