### ISSUE TITLE
Compatibility issue: AliExpress Shopping app

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1644]
### Steps to reproduce

1. Install AliExpress Shopping - https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd
2. Turn DNS filtering ON (DNSCrypt)
3. Open app, if it opens, try to synchronise it

### Expected behavior
App should show all images

### Actual behavior
Doesn't show any in-app images. Just turn the protection OFF and images loads well.

### Logs
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556153/state.txt)
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556154/debug.txt) (14:38)

### Customer ID 
1150428

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy J5
* Operating system and version: Android 7.1.1
* DNS filtering - DNSCrypt (AdGuard DNS)

**Comment by ameshkov** [comment]
I cannot reproduce this issue

**Comment by ameshkov** [comment]
@altokarev do not mark anything as bug unless you reproduced it and attached screenshots to the issue
