### ISSUE TITLE
Compatibility issue: ООО «Управление Информационными Проектами» Стиль жизни

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1645]
### Steps to reproduce

1. Install AliExpress Shopping - https://play.google.com/store/apps/details?id=com.uip.gosuslugi2
2. Turn DNS filtering ON (DNSCrypt)
3. Open app, you'll see an error

### Expected behavior
App shouldn't be broken

### Actual behavior
It does not work

### Logs
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556153/state.txt)
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1556154/debug.txt) (14:38)

### Customer ID 
780241

### Your environment

* Adguard version: 2.10.164
* Adguard filtering mode: VPN
* Device model: Xiaomi Redmi 4X
* Operating system and version: Android 7.1.2 
* DNS filtering - DNSCrypt (AdGuard DNS)

**Comment by ameshkov** [comment]
@evgeniy-ADG this is a filtering issue, blocking some domain causes it.

It should be reported to AdguardFilters
