### ISSUE TITLE
VK's proxy for Ukrainian users does not enable if the app's traffic is routed through AdGuard

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1646]
https://play.google.com/store/apps/details?id=com.vkontakte.android

### Steps to reproduce

1. Enable AdGuard for VK
2. Try to enable VK's proxy for Ukrainian users
3. VK will say that it had found "no reasons to enable the proxy"

### Expected behavior
VK should enable the proxy even when its traffic is routed thru ADG

### Actual behavior
VK tells that it had found "no reasons to enable the proxy"
Disabling HTTPS filtering will have no effect. The only applicable solution is to completely disable AdGuard traffic routing for VK app

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: LG D405
* Operating system and version (e.g. Android 7.1.2): Android v5.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: No

**Comment by ameshkov** [comment]
Guys, we need to get a "record everything"-level log.

**Comment by akmAa** [comment]
Will provide.

**Comment by ameshkov** [comment]
@akmAa any update on this?

**Comment by Alex-302** [comment]
15:03 - starting VK
15:04 - tried to enable VPN
[adguard (6).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1677745/adguard.6.zip)
