### ISSUE TITLE
Upload to Yandex Disk is slow

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1649]
> 
> очень сильно рубит (снижает) скорость загрузки файлов ( фото ) с телефона в
> облако Яндекс. в 21 - 51 загрузка с вкл фильтром , а в 21 - 52 ( 53 ) с выкл.

ID: 1150428

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy J5 (2016)
* Operating system and version: Android 7.1.1
* Rooted or not? N/A
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: N/A

DNS - off
Filtering method - full
HTTPs: Whitelist, User
Subscriptions: English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

**Comment by ameshkov** [comment]
Is there any change when ad blocking is disabled for Yandex Drive?
