### ISSUE TITLE
Test Adguard and Teamviewer

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#165]
http://forum.adguard.com/showthread.php?7522-Adguard-blocks-Teamviewer-LAN-connection

Test both working through LAN and through TV server.

**Comment by gshumihin** [comment]
Tried to connect to my PC trough LAN, but i cant. Even with disabled adguard. Even more: i still have to insert password after login in with TeamViewer account. 
As i can see, it's TeamViewer problem. Lan was activated.

**Comment by gshumihin** [comment]
Reproduced only with android 5.1. 
Logs:
https://www.dropbox.com/sh/cz6n1ywsn1o4kn1/AAAounssNW7bcl09FUaMvdc5a

**Comment by ameshkov** [comment]
@gshumihin does it help to add Teamviewer to "pref.net.exclusions" in the low-level settings section?

**Comment by gshumihin** [comment]
Adding com.teamviewer.teamviewer.market.mobile to net exclusions wont help.

**Comment by ameshkov** [comment]
That's bad. Could you please collect logs one more time with teamviewer included exclusions list?

Along with the log I'll need an approximate timing:
1. When you've started connecting to the PC
2. What is the PC ip address

**Comment by ameshkov** [comment]
@gshumihin still waiting for log

**Comment by ameshkov** [comment]
@gshumihin logs?

**Comment by gshumihin** [comment]
@ameshkov 
Here is log: https://www.dropbox.com/s/lve9r860occe8z2/adguard.log
1) Time is 22:36
2) IP: 192.168.1.2

**Comment by ameshkov** [comment]
@gshumihin nothing in the log file, we just don't filter teamviewer traffic.

We should use a tcpdump and see what's going on.

**Comment by gshumihin** [comment]
Here's tcpdump on wlan0
https://www.dropbox.com/s/ts8o8isu5gvcp96/dump.pcap
