### ISSUE TITLE
Trimming long rules in the user filter looks random

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1650]
Report from XDA (https://forum.xda-developers.com/showpost.php?p=74839356&postcount=2939):
> Please fix trimming issue with User Filters. "|...." is not acceptable on a QHD resolution screen! Example: "||crashstats-collector.opera.com^" is shown as "||crashstats...". Yet "||tracking.wealthdaily.io^" is shown as "||tracking.wealthdaily.io^"??? And "||app-measurement.com/config/app^" as "||app-measurement.com..."???
So items that fit are sometimes shown, and items that don't fit, are also sometimes shown full width with "||..." and also shown as "||xxxxxxxx.xxxxxxxxx.xxxxx...". It is very random.

@Revertron why could it be?

**Comment by Revertron** [comment]
This is the way Android TextView works :(

**Comment by ameshkov** [comment]
Check this out:
https://stackoverflow.com/questions/9870960/textview-androidellipsize-end-issue
