### ISSUE TITLE
Sorting in the apps management section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1651]
Source:
https://forum.xda-developers.com/showpost.php?p=74839356&postcount=2939

[QUOTE]> Please allow overriding the sort order of the application list. E.g. Sort applications by
> - name (a-z, z-a),
> - size (sml-lrg, lrg-sml),
> - date installed/upgraded (new-old, old-new),
> - traffic used (Wi-Fi / Data),
> - traffic blocked.[/QUOTE]

**Comment by TPS** [comment]
#384?

**Comment by ameshkov** [comment]
@TPS yep, thank you!

Duplicate of #384
