### ISSUE TITLE
Verizon (UPD: not only Verizon) mobile network losing connectivity (Android 4.4.4) 

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#166]
AdGuard causes mobile data connectivity to drop frequently as long as protection is activated. Mobile data works fine if Ad Guard protection is not running.

FQO-491-60456

**Comment by ameshkov** [comment]
I think the issue is caused by the fact that we disable IPv6 for this network.

We do this due to the Android bug:
https://code.google.com/p/android/issues/detail?id=63349

Yet it looks like that solution was wrong in this particular case.

**Comment by ameshkov** [comment]
Here is a special build with IPv6 routes restored for Android 4.4.4:
https://static.adguard.com/android/release/adguard_issue166.apk

Now let's wait for user's feedback.

**Comment by ameshkov** [comment]
One more issue, looks pretty similar:
SNW-900-80998

**Comment by ameshkov** [comment]
One more test build, now with "pref.vpn.ipv6.force" low-level setting:
https://static.adguard.com/android/release/adguard_issue166.apk


With this setting it's possible to force IPv6 filtering.

**Comment by ameshkov** [comment]
Second ticket - it was not the same issue in the end.
First ticket - a month has passed, no more complaints like this.

Status: won't fix for now.
