### ISSUE TITLE
Add Tenta DNS to DNS servers list

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1664]
Here's the user request: I would like to request support to tenta DNS:
https://github.com/tenta-browser/tenta-dns

ID: 1699343

**Comment by vozersky** [comment]
@akmAa it doesn't work with Adguard?

**Comment by akmAa** [comment]
@vozersky It works when you add it manually. The client wants it to be available immediately after installation in the list of available DNS services.
