### ISSUE TITLE
AdGuard is not capturing the mobile data usage correctly

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1665]
> I have monitored the stats for a few days and it seems like AdGuard is not capturing the mobile data usage correctly. For instance, attached are some screenshots comparing the total amount reported by AdGuard and the OS for today.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/34253145-1071f1ea-e64f-11e7-966a-6086288452b9.png)

![image](https://user-images.githubusercontent.com/15856304/34253151-167e56fa-e64f-11e7-8d2d-43e16882d86a.png)

</details>

### Customer ID 
1690598

### Your environment

* Adguard version: 176
* Adguard filtering mode: VPN
* Device model: Google Pixel 2
* Operating system and version Android 8.1
* Rooted or not? N/A
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? N/A

**Comment by evgeniy-ADG** [comment]
UPP: I see that data usage is actually being tracked, but it shows up under WiFi usage instead of mobile.

Logs and screenshots: 1690598

**Comment by ameshkov** [comment]
The same is in my case on Android 8.1.

Also, @Revertron, I guess we have to put network type to the connection context (as you suggested in the very beginning). Otherwise, it's just wrong everytime:0

**Comment by Revertron** [comment]
Done, merged.
