### ISSUE TITLE
Edadeal app getting blocked when its traffic is routed thru AdGuard

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1668]
### Steps to reproduce
1. Download and run https://play.google.com/store/apps/details?id=com.edadeal.android
2. The application's traffic should be filtered by ADG
3. App's catalogue DB will fail to update

### Expected behavior
App should work

### Actual behavior
App's catalogue DB will fail to update

### Customer ID 
1678085

### Your environment

* Adguard version:  2.10.176
* Adguard filtering mode: VPN
* Device model: HUAWEI WAS-LX1
* Operating system and version: Android 7.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: Nothing

**Comment by zebrum** [comment]
so far I haven't noticed any problem with the app. Provide a screenshot were exactly is the problem. Does turning off all filters  help?

**Comment by akmLaVx** [comment]
User reports that the problem is no longer present.
