### ISSUE TITLE
Incompatible with Netgear Arlo

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1669]
### Steps to reproduce
1. Download and use https://play.google.com/store/apps/details?id=com.netgear.android with AdGuard
2. The app will fail to connect to the camera.

### Expected behavior
AdGuard shouldn't prevent the app from working correctly.

### Actual behavior
AdGuard completely blocks the app from getting traffic.

### Customer ID 
1704808

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung SM-G920F
* Operating system and version: Android 7.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by zebrum** [comment]
can't repro since we don't have devices to connect. 
@akmAa did you collect logs?

**Comment by krohn** [comment]
Hi,
I could not see anything blocked in the regular log, but maybe I am just looking at the wrong place? 

After adding arlo.netgear.com to the HTTPS whitelist, the Arlo app is working as expected.

Regards 
Karsten

**Comment by akmAa** [comment]
@zebrum 
[arlo.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1590869/arlo.zip)

**Comment by ameshkov** [comment]
@krohn thank you for the information!

I guess we can simply disable HTTPS filtering for that app by default.

**Comment by zebrum** [comment]
@nkartyshov please add the app to https exclusions

**Comment by nkartyshov** [comment]
added
