### ISSUE TITLE
HTTPS filtering kills Symantec VIP

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1670]
### Steps to reproduce

app: https://play.google.com/store/apps/details?id=com.verisign.mvip.main

1. Enable HTTPS filtering in AdGuard
2. The app will stop receiving and sending authentication requests
3. Add the app to HTTPS filtering exclusions
4. Won't work

### Expected behavior
Should normally receive and send auth requests

### Actual behavior
Does nothing

### Fix

The following FQDN's should be added to HTTPS filtering whitelist by default:

services.vip.symantec.com<http://services.vip.symantec.com>
messaging.vip.symantec.com<http://messaging.vip.symantec.com>

Just need to add these to global https whitelist to prevent similar issues w/other users

### Customer ID 
1707623

### Your environment
Not Applicable - Fix Already Found

**Comment by nkartyshov** [comment]
done
