### ISSUE TITLE
HTTPS filtering kills Ola Cabs

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1672]
Application: https://play.google.com/store/apps/details?id=com.olacabs.customer&hl=uk

### Steps to reproduce
1. Enable HTTPS filtering
2. App will no longer work

### Expected behavior
Should work fine when HTTPS filtering is on

### Actual behavior
It dies. Painfully.

### Customer ID 
1712792

### Debug logs
[Available here](https://github.com/AdguardTeam/AdguardForAndroid/files/1596999/debug.txt)

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: OnePlus A3003
* Operating system and version: Android 8.0
* Rooted or not: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed: None found
* Filtering method: Speedy, HTTPS on
* Filters: "English filter", "Spyware filter", "Social media filter", "Mobile Ads filter"

**Comment by nkartyshov** [comment]
done
