### ISSUE TITLE
AdGuard local proxy disables when a VPN app is launched

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardForAndroid#1673]
### Steps to reproduce
1. Switch AdGuard to Local HTTP Proxy mode;
2. Sideload a VPN application (tested with https://play.google.com/store/apps/details?id=com.simplexsolutionsinc.vpn_unlimited )
3. Run AdGuard HTTP proxy with VPN app simultaneously
4. The proxy will shut down

### Expected behavior
Should work simultaneously

### Actual behavior
Doesn't work simultaneously

### DEBUG level reports
[debug-1254478.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1597321/debug-1254478.txt)

### Customer ID 
1254478

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: Proxy (127.0.0.1:8080)
* Device model: Xiaomi Mi A1
* Operating system and version: Android 7.1.2
* Rooted or not?: No, but the client wants to
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: VPN Unlimited (https://play.google.com/store/apps/details?id=com.simplexsolutionsinc.vpn_unlimited)

**Comment by beeshyams** [comment]
I am the user. I had Malware bytes running. Force stopped and repeated the setup. Same result. It doesn't work

**Comment by beeshyams** [comment]
Update : updated system to 8.0.0 problem remains

**Comment by ameshkov** [comment]
@beeshyams 

According to the log, AdGuard works in the VPN mode.

Are you sure you've switched it to the the "Proxy" with automatic setup?

**Comment by beeshyams** [comment]
Andrey

Thanks for responding

Settings > advanced > proxy mode > manual since my device is not rooted

I just tried and it gives a warning that it cannot set up

Or are you referring to something else ?

Rgds..Shyam

**Comment by ameshkov** [comment]
Yeah, that's the problem, to use AdGuard in proxy mode along with any VPN, you need to have your device rooted.

Alternative solution would be to use AdGuard's outbound proxy settings:
https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy

**Comment by beeshyams** [comment]
Thanks Andrey

There is an open discussion on the forum where a user had this working on a
stock unrooted device. Is that with an older version of your app? Time to
update that thread so that it is clear . Link below

https://forum.adguard.com/index.php?threads/integration-adguard-and-vpn-unlimited.20000/

Can you please confirm that it will work if my device is rooted? I would
like to root my device anyway but would like to wait for few months to be
able to get monthly updates and possibly OS update

Coming to the alternative, do you have the proxy address to be used or do I
need to seek it from VPN provider

Rgds..Shyam

**Comment by beeshyams** [comment]
Also request a  double check since that thread I linked where it is claimed that it works on unrooted devices is not very old

Please don't close the issue unless absolutely confirmed that it doesn't work

**Comment by beeshyams** [comment]
Also , I am not clear if I root my device and succeed in using VPN , is the VPN functionality in any way affected?

**Comment by ameshkov** [comment]
> There is an open discussion on the forum where a user had this working on a stock unrooted device. Is that with an older version of your app? Time to update that thread so that it is clear . Link below

Tbh, it depends on the VPN app. Most of the VPN apps simply ignore the Wi-Fi proxy settings, and your case proves that vpnunlimited does that.

> Also , I am not clear if I root my device and succeed in using VPN , is the VPN functionality in any way affected?

No, it will continue to work as it did.

**Comment by beeshyams** [comment]
Thanks Andrey

But the app I have is the same as mentioned in that thread

Anyway, let's see how it goes

Rgds..Shyam

**Comment by arooni** [comment]
So to be clear; there's *no way* to run adguard along side vpn unlimited on an unrooted device?

**Comment by zzebrum** [comment]
@arooni yeap.

**Comment by arooni** [comment]
@zzebrum thanks!  what if i have a *rooted* pixel xl.  would it work in that case with vpn unlimited?  or is just not going to work with that VPN?

**Comment by zzebrum** [comment]
@arooni it should work: your VPN + AG in auto proxy filtering mode.
