### ISSUE TITLE
AdGuard breaks NTLM authentication (Aquamail)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1676]
### Steps to reproduce
1. Use Aquamail with HTTPS filtering enabled
2. Won't work

### Expected behavior
Should work with HTTPS filtering

### Actual behavior
Doesn't work with HTTPS filtering

### Debug logs
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1603008/debug.txt)
~15:08

### Customer ID 
1658391

### Your environment

* Adguard version:  2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung SM-T819
* Operating system and version: Android 7.0
* Rooted or not: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: com.simplexsolutionsinc.vpn_unlimited

**Comment by gustms** [comment]
My system works just fine with AquaMail, and has worked for a long time, when using AdGuard in VPN mode.
Specs are a bit different:
Device: LG G2
Android: 5.0.2
No other VPN.

But mine has the Pro key installed as well. Maybe it is the server you are trying to access? Mine is Outlook and my university's.

**Comment by ameshkov** [comment]
I am pretty sure it depends on the mail provider and not just on the app.

**Comment by nkartyshov** [comment]
Aquamail works fine with the https filtering.
Problem with authorization from the server `mail.oxy.com`.

**Comment by ameshkov** [comment]
On the other hand, this is not the first time we face an issue with a mail server that we shouldn't filter.

If there're no ads in Aquamail, regular filtering (without HTTPS) should be enough.

**Comment by Revertron** [comment]
In a case of pure mail application we would not interfere as we are not filtering mail ports.

**Comment by patrickdrd** [comment]
I had to whitelist my company's email server in order for it to work

**Comment by nkartyshov** [comment]
@ameshkov We can exclude AquaMail for https filtering, but it has ads

**Comment by patrickdrd** [comment]
I've written it above, there is absolutely no need to disable https filtering for aquamail, just add the server you're interested in in adguard's whitelist

**Comment by ameshkov** [comment]
Actually, it is more likely that AdGuard breaks NTLM authentication used by that server. I can't say why yet, we should re-test it once the corelibs-integrated build of AdGuard is ready.
