### ISSUE TITLE
Cache folder size is extremely large

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1677]
### Steps to reproduce
No clear steps have been given to reproduce the situation. According to the user, daily usage should suffice.

### Expected behavior
Reasonable cache folder size

### Actual behavior
The user reports a 27GB cache folder size

### Debug logs
[debug-27gb.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1603453/debug-27gb.txt)

### Customer ID 
1712999

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Sony G8142
* Operating system and version: Android 8.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by ameshkov** [comment]
The log file is extremely large due to this single line:
```
11:03:11.228 [pool-1-thread-1] INFO  com.adguard.android.ui.utils.o - Delay VPN auto restart check as ServiceManager is in transition
11:03:11.228 [pool-1-thread-1] INFO  com.adguard.android.ui.utils.o - Start VPN auto restart check
```

We should limit the number of retries to avoid such a situation.

**Comment by omarcey** [comment]
is this already fixed ?

**Comment by zebrum** [comment]
The issue will be closed once it's fixed.

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/285`
