### ISSUE TITLE
Speed test on speedof.me doesn't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#1678]
### Steps to reproduce

1. Disable all fiter lists
2. Open this website in Chrome - https://speedof.me/m/
3. Start test
4. It doesn't work or you need to wait very long time and results is really bad

### Expected behavior

Speed test should works correctly

### Actual behavior

Speed test doesn't work

<details><summary>Screenshot:</summary>

![screenshot_2018-01-04-16-39-35](https://user-images.githubusercontent.com/29142494/34571432-da93da54-f16e-11e7-9d2e-b759e21ffb85.png)

</details>

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: LG G3
* Operating system and version: Android 6.0
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? -

https://github.com/AdguardTeam/AdguardFilters/issues/9195

**Comment by ameshkov** [comment]
Moved to CoreLibs:
https://github.com/AdguardTeam/CoreLibs/issues/160
