### ISSUE TITLE
obsolete cipher suite

### ISSUE THREAD

**Issue by wowkmw** [AdguardTeam/AdguardForAndroid#1680]
### Steps to reproduce

1.HTTPS filtering on android is causing google chrome to report "secure connection using **obsolete cipher suite**".
2.
3.
4.

### Expected behavior

Connection should be using a modern cipher suite.
### Actual behavior

Instead, https connection is using obsolete cipher suite.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 2.10
* Adguard filtering mode: VPN
* Device model: Zuk Z2 plus
* Operating system and version: Android 7.1.2
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NO.

**Comment by ameshkov** [comment]
This issue will go away when we finish the new filtering engine integration (the ETA is a couple of months).
