### ISSUE TITLE
Search doesn't retain search term

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1681]
In App Management, if you do a search for an app (e.g., Google), tap that app, and then tap the back navigation button (Android nav button, not in-app), AdGuard doesn't retain what you've searched for. Now, maybe this isn't the biggest issue, but it's inconsistent with other Android apps, IMO.

In Gmail, if I do a search for AdGuard, click an email, and navigate back, I still see all my AdGuard emails. If in the Play Store I do a generic search like VPN, click an app, and then navigate back, I'm still looking at results for VPN.

Maybe it's by design because it's a smaller use case, or maybe it was purposely decided not to retain the search terms. But if someone *is* doing a generic search in AdGuard for something like Google (suppose they want to quickly select multiple Google apps one after the other to disable filtering or something), then they have to re-search each and every time.
  
 Addendum: This is actually the way the Filtering Log works (i.e., how I think it should)!

**Comment by ameshkov** [comment]
Makes sense, thank you!

**Comment by vozersky** [comment]
merged into #3378
