### ISSUE TITLE
[Feature Suggestion] AdGuard inAppBrowser specifically made to detect contents/elements on websites to block

### ISSUE THREAD

**Issue by Excarius** [AdguardTeam/AdguardForAndroid#1683]
So, the PC version 6.2 have a feature in browsers allowing you to block ads or any other contents to appear (adlist not blocking it?) But by marking which content/element a user want to block it even for the future visits, it auto detects it and blocks it by adding all necessary info to rules tables.

I think we should have such a big feature in Android, or to have AdGuard make a simple browser specifically made for this purpose, to detect elements/ads a user dont want by selecting it, and clicking "Block" button.

This could make things easier rather than always blocking it.

I love this feature on PC and such a feature on Android OS would be lovely too,  because there are certain sites ocasionally where I see ads.

And we could have a "Submit" button to submit user added rules (added by this mechanism) to developers to help in a more time efficient way for end-users.

Im not sure how hard coding is, this is just an idea that I thought of, by adding this mechanism, I am confident many but many AdGuard users will be taking their time to contribute to block ads, and help create a more rich filtering list.

Or, certain users having the ability to submit their user rules to developers to make things easier for devs (considering thousands of users submitting data to devs, and not all being ads but a part of certain site's content, resulting an poor quality filtering.

Or few community members dedicated to sort it out and forward it.

Im not sure, something like this could be a huge benefit for both filter maintainers, consumers and for the AdGuard team itself.

As for the list, the list could be named something like "AdGuard UserSubmitted Filters" separately for those who wants to use it, or not.

With two separate filters, one being "Stable" and other one "Experimental" which could have contents/elements added in belonging not to an ads but rather, a website.

Im not sure how this works, if what I said doesn't make sense with how filtering system works, then my apologizes, this idea was inspired by the PC version of AdGuard V6.2 allowing users to manually select elements/content on a specific area of a website in Chrome/Firefox etc to be blocked and added to AdGuards rules list.

**Comment by ameshkov** [comment]
I agree. What was stopping me before is that I couldn't come up with an idea of how to draw it properly and not too annoying. I've stumbled upon Samsung's helper widget and it inspired me:)

AG Assistant task:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1696

What for "user submitted" rules, this is much more complicated. Rules created with the help of AG Assistant are good at doing what they're supposed to -- blocking the element you want to be blocked. But they aren't good enough to be added to the main filters, just do not fit the quality requirements. Quality filtering rules require filter maintainer to have a good understanding of HTML/CSS.
