### ISSUE TITLE
Option to use only user-selected networks as WiFi

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1684]
An option that allows users to select networks (such as trusted home network) as WiFi data and treat every other network as Cellular data can be a useful feature. For example, I may want to allow an app to update or send sensitive data over only WiFi but not over public WiFi, a paid WiFi with limited bandwidth or a WiFi network which I don't trust. For these circumstances, the suggested option can come in very handy.

**Comment by artemiv4nov** [comment]
This task could be solved with Tasker or any other automation-application, please try using them
