### ISSUE TITLE
ru.yandex.money

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1686]
> Блокирует вход в аккаунт Яндекс.Деньги (приложение) через https, отключил фильтрацию по https.

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: Proxy(auto)
* Device model: Letv X900+
* Operating system and version 6.0.1
* Rooted or not? +

**Comment by nkartyshov** [comment]
Added
