### ISSUE TITLE
Don't filter the ZTELink app

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/AdguardForAndroid#1687]
При подключение к интернету через wi-fi интернет периодически полностью блокируется. Когда открываю AG то он вылетает с ошибкой, иногда не сразу когда его открываю, а когда пытаюсь остановить защиту.
Включение 
pref.vpn.disable.pause
pref.vpn.disable.reconfiigure
не дает не какого результата.

**UPD** нам нужно добавить в исключения приложение https://play.google.com/store/apps/details?id=com.zte.android.ztelink&hl=en

**Comment by vozersky** [comment]
а логи можно?

**Comment by zovihuxij** [comment]
@vozersky , отправлял через поддержку, id к сожалению нет, отправлял через почту I110001[собака]ya.ru

**Comment by zovihuxij** [comment]
@vozersky , кажется нашел причину такого поведения.
![screenshot_20180116-133749](https://user-images.githubusercontent.com/20907093/34984774-13299a2c-fac3-11e7-843f-b6a65b30b4c7.png)
Похоже на какой-то конфликт между этим приложением и AG, как его удалил второй день ошибка не появляется.

**Comment by ameshkov** [comment]
@zovihuxij прикольно. А если фильтрацию этого приложения в AG отключить?

**Comment by zovihuxij** [comment]
Вроде помогает. Покрайне мере за эти пару часов ошибки не было.

**Comment by ameshkov** [comment]
Интересная ботва, добавим в исключения тогда:
https://play.google.com/store/apps/details?id=com.zte.android.ztelink&hl=en

**Comment by zovihuxij** [comment]
Сегодня еще раз словил ошибку первый раз за 3 дня, хотя приложении в исключениях, может все таки логи чекните, а то я уже чет не уверен)

**Comment by ameshkov** [comment]
@zovihuxij а это по ходу другая ошибка: `java.lang.OutOfMemoryError: Could not allocate JNI Env`

Надо следующей беты дождаться, там этот баг в сетевом стеке исправлен.

**Comment by nkartyshov** [comment]
Отключил фильтрацию по умолчанию
