### ISSUE TITLE
App doesn't show up if another app has the same name?

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1690]
I installed 'Simple Gallery' app but when I look in App Management the only match for gallery is the stock 'Gallery' app my phone already had. I don't know why the Simple Gallery app isn't showing up. The only reason I can think of is they both have the same name (Simple Gallery installs with name 'Gallery')

**Comment by Revertron** [comment]
It is simple - Simple Gallery doesn't have any permissions to work with network connections.
If it can't use internet why do you need it to clutter app list? :)

**Comment by Kusresa** [comment]
I see, thanks.
