### ISSUE TITLE
Option under Proxy settings to apply only for selected networks/apps

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1691]
An option to use a proxy only for a user-selected network or a only for a certain app will be very useful. Could be like "Use the proxy for: All Networks / User-selected networks / All but User-selected network". Currently if a proxy is set it must be used for all apps and networks system-wide.

**Comment by ameshkov** [comment]
Merged into: https://github.com/AdguardTeam/AdguardForAndroid/issues/1776
