### ISSUE TITLE
AdGuard breaks after Android update

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1692]
### Steps to reproduce
1. Install an Android update

### Expected behavior
App should work just fine

### Actual behavior
The "Enable protection" button becomes greyed out. User is unable to resume protection

### Debug log
[debug (2).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1626672/debug.2.txt)

### Customer ID 
1457433

### Your environment
* Adguard version: 8.1.0
* Adguard filtering mode: VPN
* Device model: Huawei Nexus 6P
* Operating system and version: Android 8.1
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by ameshkov** [comment]
```
04:17:41.283 [Binder:6212_3] INFO  c.a.android.vpn.AdguardVpnService - Third party VPN app has been detected: com.google.android.apps.freighter
04:17:41.284 [Binder:6212_3] INFO  c.a.android.vpn.AdguardVpnService - Third party VPN app has been detected: com.comodo.cisme.antivirus
04:17:41.284 [Binder:6212_3] INFO  c.a.android.vpn.AdguardVpnService - Third party VPN app has been detected: com.google.android.apps.gcs
```

One of these apps messes with AG and does not let it keep the VPN up. I bet it's comodo.

**Comment by akmLaVx** [comment]
User has been notified, please wait for response.
