### ISSUE TITLE
Random shutdowns on 8.0 + Magisk

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1693]
### Steps to reproduce
1. No known steps. Happens absolutely randomly.

### Expected behavior
Should work stable

### Actual behavior
Dies randomly

### Debug logs
[debug (3).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1627473/debug.3.txt)

### Customer ID 
1718944

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: Local HTTP proxy (port 8080)
* Device model: OnePlus A3003
* Operating system and version: Android 8.0
* Rooted or not?: Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by Excarius** [comment]
Correction:
Adguard Filtering mode: Local HTTP Proxy
Local proxy port: 8080 (Stock)
Rooted or not?: Yes

I have VPN apps but, I run AdGuard with root and connect to a VPN while keeping AdGuard protection on, so it is not my VPN apps.

As of the cleaning apps, I only have SdMaid Cleaner which I set cleaning to fully manual which I do once per month or so, it cant be neither SDMaid Cleaner.

I use MagiskSU (Root mechanism) version: 15.3

The specified log is very long but I immediately sent log when it occured, so the problem could be around the very end of the log.

Timestamp: 2018-01/12 - 14:30

**Comment by akmLaVx** [comment]
@Excarius Sorry for the confusion, fixed with the correct info.

**Comment by Excarius** [comment]
Correction: I am not using VPN at all while AdGuard is on, but what I try to mean is that using both VPN and AdGuard at the same time works without any problems, but the log I provided has no log of me turning on my VPN at all, so the VPN may conflict with AdGuard theory will make no sense as AdGuard seems to be somehow die (despite me set up notification on etc so it doesnt get killed by the system, so I always have notification of AdGuard on).

**Comment by ameshkov** [comment]
Good old OnePlus killing frenzy issue: #1385  

You should pin AG in the recent apps to fix it: https://github.com/AdguardTeam/AdguardForAndroid/issues/1385#issuecomment-348964378
