### ISSUE TITLE
LAN access only option

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1695]
Some apps don't need WiFi or Data access but make use of LAN. An option to allow only LAN access would be good.

**Comment by ameshkov** [comment]
Lan is quite rare on mobile devices.

At the moment Wi-Fi includes Lan connections.

**Comment by Versty** [comment]
@Kusresa The desired configuration can be set in Firewall settings starting from AdGuard 4.0.
