### ISSUE TITLE
Please divide now "User Filter" to "Subscriptions" and "User Rules".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1697]
1. Change "User Filter" to "User Filters".
2. In the section of "User Filters", there are 2 sections: "Subscriptions" and "User Rules".
3. For large numbers of rules, set profiles of subscription (custom filters) in "Subscriptions".
4. The profile of subscription supports to import not only adblock rule syntax but also a hosts file from a URL.
5. Users can add, delete, cancel, ok and edit profiles of subscriptions.
6. Each subscription has a tap for enabling or disabling itself.
7. When clicking the icon of "Checking for updates" in the main screen, it'll also together update subscriptions enabled.
8. Show updated time in the section of "Subscriptions".
9. For a few numbers of rules, set rules in "User Rules" (= original "User Filter").
10. A tap for enabling or disabling the whole "User Rules".

**Comment by ameshkov** [comment]
That'd be covered by #13
