### ISSUE TITLE
AdGuard does not recognize the certificate if moved to the system storage w/ MoveCerts!

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1700]
> В настройках приложения Adguard включено уведомление «Уведомление без иконки», но всё равно отображается как если было бы включено «По умолчанию». И при переносе Adguard Certificate в системные с помощью Move Certs получается сертификат 1.563.9473.49 (или что-то подобное), и Adguard его не распознает. Переустановка приложений не помогла.

### Steps to reproduce

1. Install AdGuard and MoveCerts! v.1.0.2
2. Enable the HTTPS filtering, move the cert to the system storage
3. Go back to AdGuard, navigate to the HTTPS filtering section, see it disabled
4. When turning the HTTPS filtering on, it generates a new cert;

### Expected behavior

AdGuard recognizes the certificate

### Actual behavior

It disables the HTTPS filtering and installs a certificate afresh

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/35212442-cd005b9a-ff62-11e7-9d6f-8b4917167bf5.png)

</details>

### Customer ID 
939612

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: Proxy(auto)
* Device model: OnePlus ONEPLUS A3003
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? YES
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? N/A

**Comment by nkartyshov** [comment]
@evgeniy-ADG 
I cannot reproduce this problem.
The certificate `88cba841.0` exactly is AdGuard CA? 
I see two certificate on the screen and I know the first certificate is AdGuard CA.

**Comment by Rakleed** [comment]
The certificate `88cba841.0` is AdGuard CA, which turned out after his transfer to the system with the help of MoveCerts!

**Comment by nkartyshov** [comment]
@Rakleed Can you send the certificate `88cba841.0` and your app settings for analyse?

**Comment by Rakleed** [comment]
@nkartyshov how can I do it?

**Comment by nkartyshov** [comment]
@Rakleed

**Comment by Rakleed** [comment]
Root Certificate Manager does not see certificates `88cba841.0` or `AdGuard Personal CA`.

[adguard_settings_2.10.176_2501_1544.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1664009/adguard_settings_2.10.176_2501_1544.zip)

**Comment by nkartyshov** [comment]
@Rakleed 
Try to install app https://play.google.com/store/apps/details?id=com.jrummy.root.browserfree and go to folder `/system/etc/security/cacerts`.
Find to this folder the certificate `88cba841.0` and copy to your sdcard.

**Comment by ameshkov** [comment]
Guys, let's wait for the first beta where we add functionality for moving the certificate from within AdGuard

**Comment by ameshkov** [comment]
@Rakleed could you please check out the alpha version?
https://uploads.adguard.com/up04_vfvcb_adguard-v2.11.14-alpha.apk

You can now move certificate to the root store from within AdGuard.

**Comment by Rakleed** [comment]
It was fixed. Only when there is already a public beta version of Aduard?

**Comment by ameshkov** [comment]
Expect it tomorrow, thank you!
