### ISSUE TITLE
nl.rijksoverheid.digid.pub - HTTPS filtering issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1701]
https://play.google.com/store/apps/details?id=nl.rijksoverheid.digid.pub&hl

> I didn't know I could disable HTTP filtering for specific apps. This indeed solved the problem (the app gave an error stating no connection could be made) and has no side effects as the app doesn't contain any ads.

**Comment by nkartyshov** [comment]
added
