### ISSUE TITLE
AdGuard crashing and protection stopped running

### ISSUE THREAD

**Issue by medoiq** [AdguardTeam/AdguardForAndroid#1702]
I use adguard latest version and when disconnect  internet or connect again AdGuard protection stopped running
android 4.4.2
rooted

**Comment by ameshkov** [comment]
I'd need to see the logs, could you please reproduce the issue and then export the logs?

**Comment by ministr91** [comment]
во, у меня точно такая же проблема была раньше. Спокойно сидел в инете, потом смотрю - ни один сайт не открывает, думал дело в защите, выключил - включил и все норм стало.

**Comment by ministr91** [comment]
что-то подобное было уже в этой теме, даже логи прикрепил. https://github.com/AdguardTeam/AdguardForAndroid/issues/1631
