### ISSUE TITLE
Central Weather Bureau app is abnormal. (compatibility)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1705]
The app is made by Taiwanese Central Weather Bureau.
http://www.cwb.gov.tw/eng/index.htm

For phone:
https://play.google.com/store/apps/details?id=org.cwb

For tablet:
https://play.google.com/store/apps/details?id=gov.cwb_pad

Normal state:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XN0FHgT.jpg)
</details><br/>

Abnormal state:
If enabling AdGuard HTTPS filtering, it can't normally import data.
No data.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ruQm7f7.png)
</details><br/>

After adding gov.tw in the whitelist of HTTPS filtering, it seems that the issue is solved.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/TPTeQ8u.png)
</details><br/>

When visiting the websites of Taiwanese government with AdGuard, there is the issue.
May you solve it in default?
Maybe add gov.tw in the whitelist of HTTPS filtering in default.

Thanks.

**Comment by zebrum** [comment]
reproduced

**Comment by zebrum** [comment]
resolved https://github.com/AdguardTeam/HttpsExclusions/commit/543b5c4e201e054e26c3d56a03b45410a4713b7c
