### ISSUE TITLE
Please divide now Filtering log to HTTP(S) Filtering Log and DNS Requests Log.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1706]
This is now interface in Filtering log.
HTTPS Filtering and DNS Requests are mixed in the same log.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Kvl0kgP.png)
</details><br/>

May you separate them?
A visible frame lets us know which log we are using.
(Separated by thick, thin or dark/light color frame.)
Just an idea / example.
Maybe you have another better method and layout to indicate which log we are using.

For HTTP(S) Filtering:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ltNAQDF.png)
</details><br/>

For DNS Requests:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/L2K63r0.png)
</details><br/>

**Comment by vozersky** [comment]
why https only? where should http requests go? :)
I don't really think it is necessary, tbh, you can type "dns" in search field and see dns requests only if you really need it

**Comment by lancelot-moon** [comment]
Хорошо, how about HTTP(S) Log? XDD
When enabling DNS filtering, they are mixed.
I don't like to see DNS requests when I just wish HTTPS request but I wish to enable DNS filtering...

**Comment by vozersky** [comment]
merged into #3378
