### ISSUE TITLE
An option to reset HTTPS filtering's whitelist or blacklist to default

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1707]
1. When editing HTTPS filtering's whitelist or blacklist, maybe carelessly delete other content.
Please add a feature to separately reset HTTPS filtering's whitelist or blacklist to default.

2. Honestly, the layout of HTTPS filtering's whitelist is a little primitive...
Is it possible to improve it?

3. Does the feature "export settings" include modified HTTPS filtering's whitelist & blacklist?

Thanks.

**Comment by vozersky** [comment]
> Does the feature "export settings" include modified HTTPS filtering's whitelist & blacklist?

yes, it does

**Comment by Sailor-Chibimoon** [comment]
@lancelot-moon there was an earthquake in Taiwan, i hope you are ok. 😊😊✌️✌️

**Comment by admitrevskiy** [comment]
"Reset" feature was added to HTTPS whte/black list

Testing instructions:
-Reinstall AG
-Go to HTTPS white/black list
-Change it
-Find `Reset` in menu and tap it

Expected behavior:
HTTPS white(black) list is reset to default

**Comment by lancelot-moon** [comment]
Which version has the reset function for HTTPS whitelist and blacklist?
v2.12.178 nightly version or next one?

**Comment by admitrevskiy** [comment]
@lancelot-moon Hi
This feature will be available in the next nightly
Testing instructions are written for our QA =)
