### ISSUE TITLE
Can AdGuard delete its user certificate when uninstalling it?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1708]
After uninstalling AdGuard, its certificates are still in user store.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cFIT4T0.png)
</details><br/>

Will those the same name's certificates cause a issue?
Is it possible that AdGuard automatically deletes its user certificate when uninstalling AdGuard every time?
Or can I only delete them manually?

**Comment by Revertron** [comment]
Unfortunately, no. Apps can not delete user certificates.

You can delete all of them manually, there is no problem.
And there is no problem if you have several number of old certificates.
