### ISSUE TITLE
HTTPS filtering without root bypass?

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1709]
I came across this article: https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/

Are any of the techniques there able to be used by AdGuard to allow HTTPS filtering to work fully without needing root?

**Comment by Revertron** [comment]
As you could see in the article, all the techniques need to repackage or make some modifications of _every app_ in question. This is not doable in the scope of AdGuard.
