### ISSUE TITLE
The public DNSCrypt resolvers list is now located at download.dnscrypt.info

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1712]
The link: 
https://download.dnscrypt.info/dnscrypt-resolvers/v1/dnscrypt-resolvers.csv

Change the build script accordingly.

**Comment by nkartyshov** [comment]
The DnsCrypt changed the file format. 
New resolvers list: https://download.dnscrypt.info/dnscrypt-resolvers/v2/public-resolvers.md

**Comment by nkartyshov** [comment]
Build script was changed in the issue https://github.com/AdguardTeam/AdguardForAndroid/issues/1831
