### ISSUE TITLE
Can't enable protection on HTC U11 / Android 8.0.0

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1713]
> Не могу активировать включение защиты, кнопка вкл не активна.

### Actual behavior

<details><summary>Logs:</summary>

[debug (2).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1678310/debug.2.txt.zip)

Повторилось в 17.50.

</details>

### Customer ID 
1745506

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN 
* Device model: HTC U11
* Operating system and version 8.0.0 (sdk=26)
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by vozersky** [comment]
requested more data

**Comment by lancelot-moon** [comment]
Mine is HTC U11.
I can try for you.
But there is no reproduction step.
Too less information and detail.

**Comment by evgeniy-ADG** [comment]
The original reporter didn't reply.
