### ISSUE TITLE
(Android TV) Option to install cert directly to system

### ISSUE THREAD

**Issue by worstperson** [AdguardTeam/AdguardForAndroid#1714]
On Android TV, user certificates are not supported. When selecting the toggle to enable HTTPS filtering, the dialogue opens where you can name the certificate, but proceeding will fail and the toggle will revert to off. To get past this, I suggest a feature be added to install/remove the certificate directly to the system. Adguard should also be able detect a previously installed cert and offer to remove it if app data is cleared.

Alternatively, you could make generation and installation two separate steps. This way, the certificate can still be generated and the user can copy it from their device, convert it to a format that the system expects, and manually inject it.

This should also provide information about the symptoms of cert pinning and what to do about it(disable https filtering for the app or use SSLUnpinning with Xposed to bypass).

**Comment by worstperson** [comment]
I found that it is possible to generate the system cert on one device and copy it and Adguard's data to an Android TV device(tested Nexus Player, 8.0). System certs are located here, sort by date:
/system/etc/security/cacerts
I tested with Titanium Backup
The device generating the cert needs to be Android 5+

**Comment by ameshkov** [comment]
Sorry for the late reply.

In v2.11 update, there will be an option to move certificate to the system store from withing AG settings.
