### ISSUE TITLE
App traffic is blocked on Android 4.X even when it should not be filtered at all

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1715]
Originally reported on 4pda:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=69529395

### Steps to reproduce

1. Install AdGuard on an old device that does not support `VpnService.addDisallowedApplication` method.
2. Open apps management, open app details for a browser app
3. Block network access there
4. Uncheck "Enabled"
5. Run the browser and try to open any website

### Expected behavior
Everything works.

### Actual behavior
The network access is blocked despite that it should not be filtered.

**Comment by Revertron** [comment]
Fixed.
