### ISSUE TITLE
1st line of imported user filter rules is always interpreted as actual rule

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1717]
### Steps to reproduce
1. Import any user filter rules list from URL
2. The first line will always be counted as rule, even when it is commented

### Expected behavior
Filter should correctly recognize and omit commented lines.

### Actual behavior
The first line will always be counted as rule, even when it is commented

### Customer ID 
1553302

### Your environment
Repro
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: LG D405
* Operating system and version: Android 5.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None

**Comment by zebrum** [comment]
#1313 

need to recheck.

@akmLaVx any specific file you try to import?

**Comment by FlyPigsFly** [comment]
Original reporter here...

Try this URL
https://docs.google.com/document/d/1owQufJEU1nCwYe4wrj7asssC8a0NkGxr1zM0Xdck9k8/export?format=txt

**Comment by nkartyshov** [comment]
fixed
