### ISSUE TITLE
com.droid4you.application.wallet

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1718]
@adguard-bot commented on [Tue Jan 09 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.droid4you.application.wallet&hl=en](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.droid4you.application.wallet%26hl%3Den)
### Comment
Username: @carlylemiii
> In the app, if you try to add a bank account to sync (and HTTPS filtering is enabled for the app, which it is by default), you get the error "Something went wrong" and you can select neither a country nor bank name.
> 
> You get here by going Settings > Accounts >  Plus button > Bank Sync.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/YGQTgCf.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 2.10.176
AdGuard version: | 2.10.176
AdGuard mode: | VPN
Filtering quality: | High-speed
HTTPS filtering: | enabled
Filters: | English,<br>Spyware,<br>Social media,<br>Mobile Ads,<br>Annoyances

---

@carlylemiii commented on [Tue Jan 09 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356385327)

Here are logs:

[adguard_logs_2.10.176_0801_2301.zip](https://github.com/AdguardTeam/AdguardFilters/files/1616325/adguard_logs_2.10.176_0801_2301.zip)

---

@Alex-302 commented on [Wed Jan 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356670853)

Please try to add this domain to ***HTTPS*** whitelist
`budgetbankers.com`

---

@carlylemiii commented on [Wed Jan 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356681694)

That resolves it.

---

@Alex-302 commented on [Wed Jan 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356682197)

Ok, thanks.

---

@carlylemiii commented on [Wed Jan 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356686440)

Scheiß, I lied. I had somehow turned off AdGuard and not realized it.

---

@Alex-302 commented on [Wed Jan 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356724924)

So exclusion does not work?

---

@carlylemiii commented on [Wed Jan 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/9584#issuecomment-356725360)

Right, adding that domain to the https whitelist doesn't work. It does work if I disable https filtering for that app entirely.

**Comment by nkartyshov** [comment]
done
