### ISSUE TITLE
Video on mobile.france.tv doesn't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#1719]
### Steps to reproduce

1. Disable all filter lists
2. Go here - https://mobile.france.tv/france-2/unite-42/saison-1/383233-vote-utile.html

### Expected behavior

Video should work or it should be a notice that video is geolocked

<details><summary>Screenshot:</summary>
AdGuard disabled

![image](https://user-images.githubusercontent.com/29142494/36001240-fd0271f4-0d25-11e8-9d4b-ebb6fa77f2bb.png)

</details>

### Actual behavior

Video doesn't work/there is no notice that video is geolocked

<details><summary>Screenshot:</summary>
AdGuard enabled (all filter lists disabled)

![image](https://user-images.githubusercontent.com/29142494/36000951-06774a3a-0d25-11e8-9a3e-1b668355841e.png)

</details>

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: LG G3
* Operating system and version: Android 6.0
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? -

https://github.com/AdguardTeam/AdguardFilters/issues/10330

**Comment by nkartyshov** [comment]
fixed
