### ISSUE TITLE
A bunch of Firewall feature requests

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#172]
TODO: Split these into separate tasks

http://forum.adguard.com/showthread.php?7609-very-important-wishlist-(or-app-won-t-be-practical)
- Firewall should only allow BY DEFAULT apps updates if wi-fi is available and block updates in data mode (but add an option to disable this default rule). 
- Better interface. It's annoying and time consuming that the user must click on each app to choose what to enable / disable. Please look how others firewalls are doint it. LossNet Firewall NoRoot, AFWall+ ; 
  AFWall+ ; Grey Shirts Firewall NoRoot ; DroidWall ; ... Much more convenient !
- FIREWALL: Ask the user to create a rule when an app try to connect to internet for the first time 
- FIREWALL: Ask a feature to geoblock specific countries or continents (similar to LossNet Firewall). 
- FIREWALL: add a clever "economic bandwidth" mode to avoid showing/downloading (big) pictures and videos if data mode is enabled (only big pictures and videos will be filtered not navigation buttons). 
- FIREWALL: add an option to cache specific websites to allow next session to be quicker and without losing data bandwidth.

**Comment by evgeniy-ADG** [comment]
+ it can be more helpful if one can set data limits, depending on ISP caps

ZSL-475-65638

**Comment by evgeniy-ADG** [comment]
> Зайдя в приложение мы отключаем все проги сразу, от интернета, дале после того как нам понадобилось воти в какую либо прогу на экране появляется окошко в которм сказанно что данная прога отключена от интернета и тутже опции вкл тоесть сразу можно данную программу подключить к интернету а при выходе выключить. Также допустим можно зделать в настройках сразу опции автоматического подключения программы к интернету когда мы в нее входим и отключению когда выходим! Поверте это очень удобно! 

HJE-507-63731

**Comment by evgeniy-ADG** [comment]
Possibilité de remise à zéro automatique des statistiques à un jour fixe dans le mois
MYP-274-43165

**Comment by evgeniy-ADG** [comment]
> The features I'm talking about are the ones that this app has
> https://play.google.com/store/apps/details?id=com.yirgalab.dzzz&hl=es
> 
> Since adguard has firewall and it uses a vpn implementing the features of
> this app should be very easy.
> I have tried doze and you can really save a lot of battery, like a 15-20%
> in my case.

YIK-943-73037

**Comment by ameshkov** [comment]
Yeah, we will definitely add Doze feature in one of the future releases.

**Comment by evgeniy-ADG** [comment]
But there is no screen to see a real time list of apps and processes, counting the ads blocked. Whit a screen like this, it would be very easy to find which apps are most ad consuming and which are working and doing their dirty job while no one is looking. Please consider to implement this. Thanks you very much!

<details>
Today I noticed Adguard is blocking about 5 ads each some minutes, and I think maybe some app is loading them in background. I doesn't not have too much apps and I'm very cautious about what I install, so I'm worried about. From Adguard main screen, I can see the real time counter going up.  But there is no screen to see a real time list of apps and processes, counting the ads blocked. Whit a screen like this, it would be very easy to find which apps are most ad consuming and which are working and doing their dirty job while no one is looking. Please consider to implement this. Thanks you very much!

**Comment by ameshkov** [comment]
Stats on the firewall screen are updated in real time.

**Comment by Bohdan-SUP** [comment]
Add option to disable sound and vibration signals, but keep the on-screen notification - SKD-470-96269

**Comment by vbagirov** [comment]
Another request is to let user manually set when the next day 'starts', in terms of counting daily traffic.

https://forum.adguard.com/index.php?threads/18420/#post-121573

**Comment by TPS** [comment]
> Another request is to let user manually set when the next day 'starts', in terms of counting daily traffic.

@vbagirov Are there mobile carriers that _don't_ use local midnight for this?  (GTranslate fails me for that forum link.…)

**Comment by vbagirov** [comment]
@TPS obviously, some mobile carriers start the countdown at other times, for example at 3am, as in the case of this guy from forum. Additionally, it can be complicated by nuances of tariff plan - e.g. data is free at night etc.

**Comment by TPS** [comment]
Well, that'll be the thing I learn today.  😲  I've never heard of a mobile operator doing that, but my experience is limited mostly to the US.

**Comment by TPS** [comment]
RFE/C: Block IPv4 & IPv6 individually per app, e.g., if ads get loaded on v6, while app uses v4?

Also, can #1031 be merged into _this_ issue?

**Comment by Bluscream** [comment]
Also please have a option to only allow foreground app to use 3g/wifi

**Comment by ameshkov** [comment]
@TPS we should first find out what's the problem with #1026 and why it is not routed through AG.

**Comment by TPS** [comment]
@ameshkov If logging is enabled for the requests that are wholesale-blocked (e.g., IPv6 is global/app-blocked, or app is completely blocked from network), then per-IPv× blocking _will_ help debug it, as well as provide a quick-&-dirty test.

**Comment by ameshkov** [comment]
It occurs to me that the issue is more about routing. For instance, ad servers might be located in the cellular provider's LAN (which AG excludes by default to not mess with it). Note that the issue affects Korean users, so it has something to do with their cellular providers features.

**Comment by TPS** [comment]
> For instance, ad servers might be located in the cellular provider's LAN (which AG excludes by default to not mess with it).

[Netflix does it](https://openconnect.netflix.com/en/delivery-options/); why shouldn't Google?  Or ISPs using caching proxies to serve them to decrease _their_ external bandwidth.  The possibilities are virtually endless.…

**Comment by ameshkov** [comment]
@TPS in the Netflix case traffic might be routed through ISP indeed, but it does not really become part of the private subnet, which I suspect is the case in #1026

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
