### ISSUE TITLE
Random fullscreen ads, unknown source

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1721]
### Steps to reproduce
The customer reports that the ads are appearing randomly, without any connection to opened sites/apps whatsoever.

### Expected behavior
normal behavior

### Actual behavior
fullscreen ads randomly appearing

<details><summary>Screenshot:</summary>

![screenshot_20180131-140204](https://user-images.githubusercontent.com/33634917/36062809-4dc8377a-0e7c-11e8-8fc4-4a2ea1d04b90.png)

</details>

### Logs
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1713456/debug.txt)
~7:45

### Customer ID 
1734759

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Filtering quality: High quality
* SSL filtering: Enabled, Whitelist mode
* Filters: "English filter", "Spyware filter", "Social media filter", "French filter", "Spanish/Portuguese filter", "Mobile Ads filter"
* Device model: Motorola Moto G3
* Operating system and version: Android 6.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by ameshkov** [comment]
Looks like an adware.

It's unclear what app causes it from the log, though. I'd suggest trying removing the apps one by one to figure which one is responsible.

Also, we'll need a log for a longer period with the "record http requests" level.
