### ISSUE TITLE
A questionable string on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1722]
@aalpatkina 

"The application does not trust user certificates. Enabling HTTPS filtering can break down its"
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/ZMtOP5H.png)
</details><br/>

"its" or "it"??
Or is that an incomplete string?

And another question.
**If the app does not trust user certificates, I remember that AdGuard can do nothing for it.**
Those ads won't be blocked if using Android v7 & v8. (No root)
How does HTTPS filtering break down it?
Feel questionable for that content.

**Comment by nkartyshov** [comment]
@lancelot-moon This string updated, new string: "This app does not trust user certificates so HTTPS filtering can break its secure connections."

> If the app does not trust user certificates, I remember that AdGuard can do nothing for it.
> Those ads won't be blocked if using Android v7 & v8. (No root)
> How does HTTPS filtering break down it?

Yes, Adgard will not filter traffic for such applications, but you can enable it in application settings.

**Comment by lancelot-moon** [comment]
Do you mean that AdGuard will automatically detect such apps and disable HTTPS filtering for them by default?
We need to manually enable the protection in apps management of AdGuard, right?

Is it a good thing if HTTPS filtering breaks its secure connections?
Will it cause any trouble if secure connections was broken?

Thanks for the answer.

**Comment by Revertron** [comment]
The string must look like this:
```
This app does not trust user certificates so HTTPS filtering can break its secure connections.
```

**Comment by lancelot-moon** [comment]
May you answer my 4 questions?
It will help me to understand.
Thanks.

**Comment by Revertron** [comment]
1. The app may refuse to connect to it's server.
2. AdGuard will try it's best to know which apps do support HTTPS filtering and which do not. Sometimes, user can change this setting in apps management.
3. The question is not clear for me. May be the first answer will cast some light on this?
4. Yes, AdGuard can not filter it, and it may prevent an SSH client from connecting. But we do not filter SSH ports by default.

**Comment by lancelot-moon** [comment]
Hi, thanks for the reply!

About your answer for my 1st point, it's like a problem of compatibility between certificate and HTTPS filtering.

In most situation, the log of AdGuard can only show the domain (unable to show the full path) if the app doesn't trust AdGuard certificate.
The connection is still normal.

Well, it maybe causes the trouble of connection for some apps.
You talked about some special cases which have the issue of compatibility, right?

**Comment by lancelot-moon** [comment]
Sir,
It's a little strange if using "break" there.
Originally, you used "break down", not "break".

This is my thought for the string.
"This app does not trust user certificates so HTTPS filtering is unable to break down its HTTPS requests even maybe causes the trouble of connection due to the issue of compatibility in some apps."

**Comment by Revertron** [comment]
Yes, you may be right about "break down" :)

**Comment by lancelot-moon** [comment]
May you again update the string?
I'll again translate it to my mother tongue on oneskyapp soon.

Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 
@aalpatkina 

You changed to use "This app does not trust user certificates so HTTPS filtering can break down its secure connections."

It's strange!
As what we know, AdGuard can filter HTTPS in most Internet browsers. 
Regular apps built for Nougat+ (not trust user certificates) cannot be filtered due to Android restrictions.

How can AdGuard "break down" it?
aalpatkina, you don't understand what I wrote to you on VK... 

@Revertron 
This app does not trust user certificates so HTTPS filtering can break its secure connections.

I think that he was talking about the compatibility of SSL?
So he used "break" here.

But my string gives better explanation:
"This app does not trust user certificates so HTTPS filtering is **unable** to break down its HTTPS requests even maybe causes the trouble of connection due to the issue of compatibility for some apps."

**Comment by aalpatkina** [comment]
@lancelot-moon if you open 'Android App' project, you'll see that this phrase has been already changed.

**Comment by lancelot-moon** [comment]
@aalpatkina 

I'm in 'Android App' project of oneskyapp now.
This is what I see now.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/ADxfgwG.png)
</details><br/>

You changed to use "This app does not trust user certificates so HTTPS filtering can break down its secure connections."

That string is wrong.

**Comment by lancelot-moon** [comment]
May you discuss with AdGuard team, how about my string?
**"This app does not trust user certificates so HTTPS filtering is unable to break down its HTTPS requests even maybe causes the trouble of connection due to the incompatibility for some apps."**

**Comment by lancelot-moon** [comment]
break = повреждение
break down = декомпозиция

**Comment by ameshkov** [comment]
Hm, do we still have that string in oneskyapp? It was changed in the code long ago

**Comment by lancelot-moon** [comment]
Yes, you have a wrong string on oneskyapp now.

**Comment by lancelot-moon** [comment]
What's your meaning for that string?
What can HTTPS filtering do if this app does not trust user certificates?
Decompose (analyze) its secure connections or collapse its secure connections?

Maybe "break down" easy lets people misunderstand.
break down = декомпозиция или коллапс

We can use another distinct English words instead of "break down".

Thanks.

**Comment by vozersky** [comment]
@aalpatkina pls assist

**Comment by aalpatkina** [comment]
At the moment we have this English phrase approved in OneSky and we consider it to be correct and understandable. 
"This app does not trust user certificates, so HTTPS filtering can break its secure connections."

If there are other suggestions on what word to use instead of "break" here (or any other suggestions), we will be glad to see the variants with links to examples. 

The suggestion made by @lancelot-moon is rather good but the sentence is too long. Moreover, it is the most important for users to know that secure connections can be broken and other details are not so important here (given that we speak about the "Warning" message).

**Comment by lancelot-moon** [comment]
Today, you just modified it on oneskyapp.
This app does not trust user certificates, so HTTPS filtering can **break down** its secure connections.
-> This app does not trust user certificates, so HTTPS filtering can **break** its secure connections.

Yes, only using "break" is better.
"break down" has several different meanings, it can mean "analyze" or "collapse".
The original string would let users misunderstand that "this app does not trust user certificates, so HTTPS filtering can **analyze** its secure connections".
But actually it means "break" here.

Thanks.

**Comment by bobsage123** [comment]
So when you enable HTTPs filtering for an app when getting this "break" message, does that mean that the HTTPS connection can now be "snooped" on because the secure connection is broken? Trying to understand from reading this thread.

**Comment by ameshkov** [comment]
No, it means that the connection will fail to establish.
