### ISSUE TITLE
Add per-app filtering log records

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1723]
As reported by user #1757870,

"A feature I think everyone would appreciate is the about to
see what Apps are making requests. As I look through the filtering
log, I find myself wondering why my device is connecting to certain
websites / servers. For instance, recently some App or system process
started connecting to Baidu servers. I cannot think of any App I am
using which would need to connect there."

**Comment by ameshkov** [comment]
Hm, filtering log already shows what app connects where.

Could you please specify what exactly the user wants us to add?

**Comment by akmLaVx** [comment]
The user wants to be able to know to which app(s) does the DNS request(s) pertains to.

**Comment by Revertron** [comment]
@akmLaVx This can not be done, because all DNS requests go from system :(
