### ISSUE TITLE
Loss of functionality on Android Oreo

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1724]
### Steps to reproduce
1. Upgrade to Android 8.1
2. Enjoy tons of ads, even with AdGuard enabled!

### Expected behavior
App should continue working

### Actual behavior
AdGuard stops blocking ads

### Customer ID 
1507785

### Debug logs
[dbg-oreo.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1717144/dbg-oreo.zip)

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: 1st gen Google Pixel XL
* Operating system and version: Android 8.1
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found
* Filtering mode: High-quality
* HTTPS filtering: enabled, whitelist mode

**Comment by ameshkov** [comment]
What about reinstall?

**Comment by akmLaVx** [comment]
Offered a reinstall, waiting for reply.
