### ISSUE TITLE
Something makes AdGuard to completely lose any kind of connection to the Internet

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1725]
### Steps to reproduce
1. Launch AdGuard and attempt to do ANY action that requires a connection: activate, update filters, send logs to support, etc.
2. Nothing will work.

### Expected behavior
Should work

### Actual behavior
Doesn't work

### Environment
Unknown carrier-preinstalled (Sprint) antivirus. The app is not user configurable and as far as I've understood from phone calls, there is no way to whitelist an app from being filtered by antivirus.

### Customer ID 
1747805

### Debug logs
[adguard_logs_2.10.176_0802_1852.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1717400/adguard_logs_2.10.176_0802_1852.zip)
[adguard_logs_2.10.176_0802_1856.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1717401/adguard_logs_2.10.176_0802_1856.zip)

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy S6 edge 32GB Sprint mod (SM-G925P)
* Operating system and version: Android 7.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by TheOmen6six6** [comment]
Hope this helps....the reason I am this issue was found is when attempting to activate my premium plan I keep getting the notification saying I'm unable to do so. Lookout is the bloatware I cannot remove. I do have it disabled. Please let me know if I can be of further help.

**Comment by ameshkov** [comment]
Something is not okay with the device security settings:
`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

@TheOmen6six6 first of all, could you please try clearing the security credentials of the device? Settings -> Security -> Credentials -> Clear credentials.

This will disable HTTPS filtering in AdGuard, but maybe it'll help.

**Comment by TheOmen6six6** [comment]
We got it! Thank you so much! I'm all up and running.

I was unable to clear it as you requested. Instead, I went into my security
certificates and found two of them shut off. I toggled them on and it took
my license number the first try.

Thank you for helping me figure this out!
                     Damian

**Comment by ameshkov** [comment]
Awesome, thank you!

**Comment by TheOmen6six6** [comment]
You're welcome. I appreciate your service and the product itself!

                     Take care,
                                 Damian
