### ISSUE TITLE
Allow filtering log to display blocked requests only

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1726]
As reported by user #1760194,

> Filter log needs option to just show blocked items. How can I know
> details of how good a job the app does otherwise?

**Comment by lancelot-moon** [comment]
Duplication.

https://github.com/AdguardTeam/AdguardForAndroid/issues/1535

**Comment by zebrum** [comment]
oh, thank you!
closed as dup
