### ISSUE TITLE
AdGuard won't start on boot on some Oreo devices

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1727]
AdGuard will not start or automatically activate when booting up.

### Steps to reproduce

1. Install on MD Global TA-1025 aka Nokia 6
2. Install AdGuard 2.10.176
3. Configure it to start with a system, reboot
4. It won't start

### Expected behavior

It starts with a system like on all other devices

### Actual behavior

I won't start, you have to do it manually every time

### Customer ID 

1050908 with logs
1058743

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN / Proxy(manual/auto) both
* Device model: (e.g. Google Pixel) Nokia 6, 
* Operating system and version 8.0.0.
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by ameshkov** [comment]
Does it help to whitelist AdGuard in the Battery settings of the device?

Nokia is known to be problematic when it comes to background apps.

**Comment by evgeniy-ADG** [comment]
Yes, this is the first thing that we ask to check. Here's the customer's reply:

> I already have these settings. What is happening is that when I reboot the phone Adguard is disconnected when the phone starts back up. I have to manually start it. I have changed no settings which are the same when I had Android 7.12. After updating Android to 8.0 is when Adguard will not automatically start when booting the phone. It is related to Android  Oreo 8.0.

**Comment by vozersky** [comment]
We've only got nokia 3 with android 7, but it works fine on the device, just tried

**Comment by ameshkov** [comment]
Actually, I can see that AdGuard has been started on device boot:
```
23:53:40.600 [main] INFO  c.a.a.receivers.BootUpReceiver - Receiver got an action android.intent.action.BOOT_COMPLETED
23:53:40.624 [main] INFO  c.a.a.receivers.BootUpReceiver - Auto starting protection on boot.
23:53:40.630 [main] INFO  c.a.a.receivers.BootUpReceiver - Service has been started.
```

**Comment by ameshkov** [comment]
It was killed shortly after that, and I suppose this is just how Nokia works. It should be reported to Nokia devs.

**Comment by planet0** [comment]
Just wanting to add that I have a Nokia 6 and whilst I was beta testing Orea 8 last month, AdGuard never launched on boot. Currently I'm back on Android 7 stable and AdGuard is launching on boot without needing to alter any external settings since the app install.

Am waiting to receive the Oreo 8 stable update OTA from Nokia, if I do receive it I'll update on how it goes with AdGuard.

**Comment by ameshkov** [comment]
The only possible semi-solution I see is to try changing `pref.boot.startup.delay` flag back to 10 seconds.

@evgeniy-ADG could you please ask user to do it?

**Comment by ameshkov** [comment]
It seems that it helps in the Huawei case:
https://forum.adguard.com/index.php?threads/on-the-behavior-of-huawei-terminal.27837/page-2#post-165155

I guess we should return the 10 sec value for `pref.boot.startup.delay` on Oreo.

**Comment by planet0** [comment]
Funnily enough I received the OTA update for Oreo overnight. Uninstalled AdGuard before the update and reinstalled from scratch after the update.

Restarted the Nokia 6 device twice, AdGuard did not startup automatically both times. Noticed pref.boot.startup.delay was on 0.

I set the value to 10, and now AdGuard starts up successfully upon boot up.

**Comment by planet0** [comment]
Spoke too soon, AdGuard didn't launch this time on boot. 😢 Needed to manually open the app and enable protection.

**Comment by planet0** [comment]
AdGuard Nightly 2.11.32 with low level settings reset to default (with delay back to 0) has been starting up every single time on boot so far with no failure yet, although it does take quite a while for it to kick in and to see the VPN icon appear.

**Comment by ameshkov** [comment]
> it does take quite a while for it to kick in and to see the VPN icon appear.

That's expected, Android takes quite some time before notifying apps about boot event.

**Comment by planet0** [comment]
> That's expected, Android takes quite some time before notifying apps about boot event.
Thought so, wanted to document it for you just in case. But so far, so good!

**Comment by planet0** [comment]
> That's expected, Android takes quite some time before notifying apps about boot event.

Thought so, wanted to document it for you just in case. But so far, so good!

**Comment by ameshkov** [comment]
@Revertron plz remind me the pull request for that.

**Comment by Revertron** [comment]
Mmm, for what exactly?

**Comment by ameshkov** [comment]
This: https://github.com/AdguardTeam/AdguardForAndroid/issues/1727#issuecomment-368580887

**Comment by ameshkov** [comment]
I just see that this issue in the review/QA pipeline, but I don't remember a PR about that (and PR is important for the automated changelog)

**Comment by sviperz** [comment]
Can confirm, that AG **does** start after reboot as expected on my device.

AG version: 2.11.31 Beta
AG filtering mode: VPN
Device: Google Pixel 2016
OS: Android 8.1.0
No root

**Comment by altokarev** [comment]
It restarts with no issues. Just checked.

AG version: 2.11.81
AG filtering mode: VPN
Device: Google Pixel
OS: Android P DP1
No root

**Comment by Thetromboneman1** [comment]
Doesn't restart for me 

AG version: 2.11.81
AG filtering mode: VPN
Device: S8+
OS: Android 8 
No root, Task killer, Battery optimization or Antivirus.
