### ISSUE TITLE
Lack of android.permission.INTERACT_ACROSS_USERS does not allow to use Adguard when multiple users configured on the device

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#173]
```
java.lang.SecurityException: get package uid: Neither user 10004 nor current process has android.permission.INTERACT_ACROSS_USERS.
    at android.os.Parcel.readException(Parcel.java:1599) ~[na:0.0]
    at android.os.Parcel.readException(Parcel.java:1552) ~[na:0.0]
    at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1704) ~[na:0.0]
    at android.net.VpnService$Builder.establish(VpnService.java:769) ~[na:0.0]
    at com.adguard.android.vpn.AdguardVpnService.buildVpnService(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.setupVpn(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService.access$000(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

Initial user complaint:
http://4pda.ru/forum/index.php?showtopic=601691&st=3680#entry44370208
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=44386477

**Comment by Revertron** [comment]
android.permission.INTERACT_ACROSS_USERS_FULL is a signature level permission. Your app will not be able to use it until and unless it has the same signature as the system.

We can do nothing about this exception and permission :(

**Comment by ameshkov** [comment]
The question is why it works in Tunnelbear case? Could it be somehow caused by the fact, that tunnelbear is installed from google play?

**Comment by Revertron** [comment]
With root we could trick "installer" attribute in PackageManager's config (I can't remember now what the file is...) But I have only 5.1.1 OS version.

**Comment by ameshkov** [comment]
Nah, root is not an option..

**Comment by ameshkov** [comment]
@gshumihin please examine the TunnelBear app AndroidManifest file and look at permissions there.

**Comment by TPS** [comment]
@ameshkov @Revertron @gshumihin Just reading through this, there seems to be a difference between `android.permission.INTERACT_ACROSS_USERS` & `android.permission.INTERACT_ACROSS_USERS_FULL` though you guys seem to be using them interchangeably.…  Does 1 require root & the other not?

**Comment by gshumihin** [comment]
Here's TunnelBear permissions:

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.tunnelbear.android" platformBuildVersionCode="21" platformBuildVersionName="5.0.1-1624448">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BROADCAST_STICKY"/>
    <uses-permission android:name="com.android.vending.BILLING"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by ameshkov** [comment]
@TPS anyway I've tried adding that one and it didn't help.

**Comment by ameshkov** [comment]
Just got another complaint, the very same error:
Customer ID: 1146180
http://forum.xda-developers.com/showpost.php?p=69895217&postcount=1920

**Comment by evgeniy-ADG** [comment]
The same report: 1447515

**Comment by zebrum** [comment]
just in case id 1506880

**Comment by altokarev** [comment]
One more. Customer ID: 1571123.

**Comment by vozersky** [comment]
another [report](https://forum.adguard.com/index.php?threads/adguard-%D0%BD%D0%B5-%D0%BC%D0%BE%D0%B6%D0%B5%D1%82-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-vpn-%D0%BD%D0%B0-%D1%81%D0%B2%D0%B5%D0%B6%D0%B5%D0%B9-%D0%B1%D0%B5%D1%82%D0%B5-miui9.26101/#post-156426)

**Comment by Bohdan-SUP** [comment]
Another one in ticket 1514242

**Comment by nkartyshov** [comment]
Bug report in xiaomi: http://en.miui.com/thread-977018-1-1.html

**Comment by ameshkov** [comment]
> Bug report in xiaomi: http://en.miui.com/thread-977018-1-1.html

MIUI bug is reported as fixed on the second page.

**Comment by ameshkov** [comment]
I'd better close this as we anyway cannot do anything with that.
