### ISSUE TITLE
Add information about non-filtered connections to the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1730]
At the moment we're completely ignoring some connections:

* Connections that are blocked by the firewall rules;
* Connections that are not bypassed on the VPN level for some reason;

We should record them as a "Tunnel" event type.

**Comment by TPS** [comment]
Can they also be highlighted w/ _another_ color(s) in the filtering log, & added to the issue about filtering events w/in the filtering log (which I can't currently find)?

**Comment by ameshkov** [comment]
@admitrevskiy one more thing is missing from the implementation.

We need to be able to construct blocking (and unblocking) rules for this kind of connections. It is possible to block or unblock a network connection with the rules that use the `$network` modifier.

**Comment by Alex-302** [comment]
IP is displayed instead of host name
![image](https://user-images.githubusercontent.com/8361299/39990685-e2599630-5775-11e8-9342-b65092794f5c.png)

**Comment by ameshkov** [comment]
> IP is displayed instead of host name(it seems in VPN mode)

Yes, that's expected -- no filtering, no parsing connection details.

**Comment by zebrum** [comment]
seems to be not working.

**Comment by ameshkov** [comment]
@zebrum steps to reproduce:

1. Disable ad blocking for Chrome
2. Open some web page
3. Check the filtering log

**Comment by zebrum** [comment]
@ameshkov yep, that's exactly what I've done.

**Comment by vozersky** [comment]
Connections that are not bypassed on the VPN are shown in the log, but connections that are blocked by the firewall rules are not

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/573`
