### ISSUE TITLE
No switch for disabling filtering log and the unsolved compatibility issue with BBS Telnet protocol in AdGuard v2.11.23η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1732]
1. No switch for disabling filtering log.
Why?
May you give the switch back?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9EQ1PyZ.png)
</details><br/>

2. It's still difficult even unable to login into PTT BBS with the default port 443 in mobile PTT apps whose connection is BBS Telnet protocol if enabling AdGuard Protection.
Even disabling HTTPS filtering is useless for the issue of BBS Telnet connection.
Maybe you still didn't start to solve it.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1601

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Ph56BUV.png)
</details><br/>

3. AdGuard v2.11.23η doesn't use the latest Traditional Chinese translations.
Some strings are still English strings which early have translations, or outmoded Traditional Chinese translations.
And then some strings of AdGuard Nightly builds are not on oneskyapp.

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/0NszVRM.png)

![image](https://i.imgur.com/URtx3Yf.png)

![image](https://i.imgur.com/l1wi1RD.png)

![image](https://i.imgur.com/qyd9moX.png)

![image](https://i.imgur.com/ZLNFLbE.png)

![image](https://i.imgur.com/TIacbDE.png)

![image](https://i.imgur.com/I8bC3Ps.png)
</details><br/>

Thanks.

**Comment by ameshkov** [comment]
> May you give the switch back?

No, the log is always enabled now. It does not create any overhead so the switch is simply redundant.

> BBS

We have an open issue for that already.

**Comment by ameshkov** [comment]
> AdGuard v2.11.23η doesn't use the latest Traditional Chinese translations.

That'll be resolved in due course (when we release a beta version). Nightly builds aren't automatically synced with oneskyapp.
