### ISSUE TITLE
A comparison between AdGuard and MinMinGuard.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1733]
MinMinGuard is made by a Taiwanese.
https://fatminmin.com/pages/minminguard.html

MinMinGuard GitHub:
https://github.com/chiehmin/MinMinGuard

XDA discussion thread:
https://forum.xda-developers.com/xposed/modules/xposed-minminguard-v1-7-0-cancelled-t2597332/post49112940#post49112940

How does it work?
API based blocking: Block function calls provided by the advertisement network sdk. Then recursively remove the ad space.

Name based blocking: Remove the adview in layout directly.

URL based blocking: Block webviews that contains prohibited urls.

I don't know if @ameshkov knows this adblocker.
It needs root access and Xposed.

How can it do Name/URL based blocking if there is no the installation of certificate for HTTPS filtering?
Can AdGuard do API based blocking?

Except for the 2 questions, only a simple introduction.)

Thanks.

**Comment by ameshkov** [comment]
They use Xposed framework to override some Android APIs and do the blocking.

This is a nice approach and it works well but only if you have Xposed and that makes it rly limited.
