### ISSUE TITLE
Automatically jump a pop-up to notify users about the thing along with clearing Filtering Log when the log file achieves certain big size.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1734]
It seems that you decide to remove the switch for Filtering Log forever, right?
https://github.com/AdguardTeam/AdguardForAndroid/issues/1732#issuecomment-368541281

I believe that there are users who never or rarely use Filtering Log.
However, Filtering Log is enabled by default, which maybe lets Filtering Log accumulate a lot of data if users don't notice it.
So please automatically jump a pop-up to notify users about the thing along with clearing Filtering Log when the log file achieves certain big size.

Thanks.

**Comment by vozersky** [comment]
this log only keeps the record of the last 500 requests
