### ISSUE TITLE
[Nightly, Feature request] Provide clickable links to GitHub changelog page

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1735]
As reported by user 1613931,

"Updated to Nightly 2.11.28 from 2.11.23. With regard to the change
log, is it possible to provide a direct click link to github.com?
Currently the users are unable to copy the link in order to view in
browser. Thank you!"

**Comment by ameshkov** [comment]
Guys, we'll make changelog better soon, don't worry.

**Comment by TPS** [comment]
#1487, I think.  Why not closed?
