### ISSUE TITLE
A questionable string (tap to) on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1736]
@aalpatkina 

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/E0BV3o5.png)
</details><br/>

Do you want to use "tap into" or only "tap" here?

https://goo.gl/VdQgkX
tap into sth:
to use part of a large supply of something for your own advantage
подключаться к чему-либо

Thanks.

**Comment by aalpatkina** [comment]
@lancelot-moon 
I think you are right. "Tap into" is more appropriate to use here.
I'll change this phrase. Thank you.

**Comment by aalpatkina** [comment]
@lancelot-moon 
I think that "tap AdGuard" is meant here :)
Thank you.
