### ISSUE TITLE
Pause/Assistant buttons look ugly on Xiaomi

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1739]
Check the screenshot here:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=70846965

**Comment by planet0** [comment]
On Alcatel TCL devices using Android 6, the Assistant button is a solid gray square, no icon present.

**Comment by Revertron** [comment]
@planet0 Do you talk about current nightly (2.11.32)?
We've made some changes to this notification. You can try it if you haven't already.

**Comment by planet0** [comment]
@Revertron, didn't realise it was already updated, now it just shows 'Pause' and 'Assistant' without icons. 👍

**Comment by Revertron** [comment]
I think you are happy with the changes. We can close this issue :)
