### ISSUE TITLE
Wrong date in the notification 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1742]
It shows the wrong date

### Expected behavior

The date in the notification and in the system matches

### Actual behavior

<details><summary>Screenshot:</summary>

![screenshot_20180228-201901](https://user-images.githubusercontent.com/15856304/36842891-db8a2298-1d55-11e8-81df-0d146bd049f7.jpg)

</details>

### Your environment

* Adguard version: 2.10.176, log and state.txt: https://uploads.adguard.com/7qall.zip
* Adguard filtering mode: VPN 
* Device model: HUAWEI FRD-L02
* Operating system and version 7.0.0
* Rooted or not?  n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? AVG

**Comment by ameshkov** [comment]
The date/time on the notification is shown by Android, we do not control it
