### ISSUE TITLE
Whitelisting a website

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1743]
@evgeniy-ADG commented on [Sat Feb 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713)

> Есть рабочий ресурс такого вида rm.sabpek.com:8080/redmine/. AdGuard перенаправляет запросы и получается sabpek.com/redmine, что уже делает его неработоспособным. Сайт в белом списке, но это не помогает. Как-то можно убрать перенаправление?

@Alex-302 как такое правильно исключить? 

---

@Alex-302 commented on [Wed Feb 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-367119967)

У меня не перенаправляет. Какой Адгард? Пусть попробует антитрекинг покрутить в сторону ослабления.

---

@evgeniy-ADG commented on [Wed Feb 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-367274836)

@Alex-302 это андроид, ID 1761482

---

@Alex-302 commented on [Wed Feb 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-367445582)

Вот ведро
![image](https://user-images.githubusercontent.com/8361299/36501363-988b6cec-174f-11e8-9fe4-136ef0dc5baa.png)
у себя потести, может от браузера/прошивки зависит

---

@evgeniy-ADG commented on [Tue Feb 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-368688009)

@Alex-302 была похожая штука, там виноват был DNS. Можно как-то в Android версии вайтлистить домены от DNS?

---

@geminixandroid commented on [Tue Feb 27 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-368733661)

Xiaomi redmi note 3 pro, android 6, хром 64.0.3282.137.
Если пробовали в хроме смотреть, то нужно сжатие отключить, иначе форма с логином отобразится, но при входе всё равно перенаправится не правильно. Всё аналогично и в фаерфоксе.
В Адгард ресурс в белом списке, отключена DNS фильтрация.

---

@Alex-302 commented on [Wed Feb 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-369030955)

@geminixandroid какой режим - прокси или VPN? Попробуйте переключить.

---

@geminixandroid commented on [Wed Feb 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-369087514)

@Alex-302, Был VPN, попробовал через публичный прокси - аналогично

---

@Alex-302 commented on [Wed Feb 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-369176748)

@geminixandroid не, имею в виду режим Адгарда. В расширенных настройках можно выбирать в каком режиме он будет работать - локальный VPN или локальный прокси.

---

@geminixandroid commented on [Thu Mar 01 2018](https://github.com/AdguardTeam/AdguardFilters/issues/11713#issuecomment-369512799)

@Alex-302, в расширенных настройках поставил локальный http прокси - дал root, аналогично

**Comment by ameshkov** [comment]
@geminixandroid а можете записать полный лог работы AG?

https://kb.adguard.com/en/android/solving-problems/log

**Comment by geminixandroid** [comment]
@ameshkov, [https://drive.google.com/open?id=1QfpHFCRo2Gq4yTC2wyK5rni4FOkaby7T](Log)

**Comment by ameshkov** [comment]
Хм, а точно оно без AG правильно работает?

По логу все вот так выглядит:

1. Идет запрос на `GET "http://rm.sabpek.com:8080/redmine/"`
2. В ответе приходит редирект на `http://rm.sabpek.com/redmine/login?back_url=http%3A%2F%2Frm.sabpek.com%2Fredmine%2F` (уже без порта)

Запрос:
```
15:42:07.388 [pool-2-thread-1036] DEBUG com.adguard.filter.proxy.a - TCP id=1002465 GET /redmine/ HTTP/1.1
Host: rm.sabpek.com:8080
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Redmi Note 3 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
DNT: 1
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: _ga=GA1.2.341819585.1514361490; _ym_uid=1514361490462915176
```

Ответ:
```
15:42:07.445 [pool-2-thread-1036] DEBUG com.adguard.filter.proxy.a - TCP id=1002465 HTTP/1.1 302 Found
Date: Mon, 05 Mar 2018 08:42:01 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache
X-Request-Id: df41f75d-ec60-4a6f-9795-d21d32b1a562
X-Runtime: 0.004604
X-Powered-By: Phusion Passenger 4.0.37
Location: http://rm.sabpek.com/redmine/login?back_url=http%3A%2F%2Frm.sabpek.com%2Fredmine%2F
Status: 302 Found
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
```

**Comment by geminixandroid** [comment]
@ameshkov , вот видео с телефона с включенным и выключенным адгардом.
[Видео](https://drive.google.com/file/d/18HI1WhQHOjRAxVXrIQOY6e_BWMCby8fy/view?usp=drivesdk)

**Comment by ameshkov** [comment]
@geminixandroid а можете последнюю найтли попробовать?

https://agrd.io/android_nightly

Там движок фильтрации полностью новый, возможно все уже ок

**Comment by zebrum** [comment]
reopen if needed
