### ISSUE TITLE
Nightly: Off/On switch missing in filtering log

### ISSUE THREAD

**Issue by FlyPigsFly** [AdguardTeam/AdguardForAndroid#1745]
Filtering log doesn't contain switch to turn off or on filtering log activity.

Using version 2.11.28

**Comment by Revertron** [comment]
We've seen that there is no overhead in working with filtering log always on, therefore we've decided that it will be on always.

**Comment by FlyPigsFly** [comment]
Would it be possible to still have the option to turn off logging in nightly builds? I like living on the edge ;)

**Comment by Revertron** [comment]
Filtering log is not written anywhere. It is kept only in memory.

**Comment by FlyPigsFly** [comment]
I'm confused.

Is the Nightly AdGuard filtering log different from the Stable AdGuard filter log?

When enabling the filtering log in a Stable builds, the user is presented with a message about increased RAM and CPU usage. The message is non existent is the nighty builds.

I'm not sure I fully understand the option to turn off or on filtering log.

**Comment by Revertron** [comment]
They are the same.
When we first introduced filtering log, we assumed that it will drain some resources. But our later research suggests that it it not draining resources.
Just don't be frightened :)

**Comment by ameshkov** [comment]
Key points:

1. Filtering log is not stored anywhere, it's in memory
2. It shows only the last 500 items (to avoid overusing memory)
3. Our tests show that there's no overhead
