### ISSUE TITLE
In manual proxy mode it takes too long to stop a local server

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1746]
I rarely used local proxy mode because my phone is rootless.
I'm not sure if it's normal.
1. I used local proxy mode for my Wi-Fi in AdGuard v2.11.32η yesterday.
I had done the manual configuration for Wi-Fi.
When trying to enable AdGuard Protection, it often showed the error and was failed to enable AdGuard Protection.
I need to try again for several times until successfully enable it.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MP3np1i.png)
</details><br/>

2. I tried local proxy mode to do filtering.
The quality of ad blocking is low.
With local VPN mode, some ads in apps are blocked.
But those ads appeared when I used local proxy mode.

**Comment by ameshkov** [comment]
Could you please reproduce the issue and export the log?

**Comment by lancelot-moon** [comment]
1. I have sent the bug report.
   **User ID**: 1425202
   **Subject**: [PREMIUM] [Adguard for Android] 程式錯誤報告

2. Bad ad blocking quality.
a. Ads are blocked, but the frames of ads are left and not hidden.
announcement of petroleum price:
https://play.google.com/store/apps/details?id=tw.goodlife.a_gas
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/w9mu5R6.png)
</details><br/>

Libertytimes newspaper app:
https://play.google.com/store/apps/details?id=com.ltnnews.news
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/x31nBfh.png)

![image](https://i.imgur.com/SsY5alg.png)

![image](https://i.imgur.com/n9oGve1.png)
</details><br/>

b. Local proxy mode is unable to filter some HTTPS requests even if only domains, not URL.
AppSales app:
https://play.google.com/store/apps/details?id=net.tsapps.appsales
Recently, it changed its ad domain.
It started to use ads from graph.facebook.com
I added ||graph.facebook.com^ in the user filter.
Under local VPN mode, the ads can be blocked.
Under local proxy mode, the ads can not be blocked.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/zdZ4lhY.png)
</details><br/>

Mo PTT:
https://play.google.com/store/apps/details?id=mong.moptt

Under local VPN mode, I almost don't see ads.
If enabling DNS filtering together, no ad!
(I don't know why DNS filtering is valid for ads in Mo PTT since Mo PTT should not trust AdGuard certificate.
AdGuard Pro for iOS also can do quality ad blocking for ads in Mo PTT.)
https://github.com/AdguardTeam/AdguardFilters/issues/9972

Under local proxy mode, the ads can not be blocked.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/a9n6nki.png)
</details><br/>

"moptt.azurewebsites.net/api/pttboard/update" will call ads.
I added ||moptt.azurewebsites.net^ in the user filter.

The section of 熱門文章 (Hot articles) is under the domain, moptt.azurewebsites.net.
If I block it, I should not visit the section of 熱門文章 (Hot articles).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/DRBvmWv.png)
</details><br/>

Under local VPN mode, I am unable to visit it in my expectation since I block moptt.azurewebsites.net.
Mo PTT showed the error messages.
"Oh! The server has no response, please try again later."
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7dk2KxG.png)
</details><br/>

Under local proxy mode, it's strange that I could still visit the section of 熱門文章 (Hot articles) even if I had blocked its domain.
And then sponsored ads were not blocked in the section of 熱門文章 (Hot articles).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/UpTM5lP.png)
</details><br/>

@ameshkov
I lent a PTT BBS ID & Password to Revertron.
Please get the account from him.
You can login into PTT BBS and then try Mo PTT by yourself.
Under local proxy mode, all ads aren't blocked in Mo PTT app.

**Comment by Revertron** [comment]
It's not a great discovery that proxy mode doesn't block all the ads. If you mean manual, not root mode.

**Comment by lancelot-moon** [comment]
We don't talk about the filtering for cellular network.
With no root access, local proxy mode should still do good filtering for Wi-Fi.
But its performance is worse than local VPN mode.

I don't need root access or move AdGuard certificate to system store.
Under local VPN mode:
No frames of ads left.
Powerful ad blocking.

Only compare in the same level.
Well, simply report it.

@Revertron 
I think that you have met the trouble of BBS Telnet connection via port 443 with AdGuard local VPN. XD

**Comment by Revertron** [comment]
You don't understand. The manual proxy mode **can not** intercept all the requests and connections, as in is for the VPN and root-proxy modes.
The manual proxy is used by apps only if **they want** to use it. If you are developing some application, that would work with internet, and you want to use a proxy that is set up for current Wi-Fi network, you need to implement it additionally to simple ways.

Therefore, some apps will not use proxy at all. And AdGuard can not force them to use it.

**Comment by lancelot-moon** [comment]
Ok, those apps may not use proxy.
Not all of their network traffic is routed through AdGuard local proxy.
Thanks for the answer.

**Comment by akmLaVx** [comment]
Logs have arrived for that case and are available under customer id 1425202.

**Comment by ameshkov** [comment]
```
ERROR com.adguard.android.g.a - Error starting proxy server
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:0.0]
	at sun.nio.ch.Net.bind(Net.java:442) ~[na:0.0]
	at sun.nio.ch.Net.bind(Net.java:434) ~[na:0.0]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:224) ~[na:0.0]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:0.0]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67) ~[na:0.0]
	at com.adguard.filter.proxy.o.g(Unknown Source:54) ~[na:0.0]
	at com.adguard.android.g.a.a(Unknown Source:59) ~[na:0.0]
	at com.adguard.android.g.a$1.run(Unknown Source:2) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by ameshkov** [comment]
@Revertron the problem is that we're stopping the proxy server asynchronously (in order to improve the VPN restart time).

It does not work well in manual proxy mode:

```
22:02:05.330 [pool-2-thread-13] INFO  com.adguard.filter.proxy.a - Closing proxy server
```
```
22:04:10.992 [pool-2-thread-13] INFO  com.adguard.filter.proxy.a - Proxy server has been closed
```

**Comment by ameshkov** [comment]
In order to improve this, we should close the listening socket right away, and close active connections afterward.

Swap these two lines in `BaseHttpProxyServer` and see how it works:
```
        IOUtils.closeQuietly(proxyServerState);
        super.close();
```
