### ISSUE TITLE
Autopause does not work when there's no internet connection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1749]
### Steps to reproduce

1. Uncheck `pref.vpn.disable.pause`
2. Switch to the airplane mode

### Expected behavior
AG protection automatically pauses itself

### Actual behavior
Nothing happens
### Your environment

* Adguard version: 2.11.31
* Adguard filtering mode: VPN
* Device model: Any

**Comment by Revertron** [comment]
Fixed, merged.

**Comment by TPS** [comment]
@ameshkov, @Revertron: Should be closed now?

**Comment by ameshkov** [comment]
@TPS it's on the internal Review/QA pipeline, will be closed once confirmed
