### ISSUE TITLE
[Suggestion] Rename "Ad Blocker" in Settings to something more descriptive/accurate

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1751]
I've been an AdGuard user for a while now, and I *still* forget that Ad Blocker = filter subscriptions. I'm not sure what you'd want to phrase it as, but the app as a whole is an ad blocker, and it seems to me it would make more sense to label what this actually is, that is, choosing your filters.

**Comment by ameshkov** [comment]
Actually, we've taken care of it in v3.0, so this is a dup:)
