### ISSUE TITLE
Show notification warning user about forgotten full log and HAR log enabled

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1752]
Sometimes users are forgetting that they've enabled full logging and/or HAR log for debugging purposes.
It would be helpful to show them a notification may be very hour that it can cost a battery life.

**Comment by ameshkov** [comment]
Let's do it in v3.0, it'd be better to avoid any UI changes in 2.11

**Comment by Revertron** [comment]
Duplicate: #1450
