### ISSUE TITLE
Test compatibility with HotSpotShield VPN and AdGuard in root+proxy mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1755]
We've got a report that AdGuard cannot work with it.

> Adguard никак не хочет подружиться с Hot-spot shield vpn. 
> Adguard в режиме прокси, если добавить приложение впн в фильтрацию, то оно не подключается в сети, если не включать фидьтрацию для него, то он работает, но трафик идет мимо Adguard и реклама не убирается на страницах.

**Comment by ameshkov** [comment]
@vozersky 
> Просто перестает подключаться впн в приложении, если ему включена фильтрация в adguard.

**Comment by vozersky** [comment]
повторить не могу, впн подключается успешно с Эдгардом в ручной прокси
однако есть другая проблема - не можем фильтровать https, логи чуть позже
