### ISSUE TITLE
LAN routes exclusions does not work properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1757]
A report from the telegram channel:

> Bug: (local) traffic to 192.168.7.1 is filtered by AG.
> pref.ip.routes.excluded has 2 entries starting with 192:
> 192.0.0.0/24
> 192.168.0.0/16.
> Only the 1st is respected (i.e. changing the order solves this).

What's important: **changing the order solves this**

Could it be that the new routes building code is flawed?

**Comment by sfionov** [comment]
Just checked it, in both cases, the same set of routes is added.
