### ISSUE TITLE
Allow blocking network access when screen is ON

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#176]
Something like what that app does:
https://play.google.com/store/apps/details?id=com.yirgalab.dzzz&hl=en_GB

Block all apps from network access when screen is off.

**Comment by evgeniy-ADG** [comment]
> What I mean is that I'd love to have an option to put apps into a "Doze"
> state when the screen turns off or even have an Aggressively Mode that's
> blocks all traffic until I have an app open in front of me...
> See this app for an example:
> https://play.google.com/store/apps/details?id=com.yirgalab.dzzz

**623633**

**Comment by ameshkov** [comment]
Done along with #633
