### ISSUE TITLE
Put active filters on top of the list

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1760]
> Предлагаю сделать пользование фильтрами более удобным. А именно: чтобы все включенные фильтры всегда отображались вверху всего списка фильтров. Как только пользователь отключит любой ненужный фильтр, он сразу же возвращается на своё место по алфавиту. Дело в том, что иногда нужно отключать фильтры разные для тестов и т.д.

### Expected behavior

Filters are sorted so that the enabled ones are always grouped and put on top of the list

### Actual behavior

Filters are not grouped nor sorted, this requires a lot of scrolling when testing / figuring out which filter is causing a problem

### Your environment

* Adguard version: 2.10.176

**Comment by Revertron** [comment]
Done in 3.0.
