### ISSUE TITLE
German App title and description in Google Play Store not reflecting the new name AdGuard / App title wrong

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdguardForAndroid#1761]
![2018-03-08_13-25-20](https://user-images.githubusercontent.com/25068100/37151211-d4aa4f6e-22d4-11e8-9b6b-18a6a75da2cd.png)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/ContentBlocker #109](https://github.com/AdguardTeam/ContentBlocker/issues/109) via [**ZenHub**](https://www.zenhub.com/)
