### ISSUE TITLE
Certificate "Move to system store" didn't work at all

### ISSUE THREAD

**Issue by remewer** [AdguardTeam/AdguardForAndroid#1763]
### Steps to reproduce

1. HTTPS Filtering > Certificate status > Move to system store
2. Grant Superuser permission. Toast message "Moved to system store" shows

### Expected behavior

AdGuard Personal CA certificate must show up under System Certificates in Android Settings

### Actual behavior

Nothing happened. Didn't move from User Certificates.
Workaround: Install Move Certs app.

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

1784190

### Your environment

* Adguard 2.11 beta
* Proxy(auto)
* Samsung Galaxy A5 2016 (SM-A510Y) 
* Android 7.0
* Rooted

**Comment by ameshkov** [comment]
@nkartyshov check the logs there
