### ISSUE TITLE
Update Privacy Policy and "How malware blocked" article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#177]
According to #162 

https://adguard.com/en/how-malware-blocked.html

**Comment by vbagirov** [comment]
"How malware blocked" is updated, both in English and Russian:
https://adguard.com/en/how-malware-blocked.html#other
https://adguard.com/ru/how-malware-blocked.html#other

**Comment by vbagirov** [comment]
Text regarding privacy policy is given to @mmigi , waiting for him to update privacy policy pages.

**Comment by vbagirov** [comment]
Updated:
https://adguard.com/en/privacy.html
https://adguard.com/ru/privacy.html
