### ISSUE TITLE
VPN is broken (randomly) on Samsung Galaxy S9

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1770]
### Steps to reproduce

0. You may need to repeat this a few times, the bug happens randomly
1. Make sure that you're connected to both Wi-Fi and a mobile network
2. Enable a VPN (all VPN apps are affected)
3. Switch the airplane mode ON
4. Wait a bit
5. Switch the airplane mode OFF

### Expected behavior
Traffic is routed through the VPN

### Actual behavior
1. Traffic is no more routed through the VPN
2. The only solution is to reboot the device
3. ip routes are distorted. tun0 routes are no more removed when you disable the VPN. Every time you restart a VPN, a new set of routes is added.
4. Lots of `netd` errors in the logcat.

Examples:
```
03-14 19:28:57.607 6077-6282/? E/Netd: Error adding route ::/0 -> fe80::4687:fcff:feda:871d wlan0 to table 1014: File exists
```

```
03-14 21:32:12.677 6044-6239/? I/Netd: RTNETLINK RTM_NEWRULE Process with UID_RANGE for HIGHER KERNEL
03-14 21:32:12.677 6044-6239/? E/Netd: Error adding IPv4 rule: File exists
03-14 21:32:12.677 6044-6239/? E/Netd: failed to add interface tun0 to VPN netId 542
03-14 21:32:12.679 6242-6543/? E/ConnectivityService: Exception adding interface: java.lang.IllegalStateException: command '3754 network interface add 542 tun0' failed with '400 3754 addInterfaceToNetwork() failed (File exists)'
03-14 21:32:12.680 6044-6239/? E/Netd: interface tun0 not assigned to any netId
03-14 21:32:12.680 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3755 network route add 542 tun0 1.0.0.0/8' failed with '400 3755 addRoute() failed (No such device)'
03-14 21:32:12.681 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3756 network route add 542 tun0 2.0.0.0/7' failed with '400 3756 addRoute() failed (No such device)'
03-14 21:32:12.681 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3757 network route add 542 tun0 4.0.0.0/6' failed with '400 3757 addRoute() failed (No such device)'
03-14 21:32:12.682 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3758 network route add 542 tun0 8.0.0.0/7' failed with '400 3758 addRoute() failed (No such device)'
03-14 21:32:12.682 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3759 network route add 542 tun0 11.0.0.0/8' failed with '400 3759 addRoute() failed (No such device)'
03-14 21:32:12.683 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3760 network route add 542 tun0 12.0.0.0/6' failed with '400 3760 addRoute() failed (No such device)'
03-14 21:32:12.683 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3761 network route add 542 tun0 16.0.0.0/4' failed with '400 3761 addRoute() failed (No such device)'
03-14 21:32:12.683 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3762 network route add 542 tun0 32.0.0.0/3' failed with '400 3762 addRoute() failed (No such device)'
03-14 21:32:12.684 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3763 network route add 542 tun0 64.0.0.0/6' failed with '400 3763 addRoute() failed (No such device)'
03-14 21:32:12.684 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3764 network route add 542 tun0 68.0.0.0/12' failed with '400 3764 addRoute() failed (No such device)'
03-14 21:32:12.684 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3765 network route add 542 tun0 68.16.0.0/13' failed with '400 3765 addRoute() failed (No such device)'
03-14 21:32:12.685 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3766 network route add 542 tun0 68.24.0.0/14' failed with '400 3766 addRoute() failed (No such device)'
03-14 21:32:12.685 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3767 network route add 542 tun0 68.28.0.0/15' failed with '400 3767 addRoute() failed (No such device)'
03-14 21:32:12.685 6242-6543/? E/ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '3768 network route add 542 tun0 68.30.0.0/16' failed with '400 3768 addRoute() failed (No such device)'
```

### Your environment

* Adguard version: 2.10
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy S9
* Operating system and version (e.g. Android 7.1.2): Android 8.0.0, Build: R16NW.G960FPUU1ARB3
* Rooted or not? No

**Comment by dzamyshlyayeva** [comment]
the customer sent logs as per your request ID 1308439

**Comment by ameshkov** [comment]
This is a bug of Samsung and it needs to be reported to them. As I understand, it affects ALL vpn-based apps.

**Comment by ameshkov** [comment]
As a temporary solution, please ask customers to enable `pref.vpn.disable.reconfiguration`, reboot the device and see how it goes

**Comment by ameshkov** [comment]
Reported to Samsung:
http://developer.samsung.com/forum/thread/vpn-is-broken-on-samsung-s9/201/346696?boardName=SDK&startId=zzzzz~

**Comment by sam20e** [comment]
enabled pref.vpn.disable.reconfigure options. will monitor. this shoudn't affect any performance or anything like that right?

**Comment by ameshkov** [comment]
@sam20e it should not. I'm trying it right now as well and it seems to work well.

Generally, AdGuard needs to reconfigure VPN on every network change in order to support IPv6 network interfaces -- we need to change VPN settings depending on whether IPv6 is available or not. When reconfiguration is disabled, you'll stay with the settings you've got when AG was enabled for the first time.

Usually, it's not a big deal, but it might be important for IPv6-only mobile providers like T-Mobile. We'd better handle this: https://github.com/AdguardTeam/AdguardForAndroid/issues/1773

**Comment by sam20e** [comment]
ok i enabled pref.vpn.disable.reconfigure and so far im not seeing any AD's. That means, yes. this workaround is working - Thank you. I just checked your case #1773 and saw your comment "we did it already" that means IPv6 will be automatically supported now when pref.vpn.disable.reconfigure is enabled? 

should i update your app or something? I will follow this topic here so in the future i will receive updates.. I don't think samsung gonna fix this issue anytime soon...

**Comment by ameshkov** [comment]
> should i update your app or something? I will follow this topic here so in the future i will receive updates.. I don't think samsung gonna fix this issue anytime soon...

No update required.

Regarding Samsung -- I am almost sure they will fix it, the issue is major and it affects every VPN app.

**Comment by sam20e** [comment]
ok @ameshkov thanks for your time. I appreciate it.

**Comment by evgeniy-ADG** [comment]
> Добрый день, как я понял проблема была в прошивке на телефоне galaxy s9+. После обновления проблема исчезла. Реклама блокируется в штатном режиме. Спасибо за помощь.

**Comment by ameshkov** [comment]
Awesome, the issue is resolved in the last firmware update indeed.

We will narrow the fix from #1774 specifically to that old version of Samsung firmware

**Comment by sam20e** [comment]
Hi @evgeniy-ADG @ameshkov what is your current firmware? i checked updates manually but it says "The latest updates have already been installed"

**Comment by ameshkov** [comment]
@sam20e this update is available:
https://uploads.adguard.com/up04_f83w7_2018-03-16_18.42.44.jpg

**Comment by sam20e** [comment]
@ameshkov not sure if you had noticed but samsung replied to your thread :

+++++++++++++++
This forum is only for Samsung Developer Discussions. Product user questions make it hard for developers to give or get other developer's help. Please use the more appropriate forums such as Samsung Product Communities where you may get better assistance.  This thread will be removed soon.Ron
+++++++++++++++

**Comment by ameshkov** [comment]
@evgeniy-ADG got it. Okay then, we'll leave the `pref.vpn.disable.reconfigure` workaround intact.

**Comment by vbagirov** [comment]
Just in case I will link relevant AG forum thread: https://forum.adguard.com/index.php?threads/28239

**Comment by hitechlover** [comment]
ameshkov,

The big update from Samsung doesn't fix this VPN problem at all. I applied the update when I first turned on my Galaxy S9 for the first time. VPN still doesn't work at all. This issue is either from Google Android 8.0 or from Samsung. One of them needs to fix this ASAP as this is a major problem.

Thanks

**Comment by ameshkov** [comment]
@hitechlover it is from Samsung for sure.

You can fix it for AdGuard as it is explained here: https://github.com/AdguardTeam/AdguardForAndroid/issues/1770#issuecomment-374153256

All VPN-based apps that reconfigure VPN on a network change are affected.

**Comment by sam20e** [comment]
@ameshkov did you manage to report this issue once again? as per http://developer.samsung.com/forum/thread/vpn-is-broken-on-samsung-s9/201/346696?boardName=SDK&startId=zzzzz  they said it's not the correct place to post so need to find another way to report..

**Comment by ameshkov** [comment]
Reported it to Android bug tracker:
https://issuetracker.google.com/issues/76356827

Hopefully, they know a way to notify Samsung devs about that.

**Comment by Mygod** [comment]
Some related discussions and a very useful logcat: https://github.com/shadowsocks/shadowsocks-android/issues/1712

**Comment by ameshkov** [comment]
@Mygod thanks for the link!

> It's a race condition. It doesn't happen every time. If you try it for an hour it will probably happen.

Yep, that's the very same bug caused by some sort of a race condition in Samsung's code.

**Comment by Amoxicillen** [comment]
@ameshkov  Thanks for your English report, it could let more and advanced developers know this BUG. 
I am a Galaxy S8 user and I have the same problem on the SSR randomly connect fails. It is very confused me. As those quotes, you can see there are also many same reports are posted by Chinese users, and most of them are Samsung users. (I also saw a Oneplus user) 
![38766581-79b44f70-4006-11e8-9169-995396c5d77f](https://user-images.githubusercontent.com/38374032/39394136-b8539db2-4b00-11e8-8cf3-ae83b05c445b.jpg)

**Comment by milewski** [comment]
I own a Samsung galaxy S9 I have this problem with shadowsocks and with chromecast, when even if I open no vpn at all the galaxy can't see the chromecast.. Only rebooting will restore the connection... And the sad part is that it brokes the connection in middle of a stream....

**Comment by vainglory403** [comment]
Until now.Samsung still doesnt fix the huge problem

**Comment by hitechlover** [comment]
That is Android problem, not Samsung. Many people reported the same problem
with their Google Pixel phones.

**Comment by vainglory403** [comment]
@hitechlover The writer have told us its Samsungs problem.Whatever……I regret to buy an Android device

**Comment by hitechlover** [comment]
This issue is not device specific. It affected all Android 8.0 phones that
has February 2018 updates and later. Google doesn't fix it yet and they
blame it on Samsung....lol

**Comment by vainglory403** [comment]
So now Android 9 has launched few days on Pixel.The BUG still exist,or not?

**Comment by ameshkov** [comment]
> So now Android 9 has launched few days on Pixel.The BUG still exist,or not?

This is a Samsung-specific issue, no problems with Google devices.

**Comment by ArTruong** [comment]
My Note 9 is the same issue

**Comment by ajitcool19** [comment]
I have my own vpn ipsec server with l2p.When I connect to my server with my Samsung A51 it forces it to reboot so yes the problem still exists

**Comment by leowood2000** [comment]
All samsung android 8.1 users, the temporary solution for this broken is 
-setting
- Connections
-Mor connection settings
-VPN
-SSR, enable Always-on VPN 
- DONE!!!!
