### ISSUE TITLE
App not getting filtered

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1772]
The Google play store app requests aren't getting filtered. When one of my apps update through the Play app it makes a request to one of google's servers which I can observe on a network level but it is not showing up in the filtering log. I am filtering all known Google apps so I don't know why it is not showing up in the log.

**Comment by ameshkov** [comment]
> which I can observe on a network level

What exactly do you see there? IP/port/protocol?

**Comment by Kusresa** [comment]
@ameshkov Go into Google Play app > My Apps > Check for updates. If there is a app needing an update, click update and you can observe a request being made to `redirector.gvt1.com` to update the app on the network level (not sure if it shows if no app needs an update). But this request does not show up in the filtering log at all.

**Comment by ameshkov** [comment]
Have you enabled filtering for Google play in the settings->apps management? It's disabled by default

**Comment by Kusresa** [comment]
I have both Google Play Store and Google Play services enabled for filtering.

**Comment by ameshkov** [comment]
Hm, could you please record a web requests log (settings -> advanced -> logging level) and attach it? I need to take a look

**Comment by vozersky** [comment]
closed as inactive issue, reopen if needed
