### ISSUE TITLE
Adguard's process wakes up and stays alive even if autostart is disabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#178]
Adguard app is disabled, autostart and autoupdate are disabled, but it still manages to access the Internet. 

User has provided logs: XGK-581-58528 

and screenshots: 
http://forum.adguard.com/showthread.php?6642-%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-Adguard&p=65334&viewfull=1#post65334

**Comment by ameshkov** [comment]
Fixed
