### ISSUE TITLE
adguard导致华为视频优酷版本无法播放

### ISSUE THREAD

**Issue by biange200** [AdguardTeam/AdguardForAndroid#1782]
adguard安卓正式版 会导致华为视频优酷2.2版本无法播放 一直黑屏
![screenshot_20180320-085234](https://user-images.githubusercontent.com/37582806/37656115-18a413f6-2c82-11e8-96a8-7ffa7f276e52.png)
![screenshot_20180320-085259](https://user-images.githubusercontent.com/37582806/37656135-24ac3840-2c82-11e8-99b7-6daa3b129312.png)
![screenshot_20180320-085444](https://user-images.githubusercontent.com/37582806/37656150-34d8e3b2-2c82-11e8-88ac-adb3702c3e45.png)

**Comment by zebrum** [comment]
@biange200 hello! Please provide a direct link to the app where it can be downloaded. Thanks!

**Comment by biange200** [comment]
这是一个华为手机自带的优酷定制版本 这是一个app 
http://a.vmall.com/app/C10360236?shareTo=com.android.mms&shareFrom=appmarket
这是下载地址

**Comment by zebrum** [comment]
@biange200 Also full log would be appreciated. Could you please do the following:
Go to AdGuard > Settings > Advanced and switch Logging level to Record everything 
Reproduce the issue
Go to AdGuard > Settings > Advanced and export the log to a .zip file 
Switch Logging level back to Default
Send log to support@adguard.com and specify the exact time when the issue was reproduced
Mention this thread in your letter so we could find your log.

**Comment by biange200** [comment]
日志附件已经上传了 还有一个新浪网无法过滤的日志附件 通过support@adguard.com邮箱上报了 请查看一下 谢谢

**Comment by zebrum** [comment]
So far we can't reproduce the issue :( Can you try our beta and see how it will go? https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.11.31-beta

**Comment by biange200** [comment]
输入这2个dns 会导致无法启动adguard
39.104.50.33
18.221.49.232



![Uploading Screenshot_20180321-202831.png…]()

**Comment by biange200** [comment]
能教我具体怎么操作解决？ 我是一个菜鸟

**Comment by biange200** [comment]
…能不能赠送给我一个测试版的key 我的中国大陆的 很难申请测试

**Comment by zebrum** [comment]
Actually you can go to Settings - Advanced - Update channel and choose  Beta there. After that you need to check for updates. You don't really need other license key for testing beta builds.

**Comment by biange200** [comment]
我使用的是破解版 我本来想申请测试的 但是我是一名中国用户 很难申请成功 希望你能赠送一个给我 终身key 谢谢了
还有一个问题 你们可以过滤手机浏览器上新浪网的广告？

**Comment by biange200** [comment]
我之前申请测试版 至今为止没收到key  我现在使用的测试版key是以前大陆之外一个网友帮我申请的__下个月就要到期了

**Comment by biange200** [comment]
你们官方的easylist china.规则来自cjx？ 但是效果比不了adclear abp之类的去广告软件和插件 起码同个规则 你们的无法过滤手机新浪网页

**Comment by vbagirov** [comment]
@biange200 please register an account on forum.adguard.com and semd me a PM with your beta key application details. You can find me there as `vasily_bagirov`.

**Comment by biange200** [comment]
forum我注册的用户名是biange200 邮箱是biange200@163.com 在很久以前注册的 密码忘记了 我点击找回密码 输入邮箱 但是验证那里一片空白 我无法完成验证
很遗憾我没有电脑 只有一个手机 我发现自己手机上无法完成验证 密码是找不回来了

**Comment by biange200** [comment]
我要睡觉了 这是我的登陆截图  看来是没法登陆了 我并不想重新注册个账号
![screenshot_20180321-224840](https://user-images.githubusercontent.com/37582806/37716759-39889fdc-2d5a-11e8-8344-5865cb5a9f79.png)

**Comment by vbagirov** [comment]
@biange200 I've changed your forum password to a temporary one, check your email for details.

**Comment by biange200** [comment]
thank you

**Comment by lancelot-moon** [comment]
> 我使用的是破解版 我本来想申请测试的 但是我是一名中国用户 很难申请成功 希望你能赠送一个给我 终身key 谢谢了
还有一个问题 你们可以过滤手机浏览器上新浪网的广告？

Here is AdGuard's official GitHub.
You said that you're using a cracked version and wish a free lifetime key. = =
How can a person be so shameless?

Most members in AdGuard team are Russians.
They don't know Simplified Chinese.
Pirate, although AdGuard team gave you convenience, you should write in English if you don't know Russian.
And then you should respect AdGuard's copyright!

**Comment by vbagirov** [comment]
@lancelot-moon thankfully, Google translate (and a lot of other online translators) does a pretty good job at transmitting the general meaning. Not everyone knows English, and we don't enforce "English-only" policy here (although it is welcomed).

As for the "cracked version" part: obviously, we can't approve of that, but we also can't do much about it. We'd rather at least help with honest problems (like inability to access forum) if we can than completely ignore such messages.
