### ISSUE TITLE
Problems with API compatibility on Android P

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1785]
There is some compatibility problems notification shows in AdGuard on Android P DP1.

It references to https://developer.android.com/preview/restrictions-non-sdk-interfaces.html.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/28726429/37703849-0fd2ffa4-2d08-11e8-81c0-ce4ee5f724e7.png)

</details>

### Your environment

* Adguard version: 2.11.31β
* Adguard filtering mode: VPN
* Device model: Google Pixel
* Operating system and version: Android P Developer Preview 1

**Comment by ameshkov** [comment]
Also, I promote this one to the high priority. It appears, that eventually they're planning to fully restrict the use of these APIs:
https://developer.android.com/preview/restrictions-non-sdk-interfaces.html

**Comment by Revertron** [comment]
And we are forced to eliminate all reflection uses?

**Comment by ameshkov** [comment]
Most likely, yes.

**Comment by ameshkov** [comment]
Ok, here're the issues we have right now:

1. Battery usage counter. We're using the PowerProfile and it won't be accessible on Android P. We'll be able to get the battery capacity via BatteryManager, but no the power profile values. Let's keep an eye on https://github.com/asksven/BetterBatteryStats

2. Bluetooth tethering check. By default, we don't react to that on new Android versions. We should change the code so that there is no tethering check when auto-pause is disabled.

**Comment by ameshkov** [comment]
@admitrevskiy we need to improve the battery usage meter code.

```
04-27 18:01:04.962 25793-25793/com.adguard.android I/com.adguard.android.service.BatteryServiceImpl: [main] Initializing PowerProfileXmlProxy
04-27 18:01:04.970 25793-25793/com.adguard.android I/com.adguard.android.service.BatteryServiceImpl: [main] Using default value for wifi.active instead of 0.0
04-27 18:01:04.971 25793-25793/com.adguard.android I/com.adguard.android.service.BatteryServiceImpl: [main] Using default value for cpu.active instead of 0.0
04-27 18:01:04.972 25793-25793/com.adguard.android I/com.adguard.android.service.BatteryServiceImpl: [main] battery.capacity=3000.0 cpu.active=34.0 wifi.active=31.0 radio.active=178.0
```

* `cpu.active` -- it seems that it's not properly parsed
* `wifi.active` -- it is now replaced with `wifi.controller.rx` and `wifi.controller.tx` (formula might change as well I guess)

Power profile xml:

[power_profile.xml.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1955836/power_profile.xml.zip)
