### ISSUE TITLE
Failed to launch AdGuard v2.11.64η after clearing data. It's useless even if I re-install it.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1791]
@ameshkov 

1. I am not sure if you know that AdGuard for Android will sometimes become very slow.
In such situation, I tapped the screen but it seems that the touch was not sensitive.
For solving the issue, I cleared AdGuard's cache or data, and then everything would be fine.

2. This time, I did the above step.
I'm failed to launch AdGuard v2.11.64η after clearing data.
It showed:
「AdGuard」 stops running for many times.
x Close the app.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Hbqc1mi.png)
</details><br/>

It's also useless even if I re-install a nightly version.
How can I launch AdGuard? T^T
Please help me~
Do I need to re-install a release or beta version, not a nightly version?

**Comment by ameshkov** [comment]
I've mentioned this crash in the translations issue. We'll publish an update today that will resolve the issue.

Meanwhile, the only way is to downgrade to release:(
