### ISSUE TITLE
adguard stop working

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#1794]
Android 8.1 rooted (magisk) Nexus 5X
adguard 2.11 beta using on rooted mode

switching between SIM data LTE and WiFi cause adguard to stop working.

screenshot: https://pasteboard.co/HdpyBna.png

**Comment by ameshkov** [comment]
@ham3dt uh, we need the logs to be exported right after that happens.

**Comment by ham3dt** [comment]
@ameshkov here's the log: https://ufile.io/m3mp5

**Comment by vozersky** [comment]
[adguard_logs_2.11.31_2603_2331.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1852751/adguard_logs_2.11.31_2603_2331.zip)

**Comment by ameshkov** [comment]
Meh, that's just Android killing AdGuard because it wants to do so :(

Partial solution: change the "watchdog period" in the advanced settings.

Meanwhile, we'll think about another option for rooted devices:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1812
