### ISSUE TITLE
adguard update massage required

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#1795]
when checking for new update if there's a filter update available it will automatically update the filters and show a massage "(x) filter(s) updated", or when app update available change log apears...

but if there's no update available no massage apears, i think it would be nice if users get a massage like "you're using the latest version of adguard and filters are up to date".

**Comment by carlylemiii** [comment]
![screenshot_20180324-153924](https://user-images.githubusercontent.com/29067983/37868766-df4e9cd4-2f79-11e8-8b08-323e769f9224.png)

**Comment by ham3dt** [comment]
well then it's a bug because i don't get any massage like that!

**Comment by ameshkov** [comment]
Logs?

**Comment by lancelot-moon** [comment]
There is the message.
I think it's only because you were distracted and then lost it.

**Comment by ham3dt** [comment]
@ameshkov here's the log: https://ufile.io/m3mp5

@lancelot-moon sorry what was your problem?

**Comment by TPS** [comment]
_#1810 leaves me needing a "massage" each time it happens 😉   Or maybe the title & OP should read "message."_
