### ISSUE TITLE
Wifi calling does not work in VPN mode: Orange PL

### ISSUE THREAD

**Issue by jojoro1** [AdguardTeam/AdguardForAndroid#1796]
With Adguard protection enabled I can't make phone calls over WiFi.
If I disable Adguard, wifi calling works ok.
Carrier Orange PL.
[adguard_logs_2.11.31_2403_0211.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1845136/adguard_logs_2.11.31_2403_0211.zip)

### Your environment

* Adguard version: latest stable and beta (no matter)
* Adguard filtering mode: VPN
* Device model: LG G6
* Operating system and version Android 7
* Not Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
@jojoro1 please do the following:

1. Open AdGuard, go to Settings -> Advanced -> Low-level settings
2. Find and edit `pref.ipv4.routes.excluded`
3. Add a new line there: `217.116.110.0/24`

Please let me know if this helps.

**Comment by jojoro1** [comment]
No. It didn't worked.

**Comment by ameshkov** [comment]
@jojoro1 sorry for the late reply.

Could you please collect a "record everything"-level log once again with the new settings?

**Comment by jojoro1** [comment]
Today los:
[adguard_logs_2.11.31_0204_1127.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1867729/adguard_logs_2.11.31_0204_1127.zip)

**Comment by ameshkov** [comment]
It seems that we need to exclude one more network, I see connections to `217.116.102.14:4500`.

Here is the network range that belongs to OPL:
https://bgpview.io/prefix/217.116.96.0/20

Please do the following:

1. Reset the low-level settings back to default
2. Add a new line to `pref.ipv4.routes.excluded`:  `217.116.96.0/20`

**Comment by jojoro1** [comment]
With this settings WifiCalling works fine! At last! Thank You.

**Comment by ameshkov** [comment]
Too early to close it:) We need to add this route exclusion to the default list.
