### ISSUE TITLE
Unable to restore the service after pausing

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1797]
> I hit pause and I can't turn it on again

### Steps to reproduce

1. Install AdGuard, put a widget on the screen
2. Pause it
3. Try to start the service again
4. User states he can't start the protection the same way it as paused

### Expected behavior

You can start and pause AdGuard via the widget

### Actual behavior

It's won't unpause

<details><summary>Screenshot and logs:</summary>

![image](https://user-images.githubusercontent.com/15856304/37873281-174e8678-3022-11e8-9b5f-799ade4e456a.png)

https://uploads.adguard.com/kak4w.txt

</details>

### Customer ID 
1781341

### Your environment

* Adguard version: 2.10.176, pref.vpn.disable.reconfigure enabled
* Adguard filtering mode: VPN
* Device model: SAMSUNG SM-N950F Galaxy Note 8
* Operating system and version 7.1.1
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? none

**Comment by zebrum** [comment]
can't repro on the latest nightly. 
@vozersky try on samsung, please

**Comment by vozersky** [comment]
@zebrum I can actually reproduce the problem, but with another type of our widget, the one on the screenshot works fine for me.

**Comment by vozersky** [comment]
@evgeniy-ADG the latest nightly should fix the problem, pls suggest user to install it
