### ISSUE TITLE
AdGuard 2.11.31 - blocking internet connections

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1798]
> While I am using adguard on a new phone, I discovered something. When I turn on the AdGuard, internet, Instagram feed, and social messages are not working. I have to turn off adguard first and press renews, then the social messenger, Instagram, and other start working.

The app is configured to use speedy filtering mode, does not use HTTPS filtering, AdGuard DNS is turned off.

### Expected behavior

Apps have access to the internet

### Actual behavior

Have to disable AdGuard and refresh apps

<details><summary>Logs:</summary>

https://uploads.adguard.com/2ifez.zip

</details>

### Customer ID 
1488728

### Your environment

* Adguard version: 2.11.31
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy A8 2018 SM-A530N
* Operating system and version: 7.1.1
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by evgeniy-ADG** [comment]
Another report: https://uploads.adguard.com/paxpz.zip

- ID: 1317589
- Adguard version: 2.11.31
- Adguard filtering mode: VPN
- Device model: Samsung Galaxy S8
- Operating system and version: 8.0.0
- Rooted or not? n/a
- Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

Is it a different issue? Please let me know if so, will file a separate report. This customer uses DNS and noticed the connection between using DNS and not being able to access the internet.

**Comment by evgeniy-ADG** [comment]
More reports: https://uploads.adguard.com/k3ts1.zip

> AdGuard can't access the internet when using my home wifi but works fine when using mobile data
> 
> Things I tried: restarting the app/phone/router, testing other devices and they worked fine, clearing app cache, clearing app data (which caused another problem), switching to the beta version, enabling and disabling DNS/HTTPS, swapping DNS server, _pref.vpn.disable.reconfigure_ enabled.

- ID: 1810398
- Adguard version: 2.11.31
- Adguard filtering mode: VPN
- Device model: OnePlus ONEPLUS A5000
- Operating system and version: 8.0.0
- Rooted or not? n/a
- Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by evgeniy-ADG** [comment]
https://uploads.adguard.com/wi9ax.zip

> It works fine until I turn on the DNS filtering option. No matter what DNS
> settings or servers I pick, it just seems to block every connection and no
> websites are displayed (they time out).

ID: 1810996
Adguard version: 2.11.31
Adguard filtering mode: VPN
Device model: Samsung Galaxy S9
Operating system and version: 8.0.0
Rooted or not? n/a
Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by vozersky** [comment]
@evgeniy-ADG 2.11.76 pls

**Comment by vozersky** [comment]
@evgeniy-ADG from the latest log: 
`Adding special route for bypassing IPv4 traffic due to pref.vpn.ipv4.bypass
Adding special route for bypassing IPv6 traffic due to pref.vpn.ipv6.bypass`

**Comment by ameshkov** [comment]
Reopen if there's new info
