### ISSUE TITLE
Missing Browser Recognition: CM Private Browsing

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#18]
Part of CM Antivirus

https://play.google.com/store/apps/details?id=com.cleanmaster.security

**Comment by ameshkov** [comment]
What do you mean?

**Comment by ameshkov** [comment]
Ok, got it:)

**Comment by TPS** [comment]
@ameshkov Sorry, browser glitch, this __isn't__ a duplicate ☺

**Comment by ameshkov** [comment]
Ops, sorry:)

**Comment by Revertron** [comment]
Added.

**Comment by TPS** [comment]
Thanks! ☺

**Comment by TPS** [comment]
As [I mentioned](https://github.com/AdguardTeam/AdguardForAndroid/issues/2#issuecomment-138426767), AdGuard seems to have a serious incompatibility with multiple site requests @ once, especially with CM Private Browsing. As per this browser's design, it tends to launch at _least_ 2 requests immediately on every fresh page load — 1 to the original page, & another to SafeBrowsing-type website to check phishing, &c.  Unfortunately, as mentioned, this triggers an AdGuard crash nearly _every_ pageload in this browser to the point it's virtually useless to attempt it.

My question is, should continue this discussion in [this very issue](#), leave it as part of #2, or open a brand new issue tracking crashes happening from too many varied requests through AdGuard at once?

**Comment by Revertron** [comment]
@TPS I've installed and looked into this app, and I must conclude that it is bullshit.  I didn't enable Chrome scanning because I don't trust such app.

Besides, Adguard alone has browsing security module that is using SafeBrowsing mechanism. Better to use it.

**Comment by TPS** [comment]
@Revertron BS or not, CM Security is the __#2__ utility / tool software on GPlay store now (been so for months), & provides _its_ SafeBrowsing freely, so it may be wise to work with it.  Given its popularity, people are more likely to uninstall AdGuard than it!

**Comment by ameshkov** [comment]
@Revertron, your opinion about this browser does not mean Adguard shouldn't work with it.

**Comment by TPS** [comment]
@AdGuardTeam It looks like the CM folks have now released Private Browsing as a standalone browser @ https://play.google.com/store/apps/details?id=com.cmcm.armorfly.…  D'y'all mind adding this 1, also? :bow:

**Comment by ameshkov** [comment]
Yep, thank you for alerting us!
https://github.com/AdguardTeam/AdguardForAndroid/issues/862
