### ISSUE TITLE
Remove Level3 from the list of available DNS servers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1800]
Due to this:
http://www.level3.com/en/landing-pages/level-3-dns-migration/

**Comment by sfionov** [comment]
They also have 6 resolvers with easily-typed addresses which was never publicly announced:
4.2.2.1 a.resolvers.level3.net
4.2.2.2 b.resolvers.level3.net
4.2.2.3 c.resolvers.level3.net
4.2.2.4 d.resolvers.level3.net
4.2.2.5 e.resolvers.level3.net
4.2.2.6 f.resolvers.level3.net
