### ISSUE TITLE
Add a checkbox that disables Assistant and Filtering Log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1808]
The filtering log's impact on CPU usage is zero, however, we're getting requests from people confused by the "CPU usage" toast in v2.10.

See the details:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1808#issuecomment-381332270

**Comment by lancelot-moon** [comment]
Yes, I really need a switch for disabling Filtering Log.

After I record some log and want to check, I need a switch for stopping logging, otherwise I have no method to stop logging.

Please let the switch back!

**Comment by TPS** [comment]
@lancelot-moon Would a switch to visually _freeze_ the log do you (but not altogether stop it)?  I'm concerned about forgetting to restart or missing something necessary, due to, e.g., https://github.com/AdguardTeam/AdguardForAndroid/issues/1074#issuecomment-283744603.

**Comment by ameshkov** [comment]
This switch will be added to the low-level settings and called `pref.enable.filtering.log`.

When this switch is disabled, we need to:
1. Stop the filtering log
2. Hide the "assistant" button from AdGuard notification

I still think that all the people requesting for such an option do it purely because they saw the misleading notification about CPU/memory usage in v2.10. So after some time they'll get used to the new scheme and see that there's absolutely no difference. Meanwhile, let's have a new flag :).

**Comment by ameshkov** [comment]
Useful comment:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1828#issuecomment-381684380

It indeed might be useful to pause filtering log at some point. Low-level preference won't solve it.

**Comment by lancelot-moon** [comment]
In the past, I already told about it.
But you don't understand.
> After I record some log and want to check, I need a switch for stopping logging, otherwise I have no method to stop logging.

I hate that the log is constantly logging when I only need to check somewhere.
I need the switch to "pause".
You should let the switch back in AG for Android and iOS

**Comment by Nzzyme** [comment]
+1 to get the toggle switch back on the Filtering Log page.

**Comment by ameshkov** [comment]
It's already here in the nightly, guys
