### ISSUE TITLE
AdGuard 2.11.76 beta flagged for containing a Trojan

### ISSUE THREAD

**Issue by SpasilliumNexus** [AdguardTeam/AdguardForAndroid#1809]
I maintain a collection of purchased and free Android apps I have installed on my phone on using PC software called [Raccoon](http://raccoon.onyxbits.de).

For whatever reason, when downloading the latest 2.11.76 beta of AdGuard, upon completion, it is being flagged for having a severe trojan in Windows Defender (Windows 10), and is instantly quarantined. I am sure that this is just a false-positive flag.

The name: Trojan:Win32/Spursint.Q!cl
Information: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fSpursint.Q!cl&threatid=2147723733

Versions prior to this downloaded fine with no flagging. For now, I have allowed Windows Defender to keep 2.11.76, despite now having a notification of it being dangerous.

**Comment by ameshkov** [comment]
@SpasilliumNexus thank you for reporting it!

@TheHasagi please check the file on virustotal and report to AVs if there's any false positive.

**Comment by Revertron** [comment]
I've submitted it to Microsoft as false positive.
https://www.microsoft.com/en-us/wdsi/submission/0b170569-ea65-4387-ba11-02f21ab16130

**Comment by vozersky** [comment]
can't reproduce with an apk from our side


![image](https://user-images.githubusercontent.com/17472907/38142117-d70e77fa-3443-11e8-91ed-278fdac2e6e9.png)

https://www.virustotal.com/#/file/dbd432ae84e282253a41d180a4895c92b00a0e9d3308f59178a5bf531addafc6/detection
