### ISSUE TITLE
Website ß has been incorrectly uploaded to Amazon

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1810]
@AdguardTeam

### Steps to reproduce

Update to latest Amazon ß version via Amazon Appstore

### Expected behavior

Amazon ß should've been installed/updated, complete w/ checking Amazon ß license.

### Actual behavior

Website ß is installed as freemium, complete w/ prompting to update to licensed version.

----
_N.B.: I'm trying to make this general enough that it can be kept as a tracking (openable/closable) issue for each Amazon update, as it seems to be the case every or every other update.  Following posts can give details for each iteration._

**Comment by TPS** [comment]
Today, Amazon has AG website-v2.11.76ß, which has problems as mentioned above.

**Comment by TPS** [comment]
_P.S.: This website version seems not to recognize either of my browsers (LastPass or Ff Klar) for the sake of freemium adblocking, per **Apps Management** settings._

**Comment by ameshkov** [comment]
@nkartyshov @vozersky sort this out please

**Comment by vozersky** [comment]
@TPS should be fine now

**Comment by TPS** [comment]
@vozersky Yup, exported settings, uninstalled, redownloaded/reinstalled, restored purchases (to refresh license), & finally reimported settings.…  All is well. ☺

Thanks, @all.

**Comment by vozersky** [comment]
@TPS  Thanks a lot for your help!  We'll double check the Amazon build next time.
