### ISSUE TITLE
Please add Cloudflare Public DNS and others in the known DNS list.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1811]
Cloudflare Public DNS:
https://1.1.1.1/

Global Coverage From an Anycast-Powered Network
https://www.cloudflare.com/dns/
https://blog.cloudflare.com/announcing-1111/

IPv4:
one.cloudflare-dns.com 1.1.1.1
two.cloudflare-dns.com 1.0.0.1

IPv6:
2606:4700:4700::1111
2606:4700:4700::1001

It supports both DNS-over-TLS and DNS-over-HTTPS.

DNS speed test:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/R2SGQ5b.png)
</details><br/>

(FUN DNS, OneDNS, PdoMo-DNS, AdClear DNS and CuteDNS are DNS providers with adblock feature from China.
But I don't trust them.)

DNS Performance Analytics and Comparison:
https://www.dnsperf.com/#!dns-resolvers

Freenom World DNS:
http://www.freenom.world/en/index.html
80.80.80.80
80.80.81.81

Others:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1613#issuecomment-348259151

I also suggest that AdGuard DNS uses Cloudflare Anycast-Powered Network instead of vultr.com if it's possible...
https://github.com/AdguardTeam/AdguardDNS/issues/261

Thanks.

**Comment by TPS** [comment]
@lancelot-moon _If_ adding the Sprint DNSs, there's a note (@ link provided) that the DNSs listed above are _not_ meant for general DNS, though other _global_ IPv4/IPv6 addresses are provided for such.  Though, since Sprint is a commercial MNO/ISP, I don't really understand why you have it on this list @ all.…

**Comment by lancelot-moon** [comment]
Please add this. too.
https://101.101.101.101/index_en.html
Quad101 is TWNIC's experimental Public DNS project. TWNIC (Taiwan Network Information Center) is a ccTLD (country-code Top Level Domain) registry operator. TWNIC runs one of the world's fastest DNS infrastructure.
The specific IP address (101.101.101.101) has been assigned to Quad101 Public DNS systems. TWNIC's world-class network infrastructure along with comprehensive Quad101 features will build a better Internet in Taiwan.

Quad101 DNS
IPv4:
101.101.101.101
101.102.103.104

IPv6:
2001:de4::101
2001:de4::102

**Comment by lancelot-moon** [comment]
https://blahdns.com/

BlahDNS started to support DoH/DoT.

**Comment by lancelot-moon** [comment]
@admitrevskiy
May you additionally add these DNS servers in the known list at least?
Thanks.

Quad101 DNS:
It supports **DoT**.
https://101.101.101.101/index_en.html
https://blog.twnic.net.tw/2018/07/02/1086/
Please add Quad101 DNS both in general DNS and secure DNS list.

IPv4:
101.101.101.101
101.102.103.104

IPv6:
2001:de4::101
2001:de4::102

BlahDNS:
https://blahdns.com/
108.61.201.119 <- Its Japanese server will change IP randomly.
217.61.0.97

Its Japanese server supports **DoH/DoT**.

Fourth Estate:
https://dns.fourthestate.co/
45.32.36.36
45.77.165.194
179.43.139.226

Alternate DNS:
https://alternate-dns.com/index.php
23.253.163.53
198.101.242.72

Hurricane Electric:
http://www.he.net/
74.82.42.42

FreeDNS:
https://freedns.zone/en/
37.235.1.174
37.235.1.177

B/R

**Comment by vozersky** [comment]
List of added DNS (so far)

1)Cloudflare Public DNS (IPv4/IPv6)
2)Freenom World DNS
3)Fortinet Secure DNS
4)Neustar Recursive DNS
5)Safe DNS
6)Strongarm DNS
7)Safesurfer DNS

**Comment by lancelot-moon** [comment]
Please carefully read the content.
I hope that you additionally add the 6 DNS service.

Quad101 DNS:

BlahDNS: (With adblock)

Fourth Estate:

Alternate DNS: (With adblock)

Hurricane Electric:

FreeDNS:

**Comment by ameshkov** [comment]
We add only popular and stable DNS servers for which we won't need to check if they're still alive.

Among the listed DNS servers only Quad101 DNS falls under this definition.
We will not add others, users can configure them manually.

**Comment by lancelot-moon** [comment]
Fourth Estate, Alternate DNS, Hurricane Electric and FreeDNS are also popular and stable.

Especially, you only allow 1 manual DNS service by user.

**Comment by ameshkov** [comment]
> Fourth Estate, Alternate DNS, Hurricane Electric and FreeDNS are also popular and stable.

My opinion is that a DNS server at least needs to provide an anycast IP address in order to be classified as stable. This shows that a DNS server owner is serious enough to invest money and time into it.

> Especially, you only allow 1 manual DNS service by user in AG for Android.

Yeah, that's a legit issue and we'd better let it:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2009

**Comment by lancelot-moon** [comment]
CleanBrowsing DNS is in Secure DNS list, but I think that you can also add it in general DNS list.

CleanBrowsing DNS:
https://cleanbrowsing.org/ip-address

End.
All popular DNS service is already listed in the topic.
Sorry if bothering you.

**Comment by lancelot-moon** [comment]
May you add Quad101 DNS? (☍﹏⁰)

Title: Quad101 DNS
Description: **Free alternative DNS by TWNIC (Taiwan Network Information Center)**
IPv4:
101.101.101.101
101.102.103.104

IPv6:
2001:de4::101
2001:de4::102

I supports DoT.
$ kdig +tls-host=101.101.101.101 @101.101.101.101 twnic.net.tw. a
;; TLS session (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 59758
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR

;; QUESTION SECTION:
;; twnic.net.tw.                IN      A

;; ANSWER SECTION:
twnic.net.tw.           3599    IN      A       124.9.9.9

;; Received 57 B
;; Time 2018-06-29 13:22:24 CST
;; From 101.101.101.101@853(TCP) in 26.7 ms

$

**Comment by edentw** [comment]
@lancelot-moon 
Sorry, here's my personal advice:

If the authorities have difficulty adding third-party DNS,
Let's just remove all third-party DNS options,
Instead, just put in your own DNS and custom options.

**Comment by lancelot-moon** [comment]
Remove all third-party DNS options??
That's kidding.
The known DNS list is convenient for users.
Almost all DNS changers give a known DNS list in app.
I disagree with your opinion.
