### ISSUE TITLE
Consider providing an option to renice the AG process priority

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1812]
On rooted devices, we can try to increase the process priority by using renice.

More on processes priorities:

* https://medium.com/google-developers/who-lives-and-who-dies-process-priorities-on-android-cb151f39044f
* https://developer.android.com/guide/components/activities/process-lifecycle.html

More on nice/renice:

* https://groups.google.com/forum/#!topic/tasker/GykupO-HyRs
* https://stackoverflow.com/questions/31922708/android-change-priority-application-for-rooted-device
* https://stackoverflow.com/questions/30333478/setting-priority-of-a-process-without-using-nice-and-or-renice-command

Example:

* http://4pda.ru/forum/index.php?showtopic=760461&st=40#entry58193696

If it works properly, we can get rid of the `watchdog period` setting as it will be redundant.

**Comment by TPS** [comment]
> If it works properly, we can get rid of the `watchdog period` setting as it will be redundant.

@ameshkov But those of us who're _not_ rooted (i.e., most of the userbase) may still want it, right?

**Comment by ameshkov** [comment]
@TPS afaik, there are no issues with non-rooted devices as Android tolerates VPN.

Moreover, those who use the VPN mode are able to enable "always-ON" VPN which is a 100% guarantee that nothing bad happens.

**Comment by TPS** [comment]
Is there a downside to keeping the existing service/code, as-is, but defaulted off/0?  I just ~~think~~ feel (no hard evidence, since I've not run w/o watchdog in _many_ versions), w/ the myriad of OEM ROMs (@ least) & the pursuit for every-increasing battery life, this is something much easier to remove unnecessarily than keep/return, just-in-case.

How do I determine how often this service actually _is_ used, to collect evidence, 1 way or the other?

**Comment by TPS** [comment]
Also, many users do still use Android versions w/o "Always-On" capability will still need the watchdog setting.

**Comment by sfionov** [comment]
One more useful link:
https://github.com/mcgill-cpslab/mobile-research/wiki/How-Android-manages-background-processes%3F

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-You need rooted device with Android lower than Oreo
-Reinstall AG
-Go to `Settings -> Advanced -> Low Level Settings`
-Enable `pref.root.set.oom_adj`
-In `Settings -> General -> Notifications` choose `None`

Expected result:
Android OS shouldn't kill AG process without notification icon
