### ISSUE TITLE
[NIGHTLY] AdGuard filters the apps excluded from filtering

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1816]
### Steps to reproduce
1. Exclude an app (i.e M-BOX-2) from filtering via Apps Management
2. AdGuard will still reroute its traffic thru local VPN

### Expected behavior
AdGuard shouldn't reroute the excluded apps' traffic through its own local VPN

### Actual behavior
Even when app is whitelisted via Apps Management, its traffic is still going through AdGuard's local VPN

### Customer ID and logs
1811773

### Your environment
* Adguard version: 2.11.76n
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy S7 SM-G930F
* Operating system and version: Android 7.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None

**Comment by ZakPhoenixMcKracken** [comment]
Hi, I'm the user who started the issue.
This is very clear with the app M-BOX-2, but it is reproducible with any other app.

If I turn off AdGuard, then start M-BOX-2 app (for instance), I see ads everywhere.
If I turn on AdGuard, but the M-BOX-2 app is excluded from the App Settings, I expect to see the ads anyway. Instead, they are blocked, as if the app exclusion setting was ignored.

**Comment by ameshkov** [comment]
The ads might be loaded not by the app itself but by the Google Play services app. Try disabling AG for that app as well and check if they're loaded now.

**Comment by ZakPhoenixMcKracken** [comment]
So, if the M-BOX-2 app calls Google Play, whitelisting the first app doesn't automatically whitelist the subsequent calls to other apps?
I will try soon.
Is there a way to see which apps/services are called? Maybe enabling a log... ?
Thank you

**Comment by TPS** [comment]
Also, if DNS-block is activated, DNS requests are usually does via the OS, & so those'll be blocked, also.

AG _has_ a filtering log in the menu, where you can watch all this.
