### ISSUE TITLE
com.sonymobile.androidapp.audiorecorder presumably needs HTTPS filtering disabled by default

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1817]
https://github.com/AdguardTeam/AdguardFilters/issues/13820

**Comment by carlylemiii** [comment]
@vozersky with all N+ targeting apps automatically having HTTPS filtering disabled now in 2.11.80 there's no need for this actually, right?

**Comment by ameshkov** [comment]
We need to out it to the default exceptions list anyway.
