### ISSUE TITLE
Add Additional Ad Blocking Lists

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardForAndroid#1818]
We have a number of Ad Blocker users lists in android which are great but could we have an option to add additional lists to your selection, this would be useful to add speciality lists, gambling, porn lists and allow a blocking setup for any individuals need.

**Comment by vozersky** [comment]
@versavius  Hello! Where exactly I can take a look at those lists?

**Comment by versavius** [comment]
So i use P-Hole on a Raspberry Pi at home to provide blocking for all devices at home, its like your Adguard DNS except on a home box.

The lists i currently use are below, some of which you already use like the easylist.

One suggestion i do have is you could create an Adguard set of lists on github.

Say Adguard Block lists for "Gambling, Bit-Coin Mining, Malware, Phishing, Porn, Ransomware"

This would be easy for more junior ad-blockers who don't know what easylist is and are confused as to what an "annoyances list is", but mostly for those people who just want to point and click and activate.

I run all of the below on my Pi to protect my home network while running through Adguard DNS, so i get a double layer of protection.

A Bitcoin mining block list would be useful, especially since there have been app's known to masquerade as useful apps but just abuse devices in the background.

# Advertising
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://hosts-file.net/ad_servers.txt
https://v.firebog.net/hosts/Easylist.txt
https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/Spotifynulled.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts # Adverts & Malware
https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt
http://v.firebog.net/hosts/AdguardDNS.txt
http://v.firebog.net/hosts/Easylist.txt



#Tracking & Telemetry Lists

https://v.firebog.net/hosts/Airelle-trc.txt
https://v.firebog.net/hosts/Easyprivacy.txt
https://v.firebog.net/hosts/Prigent-Ads.txt
https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/tyzbit/hosts
https://raw.githubusercontent.com/CHEF-KOCH/Canvas-Font-Fingerprinting-pages/master/Canvas.txt
https://raw.githubusercontent.com/CHEF-KOCH/WebRTC-tracking/master/WebRTC.txt
https://raw.githubusercontent.com/CHEF-KOCH/Audio-fingerprint-pages/master/AudioFp.txt
https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt 
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt 
http://v.firebog.net/hosts/Easyprivacy.txt
http://v.firebog.net/hosts/static/SamsungSmart.txt






#Malicious Lists

https://v.firebog.net/hosts/Airelle-hrsk.txt
https://mirror1.malwaredomains.com/files/justdomains
https://hosts-file.net/exp.txt
https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
https://v.firebog.net/hosts/Prigent-Malware.txt
https://raw.githubusercontent.com/quidsup/notrack/master/malicious-sites.txt
https://v.firebog.net/hosts/Shalla-mal.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
http://v.firebog.net/hosts/Shalla-mal.txt
http://v.firebog.net/hosts/Airelle-hrsk.txt


#Malware
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts # Adverts & Malware
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
http://mirror1.malwaredomains.com/files/justdomains
https://hosts-file.net/emd.txt
https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
https://www.malwaredomainlist.com/hostslist/hosts.txt
http://mirror1.malwaredomains.com/files/domains.txt

#Bit Coin Mining
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts
https://raw.githubusercontent.com/Marfjeh/coinhive-block/master/domains
https://v.firebog.net/hosts/static/w3kbl.txt


#Ransomware
https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
http://www.networksec.org/grabbho/block.txt

#Phishing
https://v.firebog.net/hosts/Prigent-Phishing.txt
https://openphish.com/feed.txt
https://hosts-file.net/psh.txt

#BotNet
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist 


#Fanboy's Annoyance List
#https://easylist.to/easylist/fanboy-annoyance.txt


#Spam
https://hosts-file.net/grm.tx
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
http://v.firebog.net/hosts/BillStearns.txt
http://sysctl.org/cameleon/hosts
https://raw.githubusercontent.com/piwik/referrer-spam-blacklist/master/spammers.txt
http://someonewhocares.org/hosts/hosts
https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt
https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
http://www.joewein.net/dl/bl/dom-bl.txt

#Peer to Peer Snoopers
https://jult.net/block.txt


#Firewall
http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
#Feodo IP Blacklist
https://feodotracker.abuse.ch/blocklist/?download=ipblocklist
#Emerging Threats - Spamhaus DROP Nets
http://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
#DShield.org Suspicious Domain List (Low Sensitivity Level)
https://isc.sans.edu/feeds/suspiciousdomains_Low.txt
#DShield.org Suspicious Domain List (Medium Sensitivity Level)
https://isc.sans.edu/feeds/suspiciousdomains_Medium.txt
#DShield.org Suspicious Domain List (High Sensitivity Level)
#Emerging Threats - Known hostile or compromised hosts
http://rules.emergingthreats.net/blockrules/compromised-ips.txt
#Emerging Threats - Known hostile or compromised hosts
http://rules.emergingthreats.net/blockrules/compromised-ips.txt
#Binary Defense Systems Artillery Threat Intelligence Feed and Banlist Feed
http://www.binarydefense.com/banlist.txt
#AlienVault - IP Reputation Database
https://reputation.alienvault.com/reputation.snort.gz
#SSLBL - SSL Blacklist
https://sslbl.abuse.ch/blacklist/sslipblacklist.csv
#Blocklist.de - Attacks on the service SSH
https://lists.blocklist.de/lists/ssh.txt
#Blocklist.de - Attacks on the service Mail, Postfix
https://lists.blocklist.de/lists/mail.txt
#Blocklist.de - Attacks on the service Apache, Apache-DDOS, RFI-Attacks
https://lists.blocklist.de/lists/apache.txt
#Blocklist.de - Attacks on the Service imap, sasl, pop3
https://lists.blocklist.de/lists/imap.txt
#Blocklist.de - Attacks on the Service FTP
https://lists.blocklist.de/lists/ftp.txt
#Blocklist.de - All IP addresses that tried to login in a SIP-, VOIP- or Asterisk-Server
https://lists.blocklist.de/lists/sip.txt
#Blocklist.de - Attacks attacks on the RFI-Attacks, REG-Bots, IRC-Bots or BadBots
https://lists.blocklist.de/lists/bots.txt
#Blocklist.de - All IPs which are older then 2 month and have more then 5.000 attacks
https://lists.blocklist.de/lists/strongips.txt
#All IPs which attacks Joomlas, Wordpress and other Web-Logins with Brute-Force Loginss
https://lists.blocklist.de/lists/bruteforcelogin.txt
#Bambenek's Feed of known, active and non-sinkholed C&Cs IP addresses
http://osint.bambenekconsulting.com/feeds/c2-ipmasterlist.txt
#BotScout FireHOL IP List
http://botscout.com/last_caught_cache.txt
#Brute Force Blocker IP List
http://danger.rulez.sk/projects/bruteforceblocker/blist.php
#CI Army Bad IPs
http://www.ciarmy.com/list/ci-badguys.txt




# CJX Annoyance List
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt

# EU: Prebake - Filter Obtrusive Cookie Notices
https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt


# Fake news sites
#https://raw.githubusercontent.com/marktron/fakenews/master/fakenews
#https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts

# Block pornography
https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts
https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts
http://securemecca.com/Downloads/hosts.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts


# Block gambling sites
https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts

**Comment by TPS** [comment]
@versavius Would #13 be sufficient for you?  That's 1 heck of a meta-list!  Also, this is essentially an instance of #12.

**Comment by TPS** [comment]
Also, @all, if you even include a small # of these lists directly, #1820 could become _very_ important.

**Comment by versavius** [comment]
@TPS  yes it would be to add some new lists, but not just that, i think as time goes by to get more of the public using these lists we need to make it simpler, to any Techie or someone here we know what these lists mean by name, but for the average iphone user they just want to block adverts, tracking, malware etc, but more lists with de-duplication is a good thing.

If the ad companies got their act together this wouldn't be necessary and they would make money, but oh well...

**Comment by TPS** [comment]
@versavius Problem is, @AdguardTeam is pretty much _guaranteeing_ any list officially included.  That's not really practical for ***all*** these.  Also, @ some point, the UI becomes overwhelming for mobile.

**Comment by ameshkov** [comment]
AG does not support hosts files syntax yet.

However, once we add it, the list from https://github.com/AdguardTeam/AdguardForAndroid/issues/1818#issuecomment-378945048 might be useful, thank you!
