### ISSUE TITLE
Warn users that moving certificate to the system store lowers security

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1824]
When the certificate is moved to the system store, AdGuard has to remove HPKP and certificate transparency support (otherwise, some websites which use it won't open at all).

This lowers (slightly, IMO) security and we must warn users about it.

**Comment by ameshkov** [comment]
Moreover, in light of [these changes](https://www.bleepingcomputer.com/news/security/starting-today-google-chrome-will-show-warnings-for-non-logged-ssl-certificates/), a special policy needs to be enabled:
https://www.chromium.org/administrators/policy-list-3#CertificateTransparencyEnforcementDisabledForCas

**Comment by admitrevskiy** [comment]
Resolved
