### ISSUE TITLE
Google Maps not working with ad blocking enabled in newest beta (2.11.80)

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1825]
### Steps to reproduce

1. Have AdGuard enabled (and mobile ads, spyware, English, annoyances, social media filters installed).
2. Open Google Maps.
3. Varying degrees of Google Maps not functioning at all.
4. Disabling AdGuard or disabling blocking for Maps resolves the issue.

This happens whether on mobile data or Wi-Fi.

### Expected behavior

I should be able to block trackers in Google Maps while retaining the use of Google Maps

### Actual behavior

AdGuard breaks Maps.

<details><summary>Screenshot:</summary>

![screenshot_20180414-120800](https://user-images.githubusercontent.com/29067983/38770783-d32c4680-3fdd-11e8-829b-8d7f6ee716a3.png)
![screenshot_20180414-120750](https://user-images.githubusercontent.com/29067983/38770784-d4c6eda6-3fdd-11e8-9b48-38876ac4023d.png)
![screenshot_20180414-120957](https://user-images.githubusercontent.com/29067983/38770786-d6529de6-3fdd-11e8-9d11-25c89799a2a5.png)

</details>

### Your environment

* Adguard version: 2.11.80 beta/release candidate
* Adguard filtering mode: VPN
* Device model: Pixel 2 XL
* Operating system and version: Android 8.1.0
* Rooted or not? Yes, cert in system store
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

Full logs if necessary (I presume default logs were sent when I submitted feedback in-app):

[adguard_logs_2.11.80_1404_1208.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1910653/adguard_logs_2.11.80_1404_1208.zip)

**Comment by ameshkov** [comment]
How often does it happen?

**Comment by carlylemiii** [comment]
It's happening every time, right away, after re-enabling AdGuard. (When I initially wrote in via the app, I thought it was occasionally, but after testing now, it's all the time.)

**Comment by ameshkov** [comment]
Ah, I see, you have a root certificate moved to system so HTTPS filtering works for Google Maps. We'll need to test it with the same settings.

Just in case -- try clearing Google Maps cache and data.

**Comment by carlylemiii** [comment]
> Ah, I see, you have a root certificate moved to system so HTTPS filtering works for Google Maps. We'll need to test it with the same settings.

The checkbox for HTTPS filtering for Maps is not checked since 2.11.80 by default wiped out N+-targeting apps. Is HTTPS still be filtered??

> Just in case -- try clearing Google Maps cache and data.

That didn't help, except for some reason Google Maps isn't giving me the different notifications about poor connectivity. It just doesn't populate any search results when searching unless I disabled AG.

**Comment by ameshkov** [comment]
> The checkbox for HTTPS filtering for Maps is not checked since 2.11.80 by default wiped out N+-targeting apps. Is HTTPS still be filtered??

Hm, according to the log HTTPS if filtered. This is another bug then.

**Comment by carlylemiii** [comment]
Yeah, I have HTTPS filtering enabled on the whole, but not for that app. :/

**Comment by ameshkov** [comment]
Try switching it on and off

**Comment by carlylemiii** [comment]
That worked!

**Comment by ameshkov** [comment]
So we have two issues out of this one.

1. Google Maps needs to be added to the default HTTPS whitelist.
2. Smth is wrong with the checkbox.

I guess we'll resolve it in v2.12 as moving certificate to system store is just too rare.

**Comment by carlylemiii** [comment]
> Google Maps needs to be added to the default HTTPS whitelist.

What is the whitelist for, if Nougat (or higher) targeting apps aren't HTTPS-filtering-enabled by default now anyway? Or do you have to maintain a list of those apps and that's what that list is? Asking because I'm generally curious but also curious about my other issue, https://github.com/AdguardTeam/AdguardForAndroid/issues/1817

**Comment by ameshkov** [comment]
> Or do you have to maintain a list of those apps and that's what that list is? Asking because I'm generally curious but also curious about my other issue, #1817

Exactly, we maintain such a list.

**Comment by carlylemiii** [comment]
> Exactly, we maintain such a list.
So if an app is not on your whitelist but it targets Nougat or Oreo, then AdGuard will by default try to filter HTTPS? Sorry, my question was a bit unclear. :) I guess my confusion is because in this original issue, AdGuard knew not to have the checkbox checked for Maps (even if it was not being obeyed) and it wasn't on your whitelist yet.

**Comment by CrescendoFang** [comment]
plus latest Facebook app throwing "can't connect" error, AG 2.12.52n here...

**Comment by carlylemiii** [comment]
@CrescendoFang Facebook doesn't support HTTPS filtering. It's unchecked by default. :) Same with Messenger.
