### ISSUE TITLE
AdGuard Notification Separator/Dot Size Issue on Samsung

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#1826]
AdGuard's separator used in the notification seems to have a sizing issue on this Samsung device as the dot is much bigger than usual.

### Seen on previous Nokia 6
![37931402-38d042bc-3191-11e8-881a-5a2c7f8909d2](https://user-images.githubusercontent.com/36845626/38775698-2ae78df0-40cc-11e8-8a34-c008fe42a03d.png)

### Seen on Samsung Galaxy J7 Pro
![screenshot_20180415-164131](https://user-images.githubusercontent.com/36845626/38775705-66a9a292-40cc-11e8-86c0-cecb147f3c15.png)

### Your environment

* Adguard version: 2.11.80 Beta
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy J7 Pro
* Operating system and version: Android 7.0

**Comment by Revertron** [comment]
It's not a separator that has an issue, it's a font used in notification on Samsung device.

**Comment by planet0** [comment]
> It's not a separator that has an issue, it's a font used in notification on Samsung device.

Is there any potential workaround that AdGuard could do to circumvent this?

**Comment by Revertron** [comment]
> Is there any potential workaround that AdGuard could do to circumvent this?
Just one - use another symbol. Just because of one of the worst device vendors :-/

**Comment by ameshkov** [comment]
&mdash; maybe?

**Comment by ameshkov** [comment]
I'll see to it as I am on Samsung as well.

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/398`

**Comment by planet0** [comment]
Perfect, thank you. 👍 

![screenshot_20180511-120604](https://user-images.githubusercontent.com/36845626/39903101-d636e758-5514-11e8-8605-c73425c857af.jpg)


There is another place where the same separator issue occurs, and that's when tapping on any dot in 'Apps and Statistics'. Doesn't look too bad in this scenario but it might be worth also making the same changes done previously for the sake of consistency.

![screenshot_20180511-120553](https://user-images.githubusercontent.com/36845626/39903105-da495f4c-5514-11e8-9318-09e67cbcf9e4.jpg)

**Comment by ameshkov** [comment]
> but it might be worth also making the same changes done previously for the sake of consistency?

The fix is too ugly and frankly, I'd better avoid replicating it elsewhere :)

**Comment by planet0** [comment]
That's completely understandable, thanks for the notification fix  :)
