### ISSUE TITLE
Moving certificate to the system store does not work on some devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1827]
One complaint:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=72083643

Another one:
https://forum.xda-developers.com/showpost.php?p=76234465&postcount=3088

You'll need to ask users for logs to figure what's wrong.

**Comment by yochananmarqos** [comment]
The reason why it didn't work for the guy on XDA is because he's using Magisk. The system is not mounted r/w. I wrote a Magisk module to move the certificate to the system store attached [here](https://forum.xda-developers.com/showpost.php?p=75835120&postcount=3039).

**Comment by remewer** [comment]
@yochananmarqos Thanks! It worked perfectly. And it worked better than Move Certs.

**Comment by carlylemiii** [comment]
> The reason why it didn't work for the guy on XDA is because he's using Magisk.

I use Magisk... AG moves it fine for me.

**Comment by yochananmarqos** [comment]
@carlylemiii Then you're using something besides Magisk that is allowing /system to be mounted r/w.

**Comment by p00h** [comment]
I can confirm the module is usefull. Xiaomi MI5s, Mokee ROM based on Android 7.1.2. I've installed module and the CA seems to be moved into system storage.
