### ISSUE TITLE
Filtering Log Enable/Disable Button Missing

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#1828]
Hi guys,

I updated the app from 2.10.176 to 2.11.80 RC and observed that the Filtering Log now does not show the enable/disable button on the top-right side of the page. It is now enabled by default without an option to turn it off. Was this intentionally removed or just missed? As enabling the filtering log takes more resources and battery, leaving this always on drains the battery? Correct me if I am wrong.

**My Specs:**

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.1.0 (MHOMIEK) ]

**AdGuard Version**:
- AdGuard for Android 2.11.80 RC

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- No user filter used
- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by vozersky** [comment]
Hello, @Nzzyme ! It actually has zero impact on cpu&battery, we have removed the button on purpose. But since many users are concerned about it, we are going to bring it back :) 
https://github.com/AdguardTeam/AdguardForAndroid/issues/1808

**Comment by Nzzyme** [comment]
Yes, please bring it back. Even though it has zero impact on battery or resources, many users find the need to pause Logging for some time to examine the connection requests because at times there is lot of quick activity in the log that scrolls fast and we are unable to see the requests. I checked on the change log and did not see that this was removed. Request you to bring this back.

**Comment by ameshkov** [comment]
Hm, pausing is a bit different angle, I'll think about it.

**Comment by Nzzyme** [comment]
It need not be pausing. The original toggle switch is sufficient. Thank you
