### ISSUE TITLE
BOOT_COMPLETED Intent is not received at “Restart” or “Reboot”

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#183]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=44457292

We've missed to add one more intent:
```
<action android:name="android.intent.action.QUICKBOOT_POWERON" />
```

More details:
http://stackoverflow.com/questions/24882861/android-intent-action-boot-completed-intent-is-not-received-at-restart-or-reb

**Comment by ameshkov** [comment]
Done

**Comment by ameshkov** [comment]
Does not work on MIUI

**Comment by ameshkov** [comment]
According to that:
http://stackoverflow.com/questions/30124108/boot-receiver-doesnt-work

MIUI uses another action:
```
<action android:name="android.intent.action.REBOOT"/>
```

**Comment by ameshkov** [comment]
Nope, again, that's wrong.

Quote from stackoverflow:
```
MIUI has a a built-in Security app. In the Security app there is a 'Startup' section, where the user can configure which app can and which app can't run on startup. Your application is disabled default.
```

**Comment by ameshkov** [comment]
Still not fixed:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45183206

**Comment by Joss** [comment]
Full log from HTC One M8 Android 6.0 in ZTS-620-56182 ticket.

**Comment by ameshkov** [comment]
Similar issues with HTC:
http://stackoverflow.com/questions/9525907/htcs-fast-boot-is-not-broadcasting-boot-completed-intent-nor-wiping-intents-f
http://stackoverflow.com/questions/10411731/how-to-get-boot-complete-intent-in-htc-when-i-use-poweroff-for-reboot
http://stackoverflow.com/questions/27732650/htc-desire-s-broadcasts-boot-completed-after-enabling-secure-credentials

If what we've done is not enough, then we have the following options:
1. Disable fast boot
2. Еnable secure credentials (Settings -> Security -> tick "Use secure credentials")

**Comment by ameshkov** [comment]
Working solution (finally):
```
        <receiver android:enabled="true" android:name=".receivers.BootUpReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
```

It has started working after I have removed android:permission attribute.

**Comment by rahulsamaddar** [comment]
Device: OnePlus 5T
I have added the permission 
   ` <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>`
Manifest Entry:- 
   ```
 <receiver
            android:name=".BootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
```

MyBootReceiver class
```
public class BootReceiver extends BroadcastReceiver {


    @Override
    public void onReceive(Context context, Intent intent) {
        Log.d("boot_boot","Received BOOT COMPLETED");
        if (UserUtil.isUserRegistered(context)) {
            ChatService.startService(context);
            MetaDataUpdaterBroadcast.scheduleAlarmManager_ForUpdatingMetadata(context);
        }
    }
}
```
Still No luck:
Logcat data:-
01-23 16:29:43.811 3466-5236/? E/NetworkScheduler.TED: Couldn't start service: Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=net.one97.paytm/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }
01-23 16:29:43.812 3466-5312/? E/NetworkScheduler: Unknown result code received: 4
