### ISSUE TITLE
Feature Request: Fallback DNS

### ISSUE THREAD

**Issue by bayazidbh** [AdguardTeam/AdguardForAndroid#1832]
Would it be possible to implement a fallback DNS option on the app? The AdGuard DNS server near Indonesia (the Singapore server, I believe?) is rather unstable, sometimes going down and other times being slow. So perhaps a fallback DNS option/setting of a sort? The latest version of Simple DNSCrypt has that option, so maybe something similar where we can input or choose a DNS server to use as a fallback (and use the device/ISP's default DNS if left blank or unchosen) if the chosen DNS server is down or slow, let's say if it didn't respond for more than a few ms. From there, there's a choice of retrying the main DNS server every time or retrying periodically.

It's important for me since I make my parents use AdGuard for Android with AdGuard DNS selected as part of a protection from various malware. I'd like to just set AdGuard DNS as main DNS server, and then either Cisco OpenDNS or Cloudflare DNS as a fallback server - just so they can always connect and protect with no bother and effort.

**Comment by CrescendoFang** [comment]
+1 to this, better than having to manually re-select DNS...

**Comment by TPS** [comment]
Even Windows has an option for a fallback DNS server _lists_, so, preferably, _any_ number of backup servers would be appreciated.

**Comment by ameshkov** [comment]
When you set up a custom DNS server, you can enter a primary and a secondary server.

However, this is not yet possible for the DNSCrypt servers and this needs to be improved indeed.

**Comment by TPS** [comment]
`pref.dns.fallback` now exists under _Low Level Settings_, yet it's unclear whether it supports any encrypted DNS or lists, & needs to exposed on _Select DNS Server_.

**Comment by TPS** [comment]
@ameshkov Why <kbd>Closed</kbd>, please?
