### ISSUE TITLE
WhatsApp Chat backup doesn't detect Wi-Fi only with AdGuard VPN

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#1834]
WhatsApp can never backup chats with AdGuard VPN when set to backup via Wi-Fi only. I found a work around which is to manually change it to back up over 'Wi-Fi or cellular' which then instantly works and I can change it back.

Tried with different smartphones and different home modems with and without AdGuard DNS setup or Android installed, seems to be AdGuard Android related, perhaps WhatsApp can't tell Wi-Fi with the VPN.

### Steps to reproduce
1. Set up Chat backup to Daily, Back up over Wi-Fi only in WhatsApp
2. Wait overnight, or until an automatic back up

### Expected behavior
WhatsApp backs up without user intervention

### Actual behavior
WhatsApp is stuck waiting for Wi-Fi

<details><summary>Backup Paused Notification:</summary>

![image](https://user-images.githubusercontent.com/36845626/39076522-3eb3f036-453f-11e8-870b-a10073be0ecb.png)

</details>

<details><summary>Backup Paused in App:</summary>

![image](https://user-images.githubusercontent.com/36845626/39076575-70fbf61a-453f-11e8-9a0c-a3d78b774933.png)

</details>

<details><summary>Workaround allowing Backup to continue:</summary>

![image](https://user-images.githubusercontent.com/36845626/39076579-78c4566c-453f-11e8-9c4e-874b693b553c.png)

</details>

### Your environment

* AdGuard version: 2.11.81
* AdGuard filtering mode: VPN
* Device model: Samsung Galaxy J7 Pro
* Operating system and version: Android 7.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Samsung's Device Management Pre-installed

**Comment by ameshkov** [comment]
This one must be a Whatsapp bug

**Comment by TPS** [comment]
I also receive this 1, once in a while.  Problem is, unpredictability & not around @ 2 to 5 am (randomly) to watch it.…

**Comment by planet0** [comment]
> This one must be a Whatsapp bug
You're right, it happened without AdGuard.

**Comment by TPS** [comment]
Wow, s/he took this hard!  Wiped GitHub account & everything! 😲

**Comment by vozersky** [comment]
@zebrum check it on your device as well pls

**Comment by zebrum** [comment]
reproduced.

**Comment by vozersky** [comment]
u sure? I was getting this error even without Adguard
need log\har then, I guess

**Comment by zebrum** [comment]
I'll try tonight without AdGuard to be sure. And then collect logs

**Comment by TPS** [comment]
A further data point: doing any kind of no-op (like toggling DNS-blocking Off, then On) that forces AG to restart, allows WhatsUp to detect wifi & complete the backup (even when AG's always-on VPN).

**Comment by ameshkov** [comment]
Guys, I am almost sure this is not our bug
