### ISSUE TITLE
Include Option to Block IP Address

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#1835]
Hi guys,

This enhancement request is the result of Issue #14799 found here:

https://github.com/AdguardTeam/AdguardFilters/issues/14799

Sometimes, we see the IP address in the Filtering Log instead of domain names that we would like to block. However, tapping on Block and then selecting the regular options does not block the IP address.

The following rule format blocks the IP address

xxx.xxx.xxx.xxx$network

That is,  IP address$network

Example: `42.62.94.2$network`

Therefore, for IP addresses, can you add the above as another option on the "Adding a rule" page after the user taps Block.

**Screenshot**: 
http://image.ibb.co/mrFabx/Screenshot_20180421162940.jpg
http://image.ibb.co/jcNA9H/Screenshot_20180421163001.jpg

### Expected behavior
Should be able to block the IP addresses seen in the Filtering Log via the "Options" seen in Filtering Log

### Actual behavior
Unable to block the IP address with the regular rule

`||42.62.94.2$app=com.xiaomi.midrop`

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.3.0 (MHOMIFA) ]

**AdGuard Version**:
- AdGuard for Android 2.11.81

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by TPS** [comment]
Similar to this: Is it possible to block _all_ "naked" IP URL requests, & then whitelist the 1s I choose?  I'm starting to see more & more sites serve up ads using random IPs, bypassing DNS (& most adblocking filters) outright.

**Comment by ameshkov** [comment]
> Similar to this: Is it possible to block all "naked" IP URL requests, & then whitelist the 1s I choose?

Nope, not similar, this is just about a filtering log bug and blocking on the IP-level.

**Comment by ameshkov** [comment]
This issue is a part of a bigger task:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1730#issuecomment-384946631
