### ISSUE TITLE
Domain Redirects Even Though Added in Malware List

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#1836]
When browsing some sites or if you click on an ad/pop-up (which was not blocked by AG), the ad/pop-up redirects and hops multiple domains quickly to take you to some target page. However, if one of the domain was included in the Malware/Phishing list, it still quickly bypasses that and continues to redirect to another page. 

The expected behavior is that as soon as the domain is encountered, it should be blocked and the warning page should be displayed. However, I can confirm that this does not happen.

**Example**: 

The domain "calcch.com" is added to the malware/phishing list as seen here: http://prntscr.com/j8768r

However, when opening the site "musicforyou.ga" (in Firefox) at times redirects via the following domains seen here: http://image.ibb.co/e3amic/Screenshot_20180421170700.jpg

You many have to reload the site once to see the redirects. As you can see from the above screenshot, the domain "secure.calcch.com" was not not blocked by AG and it continued to proceed to the next domain "leadzuaf.com".

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.3.0 (MHOMIFA) ]

**AdGuard Version**:
- AdGuard for Android 2.11.81

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/CoreLibs #216](https://github.com/AdguardTeam/CoreLibs/issues/216) via [**ZenHub**](https://www.zenhub.com/)
