### ISSUE TITLE
AdGuard still won't start on boot on Nexus 6P

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1837]
### Actual behavior

The customer has Nexus 6P on Android 8.1.0, AdGuard added to exceptions, updated to 2.11, pref.boot.startup.delay is set to 10 seconds.

### Logs
https://uploads.adguard.com/juwk8.zip (reproduced at  8:24 pm)

### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: "proxyMode" : false
* Device model: manufacturer=**Huawei** model=**Nexus 6P** brand=google version=8.1.0 security_patch=2018-04-01
* Operating system and version 8.1.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? none

**Comment by nkartyshov** [comment]
@vozersky I cannot see problem with boot on startup in the log files. 
Adguard received BOOT_COMPLETED events at 13.26 and 20.25 clock and after that launched the protection.

Maybe we were killed by the android in 8.23, since there is nothing in the logs in this time interval.

**Comment by vozersky** [comment]
can't repro
