### ISSUE TITLE
Please soon let Traditional Chinese Web Reporting Tool be online.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1838]
For Taiwanese users, now web reporting tool leads to English website in AG for Android v2.11.81.

Long~long time ago, Traditional Chinese Web Reporting Tool was very early 100% finished.
Please give Traditional Chinese Web Reporting Tool to Taiwanese users from next mirror version.

I also noted that you started to not anew update languages files in beta version, even release version.
I don't request every time for nightly / beta version.
At least, you should update languages files every time of release version.

Traditional Chinese for critical.xliff file of website is all finished.
The rate of progress for Traditional Chinese:
Total website: 81.3%
Web reporting tool: 100%

Please let Traditional Chinese website and web reporting tool be online.

Thanks a lot!

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #152](https://github.com/AdguardTeam/ReportsWebApp/issues/152) via [**ZenHub**](https://www.zenhub.com/)
