### ISSUE TITLE
Please add more hosts files for DNS filtering.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1839]
As what we know, AdGuard SDN filter is for DNS filtering.
So please also add these filters.

1hosts.cf:
http://1hosts.cf/

CoinBlockerLists:
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts

CoinBlockerLists (optional):
https://zerodot1.github.io/CoinBlockerLists/hosts_optional
(https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt)

CoinMiner:
https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt

NoCoin (adblock for HTTPS filtering):
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt

NoCoin (hosts file for DNS filtering):
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
Well, choose one kind of NoCoin.

Hexxium Creations Threat List:
https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt

Piperun's iplogger filter: (for HTTPS filtering)
https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist

Ransomware Tracker Domain Blocklist:
(It's domain format. Need to convert to hosts file or basic adblock rule syntax.)
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt

AdZHosts:
https://adzhosts.fr/hosts/AdZGuardFilter.txt

B/R

**Comment by yochananmarqos** [comment]
I believe a least a few of those are already integrated.

Since this is an AdGuard DNS issue, it should be posted [there](https://github.com/AdguardTeam/AdguardDNS/issues). I recommend doing that and closing this issue.

**Comment by lancelot-moon** [comment]
You know nothing.
AdGuard DNS is AdGuard DNS.
These are for local DNS filtering, understand?

**Comment by yochananmarqos** [comment]
You're posting an AdGuard DNS issue in the AdGuardForAndroid area. I'm suggesting you post it in the proper place so it will receive proper attention. No need to be rude.

**Comment by lancelot-moon** [comment]
As what you say, we don't need SDN filter in ad blocker of AdGuard for Android.
In your thought, it's about AdGuard DNS.

**Comment by yochananmarqos** [comment]
Your request stated you wanted to add host files for DNS filtering. AdGuard for Android does not filter DNS requests unless you use AdGuard DNS with it. Also, AdGuard for Android does not use host files, it uses block lists using regex. You can see the lists in used [here](https://github.com/AdguardTeam/AdguardFilters).

**Comment by lancelot-moon** [comment]
Kid, go to your AdGuard app.
You'll find DNS setting.
AdGuard for Android also does local DNS filtering.
Oh my God, you really don't know AdGuard.
Just like a kid who argues without normal reasons.

**Comment by yochananmarqos** [comment]
Good grief, you just said the same thing I did--except you don't know how do communicate without being condescending and rude. I'm done, later.

**Comment by lancelot-moon** [comment]
You are simply rude and don't know how to communicate with people.
You just think you're right, but you're wrong actually.
Go to check your AdGuard, a ignorant guy.

**Comment by ameshkov** [comment]
1.  AG for Android does not support hosts files syntax yet.
2. I have filed a feature request for the hosts files syntax support: https://github.com/AdguardTeam/AdguardForAndroid/issues/1851
3. This issue along with #1818 was linked there.
