### ISSUE TITLE
Adguard is broken by IMDB app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#184]
http://forum.adguard.com/showthread.php?7640-AdGuard-pwned-by-IMDB

**Comment by TPS** [comment]
Erm, IMD***B***.…

**Comment by ameshkov** [comment]
Ops:)

**Comment by TPS** [comment]
@ameshkov Just reading through the original linked bug report, this title should be more like "IMDB app & AdGuard break each other" & seems to be somewhat how #50 was.  The reported workaround also doesn't filter the advertisements in the IMDB app, I think.

**Comment by ameshkov** [comment]
Yep, you're right. I have renamed it to "Adguard is broken to show that the bug is important.

**Comment by ameshkov** [comment]
Works good in debug build. Either it is fixed in IMDB 6.0.5, or in our app.
