### ISSUE TITLE
AdGuard misbehaves when it's set as always-on and it receives a connectivity change event

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1844]
### Steps to reproduce

1. Install the latest AdGuard nightly (2.12.1)
2. Ensure that `pref.vpn.disable.reconfigure` is unchecked
3. Set AG as an "always-on" VPN
4. Trigger connectivity change (disable or enable wi-fi for instance)

### Expected behavior
AG is restarted successfully.

### Actual behavior
VPN fails to start.

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/397`

**Comment by TPS** [comment]
Now #3327
