### ISSUE TITLE
Nightly: pref.proxy.block.ipv6 does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1845]
### Steps to reproduce

1. Go to settings -> advanced -> low-level
2. Check `pref.proxy.block.ipv6`
3. Try opening `ipv6.google.com`

### Expected behavior
It does not work

### Actual behavior
It works

### Your environment

* Adguard version: 2.12.4
* Adguard filtering mode: Proxy (auto)

**Comment by admitrevskiy** [comment]
In the latest AdGuard (2.12.10) it works fine.
@ameshkov send me logs plz.

**Comment by ameshkov** [comment]
It seems that the problem is not in ipv6.

For some reason, DNS filtering does not work in the proxy mode when the user is on Wi-Fi:

> ipv6.google.com is being blocked now but the real issue is that the dnscrypt servers only work when connected to mobile network. on wifi the default network provider's servers are being used. it only happens on the last two nightly builds. beta 2.11.81 doesn't have this issue
