### ISSUE TITLE
AdGuard disables after network change event

### ISSUE THREAD

**Issue by sviperz** [AdguardTeam/AdguardForAndroid#1846]
After switching the network from WiFi/mobile to mobile/WiFi AdGuard stops working despite the button on the main screen remains green. Also, the key sign in the status bar representing active VPN connection is absent.

The bug isn't reproducible all the time, but tends to appear pretty often.

Please check the logs attached and let me know if there is anything I can help you with.
[adguard_logs_2.12.4_2904_2155.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1959069/adguard_logs_2.12.4_2904_2155.zip)

AG version: 2.12.4 Nightly
AG filtering mode: VPN
Device: Google Pixel 2016
OS: Android 8.1.0
No root

**Comment by ameshkov** [comment]
Resolved in `/ANDROID/repos/adguard-android/pull-requests/401`
