### ISSUE TITLE
It seems that the whitelist doesn't work in AdGuard v2.12.4η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1848]
User filter for HTTPS filtering.
Whitelist for DNS filtering.
Right?

**I disabled all ad blockers.**
I added www.google-analytics.com in the whitelist.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/5FK2yev.png)
</details><br/>

I enabled DNS setting for DNS filtering.
**We know that SDN filter will work in the background, and there is the rule, ||google-analytics.com^, in the SDN filter.**
But I already added www.google-analytics.com in the whitelist.
Why is www.google-analytics.com still blocked?
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/oTO0CMN.png)

![image](https://i.imgur.com/TyEcqTs.png)
</details><br/>

We can't block analytics.js under www.google-analytics.com, otherwise some websites will be broken.
EX: Line Today
https://github.com/AdguardTeam/AdguardFilters/issues/14202#issuecomment-385164860
We should add the rule, @@||www.google-analytics.com/analytics.js$third-party, in the Spyware filter and add, @@||www.google-analytics.com^, in the SDN filter.

Thanks.

**Comment by ameshkov** [comment]
Hm, whitelist does not work that way at least at the moment. Unblock it via the filtering log instead.

Whitelist is for websites, not for ordinary requests.
