### ISSUE TITLE
Вылет Kate mobile с ошибкой

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1849]
Спокойно сидел в интернете в приложении Kate mobile. Вдруг Kate вылетел. Зашел заново и ничего, не обновляется, через браузер тоже не работает, хотя на компе все норм. Думаю ладно, включил 4g и опять не грузит ничего, даже в браузере. Дело явно было в Adguard. Я отправил в тех.поддержку Kate mobile логи и они сказали, что судя по логам дело в Adguard. Вот вам логи Kate и выгрузка из Adguard. Adguard версии 2.10.176, Nexus 5, android 4.4.4, фильтры по-умолчанию, HTTP,HTTPS, качественная фильтрация. http://transfiles.ru/2jd1y

**Comment by ameshkov** [comment]
> Adguard версии 2.10.176

А чего не 2.11?

**Comment by ameshkov** [comment]
В логах жесть какая-то, такого не может в обычной ситуации происходить.

Как будто сеть раскочевряжило полностью. Но краш кстати не наш, а их (хотя с такой разбитой сетью я хз что могло повлиять).

**Comment by ministr91** [comment]
@ameshkov, неужели ничего нельзя сделать? Может по логам можно как-то исправить проблему?

**Comment by ministr91** [comment]
Да и почему такая проблема? Дело даже не в Kate, а в том, что интернет 4g и вай фай не работал у меня с включенным Adguard

**Comment by ameshkov** [comment]
Так повторяется проблема?

**Comment by ministr91** [comment]
нет. Эта проблема с кейтом первый раз была, но вот проблема с тем, что вдруг исчезает интернет и не работает как вай фай и 4g бывает. Где-то раз в месяц примерно.

**Comment by ameshkov** [comment]
Вполне возможно что прошивочная, или реально сеть пропала. По этому логу там вообще сеть в ненормальном состоянии, но что его вызвало там не видать

**Comment by ministr91** [comment]
@ameshkov, а если в настройках выставить уровень логгирования - записывать всё, то можно будет отследить в чем проблема?

**Comment by ameshkov** [comment]
Можно попытаться
