### ISSUE TITLE
Multiple feature requests for AdGuard for Android (ru)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1850]
1) При сконфигурированном прокси, добавить на HOME страничку AdGuard кнопку включения отключения прокси, к примеру под круглой зеленой/серой кнопкой "Protection is enabled/disabled". Это реально упростит доступ к этой функции.
2) При активированном прокси не выводить в шторку дополнительное постоянное сообщение о том что трафик через прокси, а добавить эту информацию к и так неубираемо висящему уведомлению самого ADguard "Blocking ads and trackers". Это сэкономит место в шторке и в целом будет гармоничнее.
3) Пожалуй САМОЕ главное. Возможно ли добавить в "Apps Management" в персональные настройки приложений работающих через ADGuard в раздел GENERAL или отдельный раздел чекбокс USE PROXY. Чтобы через активированный прокси направлялись только те приложения которые имеют на это разрешение.

reported by user 1772038

**Comment by vozersky** [comment]
1 case = 1 issue, pls

По первому реквесту: Сейчас управление подразумевается через уведомление. На home кнопка добавлена вряд-ли будет, но возможно вынесем прокси в side меню.
По второму реквесту: объединять уведомления не планируется, это не совсем просто, на разных девайсах будет по-разному.
По третьему реквесту, идея прекрасная, но сложная :) давайте оставим открытым #1776

**Comment by ivan046** [comment]
Спасибо за ответ.  Ждем эту фичу :)
