### ISSUE TITLE
Add custom hosts files support to the DNS filtering module

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1851]
Generally, it should work just like it works in the iOS version.

1. Users should be able to add custom hosts files or adblock subscriptions.
2. Custom DNS filtering rules need to be separated from the user filter.
3. We may provide a list with some popular subscriptions to choose from.

Some ideas for the list:

* https://github.com/AdguardTeam/AdguardForAndroid/issues/1839
* https://github.com/AdguardTeam/AdguardForAndroid/issues/1818

**Comment by LewisLebentz** [comment]
So it's not currently possibly to add any other lists that block DNS requests?

I thought it would be possible as the iOS app can do it, and all the competitors like Blokada etc.?

**Comment by TPS** [comment]
Just to clarify, when 1 adds a custom filter(list), those filters aren't used for DNS-blocking (like the user filter(list) can be) if that's enabled⁉️

**Comment by ameshkov** [comment]
@admitrevskiy 

If DNS filtering is enabled, but no custom DNS upstream is selected, we should honor user's DNS Privacy settings: https://developer.android.com/about/versions/pie/android-9.0-changes-28#dns-privacy

**Comment by ameshkov** [comment]
Issues with the current build:

1. "Filters" item must be disabled when "DNS requests blocking" is unchecked
2. "Filters" --> "DNS Filters"
3. Subtext: `6 filters enabled` or `No filters enabled`

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Please, check this issue after https://github.com/AdguardTeam/AdguardForAndroid/issues/2800 https://github.com/AdguardTeam/AdguardForAndroid/issues/2803 and https://github.com/AdguardTeam/AdguardForAndroid/issues/2798 will be resolved
-Reinstall AG
-Examine new screens for DNS Filters (`Settings` –> `DNS Filtering`)
-Try to add and remove custom DNS Filters (with regular and host filtering rules)
-Try to add invalid filter (insert wrong url into `Add new filter` dialog)
-Examine DNS filtering
