### ISSUE TITLE
com.google.android.apps.photos

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1853]
@adguard-bot commented on [Mon Apr 30 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15515)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.google.android.apps.photos&hl=en](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.photos%26hl%3Den)
### Comment
> При включении Adguard для приложения Google Photo фотографии не синхронизируются через Wi-Fi. Только принудительное выключение Adguard для Google Photo решает проблему. Ограничений нет, фильтрация по https отсутствует. Проблема остаётся.
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/AooQOxI.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1
AdGuard version: | 2.11.81
AdGuard mode: | VPN
Filtering quality: | High-speed
HTTPS filtering: | enabled
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Mobile Ads,<br>Annoyances

---

@Eugene-Savenko commented on [Mon Apr 30 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15515#issuecomment-385351945)

debug is here - 1631686

---

@Alex-302 commented on [Thu May 03 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15515#issuecomment-386385757)

У меня синхронизиреутся.
@vozersky глянь у себя.

---

@vozersky commented on [Thu May 03 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15515#issuecomment-386394494)

повторилось (именно на 8.1)

**Comment by ameshkov** [comment]
Это жу дубликат #1587 и оно должно было быть исправлено.
