### ISSUE TITLE
Amazon version shows "App Update Required — [Quit] [Update]" 😱

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1854]
@AdguardTeam This is what I see today, from just a few hours ago.:
![Screenshot of Error](https://user-images.githubusercontent.com/185902/39659488-00f1e7a4-4ff7-11e8-9a8d-de97b0c3ac5e.png)

Reinstalling from Amazon didn't help. It still _mostly_ works, with a few major issues:
- My apps don't update from Google, whether using Play or Yalp Store.
- I can't access any screens w/in AG itself, as that popup blocks everything in 10 seconds or so, which precludes sending bug reports or toggling log levels.

### Steps to reproduce

1. Just open AG & wait a few seconds
2. <kbd>Quit</kbd> does the obvious
3. <kbd>Update</kbd> brings up the _non-ß_ AG listing on Amazon Appstore

### Expected behavior

This should _never_ come up in the Amazon version, either ß or regular release, but should be handled by the Appstore.  Even for website version, it seems quite heavy-handed, so maybe an option to <kbd>Ignore for _**configurable**_ hours</kbd>.

### Actual behavior

As above.

Screenshot: as above.

### Customer ID 

Unable to send, as detailed.

### Your environment

* Adguard version: 2.11.81, Amazon ß
* Adguard filtering mode: VPN 
* Device model: Nextbit Robin
* Operating system and version: Android 7.1.1
* Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No (other) VPNs, & just CleanMaster (for cleaner or AV-type apps)

**Comment by TPS** [comment]
Nm, I think I figured it out 😳: I was tweaking my trusted system certs per https://security.googleblog.com/2018/03/distrust-of-symantec-pki-immediate.html .  It turns out both Google & Amazon _still_ have deep-seated TLS certs signed by Symantec-&-Co, which knocks everything off-kilter when that's distrusted.  When I re-enabled & waited a few, everything realigned.

Who knew?  The first deadlines passed _last_ month, so I thought @ least Google'd get their act together by now.  Also, I've a hunch that popup _isn't_ native to AG, so I should probably complain to Amazon about that.

Sorry for the spam. :bow:

**Comment by ameshkov** [comment]
Yeah, the popup is not native indeed :)
