### ISSUE TITLE
Do not show 7+ HTTPS filtering warning when the certificate is in the system store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1855]
Relevant discussion:
https://forum.xda-developers.com/showpost.php?p=76423776&postcount=3143

### Steps to reproduce

1. Move the certificate to the system store
2. Go to "Apps management"
3. Find an app there
4. Uncheck the HTTPS filtering flag
5. Check it again

### Expected behavior
The checkbox value changes with no questions asked

### Actual behavior
AdGuard shows the HTTPS filtering warning despite the certificate is in the system store.

### Your environment

* Adguard version: 2.12.4 nightly
* Adguard filtering mode: VPN
* Operating system and version (e.g. Android 7.1.2): any Android 7+
* Rooted

**Comment by admitrevskiy** [comment]
Looks like this bug was fixed here: https://github.com/AdguardTeam/AdguardForAndroid/issues/1825
This branch was merged after last nightly release

**Comment by ianmacd** [comment]
When is the next nightly coming? Perhaps you should rename it 'weekly'. :-)

Just kidding. You guys do fantastic work. I'm just looking forward to having the fix.

**Comment by ameshkov** [comment]
This week I guess :)
