### ISSUE TITLE
AdGuard is not capturing the mobile data usage correctly 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1856]
The data usage is being assigned to Wi-Fi despite the bug https://github.com/AdguardTeam/AdguardForAndroid/issues/1665 is closed. The only workaround I found is manually disabling and re-enabling AdGuard or restarting the device. The thing is that for some reason AdGuard believes that I'm still connected to Wi-Fi and assigns traffic stats to the Wi-Fi tab instead of the mobile tab.

### Steps to reproduce

1. I started connected to Wi-Fi and opened Reddit and loaded a few pages. AdGuard filtered it and showed it correctly on the Wi-Fi tab.
2. Then I turned off Wi-Fi and switched to mobile network. I opened Reddit again and used it a bit. As you can see in the screenshots below no data is shown in the mobile tab. All of it is assigned to the Wi-Fi tab.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/39687524-77c85264-51d7-11e8-93f7-09272f881b70.png)

</details>

### Expected behavior

Stats are correctly assigned based on the type of connection

### Actual behavior

AdGuard does not understand that the connection has changed which distorts data usage stats
### Customer ID 
1549733,  w/ logs

### Your environment

* Adguard version: 2.12.4
* Adguard filtering mode: "proxyMode" : true, Manual: false
* Device model: ONEPLUS A3003
* Operating system and version: 8.1.0
* Rooted or not? yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by ameshkov** [comment]
@admitrevskiy examine the logs, search for the connectivity change events there

**Comment by admitrevskiy** [comment]
Resolved

Testing instructions:
1. Reinstall AG
2. Connect to WiFi and enable protection
3. Open N sites in Chrome
4. Change connection to mobile network
5. Open N sites in Chrome
6. Go to `Apps Management –> Chrome`

Expected result:
Wi-Fi and mobile data should be approximately equal
