### ISSUE TITLE
Some apps not found by Apps 

### ISSUE THREAD

**Issue by ianmacd** [AdguardTeam/AdguardForAndroid#1859]
### Steps to reproduce

1. Install https://play.google.com/store/apps/details?id=com.gmail.heagoo.apkeditor.pro
2. Look for 'APK Editor Pro' (or any substring of this) under App Management in AdGuard.
3.
4.

### Expected behavior
APK Editor Pro should be found and listed.

### Actual behavior
APK Editor Pro is not found in the list.

At first, I thought it was because AdGuard was performing analysis and determining that this app cannot produce network traffic, but other apps that create no traffic CAN be searched for and found.

### Customer ID 
Sorry, no auto-reply e-mail with customer ID was received by me.

### Your environment
* Adguard version: 2.12.4
* Adguard filtering mode: Proxy auto
* Device model: Galaxy S9+
* Operating system and version: Android 8.0
* Rooted

**Comment by ameshkov** [comment]
@admitrevskiy the app has `full network access` so it must be listed in the apps management:
https://uploads.adguard.com/up04_cuc8z_APK_Editor_Pro_-_Apps_on_Google_Play_.png

**Comment by ianmacd** [comment]
Ah, OK, so it is strange that it is not listed. Perhaps there are other apps that are not listed, too.

If you want to test, APK Editor Pro is a paid app, but there is also a free version. I don't know if the bug occurs with the free version, however.

**Comment by admitrevskiy** [comment]
@ianmacd hi!
Can you tell me plz, which else apps are not listed?

**Comment by TPS** [comment]
@admitrevskiy Just to be fair, the above is a very difficult question to answer, as A/B checking is very involved, AG vs Android OS.  Maybe in debug versions, we can have a toggle that lists **ALL** installed (not just detected network) apps, so we're better able to answer?

**Comment by admitrevskiy** [comment]
`APK Editor Pro` doesn't has `full network access` as it marked on Google Play, it's very strange.
However,  free `APK Editor` has network access and listed as well.

**Comment by vozersky** [comment]
Ok, so if this app doesn't really have network access, then we can go ahead and close this issue?

I'm just confused by this statement: 
> but other apps that create no traffic CAN be searched for and found.

@ianmacd could you please tell me the names of these apps? It is not supposed to work this way.

**Comment by TPS** [comment]
Is it possible we could get the debug applist, as requested above?
