### ISSUE TITLE
Downloads are broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#186]
Starting from this comment:
https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-152739139

> I'm still having GPlay (& presumably, Appstore) updating & downloading problems in .260 VPN, but not in .261 proxy. Help! I'm having to disconnect AG & reset wifi connection to make these work. 
> 
> Straight downloads don't work, either: Try, e.g., http://m.costco.com/wcsstore/CostcoUSBCCatalogAssetStore/Attachment/Kitchen_Install_Requirements.pdf & then checking in the Downloads app/window. It'll show permanently "Queued" but will never resume, but must be deleted & redownloaded when AG isn't running. Quite irritating!

**Comment by TPS** [comment]
Thanks! I'll continue here when I've further details, like a logcat. ☺

**Comment by TPS** [comment]
Will test this in new beta & report back.

**Comment by TPS** [comment]
Still having this issue (both with GPlay & http://m.costco.com/wcsstore/CostcoUSBCCatalogAssetStore/Attachment/Kitchen_Install_Requirements.pdf) in beta 2.1.319 released recently.… :disappointed:

**Comment by ameshkov** [comment]
And what about logcat?

**Comment by TPS** [comment]
I should be setup by this upcoming week for _all_ my pending logcat issues.…  Stay tuned! :radio::wink:

**Comment by TPS** [comment]
Still setting up the laptop (having migration issues.…  who knew moving over from a 6-year old laptop would be so hard?!), but this issue with GPlay seems to have disappeared since around the time of the last APK update via Amazon, so, good job, team! :fireworks: :smile:

**Comment by ameshkov** [comment]
Heh, weird:) Let's wait a couple of days and close this issue if it does not reappear.

**Comment by TPS** [comment]
Well, it's broken again for me since around the last release. :confounded:  Here's a silly thought: Change something _non sequitur_, like #203, & do a new release; I bet I'll be reporting back that it's fixed again! :stuck_out_tongue:

**Comment by ameshkov** [comment]
And what about laptop? Have you set it up?

**Comment by ameshkov** [comment]
@TPS any news on this issue?

**Comment by TPS** [comment]
@ameshkov I can _get_ news: my laptop has been setup (even did a test with that script a while back!), but I've been waiting for all the HTTPS-filtering furor to die down, &, IRL, things are very busy.

**Comment by TPS** [comment]
Just filed https://kb.adguard.com/index.php?/Tickets/Ticket/View/GUN-991-62891.…  Will try to file logcat (after replicating) after work in several hours.

**Comment by ameshkov** [comment]
I need to know a bit more:

1. Which file have you tried to download?
2. When exactly?
3. How did it look like?

**Comment by TPS** [comment]
1. https://www.aza.org/uploadedFiles/Education/Kids_and_Families/Special_Admissions_Program/Reciprocity%20Chart%202015y.pdf
2. Within 5 to 10 mins of sending above log
3. Download arrow appears in notification bar for 2 or 3 sec, & then disappears.  When opening stock download app, it just says "not downloaded" as error.

Solved by disconnecting VPN.

Logcat in a couple hours or so.…

**Comment by TPS** [comment]
_(Just FYI, a tech will come by to fix my 'Net connection this week, so I hope to get a stable connection for more than 5 min at a time soon to do this logcat!)_

Just a thought: has any1 implemented anything like #339 as a _filter_ recently?

**Comment by ameshkov** [comment]
> Just a thought: has any1 implemented anything like #339 as a filter recently?

Nope. If we were sure it is for tracking purposes only, we'd added it to the "spyware filter".

**Comment by TPS** [comment]
Now I'm online again, even though it took a lightning storm blowing out my modem to convince my internet company to send out a tech.

Since then, I don't have the issue, but now @evgeniy-ADG [reports the GPlay end of this](https://github.com/AdguardTeam/AdguardForAndroid/issues/549), so I've referred here.

**Comment by TPS** [comment]
Since last ß, this broke again for me, but today's ß fixed it again.  I'll wait 'til next ß to officially determine it so, though. 😉

**Comment by TPS** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/549#issuecomment-231779176

**Comment by TPS** [comment]
@ameshkov Re: https://github.com/AdguardTeam/AdguardForAndroid/issues/597#issuecomment-233296349 onwards:

This re-presented itself this morning (& I sent an HTTP-request report, [as asked-for](https://github.com/AdguardTeam/AdguardForAndroid/issues/549#issuecomment-232002277)), but, reading through https://code.google.com/p/android/issues/detail?id=33666, I don't quite see how _this_ relates to _that_, in my experience.  I've _always_ had DNS filtering on, & configured custom DNS as soon as the option's available to me.  I'm still leaning toward a filtering incompatibility, @ least as starting cause, with a related Android bug, perhaps, as the root.

Also, can this & #549 be renamed a little to differentiate from #597, if you all are going to maintain all 3?  My gut tells me they're all the same _root_ problem, but that hasn't been _established_.

**Comment by TPS** [comment]
Also, https://code.google.com/p/android/issues/detail?id=33666 refers to when wifi interface is disabled, but VPN allows data, anyway.  AFAICT, that's _never_ been how AG operated, & most of the problem I was trying to solve w/ #520.

**Comment by ameshkov** [comment]
> This re-presented itself this morning (& I sent an HTTP-request report, as asked-for), but, reading through

Could you please tell me the customer ID (you should get it in an autoreply email)

**Comment by ameshkov** [comment]
> I don't quite see how this relates to that

It's just Android behaviour is the same in this and that cases. Yeah, bug description is different, but I bet there is a link:)

**Comment by TPS** [comment]
My ID = 1122984.

**Comment by TPS** [comment]
Per https://github.com/AdguardTeam/AdguardForAndroid/issues/549#issuecomment-233957307, since I just updated 2 apps _w/o_ disabling AG, I've sent an HTTP-request log in hopes it might be useful.

**Comment by ameshkov** [comment]
@TPS this log won't help. I guess we need to examine the system log.
There should be a record from DownloadManager, something like that:
`DownloadManager(13488): Aborting request for download 430: no network connection available`

**Comment by TPS** [comment]
Is the System log the same as the "Power Menu Bug Report" found in [System] Developer Options » USB Debugging?  I'll try that next time issue comes up.  Still, a relief to have it working (even if it's temporarily)!

**Comment by ameshkov** [comment]
No, that is "adb logcat", I remember we were discussing it once

**Comment by ameshkov** [comment]
Closing this issue as there are no more complaints on this. We shouldn't confuse this issue with #597, though.

**Comment by Moradnejad** [comment]
In newer android APIs (such as API 27), URL should be encoded. Otherwise, it results in unsuccessful download. I see that you have spaces in your URL.
