### ISSUE TITLE
#Wi Fi icon disappearing when AdGuard is restarted

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#1861]
### Steps to reproduce

1. Open AdGuard - Turn on the protection
2. Restart the application (on/off)

### Expected behavior
Everything seems to be in order

### Actual behavior
WiFi icon (tray) disappeared

### Your environment

* Adguard version: 2.11.81\2.12.4n
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: Xiaomi redmi 4x
* Operating system and version  Android 7.1.2 / MIUI 9 (Global)
* Not Rooted
* None of the apps that can start VPN/Antiviruses/Cleaners etc. is installed

**Comment by admitrevskiy** [comment]
Looks like it's MIUI bug. To solve this issue go to` Settings -> System & Device -> Notifications & status bar` and turn on "Show status notifications"
