### ISSUE TITLE
Mobile data not working with Block all connections setting

### ISSUE THREAD

**Issue by Kusresa** [AdguardTeam/AdguardForAndroid#1862]
When Adguard VPN is set as Always-on VPN in Android setting with the 'Block all connections that don't go through the VPN' setting Mobile data doesn't work and the internet can't be loaded. Only when I uncheck that option and restart the phone does internet work. On Android 8.0.

**Comment by vozersky** [comment]
@Kusresa hi! got logs?

**Comment by ameshkov** [comment]
Reopen if there's new info
