### ISSUE TITLE
Перевод на русский язык текста

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1863]
Стоит последняя версия приложения и некоторые слова до сих пор на английском. Скрин прикрепляю. http://www.picshare.ru/view/8783520/
И еще вопрос возник, почему журнал фильтрации нельзя отключить? В прошлой версии можно было...

**Comment by Alex-302** [comment]
Последняя с какого канала обновления из трёх?)
В nightly журнал можно отключать.
Указанная строка тоже переведена
![image](https://user-images.githubusercontent.com/8361299/39836129-0bfaeb5e-53db-11e8-885d-339061e48d5f.png)

**Comment by vozersky** [comment]
@ministr91 в найтли канале 2.12.4

**Comment by ministr91** [comment]
@vozersky можете на 4pda закинуть?

**Comment by vozersky** [comment]
@ministr91 Найтли версия никуда не выкладывается, даже на гитхаб. Канал обновления выбирается в приложении: 
![image](https://user-images.githubusercontent.com/17472907/39873757-7f35b8e4-5474-11e8-8d97-c7a313ba5725.png)
