### ISSUE TITLE
Can't export User Filter on Android 8.1.0

### ISSUE THREAD

**Issue by CHEF-KOCH** [AdguardTeam/AdguardForAndroid#1865]
### Steps to reproduce
1. Install AdGuard 2.11.81
2. Ensure that AdGuard app has permission to write/read on storage via settings - apps - adguard -permissions -> storage.
3. Restart the app (if already running)
4. Create `User Filter`
5. Try to export the User Filter list, no matter if internal/external store you get the message `Error exporting user rules.`
6. The import of a own filter list partially works, from some folders it doesn't work. 

### Expected behavior
AdGuard should export the User List on the Internal or external sdcard without any problems as long as the storage isn't special protected or restricted.

### Actual behavior
You see an error - `Error exporting user rules.` The text file with 0 bytes is created. 

### Customer ID 
* 1863484

### Environment

* Adguard version: 2.11.81 (stable)
* Adguard filtering mode: VPN + HTTPS filtering on
* Device model: S5 mini (GM-G800F) test device
* Security Patch level: April 5, 2018
* LineageOS API level: llama (9)
* Operating system and version: LineageOS 8.1 it also happens with Android 9 (P) Dev 1 with a Nexus
* Rooted or not?: Rooted via Magsik
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: No.

**Comment by ameshkov** [comment]
@CHEF-KOCH thank you for reporting it!

@admitrevskiy it appears that the exception is swallowed in the code (see `ExportUserRulesTask`) so there's nothing useful in the log file.

If you cannot reproduce this issue on your side, prepare a test build with proper exceptions handling and share it here.

**Comment by admitrevskiy** [comment]
@CHEF-KOCH Hi!
Please install this version: https://uploads.adguard.com/ADwvveo.apk
Go to Settings -> Advanced -> Logging level, set it to "Record everything" and try to export user filter.

**Comment by admitrevskiy** [comment]
@CHEF-KOCH Hi!
Please, send logs from attached version to `devteam at adguard.com` if your issue is still actual.
In another case let me know if it's not, please

**Comment by CHEF-KOCH** [comment]
Sorry, I can't get the log, it's always 0 bytes. 

Someone else needs to confirm and verify if this issue still exists, I tried the new version + even compiled a newer ROM version but the problem still exists.

**Comment by TheHasagi** [comment]
@CHEF-KOCH 

Hello!

Please install the latest nightly version 2.12.60n - https://agrd.io/android_nightly and try to reproduce the issue.

I'm on the Los 15.1 do not have this issue.

**Comment by ameshkov** [comment]
> Someone else needs to confirm and verify if this issue still exists, I tried the new version + even compiled a newer ROM version but the problem still exists.

Could you please tell us what exact ROM do you use? We'll try using the same then.

**Comment by ameshkov** [comment]
On the other hand

> Sorry, I can't get the log, it's always 0 bytes.

This must be caused by the very same issue as the export error. It has something to do with the access rights to the external storage..

**Comment by admitrevskiy** [comment]
Testing instructions:

-Reinstall AdGuard
-Deny Storage permission if it was allowed
-Try one of the following operations: Export logs/Export settings/Export user filters/Alternative certificate installation

Expected behavior:
1) You can't perform above operations until permission was not granted
2) Information dialog with redirect to the settings appears In case of "Never ask again" checkbox was enabled
