### ISSUE TITLE
com.gm.chevrolet.nomad.ownership

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1867]
@adguard-bot commented on [Tue May 08 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15803)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.gm.chevrolet.nomad.ownership](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.gm.chevrolet.nomad.ownership)
### Comment
Username: @yochananmarqos
> Disabling routing traffic through AdGuard resolves.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/P9i9K8q.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1
AdGuard version: | 2.11.81
AdGuard mode: | proxy
Filtering quality: | High-speed
HTTPS filtering: | enabled
Filters: | Filter unblocking search ads and self-promotion,<br>Mobile Ads,<br>Annoyances,<br>English,<br>Spyware,<br>Social media

**Comment by vozersky** [comment]
could you please reproduce it? @zebrum

**Comment by yochananmarqos** [comment]
I forgot to mention the error in the screenshot only came up when I attempted to login.

**Comment by ameshkov** [comment]
We'd better figure what domain is pinned and place it to the default HTTPS exclusions list.

**Comment by nkartyshov** [comment]
https://github.com/AdguardTeam/HttpsExclusions/pull/86
