### ISSUE TITLE
Encrypt.me VPN and AdGuard auto-proxy not compatible together

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1868]
If Encrype.me is enabled and then proxy mode is started, there's no usable internet connection.

If AdGuard is started first, then Encrypt.me fails to start VPN

Android 8.1.0, Pixel 2 XL

**Comment by carlylemiii** [comment]
Oh, d'oh. That worked. I should have thought to try that or disabling certain filters maybe. Sorry! :)

**Comment by vozersky** [comment]
https://play.google.com/store/apps/details?id=com.stackpath.cloak
