### ISSUE TITLE
Check boat browser add-ons and Adguard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#187]
@gshumihin please check if Adguard filters boat browser when some add-on is installed.

Read this thread for details:
http://forum.adguard.com/showthread.php?7630-Ads-returned-after-Marshmallow-update-(2013-Nexus-7)

It seems that if boat browser add-on is installed, Adguard detects the add-on package name instead the browser's package name.

The problem is that these add-ons package names are not on the browsers list and so free Adguard fails to filter it.

I need you to check all boat browser add-ons and check if it's true. And also write down these add-ons package names for us to add to the browsers list.

**Important note:** keep it in mind that everything was fine before the update to Android 6, with the same add ons installed

**Comment by TPS** [comment]
It seems like Boat Browser has a _huge_ (I shall refrain — somewhat — from a *boat*load pun ;) number of addons, which will inflate the builtin browser list considerably.…  Do you think it might be worthwhile to revisit thinking about getting #25 done?

Though I've never used Boat, if you all like, I could compile a list like for #22.…  Do let me know! ☺

**Comment by ameshkov** [comment]
> Do you think it might be worthwhile to revisit thinking about getting #25 done?

It's really easier to add 10-50 package names to a text file than implementing #25 :)

> Though I've never used Boat, if you all like, I could compile a list like for #22.… Do let me know! ☺

Let's wait until @gshumihin check my idea. I am not yet sure about this.

> As I know Dolphin add-ons aren't separate apps as in boat browser case.

Yep, I think it is possible too. @gshumihin please check Dolphin add-ons too.

**Comment by gshumihin** [comment]
>It seems that if boat browser add-on is installed, Adguard detects the add-on package name instead the browser's package name.

**Comment by TPS** [comment]
>The problem is that these add-ons package names are not on the browsers list and so ___free___ Adguard fails to filter it.

I think, in this bug, @ameshkov is primarily concerned about those limited to the free browser list.

**Comment by ameshkov** [comment]
@gshumihin thank you! i am waiting for the whole addons list then.

@TPS we'll add all these to the browsers list in the next update

**Comment by gshumihin** [comment]
With dolphin same thing happens. Here's Dolphin addons:
```
com.dolphin.addons.pocket
mobi.mgeek.textadjust
com.dolphin.battery.saver
mobi.mgeek.TunnyBrowser.Theme.EnNightModeV10
mobi.mgeek.YoutubeSearch
mobi.mgeek.browserfaster
mobi.mgeek.tabreload
mobi.mgeek.ScreenCut
com.dolphin.browser.engine
com.dolphin.browser.express.web
com.dolphin.web.browser.android
mobi.mgeek.DolphinReader
mobi.mgeek.mypdf
mobi.mgeek.DolphinTranslate
mobi.mgeek.tabswitcher
com.dolphin.browser.addons.box
com.dolphin.browser.addons.skitch
mobi.mgeek.TabHistory
mobi.mgeek.showip
mobi.mgeek.shinyshake
mobi.mgeek.brightness
com.dolphin.theme.ocean
mobi.mgeek.UltimateFlag
mobi.mgeek.TabMixPlus
com.dolphin.addons.evernotesshare
mobi.mgeek.DolphinFM
mobi.mgeek.MorningCoffee
com.dolphin.addons.dropbox
mobi.mgeek.whois
mobi.mgeek.alexa
mobi.mgeek.eBaySearch
mobi.mgeek.BookmarksWidget
```

**Comment by ameshkov** [comment]
Done
