### ISSUE TITLE
Typos in Russian localization, v2.11.81

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1870]
![image](https://user-images.githubusercontent.com/15856304/40047063-1ebaf6e8-5837-11e8-8d11-9e6ad7f431f0.png)

**Comment by nkartyshov** [comment]
done

**Comment by nkartyshov** [comment]
**Testing instructions:**
Go to Feedback screen 

**Expected result:**
Underlined texts should be corrected
