### ISSUE TITLE
Start using adguard.com/forward for the website links

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1875]
We are tired of setting up tons of redirects every time we change anything on the website.

The solution would be to use a special forwarder for every link we have in the app.

Smth like this: `https://adguard.com/forward.html?action=purchase`

**Comment by nkartyshov** [comment]
done

**Comment by TPS** [comment]
A complete list of these (like a sitemap) _might_ be useful.

**Comment by TPS** [comment]
@ameshkov I just found out (from downloading [the ηightly build](https://github.com/AdguardTeam/AdguardForAndroid/issues/1893#issuecomment-395961911) 😝) that y'all're _already_ using __agrd.io__ for something like this.  Why not continue/co-opt that domain for this?  It seems pretty ideal.…

**Comment by nkartyshov** [comment]
**Testing instructions:**
Try to open all links from the AdGuard

**Expected result:**
Links work without problems
