### ISSUE TITLE
AG with VPN applications

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#1876]
connecting to orbot/tor with vpn mode also on lantern app blocks WiFi internet access and i have to disable AG in order to use VPN applications.

<details><summary>Screenshot:</summary>

an x appears on wifi icon...
</details>

### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: Proxy(auto)
* Device model: Nexus 5X
* Operating system and version: Android 8.1
* Rooted or not? rooted

**Comment by ameshkov** [comment]
Please check that you unchecked "Enabled" box for this VPN app in the Apps Management -> app details
