### ISSUE TITLE
minor potential bugs

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#1877]
changing release mode to beta don't give me the beta update.

-----

I don't get the "you're using the latest version of adguard" pop-up message when checking for update.

* Adguard version: 2.11.81
* Adguard filtering mode: Proxy(auto)
* Device model: Nexis 5X
* Operating system and version Android 8.1
* Rooted or not? rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
There was no 2.12 beta yet, could it be the reason for it?
