### ISSUE TITLE
App traffic not showing

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#1879]
https://github.com/AdguardTeam/AdguardFilters/issues/16411

Per the request of support I've disabled https filtering. Same "issue" persists. Traffic does not, as the filter log displays, show particular app traffic. I've just chalked it up to an issue with the device as to which this is happening. This particular phone (note 3 neo) also does not play well with battery measuring apps such as AccuBattery.
On a side note: I don't think this is your department though - this and my nexus 6p require adguard to be restarted or paused for data to connect(for how many things? I would send more logs).
If I can assist in any way, please, be sure to contact me. Great work, guys!

Platform: | And Nougat
-- | --
AdGuard version: | 2.12.19η
Browser: | Atlas, also Firefox at some point
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | disabled

**Comment by Eugene-Savenko** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1874 the similar complaint, a firmware's bug most likely.

**Comment by ameshkov** [comment]
Yeah, this is the same as #1874, a firmware bug for sure
