### ISSUE TITLE
Disabled rules in the user filter still work

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1881]
I added the rule, @@||www.google-analytics.com$app=com.adguard.dns, in the user filter and then **disabled the rule**.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/GlP2S30.png)
</details><br/>

In normal situation, www.google-analytics.com should be blocked in DNS filtering.
But www.google-analytics.com was still not blocked in DNS filtering when I checked it in filtering log.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/kYZbMIg.png)
</details><br/>

B/R

**Comment by ameshkov** [comment]
It is `ssl.google.analytics.com` that is still blocked.
`www.google-analytics.com` was unblocked.

**Comment by ameshkov** [comment]
Oh

**Comment by ameshkov** [comment]
> But www.google-analytics.com was still not blocked in DNS filtering when I checked it in filtering log.

Are you sure these are NEW records that are added after the user filter change?

**Comment by lancelot-moon** [comment]
Hi,

2 weeks ago, your team added the rule, @@||google-analytics.com/analytics.js$domain=line.me, in spyware filter.

If only using HTTPS filtering, that new rule is enough.

But it's not enough if enabling DNS setting in AG for Android.

www.google-analytics.com/analytics.js can pass HTTPS filtering, but is blocked in DNS level because of SDN filter.

Is it possible that you restrict to only allow that line.me can send requests to www.google-analytics.com/analytics.js on the side of AdGuard DNS?

I tried the rule, @@||www.google-analytics.com$domain=line.me,app=com.adguard.dns,important.

But that rule doesn't work on my device...

Or can you add the rule, @@||www.google-analytics.com$app=com.adguard.dns, in spyware filter?

For AdGuard for Android, there are HTTPS filtering and DNS filtering.

Maybe you can't delete ||google-analytics.com^ from SDN filter.

But we can first allow analytics under www.google-analytics.com in DNS level.
And then block them in HTTPS filtering, except for analytics.js.

**Comment by lancelot-moon** [comment]
>Are you sure these are NEW records that are added after the user filter change?

Yes, I think it's bug, not question!
How can disabled rules in the user filter still work?

**Comment by ameshkov** [comment]
> Is it possible that you restrict to only allow that line.me can send requests to www.google-analytics.com/analytics.js on the side of AdGuard DNS?

Unfortunately, that's not possible. DNS is shared among all apps, we cannot make an exclusion for just one of them.

> How can disabled rules in the user filter still work?

Yeah, mustn't happen. We'll check it.

**Comment by lancelot-moon** [comment]
Hi,

I mean to add @@||www.google-analytics.com$app=com.adguard.dns in spyware filter.

Let them pass in DNS level.
Because AdGuard for Android can do HTTPS filtering for system-wide ad blocking, they're still blocked in HTTPS filtering, except for analytics.js which only is requested by line.me.

It should be ok.
We talk about AG for Android which owns HTTPS filtering and DNS filtering.

We don't talk about AG Pro for iOS and AdGuard DNS, which only do DNS filtering for system-wide ad blocking.

**Comment by ameshkov** [comment]
Hm, tbh, I don't like the idea, some people use DNS filtering only.

We need to somehow narrow it down to people who really need it. Ideas?

**Comment by lancelot-moon** [comment]
@@||www.google-analytics.com$app=com.adguard.dns can be put in spyware filter, which only works for DNS filtering, not for HTTPS filtering.

It's not put in SDN filter.

If some users only use DNS filtering, they should turn off all ad blockers for disabling HTTPS filtering.
Then that rule in spyware is also not used.

I don't feel any affection for those who only want DNS filtering.

**Comment by ameshkov** [comment]
I got it. The problem is that "DNS blocking" uses AdGuard SDN filter and the user filter.

It just won't use the rule from the spyware filter.

**Comment by lancelot-moon** [comment]
Yes...

For only DNS blocking, www.google-analytics.com/analytics.js is still blocked by SDN filter.

But for both HTTPS filteting & DNS filtering or only HTTPS filtering, all trackers under google-analytics.com are still blocked.
Only the request to www.google-analytics.com/analytics.js by line.me is allowed.

**Comment by ameshkov** [comment]
> Yes... if only adding @@||www.google-analytics.com$app=com.adguard.dns in spyware filter...

It is not used by the DNS blocking anyway.

**Comment by lancelot-moon** [comment]
Yes, most Taiwanese people don't know how to solve the issue of visiting Line Today.

They don't know why they still can't visit line today if enabling DNS setting in AdGuard for Android.

They only feel that AdGuard lets them not visit Line Today.

That's why I request to only add @@||www.google-analytics.com$app=com.adguard.dns in spyware filter by default.

**Comment by admitrevskiy** [comment]
@lancelot-moon Hi!
The $domain modifier does not make sense in case of DNS. Unfortunately, you need to to simplify this rule and use only $app and important modifiers.

**Comment by admitrevskiy** [comment]
@lancelot-moon Hi!
1) $third-party modifier is not useful in case of DNS too, thank you for this remark! We will remove this option for DNS rules. 
2) We solve this issue, I think in the next version it will works correct.

**Comment by lancelot-moon** [comment]
Hi,

1. After enabling DNS setting in AdGuard app, there are HTTP(S) requests and DNS requests in the filtering log.
The 3 options of making rules for HTTP(S) requests are "Apply to third-party requests only", "Apply to xxx app only" and "Give a higher priority to the rule".

The 3 options of making rules for DNS requests are "Apply to third-party requests only", "Apply to DNS requests only" and "Give a higher priority to the rule".

In DNS requests, we can make rules for HTTP(S) filtering as long as not check "Apply to DNS requests only".

Maybe AdGuard team need to think how to make it serious.
a. A simple method: In DNS requests, only restrictively make rules for DNS filtering .
When clicking DNS requests in the filtering log, it's only restricted to make rules for DNS filtering.
"$app=com.adguard.dns" is automatically added in rule syntax.
No the options of "Apply to third-party requests only" and "Apply to DNS requests only".
Only remain the option of "Give a higher priority to the rule".

b. A complex method: Allow to make rules for HTTP(S) / DNS filtering in DNS requests.
When checking the option of "Apply to DNS requests only", the option of "Apply to third-party requests only" can't be checked.
Additionally add the logic in app design.

2. The issue (Disabled rules for only DNS filtering still worked) is solved in v2.12.47η.

**Comment by ameshkov** [comment]
> a. A simple method: In DNS requests, only restrictively make rules for DNS filtering .

Not restrict, we might better just have it enabled by default.

**Comment by lancelot-moon** [comment]
> Not restrict, we might better just have it enabled by default.

That's really a good idea!
Thanks!
After all, it's about making rules in DNS requests.
"Apply to DNS requests only" is enabled by default, which is natural.

(And **sorry to trouble you** in another topic in the zone of AG for iOS.
I dislike and couldn't endure that kind of situation, especially I only talked about app from the beginning.
Sorry again!)
