### ISSUE TITLE
com.viber.voip - unable to send files

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1883]
### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.viber.voip](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.viber.voip)
### Comment
> Не отправляет фото через вайбер. Даже через час загрузки. При отключении программы отправка сразу же.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/lIY8qFb.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 4.4
AdGuard version: | 2.11.81
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Filters: | Russian,<br>Mobile Ads,<br>Simplified domain names,<br>English,<br>Spyware
Other extensions used: | avira антивирус

**Comment by zebrum** [comment]
@Eugene-Savenko please, update to the latest nightly 2.12.52 and check. If it doesn't help then collect 'Record everything' level logs.

**Comment by ameshkov** [comment]
Any updated on this?

**Comment by vozersky** [comment]
cannot reproduce
