### ISSUE TITLE
An issue with providers relying on their DNS servers to provide IPv4-mapped addresses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1884]
Just when I thought I was out, they pulled me back:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1804#issuecomment-390801713

## Steps to reproduce (Sprint):

1. Use the build with a new TUN address: https://uploads.adguard.com/up04_hichx_adguard_tun_address_settings.apk
2. Enable DNS filtering module
3. Use a custom DNS server (any of them)
4. Use the speedtest app

For some reason, the LTE is throttled to 2 Mbps.
No issue when using the system default DNS.

## T-Mobile

Using a custom DNS server is impossible, they don't let using IPv4 addresses at all.

## What do we need

Here's what we need:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1884#issuecomment-396303621

**Edit:** Got the logs for Sprint on Android: https://github.com/AdguardTeam/AdguardForAndroid/issues/1884#issuecomment-396532297

**Comment by Kaiser23k** [comment]
I just keep bringing you problems, sorry.

Anyways, this issue does not affect Wi-Fi, just LTE.
And only custom DNS servers.

That's all I have for you at this time.

**Comment by ameshkov** [comment]
No worries and thank you for helping us resolve them :)

**Comment by Kaiser23k** [comment]
Disabling AG for Speedtest app while using a custom DNS fixes the issue. 
Disabling "Ad blocking" while keeping AG Enabled for Speedtest does not work.
I'll keep trying other things.

**Comment by Kaiser23k** [comment]
Not sure if this will help, but I will run "ip addr show" in adb shell with:
DNS Disabled
DNS Enabled, System DNS
DNS Enabled, Custom DNS

I'll paste them in separate posts.

**Comment by Kaiser23k** [comment]
DNS DISABLED

star2qlteue:/ $ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 2e:9f:24:20:4f:2a brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 36:86:86:75:23:ba brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3486:86ff:fe75:23ba/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
5: p2p0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 8e:45:00:71:b9:72 brd ff:ff:ff:ff:ff:ff
6: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 8c:45:00:71:b9:72 brd ff:ff:ff:ff:ff:ff
7: rmnet_ipa0: <UP,LOWER_UP> mtu 2000 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[530]
8: rmnet_data0: <UP,LOWER_UP> mtu 1422 qdisc htb state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2600:1:971c:afa4:6cbc:b623:40c6:aab8/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::522c:bc13:f71f:917c/64 scope link
       valid_lft forever preferred_lft forever
9: rmnet_data1: <UP,LOWER_UP> mtu 1422 qdisc htb state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2600:2:8825:84be:0:5e:1ce8:6301/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ef7b:2738:a411:237b/64 scope link
       valid_lft forever preferred_lft forever
10: rmnet_data2: <> mtu 1422 qdisc noop state DOWN group default qlen 1000
    link/[530]
11: rmnet_data3: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
12: rmnet_data4: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
13: rmnet_data5: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
14: rmnet_data6: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
15: rmnet_data7: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
16: epdg0: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
17: epdg1: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
18: epdg2: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
19: epdg3: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
20: epdg4: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
23: v4-rmnet_data0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1394 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 192.0.0.4/32 brd 192.0.0.4 scope global v4-rmnet_data0
       valid_lft forever preferred_lft forever
    inet6 fe80::8dba:1c7:e189:8d37/64 scope link flags 800
       valid_lft forever preferred_lft forever
25: tun0: <POINTOPOINT,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 172.18.11.218/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:ad:0:ff::/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::2a76:23c2:ddc9:d2de/64 scope link flags 800
       valid_lft forever preferred_lft forever

**Comment by Kaiser23k** [comment]
DNS ENABLED, SYSTEM DNS

star2qlteue:/ $ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 2e:9f:24:20:4f:2a brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 36:86:86:75:23:ba brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3486:86ff:fe75:23ba/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
5: p2p0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 8e:45:00:71:b9:72 brd ff:ff:ff:ff:ff:ff
6: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 8c:45:00:71:b9:72 brd ff:ff:ff:ff:ff:ff
7: rmnet_ipa0: <UP,LOWER_UP> mtu 2000 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[530]
8: rmnet_data0: <UP,LOWER_UP> mtu 1422 qdisc htb state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2600:1:971c:afa4:6cbc:b623:40c6:aab8/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::522c:bc13:f71f:917c/64 scope link
       valid_lft forever preferred_lft forever
9: rmnet_data1: <UP,LOWER_UP> mtu 1422 qdisc htb state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2600:2:8825:84be:0:5e:1ce8:6301/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ef7b:2738:a411:237b/64 scope link
       valid_lft forever preferred_lft forever
10: rmnet_data2: <> mtu 1422 qdisc noop state DOWN group default qlen 1000
    link/[530]
11: rmnet_data3: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
12: rmnet_data4: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
13: rmnet_data5: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
14: rmnet_data6: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
15: rmnet_data7: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
16: epdg0: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
17: epdg1: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
18: epdg2: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
19: epdg3: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
20: epdg4: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
23: v4-rmnet_data0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1394 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 192.0.0.4/32 brd 192.0.0.4 scope global v4-rmnet_data0
       valid_lft forever preferred_lft forever
    inet6 fe80::8dba:1c7:e189:8d37/64 scope link flags 800
       valid_lft forever preferred_lft forever
27: tun0: <POINTOPOINT,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 172.18.11.218/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:ad:0:ff::/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::d10:682d:bd74:7496/64 scope link flags 800
       valid_lft forever preferred_lft forever

**Comment by Kaiser23k** [comment]
DNS ENABLED, CUSTOM DNS

star2qlteue:/ $ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 2e:9f:24:20:4f:2a brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 36:86:86:75:23:ba brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3486:86ff:fe75:23ba/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
5: p2p0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 8e:45:00:71:b9:72 brd ff:ff:ff:ff:ff:ff
6: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 8c:45:00:71:b9:72 brd ff:ff:ff:ff:ff:ff
7: rmnet_ipa0: <UP,LOWER_UP> mtu 2000 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[530]
8: rmnet_data0: <UP,LOWER_UP> mtu 1422 qdisc htb state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2600:1:971c:afa4:6cbc:b623:40c6:aab8/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::522c:bc13:f71f:917c/64 scope link
       valid_lft forever preferred_lft forever
9: rmnet_data1: <UP,LOWER_UP> mtu 1422 qdisc htb state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2600:2:8825:84be:0:5e:1ce8:6301/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::ef7b:2738:a411:237b/64 scope link
       valid_lft forever preferred_lft forever
10: rmnet_data2: <> mtu 1422 qdisc noop state DOWN group default qlen 1000
    link/[530]
11: rmnet_data3: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
12: rmnet_data4: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
13: rmnet_data5: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
14: rmnet_data6: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
15: rmnet_data7: <> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/[530]
16: epdg0: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
17: epdg1: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
18: epdg2: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
19: epdg3: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
20: epdg4: <POINTOPOINT,MULTICAST,NOARP> mtu 1422 qdisc noop state DOWN group default qlen 500
    link/none
23: v4-rmnet_data0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1394 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 192.0.0.4/32 brd 192.0.0.4 scope global v4-rmnet_data0
       valid_lft forever preferred_lft forever
    inet6 fe80::8dba:1c7:e189:8d37/64 scope link flags 800
       valid_lft forever preferred_lft forever
31: tun0: <POINTOPOINT,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none
    inet 172.18.11.218/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:ad:0:ff::/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::4a44:fb72:c28:7bdb/64 scope link flags 800
       valid_lft forever preferred_lft forever

**Comment by Kaiser23k** [comment]
I was unable to find any difference between them. Guess this didn't help :(

**Comment by ameshkov** [comment]
I think I have an idea!

What we need to compare the IP addresses resolved by the system default DNS to the ones resolved by the custom DNS. Sprint might be using the same IPv4-mapping trick as T-Mobile.

So, I need two sets of logs (custom DNS and system default DNS) recorded with the "record everything" logging level.

**Comment by Kaiser23k** [comment]
Custom DNS: 
[adguard_logs_2.12.26_1106_1534.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2091959/adguard_logs_2.12.26_1106_1534.zip)

System DNS: 
[adguard_logs_2.12.26_1106_1536.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2091962/adguard_logs_2.12.26_1106_1536.zip)

**Comment by ameshkov** [comment]
So, here's what I see.

In the Cloudflare DNS case, it resolves the A record (IPv4), but not the AAAA record (IPv6):
```
DNS id=10000028 question=ookla1.tacmwa.sprintadp.net.	0	IN	AAAA answer=Empty
DNS id=10000029 question=ookla1.tacmwa.sprintadp.net.	0	IN	A answer=A: 204.180.152.6 (ttl=1620)
```

However, the system default DNS returns an AAAA response as well:
```
DNS id=10000084 question=ookla1.tacmwa.sprintadp.net.	0	IN	AAAA answer=AAAA: 2600:0:cf02:ff64::ccb4:9806 (ttl=180)
DNS id=10000085 question=ookla1.tacmwa.sprintadp.net.	0	IN	A answer=A: 204.180.152.6 (ttl=84475)
```

I assume that the AAAA record is a Sprint's IPv4-mapped address. All these mapped addresses have the same prefix: `2600:0:cf02:ff64::`.

**Comment by ameshkov** [comment]
IPv4 to long (`204.180.152.6`) = 3434387462
Hex to integer (`ccb4:9806`) = 3434387462

Yeah, this is a mapped address, and we can emulate this behavior on our side. That will let Sprint users use custom DNS servers with no throttling.

However, I'd better wait and collect logs from users with other operators (T-Mobile at least) just to see if they're using the same approach.

There's a similar issue on Android and iOS, and I'd like us to resolve both: https://github.com/AdguardTeam/AdguardForiOS/issues/796

**Comment by sfionov** [comment]
Android uses this RFC for PLAT prefix detection on IPv6-only APNs:
https://tools.ietf.org/rfc/rfc7050.txt

**Comment by admitrevskiy** [comment]
Resolved in 3.0

**Comment by Kaiser23k** [comment]
Is there currently a V3.0 beta or nightly build I can use?

**Comment by ameshkov** [comment]
@Kaiser23k not yet ready for nightlies unfortunately

**Comment by TPS** [comment]
@Kaiser23k Try https://agrd.io/android_nightly for ≥ v3.056ƞ

Btw, followed entire discussion @ #1804 & here.  Absolutely fascinating!

**Comment by Kaiser23k** [comment]
Everything so far seems to be working correctly now. 👍 
I'll let you know if I find anything else not working correctly.
