### ISSUE TITLE
Add a context menu to the license activity

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1885]
Now in 3.0 layout we have 3 buttons:
1. Free trial
2. Enter key
3. Purchase

We need to remake it to be:
1. Free trial
2. Purchase

And in added context menu we will have two items:
1. Restore purchase
2. Enter key!
[Screenshot_1526983224_.png](https://images.zenhubusercontent.com/5a9694a34b5806bc2bc8c29b/edd65491-6a3e-49ce-b479-d65996452cbe)

**Comment by nkartyshov** [comment]
done
