### ISSUE TITLE
AdGuard process kills itself unexpectedly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1887]
Check the log file:
[4444.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/2039455/4444.txt)

`isCurrentAppForeground` is problematic, I suggest restricting this block to the old Android versions only.

**Comment by CrescendoFang** [comment]
I just experienced this while browsing, the page suddenly won't load and I noticed that AG was gone from notification bar...

**Comment by CrescendoFang** [comment]
AG is also forcefully disabled (or crashed, dunno since it's just gone dead) when playing Mafia City game...
