### ISSUE TITLE
HAR file is not recorded

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#1888]
### Steps to reproduce

1.Start AdGuard - Settings - Low-level settings - pref.har.capture
2.Switch off all filters, Ad Blocker but HTTPS Filtering should be on
3.Open Fast - Social App, use it for 5 minutes
4.Stop AdGuard, go to Android/data/com.adguard.android.cache/har

### Expected behavior
Har file should be more than ±3 mb

### Actual behavior
Recorded har files will be less than 311 bytes

</details>

### Your environment

* Adguard version: 2.12.19n
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: ASUS NEXUS 7
* Operating system and version Android 6.01
* Core 3.4.0-g094b859
* No other apps that can start VPN/Antiviruses/Cleaners etc. installed

**Comment by admitrevskiy** [comment]
Everything works fine 'cause it's expected behavior: all connections are bypassed and there is nothing to write in Har file, when AG in VPN mode and AdBlocker is switched off for the app.
