### ISSUE TITLE
Cosiloon Malware

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#1889]
@AdguardTeam _N.B.: From what I read, this an Android problem **only**, so I'm posting here.  If incorrectly placed, please move!_

Very widespread ___system/stock pre-installed___ ad-spamming malware, especially on 'shady' (mostly non-Google certified), low-end devices.

Reports:
- https://blog.avast.com/android-devices-ship-with-pre-installed-malware
- https://vms.drweb.com/virus/?i=9010704&lng=en
- https://news.drweb.com/show/?i=10345&lng=en

Incomplete list of infected devices: https://docs.google.com/spreadsheets/d/1RXkReFfgyBhri-B5ZFsTPk8asRLi_MKtFQnbDYhpf50/edit

Samples: https://docs.google.com/spreadsheets/d/10GREhHGREaQvx45kb7AI4FkXDFX1VDjNWyRpU9qGJ5k/edit

Some package names:
- `com.google.eMediaService`
- `com.google.eMusic1Service`
- `com.google.ePlay3Service`
- `com.google.ePlay4Service`
- `com.google.eVideo2Service`
- `CrashService` (mentioned incompletely)
- `ImeMess` (mentioned incompletely)
- `com.android.keyguard.KeyStateBroad`
- `com.android.keyguard.KeyManager`
- `com.android.keyguard.KeyguardService`
- `com.android.keyguard.KeyguardReceiver`
- `com.mediatek.mtkmusicprovider`
- `com.android.keysetting`
- `com.get.googleApps`

Some contacted infection URLs:
- `http://www.cosiloon.com/version.xml`
- `http://www.cosiloon.com/version_4.xml`
- `http://www.cosiloon.com/version_5.xml`
- `http://app.storage.yunvm.com/ba.apk`
- `http://pull-3045.kxcdn.com/getip.php`
- `*.7176.com`

**Comment by vozersky** [comment]
the best thing we can do is adding those URLs to the safebrowsing, I guess @TheHasagi

**Comment by TacoTheDank** [comment]
🤔

**Comment by TPS** [comment]
@vozersky The other major thing that can be done is default-blocking the __packages__, & _that_ requires flipping the switch on rolling out those filters ([this comment onwards](https://github.com/AdguardTeam/AdguardForAndroid/issues/908#issuecomment-261141292)) which break old versions of AG.

___N.B.: #904 (as mentioned) & #1104 could use the same treatment & love as whatever y'all do here.___

**Comment by TPS** [comment]
Is there any hope for any further progress w/ this?  @Stale plans to close it otherwise.

**Comment by ameshkov** [comment]
See https://github.com/AdguardTeam/AdguardForAndroid/issues/908#issuecomment-517489371

**Comment by TPS** [comment]
Since https://github.com/AdguardTeam/AdguardFilters/commit/59a4778bcdbfeb63a9b346164d48582e7264a5f0 was committed to close out #908, could there be a corresponding commit for _this_ issue?  The package list is [above](https://github.com/AdguardTeam/AdguardForAndroid/issues/1889#issue-326708947).

**Comment by ameshkov** [comment]
In this particular case, we'd better block URLs.

@TheHasagi please check if there are any that aren't blocked by us yet

**Comment by TPS** [comment]
>[As I mentioned, if the packages aren't blocked, all they hafta do is switch domains (as designed for similar reasons), & they're back in business.](https://github.com/AdguardTeam/AdguardForAndroid/issues/1104#issuecomment-530136682)

**Comment by TheHasagi** [comment]
All of those URLs are blocked.

**Comment by TPS** [comment]
Could the package names be blocked, also? 🙏🏾
