### ISSUE TITLE
Add a "Terms" step when the app is started for the first time

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1890]
Use the same style as we have in the "Splash screen" and add an EULA and privacy policy disclaimer:
https://uploads.adguard.com/up04_emxp5_Adguard_for_Android_-_Terms__Moqups_.png

Text: `By proceeding you agree with End User License Agreement and Privacy Policy.`
EULA: https://adguard.com/eula.html
Privacy Policy: https://adguard.com/privacy.html

When the app is started, check the `user_consent` field value. If it is not set, you need to show this interstitial screen. Therefore, we will show it even to those users who updated AdGuard from a previous version.

**Comment by nkartyshov** [comment]
done

**Comment by nkartyshov** [comment]
**Testing instructions:**
1. Reinstall AdGuard
2. Launch AdGuard
**Expected result:**
The following screen appears:
![device-2018-05-29-121333](https://user-images.githubusercontent.com/3413799/41959176-e82704ca-79f4-11e8-957b-c026992ab4d6.png)
