### ISSUE TITLE
Get rid of the Amazon AppStore build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1893]
They decided to implement the same policies as Google Play so we no more need it.

@vozersky we also need to get rid of Amazon links on KB, xda, etc.

**Comment by TPS** [comment]
Since I was 1 of the earliest proponents to get AG on Amazon, I'm terribly :sob:. re: https://adguard.com/en/blog/goodbye-amazon/.

How do those of us w/ regular commercial &/or ß licenses switch over?

**Comment by ameshkov** [comment]
Uh, sorry for the late reply:(

> How do those of us w/ Amazon standardl &/or ß licenses switch over to the website version?

Regular subscriptions are monthly, our support service should provide a temp 30 day license key for that period.

Beta testers need to go through the standard beta key requesting procedure.

> Since I was 1 of the earliest proponents to get AG on Amazon, I'm terribly 😭 re: https://adguard.com/en/blog/goodbye-amazon/.

Yeah, I didn't see it coming tbh :(

**Comment by vozersky** [comment]
Cleaned up kb and xda

**Comment by TPS** [comment]
@ameshkov So, https://kb.adguard.com/en/general/adguard-beta-testing-program#android → https://docs.google.com/forms/d/e/1FAIpQLSf5JWqO_Qsdri1nwJphse46Qk48YHVyc3IZs1l-XmJ3ff0dDQ/viewform is the current procedure?  Or do y'all have a nifty [adguard.com/forward.html? link](https://github.com/AdguardTeam/AdguardForAndroid/issues/1875)?  Also, are these perpetual? Yearly? Monthly?

**Comment by TPS** [comment]
Btw, the GForm linked above _still_ lets 1 apply for _Amazon_ ß.… 😭

**Comment by vozersky** [comment]
A new website page for beta application is coming

**Comment by ameshkov** [comment]
> is the current procedure?

Yeah

> Also, are these perpetual? Yearly? Monthly?

Usually yearly, and can be extended through the same form.

Btw, you can finally try the nightly channel (which you couldn't use with Amazon:))

**Comment by TPS** [comment]
@ameshkov I'm starting to get nervous re: receiving the new ß license: I filled out the form, but no response, & my monthly Amazon renewal is coming up in a few days.  Did I miss something?

**Comment by TheHasagi** [comment]
@TPS 
Hello!

You can now check in your mailbox, I bet there is a letter with all information you are interested in.

**Comment by TPS** [comment]
Just got it & setup!  Thanks, @all! :bow:

**Comment by Revertron** [comment]
Done with builds.
