### ISSUE TITLE
Сбои Adguard. Потеря сети, перезагрузки

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1895]
Что вы такого добавили в эту версию? Прошлая релизная версия 2.10.176 работала гораздо лучше. В версии релизной 2.11.81 постоянно проблемы появляются. 
1) Сижу в игре и тут раз - соединение потеряно. Захожу в Adguard, защита выключена, потом перезапуск автоматом. Не 1 раз такое
2) Сижу в.браузере, выхожу из него и у меня рабочий стол перезагружается. Раньше я просто выходил и видел все значки рабочего стало, а теперь они все исчезают, экран моргает и все появляется. 
3) Потеря соединения с интернетом, когда сижу через хром. Захожу, далее захожу на сайт и пишет - недоступен, загрузка продолжается и сайт появляется. Это как? Пишет недоступен, а потом сразу нормально все.
Логи какие мог выгрузил. Версия последняя, фильтры по-умолчанию, фильтрация качественная, HTTPS, HTTP, Android 4.4.4 Nexus 5
https://ru.files.fm/u/chbkevba

**Comment by ameshkov** [comment]
Андроид убивает процесс, ничего нового.

Удостоверьтесь что настройки попроще и памяти хватает.
Ну а вообще подождите первой бета-версии 2.12, там у нас новый движок фильтрации, по потреблению ресурсов все гораздо лучше.
