### ISSUE TITLE
Automation settings (Tasker, AutomateIt, etc)

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1896]
Now we've exposed our ServiceManager service to rule AdGuard from Tasker.
We need to remove ServiceManager, and for this task we need to develop some new interface.
It can be a BroadcastReceiver that will get all intents from Tasker and change the state of protection.

**Comment by ameshkov** [comment]
First of all, we need to add a new setting to the "Advanced" section and call it: `Automation`

Description:
```
Status: Disabled
AdGuard can expose an API that you can use for setting up custom complicated automation rules via apps like "Tasker", "AutomateIt", etc.
```

Tapping on this setting opens a new activity.

Here's what we need to show on this activity:

* Status bar
* Help text (just like what we show on DNS, HTTPS filtering, etc). Icon for it: https://icons8.com/icon/set/automation/material
* Pin code
* Actions description

Mockup:
https://uploads.adguard.com/up04_tx9e1_Adguard_for_Android_-_Automation__Moqups_.png

**Prior to implementing it, we must add a knowledge base article explaining what it is.** Click on the "Learn more" button leads to this article.

Here is the list of actions we expose through the API:

1. Start protection (starts protection)
2. Stop protection (stops protection completely)
3. Pause protection (pauses protection -- with a notification that allows to unpause it manually)
4. Check filters updates

**Comment by TPS** [comment]
Is this the current state for the ηightly builds?  If so, what intents _do_ work?  Or _is_ there none 'til that `Automation` section is activated?

**Comment by ameshkov** [comment]
> Is this the current state for the ηightly builds? If so, what intents do work? Or are there none 'til that Automation section is activated?

The old API does not work in the currently nightly builds.

We intend to replace it with the new one completely.

**Comment by TPS** [comment]
Sadly, this is suddenly essential again, as my current (possibly temporary) device has critical need of this.  (Apparently, the watchdog function isn't sufficient, either. :cry:)

**Comment by Revertron** [comment]
Implemented and merged.

Testing instructions:
Install AdGuard 2.12.83+, Tasker or AutomateIt.
Check all functions from KB article: https://kb.adguard.com/android/solving-problems/tasker

**Comment by TPS** [comment]
I like it, & it's rather simple to use, even on officially unsupported/abandoned automators (I use [Llama](http://play.google.com/store/apps/details?id=com.kebab.Llama)).

A suggestion: Allow an `extra` to modify behavior of that green toast that pops-up, so it can, i.e., operate silently, or, more advanced, [iff](https://en.m.wikipedia.org/wiki/If_and_only_if) it affects state (e.g., if using `start`, toast only shows whenever AG isn't _already_ started).

**Comment by ameshkov** [comment]
@Revertron let's make it configurable as @TPS suggests, the toast might be annoying. 

We will need to add it to the article as well.

**Comment by TPS** [comment]
Thanks! :bow:

Another suggestion for those using the previous/legacy version:  Popup a dialog (I think a toast is insufficient) in AG to the effect of "[You're using our old/deprecated version of automation!  Update now to our free, secure, more versatile version!](https://kb.adguard.com/android/solving-problems/tasker)" whenever an old-style intent is received/detected.  I think it's silently ignored now.

**Comment by snhv** [comment]
Hi,
Can we do something like this:
1. When phone connects to wifi networks:
- Adguard switches to proxy mode;
- another VPN of our choice starts and get connected.
2. When phone connects to mobile networks:
- the other VPN stops;
- Adguard switched back to VPN mode.

Thanks.

**Comment by Revertron** [comment]
@snhv 
1. Why do you trust your mobile operator and not wi-fi networks? ;)
2. If you already have root and you are able to use AdGuard in root-proxy mode, why do you need VPN mode? :)
You can use root-proxy mode whenever and be happy with that.
> can automation apps automatically set up proxy for whatever connected wifi too?

Without root it is impossible.

**Comment by snhv** [comment]
> Without root it is impossible.
OK understood.

> Why do you trust your mobile operator and not wi-fi networks? ;)
Mobile connection is encrypted. Wifi connection may be not and prone to man-in-the-middle attack. 

> If you already have root and you are able to use AdGuard in root-proxy mode, why do you need VPN mode? :)
No I as majority of phone users don't have root. The proxy I mentioned is manual proxy mode for wifi networks. That's why I asked if antomation app can set that up.

**Comment by TPS** [comment]
@vozersky This is still missing the [toast configurability](https://github.com/AdguardTeam/AdguardForAndroid/issues/1896#issuecomment-401515216) info, @ least in the KB article, but maybe in implementation as well.…

**Comment by ameshkov** [comment]
> This is still missing the toast configurability info, @ least in the KB article, but maybe in implementation as well.…

It's rather self-explanatory, not really necessary to have it in the KB article.

**Comment by TPS** [comment]
@ameshkov I don't understand.  How _does_ 1 configure the toasts for automation?

**Comment by ameshkov** [comment]
@TPS there's a "Show toasts" setting in the automation settings (maybe it's in the nightly ver only?)

**Comment by TPS** [comment]
@ameshkov Oh, I saw _that_, but completely silent operation isn't useful to me;  I was expecting something more along lines of
> let's make it configurable as @TPS suggests
>>Allow an _**extra**_ to modify behavior of that green toast that pops-up, so it can, i.e., operate silently _[per a particular configured intent]_, or _**display no more than once an hour, or, more advanced, [iff](https://en.m.wikipedia.org/wiki/If_and_only_if) it affects state (e.g., if using start, toast only shows whenever AG isn't already started)**_.

**Comment by TPS** [comment]
@ameshkov Oh, I saw _that_, but completely silent operation isn't useful to me;  I was expecting something more along lines of
> let's make it configurable as @TPS suggests
>>Allow an _**extra**_ to modify behavior of that green toast that pops-up, so it can, i.e., operate silently _[per a particular configured intent]_, or _**display no more than once an hour, or, more advanced, [iff](https://en.m.wikipedia.org/wiki/If_and_only_if) it affects state (e.g., if using start, toast only shows whenever AG isn't already started)**_.

**Comment by ameshkov** [comment]
Uh, this kind of configuration is too complicated and worthy of a separate feature request. Mind filing it?

**Comment by TPS** [comment]
@ameshkov [Absolutely, & done!](https://github.com/AdguardTeam/AdguardForAndroid/issues/2049) :bow:
