### ISSUE TITLE
Allow automatic switching of DNS servers

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1898]
> My wifi runs on IPv4 and mobile network on IPv6. Is there a way to automatically switch dns
> servers? Something similar to what Google/JigSaw's Intra does
> https://github.com/Jigsaw-Code/intra/tree/master/Android/app/src/main/java/app/intra/util

ID: 1894802

**Comment by ameshkov** [comment]
Not yet possible, but this is a good feature request.

**Comment by ameshkov** [comment]
Well, since we now support NAT64/DNS64, there's no need to support this.

**Comment by TPS** [comment]
Is this handled internally by AG?  Or is it a function of whatever DNS that AG supports?

**Comment by ameshkov** [comment]
> Is this handled internally by AG? Or is it a function of whatever DNS that AG supports?

The original issue cause was that AdGuard could not handle IPv6-only networks, this is not the case anymore in v3
