### ISSUE TITLE
Missing Browser Recognition: Ghostery

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#19]
https://play.google.com/store/apps/details?id=com.ghostery.android.ghostery

**Comment by Revertron** [comment]
Added.

**Comment by TPS** [comment]
Thanks! ☺

**Comment by TPS** [comment]
This seems to be defaulted off.…  Anything special I should know?

**Comment by Revertron** [comment]
@TPS It is added like any other browser. Nothing special. May be you had one issue that we've seen on one user's phone...

**Comment by TPS** [comment]
I had the same problem with Dolphin Zero when you all resolved #22 —  I hadn't noticed it'd been added (default off) until I went into the firewall list to check something else, but #18 & #20 automatically filtered when added: they were default toggled on.…  Weird, right?
