### ISSUE TITLE
[Nightly] Incorrect notification and protection button state

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1903]
Adguard  2.12.47n

**STR:**

<details><summary>1.  Open notifications</summary>

![0 1](https://user-images.githubusercontent.com/17472907/41058635-f196b7bc-69d2-11e8-8d38-6ff45deb848c.png)

</details>

<details><summary>2. Open the system's VPN notification and choose "disconnect"</summary>

![0 2](https://user-images.githubusercontent.com/17472907/41058634-f176b958-69d2-11e8-815a-eb6ae196de2d.png)

</details>

<br>

**Actual result:**

<details><summary>Adguard shows incorrect notification</summary>

![0 3](https://user-images.githubusercontent.com/17472907/41058632-f152ffd6-69d2-11e8-9625-1e8016569bbe.png)

</details>

<details><summary>The protection button is in wrong state as well</summary>

![0 4](https://user-images.githubusercontent.com/17472907/41058631-f12f9460-69d2-11e8-9916-5809290fa4ba.png)

</details>

**Comment by ameshkov** [comment]
Resolved in `repos/adguard-android/pull-requests/466`
