### ISSUE TITLE
[Nightly] "Preparing to stop protection" state takes too much time to complete

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1905]
Adguard 2.12.47n

**STR:**
1. Enable protection.
2. Choose "quit" in the side menu.

**Actual result:**

It takes about 6 secs on my device to stop the protection.

![image](https://user-images.githubusercontent.com/17472907/41062085-549b5098-69dd-11e8-900c-7af58a04b336.png)

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/467`
