### ISSUE TITLE
[Nightly] Crash on second try of starting root proxy protection on non-rooted device

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#1906]
Don't ask

### Steps to reproduce

1. Choose root proxy
2. Press start
3. Press start again

### Expected behavior
Two errors

### Actual behavior
Error on first try
Crash on second try

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 2.12.47
* Adguard filtering mode: Root proxy
* Device model: Xiaomi mi5s
* Operating system and version: Android 7.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by ameshkov** [comment]
Fixed in `adguard-android/pull-requests/468`
