### ISSUE TITLE
Wrong notification state when you change the filtering mode in the advanced settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1907]
### Steps to reproduce

1. Run AdGuard
2. Switch between proxy and VPN mode

### Expected behavior
The status notification should represent the current running filtering mode.

### Actual behavior
It shows randomly a "proxy" or VPN notification text

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1882   ?

**Comment by ameshkov** [comment]
Can't reproduce anymore
