### ISSUE TITLE
[Nightly] Broken page

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#1909]
https://m.focus.de/politik/deutschland/rechter-shitstorm-nazis-nicht-willkommen-berliner-cafe-verbietet-afd-anhaengern-zutritt_id_9051318.html

Since the latest nightly (previous was fine) the site just displays 
script type='text/javascript'> try { TFT_Ext_FOL_mobileAmznAds = true; } catch(e) {}

On unrooted Amazon Fire which is based on Android 4.4 on Silk browser.Disabling AdGuard and the site displays fine. Probably due to new CoreLibs. On Chrome the site just stays empty.

![screenshot_2018-06-07-02-35-06](https://user-images.githubusercontent.com/34266271/41071994-68bc79ee-69fb-11e8-94cc-74f6c5a5984d.png)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #323](https://github.com/AdguardTeam/CoreLibs/issues/323) via [**ZenHub**](https://www.zenhub.com/)
