### ISSUE TITLE
Incompatibility Issue between afwall and AdGuard on Oreo.

### ISSUE THREAD

**Issue by redirectr00t** [AdguardTeam/AdguardForAndroid#1913]
An incompatibility issue exists, between any Nightly builds after stable version of AdGuard 2.11.81 and afwall.

In order to reproduce install latest nightly build of AdGuard, set it to local vpn mode, inside afwall you will see many connections being blocked.

This problem only arise on Android 8.1.0, probably due to some forward rules implemented in latest nightly builds after 2.11.81, cannot repro on Nougat or Lollipop, so is a system specific issue.

**Comment by ameshkov** [comment]
Not that we can change anything on our side, we're just using the VPN API.

Also, exactly due to incompatibilities with Firewalls, AdGuard provides the same functionality by itself.

**Comment by redirectr00t** [comment]
@ameshkov I tried reproduce the problem, and happen also without afwall, I updated my klte to an unofficial build of LineageOS running 8.1.0, and no luck with any nightly buildes to update filters in local vpn mode, I suspect there is some issues on Oreo 8.1.0 and latest Nightly on LineageOS, can you assign someone trying on any lineageOS build 8.1.0 if there is a certificate issue?
