### ISSUE TITLE
Moving to priv-app will crash on revert version

### ISSUE THREAD

**Issue by redirectr00t** [AdguardTeam/AdguardForAndroid#1914]
Moving AdGuard to system/priv-app will work, I tried with latest stable, updating to a Nightly will also work, anyway trying reverting from a Nightly to Stable if the app is moved to priv-app will cause AdGuard crashing on every launch.

**Comment by ameshkov** [comment]
That's understandable, the database structure is completely different.

You need to clear the app's data before reverting nightly to stable.

**Comment by ameshkov** [comment]
In any case, it'd be helpful if you collect AdGuard logs
