### ISSUE TITLE
[Nightly] apkmirror.com high quality filtering

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#1917]
https://github.com/AdguardTeam/AdguardFilters/issues/17741

Hi, on latest Nightly, there is something wrong with High-quality filtering. It doesn't block ads as it should be. For example, on www.apkmirror.com there are blank ads spaces. High Quality filterling always removes these spaces, so there is nothing left. Also, it doesn't block popups well. In general, something is broken.

Information | value
-- | --
Platform: | And 8.1.0
AdGuard version: | 2.12.52
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Filters: | English

---

On my Android 7 I can't reproduce the issue. So probably related to Android 8.

**Comment by zebrum** [comment]
@vozersky can you check it on Oreo device?

**Comment by vozersky** [comment]
@zebrum Can't reproduce the thing with apkmirror, everything is blocked correctly.

**Comment by adnage19** [comment]
@zebrum @vozersky I can't agree, I've checked IT again - I installed stable version - no problems, everything's good. Then I updated version to Nightly one through the app. Didn't change any settings and the problem appeared. There are blank spaces again.

**Comment by BlazDT** [comment]
Maybe related issue as with with $content (HTML filtering) and Kindle Fire.

**Comment by adnage19** [comment]
2.12.81 version - the problem still appears.

**Comment by zebrum** [comment]
@adnage19 can you collect 'record everything' level log please?

**Comment by adnage19** [comment]
@zebrum
Sorry for the delay. After enabling "record everything", can I send logs inmediately or should I open some websites before sending logs?

**Comment by zebrum** [comment]
@adnage19  After enabling "record everything" you need to reproduce the problem and then send logs

**Comment by zebrum** [comment]
@adnage19 any updates on this?

**Comment by zebrum** [comment]
reopen if needed.
