### ISSUE TITLE
Make `pref.vpn.disable.reconfiguration` checked for all Android versions 7+

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1918]
It proved to be okay with all Samsung/Huawei devices and I don't see why would we need reconfiguration for other devices.

**Comment by carlylemiii** [comment]
@ameshkov - Naturally, I wanted to see what this does, so I checked it on my Pixel 2 XL. With it checked, if I turn WiFi on, the "LTE" never leaves my signal strength indicator, which normally means that WiFi isn't actually being used. It appears based on speed tests that my WiFi is indeed being used, so something seems mildly off here?

**Comment by Revertron** [comment]
@carlylemiii Android is capable to hold 2 connections simultaneously. Maybe, our reconfiguration messed with it :)

**Comment by TPS** [comment]
I think not just 2, if I understand Project Fi/Republic Wireless & the various system developer settings correctly: Depending on hardware, it might even be able keep each wifi (if multiple antennae/modules)  __&__ mobile data (SIMs) connection  open/running _simultaneously_! 😮

**Comment by carlylemiii** [comment]
@Revertron, are you saying "messed with" like it's a bad thing? Default behavior is *not* to hold on to LTE like that.

**Comment by ameshkov** [comment]
Let's see how it behaves in the beta version that comes this week. If there are any issues with it, please report.

**Comment by carlylemiii** [comment]
I just updated to the beta, and this didn't get checked for me. Is that expected because it was an upgrade and not fresh install?

**Comment by ameshkov** [comment]
> I just updated to the beta, and this didn't get checked for me. Is that expected because it was an upgrade and not fresh install?

Yeah, it must be checked on a fresh install (unless you have your settings restored from a Google backup)

**Comment by carlylemiii** [comment]
@ameshkov and that behavior (when checked, I mean) is expected and considered normal? I like to think of myself as techy, and I can only imagine others will be confused if LTE continues to show like I am :)

**Comment by ameshkov** [comment]
> @ameshkov and that behavior (when checked, I mean) is expected and considered normal? I'm confused by it, and I like to think of myself as techy, so I can only imagine others too will be confused if LTE continues to show :)

This may happen in one case only: if you changed this setting value manually prior to installing the update. In this case, we prefer not to override user's settings.

> so I can only imagine others too will be confused if LTE continues to show :)

Yeah, that we are about to see :). This decision is not final, I am not yet sure if this goes smoothly or if it cause troubles.

**Comment by carlylemiii** [comment]
FWIW, now that I'm on Pie (that sounds so unnatural, for some reason 🙂), having `pref.vpn.disable.reconfiguration` enabled does not keep LTE showing in the status bar when going from LTE to Wi-Fi. So the "issue" is gone for me. I figured if this was the default, I might as well have it enabled. :)

Last question, what does it do, exactly? I'm guessing this might help with the temporary system slowdown I'd experience when leaving my home and going from Wi-Fi to LTE?

**Comment by ameshkov** [comment]
> Last question, what does it do, exactly? I'm guessing this might help with the temporary system slowdown I'd experience when leaving my home and going from Wi-Fi to LTE?

It's simple: every time network changes, AdGuard restarts the VPN tunnel.
