### ISSUE TITLE
Traceroute and AdGuard.

### ISSUE THREAD

**Issue by redirectr00t** [AdguardTeam/AdguardForAndroid#1920]
I tried giving a traceroute terminal, with latest AdGuard Nightly set on VPN Mode and High Quality filter enabled, with AdGuard enabled I am not able to do any traceroute to any destination, I tried with more than one app, Ping Tools and Termux. It will stuck at for example:

traceroute 8.8.8.8

1: 172.18.11.218
          0.845 ms pmtu 9000
2: no reply

n+1: no reply 

I then went also into advanced settings and tried changing the mtu value to the lower extreme suggested. with same output.

The only effective way I found was ticking the option not route the traffic through AdGuard.

Is there some option I can tick to make traceroute working?

**Comment by ameshkov** [comment]
Yeah, that's basically by design.

The thing is that ICMP packets are getting routed into the VPN tunnel, but we cannot emulate them properly (Android does not provide us with necessary capabilities).

We are able to emulate ICMP packets used for ping, but traceroute is more complicated.

**Comment by ameshkov** [comment]
> Is there some option I can tick to make traceroute working?

The only way would be to disable AdGuard for the app executing the traceroute.
