### ISSUE TITLE
Пропадает интернет

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#1923]
Adguard 2.11.81, HTTPS, HTTP, качественная, фильтры по-умолчанию. Android 4.4.4., Nexus 5. Спокойно играю себе в игру и тут раз инет пропал и перезапуск защиты. Потом спустя некоторое время еще раз. У меня har логи и "записывать все" 
20:20-20:42 время https://ru.files.fm/u/qstjaqgf

**Comment by vozersky** [comment]
по всей видимости просто интернет пропал, соответственно защита перезапустилась

в любом случае, уже [2.12 ](https://static.adguard.com/android/nightly/adguard-2.12.60.apk) с новыми [core libs](https://adguard.com/ru/blog/introducing-corelibs/) лежит в nightly-канале, она сильно отличается, искать какие-то проблемы в 2.11 уже нецелесообразно, обновитесь :)

**Comment by ministr91** [comment]
@vozersky, нет, такое у меня бывало и раньше и только с включенным Adguard. Интернет у меня просто так не пропадает. Можешь логи глянуть? Может там есть серьезный баг
