### ISSUE TITLE
Unable to access internet with DNSCrypt enabled in AdGuard 2.12.60

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1924]
Switching from other servers to DNSCrypt blocks internet

### Steps to reproduce

1. Go to AdGuard > DNS
2. Enable DNS filtering
3. Switch to AdGuard DNS from the Secure DNS section

### Expected behavior

AdGuard works as expected, the internet access is not blocked

### Actual behavior

For some users, it gets blocked 

### Your environment

* Adguard version: 2.12.60
* Adguard filtering mode: VPN
* Device model: SM-G950, and others
* Operating system and version: 8.0.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by vozersky** [comment]
Can't reproduce.
Anyone? @zebrum @Alex-302 @altokarev

**Comment by Alex-302** [comment]
[adguard.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2110901/adguard.zip)

**Comment by sfionov** [comment]
@Alex-302 Do you have dnscrypt.log in your logs dump?

**Comment by Alex-302** [comment]
@sfionov no. adguard.log only. Tried few times.

**Comment by sfionov** [comment]
@Alex-302 Found it, there was an error in upgrade script from beta to the latest nightly

**Comment by DenLeo** [comment]
Обновлялся на ночную с бета-версии. Возникла проблема с ограничением доступа в Интернет при включении любого dnscrypt. Удалил adguard, скачал и установил ночную сборку, импортировал сохранненый файл с настройками adguard. Теперь все нормально, доступ в интернет есть.

**Comment by admitrevskiy** [comment]
Resolved

Testing instruction
1. Install AG beta-version
2. Enable DNS and choose any DnsCrypt server.
3. Start protection
4. Update to the latest nightly
5. Try to use internet with enabled Secure DNS (DnsCrypt)

Expected result:
Everything works fine
