### ISSUE TITLE
Moving certificate does not work with Magisk

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1928]
@nkartyshov please check it on one of our test devices.

```
"androidVersion" : "8.1.0 (sdk=27)",
"deviceName" : "manufacturer=Xiaomi model=Redmi Note 4 brand=Xiaomi version=8.1.0 security_patch=2018-06-05",
"kernelVersion" : "3.18.113-Feather",
```

User's rom:
https://forum.xda-developers.com/showpost.php?p=76851855&postcount=1459

**Comment by nkartyshov** [comment]
I cannot reproduce this problem. The certificate has been moved to the system store on Xiaomi redmi 4x without problems. Installed user's rom.

**Comment by ameshkov** [comment]
Relevant Magisk modules:
https://github.com/NVISO-BE/MagiskTrustUserCerts/releases

Relevant feature request:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1919

**Comment by ameshkov** [comment]
Also, users pointed out that AdGuard fails to detect a certificate after it's moved to the system store using these modules

**Comment by nkartyshov** [comment]
Fixed detect a certificate after it's moved to the system store using Magisk Module.

Testing instructions:
1. Install Magisk on the device
2. Download module: [MoveCert](https://forum.xda-developers.com/showpost.php?p=75835120&postcount=3039 ) or [MagiskTrustUserCerts](https://github.com/NVISO-BE/MagiskTrustUserCerts)
3. Install AdGuard certificate
4. Add module to the Magisk
5. Reboot device
6. Try to check certificate status

Expected result:
Certificate should be install to the system store
