### ISSUE TITLE
java.io.IOException 8.1.0 

### ISSUE THREAD

**Issue by redirectr00t** [AdguardTeam/AdguardForAndroid#1929]
Tester,
tested both on 05-2018, 06-2018 security patch update, contacted support sended them log, same situation on three devices with lineageOS 8.1.0 gts210vewifi, klte, zerolte,
[4_5848065699737502705.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2120254/4_5848065699737502705.zip)

Why the filters cannot be updated?

Adding log captured on lineageOS, I am available to provide more debug logs to help fix this problem on my devices.

@ameshkov Can you check the logs?

**Comment by ameshkov** [comment]
Connection to `filters.adtidy.org` times out:
`Error connecting to 104.20.10.222:443. Error: 1(Timed out)`
`Failed to connect to filters.adtidy.org/104.20.10.222:443`

Could you please disable filtering for the AdGuard app in the apps management and see if there's still an issue? Currently, AG is filtering its own connections (which is legit, but anyway).

**Comment by ameshkov** [comment]
Meanwhile, I filed a bug report to CoreLibs, I think I know what's causing this issue:
https://github.com/AdguardTeam/CoreLibs/issues/355

**Comment by redirectr00t** [comment]
Issue is fixed in  Nightly 2.12.60 I am capturing debug log and posting it here, also working certificate on June Security Update, this debug log is for device zerolte, I will submit debug log for the other 2 devices too if needed.
[adguard_logs_2.12.60_2006_1852.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2120307/adguard_logs_2.12.60_2006_1852.zip)
