### ISSUE TITLE
[Nightly] Cannot update to 2.12.74 from 2.12.60

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardForAndroid#1932]
### Behavior
The app simply downloads an "adguard.apk" file when I try to update it. The apk file appears to be corrupted, as it tapping on it opens a preview of the file instead of the installation window.

</details>

### Your environment

* Adguard version: 2.12.60
* Adguard filtering mode: VPN
* Device model: 2016 Pixel
* Operating system and version: Android 9
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by Eugene-Savenko** [comment]
@zefwef this is a known bug https://github.com/AdguardTeam/AdguardForAndroid/issues/1930
You can download the .60 release from here: https://agrd.io/android_nightly
