### ISSUE TITLE
Integrate a custom file picker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1935]
There're some cases when the system DocumentsProvider is missing. In order to handle these cases, we can integrate a custom file picker instead.

First of all, look for popular file picker libraries. It needs to be lightweight, it should be a fallback (use the default DocumentsProvider by default).

Please note, that we need it for two actions: `CREATE_DOCUMENT` and `OPEN_DOCUMENT`

**Comment by ameshkov** [comment]
Another option -- fallback to a dialog with a text input (path).

**Comment by ameshkov** [comment]
Tbh, I'd better choose a "fallback text input dialog" option

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
This feature is available for Android lower than KitKat with mounted external storage.
-Reinstall AG
-Try:
a) Export User Filters (Settings -> User Filter)
b) Import User Filters (Settings -> User Filter)
c) Export Settings (Settings -> General)
d) Import Settings (Settings -> General)
e) Export Logs (Settings -> Advanced)

Expected result:
All features are available with help of custom file picker.

Only files with required type are visible for each feature:
User filters: .txt
Settings: .json
Logs: .zip

Please, don't use emulator with API 17 and lower: there is a bug with external storage.
