### ISSUE TITLE
org.gamatech.androidclient.app

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#1936]
https://github.com/AdguardTeam/AdguardFilters/issues/18532

https://play.google.com/store/apps/details?id=org.gamatech.androidclient.app

App won't connect when HTTPS filtering is active.

**Comment by vozersky** [comment]
@zebrum pls try to repro

**Comment by vozersky** [comment]
without filters

**Comment by zebrum** [comment]
reproduced

**Comment by nkartyshov** [comment]
Fixed, https://github.com/AdguardTeam/HttpsExclusions/commit/a94370e0656f6109565f88ea2521727dcd74d216
