### ISSUE TITLE
NullPointer exception in the onTrafficChanged method

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1938]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.adguard.android.model.c.b()' on a null object reference
```

`StatisticsServiceImpl.java:221`

Most likely the issue happened due to `DeviceState.currentNetworkType` being null.

Details:
http://sentry.adguard.com/adg/adguard-android-rs/issues/5185/

**Comment by admitrevskiy** [comment]
Resolved

Testing instruction: the issue is hard to reproduce and it's the single one. Let's rely on testers feedback, and check sentry for similar issues.
