### ISSUE TITLE
App&Game 4PDA is broken by Adguard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#194]
Receiving app updates is broken when Adguard is enabled

**Comment by gshumihin** [comment]
Tested with app4pda v5.0 beta 8 and adguard v. 2.1.267, works fine.
https://www.dropbox.com/s/qddyt4tm61dltzk/2015-11-25%2011.54.36.png
https://www.dropbox.com/s/h4b9ids965yuntp/2015-11-25%2012.00.27.png?dl=0

**Comment by ameshkov** [comment]
Cannot reproduce
