### ISSUE TITLE
HTTPS filtering breaks bbm messenger

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1940]
@adguard-bot commented on [Thu Jun 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18120)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.bbm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.bbm)
### Comment
> Hi, when adguard is on bbm will not connect, as see in the screenshot. Once I pause adguard it connects immediately
> 
> samursell@gmail.com

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/skVywgv.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And The latest
AdGuard version: | 2.11.81
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Filters: | Mobile Ads,<br>Annoyances,<br>Simplified domain names,<br>English,<br>Anti-Adblock Killer | Reek,<br>Spyware,<br>Social media
Other extensions used: | None

---

@vozersky commented on [Fri Jun 22 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18120#issuecomment-399400041)

https://www.apkmirror.com/apk/bbm/bbm/bbm-300-3-16-119-release/

@zebrum check it pls

---

@zebrum commented on [Mon Jun 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18120#issuecomment-400005280)

reproduced.
if there is no ads we can exclude the app from filtering. 

---

@Alex-302 commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18120#issuecomment-400268861)

@vozersky @zebrum please don't forget about it.

**Comment by vozersky** [comment]
App contains ads, we should figure out, what domain to exclude. 

https://www.apkmirror.com/apk/bbm/bbm/bbm-300-3-16-119-release/

**Comment by nkartyshov** [comment]
Excluded this app from https filtering
