### ISSUE TITLE
Unable to play videos on chocotv.com.tw by chrome

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1941]
https://www.chocotv.com.tw/drama/9550/eps/1

It still doesn't work even if I already manually added chocotv.com.tw in the whitelist of HTTPS filtering.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oDkHGa2.png)
</details><br/>

I don't know if the solution is the same as what was reported in Adguard For Windows.
https://github.com/AdguardTeam/AdguardForWindows/issues/2264

PS: Need Taiwan IP for watching videos on chocotv.com.tw.
Thanks.

**Comment by ameshkov** [comment]
Stable or nightly AG?

**Comment by lancelot-moon** [comment]
v2.12.74η

Thanks.

**Comment by lancelot-moon** [comment]
It also provides Android app.
https://play.google.com/store/apps/details?id=com.chocolabs.app.chocotv&hl=zh_TW

If **not** adding chocotv.com.tw in the whitelist of HTTPS filtering, videos can be still normally played in its app.

The problem is in browsers.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #364](https://github.com/AdguardTeam/CoreLibs/issues/364) via [**ZenHub**](https://www.zenhub.com/)
