### ISSUE TITLE
Unable to visit a Taiwanese government's website, even afterwards AdGuard will crash while stopping protection.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1942]
AG v2.12.74η

gov.tw is Taiwanese government's domain.
In the past, I asked to add gov.tw in the whitelist of HTTPS filtering.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1705

I supposed that everything will be fine.
But I found that there are also problems for other Taiwanese government's websites.

Reproduction steps:
1. After enabling AG protection, visit the below website first.
https://www.mofa.gov.tw/AlliesIndex.aspx?n=0757912EB2F1C601&sms=26470E539B6FA395

2. Unable to connect to the website.
ERR_TIMED_OUT
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hcfsrS8.png)
</details><br/>

3. https://github.com/AdguardTeam/AdguardForAndroid/issues/1705
I went to use the Central Weather Bureau app.
In normal situation, it could import data because gov.tw was already in the whitelist of HTTPS filtering by default.
But it was no data.
It seems that there was something wrong in HTTPS filtering.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ruQm7f7.png)
</details><br/>

4. It spent about 2 minutes on stopping protection but finally AdGuard crashed.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oi2zQ58.png)
</details><br/>

Finally AdGuard crashed:
AdGuard had stopped running.
Please open the app again.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/P39EGik.png)
</details><br/>

I just replied the bug report to AdGuard Support at 21:48 on 26th June (GMT+8).
User ID: 1425202
Subject: [PREMIUM] [Adguard for Android] 程式錯誤報告 (bug report)
The attachment in my email is the log file.

Thanks.

**Comment by bug-killer** [comment]
[adguard_logs_2.12.74_2606_2145.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2137422/adguard_logs_2.12.74_2606_2145.zip)
^^^ log file

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #363](https://github.com/AdguardTeam/CoreLibs/issues/363) via [**ZenHub**](https://www.zenhub.com/)
