### ISSUE TITLE
Wrong encoding when switching the app to English on Nokia 6

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1943]
AdGuard shows some gibberish symbols instead of English when switching from default Russian localization to English on Nokia 6 w/ Android 8.1.0

### Steps to reproduce

1. Install AdGuard 2.11.81 or the latest nightly 2.12.82 on phone with non-English locale
2. Go to AdGuard > Settings > General > Language
3. Switch to English

### Expected behavior

AdGuard uses English localization

### Actual behavior

For some reason, localization is distorted as if it has wrong encoding

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/41966952-2010c894-7a09-11e8-99d8-51f036477548.png)

</details>

### Your environment

* Adguard version: 2.11.81, 2.12.82
* Adguard filtering mode: VPN
* Device model: manufacturer=HMD Global model=Nokia 6.1 brand=Nokia version=8.1.0
* Operating system and version 8.1.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by ameshkov** [comment]
А при чем тут адгард, на скриншоте настройки нокии

**Comment by Eugene-Savenko** [comment]
Блин. )
