### ISSUE TITLE
The app UI is distorted in Arabic

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1945]
Please examine the app UI and fix all the issues.

For instance, here's how the main screen looks like:

![dgsxmjhwsaadfr7](https://user-images.githubusercontent.com/5947035/41970950-59303cac-7a15-11e8-9bbf-d713d2d54e23.jpg)

**Comment by admitrevskiy** [comment]
Done

Testing instructions:
-Reinstall AG
-Change language to RTL (Arabic or Persian)
-Examine the UI

**Comment by zebrum** [comment]
@admitrevskiy 
General, Ad Blocker, Browsing security, Advanced screens there are still some problems with aligning

**Comment by admitrevskiy** [comment]
Fixed
