### ISSUE TITLE
com.appatomic.vpnhub

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1946]
@adguard-bot commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18844)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.appatomic.vpnhub](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.appatomic.vpnhub)
### Comment
Username: @Rakleed
> Adguard не даёт нормально подключиться к VPN. При отключении Adguard все нормально работает.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Hzry3zQ.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Ys4jhEH.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | 2.11.81
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
Filters: | Russian,<br>Mobile Ads,<br>Annoyances,<br>English,<br>Spyware,<br>Social media

---

@Rakleed commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18844#issuecomment-400407218)

При отключённом Adguard всё работает корректно.
1. ![screenshot_vpnhub_20180626-205156](https://user-images.githubusercontent.com/19418601/41930353-7c34b08a-7983-11e8-898b-bcab72121dd1.png)

2. ![screenshot_vpnhub_20180626-205201](https://user-images.githubusercontent.com/19418601/41930354-7c514ede-7983-11e8-9f1c-53f26f7769f8.png)

---

@Alex-302 commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18844#issuecomment-400409724)

Отключение фильтрации HTTPS помогает?

---

@Alex-302 commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18844#issuecomment-400409881)

@zebrum @vozersky гляньте плз.

---

@Rakleed commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardFilters/issues/18844#issuecomment-400433761)

@Alex-302 отключение фильтрации HTTPS не помогло. Проблема осталась.

**Comment by nkartyshov** [comment]
This is AdGuard error. We do not pause process if a third-party VPN was started. 
Issue https://github.com/AdguardTeam/AdguardForAndroid/issues/1954
