### ISSUE TITLE
Add a new parameter for reporting tool integration

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#1948]
The new parameter is `android.dns`, it can hold values of  `true` or `false`, and it should reflect the current state of DNS filtering toggle.

Add this parameter to the string the app sends to the reporting tool.

**Comment by vbagirov** [comment]
Please also add `android.version` parameter that passes Android OS version as a text.

**Comment by nkartyshov** [comment]
Added

**Testing instructions:**
Try sending a review about missed ads.

**Expected result:**
All html form field should be filled

**Comment by vbagirov** [comment]
@nkartyshov works, closng the issue.

**Comment by nkartyshov** [comment]
**Testing instructions:**

1. Install AdGuard
2. Got to Send feedback screen
3. Select Missed Ad or tracker
4. Fill out the web form

**Expected result:**
All fields of the form about the app has filled out
