### ISSUE TITLE
Periscope app is broken - can't play video

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#195]
It seems the problem with VPN - video can't start with disabled all filters. There are no problems with proxy mode and enabled filters

**Comment by ameshkov** [comment]
Unfortunately the only way I see is to add this app to ad blocking exclusions.

**Comment by Bohdan-SUP** [comment]
"Запустил перископ, онлайн трансляции грузит и грузит. Нажал разъеденить адгуард и сразу включилась трансляция. через немного включается адгуард и трансляция переходит в режим загрузки"
Логи тут - BVE-303-49539

**Comment by ameshkov** [comment]
@gshumihin please check it with the latest version.

**Comment by gshumihin** [comment]
I cannot reproduce this issue.
Tested with this settings:
-Adguard ver. 2.1.359
-VPN filtering mode
-english, russian, spyware, social, mobile filters
-high-quality filtering method

**Comment by ameshkov** [comment]
The same on my side, everything is good since the app is in exceptions list.
