### ISSUE TITLE
[Nightly] Search feature doesn't work in User filter, v. 2.12.95

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1957]
Clicking on the magnifying glass in AdGuard > Settings > User filter does not open the search

### Steps to reproduce

1. Update to 2.12.95
2. Import any filter to the User filter
3. Tap on the magnifying glass

### Expected behavior

The search tab is opened 

### Actual behavior

It makes the burger menu flicker and does not start the search

<details><summary>Screenshot:</summary>

![image](https://uploads.adguard.com/screencast_07-03-18-48.gif)

</details>

### Customer ID 
1146569, reproduced on the emulator

### Your environment

* Adguard version: 2.12.95
* Adguard filtering mode: VPN
* Device model: LENOVO model=Lenovo TB2-X30F
* Operating system and version 6.0.1
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? none

**Comment by admitrevskiy** [comment]
Resolved

Testing instructions:
-Reinstall AG
-Go to `Settings -> User Filter`
-Try to use search feature

Expected result:
Search feature works fine
