### ISSUE TITLE
Investigate what effects complete firewall wifi blocking has on Android OS

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#196]
When wholesale blocking wifi via toggling the "Allow Wifi" shield in firewall, the Android OS shows blocked as well.  Shouldn't this be excluded from Wifi blocking?  I understand the mobile data blocking (even if available via OS settings, rather obscure option) & ad-blocking exclusion (mostly bug-testing, from my experience), but turning off wifi is a highly accessible function separate from airplane mode, & turning it off for Android OS seems to have strange side effects.

Steps to reproduce:
1. Block all wifi via firewall → Toggle "Allow Wifi" from Green to Red.
2. Allow wifi for any app → Toggle app's own wifi in firewall option from Red to Green.
3. Notice on main firewall screen that main "Allow firewall shield" is now green, _but_ Android OS still shows wifi ___blocked (Red)___!
4. Go into Android OS option under firewall → All options are grayed out. :confounded: 

What I was trying to setup originally was a default blacklist environment.  (If you all are familiar with [RequestPolicy Continued](https://requestpolicycontinued.github.io/) or even [Noscript](https://noscript.net/), you understand the idea — permission denied by default, but can be granted either permanently or temporarily on case-by-case basis.)  I'm stymied, however by the Android OS blocking (unknown side-effects) & the wifi general block going green if _any_ app is allowed.

Logs needed?  Comments?

**Comment by ameshkov** [comment]
It just signals you that something is enabled, nothing more.

Firewall settings are always "per-app" and these three buttons are just like "group actions"

> turning it off for Android OS seems to have strange side effects

What are these effects?

**Comment by TPS** [comment]
Things like OS update fails intermittently, although that's via a separate (system) app that _is_ allowed.  But, really, should Android OS be _allowed_ to block via firewall?  & should/could a default blacklisted environment be workable via AG'S firewall?

**Comment by ameshkov** [comment]
In fact Android OS is not a real app, but a system traffic. Making it grayed out is a bad solution because in fact you can block it's traffic.

To understand how it works you'd better look at how Adguard's firewall configuration looks like. There is a field with default permissions set (these three main buttons) and a number of per-app permission sets.

By default there are no per-app permissions so every app uses default set.

So let's see what you've done.

1. You've disabled Wi-Fi in default set. Default button goes green to show that Wi-Fi is enabled for some apps, but **in fact default permission is OFF**.
2. You've enabled Wi-Fi for some particular app.
3. The problem with Android OS traffic is that it does not have per-app permissions set and is controlled by the default set.

Confusing, right? I think that to make it transparent we should add a "per-app" permissions set for Android OS.

**Comment by TPS** [comment]
So, if I'm understanding you, letting the Android OS be individually settable would allow my default blacklist idea to work, but shouldn't cause any strange side effects?

Also, the behavior of your point 1 loses me:  which is the overall default for a newly installed app when the 2 don't match?  The group shield/state at top *or* the shield/state of Android OS?

P.S.: Happy U.S. Thanksgiving! :fireworks:

**Comment by ameshkov** [comment]
> So, if I'm understanding you, letting the Android OS be individually settable would allow my default blacklist idea to work, but shouldn't cause any strange side effects?

In fact - no. At least until we implement self learning mode: https://github.com/AdguardTeam/AdguardForAndroid/issues/115

> Also, the behavior of your point 1 loses me: which is the overall default for a newly installed app when the 2 don't match? The group shield/state at top or the shield/state of Android OS?

Per-app has higher priority.

> & what's the practical difference between toggling OS wifi/mobile via system vs. firewall?

If you toggle it on OS level, app will be aware that network is not accessible. When you disable it on firewall level - it won't be (until it gets the error when trying to get online)

**Comment by ameshkov** [comment]
> P.S.: Happy U.S. Thanksgiving! :fireworks:

Thank you! You too:)

**Comment by TPS** [comment]
>Per-app has higher priority.
So, since the default per-app is set by the group shield/state at top, that should prevail? 

Also, if Android OS has its own per-app permission set, what _should_ it limit, actually?  As far as I figure, if its blocked, it should block _everything_, but it's then also possible via firewall to allow an app while blocking the OS.…  Should that mean something specific?

**Comment by ameshkov** [comment]
> So, since the default per-app is set by the group shield/state at top, that should prevail?

Didn't get the question. Specific per-app always prevails over the default.

> Also, if Android OS has its own per-app permission set, what should it limit, actually? As far as I figure, if its blocked, it should block everything, but it's then also possible via firewall to allow an app while 

Now when you set default permission to "block everything" this will block Android OS and you can do nothing to change that until you change the default permission again.

**Comment by TPS** [comment]
>Didn't get the question. Specific per-app always prevails over the default.

I understand that, for a new app, _just installed_, the group shield/state at top governs what the default per-app state will be, correct?
>this will block Android OS

In the scenario I mentioned far above, where Android OS is blocked, but (let's say) nothing else is via per-apps settings, _what_ precisely won't function?

**Comment by ameshkov** [comment]
> I understand that, for a new app, just installed, the group shield/state at top governs what the default per-app state will be, correct?

No. In fact you can't see these default permissions and the group state can be misleading.

So, if you have disabled mobile for all and then enable it for one app, group state will be green, while default is red.

> In the scenario I mentioned far above, where Android OS is blocked, but (let's say) nothing else is via per-apps settings, what precisely won't function?

All traffic sent from the system user accounts.

For instance, it may break default video/audio player because they use reserved system account to download media file.

The full list:
```
        RESERVED_UIDS.put(0, new NetApplicationInfo("root", false));
        RESERVED_UIDS.put(1000, new NetApplicationInfo("system", false));
        RESERVED_UIDS.put(1001, new NetApplicationInfo("radio", false));
        RESERVED_UIDS.put(1002, new NetApplicationInfo("bluetooth", false));
        RESERVED_UIDS.put(1003, new NetApplicationInfo("graphics", false));
        RESERVED_UIDS.put(1004, new NetApplicationInfo("input", false));
        RESERVED_UIDS.put(1005, new NetApplicationInfo("audio", false));
        RESERVED_UIDS.put(1006, new NetApplicationInfo("camera", false));
        RESERVED_UIDS.put(1007, new NetApplicationInfo("log", false));
        RESERVED_UIDS.put(1008, new NetApplicationInfo("compass", false));
        RESERVED_UIDS.put(1009, new NetApplicationInfo("mount", false));
        RESERVED_UIDS.put(1010, new NetApplicationInfo("wifi", false));
        RESERVED_UIDS.put(1011, new NetApplicationInfo("adb", false));
        RESERVED_UIDS.put(1012, new NetApplicationInfo("install", false));
        RESERVED_UIDS.put(1013, new NetApplicationInfo("media", false));
        RESERVED_UIDS.put(1014, new NetApplicationInfo("dhcp", false));
        RESERVED_UIDS.put(1015, new NetApplicationInfo("external_storage", false));
        RESERVED_UIDS.put(1016, new NetApplicationInfo("vpn", false));
        RESERVED_UIDS.put(1017, new NetApplicationInfo("keystore", false));
        RESERVED_UIDS.put(1018, new NetApplicationInfo("usb_devices", false));
        RESERVED_UIDS.put(1019, new NetApplicationInfo("drm", false));
        RESERVED_UIDS.put(1020, new NetApplicationInfo("available", false));
        RESERVED_UIDS.put(1021, new NetApplicationInfo("gps", false));
        RESERVED_UIDS.put(1022, new NetApplicationInfo("deprecated", false));
        RESERVED_UIDS.put(1023, new NetApplicationInfo("internal_media_storage", false));
        RESERVED_UIDS.put(1024, new NetApplicationInfo("mtp_usb", false));
        RESERVED_UIDS.put(1025, new NetApplicationInfo("nfs", false));
        RESERVED_UIDS.put(1026, new NetApplicationInfo("drm_rpc", false));
        RESERVED_UIDS.put(2000, new NetApplicationInfo("shell", false));
        RESERVED_UIDS.put(2001, new NetApplicationInfo("cache", false));
        RESERVED_UIDS.put(2002, new NetApplicationInfo("diag", false));

        /* The 3000 series are intended for use as supplemental group id's only. */
        /* They indicate special Android capabilities that the kernel is aware of. */
        RESERVED_UIDS.put(3001, new NetApplicationInfo("net_bt_admin", false));
        RESERVED_UIDS.put(3002, new NetApplicationInfo("net_bt", false));
        RESERVED_UIDS.put(3003, new NetApplicationInfo("af_inet", false));
        RESERVED_UIDS.put(3004, new NetApplicationInfo("net_raw", false));
```

**Comment by ameshkov** [comment]
While discussing it with you, I start understanding how confusing the current firewall UI is.
Thank you:)

**Comment by TPS** [comment]
>No. In fact _you can't see_ these default permissions and the group state can be misleading.

Maybe that's kind of a problem to resolve re: this UI.  I understand that it's a support nightmare, in all certainty, to allow these defaults to be changed, but perhaps they should be readily visible in a _read-only_ state to let us users know where the ground floor is, so to speak.
>The full list:

Wow, thanks!  I'll have to ruminate upon these & rethink my black/whitelisting plan.  Based upon all you've written, I think it's probably not possible without an explicit toggle via an option.…
>While discussing it with you, I start understanding how confusing the current firewall UI is.  Thank you :)

Ah, now you start to understand my nefarious hidden motivation for beating this issue to death. ;)  You're quite welcome, but also thank _you_ for having it out with me to the bitter end. ☺


Since this now counts (impressively) asked-&-answered,  I shall close, unless there's something here you'd like to keep open as a reminder.…
