### ISSUE TITLE
Print information about removed HTML elements to the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1960]
Currently, we don't do it because of extra heavy allocations that would be caused by it. I guess we should do it, but we need to be careful and to introduce a low-level setting that enables printing this information.

Also, the HTML element is different from the regular filtering log items -- instead of an URL, you would need to display the HTML code.

@admitrevskiy we need to discuss this task before you start doing anything.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions.
-Reinstall AG
-Go to `Settings –> Advanced –> Low level settings`
-Enable `pref.removed.html.log`
-Surfing the web

Expected result:
Elements that was removed by html rules will be printed to the filtering log
