### ISSUE TITLE
Cannot update filters or the adguard app itself on both Android and Mac platforms on wifi

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardForAndroid#1961]
### Description
For some reason, I can only check for app updates and filter updates on Android while connected to mobile data, but not wifi. The same issue is occurring on macOS; if I create a mobile data hotspot from my phone and connect my laptop to it, the app and filters will update, but on wifi they will not.

This appears to be a widespread issue:
https://forum.adguard.com/index.php?posts/169896/
https://forum.adguard.com/index.php?posts/169872/

### Your environment

* Adguard version: 2.12.95
* Adguard filtering mode: VPN
* Device model: 2016 Pixel
* Operating system and version: Android 9
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
Could you please do `traceroute filters.adtidy.org` in the terminal and post the output here?

**Comment by ameshkov** [comment]
Also, we've changed the cloudflare settings a bit, could you please re-test?

**Comment by zefwef** [comment]
It's working now, thank you!

**Comment by ameshkov** [comment]
Great, thanks for alarming us about it!
