### ISSUE TITLE
Rework the main screen UI

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1963]
The main screen sketch (Button states, dark theme, etc)
https://www.dropbox.com/s/ipvdemduddohtyx/main.sketch?dl=0

### Comments

https://uploads.adguard.com/up04_s2a4j_main.sketch.png

Bottom message depends on the app state:

* Premium: nothing there
* Free: text=`Free version`, button=`GET PREMIUM`
* Trial: text=`Trial period\n7 days left`, button=`BUY NOW`

Graph:
https://uploads.adguard.com/up04_s7z0k_main.sketch.png

Date periods: 24h (24 hours), 7d (7 days), 30d (30 days), ∞ (All the time)

Button states:
https://uploads.adguard.com/up04_8uw3i_main.sketch.png

Please note that there is a new "Error" state.

**Comment by lancelot-moon** [comment]
Honestly, I more like the now power button for enabling/disabling AG.
