### ISSUE TITLE
New onboarding images/styles

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1965]
Sketch:
https://www.dropbox.com/s/rq2b7trp4ao7g95/on%20boarding.sketch?dl=0

**Comment by ameshkov** [comment]
Reopened, the onboarding design needs to be updated

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/6163ab58-a722-44d0-a79d-67f78d197bb9

В общем тут надо с помощью лотти воткнуть джейсонки
http://airbnb.io/lottie/android/android.html#getting-started

Порядок такой: экран загружается, анимация на первом кадре, нажатие на кнопку = старт анимации. Конец анимации = стоп на последнем кадре + переход на следующий экран (слайд влево). Нажатие на кнопку "нет спасибо" - просто слайдим экран влево


[jsons.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2604624/jsons.zip)

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/c42ab0e5-db0f-45bd-97b1-9046bfc6bb3d
