### ISSUE TITLE
Start using ProcessHealthStats instead of scanning proc-stat for calculating AdGuard's own battery usage

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1967]
**Reported Issue**

* Current java private API in use:
* Currently, the only option to retrieve your own app battery usage is to parse /proc/*/stat and calculate it using the current device's power profile values.

**An answer from an Android dev:**

> The data we use to compute battery use is available to apps here https://developer.android.com/reference/android/os/health/ProcessHealthStats (and https://developer.android.com/reference/android/os/health/package-summary has numerous other data that is relevant as well).  I think that should cover the use case you are describing; please re-open with an explanation if it doesn't.

`MEASUREMENT_SYSTEM_TIME_MS` and `MEASUREMENT_USER_TIME_MS` seems to be exactly what we need.

**Comment by ameshkov** [comment]
It shows negative CPU time on @vozersky phone

**Comment by ameshkov** [comment]
Same thing on my side, it can become negative for some hours

**Comment by ameshkov** [comment]
The value is still incorrect, now its much higher than it should be. Test what you do and compare with the result from proc/stat parsing before considering it fixed

**Comment by nkartyshov** [comment]
Fixed.

Test investigation:
1. Install AdGuard
2. Enable Secure DNS service
3. Use the Internet or apps for about an hour or two

Expected result:
The value of using the cpu in the battery statistics should not be huge
