### ISSUE TITLE
User filter setting page is not responding

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#1968]
### Steps to reproduce

1.Open AdGuard
2.Open filter settings page

### Expected behavior

Everything seems to be in order
### Actual behavior

AdGuard application is not responding

### Customer ID 
1921883
### Your environment

* Adguard version:2.12.95
* Adguard filtering mode: VPN
* Device model: F-04K Fujitsu DOCOMO 
* Operating system and version 8.1.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Not detected

**Comment by nkartyshov** [comment]
Cannot reproduce. But in the log file a lot of problem with corelibs and I think this could have affected the operation of the app.

@TheHasagi  Please ask the user if he has already this problem?

**Comment by Eugene-Savenko** [comment]
The customer requested a refund some time ago and removed the app.
