### ISSUE TITLE
AG for Android v2.12.102η will crash when searching "adguard" on google with language and time conditions by chrome.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1969]
As the title, it will crash when searching "adguard" on google with language and time conditions by chrome.

https://i.imgur.com/tM1ReVP.png

B/R

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #381](https://github.com/AdguardTeam/CoreLibs/issues/381) via [**ZenHub**](https://www.zenhub.com/)
