### ISSUE TITLE
Extended Tasker API: proxy settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1972]
What we need is to expose the following methods:

1. Set a default proxy (not add it, just choose one).
2. Start/stop the proxy module

We should also extend the article on the website:
https://kb.adguard.com/en/android/solving-problems/tasker

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
- Reinstall AG
- Try this features: 
https://kb.adguard.com/en/android/solving-problems/tasker#action_outbound_proxy
https://kb.adguard.com/en/android/solving-problems/tasker#action_proxy_server
