### ISSUE TITLE
Android OS in the filtering log

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#1973]
### Steps to reproduce

1.Open adguard 
2.Go to the Filtering log
### Expected behavior

Everything seems to be in order
### Actual behavior

See screenshots

<details><summary>Screenshot:</summary>

![prob1](https://user-images.githubusercontent.com/37797229/42683707-ca63c456-8696-11e8-8cff-6801f9be47d5.jpg)
![prob2](https://user-images.githubusercontent.com/37797229/42683718-d19e0588-8696-11e8-921f-883eeb079891.jpg)
![em](https://user-images.githubusercontent.com/37797229/42683745-e02ef4fe-8696-11e8-8653-19087dc15649.jpg)

</details>

* Adguard version: 7.0
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel) HUAWEI P10 lite
* Operating system and version (e.g. Android 7.1.2) EMUI 5.1.1

**Comment by ameshkov** [comment]
Steps to reproduce: curl to the local proxy port

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Try to reproduce the issue with cURL
-Reinstall AG
-Try to reproduce the issue with cURL

Expected results
No more empty events from Android OS in the filtering log
