### ISSUE TITLE
Unable to start receiver com.adguard.android.ui.widget.WidgetProvider: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1980]
http://sentry.adguard.com/adg/adguard-android-rs/issues/6152/

The crash is provoked by some other app but anyway, can't we just protect ourselves and catch exceptions there?

Needs to be done in both 2.12 and 3.0 branches.

**Comment by ameshkov** [comment]
Still happens:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6152/?query=is:unresolved

**Comment by admitrevskiy** [comment]
@ameshkov 
As i see, this crash happens in `2.12.113` version, but issue was fixed in `2.12.114`
I hope that it was solved and there will be no more crashes caused by this issue in `2.12.114+`
