### ISSUE TITLE
Could not login in Millennium app while AdGuard filters its data

### ISSUE THREAD

**Issue by driversti** [AdguardTeam/AdguardForAndroid#1981]
### Steps to reproduce

1. Install [Bank Millennium](https://play.google.com/store/apps/details?id=wit.android.bcpBankingApp.millenniumPL)
2. If you don't have an account just press "Contact"
3. You should see the notification like "There is no internet connection"

### Expected behavior

Successed login (if you try it) or opened page for contact the bank (if you have pressed "Contact")
### Actual behavior

Failed. There is no internet connection

<details><summary>Screenshot:</summary>
Can not provide a screenshot, because the app does not allows it

</details>

### Customer ID 

1800076
### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: Local VPN
* Device model: OnePlus 6 (A6003)
* Operating system and version: Android 8.1.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? [Hot VPN Pro](https://play.google.com/store/apps/details?id=com.pro.bestvpn.hotvpn) (not in use)

**Comment by vozersky** [comment]
please exclude `wit.android.bcpBankingApp.millenniumPL` from filtering, it's a banking app

**Comment by vozersky** [comment]
@driversti thanks a lot for reporting this issue!

**Comment by driversti** [comment]
@vozersky hi. I did it, but I'm not sure it's a propriate solution

**Comment by vozersky** [comment]
this is a temporary solution, we will add a general exclusion for all users in the next build
