### ISSUE TITLE
FedEx tracking does not work with Adguard turned on

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardForAndroid#1983]
### Steps to reproduce

1. Visit FedEx.com, with all filters turned off but Adguard turned on.
2. Attempt to track 123456789012 with Adguard on. It will display "Unfortunately we are unable to retrieve your tracking results at this time. Please try again later."
3. Try again with Adguard off and it will work.

### Your environment

* Adguard version: Latest nightly
* Adguard filtering mode: VPN
* Device model: (e.g. Google Pixel) Pixel 2016
* Operating system and version (e.g. Android 7.1.2) 9
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by vozersky** [comment]
reproduced

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/CoreLibs #404](https://github.com/AdguardTeam/CoreLibs/issues/404) via [**ZenHub**](https://www.zenhub.com/)
