### ISSUE TITLE
Add this Download Manager to default browser list?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#199]
[RT Software Studio's Download Manager](https://play.google.com/store/apps/details?id=com.rtsw.easydownloader) perhaps should be added to the default browser list, as the latest update now ["provides an embedded web browser to find content and capture downloads](http://www.rtsoftwarestudio.com/)."  I'm aware this may be a bit of a technical challenge until #34 lands, because downloads often require certain advertising support.

**Comment by ameshkov** [comment]
Done
