### ISSUE TITLE
HTTPS filtering defaults appear inconsistent

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#1990]
Fresh install of Adguard on an Android 8.1 device.  Adguard had never been installed on that device.  HTTPS filtering *not* enabled.

In `App Details`, `HTTPS filtering` is enabled by default for some apps, but disabled for other apps.  There is no indication as to why, and it initially looks like a bug.

It turns out this is because some apps are flagged as 'This app does not trust user certificates, so HTTPS filtering can break down its secure connections'.  But this detail is hidden from the user if HTTPS filtering is currently not enabled.

Even when HTTPS filtering is disabled, this detail should be made apparent to the user in order to prevent the appearance of a bug.  (My initial report was that this was a default settings bug.)

*Testing Adguard v2.11.81*

**Comment by ameshkov** [comment]
Here's the explanation:
https://adguard.com/en/blog/android-nougat-release-and-what-does-it-mean-for-adguard-users/

**Comment by Gitoffthelawn** [comment]
@ameshkov Thank you.  I did not know that.  So for apps designed for Android 7.0 or later, DNS blocking and ad server blocking is still working, correct?

What exactly is lost then by not having the HTTPS certificate recognized by most modern apps?

**Comment by ameshkov** [comment]
> @ameshkov Thank you. I did not know that. So for apps designed for Android 7.0 or later, DNS blocking and ad server blocking is still working, correct?

Yeah.

> What exactly is lost then by not having the HTTPS certificate recognized by most modern apps?

Without HTTPS filtering we know what's the target domain and we know the app that's trying to create a connection so we can apply some rules like that: 

* `||graph.facebook.com^$app=package.name.goes.here`

But we don't know the exact resource being loaded, and we cannot apply cosmetic rules as it requires modifying the content of the pages. So the rules like these won't work:

* `###banner`
* `||graph.facebook.com/network_ads`

**Comment by Gitoffthelawn** [comment]
That's very helpful.  Thank you Andrey.
