### ISSUE TITLE
The toggle button icon missing from the notification drawer on Huawei P10 Premium

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1996]
### Expected behavior

Users see the shield icon when opening the drawer

### Actual behavior

It's either an empty circle (on the latest nightly) or a curvy square (on 2.11.81)

<details><summary>2.11.81:</summary>

![image](https://user-images.githubusercontent.com/15856304/43194086-3b0fd0a6-900a-11e8-9b13-d171f79e3f14.png)

</details>

<details><summary>2.12.x:</summary>

![image](https://user-images.githubusercontent.com/15856304/43194120-53fb9b68-900a-11e8-9234-6976259e75d8.png)

</details>

### Your environment

* Adguard version: is specified above
* Adguard filtering mode: VPN
* Device model: HUAWEI VTR-L29
* Operating system and version: 8.0.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by vozersky** [comment]
firmware issue? unfortunately, the only huawei device I've got is nova with android 7, and i can't reproduce this issue on it

**Comment by ameshkov** [comment]
Just in case, how does the outbound proxy tile look like?

The difference between them is that the main tile's image is a vector drawable, while the proxy tile's image is a png.

**Comment by vozersky** [comment]
One more report:

Oneplus 6, android 8.1

![image](https://user-images.githubusercontent.com/17472907/43522192-3da853fa-95a1-11e8-917d-b4d6dfccd866.png)
