### ISSUE TITLE
Crash: Attempt to invoke virtual method 'android.support.v4.app.NotificationCompat$Builder android.support.v4.app.NotificationCompat$Builder.setContentIntent(android.app.PendingIntent)' on a null object reference

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1997]
https://sentry.adguard.com/adg/adguard-android-rs/issues/6692/?query=is:unresolved

Happened right after the "StopProtection" task.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions: No need, this bug is very difficult to reproduce.
