### ISSUE TITLE
Add Adblock Browser to the browsers list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#20]
http://4pda.ru/forum/dl/post/6679392/Adblock_Browser_v1.0.0_build_2015081632.apk

**Comment by TPS** [comment]
Proper GPlay link (testing opt-in only):

https://play.google.com/store/apps/details?id=org.adblockplus.browser

**Comment by Revertron** [comment]
Added.

**Comment by TPS** [comment]
Thanks! ☺
