### ISSUE TITLE
Assistant works only in proxy filtering mode on Android 4.4.2 in VPN

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#2002]
Assistant is not shown on default notification settings

**Comment by admitrevskiy** [comment]
Resolved.

**Comment by vozersky** [comment]
still no notification
and lots of crashes on protection start (on test device)

**Comment by vozersky** [comment]
could be a specific samsung issue, we should figure out the origin of those crashes first
