### ISSUE TITLE
Protection is not restarted after modifying HTTPS whitelist/blacklist

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2007]
This one needs to be fixed in both 2.12 and 3.0 branches.

## STR

1. Go to HTTPS filtering
2. Open blacklist or whitelist
3. Add a new item

### Expected:
Protection is restarted automatically (applyNewSettings needs to be called)

### Actual:
Protection is not restarted

**Comment by admitrevskiy** [comment]
Resolved.
