### ISSUE TITLE
It doesn't show the translation of SDN filter in the green notification.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2008]
There are 2 problems when I click the button for updating.

1. AG v2.12.136η showed that SDN filter was updated in the green notification, but I didn't check it in ad filters.
(I enabled DNS setting.
I don't know if there is the association.)

2. In the notification of updates, the name of SDN filter should show its translation (ex: Traditional Chinese), but it showed English.

Update the screenshot.
I mean the green notification.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KMYDpFK.png)
</details><br/>

It showed Simplified Domain Names filter at that time.
It should show its translation, not English.

**Comment by lancelot-moon** [comment]
@Ameshkov
I got the screenshot.
The period of updating SDN filter is 2 days.
Reproduction steps:
1. Uncheck SDN filtet in ad filters.
2. Enable DNS filtering.
3. Check for updates.
4. The 2 issues will occur.
https://i.imgur.com/KMYDpFK.png

**Comment by lancelot-moon** [comment]
Hi,

If checking SDN filter in ad filters and then checking for updates, it can normally show the translation of SDN filter (簡化域名過濾器) in the green notification.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/621DRnR.png)
</details><br/>

Just a comparison.

**Comment by admitrevskiy** [comment]
@lancelot-moon Hi!
Is this issue still occurs in 3.0?

**Comment by lancelot-moon** [comment]
It seems to be solved in v3 nightly.
