### ISSUE TITLE
Add an option to add several "Custom" DNS servers 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2009]
Currently, a user can have a single manually configured DNS server. We'd better change the layout and users add as many custom servers as they like.

**Comment by lancelot-moon** [comment]
Adding the numbers of custom DNS servers by users and improving the layout of DNS are also suggested here.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1621

**Comment by artemiv4nov** [comment]
I think this idea is not so actual now, I'll close the task.
