### ISSUE TITLE
Protection doesn't restart when changing mode of HTTPS filtering 

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2011]
### Steps to reproduce

1. AdGuard side-settings - HTTPS Filtering
2. Change HTTPS filtering mode to 'blacklist'

### Expected behavior
Protection was restarted, new setting was applied

### Actual behavior
Protection wasn't restarted, setting wasn't applied

**Comment by admitrevskiy** [comment]
Resolved
