### ISSUE TITLE
Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://adguard.com/

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2019]
See the details of a crash here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6972/?query=is:unresolved

**Comment by nkartyshov** [comment]
Fixed

**Comment by nkartyshov** [comment]
Fixed.

Testing instructions:
1. Uninstall browsers
2. Open AdGuard
3. Go to license key status
4. Click to the Manage license

Expected result:
Show toast with generic error message
