### ISSUE TITLE
View=DecorView@329d6f2[Sprawdzanie aktualizacji] not attached to window manager

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2020]
Crash reports:

* https://sentry.adguard.com/adg/adguard-android-rs/issues/6982/?query=is:unresolved
* https://sentry.adguard.com/adg/adguard-android-rs/issues/7013/?query=is:unresolved

Related SO question (check steps to reproduce there):
https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash#

**Comment by admitrevskiy** [comment]
Resolved.

Steps to reproduce:
-Go to device's `Developer options `
-Enable `Do not keep activities`
-Open AG
-Start one of the following operations and close the app while they are executed (while you see progress dialog):
  Main screen:
    - Check filter updates
    - Import User Rules
  User Rules:
    - Export User Rules
    - Send Feedback message
  Apps Management:
    - Bulk changes in `Apps Management`
  Proxy Settings:
    - Check proxy connection
  License Status:
    - Activate premium
    - Restore purchase
    - Refresh License status

Testing instructions:
-Reinstall AG
-Try to reproduce
-Don't forget to disable `Do not keep activities` =)
