### ISSUE TITLE
HTTPS whitelist entries not saving

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#2026]
### Steps to reproduce

1. Create new HTTPS whitelist entry.
2. Item goes to top of list.
3. Exit screen, and enter settings again.
4. Entry wasn't saved.

### Expected behavior
Save it.

### Actual behavior
Doesn't save. 

</details>

### Your environment

* Adguard version: 2.12.140
* Adguard filtering mode: VPN
* Device model: Google Pixel 2 XL
* Operating system and version: Android 8.1.0
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by vozersky** [comment]
hm, can't reproduce

**Comment by ameshkov** [comment]
I cannot reproduce either. @admitrevskiy any idea what could it be?

**Comment by admitrevskiy** [comment]
@ameshkov can we make a test build with extra logging of all steps for this operation to see what's going wrong?

**Comment by carlylemiii** [comment]
@admitrevskiy I do not see it at all.

**Comment by admitrevskiy** [comment]
@carlylemiii Hi!
Please try the latest nightly and let me know if something goes wrong.

**Comment by carlylemiii** [comment]
Looks good :)

**Comment by admitrevskiy** [comment]
Thanks!
