### ISSUE TITLE
[Nightly] 2.12.142 Nest app fails to connect on local Wifi

### ISSUE THREAD

**Issue by FlyPigsFly** [AdguardTeam/AdguardForAndroid#2028]
### Steps to reproduce

1. Install Nest from Play store
2. Ensure Nest application option "Route app traffic through adguard" is checked. Ad blocking option is checked. Https filtering option for Nest is off.
3. Be connected to same wifi network as nest device.
4.

### Expected behavior

You should be able to login to nest servers

### Actual behavior

Nest app never connects and at some point will require you to enter login credentials again.

<details><summary>Screenshot:</summary>

</details>

Interestingly, if you use the nest app on a mobile network, this issue does not occur. Only affects Wifi.

The work around solution when on local wifi is to disable "Route app traffic through AdGuard" option.

### Your environment

Non rooted
Google Pixel 2
Android 8.1.0
July 2018 Security patches

**Comment by FlyPigsFly** [comment]
Issue still present with latest Android P beta as well

**Comment by FlyPigsFly** [comment]
[Adguard.pdf](https://github.com/AdguardTeam/AdguardForAndroid/files/2260044/Adguard.pdf)
Here is a record everything log

**Comment by ameshkov** [comment]
Deleted the log file, please don't share it publicly -- send it to devteam at adguard.com if necessary.
Not this one, though, I've already downloaded it.

Regarding the Nest app, most likely the issue is caused by the mere fact of routing it's traffic through the VPN tunnel. In Android when app is routed through a VPN, it cannot accept incoming connections.

To make sure that that's the case, please try disabling "Ad Blocking" for the app. Does the issue go away?

**Comment by FlyPigsFly** [comment]
As mentioned above, for Nest app to work on local wifi you must NOT route traffic through AdGuard. If an app is routed through a VPN and it can't accept incoming connections, why does using a mobile network like Verizon allow Nest app to connect properly when "routed through AdGuard?"

**Comment by ameshkov** [comment]
I assume that the app behavior is different when it's on the same network and there might be an attempt to establish a direct connection between the device and the app.

On the other hand, AdGuard by default excludes LAN from the VPN so, in theory, it does not have to mess with Nest's local connection.

Let's try to check it.

Could you please export two sets of AdGuard "record everything" level logs: one on Wi-Fi and the other one on the mobile network. Use "settings -> advanced -> export logs" to export the recorded data and send it to `devteam at adguard.com`.

**Comment by FlyPigsFly** [comment]
Logs sent
