### ISSUE TITLE
Consider using "material" icon style instead of the current one with a gradient (for both app icon and widget)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#203]
http://www.google.ru/design/spec/style/icons.html#icons-product-icons
TODO: We also should change widget style, make it look like that new material icon

**Current icons are below:**
![512x512-1](https://cloud.githubusercontent.com/assets/5947035/12289960/e5bd6b6a-b9ef-11e5-837d-f19c29b26af5.png)
![128x128](https://cloud.githubusercontent.com/assets/5947035/12289962/e7c27eaa-b9ef-11e5-8268-cebb49565bcd.png)
![256x256](https://cloud.githubusercontent.com/assets/5947035/12289963/e9c7c6a6-b9ef-11e5-9082-7378a86dfe22.png)
![app_icon](https://cloud.githubusercontent.com/assets/5947035/12289965/eb8f7ba0-b9ef-11e5-8f5a-5aed692292a5.png)

**Comment by TPS** [comment]
I really ___hate___ Material design, so —1 :-1: from me, but maybe make this default based on current environment pref?  I.e., if current OS theme is Material (maybe detect via OS/kernel version #), then use Material icon, else use current?  Is it possible to choose a theme from _within_ the app?

___N.B.___:  This may have an effect on what animation is used for #123.…

**Comment by ameshkov** [comment]
@TPS there's no choice anyway, AG will look strange among all other apps (which are will be material rather soon).

**Comment by TPS** [comment]
Only on OS versions where this is enforced.  Those of us on 4.4.x will _never_ have forced Material,  & AG would look weird if it were.

P.S.: [Another VERY relevant conversation I was part of re: this issue with a VERY different app may be enlightening.…](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/512).

**Comment by ameshkov** [comment]
But material does not mean monochromatic! 

Does this look bad?
![style_logos_product_intro_definition](https://cloud.githubusercontent.com/assets/5947035/11598197/829d0190-9ad1-11e5-81be-0a8a13fd9d8d.png)

**Comment by TPS** [comment]
Ah, yes, we're talking about the desktop ("product") icons.  You've already got Material-ready notification ("system") icons! (Though I won't use those because I can't use them to differentiate state changes, which is what all that discussion in the previous link is about.) My mistake! :confused:

**Comment by ameshkov** [comment]
New icons:
https://www.dropbox.com/sh/bw4r0zw4y6d7hgp/AAAT_VEqs5Ff-ot-VQAY_PLra?dl=0

**Comment by TPS** [comment]
I _do_ like these!  Did you mean to include shadowing _inside_ the shield, though?  Or should the shield itself be lighted & raised (by shadowing) above the rounded-off square field?

**Comment by ameshkov** [comment]
> Did you mean to include shadowing inside the shield, though? Or should the shield itself be lighted & raised (by shadowing) above the rounded-off square field?

We were looking at google icons while designing it:
http://clip2net.com/s/3t7AzqX

**Comment by ameshkov** [comment]
New widget icons:
https://www.dropbox.com/sh/wqex23xqtwb552y/AAC4vcwbz1KfTyErHnBCtF7ka?dl=0

**Comment by Sandivisi** [comment]
why not using this icon?

**Comment by TPS** [comment]
@Sandivisi As noted above, this is already scheduled to be accomplished before v. 2.5 (gold) milestone is officially released.  They're only at v. 2.5.70 beta, & [have been working on an important new feature](https://github.com/AdguardTeam/AdguardForAndroid/releases).  Just wait; it'll all be good. ☺

**Comment by TPS** [comment]
@ameshkov Note: before officially closing this, don't forget #151.…  The last icon-set released seem to be all the same shape, but just different colors.  It'll be good if that round badge in the lower-right changes shape in all states (off, off←→on, on), though _I_ think it should be 4 states (off, off→on, on, on→off), if possible.

**Comment by ameshkov** [comment]
@TPS oh, thank you, missed #151 

But I don't like the idea of different icons. Color indication is a common way to show current power state.
I suppose we can simply use gray instead of red.

**Comment by TPS** [comment]
But the _point_ of #151 is that, with [so _many_ kinds of color-blindness](http://www.color-blindness.com/2010/03/09/types-of-color-blindness/), _any_ color scheme other than outright grayscale is likely unreliable, right? (BTW, that linked site has [a pretty nifty tool](http://www.color-blindness.com/coblis-color-blindness-simulator/) to view images how color-blind folks do.  Very eye-opening! :wink:)

**Comment by ameshkov** [comment]
Great tool!

However this tools that even with current colors it is easy to distinct ON and OFF states (intermediate state is not so good though)

Try uploading this picture:
![logos](https://cloud.githubusercontent.com/assets/5947035/14355684/8151dc36-fcea-11e5-840e-5c91b8a1a1af.png)

**Comment by TPS** [comment]
Using the tool with above pic:
* Red-Blind/Protanopia -> Off & On look almost same
* Blue-Blind/Tritanopia -> Intermediate & Off look the same
* Monochromacy/Achromatopsia -> Off blends into background, & is quite similar to On

To test oneself _very_ informally, try [this simple test](http://enchroma.com/test).

**Comment by ameshkov** [comment]
@TPS check out new icons:

![96](https://cloud.githubusercontent.com/assets/5947035/14428857/8b3280e0-0003-11e6-9a93-7094e6593452.png)
![96](https://cloud.githubusercontent.com/assets/5947035/14428858/8cce019a-0003-11e6-93b6-e0054fbf4656.png)
![96](https://cloud.githubusercontent.com/assets/5947035/14428861/8ed86e94-0003-11e6-95d5-686c55de2603.png)

**Comment by Snether** [comment]
ameshkov  Добрый день я оставлял заявку на альтернативную схему для дальтоников. На самом деле цвет не имеет значения будь то синий, красный, зеленый или полное отсутствие цветовосприятия. Мы можем ориентироваться только по значкам. Вот к  примеру как может видеть человек с отсутствием цветовосприятия. Маленькие черно белые значки на маленьком дисплее телефона плохо различимы. Прошу Вас прислушаться. Спасибо. 
![img-2016-04-12-23-07-43](https://cloud.githubusercontent.com/assets/18426647/14470595/cc99c79a-0103-11e6-91aa-5b0db08fb058.jpg)

**Comment by ameshkov** [comment]
@Snether ну вот в таком размере то они неплохо различимы. Выключенное состояние получено фактически инверсией цвета. Как оно будет смотреться на телефоне - вопрос, который еще предстоит выяснить когда мы это в бета-версию включим.

Есть еще вариант индикации, когда мы будем использовать сам логотип. Например, в выключенном состоянии менять "галку" на восклицательный знак внутри логотипа.

Но в таком случае нам нужно сделать виджет внешне отличающимся от иконки приложения.

**Comment by Snether** [comment]
Еще если позволите. Вот к примеру что я хочу до вас донести. Сделал в паинте как смог))). Восклицательный знак галочка и крестик. Я вместе с дальтониками будем безумно благодарны.
![img-2016-04-12-23-07-43](https://cloud.githubusercontent.com/assets/18426647/14471412/e8979f54-0107-11e6-834f-5da686c0f1a4.jpg)

**Comment by ameshkov** [comment]
@Snether окей:) Я попрошу дизайнера еще поработать над этой иконкой.

**Comment by TPS** [comment]
@ameshkov I was going to ask you to get your color-blind users to chime in, but @Snether beat me to it.  Thanks, @Snether!

**Comment by ameshkov** [comment]
Here are new icons:

![96](https://cloud.githubusercontent.com/assets/5947035/14558910/f4066638-030d-11e6-91dc-f20a0683c19f.png)
![96](https://cloud.githubusercontent.com/assets/5947035/14558912/f5eecd46-030d-11e6-8916-99187ed416ea.png)
![96](https://cloud.githubusercontent.com/assets/5947035/14558914/f825d1ae-030d-11e6-84ad-d5b07433399a.png)

**Comment by TPS** [comment]
Yes! WFM! @Snether?

**Comment by Snether** [comment]
То, что надо. Спасибо.

**Comment by Revertron** [comment]
Done.

**Comment by ameshkov** [comment]
@Revertron new icon looks good.

Can't say the same about new widget.

**What should be done:**
1. You should change it's size, make it look exactly like the app icon.
2. Widgets states are wrong now, ON and OFF are swapped.


![screenshot_20160419-011453](https://cloud.githubusercontent.com/assets/5947035/14621565/79ff8330-05cc-11e6-9366-721ff984ee03.png)

**Comment by TPS** [comment]
_(@ameshkov Just FYI, my AG proxy crashes & restarts about 50% of the time loading the [above image](https://cloud.githubusercontent.com/assets/5947035/14621565/79ff8330-05cc-11e6-9366-721ff984ee03.png).)_

**Comment by ameshkov** [comment]
@TPS i'd like to see the log then

**Comment by ameshkov** [comment]
@Revertron much better, but widget and app icon should be on the same line (at least in the default launcher):
<img width="435" alt="2016-04-19_1941" src="https://cloud.githubusercontent.com/assets/5947035/14647554/090ca5c2-0667-11e6-8e09-355c77f0d91d.png">

**Comment by TPS** [comment]
@ameshkov @Revertron While adjusting the app & widget icons, do keep in mind the #123 shortcut, so perhaps not to duplicate effort later.

@ameshkov After a reboot, I can't duplicate [the large image crash @ will](https://github.com/AdguardTeam/AdguardForAndroid/issues/203#issuecomment-211721632), so maybe it was a transient thing?

**Comment by ameshkov** [comment]
Moving widget issue to a separate task: #481 

For now we will use the current icon (until we have a normal widget design ready).

**Comment by ameshkov** [comment]
@TPS 
> @ameshkov After a reboot, I can't duplicate the large image crash @ will, so maybe it was a transient thing?

Everything is possible. I can say for sure only if I see the log:)
