### ISSUE TITLE
Change the target SDK level to 28 (Android P)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2030]
Here's what we need to change it.

### [Behavior changes](https://developer.android.com/preview/behavior-changes)

1. Review the non-SDK APIs we use (if there's anything left): https://developer.android.com/preview/restrictions-non-sdk-interfaces
2. Start using [StrictMode.detectNetwork](https://developer.android.com/reference/android/os/StrictMode.ThreadPolicy.Builder#detectNetwork())
3. With Android P, you cannot start an activity from a non-activity context unless you pass the intent flag FLAG_ACTIVITY_NEW_TASK
4. Apps that target Android P or higher and use foreground services must request the FOREGROUND_SERVICE permission. 
5. Android P apps should honor the private DNS APIs. In particular, apps should ensure that, if the system resolver is doing DNS-over-TLS, any built-in DNS client either uses encrypted DNS to the same hostname as the system, or is disabled in favor of the system resolver.

### [Security changes](https://developer.android.com/preview/features/security-behav)

1. Network TLS enabled by default. Do we need to set `cleartextTrafficPermitted` to true (for importing filters and such)?
2. Per-app SELinux domains. We might need to re-test the way the IPv6 redirection works in root+proxy mode.

### Features we must use

1. Display cutouts support.
2. Make sure that we use backup encryption.

### DNS privacy

https://developer.android.com/about/versions/pie/android-9.0-changes-28#dns-privacy

**Comment by yochananmarqos** [comment]
SDK 27 = Android 8.1 Oreo
SDK 28 = Android 9.0 Pie

**Comment by ameshkov** [comment]
@yochananmarqos ops, my bad :)
