### ISSUE TITLE
Importing a backup from the stable version breaks DNS settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2034]
### Steps to reproduce

1. Import the backup file (PM'd it to @admitrevskiy)
2. Try using AG, DNS resolution won't work

### Expected behavior
It must work.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Export settings from 2.11 and 2.12 versions:

a) With selected regular DNS server
b) With selected DnsCrypt server
c) With selected DnsCrypt server that is not already exists 
d) With selected outbound proxy
e) With list of outbound proxies

Try all possible combinations of app version. dns(crypt) and outbound proxy settings

- Reinstall AG
- Try to import settings

Expected result:
Valid settings importing is successful
Invalid setting (not existed dnscrypt server, for example) are not imported
