### ISSUE TITLE
Crash in the SettingsUserFilterFragment$UserFilterRulesAdapter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2035]
Details:
https://sentry.adguard.com/adg/adguard-android-rs/issues/7044/?query=is:unresolved

**Comment by admitrevskiy** [comment]
Resolved.

Steps to reproduce:
-Go to Developer option -> Enable `Do not keep activities`
-Go to User Filter
-Add many rules
-Start `Enable/Disable all` operation
-Close the app while executing
-App will crash

Testing instructions:
-Reinstall AG
-Try to reproduce
