### ISSUE TITLE
"I agree with Terms" button is not visible if scale is enlarged in Android settings

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#2036]
Screenshot: https://uploads.adguard.com/vbagirov3talf.png

Device specs: https://uploads.adguard.com/vbagirov6bt7p.png

AG version: 2.12.140beta

Rooted, Magisk

Reference: https://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=75664227

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-You need device with small screen
-In device options choose the lagrest font
-Reinstall AG and clear data if it's not `clear` install

Expected behavior:
-EULA and crash reporting agreement texts are scrollable, the buttons are visible.
