### ISSUE TITLE
com.scannerradio

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2038]
@adguard-bot commented on [Thu Aug 02 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20552)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.scannerradio](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.scannerradio)
### Comment
> Your Adguard app is blocking tge audio stream from that app. It also does it on other apps that stream audio like music, news, and like the one I mentioned that streams live police radio.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/cAarGy6.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | 2.12
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Experimental,<br>German,<br>Japanese,<br>Dutch,<br>Spanish/Portuguese,<br>Mobile Ads,<br>Safari,<br>Turkish,<br>Simplified domain names,<br>French,<br>EasyList,<br>Bulgarian list,<br>EasyList China,<br>EasyList Czech and Slovak,<br>EasyList Dutch,<br>EasyList Germany,<br>EasyList Hebrew,<br>EasyList Italy,<br>EasyList Lithuania,<br>Latvian List,<br>Liste AR,<br>Liste FR,<br>ROList,<br>RU AdList,<br>Wiltteri,<br>Adblock Polska,<br>EasyPrivacy,<br>Icelandic ABP List,<br>Norsk adblockliste,<br>void.gr,<br>Fanboy's Annoyances,<br>Fanboy's Social Blocking List,<br>ABP Japanese Filters,<br>Czech List,<br>Filtros Nauscopicos,<br>hufilter,<br>Peter Lowe's list,<br>Schacks Adblock Plus liste,<br>Xfiles,<br>Adblock Warning Removal List,<br>Malware Domains,<br>Prebake,<br>Spam404,<br>Anti-Adblock Killer | Reek,<br>RU AdList: Counters,<br>RU AdList: BitBlock,<br>ABPVN List,<br>Fanboy's Enhanced Tracking List,<br>Adblock & uBlock polish,<br>Adblock & uBlock polish cookies,<br>Estonian List,<br>ChinaList+EasyList,<br>CJX's Annoyance List,<br>Polski social filtr,<br>Adblock-Persian list,<br>Fanboy's Swedish,<br>Korean Adblock List,<br>Fanboy Anti-Facebook List,<br>Fanboy's Vietnamese,<br>List-KR,<br>xinggsf,<br>I don't care about cookies,<br>FanboyEspanol,<br>Easylist Spanish,<br>KAD - Przekrety,<br>Juvander's Adblock List for Finland,<br>ROLIST2,<br>Iranian,<br>road-block,<br>AdBlock Protector List (Incompatible with Adguard),<br>Adblock & uBlock polish filter - Adguard supplement,<br>Fanboy's Anti-thirdparty Fonts,<br>BarbBlock,<br>Fanboy's Cookiemonster List
Other extensions used: | lookout anti-malware

**Comment by Alex-302** [comment]
This app is not working with disabled HTTPS filtering and disabled filters. URL exclusions(`$document`) does not help.

**Comment by nkartyshov** [comment]
Issue moved to [AdguardTeam/CoreLibs #433](https://github.com/AdguardTeam/CoreLibs/issues/433) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nkartyshov** [comment]
It's bug in the CoreLibs.
Workaround: Excluding an application from ad blocking.
