### ISSUE TITLE
Flash players freeze and show various errors with enabled Adguard

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#204]
Flash players like Steam player (https://play.google.com/store/apps/details?id=com.valvesoftware.android.steam.community) don't work properly. Errors range from player to player. From nothing (frozen frame wherever it is at on timeline) to unsupported device, infinite buffering, etc

QNZ-188-68319

**Comment by ameshkov** [comment]
@gshumihin please test this

**Comment by gshumihin** [comment]
Tested with latest build. Cannot reproduce it. Tried Steam, Firefox and Dolphin browser, videos played normally, without freezing or infinite loading.

**Comment by ameshkov** [comment]
@gshumihin please send the latest build to user and ask if it's good with that new version.

If it is still bad, we will need full logs of the issue.
But this time we'll need the whole file, not just a feedback message (as log is trimmed there).

Possible log file locations are listed in the end of the article:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android

**Comment by vbagirov** [comment]
No response from user, will close for now.
