### ISSUE TITLE
Adguard Never start on restarting the phone.

### ISSUE THREAD

**Issue by razz100** [AdguardTeam/AdguardForAndroid#2040]
Hi

Why this issue is not being fixed? I have tried the latest beta. Before that I was using the final version. The issue is every time I restart my device or turn off and then restart in both the cases Adguard does Not restart with the OS. I have to turn it on manually every time always. 

Why no focus on fixing the above issue? It has been the issue for so long.

I'm using Samsung J5, OS Marshmallow. 

Thanks 

Regards

**Comment by Rakleed** [comment]
I have the same problem on OnePlus 3, Android 8.1.0, LineageOS.

**Comment by andronov-alexey** [comment]
+1 on Le X527 Android 6.0

**Comment by ameshkov** [comment]
Guys, please check if your devices are listed here, and if any solution from that article helps:
https://kb.adguard.com/en/android/solving-problems/background-work

**Comment by razz100** [comment]
Hey!

Why did you closed the thread without my reply? I have tried the solution given in the thread but it did not work. I request you to kindly open the thread for further discussion and solutions.

Thanks

**Comment by Rakleed** [comment]
Я бы мог записать LogCat, если бы вы подсказали, как это сделать, т. к. приходится перезагружать устройство.

**Comment by razz100** [comment]
This is a major issue request you to open it. Adguard does not restart no matter what I do. This has to be fixed.

**Comment by andronov-alexey** [comment]
Seems like the issue persists on customized android operating systems (e.g. EUI on my Le X527, MIUI on xiaomi etc.)
To solve the issue you should manually allow AdGuard to launch (`Settings -> Permissions ->Allow AdGuard to auto launch`)
P.S. I also turned on usage access for AdGuard which is used by firewall activities and is turned off by default (`Settings -> Finderprint&Password ->Other security options -> Apps with usage access -> AdGuard -> On`)
