### ISSUE TITLE
HTTPS whitelist entries can't be deleted if there is a request in search box

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#2041]
### Steps to reproduce

1. Open HTTPS whitelist
2. Use search to find any domain name.
3. Delete this domain from search result without clearing the search box.

### Expected behavior
Domain has been successfully deleted

### Actual behavior
Domain is still in the list

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2026 there should be some connection to this one :)

**Comment by admitrevskiy** [comment]
Resolved.
