### ISSUE TITLE
AdGuard does not use the fallback DNS server when the primary server times out

### ISSUE THREAD

**Issue by andronov-alexey** [AdguardTeam/AdguardForAndroid#2042]
Frequently (1-2 times a day) I cannot establish connection to any site on my Android device with adguard running.
According to adb logs it seems like DNS server 217.8.224.10 is down but we still trying to connect to it
```
18:02:50.430 [cached-pool-1-thread-5987] DEBUG com.adguard.android.filtering.b.h - DNS id=10060645 Sending DNS request to /217.8.224.10:53
18:02:51.194 [cached-pool-1-thread-5933] DEBUG com.adguard.android.filtering.b.j - DNS id=10060613 Cannot process DNS request due to class java.net.SocketTimeoutException:null
```
After disabling and enabling adguard protection all works fine (because after restart was chosen different server - 176.103.130.131)
```
18:03:43.854 [cached-pool-1-thread-5996] DEBUG com.adguard.android.filtering.b.h - DNS id=10060735 Sending DNS request to /176.103.130.131:53
18:03:43.951 [cached-pool-1-thread-5996] DEBUG com.adguard.android.filtering.b.h - DNS id=10060735 Received a response from the upstream. Length=78
```
I've attached the log file ([adguard.log](https://github.com/AdguardTeam/AdguardForAndroid/files/2274076/adguard.log)) where:
- before 18:03 I'm unsuccessfully trying to connect to several sites
- after 18:03 I restart adguard protection and internet started working

Test environment:
* Adguard filtering mode: VPN
* Device model: Le X527
* Operating system: Android 6.0.1 (Not rooted)
* [state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/2274078/state.txt)

**Comment by ameshkov** [comment]
Thank you!

@nkartyshov the problem is that AG does not use the fallback upstream address in this case.
