### ISSUE TITLE
Manually added HTTPS exceptions are not applied in 2.12.140

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2043]
Whitelisted websites are still signed with AdGuard Personal CA

### Steps to reproduce

1. Go to AdGuard > Menu > HTTPS filtering
2. Add an exception (google.com.ua in my case) and make sure it's saved, restart the protection
3. Open Chrome and visit the whitelisted website

### Expected behavior

When clicking on the Lock icon > Details, you see it signed with Google Internet Authority cert

### Actual behavior

It's signed with AdGuard Personal CA, while websites added to the exceptions by default are properly whitelisted

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/43940865-52ba9c82-9c7a-11e8-937e-01c73ae3fc8d.png)

![image](https://user-images.githubusercontent.com/15856304/43940884-68994b0c-9c7a-11e8-830a-9fdf761a9633.png)

</details>

### Your environment

* Adguard version: 2.12.140
* Adguard filtering mode: VPN
* Device model: HTC One
* Operating system and version 5.0.2
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? none

**Comment by Eugene-Savenko** [comment]
It works if you add www.google.com.ua

**Comment by admitrevskiy** [comment]
Looks like it's CoreLibs issue: https://github.com/AdguardTeam/CoreLibs/issues/437

**Comment by admitrevskiy** [comment]
Resolved in https://github.com/AdguardTeam/CoreLibs/issues/437
