### ISSUE TITLE
Online Radio Box app streaming does not work when AdGuard is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2047]
The app:
http://onlineradiobox.com/android

The report by @FadeMind:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2024#issuecomment-410205987

**Comment by zebrum** [comment]
reopen if this is not [CL problem](https://github.com/AdguardTeam/CoreLibs/issues/433)
