### ISSUE TITLE
Improved Automation Notifications

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#2049]
_N.B.: This simply replicates https://github.com/AdguardTeam/AdguardForAndroid/issues/1896#issuecomment-401515216, as [requested](https://github.com/AdguardTeam/AdguardForAndroid/issues/1896#issuecomment-412352004), & https://github.com/AdguardTeam/AdguardForAndroid/issues/1896#issuecomment-402159972._

> Allow an `extra` to modify behavior of that green toast that pops-up, so it can, i.e., operate silently _[per a particular configured intent]_, or display no more than once an hour, or, more advanced, [iff](https://en.m.wikipedia.org/wiki/If_and_only_if) it affects state (e.g., if using `start`, toast only shows whenever AG isn't _already_ started).

> For those using the previous/legacy version:  Popup a dialog (I think a toast is insufficient) in AG to the effect of "[You're using our old/deprecated version of automation!  Update now to our free, secure, more versatile version!](https://kb.adguard.com/android/solving-problems/tasker)" whenever an old-style intent is received/detected.  (I think it's silently ignored now.)

**Comment by ameshkov** [comment]
Postponed, v3.1 is supposed to be a hotfix release.

**Comment by TPS** [comment]
Thanks for not forgetting about this.…  It's really the # 1 wish I've left in AG. 🙇🏾‍♂️

**Comment by TPS** [comment]
@ameshkov, @vozersky, @Revertron, &c:  What happened to the _existing_ option to turn off these automation toasts?  Or did I miss the implementation of this RFE?

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-To disable Automation toasts add `quiet:true` as additional EXTRA for intent
