### ISSUE TITLE
Add an option to make notifications soundless OR without vibration

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#205]
User feature request, ticket ID: CEI-318-23315

Also there is a similar request to disable vibration for these notifications:
http://forum.xda-developers.com/showpost.php?p=64554446&postcount=498

**Comment by ameshkov** [comment]
Planned it on release 2.5.

**Comment by Revertron** [comment]
We disabled vibration for notifications.
