### ISSUE TITLE
Hangs when cancel changes in bulk changes of apps management

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2056]
### Steps to reproduce

1. Go to Apps management -> Bulk changes
2. Press Cancel button

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/44191001-e909c080-a131-11e8-9578-dfab864a0eaa.png)

</details>

### Your environment
* Adguard version: the last nightly
* Adguard filtering mode: VPN
* Android 5.1.1
* Rooted

**Comment by nkartyshov** [comment]
Fixed

**Comment by nkartyshov** [comment]
Test investigation:
1. Open Apps management
2. Open Bulk Change dialog
3. Click to the cancel button

Expected result:
The progress dialog should close
