### ISSUE TITLE
A challenge to back to Google Play. A light version of AdGuard.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2059]
@ameshkov 

Face the competition.
Introduce the collection of Android adblockers. (One is only for Windows.)
https://www.ptt.cc/bbs/Android/M.1508556573.A.B8F.html

Will you want to challenge to back to Google Play?
I don't mean the content blocker for Samsung browser and Yandex browser.

Some apps on Google Play install user certificate for only browsers.
And establish a fake VPN for simple system-wide blocking (DNS filtering).
Lumen Privacy Monitor:
https://tinyurl.com/qjqyvbn

I really like the interface of AG Pro for iOS v2.
Try to push AdGuard Pro v2 (no filter subscription) + DNSCrypt v2 to Google Play.
Well, maybe also name the google play version as AdGuard Home.
Restrict the certificate of AdGuard Home for only browsers, not for general apps.
Maybe Google will allow AdGuard to back to Google Play.

DNSCloak is the first DNS changer with DNSCrypt v2 on Apple app store.
Now, it seems that there is no DNS changer with DNSCrypt v2 on Google Play.
It's your chance.

AdGuard team paid the cost of design for AdGuard Pro for iOS v2.
But Apple already doesn't allow its updates.
So push AdGuard Home (the interface of AdGuard Pro v2 with DNSCrypt v2 but no filter subscription) to Apple app store and Google Play.

**Comment by ameshkov** [comment]
> Will you want to challenge to back to Google Play?

We don't want to play games with Google and Apple.

> DNSCloak is the first DNS changer with DNSCrypt v2 on Apple app store.
> Now, it seems that there is no DNS changer with DNSCrypt v2 on Google Play.
> It's your chance.

Why would we do this? AdGuard is superior to simple DNS changing apps, there's no need to spend extra time on implementing something just to get to GPlay.
