### ISSUE TITLE
[Beta] High quality doesn't work as intended. It worked the same way as Simplified.

### ISSUE THREAD

**Issue by remewer** [AdguardTeam/AdguardForAndroid#2060]
### Steps to reproduce

1. Set AdGuard setting to High quality
2. Enable AdGuard VPN/proxy then browse the web

### Expected behavior
Ads should be blocked and spaces removed. Google ads aren't blocked, for example. For NYTimes, ads are blocked but spaces aren't removed. 

### Actual behavior
High quality setting worked the same as Simplified mode when I tried both. 

Tried VPN/proxy mode, enabled/disabled DNS and HTTPS filtering, filter lists, same problem. HTTPS certificate already moved to system store.

Cleared data, re-configured settings. Worked for the first time but problem persists after a reboot. Clearing data every reboot fixes the problem, but I'm not doing that.

Downgraded to stable, now working perfectly. 

<details><summary>Screenshot:</summary>

Beta:
https://imgur.com/a/JFVSATq

Stable:
https://imgur.com/a/KmyHzVE

</details>

### Customer ID 

1784190

### Your environment

* Adguard version: 2.12.140
* Adguard filtering mode: VPN / Proxy(manual) (tried both) 
* Device model: Samsung Galaxy A5 2016
* Operating system and version: Android 7.0
* Rooted or not: rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed: none

**Comment by ameshkov** [comment]
> HTTPS certificate already moved to system store.

That's the problem. In the current beta version, there is a mistake with handling the certificate moved to the system store. This mistake will be resolved in the next beta.
