### ISSUE TITLE
Please localize the language of the warning of browsing security.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2064]
As the title, it's English.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/2sLADtU.png)
</details><br/>

Please tell where to translate them.
And then apply the translations.

**Comment by sfionov** [comment]
Sorry, these pages are part of new filtering engine, but CoreLibs localization is not public yet. 
We're working to use external localizations of these pages.
I've created task to track it: https://github.com/AdguardTeam/CoreLibs/issues/447

**Comment by aalpatkina** [comment]
Hi @lancelot-moon 
You can find these strings in 'AdGuard Browser Extension' project

http://adguard.oneskyapp.com/admin/project/dashboard/project/13698
