### ISSUE TITLE
Add joey for reddit to browser list

### ISSUE THREAD

**Issue by neodada** [AdguardTeam/AdguardForAndroid#2067]
Add joey for reddit to browser list
https://play.google.com/store/apps/details?id=o.o.joey #

**Comment by vozersky** [comment]
Why? It's a reddit app, not a browser.

**Comment by neodada** [comment]
Then why relay added?
https://github.com/AdguardTeam/AdguardForAndroid/issues/1426

Joey contains a internal browser like relay does.

**Comment by vozersky** [comment]
Good point, didn't see it, soz :)

**Comment by admitrevskiy** [comment]
Done.

**Comment by zebrum** [comment]
not added to  pref.enforce.https.filtering

**Comment by ameshkov** [comment]
@zebrum does it support https filtering?

**Comment by zebrum** [comment]
@ameshkov nope. ok, then it shouldn't be in there )
