### ISSUE TITLE
Предложение по улучшению 2

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#2070]
Хотелось бы видеть это в новой версии:
о возможности модифицировать http\https трафик (речь о том что таким костылем можно было бы реализовать простые дополнения в браузерах, где этих самых дополнений вообще нет - например в хроме)

**Comment by vozersky** [comment]
Объясните, что имеется в виду.

**Comment by byaka** [comment]
речь о том, чтобы на все html страници вставлять указанный пользователем контент - например ссылку на скрипты и стили. поскольку в хроме на андроиде отсутствует поддержка дополнений, через такой костыль можно частично это решить. для простых расширений этого было бы достаточно.

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/34
