### ISSUE TITLE
DNS over TLS  doesn't work with running AdGuard 

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2075]
### Steps to reproduce

1. Write Cloudflare's 1.1.1.1 DNS over TLS service adress 1dot1dot1dot1.cloudflare-dns.com at Network setting 
2. Connect to 1dot1dot1dot1.cloudflare-dns.com
3. Run Adguard.

### Expected behavior
DNS over TLS should work

### Actual behavior
Doesn't connect with running Adguard, automatically connect back after AG shout down.

<details>

![image](https://user-images.githubusercontent.com/41899455/44480158-3ebafd00-a64b-11e8-8cf3-3f29f3e3b901.png)

![image](https://user-images.githubusercontent.com/41899455/44480296-8f325a80-a64b-11e8-98a7-708664ba6860.png)

</details>

* Adguard version: 2.12
* Device model: Google Pixel
* Operating system and version Android 9

**Comment by lucasban** [comment]
This is not limited to Cloudflare, it happens with any DNS over TLS provider

**Comment by zebrum** [comment]
@karina-archazh need to check with other VPN app, for example Tunnel Bear.

**Comment by karina-archazh** [comment]
This issue repeats with Windscribe VPN and Tunnel Bear VPN as well.

**Comment by zebrum** [comment]
Maybe Android issue.

**Comment by ameshkov** [comment]
Confirmed to be an Android bug. Filed an issue to their repo, let's wait now:
https://issuetracker.google.com/issues/119878172
