### ISSUE TITLE
The Battery Warner app does not appear in the AdGuard – Apps management

### ISSUE THREAD

**Issue by Yevhen1996** [AdguardTeam/AdguardForAndroid#2078]
### Steps to reproduce

1. Download Battery Warner from Google Play here: https://play.google.com/store/apps/details?id=com.laudien.p1xelfehler.batterywarner&hl=en
2. Open AdGuard – Apps Management – Search 
3. Type in searching field Battery Warner

### Expected behavior
The Battery Warner app should appear in the AdGuard – Apps management

### Actual behavior
The Battery Warner app does not appear in the AdGuard – Apps management

### Customer ID 

2326912

### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: VPN (auto)
* Device model: Vertex Impress_Lion_4G
* Operating system and version: Android 7.0.0
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by vozersky** [comment]
Hi.
This app doesn't request `network access`, that's why it is not listed in Apps management.

![image](https://user-images.githubusercontent.com/17472907/44543143-6b3c4b00-a717-11e8-9263-a72b33cfa5db.png)
