### ISSUE TITLE
Reporting tool issue on latest Beta 2.12.187 (reproduced on Nightly)

### ISSUE THREAD

**Issue by Elenve** [AdguardTeam/AdguardForAndroid#2079]
### Steps to reproduce

1. Open the application
2. Go to the Feedback tab
3. Turn the device horizontally 
4. The issue s reproduced

### Expected behavior

Being able to enter and select info

### Actual behavior

The screen is frozen when turned horizontally

<details><summary>Screenshot:</summary>

![screenshot_20180824-151256](https://user-images.githubusercontent.com/17320558/44585534-6201bb80-a7b5-11e8-9500-e4699a0f186d.png)
![screenshot_20180824-151842](https://user-images.githubusercontent.com/17320558/44585537-6201bb80-a7b5-11e8-9d67-4f766ca84879.png)

</details>

### Your environment

* Adguard version: beta 2.12.187
* Operating system and version Android

**Comment by zebrum** [comment]
@KozelElena what is the device model? we can't repro the issue, but found out another bug )

**Comment by Eugene-Savenko** [comment]
It's `manufacturer=Xiaomi model=Redmi Note 3 brand=Xiaomi version=6.0.1`

**Comment by zebrum** [comment]
@Eugene-Savenko @KozelElena can you record a video maybe? I can't really understand what is the problem.

**Comment by zebrum** [comment]
reopen if needed
