### ISSUE TITLE
Send feedback doesn't save screen state after rotating

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2080]
### Steps to reproduce

1. go to the Send feedback
2. select bug report  or feature request
3. rotate the screen

### Expected behavior
it should save opened form

### Actual behavior
it goes back to the screen with radiobuttons list.

**Comment by zebrum** [comment]
there is one more problem on samsung devise: screen with radiobuttons list is not appear when you open Send feedback.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Reinstall AG
-Try to reproduce the issue
