### ISSUE TITLE
"Server error" during the photo upload at reports.adguard.com 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForAndroid#2086]
### Steps to reproduce

1. Open reports.adguard.com
2. Step 5/8
3. Drag file (or click/tap) here to upload 
4. Error

<details><summary>Screenshot:</summary>

<img width="400" alt="screen shot 2018-08-28 at 9 42 43 pm" src="https://user-images.githubusercontent.com/27292111/44743509-64dd1300-ab0b-11e8-9202-c2d172863c2d.png">

</details>

### Customer ID 

Ticket ID 1463025

manufacturer=HUAWEI model=CLT-L09 brand=HUAWEI version=8.1.0 
AdGuard for Android 2.11.81

### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: VPN 
* Device model: HUAWEI
* Operating system and version: Android 8.1.0
* Any other apps that can start VPN/Antiviruses/Cleaners none

**Comment by ameshkov** [comment]
Wrong repo, we're looking into it
