### ISSUE TITLE
AdGuard assistant launched via app shortcut flickers (Pie related?)

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#2088]
### Steps to reproduce

1. Use an app shortcut to launch AdGuard Assistant (might need to do this two times)
2. Assistant window opens, but flickers to the right one time very quickly. I've seen this happen with Google's Digital Wellbeing functionality, so it _could_ be something wrong on Android's end, or it could be some sort of compatibility issue with Pie. I'm not a dev. :)

### Customer ID 

1403048

### Your environment

* Adguard version: 2.12.187
* Adguard filtering mode: VPN
* Device model: Pixel 2 XL
* Operating system and version: Android 9 Pie
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by carlylemiii** [comment]
Yes, I will get you a recording soon. For some reason a screen recorder makes the issue go away so I will have to literally film it. :)

**Comment by carlylemiii** [comment]
Sorry for the delay, kept forgetting about this.

https://www.dropbox.com/s/xv8ead8570t5jh7/video.mp4?dl=0

**Comment by ameshkov** [comment]
That would be hard to fix :)

@zebrum is it reproducible on our test device?

**Comment by zebrum** [comment]
@ameshkov nope, everything is ok.

**Comment by zzebrum** [comment]
@carlylemiii is the problem persist on v3.0?

**Comment by carlylemiii** [comment]
@zzebrum the problem is gone. I think it has been gone ever since Pie or a new Pixel for me, actually.
