### ISSUE TITLE
Rework DnsCache, so it uses several IP-addresses, and not only the first one

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#209]
As with this problem: UMI-441-10032

**Comment by Revertron** [comment]
For the best result we must make EndPoint use several IP's and in connect() method try to connect to all of them sequentially if previous try was unsuccessful.

**Comment by Revertron** [comment]
Made it cache all IP's and return one random of them. Not the best option, but will do for now.
Remind me after HTTPS-filtering is done to remake the EndPoint.

**Comment by Revertron** [comment]
Uploaded test build: http://bit.do/adguard-last-build

**Comment by ameshkov** [comment]
Hey, don't forget that DnsCache is not used in this case. We get the real endpoint from the /proc/net/tcp data and do not try to actually resolve the remote address.

Actual DNS address for the host MAY be used as a fallback though, good idea.

This can also be a good fix for facebook issue #43

**Comment by ameshkov** [comment]
CoreLibs
