### ISSUE TITLE
Pikabu app won't load articles/pictures when protection is on

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2091]
### Steps to reproduce

1. Open AdGuard and start protection
2. Open Pikabu application [App](https://play.google.com/store/apps/details?id=ru.pikabu.android&hl=ru)

### Expected behaviour

Everything should be okay

### Actual behavior

Pikabu application won't load any images, articles and etc (Screenshot attached)

<details><summary>Screenshot:</summary>

![pkb](https://user-images.githubusercontent.com/37797229/44770099-8f60b780-ab6f-11e8-909d-4d0147fc2d74.jpg)
![pkb2](https://user-images.githubusercontent.com/37797229/44770101-8f60b780-ab6f-11e8-8200-76133a9d1d0d.jpg)

</details>

### Your environment

* Adguard version: 2.12.192n
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel) Google Pixel
* Operating system and version (e.g. Android 7.1.2) Android 9

**Comment by TheHasagi** [comment]
Info update*

The issue exists only if proxy (for example, SOCKS5) is enabled.

**Comment by zebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #455](https://github.com/AdguardTeam/CoreLibs/issues/455) via [**ZenHub**](https://www.zenhub.com/)
