### ISSUE TITLE
You need to add a list

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#2092]
Hi,

1. Needs ABP Anti-Circumvention Filter List 
https://github.com/abp-filters/abp-filters-anti-cv

2. DNS side wants to add Quad 101 !
http://twnic-public-dns.twnic.tw

OK! thnak you1

### Your environment

* Adguard version: 2.12.187 Beta
* Adguard filtering mode: VPN 
* Device model: MIUI
* Operating system and version: Android 7.0 NRD90M
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by lancelot-moon** [comment]
@karina-archazh 
https://github.com/AdguardTeam/AdguardForAndroid/issues/1811#issuecomment-413856518

**Comment by edentw** [comment]
Sorry!
I hope to be added directly to your built - in list!
Without the need to customize means!
Did not describe clearly at first!

thank you!

**Comment by ameshkov** [comment]
We'll add it when scriptlets/snippets support is added https://github.com/AdguardTeam/CoreLibs/issues/687
