### ISSUE TITLE
VpnService.Builder addDisallowedApplication does not work for our own app on some devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2093]
It seems that on some devices it does not exclude AdGuard from VPN. In order to solve this issue, we must use VpnService.protect even when our app is in the list of excluded.

**Comment by TheHasagi** [comment]
Customer ID: 1462357

**Comment by ameshkov** [comment]
@TheHasagi please ask customer to test this build:
https://uploads.adguard.com/up04_tpctj_adguard_issue2093.apk

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/680`

Testing instruction: we won't be able to reproduce it on our side so just take the user's word for it.
