### ISSUE TITLE
Secure connections (HTTPS) filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#21]
Simple MITM.
Disabled by default.

**Comment by TPS** [comment]
When you say "Simple MITM", I hope you mean basic request filtering only.… ☺

**Comment by ameshkov** [comment]
@Revertron look here:
http://stackoverflow.com/questions/18065170/how-do-i-do-tls-with-bouncycastle

I think TlsServerProtocol class is what we were looking for.

**Comment by Revertron** [comment]
Commited first implementation.

**Comment by TPS** [comment]
Just a thought, if we have this active, is it possible to white-/blacklist sites from *only* this feature someplace in AG?

**Comment by ameshkov** [comment]
> Just a thought, if we have this active, is it possible to white-/blacklist sites from only this feature someplace in AG?

There are two options.
1. Blacklist filtering. Means filter **only domains from the whitelist**.
2. Whitelist filtering. Means filter **everything except the whitelist**.

Default is the second one.

**Comment by ameshkov** [comment]
An update on current state: we are working on server certificates verification.

**Comment by ameshkov** [comment]
Closing this issue as SSL filtering goes to inner testing stage.

All open bugs regarding SSL filtering are here:
https://github.com/AdguardTeam/AdguardForAndroid/labels/SSL

**Comment by eligrey** [comment]
@ameshkov Will it be a configurable option in the settings? I would like the ability to disable this feature if I want to. I am okay with it being enabled by default though.

**Comment by ameshkov** [comment]
@eligrey it will be disabled by default.

**Comment by ameshkov** [comment]
Also it will be configurable.

There are two filtering modes: "blacklist" and "whitelist".

In "blacklist" mode AG will only filter domains from the "blacklist".
In "whitelist" mode AG will filter all domains except listed in a special SSL whitelist.
Both lists are configurable.

Also "whitelist" by default contains lots of known financial services and online banking websites.

**Comment by eligrey** [comment]
@ameshkov Thank you, sounds great!
