### ISSUE TITLE
Add some popular filter subscriptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#210]
We should add popular language-specific filters for the following languages:
French: http://forum.adguard.com/showthread.php?7876-french-list
Chinese
Italian
Polish

**Comment by TPS** [comment]
Maybe differentiate this from #12 by updating title to reflect _international_ filter subscriptions?

**Comment by ameshkov** [comment]
We'll add *some* filters now, not the full list as in #12

**Comment by ameshkov** [comment]
**Filters to add:**
ABPindo
EasyList China
EasyList Czech and Slovak
EasyList Czech and Slovak
EasyList Hebrew
EasyList Italy
Liste AR
Liste FR
ABP Japanese Filters
Adblock polskie reguły

**Comment by ameshkov** [comment]
Done

**Comment by Bohdan-SUP** [comment]
Please add Greek AdBlock Filter:
https://www.void.gr/kargig/void-gr-filters.txt
https://www.void.gr/kargig/blog/greek-adblock-plus-filter/

Requester here - MFB-256-65337

**Comment by ameshkov** [comment]
@Bohdan-SUP could you please move it to a separate issue?

**Comment by Bohdan-SUP** [comment]
Done
https://github.com/AdguardTeam/AdguardForAndroid/issues/282
