### ISSUE TITLE
I already closed the CCProxy server on PC. But it still showed "connected to the proxy" on status bar.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2102]
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/1yVVKxK.png)
</details><br/>
I first closed the proxy server.

Afterwards, I enabled AdGuard.

Before enabling AG, I clicked "check for connection".
It surely can't establish connection to the proxy server.

But why did AdGuard still show "connected to the proxy server" on status bar since the proxy server was closed?
It should show "not connected to a proxy" such like the screenshot in that post.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2089
A bug?

**Should you design that AdGuard will first check proxy server when enabling AdGuard protection if proxy settings are enabled?**

**Comment by ameshkov** [comment]
Not a bug, that's how it works.

> Should you design that AdGuard will first check proxy server when enabling AdGuard protection if proxy settings are enabled?

We thought about it, but it might be unreliable as there can be dozens of reasons why the first check does not work.

**Comment by lancelot-moon** [comment]
I think AdGuard should first check proxy server when clicking for enabling AG Protection if proxy settings are enabled.

If AdGuard checks that proxy server is offline,  AdGuard shows a warning and doesn't enable protection.

**Comment by ameshkov** [comment]
Maybe you're right, i've filed a separate feature request about it:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2122
