### ISSUE TITLE
Incorrect filters sorting

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2104]
AdGuard nightly 2.12.204

<details><summary>Screenshot:</summary>

 
![screenshot_20180905-131327](https://user-images.githubusercontent.com/23637588/45087551-fac9fc80-b10e-11e8-8787-4d476fe01e14.png)

</details>

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/696`

## Testing instruction

Verify that the filters order is the same in both cases: clean install and update from the stable release.
