### ISSUE TITLE
Re-design firewall app settings section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#211]
Read this discussion:
https://github.com/AdguardTeam/AdguardForAndroid/issues/196

We should make these settings clear, not so confusing as they are now.

**Comment by vozersky** [comment]
There was also a feature request from user 1253499 about adding firewall settings icon to the application's main screen to make it easier to access.

**Comment by TPS** [comment]
Just to replicate from https://github.com/AdguardTeam/AdguardForAndroid/issues/633#issuecomment-229092366:

>I'm hoping that the right-hand column icons (AG shield, wifi antenna, :signal_strength:) are _quick toggles_, & not just static state notifications.

**Comment by vgavrish** [comment]
id 668182
the same request about adding firewall settings icon to the application's main screen

**Comment by TPS** [comment]
Why closed, @ameshkov?  No more updates to this, especially my quick toggle idea above?
