### ISSUE TITLE
Automatic updates are not responding to user setting

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#2110]
### Steps to reproduce
1. Install AdGuard Stable, Beta or Nightly on a Nokia 7 Plus that is up to date (8.1.0, Security patch: 1 August 2018)
2. Set automatic updates to any period of time
3. Enable protection
4. Set AdGuard VPN to 'Always-on' active
5. Exclude AdGuard from 'Battery optimisation'
6. Enable 'Background data' to allow mobile data usage in the background
7. Enable 'Unrestricted data usage' to allow AdGuard to update regardless of Data Saver
8. Ensure AdGuard is not blacklisted in the 'Background activity manager', and that 'Background activity cleaner' is turned off
9. Wait for an automatic update.

### Expected behavior
AdGuard updates by itself automatically as per user settings (every 'x' hours)

### Actual behavior
AdGuard updates sporadically regardless of user settings

<details><summary>Screenshots:</summary>

![screenshot_20180825-070123](https://user-images.githubusercontent.com/42660125/44615735-b7f16480-a884-11e8-88c0-4c5e058d9b37.png)

![screenshot_20180825-163317](https://user-images.githubusercontent.com/42660125/44615732-a7d98500-a884-11e8-96bd-98f09fa0b89a.png)

</details>

### Your environment

* AdGuard version: 2.12.212 beta, also experienced with nightly and stable versions.
* Adguard filtering mode: VPN
* Device model: Nokia 7 Plus
* Operating system and version: Android One 8.1.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? None

**Comment by ameshkov** [comment]
Seems to be a UI bug (the filters updates were checked, but the UI was not notified about it).

**Comment by planet0** [comment]
When I manually update a few hours later, there are always a few filters that are 'updated' and then the VPN restarts -- is this just the UI catching up to the actual updates? Manually updating also seems to the the only way I'm getting program updates as well.

We've got a Samsung smartphone (but running an older version of Android 7) that is updating hourly and the UI shows it fine -- it is also getting automatic program update notifications as well, so it does seem to be Android OS or device specific.

**Comment by planet0** [comment]
This seems to be resolved as of 2.12.247 👍🏼

**Comment by ameshkov** [comment]
Hmm, and I've no idea how did we fix it:)

I'll keep this issue open just in case -- we'd better re-test it later.

**Comment by planet0** [comment]
Sure, do you think it's related to #2153? I noticed this version apparently resolves that.

**Comment by ameshkov** [comment]
I can see the correlation, but I have no clue how exactly the change in #2153 might have helped :)

**Comment by planet0** [comment]
Hmm. The only other idea is that the Nokia 7 Plus now use Android Pie 9 instead of Oreo 8.1.

Either way, I'll continue to occasionally check the last updated time.

**Comment by vozersky** [comment]
obsolete issue
