### ISSUE TITLE
AdGuard crash. Too many apps installed.

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2113]
AdGuard crashes in Apps Management.

If there are too many apps installed on the device AdGuard will crash after a try to use Apps Management.
[Archive 635262.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2370285/Archive.635262.zip)

**Comment by ameshkov** [comment]
@TheHasagi what if you clear the app data in Android settings? Does it help?

**Comment by TheHasagi** [comment]
Asked, waiting for the reply.
