### ISSUE TITLE
RC2: Missing Highlight focused element on Android TV

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#2114]
2.12.219 RC2 on Android TV v.8.0.0

Running the beta on Android TV (Mibox) works fine, but when you go into settings (and elsewhere) the focused element should be highlighted - conventionally using a greyish background - which is missing and could be easily added. It does show up, however, on click (just not on hover, or select using DPAD input).

**Comment by nkartyshov** [comment]
Closed. Should be reopned if needed.
