### ISSUE TITLE
Feature Request: cosmetical changes Firewall

### ISSUE THREAD

**Issue by Rintenfinten** [AdguardTeam/AdguardForAndroid#2117]
Hi.

Would it be possible to change the color of the Icon beneath the apps to blue if set to block when screen is off? At the moment I only see red or green...

Also it would be great if you could somehow mark system Apps and offer Filters for system apps.

Last but not least I would like to see Log Data at the bottom of an app's detailed view.

best regards
Matthias

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
