### ISSUE TITLE
[Feature Request] Include decoded payload in the requests view

### ISSUE THREAD

**Issue by jamezrin** [AdguardTeam/AdguardForAndroid#2118]
Currently you can see the requests made by apps to services and some information about them. 
![image](https://user-images.githubusercontent.com/5949554/45577145-d4c4fa80-b87a-11e8-9c21-4647f6de4419.png)

It would be great if it included the decoded HTTP/HTTPS payload in the registry of requests, so that we can see what apps try to do and with what data.

**Comment by artemiv4nov** [comment]
Please try a new version of AdGuard, we have reworked the functionality in the v4.0.
