### ISSUE TITLE
A solution for untrusted AdGuard certificate on Android v7 , v8 and above without root.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2119]
@ameshkov 
Maybe my private messages aren't sent to you on telegram...

For AdGuard for Android v3, there is also no news about solutions for untrusted AdGuard certificate on Android v7 , v8 and above without root.
No active action, compared with others.

https://www.seven.com/adclear-faq.php
But I think some people don't like its new privacy policy....
https://www.seven.com/privacy/

App Launcher:
https://play.google.com/store/apps/details?id=com.seven.applauncher

(Android 7 and higher) What is App Launcher and how do I install it?
App Launcher is a free app that allows other apps to run in their own virtual environment. This allows AdClear to more effectively block ads on devices running Android 7 and above.

1. Install App Launcher from the Play Store.

2. Install the latest version of AdClear from seven.com. If AdClear is already installed on your phone, check for available upgrades and install the new version if available.

3. In AdClear, go to Settings>Ad Blocking>HTTPS filtering and make sure that HTTPS filtering is enabled.

4. Run App Launcher. Add the YouTube app to the list of apps that will run through App Launcher.

5. While in the App Launcher app, launch the YouTube app.

6. AdClear will now block most ads on YouTube and other apps.

7. Remember to always run your apps from within App Launcher rather than directly from the app tray.

**Comment by ameshkov** [comment]
Sorry for missing the telegram messages.

Yeah, I am aware of this approach and we have it mind, but our hands are full with other tasks at the moment. We will get back to it though.
