### ISSUE TITLE
Filter Removed Upon Selection on "User Filter" and "Whitelist" screens

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2120]
Hi, this is not related to any filter but a generic issue which I have observed in the latest nightly (2.12.220n) or probably even in earlier versions.

Currently when you search for some text on the "User Filter" page, only the filtered entries are seen. However, now when you try to check/uncheck any entry, the filter is removed although the selection is intact.

Moreover, after searching for any text, when you tap on any entry (while being in the filter view), and then deleting that entry again removes the filter.

The desired behaviour is that when we search for something on the "User Filter" page and then check/uncheck/tap an entry, the filter view should not be removed. That is, we should be able to check/uncheck/tap while being in the filter display. Thanks!

**Comment by admitrevskiy** [comment]
There are the same issues for the Whitelist.

Testing instructions for QA:
-Reinstall AG
-Examine UserFilter and Whitelist for different cases, such as:
a) Enter search query - remove item - close SearchView
b) Enter search query - remove search query - add new item - enter search query
c) etc.

Please, let me know if something goes wrong

**Comment by Nzzyme** [comment]
I tested and I think it works fine in the latest nightly (3.0.157)
