### ISSUE TITLE
VPN apps traffic might cause an infinite loop when AG works in the root+proxy mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2123]
The source report:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2121

Any generic solution? Needs to be discussed.

**Comment by lancelot-moon** [comment]
1. Other VPN apps which use VPN protocols don't have the issue.
speedin's VPN app is actually a proxy client app.
It uses ShadowSocks protocol and is incompatible with AdGuard for Android's auto local HTTP Proxy mode.
Is there no relation?

2. Another question.
Will there be problems when enabling HTTP/Socks Proxy in Proxy settings and using auto local HTTP Proxy mode together?

**Comment by ameshkov** [comment]
Closed as duplicate: https://github.com/AdguardTeam/AdguardForAndroid/issues/2712
