### ISSUE TITLE
deezer.android.app

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2126]
@adguard-bot commented on [Fri Sep 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22452)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=deezer.android.app](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Ddeezer.android.app)
### Comment
Username: @Jzamoras
> Adguard enabled breaks deezer streaming 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--rSGeAxqO--/v1536937713/wl14ugdytfrauxxqnc81.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.219
AdGuard mode: | VPN
Filtering quality: | Simplified
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Simplified domain names

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #499](https://github.com/AdguardTeam/CoreLibs/issues/499) via [**ZenHub**](https://www.zenhub.com/)
