### ISSUE TITLE
AdGuard does not restart after auto-pause on older Android devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2127]
Affected customers:

* 1570768
* 630452

For both affected customers the issue is triggered by swiping the app away (so `onTaskRemoved` is called in this case). We can detect this case and restore protection automatically.

**Comment by ameshkov** [comment]
Resolved by adding a protection restoring mechanism.

## Testing instruction

1. Start AdGuard protection.
2. Go to Android settings, find AdGuard, "force stop" it.
3. AdGuard will restart protection automatically.

The idea is that if AdGuard was started previously to the process killing, it will restore protection automatically. The proper way to stop AdGuard is from the interface or menu. If AdGuard fails to restore protection, it will not try it again.

Here are the use cases that might've been affected by this change and need to be re-tested:

1. Reaction on the network state changes (when auto-pause is enabled).
2. Working when AdGuard is configured to be the "always on" VPN.

**Comment by ForumDyskusyjne** [comment]
At the moment Your solution working correctly.
Constant VPN is not necessary...
When VPN is always ON, there is conflict with for example: KASPERSKY SECURE CONNECTION.
I using "KSC" when I have to secure connections for example payments.

Now, "cleaning" RAM, closing VPN and Application (3-5 second). Next "wake up" VPN and Application.
Seems application works like version 2.11.
Android version: 7.0 from Lenovo.

**Comment by ameshkov** [comment]
There's one more case which is important for the older devices (Android 4-6) was not fixed in this update. 

Another try, here is an updated build:
https://uploads.adguard.com/up04_spopq_adguard_2.12.228_nightly_hotfix2.apk

## Testing instruction for QA

1. Use AdGuard on an older device (**Android 6 or older**)
2. Start protection
3. Switch the phone to the airplane mode (auto-pause will kick in)
4. Go to Android settings and "Force stop" AdGuard
5. Disable the airplane mode

AdGuard must restore protection automatically.

**Comment by dtitbd** [comment]
Хз, создавать новую тему или нет, но у меня все равно не фурычит автозапуск.
Версия сабжа 2.12.233.
Версия андроида: 7.1.1.
Девайс: Lenovo Tab4 10 Plus TB-X704L.
Уведомления отключены, но раньше это проблем не создавало.
После отключения wi-fi процесс просто отключается, его даже в кэше нет.
Никаких особых тасккиллеров нет, все настройки планшета перелопатил.

**Comment by ameshkov** [comment]
@dtitbd а можете лог прислать?

**Comment by ameshkov** [comment]
@dtitbd хм, почему-то не пришло ничего.

**Comment by ameshkov** [comment]
@dtitbd посмотрел всю почту на devteam, вообще ничего похожего:(
