### ISSUE TITLE
AdGuard switches to English after restoring a backup with Japanese language

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2132]
Has been reported by a user with HTC Nexus 9, Android 7.1.1 and the release version of AdGuard. For logs and screen recording, please see 1998350.

### Steps to reproduce

1. Switch to Japanese (or, maybe, another language different from English)
2. Export settings
3. Clear app's data
4. Restore settings

### Expected behavior

AdGuard uses the language from the backup

### Actual behavior

In some cases, it uses the default language

<details><summary>Screenshot:</summary>

https://dotup.org/uploda/dotup.org1647938.mp4

</details>

### Customer ID 
1998350

### Your environment

* Adguard version: 2.12.223
* Adguard filtering mode: VPN
* Device model: HTC Nexus 9
* Operating system and version: Android 7.1.1
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Reinstall AG
-Export settings with Japan language enabled
-Clear data
-Import settings

Expected result:
-The application restarts and language changes
