### ISSUE TITLE
Visual glitch in the notification on Google Pixel 2 XL

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2133]
> Pixel 2 XL - Android 9.0: When the Protection Status notification is set to minimized, the "Pause" & "Assistant" buttons cut into the text listed above them when expanding the notification.

### Steps to reproduce

1. Open the notification drawer
2. Expand AdGuard notification 
3. Fully swipe it open 

### Expected behavior

Tex is not overlapping on step 2

### Actual behavior

It's overlapping on step 2 (see the screenshot below) and restores the correct position on step 3

<details><summary>Step 1:</summary>

![image](https://user-images.githubusercontent.com/15856304/45916538-90d08780-be70-11e8-84d0-ef75b0c98232.png)

</details>

<details><summary>Step 2:</summary>

![image](https://user-images.githubusercontent.com/15856304/45916534-75fe1300-be70-11e8-90fd-0c6faa889a30.png)

</details>
<details><summary>Step 3:</summary>

![image](https://user-images.githubusercontent.com/15856304/45916545-a776de80-be70-11e8-831f-f9474387e160.png)

</details>

### Customer ID 
1865135

### Your environment

* Adguard version: 2.12.223 / .224n
* Adguard filtering mode: proxy (auto)
* Device model: Google Pixel 2 XL
* Operating system and version: 9
* Rooted or not? +
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zebrum** [comment]
Can't reproduce. Android system draws this notification, I suppose it should be reported to Google.

**Comment by zebrum** [comment]
@Eugene-Savenko reopen if there are more complaints
