### ISSUE TITLE
The notification is always expanded on Huawei Honor 6x 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2135]
It opens expanded while other apps' notifications in the drawer stay collapsed. Could it be because of the notification being on top of the list in the drawer and expanded by the system due to its high priority? The customer states it works fine on another phone they own (Xiaomi Max), and that it had a normal behavior in the 2.12.220 release.

### Steps to reproduce

1. Install AdGuard (any release except 2.12.220)
2. Start the protection
3. Open the notification drawer

### Expected behavior

The notification stays collapsed and does not take too much space

### Actual behavior

It opens expanded

<details><summary>Actual:</summary>

![image](https://user-images.githubusercontent.com/15856304/45939645-de6a0300-bfdc-11e8-9e03-43907d6a366c.png)

</details>

<details><summary>Expected:</summary>

![image](https://user-images.githubusercontent.com/15856304/45939650-e9249800-bfdc-11e8-8fac-79b46667ebcd.png)

</details>

### Customer ID 
1154709

### Your environment

* Adguard version:  any except 2.12.220
* Adguard filtering mode: VPN
* Device model: Huawei Honor 6x 
* Operating system and version: 7.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zebrum** [comment]
Again probably Huawei firmware related - we can do nothing about it. Notification is expanded in 2.12.220 and in other versions.

**Comment by Eugene-Savenko** [comment]
It has something to do with the priority as when our notification is the first on the list, it's automatically expanded, and when it's not, it's not.  I've been a bit confused by the fact that it's been checked multiple times and worked properly (customer's words) on 2.12.220. [Here](https://stackoverflow.com/questions/13720670/implement-expand-and-collapse-notification-android) people say that:

>A notification's big view appears only when the notification is expanded, _which happens when the notification is at the top_ of the notification drawer, or when the user expands the notification with a gesture. Expanded notifications are available starting with Android 4.1.
