### ISSUE TITLE
Settings section UI

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2136]
Check the updated icons and layout:

* https://uploads.adguard.com/up04_6qe5j_Androoid_polnyi.sketch.png
* https://uploads.adguard.com/up04_489oz_Androoid_polnyi.sketch.png
* https://uploads.adguard.com/up04_a73w6_Androoid_polnyi.sketch.png

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/4ddc43db-a78c-4696-99cf-b383d88768e6
