### ISSUE TITLE
Sidebar nav UI

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2137]
Updated sidebar nav:

* https://uploads.adguard.com/up04_j6quz_Androoid_polnyi.sketch.png

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/a3d375f4-16cf-4a87-bcd3-11ebe5c48935 -  last version
https://trello.com/c/oVzCyN4O/153-%D1%81%D1%82%D1%80%D0%BE%D1%87%D0%BA%D0%B0-%D1%88%D1%83%D1%82%D0%BA%D0%B0-%D0%B4%D0%BB%D1%8F-android-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F - stroke for unlicensed users @nkartyshov
