### ISSUE TITLE
Apps Management UI

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2138]
See the screenshots:

* https://uploads.adguard.com/up04_fgf5g_Androoid_polnyi.sketch.png
* Swipe up: https://uploads.adguard.com/up04_ui065_Androoid_polnyi.sketch.png

Check other states in the sketch file.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/de5239e1-b91e-48f1-9fcf-3a19ff5a59da
Check icons on this screen, please @Revertron
