### ISSUE TITLE
New proxy settings UI

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2146]
See the sketch file in slack

**Comment by AlikhanAliev** [comment]
https://trello.com/c/JX38SvX6/56-%D0%BD%D0%B5%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%B8%D0%B5-%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D0%B8-%D0%BF%D0%BE-%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8
