### ISSUE TITLE
Network speed is disappearing​ from the status bar in OnePlus 5 after 2.12.223/2.12.233 update

### ISSUE THREAD

**Issue by duplex143** [AdguardTeam/AdguardForAndroid#2147]
OnePlus Oxygen OS has the option of displaying network speed in the status bar. But after updating to the 2.12.223/2.12.233  version, network speed in the status bar is disappearing all of a sudden.

### Steps to reproduce

1. Just turn on Adguard and wait for a while. 

### Expected behaviour
Network speed should not disappear in the status bar.

<details><summary>Screenshot:</summary> 

![Network speed visible](https://user-images.githubusercontent.com/24863030/46233052-ed5f0580-c38e-11e8-9f64-ab311cb61671.jpeg)

</details>

### Actual behavior
But it is disappearing all of a sudden. See that the Display network speed toggle is ON.

<details><summary>Screenshot:</summary> 

![asfd](https://user-images.githubusercontent.com/24863030/46233115-27300c00-c38f-11e8-8e3f-6c50a2bed9c2.jpeg)

</details>

In the first screenshot the network speed is visible. But after some time, the network speed in status bar automatically disappeared. 

### Your environment

* Adguard version:2.12.233
* Adguard filtering mode: VPN / Proxy(manual/auto) **VPN**
* Device model: (e.g. Google Pixel)**OnePlus 5 (A5000)**
* Operating system and version (e.g. Android 7.1.2) **8.1.0**
* Rooted or not? **No**
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? **No**

**I faced this issue in 2.11 version also. But only once. Then I couldn't figure out what app is causing the issue. But after this 2.12 update I'm sure that it's by adguard.**

I've raised an issue with OnePlus support team as well.
https://forums.oneplus.com/threads/network-speed-is-disappearing-from-the-status-bar-in-oneplus-5-after-2-12-update-of-adguard-app.916303/

**Comment by zebrum** [comment]
@duplex143 Was not able to reproduce the issue. Any news from oneplus forum?

**Comment by duplex143** [comment]
For reproducing the issue, you've tried on a OnePlus device right? I've sent them a bug report. No news from them.

**Comment by zebrum** [comment]
@duplex143 yep, we have one in the office. Is the situation the same if you do clean install?

**Comment by duplex143** [comment]
@zebrum I can't afford a clean install just to isolate the cause of this issue. If I were ever to do a clean install or if OnePlus devs have any update for me, I'll inform you. I'm closing this issue for now.
