### ISSUE TITLE
AdGuard icon is missing on some devices since 2.12.223 update

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2148]
> Последняя версия adguard, пропал значок в статус баре, в настройках приложения (иконка уведомления все включено), приложению все разрешения даны, в шторке отображается. Приоритет выставлен максимальный

> После обновления пропала иконка уведомления в левом верхнем углу дисплея, хотя баннер на месте. Все разрешения даны. В прошлой версии программы иконка безупречно находилась на своём месте и показывала, когда система выгружала (пару раз) программу

### Steps to reproduce

1. Update to v. 2.12.223/233
2. Check the notification channel settings and make sure nothing important is disabled
3. Start the protection

### Expected behavior

You see the AdGuard icon

### Actual behavior

You do not see the icon

### Customer ID 
1409531, 1961988

### Your environment

* Adguard version: 2.12.233
* Adguard filtering mode: VPN 
* Device model: Xiaomi Mi MIX 2, HUAWEI STF-L09 respectively
* Operating system and version: 8.0.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zebrum** [comment]
ok, we manage to reproduce the issue. In Huawei firmware there is separate notifications group of settings. In our case it was something like: android settings - apps and notifications - tap on AdGuard -  and there will be Notifications where you need to set priority. That is workaround.

**Comment by ameshkov** [comment]
I mean besides Huawei what other devices provide alternative notification channels settings?

**Comment by zebrum** [comment]
Huawei and Xiaomi so far.
@Eugene-Savenko were there any other complaints?

**Comment by Eugene-Savenko** [comment]
@zebrum please check this one: 1275885

It's a Samsung G950U. The icon is missing though the notification channels are set to Urgen and all are enabled.

**Comment by ameshkov** [comment]
Useful article:
https://get.slack.help/hc/en-us/articles/360001562747-Known-issues-with-Android-notifications#huawei-honor-8

**Comment by nkartyshov** [comment]
Fixed

Test instruction:
1. Install AdGuard
2. Start protection

Expected:
AdGuard icon should have on status bar
