### ISSUE TITLE
Blocking graph.facebook.com on the DNS level does not prevent FB app from connecting there

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2149]
It seems that FB has the graph.facebook.com IP address hardcoded and blocking it on the DNS level does not actually prevent it from connecting there.

This issue needs to be investigated.

**Comment by remewer** [comment]
Just curious. Here's what you said in this blogpost: (https://adguard.com/en/blog/one-does-not-simply-delete-facebook/)

Q: Will AdGuard DNS be able to do the job too?
A: Not really. Blocking `graph.facebook.com` will break all the FB apps so we can't make it a default behavior.

So why would you want to block graph.facebook.com in Facebook app?

**Comment by ameshkov** [comment]
We don't want to block it on our DNS, but some users do want to block it globally. For instance, when they don't use Facebook, but have the app pre-installed.

**Comment by TPS** [comment]
Larger issue: there are probably any # of trackers that do this (do direct IP address when DNS blocked).  Shouldn't this be handled as a general principle via Stealth module?  It'd probably be pretty simple (when AG controls DNS, & maybe even when it doesn't) to do "private" hostname resolution that the rest of the OS isn't privy to & then wholesale block such IPs.

I'd happily ß-test such a feature to see if it could be useful.

**Comment by artemiv4nov** [comment]
Facebook application can work stable (even if Adguard uses filter on the DNS level) because Android contains DNS cache with early resolved domain names. Therefore, not all requests from facebook application get into the Adguard.

**Comment by ameshkov** [comment]
@artemiv4nov in theory, Android flushes this cache every time when the VPN re-connects with new DNS settings.

**Comment by TPS** [comment]
I suppose this is still an issue that needs resolution.…

**Comment by ameshkov** [comment]
In the end, we could not confirm this on our side. There's some kind of a DNS cache indeed, but no hardcoded IP addresses.

**Comment by DNSBunker** [comment]
Blocking graph renders login/registration of FB unusable.
