### ISSUE TITLE
Battery drain issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#215]
This issue is for collecting all complaints on the battery drain.

**2Support: Questions that will help us determine the real cause of the battery drain.**
1. Are you sure this is a real battery drain?

Please first read the article:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/50/0/adguard-for-android-battery-and-traffic-consumption-issues
1. How did you measure the battery drain?
2. Please provide the screenshots of Android battery usage statistics (several shots, we need to see top 20 apps).
3. Please provide the screenshots of Adguard's Firewall applications statistics (several shots, we need to see top 20 apps), period - one day.
4. Also we need a screenshot with battery usage details for Adguard app (the one with CPU time and network packets count).
5. Try leaving Adguard enabled for the night with logging level set to "Record everything" (just like described in this article: https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/0/collecting-a-full-log-on-adguard-for-android)

After that please send us all log files recorded. **Feedback message is not enough** as it is trimmed to 512 kb.

**2Support: post here IDs of the tickets with all that data collected**

**Comment by ameshkov** [comment]
Useful formula to calculate battery usage properly:
https://www.reddit.com/r/Android/comments/3w8q31/i_installed_adguard_and_was_in_for_a_surprise/cxvnen8

**Comment by evgeniy-ADG** [comment]
@ameshkov We have another complaint, please check this ticket FXN-525-51079
The customer has attached screenshots and logs per your request from this task.

**Comment by ameshkov** [comment]
@evgeniy-ADG ask user to enable "DNS filtering"

**Comment by evgeniy-ADG** [comment]
@ameshkov "проблема не исчезла, фильтр dns запросов влияет слабо, либо не влияет вообще на потребление."

**Comment by ameshkov** [comment]
Вообще, судя по скриншотам в самом первом тикете FXN-525-51079, я там не вижу какого-то дикого перерасхода.

Хотелось бы увидеть детализацию потребления трафика по нашему приложению и Chrome (чисто для сравнения).

Чтобы получить детализацию, надо в андроидной статистике тапнуть на приложение. Там должна быть разбивка на составляющие: CPU, трафик.

**Comment by evgeniy-ADG** [comment]
> Здравствуйте, в настройках андроид => батарея - потребление приложений, запретил программе skype пробуждение устройства и постоянное его пребывание в активном режиме, потребление в режиме ожидания упало в 2,5, а то и 3 раза. Может скайп никогда не прекращает попыток скачать рекламу, которую подсовывает баннерами в чате? Во всяком случае проблема лично для меня решена, у меня нет необходимости в постоянном онлайн скайп.

Проблема пользователя решена.

**Comment by ameshkov** [comment]
Ого, это реально полезное замечание.

**Comment by evgeniy-ADG** [comment]
@ameshkov TPR-469-89691 - here we have another battery drain complaint with logs and data collected per instructions above. Could you please check this out?

**Comment by evgeniy-ADG** [comment]
@ameshkov here's the ticket ID 1082297

User states that the latest beta drain batter on his S7 and provided [screenshots](https://photos.google.com/share/AF1QipNC-9mFM36bh1Zfp6yPK4ReTROJwfSUhrd34d90HIRuj25KmFq4TJepaakohMNwPw?key=YTM3RHBTZXl2UkQzWnFWQXQ2TU5UeDB6eVhlaUxR).

Could you please have a look?

**Comment by ameshkov** [comment]
@evgeniy-ADG 

GSam is nice, shows the real battery usage for the app (~2.8%).
Android battery stats are messed up as always. Data usage + ["Mobile radio active" bug] (https://code.google.com/p/android/issues/detail?id=190396) = High numbers for AG.

**Comment by ameshkov** [comment]
https://blog.adguard.com/en/ad-blocking-and-battery-usage/
https://blog.adguard.com/en/great-battery-saving-mode-of-adguard-for-android/
