### ISSUE TITLE
unable to log into pnc android app with https filtering on

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2150]
@jtmckinn commented on [Mon Sep 17 2018](https://github.com/AdguardTeam/HttpsExclusions/issues/112)

It says an error has occured and won't let me login.  I disabled https filtering and it works correctly now.

**Comment by zebrum** [comment]
@jtmckinn please provide a link to the app.

**Comment by Eugene-Savenko** [comment]
This one I guess (a banking app): https://play.google.com/store/apps/details?id=com.pnc.ecommerce.mobile

**Comment by zebrum** [comment]
disable ad blocking for this app @nkartyshov

**Comment by nkartyshov** [comment]
done
