### ISSUE TITLE
Adguard startet nicht

### ISSUE THREAD

**Issue by hkkp** [AdguardTeam/AdguardForAndroid#2152]
Automatisches starten von Adguard schlägt fehlt, er kann keine vpn-verbindung aufbauen, da die firmware veraltet ist. manuelles starten von adguard funktioniert.

android 5.1.1
letzte nightly von Adguard
moto x 2013
vpn
root

**Comment by zebrum** [comment]
@hkkp 

Haben Sie 2.12.234 Version installiert? Auf welcher Version ist das Problem augetreten?

**Comment by hkkp** [comment]
Ja hatte ich. Bin zur Version 2.11.81 zurück gekehrt. Dort funktioniert alles so wie es soll.

**Comment by ameshkov** [comment]
@hkkp could you please reproduce the issue on v2.12 and then export AdGuard logs and send them to `devteam@adguard.com`?

To export logs: settings -> advanced -> export logs

**Comment by zebrum** [comment]
@hkkp can you collect logs?

**Comment by hkkp** [comment]
i have send the logs to devteam@adguard.com.

**Comment by TheHasagi** [comment]
@hkkp 

Hello!

Can you reproduce this issue with the [latest nightly build](agrd.io/android_nightly)?

**Comment by hkkp** [comment]
no, not working.

**Comment by TheHasagi** [comment]
Can you send the logs from the latest nightly (with the reproduced issue) and a screenshot with the error?

**Comment by hkkp** [comment]
yes I can, but this takes some time, because this is not my phone and I'm only the one who updates the phone, etc.
