### ISSUE TITLE
UI issues on Android TV (MiBox3)

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#2154]
Functionality is fine on Android TV using DPAD input (MiBox3), but there are some UI issues, - and only on certain screens.

- The Settings screen should be like the tablet/landscape version, with two panes, but on Android TV you only see the one screen (first pane > click > subscreen). 
- Settings > General: Missing highlighting of onFocus element (see issue #2114 ). 
This should be like on the Settings > Ad Blocker subscreen, which works perfectly. It's missing on other subscreens, too, included (but not only?): Browsing Security, Advanced,  "Ad Blocker".

### Your environment
AdGuard Beta 2.12
Xiaomi Mibox3
Oreo 8.0
Not Rooted

**Comment by ameshkov** [comment]
We'll need to re-test it on v3.0 branch

**Comment by oroboros** [comment]
Honestly, the second point seems like it was done correctly for the first subscreen, and then just forgotten for the rest. Makes it still usable, but only if you have a mouse connected (not with the DPAD remote).

Glad to see Android TV will be retested in next major version. Thanks!

**Comment by admitrevskiy** [comment]
This issue is part of biggest one: https://github.com/AdguardTeam/AdguardForAndroid/issues/2335

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-To test this issue you should use Android TV emulator (create it by Android Studio)
-Examine UI with remote emulation via keyboard.

**Comment by oroboros** [comment]
> Resolved.
> 
> Testing instructions for QA:
> -To test this issue you should use Android TV emulator (create it by Android Studio)
> -Examine UI with remote emulation via keyboard.

Feel free to contact me for testing on real Android TV device (rahter than just emulator).

**Comment by zzebrum** [comment]
@oroboros if you don't mind trying the latest nightly to check if the issue is fixed too :) v3.0.180n

**Comment by Alex-302** [comment]
highlighting of element, selected by remote control(not mouse), is missed in:
- apps management;
- filtering log.

**Comment by artemiv4nov** [comment]
Done in 3.3, you need re-test it after 3.3 releasing.

**Comment by oroboros** [comment]
@zzebrum @artemiv4nov highlighting element is also missing on selections in 

- all items under update channel
- General > Notification settings (completely not accessible, perhaps needs to be greyed out?)
- General > Language (no selection of languages)
- Extensions > everything below "new extension"


there's missing audio feedback (click sound) on selection:
- general settings
- some not all of "Stealth mode" screen

**Comment by TheHasagi** [comment]
@oroboros 

You should check it when version 3.3.x will be available :) It is not implemented in 3.2.x at the moment.

**Comment by oroboros** [comment]
I will, thanks! 

I just wanted to alert to other places having the same problem, and the problem with sound on selection feedback which is missing, and which had not been reported previously.
