### ISSUE TITLE
Bubble Shooter app has ads

### ISSUE THREAD

**Issue by TesterMan247** [AdguardTeam/AdguardForAndroid#2155]
I have raised this issue on the forum, but it seems to just keep getting overlooked.

This is to help this get a fix sooner than the long wait so far.

I've provided all the information needed, so why the long wait for the fix?

Anyway, here is the link to the issue on the forums....

https://forum.adguard.com/index.php?threads/bubble-shooter-app-has-ads-android.29525/

**Comment by karina-archazh** [comment]
Recommendations to address the problem have been received in this post:
https://forum.adguard.com/index.php?threads/bubble-shooter-app-has-ads-android.29525/#post-172556

**Comment by TesterMan247** [comment]
I saw that, but the issue remains.
Until the issue is resolved fully, why the rush to close this Github post?

**Comment by karina-archazh** [comment]
I closed this issue because this convo duplicate forum thread with Alex.
