### ISSUE TITLE
When uploading photos to imgur.com by chrome on Android, the process is frozen.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2156]
When uploading photos to imgur.com by chrome after enabling AdGuard, the process is frozen.
It always shows "Processing..."
Some photos were failed to be uploaded.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Vm3uzMP.png)
</details><br/>

Please solve it.

Thanks.

**Comment by karina-archazh** [comment]
Hi!

Please provide:
1. Amount of images
2. AdGuard settings (DNS, HTTPS on/off)
3. Could you repeat this issue using WIFI network
4. Do you using Imgur app or web application

And please send to us some logs.

**Comment by lancelot-moon** [comment]
I tried to only upload 1 photo to imgur.com.
Failed.
1. 1 or several photos (5).

2. DNS settings are disabled. HTTPS filtering is on.

3. Yes, failed in both cellular network and Wi-Fi.

4. I use chrome for uploading photos on Android.

5. log:
https://app.box.com/s/lwgyb0dwgmmepa6htslfqevae1nyjfbx

**Comment by ameshkov** [comment]
Need to be re-tested with a newer CoreLibs version (I think this upload issue is resolved there).

**Comment by lancelot-moon** [comment]
@Revertron

In AG v3.0.195η or earlier version, the issue occurred again. (Stealth mode is disabled.)
When uploading photos to imgur.com by chrome after enabling AdGuard, the process is frozen.
It always shows "Processing..."
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PfQ8lgp.png)
</details><br/>

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #689](https://github.com/AdguardTeam/CoreLibs/issues/689) via [**ZenHub**](https://www.zenhub.com/)
