### ISSUE TITLE
Disappeared HTTPS request in the filtering log.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2157]
@Ameshkov
@AdamWr

I tried to visit the web page from the issue. 
https://github.com/AdguardTeam/AdguardFilters/issues/23481

Issue URL:
https://mamibuy.com.tw/talk/article/58126

Need to unblock www.google-analytics.com/analytics.js, otherwise the web page can't be normally loaded.
`@@||www.google-analytics.com/analytics.js^$domain=mamibuy.com.tw`
You know about the similar issue for Line Today.

But my rule only works for browsers on PC and Safari on iOS.
It's strange that the HTTPS request of www.google-analytics.com/analytics.js didn't appear in the filtering log of AG for Android.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/OZUBmTy.png)
</details><br/>

So my rule can't work for mobile browsers on Android with AdGuard.
The page was always loading...
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/r86XPNH.png)
</details><br/>

So I disabled AG for Android.
I purely let my Android phone connect to my proxy server which is filtered by AG for Windows.
AG for Windows did network-wide HTTPS filtering for my Android phone.
I again tried to open that page on my Android phone.
The HTTPS request of www.google-analytics.com/analytics.js surely appeared in the filtering log of AG for Windows. 
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MWbkzDH.png)
</details><br/>

The page was opened.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/mqd1FW5.jpg)
</details><br/>

For solving it on Android, I need to manually add mamibuy.com.tw in the whitelist of HTTPS fiiltering in AG for Android.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/m9wFnHM.png)
</details><br/>

Sometimes that HTTPS request was in the filtering log of AG for Android, but sometimes it was not.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/w092E7u.png)
</details><br/>

My rule in the user filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/DusBx3z.png)
</details><br/>

Anyway, the page could be opened at least.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/mqd1FW5.jpg)
</details><br/>

Is it a bug for HTTPS filtering?
My Android phone is without root.
Is that why my filtering log can't catch all requests?
Maybe it can explain why my rule in the user filter works fine in Safari with the content blocker of AG Pro for iOS, right?

But chrome is a browser app, not a general app.
Chrome should trust AdGuard certificate on Android even if my Android phone is without root.
Why is there still the lack of browser app's HTTPS requests in the filtering log of AG for Android?

Thanks.

**Comment by karina-archazh** [comment]
@lancelot-moon Hi!
 I tried to reproduce your issue and i see that your first part about that the rule @@||www.google-analytics.com/analytics.js^$domain=mamibuy.com.tw doesn't appear actually exist.
But also I can reach your link and see an article about kids, but when I whitelisted this whole site all i get is a loading chicken. And still no google analytics in filtering log.

Could you please send to me any logs with this reproduced issue?

**Comment by artemiv4nov** [comment]
Recent activity (former Filtering log) has been completely rebuilt. Please try a new version.
