### ISSUE TITLE
Some rules in default ad blocker don't work in AG v2.12.234η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2158]
@ameshkov 

I tested on my old Android device.
**Android v4.4.2 without root.
I'm not sure if the issue also occurs on Android v6, v7, v8 and above.
It seems that only some specific rules in Base filter don't work.**

This is the log (record everything).
https://app.box.com/s/45g5yqx4prh2643dkh0do1q8bt83bm2l

I used the manhuaren app for Android.
http://www.manhuaren.com/download/android/dm5hw-2-2-5/
**The app trusts AdGuard certificate.
So I suggest that you test on both Android v4 and v8.**

I made the rules for the app before.
https://github.com/AdguardTeam/AdguardFilters/issues/21078#issuecomment-413593319

In the older nightly version, the rules in default ad blocker worked fine.
After updating to v2.12.234η, I found that the ads or leftovers appeared in manhuaren app with AdGuard enabled.
I went to check the filtering log.
**Some ad requests were not blocked even if the rules are in Base filter.
The under specific rules in Base filter didn't work on my old Android v4.4.2.**
/getStartPageAds
/getMultiAdsStrategy
/getAditem
/getads?
||by218us.cdndm5.com/25^
||by218us.cdndm5.com/29^

After my rough observation, it seems that only some specific rules in Base filter don't work.
From my screenshots, you know those HTTP requests which should be blocked by default filters are only processed. 
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/ZkHn6Of.png)

![image](https://i.imgur.com/znpSbkI.png)

![image](https://i.imgur.com/T2IRQHo.png)

![image](https://i.imgur.com/UCrdEz6.png)
</details><br/>

(If I manually add those rules in the user filter, the rules could work fine.)

**Maybe I didn't find more other rules which didn't work.
The problem seems to be related to Base filter.**
My rules in Mobile Ads filter seems to work fine.

**Comment by karina-archazh** [comment]
This rules from base filter aren't available on new Adguard nightly versions and Android versions 4/9
On version 2.12.212 the base filter blocks ads (screenshot below)
![image](https://user-images.githubusercontent.com/41899455/47171296-06fdc800-d311-11e8-926a-4dc971ee5c19.png)

**Comment by lancelot-moon** [comment]
I knew the specific rules in Base filter could work in the earlier nightly version.
I didn't test on my Android v8 because the app is from China.
Oh, except for Android v4, the specific rules in Base filter still don't work in Android v9, right?
(If you manually add those rules in the user filter, they'll work.)

Please give screenshots with English interface afterwards as possible.
Thank that finally there is somebody to check the bug. :3

**Comment by lancelot-moon** [comment]
@zebrum

When can you solve the bug?

**Comment by zebrum** [comment]
@lancelot-moon I wonder may it be related to #2157?

**Comment by zebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #587](https://github.com/AdguardTeam/CoreLibs/issues/587) via [**ZenHub**](https://www.zenhub.com/)
