### ISSUE TITLE
Adguard eventually breaks access to internet.

### ISSUE THREAD

**Issue by retrobenny** [AdguardTeam/AdguardForAndroid#2159]
I have had this happen once before where I had to delete/uninstall Adguard then install a fresh copy to fix it,and that is excrutiatingly frustating because I lose out on the stats I built up.

Please try to look into this and add a feature to cleanse Adguard so people don't have to uninstall it whenever it starts being retarded.

I turned off adblocking with it and the internet started working again instead of giving me DNS errors.
I have both ipv4 and ipv6 set to CloudFlare's numbers when adblocking is enabled.

This is on an Nvidia Shield TV Pro (2015) with OTA 6.3 Android Nougat with no major issues,only the irritating keyboard language app (English missing) bug.

**Comment by karina-archazh** [comment]
Hi!
As a temporary solution please try to write down our AdGuard Standart DNS address on your Nvidia Shield.

**Comment by ameshkov** [comment]
So basically you'd like a way to reset the app settings without loosing stats?

> I turned off adblocking with it and the internet started working again instead of giving me DNS errors.
> I have both ipv4 and ipv6 set to CloudFlare's numbers when adblocking is enabled.

Do you mean that you've disabled AG completely or smth else?

**Comment by retrobenny** [comment]
I just touched/clicked the on button in the main part of the app so that Adguard protection would be turned off then internet worked again until enabling protection again.

Uninstalling Adguard and installing it again fixes the problem for a few months or longer until it creeps up again.

**Comment by ameshkov** [comment]
Weird stuff. If you're still able to reproduce that issue, could you please record AG log?

Here's what needs to be done:

1. Settings -> advanced -> logging level -> switch to "record everything"
2. Reproduce the issue
3. Settings -> advanced -> export logs
4. Send the file to `devteam at adguard.com`

**Comment by ameshkov** [comment]
In theory, AG just can't blow up by itself, that's why I need logs in the first place :)

I understand that it's not possible at the moment, but it'd really help if you collect logs when this happens eventually.
