### ISSUE TITLE
Yandex application works incorrectly with enabled HTTPS filtration

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2160]
### Steps to reproduce

1. Start AdGuard
2. Open Yandex application and search for the news

### Expected behaviour

Everything should be in order
### Actual behavior

See the screenshots
Issue exists only with enabled HTTPS filtration
<details><summary>Screenshot:</summary>

![screenshot_2018-09-28-22-33-14-056](https://user-images.githubusercontent.com/37797229/46606110-65060080-cb04-11e8-853d-90907b9474b2.png)
![screenshot_2018-09-28-22-33-57-746](https://user-images.githubusercontent.com/37797229/46606111-659e9700-cb04-11e8-8aa6-a9467120b935.png)

</details>

### Customer ID 
1561308

### Your environment

* Adguard version: 2.12.234n
* Adguard filtering mode: VPN 
* Device model: Lenovo K920
* Operating system and version: 5.0.2

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #522](https://github.com/AdguardTeam/CoreLibs/issues/522) via [**ZenHub**](https://www.zenhub.com/)

**Comment by TheHasagi** [comment]
https://play.google.com/store/apps/details?id=ru.yandex.searchplugin
