### ISSUE TITLE
ENOENT while exporting a log file

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2162]
При попытке экспортировать логи и информацию о системе возникает ошибка и логи не экспортируются.

### Steps to reproduce
1. Открыть Adguard.
2. Зайти в "Настройки".
3. Выбрать "Расширенные".
4. Нажать "Экспортировать логи и информацию".
5. Нажать "Сохранить".

### Expected behavior
Логи экспортируются в выбранную папку на устройстве.

### Actual behavior
Появляется ошибка и логи не экспортируются.

<details><summary>Screenshot:</summary>
![screenshot_adguard_20181008-210735](https://user-images.githubusercontent.com/19418601/46626033-bf23b780-cb3e-11e8-9574-c4c199d2c0fb.png)
</details>

### Customer ID 
Так и не пришло ответное письмо в течении 10 минут, хотя писал два раза.

### Your environment
* Adguard version: 2.12.223
* Adguard filtering mode: Proxy (auto)
* Device model: OnePlus 3
* Operating system and version Android 8.1.0
* Rooted.
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? ExpressVPN, ProtonVPN, OpenVPN for Android, TunnelBear, SD Maid.

**Comment by ameshkov** [comment]
@Rakleed а можете логи вручную достать?

Они должны лежать в `/sdcard/data/Android/com.adguard.android/cache`

**Comment by Rakleed** [comment]
Это?
[adguard.log](https://github.com/AdguardTeam/AdguardForAndroid/files/2457193/adguard.log)

**Comment by ameshkov** [comment]
Ага, вижу, спасибо!

```
21:07:31.422 [main] WARN  com.adguard.android.ui.utils.n - Cannot show an CREATE_DOCUMENT dialog, looks like DocumentProvider does not exists. Let's try our file picker
21:07:31.445 [main] INFO  com.adguard.android.service.i - Setting language ru, System language is ru, from resources ru
21:07:32.448 [main] INFO  com.adguard.android.service.aq - Exporting log file to file://storage/emulated/0/adguard_logs_2.12.233_0810_2107.zip
21:07:32.475 [cached-pool-1-thread-63] INFO  com.adguard.android.service.aq - Exporting logs and system info to file://storage/emulated/0/adguard_logs_2.12.233_0810_2107.zip
21:07:32.477 [cached-pool-1-thread-63] ERROR com.adguard.android.service.aq - Error exporting a log file
java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:313) ~[na:0.0]
	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:211) ~[na:0.0]
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1242) ~[na:0.0]
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1007) ~[na:0.0]
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:983) ~[na:0.0]
	at com.adguard.android.service.aq.a(SupportServiceImpl.java:2208) ~[na:0.0]
	at com.adguard.android.service.ar.run(SupportServiceImpl.java:406) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by ameshkov** [comment]
@Rakleed вообще как вариант, возможно прав на запись в выбранную директорию у AdGuard нет

**Comment by Rakleed** [comment]
В настррйках разрешений доступ к памяти включён. Попытался сохранить в папку Download, тоже выдаёт ошибку.

**Comment by Rakleed** [comment]
@ameshkov в 2.12.242n проблема решена, жду теперь в релизной версии.
