### ISSUE TITLE
Add options of "Apps and Statistics" & "Filtering Log" in AdGuard's Notification Bar

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2164]
Hi,

**1. The option for Apps and Statistics:**
a. When **clicking** the option of "Apps and Statistics", **down show** the **hidden information** of Apps and Statistics with **apps' small icons and simple statistics of traffic** under the options of AdGuard's bar.
**(If not clicking the option of "Apps and Statistics", the information is hidden in routine.)**
b. Only show No.1~ No.15 or No.20 apps' ranks.
c. When tapping an app's small icon in the simple screen, open that app's **App info in Android settings**. 
I want to disable, force stop, uninstall or do other operations.
ex: Tap for opening its App info.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/gZco05z.png)
</details><br/>

d. The selection for showing the information during the period of today, past month and all-time.

**2. The option for Filtering Log:**
I wish a shortcut to fast open the filtering log in AdGuard's Notification Bar.
**Or add the shortcut of filtering log in "long press app shortcuts".**
<details><summary>Screenshot:</summary>

![image](https://cdn.adguard.com/public/Adguard/Blog/android212/longtap_en.png
)
</details><br/>

**3. The option for Task Manager:**
https://github.com/AdguardTeam/AdguardForAndroid/issues/2166
**Temporarily kill or forever forbid apps which I don't want them to work in the background.**

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/raBRd6Q.png)
</details><br/>

Thanks.

**Comment by vozersky** [comment]
merged into #3378
