### ISSUE TITLE
When holding down an app's bar in AdGuard's "Apps and Statistics", open that app's App info in Android settings.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2165]
I want to hold down an app's bar in AdGuard's "Apps and Statistics" for directly opening that app's App info in Android settings.
It's convenient to disable, force stop, uninstall or do other operations.

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/nn7hi7p.png)

![image](https://i.imgur.com/gZco05z.png)
</details><br/>

Thanks.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
