### ISSUE TITLE
Request for Task Manager in AdGuard app and its option in AdGuard's Notification Bar.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2166]
**This function may need root access, right?**

1. **Built in Task Manager**, such like the apps:
Greenify:
https://play.google.com/store/apps/details?id=com.oasisfeng.greenify

Advanced Task Manager:
https://play.google.com/store/apps/details?id=mobi.infolife.taskmanager

**Temporarily kill or forever forbid apps which I don't want them to work in the background.**

2. **Please also add "Task Manager" in AdGuard's Notification Bar after you design the function in AdGuard.**

a. When **clicking** the option of "Task Manager", **down show** the **hidden information** of Apps' tasks with **apps' small icons and the usage of memory or battery** under the options of AdGuard's bar.
**(If not clicking the option of "Task Manager", the information is hidden in routine.)**

b. Only show No.1~ No.15 or No.20 apps' ranks **according to the usage of memory or battery**.

c. When tapping an app's small icon in the simple screen, jump a pop-up for asking if temporarily killing or forever forbidding it. 

Thanks.

**Comment by ameshkov** [comment]
That'd be too problematic for us to implement, and it's kinda out of scope
