### ISSUE TITLE
Please add options to change dnscrypt-proxy settings

### ISSUE THREAD

**Issue by pashamcr** [AdguardTeam/AdguardForAndroid#2169]
The Internet does not work if dnscrypt-proxy + Tor integration is enabled in Adguard
Need to change the settings of dnscrypt-proxy.toml:
force_tcp = true
proxy = "socks5://127.0.0.1:9050" (no parameter in dnscrypt-proxy.toml for Adguard)
peeped here: https://github.com/jedisct1/dnscrypt-proxy/issues/603
i also need ipv6_servers = false
Is it possible to add options in Adgurd to configure the dnscrypt-proxy.toml file so that it is possible to set force_tcp and proxy for dnscrypt-proxy?

**Comment by ameshkov** [comment]
We don't use dnscrypt-proxy
