### ISSUE TITLE
Update DnsCrypt servers list

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2171]
There are some new servers in public resolvers list.

**Comment by lancelot-moon** [comment]
By the way, please add Quad101 DNS (don't mean Quad9 DNS) and CleanBrowsing DNS in the general DNS list.
Thanks.

Title: Quad101 DNS
Description: Free alternative DNS by TWNIC (Taiwan Network Information Center)
IPv4:
101.101.101.101
101.102.103.104

IPv6:
2001:de4::101
2001:de4::102

Title: CleanBrowsing DNS
https://cleanbrowsing.org/ip-address

**Comment by admitrevskiy** [comment]
Updated.

Testing instructions: 
-Reinstall AG
-Try to use new servers: 
eieiDNS (DnsCrypt)
Quad101 (Regular)
Cleanbrosing (Regular)

**Comment by lancelot-moon** [comment]
Hi, really thanks a lot!
May you add **brackets** for IPv6 in the next nightly version?
The same format with other DNS service (IPv6) in the list.

CleanBrowsing DNS **(IPv6)**
Quad101 **(IPv6)**

**Comment by lancelot-moon** [comment]
Hi, the description of CleanBrowsing Family DNS isn't on onesky.
CleanBrowsing Family DNS:
Blocks access to all adult, pornographic and explicit sites, including proxy & VPN domains and mixed content sites
