### ISSUE TITLE
AG does't show notification 'Enable HTTPS filtering ...' when certificate is removed

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2172]
Precondition: The HTTPS certificate installed, HTTPS filtering is ON.

### Steps to reproduce

1. HTTPS certificate removed

### Expected behavior

In side menu there is should the notification about HTTPS filtering is turned off.
### Actual behavior

In HTTPS filtering settings section AG detects that certificates has been removed - this is correct, but in side menu there is should the notification about HTTPS filtering is turned off.

https://uploads.adguard.com/as_859b1.png

**Comment by admitrevskiy** [comment]
This issue will be solved here: https://github.com/AdguardTeam/AdguardForAndroid/issues/2241
