### ISSUE TITLE
Youtube ads were not being blocked on Android - Note 9

### ISSUE THREAD

**Issue by madhu4target** [AdguardTeam/AdguardForAndroid#2173]
### Steps to reproduce

1. Start Adguard VPN Service
2. Open Youtube app from Note 9 Android phone ( with Oreo version)
3. Play any content. 
4. Ads will shoot up just like when there is no AdGuard

### Expected behavior

Expected not to have ads while YouTube is playing.

### Actual behavior

Stilll Ads were seen.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? 
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by CrescendoFang** [comment]
this problem is well documented...
get YouTube Vanced for ads-free YT...

**Comment by zebrum** [comment]
@madhu4target AdGuard can't block ads in youtube app, please read this [article](https://kb.adguard.com/en/android/solving-problems/youtube-ads).
