### ISSUE TITLE
Automatic dark/light theme

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2174]
Добавьте, пожалуйста, автоматически сменяемую темную / светлую тему в зависимости от времени суток. Приложения, в которых данная функциональность реализована: Telegram, Яндекс.Карты, Solid Explorer.

Возможнные варианты смены темы:
- [x] смена в зависимости от системной темы (Android 10 и выше, реализовано)
- [ ] смена в зависимости от времени суток
- [ ] смена в зависимости от степени освещения
- [ ] смена в зависимости от режима battery saver

**Comment by ameshkov** [comment]
Темная/светлая тема появятся в 3.0, а вот насчет автоматической смены - мы подумаем

**Comment by carlylemiii** [comment]
Rather than this (or maybe in addition to, I suppose), I'd love to see AdGuard follow Google's suggestions for handling dark themes, rather than the current implementation of an on/off toggle.

> When running on devices running Android 9 or earlier, the recommended theme options are:
> - Light
> - Dark
> - Set by Battery Saver (the recommended default option)

> When running on Android Q, the recommended options are different, to allow the user to override the system default:
> - Light
> - Dark
> -  System default (the recommended default option)

https://developer.android.com/preview/features/darktheme#changing_themes_in-app

**Comment by ameshkov** [comment]
@carlylemiii yeah, we're going to as a part of this task: https://github.com/AdguardTeam/AdguardForAndroid/issues/3053

**Comment by artemiv4nov** [comment]
Реализовано в 3.3 nightly 5

**Comment by artemiv4nov** [comment]
Необходимо доработать задачу, чтобы системная новая тема была по умолчанию для устройств с Android 10

**Comment by admitrevskiy** [comment]
Done.

**Comment by artemiv4nov** [comment]
@Rakleed возможность автоматической смены темы была интегрирована в приложение и поддерживается на Android 10.

**Comment by carlylemiii** [comment]
The system default option is available in 3.3 beta 1. Works great. :)

**Comment by Rakleed** [comment]
@artemiv4nov вы говорите про автосмену в зависимости от темы приложения или в зависимости от времени суток? Так как на Android 9 нет настройки для включения/отключения автосмены темы в зависимости от **времени суток**.

**Comment by Rakleed** [comment]
@artemiv4nov вы говорите про автосмену в зависимости от темы системы или в зависимости от времени суток? Так как на Android 9 нет настройки для включения/отключения автосмены темы в зависимости от **времени суток**.

**Comment by artemiv4nov** [comment]
Я имел ввиду автосмену в зависимости от темы системы.

**Comment by Rakleed** [comment]
@artemiv4nov, так я то в [своём сообщении](https://github.com/AdguardTeam/AdguardForAndroid/issues/2174#issuecomment-543104452) спросил, почему @zzebrum закрыл тему, если [я просил](https://github.com/AdguardTeam/AdguardForAndroid/issues/2174#issue-369879462) добавить поддержку автосмены темы в зависимости от **времени суток**.

**Comment by artemiv4nov** [comment]
@Rakleed 
Был запрос на автосмену темы. Мы реализовали автосмену для Android 10 в зависимости от системной темы.
Вопрос насчет автосмены в зависимости от суток/освещения/battery saver режима ещё на обсуждении.

**Comment by Rakleed** [comment]
@artemiv4nov, так зачем закрывать issue, если предложение ещё не реализовано?

**Comment by artemiv4nov** [comment]
@Rakleed потому что в рамках релиза 3.3 необходимая часть уже была выполнена.
Я добавил более полное описание для задачи и переоткрыл.
