### ISSUE TITLE
Автоматическая синхронизация настроек

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2175]
Добавьте, пожалуйста, автоматическую синхронизацию настроек между всеми устройствами. Особенно полезной будет синхронизация пользовательского фильтра.

**Comment by Eugene-Savenko** [comment]
@Rakleed это вроде бы давно в разработке: https://github.com/AdguardTeam/AdguardForAndroid/issues/134

**Comment by ameshkov** [comment]
Ага, притормозили из-за того что на новый движок перезжали

**Comment by Rakleed** [comment]
@ameshkov какие-то у вас огромные паузы – в целых 3 года...

**Comment by ameshkov** [comment]
Ох не сыпьте соль:)
