### ISSUE TITLE
Обновлённый Material Design

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2176]
Сделайте, пожалуйста, дизайн приложения в обновлённом Material Design. https://material.io
Примеры приложений с обновлённым дизайном: Google Календарь, Google Новости, Google Fit, Google Карты, Android Сообщения, Solid Explorer.

**Comment by ameshkov** [comment]
У нас редизайн почти готов, скоро увидите:)

**Comment by Rakleed** [comment]
А это будет похоже на то, что Google делает со всеми своими приложениями?

**Comment by Rakleed** [comment]
@ameshkov А это будет похоже на то, что Google делает со всеми своими приложениями?
