### ISSUE TITLE
Notification about HTTPS certificate removal

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#2177]
Сделайте, пожалуйста, так, чтобы после удаления HTTPS-сертификата появлялось уведомление об этом, и нажав на это уведомление, ты попадал в настройки "Фильтрация HTTPS".
А то после установки обновлений LineageOS и любых других кастомных прошивок сертификат для фильтрации HTTPS-соединений автоматически удаляется из системы.

**Comment by artemiv4nov** [comment]
К сожалению, нет технической возможности оперативно узнавать об изменениях в хранилище сертификатов.
