### ISSUE TITLE
Кнопка "Пожаловаться на сайт" в меню браузера "Поделиться"

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2178]
Добавьте, пожалуйста, в меню "Поделиться" для браузера ярлык "Пожаловаться на этот сайт" с иконкой AdGuard. И чтобы после нажатия на этот ярлык автоматически подставлялся сайт, браузер и настройки браузера.

**Comment by ameshkov** [comment]
Дубликат https://github.com/AdguardTeam/AdguardForAndroid/issues/2163
