### ISSUE TITLE
com.samsung.android.samsungpay.gear

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2180]
> Из-за последнего обновления перестало работать приложение для оплаты через смарт часы. Приложение просто не могло соединиться с сервером. Довожу до вашего сведения, что появилась данная проблема, которая заставляет добавлять приложения в исключения.

ID: 2016098

**Comment by ameshkov** [comment]
Added it to the default exclusions
