### ISSUE TITLE
Bypassed apps are disconnected in manual proxy mode

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2181]
1. At Adguard settings go to Advanced and choose Filtering mode - Local HTTP Poxy, Local Proxy Port - 8080, Local proxy setup mode - Manual. 
2. At general Android Settings go to Network and WiFi and choose advanced settings - manual proxy address 127.0.0.1:8080
3. Then check Google Chrome and Google PlayMarket.

### Expected behavior
Google Chrome and Google PlayMarket should be filtered and available 

### Actual behavior
 Google PlayMarket unavailable

![image](https://user-images.githubusercontent.com/41899455/46939979-4ce83100-d070-11e8-9927-b4467fd20788.png)

* Adguard version: 2.12
* Device model: Google Pixel/ Samsung Galaxy S7
* Operating system and version Android 9/8

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/CoreLibs #540](https://github.com/AdguardTeam/CoreLibs/issues/540) via [**ZenHub**](https://www.zenhub.com/)
