### ISSUE TITLE
[Android] Viber is losing the connection to the internet

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2182]
### Steps to reproduce

1. Open and start AdGuard
2. Open Viber
3. Use Viber for sometime

### Expected behaviour

Everything should be in order
### Actual behaviour
After sometime Viber is losing the connection. Switching between Mobile and Wifi networks causing connection break. This happens on release and nightly versions. Turning off the DNS/HTTPS filtering does not solve the issue.

Log files are available here:

2014132
1310221
2014269

**Comment by TheHasagi** [comment]
@ameshkov Пользователь говорит что такой вариант не помогает.

**Comment by karina-archazh** [comment]
I cant reproduce particular issue, but but there are some users who are experiencing the same problems.
