### ISSUE TITLE
UC browser does not support HTTPS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2183]
Please check the browsers with your script again.

**Comment by Alex-302** [comment]
It works
![image](https://user-images.githubusercontent.com/8361299/47002735-6fdd1880-d136-11e8-9c70-355e36e4ace4.png)

**Comment by nkartyshov** [comment]
This browser does not contain `networkSecurityConfig` and has not been added to the 
list of enforce https filtering apps.

Tested on version 12.9.5.1146 (10542).
