### ISSUE TITLE
UI validation error into whitelist settings

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2184]
### Steps to reproduce

1. Open Settings and go to Whitelist
2. Add dni.ru and lenta.ru
3. Tap on lenta.ru line
4. Tap on OK button into Enter domain name popup without any editing

### Expected behavior
Popup should be closed

### Actual behavior
There is validation error

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/47004140-8d5fb180-d139-11e8-9481-331547ec02a2.png)

</details>

### Your environment

* Adguard version: 2.12.xx
* Device model: Google Pixel
* Operating system and version Android 9

**Comment by artemiv4nov** [comment]
We reworked UI solutions in the v4.0 version, please update and try.
