### ISSUE TITLE
About the warning of "In order to enable HTTPS filtering for this app, you should turn it on system wide."

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2185]
Although there are more and more apps which don't trust AG certificate, the option of HTTPS filtering for merely a few apps is still checked by default.

When unchecking "HTTPS filtering", there is no the warning.
"In order to enable HTTPS filtering for this app, you should turn it on for system wide."

Is it a bug?
Or is the warning already unnecessary?

**Comment by zebrum** [comment]
@lancelot-moon 

you have https filtering disabled and cert is not installed, but in apps management it looks like https filtering enabled for an app, right? What exactly warning message are you talking about?

**Comment by lancelot-moon** [comment]
No, you're wrong.
HTTPS filtering is enabled, and AG certificate was installed.

**Comment by zebrum** [comment]
To show this warning https filtering should be disabled and cert is not installed. If it is still not the case you've described, you need to submit the issue with details using the template so we could understand step by step.

**Comment by lancelot-moon** [comment]
When will the warning appear?
Finally, I got it.
1. First enable HTTPS filtering and ever install AG certificate. Close AG.
2. Delete AG certificate from certificates store in security of Android settings.
3. Open AG. In App Management, if ticking the checkbox of HTTPS filtering, the warning will appear.

But the logic is strange there.
I tried v2.12.242η.

@ameshkov 
a. If existed AG certificate was deleted, it should show another warning which reminds a user that AG certificate isn't installed after opening AG (HTTPS filtering was "on" originally).

b. For the case, since AG certificate was deleted afterwards, HTTPS filtering would be "off" after opening AG.
The whole bar of "HTTPS filtering" in App Details should be **unselective**.

But the checkbox of "HTTPS filtering" in App Details isn't unselective in the actual situation.
Of course, when **trying** to tick the checkbox of "HTTPS filtering" in App Details, it'll show the warning, "In order to enable HTTPS filtering for this app, you should turn it on system wide" (buttons for cancel or learn more), because AG certificate isn't existed at that time. (The checkbox is unable to be ticked.)
I mean that the above mechanism is unnecessary.

The whole bar of "HTTPS filtering" in App Details should be **unselective** originally as long as HTTPS filtering is "off" (maybe HTTPS filtering is manually turned off, or AG certificate was deleted so HTTPS filtering is "off").

c. About this warning, "In order to enable HTTPS filtering for this app, you should turn it on system wide", there are 2 thought.
A. It can be simply unnecessary. Cancel the mechanism.
B. Or it can be modified as "In order to enable HTTPS filtering for this app, you should tick it".
It purely reminds users that it'll only do unencrypted HTTP filtering for this specific app (no HTTPS filtering) when cancelling the tick from the checkbox of "HTTPS filtering" in App Details.
But you know that now most apps already don't trust AG certificate.
For these apps, the checkbox of "HTTPS filtering" in App Details isn't ticked by default.
If ticking and then not ticking it, it should not show the warning for these apps.
The mechanisms maybe become complex.

Well, you decide it.
It's only my opinion.

**Comment by lancelot-moon** [comment]
It's not a question.
Simply redesign the logic there.
You don't understand my meaning...

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
