### ISSUE TITLE
Add Zalo app to ad blocking exclusions

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#2186]
### Steps to reproduce

1. Install Zalo app from Google Play Store (https://play.google.com/store/apps/details?id=com.zing.zalo&hl=en)

2. Open the app, tap "More" at the bottom right corner, then tap "Sticker" above.
![5e5bb749ac894cd71598](https://user-images.githubusercontent.com/22385284/47070391-4649ed00-d21b-11e8-83ef-18f7b38c3368.png)

3. The sticker store appears for a split second and then quickly disappears, as being blocked.
![edc30b2a10eaf0b4a9fb](https://user-images.githubusercontent.com/22385284/47070472-78f3e580-d21b-11e8-9e8b-8ca4187ef852.jpg)

The sticker store appears correctly when disabling AdGuard.
The sticker store works on the web version (https://chat.zalo.me/) so it seems something to do with the Mobile filter. 

4. Here is the filter log:
![a0b1364b2d8bcdd5949a](https://user-images.githubusercontent.com/22385284/47070577-c07a7180-d21b-11e8-9cb9-41f7b93d68e2.jpg)

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 2.12
* Adguard filtering mode: VPN
* Device model: Asus Zenfone Live
* Operating system and version: Android 6.0.1
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by zebrum** [comment]
Stickers doesn't load even if AdGuard is turned off completely on my side. Are you sure it's compatibility problem?

**Comment by snhv** [comment]
Hi, I'm very sure. I just tested again and successfully reproduced. Maybe your network is filtering?

This is the screenshot if I turn off AdGuard:
![d8db5610acde4c8015cf](https://user-images.githubusercontent.com/22385284/47145978-41f20280-d2f5-11e8-9359-8f654ee4476c.jpg)

The weird thing is: From AdGuard's filtering log, the domain 'm.stickers.zaloapp.com' went through. And the store appeared then disappeared quickly.

**Comment by zebrum** [comment]
yep, you are right :) my phone was connected to wi-fi with AG DNS.
 If uncheck ad blocking for this app, it's working.

**Comment by karina-archazh** [comment]
The issue still persists on 3.0 (Android 8.1)
