### ISSUE TITLE
Please add more in "long press app shortcuts".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2187]
Please add "Apps Management", "Filtering Log", "Toggle DNS" and "Send Feedback" in "long press app shortcuts".
<details><summary>Screenshot:</summary>

![image](https://cdn.adguard.com/public/Adguard/Blog/android212/longtap_en.png
)
</details><br/>

Thanks.

**Comment by TPS** [comment]
So, now I'm on Oreo/8.1, & don't see _any_ of these.  Are removed in ßv3.x?

**Comment by TPS** [comment]
Ah, nm, I think it's a Nova Launcher bug.

**Comment by TPS** [comment]
Ok, I got my AG long-press actions working!

A couple of requests:
- The current 2nd option reads "AdGuard" but probably should be "Assistant"
- Is it possible to have said menu expanded to the widget/shortcut?

**Comment by ameshkov** [comment]
Guys, the app shortcuts number is limited, we cannot just add everything there.

**Comment by TPS** [comment]
In v4.0v40, there are _no_ shortcuts @ all!

**Comment by artemiv4nov** [comment]
We will prepare a new functionality for shortcuts, just follow updates:) This task I'll close.

**Comment by TPS** [comment]
> We will prepare a new functionality for shortcuts, just follow updates:) This task I'll close.

@artemiv4nov _Why_ close?  What does that have to do w/ supposed eventual updates?
