### ISSUE TITLE
Previously used link always available in import popup 

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2189]
### Steps to reproduce

1. Go to Settings → User Filter → Import
2. Paste link https://raw.githubusercontent.com/AdguardTeam/TestCases/master/Filters/simple-rules/test-simple-rules.txt end tap on OK
3. After importing rules open the import popup again/or reopen Adguard and open the import popup again/or edit a link and reopen import popup

### Expected behavior
The link line in import popup should be empty
### Actual behavior
Previously used link is always in link line in import popup 

### Your environment

* Adguard version: 2.12

**Comment by ameshkov** [comment]
Actually, this is by design -- we want it to remember the last imported link.
