### ISSUE TITLE
[Android] Statistics issue

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2191]
AdGuard is able to count traffic in the statistics menu after disabling network access for the application.

### Steps to reproduce

1. Open AdGuard and start the protection
2. Disable network access and filtering for the application(s)
3. Check-in apps management - <app> - statistics

### Expected behavior

Statistics shouldn't be counted.
### Actual behavior

Statistics continue count app's traffic (grow)

Clip is available [here](https://drive.google.com/file/d/1TSBDyu7JK44Y-bY3QmQ5jr_2fw5hdw4S/view?usp=drivesdk)

### Customer ID 
1446690
### Your environment

* Adguard version: 2.12.234n
* Adguard filtering mode: VPN
* Device model: HTC M8
* Operating system and version: 8.1.0

**Comment by nkartyshov** [comment]
Cannot reproduce on the last nightly version. 
AdGuard does not filter the application if traffic filtering is disabled for this application, and also does not counting  traffic.
