### ISSUE TITLE
com.kabam.marvelbattle - fails to connect when the HTTPS filtering is enabled

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2193]
### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.kabam.marvelbattle&hl=ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.kabam.marvelbattle%26hl%3Dru)
### Comment
> Не смог запустить игру марвел битва чемпионов, пишет проблема с подключением, отключаю ваше приложение все нормально

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/6iNwXo8.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 6.0.1
AdGuard version: | 2.12.223
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Russian,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Japanese,<br>AdGuard Mobile Ads

**Comment by zebrum** [comment]
@Eugene-Savenko it's working on my side. Have you try to repro on latest nightly?

**Comment by Eugene-Savenko** [comment]
It works on my end but my testing device is... old, unfortunately. The user confirmed that disabling the HTTPS filtering helps so I went ahead and reported it here. We'll re-check and I'll let you know. Thanks.

**Comment by Eugene-Savenko** [comment]
Here's the ticket: 2012195

**Comment by zebrum** [comment]
Ask the user to try on latest 2.12.247 release. If the game won't work, collect debug log please and reopen this task.
