### ISSUE TITLE
Separate tabs for IPv4 and IPv6 DNS service lists in both regular DNS and secure DNS.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2194]
Now, IPv4 and IPv6 DNS service are mixed in the same list.
Some DNS service in the list are only for IPv4.
AdGuard doesn't list their IPv6 DNS service.

I wish IPv4 tab and IPv6 tab for separating them.
More complete lists.
Count this in.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1621

In the development of v3, please make good layout for DNS settings from the beginning.

**Comment by lancelot-moon** [comment]
@ameshkov 
@admitrevskiy 

ex: Quad9
You only add its IPv4 servers in the known general DNS list, but you don't add its IPv6 servers.
IPv4:
9.9.9.9
149.112.112.112

IPv6:
2620:fe::fe
2620:fe::9

My thought is to separately give IPv4 tab and IPv6 tab for complete lists of regular DNS and Secure DNS.
Now, you mix all IPv4 and IPv6 DNS service in the same list, which is not good.
This is the rough layout for your reference.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/PXsUsW5.png)

![image](https://i.imgur.com/DI8BNbD.png)
</details><br/>

Of course, this new layout of DNS settings including IPv4 and IPv6 tabs can be done in AG v3.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1621

**Comment by TPS** [comment]
Please make _optional_, as most folks using this are probably expecting all DNS servers in these lists to be _both_ IPv4 _&_ IPv6.

Maybe better to not show DNS who are _only_ 1 _or_ the other _until_ this option is toggled on? 🤷

**Comment by lancelot-moon** [comment]
Not most users wish IPv4 and IPv6 DNS service are all mixed in the same one list.
And the now IPv6 list isn't complete.

I supposed that you even don't understand what my thought is. XD

**Comment by TPS** [comment]
I _think_ I understand, @lancelot-moon, but, IMHO, I doubt most users are aware of many DNS not having both IPv4 & IPv6 addresses, hence my request to have less UI confusion.

**Comment by lancelot-moon** [comment]
IPv4 and IPv6 DNS servive are mixed in the same list, which is enought confusing!

What you talk about isn't the point.
You said, "many DNS not having both IPv4 & IPv6 addresses".
So...? Any association with my topic?

Collecting all DNS service in the list isn't the goal.
Who cares those other DNS service have both IPv4 and IPv6 service or not?

AdGuard only recruits representative and popular DNS service in the lists, and they have both IPv4 and IPv6 service.

Simply separate them into 2 zones.
When clicking or swiping on "for IPv4" / "for IPv6" tab, those DNS service are separately listed well there.

**Comment by lancelot-moon** [comment]
Outdated.
