### ISSUE TITLE
Inconsistent representation of the "Block ads" setting state inside Apps Management

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#2195]
STR:

1) Disable ad blocking for apps in "general settings"
2) Go to Apps Management, tap on any app
3) Go to "general" section

Expected result:

The checkbox is greyed out & unticked

Reality:

The checkbox is greyed out but ticked.

Screenshot: 
<details>
 <summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/8577533/47148026-380dd680-d2d8-11e8-903f-e65fce3b915a.png)
</details>

**Comment by Revertron** [comment]
fixed.
