### ISSUE TITLE
Flyme OS - HTTPS certificate issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2196]
@adguard-bot commented on [Mon Oct 15 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911)

### Issue URL (Incorrect Blocking)
[https://google.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgoogle.com%2F)
### Comment
Username: @kujibka1
> пытаюсь решить вопрос на 4пда c VasilyBagirov уже пару месяцев. Но к сожалению вопрос не решен до сих пор, да и сам VasilyBagirov перестал появляться в ветке на форуме. 
> Первое сообщение http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=75647590. 
> Последнее сообщение http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=76802136.
> Думаю большинство вопросов которые будут заданы мне от Вас, он уже спрашивал у меня и я на них отвечал. Собсно повторюсь. Проблема в сертификате. Ни один браузер не хочет с ним корректно работать в решиме фильтрации https.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dMHjHCU.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And meizu m2 mini, Android 5.1, Flyme 6.2.0.0G
AdGuard version: | 2.12.239
Browser: | Chrome (data compression)
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Base,<br>EasyList

---

@kujibka1 commented on [Mon Oct 15 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-429841428)

> 
> 
> Try reinstall `https` local AdGuard certyficate and reboot Android?

Reinstalled the certificate many times.
I install it only in the system partition.
I tried version 2.12.216 - 2.12.239
always doing a clean install.
I previously use sdmaid.
All the recommendations from the FAQ were executed correctly.
I tried different filtering modes (root installed).
Nothing helps.
sry My English is poor. I use Google translator.

@kujibka1 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430021499)

@Alex-302 во всех, оригинальная. никаких ОпераМакс и прочей лабуды работающей с сетью в телефоне нету. удалил.
@bogachenko 1. По настройкам считайте что дефолтные. первый десяток раз чистых переустановок в настройках я менял разве что режим фильтрации на локальный хттп прокси. Позже VasilyBagirov предложил проверить работу в режиме локальный ВПН. С тех пор тока так и тестирую последние 8 ночнушек. 
2. Вы используете файрвокс, рад за Вас. Мне нужен хром. Предлагать расширение адг мне не нужно.
3. Ещё раз говорю, Фраера никогда не было. Настройки сети не правил. Я уже говорил выше на что он агрится, на сертификат на данном телефоне. Версия адг 2.9.136 работает адекватно. херовую прошивку? Ещё предложите мне купить айфон.

---

@Alex-302 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430025062)

@krystian3w запишите полный лог 
https://kb.adguard.com/ru/android/solving-problems/log
когда включите запись полного лога, сделайте переустановку сертификата и запомните время. Потом загрузите логи сюда.

Ещё можно попробовать после этого очистить в меню "Шифрование и учётные данные" > "Учётные данные", перезагрузить телефон и повторить установку сертификата.

---

@kujibka1 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430240678)

@Alex-302 браузеры Meizu, Chrome, Yandex
![s80903-134604](https://user-images.githubusercontent.com/35925297/47020357-ddeb0500-d161-11e8-87fb-bad98e2f922d.jpg)
![s80903-134644](https://user-images.githubusercontent.com/35925297/47020360-ddeb0500-d161-11e8-818c-159a1f0269d9.jpg)
![s80903-134526](https://user-images.githubusercontent.com/35925297/47020368-e17e8c00-d161-11e8-949c-7a371776a77e.jpg)

---

@Alex-302 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430256245)

А можете проделать описанное выше? Перепутал адресата.

---

@kujibka1 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430257373)

@Alex-302  
> 
> А можете проделать описанное выше? Перепутал адресата.

facepalm:D без проблем. тока созрел вопрос. сертификат я буду устанавливать в системные, так как на опыте убедился, что в пользовательских он вообще не работает (оболочка Flyme отказывается его туда грузить). если я правильно понял нужна будет еще и перезагрузка после установки. не прервется ли в этом случае лог?

---

@kujibka1 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430269525)

@Alex-302  и скажите, какие еще логи Вам могут понадобиться? я бы мог их сразу все подготовить. logcat к примеру.

---

@Alex-302 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430310025)

> оболочка Flyme
> буду устанавливать в системные

в этом наверное и причина. Попробуйте серт из системных, очистить учётные данные, перезагрулиться и установить в обычное хранилище, а после этого очистить полностью данные браузера.

---

@Alex-302 commented on [Tue Oct 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430310324)

После установки в системное хранилище данные браузера тоже нужно очищать.

После всего этого можно лог прикрепить, с хронологией, чтоб быстрее искать.

---

@kujibka1 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430400622)

@Alex-302 
 мой алгоритм действий, если что то не правильно понял, уточните.
1. установил свежую ночнушку
2. в настройках почистил сертификаты
3. попробовал установить в обычное хранилище
23:53
**User ID**: 2017572
**Subject**: [PREMIUM] [Adguard for Android] Дефект

---

@kujibka1 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430403458)

@Alex-302 100% уверен что не установилось, как и говорил выше, из за Flyme. поэтому могу работать только с системным разделом и ручной установкой сертификата через файловый менеджер.

---

@Alex-302 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430405157)

Так, а с установкой в системное хранилище работает?

---

@kujibka1 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430407564)

Работает ли адг? тока так и работает

---

@kujibka1 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430634649)

@Alex-302 имеется ли принципиальная разница для фильтрации хттпс в отношении установки в какой либо раздел сертификата?

---

@Alex-302 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430683369)

после переноса иногда могут проблемы возникать. Уже не вспомню все, но данные браузера часто после этого нужно сбрасывать.

---

@kujibka1 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430684064)

@Alex-302 однако если я каждый раз переустановливаю браузер с очисткой данных, все ведь нормально должно быть?

---

@Alex-302 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430739887)

Я не знаю, что вы проделывали. Очистка данных что-то изменила?

---

@kujibka1 commented on [Wed Oct 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430740838)

@Alex-302 ничего не изменила во всех 3 браузерах. но стоит установить 2.9.136, установить сертификат в системные, все сразу начинает работать. причем даже без очистки данных в хроме и без перезагрузки телефона.

---

@Alex-302 commented on [Thu Oct 18 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23911#issuecomment-430972000)

В логе написано `HTTPs filtering is disabled or CA certificate is not installed`, т.е. не включена фильтрация HTTPS и попыток этого сделать не видно.

**Comment by ameshkov** [comment]
@kujibka1

Расскажите пожалуйста последовательность действий, которую использовали для установки серта в системные.

Ставили средствами AG? Или MoveCerts использовали?

Вопрос №2: что не так с установкой в пользовательские?

**Comment by ameshkov** [comment]
> работать только с системным разделом и ручной установкой сертификата через файловый менеджер.

Это по инструкции на 4пда да?

**Comment by ameshkov** [comment]
А работает ли такое:

1. Альтернативная установка серта в AG: он выгрузится на диск
2. Его импортировать вручную в пользовательский сертификаты

**Comment by kujibka1** [comment]
@ameshkov 

> Ничего себе у вас веселый там тред был

люблю иной раз посмеяться, если диалог идет в адекватном ключе)
перед тем как я отвечу на некоторые вопросы, хотелось бы протестить то, что я еще *наверное* ни разу не делал. очень интересно стало)

>     2\. Его импортировать вручную в пользовательский сертификаты

Вас не затруднит уточнить полный путь в папку пользовательских сертификатов? 
я правильно понимаю, что это он? /data/misc/user/0/cacerts-added

**Comment by ameshkov** [comment]
> Вас не затруднит уточнить полный путь в папку пользовательских сертификатов?

А импортировать нужно через настройки самого андроида

В обычном андроиде это находится так:
настройки - безопасность - мотаем в самый низ до раздела "Credential storage" и ищем там опцию Install from SD card или Install from device storage
во флайме наверняка переименовали и перенесли, но надеюсь этих ключевых слов достаточно будет чтобы найти

И еще момент, на всякий случай, снесите приложению AdGuard данные в настройках андроида.

**Comment by kujibka1** [comment]
> А импортировать нужно через настройки самого андроида

хааа, тогда именно по этой причине я и пользуюсь системным разделом) я думал можно в ручную через файловый менеджер закинуть в пользовательский раздел, но Вы просите через настройки это сделать)))
в общем отвечаю на вопросы.

> > сертификат я буду устанавливать в системные, так как на опыте убедился
> 
> Так, я понял, сертификат постоянно именно в системные устанавливался.

в целом я всегда устанавливаю сертификат в системные, так как пользовательское хранилище у меня работает не пойми как. НО так как:
> > оболочка Flyme
> > буду устанавливать в системные
> 
> в этом наверное и причина. Попробуйте серт из системных, очистить учётные данные, перезагрулиться и установить в обычное хранилище, а после этого очистить полностью данные браузера.

для записи логов я сделал попытку установить сертификат в пользовательское хранилище. видос того как я один в один делал для логов. https://youtu.be/XuL_07UM1AA

потому я и не удивлен сообщению ниже
> В логе написано `HTTPs filtering is disabled or CA certificate is not installed`, т.е. не включена фильтрация HTTPS и попыток этого сделать не видно.

> Расскажите пожалуйста последовательность действий, которую использовали для установки серта в системные.

Для этого второй видос https://youtu.be/ESNARLq9-nM

> > работать только с системным разделом и ручной установкой сертификата через файловый менеджер.
> 
> Это по инструкции на 4пда да

да, с 4пда. давно там сижу и на мой взгляд изучил всевозможные методы от туда вдоль и поперек. от безысходности написал сюда, потому и задался вопросом ЧЯДНТ.
> А работает ли такое:
> 
>     1. Альтернативная установка серта в AG: он выгрузится на диск
> 
>     2. Его импортировать вручную в пользовательский сертификаты

на этот вариант у меня такой видос https://youtu.be/vZwXdkKsZgA
постарался дать весьма исчерпывающую информацию. готов проделать любые манипуляции.

**Comment by nkartyshov** [comment]
@kujibka1 Пожалуйста, повторите установку сертификата через системное хранилище. Но перед этим надо включить уровень логгирование `Записывать всё`. 
Как это сделать: "Настройки" -> "Расширенные" -> "Уровень логгирования" переключите в режим "Записывать всё". 
После надо экспортировать лог: "Настройки — Расширенные" -> нажмите на пункт "Экспортировать логи и информацию о системе".

Лог отправите на почту devteam@adguard.com.

**Comment by kujibka1** [comment]
@nkartyshov 
прошу прощения, могу иногда задавать глупые вопросы. но что вы подразумеваете под "установку сертификата через системное хранилище."? может Вы хотели сказать "**_В_** системное хранилище", как я это делал на втором видосе? ведь, если я правильно понимаю, по умолчанию сам адг ставит его в пользовательское хранилище...

**Comment by nkartyshov** [comment]
@

**Comment by kujibka1** [comment]
@nkartyshov отправил лог на почту. тока уверен он ни чем не отличается от первого лога и там будет тоже самое что написал Alex-302. 

> HTTPs filtering is disabled or CA certificate is not installed
видос того как я это делал https://youtu.be/-U2dh2Lf4BM

**Comment by Revertron** [comment]
> видос того как я это делал https://youtu.be/-U2dh2Lf4BM
После нажатия на Ок в диалоге установки сертификата, где его название еще можно задать, должен появиться тост (сообщение) о том, что сертификат установлен. Но его нет, видимо система этого не делает.

**Comment by kujibka1** [comment]
@Revertron оф коз) потому я и говорю, что на флайме (не буду говорить за всех, говорю только про конкретный случай) пользовательский раздел работает не пойми как. но это все лирика. ранее я задавал вопрос
> @Alex-302 имеется ли принципиальная разница для фильтрации хттпс в отношении установки в какой либо раздел сертификата?

если нет, то я как и прежде готов его устанавливать в системный раздел, т.к. там он работает адекватно и без нареканий на примере 2.9.136

**Comment by kujibka1** [comment]
неужели на новых версиях адг не способен работать с системным разделом в моем случае?

**Comment by kujibka1** [comment]
@kujibka1 
![11446029-1514312698191659861](https://user-images.githubusercontent.com/35925297/47161913-a0ba7a80-d2fb-11e8-8100-6835017c0da1.jpg)

**Comment by zzebrum** [comment]
@kujibka1 что-то задача незаметно уехала в конец списка. Проблема актуальна?

**Comment by kujibka1** [comment]
@zzebrum уже не актуальна, не дождался. пришлось поменять прошивку на кастомную. там этой проблемы нету.
