### ISSUE TITLE
Cisco Webex doesn't work when it's routed through Adguard 

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2198]
### Steps to reproduce

1.Start webex meeting
2. Try to join this meeting through Webex app

### Expected behavior
You should be able to connect the meeting without any problems
### Actual behavior
There is a server connection error

You can connect Webex meeting after you turned down Enable checkbox in Webex App Settings into AdGuard

* Adguard version: 2.12
* Operating system and version Android 8/9

**Comment by TheHasagi** [comment]
The whole app should be excluded from filtering.

**Comment by nkartyshov** [comment]
done
