### ISSUE TITLE
AG v2.12.248η cannot parse power profile properly on LG G Pro (E988).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2199]
A similar issue as AdGuard on HTC U11 before.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2129

Well, LG G Pro (E988) is an old Android phone. (Android v4.4.2)
https://www.phonemore.com/lg-optimus-g-pro-e988/specs/1480
Battery capacity: 3140 mAh
8.318/3140=0.26%, but it showed 0.83%.
By the way, this battery for LG G Pro is already ageing very much.
Real battery capacity is maybe only a few...
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/lSeVXln.png)
</details><br/>

The log file: (record everything)
https://app.box.com/s/l7nvk3uhvypsk90ua1y04i55z0jde4s1

**Comment by zebrum** [comment]
@nkartyshov please take a look

**Comment by zebrum** [comment]
@lancelot-moon

`battery.capacity=1000.0 cpu.active=100.0 wifi.active=300.0 radio.active=300.0` -  in your firmware. I guess that's why AG shows those numbers.

**Comment by lancelot-moon** [comment]
@ameshkov 
So...?
Have you solve the bug?
In the older nightly version, AG can show correct battery usage %.
But AG v2.12.248η cannot parse power profile properly on LG G Pro (E988).
Do you not understand it's a bug?

**Comment by lancelot-moon** [comment]
I try some battery or monitor apps.
CPU-Z and AIDA64 can get correct design battery capacity on LG G Pro.
But some battery apps can't get correct design battery capacity.
