### ISSUE TITLE
Missing browser recognition: More Dolphin variants

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#22]
Ok, here's everything I found:

* https://play.google.com/store/apps/details?id=mobi.mgeek.TunnyBrowser (Main)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.engine (Separate engine & may identify differently)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.express.web (Apparently only available in certain countries)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.id (Indonesia has their own)

* https://play.google.com/store/apps/details?id=com.dolphin.web.browser.android (Old legacy)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.android.elex (Version 9)

&, as mentioned above,

* https://play.google.com/store/apps/details?id=com.dolphin.browser.zero (Private browser)

I'll edit if/when I find more.… ☺

**Comment by ameshkov** [comment]
Omg, one more dolphin? Why can't they stick to one app?

**Comment by TPS** [comment]
Do you want me to submit their complete list?  They even have different regional varieties! ;)

**Comment by ameshkov** [comment]
Would be great, it's better to check if we have them all:)

**Comment by TPS** [comment]
Ok, here's everything I found:

* https://play.google.com/store/apps/details?id=mobi.mgeek.TunnyBrowser (Main)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.engine (Separate engine & may identify differently)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.express.web (Apparently only available in certain countries)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.id (Indonesia has their own)

* https://play.google.com/store/apps/details?id=com.dolphin.web.browser.android (Old legacy)

* https://play.google.com/store/apps/details?id=com.dolphin.browser.android.elex (Version 9)

&, as mentioned above,

* https://play.google.com/store/apps/details?id=com.dolphin.browser.zero (Private browser)


I'll edit if/when I find more.… ☺

**Comment by ameshkov** [comment]
Thank you!

**Comment by TPS** [comment]
You're completely welcome. ☺

**Comment by Revertron** [comment]
Added missing package names. Thanks to TPS.

**Comment by TPS** [comment]
Could we add #18, #19, & #20, also?  Those 1st 2 are especially critical for me.… ☺

**Comment by Revertron** [comment]
Yes, I'll add them all.

**Comment by TPS** [comment]
Thanks!  How do I receive these updates?  I tried http://adguard.com/apkb, but the APK that downloads isn't installable.… ☺

**Comment by Revertron** [comment]
This issue is due to milestone 2.1, that is planned on September 3, 2015.
You'll have to wait for a week :)

**Comment by TPS** [comment]
I guess I'll wait patiently. ;)  I filed #25, though, to maybe do this in a more timely manner. ☺

**Comment by TPS** [comment]
@Revertron 
> milestone 2.1, that is planned on September 3, 2015.

Is this live now, or delayed?  I tried downloading, but neither official release nor beta is installing.…

**Comment by ameshkov** [comment]
Not yet ready, Amazon took some time. We cannot push the app to amazon until we integrate with their in-app subscriptions.
