### ISSUE TITLE
$csp rule not working

### ISSUE THREAD

**Issue by gontazaka** [AdguardTeam/AdguardForAndroid#2201]
### Steps to reproduce

1. Add following rules to User Filter
```
#%#AdGuard_onDOMContentLoaded=function(f){window.addEventListener('DOMContentLoaded',f);};
@@||twitter.com/*$csp=default-src AdguardTeam.github.io
@@||twitter.com/*$csp=style-src AdguardTeam.github.io
@@||twitter.com/*$csp=script-src AdguardTeam.github.io
mobile.twitter.com#%#AdGuard_onDOMContentLoaded(function(){const e=document.createElement('script');e.src='https://AdguardTeam.github.io/ExtendedCss/extended-css.min.js';document.head.appendChild(e);});
```
2. Go to https://mobile.twitter.com in Chrome Browser

### Expected behavior

a. "AdguardTeam.github.io"  is added to `Content-Security-Policy` of HTTP response header
b. ”extended-css.min.js” will be loaded

### Actual behavior

a. It is not added to the `Content-Security-Policy` of HTTP response header
b. Loading of "extended-css.min.js" is blocked by CSP

### details
Is **$csp rule** not supported on Android?
Similar problems have been reported.
https://forum.adguard.com/index.php?threads/csp-rule-for-android.29122/

### Your environment

* Adguard version:2.12.247 RC
* Adguard filtering mode: VPN
* Device model: Oneplus 5T
* Operating system and version: Oreo 8.1.0 [Lineage OS 15.1(RR-O-v6.2.0)]
* Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: No

**Comment by sfionov** [comment]
Yes, it is not supported yet, but will arrive to all platforms soon.
So, AdGuard 3.0 will likely have support for this rules.
We already have issue for this: https://github.com/AdguardTeam/CoreLibs/issues/15

**Comment by gontazaka** [comment]
Thank you for your reply. 
I am expecting it is a very interesting function.
