### ISSUE TITLE
Use Google breakpad instead of own native crash handler

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2205]
It integrates with Sentry better, because generates minidump files and breakpad symbol files, both are supported by Sentry.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #678](https://github.com/AdguardTeam/CoreLibs/issues/678) via [**ZenHub**](https://www.zenhub.com/)
