### ISSUE TITLE
RFC: UnInstall Tracking

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#2206]
https://www.bloombergquint.com/businessweek/now-apps-can-track-you-even-after-you-uninstall-them

Apparently, some ad networks are contracted to track app uninstalls & serve ads to get folks to reinstall.  I'd think all this is blocked via running AG, anyway, & the initial identification is the whole point of the upcoming stealth mode #2094 ← ~~#249~~, but I wanted to make sure all the concepts mentioned were/will be covered.

**Comment by zzebrum** [comment]
If you are using tracking protection in AG, there will be no difference )
