### ISSUE TITLE
Tapatalk app registration form doesn't work with Adguard local HTTPs proxy on rooted phone

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2207]
1. Go to Advanced ->  Filtering mode (Local HTTPs Proxy) and Setup mode Automatic
2. Install Tapatalk app
3. Try to complete theregistration 

### Expected behavior
Tapatalk account should be created 

### Actual behavior
Nothing happening.

**Comment by TheHasagi** [comment]
UserID: 2001601

**Comment by bungpaully** [comment]
Hello,
Error only happens when I'm connected to Wi-Fi not with data.
