### ISSUE TITLE
Differences in monitoring traffic between AdGuard and device

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2208]
### Steps to reproduce

1. Clear data and cache the app AG in device 
2. Disable the option: Apps Management -> Apps and Statistics -> Settings -> Defaults -> WiFi data / WiFi data when the screen
3. Mobile data is On
4. Chrome download 100MB file

### Expected behavior
 Correct traffic statistics is displayed in Apps management section for Chrome and Play Store.

### Actual behavior
 The traffic statistics discrepancies is displayed in Apps management section for Chrome and Play Store (in sections Apps and Single App) and device.

**Comment by ameshkov** [comment]
> 5. Go to the 'Play Store' and update the apps: Google 33MB, Microsoft Word 58Mb, Microsoft PowerPoint 56Mb, Microsoft Excel 57 Mb, SmartThings 48Mb.

This point complicates things a lot. Play Store filtering is disabled in AdGuard and that's why you won't see its traffic in the apps management section.

Please stick to some atomic actions (downloading a single file for instance) instead of overcomplicating the test case.
