### ISSUE TITLE
AdGuard does not start with the system if protection was disabled before rebooting the device

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2209]
It does not start at all if the protection is disabled and you reboot the system

### Steps to reproduce

1. Install v. 2.12.248
2. Configure AdGuard to start with the system
3. Enable protection and restart the system
4. Disable protection and restart the system

### Expected behavior

AdGuard starts with the system on both steps 3 and 4

### Actual behavior

It starts with the system on step 3 but fails to do so on step 4. The behavior is different on the release version, the app starts in both cases.

### Your environment

* Adguard version: 2.12.248
* Adguard filtering mode: VPN
* Device model: HTC One
* Operating system and version: 5.1
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Norton AV

**Comment by ameshkov** [comment]
I am not sure if that behavior is wrong actually, sounds like a feature to me:)

**Comment by ameshkov** [comment]
I'll mark it a bug, but the fix won't be included in the upcoming v2.12 hotfix
