### ISSUE TITLE
Update localizations

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2211]
Here's what we should do:

1. [x] Get rid of the old & unused strings
2. [x] Initial proofread of all the English strings
3. [x] Fix language switcher
4. [ ] Upload strings to oneskyapp and update the screenshots
5. [x] Check that outdated translations aren't broken too much

**Comment by ameshkov** [comment]
Another thing we should do: if changes to the format string are major -- rename the string. It will invalidate all the outdated translations.
