### ISSUE TITLE
Rework Filtering Log UI

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2217]
Rework Filtering Log module UI

**Comment by karina-archazh** [comment]
Fix header buttons and Search line:

<details>

![image](https://user-images.githubusercontent.com/41899455/48483912-c87efe80-e825-11e8-9594-c2fdae7c310a.png)

</details>

**Comment by admitrevskiy** [comment]
Done.

**Comment by aspasskaya** [comment]
Fix header buttons and Search line - Ok. The search and filtering icons disappear after: 
1. In search write - mail
2. Tap on three dots button at the right corner of the header and enable the option "Filter requests" the "Ok"
3. Backward to the "Filtering log"

https://uploads.adguard.com/Screenshot_2018-11-16-19-23-24.png

**Comment by TPS** [comment]
In Dark mode, green, red, &c, highlighting doesn't have enough contrast to notice clearly, though it's fine in Light mode.

**Comment by admitrevskiy** [comment]
@aspasskaya Done. Please, examine the Filtering Log in the next nightly.

**Comment by ameshkov** [comment]
Please fix the margin of the filtering rule item - it looks weird at the moment

**Comment by admitrevskiy** [comment]
Done. 
No more margins for the filtering rules

**Comment by TPS** [comment]
> In Dark mode, green, red, &c, highlighting doesn't have enough contrast to notice clearly, though it's fine in Light mode.

This has been re-fixed recently.  Thanks! 🙇🏾‍♂️
