### ISSUE TITLE
Disable Whitelist function does not work

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2218]
### Steps to reproduce

1. Go to Settings -> Content Blocking -> Whitelist
2. Tap on three dots button at the right corner of the header Disable Whitelist

### Expected behavior
 Whitelist inactive and checkboxes disabled.  

### Actual behavior
 Whitelist active and checkboxes enabled. 
![image](https://user-images.githubusercontent.com/43952607/53731113-cb603680-3e8a-11e9-90d4-9488e7c8f3f3.png)

**Comment by karina-archazh** [comment]
Checked and fixed v3.0.27

**Comment by aspasskaya** [comment]
![image](https://user-images.githubusercontent.com/43952607/53577677-24785380-3b87-11e9-9aa3-30c66551f716.png)
![image](https://user-images.githubusercontent.com/43952607/53577697-2c37f800-3b87-11e9-8588-a4d08a0c6e6d.png)
![image](https://user-images.githubusercontent.com/43952607/53577712-32c66f80-3b87-11e9-9154-2e48cec6fe93.png)
