### ISSUE TITLE
When installing the AG certificate (https filtering) does not ask the pattern  (5,6 Andriod)

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2221]
### Steps to reproduce

1. Go to Settings -> Network -> HTTPS Filtering -> Install certificate
2. Go to lenta.ru - Expected result: Certificate AG used

### Expected behavior
 Ask the pattern. Certificate installed successfully.

### Actual behavior
 Doesn't ask the pattern. Certificate installed successfully.

**Comment by ameshkov** [comment]
I don't fully understand what's the issue here if the cert is installed successfully anyway? Please explain.

**Comment by zzebrum** [comment]
It seems we've just confused tasks.
