### ISSUE TITLE
In home screen the message 'get premium' in white rectangle in dark theme

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2223]
### Steps to reproduce

1. Enable Dark Theme

### Expected behavior
 Without white color in Home screen.

### Actual behavior
 Only black color in Home screen.

https://uploads.adguard.com/Screenshot_2018-10-31-15-13-39.png

**Comment by karina-archazh** [comment]
Checked and fixed
