### ISSUE TITLE
User filter browse menu has validation error after adding file from phone storage

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2225]
For reproducing this issue you should one time import settings already

### Steps to reproduce

1. Open a Open Settings -> Content Blocking -> User Filter
2. Tap on three dots button
3. Choose import 
4.  Tap on OK

### Expected behavior
Filters from storage files should be added or there should be a notification "Error importing rules" (in case of wrong type of file), but this menu should be hidden after tapping on OK button 

### Actual behavior
Validation Error and this menu hiding only after browsing for rule file and adding it.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/47791999-10812a00-dd2c-11e8-96ea-9896cbd47bd6.png)

</details>

### Your environment

* Adguard version: 3.0.24
* Device model: all testing models
* Operating system and version all testing versions
*

**Comment by admitrevskiy** [comment]
We also need to fix the UI for this import dialog. Waiting for fixes in the Abstract.

**Comment by admitrevskiy** [comment]
Resolved
