### ISSUE TITLE
Add the ability to delete and edit comments individually

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2228]
The user can edit the filters individually, but comments for editing are available only through a bulk function.
Is it possible to add the ability to delete and edit comments in the User Filter menu?

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/47794958-956f4200-dd32-11e8-8d1a-54917fce117b.png)

</details>

### Your environment
For all testing models.

**Comment by TPS** [comment]
Also, comment editing shouldn't require AG restart (unless the comment is actually a filter that's being enabled/disabled, I suppose, but that's handled better via ☑️, anyway).

**Comment by admitrevskiy** [comment]
Resolved. Protection is not restarted anymore after add/remove/edit comments.

**Comment by aspasskaya** [comment]
[UI] Black frame and cursor on the keyboard. 
### Steps to reproduce
1. Tap on three dots button at the right corner of the header
2. Tap on edit filter

#
https://uploads.adguard.com/edit_filters.jpeg
