### ISSUE TITLE
Adguard doesn't unpause protection when Internet network is switched back on

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#223]
Once paused, protection doesn't turn on again when network restarts.

VVK-937-19406 - logs example

**Comment by TPS** [comment]
What?! #2 _again_?  This 1s like Dracula.… :confounded:

**Comment by vbagirov** [comment]
More logs from a different user: LMB-829-60772

**Comment by ameshkov** [comment]
I bet the issue is in Android killing our app because it can.

But let's have an open issue on github so we collect all complaints in one place.
