### ISSUE TITLE
Loading icon duplicated

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2230]
### Steps to reproduce

1. On Main page open Ad blocked diagram 
2. Tap on time section menu
3. Choose any and proceed

### Expected behavior
There should be only one loading icon.

### Actual behavior
Icon duplicated

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/47802239-eb4ae680-dd40-11e8-8777-8868a65082d9.png)

</details>

### Your environment
For all testing devices

**Comment by admitrevskiy** [comment]
Resolved.
