### ISSUE TITLE
[Android] Application loading extremely slow with local proxy mode (auto)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2231]
[Application](https://play.google.com/store/apps/details?id=be.persgroep.android.news.mobilead&hl=en) loads extremely slow with local proxy (auto) filtering mode.

### Expected behavior

App should load as normal
### Actual behavior

App loads after a couple of minutes (sometimes it crashes)

### Customer ID 

1886079 (log files are available)
### Your environment

* Adguard version: 2.12.247
* Adguard filtering mode: Proxy
* Device model: Galaxy S6 Edge Plus
* Operating system and version Android 7
* Rooted or not? - Rooted

**Comment by zebrum** [comment]
@TheHasagi have you try to repro?

**Comment by TheHasagi** [comment]
@zebrum 

Yes, reproduced successfully.

**Comment by artemiv4nov** [comment]
Well, I think now the application loads correctly, I'll close the task.
