### ISSUE TITLE
Change "Disable" to "Enable" into Whitelist menu when all exception is manually disabled

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2232]
### Steps to reproduce

1. Go to Setting ->Content Blocking -> Whitelist
2. Add lenta.ru and dni.ru into the whitelist
3. Disable all checkboxes manually
4. Open options menu

### Expected behavior
If all whitelisted sites are disabled manually then this option should be enabled all whitelist sites 

### Actual behavior
Asking for disabling all disabled sites.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/47842227-2266d980-ddcd-11e8-9f58-7e623f826d94.png)

</details>

### Your environment
For all testing devices

**Comment by ameshkov** [comment]
The wording might be not ideal, but anyway - there is no connection between disabling the whitelist completely and disabling an individual entry.
