### ISSUE TITLE
Failed test: Проверка обновлений фильтров

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2235]
### Steps to reproduce
1. Попробовать обновить фильтры вручную.
2. При отсутствии обновлений внести изменения в один из фильтров, повторить попытку обновления через 5-10 минут.
### Expected behavior
Включенные фильтры обновлены.
### Actual behavior

https://uploads.adguard.com/last_image.png

**Comment by aspasskaya** [comment]
Test!!!!!
