### ISSUE TITLE
Failed test: Test WIFI data checkbox availability

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2236]
### Steps to reproduce
1. Turn down your phone Cellural data in settings
2. Tap on WIFI data checkbox and turn off the check
Expected Result:
There should be a warning message firstly.
After applying new settings there should be notification "The statistics cleared successfully";
3. Open any browser and check Internet connection
Expected Result:
Internet connection should be down.

### Actual behavior

**Comment by aspasskaya** [comment]
Test!!!
