### ISSUE TITLE
ru.tinkoff.mvno

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2239]
@adguard-bot commented on [Wed Aug 01 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20538)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=ru.tinkoff.mvno](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.tinkoff.mvno)
### Comment
Username: @Rakleed
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/mjT69Eu.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | 2.12.140β
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Russian,<br>Mobile Ads,<br>Annoyances,<br>English,<br>Spyware,<br>Social media

---

@BlazDT commented on [Wed Oct 31 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20538#issuecomment-434637628)

Please check @Alex-302 - I don't understand the app - it is asking for mobile number probably and will probably only work with Russian phone.

**Comment by zzebrum** [comment]
@karina-archazh please check

**Comment by karina-archazh** [comment]
@Rakleed please update AdGuard app to release version 2.12.247
As I see this issue only persist on 2.12.140β version.

**Comment by zzebrum** [comment]
so, @Brawlence @rakleed can you confirm the app is working on your devices?  It seems to be ok on my side.

**Comment by Rakleed** [comment]
@zzebrum у меня на данный момент на версии 3.0.297 работает без проблем.

**Comment by Brawlence** [comment]
@zzebrum Yep, it's fine now. Thank you.
