### ISSUE TITLE
Change the text notification (install manual HTTPS certificate)

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2240]
### Steps to reproduce
1. Go to the 'Certificate status’ -> 'Settings -> Network -> HTTPS Filtering -> Install manually'. Next 'Ok' 
### Expected behavior
Change the text filename extension 'adguard.crt'. Right - .cer 
### Actual behavior
Change the text filename extension 'adguard.crt'. Wrong - .cer 

https://uploads.adguard.com/Screenshot_2018-11-01-18-31-42-944_com.adguard.android.png

**Comment by nkartyshov** [comment]
Fixed
