### ISSUE TITLE
Protection suggestions wizard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2241]
Check the sketch files.

Suggestions steps:

1. Ad blocking (enabled by default) 
2. HTTPS filtering (greatly improves ad blocking quality) 
3. Blocking ad trackers in apps (requires trial or premium)    
4. Blocking phishing and malware
5. Premium license

**Comment by karina-archazh** [comment]
Some of the options doesnt persist yet

**Comment by zzebrum** [comment]
yep, wizard disappear after request trial. It should stay and show 99% progress bar

**Comment by nkartyshov** [comment]
done

Test instruction:

Activate trial period:
1. Install AdGuard
2. Go to Protection level screen
3. Enable https filtering
4. Request a trial period

Expected result:
The screen should update and percent should have 99% 

Activate premium:
1. Install AdGuard
2. Activate premium license
3. Go to Protection level screen
4. Enable https filtering

Expected result:
The percent should have 100% and bottom panel with the protection level should be hide on the main screen

Activate expired premium:
1. Install AdGuard
2. Activate premium license
3. Go to Protection level screen
4. Enable https filtering

Expected result:
The percent should have 80%

**Comment by zzebrum** [comment]
After the license expires, the wizard does not appear.
