### ISSUE TITLE
Adding custom filters does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2242]
It looks like we're importing a file instead of adding a custom filter

**Comment by zebrum** [comment]
#2226 I guess

**Comment by ameshkov** [comment]
> #2226 I guess

Not really, but #2226 is a valid bug as well

**Comment by ameshkov** [comment]
Custom filters are getting removed after the first update check

**Comment by karina-archazh** [comment]
1. Add to custom filters https://raw.githubusercontent.com/AdguardTeam/TestCases/master/Filters/simple-rules/test-simple-rules.txt

2. Go to http://testcases.adguard.com/Filters/simple-rules/test-simple-rules.html

Custom filter subscription doesn't work.
