### ISSUE TITLE
User filter and whitelist changes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2243]
1. [x] Decrease rows height
2. [x] Use monospace font
3. [x] There's no "Delete" item in the menu 
4. [x] No "Cancel" button in the confirmation dialog when I am trying to delete a rule
5. [x] No "Edit" dialog when I click on comment rows
6. [x] Rules text is lower case when I use search (how did you manage?)

**Comment by admitrevskiy** [comment]
Resolved.
