### ISSUE TITLE
Remove the info pop-up message (install manual HTTPS certificate)

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#2247]
### Steps to reproduce
1. Go to the 'Settings -> Network -> HTTPS Filtering -> Install manually'. Next 'Open settings' 

Expected Result:
- Security settings opened
- 'adguard.cer' installed in system from 'Install certificate from storage or SD card'

2. Go back to AdGuard using arrow button

### Expected behavior 

HTTPS filtering is On. Info Pop-up about saving certificate is hiding.

### Actual behavior

HTTPS filtering is On. Info Pop-up about saving certificate doesn't hide.

https://uploads.adguard.com/Screenshot_2018-11-01-19-03-05-188_com.adguard.android.png

**Comment by admitrevskiy** [comment]
Done
