### ISSUE TITLE
Fix new Apps management UI issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2248]
1. [x] Unicode symbols are too huge on Samsung
2. [x] Limit the rate of icons loading to the icons cache
3. [x] HTTPS filtering is still available when I uncheck "Enabled"
4. [x] No "Cancel" in the HTTPS warning dialog
5. [x] It's not possible to understand the bulk change menu
6. [x] "Reset settings" warning dialog: cancel should be under okay, not above
7. [x] Special warning on the Google Play service should be designed
8. [x] Issue with app permissions: if there're no apps permissions access, changing cellular/wi-fi access does nothing and there's no toast/notification about it

**Comment by karina-archazh** [comment]
please change these green icons:

<details> 
![image](https://user-images.githubusercontent.com/41899455/48127079-ec759980-e293-11e8-8485-a8d2c98a5b64.png)

 </details>

**Comment by karina-archazh** [comment]
Please fix the header buttons: all buttons should stay on header in any case.
