### ISSUE TITLE
Option "Block all ads" in Content Blocking going of after exiting this menu

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2251]
### Steps to reproduce

1. Go to Settings -> Content Blocking and on the option "Block ads in all apps".
2. Then go to another menu or a different app.
3. Go back to Content Blocking 

### Expected behavior
Option should be on
### Actual behavior
Option is off

### Your environment
For all testing devices

**Comment by admitrevskiy** [comment]
Resolved.
