### ISSUE TITLE
Need line breaks in the DNSCrypt information when manually adding DNSCrypt server.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2253]
When using English interface, there are line breaks in the DNSCrypt information.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Qvkb9PD.png)
</details><br/>

**But when using Traditional Chinese interface, there is no line break for "No logs" and "No filters" in the DNSCrypt information.**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ElRnYsp.png)
</details><br/>

Please fix it.

**Comment by admitrevskiy** [comment]
Resolved

**Comment by lancelot-moon** [comment]
The bug was fixed in v3.0.66η
