### ISSUE TITLE
HTTPS filtering option doesn't ask about certificate installation 

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2254]
After clearing storage and re-installing AdGuard app HTTPs filtering option is on without asking about  AdGuard certificate installation.

1. Clear storage in device app settings
2. Re-install Adguard app
3. Enable filtering on main page
4. Go to Network -> HTTPs Filtering and tap on

### Expected behavior
Adguard app should ask about AdGuard certificate installation

### Actual behavior
Just notification about restarting protection

### Your environment
For all testing devices

**Comment by Revertron** [comment]
Not actual or can't reproduce.
