### ISSUE TITLE
Custom filters disappear after the app update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2264]
Subj

Another issue:
> custom filters are not restored from the backup either, please fix

**Comment by TPS** [comment]
Context?  I haven't had this happen @ all.…

**Comment by TPS** [comment]
Oh, wait, does this refer to user filters or custom filter*list*s?

**Comment by ameshkov** [comment]
Custom

**Comment by TPS** [comment]
The name is confusing, when individual ad-blocking patterns & lists of such are both called filters.  IMHO, the 1st is a filter & the 2nd is a [filter*list*](https://filterlists.com/).  May I propose to change the UI wording to clarify?

**Comment by ameshkov** [comment]
filter != a single rule, filter is a set of rules (what you call filterlist).

We would need to rename user filter to user filterlist as well

**Comment by TPS** [comment]
The terminology has never been used anyplace else that way, but has been standardized as I defined above — e.g., https://help.getadblock.com/support/solutions/articles/6000161377-how-to-use-custom-filters.

**Comment by lancelot-moon** [comment]
After simply reopening AG v3.0.72η (I didn't enable AG protection), custom filters disappear...

**Comment by lancelot-moon** [comment]
> filter != a single rule, filter is a set of rules (what you call filterlist).
> 
> We would need to rename user filter to user filterlist as well

Honestly, renaming it to **user rules** is better.
I don't think it's a filter from the past until now.

**Comment by patrickdrd** [comment]
custom filters are not restored from the backup either, please fix

**Comment by patrickdrd** [comment]
they don't work either, I added the ublock filter from:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt
and it blocked facebook video (video.fath3-4.fna.fbcdn.net),
when I searched for such url in the filter, there wasn't any

also, they are 'hard' to disable, disabling from main filters screen didn't work,
I had to open the custom filters and then pull the on switch.
AG didn't even restart in such an event,
I guess there's a lot of work to be done with them to work yet

**Comment by nkartyshov** [comment]
Fixed

Testing instructions:
1. Add a custom filter
2. Enable a custom filter
3. Update the filters
4. Restart app

Expected
A custom filters should be persist
