### ISSUE TITLE
Add removed html elements into filtering option in Filtering log

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2265]
Go to filtering log and on header tap on filters option.
Removed elements arent filtred.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/48276620-7c187500-e459-11e8-80ea-084cf007f599.png)

### Your environment

For all tested devices

**Comment by admitrevskiy** [comment]
Resolved.
