### ISSUE TITLE
Please change darkgreen to graceful/soft green in AG v3 if possible.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2267]
@ameshkov 
The darkgreen is too dark...
I like black theme, but prefer soft green or other graceful and **comfortable** green color with black.
The disconsolate darkgreen lets me feel melancholy.
**I think a good app interface should let users feel comfortable.**
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/EPLRYCr.jpg)

![image](https://i.imgur.com/0BcRluj.png)
</details><br/>

For your reference... though blue color is also good.
I think original bright green, **Jungle green** (Hex #29AB87), **Persian green** (Hex #00A572), **Kelly green** (Hex #4CBB17) or **Paris green** (Hex #50C878) is very good for AdGuard!
Well, maybe you can try **Russian green** (Hex #679267).
Green:
https://graf1x.com/shades-of-green-color-palette-html-hex-rgb-code/

Blue:
https://graf1x.com/shades-of-blue-color-palette/

Color codes:
https://htmlcolorcodes.com/

Really thank AdGuard team.
But the darkgreen is army green.
I like black theme, but dislike everything is dark.
AG team can use other young and vivacious green instead of darkgreen.

Bright green, gray green or soft green...etc.
I wish AG team to try different green for the interface of v3.

**Comment by ameshkov** [comment]
What's important -- adding new themes is not a big problem anymore so if you want something else, you will be able to propose it here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2275

Wait for v3.0 release, though (we will post the color palette to #2275).
