### ISSUE TITLE
Invalid rule created using filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2269]
### Steps to reproduce

1. Try to 

### Actual behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/48280120-5c824c00-e45b-11e8-83c1-68eda20a98ce.png)

</details>

### Expected behavior

`IP:port$network`

### Your environment

* Adguard version: 3.0.56 nightly

**Comment by Alex-302** [comment]
Another case
`@@||graph.facebook.com^$domain=graph.facebook.com,app=com.piriform.ccleaner`
wrong modifier `domain=` in the rule for an app
AG 3.0.182

**Comment by admitrevskiy** [comment]
Done.
Testing instructions for QA:
-Reinstall AG
-Try to add any filtering rule for app

Expected result:
-There is no `domain` modifier in filtering rule
