### ISSUE TITLE
Add Link Bubble Browser to the browsers list

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#227]
https://play.google.com/store/apps/details?id=com.linkbubble.playstore

Adguard doesn't block ads in that browser

[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/61070/debug.1.txt)

**Comment by ameshkov** [comment]
@evgeniy-ADG do you mean that ads aren't blocked in non-premium AG?

**Comment by ameshkov** [comment]
Added to the browsers list

**Comment by TPS** [comment]
Now that Link Bubble is now [Brave](https://github.com/brave/), with [a specific, targeted plan re: the ads it displays](https://www.brave.com/blogpost_4.html), does AG's handling of it need to change in any fashion?  This issue is also relevant, perhaps, on all other platforms that AG develops.…

**Comment by ameshkov** [comment]
@TPS we should make sure that brave own ads are blocked.

**Comment by TPS** [comment]
*That*'s __precisely__ why I brought it ↑.…  Also, maybe change name of this issue to reflect browser name & possible focus change?
