### ISSUE TITLE
Crash when press on the filter's tag [AdGuard 3.0.56n]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2270]
![image](https://user-images.githubusercontent.com/8361299/48280640-dcf57c80-e45c-11e8-9c5a-3f2a9ce80ead.png)

**Comment by admitrevskiy** [comment]
Done.

This bug occurs only in the release build
Testing instructions for QA:
-Reinstall AG
-Go to `Settings` -> `Content blocking` -> `Filters` -> Open any filter category.
-Tap on filter's tag

Expected result:
Bottom dialog with tag summary appears

**Comment by aspasskaya** [comment]
Crashed the app after tapping on tag "id" in Language specific filter - ABPindo.
# 
https://uploads.adguard.com/Screenshot_2018-11-22-20-01-41-548_com.adguard.android.png

**Comment by admitrevskiy** [comment]
@aspasskaya There is no description for this tag =(
Please examine tags behaviour in the next nightly, everything should be ok

Expected result:
-Nothing happens on tag tap if there is no description.
