### ISSUE TITLE
Tracking parameters in Stealth mode are separated using space

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2271]
![image](https://user-images.githubusercontent.com/8361299/48281965-00222b00-e461-11e8-8e6b-4b48a68c3cf6.png)

**Comment by TPS** [comment]
Honestly, is it possible to change the textbox type (of this & similar) to multiline (like in user filterlist)?  As you can probably see, this is _very_ messy/unclear, especially when the contents are so similar!
