### ISSUE TITLE
After shifting from Traditional Chinese to English interface, it's still Traditional Chinese somewhere. (AG v3)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2272]
After shifting from Traditional Chinese to English interface, it's still Traditional Chinese somewhere.
Ex: It should show "Feedback", not its translation.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/l9SqjMO.png)

![image](https://i.imgur.com/BvORJ2e.png)
</details><br/>

I didn't check everywhere.
You can check everywhere by yourselves.

**Comment by aspasskaya** [comment]
In the new version, it's Ok
https://uploads.adguard.com/merge_from_ofoct.png 
Please, try to reboot the system and confirm you've tried.

**Comment by lancelot-moon** [comment]
Of course, Traditional Chinese is the system language on my Android device.
