### ISSUE TITLE
Can't go back to the previous screen when cancelling a feedback. (AG v3)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2273]
I want to go back to the previous screen.
If I click **"back" button in AG app** or click **"back" real button on an Android device** but don't choose any feedback type, I can't leave the screen.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/DA9GrmK.png)

![image](https://i.imgur.com/AbFX0SG.png)
</details><br/>

Please fix it.

**Comment by Revertron** [comment]
Fixed in PR 818.

**Comment by lancelot-moon** [comment]
The bug was fixed in v3.0.66η.
