### ISSUE TITLE
Filtering log doesn't show `$replace` rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2274]
@AdamWr commented on [Fri Nov 09 2018](https://github.com/AdguardTeam/CoreLibs/issues/605)

### Steps to reproduce

1. Add this rule to user filter - `||example.org^$replace=/Example/Hello/`
2. Go to http://example.org/

### Expected behavior

Filtering log should show `$replace` rule.

### Actual behavior

Filtering log doesn't show `$replace` rule.

<details><summary>Screenshots:</summary>

![screenshot_2018-11-09-19-44-33](https://user-images.githubusercontent.com/29142494/48281840-2ee7d380-e458-11e8-9a54-345a7d132d8d.png)
![screenshot_2018-11-09-19-44-56](https://user-images.githubusercontent.com/29142494/48281844-314a2d80-e458-11e8-808f-12390182e56d.png)
![screenshot_2018-11-09-19-45-23](https://user-images.githubusercontent.com/29142494/48281848-34451e00-e458-11e8-8774-6778fed52568.png)

</details>
<br>

AdGuard 3.0.56 nightly

**Comment by admitrevskiy** [comment]
Resolved.
