### ISSUE TITLE
More UI themes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2275]
This feature request is for any theme/color change requests. If you want to propose a new theme, supply the colors you'd like it to use.

**However, wait for us to post the color palette here (we will do it after the v3.0 release).**

**Comment by lancelot-moon** [comment]
Compared with app bugs, the theme isn't so important for the developers, but unsuitable themes affect users' experience and mood.

Thanks for your understanding!
Love AdGuard team. <3

**Comment by lancelot-moon** [comment]
Hi, compared with theme selector, it's greater for the color palette in the future updates!
But some other users already think it's better if you use slightly brighter green as the default theme, not only me.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/diiIaAd.png)

![image](https://i.imgur.com/ssDQ6z3.png)
</details><br/>

**May you first modify the default theme as the below in the next v3 nightly version?**
I used these color.
Kelly Green
Codes:
Hex #4CBB17
RGB 76 187 23

Persian Green
Codes:
Hex #00A572
RGB 0 165 114

Salamander Orange Color
Codes:
Hex #F05E23
RGB 240 94 35

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/bdbeRip.png)

![image](https://i.imgur.com/2KxSPaT.png)

![image](https://i.imgur.com/M8VZ8GS.png)

![image](https://i.imgur.com/Sa7Lpva.png)
</details><br/>

Green:
https://graf1x.com/shades-of-green-color-palette-html-hex-rgb-code/

Orange:
https://graf1x.com/shades-of-orange-color-palette/

Red:
https://graf1x.com/shades-of-red-color-palette-hex-rgb-code/

Blue:
https://graf1x.com/shades-of-blue-color-palette/

Color codes:
https://htmlcolorcodes.com/

Thanks.

**Comment by lancelot-moon** [comment]
You should know the author of Kate Mobile is Russian.
https://play.google.com/store/apps/details?id=com.perm.kate_new_6
He has the sense for the color of themes.
soft color + black theme = dark mode

For your reference, the under green/blue is also great for AdGuard v3:
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/UsE0Xhz.png)

![image](https://i.imgur.com/SuGAq9k.png)

![image](https://i.imgur.com/gKLPgMs.png)

![image](https://i.imgur.com/xMdYWex.png)

![image](https://i.imgur.com/lowEJ6R.png)

![image](https://i.imgur.com/oDpJW4C.png)

![image](https://i.imgur.com/jzOq06r.png)

![image](https://i.imgur.com/jfydUvU.png)
</details><br/>

**Comment by Nzzyme** [comment]
When the dark theme is in effect, I am finding the colours shown in the filtering log page (especially the red/maroon - for blocked requests) quite difficult to recognise. I also apply the reading mode and usually dim the screen brightness, however the colours are somewhat not very eye catching and slightly light. Can you try to experiment with some more color options in the Filtering Log page?

**Comment by artemiv4nov** [comment]
#2760

**Comment by Rakleed** [comment]
Make a black theme (with background #000000). https://github.com/AdguardTeam/AdguardForAndroid/issues/2838

**Comment by Revertron** [comment]
No, “AMOLED Black” Does NOT Save More Battery Than Dark Gray
https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

**Comment by Rakleed** [comment]
@Revertron ok, I just like the black color on the AMOLED screen more than the gray color.

**Comment by artemiv4nov** [comment]
Well, recently, we integrated a dynamic theme support for Android 12 and above. Please try it in betas of v4.2.

**Comment by tengizmax** [comment]
> Well, recently, we integrated a dynamic theme support for Android 12 and above. Please try it in betas of v4.2.

@yuukiAme here's the similar issue discuss, so check this out and stay tuned.
