### ISSUE TITLE
The URL for FAQ and Discuss are reversed in AG v3.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2276]
The URL for FAQ and Discuss are reversed in v3.
Please fix them.

**Comment by karina-archazh** [comment]
@sviperz Please check in Support menu page.
For the moving menu on the main page all links are right.

**Comment by admitrevskiy** [comment]
Resolved

**Comment by sviperz** [comment]
@karina-archazh now I see it, you are right. Thanks for clarifying.

**Comment by lancelot-moon** [comment]
The bug was fixed in v3.0.66η.
