### ISSUE TITLE
When not running AG v3 in the foreground and then checking for updates via "long press app shortcuts", the toast notification has no green background.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2277]
1. **Don't ever** run AG v3 in the foreground when you try to reproduce the issue.

2. Regardless of enabling or disabling AG v3 via only "long press app shortcuts", if checking for updates via "long press app shortcuts", the toast notification has no green background.

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/rYBedj2.png)
</details><br/>

**Comment by Revertron** [comment]
Fixed in PR 817.

**Comment by lancelot-moon** [comment]
The bug isn't fixed in v3.0.66η.
