### ISSUE TITLE
Not possible to create an explicit rule that allows / blocks the "tcp://" and "udp://" traffic

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#2278]
Hello.

### Issue

The AdGuard Filtering Log shows the following "Request URL" for some connections:
**tcp://X.X.X.X:Y**
**udp://X.X.X.X:Y**

AdGuard Filtering Log shows such connections only for these apps:
- Google Play Store (app=com.android.vending)
- Google Play services (app=com.google.android.gms)
- Calendar (app=com.google.android.calendar)
- Downloads (app=com.android.providers.downloads.ui)
- WhatsApp

No matter which explicit rules I create, AdGuard never matches the above traffic to these rules.
As a result, it is not possible to block (or explicitly allow) such traffic.

### Steps to reproduce
I do not do anything to "reproduce" this behavior.
The apps mentioned above run on their own.
AdGuard Filtering Log shows the tcp:// and udp:// connections for those apps.

See the attached ZIP with files from AdGuard:
[Archive.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2568827/Archive.zip)
- Log with enabled "Record Everything"
- VPN Traffic capture

**In the attached AdGuard Log file, see these TCP entries on 10 Nov 2018:**
5)
AdGuard Filtering Log shows:
"Downloads" app - at 23:14:43.815 - Request URL `tcp://82.102.181.17:443`
Relevant reference in the AdGuard Debug Log:
`23:14:43.743 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=58] new TCP connection 172.18.11.218:49705 -> 82.102.181.17:443`
4)
AdGuard Filtering Log shows:
"Downloads" app - at 23:14:42.937 - Request URL `tcp://64.233.162.95:443`
Relevant reference in the AdGuard Debug Log:
`23:14:42.929 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=55] new TCP connection 172.18.11.218:49872 -> 64.233.162.95:443`
3)
AdGuard Filtering Log shows:
"WhatsApp" app - at 23:14:14.017 - Request URL `tcp://31.13.72.48:5222`
Relevant reference in the AdGuard Debug Log:
`23:14:14.011 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=45] new TCP connection 172.18.11.218:48012 -> 31.13.72.48:5222`
2)
AdGuard Filtering Log shows:
"WhatsApp" app - at 23:12:56.784 - Request URL `tcp://31.13.72.48:5222`
Relevant reference in the AdGuard Debug Log:
`23:12:56.672 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=15] new TCP connection 172.18.11.218:47930 -> 31.13.72.48:5222`
1)
AdGuard Filtering Log shows:
"Google Play services" app - at 23:12:56.151 - Request URL `tcp://173.194.222.188:5228`
Relevant reference in the AdGuard Debug Log:
`23:12:56.033 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=7] new TCP connection 172.18.11.218:41601 -> 173.194.222.188:5228`

**In the attached Log file, see these UDP entries on 10 Nov 2018:**
3)
AdGuard Filtering Log shows:
"WhatsApp" app - at 23:14:18.893 - Request URL `udp://85.21.78.8:123`
Relevant reference in the AdGuard Debug Log:
`23:14:18.887 [VpnService-main] DEBUG Native.TCPIP.UDPMNGR - [LWIP id=49] new UDP connection request 172.18.11.218:43270 -> 85.21.78.8:123`
2)
AdGuard Filtering Log shows:
"WhatsApp" app - at 23:14:19.217 - Request URL `udp://85.21.78.8:123`
Relevant reference in the AdGuard Debug Log:
`23:14:19.211 [VpnService-main] DEBUG Native.TCPIP.UDPMNGR - [LWIP id=50] new UDP connection request 172.18.11.218:45024 -> 85.21.78.8:123`
1)
AdGuard Filtering Log shows:
"WhatsApp" app - at 23:14:14.046 - Request URL `udp://216.239.35.8:123`
Relevant reference in the AdGuard Debug Log:
`23:14:14.043 [VpnService-main] DEBUG Native.TCPIP.UDPMNGR - [LWIP id=46] new UDP connection request 172.18.11.218:45154 -> 216.239.35.8:123`

### Expected behavior
The explicit rule should be matched

### Actual behavior
No matter which explicit rules I create, AdGuard never matches the above traffic to these rules.
None of these rules work (matched):
@@1.2.3.4:5$network$app=XXX
@@*$network$app=XXX
@@1.2.3.4:5$network,app=XXX
@@*$network,app=XXX
@@*$app=XXX
@@$app=XXX

### Customer ID
1146569

### Your environment
* Adguard version: This issue was seen in all Nightly versions 2.xxx and in the latest Nightly versions 3.xxx
* Adguard filtering mode: VPN
* Device model: Google Pixel 2 XL
* Operating system and version: Stock Android 9, Security patch from 05Nov2018, Kernel 4.4.116-g62fd7c7873da (07 Sep 2018), Build PQ1A.181105.017.A1
* Rooted or not: NOT rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NO

Thanks

**Comment by ameshkov** [comment]
@SergeiShir this might be a bug indeed. I'll check it myself in a week or two when I am back from the conference.

**Comment by ameshkov** [comment]
In the case of the "Downloads" app, the thing is that ad blocking is disabled for the app so no rules are applied at all. You can see this in the log:
`23:14:43.816 [tcpip-stack-pool-2-thread-11] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=58 Bypassing connection as ad blocking should not be used for this connection`.

* [ ] **This needs to be indicated in the filtering log.**
* [ ] **Another issue is that `@@` $network rules aren't shown in the filtering log at all.**
* [ ] `@@*$app=XXX` rules should be investigated further.

**Comment by SergeiShir** [comment]
I made sure to enable Ad Blocking for the apps I mentioned above:
* Google Services
* Google Play Store
* Downloads
* WhatsApp

Please see the attached logs and traffic captures from my replication on 21 Nov 2018 between 21:29 and 21:35.

There are explicit User Filter rules for the traffic below, but Filtering Log does not show a match for these rules.

1)
app=com.android.vending
Request URL: udp://172.217.18.14:443

2)
app=com.adguard.system
Request URL: tcp://121.121.121.121:53

3)
app=com.android.providers.downloads.ui
Request URL: https://r1---sn-4g5ednse.gvt1.com
Request URL: https://r4---sn-4g5e6ney.gvt1.com

Thank you

[AdGuard__replication__21Nov2018.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2605745/AdGuard__replication__21Nov2018.zip)

**Comment by SergeiShir** [comment]
Could you, please, provide some status update ?
Can I help you in any way by providing additional debugs ?
Thanks

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-Reinstall AG
1)-Go to User Filter
-Add rules: `93.184.216.34$network`and `@@93.184.216.34$network`
-Open `example.com` in browser
-Go to the filtering log
-There is whitelisted event with  `@@93.184.216.34$network` rule

2) -Enable DNS and disable DNS Filtering
-Surf the web
-Go to the Filtering Log
-Open any DNS request
-You will see warning about disabled ad blocking. There is no `Block` button
-Tap on warning will redirect you to the DNS screen
-Enable DNS Filtering
-Press back
-Now you can add filtering rules for DNS requests

3)-Go to the Apps Management
-Select any app (Chrome for example)
-Disable Ad blocking for it
-Surf the web via Chrome
-Go to the Filtering Log
-Select any request from Chrome
-You will see warning about disabled filtering. There is no `Block` button
-Tap on warning will redirect you to Chrome settings in the Apps Management 
-Enable Ad blocking
-Press Back button
-Now you can add filtering rules for Chrome
