### ISSUE TITLE
Bulk change does not save changes for HTTPS filtering

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2279]
Subj

### Steps to reproduce

1. Disable the HTTPS filtering for an app
2. Make sure it's disabled
3. Go to Bulck change > HTTPS filtering > For apps and browses > Apply

### Expected behavior

The changes are saved and reflected in the UI

### Actual behavior

Changes won't save. Works for all other settings except the HTTPS filtering

<details><summary>Screen recording:</summary>

https://uploads.adguard.com/20181110_133828_11-11-13-07.mp4

</details>

### Customer ID 
1922467

### Your environment

* Adguard version: 2.12.247
* Adguard filtering mode: VPN
* Device model: Xiaomi Redmi Note 4 
* Operating system and version: 7.0
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zzebrum** [comment]
@Eugene-Savenko on android > 7  it's not a bug for apps that don't trust user's certificates.

**Comment by Eugene-Savenko** [comment]
That's weird as you can "enable" the HTTPS filtering for an app manually, but can't do the same with the bulk change thing. This inconsistency confuses users. Thanks for the info.
