### ISSUE TITLE
mAh values are missing from the battery stats screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2280]
We should find some place there to print the actual values.

**Comment by lancelot-moon** [comment]
Please do this https://github.com/AdguardTeam/AdguardForAndroid/issues/2222 together.
Thanks.

Help users to check if AG get correct battery design capacity.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/ec864b25-01a8-4d58-90cb-d16e0f12487b

**Comment by nkartyshov** [comment]
done

**Comment by lancelot-moon** [comment]
@ameshkov

May you directly show the battery design capacity which AdGuard gets from firmware at least?

That helps users to know if the percentage of battery usage is right or not.
