### ISSUE TITLE
Random high CPU usage on v3.0 nightlies

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2282]
We've got two complains from the testers on a VERY high CPU usage on this version:
https://uploads.adguard.com/up04_8d4nt_2018-11-11_22.33.36.jpg

Waiting for logs now.

**Comment by sfionov** [comment]
@Xophile What version do you use?

**Comment by Xophile** [comment]
Hi!

Updated yesterday and so far so good!
