### ISSUE TITLE
BabyBus' games on Nougat

### ISSUE THREAD

**Issue by CrescendoFang** [AdguardTeam/AdguardForAndroid#2287]
**Steps to reproduce** 

1. Any game from: https://play.google.com/store/apps/dev?id=4946022439885210717 

2. HTTPS filtering with certs installed as system certs.

3. Play game, at some point, it will display full screen ads.

**Expected behavior** 

1. Ads blocked (no ads at all except at the title menu - it's only a shortcut to other devs' games, normal).

2. On my Mi Pad 4 with MIUI 9.6 but Oreo 8.1 based, the ads all blocked.

**Actual behavior** 

1. The ads is getting thru.

2. Even tho I blocked all internet access to the said app, the ads still getting thru.

**Your environment** 

Adguard version: 2.12.247

Adguard filtering mode: Proxy (auto)

Device model: Xiaomi Mi 5S Plus

Operating system and version: MIUI 9.6 - Nougat 7.0

Rooted or not? YES - Magisk 17.1

Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NO

**Comment by zzebrum** [comment]
@CrescendoFang Please use the template to report a problem.
I need to know AG version, what filters enabled, filtering mode, etc. It would be better if you attach logs. Thank you!

**Comment by CrescendoFang** [comment]
Logs: https://mega.nz/#!fpp2QCjT!axwHQnWrMkqMf4vO8qvxb_AfzKNyIsFmWzlbyMYeN2w

**Comment by CrescendoFang** [comment]
Seems enabling adblock for Google Play Services getting rid of any BabyBus' games ads...

Strange... do I need to close this issue or you wanna check it?

The ads originated from Google.

Filter logs said it was blocked but the ads is displayed.

**Comment by zzebrum** [comment]
I'm glad it's working now.
Does both Mi 5S Plus and Mi Pad 4 have the same version of android?
