### ISSUE TITLE
‘overwrite existing rules’ option doesn't work in import (User filter section)

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2288]
### Steps to reproduce

1. Go to Content Blocking -> User filter -> Import
2. Import enter thу URL and 'Overwrite existing rules' is On - https://filters.adtidy.org/extension/chromium/filters/11.txt. Expected result: 3120 user rules imported successfully.
3. Repeat import - step 2

### Expected behavior 
 The user rules should overwrite and count 3120.

### Actual behavior
 The user rules doesn't overwrite and count 6240.

https://uploads.adguard.com/Screenshot_20181112-134820.png

**Comment by nkartyshov** [comment]
Fixed

**Comment by aspasskaya** [comment]
The user rules should overwrite and count 3120 - it's Ok. The message “3120 user rules imported successfully and Protection was restarted to apply new settings” doesn't display on Android 5, and Adguard has stopped while copying the rule.

Android 5 - https://uploads.adguard.com/image_5.png
Android 8 - https://uploads.adguard.com/image.png
