### ISSUE TITLE
Validation error contains invalid text

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2289]
1. Go to Settings - Stealth Mode 
2. Go to Tracking parameters
3. Open any TTL dialog window 
4. Add 0 and tap OK button

### Expected behavior
Enter a number of minutes

### Actual behavior
Enter a number of **seconds**

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/48347103-53c58c00-e68e-11e8-9533-533bdf4129f3.png)

</details>

### Your environment

For all testing devices.

**Comment by admitrevskiy** [comment]
Resolved.
