### ISSUE TITLE
External app crashes when English filter is enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#229]
http://pad.showname.jp/pad.apk - this app crashes at startup if English or ABP Japanese filter is enabled.

Also mentioned at /ExperimentalFilter repository: https://github.com/AdguardTeam/ExperimentalFilter/issues/1083

Logs: GPD-900-92239

**Comment by ameshkov** [comment]
@vbagirov what if ad filtering is disabled for this app?

**Comment by ameshkov** [comment]
@vbagirov ?

**Comment by vbagirov** [comment]
Asked user to provide such information.

**Comment by freezewind** [comment]
It is no problem if I disable its ad filtering in Firewall.

**Comment by ameshkov** [comment]
@Alex-302 please take a look. Can we fix this by adding some exceptions to mobile filter?
