### ISSUE TITLE
AG crashes when turning off protection manually

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2290]
2 different patterns:

- turn on protection and turn it off --> crash

- turn on protection, open any webpage in a browser, open AG and turn off protection --> crash

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/CoreLibs #610](https://github.com/AdguardTeam/CoreLibs/issues/610) via [**ZenHub**](https://www.zenhub.com/)
