### ISSUE TITLE
Links inside Adguard app doesnt targeting by system language

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2291]
1. Check that system language: English
2. Check that app language: English
3. Open any support link like FAQ or Discuss

### Expected behavior
All links must be redirected to the page in accordance with the system language.

### Actual behavior
The page is displayed in Russian.

### Your environment
 For all testing devices

**Comment by sviperz** [comment]
Well, for me it opens English pages every time, even if I change the language on the page and reopen it again. I'm using English locale all the time in the OS.

**Environment**
Android 9 Pie
Google Pixel 3
AdGuard v3.0.56

**Comment by ameshkov** [comment]
Guys, the website detects language on its own and it can easily can be that you have different system language and AdGuard language
