### ISSUE TITLE
Export toast doesn't indicate folder

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2292]
### Steps to reproduce

1. Go to Settings -> Advanced 
2. Choose Export logs
3. Save logs into Downloads folder
4. Check notification after saving the logs

### Expected behavior
 

59/5000
The notification must contain a folder or path.

### Actual behavior
 Instead of folder or path name there just two spaces.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/48403250-90e95700-e73e-11e8-9f05-d2c74eabe63e.png)

</details>

### Your environment
For all teting devices

**Comment by sviperz** [comment]
BTW, I don't get any notification at all when exporting logs.

**Comment by karina-archazh** [comment]
@sviperz Sergey, could you please specify your environment?

**Comment by sviperz** [comment]
@karina-archazh yes, sure:

Android 9 Pie
Google Pixel 3
AdGuard v3.0.56

**Comment by nkartyshov** [comment]
Fixed

Test instruction:
1. install AdGuard
2. Import setting or Export logs and system info

Expected:
The file name should have on toast or alert dialog
