### ISSUE TITLE
No more "debug logging is enabled" notification on v3.0

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2296]
#1688 - it was added in 2.12

**Comment by Revertron** [comment]
But it works for me... May be you have disabled "Other" notification channel?

**Comment by sviperz** [comment]
Seems like this issue has been created according to my report in Telegram channel. Can confirm that there is no any notification when debug logging is enabled and I indeed have "Other" notification channel enabled either.

Please see my environment below.

### Environment
* Adguard version: v3.0.66
* Adguard filtering mode: VPN
* Device model: Google Pixel 3
* OS: Android 9
* No root

**Comment by sviperz** [comment]
The debug logging notification is finally here for me on v3.0.100. Still, can confirm what is described in the cooment above https://github.com/AdguardTeam/AdguardForAndroid/issues/2296#issuecomment-439861786

**Comment by Revertron** [comment]
@aspasskaya, @zebrum, I've added a mechanism to refresh that status on protection restart.

**Comment by karina-archazh** [comment]
@Revertron @nkartyshov Adguard stopped restarting protection after these changes (when you choosing any logging level options)

**Comment by nkartyshov** [comment]
@karina-archazh Protection didn't restarting after changed logging level.
