### ISSUE TITLE
Manual download option for the update screen

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#2299]
Some people have problems with the download manager provided by Android so it would be neat if the "New update available" screen would have a "3 dot menu" in the upper right corner that contains a entry called "Manual download" and opens the url of the download in a browser instead of the download manager.

**Comment by TPS** [comment]
This, please!  I nowadays can almost never successfully complete an update for AG ηightly via built-in download via Android DL manager, but must always download https://static.adguard.com/android/nightly/adguard.apk via [MS Edge](https://play.google.com/store/apps/details?id=com.microsoft.emmx).

**Comment by Revertron** [comment]
Maybe, we just need to download update file by our own code.

**Comment by TPS** [comment]
Sure, that's what I suggested in https://github.com/AdguardTeam/AdguardForAndroid/issues/1295#issuecomment-462006956, but that's much more work, so #2299 (_this_ issue 😁) is the quicker workaround.

**Comment by ameshkov** [comment]
@Revertron @AlikhanAliev 

1. Add "download" button to the context menu
2. Handle download errors and offer to download manually as an alternative

**Comment by AlikhanAliev** [comment]
> @Revertron @AlikhanAliev
> 
> 1. Add "download" button to the context menu
> 2. Handle download errors and offer to download manually as an alternative

We can add this button to the context menu, but I do not understand the problem. Guys said me that if we have download error then we have a dialog with "download manually" button too. It is right flow, isn't it?

@ameshkov

**Comment by TPS** [comment]
As of right now, I don't think AG ever even _notices_ download error for this, so I guess that might be 1st part of pt 2.

**Comment by Revertron** [comment]
@TPS don't you see some toast that an error occurred?

**Comment by TPS** [comment]
No, it just stops downloading or randomly pauses, like anything else in #597.

**Comment by Revertron** [comment]
Added a button to actionbar, you will see it in current nightly 3.0.303 when an update will be available :)

**Comment by Bluscream** [comment]
Nice, thank you
