### ISSUE TITLE
AdGuard crashes after clicking on create new user filter button

### ISSUE THREAD

**Issue by jkennethcarino** [AdguardTeam/AdguardForAndroid#2300]
### Steps to reproduce

1. Go to Settings -> Content Blocking
2. Go to User filter
3. Click on + floating action button

### Expected behavior

Should be able to create new user filter

### Actual behavior

AdGuard crashes

### Your environment

- Adguard version: v3.0.66 nightly (1.2.116cl)
- Adguard filtering mode: VPN
- Device model: Nokia 6
- Operating system and version: Android 8.1
- Rooted or not? Not rooted.
- Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? SD Maid

**Comment by karina-archazh** [comment]
Same logic in Whitelist option.
