### ISSUE TITLE
Outbound proxy add dialog is hiding (losing entered data) when switching between apps

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2301]
### Steps to reproduce
1. Go to outbound settings
2. Tap add proxy
3. Fill the fields, try to remember the port
4. Switch to another application to see what the port is
5. Return to AdGuard - dialog is gone :(

### Expected behavior
Dialog is not gone, I enter the port and add proxy

### Actual behavior
Dialog is gone.
I fill the fields again and forget the port again. Ahrrrrrr!

### Your environment
* Adguard version: 3.0.66n
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: Samsung G960F
* Operating system and version Android 8.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Reinstall AG
-Try to reproduce the issue

Expected result:
-"Add new proxy" dialog is still visible, entered data is not lost
