### ISSUE TITLE
It is not obvious when battery statistics is updated

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2303]
I didn't noticed any change in about an hour, activity looks static and filled once (even if it is not).

**Comment by nkartyshov** [comment]
Fixed

Testing instructions:
1. Start protection
2. Open Battery usage screen
3. Minimize the AdGuard
4. Surf on the internet
5. Open after the few minutes

Expected:
The information about the battery usage will be updated
