### ISSUE TITLE
Apps indicators in App Management doesn't change color from green to gray after applying new settings

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2304]
### Steps to reproduce

1. Go ta App Managment 
2. Choose a bulk change 
3. in bulk change disable wifi data for all apps and browsers 

### Expected behavior
Wifi indicator opposite App Name should be gray

### Actual behavior

Wifi indicator opposite App Name stayed grуут

Also, this logic is repeated to disable a single app.

### Your environment
For all testing devices
v. 3.0.66

**Comment by admitrevskiy** [comment]
Resolved.

**Comment by TPS** [comment]
I'd just be happy to be able to _open_ App Management w/o AG crash/restarting.…
