### ISSUE TITLE
testing nightly build 3.0.0.72, here's my results

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2307]
so I installed adguard again, version 3 and I liked it,
it justs needs a bit of work to become perfect,
well I'd like to report 3 things
(all the tests were done using latest chrome, version 70):
1) even though I enabled all relevant anti-adblocking filters,
they didn't work in apkmirror.com,
adblocker was still detected and I had to wait 10 seconds or so to continue
2) when using "open pages internally" in viber,
I got no internet connection when clicking on this link:
https://www.news247.gr/psixagogia/tileorasi/oristiko-to-logo-timis-epistrefei-se-poio-kanali-tha-to-doyme.6666405.html,
which has a cookie notice on it and I clicked it many times to see if it would be removed,
because I enabled all cookie notice disabling filters too,
no matter what I tried, "blocking ads in apps" enabled/disabled,
I still got no internet connection,
other links worked fine,
I even went in the filtering log and enabled everything that was blocked
when clicking this page, same result
3) I noticed my certificate expires in 4 years, why is that?
I've got a lifetime subscription, will I get a new one then?

* Adguard version: nightly build 3.0.0.72
* Adguard filtering mode: VPN with https (certificate installed) and adguard encrypted dns server enabled
* Device model: xiaomi redmi note 5a
* Operating system and version Android 7.1 (nougat/lineage)
* Rooted or not?  rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? dns66 and adaway, 
but both totally disabled when testing the above

I've got a nokia 6 device too, nougat as well, but unrooted,
I'll test there too

**Comment by zzebrum** [comment]
1. about missed ads you should use AG side menu - Support - Send Feedback - missed ads
2. need to recheck on our side
3. do you mean Security cert in https filtering section?

**Comment by patrickdrd** [comment]
ok about 1, I fixed it by sorting out my filters
about 2 I think you should check adblocking in general in internal browsers in apps,
if that's possible, I mean, ads are blocked in internal viber browser,
but neither white page was removed, nor the cookie notices, etc

3. yes

also,
how can I track nightly builds? is there any url to track when a new one is out and changelog?

and, is there any (other) way to add a hosts file 
(with entries such as "0.0.0.0 example.com"
besides replacing with "||example.com^"?)

**Comment by zzebrum** [comment]
2. the page doesn't open in viber even if AG is off on our side

3. https certificate != lifetime subscription. I think your cert was generated in previous version of AG when certs had random expiration dates. You can delete it and generate a new cert for 20 more years :) all manipulations with your license you can do in your personal account, [read more](https://kb.adguard.com/en/general/license-key#account).

**Comment by patrickdrd** [comment]
ok, I deleted it and I recreated (I moved it to the system too), 
but I still got the same,
I mean expiration date at 2022, 
I had bought adguard last year too, but I refunded it and
I decided to give another try at it

also, the filtering is not as effective when using viber's (or any other app's) internal browser,
because, as I reported neither the white space is cleared, nor the cookie notice 
(you can use the same url for testing purposes, it has both),
the results were the same even after moving the certificate to system

**Comment by patrickdrd** [comment]
ok I did it from inside adguard and it worked,
another question please:
does the filtering log clean automatically?
or do I have to clean it from time to time?

**Comment by patrickdrd** [comment]
and another question:
what's the custom filter (not the user filter, the one on the bottom) used for?

**Comment by lancelot-moon** [comment]
Import filters for HTTPS filtering by URL.
You know the subscriptions of AG Pro for iOS................

**Comment by patrickdrd** [comment]
I tried to use a hosts file in there but it never worked,
I wish it was

**Comment by lancelot-moon** [comment]
I mean filters for HTTPS filtering, **NOT hosts files for DNS filtering.**
Importing hosts files for DNS filtering is not ready yet.

**Comment by patrickdrd** [comment]
yes, but I cannot import hosts file, that's my problem, I guess I have to wait for new corelibs, as @lancelot-moon suggested

I found out what's happening with viber's internal browser too, https filtering isn't possible, that's why I'm  getting white spaces and cookie notices

**Comment by zzebrum** [comment]
@patrickdrd AG doesn't support hosts files.
