### ISSUE TITLE
Crash in the Apps Management settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2308]
Details:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13243/

**Comment by infinitewaveparticle** [comment]
This has been an issue for me for the entire time I've had AdGuard. For me to successfully be able to open the App Management tab I have to first disconnect from the internet AND disable AdGuard. This is very annoying.

**Comment by ameshkov** [comment]
@infinitewaveparticle this must be something else as this crash is a new thing introduced (and already fixed) in the nightly builds.

Could you please enable crash reporting in AdGuard service, reproduce the crash and comment on this issue immediately after that (so that I could figure that the crash report is from you?)

**Comment by TPS** [comment]
I just sent mine, as it's still doing this.  I thought y'all hadn't gotten to this yet.  🤷‍♂️

**Comment by Yevhen1996** [comment]
@Revertron we received a message from a customer who claims that the issue persists even with latest update 3.0.180
User's ID – 2293655

**Comment by ameshkov** [comment]
@Yevhen1996 please ask him to enable crash reporting in the settings, we will check & fix the most often crashes anyways.

**Comment by infinitewaveparticle** [comment]
@ameshkov My apologies for not responding sooner. I just now enabled crash reporting and reproduced the crash. I must note, however, that just before I updated to yesterday's release I hadn't noticed it happening. I don't often use the Apps Management because I rarely need to enable or disable an app from my current settings. I also have only noticed the crash when using WiFi; I don't ever recall it crashing while using cellular data. It always works while not connected, though, and especially after also disabling AdGuard.

**Comment by infinitewaveparticle** [comment]
Please note that the crash happened approximately 5-10 minutes prior to submitting the comment above.

**Comment by ameshkov** [comment]
@infinitewaveparticle got it, thank you!

**Comment by ameshkov** [comment]
@infinitewaveparticle could you please do just one more thing?

Next time the issue happens:
1. Go to settings -> advanced -> export logs and system info
2. Send the file to `devteam@adguard.com` (and mention this issue in the email)

**Comment by infinitewaveparticle** [comment]
@ameshkov I experimented a bit more... turns out that it crashes now no matter which data connection I'm using (Wi-Fi or cellular). It also happens when I'm disconnected from the internet. I now have to disable AdGuard to even be able to open Apps Management. This wasn't happening prior to the most recent release, but it did happen prior to the release before it. So whatever was changed from the version prior to the latest is headed in the wrong direction.

**Comment by infinitewaveparticle** [comment]
By the way, my device is a Samsung Galaxy S7 Edge running stock Android 8.

**Comment by ameshkov** [comment]
@infinitewaveparticle the logs will help a lot, it's not a common issue.

**Comment by zzebrum** [comment]
@infinitewaveparticle hello! any new about reproducing the problem?

**Comment by infinitewaveparticle** [comment]
@ameshkov @zzebrum Seemingly out of the blue I can no longer reproduce the crash. I didn't change anything. Smh...

**Comment by infinitewaveparticle** [comment]
Which is a good thing... I'll let you know if anything changes.

**Comment by TheHasagi** [comment]
#### Another case : 1969826

**Comment by safaksama2018** [comment]
İ just sent latest extended logs to  devteam@adguard.com mine doesn't matter with Wi-Fi on or off cellular on or off this is Samsung android 8 mobile all detail inside the logs. if reproduce crash need could that because it's every time crash when ever try to open app management screen only %1-2 time succeed with out crash to open those settings. I think maybe it could be because I got allot off apps so could you please extend buffer some maybe it could fix that way.

**Comment by safaksama2018** [comment]
Notice i use dual sim card plus wi-fi any news about fix?

**Comment by Revertron** [comment]
You have this kind of crash, apparently:
```
ERROR com.adguard.android.b.h - Thread: Thread[cached-pool-1-thread-433,5,main]; Uncaught exception:

android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1018) ~[na:0.0]
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836) ~[na:0.0]
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62) ~[na:0.0]
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152) ~[na:0.0]
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141) ~[na:0.0]
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219) ~[na:0.0]
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268) ~[na:0.0]
	at com.adguard.android.db.b.a(AppRulesDaoImpl.java:58) ~[na:0.0]
	at com.adguard.android.service.g.a(AppRulesServiceImpl.java:206) ~[na:0.0]
	at com.adguard.android.service.g.a(AppRulesServiceImpl.java:152) ~[na:0.0]
	at com.adguard.android.service.g.a(AppRulesServiceImpl.java:132) ~[na:0.0]
	at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:2440) ~[na:0.0]
	at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:83) ~[na:0.0]
	at com.adguard.android.ui.AppsManagementMainActivity$4.run(AppsManagementMainActivity.java:635) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by Revertron** [comment]
@safaksama2018 Please, try this build with the fix:
https://uploads.adguard.com/adguard-v3.0.266n-issue2308.apk
You can install it over whatever version you have on your device now.

**Comment by safaksama2018** [comment]
Nope my result is some its still crash when ever try to open app management
screen here is the new logs hope it's help

5 Mar 2019 Sal 17:31 tarihinde Roman <notifications@github.com> şunu yazdı:

**Comment by ameshkov** [comment]
@safaksama2018 could you please send the logs again to `devteam`? We'll check what's the difference

**Comment by safaksama2018** [comment]
Yes but what is the dev team adress do you mean sent this to git hub ?

6 Mar 2019 Çar 20:02 tarihinde Andrey Meshkov <notifications@github.com>
şunu yazdı:

**Comment by ameshkov** [comment]
I mean to `devteam@adguard.com`

**Comment by safaksama2018** [comment]
Here is the latest nightly build logs. It will delete in 7 day I sent there because I can't attach log files directly here.

https://we.tl/t-OYiP0xen7Y

**Comment by safaksama2018** [comment]
Ok allright sorry on the way.

6 Mar 2019 Çar 20:17 tarihinde Andrey Meshkov <notifications@github.com>
şunu yazdı:

**Comment by ameshkov** [comment]
@safaksama2018 hm, I checked the logs, but I don't see any crash info there. Is it still happening on the latest nightly?

**Comment by safaksama2018** [comment]
Yes its still crash and always crash on app management screen

9 Mar 2019 Cmt 18:21 tarihinde Andrey Meshkov <notifications@github.com>
şunu yazdı:

**Comment by ameshkov** [comment]
That's weird, I see no new crash reports. Do you have them enabled?

One more thing -- maybe it crashes differently now, and that's why I cannot see anything.

Could you please export logcat for us? Here's how to do it:
https://kb.adguard.com/en/android/solving-problems/logcat

**Comment by safaksama2018** [comment]
Here is the latest logs hope this time crash existed and insided; here by
luckly i could also added logcat too.

10 Mar 2019 Pzr 18:31 tarihinde Andrey Meshkov <notifications@github.com>
şunu yazdı:

**Comment by ameshkov** [comment]
Got it, thank you.

Stack trace:
```
03-12 14:13:30.461 17719 17778 E AndroidRuntime: FATAL EXCEPTION: cached-pool-1-thread-4
03-12 14:13:30.461 17719 17778 E AndroidRuntime: Process: com.adguard.android, PID: 17719
03-12 14:13:30.461 17719 17778 E AndroidRuntime: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.CursorWindow.<init>(CursorWindow.java:108)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:309)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:141)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.db.b.a(AppRulesDaoImpl.java:58)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.service.g.a(AppRulesServiceImpl.java:206)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.service.g.a(AppRulesServiceImpl.java:152)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.service.g.a(AppRulesServiceImpl.java:132)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:2440)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.ui.AppsManagementMainActivity.a(AppsManagementMainActivity.java:83)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at com.adguard.android.ui.AppsManagementMainActivity$4.run(AppsManagementMainActivity.java:635)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-12 14:13:30.461 17719 17778 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by ameshkov** [comment]
@safaksama2018 as I see this is not the latest build, and maybe the fix was not included there. Could you please update AG to the latest nightly ver?

**Comment by safaksama2018** [comment]
Latest nightly still have that bad bug its not fixed yet but i read, on the development logs its show rollback hope it could fix as soon i still waiting for that it's impossible to configure each apps at the moment
