### ISSUE TITLE
Yandex navigator camera problem

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2311]
@Y2Kot commented on [Sat Nov 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150)

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

Последние 2 обновления ломают яндекс навигатор, скрывая камеры с интерфейса навигатора.
Лог программы - https://yadi.sk/d/HGGAWoharZTjbg

---

@bogachenko commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437760288)

скрин будет?

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437791721)

скрин навигатора?

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437793148)

<details>

![zzhbnvd0ucm](https://user-images.githubusercontent.com/4283562/48334682-8c546e00-e66c-11e8-837e-d64907a10e57.jpg)
![q5npu3o3b-4](https://user-images.githubusercontent.com/4283562/48334690-91192200-e66c-11e8-9ac7-eb32e53756ac.jpg)
</details>
С включернным из выключенным AdGuard

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437793302)

При этом голосом навиагатор предупреждает

---

@bogachenko commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437795744)

@Y2Kot че по подпискам, какие листы с фильтрами у тебя активны?

Призываю в тред @Alex-302, посмотришь?

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437845837)

да фильтры вроде стандартные все:

<details>

![80u_dibmqea](https://user-images.githubusercontent.com/4283562/48344628-abf89000-e686-11e8-8e91-8e7c14e1506a.jpg)
![4x-ufhwmhjg](https://user-images.githubusercontent.com/4283562/48344629-abf89000-e686-11e8-8724-ff607e24107c.jpg)
![gse9ndgrdts](https://user-images.githubusercontent.com/4283562/48344631-abf89000-e686-11e8-83b8-7a8ccf7f5fb4.jpg)
</details>
Сейчас поставил 3.0 версию в надежде, что в ней этого бага нет, но не помогло, что на 2й, что на 3й - камер нет

---

@Alex-302 commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437857111)

@Y2Kot Скрины фильтров не нужны. Лучше из приложения создавать отчёт, в котором будет вся необходимая информация.

У меня камеры отображаются верно. Отключение фильтров, не выключая Адгард, помогает?

<details>

![image](https://user-images.githubusercontent.com/8361299/48346730-b7e35280-e684-11e8-9e3d-dcc1e020fc90.png)

</details>

@zebrum проверь у себя ещё.

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437857382)

@Alex-302 я попытался сделать в приложении (ссылка в первом сообщении) но он создает архивы 0байт

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437857830)

отключил все фильтры, камер так и нет

---

@Alex-302 commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437867814)

Попробуйте в настройках приложений отключить фильтрацию этого приложения. Если не поможет - отключите для него фильтрацию HTTPS.
Фильтры можно включить, т.к. не влияют.

---

@karina-archazh commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437869577)

@Y2Kot а уточните, пожалуйста, вашу версию Навигатора?

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437870338)

@karina-archazh 3.47 от 07.11.2018, сборка 305.
@Alex-302 https был отключен. После отключения "пропускать трафик приложения через Adguard" камеры появились

---

@zzebrum commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437870828)

@Y2Kot а DNS включен в настройках AdGuard?

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437871026)

@zebrum нет

---

@karina-archazh commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-437898266)

@Y2Kot А когда последний раз у вас обновлялись карты в приложении?

---

@Y2Kot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-438010149)

@karina-archazh 10 октября. Сейчас обновлений нет.

---

@karina-archazh commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-438244116)

@Y2Kot Можно вас попоросить с выключенным адгардом переустановить карту в Яндекс Навигаторе и проверить?

---

@Y2Kot commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-438306363)

@karina-archazh сделал, после включения фильтрации навигатора камеры пропали

---

@Alex-302 commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-438311396)

@karina-archazh посмотри, к каким доменам обращаетсяпосле очистки данных. Возможно в исключения HTTPS что-то нужно добавить.

---

@Y2Kot commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25150#issuecomment-438350497)

@Alex-302 так а какая разница, если для навигатора https отключён? После очистки включил только пропускание трафика через Adguard + блокировку рекламы, фильтрация https отключена.

**Comment by karina-archazh** [comment]
The issue repeats with the filters turned off.
Logs attached.

> 
[adguard_logs_3.0.72_1411_1702.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2581600/adguard_logs_3.0.72_1411_1702.zip)

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/CoreLibs #616](https://github.com/AdguardTeam/CoreLibs/issues/616) via [**ZenHub**](https://www.zenhub.com/)
