### ISSUE TITLE
License page: Incorrect return logic

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2313]
For reproducing this issue firstly reset your license.

### Steps to reproduce

1. Go to any page (for this test we using the app management page)
2. Open the sidebar and choose License Status
3. Tap on key button 
4. Paste your license key

### Expected behavior
You should stay on License status page with the notification and status of your license
### Actual behavior

Actually, you get a notification about the activation of your license and returning on the app management page.

### Your environment

* Adguard version: 3.0.72
For all testing devices

**Comment by admitrevskiy** [comment]
Done
