### ISSUE TITLE
Send Feedback page: incorrect return logic 

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2314]
### Steps to reproduce

1. Choose to Send Feedback page (from slide bar or Support page)
2. Tap on Bug report into Feedback Type dialog window
3. Tap on Arrow button

### Expected behavior
You should be returned into page with Feedback Type dialog window
### Actual behavior
You returning to Support page or page where you firstly choosing Send Feedback page from slide bar.

Also, this logic works if you choose the options for feedback using the reporting site (Missed ad and Incorrect blocking).

### Your environment

* Adguard version: 3.0.72
For all testing devices

**Comment by zzebrum** [comment]
We've decided there is no need for this logic when #2306 will be done
