### ISSUE TITLE
Please give the field of "Filter name" with 2 options of "Automatically detect" and "Manually input" when importing a custom filter.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2315]
@ameshkov 
1. Not every filter has the below standard format for a filter's title.
Supported: `! Title: Hexxium Creations Threat List`
Unsupported: # Ransomware Domain Blocklist (RW_DOMBL)                                 #
or others or even no title in a list...

ex: After importing the below list, there is no filter's title and description.
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/aU6sNpM.png)
</details><br/>

Please give the field of "Filter name" with 2 options of "Automatically detect" and "Manually input" when importing a custom filter.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/B0KfVYv.png)
</details><br/>

**I also wish this for AG for Windows/macOS.**

2. Please add the field of "Description".

Thanks.

**Comment by karina-archazh** [comment]
Related to https://github.com/AdguardTeam/AdguardForWindows/issues/2118#issuecomment-439077527

**Comment by lancelot-moon** [comment]
This was done.
Now AG for Android can automatically detect a regular filter's name, or let users manually input filter's name while it's not a regular filter's name in the list.
