### ISSUE TITLE
Improve the layout of specific languages filters

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2316]
The list of 62 specific languages filters is too long in the same screen.
Giving a long list and then letting users feel tired to scroll down isn't smart layout.
Please delete the strings, "recommended" and "others", from specific languages filters.
Separate those filters into different tabs (zones) for shortening the list.
Users can swipe between different tabs.

Ex:
Tabs according to languages (Chinese, Russian,...etc.), continents (Asia, Europe...etc.) and so on.

**Comment by lancelot-moon** [comment]
This request was also for https://github.com/AdguardTeam/AdguardForiOS/issues/819#issuecomment-431260780

**Comment by TPS** [comment]
@lancelot-moon "Recommended" is important IIUC, b/c those lists are meant to be fully supported.  I think rest are listed for convenience or popularity, but whenever problems, 1 must contact list maintainer directly.  I agree completely w/ everything else you listed.
