### ISSUE TITLE
Update CoreLibs to 1.2.12x

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2317]
API is changed slightly.

* [Feature] Add the $csp modifier support: AdguardTeam/CoreLibs#15
* [Fix] Do not apply stealth mode to non-browser apps requests: AdguardTeam/CoreLibs#607
* [Fix] Don't crash when CoreLibs init is called when CoreLibs is already initialized: AdguardTeam/CoreLibs#608

API changes: 
RequestProcessedEvent now has cspRules field which is similar to replaceRules field - is a list of applied rules.

**Comment by Revertron** [comment]
Done.
