### ISSUE TITLE
Can't add DNS block list

### ISSUE THREAD

**Issue by LewisLebentz** [AdguardTeam/AdguardForAndroid#2318]
I tried to add this block list:

https://raw.githubusercontent.com/EnergizedProtection/block/master/bluGo/formats/filter

To block more domains via DNS, however once added to the app, it treats the list like a normal adblock list (blocking HTTP GET). Is there something special I can do to make Android treat it as a DNS block list? The existing DNS filter you provide is formatted in the same way:

https://filters.adtidy.org/extension/chromium/filters/15.txt

They provide block lists in other formats here: https://github.com/AdroitAdorKhan/Energized none seem to work. I'd expect the plain domains list to work for DNS, but no joy.

The only thing that does seem to block DNS requests is if you click a DNS request from the log file, then choose to block it from there.

**Comment by lancelot-moon** [comment]
The feature of importing filters / hosts files for DNS filtering is not ready yet before new CoreLibs with DNS module is released.

That list which you imported would only work for HTTPS filtering, not for DNS filtering.

**Comment by lancelot-moon** [comment]
@karina-archazh 
This is only a question, not a feature request.

If you mean a feature request, here it is.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1851

The article is duplication.

**Comment by zzebrum** [comment]
@LewisLebentz 

like @lancelot-moon said if you add something in user filter it will work like a regular filter, not on DNS level. 
closed as dub of #1851
