### ISSUE TITLE
Return "Rate App" button to "About" view in Amazon build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#232]

**Comment by TPS** [comment]
Strange limit re: Amazon Appstore rating:  It will sometimes block a rating/review via Appstore _app_ if user has not purchased any _explictly paid_ apps (does _not_ include subscriptions or any other IAP).  The Appstore _website_ does _not_ have this limit, so perhaps (also) link to web Appstore AG review section?

**Comment by ameshkov** [comment]
As I know the website has the same limit, you should pay for the app (in case of a free app - install the app)

**Comment by TPS** [comment]
No, this is something different.  The Amazon Appstore app will (sometimes) attempt to block 1's review, _even though 1 has "purchased" (@ $0, if free app) & installed ***that*** app through Amazon Appstore,_ if that account has never directly purchased _any_ app for >$0!  If same review is attempted through website, though, no problem.

I've never understood Amazon about this! :confused:

**Comment by Revertron** [comment]
Done.
