### ISSUE TITLE
Specify filter name for all filtering rules in filtering log

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2320]
### Steps to reproduce

1. Open a web page in chrome browser
2. Go to filtering log
3. tap on blocked request

### Expected behavior
https://uploads.adguard.com/Screenshot_2018-11-16-18-41-20_2018-11-16_19-13-31.png

### Actual behavior
https://uploads.adguard.com/Screenshot_20181116-175140_2018-11-16_19-13-20.png

**Comment by admitrevskiy** [comment]
We should also add the ability to work with rules separately if there are more than one rule in single event

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Reinstall AG

1)
-Open `dni.ru`(for example)  in the browser
-Go to Filtering Log
-Filter out HTML Removed element requests
-Open details for event

`Expected result:`
`-Filter name should be specified for the filtering rule. Tap on Filter name will redirect you to the  relevant Filter category screen`

2)
-Go to the User Filter
-Add some replace blocking and whitelist rules for single domain (for ex. example.org)
-Open example.org
-Go to the Filtering Log
-Filter out Modified requests

`Expected result`
-There are many filtering rules for single event. Block/Unblock button is gone. To remove or copy filtering rule from the UserFilter tap on the filtering rule. Moreover now we support many $replace and $csp rules and filters for one event. Please, examine Filtering Log behaviour with your own filtering rules.
