### ISSUE TITLE
Missed domain name when adding exception rule

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2321]
### Steps to reproduce

1. enable filtering log
2. go to http://blog.i.ua/
3. find there <script type...> blocked rule: https://uploads.adguard.com/Screenshot_20181116-170043_2018-11-16_19-44-50.png

### Expected behavior
exception rule should have a domain name in it: blog.i.ua$@$script[wildcard="*!function(*mzs*zmctrack*"][max-length="9000"]

### Actual behavior

https://uploads.adguard.com/Screenshot_20181116-015034_2018-11-16_19-45-44.png

**Comment by admitrevskiy** [comment]
Resolved.
