### ISSUE TITLE
manual download & installation of filters

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#2322]
I would like to be able to download AdGuard's filters directly from the website in a browser. This would also necessitate a way to install the filters simply by placing the files into a directory - or by adding a filter installation part of the app that can be done online or offline. I would also like to be able to create my own filters or download other filters from elsewhere and also be able to install them. This would be very helpful as people could make custom firewall filters for different needs.

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? 
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by zzebrum** [comment]
@infinitewaveparticle in nightly versions you can import filters by URL and from local storage.

**Comment by TPS** [comment]
@infinitewaveparticle https://kb.adguard.com/en/general/adguard-ad-filters ?

**Comment by TPS** [comment]
@infinitewaveparticle Well, https://filterlists.com/ is the granddaddy metalist of *all* of these.…  Something _there_ to your liking?

**Comment by zzebrum** [comment]
@infinitewaveparticle 

AdGuard doesn't claim to be the one and only place on the Internet to have filters-related discussion. We have our platforms — notably, a dedicated section of the [forum](https://forum.adguard.com/index.php?categories/66/) and the [GitHub repository](https://github.com/AdguardTeam/AdguardFilters). Having that said, there are plenty of other forums, websites etc. where involved community members do the same. 

As for the other questions (presuming you talk about Android app), a lot of changes will come in the next version, including those you mention: an option to add multiple custom filters by URL or from a local file and them manage them like regular default filters. You can try nightly builds and check it out for yourself.
