### ISSUE TITLE
Https filtering for Firefox Focus

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#2323]
Forced https filtering works for Firefox Klar on my Android 5.1.1 tablet, but for Firefox Focus on my Android 8.1 phone it just gives the insecure connection error.

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? 
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by infinitewaveparticle** [comment]
Example of a website where https filtering helps on Firefox Klar - apkmirror - the adblock detector that makes you wait 15 seconds to download files is killed by successful https filtering.

**Comment by ameshkov** [comment]
The problem is that FF Focus/Klar does not respect user-added certificates unlike other browsers:
https://adguard.com/en/blog/android-nougat-release-and-what-does-it-mean-for-adguard-users/
