### ISSUE TITLE
Unable to pair with the Your phone app on Windows when AdGuard is running

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2324]
AdGuard is reportedly interfering with the new [Your phone](https://support.microsoft.com/en-ca/help/4459358/windows-10-your-phone-app-help) app on Windows. When AdGuard is disabled, the pairing is successful. Enabling the protection again disconnects the phone immediately.

### Steps to reproduce

1. Pair your phone with a Windows 10 PC with the Your phone app installed 
2. Disable AdGuard on Android and try again
3. Once paired, enable the protection;

### Expected behavior

The phone is successfully paired; the connection does not drop

### Actual behavior

Unable to pair and use the Your phone app unless AdGuard is disabled or the protection is on pause

### Your environment

* Adguard version: 2.12.247
* Adguard filtering mode: VPN
* Device model: n/a
* Operating system and version: 7 and higher
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zzebrum** [comment]
@Eugene-Savenko do you have the [app](https://play.google.com/store/apps/details?id=com.microsoft.appmanager) installed?

**Comment by UfoAkaJuggalo** [comment]
Hello,
I'm the guy who reported this issue.
I tried to disable HTTPS filtering in app on my phone, but it doesn't help.
My OS info:
![image](https://user-images.githubusercontent.com/25750395/48817393-8d5d5d80-ed46-11e8-8e9c-03e7649fee91.png)

My Phone:
Motorola G6 plus (XT1926-3) Android 8.0.0 Kernel 4.4.78 (3.9.2018) buid OPWS27.113-89-2
AdGuard 2.12.247
not rooted, (almost) factory setup (except launcher, icons etc.). I've VPN app, but it's turned off, so it shouldn't interfered

**Comment by aspasskaya** [comment]
We need to add com.microsoft.appmanager to disable protection

**Comment by UfoAkaJuggalo** [comment]
log from my phone (I started app around 3.20 and it's breaks my connection with PC)
[adguard_logs_2.12.247_2611_0321.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2613871/adguard_logs_2.12.247_2611_0321.zip)

**Comment by ysagiru266-sys** [comment]
Please I'm sorry how you can get my speaker 🔊
