### ISSUE TITLE
List of all adguard servers

### ISSUE THREAD

**Issue by blub4747** [AdguardTeam/AdguardForAndroid#2329]
Hello adguard team,
Is there somewhere a complete list of al your dns servers available ?
Like in a csv format_

Thx, blubblub4747

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? 
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by zzebrum** [comment]
@blub4747 hello! you can find both ipv4 and ipv6 addresses for default and family DNS servers [here](https://adguard.com/en/adguard-dns/overview.html).
