### ISSUE TITLE
German O2 (Telefonica) VoWifi/WLAN calling

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/AdguardForAndroid#2334]
when using ADGuard in proxy auto mode than VoWifi neither VoLTE isnt working whenever i toogle to airplane mode an back.
Then i have to switch Wifi to off and back to on. Than VoWifi is working again.
If VPN mode is used instead than there is no problem at all but the load times with VPN mode are very bad.
So i prefer to use root mode.

* Adguard version: 2.12.247
* Adguard filtering mode: Proxy auto
* Device model: Pocophone F1
* Operating system and version: MIUI 10.0.4.0
* Rooted or not? Rooted
* German provider o2 (Telefonica)

Adguard Forum Link -> https://forum.adguard.com/index.php?threads/problems-with-vowifi-wlan-call.29903/

Logfile: [adguard.log](https://github.com/AdguardTeam/AdguardForAndroid/files/2603167/adguard.log)

**Comment by zzebrum** [comment]
@derKief please collect debug log following the [instruction](https://kb.adguard.com/en/android/solving-problems/log), on step 5 instead of sending it to support via the AdGuard app, export the logs and send them to devteam[at]adguard[dot]com

**Comment by derKief** [comment]
i just sent the requested debug.log via email.

**Comment by derKief** [comment]
any update on this ?
Meanwhile i tried latest nightly but problem remains.
Its really annoying :-(

**Comment by zzebrum** [comment]
@derKief sorry for the delay. Unfortunately, I can't find your email. Please resend it to my email directly mg[at]adguard[dot]com

**Comment by derKief** [comment]
i just made a new debug log and sent it to your mail directly.
Did you receive it ?

**Comment by ameshkov** [comment]
Some intermediate server might be blocking this email due to attachment.

There's also another option: upload it somewhere (dropbox/gdrive/whatever) and re-send the email.

**Comment by derKief** [comment]
@zzebrum 
@ameshkov 
i just sent a new mail with an gdrive link to download the logs :-)

**Comment by sfionov** [comment]
@derKief Hello!
Can you please add the following line to `pref.ipv6.routes.excluded` low-level settings (Settings->Advanced settings->Low Level Settings)?:
```
2a02:3000::/23
```
And say if it will help or not.

**Comment by ameshkov** [comment]
And now that's really weird. Let's go with forum then :)

**Comment by ameshkov** [comment]
@sfionov so it's German O2 (Telefonica) wi-fi calling range? 

@derKief if @sfionov suggestion helps, we will add this route to exclusions in the next AG version.

**Comment by derKief** [comment]
can i add this route myself to exclusions ?
Is there a way to do this ?

**Comment by derKief** [comment]
@sfionov
@ameshkov
that was the solution ... thank you very much :-)

pref.ipv6.routes.excluded
2a02:3000::/23
now VoWifi is working perfectly

**Comment by ameshkov** [comment]
Awesome, thank you for helping us!

**Comment by derKief** [comment]
Thank you for helping me :-)

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Go to Settings -> Advanced -> Low level -> pref.ipv6.routes.excluded

Expected result:
`2a02:3000::/23` is in the exclusions list

**Comment by ameshkov** [comment]
Merged to https://github.com/AdguardTeam/AdguardForAndroid/issues/2550
