### ISSUE TITLE
New UI for landscape orientation

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2335]
We need to add landscape orientation support for tablets, android TV and other devices with big screens.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/5c015d87-e387-49b5-85ee-e6f6dab90dac

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Examine Main screen behaviour in landscape orientation for phones and tablets.

Please, let me know if any other screen is broken for specified device.

**Comment by zzebrum** [comment]
1. go to Settings - DNS Filtering - Custom DNS settings - Choose DNS server from the list 
2. you'll be redirected to kb webpage
3. choose any DNS, tap on Add to AdGuard
4. back to Edit DNS server window
5. rotate the device to landscape orientation

Actual behavior: The Edit DNS server window is closed, DNS settings are lost.

**Comment by aspasskaya** [comment]
Search in Apps management section:
![image](https://user-images.githubusercontent.com/43952607/51734755-545ea380-207d-11e9-8b98-7941092fce2a.png)

**Comment by karina-archazh** [comment]
When you click on each search line, white box pops up:


<details> 

![image](https://user-images.githubusercontent.com/41899455/51750562-7418ba80-20c3-11e9-9c4b-8b7bf4b75d5f.png)
 </details>

**Comment by aspasskaya** [comment]
v3.0.291 
### Search
1. write in search anything
2. rotate the device to landscape orientation
#### Actual behavior: The search field and result are disappeared.
- Apps management
- Filtering log
- HTTPS whitelist
- HTTPS blacklist
- Whitelist
- User filter
#### Actual behavior: The search field and result doesn't disappeared, but:
- Filters
![image](https://user-images.githubusercontent.com/43952607/54682430-f8197c80-4b1f-11e9-8c15-0fcfa599d2ec.png)
- Filters group
![image](https://user-images.githubusercontent.com/43952607/54682447-023b7b00-4b20-11e9-9a68-e63e3a138198.png)

**Comment by admitrevskiy** [comment]
Done.
