### ISSUE TITLE
A filter can be enabled if filters group disabled

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2336]
1. go to AG side menu - content blocking  - filters
2. disable any filter group and open it
3. tap anywhere on filter name or description (not on switcher)

Actual behavior: it looks like a filter being enabling and protection has been restarted.

Expected behavior: you can not enable filter in disabled filters group.

**Comment by admitrevskiy** [comment]
Done.

Testing instructions:
-Reinstall AG
-Go to `Settings - Content Blocking - Filters - Any Filter group`
-Disable group

`Expected result:`
`-Protection should be restarted`

-Tap on filter name or disabled switch
`Expected result:`
`-Nothing happens`
