### ISSUE TITLE
Protection level activity issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2337]
1. It does not react to settings and status changes (request trial -> nothing changes)
2. It wrongly considers "premium" acquired when it's just an active trial period

**Comment by nkartyshov** [comment]
Fixed

Test instruction:
1. Install AdGuard
2. Go to Protection level screen
3. Request a free trial

Expected result:
Protection level screen should be change and  premium license option shouldn't be mark
