### ISSUE TITLE
App Management Crash

### ISSUE THREAD

**Issue by jessemclaren** [AdguardTeam/AdguardForAndroid#2338]
Using nightly 3.0.72 on an unrooted 7th gen Amazon HD-10 and on an ANS UL40 (Nougat, unrooted):  on both devices, choosing App Management causes immediate tofal crash.  Reported it via the app, but thought I'd mention it here.  If I remember correctly, the first v3 nightly was working.

**Comment by zzebrum** [comment]
@jessemclaren thank you for your report. We are aware of this problem, it will be fixed in the next nightly version!
