### ISSUE TITLE
Filters update might not work due to flawed implementation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2339]
The bug exists in the latest v3.0 nightly build.

Filter metadata is updated properly, but not the filters content

**Comment by nkartyshov** [comment]
Fixed

**Comment by nkartyshov** [comment]
Migration from 2.12
1. Install AdGuard 2.12
2. Got to Filters screen
3. Eneble few filters
4. Install AdGuard 3.0

Expected result:
The filters should be migrate from 2.12

Migrate from previus nigthly:
1. Install AdGuard previus nigthly
2. Got to Filters screen
3. Eneble few filters
4. Install AdGuard 3.0

Expected result:
The filters should be migrate from 3.0 and the filter group should be migrate too

Check filter update:
1. Install AdGuard
2. Tap to check filter update

Expected result:
The filters should be update if it really changed

First installation:
1. Install AdGuard
2. Go to the filters screen

Expected result:
Should be enable a recommended filters on Ad blocking, Privacy, Social and Language-specific groups

Enable group:
1. Install AdGuard
2. Go to the filters screen
3. Enable filter group

Expected result:
Should be enable a recommended filter

Eneble filter:
1. Install AdGuard
2. Go to the filters screen
3. Enable filter
4. Start protection

Expected result:
A rule should be apply

**Comment by karina-archazh** [comment]
Migration from 2.12 doesn't work as expected
After enabling 10-15 language filters in 2.12 and installation of v.3.0.195, only 5 filters are enabled.

**Comment by karina-archazh** [comment]
Some of the filters doesn't import during migration from 2.12
[adguard_logs_3.0.232_0802_1438.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2845329/adguard_logs_3.0.232_0802_1438.zip)
