### ISSUE TITLE
Add android:installLocation=auto to the app manifest

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#234]
http://developer.android.com/guide/topics/data/install-location.html

According to the documenation, out app should not be installed to the external storage. But anyway, there is a user request for us to add such option.

As I understand, if we set installLocation to auto, the app will be installed to the internal storage by default, so that should not be a problem.

**Comment by TPS** [comment]
So, is #168 invalid or just not recommended?  Will we eventually get the _option_ to do so (obviously, only if platform allows), even though it may not be by default?

**Comment by TPS** [comment]
~~So, is #168 invalid or just not recommended?  Will we eventually get the _option_ to do so (obviously, only if platform allows), even though it may not be by default?~~

OIC: This literally gives us the option, but not default.  Thanks!

**Comment by ameshkov** [comment]
@TPS , thank you for reminding me about #168 :)

**Comment by TPS** [comment]
No problem! :+1:

**Comment by TPS** [comment]
No problem! :+1: 

I guess this may not be as simple as modifying that manifest.  [As mentioned in that link](http://developer.android.com/guide/topics/data/install-location.html), I suppose you all will want to listen for `ACTION_EXTERNAL_APPLICATIONS_AVAILABLE`, as well as how to know when to start after boot, since `ACTION_BOOT_COMPLETED` won't be received.…  Same difference?

**Comment by ameshkov** [comment]
> Also, will some of AG's data — filters, userscripts (eventually), firewall settings, logs, &c — be on SD, also, along with the APK?

In fact I don't know where Android stores app data when it's installed on external storage.

Anyways, moving app there is not recommended and it is for power users only, who (I hope) are aware of possible issues.

**Comment by TPS** [comment]
>In fact I don't know where Android stores app data when it's installed on external storage.

I understand you have to [code for it directly](http://developer.android.com/training/basics/data-storage/files.html).

**Comment by ameshkov** [comment]
We may need to review how we save files also. 

But I was also talking about the shared preferences (which are used for saving app settings). 99% that it's saved on internal storage, but it worth checking too.

**Comment by Revertron** [comment]
I'm strongly against giving users an option to install Adguard on external storage. In some firmwares there is a hidden setting that installs all apps to SD by default. We will get a bunch of bugs instead of something useful.

**Comment by TPS** [comment]
@Revertron Then just telling us to try moving to internal storage (VERY simple & easy) to attempt to solve the problem! Not giving the _option_ for _that_ reason isn't really cool!

**Comment by ameshkov** [comment]
> In some firmwares there is a hidden setting that installs all apps to SD by default.

@TPS this is an important note. In this case the price for this install location option is high.

The app itself does not take much place, so what's important is where we store the app data and cache.
Cache is used for storing logs only. Data is used for storing domain-certificates cache.

In theory we could allow user to store app data on external storage. On the other hand it is really insecure to store certificates cache there as in this case we expose these certificates to other apps.

**Comment by TPS** [comment]
@ameshkov @Revertron Are you aware if any firmware, implementing all apps to installed to SD by default, that _doesn't_ allow moving to internal storage very simply?  Also, those using such alternate firmwares should be quite a small percentage, so such technical folks should be pretty savvy about possible issues.  The vast majority of users should be using stock manufacturer firmware, right?

What _is_ the breakdown between all the various data stored by AG, anyway?  I can pretty easily find, e.g., the APK size, but the rest?
* I assume, from experience, that logfiles are unbounded in size (until I clear the cache, anyway) & seem to be prime candidates for external storage.
* Do the filterlists take much room?  On, e.g., browser adblockers, they are the single largest component of the storage used.
* Certificate cache, I agree, is more secure internally, but I can't imagine it's particularly a huge cache (unless it, too, grows unboundedly like the logfiles — they should expire within a pretty short time, I hope)
* Firewall lists & settings — I've no idea @ all, size-wise.…
* What else is in that storage?

**Comment by Revertron** [comment]
The main problem with moving Adguard on external storage that it will be killed when user is unmounting SD-card. No application is alowed to work while it is unmounted - nor widget nor other background/foreground service.
Do we need such problems?

**Comment by TPS** [comment]
Most folks with external storage _rarely_ perform any action to unmount the card (besides rebooting, which [I addressed earlier]( https://github.com/AdguardTeam/AdguardForAndroid/issues/234#issuecomment-167288984)), as it's usually physically mounted next to the SIM (how often does the average person change _that_ out?), & are pretty aware, anyway, of what happens to software that's installed on media that's no longer installed.

**Comment by Revertron** [comment]
Some devices are connected as storage, not MTP. And in this case SD-card is unmounted from device and mounted to PC.

**Comment by TPS** [comment]
Special edge-cases should be handled specially, as in #285, but should be handled fine by listening for `ACTION_EXTERNAL_APPLICATIONS_AVAILABLE`, as mentioned earlier.  It's not upto you folks, anyway, to handle _every_ wonky thing that we users throw at you; as in #404, some things will be out-of-scope, but most typical issues will be resolvable for the greater good.

**Comment by Revertron** [comment]
In fact, if the SD-card is unmounted the app that is installed on it is killed instantly. And "ACTION_EXTERNAL_APPLICATIONS_AVAILABLE" is for other thing, for working with files on SD-card, not being runned from it.

**Comment by TPS** [comment]
Then, again, a rather uncommon case that a user will simply have to remember to rerun AG in the case they want to remount the SD.  Are no apps autorun from SD by Android on boot or after?

Also, you folks (@ameshkov @Revertron) are correct in that this is kind of 2 issues:
* _installed_ (or moved) to external
* _data_ on external

I hope for both, but [which actually gives the largest gain, if moved](https://github.com/AdguardTeam/AdguardForAndroid/issues/234#issuecomment-211715633)?

**Comment by ameshkov** [comment]
I'd like to avoid **installing app on SD** in any case, so the only thing in question is moving app data to external storage.

> I assume, from experience, that logfiles are unbounded in size (until I clear the cache, anyway) & seem to be prime candidates for external storage.

Usually log files are tiny, 10-100kb max (if you use default logging level).

> Do the filterlists take much room? On, e.g., browser adblockers, they are the single largest component of the storage used.

About 2-3 MB.

> Certificate cache, I agree, is more secure internally, but I can't imagine it's particularly huge (unless it, too, grows unboundedly like the logfiles — they should expire within a pretty short time, I hope)

Depends on your browsing profile. The cache is 10 days. So let's assume that we've generated 1000 certificates for 10 days. So it will take about 2-3MB.

> Firewall lists & settings — I've no idea @ all, size-wise.…

It is anyway stored in Android shared preferences, can't be moved.

> What else is in that storage?

That's all.

**Comment by TPS** [comment]
Well, for those who need this (the critically space-challenged, which I'd define as 512MB total user-accessible internal storage), the 12MB of app is the _key_ item to be saved vs. the 6.1MB (0.1 + 3 + 3 MB max mentioned above) of data, though the latter is very helpful, of course.

However, is it possible to start small with just the external _data_ option & then later on test externally moving the _app_ (maybe via α-testing as when deploying #21)?

**Comment by ameshkov** [comment]
> define as ≈512MB total user-accessible internal storage

Huh, so it is for VERY OLD devices anyway.

> However, is it possible to start small with just the external data option & then later on test externally moving the app (maybe via α-testing as when deploying #21)?

You're right, it is possible. However, I think we shouldn't do it until the size of AG data is more than 5-6MB. For instance, when we start storing some per-domain statistics and such.

**Comment by TPS** [comment]
Perhaps not just old ones, but the current low-end devices that advertise here in the U.S. as 4GB memory, but, by the time everything updates from Play, &c, there isn't much left over.

As for waiting.…  Isn't it better to get it figured out before you all add more data to the mix?  It'd make it easier to work out any kinks.  (Heck, it'd been easiest probably _before_ implementing #21 & firewall — including #25 — @ all, but I know it's not been a _top_ priority.)

Also, something to think over, also:  few apps (if any) installed to external are _completely_ installed there.  Usually, some portion (maybe 70%) is external, & the remainder still internal.  I never knew why, but I doubt that whole (currently) 12MB would be saved.  However, as more features are added/expanded, the app will continue to grow, & make a more difficult choice with each official release for many, so if _as much as possible_ is moved _from_ internal, such folks will continue to keep installed, update, & support (i.e., pay subscriptions).

**Comment by TPS** [comment]
What _was_ the resolution for this?

**Comment by ameshkov** [comment]
Yeah, this is just too problematic and will cause more questions/issues.
