### ISSUE TITLE
`https filtering` can be enabled for an app when AdGuard protection is disabled

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2342]
<details><summary>Screenshot:</summary>

![screenshot_20181122-191826](https://user-images.githubusercontent.com/44832195/48916552-d66ef800-ee93-11e8-9886-41a5690256e2.png)

</details>

Also, need to grey out those icons:

<details>

![screenshot_20181122-201953](https://user-images.githubusercontent.com/44832195/48916656-336aae00-ee94-11e8-961e-2109051dff88.png)

</details>

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Reinstall AG
-Try to reproduce the issue
