### ISSUE TITLE
Enable HTTPS notification is visible when certificate is moved to the system store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2343]
Report from the telegram chat:

> On the latest nightly you've added the notification "Enable HTTPS filtering for better blocking quality".

> When the certificate is moved to the system store on a device with root access that is still there. Is that intentional?

**Comment by nkartyshov** [comment]
Cannot reproduce

I think this bug has already fixed in issue https://github.com/AdguardTeam/AdguardForAndroid/issues/2360
