### ISSUE TITLE
Black area appears and the cursor moves on the keyboard after scroll text (User filter section)

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2345]
### Steps to reproduce
1. Tap on three dots button at the right corner of the header
2. Tap on edit filter
#
https://uploads.adguard.com/edit_filters.jpeg

### Your environment
* Adguard 3.0.0 (100n)
* All devices

**Comment by nkartyshov** [comment]
Cannot reproduce

**Comment by nkartyshov** [comment]
fixed
