### ISSUE TITLE
Filters are going off randomly

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2348]
v3.0.100n

**Comment by TPS** [comment]
If this is re: the _builtin_ filterlists, I'm having something like this happen on _every_ ηightly update:  Random filterlists are turned on/off.…  It's quite annoying to have to redo all this!

**Comment by patrickdrd** [comment]
you can always go back to the latest stable, that's what I did and I'm very happy,
stable version is indeed.. very stable,
version 3.0 needs a ton of work to be done in order to become stable
