### ISSUE TITLE
[Android] Unable to use Samsung pay mini until VPN is active

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2349]
Samsung Pay mini in South Korea won't work when any VPN is running.

[APK download link](https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-pay-mini/samsung-pay-mini-2-9-39-release/samsung-pay-mini-2-9-39-android-apk-download/)

Same as #1209 

<details><summary>Screenshot:</summary>

![smsp1](https://user-images.githubusercontent.com/37797229/49071140-63240800-f23e-11e8-91e2-1d8cdb59537e.jpeg)
![smsp](https://user-images.githubusercontent.com/37797229/49071141-63bc9e80-f23e-11e8-8f2a-417d90aacf5a.jpeg)

</details>

### Customer ID 
2044663

**Comment by Revertron** [comment]
Fixed. Will be available in new nightly.

**Comment by Kgyeongmin** [comment]
Still Error occur

![screenshot_20181129-133956](https://user-images.githubusercontent.com/45446424/49199850-60abe480-f3dd-11e8-9f1d-06624fe613c1.png)

Message :  To use "samsung pay mini", disconnect the VPN connection and try again.

**Comment by ameshkov** [comment]
@Revertron so I guess this app does not send `Intent.ACTION_CLOSE_SYSTEM_DIALOGS` as the "big" Samsung pay does? Or maybe it does not come to the foreground?

@Kgyeongmin could you please collect Android logs for us?

Here's how to do it: https://kb.adguard.com/en/android/solving-problems/logcat

We will also need to know the exact time when you reproduced the issue to find that place in the logs.

**Comment by Kgyeongmin** [comment]
I get log file. Where I send file?

**Comment by ameshkov** [comment]
@Kgyeongmin thank you!

`devteam@adguard.com`

**Comment by ameshkov** [comment]
@Kgyeongmin got the logs, thank you!

@Revertron check the logs, starting at `18:04`

**Comment by Revertron** [comment]
It seams from the log, that it has another package name:
```
SAMSUNGPAY: [GearForegroundService] onStartCommand - intent = Intent { act=com.samsung.android.spay.gear.ACTION_START_FOREGROUND_SERVICE cmp=com.samsung.android.spaylite/com.samsung.android.spay.gear.service.GearForegroundService }
```

**Comment by Revertron** [comment]
@Kgyeongmin try this one, please:
https://uploads.adguard.com/adguard-v3.0.112n-samsung-pay-mini.apk

**Comment by Kgyeongmin** [comment]
still error occur2018. 11. 30. 오전 12:47에 Roman <notifications@github.com>님이 작성:@Kgyeongmin try this one, please:
https://uploads.adguard.com/adguard-v3.0.112n-samsung-pay-mini.apk

**Comment by Revertron** [comment]
@Kgyeongmin In that build I've added more logging, can you please export logs from AdGuard (no need for logcat) and send to devteam@adguard.com again?

**Comment by Kgyeongmin** [comment]
send it2018. 11. 30. 오전 1:12에 Roman <notifications@github.com>님이 작성:@Kgyeongmin In that build I've added more logging, can you please export logs from AdGuard (no need for logcat) and send to devteam@adguard.com again?

**Comment by Revertron** [comment]
@Kgyeongmin Something is wrong with the mail I think, can you resend it one more time?

**Comment by Kgyeongmin** [comment]
resend it
​
-----Original Message-----
