### ISSUE TITLE
https got disabled all of a sudden

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2350]
hello,
after the problems with filters in nightly, I installed latest stable,
but some hours ago I witnessed the first bug,
after switched of airplane mode and
after browsing a bit, I noticed that AG wasn't working properly,
I restarted it twice, the same results,
so, I had to search what was going wrong with the settings,
I found out that https was disabled out of nowhere!
I switched it on, it requested to install a certificate, 
I went on to check certificates and the old one was there too,
can you explain why/how did this happen?

* Adguard version: latest stable (2.x)
* Adguard filtering mode: VPN
* Device model: Nokia 6
* Operating system and version Android 7.1.2
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?
none

**Comment by TheHasagi** [comment]
@patrickdrd 

Hello!

Can you send us the log files?

You need to set the logging level parameter to debug in AdGuard - Settings - Advanced - Logging level.

After you completely reproduced the issue export and send them to aa@adguard.com

**Comment by patrickdrd** [comment]
I don't think it's easy to reproduce,
because I'm using 2.12 since saturday and it only just happened today,
what's the default logging level?
can I check if there's any error recorded there?

also, what are the recommended settings?
I'm using  (low level) pref.enforce.paused.notification, 
pref.proxy.disable.reconfigure,
pref.vpn.disable.pause and
today I checked pref.vpn.disable.reconfigure too,
because I thought that maybe this caused the https malfunction,
I've had similar problems with latest nightly too,
which were solved by restarting AG

I also have a macrodroid macro to monitor AG's notification and 
send a start command (through automation) when it is cleared

**Comment by TheHasagi** [comment]
You can, but let's keep this to our devs:)
 Settings are optimized by default and nothing to change is needed. Is it possible to reproduce on 2.12?

**Comment by patrickdrd** [comment]
I told you, AFAIK it happened only once, how could I know?
maybe I should keep an eye on it

**Comment by TheHasagi** [comment]
Ok, I'll close this issue until it's can be reproduced with log files.

**Comment by patrickdrd** [comment]
ok, but my point is that you should have warned to user with a big red alert that he's without https protection (which is equal to unprotected for the most part),
rather than spending his time to find out why his newly bought software 
(which is supposed to be stable too!) doesn't work as it should
