### ISSUE TITLE
Widget redesign 

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2354]
Since we change the app icon we need to redesign the widget icon. Plus don't forget about landscape orientation.

**Comment by TPS** [comment]
Could we [get a type of the original version of the widget back, as well/instead](https://github.com/AdguardTeam/AdguardForAndroid/issues/1231#issuecomment-441449995)?

The slider is quite [accessible](https://github.com/AdguardTeam/AdguardForAndroid/issues/957), I'm sure, but looks so bleh, & isn't particularly AG-looking visually.

Maybe remove "AdGuard" & make the dot in the slider an AG-🛡️, toggling from bottom to top (like a light switch), while _also_ going from red to green, & perhaps a neutral grey/yellow position in between if AG isn't even loaded/running. (🚦-ish, if that renders correctly!)

**Comment by karina-archazh** [comment]
Some unexpected UI results is here: https://github.com/AdguardTeam/AdguardForAndroid/issues/2484
