### ISSUE TITLE
Background / foreground CPU time on the battery usage screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2355]
It'd help us understand whether there is an issue with the filtering engine or if the user kept the UI open for too long.

**Comment by ameshkov** [comment]
Let's do it in v3.0 nightly, it will help us figure if there're any battery usage issues.

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Examine new fields at the Battery Usage screen:
Compare background (when app is minimized) and foreground (when app UI is visible) battery usage statistics.
