### ISSUE TITLE
Wrong date format for "Ads blocked", "Trackers blocked", "Threats blocked" and "Data saved" in other languages.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2356]
The now date format for "Ads blocked", "Trackers blocked", "Threats blocked" and "Data saved" is wrong in Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/EokAIlZ.png)
</details><br/>

ex: 29 Nov
According to your now date format, 29 11月 is very strange date format for Chinese.
Nov -> 11月
29 -> 29日
"29 Nov" should be "11月29日" in Chinese, not "29 11月".

Some other languages have a different word order for date format.
You have to upload the phrase to onesky for letting me translating.

**Comment by ameshkov** [comment]
We'd better format it automatically but using proper locale and not a hard-coded format string as it is now.

**Comment by Revertron** [comment]
But we are using Androids formatting:
```
DateFormat.getLongDateFormat(context).format(date);
```

**Comment by lancelot-moon** [comment]
The date format in #47616884 of Adguard Android / Android App is what you should give.
#47616884
Updated %s
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7M2KlsN.png)
</details><br/>

**Comment by lancelot-moon** [comment]
@Revertron 

About date format in Chinese:
https://www.ibm.com/support/knowledgecenter/en/SSS28S_3.0.0/com.ibm.help.forms.doc/locale_spec/i_xfdl_r_formats_zh_Hant_TW.html
