### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2358]
A single place for all small UI issues.

I'll be adding items to the checklist below, don't close this issue.

* [x] "Get Premium" align: https://uploads.adguard.com/up04_xul82_App.png
* [x] No scroll in the dialogs: https://uploads.adguard.com/up04_mrojb_2018-12-20_12.28.57.jpg
* [x] Available date ranges should be the same everywhere (it's 24h on the main screen and "today" in the notification and apps mgmt) -- we should use: `Today`, `24h`, `7d`, `30d`, `All time`.
* [x] Consider increasing font size
* [x] Icons are too thin. In some places, it's hard to see them (for instance, apps management list)
* [ ] Automatic protection restart might be annoying, any ideas?
* [ ] Add description for the "no license" case: https://uploads.adguard.com/up04_h1v1q_App.png
* [x] It's unclear what we show on the chart in the apps mgmt

**Comment by Revertron** [comment]
> Automatic protection restart might be annoying, any ideas?
Add an icon to the ActionBar as "Apply".

**Comment by lancelot-moon** [comment]
May you adjust some words somewhere to bigger words if space of field is enough for all languages' translations?

I mean big a little~ a little...

Compared with v2.12, I really think words of UI are smaller in v3.
Maybe you need to consider for old persons.

Thanks.

**Comment by Revertron** [comment]
@lancelot-moon, you are right, the font sizes are smaller. And it is not a good thing :(

**Comment by TheHasagi** [comment]
#### Little glitch:

Open filtering log, open sidebar and tap on the icon it will ask you to disable filtering log, if you go back it will show you that filtering log is disabled, but it's not.

**Comment by admitrevskiy** [comment]
[ ] - Disable OutboundProxy screen if Outbound Proxy is disabled
[ ] - Replace `No connection with DNS upstreams` snack with upstreams EditText error
[ ] - Show EditText error in FeedbackActivity if email address field is empty
