### ISSUE TITLE
Please give tabs for those configurations which need root access for taking effect in low level settings.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2359]
1. In low level settings of AG for Android, "This might void your warranty!"
Why does it say so?
What does the "warranty" mean? A device's warranty?
Will it void a device's warranty if I don't root my device but simply do changes in low level settings?

2. It seems that some configurations in low level settings need root access for taking effect, right?
May you give tabs for those configurations which need root access in low level settings?
Such the below:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/s7GMAVK.png)
</details><br/>

Thanks.

**Comment by artemiv4nov** [comment]
We removed these settings from the low-level, I'll close the task.
