### ISSUE TITLE
Cert is not moved to the system store

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2360]
It looks like AG was granted superuser rights, but https filering is off
video: https://uploads.adguard.com/video_2018-11-29_16-03-09_2018-11-29_16-06-04.mp4

Can't repro on test devices, but I have logs from user.

**Comment by jslawler** [comment]
Issue is currently rectified by manually exporting the certificate and pasting it to the system store.

**Comment by ameshkov** [comment]
> and pasting it to the system store

How exactly did you paste it to the system store?

**Comment by jslawler** [comment]
> > and pasting it to the system store
> 
> How exactly did you paste it to the system store?

Initially I attempted a move with "Move Certs!" Followed by a restart however this caused HTTPS filtering to inconsistently work by causing certificate errors in some apps even after cleaning cache.
Manually copying and pasting the user certificate to the system store directory using a file manager followed by a restore corrected the issue and made HTTPS filtering function correctly.

**Comment by ameshkov** [comment]
@nkartyshov please check this:

> It's being moved, but only to the masked (i.e. bound) version of /system, not the actual file-system of the device.

> AdGuard really ought to be made to detect this and give an error.

> Use the Move Certificates module from the Magisk Repo.

> Then, the cert will be moved every time you boot, before AdGuard can start.

**Comment by ameshkov** [comment]
@nkartyshov check these modules:

* https://github.com/NVISO-BE/MagiskTrustUserCerts
* https://github.com/Magisk-Modules-Repo/movecert

https://github.com/NVISO-BE/MagiskTrustUserCerts/blob/master/common/post-fs-data.sh

**Comment by nkartyshov** [comment]
> Use the Move Certificates module from the Magisk Repo. Then, the cert will be moved every time you boot, before AdGuard can start.

Magisk Certs Move module works perfect and adguard detects a certificate moved with this module

> The path to the real /system on a Magisk system has been /sbin/.core/mirror/system for a long time now, but please be aware that this has recently changed in recent Magisk snapshots, and that this path is now a symlink to the new location. The new location (since 15-11) is /sbin/.magisk instead of /sbin/.core.

Yes, i found  /sbin/.core/mirror/system in file system on google 6p. But we cannot mount this because have not information in /proc/mounts about this directory.

**Comment by nkartyshov** [comment]
I looked at the code of the magisk module and any changes to the system are made through the overwriting magic.img.

**Comment by ameshkov** [comment]
@nkartyshov let's do the following then:

1. Check for Magisk presence
2. If it is detected, show an alert dialog:

```
AdGuard detected that you're using Magisk. In the case of Magisk, it is recommended to use the "Move Certificates" module from the official modules repository.
```

Buttons:
* `How to use Magisk` -- opens `https://www.xda-developers.com/how-to-use-magisk/`
* `Move anyway` -- moves certificate as we usually do. 
* `Cancel` -- closes dialog

**Comment by nkartyshov** [comment]
done

Test instruction:
1. Install AdGuard
2. Got to https filtering screen
3. Install certificate
4. Move to system store

Expected result:
If su is Magisk then should be show alert with three options(see on previous comment). 
if su is SuperSu then certificate should be move to system store

1. Install AdGuard
2. Got to https filtering screen
3. Install certificate
4. Move to system store
5. remove certificate

Expected result:
Certificate should be remove to system store

**Comment by zzebrum** [comment]
On android 8 can't remove cert
@nkartyshov please take a look

**Comment by nkartyshov** [comment]
Fixed
