### ISSUE TITLE
Can't play videos on iqiyi.com with AG enabled.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2364]
https://tw.iqiyi.com/v_19rr46hfr4.html

A. I use AG for Android v3.0.109 nightly.
After enabling AG, there are 2 issues when playing videos by chrome on Android.
1. Videos are always loading and can't be played.
2. When clicking other video' page, it won't go to another video's page. No response.
ex: You can try to click videos in "相關視頻" below.

There might be bugs in CoreLibs...

With AG:
Always loading... The video can't be loaded.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fOH79LL.png)
</details><br/>

Without AG:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vesIxVP.png)
</details><br/>

B. After adding iqiyi.com in the whitelist of HTTPS filtering, videos can be normally played by chrome on Android with AG enabled.
But it won't use AG certificate when visiting https://tw.iqiyi.com/ on Android with AG enabled.
So the new rules for skipping ad videos by @AdamWr won't work.
https://github.com/AdguardTeam/AdguardFilters/issues/22801#issuecomment-444051648

**Comment by zzebrum** [comment]
@karina-archazh try to reproduce, please.

**Comment by lancelot-moon** [comment]
You may need Taiwan or Hong Kong ip.
Or try the link...
https://tw.iqiyi.com/v_19rr3o9ddc.html

**Comment by karina-archazh** [comment]
Thanks for info.
I'll get back for this issue as soon as possible.

**Comment by lancelot-moon** [comment]
AdamWr said he could play the video without Taiwan ip on iOS.

You may try this on Android with AdGuard.
https://tw.iqiyi.com/v_19rr3o9ddc.html

**Comment by lancelot-moon** [comment]
After updating to v3.0.129η, the video can be normally played.
Strange...

@AdamWr, Will you meet the issue if you use old v3.0.109η?

What did you fix in the CoreLibs of v3.0.129η?

**Comment by sfionov** [comment]
@lancelot-moon 

> What did you fix in the CoreLibs of v3.0.129η?

There was no CoreLibs updates between 3.0.109n and 3.0.129n.

**Comment by lancelot-moon** [comment]
Thanks for your reply.
May somebody try v3.0.109η for the issue?
Can you reproduce?

I also meet the strange issue on iOS.
https://github.com/AdguardTeam/AdguardForiOS/issues/867

**Comment by lancelot-moon** [comment]
I tried v2.12.248η, but the video can't be played.

**Comment by karina-archazh** [comment]
@lancelot-moon hi, sorry for the delay
I've checked on last release version 2.12.247 and everything works fine: video plays and switching to the next video is enabled
