### ISSUE TITLE
user filter disable doesn't work

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2366]
last night I run into a conflict,
an entry I've had in my user filter conflicted with an entry in default filters (AG's ones),
I didn't know until I started troubleshooting,
and in order to do so, I started disabling entries about that domain in the user filter,
well, it didn't work, even if I disabled them all (about that domain),
the problem remained,
I've had to delete the user filter at all in order to make it work and
then to find out there was a conflict,
I mean, disabling didn't have any effect on the page with the problem reload,

I'm running AG 2.12 stable (VPN mode) on android 7.1

**Comment by zzebrum** [comment]
I'm not sure if that's the problem. It maybe caches for example.
Can't repro the issue. Can you give me an exact example?

**Comment by patrickdrd** [comment]
well, I've had issues with the user filter for the last days, 
I think the user filter need a bit of work and
the issues persist since 2.12 stable,

let's start:
1)a. editing doesn't seem to work, e.g. I've had some filters for `m.facebook.com`  and decided to change them to `facebook.com`, after editing and doing search again, I saw that `m.facebook.com` was still there
b. I disabled some filters (even all of them eventually) for facebook to see what was causing the new filter to not work, seemed to have no effect, even after AG's restart, the same was with deleting all the previous user filters, I only managed to check my new filter after removing everything and start from scratch,

2) can I make a new question here: dns (hosts) blocking works only with user filter? on the weekend I noticed that my entries weren't blocked by dns if they were in a url in custom filters,
they did when I moved them to user filter(s),

3) in version 2.12 I've had problems with `redirect.viglink.com`, which was blocked by AG,
so I created the following filter: `@@||redirect.viglink.com$app=com.adguard.dns`,
on the weekend I installed nightly and I noticed the above didn't work, 
so `redirect.viglink.com` was again blocked!
the "strange" thing is that I wasn't exactly blocking it, but I was blocking the parent,
`||viglink.com^`, which as far as I know,
wasn't supposed to block the whole domain, i.e. affecting `redirect.viglink.com`, so I had to remove `||viglink.com^` in order for `redirect.viglink.com` to work, is there a bug here? or has the implementation changed? 
because I've still had `||viglink.com^` in 2.12 dns hosts blocking (via user filter) and 
`redirect.viglink.com` was working

**Comment by zzebrum** [comment]
@patrickdrd are problems still reproducible?

**Comment by patrickdrd** [comment]
no, no issues with it, but I didn't try it that much either, only issue with [url=https://github.com/AdguardTeam/AdguardForAndroid/issues/2633]sdn[/url]

**Comment by zzebrum** [comment]
reopen if needed then.
