### ISSUE TITLE
uploading problems

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2367]
I also think we need to open an issue with the uploading problems,

more on:
https://forum.adguard.com/index.php?threads/slow-down-google-drive-upload.29493/

I've discussed it extensively with @TheHasagi on telegram,
I've sent him logs too this morning when my drivesync (or "autosync for google drive")
stuck in network error (only solution is to disable AG for the uploading apps)

**Comment by zzebrum** [comment]
@patrickdrd @TheHasagi guys, please provide steps to repro so I could check it.

**Comment by patrickdrd** [comment]
it is not constant (i.e. it doesn't happen all the time, so you will need to monitor it for some days,
affected apps are: drivesync (or aytosync for google drive by metactrl,  titanium backup, es file explorer and - possibly, I haven't used it that much - solid explorer),
here are the steps:
in general, first of all:
use a google drive account and with AG's protection set to on (with or without https filtering) for the above apps, try to upload some files (let's say average size - around 10-20 megabytes, it depends of the network speed, anyway, let it upload for some minutes) to google drive, 
using drivesync you can create a pair of folders (one local on the device and the other on google drive), so you can try copying files locally and let it upload them afterwards,
using es file explorer  (in this case you can just try to copy a file over to a google drive folder),  I've noticed that even the calculation for the remaining time is wrong with AG enabled and another symptom is that the progress bar reaches the end immediately after starting uploading

**Comment by TPS** [comment]
I'm having uploading issues w/ Amazon Photos (as well as #1094).  When I bypass AG, it works fine.

**Comment by TheHasagi** [comment]
Dears, does it continue with the [latest nightly](agrd.io/android_nightly)?

**Comment by TPS** [comment]
Now, Amazon Photos works fine, but GDrive (#1094) is still flaky:  sometimes uploading works fine, other times it doesn't, & I've no idea the difference why.

**Comment by TheHasagi** [comment]
Well, I guess it is related to your carrier/internet provider. Try to use it with the public WiFi or with other WiFi spots. Closed for now.
