### ISSUE TITLE
Wi-Fi direct vs. VPN mode issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#237]
The customer managed to fix the issue on his side by adding two files into pref.net.exclusions.

"Ребята! Проблема решена. Просто в низкоуровневых настройках добавил в исключения фильтрации 2 процесса:
com.samsung.android.app.FileShareClient
com.samsung.android.app.FileShareServer
Теперь и принимает, и отсылает.Прошивка сток без рута и кастом рекавери...Может добавите в обновлении эти файлы в исключения, чтоб не вводить их вручную?Спасибо"

Please consider. BTK-739-25300.

**Comment by ameshkov** [comment]
Added to net_exclusions.
