### ISSUE TITLE
Add stealth mode parameters to the report link

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardForAndroid#2370]
Look how it works for Window application https://reports.adguard.com/en/new_issue.html

**Comment by nkartyshov** [comment]
done

Test instruction for QA:
1. Install AdGuard
2. Enable stealth mode
3. Go to Send feedback 
4. Select Missed Ads or Incorrect Blocking
5. Go to step 4 on report web site

Expected result:
The stealth mode parameters should be filled
