### ISSUE TITLE
[Filtering log] Don't hide filters button when the search field contains a text

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2372]
![image](https://user-images.githubusercontent.com/8361299/49659690-6e9cdd80-fa4d-11e8-84aa-94cd19512c29.png)
or
![image](https://user-images.githubusercontent.com/8361299/49659796-b6236980-fa4d-11e8-902b-fcc189154330.png)

**Comment by admitrevskiy** [comment]
Resolved.

**Comment by Alex-302** [comment]
An issue with it
![image](https://user-images.githubusercontent.com/8361299/50169943-623f3d00-02f7-11e9-8e4c-ea2e3f1ffd79.png)
