### ISSUE TITLE
Please again improve the layout of DNS settings.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2374]
@ameshkov 
@Revertron
@sfionov

I feel disappointed at the new layout of DNS settings in v3.0.129η.
**Especially, I wish the descriptions of public regular DNS back!!!**

You simply **throw** most parts of regular & secure DNS service into the same list, which is **disordered**!
And you **only** give 5 recommended DNS providers.
**We had chosen the most popular regular DNS providers on the world in the past.
They're all recommended regular DNS providers, and their descriptions are necessary.**

Well, you let users choose server type (Regular, DNSCrypt or DoH) in the 5 recommended DNS providers.
How about IPv4 or IPv6?
ex: Use Google DNS (IPv6, DoH).

These are my idea.
**Please...!!! I really very dislike your new layout of DNS settings.**

**The main screen of DNS settings:**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ibVOWmV.png)
</details><br/>

Consider for filters subscriptions for DNS filtering.
For System default DNS, let AdGuard automatically detect the current DNS and show the current DNS IP address on screen if possible.
When using mobile cellular network, AdGuard shows ISP's DNS IP address.
When using Wi-Fi network, AdGuard shows modem's DNS IP address.
When connecting to a real VPN server with AdGuard local HTTP proxy mode, AdGuard shows VPN provider's DNS IP address.
(**If it's difficult to let AdGuard automatically detect the system DNS, simply ignore.**)

**For custom DNS service:**
The ability of adding 20 custom DNS service at least.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/mWxgXa1.png)
</details><br/>

**For regular DNS service:** (The tabs for regular DNS, secure DNS, IPv4 and IPv6.)
**Please give the regular DNS service list and their descriptions in v3.0.109η back, except for Norton DNS.**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NpbXfwF.png)
</details><br/>

**For secure DNS service:** (The tabs for regular DNS, secure DNS, IPv4 and IPv6.)
We don't give descriptions for introducing their characteristics.
Even DNSCrypt and DoH can be tabs in the back of secure DNS name.
This can shorten the secure DNS list.
**Note "location" for regional DNS service.**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/KgDTmZM.png)
</details><br/>

I'll appreciate if you approve my idea!
Thanks.

**Comment by ameshkov** [comment]
The app is not a repository of all the DNS services. We want to make the list as short as possible because this list is confusing for most of the users. Moreover, these services tend to disappear with time and maintaining the list of alive services is time-consuming.

> And you only give 5 recommended DNS providers.

As I've said, this list should be short to avoid confusing casual users.

> We had chosen the most popular regular DNS providers on the world in the past.

That was not "the most popular" list but every known DNS service.

> How about IPv4 or IPv6?

Using IPv6 server may break the internet access in IPv4-only networks, therefore making this option easily accessible for casual users is dangerous.

> These are my idea.

Regarding the screenshots, I'll need more time to analyze them.

**Comment by lancelot-moon** [comment]
In my **user experience**, I really dislike your new layout of DNS settings......
No need to give the only 5 recommended DNS providers.
Originally, your DNS list was very poor in old v2.10.
Afterwards, we picked DNS service and then made the best DNS list on the world.
But now you just throw most of them into a disordered list, which is not a responsible method.

Please seriously consider.
Большое спасибо!

**Comment by lancelot-moon** [comment]
How do you define the recommend DNS provides for different users?

For example, Clouflare DNS is fast, but sometimes users meet trouble because it sometimes can't resolve IP for some domains due to DNSSEC issues.
Do you know?

We already gave the great list with descriptions in the past.
Why do you throw most of them into trash can?
Maybe users like those simple descriptions for popular DNS service.
He maybe says, "Wow, in the past, I didn't know that there are these functional DNS service on the world."

When a user dislikes your 5 recommend DNS provides, he will need to view the so long and disordered DNS list and feel bad.
He will say, "OOOXXXX..."
You still don't solve the disordered thing.

Sorry, I just express my thought to let AdGuard better.
Hope that I don't offend you. m(__ __)m

**Comment by Revertron** [comment]
> How do you define the recommend DNS provides

Recommended means that somebody recommends it. We recommend using these 5 DNS providers.
The other servers are not recommended.

If the user knows something about DNS and its security, he will Google something about it and he will know what to choose. If we are to make a product for not so experienced users, we need to make the interface simpler.

**Comment by lancelot-moon** [comment]
Hi, I updated the screenshot for secure DNS list.
A tab of "DNSCrypt" or "DoH" in the back of secure DNS name.
Shorten the known DNS list as possible especially if we separate them into IPv4 and IPv6 tabs...
(You put DNS service for IPv4 and IPv6 in the same list, which is a little long.)

**Comment by lancelot-moon** [comment]
> If the user knows something about DNS and its security, he will Google something about it and he will know what to choose.

Choose from the so long and disordered DNS list (if not wish the 5 DNS providers)?
Are you serious?

**Comment by lancelot-moon** [comment]
Update screenshots again.
Hide DNS IP, SDNS stamp or description in the icon of exclamation mark.

**Comment by ameshkov** [comment]
We don't want to make AdGuard app a repository of known DNS services, it does not make sense to hardcode this stuff in the app. This is why the list of recommended services will never be huge, it consists only of the services which we are sure will continue to operate for years. We also cannot place regional services there as it is not relevant to users from a different region.

Regarding other DNS services, ideally, they should be listed on the knowledge base but not inside the app, and the "choose DNS server from list" should lead there. The problem with the knowledge base is that it does not support all the languages, but this will be solved with time.

Regarding the screenshots.

https://i.imgur.com/ecG8g6O.png

1. Custom filters / hosts for DNS filtering won't be in v3.0, but yeah, when we implement them, it will be another item on that page.
2. Different text changes -- some of them we will use (not all though).

https://i.imgur.com/UJwiJYs.png

1. The recommended list does not go away
2. Custom servers metadata is not good indeed and should be improved.

https://i.imgur.com/ZHISFmR.png

1. There will be no tabs anymore and here's why - if a DNS service provides an encrypted version, it should be used by default.
2. I don't understand what's the big deal with IPv6. IPv4 is stable and works everywhere, even in the IPv6-only networks as they all support NAT64. Promoting IPv6 to users will cause them trouble with no benefit whatsoever.

**Comment by ameshkov** [comment]
Here's what I propose to change in v3.0:

1. "Choose DNS server from a list" link should lead to a new page on the knowledge base instead what it currently does.
2. Here we will have nice and clean list of DNS providers that can be easily maintained without updating the app.
3. Make AdGuard intercept links with `sdns://` protocol. Click on such a link will be intercepted, and AdGuard will propose adding a new custom DNS server.
4. Some text and cosmetic changes need to be done as well.

**Comment by lancelot-moon** [comment]
I can't understand why you must combine custom DNS and public DNS list in the same place.
Terrible!

**The main screen of DNS settings:**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ecG8g6O.png)
</details><br/>

The above screenshot is already a good layout.
Please let custom DNS service and public DNS service be in the different zones.

I knew custom filters / hosts for DNS filtering won't be in v3.0.
You ever said it will maybe be in v3.1.
**For the new DNS feature, I wish blacklist, whitelist, filters subscriptions and recommended default filters list, such as the privacy setting of AG Pro for iOS.**

> The recommended list does not go away

I dislike the idea for 5 recommended DNS providers.
The space is wasted.
**I wish the regular DNS service list and their descriptions in v3.0.109η back, except for Norton DNS.**
You just don't understand users hope that their favorite DNS servers can be in the default known list, compared with manually adding them.
And you simply throw most of them (IPv4 and IPv6 even regular & secure DNS) into the so long and disordered DNS list.
You think that things are solved since you hide them.
But actually you solve nothing.

> There will be no tabs anymore and here's why - if a DNS service provides an encrypted version, it should be used by default.

I maybe use its regular DNS service.
Why should I must use its encrypted version?

> I don't understand what's the big deal with IPv6. IPv4 is stable and works everywhere, even in the IPv6-only networks as they all support NAT64. Promoting IPv6 to users will cause them trouble with no benefit whatsoever.

Some users use IPv6 network.
Why should we not classify them (IPv4 and IPv6 even regular & secure DNS) well from the beginning?
You totally make a disordered DNS list, except for your 5 recommended DNS providers.

**Comment by ameshkov** [comment]
> I maybe use its regular DNS service.
> Why should I must use its encrypted version?

Then you can choose the regular version. I am talking about **default** settings which can be changed. Using less encrypted DNS by default would be strange.

> Some users use IPv6 network.

It does not matter, IPv4 works in any network.

> You totally make a disordered DNS list, except for your 5 recommended DNS providers.

It's more than that, I even want to move it outside the app.

**Comment by ameshkov** [comment]
> Why should we not classify them (IPv4 and IPv6 even regular & secure DNS) well from the beginning?

Classifying is a good thing, but we are doing it in a wrong place -- hardcoding all this stuff inside the app is too hard to maintain.

We should move it to the KB:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2374#issuecomment-445170515

**Comment by lancelot-moon** [comment]
Honestly, I understand your thought.
Compared with classifying the DNS service list well, you more want to remove them.
But you ignore that users wish good DNS service list for choosing, especially favorite DNS service in the known list.

You're a designer.
I'm a user and express my user experience.
Nobody is wrong.
Just we don't have the intersection...
A pity.

**Comment by ameshkov** [comment]
> But you ignore that users wish good DNS service list for choosing

What I propose should satisfy those users as well. 

You should consider the full picture: this list of DNS is needed for all AdGuard apps, not just for the Android version. Hardcoding it inside Mac or Win does not make much sense.

**Comment by ameshkov** [comment]
Here's an example of how the KB page I am talking about:
https://gist.github.com/ameshkov/b904a5bf7bb162bbc4d95c6f1ea1b89e

**Comment by lancelot-moon** [comment]
IPv4 and IPv6 in different tabs.
**Regular DNS with their descriptions in app:**
AdGuard
Cisco OpenDNS
CleanBrowsing
Cloudflare
Comodo
DNS.WATCH
Dyn
Fortinet Secure
Freenom World
Google DNS
Neustar Recursive DNS
Open NIC
Quad101
Quad9
Safe DNS
SafeSurfer DNS
Strongarm DNS
Verisign
Yandex

**Secure DNS:**
AdGuard
Cisco OpenDNS
Cloudflare
Google DNS
Quad9
The above 5 DNS providers in app.
Others on the KB page.

**Comment by ameshkov** [comment]
1. It does not make sense to divide regular and secure, DNS providers are what matters.
2. The recommended list is at max size. We can change what's inside but making it bigger is out of the question. Maybe we'll even remove Quad9 from it, nobody knows what's that it anyway.
3. KB page does not mean that it will be hard to add anything from there, it will be as easy as clicking on a link.

> IPv4 and IPv6 in different tabs

Again, mentioning IPv6 is dangerous to casual users. For a mobile user, this is normal to go from IPv4 to IPv6 network and back, and using IPv6 DNS will break the internet to them. Only IPv4 is safe to use (until we implement DNS profiles so that users could choose which server to use on per network basis).

**Comment by lancelot-moon** [comment]
I know what you said...
For your 1st point:
I maybe make new layout according to it.

For your 2nd point:
I wish the 19 regular DNS providers and their descriptions back.

For your 3rd point:
I guess you'll simply throw all other DNS servers to KB page.
The list on KB page will be even much longer than the now list in app.
I can accept that you throw other secure DNS to KB page, not including the 19 regular DNS providers.

I also know that most people use IPv4.
But some other users use IPv6 network.

**Comment by ameshkov** [comment]
> The list on KB page will be even much longer than the now list in app.

It will be structured and easy to navigate compared to what it was.

> But some other users use IPv6 network.

IPv4 addresses work in most of the IPv6 network due to NAT64.
IPv6 addresses do not work in IPv4 networks.
