### ISSUE TITLE
[Android] AdGuard crashes with CBC app

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2376]
AdGuard crashes if open About menu in CBC app and tap on any of options (screenshot attached).

### Steps to reproduce

1. Start AdGuard 3.0
2. Open CBC app - Settings - About - tap on any options (e.g. Help and FAQ, Terms of Use, Privacy Policy)

### Expected behaviour

The selected option should open.
### Actual behaviour

AdGuard crashes.

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagisbmkr.png)

</details>

### Customer ID 

1617051
### Your environment

* Adguard version: 3.0.129n(1.2.150cl)
* Adguard filtering mode: VPN 
* Device model: Samsung Galaxy S9 plus
* Operating system and version: 8.0.0

**Comment by TheHasagi** [comment]
[App](https://play.google.com/store/apps/details?id=ca.cbc.mobile.android.cbcnewsandroidwebview&hl=ru)

**Comment by zzebrum** [comment]
Can't reproduce.
