### ISSUE TITLE
Wrong icon for the whitelist and user filter

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2377]
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/AciqRoe.png)
</details><br/>

Are they "thumb down" icons for whitelist and user filter in content blocking?

**Comment by ameshkov** [comment]
Using thumb down for the user filter also seems strange.

**Comment by lancelot-moon** [comment]
Yes, I mean they should be "thumb up" or other icons.

Thanks.

**Comment by nkartyshov** [comment]
Fixed
