### ISSUE TITLE
Enable custom filter after adding

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2378]
### Steps to reproduce

1. go to Settings - Content blocking - Filters - Custom filters
2. tap on "plus"
3. paste here https://filters.adtidy.org/extension/chromium/filters/2.txt
4. tap "Import" button

Maybe we should enable the filter and restart protection right away? 

Actual behavior: the filter is disabled, so a user needs to enable it manually and protection isn't restarting which is definitely a bug.

**Comment by nkartyshov** [comment]
done

Test instruction:
1. Install AdGuard
2. Go to custom filter screen
3. Add a custom filter

Expected result:
Custom filter should be enabled
