### ISSUE TITLE
Only .txt file can be imported in Custom filter

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2381]

**Comment by nkartyshov** [comment]
Fixed

Test instruction:
1. Install AdGuard
2. Go to Custom filter screen
3. Add filter from url http://www.ovh.net/files/1Mb.dat

Expected result
Should be importing error

**Comment by aspasskaya** [comment]
Can be imported in Custom Filters/ User Filter sections -> .json and html files:
![image](https://user-images.githubusercontent.com/43952607/51736629-95fe4700-209b-11e9-8269-acd900a3ebfc.png)

**Comment by ameshkov** [comment]
I suppose we shouldn't do additional checks with files imported from the device itself.

Also, there must be another task (or feature request) about proper filters validation and content type detection
