### ISSUE TITLE
Filters labels' issues

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2386]
@ameshkov 
@aalpatkina 

1. A wrong description for Bulgarian (bg) label.
(Wrongly use the description of Indonesian language-specific ad blocking)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/GORSruq.png)
</details><br/>

2. Lack the descriptions for Bulgarian on onesky.
You need to add the below 2 **new** phrases on onesky.
**Bulgarian language-specific ad blocking**
**Designed specifically to block ads on web pages in the Bulgarian language**
And use them for **Bulgarian list** filter. [Bulgarian (bg) label]

3. Lack the label for **ABPindo** filter and need to use the correct description (Indonesian language-specific ad blocking).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/p6IbbeP.png)
</details><br/>

4. Lack the "**ru**" label for **RU AdList: Counters** filter and **RU AdList: BitBlock** filter.

**Comment by ameshkov** [comment]
Labels are loaded from the server periodically (rarely) from here: http://filters.adtidy.org/android/filters_i18n.json

We will update them eventually, but that's not a part of Android app.

Anyways, it needs to be taken care of @aalpatkina

**Comment by ameshkov** [comment]
@aalpatkina plz close this issue once it's resolved on oneskyapp

**Comment by ameshkov** [comment]
Regarding points 3 and 4, it needs to be resolved in https://github.com/AdguardTeam/FiltersRegistry

@Alex-302 plz assist

**Comment by aalpatkina** [comment]
resolved on Onesky platform

**Comment by lancelot-moon** [comment]
@ameshkov
Yes, you had fixed the point 2, 3 and 4.
But the point 1 and ABPindo's issue (no description when clicking its tag) aren't fixed in AG v3.0.145η.

**Comment by ameshkov** [comment]
@lancelot-moon we have not yet synced Android version with the server side. We will do it in one of the future versions
