### ISSUE TITLE
Custom filters have no title and description

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2387]
@nkartyshov let's discuss what we should do before you start fixing it.

**Comment by lancelot-moon** [comment]
I had suggested before...
https://github.com/AdguardTeam/AdguardForAndroid/issues/2315

**Comment by nkartyshov** [comment]
done

Test instruction:
1. Add a custom filter

Expected result:
Should be appear the dialog for a filter title change after the importing a filter
