### ISSUE TITLE
[Feature request] Block all connections that were not allowed.

### ISSUE THREAD

**Issue by Hashira-ira** [AdguardTeam/AdguardForAndroid#2388]
Решила предложить функцию блокировать весь трафик кроме разрешённого.
I decided to offer a function to block all traffic except allowed traffic.

<details>
  <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/45854754/49952237-276f8a80-ff2e-11e8-9ad3-e0ed49f6a5e6.jpg" >
</details>

В разделе настройки приложений при выборе приложения.
In section Apps Management when selecting an application.

<details>
  <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/45854754/49952339-571e9280-ff2e-11e8-81e4-e643a8a5dec8.jpg" >
</details>

Функциональность брандмауэра остаётся нетронутым.
The functionality of the firewall remains as before.

<details>
  <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/45854754/49952623-e166f680-ff2e-11e8-87bf-662fb2b3dd5e.jpg" >
</details>

Пример выключенная функция [Блокировать трафик]
An example of a disabled function [Block traffic]

<details>
  <summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/45854754/49952671-fba0d480-ff2e-11e8-9018-65bd60a99403.jpg" >
<img src="https://user-images.githubusercontent.com/45854754/49953088-ea0bfc80-ff2f-11e8-9e73-05f4dad4cda4.jpg" >
</details>

Включена функция [Блокировать трафик]
The [Block traffic] feature is enabled.

P.S. Названия функции и описания продуманно только для примера.
P.S. The function names and descriptions are only for the example.

**Comment by Hashira-ira** [comment]
> Решила предложить функцию блокировать весь трафик кроме разрешённого.
> I decided to offer a function to block all traffic except allowed traffic.
> 
> В разделе настройки приложений при выборе приложения.
> In section Apps Management when selecting an application.
> 
> ![screenshot_20181208-023442](https://user-images.githubusercontent.com/45854754/49952237-276f8a80-ff2e-11e8-9ad3-e0ed49f6a5e6.jpg)
> 
> Функциональность брандмауэра остаётся нетронутым.
> The functionality of the firewall remains as before.
> 
> ![screenshot_20181213-210032](https://user-images.githubusercontent.com/45854754/49952339-571e9280-ff2e-11e8-81e4-e643a8a5dec8.jpg)
> 
> Пример выключенная функция [Блокировать трафик]
> An example of a disabled function [Block traffic]
> 
> ![screenshot_20181209-032334](https://user-images.githubusercontent.com/45854754/49952623-e166f680-ff2e-11e8-87bf-662fb2b3dd5e.jpg)
> 
> Включена функция [Блокировать трафик]
> The [Block traffic] feature is enabled.
> 
> ![screenshot_20181209-031621](https://user-images.githubusercontent.com/45854754/49952671-fba0d480-ff2e-11e8-9018-65bd60a99403.jpg)
> ![screenshot_20181209-031644](https://user-images.githubusercontent.com/45854754/49953088-ea0bfc80-ff2f-11e8-9e73-05f4dad4cda4.jpg)
> 
> P.S. Названия функции и описания продуманно только для примера.
> P.S. The function names and descriptions are only for the example.

**Comment by Hashira-ira** [comment]
> Решила предложить функцию блокировать весь трафик кроме разрешённого.
> I decided to offer a function to block all traffic except allowed traffic.
> 
> В разделе настройки приложений при выборе приложения.
> In section Apps Management when selecting an application.
> 
> ![screenshot_20181208-023442](https://user-images.githubusercontent.com/45854754/49952237-276f8a80-ff2e-11e8-9ad3-e0ed49f6a5e6.jpg)
> 
> Функциональность брандмауэра остаётся нетронутым.
> The functionality of the firewall remains as before.
> 
> ![screenshot_20181213-210032](https://user-images.githubusercontent.com/45854754/49952339-571e9280-ff2e-11e8-81e4-e643a8a5dec8.jpg)
> 
> Пример выключенная функция [Блокировать трафик]
> An example of a disabled function [Block traffic]
> 
> ![screenshot_20181209-032334](https://user-images.githubusercontent.com/45854754/49952623-e166f680-ff2e-11e8-87bf-662fb2b3dd5e.jpg)
> 
> Включена функция [Блокировать трафик]
> The [Block traffic] feature is enabled.
> 
> ![screenshot_20181209-031621](https://user-images.githubusercontent.com/45854754/49952671-fba0d480-ff2e-11e8-9018-65bd60a99403.jpg)
> ![screenshot_20181209-031644](https://user-images.githubusercontent.com/45854754/49953088-ea0bfc80-ff2f-11e8-9e73-05f4dad4cda4.jpg)
> 
> P.S. Названия функции и описания продуманно только для примера.
> P.S. The function names and descriptions are only for the example.

**Comment by zzebrum** [comment]
@Hashira-ira what is the purpose of this feature?

**Comment by Hashira-ira** [comment]
> @Hashira-ira what is the purpose of this feature?
Sorry, I am not sure I can say this all in English. 
Например, мне нужна блокировать весь трафик у приложения менеджер паролей, кроме резервного копирования на облачный сервис, на который приходит шифрованный файл, это может быть и записная книжка с шифрованием и другие приложение где мне нужно заблокировать весь трафик кроме определённого.

**Comment by Hashira-ira** [comment]
@zzebrum
Sorry, I am not sure I can say this all in English. 
Например, мне нужна блокировать весь трафик у приложения кроме определённого, которые можно задавать напрямую правилами или занося запросы в список доверенных в журнале фильтрации.

**Comment by Hashira-ira** [comment]
@zzebrum
Sorry, I am not sure I can say this all in English. 
Например, мне нужна блокировать весь трафик у приложения кроме определённого, которые можно задавать напрямую правилами или занося запросы в список доверенных в журнале фильтрации.

**Comment by zzebrum** [comment]
@Hashira-ira одно неверно заблокированное соединение и у вас нарушится работа приложения. Блокируйте правилами, все что хотите заблокировать.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
