### ISSUE TITLE
Black theme changed too dark theme

### ISSUE THREAD

**Issue by zombosses** [AdguardTeam/AdguardForAndroid#2390]
Hi,

I'm a OnePlus 6 user. The phone has an AMOLED display panel. Which means pixels get turned off whenever the pixel is black, in this case when the theme is black, which helps save battery and give a darker black.

The initial 3.0 (nightly) release had a black theme but in a recent update it was changed to dark.

Can you bring the black theme back and keep the dark theme as well. (like an OLED only option) 

Old black theme: https://i.imgur.com/Kg0W6cG.jpg
New dark theme: https://i.imgur.com/PaTTsYb.jpg

**Comment by zzebrum** [comment]
UI theme for battery saving is not the main purpose for the app working in the background. It's just new dark theme UI looks more friendly.
