### ISSUE TITLE
DNS requests blocking does not work in the latest nightly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2391]
Despite I have it enabled, nothing is blocked on the DNS-level. It looks as if the SDN filter comes empty.

**Comment by patrickdrd** [comment]
it does work for me, for user filter and simplified domains filter

**Comment by ameshkov** [comment]
It started working for me too, but only after checking filters updates.

@admitrevskiy we should schedule a filters update check after this feature is enabled for the first time.

**Comment by admitrevskiy** [comment]
Resolved. 

Testing instructions for QA:
-Reinstall AG
-Clear data for app
-Enable DNS and DNS request blocking

Expected result:
-SDN filter should be updated
