### ISSUE TITLE
AG Allows Duplicate User Filter Rule to be Added

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2393]
Hi,

I have observed a bug in the latest nightly (3.0.137) & possibly other versions of AG. When you try to add exactly the same filter rule to the 'User Filter' twice, AG does not prompt that an exact same rule is already saved and continues to add & save the rule.

**Test Condition**: From the 'Filtering Log', click on 'Block' and try adding any rule. Later, try adding the exact same rule and it also gets added.

**Expected Behaviour**: AG is supposed to show a toast message that this rule already exists.

Please also check this behaviour in other versions (AG for Chrome/Windows/etc. and fix if necessary).

Thanks!

**Comment by ameshkov** [comment]
Tbh, it looks more like a feature request:)

Currently, AG just ignores duplicates.

**Comment by Nzzyme** [comment]
On a similar note, after adding a custom user filter rule from the Filtering Log (by clicking on the "Block" button), the button should immediately change from 'Block' to 'Unblock'.

Steps:

1. Open Filtering Log and tap on a particular list item which is not blocked.
2. Tap on 'Block' and then select the desired options and tap on 'Add Rule'.
3. It takes us back to the 'Log Details' page and now we still see 'Block' instead of 'Unblock'.

Thanks!

**Comment by artemiv4nov** [comment]
There is no possibility to add a duplicated user rule manually since v4.0 version, I'll close the task.
