### ISSUE TITLE
[Feature Request] Add 'Whois' of IP Address on the 'Log Details' Page

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2394]
Hi,

I was wondering if it is possible to include a tiny 'i' icon besides the 'Copy' icon next to the IP address of a Log entry on the 'Log Details' page so that when we tap that, the whois of the IP address should be shown in another webview window just like a window opens when you tap 'Support' > 'FAQ'. It can query from any popular whois service and can display a toast message if the internet is not connected.

I often find the need to know details of the IP address (Company, Country, etc.) and currently one has to copy the IP address, open a whois webpage in the browser and then check the details. It would be good if this feature is added. I don't think this should be difficult to add.

Thanks!

**Comment by ameshkov** [comment]
This feature request is actually wider than just the Android version. I'll merge it here: https://github.com/AdguardTeam/CoreLibs/issues/652
