### ISSUE TITLE
When you change the app theme (enable or disable the Dark Theme), it clears the Filtering Log

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#2395]
### Steps to reproduce

1. Filtering Log > wait until you see some entries
2. Settings > General > enable / disable Dark Theme
3. Protection is restarted
4. All entries from the Filtering Log are deleted

### Expected behavior

Entries in the Filtering Log should NOT be deleted

### Actual behavior

When you change the app theme (enable or disable the Dark Theme), it clears the Filtering Log

### Customer ID 
1146569 Premium

### Your environment

* Adguard version: v3.0.137n
* Adguard filtering mode: VPN auto
* Device model: Google Pixel 2XL (also Lenovo tablet TB2-X30F)
* Operating system and version: stock Android 9 (also 6.0.1)
* Rooted or not? Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by zzebrum** [comment]
Not a bug, a log is getting cleared when the app is restarted.
