### ISSUE TITLE
[Android] Netflix conflicts with proxy mode

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2397]
If root or outbound proxy enabled Netflix stops playing video.

### Steps to reproduce

1. Start AdGuard, turn on auto proxy/outbound
2. Open Netflix and try to start any video

### Expected behavior

Video should be available
### Actual behavior

![img](https://uploads.adguard.com/TheHasagiw6ahf.png)

### Your environment

* Adguard version: 3.0.137n (1.2.150cl)
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version 9

**Comment by vinpremkumar** [comment]
Using the recommendation from A1904's reply from https://forum.adguard.com/index.php?threads/nordvpn-and-adguard.29129/post-174787.
In fact, all that is need is to find a SOCKS5 server, use that server as the domain in AdGuard's proxy setting (No need to enable TCP in NordVPN app). Finally, change Filtering method from Local VPN to Local Proxy manual mode and change it to the proxy port that you use for your VPN (1080 for NordVPN). This should be enough to make Netflix work without blocking the proxy.
