### ISSUE TITLE
Add Google Pay to the list of default exclusions

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2399]
Please add com.google.android.apps.walletnfcrel package name (Google Pay) to the list of exceptions for filtered applications.

**Comment by DmitriyVelichko** [comment]
Да, отключение фильтрации 3 приложений влияет на результат. Xiaomi services
framework, Google play market и Google pay. Если выключить только Google
pay, я заметил лаги во время оплаты, он может 3 раза с ошибкой провести
платеж и на 4 нормально соединиться и оплатить. Я во время платежа сразу
посмотрел в логи к каким приложениям обращается Adguard и там высветилось
xiaomi services framework и google play market.

**Comment by DmitriyVelichko** [comment]
Скажите а вы можете поправить так же
приложение App Vault, или оно называется панель виджетов. Реклама все равно
появляется там.

**Comment by Alex-302** [comment]
@DmitriyVelichko если пропущена реклама, то нужно создать отчёт из приложения. Здесь неподходящий репозиторий.
