### ISSUE TITLE
Critical error [Deadlock]

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#24]
Often an error message appears: "Adguard was restarted due to a critical error"

https://www.dropbox.com/s/lgpdi1ns9o3hm9q/logs_UTK-661-32785.txt?dl=0 - logs
https://www.dropbox.com/s/325wrerzdvi454h/logs_%28FML-746-60698%29.txt?dl=0 - more logs with similar problem

UTK-661-32785
FML-746-60698

**Comment by ameshkov** [comment]
Here it is:

    Thread:	621	Timer-2	BLOCKED
    135 java.nio.DatagramChannelImpl.isConnected(DatagramChannelImpl.java:135)
    -1 com.adguard.android.filtering.vpn.VpnUdpConnection.isServerSocketOpen(Unknown Source)
    -1 com.adguard.android.filtering.vpn.VpnProxyService.shouldCleanUp(Unknown Source)
    -1 com.adguard.android.filtering.vpn.VpnProxyService.cleanUpUdpConnections(Unknown Source)
    -1 com.adguard.android.filtering.vpn.VpnProxyService.cleanUpConnections(Unknown Source)
    -1 com.adguard.android.filtering.vpn.VpnProxyService.access$100(Unknown Source)
    -1 com.adguard.android.filtering.vpn.VpnProxyService$1.run(Unknown Source)
    284 java.util.Timer$TimerImpl.run(Timer.java:284)

@vbagirov how often does this happen?

**Comment by vbagirov** [comment]
@ameshkov not too often, but this case is not the only one. I added more logs from different user in the desccription.

**Comment by ameshkov** [comment]
Second log is similar.

@Revertron we should remove this method call on UDP connection cleanup.

**Comment by Revertron** [comment]
Fixed this stuff.

**Comment by ameshkov** [comment]
Reappears in .156?

**Comment by Revertron** [comment]
A new log shows that the connection of UDP socket was causing a deadlock in some cases. Fixed that too.
