### ISSUE TITLE
Change Mb to MB in firewall data statistics

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#240]
![image](https://cloud.githubusercontent.com/assets/15856304/11918228/f2bff35e-a730-11e5-9a95-8e2d92127904.png)

"Is the number shown for bandwidth saved in Megabits (Mb) or Megabytes (MB)? If the latter would it be possible to change the Mb to MB so that it is correct. Thanks, Arthur"

NQL-943-23596

**Comment by ameshkov** [comment]
Done
