### ISSUE TITLE
Filtering rules limitations (custom filter, user filter)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2401]
@ameshkov commented on [Tue Dec 18 2018](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1196)

1. Custom filters must not support powerful modifiers ($replace and JS) unless they are explicitly enabled by the user filter (there should be a "Trusted" checkbox in the custom filter dialog)
2. Change the CSS rules validation process and discard those with `url` in the style text

`[ ] Trusted filter`
`Filters marked as trusted can use powerful filtering rules modifiers which can be dangerous in the wrong hands. Do not check this box unless you fully trust it.`

Pre-installed filters are marked as trusted by default (as we perform validation on the server-side).

**Comment by ameshkov** [comment]
Additionally:
1. You need to show "trusted" value on the filter details screen
2. Add an option to remove a custom filter on its details screen

**Comment by TPS** [comment]
It may be useful to flag _only_ filter(list)s that have rules (filters) disabled unless this Trusted flag ia checked.…  Meaning, this could be true per _update_ of these lists, if such unsafe rules are added/removed during such.
