### ISSUE TITLE
Toast notification in HTTPS filtering appears when the https filtering option is enabled

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2404]
### Steps to reproduce

1. Clean install AG
2. go to Settings - Network - HTTPS filtering and enable HTTPS filtering there
3. tap on Whitelist

### Expected behavior
https whitelist opens

### Actual behavior
Toast notification will appear even if the https filtering function is already enabled

**Comment by nkartyshov** [comment]
Fixed
