### ISSUE TITLE
Suggestion: Android Manual Local Proxy Mode Possible with Mobile Data

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#2406]
Hi,

As the title suggests, I've just found out that for non-rooted Android, manually configuring proxy for mobile data access is actually possible by inputting proxy and port entries of Access Point Names in Android settings. It's so simple. This is huge because we can then use Adguard proxy mode comfortably with a VPN. I don't understand why not just Adguard itself but also all the internet says (wrongly) that proxy with mobile data is not feasible !?

You need to advertise this option because it's so easy to configure and the application is awesome, please. Thanks.

Android 6.0.1

Edit: Btw, it's like never before that my phone ever feels cool like now. It was always somewhat warm even when lying idle. I guess I know the culprit ;-)

**Comment by snhv** [comment]
> For **local** HTTP proxy and mobile data, you need root access for automatic proxy configuration.
No, for local proxy, manual proxy configuration is possible (and easy), for both data and mobile connections. Please read my post again, and try out. My post is for mobile connection; for wifi, the guide is all over the internet.

There is one caveat though, that is if your phone is locked with your carrier then the carrier may lock editing or adding APN (Access Point Names).

**Comment by lancelot-moon** [comment]
Via APN, your method is available for mobile data with AdGuard enabled.
Manually set 127.0.0.1:8080 in APN.
But the filtering quality under local HTTP manual proxy configuration is bad.
By the way, if disabling AdGuard, need to remove proxy from APN for internet, which is inconvenient.

Without root access, it can't force all apps' traffic through AdGuard.

Or it seems that some advanced adblock rule syntax aren't supported under local HTTP manual proxy configuration.
Ads will appear.

**Comment by lancelot-moon** [comment]
AdGuard's DNS module also can't work with local HTTP manual proxy configuration.

**Comment by snhv** [comment]
> But the filtering quality under local HTTP manual proxy configuration is bad.

I don't think it greatly deteriorates the quality to point of "bad". I guess it depends on taste. As long as ads in browsers and apps are gone, it's acceptable to me. And I even switch to Simplified filtering method. 

> By the way, if disabling AdGuard, need to remove proxy from APN for internet, which is inconvenient.

Well, only when you uninstall Adguard, not that you do that oftenly.

> Without root access, it can't force all apps' traffic through AdGuard.

Technically yes. I only know DNS traffic won't go through Adguard, and Adguard's DNS setting will be disabled. But besides that, what else?

All in all, this is only optional for advanced users. And for me, it's totally worth a few seconds to configure. The saving in phone performance is noticeable to me. RAM down, heat down, so should longer battery. I'm not saying this is preferable or default to all users, but at least Adguard should make this known.

**Comment by lancelot-moon** [comment]
Under local HTTP manual proxy configuration, the adblock quality is surely bad.

Ads on browsers or in apps appear!
You should try more websites and apps.

**Comment by snhv** [comment]
> It means no DNS filtering.

Not important really, DNS filtering utilizes Simplified Domain list. You can enable that list and the effect will be the same. But even that list is not important too, because it's a smash up of different lists which you already enable separately.

**Comment by snhv** [comment]
> Under local HTTP manual proxy configuration, the adblock quality is surely bad.
> 
> Ads on browsers or in apps appear!
> You should try more websites and apps.

That's weird, really, but ok will do. By the way, just to be sure so pls don't take this the wrong way, if you're connecting to wifi, you need to set up proxy for each wifi too; APN is only for mobile connection.

**Comment by lancelot-moon** [comment]
You don't understand what I say.
Since not all of apps' traffic is through AdGuard under manual proxy configuration, the adblock quality is bad even if enabling AdGuard SDN filter.

Try AppSales app and more apps or websites.
https://play.google.com/store/apps/details?id=net.tsapps.appsales

Ads appear everywhere.

**Comment by lancelot-moon** [comment]
@ameshkov

I think you can mention APN with manual proxy configuration for mobile data in AdGuard's FAQ.

**Comment by snhv** [comment]
> Try AppSales app and more apps or websites.
> https://play.google.com/store/apps/details?id=net.tsapps.appsales
> 
> Ads appear everywhere.

Uhm, not for me.
![image](https://user-images.githubusercontent.com/22385284/50324348-fa643e80-0510-11e9-8001-7e38f8d2df5a.png)

> Since not all of apps' traffic is through AdGuard under manual proxy configuration, the adblock quality is bad even if enabling AdGuard SDN filter.

Uhm, you know technically it won't be much different...
https://kb.adguard.com/en/android/faq#then-the-proxy-mode-is-bad

Again, my point to Adguard is that it should make this configuration known and let users choose.

**Comment by lancelot-moon** [comment]
You use Wi-Fi in your screenshot.
Maybe your router does URL filtering or DNS filtering for your mobile devices.
Or you use DNS with adblock such like AdGuard DNS .

See ads.
https://imgur.com/a/UVRrVY8

You should use cellular network.

**Comment by snhv** [comment]
> You use Wi-Fi in your screenshot.
> Maybe your router does URL filtering or DNS filtering for your mobile devices.
> Or you use DNS with adblock such like AdGuard DNS .
> 
> See ads.
> https://imgur.com/a/UVRrVY8
> 
> You should use cellular network.

Yup I used my company wifi which does malware filtering, by squidblacklist malware list, only. No other url or dns filtering.

So I cleared cache with CCleaner, switched to cellular, and here it is.
![image](https://user-images.githubusercontent.com/22385284/50324760-752e5900-0513-11e9-8e6d-eb7b5e1f65b0.png)

I have Base, Mobile, Spyware, Social, Annoyances, and ABPVN (for Vietnamese) lists enabled. Could it be that yours is a case of missed ads for Chinese adserver?

**Comment by lancelot-moon** [comment]
No, under AdGuard's local VPN mode, ads in AppSales app are blocked.

Eh, you use Android v6, which is maybe the point.
Above Android v7, most apps don't trust AdGuard certificate, and AdGuard doesn't do HTTPS filtering for them by default.

**Comment by lancelot-moon** [comment]
> Since not all of apps' traffic is through AdGuard under manual proxy configuration, the adblock quality is bad even if enabling AdGuard SDN filter.

I told that I had enabled it.
SDN filter = Simplified Domain Names filter.

Nothing helps.

**Comment by snhv** [comment]
> Try the app with ads.
> https://play.google.com/store/apps/details?id=com.iudesk.android.photo.editor

Here it is:
![image](https://user-images.githubusercontent.com/22385284/50326654-14584e00-051e-11e9-8423-7da852c5096b.png)

**Comment by lancelot-moon** [comment]
For your reference:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1746#issuecomment-370482075

We use different Android version.
Maybe you can try if you have devices with Android v7 or above.

**Comment by snhv** [comment]
> Yes, but it's only for local HTTP **automatic** proxy configuration, not including manual proxy configuration.

Thanks. Adguard should clarify in its KB.

> Maybe you can try if you have devices with Android v7 or above.

OK, will see if my wife's android is 7+.

**Comment by lancelot-moon** [comment]
It also has a shortcoming.
With manual proxy configuration, the apps which have no ad will lose internet if I don't route them through AdGuard.

**Comment by ameshkov** [comment]
Guys, I just don't want promote manual proxy mode because of its limitations.

1. Some apps simply ignore network's proxy settings and bypass it.
2. Not every cellular provider let you change the APN settings that way.
3. Manual proxy mode will be severely limited in the next Android version due to this https://github.com/AdguardTeam/CoreLibs/issues/661
