### ISSUE TITLE
Suggestion: Suppress Android Blinking of Disconnected Outbound Proxy's Permanent Notification

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#2407]
Hi,

As the title suggests, in Android, when I enable 'Show notification icon' for outbound proxy and turn on outbound proxy, then disconnect outbound proxy from notification bar, the notification icon stays on. And then when screen if off, the phone blinks which is quite annoying where there's really nothing to be concerned about. Can we suppress this blinking please?

Also, when outbound proxy is disconnected, we can just wipe off the notification. Can we make it really permanent (like the main Adguard process) so that we can conveniently turn on/off from notification bar? Thanks.

Android 6.0.1

**Comment by ameshkov** [comment]
> And then when screen if off, the phone blinks which is quite annoying where there's really nothing to be concerned about.

I guess this issue is specific to your device, Android should not behave like that.
@nkartyshov any idea? what if we make this notification's priority lower?
