### ISSUE TITLE
Navigation header is transparent for taps

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2408]
For example, open filtering log, open sidebar and tap on AdGuard's icon.

#### Screenshot:

![img](https://uploads.adguard.com/TheHasagimc4pv.png)

AdGuard version - 3.0

**Comment by admitrevskiy** [comment]
Resolved.

Steps to reproduce:
-Whole header zone (see attachment) is transparent for taps. It means that tap on this zone leads to tap on element under it.

Testing instructions
-Reinstall AG
-Try to reproduce.

Expected result:
-Nothing happens after tap on the header.

![2018-12-21 17 31 02](https://user-images.githubusercontent.com/32459082/50347640-4f22ac00-0547-11e9-92d6-1d23d4fa2648.png)
