### ISSUE TITLE
Show Log Data of an App in 'Apps Management'

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2412]
Currently, tapping on an app in the 'Apps Management' page shows details about that app namely:

1. Total Traffic, data saved
2. Stats (Total requests, Blocked (threats, counters & trackers)
3. Settings, etc..

It would be good if AG allows us to 'tap' on the following 'links':

-**Total Requests** - should take the user to the Filtering log page and show 'all' requests for that app
-**Blocked Ads** - should take user to log page & only show the blocked ads
-**Blocked Threats** - should take user to log page & only show the blocked threats
-**Blocked Counters and Trackers** - should take user to log page & only show the blocked trackers & counters

The point is that AG should show the data for the above categories instead of just displaying the stats. It was mentioned in earlier posts by you that AG has zero/very minimal effect on the memory/battery when the filtering log is on. Therefore, to achieve the above, AG can internally keep tracking the log and show it to the user when we tap on any of the above link in 'Apps Management' for that app. Clearing the regular 'Filtering Log' page should not clear this list which AG has tracked for the apps to show in the Apps Management page. On the Apps Management page of that app, tapping the menu option (Clear statistics) should also clear the internal log tracked for that app.

There can be an option somewhere in settings saying 'Allow AG to track the log' to enable this functionality. Do you think this is a feasible option?

**Comment by Nzzyme** [comment]
Oh, that's sad. Was this recently implemented (filtering log is limited up to 500 latest requests)? Any reason why is this limited to 500 entries?

**Comment by ameshkov** [comment]
@Nzzyme it's completely in-memory so we just want to avoid using RAM.

**Comment by versavius** [comment]
This was what i was asking about under #2923 if we could access what we blocked etc that would be awesome :)

Can we not output the stats to a log file or something? But then how do we prevent eating up the devices hard disk space with a log file that will just get massive ?

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
