### ISSUE TITLE
Custom filters can't update

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdguardForAndroid#2414]
### Steps to reproduce

1. Import any custom filter by URL.
2. Wait for filter update.
3. Click [Home]'s update icon.

### Expected behavior

All filter will update.

### Actual behavior

Some filter update but the custom filters has not to update.

<details><summary>Screenshot:</summary></details>

### Your environment
* Adguard version: `3.0.145η (1.2.150cl)`
* Adguard filtering mode: `VPN`
* Device model: `ASUS Zenfone3 (ZE552KL)`
* Operating system and version: `Android 8.0.0`
* Rooted or not? `No`
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? `No`

**Comment by ameshkov** [comment]
Are you sure the custom filter was modified? It will be only reported as updated if the content was changed.

**Comment by patrickdrd** [comment]
yes, and sometimes they take a bit of time in order to update, 
e.g. gist (github), pastebin, etc,
I mean, it's not adguard's fault

**Comment by lancelot-moon** [comment]
@ameshkov 
I subscribe to Hexxium Creations Threat List.
https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt

But I don't see it's updated in AG v3.0.145η during the period.
Today I try to update, but AG still shows its version is 20181205.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/35L32X8.png)
</details><br/>

So I directly opened its link and found that its now version is 20181220.
I deleted it and re-subscribed to it.
It started to show the correct version.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/21EIF6L.png)
</details><br/>

I am not sure if it's really not updated, or just shows a wrong version of the custom filter.
Or you can try if the bug existed in the previous nightly versions.
But it's surely a bug in AG v3.0.145η at least.

**Comment by nkartyshov** [comment]
The custom filters updates on the latest nightly.

**Comment by bestpika** [comment]
I use short URL to subscription a filter.
This filter still can't update.

**Comment by nkartyshov** [comment]
@bestpika Provide the short url to the filter, please

**Comment by bestpika** [comment]
https://s.iku.pw/addemo
Latest version:
![image](https://user-images.githubusercontent.com/5698157/51188110-45a71c80-1918-11e9-9e8f-e94882c5d728.png)
Version in app:
![image](https://user-images.githubusercontent.com/5698157/51188118-4b046700-1918-11e9-84ec-6d67d77d87d8.png)

**Comment by patrickdrd** [comment]
what's the url you input in adguard?
https://bestpika.github.io/abp/ is a page not a filter url,
did you input:
https://gist.githubusercontent.com/bestpika/5e414a4f60b2a996a6fb31ec592a56b4/raw/hide.txt
or: https://bestpika.github.io/abp/yui.txt?

**Comment by nkartyshov** [comment]
@bestpika I understood, we aren't update metadata for 
the custom filter.

**Comment by bestpika** [comment]
@patrickdrd
- <https://s.iku.pw/addemo>
- <https://bestpika.github.io/abp/demo.txt>

**Comment by lancelot-moon** [comment]
@nkartyshov
https://github.com/AdguardTeam/AdguardForAndroid/issues/2414#issuecomment-449849761

The bug isn't solved in AG v3.0.166η.

> Custom filters are updating fine on the last Nightly.

I supposed you had tested it in the **next** unreleased nightly version...

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1240
Andrey had defined it.
Honestly, your feature of custom filter in some platforms isn't reliable.
> We should either check if filter content was changed OR if the version was changed.
Otherwise, we shoudn't consider the custom filter updated.

**Comment by nkartyshov** [comment]
Fixed

Test instruction:
1. Install AdGuard
2. Add a custom filter
3. Change metadata
4. Update filters

Expected result
The filter metadata should be updates

**Comment by bestpika** [comment]
<https://bestpika.github.io/abp/cf.txt>
`2019.0118.1`

AdGuard said it was updated.
![image](https://user-images.githubusercontent.com/5698157/51360586-320dd880-1b07-11e9-9a07-f686ad0112de.png)
This filter version still old.
![image](https://user-images.githubusercontent.com/5698157/51360606-4520a880-1b07-11e9-8762-12fa4b9a60e6.png)

AdGuard version still `3.0.166η (1.2.150cl)`.
Is this app version update?

**Comment by nkartyshov** [comment]
@bestpika Please, try updating a custom filter on the new nightly version(3.0.180)

**Comment by bestpika** [comment]
@nkartyshov Work fine. Great.
