### ISSUE TITLE
Start using our dnsproxy as an underlying DNS client (+DNS-over-TLS support)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2415]
Instead of bundling with the dnscrypt-proxy binaries, we can start using our own implementation that supports every known protocol.

Here it is:
https://github.com/AdguardTeam/dnsproxy

(see the PR with the mobile build here: `DNS/repos/dnsproxy/pull-requests/2/overview` -- not yet published to github)

Here is what needs to be done:
1. Change the format supported for DNS addresses: https://uploads.adguard.com/up04_z8zfz_AdGuard_Home.png
    Please note, that DNS stamps are supported for DNSCrypt and DoH clients ONLY. We do not support it for DoT so you'll need to explicitly convert it to `tls://`
2. Setting bootstrap DNS is necessary (make it configurable via advanced settings though: `pref.dns.bootstrap`)
3. Setting fallback DNS is also necessary. We should use the system default.
4. Regarding the build process, once we are sure that the mobile build is okay, we should start publishing aar to our archiva and start versioning them.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-Add some DNS servers at the DNS screen.
-Reinstall AG (try to update from latest nightly and from 2.12.247)
-Go to Custom DNS Settings screen.

-Try to add server from KB.

-Examine DNS with different protocol upstreams (regular, DNSCrypt, DoT and DoH)

-Add and choose new invalid DNS server (for example `1.2.3.4`)
-Enable protection

Expected result:
-Internet is still available
