### ISSUE TITLE
Unable to use  NLB Pay Slovenija until VPN is active

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2417]
[APK download link](https://play.google.com/store/apps/details?id=si.nlbpay.slovenija&hl=en_US)

### Customer ID - 2073339

**Comment by ameshkov** [comment]
@TheHasagi does it help to disable AdGuard filtering for this app?

**Comment by TheHasagi** [comment]
Turning off filtering for NLB pay doesn't work.

**Comment by ameshkov** [comment]
I doubt we can do anything with this
