### ISSUE TITLE
I cannot view my router page

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2418]
I can't view my router page

with ag enabled, all I get is some code like 3a4 2 0

with ag paused, the page (192.168.2.1) works (in chrome)

filtering log doesn't show anything relevant

should I whitelist something?

I'm running ag vpn mode with ag dns,
latest nightly on nougat

**Comment by Eugene-Savenko** [comment]
Please try the following rule: `@@192.168.2.1$network `

**Comment by patrickdrd** [comment]
it worked, thanks

**Comment by patrickdrd** [comment]
can I use wildcard(s) in this please?
will this work?

`@@192.168.*.*$network`

**Comment by sfionov** [comment]
you can specify subnets there.
So `@@192.168.2.0/24$network` should work
