### ISSUE TITLE
Opera still working after disabling options "wifi data/cellular data when screens off"

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2419]
Opera/Opera Mini still downloading pages and content after disabling options "wifi data/cellular data when screens off" in app management and when the screen is off

### Steps to reproduce

1. In App management find Opera app and disable options "wifi data when screens off" and "cellular data when screens off"
2. Go to Opera app and choose any news page or some favorites addresses 
3. Lock screen
4. Unlock screen

Webpage is fully downloaded.

### Your environment

* Adguard version: v3.0.157
* Operating system and version  Android 5.1

**Comment by ameshkov** [comment]
This is not an ideal test case, it does not block network access immediately after you turn the screen off.
