### ISSUE TITLE
Fail to update AdGuard (3.0)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2421]
### Steps to reproduce

Open AdGuard and tap to update

### Expected behavior

Updates should be installed as well.

### Actual behavior

Protection disabled and error occurs

### Your environment

* Adguard version: 3.0.157 
* Adguard filtering mode: Proxy (auto)
* Operating system and version: Android 9
* Rooted or not?  - Rooted

**Comment by ameshkov** [comment]
Weird stuff guys:
```
"android.database.sqlite.SQLiteException: no such table: filter_lists (code 1 SQLITE_ERROR): , while compiling: select filter_list_id from filter_lists where enabled = 1
```

**Comment by admitrevskiy** [comment]
Done.

Testing instructions:
-Install v.2.12 AG
-Try to install (upgrade) new v.3.0.xxx version

Expected result:
-Update should be installed without any errors
