### ISSUE TITLE
Protection level indication is not shown when important features aren't working

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2423]
When https filtering is disabled or "block ads in apps" is disabled, we should show it

**Comment by admitrevskiy** [comment]
Done:

Testing instructions:
-Reinstall AG
-Activate premium
-Disable one of the following features: All filters/Https Filtering/Filtering in apps/Phishing & malware protection

Expected result:
-Protection level indication is shown. All items are clickable and redirects to screens with corresponding features.
-If there is no trial/premium license only first two items redirects to feature screens. Other three redirects to promo screen.
