### ISSUE TITLE
Opening on Proxy settings causing a crash

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2425]
Opening Proxy settings causing a crash
### Steps to reproduce

Open AdGuard - Settings - Network - Proxy

### Expected behavior

Proxy settings should be opened as normal
### Actual behavior

Opening proxy settings fail into a crash

### Your environment

* Adguard version: 3.0.165n (1.2.150cl)
* Adguard filtering mode: VPN
* Device model: (e.g. Google Pixel) : Google Pixel
* Operating system and version (e.g. Android 7.1.2) : Android 9

**Comment by ameshkov** [comment]
Resolved in `adguard-android/pull-requests/966`
