### ISSUE TITLE
Protection Restarting Randomly

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2426]
Protection is restarting randomly in the latest nightly (3.0.166) even though there is no change in the network (switch from WiFi to mobile data/network interruption/etc.). I see a toast message randomly stating that "Protection was restarted to apply new settings". Why is AG restarting randomly? Can you implement the functionality such that the protection should be always ON irrespective of any network/any other changes? In this way, we can be sure that all the traffic is passed through AG without any 'leaks'.

Device: Xiaomi Redmi Note 3
Android Version: 6.0.1 MMB29M
MIUI Version: MIUI Global 10.1 [Stable]; 10.1.1.0 (MHOMIFI)

**Comment by patrickdrd** [comment]
maybe it restarts because filters were updated?

**Comment by Yannis1903** [comment]
same issue (Google Pixel 2 XL / Android 9)

**Comment by ameshkov** [comment]
@nkartyshov I am quite sure this is due to your changes

**Comment by Yannis1903** [comment]
Curiously, this didn't happened the last 3 days anymore to me.

**Comment by Nzzyme** [comment]
Happens about 3 to 4 times everyday for me.

**Comment by nkartyshov** [comment]
@Nzzyme I cannot reproduce issue on test device, could you please record AG log?

Here's what needs to be done:
- Settings -> advanced -> logging level -> switch to "record everything"
- Reproduce the issue
- Settings -> advanced -> export logs
- Send the file to devteam at adguard.com

**Comment by nkartyshov** [comment]
I cannot reproduce this issue
@zebrum Please, assist me

**Comment by Nzzyme** [comment]
> @Nzzyme I cannot reproduce issue on test device, could you please record AG log?
> 
> Here's what needs to be done:
> 
> * Settings -> advanced -> logging level -> switch to "record everything"
> * Reproduce the issue
> * Settings -> advanced -> export logs
> * Send the file to devteam at adguard.com

I am on it. Will send you the file once I observe the issue. In the meantime, can you list all the cases when the protection is restarted? (filter update, setting change, etc...)

**Comment by nkartyshov** [comment]
@Nzzyme The protection can be restarting in case of activate premium license, filter updates or enable/disable filter, setting change and if your change dns setting or outbound proxy with the automation tasker(AutomationIt, Tasker, etc).

**Comment by Nzzyme** [comment]
I don't see this happening in the latest nightlies (currently 3.0.205)
