### ISSUE TITLE
Automatically skip ad video after count down is finished for official YouTube app.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2427]
@ameshkov 

I ever read this feature in other article.
Recently, I can't believe that an app has realized it.
After trying, it's valid.
Now it's limit time free.
https://play.google.com/store/apps/details?id=com.agooday.skipadspro

How does it work?
Magic.
Is it safe since it's on Google Play?

Can AG do the same thing for official YouTube app?
Well, a feature request for it.

I found another project on XDA.
But it's old.
Version 1.0.0.0 on 05.06.2016
https://labs.xda-developers.com/store/app/com.cygery.adskip.xda
https://forum.xda-developers.com/android/apps-games/app-cygery-adskip-youtube-xda-exclusive-t3361271

Other article:
https://stopad.io/blog/how-to-stop-youtube-ads

**Comment by TPS** [comment]
Given https://github.com/AdguardTeam/AdguardForAndroid/issues/2994 is all but implemented officially, is _this_ issue still planned?

**Comment by ameshkov** [comment]
Well, this issue is here to see how many upvotes it gets.

So far, not too many.

**Comment by ministr91** [comment]
Да потому что решение не популярное. Вы лишним действия просите совершить и что в итоге? Сделали по-умолчанию 15 секунд перемотку вместо по выбору 5, которое у пеня стоит, а у некоторых больше. Потом ещё нельзя качество поменять.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/5092
