### ISSUE TITLE
ublock annoyances conversion

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2429]
In my opinion there should be a team assigned to monitor ublock annoyances filter (https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt) and import them in adguard filters

ublock team is much more responsive than adguard's ones,
e.g. look at this:
https://forum.adguard.com/index.php?threads/runningnews-gr.30371/#post-175532

I'm waiting for so many days for an answer and 
the rule is included in ublock annoyances just minutes (!) after I opened the issue

I had imported ublock annoyances on my android but almost none works,
because of the different formatting..

I'm looking forward for your actions

**Comment by ameshkov** [comment]
It consists mostly of scriptlet rules which will be supported by AG eventually, there's just no need for a separate issue (we have one in the CoreLibs repo)
