### ISSUE TITLE
Wrong notification with "none" Notification Icon

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#243]
Adguard ver. 2.1.344
<img src="https://cloud.githubusercontent.com/assets/8577547/11936824/624e5e72-a821-11e5-8930-796f44d9d305.png" width="300">

**Comment by gshumihin** [comment]
Icon won't get changed from "default" to "none" even after app restart.

**Comment by ameshkov** [comment]
Fixed
