### ISSUE TITLE
Reset license is not working

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2431]
Reset license is not working (3.0.166).

### Steps to reproduce

Open AdGuard (3.0.166) tap on "Reset license" and nothing will happen.

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagilgj0z.png)

</details>

**Comment by nkartyshov** [comment]
fixed

Test instruction:
1. Install Adguard
2. Activate premium
3. Reset license

Expected result:
License should be reset
