### ISSUE TITLE
Cannon move certificate to the system storage

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2435]
@adguard-bot commented on [Sat Dec 15 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26954)

### Issue URL (Incorrect Blocking)
[https://www.google.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.google.ru)
### Comment
Username: @Kujibka1
> Не работает кнопка в приложении "переместить сертификат в системное хранилище". Лог отправил.
> 
> **User ID**: 2017572
> **Subject**: [PREMIUM] [Adguard for Android] Дефект

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/e10zYFq.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/R2XaYXj.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And Android 7.1.2, resurection remix 5.8.5
AdGuard version: | 3.0.137
Browser: | Chrome
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Base,<br>AdGuard Mobile Ads,<br>EasyList

**Comment by nkartyshov** [comment]
This issue has already fixed in latest version

**Comment by nkartyshov** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2360
