### ISSUE TITLE
Unblocking rule is incorrect for Removed HTML elements

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2436]
### Steps to reproduce

1. go to http://tivix.co/372-belarus-5.html with Base filter enabled
2. open Filtering log, find there removed script
`tivix.cotivix.co,tamilyogi.cc$$script[tag-content="!function(f,u,n,t,o,r,i"][max-length="10000"]`
3. unblock it

### Actual behavior
Unblocking rule is:
`tivix.cotivix.co,tamilyogi.cc$@$script[tag-content="!function(f,u,n,t,o,r,i"][max-length="10000"]`

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions:
-Reinstall AG
-Try to reproduce the issue

Expected result:
-`tivix.cotivix.co$@$script[tag-content="!function(f,u,n,t,o,r,i"][max-length="10000"]`
