### ISSUE TITLE
How to Solve Vpn Detection

### ISSUE THREAD

**Issue by liang-hiwin** [AdguardTeam/AdguardForAndroid#2437]
As long as I run VPN mode filtering, this software restricts my use. I only need to close adguard to use this software, and this software is not proxy software, otherwise you think I run two vpns, but I only run one vpn.
[轻应用_2.0.0.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2759917/_2.0.0.apk.zip)

**Comment by zzebrum** [comment]
@thb007 cannot install the app.

**Comment by thb007** [comment]
> @thb007 cannot install the app.

Please decompress zip and install it

**Comment by zzebrum** [comment]
@thb007 It says the apk failed to install.

**Comment by thb007** [comment]
> @ thb007它说apk无法安装。

I have no problem installing Android 8.1 properly.
正在使用发音
I compressed it again. Please download the test.

[轻应用_2.0.0.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2779304/_2.0.0.zip)

**Comment by TheHasagi** [comment]
This application is patched. Can you provide the link to the app (play store)?

**Comment by thb007** [comment]
> 此应用程序已修补。你能提供一个应用程序链接（游戏商店）吗？

https://www.lanzous.com/i23f58d

**Comment by TheHasagi** [comment]
This apk contains malware. For a solution try to disable filtering for this application (AdGuard - Apps management - <appname>)

![img](https://uploads.adguard.com/TheHasagid817u.png)
