### ISSUE TITLE
Toggle buttons in Low-level settings do not reflect changes

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2438]
> In Nightly Versions 3.0.157 and 3.0.166, in the page of Low-Level Settings, I can't click on the buttons that change options. When I brush the button, it doesn't become green, but it remains grey. However, if I look in the files of logs, in the "state" file, the modifications are correct. So, I always have to control the logs to verify if options are changed.

### Steps to reproduce

1. Install v. 3.0.166
2. Head to low-level settings
3. Try changing low-level settings
4. Check if they have changed by exporting the log and looking into the State file

### Expected behavior

Settings are changed which is reflected in the UI

### Actual behavior

UI does not reflect changes

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/51235657-c85fc400-1978-11e9-909c-04e12ce23d58.png)

</details>

### Customer ID 
2071856

### Your environment

* Adguard version: 3.0.157 and 3.0.166
* Adguard filtering mode: VPN
* Device model: LG Nexus 5
* Operating system and version: 6.0.1
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zzebrum** [comment]
reproduced

**Comment by nkartyshov** [comment]
fixed
