### ISSUE TITLE
Startup after boot

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2444]
when device boots and there is no connection (airplane mode or mobile data and wifi disabled),
adguard should start in paused mode, like what happens when the connection is disabled afterwards,
please check and fix

I'm running AG 3.0.166 with dns (adguard regular), https filtering and VPN mode

**Comment by artemiv4nov** [comment]
@patrickdrd After all we decided to keep at is now.
