### ISSUE TITLE
AdGuard autostart function

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2445]
If AdGuard auto-start function is disabled (protection is on) after device restart it appears to start automatically anyway.

### Steps to reproduce

Disable auto-start function in AdGuard - Settings - General
Restart device and wait 2-3 minutes

### Expected behavior

Adguard won't start automatically
### Actual behavior

Adguard starts automatically as normal

### Your environment

* Adguard version: 2.12.247 - 3.0.66n
* Adguard filtering mode: VPN
* Device model: Google Pixel
* Operating system and version: 9

**Comment by Eugene-Savenko** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2209 related?

**Comment by patrickdrd** [comment]
should be related to [mine](https://github.com/AdguardTeam/AdguardForAndroid/issues/2444)?

**Comment by nkartyshov** [comment]
fixed

Test instruction for QA:
1. Install AdGuard
2. Start protection
3. Go to Settings -> General
4. Uncheck the auto start option

Expected result:
Protection shouldn't be starting after reboot
