### ISSUE TITLE
The chart didn't paint for today and 24h period  in app management

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#2446]
### Steps to reproduce
1. Open App management
2. Select today or 24h period
3. Click on the traffic statictics

### Expected behavior
The chart should be paint or today and 24h period 

### Actual behavior
The chart don't paint for today and 24h period 

<details>
<summary>Screenshot:</summary>
![device-2019-01-21-110446](https://user-images.githubusercontent.com/3413799/51460467-9f6e7300-1d6c-11e9-84d1-eb3ead2cc897.png)

</details>

### Customer ID 
Me

### Your environment
* Adguard version: 3.0.166
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: Huawei 8x
* Operating system and version: 8.1
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by nkartyshov** [comment]
fixed

**Comment by aspasskaya** [comment]
The chart didn't paint for All time
#
![image](https://user-images.githubusercontent.com/43952607/51688999-d2cc2e80-2006-11e9-853a-8550d2ccde51.png)
