### ISSUE TITLE
ConnectionFinder finds wrong connection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2450]
It finds socket bound to the same port we're looking for.

**Comment by ameshkov** [comment]
@nkartyshov I need your help on this: `adguard-android/pull-requests/1004`

**Comment by nkartyshov** [comment]
done

Test instruction for QA:
1. install AdGuard
2. Select Proxy mode(manual or auto)
3. Start protection
4. Serf on internet

Expected result:
The app names should have correctly detected
