### ISSUE TITLE
adguard mobile has stopped Disqus from opening on Rawstory.com on all pages...

### ISSUE THREAD

**Issue by silat** [AdguardTeam/AdguardForAndroid#2452]
### Steps to reproduce

1. Samsung S8 Open Raw Story in Firefox. Click on Disqus banner to make comment
2.Disqus will not open
3. Disable Adguard Mobil Ads Filter in Ublock Origin for Android
4. Disqus opens with Adquard filter disabled

### Expected behavior

Disqus should open. It has previously.

### Actual behavior

Disqus will not open..

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:20465
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel) Samsung S8Plus
* Operating system and version (e.g. Android 7.1.2) Android 8
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Nope

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardFilters #28675](https://github.com/AdguardTeam/AdguardFilters/issues/28675) via [**ZenHub**](https://www.zenhub.com/)
