### ISSUE TITLE
When updated time's words of filters in content blocking is long, it's covered in AG v3.0.180η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2456]
@Revertron
@aalpatkina 

AG v3.0.180η: filters in content blocking
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vyV1hFH.png)
</details><br/>

1. Add v in the front of "%s".
2. Need line break for "updated %s".

Can this be solved on onesky?
#48361633
original phrase:
%s updated %s

new phrase: 
v%s
updated %s

**Comment by zzebrum** [comment]
1. yes
2. I'm not sure. If @AlikhanAliev will approve it - ok then.
