### ISSUE TITLE
Add problematic devices detection and supply a link to the KB article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2458]
This task consists of several parts actually.

1. [ ] First of all, we need to update the KB article: https://kb.adguard.com/en/android/solving-problems/background-work Use the information from https://dontkillmyapp.com/ to make it up-to-date. @aalpatkina please assist with this.
2. [x] Second, detect the problematic devices (those with at least 3 downvotes on dontkillmyapp) and warn user that it might be necessary to do something to keep AdGuard in background. @AlikhanAliev how and when should we show this warning?

**Comment by ameshkov** [comment]
Let's try detecting when this issue happens and then show a notification.

**Comment by nkartyshov** [comment]
done

Test instruction for QA:
1. Start protection
2. Go to Android settings, find AdGuard, "force stop" it.

Expected result:
AdGuard must show notification about problem with battery saving methods

**Comment by roboderpy** [comment]
Seems to work on Xiaomi, but it only display notification *After* you restart Adguard, which could get some users still confused. Consider to make something a bit more noticeable by the end user.

**Comment by ameshkov** [comment]
> Seems to work on Xiaomi, but it only display notification after you restart Adguard, which could get some users still confused. Consider to make something a bit more noticeable by the end user.

Well, that was the idea -- we'd like to detect the issue first and not alarm users until it happens for the first time.
