### ISSUE TITLE
Feature discovery and contextual help

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2459]
When a user visits some settings section for the first time, we might need to explain what it is and what can be done here.

@AlikhanAliev by feature discovery I mean patterns like this one:
https://material.io/archive/guidelines/growth-communications/feature-discovery.html

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/26aca8d2-dc78-4794-b083-ccc9149b918c

**Comment by ameshkov** [comment]
1. [ ] There should be a way to completely disable feature discovery; For instance, when it is shown on the main screen.
2. [ ] Discuss with @TheHasagi where exactly we'd like to have contextual help;
3. [ ] Implement the feature discovery mechanism;

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/1b95428e-7652-479a-8d34-c1f7fc756d4a
@Revertron

**Comment by TheHasagi** [comment]
Confirmed text and translations with @vbagirov https://gist.github.com/TheHasagi/d3f5363467fa79e06e3bdf5584c712b7#file-secret-gist

**Comment by ameshkov** [comment]
@AlikhanAliev please review it in the latest nightly.

We need either a "Next hint" button, or it should close itself on any tap.
