### ISSUE TITLE
Sometimes we are breaking Автовход Wi-Fi в Метро functionality

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#246]
Link: http://4pda.ru/forum/index.php?showtopic=585387&st=460
And now, when we almost have HTTPS-filtration, we are breaking it more.
I suggest adding it to net_exclusions, then its functionality will not be broken.

**Comment by ameshkov** [comment]
Let's fix it in 2.5, patch 2 is almost ready.

**Comment by Revertron** [comment]
Added the better analog - https://play.google.com/store/apps/details?id=pw.thedrhax.mosmetro too.
