### ISSUE TITLE
License status notifications

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2460]
It is super easy to miss any change that happens to the license status (trial/premium/expired/etc) and we should definitely improve the situation with them.

**Comment by nkartyshov** [comment]
done

Test instruction:
1. Install AdGuard
2. Do not activate premium or trial
3. Start protection

Expected result:

After certain days a notification will be displayed:
1. After one day should be the notification about low app efficiency
2. After two days should be the notification about malware protection
3. After five days should be the notification about blocking ads in app
4. After eight days should be the notification about premium features
5. After ten days should be the notification about low protection
