### ISSUE TITLE
Filter status is non-changed

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForAndroid#2461]
### Steps to reproduce

1. Settings > Content Blocking > Filters
2. Choose one of them
3. Turn on/off
4. Go back

### Actual behavior
Switch position changed, but status of filter didn't

<details><summary>Screenshot:</summary>

![photo32154](https://user-images.githubusercontent.com/45171506/51679707-adccc100-1ff0-11e9-8ae6-5152cfcb5987.jpeg)

</details>

### Your environment

* Adguard version: 3.0.180

**Comment by nkartyshov** [comment]
fixed

**Comment by zzebrum** [comment]
1. go to Settings - Content Blocking - Filters - Ad blocking
2. disable all filters, go back, status: Enabled filters: 0/4
3. disable Ad blocking filter group, status: Disabled
4. enable Ad blocking filter group, status: Disabled
5. enter Ad blocking filter group to sure that 2 recommended filters are enabled.

**Comment by nkartyshov** [comment]
Fixed
