### ISSUE TITLE
Show an error notification when exporting logs and system info with empty file name 

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2462]
### Steps to reproduce

1. go to Settings - Advanced
2. tap on Export logs and system info
3. remove a suggested file name
4. tap Save button

### Expected behavior
an error notification

### Actual behavior
Notification: Export to (invalid) finished successfully.

**Comment by zzebrum** [comment]
The issue also exists for settings and user filter export.

**Comment by admitrevskiy** [comment]
Resolved.
Moreover there is file type validation

Testing instructions for QA:
-Reinstall AG
-Try one of the following features: Export logs/settings/user filter with empty file name or wrong file type.

Expected result:
-An error notification appears
