### ISSUE TITLE
The license page does not fit on the screen

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2464]
Only for asus zenfone max pro m

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/51735158-a3b1cd80-2097-11e9-9539-34f2bc1d5670.png)

</details>

**Comment by Alex-302** [comment]
Screen size is 4.6" (1280x720)

**Comment by nkartyshov** [comment]
fixed
