### ISSUE TITLE
Summary text in Low-level settings is truncated

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2467]
Go to Settings → Advanced → Low Level settings.
Some of the translations are not fully finished.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/51743242-17aaa080-20ad-11e9-9031-f9e66e445ca2.png)

![image](https://user-images.githubusercontent.com/41899455/51743261-26915300-20ad-11e9-92ea-c04a732e59ac.png)

![image](https://user-images.githubusercontent.com/41899455/51743305-4a549900-20ad-11e9-85cf-3245db739bb8.png)

</details>

### Your environment

* Adguard version: 3.0.185
* Operating system and version Android 5.1/6

**Comment by admitrevskiy** [comment]
Done.
