### ISSUE TITLE
Search string overlay buttons in User Filter

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2468]
### Steps to reproduce

1. Go to Settings -> Content Blocker -> User filter
2. Paste any info into User filter
3. Tap on a search string

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/51747718-665f3700-20bb-11e9-9acb-2ee5620012b4.png)

</details>

### Your environment

* Adguard version: 3.0.185

* Device model:  Google Pixel/Nexus 6p
* Operating system and version Android 7/9
*

**Comment by nkartyshov** [comment]
fixed

**Comment by karina-archazh** [comment]
@nkartyshov Please check this search strings:
In Settings - Network -HTTPS Filtering three dots button moves to the right:
![slack - adguard software ltd 2019-01-31 12-34-43](https://user-images.githubusercontent.com/41899455/52045055-b5dab280-2554-11e9-9d90-ef833e14ee19.png)

In App Management whole string moves right:
![slack - adguard software ltd 2019-01-31 12-37-05](https://user-images.githubusercontent.com/41899455/52045212-0e11b480-2555-11e9-8e56-809824fd351d.png)

**Comment by nkartyshov** [comment]
This bug will fix in next version
