### ISSUE TITLE
Double stripes dividers in low-level settings

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2469]
1. Go to Settings -> Advanced _> Low Level 
2. Scroll down 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/51749315-1898fd80-20c0-11e9-9ad5-adce205c9bd8.png)

</details>

* Adguard version: 3.0.185
* Device model: Nexus 6p

**Comment by admitrevskiy** [comment]
Done.
