### ISSUE TITLE
Battery saver mode stops Adguard from working

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#247]
Steps to reproduce:
1. Go to "Settings" -> "Battery" -> "Battery saver"
2. Enable it

Result: apps do no have web access anymore.

The problem is that Android in battery saver mode restricts background apps from accessing the internet. But the VPN is still alive, so we get all the packets from the apps, but as Adguard works in background, we also cannot access the internet.

**Solution:** we should react on battery saver mode the same way as we react on the situations when network is not accessible - stop VPN and show "Protection Paused" notification. Then, when battery saver mode is off, we should automatically enable protection back.

**Comment by ameshkov** [comment]
Update on this issue: it can be reproduced only on Andoird 6.0.
On Android 5.X Adguard works ok even in battery saver mode.

**Comment by ameshkov** [comment]
POWER_SAVE_MODE_CHANGED has FLAG_RECEIVER_REGISTERED_ONLY so we should register receiver on app startup.

**Comment by evgeniy-ADG** [comment]
OEJ-110-29055

**Comment by ameshkov** [comment]
Done, will be available in the next beta.
