### ISSUE TITLE
Cloudflare DNS does not work in 3.0.195

### ISSUE THREAD

**Issue by bellemia** [AdguardTeam/AdguardForAndroid#2473]
### Steps to reproduce

1. install adguard 3.0.195
2. setting DNS as cloudflare secure dns (dns over https) with https filtering activation.

### Expected behavior

Everything is fine.

### Actual behavior

all networks are inaccessible. Only dns responses are followed in the filtering log.
The same problem occurs when i reboot
The same problem occurs re-settings after reset.
The same problem occurs re-settings after uninstall-reinstall.
Continuously check for 2 days.
Adguard dns or other dns, no manual dns setting resolves the problem.

There was no problem with 3.0.180 nightly, 2.12.247 with same settings.
so I'm using 2.12.247 Release instead now.

<details><summary>Screenshot:</summary>
I'm sorry, but I'll skip it. I've uninstalled 3.0.195 now.

</details>

### Customer ID 

It is difficult to use diagnostic report because i've already uninstalled and i thought it is not possible to use network. I haven't thought about it that far.

### Your environment

* Adguard version: lollipop 5.0.1 / nougat 7.0
* Adguard filtering mode: VPN / Proxy(manual/auto) VPN, no proxy, no firewalls
* Device model: (e.g. Google Pixel) ellipsis 8 hd / lenovo s8
* Operating system and version (e.g. Android 7.1.2) lollipop 5.0.1 / nougat 7.0
* Rooted or not? no root
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? nothing.

**Comment by ameshkov** [comment]
@bellemia 
> cloudflare secure dns

Do you have this issue with Cloudflare DNS only, right?

We need to take a look at the record-everyting-level log:

1. Go to settings -> advanced
2. Change logging level to "record everything"
3. Reproduce the issue
4. Go to settings -> advanced -> "Export logs and system info"
5. Send the logs archive to `devteam@adguard.com` and post the link to this issue there as well

**Comment by admitrevskiy** [comment]
@bellemia Hi!
Please try this build: https://ncloud.adguard.com/s/XZLqtdfa4mtEokH

**Comment by admitrevskiy** [comment]
@bellemia 
Please try this build: https://uploads.adguard.com/ADgchq0.apk

**Comment by bellemia** [comment]
Sorry I'm late.
My problem (issue with cloudflare dns over https) is resolved in this
version (https://uploads.adguard.com/ADgchq0.apk)
I haven't checked the two previous test versions. thank you.

 adguard_logs_3.0.196_2901_0532.zip
<https://drive.google.com/file/d/1wPrD0n-wSIpTyCzveVX77-wXINPcCmT2/view?usp=drive_web>



2019년 1월 28일 (월) 오후 6:45, admitrevskiy <notifications@github.com>님이 작성:

**Comment by ameshkov** [comment]
@bellemia this is great news! Most likely, it is resolved in the latest nightly update as well then.

**Comment by bellemia** [comment]
I'll try it later. thank you a lot. have a nice day.

2019년 1월 29일 (화) 오전 5:37, Andrey Meshkov <notifications@github.com>님이 작성:
