### ISSUE TITLE
Connection is lost when DoH/DoT is enabled

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2475]
Unable to reach any website while DoH/DoT enabled in server-type (DNS).

### Steps to reproduce

Open AdGuard - Settings - DNS filtering - Choose a custom dns settings - choose any DNS with DoH/DoT - server-type DoH/DoT

### Expected behavior

Everything should be in order
### Actual behavior

Unable to open any website

### Your environment

* Adguard version: 3.0.195n
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version: 6 - 9

**Comment by ameshkov** [comment]
First of all, it uses wrong address for a fallback: `Fallback is [fe80::2a3b:82ff:fe53:e8b1]:53`

**Comment by ameshkov** [comment]
Second, we need a "record-everything" level log

**Comment by ameshkov** [comment]
The root cause: https://github.com/AdguardTeam/CoreLibs/issues/638

**Comment by TheHasagi** [comment]
The logs are provided.

**Comment by admitrevskiy** [comment]
Done.

@TheHasagi Please, let me know if the user has any more problems with DoH/DoT
