### ISSUE TITLE
Add "pref.dns.fallback" to the low-level settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2478]
`A fallback DNS resolver that will be used when the configured server is not available. Empty string means using system default DNS as a fallback.`

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Go to Low-Level settings
-Tap on `pref.dns.fallback`
-Change it
-Enable DNS filtering and choose any custom server
-Start protection

-Export log
-Look for `Fallback is <your_fallback_dns>` record in the log
