### ISSUE TITLE
Side menu is always open after restarting the app

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2479]
### Steps to reproduce

1. Open the app
2. Change the theme or the language to make the app restart.
### Expected behavior
Probably may depend on the situation or just open AG main screen

### Actual behavior
Side menu is open. 

<details><summary>Screenshot:</summary>

![screenshot_2019-01-29-12-14-52](https://user-images.githubusercontent.com/44832195/51897360-a413d680-23bf-11e9-8f2e-49d25655d04b.png)

</details>

**Comment by nkartyshov** [comment]
Fixed
