### ISSUE TITLE
Fix warning notifications in Apps Management

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#2481]
"В режиме прокси функционал брандмауэра ограничен" - появляется каждый раз при выходе из настроек отдельно взятого приложения. Просьба это убрать, хватает одного появления при заходе в меню приложений из главной.
<details><summary>Screenshot:</summary>

![screenshot_2019-01-29-14-52-33-672_com adguard android](https://user-images.githubusercontent.com/33488229/51906803-12fc2a00-23d6-11e9-8734-71e00d9b07eb.png)
</details>
### Your environment
* Adguard version: 3.0.199
* Adguard filtering mode: Proxy
* Xiaomi Redmi Note 4X (Snapdragon)
* Android 7.0
* Root

**Comment by Revertron** [comment]
Done.
