### ISSUE TITLE
Adding AdGuard widget doesn't work correctly

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2484]
## 1. Transparent

Add AdGuard widget by size 3*1 -> transparency 100 % -> ok
#### Expected behavior
The widget should be transparent.
#### Actual behavior
Added black Wiget. If tap on it, it becomes transparent.
## 2. Information should change when resizing
!Also, much excess area in widget. 
- LG phone

![image](https://user-images.githubusercontent.com/43952607/51910352-041a7500-23e0-11e9-83ce-d933b814b9bd.png)
- Nexus 6p phone

![image](https://user-images.githubusercontent.com/43952607/51911258-70967380-23e2-11e9-853f-9bbc41f63664.png)

- Meizu phone

![image](https://user-images.githubusercontent.com/43952607/51910993-bb63bb80-23e1-11e9-9cd4-52d6ca3775e6.png)

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Examine widget resize and transparency
