### ISSUE TITLE
Outmoded filters can't update their descriptions though they are changed at server side.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2486]
ex: Bulgarian list and Anti-Adblock Killer.
The 2 filters have no update for a long time.
After enabling them and checking for updates, no change.

Bulgarian list still wrongly uses Indonesian description.
Anti-Adblock Killer uses anti-adblock.
(It should be adblock circumvention.)

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/ZLfEC02.png)

![image](https://i.imgur.com/aORxTCz.png)
</details><br/>

**Comment by lancelot-moon** [comment]
Another question, can you design to update filters' description without enabling them?

I remember that AG for iOS can be so.
Use a finger to press, swipe down and then release on the screen of filters section.
Filters' description will be updated.

**Comment by nkartyshov** [comment]
Fixed
