### ISSUE TITLE
Tile icon is always grey  

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2488]
Tile icon of AdGuard (see attachments) works properly, but always grey.

<details><summary>Short clip:</summary>

https://uploads.adguard.com/SVID_20190128_205333_1.mp4

</details>

### Your environment

* Adguard version: 3.0.205n
* Adguard filtering mode: VPN 
* Device model: HUAWEI MHA-L09
* Operating system and version: 8

**Comment by zzebrum** [comment]
It is ok on Samsung s9.
