### ISSUE TITLE
Consider having multiple fallback/bootstrap DNS addresses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2490]
The issue one of the users has is that one of the DNS servers provided by the ISP is dead.

We're using the first DNS server found (which is dead) and so `dnsproxy` simply does not work.

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
1)
-Install AG v2.12
-Add and select any invalid custom DNS server (`1.2.3.4` for example)
-Update AG to the latest nightly.
-Go to Low-Level settings - pref.dns.fallback
-Add one valid and one invalid dns servers (`1.2.3.4` and `8.8.8.8` for example)
-Enable protection

Expected result:
-Internet is still available

2)
-Go to Low-Level Settings - pref.dns.bootstrap
-Add one valid and one invalid dns servers (`1.2.3.4` and `8.8.8.8` for example)
-Go to Custom DNS Settings and select any DoH or DoT server
-Enable protection

Expected result:
-Internet is available and you are connected to the selected server
