### ISSUE TITLE
Ad blocking is turning on after language changing

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForAndroid#2491]
### Steps to reproduce

1. Downgrade Protection level to minimum.
2. Change language.

Actually, it's reproducing even if Protection level isn't minimal.

<details><summary>Before language changing:</summary>

![photo_2019-01-30 13 34 26](https://user-images.githubusercontent.com/45171506/51976234-3934cf00-2495-11e9-9ecc-c77aeeebe7af.jpeg), ![photo_2019-01-30 13 44 36](https://user-images.githubusercontent.com/45171506/51976254-45209100-2495-11e9-94a4-d2d1960b1e5c.jpeg)

</details>

<details><summary>After:</summary>

![photo_2019-01-30 13 34 30](https://user-images.githubusercontent.com/45171506/51976426-ad6f7280-2495-11e9-95c3-927210510e9b.jpeg)
![photo_2019-01-30 13 34 32](https://user-images.githubusercontent.com/45171506/51976452-b9f3cb00-2495-11e9-9d91-52bc4b2201d9.jpeg)

</details>

### Your environment

* Adguard version: 3.0.205 / 3.0.199
* Android version: 8.1 / 5.1

**Comment by Revertron** [comment]
Fixed in PR 1159.
