### ISSUE TITLE
Settings backup does not contain backup of app settings

### ISSUE THREAD

**Issue by sebast889** [AdguardTeam/AdguardForAndroid#2492]
Even when importing from settings backup I have to manually reconfigure each apps permissions/internet settings etc. Is it possible to export these settings with a backup so that it is easy to import them back or at least add option to include it in backup?

Also, what other settings are excluded in backups currently?

**Comment by ameshkov** [comment]
Hm, actually the apps mgmt settings must have been exported/imported okay so this must be a bug.

> Also, what other settings are excluded in backups currently?

If anything is excluded, this is a bug that needs to be fixed.

**Comment by sebast889** [comment]
Filter list settings (selected lists, custom filters etc) also weren't imported back with settings. Also noticed my DNS settings changed from system default to using custom (adguard-doh) though I don't know if this bug is related to settings or a new version upgrade.

**Comment by Revertron** [comment]
I think that you are trying to import very old scheme of backup :(

**Comment by sebast889** [comment]
It wasn't an old backup it was one from a few nightly versions ago into the newest one.

**Comment by ameshkov** [comment]
> It wasn't an old backup it was one from a few nightly versions ago into the newest one.

Well, we are trying to maintain compatibility of backups between 2.12 and the latest nightly 3.0, but not between different nightly versions (that'd be too hard).

Anyways, we'd better test it once again (export/import from/to 2.12/3.0) @zzebrum

**Comment by Revertron** [comment]
In 3.0 nightly it is working perfectly.
1. Set some settings for some app.
2. Export settings to SD-card.
3. Reset settings in App Management.
4. Import saved settings.
5. The changes from point 1 are back as they should.
