### ISSUE TITLE
Multi-select apps and change their settings

### ISSUE THREAD

**Issue by sebast889** [AdguardTeam/AdguardForAndroid#2493]
Can there be added a way to multi-select apps and change their settings (wifi, mobile etc.) at once? Currently from new installed phones it is very tedious to do it one by one for the apps I want to change. The currently available setting to change settings for all apps is not very useful for this case so a multi-select option would be much more useful.

**Comment by madasahat** [comment]
Bulk change I can see is an option in app management

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
