### ISSUE TITLE
Empty stealth mode param in filtering log

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2495]
I found such events in filtering log
Stealth mode options enabled: self-destructing first-party cookies.

<details><summary>Screenshot:</summary>

![screenshot_20190130-164424_adguard](https://user-images.githubusercontent.com/44832195/51985445-e49e4d80-24ae-11e9-9b71-4c602244f942.jpg)

</details>

AdGuard 3.0.205n

**Comment by nkartyshov** [comment]
We do not display the status when cookies was blocked

**Comment by ameshkov** [comment]
It will make sense if we somehow identify that cookies associated with this web request were modified by AdGuard

**Comment by nkartyshov** [comment]
fixed

Test instruction:
1. Enable stealth mode
2. Enable Self-destruction of first-party cookies
3. Start protection
4. Open google.com or yandex.ru

Expected result:
Filtering log should have a blocking cookies event
