### ISSUE TITLE
Proxy settings issue

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2496]
If you enable outbound proxy mode and select the server you want then general notification (back to network settings) displays that Proxy is disabled (see the screenshots).

Latest nightly build 3.0.205(1.3.113 CL)

### Steps to reproduce

1. Open AdGuard - Settings - Network - Proxy - Enable - add any proxy HTTP/SOCKS
2. Return back to the network settings

### Actual behavior

<details><summary>Screenshot 1:</summary>

![img](https://uploads.adguard.com/TheHasagihe1u0.png)

</details>

<details><summary>Screenshot 2:</summary>

![img](https://uploads.adguard.com/TheHasagik0gfo.png)

</details>

**Comment by Revertron** [comment]
It seams we've fixed it some time ago.
