### ISSUE TITLE
When selecting a quick install, automatic crash reporting doesn't turns on

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2497]
### Steps to reproduce

1. Install apk file
2. On Installation screen with EULA check that check in crash report checkbox is on
![image](https://user-images.githubusercontent.com/41899455/51993830-aad64280-24c0-11e9-9af1-a30819f20714.png)
3. *Tap on Skip Quick Settings*

### Expected behavior
In Settings -> Advanced Automatic crash reporting switch should be enabled.

### Actual behavior

It's disabled.
<details>

![slack - adguard software ltd 2019-01-30 19-00-27](https://user-images.githubusercontent.com/41899455/51994728-78c5e000-24c2-11e9-9de2-9a7327ce9e81.png)
</details>

**Comment by ameshkov** [comment]
IMPORTANT NOTE: Automatic crash reporting is enabled by default for BETA and NIGHTLY versions only

**Comment by Revertron** [comment]
Done.
