### ISSUE TITLE
AdGuard stops working when changing Stealth mode functions state

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2498]
### Steps to reproduce 

Enabling and disabling stealth mode functions from time to time causes AG incorrect working. 
### Expected behavior

changed setting is applied correctly after protection restart
### Actual behavior

protection is not restarting, no internet connection, "Protection is disabled" status on the main screen but it looks like protection is active in status bar.

<details><summary>Screenshot:</summary>

![20190130_174926](https://user-images.githubusercontent.com/44832195/51989450-2384d100-24b8-11e9-8cd5-219d479c4639.jpg)

</details>

**Comment by zzebrum** [comment]
So, it's not only in Stealth mode settings. It seems that the issue can happen any time when protection restart is needed. Maybe CL bug?

**Comment by ameshkov** [comment]
Yeah, it looks like a CL bug indeed, for some reason it fails to stop protection properly.
