### ISSUE TITLE
Mark "Adguard.com" as html link in about section

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2499]
![image.png](https://images.zenhubusercontent.com/5bbf23f1307bc60241e3ae0e/892cfd9c-d947-487d-b4aa-e1c9d748b3d1)

**Comment by ameshkov** [comment]
Not fully done:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2792

Guys, can we not make people set the link range and somehow set it dynamically?

**Comment by lancelot-moon** [comment]
Maybe modifying the phrase on onesky is simple.
ex:
[link](url)
[AdGuard.com](https://adguard.com)

**Comment by admitrevskiy** [comment]
Done
