### ISSUE TITLE
Google Play Music - "blocked counter" behavior

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#250]
It seems that app starts repeating requests for the tracker with a very-very short period. We should do something with that.

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45577270

**Comment by ameshkov** [comment]
Cannot reproduce this, guess I need the log with blocked requests to see what's not blocked.

**Comment by evgeniy-ADG** [comment]
TICKET ID - тут логи по techmedia. или сделать из него новую задачу?
GGH-607-67841

В некоторых приложениях, таких как play музыка и techmedia при включении фильтрации через прокси, adguard постоянно что-то делает, на счетчике заблокированных баннеров больше 300 тыс, а сэкономленного трафика почти 10ГБ. Приходится включать локальный vpn что не очень удобно, т.к. иногда приходится использовать vpn соединение для доступа в интернет.

**Comment by ameshkov** [comment]
@evgeniy-ADG с play музыкой я вроде разобрался в чем проблема, еще непонятно как оно с починкой.

Все новые приложения с той же проблемой дополняй вот в эту задачу: #511

**Comment by ameshkov** [comment]
В логах кстати опять Play Music, закрываю как дубликат.
