### ISSUE TITLE
Crash: Could not dispatch event FilteringLogEvent

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2500]
See the details here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13984/

And also here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13990/

And here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13744/

**Comment by Revertron** [comment]
All these crashes are going right after such strings in log:
`Cannot find packages for uid 10213`

**Comment by Revertron** [comment]
Fixed.
