### ISSUE TITLE
Crash: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2501]
SettingsGroupActivity:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13163/

AutomationActivity:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13172/

FilteringLogActivity:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13157/

FiltersCategoryActivity:
https://sentry.adguard.com/adg/adguard-android-rs/issues/13247/

**Comment by nkartyshov** [comment]
Fixed 

Test instruction: no need
