### ISSUE TITLE
Crash after importing settings from 2.12

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2503]
### Steps to reproduce

1. Reinstall Adguard 
2. Import these settings (settings from 2.12.250 with non-existing proxy and dns server addresses like 11.22.33.44:8080) :

[adguard_settings_2.12.250_3001_2027.json (1).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2816967/adguard_settings_2.12.250_3001_2027.json.1.zip)

Logs: 
[adguard_logs_3.0.205_3001_2032.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2816969/adguard_logs_3.0.205_3001_2032.zip)

Tested on Pixel (Android 9)

**Comment by admitrevskiy** [comment]
Done.
