### ISSUE TITLE
When entering words in the search of app management, AG for Android v3.0.217η crashed. 

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2507]
Even don't need to enable AG protection. Simply enter words in the search of app management, and it will crash.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8MtI1X5.png)
</details><br/>

**Comment by Nzzyme** [comment]
Duplicate post

**Comment by zzebrum** [comment]
#2508 - fixed already
