### ISSUE TITLE
Old notification text in HTTPS Filtering

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2510]
1. Go to Settings -> Network -> HTTPS Filtering
2. Enable a switch filter Blacklist only
3. Tap on a Whitelist

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/52119242-8d70b800-2629-11e9-9b3d-8a6999e751b9.png)

</details>

For all testing devices

**Comment by nkartyshov** [comment]
Fixed
