### ISSUE TITLE
Filter Blacklist only doesn't work properly

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2511]
1. Open Settings -> Network -> HTTPs filtering
2. Make sure HTTPs filtering is on (disable dns and filters in content blocking)
3. Enable Filter Blacklist only
4. Add lenta.ru and mail.ru into blacklist

### Expected behavior
Mail.ru and Lenta.ru should be filtered
### Actual behavior
There is no blocked request in the filtering log.

**Comment by Revertron** [comment]
May be there are no blocked requests because of this?

> disable dns **and filters**

**Comment by nkartyshov** [comment]
Blacklist working if enable filters
