### ISSUE TITLE
Wrong custom DNS server name for DOH stamps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2514]
### Steps to reproduce

1. Go to DNS -> custom -> add a custom server
2. Add `sdns://AgcAAAAAAAAABzEuMC4wLjGgENk8mGSlIfMGXMOlIlCcKvq7AVgcrZxtjon911-ep0cg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk`
3. Save the server and get back to the list of servers

### Expected behavior
Subtext: `https://dns.cloudflare.com/dns-query`

### Actual behavior
Subtext: `https://https://dns.cloudflare.com/dns-query`

<details><summary>Screenshot:</summary>

https://uploads.adguard.com/up04_9ydhk_Monosnap.png

</details>

### Your environment

* Adguard version: 3.0.217

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Try to reproduce the issue
