### ISSUE TITLE
DNS server list

### ISSUE THREAD

**Issue by blub4747** [AdguardTeam/AdguardForAndroid#2515]
### Expected behavior
I am looking at the DNS servers list in the android app and I would like to know if there is a way to view list of DNS servers without the app.

like in a .csv file.

Thank you, blub4747

**Comment by ameshkov** [comment]
Well, I can simply share the list

**Comment by ameshkov** [comment]
Here you are:
https://uploads.adguard.com/up04_pepb7_main_dns_providers.json

**Comment by blub4747** [comment]
Hi thank you for your reply.
However your given answer only partially solves my problem.
I actually wanted a of all DNS servers with ip addresses.
Guess I have mess on the screen of my Android phone and find some other solution.
Thank you.

**Comment by ameshkov** [comment]
What about this list then?
https://kb.adguard.com/en/general/dns-providers

**Comment by blub4747** [comment]
Thank for this better list.

Is there also somewhere a copy of the regional servers list?

Thx,blub4747
