### ISSUE TITLE
modified in filtering log?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2518]
so what's that modified in filtering log?
please note that stealth mode is disabled in my case,
I also switched it on temporarily and disabled all the options and
disabled it again, I still got modified results in filtering log...

maybe somebody should explain?
I tried contacting on telegram, but there was no-one there to answer,
I search on google, no results either,
maybe there should be documentation for (new) features like this one?

**Comment by patrickdrd** [comment]
that's what I thought, but I told someone on telegram to add the show html filtering option on advanced (pref.removed.html.log) and it didn't show that something was hidden

**Comment by patrickdrd** [comment]
ok, I understood the meaning from @ameshkov,
but can you add an option to show detailed/expanded view for it please?
I don't like it being "black box", I want to be able to see what was filtered

**Comment by ameshkov** [comment]
I guess we should split it into several issues.

This one about cosmetic/JS rules is one of them: https://github.com/AdguardTeam/CoreLibs/issues/729
There might be more, though.
