### ISSUE TITLE
Update resources before the first beta version

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2519]
Filters, resources.

**Comment by lancelot-moon** [comment]
Before releasing beta, may you fix wrong date format in Chinese?
https://github.com/AdguardTeam/AdguardForAndroid/issues/2356

@maximtop had fixed it in browser extension.

Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 
In the recent 2 nightly versions, you didn't update translations but added new English phrases...
Please remember to update translations before releasing beta.

Btw, fixing wrong date format in Chinese should not be difficult.
May you fix it?
Thanks.
