### ISSUE TITLE
custom filter dns blocking (hosts)?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2520]
hello,
can we do dns blocking (hosts) with a custom filter?

last time I tried (with entries such as `||sitetoblock.com^` it wasn't possible, 
the url appeared as blocked on my logs,
but not by dns

however, adguard simplified domains filter's entries (which works in a similar way as a custom filter) 
are blocked by dns

**Comment by lancelot-moon** [comment]
You should know subscription for DNS filtering isn't ready in v3.0...

If enabling DNS filtering, AG uses SDN filter in the background for DNS filtering even if users disable SDN filter in filters.

Anyway, hosts files aren't supported by AG for Android now.

The custom filter in filters is only for HTTPS filtering.

If you want custom list for DNS filtering, enable DNS filtering and import basic adblock rule syntax or domians into the user filter, but the update of custom list for DNS filtering isn't convenient.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/1851
