### ISSUE TITLE
Custom launchers breaks widget's min size

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2521]
Some custom launchers allows to squeeze widget's width less than defined in initialLayout

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-You should test this issue on device with custom launcher (Nova Launcher for example)
-Reinstall AG
-Squeeze widget to 2x1 or 1x1

**Comment by TPS** [comment]
Could this be done better than losing all text @ < 3×2 or so?  Perhaps have such overflow when long & thin?  My layouts often have long thin areas (either dimension) where overflow could work well.
