### ISSUE TITLE
Error with activated SSL filtering

### ISSUE THREAD

**Issue by quthla** [AdguardTeam/AdguardForAndroid#2522]
Very often when browsing https websites with Chrome, it will show `ERR_NETWORK_CHANGED`. As Chrome automatically reloads the page, it will work then after. This also happens in other apps with enabled SSL filtering, but these might crash then or need to be manually reloaded.

It seems like the first request fails then but subsequent requests work. Rarely also gives error `err_ssl_version_interference`

CA is moved to system store with Magisk module.

Related to https://github.com/AdguardTeam/AdguardForAndroid/issues/319?

### Steps to reproduce

1. Download https://play.google.com/store/apps/details?id=de.payback.client.android&hl=de
2. Start the app, it wiill show error but when pulling to refresh, it'll work
3. When restarting the app after, it'll also work but when restarting some longer time after, it'll show the error again
4.

### Expected behavior

Should not show any error.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 3.0.220
* Adguard filtering mode: VPN
* Device model: OnePlus
* Operating system and version 9
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by zzebrum** [comment]
@quthla hello! Please, enable debug logging level, reproduce the issue, notice the exact time when it happened, export log file and send it to devteam[at]adguard[dot]com
the instruction how to do so is [here](https://kb.adguard.com/en/android/solving-problems/log#debug).

**Comment by quthla** [comment]
Is it this you are looking for? It seems to be adding an exception. That would explain why subsequent requests work then.

```
13:57:06.161 [Thread-7] DEBUG com.adguard.android.filtering.a.b - TCP id=5900 resolveConnectionInfo: sessionId=1005764 connectionInfo=de.payback.client.android /172.18.11.218:48070 /45.60.14.82:443 10144 DEFAULT
13:57:06.161 [Thread-7] DEBUG c.a.corelibs.proxy.ProxyServerImpl - New proxy connection /127.0.0.1:41350<->/45.60.14.82:443
13:57:06.161 [Thread-7] DEBUG Native.AGAndroidProxyServer - completeOnNewConnectionWithInfo: Resolved application name: de.payback.client.android
13:57:06.210 [Thread-6] DEBUG Native.AGProxySession - [id=1005764] Set operating mode to DETECTION
13:57:06.262 [Thread-6] DEBUG Native.AGIpReachabilityTester - operator()() Connection to 50.16.243.70:443 succeeded
13:57:06.263 [Thread-6] DEBUG Native.AGIpReachabilityTester - processConnectResult()
13:57:06.263 [Thread-6] DEBUG Native.AGIpReachabilityTester - cacheDestination() ok
13:57:06.263 [Thread-6] DEBUG Native.AGIpReachabilityTester - processConnectResult() ok
13:57:06.268 [tcpip-stack-pool-1-thread-5] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=5901 onTcpConnectRequest: de.payback.client.android /172.18.11.218:46854 /50.16.243.70:443 10144 DEFAULT
13:57:06.269 [tcpip-stack-pool-1-thread-5] DEBUG c.a.android.filtering.commons.g - TCP id=5901 de.payback.client.android /172.18.11.218:46854 /50.16.243.70:443 10144 DEFAULT redirect /50.16.243.70:443 to /127.0.0.1:1101
13:57:06.269 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=5901] complete_tcp_connect_request: redirecting connection
13:57:06.271 [Thread-7] DEBUG c.a.android.filtering.events.i - Creating new stats for de.payback.client.android with id 5901 and network type WIFI
13:57:06.271 [Thread-7] DEBUG com.adguard.android.filtering.a.b - TCP id=5901 resolveConnectionInfo: sessionId=1005765 connectionInfo=de.payback.client.android /172.18.11.218:46854 /50.16.243.70:443 10144 DEFAULT
13:57:06.271 [Thread-7] DEBUG c.a.corelibs.proxy.ProxyServerImpl - New proxy connection /127.0.0.1:41354<->/50.16.243.70:443
13:57:06.271 [Thread-7] DEBUG Native.AGAndroidProxyServer - completeOnNewConnectionWithInfo: Resolved application name: de.payback.client.android
13:57:06.319 [Thread-13] DEBUG Native.PF - verifyCertificateAsync www.payback.de state:0
13:57:06.320 [Thread-14] DEBUG Native.PF - Certificate verification for www.payback.de returned with status 0 ()
13:57:06.338 [VpnService-main] DEBUG Native.AGIpReachabilityTester - cancelCheck()
13:57:06.339 [tcpip-stack-pool-1-thread-5] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=5900 Connection statistic: sent=423, received=1520
13:57:06.339 [VpnService-main] DEBUG Native.AGIpReachabilityTester - cancelCheck() ok
13:57:06.338 [Thread-6] DEBUG Native.AGSslDomainFilter - [id=1005764] TLS connection is not HTTPS, adding 'de.payback.client.android#45.60.14.82:443#www.payback.de' to exceptions
13:57:06.339 [tcpip-stack-pool-1-thread-5] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=5900 onTcpClosed: Connection closed
13:57:06.339 [Thread-6] DEBUG Native.AGProxySession - [id=1005764-ssl] Set operating mode to PASS
13:57:06.339 [Thread-6] DEBUG Native.AGProxySession - [id=1005764-pass-ssl] Can't detect protocol, switching to pass mode
13:57:06.339 [proxy-server-pool-1-thread-6] DEBUG com.adguard.android.filtering.a.b - TCP id=5900 onBeforeRequest: null
13:57:06.339 [Thread-6] DEBUG Native.AGProxySession - [id=1005764-pass-ssl] Set operating mode to PASS
13:57:06.340 [Thread-6] DEBUG Native.AGProxySession - [id=1005764-pass-ssl] Shutting down session (from=431)
13:57:06.340 [Thread-6] DEBUG Native.PF - SSLDataProvider::clearExceptions _www.payback.de
13:57:06.339 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=5900] TCP connection was closed, 43 active connections left
13:57:06.340 [Thread-6] DEBUG Native.AGProxySession - [id=1005764-pass-ssl] Destroying session
13:57:06.340 [proxy-server-pool-1-thread-6] DEBUG com.adguard.android.FilteringLog - TCP id=5900 sess=1005764  0  "www.payback.de" "" de.payback.client.android (10144) 130ms 340 1440```

**Comment by zzebrum** [comment]
@quthla try to add `payback.de` to Settings - Network - HTTPS filtering - whitelist and check if it helps.

**Comment by quthla** [comment]
I guess it'll help but the question is rather why it's being considered not https. It most likely is as it's using port 443

**Comment by zzebrum** [comment]
@quthla that's because of ssl pinning. We may add the domain to https exclusions.

**Comment by anastenko** [comment]
Also reproduced with AdGuard premium version on android 11 (Oppo reno 10x zoom).
Everytime a site is opened the error message states "your connection is interrupted" for a couple of seconds and then the page loads.

Turning the system dns off doesn't help, neither the certificate reinstalling.

Support ticket [#512648](https://adguard.zendesk.com/agent/tickets/512648)

**Comment by artemiv4nov** [comment]
@anastenko Does the HTTPS filtering disabling help? Please check it up.

**Comment by Birbber** [comment]
@artemiv4nov We couldn't reproduce the issue on our end. The ticket was closed, so it wasn't possible to ask the user about it.
