### ISSUE TITLE
Wi-FI calling Vodafone UK

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2523]
I am having pretty much the same issue, only I am on Vodafone UK. 

Like sfdd I am also on Android Pie and an S9+, but using the latest AdGuard nightly build in VPN mode and not rooted. 

I've just sent a support request through the app with logs but don't know Vodafone UK's WiFi calling servers to exclude from pref.ipv4.routes.excluded.

_Originally posted by @Lurchus in https://github.com/AdguardTeam/AdguardForAndroid/issues/2432#issuecomment-460870667_

**Comment by ameshkov** [comment]
Merged to https://github.com/AdguardTeam/AdguardForAndroid/issues/2550
