### ISSUE TITLE
Some rules are applied to wrong type of request

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#2525]
### Steps to reproduce

1. Enable AdGuard Base filter
2. Go to https://www.wp.pl/

### Expected behavior

Rules with `~script` modifier shouldn't be applied to `script` requests, for example this rule:
`||wp.pl^$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,xmlhttprequest,other,~script`

### Actual behavior

It's applied to `script` request.

<details><summary>Screenshot:</summary>

![screenshot_20190206-210741_adguard](https://user-images.githubusercontent.com/29142494/52370710-e7231900-2a53-11e9-97d9-d9ca8756c5ff.jpg)

</details>

### Your environment

* Adguard version: 3.0.229 (1.3.126cl)
* Adguard filtering mode: VPN

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #712](https://github.com/AdguardTeam/CoreLibs/issues/712) via [**ZenHub**](https://www.zenhub.com/)
