### ISSUE TITLE
AG Crashing after installing the latest Nightly [3.0.229]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2527]
Installed the latest nightly (3.0.229) now and it crashed everytime I restarted my phone and switched on either Wi-Fi / Mobile data and opened any webpage in the Firefox app.

The setting "Automatic crash reporting" is turned on so I hope the logs have reached you.

Additionally, when I see the crash, my phone firmware (MIUI) allows me to view the crash logs. I have pasted here for your reference (https://pastebin.com/Cztsv2mS).

I have also enabled the logging level to "Record Everything" in Advanced options and when AG crashed, I opened AG, navigated to "Export logs and system info" option and exported the zip file to my phone. However, when I navigated to that folder and opened the zip archive, I see 0 B file and when I open the zip file, I see a message saying that the archive is corrupted. I did this process twice.

I think the log feature is not working correctly due to the crash? So two issues now - AG crashes and log does not work as expected after the crash.

I am running on Android version 6.0.1 MMB29M
Firmware: MIUI Global 10.2 Stable

Test Steps:

1. Mobile data/WiFi turned off.
2. Restart Phone and then open AG & enable protection.
3. Turn WiFi on
4. Open FF and visit any page and AG crashes.

**Comment by ameshkov** [comment]
Yup, we're rolling an update soon with this crash fixed (hopefully)

**Comment by ameshkov** [comment]
Please reopen if it happens with the next nightly again

**Comment by ameshkov** [comment]
@Nzzyme new nightly should be available in 5 minutes
