### ISSUE TITLE
Incorrect Date Shown on Home page of AG after selecting "Today"

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2528]
Test:
1. Launch AG > Apps Management > Clear statistics > Home
2. Select "Today" from the drop-down on the homepage. The text then says:

"Since February 6, 2019 11:59 PM"

It should instead read as:

"Since February 7, 2019 12:00 AM" (that is today's date should be shown).

Thanks!

Observed in the latest nightly (3.0.299).

**Comment by lancelot-moon** [comment]
AG uses 24-hour clock.
AM or PM is unnecessary.

**Comment by Nzzyme** [comment]
Please close this. This has already been fixed
