### ISSUE TITLE
An easy way to recognize whether https filtering is enabled?

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdguardForAndroid#2530]
### Actual behavior

In the application list, I can't recognize whether an application's https filter enable. So could you change icon when https filter enable or disable?

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5698157/52427589-398b3500-2b3b-11e9-84af-12320a66a2cf.png)

For example:

![image](https://user-images.githubusercontent.com/5698157/52428702-7f48fd00-2b3d-11e9-8497-8861c05feb6e.png)

</details>

### Your environment

* AdGuard version: `3.0.220η (1.3.113cl)`
* AdGuard filtering mode: `VPN`
* Device model: `ZE552KL`
* Operating system and version: `Android 8.0`
* Rooted or not? `No.`
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? `No.`

**Comment by zzebrum** [comment]
@bestpika the shield icon show if ad blocking enabled or not and became orange if ad blocking disabled for the app.

**Comment by bestpika** [comment]
I want to know the https filter is enabled or not in the application list, but now I can't know.

**Comment by lancelot-moon** [comment]
@ameshkov

How about letting it be the icon of lock if enabling HTTPS filtering?

**Comment by zzebrum** [comment]
@bestpika oh, you want to change what setting the icon represents.

**Comment by Revertron** [comment]
I propose orange tick sign in a shield icon if HTTPS filtering is disabled :)

**Comment by lancelot-moon** [comment]
But you use lock icon for HTTPS filtering.
Be intuitional.

The orange shield icon is already for only AG protection enabled (ad blocking disabled).

Orange shield icon: AG protection enabled
Green shield icon: Ad blocking enabled, except for above
Green lock icon: HTTPS filtering enabled, except for above

**Comment by lancelot-moon** [comment]
> I propose orange tick sign in a shield icon if HTTPS filtering is disabled :)

Green shield icon means HTTPS filtering disabled.
Orange tick sign in shield icon is unnecessary.
What we talk about is for HTTPS filtering **enabled**.

**Comment by lancelot-moon** [comment]
@ameshkov

Otherwise, you have to **redesign** icons for ad blocking and HTTPS filtering.

Green shield icon with **orange tick**: Both AG protection and ad blocking enabled, but HTTPS filtering disabled

Green shield icon with **green tick**: All enabled
(Use this instead of green lock icon)

**Comment by lancelot-moon** [comment]
@Revertron

Can this minor improvement be done before v3 release?
This is helpful.
Thanks.

**Comment by Revertron** [comment]
We will think about it with our designer :)

**Comment by lancelot-moon** [comment]
Sure.
You use lock icon for HTTPS filtering...
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/kYI5Z6g.jpg)
</details><br/>

It's a problem if changing to use green shield icon with green tick.

Anyway, just wish the **intuitional difference of HTTPS filtering enabled/disabled** in app management **before v3 release**.

Thanks a lot!

**Comment by TPS** [comment]
`pref.notify.on.unknown.ca` is actually quite good as a step toward this.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
