### ISSUE TITLE
[FR] Add an Internet speed meter

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2533]
As requested by user 2063801,

"Can you add Internet speed meter in adguard? that I can see my
Internet speed on notification bar and decide to open assistant or not
when I see abnormal network traffic."

**Comment by lancelot-moon** [comment]
He might wish that the feature is built in AG...
https://play.google.com/store/apps/details?id=info.kfsoft.android.TrafficIndicatorPro

But it'll be shown in AG's notification bar.

**Comment by ameshkov** [comment]
dup of https://github.com/AdguardTeam/AdguardForAndroid/issues/1492
