### ISSUE TITLE
After license resetings Stealth Mode settings still persist in Filtering Log requests

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForAndroid#2534]
1. Reset License
2. Go to http://wmconvirus.narod.ru/
3. Return to Adguard app and check Filtering log
4. Go through request 

### Expected behavior
There should be no informaation about Stealth Mode settings

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/52492401-28453580-2bda-11e9-88a4-9653ee5a7036.png)

![image](https://user-images.githubusercontent.com/41899455/52492862-24fe7980-2bdb-11e9-9e2f-0c571b9b2b68.png)

</details>

### Your environment

* Adguard version:3.02.231
* 
* Device model: Pixel/Xiaomi/Samsung

**Comment by nkartyshov** [comment]
Fixed
