### ISSUE TITLE
Incorrect 'Filter Name' Shown in 'Log Details' page

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2535]
Navigate to Settings > Content Blocking > Filters

On this page, the 'Others' category of filters is disabled.

Settings > DNS Filtering is enabled.
DNS requests blocking is enabled.
Custom DNS settings is enabled.
"Cisco OpenDNS" is selected.

However, checking the filtering log shows many blocked DNS entries. Upon opening one of them, the 'Filter Name' shown is 'AdGuard Simplified domain names filter'.

Screenshot: https://ibb.co/h1rtmzt

Note that 'AdGuard Simplified domain names filter' was disabled (which is found under 'Other' filter category). Therefore, AG shows the wrong filter name in the log details. Please fix. Issue seen in v3.0.232η

**Comment by lancelot-moon** [comment]
This isn't a bug.
As long as you enable DNS filtering, SDN filter works on DNS level in the background. :D

The filters of content blocking is for HTTPS filtering, not for DNS filtering.
(User filter is exception.)

**Comment by ameshkov** [comment]
`AdGuard Simplified domain names filter` is used implicitly when DNS requests blocking is enabled

**Comment by Nzzyme** [comment]
So then there are two filters used for DNS in this scenario:

1. AdGuard Simplified domain names filter
2. Cisco OpenDNS

Is that correct? Why is the first one used when I did not select it?

What if I just wanted to use  the second one?

And finally, if I selected the 'AdGuard DNS' filter under DNS, would the 'AdGuard Simplified domain names filter' still be used?

Thanks

**Comment by ameshkov** [comment]
Well, OpenDNS is not a filter, this is a DNS server.

> What if I just wanted to use the second one?

You'll need to disable DNS requests blocking

**Comment by lancelot-moon** [comment]
OpenDNS has its own filters, which isn't AdGuard's business.

If you disabled SDN filter in content blocking, you only disabled it for HTTPS filtering, understand?

If you enable SDN filter for both DNS filtering and HTTPS filtering, I think it will first do filtering on DNS level.

**Comment by Nzzyme** [comment]
> `AdGuard Simplified domain names filter` is used implicitly when DNS requests blocking is enabled

Why should it be used implicitly when DNS is enabled and why can't it be disabled just like the other filters?
