### ISSUE TITLE
Feature Request for the color blind

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#2536]
Preface: I have red/green and green/brown color blindness.

Issues:
1. In Filtering Log I have a very hard time telling which traffic is whitelisted (light green) and blocked (light red).

2. In Apps Management I have a very hard time telling which traffic (cellular/WiFi) is allowed (green icon) and which is blocked (red icon).

Proposed Fix:
Using publicly available color blindness data please select a shade of green and a shade of red that can very easily be told apart - or change the light green to light blue. Whatever the case this has driven me nuts the entire time I've had AdGuard. I'm curious as to how many others experience this who both are and aren't Github users.

**Comment by TPS** [comment]
#151?

**Comment by ameshkov** [comment]
Assigned both to v3.1, thank you!

**Comment by ameshkov** [comment]
Merged into:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2637
