### ISSUE TITLE
Let user filter itself support AG_defineProperty by default.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2537]
@ameshkov 

Before, I didn't know that user filter itself doesn't support `AG_defineProperty` rules.
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1276#issuecomment-461923800

Please fix it.
It's because users may disable all AG filters but try `AG_defineProperty` rules in the user filter for testing.

**Comment by ameshkov** [comment]
Uh, please don't create similar tasks in the product-specific repos.

Currently we have only two different filtering engine: CoreLibs and the browser extension.

**Comment by ameshkov** [comment]
Also I've answered this question in the browser extension repo.
