### ISSUE TITLE
Support multi-upstream DNS servers and optimistic DNS.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2539]
1. Multi-upstream DNS servers such as what is in AG Home.
Examples:
1.1.1.1 - regular DNS (over UDP)
tls://1dot1dot1dot1.cloudflare-dns.com - encrypted DNS-over-TLS
https://cloudflare-dns.com/dns-query - encrypted DNS-over-HTTPS
tcp://1.1.1.1 - regular DNS (over TCP)
sdns://... - you can use DNS Stamps for DNSCrypt or DNS-over-HTTPS resolvers

2. Optimistic DNS project lets all upstream DNS servers resolve domains at the same time and gets the fastest response time.

https://forums.developer.apple.com/thread/110429

**Comment by ameshkov** [comment]
Good news is that `dnsproxy` supports both, we just need to implement this in the UI.

**Comment by lancelot-moon** [comment]
It seems that you add the feature in v3.0.237 nightly, right?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fN7th5X.png)
</details><br/>

About DNS upstreams, does AG app support the under syntax?
tcp://1.1.1.1 - regular DNS (over TCP)

May you give these examples in Android app?

1.1.1.1 - regular DNS (over UDP)
tls://1dot1dot1dot1.cloudflare-dns.com - encrypted DNS-over-TLS
https://cloudflare-dns.com/dns-query - encrypted DNS-over-HTTPS
tcp://1.1.1.1 - regular DNS (over TCP)
sdns://... - you can use DNS Stamps for DNSCrypt or DNS-over-HTTPS resolvers

I think the above descriptions are good!

**Comment by ameshkov** [comment]
> It seems that you add the feature in v3.0.237 nightly, right?

Yep, surprisingly:)

> May you give these examples in Android app?

Unlike AG Home, there's not enough place for a large description. This might be explained in the knowledge base

**Comment by lancelot-moon** [comment]
About DNS upstreams, does AG app support the under syntax?
tcp://1.1.1.1 - regular DNS (over TCP)

AG app only marks 4 kinds of syntax.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MvzsNuG.png)
</details><br/>

**Comment by ameshkov** [comment]
> tcp://1.1.1.1 - regular DNS (over TCP)

Well, it does, but we don't advertise it. Frankly, this is redundant as TCP will be used implicitly anyway when UDP is not available.

**Comment by lancelot-moon** [comment]
Excuse me.
How many of DNS upstreams can be added in the same field?

2 DNS upstreams?
Or more than 5?

Thanks.

**Comment by ameshkov** [comment]
Any number
