### ISSUE TITLE
 A full version of AG for Android but without the ability of blocking ads in all app on Google Play?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2541]
May you consider to release AG content blocker (or system-wide HTTPS filtering only works on browsers) + apps management (firewall) + Safe browsering + pure DNS changer on Google Play?
Maybe it can be a paid version at sweet price...
I think more people will know your products.

Even a full version of AG for Android but without the ability of blocking ads in all app.
Stealth mode is great for privacy protection.
(After 7 days, your trial version is so.
Has no the ability of blocking ads in all app.)

Most people are used to use Chrome, but Chrome doesn't have built-in content blockers.

Will Google not allow AG on Google Play?

**Comment by zzebrum** [comment]
@lancelot-moon we may have such plans in a really distant future. it is too early to say more :)
closing for now.
