### ISSUE TITLE
AG connecting to a proxy which is not added yet

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2543]
### Steps to reproduce

1. Settings - Network - Proxy settings
2. enable proxy
3.
4.

### Expected behavior
since there is no proxy added, AG should not restart the protection and connect to the nonexistent proxy.

### Actual behavior

notification about AG connected to a proxy, protection restarts.

**Comment by Revertron** [comment]
Done.

**Comment by zzebrum** [comment]
1. Add proxy server
2. Connect to it
3. Delete the server from the list

Actual behavior: AG connected to the proxy

Expected behavior: We should handle the situation

**Comment by sfionov** [comment]
Also there is an UI problem:
Size of proxy adding dialog is halved if I switch between apps while filling that dialog.

**Comment by aspasskaya** [comment]
1. Add proxy server
2. Connect to it
3. Delete the server from the list

Expected behavior: Proxy disabled.
Actual behavior: 
![image](https://user-images.githubusercontent.com/43952607/53644450-b182e180-3c47-11e9-9278-21bbe87510ea.png)

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Try to reproduce the following issues:
- [ ] https://github.com/AdguardTeam/AdguardForAndroid/issues/2543#issuecomment-468683190
- [ ] https://github.com/AdguardTeam/AdguardForAndroid/issues/2543#issuecomment-463105178

**Comment by TheHasagi** [comment]
Fixes should be available with the nearest updates.
