### ISSUE TITLE
The app UI is distorted in Arabic

### ISSUE THREAD

**Issue by ahmadMabhei** [AdguardTeam/AdguardForAndroid#2547]
1. Please examine the app UI and fix the error     
2. Version 3.0
3.   preferable to (الحماية معطلة )+( الحماية فعالة ) 
4. ![screenshot_ - - - - -](https://user-images.githubusercontent.com/32304270/52727534-7be2c500-2fc6-11e9-8d37-50acbdc6b3b4.png)
5.

**Comment by aalpatkina** [comment]
fixed in OneSky

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Examine new UI for RTL languages

**Comment by TheHasagi** [comment]
The fix should be available with the nearest update.
