### ISSUE TITLE
Why can TTL of cookies not be 0 in stealth mode?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2548]
In AG for Windows, users can set 0 for TTL of cookies.

Why is 0 not available in AG for Android?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oyQUJzD.png)
</details><br/>

**Comment by zzebrum** [comment]
looks like a bug, thank you!

**Comment by lancelot-moon** [comment]
The description for TTL of cookies in AG for Windows:
Set the time interval here (in minutes). All third-party cookies will self-destroy when they have been alive for this period. Set to '0' to block cookies completely.

**Comment by nkartyshov** [comment]
fixed
