### ISSUE TITLE
RuntimeException while importing settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2554]
See the details here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/16331/

**Comment by nkartyshov** [comment]
Cannot reproduce. 
@zebrum assist me please

**Comment by ameshkov** [comment]
I don't think you'll be able to reproduce it easily, you should read the code carefully and add protection mechanism there

**Comment by nkartyshov** [comment]
Fixed

Test instruction: no need
