### ISSUE TITLE
FiltersCategoryActivity: Comparison method violates its general contract

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2555]
See the details here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/17141/
https://sentry.adguard.com/adg/adguard-android-rs/issues/14614/
https://sentry.adguard.com/adg/adguard-android-rs/issues/11794/

**Comment by nkartyshov** [comment]
This issue will be fixed in https://github.com/AdguardTeam/AdguardForAndroid/issues/2556
