### ISSUE TITLE
TransactionTooLargeException exception while starting a service

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2557]
https://sentry.adguard.com/adg/adguard-android-rs/issues/14881/events/635831/

So it seems that we're trying to pass too much data to the service. Could be a VpnService configuration (where else do we use it?).

**Comment by Revertron** [comment]
From [this answer](https://stackoverflow.com/a/12809171/2605687) we have:

> waiting for android to respond back with huge data (for example, getInstalledApplications() when the user installed lot of applications)

I think this is our case.

**Comment by ameshkov** [comment]
Check the threats state, you'll see what it was waiting for

**Comment by ameshkov** [comment]
Look for `Parcelable` implementations and try to limit the maximum size of it.
