### ISSUE TITLE
"Support" menu bug

### ISSUE THREAD

**Issue by vadrozh** [AdguardTeam/AdguardForAndroid#2561]
### Steps to reproduce

1. Open AG
2. Go to Support->Send a message
3. Go "back"/tap on empty space(close topic select)

### Expected behavior

AdGuard will continue work.
### Actual behavior

AdGuard lags

<details><summary>Screenshot:
Before:
 
https://pp.userapi.com/c846322/v846322778/1a4937/TGsxD6EIxVU.jpg

After: 

https://pp.userapi.com/c846122/v846122778/19c9e1/mr-REtXicA4.jpg</summary>

</details>

### Your environment

* Adguard version: Beta 3.0
* Adguard filtering mode: VPN / Proxy(manual/auto) VPN
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2) 5.1 Cyanogenmod
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by vadrozh** [comment]
Send a message to support, appended issue number.

**Comment by zzebrum** [comment]
@vadrozh  is it reproducible all the time?

**Comment by ameshkov** [comment]
Also, define "lags" please

**Comment by zzebrum** [comment]
Ok, we've figured it out.
* Open AG
* Go to Support->Send a message
* Go "back"/tap on empty space(close topic select)
* **Swipe to open side menu**

**Comment by nkartyshov** [comment]
Fixed
