### ISSUE TITLE
Allow running the onboarding tool for the second time 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2562]
> I think this flow of options should be available a second time (to pick one of the preconfigured options), or you should document what those three levels are. It would be easier to go between various options and know you're not going to **** something up because you can see a list of recommended options and easily revert.

ID 1403048

**Comment by ameshkov** [comment]
@AlikhanAliev plz take a look.

**Comment by AlikhanAliev** [comment]
It will be in context menu in settings
