### ISSUE TITLE
The AdGuard 3.0β filtering log does not show enough information prior to clicking on an event

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2564]
The Filtering log in v3 doesn't show enough information prior to clicking on the event. In previous versions, I could see both the server and most of the detailed URL prior to opening each item. I see this as a major step backward. Please add an option to display the Filtering Log as it was before. I literally have almost no use for it now because it will now take me 3-4x longer to analyze the log than it did before. 

### Expected behavior

<details><summary>Expected:</summary>

![screenshot_2019-02-17-09-19-26](https://user-images.githubusercontent.com/15856304/52909716-b7ff7980-3295-11e9-85a1-b2c4c01c6199.png)

</details>

### Actual behavior

<details><summary>Actual:</summary>

![screenshot_2019-02-17-09-12-42](https://user-images.githubusercontent.com/15856304/52909714-b3d35c00-3295-11e9-855a-917b01968c04.png)

</details>

### Customer ID 
1968599

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/3b5ae90b-463d-4cdd-806b-d58ccc3d85fe

- 2 lines in filtering log again
- Switch on/off was hidden in context menu
- Changes in disabled fl

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Examine new Filtering Log screen
