### ISSUE TITLE
NordVPN integration stopped working for some users

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2565]
ID: 1536845, 2.12.50 >> 3.0.241

> I tried following the instructions available at your help page by filling my NordVPN login credentials, "1080" as my port, "us3001.nordvpn.com" as my server link, checked the proxy as "default" and selected "SOCKS5" in proxy type but connection is not working when I turn on the proxy in AdGuard. Credentials are good to go, I can log in just fine with them on the website and subscription is active. There's no space before, between or after the server name.

> v. 3.0 beta does not help, unfortunately. I got the same "unable to connect to proxy"

ID: 2118201

> proxy with NordVPN stopped working

ID: 2118568

> I have NordVPN running on my Galaxy S7 with android 8. I cannot get your app to use it. Keeps saying unable to connect

ID: 2115769 _(w/ debug logs from 3.0.237)_

> When I have the app set to on it says it's being routed through a proxy but it's not actually letting me connect to the Internet?

### Steps to reproduce

1. Configure the AdGuard app to upstream to the NordVPN proxy
2. Check the connection status

### Expected behavior

The proxy works

### Actual behavior

AdGuard faisl to connet to the proxy

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/52909940-e29f0180-3298-11e9-87cd-9a0df4f352f0.png)

</details>

### Customer ID 

multiple reports 

### Your environment

* Adguard version: 2.12.250, 3.0.242, 3.0.237
* Adguard filtering mode: VPN 
* Device model: (e.g. Google Pixel)
* Operating system and version: 8.1.0, 9, 8.0.0
* Rooted or not?  n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by devlamania** [comment]
ID 2096898

Ignore issue. Was using Indian NordVPN servers which doesn't support SOCKS5. Using Singapore servers now without any issue.

**Comment by ameshkov** [comment]
Guys, we cannot do anything with that, this is on NordVPN side
