### ISSUE TITLE
AdGuard exits without confirmation

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#2566]
Currently testing: AdGuard 3.0.241β

If the user accidentally (or intentionally) clicks on the `Exit` item in the menu, AdGuard completely closes without warning.  This immediately shuts down the firewall and content blocker.

Because the impact is so severe, I recommend adding a warning box that informs the user that the firewall will be deactivated if they continue, and require them to confirm their action.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/7f88ed4f-b8d2-46ca-8214-0cd7758992d1

@vbagirov , help me with texts, pls

**Comment by Gitoffthelawn** [comment]
@AlikhanAliev If you post your best guess at the strings here, I can provide you with the correct English strings.

**Comment by AlikhanAliev** [comment]
@Gitoffthelawn 
**Are you serious?**
In AdGuard app “Exit” mean “EXIT”. If you close the application, then ads and trackers will obsess you again.
Don't show me this dialog anymore [  ]
Exit

**Comment by Gitoffthelawn** [comment]
@AlikhanAliev *For you:*

**If you exit AdGuard, your system will no longer be protected by our firewall and ad-blocking technology.**

**Do you want to exit?**
**[No]  [Yes]**

*When there is sufficient space (e.g. on a tablet), you can use:*
**[No, keep protection enabled]
[Yes, disable protection and exit]**

*You can also include:*
**[ ] Don't ask again**

*But I don't recommend including this option because if the user accidentally selects it, then AdGuard protection will be too easy to accidentally terminate in the future.*
