### ISSUE TITLE
New wizard cannot be re-invoked

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#2567]
Currently testing: AdGuard 3.0.241β

The user currently cannot re-invoke the protection suggestions wizard after it has been used one time.  This means that if the user wants the change their level of protection through the wizard interface, they cannot.

Recommendation: Allow the user to re-invoke the wizard.

**Comment by Gitoffthelawn** [comment]
Note: I think this may be the same as https://github.com/AdguardTeam/AdguardForAndroid/issues/2562, but I'm not sure if "onboarding" is the same as the wizard.

**Comment by ameshkov** [comment]
yeah, this is a duplicate for #2562.
