### ISSUE TITLE
DNS forwarding for DNS hijacking and DNS cache pollution.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2569]
Can DNS overriding solve DNS hijacking and DNS cache pollution?

If not, ...

How about adding the feature of DNS forwarding, except for blacklist and whitelist for DNS filtering?
(Such like the user filter.
Users can manually input rules or import from a file.
But it will intuitively show the information of domain and forwarding IP in the list.)

Well, it's a good thing if you can provide a default list of DNS forwarding for importing from a URL.
(Maintain the list at server side, not in app.)

**Comment by ameshkov** [comment]
Well, no, this all is about DNS servers protection, not the client side.

**Comment by lancelot-moon** [comment]
DNSCloak has the feature of DNS forwarding.

It can be at client side...
