### ISSUE TITLE
When Adguard is enabled, connection is terminated in a few seconds, then restored again

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#257]
Happens only with mobile network, but not with Wi-Fi.

Logs and other details are in the ticket: FYF-527-48387

**Comment by ameshkov** [comment]
What do I see in the log from 18 December:

14:12:31.394: mobile data is available
14:12:55.665: network is not available
14:13:18.447: network is available again

Just before Android signals that network is not available, there is a request to http://191.238.96.69/generate_204 which times out.

My guess: 
1. Android uses this request to check if network is available
2. In our case request times out much faster as we have a very small connection timeout

That explains why mobile data connection is terminated much faster in case if Adguard's protection is on.
