### ISSUE TITLE
Missed space it date on the main screen in French translation

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2570]
<details> <summary> Example 1 (3.0.242n): </summary>

![image](https://user-images.githubusercontent.com/15856304/52936720-b3a29180-3365-11e9-873e-21948db709dd.png)

</details>

<details> <summary> Example 2 (3.0.241 beta): </summary>

![screenshot_2019-02-18-09-51-13](https://user-images.githubusercontent.com/15856304/52935963-848b2080-3363-11e9-9e85-46bb2131e9e7.png)

</details>

**Comment by nkartyshov** [comment]
fixed

**Comment by TheHasagi** [comment]
Waiting for updates to be implemented.
