### ISSUE TITLE
"I agree with Terms" button is not visible on screens with small resolution

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2571]
> Запустил обновление на 3 версию на магнитоле с андроидом 8.0. теперь не могу зайти в программу, кнопка соглашения с лицензией находится за пределами экрана. Разрешение. экрана 1024х600

### Steps to reproduce

1. Get a device with a 1024х600 or similar display resolution
2. Install AdGuard 3.0.241 b or update from within the 2.12.x app
3. Try accepting the EULA

### Expected behavior

Users are able to accept the EULA by clicking on the corresponding button

### Actual behavior

Unable to reach the Agree button

### Customer ID 
1589286

### Your environment

* Adguard version: 3.0.241 beta
* Adguard filtering mode: VPN
* Device model: a vehicle audio system
* Operating system and version: 8.0
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by zzebrum** [comment]
Also on About screen:

<details>

![photo_2019-02-21_16-12-08](https://user-images.githubusercontent.com/44832195/53171336-8539e600-35f3-11e9-8dd2-94e1513d2677.jpg)


</details>

**Comment by nkartyshov** [comment]
@zzebrum fixed

@Eugene-Savenko I can not reproduce your problem on version 3.0.241b.
Screenshot from 3.0.241b:
<details>

![device-2019-02-22-161324](https://user-images.githubusercontent.com/3413799/53245319-6f452780-36be-11e9-96cc-ad1d91b16e63.png)


</details>

**Comment by vadrozh** [comment]
@nkartyshov another UI bug on small resolution display: https://pp.userapi.com/c846021/v846021921/1b3403/6jWfX25GF2w.jpg

**Comment by TheHasagi** [comment]
Unable to reproduce it with 3.0.257n.
