### ISSUE TITLE
Please correctly apply the localization about the warning page of browsing security.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2572]
Hi,
The warning page of browsing security is still not localized with AG v3.0.242η.
It's an English page.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YduaswB.png)
</details><br/>

In **AG Home**, the warning of browsing security can be shown as Chinese Traditional (**zh-TW**) according to my language setting.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vRdjrHU.png)
</details><br/>

In **AG Browser Extension v3.0.5 beta**, the warning of browsing security can be shown as Chinese Traditional (**zh-TW**) according to my language setting.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/m7FmjLp.png)
</details><br/>

**But it's not fixed in AG for Android.
I think that you don't correctly apply it yet.
Does AG for Windows v7 / Mac v2 nightly have the same issue?**

**Comment by ameshkov** [comment]
This is a wrong repo for this, you've already filed it to CoreLibs

**Comment by lancelot-moon** [comment]
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/T3hwQwZ.png)
</details><br/>

Well, only wish it can be solved...
