### ISSUE TITLE
Regional DNS server list with  IP Addresses 

### ISSUE THREAD

**Issue by blub4747** [AdguardTeam/AdguardForAndroid#2574]
Is there somewhere a copy of the regional servers list with IP Addresses

Thx,blub4747

**Comment by ameshkov** [comment]
We're trying to maintain the list here:
https://kb.adguard.com/en/general/dns-providers

If you'd like to add anything, please propose herE:
https://github.com/AdguardTeam/AdguardKnowledgebase/

**Comment by blub4747** [comment]
In the Android app I can see three different types of DNS Servers
Regulare
Safe DNS - Global (anycast) Servers
and at the end of the this list
another one called Regional Servers

The on the link provided by does not reflect the same structure or same Server lists.

**Comment by ameshkov** [comment]
@blub4747 you should try the v3.0 beta version, DNS filtering settings look absolutely different now.
