### ISSUE TITLE
Tunnel hangs very often when switching from WiFi to mobile or vice versa

### ISSUE THREAD

**Issue by quthla** [AdguardTeam/AdguardForAndroid#2575]
### Steps to reproduce

1.
2.
3.
4.

### Expected behavior

Should notice connection change and restart tunnel.

### Actual behavior

No connection possible unless protection manually restarted

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 3.0.242
* Adguard filtering mode: VPN
* Device model: OnePlus
* Operating system and version 9
* Rooted or not? Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by zzebrum** [comment]
@quthla hello!

please, collect a debug log: https://kb.adguard.com/en/android/solving-problems/log#collecting-debug-log
on step 5, export the log directly into a local file and send it devteam[at]adguard[dot]com

**Comment by quthla** [comment]
Problem is that log will get pretty big so it's not really feasible having it on that level.

**Comment by ameshkov** [comment]
@quthla well, it's about 300MB per day, but it will be about 20-30MB when archived (that's what AdGuard does when it exports logs).

**Comment by Eugene-Savenko** [comment]
We have a similar report:

> после обновления до and 8.0 часто при переключении с Wi-Fi на мобильную сеть программа намертво замирает.

The debug log will be available here soon: 1393535

**Comment by quthla** [comment]
Seems fixed for me. Battery optimization was reenabled after reinstalling the app and probably the part of the app which restarts the tunnel on connection change was killed then.
