### ISSUE TITLE
[Root] IPv6 filtering doesn't work

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2579]
### Steps to reproduce
1. Must use a Google Fi SIM card;
2. Set AdGuard to automatic proxy mode;
3. AdGuard will be unable to establish a local HTTP proxy. All sites will return an ERR_CONNECTION_RESET upon visit;
4. Manual HTTP proxy will work just fine.

### Expected behavior
Using a Google Fi SIM card should not prevent AdGuard from working in local HTTP proxy mode w/automatic configuration.

### Actual behavior
Google Fi somehow prevents AdGuard from launching automatic local proxy.

<details><summary>Screenshot:</summary>

Not applicable.
</details>

### Customer ID 
2114670

### Your environment
* Adguard version: 2.12.250 Release, 3.0.241 Nightly
* Adguard filtering mode: Local HTTP proxy, automatic configuration
* Device model: OnePlus A6013
* Operating system and version: Android 9
* Rooted or not?: Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None found

**Comment by moonspeak** [comment]
I am the user who reported this issue via email. Feel free to ask me for any further information or troubleshooting.

**Comment by ameshkov** [comment]
@sfionov I guess we will need your help with this one. Some really weird stuff is going on.

1. When on Google Fi with auto-proxy mode enabled, AdGuard's own connections are seem to be dropped.
2. We might need to examine the logs, iptables and routes look complicated, I can't yet understand what's the issue.

**Comment by sfionov** [comment]
Seems that IPv6 filtering in root proxy mode breaks any IPv6 connections (with connection timeouts) on OnePlus.

Reproduced on our OnePlus test device.

**Comment by sfionov** [comment]
core/pull-requests/1372

**Comment by artemiv4nov** [comment]
@moonspeak the problem solved in latest nightly 3.1.77. Update Adguard and check it please.
