### ISSUE TITLE
[System Notification] AdGuard is draining your battery

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#2580]
### Steps to reproduce
1. Set filtering method to use the Local HTTP Proxy auto mode
2. Wait
3. Android system notifies "AdGuard is draining your battery"

### Expected behaviour
No notification of battery drain appears when using the local VPN filtering method, the same should apply for Local HTTP proxy auto mode.

### Actual behaviour
Android system notifies user of AdGuard draining battery when in Local HTTP proxy auto mode.

<details><summary>Screenshot:</summary>

![notification](https://user-images.githubusercontent.com/6005161/53230442-69594180-36d2-11e9-8a4e-96fe0a7d529a.jpg)
![adguard reported use](https://user-images.githubusercontent.com/6005161/53230453-6e1df580-36d2-11e9-821c-594a8ad58265.jpg)
![oxygenos reported use](https://user-images.githubusercontent.com/6005161/53230460-6fe7b900-36d2-11e9-8803-ef81956c646e.jpg)

</details>

### Customer ID 
1663474

### Your environment
* Adguard version: 3.0.250n
* Adguard filtering mode: Local HTTP Proxy auto mode
* Device model: OnePlus 6
* Operating system and version OxygenOS Beta 12
* Rooted

**Comment by ameshkov** [comment]
Tbh, this sounds like some OxygenOS specific issue. We should figure out what triggers this behavior, though.

Just in case, could you please take a screenshot of AdGuard's own battery usage stats? Any anomalies there?

**Comment by jslawler** [comment]
> Tbh, this sounds like some OxygenOS specific issue. We should figure out what triggers this behavior, though.
> 
> Just in case, could you please take a screenshot of AdGuard's own battery usage stats? Any anomalies there?

See OP for screenshots.

**Comment by ameshkov** [comment]
Ah, I see it now.

Yeah, the battery usage seems to be just okay. On the other hand, OxygenOS is not aware that AdGuard works as a proxy so unlike the VPN case, it might think that all the traffic belongs to AdGuard and not the apps which are being proxied.

**Comment by alvussar** [comment]
disabled adaptive battery

**Comment by ameshkov** [comment]
"adaptive battery" is some OxygenOS feature? Could you please explain where to find it? We might need to update our knowledge base article about it.

**Comment by alvussar** [comment]
The adaptive battery is a feature of Android 9, on which the latest firmware for OnePlus 6. But she is very buggy...

**Comment by jslawler** [comment]
> "adaptive battery" is some OxygenOS feature? Could you please explain where to find it? We might need to update our knowledge base article about it.

From the Adaptive Battery page:

> **Use Adaptive Battery**
> _Limit battery for apps that you don't use often_
> 
> To extend battery life, Adaptive Battery limits battery for infrequently used apps. Your phone will learn how yo use apps over time.
> 
> Notifications may be delayed for these apps.

**Comment by jslawler** [comment]
On Oxygen OS, the following settings should be disabled to keep apps such as AdGuard fully functional:

- Adaptive Battery
- Battery optimisation
- Battery Saver

As an additional, locking the app in the app switcher also helps keep it alive.

**Comment by lancelot-moon** [comment]
https://bit.ly/2XlUo6f

Hope a solution without root.

**Comment by alvussar** [comment]
Battery optimisation can not disable

**Comment by jslawler** [comment]
> Battery optimisation can not disable

Settings > Battery optimisation > AdGuard > Don't optimise

**Comment by jslawler** [comment]
> https://bit.ly/2XlUo6f
> 
> Hope a solution without root.

Great solution, however not pertaining to the topic. This should definitely be added to another thread as a workable solution for rooted users.

**Comment by alvussar** [comment]
> > Battery optimisation can not disable
> 
> Settings > Battery optimisation > AdGuard > Don't optimise

I have adguard on OnePlus 6 with optimization, it works fine

**Comment by jslawler** [comment]
> > > Battery optimisation can not disable
> > 
> > 
> > Settings > Battery optimisation > AdGuard > Don't optimise
> 
> I have adguard on OnePlus 6 with optimization, it works fine

It is possible, however due to the nature of battery optimisation it is likely that it will restrict background activity if the OS thinks the app is using more battery than it should. This especially pertains to this topic of "AdGuard is draining your battery" notification.

I daresay if you set Local HTTP Proxy auto mode and get this notification the system will kick in the battery optimisation flag to start restricting AdGuards background activity.

**Comment by ameshkov** [comment]
Guys, I am pretty sure we cannot do anything with this from our side. The information in this issue is helpful, though.
