### ISSUE TITLE
Filters in disabled groups being updated

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2581]
### Steps to reproduce

1. enable base filter
2. disable ad blocking filter group
3. check for update
4.

### Expected behavior
base filter is not updated

**Comment by nkartyshov** [comment]
fixed

**Comment by TheHasagi** [comment]
The text should be changed like "Nothing to update" \ "No updates found for enabled filters".

![img](https://uploads.adguard.com/TheHasagiu8gip.png)
![img](https://uploads.adguard.com/TheHasagib51v4.png)

**Comment by nkartyshov** [comment]
@TheHasagi This will fix in https://github.com/AdguardTeam/AdguardForAndroid/issues/2609
