### ISSUE TITLE
HTTPS Filtering settings bug

### ISSUE THREAD

**Issue by vadrozh** [AdguardTeam/AdguardForAndroid#2582]
### Steps to reproduce

1. Go to Settings->Network->HTTPS filtering
2. Enable autorotate
3. Try to rotate image

### Expected behavior

Image will be rotated
### Actual behavior

Image not rotating
<details><summary>Screenshot: not applicable</summary>

</details>

### Your environment

* Adguard version: 3.0.241 Beta
* Adguard filtering mode: VPN
* Device model: GT-S7270
* Operating system and version: 5.1 Cyanogenmod
* Rooted or not? Rooted.
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No.

**Comment by admitrevskiy** [comment]
Done.

The same issue occurs in the MainScreen after protection enabling.

**Comment by aspasskaya** [comment]
! Also, 
- (root device) Go to Settings -> Network -> HTTPS filtering -> Security certificate 
Scroll doesn't work.
Disappeared 'Move to the system store'.

![image](https://user-images.githubusercontent.com/43952607/53726794-ce095e80-3e7f-11e9-84d0-385529c1ec77.png)
![image](https://user-images.githubusercontent.com/43952607/53726933-1b85cb80-3e80-11e9-96f3-6f82cb96a6ac.png)
