### ISSUE TITLE
In other languages' interface, lack the descriptions of Faroese language-specific ad blocking in Dandelion Sprout's Nordic Filters.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2583]
In English interface, there is the descriptions of Faroese language-specific ad blocking in `Dandelion Sprout's Nordic Filters`.

In other languages' interface, **lack** the descriptions of Faroese language-specific ad blocking in `Dandelion Sprout's Nordic Filters`.

On onesky, there is also no phrase for the tag of Faroese language.
Need to upload the 2 new phrase.
`Designed specifically to block ads on web pages in the Faroese language`
`Faroese language-specific ad blocking`

**Comment by nkartyshov** [comment]
Those phrases have been already added, but you should update your filters

**Comment by lancelot-moon** [comment]
Until now, I don't see new phrases for Faroese language in Miscellaneous / Miscellaneous.
I'll check later.

**Comment by lancelot-moon** [comment]
What did you fix in v3.0.277 nightly?
Still lack the tag of `Faroese language-specific ad blocking` in AG when choosing other language interface.

You should also upload the 2 new phrase to onesky.
`Designed specifically to block ads on web pages in the Faroese language`
`Faroese language-specific ad blocking`

**Comment by TheHasagi** [comment]
@lancelot-moon 

Can you reproduce it with 3.0.282n?

[latest nightly](agrd.io/android_nightly)

**Comment by lancelot-moon** [comment]
Yes, you don't fix it in v3.0.282 nightly.
Can you not try to shift to Russian interface and check by yourself?

You lack the tag of Faroese language-specific ad blocking in other languages' interface.

The situation is a little like that you lacked the tag of Bulgarian in the past.

Simply answer me.
Can you find "Faroese language-specific ad blocking" on Misc/Misc of onesky?

**Comment by lancelot-moon** [comment]
@zzebrum

How did you solve it since there is no phrase about Faroese language-specific ad blocking on onesky?
In the next nightly version?

**Comment by lancelot-moon** [comment]
Fixed.
