### ISSUE TITLE
Crash happen android version v2 also v3beta too

### ISSUE THREAD

**Issue by safaksama2018** [AdguardTeam/AdguardForAndroid#2584]
### Steps to reproduce

1.when ever open app management screen
Than when ever try to load and show all app s itself adguard app almost always crash sometimes restart itself sometimes I need to restart but it happen almost always only %1-2 chance to adguards app management screen to show up normally
2.
3.
4.

### Expected behavior

Adroid adguard always crash on app management screen
### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

1969826
### Your environment

* Adguard version: 3.0.241b
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel) samsung a8
* Operating system and version (e.g. Android 7.1.2) android 8
* Rooted or not?  Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?
Sophos

**Comment by zzebrum** [comment]
#2308 closed as dup
