### ISSUE TITLE
Incorrect battery capacity

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2587]
Incorrect battery capacity at startup and random CPU hops.

#### Logs will be provided upon request

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagie7l15.png)
![img](https://uploads.adguard.com/TheHasagi3n4io.png)

</details>

### Your environment

* Adguard version: 3.0.250n
* Adguard filtering mode: VPN
* Device model: HUAWEI model=CLT-L29
* Operating system and version: 9/EMUI

**Comment by admitrevskiy** [comment]
It looks like EMUI firmware bug. Here is the report for Huawei: https://uk.community.huawei.com/software-40/emui-battery-issue-4941

**Comment by ameshkov** [comment]
@Revertron just increase default to 2000
