### ISSUE TITLE
Add ABP Bulgarian EasyList

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#259]
http://stanev.org/abp/adblock_bg.txt
Requester here - ISO-166-78393

**Comment by evgeniy-ADG** [comment]
The same request from another customer ODE-958-40521

**Comment by ameshkov** [comment]
Will be done in v2.5

**Comment by ameshkov** [comment]
Done, will be available in the next beta version.
