### ISSUE TITLE
A group should be enabled if a filter is enabled from search a filters

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/AdguardForAndroid#2590]
### Steps to reproduce

1. Go to Search filters
2. Enable a filter

### Expected behavior
Filter group should be enbaled

### Actual behavior
Filter group

### Your environment
* Adguard version: 3.0.250
* Adguard filtering mode: VPN
* Device model: Google Pixel
* Operating system and version Android 9
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? no

**Comment by nkartyshov** [comment]
fixed

**Comment by aspasskaya** [comment]
Error in search for filters in disabled filters group.
- Search for filters in filters group section -> Ok. The filters group 'Security' - disabled. 'Spam404' filter disabled.
![image](https://user-images.githubusercontent.com/43952607/53734969-8e01a600-3e96-11e9-91fd-ba331fbb1a8f.png)

- Search for all filters and filters group -> Error. 'Spam404' filter enabled.
![image](https://user-images.githubusercontent.com/43952607/53734778-13d12180-3e96-11e9-953e-9dbff34e71cc.png)

**Comment by nkartyshov** [comment]
Fixed
