### ISSUE TITLE
Filtering log section reset default

### ISSUE THREAD

**Issue by safaksama2018** [AdguardTeam/AdguardForAndroid#2591]
Filtering log section reset default each time when ever I return that section it allow all but I just only allow blocked or modified , white listed, and third-party but each time I return filtering log panel its allow all so I lost all my previous logs . 

### Steps to reproduce

1.on filtering panel just adjust any filtering rules
2.than go anywhere anypage 
3.than after return filtering section again
4.you'll see your filtering log section dismissed and returned to default log all. 

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 3b
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel)
* Operating system and version (e.g. Android 7.1.2) android 8
* Rooted or not?  Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?

**Comment by zzebrum** [comment]
If you are talking about the filter requests section, then I can not reproduce the problem.

**Comment by zzebrum** [comment]
@safaksama2018 ?
