### ISSUE TITLE
Remove icon to custom filter group sections

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2592]
# Expected behavior
![image](https://user-images.githubusercontent.com/43952607/53555055-38559280-3b52-11e9-97f0-17db4724ed27.png)
# Actual behavior
![image](https://user-images.githubusercontent.com/43952607/53555047-325fb180-3b52-11e9-8077-19cc17a1fa8f.png)

**Comment by nkartyshov** [comment]
We decided removing the icon in the top switch to all filters group screen, but that forgot removing icon to custom filters screen
