### ISSUE TITLE
Filters update when download failed

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2595]
## Disable network. Check filters update. Should be error.
 
![image](https://user-images.githubusercontent.com/43952607/53632878-137f1f00-3c27-11e9-8dbf-510f59a4e332.png)
# 
![image](https://user-images.githubusercontent.com/43952607/53633048-74a6f280-3c27-11e9-8f42-e51dfb331f6b.png)

**Comment by zzebrum** [comment]
seems to be working now.
