### ISSUE TITLE
Some filter descriptions issues

### ISSUE THREAD

**Issue by vadrozh** [AdguardTeam/AdguardForAndroid#2596]
1. Two translation misses:
https://pp.userapi.com/c846216/v846216076/1bafc2/4uusVpMxrBQ.jpg
https://pp.userapi.com/c852220/v852220519/cb63a/6Ky8c_nTEfc.jpg

2. Missed description of filter
https://pp.userapi.com/c847016/v847016076/1b3925/kZrcW_WppXA.jpg

### Your environment

* Adguard version: 3.0.241 Beta
* Adguard filtering mode: VPN
* Device model: GT-7270
* Operating system and version: 5.1
* Rooted or not? Rooted.
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No.

**Comment by vadrozh** [comment]
Also, i think that it's a bit better to change block name to "Возможны проблемы" instead of "Потенциально проблематично"
https://pp.userapi.com/c850632/v850632519/d2de2/XLl-s233KD4.jpg

**Comment by aalpatkina** [comment]
@vadrozh the translations have been completed on OneSky platform. We will add them to the next release. Thanks.
As about this missed description, we don't translate descriptions for filters created by someone else.

**Comment by vadrozh** [comment]
> 
> 
> @vadrozh the translations have been completed on OneSky platform. We will add them to the next release. Thanks.
> As about this missed description, we don't translate descriptions for filters created by someone else.

i said about that
![изображение](https://user-images.githubusercontent.com/16451530/54515816-6a0a8e00-4987-11e9-8a4f-6c72d110cec8.png)
description

**Comment by ameshkov** [comment]
@vadrozh это все - часть локализации списка фильтров, а не программы
