### ISSUE TITLE
Incorrect animation

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#2597]
Remove [animation](https://performix.slack.com/files/UC1V6R0GL/FGL4MFWFK/20190301_180915.mp4) please

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Examine checkboxes on the following screens: 
- [ ] Feedback
- [ ] Custom DNS dialog
- [ ] Trial dialog
- [ ] New Custom filter dialog
- [ ] Import user filter dialog
