### ISSUE TITLE
Wrongly use obsolete tag for AdGuard Safari filter?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2598]
Wrongly use obsolete tag for AdGuard Safari filter?
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/so1vbrC.png)
</details><br/>

**Comment by ameshkov** [comment]
That's not a mistake, the filter is marked obsolete as all the necessary rules are included into the base filter now.

**Comment by ameshkov** [comment]
And yeah, we'll need to stop using it everywhere where it was used by default.
