### ISSUE TITLE
"Content Blocking" Menu Missing

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2599]
In the nightly version (3.0.257) the menu option for 'Content Blocking' is missing when tapping on:

Menu > Settings  (Screenshot: https://ibb.co/tm5M8vf)

Tapping on the down-arrow next to 'Settings' however shows the 'Content Blocking' option (Screenshot: https://ibb.co/XfQD8x8)

Please fix.

**Comment by ameshkov** [comment]
Huh, weird, I do see it in the list. @nkartyshov how's that possible?

**Comment by nkartyshov** [comment]
@ameshkov It's possible if the `LayoutInflater` has be null when building a component

**Comment by nkartyshov** [comment]
Fixed

Test instruction: no need

**Comment by Nzzyme** [comment]
Ok, thanks. Please also look at other related issues posted.

**Comment by Nzzyme** [comment]
Issue fixed in the latest nightly (3.0.270)
