### ISSUE TITLE
Filters Removed in Nightly?

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2600]
Just observed that if I try to access the 'Filters' page (through steps shown in this issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/2599) then I no longer am able to see some of the filters that were available earlier in any filter category (Privacy, Social, etc.). Have these filters been removed on purpose? If not, please add them back. Issue observed in Nightly (3.0.257)

AdGuard Base Filter
Mobile Ads
Spyware
(and possibly others...)

**Comment by ameshkov** [comment]
> Just observed that if I try to access the 'Filters' page (through steps shown in this issue

Do you have any issue when you go to settings first?

**Comment by zzebrum** [comment]
@Nzzyme Not sure how to reproduce the problem ) May it be related to #2599

Can you record the debug log, please?

**Comment by Nzzyme** [comment]
I installed the latest nightly (3.0.270) and no longer observing this issue.

**Comment by ameshkov** [comment]
Well, hopefully it is fixed:)

**Comment by Nzzyme** [comment]
Yes, please close
