### ISSUE TITLE
Incorrect Search Results on "Filters" Page

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2602]
On the "Filters" page, I added a 'Custom Filter' called the AG Mobile Ads filter. Now the main 'Custom Filter' section is turned off. Also tapping on the 'Custom Filter' link takes you to the next page where you see all the custom filters added. On this page too, I have disabled the filters as seen here:

https://ibb.co/gSjnMDT
and
https://ibb.co/6ZHSgr8

However, now when doing a search with the text "mobile" on the main 'Filters' page shows this:
Screenshot: https://ibb.co/Nj6WVv2

As you can see, this is clearly a bug. The results show that the 'Mobile Ads' filter is even active in the 'Custom Filter' section of search results when it was deactivated manually.

Please fix.

**Comment by Nzzyme** [comment]
Guys, a reminder. Issue still still seen in the 3.0.270. Please fix.

**Comment by nkartyshov** [comment]
This issue have been already fixed in 3.0.277n version.
