### ISSUE TITLE
DNS Filtering Bug

### ISSUE THREAD

**Issue by vadrozh** [AdguardTeam/AdguardForAndroid#2603]
### Steps to reproduce

1. Enable DNS Filtering
2. Enable "Block DNS requests"
3. Quit AG
4. Lock phone
5. Unlock phone
6. Try to load some site(google.com etc.)

### Expected behavior

Site will be loaded
### Actual behavior

Browser returns ERR_EMPTY_RESPONSE

If you will reload page it wil be loaded normally.

###Customer ID
2117971

### Your environment

* Adguard version: 3.0.241 Beta
* Adguard filtering mode: VPN
* Device model: GT-S7270
* Operating system and version: 5.1 CM
* Rooted or not? Rooted.
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No.

**Comment by alvussar** [comment]
on nightly 3.0.264 same
p.s.
Android 9 (OnePlus 6)

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/CoreLibs/issues/763
