### ISSUE TITLE
При смене сети с WiFi на мобильную, отсутствует интернет для приложений.

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/AdguardForAndroid#2608]
При переходе с WIFI сети на мобильную, в приложениях таких как viber, facebook messanger, при запуске отсутствует сеть. При переходе с мобильной сети на wifi, такого бага не наблюдается.

### Steps to reproduce

1. Переходим с wifi сети на мобильную
2. Открываем viber, видим что при отправке сообщения нет интернета.
3. Делаем тоже самое, с выгруженным adguard, проблем не наблюдается.

* Adguard version: 3.0.264n
* Adguard filtering mode: VPN
* Device model: OnePlus 6
* Operating system and version: Android 9
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/CoreLibs/issues/763
