### ISSUE TITLE
4pda app - Adguard breaks files download

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#261]
**Source complaint:**
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45763142
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45770855

Filtering mode: VPN

**Comment by ameshkov** [comment]
@gshumihin could you please check it in the latest build?

**Comment by gshumihin** [comment]
Cannot reproduce it.
Tested with this versions: Adguard 2.5.94 + App&Game 4PDA 5.0 beta 11
