### ISSUE TITLE
Error landscape orientation in 'security certificate' section

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2612]
### Steps to reproduce

(Root device)
1. Go to Settings -> Network -> HTTPS filtering -> Security certificate
2. Enable autorotate

### Actual behavior
Scroll doesn't work.
Disappeared 'Move to the system store'.

![image](https://user-images.githubusercontent.com/43952607/53726794-ce095e80-3e7f-11e9-84d0-385529c1ec77.png)
![image](https://user-images.githubusercontent.com/43952607/53726933-1b85cb80-3e80-11e9-96f3-6f82cb96a6ac.png)

**Comment by admitrevskiy** [comment]
Done.
