### ISSUE TITLE
With v3.0.264η, AG protection restarts when entering the whitelist or the user filter in content blocking.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2613]
@ameshkov 

With v3.0.264η, AG protection restarts when entering the whitelist or the user filter in content blocking.
(Only enter and do nothing.)

**Comment by ameshkov** [comment]
Good bug, thank you!

**Comment by nkartyshov** [comment]
Fixed

Test instruction:

1. Start protection
2. Open Userfilter or Whitelist

Expected result:
Protection doesn't restart

**Comment by Nzzyme** [comment]
Confirmed also in the latest nightly 3.0.270
