### ISSUE TITLE
An option of "Only enable DNS filtering but disable HTTP(S) filtering" in DNS filtering.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2615]
@ameshkov

Maybe add the new option (switch) of "**Only enable DNS filtering but disable HTTP(S) filtering**" in DNS filtering.
After enabling the new option, pref.vpn.ipv4.bypass and pref.vpn.ipv6.bypass will be enabled.
Under the only DNS filtering mode, if trying to disable one of pref.vpn.ipv4.bypass and pref.vpn.ipv6.bypass, it will show a warning.

Some users may dislike HTTPS filtering and wish AG to work as Blokada.
This can be done in v3.1 or later which has filters subscriptions for DNS filtering.

In my another feature request, it's better if you can let AG work as AdAway for rooted devices (no VPN).
https://github.com/AdguardTeam/AdguardForAndroid/issues/2605

(Such like that HTTPS filtering has local VPN mode and local HTTP proxy mode.)

**Comment by ameshkov** [comment]
I don't want to help users get worse ad blocking and let them transform AdGuard into an inferior ad blocker.

**Comment by lancelot-moon** [comment]
Some users have no knowledge to configure AG when meeting trouble with HTTPS filtering.
They don't know they can add those domains in the whitelist of HTTPS filtering or not route specific apps' traffic through AG.
Especially, non-English speaking users are afraid to contact with AG support in English.

Just wish it can be an obvious option in DNS filtering since pref.vpn.ipv4.bypass and pref.vpn.ipv6.bypass exist in the low settings.

**Comment by ameshkov** [comment]
It does not matter. With or without HTTPS filtering, what AdGuard does is better than what DNS-level ad blockers can do. I can't see why should we make it easier for users to make AdGuard worse than it is.
