### ISSUE TITLE
New filtering mode (Knox) for Samsung devices only.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2616]
@ameshkov

Disconnect Pro and AdHell configure Samsung Knox to do DNS filtering without VPN and root on Samsung devices.

Is it possible that AdGuard app configures Samsung Knox to do system-wide HTTPS filtering, except for DNS filtering?

**Comment by ameshkov** [comment]
No https://github.com/AdguardTeam/AdguardForAndroid/issues/813#issuecomment-278929231
