### ISSUE TITLE
Main screen UI correction

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#2617]
![image](https://user-images.githubusercontent.com/30260021/53871616-a3e5a700-400d-11e9-8eba-b7f9d7f3f906.png)

**Comment by lancelot-moon** [comment]
107 391??
Maybe lack a comma?
107,391
Or simply delete the space?

**Comment by snhv** [comment]
I prefer a comma.

**Comment by ameshkov** [comment]
Numbers format is language-specific

**Comment by Revertron** [comment]
Done.
