### ISSUE TITLE
Proxy mode: internet connection is lost after Android gets back from sleep

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#262]
Source complaints:
http://forum.xda-developers.com/showpost.php?p=64535019&postcount=489
http://forum.xda-developers.com/showpost.php?p=64596446&postcount=521
http://forum.xda-developers.com/showpost.php?p=64597972&postcount=522

Ticket ID:
HWZ-864-68199

**Comment by Bohdan-SUP** [comment]
New set of logs here - LNV-620-39563

**Comment by ameshkov** [comment]
Update from user:
http://forum.xda-developers.com/showpost.php?p=64602993&postcount=524

**Comment by ameshkov** [comment]
Ok, so we have the good and old "Android killing apps" issue. The problem in this particular case is that user has "Proxy+Automatic" mode.

Adguard is silently killed by Android, so it can't restore iptables (linux firewall) configuration. This means, that "redirect to proxy" rules remain there while the proxy itself was killed.

Short checklist (frequent causes of this killing issue):
1. Check that Adguard's notification icon setting is not set to "None". Disabling notifications lowers the app priority and it can lead to the issue.
2. A cleaner app (like Clean Master and such) may cause this. Check that Adguard is in exceptions list.
3. I am not sure about Doze yet, but it's worth trying to disable battery optimization for Adguard.

**Comment by ameshkov** [comment]
Closing as this is not a bug.
