### ISSUE TITLE
Extend filtering log: add "modified requests" filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2623]
`Blocked and modified requests` filter is inconvenient, because when you try to find non-blocked requests and enable this filter, modified requests are also hidden, but they can be an ad or something other you want to block.
Better make just `Blocked requests` or `Blocked requests`+`Modified requests` filters.

_Originally posted by @Alex-302 in https://github.com/AdguardTeam/AdguardForAndroid/issues/1369#issuecomment-470731513_

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Enable protection
-Surf the web
-Go to the Filtering Log

1) There is no switch on the top of the screen anymore. To disable filtering log go to the "three dots" menu at the right-top corner of the screen
2) Examine new filtering dialog with separated `blocked` and `modified` requests
