### ISSUE TITLE
Add to HTTPS exclusion bskyb

### ISSUE THREAD

**Issue by et6at** [AdguardTeam/AdguardForAndroid#2624]
This app https://play.google.com/store/apps/details?id=com.bskyb.skyq.it

display a error of connection using latest AdGuard nightly with https filtering enable for it, disabling the https filtering produce no more errors about connection.

**Comment by zzebrum** [comment]
@TheHasagi please check

**Comment by TheHasagi** [comment]
@et6at 

Hello!

Unfortunately, this application can't be installed and work within the devices we have. Please, tell me the package name so we can add it to HTTPS exclusions. 

You can manually download the [app](https://play.google.com/store/apps/details?id=com.csdroid.pkg) that will show you the package name of "Sky Go per i clienti Sky Q" app.

**Comment by et6at** [comment]
Package Name: com.bskyb.skyq.it

**Comment by et6at** [comment]
@ameshkov 

If you decompile the app, inside com.bskyb.skyq.it_PR16.3.1.1-1000\res\raw\config.props

sa.vgdrm.host=pskyq-drm-sgw.skycdn.it
sa.vgdrm.port=443
sa.vgdrm.path=DRMS5
sa.vgdrm.edge.host=pskyq-drm-sgw.skycdn.it
sa.vgdrm.edge.port=443
sa.vgdrm.edge.path=DRMLG5
sa.vgdrm.vod.edge.host=pskyq-drm-sgw.skycdn.it
sa.vgdrm.vod.edge.port=443
sa.vgdrm.vod.edge.path=DRMVLG5
sa.singleton.bin.path=libvgc.bin
VGConnect.log.pal=1
VGConnect.log.severities=511
vgk.drmTrace=1
sa.urlFromDrm=0
sa.tokenBinConvert=1
sa.deactResult=1
IsDownloadAllowedWhileStreaming=1
IgnoreNetworkEventDRM=0
IgnoreNetworkEventSTRM=1
IgnoreNetworkEventDL=0
IsDownloadAllowedThroughCellular=0
sa.drma.config.name=vgdrm.cfg
**setDefaultSSLSocketFactoryByApp=true**

It explains why a SSL Socket is established by default, that probably place a interference with the AdGuard SSL filtering.

**Comment by ameshkov** [comment]
@et6at do you have AG certificate moved to the system store? By default, AG won't filter HTTPS for this app (unless you moved the certificate).

Also, does it help to disable HTTPS filtering for this app?

**Comment by et6at** [comment]
Yes I moved to system store using https://github.com/NVISO-BE/MagiskTrustUserCerts,

disabling HTTPS for the app fix the problem.

**Comment by ameshkov** [comment]
Got it, thank you!

**Comment by et6at** [comment]
You welcome. : )

**Comment by admitrevskiy** [comment]
Done.

**Comment by et6at** [comment]
If it is fixed, I proceed to close this. =)
