### ISSUE TITLE
When casually clicking for viewing the statistics of ads blocked, trackers blocked, threats blocked and data saved in the main screen, sometimes the number is 0.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2627]
In v3.0.282 nightly, when casually clicking for viewing the statistics of ads blocked, trackers blocked, threats blocked or data saved in the main screen, sometimes the number is 0.

In any period, there is the chance to be 0, which randomly occurred.
Please shift the period between today, 24 hours, 7 days, 30 days and all time.
And then try for many times.
(I tried to reset statistics, which is useless.)

ex: The number of trackers blocked is 2.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/SjuicCQ.png)
</details><br/>

After clicking it, it randomly showed 0.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/2fW3cS5.png)
</details><br/>

**Comment by Nzzyme** [comment]
Confirmed in the latest nightly
