### ISSUE TITLE
Clicking "Language-specific" in Filters causes app to crash

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#2632]
Steps to reproduce
1. Open Adguard
2. Click Menu, Settings, Content Blocking
3. Click Filters
4. Click Language-specific

Expected behavior:
It should open the list of filters.

Actual behavior
The AdGuard application crashes.

* Adguard version: 3.0.241B
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy S7 Edge
* Operating system and version: Android 8.1
* Rooted or not? Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by infinitewaveparticle** [comment]
I just recreated the crash about a minute ago so you should have the crash report.

**Comment by lancelot-moon** [comment]
You used v3.0.241 beta in your test.

Try v3.0.287 beta.
Can't reproduce your issue.

**Comment by ameshkov** [comment]
Same thing, cannot reproduce on the latest beta
