### ISSUE TITLE
simplified domain names issue with whitelisting and disabling

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2633]
I'm using a user filter for my hosts blocking and a custom filter for my filters and
I didn't have problems so far, but
today I came up across two issues:
1) first of all, no matter what I tried I couldn't whitelist `go.linkwi.se` (and/or `linkwi.se`),
which is a legitimate site according to virustotal and I need it whitelisted anyway,
of course I added, even both entries in my custom filter, 
maybe because dns blocking comes first,
2) second and most important maybe, simplified domain names filter isn't enabled in my "other filters" section, so, why have it tied to the dns filtering, since I don't want it?
I want to have control over things and dns blocking of course, how is it possible with this implementation?
also, how is this simplified domain names updated since I can't see it in my lists?

**Comment by ameshkov** [comment]
> why have it tied to the dns filtering, since I don't want it

That's how DNS requests blocking works in the current version.

Once we allow users customizing hosts-level filters in #1851, the issue will gone automatically.
