### ISSUE TITLE
Add a "pause-on-demand" functionality

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#2635]
Submitter: 2098000

Request: Добавьте пожалуйста в
функцию "паузы" возможно
автоматического возобновления работы
по таймеру. Пример: Приостановить Adguard
на 15 минут. После прошествии 15 минут
после активации, защита будет
восстановлена.

**Comment by TPS** [comment]
A configurable pause length would be appreciated.  I usually need 1 minute, but max 5 minutes, myself, so 15 minutes would be too long for my use cases.

**Comment by Versty** [comment]
@dnovitskyi Closed as a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/4772
