### ISSUE TITLE
Design changes to make the UI look better for color-blind people

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2637]
1. Review the UI elements and look for elements which don't look good to color-blind (red/green indication for instance). Do it for both themes. @AlikhanAliev 
2. @admitrevskiy is responsible for implementation.

**Comment by TPS** [comment]
Just as a reminder, [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor) is an official (Google's, anyway 😁) tool that may be useful.

**Comment by Gitoffthelawn** [comment]
Remember, there is red-green color blindness, as well as blue-yellow color blindness.  Furthermore, there is complete color blindness (monochromacy).

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Examine new `Colorblind mode` (you can enable it in General Settings). You will see changes in the Filtering Log. Check it for both light and dark themes.
-Examine new icons in the Apps Management
