### ISSUE TITLE
Filtering log improvements

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2638]
See the detailed checklist here:
https://github.com/AdguardTeam/AdguardForWindows/issues/2427

1. [x] We should use the same statuses we get from CoreLibs:
2. [x] Color indication
    * Blocked - red
    * Modified - yellow
    * Whitelisted - green
    * Bypassed - no color
3. [x] Show the full list of rules applied to the request in the log item details (including whitelist, cookie, csp, whatever).
4. [x] Additionally, show the stealth mode actions applied (if any)
5. [x] Exceptions: removed cookies and removed HTML elements should be separate items in the filtering log (just like we do now).
6. [x] "Size" value should be replaced with `↑3.0 KB ↓15.0 KB`. That's important to understand what's the size of uploaded data.
7. [x] Print `Connection ID` for processed requests as well
8. [x] Add modify reason (see `ModifyReason` flag will be useful for this task: #2708)

Current implementation issues:

* [x] "Removed HTML Element" events must be marked with "Blocked" status (red), not modified
* [x] In the case of a modified cookie, you should print the original cookie instead of the URL
* [x] ModifyReason is not handled
* [x] Also, the change caused a new crash: https://sentry.adguard.com/adg/adguard-android-rs/issues/22619/?query=3.0.363

**Comment by ameshkov** [comment]
`ModifyReason` flag will be useful for this task: https://github.com/AdguardTeam/AdguardForAndroid/issues/2708

**Comment by ameshkov** [comment]
"Removed HTML Element" events must be marked with "Blocked" status (red), not modified

**Comment by ameshkov** [comment]
In the case of a modified cookie, you should print the original cookie instead of the URL

**Comment by ameshkov** [comment]
`ModifyReason` is not handled

**Comment by ameshkov** [comment]
Also, the change caused a new crash: https://sentry.adguard.com/adg/adguard-android-rs/issues/22619/?query=3.0.363

**Comment by patrickdrd** [comment]
so is the new "modified" fixed? 
I mean are these issues considered fixed?
https://github.com/AdguardTeam/CoreLibs/issues/729 and
https://github.com/AdguardTeam/AdguardForAndroid/issues/2518

**Comment by ameshkov** [comment]
@patrickdrd yes, in the new beta you can now see the detailed modification reason

**Comment by patrickdrd** [comment]
how long till it reaches stable?
because I'm on stable now,
if it is for some days I can wait

**Comment by ameshkov** [comment]
If there are no major issues with this beta, it will be pushed to stable by the end of this week.

**Comment by patrickdrd** [comment]
great news! thanks a lot!
one more to go: use our own hosts without the sdn
