### ISSUE TITLE
$mp4 modifier doesn't work and breaks the video

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#264]
For example:
http://gamebomb.ru/fight.flv
A rule from Russian filter:
||gamebomb.ru/fight.flv$mp4

**Comment by ameshkov** [comment]
I cannot confirm this issue, $mp4 rules work properly

**Comment by ameshkov** [comment]
True for some devices.

**Comment by ameshkov** [comment]
When we are trying to open an URL blocked by $mp4 rule in browser, it makes TWO requests.

First:
```
GET /fight.flv HTTP/1.1
Host: gamebomb.ru
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; D5503 Build/14.6.A.1.236) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
```

Second:
```
GET /fight.flv HTTP/1.1
Host: gamebomb.ru
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; D5503 Build/14.6.A.1.236) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36
Accept: */*
Referer: http://gamebomb.ru/fight.flv
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
Range: bytes=0-1
```

The difference is that *Range* header is present in the second request.

**Comment by ameshkov** [comment]
We may need to implement Range header:
https://code.google.com/p/googleappengine/source/browse/trunk/java/src/main/com/google/appengine/api/blobstore/ByteRange.java

**Comment by ameshkov** [comment]
Seems to be working ok.

**Comment by TPS** [comment]
@ameshkov Wait, _is_ this currently working?  _Does_ AG support [SDCH](https://engineering.linkedin.com/shared-dictionary-compression-http-linkedin)/[ZSDCH](https://learn.microsoft.com/en-us/deployedge/learnmore-zsdch-compression)?  I've just now seen an experimental flag to turn this on in Android Edge, looked it up, & found that Chrome has been using this for almost a _decade_ (per the headers above)?

**Comment by ameshkov** [comment]
@TPS nope, it does not support it at the moment. Could you please open a feature request in CoreLibs about that?

**Comment by TPS** [comment]
@ameshkov Filed @ https://github.com/AdguardTeam/CoreLibs/issues/1799 🙇🏾‍♂️
