### ISSUE TITLE
Improve the VPN description we show when AG is started for the first time

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2640]
We should better explain that AdGuard is not really a VPN, and that it is just a local filter.

Also, the UI needs to be improved as well, the current implementation is not ideal.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/35dfe290-ba5a-4b4a-b728-59fbf0a8627c

**Comment by ameshkov** [comment]
@AlikhanAliev please prepare several images for different resolutions.
