### ISSUE TITLE
Сustom proxy context menu appears at random places on the a screen

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForAndroid#2641]
### Steps to reproduce

Settings -> Proxy settings -> Add proxy
### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/54687155-f5248900-4b2b-11e9-9ede-efc023187bff.png)![image](https://user-images.githubusercontent.com/43952607/54687166-fbb30080-4b2b-11e9-9695-5369c658b83d.png)

**Comment by ameshkov** [comment]
@AlikhanAliev we need your help with this task. What other alternatives do we have here?

**Comment by AlikhanAliev** [comment]
> @AlikhanAliev we need your help with this task. What other alternatives do we have here?

We can just show this menu on tap point :)
