### ISSUE TITLE
Change the way batch actions in Apps Management work for the default exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2648]
What I mean is that there is a list of apps for which we keep filtering (or https filtering) disabled by default. I think we should exclude these apps from batch actions, and notify users that they should change settings for these apps manually.

I see a connection with #1110 -- there should be a filter which allows to quickly show all these special apps.

**Comment by AlikhanAliev** [comment]
It can be irrelevant if we will change "apps management" this way: https://share.goabstract.com/cc073945-ec87-45d1-a89d-5e1ac207bb07

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
