### ISSUE TITLE
Amazon version does not check filter updates

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#265]
http://forum.adguard.com/showthread.php?8074-Adguard-for-Android-Beta-version-2-1-356&p=71696#post71696

**Comment by TPS** [comment]
@ameshkov Do you think this broke sometime around https://github.com/AdguardTeam/AdguardForAndroid/issues/102#issuecomment-153315379?
>ameshkov commented on Nov 3, 2015:
>>Disabled app update check for amazon build. With the current scheme it is too confusing.

I've pretty much always manually checked around 2× daily, though, so I don't really remember _not_ getting an auto-update notification.…

**Comment by ameshkov** [comment]
Yep, I am thinking about the same.

**Comment by ameshkov** [comment]
I've checked the code and it is ok.
