### ISSUE TITLE
APK download stalls at 100%

### ISSUE THREAD

**Issue by ivancuric** [AdguardTeam/AdguardForAndroid#2650]
### Steps to reproduce
Try downloading [this apk](https://github.com/hemker/apkgrabber/releases/download/v1.1.10/app-release.apk) with AdGuard on. 

### Expected behavior
Download finishes.

### Actual behavior
Download stalls on 100%.

### Customer ID 

1673388

### Your environment
* Adguard version: v3.0.291
* Adguard filtering mode: VPN
* Device model: OnePlus3
* Operating system and version: LineageOS 16.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No.

**Comment by ameshkov** [comment]
Cannot reproduce this. What browser do you use?

**Comment by ivancuric** [comment]
Chrome 73.
Here's a screen recording:
https://photos.app.goo.gl/hpkipw3GXn7BFsqf6

**Comment by zzebrum** [comment]
Can't repro either.

**Comment by zzebrum** [comment]
@ivancuric can you try to clean cache in the browser?

**Comment by zzebrum** [comment]
@ivancuric is the issue still reproducible?

**Comment by ivancuric** [comment]
Nope, not anymore.
