### ISSUE TITLE
Locale country is not used for initial language detection and not passed to CoreLibs

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2651]
* Language is detected incorrectly initially in Application and ApplicationService (only "lang" code based on `Locale.getLanguage() (without country code)` is searched but not "lang-cc", so some languages with country code may not be detected by default).
* `Locale.getLanguage() (without country code)` is passed to CoreLibs instead of application language.

Currently it is a problem only for Chinese and Portuguese locales.

**Comment by sfionov** [comment]
Related issue is https://github.com/AdguardTeam/CoreLibs/issues/805

**Comment by lancelot-moon** [comment]
Confirmed while Android system language is Traditional Chinese (繁體中文, locale: zh-TW).
This is fixed in v3.0.344η.
