### ISSUE TITLE
Threema web feature does not work with Adguard 3.0 (stable/beta) anymore

### ISSUE THREAD

**Issue by heinihuber** [AdguardTeam/AdguardForAndroid#2652]
### Steps to reproduce

1. Upgrade to AdGuard version 3.0 on the Android based mobile phone
2. Open url "https://web.threema.ch/#/welcome" with a browser on the desktop
3. Open Threema on the mobile phone -> menu -> switch Threema Web on and scan the QR code from the desktop session
4. And see that the connection can't be established anymore

### Expected behavior

Normally (when the connection could be established before) you're able to read and write Threema messages on the desktop that will be send over the app on the mobile phone.
### Actual behavior

Establishing the connection with Aguard activated is not possible anymore. DNS-Filtering activated and set to Adguard DNS does not show a progress bar in the browser session on the desktop.

Disabling DNS-Filtering brings the progress indication back but it stops on 60%.
Disabling Adguard completely enables to connect without any problem.
Whitelisting threema.ch and/or web.threema.ch does not help. 

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

01020169a5e8ac1c-8617c718-b88a-4754-8059-7676a2f2df50-000000@eu-west-1.amazonses.com
### Your environment

* Adguard version: 3.0 (stable/beta)
* Adguard filtering mode: VPN / Proxy(manual/auto) VPN
* Device model: (e.g. Google Pixel) Samsung S8 plus
* Operating system and version (e.g. Android 7.1.2) Android 9.0
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? OpenVPN but disabled when the problem comes up and tried to establish the connection between Threema browser session and mobile device app.

**Comment by TheHasagi** [comment]
@heinihuber 

Hello!

Can you please record a debug [log](https://kb.adguard.com/en/android/solving-problems/log) with reproduced issue and send it to support@adguard.com (also, provide the unique User ID).

**Comment by heinihuber** [comment]
Hello support team, 

the debug log is already sent to you with message ID 01020169b4858299-6a5c0f48-9945-4bc3-b227-641600df0248-000000@eu-west-1.amazonses.com

Thank you, kind regards

**Comment by TheHasagi** [comment]
@heinihuber 

Unfortunately, I cannot find you by that message ID, can you send me the unique ID that you shall receive in the reply message?
