### ISSUE TITLE
Disabling/enabling https filtering triggers warning alert dialog

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2653]
Does chrome app not trust user certificate? (v3.0.298 nightly)

In app management, try to disable HTTPS filtering and then enable it for chrome app.
It'll show the warning:
Enabling HTTPS filtering may break its safe connection.
Why?
I supposed there should be no the warning for supported browser apps.

I remember that you have the list of apps with forced HTTPS filtering in the low settings...

**Comment by ameshkov** [comment]
This one is a bug

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
