### ISSUE TITLE
EV Filtering warning

### ISSUE THREAD

**Issue by vadrozh** [AdguardTeam/AdguardForAndroid#2654]
Warn user about connection reset(SSL_CIPHER_MISMATCH) on first connect to sites with EV certificate (https://t.me/adguard/59231).
(If it is not a bug)

**Comment by zzebrum** [comment]
connection reset on sites with ev cert is ok. But the error is not. Please, reproduce the problem and collect debug log.

**Comment by artemiv4nov** [comment]
The task should be closed.
