### ISSUE TITLE
Adaptive icons for app shortcuts

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2656]
Пожалуйста, сделайте [адаптивные иконки](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) для [ярлыков (app shortcuts)](https://developer.android.com/guide/topics/ui/shortcuts/).
<details><summary>Screenshot:</summary>

![Screenshot_20190322_144131](https://user-images.githubusercontent.com/19418601/54857779-38405100-4d12-11e9-81a0-3beda445afe4.png)

</details>

**Comment by Revertron** [comment]
It was done when we changed our icons to vector graphics.
https://up.agrd.eu/Screenshot_1578569128.png
https://up.agrd.eu/Screenshot_1578569169.png

**Comment by Rakleed** [comment]
@Revertron @ameshkov @artemiv4nov почему закрыли issue, если в 3.4 это всё ещё не работает?

**Comment by Revertron** [comment]
> @Revertron @ameshkov @artemiv4nov почему закрыли issue, если в 3.4 это всё ещё не работает?

На скриншотах хорошо видно, что оно работает. Остальные вопросы к производителю лаунчера.

**Comment by Rakleed** [comment]
Проверил в Nova и Lawnchair 2 — всё ещё иконки в шорткатах круглые при любой другой форме адаптивных иконок. В каком лаунчере вы проверяли?
