### ISSUE TITLE
Splash screen is white in dark theme

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#2657]
### Steps to reproduce

1. Открыть AdGuard
2. Зайти в основные настройки
3. Включить тёмную тему
4. Закрыть приложение
5. Запустить приложение

### Expected behavior
Заставка (splash screen) при загрузке приложения тёмного цвета

### Actual behavior
Заставка (splash screen) при загрузке приложения на 0.2-0.5 секунд белого цвета

<details><summary>Video:</summary>

![ScreenRec_20190322_144001](https://user-images.githubusercontent.com/19418601/54858026-7e49e480-4d13-11e9-9c45-d2b2fc626379.gif)

</details>

### Customer ID 

Мне так и не пришло от вас ответное письмо.

### Your environment

* Adguard version: 3.0.297
* Adguard filtering mode: Proxy (auto)
* Device model: OnePlus 3
* Operating system and version: Android 9
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? –

**Comment by Revertron** [comment]
Это не лечится.
При запуске приложения ОС берёт тему приложения, записанную в AndroidManifest. Отрисовывает всё окно заданным в теме цветом, а потом уже передаёт управление приложению.
Для смены цвета при запуске нужно пересобирать приложение.

П.С.: Вы можете увидеть такое же поведение во всех остальных приложениях, которые позволяют включить тёмную тему.

**Comment by Rakleed** [comment]
@Revertron в Evernote, Todoist, Solid Explorer, Reddit, Moon+ Reader после включения тёмной темы описанной мною проблемы нет.

**Comment by ameshkov** [comment]
Хм, интересно как они это лечат, мы эту тему долго изучали

**Comment by artemiv4nov** [comment]
@Rakleed во всех приведенных Вами примерах welcome screen по умолчанию темный и с иконкой.
В следующей nightly-версии мы внесли корректировки для запуска нашего приложения.
Пожалуйста, дайте знать, если проблема всё ещё не решена.

**Comment by Rakleed** [comment]
Не совсем понял в какой версии конкретно вы пофиксили проблему, но судя по списку изменений, вы сделали это в 3.0.359n, но в этой версии у меня всё ещё присутствует данная проблема. Видео: https://youtu.be/X1V8oYCtq8c

**Comment by Rakleed** [comment]
@artemiv4nov не совсем понял в какой версии конкретно вы пофиксили проблему, но судя по списку изменений, вы сделали это в 3.0.359n, но в этой версии у меня всё ещё присутствует данная проблема. Видео: https://youtu.be/X1V8oYCtq8c

**Comment by Revertron** [comment]
@Rakleed Не могли бы вы записать видео светлого и тёмного сплэша у какой-нибудь одной программы?

**Comment by artemiv4nov** [comment]
@Rakleed, в следующей nightly-версии будет другая реализация.
Посмотрите и дайте знать, пожалуйста, если проблема всё ещё не будет решена на Вашем устройстве.

**Comment by Rakleed** [comment]
@artemiv4nov в последней nightly-версии нет проблемы. Осталось дождаться в стабильной версии.

**Comment by TPS** [comment]
This is again an issue in ≥ v4.0n39.

**Comment by Versty** [comment]
@TPS Separate issue is created for `≥ v4.0 nightly 39` #4464.
