### ISSUE TITLE
Localization issue in the HTTPS filtering settings (app name is translated while it should not)

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2658]
### Steps to reproduce

0. (Предварительно должен быть установлен сертификат AdGuard в хранилище пользовательских сертификатов)
1. Открыть AdGaurd
2. Зайти в настройки сети
3. Фильрация HTTPS
4. Сертификат безопасности
5. Переместить в системное хранилище

### Expected behavior
«В случае с Magisk рекомендуется использовать модуль "Move Certificates" из официального репозитория модулей.»

### Actual behavior
«В случае с Magisk рекомендуется использовать модуль "Переместить сертификаты" из официального репозитория модулей.»

<details><summary>Screenshots:</summary>

![Screenshot_AdGuard_20190322-144944](https://user-images.githubusercontent.com/19418601/54858438-d08c0500-4d15-11e9-8e8f-cfe44f7f95ad.png)
![Screenshot_Magisk_Manager_20190322-144726](https://user-images.githubusercontent.com/19418601/54858439-d255c880-4d15-11e9-81b4-f72ced498da8.png)

</details>

### Customer ID 

Мне так и не пришло от вас ответное письмо.

### Your environment

* Adguard version: 3.0.297
* Adguard filtering mode: Proxy (auto)
* Device model: OnePlus 3
* Operating system and version: Android 9
* Rooted or not? Rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? –

**Comment by Rakleed** [comment]
В репозитории Magisk все модули идут с оригинальными названиями, поэтому при поиске «Переместить сертификаты» ничего не находится.

**Comment by Revertron** [comment]
Fixed in OneSkyApp.
