### ISSUE TITLE
При попытке переместить сертификат в системное хранилище предлагайте открыть Magisk

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2659]
Я не понимаю, зачем при перемещении сертификата из пользовательского хранилища в системное и установленном Magisk вы даёте ссылку на то, как использовать Magisk. Лучше бы вы заменили эту ссылку на кнопку для открытия Magisk или сразу переходу в раздел «Репозиторий», ведь если у пользователя установлен Magisk, он скорее всего умеет им пользоваться.
<details><summary>Screenshot:</summary>

![Screenshot_AdGuard_20190322-144944](https://user-images.githubusercontent.com/19418601/54858951-0383c800-4d19-11e9-896e-e3f4c1f51e46.png)

</details>

**Comment by ameshkov** [comment]
Ну вообще практика показывает что даже те кто осилил рут, не очень разбираются в том, что с ним дальше делать. Поэтому безопаснее дать им ссылку на инструкцию лишний раз, чем просто в приложение кидать.

Да и открыть мажиск проще чем инструкцию к нему найти, экономим им время.

**Comment by Rakleed** [comment]
@ameshkov а почему бы тогда просто не добавить ещё один пункт «Открыть Magisk»? Ведь вы рекомендуете использовать модуль Magisk «Move Certifiactes» для перемещения сертификата в системное хранилище (и почему кстати?), но для этого надо свернуть ваше приложение, найти Magisk и открыть его, что мне было делать лень. Поэтому я нажал «Переместить всё равно». А если бы была кнопка для открытия Magisk, то я бы скорее попробовал установить модуль Magisk «Move Certifiactes».

**Comment by ameshkov** [comment]
Это можно, завел под это таск отдельный

**Comment by Rakleed** [comment]
@ameshkov ок, а почему вы рекомендуете использовать модуль Magisk «Move Certifiactes» для перемещения сертификата в системное хранилище?

**Comment by Revertron** [comment]
@Rakleed Потому, что с помощью модуля сертификат не записывается напрямую в системный раздел, а находится на "отдельном слое" файловой системы. Таким образом, целостность образа системного раздела не страдает.

**Comment by Rakleed** [comment]
> @Rakleed Потому, что с помощью модуля сертификат не записывается напрямую в системный раздел, а находится на "отдельном слое" файловой системы. Таким образом, целостность образа системного раздела не страдает.

@ameshkov может такое объяснение тоже стоит добавить в приложение?
