### ISSUE TITLE
Add a better explanation for blocking third-party authorization header option

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2660]
Пожалуйста, добавьте более подробное описание для функции «Блокировать заголовок Authorization» в настройках антитрекинга. А то «Может быть использован с целью отслеживания.» вообще ничего не объясняет.
<details><summary>Screenshot:</summary>

![Screenshot_AdGuard_20190323-031439](https://user-images.githubusercontent.com/19418601/54859047-f0bdc300-4d19-11e9-9ed2-747e25758c9d.png)

</details>

**Comment by ameshkov** [comment]
Могу своими словами пока сказать: в URL можно добавить юзернейми типа вот так: `http://username:password@example.com/`, которые будут переданы в Authorization заголовке и браузер их может запомнить. Как думаете лучше описать?

**Comment by Rakleed** [comment]
@ameshkov понятно, но я не знаю как лучше это писать. Например, в приложении для Windows вы довольно подробно описали это, но как такое поместить в мобильное приложение — не знаю.
