### ISSUE TITLE
Samsung Pass compatibility

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2662]
AdGuard prevents the Samsung Pass app from working, similarly to the issue we had with Samsung Pay. 

- Disabling the filtering for the Samsung Pass app > does not help
- Disabling for the app you're using the SP in > helps but leaves you with unblocked ads

### Steps to reproduce

1. Try to log in somewhere via Samsung pass

### Expected behavior

You're successfully logged in

### Actual behavior

You get an ERR_NETWORK_CHANGED error
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/54865519-335dba80-4d6f-11e9-8c0d-ca954eeb8208.png)

![image](https://user-images.githubusercontent.com/15856304/54865517-2771f880-4d6f-11e9-821b-2a2a5c53da1f.png)

</details>

### Your environment

* Adguard version: 2.12.50, 3.0.298
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy S8+
* Operating system and version: 9, sdk=28
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by TheHasagi** [comment]
Unable to reproduce, ask a customer to clear the cache of browser and check again.

**Comment by TheHasagi** [comment]
@Eugene-Savenko

Please, ask for the debug logs and settings file (json).

**Comment by Eugene-Savenko** [comment]
@TheHasagi here: 2143284

**Comment by TheHasagi** [comment]
Cannot be reproduced anymore. Closed.
