### ISSUE TITLE
Add dark theme support for KB

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2663]
Если включена тёмная тема в AdGuard, и ты нажимаешь на знак "вопроса" (например, в настройках фильтрации DNS), то в webview открывается База знаний AdGuard с белым задним фоном. И получается очень не комфортно, когда в приложении тёмная тема, а сайт с белым задним фоном. Хотелось, чтобы при включённой тёмной теме в приложении сайт открывался с тёмным задним фоном или была простая возможность включить тёмный задний фон как, например, на [сайте с документацией по VBA для Microsft Office](https://docs.microsoft.com/ru-ru/office/vba/api/overview/).

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardKnowledgeBase #308](https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/308) via [**ZenHub**](https://www.zenhub.com/)
