### ISSUE TITLE
Add Y scales for homepage graphs

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#2665]
As suggested by user 1170007,

"Graphs have no Y axis scale. Anyone who cares about these figures will
want to see how many on a particular period. Please can we have a
scale and a set of discrete points, one point per period of the X
axis. This data is serious and should not be advertising eye candy.
You should not be smoothing the graph since there is no relationship
between one period and the next. They are not graphs but *histograms*.
For a serious piece of software you have made a big mistake. I suggest
you read about histograms."

**Comment by TPS** [comment]
Similar in spirit to #785, I think.

**Comment by artemiv4nov** [comment]
There is no more graphs on the main screen, I'll mark the task as completed.
