### ISSUE TITLE
Widget 1x1 is missing in 3.0.297

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2666]
The AdGuard widget 1x1 is missing in 3.0.297 version in Xiaomi/Meizu devices but available in Android stock devices (e.g. Google Pixel/Nexus).

### Your environment

* Adguard version: 3.0.297
* Device model: Xiaomi redmi note 4x (snapdragon)
* Operating system and version: MIUI 10 / Android 7.0

**Comment by Yevhen1996** [comment]
Reproduced on Meizu M6 Note (snapdragon)
Operating system and version: Flyme 7.1.1.0G / Android 7.1.2
Adguard version: 3.0.297

**Comment by Eugene-Savenko** [comment]
No 1x1 shortcut on HTC devices and the 3x1 widget won't shrink to 1x1

**Comment by admitrevskiy** [comment]
1x1 widget is a part of shortcuts feature that is available only since Android 7.1
@Yevhen1996 can you give me more information, please? Are shortcuts available? (long tap on the app icon should open additional menu)
@Eugene-Savenko can you tell me the Android OS version installed on your HTC devices?

**Comment by admitrevskiy** [comment]
Looks like Flyme firmware issue. Anyway, here's the bug report for Flyme OS team: http://forum.flymeos.com/thread-50838-1-1.html

**Comment by admitrevskiy** [comment]
Here is the answer from Flyme forum administrator:

`I'm sorry to tell you that it doesn't support.`

So, there is no way to add shortcuts support for Android below 7.1 and Flyme except for custom launchers.

**Comment by robson80** [comment]
Widget 1x1 also missing on Xiaomi Mi 9 with AdGuard 3.1 and Miui 10 / Android 9.
Is this known? I did not find anything.

**Comment by admitrevskiy** [comment]
@robson80 hi!
Please, check if there are shortcuts available (long tap on the app icon should open shortcuts menu).

**Comment by robson80** [comment]
@admitrevskiy Unfortunately no shortcuts. Widget is missing.
With a previous AdGuard version and same Android setup everything worked fine (a few days ago).

**Comment by admitrevskiy** [comment]
1x1 widget is a part of shortcuts feature, as I wrote above, and for some reasons it's not available for MIUI at all.

**Comment by robson80** [comment]
I have read your post. But I used the 1x1 widget/shortcut until last week with Android 9 and Miui 10 on my Xiaomi Device very frequently. So, it seemed to work with one of the last AdGuard versions.
 The widget was available in the widget section. Now, only the 3x1 widget is available.

**Comment by admitrevskiy** [comment]
Can you provide me more information, please?
- Which version did you use before update? 
- Did you have 2 widgets available?
- If yes - it were 1x1 + 1x1 or 1x1 + 3x1 widgets?

**Comment by robson80** [comment]
@admitrevskiy Unfortunately, I cannot tell the version anymore. The last update was quite a while ago. Maybe end 2018 / beginning 2019.
There was only the 1x1 widget available. No more.

**Comment by admitrevskiy** [comment]
I think it was AdGuard 2.12.
There were 2 1x1 widgets available, and MIUI shows you only one of them. Since AG 3.0 1x1 was transformed to provide more information about statistics.

**Comment by robson80** [comment]
Thanks for clarification. Please bring back the 1x1 widget. Statistics are not needed :)
