### ISSUE TITLE
Support common VPN protocols.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2667]
I don't talk about real VPN service by AdGuard.
Such like the option of outgoing proxy.
(Support Socks4/5 and HTTP.)

Is it possible to be a pure VPN client app which supports common VPN protocols, like L2TP/IPSec, OpenVPN, SSTP, WireGuard... etc.?

**Comment by sebast889** [comment]
+1 for OpenVPN

**Comment by Revertron** [comment]
+1 for WireGuard ;-)

**Comment by miraj85s** [comment]
Yes, I also want this feature
Please Adguard Team Do Something About It.

**Comment by Slipi089** [comment]
is there any news about it?

**Comment by Chinaski1** [comment]
@Slipi089 @miraj85s 

But we decide to go ahead and make our own real VPN service.

- Its features include its own protocol for encrypting VPN traffic.
- The VPN works seamlessly with AdGuard's main app in compatibility mode and requires no additional settings.
- Two operating modes and much more

AdGuard VPN is available on PlayStore (Free 3GB trial)

**Comment by Slipi089** [comment]
> @Slipi089 @miraj85s
> 
> But we decide to go ahead and make our own real VPN service.
> 
> * Its features include its own protocol for encrypting VPN traffic.
> * The VPN works seamlessly with AdGuard's main app in compatibility mode and requires no additional settings.
> * Two operating modes and much more
> 
> AdGuard VPN is available on PlayStore (Free 3GB trial)

Too bad, I wanted to use my own VPN. So that I can access my home network, among other things.

**Comment by ilsubyeega** [comment]
This issue was wrongly closed because we provided a completely different solution, adguard vpn. 

Adguard VPN product does not cover everything, such as accessing internal networks via vpn. (wireguard. but preferring tailscale, i know thats hard to maintain).

This issue must to be reopened. If this is not possible, I'll bump it as a new issue.
