### ISSUE TITLE
Slight error in "protection level" calculation

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#2670]
In AdGuard v3.0, there is a percent value on the bottom of the main screen that reflects the "protection level".

If 1 out of the 5 parameters is disabled, AdGuard reports 79%, whereas is should report 80% (4/5=0.8).

**Comment by ameshkov** [comment]
Actually, there's a reason for it -- the last one percent is activating AG with a license key.

**Comment by Gitoffthelawn** [comment]
All items are checked, including "Premium license".   I am one of your beta testers, so I received the license directly from your team... perhaps that license is recognized differently?

**Comment by ameshkov** [comment]
@admitrevskiy could you please check how exactly is it calculated?

**Comment by admitrevskiy** [comment]
Hi! The protection level is calculated as follows:

Ad blocking (at least one filter is enabled): 19%
HTTPS Filtering: 21%
Blocking ads and trackers in apps: 30%
Blocking phishing and malware: 29%
Premium license: 1%

**Comment by Gitoffthelawn** [comment]
The results I receive are congruent with the design @admitrevskiy posted.

It's a little confusing, because each category has a different weight, but I respect what you are trying to convey with the percentages currently assigned.

**Comment by ameshkov** [comment]
Thanks for the useful question! This explanation can be helpful to others, it's good that we now have it here.
