### ISSUE TITLE
swedroid.se

### ISSUE THREAD

**Issue by oceanic84** [AdguardTeam/AdguardForAndroid#2671]
Ad blocking does not work well on this site, I think site owners of Swedroid.se purposely have made it harder for ad blockers to remove "empty space" so even though the ads are blocked half of the screen takes up by empty space from the ad, make it look ugly and you have the scroll like crazy all the time. Normally Adguard is very good to remove empty space from ads but on swedroid it does not work good. I spend a lot of time on this site, on blog and forum and it is the biggest android community site in Sweden. 

(Some adds slips thru, I have message fanboy about it (creator behind Swedish filter))

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #31773](https://github.com/AdguardTeam/AdguardFilters/issues/31773) via [**ZenHub**](https://www.zenhub.com/)
