### ISSUE TITLE
The "on" status of HTTPS filtering can't be saved after disabling, enabling HTTPS filtering but clicking "cancel" and then enabling it.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2672]
@ameshkov 
@Revertron

Related to
https://github.com/AdguardTeam/AdguardForAndroid/issues/2653

But I found other bugs.
Reproduction steps:

(If the app trusts user certificate:)
1. Disable HTTPS filtering for an app in app management.

(If the app doesn't trust user certificate on Android v7 and above:)
2. Try enabling HTTPS filtering. But click "**cancel**" in the warning (The app doesn't trust user certificate...).
3. Try enabling it again. **The warning won't be shown. And the switch of HTTPS filtering is on.**
4. Exit AdGuard app.
5. Open AdGuard app. The switch of HTTPS filtering for that app is **off**.

Bugs:
For apps which are forcibly done HTTPS filtering:
a. The warning (The app doesn't trust user certificate...) shouldn't be shown.
We had opened the issue for the bug:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2653

b. After disabling and then enabling HTTPS filtering but clicking "cancel", again enabling HTTPS filtering should be saved.
But it's not saved actually.

For apps which are disabled HTTPS filtering by default:
a. After enabling HTTPS filtering but clicking "cancel", again enabling HTTPS filtering should still show the warning (The app doesn't trust user certificate...).
But it doesn't show the warning actually.

b. And then the changed status of HTTPS filtering (on or off) should be saved.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instruction for QA:
-Reinstall AG (please, use device with Android 7+ installed)
-Enable HTTPS filtering
-Go to Apps Management screen and select any app
-Try to reproduce the issue

Expected result:
-HTTPS filtering switch cannot be toggled without dialog confirmation
