### ISSUE TITLE
AdGuard crashes when opening its settings

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2674]
### Steps to reproduce
1. Open the settings menu
2. Crash
3. Subsequent attempts to load AdGuard will fail

### Expected behavior
Shouldn't crash

### Actual behavior
Crashes upon entering Settings

<details><summary>Screenshot:</summary>
Not Applicable
</details>

### Customer ID & Logs
1035973

### Your environment
* Adguard version: 3.0.297
* Adguard filtering mode: VPN
* Device model: Samsung SM-N910C
* Operating system and version: Android 6.0.1
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None detected

**Comment by akmLaVx** [comment]
Update: The device uses its stock Android firmware.

**Comment by artemiv4nov** [comment]
@akmLaVx , необходимо предоставить debug-логи из приложения.
Отправьте их на dev@adguard.com или на support@adguard.com, пожалуйста.

**Comment by ameshkov** [comment]
No feedback, we cannot repro, closing it
