### ISSUE TITLE
AdGuard can no longer recognise its SSL cert in system store.

### ISSUE THREAD

**Issue by ianmacd** [AdguardTeam/AdguardForAndroid#2675]
It seems that AdGuard can no longer recognise that its SSL cert has been installed into the system store.

I have 3 devices (all Samsung: S9+, S10+ and Tab S4), all rooted and all running the latest AdGuard nightly in auto-proxy mode.

Since very recently, possibly since the release of Magisk v19, AdGuard has been failing to detect that its SSL certificate is installed in the system store. I am using the Magisk Move Certs module and have verified that it is working correctly, i.e. the AdGuard cert is properly moved at boot time.

Even stranger is that when I try to turn on HTTPS Filtering in AdGuard, it creates the cert again (even though there is already one in the system store), but then toggles HTTPS Filtering off again.

The usual message that Magisk has been detected and that the Move Certs module should be used never appears, and the cert doesn't even get installed into the *user* store.

So, a couple of weird things are going on here. The system store cert is ignored and creating a new cert mysteriously fails. And Magisk isn't properly being detected, probably because whichever test you are using ceased to be true in Magisk v19.

**Comment by ameshkov** [comment]
Additional info from the Telegram chat:

> In fact, there's a second issue if one selects the 'Move Anyway' option after Magisk is detected on a system-as-root device.

> Magisk mounts the actual system on these devices under /system_root, not /system, so AdGuard's attempt to move the cert fails and it must be done by hand.
