### ISSUE TITLE
AG not being held in memory due to "Deep Optimisation"

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#2678]
As an addition to the [How to protect AdGuard from being disabled by the system](https://kb.adguard.com/en/android/solving-problems/background-work#Oneplus) guide, an extra step is required, which is disabling "Deep Optimisation" which can be found in Settings > Battery > Battery Optimisation > 3 dots > Advanced Optimisation > Disable Deep Optimisation.

> Deep Optimisation
> Restricts background activity of apps more heavily to further improve battery life. Certain apps might not receive notifications until they are reopened.

Note that prior to disabling this after a clean wipe and already having AdGuard excluded from "Battery optimisation" already AdGuard was clearing from memory approximately 4 - 5 times a day.

If this does not fix the issue, I'll be sure to note that in the issue within the next 24 hours.

**Comment by zzebrum** [comment]
@jslawler what's the model of your mobile device?

**Comment by jslawler** [comment]
> @jslawler what's the model of your mobile device?

OnePlus 6
Android version: 9
Oxygen OS: 9.0.4

**Comment by zzebrum** [comment]
@TheHasagi investigate the problem, please.

**Comment by TheHasagi** [comment]
@jslawler 

We will add this step to our KB, thanks.
