### ISSUE TITLE
[Question] [Feature Request] Block data when screen is off.

### ISSUE THREAD

**Issue by skudo12** [AdguardTeam/AdguardForAndroid#268]
Hello,

There is currently an application in the Google Play that uses VPN to block data when the screen is off (it is possible to allow specific application) and allow when screen is on to save battery.
Link: https://play.google.com/store/apps/details?id=com.yirgalab.dzzz

Can I do the same thing with Adguard using its Firewall feature? If not, is there any plans to add the said feature?

**Comment by ameshkov** [comment]
Closing this issue as it's a duplicate for #176 

@skudo12 right now it is not possible, but we have this in our future plans.
Yet we need time to implement this.

First of all we'd like to implement firewall "profiles" (you'll be able to set these profiles separately).
Then you'll be able to switch from one profile to another or to link a profile to the device state.

For instance, there will be:
* "Default" profile
* "WiFi" profile
* "Mobile Data" profile
* "Roaming" profile
* "Doze" profile
