### ISSUE TITLE
Enable HTTPS filtering by default for Bromite

### ISSUE THREAD

**Issue by domebacsi** [AdguardTeam/AdguardForAndroid#2680]
Please enable HTTPS filtering by default for Bromite (Chromium-based browser, package name: 
"org.bromite.bromite", https://www.bromite.org/)

**Comment by ameshkov** [comment]
@domebacsi does it support it? You can enable it manually and see if it works okay

**Comment by domebacsi** [comment]
@ameshkov In the past 5–6 months I haven't had any issues, that's why I suggested that you guys should enable it by default

**Comment by ameshkov** [comment]
Got it, thank you! We'll do it in v3.1 then
