### ISSUE TITLE
Do search results in filtering log not include blocked URL which match keywords?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2681]
@ameshkov

Enable `pref.removed.html.log` in low settings of AG for Android.
I type the keywords of blocked URL (Event type: Removed HTML element) in the search of filtering log.
But it shows nothing.

It seems that it only shows requests of request URL and source URL which match the keywords.

It doesn't show requests of blocked URL which matches keywords.

ex: Search cdnjs but show nothing in the filtering log.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/bsN9u0g.png)

![image](https://i.imgur.com/AX2Cg03.png)

![image](https://i.imgur.com/7kym5S1.png)

</details><br/>

**Comment by lancelot-moon** [comment]
In the filtering log of AG for Windows, only there are requests of request URL and source URL.
So if I search cdnjs, those requests can be shown.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ilC1Pej.png)
</details><br/>

**Comment by Revertron** [comment]
![Screenshot_1554467646](https://user-images.githubusercontent.com/105154/55628011-e1298a00-57af-11e9-9ea8-2b8280e27a28.png)
In my test it is Blocked, not Removed. And it is shown in a search.

**Comment by lancelot-moon** [comment]
@Revertron

Try to enable `pref.removed.html.log` in low settings.
Go to visit https://www.linetv.tw/drama/10052/eps/1.
You'll see that request of Event type: Removed HTML element.

@AdamWr
Maybe need Taiwanese IP.
May you help?
Thanks.

**Comment by Revertron** [comment]
I couldn't repeat this with cdnjs, but with pagead2 I see this problem.
I think it is a bug.

**Comment by lancelot-moon** [comment]
Yes, it's ok.
Just try to type **keywords in the Blocked URL** of any requests whose Event type: Removed HTML element in the filtering log.
(First enable pref.removed.html.log in low settings.)

Thanks for your confirmation.
I think it's bug, too.

**Comment by Revertron** [comment]
Fixed.
Testing:
1. Enable pref.removed.html.log in low settings of AG for Android.
2. Go to https://www.linetv.tw/drama/10052/eps/1
3. I type the keywords of blocked URL (Event type: Removed HTML element) in the search of filtering log, such as "cdnjs" or "pagead2". Some of removed HTML events must be shown.
