### ISSUE TITLE
Update to CoreLibs 1.3.261

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2682]
@adbuker commented on [Fri Apr 05 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2560)

* [Fix] Added some assertions for ensuring that socket logic now works perfectly
* [Fix] Upload interrupted in Safari but keeps going in Adguard: AdguardTeam/CoreLibs#615
* [Feature] Add method for receving CoreLibs version in runtime

**Comment by Revertron** [comment]
Done.
