### ISSUE TITLE
Allow AdGuard to add itself to device admins

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2683]
Reported by user 2155045,

"добрый! добавьте возможность вносить
адгуард в список администраторов
устройства, а то переодически при
нехватке памяти система убивает
адгуард(("

**Comment by zzebrum** [comment]
@akmLaVx лучше всего пользоваться советами из кб для настройки корректной работы приложения в бэкграунде.

**Comment by TPS** [comment]
#1341?

**Comment by zzebrum** [comment]
@TPS kinda! tbh it's not a good solution anyway. Probably I should close it as a dup
