### ISSUE TITLE
Support Links Not Working in Bromite

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#2685]
### Steps to reproduce
1. Select Support menu
2. Select any Support submenu
3. Browser opens with no link redirection

This may be related to Bromite's focus on security and privacy. I have not tested this on another browser.

### Expected behavior
Selecting any link (FAQ/Discuss/Send Feedback) in the support menu should open their respective page in web browser.

### Actual behavior
Selecting any link in the support menu opens to a blank page in Bromite browser. Other browsers are untested.

### Your environment

* Adguard version: 3.0.310n
* Adguard filtering mode: VPN
* Device model: OnePlus 6
* Operating system and version: Oxygen OS 9.0.4
* Rooted: Yes
* Any other apps that can start VPN/Antiviruses/Cleaners etc.: No

**Comment by jslawler** [comment]
Issue isn't with AdGuard - latest Bromite update broke link redirection.

https://github.com/bromite/bromite/issues/279

**Comment by ameshkov** [comment]
Yeah, the issue sounded weird indeed:)
