### ISSUE TITLE
AG v3.0.310η constantly crashed when importing settings of v3.0.310η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2687]
Before reinstalling AG v3.0.310η, I exported settings of v3.0.310η.
But AG v3.0.310η constantly crashed when importing settings.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/o3phZCN.png)
</details><br/>

I'm unable to import settings.
Oh my God, I want my user filter back.
Please help me.

@ameshkov 
Do you need the settings file for reproducing?
Please contact with me on telegram if you need it.
Thanks.

**Comment by ameshkov** [comment]
> Oh my God, I want my user filter back.

Check what's inside the backup file, you can restore user filter from there.

We might need to get your backup file, could you please send it to devteam?

**Comment by lancelot-moon** [comment]
I just sent my settings file to `devteam at adguard.com`.

Hope the crash can be solved.
BTW, please update app's translations in the next nightly version.
Thanks.

**Comment by ameshkov** [comment]
@admitrevskiy 
Please find the logs in our NextCloud
