### ISSUE TITLE
Certificate error with Mi Browser (by Xiaomi)

### ISSUE THREAD

**Issue by ronildo66** [AdguardTeam/AdguardForAndroid#2688]
I have an Xiaomi Mi5 for 2 years, since always I used the a Google Chrome downloaded through the Play Store with AdGuard.

This week I tried to use the default browser called "Mi Browser" Version: 10.5.6-g (updated) but all the https pages I tried to access had the following error:

> **Security warning**
> 
> There are problems with the security certificate for this site.
> 
> Continue | View certificate | Go back

I was able to resolve the issue by disabling HTTPS filtering for "Mi Browser" in AdGuard> Apps Management

But I'm not satisfied, I would like to use https filtering in this browser. Any idea what might be happening?

I've heard that this happens a lot in default browser from several manufacturers, is it true? I tested the default browser of NoxPlayer 6.2.7.1028 emulator (Android 7.1.2) with AdGuard and was the same problem.

### Your environment

* Adguard version: **3.0.297**
* Adguard filtering mode: **Local VPN**
* Device model:  **Xiaomi Mi5**
* Operating system and version: **Android 8.0.0**
* Root access: **No**
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: **No**

Thanks!

_Originally posted by @ronildo66 in https://github.com/AdguardTeam/AdguardForAndroid/issues/2538#issuecomment-480674475_

**Comment by TheHasagi** [comment]
@ronildo66 

Hello!

Before the update HTTPS filtering was a little bit broken, so, for now, you can hide this notification (due of Mi browser do not trust user CA) in MI browser - Settings - Privacy & security - Show secure warnings (toggle). Let me know if this help.

**Comment by ameshkov** [comment]
@ronildo66 

Well, the only option is to move the certificate to the system store, and it requires root.

This can be also solved if Mi browser developers add user certificates support.
