### ISSUE TITLE
Minor question about the start date of statistic when newly installing AG.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2689]
I uninstalled and then reinstalled AG v3.0.310η on 8th April.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Xa3jcHO.png)
</details><br/>

But the statistic is from 5th April.
(Maybe it's because the nightly version was made on 5th April.)
Why?
Is it reasonable?
Since I can't import settings, I suppose that the statistic should be calculated from the date which I newly install AG app.

**Comment by zzebrum** [comment]
It's by design to make the statistics graph looks better.
