### ISSUE TITLE
The icon shifts color and size

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2690]
The icon changes its shape when opening the notification drawer, and changes color to green after restarting the protection

### Steps to reproduce

See the screen recording IN NOTES here: 749933

### Expected behavior

The size and color are persistent

### Actual behavior

They change 

### Customer ID 
749933

### Your environment

* Adguard version: 3.0.310
* Adguard filtering mode: VPN
* Device model: Redmi Note 4
* Operating system and version: 8.1.0 (sdk=27)
* Root access:  n/a
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: n/a

**Comment by zzebrum** [comment]
I think it's android :)

@Revertron @admitrevskiy ?

**Comment by Revertron** [comment]
Yep, it's a firmwares "special effects" :)

**Comment by Alexey71** [comment]
Ни в одном приложении кроме гварда такого бага нет. Так что проблема в приложении
