### ISSUE TITLE
AdGuard crashes on cdaction.pl

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#2692]
AdGuard crashes everytime I visit this website - https://www.cdaction.pl/
### Steps to reproduce

1. Go to this website - https://www.cdaction.pl/ and wait a moment.

### Expected behavior

AdGuard shouldn't crash.
### Actual behavior

AdGuard crashes.

### Your environment

* Adguard version: 3.0.310n (1.3.261cl)
* Adguard filtering mode: Local VPN
* Device model: Samsung Galaxy S9
* Operating system and version: Android 9
* Root access: No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: -

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #850](https://github.com/AdguardTeam/CoreLibs/issues/850) via [**ZenHub**](https://www.zenhub.com/)
