### ISSUE TITLE
[FEATURE REQUEST] Default period selection

### ISSUE THREAD

**Issue by sam20e** [AdguardTeam/AdguardForAndroid#2694]
Hi guys

On my main screen there is a summary like how many ads blocked etc. By default it's showing the entire count - all time. 

I can change this from the drop down to show today's stats, but when I switch/re-open the app it's getting reset to all time.

I'd like to see the daily stats whenever I open the app. Is it possible for me to set a default view? 

Please see attached screenshot - https://www.dropbox.com/s/cnflobav40omabl/2019-04-09_08-24-05.png?dl=0

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2516
