### ISSUE TITLE
AdGuard app requests are not appearing

### ISSUE THREAD

**Issue by sebast889** [AdguardTeam/AdguardForAndroid#2697]
With AdGuard protection turned on for the AdGuard app the filtering log should show all the requests made by the app but none of the requests it makes are showing up.

**Comment by ameshkov** [comment]
We had to add AG to exceptions for now. Otherwise, it was leading to infinite recursion and complete internet breakage.

I guess we need to indicate this in the UI somehow.

**Comment by sebast889** [comment]
Is AG the only exception or are there others? I feel there should be a pref where the user can see and edit exceptions if they want to similar to the HTTPS filtering list.

**Comment by ameshkov** [comment]
It's the only exception, all others can be filtered.

**Comment by ameshkov** [comment]
> I feel there should be a pref where the user can see and edit exceptions if they want to similar to the HTTPS filtering list.

Hm, this makes sense btw

**Comment by TPS** [comment]
Now #2700?
