### ISSUE TITLE
Indicate in the UI that AG cannot filter itself

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2700]
Enabling filtering for AG itself was leading to multiple issues so we had to add it exceptions. We should find a way to indicate this in the UI (or we might need to simply remove AG from the filtered apps list).

We could also add a low-level flag that controls if AG is excluded or not.

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Go to `Apps Management` -> `AdGuard`


Expected result:
- You will see warning about AG not being able to filter itself
- AG settings cannot be changed
