### ISSUE TITLE
суицид

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardForAndroid#2701]
Такое дело, ~не думаю, что это баг, наверно я опростоволосился,~ @ameshkov  @Alex-302 скачал тут недавно вашу программу на ведройд, не та что в марките, а та что на оф. сайте, так вот заблокировал я значит n количество не понравившихся мне адресов. Все для личного использования. Сделал 2 листа. Все адреса в 1 списке, которые я заблокировал DNS. Все не DNS во 2.

Синтаксис 1 листа:
`||говенныйсайт.ком^$app=com.adguard.dns,important`

Синтаксис 2 листа:
`||говенныйсайт.ком/говеннаястраница^$script,important`

Сделал экспорт, (в пользовательском списке все работало!), добавил на сайт, скопировал и вставил в ведройде куда следует, подписки появились и все было бы круто, однако 1 список просто отказывается работать. Проблема только с DNS листами, обычные работают.
Вопрос, что это за магия?
Где об этом можно прочитать? В пользовательских списках вообще не работает DNS, так задумывалось? В чем подвох, что я не так делаю?

PS: у меня триал версия, пока думаю строит ли тратить шекели ~или качать крякнутые~ :rofl:
PSS: Обновлял фильтры несколько раз.
PSSS: Рут есть.

***
И второй вопрос, просто интересно, эм, по моему, ~я точно не уверен. так как я не захожу в маркет уже давно~ года 2-3 назад ваше приложение было в марките, ~тогда еще, вместе с вашим приложение было нормальное приложение от adblockplus, правда работал от рут, а не то что сейчас - говеный браузер от adblock plsu~ что случилось сейчас? Когда богопротивный гугл изменил правила и выпилил неугодные ему приложения с маркета? И почему вы не пишите в описании своего приложения, **тот что в маркете**, что у вас есть еще одно приложение, которое у вас на сайте? Судя по комментариям ~люди не прочли, что блокируется только в яндексбраузере и самсунге~ люди хотят именно, то приложение которое блокирует везде рекламу, т.е то приложение которое на сайте.

~PS: хотя с другой стороны если они не прочли, что реклама блокируется, только в яндекс и самсунге вряд ли они прочтут, что у вас есть еще одно приложение~

Собственно все.

**Comment by ameshkov** [comment]
Про DNS: кастомные подписки не применяются к DNS запросам (пока что). Сейчас применяется только AdGuard SDN filter (неявно) и то, что в пользовательском фильтре. В будущих версиях мы вообще разделим DNS-листы и обычные -- то что они пересекаются это не очень верно. Вот в этой задаче все: #1851 

Но в целом DNS это не круто, обычные блокирующие правила гибче, ведь их можно конкретными приложениями ограничивать.

> года 2-3 назад ваше приложение было в марките

В маркете у нас только была версия ограниченная браузерами, но и ее не дали там держать и выкосили на пятый день после релиза. У гугла эти правила года с 2012.

> PS: у меня триал версия, пока думаю строит ли тратить шекели или качать крякнутые 🤣

Мы разработчикам фильтров ключи нахаляву всегда выдаем, ну чо вы.

> И почему вы не пишите в описании своего приложения, тот что в маркете, что у вас есть еще одно приложение, которое у вас на сайте? 

Гугл запрещает такое писать.

> PSSS: Рут есть.

Ну кстати VPN режим то ничем не хуже (а то и лучше) чем рутовый. Но с рутом можно сертификат в системные перенести и залезть в кишки запросов обычных приложений, а не только браузеров.

Чтобы посмотреть детально на данные которые приложения шлют можно включить запись HAR-файла в low-level настройках.

**Comment by bogachenko** [comment]
окей спасибо
