### ISSUE TITLE
Adguard not appearing in recent app list

### ISSUE THREAD

**Issue by duplex143** [AdguardTeam/AdguardForAndroid#2702]
I'm using OnePlus 5 running Oxygen OS 9.0.4.
I've tested with various launchers.
### Steps to reproduce

1. Open Adguard app.
2. Close it using home button.
3. Open recent apps list.

### Expected behavior

It should be there.
### Actual behavior

Adguard isn't there.

<details><summary>Screenshot:</summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24863030/55941223-6ce36080-5c5f-11e9-8695-9184de09690a.gif)

</details>

### Customer ID 
1708920

### Your environment

* Adguard version: 3.0.297
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual))
* Device model: (e.g. Google Pixel) OnePlus 5
* Operating system and version: (e.g. Android 7.1.2) Oxygen OS 9.0.4 based on Android 9
* Root access:  (e.g. Yes / No) No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: No

**Comment by zzebrum** [comment]
@duplex143 did you try to restart your device? It helped me once in the same situation (:

**Comment by patrickdrd** [comment]
I've run into this issue myself from time to time and I think the answer is obvious:
adguard isn't set to remain in recent apps somehow, based on its implementation,
I mean it isn't "minimizable", I don't know how to describe it better, 
but when I open if and minimize it I wouldn't rely on it staying there until I close it,
I don't know why it was created that why either, but personally I wish it had the default behavior

**Comment by duplex143** [comment]
> @duplex143 did you try to restart your device? It helped me once in the same situation (:

It clearly is a bug. At times I want to tweak some settings seeing from Android Chrome browser. When I open chrome, copy/remember something, I can't open Adguard from recents (In oxygen OS, double tapping on recents can be set to open last closed app) directly. I need to open Adguard from app list. It really is very frustrating.

**Comment by zzebrum** [comment]
ok, we will check in a couple of days on our Oneplus device )

**Comment by duplex143** [comment]
@zzebrum bump
