### ISSUE TITLE
APKPure ß App has unblocked ads

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#2703]
The APKPure app, since recent versions, has unblocked ads, especially upon launching.
### Steps to reproduce

1. Download ß app from https://m.apkpure.com/apkpure-app.html & install
2. Open app.
3. If wished, browse around.
4. Check AG log.

### Expected behavior

No ads, no counter, & blocks shown in AG log.

### Actual behavior

An opening intersticial ad appears, complete w/ timeout counter.  When checking AG log, not much useful info appears to help block it.

Screenshot: Can't upload example of actual ad 😕

</details>

### Customer ID 

1122984
### Your environment

* Adguard version: 3.0.311η
* Adguard filtering mode: Local VPN
* Device model: Moto G5+
* Operating system and version:  Android Oreo 8.1.0
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: 
No

**Comment by zzebrum** [comment]
@TheHasagi try to repro, move to filters repo if needed.

**Comment by TPS** [comment]
I think I've solved this for myself.  Firstly, I *en*abled HTTPS Filtering for the app, which seems to show more requests in the AG log related to it, w/o affecting functionality!  Then I tried the following filters.  (I don't know whether any are redundant or irrelevant, or *dis*abling HTTPS Filtering for it would work):
````
||zcoup.
54.179.191.158$network
||a.pureapk.com^
||admarvel.

**Comment by lancelot-moon** [comment]
This isn't app's issue and should be moved to filters repo.

**Comment by TPS** [comment]
I wasn't sure, because of that № 1 step of first toggling the defaulted HTTPS Filtering.

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers guys, could you please take a look?

**Comment by Alex-302** [comment]
@TPS please make screenshot of ads.
admarvel must be blocked by mobile filter.

**Comment by TheHasagi** [comment]
Unable to reproduce. Please, download or update to the release version 3.0.297.

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardFilters #32867](https://github.com/AdguardTeam/AdguardFilters/issues/32867) via [**ZenHub**](https://www.zenhub.com/)
