### ISSUE TITLE
Improvements for Data saved card on Home screen 

### ISSUE THREAD

**Issue by sam20e** [AdguardTeam/AdguardForAndroid#2704]
Hello,

Currently, when you open adguard, you can see the "Data Saved" stats. I believe it's a combination of data saved through Mobile data and Wi-Fi. 

To be honest, no one really worry about Wi-Fi data. Lets say if I only have 3GB Mobile data bundle (data bandwidth) every month I'll be more concerned about my Mobile data usage. 

2 different request :

1) Can you add a new setting, where we can select if we want to display only the amount of data saved through Mobile Data?

i.e. lets say if i want to display only saved Mobile Data, i will tick this setting and home screen "Data Saved" total stat will only show my saved Mobile Data. I will not include Wi-Fi stats.

2) If not, another alternate method, can you add one more Home Screen line to your Data Saved Stats? like

Data Saved through Mobile Data  : 2GB
Data Saved through Wi-Fi  : 4GB

Just an idea, this way your clients will know how much Mobile Data they saved in total at a glance.  Right now we have to go to app management and filter these stats.

Cheer

**Comment by artemiv4nov** [comment]
Hmm, this functionality has been replaced to full-feature statistics, let's close this task
