### ISSUE TITLE
Notification about Premium Version Adguard Android

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardForAndroid#2705]
Hello, 
Every Day I see notification like that :
![Screenshot_2019-04-12-09-54-53](https://user-images.githubusercontent.com/16944478/56050650-b9f13080-5d4c-11e9-8704-b3307ef55d15.png)
I don't see any button for turn off that notification. 
If it possible add option for deactive that monit? 

Best Regards
seba2282

**Comment by duplex143** [comment]
1)You can block Adguard notifications altogether in system settings.
2)If you are in Android pie, you'll have notification categories. You can turn them off individually.
3)Check if you can turn off notifications of this particular type in adguard notification settings.

**Comment by seba2282** [comment]
I turned off all notification in App and only that showed me. I want have notification about when app restart or how much is blocked ads only that want block. Suggest, how can turn settings in App or system Android 6.0 in Huawei P8 Lite (2015) for turn off only that notification?

**Comment by zzebrum** [comment]
@seba2282  
1. how many days exactly since you've installed the app?
2. the notification is always the same?

**Comment by seba2282** [comment]
I use few days after how Adguard Extension on Firefox started crash me (that Extension is actually turn off in browser and wait for fix). 


I had one every day, but now see is calm and didn't see today. If will show today I will write.

**Comment by zzebrum** [comment]
@seba2282  after 10 days, the notification will stop showing up.

**Comment by seba2282** [comment]
Thanks for concrete informations. 🙂

**Comment by zzebrum** [comment]
reopen if things'll go unexpectedly )
