### ISSUE TITLE
Blocking page flashed when using $popup modifier.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2709]
I added `||eprice.com.tw^$popup` in the user filter.

When visiting the website by mobile browser, the blocking page flashed.
https://m.eprice.com.tw
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/QzN7iI1.png)
</details><br/>

1. Blocking page flashed when using $popup modifier.
Is it your design?
The flash blocking page becomes an **annoyance** when visiting somewhere on the website every time.

2. But it's blank in the field of filter rule.
Is it normal?

**Comment by ameshkov** [comment]
Merged here:
https://github.com/AdguardTeam/CoreLibs/issues/875
