### ISSUE TITLE
The notification for protecting AdGuard from being disabled by the system showed even if already setting them.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2711]
https://kb.adguard.com/en/android/solving-problems/background-work#Xiaomi

After setting these steps for protecting AdGuard from being disabled by the system, a Xiaomi user reported that the notification of `The battery saving method of your system can influence AdGuard's functioning` still showed, which annoyed users.

Xiaomi Note 4X
MIUI 10

**Comment by Revertron** [comment]
It means, that the system is ignoring those settings, and we are detecting that it kills AdGuard anyway.

**Comment by lancelot-moon** [comment]
The user told that AG wasn't killed.
He already did those configurations for protecting AdGuard from being disabled by the system according to you KB.

The notification should not be shown anymore.
But it appeared when AG still normally worked.

**Comment by zzebrum** [comment]
@lancelot-moon to be absolutely sure whether AdGuard was killed or not we need to see logs. Can you do that?

**Comment by lancelot-moon** [comment]
No, it's not my issue.
Just another Taiwanese user reported this.

https://www.ptt.cc/bbs/Android/M.1555559027.A.6B4.html

**Comment by zzebrum** [comment]
@lancelot-moon ok, can you suggest to this user contact our support team? or just redirect him to this thread.

**Comment by TheHasagi** [comment]
This notification can be managed from the system notifications settings and does not apply to AdGuard. Closed.

**Comment by Eugene-Savenko** [comment]
@zzebrum you can find the logs here: 2185868

**Comment by TheHasagi** [comment]
Customer did not respond. Closed.

**Comment by Eugene-Savenko** [comment]
He responded 3 days ago:

I still have the same notification issue.

**Comment by artemiv4nov** [comment]
>This notification can be managed from the system notifications settings and does not apply to AdGuard. Closed.
