### ISSUE TITLE
AG breaks captive portals authentication

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2713]
### Steps to reproduce

1. Connect to Wi-Fi hotspot that has some captive portal
2. Android will ask you if you want to sign in
3. Agree and try to sign in

### Expected result
You should see the captive portal

### Actual result
White empty page

### Logs
Uploaded to the private nextcloud

**Comment by ameshkov** [comment]
To fix this we should simply disable filtering for `com.google.android.captiveportallogin`.

**Comment by rWolstenholme** [comment]
AOSP/MIUI uses `com.android.captiveportallogin`, I think for the same reasons it should treated similarly

**Comment by ameshkov** [comment]
@rWolstenholme makes sense, thank you! We'll add it to the default exceptions list.

**Comment by frider-balzke** [comment]
Ich hoffe es funktioniert sehr gut !!!

**Comment by frider-balzke** [comment]
Ich habe eine große Hoffnung in diese Software!!!

**Comment by noteocupo1234-png** [comment]
> ### Pasos para reproducir
> 1. Conéctate a un punto de acceso Wi-Fi que tenga algún portal cautivo.
> 2. Android te preguntará si quieres iniciar sesión.
> 3. Acepta e intenta iniciar sesión.
> 
> ### Resultado esperado
> Deberías ver el portal cautivo
> 
> ### Resultado real
> Página blanca en blanco
> 
> ### Registros
> Subido a la nube privada de Nextcloud.

### Steps to reproduce

1. Connect to Wi-Fi hotspot that has some captive portal
2. Android will ask you if you want to sign in
3. Agree and try to sign in

### Expected result
You should see the captive portal

### Actual result
White empty page

### Logs
Uploaded to the private nextcloud

**Comment by noteocupo1234-png** [comment]
[](url)

[f.txt.json](https://github.com/user-attachments/files/29933133/f.txt.json)
