### ISSUE TITLE
Sporadic loss of internet connection

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2714]
### Steps to reproduce
1. Enable the protection
2. Websites you visit / apps you keep open will lose connection sporadically

### Expected behavior
AdGuard shouldn't affect internet connectivity

### Actual behavior
Sometime the connection just breaks

### Customer ID & Logs
2123995
Issue is ongoing, multiple logs available.

### Your environment
* Adguard version: started on 3.0.242, current is 3.0.315n
* Adguard filtering mode: Local VPN, high-quality, AdGuard used as outbound proxy for Orbot / NordVPN
* Device model: Xiaomi Redmi 3
* Operating system and version: Android 5.1.1
* Root access: No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: Orbot / NordVPN (only used as outbound proxy)

**Comment by TheHasagi** [comment]
@akmLaVx 

Looks like AdGuard or Orbot is restricted to work in the background. You should ask a customer to check the app's background rights.

**Comment by TheHasagi** [comment]
The issue has gone. Unable to reproduce it anymore. Closed.
