### ISSUE TITLE
Is split DNS possible?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2715]
@ameshkov 

In the past, I supposed that it can use different DNS service under split VPN.
But it seems that I was wrong.

https://www.expressvpn.com/support/troubleshooting/split-tunneling-desktop/

> What happens to my DNS queries when I use split tunneling?
As long as you are connected to ExpressVPN, all of your DNS queries will go through ExpressVPN’s servers, no matter how you configure your split-tunneling settings.

Well, I tried to enable AG DNS module and disable AG protection for some apps in AG's app management.
Generally, DNS filtering can block their ads without HTTPS filtering.
Most apps' ads were still blocked on DNS level even if disabling AG protection for them in app management.

1. But 1 app's ads appear when disabling AG protection for it in app management.
I feel doubtful if all of DNS queries will go through AG VPN, no matter how we configure our split-tunneling settings.

2. Is it possible to implement split DNS?

3. If split DNS is possible, need to notice that AG VPN also uses system DNS (with DNS filtering) when apps without AG protection use system DNS (without DNS filtering).
Mess up?

**Comment by ameshkov** [comment]
This article is not applicable to Android.

> Generally, DNS filtering can block their ads without HTTPS filtering.

Most likely because these ads are loaded by google play services which are still filtered.

**Comment by lancelot-moon** [comment]
Is split DNS available for AG for Windows/Mac?

**Comment by ameshkov** [comment]
AG for Windows/Mac are not VPN providers

**Comment by ameshkov** [comment]
Tbh, I really don't see what's so special about that stuff. This article is simply about choosing which apps are routed through the VPN.
