### ISSUE TITLE
Items are not highlighted on tap

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2716]
I am talking about these:

![](https://uploads.adguard.com/up04_tjpns_Monosnap.png)

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-Reinstall AG
-Examine dialogs with single choice (Time period  for statistics, language selection, filters update period, update channel, etc)

Expected result:
- Items are highlighted on tap
