### ISSUE TITLE
App gets through Adguard VPN

### ISSUE THREAD

**Issue by jonathanmmm** [AdguardTeam/AdguardForAndroid#2717]
Hi,

On one device (LG G5 H850 Android 8.0.0)

I have disabled WhatsApp through adguard with taking away wifi and Mobile Data. Maybe adguard gets killed or Something?
Want to use the Phone while being offline on WhatsApp.

We are trying know through the VPN Android system setting to enable adguard with "enable all the time" and "block Connection without vpn" maybe it is then resolved.

Adguard autostart when device is powering on is Off (but device does Not restart).

Low Level settings are Standard.
(Should I Change There Something that If vpn does Not Work all Connections are Blocked or the corresponding system setting is Set?)

Checking-time (If adguard runs) is disabled. I believe this is Default.

Adguard Version: v3.0.291 (1.3.207cl) free Version.

**Comment by ameshkov** [comment]
> I have disabled WhatsApp through adguard with taking away wifi and Mobile Data

It is staying disabled. However, you might be getting new messages notifications because Whatsapp receives them from [GCM](https://developers.google.com/cloud-messaging/), i.e. these notifications are loaded by a different app.

**Comment by jonathanmmm** [comment]
But GCM should inform WhatsApp that new messages are available. Not downloading them. Because WhatsApp encryptes the messages end to end GCM should not be able to download and encrypt the messages for WhatsApp, right? Or does WhatsApp sends the message through GCM and gives it locally to the App API (or so) which then shows me the message?

I believe WhatsApp somehow gets around the vpn, because adguard is shortly disabled/crashed or so.

**Comment by jonathanmmm** [comment]
Maybe GCM (or now called FCM) is the reason. But disabling GCM internet connection would result in all kinds of apps not recieving notifications.

**Comment by ameshkov** [comment]
> Because WhatsApp encryptes the messages end to end GCM should not be able to download and encrypt the messages for WhatsApp, right? Or does WhatsApp sends the message through GCM and gives it locally to the App API (or so) which then shows me the message?

They might be sending encrypted messages through it.


> Maybe GCM (or now called FCM) is the reason. But disabling GCM internet connection would result in all kinds of apps not recieving notifications.

Yeah, and that's quite a problem.

> I believe WhatsApp somehow gets around the vpn, because adguard is shortly disabled/crashed or so.

If you're on Android 8 or newer, you can configure AG to be "always-on" and restrict other apps to access the internet without VPN. This way you will guarantee that nothing avoids being filtered.

**Comment by jonathanmmm** [comment]
That always-on is which I described above which we will test.
But more complicated to go into settings, switch bove on instead of toggling the adguard symbol in the notification tray (where flightmode and so on is)

**Comment by ameshkov** [comment]
So do you see new messages notification when always-on + block connections without vpn?

**Comment by TheHasagi** [comment]
Issue closed. Will be reopened if needed.
