### ISSUE TITLE
AdGuard rotate mode issue

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2721]
Steps to reproduce:

Enable rotate mode on the phone.

AdGuard - Send Feedback - Bug report:

Fill the columns with text and rotate the phone.

Rotation issue, see the screenshots above:

<details>

![img](https://uploads.adguard.com/TheHasagiho67j.jpg)

![img](https://uploads.adguard.com/TheHasagi5z6ye.jpg)

</details>

**Comment by admitrevskiy** [comment]
Done.
