### ISSUE TITLE
Notify user about certificate errors

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#2722]
The 2 types of certificate issues are added in https://github.com/AdguardTeam/CoreLibs/issues/868 and we have the opportunity to notify user if there is a problem with certificates on some domain or some application is not trusting our certificate.
The user can disable HTTPS-filtering for that app or try to add server's certificate to user store.

**Comment by jslawler** [comment]
I'm showing interest in this as I was about to raise this issue.
From Magisk 17 there has been issues with loss of root which was meant to be getting fixed in 19.2, however yesterday I lost root again, and in turn was not notified by AG of the certificate issue.

**Comment by ameshkov** [comment]
@Revertron assigned to v3.2

**Comment by TPS** [comment]
`pref.notify.on.unknown.ca`, right?

**Comment by ameshkov** [comment]
@TPS yep, that's right
