### ISSUE TITLE
Bypass/remove AMP sites?

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2723]
### Expected behavior

A great feature would be the ability to shut off AMP sites. The only thing that would need to be done by adguard is to remove /amp/ from the URL. So when adguard sees (for example):
https://www.blah.com/amp/something/73737.htm 

it could just convert the URL to :
https://www.blah.com/something/73737.htm

APM sites  often remove the comments section and while it's easy to go to the URL bar and remove it yourself it would be awesome if adguard could do it for me lol 

Especially because every url..or almost every URL that you click in Google Now automatically goes to the AMP site so stripping that from the URL would fix the issue.

Another problem I've found with AMP sites is they ignore any settings you might have setup for the regular site. One example is dark/night mode but there are more.

**Comment by ameshkov** [comment]
This can be achieved by a simple userscript.

Once we add full userscripts support to AG for Android, we should create one for this.

**Comment by artemiv4nov** [comment]
Done in #2815

**Comment by patrickdrd** [comment]
can somebody give an example to see if and how it works?

**Comment by ameshkov** [comment]
> can somebody give an example to see if and how it works?

https://moz.com/blog/accelerated-mobile-pages-whiteboard-friday

Currently, AG can suppress AMP pages on Google search results page only.

**Comment by patrickdrd** [comment]
> AG can suppress AMP pages on Google search results page only

yes, I need an example of that to see how it works with this extension enabled and without it,
I searched but I couldn't find one,
e.g. tell me search on google for.. what?
and check the result.. which?

**Comment by ameshkov** [comment]
> e.g. tell me search on google for.. what?

Here's how it looks like:
https://uploads.adguard.com/up04_grcde_what_is_amp_pages_-_Google_Search.png

There are quite a lot of AMP pages so whatever you're googling, you'll find one in the search results

**Comment by patrickdrd** [comment]
ok, so I run the google search for accelerated mobile pages, I reach to the result in the screenshot you posted (with the thunder) and
I open it (with disable amp enabled),
then I open adguard, I disable "disable amp" refresh the google search page and I hit the same result,
I can't notice any difference!

**Comment by ameshkov** [comment]
> then I open adguard, I disable "disable amp" refresh the google search page and I hit the same result,

You might need to clear the cache as well

**Comment by patrickdrd** [comment]
nah, I cleared it and launched the page many times with and without "disable amp",
I'm seeing the same page each time,
I think I'm seeing the amp page,
can you do it and post the two screenshots of the page?

**Comment by ameshkov** [comment]
Normal page:
![2019-07-11 16 48 19](https://user-images.githubusercontent.com/5947035/61056274-b62c8300-a3fb-11e9-995f-be7733da2a5e.jpg)

AMP page:
![2019-07-11 16 48 14](https://user-images.githubusercontent.com/5947035/61056275-b62c8300-a3fb-11e9-9a4d-153e56101424.jpg)

**Comment by patrickdrd** [comment]
thanks, I understood that I can see if a page is an amp page by viewing its link,
one of these screenshots show that it is google.com/amp url,
anyway, no matter what I tried I cannot get amp pages to show,
and this is what I've tried:

I disabled "disable amp", I even deleted it completely (!),
I cleared chrome's cache and forced close chrome,
I searched in chrome for "accelerated web pages" and 
I opened 10 links with a thunder next to them,
I didn't see a single url with google.com/amp!

**Comment by ameshkov** [comment]
Maybe you have custom user-agent configured in the stealth mode settings

**Comment by patrickdrd** [comment]
nope, neither this nor blocking graph.facebook.com for these apps, I've sent my settings at support@adguard.com as alexander said
