### ISSUE TITLE
 Development wishes from user

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2726]
### Steps to reproduce

1."Would you consider including Hosts file blocking in a future version as an alternative to the VPN blocker?"
2."Could you make it easier to disable just the filters whilst keeping the Adguard DNS active, from the home screen? (one button in the main menu to disable all filters but leave the DNS)"
3. Is there any chance you could add Steven Black's host's file to the default filter list selection on the app?

**Comment by lancelot-moon** [comment]
Honestly, your requests are duplication.
1. AG team had answered that they'll design filters subscription for DNS filtering in future version for several times.
Maybe v3.2 or delay...

2. I ever suggested the similar idea, but Andrey refused:

> I don't want to help users get worse ad blocking and let them transform AdGuard into an inferior ad blocker.

> It does not matter. With or without HTTPS filtering, what AdGuard does is better than what DNS-level ad blockers can do. I can't see why should we make it easier for users to make AdGuard worse than it is.

https://github.com/AdguardTeam/AdguardForAndroid/issues/2615

3. Steven Black's hosts file isn't popular now.
We have suggested other hosts files as the default lists for future version.
