### ISSUE TITLE
Return the option to test proxy connectivity before attempting connection

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2728]
As reported by user 1212839

Before 3.0, AdGuard was able to test proxy connectivity before connecting to any proxy server - you just had to long-tap a proxy name in proxy servers list, and AdGuard would test everything for you. Since 3.0, this feature is missing.

**Comment by Yevhen1996** [comment]
Would it be also possible to show the proxy connectivity status in the slide menu? something like here: https://uploads.adguard.com/IMG_20190501_054707.jpg

**Comment by TheHasagi** [comment]
It is available.

![img](https://uploads.adguard.com/TheHasagiol6by.jpg)

**Comment by lancelot-moon** [comment]
@TheHasagi 
https://github.com/AdguardTeam/AdguardForAndroid/issues/2122

**Comment by Eugene-Savenko** [comment]
@TheHasagi вопрос вот в чем:

> Плюс к тому, что сейчас проверить соединение можно только после включения прокси, отредактировать прокси тоже можно только после включения, в предыдущих версиях гуард всё это делалось без подключения и проверка и редактирование и удаление.

Просьба протестировать должным образом и сообщить нам результат.

**Comment by Eugene-Savenko** [comment]
Another report here: 1102858

> I am not able to test whether a proxy connection is working or not when the proxy setting is disabled. I was able to test even when the proxy setting is disabled before the last major update.

**Comment by artemiv4nov** [comment]
@Eugene-Savenko This option is available on the latest versions of AgGuard
