### ISSUE TITLE
[Broken app] com.snailgameusa.tp

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#273]
How to reproduce:
1. Install
https://play.google.com/store/apps/details?id=com.snailgameusa.tp&hl=ru
2. Run and wait for downloading recources
3. The app will stop responding after status bar is 100%
Screenshots:
http://forum.adguard.com/attachment.php?attachmentid=4120&d=1452450506&thumb=1

**Comment by Alex-302** [comment]
pcap's
https://mega.nz/#!ZI0DkZzT!SXiuyeNg9FKBymYCyGl3UjlQdU1A5rOQRg7M50dKrHA

**Comment by Revertron** [comment]
On 100% of downloading of the data pack it has some pause. If you wait about 20-30 seconds it will work normally.
