### ISSUE TITLE
May you not bundle outmoded filters locales in APK?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2730]
I reinstalled the latest nightly APK.
I found filters locale (zh-TW) in APK are outmoded.
Well, we can still check for updates.
Then filters locales can be synchronized with server and kept the latest.

But the latest filters locales are compiled on GitHub.
I think you can bundle the latest locales in APK or installers of AG for PC.

This isn't important...
Please ignore if bothering you.

**Comment by ameshkov** [comment]
Well we should bundle some version anyway.
