### ISSUE TITLE
DNSCrypt

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#2731]
I see this is an option when using Adguard under DNS filtering but not for Cloudflare - do you think this could be implemented as they are supporting DNSCrypt?

**Comment by admitrevskiy** [comment]
Hi!
If you mean the following stamp from [download.dnscrypt.info](//download.dnscrypt.info/dnscrypt-resolvers/v2/public-resolvers.md): 
```
sdns://AgcAAAAAAAAABzEuMC4wLjGgENk8mGSlIfMGXMOlIlCcKvq7AVgcrZxtjon911-ep0cg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk
```
It's actually DNS-over-HTTPS (you can check it with [online tool](https://dnscrypt.info/stamps)).
