### ISSUE TITLE
Allow user to configure app internet access even when app currently has no internet permission

### ISSUE THREAD

**Issue by sebast889** [AdguardTeam/AdguardForAndroid#2732]
All apps which currently don't have internet permission are not shown at all in AdGuard UI. This is not good as new updates to apps can introduce internet permissions without the user even knowing. It's better to show those apps so that the user can deny internet access to them so it doesn't matter even if new updates introduce internet permissions for the app.

**Comment by TheHasagi** [comment]
The direct meaning is to show the apps that have the ability to access the internet otherwise, there will be too many of them. For example in MIUI/EMUI.

**Comment by ameshkov** [comment]
Marked as feature request with low priority

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
