### ISSUE TITLE
Add the DNS server address to the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2735]
The problem is that users cannot check if the DNS request was made to the configured upstream, or to the fallback server.

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
-Reinstall AG
-Enable DNS module
-Serf the web
-Go to the Filtering Log -> select any `processed` event
-You will see DNS Upstream in the event details screen

**Comment by TheHasagi** [comment]
Not solved.

**Comment by admitrevskiy** [comment]
Done. 
@TheHasagi  please check it in the next build.
