### ISSUE TITLE
AdGuard v3.0.359η crashed while trying to make rules from the filtering log.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2737]
AdGuard v3.0.359η crashed while trying to make rules from the filtering log.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/G1gkDTs.png)
</details><br/>

**Comment by sfionov** [comment]
Hello! I can't find your crash. Do you have crash reporting enabled? If yes, can you please say send standard logs archive to devteam@adguard.com ?

**Comment by lancelot-moon** [comment]
I surely enabled auto crash report.
Strange.

I'll send the log to that email address soon.

**Comment by lancelot-moon** [comment]
I have sent the log to devteam@adguard.com.
It seems that AG crashed while trying to block request from the filtering log.
In my case, trying to unblock request won't cause AG to crash.

Thanks.

**Comment by lancelot-moon** [comment]
I found a strange thing.
After AG crashed, AG would automatically enable protection when I reopened AG.

I supposed I need to manually enable protection.

**Comment by sfionov** [comment]
@lancelot-moon It is ok. Crash is not related to protection (CoreLibs), so protection was not auto-disabled.

**Comment by L31FY** [comment]
Mine has the behavior if I try to create either kind of filtering rule. Clicking on the block or unblock button triggers a restart of protection and the filtering log is cleared.

**Comment by lancelot-moon** [comment]
Do you still have the problem with AdGuard v3.0.363η?
If you still have the issue, send log (record everything) to the above email address.
Mine seems to be solved.

In my case:
With AdGuard v3.0.359η, AG would crash only when clicking "block" from the filtering log.

Clicking "unclock" wouldn't cause AG to crash.

**Comment by akmLaVx** [comment]
User 2186810 has sent some debug-level logs. They might be of some assistance here.

**Comment by Revertron** [comment]
@akmLaVx It's already fixed in 3.0.363 nightly.

**Comment by L31FY** [comment]
It's still happening in the new build

**Comment by L31FY** [comment]
I did send them a log.

**Comment by ameshkov** [comment]
@Revertron have you received the log?

**Comment by Revertron** [comment]
Nope :(
