### ISSUE TITLE
Separate DNS server IP for Wifi and Mobile data connection

### ISSUE THREAD

**Issue by sz4bi** [AdguardTeam/AdguardForAndroid#2739]
I would like an option to specify the DNS server's IP (or use the IP provided by DHCP) if the device is connected to a specified wifi network and automatically switch back to AdGuard's DNS settings if mobile data is connected.
I am using pihole at home and I have to disable DNS filtering when I am connected to my home network to use it.
Some sort of automatic DNS IP switcher would be nice.

**Comment by ameshkov** [comment]
Temporary solution: use Tasker/Automation - https://kb.adguard.com/en/android/solving-problems/tasker

**Comment by artemiv4nov** [comment]
Well, the real perfect solution is only using our Automation API: for smooth app management it will work better.
