### ISSUE TITLE
Enhance parental control?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2740]
It seems that you will bring parental control to AG for Android.

Is it possible that your parental contronl will be enhanced such like Google Family Link?

https://play.google.com/store/apps/details?id=com.google.android.apps.kids.familylink

Some parents may want to restrict their children’s time of browsing on internet.

Other features in Google Family Link can be for your reference.

**Comment by ameshkov** [comment]
Kinda out of scope

**Comment by lancelot-moon** [comment]
@ameshkov 

At least, when will parental control and password function come to AG for Android/iOS?

**Comment by ameshkov** [comment]
We're not planning to add parental & password protection to Android. Android limits the ways AdGuard can be used in the multi-user environment and it's hard for casual users to overcome these limitations. So it just is not fit to be used as a parental control tool.

**Comment by lancelot-moon** [comment]
@ameshkov Some parents may not want their children to visit adult websites.
Is this not realized by AdGuard for Android/iOS?

**Comment by ameshkov** [comment]
It's too easy to disable this protection for a child. And if you set up a different limited "child" account on Android, you cannot use AdGuard there.
