### ISSUE TITLE
AdGuard fails to block Samsung firmware updates

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2741]
### Steps to reproduce
1. Configure AdGuard as shown below
2. Try to block Samsung's firmware update
3. Won't work

### Expected behavior
Samsung's firmware updates should be blocked

### Actual behavior
Firmware updates bypass the block

### Configuration

Phone settings:
**Always-on VPN**: Enabled
**Block connections without VPN**: Enabled

All Samsung Knox security features are **disabled**

AdGuard rules:
||upd.samsung.com^$app=org.com.sec.android.soagent
||upd.samsung.com^$app=org.com.wssyncmldm

### Customer ID, logs, additional details
1907031

### Your environment
* Adguard version: 3.0.368
* Adguard filtering mode: Local VPN, high-quality
* Device model: Samsung SM-A910F
* Operating system and version: Android 8.0.0 
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: Not found

**Comment by drkunder** [comment]
Hi, this is the Issue I reported to your team and face the problem on 3 of Samsung Galaxy phones- One A9 Pro and rest two Galaxy A8 Star

**Comment by ameshkov** [comment]
@drkunder are you sure the firmware updates are received by these two apps? `org.com.sec.android.soagent` and `org.com.wssyncmldm`?

Could it be that the request is done by `root`?

**Comment by drkunder** [comment]
Hello,
As far as I know, at least one of the two circled "Android System" components shown in the snapshot connect to the server to check for update.
When I enable another VPN Firewall - "Netguard" available on Playstore & Github(and block the Android System, all its 82 sub software components including the above two Update components are SIMULTANEOUSLY  blocked together and the OS Updater is unable to reach the update server (along with all the components). An error message pops up that server could not be reached. However all permitted apps function normally by connecting to the internet.
Under similar circumstances, when all these components are individually blocked in Adguard, the Update somehow connects to the server and respond that 1st February patch is the latest.
Apart from the Update, I would not know which if the 82 components of Android System connects to the internet as it isnt captured in the internet connection log. This is what I fear MOST and do not want it to happen.
Please see all the various components under Android System in the snapshots.
This is my layman's explanation as far it gets.
My phone is not rooted so would not know if root permits such connections even when its blocked in Adguard firewall (forced https enabled).
Moreover, I do not know if Adguard uses different Firewall blocking methods than Netguard even as both work via Always on VPN enabled.
--
Kind regards,
Dwight
Sent from Mail.Ru app for Android
Monday, 20 May 2019, 02:55pm +05:30 from Andrey Meshkov notifications@github.com:

**Comment by ameshkov** [comment]
@drkunder got it, just one question then in order for us to reproduce the issue - how do you check updates? Is it done through some Samsung system app?

**Comment by drkunder** [comment]
When you press "Download updates Manually" under the "Software Update" under the settings menu, the OS connects to the internet and returns a response whether there is an update available or could not connect to server(if the firewall blocks the update)

**Comment by zzebrum** [comment]
@drkunder 

> All Samsung Knox security features are disabled

specify what features and how exactly they are disabled?

can you reproduce the issue with debug logging level enabled? and also export and send to support team support@adguard.com AdGuard settings? 

so far can not repro on our side

**Comment by drkunder** [comment]
I sent a email to support@adguard.com yesterday with the Debug file while re producing the issue twice. Let me know if this file contains the necessary logs?

**Comment by zzebrum** [comment]
I see quite a big chat with support team @drkunder 
And I'm not sure if I got it right: do you have **Always-on VPN** and **Block connections without VPN** options enabled? and what message do you get if check for an update?

**Comment by drkunder** [comment]
Hi,
Yes its been multiple times back and forth with your support team but I will try to be as crisp as possible, once again.
Condition 1-
If-
Only "Always on VPN" is turned on and updated, the OS contacts the server and turns on message on the page "Latest update has already been installed". If there was an update, it shows update available  in notification as well as under the Software Update setting (even without manual update check). Moreover Samsung's Device Maintenance > Storage module too can be forced updated (the Chinese company's 360 Security have integrated their module for storage cleaning on Samsung devices so it connects to 360's security server!)
This behaviour has been seen on my Samsung Galaxy A9 Pro as well as my wifes Samsung Galaxy A8 Star.
Condition 2-
If-
"Always on VPN" and "Block connections without VPN" is simultaneously turned on and then updated the following pop up apoears that reads "Couldn't download update, Unable to update the software. A network or server error occured. Try again later". Samsung's Device Maintenance > Storage module too cannot be forced updated any more and an error pops up that "Couldn't connect to server"
However under this condition, many downloaded apps like Google Map, Uber, Ola, Bigbasket, Outlook to name a few, display error message that internet connection unavailable or simply turn up a blank page with network error symbol. 
--
Sent from Mail.Ru app for Android
Tuesday, 21 May 2019, 08:47pm +05:30 from zzebrum notifications@github.com:

**Comment by zzebrum** [comment]
@drkunder both cases seem to have the correct behavior. 

> AdGuard rules:
||upd.samsung.com^$app=org.com.sec.android.soagent
||upd.samsung.com^$app=org.com.wssyncmldm

where did you get these rules?

**Comment by drkunder** [comment]
Hi,
Adguard Support suggested these rules on 16th May. The latter SAMSUNG_UPDATER part was to be replaced with the two Update package names that appeared on apk extractor.
--
Kind regards,
Sent from Mail.Ru app for Android
Friday, 24 May 2019, 09:48pm +05:30 from zzebrum notifications@github.com:

**Comment by drkunder** [comment]
Hi, I managed to sort the complaint with Always on VPN setting + block connection without VPN set yo ON together. I made certain changes to the Low Level settings on Adguard. Android OS is unable to bypass the Firewall anymore nor can  Device Maintenance >Storage module update over the 360's server. All Google as well downloaded apps functions with proper internet connectivity which did nit happen earlier. Have sent an email to support@adguard.com with full details with Adguard log file for your understanding. Isuue sorted on all our three Samsung Galaxy phones running Android 8 with the same settings (mine on nightly and other two on stable release v.3.0.0). Immensely greatful to the entire Developer team at Adguard! Thanks once again!

**Comment by infinitewaveparticle** [comment]
@drkunder Why don't you just block all traffic to all system apps using Apps Management? That's what I do.. and I also use the generic rule:

||*samsung*$important

**Comment by infinitewaveparticle** [comment]
||**samsung**$important

**Comment by infinitewaveparticle** [comment]
Should have "*" in front and behind 'samsung'

**Comment by drkunder** [comment]
Appreciate the suggestion! Yes, I tried similar wildcard rules but surprisingly did not stop the system contacting the samsung server...Device Maintenance > Storage connecting to 360 security server in our 3 devices...however as of now, the situation is controlled
