### ISSUE TITLE
Do not restart the protection when network connectivity disappears for the short period of time

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#2743]
As in helpdesk ticket 2191137:

Protection restarts immediately after very brief losses of network connectivity (the Wi-Fi icon doesn't even gray out). `pref.vpn.disable.reconfigure`,  `pref.proxy.disable.reconfigure` and `pref.vpn.disable.pause` flags don't help.

**Comment by ameshkov** [comment]
Hm, that's weird, `pref.vpn.disable.reconfigure` **must** help in this case.

@Revertron please take a look at the log

**Comment by Revertron** [comment]
I've took a look at the log before, and delegated @vbagirov to create a task about it.
Next step - to take a look at the code :)

**Comment by Revertron** [comment]
After second thorough examination of that log it seems that all the defense restarts are related to filters update. And our low-level flags are working properly.
