### ISSUE TITLE
Please correct the Arabic interface and set this phrase shown in the image in its correct location

### ISSUE THREAD

**Issue by ahmadMabhei** [AdguardTeam/AdguardForAndroid#2748]
![Screenshot_٢٠١٩-٠٥-٢٥-٠٢-٤٢-١٤](https://user-images.githubusercontent.com/32304270/58386491-1cef0c00-8009-11e9-9b98-9f37b59dc8dd.png)

**Comment by admitrevskiy** [comment]
Done.
Testing instructions for QA:
-Reinstall AG
-Switch language to Arabic (عربى)
-Check RTL issue from the screenshot
