### ISSUE TITLE
Stealth mode and Google Duo compatibility issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#2757]
### Steps to reproduce

1. Enable Stealth mode.
2. Disable all the filters but leave ad blocking enabled for Google Duo (leave HTTPS-filtering disabled though).
2. Try to make a voice or video call to someone.

### Expected behavior
Connection is established after the second party answers the call.

### Actual behavior
Nothing happens. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17472907/58496277-3c5d7480-8182-11e9-85fd-b60eee223945.png)

</details>

### Your environment

* Adguard version: 3.0.297
* Adguard filtering mode:  Local VPN
* Device model: Google Pixel 2 XL
* Operating system and version: Android 9

**Comment by ameshkov** [comment]
Broken by "blocking webrtc"

**Comment by Nzzyme** [comment]
But WebRTC leaks are not just limited to browsers right?

I see that the latest beta now only limits this to browsers. Until now, was it blocking for all apps?
