### ISSUE TITLE
Incompatibility with WireGuard kernel mode

### ISSUE THREAD

**Issue by ViRb3** [AdguardTeam/AdguardForAndroid#2759]
### Steps to reproduce
1. Get an Android kernel with the WireGuard module integrated
2. Start WireGuard connection
3. Start AdGuard protection

### Expected behavior
AdGuard works on top of WireGuard

### Actual behavior
No internet connection

### Details
Starting WireGuard after AdGuard will make it work, however, after the network/interface changes, connection is lost again.

Related issue (not raised by me):
https://forum.adguard.com/index.php?threads/wireguard-compatibility.31004/

### Your environment
* Adguard version: v3.0.377
* Adguard filtering mode: HTTP Proxy (Auto)
* Device model: OnePlus 5T
* Operating system and version: Android 9, OmniROM (TreskMod)
* Root access: Yes
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: Yes, WireGuard

**Comment by ameshkov** [comment]
> Starting WireGuard after AdGuard will make it work, however, after the network/interface changes, connection is lost again.

Hm, I see on that forum thread that enabling `pref.proxy.disable.reconfigure` does not help. This makes it complicated.

AdGuard adds a set of iptables rules like this:
```
iptables  -t nat -A ADGUARD_OUTPUT -p tcp -d {{OUT_PREFIX}} --dport {{OUT_PORT}} -j REDIRECT --to {{PORT}}
```

It does not use any specific network interfaces so I have to assume that WireGuard is re-initialized on network change.

If you export AdGuard logs in advanced settings, you'll find two files in the archive: `routes.txt` and `addrs.txt`, could you please attach them? Also, AdGuard prints the current iptables rules list in the log, could you please take a look there and copy/paste it?

Alternatively, you can simply send the archive to `devteam@adguard.com`

**Comment by ViRb3** [comment]
I have attached 4 log cases below:
* AdGuard paused, no WireGuard
* AdGuard enabled (HTTP mode auto), no WireGuard
* AdGuard enabled, WireGuard enabled (kernel mode)
* AdGuard enabled, WireGuard enabled (kernel mode), Wi-Fi turned off then on

I masked most IPs, please let me know if that prevents you from reading the logs and I can send untouched ones. Thanks!

[adguard.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3230148/adguard.zip)

**Comment by ViRb3** [comment]
Update: starting WireGuard first and then AdGuard will let it work after connectivity changes, although the Wi-Fi icon will still show no internet connection.

**Comment by ViRb3** [comment]
Hello, another update on this issue:
With latest 3.1 I can't use WireGuard with AdGuard at all; no matter the activation order, internet would cut off until one is disabled.
However, after some testing, I discovered that the problem seems to be in the DNS filtering - more specifically - DNS-over-HTTPs. After turning it off or changing the mode to DNS-over-TCP, everything works properly, no matter the order of activation, and including after connectivity changes!

**Comment by ameshkov** [comment]
> So after some testing, I discovered that the problem seems to be in the DNS filtering - more specifically - DNS-over-HTTPs. After turning it off or changing the mode to DNS-over-TCP, everything works properly, no matter the order of activation, and including after connectivity changes!

Huh, this is **really** weird. I mean I'd understand if it worked when you completely disabled DNS filtering, but I don't see what's the difference between DOH and DOT.

What exact DNS resolver were you using in both cases?

**Comment by ViRb3** [comment]
I tried all of them. Any DOT works and all DOH fail.

**Comment by ViRb3** [comment]
After numerous testing I can confirm that OpenDNS DNSCrypt works, as well as Cloudflare DOT, however AdGuard DOT and DOH, as well as Google DOH don't work.

**Comment by ameshkov** [comment]
😕 

I guess we should look into it, but it will take some time to set up the test environment.
Assigned to v3.3 for now.

**Comment by ViRb3** [comment]
Sure, happy to assist in any way possible.

**Comment by admitrevskiy** [comment]
@ViRb3 Could you please retest this issue with latest nightly? 
Please, send debug logs to `devteam@adguard.com` If it still exists
To collect debug logs go to Settings -> Advanced -> Log Level -> Record everything
To export logs go to Settings -> Advanced -> Export logs

**Comment by Chinaski1** [comment]
Helpdesk ID : 2045955

**Comment by artemiv4nov** [comment]
Reassigned to 3.4 for because of waiting to re-check on the user side.

**Comment by ameshkov** [comment]
Reopen if there's any update plz
