### ISSUE TITLE
[Feature request] Add more icon/notifications options

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#276]
I would like the icon on the status bar (i.e. when you have unlocked the
phone) to be there - so I know AdGuard is running, I do NOT want to have
the notification displaying on the lock screen itself. You can configure
notifications on the lock screen to be completely hidden if the
notification is marked as 'Secret' rather than just 'Private' (private just
hides the details) - I'm getting these names from the Visibility options in
the app Automagic - which lets you create notifications so they may be
called something else?
NDH-284-87917

**Comment by ameshkov** [comment]
We'll look into this, thank you!

**Comment by evgeniy-ADG** [comment]
> В настройках есть 3 возможности показа иконки: без иконок, шторка+иконка и только шторка. Будет ли 4ый вариант - только иконка в статус-баре? Отключать не хочется, а наличие в шторке уведомления не очень то радует

POX-563-25922

**Comment by ameshkov** [comment]
@evgeniy-ADG я не уверен, что четвертый вариант возможен. Проверим.

**Comment by evgeniy-ADG** [comment]
> I also have ESET mobile security on my phone. ESET keeps its
> notification ready icon in a separate area, below the usual
> notifications that come and go. Their app icon also doesn't appear at
> the top of the phone, helping to keep my phone free from distractions.
> I believe Adgauard would be improved by doing something similar.
> System maintenance apps are always running, but I rarely need to
> actually interact with them. Love everything else though. I plan on
> subscribing to premium in the near future.
1306497

**Comment by ameshkov** [comment]
If I get it right, we already have this option, it is named "Notification without icon

**Comment by ameshkov** [comment]
Dup
