### ISSUE TITLE
Make navigation bar dark grey / black when AdGuard is in dark mode

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2760]
This is a feature request received from user 1403048:

"It is weird for the navigation bar to be the color it is. That is not
standard for dark mode. It should either match the rest of the gray it
touches, or it should be black. But for it to be a light gray and not match
anything else is weird."
<details><summary>Screenshot</summary>

![Screenshot_20190527-223145](https://user-images.githubusercontent.com/33634917/58612374-08d23580-82bb-11e9-9db2-094d7b5c4902.png)

</details>

**Comment by artemiv4nov** [comment]
#2275

**Comment by carlylemiii** [comment]
Note that this issue is about the nav bar, but the author circled the app bar. It's not so much about themes as it is dark mode best practices.
