### ISSUE TITLE
AdGuard displays a blank white screen for a short period of time before enabling dark mode

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2761]
### Steps to reproduce
1. Enable dark mode
2. Go to home screen
3. Launch AdGuard from phone menu
4. AdGuard will show a blank white screen for a fraction of a second before applying dark mode

### Expected behavior
Theme settings should be applied instantaneously

### Actual behavior
AdGuard displays a blank white screen before switching to dark mode

<details><summary>Screen recording:</summary>

https://photos.google.com/u/1/share/AF1QipP2oknIEoLv2MJNrnhOBKfI4hJEzaycRoYnQs-EAJKZt8p2fEWAXnQGH8cbEWcCNA/photo/AF1QipM5GfPMjEwGs3kHuYvwKqWgfonI4kJxv17GZq1n?key=VDlHdjdfeHpRUDIteVQ0M1VJOFdiMmtQQmlEZHNB

</details>

### Customer ID 
1403048

### Your environment
* Adguard version: 3.0.297 Release
* Adguard filtering mode: Not applicable
* Device model: Google Pixel 3 XL
* Operating system and version: Android 9.0
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: None found

**Comment by artemiv4nov** [comment]
This feature was improved in newer nightly-versions: blank screen is no longer displayed.
