### ISSUE TITLE
UI is "blinking" when dark theme is enabled

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2763]
Steps to reproduce:

Open AdGuard - Settings - General - Dark theme (enable)

Return back to the main page (you will see the short blinks on the display)

**Comment by srknzl** [comment]
I could not reproduced this bug, are you sure this is a software bug?

**Comment by TheHasagi** [comment]
@srknzl 

This relates to the latest Nightly :)
