### ISSUE TITLE
Targeting SDK 28: check that IPv6 redirection works properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2764]
> Per-app SELinux domains. We might need to re-test the way the IPv6 redirection works in root+proxy mode.

**Comment by artemiv4nov** [comment]
How to reproduce on OnePlus:
1) Turn on root proxy: Settings -> Network -> Filtering method -> Local HTTP Proxy;
2) Install certificate: Settings -> Network -> HTTPS Filtering -> turn on;
3) Move certificate to System store: Settings -> Network -> HTTPS Filtering -> Security certificate -> Move to system store;
4) Turn on protection on main activity;
5) Be sure that browser uses Adguard's certificate on ipv6.google.com
