### ISSUE TITLE
Landscape mode freezes in latest Beta (3.1)

### ISSUE THREAD

**Issue by Yevhen1996** [AdguardTeam/AdguardForAndroid#2765]
The app freezes and hang on landscape view and not coming back to portrait mode until
you force close it. 

### Expected behavior
The app returns portrait mode when you rotate the phone. 

### Actual behavior
Landscape mode freezes when you rotate the phone

### Your environment

* Adguard version: 3.1
* Adguard filtering mode: Local VPN
* Device model: samsung SM-N910C
* Operating system and version: Android 6.0.1
* Root access:  No

**Comment by Yevhen1996** [comment]
Another user shared screenshots of a familiar problem (model=SM-G930F brand=samsung):

![Screenshot_2019-05-30-23-18-08](https://user-images.githubusercontent.com/39196837/58749008-e55ce580-8488-11e9-9eb9-0d0ffc7217f1.png)
![Screenshot_2019-05-30-22-52-12](https://user-images.githubusercontent.com/39196837/58749014-fb6aa600-8488-11e9-8e73-69a706d1b546.png)

**Comment by Yevhen1996** [comment]
similar issue on Samsung phone when switching back to vertical. Landscape mode stays. model=SM-G930F brand=samsung


![Screenshot_2019-05-30-23-18-08](https://user-images.githubusercontent.com/39196837/58749041-7f249280-8489-11e9-9ae6-2fbf58cb2176.png)

![Screenshot_2019-05-30-22-52-12](https://user-images.githubusercontent.com/39196837/58749042-864ba080-8489-11e9-8710-9e7d619cb5a7.png)

**Comment by TheHasagi** [comment]
Steps to reproduce:

1. Run AdGuard at first time
2. Try to start the protection
3. When you will see the message that explains about VPN, change orientation to landscape and back again until it stuck.
