### ISSUE TITLE
MMS messages are very slow to send or recieve while connected to WiFi with DNS filtering is on

### ISSUE THREAD

**Issue by moonspeak** [AdguardTeam/AdguardForAndroid#2766]
### Steps to reproduce
1. Enable DNS filtering and turn AdGuard protection on
2. Send an MMS message
3. The message will stay in "Sending..." for either very long or indefinitely
4. If you disconnect from WiFi OR turn AdGuard off OR turn off DNS filtering, the MMS will send almost immediately

Alternatively, receive an MMS and it will not download automatically. I have to manually download the MMS and it takes a very long time as well.

### Expected behavior
MMS should not be halted by DNS filtering

### Actual behavior
* Outgoing MMS will stay in "Sending..." for either very long before finally going through or never get sent.
* Incoming MMS will take very long to download.

### Logs
[Google Drive link](https://drive.google.com/file/d/18L_1KpzvRERGMirYnXmEv2IFKVR9Ynw6/view?usp=drivesdk)

- At 15:53, I sent an MMS image to a group message. It takes a long time but eventually sends.
- Around 15:54, I've disconnected from WiFi and then send another MMS image (this time to myself) and it sends without delay.
- I then disable DNS filtering in AdGuard, reconnect to WiFi, and send another MMS to myself which also sends without delay.

### Customer ID 
2114670

### Your environment
* Adguard version: 3.1 beta (issue has been present on previous versions)
* Adguard filtering mode: HTTP Proxy Auto (I believe issue exists with VPN mode as well)
* Device model: OnePlus 7 Pro (issue also present on OnePlus 6T)
* Operating system and version: Android 9, OxygenOS 9.5.6
* Root access: Yes
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: No
* Service provider: T-Mobile US
* SMS/MMS apps tested with: Messages by Google, Textra, Facebook Messenger (with SMS enabled)

**Comment by Chinaski1** [comment]
Regardless of the application used (Android messages/Textra/Facebook Messenger)

**Comment by ameshkov** [comment]
Could you please check if there's any difference when you use AG in VPN mode?
