### ISSUE TITLE
Display whitelist-modified rules

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#2767]
As reported by user 1968599,

> I think there is an absolute necessity to distinguish between
> whitelisted-unmodified and whitelisted-modified rules. A whitelisting
> rule sometimes serves to simply stop another rule from always working
> so to exempt a whitelisted site, item, or server from stealth mode
> modifications is wrong.

**Comment by artemiv4nov** [comment]
Recent activity (former Filtering log) has been reworked in the 4.0 version, events for whitelisted rules looks different.
