### ISSUE TITLE
User Rules & DNS

### ISSUE THREAD

**Issue by bass3aad** [AdguardTeam/AdguardForAndroid#2769]
### Steps to reproduce
1. Configure a User rule like ||facebook.com^
2. dns://facebook.com is resolved to IP
3. However, facebook.com can not be accessed

### Expected behavior
In AdGuard v2, dns://facebook.com is blocked.
In AdGuard v3, dns://facebook.com is allowed.
Expected behavior: dns://facebook.com should be blocked

### Your environment
* Adguard version: 3
* Adguard filtering mode: Local VPN
* Device model: Moto Z3 , OnePlus 7 Pro , Note 9
* Operating system and version: 9
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:  No

**Comment by ameshkov** [comment]
@admitrevskiy please take a look once you're done with #1851

**Comment by admitrevskiy** [comment]
@bass3aad hi!
I can't reproduce this issue with the latest nightly environment (3.1.10). Please, provide me some additional information.
1) Which version of AG 3 do you use? 
2) `dns://facebook.com is resolved to IP` - Do you mean that event Status in Filtering Log is `Processed` and there is a DNS Answer inside?
3) Do you try to reach `facebook.com` via browser or facebook app?
4) `However, facebook.com can not be accessed` - What kind of answer is observed in browser? (In my case it's `DNS_PROBE_FINISHED_NXDOMAIN` or `ERR_NAME_NOT_RESOLVED`)
5) Is DNS Request Blocking feature enabled on DNS Filtering screen? Are there any other blocked events for `facebook.com` in the Filtering Log (`https//facebook.com` etc)?

**Comment by bass3aad** [comment]
![2](https://user-images.githubusercontent.com/49113670/59328257-c9cfb700-8ca0-11e9-8caf-9e7b74d67b43.png)
In AdGuard 2 Rule configured ||smetrics.cnn.com^

**Comment by bass3aad** [comment]
![1](https://user-images.githubusercontent.com/49113670/59328346-f84d9200-8ca0-11e9-8982-9ba86fb85ebe.png)
In AdGuard 3 Rule configured ||smetrics.cnn.com^
Yet, this is processed!

**Comment by admitrevskiy** [comment]
@bass3aad hi!
Please, try the latest nightly. Do not use `$app` - syntax (dns user rules will be separated into new section in https://github.com/AdguardTeam/AdguardForAndroid/issues/2803 ). DNS filtering module was reworked and issue should be already resolved
