### ISSUE TITLE
Improve UI by adding consistency

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#2777]
Congratulations on AdGuard v3.1.0 beta.  Job well done!

The AdGuard Apps Management UI can be significantly improved by adding consistency.

Currently, the small icons to the right of the name of each app are ordered as follows:

1. AdGuard Protection status
2. WiFi data status
3. Cellular data status

Once the user clicks on an app's name, the resultant page presents the same information in a different order:

1. AdGuard Protection status
2. Cellular data status
3. WiFi data status

I recommend making them consistent, using this order:

1. AdGuard Protection status
2. WiFi data status
3. Cellular data status

**Comment by ameshkov** [comment]
Uh, how could we miss that:)

**Comment by Gitoffthelawn** [comment]
@ameshkov An extra set of trained eyeballs always helps!  :)   I'm here for you and your team.

**Comment by Nzzyme** [comment]
Is this already fixed in 3.1.0 as I do not see this issue? For me all the icons are in the same order on both the pages.
