### ISSUE TITLE
Can data leak when AdGuard restarts itself?

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#2778]
Every time the user changes an app rule in AdGuard, AdGuard restarts itself.  If an app is sends/receives data during this process, can it send/receive data even though it is set to not do so?

Testing AdGuard v3.1.0beta

**Comment by Revertron** [comment]
Yes, they can.
But a new version of Corelibs with configuration change on the fly is almost ready. Stay tuned! ;)

**Comment by Gitoffthelawn** [comment]
@Revertron Looking forward to it!  Is there an approximate ETA?

**Comment by Revertron** [comment]
@Gitoffthelawn I think about a week ;)
