### ISSUE TITLE
ru.yandex.yandexnavi — road alerts and maps saving don't work 

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForAndroid#2779]
### [Issue URL](https://github.com/AdguardTeam/AdguardFilters/issues/26263)

[https://play.google.com/store/apps/details?id=ru.yandex.yandexnavi](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.yandex.yandexnavi)

### Steps to reproduce

1. Disable all filters, turn off Stealth Mode and DNS Filtering.
2. Roads alerts aren't showing up and maps aren't downloading to storage.

### Actual behavior

> При включенном AdGuard в яндекс.навигаторе пропадают все иконки дорожных событий. 

> При включенном adguard блокировалась скачка карт для Яндекс навигатора.

### Your environment

* Adguard: 3.1.8
* Android: 8.1 / 9

**Comment by sfionov** [comment]
We have this issue in CoreLibs: https://github.com/AdguardTeam/CoreLibs/issues/616
