### ISSUE TITLE
Yandex Navigator is unstable because of ad filtering 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#278]
It can't build a route when ad filtering is enabled.

@Alex-302 can you take a look please?

**Comment by Alex-302** [comment]
No problems with routes. (from A to B across C)

**Comment by ameshkov** [comment]
Try using it a bit more, enable traffic data and such.

**Comment by Alex-302** [comment]
All options are enabled. Made 5 routes.

**Comment by ameshkov** [comment]
Use Mobile data, not Wi-Fi

**Comment by evgeniy-ADG** [comment]
гайз, а тут поступило обращение, у пользователя есть проблема:

> Навигатор (не строит маршрут) при включении adguard

**Comment by ameshkov** [comment]
А у меня в альфа-версии исправилось.

Пока что надо фильтрацию рекламы отключать в нем.

**Comment by evgeniy-ADG** [comment]
ясно, завтра отвечу.

**Comment by ameshkov** [comment]
Seems to be fixed in v2.5 alpha
