### ISSUE TITLE
MIUI10 9.5.23 don't show VPN icon in status bar

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2780]
### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/59026609-84a22400-885f-11e9-889b-4a878edd597c.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/59026826-ff6b3f00-885f-11e9-8c25-666cdcd5fa5a.png)
</details>

### Customer ID 
post-182987

### Your environment

* Adguard version: nightly 3.1.2
* Adguard filtering mode: Local VPN 
* Device model: MIUI10 9.5.23

**Comment by makstrix** [comment]
For me, sometimes it's shown and sometimes not. Xiaomi.eu 9.5.30 (Previous versions too).

**Comment by TheHasagi** [comment]
@Chinaski1 
This isn't related to AdGuard. Some MIUI issues. Can this situation be easily reproduced with any VPN based app?

**Comment by TheHasagi** [comment]
Also, you better to check this [forum](http://en.miui.com/thread-307919-1-1.html).

**Comment by paradislover** [comment]
Openvpn and wireguard never meet such issue. So I don't think it is only MIUI issue. Adguard should fit for MIUI. Thanks.

**Comment by panda-mute** [comment]
@TheHasagi @Chinaski1
It is long time for this issue.

I have tried openvpn/wireguard/shadowsocks, any of them can show vpn icon in status bar.
But the adguard can't work? Could you check this issue with priority.

MIUI10: 9.7.4
Adguard: 3.1.84 night

**Comment by panda-mute** [comment]
Append.

A ad block app adshield can work in MIUI10, so it is adguard issue truly.

Why there is no any update?
