### ISSUE TITLE
Default on HTTPS filtering for apps

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#2781]
I've experimented in the last few months w/ toggling on HTTPS-filtering for various apps I've installed.  I've found few _browsers_ support it, but a random hodgepodge of _other_ apps actually do quite well w/ it. 🤷🏾‍♂️  Is reporting them here (like #2680) what y'all would prefer?

Here're some of them (if #2530 were implemented, I'd be more easily comprehensive):
- GMail → com.google.android.gm
- [APKPure → com.apkpure.aegon](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703)
- MS Edge → com.microsoft.emmx
- MS Outlook → com.microsoft.office.outlook
- WhatsUp → com.whatsapp
- Best App Sale → com.bestappsale

### Customer ID 

1122984 (No report sent, though)

### Your environment

* Adguard version: 3.1.9η
* Adguard filtering mode: Local VPN
* Device model: Moto G5+
* Operating system and version: Android 8.1.0
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: No

**Comment by ameshkov** [comment]
The problem here is that we're afraid that these apps will stop supporting https filtering and we'll have to quickly update the app. So we'd better keep the defaults as they're now.

On the other hand, we could maintain a list of compatible apps and somehow highlight them in the UI?

Regarding WhatsApp, they use a different protocol so HTTPS filtering just does nothing.

**Comment by patrickdrd** [comment]
I agree, it's better to play safe than aggressive, because the loss of an app not working 
(in case of stop supporting https) is bigger than the gain

**Comment by TPS** [comment]
> The problem here is that we're afraid that these apps will stop supporting https filtering and we'll have to quickly update the app. So we'd better keep the defaults as they're now.

>I agree, it's better to play safe than aggressive, because the loss of an app not working (in case of stop supporting https) is bigger than the gain

By that reasoning, y'all couldn't have _any_ apps default on for this (or any other _currently_ compatible feature).
> On the other hand, we could maintain a list of compatible apps and somehow highlight them in the UI?

The highlighting idea isn't bad, but IMHO, rather than hard-coding, this should be another online updating list (#25) that includes known compatible, known *in*compatible, & recommendations (perhaps privacy-concerned, like banking, apps), somewhat extending the current white- & blacklists.  Such could be another opt-in toggle _outside_ the filtering subscriptions, but otherwise subscribed exactly like them.
>Regarding WhatsApp, they use a different protocol so HTTPS filtering just does nothing.

Currently there're a _bunch_ of protocols that're ignored/blocked that I've seen (udp, tcp, wss, quic, &c).  Maybe I'm just imagining it, but, somehow,  I've observed (#2703) that this HTTPS toggle allows me to observe (& potentially block) more, even before AG is capable of decoding.

**Comment by TPS** [comment]
Another app that works perfectly w/ HTTPS filtering is
- Our Daily Bread → org.rbc.odb

**Comment by TPS** [comment]
I actually now prefer the _functionality_ of `pref.notify.on.unknown.ca`, though its _UI_ could do w/ a lotta work — is it possible to incorporate it into a feature that could _automatically_ handle HTTPS filtering, but w/ said behavior overridable per-app?

**Comment by artemiv4nov** [comment]
Hello!
It seems the task exists for a long time without any reaction. Well, I closed it again.
