### ISSUE TITLE
 Dark theme settings are reset

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2784]
### Steps to reproduce

1. Enable Dark Theme
2. Go back to the Main menu. 
3. Open general settings > Change update channel
4. Automatically returns to White Theme

### Customer ID 

customer-1867397

### Your environment

* Adguard version: 3.1.0
* Device model: ONEPLUS A3003
* Operating system and version: Android 9

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
- To reproduce the issue enable `Don't keep activities` in `Developer Options`
- Reinstall AG
- Reproduce steps from the first message
