### ISSUE TITLE
Crash: java.util.UnknownFormatConversionException: Conversion

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2787]
See here:
https://sentry.adguard.com/adg/adguard-android-rs/issues/24659/
https://sentry.adguard.com/adg/adguard-android-rs/issues/24658/

**Comment by admitrevskiy** [comment]
Resolved in https://github.com/AdguardTeam/AdguardForAndroid/issues/2748
