### ISSUE TITLE
Other installed apps take up to 15-20 seconds to start when Adguard is enabled.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#279]
If Adguard is disabled, apps start instantly. Was checked in v.2.1.350, asked to install v.2.1.359. Back with v.2.1.267 this was not an issue.

Some logs are inside the ticket.

HAR-272-96391

**Comment by ameshkov** [comment]
Which apps exactly?

**Comment by vbagirov** [comment]
@ameshkov quote from the user: "app that are affected are 2g 3g 4g lte network monitor, photo grid, electrodroid, etc. other apps like facebook, gmail are not affected."
