### ISSUE TITLE
Failed Update Text String

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2790]
Currently, when WiFi / Mobile data is off and one tries to update the filters, we see a message:

> Update failed. Please try again later.

And sometimes, even though we are connected and try to update the filters, we see a similar message (server issue, etc.). In this case, it makes sense to include the above message.

But if one is not connected to the internet, instead of this message, you can include the following text:

> Not connected to the Internet. Please connect and try again later.

**Comment by artemiv4nov** [comment]
No reaction for a long time, will close it, re-open if needed
