### ISSUE TITLE
Include a "Kill Switch" Functionality

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#2791]
Currently, there is no "Kill Switch" functionality in AG. Can you include a setting such that when this functionality is enabled and when protection is disabled, the internet of the device (WiFi & Mobile Data) should be disconnected so as to prevent any leakages of ads/trackers. Many popular VPN software have this feature.

A toast message / Notification should follow informing the user that protection is disabled and the internet is disconnected.

**Comment by ameshkov** [comment]
On Android this is called "Always-On VPN" and can be enabled manually from Android settings

**Comment by Nzzyme** [comment]
I am on Android version 6 (6.0.1) - Marshmallow (MIUI Global 10.2) and don't see this option in VPN system settings or any other option :(

Not all might have this setting. Would it be possible to implement this in AG itself?

**Comment by omaryey** [comment]
this setting ( vpn always on )  found in setting > connections > more connection settings > VPN

**Comment by Nzzyme** [comment]
Hi @omaryey As I mentioned, I did not see any such setting. MIUI probably does not have this setting.

**Comment by TheHasagi** [comment]
@Nzzyme 

It's better to check this [forum](http://en.miui.com/thread-307919-1-1.html) thread. I guess some of MIUI ROMs does not support such option.

**Comment by Nzzyme** [comment]
Is it actually possible to do this with AG though?

**Comment by ameshkov** [comment]
> Is it actually possible to do this with AG though?

Well, on Android 8+ it is possible to do this in Android settings.

**Comment by lancelot-moon** [comment]
You provide outbound proxy in AG for Android.
Vote this feature request of "kill switch", especially if AG starts to support common VPN protocols.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2667

As what you know, some VPN apps also provide "kill switch" option.
