### ISSUE TITLE
The wrong link's range of AdGuard.com in About when app's language is Traditional/Simplified Chinese in v3.1.14η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2792]
The phrase number is #47617003 on onesky.
AG for Android v3.1.14η.

In English and other languages' interface, it's ok.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/C32aiTt.png)
</details><br/>

But the issue maybe only happens in Traditional/Simplified Chinese.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/96xsmR6.png)

![image](https://i.imgur.com/s1gbTle.png)
</details><br/>

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/2499
