### ISSUE TITLE
Feature request for "Apply new settings"

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2795]
When you configure AG, it reboots several times to apply changes made by the user. 
There is an offer to make “Apply new settings” or popup with something like this.
“To apply new settings, restart AdGuard” and two buttons “apply” and “cancel” or something like that.

**Comment by Haron-Prime** [comment]
I think that a similar window should appear after the user has made changes and closes the settings section.
