### ISSUE TITLE
Change notification about updated userscripts and filters

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#2796]
Application checks updates for filters, application and userscripts. If filters or userscripts have been updated, application shows Toast for every action.

Need to combine two toast into one entity (dialog, toast, activity).

**Comment by ameshkov** [comment]
This should be a new activity with a list of items being checked:

* Content blocking filters
* DNS filters
* Extensions
* Application update

Each item should have its own status and progress.
Once the update is finished, we should be able to inspect the details (what exactly was updated)

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Tap on `Update` icon on Main screen
-Examine new Updates screen:
- If Module is disabled tap on item should lead to Module screen
- If something was updated tap on item should show updates listing
- If nothing was updated you'll see `Up to date` message
- If App update is available tap on `App` item will open Release notes. To start app update tap on `Update application` or download icon at the right side if `App` item

**Comment by BlazDT** [comment]
Please add an option to not show the new update screen, some users like I do not want to know what was updated, just that something was updated.
