### ISSUE TITLE
DNS filtering is invalid in v3.1.28η.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2798]
Test v3.1.28η.
1. The domains in the filters for DNS filtering aren't shown as blocked in the filtering log.

2. DNS filtering is invalid. Ads appear.

3. Remark the supported formats information of filter list.
ex: Basic adblock rule syntax, domains, hosts files... etc.

**Comment by SergeiShir** [comment]
Exactly the same symptoms. The Filtering Log just shows "Processed", although explicit User Rules exist to block / allow the DNS packets.

![1-log](https://user-images.githubusercontent.com/17823400/59554279-7368be00-8fa9-11e9-84c4-a0d7562b631d.png)
![1-rule](https://user-images.githubusercontent.com/17823400/59554280-74015480-8fa9-11e9-84c3-851f6810027b.png)
![2-log](https://user-images.githubusercontent.com/17823400/59554281-74015480-8fa9-11e9-8a8e-97dfd6abd864.png)
![3-rule](https://user-images.githubusercontent.com/17823400/59554282-74015480-8fa9-11e9-99cb-d86f1ff7a35f.png)
![3-log](https://user-images.githubusercontent.com/17823400/59554283-7499eb00-8fa9-11e9-82dc-b390171c63be.png)
![4-log](https://user-images.githubusercontent.com/17823400/59554284-7499eb00-8fa9-11e9-983b-d65300bc52e1.png)
![4-rule](https://user-images.githubusercontent.com/17823400/59554285-7499eb00-8fa9-11e9-9be1-833333f5c0d8.png)
![2-rule](https://user-images.githubusercontent.com/17823400/59554286-7499eb00-8fa9-11e9-9ffa-b159db535e37.png)

**Comment by TPS** [comment]
@ameshkov, @admitrevskiy: I've precisely same symptoms as all of the above w/ 1 additional datum:  I tried toggling the new Advanced `pref.dns.blocking.nxdomain`, but that had no effect.  DNS blocking seems completely broken. ☹️

**Comment by ameshkov** [comment]
Regarding user filter, I guess the current approach is super confusing.

The only way to resolve it is to have a different section for DNS-level rules. I'll file a separate task about it.

**Comment by ameshkov** [comment]
The bug is caused by proguard obfuscation in the production build, it seems that it strips something important to DNS filtering. We'll fix it tomorrow.

**Comment by TPS** [comment]
Thanks, @ameshkov @admitrevskiy &c: All's well w/ DNS-block again. 🙇🏾‍♂️

Curious questions: What is the advantage of changing default from responding `NXDOMAIN` to `0.0.0.0` (or IPv6 equivalent)?  What circumstances do y'all  forsee us needing `pref.dns.blocking.nxdomain` to revert that?

**Comment by ameshkov** [comment]
> Curious questions: What is the advantage of changing default from responding NXDOMAIN to 0.0.0.0 (or IPv6 equivalent)? What circumstances do y'all forsee us needing pref.dns.blocking.nxdomain to revert that?

Frankly, for the local DNS filtering, there's no difference.

However, for the case when you're running a DOH server, using NXDOMAIN prevents caching of the result by the client -> leads to more DNS queries.

**Comment by SergeiShir** [comment]
The v3.1.37 uses the existing DNS filtering rules.
BUT you still can not create new rules - when you try to create a new rule for a DNS packet, there is no option anymore to select $app=com.adguard.dns - there is nothing under the rule string.

**Comment by Revertron** [comment]
@SergeiShir, this is how new system works. You don't need that part of rule anymore, it will be added in a special section in DNS filtering.

**Comment by TPS** [comment]
> this is how new system works. You don't need that part of rule anymore, it will be added in a special section in DNS filtering.

So, this means 1 can no longer make a _general_ rule from such a log entry, only a  _DNS_ rule⁈  That seems less than optimal, as I myself have generated mostly dual-use rules, which need to match either DNS or URLs.  (While I'm kvetching, I'd still really like the options to _both_ create a white-/blacklist rule, or edit my original black-/whitelist rule, _not_ just directly __delete__ my original rule.  The reasoning to do so then, IMHO, was naive, & isn't better now.)

**Comment by SergeiShir** [comment]
The new system does not let me control the traffic - for example, I always want to allow DNS packet for facebook.com, but I want to block the actual connections for specific URLs or apps.

**Comment by ameshkov** [comment]
@SergeiShir you're about to get it.

We will introduce separate "custom rules" settings for DNS filtering in one of the next nightlies.

**Comment by TPS** [comment]
This seems partially broken again since 3.1.37η: General user rules don't process for DNS-blocking anymore, which is noticeable, because everything's slower this way.

**Comment by TPS** [comment]
This seems partially broken again since 3.1.37η: ___Certain___ general user rules don't process for DNS-blocking anymore, which is noticeable, because everything's slower this way.

It turns out to be very specific:  all my rules that are simple strings (e.g. `adobedtm`) no longer DNS-block.  But if they're delimited in any fashion (e.g. `||app-measur`), then they work just as before.

**Comment by TPS** [comment]
Another glitch:  When using a `hosts` subscription for DNS-block, `pref.dns.blocking.nxdomain` (tried because of discussion in #1582) seems to be ineffective for domains set to ::, 127.0.0.1, or 0.0.0.0 — those don't get __NXDOMAIN__ response per AG log.

**Comment by admitrevskiy** [comment]
@TPS, hi!
Looks like there is a mistake in description for `pref.dns.blocking.nxdomain`. NXDomain should be generated for regular filtering rules, not host rules. Thank you for the feedback, I'll fix this phrase.

**Comment by TPS** [comment]
@admitrevskiy But why⁈  Shouldn't DNS-blocking work consistently, no matter where the rule comes from?

**Comment by ameshkov** [comment]
Hosts subscriptions already indicate the IP address that needs to be returned

**Comment by TPS** [comment]
That makes sense when using `hosts` as [originally intended](https://en.m.wikipedia.org/wiki/Hosts_(file)#History), but [adblockers don't do that](https://en.m.wikipedia.org/wiki/Hosts_(file)#Extended_applications).  I suppose if y'all want to support the former (as rare as that might be), that'd be fine, but isn't the major use by AG purely adblock?  Then wouldn't it make sense to be consistent in the DNS-based blocking behavior, especially for an advanced toggle which _(currently)_ isn't the default behavior?

**Comment by ameshkov** [comment]
I guess this needs to be a separate feature request.

**Comment by TPS** [comment]
@admitrevskiy, @ameshkov: Opened & quoted y'all in #2847 to handle `pref.dns.blocking.nxdomain` issue.
