### ISSUE TITLE
Adguard protection doesn't restart

### ISSUE THREAD

**Issue by kwasi101** [AdguardTeam/AdguardForAndroid#2801]
Adguard protection doesn't restart after toggling features in dns or stealth mode. You have to manually restart protection. It happens on the latest nightly v3.1.28n
[adguard_logs_3.1.28_1506_0602.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3293923/adguard_logs_3.1.28_1506_0602.zip)
[adguard_logs_3.1.28_1606_0745.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3293924/adguard_logs_3.1.28_1606_0745.zip)

**Comment by kwasi101** [comment]
v3.1.28n

**Comment by lancelot-moon** [comment]
Duplication.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2800

**Comment by TheHasagi** [comment]
Duplicate of #2800 

Closed.
