### ISSUE TITLE
Add "Custom rules" section to DNS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2803]
Basically, this is a "User filter" for DNS filtering only.

1. [x] It should support basic blocking rules and hosts-level rules.
2. [x] It should be integrated with the filtering log (block/unblock should add/remove rules to the user filter)
3. [x] It should support import/export
4. [x] Help icon should lead to an article explaining DNS-level filtering rules
5. [x] We need to add this article to the knowledge base: https://uploads.adguard.com/up04_dvfc5_AdGuard_Home.png
6. [x] It should be possible to enable/disable custom rules filter

### UI
1. Place the "Custom rules" inside the "DNS Filters".
2. Visually separate blocklists and custom rules.

**Comment by lancelot-moon** [comment]
Is it possible that AG team make the default whitelist for only DNS filtering?
https://github.com/AdguardTeam/FiltersRegistry/issues/153

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/f8401d1b-ffd9-4f47-a4fa-a3c01c29946c?mode=design&sha=3e095474b49ed51225d11b082ddfeab08e4cccaf – separated custom rules
https://share.goabstract.com/221561bd-6437-438f-bcd7-26d2d76b4afa?mode=design&sha=f88d60eb2638dd05416fa13682e7ed5464118863 – filters

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG
-Check issue items

**Comment by SergeiShir** [comment]
Hi
The latest v3.1.53 brings the custom DNS rules feature.
From what I see, I need to manually reconfigure all my DNS rules ($app=com.adguard.dns) that are saved in the list of all custom rules.
Is there a simple way of doing this?

**Comment by SergeiShir** [comment]
In addition, this is a problem:
export of DNS rules saves them under the same name as the export of regular rules - "adguard_user_filter_...".
Could you please change the name to  "adguard_user_filter_DNS..."?

**Comment by superlex** [comment]
Hi, thank you for this feature :)
I'm trying the new beta v. 3.2.98 (PS: in the README file, beta link is not updated for the new beta).
As regards

> It should be integrated with the filtering log (block/unblock should add/remove rules to the user filter)

maybe it could be improved:
- when you unblock a rule, currently it says that the rule will be deleted: why not disable it instead (empty square)?
- when you add a rule (by blocking a log entry or simply adding a new rule to the user filter), this new rule could be added to the top instead of the bottom, just for user convenience (e.g. if there are a lot of rules).

My 2 cents :)

**Comment by ameshkov** [comment]
> when you unblock a rule, currently it says that the rule will be deleted: why not disable it instead (empty square)?

Well, the reason is to not clutter the user filter. It's simple to add a new rule, it should be simple to remove it:)

> when you add a rule (by blocking a log entry or simply adding a new rule to the user filter), this new rule could be added to the top instead of the bottom, just for user convenience (e.g. if there are a lot of rules).

Hm, do you think we should do the same with the regular content blocking user filter?
Could you please open a feature request about it?

**Comment by superlex** [comment]
> Well, the reason is to not clutter the user filter. It's simple to add a new rule, it should be simple to remove it:)

Make sense :)

> Hm, do you think we should do the same with the regular content blocking user filter?

Thinking about it, it could be useful if a user has many custom rules..

> Could you please open a feature request about it?

Of course :)

Then, I'd like to ask two questions:

1) when you add `example.org` to dns user filter only `example.org` is blocked, while when you add `||example.org^` then `a.example.org`, `b.example.org` etc.. are blocked as well: is the correct behavior? Should AdGuard convert `example.org` to `||example.org^` internally?
For example, uBlock Origin does that (and it does the same for `127.0.0.1 example.org` and `0.0.0.0 example.org`).

2) when you import a dns/hosts list, should a rule that begins with `#` be considered as a rule that begins with `!`, that is only a comment (without the square box)? Or as an alternative, should the rule have an empty square box (and the same for `!` as regards content blocking user filter)?

Thanks :)

**Comment by ameshkov** [comment]
> Should AdGuard convert example.org to ||example.org^ internally?
> For example, uBlock Origin does that.

Well, it works exactly as we wanted it to.

The thing is that most of these domains lists are actually a different form of the existing hosts lists, so we're just keeping the semantics of the original list.

> Currently, domains lists like for example Malvertising list by Disconnect are not recognized as valid dns lists, while they could.

Most likely because of `Content-Type: application/octet-stream`, the list is served as it was a binary file and not a text file.

> when you import a dns/hosts list, should a rule that begins with # be considered as a rule that begins with !, that is only a comment (without the square box)? Or as an alternative, should the rule have an empty square box (and the same for ! as regards content blocking user filter)?

AdGuard respects the /etc/hosts specification, `#` is how comments should be marked in hosts files. You can even use it on the same line as the rule: `127.0.0.1    hosts # blah blah comment`

**Comment by superlex** [comment]
> The thing is that most of these domains lists are actually a different form of the existing hosts lists, so we're just keeping the semantics of the original list.

I agree.

> AdGuard respects the /etc/hosts specification, # is how comments should be marked in hosts files. You can even use it on the same line as the rule: 127.0.0.1 hosts # blah blah comment

Ok :)

> Most likely because of Content-Type: application/octet-stream, the list is served as it was a binary file and not a text file.

Uhm, [Spam404](https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt) has `Content-Type: text/plain;` but the warning is the same..

**Comment by ameshkov** [comment]
> Uhm, Spam404 has Content-Type: text/plain; but the warning is the same..

Well, and this looks like a bug :)

Filed a bug report:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2982

**Comment by superlex** [comment]
Ok, thank you @ameshkov :)
