### ISSUE TITLE
Extensions settings UI issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2804]
1. [x] Print "N extensions enabled" or "No extensions enabled" under "Extensions" menu item
2. [x] Change extensions description to "AdGuard can extend web sites functionality, working as a cross-browser userscript manager."
3. [x] Add "help" icon to the toolbar, it should open https://kb.adguard.com/en/general/userscripts

**Comment by admitrevskiy** [comment]
Done
