### ISSUE TITLE
Add "Extension Details" activity

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2807]
First of all, get rid of the context menu. We will put all the necessary actions to this new activity.

What fields do we need to display there:

0. Status (enabled/disabled) with an option to enable or disable the userscript
1. Title
2. Description
3. Version (if any)
4. Homepage (there should be an option to open this link)
5. Download URL
6. Last update time

Actions

* Delete
* Reinstall

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/cfc4a7d3-5a89-4c26-8019-917095b1cb83?mode=design&sha=97dda325b85a28879064c5e6fd36a1471ba58d90
