### ISSUE TITLE
Stealth mode settings dialogs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2808]
For some unknown reason, all dialogs (tracking parameters, ttl, etc) ask users to enter "Domain name". This is wrong.

1. We should let users edit the current value, not just fill the field
2. There should be the "Cancel" button in the dialog

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Go to Stealth Mode
- Try to change any value 

Expected result:
- There is `Cancel button` in the dialog
- No more `Enter domain` hints
- Current value is visible in the dialog
- New value is saved after dialog confirmation
