### ISSUE TITLE
"New extension" and "New custom filter" dialogs layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2809]
1. The input field does not look right ("browse" margins are wrong)
2. No "Cancel" button
3. Need delete context menu

Also, take a look at the "Import" dialog of user filter and whitelist -- "Overwrite" checkbox margins are wrong there.

**Comment by artemiv4nov** [comment]
Also need delete context menu.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/5095da8f-b126-437f-8462-9d14fccaf7c6
