### ISSUE TITLE
Add "Disable AMP" userscript to the list of default userscripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2815]
We should first develop this userscript :)

**Comment by TPS** [comment]
Why, though?  Not only do I find adblocking AMP pages more efficient, y'all could use 1 of the many extant 1s. (E.g., https://github.com/bentasker/RemoveAMP comes up first from Google search.)

N.B.: To implement #2723?

**Comment by ameshkov** [comment]
There are tons of people who hate AMP so why not? It'll be disabled by default anyway.

**Comment by TPS** [comment]
Nono, I mean, why reinvent _this_ wheel?  Why not just link, e.g., the above userscrip?

**Comment by ameshkov** [comment]
We'd like to avoid including any third-party userscript by default. Userscripts are simply too powerful and dangerous in the wrong hands.

**Comment by ameshkov** [comment]
@artemiv4nov the first **very-very simple** version:
https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.user.js

(Does not work on Google News yet)

Please check that it works properly on Android.
