### ISSUE TITLE
Add Greek AdBlock filter

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#282]
Please add Greek AdBlock Filter:
https://www.void.gr/kargig/void-gr-filters.txt
https://www.void.gr/kargig/blog/greek-adblock-plus-filter/

Requester here - MFB-256-65337

**Comment by ameshkov** [comment]
We'll do it, thank you!

**Comment by ameshkov** [comment]
Done, will be available in the next beta version.
