### ISSUE TITLE
German O2 (Telefonica) VoWifi/WLAN calling (old issue #2334)

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/AdguardForAndroid#2821]
this is a reopening of issue #2334 as i cannot reopen old issue !
the solution descriped there isnt working anymore with Adguard v3
I posted actual logs over at Adguard forum (PM to forum memeber TheHasagi)

_when using ADGuard in proxy auto mode than VoWifi neither VoLTE isnt working whenever i toogle to airplane mode an back.
Then i have to switch Wifi to off and back to on. Than VoWifi is working again.
If VPN mode is used instead than there is no problem at all but the load times with VPN mode are very bad.
So i prefer to use root mode.

Adguard version: v3.1.0
Adguard filtering mode: Proxy auto
Device model: Pocophone F1
Operating system and version: MIUI 10.3.5.0
Rooted or not? Rooted
German provider o2 (Telefonica)
Adguard Forum Link -> https://forum.adguard.com/index.php?threads/problems-wit_h-vowifi-wlan-call.29903/

**Comment by ameshkov** [comment]
@derKief sorry for the very late reply:( Is it still an issue?

**Comment by TheHasagi** [comment]
No response. Will be reopened if needed.
