### ISSUE TITLE
Не сохраняются настройки уведомлений 

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#2826]
Версия Android 9.0.0.222. Версия приложения 3.1.0. Телефон Honor 10.
Захожу в раздел уведомления AdGuard, настройка уведомлений и снимаю галку со статуса защиты. Выхожу. Спустя какое-то время галка автоматически появляется сама там опять же. Помогает только снятие галки через системные уведомления.

**Comment by ministr91** [comment]
Интересная вещь. Снимаю через системные настройки галку со статуса защиты и в приложении она так же снимается, а если наоборот, то не работает. Галка автоматически ставится сама.

**Comment by ministr91** [comment]
Ещё 1 проблема.
Сверху есть значок adguard и знак в виде ключа. Опускаю шторке вниз и знак сверху adguard пропадает и остаётся только знак ключа.

**Comment by TheHasagi** [comment]
@ministr91 

Приветствую, а можно по подробнеее:

Модель телефона
Повторяется ли с [найтли версией](agrd.io/android_nightly)?

**Comment by ministr91** [comment]
Модель Honor 10. Ошибка присутствует.

**Comment by ministr91** [comment]
неправильный Labels поставлен. Это БАГ

**Comment by ameshkov** [comment]
Если это и баг, то не наш. В обоих случаях настройки уведомлений контролируются самим андроидом, мы только их открываем.
