### ISSUE TITLE
Maybe modify some phrases in DNS module?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2827]
It's a little weird that you use DNS filtering for representing the whole DNS module.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/2xUM5B9.png)

![image](https://i.imgur.com/aWjP8Ut.png)
</details><br/>

Maybe modify these phrases in DNS module?
Just a suggestion.
It's up to you.
Thanks.

**Comment by ameshkov** [comment]
We use this phrase everywhere in the docs so not sure about that.

Maybe we'll simply rename it to DNS in v4
