### ISSUE TITLE
Userscript is not injected on Non-browser with HTTPS

### ISSUE THREAD

**Issue by DitFranXX** [AdguardTeam/AdguardForAndroid#2829]
### Steps to reproduce

1. Access HTTPS site on not marked as browser. (I think it is based on android's `Browser` class)
(Https filtering is turned on that app, 3.1.37 nightly)

### Expected behavior

Userscript is applied

### Actual behavior

Not applied on Https, but on http.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 3.1.37nightly
* Adguard filtering mode: LocalVPN
* Operating system and version: 7.1.1
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:  Shadowsocks Connected with Adguard proxy

**Comment by ameshkov** [comment]
HTTPS filtering is disabled by default for a lot of apps:
https://adguard.com/en/blog/android-nougat-release-and-what-does-it-mean-for-adguard-users.html

We keep a pre-defined list of browsers that support it. You can override this in the apps mgmt settings, but I can't guarantee that it will work in the app where you're testing.

**Comment by DitFranXX** [comment]
But, I turned on HTTPS filtering for that app. I can check app's package name on `pref.enforce.https.filtering`.

Don't know why but app communicate servers with tcp:// prefix, Is this means this app can't filtered with HTTPS filtering?

**Comment by ameshkov** [comment]
This just means that the app does not support HTTPS filtering
