### ISSUE TITLE
Other apps don't have access to Internet if Adguard is on and Mobile network is used

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#283]
User doesn't have root access, has Android 4. Everything is fine if he uses WiFi. 

Logs and details are inside ticket:
LDO-752-87754

**Comment by ameshkov** [comment]
@vbagirov could it be that he has "restricted background data" enabled?

**Comment by vbagirov** [comment]
Asked user about it.

**Comment by vbagirov** [comment]
No reply from user, I will close the issue and reopen it in case he replies.
