### ISSUE TITLE
It seems that DNS filters can't be updated.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2830]
1. After checking for updating on 21st June, the DNS filter isn't updated.
downloaded time: 15th June
Old rules count: 39044
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/XMpRo21.png)
</details><br/>

I deleted the original filter and anew added it at once.
downloaded time: 21st June
rules count: 36673
You can see the downloaded time and rules count are different.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NxaYMVm.png)
</details><br/>

2. Now, it's downloded time.
Users may not understand it means the first downloaded time or the last downloaded time.
May you change downloaded time as **the time of checking for updates**?
Or **the last downloaded time**?

**Comment by lancelot-moon** [comment]
Hi, both downloaded time and rules count aren't updated.

**Comment by lancelot-moon** [comment]
It seems that only the information of built-in SDN filter can be updated.

The information of custom DNS filters still can't be updated.

**Comment by admitrevskiy** [comment]
@lancelot-moon hi!
Please, provide me additional info: what custom filter you've tried to update?

**Comment by patrickdrd** [comment]
I guess the one shown in the screenshot?

`https://1hos.cf/mini/`

**Comment by patrickdrd** [comment]
I've installed the latest nightly and I've noticed something else:
the blank (or commented lines are counted too),
e.g. the start is like this:

```
! Title: _gist hosts
! Expires: 1 day


```

so let's say my blocked hosts are 100,
AG says that there are 103 blocked hosts (2 commented lines and a blank one), 
while they are 100
