### ISSUE TITLE
dns request

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#2831]
hello the dns requests blocked by adguardhome no longer return a dns response in the adguard android logs, before the update of the modules in the dns response return NXDOMAIN when the requests were blocked by adguardhome , 

It says requests to proccesed those who are false

<a href="http://zupimages.net/viewer.php?id=19/25/8vhz.jpg"><img src="https://zupimages.net/up/19/25/8vhz.jpg" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/n5od.jpg"><img src="https://zupimages.net/up/19/25/n5od.jpg" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/xxu3.jpg"><img src="https://zupimages.net/up/19/25/xxu3.jpg" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/9uh8.jpg"><img src="https://zupimages.net/up/19/25/9uh8.jpg" alt="" /></a>

**Comment by ameshkov** [comment]
AG for Android does not know that NXDOMAIN is due to AGH blocking and not due to something else.

So there's no mistake, the status is Processed, and there is no DNS answer there in the details. The only thing we can do is https://github.com/AdguardTeam/AdguardForAndroid/issues/2835
