### ISSUE TITLE
Use Android accessibility module to automatically skip YouTube ads

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2832]
This is a feature request submitted by user 2236507. 

> Okay, being a developer I do understand the technical challenge. However I
> come across an app called "Adclear" which does the job by using
> accessibility service of android. It doesn't perform ad blocking on most of
> the case but it clicks on "Skip Ad" button from own after 5 sec of ad
> playing on youtube. Which is still a potential gain on blocking ads. If you
> see that something similar can be implemented (in Android at least) then
> that would be very good to have feature on Adguard.

**Comment by lancelot-moon** [comment]
It's maybe a duplication.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2427
