### ISSUE TITLE
Question: Does AG support/prefer alternate HOSTS file formats?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#2833]
I just ran across https://scripttiger.github.io/alts/ which provides alternate formats for https://github.com/StevenBlack/hosts files.  I'm curious whether _any_ of them are better for AG than the standard list:
- [x] If the `FQDN` lists were to be subscribed under __Custom Filters__, how does that compare to subscribing the equivalent `hosts` file under __DNS Filters__?
- [x] Can AG parse/use the `IPv4_IPv6`, `compressed`, or `mcompressed` lists?  If so, are they more efficient for AG?

**Comment by ameshkov** [comment]
1. DNS filters work with DNS requests only. Custom filters work with real network requests so they're kinda different.
2. AG can parse all of them. The most efficient would be FQDN actually.

**Comment by TPS** [comment]
@ameshkov What would be the best way to use said FQDN list in AG?  It doesn't really work as a custom user filterlist, but it's also not really a `hosts` file, either.…

**Comment by ameshkov** [comment]
@TPS if you're on the nightly build, simply add it to the list of DNS filters (under DNS filtering -> DNS requests blocking).
