### ISSUE TITLE
Add response status to the DNS log entry details

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2835]
Currently, it's unclear what exactly happened when there's no response:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2831

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Enable DNS filtering
- Try to reach any non-existing web site
- You'll see `NXDomain` response in `DNS Answer` section
