### ISSUE TITLE
Black theme for AMOLED

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#2838]
Сделайте чёрную тему (с задним фоном #000000). Это помогает снизить расход батареи на смартфонах с AMOLED экранами.

**Comment by Revertron** [comment]
С какой целью вы оставляете включенным дисплей с запущенным Адгардом настолько долго, что экран съедает батарею?

**Comment by ameshkov** [comment]
Лучше вот сюда все пожелания по темам:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2275
