### ISSUE TITLE
Настройки в разделе Разное "Антитрекинг" 

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/AdguardForAndroid#2839]
Настройки в разделе Антитрекинг>Разное>[Пользовательский****]
Не сохраняются. После изменения значения по умолчанию и применения изменений, значения остаются "По умолчанию"

p.s.
OnePlus 6@ Android 9 

![Screenshot_20190626-061040](https://user-images.githubusercontent.com/26434853/60148622-84e86c00-97da-11e9-8163-b5850276f3a6.jpg)

**Comment by TheHasagi** [comment]
@alvussar 

Попробуйте изменить канал обновления на Nightly и обновиться. Данная проблема не повторяется.
