### ISSUE TITLE
Can't import (large?) DNS filter (Energized Unified)

### ISSUE THREAD

**Issue by DitFranXX** [AdguardTeam/AdguardForAndroid#2840]
### Steps to reproduce

1. Add this filter: `https://raw.githubusercontent.com/EnergizedProtection/block/master/unified/formats/filter`
(plus, It's an adblock filter. I don't know what format should i use. Just following simplified filter)
### Expected behavior

Shows something like `input filter name`

### Actual behavior

![Error](https://user-images.githubusercontent.com/45893338/60173521-e72c8580-9849-11e9-8909-6c786d70ac35.png)

### Your environment

* Adguard version: 3.1.44n
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual)) LocalVPN
* Operating system and version: (e.g. Android 7.1.2) 7.1.1
* Root access:  (e.g. Yes / No) No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: Shadowsocks through Adguard Proxy feature

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Try to import this DNS filter: https://raw.githubusercontent.com/EnergizedProtection/block/master/unified/formats/filter

Expected result:
- You'll see attention dialog: `Downloaded DNS filter is too large and may dramatically slow down AdGuard performance. Are you sure you want to continue?`
- Tap `Add` button to continue filter import or `Cancel` to abort operation.
