### ISSUE TITLE
Do not print proxy name/address in the log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2841]
When a user sends AdGuard logs to the support service, they can see the socks proxy address in the users' logs:
`Using outbound proxy SOCKS5 username@proxy_address` 

I think it makes sense to hide the real proxy address and the username.

**Comment by sfionov** [comment]
This is CoreLibs' message

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #982](https://github.com/AdguardTeam/CoreLibs/issues/982) via [**ZenHub**](https://www.zenhub.com/)
