### ISSUE TITLE
AdGuard crashes when setting up assistant

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2848]
Sometimes when a user tries to change the setting filtering for the application through
AdGuard assistant - it crashes.
**1**. Tap to AdGuard assistant
**2**. Begin to open the settings and AdGuard is crashed
### Customer ID 

2166006
**Logs in Ncloud**
### Your environment

* Adguard version: 3.1.0 / 3.1.37
* Adguard filtering mode: Local VPN
* Device model: Samsung J415FN
* Operating system and version: Android 9

**Comment by Eugene-Savenko** [comment]
check the support ticket if you need logcat logs

**Comment by TheHasagi** [comment]
@Chinaski1 

Check with the latest Nightly.

**Comment by Kiborg-Man** [comment]
> Check with the latest Nightly.
On the last Nightly also crashes
На последней ночнушке тоже крашится.

**Comment by Kiborg-Man** [comment]
> Check with the latest Nightly.


On the last Nightly also crashes
На последней ночнушке тоже крашится.

**Comment by Chinaski1** [comment]
Still the same.

**Comment by Chinaski1** [comment]
Last nightly version - fixed.
