### ISSUE TITLE
[Feature request] disable protection automatically when using device as a hotspot

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#285]
I would like to request an enhancement to Adguard. I frequently use tethering on my phone and right now I have to manually turn off protection on Adguard each time. You currently show a warning that tethering doesn't work with VPN. Instead of the warning is it possible for you to just turn off protection automatically when you detect tethering and turn it back on once tethering stops? Also perhaps add a checkbox somewhere in the app settings to control this in case not every one likes the functionality. Thanks

ZID-144-93771
QNE-467-85160

**Comment by ameshkov** [comment]
Makes sense, we'd better "Pause" protection and "Unpause" it again when tethering is disabled.

**Comment by ameshkov** [comment]
Duplicate for #247

**Comment by TPS** [comment]
@ameshkov How's this related to #247 @ all?!

**Comment by ameshkov** [comment]
Ops:)

**Comment by ameshkov** [comment]
It's just this feature request was implemented in the latest beta along with #247.

So it guess it is not a duplicate, just resolved:)
