### ISSUE TITLE
Change the DNS query log item

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2852]
### Filtering log

For the filtering log:
https://uploads.adguard.com/up04_yts6b_Monosnap.png

It should be smth like this:
```
ad.doubleclick.net
A, 0.0.0.0

ad.doubleclick.net
AAAA, [::]
```

### Log details

We don't need "Request URL" there

**Comment by admitrevskiy** [comment]
Resolved.

Testing instructions for QA:
- Reinstall AG
- Enable DNS Filtering
- Surf the web
- Go to `Filtering Log`
- You'll see first DNS Answer or response code instead of `dns://<request_url>` in query log item
