### ISSUE TITLE
Question: Youtube ads and adguard

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForAndroid#2856]
Only a simple question.

The situation is still this? 
https://kb.adguard.com/en/android/solving-problems/youtube-ads

Thank you

**Comment by BooBerry** [comment]
AG for Android can't remove the ads from the YouTube app. There's a couple 'workarounds';

1) Use a modded YouTube app that has ads removed, e.g. YouTube Vanced.
2) Use a third-party YouTube app like NewPipe.
3) Use YouTube in a web browser, where AG for Android can still remove the ads.
