### ISSUE TITLE
Ring doorbell App issue

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2857]
### Steps to reproduce

1. [Install the app](https://play.google.com/store/apps/details?id=com.ringapp&hl=uk)
2. If protection is ON - Unable to connect to the camera
3. Disabling HTTPS filtering does not help.

**Logs in NCloud**

### Customer ID 

2237004
### Your environment

* Adguard version: 3.1.37
* Adguard filtering mode: Local VPN
* Device model: Samsung - G935T
* Operating system and version: Android 8

**Comment by TheHasagi** [comment]
@Chinaski1 

And if you turn off the whole filtering for the application?

**Comment by Chinaski1** [comment]
We are waiting for a response from the user

**Comment by TheHasagi** [comment]
Waiting for response from a customer.

**Comment by TheHasagi** [comment]
User did not confirm that the problem still exists.

**Comment by Chinaski1** [comment]
I have a request from [the user](https://forum.adguard.com/index.php?threads/psa-adguard-breaks-setting-up-ring-doorbell.37492/) who met a similar issue.
Time | Date: 13:41 29.02.2020
Archive with the logs added to NCloud.

**Comment by TheHasagi** [comment]
@Chinaski1 

So if he turns off the whole filtering for the application - does it help or not?

**Comment by Chinaski1** [comment]
Yes, if you turn off the protection completely, there is no issue.
Maybe we should add this application to the default filter exception list?

**Comment by TheHasagi** [comment]
Will be excluded with the next update.
