### ISSUE TITLE
Adguard and Lenovo Security compatibility - doesn't start with system boot.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#286]
User uses VPN mode, his phone is rooted.

Also problems with Adguard service - see ticket for details: DJE-692-91037

Logs are also inside the ticket.

**Comment by ameshkov** [comment]
That is not a program bug.

1. The issue is seems to be caused by Lenovo Security
2. To find out why it is not started on device boot: ask user to send INFO log shortly after device boot.
3. The same about "remove from task manager". What does that mean? What manager?
Does he mean "Recent apps"?

**Comment by vbagirov** [comment]
1st line support replied to user.

**Comment by samalero** [comment]
Hello, right. This is not program bug, this is bug of lenovo android firmware. Please, close issue.

**Comment by ameshkov** [comment]
@samalero thank you for clarification, closing this issue then.
