### ISSUE TITLE
adm (advanced download manager) browser https filtering

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2866]
when I enable https filtering for adm (advanced download manager) browser,
I get popups saying that "the certificate can't be trusted, do you want to continue?"
I'm pressing ok and another pops up and so on,
can you fix that?

**Comment by TheHasagi** [comment]
@patrickdrd 

Please, provide the link to that browser

**Comment by patrickdrd** [comment]
I think it's similar to this issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2861

adm browser needs to be added to the known browsers list 

there isn't a direct link for the browser app,
because the browser is a component of the adm app:
https://play.google.com/store/apps/details?id=com.dv.adm

I tested on a rooted device (certificate is in system store) and
https filtering works fine this way,
but it doesn't when certificate is in user store

**Comment by ameshkov** [comment]
> but it doesn't when certificate is in user store

Well, that's because this app does not trust user certs
