### ISSUE TITLE
UI issue in user filter editor with dark theme

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2867]
### Steps to reproduce
1. Add or edit any rule

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/60528261-babab280-9cfc-11e9-9e76-809d82aef261.png)

</details>

### Your environment
* Adguard version: 3.1.53n

**Comment by TheHasagi** [comment]
Unable to reproduce with the latest Nightly v3.1.177n

**Comment by Alex-302** [comment]
Reproduced in 3.1.83n after clean install and import settings with dark theme. The rule was added using Assistant.
