### ISSUE TITLE
Persistent internet connectivity issues when AdGuard is on

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2868]
### Steps to reproduce
1. Enable AdGuard
2. Some time later AdGuard will start blocking all access to the internet
3. Problem can be resolved by restarting the phone or switching it to plane mode
4. Problem can only be reproduced if AdGuard is on

### Version persistence
Began sporadically with 2.11, continues until today

### Attempted solutions
1. Changing / disabling DNS filtering did not help;
2. Enabling pref.vpn.disable.pause / pref.vpn.disable.reconfigure did not help;
3. Background optimization did not help.

### Expected behavior
AdGuard shouldn't break internet connection

### Actual behavior
AdGuard sporadically shuts down the connection

### Customer ID & Debug Logs
1872696

### Your environment
* Adguard version: 3.1.0
* Adguard filtering mode: Local VPN
* Device model: Xiaomi Redmi Note 5
* Operating system and version: Android 9
* Root access:  None
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: None found

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/2842
