### ISSUE TITLE
Fix some minor UI issues

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#2870]
- [x] 1. We should remove all bottom dividers from last rows of all list views. @AlikhanAliev, please provide a list of the problematic views.
- [x] 2. Bug: when I am trying to add a new user filter rule, the text field doesn't get focus
- [x] 3. Bug: stop saving the last added custom filter URL, this is annoying. However, we should keep this functionality for the user filter and whitelist import dialogs.
- [x] 4. Don't forget to restore the divider in the extensions list: https://uploads.adguard.com/up04_6exgv_Switches_and_dialogs_-_Android_app_-_New_extension_step_3.png

Mockups:

* [DNS](https://share.goabstract.com/37f319c7-37ad-45fa-b05f-1a017c41d8d8)
* [User scripts](https://share.goabstract.com/3c4a6845-458b-4df9-b974-3bbccfd1c7a1)
* [Filters](https://share.goabstract.com/291ca12f-dc7c-440d-9e8c-94f19f646e4f)

**Comment by ameshkov** [comment]
Don't forget to restore the divider in the extensions list: https://uploads.adguard.com/up04_6exgv_Switches_and_dialogs_-_Android_app_-_New_extension_step_3.png

**Comment by chernikova-yana** [comment]
Bottom dividers 
@admitrevskiy 

- Home/Settings/DNS Filtering/SelectDNSserver/RecommendedDNSproviders/Quad9 
- Home/Settings/StealthMode/description(Stealth Mode module protects your identity…)
- Home/Battery Usage/description(When AdGuard is on...)
- Home/Settings/Network/Proxy/description(A proxy server is...)
- Home/under the date and above Ads blocked

**Comment by admitrevskiy** [comment]
Done.
