### ISSUE TITLE
Adguard network issue

### ISSUE THREAD

**Issue by omaryey** [AdguardTeam/AdguardForAndroid#2872]
I sometimes need to disable and re enable adguard to resume the internet.
My device : A8 2018
OS : Android pie
Adguard V. : 3.1.0
Dns filtering : ON ( cloudflare server )
Adguard filtering method : Local VPN
Antivirus : Kaspersky mobile security 
Root access : No
I reported this to the support team about two weeks but no response.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/2842
