### ISSUE TITLE
Livejournal.com, не раскрываются посты

### ISSUE THREAD

**Issue by Tremm** [AdguardTeam/AdguardForAndroid#2876]
На livejournal.com стало невозможно развернуть полный текст записи. Вместо этого идёт переход на страницу с постом. Если adguard выключить, то все работает как надо. Начало появляться после вчерашнего обновления русского фильтра. До этого была реклама Я.Д, но посты раскрывались. Теперь нет рекламы, но и посты не раскрываются

Steps to reproduce
https://strangernn.livejournal.com
1. Переходим в любой блог
2. Ищем пост, который не помещается полностью на странице
3. Жмём на иконку для раскрытия всего поста
4. Видим переход на страницу с постом

### Expected behavior
При отключении adguard нажатие на иконку раскрытия просто раскрывает содержимое поста на той же странице.

### Actual behavior
По факту нажатие на иконку работает как клик на заголовок поста, т.е. осуществляется переход на страницу поста

Screenshot:
![Screenshot_20190704-131130](https://user-images.githubusercontent.com/52530603/60659344-d5f10380-9e5d-11e9-8172-13effeba6905.png)

### Customer ID 
2058596

### Your environment
* Adguard version: 3.1.61n
* Adguard filtering mode: Local VPN, DNS
* Device model: Nokia 6
* Operating system and version: Android 9
* Root access:  No
* Any other apps that can start VPN: nope

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/2ab4332d6bb3ce338b3b74d337b134bad8cac3a1
