### ISSUE TITLE
Change modules descriptions -- use rich formatting

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2878]
@AlikhanAliev please provide the list of the places where you'd like to have "rich" descriptions.

Also, I suppose we can add some useful links to the descriptions, maybe link KB directly.

List of screens:
- filters
- custom filters
- dns filters
- extension details
- extension adding dialog
- dns server details

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/8d1d4ce0-7e83-47c8-ab37-2894e7e9fd37?mode=design&sha=29cac72a0e3cf3d187f601c9c11b48e20613ee91

**Comment by admitrevskiy** [comment]
Done (v3.3)
