### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2879]
- [x] 1. Remove the top border from the "bottom" buttons 
- [x] 2. If a button is over the content, there must be a shadow: https://uploads.adguard.com/up04_l769m_AdGuard.png
- [x] 3. Use `+ add` button instead of the floating button on the "Custom filters" screen.
- [ ] 4. Try to keep the same color of the navigation bar when a dialog is opened.

**Comment by admitrevskiy** [comment]
Done (v3.3) 

I've found no way to keep the same color of the navigation bar when a dialog is opened, because changed color is a part of a dialog.
