### ISSUE TITLE
[Feature request] App specific custom filters

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#288]
User would like to see an option to create custom filters that affect only specific apps traffic. Maybe it is better to make possible adding rules modificators to affect only specific apps based on package names.

http://forum.adguard.com/showthread.php?8801

**Comment by ameshkov** [comment]
This makes sense, I guess we should implement the same in AG for Windows.

**Comment by TPS** [comment]
This is now done via `$app=`, right?

**Comment by ameshkov** [comment]
Yeah, so this is a duplicate
