### ISSUE TITLE
 (Мелочь) Основной переключатель требует два нажатия

### ISSUE THREAD

**Issue by Tremm** [AdguardTeam/AdguardForAndroid#2882]
Android 9, Nokia 6
Nightly 3.1.61n

На главном экране основной переключатель требует двух нажатий для срабатывания. При первом нажатии только подсвечивается.
Штука неочевидная, первый раз сидишь и ждёшь, пока сработает.

Хотелось бы вернуться к одному нажатию, либо добавить пояснение, что требуется второе нажатие.
![Screenshot_20190704-151645](https://user-images.githubusercontent.com/52530603/60667036-32115300-9e71-11e9-93b9-70065e0af675.png)
![Screenshot_20190704-151655](https://user-images.githubusercontent.com/52530603/60667053-389fca80-9e71-11e9-87c4-4c6857135226.png)

**Comment by ameshkov** [comment]
Дубликат: https://github.com/AdguardTeam/AdguardForAndroid/issues/2883
