### ISSUE TITLE
Crash with adding custom filter list.

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#2888]
Add this custom filter to filter list: https://gitee.com/banbendalao/adguard/raw/master/ADgk.txt
When AdGuard tries to restart protection it crashes.

3.1.77 Nightly
Android 9

It seems it does not matter which list you add, even an empty one is causing the crash:

https://github.com/BlazDT/Test/blob/master/test.txt

**Comment by huangchuxing** [comment]
When will this problem be solved, and many people will be affected?

**Comment by BooBerry** [comment]
Likely this issue: https://github.com/AdguardTeam/CoreLibs/issues/1005

**Comment by admitrevskiy** [comment]
Resolved in #2900
