### ISSUE TITLE
Add silent update action as a long-tap on the update button on MainActivity

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#2890]
Some users complain that they don't need our cute new update activity with a lot of information and shiny progress-bars.
I propose adding a "silent update" action as long-click action to our main update button. It can update fully silently or show short toast like "Updated: 4 filters, 2 userscripts, new app version is ready".

**Comment by sviperz** [comment]
Good suggestion! Please consider to perform silent update using Quick Shortcut on the launcher icon as well. It's really not necessary to show additional activity while trying to quickly update what is updatable right now.

**Comment by ameshkov** [comment]
Tbh, I don't think we need this for the main activity.

Quick shortcut idea, on the other hand, makes perfect sense.

**Comment by artemiv4nov** [comment]
In the end, we'll change behavior of "check updates" shortcut: it will show only toast about updates' results.
