### ISSUE TITLE
cosmote apps don't work with https filtering on (certificate in system store/root)

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2891]
I checked all (or almost all) my apps with https filtering on (certificate in system store),
all of them worked, even banking apps,
the only ones that refused to work were the two cosmote carrier apps:
https://play.google.com/store/apps/details?id=gr.cosmote.myaccount.widget
https://play.google.com/store/apps/details?id=gr.cosmote.whatsup

one of them wasn't opening and the other was saying that I don't have internet,
when I disabled https filtering for them,
they worked fine,

they both hit graph.facebook.com, 
which I've blocked for them,
but I don't think that it matters,
because it was still blocked even after disabling https filtering

### Your environment
latest nightly on nougat (rooted)

**Comment by TheHasagi** [comment]
Well, the apps are working fine. Seems like you did more than just restricted graph.facebook.com for these apps. Can you export your settings and send it to support@adguard.com (note my nickname in the message so I’ll be able to check)

**Comment by ameshkov** [comment]
@TheHasagi root + cert in the system store

**Comment by TheHasagi** [comment]
@ameshkov

Affirmative, tested with rooted Nexus 6p. Apps are working fine.

**Comment by patrickdrd** [comment]
with my settings?

I've sent the settings, nobody responded.. yet

also, the settings I've sent are modified,
https filtering is disabled for these apps,

and last but not least, ok the cosmote app loads,
but this doesn't mean that it works, 
because as soon as it loads there's a message saying "network not available" (in greek),
the right option is connect again (in greek again),
but no matter how many times you tap it there's no connection at all

I got the same message with https filtering disabled for the cosmote app,
but after tapping a couple of time on try again, I'm in,
there's no way to get in with https filtering enabled

**Comment by TheHasagi** [comment]
@patrickdrd 

Got your settings. But it’s impossible to test these apps without carrier service. We will add them to the exclusion list, thanks.

**Comment by patrickdrd** [comment]
no, it's not impossible, I first noticed the problem when I was connected with wifi (no sim card on this device at all)
also, I connected two or three times today with a sim of a different carrier,
anyway, do what you think it's best
