### ISSUE TITLE
no encrypted sni when using dns-over-https?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2893]
I'm using dns-over-https (cloudflare) and
when testing with this page:
https://www.cloudflare.com/ssl/encrypted-sni/

it says I don't have encrypted sni

> Your browser did not encrypt the SNI when visiting this page.
> Anybody listening on the wire can see the exact website you made a TLS connection to.

same thing with dns-over-tls

why is that?

I don't know much about the subject,
but is it possible to have encrypted sni?

**Comment by TheHasagi** [comment]
@patrickdrd 

Not related to AdGuard, better to ask it [here](https://support.mozilla.org).
