### ISSUE TITLE
MAC address spoofing in stealth mode

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardForAndroid#2899]
TFL for London who operate the London underground have started tracking users via their mac address, your mac gets recorded when it pings a TFL wifi hotspot not when your connected only when pinging it.

So the stealth tracking we have in the adguard app is kind of defeated, is there any plans to randomise the mac of wifi and/or bluetooth ?

The current TFL solution to opt out is to turn off your wifi, there is no opt out list for them to not track you (i have emailed them).

Is it possible to have the option in adguard to randomise your mac address for each wifi point that gets pinged/connected to and have a whitelist for wifi points that you want to have your real mac address?

A bit more about the TFL tracking:

https://www.gizmodo.co.uk/2017/09/l...rything-we-learned-from-tfls-official-report/

Thanks

**Comment by Revertron** [comment]
MAC randomization is done on driver level by the OS.
If you have an old OS with root, you can change your MAC as you wish.

**Comment by versavius** [comment]
I can't downgrade and going to an old os undoes the point of making everything more secure by introducing bugs and security issues that the newer is fixed.

**Comment by Revertron** [comment]
@versavius You didn't understand me :)
If you have Android 9, it will randomize your MAC on its own.
If you have older Android version you need to make it by yourself.

**Comment by versavius** [comment]
Ahh ok thanks ! apologies ! i am on android 9

**Comment by versavius** [comment]
This actually does details about this feature:

https://www.androidpolice.com/2018/03/08/android-p-feature-spotlight-per-network-mac-address-randomization-added-experimental-feature/

Ok so it looks like the old implementation only randomized 'probe' requests for a network (so established connections still revealed the real MAC), while Android P uses the randomized address for the actual connection.

What might be useful is in adguard to display the mac so we know it is being randomised or perhaps some sort of logging to know if this is an issue across adguard users where we think we can't be tracked by mac but actually were believing the companies that this feature works but in face it does not and we can be tracked if that makes sense ?

**Comment by versavius** [comment]
Just a bit more information about mac address tracking:

You are getting companies like this one below which is tracking people by IP address:

https://www.theregister.co.uk/2019/07/10/netlify_log_analytics/

and TFL tracking by mac address:

https://www.wired.co.uk/article/london-underground-wifi-tracking

So it looks like its just a matter of time before companies start tracking by IP and mac address as above so if we started randomising these then on top of the current stealth devices we really should be difficult to track online.

**Comment by versavius** [comment]
Interestingly enough some researchers have just proven how the mac address randomisation of Bluetooth does not work and you can track the users:

https://www.theregister.co.uk/2019/07/12/untraceable_bluetooth_exposed/

So unless we really randomise our mac address all our stealth attempts are a tad limited.

**Comment by ameshkov** [comment]
Randomizing MAC address is not possible without root.

I'll keep this feature request open, but I've marked it as "low priority".

**Comment by versavius** [comment]
That's a shame, is there anything that can be like how the IP address is 
spoofed?

**Comment by qquiderr** [comment]
on mobile is currently possible use native OS "mac randomizer" but only for wifi, no mobile data. On windows pc you can use software like "tmac".  This is proof of you can hide your mac. Can adguard add "hide mac" or "mac randomize" into app? Its very good feature for stealth mode like ip hide and etc.
