### ISSUE TITLE
Adguard doesn't work with LTE network.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#290]
Everything is fine with Wi-Fi, but upon switching to LTE Adguard closes. If user starts it manually and enables protection, no apps or browsers are able to access network.

Logs here: KLX-800-99856

Could it be same as #283?

**Comment by ameshkov** [comment]
It is very likely to be the same as #283

**Comment by vbagirov** [comment]
No reply from user, I will close the issue and reopen it in case he replies.
