### ISSUE TITLE
FairEmail - Outlook Timeout

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#2905]
### Steps to reproduce

1. Install FairEmail with Outlook account
2. Sync email
3. Email sync timeout

### Expected behavior

Email synchronised.
### Actual behavior

Email is not synchronised, and the following error occurs.

`Couldn't connect to host, port: outlook.office365.com, 993; timeout 20000 failed to connect to outlook.office365.com/2603:1016:401:1003::2 (port 993) from /2001:db8:ad:0:ff:: (port 48748) after 20000ms: isConnected failed: ENETUNREACH (Network is unreachable) isConnected failed: ENETUNREACH (Network is unreachable)`

The DNS logs do not show anything being blocked.
Turning off filtering for FairEmail clears the fault.
Contact @jslawler on Telegram for the logs if required.

### Customer ID 

2257234

### Your environment

* Adguard version: Latest nightly 
* Adguard filtering mode: Local VPN
* Device model: OnePlus 6
* Operating system and version: OmniROM latest weekly.
* Root access: Yes
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: No

**Comment by ameshkov** [comment]
Well, IPv6 is unavailable so that's why. The question is why is it not trying IPv4.

This issue needs to be re-tested when this issue is fixed: https://github.com/AdguardTeam/CoreLibs/issues/993

**Comment by jslawler** [comment]
> Well, IPv6 is unavailable so that's why. The question is why is it not trying IPv4.
> 
> This issue needs to be re-tested when this issue is fixed: [AdguardTeam/CoreLibs#993](https://github.com/AdguardTeam/CoreLibs/issues/993)

I've subscribed to #993 and will re-test when that issue is closed out.

**Comment by artemiv4nov** [comment]
Fixed in nighty 3.2.110. @jslawler check it, please

**Comment by jslawler** [comment]
Fixed.

**Comment by ameshkov** [comment]
@jslawler awesome, thank you so much for testing it!
