### ISSUE TITLE
Error while saving exported settings json file (replace with existing)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2906]
If you try to export the settings with the same as existing one it should ask you to replace the item or no, actually it saves the file with <name>(1).json format, but shows an error message (see the screenshot)

### Steps to reproduce

1. Open Adguard - settings - general - export settings - save the file with a name a.json
2. Go back to general - export settings - try to save the file with name a.json - tapn to save

### Expected behavior

It should ask you to replace the file with an existing name

### Actual behavior

It saves the file (actually), but shows an error (that’s incorrect)

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagi57dlj.jpg)

</details>

**Comment by admitrevskiy** [comment]
Done.
