### ISSUE TITLE
facebook & messenger images not shown (https issue)

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2907]
besides the issues with the cosmote apps I posted here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2891

I found another issue with facebook apps (facebook & messenger):
when https filtering is on for these two and dns is dns-over-https (cloudflare or google, doesn't matter),
issues with images arise, they aren't shown, just a circle in the center and
when I press it nothing happens,

if I disable https filtering or change from dns-over-https to regular dns,
everything works fine,
At first I used the no-https filtering option, but I finally opted for the second one,
because I'm using the internal browser,

the device is rooted, and adguard is running in proxy mode with certificate in the system store

**Comment by ameshkov** [comment]
Do you have the certificate moved to the system store?

**Comment by ameshkov** [comment]
Ah, sorry, I see that you have.

**Comment by patrickdrd** [comment]
after further testing, I see that there are two problems with https filtering (adguard certificate in system store) with both these apps (facebook and messenger):
1) lazy images loading doesn't work, I mean images that are loaded-downloaded over scrolling, aren't shown and
2) some links fail to open with these apps' internal browser with a certificate cannot be trusted error,
if you click on the same link again they do work, but it's a bit annoying,
so,
for the time being, I disabled https filtering for these two apps and enabled external browser

please check and fix

**Comment by ameshkov** [comment]
I've just realized that this is not a bug.

Facebook uses SSL pinning, HTTPS filtering won't work for their domains. It may seem to be working due to the fact that AdGuard is able to detect such cases and add the domains to temporary exceptions.
