### ISSUE TITLE
many app restarts (Initializing exception handler with enabled OutOfMemory handling) - can adguard run on old(er) devices?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2908]
I've installed adguard on an older device running android lollipop, with 1gb ram (rooted) and
I've noticed it restarts often,
my latest setup is system store certificate and I switched to local proxy,

I'm attaching the log:
[4_5848345559806510494.log](https://github.com/AdguardTeam/AdguardForAndroid/files/3376535/4_5848345559806510494.log)

**Comment by Revertron** [comment]
Try these steps:
1. Disable battery optimization for AdGuard in OS settings.
2. Enable persistent notification in AdGuard.
3. Disable DNS-filtering module, and any not so needed filters. It will free some memory and OS will not kill AdGuard every time RAM is needed.
4. Try to enable `pref.root.set.oom_adj` flag in low-level settings in AdGuard. It will periodically rise priority of AdGuard's process and prevent OS from killing it.

**Comment by patrickdrd** [comment]
> 4\. Try to enable `pref.root.set.oom_adj` flag in low-level settings in AdGuard. It will periodically rise priority of AdGuard's process and prevent OS from killing it.

I didn't know about this setting, your low-level settings guide is out of date I think:
https://kb.adguard.com/en/android/solving-problems/low-level-settings
I changed in on my nougat device too

**Comment by sfionov** [comment]
There are strange CoreLibs error messages of bufferbloat. May be it triggers the crash. If it happens often, can you provide debug log?

**Comment by patrickdrd** [comment]
what do you mean? I provided debug log? do you mean another? or logcat?

**Comment by sfionov** [comment]
Provided log is written without debug log level on :(
Can you please write debug log?
To write debug log, change logging level to "Record everything" in Advanced settings. After issue is reproduced, export logs using application (this function cuts off some sensitive data like cookies from your logs) and send it to devteam@adguard.com.

**Comment by patrickdrd** [comment]
nevermind, I uninstalled it because, besides the AG restarts, I noticed high cpu usage too, 
I think android was killing it (even though I've had a persistent notification for it) because AG demands much memory and
this device doesn't have (only 1gb),
so I can say that AG has become good with so many functions etc but it wouldn't be recommended for older, low-end devices
