### ISSUE TITLE
Refactor exporting/importing of settings

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#2910]
We need exporting/importing of application settings with versioning.

**Comment by admitrevskiy** [comment]
Done (v3.3)

Testing instructions for QA:
1) Current version
-Reinstall AG
-Export settings
-Reset settings
-Import settings

2) Older versions
-Install AG v2.12/3.0/3.1/3.2
-Customize settings
-Export settings
-Install AG v3.3
-Import settings

- Expected result:
-Settings imported successfully
