### ISSUE TITLE
Is $protobuf rule not supported on Android?

### ISSUE THREAD

**Issue by gontazaka** [AdguardTeam/AdguardForAndroid#2911]
I've checked the issue and filter below. seems to support it
- issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/573
- filter: [AdGuard Mobile Ads filter](https://filters.adtidy.org/windows/filters/11.txt)

### Steps to reproduce

1. Add following rules to User Filter
`||googleapis.com/youtubei/v1/search?$protobuf=1|2|3`
2. Search in the YouTube app

### Expected behavior

The search should fail and some errors should occur
_Log Details.Status = Modified(?)_

### Actual behavior

The search completes successfully
_Log Details.Status = Processed_

<details>
<summary>Screenshot: </summary>

YouTube 14.25.57
YouTube Vanced 14.21.54 is also the same behavior as YouTube app.

![protobuf (1)](https://user-images.githubusercontent.com/40248057/60980287-26d98e00-a36f-11e9-9476-827fe8d22a86.png)
</details>

### Your environment

* Adguard version: v3.1.84η(1.4.79cl)
* Adguard filtering mode: Local VPN
* Device model: Oneplus 5T
* Operating system and version: Android 9.0
* Root access:  Yes
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: No

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1018](https://github.com/AdguardTeam/CoreLibs/issues/1018) via [**ZenHub**](https://www.zenhub.com/)
