### ISSUE TITLE
Some HTTPS tunnel connections URLs have tcp:// prefix

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2912]
This needs to be looked into. 

It looks like an "empty" connection with no data actually sent through it. Anyways, it should've had `https` protocol and not `tcp`.

> Hi. Indeed enabling HTTPS Inspection improved the situation.

> Upon closer examination of logs and rules, I only have problems with TCP and UDP connections such as tcp://www.google.com

> I already enabled HTTP Inspection for Chrome. I do not have a specific rule for TCP connections to that URL. 
> What confuses me is the "Processed" status in the log.

> Example screenshot:
> ![ScreenshotCapture_2019_07_06_07_39_40_167](https://user-images.githubusercontent.com/17823400/60751662-00f46800-9fc2-11e9-8869-fafc8f839582.png)

_Originally posted by @SergeiShir in https://github.com/AdguardTeam/AdguardForAndroid/issues/2863#issuecomment-508896738_

**Comment by artemiv4nov** [comment]
Waiting for fix in https://github.com/AdguardTeam/CoreLibs/issues/1029

**Comment by artemiv4nov** [comment]
Fixed in the latest nightly.
