### ISSUE TITLE
[Feature Request] Blocked Threats

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardForAndroid#2914]
Adguard is great for blocking threats and i can see the number of threats blocked but it would be nice to know what the threats were and where they came from so i can avoid those sites in the future?

Is it possible that when we click on the "threats blocked" it gives us a little log file or something of what was blocked?

Thanks

**Comment by d0x360** [comment]
Yes this would be extremely helpful.  I've never been able to determine what the "threat" was from the logs

**Comment by d0x360** [comment]
What feature?  I'm sorry for opening this, I wish GitHub had a question section.  I bought 20 licenses between PC and mobile for friends & family to make up for it lol. 

I don't recall this ever being a feature on 3.x.x

Do you mean you're removing the blocked threats statistic?  The log?  

I would guess the mention of threat on the stats so I have a final question on the issue.

What did Adguard 3.x.x internally define what constituted a "threat" in the first place?

Thanks & take care.
