### ISSUE TITLE
Analyze logs and Add Kaspersky internet security to the exceptions by default

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2917]
We need analyze logs to set the reason of application net connection breaking.

if logs will be clear, please, add the `com.kms.free` package to the filtering exception list.

**Comment by admitrevskiy** [comment]
Done.

**Comment by admitrevskiy** [comment]
Looks like `Kaspersky internet security` app can't process HTTP response after CL cuts out `Content-Length` and replaces it with `Transfer-Encoding: chunked`

Anyway, this issue should be retested after new CL release.

**Comment by admitrevskiy** [comment]
Looks like CL release hasn't solve this issue and `com.kms.free` should be left in the exceptions list
