### ISSUE TITLE
Intercept abp:subscribe and adguard:subscribe links

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2918]
This is useful for adding custom filter lists. For instance, from this website: https://filterlists.com/

**Comment by admitrevskiy** [comment]
Done (v3.3)

Testing instructions for QA:
- Reinstall AG
- Go to https://filterlists.com/
- Try to subscribe for any filter

Expected result:
- In app with not activated license you will see Promo activity
- In app with activated license you will see `Add new Custom Filter` dialog with filled `url` field

**Comment by ameshkov** [comment]
@admitrevskiy you should also test that it works on https://adblockplus.org/subscriptions

**Comment by admitrevskiy** [comment]
@ameshkov I've retested this issue with https://adblockplus.org/subscriptions and it works fine. 
`subscribe.adblockplus.org` is replaced with with `adguard:subscribe`
