### ISSUE TITLE
Add COSMOTE and whatsup application to the exclusions

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2920]
Please add these apps to the https exclusion list. #2891 

COSMOTE: 
gr.cosmote.myaccount.widget
gr.cosmote.myaccount.widget.Activities.SplashScreenActivity

Whatsup:
gr.cosmote.whatsup
gr.cosmote.whatsup.Activities.MainUserScreenActivity

**Comment by akmLaVx** [comment]
Filtering log records from the original submitter: 1648013

**Comment by admitrevskiy** [comment]
Done.
