### ISSUE TITLE
Feature request: Make the update screen to display which filters were updated immediately

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2921]
### Steps to reproduce
1. Update to 3.1.84n+
2. Update filters through the new Update screen
3. Tap on "Filter updates" to have AdGuard display which exact filters have an update available or were updated

### Expected behavior
AdGuard should display update data immediately, without a tap

### Actual behavior
AdGuard displays this data after a tap

<details><summary>Screenshot:</summary>

![img](https://user-images.githubusercontent.com/33634917/61159131-aac47f00-a503-11e9-993d-318073f74b7d.jpg)

</details>

### Customer ID 
2119398

### Your environment
* Adguard version: 3.1.84n
* Adguard filtering mode: Local VPN
* Device model: Samsung SM-N960U
* Operating system and version: Android 9.0
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: None detected

**Comment by TheHasagi** [comment]
@akmLaVx 

This is correct behaviour, updated filters are shown after a tap.

**Comment by akmLaVx** [comment]
Yeah, that's how it behaves now. The user wants the updated filters to be displayed immediately, without a tap.

**Comment by Revertron** [comment]
> The user wants the updated filters to be displayed immediately, without a tap.

Other users want fully silent updates :)
