### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardForAndroid#2923]
Ok so I have a niggling issue, it's not a pic oblem but take the app in this screenshot I can see 7 adverts blocked which is great but since I paid for this app there should be no ads, so no issue with adguard as it's doing what it's meant to :)

What would be good is if I could click on each or the blocked items and get a filtered log of those items, it would it super easy to then go back and challenge that app maker as to what is going on..

Thanks

![Screenshot_20190713-121913_AdGuard](https://user-images.githubusercontent.com/11394779/61170966-b8f8b680-a568-11e9-87f4-0d2ae04dcf67.jpg)

**Comment by zzebrum** [comment]
@versavius I think [that's](https://github.com/AdguardTeam/AdguardForAndroid/issues/2412) what you want.

**Comment by versavius** [comment]
Yes thats right ! were basically talking about wanting the same thing here:

https://github.com/AdguardTeam/AdguardForAndroid/issues/2412

**Comment by Nzzyme** [comment]
@versavius - You can always see the filtering log to see the connections that the particular app makes (Use filter and only show blocked entries).
