### ISSUE TITLE
Random performance on galaxy s4

### ISSUE THREAD

**Issue by larbolo** [AdguardTeam/AdguardForAndroid#2924]
###Actual behavior 

started using the beta app about 2 days ago and have noticed some heavy processing overheat and a noticeable constant slow WIFI connection.
Note: all filters are running at the same time + the adguard dns server and the Https certification anyway
so the phone vulnerability can be the problem itself
  
**User ID**: 2261511 

### environment :
* Adguard version: beta
* Adguard filtering mode:Local VPN 
* Device model: galaxy s4
* Operating system and version: Android 5.1
* Root access: No

**Comment by zzebrum** [comment]
@larbolo, first of all, try to use recommended filters only, e.g. filters enabled by default + some language-specific filters if you need. Not a good idea to enable all filters.

**Comment by larbolo** [comment]
ok, i will

**Comment by larbolo** [comment]
performance improved after default settings reset 
it looks like activating all filters at the same time wasn't a good idea at all

**Comment by ameshkov** [comment]
> it looks like activating all filters at the same time wasn't a good idea at all

Definitely not a good idea:)
