### ISSUE TITLE
Проблемы с помощником!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#2929]
На андроид 5 в гугл хром через панель уведомлений нельзя оькрыть!  К тому же, на андроид Н, в браузере опера(не мини) ,при открытии журнала помощника не отображаются запросы,а на панель уведомлений пишет,что для этого приложения нет запросов!

**Comment by zzebrum** [comment]
@Spok1 is https filtering enabled for opera app?

**Comment by Spok1** [comment]
Yes

**Comment by Spok1** [comment]
@zzebrum, yes.

**Comment by ameshkov** [comment]
HTTPS filtering не может работать в Opera если сертификат не перенесен в системные (а для этого нужен рут).

**Comment by ameshkov** [comment]
HTTPS filtering не может работать в Opera если сертификат не перенесен в системные (а для этого нужен рут).
