### ISSUE TITLE
Add Finnish filter

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#293]
Wiltteri filter - Finnish supplement list for EasyList
https://github.com/wiltteri/wiltteri.txt/blob/master/wiltteri.txt

Requester here - IOQ-379-56228

**Comment by ameshkov** [comment]
Will be done in the next beta version.

**Comment by ameshkov** [comment]
@mmigi please add this filter to the database.

**Comment by ameshkov** [comment]
Done, will be available in the next beta version.
