### ISSUE TITLE
Ошибка фильтрации!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#2936]
### System configuration

Information                            | Value
---                                          | ---
Platform:	|And 7.0.2
Device model:|Z500M
Root:|No
AdGuard version:	|v3.1.0 (1.3.347cl)
Browser:	|Opera
AdGuard mode:	|VPN
Filtering quality:	|High-quality
HTTPS filtering:	|enabled
DNS requests blocking:	|disabled
Filters:	|AdGuard Russian,</br>AdGuard Mobile Ads,</br>AdGuard Annoyances,</br>AdGuard Base,</br>AdGuard Tracking Protection,</br>AdGuard Social Media

**Comment by zzebrum** [comment]
@Spok1 please, elaborate the issue.

**Comment by Spok1** [comment]
Не фильтруются страницы!

**Comment by Spok1** [comment]
@zzebrum, не фильтруются страницы!

**Comment by ameshkov** [comment]
Скорее всего дело в том, что в Opera -- невозможна HTTPS фильтрация, поэтому возможности несколько ограничены.

Попробуйте включить в настройках AdGuard фильтр "AdGuard Simplified domain names filter", он как раз на такие случаи расчитан.

**Comment by Spok1** [comment]
@zzebrum, ограничения с ним связанные есть??
