### ISSUE TITLE
A wrong link to Tracking Protection filter on KB.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2937]
Need to fix it to the current link.
Outmoded:
https://kb.adguard.com/en/general/adguard-ad-filters#spyware-filter

Current:
https://kb.adguard.com/en/general/adguard-ad-filters#privacy

**Comment by admitrevskiy** [comment]
Done.

Correct link should be added on the next filters update or clean nightly application reinstallation
