### ISSUE TITLE
Non-HTTP data to port=80 should be bypassed, not just dropped

### ISSUE THREAD

**Issue by PaulMarkey1** [AdguardTeam/AdguardForAndroid#294]
Original issue: messages cannot be sent in Telegram app.

**Comment by ameshkov** [comment]
Seems that the problem was resolved on Telegram side.

**Comment by ameshkov** [comment]
Not so fast:)

**Comment by ameshkov** [comment]
Temporary workaround: disable ad filtering for Telegram in Adguard's firewall.

**Comment by TPS** [comment]
Now that #21 is landing, maybe expand this to include non-http ***&*** non-http***S***?

**Comment by ameshkov** [comment]
That's a good question.

Btw the original issue should be now fixed (along with #21).
But "non-HTTP over TLS" is still possible, yet I'd better wait for a real example before fixing it:)

**Comment by ameshkov** [comment]
Haha, here is a real example:
https://github.com/AdguardTeam/AdguardForAndroid/issues/322

**Comment by Bohdan-SUP** [comment]
Logs here - KOB-718-28059

**Comment by ameshkov** [comment]
@Bohdan-SUP which logs exactly? Telegram compatibility?

> Temporary workaround: disable ad filtering for Telegram in Adguard's firewall.

**Comment by ameshkov** [comment]
Fixed
