### ISSUE TITLE
Incorrect translation with "Protection is enabled" in other languages

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2942]
Strings are wrong.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/37797229/61576449-eacac980-aae2-11e9-97d2-e45026f12e07.png)

![image](https://user-images.githubusercontent.com/37797229/61576455-f3230480-aae2-11e9-8008-81d53d389c61.png)

</details>

### Your environment

* Adguard version: 3.2.100n
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual))
* Device model: (e.g. Google Pixel)
* Operating system and version: (e.g. Android 7.1.2)
* Root access:  (e.g. Yes / No)
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:

**Comment by lancelot-moon** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2939#issuecomment-513449919
Check if the space is deleted when AG team took the translations from onesky.
Let translators decide to keep the space or not.
For some Asian languages (ex: Chinese, Japanese, Korean...etc.), we don't need a space there in our translations.
