### ISSUE TITLE
http get from google.com returns 404

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2943]
I have created a macro in an app called macrodroid which runs a http get from google.com and
it returns the following sometimes (404 Not Found, instead of 200 that it returns normally):

[result.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/3414469/result.txt)

it should be related to adguard script injection, can you check?

**Comment by artemiv4nov** [comment]
@patrickdrd send debug logs to devteam@adguard.com, please

**Comment by ameshkov** [comment]
Actually, most likely it has nothing to do with AdGuard.

404 error is returned by the server, not by AdGuard. However, AdGuard adds the content script injection to every HTTP response regardless of it's status. Surprisingly, sometimes people insert ads into error pages, that's why we do this.

**Comment by ameshkov** [comment]
I'll reopen this just in case. If you want to dig this further, we could take a look at the [log file](https://kb.adguard.com/en/android/solving-problems/log#debug).
