### ISSUE TITLE
New Local VPN connection shows wrong app name

### ISSUE THREAD

**Issue by yashjahit-21705201** [AdguardTeam/AdguardForAndroid#2946]
### Steps to reproduce

1. Install AdGuard
2. Enable protection for the first time
3. Dialog should appear asking for permission to create a new VPN Connection

### Expected behavior

New connection dialog should show the app name
### Actual behavior

When enabling protection for the first time, new VPN connection dialog doesn't show app name at the beginning

<details><summary>Screenshot:</summary>

![Screenshot_20190723-115054](https://user-images.githubusercontent.com/34451870/61706825-fb787b00-ad40-11e9-8198-d95d6aabcbed.jpg)

</details>

### Customer ID 

2268489
### Your environment

* Adguard version: 3.2.98 beta (1.4.79 cl)
* Adguard filtering mode: Local VPN
* Device model: P00A
* Operating system and version: Android 7.0
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:  No

**Comment by zzebrum** [comment]
@yashjahit-21705201 that is the system dialog, not our. Probably it's device's firmware problem.

**Comment by ameshkov** [comment]
Yeah, this is 100% a firmware isssue
