### ISSUE TITLE
ru.letu - app is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2948]
@adguard-bot commented on [Tue Jul 23 2019](https://github.com/AdguardTeam/AdguardFilters/issues/37312)

Alternative download link: https://apkpure.com/%D0%BB%E2%80%99%D1%8D%D1%82%D1%83%D0%B0%D0%BB%D1%8C/ru.letu

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=ru.letu](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.letu)
### Comment
> В фильтрацией приложение работает крайне медленно. Иногда выходят сообщения вида "попробуйте ещё раз через 15 минут"

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/2lVo5u3.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/DDlO6eI.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | v3.1.0 (1.3.347cl)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by admitrevskiy** [comment]
Looks like with the latest versions of AG and `ru.letu` everything works fine.
@Alex-302 could you re-check it, please?

**Comment by Alex-302** [comment]
Still reproduced.

**Comment by Alex-302** [comment]
It seems it works now.
