### ISSUE TITLE
Fix bug while showing notification

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#2950]
Sentry link: https://sentry.adguard.com/adg/adguard-android-rs/issues/7120/events/1063043/

**Comment by admitrevskiy** [comment]
@artemiv4nov we need to find a way to pass resource ID to CL

**Comment by BlazDT** [comment]
Maybe related: When disabling notifications and then reenabling notifications the protection status is not shown as notification unless protection is restarted.
