### ISSUE TITLE
Status bar no longer colored if you have a display cutout

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#2952]
### Steps to reproduce
1. Have a display cutout device, like the Pixel 3 XL.

### Expected behavior
Status bar is still colored.

### Actual behavior
Status bar is black, appearing as though AdGuard is artificially constraining itself into a smaller space than it needs to.

<details><summary>Screenshot comparisons:</summary>

![Screenshot_20190723-235339](https://user-images.githubusercontent.com/29067983/61766182-90ad5b00-ada5-11e9-8c43-2d619ccdef7b.png)

![Screenshot_20190723-235507](https://user-images.githubusercontent.com/29067983/61766187-96a33c00-ada5-11e9-8f06-d21926fa887d.png)

</details>

### Customer ID 
1403048

### Your environment

* Adguard version: 3.2.98β
* Adguard filtering mode: Local VPN
* Device model: Pixel 3 XL
* Operating system and version: Android 9
* Root access: No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: No

**Comment by ameshkov** [comment]
> Status bar is black, appearing as though AdGuard is artificially constraining itself into a smaller space than it needs to.

Well, this actually might be true since we added the cutouts support, and that's how Android implements it.

@artemiv4nov could you please check if this is our only feasible option?

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG on device with display cutout (or enable `cutout mode` in developer options) and android 9+ aboard
-Open AG

Expected result:
-Cutout area should be colored
