### ISSUE TITLE
voip.voipunify.com - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2953]
@adguard-bot commented on [Sat Jun 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35947)

### Issue URL (Incorrect Blocking)
[http://voip.voipunify.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fvoip.voipunify.com)
### Comment
> When adguard is enabled, my SIP client can't register on the sip server.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/0ILRhSU.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/C2KGPgr.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.1.0 (1.3.347cl)
Browser: | Sipnetic
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Malware Domains,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Spanish/Portuguese

**Comment by ameshkov** [comment]
As of usual, VOIP apps should not be routed through AdGuard if you want them to work:(

**Comment by Revertron** [comment]
I think, that you mean [Sipnetic](https://play.google.com/store/apps/details?id=com.sipnetic.app) app. Added it to exclusions.
