### ISSUE TITLE
Add ABP Persian/farsi list

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#296]
for instance http://ideone.com/K452p

QDE-400-90009

**Comment by ameshkov** [comment]
@mmigi please add this filter to the database.

Homepage: http://ideone.com/K452p
Plain text: http://ideone.com/plain/K452p

! Title: Adblock-Persian list
Description: the same as title

**Comment by ameshkov** [comment]
Done, will be available in the next beta version.
