### ISSUE TITLE
com.nhn.android.nmap - app is broken on Android 5.1.1

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2960]
@adguard-bot commented on [Sat Jun 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/34926)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.nhn.android.nmap&hl=en](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.nhn.android.nmap%26hl%3Den)
### Comment
Username: @mickeyseo
> Naver Maps works properly when Adguard is disabled. Here is a captured video.
> https://drive.google.com/file/d/13sMFNk-TTzyLeE3ScMnXob9gepXtJVo6/view?usp=sharing
> 
> Naver Maps doesn't work properly when Adguard is enabled. Here is a captured video.
> https://drive.google.com/file/d/1TweYIHyfdhJgxmQqkuzDvEnAfmSBWq-_/view?usp=sharing
> The notification says "Try again after checking the network connection status."

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/N6wQ7hE.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/qrLyHnT.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 5.1.1
AdGuard version: | 3.1.0
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180 mins)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | disabled
DNS requests blocking: | enabled
Filters: | AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>List-KR
Other extensions used: | V3 Mobile Plus 2.0

**Comment by Alex-302** [comment]
Only disabling a filtering helps.

**Comment by ameshkov** [comment]
Does it help to disable HTTPS filtering?

**Comment by Alex-302** [comment]
No

**Comment by ameshkov** [comment]
@Alex-302 well, this is a problem then. Does only disabling ad blocking help? I'd like to avoid unblocking stuff:)

Could it be that the problem is in some of the stealth mode rules?

@mickeyseo could you please try the latest nightly build of AdGuard and see if it helps?

**Comment by Alex-302** [comment]
It seems it works now.
@mickeyseo please check again.

**Comment by artemiv4nov** [comment]
Can't reproduce anymore.
The task is closed and can be reopened on demand.

**Comment by Alex-302** [comment]
@mickeyseo says that an issue still exists.

**Comment by mickeyseo** [comment]
As of November 26th, 2019
1. Adguard v3.2.150 enabled, Naver Maps doesn't properly work as previously.
2. Adguard v3.3 nightly 24 enabled, Naver Maps doesn't properly work as previously.

**Comment by artemiv4nov** [comment]
This task will be completed after [Corelibs task](https://app.zenhub.com/workspace/o/adguardteam/corelibs/issues/1062) done.

**Comment by admitrevskiy** [comment]
@mickeyseo Hi!
It looks like the latest version of Naver is totally broken even without AdGuard. Did you notice any difference after updating Naver/AdGuard?

**Comment by mickeyseo** [comment]
Thank you for your continuous support.
I cannot open the Naver Maps app regardless of using the Adguard app. It is not open whether the Adguard feature is on or not. Please check the screenshot below.

https://drive.google.com/file/d/1VdQU-cLiPYF5dJH2-VZbP36jMRu98_gi/view?usp=sharing

Naver Map information
1. App version : 5.8.2 (the latest version as of May 21st, 2020)

My device information
1. Device name : Galaxy J5
2. Model Number : SM-J500N0
3. Android version : 5.1.1

**Comment by artemiv4nov** [comment]
So, I closed the task, please, re-open it if you will feel uncomfortable with this application during the AdGuard is working
