### ISSUE TITLE
Add new rules at the top of user filter?

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#2962]
Hi,
when you add a rule to DNS User Filter (by blocking a log entry or simply adding a new rule to user filter), this new rule could be added at the top instead of the bottom, just for user convenience (e.g. if there are many rules).
This behavior could be applied to regular Content Blocking User Filter too, and for other AdGuard products as well.

As an alternative, there could be an option to choose to add the rule at the end or at the top in the dialog window, or in AG settings (e.g., "add new rules at the top").

### Steps to reproduce (for example)

1. open AdGuard -> Settings -> Content Blocking -> User Filter
2. tap on +
3. add a rule

### Expected behavior
The rule could be added at the top of the list

### Actual behavior
The rule is added at the end of the list

### Your environment

* Adguard version: 3.2.98 Beta

**Comment by ameshkov** [comment]
Assigned to 3.4 and marked for discussion. Please comment if you have an opinion on this topic.

**Comment by superlex** [comment]
Hi, with new AG versions rules are added at the end of the list.
Is it an expected behavior or a regression?
