### ISSUE TITLE
A unnecessary space in "Protection is enabled/disabled" for some Asian languages.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2963]
**On Onesky**:
#2362172 = "Protection is"

You did the change in v3.2.110η.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2939

In old versions,
#2362173 = " enabled".
(There is a space in the front of enabled.)

In v3.2.110η,
#2362173 = "enabled".
(No space.)

In old versions,
#2362174 = " disabled".
(There is a space in the front of disabled.)

In v3.2.110η,
#2362174 = "disabled".
(No space.)

But I already reminded that the space in "Protection is enabled/disabled" is unnecessary for some Asian languages.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2939#issuecomment-513448756

In v3.2.110η, it's like so.
Please delete the space for Chinese (zh-TW & zh-CN), Japanese and Korean...etc.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/obJNDSu.png)
</details><br/>

**Please don't add a space in your program codes.
Let translators decide to keep the space in their translations or not.
It doesn't need a space there for some Asian languages, ex: Chinese, Japanese, Korean...etc.**
This is the correct screenshot in old version.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hV3ogBr.png)
</details><br/>

Otherwise, will you merge #2362172, #2362173 and #2362174 to 2 new phrases?
This is maybe easier.
`Protection is enabled`
`Protection is disabled`

**Comment by lancelot-moon** [comment]
**On Crowdin**:
#3866192 = "Protection is"
#3866194 = "enabled"
#3866196 = "disabled"

Will you merge #3866192, #3866194 and #3866196 to 2 new phrases **on Crowdin**?
`Protection is enabled`
`Protection is disabled`

You can't know if a gap is necessary between "Protection is" and "enabled/disabled" for all languages in the world.
Let translators make the translations in full sentences, which is maybe easier.

**Comment by Revertron** [comment]
Yes, probably. But later.

**Comment by lancelot-moon** [comment]
v3.2.135 is released.
However, this issue isn't fixed.
Please open it.

**Comment by ameshkov** [comment]
The proper fix would require changing "status" phrases in all languages.

**Comment by lancelot-moon** [comment]
It seems that v3.2.137 is the hotfix.

I supposed you'll merge #3866192, #3866194 and #3866196.
But this is fixed in v3.2.137 without merging them.
You decide it.
Thanks.

**Comment by lancelot-moon** [comment]
This was fixed in the recent nightly versions.
You can close.
Thanks.
