### ISSUE TITLE
Missed translation #3866856 (Crowdin) in DNS filter.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2964]
#3866856 on Crowdin:
English: AdGuard Simplified domain names filter
zh-TW: AdGuard 簡化的域名過濾器

AdGuard Simplified domain names filter is a default filter.
Hope it can show its translation there.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/xO3uS4S.png)

![image](https://i.imgur.com/bzR6Tbg.png)
</details><br/>

**Comment by ameshkov** [comment]
Well, this is a valid problem. DNS filter lists don't have metadata (unlike their content blocking counterparts). Assigned to v3.3, we'll think about it.

**Comment by ameshkov** [comment]
Too many tasks on 3.3, moved to 3.4

**Comment by lancelot-moon** [comment]
This is realized in v3.2.140 Release.
But there is a small bug.

When updating from v3.1/older versions to v3.2.140 Release or first installing v3.2.140 Release, AG SDN filter will show its translation.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8jF9GHZ.png)
</details><br/>

However, AG SDN filter will still show English if updating from v3.2 nightly versions to v3.2.140 Release or importing the settings file of v3.2 nightly version.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/FxEqBof.png)
</details><br/>

**Comment by lancelot-moon** [comment]
I don't know if the bug is related to this.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2971

After cleanly installing v3.2.140, if changing AdGuard's language from Chinese to English, AG SDN filter still shows Chinese.

**Comment by admitrevskiy** [comment]
Yep, this issue is already fixed.
