### ISSUE TITLE
Please add a space in the back of Extra in its zh-TW translation.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2965]
https://github.com/AdguardTeam/AdguardForWindows/issues/2761#issuecomment-514610800

AdGuard Extra script is updated for several times.
But you didn't modify the description in the source file.
This isn't fixed until now.
https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

In the zh-TW translation of AdGuard Extra's description, please add a space in the back of Extra for better looking.
當一般的廣告封鎖規則不夠時，AdGuard Extra可解決複雜的情況。
-> 當一般的廣告封鎖規則不夠時，AdGuard Extra 可解決複雜的情況。

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/1kB0Fau.png)
</details><br/>

Thanks.

**Comment by lancelot-moon** [comment]
The description of AdGuard Extra had been uploaded to Crowdin.
I already fixed the translation by myself.
I'll check if the translation is changed in new AdGuard Extra.
Thanks.

**Comment by ameshkov** [comment]
Please reopen if the new translations do not arrive in the next AG Extra update
