### ISSUE TITLE
Update AppsManagementPackageActivity UI on Premium status changed

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/AdguardForAndroid#2968]
Steps to reproduce:

-Reset license
-Go to AppsManagementPackageActivity for any non-browser package
-Tap on `Ad blocking`
-Enter key and activate Premium
-Go back

Expected result:
-Premium features are available

Actual result:
-Premium features are not available

**Comment by artemiv4nov** [comment]
This screen has been removed from application
