### ISSUE TITLE
Https Exclusion Ooni Probe

### ISSUE THREAD

**Issue by et6at** [AdguardTeam/AdguardForAndroid#2969]
Application Ooni Probe is used globally to measure providers surveillance and censorship of own network, AdGuard should add it to https exclusion because the app won't work without an exclusion set.

https://play.google.com/store/apps/details?id=org.openobservatory.ooniprobe

**Extra note:** Ooni Probe could detect AdGuard Home as a surveillance device, "middlebox test" that is expected and is of course a false-positive.

**Comment by TheHasagi** [comment]
@et6at 

Hello, HTTPS filtering for this application is disabled by default. The application works fine with AdGuard protection. Can you provide more details such as screenshot and version of AdGuard you are facing the issue?

**Comment by et6at** [comment]
As previous reply, we are considering the case a user is relying on a specific way of using AdGuard, AdGuard.crt installed into system, will filter all apps by default, unless a specific exception is made by AdGuard rulesets or by user manual intervention.
