### ISSUE TITLE
Application is being killed by Android

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#297]
Report all similar issues here in comments.

Before reporting the issue, please check the following:
1. Check that notification is **not disabled** for our app. This is very important as notification absence lowers the app priority.
2. Check if user has any "cleaner" apps. If so, advice him to add AG to exceptions in that app.
3. If the icon is not disabled and there's no cleaner app, we need "logcat" logs to troubleshoot the issue.

Instruction on how to collect "logcat" logs:
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/62/0/how-to-get-logcat-log-from-android-device

**Comment by ameshkov** [comment]
> The application disconnects several times a day.
> Logcat logs along with other information are available here:
> OXS-911-84845

@vbagirov, according to logcat log, the app has BG priority:
```
01-17 21:36:23.892   893   893 I ActivityManager: Killing 3451:com.adguard.android/u0a590 (adj 15): BG, 21808K, hotnessAdj=5, XmlFlag=false, oom_adj=15
```
This means that notification icon is disabled. Advise user to set it to "notification without icon" instead.

**Comment by vbagirov** [comment]
No reply from user so far, I will close the issue and re-open it in case it is not solved.
