### ISSUE TITLE
Add ch.threema.app to the default https exclusions list

### ISSUE THREAD

**Issue by et6at** [AdguardTeam/AdguardForAndroid#2970]
Since the application Threema is not pushing ads to their users, I think Https filtering could be disabled for it; moreover, in the latest version, is pushing a message about certificate pinning detecting the AdGuard filtering.

To the team to evaluate if adding it or not to Https Exclusion, even if I think could be whitelisted so far.

https://play.google.com/store/apps/details?id=ch.threema.app

**Comment by TheHasagi** [comment]
The same here, HTTPS filtering for this application is turned off by default. Can not get any problems with using with AdGuard. Please, provide more information such as screenshots with the error displayed, logs can be sent to devteam@adguard.com.

**Comment by et6at** [comment]
HTTPS filtering is on for every application when you use the stable build of AdGuard, unless a specific exception is specified by either the own AdGuard rulesets or by user manual opt-out from the filtering, when I am referring to HTTPS filtering, what I mean is that the user import the AdGuard certificate into system and not as user.

**Comment by et6at** [comment]
If you want reproduce the same bugs, or rather, "security features" I reproduced indipendently, you will need to move the certificate to system.

Regards, 

In the past, about 5-6 months ago, we used to reports similar events to be added to the default exclusion list.

**Comment by ameshkov** [comment]
> moreover, in the latest version, is pushing a message about certificate pinning detecting the AdGuard filtering.

Yup, this makes sense to add it to the exclusions list by default. Reopened and assigned to v3.3.

@TheHasagi 
> The same here, HTTPS filtering for this application is turned off by default

Are you testing on Android 7 or newer? You must know that this behavior is different on older Android versions or when the certificate is moved to the system store.

**Comment by admitrevskiy** [comment]
Done.
