### ISSUE TITLE
Incorrect filter locale displayed after language change

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2971]
Incorrect filter translation after language is changed (See the screenshot)

Preconditions are:

Switch device language for RU (example), AdGuard language is RU.

### Steps to reproduce

1. Switch language of AdGuard to EN
2. Open AdGuard - Settings - DNS filtering - DNS requests blocking

### Expected behavior

SDN filter should look with the selected locale (EN)

### Actual behavior

SDN filter shown in RU translation

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagir21s5.jpg)

</details>

**Comment by ameshkov** [comment]
Hmm, @admitrevskiy where does this translation come from? I thought there are no translations of the DNS filter lists?

**Comment by admitrevskiy** [comment]
We store SDN filter name in `strings.xml`. Looks like on the first SDN filter initialization selected locale was `ru`. Anyway, I think we should hide this phrase and make it not translatable.

**Comment by ameshkov** [comment]
Well, in the case of custom DNS filter lists, the user enters their names manually so there's no need to bother.

This one is preinstalled so ideally, it should be "translatable". It's just we'd better do it in runtime.

**Comment by lancelot-moon** [comment]
Yes, AdGuard SDN filter in DNS filter should be translated.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2964
Thanks.

**Comment by lancelot-moon** [comment]
My Android system language is Chinese.

After cleanly installing v3.2.140, if changing AdGuard's language from system (Chinese) to English, AG SDN filter still shows Chinese.

**Comment by TheHasagi** [comment]
@lancelot-moon 

As you can see the milestone is set to 3.3 and it cannot be fixed in 3.2.140. Please, stand by.

**Comment by lancelot-moon** [comment]
@TheHasagi 
Then you should not mark that you had fixed this in the changelog.
https://adguard.com/zh_tw/versions/android/release.html
[Fixed] "DNS filters" screen uses incorrect locale after language change #2971

**Comment by TheHasagi** [comment]
Fair enough :)

**Comment by admitrevskiy** [comment]
Done.
