### ISSUE TITLE
DNS User filter isn't clear after the import

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2972]
DNS User filter isn't clear after the import a JSON file with the settings where DNS User filter is empty.

Preconditions:

Some example rule like google.com 0.0.0.0 should be added to the DNS User filter and JSON file (example.json) with default settings must be prepared.

### Steps to reproduce

1. Enable AdGuard, check that example rule (google.com 0.0.0.0) is added ot the DNS User filter
2. Go to Settings - Import settings - example.json

### Expected behavior

DNS User filter should be empty

### Actual behavior

DNS User filter contains obsolete rule (before importing)

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagitdvc7.jpg)

</details>

### Your environment

* Adguard version: 
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual))
* Device model: (e.g. Google Pixel)
* Operating system and version: (e.g. Android 7.1.2)
* Root access:  (e.g. Yes / No)
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:

**Comment by ameshkov** [comment]
Great catch!

**Comment by admitrevskiy** [comment]
Resolved in 3.3
