### ISSUE TITLE
Notification did not disappear after enabling filters

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2973]
Notification about "No filters enabled. Enable some." did not disappear after some manipulations (see the steps and attachments).

### Steps to reproduce

1. Open AdGuard and disable all filters section
2. Open recent tasks menu and swipe out the adguard (hard exit)
3. Run AdGuard again and see the correct notification that explains the result of step 1 on the main screen
4. Do not tap on notification, go to Settings - Content blocking - Filters - enable all of them
5. Get back to the main screen

### Expected behavior

Everything should be in order. Notification should disappear after you turn on all filters

### Actual behavior

Notification did not disappear

<details>

![img](https://uploads.adguard.com/TheHasagi8clxy.jpg)

</details>

### Your environment

* Adguard version: 3.2.118n
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual))
* Device model: (e.g. Google Pixel)
* Operating system and version: (e.g. Android 7.1.2)
* Root access:  (e.g. Yes / No)
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:

**Comment by admitrevskiy** [comment]
Done
