### ISSUE TITLE
dns filter (custom) doesn't work in http proxy mode (root)

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2975]
on vpn it works fine,

please fix

**Comment by TheHasagi** [comment]
@patrickdrd 

Hello!

You are using IPv6 only?

**Comment by patrickdrd** [comment]
I'm using ipv4,
what kind of details?
all I know is I've got no dns blocking at all

**Comment by TheHasagi** [comment]
@patrickdrd 

Can you gather and send the log files according to this [KB article](https://kb.adguard.com/en/windows/solving-problems/adguard-logs) to devteam@adguard.com?

Can you remember when this problem has started? From what version exactly?

**Comment by patrickdrd** [comment]
it's working on .119 nightly,
but it needs monitoring,
because it has broken once more before,
the problem was on .118 nighty, maybe one before that too

**Comment by ameshkov** [comment]
Duplicate of #2977

**Comment by TheHasagi** [comment]
@patrickdrd 

The common question - Do you use private DNS? :)

**Comment by patrickdrd** [comment]
nope. just simple, regular cloudflare dns

**Comment by patrickdrd** [comment]
this still happens for me in .140, 
dns filtering is broken after filters update

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2977
