### ISSUE TITLE
Please add "Changelog" link to "About".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2976]
Please add "Changelog" in "About".
While tapping it, it'll lead to the corresponding page according to release, beta or nightly version.
https://adguard.com/zh_tw/versions/android/release.html
https://adguard.com/zh_tw/versions/android/beta.html
https://adguard.com/zh_tw/versions/android/nightly.html
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/k1vdpu7.png)
</details><br/>

This is a feature request.
In old versions, you know that users can only read changelog while new version is available.
My suggestion can let users read the current version's changelog any time.
Is it possible to let users reach changelog in "About"?
Thanks.

**Comment by ameshkov** [comment]
Well, we could open `adguard.com/versions.html` when the user taps on this item. This might be a little bit annoying, though.

@AlikhanAliev what do you think?

**Comment by lancelot-moon** [comment]
Sorry that I changed my idea.
Don't need to do changes in the update screen.
Please add "Changelog" in "About".
While tapping it, it'll lead to the page according to release, beta or nightly version.
Thanks.

**Comment by lancelot-moon** [comment]
It seems that mine is a duplication.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2774
