### ISSUE TITLE
Https proxy

### ISSUE THREAD

**Issue by whynotnow2** [AdguardTeam/AdguardForAndroid#2984]
Hi, 

Could you please add in proxy settings HTTPS PROXY support. 
 Today there are only HTTP and SOCKS4 and SOCKS5. We also needs HTTPS. 

Many Thanks 
Kind regards

**Comment by ameshkov** [comment]
What exactly do you mean by HTTPS?

Is it just a proxy that accepts HTTP CONNECT tunnel requests only?
Or is it an `HTTP proxy over TLS` kind of proxy?

**Comment by whynotnow2** [comment]
I mean SSL/TLS proxy.

Thanks

**Comment by ameshkov** [comment]
Thank you!

Moved to https://github.com/AdguardTeam/AdguardForAndroid/issues/2984

**Comment by whynotnow2** [comment]
Could you please tell me why did you close the request ?

**Comment by ameshkov** [comment]
Ops, sorry, it was moved to https://github.com/AdguardTeam/CoreLibs/issues/1071

**Comment by whynotnow2** [comment]
Thank you so much.
Hope it will Added soon

Kind regards
