### ISSUE TITLE
firewall when screen off blocks internet completely

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2986]
I have disabled both mobile data and WiFi access for instagram app when screen is off only, but when I open the app, I'm getting errors "couldn't refresh feed",
if I disable firewall for this app, everything works fine, so "screen off" detection isn't working properly maybe?

edit: it seems that it could be another http proxy issue, I switched to dns mode today and it worked

**Comment by ameshkov** [comment]
We need to have clear steps to reproduce this issue. So far, I couldn't do it.

**Comment by patrickdrd** [comment]
it was due to https filtering (certificate in system store, root),
I disabled it for instagram app and it works
