### ISSUE TITLE
Add a "Refresh license status" button to the action bar menu

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2988]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Problem Description

In AdGuard 3.x, you can't check for the license status changes anymore. The Upgrade or renew feature forwards you to the website where you can upgrade the key

### Proposed Solution

Allow users to check for the license status updates. The only way to do that now is to reset the key and reactivate it which is very inconvenient

**Comment by admitrevskiy** [comment]
Done.
