### ISSUE TITLE
Blocking Youtube ads by "sharing" video to our app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2994]
### Problem Description

There is no normal solution to adblocking on Youtube besides watching it in the browser (or rooting your device). Well, and besides purchasing YT Premium, but it's not available in a lot of countries.

### Proposed Solution

Allow watching Youtube videos right inside AdGuard (without ads, obviously).

1. Add a sharing provider for YT videos URLs. Let's call it "Watch without ads".
2. The video is opened in AdGuard (just like you could open it in Telegram or NewPipe).
3. The player should support:
    * Standard video controls
    * Tap to pause/play
    * Double-tap to seek
    * Slide up/down to control the volume
    * Setting menu with the following options:
        * Change orientation (portrait/album)
        * Changing quality
        * Picture-in-picture mode
        * Enable/disable captions
        * Share option (with timecode)
4. Add an additional screen to the app's onboarding explaining how to use this feature
5. Add "Youtube settings" under the "Content Blocking" settings with the following options there:
    * ON/OFF the sharing provider
    * The same explanation the as on the onboarding screen

Please note, that we cannot and do not want to replace the YT app. There are some awesome solutions for that already (see [NewPipe](https://github.com/TeamNewPipe/NewPipe)).

### Alternatives Considered

1. We cannot and do not want to replace the YT app. There are some awesome solutions for that already (see [NewPipe](https://github.com/TeamNewPipe/NewPipe)).
2. Automatic ad-skipping. Ridiculously hard to maintain. All the examples I've seen are quite unstable.
3. Virtualization (see #2889). Feasible, but much harder to implement, and worthy of a separate product.

**Comment by lancelot-moon** [comment]
For the 2nd point in Alternatives Considered:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2427

This is valid. It also has a free version.
https://play.google.com/store/apps/details?id=com.agooday.skipadspro

But I don't know if it's safe to use this.

Great ideas!
Just it looks like watching YouTube with a browser, right?
I remember the upper resolution of YouTube video by browsers is limited in 720p.
(YT app can use 1080p.)

**Comment by snhv** [comment]
How about just sending it to the browser?

**Comment by lancelot-moon** [comment]
May you give the options of playing speed if possible?
I mean 0.5x, 0.75x, normal, 1.25x and 1.5x speed.
Thanks.

**Comment by ameshkov** [comment]
> How about just sending it to the browser?

It won't provide picture-in-picture

**Comment by ministr91** [comment]
Это костыль. Перемотка 15 секунд, но куда подевались мои 10? Неизвестно в каком качестве видео запускается

**Comment by zero77** [comment]
Instead of developing and maintaining a video player would it not be easier to just recommend an existing one like, NewPipe.

**Comment by TPS** [comment]
I tried to determine what AG had done (blocked, modified, &c) with the YT link I shared, but didn't find any entries in the log.  Not implemented?

**Comment by Chinaski1** [comment]
Yes at this stage this info not implemented in the filtering log.

**Comment by TPS** [comment]
> Yes at this stage this info not implemented in the filtering log.

Planned?  ETA?

**Comment by Chinaski1** [comment]
Tentatively by version 4.0.

**Comment by artemiv4nov** [comment]
@TPS Hi! I guess the YouTube traffic can't be shown in the Filtering log because the AdGuard app makes requests to YouTube. The AdGuard traffic is not taken into account by ourselves.

**Comment by TPS** [comment]
That's a problem, isn't it?  How does 1 debug, &c?

**Comment by artemiv4nov** [comment]
No, that's not a problem

**Comment by ameshkov** [comment]
@TPS blocking YT ads in this case is not achieved via declarative rules, rather by using YT Iframe API with additional parameters to disable ads. Debugging it is only possible if you're an AdGuard dev, you need access to the code to change anything.
