### ISSUE TITLE
Get rid of Apache AvailablePortFinder

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#2995]
Binding to port 0 is more reliable in any cases. Also, current implementation keeps open socket at port 1100.

But support of binding to port 0 requires API methods to retrieve port to which server was bound.

Linked CoreLibs issue:
https://github.com/AdguardTeam/CoreLibs/issues/1028

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Examine possible protection restart cases for different filtering methods and configurations
