### ISSUE TITLE
Add an option to packet-block multiple apps

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2996]
As reported by user 2277949,

> "For a specific app I need to allow ads which means removing AdGuard protection from the app + Google Play Services + Google framework + Google backup transport.
> When I don't use this specific app I'd like to quickly block the above apps/services. At the moment I have to select all these 4 package names in the list of installed apps and manually switch the options."

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
