### ISSUE TITLE
Review network exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3]
I suspect that part of these apps are now working good.

**Comment by Revertron** [comment]
Testing build:
https://cloud.jamm.me/index.php/s/ohsoG0lDMYtq2p3
May have bugs and glitches, even set your device on fire and kill your dog.

**Comment by ameshkov** [comment]
@gshumihin don't forget to check that build.

@Revertron would be good if you post default exclusions list also

**Comment by ameshkov** [comment]
@gshumihin result?

**Comment by gshumihin** [comment]
testing atm

**Comment by Revertron** [comment]
New build: https://cloud.jamm.me/index.php/s/eef9rGex9ckDdFK

**Comment by gshumihin** [comment]
will test it tommorow

**Comment by Revertron** [comment]
These apps where thrown from exclusions:
com.google.android.talk
com.google.android.apps.docs
com.google.android.music
org.xbmc.kodi
net.wargaming.wot.blitz
com.bittorrent.sync
ru.bandicoot.dr.tariff
com.cbaplab.bogr
