### ISSUE TITLE
AT&T Duplicate messages / can't send SMS

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#30]
User can't send SMS/MMS with enabled Adguard. Also receives double SMS/MMS.

He uses Samsung Galaxy S6 / AT&T

https://www.dropbox.com/s/lcj73xxsn0k5ms6/Logs_%28JTY-872-67340%29.txt?dl=0 - logs (double messages)

Details here: JTY-872-67340

**Comment by TPS** [comment]
Is this same or different than #33?
