### ISSUE TITLE
Use custom adguard: scheme for adding userscripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3000]
@ameshkov commented on [Thu Jul 11 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2838)

1. Update CoreLibs to convert userscript links to use `adguard:` scheme
2. Intercept these links and offer to install a userscript
3. No more intercept `.user.js` on the network level

**Comment by ameshkov** [comment]
This is more or less the same as https://github.com/AdguardTeam/AdguardForAndroid/issues/2918 but for userscripts

**Comment by adbuker** [comment]
Please note, that the new proxy-server confuration's property have appeared - `clickedLinksInterception` . It is responsible for allowing to intercept request to subscription, userscripts (a list can be extended further). See more in `core/pull-requests/1576`

**Comment by admitrevskiy** [comment]
Done.
