### ISSUE TITLE
Does $script equal to "add to exception" in JavaScript of Chrome?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3002]
A question.
I want to disable JavaScript for a specific sub-domain.
Is $script for the purpose?
But scripts are still run on the website even if using such rule syntax example.com$script.
I'm confused.
Do I misunderstand the use of $script?
Can any rule syntax disable JavaScript for a specific sub-domain?

Thanks.

**Comment by ameshkov** [comment]
> Is $script for the purpose?

Not if you want to disable inline javascript.

You have two options:
1. `example.com$$script` -- removes all scripts
2. `||example.com^$csp=script-src 'none'` -- disables scripts using content security policy
