### ISSUE TITLE
[Bug] [Android TV] Overlayed hints can't be dismissed (new)

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#3003]
Because this was closed but it wasn't constantly fixed throughout the UI: 
[Bug] [Android TV] Overlayed hints can't be dismissed; #2979 

@TheHasagi: The problem referred to still shows up on certain screens with no possibility to dismiss (tested on v.3.2.1211B). 
For example in "content blocking", there's no way to neither dismiss nor access the settings on this page.

**Comment by artemiv4nov** [comment]
@oroboros done in latest nightly, can you check please?

**Comment by oroboros** [comment]
> @oroboros done in latest nightly, can you check please?

Confirmed. Works fine!
