### ISSUE TITLE
Add DNS exclusions

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3007]
### Problem Description

As of now, AdGuard does not allow the user to whitelist a specific app from DNS filtering.

### Proposed Solution

Either add "whitelist from DNS filtering" option to Settings > DNS, or add the same switch to Apps Management

### Alternatives Considered
null

### Additional Information
Reported by user 1973547

**Comment by ameshkov** [comment]
> As of now, AdGuard does not allow the user to whitelist a specific app from DNS filtering.

Unfortunately, it is not technically possible to disable just DNS filtering for an app. You can only disable filtering completely:(
