### ISSUE TITLE
Rename fields to better suit their purpose

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3011]
Currently, we see the following field names:

**Filters**: This is seen in Settings > Content Blocking

**Custom filters**: This is seen in Settings > Content Blocking > Filters

**User filter**: This is seen in Settings > Content Blocking

It would be better if the field "Filters" is renamed to "Filter Subscriptions" and the field "Custom filters" is renamed to "Custom Filter Subscriptions" as this is where we either provide the URL / path to the file with all the filter rules. 

Currently, both "Custom filters" and "User filter" have the same meaning and are just written differently.

Thanks

**Comment by lancelot-moon** [comment]
Why should "Filters" be renamed to "Filter Subscriptions"?
They're default filters which are already subscribed.

Custom filter and user filter are in different places.
Users also can't fill in rules in custom filter.
They should know the difference between custom filter and user filter.

**Comment by Nzzyme** [comment]
> Why should "Filters" be renamed to "Filter Subscriptions"?
> They're default filters which are already subscribed.
> 
Hence, change the field name to Field Subscriptions. Think of it like a heading.



> They should know the difference between custom filter and user filter.

For a regular user, it looks the same. We are therefore being more specific when naming fields.

**Comment by ameshkov** [comment]
Actually, this is an old problem, and the real question is the "filter" definition.

We were always using "filter" and "filter list/subscription" as synonyms, but nowadays some people tend to call individual filtering rules "filter". Personally, I'd better keep our traditional approach.

Anyways, "custom filters / user filter" misunderstanding is a legit problem.

What about this?
"User rules"
"Custom filters"

**Comment by lancelot-moon** [comment]
Yes, I ever suggested to rename "User filter" to "User rules" in the past.
Then you need to modify for all of your products.

"Custom filters" should be kept.

**Comment by Nzzyme** [comment]
> Actually, this is an old problem, and the real question is the "filter" definition.
> 
> We were always using "filter" and "filter list/subscription" as synonyms, but nowadays some people tend to call individual filtering rules "filter". Personally, I'd better keep our traditional approach.
> 
> Anyways, "custom filters / user filter" misunderstanding is a legit problem.
> 
> What about this?
> "User rules"
> "Custom filters"

Sounds good to me. Thank you

**Comment by ameshkov** [comment]
Well, I guess this needs to be done in every AG product in order to be consistent.

@zzebrum could you please take care of this and file issues to every AG repo where this is applicable? Close this issue after that.

**Comment by aalpatkina** [comment]
"User filter" was renamed to "User rules" in Crowdin
