### ISSUE TITLE
After adding a custom user filter rule from the Filtering Log (by clicking on the "Block" button), the button should immediately change from 'Block' to 'Unblock'.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3012]
After adding a custom user filter rule from the Filtering Log (by clicking on the "Block" button), the button should immediately change from 'Block' to 'Unblock'.

Steps:

1. Open Filtering Log and tap on a particular list item which is not blocked.
2. Tap on 'Block' and then select the desired options and tap on 'Add Rule'.
3. It takes us back to the 'Log Details' page and now we still see 'Block' instead of 'Unblock'.

Thanks!

_Originally posted by @Nzzyme in https://github.com/AdguardTeam/AdguardForAndroid/issues/2393#issuecomment-522895368_

**Comment by Nzzyme** [comment]
Hello,

I was trying to add a DNS entry from the Filtering Log to the block list and observed that AG allowed me to add the same entry twice thereby creating duplicate DNS User filters as seen in the screenshot.

https://i.ibb.co/m4kWJH6/Screenshot-20220709134314.jpg

I thought that once you add an entry, then the "Block" button should immediately change to "Unblock"?
