### ISSUE TITLE
Allow users to reset AdGuard contextual tips

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3017]
### Problem Description
As of now, users are unable to reset contextual tips introduced in patch 3.2. Some of the users had complained that they have either closed them automatically, without reading the description, or wanted to access them again, but had no way of doing it.

### Proposed Solution
Add a "Reset tips" setting to Settings > General.

### Alternatives Considered
None available.

### Additional Information
Originally reported by user 1554617

**Comment by artemiv4nov** [comment]
Hmm, it's interesting feature, let's see how many likes it gain

**Comment by artemiv4nov** [comment]
Well, we re-built the feature discovery functionality, the task is not actual anymore.
