### ISSUE TITLE
Open Chrome custom tabs in the same window

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3019]
### Issue Details
When opening a Chrome Custom Tab through AdGuard (e.g. when tapping on "Upgrade license" in AdGuard > License status), a custom tab containing AdGuard page is opened in a separate window.

- **AdGuard version:**
  - 3.2.135
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 3 XL
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Custom tab should be displayed in AdGuard main window.

### Actual Behavior

Custom tabs are displayed in separate window.

### Screenshots

Screen recording available in ticket 1403048.

**Comment by admitrevskiy** [comment]
Done.
