### ISSUE TITLE
Add com.project.materialmessaging to the pref.net.exclusions by default

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#302]
[This](https://play.google.com/store/apps/details?id=com.project.materialmessaging&hl=en).

The customer couldn't send MMS. Adding into exclusions makes it work fine. 

> "Thanks, that fixed it!
> 
> My mobile carrier is Cricket - an AT&T MVNO. Regarding other apps, Google
> Messenger does not work, even without Adguard.
> 
> There is a known issue with both Cricket's DNS entries and server
> configuration for their MMS proxy servers. DNS resolves to different
> addresses depending on whether the device is connected to WiFi or mobile
> data, and the servers at the addresses resolved via WiFi don't have the
> proper ports open. It appears that when connecting to the MMS proxy fails
> via WiFi, some messaging apps fail to re-resolve the proxy address after
> switching to mobile data, causing them to fail, while other apps do
> re-resolve the address, allowing them to succeed.
> 
> However, with a workaround implemented (that correctly resolves the proxy
> address over WiFi), Material Messaging still fails with Adguard enabled."

**Comment by ameshkov** [comment]
We should add this app to the default exclusions list.

**Comment by Revertron** [comment]
Done.
