### ISSUE TITLE
Incorrect status when the internet is not available

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#3020]
### Expected Behavior

When we can't connect to internet we should text about it in each cell and use right icons

### Actual Behavior

We show incorrect condition

### Screenshots

![Slice@1x](https://user-images.githubusercontent.com/30260021/63591448-7f7b8800-c5b7-11e9-8df1-5c3cc751b683.png)

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
- Reinstall AG
- Enable `Airplane mode`
- Go to `Updates` screen
