### ISSUE TITLE
Добавьте расширение для отключения Турбо-страниц при поиске в Яндексе

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#3021]
Пожалуйста, добавьте расширение для отключения [Турбо-страниц](https://yandex.ru/dev/turbo/) при поиске в Яндексе подобно тому, как у вас реализовано это в расширении «Отключить AMP».

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/DisableAMP #3](https://github.com/AdguardTeam/DisableAMP/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/DisableAMP #4](https://github.com/AdguardTeam/DisableAMP/issues/4) via [**ZenHub**](https://www.zenhub.com/)
