### ISSUE TITLE
"AdGuard Simplified domain names filter" contains explicit rule that allows "www.googleadservices.com"

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#3022]
### Issue Details

"AdGuard Simplified domain names filter" contains explicit rule that allows "www.googleadservices.com"
![ScreenshotCapture_2019_08_24_14_54_51_284](https://user-images.githubusercontent.com/17823400/63637075-a8b41b00-c680-11e9-9a04-dcb982d4ce74.png)

- **AdGuard version:**
  - v3.2.139n
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 2 XL)
- **Operating system and version:**
  - Android 9 with latest patches
- **Root access:**
  - No

### Expected Behavior

AdGuard filters should not explicitly allow advertising URLs

### Actual Behavior

Played with a new app
According to Filtering Log. it connected to "www.googleadservices.com", which was explicitly allowed by a rule

### Additional Information

Adding a manual explicit rule "||googleadservices.com" to the DNS filter did NOT help - the connection was still accepted by the "AdGuard Simplified domain names filter"

**Comment by ameshkov** [comment]
@SergeiShir this is not a bug.

The problem with blocking this domain is explained here: https://github.com/AdguardTeam/AdGuardHome/issues/64

> Adding a manual explicit rule "||googleadservices.com" to the DNS filter did NOT help - the connection was still accepted by the "AdGuard Simplified domain names filter"

`||googleadservices.com^$important`
