### ISSUE TITLE
Unable to reset settings in firewall section

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3027]
Steps to reproduce:

1. Open AdGuard - Apps Management - 3dots - Settings
2. Change any settings (switch on/switch off)
3. In Firewall settings - 3dots - Reset settings

Actual behaviour:

Settings won't get back to its default stage.

Expected behaviour:

Settings should rollback to previous stage (default)

<details>

![img](https://uploads.adguard.com/TheHasagiw4hn9.jpg)

</details>

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
