### ISSUE TITLE
Random user-agents

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3028]
Allow adding several user-agents and switch between them randomly, just like the [Random User-agent](https://chrome.google.com/webstore/detail/random-user-agent/einpaelgookohagofgnnkcfjbkkgepnp?hl=uk) extension does.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1096](https://github.com/AdguardTeam/CoreLibs/issues/1096) via [**ZenHub**](https://www.zenhub.com/)
