### ISSUE TITLE
Unable to connect to Internet through 4g LTE when Adguard is enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#303]
None of the websites open, nor apps work. Much like in #284 but for 4g only. With Wi-Fi everything is fine.

Should I ask user about "restricted background data" option?

INY-523-91317

**Comment by ameshkov** [comment]
Huh, you've made him wait for 20 days? That's not good at all.

**Comment by ameshkov** [comment]
I'd like to see the log with DNS requests.

Please ask user:
1. Enable "Filter DNS requests" in AG advanced settings
2. Record one more full log

**Comment by vbagirov** [comment]
Asked for the log with DNS requests enabled.
