### ISSUE TITLE
com.nvidia.shield.remote - app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3030]
@adguard-bot commented on [Thu Aug 01 2019](https://github.com/AdguardTeam/AdguardFilters/issues/37788)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.nvidia.shield.remote](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.nvidia.shield.remote)
### Comment
Username: @CoreyVidal
> NVIDIA SHIELD TV had an app for Android that allows you to control your SHIELD set-top box from your phone. Version 1.0 of this app has been working fine for a few months.
> Version 2.0 came out today. I noticed it would no longer "see" my SHIELD device in the app (my phone must be on the same network as the SHIELD to work). I thought maybe v2.0 of this app was the problem. I did extensive testing and happened to notice that completely disabling AdGuard made the NVIDIA SHIELD TV app "see" my SHIELD device instantly.
> I tried re-enabling AdGuard, and then going into settings to turn off AdGuard specifically for my NVIDIA SHIELD TV app. This did not work. It won't find/see my device. But as soon as I completely disable AdGuard, then the app works right away.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/PAsOteJ.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Pz0irbR.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.1.0 (1.3.347cl)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Filter unblocking search ads and self-promotion,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Spam404,<br>NoCoin Filter List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media
Other extensions used: | None

**Comment by Alex-302** [comment]
@CoreyVidal could you, please send debug logs to us?
https://kb.adguard.com/android/solving-problems/log#debug

**Comment by Chinaski1** [comment]
@CoreyVidal
To solve this problem we need log files, please send a log to k.gretskyi@adguard.com
> How to collect:
- AdGuard > Settings > Advanced > Logging Level > Record All.
- Reproduce your issue.
- Note the time the error occurred and let us know.
- Don’t forget to return to the default logging level.

**Comment by admitrevskiy** [comment]
Unfortunately, this issue is unreproducable without Nvidia Shield and there are no logs from user.
Re-open this issue if necessary.
