### ISSUE TITLE
com.facebook.lite - cannot detect that IPv6 is unreachable

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3031]
@adguard-bot commented on [Sun Aug 25 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39179)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.facebook.lite](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.facebook.lite)
### Comment
> Facebook Lite app no longer starts after latest Adguard update. I tried disabling Adguard settings one by one to identify the cause, without success. No other changes were made on my phone except Adguard updating to the last version. I had to add Facebook Lite to the exclusion list eventually, which works but is not the solution I want. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/1cWeAsa.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/7KMqezg.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | v3.2.140 (1.4.138cl)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>ROList,<br>AdGuard Annoyances,<br>AdGuard Base,<br>ROLIST2,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by Alex-302** [comment]
This app works only when AdGuard rptection is disabled in the app settings

**Comment by Alex-302** [comment]
Log:
[log (7).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3540883/log.7.zip)
with and without DNS blocking.

**Comment by ameshkov** [comment]
The current solution is to keep `pref.vpn.disable.reconfigure` disabled in the case when Facebook Lite is detected on the device.

**Comment by artemiv4nov** [comment]
Note:
This bug can be reproduced if you connect to IPv4 only network and turn on the low-level setting: `pref.vpn.disable.reconfigure`.
