### ISSUE TITLE
Add user/system app filter to Bulk Change in Apps Management

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3033]
The use case provided by user #2263530:

_I want to use a preference in Bulk Change that apply only for user applications and let system applications without filtering because that can cause issues later on with the system (I'm not an end-user)._

_The first thing you can configure in any firewall is the option to apply a filter only for a type of application (user or system). That's not an uncommon option in a firewall._

_Or add an option to sort by type of application in Apps Management to only show user apps or system apps._ 

_It's frustrating to have to scroll (in my case) a total of 294 applications (209 are system apps) to manage manually 84 user apps, I need to focus on all applications to distinguish user applications from system applications._

**Comment by ameshkov** [comment]
Makes perfect sense, thank you!

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
