### ISSUE TITLE
Fix "Preparing to start protection" notification

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3034]
When device's OS starts, application starts automatically and tries to start protection.
But if we did not allow the use of VPN, then the protection will not start, and the notification will stay.
We need fix this behavior.

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Clean install AG
-Do not pass `Quick Settings`
-Restart device (*)
-Expected result: no autostart, no notifications

-Pass onBoarding
-Do not start protection
-(*)
-Expected result: no autostart, notification `Please, configure application`
-Tap on notification lead to Main screen

-Select `Proxy` filtering mode
-(*)
-Expected result: AG starts on device boot

-Select `VPN` filtering mode
-Tap on start protection -> Ok -> Create local VPN
-Don't allow AG to set up VPN (System dialog with key icon)
-(*)
- Expected result: no autostart, `Allow AG to create VPN` notification
-Tap on notification should lead you to system dialog

-Allow AG to set up VPN connection
-(*)
-Expected result: AG starts on device boot
