### ISSUE TITLE
Move "Import / Export Settings" to a more visible area

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3037]
### Problem Description

Since the release of AdGuard 3.0, we've received multiple support tickets about the "disappearance" of the "import / export settings" feature. While the option is still there, it is located in a very inconvenient spot (Settings > top-right menu) and is quite hard to find.

### Proposed Solution

Move "Import / Export settings" to Settings > General.

### Alternatives Considered

To give these features even better visibility, add an option to import your own settings during initial first-launch configuration.

**Comment by chernikova-yana** [comment]
There are 2 alternative phrases for the screen. Both are approved, so we can choose one that we find the most applicable:

1) https://share.goabstract.com/899b5743-9b53-48f5-892f-02a49ce18b96?sha=a8ec1912fa7f03a570687c74ea1338fefba1dc2d

2) https://share.goabstract.com/84d01cb3-908c-4111-a78c-6b21890ff1df?sha=a8ec1912fa7f03a570687c74ea1338fefba1dc2d

**Comment by admitrevskiy** [comment]
Import / Export settings has been moved to `General`
