### ISSUE TITLE
Google Now not updated on "Always on VPN"

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3039]
### Issue Details

- **AdGuard version:** v3.2.150
- **Filtering mode:** Local VPN 
- **Device:** ASUS ZB602KL
- **Operating system and version:** 9
- **Root access:** No

### Expected Behavior
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/63937891-32daf580-ca6c-11e9-8ff4-423c5906149b.png)

</details>

### Actual Behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/63937872-26ef3380-ca6c-11e9-8432-ad2a6d43e45a.png)

</details>

### Additional Information

If in Android settings to enable the "Always-on-VPN" and "Block VPN connections" without. The Google news feed stops updating. Is this normal behavior?

**Comment by sfionov** [comment]
It's working as expected.
When "Block connections without VPN" is on, traffic from applications that are not filtered by AdGuard will not be redirected into AdGuard's local VPN, and thus systen will continue to block traffic from that applications (because they are "without VPN").

**Comment by Koruy** [comment]
Тогда почему приложение windscribe, которое так же работает с vpn, при включенной настройке: блокировать соединение без vpn работает и обновляется лента гугл?
Then why is the windscribe application, which also works with vpn, with the setting turned on: block a connection without vpn running and updating Google feed?

**Comment by Revertron** [comment]
@Koruy потому, что windscribe пропускает через себя _все_ соединения, а AdGuard - нет.

**Comment by Koruy** [comment]
Тогда как adguard блоуирует трафик через брандмауэр, если он не все соединения пропускает через себя?

**Comment by ameshkov** [comment]
@Koruy это все меняется в "настройках приложений", вам просто нужно для всех приложений включить фильтрацию там

**Comment by Koruy** [comment]
Вот именно, что фильтрация для гугл, сервисов гугл плей, почты гугл фильтрация для них включена и не могут гугл приложения получить доступ к интернету, обновить ленту и так далее, баг программы, разработчики упорно не признают.

**Comment by Koruy** [comment]
Вот именно, что фильтрация для гугл, сервисов гугл плей, почты гугл фильтрация для них включена и не могут гугл приложения получить доступ к интернету, обновить ленту и так далее, баг программы, разработчики упорно не признают.

**Comment by Koruy** [comment]
That's it, that filtering for google, google play services, google mail filtering is turned on for them and google apps can’t access the internet, update the feed and so on, the program’s bug, the developers stubbornly do not recognize.

**Comment by ameshkov** [comment]
@Koruy вы уверены что вообще для всех приложений включена фильтрация? Рекомендации эти могут грузиться каким-то отдельным системным приложением

**Comment by Koruy** [comment]
Вот сейчас проверил, включил фильтрацию (защиту) полностью для всех приложений, кроме самого adguard, результат тот же самый. Не обновляется лента гугл, и к тому же ещё и по ссылке в почте я не смог перейти на сайт github.

**Comment by ameshkov** [comment]
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Open AdGuard -> Settings -> Advanced -> Set "Logging level" to "Record everything". It's desirable to close all background apps that don't concern the problem beforehand.
2. Reproduce the issue and set the logging level back to "Default".
3. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
4. Open AdGuard -> Settings -> Advanced -> Export Logs
5. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
6. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Koruy** [comment]
Отправил, а в названии темы в письме указал ссылку на данную страницу в github

**Comment by Koruy** [comment]
Дело в том, что не удаётся обновить не только ленту гугл, так же не
работает почта gmail и ещё какие то приложения не работали, я на вскидку
так не скажу play market вроде бы.

вт, 10 сент. 2019 г., 23:27 Andrey Meshkov <notifications@github.com>:

**Comment by Koruy** [comment]
Бот пытается закрыть тему. Есть какие то подвижки в устранении деффекта?

**Comment by artemiv4nov** [comment]
@Koruy Не закроет, видим :) Решение в бету 3 войдёт.

**Comment by Koruy** [comment]
[adguard_logs_3.3.141_1511_195249.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3852485/adguard_logs_3.3.141_1511_195249.zip)
[bugreport-H4113-50.2.A.0.400-2019-11-15-19-53-20.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3852487/bugreport-H4113-50.2.A.0.400-2019-11-15-19-53-20.zip)
 И ещё проблема не возможно передать контент по dlna отчёты об ошибках и логи вверху сообщения время 19.52
![Screenshot_20191115-195220](https://user-images.githubusercontent.com/53151866/68961497-93640e00-07e3-11ea-9de6-42b814d82e9b.png)
Не возможно отправить сюда на сайт вложения при включенной постоянной vpn и блокировкой соединений без vpn. С гугловскими приложениями вроде бы исправили в nightly.

**Comment by artemiv4nov** [comment]
@Koruy ,
Пожалуйста, выполните следующие шаги:
1) Включите в AdGuard полное логирование: Settings -> Advanced -> "Logging level" -> "Record everything";
2) Вопроизведите проблему и запомните её точное время;
3)  Отправьте нам логи на devteam@adguard.com с указанием точного времени воспроизведения.

**Comment by Koruy** [comment]
Отправил логи время проблемы 21.20

**Comment by ameshkov** [comment]
@Koruy ну в целом логично получается.

Суть в том, что локальная сеть исключена из VPN по-умолчанию. В обычной ситуации это означает, что трафик в локалку мы не фильтруем.

Но в случае, когда вы включили "блокировку соединений без VPN", получается что и трафик в локалку полностью заблокирован.

Попробуйте почистить содержимое следующих низкоуровневых настроек:
`pref.ipv4.routes.excluded`
`pref.ipv6.routes.excluded`

**Comment by Koruy** [comment]
Я почистил записи в pref.ipv4.routes.excluded их там около 20 шт было, очистил все dlna заработал, может не стоило всёудалять, а какую то одну запись надо удалить?

**Comment by ameshkov** [comment]
> Я почистил записи в pref.ipv4.routes.excluded их там около 20 шт было, очистил все. DLNA заработал, может не стоило всё удалять, а какую то одну запись надо удалить?

Вот в случае этой функции включенной -- надо их все удалять.
Более того, надо для всех приложений фильтрацию включить, а то у тех где она выключена - доступа в сеть вообще не будет.

**Comment by Koruy** [comment]
Да, согласен, полностью для всех приложений должна быть включена фильтрация. Есть приложения банковские, личные данные никуда на сторону не уплывут?

**Comment by artemiv4nov** [comment]
Так как баг с Google Now был решён ещё в другой задаче, то эту закрываю, потому что все найденные проблемы решены.
