### ISSUE TITLE
[Feature request] Add "update" button or update by pulling down the window

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#304]
Здравствуйте, сделайте кнопку обновления отдельно на панели, или потянуть в низ. Кнопку проверки обновления вручную, отдельно на верхней панели (рядом со справкой FAQ), или тянуть вниз в как в мат. дизайне сейчас принято.

HLB-329-87682

**Comment by ameshkov** [comment]
Учтем во время редизайна
