### ISSUE TITLE
Do not filter new apps by default

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3041]
That could be an optional low-level feature that would prevent AdGuard for enabling filtering for apps you've just installed. Requested by 1400233:

> предлагаю внести коррективы, можно ли сделать так чтобы при установке нового приложения, Adguard автоматически не ставил это приложение под фильтрацию? а то приходится потом вручную ручками снимать галочку фильтрации с нового приложения. спасибо!

**Comment by vozersky** [comment]
we could actually start showing a notification for every new app installed, to tell user what do we know about the app and then let him decide about filtering

**Comment by drikah** [comment]
> Isso poderia ser um recurso opcional de baixo nível que impediria o AdGuard de habilitar a filtragem de aplicativos que você acabou de instalar. Solicitado por 1400233:
> 
> > предлагаю внести коррективы, можно ли сделать так чтобы при установке нового приложения, AdGuard автоматически не ставил это приложение под фильтрацию? а то приходится потом вручную ручками снимать галочку фильтрации с нового приложения. спасибо!

Gostei da idéia!

**Comment by sky96111** [comment]
I think a new blacklist mode could be introduced, where only apps within the list are filtered and the list needs to be added manually. Like in the PC version.
Because there is a lot of app that has problems when routed by adg. It costs time to find what is to blame.

**Comment by Versty** [comment]
@sky96111 @drikah 
Duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/4482, please put some 👍 emoji on the linked issue.
