### ISSUE TITLE
After connecting to BBS, Telnet connection will be disconnected later with Socks5 outbound proxy.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3042]
I use AG for Android v3.3 nightly 2 (5).

After successfully connecting to BBS, Telnet connection will be disconnected later with Socks5 outbound proxy.

I tested Telnet connection with Socks5 or HTTP outbound proxy.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vJWhO58.png)
</details><br/>

When I stayed on BBS via Telnet protocol, I could keep connection with **HTTP** outbound proxy, but Telnet connection would be disconnected later with **Socks5** outbound proxy.

I have sent the log file (record everything) to devteam@adguard.com on 1st September.

(My BBS client app would automatically try reconnecting while disconnection occurred.
So you should find Telnet connection repeatedly reconnected from my log file.)

The email title: Bug report (AG for Android)

**Comment by ameshkov** [comment]
What about not using a proxy at all?

**Comment by lancelot-moon** [comment]
> What about not using a proxy at all?

Did you maybe reply a wrong issue?

Here, I found a bug in Socks5 outbound proxy for Telnet connection.

**Comment by lancelot-moon** [comment]
Waiting for report?
I have sent the log file (record everything) to devteam@adguard.com on 1st September.

**Comment by ameshkov** [comment]
> Did you maybe reply a wrong issue?

I mean is there a difference when you are not using any proxy? 
Also, could you please try a different proxy, not nordvpn?

**Comment by lancelot-moon** [comment]
Without outbound proxy, AG had fixed the disconnection bug in the past.

You got it.
With Windscribe Socks5 proxy (port: 1080) in AG, Telnet connection won't be disconnected.

It seems that disconnection issue is with NordVPN Socks5 proxy.

**Comment by ameshkov** [comment]
Yeah, this is most likely the Nord's issue.
