### ISSUE TITLE
A feature request for split proxy.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3043]
Is it possible to set some apps through outbound proxy but others not through outbound proxy? Those apps still have AG protection (adblock) in this situation (VPN mode) whether their traffic pass through outbound proxy or not.

**Comment by lancelot-moon** [comment]
@ameshkov 
https://github.com/AdguardTeam/AdguardForAndroid/issues/3042#issuecomment-527086152

Do you mean this?

I wish some apps can use foreign ip but others can't use in VPN mode.
I also wish adblock in split proxy.

Ex:
A app (in the routed apps list) -> outbound proxy with adblock
B app -> not use outbound proxy but still with adblock

**Comment by ameshkov** [comment]
Duplicate, we already have such feature request here
