### ISSUE TITLE
Unchecked rules become checked after importing the content blocking user filter to the DNS user filter

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3046]
When exporting the regular user filter with certain rules disabled and importing it to the DNS User filter, all rules turn enabled. Some customers would like to have the status of the rules preserved. Reproduced with AdGuard 3.3 nightly 2.

<details> <summary> the content blocking user filter before exporting </summary>

![Screenshot_2019-09-03-13-53-27](https://user-images.githubusercontent.com/15856304/64168077-714d2780-ce53-11e9-8d6e-4cb2a6b570cd.png)

</details>

<details> <summary> the DNS user filter after importing </summary>

![Screenshot_2019-09-03-13-53-16](https://user-images.githubusercontent.com/15856304/64168212-b1140f00-ce53-11e9-93a7-756de383e706.png)

</details>

**Comment by TheHasagi** [comment]
Actually, it is not a but or issue. Logic is that those filters are storing only as a "text" and can not contain any states of enabled/disabled rules. It is working as you suppose only if you export whole settings from general - settings - 3dots - export settings.

**Comment by ameshkov** [comment]
This is by design
