### ISSUE TITLE
После нажатия "Quick Connect" для ProtonVPN - AdGuard не ставится на паузу, тем самым не позволяет ProtonVPN подключиться

### ISSUE THREAD

**Issue by pdkpv** [AdguardTeam/AdguardForAndroid#3048]
Предыстория: https://github.com/AdguardTeam/AdguardFilters/issues/39864

Устройство: Xiaomi Redmi 4X, MIUI 10 Global Beta, Android 7.1.2
Версия AdGuard: версия 3.3.5 от 31 августа 2019
Версия ProtonVPN: 2.0.3 (beta)

Сейчас отправлю логи через приложение, в письме добавлю линк на эту тему

**Comment by TheHasagi** [comment]
Проверил на релизной версии Proton VPN и с бета, проблема не повторяется. Скорее всего специфика прошивки MIUI. Нужны детальные логи.

**Comment by TheHasagi** [comment]
Повторяется, если запускать ProtonVPN из шторки.

**Comment by akmLaVx** [comment]
Logs from the OP are available in  ticket 2303082.

**Comment by pdkpv** [comment]
UP

**Comment by ameshkov** [comment]
@pdkpv assigned to v3.4

**Comment by pdkpv** [comment]
I see that the nightly version 3.4 started. Please fix this bug. I have already survived ~ 115 days of torment and expectation :)

**Comment by ameshkov** [comment]
@pdkpv да мы просто предполагаем что баг не наш а ProtonVPN'а.

Они видят другой ВПН и не стартуют. А могли бы

**Comment by pdkpv** [comment]
@ameshkov они говорили примерно тоже самое, но про AG)

Попробую им отправить новый тикет с ссылкой на эту проблему, может быть что-нибудь новое произойдёт...

**Comment by ameshkov** [comment]
Ахах, ну обождите пять сек

**Comment by pdkpv** [comment]
Оке

**Comment by pdkpv** [comment]
Версия Протона на данный момент 2.0.13 (бета)

**Comment by ameshkov** [comment]
Короче это все-таки кажется прошивочная проблема. У меня просто не повторяется - нормально все на паузу встает.

@TheHasagi а у тебя до сих пор повторяется?

**Comment by pdkpv** [comment]
@ameshkov  из шторки нажимаете?
![IMG_20191226_142301](https://user-images.githubusercontent.com/43634070/71474172-5419db80-27eb-11ea-9b0b-f02f8551a62d.jpg)

**Comment by ameshkov** [comment]
Ага, из нее

**Comment by pdkpv** [comment]
Записать ещё раз логи?

**Comment by ameshkov** [comment]
Ага, отправьте на devteam@adguard.com

**Comment by pdkpv** [comment]
Готово

**Comment by ameshkov** [comment]
Вероятность того, что это их косяк прямо очень велика.

Событие о том, что поднимается другой VPN прилетело только один раз - в 14:34:51.174. Судя по видео это когда вы второй раз уже из их интерфейса запускали.

**Comment by ameshkov** [comment]
Кстати, а если фильтрацию для их приложения отключить - меняется ли что-нибудь?

**Comment by pdkpv** [comment]
> меняется ли что-нибудь

Нет

**Comment by ameshkov** [comment]
Ну тогда точно их косяк:)

**Comment by pdkpv** [comment]
Жесть)

**Comment by ameshkov** [comment]
Причем он странный конечно - потому что на пикселе событие к нам приходит, а тут оно у вас в статусе Connecting почему-то подвисает
