### ISSUE TITLE
After changing AG's language but not enabling AG protection nor clearing AG app from the background and then opening it, it shows the previous language in long press shortcut.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3049]
After changing AG's language but **not enabling AG protection nor clearing AG app from the background and then opening it**, it shows the previous language in long press shortcut.

Ex: 
1. Change AG's language from Russian to English.
2. Don't enable AG protection.
3. It shows Russian in long press shortcut.

For letting it show the selected language in long press shortcut, need to ever enable AG protection or first clear AG app from the background and then open it after changing AG's language.

Can it apply the selected language in long press shortcut at once?

Just a trifle.
Sorry to bother you.

**Comment by lancelot-moon** [comment]
I found that it will show the matched language in long press shortcut as long as first clear AdGuard app from the background and then open AdGuard app (Don't need to enable AG protection).

**Comment by artemiv4nov** [comment]
This behavior has been changed in the 4.0 version, please follow updates
