### ISSUE TITLE
[Feature request] Make separate statistics for WiFi and Mobile data

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#305]

**Comment by TPS** [comment]
#202?

**Comment by ameshkov** [comment]
Yeah, clearly this is a duplicate.

@TPS, thank you!

**Comment by ameshkov** [comment]
@TPS by the way, v2.5 first beta version will arrive next week:) We are almost finished with implementing HTTPS filtering.

**Comment by TPS** [comment]
@ameshkov I appreciate the update:  I've been quiet (here :wink:) mostly to let you all work! ☺
