### ISSUE TITLE
Protection doesn't start when using Shadowsocks

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3050]
### Issue Details

- **AdGuard version:**  v3.3 nightly 2(5)
- **Filtering mode:** HTTP Proxy Manual
- **Device:** ASUS ZB602KL
- **Operating system and version:** Android 9
- **Root access:** No

### Actual Behavior

1) Run Shadowsocks
2) Connect to the server
3) Setup AdGuard as the outbound proxy
4) Try to start AdGuard protection
5) Unable to activate AdGuard protection

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64336468-b2754100-cfe5-11e9-9275-df53d1a1a83b.png)

</details>

**Comment by ameshkov** [comment]
Well, this is not how it should work.

You should:
1. Configure Shadowsocks to run as a Socks proxy 
2. Configure AdGuard to use Shadowsocks as a proxy (and not the way around)
