### ISSUE TITLE
Stealth mode set option issue

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3051]
### Steps to reproduce:

1. Open AdGuard - Settings - Stealth mode - Enable
2. Choose between High - Ultimate - Custom
3. Switch between these options rapidly

### Expected behaviour:

After a small delay option should be applied

### Actual behaviour:

Somehow you can enable all of those options at the same time

**Comment by admitrevskiy** [comment]
Done.
