### ISSUE TITLE
Change the target SDK level to 29 (Android 10)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3053]
Here's what we should do:

1. Dynamic theme: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme
    We'll need to add the "System default" option to our themes.
2. Check that there are no issues with the [scoped storage access](https://developer.android.com/training/data-storage/files/external-scoped) in the cases when we download an update, export/import settings/filters, etc.
3. Check if there are any places where we can use [settings panels](https://developer.android.com/about/versions/10/features#settings-panels).

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:
-Reinstall AG on device with Android Q aboard

1)
-Go to Settings -> General -> Theme -> System default
-Go to device settings and select `Dark theme`

Expected result:
-App Theme equals system theme

2)
-Examine Export/Import (settings/userfilter/whitelist/etc)

3) 
-Enable airplane mode
-Try to add Extension/Dns Filter/Custom filter via URL

Expected result:
-You will see Android internet Panel Settings

**Comment by carlylemiii** [comment]
> Go to Settings -> General -> Theme -> System default

Are you not opting for System default to _be_ the default, per Google's recommendation? Or is that testing step to verify that the setting is set that way?
