### ISSUE TITLE
Can't update version

### ISSUE THREAD

**Issue by proton777** [AdguardTeam/AdguardForAndroid#3054]
Running now on version 3.1 for Android.

There have been several recent updates and I have been unable to successfully do any of them. I download the apk file to my phone and try to run it but always get the same message "App Not Installed".

I tried many times and many ways but I always get the same message.  Installing from Unknown Sources has been enabled.

The only way to successfully install a newer version is to completely uninstall the previous one but then it is like starting over with a new app. The cache data and stored data are gone and I have to manually re-enter my license key.

Any help out there?

**Comment by artemiv4nov** [comment]
@proton777 Android uninstalled application not all. You have to uninstall application from Settings -> Applications.

**Comment by proton777** [comment]
Yes, that is how I uninstalled previous versions - Settings>Apps>AdGuard>Uninstall.

Now a new version can be installed but all the settings are gone and so is the license key.  I would like to install each new update on top of the existing one, without having to uninstall and start from the beginning like I do with a new app.

Thank you
