### ISSUE TITLE
The update window appears on top of all activities

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3055]
We should wait until the user will follow the onboarding steps before we can show the update window.

### Steps to reproduce:

1. Install AdGuard 
2. Launch it for the first time
3. Do not continue, just wait for 1 minute

### Expected behaviour:

Nothing will happen until the user will follow the onboarding

### Actual behaviour:

After ~ 1 minute you will see the update window

**Comment by admitrevskiy** [comment]
Cannot reproduce.
