### ISSUE TITLE
Speedtest.net keeps detecting VPN even when filtering for the app is disabled

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3057]
> I don't know if there's anything you can do about this, but the [Speedtest](https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest) app always reports as being run under a VPN due to AdGuard. This is even the case when AdGuard is set not to filter application traffic. But it causes the speed test to run in a less optimal mode, so it's rather a nuisance. If you can improve this from your side in any way that would be great!

**Comment by Revertron** [comment]
We cannot do anything with this.
