### ISSUE TITLE
Action bar with fixed position

### ISSUE THREAD

**Issue by domebacsi** [AdguardTeam/AdguardForAndroid#3058]
Make the navigation bar transparent on Android 10

AdGuard's implemantation:
![AdGuard](https://i.imgur.com/HUjMBu4.png)

Example of the transparent navigation bar on Google Calendar:
![Google Calendar](https://i.imgur.com/ya7VtEF.png)

**Comment by ameshkov** [comment]
Assigned to v3.5 for now, but first we'll need @AlikhanAliev's opinion on this.
