### ISSUE TITLE
AdGuard is displayed in incorrect display mode(landscape instead of portrait)

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3059]
### Issue Details

- **AdGuard version:**
  - 3.2.150 release
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung SM-J500F
- **Operating system and version:**
  - 6.0.1
- **Root access:**
  - No

### Expected Behavior

The app should correctly detect screen position and switch to portrait/landscape mode correctly.

### Actual Behavior

The app ALWAYS goes to landscape mode even though Screen Rotation is turned off

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_2019-09-04_171439](https://user-images.githubusercontent.com/33634917/64479789-b01d0d80-d1c4-11e9-8e72-013a03ad9b8a.png)

</details>

### Additional Information

Helpdesk ID: 1971228

**Comment by TheHasagi** [comment]
This issue related to TouchWiz OS. Any chance we can fix this? @artemiv4nov

**Comment by Eugene-Savenko** [comment]
Bit of a correction in that thread. The app does not "always" go in landscape mode/show incorrect display. This error happens to the app "randomly" and "regularly".

**Comment by akmLaVx** [comment]
Same problem with user 1140814.

**Comment by artemiv4nov** [comment]
Well, we are going to re-work all screens in a landscape position
