### ISSUE TITLE
Wrong description of Cloudflare DNS 

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3062]
In DNS server settings is specified that Cloudflare DNS can block malicious domains, Ads and Tracking.
But the official representative of the Team Cloudflare [denied this information](https://community.cloudflare.com/t/does-cloudflare-1-1-1-1-block-malicious-domains-ads-and-tracking/14870).
Please remove this tab.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64536629-179c9f80-d322-11e9-93b0-0e2789dec9da.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64536655-21260780-d322-11e9-8820-d19387336b66.png)

</details>

**Comment by ameshkov** [comment]
@Chinaski1 do we have this mistake in the iOS version? If so, please create an issue there as well

**Comment by Chinaski1** [comment]
Got it!

**Comment by admitrevskiy** [comment]
Done.
