### ISSUE TITLE
Flamingo for Twitter can't load images

### ISSUE THREAD

**Issue by sviperz** [AdguardTeam/AdguardForAndroid#3064]
**Flamingo for Twitter** can't load images in the feed. If **AG** is switched off or **Flamingo for Twitter** is excluded from the filtering, everything works as expected. It started about two nightlies back.

Please fix.

![Screenshot_20190910-114821](https://user-images.githubusercontent.com/11470610/64627790-efcc3b00-d3f8-11e9-85fe-3940a65ba2f5.png)

### Environment
* Adguard version: v3.3. nightly 3 (14)
* Adguard filtering mode: VPN
* Device model: Google Pixel 3
* OS: Android 10
* Flamingo for Android version: 18.0
* No root

**Comment by carlylemiii** [comment]
See also https://github.com/AdguardTeam/AdguardFilters/issues/40135

**Comment by sviperz** [comment]
Suddenly, the issue has been fixed by the dev of Flamingo in the latest beta version v18.1.1.

![Screenshot_20190911-065123](https://user-images.githubusercontent.com/11470610/64676564-8989fb80-d47e-11e9-8d70-211cb4b9fb8d.png)
