### ISSUE TITLE
AdGuard DNS blocks Xbox Beta App

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3066]
### Issue Details

- **AdGuard version:**
  -  3.2.150
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Samsung SM-G955U
- **Operating system and version:**
  -  Android 9
- **Root access:**
  -  No

### Actual Behavior

1) Open Xbox Beta settings
2) Configure dns.adguard.com as Private DNS sever
3) AdGuard DNS seems to block friends functionality in the Xbox Beta
Android App

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64707813-43538d00-d4bc-11e9-8c0d-0713a1d86d15.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64707836-4b133180-d4bc-11e9-84b1-1d67ad89ed6c.png)

</details>

### Logs in NCloud

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #127](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/127) via [**ZenHub**](https://www.zenhub.com/)
