### ISSUE TITLE
Compatibility with ExpressVPN

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#307]
https://play.google.com/store/apps/details?id=com.expressvpn.vpn
Have ExpressVPN running, Adguard is in Proxy mode (manual).
After a short while both ExpressVPN and Adgaurd turn off.

Logs - CGW-678-46796
It dropped at around 20:59

**Comment by ameshkov** [comment]
@gshumihin test it please.

**Comment by gshumihin** [comment]
I cannot connect to their servers even without adguard. tested few countries, and few devices. This VPN doesn't work for me :( Tried with couple devices.

**Comment by gshumihin** [comment]
Finally was able to connect to ExpressVPN. After couple hours both adguard and ExpressVPN works fine. Seems like android kills processes at user's side.

**Comment by Androidman18** [comment]
How were you able to get both to work express vpn and aguard

**Comment by ameshkov** [comment]
@Androidman18 this is possible if you are in the proxy+root filtering mode
