### ISSUE TITLE
com.udemy.android - app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3072]
@Alex-302 commented on [Mon Sep 16 2019](https://github.com/AdguardTeam/CoreLibs/issues/1127)

@adguard-bot commented on [Fri Sep 13 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40416)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.udemy.android](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.udemy.android)
### Comment
Username: @Rakleed
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/6hnzRZi.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ECnmHne.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your User-Agent ()
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>Filter unblocking search ads and self-promotion,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Alex-302 commented on [Mon Sep 16 2019](https://github.com/AdguardTeam/CoreLibs/issues/1127#issuecomment-531728867)

Exclusions don't help. This app works when AdGuard protection is disabled.
`13:47:25.045 [Thread-7] DEBUG Native.AGIpReachabilityTester - [id=230] operator() Connection to [2606:4700::6810:5b34]:80 failed: Error connecting to [2606:4700::6810:5b34]:80. Error: 101(Network is unreachable)`
Log:
[adguard.txt](https://github.com/AdguardTeam/CoreLibs/files/3615897/adguard.txt)
IPv6 is not provided by my ISP.

You can use random email and name to reproduce this issue.

**Comment by ameshkov** [comment]
This looks just like the case with the Facebook app

**Comment by artemiv4nov** [comment]
@ameshkov you mean, Facebook Lite app? I think we can try to add an application to a special "VPN-reconfigure-if-app-installed" list.

**Comment by admitrevskiy** [comment]
Can't reproduce. Looks like the latest version of `com.udemy.android` has no issues with AdGuard.

**Comment by Rakleed** [comment]
@admitrevskiy у меня при попытке залогинится появляется ошибка. Помогает отключение фильтрации HTTPS для этого приложения. Но хотелось, чтобы для этого приложения по умолчанию была отключена фильтрация HTTPS.

<details>
<summary>Screenshot</summary>

![Screenshot_20191108_110729](https://user-images.githubusercontent.com/19418601/68460105-0daaf600-0218-11ea-85d7-01d324702741.png)

</details>

**Comment by artemiv4nov** [comment]
@Rakleed вы проверили на последней версии найтли AdGuard с последней версией Udemy?

**Comment by Rakleed** [comment]
@artemiv4nov да.

**Comment by artemiv4nov** [comment]
@admitrevskiy let's add the app to the HTTPs exclusions list

**Comment by admitrevskiy** [comment]
Done.
