### ISSUE TITLE
Adguard 3.2 does not launch

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3076]
### Issue Details

- **AdGuard version:**
  -  v3.3 nightly 5 / latest realese

### Actual Behavior
After installing version 3.2 the application does not start.

### Customer ID

2296943

MarkFrom4PDA

**Logcat in NCloud**

### Additional Information

Both users run AdGuard  without problems on version 3.1

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA: no needs
