### ISSUE TITLE
com.gsgroup.tricoloronline.mobile - app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3077]
@adguard-bot commented on [Sat Aug 17 2019](https://github.com/AdguardTeam/AdguardFilters/issues/38752)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.gsgroup.tricoloronline.mobile](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.gsgroup.tricoloronline.mobile)
### Comment
> При включенном Adguard приложение Онлайн ТВ от Триколор выдаёт ошибку 21 и не запускается. При отключении Adguard приложение работает нормально.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/2ts0jkp.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/WWpuCqN.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | v3.1.0 (1.3.347cl)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (180)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Malware Domains,<br>Spam404,<br>NoCoin Filter List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Alex-302 commented on [Tue Aug 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/38752#issuecomment-523087282)

@slavaleleka проверь у себя. На мой девайс не установить.

**Comment by Alex-302** [comment]
Probably a bug. Cannot check.

**Comment by slavaleleka** [comment]
I've checked and filtering log was empty, so definitely a bug

**Comment by admitrevskiy** [comment]
Looks like with the latest versions of AG and `com.gsgroup.tricoloronline.mobile` everything works fine.
@slavaleleka  could you re-check it, please?

**Comment by slavaleleka** [comment]
the tricolor app works fine now
