### ISSUE TITLE
Анимация включения защиты после применения настроек

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#3078]
### Problem Description

При изменении настроек и переходе на главный экран переключатель защиты находится в выключенном положении, потом через несколько секунд включается. При этом нет никакой анимации, что сейчас идёт включение защиты. Из-за этого хочется вручную включить защиту, что не требуется.

### Proposed Solution
Добавьте анимацию при автоматическом отключении и включении защиты при изменении настроек, как это сделано в приложении для Windows.

**Comment by artemiv4nov** [comment]
Обновили главный экран и уведомление, должно получше стать.
