### ISSUE TITLE
[Feature request] Disable / Enable function for filter rules

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardForAndroid#308]
For better debuging / testing filter rules on Android.

**Comment by ameshkov** [comment]
Filter rules editor is a desirable feature, but it is pretty hard to implement.

I'll plan this on v4 now.

**Comment by TPS** [comment]
@ameshkov If I understand, @Vincent-Michael isn't quite (yet ;) asking for a full-blown editor, but more of of a toggle-list of filter rules, something like desktop AB+ has.  If I'm correct, making said toggle-list sortable (by # hits, recent hits, &c) & filterable/searchable (by typing in page/asset to match) would probably be necessary to make this practically functional.

So, yes, big task!

**Comment by Revertron** [comment]
The user filter was reworked, and it can enable/disable rules as you want.

**Comment by TPS** [comment]
@AdGuardTeam. This isn't working correctly, @ least as of the last few ßs: Un☑️ing the filter does ___NOT___ disable the user filter, as shown in the filtering log.  I actually have to manually nonsense the filter (e.g., by adding `//` to front) to keep AG from implementing.

**Comment by ameshkov** [comment]
@TPS does it help to manually restart the protection after unchecking a rule?

**Comment by TPS** [comment]
Nope, even though "Applying Settings" pops-up, tried _that_ , killing AG & restarting, & even rebooting (just in-case something was stuck on my phone).

I just tried it again w/ current ß.  Same behavior. 🤷‍♂️

**Comment by ameshkov** [comment]
I don't yet understand why is that so, reopened, let's re-test it.

**Comment by TPS** [comment]
Of course, [I'm still stuck @ .108](https://github.com/AdguardTeam/AdguardForAndroid/issues/1396#issuecomment-336769269), so I'm probably missing many new features/fixes.

**Comment by TPS** [comment]
Still same for .142, though.

**Comment by Revertron** [comment]
Now (in 2.10.186) it works perfectly!
Just unticking the rule and refreshing page in browser does the magic.

**Comment by Revertron** [comment]
Retested it.
If I enable/disable a rule blocking a domain of some simple application, it really works great.
But, for example, with `ya.ru` domain in a browser it behaves rather weird.
