### ISSUE TITLE
Request trial via OAuth

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3081]
Currently, we ask users to enter the email address when starting trial period. We should allow using social accounts as an option.

@AlikhanAliev we need a mockup for that.

**Comment by AlikhanAliev** [comment]
https://share.goabstract.com/a9ef7833-3fe3-4848-b7f4-cce0bff477c1 - Win
https://share.goabstract.com/b302f737-8a1e-4361-920e-88ee486a74d5 - Android

**Comment by ameshkov** [comment]
@artemiv4nov you can use custom `adguard:` scheme as a redirect URL for the OAuth endpoint
