### ISSUE TITLE
Hide Referrer from third-parties function fails in that purpose

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3083]
### Issue Details

- **AdGuard version:**
  -  3.3 Nightly 5(25-1.4.138CL)
- **Filtering mode:**
  -  Local VPN
- **Operating system and version:**
  -  Android 9

### Expected Behavior

Function **Hide Referrer from third-parties** should conceal what website we visited.

### Actual Behavior

For example, I try to test in on [amiunique.org/fp](amiunique.org/fp)

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/65425870-b42d6a00-de17-11e9-9dd1-493eedd9a93c.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/65425860-ae378900-de17-11e9-8ebc-e29f3280164f.png)

</details>

**Comment by d0x360** [comment]
This was the issue I reported via the app a couple weeks ago so you probably have my logs.  If you need any more info from me just let me know.

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/CoreLibs #1136](https://github.com/AdguardTeam/CoreLibs/issues/1136) via [**ZenHub**](https://www.zenhub.com/)
