### ISSUE TITLE
Add proxy auto-switching

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3084]
### Problem Description

AdGuard is unable to automatically switch between proxies based on their speed / latency.

### Proposed Solution

Allow AdGuard to automatically switch between user-specified proxies depending on their speed.

### Alternatives Considered

None considered.

### Additional Information

Reported by helpdesk user 1553986

**Comment by artemiv4nov** [comment]
I'll close this task, it's not so popular
