### ISSUE TITLE
Option to export all settings has disappeared (v3.3 Nightly 5 (25))

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#3085]
### Prerequisites

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

### Issue Details
Option to export all settings has disappeared

- **AdGuard version:**
  - 3.3 nightly 5 (25)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 2 XL
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

In the Settings page, there should be a button to export all settings

### Actual Behavior

There is no button in the top right corner to export settings

![ScreenshotCapture_2019_09_25_09_19_38_081](https://user-images.githubusercontent.com/17823400/65574486-4c416580-df76-11e9-996b-07450a93c64f.png)

**Comment by admitrevskiy** [comment]
@SergeiShir hi!
Export / Import settings has been moved to `General`

**Comment by SergeiShir** [comment]
Thank you for quick response
