### ISSUE TITLE
AdGuard crashes when pinging a domain via PingTools 

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3086]
### Repro
1. Install PingTools from https://pingtools.org/
2. Attempt to ping any website (eg. example.com)
3. AdGuard crashes

### Issue Details

- **AdGuard version:**
  - 3.2.150 (Release)
- **Filtering mode:**
  - Local VPN, high-quality
- **Device:**
  - Motorola Moto G (5)
- **Operating system and version:**
  - Android 8.1.0
- **Root access:**
  - No

### Expected Behavior

PingTools pings the website, AdGuard works as usual

### Actual Behavior

PingTools pings the website, AdGuard crashes

### Additional Information

Logs: 2321485

**Comment by Chinaski1** [comment]
Login in *NCloud*
**Time: 16:17**

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1158](https://github.com/AdguardTeam/CoreLibs/issues/1158) via [**ZenHub**](https://www.zenhub.com/)
