### ISSUE TITLE
Xiaomi Mi 9T Not always showing VPN badge - Android keeps turning it off.

### ISSUE THREAD

**Issue by JonnyRedHed** [AdguardTeam/AdguardForAndroid#3088]
- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed

### Issue Details

Xiaomi Mi 9T  - New - Global version set to UK.

AdGuard version:  Latest as writing this.
Local VPN on
Xiaomi Mi 9T up to date Android 9,  10 coming next month.
Not Rooted.

Expected Behaviour

Adguard not always, seldom showing the local VPN badge on top right next to wifi and 4g section

Getting android notifications saying local vpn not active, open adguard to activate. Doesn't appear to turn it back on until reboot. Have given adgaurd permissions in all sections, inc always on vpn for it. But it keeps going off.

I can't take photo to show you the vpn badge, sorry.

I'm guessing this Xiaomi Mi 9T is still pretty new and you guys haven't got around to checking it.

**Comment by TheHasagi** [comment]
@JonnyRedHed 

Hello, this issue is not related to AdGuard, the VPN icon is a system-based function that should be handled by MIUI. As it was already spoken in #2780 - unfortunately, we can not do anything here.

**Comment by JonnyRedHed** [comment]
I understand, thanks for the reply.
