### ISSUE TITLE
Friendly snacks

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#3089]
We should correct a font size, a snack's height etc. It should be same as on layout

https://share.goabstract.com/aed96260-9d1d-4cc4-827c-5661879cd8a2?sha=1a96533a1efc9c3ad3967deb358dd9d07e5a405c

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30260021/65682602-eaf7c000-e063-11e9-9284-feda3901e462.png)

</details>

**Comment by artemiv4nov** [comment]
The task has already been fixed
