### ISSUE TITLE
Add Hungarian language

### ISSUE THREAD

**Issue by zoli456** [AdguardTeam/AdguardForAndroid#309]
The translation is full but some lines are locked. Can you unlock them? I would like change some of them.

**Comment by ameshkov** [comment]
Yeah, we'll do it today, thank you!

@vbagirov pease take a look at it.

**Comment by vbagirov** [comment]
I have unfinalized all the lines, you should now be able to modify them.

**Comment by zoli456** [comment]
Now you can add the language. (Can you unlock this line "Ⓒ 2008-2016 Performix LLC, All rights reserved." in Adguard 6.x /Adguard UI?)

**Comment by ameshkov** [comment]
Done

**Comment by ameshkov** [comment]
Added, will appear soon in the first beta release.
