### ISSUE TITLE
Proxy screen corrections

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#3092]
We should use [this layout](https://share.goabstract.com/0296dcd9-a9e5-43e8-9b87-570c3b2453db?sha=977ce3f4913be876e6c902fca13f4fff82359999)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30260021/65683032-f0a1d580-e064-11e9-8b61-7b819f35912c.png)

</details>

**Comment by admitrevskiy** [comment]
Done.
