### ISSUE TITLE
Allow local VPN to fixate packet TTL

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3094]
Requested by user 2324870

### Description
Не ли технической возможности
внедрить фиксацию TTL всех пактов во встроенный VPN? Это даст возможность
смартфонам, на котором установлено ваше приложение, невозбранно раздавать
интернет на тарифных планах, на которых раздача запрещена. Уверен, это
повысит популярность вашего приложения + может служить хорошим стимулом для
покупки полной версии.

**Comment by ameshkov** [comment]
We have no access to the traffic from devices connected to hotspot
