### ISSUE TITLE
Let's do Proxy list like in the Telegram app

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#3099]
### Problem Description

Now we have to check Proxy availability manually

### Proposed Solution

Start availability checking on Proxy list view automatically
Show a status below each added Proxy 
Remove "check" button

https://share.goabstract.com/0142e267-8d93-424a-a2c7-0a7667a083ec?sha=2d77621283131a7de16235e905bd236c879fec37

**Comment by artemiv4nov** [comment]
We already reworked this behavior in the new version.
