### ISSUE TITLE
Incorrect firewall traffic stats

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#31]
http://forum.adguard.com/showthread.php?6532-Beta-Version-2-0-23-Firewall-mobile-usage-display-by-far-not-correct&p=59095#post59095

**Comment by Revertron** [comment]
Unable to find what is wrong with those screens :(

**Comment by ameshkov** [comment]
The problem with that issue is that the traffic stats are too "small".

What could help us with this situation? Maybe we can somehow get access to his SQLite db?

**Comment by Revertron** [comment]
The log file was very small. Only one thing seems unusual to me:
TCP id=1741 Client null has not sent any data to the connection.
TCP id=1742 Client null has not sent any data to the connection.
TCP id=1743 Client null has not sent any data to the connection.
Some connections are going from "null" app. May be our NetConnectionFinder is not working properly on that particular device and sometimes all connections are "anonymous"...

**Comment by ameshkov** [comment]
These unidentified connections should be tracked as generic TCP traffic in Firewall

**Comment by Revertron** [comment]
I did it! The bug was in StatisticsTrafficServiceImpl. There was an exception that was catched somewhere else and wasn't visible.
