### ISSUE TITLE
"Cell standby" process consumes a lot of battery when Adguard is installed

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#310]
"Сеть оператора связи" вырывается вперед даже если защита выключена. Т.е. если adguard на телефоне установлен, то не имеет значения включен он или нет. Я в прошлом письме оговорился. Если удалить adguard, то через некоторое время сеть оператора связи уходит в низ списка и показывает ~2 или 3%. Adguard в статистике впринципе никогда не отображается воскресенье, 

Adguard is on
<details> 
![image](https://cloud.githubusercontent.com/assets/15856304/13183988/1a329f86-d742-11e5-9600-c2f4f5678914.png)
</details>
Adguard is off
<details> 
![image](https://cloud.githubusercontent.com/assets/15856304/13183961/0718f7e2-d742-11e5-8bd1-e1a7a54db257.png)
</details>
Adguard is uninsalled
<details> 
![image](https://cloud.githubusercontent.com/assets/15856304/13183978/0f38092c-d742-11e5-8b9f-1ae27d18b081.png)
</details>

more screens, logs, descriptions and stuff ZHO-651-37977

**Comment by ameshkov** [comment]
@Revertron please take a look, any thoughts?

I just have no idea, that's impossible:)

**Comment by TPS** [comment]
#215/#578?

**Comment by ameshkov** [comment]
That's a firmware bug, I've seen this issue once already.
