### ISSUE TITLE
Error notification while custom local stored filter updates

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForAndroid#3101]
### Issue Details

**AdGuard version:** 3.3 nightly 7
**Operating system and version:** Android 9

### Actual Behavior

<details><summary>look at this:</summary>

![Screenshot_20191001-165121](https://user-images.githubusercontent.com/45171506/65972050-eec78000-e471-11e9-96fa-310d434195eb.png)

</details>

### Expected Behavior

There is notification bottom padding which shouldn't be.

I guess error notification should not be green. And I would like to have an opportunity to disable problematic filter just right through that error notification.

<details><summary>something like that:</summary>

![slbdzd8l wsgkz](https://user-images.githubusercontent.com/45171506/65973414-f5ef8d80-e473-11e9-9eb6-edc4e716ab28.png)

</details>

**Comment by artemiv4nov** [comment]
Also, we should not show a local path to filter file in a notification.

**Comment by admitrevskiy** [comment]
This issue was fixed in https://github.com/AdguardTeam/AdguardForAndroid/issues/2997
