### ISSUE TITLE
com.nikkei.newspaper app is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3102]
@adguard-bot commented on [Sat Sep 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41362)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.nikkei.newspaper](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.nikkei.newspaper)
### Comment
> The need feed in Nikkei fails to load at all. It might be blocking the ads that show up within the app. It'd be nice if shared could block them, but I wouldn't mind seeing them if it means being able to read the articles. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/axyRMZq.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/EBPUa5W.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | EasyList,<br>AdGuard Mobile Ads,<br>AdGuard Base,<br>Peter Lowe's list,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Japanese

**Comment by Alex-302** [comment]
On my device it is not working with AdGuard DNS only(with filters and with another DNS it works).
Not sure if it is broken by AdGuard app or AdGuard DNS, don't see network requests from this app in filtering log.

**Comment by TheHasagi** [comment]
Confirmed. Only disabling ad blocking helps.

**Comment by admitrevskiy** [comment]
This issue was caused by the following rule in SDN filter: `||n8s.jp^`
The application was unable to load the feed since the same rule was used on the server side.

This rule was removed from SDN filter and now app works fine.
