### ISSUE TITLE
Notifications for which apps cause pop-ups.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3111]
For advanced users, it's not difficult to find adware apps by filtering log.
But it may be not easy for beginners.
Especially, full-screen pop-ups by adware apps which automatically work in the background are annoying.

I see this on google play:
https://play.google.com/store/apps/details?id=popup.ads.detector

Is it possible to have notifications for **which apps automatically cause pop-ups in the background**?
**Then beginners can easy find and uninstall adware apps.**

**Comment by ameshkov** [comment]
Interesting, have you tried it?

**Comment by lancelot-moon** [comment]
No, I don't try apps from China as possible.
You know some users may be uninformed about installed adware apps.
Users may want to delete them but don't know which apps cause pop-ups.
If AdGuard can realize this feature request, it's helpful for users.
Thanks.

**Comment by artemiv4nov** [comment]
It looks like not so popular feature request. Closed.
