### ISSUE TITLE
Material Theming

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#3112]
Пожалуйста, сделайте дизайн приложения в стиле Material Theming (это расширение Material Design, которое было представлено на Google I/O 2018). Material Theming позволяет более тонко настраивать Material Design, и Material Theming мне больше нравиться, чем более старая версия Material Design. Полезные ссылки: https://material.io/design/material-theming/overview.html, https://material.io/develop/android/docs/theming-guide/.

**Comment by ameshkov** [comment]
Ну это уже на 4.0 хотелка.

Я пока что прикрою таск потому что потеряется он, слишком общий.
Когда будем делать редизайн, постараемся учесть конечно текущие (на тот момент) гайды от гугла.
