### ISSUE TITLE
Virtual host function for AdGuard

### ISSUE THREAD

**Issue by oncev** [AdguardTeam/AdguardForAndroid#3113]
Could you add the virtual hosts function for  AdGuard, such as setting "12.33.45.56 google.com" in hosts.

These can be done without root by VPN through "Virtual Hosts" -- a open source android app ( https://github.com/x-falcon/Virtual-Hosts ) .

**Comment by ameshkov** [comment]
You can do it already in your DNS User filter, it understands hosts syntax just okay.
