### ISSUE TITLE
Can't see the button on VPN first start dialogue Screen

### ISSUE THREAD

**Issue by vyanovsky** [AdguardTeam/AdguardForAndroid#3114]
On a kyocera 705KC smartphone (https://www.ymobile.jp/lineup/705kc/), in the VPN first start dialogue the button is placed outside of the screen and can't be seen. 
![image (22)](https://user-images.githubusercontent.com/51786050/66294700-45114480-e8f2-11e9-8338-7db57646c35b.png)

Phone screen specs: 5 inch, 1,280×720（HD）

**Comment by artemiv4nov** [comment]
Well, this dialog will be changed in the next release of the AdGuard. We'll fix the issue during re-work on this dialog.

**Comment by admitrevskiy** [comment]
Done.
This changes will be available in v3.3 beta2
