### ISSUE TITLE
ru.myshows.app - app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3117]
@adguard-bot commented on [Sun Oct 06 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41840)

https://play.google.com/store/apps/details?id=ru.myshows.app

### Comment
Username: @Globulopolis
> При включении фильтрации, приложение myshows не может получить доступ в сеть. Отключение всех фильтров, расширений и т.п. ничего не даёт. В логах АГ нет информации о блокировках для этого приложения(включено полное логирование запросов). Если отключить фильтрацию крыжиком на главной странице АГ, то myshows может выходить в интернет.

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | v3.2.150 (1.4.138cl)
Browser: | Brave
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (180), Block WebRTC, Block Push API, Block Location API
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Alex-302 commented on [Mon Oct 07 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41840#issuecomment-539085509)

@Globulopolis вот это приложение?
https://play.google.com/store/apps/details?id=ru.myshows.activity&hl=ru
У меня в нём не повторилось. Фильтрацию HTTPS для приложения не включали вручную?

---

@Globulopolis commented on [Tue Oct 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41840#issuecomment-539431964)

@Alex-302 нет. Вот это https://play.google.com/store/apps/details?id=ru.myshows.app

---

@Alex-302 commented on [Tue Oct 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41840#issuecomment-539438898)

Тоже не повторилось. ~В настройках приложений в Адгарде не включали фильтрацию HTTPS для этого приложения?~

---

@Alex-302 commented on [Tue Oct 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41840#issuecomment-539439342)

Можете сделать скриншоты переключателей на экране настроек приложения в АГ?

---

@Globulopolis commented on [Tue Oct 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41840#issuecomment-539444366)

<details>

![Screenshot_2019-10-08-13-00-14-177_com adguard android](https://user-images.githubusercontent.com/740757/66387096-ecae7580-e9cb-11e9-9cd0-1f8c3605cafb.png)
![Screenshot_2019-10-08-13-00-21-119_com adguard android](https://user-images.githubusercontent.com/740757/66387106-f0da9300-e9cb-11e9-8310-8ecf6e352fbc.png)

 </details>

**Comment by Alex-302** [comment]
@Globulopolis запишите, пожалуйста, отладочный лог
https://kb.adguard.com/ru/android/solving-problems/log#debug
и прикрепите его сюда в виде архива ZIP.

**Comment by Globulopolis** [comment]
[adguard_logs_3.2.150_0810_225702.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3704303/adguard_logs_3.2.150_0810_225702.zip)
22:56 примерное время проблемы.

**Comment by Alex-302** [comment]
Отсюда удалил, т.к. там могут быть приватные данные(ip, mac-адреса, адреса страниц). Утром загрузим куда следует.
А лог точно отладочный? Не вижу в нём упоминания `ru.myshows.app`

**Comment by Globulopolis** [comment]
> А лог точно отладочный? Не вижу в нём упоминания ru.myshows.app

Да. Делал согласно инструкции.

**Comment by zzebrum** [comment]
logs are in ncloud

**Comment by TheHasagi** [comment]
@Globulopolis 

Не могли бы вы попробовать с последней [Nightly](https://agrd.io/android_nightly) версией? Отключение функции DNS фильтрации дает возможность приложению получить доступ в сеть? Проверьте заодно не отключили ли вы вручную доступ приложению по пути AdGuard - Менеджер приложений - My Shows. С аналогичными настройками на моем устройстве не воспроизводится.

**Comment by Globulopolis** [comment]
@TheHasagi без изменений.
PS! Проверил на полностью новом телефоне на android 8.0.0.

**Comment by artemiv4nov** [comment]
@Globulopolis

В логах ничего не видно, приложение даже никак не фигурирует.

Однако была замечена активность `com.lbe.security.miui`.
Какой у вас телефон?
Если MIUI прошивка, то попробуйте, пожалуйста, отключить фильтрацию для `com.lbe.security.miui` приложения (LBE Security Manager).

**Comment by Globulopolis** [comment]
@artemiv4nov 

> Какой у вас телефон?

Один xiaomi mi4c на прошивке xiaomi.eu 9.5 стабильная(7-ой андроид), второй galaxy s9+ На обоих телефонах одна и та же проблема с этим приложением при одинаковых настройках AG.

**Comment by artemiv4nov** [comment]
Мы проверили заново на различных версиях Андроида это приложение, проблема не повторяется. Возможно, проблема именно в странном поведении Андроида на китайском смартфоне.
@Globulopolis у вас все ещё повторяется?

**Comment by Globulopolis** [comment]
Проверил, работает.
