### ISSUE TITLE
Automatically pause protection while LG Pay is being used

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3122]
Similarly to Samsung Pay, AdGuard should be able to pause protection while the user is paying for someting with LG Pay.

**Comment by TheHasagi** [comment]
Please, add the following package to the exclusions:
com.lge.lgwallet

**Comment by ameshkov** [comment]
@akmLaVx is this specific to Korea? Samsung Pay compatibility is, for instance.

**Comment by akmLaVx** [comment]
Unfortunately, the user has gone dark, so we cannot provide any additional details at this point.

**Comment by artemiv4nov** [comment]
The task was closed. Please, re-open it if the problem will available again.
