### ISSUE TITLE
Print some information about the DNS filter list in the "New DNS filter" dialog

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3124]
The current "New DNS filter" dialog might be confusing and lead to smth like this: https://github.com/AdguardTeam/AdguardForAndroid/issues/3123

In order to avoid confusion, we should print some information about the downloaded DNS filter right in the same dialog window where we ask the user to enter its name.

At least we could print rules count and the URL

**Comment by Crescendo-BLYAT** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/3265
