### ISSUE TITLE
The "missed ad" option in the Android feedback section leads to a search error

### ISSUE THREAD

**Issue by sophisticated-zero** [AdguardTeam/AdguardForAndroid#3128]
### Issue Details

- **AdGuard version:**
  - v3.2.150
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Meizu M6 Note (but it's on any phone, doesn't matter
- **Operating system and version:**
  - Android 7.1.2
- **Root access:**
  - No

### Expected Behavior

The "missed ad" option on the Android feedback section should open the report page when DuckDuckGo browser is selected as a default browser.

### Actual Behavior

The "missed ad" option on the Android feedback section gives a search error when DuckDuckGo browser is selected as a default browser

### Screenshots

![S91011-163924](https://user-images.githubusercontent.com/39196837/66656696-2ccd5c80-ec47-11e9-9657-507f3ca38e85.jpg)

**Comment by admitrevskiy** [comment]
Done.
