### ISSUE TITLE
When update userscript, only download meta part not full script.

### ISSUE THREAD

**Issue by steven7851** [AdguardTeam/AdguardForAndroid#3129]
As title and Ex. https://adsbypasser.github.io/releases/adsbypasser.full.es7.user.js

**Comment by ameshkov** [comment]
Well, that's what we do.

AdGuard first downloads `https://adsbypasser.github.io/releases/adsbypasser.full.es7.meta.js` and checks if there's an update available. Only if it's available, it downloads the full script
