### ISSUE TITLE
Do not establish unnecessary SSL connections

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#313]
While fixing this issue we MUST not forget about security and certificates verification.

#### Problem 1: Blocked requests. 
Request can be blocked, but AG establishes an encrypted remote connection anyway.

#### Problem 2: injections.adguard.com domain (used for AG injections)
Currently we use an ugly workaround:
1. Client connects to injections.adguard.com (which is in fact just a cloudflare "cache everything" host)
2. Adguard intercepts this connection and handles it locally (returning necessary CSS/JS)

**Problem:** there is still an empty remote connection which we do not need. We need this in order to have a host with valid HTTPs certificate so that client can establish a secure connection with it.

Instead of this we should:
1. Redirect connection to localhost
2. In case of plain HTTP everything is simple (the same as it was in previous version)
3. In case of HTTPs we should:
3.1. Establish a secure connection with client app
3.2. Establish a plain connection with localhost

**Comment by ameshkov** [comment]
Too complicated, let's do it in v2.6

**Comment by ameshkov** [comment]
In the end it was not that complicated. Done.

**Comment by TPS** [comment]
#363 have any relation to this, you think?  Do you think fixing this helped that? (This is keeping in mind, on the *nixes, ["everything is a file"](https://en.m.wikipedia.org/wiki/Everything_is_a_file).

**Comment by ameshkov** [comment]
@TPS no, there's not so many such connections. #363 is still about some app behavior.
