### ISSUE TITLE
Improve HTTPS whitelist filter

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3131]
### Problem Description

HTTPS whitelist is extremely difficult to either navigate or edit.

### Proposed Solution

Provide better text editing functionality in HTTPS whitelist

### Alternatives Considered

Allow users to export HTTPS whitelist to third-party text editors

### Additional Information

Reported by helpdesk user 2345406

**Comment by dviree** [comment]
or maybe tbat we can do a proper bulk change. like mark the apps by holding them down. we only wanna block ads here not injure my thumb

**Comment by artemiv4nov** [comment]
Reassigned to 3.4

**Comment by artemiv4nov** [comment]
After all, I don't think to implement this functionality.
