### ISSUE TITLE
Enable TLS 1.3 in dnsproxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3132]
It seems that we have not yet enabled TLS 1.3 in the mobile dnsproxy build.

We should do it.

Test server:
`https://dns.glassrom.pw/dns-query`

**Comment by admitrevskiy** [comment]
Done.

Testing instructions for QA:

- Reinstall AG
- Check if `https://dns.glassrom.pw/dns-query` is available using [dnslookup](https://github.com/ameshkov/dnslookup)
- Try to add custom DNS server with `https://dns.glassrom.pw/dns-query` upstream
