### ISSUE TITLE
com.dcinside.app - app is not working as it should be

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3135]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/41411

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Base,<br>List-KR,<br>AdGuard Tracking Protection
Other extensions used: | Unicorn adblocker for samsung browser

### Actual Behavior

@skh1995328
`This app stops very frequently with adguard. But it does not happen always. After 5~10 tries, i can see the page. It happens even I turn off "block ads" at app management menu in adguard. The app only works well when adguard has turned off or there is no any filtering for dc app. I tried many whitelists but they didn't work. However when I change some adguard settings like DNS or delete and reinstall the app, it works very well! But it doesn't happen again for same change. When it happens, the app works fast at first, but it stops more frequently as time goes. At last, I can see only one page for over 20 clicks.`

Not reproduced on my device(Sony xperia xz1с, Android 9).

**Comment by skh1995328** [comment]
I found some users in community 'dcinside' who suffering same problem, but I don't know their device conditions.

**Comment by ameshkov** [comment]
@skh1995328 it sounds that the app does not react well on blocking some of the trackers, but it's hard to say which ones are the problem.

Here's what you can do:
1. Disable DNS filtering completely (in this case you'll see what exact trackers from this app are being blocked)
2. Try unblocking some of them and see if it helps

If you can narrow it down to some specific tracker, we'll be able to handle this in the filter lists.

**Comment by TheHasagi** [comment]
@skh1995328 

It really can depend on DNS resolver. If you change it for another one issue continues?

**Comment by TheHasagi** [comment]
Can not reproduce the issue. Closed. Should be reopened if needed.
