### ISSUE TITLE
Block Youtube app ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#314]
They use VAST/VPAID protocol serialized by protobuf.

**Comment by ameshkov** [comment]
Some useful links:
http://www.segmentationfault.fr/publications/reversing-google-play-and-micro-protobuf-applications/
https://github.com/androguard/androguard

**Comment by ameshkov** [comment]
New alpha version contains a temporary solution: blocking YT video ads only.

**Comment by TPS** [comment]
@ameshkov In blacklist mode, how do I access this?  Is there _anything_ I should put in the blacklist? Or does AG recognize & filter by itself?  If _something_ should be added,  maybe all the various YouTube ad-hosting sites can be pre-populated in the blacklist by default, like all those banks, &c, in the whitelist?

**Comment by Revertron** [comment]
@TPS Add www.googleapis.com to blacklist.

**Comment by TPS** [comment]
@Revertron I think I (& others) wouldn't be comfortable with that, _unless_ we had a way to limit the Google APIs filtering to YouTube-related activities _only_.  1 heck of a _lot_ of other stuff goes through those APIs, & blacklist-mode is all about limiting all that MITM.  Besides, wouldn't that open up the likelihood of many, random problems, doing this so broadly?  Maybe I'm misunderstanding the blacklist mode, as I detail in https://github.com/AdguardTeam/AdguardForAndroid/issues/340#issuecomment-191092823.

**Comment by ameshkov** [comment]
@TPS 

We don't plan to limit HTTPs filtering on a per-app basis, at least for now. However, this is possible in future, when re-design is ready.

What about googleapis.com, I think it's a good idea to make a research, what is really goes through this domain.

Currently I see that YT actively uses it, also i saw these SafetyNet requests #339. I don't see any sensitive data going through it.

**Comment by TPS** [comment]
I'm not familiar w/ what Google APIs does on Android (due to lack of extensibility of my preferred browser), but, on PC, running Pale Moon w/ [NoScript](https://noscript.net/), [RequestPolicy Continued](https://github.com/RequestPolicyContinued/requestpolicy), [Ghostery](https://www.ghostery.com/our-solutions/ghostery-browser-extention/), & [uBlock](https://github.com/gorhill/uBlock), they show it pops up on a _pile_ of sites, not even just Google properties, & some of those _are_ sensitive (e.g., GMail, &c).

**Comment by ameshkov** [comment]
@Revertron here is an issue with YT ad blocking:
http://forum.xda-developers.com/showpost.php?p=65860048&postcount=756

**Comment by ameshkov** [comment]
Seems to be done
