### ISSUE TITLE
Allow AdGuard firewall to block app traffic in roaming connections

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3144]
### Problem Description

Currently, AdGuard's built-in firewall does not allow user to block apps from using mobile data in roaming.

### Proposed Solution

Allow AdGuard firewall to block app traffic in roaming connections

### Alternatives Considered

None available.

### Additional Information

Helpdesk ID: 2298177

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
