### ISSUE TITLE
by.gis.gidrometweather - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3147]
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/42416

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -   3.3 nightly 14
- **Filtering mode:** 
  -  VPN
- **Device:**
  -  Xperia XZ1c
- **Operating system and version:**
  -  9
- **Root access:**
  -  no

### Actual Behavior

An error when you open app(close it before checking).

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/66925523-3256e800-f035-11e9-83a9-179f60658b9a.png)

</details>

### Additional Information

Log(reproduced on my device): 
[adguard.log](https://github.com/AdguardTeam/AdguardForAndroid/files/3734666/adguard.log)

**Comment by admitrevskiy** [comment]
Looks like this app tries to ping some remote server to check if internet connection is available.
This operation is impossible with enabled AdGuard. We should exclude it from filtering at all.

**Comment by admitrevskiy** [comment]
Done.
