### ISSUE TITLE
Draw behind navigation bar

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#3151]
### Problem Description

The navigation bar for AdGuard is a gray that is different from the rest of the app, whether this is in the light or dark theme. It looks out of place.

### Proposed Solution

Make the navigation bar match the rest of the app's either gray or white background. I previously tried to suggest this in https://github.com/AdguardTeam/AdguardForAndroid/issues/2760 but the request was misunderstood and ultimately closed — this isn't a theming issue, really; it's about supporting modern UX and gesture navigation more beautifully.

> The first, and most important consideration for supporting gesture navigation, is drawing behind the navigation bar. Since the navigation bar has shrunk in size and prominence, it is now _strongly_ recommended for apps to draw behind the navigation bar when running on Android Q+ for a more compelling and modern UX.

> When running on devices with Android Pie or below, drawing behind the navigation bar is optional, allowing apps to decide what makes sense. That said, nearly all the necessary APIs work back to API 21 (or AndroidX handles the differences), so the amount of extra work needed to support pre-Q devices is minimal. Users on pre-Q devices also benefit from the more immersive experience. We consider it optional solely to minimize the amount of required work and testing.

https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e

**Comment by artemiv4nov** [comment]
The navaigation bar has already been changed in the v4.0 version, please follow updates
