### ISSUE TITLE
AG wrongly made 2 SDN filters in DNS filtering during update, which caused I can't create a VPN connection if enabling DNS filtering with 2 enabled SDN filters.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3154]
1. I updated to v3.3 nightly 16 (93) from v3.3 nightly 15.
With v3.3 nightly 15, I can create a VPN connection.
But I couldn't create a VPN connection with v3.3 nightly 16 (93).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7kESDvh.jpg)
</details><br/>

So I tried to find the cause.
I found AG wrongly made 2 default SDN filters in DNS filtering during updating to v3.3 nightly 16 (93).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/n5R9LfF.jpg)
</details><br/>

If enabling DNS filtering **with 2 enabled SDN filters**, I can't create a VPN connection .
After disabling one of SDN filters in DNS filtering, I can create a VPN connection.

2. Because AG SDN filter is default filter, I can't remove one of 2 SDN filters.
For solving 2 SDN filters, can I get the solution in the next nightly version?
Or is cleanly installing AG by APK the only way?

**Why did AG wrongly make 2 default SDN filters in DNS filtering during updating app?**
May you fix the bug?

I already sent the log file to devteam@adguard.com at 14:27 on 20th October (GMT+8).
email title: After updating to v3.3 nightly (16), it wrongly made 2 enabled SDN filters in DNS filtering and caused failed VPN connection.
Thanks.

**Comment by ameshkov** [comment]
Logs are in our nextcloud

**Comment by lancelot-moon** [comment]
Maybe this guy on telegram met the same issue (2 default SDN filters), but I don't know if he ever updated app.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/0gd5TGn.png)
</details><br/>

If AG team need my settings file, please contact me on telegram.

**Comment by lancelot-moon** [comment]
I updated to v3.3 nightly 17 (99), but there are still 2 default SDN filters in DNS filtering.

Is cleanly installing AG by APK the only way to solve 2 SDN filters?

Thanks.

**Comment by admitrevskiy** [comment]
@lancelot-moon hi!
Yes, please reinstall AG cleanly to get rid of duplicates.
