### ISSUE TITLE
With v3.3 nightly 15, something wrong in update mechanism.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3155]
I saw the news of v3.3 nightly 16 on telegram.
So I checked for updates via long press shortcut with v3.3 nightly 15.

1. I felt weird why there is no update notification since I checked for updates via long press shortcut.

2. I went to directly open AdGuard app and checked for updates.
I found it showed no updates available, but actually new v3.3 nightly 16 was available.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Wqk27NU.jpg)
</details><br/>

**Comment by artemiv4nov** [comment]
This problem has a connection with #3153.
I closed this task because #3153 already done but if you will have any problems with the next update of nightly version, re-open this task, please.
