### ISSUE TITLE
Add bank apps to exclusion list

### ISSUE THREAD

**Issue by R3gi** [AdguardTeam/AdguardForAndroid#3157]
Hi,
would be please possible to consider adding following bank apps and URLs to exclusion list? Those apps are active finantial apps made by "Česká spořitelna", czech largest bank. Thanks.

URLSs:
- `*.mojezdravefinance.cz`

Apps:
- `cz.csas.georgego`
https://play.google.com/store/apps/details?id=cz.csas.georgego

- `cz.csas.app.georgeklic`
https://play.google.com/store/apps/details?id=cz.csas.app.georgeklic

- `cz.csas.app.friends24`
https://play.google.com/store/apps/details?id=cz.csas.app.friends24

- `cz.csas.app.poketka`
https://play.google.com/store/apps/details?id=cz.csas.app.poketka

- `com.cleverlance.csas.servis24`
https://play.google.com/store/apps/details?id=com.cleverlance.csas.servis24

- `cz.csas.app.mujstav`
https://play.google.com/store/apps/details?id=cz.csas.app.mujstav

- `cz.csas.business24`
https://play.google.com/store/apps/details?id=cz.csas.business24

**Comment by admitrevskiy** [comment]
Done.

**Comment by Chinaski1** [comment]
Please add that one.

>- ru.simpls.mbrd.ui
https://play.google.com/store/apps/details?id=ru.simpls.mbrd.ui.beta&hl=ru>
