### ISSUE TITLE
Network Options to the "DNS filtering" settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3158]
We should let people enable/disable DNS filtering for a given Wi-Fi network or cellular network.

See how it's done in the iOS version for the reference.

**Comment by avbfr** [comment]
+1. This feature would be very very interesting for me.

**Comment by artemiv4nov** [comment]
For now we have huge support for shortcut related applications. You can use our Automation API to resolve your issue.
