### ISSUE TITLE
[Feature request] Add Sleipnir Mobile to browser list

### ISSUE THREAD

**Issue by Mokura** [AdguardTeam/AdguardForAndroid#316]
https://play.google.com/store/apps/details?id=jp.co.fenrir.android.sleipnir
https://play.google.com/store/apps/details?id=jp.co.fenrir.android.sleipnir_test

Possibly Sleipnir Black (https://play.google.com/store/apps/details?id=jp.co.fenrir.android.sleipnir_black) but it's a paid app so I haven't used it.

**Comment by ameshkov** [comment]
Got it, we'll do it.

**Comment by Revertron** [comment]
Done.
