### ISSUE TITLE
PWA won't install when AdGuard is active

### ISSUE THREAD

**Issue by stevenjaycohen** [AdguardTeam/AdguardForAndroid#3160]
1 Android phone without AdGuard
2 Install Twitter or Instagram PWA using Chrome
3 Install AdGuard
4 Uninstall PWA
5 Try to reinstall PWA
*FAIL to reinstall* - will only offer to put shortcut on desktop
6 Turn AdGuard off
7 PWA will install normally after refreshing page

**Comment by ameshkov** [comment]
Could it be that you have the Annoyances filter list enabled?

**Comment by stevenjaycohen** [comment]
I do have Annoyance enabled. So, I suggest that anything suppressing PWA functionality be separated into its own set of filters. Please note that once installed the PWA functions fine with the Annoyance filters. So it is just PWA detection that I am talking about.

**Comment by stevenjaycohen** [comment]
The term Annoyance is subjective. I personally consider the need to install yet another app that may try to grab more permissions than needed an Annoyance that limiting the application to a PWA solves.

I would believe that since PWA usage skews toward a more tech-savvy audience (like AdGuard itself), that a fair number of users would not consider PWA detection an "annoyance".

**Comment by ameshkov** [comment]
Well, we actually ran a survey about this, and about 85% of the users voted for blocking PWA.

On the other hand, you're right that we should split the Annoyances filter into something more granular -- cookie notices, support popups, PWA, etc.

**Comment by stevenjaycohen** [comment]
Thank you for being open to the input. More granularity would be appreciated. And, it would help in troubleshooting site related issues as well.

**Comment by artemiv4nov** [comment]
Reopened to discuss the split of Annoyances filter.

**Comment by stevenjaycohen** [comment]
I don't know if the "popup" saying Install the PWA can be isolated from PWA discovery by the browser (manually going to the menu and choosing to install). But, if they can be done separately, then leaving the popup bit in annoyances and moving the other part to a PWA discovery filter would make sense.
