### ISSUE TITLE
com.appgate.gorealra

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3163]
@adguard-bot commented on [Sat Oct 12 2019](https://github.com/AdguardTeam/AdguardFilters/issues/42222)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.appgate.gorealra](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.appgate.gorealra)
### Comment
> 스플래시 화면에서 넘어가질 않습니다

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/n62PJwl.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Ct85Qfa.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Simplified domain names,<br>AdGuard Base,<br>Korean Adblock List,<br>List-KR,<br>AdGuard Tracking Protection

---

@Alex-302 commented on [Tue Oct 22 2019](https://github.com/AdguardTeam/AdguardFilters/issues/42222#issuecomment-545073206)

It works with `@@||googleads.g.doubleclick.net^$app=com.google.android.gms` only. This rule will unblock ads in another apps.

**Comment by Alex-302** [comment]
Please disable ad blocking for this app, because it cannot be fixed by the rules(see a comment above).

**Comment by ameshkov** [comment]
Well, this is not our problem, it's just this app relies on loading ads for some reason
