### ISSUE TITLE
[Feature request] Add normally-updateable custom filters

### ISSUE THREAD

**Issue by Mokura** [AdguardTeam/AdguardForAndroid#317]
http://fanboy.co.nz/filters.html
When using uBlock0 on desktop and mobile Firefox, I usually use the Fanboy Ultimate List filter, since it blocks most of what I care about in one filter.  I have the ability to import the list into the user filter list, but it manually adds all(?) of the individual lines to the user filter list.  If/when the filter gets updated, I'd have to clear out the entire user filter list and re-import the filter, losing whatever non-import custom rules I had set.  I could keep my own personal custom rules in a file, but it'd be nice to add an arbitrary filter to the updateable list so the app could do the heavy lifting in the background.  In any case, thank you for your work.

**Comment by TPS** [comment]
@Mokura I think what you're after is #13, which is already tagged for the 3.0 milestone.  Else, please clarify difference.

**Comment by Mokura** [comment]
That's exactly it.  Closing this as duplicate.
