### ISSUE TITLE
com.riotgames.mobile.leagueconnect - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3172]
@adguard-bot commented on [Tue Oct 22 2019](https://github.com/AdguardTeam/AdguardFilters/issues/42775)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.riotgames.mobile.leagueconnect](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.riotgames.mobile.leagueconnect)
### Comment
> при включенной защите не подгружается список друзей и сообщения

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/JV5EIWN.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/1nolLbo.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> (Obsolete) Anti-Adblock Killer \| Reek, <br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Simplified domain names<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | других нет

**Comment by Alex-302** [comment]
У меня игра не запускается как следует и без Адгарда, но при запущенном, вот такая ошибка:
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/67506274-6ebdc000-f695-11e9-96ec-77abcf4705d0.png)

 </details>

Отключение фильтров, антитрекинга, фильтрации DNS и блокировки рекламы для приложения не помогают. Т.к. у меня не работает, не понятно, что виновато. Нужно чтоб ещё кто-нибудь проверил.

Отладочный лог:
[log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/3768601/log.txt)

**Comment by artemiv4nov** [comment]
@Alex-302 попробуйте повторить заново:
1) удалите HTTPS сертификат и поставьте заново
2) включите "легировать все"
3) запустите защиту
4) проверьте игру

**Comment by Alex-302** [comment]
Ещё жалоба
https://github.com/AdguardTeam/AdguardFilters/issues/43859

**Comment by Domi52** [comment]
> @Alex-302 попробуйте повторить заново:
> 
> 1. удалите HTTPS сертификат и поставьте заново
> 2. включите "легировать все"
> 3. запустите защиту
> 4. проверьте игру

cделал это, но все равно не работает

**Comment by Alex-302** [comment]
@Domi52 пятый пункт пропустили - экспорт и отправку лога)
Здесь описано как его экспортировать
https://kb.adguard.com/ru/android/solving-problems/log
Повторите пункты выше, и загрузите лог сюда, с указанием времени запуска игры.

**Comment by Domi52** [comment]
> @Domi52 пятый пункт пропустили - экспорт и отправку лога)
> Здесь описано как его экспортировать
> https://kb.adguard.com/ru/android/solving-problems/log
> Повторите пункты выше, и загрузите лог сюда, с указанием времени запуска игры.
> Экспорт - после повторения проблемы.

[adguard_logs_3.2.150_2711_095634.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3895501/adguard_logs_3.2.150_2711_095634.zip)

**Comment by admitrevskiy** [comment]
@Domi52 подскажите пожалуйста, на последней найтли повторяется?

**Comment by Domi52** [comment]
> @Domi52 подскажите пожалуйста, на последней найтли повторяется?

на первый взгляд всё ок

**Comment by admitrevskiy** [comment]
> на первый взгляд всё ок

Отлично! Если вдруг возникнут проблемы - напишите пожалуйста.

**Comment by Domi52** [comment]
> > на первый взгляд всё ок
> 
> Отлично! Если вдруг возникнут проблемы - напишите пожалуйста.
с чатами и списком друзей, вроде норм, а вот сверху вместо "инициализации" должен быть ник и статус
![IMG_20191205_172708](https://user-images.githubusercontent.com/14108393/70296370-7a0b1c00-17fb-11ea-84b8-5a065d46da90.jpg)

**Comment by admitrevskiy** [comment]
@Domi52 
А с выключенным AG наблюдается такое поведение? В моем случае включение-выключение фильтрации никак не влияет на проблему с инициализацией аккаунта, грузит долго в любом случае.

**Comment by artemiv4nov** [comment]
Закрываю задачу. Она может быть переоткрыта, если баг с приложением снова появится.
