### ISSUE TITLE
AG_onLoad function doesn't work on Android

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#3173]
### Issue Details

- **AdGuard version:**
  -  v3.3 nightly 18 (104)
- **Filtering mode:**
  - VPN
- **Device:**
  - Samsung Galaxy S9+
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Steps to reproduce
1. Add this rule to user filter:
`example.org#%#AG_onLoad(function() { alert(1); });`
2. Go here - http://example.org/

### Expected Behavior
There should be an alert.

### Actual Behavior
It seems that for some reason `AG_onLoad` function doesn't work.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/67571904-61f0a900-f735-11e9-8a3e-6c236f81531b.png)

</details>

### Additional Information
There is no problem with this rule with AdGuard for Windows

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1172](https://github.com/AdguardTeam/CoreLibs/issues/1172) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1173](https://github.com/AdguardTeam/CoreLibs/issues/1173) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1174](https://github.com/AdguardTeam/CoreLibs/issues/1174) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
It appears that it can be an Android-specific issue.

Reopened, raised the priority to P1: Critical

**Comment by artemiv4nov** [comment]
Approved: that's the corelibs-related problem, will be fixed in the next nightly
