### ISSUE TITLE
Incorrect translation in DNS filtering section

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3174]
Incorrect string translation in DNS filtering section (see attachments).

<details>

![image](https://user-images.githubusercontent.com/37797229/67660285-820bac80-f96f-11e9-9f89-c984f86b159e.png)

</details>

**Comment by artemiv4nov** [comment]
@admitrevskiy we can use phrase with id "system_dns_name"

**Comment by admitrevskiy** [comment]
Done.
