### ISSUE TITLE
Add the app to the exception list

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3177]
Please, add a com.bn.addedinfluence package to the exception list due of app won't work with enabled AdGuard.

[Google Play](https://play.google.com/store/apps/details?id=com.bn.addedinfluence)

**Comment by artemiv4nov** [comment]
@TheHasagi What exception list do you want to add the app's package name?

**Comment by TheHasagi** [comment]
I want you to add this application to the filtering exception list.

**Comment by TheHasagi** [comment]
The issue depends on branch.io domain. To avoid inconveniences with this app api2.branch.io should be excluded from filtering.
