### ISSUE TITLE
Add Indian Filter

### ISSUE THREAD

**Issue by pidus** [AdguardTeam/AdguardForAndroid#3178]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer

### Problem Description
AdGuard has plenty of language specific filter lists to choose. But, an Indian list is not present. This list can be found in the Fanboy's website's regional section: https://www.fanboy.co.nz/regional.html
Direct link to the list: https://www.fanboy.co.nz/fanboy-indian.txt

### Proposed Solution
Add the Indian filter list to the language-specific filters section.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #250](https://github.com/AdguardTeam/FiltersRegistry/issues/250) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Moved to correct section.
