### ISSUE TITLE
tv.fanserials.mobile

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3179]
@adguard-bot commented on [Sun Oct 27 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43064)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=tv.fanserials.mobile](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dtv.fanserials.mobile)
### Comment
Username: @e-shl
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/83TzLJj.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/eSt6Lu1.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> RU AdList, <br/>RU AdList: Counters, <br/>AdGuard Russian

**Comment by Alex-302** [comment]
Not reproduced on my device.

**Comment by TheHasagi** [comment]
Not reproduced on my device with the same configuration. The app working as well, you can log in or watch the video directly. User should check the internet connection, internet access for this app and DNS settings.

**Comment by TheHasagi** [comment]
@e-shl 

Can you turn off the ESET and check again? Also, for the best experience please, download the [latest beta version](https://agrd.io/apkb) and collect the log files with the reproduced issue regarding this [article](https://kb.adguard.com/en/android/solving-problems/log).

**Comment by e-shl** [comment]
@TheHasagi stable version
![Screenshot_20191101-203352](https://user-images.githubusercontent.com/35057681/68036412-6c87e100-fce7-11e9-93ab-e600c67343eb.jpg)
![Screenshot_20191101-203402](https://user-images.githubusercontent.com/35057681/68036413-6c87e100-fce7-11e9-94c3-2c4e395f25ba.jpg)
![Uploading Screenshot_20191101-203527.jpg…]()

**Comment by TheHasagi** [comment]
@e-shl 

Please, follow the steps I asked above.

**Comment by e-shl** [comment]
@TheHasagi 
[adguard_logs_3.3.102_0111_205332.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3798586/adguard_logs_3.3.102_0111_205332.zip)
somehow loaded
![Screenshot_20191101-205709](https://user-images.githubusercontent.com/35057681/68037780-47e13880-fcea-11e9-9840-c6af0728ceb8.jpg)
and again no
![Screenshot_20191101-205933](https://user-images.githubusercontent.com/35057681/68037901-9393e200-fcea-11e9-94da-c029e772129a.jpg)

**Comment by e-shl** [comment]
@TheHasagi Another one
[adguard_logs_3.3.102_0111_210153.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3798611/adguard_logs_3.3.102_0111_210153.zip)

**Comment by e-shl** [comment]
@TheHasagi https://yadi.sk/d/3SZEGRq5AEGlcA

**Comment by TheHasagi** [comment]
@e-shl 

And if you try to switch to another DNS resolver or switch it off?

**Comment by e-shl** [comment]
@TheHasagi the only thing used was related to dns

**Comment by TheHasagi** [comment]
@e-shl 

I meant in AdGuard - Settings - DNS Filtering :)

**Comment by e-shl** [comment]
@Alex-302 I didn’t turn it on, but turning it on doesn’t help

**Comment by e-shl** [comment]
@TheHasagi disabling all advertising filters did not help either. only complete shutdown of the adhuard or disabling https filtering
<details>

![Screenshot_20191105-183546](https://user-images.githubusercontent.com/35057681/68212367-36a26f80-fffb-11e9-9524-6bf3b08ab281.jpg)

</details>

**Comment by TheHasagi** [comment]
@e-shl 

Hello! 

Can you try one more time with the latest [Nightly build](https://agrd.io/android_nightly)?

Also, if the problem still happens, follow these steps:

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.
