### ISSUE TITLE
Fix the text of notification and dialog on the Whitelist Activity

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3182]
When you exporting the whitelist there should be a correct wording:

Expected behavior:

"Белый список был успешно экспортирован"

Actual behaviour:

<details>

![image](https://user-images.githubusercontent.com/37797229/67945596-5b0fdd80-fbf0-11e9-90a6-a40a91e4fdd2.png)

</details>

The same with deletion function, it should notify the user about a domain, not the rule:

<details>

![image](https://user-images.githubusercontent.com/37797229/67947269-61a05400-fbf4-11e9-80a0-c12a1b12b3a0.png)

</details>

**Comment by admitrevskiy** [comment]
Done.
