### ISSUE TITLE
Fix the notification toast (License expired)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3183]
When the license is expired there is a wrong toast notification.

Expected behavior:

There should be a notification that license is expired and should be prolonged.

Actual behaviour:

<details>

![image](https://user-images.githubusercontent.com/37797229/67949768-5d2a6a00-fbf9-11e9-8a1a-43f1f5f34c35.png)
![image](https://user-images.githubusercontent.com/37797229/67949772-61ef1e00-fbf9-11e9-8753-6518de657acc.png)

</details>

**Comment by Revertron** [comment]
Fixed.
