### ISSUE TITLE
Wrong name adblockID filter

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdguardForAndroid#3184]
https://photos.app.goo.gl/JzA3HSpnynJ8gLBX9

**Comment by Alex-302** [comment]
@slavaleleka please check why old filter name was sent from app
https://github.com/AdguardTeam/AdguardFilters/issues/43277

**Comment by artemiv4nov** [comment]
@Alex-302 What is the point of this task?

**Comment by slavaleleka** [comment]
@3xploiton3 it has been fixed now, you may check

**Comment by 3xploiton3** [comment]
Solved, thx

**Comment by 3xploiton3** [comment]
> 
> 
> @3xploiton3 it has been fixed now, you may check

please check in adguard windows
![](https://i.imgur.com/4hnu7t9.png)

**Comment by 3xploiton3** [comment]
@slavaleleka

**Comment by Alex-302** [comment]
Please remove that filter and add it again
![image](https://user-images.githubusercontent.com/8361299/69009796-c7653d80-0961-11ea-84ce-5aed6e8329ca.png)
