### ISSUE TITLE
com.google.android.apps.searchlite - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3185]
@adguard-bot commented on [Mon Oct 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43097)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.google.android.apps.searchlite](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.searchlite)
### Comment
Username: @3xploiton3
>  can't read my voice

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/JHZUUfA.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/gjq3rKS.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block WebRTC, Hide your User-Agent ()
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>EasyList, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> Web Annoyances Ultralist, <br/>AdGuard Annoyances, <br/>I don't care about cookies, <br/>Fanboy's Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> (Obsolete) Norsk adblockliste, <br/>ABPindo

---

@Alex-302 commented on [Wed Oct 30 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43097#issuecomment-547947053)

@3xploiton3 Hi. I can't reproduce. Could you please record debug logs?
https://kb.adguard.com/en/android/solving-problems/log#debug
And sent them to support@adguard.com with the link of this issue.

---

@3xploiton3 commented on [Wed Oct 30 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43097#issuecomment-547956252)

Ok, It has been sent

---

@Alex-302 commented on [Thu Oct 31 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43097#issuecomment-548489456)

Cannot find a reason. Moved to AG for Android repository.

**Comment by Alex-302** [comment]
Not reproduced on my device.

**Comment by zzebrum** [comment]
logs are in ncloud
