### ISSUE TITLE
adguard causing problem in pushover and advanced download manager (adm) apps

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#3189]
have you changed anything (today)?

I've noticed pushover and advanced download manager (adm) apps don't work
when the traffic is passed through adguard,

pushover fills me with "could not connect" messages (even though I'm receiving notifications) and
adm cannot detect if the link I sent to it needs to be opened in internal browser

Nothing is recorded in filtering log, even when I turned on the option to record everything

[adguard_logs_3.3.114_0511_141709.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3808960/adguard_logs_3.3.114_0511_141709.zip)

and as I said the issue started happening today

disabling adblocking for those 2 apps doesn't make them work either,
I have to completey disable traffic through adguard for them in order for them to work,

please check and fix

**Comment by TheHasagi** [comment]
@patrickdrd 

Check for user filter and DNS (try to switch to another one or disable it), looks legit for me.

**Comment by patrickdrd** [comment]
I disabled my dns and nothing..

**Comment by patrickdrd** [comment]
got it: something you added in (your) mobile ads filter is causing the issue,
at least the pushover one,
as for the other one, I'm passing a 4pda.ru link and
even though I have disabled everything, 
detection that the link needs to be opened in browser doesn't work!

**Comment by patrickdrd** [comment]
well, I disabled all filters and I still couldn't manage to make either of the above work
(on the adm issue, I'm waiting for adm to detect that the url passed to it is a web page and
prompt me to open it in a browser)

**Comment by patrickdrd** [comment]
got it!
the "disable vpn pause" in low level settings is causing such issues

**Comment by TheHasagi** [comment]
@patrickdrd 

Did you manage it manually? Is this issue happens on default settings?

**Comment by patrickdrd** [comment]
I thought about changing the "disable vpn pause" setting in low level settings a couple of days ago and
the very next day I had the two problems mentioned in this issue,
I re-enabled it yesterday and everything is fine since then
