### ISSUE TITLE
Add "Change filtering type" quick action

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3190]
### Problem Description

Users who often switch from Local VPN to Local HTTP Proxy find it quite annoying to constantly go to AdGuard settings to change filtering mode.

### Proposed Solution

Add a quick action to switch filtering mode.

### Alternatives Considered

Use widget instead of quick action.

### Additional Information

Reported by user 1272889

**Comment by artemiv4nov** [comment]
I don't think that's a relevant idea, I will close the task
