### ISSUE TITLE
Please add and use zh-HK locale in all of AG products' next version.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3191]
AG team uses zh-TW (Chinese Traditional, Taiwan) language file for not only Taiwan but also Hong Kong and Macau (apps or introduction on Google Play/Chrome web store/App Store/official website...etc.) due to the convenience.

Since zh-HK (Chinese Traditional, Hong Kong) locale was added on Crowdin, please add and use zh-HK locale in all of AG products' next version and the official website for Hong Kong by default.
ex: For AG for Android, zh-HK can be used by default from v3.3 for Hong Kong.

**Comment by Revertron** [comment]
But I don't see any translation for zh-HK in Crowdin:
https://up.agrd.eu/Pc9OPP.png

**Comment by lancelot-moon** [comment]
@Revertron 
Hi,
That's HK translators' responsibility since they asked AG team to add zh-HK locale.

HK users can still manually choose zh-TW in the languages selection if they wish.
But it's much better to set zh-HK for Hong Kong by default.
From the beginning, "TW" of zh-TW means Taiwan, not Hong Kong.

We should respect Hong Kong people and give them zh-HK by default.

**Comment by artemiv4nov** [comment]
@lancelot-moon
Hi,
My teammate meant that until the translation into the language appears in the Crowdin service, we will not add it to the application.

Please add the translation for this locale.

**Comment by artemiv4nov** [comment]
@lancelot-moon 
After you add the translation, you have to approve all new translations, also.

**Comment by lancelot-moon** [comment]
@artemiv4nov
zh-HK proofreader isn't me.
It's not my responsibility.

I just think zh-TW and zh-HK are different locales.
So zh-TW is much better not for Hong Kong by default.
It's up to you.

**Comment by artemiv4nov** [comment]
@lancelot-moon
So I see, thanks!
When translations become available on Crowdin, we will immediately add support for the new locale to please our users.
