### ISSUE TITLE
Wrong state of update result (Updates section)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3195]
Screenshot # 1 - Internet is limited for a whole network

<details>

![image](https://user-images.githubusercontent.com/37797229/68336674-ef49db00-00ef-11ea-9ef6-4961fc5e961b.png)

</details>

Screenshot # 2 - Internet is unavailable

<details>

![image](https://user-images.githubusercontent.com/37797229/68336663-e9ec9080-00ef-11ea-9d17-4eb826e6c34d.png)

</details>

**Comment by artemiv4nov** [comment]
So, we have to improve the updates checking, throwing connection error processing to the place where the check occurs.

**Comment by admitrevskiy** [comment]
Done.
