### ISSUE TITLE
Group edit whitelist/blacklist entries

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3198]
### Problem Description

It is not currently possible to remove / disable multiple Blacklist / Whitelist features. In addition, confirmation dialog pops up for EACH operation like this.

### Proposed Solution

Add group selection feature for Blacklist / Whitelist.

### Alternatives Considered

null
### Additional Information

Reported by user 709698.

**Comment by ameshkov** [comment]
This is exactly why we made "edit mode" (menu -> edit filter)
