### ISSUE TITLE
Unable to update previously open page in browser

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3199]
### Issue Details

- **AdGuard version:**
  - 3.2.140, 3.2.150, 3.3.5 and further nightlies
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Honor 10 Lite
- **Operating system and version:**
  - Android 9
- **Root access:**
  - none
- **Environment:**
  - AdGuard + Yandex Browser

### Expected Behavior

Updating saved pages in browser should be without issues.

### Actual Behavior

When AdGuard is enabled, user is unable to refresh a previously saved page.

### Screenshots

<details><summary>Screen recording:</summary>

[SVID_20190917_130442_1.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828187/SVID_20190917_130442_1.zip)

</details>

### Debug logs

<details><summary>Initial report</summary>

[adguard_logs_3.2.140_3108_125715 (время 12;54-12;55).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828189/adguard_logs_3.2.140_3108_125715.12.54-12.55.zip)

[bugreport-HRY-LX1RU-HONORHRY-L21-2019-08-31-13-02-23.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828190/bugreport-HRY-LX1RU-HONORHRY-L21-2019-08-31-13-02-23.zip)

</details>

<details><summary>Nightly (older builds)</summary>

[bugreport-HRY-LX1RU-HONORHRY-L21-2019-09-07-19-44-00.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828193/bugreport-HRY-LX1RU-HONORHRY-L21-2019-09-07-19-44-00.zip)
[adguard_logs_3.3.5_0709_194113.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828194/adguard_logs_3.3.5_0709_194113.zip)

</details>

<details><summary>Latest available logs</summary>

[bugreport-HRY-LX1RU-HONORHRY-L21-2019-09-17-13-07-16.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828196/bugreport-HRY-LX1RU-HONORHRY-L21-2019-09-17-13-07-16.zip)
[Файл-2 время 13;05 adguard_logs_3.2.150_1709_130558.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828197/-2.13.05.adguard_logs_3.2.150_1709_130558.zip)
[Файл-1 время 11;28 adguard_logs_3.2.150_1709_122839.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3828198/-1.11.28.adguard_logs_3.2.150_1709_122839.zip)

</details>

### Additional Information

Reported by: 1129255

**Comment by admitrevskiy** [comment]
I found that every time before the problem occurred, the browser would send a request to `storage.ape.yandex.net/get/browser/experiments-mobile`.
However `||storage.ape.yandex.net^` filtering rule did not solve the issue. We're still looking for a solution.

**Comment by artemiv4nov** [comment]
@admitrevskiy according to the user, everything worked on the last nighty version using the rule
