### ISSUE TITLE
Feature request: modify user agent on certain website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#32]
http://forum.adguard.com/showthread.php?6677-Function-to-modify-user-agent-on-certain-website

**Comment by TPS** [comment]
:+1: Fantastic idea!  On a related note, does AdGuard announce itself via useragent, because adding an option with this enhancement to toggle that would be good.

**Comment by Revertron** [comment]
>> does AdGuard announce itself via useragent
For what purpose?

**Comment by TPS** [comment]
I don't know! Many proxy-types do, & I always turn such off whenever possible.

**Comment by ameshkov** [comment]
Additional info:

Yes, this is the site i know use this method:
www.corriere.it (2 euro every week)
www.repubblica.it (2,99 euro every week)

Repubblica.it redirect to m.repubblica.it

This is the condition of
Corriere.it
http://www.corriere.it/inapp/condition.shtml

**Comment by ameshkov** [comment]
Honestly, I don't like the idea of customizing it on **per-site basis**.
It is too hard for such specific task.

I am thinking about one setting for all websites.

**Comment by TPS** [comment]
That makes it **much** less useful; OTOH, I do understand how difficult it is (e.g., problems like, how does 1 consistent useragent apply for all 3rd-party assets *in* a page, & how does 1 handle 1 site in list, another not, but both of which include asset from same 3rd-party site).

**Comment by ameshkov** [comment]
Dup of a CL task
