### ISSUE TITLE
Display appids in Apps Management menu

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3200]
### Problem Description

Advanced users are unable to find an app through Apps Management menu using application IDs.

### Proposed Solution

Display application IDs under app names using smaller font.

### Alternatives Considered

Display application IDs under each individual app's submenu + make appIDs searchable.

### Additional Information

reported by 2377037

**Comment by ameshkov** [comment]
Do you mean package names?

Here's where you can find them:
Menu -> Technical information

**Comment by akmLaVx** [comment]
Yes, and the user thinks it would be great if we could search apps in Apps Management menu by their package name. At the very least, we could add a setting to display package names next to human-readable names.

**Comment by ameshkov** [comment]
Package names are already searchable.

Also, I don't really like the idea of displaying them, most of the users just don't need them, and there's not too much free space screen.
