### ISSUE TITLE
Cannot import settings due to the file size

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3203]
### Issue Details

- **AdGuard version:**
  -  3.3.20(129-1.5.109cl)

### Actual Behavior
Importing settings will not work if the file size exceeds 4 megabytes.

### Additional Information

Uploaded a Configuration file to NCloud for example

**Comment by admitrevskiy** [comment]
Done. Limit size has been increased to 10 Mb
