### ISSUE TITLE
com.pelmorex.WeatherEyeAndroid

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#3204]
@adguard-bot commented on [Mon Nov 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43855)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.pelmorex.WeatherEyeAndroid&hl=en_US](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.pelmorex.WeatherEyeAndroid%26hl%3Den_US)
### Comment
Username: @darkmage87
> The Android app "The Weather Network" is not working properly with Adguard, I have to completely disable protection to use the app or it wont load the weather information and gives connection errors. Even giving it full exception on the Adguard firewall it still doesn't work properly.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/8SpjNiP.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ubWvnpB.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Spam404, <br/>NoCoin Filter List, <br/>Malware Domains Blocklist<br/><br/><b>Language-specific:</b><br/> AdGuard Japanese
Other extensions used: | Kaspersky Internet Security

---

@BlazDT commented on [Mon Nov 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43855#issuecomment-552307767)

When HTTPS filtering is disabled for the app, I can get the temperatures etc, just the bottom error is still there (
When adblocking is disabled fully, it works without that error even though nothing is blocked.

@AdamWr an idea how to fix that message without fully disabling filtering for the app?

---

@Alex-302 commented on [Mon Nov 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43855#issuecomment-552445180)

@BlazDT move to https://github.com/AdguardTeam/AdguardForAndroid + debug logs.

**Comment by BlazDT** [comment]
[adguard_logs_3.3.129_1211_105228.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3835448/adguard_logs_3.3.129_1211_105228.zip)

Log with everything recorded attached.

**Comment by admitrevskiy** [comment]
Looks like the latest version of `com.pelmorex.WeatherEyeAndroid` has no issues with bottom error but our certificate is not acceptable for all connections of this app. It should be added to the HTTPS exclusions list.
