### ISSUE TITLE
com.x8bit.bitwarden - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3206]
@adguard-bot commented on [Thu Nov 07 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43695)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.x8bit.bitwarden](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.x8bit.bitwarden)
### Comment
Username: @bkrucarci
> The application does not allow taking screenshots in the app sonI have tonadd these to pass the submission process. When I enabled AdGuard; the Bitwarden Password Manager cannot syncronize the passwords. Please solve this.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/BHPv4kZ.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vNerG3N.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 3.3 beta 2 (102)
Stealth mode options: | Strip URLs from tracking parameters, Self-destructing third-party cookies (0)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish

---

@Alex-302 commented on [Fri Nov 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43695#issuecomment-551839079)

@bkrucarci Hi. Could you please chech with disabled filters and dns filtering(DNS - google or another not-AdGuard)

---

@zloyden commented on [Fri Nov 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43695#issuecomment-551841122)

Not reproduced on my end.

---

@krystian3w commented on [Fri Nov 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43695#issuecomment-551843346)

Also no have Troubles with DoH AdGuard DNS version.

**Comment by Alex-302** [comment]
Not reproduced on my device, but this is a password manager. Maybe it can be excluded.

**Comment by Revertron** [comment]
I couldn't reproduce the issue. But I think, that this app may use certificate pinning for some of its connections.
I've added it to HTTPS-exclusions.
