### ISSUE TITLE
Некорректный перевод количества обновлённых фильтров

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForAndroid#3209]
### Prerequisites

- **AdGuard version:**
  -  3.2.150
- **Filtering mode:**
  -  HTTP Proxy (Auto)
- **Device:**
  -  OnePlus 3
- **Operating system and version:**
  -  Android 9
- **Root access:**
  -  Yes

### Expected Behavior

Отображается «4 фильтра обновлено».

### Actual Behavior

Сейчас отображается «4 фильтров обновлено».

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_AdGuard_20191113-165127](https://user-images.githubusercontent.com/19418601/68886483-5a1a9800-0728-11ea-8aeb-3064a6769e6d.png)

</details>

**Comment by aalpatkina** [comment]
Перевод обновлен в Crowdin. Спасибо!
Обновим локализацию со следующим релизом.
