### ISSUE TITLE
IP Cam Viewer Pro stream blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#321]
https://play.google.com/store/apps/details?id=com.rcreations.WebCamViewerPaid

The video stream from this camera is blocked when accessed from its external internet IP address (either numeric or via its duckdns proxy name). Accessed via its intranet IP address it is not blocked.

Disabling ad blocking in Firewall helped.

Logs here - DLI-998-60164

**Comment by ameshkov** [comment]
I suppose we should simply add this app to exceptions

**Comment by Revertron** [comment]
Done.
