### ISSUE TITLE
AdGuard 3.3.102 beta keeps on crashing if Ultra battery saver is enabled once on MIUI 11 and then disabled

### ISSUE THREAD

**Issue by sanjayen** [AdguardTeam/AdguardForAndroid#3210]
I was running out of battery when traveling and hence enabled Ultra battery saver mode in MIUI 11 v9.10.10 beta on my Xiaomi Mi5. Once I disabled the battery saver mode, AdGuard does not open at all and crashes all time. I have been using the beta version of AdGuard for a long time and keep on updating as and when a new version is available and also run the beta version of Xiaomi.eu ROM.

Here are my app details along with screenshots of the generated bug report.
AdGuard version: 3.3.102 beta
Filtering mode: Local VPN
Device: Xiaomi Mi5
Operating system and version: Android 8.0.0/ MIUI 11 by xiaomi.eu 9.10.10 beta
Root access: Yes using Magisk

Expected Behavior
Once ultra battery saver is disabled, AdGuard should work as expected. All optimizations have been disabled for AdGuard and all permissions have been always provided.

Actual Behavior
AdGuard crashes every single time even after a restart. I even cleared Dalvik and app cache but with no luck. I even reinstalled the same beta (which is the latest) on top of the existing installation but the crashes continues.

Screenshots
Attaching a screenshot of what Ultra battery saver mode does along with 2 screenshots of a long scrolling window of the bug report which gets generated once AdGuard crashes.

![MIUI 11-Ultra-battery-saver](https://user-images.githubusercontent.com/4888991/68917792-b353ed00-0763-11ea-9f65-a062ffc03a5d.jpg)
![AdGuard-error-stack-1](https://user-images.githubusercontent.com/4888991/68917796-b64edd80-0763-11ea-98d2-a475bd24c4aa.jpg)
![AdGuard-error-stack-2](https://user-images.githubusercontent.com/4888991/68917800-ba7afb00-0763-11ea-8936-68c9e968d857.jpg)

Please let me know if any other information is required. I do not want to completely uninstall AdGuard and start from scratch as I did not make a backup of my settings.

**Comment by artemiv4nov** [comment]
@sanjayen This error looks like you use Crack version of `AdGuard for Android`.

**Comment by sanjayen** [comment]
> 
> 
> @sanjayen This error looks like you use Crack version of `AdGuard for Android`.

Nope I have a lifetime licenses which I have purchased twice. What do I share to indicate that my licenses are valid? I have logged into my AdGuard account and can see my two purchases as valid.

**Comment by sanjayen** [comment]
Sharing a redacted screenshot of my AdGuard account.

![AdGuard-account](https://user-images.githubusercontent.com/4888991/68942330-41e65f80-07a0-11ea-996e-c442b1db7ab0.png)

**Comment by ameshkov** [comment]
@artemiv4nov the filters state might be corrupted -- one of the filter lists has invalid groupId). The question is what happened and why it has happened.

On our side, we can avoid this crash by making `FilterGroup.findByCode` never return `null`.

@sanjayen I think reinstalling the app will fix this issue.

**Comment by sanjayen** [comment]
@ameshkov I did reinstall and it did not work. Though I have **not** done a complete uninstall and reinstall.

Just to reiterate, the problem occurred when I enabled Ultra battery saver and disabled it when I started charging. I have used Ultra battery saver in the past but not with this new beta version.

**Comment by sanjayen** [comment]
@ameshkov any steps on how to backup the settings and user filters before I uninstall completely? I have added multiple filters based on my navigation needs and sadly did not take a backup.

**Comment by ameshkov** [comment]
@sanjayen could you please export your settings and them to `devteam@adguard.com`?
Please mention this issue in the email.

Also, instead of uninstalling, you can simply clear the app data in the Android settings.

**Comment by sanjayen** [comment]
@ameshkov how do I export the settings as the app does not open at all.

Ok will do that as well and revert.

**Comment by sanjayen** [comment]
@ameshkov have emailed my settings file to the provided address. Hope you solve this issue.

**Comment by ameshkov** [comment]
@sanjayen did it help to clear the app data?

**Comment by artemiv4nov** [comment]
@ameshkov @sanjayen
The error places in other code.
Today we'll roll out the new nightly with the fix for this bug.

**Comment by sanjayen** [comment]
> 
> 
> @sanjayen did it help to clear the app data?

yes, however I lost all my settings and user filters. Sadly also lost the blocking history. I had close to 15GB which had been blocked by AdGuard.

**Comment by TheHasagi** [comment]
@sanjayen 

Can you confirm that the issue is still exists with the latest [Nightly](https://agrd.io/android_nightly) version?

**Comment by sanjayen** [comment]
@TheHasagi I have installed the latest version 3.3 nightly 23 (150)

I shall try and replicate the same ultra battery saver scenario sometime later today and check.

Do give me a day to reply back.

**Comment by sanjayen** [comment]
@TheHasagi I tried replicating the ultra battery saver scenario twice yesterday and both times when I started charging, AdGuard opened and worked as expected. I will keep an eye out for any other scenario but for this moment I will close this ticket. Thank you for solving the issue.
