### ISSUE TITLE
HTTP Proxy http address bug

### ISSUE THREAD

**Issue by ilanyu** [AdguardTeam/AdguardForAndroid#3213]
### Issue Details

- **AdGuard version:**
  - ALL
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 3 XL
- **Operating system and version:**
  - Android 7.1.2
- **Root access:**
  - Yes

My network must set http proxy to connect some website.

When I set the http proxy on adguard, I can't connect any http website.

I test the http proxy server by the code:

```
package main

import (
	"encoding/base64"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"net/url"
)

func main() {
	u := url.URL{}
	parse, err := u.Parse("http://101.71.140.5:8128")
	if err != nil {
		panic(err)
	}

	auth := "uc10.148.245.194:1f47d3ef53b035443451c7ee7873ff38"
	basicAuth := "Basic " + base64.StdEncoding.EncodeToString([]byte(auth))
	hdr := http.Header{}
	hdr.Add("Proxy-Authorization", basicAuth)

	client := http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyURL(parse),
			ProxyConnectHeader: hdr,
		},
	}

	request, err := http.NewRequest("GET", "http://ifconfig.co/", nil)
	if err != nil {
		log.Println(err)
	}

	request.Header.Add("Proxy-Authorization", basicAuth)

	get, err := client.Do(request)
	if err != nil {
		panic(err)
	}
	all, err := ioutil.ReadAll(get.Body)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(all))
}

```
and the http proxy server is working.

then, I am use tcpdump and wireshark to analysis the http package data.

the code send like follow data to 101.71.140.5:8128:

```
GET http://ifconfig.co/ HTTP/1.1
Host: ifconfig.co
User-Agent: Go-http-client/1.1
Proxy-Authorization: Basic dWMxMC4xNDguMjQ1LjE5NDoxZjQ3ZDNlZjUzYjAzNTQ0MzQ1MWM3ZWU3ODczZmYzOA==

```

and adguard send like follow data to 101.71.140.5:8128:

```
CONNECT 104.28.18.94:80 HTTP/1.1
Host: 104.28.18.94
Proxy-Authorization: Basic dWMxMC4xNDguMjQ1LjE5NDoxZjQ3ZDNlZjUzYjAzNTQ0MzQ1MWM3ZWU3ODczZmYzOA==
```

the http proxy server just support connect 443 port by `CONNECT` method, so adguard can't connect any http website.

so,the adguard can send GET, POST and so on method to http website, and send CONNECT method to https website when using http proxy server?

![p1](https://user-images.githubusercontent.com/9317609/68961623-c4593880-080d-11ea-8959-538e69df674d.jpg)

**Comment by TheHasagi** [comment]
@ilanyu 
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by ameshkov** [comment]
@ilanyu yeah, this is a limitation of the current proxy implementation in AdGuard.

It can only use it with HTTP CONNECT requests, not GET/SET. This approach is compatible with most of the popular HTTP proxy implementations (squid for instance).
