### ISSUE TITLE
Add a "Data Bank" feature to AdGuard firewall

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3215]
### Problem Description

Users can easily use up their monthly data plan by using their apps as intended.

### Proposed Solution

Add a feature that would block all apps from using mobile data once user spends a user-specified amount of data.

### Alternatives Considered

None

### Additional Information

Reported by user 2276804

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
