### ISSUE TITLE
Adguard Extra is automatically enabled when it is updated

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3216]
### Issue Details

- **AdGuard version:**
  -  3.3.141
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Sony H4113
- **Operating system and version:**
  -  Android 9

### Steps to reproduce

1. AdGuard Extra is disabled.
2. Manually check for updates.
3. If AdGuard Extra update is available it will be turned automatically after the update.

### Additional Information
User HelpDesk ID: **1764241**

**Comment by admitrevskiy** [comment]
Done.
