### ISSUE TITLE
Add the Send Feedback tab to the quick access panel.

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3217]
Users often send a report to filter developers. Therefore, they need a Feedback button on the quick access panel for convenience.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/69054534-d78e2300-0a1c-11ea-9ab4-a9b80215739a.png)

</details>

**Comment by 3xploiton3** [comment]
Any update?

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3378
