### ISSUE TITLE
DNS not working

### ISSUE THREAD

**Issue by hkkp** [AdguardTeam/AdguardForAndroid#3219]
If I change the DNS to Custom in Android Pie and disable it in Adguard, then it works. I also activate it in Adguard and enable use system, then the default value is taken from the provider and not the set custom value.

**Comment by TheHasagi** [comment]
@hkkp 

Hello!

This is an issue of Android 9 if you want to use Private DNS you should disable DNS filtering in AdGuard (basically, AdGuard DNS filtering  overrides the records and has major priority than Private DNS in Android 9)
