### ISSUE TITLE
Orbot does not stop when AdGuard protection turned off

### ISSUE THREAD

**Issue by Ultrabenosaurus** [AdguardTeam/AdguardForAndroid#3220]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

If I turn on AdGuard with the Tor via Orbot SOCKS5 proxy then Orbot will automatically launch, connect, and integrate with AdGuard filtering in the background. 

Turning off AdGuard or disabling proxy will work as far as AdGuard is concerned, but the Orbot process and proxy are still enabled. You have to manually open Orbot, stop the proxy, and exit the app every time. 

- **AdGuard version:**
  - 3.2.150 (1.4.138cl)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Note 8
- **Operating system and version:**
  - Android 9 with October 2019 security patch
- **Root access:**
  - No

### Expected Behavior

Turning off AdGuard should reverse all actions taken when it was enabled. This includes stopping the AdGuard VPN itself but also anything else it does during activation, such as disconnecting and closing Orbot. 

### Actual Behavior

The AdGuard VPN stops but Orbot stays running and active in the background. 

### Screenshots

https://www.youtube.com/watch?v=wIS8ESW2_Ho

(video not screenshot)

### Additional Information 

I have activated the premium features of the app via a lifetime license bought through my AdGuard account on the website.

**Comment by artemiv4nov** [comment]
@Ultrabenosaurus
It seems like Orbot doesn't have any receivers to stop it from another application.
I suggest waiting some time to research the issue deeply.

**Comment by artemiv4nov** [comment]
In the 4.0 version, we re-worked Orbot integration. Please try use it.
