### ISSUE TITLE
Add banking app to the exclusions

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3222]
Please, add this banking application to the exclusion list:

Package name:com.finanteq.finance.bgz
[Google Play link](https://play.google.com/store/apps/details?id=com.finanteq.finance.bgz&hl=pl)

**Comment by admitrevskiy** [comment]
Done.

**Comment by Nzzyme** [comment]
I am curious to know more about such kind of requests. Is it just just a particular domain getting whitelisted or the entire app?

**Comment by 3xploiton3** [comment]
Add this
https://play.google.com/store/apps/details?id=id.flip
