### ISSUE TITLE
dnsproxy stderr cannot be included into the automatic crash report

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3223]
The problem is that when we read the native crash report data from the disk, dnsproxy has been already started and the `dnsproxy_stderr.log` file is empty.

**Comment by ameshkov** [comment]
My bad, it seems we can

**Comment by ameshkov** [comment]
Reopened, there's still a probability this will happen

**Comment by admitrevskiy** [comment]
We read `dnsproxy_stderr.log` on `CrashReportingServiceImpl` initialization before starting DNSProxy, there seems to be no issues with `dnsproxy_stderr.log` file overwriting.
