### ISSUE TITLE
Per-App Traffic Shaping

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3226]
Currently, there is no way to control / limit the speed of traffic from individual apps. We can only enable or disable the app to allow it to connect to internet (Firewall settings in 'Apps Management' page).

However, it would be good if two additional fields can be added in the 'Firewall' section of an app that can allow us to specify custom values for Upload & Download in units like kbit/s, Mbit/s, etc. Therefore, this request is to implement such a feature.

Example Scenario: If a file is being downloaded in a web browser, then the entire traffic is dedicated to that. If you now try to install any other app from the Play Store, it would obviously be very slow as the entire traffic is being used by the browser. In this case, if we implement such a feature in AG, then we can limit traffic per app basis.

**Comment by TPS** [comment]
Perhaps, an app priority for the bandwidth?  E.g., when streaming Netflix, allow to allocate 80% to it, & reserve rest for other/system/&c.

**Comment by Ilithy** [comment]
Hello;
@TPS: I think Nzzyme specified to allocate a maximum bitrate for each application, in Kbps, Mbps and Gbps; example: allocate to the Netflix App a maximum bitrate of 40Mbps i.e. ~4MB/s, to avoid it taking 80MB (for example) unnecessarily.

Allocated a percentage may cause problems if AdGuard's bandwidth detection is wrong.

This is a great idea for improvement, I admit, it would make the AdGuard firewall even more convenient (it's already very good).

**Comment by TPS** [comment]
@Ilithy I think that's a great idea for a steady (wired) connection, but on a cell phone (wifi/mobile data), the bandwidth changes constantly, so percentages _might_ be the best way to go, ifF the detection algorithm can be designed well enough.

**Comment by Ilithy** [comment]
Maybe, but assigned a fixed maximum value seems to me the easiest to implement ;-)
you also have to think that a lot of devices running under Android OS today are on fixed bandwidths (TV under Android TV, box tv android, and soon even AdGuard on smart refrigerators under Android ;-)),
after that is only one point of view, because in both cases the important thing is to be able to limit the use of the total available bandwidth.

PS: I don't know if AdGuard can run on an Android TV, but I think it can.

**Comment by artemiv4nov** [comment]
We have a few firewall improvements in the new version, please try use them. They are not the same you want but it's much better than in 2019:)

**Comment by TPS** [comment]
@artemiv4nov Please reopen.  This is an important request many years waiting.
