### ISSUE TITLE
Per-App Quota Management

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3227]
Currently, there is no quota management in AG where we could specify that a particular app needs to only use a particular amount of data.

Many of the users use a limited bandwidth internet connection (Fair Usage Policy, etc.) and to them, data is precious and we all know how Android is when it comes to data transfers (foreground & background apps). Many apps need data for many things - keep polling for updates, messages, queries, content, back-ups, sync, etc. and these sometimes happen without the user's intervention (background) and in this case, if there is no quota management, then the traffic gets exhausted quickly.

This request is therefore to implement such a feature where we can specify the amount of data (in bytes/kilo bytes/Mega bytes, etc.) for an app (in 'Apps Management' page) so that when the app crosses that limit, it should no longer be able to access the internet.

Ex: Specify a limit of 500 MB to Play Store and it can only access (download apps) till it reaches that limit. Once it crosses this limit, the app should not be able to access the internet.

**Comment by Nzzyme** [comment]
@ameshkov Why is this issue closed? You mentioned https://github.com/AdguardTeam/AdguardForAndroid/issues/1363 but that is a different issue. Is this being worked on as part of another request?

**Comment by Nzzyme** [comment]
Hello, is this request being considered?

**Comment by ameshkov** [comment]
@Nzzyme it's open so it will be considered in the future when we have time for this.

For the nearest future, the scope of v4.0 is already defined.

**Comment by Nzzyme** [comment]
Thanks

**Comment by artemiv4nov** [comment]
Often an Android OS provides the same functionality for applications natively. We have a new version of Firewall in application, please try use it.

**Comment by TPS** [comment]
There's nothing in the firewall that approaches this.  Please reopen.
