### ISSUE TITLE
DNS filtering: block cloaked trackers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3228]
See the original task in the mobile API:
https://github.com/AdguardTeam/dnsproxy/issues/76

**Comment by admitrevskiy** [comment]
Done. Testing instructions for QA:

- Reinstall AG
- Find some DNS upstream which has CNAME record for some host. For example:
```
dig @8.8.8.8 mail.google.com
```
should return CNAME record `googlemail.l.google.com.`
- Enable DNS filtering and select chosen upstream
- Add DNS filtering rule for CNAME:`0.0.0.0 cname` or `||cname^. For mail.google.com valid rule is `||googlemail.l.google.com^` (please note that cname record has a dot in the end. You shouldn't include this dot to the filtering rule)
- Try to reach selected domain

Expected result:
- Domain is blocked
- Go to the filtering log
- DNS request is blocked with CNAME filtering rule.

**Comment by TPS** [comment]
It seems not to be working clearly (correctly).  IIUC, this is implemented in v3.3n25(166).  However, my userfilter `||c.` blocks `m.media-amazon.com` & `images-na.ssl-images-amazon.com`, but the log doesn't show _how/why_.…

**Comment by admitrevskiy** [comment]
Done. 
Original answer with CNAME was added to Filtering Log
