### ISSUE TITLE
Integrate with  DnsLibs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3229]
https://github.com/AdguardTeam/DnsLibs

**Comment by admitrevskiy** [comment]
Here some critical fixes that we need before implementation:
https://github.com/AdguardTeam/DnsLibs/issues/20
https://github.com/AdguardTeam/DnsLibs/issues/31
https://github.com/AdguardTeam/DnsLibs/issues/34
https://github.com/AdguardTeam/DnsLibs/issues/38

These issues are not critical, but it would be nice to resolve them before implementation:
https://github.com/AdguardTeam/DnsLibs/issues/27
https://github.com/AdguardTeam/DnsLibs/issues/28
https://github.com/AdguardTeam/DnsLibs/issues/29
https://github.com/AdguardTeam/DnsLibs/issues/30
https://github.com/AdguardTeam/DnsLibs/issues/36
https://github.com/AdguardTeam/DnsLibs/issues/39
https://github.com/AdguardTeam/DnsLibs/issues/40
