### ISSUE TITLE
CloudFlare DNS periodically dies in autoproxy mode

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3232]
### Issue Details

- **AdGuard version:**
  - 3.2.150
- **Filtering mode:**
  - Local HTTP Proxy (Auto)
- **Device:**
  - Xiaomi Mi 5
- **Operating system and version:**
  - Android 9 / LineageOS
- **Root access:**
  - Yes

### Expected Behavior

Cloudflare 1.1.1.1 DNS should work without interruptions.

### Actual Behavior

Cloudflare 1.1.1.1 DNS randomly causes all connections to stop working. Only happens if DoT is used; does not affect DoH, DNSCrypt and regular versions.

### Screenshots

N/A

### Additional Information & Logs

See helpdesk ticket 2410514

**Comment by artemiv4nov** [comment]
The IPv6 blocking mechanism has been re-worked in the 4.0 version, please follow updates.
