### ISSUE TITLE
[Question] Can I block ads in the YouTube app on Android?

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3236]
Is it possible for me to block ads in the YouTube app using AdGuard for Android (With premium license) or do I have to use a browser?

**Comment by BooBerry** [comment]
Nope, AG for Android can't filter the YouTube app.

I'd recommend either using a modified YouTube app with ads removed like [YouTube Vanced](https://vanced.app/) or using a third-party YouTube app like [NewPipe](https://newpipe.schabi.org/).

**Comment by Cybo1927** [comment]
Okay, Thanks!
