### ISSUE TITLE
Can't navigate settings for FireTV

### ISSUE THREAD

**Issue by stevenjaycohen** [AdguardTeam/AdguardForAndroid#3238]
By default, the device will refuse to download your apk directly from your site. My guess is that Mr. Bezos does not want the ads to be removed. ;)

By downloading the apk on another device, renaming the file, uploading to another server, and then downloading to the FireTV, I can install the app on the device, but the following issues arise.

1. The tutorial overlay cannot be closed because the FireTV device does not see it's buttons as points that it can navigate to.
2. After force stopping the app and reopening it, the overlay can be closed. I then found that I could not navigate the settings on the FireTV for the same reason, I can select the settings menu and toggle it open, but I cannot select any of the submenus.

Expected Behavior:
I'd like to be able to toggle all settings of the app using the remote that accompanies the FireTV. If anyone has found a workaround, I'd love to know that too.

NOTE:
I was so impressed with this app that I bought a lifetime license for my main devices. I then took my 2 beta licenses and tried moving them to other devices in my home, one for the FireTV and the other to my LifeBook Mars e-Ink tablet. It's working well on the tablet. And, I'd love to be of any help that I can in getting this working on the FireTV.

**Comment by artemiv4nov** [comment]
@stevenjaycohen , Hi!
What version os Android OS do you have on FireTV?

**Comment by stevenjaycohen** [comment]
Fire OS 6.2.6.8 (NS6268/2315)
Fire TV Home Version
6.1.8.1-012

**Comment by stevenjaycohen** [comment]
https://photos.app.goo.gl/7vrmpfS1DP7HaX4c9

There is no way to navigate from Settings to General.

When the menu is open, DOWN needs to see the contents of Settings below it. Right now, it skips over it completely.
