### ISSUE TITLE
[Question] Is There Something I Can Add To My Filters List To Recognize Certain Domains As Trackers Instead Of Ads

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3239]
Is there something I can put into my filters list that will add domains under 'Trackers' instead of 'Ads'

![Screenshot_20191201-135906_1](https://user-images.githubusercontent.com/39284087/69919538-5a62a500-1443-11ea-8d6d-185b384442ec.png)

**Comment by pidus** [comment]
Disabling Ad blocking filters and enabling Privacy filters should do. But, blocking only trackers would block most ads as a side effect.

**Comment by Cybo1927** [comment]
@pidus I mean for my custom filter list `https://github.com/Cybo1927/Hosts`

**Comment by TheHasagi** [comment]
@Cybo1927 

It can be recognized only if the filter was made to block trackers.

**Comment by Cybo1927** [comment]
@TheHasagi So.. is there a way I can make AdGuard recognize my stuff in /Anti/ as trackers and not ads?

**Comment by ameshkov** [comment]
Well, you cannot, it will always be considered "ads".

**Comment by Cybo1927** [comment]
@ameshkov Could I make a feature request or would it be a waste of time (like if nobody else would use it)?

**Comment by ameshkov** [comment]
I think it will be a low priority issue, but we can see how many upvotes it will get
