### ISSUE TITLE
Certificate Installation Errors in Android Q with/without magisk module. 

### ISSUE THREAD

**Issue by RaXorX** [AdguardTeam/AdguardForAndroid#3241]
Alright. While using the latest nightlies for Adguard I encountered some issues with the certificate installation. 

Magisk: Canary 20.2-72edbfc4 (20108)
Adguard: Nightly 3.3.166
Android OS: EvolutionX Unofficial v18 for lavender (Redmi Note 7)

After installing adguard and the certificate in user store, I tried to move it to the system store where I got the usual notification suggesting me to use magisk module to process this transition. 
Apparently, this got the certificate installed but in browser it gave me issues which apparently couldn't verify/trust the certificate. 

As Andrey suggested, I tried installing it normally without magisk and here is my observation and how I got it to work properly.

1) Give AG su permissions before trying to make the certificate move to system, otherwise it'll take 3  attempts.
2) Install certificate for the first time. Then move it to the system, if su permissions are granted it'll say successful. (If su permissions aren't granted already, it'll ask for su permission and even though it seems like it got installed, it doesn't actually. If this is the case, then repeat the steps, but one will have to reinstall the certificate from the beginning).
3) After it shows the successful notification, I noticed that AG still showed as if there was no certificate installed. I had to install it one more time to get AG to show. But when I tried to install it to the system again it gave me an error and suggested me to use magisk. Reboot.
4) Check in Settings->Security->Encryption and Credentials->Trusted credentials to see if there's AG certificate or not (for both user and system) If so, delete the user one and reboot. 

This got HTTPS filtering working normally. 

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Although with this method there's a drawback. I couldn't delete/remove the system certificate. Even after I deleted it from the AG, rebooted it was still present in the trusted credentials under system. If I installed AG once again after removing it, it didn't take that system cert already present into account. But when I repeated the above steps and got the error while moving the cert to the system store, a reboot afterwards got it working again while being in the system store (at this point it showed me 2 certs since I had to install it once again in the user store to get it to work). After which I removed the user one once again, which kept the system cert working as before. 

My only concern is, with this method how does one go about actually removing the cert from the system store if they don't use the magisk module.

I also saw some users had issues with installing the cert this way, maybe this is a way to solve it up.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2941

**Comment by TheHasagi** [comment]
@RaXorX 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by RaXorX** [comment]
@TheHasagi Since and after I installed the certificate in system with root without the magisk module, I am unable to remove it. Failing to remove it and the inability to install a duplicate cert over it will only make me get either inaccurate logs or different/more issues than before. What do you suggest me to do? 

Already tried uninstalling it through adguard which only removes it from itself and not the system. I guess that's the whole disadvantage with it and thus, the suggestion to use Magisk.

**Comment by RaXorX** [comment]
Ah, so this got fixed in later nightlies on it's own, reason why I didn't ask more about it. Apparently, with the latest nightly it's back.

**Comment by ameshkov** [comment]
@RaXorX we'll need new logs then.

We only need AdGuard logs here, Android bug report is not needed. We need to see what was going on during the certificate installation/removal.

**Comment by artemiv4nov** [comment]
@RaXorX Well, the task has been resolved in 2019 and it cannot appear in the latest nightly. So, you can recheck it on the pre latest nightly and be sure yourself. And, can you describe the details of your system, please?
Root/non-root; Android version; Phone model.

**Comment by artemiv4nov** [comment]
I'll close this task. Please, reopen it if the issue still has on your device.
