### ISSUE TITLE
[Feature Request]  Add something for Filters List Maintainers To Define What Their Filters Are Blocking (ads, trackers, or threats)

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3242]
### Problem Description

Currently custom filters when blocking requests are listen under ads. Would be nice to have a way for AdGuard on Android to put certain things under trackers blocked and not ads. Example: my hosts `https://github.com/Cybo1927/Hosts/blob/master/Hosts` is fine being placed under ads but the stuff in `https://github.com/Cybo1927/Hosts/tree/master/Anti` is to prevent specified apps/companies from tracking you (by trying to preventing all connections to them). 

This really comes down to the individual, I personally believe it looks better on the homescreen for it to show something like 'Ads blocked = 60,000' and 'Trackers blocked = 2,000' instead of trackers having 0

### Additional Information

Would probably be something with `!#` so other adblockers like Adblock Plus thinks it's a comment

https://github.com/AdguardTeam/AdguardForAndroid/issues/3239

**Comment by ameshkov** [comment]
Actually, after some thinking, I think we should provide a way to set the filter list category, and not an individual rule category.

For instance, it could be a special comment or tag:
`Category: ads`

**Comment by Cybo1927** [comment]
How exactly would it work? (like would it be another tag like Title?)

And it's up to you honestly, I don't really know what would be best.

**Comment by Cybo1927** [comment]
I dunno if you guys still have plans to do this, just checking up on it

Another thing you could add would be in the filtering log. When you click on a blocked domain under "filter name" you could have a spot for the category so users know why it was blocked

**Comment by ameshkov** [comment]
Uh, sorry for the late reply.

We discussed this and decided against it after all. Instead of that, we'd better use a database of categorized domains (like what whotracksme maintains) or create one ourselves. This way we won't need to rely on filters maintainers and make sure that requests are properly categorized regardless of the filter list.
