### ISSUE TITLE
UDP relay over SOCKS5 support.

### ISSUE THREAD

**Issue by Howard-00** [AdguardTeam/AdguardForAndroid#3243]
This feature request was put in #1357 two years ago, and got a `P3: Medium` label but haven't been solved so far. 
As you know, in some countries, a proxy is very important to get connected with the full internet, and no UDP relay can be a serious problem. 
So I will be really appreciated if you could re-prioritize this feature request and work on it.

**Comment by artemiv4nov** [comment]
At the moment, we already have the full set of tasks for the 3.4 release. We'll try to re-prioritize tasks in 2020.

**Comment by ameshkov** [comment]
We're going to add it in the coming months for sure, but this issue should be filed to CoreLibs instead. I'll move #1357 to the proper repo.

**Comment by Howard-00** [comment]
> We're going to add it in the coming months for sure, but this issue should be filed to CoreLibs instead. I'll move #1357 to the proper repo.

That's awesome. So many thanks to you.
