### ISSUE TITLE
DNS issue on OnePlus 7pro in China

### ISSUE THREAD

**Issue by mariokart1992** [AdguardTeam/AdguardForAndroid#3247]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.3 beta 2 & 3.2 stable
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - OnePlus 7 pro
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Actual Behavior
I found that in China. My Android phone select  every DNS listed in the Adguard will have a Exclamation mark on WiFi & LTE signal , used for a while it will suddenly no signal and got back. I can only manually use 119.29.29.29 or 223.5.5.5 to avoid that. My phone's version is Android 10 now. How can I use Adguard DOH or Cloudflare DOH on my phone in China?

**Comment by mariokart1992** [comment]
Is there anyone can solve this problem? I have sent the log file to devteam mail box.

PS: When I back to Japan and travel to Korea, there is no problem with DNS setting on my phone. Only happened when I go to China. Is there any solutions to this issue?

**Comment by ameshkov** [comment]
@artemiv4nov logs are in the nextcloud.

@mariokart1992 I see you have a VPN connection. Do you have this issue every time or only when you're using AG alongside the VPN?

**Comment by mariokart1992** [comment]
Dear team

I tried to use Adguard only. But still will facing the problem.

I tried to clean the cache and restart the phone without any other VPN
connected.

Don't think it related to my VPN.



Andrey Meshkov <notifications@github.com> 于 2019年12月9日周一 05:08写道：

**Comment by ameshkov** [comment]
@mariokart1992 could you please record the same log but with "System DNS" selected instead of a custom DNS?

I suspect that in China they re-route the `connectivitycheck.gstatic.com.` domain to some other IP address, and the IP returned by AdGuard and CloudFlare simply does not work.
