### ISSUE TITLE
Turn on the "Blocking phishing and malware" when the status is Premium

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3249]
We have to turn on the "Blocking phishing and malware" module when the premium status activated.
The mechanism of the turning on of the "Blocking ads and trackers" module is similar.

**Comment by Revertron** [comment]
After thorough investigation it may be concluded, that browsing protection is being enabled by default, if user hadn't the chance to disable it on purpose before enabling premium.

**Comment by Revertron** [comment]
It seems, that there is a problem in Onboarding, that saves false flag.
