### ISSUE TITLE
Add HTTPS filtering configuration to the state.txt sent to support along with a message

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#325]
We should send the following information:
1. HTTPs filtering status (enabled or disabled). If certificate is not installed - set it to false.
2. HTTPs filtering mode (either BLACKLIST or WHITELIST)

**Comment by Revertron** [comment]
Without active list itself? :-/

**Comment by ameshkov** [comment]
The list (at least the whitelist) will be ~1000 domains

**Comment by Revertron** [comment]
Done.
