### ISSUE TITLE
[MIUI 9+] Hiding app window (swiping left) in Task Manager kills the app entirely

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3256]
### Issue Details

- **AdGuard version:**
  - 3.2.150
- **Filtering mode:**
  - Local VPN (Full filtering quality)
- **Device:**
  - Xiaomi Redmi Note 4
- **Operating system and version:**
  - Android 7 NRD90M, MIUI Global 11.0.2 Stable
- **Root access:**
  - No

### Expected Behavior

"Killing" the app through Task Manager should only close its window, not kill the service outright

### Actual Behavior

App dies, local VPN connection breaks.

### Screen recording

<details><summary>Screen recording:</summary>

https://drive.google.com/file/d/15X54LHzP5mMEd9WsButiAUrjN5Z66O9u/view

</details>

### Additional Information

Helpdesk ID: 2251404

**Comment by TheHasagi** [comment]
This depends on MIUI. To avoid such issues app should be locked in the tasks and should not be withdrawn manually.

More information available in [KnowledgeBase](https://kb.adguard.com/ru/android/solving-problems/background-work#Xiaomi).
