### ISSUE TITLE
DNS Selection Description Missing

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [AdguardTeam/AdguardForAndroid#3265]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.3 nightly 30
- **Filtering mode:**
  - HTTP Proxy
- **Device:**
  - Mi Pad 4
- **Operating system and version:**
  - Android 8.1.0
- **Root access:**
  - Yes

### Screenshot
![Screenshot_2019-12-14-21-50-42-407_com adguard android](https://user-images.githubusercontent.com/1637244/70850343-d6390480-1ebb-11ea-999d-34cee854cd61.png)
![Screenshot_2019-12-14-21-50-37-052_com adguard android](https://user-images.githubusercontent.com/1637244/70850345-d933f500-1ebb-11ea-8297-727dc78498ae.png)

**Comment by ameshkov** [comment]
Looks like a bug indeed, thank you for reporting it!

**Comment by artemiv4nov** [comment]
@ameshkov That's can happen when APK was rebuild.

**Comment by ameshkov** [comment]
Yep, cannot reproduce with the official build.

**Comment by Crescendo-BLYAT** [comment]
I don't think I'm using rebuilt apk...
But one thing for sure, I re-installed the same one, it works OK now...
