### ISSUE TITLE
Allow users to select filter auto-update algo manually

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3267]
### Problem Description

In newer versions of AdGuard, AdGuard only updates its filters when the device is blocked or in sleep mode. This seems to upset some users who use their devices constantly (see helpdesk ticket 2387896 for an example).

### Proposed Solution

Add an option to select filter auto-update algo:
1. Update filters & restart protection in sleep mode
2. Update filters & restart protection anytime
3. Update filters anywhere, ask user whether we should restart protection now or do it later

### Alternatives Considered

Just roll back to previous mode.

### Additional Information

None provided

**Comment by ameshkov** [comment]
Well, let's see how many upvotes this feature request gets.

**Comment by artemiv4nov** [comment]
It looks like not so popular feature request. Please re-open it if it will gain more than 10 upvotes.

**Comment by TPS** [comment]
This is easily handled _externally_ (via automation support), but really should be handled internally. Please reconsider.
