### ISSUE TITLE
Exclude com.google.android.apps.adwords from the list of filtered apps

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#327]
https://play.google.com/store/apps/details?id=com.google.android.apps.adwords
You get a connection error.
Logs are here - MOV-337-57825

**Comment by ameshkov** [comment]
@evgeniy-ADG does disabling ad filtering through the Firewall help?

**Comment by evgeniy-ADG** [comment]
@ameshkov that's what the customer replied:

> Если отключить то запускается, запись в низкоуровневых настройках не помогла.
> При vpn фильтрации не работает, а при http работает...

**Comment by ameshkov** [comment]
Is "DNS filtering" enabled? If it is, then only pref.net.exclusions could help.

But it will help in Android 5+ only.

**Comment by evgeniy-ADG** [comment]
Not sure, can you check it in logs (MOV-337-57825)?

**Comment by ameshkov** [comment]
Adding "com.google.android.apps.adwords" to pref.net.exclusions should help (according to what I see).

**Comment by Revertron** [comment]
Done.

**Comment by Bohdan-SUP** [comment]
Adguard 2.6.23, user can't login to AdWords with protection enabled:
NHX-751-56350

**Comment by ameshkov** [comment]
It seems that package name is different:
com.google.android.apps.ads.express

**Comment by Revertron** [comment]
Added that one.
