### ISSUE TITLE
Update filters and translations before beta 4

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3271]

**Comment by lancelot-moon** [comment]
v3.3 was release, but filters' description and translations aren't updated.
May you update locales in filters registry?
https://crowdin.com/project/adguard-applications/en#/miscellaneous/filters-registry
Thanks.

**Comment by ameshkov** [comment]
Yeah, we missed that, we'll update the filters registry soon.

**Comment by lancelot-moon** [comment]
Thanks a lot!
Although the translations of zh-TW are up to date, there are some outmoded translations in some other languages.
Anna needs to approve corrected ones.
ex: The current translations of zh-CN (Chinese Simplified) in the filters registry are outmoded (still the translations of English filter, Spyware filter, Useful filter...), but some new translations aren't uniform.
https://github.com/AdguardTeam/FiltersRegistry/issues/284

Anyway, it depends on translators, not AdGuard's responsibility.
Best regards.
