### ISSUE TITLE
Apps Management: "Bulk change" do not persist

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3273]
## Issue Details

- **AdGuard version:**
  - 3.2.150, 3.3.210
- **Filtering mode:**
  - Local VPN HQ
- **Device:**
  - Samsung Galaxy Tab SM-T555
- **Operating system and version:**
  - Android 7.1
- **Root access:**
  - None

### Expected Behavior

Applying changes through Apps Management > Bulk Changes correctly applies settings everywhere.

### Actual Behavior

Settings are not saved.

### Screenshots

N/A

### Additional Information

Helpdesk ID: 1394429

**Comment by TheHasagi** [comment]
@akmLaVx 

Ask a customer to check with the actual beta or nightly build.

**Comment by akmLaVx** [comment]
They are already on the latest nightly build. No changes.
