### ISSUE TITLE
Bulk changes UI bug

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3274]
AdGuard - Apps management - Bulk change

<details>

![image](https://user-images.githubusercontent.com/37797229/70980133-d73c8280-20c3-11ea-9cc6-858056d0491d.png)

</details>

This bug can be reproduced only with mobile devices with a high resolution of the display.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
