### ISSUE TITLE
com.amazon.avod.thirdpartyclient - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3277]
@adguard-bot commented on [Wed Dec 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45786)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.amazon.avod.thirdpartyclient](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.amazon.avod.thirdpartyclient)
### Comment
Username: @Rakleed
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/iySUrVJ.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/24Ygdug.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your User-Agent ()
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

---

@Alex-302 commented on [Thu Dec 12 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45786#issuecomment-564969052)

Не повторяется. Нужны отладочные логи с указанием времени ошибки.

---

@Rakleed commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45786#issuecomment-566190440)

Отправил в поддержку. Время воспроизведения — 9:43 p.m. ID: 939612.

**Comment by TheHasagi** [comment]
It is not working if HTTPS filtering is enabled for this application in AdGuard - Apps management.

@Rakleed

Please, check without HTTPS filtering for this app.

**Comment by Rakleed** [comment]
@TheHasagi, при отключении HTTPS-фильтрации проблемы нет.
