### ISSUE TITLE
com.slack compatibility issues

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3279]
### Issue Details

- **AdGuard version:**
  - 3.2.150
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy S10+
- **Operating system and version:**
  - Android 10

### Actual Behavior

Slack gets stuck on "Connecting..." when using AdGuard

### Additional Information

user id: 2455198

**Comment by BoD** [comment]
Actually I want to clarify that it's not just Slack that isn't working but all the apps. The network seems to be completely unreachable (all the calls end up with a timeout).

I have tried to uninstall / reinstall AdGuard, and got the same behavior. 

Thus I believe it should be easy to reproduce the issue: get a Samsung Galaxy s10+ with the Android 10 update, and try AdGuard, I'm pretty sure it won't work.

Please don't hesitate to ask me any information that could help you resolve this issue, I sorely miss my ad blocker!

**Comment by artemiv4nov** [comment]
@BoD ,
Hi!

Something tells me that your problem is with the operation of the DNS on your device.
We already fixed it in the #3259 task.
Please, update the AdGuard app to the beta version and try again.

**Comment by BoD** [comment]
Yes!!!  That worked indeed.  Thanks a lot, and kudos! :)
