### ISSUE TITLE
Protection restart became very slow because of SSL connections

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#328]
Steps to reproduce:
1. Disable Wi-Fi
2. Enable it again in 5 seconds
3. You'll see that it will take 30 seconds to stop and then start AG again

**Comment by Revertron** [comment]
On my device Adguard starts momentarily always. May be you have some dozens of apps that are all starting by their BroadcastReceivers on network change? Just root your device and disable them ;-)

**Comment by ameshkov** [comment]
Nah, I am talking about protection restart, not just starting. Specifically - about protection stopping.

It seems that SSL connections are really slow to close (as along with closing the connection is sends a shutdown packet).

**Comment by Revertron** [comment]
I have noticed it too :(

**Comment by ameshkov** [comment]
```
02-26 15:39:49.394  20166-25395/? I/com.adguard.android.filtering.vpn.VpnProxyService﹕ [Thread-8404] Closing all connections...
02-26 15:40:15.946  20166-25712/? I/com.adguard.filter.proxy.BaseHttpProxyServer﹕ [pool-2-thread-89] Active connections have been closed
```

**Comment by ameshkov** [comment]
Done
