### ISSUE TITLE
The google play store app has no internet connection

### ISSUE THREAD

**Issue by mmyz1234** [AdguardTeam/AdguardForAndroid#3280]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.2.150 & v3.3 beta 3.1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Note 8
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

The internet connection of google play store app is normal.

### Actual Behavior

The google play store app has no internet connection.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20191221-123456_Google Play Store](https://user-images.githubusercontent.com/30427542/71303564-927f5700-23f5-11ea-905e-1d719ed9c654.jpg)

</details>

### Additional Information

In China, we have to access some websites through a proxy. However, when I use adguard, the google play store app does not have internet. The following is the details of the problem.

####  Step 1

- **Step:**

1. Start a http proxy service, the proxy ip is 127.0.0.1, the proxy port is 1080.
2. Configure and enable this proxy in adguard.
3. Enable adguard.

<details><summary>Screenshot:</summary>

![Screenshot_20191221-123419_AdGuard](https://user-images.githubusercontent.com/30427542/71303753-19353380-23f8-11ea-9dea-369798d7fb54.jpg)

</details>

- **Result:**
  - The google play store app has no internet connection.
  - The internet connection of other app is normal.
  - Access the google play store website normally through chrome.

####  Step 2

- **Step:**

1. Start a http proxy service, the proxy ip is 127.0.0.1, the proxy port is 1080.
2. Disable adguard.
3. Configure this proxy manually in the advanced settings of wlan.

<details><summary>Screenshot:</summary>

![Screenshot_20191221-123556_Settings](https://user-images.githubusercontent.com/30427542/71304155-9adb9000-23fd-11ea-8994-ae10a91e9049.jpg)

</details>

- **Result:**
  - The internet connection of google play store app is normal.
  - The internet connection of other app is normal.

####  Step 3

- **Step:**

1. After Step 2.
2. Remove the proxy in the advanced settings of wlan.
3. Configure and enable the proxy in adguard.
4. Enable adguard.

- **Result:**
  - The internet connection of google play store app is normal.
  - The internet connection of other app is normal.
  - After 24 hours, the google play store app will have no internet connection. but you can access the play store website through chrome. Now, if you go to Step 2 again, and than go to Step 3, the internet connection of google play store app will be normal. However, after 24 hours, the google play store app will have no internet connection again. You need to go to Step 2 again, and than go to Step 3...

### Log file

- **by adguard:**
  - [adguard_logs_3.3.227_2212_094548.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3992150/adguard_logs_3.3.227_2212_094548.zip)

**Comment by admitrevskiy** [comment]
@mmyz1234 Hi!
Please, provide me a little bit more information.
As I can see in logs provided, Google Play store app was not excluded from VPN. 
Check your settings for this app: 
`Apps Management` –> `Search` –> Type `Google Play Market` or `com.android.vending` 

All switches should be turned off and state icons should be red since there is no way to filter this app so that it will continue to work correctly.

**Comment by mmyz1234** [comment]
@admitrevskiy 
Yes, Google Play store app was not excluded from VPN.
There is GFW in China. So we have to use proxy in Google Play store app.
AdGuard runs with proxy in local vpn mode.
The Google Play store app traffic should be routed through Adguard, so this app can use proxy. 
But there is a problem which I said in this issue. I want a solution to make Google Play store app work correctly in this case.
Thanks.

**Comment by mmyz1234** [comment]
Actually, AdGuard runs with proxy in local vpn mode, the Gmail app and Youtube app also have the same problem. The chrome app cannot sync bookmarks, but it can access websites like google.com, youtube.com and etc.

**Comment by ameshkov** [comment]
Could it be that the problem is in the proxy itself? For instance, it may be dropping connections to non-standard ports?

**Comment by mmyz1234** [comment]
> Could it be that the problem is in the proxy itself? For instance, it may be dropping connections to non-standard ports?

I have tested the proxy such as Shadowsocks and V2Ray.

- Shadowsock runs in vpn mode without adguard, all is normal.
- Shadowsock start a proxy service, configure this proxy manually in the advanced settings of wlan, all is normal.
- Shadowsock start a proxy service, configure this proxy in SocksDroid app, all is normal.
- Shadowsock start a proxy service, configure and enable this proxy in adguard, there is a problem which I said in this issue.
- V2ray is the same as Shadowsocks.

So I'm sure my proxy has no problem.

**Comment by ameshkov** [comment]
Got it. So the easiest way for us to reproduce this is to try using AdGuard alongside Shadowsocks (configure it to be an outbound proxy server in AG). We'll get back once we try reproducing it.

**Comment by mmyz1234** [comment]
It seems that the proxy in AdGuard can not handle the traffic of GMS properly. So it caused the problem in the app of Google series.

**Comment by ameshkov** [comment]
@mmyz1234 well, if you don't filter HTTPS there then AdGuard just proxies TCP/UDP traffic with no special treatment.

**Comment by mmyz1234** [comment]
Configure the proxy in NetGuard app, all is normal. I hope that AdGuard can be fixed soon. Thanks.

**Comment by artemiv4nov** [comment]
@mmyz1234 hi! Could you check your issue on the latest nightly version of the AdGuard? Thanks!

**Comment by mmyz1234** [comment]
@artemiv4nov I have checked it on AdGuard 3.4 nightly 9. The problem still exists.

[adguard_logs_3.4.40_2503_222319.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4381748/adguard_logs_3.4.40_2503_222319.zip)

* Check Youtube
  * [video-screenshots-check-youtube.mp4](https://github.com/mmyz1234/FeedbackForAdguard/raw/master/video-screenshots-check-youtube.mp4)
  * [log-check-youtube.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/4381755/log-check-youtube.txt)
* Check Google Play
  * [video-screenshots-check-google-play.mp4](https://github.com/mmyz1234/FeedbackForAdguard/raw/master/video-screenshots-check-google-play.mp4)
  * [log-check-google-play.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/4381762/log-check-google-play.txt)

**Comment by mmyz1234** [comment]
@artemiv4nov I will provide more information to resolve this problem.

It seems that AdGuard can not route the traffic of `com.google.android.gms`, `com.google.android.gsf` and `com.google.android.backuptransport`, even though enable it in Apps Management in AdGuard.

Check the log in AdGuard when use google play store. There is no log about these 3 package.

<details><summary>Screenshot:</summary>

![Screenshot_20200329-120858_AdGuard](https://user-images.githubusercontent.com/30427542/77840303-80f9d800-71b8-11ea-9d2b-8f00ab9b0c15.jpg)

</details>

But you can find the log about these 3 package (uid: 10036) if you use NetGuard instead of AdGuard.

<details><summary>Screenshot:</summary>

![Screenshot_20200329-121038_NetGuard](https://user-images.githubusercontent.com/30427542/77840354-34fb6300-71b9-11ea-9d6f-96e182225747.jpg)

![Screenshot_20200329-122027_AdGuard](https://user-images.githubusercontent.com/30427542/77840375-5ceac680-71b9-11ea-85e6-0064e5e668b0.jpg)

</details>

**Comment by artemiv4nov** [comment]
Maybe this task is related to #3355 , will see after it will be done

**Comment by mmyz1234** [comment]
The problem still exists in AdGuard 3.4 nightly 13.

**Comment by mmyz1234** [comment]
The problem still exists in AdGuard 3.4 nightly 15.

**Comment by ForeverCan** [comment]
same issue with galaxy s10

**Comment by mmyz1234** [comment]
It is fixed in AdGuard 3.4 nightly 16. Thanks.

**Comment by mmyz1234** [comment]
This problem reappears in AdGuard 3.4 nightly 18.

**Comment by ForeverCan** [comment]
> This problem reappears in AdGuard 3.4 nightly 18.

yes, same here
i rolled back to nightly 17...

**Comment by artemiv4nov** [comment]
@mmyz1234 @ForeverCan Reset your Low-Level settings to default, please and re-check again.

**Comment by mmyz1234** [comment]
@artemiv4nov 
> Reset your Low-Level settings to default, please and re-check again.

Not work, the problem still exists.

**Comment by artemiv4nov** [comment]
@mmyz1234 Can you collect debug logs with the exact problem time, please?

**Comment by mmyz1234** [comment]
@artemiv4nov Sent. Please check.

**Comment by artemiv4nov** [comment]
@mmyz1234 So, we are trying to understand what is going wrong with traffic. Can you play a little with Low-Level settings, please? You have the "pref.excluded.packages" setting. Try to remove 1000 or/and 1001 UIDs, maybe, something will change.

**Comment by artemiv4nov** [comment]
@mmyz1234 Also, send the Android Bug report, please. You can collect it using our instructions: https://kb.adguard.com/en/android/solving-problems/logcat#capture-a-bug-report-from-a-device

**Comment by mmyz1234** [comment]
@artemiv4nov 
> Try to remove 1000 or/and 1001 UIDs, maybe, something will change.

Remove 1000, it work. 

> send the Android Bug report, please. You can collect it using our instructions: https://kb.adguard.com/en/android/solving-problems/logcat#capture-a-bug-report-from-a-device

I have resent the log to <devteam@adguard.com>, please check.

**Comment by xxy9468615** [comment]
您好，请问有官方过滤器规则吗，全面的。

**Comment by artemiv4nov** [comment]
So, we have tested a lot of options with @mmyz1234 (thank you again, sir). the only possible way to use a few Google applications under VPN with a proxy server is to remove the UID 1000 from a default list of the "pref.excluded.packages" Low-Level setting.

**Comment by ForeverCan** [comment]
> @artemiv4nov
> 
> > Try to remove 1000 or/and 1001 UIDs, maybe, something will change.
> 
> Remove 1000, it work.
> 
> > send the Android Bug report, please. You can collect it using our instructions: https://kb.adguard.com/en/android/solving-problems/logcat#capture-a-bug-report-from-a-device
> 
> I have resent the log to [devteam@adguard.com](mailto:devteam@adguard.com), please check.

what about the newest 19 version?

**Comment by ForeverCan** [comment]
> @artemiv4nov
> 
> > Try to remove 1000 or/and 1001 UIDs, maybe, something will change.
> 
> Remove 1000, it work.
> 
> > send the Android Bug report, please. You can collect it using our instructions: https://kb.adguard.com/en/android/solving-problems/logcat#capture-a-bug-report-from-a-device
> 
> I have resent the log to [devteam@adguard.com](mailto:devteam@adguard.com), please check.

what about the latest 19 version?
im staying with the 17 version.

**Comment by artemiv4nov** [comment]
@ForeverCan it should be worked, also.
