### ISSUE TITLE
Error HTTPS filtering

### ISSUE THREAD

**Issue by minsk21** [AdguardTeam/AdguardForAndroid#3285]
Optional ability to disable notifications about this error

<details>

![Пример](https://i.imgur.com/ySeIwLE.jpg)

</details>

Adguard 3.3.228

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/3225

**Comment by admitrevskiy** [comment]
For now you can disable `all` notifications about this warning with `pref.notify.on.unknown.ca` in Low-level settings
