### ISSUE TITLE
Application won't start after the restart of the device

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3286]
Application won't start after the reboot (this issue is specific and depends on some devices)

### Steps to reproduce:

1. Open AdGuard main menu
2. Tap on update icon
3. After the filters were updated restart the phone
4. Wait untill device is restarted and start the Android OS

<details>

![image](https://user-images.githubusercontent.com/37797229/71514377-5cd3e580-28af-11ea-8f32-bedf10dd8fef.png)

</details>

**Comment by Nzzyme** [comment]
I have the latest version of AG and after I restart my phone, AG does not start automatically.

1. AG settings has autostart enabled
2. The permission 'Start in Background' is enabled for AG
3. AG is enabled in phone's Autostart setting.
4. Exception for AG set in phone's battery saver settings.

But still, when I restart, AG does not start automatically.

My phone specs:

Xiaomi Redmi Note 3
Android version: 6.0.1 MMB29M
MIUI Global 10.2 | Stable
10.2.1.0(MHOMIXM)

**Comment by admitrevskiy** [comment]
@Nzzyme could you please collect debug logs with this issue (Settings -> Advanced -> Logging Level -> Debug) and send 'em to `devteam@adguard.com`?

**Comment by Nzzyme** [comment]
> @Nzzyme could you please collect debug logs with this issue (Settings -> Advanced -> Logging Level -> Debug) and send 'em to `devteam@adguard.com`?

Do you first want me to enable that setting, then reboot the phone and then export the log? What is the sequence?

**Comment by admitrevskiy** [comment]
@Nzzyme yes, absolutely right. Disable all MIUI autostart restrictions, turn on AdGuard autostart in General settings, enable debug logs and reboot the phone. Wait a while after reboot since AdGuard needs some time to receive start-on-boot intent from OS and export logs if something goes wrong.

**Comment by Nzzyme** [comment]
> @Nzzyme yes, absolutely right. Disable all MIUI autostart restrictions, turn on AdGuard autostart in General settings, enable debug logs and reboot the phone. Wait a while after reboot since AdGuard needs some time to receive start-on-boot intent from OS and export logs if something goes wrong.

Sorry to be a pain. I don't see 'Debug' under Logging Level. I see the following:

Default
Record web requests
Record everything
Errors only

Which one should I select?

**Comment by admitrevskiy** [comment]
@Nzzyme Oops, pardon, it's my fault. You should select `Record everything`

**Comment by Nzzyme** [comment]
I sent it. Thanks

**Comment by Nzzyme** [comment]
@admitrevskiy Did you check that?

**Comment by admitrevskiy** [comment]
@Nzzyme sorry for the long response. 

Unfortunately, there is nothing notable in the logs you've sent. Looks like you rebooted device at 13.25 and it took more than 3 minutes before you opened the app again. We need to reproduce this issue on our side and try to debug app on boot. 

BTW Maybe there is something more informative in the logcat (system messages or something). Do you have the possibility to record it? Here are some [instructions from knowledge base](https://kb.adguard.com/en/android/solving-problems/logcat)

**Comment by zzebrum** [comment]
@Nzzyme is the problem still happening on your side?
