### ISSUE TITLE
Any TcpListener is not working on Android 4.4.2

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#329]
TcpListener is standing on selector.select() and not getting any connection attempts.
I've tried "127.0.0.1" and "0.0.0.0" - the server starts okay, but no connections accepted.
The netstat command shows "tcp6" in first column in any case, may be this is the root of all evil?

**Comment by Revertron** [comment]
We must not protect local sockets!

**Comment by ameshkov** [comment]
must not protect? or must protect?
