### ISSUE TITLE
Can't change AG's UI language

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdguardForAndroid#3290]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - `3.4 n3 (7)`
- **Filtering mode:**
  - `Local VPN`
- **Device:**
  - `Nexbit Robin`
- **Operating system and version:**
  - `7.1.1`
- **Root access:**
  - `No`

### Expected Behavior

When I change AG's language, the UI will change its language to target language.

### Actual Behavior

AG's UI language follows the system language setting.

### Screenshots

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/5698157/71544354-78c3ae00-29b9-11ea-9581-db52c796ea23.png)
![image](https://user-images.githubusercontent.com/5698157/71544383-ccce9280-29b9-11ea-9528-12eb6e27fa09.png)

</details>

### Additional Information

[adguard_logs_3.4.7_2812_204120.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4007050/adguard_logs_3.4.7_2812_204120.zip)

**Comment by artemiv4nov** [comment]
@bestpika hi!
This may have occurred when the Android continues to keep the app live even after the system language is changed.
The default behavior os the Android OS is to restart the app after the language is changed.
I think, the problem with your ROM, unfortunately.
