### ISSUE TITLE
"HTTPS filtering is off" SnackBar covers Data Saved stat on Home Screen

### ISSUE THREAD

**Issue by vyanovsky** [AdguardTeam/AdguardForAndroid#3292]
Where: Home screen

In Japanese, German, Russian, Ukranian and other languages, where text "HTTPS filtering is off" goes to second line, SnackBar covers Data Saved stat and users can't see the stat.

![Image from iOS (2)](https://user-images.githubusercontent.com/51786050/71624068-bca0f800-2bf1-11ea-80bf-7f032f92872c.jpg)

**Comment by artemiv4nov** [comment]
@AlikhanAliev do you have any suggestions?

**Comment by artemiv4nov** [comment]
@admitrevskiy 
there are some updates for the task: when the user swipes by snack bar, we should not show it anymore.

**Comment by ameshkov** [comment]
Make the third button "red" to emphasize that we don't recommend it.

**Comment by admitrevskiy** [comment]
Done.
