### ISSUE TITLE
Avast and AVG recognize AdGuard 3.3.1 as ELF:Agent-AEV [Trj]

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#3293]
### Issue Details

- **AdGuard version:**
  - v3.3.1 (229)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - P10 Lite
- **Operating system and version:**
  - Android 8.0 - EMUI 8.0
- **Root access:**
  - No

SHA 256:
437bf87171d8961c4dcc1b03bc0dc9dcbc815adec9813b4205cc10b6655b9404

APK name:
com.adguard.android_3.3.229.apk

Link:
https://www.virustotal.com/gui/file/437bf87171d8961c4dcc1b03bc0dc9dcbc815adec9813b4205cc10b6655b9404/detection

**Comment by SaberAkiyama** [comment]
Sign said "No engines detected this file". I guess it was false positive, to be honest.

**Comment by superlex** [comment]
Yep, now they say _undetected_, thanks.
