### ISSUE TITLE
Let users decide if a request from the log should be added as an adblock filter or a dns filter

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3294]
Let users decide if a request from the log should be added as an adblock filter or a dns filter

**Comment by TPS** [comment]
Actually, many of these, I need _both_, so please don't make mutually exclusive.

**Comment by artemiv4nov** [comment]
Well, I think, we reworked the Recent Activity (ex-Filtering Log) as well in the new version.
