### ISSUE TITLE
Make privacy levels' phrases colored on old versions of Android

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/AdguardForAndroid#3295]
https://user-images.githubusercontent.com/30260021/71641146-1237dc00-2ca8-11ea-88dc-9db301963dee.png

**Comment by artemiv4nov** [comment]
So, here is a little issue related to color makes for a text on the older Android OS versions.
Older Android OS versions use the restricting range of colors, that's why we cannot use  ######## colors.
But we can implement compatibility between actual and restring colors.
