### ISSUE TITLE
Per app proxy setting. 

### ISSUE THREAD

**Issue by h0cheung** [AdguardTeam/AdguardForAndroid#3297]
Sometimes I need an app to not use proxy, but I still want adguard to reduce it's advertisement.

Also, I may need to use several different proxies for different applications at the same time.

**Comment by artemiv4nov** [comment]
well, let's see how much stars this feature request will gain

**Comment by lancelot-moon** [comment]
@artemiv4nov 
Duplication.
https://github.com/AdguardTeam/AdguardForAndroid/issues/3043#event-2616950462

However, I didn't see the opened issue number from Andrey's reply.

**Comment by ameshkov** [comment]
Here it is:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1776
