### ISSUE TITLE
DNS PreFetch bypasses AG-configured DNS

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#3298]
# Issue Details 

Some of the browsers I choose to use (_1st set=_ LastPass, Firefox Focus, Bing) aren't _(yet?)_ compatible w/ HTTPS Filtering & others (Edge, mostly) are.  Yahoo News ( https://news.yahoo.com/ ) site & articles is a completely different experience under each of those, due to extensive use of ads loaded via stylesheets & `<link>` tags.

What concerns me is, where are the DNS queries⁈  If AG was processing them, I'd be able to handle them via DNS Blocking, but nothing appears in logs for these servers, yet the ads _are_ served in the 1st set of browsers, ___even though the servers are specifically in DNS Blocklist___.

- **AdGuard version:**
  - v3.4η4 (11)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Moto G5+
- **Operating system and version:**
  - Android 8.1
- **Root access:**
  - No

### Expected Behavior

Configured DNS should be used, be logged, & be optionally blockable.

### Actual Behavior

AG's DNS looks to be bypassed entirely.

### Screenshots

<details><summary>Screenshot:
</summary>

![Screenshot_20200103-064759](https://user-images.githubusercontent.com/185902/71722692-b8462c00-2df7-11ea-9cae-030b67cf8be8.png)
![Screenshot_20200103-070040](https://user-images.githubusercontent.com/185902/71722697-bf6d3a00-2df7-11ea-8c3b-b968c34ed150.png)
![Screenshot_20200103-064744](https://user-images.githubusercontent.com/185902/71722712-ca27cf00-2df7-11ea-80c9-42442743d517.png)
![Screenshot_20200103-070054](https://user-images.githubusercontent.com/185902/71722718-d875eb00-2df7-11ea-99e0-2b394ce49a68.png)

</details>

**Comment by TPS** [comment]
I tried a workaround, but, sadly https://github.com/AdguardTeam/AdguardForAndroid/issues/2733#issuecomment-549135770 is still a problem.

**Comment by admitrevskiy** [comment]
@TPS Hi!

I've tried to reproduce this issue with Edge and Yahoo news. As I can see, `dns-prefetch` elements were removed, and the browser didn't try to resolve DNS queries.
If I disable filtering rule for this element with whitelist rule `@@||btrll.com^`, I can see DNS requests for `*.btrll.com`.

I've also tried to do the same trick with `Firefox` browser and I can see DNS requests to `*.btrll.com`

Maybe I don't fully understand what the problem is, explain issue details please.

**Comment by TPS** [comment]
Ever since https://github.com/AdguardTeam/AdguardForAndroid/issues/2955#issuecomment-572675309, this is working correctly/as expected, which leads me to believe there's some problem with my configuration which has caused this.  Until it's tracked down, I'll close.

**Comment by ameshkov** [comment]
Please note that on your screenshots there are no issues -- AdGuard has removed the elements and it happened before browser could learn about them and try DNS prefetching, hence no DNS queries in the log.

**Comment by TPS** [comment]
That's correct, when I was running Edge, always.  Previous to my AG settings reset, Ff Focus wasn't even generating DNS requests (per log) for `*.btrll.com` — clearly impossible, as it was serving ads from there via those elements.

Now, all is well, so something in my legacy config must've been breaking this.
