### ISSUE TITLE
AT&T sms issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#33]
The same issue we have fixed for Verizon and T-Mobile in Adguard 1.0.
For some reason IPSec packets are routed through the VPN.

We should check the endpoint IP in these packets and exclude the subnetwork.

It seems that AT&T uses public subnetwork for IPSec.

Here is a packet:
04:38:33.687 [Thread-171] ERROR c.a.a.f.packet.PacketFactory - ESP (50) over IPv6 is not implemented.
04:38:33.688 [Thread-171] WARN  c.a.a.f.packet.PacketFactory - Packet [96, 0, 0, 0, 3, -60, 50, 64, 38, 0, 3, -128, -116, -85, 118, 27, -43, 72, 111, -82, -16, -62, -85, -121, 32, 1, 24, -112, 1, -8, 32, -126, 0, 0, 0, 0, 0, 1, 0, 2, 0, -74, -127, -64, 0, 0, 0, 24, 55, -61, 123, -105, -16, 103, -41, -101, -87, -75, 77, 60, 87, -21, -75, 6, 17, -119, -103, 47, 50, 103, 114, 75, 37, 26, -124, 76, -112, 79, 94, -118, 121, -101, 100, -52, 74, -27, 48, 94, -41, -26, 114, -8, -67, -74, 111, 55, 35, -76, 84, -65, -118, 49, -114, -116, -73, -27, -127, -121, 40, -5, -7, 112, 111, 112, 15, 75, -31, -61, 92, -32, 55, 8, -70, -111, 35, 111, -121, 56, 51, -91, 110, 92, 48, -14, -77, -43, 29, -100, -38, -92, 97, -102, 61, 104, 97, -31, -56, 123, -124, -113, -107, 78, -60, -56, 99, -46, -107, 5, 87, -100, 77, 108, 124, 122, -26, 75, -45, 49, 90, 51, 42, -46, 76, -22, -125, -33, -71, 39, -113, 15, -126, 72, -75, -23, 45, 76, 113, 106, 64, -76, 38, -84, -70, -92, 127, -36, 45, -75, 84, -103, 64, -109, -22, 57, 13, 59, -74, 102, 63, -36, -107, 115, 18, 63, -94, -65, -99, 53, 42, 65, -45, 17, 29, -3, -37, 102, -90, 84, -39, 48, -94, -1, 6, 99, -47, 30, -42, -33, 122, -106, 17, 57, -13, 53, 0, -84, -109, -64, 103, 119, 96, -64, -126, -122, -17, -34, 73, -39, -107, 101, -113, -110, -115, -85, -105, -120, 35, 2, 34, 111, 87, -68, 85, 38, -11, -86, 58, 87, 88, -97, 16, -46, 125, -37, -86, 123, 80, -90, 32, -35, -73, 85, 91, 122, -18, 23, 79, 20, -14, -57, 9, 123, -74, -71, -25, 2, 23, 49, 27, 94, -122, 85, -18, 19, 7, -115, -81, -50, -85, 40, -32, 47, -21, 11, -47, -74, 15, 60, 55, -34, -21, -71, -90, 75, -110, -13, -79, 47, 116, 114, -88, -126, -77, 59, -66, 27, -67, -48, -100, -27, -114, 51, -47, 27, -74, 4, 32, 28, -120, -39, -48, -74, 9, -80, -17, -39, 36, -123, 118, -74, 77, -99, -89, 43, 66, -53, -10, -80, 30, 69, 96, -75, 9, 61, 27, 28, 38, 74, 118, -118, -13, -6, -18, -72, 40, 96, -13, 104, 123, 15, -1, -119, 53, -65, 92, -85, 85, 78, 60, -107, 13, -117, 0, 110, -63, 55, -112, 27, 17, 15, -94, -39, -28, -105, -52, -71, -65, -19, 81, 55, -80, 80, -83, 28, 106, 84, -48, 52, 121, -23, -113, 96, 45, 56, -13, -60, -96, 118, 120, 3, 106, -6, 40, -7, 112, -78, 96, -126, -18, 9, 13, 96, -71, 103, 60, 24, 41, 26, -59, 121, -46, -89, 95, -45, 40, 86, 63, -43, 6, -57, -16, -57, 10, 9, 1, -15, -83, 114, -37, -110, -14, 69, 2, -98, 91, 95, 57, 21, 41, -112, -31, 30, 23, -33, 122, -103, -72, 31, 21, 76, -75, 86, 45, -84, -67, 83, 33, -121, 10, -69, 123, 94, 112, 7, 13, 127, 23, -79, 100, -114, 50, 60, -104, -30, 125, -69, 37, -80, 47, -39, 121, -1, 59, 87, -67, -60, 0, 20, -48, -44, 97, 16, -44, -126, -64, 48, -94, 83, 64, -81, 107, -125, -52, 71, 100, -1, 26, -68, -6, 65, -24, -5, -76, -37, -93, -21, -95, 97, -82, -100, 48, 124, 10, 99, -69, -19, -28, -100, -85, -28, 77, -71, 122, 27, -69, -7, -97, 23, -68, 103, 62, -80, 89, 86, -56, -52, 39, -22, -62, 40, 61, -83, 57, 68, -112, 5, 28, -81, 56, -56, 6, 33, -85, -75, -43, -32, 98, 92, 108, 19, 38, -4, -33, 39, 120, 74, 37, 49, 68, -109, -106, 36, 125, -121, 51, 36, 74, -35, 124, -20, -57, 21, -59, -10, 119, 46, -112, 105, 82, 66, -1, -113, -52, -24, -119, 67, -44, 5, 66, -49, -68, -98, -75, -24, -9, -43, 125, -21, 49, 66, -64, -79, -93, -107, -45, 69, 64, -68, 9, 111, 123, -9, 58, 21, -13, -28, -98, 13, 30, -87, -38, -48, -115, 16, -48, -112, 8, 120, -2, 36, 46, -44, -100, 89, -9, 73, 14, -27, -51, 7, 120, 40, 55, -7, 83, 59, 29, -41, 0, 68, -32, -54, 126, 80, 48, -73, -90, -52, -62, 25, 118, -67, -61, 124, -36, -115, -14, 72, 95, 22, 118, -102, 114, 3, -100, 46, -51, 65, -32, 29, 73, -60, 120, 95, 58, -94, -29, 40, -128, -89, 35, 89, -128, -67, -97, 14, -123, -66, 30, -125, 60, 33, -123, 90, -3, -72, 28, -119, 72, -118, 31, -53, -25, 84, 8, 123, 43, -16, -19, -103, -72, 113, 75, 66, 103, 94, 108, -44, -46, 50, 18, 51, -85, 91, -127, 100, -117, -122, 23, -49, -76, 33, -56, -20, 111, -20, -87, 31, -63, 108, 71, 101, -110, 65, 99, 105, 10, -77, -51, -116, -92, 18, -48, 20, -61, -123, 126, -117, 95, -40, 45, 57, 10, 31, -38, -104, -44, -40, 121, 34, 77, -94, 117, -108, -106, 46, -9, -9, -89, -82, -87, -74, -80, -41, -36, -89, 23, -94, -23, -35, -8, -1, 75, -79, -34, -43, -63, -23, -9, 28, -28, 125, 26, -96, 58, -60, 3, 83, -49, -128, -128, -68, -78, 3, 38, 22, 120, -57, 58, 71, 2, 52, 68, 2, 110, 29, -110, 35, 56, -28, -84, -17, 106, -127, 55, 9, -89, 101, 113, -90, -107, 53, -39, 51, 47, -26, -76, 111, -107, 69, 90, 103, -123, -50, 122, 52, -4, -7, 77, 90, 62, -81, 34, -105, -21, 50, 97, 66, 49, 54, -44, -11, 19, 97, 113, -44, 102, -80, 85, 54, -82, 101, -54, -1, 124, -127, -64, -104, 83, 47, 70, -65, -35, -41, 83, -93, -106, -12, 14, -127, -4, 121, 86, -122, -68, -71, 52, 14, -107, 49, -76, 107, -79, 113]
04:38:35.723 [Thread-171] ERROR c.a.a.f.packet.PacketFactory - ESP (50) over IPv6 is not implemented.
04:38:35.725 [Thread-171] WARN  c.a.a.f.packet.PacketFactory - Packet [96, 0, 0, 0, 3, -60, 50, 64, 38, 0, 3, -128, -116, -85, 118, 27, -43, 72, 111, -82, -16, -62, -85, -121, 32, 1, 24, -112, 1, -8, 32, -126, 0, 0, 0, 0, 0, 1, 0, 2, 0, -74, -127, -64, 0, 0, 0, 25, -38, -17, 14, -68, -55, 126, 57, -19, 89, -111, 72, 18, 58, 58, -97, -3, 76, 86, -87, 67, -32, 22, -98, 71, -42, 102, 88, 16, 36, 100, -59, -69, 4, -44, -62, 34, 90, -90, 46, -16, -111, 81, -86, 80, 74, -56, -72, -20, -50, -41, 79, -10, -53, 103, 40, -110, -38, -49, 38, -30, 49, 63, -63, 58, -63, 59, -57, 19, 82, 101, 88, -1, -40, -38, 7, 42, -22, -84, -103, 78, 60, -99, 4, 88, -15, -92, -47, 64, -120, -81, 127, -2, 30, -52, -47, -123, -92, 59, 98, -83, -104, -86, 31, 119, -123, -74, -58, 56, -69, 110, 45, 92, 49, -22, 76, -13, 58, -6, 14, 108, 87, 9, 116, 6, -67, -66, 14, -113, -119, 30, -32, -15, 17, 115, 124, 24, -63, 91, 115, 104, 126, -51, -60, -16, -31, 126, -9, 127, -34, -98, 32, 73, 102, -42, -77, -55, -105, -119, 106, 9, 21, 33, 31, 55, 14, 111, 68, 40, 35, -58, 64, -86, -113, 36, 39, -15, 44, -97, -69, 110, 112, -124, -34, -55, 29, -27, -17, -73, 55, -54, -48, 54, -46, -122, 25, -86, -128, 111, 12, 52, -16, -71, 7, -34, -33, -14, 120, 59, 124, -34, -73, 127, -71, -10, 27, -67, -40, 112, -26, 92, 1, -75, 104, -30, 10, 91, -45, 50, 12, 106, -39, 22, -20, 108, 112, 119, -122, 8, 86, 63, -72, 88, -106, -25, -112, 99, 57, -113, 62, 113, -48, 99, -66, -34, -97, -34, 69, 124, -68, 103, -99, -74, 0, -113, -43, 49, -120, 29, -91, -103, 10, -104, -59, -31, 66, -63, 52, 56, 30, 23, -4, 65, -17, 70, -48, 109, 78, 126, -112, 25, -77, 101, 25, -60, 94, 38, 98, -56, 16, 33, -30, -20, -104, -62, 65, -124, 35, -83, -80, 115, -22, 127, 37, -103, 57, -111, -78, -33, -52, -70, 42, 16, -112, 23, 5, 10, 86, 126, 80, 12, 9, 13, 60, 50, -79, -105, 85, 120, 61, 110, -73, -125, 2, 65, -47, -95, 86, 62, -28, -103, 46, -30, 55, -75, -45, 46, -65, 96, 5, 102, 32, -12, -27, 93, -93, -110, 101, -111, -36, -57, -5, 66, 83, 77, -67, -7, -107, -35, 63, 12, -39, 73, -109, -50, -122, 113, -100, -30, -12, -25, 35, 93, 55, -21, -65, -40, -127, 105, 78, -125, 19, 45, -104, 27, -45, 117, 109, -65, -87, -93, -3, 45, -84, -51, -109, 89, -45, -46, 10, 3, 118, 82, -69, -94, -6, 59, 16, -70, -18, 79, 105, 85, 71, -39, -31, 104, 14, -59, -14, 61, -63, 45, -51, 47, -68, 16, -80, 126, 65, 93, 58, -22, 101, -56, 63, 75, -101, -96, 39, 39, 93, -126, 106, 112, 95, 113, 14, -118, 8, 113, 110, -24, 36, -48, -88, -39, -94, 99, 12, 33, 76, 27, -86, -3, 28, -22, -125, 70, -18, 120, -39, 109, 23, -78, 15, 96, -84, -55, 64, -126, -51, -64, -53, 0, 114, -104, 93, 15, -121, 55, 59, 65, -39, -23, -5, 125, 77, 58, 92, -22, -47, -6, 108, 60, 43, 86, 60, -102, -110, 68, 32, 21, 20, -125, -24, 11, -77, -28, -76, -56, -42, -48, 52, 0, 105, 95, 113, -82, -95, 26, 45, -90, 99, -121, -122, 107, -86, -41, -31, 53, 77, -60, -92, -28, -120, -44, 74, 1, -78, -73, 109, -128, -46, -88, -70, 118, -78, -101, 72, 69, -114, 52, 92, -45, -111, -66, -113, -28, 60, -89, -65, -80, -40, -67, 47, 18, 54, -30, 126, -88, 92, -49, 112, 118, 7, -124, -54, -110, -41, -75, -80, -101, 40, -55, -128, -64, 65, -108, 86, -44, 59, -49, 14, -12, -59, -93, 34, 36, 61, 87, 0, 125, -126, 55, 46, 21, -118, -128, 104, -95, -48, 96, 12, 75, 58, -15, 122, -79, -122, -51, -118, 22, -60, -125, 31, -22, -71, 91, -81, -29, -117, -2, 1, 67, 89, 80, -119, 100, 58, -97, 108, -35, -22, 56, -97, 62, 23, 4, 60, 121, -48, 38, -127, -61, -126, 73, 79, 62, 60, 74, 45, 123, 89, 88, 97, -68, 74, 46, -115, -50, -22, -116, 35, 114, -77, -112, -31, -69, 40, 24, -117, 20, -37, -58, -127, 113, -87, -110, -22, 106, -80, 26, 101, 10, -4, -85, -47, -22, 50, 89, -11, -20, -123, 32, 18, -37, 121, 25, -5, -68, -28, 12, 56, 118, 94, -90, 43, -27, -45, 41, -117, -8, -58, -115, 109, -120, 92, 120, -70, 88, -99, 81, 74, -43, 121, 35, 45, -108, -45, -117, -49, 90, -84, 63, -98, -32, 29, -105, 61, 21, 60, 24, -77, -94, 12, 14, 123, -61, -82, -94, -20, -23, 101, -21, -109, 78, -117, 20, -2, -1, 6, 48, 61, 112, 4, 48, -74, -98, -13, -88, 14, -82, -97, -5, 34, 14, 66, -99, -51, 20, 65, -57, -119, -93, 125, -93, 108, 85, -20, -101, -118, 53, -103, 51, 103, 37, -77, -96, -117, 56, 60, 55, 113, 33, -116, -89, -50, 114, 9, 97, -38, -40, -20, -2, 118, 87, -112, -22, -124, -41, 13, -75, 23, -86, -54, -111, -24, 87, -71, 122, -56, -95, 99, 54, -25, 81, -59, 36, 74, 35, 61, 37, 96, 39, 12, -96, 127, -23, 122, -18, 28, -36, 112, 104, 54, -115, 61, -124, -115, 59, -26, -126, -37, 58, 49, 29, 57, 47, -75, 40, -48, -48, 36, -92, 53, -13, -40, 37, -62, -52, -3, 110, -121, -58, -23, -22, 9, -8, -57, -26, -46, 72, 95, 30, 93, -28, -45, 12, 75, -88, 72, 14, -43, 52, 23, -75, 92, -2, -127, -28, 22, 66, -31, 97, 3, -5]
04:38:39.763 [Thread-171] ERROR c.a.a.f.packet.PacketFactory - ESP (50) over IPv6 is not implemented.
04:38:39.767 [Thread-171] WARN  c.a.a.f.packet.PacketFactory - Packet [96, 0, 0, 0, 3, -60, 50, 64, 38, 0, 3, -128, -116, -85, 118, 27, -43, 72, 111, -82, -16, -62, -85, -121, 32, 1, 24, -112, 1, -8, 32, -126, 0, 0, 0, 0, 0, 1, 0, 2, 0, -74, -127, -64, 0, 0, 0, 26, -17, 87, 113, 46, -63, 18, -48, 48, -112, 80, -34, 31, -80, -92, -89, 66, -127, 66, 61, 64, -103, 6, 75, -22, 67, -107, -121, -121, 2, 32, 54, 114, 125, -102, -67, 85, -77, 31, -107, -36, -38, 29, 123, 59, 55, 63, 88, 13, 0, 71, -3, -57, -70, -67, 22, -127, 17, -59, 27, 20, -113, -44, -70, 15, -36, -62, -70, -10, -12, 48, 71, -72, -126, -97, -70, -9, -27, 55, 99, 96, 29, -110, -98, -69, 22, -67, 100, 115, 10, -65, 35, -103, 93, 118, 79, 20, -111, -33, -82, -102, 0, -22, -74, -121, -45, -124, -45, -21, -45, -25, -89, -100, -11, -109, -20, -115, 65, 54, 77, 125, -2, 6, -104, -63, 61, 6, 91, -64, -53, 20, -74, -82, 118, -25, 31, 26, 8, 17, 98, -88, -46, 49, -37, -88, -68, -95, 87, -5, 7, -35, 92, -104, 91, 11, 85, 76, -125, -128, -87, -38, 97, -79, 122, -9, 62, 37, 59, 59, -27, 38, 123, 29, -103, -60, 106, -43, 37, 55, -71, -92, 75, 43, -69, 74, -71, 87, 105, -104, -123, 87, 8, -87, 116, -62, -1, 64, -86, -27, -82, -96, -30, -32, 119, 67, 13, 83, -97, -26, 68, -118, 7, 120, 7, 116, 81, 88, 107, -40, -114, -30, -53, -98, 2, -35, 57, 64, 10, -39, -121, 71, 89, 12, 83, -27, -67, -16, 8, 1, -56, 88, 0, -77, 86, -2, -77, -54, -33, 66, 32, -60, 114, -110, 15, -128, -36, 12, -79, -120, 126, 65, -46, 103, 51, 0, 125, 81, 50, -86, -121, -43, -4, 122, -59, -68, -106, 87, -31, 94, -58, -74, 67, -48, 33, -5, -25, 73, -91, -46, 85, -75, -23, -114, 115, 79, 124, 89, 33, -120, 92, 47, 7, 121, 81, 79, 80, 125, -9, 114, -42, -92, 30, 6, 68, -89, 78, 94, -125, -62, 36, 9, 87, -40, -33, 125, -11, 91, -27, -112, 58, -111, 50, -93, -6, -39, -108, -61, -95, -56, -119, 14, -13, 88, 55, -77, -44, 101, 97, 21, 100, -56, -109, -16, -114, -105, -16, 90, -40, -15, 123, 84, -102, 109, -96, -128, -88, 42, 101, 49, -70, 61, -19, -101, -127, -87, -108, -66, 4, -40, -73, 110, -54, 2, 3, 83, -75, 100, -43, -81, 22, -93, 3, -90, 11, -85, -90, -24, -92, -2, -32, -125, 109, 69, 118, -32, 81, 60, 6, 64, -30, -84, -49, -76, -23, 126, -31, -61, 28, -72, -102, -35, 127, 126, -65, 109, 66, 65, -50, -95, -112, -124, 114, -110, -39, -128, -36, -76, 88, 112, 80, -104, 73, 115, -82, 120, -72, 14, 107, 106, 81, -70, -64, 47, -29, -65, 48, 96, 10, 75, -73, 85, -68, 74, 97, -27, -11, 66, 113, 35, 119, -77, 96, -12, -100, -29, 57, 113, -115, -39, 111, -43, 44, -41, 117, 9, 29, 95, -13, -79, -34, 17, -122, 25, -97, -27, 97, 23, 104, -46, 69, -35, 95, 17, 70, -87, 94, 15, -32, 41, 59, -126, 10, -88, -50, -98, -18, 57, 89, -99, 32, 28, 28, -100, 81, 35, 75, 36, -56, 83, 117, -32, -114, 96, -90, 30, -112, -31, -55, -24, -76, -44, 44, -8, 118, -117, -97, 3, -125, -15, -91, -93, 117, 42, -108, -119, 14, -55, -50, -127, 2, 0, -15, 75, 86, 70, -53, 87, -106, -55, -16, 37, -68, -94, 108, -100, 24, 84, 110, 117, -106, 118, 67, 124, 32, -69, -11, 28, 108, 58, 120, 98, 2, -43, 80, -39, 16, -25, 125, -103, -120, 48, -6, 31, 46, -18, 108, 57, 62, 49, 112, -84, -49, 81, -128, 87, 24, 85, 4, -73, -21, 109, -87, -67, 10, -45, 99, 117, 25, 107, -79, -43, -1, -60, -105, -83, 87, 53, 67, 123, 82, -98, 84, -55, 103, -107, 56, 9, -9, 109, 37, -71, -79, -69, 87, -112, 18, -40, -59, 96, -7, -50, 61, 24, 34, 58, -108, 76, -93, -126, -119, -7, 126, -79, 62, 81, -79, 115, 118, 84, 6, -105, -25, -68, -116, -125, -21, -29, -14, -114, 90, -16, 119, 101, -16, -15, -70, -128, -74, -75, -8, 125, -98, 127, -105, 53, -74, -68, -6, -65, -13, -99, 26, -47, 21, -47, 121, -30, -45, 52, -119, -73, 18, -115, 56, -37, 87, 109, 95, -32, -30, 123, 60, -67, -111, 0, 106, 59, 75, -95, -127, -38, 24, -106, -104, -79, -11, 21, -44, -71, -128, -95, -115, -85, -90, 36, 77, -53, 24, 90, -117, -10, -87, 21, 23, 37, 46, 113, -89, 118, 12, 4, -47, 60, 88, 109, 26, 10, -91, -38, -43, 20, 30, 41, 95, 36, -87, 61, -62, 118, 28, -21, 29, -52, 48, -5, -125, -35, -17, 112, 47, 72, 83, -90, 45, -29, 60, -91, 14, -72, 36, 62, -19, -8, -37, 111, -118, -9, 84, 68, -48, 31, 22, 100, -63, 65, 90, 66, 48, 15, -32, 73, -3, -4, 108, 120, 94, 98, 109, -47, -89, 95, 122, 91, 122, -120, -25, -90, 82, 121, 99, -3, 58, 99, 74, 87, -113, 117, -22, -48, -55, -57, 0, -49, 27, 115, 65, -39, -118, 103, -105, 86, -110, 14, 57, 45, -26, 25, -120, 124, -23, -97, -19, 12, 60, 68, 94, 105, -10, 19, -36, -43, 25, 63, 69, -52, -23, 114, -22, -12, -112, -98, 123, -18, 70, 79, 126, -105, -68, -10, 17, -82, 12, -35, -42, 122, 125, -100, -95, 77, -60, 10, 94, -69, 22, 83, 35, 90, -115, 22, 32, 31, 101, 76, -6, 37, 57, 69, 90, 39, -72, -52, -100, -16, 102, 100, -31, -15, -7, -54, -125, 29, 16, 25, 28, 93, -38, 24]

**Comment by TPS** [comment]
Is this same or different than #30?

**Comment by ameshkov** [comment]
Maybe the same, at least I see the same IPSec packets errors in the #30 log

**Comment by ameshkov** [comment]
source address: 2600:380:8cab:761b:d548:6fae:f0c2:ab87 
dest address: 2001:1890:1f8:2082:0:0:1:2

**Comment by ameshkov** [comment]
Log from #30:
src=/2600:380:62f1:b363:9d98:c633:67b1:2583
dst=/2001:1890:1f8:2074:0:0:1:1

**Comment by Revertron** [comment]
Waiting for testers to test.

**Comment by vbagirov** [comment]
Logs from user: https://www.dropbox.com/s/wiy0gtvhh6ehece/QMQ-761-29241%20-%20logs.txt?dl=0
Also state.txt: https://www.dropbox.com/s/8m67vhtn0ch5di6/state.txt?dl=0

**Comment by ameshkov** [comment]
IPSec packets again, seems that our route is not enough.
@Revertron parse it and see what's the endpoint (and look at the source too)

**Comment by Revertron** [comment]
From new logs:
src: 2600:0380:4abc:59b3:79ae:1ecd:2c96:f3c5
dst: 2001:1890:1f8:20e0:0000:0000:1:2

Something is wrong with the exclusion...

**Comment by Bohdan-SUP** [comment]
Please check new logs in ZSK-316-32801

**Comment by Revertron** [comment]
@Bohdan-SUP The same src/dst networks in new logs. Thanks, but we have all the info to hunt the bug down...

**Comment by ameshkov** [comment]
@Bohdan-SUP temporary workaround:
1. Install the latest beta
2. Go to "Advanced" - "Low level settings"
3. Switch "pref.vpn.ipv6.bypass" to true

@Revertron, are you sure the new routes were applied in the latest log?
Please check this, maybe we have not detected AT&T properly.
If so then maybe we should forcibly bypass ipv6 for AT&T?

**Comment by ameshkov** [comment]
@Revertron any update on this?

**Comment by ameshkov** [comment]
Ticket with update: JKM-539-43556
Bypassing IPv6 does not help with SMS/MMS

**Comment by ameshkov** [comment]
@Revertron 

Bypassing IPv6 helps.

So we should change the routes for AT&T - simply bypass ipv6 and that's all.

**Comment by Revertron** [comment]
Added bypassing IPv6 routes and logging of the AT&T network.
