### ISSUE TITLE
Impossible to update

### ISSUE THREAD

**Issue by Azertixe** [AdguardTeam/AdguardForAndroid#3300]
Hello. I have a notification for update the app but it doesn't work.
Update is downloaded but installation fails.
I tried to close Adguard before update but i have the same issue :'

Thanks

**Comment by artemiv4nov** [comment]
@Azertixe 
Hi!
What version do you have in the app?
What channel did you choose in the app?

**Comment by Azertixe** [comment]
Hi. I am in 3.2.150
Version channel

Lanza Bertucci-Domergue


---- Message d'origine ----

**Comment by jjt00** [comment]
Are you using the official Adguard APK?
If you're using a cracked/mod APK, then this might be the cause of not being able to upgrade the app.

**Comment by Azertixe** [comment]
Hello. Yes it's official app. Each time i want to update i needed to desinstall, download AdGuard apk on official website and reinstall.
But i loose all my custom paràmetres :(

Thanks 

Lanza Bertucci-Domergue


---- Message d'origine ----

**Comment by jjt00** [comment]
Losing your settings is not how it should be, but you can export your setting first before updating, then importing your settings again after updating. It's a workaround, but it works.

**Comment by Azertixe** [comment]
Hi. Yes i saw this possibility recentlty. Do you think there is a durable solution? 
Thx

Lanza Bertucci-Domergue


---- Message d'origine ----

**Comment by ameshkov** [comment]
Tbh, we've seen a couple of cases when the app couldn't be installed or updated due to some random Android bug and the only thing helped was installing it via adb. Also, sometimes, rebooting the device helps.

**Comment by artemiv4nov** [comment]
@Azertixe ,
Please, download the latest release from our website: https://adguard.com/en/adguard-android/overview.html
