### ISSUE TITLE
Unable to install certificate on Honor 7A automatically (root)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3302]
### Issue Details

- **AdGuard version:**
  - 3.4.7 nightly
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Honor 7A
- **Operating system and version:**
  - Android 8.1.0
- **Root access:**
  - No

### Expected Behavior

Certificate should be available to install.

### Actual Behavior

Certificate refuses to be installed.

### Screenshots

N/A

### Additional Information

Logs: 
[adguard_logs_3.4.7_0501_145520 (1).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4042025/adguard_logs_3.4.7_0501_145520.1.zip)
Helpdesk ID: 2474473

**Comment by ameshkov** [comment]
> Certificate refuses to be installed.

I don't understand what exactly is happening

**Comment by ameshkov** [comment]
Ah, that's an automatic installation with root?

**Comment by ameshkov** [comment]
@artemiv4nov could you please check the logs?

**Comment by artemiv4nov** [comment]
This log doesn't contain any information about the certificate installing. It looks like an Android ROM's problem. @akmLaVx is the user has a problem yet?
