### ISSUE TITLE
Add a smaller, minimal notification

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3303]
### Problem Description

"Protection enabled" notification in notification area is perceived as too large by some users.

### Proposed Solution

Create a minimal notification like this one:

<details><summary>Mockup</summary>
![mockui](https://user-images.githubusercontent.com/33634917/72203289-364aa880-3472-11ea-85b7-2be48ff96368.png)
</details>

### Alternatives Considered

Allow users to hide "Blocked xxx ads" from the notification.

### Additional Information

Submitted by: 1603163

**Comment by ameshkov** [comment]
The notification is configurable: go to notification settings, make it "Silent" and check "Minimize".
