### ISSUE TITLE
com.scee.psxandroid - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3305]
@adguard-bot commented on [Sat Jan 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47050)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.scee.psxandroid](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.scee.psxandroid)
### Comment
Username: @Rakleed
> Приложение не позволяет делать нормальные скриншоты. Но при первом открытии приложения и нажатии Sign In to PSN при включенном AdGuard появляется просто белый экран, при отключении AdGuard — страница авторизации с полями ввода логина и пароля.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/llcIdzn.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/llcIdzn.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 3.3.1 (229)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your User-Agent ()
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

---

@Rakleed commented on [Thu Jan 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47050#issuecomment-570783504)

Тоже проблема с фильтрацией HTTPS.
<details><summary>Screenshot:</summary>

![Screenshot_PS_App_20200104-155449](https://user-images.githubusercontent.com/19418601/71765886-de102580-2f0a-11ea-9434-52e9de41f7d0.png)
</details><br/>

---

@Alex-302 commented on [Thu Jan 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47050#issuecomment-572521334)

Не повторяется. @zloyden проверь у себя.

---

@zloyden commented on [Thu Jan 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47050#issuecomment-572536304)

Фильтрация HTTPS по-умолчанию выключена для этого приложения, у меня не повторяется. @slavaleleka посмотри у себя.

---

@slavaleleka commented on [Fri Jan 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47050#issuecomment-573129763)

у меня тоже не повторяется

@Rakleed если HTTPS-фильтрация включена — [отключите ее](https://uploads.adguard.com/slbdzd8ligdmk.png)

---

@Rakleed commented on [Fri Jan 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47050#issuecomment-573148606)

@slavaleleka по умолчанию для этого приложения была включена фильтрация HTTPS.

**Comment by Alex-302** [comment]
@Rakleed Нужен отладочный лог
https://kb.adguard.com/ru/android/solving-problems/log#debug

**Comment by TheHasagi** [comment]
Для этого приложения нужно отключить HTTPS фильтрацию (AdGuard - Apps management - PS app - Фильтрация HTTPS - отключить), после чего перезапустить.

**Comment by Rakleed** [comment]
@TheHasagi проблема в том, что для этого приложения по умолчанию не отключена фильтрация HTTPS.

**Comment by TheHasagi** [comment]
@Rakleed 

[Issue](https://github.com/AdguardTeam/AdguardForAndroid/issues/3306) created.

**Comment by Rakleed** [comment]
@Alex-302 отправил логи, id 939612.
