### ISSUE TITLE
Add "outbound" HTTPS proxy support

### ISSUE THREAD

**Issue by ngorskikh** [AdguardTeam/AdguardForAndroid#3307]
See core/pull-requests/1663

HTTPS means "HTTP over TLS".

What can/should be configured:
* Hostname
* Port
* Username / password
* Verify certificate (true by default)

How to test:
You can setup gomitmproxy, it can work as an HTTPS proxy: https://github.com/AdguardTeam/gomitmproxy/tree/master/examples/mitm

**Comment by artemiv4nov** [comment]
The task has already been implemented in the 3.4.
