### ISSUE TITLE
Using AdGuard w/IPv6 internet causes significant app lagging

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3309]
### Issue Details

- **AdGuard version:**
  - 3.3.229
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Motorola Moto X4
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Reproduction
1. Must have an IPv6-enabled router and IPv6-compliant ISP
2. Switch to IPv6 through your router
3. When protection is enabled, all applications will start exhibiting a 10-15 second lag
4. Switch back to IPv4
5. Apps work without delays

### Expected Behavior

Using IPv6 shouldn't cause severe lags

### Actual Behavior

When IPv6 is enabled, apps exhibit a 10-15 sec lag

### Logs

Logs are in ncloud.

### Additional Information

Submitted by user 1667299.

**Comment by ameshkov** [comment]
It seems something is wrong with the connection to the IPv6 address of dns.adguard.com.

This is not a bug, the issue will go away if the user switches to a different DNS resolver for instance.

Could you please ask what ISP does the user have?

**Comment by ogpvp** [comment]
The ISP is Comcast.

**Comment by ameshkov** [comment]
@ogpvp hi! Does the issue go away if you choose a different DNS server or use the system default DNS?

**Comment by ogpvp** [comment]
I am using the default DNS. I have not tried using a different DNS.

**Comment by ameshkov** [comment]
That's not what I see in the log.

**Comment by ameshkov** [comment]
Or do you mean AdGuard DNS as a default DNS? Try disabling DNS filtering completely just in case.

**Comment by ogpvp** [comment]
I just put in the AdGuard DNS in the modem and even without AdGuard running on my android, the same lag occurs.

**Comment by ogpvp** [comment]
Disabling DNS filtering in the AdGuard app on android fixes the lag. I have IPV6 on and AdGuard running without DNS filtering right now with no lag.

**Comment by ogpvp** [comment]
I had never messed with DNS on the modem until now. Also I had been using AdGuard DNS filtering on the android for a while because my license ran out. I never turned it off when I got my lifetime license. Will AdGuard work just as good without DNS filtering?

**Comment by ameshkov** [comment]
> Will AdGuard work just as good without DNS filtering?

No, DNS filtering is rather important if you don't have a license. 

The only thing I can't understand is why DNS filtering causes this. Could you please confirm that if you use a regular DNS server in your router, there's also no problem even if you keep DNS filtering enabled in AdGuard?

**Comment by ogpvp** [comment]
My actual router does not even offer DNS settings. The modem has been on default and is back on default now. ( I just tried AdGuard DNS when posting here earlier). As soon as I turn on DNS filtering in AdGuard the lag returns. 

Well, I found the issue. It is the DNS over HTTPS option when choosing the AdGuard DNS settings. If I choose regular AdGuard DNS, no lag. AdGuard DNS over HTTPS, lag.

**Comment by ameshkov** [comment]
> AdGuard DNS over HTTPS, lag.

What about Cloudflare DNS-over-HTTPS or Quad9 DNS-over-HTTPS? Any lag with them?

**Comment by ogpvp** [comment]
Cloudflare HTTPS does lag. Quad9 HTTPS does not lag.

**Comment by ameshkov** [comment]
Hmm, I really don't understand what's wrong, maybe IPv6 connectivity is somehow broken in your network.

All three (AG, CF, Quad9) have IPv6 addresses so there should be no difference:(

**Comment by ogpvp** [comment]
I don't understand either. I had switched to HTTPS over DNS a good while back. Then when I turned on IPV6 because ISP brought me a new modem and the issues were gone...... that is when the lag started on my android. It is not really a big deal to me. I am not one of those that thinks any DNS needs to be HTTPS. Do not want to get into that whole discussion any way. 

I would like to ask though, is the DNS filtering really needed for AdGuard if I have lifetime license?

**Comment by ameshkov** [comment]
> I would like to ask though, is the DNS filtering really needed for AdGuard if I have lifetime license?

DNS filtering is not needed, but it provides some nice perks like, for instance, encrypting your DNS traffic and hiding it from your ISP.
