### ISSUE TITLE
Turn off AdGuard protection for ru.rostel app

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForAndroid#3310]
@adguard-bot commented on [Mon Jan 13 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47608)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=ru.rostel](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.rostel)
### Comment
Username: @LordRomzessV
> При включенной фильтрации сходу блокируется доступ к сервису авторизации приложения Госуслуги. Проблема повторяется более полугода независимо от провайдера и модели смартфона.
> 
> Сегодня заметил, что окно авторизации начинает отображаться корректно, если войти в приложение, перейти к экрану входа, увидеть "ошибку сети", свернуть приложение и снова развернуть.
> 
> Однако с отключённым Adguard проблем вовсе не возникает.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ErkUmLu.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/3sT67c8.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3.1 (229)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> (Obsolete) Prebake, <br/>Fanboy's Cookiemonster List, <br/>Fanboy's Annoyances, <br/>AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/> Spam404, <br/>Malware Domains Blocklist, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> YanFung mobile ads, <br/>AdGuard Russian
Other extensions used: | AVG Antivirus, но он редко когда включается - проблемы с автозапуском.

---

@Rakleed commented on [Mon Jan 13 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47608#issuecomment-573568286)

@LordRomzessV попробуйте отключить HTTPS-фильтрацию для данного приложения.

---

@slavaleleka commented on [Tue Jan 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47608#issuecomment-574110305)

@LordRomzessV к сожалению, отключение HTTPS-фильтрации не поможет, если ДНС-фильтрация включена и в качестве сервера выбран AdGuard DNS.

На данный момент есть 2 варианта, как решить эту проблему.

1. Полностью отключить защиту Адгарда для приложения:
Настройки приложений → Госуслуги → Защита AdGuard → откл

2. В настройках ДНС-фильтрации выбрать не наш сервер, а, например, системный или гугловый. Кроме того, в Пользовательский DNS-фильтр (Настройки → Фильтрация DNS → Блокировка DNS-запросов) надо добавить исключение
`@@||mc.yandex.ru^`

**Comment by TheHasagi** [comment]
It is disabled by default.
