### ISSUE TITLE
Connection problems caused by the SwiftKey application

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3314]
### Issue Details

- **AdGuard version:**
  -  v3.4 nightly 7 (23-1.5.165cl) (and the previos one)
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Xiaomi MI MAX 2 
- **Operating system and version:**
  -  7.1.1 

The user has noticed that the phone occasionally loses its connection. It happens for literally 2-3 seconds. Situation reproduced on Wi/FI and LTE networks.
Looking through the filtering log, he found a blocked request from the SwiftKey application.
They may be breaking the connection.

### Example of an error from the logs:

> 13:18:09.949 [Thread-14] INFO  com.adguard.android.filtering.dns.b - 3435#12733 [debug] github.com/AdguardTeam/dnsproxy/proxy.exchangeWithUpstream(): upstream https://dns.adguard.com:443/dns-query failed to exchange ;im.vk.com.	IN	 A in 9 milliseconds. Cause: couldn't initialize HTTP client or transport, cause: couldn't do a POST request to 'https://dns.adguard.com:443/dns-query', cause: Get https://dns.adguard.com:443/dns-query?dns=pQABAAABAAAAAAAACGlwdjRvbmx5BGFycGEAAAEAAQ: synthetic.wrap: all dialers failed to initialize connection: , cause: dial tcp [2a00:5a60::ad1:ff]:443: connect: network is unreachable (hidden: dial tcp [2a00:5a60::ad2:ff]:443: connect: network is unreachable, dial tcp 176.103.130.130:443: connect: network is unreachable, dial tcp 176.103.130.131:443: connect: network is unreachable)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/72731314-8cbb9380-3ba4-11ea-91c7-83bfe664adb2.png)

</details>

### Time of the issue
**Logs part one**: 20.01.20\12:12 
**Logs part two**: 20.01.20\13:08

### User name:
**T_sova** from Telegram
Two packs of Logs in NCloud

**Comment by ameshkov** [comment]
> cause: dial tcp [2a00:5a60::ad1:ff]:443: connect: network is unreachable (hidden: dial tcp [2a00:5a60::ad2:ff]:443: connect: network is unreachable, dial tcp 176.103.130.130:443: connect: network is unreachable, dial tcp 176.103.130.131:443: connect: network is unreachable)

This actually signals that the device simply is not connected to any network. I am not sure that we can do anything with this.

Just in case, ask him if the issue goes away if DNS filtering is disabled OR if the system DNS resolver is enabled.
