### ISSUE TITLE
Fix Cloudflare DoH address in DNS providers info

### ISSUE THREAD

**Issue by Termi79** [AdguardTeam/AdguardForAndroid#3317]
- **AdGuard version:**
  - 3.3.1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - different Motorola and Samsung devices
- **Operating system and version:**
  - Android 8.1 and Android 9
- **Root access:**
  - No

### Expected Behavior

Under DNS filtering Cloudflare DNS (DNS-over-HTTPS) is configured and should be used.

### Actual Behavior

Cloudflare DoH is not used, fallback on system DNS. Checked on https://1.1.1.1/help

### Additional Information

Adding Cloudflare DoH (https://cloudflare-dns.com/dns-query) as an own server manually in AdGuard fix the problem.

**Comment by admitrevskiy** [comment]
@Termi79 hi!
Thank you for reporting it.

Looks like they changed host for DoH server. Not so long ago it was `https://dns.cloudflare.com/dns-query`.

I think, we should use `https://1.1.1.1/dns-query` to prevent this problem from occurring in the future.

**Comment by Termi79** [comment]
Please add https://1.0.0.1/dns-query as well if you want to use IP adresses.

**Comment by sfionov** [comment]
Also https://1.1.1.1/dns-query is not acceptable for IPv6-only networks :)
May be https://1dot1dot1dot1.cloudflare-dns.com/dns-query ?

**Comment by gms77** [comment]
Still not fixed on Adguard 3.3.3
