### ISSUE TITLE
Show updates screen when "check for updates" shortcut is used

### ISSUE THREAD

**Issue by arunsathiya** [AdguardTeam/AdguardForAndroid#3318]
When I use the "check for updates" shortcut button/icon on my home screen, I expect the AdGuard updates screen to open and show the updates working. This used to be the behavior in the earlier version of the app.

In the latest version, that screen doesn't appear. Clicking the icon continues showing my home screen, and after a few minutes/seconds (depending on how long the update takes), a success message appears at the bottom of the screen.

In its current behavior, it's not clear if the updates have started. So, I ended up clicking on the "check for updates" shortcut icon multiple times.

Could we consider bringing back the old behavior where the updates screen is shown immediately? Or, at least a toast saying, "working on updates" as soon as the icon is clicked.

PS: I'm using the new GitHub android app to submit this issue, so, I'm not sure if we follow a certain issue template.

**Comment by artemiv4nov** [comment]
@arunsathiya Well, we can show a toast at the beginning of the checking. It should improve the user experience for this section.

**Comment by arunsathiya** [comment]
That would be great, @artemiv4nov!
