### ISSUE TITLE
com.vtosters.android - HTTPS issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3325]
@adguard-bot commented on [Sat Jan 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47054)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.vtosters.android](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.vtosters.android)
### Comment
Username: @Rakleed
> Проблемы с фильтрацией HTTPS у [VTosters](https://t.me/vtosters/872). Скорее всего те же самые, что и у официального приложения VK.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/vgvnD8F.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vgvnD8F.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 3.3.1 (229)
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your User-Agent ()
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

**Comment by artemiv4nov** [comment]
Приложение не принимать пользовательские сертификаты для шифрования трафика, это нормально.
