### ISSUE TITLE
Applications that do not trust user certificates (Notification)

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3328]
### Name and domain:
- Norton Mobile Security (developers.google.com, us.norton.com)
- Sophos Intercept X (4.sophosxl.net)
- WhatsApp
- Google Play Services (fonts.gstatic.com)
- Zomato (api.zomato.com)
- com.google.android.syncadapters.calendar

**Comment by sophisticated-zero** [comment]
+
Google Play services
Вконтакте
Яндекс.Диск
Issue: 2527105

**Comment by Eugene-Savenko** [comment]
Google Calendar Sync (calendarsync-pa.googleapis.com; googleapis.com)

<details>

![Screenshot_2020-02-01-09-15-46-469_com miui home](https://user-images.githubusercontent.com/15856304/73607564-3e54be80-45c0-11ea-9c32-f66a090b0869.jpg)

**Comment by sophisticated-zero** [comment]
SASystemProviders (dls-udc.dqa.samsung.com)
![Screenshot_20200201-184559_One UI Home (1)](https://user-images.githubusercontent.com/39196837/73609808-df03a800-45d9-11ea-914a-153109f27889.jpg)

**Comment by tprofi** [comment]
+Any PlayStation network services.

**Comment by Chinaski1** [comment]
**Note**:
- When receiving such requests, it is important to know if the root is used on the device.
