### ISSUE TITLE
io.olibra.bondapp - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3329]
@adguard-bot commented on [Wed Jan 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/48822)

### Issue URL (Incorrect Blocking)
[http://Bondhome.io](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2FBondhome.io)
### Comment
> Can't use bond home app on my phone to connect to the apps services to control my house fans. Only works when adguard is disabled. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/MLRMhYs.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/DadmLIk.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3.1 (229)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> I don't care about cookies, <br/>AdGuard Annoyances

---

@Alex-302 commented on [Wed Jan 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/48822#issuecomment-579828755)

Cannot reproduce without their device.

**Comment by Alex-302** [comment]
Cannot be checked without device.

**Comment by TheHasagi** [comment]
No problems found while bondapp usage. Seems like customer enabled force HTTPS filtering for the app (it should be disabled).
