### ISSUE TITLE
Individual userscript incompatibility

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3330]
### Userscript in question
[slickdeals_test.user.js.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4150286/slickdeals_test.user.js.zip)
Blocks tracking part of SlickDeals links to affiliate websites.

### Issue Details

- **AdGuard version:**
  - Initial report: 3.3 release, Reproduction: 3.4 nightly 7
- **Filtering mode:**
  - Local VPN, both
- **Device:**
  - Initial: Huawei BLA-A09, Reproduction: Sony Xperia XZ1 (G8342)
- **Operating system and version:**
  - Android 9 (both)
- **Root access:**
  - None

### Actual Behavior

Userscript works just fine on Windows but does not work at all on Android devices.

### Screenshots

None applicable.

### Additional Information

User ID: 2515659

**Comment by artemiv4nov** [comment]
@TheHasagi let's reproduce it

**Comment by artemiv4nov** [comment]
@TheHasagi can we reproduce it?
