### ISSUE TITLE
Unable to synchronize with Offline Maps & Navigation server

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3332]
### Issue Details

- **AdGuard version:**
  -  3.3.1(229.1.5.163cl)
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  ASUS ZB602KL
- **Operating system and version:**
  -  9
- **Root access:**
  -  No

### Actual Behavior

When protection is enabled, the application cannot connect to the server.
- HTTPS filtering for this app is off.
- DNS filtration is off.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/73825027-4bfe8400-480c-11ea-8de2-99f321ad56bc.png)

</details>

### Additional Information

**User ID**: 2514513
**Time of the issue**: 11:30/05.02.2020
**Logs in NCloud**
Link for [Download](https://play.google.com/store/apps/details?id=com.navigation.offlinemaps.gps) the app

**Comment by TheHasagi** [comment]
It works fine with the latest [nightly](https://agrd.io/android_nightly).
