### ISSUE TITLE
Add Firefox Preview Nightly for Developers to the list of browsers

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#3333]
Currently, premium is required to block ads there:
https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly

(My AG version: AG for Android v.3.31)

**Comment by TheHasagi** [comment]
@superlex 

Unfortunately, this browser does not accept our certificate and HTTPS can not be filtered by AdGuard properly.

**Comment by superlex** [comment]
@TheHasagi 
Yep, I know, but maybe it could be added to the known browser's list anyway.
See https://github.com/AdguardTeam/AdguardForAndroid/issues/2958 and https://github.com/AdguardTeam/AdguardForAndroid/issues/2861#issuecomment-558095498

**Comment by ameshkov** [comment]
@superlex sure, it should be added to the browsers list, but marked as not supporting HTTPS filtering (just like Opera for instance).

**Comment by superlex** [comment]
@ameshkov 
Yes, like Firefox Preview (org.mozilla.fenix) :)
Thanks
