### ISSUE TITLE
Add an option to stop filtering all ads on low battery charge

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3334]
### Problem Description

Some users are ready to sacrifice ad blocking to save on battery life. Except stopping the protection manually, AdGuard offers nothing.

### Proposed Solution

Add an option to automatically stop protection when battery level falls beyond a certain threshold.

### Alternatives Considered

Force stop ad blocking when battery level falls beyond a certain threshold.

### Additional Information

Reported by user 2535911.

**Comment by alexdonh** [comment]
In the mean time I believe you can use Tasker or similar to get this done using Automation API https://kb.adguard.com/en/android/solving-problems/tasker

**Comment by artemiv4nov** [comment]
Well, using the Automation API is a good way to solve this issue.
