### ISSUE TITLE
Adguard VPN falsifies the speed indicator download/upload function

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [AdguardTeam/AdguardForAndroid#3335]
### Issue Details

- **AdGuard version:**
3.3.229
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.3.229
- **Filtering mode:**
  Local VPN and I use "Content Blocking" only. I use only default settings.
- **Device:**
  Xiaomi Redmi Note 8 Pro
- **Operating system and version:**
  Android 9 (MIUI 11)
- **Root access:**
  No

### Issue

I use a speed indicator app like this to know how up-to-date my total speed (download + upload rate) is in the status bar when I download files with Firefox Android (68.4.2)

https://play.google.com/store/apps/details?id=com.internet.speed.meter.lite

The problem Adguard Android VPN distorts the display for speed indicator apps.

I have a 4G Wi-Fi router and the Note 8 Pro is connected to the 4G router via Wi-Fi. My data plans can only support a maximum of 21.6 MBit/s (2.7 MB/s) and the 4G reception is generally not good.

When I download without Adguard VPN file in the standard browser or Firefox Android. I only get the average total speed (0.7 MB/s to 1.5 MB/s). This is correct because the download is also finished in about 30 min with a 1.8 GB file.
https://download.fedoraproject.org/pub/fedora/linux/releases/31/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-31-1.9.iso

But when I activate Adguard Android VPN, the same file (1.8 GB) is loaded in 30 minutes. But the Speed Indicator app often displays values between 3.0 MB/s and 11 MB/s during download. This Speed Indicator app has an integrated function to know how much data was used. With Adguard VPN it distorts the measurement results. A 1.8 GB file download says I have 6.0 GB loaded. This is not true.

Something is happening with Adguard Android, that the speed indicator app do not show the correct total speed (download + upload rate) values anymore.

What is the problem?

I use Blokada and I don't have these problems. https://github.com/blokadaorg/blokada/releases/tag/4.5.2

**Comment by TheHasagi** [comment]
@USB3-2-10Gbit 

The application you've provided is not qualified to verify the speed of the internet connection. I've tried it to check how long it will take to download a 5 GB file (test link) without AdGuard and it showed a 3 KB/s speed, but file downloaded at 8 minutes.

For more information, you can read this [article](https://kb.adguard.com/android/solving-problems/battery).

**Comment by USB3-2-10Gbit** [comment]
> @USB3-2-10Gbit
> 
> The application you've provided is not qualified to verify the speed of the internet connection. I've tried it to check how long it will take to download a 5 GB file (test link) without AdGuard and it showed a 3 KB/s speed, but file downloaded at 8 minutes.
> 
> For more information, you can read this [article](https://kb.adguard.com/android/solving-problems/battery).

Here are current speed indicator apps. These apps work on current Android 10 version. Here you should see the correct values even without Adguard.

https://play.google.com/store/apps/details?id=com.nisargjhaveri.netspeed

https://play.google.com/store/apps/details?id=me.zheteng.android.powerstatus
