### ISSUE TITLE
Screening bypass function

### ISSUE THREAD

**Issue by luvs01** [AdguardTeam/AdguardForAndroid#3336]
In order to bypass address-based censorship in Korea, I wonder if it is possible to add features such as bypassing packet segmentation (aspear, splitting Client Hello packets containing SNI fields), and using vpn of tls-related packets. (intra)

**Comment by TheHasagi** [comment]
@luvs01 

We do not process packages and working only with regular sockets. For now, it is impossible to add such a feature.
