### ISSUE TITLE
Implement Protection Restart when excluded App is installed 

### ISSUE THREAD

**Issue by vyanovsky** [AdguardTeam/AdguardForAndroid#3340]
Problem's Sequence:
* Turn AG Protection ON
* Install App from Google Pay e.g.: com.nttdocomo.keitai.payment
* AdGuard tries to restart the Protection
* Checks hashes
* Hashes didn't change
* Protection doesn't restart

**Comment by artemiv4nov** [comment]
Fixed in 3.3.2 release
