### ISSUE TITLE
Network shutdown when protection is activated

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3342]
### Issue Details

- **AdGuard version:**
  -  3.3.229
- **Filtering mode:**
  -  VPN
- **Device:**
  -  ONEPLUS A6003
- **Operating system and version:**
  -  Android 10
- **Root access:**
  -  No

### Actual Behavior

- After updating to 10 Android, the user's network started to be blocked when AdGuard protection is enabled. Both on Wi/Fi and LTE.
- Changing the DNS servers and completely disabling DNS filtering did not give any result.
- The DNS server is also not configured in the Android system settings.

### Additional Information

User ID: 2466695
Logs in NCloud

**Comment by TheHasagi** [comment]
@Chinaski1 

Ask a customer to try with the latest Nightly.

**Comment by TheHasagi** [comment]
Closed due to no response from a customer.
