### ISSUE TITLE
Why does the bottom banner pop-up show late after checking for updates via long press shortcut?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3343]
Why does the bottom banner pop-up show late after checking for updates via long press shortcut?

It takes several minutes, compared with updates via the update button in the main screen.

When I check for updates via long press shortcut, it doesn't soon show pop-up.
I supposed that I didn't click well so I clicked for some times.
And then it started to separately show several pop-ups after some minutes.
Respond too late.
Is it reasonable?

**Comment by Revertron** [comment]
@lancelot-moon, do you see our new pop-up that updates have started? Is the problem still actual?

**Comment by lancelot-moon** [comment]
I tried v3.5 nightly 3 (17).
Not fixed.
