### ISSUE TITLE
Extremely large Elapsed time figure in the log

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3346]
### Prerequisites

It's more of a question rather than an issue as it does not affect the adblocking or anything else. The user 2537435 is wondering why the elapsed time is so large for certain connections.

### Issue Details

- **AdGuard version:**
  - 3.3.229
- **Filtering mode:**
  - VPN
- **Device:**
  - LG-V500 and other
- **Operating system and version:**
  - 5.0.2 and other
- **Root access:**
  - no

### Expected Behavior

The Elapsed time represents the real situation. 

### Actual Behavior

The Elapsed time figure is quite large which looks wrong and confusing. If it's not a bug, can we add some sort of explanation to the log?

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/74584567-86220f80-4fdc-11ea-8407-0922f8023e2f.png)

</details>

**Comment by TheHasagi** [comment]
In fact, elapsed time shows how long the connection lives and nothing more.
