### ISSUE TITLE
DNS over HTTPS: POST request (instead of GET) to avoid parameters logging 

### ISSUE THREAD

**Issue by sevospl** [AdguardTeam/AdguardForAndroid#3347]
Hi,
By default AdGuard makes GET requests for DNS over HTTPS. It would be nice to add/switch to POST -- so that there will be no parameters logging at all.

Helpful when using a CDN/any reverse proxy like Cloudflare.

**Comment by artemiv4nov** [comment]
The current version of the DNS functional is used POST requests.
