### ISSUE TITLE
Display amount of rules under each filter

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3348]
### Problem Description

We've been contacted by a user who would like to know how many rules each filter contains. As of now, AdGuard does not provide that option.

### Proposed Solution

Allow users to see the exact number of rules each filter contains - most likely under each individual filter's description.

### Alternatives Considered

Simpler option would be to display total amount of enabled rules, just like on Windows/iOS.

### Additional Information

reported by: 2553843

**Comment by artemiv4nov** [comment]
We decided to hide amount of rules for filters, we have a lot of other useful settings in the version app version.

**Comment by TPS** [comment]
This is necessary for filterlist choosing optimization.
