### ISSUE TITLE
ru.yandex.yandexnavi

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3352]
@adguard-bot commented on [Tue Feb 18 2020](https://github.com/AdguardTeam/AdguardFilters/issues/50062)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=ru.yandex.yandexnavi](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.yandex.yandexnavi)
### Comment
> При работающей защите перестает работать интернет в навигаторе и других приложениях, такая ерунда после последних 2х обновлений программы. Лечится выключением и включением защиты или же полной выгрузкой навигатора из оперативки. Т е когда приложение просыпается из памяти, adguard блокирует интернет приложению... Самое интересное - приложение в исключениях любых блокировок!!!! Почему адгуард вообще трогает приложение в исключениях?

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Wp7Vwyp.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/6lMREVJ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3.2 (230)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> I don't care about cookies, <br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

**Comment by TheHasagi** [comment]
Unable to reproduce. Seems like customer blacklisted some various yandex domains.
