### ISSUE TITLE
Cannot do anything with the "Removed apps" entry in the Apps Management settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3353]
1. It should be possible to clear statistics for this
2. All switches should be grayed out -- it is not possible to disable or enable filtering for the apps that do not exist

**Comment by TPS** [comment]
Is it possible to get some info added as to _what_ removed apps produced these stats?

**Comment by Alexey71** [comment]
![Screenshot_20200304-110810](https://user-images.githubusercontent.com/10572914/75858167-adfcda00-5e08-11ea-9bcb-01d35614cfcc.png)
![Screenshot_20200304-110822](https://user-images.githubusercontent.com/10572914/75858180-b228f780-5e08-11ea-9a15-bb53d647fff1.png)
![Screenshot_20200304-110827](https://user-images.githubusercontent.com/10572914/75858183-b3f2bb00-5e08-11ea-96f2-70f12d3c9427.png)

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
