### ISSUE TITLE
Период обновления подписок

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#3356]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [,√ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.2.1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - All
- **Operating system and version:**
  - All
- **Root access:**
  - No

### Expected Behavior

Чтоб обновлялись в назначенный срок без ручного вмешательства!
### Actual Behavior

Подписки не обновляются по истечению периода 24 часа.

**Comment by TheHasagi** [comment]
@Spok1 

О каких подписках идет речь? Фильтры обновляются в промежуток который был задан в разделе Настройки - Основные - Обновления и обновляются в случае если для этих фильтров доступны/есть обновления в целом.

**Comment by Spok1** [comment]
Все подписки если так понятней станет. Вот уж нет, обновляются они,насколько я понял, не по прошествии 24 часов в независимости от состояния устойства ,а при включенном устройстве 24 часа подряд. В итоге и получается,что 24 часа проходят, а фильтры как не обновлялись, так и не будут пока вручную не обновить или же мешьший интервал выставить. Такая же фигня была и с обновлениями фильтров в браузером расширении пока я не указал на это разработчику!

**Comment by artemiv4nov** [comment]
@Spok1 здравствуйте!
Проверьте на последней версии, пожалуйста. Когда-то у нас была эта проблема на найтли версиях, и мы её давно пофиксили, она даже в бету не попала.

**Comment by Spok1** [comment]
@artemiv4nov, изменений как ее было так и нет,версия 3.3.2(230)

**Comment by Spok1** [comment]
@artemiv4nov, изменений как не было так и нет,версия 3.3.2(230)! Последние обновления фильтров за 25 февраля в ручном режиме!

**Comment by ameshkov** [comment]
Может у вас включена функция "обновлять только по wi-fi"?

**Comment by Spok1** [comment]
Нет! Даже если бы так , я всегда через wi-fi  подключаюсь!  Разбирайтесь! У вас что , мало тестировщиков? Дайте им задание!

**Comment by TheHasagi** [comment]
@Spok1 

Воспользуйтесь пожалуйста данной [статьей ](https://kb.adguard.com/ru/android/solving-problems/log)для сбора отладочного лога и пришлите результаты на devteam@adguard.com.

**Comment by TheHasagi** [comment]
The issue is closed because of no response from the user. Will be reopened if needed.
