### ISSUE TITLE
AdGuard is Preventing/Delaying Various Applications from Loading (IPv6 Related?)

### ISSUE THREAD

**Issue by Hazbelll** [AdguardTeam/AdguardForAndroid#3359]
### Issue Details

- **AdGuard version:**
  - v3.3.2
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 3T (A3003)
- **Operating system and version:**
  - Android 9.0.0 (Resurrection Remix - RR-P-v7.0.2-20190915-oneplus3-Official)
- **Root access:**
  - No

### Expected Behavior

When AdGuard is Enabled or Disabled; All Apps should load their content as normal when opening/refreshing.

### Actual Behavior

When AdGuard is Enabled: Some Apps fail to load their content, or exhibit an unacceptably long delay until the content is loaded/refreshed (Apps Include: YouTube, Twitter, BBC Weather, Google Earth, etc.). When AdGuard is Disabled; All Apps resume normal/expected behaviour.

### Screenshots
<details><summary>Screenshot:</summary>

![BBC Weather App Failing to Load](https://user-images.githubusercontent.com/12906141/75274526-e5f99100-57fa-11ea-8097-30ff817950c5.png)

</details>

### Additional Information

**User ID: 1688853**

This issue has only been observed on one particular network - the network I use in my University Accommodation. I have narrowed it down to AdGuard seeing as the issue is not at all present on any other devices I use (Including a laptop running AdGuard for Windows), and is not present on my phone when AdGuard is disabled.

Unfortunately I am unable to pinpoint why exactly only this network causes it. Other WiFi Networks elsewhere and 2G/3G/4G Networks do not exhibit this issue at all. All I can assume is perhaps it's related to IPv6, as this is the only network I have used which is IPv6 Internet-enabled (IPv6 is rare in the United Kingdom).

**To Reproduce:**

1. Download/Install BBC Weather App
2. With AdGuard *Enabled*, open the App.
3. Observe the App Failing to load content until a significant amount of time passes (Screenshot here shows the symptom).
4. Close the App and Clear it from Recents. **Warning: If you waited until the content loaded, it might be cached the next time you open the App!**
5. With AdGuard *Disabled*, open the App.
6. Observe the App loading content (almost) immediately.

**Comment by akmLaVx** [comment]
User has contacted us:

_"Uploading a new Report to assist with reproduction of GitHub Issue:
#3359. Cleared Recents, Rebooted Phone. Performed Reproduction Steps
outlined in the above GitHub Issue. Tried with both AdGuard Enabled,
then Disabled, then Enabled again. Results were the same, however
noticed a list of saved areas for Weather eventually loaded,
attempting to use current location (Via Location Services) failed with
AdGuard Enabled and never loaded. I hope this helps and will comment
on the above GitHub issue for reference to this Report."_

Updated logs available in the ticket.

**Comment by artemiv4nov** [comment]
@Hazbelll , hi!
Try to reproduce it on the latest nightly, please.

**Comment by Hazbelll** [comment]
Hello @artemiv4nov, I have just tried reproducing using the Nightly (v3.4 nightly 8 (33)) and the issue remains. One difference I noted however, is Location Services no longer totally fails, it is just delayed the same as trying to retrieve content via WiFi Connection.

**Comment by Hazbelll** [comment]
Seems the problem has now solved itself for me. I wiped my phone entirely and installed a different System ROM (From Resurrection Remix based on Android Pie to Pixel Experience based on Android 10).

I can only assume therefore the old ROM was the culprit (Or possibly Android Pie?) in this issue. I'll leave the Issue open in case you have a better understanding from the logs provided. Thank you regardless!

**Comment by artemiv4nov** [comment]
Well, I guess a few applications don't reconnect at the second time after their connection has been rejected. That can appear from time to time with enabled protection of AdGuard because of the app filters the HTTPs traffic.

@Hazbelll Please reopen the task if you will feel not so good with other apps which you use.
