### ISSUE TITLE
Interface freezed out when "which domain to filter?" setting was changed

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#336]
Freezed after protection was disabled. Issue comes out with android 5.1
Turn on/off button doesn't work after this happens

**Comment by ameshkov** [comment]
Is it fixed?

**Comment by gshumihin** [comment]
Cannot reproduce it anymore, so i think yes :)

**Comment by ameshkov** [comment]
Then let's just close it.
