### ISSUE TITLE
AdGuard blocks Samsung Pay with pref.samsungpay.autopause.enable already enabled

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3360]
### Issue Details

- **AdGuard version:**
  - 3.3.230
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung SM-G981N
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

pref.samsungpay.autopause.enable allows user to use Samsung Pay.

### Actual Behavior

AdGuard ignores the setting.

### Screenshots

n/a

### Additional Information

See ticket 1488728 for logs.

**Comment by artemiv4nov** [comment]
At the moment, this issue has been tested successfully. Please, re-open the task if it will occur again.
