### ISSUE TITLE
Duckduckgo search suggestions in Firefox with Adguard

### ISSUE THREAD

**Issue by WhinVader** [AdguardTeam/AdguardForAndroid#3361]
[RU]

В Firefox c Adguard не работают поисковые предложения, я понимаю данную проблему решили не решать так как если в нее влезть можно устроить "щас буит мясо" с HTTPS фильтрацией в целом (AdguardTeam/AdguardForAndroid#2884)
Однако костыль с добавлением в белые ac.duckduckgo.com и duckduckgo.com не работает, что я сделаль не так и как заставить работать в лисе поисковые предложения от "утки".
Я уже создавал тикет в репо по фильтрам (AdguardTeam/AdguardFilters#50299), мне посоветовали обратиться сюда.

[ENG]

My problem that i meet issue co-working adguard+firefox and duckduckgo search suggestions in address bar, they don't work if AdGuard is on.
I understand that this problem is already marked as Wontfix (AdguardTeam/AdguardForAndroid#2884), but suggested workaround with whitelist ac.duckduckgo.com don't help and that's why i ask help for workaround it.

[System configuration]
Device: | Samsung Galaxy a40 with official Samsung full stock firmware, default knox state.
Platform: | Android 9 
AdGuard version: | 3.3.2 (230)
Browser: | Firefox Mobile
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters:
Ad Blocking: AdGuard Base, AdGuard Mobile Ads
Privacy: AdGuard Tracking Protection
Social Widgets: AdGuard Social Media
Annoyances: AdGuard Annoyances
Language-specific: AdGuard Russian
Also: | Use Cloudflare DNS and Adguard Extra

**Comment by TheHasagi** [comment]
@WhinVader 

Данная проблема не воспроизводится. Запишите и пришлите файлы журнала работы приложения на devteam@adguard.com согласно данной [статье](https://kb.adguard.com/en/android/solving-problems/log#debug).

**Comment by WhinVader** [comment]
Прошу прощения оказалось что в текущей лисе (не превью) в принципе в моем локальном случае по неизвестной причине даже без Adguard после перезагрузки устройства или после остановки лисы через диспетчер приложений перестают отображаться поисковые предложения от дакдакго в адресной строке, поэтому полагаю что "ваша хата с краю" и не к вам нужно с этой проблемой.

**Comment by akmLaVx** [comment]
Customer 2259950 reported the same issue for Firefox Mobile instead of DuckDuckGo. Detailed information about the case is in the mentioned issue.

**Comment by TheHasagi** [comment]
Closed due to no response from a customer. Should be reopened if needed.
