### ISSUE TITLE
Bypass apps in work profile in root mode. 

### ISSUE THREAD

**Issue by h0cheung** [AdguardTeam/AdguardForAndroid#3362]
When using adguard in root mode, all apps in work profile will connect through adguard.

**Comment by TheHasagi** [comment]
@h0cheung 

Could you clarify your question? What do you mean "work profile"?

**Comment by h0cheung** [comment]
> @h0cheung
> 
> Could you clarify your question? What do you mean "work profile"?

There is some documents about work profile.

https://developers.google.com/android/work/requirements/work-profile

It can be used to create an profile, in which there are independent applications and storages. And VPNService in work profile is also independent.

Island and shelter (both can be installed from Google Play Store) are two applications that are based on work profile and are easy to use. 

In my phone, the UIDs of applications are 10xxxxx, but I don't know if is is the same in all situation.

**Comment by OnkelM** [comment]
this issue is still open? i have the same result with Microsoft company portal specifically the edge browser in the work profile. I cannot browse to work related sites because the Adguard certificate is being rejected from the company. i tried disabling company portal app in the Adguard settings but this does not help.

**Comment by Chinaski1** [comment]
Yes, this issue is still open
We will come back to it after releasing version 4.0.

**Comment by alxs** [comment]
This is a real issue. I cannot use Chrome on my work profile as it rejects the certificate (`NET::ERR_CERT_AUTHORITY_INVALID`), and it's not possible to install it manually since the profile is managed.

**Comment by senseigit** [comment]
Version 4.0 is also released a long time ago but still the issue persists? Can't we do anything about it?
