### ISSUE TITLE
Fast transition feature in the filter rules.

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3364]
### Problem Description
In case when the user filter list is getting a bit long, and any time he needs to get to the bottom it takes a bit of scrolling.  When he edit a rule at the bottom, the list always resets to the top again and  need to scroll again to the bottom for further editing.

### Proposed Solution

How about a **Jump to Bottom** button somewhere at the top.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3378
