### ISSUE TITLE
Ad blocking randomly stops on Samsung Galaxy Tab Pro

### ISSUE THREAD

**Issue by paskardv** [AdguardTeam/AdguardForAndroid#337]
Спустя какое то время на планшете Samsung Galaxy Tab Pro отключается фильтрация рекламы. Выключение и включение защиты не помогает, только ребут устройства.
Реклама проскакивает только на 
планшете Samsung с бесплатной версией adguard и android 4.4, в то же самое время на телефоне LG с вечной лицензией adguard и 
android 6.0 реклама режется нормально. Отключение и включение защиты 
adguard не помогает, только перезагрузка планшета. Алгоритм фильтрации - 
качественный и режим фильтрации - локальный vpn установлены одинаково на 
обоих устройствах.

Обсуждение на 4pda http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=47175825

Полный лог, сделанный с устройства при наличии проблемы: PZH-284-78606

**Comment by ameshkov** [comment]
Спасибо за баг репорт!

Сегодня не факт что успею в детали погрузиться, но завтра точно посмотрю;

**Comment by ameshkov** [comment]
Похоже на проблемы с прошивкой. В логе видно, что через нас вообще не проходит TCP трафик, только UDP.

Есть ли другая прошивка?

**Comment by paskardv** [comment]
Свежее пока ничего нет, хотя и давно обещают выпустить 5й андроид на этот планшет.

**Comment by ameshkov** [comment]
Это не очень хорошо. Частично облегчит жизнь включение DNS фильтрации в расширенных настройках, там как раз UDP трафик фильтруется.
