### ISSUE TITLE
Third party applications ask disable your adblocker

### ISSUE THREAD

**Issue by PugalRajan** [AdguardTeam/AdguardForAndroid#3371]
This application not open properly please help me!

Package name: com.apkland.tamiltvlive
Uid: 10238
App type: User
Version: 1.8 (8)
Target SDK: 27

Apk link - http://www.apktv.in/livetv_new/apk/apklandtv-latest.apk

**Comment by ameshkov** [comment]
If you really need that app, you may need to use something like App Cloner to change AdGuard's package name. Please note, that in this case, you'll have to install updates manually
