### ISSUE TITLE
Installation certificate filters HTTPS impossible in Bluestacks on PC

### ISSUE THREAD

**Issue by grysor** [AdguardTeam/AdguardForAndroid#3372]
Hello
whenever i want to install the HTTPS certificate automatically in the Bluestacks emulator on my PC ,adguard tell me :
" enter the password for storing identifiers "
and i don't have a password!

I also tried to install the certificate manually but the result is the same, this unknown password is requested,
how to do? :( thank you in advance

**Comment by grysor** [comment]
![2020-03-12_025353](https://user-images.githubusercontent.com/35570935/76479691-e7d36f00-640c-11ea-9f57-eae454df88a1.png)

**Comment by artemiv4nov** [comment]
Well, that is a ROM's problem. Try to set a password to your user and try again using the password, please.

**Comment by grysor** [comment]
> Try to set a password to your user and try again using the password, please.


-Hello thanks but unfortunately it is not possible to define a password in Bluestack :(

**Comment by ameshkov** [comment]
There's not much we can do with that:(

The only alternative is installing automatically using root access.
