### ISSUE TITLE
[Nightly] Adguard causes other VPN to close

### ISSUE THREAD

**Issue by alexdonh** [AdguardTeam/AdguardForAndroid#3373]
I am currently on v3.4 nightly 8. When opening Adguard app (working proxy mode auto), the current VPN connection from another VPN app gets terminated and closed. Everytime. 

Notifications permission of the VPN app is blocked (to avoid displaying too many notifications). It works just fine if Adguard app is not opened.

Samsung S10+
Android 10
One UI 2.0
Adguard 3.4 nightly 8
Proxy mode (auto - with root)
Steath mode on
Block WebRTC on

**Comment by lancelot-moon** [comment]
Duplication.
https://github.com/AdguardTeam/AdguardForAndroid/issues/3338

**Comment by alexdonh** [comment]
Actually when I was on the stable build it happens too. Just using nightly as @TheHasagi asked me to try with nightly build on another issue. Its duplicated then Im gonna close.

Thanks & BR
