### ISSUE TITLE
Issues with Internet access for some apps in Android 11 DP 1.1

### ISSUE THREAD

**Issue by sviperz** [AdguardTeam/AdguardForAndroid#3374]
### Some apps has no Internet access when AG is active. Whenever AG is paused, the apps immediately start their pending network activity such as synchronization, backup, content loading, etc.

- **AdGuard version:** v3.4 nightly 8 (33)
- **Filtering mode:** Local VPN
- **Device:** Google Pixel 3
- **Operating system and version:** Android 11 DP 1.1
- **Root access:** No

### Expected Behavior

Apps get Internet access whenever they need it.

### Actual Behavior

Apps pending their network activity or have no access to Internet.

### Steps to reproduce:

1. Create shared Google Keep note and edit it on another device.
2. Check the note on the device with working AG. The note isn't updated.
3. Pause AG. The not is updated immediately.

**Comment by artemiv4nov** [comment]
The task has already been fixed by #2842
