### ISSUE TITLE
安装ca证书后部分app无法正常使用

### ISSUE THREAD

**Issue by fliu52** [AdguardTeam/AdguardForAndroid#3380]
如题，安装ca证书后启用https过滤，发现`滴滴出行`app部分功能无法联网使用，删除ca证书并关闭adguard后就可以正常使用。同样的情况还有`什么值得买`app，希望重视并解决。

**Comment by ameshkov** [comment]
@fliu52 

Not every app supports HTTPS filtering. If it does not work for some app, you can do the following:

1. Go to "Settings", "Apps Management"
2. Find the problematic app
3. Tap on it
4. Uncheck "HTTPS filtering" there
