### ISSUE TITLE
HTTPS Everywhere support.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3381]
Request HTTPS Everywhere support like this:
https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=zh-TW

**Comment by sfionov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/689

However, in apps it should be done in CoreLibs or its resources

**Comment by lancelot-moon** [comment]
Yes, it should be done in CoreLibs.
Then AG for PC/Android will easy have HTTPS Everywhere.
I'll close this.
Hope you won't forget the old feature request from 2016.
https://github.com/AdguardTeam/AdguardForAndroid/issues/689
