### ISSUE TITLE
Is it Possible to Block Only Uploaded/Received Data (Per Domain)

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3383]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard can see the requests size for data send and received from a domain, would it be possible to block a domain from uploading data? (e.g. example.com$upload prevents example.com from sending data to its servers)

### Additional Information

I feel like this could be used for things like mtalk.google.com which is used for Google Cloud Messaging because it might not need to send info to google but each request seems to send 0.03 KB of data for each request that happens every few seconds. I'm sure I'm just paranoid but I don't like things uploading data even that small of a size.

**Comment by TheHasagi** [comment]
@Cybo1927 

At the moment, I doubt that it is technically possible.
