### ISSUE TITLE
AdGuard blocking incoming emails on office365

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3384]
If security is enabled, e-mail delivery is blocked.
Disabling all modules and adding the domain to the whitelist does not bring any result.

Info:
- POP3 server: outlook.office365.com;
- Safety: SSL/TLS;
- Port 995;
- Unencrypted password.

User ID: **2583339**
Time/Date: **21.03.2020 |  10:39** 
Logs in NCloud

**Comment by TheHasagi** [comment]
Everything works smoothly. Unable to reproduce.

**Comment by TheHasagi** [comment]
@Chinaski1 

Ask a customer to check if adding office365.com to the whitelist helps to solve the issue. Should be reopened if needed.

**Comment by Chinaski1** [comment]
The user has sent new logs using the latest Nightly version.
Added to NCloud.
