### ISSUE TITLE
adguard replace is compatible with bugs

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdguardForAndroid#3385]
- **AdGuard version:**
version 3.4 nightly 9 from March 19, 2020
- **Filtering mode:**
vpn mode
- **Device:**
One plus 6t
- **Operating system and version:**
android 10.0.1
- **Root access:**
root 

adguard is not compatible with this rule "||xxxx.com/v6/main/indexV8?page=1$replace=/\"url\":\s*?\"\/apk\/\d+"\,/\"url\": \"/\"\,/"
But this rule is compatible with "||xxxx.com/v6/main/indexV8?page=1$replace=/\"entityType\":\s*?\"image\w\d\",/\"entityType\":\s*?"NULL","

I don't understand these two rules. One of the two rules has no effect.

This is part of the packet capture data
`{
  "data": [
    {
      "entityType": "card",
      "entityTemplate": "imageCarouselCard_1",
      "title": "",
      "url": "",
      "entities": [
        {
          "entityType": "image_1",
          "title": "ad",
          "url": "https://shop282992944.m.taobao.com/?frombear\u003d-194854652",
          "pic": "http://image.xxxxx.com/image/2020/0321/20/1584794904_8241-0-o_1e3ui69ku17e1140b1qnf1ca21lt8a-uid-97100@1080x360.png"
        },
{
          "entityType": "image_1",
          "title": "ad2",
          "url": "/apk/80389",
          "pic": "http://image.xxxx.com/image/2020/0320/11/3E590BCE5A786-0-o_1e3qun7ln1j5v1usj1vlp1mgl2oa-uid-97100@960x320.jpg"
        },

`

**Comment by TheHasagi** [comment]
@thb007 

Please, describe in more detail which domains you are trying to apply these rules to and where does this problem reproduce?

**Comment by thb007** [comment]
> @thb007
> 
> Please, describe in more detail which domains you are trying to apply these rules to and where does this problem reproduce?

The replace rule has no effect on the data in the screenshot. This is the replace rule I wrote "||xxx.
domain/v6/main/indexV8?page=1$replace=/"url":\s*?"/apk/\d+",/"url": "/",/""
Please delete the pictures I uploaded after reading them.

![YOQJVRTWUEKXFL{`K)AIIXN](https://user-images.githubusercontent.com/17548936/77646649-eb83fb80-6f9f-11ea-9ed2-60d07466ac53.png)
![QCN2_7@ YR5D4RAOX%AGVN](https://user-images.githubusercontent.com/17548936/77646710-08b8ca00-6fa0-11ea-9c3d-9dc16bedcd6a.png)

**Comment by TheHasagi** [comment]
@Alex-302 

Can you confirm that rule is legit?

**Comment by Alex-302** [comment]
@thb007 please show on https://regex101.com/ what do you want to do.
