### ISSUE TITLE
Adguard pro not blocking ads on apps

### ISSUE THREAD

**Issue by omegapaulo** [AdguardTeam/AdguardForAndroid#3387]
Adguard not blocking ads on apps, I bought the pro version specially for that but it doesn't work on my note9.

**Comment by TheHasagi** [comment]
@omegapaulo 

Hello, can you provide more information like AdGuard version, installed filters, enabled DNS and the apps where you are facing the ads.

**Comment by TheHasagi** [comment]
Closed because of no response. Will be reopened if needed.
