### ISSUE TITLE
AdGuard can't be enabled with dns filtering on amazon firestick with 3.4 nightly 10

### ISSUE THREAD

**Issue by Theitfixer85** [AdguardTeam/AdguardForAndroid#3388]
Device - Amazon firestick v2
AdGuard version - 3.4 nightly 10

AdGuard can't be enabled if dns filtering is enabled (regardless of the dns server selected) 
When you try and enable AdGuard you just get a box saying please wait with a spinning circle & nothing happens 

If I disable dns filtering AdGuard can successfully be enabled. 
AdGuard could be used with dns filtering successfully on 3.4 nightly 9 and I noticed some changes were made to amazon in the changelog between versions

Also I am still unable to activate premium on the firestick v2 as it gives error please make sure that you have entered a valid premium license key - I have previously sent logs for this

Logs sent via email to devteam@adguard.com

**Comment by TPS** [comment]
I've the same problem on Moto G5+ Android 8.1 non-rooted, so I doubt it's device specific.  Add'lly, I can't successfully send bug report, as AG freezes completely when trying to do so.  (Need to force stop & wipe cache.)

 Please, can we get higher nightly version quickly that reverts DNS changes?

**Comment by Ilithy** [comment]
Hi;
I'm on a Oneplus 6 under oxygen OS 10, I have DNS filtering enabled, and AdGuard works perfectly (I attach a screenshot)

![Screenshot_20200327-120845](https://user-images.githubusercontent.com/36798218/77750601-5c6cf700-7024-11ea-8399-6a9ab9c87ab6.jpg)

Sorry AdGuard is in English, I can provide log files if needed for comparison.

**Comment by Theitfixer85** [comment]
@Ilithy Yes it works fine on my phone but it doesn't work on my amazon firestick with dsn filtering with 3.4 nightly 10

As mentioned it worked fine with nightly 9 and there were changes made to amazon in the AdGuard changelog between versions 

I cannot comment on other devices but I opened this thread for the amazon firestick however it may effect other devices where as others like my phone are as with yours not effected

**Comment by TPS** [comment]
@Ilithy Are you running v3.4n10?

**Comment by TheHasagi** [comment]
Dears, 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Theitfixer85** [comment]
@TheHasagi logs have been sent as requested

**Comment by TheHasagi** [comment]
@Theitfixer85 

Thank you very much, got the logs.

**Comment by Ilithy** [comment]
@Theitfixer85: Yes indeed, sorry, it wasn't meant to bother you.

@TPS : yes, Il running AdGuard 3.4 nightly 10

**Comment by Theitfixer85** [comment]
Issue resolved with nightly 11

**Comment by TPS** [comment]
All solved for me, also.  Thanks _very_ much. 🙇🏾‍♂️
