### ISSUE TITLE
anti-AD domains list causes photos broken on GitHub when enabling DNS filtering in AG for Android.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3390]
anti-AD **domains list** causes photos broken on GitHub when **enabling DNS filtering in AG for Android**.
I tested on Android.
**Clear cache before the test.**
ex: Photos were broken on GitHub:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8qyDC0o.jpg)
</details><br/>

No problem on PC.
(I also subscribed to anti-AD domains list in my router for DNS filtering.)

I tried anti-AD other formats list, ex: basic rule syntax, which is no problem.
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt

The problem is only with anti-AD **domains list**.
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt

Maybe something wrong between anti-AD domains list and AG for Android.
Also reported there:
https://github.com/privacy-protection-tools/anti-AD/issues/81

After checking, AG for iOS v4 beta with anti-AD domains list also has the problem of broken photos on GitHub.
With anti-AD basic rule syntax list in AG for iOS v4 beta, no problem.

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/DnsLibs/issues/66
