### ISSUE TITLE
IP won't be changed with outbound proxy if enabling pref.vpn.ipv4.bypass or pref.vpn.ipv6.bypass.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3392]
I use v3.4 nightly 10.
Assume that I enable pref.vpn.ipv4.bypass or pref.vpn.ipv6.bypass and DNS filtering for only DNS filtering, I expect that outbound proxy should work.
But IP won't be changed with outbound proxy if enabling pref.vpn.ipv4.bypass or pref.vpn.ipv6.bypass.
Is it a bug or designed so?

**Comment by lancelot-moon** [comment]
Andrey answered me, "IPv4 or IPv6 is not routed through AG at all in this case".

Will the logic be better if only ad blocking is disabled, but HTTPS traffic is still routed through AG in this case?
Consider outbound proxy...

**Comment by lancelot-moon** [comment]
AG will show that normally connected to a proxy server, but IP isn't changed actually in this case.
You should provide a warning about invalid outbound proxy in this case if you keep the original logic (not routed through AG).

**Comment by artemiv4nov** [comment]
Well, it can be considered as a feature request. Let's see how many users will want to see the feature in the next versions of AdGuard.

**Comment by artemiv4nov** [comment]
Well, we removed these settings, I'll close the task.
