### ISSUE TITLE
Maybe better to modify the descriptions for pref.vpn.ipv4.bypass and pref.vpn.ipv6.bypass if keeping now logic.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3393]
will not be filtered
-> won't be routed through AdGuard
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/NyhzK7H.jpg)
</details><br/>

"Not filtered" can also mean only ad blocking disabled but still routed.
Your original description isn't accurate.

**Comment by artemiv4nov** [comment]
We already removed these points, the task should be closed
