### ISSUE TITLE
Can not enable UDP through SOCKS5 proxy

### ISSUE THREAD

**Issue by mmyz1234** [AdguardTeam/AdguardForAndroid#3394]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.4 nightly 10
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Note 8
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Can enable UDP through SOCKS5 proxy.

### Actual Behavior

Enable UDP through SOCKS5 proxy and save it. Then edit it again, the switch is disabled.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20200327-235917_AdGuard](https://user-images.githubusercontent.com/30427542/77776423-f5cdf480-7088-11ea-8751-3b3af8781fb3.jpg)

</details>

**Comment by TheHasagi** [comment]
@mmyz1234 

Hello there,

Can you clarify your question? As I can see on the screenshot you did not fill the fields correctly.

**Comment by mmyz1234** [comment]
@TheHasagi Looke this video. Thanks.

[video-screenshots-enable-UDP-through-SOCKS5-proxy.mp4](https://github.com/mmyz1234/FeedbackForAdguard/raw/master/video-screenshots-enable-UDP-through-SOCKS5-proxy.mp4)

**Comment by TheHasagi** [comment]
@mmyz1234 

Thank you for the short clip you've recorded. Confirmed.

**Comment by Revertron** [comment]
It's enabled actually, but not reflected in edit dialog properly.
It's my bug, I'm committed to fix it :)

**Comment by mmyz1234** [comment]
It is fixed. Thanks.
