### ISSUE TITLE
com.google.android.apps.podcasts

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3398]
@adguard-bot commented on [Sat Mar 28 2020](https://github.com/AdguardTeam/AdguardFilters/issues/52420)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.google.android.apps.podcasts](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.podcasts)
### Comment
> С включенным блокировщиком не обновляется страница новых эпизодов, но воспроизведение работает
> 
> Сертификат добавлен в систему (magic root)
> Блокировка рекламы по всех приложениях - включено, а вся блокировка в приложении Google Podcasts отключена (в разделе настройки приложений)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/WfuEmXf.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/gOJ1zwE.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3.2 (230)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>EasyList<br/><br/><b>Annoyances:</b><br/> Fanboy's Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> RU AdList, <br/>RU AdList: Counters, <br/>RU AdList: BitBlock

**Comment by TheHasagi** [comment]
Cannot reproduce.  Should be reopened if needed.
