### ISSUE TITLE
Default HTTPs blacklist

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#340]

**Comment by ameshkov** [comment]
graph.facebook.com
googleapis.com
doubleclick.net

What else?

**Comment by TPS** [comment]
@ameshkov I'm a little confused.  If I'm already SSL-filtering, why do _any_ of _these_ need to be added to the blacklist?  Aren't these already in the ad blocklists?  I thought this list was for ad-_hosting_ sites, like #314?

**Comment by Revertron** [comment]
@TPS This is a very good question!

**Comment by ameshkov** [comment]
I guess the task name is misleading.

These domains (graph.facebook.com and googleapis.com) are not ad networks. At the same time, **some** requests to these domains are for loading ads.

Let's take a closer look.

Facebook mobile SDK uses this URL to get personalized ads for you:
```
https://graph.facebook.com/network_ads_common/
```

Youtube app uses this URL to get video player settings which includes a [VAST](http://www.iab.com/guidelines/digital-video-ad-serving-template-vast-3-0/) object containing ads definition.
```
https://www.googleapis.com/youtubei/v1/player
```

So, here are some key points about these domains:
1. As you see, both URLs are HTTPs.
2. We can't block whole domains as all other requests to these domains are crucial for the apps.
3. We need to decrypt connections to these servers to be able to block (or modify in YT case) requests.

@TPS how should I rename this issue to make it clear?

**Comment by TPS** [comment]
I'm still lost, so I'm not sure how to clarify the name.  Here's why:  I assume all these filters are already added to whichever appropriate filterlist, but _processing_ said list will change based on my settings:
* SSL filtering disabled → non-SSL versions filtered, SSL versions passed through unchanged
* SSL filtering enabled
 * whitelist mode → unless whitelisted, both SSL & non-SSL versions filtered, else just non-SSL
 * blacklist mode → iff (e.g., if-&-only if) blacklisted, both SSL & non-SSL versions filtered, else just non-SSL _← I personally prefer this mode_

I think how you're explaining this, the white-/blacklist is like another filtering subscription, irrelevant of the other subscriptions, but I understand it as an additional _mode_ to further filter SSL, using the same filterlists.  Am I wrong?

**Comment by ameshkov** [comment]
> but I understand it as an additional mode to further filter SSL, using the same filterlists.
This mode has no direct connection with the ad filters list. It manages when SSL/TLS should be decrypted and when it should not.

In general you are close, but let me elaborate on this topic.

#### SSL filtering disabled
* *plain-HTTP* → filtered, which means that AG can see the exact request and modify both request and response
* *HTTP over TLS* → limited filtering. AG can see the remote server's domain name and that's all. Some domains can be fully blocked (like doubleclick.net), some - cannot be blocked, like graph.facebook.com.

#### SSL filtering enabled
SSL filtering means decryption of the HTTPs traffic inside Adguard.

Take a look at this diagram:
*Browser* → encrypted traffic → Adguard → encrypted traffic → *Remote Server*
Adguard decrypts TLS and filters underlying HTTP traffic. Then it encrypts it again and sends further.

**Important note:**
Adguard won't decrypt some connections. Possible causes: invalid server certificate, old TLS/SSL version, also some if client app does not accept our certificate.

#### Which connections to filter
Look at the very start. When we start processing some encrypted connection, we know nothing about it except the domain name. **So, we should make a decision about decryption based on the domain name only**.

##### Whitelist mode
Adguard will decrypt ALL connections EXCEPT the whitelist. Whitelist can be edited manually. What's important is that by default whitelist **is not empty**. It contains popular financial services and some other websites with sensitive personal information.

Here is a special github issue used for collecting domains for this default whitelist:
https://github.com/AdguardTeam/AdguardForWindows/issues/911

*Note:* the whitelist is smaller in Android, some of the domains in the default whitelist cannot be used from mobile.

##### Blacklist mode
Adguard will decrypt ONLY connections to the domains from the blacklist. Blacklist can (and should) be edited manually. At the same time, I'd like it to contain some domains by default.

**Comment by ameshkov** [comment]
Huh, I've read my last comment and figured out from it, that the right name for this issue should be "Default HTTPs blacklist":)

**Comment by TPS** [comment]
Thanks for detailed response!  I _still_ don't think the approach makes sense from a user perspective, & I _do_ understand the technical limitations.  What _does_ makes sense, but redoing according to your example above:

Appropriate`graph.facebook.com`filter should be added to respective filterlist (tracking, spyware, whatever), then:
* If SSL filtering disabled,`graph.facebook.com`will only match to non-SSL requests made (if any)
* If SSL filtering enabled, `graph.facebook.com`in
 * whitelist mode will match from _any_ requesting "container" — app, website, whatever, _except_ those on whitelist
 * blacklist mode will match from _only_ those "containers" on the blacklist

 ↑ _Is this possible, especially website?_ ↑

Making the user _have_ to be _this_ technical makes the white-/blacklist feature _much_ less useful.

**Comment by ameshkov** [comment]
What do you mean by container?

**Comment by TPS** [comment]
Container, in this case, would mean either requesting _site_ (e.g., via browser app: YouTube.com, FaceBook.com, &c) or any other _dedicated app_ (e.g., YouTube, Facebook, &c).  An user would know what those are, but not what domain (e.g.,`graph.facebook.com`) needs to be included/excluded!

**Comment by ameshkov** [comment]
> would mean either requesting site

That's not possible.

We know two things about outgoing connection: the app and target domain name.

**Comment by TPS** [comment]
Then, for a user, like all the other lists, the white-/blacklist should likely include apps, somehow, as well, maybe via another toggle on that firewall screen?

**Comment by ameshkov** [comment]
> Then, for a user, like all the other lists, the white-/blacklist should likely include apps, somehow, as well, maybe via another toggle on that firewall screen?

Yeah, that's possible, but I'd better do it in some future release. I don't like the current situation when ad filtering and firewall settings are in the same section.

We will make a separate settings named "Filtered Apps" where you'll be able to select the apps for which you want ads to be blocked.

**Comment by TPS** [comment]
:+1: +1 That works for me, & those like me. ☺

**Comment by ameshkov** [comment]
For now default SSL blacklist contains only two domains:
```
// necessary to block Youtube ads
googleapis.com
// used by the facebook ad network
graph.facebook.com
```

Most ad networks domains could be blocked without HTTPs filtering so in this list we collect only domains for which we need fine-grained filtering.
