### ISSUE TITLE
Quick Settings button to update filters

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3404]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/78560442-c0f73580-781e-11ea-9d17-6bf097bc411f.png)

</details>

### Additional Information
The request was sent by users from the [AdGuard forum](https://forum.adguard.com/index.php?threads/quick-settings-button-to-update-filters.38064/#post-196801).

**Comment by artemiv4nov** [comment]
After all, we decided to keep it as is.
