### ISSUE TITLE
DNS filtering kills internet speed

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/AdguardForAndroid#3405]
Galaxy Note 10+ with Android 10, galaxy note 10 with Android 10, nexus 6 with Android 9.  No devices are rooted.  All devices using nightly builds of adguard (latest build)

The issue... Internet speeds on my gigabit connection when using adguard are beyond horrible and fine when WiFi is shut off OR wifi is on and adguard is shut off.  This began before the covid issue and roughly 3 nighly builds ago.

I did some more playing around trying to figure this odd situation out when I disabled DNS filtering altogether and instantly webpages and downloads were.. well instant.

So I rebooted all my network equipment and my phones then turned DNS filtering back on and again it would take up to a min to load any webpage and downloading even small apps from the play store would take around 4 min.

I shut DNS filtering off again and again all web pages loaded instantly and app downloads that were even 100mb downloaded in 1-2 seconds.

I haven't checked the stable build of adguard for android yet but on 3 different phones with the nightly builds installed this issue was present and instantly fixed by shutting off DNS filtering.

Tested with adguard, cloudflare, Google and Comcast DNS.  Same results occur with all.

**Comment by TheHasagi** [comment]
@d0x360 

What DNS resolver is selected when internet speed slows down? Have you been trying to select other DNS server or change the DNS server type like DoH/DoT/Regular/Crypt?

**Comment by d0x360** [comment]
All the DNS servers listed would run at the same speed.  A webpage would
take like a min to start loading.  Immediately after shutting dns filtering
off pages loaded instantly.

I only used the regular ones in settings and I have no custom rules.

This issue didn't occur until about 3 nightly builds ago, I'm sorry I don't
have a date or exact version#

**Comment by TheHasagi** [comment]
@d0x360 

Could you please check it with the stable [release](https://agrd.io/apk)?

**Comment by TheHasagi** [comment]
Closed due to no response. Will be reopened if needed.

**Comment by d0x360** [comment]
Checked with a stable release and it works fine.  Also uninstalled the
nightly and installed it again and the same issue occured.

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/DnsLibs #69](https://github.com/AdguardTeam/DnsLibs/issues/69) via [**ZenHub**](https://www.zenhub.com/)
