### ISSUE TITLE
Kodi app crashes when protection is enabled

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3407]
### Issue Details

- **App**
 - org.xbmc.kodi
- **AdGuard version:**
  - 3.3.231
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Amlogic X Player
- **Operating system and version:**
  - Android 6.0.1
- **Root access:**
  - No

### Actual Behavior

When protection is enabled, Kodi app crashes to desktop

### Additional Information & debug logs

See helpdesk ticket 2622940

**Comment by TheHasagi** [comment]
Ask a customer to disable HTTPS filtering or disable the whole filtering for the application if it crashes.
