### ISSUE TITLE
Закрывается системой.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3409]
Здравствуйте,
Система закрывает процесс. Низкоуровневые настройки включал, интервал проверки жизни ставил. Как с этим бороться?

**Comment by artemiv4nov** [comment]
Какой у вас телефон? Марка, модель, версия Андроида

**Comment by TheHasagi** [comment]
Для решения данной проблемы прочитайте данную статью в нашей [Базе Знаний.](https://kb.adguard.com/ru/android/solving-problems/background-work) Если у вас возникнут трудности вы сможете обратиться в службу поддержки по адресу support@adguard.com.
