### ISSUE TITLE
Rename "Send detailed system info" to "Send detailed system info and the log file"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#341]
And we should also add information about the log file into this item description.

**Comment by Revertron** [comment]
And what "information about the log file" should we add to the summary?

**Comment by ameshkov** [comment]
Something like "Log file contents depends on the logging level you set in the app settings."

Two more things:
1. Check the grammar of the new strings.
2. Check the checkbox layout, it seems weird now (checkbox label is gray, description text is cut in the middle)

**Comment by Revertron** [comment]
Done.
