### ISSUE TITLE
Notification: Wi/Fi without network access

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3410]
### Issue Details

- **AdGuard version:**
  -  3.4.70
- **Filtering mode:**
  -  HTTP Proxy Auto
- **Device:**
  -  Xiaomi MI 6
- **Operating system and version:**
  - 9
- **Root access:**
  -  YES

### Actual Behavior

When the user starts AdGuard in HTTP Auto Proxy mode, he faced an issue with Wi/Fi.
The connection to the network is successful, but the user receives a notification that the network is not connected to the Internet.
Restart protection or change to VPN mode solves the issue.
- Note: No third-party VPN service is used.

### Additional Information

User ID: **2636438**
Logs in NCloud.

**Comment by artemiv4nov** [comment]
I am thinking, this task is related to #3415. Yesterday, we had dropped the new nightly version with a few improvements and it helped
