### ISSUE TITLE
https://wiki.freifunk.net/

### ISSUE THREAD

**Issue by larena1** [AdguardTeam/AdguardForAndroid#3412]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4 Nightly 19
- **Filtering mode:**
  - Proxy
- **Device:**
  - 
- **Operating system and version:**
  -  Android 10
- **Root access:**
  -  Yes

https://wiki.freifunk.net/

This site can't be viewed in Chrome. It just says ERR_CONNECTION_RESET
The URL will also not even show up in the Filtering Log. WIth AdGuard turned off, the site can be viewed.

**Comment by TheHasagi** [comment]
@larena1 

Cannot reproduce the issue, seems like you are using third-party filters that can block this website. Try to check the filtering log and see what happens with the requests.
