### ISSUE TITLE
Cannot revoke a root CA certificate.

### ISSUE THREAD

**Issue by h0cheung** [AdguardTeam/AdguardForAndroid#3414]
After a certificate has been revoked in Android settings, if I enable https filtering, I can still open websites that use the certificate. 

It seems that adguard use its own certificate database.
 If so, adguard should let users revoke certificates in adguard's settings.

**Comment by TheHasagi** [comment]
@h0cheung 

Seems like you delete another certificate that not belongs to AdGuard. You are able to delete the certificate from AdGuard Settings - Network - HTTPS Filtering - Security certificate - Delete.
