### ISSUE TITLE
The latest nightly version of adg will cause the network to be disconnected from the network. 

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/AdguardForAndroid#3415]
The latest nightly version of adg will cause the network to be disconnected from the network. Restarting the adg network will restore the network, but it will be disconnected after a short time. My goodness!

**Comment by Chinaski1** [comment]
Hello, dear @thb007 

Then let’s do the following:
- AdGuard > Settings > Advanced > Logging Level > Record All.
- Reproduce your issue.
- Note the time the error occurred and let us know.
- Don’t forget to return to the default logging level.
- Logs can be sent to devteam@adguard.com

**Comment by thb007** [comment]
> Hello, dear @thb007
> 
> Then let’s do the following:
> 
> * AdGuard > Settings > Advanced > Logging Level > Record All.
> * Reproduce your issue.
> * Note the time the error occurred and let us know.
> * Don’t forget to return to the default logging level.
> * Logs can be sent to [devteam@adguard.com](mailto:devteam@adguard.com)

Seems to be a DOH / dot dns parsing problem, not related to the software
