### ISSUE TITLE
Firefox Beta has no internet access unless whitelisted in AG

### ISSUE THREAD

**Issue by gms77** [AdguardTeam/AdguardForAndroid#3418]
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

Since Firefox Beta updated to 75 (which was the merger of the Firefox Preview to the regular Beta version) I can't load any websites unless I disable Adguard protection.

- **AdGuard version:**
3.3.3.231
- **Filtering mode:**
Local VPN
- **Device:**
Huawei P9 Lite 2017
- **Operating system and version:**
Android 8
- **Root access:**
No

### Expected Behavior
Websites open

### Actual Behavior
No connection

### Screenshots
![Screenshot_20200424-161220](https://user-images.githubusercontent.com/15159047/80229393-43b62800-8648-11ea-8c91-5907e964b9b8.jpg)
![Screenshot_20200424-161231](https://user-images.githubusercontent.com/15159047/80229398-46188200-8648-11ea-89c4-d7499cbb20bc.jpg)
![Screenshot_20200424-161247](https://user-images.githubusercontent.com/15159047/80229404-49137280-8648-11ea-8148-3d6973bbb3ec.jpg)
![Screenshot_20200424-161307](https://user-images.githubusercontent.com/15159047/80229409-4add3600-8648-11ea-9cb9-d8549188cc5d.jpg)

**Comment by anonymous-user** [comment]
Does it work if you just disable HTTPS filtering?

**Comment by gms77** [comment]
I already tried that, it still doesn't work.
Here's another screenshot of the technical info incase it's of any use.

![Screenshot_20200425-023734](https://user-images.githubusercontent.com/15159047/80269624-4301ae00-86a9-11ea-86d7-22634969dc99.jpg)

**Comment by gms77** [comment]
An update, I'm not sure what happened but I've got it working now.
Currently using AG 3.4 beta 1 and Firefox 76 Beta 1 and I can load webpages normally again without whitelisting so I'll close this bug report.
