### ISSUE TITLE
Some applications doesn't apply the AdGuard certificate

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#3419]
![Screenshot_20200426_152909_com adguard android](https://user-images.githubusercontent.com/22351242/80307606-bf43e080-87d2-11ea-9b87-4afed1141aa5.jpg)
Стоит версия 3.3.3 (231). Что это за ошибка и как исправить? Приложение системное 
![Screenshot_20200426_152313_com huawei android launcher](https://user-images.githubusercontent.com/22351242/80307553-6a07cf00-87d2-11ea-98c0-d3985ca1fd0a.jpg)

**Comment by ministr91** [comment]
Ещё 1 системное приложение 
![Screenshot_20200426_154849_com adguard android](https://user-images.githubusercontent.com/22351242/80308059-82c5b400-87d5-11ea-9b1a-1dfba6d9a165.jpg)

**Comment by TheHasagi** [comment]
Откройте AdGuard - Настройки - Расширенные - Низкоуровневые настройки и включите функцию pref.https.opportunistic для того, что бы отключить данные уведомления. Это вовсе не ошибка, а уведомление о том, что данное приложение не доверяет сертификату и его HTTPS трафик не может быть отфильтрован.

**Comment by ministr91** [comment]
@TheHasagi, может вы у себя измените настройки https, чтобы в будущем не пришлось вручную добавлять? Есть же список приложений, который не подлежит фильтрации по https.

**Comment by artemiv4nov** [comment]
@ministr91 Да, добавим, во второй бете AdGuard v3.4 будет.

**Comment by ministr91** [comment]
Спасибо, @artemiv4nov, а то @TheHasagi закрыл и даже разобраться не захотел в проблеме, чтобы в будущем у других пользователей не возникало таких вопросов.
