### ISSUE TITLE
Filtering Log Improvement - Collapse Duplicate Consecutive Entries

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#3421]
### Problem Description
Especially when the AG's HTTPS certificate isn't trusted by a browser &/or when using DNS-blocking, the AG filtering log fills up with many duplicate consecutive blocks that're only different by some milliseconds' timestamp.  This unnecessarily loads up the log, sometimes more than a dozen entries @ a time.

### Proposed Solution
Optionally, collapse the entries into 1, & have the individual timestamps detailed _w/in_ that 1 entry when tapped.

### Alternatives Considered
Perhaps do this for *non*consecutive entries, but that may not be _as_ useful.

### Additional Information
![Screenshot_20200428-223141](https://user-images.githubusercontent.com/185902/80556369-5bbbdd80-89a1-11ea-9d7b-91dab484004c.png)

**Comment by Nzzyme** [comment]
Good idea. It was suggested by me earlier.

https://github.com/AdguardTeam/AdguardForAndroid/issues/1951


https://github.com/AdguardTeam/AdguardForAndroid/issues/1950

**Comment by TPS** [comment]
I guess the only clarification over that request, would be that DNS be treated the same as an app for this purpose.  But, otherwise, precisely the same.

**Comment by Nzzyme** [comment]
> I guess the only clarification over that request, would be that DNS be treated the same as an app for this purpose. But, otherwise, precisely the same.

Yes, I would agree

**Comment by TPS** [comment]
Might have underlying problem solved by #5599?

**Comment by TPS** [comment]
Trying again in https://github.com/AdguardTeam/AdguardForAndroid/issues/5849
