### ISSUE TITLE
HTTPS-s filtering error for the "providers media" system app

### ISSUE THREAD

**Issue by zovihuxij** [AdguardTeam/AdguardForAndroid#3425]
Сразу же после обновления приложения до версии 3.4 beta 1 стала постоянно появляться данная ошибка.
<details><summary>Скриншоты</summary>

![image](https://user-images.githubusercontent.com/20907093/80899688-045b9b80-8d1a-11ea-904b-de7fabf2b8ca.png)
![image](https://user-images.githubusercontent.com/20907093/80899745-09204f80-8d1a-11ea-900b-88dbe868cf3d.png)

</details>

**Comment by TheHasagi** [comment]
@zovihuxij 

Проверьте в низкоуровневых настройках (AdGuard - Настройки - Расширенные - Низкоуровневые настройки), что функция pref.https.opportunistic включена.

**Comment by admitrevskiy** [comment]
@zovihuxij 
Похоже, что приложение `Хранилище мультимедиа` специфично для вашего телефона/прошивки/оболочки
Чтобы добавить правило в [список исключений](https://github.com/AdguardTeam/HttpsExclusions) мне необходимо знать имя пакета. На экране настроек приложения [(последний скрин)](https://user-images.githubusercontent.com/20907093/80899745-09204f80-8d1a-11ea-900b-88dbe868cf3d.png) откройте доп. меню в правом верхнем углу и нажмите на пункт `Техническая информация` - можно скопировать в этот тред или прислать скриншот. 
Если аналогичная нотификация возникает для других доменов - прикрепите пожалуйста скриншоты.

**Comment by zovihuxij** [comment]
@admitrevskiy 
`Имя пакета: com.android.providers.media
Uid: 10012 shared with:
com.android.providers.downloads.ui
com.android.mtp
com.android.providers.downloads
Тип: System privileged
Версия: 9 (906)
Целевой SDK: 23`
