### ISSUE TITLE
Application crash when changing from 4G to Wi-Fi in Local HTTP Proxy Mode

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3431]
### Issue Details

- **AdGuard version:**
  - 3.4.99
- **Filtering mode:**
  - Local HTTP Proxy (Manual)
- **Device:**
  - WIKO WIM Lite
- **Operating system and version:**
  - Android 7.1.1
- **Root access:**
  - No

### Expected Behavior
Changing networks shouldn't cause an app crash

### Actual Behavior
App crashes when changing from Wi-Fi to LTE (and vice versa)

### Screenshots

Unavailable

### Logs

See support ticket 2665695

**Comment by artemiv4nov** [comment]
@akmLaVx We fixed this issue, let ask the user to test on the latest nightly version.

**Comment by Barzaquaa** [comment]
> @akmLaVx We fixed this issue, let ask the user to test on the latest nightly version.

Hi, thank you. It works fine now with the new update of the nightly version.
