### ISSUE TITLE
DNS traffic leak.!

### ISSUE THREAD

**Issue by lessload** [AdguardTeam/AdguardForAndroid#3434]
### Issue Details

- **AdGuard version:**
  - v3.3.3
- **Filtering mode:**
  - Local VPN, DNSCrypt (Adguard)
- **Device:**
  - Mi CC9 Pro (Xiaomi)
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

App should always filtering traffic or have something like Kill Switch. and stop only when disable protection. 

### Actual Behavior

I found DNS traffic leak. It's show in my Pi-hole. mobile connect to `data.mistat.intl.xiaomi.com` and some other when press check update block list or while lockscreen.

### Additional Information

Problem while lockscreen may from MIUI (android on xiaomi) do something like sleep your app. i'm not sure about it. [already set battery - No restrictions / enabled - auto start] but when update blocklist it couldn't leak the traffic. it shoult have something like kill switch to protect the traffic.

**Comment by TheHasagi** [comment]
@lessload 

Hello!

Perhaps you restarted the application at this moment - this may lead to some leakage when protection is restarting. To avoid such case, turn on Always-on VPN feature on your device for AdGuard.

Go to System settings - VPN - AdGuard - enable Always-on VPN function.

**Comment by lessload** [comment]
as i test by your setting it still leak some dns traffic when i press update.

**Comment by lessload** [comment]
mark as Duplicate of #3447
