### ISSUE TITLE
Add support for Samsung "Multi Window" mode (Android < 7.0 users)

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdguardForAndroid#3435]
# Samsung "Multi Window" mode
![Samsung_Galaxy_Tab_S_10 5_inches](https://user-images.githubusercontent.com/4764956/81015799-98834b00-8e5f-11ea-8516-d22f415d9e74.png)

## Context
Long before Android natively supported multi-window management with Android 7.0, Samsung had launched its system. The purpose of this request is to make _AdGuard for Android_ compatible with this system, which can be used on some tablets but also on some large screen smartphones from the Samsung brand.

## Request
Could you consider adding this simple functionality to implement (see the [two lines of code required](https://github.com/bitwarden/mobile/pull/877/files) and the [detailed description](https://github.com/bitwarden/mobile/pull/877) of my merged _pull request_ on the Bitwarden project)? Your app seems to resize correctly in all sizes (tested on Android 7+), so no problem!

<details>
<summary>Additional code potentially required in your case (<em>AndroidManifest.xml</em> too) ...</summary>

```xml
<!-- <intent-filter> tag of the desired activity -->
<intent-filter>
    <!--
    Your existing lines of code below, including ...
    -->
    <category android:name="android.intent.category.LAUNCHER" />

    <!--
    This line only needs to be added in the case of a customized default activity
    (or if you want to launch a very specific activity instead,
    when the AdGuard icon in the OS sidebar is tapped)
    -->
    <category android:name="android.intent.category.MULTIWINDOW_LAUNCHER" />
</intent-filter>
```

</details>

## Purpose
To be able to make quick adjustments (regarding the rules of a website being visited for example) on these devices, in parallel with the surfing session. As allowed by the browser extension on a computer.

### _Thanks in advance!_ :thumbsup:

**Comment by TheHasagi** [comment]
This function is available. Check with the latest release version.

**Comment by contribucious** [comment]
@TheHasagi Thank you for your responsiveness! :thumbsup:

However, tested just now with the latest release/stable version `3.4` (+ restart of the tablet) and ... the possibility is not present in my case. The AdGuard icon does not appear in the OS sidebar (nor is it available for manual addition by the user).

Then tested with the `3.5 nightly 1` and there either, possibility not present.

As nothing appears on this subject in the changelog (neither [stable](https://adguard.com/en/versions/android/release.html), nor [beta](https://adguard.com/en/versions/android/beta.html), nor [nightly](https://adguard.com/en/versions/android/nightly.html)), perhaps you are talking about the `3.5 nightly 2` not yet available at the moment. So I'm going to wait and see.

___
### P.S.

**Just to make it clear:** we are talking about, in this case, the _specific_ support required for these Samsung devices with Android 6.0 Marshmallow or lower (as can be seen [here](https://github.com/bitwarden/mobile/pull/877/files)).

:arrow_right: _Not_ to be confused with the native/built-in multi-window support available since Android 7.0. For the latter, no modification is required in the applications to add the support.

**Comment by contribucious** [comment]
> This function is available. Check with the latest release version.

Hello @TheHasagi.

Are you probably talking about my "Purpose" section?

Two things therefore:
1) Having the ability to open _AdGuard for Android_ in multi-tasking (side-by-side, with any app) allows other things as well. So, useful anyway.
2) You are aware that the quick action "Assistant" from the notification is only available from Android 7, in other words my solution remains useful for Android 6 and below (for these Samsung devices, of course).

:arrow_right_hook: Taking these two points into account, could you consider reopening this issue (as well as the [similar one for LG](https://github.com/AdguardTeam/AdguardForAndroid/issues/3436))? Thanks.

**Comment by contribucious** [comment]
@admitrevskiy Hello! What do you think of that, from your side? _Thank you in advance!_
