### ISSUE TITLE
Add support for LG "Dual Window" mode (Android < 7.0 users)

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/AdguardForAndroid#3436]
# LG "Dual Window" mode
![LG_Dual_Window_on_smartphone](https://user-images.githubusercontent.com/4764956/81095884-ea7eac00-8f05-11ea-9839-9efec586cbe3.jpg)

## Context
Long before Android natively supported multi-window management with Android 7.0, LG had launched its system. The purpose of this request is to make _AdGuard for Android_ compatible with this system, which can be used on some tablets but also on some large screen smartphones from the LG brand.

## Request
Could you consider adding this simple functionality to implement (see the [only line of code required](https://github.com/bitwarden/mobile/pull/878/files) and the [detailed description](https://github.com/bitwarden/mobile/pull/878) of my merged _pull request_ on the Bitwarden project)? Your app seems to resize correctly in all sizes (tested on Android 7+), so no problem!

## Purpose
To be able to make quick adjustments (regarding the rules of a website being visited for example) on these devices, in parallel with the surfing session. As allowed by the browser extension on a computer.

### _Thanks in advance!_ :thumbsup:

**Comment by TheHasagi** [comment]
This function is available. Check with the latest release version.

**Comment by contribucious** [comment]
@TheHasagi Thanks for your rapidity!

#### However, see my remark section [here](https://github.com/bitwarden/mobile/pull/878) or below:

<details>
<summary>Read me ...</summary>

## Remark
:point_right: Having neither LG tablet nor LG smartphone compatible with "Dual Window" mode allowing me to test this, any feedback is welcome. Although LG has made it as simple as possible to implement (only one line of code to add).

</details>

:arrow_right_hook: _So I trust the AdGuard developer team for the correct implementation (and here too, **any feedback from users with a LG device compatible with "Dual Window" mode to test this functionality is welcome** :thumbsup:)._

___
:information_source: As a modification carried out at the same time as that for the support of Samsung peripherals, see also [this comment](https://github.com/AdguardTeam/AdguardForAndroid/issues/3435#issuecomment-632903657), though.

**Comment by contribucious** [comment]
@admitrevskiy Hello! What do you think of that, from your side? _Thank you in advance!_
