### ISSUE TITLE
Parser engine error

### ISSUE THREAD

**Issue by jncr** [AdguardTeam/AdguardForAndroid#3438]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Current easylist / adguard base list contains a regex which doesn't compile and prevents requests from completing

- **AdGuard version:**
3.1.0 (1.3.347cl)
- **Filtering mode:**
VPN
- **Device:**
Samsung s8
- **Operating system and version:**
Android 9
- **Root access:**
No

### Expected Behavior

Images load

### Actual Behavior

Images fail to load, instead generating an error screen

### Screenshots

<details><summary>Screenshot:</summary>
[SmartSelect_20200517-170945_Chrome](https://user-images.githubusercontent.com/3667695/82157679-e6924880-987a-11ea-9c59-430e5511e91e.jpg)

</details>

### Additional Information

Example url: https://i.guim.co.uk/img/media/a9c26bbea1ba7e1549e5155dc140ba005e6804fe/0_277_3060_1836/master/3060.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=2b05365c6caa608a877cf52428950bce

Adguard logs:
```
00:00:38.862 [Thread-260] WARN  Native.urlfilter - urlfilter_compile_rule(): Couldn't PCRE-compile rule '/^https:\/\/([a-z]+\.)?sythe\.org\/\[=%#@$&!^].*[\w\W]{20,}/$image' -- ] is an invalid data character in JavaScript compatibility mode
00:00:38.924 [Thread-260] WARN  Native.urlfilter - match_rule(): Delayed compilation of rule '/^https:\/\/([a-z]+\.)?sythe\.org\/\[=%#@$&!^].*[\w\W]{20,}/$image' failed
```

Easylist rule: https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L2104

![Regular expression visualization](https://www.debuggex.com/i/Q0M2CCR7ZLraI1Ol.png)

[Debuggex Demo](https://www.debuggex.com/r/Q0M2CCR7ZLraI1Ol)

**Comment by artemiv4nov** [comment]
@jncr Please check on the latest version (v3.4 beta 2).

**Comment by jncr** [comment]
@artemiv4nov fixed, thanks
