### ISSUE TITLE
Add the app to the exclusions list

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3439]
@adguard-bot commented on [Mon May 11 2020](https://github.com/AdguardTeam/AdguardFilters/issues/55253)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.google.android.apps.cultural](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.cultural)
### Comment
> The app won't load of adguard is running

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/4Zotdko.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/tQNh4y9.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3.3 (231)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Malware Domains Blocklist<br/><br/><b>Language-specific:</b><br/> Estonian List, <br/>AdGuard Russian

---

@Alex-302 commented on [Fri May 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/55253#issuecomment-629164977)

Not reproduced.
@TheHasagi please check on Android 10.

**Comment by TheHasagi** [comment]
Please, add this package to the exclusion list.

**Comment by Revertron** [comment]
The investigation shows that this application is very sensitive to any blocking of ads or trackers.
User has only one solution - to fully exclude this app from filtering. We will not do it on our end.
