### ISSUE TITLE
Filtering doesn't work after it's had been interrupted

### ISSUE THREAD

**Issue by domebacsi** [AdguardTeam/AdguardForAndroid#3440]
On Android 11 Developer Preview 4 filtering doesn't work after it had been interrupted

- **AdGuard version:**
  - 3.5 nightly 1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 2 XL
- **Operating system and version:**
  - Android 11 Developer Preview 4 (RPP4.200409.015)
- **Root access:**
  - No

https://streamable.com/o645xj
(even though AdGuard states that the protection is on, but there's no VPN key at the status bar, and filtering doesn't work)

**Comment by artemiv4nov** [comment]
@domebacsi the link doesn't open.

Can you collect the debug logs and send them to devteam@adguard.com, please?

Here are instructions on how to collect the debug logs: https://kb.adguard.com/en/android/solving-problems/log

**Comment by domebacsi** [comment]
This was an Android 11 bug, every VPN app had this issue. Beta 2 seemingly fixed it.
