### ISSUE TITLE
Google play does not accept our certificate

### ISSUE THREAD

**Issue by desperanish** [AdguardTeam/AdguardForAndroid#3442]
In the name of GOD
Hello to everyone in AdGuard (Most useful app in Android).
I have a problem with Google play (store).
This app does not accept AdGuard certificate.

And shows errors in notification bar.
Are you have an idea to resolve this problem?
Thanks

**Comment by desperanish** [comment]
![Screenshot_۲۰۲۰۰۵۲۳-۰۴۴۷۴۰_Package installer](https://user-images.githubusercontent.com/11538368/82718673-23b26c80-9cb9-11ea-8e12-f5a1808b9c5f.jpg)

**Comment by TheHasagi** [comment]
@desperanish 

Hello, seems like you've manually enabled HTTPS filtering for Google Play, at this moment there are nothing we can do with it so just disable it for Google Play.
