### ISSUE TITLE
Add an "Automated" DNS rotation mode

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3443]
### Problem Description

As described by user:

_One thing you could add though (if that's possible) is a function to automatically rotate the DNS-servers, so that I don't have to it manually. I heard that Mozilla got criticized for making Cloudflare DoH the default in the US, because it would centralize a lot of DNS-queries at one provider. So it would be useful if the app automatically changed the servers from a list of favorites from time to time._

### Proposed Solution

Add a separate "Automated" mode which rotates between a user-defined set of secure DNS servers every once in a while.

### Alternatives Considered

Query multiple servers and use the fastest one?

**Comment by snhv** [comment]
Great idea!

**Comment by Ilithy** [comment]
@snhv: I agree, extremely interesting

**Comment by snhv** [comment]
I just found out that this is something Yoga DNS already can do. But I'll wait for AdGuard.

**Comment by Ilithy** [comment]
@snhv: indeed, thanks for the discovery, but two things: the first, YogaDNS is only available for Windows; and second thing, by creating a DNS server pool, Yoga uses them randomly, that's fine, but we should also be able to choose a delay between the use of each server, this would be a huge improvement in DNS management in adGuard

**Comment by artemiv4nov** [comment]
As a good solution, please use our Automation API to rotate DNS servers on your way.
