### ISSUE TITLE
com.avito.android

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3444]
@adguard-bot commented on [Fri May 22 2020](https://github.com/AdguardTeam/AdguardFilters/issues/55878)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.avito.android](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.avito.android)
### Comment
> Если провести перезапуск adguard, то проблема временно исчезает. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/1PizGy4.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/i82yIKw.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.4 (120)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Custom filter subscriptions: |

**Comment by TheHasagi** [comment]
Скорее всего так приложение реагирует на смену типа сети, повторяется ли такое без WiFi?

**Comment by TheHasagi** [comment]
Closed. Should be reopened if needed.
