### ISSUE TITLE
Incorrect behavior of filters update settings

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3445]
### Issue Details

- **AdGuard version:**
  - 3.4(120-1.5.269cl)

### Expected Behavior

Once you have turned off automatic filter updates, you cannot select their update period.

### Actual Behavior

But if you log out of the application and go back in. This feature will be available.
Pay attention to the screenshots.

### Screenshots

<details><summary>Normal:</summary>

![image](https://user-images.githubusercontent.com/49645813/82930028-5e542780-9f8d-11ea-9382-2c6e2e0b593b.png)

</details>

<details><summary>Bug:</summary>

![image](https://user-images.githubusercontent.com/49645813/82930044-6744f900-9f8d-11ea-807a-64659934e61f.png)

</details>

### Additional Information

Information provided **Apoorva Tendulkar**

**Comment by artemiv4nov** [comment]
The UI solution has been reworked since v4.0.
