### ISSUE TITLE
com.overlook.android.fing

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3446]
@adguard-bot commented on [Sat May 23 2020](https://github.com/AdguardTeam/AdguardFilters/issues/55960)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.overlook.android.fing](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.overlook.android.fing)
### Comment
Username: @AnthonyBe
> AG is causing the internet speed test feature of the Fing app to not work.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/YnvUxAS.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vYcZ0xn.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.4 (120)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your IP address (209.141.53.254)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/> Spam404, <br/>NoCoin Filter List, <br/>Malware Domains Blocklist
Custom filter subscriptions: |

**Comment by TheHasagi** [comment]
@AnthonyBe

Please, disable the filtering for the application and check again.
