### ISSUE TITLE
Slow DNS Lookup with DNS Filtering enabled if one or more servers are not available

### ISSUE THREAD

**Issue by Tornhoof** [AdguardTeam/AdguardForAndroid#3448]
### Issue Details

- **AdGuard version:**
3.4
- **Filtering mode:**
Local VPN
- **Device:**
OnePlus 5
- **Operating system and version:**
Android 9
- **Root access:**
No

### Expected Behavior

Fast DNS Lookup with DNS Filtering enabled if one or more servers are not available

### Actual Behavior

After upgrading to 3.4 DNS lookup with custom DNS Servers now take 10 seconds.

### Additional Information

I use a custom DNS server configuration in AdGuard (since Version 2.x), consisting of 4 DNS Servers.
192.168.0.1
192.168.0.2 
8.8.8.8
1.1.1.1
(parallel lookup enabled)

I put my local DNS servers first, otherwise I run into DNS lookup problems in my WLAN (the public servers would return nxdomain for my private LAN servers)
As soon as I leave the WLAN (and the configuration remains the same) each DNS lookup takes 10 seconds, even though Parallel Lookup is enabled.

I downgraded to 3.3.3. and everything works fast again and as your changelog mentions the switch to a different dns library, I guess 3.4 broke something here, from the behaviour the parallel lookup feature would be my best guess (as it would then need to wait for a timeout of each server).

**Comment by gontazaka** [comment]
I also found the same problem.
Probably "Use parallel queries..." feature has been removed.

AdGuard for Android 3.4 seems to be working as follows:
1) Sends a query to "192.168.0.1" ...and Timeout [pref.dns.timeout=3000ms]
2) Sends a query to "192.168.0.2." ...and Timeout [pref.dns.timeout=3000ms]
3) Sends a query to "8.8.8.8". Succeed!
 **It's not a parallel😢**

implementation is here..?
https://github.com/AdguardTeam/DnsLibs/blob/e59fa6bed0b565a2390d92ce499e035d3cf645bb/proxy/src/dns_forwarder.cpp#L899

**Comment by admitrevskiy** [comment]
Hi! 
As you've noticed `Parallel queries` option from DnsProxy is not available for now and it will be implemented in new DnsLibs ASAP.
Moreover we are going to add upstreams sorting by RTT to speed up consistent resolve: https://github.com/AdguardTeam/DnsLibs/issues/39

**Comment by artemiv4nov** [comment]
This issue will be fixed after task #3448 will be resolved, I'll close this task.
