### ISSUE TITLE
msh.amazon.com - DNS filtering issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3449]
@adguard-bot commented on [Thu May 28 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56267)

### Issue URL (Ads)
 [http://msh.amazon.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fmsh.amazon.com)
### Comment
Username: @infinitelight
> Device: Amazon Kindle Fire HD 10, 7th Edition, running stock Android 5.1.1
> I cannot use said device for screenshots so I am sending this from a different device.
> For some reason, as you can see in the photo, the DNS user filter rule ||msh.amazon.com was not applied at 23:09:54, but at 23:10:06 it WAS applied. No other rules were skipped, as you can also see in the screenshot. At the time it failed I was disconnected from the internet (hence the SERVFAIL). I didn't reconnect until 23:16:06.
> I don't have logs from this, as far as I know. My logging is set to Errors Only. I doubt this would be captured by that.
> Please reach out to me if you can. I rarely login to or even visit github. Thank you.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/YPlYqWg.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 5.1.1
AdGuard version: | 3.5 nightly 1
Browser: | Not a browser
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing first-party cookies (60), Self-destructing third-party cookies (5), Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties (example.org), Hide your Referrer from third-parties, Hide your IP address (107.178.250.75)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>EasyList, <br/>AdGuard Mobile Ads, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> Fanboy Anti-Facebook List, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Web Annoyances Ultralist, <br/>(Obsolete) Anti-Adblock Killer \| Reek, <br/>AdGuard Annoyances, <br/>EasyList Cookie List, <br/>Adblock Warning Removal List, <br/>Fanboy's Annoyances, <br/>I don't care about cookies, <br/>(Obsolete) Prebake<br/><br/><b>Security:</b><br/> Spam404, <br/>Malware Domains Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental, <br/>AdGuard Simplified domain names, <br/>BarbBlock<br/><br/><b>Language-specific:</b><br/> Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>KAD - Przekręty, <br/>ChinaList+EasyList, <br/>AdGuard Spanish/Portuguese, <br/>RU AdList: BitBlock, <br/>Fanboy's Swedish, <br/>List-KR, <br/>EasyList Hebrew, <br/>Adblock List for Finland, <br/>ABPindo, <br/>AdGuard Turkish, <br/>Frellwit's Swedish Filter, <br/>CJX's Annoyance List, <br/>Easylist Spanish, <br/>Polskie Filtry Ciasteczkowe, <br/>YousList, <br/>Latvian List, <br/>road-block, <br/>Xfiles, <br/>EasyList Lithuania, <br/>EasyList Italy, <br/>Polish Anti Adblock Filters, <br/>Fanboy's Vietnamese, <br/>Estonian List, <br/>RU AdList, <br/>ABPVN List, <br/>(Obsolete) Schacks Adblock Plus liste, <br/>EasyList Polish, <br/>AdGuard German, <br/>EasyList Czech and Slovak, <br/>Bulgarian list, <br/>Liste AR, <br/>FanboyEspanol, <br/>AdGuard Japanese, <br/>Polski Antyirytujący Dodatek Specjalny, <br/>AdGuard French, <br/>EasyList Germany, <br/>Icelandic ABP List, <br/>AdGuard Dutch, <br/>ROList, <br/>AdGuard Russian, <br/>EasyList Dutch, <br/>(Obsolete) Korean Adblock List, <br/>RU AdList: Counters, <br/>EasyList China, <br/>Polskie Filtry Wewnętrzne, <br/>Dandelion Sprout's Nordic Filters, <br/>Polskie Filtry Elementów Irytujących, <br/>Polskie Filtry Społecznościowe

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/DnsLibs #74](https://github.com/AdguardTeam/DnsLibs/issues/74) via [**ZenHub**](https://www.zenhub.com/)
