### ISSUE TITLE
Notification Requirements (AdGuard for Android/AdGuard VPN)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3453]
### Problem Description

AdGuard's products on Android are quite heavy with notifications, with a lack of explanation or requirement to have as many as it does.

As seen in the below screenshot, we can see 4 notifications upon AdGuard/VPN starting up.

1. A disssmissable reminder, and
2. 3 app running in background notifications.

I understand the requirement for transactional notifications under the the material notification design guidelines, however this could be better solved.

![2020-06-10 13 04 47](https://user-images.githubusercontent.com/6005161/84222472-03890700-ab1b-11ea-883c-bf15f0af9729.jpg)

### Proposed Solution

My solution to this would be to design an inbuilt notification panel to:

- Split all notifications
- Explain what their purpose is,
- Explain their priority and ramifications of disabling, and
- Notify users when a function wasn't working correctly, rather than requiring 3+ persistent notifications, depending on the users setup.

See below, for an example from Google Pay.

![IMAGE 2020-06-10 13:05:33](https://user-images.githubusercontent.com/6005161/84222499-126fb980-ab1b-11ea-9561-54db99ca6ddd.jpg)

**Comment by artemiv4nov** [comment]
@jslawler You can hide these notifications by long tap on them and going to the device settings.
This is Android functional, not needed to implement it inside applications at the moment.

**Comment by jslawler** [comment]
> @jslawler You can hide these notifications by long tap on them and going to the device settings.
> This is Android functional, not needed to implement it inside applications at the moment.

I realise this, as pointed out in the original post.

The problem is not how to dismiss a notification, it's the abundance of notifications, the lack of explanation as to what each notification channel does, and what effect hiding/dismissing that notification would have on the users system.

**Comment by artemiv4nov** [comment]
So, this issue can transform to "Make descriptions for Notification channels". I think we can improve it in the future.

**Comment by artemiv4nov** [comment]
Well, we describe all notification channels in v4.0
