### ISSUE TITLE
com.fitbit.FitbitMobile

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3454]
@adguard-bot commented on [Wed Jun 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57129)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.fitbit.FitbitMobile](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.fitbit.FitbitMobile)
### Comment
Username: @AnthonyBe
> Only way to get Fitbit app to work is to bypass AG routing entirely in App Management. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/jV0snvE.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/cuD0Om0.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 3.4 (120)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing third-party cookies (180), Hide your Referrer from third-parties (), Hide your Referrer from third-parties
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/> Spam404, <br/>Malware Domains Blocklist, <br/>NoCoin Filter List
Custom filter subscriptions: |

**Comment by TheHasagi** [comment]
@AnthonyBe

Looks like it is ok on my side, check with other DNS and disable third-party filters and check again.
