### ISSUE TITLE
feature: apps management- filter out system apps, disabled, and those without internet permission

### ISSUE THREAD

**Issue by jawz101** [AdguardTeam/AdguardForAndroid#3456]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Problem Description

Hundreds of irrelevant apps to sift through in the apps mgmt screen

### Proposed Solution

Give filters on apps management screen to exclude or include system apps, disabled apps, apps w/o internet permission.

### Alternatives Considered

None

**Comment by jawz101** [comment]
In fact, I would like a setting to exclude controlling system apps at all.  On a trusted device you're more likely to toggle connectivity off on some random system package that may need it one day.

**Comment by artemiv4nov** [comment]
Well, we reworked apps management in v4.0

**Comment by usgrnk** [comment]
Where can I find this option? using v4.12.77

**Comment by TPS** [comment]
@usgrnk It's not available in the reworked (current) UI, either.  The only logic to closing this seems to be that this request was originally intended for the replaced (previous) UI, so it's _technically_ obsolete.  Their backend ticket system seems to require requests to pertain to current code, so 1 would have refile this & garner enough upvotes for it to be considered for implementation.
