### ISSUE TITLE
Добавить возможность исключения доменов из передачи через прокси

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3457]
Здравствуйте,
Хотелось бы иметь возможность добавить домены в белый список, тем самым исключив их из передачи через прокси.
Например:
Все домены передаются через прокси, кроме example.com

Заранее спасибо!

**Comment by TheHasagi** [comment]
@ghost

Все HTTPS домены могут быть добавлены в белый список, если же вы не хотите фильтровать весь домен, то его можно исключить путем добавления правила, подробнее по [ссылке](https://github.com/AdguardTeam/AdguardForAndroid/issues/3457).
