### ISSUE TITLE
Per-App Stealth Setting

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3459]
Currently, there is no stealth setting under Apps Management page of an app. This request is to also include an option for that under Settings.

1. Tap on Menu -> Apps Management
2. Tap on any app from the list.
3. Scroll-down and under 'Settings' section, we see three settings (AdGuard protection, Ad blocking, HTTPS Filtering).

In this section, can you also include a setting named 'Stealth Settings' which we can enable/disable only for that app.

**Comment by Nzzyme** [comment]
Anyone checking this please?

**Comment by Nzzyme** [comment]
A gentle reminder.

**Comment by artemiv4nov** [comment]
It looks like this feature request is not so popular. I'm going to close it.
