### ISSUE TITLE
Feature Request: Shizuku Support

### ISSUE THREAD

**Issue by warmoans** [AdguardTeam/AdguardForAndroid#3461]
There's an app called Shizuku Server, which allows for quicker than root request system api calls that require root/adb.

https://github.com/RikkaApps/Shizuku/blob/master/README.md

I was curious to see if this could be implemented to improve auto-proxy mode. Not that I'm facing a specific problem, but from what I understand, this could speed up auto-proxy mode when/if it requires the system api calls.

**Comment by TheHasagi** [comment]
@warmoans 

As they say in their own documentation:

"Hidden API limitation from Android 9
As of Android 9, the usage of the hidden APIs is limited for normal apps. Please use other methods (such as https://github.com/tiann/FreeReflection)."

So this feature request is no longer relevant.

**Comment by TPS** [comment]
> As of Android 9, the usage of the hidden APIs is limited for normal apps. Please use other methods (such as https://github.com/tiann/FreeReflection)."
> 
> So this feature request is no longer relevant.

@TheHasagi Ok, then, does/will AGa use FreeReflection (or whatever the current best nonroot hidden API access is)?

**Comment by bropines** [comment]
I will support the commentator above, will there be an attempt to use new access methods with a system api?

**Comment by TPS** [comment]
@Swen90 Would supporting Shizuku have any _other_ benefit for AGa?  E.g., per https://github.com/shynoiddev/FireWall-Blocks, [Shizuku can be used to fully block apps from network](https://github.com/celzero/rethink-app/issues/2461) more efficiently than _(only?)_ VPN mode?

Here's a full implementation! https://github.com/AhmetCanArslan/ShizuWall
