### ISSUE TITLE
Not blocking overlay ad on game

### ISSUE THREAD

**Issue by zacx01** [AdguardTeam/AdguardForAndroid#3462]
[x] I am running the latest version
[x] I checked the documentation and found no answer
[x] I checked to make sure that this issue has not already been filed

- 
version 3.4 from May 21, 2020
- **Filtering mode:**
  Local VPN / HTTP Proxy (Auto/Manual))
- **Device:**
  Samsung galaxy note 8
- **Operating system and version:**
Android 7.1.2/Latest
- **Root access:**
No

Game
https://play.google.com/store/apps/details?id=com.tilemaster.puzzle.block.match&hl=en_US
https://i.imgur.com/12LyxKFr.jpg

Turned on https filtering and didn't help either.. The ad is literally un exitable. You have to close the darn app every time it pops up.

**Comment by TheHasagi** [comment]
@zacx01 

Try to clear the app's cache and check again, note that DNS should be enabled to maximize the ad-blocking functionality against that ads.

**Comment by TheHasagi** [comment]
Closed due of no response. Will be reopened if needed.
