### ISSUE TITLE
Add de.number26.android to the exclusions list

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3463]
# Problem Description

N26 is a legitimate German banking app which functionality is currently blocked by AdGuard. 

### Proposed Solution

Add the app and associated domains to app/HTTPS exclusions by default.

### Original Submission
See support ticket 2243709

**Comment by TheHasagi** [comment]
App package - de.number26.android
[Google Play](https://play.google.com/store/apps/details?id=de.number26.android)

**Comment by Revertron** [comment]
Duplicate #1287
