### ISSUE TITLE
Filter update is stuck

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3467]
Купил себе телефон на андроид 10, установил AdGuard но когда включил ручное обновление, то фильтры продолжает обновлять. Если посмотреть по дате обновления то вроде все корректно обновляется. Но кружок вовремя обновления крутится без остановки.

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

Запишите пожалуйста короткое видео с воспроизводимой проблемой.

**Comment by GdeZsqyAY** [comment]
По экспериментировал и понял в каких случаях обновление фильтров зависает. Ситуация вот какая, после включения или же перезагрузки все работает отлично, но если же он полежит включенным не которое время ( сколько надо полежать включенным сказать не могу ), то при запуске обновления в ручном режиме, обновление фильтров зависает. Все остальное же проверяется на обновление без проблем.

**Comment by TheHasagi** [comment]
Может быть причуды оболочки, все же запишите детальное видео с воспроизводимой проблемой и пришлите журналы событий согласно [данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log) на devteam@adguard.com в теме письма обязательно укажите номер задачи #3467.

**Comment by GdeZsqyAY** [comment]
> Может быть причуды оболочки, все же запишите детальное видео с воспроизводимой проблемой и пришлите журналы событий согласно [данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log) на [devteam@adguard.com](mailto:devteam@adguard.com) в теме письма обязательно укажите номер задачи #3467.

Отправил. Хотелось бы получить ответ на чей стороне именно проблема.

**Comment by GdeZsqyAY** [comment]
@TheHasagi

> Может быть причуды оболочки, все же запишите детальное видео с воспроизводимой проблемой и пришлите журналы событий согласно [данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log) на [devteam@adguard.com](mailto:devteam@adguard.com) в теме письма обязательно укажите номер задачи #3467.

Отправил. Хотелось бы получить ответ на чей стороне именно проблема.

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

Не получил письма с логами, попробуйте отправить еще раз.

**Comment by GdeZsqyAY** [comment]
@TheHasagi

Вот подтверждение того, что было отправлено то, что Вы просили.

<a href="https://fastpic.ru/view/113/2020/0706/_d12a4bb0a4d732b1e0b00c608b4bf016.png.html" target="_blank"><img src="https://i113.fastpic.ru/thumb/2020/0706/16/_d12a4bb0a4d732b1e0b00c608b4bf016.jpeg" border="0"></a>

**Comment by GdeZsqyAY** [comment]
@TheHasagi

Вот отправил повторно само письмо

<a href="https://fastpic.ru/view/113/2020/0706/_d314c36f07031b5ca814e169480b3ff8.png.html" target="_blank"><img src="https://i113.fastpic.ru/thumb/2020/0706/f8/_d314c36f07031b5ca814e169480b3ff8.jpeg" border="0"></a>

А вот письмо было создано заново

<a href="https://fastpic.ru/view/113/2020/0706/_700e664049351592306a67f6293d0f20.png.html" target="_blank"><img src="https://i113.fastpic.ru/thumb/2020/0706/20/_700e664049351592306a67f6293d0f20.jpeg" border="0"></a>

**Comment by GdeZsqyAY** [comment]
В последний раз даже перезагрузка не помогла, обновление фильтров не отрабатывает ( что видно на видео которое отослал вам ). Но несколько дней назад обновление ночью вдруг неожиданно  заработало, но потом так же неожиданно и перестало опять работать.

Ручное обновление у меня работает не понятно как.

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

Получил, спасибо. Отпишу тут по мере выяснения причины. Пока попробуйте обновиться до [найтли](https://agrd.io/android_nightly) версии и проверить еще раз.

**Comment by GdeZsqyAY** [comment]
> @TheHasagi
 
> Получил, спасибо. Отпишу тут по мере выяснения причины. Пока попробуйте обновиться до [найтли](https://agrd.io/android_nightly) версии и проверить еще раз.

Без обид, но я не являюсь тестером. мне попалась проблема и я сообщил о ней. Так что проверять ничего не буду. У Вас для этого есть огромный штат который этим занимается.

**Comment by GdeZsqyAY** [comment]
@TheHasagi 

Уже неделя прошла как отправил Вам данные. Хотелось бы узнать в чем проблема и когда планируется ее решение?

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

Разработчики еще в процессе решения задачи. Если вы не хотите обновляться до найтли версии (в которой возможно проблема не повторяется), то решения придется ждать вплоть до релизной версии приложения.

**Comment by GdeZsqyAY** [comment]
@TheHasagi 

> Если вы не хотите обновляться до найтли версии (в которой возможно проблема не повторяется).

Не хочу ставить то, что не является стабильной версией. В версии 3.4 у меня проблема только в обновлении фильтров, а в Вашей найтли версии не известно какие проблемы могут появиться.

> То решения придется ждать вплоть до релизной версии приложения.

До релиза какой версии - 3.5, 3.6, 3.7 и так далее? Нужна конкретика, а не просто отписка для пользователя, что бы он отстал и думал, что его проблема решается.

> Разработчики еще в процессе решения задачи.

Значит он в курсе из за чего проблема. Но как быть вот с этими Вашими словами?

>  Отпишу тут по мере выяснения причины.

Как можно Вам верить если Вы же не держите свои слова???

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

> Не хочу ставить то, что не является стабильной версией. В версии 3.4 у меня проблема только в обновлении фильтров, а в Вашей найтли версии не известно какие проблемы могут появиться.

Проблема скорее всего носит индивидуальный характер, т.к. на устройствах с EMUI такого поведения как у вас не наблюдается.

> До релиза какой версии - 3.5, 3.6, 3.7 и так далее? Нужна конкретика, а не просто отписка для пользователя, что бы он отстал и думал, что его проблема решается.

До ближайшего - 3.5 в случае, если вы не хотите обновляться до найтли версии.

> Значит он в курсе из за чего проблема. Но как быть вот с этими Вашими словами?

Это значит, что **задача** стоит в очереди решения, как я уже писал выше - данное поведение не повторяется и не воспроизводится на устройствах с EMUI OS (Huawei/Honor). Вы прислали необходимые логи с данными, если их будет недостаточно я отпишу тут в задаче.

**Comment by GdeZsqyAY** [comment]
@TheHasagi

Сделал я так как Вы просили и результат получился спорный. С одной стороны обновления работают, а с другой стороны работают не так как должны. Вот видео и поглядите сами.

https://www.youtube.com/watch?v=njWV75WGMS0&feature

Вот логи для анализа - https://www.upload.ee/files/12049073/adguard_logs_3.5.29_2307_132214.zip.html

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

Вижу, логи переданы разработчикам.

**Comment by artemiv4nov** [comment]
@GdeZsqyAY Добрый день! Перепроверьте, пожалуйста, на последней версии найтли.

**Comment by GdeZsqyAY** [comment]
@artemiv4nov

Работает так же как показано на видео выше.

Сейчас обновилось до бета версии. Заметил то, что стало работать медленней и иной раз при обновлении фильтров выдает ошибку и ничего не обновляет.

В Найтли версии обновление работало лучше чем в Бета версии сейчас.

**Comment by artemiv4nov** [comment]
@GdeZsqyAY Добрый день! Я не могу повторить поведение, которое у вас наблюдается.
Я могу понять, почему не происходит обновления на текущей релиз версии – некоторые фильтры были изменены и удалены, поэтому не скачивались.
Однако для бета версии это несколько странное поведение. Можете, пожалуйста, повторить проблему на текущей версии v3.5 beta 2 в дебаг режиме и прислать на devteam@adguard.com?

**Comment by artemiv4nov** [comment]
Механизм обновления фильтров был изменен в версии 4.0. Пожалуйста следите за обновлениями и проверьте снова на 4.0 версии.
