### ISSUE TITLE
AdGuard.apk не устанавливается.

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3468]
У меня телефон **HUAWEI Y6p** и вот его характеристики https://consumer.huawei.com/ru/phones/y6p/specs/

Файл .apk скачан вот отсюда https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.4-release . Во время запуска файла выскакивает сообщение и запуск файла автоматически прекращается.

**Comment by TheHasagi** [comment]
@GdeZsqyAY 

Попробуйте скачать и установить по [ссылке](https://agrd.io/android).
