### ISSUE TITLE
Statistics for the wifi 360 application do not work

### ISSUE THREAD

**Issue by Koruy** [AdguardTeam/AdguardForAndroid#3469]
Statistics for the wifi 360 application do not work 
![Screenshot_20200630-133131](https://user-images.githubusercontent.com/53151866/86116697-8a0b8580-bad6-11ea-8b44-2232c05afdee.png) https://play.google.com/store/apps/details?id=de.android.wifiscanner
[adguard_logs_3.4.120_3006_133013.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4851165/adguard_logs_3.4.120_3006_133013.zip)

**Comment by TheHasagi** [comment]
There are no ads detected in this application. So the statistics are calculated correctly.

**Comment by Koruy** [comment]
There is advertising in this application, statistics do not take it into account, your information is incorrect
![Screenshot_20200703-144956](https://user-images.githubusercontent.com/53151866/86466737-db1cb300-bd3c-11ea-8699-1a74a602b15f.png)
![Screenshot_20200703-145011](https://user-images.githubusercontent.com/53151866/86466751-e243c100-bd3c-11ea-9c6a-6c4ecf7b5ebc.png)
