### ISSUE TITLE
GCM notifications and Firewall rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#347]
Steps to reproduce:
1. Block net access for Skype
2. You'll still get new messages notifications

It's unclear for users that Skype uses GCM so you can't simply block its access to push notifications.

**Comment by Revertron** [comment]
100% that it is GCM. They all use it for pushes.

**Comment by ameshkov** [comment]
The problem is that user is not aware of how GCM works and for him it looks like Facebook app has net access.
Second issue: I don't see GCM in the apps list.

Can we do something with it?

Reassigned this issue to v3.0

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
