### ISSUE TITLE
Statistics do not work in the blackmart application

### ISSUE THREAD

**Issue by Koruy** [AdguardTeam/AdguardForAndroid#3470]
Statistics do not work in the blackmart application
[adguard_logs_3.4.120_3006_133948.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4851228/adguard_logs_3.4.120_3006_133948.zip) https://4pda.ru/forum/index.php?showtopic=215163&view=findpost&p=6391772 https://4pda.ru/forum/index.php?s=&showtopic=215163&view=findpost&p=71070315 
![Screenshot_20200630-134405](https://user-images.githubusercontent.com/53151866/86117641-123e5a80-bad8-11ea-90d7-c30ddfc59c68.png)

**Comment by TheHasagi** [comment]
Seems like it's ok on my side. Much requests and trackers were blocked. Maybe you whitelisted some requests for this app?

**Comment by Koruy** [comment]
In no case was this application added to the white list.  I don’t understand why counters don’t consider blocked ads.

**Comment by TheHasagi** [comment]
@Koruy

Try to update to the latest [nightly build](https://agrd.io/android_nightly) and re-check.

**Comment by Koruy** [comment]
Counters do not count anyway.
![Screenshot_20200703-150252](https://user-images.githubusercontent.com/53151866/86467677-7cf0cf80-bd3e-11ea-97d7-4ea2df423039.png)
![Screenshot_20200703-150239](https://user-images.githubusercontent.com/53151866/86467691-837f4700-bd3e-11ea-8acc-e9001759c0f7.png)

**Comment by Koruy** [comment]
По приложению wifi 360 сканер, скриншоты с рекламой предоставил в запросе который вы закрыли, просьба открыть запрос.

**Comment by TheHasagi** [comment]
@Koruy 

Попробуйте обновиться до последней [найтли](https://agrd.io/android_nightly) версии и попробовать еще раз.

**Comment by Koruy** [comment]
Обновился до новой версии по ссылке. Затем запустил blackmart и wifi 360 обзор полазил по приложениям, затем открыл статистику для этих приложений - опять по нулям.
![Screenshot_20200706-171033](https://user-images.githubusercontent.com/53151866/86603103-3ef8e300-bfac-11ea-91f2-98fb5ef288ab.png)

**Comment by Koruy** [comment]
> Обновился до новой версии по ссылке. Затем запустил blackmart и wifi 360 обзор полазил по приложениям, затем открыл статистику для этих приложений - опять по нулям.
> ![Screenshot_20200706-171033](https://user-images.githubusercontent.com/53151866/86603103-3ef8e300-bfac-11ea-91f2-98fb5ef288ab.png)

![Screenshot_20200706-171005](https://user-images.githubusercontent.com/53151866/86603244-6d76be00-bfac-11ea-8543-fd555dbaecf3.png)

**Comment by Revertron** [comment]
The app is just a swarm of trackers and ads. There is no way to make it load app list without adding whole app to whitelist.
Here are some screenshots to prove that the stats are counted well if it is not in whitelist. But it doesn't work that way :-D

![Screenshot_159733420](https://user-images.githubusercontent.com/105154/90157890-9437c980-dd8e-11ea-8446-880252d35184.png)
