### ISSUE TITLE
Исключения в режиме прокси

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3472]
Здравствуйте,
Прошу добавить функцию белого списка в режиме прокси. Я имею ввиду то, чтобы была возможность при включённом прокси заходить на разрешённые пользователем сайты в обход прокси, то бишь с настоящего ip.

**Comment by TheHasagi** [comment]
Данный функционал уже имеется в приложении:

AdGuard - Content Blocking - Whitelist.
