### ISSUE TITLE
Родительский контроль

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3473]
Здравствуйте,
Прошу добавить функцию родительского контроля в адгуард на андроид.

С проблемами этого решения ознакомлен и предлагаю следующие решения:
1. Проблема:
Возможно удалить приложение и зайти на сайт
Решение:
Запросить права администратора устройства
2. Проблема:
Можно зайти в приложение и вырубить родительский контроль
Решение:
Добавить возможность блокировки приложения пин-кодом

**Comment by TheHasagi** [comment]
В Android есть функция блокировки приложения по пину/паролю, не имеет смысла добавлять такую функцию в приложение.
