### ISSUE TITLE
Waze inbox message is shown for a second and then disappear forever

### ISSUE THREAD

**Issue by stanislav-poliakov** [AdguardTeam/AdguardForAndroid#3476]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.4(200)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 7T
- **Operating system and version:**
  - Android (Oxygen OS 10.0.11.HD65AA)
- **Root access:**
  - No

### Expected Behavior

I open inbox message and I can view it

### Actual Behavior

When I open inbox message I vcan see it for a second and them disappear forever.
When I turn off protection It works.

### Screenshots

<details><summary>Whitelist:</summary>
![image](https://user-images.githubusercontent.com/575209/86439634-9e879200-bd11-11ea-88b6-49d2b1f70fed.png)
</details>

<details><summary>Log:</summary>
![image](https://user-images.githubusercontent.com/575209/86439711-bf4fe780-bd11-11ea-9cc9-611fdf79ecff.png)
</details>

<details><summary>Waze Inbox message detail:</summary>
![image](https://user-images.githubusercontent.com/575209/86439730-c840b900-bd11-11ea-99fe-2b0f68ed5c35.png)
</details>

### Additional Information

I've try analyze filtering log and it doesn't help me
I've added 'waze.com' to whitelist and it doesn't help me
I've try to turn off features and filters one-by-one and no one helps me (what I try)

**Comment by TheHasagi** [comment]
@stanislav-poliakov 

Does HTTPS filtering enabled for this application?

**Comment by stanislav-poliakov** [comment]
Yes
![image](https://user-images.githubusercontent.com/575209/86456920-8b81bb80-bd2b-11ea-8cd9-dce6deadce4a.png)
![image](https://user-images.githubusercontent.com/575209/86456940-90df0600-bd2b-11ea-8906-325dfc3df518.png)
I've add waze.com to whitelist and still doesn't work

**Comment by TheHasagi** [comment]
I meant in AdGuard - Apps management - Waze (Try to disable the whole protection for the application and re-check the case)

**Comment by stanislav-poliakov** [comment]
It was disabled

I enable it, still the issue present

![image](https://user-images.githubusercontent.com/575209/86457738-cd5f3180-bd2c-11ea-8c83-27b487462f73.png)

**Comment by TheHasagi** [comment]
You should disable HTTPS protection for the Waze application. Also, check that third-party filters are disabled, check what DNS may cause the problem. With the base preset I cannot reproduce the issue.

**Comment by TheHasagi** [comment]
Closed due to no response. Will be reopened if needed.
