### ISSUE TITLE
Integrate AG VPN's proxy servers list in AG for Android.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3477]
I watched this. It's inconvenient.
https://www.youtube.com/watch?v=oJv2J9j36b8&feature=youtu.be

Why not integrate AG VPN's all proxy servers list in AG for Android?
After paid users pass a VPN login page in AG for Android, they can choose any AG VPN's proxy servers in the list.
AG VPN's proxy servers in the list means proxy profiles (presets).
After choosing one proxy profile, it'll transfer the chosen proxy server's address, port and user's login data to the original outbound proxy feature of AG for Android in the background.
When enabling AG protection, paid users enjoy both ad blocking and AG VPN's proxy server (via outbound proxy).
Paid users may want to just use AG VPN's proxy servers without installing AG VPN app.

**Comment by TheHasagi** [comment]
@lancelot-moon 

We are working on the integration process between two apps. Please, stand by.

**Comment by GitHuber-dev** [comment]
> @lancelot-moon
> 
> We are working on the integration process between two apps. Please, stand by.

Плохая идея. Если так сделать и вшить приложения друг в друга, то в некоторых странах пользователи могут потерять не только ваш впн но и основное приложение, ведь впн весьма щекотливая тема и не во всех государствах он разрешён....
