### ISSUE TITLE
Embedded ads not blocked in videos of hotstar app

### ISSUE THREAD

**Issue by ganeshjkale** [AdguardTeam/AdguardForAndroid#3479]
### Issue Details
- **AdGuard version:**
  v3.4-120
- **Filtering mode:**
  Local vpn
- **Device:**
  -Realme 2 pro
- **Operating system and version:**
  Android  v9.0
- **Root access:**
  -  No

### Expected Behavior

Ads should be blocked in hotstar videos.
Tried https filter also for hotstar but certificate is rejected by app. 
Also tried another ad block app BLOCK THIS which is able to block ads from hotstar videos
### Actual Behavior
Ads are not blocked

**Comment by ganeshjkale** [comment]
#
[adguard_logs_3.4.120_0407_211510.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/4873101/adguard_logs_3.4.120_0407_211510.zip)

**Comment by zzebrum** [comment]
@ganeshjkale is the problem still reproducible on the latest AdGuard version?

**Comment by ganeshjkale** [comment]
@zzebrum https is not useful for hotstar app stopped working ,also without https video loading is very slow ,seems like ads are not visible in video but are played in background,till that time user have to wait for video loading.

**Comment by TheHasagi** [comment]
@ganeshjkale 

Could you please check it with the latest release version once again?

**Comment by ganeshjkale** [comment]
@TheHasagi  issue still exists with latest v3.6(1)
with https app is unusable and with http only filter ads loads in background but not visible
