### ISSUE TITLE
Add com.homeretailgroup.myargoscard & associated domains to exclusions

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3480]
### Affected App

com.homeretailgroup.myargoscard - Banking app by Argos Card.

### Issue Details

- **AdGuard version:**
  - 3.4.120
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Sony G8342
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Actual Behavior

AdGuard attempts to filter this app, resulting in breaking it

**Comment by TheHasagi** [comment]
Please, add to the exclusions list:

Package name - com.homeretailgroup.myargoscard
[Google Play link](https://play.google.com/store/apps/details?id=com.homeretailgroup.myargoscard&hl=ru)
