### ISSUE TITLE
Microsoft Teams Issues

### ISSUE THREAD

**Issue by Mbarnsdale** [AdguardTeam/AdguardForAndroid#3483]
Running Adguard v3.4 (120)
Pixel 3
Latest security patch on Android Q

When going through Adguard, I can't make or accept teams calls. I'll rarely get notifications. When stop the app going through Adguard, I can make calls without issue

**Comment by artemiv4nov** [comment]
@Mbarnsdale hi!
Can you collect the debug logs, please?

Use the following link to collect logs: https://kb.adguard.com/en/android/solving-problems/log

**Comment by Mbarnsdale** [comment]
Logs sent. Please let me know if this works?
    On Monday, July 13, 2020, 01:14:29 PM CDT, Artem Ivanov <notifications@github.com> wrote:  
 
 


@Mbarnsdale hi!
Can you collect the debug logs, please?

Use the following link to collect logs: https://kb.adguard.com/en/android/solving-problems/log

**Comment by Chinaski1** [comment]
@Mbarnsdale 
Hello there!
Please specify your e-mail address from which you sent a request to support.

**Comment by Mbarnsdale** [comment]
mbarnsdale@yahoo.com
    On Tuesday, July 28, 2020, 05:35:30 AM CDT, Konstantin <notifications@github.com> wrote:  
 
 


@Mbarnsdale
Hello there!
Please specify your e-mail address from which you sent a request to support.

**Comment by Revertron** [comment]
Unfortunately, we couldn't find anything wrong in that log, and any errors were related to the Microsoft Teams server connectivity.
If anyone is experiencing any problems on this matter feel free to send us additional logs to investigate this issue further.
