### ISSUE TITLE
Revert #3012 (After adding a custom user filter rule from the Filtering Log (by clicking on the "Block" button), the button should immediately change from 'Block' to 'Unblock')

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3485]
### Problem Description

The latest nightly build has changed the behavior of filtering log UI after adding a custom user filter rule from the Filtering Log. Issue in question: #3012 

We've received feedback from one of our customers (Helpdesk ID: 2576359):

> Your decision to force the Block button to change to Unblock after creating a user filter entry from the Filtering Log is not a good idea. Here's why: when I choose to block a DNS server I may also choose to make a second entry based on the CNAME. Forcing me to exit and come back is inconvenient. Furthermore, when I choose to make an entry to the non-DNS user filter, many times I choose to make multiple customized entries. Example: for http://example.com/track/beacons/transparentpixel1x1.gif I would make the following user filter entries: ||example.com/track^ & /beacons/ & transparent*.gif & ||*pixel1x1. If I have to exit each time to do this it becomes more burdensome than before -- especially considering the fact that switching Block to Unblock immediately adds very little - if any - value to AdGuard. This "improvement" is actually not an improvement at all, but rather a waste of time for both the dvelopers and users. Please change it back. Thank you.

### Proposed Solution

Either completely revert the change or make Filtering Log switch the "Unblock" button back to "Block" once a user moves from one entry to another.

**Comment by artemiv4nov** [comment]
We already added behavior to change the 'block' button to 'unblock'. Please, see in the latest nightly

**Comment by akmLaVx** [comment]
@artemiv4nov The user does not like this change, that's why I've created the issue. A copy of his thoughts is available in the first message.
