### ISSUE TITLE
Apps management new feature

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3490]
Здравствуйте,
Предлагаю добавить в брендмауэр новую функциональность, а именно функцию "разрешено только при использовании". То есть, при активации этой функции, приложение не сможет выходить в интернет, если оно не используется пользователем на данный момент.

**Comment by Mav3r1x** [comment]
If implemented correctly, this would be a great privacy feature. And by current, I mean adguard shouldn't restart protection when the disabled app is run.

**Comment by artemiv4nov** [comment]
Такой функционал уже есть, правда работает он через явное разрешение от пользователя.
