### ISSUE TITLE
Улучшения режима прокси

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3491]
Здравствуйте,
Предлагаю добавить в режим прокси следующие функции:
1. Включён **_ТОЛЬКО_** на выбранных сайтах
2. Включён на всех сайтах _**КРОМЕ**_ выбранных сайтов.
3. Включен **_ТОЛЬКО_** для выбранных приложений
4. Включён для всех, _**КРОМЕ**_ выбранных приложений.

Пункты **_НЕ_** являются взаимозаменяемыми! Все пункты (начиная от 1 и заканчивая 4) необходимы для комфортного использования!

Это полезно в случае, если человек хочет заходить на заблокированные сайты, но не хочет при этом лазить постоянно в настройки и включать или выключать режим прокси. Также это будет полезно, если нужно заходить через прокси _**ТОЛЬКО**_ на определённые ресурсы, ведь используя прокси для всех ресурсов, сильно замедляется интернет.

**Comment by TheHasagi** [comment]
Для таких целей существуют правила исключения и белый/черный список.
