### ISSUE TITLE
com.google.android.apps.nbu.files

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3493]
@adguard-bot commented on [Sun Jul 12 2020](https://github.com/AdguardTeam/AdguardFilters/issues/59143)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=pl](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.nbu.files%26hl%3Dpl)
### Comment
> AdGuard for Android break share files in `Google Files`.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/y9BYOE8.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/RrldYxG.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.4 (120)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances

**Comment by Alex-302** [comment]
Logs:
[adguard transmit.log](https://github.com/AdguardTeam/AdguardForAndroid/files/4919591/adguard.transmit.log)
[adguard receive.log](https://github.com/AdguardTeam/AdguardForAndroid/files/4919593/adguard.receive.log)
There are to logs - from transmitting device and from receiving device.

Also, as I see, one file was partially transmitted.

**Comment by zzebrum** [comment]
please, reopen the issue, if the problem still occurs with the latest AdGuard version.
