### ISSUE TITLE
Cosmetic filtering not working properly

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdguardForAndroid#3494]
### Issue Details

- **AdGuard version:**
  -  v3.4.120
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Moto G5 Plus
- **Operating system and version:**
  -  Android 8.1
- **Root access:**
  -  No

### Expected Behavior

All cosmetic filtering rules present in the enabled filter lists should be enforced properly on every webpage.

### Actual Behavior

Some ad placeholders are not removed even though matching rules are present in the enabled filter lists.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20200716-010419](https://user-images.githubusercontent.com/42700209/87587898-62d0cd00-c700-11ea-993f-dca142cbab23.png)

</details>
<details><summary>Screenshot 2:</summary>

![Screenshot_20200716-010659](https://user-images.githubusercontent.com/42700209/87588143-c65afa80-c700-11ea-85d4-fa6726fc754d.png)

</details>

### Additional Information

In Easylist, both `##div[id^="div-gpt-ad"]` and `##.adSpace` rules are present. But from the screenshots it is clear that these rules were not enforced.

**Comment by artemiv4nov** [comment]
@BlitW0 Hello! Can you reproduce on the latest nightly build, please?

**Comment by Revertron** [comment]
I'm unable to reproduce the problem. Maybe HTTPS filtering went off?

**Comment by BlitW0** [comment]
Still reproducible for me on v3.5 nightly 10, and https filtering is definitely on. Since the applied cosmetic filters do not show up in the filtering log I cannot tell whether the filters are being parsed from Easylist.

**Comment by admitrevskiy** [comment]
The real problem with this issue is the conflict between the two filters: `EasyList` and  `Web Annoyances Ultralist`:

`Web Annoyances Ultralist` changes the layout of a webpage and cosmetic filtering rule from `EasyList` failed to match the container. 

There are 2 ways to fix this problem:
1) Disable `Web Annoyances Ultralist` filter
2) You can whitelist rules from `Web Annoyances Ultralist` filter by adding some rules to the User filter:

```
livemint.com#@$##fixed-header, .no-border.lead-stories { position: relative !important; }
livemint.com#@$##header { position: relative !important; padding: 20px 0 !important; }
livemint.com#@$##leftSec { position: static !important; }
livemint.com#@$#header.sticky .btnSection { margin: 13px 0 0 10px !important; }
livemint.com#@$#header.sticky .headerDate { display: block !important; }
livemint.com#@$#header.sticky .headerIcon { padding-top: 10px !important; }
livemint.com#@$#header.sticky a.logo { width: 215px !important; margin-left: -154px !important; }
```

However, this solution is not universal and you will have to look for a set of exceptions for every site where filters conflict.

**Comment by BlitW0** [comment]
@admitrevskiy Thanks for the resolution.  I have also created an issue for adding logs for cosmetic filter rules, it will be easier to figure out future conflicts once that feature is added.
