### ISSUE TITLE
cannot install the HTTPS certificate and cannot use HTTPS filtering on the latest Tivo Stream 4k TV box

### ISSUE THREAD

**Issue by xnxy2012** [AdguardTeam/AdguardForAndroid#3496]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes ] I am running the latest version
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed

### Problem Description
I adapt to loyal aguard users, and now I have the following problems
I installed adguard on the latest Tivo Stream TV 4k TV box. Other functions are used normally, but I cannot install the HTTPS certificate and cannot use HTTPS filtering, which results in incomplete advertising filtering and poor results.
The specific performance is: the device does not support the installation of HTTPS CA certificates. Device system Android9.0 TV system, please give solutions, thank you very much

**Comment by TheHasagi** [comment]
@xnxy2012 

Hello, as you noticed this device is not supported with HTTPS CA installation, the only thing you can do is to use [AdGuard DNS](https://adguard.com/adguard-dns/overview.html#instruction) with your network.
