### ISSUE TITLE
Missed ad in SpeedTest Master

### ISSUE THREAD

**Issue by procheekibreeki** [AdguardTeam/AdguardForAndroid#3497]
### Issue Details
Seeing an ad in an app called SpeedTest Master

- **AdGuard version:**
 3.4
- **Filtering mode:**
 DNS filter is enabled using the Adguard DNS
HTTPS Filtering Enabled
- **Device:**
 Galaxy A10
- **Operating system and version:**
Android 10
- **Root access***
No

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
@procheekibreeki 
Hello there!
Please confirm,  did you send the log files to the support team?
If yes, which email address was specified?

**Comment by procheekibreeki** [comment]
I did not but I can sned them

**Comment by admitrevskiy** [comment]
@procheekibreeki Hi!
Could you please report this issue via AdGuard application? Support -> Send feedback -> Missed ad or tracker

Our 'filters' team will manage this issue.
