### ISSUE TITLE
Proxy settings Show icon off not functioning

### ISSUE THREAD

**Issue by chromer030** [AdguardTeam/AdguardForAndroid#3498]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

In Proxy settings , when turning **Show notification** on , while **Show icon** is off , still adguard icon is on Status bar.
(Show notification and Show icon in General section is already off).

- **AdGuard version:**
  - `3.5.29`
- **Filtering mode:**
  - `Local VPN`
- **Device:**
  - `Lenovo K3 Note`
- **Operating system and version:**
  - `Android 7.1.2`
- **Root access:**
  - `No`

### Screenshots

![Screenshot_20200723-105836](https://user-images.githubusercontent.com/13361552/88258071-7e297280-ccd4-11ea-80e9-c073ac53e06d.png)

**Comment by admitrevskiy** [comment]
@chromer030 Hello!
[Android documentation](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setPriority(int)) is vague for this feature: it says
> The effect may differ slightly on different platforms.

At the same time almost all the devices that I have in stock are working properly and most likely your issue depends on Lenovo UI firmware.

You can manage notifications in system app settings (Apps -> AdGuard -> Notifications). Hope it helps.

**Comment by chromer030** [comment]
Thanks for explanations.
