### ISSUE TITLE
Adguard and Orbot compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#35]
We should check if there any way to use them together?

**Comment by TPS** [comment]
This was a major fuss for me, too, with AB+;  I'll report back on what I find with AG.

**Comment by gshumihin** [comment]
Seems like works fine with this config:
1) Adguard in local proxy mode (tested with auto mode)
2) Orbot as vpn (apps enabled)

**Comment by TPS** [comment]
Is there anyway to set up chain-proxying, as [I mentioned above](https://github.com/AdguardTeam/AdguardForAndroid/issues/35#issuecomment-137484089), for those of us who need that?

**Comment by ameshkov** [comment]
@TPS could you create a feature request for us to add "Outbound proxy" settings?
I can't yet give you the ETA on this, but this is possible

**Comment by TPS** [comment]
I'd like y'all to eventually consider what'd hafta be done to make, e.g., https://github.com/brave/browser-laptop/issues/1185 (but via Orbot & related to #922) work w/ AG in the loop, as well.

**Comment by TPS** [comment]
> _(  __gshumihin__ was unassigned by __TPS___

_No idea how I did that! 😮)_

**Comment by ameshkov** [comment]
@TPS not sure about their requirements for the commercial products. Sent an inquiry, let's wait for the answer.
