### ISSUE TITLE
Исключения КОНКРЕТНЫХ доменов из режима прокси

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3500]
Здравствуйте,
Прошу добавить функцию исключения **КОНКРЕТНЫХ** доменов из режима прокси (я имею ввиду сделать так чтобы пользователь мог сам выбрать какие сайты он не хочет передавать через прокси). На данный момент такая функция полностью отсутствует!!!!!!! Я уже добавлял домен во все исключения (и в белый список, и в исключения https, и создавал правила на подобии "@@||") всё в бестолку. Домен продолжает передаваться через прокси, увы.

Версия адгуарда 3.4

**Comment by dropper1** [comment]
Для проверки и доказательства того что данной функции на данный момент нет, попробуйте сами. Включите режим прокси через Tor (Orbot) и попробуйте сделать так, чтобы подключение к конкретному домену не передавалось через прокси. У вас естественно ничего не получится, так как данная функциональность отсутствует.

**Даже при добавлении домена во все виды исключений его фильтрация прекращается, !!!! НО!!!! он продолжает передаваться через прокси***

**Comment by TheHasagi** [comment]
Приведите конкретные примеры со скриншотами из журнала фильтрации если таковые имеются. Пока закрыто.

**Comment by GitHuber-dev** [comment]
Добавил.
Здесь:
https://github.com/AdguardTeam/AdguardForAndroid/issues/3506
