### ISSUE TITLE
Улучшение смены user agent

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3502]
Здравствуйте,
1. Хотелось бы иметь возможность автоматической смены юзер агент через заданный интервал времени. Это нужно для того, чтобы максимально усложнить трекинг.
2. Также не помешает функция добавления домена в исключения **ТОЛЬКО**  касаемо смены юзер агента. Я имею ввиду сделать так, чтобы для конкретного домена смена юзер агента не работала, а остальные функции модуля "антитрекинг" оставались по-прежнему включёнными

**Comment by TheHasagi** [comment]
Возможно в скором времени такой функционал можно будет реализовать благодаря пользовательским правилам. На данный момент неактуально.

**Comment by GitHuber-dev** [comment]
Прискорбно.
В расширении Random User Agent это реализовано. Тут буквально на несколько дней работы... Не вижу ничего сложного в этой функции, но эта функция способна скрывать личность ещё лучше, имитируя разные гаджеты...
