### ISSUE TITLE
Добавление новых модификаторов

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3503]
Здравствуйте,
Я предлагаю добавить новые модификаторы
**1. $proxy**
Данный модификатор должен исключать домен из передачи через прокси, но при этом сохранять его фильтрацию.
**2. $useragent**
Данный модификатор должен выключать подмену user agent для конкретного домена
**3. $webrtc**
Данный модификатор должен будет выключать блокировку WebRTC для конкретного домена, при этом сохраняя работоспособность остальных функций антитрекинга. Это полезно для сервисов видеовстреч (например Яндекс.Телемост)
**4. $pushapi**
Данный модификатор должен будет отключать функцию блокировки Push API для конкретного домена, при этом сохраняя работоспособность остальных функций модуля "Антитрекинг". Это будет полезно для сервисов почты и чатов.

Примеры использования:
1. example.com^$proxy
2. example.com^$useragent
3. example.com^$webrtc
4. example.com^$pushapi

Спасибо за внимание!

**Comment by Chinaski1** [comment]
В ближайшее время добавление данных модификаторов не планируется.
