### ISSUE TITLE
Добавить кнопку "больше не показывать"

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3504]
Здравствуйте,
Прошу добавить кнопку "больше не показывать" под уведомление "в режиме прокси функционал брандмауэра ограничен". Постоянно созерцать это уведомление сильно раздражает. Прошу добавить кнопку, которая скроет его раз и навсегда.

Речь идёт об этом уведомлении:
![Screenshot_20200725-102708](https://user-images.githubusercontent.com/68769065/88451697-6e8b6480-ce61-11ea-8036-30889a36b632.jpg)

Заранее спасибо!

**Comment by Chinaski1** [comment]
Будет переработано в версии 4.0.
