### ISSUE TITLE
Exclusions problem

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3506]
Здравствуйте,
Как вы и просили уйма скринов.
Это относится к этой issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/3500

Добавил домен в исключения ВЕЗДЕ, но это в бес толку.
![Screenshot_20200727-233954](https://user-images.githubusercontent.com/68875005/88590385-4c613480-d063-11ea-82db-9fe31ed6f4c7.jpg)
![Screenshot_20200727-232446](https://user-images.githubusercontent.com/68875005/88590395-5125e880-d063-11ea-81de-a992dd30f5a4.jpg)
![Screenshot_20200727-232721](https://user-images.githubusercontent.com/68875005/88590396-52571580-d063-11ea-8a5d-80c3fe3b5ee3.jpg)
![Screenshot_20200727-232740](https://user-images.githubusercontent.com/68875005/88590399-53884280-d063-11ea-84b3-10fedcd38446.jpg)
![Screenshot_20200727-233034](https://user-images.githubusercontent.com/68875005/88590401-5420d900-d063-11ea-8ffa-42eef01f04ae.jpg)

После всех манипуляций домен продолжает передаваться через прокси:
![Screenshot_20200727-233208](https://user-images.githubusercontent.com/68875005/88590515-85010e00-d063-11ea-9ee9-054b65376c2d.jpg)

**Comment by TheHasagi** [comment]
К сожалению, в настоящий момент полностью исключить домен из трафика невозможно. Исключения предполагают, что домен не фильтруется , но отображаться в журнале фильтрации все же будет.
