### ISSUE TITLE
[BUG] HTTPS filtering notice cannot be dismissed on Android TV 

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#3508]
AFAIK HTTPS filtering for Android TV OS cannot be enabled (I'm running Oreo on Mibox3). 

The orange notice bar for "HTTPS filtering is off" cannot be dismissed on Android TV running AdGuard v3.4 and it causes navigation problems using DPAD and and visualization problems.

**Comment by oroboros** [comment]
Bumping this.

**Comment by Chinaski1** [comment]
@oroboros 

Hello there!
It seems that the implementation of user certificates is not supported by this firmware.
Unfortunately, there is nothing we can do on the application side.

**Comment by oroboros** [comment]
I realize that, but there could be a way to dismiss this perhaps in the UI, or only show it on the main screen?

It causes navigation problems using DPAD and visualization problems (it effectively hides what it covers, especially in some of the menus).

**Comment by Chinaski1** [comment]
Have you tried to flick this notice?

**Comment by oroboros** [comment]
> Have you tried to flick this notice?

Like I say, it cannot be dismissed on Android TV.
(You just can't reach it via DPAD control.)
