### ISSUE TITLE
Android adguard Query on why the local subnets are excluded by deault

### ISSUE THREAD

**Issue by talkwithsrinivas** [AdguardTeam/AdguardForAndroid#3509]
I would like to understand why the local lan subnets are excluded by default by adguard. I am using the vpn mode.
Is it because of any android bug?

**Comment by TheHasagi** [comment]
@talkwithsrinivas 

It is not necessary. They are excluded to avoid any problem with corporate intranets, home network, and others.

**Comment by talkwithsrinivas** [comment]
@TheHasagi 
Thanks. Just curios why the local routes need to be treated separately than the other networks?  Is it because they have incoming connections?
