### ISSUE TITLE
Android notification recommends to uninstall Adguard 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#351]
> Notification from Android OS, along the lines of.. Adguard is causing this device to run slowly please disable autostart for this app. Ps I have already disabled autostart in the app settings. Samsung S5 Neo 5.1.1

![image](https://cloud.githubusercontent.com/assets/15856304/13649622/35092f78-e647-11e5-94b2-0376291b77df.png)

XAW-692-86707

**Comment by ameshkov** [comment]
Is there any way to find out which errors this notification is talking about?

**Comment by evgeniy-ADG** [comment]
idk, there're a lot of complaint [on the internet ](http://stackoverflow.com/questions/34124016/how-to-get-rid-of-this-app-is-causing-your-device-to-run-slowly-notification)

**Comment by Bohdan-SUP** [comment]
Logs here - TZT-492-89487

**Comment by TPS** [comment]
Does #366 & associated KB link relate to what Android is complaining about?

**Comment by ameshkov** [comment]
@TPS no, I think it's something different.

**Comment by TPS** [comment]
Now that I'm on 7.1.1, I've _never_ had this message.  Is this the OS or manufacturer addition?

**Comment by ameshkov** [comment]
Yeah, seems to be Samsung addition. Although I've never heard of this issue besides this single complaint.
