### ISSUE TITLE
Adguard No Longer Blocking Ads in Latest Google Beta App Update

### ISSUE THREAD

**Issue by cnaples79** [AdguardTeam/AdguardForAndroid#3512]
### Issue Details

Adguard is no longer blocking Ads when web pages are viewed in the latest Google Beta App.

- **AdGuard version:**
  V.3.4
- **Filtering mode:**
  Local VPN 
- **Device:**
  Galaxy Note 10+
- **Operating system and version:**
 Android 10
- **Root access:**
 No

### Expected Behavior
Before the latest Google beta app update, all ads would be blocked on web sites viewed within the app.

### Actual Behavior
No ads are currently being blocked on sites within the app.

### Screenshots
![Screenshot_20200729-225952_Google](https://user-images.githubusercontent.com/28323262/88908169-8e3ad800-d227-11ea-8cbd-ae78084f7f8b.jpg)

### Additional Information
Latest Google Beta App is version 11.21.7.21

**Comment by Revertron** [comment]
Okay, the solution is this:
1. Enable HTTPS filtering for Google App
2. Add these rules to whitelist of HTTPS filtration in AdGuard: `lh*.googleusercontent.com$app=com.google.android.googlequicksearchbox` and `www.google.com$app=com.google.android.googlequicksearchbox`
3. Try to use Google App as before, it should work normally and ads will be blocked.
