### ISSUE TITLE
Fix the filters update on Android nougat

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#3514]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:*3.4(120)*
  - 
- **Filtering mode:*VPN*
  - 
- **Device:*p027*
  - 
- **Operating system and version:*android 7.0*
  - 
- **Root access:*no*
  - 

### Expected Behavior
Автообновление фильтров 

### Actual Behavior
Не происходит автообновление 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Писал в поддержку через приложение. Мне как обычно,насоветовали решение не имеющие ничего общего с решением проблемы ,поэтому я туда больше не пишу, они и не ответили даже ибо я им прямо и написал, что можете не присылать мне инструкции если не можете решить проблему  уже как полтора года! Я не знаю, что,нельзя воспроизвести условия при которых это происходит? Деньги гребёте не малые,а поддержки 0.

**Comment by artemiv4nov** [comment]
@Spok1 Добрый день! Пожалуйста, перепроверьте ещё раз на последней найтли версии.

**Comment by Spok1** [comment]
Это не даст результата! Вы каждый раз говорите чтобы установить бету,но в итоге в бете не исправляете ничего и это превращается в палку о двух концах. Разбирайтесь с текущим!

**Comment by Spok1** [comment]
@artemiv4nov , вышла версия 3.5, в ней исправлен этот баг?

**Comment by artemiv4nov** [comment]
@Spok1 Добрый день! Мы предлагаем пользователям перепроверять на последних версиях, потому что в них меняется список фильтров. Поэтому потенциально ваша проблема могла быть исправлена.
Вы проверили на релизе 3.5?

**Comment by Spok1** [comment]
@artemiv4nov , увы,но всё  по-прежнему.

**Comment by artemiv4nov** [comment]
Что ж такое-то :(
@Spok1 , а можете записать логов дебажных ещё раз, пожалуйста? Желательно на 4+ версии, чтобы по логам было быстрее соориентироваться?
Мы не можем повторить, поэтому бьемся в догадках, что же это может быть.

**Comment by Spok1** [comment]
@artemiv4nov, напомните как это сделать.

**Comment by Spok1** [comment]
Каким образом мне ловить эту проблему? Неделю с отделочными записями сидеть? Там столько информации накопился, что вы и подавно не найдете истоки...

**Comment by artemiv4nov** [comment]
У вас ведь это повторяется стабильно, если вы нажмете обновление фильтров.

1) Надо включить дебаг логгинг в настройках;
2) Повторить баг и запомнить время;
3) Отправить их на devteam@adguard.com и точным временем, когда это повторилось.

**Comment by Spok1** [comment]
То бишь просто нажать "проверить обновления" и отослать отладочный файл журнала? Если с этим понятно,то какой  тип записи выбрать журнала?

**Comment by artemiv4nov** [comment]
Стоп.
Вы утверждаете по условию этой задачи, что у вас не обновляются фильтры. Точнее, не происходит автообновление.
Значит, вы уже наблюдали ситуацию, когда фильтры не обновлялись.

Во-первых, надо конкретизировать проблему: фильтры не обновляются вообще; фильтры пытаются обновиться, но UI зависает при обновлении; фильтры не обновляются автоматически.
Во-вторых, надо сократить количество потенциальных источников для проблемы.

Поэтому сделайте следующее:
– Перейдите в "Настройки" — "Дополнительно" — "Уровень логирования" и выберите "Записывать всё".
– На главном экране нажмите кнопку обновить (справа сверху) и дождитесь окончания проверки обновлений. Рядом с фильтрами должно быть написано количество обновленных или что все фильтры обновлены. Если есть какие-то проблемы с обновлениями – это будет заметно в логах.
– После окончания проверки обновлений, перейдите в "Настройки" — "Дополнительно" — "Экспортировать логи", сохраненные логи пришлите на devteam@adguard.com.

В логах я также посмотрю установленные вами настройки. После анализа – дам вам ответ.

**Comment by Spok1** [comment]
> Вы утверждаете по условию этой задачи, что у вас не обновляются фильтры. Точнее, не происходит автообновление.
> Значит, вы уже наблюдали ситуацию, когда фильтры не обновлялись.

Именно. И обновляю я их вручную с интервалом  в 3-5 дней. Меня интересует следующий вопрос,каким образом вы сможете выявить ошибку,если ошибка-то и не проявляется ибо автообновление в заданный интервал(сутки) не происходит? Запись журнала покажет это?

**Comment by TheHasagi** [comment]
@Spok1 

К сожалению, так и не получили от вас логов. По инструкции выше попробуйте еще раз их прислать и укажите в теме письма номер данной задачи "issues/3514".

**Comment by Spok1** [comment]
@TheHasagi, отсылал на devteam@adguard.com

**Comment by TheHasagi** [comment]
@Spok1 

По инструкции выше с темой письма "issues"/3514" отправьте еще раз пожалуйста.

**Comment by Spok1** [comment]
Понял 🤠

**Comment by Spok1** [comment]
Отправил

**Comment by TheHasagi** [comment]
@Spok1 

До сих пор не получил, убедитесь, что ввели почтовый адрес верно - `devteam@adguard.com`.

**Comment by TheHasagi** [comment]
@Spok1 

Пришли, спасибо.

**Comment by TheHasagi** [comment]
@Spok1 

Приветствую! Спасибо за ожидание, в логах которые мы получили видно, что фильтры были автоматически обновлены. Видимо вы проверяли в момент, когда для них уже было доступно какое-то обновление в связи с этим они и обновлялись. Обратите внимание на то, что фильтры обновляются очень часто и если промежуток авто-обновления фильтров выставлен в 24 часа, то за данный период времени доступных обновлений может быть несколько. В будущих версиях мы подумаем над информированием пользователя при авто-обновлении фильтров.

**Comment by Spok1** [comment]
Нет, я знаю ,что они не автообновляются! Я проверял неоднократно, и знаю,что нет автообновления. Самый долгий промежутоа который я ждал- была неделя,после чего обновлял. Журнал выдает не точную информацию.

**Comment by Spok1** [comment]
@TheHasagi, нет, я знаю ,что они не автообновляются! Я проверял неоднократно, и знаю,что нет автообновления. Самый долгий промежутоа который я ждал- была неделя,после чего обновлял. Журнал выдает не точную информацию. Для наглядной демонстрсции прилагаю снимок по состоянию на 15.10.2020!
![Screenshot_20201015-190827](https://user-images.githubusercontent.com/34476664/96157031-774c7d80-0f1a-11eb-8ef8-ea12841ad7bf.jpg)
