### ISSUE TITLE
Telegram Beta can't download own update

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3517]
Well, We have a situation with Telegram when it can't download own update. We have to fix it ASAP before the 3.5 release of AdGuard.

**How to reproduce?**
- Download a pre-last beta version from https://t.me/betainfo
- Trigger an update
- The update won't be downloaded

**Comment by Revertron** [comment]
It seams that system Download Manager (that is used to download updates) can not download files if it is excluded from VPN. But we exclude it by default.
The user may remove `com.android.providers.downloads` and `com.android.providers.downloads.ui` from `pref.excluded.packages` low level setting to resolve this issue for now. But this is not a broad solution and may lead to other side effects, needs further investigation.
