### ISSUE TITLE
Unable to connect to upstream socks5 proxy

### ISSUE THREAD

**Issue by terrytw** [AdguardTeam/AdguardForAndroid#3519]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I use adguard together with shadowsocks-android. I use adguard in VPN mode, and shadowsocks in transparent proxy mode.
Adguard connects upstream socks5 proxy provided by shadowsocks, with UDP over socks5 enabled. I follow the instructions here: https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy#shadowsocks

It worked fine in earlier versions of shadowsocks. Recently their devs rolled out some changes to it, which lead to the following problem: 
In versons 5.1.0, 5.1.1, 5.1.2 of shadowsocks-android (you can find them here: https://github.com/shadowsocks/shadowsocks-android/releases), when "UDP fallback" is enabled, adguard gave an error saying that UDP over socks5 is not supported by the proxy, however same setup works just fine in 5.0.6 of shadowsocks-android. 

Since this problem comes with the change to their app, naturally I reported to their devs first: https://github.com/shadowsocks/shadowsocks-android/issues/2571
But they tested and insisted that their implementation worked as intended, and suggested that it was adguard's connectivity test that is broken. 
Could someone please look into it? Thank you!

A little context: shadowsocks-android uses plugins to obscure their traffic to bypass censorship, but it only works with TCP protocol, in order to support UDP traffic, they implemented a so-called "UDP fallback" mechanism, basically created a parallel socks5 proxy that dedicates for UDP traffic on the same port (1080). This worked fine with adguard in their earlier versions up until 5.0.6. 

In order to test this, you need to setup a shadowsocks server, which can be achieved by simply install the package "shadowsocks-libev" from Debian buster's backport repository or similarly from Ubuntu. Put `"mode":"tcp_and_udp"` in its config.json file will enable UDP relay function. Put `"plugin":"v2ray-plugin"`, `"plugin_opts":"server;host=cloudflare.com"` in the config to enable plugin. Then install shadowsocks app (you can find them here: https://github.com/shadowsocks/shadowsocks-android/releases), and v2ray-plugin from here: https://github.com/shadowsocks/v2ray-plugin-android/releases, and enable plugin from shadowsocks app and put the same plugin option in. You need to create a secondary profile without plugin enabled, and link it as UDP fallback in the first profile. 

- **AdGuard version:**
3.4
- **Filtering mode:**
VPN
- **Device:**
Oneplus 5T
- **Operating system and version:**
Andoird 10
- **Root access:**
Yes

**Comment by TheHasagi** [comment]
@terrytw 

Can you please check with the latest [Nightly](https://agrd.io/android_nightly) version?

**Comment by terrytw** [comment]
@TheHasagi 
It's the same with the latest nightly version.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #1346](https://github.com/AdguardTeam/CoreLibs/issues/1346) via [**ZenHub**](https://www.zenhub.com/)
