### ISSUE TITLE
Thai Ads Filters always enabled if the group is enabled

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3520]
Thai Ads Filters always enabled if the language filters group is enabled from the Filters section.

### Steps to reproduce:

1. Open AdGuard - Settings - Content Blocking - Filters
2. Enable Language-specific group

### Expected behaviour

Only preferred language filter should be enabled

### Actual behaviour

Thai Ads Filters is enabled alongside with the preferred language filter

**Comment by Rakleed** [comment]
@TheHasagi у меня при чистой установке версии 3.5.1 на OnePlus 3 автоматически был включён этот фильтр. Похоже, что проблема всё ещё актуальна.
