### ISSUE TITLE
Adguard cannot setup VPN connection after last Samsung S10 update 08/2020

### ISSUE THREAD

**Issue by GomezNL** [AdguardTeam/AdguardForAndroid#3521]
After i updated my Galaxy S10 today to the last security updates by Samsung i cannot start the adguard local VPN. The message that comes up says that the firmware does not support VPN. But in the VPN settings there is a setting for Adguard. Tried rebooting the phone, changing settings, reinstalling Adguard latest version but nothing helps.

**Comment by TheHasagi** [comment]
@GomezNL 

Hello, please, update to the latest [nightly version](https://agrd.io/android_nightly) and check again.

**Comment by GomezNL** [comment]
Problem still exists with the latest nightly :(

**Comment by TheHasagi** [comment]
@GomezNL 

Can you try these steps:

1. Go to Settings - Advanced - Dual Messenger
2. Uncheck all apps 
3. Turn off the screen for about 5-10 minutes
4. Launch adguard again and try to start the protection

**Comment by GomezNL** [comment]
Also tried the steps you mentioned, still gives the message that the firmware does not support VPN. Samsung says nothing is wrong with the firmware.

**Comment by TheHasagi** [comment]
@GomezNL 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by TheHasagi** [comment]
Closed due to no response. Will be reopened if needed.

**Comment by GomezNL** [comment]
Why closed? I have send a response to devteam@adguard.com??

Op do 6 aug. 2020 13:20 schreef Alexander <notifications@github.com>:

**Comment by TheHasagi** [comment]
@GomezNL 

Did not receive an e-mail, can you try again?

**Comment by GomezNL** [comment]
Have just send the email again, hope you recieved it this time :-)

**Comment by zzebrum** [comment]
@GomezNL do you use Dual app? 
it seems that something was broken in the latest Samsung patch :( 
temporary solution for this problem is described here: https://kb.adguard.com/en/android/solving-problems/restricted-profile#samsung

**Comment by ameshkov** [comment]
This is 100% caused by Dual messenger settings.

The easy solution: disabling dual messenger, rebooting device, usually works.
But if it's not, there's always a hard way -- using adb and granting necessary privileges to AdGuard.

**Comment by GomezNL** [comment]
So what if you depend on dual messenger? Then no Adguard anymore?

Kind regards,

Mark.

Op ma 10 aug. 2020 19:46 schreef Andrey Meshkov <notifications@github.com>:

**Comment by ameshkov** [comment]
> So what if you depend on dual messenger? Then no Adguard anymore?

In this case you need to use `adb` and grant AdGuard the necessary permissions.

Check the instruction here: https://kb.adguard.com/en/android/solving-problems/restricted-profile

**Comment by GomezNL** [comment]
Tried that but also does not work? Do I need Root permissions to do this?
Hope not, because I don't want to root my phone.
Also the VPN profile is created so no problem there, the problem is tat it
cannot start the VPN.
It says that the firmware does not allow it, was fine before the last
update by Samsung.
Also contacted Samsung and they say there is nothing wrong with te firmware.
Also had a problem with the android Bitdefender virus scanner but they
where able to fix this issue.

Op ma 10 aug. 2020 om 20:00 schreef Andrey Meshkov <notifications@github.com

**Comment by ameshkov** [comment]
> Tried that but also does not work? Do I need Root permissions to do this?

Nope, root permissions are not needed.

The most problematic part of the instruction is how to connect your device to your laptop/PC properly.

First of all, you need to enable "Developer mode" on your device.

1. Go to **Settings > About Phone**, find **Build Number**
2. Tap 7 times on Build Number, once you do this, developer mode will be unlocked.
3. Go to **Settings > System > Advanced > Developer Options**, find and enable **USB debugging**

There's a more [detailed instruction](https://developer.android.com/studio/debug/dev-options) on Android developer website just in case.

Only when it's done, connect your device via USB to your laptop/PC and run `adb devices` to check if it's connected properly. When you run this command, you'll see a dialog on your device asking whether you trust this computer, tap Yes.

Now you're ready to run the command that grants necessary permissions.

> It says that the firmware does not allow it, was fine before the last update by Samsung.

They did add a "restricted" account in the latest firmware update, this is a cause for all the troubles.

**Comment by GomezNL** [comment]
[image: afbeelding.png]

I get the following error, what am i doing wrong?
Phone is connected trough adb.

Thank you :-)


Op di 11 aug. 2020 om 09:47 schreef Andrey Meshkov <notifications@github.com

**Comment by ameshkov** [comment]
You need to attach the image right here on Github, I don't see the attachment

**Comment by GomezNL** [comment]
![afbeelding](https://user-images.githubusercontent.com/69202997/89872680-985ebe00-dbb9-11ea-8aab-43c7abca1d32.png)

**Comment by ameshkov** [comment]
Oh, my bad.

You need to install the nightly version of AdGuard, the current release version is not compatible with this permission.

You can either download it here:
https://agrd.io/android_nightly

Or you can change the update channel to "Nightly" in AdGuard settings.

**Comment by GomezNL** [comment]
That worked, thanks allot for your time!
