### ISSUE TITLE
Проблема исключений! Дубль 2

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3522]
Снова здравствуйте!
Речь в этой issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/3506  шла не о журнале фильтрации, а о исключении домена из передачи через прокси!!!

Поясняю я имел ввиду то, что при добавлении во все белые списки я продолжаю передавать домен через прокси, хотя мне нужно отключить режим прокси **ТОЛЬКО** для конкретного домена!!!!!!!! А именно, я не могу зайти на сайт со своего айпи даже при всех включённых исключениях!!!!!!!!!!!!!!!!!!!!!!!!!!

Режим фильтрации;
Локальный ВПН
Прокси:
Включен (орбот)

### Проблема - невозможность исключить домен из передачи чере прокси!

**Comment by TheHasagi** [comment]
Журнал фильтрации выводит весь трафик который передается через AdGuard и соответственно через вышестоящую прокси, следовательно отвечаю на ваш вопрос - в настоящий момент такой функционал не реализован.
