### ISSUE TITLE
Add a domain exclusion to the Proxy mode

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3523]
Well, we have a feature request to exclude domains from the filtering under the Proxy mode.
Let's see how many stars it gets.

**From user:**
В этом issue https://github.com/AdguardTeam/AdguardForAndroid/issues/3522

Я имел ввиду не журнал. Журнал не имеет никакого отношения к этому запросу. А невозможность исключения домена из передачи через прокси. А именно невозможность внести домен в исключения при передаче через прокси!

**Comment by gctcgv** [comment]
Повторяю: проблема заключается в том, что даже при добавлении домена в исключения я не могу исключить его из режима прокси.

Я имею ввиду этот режим!
![Screenshot_20200805-162224](https://user-images.githubusercontent.com/69247523/89417854-f01fa400-d737-11ea-8626-3efdc3febac4.jpg)

**Comment by chromer030** [comment]
it's really useful for accessing router or local address.
Please add this feature.

**Comment by artemiv4nov** [comment]
Well, this functionality won't be implemented for a while.
