### ISSUE TITLE
Add an option to rename userscripts

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3526]
Requested by 2576359:

> Could you please add support for renaming userscript extensions? I want to install 2 that have the same name from URLs (so I can't just rename the file). Please unlink the userscript name from the file name.

**Comment by TPS** [comment]
@Eugene-Savenko If mark this issue with the label **Pinned** _(IRC)_, StaleBot will leave it alone.

**Comment by artemiv4nov** [comment]
Let's see how many people will upvote for this feature request.

**Comment by artemiv4nov** [comment]
As a solution, you can change a name for a userscript inside the script. I'll close the task.

**Comment by TPS** [comment]
> As a solution, you can change a name for a userscript inside the script. I'll close the task.

@artemiv4nov That doesn't make any sense.  If it was 1's _own_ userscript, of course 1'd do it that way.  But what about a 3rd-party subscription, as this issue is _obviously_ about?
