### ISSUE TITLE
Xbrowser error https

### ISSUE THREAD

**Issue by wiwin-github** [AdguardTeam/AdguardForAndroid#3528]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4 beta
- **Filtering mode:**
  -  local vpn
- **Device:**
  -  samsung tab a 2016 spen - p585y
- **Operating system and version:**
  -  8.1
- **Root access:**
  -  no

### Screenshots

 
![Screenshot_20200810-184228_XBrowser](https://user-images.githubusercontent.com/61280814/89779957-b20cf080-db3a-11ea-91f8-559035b0c902.jpg)
![Screenshot_20200810-184210_XBrowser](https://user-images.githubusercontent.com/61280814/89779987-bc2eef00-db3a-11ea-9505-c2977d829218.jpg)

<details><summary>Screenshot:</summary>

</details>

### Additional Information

 i already install certificate to device

**Comment by wiwin-github** [comment]
https://play.google.com/store/apps/details?id=com.xbrowser.play

**Comment by TheHasagi** [comment]
@wiwin-github 

This browser does not accept our certificate and HTTPS filtering is disabled by default for this app. There is nothing we can do with it, just disable HTTPS filtering in AdGuard - Apps management - XBrowser.
