### ISSUE TITLE
Android 10 = MIUI 11.x | Adguard DOES NOT work when mobile data is connected

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#3534]
### Issue Details

- **AdGuard version:**
Android 10
- **Filtering mode:**
Local VPN 
- **Device:**
Redmi Note 7
- **Operating system and version:**
Android 10 (MIUI Global 11.0.1 stable)
- **Root access:**
NO

### Expected Behavior

Adguard Test page failed test and leaking ads when MOBILE DATA are using to connect with Internet.

### Actual Behavior

Adguard should block ads in mobile and WIFI connections as well.

I thought thats was some messed up with system, settings, permissions, but NO. With Android 9.x this was not happen.
After upgrade to lastest MIUI 11.0.1 with new Android 10 this started.
Notice: 
Filtering DNS from Adguard app works well in both connections scenario. ONLY failed protection ads in mobile data connection. 
I tested stable release ADG too and lastest nightly - SAME happen. 

UPDATE

- filtering sometimes works only if DNS filtering is enabled too, IF I switch off this - ads leaks. 
@TheHasagi

**Comment by zzebrum** [comment]
@FadeMind is it AdGuard certificate on web pages?

**Comment by FadeMind** [comment]
I cleaned up setup, install NEW nightly, import settings aaand seems works (mobile vs WIFI switching is fine).
I will do more test for create scenario step by step for recreate this annoying. 

Edge report Adguard CA valid Here. Really weird behaviour.

**Comment by TheHasagi** [comment]
@FadeMind 

I'll close this issue for now if it is not relevant and cannot be reproduced anymore.
