### ISSUE TITLE
Add a separate filter update log

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3537]
### Problem Description

We've received a few requests from users who would like to manually check each and every filter update.

### Proposed Solution

Add a separate filter update log and UI indicator to let the user know that the filter was updated during the last update checkup.

### Alternatives Considered

User did not offer any alternatives.

### Additional Information

OP: 1454863

**Comment by artemiv4nov** [comment]
The task is not so popular, will close it.
