### ISSUE TITLE
HTTPS filtering option is available in Removed Apps

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/AdguardForAndroid#3539]
### Issue Details

- **AdGuard version:**
  - v3.5 beta 1 (48)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy S9
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Actual Behavior

HTTPS filtering option is available in Removed Apps within the Apps Management.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_AdGuard](https://user-images.githubusercontent.com/57285466/90332639-16ea9f80-dfae-11ea-83c1-bf249e240e57.jpg)

</details>

**Comment by artemiv4nov** [comment]
This behavior is by design. But we will improve the Apps management in the AdGuard v4 version.
