### ISSUE TITLE
Add Polish filters

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardForAndroid#354]
please add polish filters 

Adblock & uBlock polish filters 

https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

Adblock & uBlock polish cookies filters

https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

**Comment by ameshkov** [comment]
We'll add these, thank you!

**Comment by xxcriticxx** [comment]
thx

**Comment by ameshkov** [comment]
Done, will be available in the next beta version.
