### ISSUE TITLE
AdGuard obstructs internet connection

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3540]
### Issue Details

- **AdGuard version:**
  -  3.5.49
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Xiaomi POCO F1
- **Operating system and version:**
  -  10
- **Root access:**
  -  No

1. After a certain period of time AdGuard blocks the Internet connection
2. User need to reset protection to re-establish the connection
3. Changing the DNS server, its type, or disabling DNS filtering will not give a result.

### Additional Information
- HelpDesk ID: 2298828
- Time in logs: 11:13-11:14 / 16.08.2020
- Logs are added to NCloud

**Comment by Chinaski1** [comment]
One more user faced a similar issue: 2836144
- User ID: 2836144
- Time in Logs: 20.08.2020 | 6:12 - 6:27
- Logs are added to NCloud

**Comment by Eugene-Savenko** [comment]
1455951 (w/ system and AdGuard logs:

>VPN AdGuard периодически блокирует все соединения и телефон висит без связи, пока не отключишь VPN. Замена и выбор других DNS проблему не решает.

**Comment by nuc134r** [comment]
Happens to me as well on a Xiaomi phone. I suddenly cannot refresh or load anything from any app until I stop and start protection again. Very annoying

**Comment by artemiv4nov** [comment]
Well, I think the problem has gone in the 4.0 version.
