### ISSUE TITLE
AdGuard 3.5 beta 2 и Wi-Fi

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3544]
У меня телефон **HUAWEI Y6p** и на него установлен **AdGuard 3.5 beta 2**

Внимание!!! Данная тема полностью совместима с вот этой темой - https://github.com/AdguardTeam/AdguardForAndroid/issues/3467, просто в этой теме выявил у себя другую проблему и мне кажется, что та та проблема тоже из за этого.

Заметил вот, что. Дома **HUAWEI Y6p** подключен к **Wi-Fi** и происходит проблема описанная вот здесь - https://github.com/AdguardTeam/AdguardForAndroid/issues/3467. Решил при обновлении фильтров на **AdGuard 3.5 beta** отключить **Wi-Fi** и обновления производить при помощи мобильного интернета, на данный момент проблема описанная вот здесь https://github.com/AdguardTeam/AdguardForAndroid/issues/3467 больше не повторяется.

Получается, что на **HUAWEI Y6p**  **AdGuard 3.5** имеет проблемы с обновлениями по **Wi-Fi**, так как через мобильный интернет данная проблема отсутствует. Где то в течении недели обновляю без проблем.

**Comment by artemiv4nov** [comment]
Duplicated to #3467
