### ISSUE TITLE
Fix a bug related with strange and small "m^" rules

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdguardForAndroid#3548]
We have to fix a bug in the code, which leads to the creation of small rules, under which a large number of sites fall, due to which the Internet does not work.
For example, a user can see a rule "m^" in the Filtering log.

**Comment by TPS** [comment]
Resolves https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/431.  Thanks! 🙇🏾‍♂️
