### ISSUE TITLE
AdGuard fails to start protection immediately after turning on 4G/LTE

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3551]
### Issue Details

- **AdGuard version:**
  - 3.4 Release, 3.5 nightly 11
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus HD1911
- **Operating system and version:**
  - Android 10, Jul 2020 security patch
- **Root access:**
  - Yes

### Actual Behavior & repro

1. Switch AdGuard to **Local VPN** filtering mode
2. Turn on mobile data
3. Try to enable protection
4. AdGuard will soft hang and display the "Preparing to enable protection..." screen infinitely

This doesn't reproduce in Local HTTP Proxy, auto mode.

### Additional information

User suspects the issue might be related to root.set.oom_adj. To validate this theory, we've asked them to send us two batches of logs - one with problematic behavior, one without.

Logs & screen recording available under helpdesk ID 1556449.

**Comment by akmLaVx** [comment]
Pinging devs @artemiv4nov

**Comment by techIndia-hacker** [comment]
I am still having this issue in 3.5 release

**Comment by ameshkov** [comment]
Am I understanding it right - there's no issue when `root.set.oom_adj` is disabled?

**Comment by techIndia-hacker** [comment]
Yes

**Comment by ameshkov** [comment]
The log is missing the part that's recorded on the video.

You're clearing the app data on the video and it removes all the log that was recorded previously.

**Comment by techIndia-hacker** [comment]
🤨😅

**Comment by techIndia-hacker** [comment]
Sent

**Comment by ameshkov** [comment]
Could you please send the file, not a link to GDrive? We don't have access to the file by that link.

**Comment by techIndia-hacker** [comment]
Sent again

**Comment by ameshkov** [comment]
Tbh I see nothing problematic in the log.

It seems to be started successfully.
`19:06:12.014 [protection-pool-9-thread-1] INFO  com.adguard.android.service.a.a - Protection has been successfully started`

Apparently, for some reason it fails to notify the UI about that. Maybe tweaking process OOM score is not really safe.

**Comment by techIndia-hacker** [comment]
I don't know why the UI hangs in my devices when trying to start the vpn first time. But I am sure it's related to accessing root privileges .

What u see in the previously sent video is just that the ui thread hangs infinitely. As u may have observed that the system back button does not work when hit by this bug.

I am attaching another video which I think is the source of the bug.

**Comment by Ruslanrem** [comment]
@techIndia-hacker hi, does the problem still actual?

**Comment by techIndia-hacker** [comment]
No I found a workaround. I found that disabling battery optimisation for
magisk solved the problem for adguard. Though other applications didn't
have a problem with magisk even with battery optimistic turned on. It's for
sure a adguard bug.

@techIndia-hacker <https://github.com/techIndia-hacker> hi, does the

**Comment by Ruslanrem** [comment]
@techIndia-hacker  
According to the logs, all clear, but something in your phone jams adguards process.

**Comment by ameshkov** [comment]
> It's for sure a adguard bug.

Well, not at all. AdGuard just tries to run a command with root access, right after that it's Magisk who's controlling this command lifetime.

Anyway, thanks for the tip about Battery optimization for Magisk. I think that maybe with battery optimization the phone kills Magisk when you change networks, and that's why the command that we're trying to execute ends up being stalled.

**Comment by techIndia-hacker** [comment]
Yeah execution of the root command gets a little delayed due to battery
optimisation for magisk. But the delay is for 600ms at max. For this
adguard ui should not hang forever. Also there are other apps which
requests SU privileges but are better programmed to wait for the time
required for granting the privilege
