### ISSUE TITLE
AdGuard blocking Internet connection of some apps

### ISSUE THREAD

**Issue by Theitfixer85** [AdguardTeam/AdguardForAndroid#3552]
AdGuard version Version 4.0 nightly 1
Nvidia shield pro 2019
Local vpn
With AdGuard enabled (settings enabled irrelevant) 

AdGuard is blocking access to the Internet for some apps
It doesn't matter what settings are enabled eg filters dns etc as I've turned all these off to test and it's still blocking access to the Internet for some apps

The only way these apps will have access to Internet is if either AdGuard is disabled entirely or you tell AdGuard not to route the app through AdGuard 

There is nothing in the filtering log to suggest anything is being blocked

Example of apps that are effected
FileLinked - start the app and it sits on the start screen loading until an error no Internet connection displays

CinemaHD - can't get a connection to load any of the home page or sub lists with either a spinning circle or a server error. Can't load any thumbnails etc 

Both these apps used to function perfectly well with the issue happening some time around AdGuard version 3.5 nightly 11

It also effects other devices and I've even tried the stable version and it still does it which is odd as it's only started to happen in the last few weeks across all devices 

Edit - now also Smart YouTube TV is no longer getting an Internet connection when AdGuard is enabled. Just the loading screen. Disable AdGuard and it instantly loads up

Edit 2 - It is also blocking any PlutoTV channels from loading as well. Again soon as I disable AdGuard or tell AdGuard not to route app through AdGuard everything works

**Comment by Theitfixer85** [comment]
This is becoming a serious issue - more and more apps are being denied access to the Internet while AdGuard is enabled even with no filters dns filters or anything else enabled other than AdGuard itself

**Comment by Theitfixer85** [comment]
I have taken logs - if you want them please let me know what email to send them to for privacy reasons

**Comment by artemiv4nov** [comment]
@Theitfixer85 Hello@ Send the debug logs to devteam@adguard.com, please

**Comment by Theitfixer85** [comment]
> @Theitfixer85 Hello@ Send the debug logs to [devteam@adguard.com](mailto:devteam@adguard.com), please

Logs sent

Forgot to mention the logs were recorded when I opened up the cinemaHD app with the app not getting an Internet connection and me trying to open different emails tabs within the app with same effect

**Comment by akmLaVx** [comment]
We've received logs from 3552

**Comment by infinitewaveparticle** [comment]
As I've stated before, and it seems impossible to fix, on Android 7 & 8, AdGuard blocks ESET Mobile Security from connecting to the internet. I wonder if there's something about certain apps and firewalls on certain versions of Android.

@Theitfixer85 what version(s) of Android are you seeing this on?
