### ISSUE TITLE
AdGuard SSL cert rejected by several apps on Note20 Ultra

### ISSUE THREAD

**Issue by ianmacd** [AdguardTeam/AdguardForAndroid#3553]
The AdGuard cert is rejected by many apps on the Note20 UItra and probably on other Samsung devices launched in 2020 on Android 10. My Samsung Android 10 devices that launched in 2019 on Android 9 and have only since been upgraded to Android 10 are not affected.

It doesn't matter whether the cert is actually moved to the system store or virtually placed there by Magisk's Move Certificates module. Either way, the same apps reject the certificate.

![Screenshot_20200825-195846_Nova Launcher](https://user-images.githubusercontent.com/749942/91408772-b2003680-e844-11ea-8b4f-1253adb6caee.jpg)

**Comment by ianmacd** [comment]
I guess this is due to the apps in question using SSL pinning and that there's no fix for the issue, short of modifying the APKs of the packages themselves. In that case, I guess they should be added to the HTTPS filtering exemption list.

**Comment by TheHasagi** [comment]
@ianmacd 

Some apps are rejecting the cert and cannot be filtered properly. In that case, you should go to AdGuard - Settings - Advanced settings - Low-level settings and enable pref.https.opportunistic and disable pref.notify.on.unknown.ca
