### ISSUE TITLE
No filtering on Pikabu on Opera

### ISSUE THREAD

**Issue by Vasya317** [AdguardTeam/AdguardForAndroid#3555]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

AdGuard stopped filtering sponsored posts on Pikabu.ru on Opera. Please see details below (screenshots and links).

- **AdGuard version:**
v3.4 (120)
- **Filtering mode:**
Local VPN / HTTP Proxy (Auto)
- **Device:**
OnePlus 7 Pro
- **Operating system and version:**
 Android 10
- **Root access:**
 No

### Expected Behavior

Sponsored posts should have been filtered.

### Actual Behavior

Sponsored posts appear as they have not been filtered.

### Screenshots

![Screenshot_20200827-211423](https://user-images.githubusercontent.com/37618262/91479617-63858300-e8aa-11ea-8ca2-f809281eaff0.jpg)

![Screenshot_20200829-190536](https://user-images.githubusercontent.com/37618262/91641078-c56cf680-ea2a-11ea-9752-147beb04ab88.jpg)

![Screenshot_20200829-191114](https://user-images.githubusercontent.com/37618262/91641205-7f646280-ea2b-11ea-9add-56430bb1320f.jpg)

### Additional Information

https://pikabu.ru/story/azovmee_imyahchmu_seyla_jzfa_dhka_espreazolena_dkloo_pchaseyla_jzfa_dotopos_7677669

https://pikabu.ru/story/la_udeksohchku_mu_seyla_jzfkayotoudeel__esa_d_me_torevhchseyla_jzfkaythcnya_7646477

https://pikabu.ru/story/seka_med_ikh_ukchaseyla_jzfkay_occhi_chla_udeksohchku_mu_seyla_jzfkayotoris_7643759

**Comment by TheHasagi** [comment]
@Vasya317 

Эта реклама нативная (встроенная), уточните на какой версии она у вас блокировалась?

**Comment by Vasya317** [comment]
Да, это встроенная реклама. Всегда она раньше блокировалась. Это они видимо сделали какое-то нововведение, которое стало подходить через фильтры. Вся эта реклама идёт от так называемого пользователя "specials", которого нельзя заблокировать как пользователя (отписаться от постов) средствами сайта.

**Comment by TheHasagi** [comment]
@Vasya317 

Я боюсь в этом случае мы ничего не сможем сделать. @Alex-302 Есть ли какие нибудь варианты?

**Comment by Vasya317** [comment]
Надеюсь, что всё-таки какие-то варианты есть, потому что ранее на данном сайте появлялись проблемы, но их так или иначе удавалось разрешить.

**Comment by Alex-302** [comment]
@Vasya317 Лучше отправьте отчет из меню Адгарда. Там вся нужная нам информация добавится автоматически. Иначе не понятно, сайт это или приложение.

**Comment by Vasya317** [comment]
Напомните, как это сделать. В интерфейсе я не вижу простого способа сформировать данный отчёт. Спасибо

**Comment by Alex-302** [comment]
Меню -> Поддержка -> Отзыв

**Comment by Vasya317** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/62962

![Screenshot_20200903-001419](https://user-images.githubusercontent.com/37618262/92037457-756b9800-ed7a-11ea-888a-d02ad584c19d.jpg)

**Comment by TheHasagi** [comment]
Closed.

**Comment by Vasya317** [comment]
![Screenshot_20200904-120331](https://user-images.githubusercontent.com/37618262/92221819-b95bbb80-eea6-11ea-9130-0d39180cad83.jpg)

**Comment by Vasya317** [comment]
https://pikabu.ru/story/o_rota_neryi_by_noekdogopono_r_aystae_colkidns_t_nel_totaekdogopono_ryat_al_7691926
