### ISSUE TITLE
Many log elements seem to be jumbled around

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#3557]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.5 RC 1 (61)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Motorola One Zoom
- **Operating system and version:**
  - Android 9.0 (PPHS29.59-51-13)
- **Root access:**
  - No

### Expected Behavior

The log correctly shows entries in descending chronologic order, like in AdGuard Home.

### Actual Behavior

Currently, my impression is that 20~25% of the log entries are not at their correct timestamp locations, as can be seen in the screenshot below. I can't seem to work out the exact cause for it, nor can I find any log sorting settings that are about sorting by timestamps.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/91643365-f9e4b080-ea32-11ea-962e-6f8a80699ee1.png)

</details>

### Additional Information

The problem seems to me personally to be more noticeable (but not at all exclusive to) when regular filtering and DNS filtering has been turned on at the same time.

I also suppose it deserves mention that I have a clock seconds-counter turned on in Nova Launcher, if that'd have any effect on anything whatsoever with this.

**Comment by DandelionSprout** [comment]
Still seems pretty jumbled to me.
![image](https://user-images.githubusercontent.com/22780683/97791995-d7a91380-1bd8-11eb-9e6e-2f30e943c5fd.png)

**Comment by Ruslanrem** [comment]
@DandelionSprout, requests in the filtering log are shown by elapsed time finish. The timestamp is just requests start time. It can not match with the order in filtering log, because of different elapsed time. (You can see that in Log Details)

**Comment by DandelionSprout** [comment]
Ah. That explains quite a bit.
