### ISSUE TITLE
In which way (and when) are Crowdin translations added to AdGuard for Android?

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#3558]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v3.5 RC 1 (61))
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I've done considerable work on *AdGuard for Android*'s Norwegian translation in the past month, getting it from ~40% to 80% in Crowdin's official statistics (Around 93% if we count strings instead of source-words), incl. the entire main-menu system. However, the new translations don't seem to have been implemented as of v3.5 RC 1 (61), as can hopefully be seen in the screenshot below. And since that was a release candidate build, I just wanted to ask about and feel sure that they'll be implemented in time for V3.5 stable?

![image](https://user-images.githubusercontent.com/22780683/91643693-d111ea80-ea35-11ea-863f-6790ecfb7194.png)

### Proposed Solution

Implement the newest Crowdin translations for and in AdGuard for Android, and possibly also consider implementing/syncing them for each beta build and not just for stable builds.

### Alternatives Considered

None.

### Additional Information

None that I feel would be relevant at the moment.

**Comment by TheHasagi** [comment]
@DandelionSprout 

We will try to keep up with the translations and implement already translated strings in the nearest update, but as usual, they are not always ready by the time the version is ready to be released.

**Comment by el-termikael** [comment]
@DandelionSprout 

Hello!

The problem was that you *did* translate plenty of strings, but they were not approved (we missed them somehow) and, consequently, were not added to the latest version :(

I'd like to offer you to be a Norwegian proofreader. What do you say? If you agree, I’ll update your status to Proofreader and you’ll be able to approve/disapprove the Norwegian translations (thus ensuring that all the strings will appear in the new version).

**Comment by DandelionSprout** [comment]
I accept the offer to become a proofreader.

**Comment by el-termikael** [comment]
@DandelionSprout 

Ready!

Now you can approve your own strings and the ones of other Norwegian translators. If you have some spare time, could you approve your recent translations for [AdGuard for Android](https://crowdin.com/translate/adguard-applications/17634/en-no?filter=basic&value=5)?

**Comment by DandelionSprout** [comment]
Sure thing. I'll get it done today.
