### ISSUE TITLE
AdGuard truncates DNS user filters

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3559]
Issue Details

- **AdGuard version:**
  -  4.0 Nightly 1 **
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Kindle Fire HD 10 7th Edition*
- **Operating system and version:**
  -  Android 5.1.1 *
- **Root access:**
  -  No

*Note: I've also noticed this happening on Samsung phones and my NVIDIA Shield also (all running Android 7, 8, and Android TV)
**Note: This bug has been happening for a long time, but it only started with the 3.5 implementations.

### Expected Behavior

AdGuard should implement DNS user filters as written at all times.

### Actual Behavior

After making any edit/addition/deletion to any setting that causes AdGuard to restart in order to implement the change(s), sometimes DNS user filters are shortened which ends up blocking some servers that should be allowed while also allowing some servers that should be blocked.

### Screenshots

<details><summary>Screenshot:</summary>

![dotcom_DNSuserfilterbug](https://user-images.githubusercontent.com/29090831/91649524-47691980-ea43-11ea-8496-ca7582361e2a.jpg)

![a org](https://user-images.githubusercontent.com/29090831/91649529-5a7be980-ea43-11ea-8f90-93c14c0382c8.jpg)

![portal firefox com](https://user-images.githubusercontent.com/29090831/91649537-636cbb00-ea43-11ea-921a-bed291909696.jpg)

![azon com](https://user-images.githubusercontent.com/29090831/91649551-69629c00-ea43-11ea-9c81-d6c202808d0a.jpg)

![4287340888846339350](https://user-images.githubusercontent.com/29090831/91649580-8ac38800-ea43-11ea-821a-2509362c2b48.jpg)

</details>

### Additional Information

I have logs saved for several instances of this happening. Just let me know where to send them. Also, for some reason, in Github Issues there is no reply option for me... so this may be the only post I can make on this thread. Hopefully that isn't the case.

**Comment by admitrevskiy** [comment]
@infinitewaveparticle Hi!
Please try [this build](https://yadi.sk/d/4WOYfa2Z6Ny0PA). If the problem still persists, please collect debug logs and send them to `devteam@adguard.com`

**Comment by infinitewaveparticle** [comment]
Hello,

I am unsure which of my bug reports this was a response to, but after installing this version I can say without a doubt that all the bugs are still happening - especially the tracking parameters one and the tcp/https one (which I noticed recently is from the browsers only accepting the certificate part of the time - it seems to be accepted by the browsers and it works... but simultaneously also does not work, as I receive notifications saying it's not accepted for every website even tho it's also being accepted - I noticed this while using fennec_fdroid browser). The only one that is happening far less is the user filter bug (the one where user filters are truncated after making edits to the settings that cause the connection to be restarted), but it too still happens rarely.

Sorry for not responding sooner, but I get burnt out quite easily with submitting bug reports. I wish I was a more active Github user, but I simply don't have the time. I do, however, use AdGuard A LOT so I do recognize bugs that no one else seems to.

Thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
Hello again,

I am currently using 4.0 Nightly 15. This issue still happens, but it has been greatly reduced. When I created this report it happened constantly. Now it only happens every once in a while. Furthermore it used to require force closing and restarting AdGuard to fix it. Now it automatically fixes it after a very small amount of time... For most users that makes this issue solved, but for me and the sake of completely solving every issue more work remains to be done. I will try to snag logs of it happening again and send them to ***@***.*** Thanks for all your work and for the great customer service!

iwp

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
Hello,

As promised I collected logs and screenshots of this issue still happening. I am attaching them to this email and Cc-ing devteam & support because I doubt they'll post here on Github via email. I will try to post them here if you need me to (let me know). The timestamps shown in the filtering log in the screenshots show when the issue occurs and also when it fixes itself. I hope you are able to diagnose why this is still happening and propose a viable solution for the next release.

Device: Samsung Galaxy S7 Edge
OS: stock Android 8
AdGuard version: 4.0 Nightly 16

Steps to reproduce:

1. Turn on Airplane Mode.
2. Make a few changes to the settings to cause AdGuard to disconnect and restart its connection to apply the new settings.
3. Observe the bug occur and then correct itself in the filtering log.
4. Turn Airplane Mode off.

I have no idea if this happens if Airplane Mode isn't activated, but I suspect it would.

Note: The DNS user filter rules I always observe this happening on are:

||mozilla.org (there are several instances of AdGuard not blocking this when it should - not sure why)
&
||detectportal.firefox.com$important (this somehow becomes simply "om$important" which can block anything ending in .com)

In case you're wondering why I block these it's because Firefox Focus tries to call home with them when it has internet connectivity problems (such as being in Airplane Mode). I find this annoying so I block them via DNS.

Please let me know if you need further explanation or information about this issue.

Thank you!
iwp

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment]
Hello @infinitewaveparticle !

Thank you for continuing to monitor the situation and sending reports.
I hope they will help us to understand what is causing the issue.

**Comment by artemiv4nov** [comment]
@infinitewaveparticle Hi!
The new nightly version with newly updated DnsLibs is available. Could you please check on it?

**Comment by infinitewaveparticle** [comment]
@artemiv4nov While I have only tried Nightly 20 for about an hour I can say two things so far:

1. I haven't noticed any truncated rules...yet.
2. I HAVE, however, noticed rules that should be blocked by DNS user filter rules go unblocked, albeit temporarily.

Knowing this I'd say it's not fully fixed...?

**Comment by infinitewaveparticle** [comment]
I have submitted the logs and screenshots (via email) for this issue still happening in 4.0 Nightly 20 (including the truncating - this time a user filter rule "m" is created). One thing I've noticed is that it only happens when two or more edits/changes to settings are made in rapid succession (for example unchecking 2-3 user filters and checking another fairly quickly). Not sure if that's significant or not. Thanks for working on this. It's this issue and the Stealth Mode not stripping tracking parameters issue (3561, 3584, & 3647) that seem to persist for me no matter what is done to fix them.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by artemiv4nov** [comment]
Okay, thanks! We will investigate your files later.

**Comment by infinitewaveparticle** [comment]
btw, I have now begun seeing this happen almost every time I make any settings change. it also happens when I don't turn on airplane mode, and in those instances connections are successfully made that should be blocked. I have one rule truncated to simply "4" and one to simply "t" so in addition to blocked connections going unblocked there are also unblocked connections that get blocked. the only good thing is that it corrects itself... could it be happening to me because I have over 2000 dns user filters + 10 custom dns filters? not saying that I should trim my lists, but maybe to reproduce it you need to really pile on the dns filters.

**Comment by Eugene-Savenko** [comment]
Logs in Zendesk: 527152

**Comment by artemiv4nov** [comment]
The DNS filtering has totally been re-implemented in the 4.0 version. Please follow the updates.
