### ISSUE TITLE
Tracking parameters are no longer stripped by Stealth Mode

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3561]
Issue Details

- **AdGuard version:**
  -  4.0 Nightly 1 **
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Kindle Fire HD 10 7th Edition*
- **Operating system and version:**
  -  Android 5.1.1 *
- **Root access:**
  -  No

*Note: I've also noticed this happening on Samsung Galaxy phones too (running Android 7 & 8)
**Note: This bug has been happening since at least 3.5 Beta 1, 3.5 Nightly 11, & 3.5 RC 1. In 3.5n7 it also started saying "Tracking parameters stripped" for all Stealth Mode modified connections - even ones with no tracking parameters (that part has been fixed).

### Expected Behavior

AdGuard should strip tracking parameters whenever they should be.

### Actual Behavior

Opening URLs (in browsers that can be filtered) that have parameters listed in "Tracking parameters" in Stealth Mode (with the option turned on) results in the parameters being included in the opened links. No redirect occurs.

### Screenshots

<details><summary>Screenshot:</summary>

![trackingParametersBug1](https://user-images.githubusercontent.com/29090831/91650532-d7f92700-ea4e-11ea-86d3-d9e745e380f9.jpg)

![trackingParametersBug1a](https://user-images.githubusercontent.com/29090831/91650534-e0516200-ea4e-11ea-80c1-74cafacee487.jpg)

![trackingParametersBug1c](https://user-images.githubusercontent.com/29090831/91650538-e8110680-ea4e-11ea-8e21-f8000980b331.jpg)

![trackingParametersBug2](https://user-images.githubusercontent.com/29090831/91650541-f0694180-ea4e-11ea-83a8-88a07a1c7ace.jpg)

![trackingParametersBug2a](https://user-images.githubusercontent.com/29090831/91650544-f6f7b900-ea4e-11ea-9cc4-4d062929deab.jpg)

</details>

### Additional Information

I have logs saved of this happening. I am sending to devteam@adguard.com. Also, for some reason, in Github Issues there is no reply option for me... so this may be the only post I can make on this thread. Hopefully switching to a different browser will fix this.

**Comment by Chinaski1** [comment]
Hello there!

The issue seems to be related to the point that the tracking parameters are listed in one line and not through line breaks.
But in any case, it is a bug. We will fix this situation in the next updates.
Thank you for the feedback.

**Comment by Chinaski1** [comment]
You can track solution progress here: #3584
