### ISSUE TITLE
Proxy IP no longer listed as "Remote address"

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3562]
Issue Details

- **AdGuard version:**
  -  4.0 Nightly 1 **
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Kindle Fire HD 10 7th Edition*
- **Operating system and version:**
  -  Android 5.1.1 *
- **Root access:**
  -  No

*Note: I've also noticed this happening on Samsung Galaxy phones too (running Android 7 & 8)
**Note: This bug has been happening since 3.5 RC 1.

### Expected Behavior

AdGuard should list the proxy's IP and port as the remote address. It should also be sure to route traffic thru the proxy server.

### Actual Behavior

Although checking my IP address still shows the proxy to be functioning properly, the "Remote address" portion of the filtering log now acts as if no proxy is enabled even though mine is enabled and apparently working. It instead lists the IP address of the server it's connecting to, as well as its port (usually 443 or 80). In versions prior to RC 1 my proxy server was always listed as the Remote address. Also, the occasional tcp tunnel that usually showed as connected to my proxy server now shows it connecting to the IP address of the website/server. See screenshots.

### Screenshots

<details><summary>Screenshot:</summary>

![proxyNotRemoteAddressBug](https://user-images.githubusercontent.com/29090831/91650765-7edec280-ea51-11ea-8120-89389679ad99.jpg)

![proxyNotRemote_and_tcpBug](https://user-images.githubusercontent.com/29090831/91650770-8a31ee00-ea51-11ea-8668-9d639c17d35c.jpg)

</details>

### Additional Information

I have logs saved of this happening. I am sending to devteam@adguard.com. Also, for some reason, in Github Issues there is no reply option for me... so this may be the only post I can make on this thread. Hopefully switching to a different browser will fix this.

**Comment by zzebrum** [comment]
@infinitewaveparticle is the problem still reproducing?

**Comment by sfionov** [comment]
This is expected behavior, displaying outbound proxy IP:port in destination address was a bug. 
However, I've created feature request in CoreLibs: https://github.com/AdguardTeam/CoreLibs/issues/1385

**Comment by infinitewaveparticle** [comment]
Yes, it is still reproducing.... It's not really a big deal, though, because the proxy is still connected just fine. It's actually helpful sometimes to see the IP of the end server instead if the IP of the proxy server. Perhaps adding a new category when proxies are connected would help because it's nice to see the IP of the proxy too - "Remote address (proxy)".

Sent from ProtonMail mobile

-------- Original Message --------
