### ISSUE TITLE
Some Adguard traffic is handled as if ad blocking or https filtering is disabled

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3563]
Issue Details

- **AdGuard version:**
  -  3.5 Nightly 7 thru 4.0 Nightly 1 **
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Kindle Fire HD 10 7th Edition*
- **Operating system and version:**
  -  Android 5.1.1 *
- **Root access:**
  -  No

*Note: I've also noticed this happening on Samsung Galaxy phones (running Android 7 & 8) and my NVIDIA Shield running Android TV

### Expected Behavior

AdGuard should connect to and properly filter servers resolved by DNS, not tcp connections to their IPs or unfiltered https connections.

### Actual Behavior

The best way for me to explain this is with examples and my best explanation for why it may be happening because it has happened a lot:

Examples:

NVIDIA Shield: In the Filtering Log there are DNS queries to m.youtube.com, a googlevideo.com server, i.ytimg.com, & s.ytimg.com. Immediately following those queries are a bunch of https tunnel connections to my proxy server (or after 3.5 RC 1 the IPs of the above servers) - see the nvidia screen shot. There are no https or http connections listed in the Filtering Log for the servers m.youtube.com, X.googlevideo.com, i.ytimg.com, or s.ytimg.com - not immediately, soon after, or even later on. That data was transferred and logged only as https tunnel connections to my proxy server, as if ad filtering was turned off. The videos and images correctly displayed in the browser so there was no data failure.

I suspect this is somehow *part* of what is happening on my other devices too (Samsung Galaxy phones and Kindle Fire tablet - just not sure why, how, or when), as tcp connections to IP addresses are what's shown when ad filtering is disabled for individual apps and/or sites/servers and. The only strange thing about all of this is that not all data is handled as if ad filtering - or https filtering - is turned off. It's not limited to only certain servers, sites, or apps either (although it mainly happens in browsers):

1. Some browser traffic to example.com is handled normally. It shows and filters the traffic as it should (ignoring the other filtering bugs in my other reports); 
2. Some browser traffic to example.com, however, is displayed as tcp://example.com. If this was just https filtering not working it would display it as an https tunnel, correct?;
3. On devices with https filtering some browser traffic to example.com is displayed as an unfiltered tcp connection to my proxy server, while on devices without https filtering it's shown as a https tunnel connection to my proxy server (like I said above, since RC 1 this is now shown as the website's IP address instead of my proxy's). This may be explained by a partial or temporary breakdown or disabling of ad filtering for either the browser app or the site/server example.com.

### Screenshots

<details><summary>Screenshot:</summary>

![browser_traffic nvidia_shield_android_tv adguard_3 5_n11](https://user-images.githubusercontent.com/29090831/91651023-3aedbc80-ea55-11ea-8b35-0e8ca64be049.jpg)

![proxyNotRemote_and_tcpBug](https://user-images.githubusercontent.com/29090831/91651028-4345f780-ea55-11ea-9e5b-6035e0750e56.jpg)

</details>

### Additional Information

I have logs saved of this happening. I am sending to devteam@adguard.com. Also, for some reason, in Github Issues there is no reply option for me... so this may be the only post I can make on this thread. Hopefully switching to a different browser will fix this.

**Comment by zzebrum** [comment]
@infinitewaveparticle it should be fixed with CoreLibs v1.7 update
