### ISSUE TITLE
Option to Allow QUIC

### ISSUE THREAD

**Issue by borealis999** [AdguardTeam/AdguardForAndroid#3565]
### Problem Description

 No way to allow QUIC.

### Proposed Solution

 Option in settings to allow QUIC connections.

### Alternatives Considered

 I've tried to stop filtering on the QUIC enabled browser, but it just ends up with this intriguing situation
![Screenshot_2020-09-02-21-01-57-858_com adguard android](https://user-images.githubusercontent.com/66651428/92070090-b07dc380-ed9a-11ea-99d4-f6fae53a7589.jpg)
I've also attempted to manually whitelist every QUIC instance to no avail. 

### Additional Information

 I know QUIC is not good for privacy or content blocking, however, my default browser Iceweasel has uBlock Origin built in and should take care of most ad requests. I want to primarily use Adguard to block ads outside of my browser.

**Comment by JohnRTitor** [comment]
Even Cloudflare implemented it in their network. Quic introduces faster connection, the same reason as you guys implemented DNS over quic. 

 https://cloudflare-quic.com/ this official website by Cloudflare can check if the connection uses http/3. When AdGuard is enabled the site shows the connection uses HTTP/2, and when AdGuard is disabled, the connection uses HTTP/3.

**Comment by TPS** [comment]
This is _finally_ going to happen because [TikTok is broken](https://github.com/AdguardTeam/AdguardForAndroid/issues/3866) if QUIC isn't graylistable.

**Comment by artemiv4nov** [comment]
This issue has been merged with #3866.
