### ISSUE TITLE
Adguard interferes with local ftp server

### ISSUE THREAD

**Issue by techIndia-hacker** [AdguardTeam/AdguardForAndroid#3566]
Adguard version- 3.5 RC1

Filtering mode:- Local Vpn with dns set to cloudfare

Device:- Oneplus 8 at stock oxygen 10

Root:- Yes

Expected behavior:- Files from local ftp server at 192.168.0.1:21 should be accessible from browser

Actual behavior:- Access to the local server is somehow disturbed and files can't be accessed from my phone when adguard is active. My desktop and pc also has adguard installed and configured to cloudfare dns. But does not suffer from this bug. 
On Android however adguard must be turned off to access the ftp server files smoothly otherwise there is disconnecting here and there

**Comment by techIndia-hacker** [comment]
Sending bug report to support@adguard

**Comment by akmLaVx** [comment]
Received logs: 1556449.

**Comment by techIndia-hacker** [comment]
Sent a video to support@adguard for more clarity

**Comment by techIndia-hacker** [comment]
Any progress on this?

**Comment by ameshkov** [comment]
VPN is incompatible with FTP in general due to Android limitations.

The only solution is to exclude either the FTP app or the IP address of the server.
Excluding IP address is possible via low-level settings -- `pref.ipv4.routes.excluded`
