### ISSUE TITLE
Google Play: com.shark.taxi.client

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForAndroid#3567]
**The issue in AdguardFilters:** https://github.com/AdguardTeam/AdguardFilters/issues/61581

 [https://play.google.com/store/apps/details?id=com.shark.taxi.client&hl=ruterm%3Dshark+%D1%82%D0%B0%D0%BA%D1%81%D0%B8&pcampaignid=APPU_1_gv43X4m1L9-HwPAP8NGYmA8](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.shark.taxi.client%26hl%3Druterm%253Dshark%2B%25D1%2582%25D0%25B0%25D0%25BA%25D1%2581%25D0%25B8%26pcampaignid%3DAPPU_1_gv43X4m1L9-HwPAP8NGYmA8)
### Comment
Username: @ministr91
> При включённом adguard я не могу зайти в приложение и оно постоянно висит у меня на заставке. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dDZFKgM.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/CqlUAXG.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.4
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | disabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian**

**Comment by Sergey-Lyapin** [comment]
@ministr91  пришлите, пожалуйста, логи приложения с указанием времени 
<details>
<summary>Инструкция</summary>

Сбор отладочного лога
Для того чтобы собрать отладочный лог и переслать нам, нужно проделать следующее:

1. Откройте AdGuard и перейдите в раздел "Настройки".

2. Выберите в меню слева пункт "Расширенные".

3. "Уровень логгирования" переключите в режим "Записывать всё". Желательно перед этим закрыть все фоновые приложения, не связанные с проблемой.

4. Постарайтесь воспроизвести проблему, после чего уровень логгирования переключите обратно на обычный ("По умолчанию"). Заметьте точное время, когда это произошло.

5. Чтобы экспортировать логи, перейдите в раздел "Настройки — Расширенные" и тапните по пункту "Экспортировать логи и информацию о системе". В открывшемся окне выберите нужную директорию и нажмите "Сохранить".
</details>

**Comment by TheHasagi** [comment]
@ministr91

А если включите DNS (AdGuard DNS) и попробуете зайти в приложение?

**Comment by ministr91** [comment]
@TheHasagi включил, проблема осталась

**Comment by ministr91** [comment]
https://fex.net/ru/s/nxckppd
или
https://dropmefiles.com/xhQxt
14:06 включил и долго висело как на 1 скрине

**Comment by ministr91** [comment]
@Alex-302

**Comment by Alex-302** [comment]
@TheHasagi

**Comment by ministr91** [comment]
@Alex-302 @Sergey-Lyapin @TheHasagi @ameshkov 8 дней прошло с момента, как я выложил отчёт. Его вообще кто-нибудь смотрел?

**Comment by artemiv4nov** [comment]
@ministr91 Добрый день! Да, я посмотрел.

По всей видимости, приложение использует facebook трекеры. В Facebook SDK есть баг, при котором не получается им отправить данные на их сервер, если сеть IPv4-only. У нас уже [была подобная задача](https://github.com/AdguardTeam/AdguardForAndroid/issues/3031).
Приложение Shark Taxi сделали ещё и таким образом, что без отправки стат данных из-под Facebook SDK приложение нельзя использовать.
Попробуйте отключить `pref.vpn.disable.reconfigure` настройку в Low-Level настройках.

**Comment by ministr91** [comment]
@artemiv4nov спасибо, приложение заработало. pref.vpn.disable.reconfigure мне оставить отключенным? Проблемы какие-то будут, если pref.vpn.disable.reconfigure отключенным держать?

**Comment by ameshkov** [comment]
@ministr91 проблемы случались на самсунгах например из-за багов в Android, связанного с обработкой "слишком быстрого" рестарта.
