### ISSUE TITLE
For "My DNS servers", add an option for a connection-method priority rank system

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#3568]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v3.5 RC 1 (61))
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Having only begun to use *AdGuard for Android* on a fulltime basis a week ago, I'm impressed by how it's the only DNS-server-choice app I've ever come across that allow seamless use of DNS-over-HTTPS and regular DNS at the same time, without any need to change options or entire apps (Compared to Intra, Blokada and DNSpipe):

![image](https://user-images.githubusercontent.com/22780683/92226845-a399c680-eea5-11ea-9a36-174f91a20702.png)

However, AdGuard for Android seems to me to rotate at random between all listed connection methods for a server, which will make AdGuard Home logs (and any at-home units that are connected to it) harder to distinguish between. This screenshot is from AGH, where AdGuard for Android had rotated between 4 of my 5 connection methods within 10 seconds: 
![image](https://user-images.githubusercontent.com/22780683/92227855-3129e600-eea7-11ea-8b61-6a8c0fe4c3c3.png)

### Proposed Solution

A way to make AdGuard for Android primarily connect to one connection method, with the rest of the methods for a DNS server being failovers. In my case it'd be `192.168.1.168` that I'd want to have as my primary connection method, and `https://dandelionsprout.••••••••/dns-query` as the secondary connection method if the primary method is not instantly available, and so on.

### Alternatives Considered

The proposed solution above should give you guys a lot of leeway to come up with something more specific.

### Additional Information

None that I'm aware of at the moment.

**Comment by artemiv4nov** [comment]
In the current version, we resolve all DNS servers simultaneously. But if you want change a priority of what DNS server should be used, you can use our Automation API to change DNS server automatically.
