### ISSUE TITLE
How can I block this AD?

### ISSUE THREAD

**Issue by MuZhilin** [AdguardTeam/AdguardForAndroid#3570]
![Screenshot_20200907-122324_Amap.jpg](https://user-images.githubusercontent.com/7886881/92348573-0c7f7980-f106-11ea-9634-2a6b1809f909.jpg)

**Comment by MuZhilin** [comment]
This is Autonavi(高德地图）,a Chinese map app.

**Comment by TheHasagi** [comment]
@MuZhilin 

It is very similar to embedded ads, but if you clear the application cache, enable DNS and select AdGuard DNS, then the problem still persists?

**Comment by MuZhilin** [comment]
> @MuZhilin 
> 
> It is very similar to embedded ads, but if you clear the application cache, enable DNS and select AdGuard DNS, then the problem still persists?

No,the problem still persists.

**Comment by MuZhilin** [comment]
> @MuZhilin 
> 
> It is very similar to embedded ads, but if you clear the application cache, enable DNS and select AdGuard DNS, then the problem still persists?

![Screenshot_20200907-185427_AdGuard.jpg](https://user-images.githubusercontent.com/7886881/92380500-dbba3700-f13b-11ea-91fb-227333f0b80a.jpg)

**Comment by TheHasagi** [comment]
@MuZhilin 

Make sure that protection is enabled and app filtering (except HTTPS) is enabled for this app (AdGuard - Apps Management - Autonavi). If this issue still persists there is no option you can hide this ad because it is embedded.

**Comment by TheHasagi** [comment]
Closed due to no response.
