### ISSUE TITLE
OpenVPN support for AdGuard VPN

### ISSUE THREAD

**Issue by Wibblyw** [AdguardTeam/AdguardForAndroid#3571]
### Problem Description

Please consider AdGuard VPN support for OpenVPN as a client. This will open up AdGuard benefits to private VPNs. 

### Proposed Solution

Enhance AdGuard VPN with an option to support OpenVPN as a client and configuration for private VPN servers, so users have a VPN client that plays nicely with the main AdGuard product.

### Alternatives Considered

Today, when firing up a 3rd party VPN client, AdGuard does not play nicely with it, so AdGuard has to be paused for the duration of the VPN session, and restored afterwards.

### Additional Information

AdGuard VPN is today focused on supporting privacy for general internet use. Adding OpenVPN client support means users of private VPNs can easily benefit from the protection of the main AdGuard product whilst using their VPN.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdGuardVPNForAndroid #18](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/18) via [**ZenHub**](https://www.zenhub.com/)
