### ISSUE TITLE
Activity based https filter

### ISSUE THREAD

**Issue by techIndia-hacker** [AdguardTeam/AdguardForAndroid#3572]
Device:- oneplus 8 android 10
Adguard v 3.5 release
Filtering mode:- VPN
Root:- yes
### Problem Description
Adguard https filter has www.googleapis.com whitelisted. But this leads to Google trackers getting access according to your adguard base filter. So I have manually deleted the domain from whitelist.
![Screenshot_20200909-155509](https://user-images.githubusercontent.com/58086339/92587133-db917700-f2b4-11ea-9710-53cf54f4dbd2.jpg)

But now due to #1894 SafetyNet is tripped. So, @ameshkov on February 5th 2019 suggested that www.googleapis.com should be whitelisted for com.google.android.gms and later on it was implemented. But i find out that this leads to trackers leaking according to above picture.

Current situation
![Screenshot_20200909-162055__01](https://user-images.githubusercontent.com/58086339/92589922-f4039080-f2b8-11ea-9d69-2d156e263dbc.jpg)

### Proposed Solution

I suggest an alternative solution for this issue. Instead of whitelisting entire com.google.android.gms for www.googleapis.com, we can disable https filtering only for a perticular activity inside  the app responsible for SafetyNet checks which is  com.google.android.gms.unstable just like magisk.
![Screenshot_20200909-161531](https://user-images.githubusercontent.com/58086339/92589142-be11dc80-f2b7-11ea-83fe-15673b3db6ef.jpg)

In this way we block trackers as well as don't disturb safetynet

**Comment by ameshkov** [comment]
> we can disable https filtering only for a perticular activity inside the app responsible

Try adding `googleapis.com$app=com.google.android.gms` to the **HTTPS filtering exclusions list**

**Comment by techIndia-hacker** [comment]
If i add that many ads and trackers will leak

**Comment by ameshkov** [comment]
I am just showing an example of how to disable HTTPS filtering of this domain for a particular app. I doubt there can be anything more granular than this.

**Comment by techIndia-hacker** [comment]
We need activity based https whitelist

**Comment by ameshkov** [comment]
I don't understand what you mean by activity. If you mean a part of an app, that's virtually impossible to detect this on the network-level.

**Comment by techIndia-hacker** [comment]
Yeah activity means app component activities. Just go to magisk hide and see all the Google Play service activities inside gms app which the screenshot depicts

**Comment by ameshkov** [comment]
As I've said, it is not possible to detect that network connection is made by a particular component.

**Comment by techIndia-hacker** [comment]
Ok in have think...
Thanks for the input though.
And I would like to ask u to see #3551 if time permits
