### ISSUE TITLE
Some traffic leak in v3.5

### ISSUE THREAD

**Issue by lessload** [AdguardTeam/AdguardForAndroid#3575]
### Issue Details

- **AdGuard version:**
  - v3.5
- **Filtering mode:**
  - Local VPN, DNSCrypt (Adguard)
- **Device:**
  - Mi CC9 Pro (Xiaomi)
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

App should resolve DNS host url through DNSCrypt that i select.

### Actual Behavior

I found DNS host (host filter list) leak when check for update. seem like dns not resolve through DNSCrypt.

### Additional Information

As i test, v3.5 less traffic leak than v3.4 & v3.3.3

In xiaomi device still leak some traffic like
>    find.api.micloud.xiaomi.net
>    api.sec.intl.miui.com
>    app.chat.global.xiaomi.net

Hard to fix that without root, as i understand.

Still in long-term test. Good update.

**Comment by zzebrum** [comment]
@lessload it may have happened during the update and restart processes
