### ISSUE TITLE
com.hbo.android.app - app is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3577]
@adguard-bot commented on [Tue Sep 08 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63434)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.hbo.android.app](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.hbo.android.app)
### Comment
Username: @gabbsmo
> After signing in to HBO Nordic on Android with AdGuard enabled I get this "No network" error. I do not have this problem with the service in Google Chrome for Windows where I use the browser extension. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/HMrsJew.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/zMhbYqC.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 8.0.0
AdGuard product: | AdGuard for Android vv3.1.0 (1.3.347cl)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> Frellwit's Swedish Filter

---

@Alex-302 commented on [Wed Sep 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63434#issuecomment-689740125)

Not reproduced. Could you please check with disabled filters?

---

@gabbsmo commented on [Thu Sep 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63434#issuecomment-689819296)

Same error with all filters disabled.

I noticed that I get the same error when connecting through a L2TP VPN and get the same error as with AdGuard VPN.

Could it be a combination of VPN, Samsung Experience and/or Android 8?

---

@Alex-302 commented on [Fri Sep 11 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63434#issuecomment-691051303)

Probably this is caused by VPN.
Please collect debug level logs after reproducing an issue + time stam;
https://kb.adguard.com/en/android/solving-problems/log#debug
and send to support@adguard.com with the link of this issue.

I will move this issue to Android repository.

**Comment by gabbsmo** [comment]
I have sent a "bug" feedback as per the instructions in your kb link. I added a link to this issue as description.

**Comment by akmLaVx** [comment]
Logs have been received and can be accessed via the following Helpdesk ticket: 2901414.

**Comment by ameshkov** [comment]
@gabbsmo temporary solution: uncheck "AdGuard protection" for that app in the Apps Management

**Comment by gabbsmo** [comment]
How do I do that? Is there a manual page?

**Comment by zzebrum** [comment]
@gabbsmo go to AdGuard app - side menu - Apps Management - find there `com.hbo.android.app` and disable AdGuard protection switch.

**Comment by Chinaski1** [comment]
@gabbsmo 
Hello there!

As I understand your support number is 2901414?
Judging by the logs you use version 3.1.0, the current version is - 3.5.56, please update.

If the issue is still reproduced after the update:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by gabbsmo** [comment]
@Chinaski1 I have sent two emails with the AdGuard log and Android bug report respectively. Time stamp and Github issue id is in the subject line.

**Comment by Chinaski1** [comment]
I only got the bug report, but unfortunately, the application logs did not reach devteam@adguard.com.

**Comment by gabbsmo** [comment]
@Chinaski1 Oh sorry, I mixed it up. I sent the application log through the send feedback function.

**Comment by Chinaski1** [comment]
@gabbsmo 

Please check the HBO application settings. Isn't there a setting that only allows the application to access the network when using Wi/FI?

**Comment by gabbsmo** [comment]
@Chinaski1 There is a setting to only allow downloading on Wifi. Is that what you are referring to?

**Comment by Chinaski1** [comment]
Is this feature enabled?

This setting can also be called "traffic saving" or something similar.

**Comment by gabbsmo** [comment]
@Chinaski1 Disabling that feature does not affect the issue. There is no "traffic saving" or similar.

**Comment by Chinaski1** [comment]
If you do not mind, I would also like to ask you to check the situation in the HTTP proxy filtering method.
- Open AdGuard settings > Network > Filtering method > Local HTTP Proxy.

**Comment by gabbsmo** [comment]
The issue does not reproduce with the local HTTP proxy.

**Comment by akmLaVx** [comment]
We've received another portion of the logs. Helpdesk ID is 2901414

**Comment by admitrevskiy** [comment]
@gabbsmo Hi!

In this thread I cannot see a result of [this](https://github.com/AdguardTeam/AdguardForAndroid/issues/3577#issuecomment-696033920) action. Did it help?

Furthermore could you try to disable `pref.vpn.disable.reconfigure` in Low-level settings? (Menu -> Settings -> Advanced -> Low Level Settings)?

**Comment by gabbsmo** [comment]
@admitrevskiy Disabling "Adguard protection" for the HBO works as a workaround.

If I leave protection on, the error still shows with `pref.vpn.disable.reconfigure` disabled.

**Comment by admitrevskiy** [comment]
Seems like HBO android app doesn't work with VPN (as you've mentioned other VPN apps also break HBO connection)

This issue can't be fixed from our side and disabling AdGuard protection is the only way to let it work in VPN filtering mode :(

**Comment by gabbsmo** [comment]
@admitrevskiy OK I understand. Any reason I should not use the HTTP proxy mode since the VPN mode is the default?

**Comment by admitrevskiy** [comment]
There are restrictions on the use of mobile data related to manual HTTP proxy mode. If you have a root permission you can use automatic mode without any restrictions.
