### ISSUE TITLE
Block ads in all apps not working in V3.5

### ISSUE THREAD

**Issue by sdugoten** [AdguardTeam/AdguardForAndroid#3580]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  v3.5 for Android premium
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -   Sony XZ3
- **Operating system and version:**
  -  Android 10
- **Root access:**
  -  No

### Expected Behavior

Block ads in all apps should be working for all apps, I have set Filters and User rules under "Content blocking", and it used to be working in v3.32 .

### Actual Behavior

The block add in all apps stop working in v3.5.   I will have to enable "DNS filtering" and put all User rules inside DNS filtering in order to have Adguard works on all apps.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by bosaad21** [comment]
I have the same problem on my device Samsung galaxy s10

**Comment by Bhooty** [comment]
I have the same prpblem on my samsung note 8
If I use google duo
Adguard for some reason thinks i am using another vpn and autopause

**Comment by Chinaski1** [comment]
@Bhooty 
Hello!
This is a [known issue ](https://kb.adguard.com/en/android/solving-problems/restricted-profile)and unfortunately, there is nothing we can do on the application side.

@bosaad21 @sdugoten 
Ads is not blocked only in certain applications?
Open Apps management and check if HTTPS filtering is enabled for these apps?

**Comment by Bhooty** [comment]
Should i exclude duo from protection?
Will that work?

**Comment by bosaad21** [comment]
> @Bhooty
> Hello!
> This is a [known issue ](https://kb.adguard.com/en/android/solving-problems/restricted-profile)and unfortunately, there is nothing we can do on the application side.
> 
> @bosaad21 @sdugoten
> Ads are not blocked only in certain applications?
> Open Apps management and check if HTTPS filtering is enabled for these apps?

Yes, specially Snapchat as mentioned here
https://github.com/AdguardTeam/AdguardFilters/issues/63805

**Comment by Chinaski1** [comment]
@Bhooty 
You should totally disable this feature or use `adb`
