### ISSUE TITLE
ru.alarmtrade.connect is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3583]
@adguard-bot commented on [Mon Sep 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63861)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=ru.alarmtrade.connect](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.alarmtrade.connect)
### Comment
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/se7T6I6.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/FY3vAAg.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.5 (63)
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Block third-party Authorization header, <br/>Disable cache for third-party requests, <br/>Block WebRTC, <br/>Block Push API, <br/>Block Location API, <br/>Hide your Referrer from third-parties (), <br/>Hide your Referrer from third-parties, <br/>Hide your User-Agent (), <br/>Hide your IP address (209.141.53.254)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>AdGuard Base, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> Fanboy Anti-Facebook List, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> RU AdList: Counters, <br/>AdGuard Russian, <br/>RU AdList, <br/>RU AdList: BitBlock
Custom filter subscriptions: | 
Other extensions used: | Avast

**Comment by Alex-302** [comment]
Logs from my device
[adguard-.log](https://github.com/AdguardTeam/AdguardForAndroid/files/5238287/adguard-.log)

This app works if `AdGuard protection` is disabled for this app.

**Comment by Versty** [comment]
@Alex-302 Is this problem still relevant?

**Comment by Versty** [comment]
Closed as outdated. Please reopen if any user comes back with the same case.
