### ISSUE TITLE
Tracking parameters not stripped when using custom stealth mode

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdguardForAndroid#3584]
### Issue Details

- **AdGuard version:**
  - v3.5.63
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Moto G5 Plus
- **Operating system and version:**
  - Android 8.1
- **Root access:**
  - No

### Expected Behavior

Tracking parameters are removed when custom stealth mode is used.

### Actual Behavior

Tracking parameters are removed when using high setting in stealth mode, but not when using custom setting.

### Additional Information

When posting a linked shared from another android app into a browser and using custom mode for stealth, tracking parameters like `utm_source` and `utm_medium` are not stripped. When changing to high, everything works like normal.

**Comment by Chinaski1** [comment]
Hello there!

Is the issue reproduce in some particular browser?
If you open the Stealth-mode settings and check the Tracking parameters, will the [specified configs](https://uploads.adguard.com/Chinaski6kuz6.png) be displayed there?

**Comment by BlitW0** [comment]
It occurs when I paste a link copied from share sheet on the official reddit app. Reproducible in Chrome and Samsung Internet Beta. These are the configs I have, unmodified:

![Screenshot_20200921-191320](https://user-images.githubusercontent.com/42700209/93774329-c581a000-fc3e-11ea-8ec4-3dbd2eb24118.png)

![Screenshot_20200921-191312](https://user-images.githubusercontent.com/42700209/93774344-cb778100-fc3e-11ea-9245-4999d80ce247.png)

**Comment by Chinaski1** [comment]
@BlitW0 
The tracking parameters look weird.
Can you try to list them not using the spacebar and through line shift as in the screenshot I sent above?

**Comment by Chinaski1** [comment]
I managed to reproduce the situation you mentioned.
We will fix this problem in the next update, thanks for the feedback.
Also, we have similar request at #3561

**Comment by Eugene-Savenko** [comment]
@Chinaski1 can you look into it once again, please? More information in the #523959 ticket.  

> Furthermore, (and I've created issues about this that are now closed even though it still happens - see Issues #3561 & #3647), tracking parameters I've added to Stealth Mode (custom level chosen) are still not stripped on my Samsung Galaxy S7 Edge running stock Android 8. See screenshots. I've been hoping for a fix since the issues were closed, but none ever came. Note that I simply created dummy sites to test these on, but I assure you it happens on real sites too. The yptr parameter I made into a $removeparam user filter rule because I was sick of Stealth Mode not working to strip it. This problem has persisted since at least v3.5 RC1.

<details>

![image](https://user-images.githubusercontent.com/15856304/127112572-0604cb0a-abff-4cb8-9ed9-243bee199b2c.png)

![image](https://user-images.githubusercontent.com/15856304/127112596-4e4f30c9-8b6d-4425-bdb5-f50fc7241260.png)

![image](https://user-images.githubusercontent.com/15856304/127112622-c1125d8c-8fc4-451a-acf1-04eb4e553adb.png)

**Comment by artemiv4nov** [comment]
@Chinaski1 Any news?

**Comment by infinitewaveparticle** [comment]
It also doesn't say "Tracking parameters stripped" in the Stealth Mode section so something is telling AdGuard that the option is disabled even when it's enabled.

**Comment by Chinaski1** [comment]
I try to reproduce [specified situation](https://uploads.adguard.com/Chinaskiuwenm.png) but tracking parameters are stripped [as expected](https://uploads.adguard.com/Chinaskizdlu4.png).
Please specify which version of AdGuard are you currently using?

**Comment by infinitewaveparticle** [comment]
@Konstantin I think this issue is fixed for literally everyone but me. It has never been fixed for this device (Samsung Galaxy S7 Edge, Android 8), although it works on my other devices (Android 5 & 7). I am using 4.0 Nightly 20.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment]
We have Galaxy G7 (With Nightly 20) and I have just checked the above situation on it.
The parameters were cut without any problems.
Please specify in which browser do you check and which domains do you use?
Could they be in HTTPS exceptions or in the allowlist?

**Comment by Chinaski1** [comment]
@infinitewaveparticle 

I was eventually able to reproduce your issue.
The thing is, I entered one specific parameter and it successfully cut out. And if there was more than one in the settings list, they no longer cut out. This was due to a change in rule syntax.

All in all, we decided to abandon this setting in favour of the [AdGuard URL tracking filter](https://github.com/AdguardTeam/CoreLibs/issues/1438).

**Comment by artemiv4nov** [comment]
We have to fix it ASAP, the task is planned for 3.6.3.

**Comment by infinitewaveparticle** [comment]
@Konstantin

This happens in Firefox, Firefox Beta, and Fennec F-Droid browsers (HTTPS filtering is working great). Prior to *about* v3.5 RC1 the tracking parameters were stripped perfectly. After that they stopped being stripped. When you fixed the Custom Stealth Mode issue it worked again, but then I added my own list of parameters to the list and ever since then it has been permanently broken (only on my Galaxy S7 Edge running Android 8). I've always used Custom Stealth Mode. The domain doesn't matter. You name it, it won't work. It won't say "Tracking parameters stripped" under the Stealth Mode reasons for modification, nor will any of the parameters listed ever be stripped unless they're included in the AdGuard URL Tracking filter or manually added as $removeparam rules. I really don't get it. What do my logs tell you?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
@Konstantin

More than one what? How can I fix this in the meantime?

Will you be removing tracking parameters from Stealth Mode entirely? And are we to simply make $removeparam rules for any parameters we wish to strip manually?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
> @infinitewaveparticle
> 
> I was eventually able to reproduce your issue.
> The thing is, I entered one specific parameter and it successfully cut out. And if there was more than one in the settings list, they no longer cut out. This was due to a change in rule syntax.
> 
> All in all, we decided to abandon this setting in favour of the [AdGuard URL tracking filter](https://github.com/AdguardTeam/CoreLibs/issues/1438).

@Chinaski1 By this do you mean you are removing the Strip Tracking Parameters section from Stealth Mode? Will you be fixing this error? Or should I convert all of my custom added parameters to a custom filter using $removeparam / $queryprune ?

**Comment by Chinaski1** [comment]
On Friday we released the [Nightly](agrd.io/android_nightly) version.
In it, we removed the ability to add custom parameters in the Stealth-mode section.
Now as you correctly noticed you can do it with modifier $removeparam
I want to note that if you have Custom strip parameters, they will be converted into separate User filter during the update.
