### ISSUE TITLE
AdGuard fails to pass Cloudflare DDOS protection

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3585]
### Issue Details

- **AdGuard version:**
  - 3.5.63
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung SM-G975N
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Actual Behavior

All sites protected with Cloudflare DDoS prevention cannot be opened.

### Additional Information

DNS: AdGuard DNS DoH
Helpdesk ID & logs: 1925607

**Comment by Chinaski1** [comment]
I tried to reproduce the issue but the attempt was not successful, AdGuard DNS (DoH) passed Cloudflare DDOS protection.

Ask the user to make the following operations:
- Export the settings;
- Use setup wizard (to reset all settings);
- Enable debug logging;
- Reproduce the issue ;
- Send logs again (Also, be advasible if he specified time of the issue).

It is also useful to specify additional information:
- The issue reproduces only with AdGuard DoH (did he try to change the server or its type)?
- The issue did not occur before the last update?

**Comment by akmLaVx** [comment]
Will do

**Comment by Chinaski1** [comment]
The issue is not reproduced.
The user does not respond to a support call.
I close the task, re-open it if necessary.
