### ISSUE TITLE
Samsung GalaxyS10 OneUI 2.5 update breaks filtering

### ISSUE THREAD

**Issue by Laurisade** [AdguardTeam/AdguardForAndroid#3588]
### Issue Details

- **AdGuard version:**
v4.0 nightly 2 (12-1.7.109cl)
- **Filtering mode:**
Local VPN
- **Device:**
Samsung Galaxy S10 (Exynos) with stock firmware.
- **Operating system and version:**
Android 10, OneUI 2.5 (September patch)

### Issue
Filtering seems to be broken after OneUI 2.5 Update. A lot of empty spaces in all sites. One screenshot example is attached. Tried with many browsers - same result. 
![Screenshot_20200919-182125_Samsung Internet Beta (1)](https://user-images.githubusercontent.com/6094860/93670694-ecf13500-faa5-11ea-8318-93a0a8bd604a.png)

**Comment by Chris79100** [comment]
Same for me with my s10+ ( exynos ) with same adguard nightly. And it seems I've got cookies banner from sites that were fine before.
Everything was fine before the update.

**Comment by Laurisade** [comment]
> Same for me with my s10+ ( exynos ) with same adguard nightly. And it seems I've got cookies banner from sites that were fine before.
> Everything was fine before the update.

Yeah, I did get cookie notices as well :)
Hope this gets fixed soon, as I had to install Adguard Content blocker for Samsung Internet.

**Comment by zzebrum** [comment]
guys, please, check that https filtering is enabled in AdGuard settings and AdGuard certificate is present on webpages in browsers.

**Comment by Chris79100** [comment]
Https is on, already checked this. All my settings are the same as before. 
How to check the second one please? In browser? ( chrome for me )

**Comment by Neon329** [comment]
@Chris79100 

> Https is on, already checked this. All my settings are the same as before.
> How to check the second one please? In browser? ( chrome for me )

Click on the padlock icon in the address bar on the top left and see if the certificate information says that `AdGuard Personal CA` issued this website's certificate. If yes, then AdGuard is handling the HTTPS filtering for the website otherwise no. 

Example website you can check this on: https://www.wikipedia.org/

Also, can you follow this article to see the AdGuard process isn't being cleared in the background by the OS? -- https://kb.adguard.com/en/android/solving-problems/background-work

**Comment by Chris79100** [comment]
Adguard certificate ok for chrome.
Adguard is not cleared by the OS, I think that was the first or second thing I've checked when the problem started ( had this problem with an OS update on my s10+ in the beginning )

**Comment by akmLaVx** [comment]
Received new logs, see ticket 1014786

**Comment by Laurisade** [comment]
A small update.
I have reset the system and with latest stable version of Adguard, everything works as intended. v3.5 (63)

After upgrading to latest Nightly, it seems to be fixed... Will monitor the situation.

**Comment by Chris79100** [comment]
Will try that and tell if it works for me.

**Comment by zzebrum** [comment]
guys, how it's going on? I didn't receive the OneUI v2.5 yet (

**Comment by Chris79100** [comment]
Everything went right with the different adguard nightly upgrades + filters update.
So everything is great again now.

**Comment by zzebrum** [comment]
reopen if needed
