### ISSUE TITLE
The "Hide your User-Agent" option in the Stealth Mode is a bit misleading with its description

### ISSUE THREAD

**Issue by Neon329** [AdguardTeam/AdguardForAndroid#3589]
## The problem

The "Hide your User-Agent" option in the Stealth Mode is somewhat misleading with its current wording.

So, here's the problem: I am using AdGuard since a month now. As I started to explore its features, I discovered just how many features AdGuard had and it was a perfect solution for me. 

And as soon as I discovered the existence of Stealth Mode I started changing and experimenting with all the settings and toggles it had. But there was a problem I didn't notice (and I kept on browsing believing something that was not correct) and it was that the option "Hide your User-Agent" actually didn't hide the user agent, and so I thought it was a bug and I went to report it to the Support. The answer I got was completely unexpected. They said the it was not a bug but rather it was by design. It was working as expected. 

The option has these strings in it:

*"Hide your User-Agent > Remove identifying information from the User-Agent header."*

I thought if I enable this option, the identifying information will be stripped since the string says that it is removing the identifying information. And I also had the extra assurances that the "Hide your User-Agent" option was enabled so I thought I was set. I thought AdGuard now won't reveal anything personal to the websites from my browser's User-Agent. 

And furthermore in a sub menu it says: 

*"Custom User-Agent > The default behaviour is to remove the identifying information from the browser. Leave empty to use the default behaviour."*

By the above string I again thought that the *default behaviour* is to *remove* the identifying information and if I leave empty *that* default behaviour of *removing identifying information* will be used. 

Out of curiosity, I went to a website which checks for User-Agents. And to my surprise the user agent was just like before. I uninstalled AdGuard and reinstalling it thinking it might a temporary bug, nothing happened. Restarted the browser and device, again nothing happened. 

Checked with Chrome browser, Samsung Internet Browser, etc. it was the same, other browsers also seemed to behave the same, except in Samsung Internet Browser's case the word "SamsungBrowser/version_number" was removed from the User-Agent string. 

This was completely unexpected for me. What I expected was that AdGuard would remove my device information (its name), and other identifying information and give me a user agent similar to what Firefox for Android has. But customer support said that AdGuard doesn't remove anything from the user agent unless a custom user agent was manually added by the user and *just* turning on "Hide your User-Agent" option doesn't do anything.

This is a bit misleading and I think it needs to be changed.

**Comment by zzebrum** [comment]
@Neon329 if you are not using custom user-agent, then it is indeed removing very little information. 

we can do 2 things: 
- change the description
- see if we can enhance the work for the option on mobile devices: https://github.com/AdguardTeam/CoreLibs/issues/1345
