### ISSUE TITLE
Total traffic displayed under "App Management" is not actually total data traffic of the device

### ISSUE THREAD

**Issue by Neon329** [AdguardTeam/AdguardForAndroid#3590]
When AdGuard says that it is total traffic of the device under the "App Management" lable users are bound to mistake it for the actual total device traffic and not just data traffic of the apps that AdGuard has filtered from. I think this needs to be changed.

**Comment by Chinaski1** [comment]
In this section of statistics, we count all traffic used by applications.
Applications that are not included in statistics are marked as [No Data](https://uploads.adguard.com/Chinaskil4tco.png).

**Comment by Neon329** [comment]
Hi, @Chinaski1 thanks for the reply. 

I think there's some confusion here. When I contacted the Support this was the response I got:

![Screenshot_20200922_163739](https://user-images.githubusercontent.com/70356738/93875149-17373280-fcf2-11ea-9521-991e4ed2d784.jpg)
