### ISSUE TITLE
Android TV: Unable to Activate via Google authorization (Error 403: disallowed_useragent) 

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#3592]
- **AdGuard version:**
v3.5
- **Filtering mode:**
Filtering is set to OFF (as it's not available on stock Android TV)
- **Device:**
MiBox3
- **Operating system and version:**
8.0.0
- **Root access:**
no

I tried to activate your account via Google authorization, but I get this error in the popup window.
Typically on Android TV with Google authorization you don't see a separate "browser" window popping up.

**Comment by Chinaski1** [comment]
Hello there!

The fact is that we do not provide official support for Android TV, so we can not guarantee the correct operation of the application.
We may add this feature in the future, but I can't say anything more specific.
