### ISSUE TITLE
Android TV: Navigation SOUND effect missing in some screens

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#3593]
- **AdGuard version:**
v3.5
- **Filtering mode:**
Filtering is set to OFF (as it's not available on stock Android TV)
- **Device:**
MiBox3
- **Operating system and version:**
8.0.0
- **Root access:**
no

When using the DPAD input to navigate across UI items, typically there's a navigation sound effect / audio feedback.

Content blocking screen works fine (Network, Updates, DNS filtering and some others too). 
But other screens are either partially or completely missing this:
- Main menu (from hamburger)
- Settings
- Filters
- Stealth mode
- Advanced

**Comment by Chinaski1** [comment]
Hello there!

The fact is that we do not provide official support for Android TV, so we can not guarantee the correct operation of the application.
We may add this feature in the future, but I can't say anything more specific.

**Comment by oroboros** [comment]
OK, thanks! 

But another way to look at it is that AdGuard *does* work on Android TV. Since it seems to work fine on most screens except those few, it seems like it's a very simple UI bug (functionality is not broken) that makes AdGuard work even more properly on Android TV.
