### ISSUE TITLE
Android TV: Navigation VISUAL effect missing in some screens

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#3594]
- **AdGuard version:**
v3.5
- **Filtering mode:**
Filtering is set to OFF (as it's not available on stock Android TV)
- **Device:**
MiBox3
- **Operating system and version:**
8.0.0
- **Root access:**
no

When using the DPAD input to navigate across UI items, typically there's a visual feedback, with the current selection being highlighted.

For example, General and Content blocking screens work fine.

In Apps Management screen, items don't start getting the visual feedback of selection - being highlighted - until you "scroll" some 10 times.
- In Extensions, the last two items get an audio feedback of being selected, but don't have the visual feedback.

**Comment by oroboros** [comment]
@Chinaski1 Please note this is not a duplicate: one issue was opened for missing VISUAL effects and one for missing AUDIO effects. Please reopen.

**Comment by Chinaski1** [comment]
Hello there!

The fact is that we do not provide official support for Android TV, so we can not guarantee the correct operation of the application.
We may add this feature in the future, but I can't say anything more specific.

But I can advise you to use the free [AdGuard Home](https://github.com/AdguardTeam/Adguardhome) utility.
It filters ads on Android TV pretty well.

**Comment by oroboros** [comment]
OK, thanks! 

But another way to look at it is that AdGuard *does* work on Android TV. Since it seems to work fine on most screens except those few, it seems like it's a very simple UI bug (functionality is not broken) that makes AdGuard work even more properly on Android TV.
