### ISSUE TITLE
Some websites completely break when the Stealth Mode is set to "High"

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3595]
Refer this comment for steps to reproduce: https://github.com/AdguardTeam/AdguardFilters/issues/63762#issuecomment-696487713

Main issue thread: https://github.com/AdguardTeam/AdguardFilters/issues/63762

It's been more than 11 days and filter maintainers tried to reproduce the issue but they can't seem to reproduce it. 

Moving this issue here in the hope that more people look into it. I'm done now, I don't have anymore patience left to wait. It's been more than 11 days. Placing this issue here, if you want to improve your product you *will* look into it seriously, otherwise even if you don't, I don't care. Sorry but If you take 4 to 5 days to respond to a single comment while I keep on waiting, waiting and waiting for your response, this is not the way to respond to bug reports from general users. Nobody will bother for your response and they will probably move on thinking that they're not going to get any response. I thought at least AdGuard was a bit more responsive to their users but it seems that is not the case. I'll keep on using your product but this has given me a bad impression of you. Thank you.

**Comment by zzebrum** [comment]
Hi there! Sorry to hear that :( 

1. Any option from Stealth mode is a powerful one and can break site functionality.  You should use them only if you know what you are doing. 
2. All the links you have mentioned are free shortener services which are often designed full of malware. 

Most likely the solution will be to disable the culprit option. 

A temporary solution is to disable Stealth mode and  DNS filtering.

I'll take a look at this issue tomorrow.

**Comment by Ruslanrem** [comment]
@ghost Looks like this is expected behavior of the stealth-mode feature because ads have been added to the policy of these domains.
Also, page can be affected by SDNF filter(So you can disable DNS feature)
You can always use the whitelist option (settings - content blocking - whitelist), and continue using the high mode.
