### ISSUE TITLE
Add Android TV OS support 

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#3597]
AdGuard already works fine on Android TV, but it needs to be sideloaded.

Since it already works on Android TV, the one thing that is missing is an icon launcher, which can be fixed by adding the following code and a larger size icon:

Source: http://stackoverflow.com/questions/32449904/how-to-make-a-android-tv-app-without-using-leanback-lib
Code:

`<uses-feature android:name="android.software.leanback" android:required="false" /> <uses-feature android:name="android.hardware.touchscreen" android:required="false" /> android:banner="@drawable/banner" <category android:name="android.intent.category.LEANBACK_LAUNCHER"/>`

Beyond adding the Android TV launcher, there are only a few minor tweaks that need to be made to your code, and almost all of them regard the UI (like a few screens, not all, which are missing the highlight when items are selected and stuff like that):
https://github.com/AdguardTeam/AdguardForAndroid/issues?q=%22android+tv%22

But these are all GUI issues which do not effect functionality. Adding the code above would already make it usable.

**Comment by oroboros** [comment]
I'm gonna pump this up, considering the new version in development, especially since v4 seems to break a lot of UI issues previously fixed.

**Comment by alextallinn** [comment]
Not working correctly on my "Sony BRAVIA 4K UR3" Android TV 8.
Incorrectly shown UI, so unable to use it!!!

**Comment by redtrillix** [comment]
Are we able to get support for the Amazon Fire TV OS?, I've tried with both Nightly and Beta and it's currently not very usable.

**Comment by maxikuzmin** [comment]
@redtrillix there will be a release today, there will be a separate build for TV, please try it. If you have any problems, please open a new issue

**Comment by oroboros** [comment]
I'm reopening this issue because somewhere between v4.3 and v4.7, AdGuard for Android TV has lost very basic and important functionality that was previously available.

Specifically, two critical features have disappeared:

1. **Import/Export Settings** – The ability to back up and restore settings.
2. **Filter Selection** – The ability to manually choose which filters to keep active (ad, privacy, social, language-specific, and other filters).

According to your support team, "We have clarified information with our developers. There were no such option to import/export settings on the AdGuard version for Android TV." However, as documented in this issue here above, all these options were indeed present in earlier versions. 

There doesn’t seem to be any valid reason for their removal, and I suspect this may be a bug causing certain menu items to be hidden. Could you confirm whether this is an unintended regression, and if so, whether these features can be restored?

**Comment by alextallinn** [comment]
Super, thank you, now it is working on  "Sony BRAVIA 4K UR3" Android TV 8. But application itself is not visible on standart AngroidTV application list. It is posible to find in in confinuration, application list. So it is hard to use!
But UI working fine, thank you!
*****
Великолепно, спасибо большое, наконец-то оно заработало на телевизоре "Sony BRAVIA 4K UR3" Android TV 8. Но само приложение не видно в стандартном списке приложений. Его возможно найти в настройках списке приложений, но там сложно искать.
Но сам интерфейс работает правильно, проблем не заметил, Спасибо!
