### ISSUE TITLE
A way to know number of filter rules count currently in use

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3599]
A way to know number of filter rules count currently in use like how desktop extension displays (see the screenshot). Currently there is no way to know the number of filter rules count (at least I couldn't find it) in use, it would be great if we can know the number of filter rules count currently in use. 
![Screenshot (34)](https://user-images.githubusercontent.com/70356738/94364701-ffdcb880-00e8-11eb-8e96-62a7b3789def.png)

**Comment by zzebrum** [comment]
closed as a dup of #3348
