### ISSUE TITLE
can't redirect to the page

### ISSUE THREAD

**Issue by nri82** [AdguardTeam/AdguardForAndroid#3600]
While use this [forum](mobile.donanimhaber.com) page shows a advertisement page and gives you 8 seconds and after redirect you to the page. If you don't want to wait 8 seconds you should click to the skipping button. But it's only works with firefox but not works with chrome or other chromium based browsers (Samsung internet, edge etc)

I have record a screen video

https://streamable.com/r2ro4q

Forum address mobile.donanimhaber.com

Android 10
Adguard 3.5

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardFilters #64870](https://github.com/AdguardTeam/AdguardFilters/issues/64870) via [**ZenHub**](https://www.zenhub.com/)
