### ISSUE TITLE
[Feature] Exclude de.materna.bbk.mobile.app from protection

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForAndroid#3602]
https://play.google.com/store/apps/details?id=de.materna.bbk.mobile.app

When first installing NINA and setting it up works. After a week or two the app claims it has no internet connection (push messages still work). After disabling AdGuard protection for the app one can see the messages for the selected locations again and no error message.
When enabling protection again it will work for a while until you see the message again.

This is on latest 4.0 nightly 4.

**Comment by moonseppel** [comment]
Any idea when this will be implemented? Or is there a possible workaround? That push messages work takes the important pain out of it, but this is still bugging me. As it's the official warning app from governmental organizations, I'd love to have it working correctly.

**Comment by Chinaski1** [comment]
@moonseppel 

Hello!

As a temporary solution, you can completely disable AdGuard protection in the Apps management section.

**Comment by moonseppel** [comment]
Thanks :) But no chance to manually whitelist some URLs?

**Comment by Chinaski1** [comment]
Settings -> Network -> HTTPS filtering -> Add domain to the Allowlist

**Comment by moonseppel** [comment]
And which ones are needed to make NINA wirk properly again?

**Comment by Chinaski1** [comment]
This information can be found using the AdGuard `filtering log`.
However, there is no guarantee that the application will work correctly once the domain is unblocked.
Therefore, it is easier to temporarily disable the filtering for it.

**Comment by BlazDT** [comment]
Lately there has not been any warning in my area. So cannot tell.

**Comment by max19-8** [comment]
@moonseppel
if the problem occurs again - please reopen the issue

**Comment by jpralle** [comment]
I neither have had any warnings, but when I open the app it does not complain about a missing internet connection, so I guess it's solved.

**Comment by moonseppel** [comment]
I neither have had any warnings, but when I open the app it does not complain about a missing internet connection, so I guess it's solved.

**Comment by maxikuzmin** [comment]
@BlazDT @moonseppel for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
