### ISSUE TITLE
Blocking internet connection when used alongside 3rd-party VPN

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdguardForAndroid#3603]
### Prerequisites

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.5.63
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - One Plus 7
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Expected Behavior

Stable work in auto proxy mode with 3rd party VPNs.

### Actual Behavior

User needs to disconnect VPN at first to connect to internet.
Once connected, he can activate VPN and then everything is ok.

### Additional Information

Started at 3.5. Uses kill switch. The issue happens occasionally. Logs are in a Jira ticket.

**Comment by beeshyams** [comment]
This bug was reported on my OnePlus 7,Android 10. **Three months later and on Pixel 4a, Android 11, it still happens occasionally.**

Team Adguard, this is disappointing

**Comment by artemiv4nov** [comment]
This issue has gone in the 4.0 version, please follow updates.
