### ISSUE TITLE
Add Amazon Silk Browser to browsers list

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3604]
@adguard-bot commented on [Sat Sep 26 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64590)

Can be downloaded here: https://4pda.ru/forum/index.php?showtopic=736849&st=100

**Comment by eerdnecm** [comment]
As someone with a Kindle, and Fire TV devices, this would be great. At the current moment, Adguard only does the minimum on these browsers. It would be great if AdGuard cosmetically fixed how pages look.
