### ISSUE TITLE
[UX] It is very hard to know where to enter the license key and there's too much focus on promoting to get the premium version of AdGuard

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3606]
***The tale of activating AdGuard Premium after a certain person bought it:***

1.  I clicked on the hamburger menu on the left, I saw a button and out of curiosity I clicked on `**License Status**`*, in the hope that I may get some sort screen to enter my key.

But what made me even sadder was a person beside me standing and uttering, in a somewhat silent voice:

 "*No license. Oh, no :( ...*"

I couldn't wait to let that person know -- no, you needn't be this sad. I was about to let that person know about something good, but I was devastated to know this that I myself was about to get even sadder than the person standing beside me: 

![Illustration 2](https://user-images.githubusercontent.com/70356738/94645333-32fd9280-0309-11eb-8597-fc807f04d979.jpg)

2. ...Wait what if I don't do that but click on this `**Get Premium**` beside that sad person I saw earlier:

![Illustration 1](https://user-images.githubusercontent.com/70356738/94644979-4d833c00-0308-11eb-8bee-35f7c8f04a72.jpg)

But who knew the destiny had planned something else...

3. After being faced with a giant screen in front of them. They get faced with two more buttons but even after clicking them they were not happy. But instead they were again more confused, they didn't know where to enter the license key they bought earlier. They were very nervous, a chill ran down of a person's spine. That person thought perhaps it isn't in their fate to use that amazing, the very good, the cool one, the AdGuard Premium they bought earlier. They thought it isn't just in their destiny to have good things for once. The fate might to be not use it but only gaze upon its awe: 

![Illustration 3](https://user-images.githubusercontent.com/70356738/94645377-5294bb00-0309-11eb-8ece-61726e30c8d1.jpg)
![Illustration 4](https://user-images.githubusercontent.com/70356738/94645425-70622000-0309-11eb-85ed-2352cb4a3ffc.jpg)

4. Let down by this twisted world that person gives a final try. With all their might, they courageously clicked on the three-dot menu at the upper right corner. They got again greeted by the promotion to get the... premium version, again. 

*What have I done wrong? Why is this happening to me? Why are these things that are happening to me are happening to me...? Why can't I be happier? Why I couldn't get that AdGuard premium version I bought earlier...? Why ..?* 

Those were some of the words uttered by a person who was completely hopeless, hopeless to the very end of the abyss.

 
![Illustration 5](https://user-images.githubusercontent.com/70356738/94645521-a7383600-0309-11eb-955c-bd546ab550c2.jpg)

5. By these many trials and errors they think that if... maybe... perhaps... they click on this **`Acivate Premium`** option they might get to enter their keys... their wish was finally granted (before clicking on that button they still thought that they'll again get greeted to buy the license again) by these screens: 
![Illustration 6](https://user-images.githubusercontent.com/70356738/94645834-786e8f80-030a-11eb-92e7-ef6f4b3707e1.jpg)
![Illustration 7](https://user-images.githubusercontent.com/70356738/94645838-7b698000-030a-11eb-9ec1-e887feaa83f6.jpg)

Seeing those screens that actually let that person enter the license key they had bought... they were the happiest person alive at that moment.

That person lived happily ever after that. 

The Superman with the green cape had finally brought justice and peace upon this world. That person thought. There was only appreciation in their heart.

~ End ~.

***P.S. Can I have the the **`Activate`** button on the bottom right side of the screen Instead on the bottom left of the screen? Please...***

**Comment by zzebrum** [comment]
And again, it will be done when new design arrives 👍
