### ISSUE TITLE
Update Wiki to Help App Developers

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3607]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Problem Description

App developers might not know how to trust the AdGuard certificate to allow HTTPs/advanced filtering

### Proposed Solution

Create a section in the wiki that gives a useable example for allowing the AdGuard certificate

### Additional Information

No devs that I know of even knew this was a thing - https://developer.android.com/training/articles/security-config

**Comment by zzebrum** [comment]
@Cybo1927 hi! Can you elaborate on your idea a little bit more? Not quite understand why we should have an article about it.

**Comment by Cybo1927** [comment]
What I mean by this is that there might be developers out there who don't know about the network security configuration file and even if they do they might not know how to allow AdGuard to use further (HTTPs) filtering. I was suggesting that you guys make a wiki that explains this and gives a real world/useable example of allowing AdGuard to do said further filtering

**Comment by zzebrum** [comment]
@Cybo1927 our knowledge base is not that popular :) and all info about certificates is present in android dev guides.
