### ISSUE TITLE
Add a shortcut to the option "Report website issue" 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3609]
Currently it is not very clear where users can report website issues. 

First, they have to click "Support" then "Send feedback" then choose one of the options and then report the website. This is not the correct UX flow I think because without reporting websites that users are having trouble with AdGuard (or for that matter any adblocker) is as good as useless (at least that's what I have experienced) as I think the option is currently feels a bit hidden. It should very clear and apparent, at a glance, that users can report the website. For which, a "Report website issue" button just like AdGuard desktop extension would be extremely useful.

Event after clicking the "Support" option it isn't clear that users can report website issues by clicking "Send feedback" option nor does its description make it clear that is the case.

**Comment by artemiv4nov** [comment]
Well, this UI solution has been reworked in the v4.0, please try the new version.
