### ISSUE TITLE
AdGuard VPN service runs in background even if I don't use the AdGuard VPN actively

### ISSUE THREAD

**Issue by Neon329** [AdguardTeam/AdguardForAndroid#3610]
![Screenshot_20200930_202629](https://user-images.githubusercontent.com/70356738/94702783-c6f84a00-035b-11eb-8418-b852ccf7f353.jpg)
### Issue Details

- **AdGuard version:**
  -  Version 3.5.63
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Motorola One Power
- **Operating system and version:** 
  -  Android 10
- **Root access:**
  -  No

**Comment by admitrevskiy** [comment]
@Neon329 Hi! This service is required for 'Compatibility with AdGuard mode'
