### ISSUE TITLE
In the "App management" screen display the actual data consumption of the device in addition to the existing "Total data" and "Data saved" indicators

### ISSUE THREAD

**Issue by Neon329** [AdguardTeam/AdguardForAndroid#3611]
This is an extension to the existing issue I created https://github.com/AdguardTeam/AdguardForAndroid/issues/3590

I also did make some additional comments after the response I received to convince the developers but I think I was ignored as I didn't get any response even after a week of waiting, so I deleted that comment.

I'm saying it again the "App management" screens data consumption reports are confusing to no end to me. It isn't clear what it is about to me as a general user. But if you still insist on that it is a good UX decision then I won't speak anymore. I'm just suggesting an option here, a sort of a middle ground if I may say.

**Comment by zzebrum** [comment]
@Neon329 well, most probably the app will receive a new design, so your issue won't be relevant by that time
