### ISSUE TITLE
When the limit of the number of allowed devices for AdGuard Premium is reached, let the users see the list of connected devices and let them reset them without going to the website

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3612]
The title. Its very inconvenient to go to the website reet the connected devices. It'll be great if  I can reset the devices in the app itself without ever going to the website. Going to the website and disconnecting the device feels a bit disconnected to me.

**Comment by zzebrum** [comment]
This feature seems to narrow. The vast majority of users will never face this problem, and implementing this feature would take a lot of time and resources from our side.
I'm closing this issue for now, if ever this becomes a popular request and a real problem, we will reopen it or create a new, similar issue.
