### ISSUE TITLE
[UX] move the "Discuss" button out from "Support" to the "About" screen

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3614]
I think it doesn't make sense to include that in the "Discuss" option in the "Support" tab. Community cannot provide the same level of support like the official AdGuard support. 

I meat the "Discuss" button has its discription as "Share you opinion with other users" so by this I'm making my point very clear that it doesn't belong there.

**Comment by zzebrum** [comment]
I'll pass your suggestion to the devs, but as I said there may be a lot of changes with the new design.
