### ISSUE TITLE
Consider moving to using a bottom navigation bar instead of using a hamburger side bar menu

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3615]
Google is moving Android towers gesture navigation so it makes a lot of sense to move to using a bottom navigation in AdGuard as well. Side bars are relatively harder to use with Android 10's gesture navigation, to be really honest. 

Google itself still seems to have stuck to using side bar menus in some of their apps like Play Store or Google Drive for example but they and a lot of apps I use have largely moved to using a bottom navigation bar. It's like I have almost forgotten side bar menus in apps now. I want AdGuard to follow the same if possible.

**Comment by zzebrum** [comment]
Yep, most probably the new design will be like you suggest.  :)
