### ISSUE TITLE
No Filtering on URLs with German Umlaut

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3616]
@Berovowilare commented on [Mon Sep 28 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64751)

Hello 

Since a few years German Umlauts are possible for URLs. But your AdGuard doesn't filter it. Nor I can send a report over the normal way. It writes: The URL you entered is invalid or can't be parsed. You can submit your report manually here. And the URL is https://xn--zrimech-n2a.ch/. You see the ü in Züri missing .

The URL is https://zürimech.ch See the ü in Züri. 

---

@krystian3w commented on [Tue Sep 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64751#issuecomment-700529891)

> You see the ü in Züri missing

converted to Punycode: https://en.wikipedia.org/wiki/Punycode / https://de.wikipedia.org/wiki/Punycode

for domain names you can't use punycode?

`xn--zrimech-n2a.ch##someting`

`||xn--zrimech-n2a.ch/someting$image`

---

or some like this is also broken:

`/ü|Ü/$all`

filter should block any `ü` converted to "`%C3%BC`" / "`%C3%9C`" itself:

https://stackoverflow.com/questions/23009232/php-translating-c3bc-to-ü
https://de.wikipedia.org/wiki/ü
https://de.wikipedia.org/wiki/Ü

---

@BlazDT commented on [Wed Sep 30 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64751#issuecomment-701565728)

Working fine using xn--zrimech-n2a.ch
Not a filters issue anyway.

AdGuard should autocorrect rules imho.

**Comment by BlazDT** [comment]
First solution would be likely to improve compiler and then die every product it should rewrite/support unicode rules

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #1353](https://github.com/AdguardTeam/CoreLibs/issues/1353) via [**ZenHub**](https://www.zenhub.com/)
