### ISSUE TITLE
If I use AdGuard VPN with AdGuard Adblocker, only IPv6 changes.

### ISSUE THREAD

**Issue by Richelieu4771** [AdguardTeam/AdguardForAndroid#3620]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version: 3.5.1**
  - 
- **Filtering mode: Local VPN**
  - 
- **Device:Galaxy S10 5G**
  - 
- **Operating system and version:Android 10**
  - 
- **Root access:No**
  - 

### Expected Behavior
If Adguard VPN is applied to a different country, IPv4 and IPv6 must be changed together.

### Actual Behavior
Only IPv6 will be changed.

### Screenshots
![20201003_023834430](https://user-images.githubusercontent.com/68171816/94953082-ea6cf180-0521-11eb-8813-e4282cef1fcf.png)

<details><summary>Screenshot:You can see that IPv6 was changed to an overseas server for Adguard VPN, but IPv4 was not changed to IP 223.38 given by the Korean ISP "SKT".</summary>

</details>

### Additional Information
I simply found a way to change IPv4 temporarily! Turn on "pref.vpn.ipv6.disable" in the AdGuard Low Level setting. When enabled, IPv6 is blocked and IPv4 is changed.

**Comment by zzebrum** [comment]
@Richelieu4771 please, follow these steps:

1. change logging level in Advanced settings to  Record everything
2. reproduce the problem. Please also check IPs on a different site, e.g. https://ipleak.net/
3. export logs (also in Advanced settings) and send it to devteam[at]adguard[dot]com

**Comment by zzebrum** [comment]
@Richelieu4771 got your logs. thank you! We will take a look at it.

**Comment by zzebrum** [comment]
Devs suggested waiting until the next AdGuard VPN version is out, please, reopen if the problem won't be fixed.
