### ISSUE TITLE
sales.scanngo.atbapp - app is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3622]
@adguard-bot commented on [Fri Oct 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64927)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=sales.scanngo.atbapp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dsales.scanngo.atbapp)
### Comment
> Если в настройках Adguard отключить фильтрацию - всё работает.
> Для приложения стоит отключить фильтрацию по умолчанию так как оно без рекламі по умолчанию.
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/mjV4oEY.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/2XXsyoo.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.5
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads

---

@Sergey-Lyapin commented on [Fri Oct 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64927#issuecomment-702874413)

@Alex-302 посмотри, пожалуйста, у себя, оно недоступно в России

**Comment by Alex-302** [comment]
Reprodued. Exclusions do not help, only disable filtering of this app.

**Comment by Alex-302** [comment]
Logs:
[sales.scanngo.atbapp.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/5339933/sales.scanngo.atbapp.zip)

1. My usual settings - app is not working;
2. Disabled filters and DNS filtering - app is not working;
3. Disabled filtering for this app - app is working.

**Comment by TheHasagi** [comment]
The issue is fixed, changes will be available in the nearest update.
