### ISSUE TITLE
preferences window event hide 

### ISSUE THREAD

**Issue by kasv6** [AdguardTeam/AdguardForAndroid#3623]
### Prerequisites
Installed app redquits easy to use for quit last opened windows and close apps automatically
http://www.carsten-mielke.com/redquits.html

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Expected Behavior

When I use adguard preferences windows, it allows only the close event.
But the close event of last opened windows for the app is used by red quits to close automatically the app! Is a feature!

### Actual Behavior

The Close event of any last window is closing adguard app completely by using red quits app.

Improving:  
Please implement the hide event instead of only close event  to hide the window (preferences or other sub windows in the adguard app)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardForMac #752](https://github.com/AdguardTeam/AdguardForMac/issues/752) via [**ZenHub**](https://www.zenhub.com/)
