### ISSUE TITLE
Can't Block Youtube App Ads Even in Adguard v4.0.24

### ISSUE THREAD

**Issue by stralpt2** [AdguardTeam/AdguardForAndroid#3625]
I left adguard many months ago and i came back and hopefully my dream are becoming true,but till now i don't see any different on adguard and still can't block Youtube App Ads, i think it should be up voted request come on adguard team you can made this 👍👍.

**Comment by zzebrum** [comment]
Unfortunately, the situation has not changed. Nobody can block ads in the youtube app unless you use a patched youtube app. You can still watch youtube in a browser.
