### ISSUE TITLE
Disable AMP isn't working for reddit links on Google search

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3626]
# Steps to reproduce:

Have Disable AMP userscript enabled in AdGuard Extensions.

1. Search for "AdGuard Reddit" on Google search 

2. Click on one of the AMP search results leading to a Reddit post.

3. Observe that the Reddit page is served through Google AMP instead of the non-AMP version.

### Observations

Taking one of the Reddit search results; 

The browser loads this link: 

https://amp.reddit.com/r/apple/comments/8c9h7o/what_is_the_best_adblocker_right_now/

And,

if I just replace the `amp` in the address with `www`, like this: 

https://www.reddit.com/r/apple/comments/8c9h7o/what_is_the_best_adblocker_right_now/ it loads normal Reddit webpage.

If this issue is solved then it will also help avoid issue like these when using Disable AMP extension in AdGuard: https://github.com/AdguardTeam/CoreLibs/issues/1120.  
* AdGuard version: 3.5.65
* Chrome browser version: 86.0.4240.75

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/DisableAMP #35](https://github.com/AdguardTeam/DisableAMP/issues/35) via [**ZenHub**](https://www.zenhub.com/)
