### ISSUE TITLE
Google Play: ru.yota.android

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3629]
@adguard-bot commented on [Sun Oct 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64999)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=ru.yota.android&hl=ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.yota.android%26hl%3Dru)
### Comment
Username: @Spirys
> При включенном AdGuard невозможно обновить информацию о минутах и гб, остальные функции (пополнение, изменение условий, покупки) работают.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/KSWwPXN.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Gz7Te5f.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.5
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (180), <br/>Block Push API, <br/>Block Location API
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | -

**Comment by Alex-302** [comment]
У себя проверить не могу.

**Comment by TheHasagi** [comment]
@Spirys

Приложение Yota в целом обновляет информацию только если работает в мобильной сети, а можете отключить WiFi и с включенным AdGuard проверить еще раз?

**Comment by TheHasagi** [comment]
Closed. Should be reopened if needed.
