### ISSUE TITLE
Cannot create local VPN on Galaxy A50

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#3630]
### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.5.1 (65)
- **Filtering mode:**
  - Local VPN 
- **Device:**
  - Samsung Galaxy A50
- **Operating system and version:**
  - Android 10
  - Patch 01.09.20
  - Kernel 4.14.62-19243154
  - Build qp1a.190711.020.a505fnxxu5bth8
- **Root access:**
  - No

### Expected Behavior

A Local VPN is created

### Actual Behavior

Local VPN cannot be created

### Screenshots

![attachment](https://user-images.githubusercontent.com/1375223/95575403-f4fe1e00-0a2e-11eb-8cc0-dfe29f3257e0.jpg)

**Comment by admitrevskiy** [comment]
Hi! As I can see there is a dialog with tips how to fix this issue. Have you tried following the instructions?

**Comment by superlex** [comment]
Hello @admitrevskiy ,
suggested tips cannot be followed, the only possibile operation is click home button.

**Comment by TheHasagi** [comment]
@superlex 

Hello, what do you mean about "cannot be followed, the only possible operation is clicking the home button"? Can you try to do these steps described in our [knowledge base](https://kb.adguard.com/android/solving-problems/firefox-certificates)? Closed.  Should be reopened if needed.

**Comment by superlex** [comment]
Did you mean https://kb.adguard.com/en/android/solving-problems/restricted-profile ?

> "cannot be followed, the only possible operation is clicking the home button"

This is what user that has the issue told me. 
I suggested him the adb tips above, I'll update the issue if he has troubles following them.

Thanks :)
