### ISSUE TITLE
Missing ad in Podcast Addict app

### ISSUE THREAD

**Issue by Primokorn** [AdguardTeam/AdguardForAndroid#3631]
#3484 

Since it has been wrongly closed and nobody answers now.

**Comment by TheHasagi** [comment]
@Primokorn 

Hello!

Sorry for the late reply, yes the ad is back there I can confirm. The [root issue](https://github.com/AdguardTeam/AdguardFilters/issues/57724) is reopened.

<details>

![img](https://user-images.githubusercontent.com/37797229/95856235-60632b00-0d62-11eb-9bd2-8b0dead5a507.png)


</details>

**Comment by Alex-302** [comment]
@TheHasagi

**Comment by Alex-302** [comment]
@Primokorn Please read the message above.

**Comment by TheHasagi** [comment]
@Primokorn 

Hello, can you confirm that issue is no more with the latest release version?

**Comment by Primokorn** [comment]
@TheHasagi Still there. AdGuard v3.6. I give up.

**Comment by TheHasagi** [comment]
@Primokorn 

Looks like this is a built-in banner and can't be removed at all. For a better experience try to use up-to-date filters with AdGuard DNS.
