### ISSUE TITLE
Google Play: org.telegram.messenger

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3632]
@adguard-bot commented on [Thu Oct 08 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65287)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=org.telegram.messenger](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dorg.telegram.messenger)
### Comment
> Часто при включённом блокировщик рекламы телеграмм не может найти сеть. При чем уведомления о сообщениях приходят, а само сообщение в приложении  нет.
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/zMt9mEx.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/xrqTQzd.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android vv3.2.150 (1.4.138cl)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | Только 1 блокировщик. Без других приложений которые впн используют

**Comment by TheHasagi** [comment]
User should update AdGuard to the latest [release version.](https://agrd.io/apk) and check again. Closed for now, should be reopened if needed.
