### ISSUE TITLE
Android 11 -- moving cert to the system store does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3633]
See the report from `@ adzkii` in the Telegram chat.

There are two distinct issues with Android 11:

1. AdGuard's own cert moving procedure does not work at all
2. MoveCert kinda works and the cert is even shown in the "System store", but apps don't trust it for some reason

Magisk v21.0

One more affected user：https://t.me/AdGuard_chinese/14978

Might be caused by "Magisk hide" -- if we cannot reproduce this with the normal Magisk, we should try it with that module and see if it's feasible to fix this (or maybe it should be fixed on the side of Magisk hide?)

**Comment by admitrevskiy** [comment]
It looks like MagiskHide is the root of the problem. Disabling HTTPS filtering for applications that are affected by MagiskHide module (primarily for GMS since MagiskHide is enabled by default for it) solves the problem.
This is a temporary solution and we should think about how to improve it

**Comment by artemiv4nov** [comment]
Well, I will think the problem has gone.
