### ISSUE TITLE
URL Redirection

### ISSUE THREAD

**Issue by BlitW0** [AdguardTeam/AdguardForAndroid#3634]
### Problem Description

Add a way to redirect a URL to a different URL based on regex rules.

### Proposed Solution

No idea how it would work, but it might be separate section in settings since standard filter rules do not support URL redirection.

### Alternatives Considered

Tried to see if standard filters with ABP syntax can do this, but was not able to find anything.

**Comment by TheHasagi** [comment]
@BlitW0 

Hello! Can you explain with more details for what purposes do you need such a feature?

**Comment by zzebrum** [comment]
@BlitW0 any update?

**Comment by BlitW0** [comment]
My reason was for redirecting reddit's awful mobile website to the compact version or old reddit. It might also be useful for different sites in the same manner?

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #1364](https://github.com/AdguardTeam/CoreLibs/issues/1364) via [**ZenHub**](https://www.zenhub.com/)
