### ISSUE TITLE
Accept SSL Certificate of Upstream Proxy CA

### ISSUE THREAD

**Issue by AppliedEllipsis** [AdguardTeam/AdguardForAndroid#3635]
### Problem Description

When using ADGuard, I'd like to be able to use an upstream MITM proxy like charles, burp, fiddler, mitmproxy, OWASP Zed Attack Proxy (ZAP).

I already have my CA installed in Android Root, and works great, but if I upstream it with Adguard, it doesn't accept the connections. I can't even test proxy with it and SSL interception enabled.

Without AdGuard, my MITM works fine.

I'm using my own CA setup with openssl and the android subject_hash_old and <= 730 day old stuff.

### Proposed Solution

AdGuard should trust the installed Root CA's, User CA's

or

AdGuard should have an ignore certificate issues (date, ca trust, dns, etc) checkbox

or

AdGuard should allow us to install our own CA Certs to be trusted by it.

**Comment by zzebrum** [comment]
@AppliedEllipsis by default AdGuard should trust such certificates.  Can you provide us with steps so we could reproduce the issue on our side? Also, we need to know what device and OS version do you use?

**Comment by zzebrum** [comment]
@AppliedEllipsis any update?

**Comment by zzebrum** [comment]
reopen if needed
