### ISSUE TITLE
Nimbus Note app sync issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#364]
[Nimbus Note](https://play.google.com/store/apps/details?id=com.bvblogic.nimbusnote)

Не работает синхронизация с облаком nimbus.everhelper.me
Установки Adguard стандартные, при включенном синхронизация зависает, при
отключении защиты проходит без проблем. Ошибок никаких не выдаёт.

HTTP лог тут: KSV-295-19691

- отключение фильтров не повлияло
- проблема выглядит так: зависает колесико при ручном обновлении, не работает синхронизация, если заметка создана на сервере (в телефоне после ручного или автообновления не появляется)
- помогает только отключение адг

**Comment by ameshkov** [comment]
@evgeniy-ADG помогает ли отключение фильтрации рекламы?

**Comment by Revertron** [comment]
@ameshkov Помогает отключение фильтрации рекламы, да.

**Comment by Revertron** [comment]
Added to ad_exceptions.

**Comment by ameshkov** [comment]
@Revertron давай лучше вычислим что лишнее блокируется.

@Alex-302 помоги пожалуйста.

**Comment by ameshkov** [comment]
А, туплю, отключение фильтров же не помогает.
