### ISSUE TITLE
Add an option to disable Quick Settings tile

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3643]
### Problem Description

User needs the ability to disable the quick settings tile from within the native Adguard android app. For parental supervision purpose, they need to prevent the phone users from disabling Adguard from a quick settings tile.

### Proposed Solution

Add an option to remove quick setting tiles from the app.

### Additional Information

Reported through forum: https://forum.adguard.com/index.php?threads/disable-quick-settings-tiles.40282/
and through helpdesk ticket 1564057

**Comment by moofawsaw** [comment]
Also would need the ability to disable the Adguard widget which has the same capability to disable the application as the quick tiles.

**Comment by I-G-1-1** [comment]
I'm also interested in the ability to disable the Quick Settings tile and the Adguard widget. Would be great to avoid anyone that doesn't have the password to access the app (blocked using the Xiaomi MIUI Secutiy system app) to disable AdGuard filters.

**Comment by artemiv4nov** [comment]
It looks like not so popular feature request. Closed.
