### ISSUE TITLE
Wifi calling does not work when AdGuard is enabled: Turkcell TR

### ISSUE THREAD

**Issue by denimguru** [AdguardTeam/AdguardForAndroid#3645]
**Issue Details**

    AdGuard version: v3.5.1 (65)
    Filtering mode: Local VPN
    Device: Xiaomi Redmi Note 9 Pro
    Operating system and version: Android 10 (MIUI 12.0.2)
    Root access: No

**Actual Behavior**

Recently I changed my phone from Huawei Mate 20 Lite to Xiaomi redmi Note 9 Pro. With Huawei I didn't have any issues with Wifi calling when Adguard is enabled. I imported my AdGuard settings from Huawei to Xiaomi.

Unfortunately with Xiaomi I have problems. When Adguard is enabled, the phone doesn't switch to VoWifi mode. When I disable Adguard, then it connects and I can make phone calls. But when enable AdGuard again (when VoWifi is active), I can't make any phone calls.

**Comment by Chinaski1** [comment]
Hello there!

To troubleshoot this issue, we need to get additional information.

Go to your phone Settings -> Network & Internet -> Mobile Network -> Advanced -> Access Point Names

I'm interested in the MCC and MNC values.

**Comment by denimguru** [comment]
Hello,

By searching similar posts in forums, I solved the problem.

In low-level settings, I add a new line to pref.ipv4.routes.excluded:
188.56.0.0/14 <https://bgpview.io/prefix/188.56.0.0/14>

Now VoWiFi works without any problems.

Best,

**Comment by denimguru** [comment]
Hello,

By searching similar posts in forum, I solved the problem.

In low-level settings, I add a new line to pref.ipv4.routes.excluded: 188.56.0.0/14

Now VoWiFi works without any problems.
