### ISSUE TITLE
Adding new tracking parameters to the list causes the function to break

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3647]
‹### Issue Details

- **AdGuard version:**
  -  4.0 nightly 6
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Samsung Galaxy S7 Edge
- **Operating system and version:**
  -  stock Android 8
- **Root access:**
  -  No

### Expected Behavior

 Tracking parameters should always be stripped when they're included in URLs that are filtered via https filtering and all necessary settings are turned on.

### Actual Behavior

 After updating to AdGuard 4.0 nightly 6 the issues #3561 & #3584 were fixed. However, I recently added a few more tracking parameters to my list. After applying those changes the tracking parameters are no longer stripped.

### Screenshots

<details><summary>Screenshot:</summary>

![TrackingParameters 2020-11-02_09-55-07](https://user-images.githubusercontent.com/29090831/97889092-d59f9b80-1d23-11eb-8fb4-d2ca109f9786.jpg)
![TrackingParameters 2020-11-02_09-55-27](https://user-images.githubusercontent.com/29090831/97889121-e18b5d80-1d23-11eb-81b6-fab31012f1dc.jpg)
![TrackingParameters 2020-11-02_09-55-49](https://user-images.githubusercontent.com/29090831/97889138-e51ee480-1d23-11eb-8f1f-4723d85bc6e0.jpg)

</details>

### Additional Information
I have application logs for this and will email them to the devteam.

**Comment by infinitewaveparticle** [comment]
p.s. I have also seen tracking parameters on youtube and linked news artickes no longer working. This is just one example. The functionality is completely broken; no parameters are stripped from any URLs whatsoever.

**Comment by TheHasagi** [comment]
@infinitewaveparticle 

Hello there, can you please specify the exact parameters you are using in tracking parameters? Also, does the issue exists in the latest [Nightly version?](https://agrd.io/android_nightly)

**Comment by TheHasagi** [comment]
Closed due to no response from a customer. Should be reopened if needed.

**Comment by infinitewaveparticle** [comment]
Yes it does. Here are the parameters:

utm_source utm_medium utm_term utm_content utm_campaign utm_referrer yclid gclid fbclid _openstat fb_action_ids fb_comment_id fb_action_types fb_ref fb_source action_object_map action_type_map action_ref_map autotags trx?id dateline ancestor_origins siteid yptr break guce_referrer reason metrics t withAds referrer _ uuid gcrumb ts adgroup destination referer src_bizid src_ref user_agent show_in_content_ads referrer customReferer ref_ ref

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
This issue is still very much alive for me... I am the same person who made the support request mentioned a few days ago in #3584
