### ISSUE TITLE
Missed ad or tracker: Samsung Weather

### ISSUE THREAD

**Issue by dmraymond** [AdguardTeam/AdguardForAndroid#3648]
- **AdGuard version:**
  - 3.5.1 (65)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung S10+
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

Rather than the ad the title message would be displayed. An ad is not always present.

### Actual Behavior

50% of the time an ad is placed at the top of the app.

### Screenshots

<details><summary>Screenshot: 
![Screenshot_20201103-091146_Weather](https://user-images.githubusercontent.com/12863807/98018227-28756380-1db5-11eb-9ace-715098feddcb.jpg)
</summary>

</details>

### Additional Information

Samsung Weather v1.6.24.50

**Comment by zzebrum** [comment]
@dmraymond sorry for the late reply! Which filters do you have enabled?

**Comment by dmraymond** [comment]
Just the default AdGuard ones.

AdGuard Base filer
AdGuard Mobile Ads filter
AdGuard Annoyances filter

**Comment by Ruslanrem** [comment]
@dmraymond Can you send a link to the app,  witch on your screen, in play store, please.

**Comment by Chinaski1** [comment]
Also, be advisable to enable the AdGuard DNS feature.

Please, specify did you try to clear the application's cache and open it again.
Will there be any advertising shown?

**Comment by Chinaski1** [comment]
I am closing this task because a week has passed since the last user message.
If necessary, re-open it.
