### ISSUE TITLE
Added UBO Custom filters into Adguard list but didn't work

### ISSUE THREAD

**Issue by automatorMaxima** [AdguardTeam/AdguardForAndroid#3650]
For example, using this link doesn't block the footer on the website when I use my default Huawei browser or the facebook built-in browser. Am I doing anything wrong?

https://pastebin.com/raw/vAdrQGaV

**Comment by Chinaski1** [comment]
Hello there!

I try to reproduce the issue using a specified filter and I can notice that the filter works as expected.

Do you add the filter you specify to AdBlocking -> Filters -> Custom filters?

**Comment by automatorMaxima** [comment]
Yes I did.


Regards,
Annabelle.

**Comment by Ruslanrem** [comment]
@automatorMaxima  try to update Adguard blocker from a Nightly channel (settings - general - updates - update channel - nightly). If the issue will stay, add screenshots of the problem, screenshots of your settings and added filters, please.

**Comment by Ruslanrem** [comment]
@automatorMaxima   did You try to update to the Adguard Nightly? Did issue stay?

**Comment by automatorMaxima** [comment]
Yes I did. Issue is persistent.


Regards,
Annabelle.

**Comment by Ruslanrem** [comment]
@automatorMaxima, ok, please collect debug level logs and send to support@adguard.com with the link to the issue
https://kb.adguard.com/en/android/solving-problems/log#debug

**Comment by zzebrum** [comment]
@automatorMaxima sorry, I can't find any email from you :( Can you please resent logs file to mg[at]adguard[dot]com
