### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by xiaozhou888** [AdguardTeam/AdguardForAndroid#3651]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by zzebrum** [comment]
@xiaozhou888 please, fill the form above to report an issue.
