### ISSUE TITLE
AdGuardForAndroid/iOS not blocking ads SnapChat

### ISSUE THREAD

**Issue by iAYMANi** [AdguardTeam/AdguardForAndroid#3653]
AdGuardForAndroid/iOS not blocking ads **SnapChat**

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  latest version
- **Filtering mode:**
  VPN
- **Device:**
Note 10+ / iPhone 12
- **Operating system and version:**
Android 10 / iOS 14
- **Root access:**
No

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by zzebrum** [comment]
s@iAYMANi please, use [the reporting tool](https://reports.adguard.com/ru/new_issue.html) to report about missed ads
You can find the reporting tool in android app here: `side menu - support - send feedback` and in iOS app: `settings - support - report incorrect blocking`
