### ISSUE TITLE
missing background app notifications

### ISSUE THREAD

**Issue by donestefan** [AdguardTeam/AdguardForAndroid#3657]
- **AdGuard version:**
  - v3.5.1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 4a
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Config

I use AdGuard mainly as a firewall to allow/block internet access for apps. Access to internet is blocked by default for all (new) apps. I depend on the notifications created by AdGuard to notify me about apps trying to access the internet, so I can choose to unblock them. This worked fine on my old Phone (Samsung S7 - Android 8) but is buggy on my new phone Pixel 4a.

### Expected Behavior

Notification comes up whenever an app causes a blocked connection (and adguard is set up accordingly).

### Actual Behavior

Notification only appears if the app making the connection is used in foreground. If it is used in the background there will be no notification (and also no log entry) about a blocked connection.

Examples:
- Playing a promo video in the google app store uses the youtube app for video playback. But the youtube app is not opened in foreground but embedded in the app store. AdGuard blocks all youtube app connections as configured, but does not log the connection and does not create a notification. 
When youtube app is opened as a regular foreground app, Adguard correctly logs and notifies about blocked connections.
When youtube app is allowed to access the internet then videos in both apps (youtube and play store) start to work.
- Firefox uses a separate process for file downloads. I allowed internet access for firefox and regular surfing works fine with this. But Downloads seem to be handled by a separate background process and do not work. Since I don't see this separate background process in the log/notification, I can not allow internet access to this process.

**Comment by Ruslanrem** [comment]
@donestefan, Hi, sorry for the late answer,
please collect debug level logs and send to support@adguard.com with the link to the issue
https://kb.adguard.com/en/android/solving-problems/log#debug

**Comment by Ruslanrem** [comment]
@donestefan, hello! Did you collect log files?

**Comment by Chinaski1** [comment]
Closing this task as the user has not responded for a long time.

**Comment by Chinaski1** [comment]
Also, I think you should check on version 3.6. which was released today.

**Comment by Birbber** [comment]
@anuraag488 We're preparing for 4.0 release where lots of functions will be reworked. There's a possibility it might affect notifications as well. So please wait for 4.0 and check the behavior.
