### ISSUE TITLE
Warn smartphone users about battery stats

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#366]
We have some complaints on the app battery usage caused by this:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/50/7/adguard-for-android-battery-and-traffic-consumption-issues

Nobody reads FAQ or looks for that KB article, it's easier to uninstall the app instead.
Important note: this issue is important for all those who use much cellular data.

There should be a way to gently warn user about that.

**UPD: use this text:**
Please note that when Adguard is on, battery and data usage statistics doesn’t present the real situation. Due to app filtering Android counts the other apps consumption as Adguard’s, which leads to overestimation of Adguard’s share and on the contrary - underestimation of other apps consumption rate.

**Button text:** Got it.

**We should show this only to smartphone users.**

**Comment by Revertron** [comment]
Maybe we could show some notification like "Did you know?" that will guide user to FAQ section?

**Comment by ameshkov** [comment]
thedicemaster on xda suggests to warn user when he starts protection for the first time.

We now show there a local VPN description dialog.
We could show this warning as a second step.

**Comment by ameshkov** [comment]
@vozersky could you please help us with the proper description?

This "pre-start" dialog is pretty small so the warning should also short and easy to understand.

**Comment by vozersky** [comment]
We could write something like:

Please note that Android battery and traffic consumption counters may become distorted due to the filtering. More details in this [https://kb.adguard.com/index.php?/Knowledgebase/Article/View/50/7/adguard-for-android-battery-and-traffic-consumption-issues](article)

**Comment by ameshkov** [comment]
There should be no links, just text.

**Comment by vozersky** [comment]
"Please note that Android battery and traffic consumption counters may become distorted due to the app filtering. It doesn't reflect the actual consumption values."

or shortened to 
"Android battery and traffic consumption counters may become distorted due to app filtering. It doesn't reflect the actual consumption values" 
That should fit

**Comment by ameshkov** [comment]
That's even too short:)

The main thing I'd like user to understand is that AG does not use as much battery as it is shown in Android stats. In fact its own usage is relatively small.

Something like:
Please note that when Adguard is turned on battery and traffic consumption shown in devices statistics **does not represent the facts**. The thing is, Android attributes all of the WiFi and Mobile traffic to Adguard, which was in fact consumed by other apps. Due to this, Adguards real share of total data and battery resource consumed increases, and other apps, on the contrary, decreases.

**Comment by vozersky** [comment]
Why don't you want to provide a link a kb article? Too much to read?

**Comment by ameshkov** [comment]
We will show this warning when user has already pushed the "start protection" button. Clicking this link will interrupt the process.

**Comment by TPS** [comment]
I guess this makes #176 perhaps somewhat more of a priority?

**Comment by ameshkov** [comment]
@TPS not really, we just want to tell users that what they see in battery stats is not exactly true.

In fact we're doing some testing on our side and it appears that Adguard actually improves battery usage.

**Comment by vozersky** [comment]
Could be like this:
Please note that when Adguard is on, battery and traffic consumption statistics doesn’t present the real situation. Due to app filtering Android counts the other apps consumption as Adguard’s, which leads to overestimation of Adguard’s share and on the contrary - underestimation of other apps consumption rate.

**Comment by ameshkov** [comment]
@TPS what do you think? Is this short explanation ok for casual user?

**Comment by TPS** [comment]
For the casual user, yes. It might be even better, whenever #123 lands & you claim that permission for screen overlays, to actually lay this out on the battery scren some way — maybe just as simple (I know, _not_ easy) as a ✳️ somewhere by AG's stats, to prompt folks to question that screen a little.

Of course, for nerds like _me_, I'd want more, but then I'd already be a β-tester & already been exposed to a detailed explanation — just like now! 😆

**Comment by ameshkov** [comment]
> actually lay this out on the battery screen some way

I must admin the idea is great, but Android won't allow us to detect what app is currently on the screen:(

**Comment by TPS** [comment]
Maybe if you directly call the battery stats page directly from _within_ an appropriate section of AG & then overlay.…  CleanMaster does something quite similar with great success.

**Comment by Revertron** [comment]
Done.

**Comment by ameshkov** [comment]
> Maybe if you directly call the battery stats page directly from within an appropriate section of AG & then overlay.… CleanMaster does something quite similar with great success.

But the only thing we want it to warn user, not replace the battery app for him:)

**Comment by TPS** [comment]
Replace?!  Nono, just suggesting to call up the page & overlay.  No replacing here!  😕

**Comment by ameshkov** [comment]
It's just easier to warn inside our app then.

> just suggesting to call up the page & overlay.

I understand of course. It's just not as good as placing a warning text when user navigates there on his own.

**Comment by TPS** [comment]
This is true, but it's the constraints you got.…  If AG has root, can it be done _then_?

**Comment by ameshkov** [comment]
> This is true, but it's the constraints you got.… If AG has root, can it be done then?

Possibly, but most of the users do not have root access.
