### ISSUE TITLE
Extensions settings are broken in v4.0 nightly 8

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#3661]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v4.0 nightly 8 (45)

 ho , lasted nightly extension area ui bug check screen 

![Screenshot_20201121-140020](https://user-images.githubusercontent.com/41585567/99882769-44855b80-2c23-11eb-9129-13aac7cb5546.jpg)
![Screenshot_20201121-140035](https://user-images.githubusercontent.com/41585567/99882772-46e7b580-2c23-11eb-8de4-e471cdf330b6.jpg)

**Comment by ameshkov** [comment]
Weird stuff

**Comment by MPThLee** [comment]
Ok, Do not reset to default. It will makes userscript unusable. Also adding new extension doesn't work too.

Video demo: https://streamable.com/of1aob
