### ISSUE TITLE
zArchiver app is missing in Apps Management and Logs

### ISSUE THREAD

**Issue by nullsurfer** [AdguardTeam/AdguardForAndroid#3662]
![Screenshot_20201121-232003](https://user-images.githubusercontent.com/67369340/99884731-5559bf80-2c6b-11eb-8a9b-48205874c813.png)

![Screenshot_20201122-023712](https://user-images.githubusercontent.com/67369340/99884772-a964a400-2c6b-11eb-93fd-445a0d1f6b07.png)

![Screenshot_20201122-023618](https://user-images.githubusercontent.com/67369340/99884779-b5e8fc80-2c6b-11eb-886d-d7b73bd4f7db.png)

It's not just me either. I tried in another phone and same thing happens: zArchiver is also absent in Apps Management and and Logs. Makes me wonder if AdGuard is hardcoded to ignore zArchiver.

**Comment by Disqu3-mirOir-qt** [comment]
hi , it,s not a bug because zarchiver not need / permission  internet for work ,
