### ISSUE TITLE
add an option to disable AdGuard VPN for the chosen app in integration mode

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardForAndroid#3667]
add option to disable AdGuard VPN without having to disable AdGuard ad blocking in support mode with AdGuard

**Comment by Ruslanrem** [comment]
@eduardoaddad hi, by support mode you mean integrated mode?

**Comment by eduardoaddad** [comment]
> @eduardoaddad hi, by support mode you mean integrated mode?

Yes

**Comment by Ruslanrem** [comment]
@eduardoaddad you dont have to disable AdGuard ad blocking. If you disable only AdGuard VPN, Adguard ad blocker would still turned on and works.

**Comment by eduardoaddad** [comment]
You cannot disable an application without turning off VPN or AdGuard protection

(If I want to disable VPN for Facebook, I’ll need to disable AdGuard protection for the app to disable VPN)

**Comment by artemiv4nov** [comment]
This task has been implemented in the 4.0 version, please follow updates.
