### ISSUE TITLE
Give a user configure Firewall pre-settings for all new installed applications

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#3668]
Добрый день.

Можно ли попросить в Adguard под Андроид сделать отдельно вот такое же как прикрепленном скриншоте меню с firewall pre-settings, которые будут применяться по умолчанию ко всем новым устанавливаемым приложениям. В данный момент Adguard по умолчанию применяет pre-settings, которые нельзя изменить для новых приложений, кроме как зайди после установки приложения в настройки firewall и поменять вручную. А хотелось бы избавить себя от необходимости каждый раз после установки заходить и что-то менять вручную, хотелось бы один раз в самом начале определить политику доступов для новых приложений и после этого давать новым приложениям доступы вручную только в случае особой необходимости. Заранее благодарю.

https://i114.fastpic.ru/big/2020/1129/23/9ba2d98bf8777a9bdb4e783477d99e23.jpg

Operating system: Android 8
AdGuard version: Version 3.5.2 (66)
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter

**Comment by artemiv4nov** [comment]
That's interesting feature request. Let's see how many likes it will gain.

**Comment by artemiv4nov** [comment]
In the current version, we already have general Firewall settings which used for all and newly installed applications. Please try it.
