### ISSUE TITLE
[Android] Unbinded device still keep license until manual refresh

### ISSUE THREAD

**Issue by ictnmd** [AdguardTeam/AdguardForAndroid#3670]
### Issue Details
- **AdGuard version:**
  - Lastest from website (30/11/2020)
- **Device:**
  - Redmi Note 7 Pro
- **Operating system and version:**
  - MIUI 11.2/ Android 10
- **Root access:**
  - Yes

### Expected Behavior

Auto-refresh licence

### Actual Behavior

No auto-refresh licence information when unbind a device. The device continues using normally (can disable/ enable filter, restart app and restart OS).

**Comment by ictnmd** [comment]
The check-for-update button is also don't update the lisence information

**Comment by Ruslanrem** [comment]
@ictnmd please, collect debug level logs and send to support@adguard.com with the link to the issue
https://kb.adguard.com/en/android/solving-problems/log#debug

**Comment by zzebrum** [comment]
@ictnmd background license check happens every 6 hours, so the described behavior is normal. To update license status use the "Refresh license status" button on the License settings screen.
