### ISSUE TITLE
log android adguard

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#3671]
- [x] I am running the latest version: v4.0 Nightly 9 (48)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been fil

os-system: api 27
device: Huawei mate 10 mate lite

log filter android show only domain / http /stealh mode and some others rules , 

my featured request it,s posible to see (dom) html rules example##.adguard / ##a[href*="adguard.com"] ... and scriptplet injection too #%#//scriptplet'(prevent-bab') same behavior browser extension 

thanks you
![screen](https://user-images.githubusercontent.com/41585567/100625600-07a51d00-3325-11eb-913a-158ec7f670d9.jpg)

**Comment by ameshkov** [comment]
Dup of https://github.com/AdguardTeam/CoreLibs/issues/180
