### ISSUE TITLE
Youtube share crashes when you press the play button before the video's actually loaded

### ISSUE THREAD

**Issue by JazunOwO** [AdguardTeam/AdguardForAndroid#3672]

**Comment by Ruslanrem** [comment]
@JazunOwO Hi , can you tell your version of Android, phone model, version of Adguard, and a short clip with reproduction of the problem please?

**Comment by JazunOwO** [comment]
> @JazunOwO Hi , can you tell your version of Android, phone model, version of Adguard, and a short clip with reproduction of the problem please?

@Ruslanrem  
Android Version: 10
Model: SM-J600FN
Adguard Version: v3.6 beta 1
Youtube video link: https://youtu.be/QR6NHkFoAZs

**Comment by Ruslanrem** [comment]
@JazunOwO, unfortunately, the problem doesn't reproduce, please, collect debug level logs and send to support@adguard.com with the link to the issue
https://kb.adguard.com/en/android/solving-problems/log#debug

**Comment by JazunOwO** [comment]
@Ruslanrem I did it using the "Send Feedback" button and sent the debug logs after setting it to everything, reproducing the bug and then setting it to default and I included the link

**Comment by zzebrum** [comment]
@JazunOwO can you tell support ticket id then?

**Comment by JazunOwO** [comment]
I got the auto reply email 3 days ago and the ID was 3057501

**Comment by akmLaVx** [comment]
Customer has sent the logs.
Ticket id: 3057501
