### ISSUE TITLE
AdGuard does not recognise "!#if" negations

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#3674]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (4.0 Nightly 9)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0 Nightly 9
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Motorola One Zoom
- **Operating system and version:**
  - Android 10 (QPHS30.29-Q3-28-13-2)
- **Root access:**
  - No

### Expected Behavior

`!#if !adguard_app_android` and `!#if !adguard` are recognised by AdGuard for Android.

### Actual Behavior

I appear to have found a huge problem: `!#if !adguard_app_android` and `!#if !adguard` are not actually recognised by AdGuard for Android, leading to the potential for severe page breakage.

Reproduceable with this setup:
1) Add https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/AdGuardAndroidIfTest.txt as a custom list.
2) Visit `google.no` and/or `google.dk`
3) Open up AdGuard's logger.
4) See that AdGuard still blocked things from those sites.

### Screenshots

Sadly I don't think this can be shown in a screenshot.

### Additional Information

Nothing that feels appropriate for the situation.

**Comment by sfionov** [comment]
Adguard doesn't support applying these directives directly on device, and usually compiles filters server-side. But there is work in progress on filters downloader that will apply these directives during filter update:
https://github.com/AdguardTeam/CoreLibs/issues/1358
