### ISSUE TITLE
Android 11 - App Gmail: no mail receipt and dispatch with strato servers when Adguard is active

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3679]
@RastoDE commented on [Mon Nov 30 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68937)

Hello,
I have a problem with the Gmail-App (Google) on Android 11.
With gmail-account no problems to receive and send mails.

But I use the Gmail-App also for mails of my own domains (on provider Strato). These accounts are using the Server imap.strato.de and Port 993 and SSL/TLS for receiving and Server smtp.strato.de and Port 465 and SSL/TLS for sending.
What could I do, that I Adguard can stay active while using the strato servers?

---

@Alex-302 commented on [Wed Dec 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68937#issuecomment-737206484)

Could you please check with disabled filters and DNS filtering, but with enabled protection?
What status of HTTPS filtering for this app?(in Apps Managenent)

---

@RastoDE commented on [Wed Dec 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/68937#issuecomment-737332151)

With disabled filters and DNS and also with disabled HTTPS (normally activated) I can't reveice/send mails.

**Comment by Alex-302** [comment]
@RastoDE 
Please collect debug logs https://kb.adguard.com/en/android/solving-problems/log#debug
and send to support@adguard.com and write ticket ID here.

**Comment by zzebrum** [comment]
@RastoDE any news?

**Comment by RastoDE** [comment]
no news, I have uninstalled Adguard. too many problems with mail and other apps.
a long time ago Adguard was really good. But now it just bothers and annoys.
please close this ticket.

**Comment by sfionov** [comment]
You may try to add whitelist network rules like 
||[2a01:238:20a:202:54f0::1103]^$network
||81.169.145.103^$network

Or add 81.169.145.103 prefs.ipv4.routes.excluded and 2a01:238:20a:202:54f0::1103 to prefs ipv6.routes.excluded advanced settings.

> a long time ago Adguard was really good.

There were no changes in traffic redirection code for years, but on some firmwares some apps may not work with Adguard. We can't cover any firmware built on this planet but we may try to solve the problem. So, to try to solve this, we need debug info (that includes logs and information about your device).

**Comment by Chinaski1** [comment]
@RastoDE 
Any news?

**Comment by Chinaski1** [comment]
I am closing this task because the user has not responded for a long time.

Reopen it in case the issue occurs again.

**Comment by Serega124** [comment]
Могу воспроизвести баг на AdGuard v3.6.8 Android 11
В приложении Gmail учетка Outlook

imap: outlook.office365.com:993 (TLS)
smtp: smtp.office365.com:587 (STARTTLS)

При выключенной DNS-фильтрации Gmail не может подключиться к серверу. После включения DNS-фильтрации все ок.
