### ISSUE TITLE
Enabled proxy is disabled on every AdGuard VPN update

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#3680]
### Prerequisites

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v4.0 nightly 9 (48)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Sony Xperia 1 II
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

When AdGuard and AdGuard VPN both are installed on device, and AdGuard is using some proxy, and AdGuard VPN updates AdGuard must not disable the proxy.

### Actual Behavior

I have AdGuard and AdGuard VPN (v1.0.1 pre-alpha 1 (265)) on my device.
My AdGuard is using proxy (Shadowsocks if that matter), I use AdGuard VPN rarely.
No integration is enabled.

When I update AdGuard VPN from Google Play AdGuard is disabling proxy, and thinks that it is working in integration mode (I suppose).
When I go to proxy settings I see disabled main switch. I enable it - it complains about integration to break, I confirm the dialog, and (I think it send me back in settings) I need to reenter proxy settings screen to enable it the second time.

**Comment by ameshkov** [comment]
IMO, when "integration mode" is explicitly disabled in AdGuard (or AdGuard VPN fwiw), this setting should be persisted and cannot be restored unless the user explicitly does that.

**Comment by infinitewaveparticle** [comment]
yes, i stopped updating the adguard vpn app for this very reason

**Comment by RalMay** [comment]
not only "AdGuard VPN updates AdGuard must not disable the proxy" but AG AB has to just respect the users settings (no matter if whilst updating or in daily use).
Pls see my comments here https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/113 for why.
