### ISSUE TITLE
jp.co.carview.minkara.minkara - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3683]
@adguard-bot commented on [Sat Dec 05 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69316)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=jp.co.carview.minkara.minkara](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Djp.co.carview.minkara.minkara)
### Comment
> ホーム画面は表示されますが、それ以外すべてのタブやページで通信ができません。
> 
> 全てのフィルターなどをオフにしてみましたが変わらず、保護を無効にした場合のみ通信ができます。

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Lgg3kbR.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/bAadMDi.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.5.2 (66)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> Fanboy Anti-Facebook List, <br/>AdGuard Tracking Protection, <br/>Fanboy's Anti-thirdparty Fonts, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion, <br/>AdGuard DNS
Custom filter subscriptions: |

**Comment by Alex-302** [comment]
Steps: 

<details><summary>1:</summary>

![image](https://user-images.githubusercontent.com/8361299/101528724-504d7d80-3998-11eb-826c-2fedd0aa5733.png)

</details>

<details><summary>2:</summary>

![image](https://user-images.githubusercontent.com/8361299/101528774-61968a00-3998-11eb-9af6-5f0877cb7b21.png)

</details>

<details><summary>3:</summary>

![image](https://user-images.githubusercontent.com/8361299/101528812-7115d300-3998-11eb-919e-840805e9dade.png)

</details>

<details><summary>Actual:</summary>

![image](https://user-images.githubusercontent.com/8361299/101528866-7ecb5880-3998-11eb-8062-5bbf7619a7d4.png)

</details>

<details><summary>Expected:</summary>

![image](https://user-images.githubusercontent.com/8361299/101528972-97d40980-3998-11eb-8587-0e4385d9db73.png)

</details>

**Comment by Ruslanrem** [comment]
Doesnt reproduce
