### ISSUE TITLE
Request multiplication 

### ISSUE THREAD

**Issue by fegranata** [AdguardTeam/AdguardForAndroid#3685]
We are seeing issues when AdGuard is blocking our ads and multiplying requests to our servers, in the tests we've, we saw 3 requests becoming 45 requests.
This is affecting our server load and affecting the end-user performance as well as it could lead to crashes of the app they are currently using.

We received multiple complaints from apps that use our platform for monetization and we also saw that the behavior is not only true to us but to other networks as well.

Here is the information on the test we did:
AdGuard version: 3.5.2
Filtering mode: Local VPN
Device: Samsung SM-G930FD
Operating system and version: Android 8.0
Root access: No
Expected Behavior:
The number of items in the filtering log is equal to the number of requests
Actual Behavior:
The number of items in the filtering log is greater than the number of requests

![image](https://user-images.githubusercontent.com/75787445/101776026-9fa6c180-3af0-11eb-9c19-594c2e233a57.png)

We would like to work together with AdGuard to solve this issue.

**Comment by Chinaski1** [comment]
@fegranata 

Hello there!
Please describe the steps to reproduce this situation so that we can try to reproduce it on our side.

**Comment by Chinaski1** [comment]
I am closing this task as no further information has been received.
