### ISSUE TITLE
BETA report: Important Sites getting blocked

### ISSUE THREAD

**Issue by Ronak-59** [AdguardTeam/AdguardForAndroid#3688]
### Prerequisites

- I am running the latest version
- I checked the documentation and found no answer
- I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6 Beta 1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy M31 8GB
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

1) Should be able to use OKTA SSO configured as subdomain.okta.com. After entering the credentials, OKTA should be able to complete authentication flow and redirect user back to Okta-Auth protected site.

2) Github should maintain logged-in state

### Actual Behavior

1) OKTA login page loads correctly as subdomain.okta.com but on entering the credentials, it again loads the login form. The loop goes on.

2) Github shows logged in user as logged-out. On clicking "Sign in" or visiting https://github.com/login manually, user is redirected to homepage and has logged out state.

### Additional Information

- Was able to fix OKTA Error by entering following rules:
1) `@@||login.okta.com^$domain=login.okta.com`

- Github site was able to load my logged-in state and maintain it after I added following unblock rules:

1) `github.com$@$link[rel="manifest"]`
2) `@@||github.com^`
3) `||collector.githubapp.com^`
4) `@@||github.com^$domain=github.co,important`

That being said, I've been facing authentication related issues on several other sites.

**Comment by Chinaski1** [comment]
Hello there! @Ronak-59 

Please clarify if you have the Stealth-mode settings enabled? 
If so, try disabling it and checking again.
Also, you can try to use the ```@@||*.okta.com^$important``` rule.

**Comment by Ronak-59** [comment]
@Chinaski1 

Yes, I've set **Stealth Mode** to **"Ultimate"** to protect identity and personal information from all trackers.

**Comment by Chinaski1** [comment]
It's true, the Ultimate level can cause some sites to work incorrectly.
If you want to maximize your privacy, you will have to sacrifice something :)
I close this task because this behavior of Stealth-mode settings is normal.
