### ISSUE TITLE
Unstable internet connection w/Shadowsocks

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3689]
### Issue Details

- **AdGuard version:**
  - 3.5.2
- **Filtering mode:**
  - Local VPN (outbound proxy to Shadowsocks)
- **Device:**
  - Samsung SM-G986W
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Actual Behavior

When connected to Shadowsocks and protection is enabled, connection suddenly becomes unstable.

### Screenshots

Not Applicable

### Additional Information

Helpdesk ticket ID & logs: 2452747

**Comment by sfionov** [comment]
Did user turn off filtering of Shadowsocks app in AdGuard?

**Comment by sfionov** [comment]
Ah, I see in forum thread that filtering is turned off.

**Comment by Chinaski1** [comment]
Also, according to the helpdesk ticket, it was about unstable filtering when app operating in proxy-mode.
We cannot guarantee that AdGuard will be as effective as possible in proxy mode.

**Comment by JeremyHaynes-devguy** [comment]
Wait... That's your best answer? It won't be as effective? There's effective and then there's broken. How about fix the problem??
