### ISSUE TITLE
Instagram and Adguard in Proxy+Auto mode with HTTPs filtering 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#369]
We have a complaint on some issues with instagram and SSL filtering:
http://forum.xda-developers.com/android/apps-games/adguard-ad-blocker-doesnt-require-root-t2958895/post65863898#post65863898

@gshumihin please test it

**Comment by gshumihin** [comment]
I cannot reproduce this issue. Tried both proxy modes and VPN. Everything loads fine. Tested with latest adguard alpha (2.5.39).
