### ISSUE TITLE
Drop HTTP/1.1 Instead HTTP/2.0

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#3690]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Adguard for android for update app / filters use HTTP/1.1 GET request

I purpose implemented/use support HTTP/2.0 instead HTTP/1.1

![screen02](https://user-images.githubusercontent.com/41585567/102018564-51065b00-3d6e-11eb-81e8-54c1d6191e0e.jpg)

**Comment by ameshkov** [comment]
It does not grant any advantages, only makes things harder to configure on the server- and client- side.
