### ISSUE TITLE
Encrypted DNS queries aren't sent through the Oubound Proxy configured in AdGuard for Android settings

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3692]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0 nightly 9 (4.0.48)
- **Filtering mode:**
  - Local VPN (Maybe both)
- **Device:**
  - any
- **Operating system and version:**
  - any supported
- **Root access:**
  - No

### Expected Behavior
Encrypted DNS requests (e.g. DoH or maybe DoT (I tested only DoH)) should be sent through a proxy includes compatible AdGuard VPN

### Actual Behavior
Requests won't be sent through proxy, so my IP address is exposed to DNS server because of them
I found this problem from logs on NextDNS

### Screenshots
<details><summary>Screenshot:</summary>
Nothing
</details>

### Additional Information
I'm sorry for my fluent Engrish

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1390](https://github.com/AdguardTeam/CoreLibs/issues/1390) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sfionov** [comment]
Reopening since it is not CoreLibs problem, and DnsLibs part of this is already done: https://github.com/AdguardTeam/DnsLibs/issues/78

**Comment by ameshkov** [comment]
Let's plan it on 4.1

**Comment by nicolassp** [comment]
Any news on this?

**Comment by Chinaski1** [comment]
Tentatively this issue will be fixed in release 4.0/4.1

**Comment by artemiv4nov** [comment]
In the v4.0 version, we introduce new functionality to redirect apps' traffic through outbound proxy. Please try it.
