### ISSUE TITLE
App is already up-to-date, but keeps asking for update

### ISSUE THREAD

**Issue by dora-0** [AdguardTeam/AdguardForAndroid#3693]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6
- **Filtering mode:**
  - Local VPN
- **Device:**
  - LG G7+ThinQ (LM-G710N)
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

- Update AdGuard to version v3.6.
- Run AdGuard and click the Update button on the top right.
- You will see a message telling you that AdGuard is up to date.

### Actual Behavior

- Update AdGuard to version v3.6.
- Run AdGuard and click the Update button on the top right.
- The current version is displayed as AdGuard 3.6 (0), and it says that it can be updated to AdGuard 3.6 (1). If I proceed with the update and try again, the same problem occurs.

### Screenshots

<details><summary>Screenshot:</summary>

![update](https://user-images.githubusercontent.com/55905774/102212601-d594dd00-3f18-11eb-80e9-a3b7b10586ba.png)

</details>

### Additional Information

None

**Comment by Chinaski1** [comment]
Hello there!
Sorry for the temporary inconvenience.
Now it fixed.
