### ISSUE TITLE
Some software advertisements are transmitted through ports. The ports are random. How to write the rules?

### ISSUE THREAD

**Issue by etjson** [AdguardTeam/AdguardForAndroid#3694]
Some software advertisements are transmitted through ports. The ports are random. How to write the rules?

For example, an APP, its advertisement is transmitted through the port, and the port range is between 10070-20070

So how to write blocking rules?

I hope the author can improve the port shielding!

**Comment by etjson** [comment]
现在我是通过这个方式来做的

先屏蔽这个APP的所有端口
*$network,app=com.xxx.app

然后只开放80和443保证软件正常运行
@@*:80$network,app=com.xxx.app
@@*:443$network,app=com.xxx.app

不过这样做发现流量日志中80和443的日志不显示域名了只显示了IP，那么我添加的域名拦截就不知道有没有生效
||xxxx.com^$app=com.xxx.app

希望后期可以有这种范围屏蔽IP的支持
*:[100-200]$network,app=com.xxx.app

并且还可以根据传输的内容进行屏蔽
*:[100-200]$network,app=com.xxx.app,raw=adjson

**Comment by ameshkov** [comment]
你好，你可以表示任何广告查询例子吗？

**Comment by etjson** [comment]
> 你好，你可以表示任何广告查询例子吗？

Sorry, the meaning expressed in Chinese may be wrong, it has been changed to English, I hope to take a look, thank you.

**Comment by etjson** [comment]
Now the advertisement of this APP is transmitted through the port, and the number of ports is too much. If I write a blocking rule per line and add it to adguard, an error will occur in adguard.

**Comment by ameshkov** [comment]
@etjson 

No worries, I understand the meaning. However, I'd still like to see some examples of these ad requests that use random ports.

**Comment by etjson** [comment]
> @etjson
> 
> No worries, I understand the meaning. However, I'd still like to see some examples of these ad requests that use random ports.

Sorry, the internally used APP cannot be made public and can only describe the advertising situation, so I would like to ask how to write the blocking rules.

So what other information do I need to provide about this advertisement?

**Comment by ameshkov** [comment]
@etjson you can replace the hostname/IP address in the URLs with some random info.

I just need to understand what kind of requests AdGuard is able to see.
It may be connections to IP addresses, or it may be different hostnames, for instance.

**Comment by etjson** [comment]
> @etjson you can replace the hostname/IP address in the URLs with some random info.
> 
> I just need to understand what kind of requests AdGuard is able to see.
> It may be connections to IP addresses, or it may be different hostnames, for instance.

In the traffic log, it is shown that it is a TCP connection, and each request has a different IP and a different port.

**Comment by etjson** [comment]
I tried to write the 65535 line of port blocking rules, and then deleted the ones I wanted not to block, but too many lines caused adguard to crash without responding.

**Comment by etjson** [comment]
So now it's poorly supporting range port shielding.

I hope the author will support as soon as possible ~ Many thanks

**Comment by ameshkov** [comment]
> In the traffic log, it is shown that it is a TCP connection, and each request has a different IP and a different port.

You could try using regular expressions then.

Somethign like this for instance:
`/.+:[1-3][0-9]{2,5}/$network`

**Comment by ameshkov** [comment]
Oh, my bad, it seems they won't work, only wildcards are supported for $network rules.

Quick question: why don't you want to block the whole IP addresses?

**Comment by etjson** [comment]
IP is a CDN node, there are a few hundred in total, it is not easy to block.

**Comment by etjson** [comment]
If you support this kind of rule, it's really great.
/.+:[1-3][0-9]{2,5}/$network

Can you consider supporting this?

**Comment by etjson** [comment]
> Oh, my bad, it seems they won't work, only wildcards are supported for $network rules.
> 
> Quick question: why don't you want to block the whole IP addresses?

IP is a CDN node, there are a few hundred in total, it is not easy to block.

**Comment by ameshkov** [comment]
@sxgunchenko would it be hard to add full regex support for $network rules? Or are they processed differently from other types?

**Comment by sxgunchenko** [comment]
> Or are they processed differently from other types?

Yup, the $network rules matching mechanism differs from other ones.

> would it be hard to add full regex support for $network rules? 

It seems like it wouldn't be hard to support regex

**Comment by ameshkov** [comment]
@sxgunchenko will you file an issue in the CoreLibs repo so that we could close this one?

**Comment by sxgunchenko** [comment]
done

**Comment by etjson** [comment]
@sxgunchenko @ameshkov 
What is the situation now? Will the Android version support this regex writing in the future?

**Comment by TPS** [comment]
@etjson I'm reasonably sure @sxgunchenko just means they opened https://github.com/AdguardTeam/CoreLibs/issues/1394 (where everyone should _continue_ this discussion) to track developing this RFE in the correct segment of the product.

**Comment by sxgunchenko** [comment]
@TPS you are absolutely right, thank you

@etjson for now, unfortunately, there are no options to make a $network rule matching several ports (except a rule without port which matches any port)
