### ISSUE TITLE
Add double tap to skip 10 seconds feature to YouTube Player

### ISSUE THREAD

**Issue by errorsxp** [AdguardTeam/AdguardForAndroid#3696]
When you press share and watch a YouTube video through AdGuard it should let you be able to skip like the YouTube app, it only lets you use the progress bar to skip, which can be annoying for trying to get to a precise part of the video.

I'm not sure if it would be hard or not but the ideal solution would be to add the double tap to skip 10 seconds feature from YouTube to the AdGuard player.

It would also be nice to set the skip time from like 5, 10, or 30.

**Comment by Chinaski1** [comment]
Hello there!
Probably we will add this feature in the next updates.

**Comment by Chinaski1** [comment]
Regarding these tasks:
- https://github.com/AdguardTeam/AdguardForAndroid/issues/3698
- https://github.com/AdguardTeam/AdguardForAndroid/issues/3699
Features that you propose to add would be really useful. But at the moment we are using a method that opens Youtube in WebView. And this launch option is slightly limited in the interface. So we are unlikely to be able to add anything like that at this stage.

**Comment by oldip** [comment]
i think this is done now? maybe can close?
