### ISSUE TITLE
Video title on AdGuard YouTube share wont disappear 

### ISSUE THREAD

**Issue by rtsaab** [AdguardTeam/AdguardForAndroid#3697]
I am using the latest version (3.6) with the PlayStore YouTube application and I don't think all the other details are needed for this.

### Expected Behavior
The title should disappear since it covers the top part of the video, cutting it off.

### Actual Behavior
The title of the video stays and doesn't disappear, covering up the top part of it. 

For a screenshot I think the issue is easy enough to understand without one, but if needed I will edit this.

It would be nice if the title would disappear as the normal information does if you tap the screen or leave it alone for like three seconds.

**Comment by zzebrum** [comment]
@rtsaab you need to tap on the full-screen button at the right bottom corner to hide the title.

**Comment by rtsaab** [comment]
You need to tap on the full-screen button at the right bottom corner to hide the title.

I think I encountered a bug, since I did press full screen. I will try to reproduce it again but it seems to work fine after clearing cache.
