### ISSUE TITLE
Adguard considers server certificate invalid when server certificate chain is unsorted

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#370]
For instance, startcom certificate is used instead of Adguard's at meduza.io website

<img src="https://cloud.githubusercontent.com/assets/8577547/13812223/f74ee340-eb8b-11e5-884f-ceed38f76c44.png" width="400">

**Comment by ameshkov** [comment]
**Problem:**
1. meduza.io serves unsorted certificates chain (in fact not just unsorted, one of certificates in the chain is redundant).
2. AG tried to verify that chain and considered it invalid

We now sort the chain before verifying it.
