### ISSUE TITLE
Сломалось автообновление фильтров!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#3702]
- **AdGuard version:** 3.5.2(66)
  - 
- **Filtering mode:** local vpn
  - 
- **Device:** Asus zenpad 3 s10
  - 
- **Operating system and version:** Android 7.0
  - 
- **Root access:** no
  - 

### Expected Behavior
Ожидаю,чтобы автообновлялось соглсно настройкам-раз в сутки!

### Actual Behavior
После обновления с предыдущей версии(3.5.1),перестали автообновляться фильтры.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20201219-023631](https://user-images.githubusercontent.com/34476664/102675722-1b64d600-41a3-11eb-8a20-85746d6df341.jpg)

</details>

### Additional Information
Вот было всё хорошо после нашего разговора:исправили у себя на серверах, а теперь "наша песня хороша,начинаем всё с начала"  снова накуралесили! Стыдно,товарищи!😐

**Comment by Chinaski1** [comment]
Приветствую, @Spok1 

У настройки "автообновление фильтров"  есть интересная особенность.
Если телефон активен, обновление не происходит и цикл обнуляется.
Тем самым мы защищаем пользователей от обрыва соединения (при обновлении фильтров происходит рестарт защиты).
В общем обновление происходит в тот момент, когда телефон в сети, но экран выключен.

Для диагностики и решения Вашей проблемы, нам понадобятся логи приложения AdGuard.
Если автоматическое обновление все еще не происходит, тогда хотел бы попросить вас собрать и отправить указанные файлы, используя данную инструкцию:

1. Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
2. Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Дополнительно запишите [системный лог](https://developer.android.com/studio/debug/bug-report);
4. Отправьте оба файла по адресу `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by Spok1** [comment]
> В общем обновление происходит в тот момент, когда телефон в сети, но экран выключен.

Это что получается, нужно сутки в выключенным экраном сидеть в надежже на обновление? Дела... Раньше обновление проходили в свой цикл и не важно был разрыв или не был-соединение тот час же восстанавливалось. Вечно у вас отговорки на этот счет! Вам следует воспользоваться золотым правилом -"работает-не трогай", и не строить пряничный домик каждый раз. Вот что вы мне предлагаете на данный момент? Сидеть сутки с выключенным экраном?  Скажу,что в вашей теории есть изъяны,так как во первых: гаджет использовался продолжительное время с выключенным экраном и за это время обновление не произолшо,ровно как и со включенным,что делает вашу теорию несосоятельной.

**Comment by Chinaski1** [comment]
Нет, обновление произойдет спустя 5 минут после ухода экрана в сон. 
Если вы хотите, чтобы фильтры обновлялись чаще, вы всегда можете изменить ```период автообновления``` в настройках приложения (AdGuard -> Основные ->  Обновления).

**Comment by Spok1** [comment]
> Нет, обновление произойдет спустя 5 минут после ухода экрана в сон.

Короче, это всё миф и этого не происходит у меня! Отчёт я вам отослал—жду разбирательст!

**Comment by Spok1** [comment]
> Нет, обновление произойдет спустя 5 минут после ухода экрана в сон.

Короче, это всё миф и этого не происходит у меня! Отчёт я вам отослал—жду разбирательст!

**Comment by Spok1** [comment]
> Нет, обновление произойдет спустя 5 минут после ухода экрана в сон.

Короче, это всё миф и этого не происходит у меня! Отчёт я вам отослал—жду разбирательств!

**Comment by Chinaski1** [comment]
Вы не могли бы уточнить, вы отправили логи через приложение?
Или прямиком на ```devteam@adguard.com```

**Comment by Spok1** [comment]
> прямиком на `devteam@adguard.com`

**Comment by Chinaski1** [comment]
А после обновления 3.6.1 ситуация не изменилась?

**Comment by Spok1** [comment]
Нет

**Comment by Spok1** [comment]
Нет! И что ещё за надписи после времени <<ДП,ПП>> Мы не в США или Канаде находимся. Испрсвьте в соответствии с регионами и форматом относящимся к ним!

**Comment by Spok1** [comment]
Нет! И что ещё за надписи после времени <<ДП,ПП>> Мы не в США или Канаде находимся. Исправьте в соответствии с регионами и форматом относящимся к ним!

**Comment by Chinaski1** [comment]
А можно, пожалуйста, поточнее, где именно такой формат времени используется?

**Comment by Spok1** [comment]
В списке подписок.

**Comment by Chinaski1** [comment]
В данный момент мы работаем над релизом 4.0, который содержит массу кардинальных изменений. 
Не исключено, что будет переработан и механизм обновления фильтров.
Предлагаю дождаться релиза, и если проблема на версии 4.0. все еще будет сохраняться, мы откроем задачу повторно.
