### ISSUE TITLE
Unable to tap any links or menus on YouTube Player

### ISSUE THREAD

**Issue by errorsxp** [AdguardTeam/AdguardForAndroid#3704]
### Issue Details

- **AdGuard version:** 3.6
  
- **Filtering mode:** Local VPN
 
- **Device:** Samsung Galaxy 
  

- **Operating system and version:** Android 9
  
- **Root access:** No
  

### Expected Behavior

Should be able to tap on the play next video, open channel and other links that pop up in the share viewer.
### Actual Behavior

Doesn't let you interact at all with the links, it just treats them like there is nothing there.

### Screenshots
None of these links work.
![20201221_020722](https://user-images.githubusercontent.com/59858550/102749271-bb506a00-4331-11eb-92de-7e2d510e6060.jpg)
(Opened this video as an example, glitch is on all)

</details>

### Additional Information

I understand that this player is a barebones web viewer however I think it could be do-able to let the links act as another share to adguard type of thing and it will open that video in the player without leaving it also if it's not possible to add functionality to these, maybe hiding them would be best (again, if possible.)

**Comment by Versty** [comment]
@errorsxp Links are now clickable, we highly recommend to check this out in the AdGuard app!
