### ISSUE TITLE
Add QQ and UC browsers to the list of browsers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3707]
1. It can be downloaded here:
    * QQ browser: https://browser.qq.com/10.0/m/index.html
    * UC browser: https://uc.cn (please note, that you have to use Hong Kong VPN to access this website)
![image](https://user-images.githubusercontent.com/5947035/103151017-17304e00-478b-11eb-9770-53acbb09773a.png)

2. Check whether HTTPS filtering is supported in these browsers

**Comment by MaharnavS** [comment]
Same issue here but with a different browser. Mine is with either duckduckgo's stand alone browser app or with firefox lite.

**Comment by ameshkov** [comment]
@MaharnavS for Duckduckgo you may need to install the cert manually: https://kb.adguard.com/en/android/solving-problems/firefox-certificates

Regarding Firefox Lite, you may need root + moving the cert to the system store to make it work.

**Comment by MaharnavS** [comment]
> @MaharnavS for Duckduckgo you may need to install the cert manually: https://kb.adguard.com/en/android/solving-problems/firefox-certificates
> 
> Regarding Firefox Lite, you may need root + moving the cert to the system store to make it work.

Thank you. Will try it later. 👍
