### ISSUE TITLE
Убрать рекламу из блокировщика рекламы.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3708]
Здравствуйте.
Я конечно все понимаю, но это уже перебор.
Вы добавили рекламу внутрь блокиратора рекламы! Вы только вдумайтесь!!! Реклама внутри блокиратора рекламы!

Поясняю:
В меню настроек адгарда есть такой пункт "Adguard VPN".
Он то и есть по сути рекламой. И это раздражает. Причём серьёзно. Я заплатил за пожизненную лицензию в адгарде, чтобы созерцать ЭТО? Ладно, я бы купил бы и второй продукт. Тоже хорош, но система подписок меня не устраивает. К тому же есть куча сервисов (например тор или любой другой прокси (та хоть i2p)). Я сейчас о том, что пункт в настройка, предлагающий его скачать очень сильно раздражает.

Возможные решения проблемы:
1. Предложить скачать Adguard VPN в подсказках (один раз и ненавязчиво)
2. Добавить крестик к этому пункту, чтобы его можно было раз и навсегда убрать.
3. Вовсе убрать. Да да. Именно вовсе. Вы же писали, что приложения сделают все сами для бесшовной работы! Тогда зачем этот пункт? Раздражать?

Я вас очень прошу, уберите его либо спрячьте под настройки сети, так как я считаю что реклама (пусть даже и самореклама) внутри блокиратора рекламы недопустима.

Надеюсь на ваше понимание.

**Comment by Chinaski1** [comment]
Добрый день, уважаемый @ghost!

Спасибо за оставленный отзыв, мы обязательно подумаем над возможными решениями данной ситуации.
