### ISSUE TITLE
Incorrect Search Results in Filtering Log

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3709]
Test Scenario: Open the Filtering Log and search for 'ad'. The results included an entry which does not include the strings 'ad' in the Log Details page. Please fix.

Screenshot 1: https://ibb.co/zQVcT8Q
Screenshot 2: https://ibb.co/Y3kG8y0

**Comment by Nzzyme** [comment]
Hello. Anyone checking this please?

**Comment by Chinaski1** [comment]
Hello @Nzzyme 

Sorry for the late reply.
The search is also sensitive to package name information. 
You can see the list of packages if you tap on [Android OS](https://uploads.adguard.com/Chinaskip4d53.png).
Then tap on [technical information](https://uploads.adguard.com/Chinaskih1lug.png).
There are several names that contain ["ad"](https://uploads.adguard.com/Chinaskisgttb.png)
