### ISSUE TITLE
Dropbox app does not work when SSL filtering is turned on

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#371]
Here's log: https://www.dropbox.com/s/ggh9t5verfpxzws/dropbox.log

**Comment by Revertron** [comment]
The Dropbox app doesn't work with mitm attack. These domains added to exclusion list (https-whitelist):
api.dropbox.com
api-notify.dropbox.com
dropboxapi.com
dropboxusercontent.com

**Comment by evgeniy-ADG** [comment]
"versionName" : "2.6.23"
https filtering block dropbox auto sync via https. trying to open keepass, which auto pulls updated database, but it fails while adguard is on

Adding dropbox to the whitelist fixes issue.
Https issue only as far as i can tell, the dropbox app itself works fine
when keepass requests will not.
Disabling https filter fixed issue.
I added whitelist to both https and firewall.

**Comment by ameshkov** [comment]
So the issue is with Keepass sync through Dropbox.

**Comment by Revertron** [comment]
> Adding dropbox to the whitelist fixes issue.

Keepass somehow is connected to dropbox. Maybe we need to add full domain `dropbox.com`?

**Comment by ameshkov** [comment]
Agreed, however we should also test it.

@lity uses keepass, maybe he can help?

**Comment by Revertron** [comment]
@lity Is not using it with dropbox. But I've reloaded log from user - rechecking shows that there are only connections to dropbox domains without SNI. No keepass package names in the log.

**Comment by Revertron** [comment]
Okay, I've added these domains to exceptions:
dropbox.com
dropboxapi.com
dropboxusercontent.com

**Comment by Revertron** [comment]
We will wait some time for the users info.

**Comment by gshumihin** [comment]
No problems with dropbox for me since propbox domains were added to exceptions list. I think we should close this issue.
