### ISSUE TITLE
How to use with PowerTunnel?

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdguardForAndroid#3710]
To bypass DPI inspection, I downloaded [PowerTunnel](https://github.com/krlvm/PowerTunnel-Android) which also runs a local VPN so it cannot work side-by-side with Adguard. It has proxy mode, so I tried running it as proxy and set it as proxy in Adguard. But Adguard shows message "unable to connect to proxy". Where am I going wrong?

Default proxy for PowerTunnel runs at 127.0.0.1:8085.

**Comment by EntropySmoke** [comment]
You can't have 2 local VPN's.

**Comment by cantunborn** [comment]
But I'm running it in proxy mode, similar to how Adguard VPN works with Adguard Android using SOCKS proxy, so the 2 VPN restriction is not relevant.

**Comment by trmdi** [comment]
You can run Green Tunnel in termux, set Adguard to stop monitoring the network on Termux, and set Adguard to use the local proxy created by Green Tunnel.

**Comment by cantunborn** [comment]
Thanks! Your solution works. Instead of running anything in termux (which would be a hastle to setup), I whitelisted [PowerTunnel](https://github.com/krlvm/PowerTunnel-Android) in Adguard apps management and ran it in proxy mode. That solution worked perfectly and without the need to go on a terminal.

Closing this issue since it is solved.
