### ISSUE TITLE
Question: Why NXDomain for AdGuard AdBlocker and Null IP for AdGuard Home?

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardForAndroid#3713]
AdGuard AdBlocker uses NXDOMAIN as a default response to blocked/filtered domains, but AdGuard Home uses Null IP (0.0.0.0) as a default. Is there something specific to AdGuard AdBlocker that makes NXDOMAIN a better response than Null IP? I know the setting can be changed, but I am curious why AdGuard developers set defaults differently for AdGuard AdBlocker and AdGuard Home.

Is there any performance benefit to using one method or the other?

**Comment by zzebrum** [comment]
@EntropySmoke it was [changed](https://github.com/AdguardTeam/AdGuardHome/issues/1914) for AG home.

**Comment by EntropySmoke** [comment]
> 
> 
> @EntropySmoke it was [changed](https://github.com/AdguardTeam/AdGuardHome/issues/1914) for AG home.

That is exactly why I was asking about it. Why change it to Null IP for AdGuard Home, but not change it for AdGuard for Android?
