### ISSUE TITLE
Firefox lite not supported as a browser

### ISSUE THREAD

**Issue by MaharnavS** [AdguardTeam/AdguardForAndroid#3714]
Some of the browser applications are not being detected as a browser application. Some of the applications are duckduckgo, firefox lite, some others. Thus the https filtering is not working for the same. 

Please add some feature to manually add the application under the browser applications category or else please update the list of browser applications.

**Comment by Chinaski1** [comment]
Hello there!

As you have already been answered before:
- for Duckduckgo you may need to install the cert [manually](https://kb.adguard.com/en/android/solving-problems/firefox-certificates)
- Regarding Firefox Lite, you may need root + moving the cert to the system store to make it work.
