### ISSUE TITLE
Google Play: com.sec.android.app.sbrowser.beta

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdguardForAndroid#3716]
@adguard-bot commented on [Wed Dec 23 2020](https://github.com/AdguardTeam/AdguardFilters/issues/70629)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser.beta](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.sec.android.app.sbrowser.beta)
### Comment
Username: @uaevuon
> 
> --
> 하단 정보는 자동으로 생성되었습니다. 삭제하지 마세요.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/4Rvdn4T.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/PXtbsDO.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.6 (1)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> YousList, <br/>List-KR
Custom filter subscriptions: | 

---

@uaevuon commented on [Wed Dec 23 2020](https://github.com/AdguardTeam/AdguardFilters/issues/70629#issuecomment-749845712)

Comment: Adguard breaks Samsung Internet's sync feature. After pausing adguard, sync works.

---

@stanislav-atr commented on [Wed Dec 30 2020](https://github.com/AdguardTeam/AdguardFilters/issues/70629#issuecomment-752393856)

I was not able to reproduce this on my device with both release and beta versions of the app.
@AdguardTeam/filters-maintainers, please, take look.

---

@stanislav-atr commented on [Mon Jan 11 2021](https://github.com/AdguardTeam/AdguardFilters/issues/70629#issuecomment-758029853)

@uaevuon, hi! Could you please send us your AdGuard logs?
Settings > Advanced > Logging level > Record everything
Reproduce the issue again, and then `Export logs and system info.`

---

@uaevuon commented on [Tue Jan 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/70629#issuecomment-758314447)

[adguard_logs_4.0.48_1201_093439.zip](https://github.com/AdguardTeam/AdguardFilters/files/5799073/adguard_logs_4.0.48_1201_093439.zip)
Here it is.

---

@stanislav-atr commented on [Wed Jan 13 2021](https://github.com/AdguardTeam/AdguardFilters/issues/70629#issuecomment-759289770)

@uaevuon, hello! I am moving the issue here.

**Comment by ameshkov** [comment]
@AdguardTeam/qa-team most likely this is HTTPS filtering, we should just figure out what domain to exclude

**Comment by TheHasagi** [comment]
@uaevuon

Please, open AdGuard - Settings - Network - Allowlist and add api.samsungcloud.com to the list and check again.

**Comment by uaevuon** [comment]
> @uaevuon
> 
> Please, open AdGuard - Settings - Network - Allowlist and add api.samsungcloud.com to the list and check again. After you confirm that issue is solved I will add this domain to HTTPS exclusion list.

After adding this domain to HTTPS whitelist, syncing works now.

**Comment by TheHasagi** [comment]
@uaevuon 

The changes will be applied in the nearest update. Thank you for the report.
