### ISSUE TITLE
Bypass DPI

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardForAndroid#3717]
It would be great if Adguard can bypass DPI like Green Tunnel: https://github.com/SadeghHayeri/GreenTunnel

**Comment by cantunborn** [comment]
Don't know if it uses the same tricks for bypassing DPI, but [PowerTunnel](https://github.com/krlvm/PowerTunnel-Android) is another solution and works with Adguard as per the steps discussed in https://github.com/AdguardTeam/AdguardForAndroid/issues/3710#issuecomment-760089163.

**Comment by trmdi** [comment]
> Don't know if it uses the same tricks for bypassing DPI, but [PowerTunnel](https://github.com/krlvm/PowerTunnel-Android) is another solution and works with Adguard as per the steps discussed in [#3710 (comment)](https://github.com/AdguardTeam/AdguardForAndroid/issues/3710#issuecomment-760089163).

Yeah, it would be very cool if Adguard provides this feature out-of-the-box.

**Comment by Chinaski1** [comment]
Hello there!

This feature is good in itself. However, it doesn't really match the overall functionality of the AdGuard AdBlocker app.
We developed the AdGuard VPN app to use this kind of feature :)
By the way, there is a trial period and you can familiarize yourself with the functionality.
