### ISSUE TITLE
Adguard stopping play store and other Android functions?

### ISSUE THREAD

**Issue by bigric68** [AdguardTeam/AdguardForAndroid#3719]
Good day.

I run AdGuard on my Android and my desktop. On Android I’ve been having issues for months. Play store downloads that never finish, updates (also play store) that never finish, text messages that take days to arrive, etc. After trying a bunch of normal things, I finally removed AdGuard thinking that it’s one of the few apps that blocks/prevents data access and so far, it’s not had any issues. It didn’t matter what messaging app I used (Message+, FB Messenger, Samsum Messages), etc. Could there be something going on with this app that’s causing these types of problems? For now, I’m leaving it uninstalled.

Latest version of Android and AdGuard. Have tried current Play Store updates and reverting back to older versions. Have cleared data, cleared cache, etc.

**Comment by Chinaski1** [comment]
Hello there! @bigric68 

Please clarify the following information:
- Which filters are used?
- Whether Stealth-mode is enabled?
- Did you turn on filtering for the Play Store in the app settings?
- Is DNS filtering enabled, and have you tried changing the server and its type?

**Comment by bigric68** [comment]
All of the settings were default. I didn’t change anything. What changes do you recommend (away from default)?

Thanks,
Eric

**Comment by Chinaski1** [comment]
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment]
Unfortunately, without the log files, we can't figure out what's causing the issue.
@bigric68

**Comment by bigric68** [comment]
I will turn it back on.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by srknzl** [comment]
I can confirm that some time after adguard begin to rh , some internet related things do not work or become really slow like browsing,  spotify music switching. I manually restart it to fix this

**Comment by bigric68** [comment]
So far, I've left it off. Months' worth of issues have stopped. I no longer have problems with my cloud player music app, the play store works reliably, even text messages are coming through that had stopped working. I've still not reinstalled as I don't feel like there are any solid suggestions for how to configure it to start it in such a way as to avoid this. It was really hampering my productivity.

**Comment by QAJ321** [comment]
I've noticed that many Google apps don't play nice when they're filtered. Usually I just don't filter Play Store & Gmail so I don't have problems. Chrome is usually fine though

**Comment by drikah** [comment]
> Olá! @ bigric68
> 
> Esclareça as seguintes informações:
> 
> * Quais filtros são usados?
> * Se o modo Stealth está ativado?
> * Você ativou a filtragem para a Play Store nas configurações do aplicativo?
> * A filtragem de DNS está ativada e você tentou alterar o servidor e seu tipo?

Eu tirei a Play Store do filtro e voltou ao normal, é só não deixar o Adguard filtrar apps como: Gmail, Play Store, fotos e outros do Google que não terá problemas. Eu amo o Adguard e não vivo sem ele, já até tentei usar outros, mas o adguard é o melhor!

**Comment by Chinaski1** [comment]
@bigric68 
Glad to hear your issue has been resolved.

@drikah @QAJ321 
As you correctly point out, enabling filtering for these applications can cause issues in their operation.
Therefore, there is not much sense in doing so.
