### ISSUE TITLE
Unable to whitelist SIP apps through Apps management settings

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3720]
### Issue Details

Два телефона Samsung c Android10 и Android11, на обоих не работает правильно «настройка приложений». При отключении защиты AdGuard для всех перепробованных Sip-клиентов (во вкладке «Настройка приложений»), Sip программы не работают, не могут установить соединение. 

SIP-приложения:
https://play.google.com/store/apps/details?id=org.linphone
https://play.google.com/store/apps/details?id=cz.acrobits.softphone.aliengroundwire
https://play.google.com/store/apps/details?id=com.sipnetic.app

- **AdGuard version:**
  - 3.6
- **Filtering mode:**
  - VPN?
- **Device:**
  - Samsung SM-N975F
- **Operating system and version:**
  - Amndroid 10, 11
- **Root access:**
  - n/a

### Expected Behavior

SIP-клиент можно добавить в исключения и разрешить им выходить в Интернет

### Actual Behavior

При отключении защиты AdGuard для всех перепробованных Sip-клиентов (во вкладке «Настройка приложений»), Sip-программы не работают, не могут установить соединение. 

### Additional Information

Helpdesk ID w/ logs: 3133836

**Comment by Chinaski1** [comment]
@Eugene-Savenko 
This issue is not reproduced on my side.
In addition, there is no information in the logs to help figure out the cause of the issue.
Please ask the user to disable DNS and reproduce the situation again specifying the exact time of the issue.

**Comment by Eugene-Savenko** [comment]
@Chinaski1 please check here: 3133836

**Comment by Chinaski1** [comment]
Since the user has not responded for a long time, I am closing this task.
Open it if the issue occurs again.
