### ISSUE TITLE
Mal funcionamiento.

### ISSUE THREAD

**Issue by JorgEngel** [AdguardTeam/AdguardForAndroid#3721]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

En los dispositivos Huawei no tiene un buen funcionamiento, porque automáticamente se apaga y el botón de notificaciones luego no sirve hasta que vuelva a ingresar a la aplicacion.

**Comment by JorgEngel** [comment]
espero que mejoren la compatibilidad con los dispositivos Huawei

**Comment by Chinaski1** [comment]
Hello there!

Most likely This issue occurs because you need to configure the battery background. 
Here are detailed instructions on how to set up the optimization: https://kb.adguard.com/en/android/solving-problems/background-work#Huawei
