### ISSUE TITLE
Add Setting to Turn Off "HTTPS Filtering Error" Notifications

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3722]
I frequently receive a LOT of notifications from AG informing me that the app doe snot accept certificate for a particular domain.

Ex: See screenshot (https://ibb.co/Lzk5vRq)

Can you please include a setting where we can disable these notifications?

**Comment by Chinaski1** [comment]
Hello there!

You should open AdGuard settings -> Advanced -> Low-level settings -> pref.https.ignored.errors -> Add desired domains

**Comment by Chinaski1** [comment]
Add Setting to Turn Off "HTTPS Filtering Error" Notifications

**Comment by Nzzyme** [comment]
Fair enough. What is the syntax that domains and app names should be entered in that setting?

I would say it is a very manual approach rather than have one setting which is valid for all apps and all domains for such notifications.

**Comment by Nzzyme** [comment]
???

**Comment by Chinaski1** [comment]
Sorry for the late reply.

Let's take [speedtest](https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest&hl=en) app as an example.
When adding a domain to exceptions, you must first specify its ID (org.zwanoo.android.speedtest) then you specify the domain that the application uses(www.speedtest.net).
[This](https://uploads.adguard.com/Chinaskibnzeo.png) is what it looks like in the final version.
