### ISSUE TITLE
Local SOCKS5 Proxy Auto-Mode to filter UDP traffic

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardForAndroid#3725]
### Problem Description

Local HTTP Auto-Proxy Mode cannot filter UDP traffic because TCP traffic is all any HTTP proxy can filter. SOCKS5 Auto-Proxy Mode would solve that issue and allow to filter and protect UDP traffic.

### Proposed Solution

Add Local SOCKS5 Auto-Proxy Mode

**Comment by sfionov** [comment]
Local auto proxy can not be socks5, kernel has no such variant of redirection.
