### ISSUE TITLE
Microsoft Edge browser and Vivaldi browser synchronization cannot be used when AdGuard is activated

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3728]
@sH1222J commented on [Sun Jan 24 2021](https://github.com/AdguardTeam/ContentBlocker/issues/247)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:** 3.6
  - 
- **Browser:** Microsoft Edge , Vivaldi browser 
  - 
- **Device model:** Galaxy s10e
  - 
- **Operating system and version:** Android 10
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Microsoft Edge browser and Vivaldi browser synchronization cannot be used when AdGuard is activated
Disabling AdGuard will enable your browser's sync feature.
I want to use AdGuard and Micro Edge browser at the same time.

**Comment by ameshkov** [comment]
@artemiv4nov most likely this is due to HTTPS filtering, let's figure out what domains should be excluded.

**Comment by artemiv4nov** [comment]
I just checked the account synchronization for both browsers, and it worked.

I'll close this task, re-open it if the issue reproduces again.
