### ISSUE TITLE
Add Microsoft Authenticator to the list of exclusions

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForAndroid#3729]
https://github.com/AdguardTeam/AdguardFilters/issues/72932

> ### Issue URL (Incorrect Blocking)
> [https://play.google.com/store/apps/details?id=com.azure.authenticator](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.azure.authenticator)
> 
> ### Comment
> 
> > Microsoft Authenticator refuses to check for notifications or refresh with AdGuard enabled. When excluding app from the local VPN, all functions work.
> > 
> > Error when using local VPN: No internet connection detected.
> > 
> > When excluded from local VPN: No error, approvals function, refresh works.
> >
>
> No blocked domains seen in filtering log, seems to be an issue with the app using the local VPN itself.
>
> Might need to exclude the app from AdGuard for Android by default.

**Comment by Chinaski1** [comment]
Added to HTTPS exclusions
