### ISSUE TITLE
Error while parsing a style tag with embedded svg

### ISSUE THREAD

**Issue by backupmc** [AdguardTeam/AdguardForAndroid#373]
Hi,

The bug is related to a wrong rendering of (at least) the Lifehacker website. You can find more details (and screenshots) in the adguard forum.

http://forum.adguard.com/showthread.php?9655-Troubles-with-Lifehacker-website

Version of the android app: 2.1.359

List of the active filters:
English
Spyware
Social networks widgets
Useful
Mobile phones
EasyList Italy
Liste Fr.

It should be noted that the page isn't rendered correctly just with the advanced/filter mode set to high quality. It works perfectly with both high speed or simplified mode. 

best regards,
Paul

**Comment by backupmc** [comment]
It seems that the problem exists also in gitzmodo.com

http://forum.adguard.com/showthread.php?9655-Troubles-with-Lifehacker-website&p=79214&viewfull=1#post79214

**Comment by BooBerry** [comment]
And it happens on kotaku.com as well

http://forum.adguard.com/showthread.php?9740-Kotaku-com-Android

Lifehacker, Gizmodo and Kotaku are all Gawker Media sites. So it's likely all their sites have this issue.

**Comment by ameshkov** [comment]
There is a complex style on the page:
```url('data:image/svg+xml;utf8,<svg width="32" height="24" viewBox="0 0 32 24" xmlns="http://www.w3.org/2000/svg"><title>Group</title>.................```

AG parsed thought that embedded SVG is html page code and injected inside it. Hence the page code was broken.

**Comment by ameshkov** [comment]
Fixed

**Comment by backupmc** [comment]
Is it been already fixed via a filter update, or will it be with the next release of the app ?

**Comment by Alex-302** [comment]
@backupmc 
it is fixed in alpha version. Filter exclusion is temporary.

**Comment by ameshkov** [comment]
@backupmc it is a program bug, so can't be fixed with filters.

Btw, beta version is already available, pretty stable:
https://github.com/AdguardTeam/AdguardForAndroid/releases
