### ISSUE TITLE
The issue with changing the language in the DNS section

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3731]
Вот этот раздел от AdGuard не локализован

<a href="https://fastpic.ru/view/114/2021/0131/21f96c7852c406fbdf4ca94fb09dd673.jpg.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0131/73/21f96c7852c406fbdf4ca94fb09dd673.jpeg" border="0"></a>

Остальные разделы локализованы, а этот нет.

**Comment by Chinaski1** [comment]
@GdeZsqyAY 

Вы не могли бы, пожалуйста, уточнить какую версию AdGuard вы используете?

**Comment by GdeZsqyAY** [comment]
> @Chinaski1
> 
> Вы не могли бы, пожалуйста, уточнить какую версию AdGuard вы используете?

Использую **AdGuard 3.6** для **Android**

Сделал видео с проблемой. Оказалось, что данный раздел переведен, но не сохраняются настройки.

https://youtu.be/tgBXvfJHADA

Данная проблема идет с любым выбранным сервером ( не только с Вашими ).

**Comment by Chinaski1** [comment]
Мне также удалось воспроизвести вашу проблему.
Спасибо за предоставленную информацию, исправим в ближайших обновлениях.
