### ISSUE TITLE
Так и должно быть?

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3732]
Первые два пункта включены, но иконки серые

<a href="https://fastpic.ru/view/114/2021/0131/b1467f90936fb4d2a49d1846827c505f.jpg.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0131/5f/b1467f90936fb4d2a49d1846827c505f.jpeg" border="0"></a>

Так и должно быть?

**Comment by Chinaski1** [comment]
Приветствую.

Данные пункты выделены оранжевым цветом, поскольку регулировка данных настроек требует повышенного внимания т.к. отключив их, вы заблокируете приложению доступ к сети.
