### ISSUE TITLE
Google Play: de.dkb.portalapp

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3734]
@adguard-bot commented on [Sat Jan 23 2021](https://github.com/AdguardTeam/AdguardFilters/issues/72998)

### Issue URL (Incorrect Blocking)
[NSFW] [https://play.google.com/store/apps/details?id=de.dkb.portalapp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dde.dkb.portalapp)
### Comment
> Beim Download von PDF Dateien wird diese Fehlermeldung angezeigt. Nur beim Ausschalten des Filters komplett funktioniert es.
> --
> Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/dDyXfxz.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/dDyXfxz.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6 (1)
Stealth mode options: | Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (0)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> Fanboy's Enhanced Tracking List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>EasyPrivacy, <br/>AdGuard Tracking Protection, <br/>Fanboy Anti-Facebook List<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/> NoCoin Filter List, <br/>Online Malicious URL Blocklist, <br/>Spam404<br/><br/><b>Other:</b><br/> AdGuard DNS<br/><br/><b>Language-specific:</b><br/> AdGuard German
Custom filter subscriptions: |

**Comment by Alex-302** [comment]
banking app. Can be just excluded from filtering, I guess.

**Comment by Chinaski1** [comment]
Unfortunately, I can't find out which domain is blocked by the AdGuard app as I don't have an account in the bank.
If the user applies again, it is advisable to ask them for this information.
