### ISSUE TITLE
Disable HTTPS filtering in Bromite browser by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3740]
It does not support it since v88 anymore so we should keep it disabled by default (unless the user enables it).

**Comment by jeffersoncheang** [comment]
Hi. This isn't a problem with Adguard, rather Bromite dev has to decide to remove the patch or not.
That said, Android 11 has tighten the CA installation, sonner or later Adguard has to find a way to incorporate the CA into its app, forcibly, I reckon.

Let's wait for Bromite dev to take action. Issue has been raised in their Github.

**Comment by ameshkov** [comment]
Well, okay, let's wait a little bit and keep it as is now.

**Comment by ameshkov** [comment]
It seems that Bromite will roll this back, we can close this.

**Comment by dantecpu** [comment]
Another working solution is moving the certificate to system, on Android 10 we can do that with AdGuard itself easily.

Unfortunately on Android 11 I had to use a Magisk module to do so with the stable release of AdGuard.
