### ISSUE TITLE
Add Vivaldi Snapshot to the HTTPS filtering list

### ISSUE THREAD

**Issue by KosmoEskudo** [AdguardTeam/AdguardForAndroid#3741]
### Problem Description

My version of AdGuard: 3.6 (1)

When installing Vivaldi Snapshot (version 3.6.2173.4) from the Play Store, HTTPS filtering is disabled (unlike other browsers like Firefox Nightly). When trying to enable it, it says that "this application does not trust the user's certificate, so HTTPS filtering may break secure connections". However, in the stable version of Vivaldi (3.5.2115.95) HTTPS filtering is enabled by default.

### Proposed Solution

- HTTPS filtering for Vivaldi Snapshot by default.

- Enable HTTPS filtering manually, but is it safe?

### Additional Information

It was mentioned last year here https://github.com/AdguardTeam/AdguardForAndroid/issues/3400#issuecomment-625805562

**Comment by Chinaski1** [comment]
@KosmoEskudo 

I have now checked and can indeed confirm that HTTPS filtering for the specified browser is not enabled by default.
Once enabled, the browser works correctly and ads are completely blocked. Therefore you can enable this feature in Apps Management - it's safe.
We will add this browser to the default HTTPS filtering list in the next updates.
