### ISSUE TITLE
Для прозрачного редиректа https через iptables на AdGuard нужен локальный socks - прокси

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3745]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

На локальный http - прокси AdGuard в ручном режиме невозможно через iptables перенаправить https-траффик. Для https прозрачный редирект работает лишь для socks-прокси (см. TOR).

### Proposed Solution

Для прозрачного редиректа https через iptables на AdGuard нужен локальный socks - прокси

**Comment by Chinaski1** [comment]
Добрый день!

Это ожидаемое поведение AdGuard, приложение не будет обрабатывать трафик отправленный через iptables в ручном режиме.

Что касается предлагаемого решения, вы не могли бы, пожалуйста, более подробно описать шаги его реализации?

**Comment by Baltazar500** [comment]
>Это ожидаемое поведение AdGuard, приложение не будет обрабатывать трафик отправленный через iptables в ручном режиме.

Но http же он без проблем обрабатывает, а вот с https не работает :/ Та же петрушка возникает, если направить https трафик на ТОР'овский polipo. Если https направить на ТОР'овский локальный socks-прокси, то трафик без пробоем заворачивается.

>Что касается предлагаемого решения, вы не могли бы, пожалуйста, более подробно описать шаги его реализации?

Если вопрос по части кодинга, то это увы не ко мне :( В этом не разбираюсь :( 

У меня проблема с редиректом https на AdGuard через iptables по конкретным owner'ам и я предположил, что локальный socks - прокси вместо http прокси, который поднимает AdGuard на порту 8080 мог бы решить эту проблему. 

Или подобное невозможно реализовать ? 

Может быть есть альтернатива, дабы можно было вручную маршрутизировать трафик именно через iptables (рут у меня есть)  ?

**Comment by sfionov** [comment]
Прозрачное проксирование возможно только в Auto proxy и VPN режимах.

В режиме ручной прокси адгард работает как HTTP-прокси, соответственно требует HTTP CONNECT-запроса перед установкой HTTPS-соединения. iptables не умеет создавать такие запросы.

В локальный SOCKS-прокси же невозможно никакое заворачивание HTTP-трафика с помощью iptables, т.к. вместо HTTP-запроса он ожидает SOCKS5-хендшейк.

**Comment by Baltazar500** [comment]
>Прозрачное проксирование возможно только в Auto proxy

А почему его нельзя включить и для обычного прокси-режима ? Отдельной настройкой например ?

>В локальный SOCKS-прокси же невозможно никакое заворачивание HTTP-трафика с помощью iptables, т.к. вместо HTTP-запроса он ожидает SOCKS5-хендшейк.

Хм, ОК. А сделать как это реализовано у ТОР'а (не тот, что приложение, а тот что консольный) возможно например ?

**Comment by sfionov** [comment]
> А почему его нельзя сделать/включить и для обычного прокси-режима ? Отдельной настройкой например ?

Manual proxy-режим существует для совместимости и не работает на Android 11. Мы не планируем расширять его поддержку. А вот то, что он когда-нибудь исчезнет - вполне вероятно.

**Comment by Baltazar500** [comment]
>Manual proxy-режим существует для совместимости и не работает на Android 11. Мы не планируем расширять его поддержку. А вот то, что он когда-нибудь исчезнет - вполне вероятно.

Т.е. с ручной маршрутизацией трафика через iptables без выдачи рута AdGuard'у совсем без вариантов ? Просто мне нужно, чтобы AdGuard вмешивался в работу iptables ибо он нарушает логику остальных моих правил редиректа.

**Comment by Chinaski1** [comment]
Все именно так, без наличия root прав ничего не выйдет.
