### ISSUE TITLE
Legacy - версия AdGuard для старых устройств ?

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3746]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

В нынешнее время похоже считается дурным тоном поддерживать старые устройства, но тем не менее многие разработчики ведут отдельные "Legacy" ветки своих программ/прошивок производя мелкие фиксы в рамках возможностей тех версий и поддерживая тем самым продукт на плаву. Можно ли рассчитывать на появление подобной ветки у AdGuard'a ? Или у AdGuard'a движение только "вперёд" как у локомотива, с отказом от всего "старого" ?

Банальный пример. На 2.12.250, последней, доступной для 4.2.2 через пень-колоду работает прокси-фильтрация и AdGuard постоянно на ней валится, а через локальный VPN всё работает более-менее стабильно (без шероховатостей типа смахивания AdGuard'a и его дезактивации по причине этого тоже не обошлось). Плюс до кучи включение/выключение вафли вызывает нехилый лаг из-за рестарта локального VPN'a. И что делать в такой ситуации ? Обновлять гаджет из-за таких мелочей я смысла не вижу. Но лишнего геммороя они добавляют определённо ...

### Proposed Solution

Legacy - версия (ветка) AdGuard для старых устройств

**Comment by Chinaski1** [comment]
Добрый день!

В данный момент вектор разработки направлен на совершенствование продуктов AdGuard for Android и AdGuard VPN.
В скором времени мы планируем выпустить версию 4.0. с обновленным функционалом и новым дизайном.
Поэтому заниматься поддержкой Legacy приложений для старых версий Android не является целесообразным.
