### ISSUE TITLE
Consolidate battery saving settings into a single menu

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdguardForAndroid#3748]
### Problem Description

Users can disable certain settings (e.g. get rid of system notification) in order to reduce AdGuard's battery drain. However, these settings are located across different menus.

### Proposed Solution

Consolidate these settings into a single menu.

### Alternatives Considered

None provided.

### Additional Information

Original submission: see helpdesk ticket 3193511.

**Comment by artemiv4nov** [comment]
Well, since 2021, the app design has been changed, the batery counting functionality has also been changed, will close the task
