### ISSUE TITLE
Local VPN pauses

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardForAndroid#3751]
### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Expected Behavior

Vpn always on to clear ads

### Actual Behavior

From time to time vpn pauses and shows waiting for other vpn to stop in notification area
### Screenshots

<details><summary>Screenshot:</summary>
![Screenshot_20210215-141517_Telegram](https://user-images.githubusercontent.com/46019727/108043095-da862200-706a-11eb-8f7b-38847bb5ff36.jpg)

</details>

**Comment by anastenko** [comment]
Hello. Most likely the issue is present because you're trying to use some third-party VPN along with AdGuard VPN. This is a limitation of Android OS. You can't use 2 VPN services at the same time.

**Comment by Bhooty** [comment]
No all are turned off

**Comment by anastenko** [comment]
Could you please open your phone settings -> Network -> Advanced -> VPN -> and check if there are any third-party connections ?

**Comment by Bhooty** [comment]
Yes there are like 3-4 
But even when i don't turn on those vpn like windscribe adguard pauses and resumes after sometime :3
Tried dns66 it also used to have same problem but then they gave a watch connection option
If i enable it
It doesn't pause anymore

**Comment by anastenko** [comment]
Looks like one of the applications connects its vpn service. You can temporarily delete those VPN services of yours and check if the issue still remains.

**Comment by Bhooty** [comment]
Tried it
It works 
But suppose i use a vpn later
Then adguard again have same problem
Ultill i restart and delete the vpn profile of the vpn

**Comment by anastenko** [comment]
Android OS sets a limit on the simultaneous use of only 1 VPN service.
AdGuard pauses precisely because you launch a third-party VPN (or have it automatically activated).

**Comment by Bhooty** [comment]
Yes that's what i saying xD
It does activate automatically 
But pauses randomly thinking another vpn is on :3
