### ISSUE TITLE
AdGuard with proxy not working

### ISSUE THREAD

**Issue by Dan884** [AdguardTeam/AdguardForAndroid#3754]
It used to work. Now my browsers just hang when I turn Proxy on.
I haven't used the VPN for a while so I don't know when it stopped working. 
I am using NordVPN Socks5 server us6451.nordvpn.com.
I have tried others. 
NordVPN works when AdGuard is turned off. 
AdGuard works when proxy is turned off. 
I am using the latest AdGuard version 3.6.
I am running on a Samsung Galaxy S5e tablet running Android 10.
It did the same thing on my Samsung Galaxy S20 FE 5G running Android 11.
Any help would be appreciated.
Thanks

**Comment by anastenko** [comment]
Hello. This issue is not on the AdGuard's side.
Most of the servers are currently being reworked by NordVPN, so there might be difficulties with connecting to them.
You can check this info here: https://nordvpn.com/blog/socks5-proxy/
