### ISSUE TITLE
Add the ability to block sponsor inserts on YouTube

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3755]
Здравствуйте!
Предлагаю сделать интеграцию с этим расширением (это Open Source) https://sponsor.ajay.app/.
Оно блокирует спонсорские вставки (непосредственно от блогера) на YouTube. Было бы очень полезно.

**Comment by Chinaski1** [comment]
Добрый день!

Да, это выглядит как  действительно хорошее дополнение к функционалу блокировщика.
Мы подумаем над возможностью реализации собственного расширения.
Спасибо за озвученную идею. :)

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardBrowserExtension #1762](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1762) via [**ZenHub**](https://www.zenhub.com/)
