### ISSUE TITLE
Блокировка протоколов

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3757]
Здравствуйте!
Есть ли возможность заблокировать все сайты работающие на http? Можно ли сделать так, чтоб сайт http://example.com блокировался, а https://example.com нет?

Буду рад вашему ответу!)

**Comment by Chinaski1** [comment]
Добрый день!

Вы можете использовать данное правило фильтрации для блокировки `http` сайтов: `/^http:\/\/.+$/$important,document`
