### ISSUE TITLE
Https фильтрация

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3758]
Здравствуйте!

**О чем речь?**
**Речь о пользовательском интерфейсе. А если быть точнее исправлении неточности (ошибки) в тексте в самом приложении**

В настройках приложений имеется флаг "Фильтрация https". По умолчанию он отключён, но при нажатии на него появляется надпись, что приложение не доверяет пользовательскому сертификату. Это не совсем правильно, так как приложение того же Telegram спокойно работает и с включённой фильтрацией.

Предлагаю заменить текст предупреждения на:
"Данное приложение может функционировать некорректно при включении https фильтрации"

**Comment by Chinaski1** [comment]
Добрый день!

Включение HTTPS фильтрации для ряда приложений является не лучшей идеей, т.к. активация данной настройки может привести к неккоректной работе фукнционала. В всплывающем уведомлении мы указываем первопричину проблемы. Нет видимых предлогов исправлять или менять текст данного уведомления.
