### ISSUE TITLE
Missing app in App Management list

### ISSUE THREAD

**Issue by ja-som** [AdguardTeam/AdguardForAndroid#3763]
### Issue Details

- **AdGuard version:** 
  -  3.6.1
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Nvidia SHIELD TV 2019 (not Pro)
- **Operating system and version:**
  -  SHIELD Android TV 8.2.2
- **Root access:**
  -  No

### Description

Application **SideApps - App launcher for TV** is not listed in App Management list and it displays ads.
Link to the app:
https://play.google.com/store/apps/details?id=net.easyjoin.applauncher

Please let me know if you need more information.

**Comment by anastenko** [comment]
Hello there.
Unfortunately, you can't install the HTTPS certificate on Android TV boxes (Including Nvidia Shield TV, unless you have a root rights)
In this case it's better to use AdGuard DNS or AdGuard Home (https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started) for ad blocking on Android TV.

**Comment by ja-som** [comment]
Hi,
I noticed that when I installed Adguard, but I didn't know that the certificate is needed to "detect" installed apps.
Thanks for your reply, I'll try that Home app.

**Comment by anastenko** [comment]
Most likely the absence of Nvidia SHIELD TV 2019 in the list of applications occurs because it doesn't have permission to use the Internet (maybe this console is forbidden to use the Internet on its own, so it's defined as an offline app)
