### ISSUE TITLE
Expanding the functionality of the custom filter editor

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3764]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Собственные правила блокировок рекламы в AdGuard очень муторно удалять. Надо ткнуть по правилу, ткнуть удалить и подтвердить удаление. Для одного - двух правил это куда ни шло. А если их там пара десятков ? Так реально задолбаться можно. Можно конечно вычистить xml-ку с конфигом, но это так себе вариант, к тому же требующий рута.

### Proposed Solution

Лонг-тап на любом из правил вызывает его выделение и позволяет выделять соседние правила а потом посредством кнопки "удалить" в верхнем баре их удалить с предварительным подтверждением удаления. 

p.s. Кнопка "копировать" в верхнем баре тоже пригодилась бы :)

**Comment by Chinaski1** [comment]
Добрый день!

Данная возможность уже реализована в "Редакторе" пользовательских правил.
Откройте настройки AdGuard -> Блокировка Контента -> Пользовательские правила ->  3 точки в правом верхнем углу экрана -> Редактировать
Использу данную функцию, вы сможете массово удалять/добавлять/редактировать правила в более удобном для вас формате.

**Comment by Baltazar500** [comment]
>Данная возможность уже реализована в "Редакторе" пользовательских правил.

Там кнопки "Удалить/Включить/отключить" всё. Возможности выбора конкретных правил нет. Если мне надо зачистить десяток-другой правил, которые раскиданы по списку в пару сотен правил, мне как быть ? Делать экспорт, зачистку в редакторе, а потом импорт ? 

Копирования прааил в буфер обмена там тоже не видно.

**Comment by Baltazar500** [comment]
Так что по поводу  озвученной в тикете фичи ? Предложенное выше имеет низкую степень юзабилити т.к. там приходится действовать как в текстовом редакторе (хотя в ряде случаев эта фича удобна) и хотелось бы иметь озвученную в тикете возможность удалять (да и копировать) правила, выделив их посредством long - тапа (или long-тап на любом правиле, а потом уже выделение последующих, как с мейлами в AquaMail - очень удобно).

Этот тикет забросили ? Мне перееоткрытвать новый, дабы запрос было видно ?

**Comment by artemiv4nov** [comment]
Функционал был значительно переработан в 4.0 версии, пожалуйста используйте её.

**Comment by Baltazar500** [comment]
>Функционал был значительно переработан в 4.0 версии, пожалуйста используйте её.

На момент запроса функционала AdGuard был версии 3.x и вполне себе поддерживал Android 5.1. AdGuard 4.x его поддерживает (вопрос риторический) ?
