### ISSUE TITLE
Any chance block ads from this sites?

### ISSUE THREAD

**Issue by kotoricon** [AdguardTeam/AdguardForAndroid#3766]
Those ads really suck.
![Screenshot_20210223-012843_Samsung Internet](https://user-images.githubusercontent.com/8659834/108746210-fca20780-7576-11eb-86bf-49493cfa9efe.jpg)

example:
http://m.feijisu7.com/acg/60525/8.html

Tried to block 'm.feijisu7.com' but look like there ads servers always change, dont really works well. chrome and samsung self browser dont work for this site.

**Comment by Chinaski1** [comment]
Hello there!

I will move this task to the filters section.
But first, I recommend that you check for filter updates and clear your browser cache.

**Comment by anastenko** [comment]
Issue moved to [AdguardTeam/AdguardFilters #75815](https://github.com/AdguardTeam/AdguardFilters/issues/75815) via [**ZenHub**](https://www.zenhub.com/)
