### ISSUE TITLE
[Android] Breaking lifehacker.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#377]
Website is not displayed correctly (http://screencast.com/t/Y6lFGJg9UB) when high-quality filtering mode is enabled.

Originally posted on: http://forum.adguard.com/showthread.php?9655-Troubles-with-Lifehacker-website

Duplicated from here:
https://github.com/AdguardTeam/ExperimentalFilter/issues/1786

**Comment by TPS** [comment]
#373?

**Comment by ameshkov** [comment]
Ops, indeed, closing this as duplicate.
