### ISSUE TITLE
Wi-Fi exceptions for DNS filtering

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3771]
@Eugene-Savenko commented on [Sat Feb 27 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3704)

>Please add, if possible, the option to disable DNS filtering on certain networks like you can in the iPhone app.

Helpdesk ID: 3227382

**Comment by Chinaski1** [comment]
You can set up selective use of DNS on Wi/Fi networks using the [tasker](https://kb.adguard.com/en/android/solving-problems/tasker).

**Comment by ameshkov** [comment]
Duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/3158
