### ISSUE TITLE
Add HTTPS filtering support for Via browser

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3772]
### Problem Description

App: https://play.google.com/store/apps/details?id=mark.via.gp&hl=en&gl=US

Does not currently accept our filtering certificate. Unclear if the browser accepts any third-party certificates at all.
 
### Proposed Solution

Check if the browser accepts certificates. If it does, add it to our list of filtered apps by default.

### Additional Information

Helpdesk ticket id 2287635.

**Comment by Chinaski1** [comment]
The browser in question does not trust user certificates, so HTTPS filtering will not work there.
The only option is to transfer the certificate to the system if you have root rights.
