### ISSUE TITLE
Add additional tracking parameters to be stripped by Stealth Mode

### ISSUE THREAD

**Issue by wefalltomorrow** [AdguardTeam/AdguardForAndroid#3773]
### Problem Description

The default tracking parameters in Stealth Mode seem to be a bit lacking, missing even simple UTM_ parameters such as utm_cid, utm_name, utm_reader, etc.

### Proposed Solution

Add additional tracking parameters by default that other URL cleaners/strippers include, such as (but not limited to); cmpid, dclid. hmb_campaign, hmb_medium, the aforementioned utm_* parameters, etc.

My current list: https://pastebin.com/d37vg8zJ

**Comment by infinitewaveparticle** [comment]
> ### Proposed Solution
> Add additional tracking parameters by default that other URL cleaners/strippers include, such as (but not limited to); cmpid, dclid. hmb_campaign, hmb_medium, the aforementioned utm_* parameters, etc.
> 
> My current list: https://pastebin.com/d37vg8zJ
> 
> ### Alternatives Considered
> ### Additional Information

others i've found on my own include:
trx?id
ancestor_origins
siteid
yptr
guce_referrer
withAds
adgroup
src_bizid
src_ref
user_agent
show_in_content_ads
customReferer
referrer

i have more too. this is my bread & butter ;)

**Comment by ameshkov** [comment]
Since we now use AdGuard URL Tracking filter all things like that should be reported to AdguardFilters.
