### ISSUE TITLE
Miui 12 (Android 10) is disabling Adguard despite executing advised actions on permissions and power management

### ISSUE THREAD

**Issue by guroncall** [AdguardTeam/AdguardForAndroid#3775]
### Prerequisites

1) I confirm I am running the latest version of AdGuard for Android: v 3.6.1
2) I confirm I checked the documentation and forums and found only some advice for MIUI 10/1: I applied such advice to the best of possibilities but not all the settings advised could be found in MIUI12.
3) I confirm I checked in the list of issues reported, both closed and open, and I could not find any matching this.

### Issue Details

- **AdGuard version:**
  - 3.6.11
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Mi Note 9T 5G
- **Operating system and version:**
  - Android 10 QP1A. 190711.020 (MIUI 12.0.4)
- **Root access:**
- NO root access
  - 

### Expected Behavior

AdGuard keeps running and doesn't get disabled by Android/MIUI

### Actual Behavior

I've been applying all the settings and options known to me to prevent Android/MIUI from stopping AdGuard: still, after 6 to ( hours of inactivity (typically during the night) AdGuard is stopped and needs manual restarting.

### Screenshots

No significant screenshots available, right now.

### Additional Information

Under the menu "Settings -> VPN ->" I just now found a configuration for AdGuard to be kept always on: I activated it and see if Adguard will "survive" tonight pausing. I'll let you know the result of this experiment in the morning.

**Comment by guroncall** [comment]
Hi again,
as mentioned in the "Additional Information" section above, I gave a try to "Keep VPN Always On" setting and I'm sorry to say it did not work: AdGuard has been stopped by MIUI/Android overnight.

**Comment by guroncall** [comment]
Sorry, closed by mistake. Reopened, now.

**Comment by anastenko** [comment]
Hello there.
Unfortunately we can't do anything about this issue on the application side. The problem is caused by the MUIU 12 system itself (might be caused by energy saving mode which drops the application). You can try using this instruction: https://dontkillmyapp.com/xiaomi

**Comment by orabeidm** [comment]
та же самая проблема. нужно искать обход. вочдог не работает. мы ничего не можем сделать - не выход. телефонов сяоми тьма. к примеру тот же рустор бьётся в активность несмотря на все запреты. не можете сделать сами - узнайте как сделали другие
