### ISSUE TITLE
Unable to use snapdrop with Adguard

### ISSUE THREAD

**Issue by terrytw** [AdguardTeam/AdguardForAndroid#3778]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

- **AdGuard version:**
nightly
- **Filtering mode:**
VPN
- **Device:**
Oneplus 5T
- **Operating system and version:**
Oxygen OS 10.0.2 based on Android 10
- **Root access:**
Yes

Hello respected devs,

I ran into a problem with Snapdrop: https://github.com/RobinLinus/snapdrop
It's a website that lets you transfer files within the same subnet. 

Whenever I have Adguard enabled on my android phone, I will be able to see other devices on the same local subnet, but I am not able to send messages or files through. 

I am aware that Snapdop uses webrtc protocol, so I disabled stealth mode since it has a function to disable webrtc, but the problem persists. In fact, I can disable every single ad blocking function of Adguard, just tunneling traffic through VPN would cripple the Snapdrop function. 

Can you please look into this? Thanks!

**Comment by anastenko** [comment]
Hello.
This is a known issue, but unfortunately there's still no solution, but to turn the filtration off.
We will investigate it further and hope to fix it soon.

**Comment by terrytw** [comment]
Can you please give me a little bit more details on this? 
What exactly is the cause here?

**Comment by anastenko** [comment]
It's still unknown why the issue occurs, that's why we can't provide any details on that.
Nevertheless this problem can be reproduced on our side and we will look into it.

**Comment by anastenko** [comment]
@terrytw 
In order to investigate this issue furthermore, we need to get additional logs.

Here's what we need you to do: 

1. Collect the debug log as it's explained [here](https://kb.adguard.com/en/android/solving-problems/log);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. Here's the [instruction](https://kb.adguard.com/en/android/solving-problems/logcat);
4. Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by terrytw** [comment]
Hi, I have sent the log as you requested. 

I would also like to update on my end about what I believe is the cause of this problem, just for anyone whose is interested to read. 

I believe this is a problem between Adguard and ICE services like TURN and STUN. When using these services, clients need to report their local IP addresses for the possibility of a direct connection. However when using Adguard in VPN mode, it creates an IP adress of 172.18.11.218. Client would report this IP to TURN or STUN servers, other peers would try to connect to client using 172.18.11.218 instead of the actual private IP address that the client has (like 192.168.1.100). This is the cause of the problem. It is also causing UPNP problems as well, when client request a UPNP port, it would be rejected because client wants to establish a port mapping using IP address of 172.18.11.218. 

I am fairly confident in my speculations that the IP address 172.18.11.218 caused these numbers of issues.

**Comment by sxgunchenko** [comment]
Hi, @terrytw. Your assumption seems to be correct, so the best we can suggest is to exclude the application from filtering.

**Comment by terrytw** [comment]
OK.
