### ISSUE TITLE
Samsung Battery saving feature interferes with Adguard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#378]
> I'm using s7 edge. Adguard seems to be blocking my Internet connect whether it's wifi or mobile data when my s7 edge is in power saving mode. If it's not in power saving, there is no issue with the connection. Can you assist?

Asked for logs: YNX-978-72059
BXN-748-55159 - Samsung S6

**Comment by vozersky** [comment]
Turning battery optimizing for Adguard off doesn't help.
Logs updated.

**Comment by vozersky** [comment]
Same here:  TICKET ID ZRR-164-27956

**Comment by vozersky** [comment]
#247

**Comment by ameshkov** [comment]
We have the similar issue with stock firmware, yet there turning battery optimization is enough: #247 

We will pause the protection in battery saving mode then.

**Comment by Revertron** [comment]
We made pausing the protection on power saving mode. Needs testing.

**Comment by ameshkov** [comment]
We'll test it when samsung galaxy arrives in the  office:)

**Comment by evgeniy-ADG** [comment]
Samsung SM-G900F Galaxy S5 - LBZ-403-38324
The latest beta didn't help.

**Comment by ameshkov** [comment]
@gshumihin could you please check if there is any issue with our test Samsung device?

**Comment by gshumihin** [comment]
Reproduced situation with blocked internet connection, here's log:

[adguard.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/281933/adguard.txt)

**Comment by ameshkov** [comment]
The difference between Samsung and others is that in its case even when network is no more accessible (in the power save mode) ConnectivityManager still returns a positive result.

So, instead of using ConnectivityManager we should try to create a real connection and see if it is refused or not.

**Comment by Bohdan-SUP** [comment]
User 1191238 still faces the trouble when battery saving is enabled with 2.6.108
Log - [debug (2).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/324655/debug.2.txt)

**Comment by ameshkov** [comment]
@Bohdan-SUP what's the problem exactly?

**Comment by ameshkov** [comment]
In the end it appears I have not fully fixed that issue.

Should be good in this build:
[adguard.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/371503/adguard.apk.zip)
