### ISSUE TITLE
Improve the AdGuard applications communication

### ISSUE THREAD

**Issue by pdkpv** [AdguardTeam/AdguardForAndroid#3780]
We talked to @artemiv4nov about this problem, he is aware of all the details.

Briefly: due to constant communication AG and AG VPN among themselves - AG reconnects after using the system function "Clean up memory" (closing running applications), as it restores connection with AG VPN. Because AG VPN is not excluded by the system function "always hold in memory".

https://user-images.githubusercontent.com/43634070/111155556-a89ea780-85a5-11eb-93a7-35bf042d321d.mp4

**Comment by artemiv4nov** [comment]
Well, this issue should be gone
