### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3781]
I don't get it, why adguard still can get  the ip addr?...

adguard "blocked" them? right?...

![Screenshot_2021-03-17-02-32-24-200_com.adguard.android.jpg](https://user-images.githubusercontent.com/75058881/111362221-7f773780-86c9-11eb-8883-da2dc68f7ab9.jpg)![Screenshot_2021-03-17-02-32-27-013_com.adguard.android.jpg](https://user-images.githubusercontent.com/75058881/111362228-81d99180-86c9-11eb-9d09-58b8b9cfee0b.jpg)

**Comment by c2xusnpq6** [comment]
version: android 3.6.11

**Comment by zzebrum** [comment]
@c2xusnpq6 Probably, the IP address is hardcoded, or the app somehow is able to recover and re-request it using different means.
Add `||ap.cpatrk.com^` to the Content Blocking user filter, it should completely block it.
Also, do you know what's the purpose of this domain? Should we block it in our filters?

**Comment by c2xusnpq6** [comment]
@zzebrum I'm using this filter `anti-AD`, it's for Chinese website
https://github.com/privacy-protection-tools/anti-AD/
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt

**Comment by Chinaski1** [comment]
This IP seems to be used to redirect requests.

You can add these filters at your discretion but blocking such requests is not a good option as it may cause issues with the app operation.
