### ISSUE TITLE
Add integration with whotracks.me

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardForAndroid#3783]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Additional Information

In the same way [AdGuardHome](https://github.com/AdguardTeam/AdGuardHome/issues/364) has, could you please integrate with whotracks.me to provide more info on what is being blocked and  why.

**Comment by Chinaski1** [comment]
Hello @zero77 

We plan to add a similar feature in the forthcoming update 4.0.
Let's come back to your proposal when the update is released.

**Comment by artemiv4nov** [comment]
This integration has been implemented in Statistics.
