### ISSUE TITLE
Feature request: Опция отключения уведомления о выходе новой версии.

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3785]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

При выходе новой версии при каждом обновлении фильтров вылезает назойливое уведомление о выходе новой версии в панели уведомлений, сопровождаемое миганием светодиода. Иной раз его можно смахнуть, а иногда оно "приколото" к панели уведомлений. У меня не вмегда есть желание апдейтить версию AdGuard и такое роведение утилиты жутко раздражает.

### Proposed Solution

Нужна опция отключения уведомления о выходе новой версии

**Comment by anastenko** [comment]
Здравствуйте!
Мы стараемся сделать наш продукт лучше с каждым обновлением, исправляя возникающие проблемы и добавляя новый функционал, поэтому установка обновлений необходима. 
Если вы не желаете обновлять приложение, всегда можно оставить более старую версию. Однако уведомления при этом всё ещё будут появляться.
Уточните, пожалуйста, что влияет на ваше решение не обновлять приложение до актуальной версии?

**Comment by Baltazar500** [comment]
>Если вы не желаете обновлять приложение, всегда можно оставить более старую версию. Однако уведомления при этом всё ещё будут появляться.

Если бы оно мне не моргало светодиодом, да и бог с ним. А так, простите, жутко раздражает.

>Уточните, пожалуйста, что влияет на ваше решение не обновлять приложение до актуальной версии?

Опыт и поговорка "работает  - не трогай". Обычно я адейчусь спустя n-е число билдов, когда в новой версии появляются функции, без которых мне уже ну вот никак не обойтись и когда версия давно находится в stable-состоянии и новые релизы не штампуются аки горясие пирожки.

**Comment by artemiv4nov** [comment]
@Baltazar500 Добрый день!

Убирать это уведомление мы точно не будем, поскольку очень важно обновляться на новые версии хотя бы потому, что фильтрация улучшается с каждым разом.

Попробуйте сходить в системные настройки уведомлений и для нашего приложения уберите "световое уведомление". На каждой версии оно по-разному называется, но суть примерно та же.

**Comment by Baltazar500** [comment]
>Убирать это уведомление мы точно не будем, поскольку очень важно обновляться на новые версии хотя бы потому, что фильтрация улучшается с каждым разом.

Да никто не просит его убирать. Сделайте опцию для отключения, по умолчанию деактивированную. Кому нужно - тот отключит.

>Попробуйте сходить в системные настройки уведомлений и для нашего приложения уберите "световое уведомление". На каждой версии оно по-разному называется, но суть примерно та же.

На 5.1 такого нет (я по крайней мере подобного не нашёл). Только полное скрытие уведомлений. А это может быть чревато тем, что тасккиллер андроида быстро схлопнет AdGuard.

**Comment by Baltazar500** [comment]
Новые билды стали выходить с завидным постоянством и AdGuard стал постоянно семафорить светодиодом. Запилите галку "Проверять наличие новой версии", ну ей богу. Ведь куча же софта с подобной функцией существует. Реально уже этот чекинг задолбал.

**Comment by Chinaski1** [comment]
Да, закрытые тикеты продолжают монитроиться. 

И думаю нет смысла открывать задачу повторно, так как мы уже обозначили политику касательно уведомлений об обновлении приложения.

**Comment by Baltazar500** [comment]
> Да, закрытые тикеты продолжают монитроиться.
> 
> И думаю нет смысла открывать задачу повторно, так как мы уже обозначили политику касательно уведомлений об обновлении приложения.

В панели уведомлений на пару со светодиодом это обязательно ? Уберите моргание светодиодом и пусть оно хоть 10 раз висит.
