### ISSUE TITLE
Повышение безопасности

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3793]
Здравствуйте!
Прошу вас рассмотреть возможность внедрения кода Https Everywhere (open source) внутрь вашего приложения. Это существенно повысит безопасность трафика.

Ссылка на https everywhere:
https://github.com/EFForg/https-everywhere

Это будет особенно полезно, если пользователь использует режим прокси в Adguard так как некоторые прокси при передаче через них незашифрованного трафика могут его просматривать и использовать в своих корыстных (либо и вовсе вредоносных) целях.

Предлагаю добавить подобный функционал с возможностью **ПОЛНОЙ** блокировки незашифрованного трафика (например http)

Если нет возможности реализовать добавление конкретного кода, то предлагаю сделать что-то подобное:
Случай 1:
http запрос -> Adguard меняет http на https -> успешное соединение
Случай 2:
http запрос -> Adguard меняет http на https -> невозможно установить https соединение -> блокировка запроса и отображение дисклеймера.

P.S: Тоже самое касается и FTP (его нужно менять на FTPS)

Считаю данное дополнение предельно важным в связи с тем, что многие пользователи подвергаются перехвату трафика со стороны злоумышленников, в то время как Adguard позиционирует себя как компанию, которая борется за безопасность пользователей.

Есть еще более простой способ. Попросту заблокировать http и показать дисклеймер.

Почему блокировка Http не повлияет на комфортное использование интернета?
Все очень просто:
Большинство сайтов (около 98%) используют зашифрованный канал связи.

Протокол http является крайне не безопасным (во всяком случае так считают разработчики Tor и Firefox, блокируя http).

**Comment by Chinaski1** [comment]
Добрый день, мы планируем реализовать данную функцию на уровне фильтров.

С оригинальной задачей вы можете ознакомиться [тут](https://github.com/AdguardTeam/CoreLibs/issues/1284)

Данную задачу я закрываю как дубликат.
