### ISSUE TITLE
Delete annoying object from interface

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3794]
Dear developers!
Please remove the annoying Adguard VPN item from your app settings! Because of it, I am forced to stay on the app version 3.4. I believe that this is nothing more than a spit in the face by the user. Make a cross for closing at least. There are users who do not want (or cannot afford) to use your VPN service. And there are users who keep their own VPN server (such as me, for example) because it is not a good idea to transmit traffic through servers, even if it is a very well-known company.

Please remove the intrusive offer from your app. this is seriously annoying and discourages the desire to update. You are a company that fights such content by blocking it! And you take it and do it with the users. This is ridiculous!

I have repeatedly written to your technical support (by mail and without), but some of the letters were not answered at all, and some were recommended to create a topic on the forum or here. I really hope that I am not the only one and that you will listen to my opinion.

Hello from Netherlands ;)
Thanks for reading.
This is just a cry of the soul.

**Comment by Chinaski1** [comment]
Hello there!

Honestly, I don't see any good reason for removing the notice in question. The AdGuard VPN app has been specifically designed to work in conjunction with the AdBlocker as they can work perfectly in compatibility mode.
In addition, the item is not on the home screen and does not send annoying notifications, or something like then. Just neatly located in the settings section.
I hope you will decide to update the app after all :)
