### ISSUE TITLE
Необходима поддержка proxy.pac самим AdGuard'ом

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3795]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

В AdGuard нет возможности настраивать маршрутизацию трафика через прокси, а предложенное решение в качестве использования proxy.pac посредством прописывания его в настройках сетевых настроек системы несёт ряд минусов. В моём случае это невозможность указать локальный proxy.pac файл (система принимает лишь расположенный на удалённом или локальном сервере файл) и работа с этим proxy.pac'ом только встроенного AOSP - браузера. В таком случае цепочка с использованием локального VPN'a и proxy.pac'a становится бесполезной. С режимом прокси AdGuard'a AdGuard и proxy.pac в принципе не удалось подружить.

### Proposed Solution

Нужна поддержка proxy.pac в самом AdGuard'e минуя системную надстройку. Или как минимум менеджер сайтов для каждого прокси (отдельной опцией напротив каждого прокси) например.

**Comment by artemiv4nov** [comment]
Идея хорошая, надо поисследовать сначала, как это можно реализовать.
Закину пока на 4.1, на 4.0 и так очень много обновлений будет.

**Comment by Chinaski1** [comment]
Я закрываю данную задачу, поскольку она является дубликатом - https://github.com/AdguardTeam/CoreLibs/issues/217
