### ISSUE TITLE
sq.com.ua

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdguardForAndroid#3799]
@adguard-bot commented on [Tue Mar 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78884)

### Issue URL (Annoyance)
 [https://www.sq.com.ua/rus/news/novosti/29.03.2021/v_harkove_nashli_pryaniki_s_narkotikami/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.sq.com.ua%2Frus%2Fnews%2Fnovosti%2F29.03.2021%2Fv_harkove_nashli_pryaniki_s_narkotikami%2F)
### Comment
Username: @Spok1
> Дыра в футере

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/K9EpJyu.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.0
AdGuard product: | AdGuard for Android v3.6 (1)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `Нефильтрующий AdGuard DNS`<br>filters: `DNS-фильтр AdGuard`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Userscripts: | disabled

---

@Spok1 commented on [Fri Apr 02 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78884#issuecomment-812690272)

@zloyden,@stanislav-atr, посмотрите у себя.🤓

---

@zloyden commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78884#issuecomment-813104173)

Не повторяется.

---

@Spok1 commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78884#issuecomment-813254488)

Что делать будем?

---

@zloyden commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78884#issuecomment-813259836)

@Sergey-Lyapin еще посмотрит у себя. Если не повторится, перенеси задачу в репозиторий андроида.

---

@stanislav-atr commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78884#issuecomment-813266495)

@Spok1, @zloyden
<details><summary>Screenshot:</summary>

![Screenshot_2021-04-05-11-14-19-870_com android chrome](https://user-images.githubusercontent.com/68852737/113553267-2df30600-9600-11eb-9e65-aa87c3efe6b3.jpg)</details><br/>

**Comment by artemiv4nov** [comment]
@stanislav-atr а как вы тестили, на каком устройстве, браузере?

**Comment by stanislav-atr** [comment]
@artemiv4nov, я тестил с юзерконфигом в хроме, на MIUI 12.0.7.
@zloyden

**Comment by zloyden** [comment]
Проверил с юзерконфигом в хроме, дополнительно в ЯБе, но у меня девайс с 11 андроидом.

**Comment by Chinaski1** [comment]
Не повторяется с юзерконфигом в хроме на Android 7.

**Comment by ameshkov** [comment]
Ребят ну это же корлибс

**Comment by Spok1** [comment]
@Chinaski1, дополню отчёт: в режиме "для пк" отображается как у злого дэна, однако, при клике в край верхней грани, перенаправляет на др. страницу, в моб. адаптации же попадаю с пустоты на приложение из google play!😐

**Comment by Chinaski1** [comment]
@Spok1 Попробуйте обновиться до последней Nightly версии, будет ли повторяться проблема?
Ссылка для скачивания Nightly: agrd.io/android_nightly

**Comment by Chinaski1** [comment]
Поскольку пользователь длительное время не отвечает, я закрываю данную задачу.
Откройте её повторно, если проблема все еще повторяется на Nightly версии.
