### ISSUE TITLE
Log files are damaged while being sent to our server

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#38]
Sometimes we get something like that:

    06:39:43.824 [pool-5-thread-6] DEBUG c.a.a.f.f.FilteringHttpsProxyServer - TCP id1 First chunk length is 174
    06:39:43.824 [pool-5-thread-6] DEBUG com.adguard.commons.utils.TlsUtils - TCP id1 handShakeType = 1
    06:39:43.824 [pool-5-thread-6] DEBUG com.adguard.commons.utils.TlsUtils - TCP id1 size = 165
    06:39:43.824 [pool-5-thread-6] DEBUG com.adguard.commons.utils.TlsUtils - TCP id1 tlsVersion = 301
    06:39:43.824 [pool-5-thread-6] DEBUG com.adguard.commons.utils.TlsUtils - TCP id1 sessionIDLength 

For some reason TCP id=XXX string is damaged.

**Comment by Revertron** [comment]
For such error the qcrm is responsible. But I think that we should archive the logs before sending.
