### ISSUE TITLE
www.wonderzine.com

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdguardForAndroid#3800]
@adguard-bot commented on [Tue Mar 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78882)

### Issue URL (Annoyance)
 [https://www.wonderzine.com/wonderzine/life/experience/219201-congenital-melanocytic-nevus](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.wonderzine.com%2Fwonderzine%2Flife%2Fexperience%2F219201-congenital-melanocytic-nevus)
### Comment
Username: @Spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/o67tWLO.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.0
AdGuard product: | AdGuard for Android v3.6 (1)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `Нефильтрующий AdGuard DNS`<br>filters: `DNS-фильтр AdGuard`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Userscripts: | disabled

---

@Spok1 commented on [Fri Apr 02 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78882#issuecomment-812690682)

@zloyden,@stanislav-atr, проверьте.

---

@zloyden commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78882#issuecomment-813104189)

Не повторяется.

---

@Spok1 commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78882#issuecomment-813253832)

Что делать будем?🤔

---

@zloyden commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78882#issuecomment-813259871)

@Sergey-Lyapin еще посмотрит у себя. Если не повторится, перенеси задачу в репозиторий андроида.

---

@stanislav-atr commented on [Mon Apr 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78882#issuecomment-813270282)

@Spok1, @zloyden, 

<details><summary>Screenshot:</summary>

![Screenshot_2021-04-05-11-23-25-069_com android chrome](https://user-images.githubusercontent.com/68852737/113554097-752dc680-9601-11eb-9ad3-0d201f6aee22.jpg)
</details><br/>

**Comment by Chinaski1** [comment]
Fixed
https://github.com/AdguardTeam/AdguardFilters/commit/4c9d7c1661b99f16735001c07b8bea500cd2cd86
