### ISSUE TITLE
Anti-OS tracking

### ISSUE THREAD

**Issue by QuartzWarrior** [AdguardTeam/AdguardForAndroid#3801]
I am using the Latest nightly edition.

  I have seen that AdGuard blocks Amazon's tracking requests on my fire kindle and was thinking,"What if AdGuard blocked all of OnePlus's tracking app access to send data?"

  I am suggesting this for a premium feature because it seems premium to stop all tracking of your data from your OS developers. Also I was wondering if this was already a feature and I didn't know lol.

**Comment by artemiv4nov** [comment]
@QuartzWarrior Hi!
Please describe your idea a little bit more.

**Comment by QuartzWarrior** [comment]
A filter per Android company (Popular ones for probably). Example, for part of the OnePlus filter, block all requests from _com.oneplus.clipboard_. 

_com.oneplus.clipboard_ sends your clipboard to OnePlus if it contains certain words.

Also any other popular companies like Huawei that are known to take data and stop them from getting out.

**Comment by QuartzWarrior** [comment]
> It looks like we have to create our own AdGuard keyboard.

Wdym?

**Comment by artemiv4nov** [comment]
At first, I assumed you mean the clipboard data filtering by system applications. This type of data we can't control.

**Comment by QuartzWarrior** [comment]
No, I mean, by default to block access to send data (block its internet access) for those apps.

**Comment by artemiv4nov** [comment]
Ah, now I see. You can control it by disabling the Wi-Fi and Mobile access for application through Apps Management.

**Comment by QuartzWarrior** [comment]
Ok, thanks!
