### ISSUE TITLE
Add "MicrosoftEdge Canary" browser to the known browsers list

### ISSUE THREAD

**Issue by ganon69** [AdguardTeam/AdguardForAndroid#3807]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Dup of #3808
