### ISSUE TITLE
de.avm.android.fritzapp - VoIP/SIP issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3810]
@adguard-bot commented on [Fri Apr 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/80642)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=de.avm.android.fritzapp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dde.avm.android.fritzapp)
### Comment
Username: @tox1c90
> The app allows to make and receive phone calls from your landline number which is configured as VoIP/SIP account in the Fritzbox router (basically to use the smartphone as landline phone). 
> 
> Initially, it seems to work with Adguard enabled because incoming calls are signaled and you can both answer and start a call.
> But then no audio is transmitted. It shows no error and both caller and receiver act as if the connection is properly established, but it is just dead silent on both ends.
> 
> Filter protocol does not show any blocked connections. It is neither sufficient to exclude the app from filtering nor to exclude it from being routed through Adguard local VPN. 
> 
> Only way to get any audio transmitted is to completely disable Adguard. Any ideas why that could be?

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/sRDazSE.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/F3YMUTO.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v4.0 nightly 10 (50)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by Alex-302** [comment]
@tox1c90 Hi. Please collect debug logs and send to support@adguard.com
https://kb.adguard.com/en/android/solving-problems/log#collecting-debug-log

**Comment by ameshkov** [comment]
VPN (event a local one) and SIP cannot work together so it's natural.
