### ISSUE TITLE
Phone falls back to system default DNS even if a custom DNS is set in AdGuard

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3812]
### Issue Details

- **AdGuard version:**
  - 4.0 nightly 10
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Mi 9
- **Operating system and version:**
  - Android 11
- **Root access:**
  - Yes, via Magisk

### Expected Behavior

Setting up a custom DNS shouldn't cause the phone to fallback to system default

### Actual Behavior

Phone falls back to system default DNS even if a custom DNS is set in AdGuard

### Screenshots & Logs

See helpdesk ticket **Z504403**

**Comment by QingKongBaiYu** [comment]
> ### Issue Details
> * **AdGuard version:**
>   
>   * 4.0 nightly 10
> * **Filtering mode:**
>   
>   * Local VPN
> * **Device:**
>   
>   * Xiaomi Mi 9
> * **Operating system and version:**
>   
>   * Android 11
> * **Root access:**
>   
>   * Yes, via Magisk
> 
> ### Expected Behavior
> Setting up a custom DNS shouldn't cause the phone to fallback to system default
> 
> ### Actual Behavior
> Phone falls back to system default DNS even if a custom DNS is set in AdGuard
> 
> ### Screenshots & Logs
> See helpdesk ticket **Z504403**

this usually happens when update filters.

**Comment by techIndia-hacker** [comment]
Hi, go to advanced settings>low level>type "none" in pref.dns.fallback

**Comment by QingKongBaiYu** [comment]
> Hi, go to advanced settings>low level>type "none" in pref.dns.fallback
Already set.

**Comment by QingKongBaiYu** [comment]
> Hi, go to advanced settings>low level>type "none" in pref.dns.fallback

already set, same result.
it seems like adguard doesn't proxy itself (at least for dns).

**Comment by techIndia-hacker** [comment]
Miui version?
In vpn or auto proxy? Root access?

**Comment by QingKongBaiYu** [comment]
> Miui version? In vpn or auto proxy? Root access?

ROM: pixel experience
vpn mode,
using magisk 22.1.

**Comment by techIndia-hacker** [comment]
System certificate in the root certificate store I hope?

**Comment by QingKongBaiYu** [comment]
> Adguard certificate in the system certificate store I hope?

yes, it's moved with magisk module

**Comment by techIndia-hacker** [comment]
Give a screenshot of dns leak in filtering logs

**Comment by QingKongBaiYu** [comment]
> Give a screenshot of dns leak from filtering logs

there is nothing related in filter log.

**Comment by QingKongBaiYu** [comment]
> > Give a screenshot of dns leak from filtering logs
> 
> there is nothing related in filter log.

may because the dns queries is unfiltered.

**Comment by QingKongBaiYu** [comment]
> > > Give a screenshot of dns leak from filtering logs
> > 
> > 
> > there is nothing related in filter log.
> 
> It looks like the DNS filtering is turned off.

I'm pretty sure it's on, just not working when updating filters.

**Comment by techIndia-hacker** [comment]
> > Give a screenshot of dns leak from filtering logs
> 
> there is nothing related in filter log.

How do you know there is a dns leak then??

**Comment by techIndia-hacker** [comment]
![Screenshot_20210429-001918__01](https://user-images.githubusercontent.com/58086339/116457459-0e5aa080-a881-11eb-88ca-48728019fce2.jpg)

**Comment by QingKongBaiYu** [comment]
> > > Give a screenshot of dns leak from filtering logs
> > 
> > 
> > there is nothing related in filter log.
> 
> How do you know there is a dns leak then??

github is blocked in my country with dns pollution, I cannot update github rules without a custom dns. and there are no "github" dns queries in my adguardhome server log.

**Comment by QingKongBaiYu** [comment]
Please confirm whether adguard will use custom dns for its own request (for update filters or extensions).

**Comment by QingKongBaiYu** [comment]
> Please confirm whether adguard will use custom dns for its own request (for update filters or extensions).

maybe proxy is not used for its own request too.

**Comment by techIndia-hacker** [comment]
> Please confirm whether adguard will use custom dns for its own request (for update filters or extensions).

No

**Comment by QingKongBaiYu** [comment]
> > Please confirm whether adguard will use custom dns for its own request (for update filters or extensions).
> 
> No

so that's the reason

**Comment by QingKongBaiYu** [comment]
Adguard for Android does not apply dns setting (and proxy?) for it's own request.

maybe we should change the title or create a new issue.

**Comment by techIndia-hacker** [comment]
> > > Please confirm whether adguard will use custom dns for its own request (for update filters or extensions).
> > 
> > 
> > No
> 
> so that's the reason

However in pc, adguard users custom dns for filter updates and other network activity but in Android adguard can't route it's own traffic through its own vpn

**Comment by artemiv4nov** [comment]
@QingKongBaiYu Another reason is upstreams have miswritten. Can you re-check them, please?

**Comment by QingKongBaiYu** [comment]
> @QingKongBaiYu Another reason is upstreams have miswritten. Can you re-check them, please?

the same configuration(exclude dns) works when I set a private dns in Android setting (which should handle all dns request), but  doesn't work when I set it in adguard.

**Comment by artemiv4nov** [comment]
@QingKongBaiYu What Android versions on do you check the configuration?

Since Android 9 the "private DNS" system setting conflicts with our DNS server and you should disable the private DNS totally.

**Comment by QingKongBaiYu** [comment]
> @QingKongBaiYu What Android versions on do you check the configuration?
> 
> Since Android 9 the "private DNS" system setting conflicts with our DNS server and you should disable the private DNS totally.

android 11.
Private dns is always turned off manually when using adguard dns filter.

**Comment by QingKongBaiYu** [comment]
It can be easily checked with a self-host dns server: 
1. setup the dns filter
2. add a filter with special domain (It doesn't matter whether it's real or not) 
3. try to update filter
4. check the query logs on your server.
if the domain not exist, this is obviously a bug of adguard.

**Comment by Chinaski1** [comment]
@QingKongBaiYu 

When the filters are updated, the protection is restarted that is why this situation occurs.
You can switch AdGuard on Always-on VPN in the Android settings, then it will not happen.

**Comment by QingKongBaiYu** [comment]
> @QingKongBaiYu
> 
> When the filters are updated, the protection is restarted that is why this situation occurs.
> You can switch AdGuard on Always-on VPN in the Android settings, then it will not happen.

update all other filters and then update again, adguard will not restart but the update still failed.
if you have a self-host dns server, you can test with the method above.

**Comment by QingKongBaiYu** [comment]
> It can be easily checked with a self-host dns server:
> 
> 1. setup the dns filter
> 2. add a filter with special domain ( ~It doesn't matter whether it's real or not~ cannot add filter if not exist )
> 3. try to update filter
> 4. check the query logs on your server.
> 
> if the domain not exist, this is obviously a bug of adguard.

filter link: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
result on my server:
**NOTICE that the local time is 20:08! when i update filters**
![image](https://user-images.githubusercontent.com/45838887/118486252-fbcedb00-b74b-11eb-8159-773d5272a3b6.png)

**Comment by Chinaski1** [comment]
> Adguard for Android does not apply dns setting (and proxy?) for it's own request.
> 
> maybe we should change the title or create a new issue.

The point is that for technical reasons we cannot filter our own requests.

**Comment by QingKongBaiYu** [comment]
> > Adguard for Android does not apply dns setting (and proxy?) for it's own request.
> > maybe we should change the title or create a new issue.
> 
> The point is that for technical reasons we cannot filter our own requests.

thanks for the reply, any plan to fix it?

**Comment by Chinaski1** [comment]
It is not possible to implement this functionality.

**Comment by techIndia-hacker** [comment]
I think if there is a possibility to update filters without vpn or proxy
restart

**Comment by QingKongBaiYu** [comment]
> It is not possible to implement this functionality.

sad to know this😥

**Comment by QingKongBaiYu** [comment]
> I think if there is a possibility to update filters without vpn or proxy restart

may not possible, but adguard should wait for all filters update to complete and then restart instead of interrupting the update.

**Comment by artemiv4nov** [comment]
> > I think if there is a possibility to update filters without vpn or proxy restart
> 
> may not possible, but adguard should wait for all filters update to complete and then restart instead of interrupting the update.

A comment is related to another task #3849
