### ISSUE TITLE
Expose AG Userscripts via Extensions

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#3814]
### Problem Description
I recently revisted https://www.github.com/AdguardTeam/Userscripts/tree/master/ & now found a number of interesting AG-developed userscripts, but, when I go to AG app menu » Settings » Extensions, I see only [_Disable AMP_](https://github.com/AdguardTeam/DisableAMP) & [_AdGuard Extra_](https://github.com/AdguardTeam/AdGuardExtra).

### Proposed Solution
Have these listed in Extensions, default disabled (like _Disable AMP_), maybe via a subscription (i.e., whenever new script added, this list auto-updates)?  Add whatever disclaimers needed.

### Alternatives Considered
These could be added manually, but it's easier to have a toggle option.
Or, a link to a safer userscripts directory, if AG Android does intercept & install directly.

**Comment by Chinaski1** [comment]
Hello!

Scripts from [this repository]( https://www.github.com/AdguardTeam/Userscripts/tree/master/ ) are obsolete and will not be updated for a number of reasons(at least in the near future). 
While AdGuard Extra and Disable AMP scripts are constantly being updated. 
This is why they are the basic scripts in most AdGuard products.

In any case, you can add any custom scripts to the list at your discretion.

**Comment by TPS** [comment]
Maybe archive that repo, then, to make its obsolescence obvious?

Thanks for clarifying!
