### ISSUE TITLE
 use proxy function to proxy dns 

### ISSUE THREAD

**Issue by pongfcnkl** [AdguardTeam/AdguardForAndroid#3815]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ √ ] I am running the latest version

- [ √] I checked the documentation and found no answer
- [√ ] I checked to make sure that this issue has not already been filed

### Problem Description
Use AdguardForAndroid's proxy function to proxy dns 

### Proposed Solution
Proxy dns together 

### Alternatives Considered
Proxy dns

### Additional Information
China will hijack dns, for example, google will hijack to 127.0.0.1, resulting in inaccessibility, and proxy dns is required 

![photo_2021-04-28_19-33-56](https://user-images.githubusercontent.com/24273319/116397192-e22b2980-a858-11eb-850f-3753896af23d.jpg)
![photo_2021-04-28_19-33-58](https://user-images.githubusercontent.com/24273319/116397291-038c1580-a859-11eb-8ac8-6e1af5244c3b.jpg)

**Comment by anastenko** [comment]
Hello.

We're already working on this feature. Here's the [task](https://github.com/AdguardTeam/DnsLibs/issues/102) created.

**Comment by pongfcnkl** [comment]
@anastenko 
No, I mean socks5 can proxy dns instead of going to dns settings

**Comment by sfionov** [comment]
So you want to proxy DNS queries without DNS blocking?

This will be possible when that task will be done.

Now you can use DNS filtering tab without DNS blocking, to redirect DNS queries to any plain DNS server (e.g. "AdGuard unfiltered" plain DNS).

After adding proxy support to DNS filtering module, these requests will be directed through proxy server.
