### ISSUE TITLE
Remove duplicate filters on configuration import (by url)

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#3817]
We should remove duplicate filter lists on import.

**Comment by infinitewaveparticle** [comment]
I, too, have requested this and even went further to request a service like realityripple.com

**Comment by artemiv4nov** [comment]
Sorry for the bot's miss.
This task has been planned for the AdGuard 4.0 version.

**Comment by artemiv4nov** [comment]
Done in the 4.0 version
