### ISSUE TITLE
Test Adguard's HTTPS filtering compatibility with popular apps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#382]
**How to test:**
1. Install the app or clear app data and cache
2. Sign in
3. Navigate there a bit, check main features

**What to check:**
Check that everything work flawlessly. If you see some random error (during sign in for instance) that is fixed on the second retry - it is a bad sign. It may mean that Adguard failed the first attempt to filter SSL and just added that domain name to temporary exceptions.

**The list of apps to test:**
Facebook
Facebook Messenger
Facebook Lite
Twitter
Instagram
Tinder
Snapchat
Whatsapp
Telegram
Gmail
Inbox
VK
OK
Mail.ru
Yandex Disk
Google Drive
Cloud Mail ru
OneDrive

**Comment by gshumihin** [comment]
Tested latest beta with android 5.1.1. All apps works normal for me, all ads seemed to be blocked.

**Comment by ameshkov** [comment]
Ehm, I don't know how you tested, but for some of these apps we have known issues with HTTPS filtering.

**Comment by gshumihin** [comment]
Facebook Lite won't load with https filtering enabled. And missed ads in twitter ofc. Also Yandex.disc wont sync at all.

**Comment by ameshkov** [comment]
@gshumihin 
1. We need their package names
2. Please check how Facebook works if you move our certificate to the system store.

**Comment by gshumihin** [comment]
Here's apps package names:
- com.facebook.lite 
- ru.yandex.disk

**Comment by gshumihin** [comment]
After i deleted com.facebook.katana and moved Adg's cert to the system store, I've got this notification:
<img src="https://www.dropbox.com/s/joy9o4fqmytnpkt/2016-04-13%2015.27.05.png">

**Comment by ameshkov** [comment]
Create a separate issue for Facebook.

Add this screenshot.
Also attach a debug log of that failed login attempt.

I suppose the problem is not in our domain certificate, but in the fact that facebook uses client certificate authorization.

**Comment by ameshkov** [comment]
@gshumihin we are close to release, so let's re-test it.

**Comment by gshumihin** [comment]
The only issue i find out today is #498
