### ISSUE TITLE
Cosmote Greek carrier vowifi blocking

### ISSUE THREAD

**Issue by nicolassp** [AdguardTeam/AdguardForAndroid#3821]
It seems that Adguard blocks Cosmote vowifi calling.

It would be resolved for all Cosmote users if you enhance the exclusion list with the following ip ranges

94.143.176.242
94.143.177.210
94.143.178.220

Or

94.143.176.0/24
94.143.177.0/24
94.143.178.0/24

It refers to epdg.epc.mnc001.mcc202.pub.3gppnetwork.org

**Comment by nicolassp** [comment]
@Chinaski1  also on this matter, i think that it should be on the default exclusion list

**Comment by Chinaski1** [comment]
Hello!

This issue can be solved by adding specified domains to pref.ipv4.routes.excluded in low-level settings.
Try this method and please let me know the result.

**Comment by nicolassp** [comment]
@Chinaski1  it is solved that way. But it would be nice for other users to be excluded by default i think

**Comment by nicolassp** [comment]
@Chinaski1 

If you think that is right instead of creating new issues, i would like to mention

Vodafone Greece epdg server
epdg.epc.mnc005.mcc202.pub.3gppnetwork.org

With network 62.74.30.0/24

Thank you

**Comment by nicolassp** [comment]
@Chinaski1 So it will be fixed for both Cosmote Greek Carrier and Vodafone Greek carrier at 4.0 version?

**Comment by nicolassp** [comment]
@ameshkov i think that it has to be included at 3.6.3 as the v4 will take some time to be released. Is it possible?

**Comment by ameshkov** [comment]
Yeah, you're right.
