### ISSUE TITLE
Stoiximan application unusable with adguard

### ISSUE THREAD

**Issue by nicolassp** [AdguardTeam/AdguardForAndroid#3822]
Exclude gr.stoiximan.sportsbook apk from filtering as it is not usable when adguard for android is enabled.

**Comment by Chinaski1** [comment]
Hello!

Unfortunately, I can't find an app with this ID
Could you send me the link to the PlayStore?
Does the application you mentioned not operate regardless of the AdGuard settings you selected?

**Comment by nicolassp** [comment]
@Chinaski1  it is outside google play.

https://www.stoiximan.gr/arthro/efarmogi-android/276309/

And you download the sportsbook application.

It seems that it may block some requests that app does. Initially and gradually, the application slows down in terms of performance. Then some components do not work and eventually it is unusable.

When disabling adguard, the problem does not persist

**Comment by Chinaski1** [comment]
At first glance, the app works without any issues (using the standard settings)
If you have problems using it, simply exclude it from filtering in Apps Management
I don't think it makes sense to exclude it by default.

**Comment by nicolassp** [comment]
@Chinaski1 will do that manually then. Thank you very much
