### ISSUE TITLE
Unable to login to MEGA account

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardForAndroid#3825]
I am not able to login to my MEGA account on Android 10 tablet when AdGuard 3.6.1 is running. AdGuard log does not show any blocked traffic during login process. I use AdGuard as local proxy with a 3rd party VPN and AdAway hosts-based blocking. 

VPN + AdGuard DNS + AdAway = successful login to MEGA
VPN + AdGuard DNS = successful login to MEGA
VPN + VPN DNS + AdAway = successful login to MEGA
VPN + VPN DNS = successful login to MEGA
VPN + AdGuard App (any DNS) with/without AdAway = unable to login

I have not tried to use AdGuard App without VPN due to privacy concerns.

**Comment by Chinaski1** [comment]
Hello there!

AdGuard DNS feature cannot be used with local HTTP proxy mode.
When this mode is activated, the AdGuard DNS section becomes inactive.
Or have you set a DNS address in the Android system settings?

**Comment by Chinaski1** [comment]
The issue does not seem to be DNS-related.
I managed to reproduce your issue and created a new task.
You can follow the solution [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/3837)
