### ISSUE TITLE
Adapt the dns results from Nextdns

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3826]
can you guys compatible with dns results from nextdns? thx

![IMG_20210503_053755.jpg](https://user-images.githubusercontent.com/75058881/116828637-83f0a480-abd2-11eb-858b-eb7d6854cdc0.jpg)

![IMG_20210503_053826.jpg](https://user-images.githubusercontent.com/75058881/116828635-7f2bf080-abd2-11eb-9d52-bf6baba6c61e.jpg)

https://github.com/nextdns/

(google translate~)

**Comment by c2xusnpq6** [comment]
mark it as `blocked` or `blocked by nextdns`?

**Comment by Chinaski1** [comment]
Hello!

Requests are marked as blocked if they are blocked by a DNS filter and not by the selected DNS server.
[Here's a](https://uploads.adguard.com/Chinask196268.png) blocked analytical query by AdGuard DNS, for example.
As you can see the request is blocked (0.0.0.0) but remains marked Processed.
