### ISSUE TITLE
Adguard blocks connection over LAN (KDE Connect)

### ISSUE THREAD

**Issue by qumberrizvi** [AdguardTeam/AdguardForAndroid#3827]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.1 (11)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 6T
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

Running `netcat -z -v 192.168.1.35 1716` (where `192.168.1.35` is my Phone's IP over same WiFi network & 1716 is the port where `kdeconnectd` is listening) should show successful connection regardless of Adguard's status.

### Actual Behaviour

When I try to connect to my phone from my Manjaro PC using out of the box KDE Connect, my doesn't show up on available devices when Adguard is on.
Running `netcat -z -v <phone-ip> <kdeconnect-port>` results in refused connections when Adguard is on.
As soon as I turn off Adguard, the following output appears for the aforementioned command:
```
Android.local [192.168.1.35] 1716 (xmsg) open
```
Similarly, when Adguard is on, running `kdeconnect-cli -l` to list available devices returns `0 devices`. But, when Adguard is off, the following output appears for the same command:
```
- OnePlus 6T: 31809fb40923ef4b (reachable)
1 device found
```

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/12488086/116905317-6ff18500-ac5c-11eb-9eba-19066fd000d7.png)

</details>

### Additional Information

Before trying to reproduce the issue, please ensure that your device is unpaired in KDE Connect, you are connected to the same network, you have Adguard Android and enabled, and you have KDE Connect app installed on your Android.

**Comment by Chinaski1** [comment]
Hello there!

You can try to add a custom filtering rule - `@@||192.168.1.35:1716$Network` in the Content blocking section.
But I'm afraid this may not work as the local VPN could potentially break inbound connections.

**Comment by Chinaski1** [comment]
I closing the task as the user is not responding.

**Comment by qumberrizvi** [comment]
I would try it out this weekend and post the outcome. Thanks.
