### ISSUE TITLE
How to block a TCP/UDP protocol IP addr?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3828]
I tried `tcp://{ip}` but it doesn't work...

**Comment by Chinaski1** [comment]
Hello @c2xusnpq6 

You should try to use *$network* modifier at the end of the rule
More information about syntax rules can be found in our [knowledge base](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier).

**Comment by Chinaski1** [comment]
I closing the task as the user is not responding.
