### ISSUE TITLE
Add proxy PAC script support

### ISSUE THREAD

**Issue by depler** [AdguardTeam/AdguardForAndroid#3830]
It would be very useful to have ability to set proxy as PAC script, like in desktop OS. Then it will be possible to filter requests on domain basis.

**Comment by Chinaski1** [comment]
Hello @depler 

We plan to add support for proxy PAC in the near future.
Here is the [link](https://github.com/AdguardTeam/CoreLibs/issues/217) to the primary task.

This request will be closed as a duplicate.
