### ISSUE TITLE
Adguard not appearing in launcher's recent app list

### ISSUE THREAD

**Issue by sumanth-98-dev** [AdguardTeam/AdguardForAndroid#3833]
### Issue Details

- **AdGuard version:**
  - 3.6.1 (11)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus Nord
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

Adguard should persist in recent apps list

### Actual Behavior

Adguard isn't persisting in recent apps list. It's getting removed as soon as the app is closed

### Screenshots

I don't have any apps in recents. I'm opening and closing adguard. When I'm checking again, it's not there in recents apps list.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24863030/55941223-6ce36080-5c5f-11e9-8695-9184de09690a.gif)

</details>

### Additional Information

I've tested with various launchers. Not specific to OnePlus launcher.

**Comment by sumanth-98-dev** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2702

**Comment by anastenko** [comment]
Hello.
So it happens only with AdGuard app and other apps work fine? It looks like some specific settings of your device.

**Comment by sumanth-98-dev** [comment]
It's happening only for Adguard. I've tried in another OnePlus device as well with various launchers. But  in Pixel devices, adguard is persisting in recent apps list. Looks like a OnePlus specific issue

**Comment by anastenko** [comment]
Yeah, as I can see there are lots of issues with Oneplus battery optimization, etc. You might try some of [these solutions](https://dontkillmyapp.com/oneplus).

**Comment by anastenko** [comment]
@sumanth-98-dev Any news? Did you try it?

**Comment by sumanth-98-dev** [comment]
I've tried those solutions but they didn't work.

**Comment by anastenko** [comment]
Sad to hear that. I'm afraid that we can't do anything at this point, since it's obviously a OnePlus system issue.

**Comment by mario0318** [comment]
I've the same exact issue, on LineageOS 15.1 on an LG K20Plus. However, what I find is that opening the app via the quick settings icon doesn't keep the app in recents upon exiting. I would have to launch the app via the launcher shortcut for it to remain in recents.
