### ISSUE TITLE
Aguard interferes with FTPS

### ISSUE THREAD

**Issue by terrytw** [AdguardTeam/AdguardForAndroid#3835]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

- **AdGuard version:**
  - nightly 
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Oneplus 5T
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Expected Behavior

Connect to a FTPS server

### Actual Behavior

Cannot connect to FTPS server, error: connection reset by peer

### Additional Information

My FTPS server is behind a router. I have port forwarded from router to FTPS server. 
When connecting from outside network, with Adguard on, connection fails. 
When connecting from outside network, with Adguard off, connection succeeds. 
When connecting from the same local network, connection succeeds with Adguard on.

**Comment by terrytw** [comment]
@Chinaski1 
Hi, I just tried exclude the server from filtering using your instruction, the result is the same.

**Comment by Chinaski1** [comment]
I investigated your issue in more detail and can say that this is the expected behavior of the application.
We will be releasing release 4.0 shortly. in which this situation is likely to be reviewed.
Let's return to the issue after the release

**Comment by Chinaski1** [comment]
After analyzing your request I can tell you that the only way to solve this issue is to exclude IP addresses in the **low-leve**l settings of the application:

- pref.ipv6.routes.exclusions
- pref.ipv4.routes.exclusions

**Comment by terrytw** [comment]
Thank you for your time.

However there is one more problem, my server does not have a fixed IP address, I connect to it using DDNS service. I tried to use DDNS domain in the low-level settings, and it does not seem to work.

Is it possible to add support for DDNS domain name in pref.ipv6.routes.exclusions and pref.ipv4.routes.exclusions?

**Comment by Chinaski1** [comment]
Unfortunately, this is not possible :(
