### ISSUE TITLE
AdGuard prevents MEGA app from logging in

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3837]
### Issue Details

- **AdGuard version:**
  -  Nightly 4.0(14)
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Google pixel 3
- **Operating system and version:**
  -  Android 11
- **Root access:**
  -  No
-  **Time in logs:** 17:00-17:52

[Play Store](https://play.google.com/store/apps/details?id=mega.privacy.android.app&hl=en&gl=US)

**Comment by EntropySmoke** [comment]
In the closed thread you mention that AdGuard DNS does not work in HTTP Proxy Auto-mode. That is not true, at least not for DNS-over-HTTPS SDNS addresses I manually configure for AdGuard:
sdns://AgEAAAAAAAAADDk0LjE0MC4xNC4xNAAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk
sdns://AgEAAAAAAAAADDk0LjE0MC4xNS4xNQAPZG5zLmFkZ3VhcmQuY29tCi9kbnMtcXVlcnk

The issue of AdGuard DNS not working in HTTP Proxy Auto-mode may be specific to Android 11 as someone mentions here - https://github.com/AdguardTeam/AdguardForAndroid/issues/3791 and AdGuard 3.6.2, supposedly, fixes it.

MEGA works if AdGuard is simply disabled for the application. There is no need to fully disable AdGuard. I don't know the cause. Developers may have to whitelist MEGA somehow.

**Comment by Chinaski1** [comment]
@EntropySmoke 
Thank you for extending the task with your observations.
We will certainly take this into account.

**Comment by admitrevskiy** [comment]
Can't reproduce with the latest version of Mega app and the latest AdGuard nightly.
I'm not sure on which side it has been fixed, but looks like everything works fine. @Chinaski1 re-open this issue if needed.

https://github.com/AdguardTeam/AdguardForAndroid/issues/3837#issuecomment-840734020
AdGuard DNS does not work in HTTP Proxy `manual`-mode. And there are some issues with IPv6 DNS traffic in HTTP Proxy `Auto`-mode
