### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3839]
If the website is a content farm, then jump to the reminder page, click "Continue" to continue to visit the page @sfionov thx!

You can refer to this:
https://chrome.google.com/webstore/detail/content-farm-terminator/lcghoajegeldpfkfaejegfobkapnemjl

https://github.com/danny0838/content-farm-terminator

https://github.com/danny0838/content-farm-terminator/tree/gh-pages

> You may request author the userscript version of this extension, after that you may add it to AdGuard as userscript.

but not via userscript, via adguard.... thx 😅

https://github.com/AdguardTeam/AdguardForWindows/issues/3786

**Comment by sfionov** [comment]
Please stop creating duplicate tasks, we don't have plans to implement such thing.

**Comment by c2xusnpq6** [comment]
I added something new btw............ 

> but not via userscript, via adguard.... thx 😅

> https://github.com/AdguardTeam/AdguardForWindows/issues/3786
