### ISSUE TITLE
Allow sorting of the apps in Firewall section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#384]
For instance, sort by bandwidth saved.

From XDA:
https://forum.xda-developers.com/showpost.php?p=74839356&postcount=2939

> Please allow overriding the sort order of the application list. E.g. Sort applications by
> - name (a-z, z-a),
> - size (sml-lrg, lrg-sml),
> - date installed/upgraded (new-old, old-new),
> - traffic used (Wi-Fi / Data),
> - traffic blocked.

**Comment by hertill** [comment]
Also sorting by name would be helpful to, e.g., quickly find a newly installed app and disable it's Internet access.

**Comment by TPS** [comment]
@adguardTeam Closely related to #201, I think, so maybe implement simultaneously?

**Comment by ameshkov** [comment]
Yep, it will be.

**Comment by TPS** [comment]
& sorting by install date/time to partially satisfy #478.

**Comment by nkartyshov** [comment]
added, adguard-android/pull-requests/442

**Comment by nkartyshov** [comment]
done

**Comment by karina-archazh** [comment]
In App Managment in sorting dialog window fix reverse sorting (from z-a in app name, from sml -large in data usage, from sml -large in blocked count, from sml -large in total requests).

**Comment by nkartyshov** [comment]
fixed
