### ISSUE TITLE
about trusted filters

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3840]
There is a `mark as trusted filter list` but no `mark as $network or $app filter list`
I want to use [>>>this filter list<<<](https://github.com/stamparm/ipsum/blob/master/levels/4.txt) as a IP blacklist. That is, add `$network` or `$app` or `$cookie`......... at the end of each line

https://github.com/stamparm/ipsum
https://github.com/stamparm/ipsum/tree/master/levels
https://github.com/stamparm/ipsum/blob/master/levels/4.txt

**Comment by c2xusnpq6** [comment]
like this one....

I want to lookup the `whois` info for this domain, but if the URL contains the string "umeng.com", Adguard will block it instead of treating it as a domain-based filter list

can I just... mark as `$hosts`?

![image](https://user-images.githubusercontent.com/75058881/118190136-3f3bf780-b475-11eb-91c8-21b102d0e351.png)

**Comment by Chinaski1** [comment]
Simply add this filter to the list of DNS filters
