### ISSUE TITLE
add/edit http packet header

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3841]
I want to add "dnt: 1" and "save-data: on" to each packet to be sent

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT

**Comment by Chinaski1** [comment]
We have no plans to add this functionality to the AdGuard app.
