### ISSUE TITLE
DNS-over-QUIC (Remove "experimental" marking)

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3842]
**Adguard 3.6.2 для Android**

<a href="https://fastpic.ru/view/114/2021/0513/4470f60827adaed942db024605b3cd1f.jpg.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0513/1f/4470f60827adaed942db024605b3cd1f.jpeg" border="0"></a>

**Adguard 7.6.1 для Windows**

<a href="https://fastpic.ru/view/114/2021/0513/54fcdeaebbc6586e9c1745e42aa93d6a.png.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0513/6a/54fcdeaebbc6586e9c1745e42aa93d6a.jpeg" border="0"></a>

Как правильно воспринимать **DNS-over-QUIC** ( **experimental** или нет )?

**Comment by c2xusnpq6** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/3842

**Comment by c2xusnpq6** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/3784

**Comment by Chinaski1** [comment]
DNS-over-QUIC вышел из экспериментального режима, уберем данную приписку в следующем обновлении.
