### ISSUE TITLE
Russian server!

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3843]
I found out that Adguard is using a Russian server... For the benefit of Adguard users, can you stop using a Russian server?

https://www.virustotal.com/gui/domain/adguard.com/relations

https://www.virustotal.com/gui/domain/agrd.io/relations

https://www.virustotal.com/gui/domain/adtidy.org/relations

Or... Adguard_RU allows me to store my data on servers in the European Union?? thx and sorry for the google translated english

**Comment by c2xusnpq6** [comment]
I choose to share usage data with Adguard because I like Adguard and I agree with Adguard’s philosophy

but... you are using server in RU? not US, not EU....... RU??????????????

**Comment by c2xusnpq6** [comment]
T.T

**Comment by Chinaski1** [comment]
AdGuard does not use servers located in Russia.
