### ISSUE TITLE
HTTP proxy + Root slowdown on Android 7

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3844]
Originally reported here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2977#issuecomment-839727959

**Comment by ameshkov** [comment]
@patrickdrd we'll publish a new nightly version this week, it should fix this issue of yours.

**Comment by patrickdrd** [comment]
got it, thanks

**Comment by artemiv4nov** [comment]
@patrickdrd Hi!
Did you check the nightly version? Do you have any issues with it?

**Comment by patrickdrd** [comment]
there were issues with 4.0.60 but they were fixed in 4.0.61
