### ISSUE TITLE
Russian server? (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3845]
> AdGuard doesn't have servers located in Russia.

> Could you provide information to the contrary?

https://search.censys.io/search?resource=hosts&q=%28%22adguard.com%22+or+%22agrd.io%22+or+%22adtidy.org%22+or+autonomous_system.name.raw%3A+%60ADGUARD%60%29+and+%28location.country_code%3A+RU+or+location.registered_country_code%3A+RU%29

https://fofa.so/result?qbase64=KCJhZGd1YXJkLmNvbSIgfHwgImFncmQuaW8iIHx8ICJhZHRpZHkub3JnIiB8fCBjZXJ0LnN1YmplY3Q9IkFkZ3VhcmQgU29mdHdhcmUgTGltaXRlZCIpICYmIGNvdW50cnk9IlJVIg%3D%3D

https://www.zoomeye.org/searchResult?q=(%22adguard.com%22%20%22agrd.io%22%20%22adtidy.org%22%20organization%3A%22adguard.com%22)%20%2Bcountry%3A%22RU%22

https://quake.360.cn/quake/#/searchResult?searchVal=%28%22adguard.com%22%20or%20%22agrd.io%22%20or%20%22adtidy.org%22%29%20AND%20country%3A%20%22Russia%22&selectIndex=quake_service&latest=false&ignore_cache=false&exclude_honeypot=false&timeRange=2020-05-13%2016%3A00%3A00&timeRange=2021-05-14%2015%3A59%3A59&t=1621011236962

https://github.com/AdguardTeam/AdguardForAndroid/issues/3843

> Or... Adguard_RU(?) allows me to store my data on servers in the European Union?? thx and sorry for the google translated english

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118304365-2b49d180-b519-11eb-9872-430ab58f77a7.png)

**Comment by c2xusnpq6** [comment]
I am a paid user, can you let me ~put~ store my data on servers in the European Union? thx

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118351250-769dc780-b58d-11eb-99e6-343b916efe3f.png)

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118351279-9d5bfe00-b58d-11eb-8a3f-bf5d3c851b7e.png)

**Comment by c2xusnpq6** [comment]
and you may ~need~ want to explain the relationship between Adguard and China
![image](https://user-images.githubusercontent.com/75058881/118351969-730c3f80-b591-11eb-9487-6550f51f8dd4.png)

**Comment by c2xusnpq6** [comment]
Why do I want you to explain? Because I gave you a lot of strength, such as... trusted Adguard's SSL certificate to filtering my packets?

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/118355981-a3f66f80-b5a5-11eb-8e97-603200505fcb.png)

**Comment by c2xusnpq6** [comment]
The packets will pass through Cloudflare and finally reach the server in Russia

**Comment by ameshkov** [comment]
The place where IP addresses are registered and the server's location are two very different things.

In order to figure out where the server is located, do a simple thing: run `traceroute IPADDR`, look at the last hops, this route will show you where the servers are located.

**Comment by c2xusnpq6** [comment]
> The place where IP addresses are registered and the server's location are two very different things.
> 
> In order to figure out where the server is located, do a simple thing: run `traceroute IPADDR`, look at the last hops, this route will show you where the servers are located.
> 
> Spoiler: AdGuard servers are currently located in Webzilla's Amsterdam data center.

GREAT~~~~~~

RISKY NO MORE~~~ If you are telling the truth...............................................................................

**Comment by c2xusnpq6** [comment]
> Spoiler

you mean me?? haha!! very interesting~ I hate CN more than RU, I like RU more than CN. but Adguard really... REALLY taking control of my internet life, ~~my~~our most important thing, like decrypting https packets.... so... explaining these thing is needed.
because you guys never say those thing to ~~users~~people ACTIVELY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by c2xusnpq6** [comment]
and I hope Adguard can take the initiative to tell people things like that next time, instead of users asking for it. I love using Adguard, and I really hope Adguard be better, because it can be.

**Comment by ameshkov** [comment]
Spoiler as in "Spoiler Alert": https://www.yourdictionary.com/spoiler-alert

Spoiler=剧透

**Comment by c2xusnpq6** [comment]
> Spoiler as in "Spoiler Alert": https://www.yourdictionary.com/spoiler-alert
> 
> Spoiler=剧透

> and I hope Adguard can take the initiative to tell people things like that next time

todo list already? or not yet? or NO! ?
