### ISSUE TITLE
userupload.in [Fake Button]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#3846]
https://userupload.in/56l6effqq87c

Please remove the fake "Download Netflix Mod" button in red. Checked with AG for Android on Chrome.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardFilters #83416](https://github.com/AdguardTeam/AdguardFilters/issues/83416) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardFilters #83417](https://github.com/AdguardTeam/AdguardFilters/issues/83417) via [**ZenHub**](https://www.zenhub.com/)
