### ISSUE TITLE
Low-Level Settings - Pref.DNS.Blocking.Type - Options 2 and 3 are identical

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardForAndroid#3847]
Low-Level Settings - Pref.DNS.Blocking.Type
0 - ...
1 - ...
2 - Means block requests with Unspecified IP for all kinds of filtering rules.
3 - Means block requests with Unspecified IP for all kinds of filtering rules.
4 - ...

What is the difference? between option 2 and 3? They may be different, but their description is identical.

I also don't understand the lowest "Pref.Boot.Startup.Delay" value, which is  "-1". How can you have a negative delay? I assume "-1" means AdGuard loads before booting begins or during very early stages of the booting process.

**Comment by anastenko** [comment]
@EntropySmoke 
2 - Blocks via Unspecified IP
3 - Blocks with custom IP address, which is Unspecified IP by default
But for objective reasons functional 3 wasn't implemented, so they have the same description.

Value less than zero indicates that there will be no waiting.
