### ISSUE TITLE
Check proxy connection status error

### ISSUE THREAD

**Issue by ExcellentHzj** [AdguardTeam/AdguardForAndroid#3848]
device:Xperia 5 II
Android version:11
Adguard for android version:v3.6.2 (23)
details:Use other proxy app like shadowsocks work with adguard can't check connection status,it's always show "unable to connect to proxy"
![Screenshot_20210516-182101](https://user-images.githubusercontent.com/38839476/118393815-98717a00-b673-11eb-91b6-13a6ab838ecc.png)

**Comment by Chinaski1** [comment]
Hello!

Please clarify if you have excluded Shadowsocks from filtered applications?
Does the issue recur regardless of the server selected?

**Comment by ExcellentHzj** [comment]
> Hello!
> 
> Please clarify if you have excluded Shadowsocks from filtered applications?
> Does the issue recur regardless of the server selected?

@yes,it

**Comment by ExcellentHzj** [comment]
> Hello!
> 
> Please clarify if you have excluded Shadowsocks from filtered applications?
> Does the issue recur regardless of the server selected?

Yes,the proxy function is running corretly,just the check connection status notification is not ture.

**Comment by Sinsstranger** [comment]
I have this problem too.

**Comment by ameshkov** [comment]
@Sinsstranger could you please try on AdGuard nightly version? https://adguard.com/beta.html

**Comment by artemiv4nov** [comment]
@ExcellentHzj @Sinsstranger Hello!
Any news?

**Comment by ExcellentHzj** [comment]
> @ExcellentHzj @Sinsstranger Hello!
> Any news?

latest nightly version fixed it.
