### ISSUE TITLE
Samsung Galaxy apps does not allow encrypted data filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#385]
Здравствуйте!  На телефоне Samsung установлен Adguard 3.5.39 alfa. Включена фильтрация по https. При входе в приложение Galaxy apps  (предустановленный магазин приложений от Samsung) появляется окно с сообщением о проблеме с доступом и сертификатом (скриншот). Если несколько раз нажать повтор, то это окно исчезает и можно дальше работать в приложении. Если отключить adguard, окно с сообщением о проблеме с доступом не появляется
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13991425/c6f7c0a0-f120-11e5-81ff-46de7a129be1.png)
</details>

Перезагружал телефон, чистил кэш. Зашел в доверенные сертификаты, а там 3 сертификата Adguarg Personal CA. Видимо остались после предыдущих альфа-версий. Удалил их. Работа Galaxy app и вход в Samsung  account возобновились. Пока проверяю. Вход в Samsung account осуществляется не сразу, приходится нельско раз делать повтор. Без этого работа в магазине Galaxy apps затруднена. 
По вашим вопросам (до удаления сертификата):
1. В 4G работал, по Wi-Fi не входил в Samsung account из-за это возникали проблемы с работой магазина приложений  Galaxy apps.
2. В VPN проблема сохранялась, в режиме прокси работает.

Логи: NDT-848-88505

**Comment by ameshkov** [comment]
А какой у Galaxy Apps package name?

**Comment by ameshkov** [comment]
@evgeniy-ADG вроде нашел:
com.sec.android.app.samsungapps

Проще будет в список исключенных из HTTPS фильтрации приложений добавить.
Сделаем.
