### ISSUE TITLE
Не работает объединённый фильтр (несколько хостов) для дезактивации антитрекинга.

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3850]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
3.6.1
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Expected Behavior

Нужно, чтоб фильтр дезактивации антитрекинга работал для перечисленных в нём через запятую хостов.

### Actual Behavior

Объединённый фильтр @@||4pda.to,4pda.ru^$stealth для дезактивации антитрекинга не работает. Работают только отдельные фильтры @@||4pda.ru^$stealth и @@||4pda.to^$stealth

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
Приветствую!

Правило, которое вы применили будет блокировать только `First-party` запросы.
Попробуйте применить вот это: ```@@*$stealth,domain=4pda.to|4pda.ru```

**Comment by Baltazar500** [comment]
>Попробуйте применить вот это: @@*$stealth,domain=4pda.to|4pda.ru

Не работает. 4pda из гугла в хроме открывается в мобильной версии и без авторизации т.к. отрабатывает антитрекинг. С теми правилами открывается десктопная  версия (десктопный UA прописан в /data/local/command-line) и с авторизацией, как и положено.

**Comment by Chinaski1** [comment]
Попробуйте в таком случае добавить к правилу домен, который используется google при открытии страницы.

**Comment by Baltazar500** [comment]
>Попробуйте в таком случае добавить к правилу домен, который используется google при открытии страницы.

Какой домен ?
![2021 05 21_22 07 01~01](https://user-images.githubusercontent.com/12525093/119135041-42407480-ba81-11eb-8e00-93417db72cbf.jpg)
На скрине попап по лонг-тапу на ссылке из выдачи гугла.

**Comment by Chinaski1** [comment]
Попробуйте вот такой домен: `google.*`

**Comment by Baltazar500** [comment]
>Попробуйте вот такой домен: google.*

Т.е. вы предлагаете такое правило ? 

> @@*$stealth,domain=4pda.to|4pda.ru|google.*

но разве оно не равноценно правилу

> @@*$stealth,domain=google.*

?

Мли вы о нём и говорите ?

Но разве это не рубанёт ВЕСЬ антитрекинг при переходе с гугла ? Мне надо только на 2-х доменах.

**Comment by Sergey-Lyapin** [comment]
Здравствуйте, @Baltazar500
`@@*$stealth,domain=4pda.to|4pda.ru` правило применяется к любым запросам с URL источника 4pda.to или 4pda.ru. 
При открытии главной 4pda я например вижу в логе фильтрации запросы с URL источника `ds-assets.cdn.devapps.ru`, этот домен тоже нужно добавить в правило `@@*$stealth,domain=4pda.to|4pda.ru|ds-assets.cdn.devapps.ru`

Посмотрите в логе фильтрации к каким еще запросам был применен Stealth Mode несмотря на исключение, и добавьте их URL источника к этому правилу

**Comment by Baltazar500** [comment]
>@@*$stealth,domain=4pda.to|4pda.ru|ds-assets.cdn.devapps.ru

Не работает. При переходе из гугла в треды на форуме 4da я продолжаю видеть мобильную версию сайта и то, что я не авторизован.

С правилом "@@||4pda.to^$stealth" таких проблем нет. Я бы использовал его, но ему не скормишь несколько доменов за раз.

**Comment by Sergey-Lyapin** [comment]
@Baltazar500 
Попробуйте это правило: `@@||4pda.*$stealth,domain=google.com`, у меня с ним авторизация сохраняется при переходе из поиска гугла

**Comment by Baltazar500** [comment]
>Попробуйте это правило: @@||4pda.*$stealth,domain=google.com, у меня с ним авторизация сохраняется при переходе из поиска гугла

Я выше писал, что аналогичное правило

>@@*$stealth,domain=google.*

или

>@@*$stealth,domain=4pda.to|4pda.ru|google.*

работало. Вот только мне не нужна деактивация антитрекинга для всего гугла или google.com при переходе по ссылкам из них. Мне нужна деактивация для перечисленных доменов.  Сейчас их 2 на 4pda и парочка на али. Это не так много, но плодить отдельные правила напрягает. А от антитрекинга для остальных сайтов при открытии их из гугла я отказываться на хочу.

**Comment by Sergey-Lyapin** [comment]
@Baltazar500

`@@||4pda.*$stealth,domain=google.com`
Это правило отменяет stealth mode для запросов от гугла к 4pda (с любым доменом верхнего уровня)

**Comment by Baltazar500** [comment]
@Sergey,
>`@@||4pda.*$stealth,domain=google.com`
 >Это правило отменяет stealth mode для запросов от гугла к 4pda (с любым доменом верхнего уровня)

это понятно и оно работает. Но если хостов будет несколько ? Не только 4pda ? А если нужна отмена антитрекинга для них не толтко для гугла ? Как всё это в одно правило впихнуть ? Или это невозможно ?

**Comment by Sergey-Lyapin** [comment]
Вот можно регулярку использовать:
@@/.*(4pda.ru|4pda.to|aliexpress.com|aliexpress.ru).*/$stealth,domain=google.com

> А если нужна отмена антитрекинга для них не только для гугла 

Тогда дополнительные домены после гугла через | палку

**Comment by Baltazar500** [comment]
>`@@/.*(4pda.ru|4pda.to|aliexpress.com|aliexpress.ru).*/$stealth,domain=google.com`

Вот этот вариант получше, но под регулярку много чего может прпасть лишнего, имхо. Тут для антитрекинга антитрекинга по хостам нужен отдельный регулятор походу. А то с этими правилами мозг сломаешь.

>Тогда дополнительные домены после гугла через | палку

или вообще убрать блок domain, если везде ?

**Comment by Sergey-Lyapin** [comment]
@Baltazar500
> но под регулярку много чего может прпасть лишнего
ну можно ее более точной сделать

> или вообще убрать блок domain, если везде ? 
тогда антитрекинг не будет применяться ко всем запросам, адреса которых выбираются этой регуляркой, независимо от источника запроса

**Comment by Baltazar500** [comment]
>тогда антитрекинг не будет применяться ко всем запросам, адреса которых выбираются этой регуляркой, независимо от источника запроса

Я интересовался в том плане, будет ли работать это правило для отключения антитрекинга для этих сайтов не только для гугла, а и на других ресурсах (чтобы при переходе по referer-ссылкам ничего не отваливалось). Проверка показала, что так оно и есть. Разве что я правило немного скорректировал :
>`@@/^https://(4pda.ru|4pda.to).*/$stealth`
