### ISSUE TITLE
Whitelistened requests blocking issue (DNS-filtering)

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForAndroid#3851]
If we block whitelisted by DNS-filtering request from the filtering log AG should add `$important` modifier to the blocking rule.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/18536328/118826810-77ec2e80-b8c4-11eb-987e-5876b89957d1.jpg">
</details>

## Steps to reproduce

1. Add a custom filter list to "Filters": https://gist.githubusercontent.com/ameshkov/4a0614ca049466473a657eeadab1e38b/raw/acf304b50b7978612f4e65bcce7b1dbea7a71f5d/filter.txt
2. Add a new DNS filter: https://gist.githubusercontent.com/ameshkov/4a0614ca049466473a657eeadab1e38b/raw/acf304b50b7978612f4e65bcce7b1dbea7a71f5d/filter.txt
3. Open `example.org`
4. Open Recent activity and find unblocked DNS query
5. Tap "Add blocking rule"
6. Then find unblocked web request and tap "Add blocking rule" there as well

### For a DNS query

1. Add "Give a higher priority to the rule" checkbox
2. Make it "checked" in this particular case (when blocking a `@@` rule).

### For a web request

1. Make the  "Give a higher priority to the rule" checkbox checked for this particular case (when blocking a `@@` rule).

**Comment by artemiv4nov** [comment]
In next versions we are going to apply huge improvements for Filtering log, please follow updates. I'll close this task as a duplicate.
