### ISSUE TITLE
Allow web requests via HTTP3 protocol

### ISSUE THREAD

**Issue by JohnRTitor** [AdguardTeam/AdguardForAndroid#3852]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

HTTP/3 is the third version of the Hypertext Transfer Protocol (HTTP), previously known as HTTP-over-QUIC. QUIC (Quick UDP Internet Connections) was initially developed by Google and is the successor of HTTP/2. It provides faster connection on mobile networks, faster TLS handshakes, improvement overall. 

However, it currently doesn't work with AdGuard enabled. Probably because AdGuard blocks all QUIC requests by default.

[This official website by Cloudflare](https://cloudflare-quic.com/ ) can check if the connection made to that website uses http/3. When AdGuard is enabled the site shows the connection uses HTTP/2, and when AdGuard is disabled, the connection uses HTTP/3.

### Proposed Solution

AdGuard is one of the first ones to implement DNS-over-QUIC support but is yet to actually allow HTTP/3 requests. DNS-over-QUIC is indeed more reliable and "quic" but web requests via QUIC protocol/HTTP3 are yet to be implemented in AdGuard.

### Alternatives Considered

None.

### Additional Information

HTTP/3 is supported by most browsers these days, including Chrome and other browsers based on Chromium (i.e. Microsoft Edge, Opera, Brave). Chrome alone have 60% market share. Most websites are yet to implement it though, but popular websites such as Facebook and Google have already started using it.

**Comment by anastenko** [comment]
@JohnRTitor
We're already working on it :)
Here's an open task: https://github.com/AdguardTeam/CoreLibs/issues/487

**Comment by JohnRTitor** [comment]
> @JohnRTitor
> We're already working on it :)
> Here's an open task: [AdguardTeam/CoreLibs#487](https://github.com/AdguardTeam/CoreLibs/issues/487)

Hello thanks for working on it! My question is that, after this has been implemented would AdGuard allow QUIC requests such as this? Currently all quic requests are blocked by default, there is not even a low level setting to modify this behavior. 
![IMG_20210520_213941](https://user-images.githubusercontent.com/50095635/119012853-08ee0300-b9b4-11eb-837d-d34d12632597.jpg)

**Comment by sfionov** [comment]
@JohnRTitor Yes, AdGuard will stop blocking QUIC when it can efficiently filter out ads from it.
