### ISSUE TITLE
Unable to update Kaspersky WhoCalls offline bases

### ISSUE THREAD

**Issue by skipik** [AdguardTeam/AdguardForAndroid#3855]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Не получается обновить базы в WhoCalls, помогает только отключение галочки "блокировка рекламы" для приложения WhoCalls. Программа долго пытается выполнить обновление, перебирает сервера, но каждый раз это завершается сбоем.
Для теста нужна лицензия, т.к. в триале нет возможности обновления оффлайн баз.
Если обновили успешно (например, выключив AdGuard), то в след. раз пробовать нужно примерно через 24 часа, иначе не воспроизведётся (базы просто проверятся и вроде как всё успешно). Нам нужно чтобы они скачивались, для этого и ожидаем 24 часа.
Не помогает ни отключение всех фильтров, ни днс фильтрации.
Изначально грешил на фильтры, поэтому завёл баг здесь: https://github.com/AdguardTeam/AdguardFilters/issues/81785
P.S. актуально как для релизной версии, так и для ночнушки.

- **AdGuard version:**
  - 4.0 nightly 14
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Redmi 4a
- **Operating system and version:**
  - MIUI Global 10.2.3 Android 7.2.1
- **Root access:**
  - No

### Expected Behavior

Базы успешно обновятся.

### Actual Behavior

Ошибка, как будто не удалось достучаться до серверов

### Screenshots

Скриншоты есть в теме по фильтрам, дублировать тут не стал.

<details><summary>Screenshot:</summary>

</details>

### Additional Information

https://github.com/AdguardTeam/AdguardFilters/issues/81785

<details><summary>Репорт из фильтров:</summary>

### Issue URL (Incorrect Blocking)
 [http://94.75.236.123/diffs/bases/mobile/pndba/countries/ru/rusp060.ndb.cnz](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2F94.75.236.123%2Fdiffs%2Fbases%2Fmobile%2Fpndba%2Fcountries%2Fru%2Frusp060.ndb.cnz)
### Comment
Username: @skipik
> Проблема заключается в том, что невозможно обновить базы WhoCalls. Помогает отключение AdGuard или выключение "блокировки рекламы" для приложения #whocalls.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/A0cm44H.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/WMshKVL.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.1.2
AdGuard product: | AdGuard for Android v4.0 nightly 11 (51)
Browser: | Kaspersky WhoCalls
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: ``<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
</details>

**Comment by Chinaski1** [comment]
Приветствую!

Для диагностики и решения Вашей проблемы, нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
2. Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Отправьте полученный архив на `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by skipik** [comment]
@Chinaski1 добрый день! Логи на почте.

**Comment by skipik** [comment]
Есть какие-то новости по проблеме?

**Comment by Chinaski1** [comment]
К сожалению, изучение логов не дало результата.
Пробуем воспроизвести проблему у себя, как только появится какая-либо информация, я обязательно дам знать.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1460](https://github.com/AdguardTeam/CoreLibs/issues/1460) via [**ZenHub**](https://www.zenhub.com/)
