### ISSUE TITLE
Unable to block "root" for Google Voice

### ISSUE THREAD

**Issue by EntropySmoke** [AdguardTeam/AdguardForAndroid#3857]
Latest version of AdGuard (3.6.23) on rooted Android 10 running in HTTP Proxy Auto-Mode lists "root" in Filtering Log for Google Voice app. It lists tcp://216.239.36.145:443 (HTTPS tunnel) and when trying to view Technical Information for it, it says "An error occurred while loading technical information for root."

I understand when a program has root access, but Google Voice is the only program that gets listed as "root". There is no way to block that IP via DNS blocking or Content Blocking. "Root" is not listed in Apps Management section, but when viewed from Filtering Log, it can be set not to use Cellular or WiFi data. Those settings do not work for "root" either. "Root" tcp://216.239.36.145:443 bypasses everything...

AdGuard for Android VPN mode can't block it either. Google Voice uses STUN and while AdGuard for Android can block WebRTC, it cannot do so for Google Voice. TCPDump for tun0 (AdGuard Local VPN) interface lists local private IP address during Google Voice calls instead of AdGuard Local VPN address (set in Advanced Options). The same happens with 3rd party VPN providers, regardless of encryption protocol.

What exactly is "root"? How do I block it?

**Comment by artemiv4nov** [comment]
@EntropySmoke Hi!
You may have changed the settings earlier. Please find the "Android" application in the Apps Management section. What settings does this application have?
Also, you can reset all settings for the Apps Management section to restore the default behavior.

**Comment by EntropySmoke** [comment]
Google Voice exists as a separate application in Apps Management, but every single time a call is made via Google Voice, AdGuard lists tcp://216.239.36.145:443 (HTTPS tunnel) for app "root" in Filter Log along with "stun.l.google.com" DNS resolution and Google Voice app. The "root" and "stun.l.google.com" entries appear only for calls, not messaging. TCPDump shows that live Google Voice calls use UDP ports 19302-19305. The 

Resetting Apps Management makes no difference. Blocking "stun.l.google.com" DNS makes no difference and doesn't affect ability to make calls. AdGuard can block Google Voice app itself, BUT doing so still does not block "root". There just doesn't appear to be a way to block "root" via AdGuard... The IP for it is a legitimate one.  The IP can be blocked via custom IPTables, but blocking that IP also blocks Google Voice.

I think the "root" IP 216.239.36.145 is used for Google OAuth token, but there is very little information about it on the internet...

**Comment by EntropySmoke** [comment]
OK, I found out that "root" is "Android OS" in Apps Management. If disabled, the "root" IP is blocked without any negative effect on anything (so far...), including Google Voice!

Android OS includes a bunch of system apps, but this is a WiFi-only SIM-free phone and none of the mobile data or mobile radio functions need to work.

Yey!
