### ISSUE TITLE
ru-wikipedia-org.turbopages.org is broken by disable-amp extension

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3858]
@adguard-bot commented on [Wed May 19 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83553)

### Issue URL (Incorrect Blocking)
 [https://ru-wikipedia-org.turbopages.org/ru.wikipedia.org/s/wiki/%25D0%2592%25D0%25B8%25D0%25BA%25D0%25B8%25D0%25BF%25D0%25B5%25D0%25B4%25D0%25B8%25D1%258F?turbo_uid=AACWUZp_tcy-BE1krwLiLsVimZbplJq3MFbuuWlhLFB1L37OaiUeRc4vNkyFA83JwPf7-vrbebauospxngR0vBtPv6ctCAVHXF58bhNCg2a2NEAE&turbo_ic=AACmtcsbURDmOYvD_hAtsvxoRMwwLLPEtv5XCNrGr4RVxPLaNWPGKMZG7ubV0tD1GUgd5sKN_bAbT_3WSEwT3RweoHVubrvWCNOpG3MykisptJsz&sign=62d18a96c983945f8612fcb6fb7ac005326fe379801575986b566ff4a828b37b%3A1621418305&parent-reqid=1621418305677817-1721319447586982284200104-production-app-host-sas-web-yp-64&trbsrc=wb](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fru-wikipedia-org.turbopages.org%2Fru.wikipedia.org%2Fs%2Fwiki%2F%2525D0%252592%2525D0%2525B8%2525D0%2525BA%2525D0%2525B8%2525D0%2525BF%2525D0%2525B5%2525D0%2525B4%2525D0%2525B8%2525D1%25258F%3Fturbo_uid%3DAACWUZp_tcy-BE1krwLiLsVimZbplJq3MFbuuWlhLFB1L37OaiUeRc4vNkyFA83JwPf7-vrbebauospxngR0vBtPv6ctCAVHXF58bhNCg2a2NEAE%26turbo_ic%3DAACmtcsbURDmOYvD_hAtsvxoRMwwLLPEtv5XCNrGr4RVxPLaNWPGKMZG7ubV0tD1GUgd5sKN_bAbT_3WSEwT3RweoHVubrvWCNOpG3MykisptJsz%26sign%3D62d18a96c983945f8612fcb6fb7ac005326fe379801575986b566ff4a828b37b%253A1621418305%26parent-reqid%3D1621418305677817-1721319447586982284200104-production-app-host-sas-web-yp-64%26trbsrc%3Dwb)
### Comment
> не работают все турбо страницы и видео в вк в браузере 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/UpNI2Q6.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/G2UIvyn.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.6.2 (23)
Browser: | Yandex
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Hide your Referrer from third-parties, <br>Hide your IP address (209.141.53.254)
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard Japanese, <br/>Thai Ads Filters
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | встроиный блокировщик яндекс браузера для андроид 

---

@Mintedan commented on [Wed May 19 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83553#issuecomment-843962123)

просто скажите что убрать в настройках чтобы сайты с турбо страницами и видео в вк работали 

---

@Alex-302 commented on [Mon May 24 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83553#issuecomment-846960842)

@Mintedan У меня работает нормально. Можете проверить без фильтрации DNS? 

---

@Mintedan commented on [Mon May 24 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83553#issuecomment-846981344)

@Alex-302 не помогло. я отключил расширение, турбо страницы заработали , видео в вк пока нет 
![upload_2021_05_24_14_31_34_847](https://user-images.githubusercontent.com/84447208/119341671-be62d400-bc9c-11eb-96a6-a721fae00f02.jpg)

**Comment by Alex-302** [comment]
У меня не повторяется, проблема странная.

**Comment by Sergey-Lyapin** [comment]
вот такая же проблема:
https://github.com/AdguardTeam/AdguardFilters/issues/83906
у меня повторяется, логи:
[adguard_logs_4.0.54_2505_174042.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/6540319/adguard_logs_4.0.54_2505_174042.zip)

нужно например пройти по этой <a href="https://yandex.ru/news/story/Putin_i_Bajden_vstretyatsya_vZHeneve_16_iyunya--c105253e3921064e9177545d3d1c98a0?lang=ru&fan=1&stid=a9K3pwNxStJ0mfRc7QS_&t=1621954408&tt=true&persistent_id=144827024
">ссылке</a>: и нажать на ссылку от РИА Новости под видео

**Comment by Mintedan** [comment]
![Screenshot_20210525_180740_com yandex browser](https://user-images.githubusercontent.com/84447208/119525795-7cfb2300-bd87-11eb-86ca-11db14c21f4c.jpg)
![upload_2021_05_25_18_31_56_787](https://user-images.githubusercontent.com/84447208/119525801-7e2c5000-bd87-11eb-93ab-9680a291a8de.jpg)
![Screenshot_20210525_183057_com yandex browser](https://user-images.githubusercontent.com/84447208/119525805-7ec4e680-bd87-11eb-8e5d-af6ece0ee7c9.jpg)
после того как отключил эту функцию видео в вк заработали

**Comment by Mintedan** [comment]
ну по сути свою проблему я решил выключением этих 2 настроек

**Comment by Sergey-Lyapin** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/3858#issuecomment-847957861
В моем случае отключение Disable AMP помогает

**Comment by Alex-302** [comment]
Скопировал в https://github.com/AdguardTeam/DisableAMP/issues/46 на всякий случай.

**Comment by Chinaski1** [comment]
Я закрываю данную задачу, поскольку проблема вызвана Disable AMP скриптом.
Дальнейшее решение доступно по ссылке выше.
