### ISSUE TITLE
Offline database is not downloaded in Caller ID in Yandex app

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#3860]
### Issue Details
- **AdGuard version:**
  - 3.6.2
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 3
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior
The offline database is downloaded in the [Yandex app](https://play.google.com/store/apps/details?id=ru.yandex.searchplugin) in the Caller ID.

### Actual Behavior
The offline database is not downloaded in the [Yandex app](https://play.google.com/store/apps/details?id=ru.yandex.searchplugin) in the Caller ID.

### Screenshots
<details><summary>Application filtering enabled:</summary>

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f576f72383045662e6a7067](https://user-images.githubusercontent.com/19418601/119643944-06146780-be25-11eb-845a-818184cec330.jpeg)

</details>
<details>
<summary>Application filtering disabled:</summary>

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f48763842324d422e6a7067](https://user-images.githubusercontent.com/19418601/119643964-0a408500-be25-11eb-978c-62322a753b50.jpeg)

</details>

### Additional Information
I tried to disable all filters, DNS filtering, Anti-tracking module, Anti-phishing, all extensions, HTTPS filtering, but it did not help. Only disabling AdGuard protection for this application worked.

Originally reported this here: https://github.com/AdguardTeam/AdguardFilters/issues/84002

Also, I have now sent logs from the app to support. Reference 512974 and 512976.

**Comment by rakleed** [comment]
When I turn off the filtering of the Yandex app in AdGuard, either the offline database is loaded immediately, or after the offline database function is turned off and on. I tested this function in this way.

In general, after the first download of the database, it updates itself in the background every few days or weeks (judging by how it works on iOS).

**Comment by Eugene-Savenko** [comment]
@Chinaski1 in case you need logs: **512976**

**Comment by Chinaski1** [comment]
Looks like this issue caused by the filtering rule `||report.appmetrica.yandex.net^` 
You should try to add `@@||yandex.net^` and check the situation again.

**Comment by rakleed** [comment]
It's strange, but at the moment, after updating the filters, the problem is not reproducible.

**Comment by Chinaski1** [comment]
In that case, I will close the task.
Open it again if the issue recurs.
