### ISSUE TITLE
Google Play: com.masomo.headball2

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3861]
@adguard-bot commented on [Mon May 17 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83421)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.masomo.headball2](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.masomo.headball2)
### Comment
Username: @Vijaychandk
> When adguard is on, the game keeps on loading and stops at 0%.when it is turned off then it loads the game

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/lp5nuh7.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vcUEnLq.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.2 (23)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Strip URLs from tracking parameters, <br>Self-destructing first-party cookies (0), <br>Self-destructing third-party cookies (0), <br>Block WebRTC, <br>Block Location API
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> Fanboy's Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>EasyList Cookie List, <br/>I don't care about cookies, <br/>Web Annoyances Ultralist<br/><br/><b>Security:</b><br/> NoCoin Filter List, <br/>Online Malicious URL Blocklist, <br/>Spam404<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion, <br/>BarbBlock, <br/>AdGuard DNS, <br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> EasyList Dutch, <br/>Greek AdBlock Filter, <br/>AdGuard Russian, <br/>Fanboy's Spanish/Portuguese, <br/>AdGuard Turkish, <br/>Thai Ads Filters, <br/>Adblock List for Finland, <br/>RU AdList, <br/>List-KR, <br/>EasyList Spanish, <br/>Estonian List, <br/>AlleBlock, <br/>ROLIST2, <br/>EasyList Polish, <br/>Hungarian, <br/>Fanboy's Vietnamese, <br/>xinggsf, <br/>Icelandic ABP List, <br/>ChinaList+EasyList, <br/>Liste AR, <br/>ABPVN List, <br/>AdBlockID, <br/>AdGuard Chinese, <br/>Fanboy's Swedish, <br/>ROList, <br/>road-block, <br/>AdGuard Japanese, <br/>CJX's Annoyances List, <br/>AdGuard German, <br/>EasyList Germany, <br/>EasyList Italy, <br/>AdGuard Dutch, <br/>Latvian List, <br/>Polish Anti-Annoying Special Supplement, <br/>Xfiles, <br/>Adblock-Persian list, <br/>EasyList China, <br/>EasyList Lithuania, <br/>Polish Social Filters, <br/>Polish Annoyances Filters, <br/>Dandelion Sprout's Nordic Filters, <br/>EasyList Czech and Slovak, <br/>Polish Anti Adblock Filters, <br/>KAD - Anti-Scam, <br/>AdGuard Spanish/Portuguese, <br/>Iranian, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polish GDPR-Cookies Filters, <br/>AdGuard French, <br/>Liste FR, <br/>YousList, <br/>EasyList Hebrew, <br/>ABPindo, <br/>RU AdList: Counters, <br/>RU AdList: BitBlock, <br/>Bulgarian list, <br/>Frellwit's Swedish Filter
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by Alex-302** [comment]
Not reproduced on my device.
@VijayChandK Please collect debug logs and send to support@adguard.com
https://kb.adguard.com/en/android/solving-problems/log#collecting-debug-log

**Comment by Chinaski1** [comment]
Also not reproduced on my side.
Generally, it seems that a combination of filters could be the possible cause of the application malfunction.
@VijayChandK Please try deactivating all third-party filters (leave only those marked with the Star)
You can also try to disable Stealth-mode.
If this has no effect, then we need logs to diagnose the issue.
Instructions have been sent by @Alex-302 above.

**Comment by Chinaski1** [comment]
@VijayChandK
Any news?

**Comment by Chinaski1** [comment]
Closed due not reply
