### ISSUE TITLE
Turkey - Turkcell VoWifi new ip address

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3864]
@bymcs commented on [Fri May 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83734)

Hello Turkcell is using a new VoWifi ip address and it does not work with Adguard enabled.
I want you to add this.

new adress : 188.59.227.1:4500
                     188.59.228.1:4500

---

@krystian3w commented on [Fri May 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83734#issuecomment-845885151)

Try add allow rule:

`@@||188.*.*.*:4500^`

to user rules Filter (maybe later to DNS user rules Filter).

**Comment by infinitewaveparticle** [comment]
Wouldn't this just go into pref.ipv4.rotes.excluded?

**Comment by Chinaski1** [comment]
Yes, IP addresses will be added to pref.ipv4.routes.exclusions
