### ISSUE TITLE
Fanboy's Annoyance List's Subscription URL broken

### ISSUE THREAD

**Issue by arrow98** [AdguardTeam/AdguardForAndroid#3865]
The subscription URL of Fanboy's Annoyance list is broken (outdated).
It should be updated to https://secure.fanboy.co.nz/fanboy-annoyance.txt

**Comment by Chinaski1** [comment]
Hello there!
Thanks for the report, we will fix it in the next update.

**Comment by admitrevskiy** [comment]
The contents of https://secure.fanboy.co.nz/fanboy-annoyance.txt and https://easylist.to/easylist/fanboy-annoyance.txt are the same and as I can see old link contains pretty fresh version of the filter.
