### ISSUE TITLE
Google Play: com.zhiliaoapp.musically (TikTok)

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#3866]
@adguard-bot commented on [Fri May 14 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83229)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.zhiliaoapp.musically)
### Comment
> Во время включенного Adguard не работает просмотр трансляций TikTok. До обновления таких проблем не наблюдалось.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/L3dQ3pK.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/MFxWXjk.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.6.2 (23)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>I don't care about cookies, <br/>Adblock Warning Removal List<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | Иные блокировщики отсутствуют, пользуюсь более года Dr. Web Light.

---

@Alex-302 commented on [Tue May 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83229#issuecomment-847958168)

Account is required, but I cannot register.
@AdguardTeam/filters-maintainers please take a look.

---

@Alex-302 commented on [Tue Jun 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83229#issuecomment-852430699)

@AdguardTeam/filters-maintainers

---

@Sergey-Lyapin commented on [Wed Jun 02 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83229#issuecomment-852944741)

I cant't find translations in the app

**Comment by zloyden** [comment]
These broadcasts are blocked with the modules completely turned off. Tested on the latest nightly.

Steps to reproduce (account required):
1. Open TikTok app.
2. Inbox -> Button `Watch` at the top.

**Comment by ameshkov** [comment]
The issue is caused by QUIC blocking.

In order to bypass QUIC you should return BYPASS in the `udpConnectRequest` handler. 
Let's add a low-level setting that allows to configure the list of apps where we don't suppress QUIC.

**Comment by Alex-302** [comment]
> Let's add a low-level setting that allows to configure the list of apps where we don't suppress QUIC.

Maybe modifier would be better.

**Comment by ameshkov** [comment]
@Alex-302 

The alternative solution would be to extend $network rules and allow handling protocols i.e. `@@quic:*$network` or `tcp:*$network`, but this would be rather hard to implement.

**Comment by artemiv4nov** [comment]
Well, our plan is to make a Low-Level setting to non-block connections for specific apps.
This solution will be available since AdGuard 4.0.

**Comment by ameshkov** [comment]
@artemiv4nov we should find a temporary solution to fix this in the upcoming patch. We're talking about an app with 500M+ users, this is not the case when we postpone fixes.

**Comment by artemiv4nov** [comment]
Hmm... So, we will create a Low-Level setting with applications to non-block requests with QIUC protocols in the 3.6.3 version.

**Comment by TPS** [comment]
Current issue for allowing QUIC is #3565.

Also, why doesn't this issue _name_ TikTok anyplace?

**Comment by Disqu3-mirOir-qt** [comment]
not work because quic for tiktok trought android meta package

**Comment by admitrevskiy** [comment]
We should try to reproduce this issue with Android API 26

**Comment by DandelionSprout** [comment]
I just want to chip in with how `quic://` blocking affects other apps as well (though not with such severe effects), and not just TikTok:
![Screenshot_20210813-123339](https://user-images.githubusercontent.com/22780683/129811289-f252b101-e70a-4bee-b9d0-d33f79b18fd0.png)

**Comment by sfionov** [comment]
@DandelionSprout So we have the roadmap for this. 

Version of CoreLibs to be released (1.8 update 1; ETA Sept 2021) will be able to filter QUIC bypassed connections.

Corelibs 1.9 (ETA Q4 2021) will be able to MITM QUIC connections.

**Comment by TPS** [comment]
This is released?  How's it accessed?

**Comment by sfionov** [comment]
@TPS Solved only for TikTok in 3.6.3 release.

QUIC-bypass filtering is not reached any of our products yet.

**Comment by TPS** [comment]
> Version of CoreLibs to be released (1.8 update 1; ETA Sept 2021) will be able to filter QUIC bypassed connections.
> 
> Corelibs 1.9 (ETA Q4 2021) will be able to MITM QUIC connections.

> @TPS Solved only for TikTok in 3.6.3 release.
> 
> QUIC-bypass filtering is not reached any of our products yet.

Could you reopen #3565 then to track?  That was closed in favor of this.

**Comment by admitrevskiy** [comment]
@TPS you can configure any package to bypass QUIC traffic for: `Settings -> Advanced ->  Low-Level Settings  -> pref.quic.bypass.packages`
