### ISSUE TITLE
Editing a disabled user filter should keep it disabled - instead it enables it automatically

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3867]
### Issue Details

- **AdGuard version:**
  - 4.0.54
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OP: Unspecified / Repro: Sony G8342
- **Operating system and version:**
  - OP: Unspecified / Repro: Android 9
- **Root access:**
  - No

### Expected Behavior

Editing a disabled user filter should keep it disabled

### Actual Behavior

Editing a disabled user filter immediately enables it

### Repro

1. Disable a filter
2. Attempt to edit it manually
3. It will automatically reenable itself

### Additional Information

Z514327

**Comment by Chinaski1** [comment]
This is the expected behaviour of the application.
If users are editing a rule they will most likely need it in the near future.
