### ISSUE TITLE
Enable additional block lists for specific applications

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3871]
I am a person who speaks Chinese, and I will also use apps from Chinese companies. I want to enable additional block lists for my Chinese apps, because it is well known that China’s software ecosystem is very complicated. This may be due to China’s weak privacy regulations.

**Comment by c2xusnpq6** [comment]
You can google the past black history of China's anti-virus software, although it is not much better now.

**Comment by anastenko** [comment]
@c2xusnpq6 Hello.
We don't plan to implement such feature, but you can create your own custom filter and use `$ app` modifier in order to apply them to a specific application.
Check info on `$ app` modifier [here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#app-modifier)
