### ISSUE TITLE
View POST content

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3875]
I have added the Adguard certificate to the system storage through Magisk

Sometimes it’s hard to tell whether it’s really a tracker or an ad based on the URL alone

Just like this one:
```
https://dad-api.dcard.tw/v0/events
```
![Screenshot_20210616-112717_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122154043-b90d3980-ce96-11eb-9441-12fb1d28ab4c.png)

**Comment by c2xusnpq6** [comment]
You can refer to this app:
HttpCanary (com.guoshi.httpcanary)
https://play.google.com/store/apps/details?id=com.guoshi.httpcanary

**Comment by artemiv4nov** [comment]
@c2xusnpq6 Hi!
We take into account by what filter the request has been blocked.
This feature may change in AdGuard 4.0. Let's look at this issue after the first nightly version of the real AdGuard 4.0 will be published.

**Comment by c2xusnpq6** [comment]
ping? 😗

**Comment by Chinaski1** [comment]
@c2xusnpq6 

Please, stop writing "ping" in every task you created earlier.
The developers have outlined a rough solution/change on version 4.0.
It is not released yet.

**Comment by infinitewaveparticle** [comment]
> ```
> https://dad-api.dcard.tw/v0/events
> ```

While I also would LOVE to be able to read POST content, 99% of the time I would block anything ending in /events unless doing so blocks notifications that you want/need.

**Comment by c2xusnpq6** [comment]
Ping?

**Comment by c2xusnpq6** [comment]
Or just show us the http header for now. (`$removeheader`, `$cookie`)

**Comment by artemiv4nov** [comment]
The Filtering log functionality has been re-worked in the 4.0 version, please follow updates.
