### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#3876]
![Screenshot_20210616-220533_Trebuchet~2.png](https://user-images.githubusercontent.com/75058881/122234132-349ad500-ceef-11eb-8a55-eed7bac7186e.png)

![Screenshot_20210616-220733_Trebuchet.png](https://user-images.githubusercontent.com/75058881/122234196-441a1e00-ceef-11eb-8096-5e30c82ed633.png)

**Comment by Chinaski1** [comment]
Please clarify what the question is?

**Comment by c2xusnpq6** [comment]
![Screenshot_20210616-220533_Trebuchet~3.png](https://user-images.githubusercontent.com/75058881/122249721-aaa53900-cefb-11eb-8f5b-b93fc4bcf308.png)

**Comment by sfionov** [comment]
Yep, it is a bug in application that made such crazy request. :)

**Comment by c2xusnpq6** [comment]
So has it been fixed in the next version? Or what?

**Comment by sfionov** [comment]
No, the app actually made this crazy request. Not our bug.
