### ISSUE TITLE
Show in-app notifications when changing the settings #3822

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3878]
Добавьте и сюда подобное:

Show in-app notifications when changing the settings #3822 - https://github.com/AdguardTeam/AdguardForWindows/issues/3822

**Comment by artemiv4nov** [comment]
@GdeZsqyAY Hi!
In-app notifications have already been integrated into AdGuard using Android Toasts.
