### ISSUE TITLE
Yandex Mail does not work with HTTPS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#388]
https://play.google.com/store/apps/details?id=ru.yandex.mail

**Comment by Revertron** [comment]
Added "mobile.yandex.net" to ssl_exclusions.

**Comment by evgeniy-ADG** [comment]
It's back. The app version is: [3.10](https://play.google.com/store/apps/details?id=ru.yandex.mail) If you disable HTTPS filtering in Apps and Statistics, it gets back to normal

![image](https://cloud.githubusercontent.com/assets/15856304/17977870/0db97920-6afc-11e6-9275-30e6318092a3.png)

**Comment by nkartyshov** [comment]
done
