### ISSUE TITLE
Some Enhancements implemented by Puffer

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#3880]
I ran into [Puffer](https://play.google.com/store/apps/details?id=com.parsed.securitywall) today ([GitHub source](https://github.com/jawline/Puffer), [dev's Reddit discussion](https://www.reddit.com/r/androidapps/comments/lkbd7t/dev_puffer_sni_based_tracker_protection_for/)), which claims some nifty features which AG could potentially implement:

- [ ] Stats re: most active filters
<Details>

> ![Accountability Blocked (1).png](https://user-images.githubusercontent.com/185902/122647188-f66d0380-d0f0-11eb-833a-a75269bd131f.png)

</Details>

- [ ] Current open connections (maybe add how _long_ open & ability to close/block)
<Details>

> ![Review Live.png](https://user-images.githubusercontent.com/185902/122647248-49df5180-d0f1-11eb-8290-ebd89fb6f87f.png)

</Details>

- [ ] Block UPnP & LAN connections
<Details>

> ![Control Block.png](https://user-images.githubusercontent.com/185902/122647312-a6427100-d0f1-11eb-8723-41c9226cbe57.png)

</Details>

Technical Details _(Emphasis mine for strange parts 🤔)_:
> Puffer is a packet-level filter for Android that uses the VPN interface to read raw packets. By registering as a VPN, Puffer can get Android to forward raw IP packets to the application instead of the network. _Puffer then emulates a network card and performs complementary Linux socket operations but keeps track of TLS packets. Puffer reads the initial ClientHello packet of each TLS connection and extracts the SNI (Server Name Indication) headers, which it uses to classify and selectively block streams. By this mechanism, Puffer can block streams without needing to decrypt the stream contents._

**Comment by anastenko** [comment]
@TPS Hello.
Thanks for your suggestion, we'll consider these features for the future updates.

**Comment by TPS** [comment]
@artemiv4nov None of the OP's tasks are _hinted_ at, much less implemented.  Why close?
