### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardForAndroid#3883]
Under advanced of settings
There is watchdog period
If i input 0 it says to put number between 10-300
But it accepts 0>number<10 also
It maybe a typo

![Screenshot_20210623-165824_AdGuard](https://user-images.githubusercontent.com/46019727/123127719-5c001d80-d46c-11eb-9add-a5d298cfad50.jpg)

![Screenshot_20210623-214558_AdGuard](https://user-images.githubusercontent.com/46019727/123127865-7b974600-d46c-11eb-94b4-9adc9f503a4a.jpg)

**Comment by anastenko** [comment]
@Bhooty Hello.
We recommend entering a number from 10 to 300, but if user enters a value less than 10, it will be converted into 10 "beneath the hood" in order to save battery.

**Comment by Bhooty** [comment]
> @Bhooty Hello.
> We recommend entering a number from 10 to 300, but if user enters a value less than 10, it will be converted into 10 "beneath the hood" in order to save battery.

Still shouldn't it restrict putting less than 10?
Btw thanks for the explanation 😬

**Comment by anastenko** [comment]
Well, absence of such restriction makes it more user-friendly :)
Maybe it will be changed in the future updates, but for now it remains this way.
