### ISSUE TITLE
Separate app builds to different architectures

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3884]
А почему нет отдельных релизов AdGuard'a под разные архитектуры (с конкретным набором lib, assets и т.д.) ? Перепаковать и переподписать исходный apk не проблема, но есть нюанс. AdGuard без оригинальной подписи начнёт переодически сигналить "We detected that you are using a modified version of adguard" и мигать светодидом, что сильно напрягает.

**Comment by artemiv4nov** [comment]
@Baltazar500 
Hi!
We speak in English to support all users, including non-Russian natives.
What the point to you of making a few configurations with different arch-present libraries? I want to understand your opinion better.

**Comment by Baltazar500** [comment]
>Hi!
>We speak in English to support all users, including non-Russian natives.

Привет.

Мой английский оставляет желать лучшего. Поэтому, если есть возможность, я пишу на русском. Машинный перевод зачастую сильно искажает исходные фразы, поэтому мне их приходится выправлять, руководствуясь словарём. Посему для меня куда бОльшим неуважением в отношении НЕрусскоязычных пользователей является текст прогнанный через машинный перевод, нежели написанный на русском. Проблема в том, что его приведение в адекватный вид отнимает много времени, которое у меня не всегда есть. Тем не менее. Раз вы настаиваете на английском, буду переводить машинным переводом без правок :/ ради экономии времени 

###

Hi.

My English is poor. Therefore, if possible, I write in Russian. Machine translation often distorts the original phrases greatly, so I have to correct them using a dictionary. Therefore, for me, a much greater disrespect for non-Russian-speaking users is a text driven through machine translation, rather than written in Russian. The problem is that putting it in an adequate form takes a lot of time, which I don't always have. However. Since you insist on English, I will translate by machine translation without edits :/ in order to save time

>What the point to you of making a few configurations with different arch-present libraries? I want to understand your opinion better.

Да банально ради экономии места. 15 мегабайт тут, 30 мегабайт там, 40 сям и вот на 1.5 - 2 десятках приложений есть "прицеп" бесполезного веса в пару - тройку сотен мегабайт. Опять же на производительность это тоже в некоторой мере влияет. Как я уже писал ранее, я бы сам всё обрезал, но в AdGuard я напарываюсь на вышеописанные грабли.

###

Yes, it is corny for the sake of saving space. 15 megabytes here, 30 megabytes there, 40 here and here on 1.5 - 2 dozen applications there is a "trailer" of useless weight in a couple - three hundred megabytes. Again, this also affects performance to some extent. As I wrote earlier, I would cut everything myself, but in AdGuard I run into the same rake described above.

**Comment by artemiv4nov** [comment]
Понимаю вашу ситуацию.

Поставка приложений для пользователей сильно усложнится, так что пока вариант с разделением по архитектурам исключаем.
Тем не менее, это не означает, что этого не будет в будущем. Возможно, получится использовать относительно недавние технологии Play Store за его пределами адекватно (речь про bundles), поскольку AdGuard не распространяется через Play Store.
