### ISSUE TITLE
开启ad后 google play store无法联网

### ISSUE THREAD

**Issue by eleven702** [AdguardTeam/AdguardForAndroid#3887]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
 3.6.2（23）
- **Filtering mode:**
  - 
- **Device:**
三星s10国行
- **Operating system and version:**
oneui3.1 安卓11最新版
- **Root access:**
no
我三星s10国行，不开adguard能连接google play store,打开adguard并且开启google play store控制流量，google play store不能联网
adguard开启vpn。开启socks5连接开启仅代理的anxray或者v2ray ng，google play store都不能联网，单独开启anxray或者v2rayng就可以连接google play store，

**Comment by artemiv4nov** [comment]
@eleven702 Hi!
Please try to remove 1000 or 1001 or both from the Low-level setting "pref.excluded.packages".

**Comment by eleven702** [comment]
I don't know how to delete 1000 and 1001

Is it the whole / / disable for "radio" and / / disable for "system"

In addition, in the Chinese version of S10, Google plat store is not controlled by guard, and there is no filtering information about store in the filtering list. Can it be used normally according to your operation?
![photo_2021-06-30_10-09-45](https://user-images.githubusercontent.com/85826516/123891719-e9230500-d98b-11eb-8710-d14b1decf0a6.jpg)

**Comment by eleven702** [comment]
我不知道1000和1001是指的哪一行，请明确。另外三星s10中国版本中，adguard开启谷歌商店流量控制，但是在过滤列表中没有任何关于谷歌商店的任何记录，我想问题就是出在这里。
删除1000和1001后是否能正常使用？

Artyom Ivanov ***@***.***> 于2021年6月29日周二 下午4:42写道：

**Comment by Chinaski1** [comment]
You need to delete these two entries, which are marked with arrows on the [screenshot](https://uploads.adguard.com/Chinaskiaa3uy.png).
After deleting click OK

**Comment by anastenko** [comment]
I'm closing this issue due to no response. Please re-open it if the issue is still present.
