### ISSUE TITLE
Apps show connection error or load error on Android 9

### ISSUE THREAD

**Issue by satomi-ynk-sg** [AdguardTeam/AdguardForAndroid#3888]
### Issue Details

Our customers have reported issues with two Android apps.  We can reproduce the issues on Andoroid 9.

- **AdGuard version:**
  - 3.6.2 (23)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Huawei P20 lite
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

We can open pages without an error.

#### App 1: au Service Today
- package name: com.kddi.pass.launcher
- version: 8.7.1 (8070102)
- target SDK: 29

How to reproduce on Android 9:
1. Select an article in the list.
2. We see an error "Failed to load the page. Please try again after a while."

#### App 2: GU
- package name: com.osharemaker
- version: 5.0.2 (149)
- target SDK: 29

How to reporduce on Android 9 (A):
1. Select "Favorite".
2. We see an error "An error occurred while displaying the page. Please check the communication status and refresh the screen again, or try again after a while.

How to reproduce on Android 9 (B):
1. Select the Search field.
2. Select one of the Trend Words (keyword following a "#") or enter any word.
3. We see and error "Could not connect to the Internet. Please check your network connection."

### Screenshots

<details><summary>Screenshot: App1: au Service Today </summary>

![au_Service_Today_app](https://user-images.githubusercontent.com/49304669/123622696-81fc3800-d847-11eb-999e-c068353660ad.jpg)

</details>

<details><summary>Screenshot: App2: GU app</summary>

![GU_app](https://user-images.githubusercontent.com/49304669/123622832-b1ab4000-d847-11eb-8e2d-6142046c36ed.jpg)

</details>

### Additional Information

We could not reproduce the issue on Android 10 (on another smartphone model).

The difference we observe between Android 9 and Android 10 is the quic connections.  In AdGuard Filterling Log screen, blocked quic connections have the application icon on Android 9 but the Android system (Droid) icon on Android 10.

**Comment by satomi-ynk-sg** [comment]
Attached are the AdGuard logs.  
The error occured just before the logs were exported.

<details><summary>Log: App1: au Service Today app</summary>
[auServiceToday_adguard_logs_3.6.23_2506_150705.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/6725537/auServiceToday_adguard_logs_3.6.23_2506_150705.zip)
</details>
<details><summary>Log: App2: GU app</summary>
[GU_adguard_logs_3.6.23_2506_142711.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/6725539/GU_adguard_logs_3.6.23_2506_142711.zip)
</details>

**Comment by satomi-ynk-sg** [comment]
The issue reproduces on AQUOS sense3 basic (SHV48) also running under Android 9.

**Comment by Chinaski1** [comment]
@satomi-ynk-sg 

The issue may be due to the combination of filters used.
Try completely disabling all filters under Content blocking and check if the issue recurs?

**Comment by satomi-ynk-sg** [comment]
@Chinaski1 

Thank you for your suggestion, but even if we turn off all filters under Content Blocking, it reproduces.
Here is the screenshot of the blocked items in the filtering log.

<details>
<summary>Screenshot of blocked quic connections</summary>
![Screenshot_20210721_215332_com adguard android](https://user-images.githubusercontent.com/49304669/126494918-cdae7047-b6b7-4e1e-a5a7-20e9828ad602.jpg)
</details>

**Comment by Chinaski1** [comment]
As a temporary solution, you can disable filtration to specified applications.
AdGuard -> Settings -> Apps management -> find the app -> disable AdGuard protection

**Comment by satomi-ynk-sg** [comment]
Thank you.  We can avoid the problem by disabling AdGuard protection for these application, and we have suggested this workaround to our customers.

Do you expect this issue will be resolved with version 3.6.3 ?

**Comment by Chinaski1** [comment]
Yes, the issue should be fixed in version 3.6.3

**Comment by satomi-ynk-sg** [comment]
Thank you!

**Comment by admitrevskiy** [comment]
This bug can only be fixed on CoreLibs level, here is the issue with the details: https://github.com/AdguardTeam/CoreLibs/issues/1499
