### ISSUE TITLE
Google blocking

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardForAndroid#3890]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

As a user said, AdGuard starts to block the Google search in the Google Chrome browser.
We should investigate its case and provide feedback.

Support ticket [#514139](https://adguard.zendesk.com/agent/tickets/514139)

**Comment by sfionov** [comment]
Let's wait for QUIC filtering support in CoreLibs.

**Comment by artemiv4nov** [comment]
The issue is not actual anymore, closed
