### ISSUE TITLE
Не появляются уведомления о разрешении доступа отдельным приложениям

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardForAndroid#3891]
### Issue Details

После установки на новое устройство перестали всплывать индивидуальные уведомления о блокировке приложения. Соответственно, пропала возможность временно предоставить приложению разрешение на доступ, приходится полностью отключать AdGuard. В настройке приложения галочка стоит.
Уведомления о "Статусе защиты" работают — если включить всплывающие уведомления, то они постоянно всплывают. Аналогичная настройка для брандмауэра не работает.

Проблема скорее всего в самом AdGuard, поскольку каких-то принципиальных запретов на уведомления от него со стороны системы нет.

**Device:**
  POCO M3

Ticket number [#515618](https://adguard.zendesk.com/agent/tickets/515618)

**Comment by vol2160** [comment]
_Также, уточните, пожалуйста, какое устройство вы использовали ранее (на котором проблема не возникала)._
Предыдущая модель смартфона, и на которой всё работало — Highscreen Power Five Max.

**Comment by artemiv4nov** [comment]
@vol2160 Здравствуйте!
Вы уверены, что для канала уведомлений "Firewall" у вас включены уведомления?
Секция проекта, отвечающая за уведомления, не менялась, и маловероятно, что она ломалась.

**Comment by vol2160** [comment]
> Вы уверены, что для канала уведомлений "Firewall" у вас включены уведомления?
> Секция проекта, отвечающая за уведомления, не менялась, и маловероятно, что она ломалась.
Добрый день.
Да, включены. И эта информация есть у службы поддержки. Прежде, чем завести данную задачу, служба поддержки исчерпала все очевидные варианты. Если Вы поднимете переписку, то обнаружите не только множество скриншотов, но и наличие логи приложения с таймингом, когда и что делалось, какие уведомления были включены и какие из них приходили (от одновременно включённых уведомлений о "Статусе защиты" всё приходит, а включённых всплывающих уведомлений в разделе "Брандмауэр" -- нет).

**Comment by Alex-302** [comment]
А настройки импортировали, или настраивали заново?

**Comment by vol2160** [comment]
Сначала импортировал, потом пару раз менял, в том числе, по просьбе службы поддержки включал логи и потом их выгружал.

**Comment by artemiv4nov** [comment]
@vol2160 
К сожалению, не совсем ясно, чем вызвано такое поведение системы. Наши уведомления все приходят исправно, возможно, прошивка специфического девайса влияет.
Пожалуйста, дождитесь выхода бета версии AdGuard, где эти уведомления будут значительно переработаны, как их логирование. Тогда мы сможем узнать больше информации.

**Comment by vol2160** [comment]
ok. Вы тогда уведомите хоть, когда эта версия будет и как, и откуда её установить, и, главное, какую информацию необходимо будет предоставить по результатам установки.

**Comment by artemiv4nov** [comment]
Да, конечно, обязательно в комментариях к этой задаче оповестим

**Comment by admitrevskiy** [comment]
@vol2160 Здравствуйте!
Попробуйте переключиться на найтли канал (на всякий случай экспортируйте свои настройки) и обновиться до актуальной версии найтли 4.0
