### ISSUE TITLE
До конца времен

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3892]
**До конца времен** - это сколько?

<a href="https://fastpic.ru/view/115/2021/0629/d9a23b04c60086ae3babe75cb4477141.jpg.html" target="_blank"><img src="https://i115.fastpic.ru/thumb/2021/0629/41/d9a23b04c60086ae3babe75cb4477141.jpeg" border="0"></a>

Будьте так любезны привести информацию о сроке лицензии к единому стандарту

<a href="https://fastpic.ru/view/115/2021/0629/12aac73060b99db66911b8afd3558f07.jpg.html" target="_blank"><img src="https://i115.fastpic.ru/thumb/2021/0629/07/12aac73060b99db66911b8afd3558f07.jpeg" border="0"></a> <a href="https://fastpic.ru/view/115/2021/0629/88fc4ebf9c5a55990c0d6ba38da5ffb9.png.html" target="_blank"><img src="https://i115.fastpic.ru/thumb/2021/0629/b9/88fc4ebf9c5a55990c0d6ba38da5ffb9.jpeg" border="0"></a>

**Comment by anastenko** [comment]
@GdeZsqyAY
"До конца времен" - это уже устоявшееся описание срока лицензии и менять его мы не планируем.

**Comment by GdeZsqyAY** [comment]
@anastenko

> "До конца времен" - это уже устоявшееся описание срока лицензии и менять его мы не планируем.

Информация должна быть корректной, а не написанной через одно место.

**Comment by anastenko** [comment]
Уточните, пожалуйста, что конкретно вам не нравится в этом описании? Оно указывает на то, что лицензия бессрочна.

**Comment by GdeZsqyAY** [comment]
@anastenko

> Оно указывает на то, что лицензия бессрочна.

В каком именно месте она это указывает?

**До конца времен** - жизни человечества на земле или же существовании нашей планеты или же ...
