### ISSUE TITLE
Google Play: com.booking

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3894]
@adguard-bot commented on [Mon Jun 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86425)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.booking&hl=ru&gl=US](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.booking%26hl%3Dru%26gl%3DUS)
### Comment
Username: @Thecy39
> При включённой защите приложение не может выйти в интренет. Та же ситуация с приложением Яндекс go.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/xSYiOWp.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/3m4H3m8.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.6.2 (23)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | Касперский интернет секьюрити

**Comment by Chinaski1** [comment]
Добрый день @thecy39 

А вы не могли бы попробовать повторить проблему предварительно отключив Kaspersky Internet Security?

**Comment by thecy39** [comment]
Добрый день. Отключил Касперский, выгрузил из памяти. Проблема осталась.

Konstantin ***@***.***> 5 июля 2021 г. 16:40:17 написал:

**Comment by Chinaski1** [comment]
@thecy39 

Возможно проблема вызвана использованием DNS фильтрации.
Я бы порекомендовал вам попробовать выбрать другой сервер для проверки, или же полностью отключить данную функцию.

В случае, если это не возимеет эффекта, нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
2. Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

В качестве временного решения вы можете попробовать полностью отключить фильтрацию для указанных приложений:
- Октройте настройки AdGuard
- Настройки приложений
- Выберите приложение Booking
- Отключите настройку **Защита AdGuard**

**Comment by thecy39** [comment]
Добрый день!
Действительно из-за dns фильтрации. Сменил фильтр adguard на Google и все 
заработало. Спасибо.

Konstantin ***@***.***> 8 июля 2021 г. 17:44:31 написал:

**Comment by anastenko** [comment]
@thecy39 Здравствуйте! 
Рады слышать, что проблема была решена. В таком случае мы закрываем задачу. Если проблема проявится вновь, переоткройте эту задачу.
