### ISSUE TITLE
Feedback message gets erased immediately after taping back button

### ISSUE THREAD

**Issue by isHrytsai** [AdguardTeam/AdguardForAndroid#3896]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

While composing a feedback message, whenever you hit the back button either on purpose or by accident you are quickly taken to the previous menu and everything that has been typed is lost forever.

### Proposed Solution

Add a Confirm dialog that warns the user that the Feedback message/draft will be permanently deleted.

Force the user to select OK or Cancel (or perhaps even a 3rd option to Save a draft locally, within the app Data, or to email the draft to oneself).

### Alternatives Considered

You could also use an auto-save function to save the user's message progress every 30 seconds or so.

### Additional Information

Ticket number is 519943

**Comment by artemiv4nov** [comment]
@isHrytsai Hello!
I'm sorry for the late response.
Would you please clarify what do you do to send a feedback message?

**Comment by infinitewaveparticle** [comment]
@artemiv4nov This was my feature request that I sent thru a support request from the app, ironically. To answer your question... Well, I do what anyone does... In the app... Click hamburger, Support, Send Feedback, choose Feature Request or Other, type body, click the Send Arrow in the upper right corner.

**Comment by artemiv4nov** [comment]
@infinitewaveparticle Hi!
Ah-ha got it.
So, do you want the message won't be erased if you tapped the back button but did not send the feedback?
What if you sent the feedback? Should the message be erased, or should be filled for N seconds?

**Comment by infinitewaveparticle** [comment]
@Artyom Ivanov

Yes, it would be helpful to not have the feedback message erased if the user either accidentally clicks 'back' or if the user needs to reference the app's Settings or Filtering Log and then return to the feedback message to complete it.

I think if the feedback message is successfully sent it would be safe to erase it from memory, although it would be awesome to see sent requests, see the replies to them, and be able to respond to those replies from within the app... Users could then track the issues they've sent without having to use their email app. For users like me who use the in-app Support Request function a lot (and Github not as much) it would help to be able to see my sent requests and be able to delete them when they've been dealt with.

Sent from ProtonMail mobile

-------- Original Message --------
