### ISSUE TITLE
Enable https filtering by default for Edge Dev, Edge Beta, and Styx Browser

### ISSUE THREAD

**Issue by Uranite** [AdguardTeam/AdguardForAndroid#3897]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description
Https filtering isn't enabled by default for Edge Dev, Edge Beta, and Styx Browser

### Proposed Solution
add
com.microsoft.emmx.beta
com.microsoft.emmx.dev
com.jamal2367.styx

**Comment by Chinaski1** [comment]
Hello @Uranite 

We will add  HTTPS filtering by default to the specified browsers in a future update.
Thank you.
