### ISSUE TITLE
Advertisements aren't being hidden

### ISSUE THREAD

**Issue by basamaryan** [AdguardTeam/AdguardForAndroid#3901]
### Issue Details

- **AdGuard version:**
  - v4.0.57
- **Filtering mode:**
  - Local Proxy Auto Mode
- **Device:**
  - Redmi Note 10 Pro Max
- **Operating system and version:**
  - Android 11
- **Root access:**
  - Yes

### Expected Behavior

The Advertisement should have been hidden fully, and the space removed 

### Actual Behavior

Advertisements on multiple pages aren't hiding the space. Instead, it is showing an Android logo and the error
Webpage not available
The webpage at https://securepubads.g.doubleclick.net/gampad/ads?iu=%2F1055314%2FLM_MF_AMP_AllPages_Masthead_A_Multisize&adk=1873786642&sz=300x250%7C250x250&output=html&impl=ifr&ifi=2&msz=320x-1&psz=320x-1&fws=4&scp=keyword%3DWhatsApp%252CDelhi%2520High%2520Court%252CPrivacy%2520Policy%252CCompetition%2520Commission%2520of%2520India%252CData%2520Protection%2520Bill&adf=1456615394&nhd=0&adx=56&ady=86&oid=2&ptt=13&gdfp_req=1&sfv=1-0-37&u_sd=2.625&artc=482%2C285%2C286%2C819%2C361&ati=8%2C8%2C8%2C8%2C8&ard=segment-data.zqtk.net%2Fhtmedia-cna806f%2Cindexexchange%2Copenwrap%2Cprebidrubicon%2Caps&is_amp=3&amp_v=2106182132000&d_imp=1&c=1000852&ga_cid=amp-mltj1tqCIC-oQJqBRChThQ&ga_hid=852&dt=1625873050550&biw=412&bih=773&u_aw=412&u_ah=915&u_cd=24&u_w=412&u_h=915&u_tz=330&u_his=1&vis=1&scr_x=0&scr_y=1171&bc=7&url=https%3A%2F%2Fwww.livemint.com%2Ftechnology%2Ftech-news%2Fwhatsapp-puts-privacy-policy-on-hold-informs-delhi-high-court-11625811860573.html&loc=https%3A%2F%2Fwww.livemint.com%2Ftechnology%2Ftech-news%2Fwhatsapp-puts-privacy-policy-on-hold-informs-delhi-high-court%2Famp-11625811860573.html&ref=android-app%3A%2F%2Fcom.google.android.googlequicksearchbox%2F&bdt=1645&dtd=833&aet=n&__amp_source_origin=https%3A%2F%2Fwww.livemint.com could not be loaded because:

The website I faced it on: https://www.livemint.com/technology/tech-news/whatsapp-puts-privacy-policy-on-hold-informs-delhi-high-court-11625811860573.html

net::ERR_NAME_NOT_RESOLVED

While the advertisement is blocked, this space never used to come before

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20210710-045346_Google](https://user-images.githubusercontent.com/66957409/125145079-a5738c80-e13d-11eb-9340-8d790e459982.png)
![IMG_20210710_050603_007](https://user-images.githubusercontent.com/66957409/125145084-a86e7d00-e13d-11eb-9e1a-d7b2d0af1490.jpg)

How it is in the first picture vs How it is supposed to be in the second picture

</details>

### Additional Information

I updated to a newer version today, could it be that? I checked and HTTPS filtering is enabled as well

**Comment by anastenko** [comment]
@basamaryan Hello. Our developers will take a look at this issue.

**Comment by basamaryan** [comment]
> @basamaryan Hello. Our developers will take a look at this issue.

Thank you

**Comment by admitrevskiy** [comment]
@basamaryan Hi!
Could you provide me a little bit more information about your network? Is IPv6 present? If this is the case, could you try to reproduce the issue on IPv4-only network?

**Comment by basamaryan** [comment]
@admitrevskiy Hi, thanks for getting back to me. I have tested it on a IPv6 enabled network and got that issue. When I tried on an IPv4 only network, ads were hidden properly and there was no issue. Hope this helps

**Comment by admitrevskiy** [comment]
@basamaryan well, this is known issue: we have some issues with IPv6 traffic filtering in auto-proxy mode. We'll try to fix this issue in AG 4.0: all IP tables logic should be redone from scratch and also take into account IPv6 traffic.

**Comment by aliafshany** [comment]
@admitrevskiy 
have you been able to solve this issue in v4 nightly versions?
