### ISSUE TITLE
Export private key of SSL cert

### ISSUE THREAD

**Issue by Duvio** [AdguardTeam/AdguardForAndroid#3902]
You should be able to export the private key of adguards SSL certificate

**Comment by anastenko** [comment]
@Duvio Hello. It doesn't seem like a good idea by means of security.

**Comment by Duvio** [comment]
Yesn't. The button could be hidden in the advanced settings and there should be a warning. I mean, those who would do that know what a private key is and know how to handle it, thus no security risk. I dont want to root every of my devices just to be able to load the private key from the apps /data/data/
