### ISSUE TITLE
please remove Adguard VPN banner from Adguard for android product

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#3903]
This banner is extremely annoing, more then the ads that you block. Once, i created the same issue on your forum, but nobody answered :(

You said that both apps have integration. Ok. But why do you need an annoying banner, that recommend to install Adguard VPN? It isn't more secured then Orbot Tor service that I am using now. I don't want to install your compromising VPN that knows person and traffic. And more I WILL NEVER USE SOME VPNs. THERE NOT SECURED AND NOT ANONYMOUS.

SO LET USERS CLOSE THIS TERRIBLE BANNER or I will just cancel all subscribings to adguard and move to another adblocker. You are not the only adblocking programme. So stop spitting in user's face AND REMOVE THE ADGUARD VPN BANNER IN SETTINGS.

I hope you will understand me.

**Comment by Chinaski1** [comment]
Hello there!

As I have answered before

Honestly, I don't see any good reason for removing the notice in question. The AdGuard VPN app has been specifically designed to work in conjunction with the AdBlocker as they can work perfectly in compatibility mode.
In addition, the item is not on the home screen and does not send annoying notifications, or something like then. Just neatly located in the settings section.
