### ISSUE TITLE
Custom DNS filters are disabled after navigating

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardForAndroid#3906]
### Issue Details
This bug has been displayed and encountered a few different ways, but the main issue is that on devices with a lot of custom DNS filter lists certain actions cause some disabled lists to become enabled and some enabled lists to become disabled.
Now all that is happening is one disabled filter is becoming enabled. This is caused by simple navigation, but also by taking a screenshot.

Steps to reproduce and what happens:

**Method 1**
1. Navigate to the Settings menu.
2. Click on DNS Filtering and notice that it says “10 filters enabled” under DNS requests blocking.
3. Click DNS requests blocking and observe 10 of 11 total lists enabled.
4. Click back and notice that it now says “11 filters enabled” under DNS requests blocking.
5. Click DNS requests blocking and observe that all 11 lists are now enabled.

**Method 2**
1. Follow steps 1-3 above.
2. Take a screenshot and notice that the one disabled list becomes enabled.

- **AdGuard version:**
  4.0 Nightly 16
- **Device:**
 Samsung Galaxy S7 Edge*
- **Device and OS version:**
stock Android 8.0*

### Expected Behavior

All lists should remain in their chosen states until the user makes explicit changes.

### Note

This bug seems to always affect the same lists given the lists aren’t changed. Changing the lists or enabling/disabling lists can change which lists are affected. I’ve also noticed it primarily happens to lists closer to the bottom, but never the last one in the list.

**Comment by anastenko** [comment]
I've managed to reproduce the issue on our test device. The same positions always get disabled after switching DNS filtering off or changing the settings, etc.
