### ISSUE TITLE
Allow/block lists for userscripts

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3908]
> Currently, users cannot set which websites the extension is allowed or not allowed to operate on. Can the extension allow users to set black and white lists like a script manager?

Requested by: 520630

**Comment by Disqu3-mirOir-qt** [comment]
y can with // @exlude and // @match or @include

**Comment by Chinaski1** [comment]
You can disable extensions on certain sites by adding a simple rule with the modifier $extension
- Example: @@||test.org^$extension

[Knowledge base article](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#extension)
