### ISSUE TITLE
Make beta update channel a default one in alpha and beta versions.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#391]
First mentioned here:

http://forum.adguard.com/showthread.php?8074-Adguard-for-Android-Beta-version-2-1-356&p=79882&viewfull=1#post79882

**Comment by ameshkov** [comment]
We'll have to slightly change the build process for this.

**Comment by zebrum** [comment]
since we decided to do it earlier, task is here: #1377
