### ISSUE TITLE
Add realityripple.com & "Find useless filters" functionalities

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3916]
### Problem Description

It's not necessarily a problem, but rather a method of staying concise and using the least amount of code/memory as possible.
### Proposed Solution
I propose to add functionality that improves the way AdGuard handles at least user filters and imported custom lists (for both dns and regular filtering):

1) https://adblockplus.org/en/redundancy_check - This tool will evaluate a list of filters to find out which filters can be removed. It detects duplicates and cases like ||example.com/ads^ and /ads/* where the first is made redundant by the second. We should be able to click a button that does this for all imported lists and user filters. It should also happen automatically after each filter update. This will keep filters tidy and cut down on memory usage.

2) https://realityripple.com/Tools/AdBlock++/ - "This tool will let you merge multiple AdBlock rules into one list of rules without comments or extra lines, improving efficiency." This will also allow all lists added to a single list to be updated in a single network request. This can be done in the app's code so you wouldn't even need to change the GUI. It would basically automatically create the list of rules behind the scenes and update them as one.

With both implemented it would download the redundant entries each update and then remove them immediately afterwards. It would be awesome to do this on a server side because finding and removing redundant entries from a very long list could eat up system resources fairly severely.

### Additional Information
These ideas are mainly to show what's possible and to hopefully help the devs and users to brainstorm new ideas and implement new features for keeping the filters slim, tidy, ordered, and customizable.

**Comment by anastenko** [comment]
@infinitewaveparticle Hello.
That sounds like a good feature request, which is probably better to be done as a separate service, not a feature for a particular platform.
We will think about implementing it.

**Comment by TPS** [comment]
Similar to #3817?

**Comment by anastenko** [comment]
> Similar to #3817?

@TPS Yeah. These issues concern the same thing, although this one describes more detailed feature request.

**Comment by infinitewaveparticle** [comment]
@TPS Similar, yes, but this goes further

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by TPS** [comment]
Is [AGLint](https://github.com/AdguardTeam/AGLint) meant as a 1st step toward this?

**Comment by ameshkov** [comment]
Yeah, AGLint kind of covers this and will cover more in the future.

**Comment by TPS** [comment]
I think https://github.com/AdguardTeam/AGLint/issues/13 point 3 supersedes this issue?
