### ISSUE TITLE
Add an option to globally disable ftp requests

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3917]
Мобильный хром 71.0.3578.99, по ftp - ссылкам

>ftp://84.204.12.2
>ftp://relay.alkotel.ru

при использовании AdGuard 3.6.2 ходит через http - протокол. Почему ?

![2021 07 28_07 39 28~01](https://user-images.githubusercontent.com/12525093/127254021-a1ea370c-7b44-4314-a522-9ae398f9e186.jpg)

**Comment by Chinaski1** [comment]
Добрый день!

Уточните, пожалуйста, какой режим фильтрации используется в приложении?
Manual HTTP proxy?

**Comment by Baltazar500** [comment]
@Chinaski1, он самый.

**Comment by Chinaski1** [comment]
`ftp`  не поддерживается в режиме Manual proxy

**Comment by Baltazar500** [comment]
@Chinaski1, да мне и не нужно фильтровать FTP через adguard. Скажите, как глобально правилами его исключить из фильтрации ? На форуме мне давали вот такое правило :

>@@IP_сервера$network

но оно исключает конкретный сервер из фильтрации. А как отключить фильтрацию для FTP глобально, чтобы ftp не обрабатывалось AdGuard'ом, но проходило черещз его прокси без подобных последствий ?

**Comment by Chinaski1** [comment]
К сожалению, отключить `ftp` глобальными правилами не получится. Только для каждого отдельно взятого случая.

**Comment by Baltazar500** [comment]
> К сожалению, отключить `ftp` глобальными правилами не получится. Только для каждого отдельно взятого случая.

ОК. А как-то решить эту проблему в новых билдах можете ?

Пока выкрутился смаршрутизировав трафик через proxy.pac

>if (url.substring(0, 4)=="ftp:"){return "DIRECT";};

Но этот метод требует наличие файла proxy.pac на удалённом или локальном сервере. Можно конечно в хроме прописать персонально прокси для всех протоколов и указав пустой прокси для ftp, но использование proxy.pac 
- \ более универсальное решение.

**Comment by anastenko** [comment]
@Baltazar500 Попробуем придумать решение после выхода версии 4.0.

**Comment by sfionov** [comment]
FTP протокол с 2021 года не поддерживается ни одним из мажорных браузеров, задача потеряла актуальность
