### ISSUE TITLE
Multiple DNS Upstream

### ISSUE THREAD

**Issue by What-Zit-Tooya** [AdguardTeam/AdguardForAndroid#3918]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Is possible to add multiple DNS like on adguard home. On adguard home i can add more DNS upstream and let adguard choose fastest server.
Also i combine it with DNScrypt-proxy. On DNScrypt-proxy we can uncomment `server` section and add more DNS servers

**Comment by anastenko** [comment]
@What-Zit-Tooya Hello.
Yep, you can add multiple upstreams while adding a DNS server(one per line).

**Comment by What-Zit-Tooya** [comment]
> 
> 
> @What-Zit-Tooya Hello.
> Yep, you can add multiple upstreams while adding a DNS server(one per line).

Not available on adguard for android, it only support (i think) on adguard home.

**Comment by anastenko** [comment]
@What-Zit-Tooya This feature is already implemented. Are you saying in doesn't work the way it supposed to?
Could you give us more details on what you mean?

**Comment by What-Zit-Tooya** [comment]
> 
> 
> @What-Zit-Tooya This feature is already implemented. Are you saying in doesn't work the way it supposed to?
> Could you give us more details on what you mean?

Sorry, i mean when i add multiple servers, can i add multiple type DNS like DOH, DOT, UDP, QUIC , DNSCrypt, (all blended)?

**Comment by admitrevskiy** [comment]
@What-Zit-Tooya Hi! 
Yes, you can add multiple DNS types when adding a custom server. However, unlike Home, a parallel resolve has not been implemented in the android yet.

**Comment by infinitewaveparticle** [comment]
i very much look forward to parallel resolve being added for Android

**Comment by artemiv4nov** [comment]
So, let's try to implement this feature in future releases.
