### ISSUE TITLE
Sticky Password app asks for a certificate if HTTPS filtering is enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#392]
https://play.google.com/store/apps/details?id=com.stickypassword.android - Google Play link;

Originally posted on forum: 
http://forum.adguard.com/showthread.php?9847-Adguard-%D0%B4%D0%BB%D1%8F-Android-%D0%91%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-2-5-70&p=80051&viewfull=1#post80051

**Comment by Revertron** [comment]
Works normally, no complains from this app.
