### ISSUE TITLE
Sponsored posts of Imgur aren't blocked

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardForAndroid#3920]
### Issue Details
There's an issue with the Imgur App. While scrolling Imgur front page for an extended period of time, a sponsored post comes through with an advertisement showing.  

When turning the Adguard VPN on, the Adguard App gives the notification starting with "The battery saving method of your system can...", which provides lots of info about how to effectively set up the phone to work with Adguard, but it didn't help. 

Things tried: 
- Setting Adguard VPN as an Always-on VPN through phone settings
- Using the built in watchdog feature in Adguard
- Monitoring the Adguard filtering log and manually blocking sketchy and irrelevant links originating from Imgur
- Pretty much every suggestion listed by the "battery saving method" notification.

Ticket number 520644

**Comment by artemiv4nov** [comment]
No more support requests about this issue, closed.
