### ISSUE TITLE
Lines with comments (!) in custom rules are treated by the counter

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3922]
Строки с комментариями (!) в пользовательских правилах обрабатываются счётчиком AdGuard как правила. Можно это поправить ? А то оставляю пометки для себя, что за правила я добавил, а счётчик AdGuard считает их за правила, хоть и игнорирует. Проблема косметическая, но глаз мозолит

**Comment by artemiv4nov** [comment]
Должно поправиться в 4.0
