### ISSUE TITLE
While on IPv6 connections, AdGuard for Android fail to connect to DNS-over-QUIC servers that are only accessible over IPv4

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#3927]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v4.0 nightly 14
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Motorola One Zoom
- **Operating system and version:**
  - Android 10; build QPHS30.29-Q3-28-13-10-8; security update set 1st of July 2021
- **Root access:**
  - No

### Expected Behavior

AdGuard for Android scans for both IPv6 and IPv4 when scanning the availability of DNS-over-QUIC servers.

### Actual Behavior

A rather odd bug seems to be present in nightly 14. If the phone has access to an IPv6 connection, AdGuard for Android tries to connect to DNS-over-QUIC servers over IPv6 only, with no fallback to IPv4, causing the connection to fail if the DNS server is only accessible over IPv4, which they may be due to low-quality DDNS providers. This currently affects `quic://dandelionsprout.asuscomm.com:48582` rather heavily.

Most relevant lines of [the log file](https://github.com/AdguardTeam/AdguardForAndroid/files/6910435/adguard.log):
```
02:23:54.447 [Thread-91] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-07-31 02:23:54.447126] [12903] [DOQ upstream] [info] Connected to [::ffff:84.202.44.53]:48582
02:23:59.448 [AsyncTask #4] WARN  com.adguard.android.filtering.dns.c - Failed to test quic://dandelionsprout.asuscomm.com:48582
java.lang.IllegalArgumentException: Request timed out
```

### Screenshots

N/A (at the time of writing)

### Additional Information

I feel confident that I've been able to rule out the possibility of any port conflicts on the DNS server's end, as well as any firewall/SELinux problems (as I've turned off both firewalld and SELinux).

Closely related to https://github.com/AdguardTeam/AdguardForWindows/issues/3878

**Comment by sfionov** [comment]
Is the problem reproduced on 4.0 nightly 20?

**Comment by DandelionSprout** [comment]
From what I can tell after updating to nightly 20 just now: Yes. 
![Screenshot_20210802-112219](https://user-images.githubusercontent.com/22780683/127837947-eb1f1050-f7ea-40a8-90d6-6d9dfe53b660.png)
