### ISSUE TITLE
If user edited pref.ipv4.routes.excluded in an earlier version the newly added telecoms aren't added by updating AdGuard

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3929]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

 I just now noticed that on my phone the excluded IPs for WiFi calling (IranCell thru TurkCell) are not present (but they are on devices on which I never edited this list). This leads me to believe that editing this list in the past somehow caused the new entries to not be added when future updates were made.

- **AdGuard version:**
  - 4.0 Nightly 20, but has been present since before the version(s) that added IranCell thru Turkcell
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy S7 Edge
- **Operating system and version:**
  - Android 8
- **Root access:**
  - No

### Expected Behavior
All default items should be included, as well as persisting user edits.

### Actual Behavior
User edits persist, but newly added defaults are not added with an app update.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by anastenko** [comment]
@infinitewaveparticle Truly so. This is an expected behavior, but it will be reworked in v4.0.

**Comment by infinitewaveparticle** [comment]
I would think the edits would remain, but anything new would be added. It seems to affect many low level settings, actually. If the user CAN edit them, then the user should also expect fixes and additions to be made by updating the app. Otherwise, having these in an editable setting is pointless. However, it is nice to be able to edit them so I hope the reworking doesn't take away our ability to do that. I hope the 4.0 release comes with at least 3 levels of available settings; 4 would be ideal:

"Beginner (what's DNS?)"
"Novice (I'm a lurker in low-level settings)"
"Expert (I write my own extensions)"
"Superuser (can seriously break everything)"

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by artemiv4nov** [comment]
@infinitewaveparticle Hi!
In the AdGuard 4 version, you will still have the possibility to change Low-Level settings.
