### ISSUE TITLE
Adguard cannot install a certificate (CertInstall activity is present, but broken)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#393]
Report:
http://forum.xda-developers.com/showpost.php?p=66017008&postcount=866

![screenshot_2016-03-24-18-11-24](https://cloud.githubusercontent.com/assets/5947035/14048305/7d8c5df0-f2be-11e5-859e-34fff0593f2a.png)

**Comment by Revertron** [comment]
Done.
