### ISSUE TITLE
Add a way to submit a recent debug log through the app

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3930]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

 Currently, submitting logs requires turning on Record Everything, exporting the logs to a zip file, and then emailing the logs with timestamps. This should be faster and easier.

### Proposed Solution

 Similar to how Signal does it, simply allow the user to include the debug log with a Support Request from within the app. You can also have the app upload it to debuglogs.org and simply copy the link to a support request. This can be done in addition to turning on 'Record Everything' or... (see below)

### Alternatives Considered

...if it's not too resource-intensive, have the AdGuard app, by default, create a running 5-10 minute Record Everything log that continuously overwrites itself.

**Comment by anastenko** [comment]
@infinitewaveparticle Hello.
Thank you for the suggestion, but we'll unlikely change the debug logs collecting, since sometimes users have to collect the logs during several hours, so "5-10 minutes" time limit might overwrite necessary data.
Also some data can be sent with the feedback if checking the relevant checkbox.

**Comment by infinitewaveparticle** [comment]
@anastenko I didn't mean to overwrite the regular logs and get rid of their settings, but instead just an option to send logs for an error that is encountered quickly. What I meant is that the ongoing log could overwrite itself continuously, not replace the logging found in Settings currently. The reason I make this suggestion is because all of the logs I've had to collect were for issues that only happened over the span of a few seconds to maybe 6-8 minutes. I assume a lot of issues are like this. My suggestions could remove some of the friction for reporting issues that don't require long logs.

I know about the checkbox, but that generally misses the issues that require further logs.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by anastenko** [comment]
@infinitewaveparticle Keeping debug logs turned on is quite consuming. Although it sounds useful to make automatic inclusion of debugging logs for like 10 minutes, the best option for now is keeping it the way it is. Maybe we'll implement something like this, but not now.

**Comment by infinitewaveparticle** [comment]
👍

Sent from ProtonMail mobile

-------- Original Message --------
