### ISSUE TITLE
AdGuard player does not play videos from youtube.com (full version of website via "share" link)

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3932]
Собственно, сабж. Плеер AdGuard не воспроизводит ролики с youtube через функцию "поделиться ссылкой). Безостановочно куролесит по кругу спиннер прогресса после передачи ссылки :/ AdGuard 3.6.2

Механизм экстракции ссылок на видео с ютуба фиксированный, не обновляемый ? Мб стоит сделать его в таком случае обновляемым ?

**Comment by anastenko** [comment]
@Baltazar500 
У нас проблему воспроизвести не удаётся, всё работает нормально. Возможно зависит от конкретного ролика или самого приложения YouTube.
Какую версию YouTube вы используете?

**Comment by Baltazar500** [comment]
>Какую версию YouTube вы используете?

Эээ. Никакую. Разве у вас там не встроенный плеер работает на базе какого-нибудь фреймворка ?

![2021 08 04_21 24 28~01](https://user-images.githubusercontent.com/12525093/128172911-0063aadf-b7f6-4df4-b2af-437b161cd286.jpg)

При передаче ссылки НА AdGuard он использует ютуб - приложение ??? Я думал тут та же мхема, что и в NewPipe :/

**Comment by anastenko** [comment]
@Baltazar500 Я имею в виду ситуацию, когда вы в приложении YouTube нажимаете "Share" и у вас открывается плеер. 
Этот плеер создан с использованием библиотеки, которая использует API ютуба, поэтому любые проблемы самого ютуба могут проецироваться и на плеере.

**Comment by anastenko** [comment]
@Baltazar500 Сейчас проверили на девайсе без ютуба - через браузер также запускается плеер и видео работает.
Можете поделиться с нами точной ссылкой, чтобы мы смогли проверить?

**Comment by Baltazar500** [comment]
>Сейчас проверили на девайсе без ютуба - через браузер также запускается плеер и видео работает. Можете поделиться с нами точной ссылкой, чтобы мы смогли проверить?

Ну если вы делали вот так :

![Screenshot_20210805_222120](https://user-images.githubusercontent.com/12525093/128349001-5f6e0090-2076-4777-ad75-047ba8996cda.jpg)
![Screenshot_20210805_222047](https://user-images.githubusercontent.com/12525093/128349039-9045a200-a914-4731-bb9f-f2c5e9a7d11d.jpg)

то любая "watch" ссылка, например эта https://www.youtube.com/watch?v=RQAOmtNW52Y

В логе вот такие строки обнаружились :

>`22:12:52.851 [main] INFO  c.a.android.ui.YoutubeActivity - Opened video: null`
>`22:12:52.852 [main] WARN  c.a.android.ui.YoutubeActivity - Trying to open empty video!`

**Comment by anastenko** [comment]
@Baltazar500 Да, мы тестировали имеено так.
С этой ссылкой удалось воспроизвести: дело действительно в видео - правообладатель запретил воспроизведение с других сайтов, кроме Youtube.
С другой стороны, нет необходимости открывать видео в отдельном плеере, если реклама в браузере изначально блокируется.

**Comment by Baltazar500** [comment]
>дело действительно в видео - правообладатель запретил воспроизведение с других сайтов, кроме Youtube.

Значит мне поголовно попадались именно такие ролики т.к. от плеера AdGuard'a мне воспроизведения так и не удалось добиться :(

>С этой ссылкой удалось воспроизвести:

Ну т.е. ваш плеер- это НЕ универсальное решение для просмотра роликов по типу NewPipe и экстрактит только те стримы, что лежат на поверхности и не "защищены" с помощью различных "уловок" ?

>С другой стороны, нет необходимости открывать видео в отдельном плеере, если реклама в браузере изначально блокируется.

Мне в браузере смотреть менее комфортно, чем через плеер. Да и лаги при подгрузке страниц ютуба напрягают. Мне быстрее "спустить" плееру линк на воспроизведение, чем дожидаться окончательной прогрузки сираницы ютуба и старта ролика на ней.

**Comment by anastenko** [comment]
@Baltazar500 Удалось понять суть проблемы. Дело не в видео, а в способе открытия плеера, т.к есть "Поделиться" под видео, а есть опция "Поделиться" через дополнительное меню (три точки) в браузере.

**Comment by Baltazar500** [comment]
>Удалось понять суть проблемы. Дело не в видео, а в способе открытия плеера, т.к есть "Поделиться" под видео, а есть опция "Поделиться" через дополнительное меню (три точки) в браузере.

Извините, а вы на мои скриншоты хоть смотрели ? Структура меню и пункты в нём как минимум на это указывали. Не поленился и залез в упомянутое вами меню "поделиться" под видео и даже близко там AdGuard'a не нашёл :

![2021 08 10_11 07 04~01](https://user-images.githubusercontent.com/12525093/128793481-ac690943-a2b3-46a5-b5c5-a20697c02836.jpg)
![2021 08 10_11 07 13~01](https://user-images.githubusercontent.com/12525093/128793502-dd3fe8e7-9f1d-4fad-b5f0-f65e48d8591f.jpg)
![2021 08 10_11 07 22~01](https://user-images.githubusercontent.com/12525093/128793515-a84b4887-da11-453b-a670-2075ceaeb337.jpg)

Из всего этого списка у меня есть разве что WhatsApp, а значит он даже не регулируется системой, а составляется самим сервисом и откуда у вас там AdGuard мог в0яться для меня загадка.

**Comment by anastenko** [comment]
@Baltazar500 Скорее всего AdGuard у вас не появляется, потому что используете полную версию сайта, а не мобильную. Если открывать с мобильной версии, приложение будет предложено в "Поделиться".
