### ISSUE TITLE
com.zattoo.player (switzerland only)

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#3933]
issue: live tv not work because imasdk.googleapis.com inside adguard base

fixed solution:
@@||imasdk.googleapis.com^$app=com.zattoo.player

thanks

**Comment by Chinaski1** [comment]
Fixed on filters side.

Thank you for the report!

**Comment by Disqu3-mirOir-qt** [comment]
@||imasdk.googleapis.com^$app=fr.tf1.mytf1|com.sfr.android.redtv


too

**Comment by Chinaski1** [comment]
@Disqu3-mirOir-qt 
`com.sfr.android.redtv` - I was able to find this app
But `fr.tf1.mytf1` looks like a domain. The `$app` modifier should not contain the address, there should be the name of the application
