### ISSUE TITLE
 Как включить полноценный YouTube на Семейном DNS?

### ISSUE THREAD

**Issue by 17721** [AdguardTeam/AdguardForAndroid#3934]
Почему нет настройки добавить вручную сайт (youtube) в белый список, при включенном Семейном ДНС? Я хочу оставить и безопасный поиск, и youtube. Гугл и так уже вычистил его. Почему Вы не можете сделать такую простую опцию на усмотрение пользователя?

**Comment by Chinaski1** [comment]
Приветствую!

К сожалению, добавить данную опцию не представляется возможным.
Дело в том, что когда вы включаете семейный DNS и переходите на Youtube или Google поиск, они активируют безопасный режим на своей стороне. Это происходит не стороне AdGuard. Мы лишь отправляем запрос на включение данной функции.

**Comment by Chinaski1** [comment]
Также закрываю идентичную задачу в репозитории  Windows - https://github.com/AdguardTeam/AdguardForWindows/issues/3886
