### ISSUE TITLE
hasIPv6NetworkInterface function returns wrong value on IPv4/IPv6 network randomly

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3939]
- **AdGuard version:**
  -   4.0 nightly 21

### Actual Behavior
hasIPv6NetworkInterface sometimes returns a `false` value when switching from IPv6-only to IPv6/v6 networks. It violates DNS logic since we set `IPv6 blocking response` flag to `true`

**Comment by artemiv4nov** [comment]
It has already been done in the 4.0 version. Please follow the nightly updates.
