### ISSUE TITLE
de.lotum.whatsinthefoto.us crashes when HTTPS filtering is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#394]
http://forum.xda-developers.com/showpost.php?p=66018724&postcount=867

**Comment by Revertron** [comment]
I am unable to find "de.whatsinthefoto.us".

**Comment by ameshkov** [comment]
I guess here it is:
https://play.google.com/store/apps/details?id=de.lotum.whatsinthefoto.us&hl=en

**Comment by Revertron** [comment]
This puzzle works perfectly now.

**Comment by ameshkov** [comment]
Ok then

**Comment by ameshkov** [comment]
Hm, it crashes:
http://forum.xda-developers.com/showpost.php?p=66496640&postcount=1071

**Comment by ameshkov** [comment]
Added to default exceptions list.
