### ISSUE TITLE
AdGuard interferes with app downloads.

### ISSUE THREAD

**Issue by stanislav-atr** [AdguardTeam/AdguardForAndroid#3946]
https://github.com/AdguardTeam/AdguardFilters/issues/90175

https://play.google.com/store/apps/details?id=nl.home_academy.app

> The (Dutch language) audiobook app needs a connection to the internet to update the bookshelf and to download new audiofiles. Updating the bookshelf works always, but downloading new audio files gets blocked by AdGuard.
> I did some testing, and the resolution seems to be:
> Go to Menu → Settings → Advanced → Low-level settings. Disable "pref.vpn.disable.pause" and "pref.vpn.disable.reconfigure".
> But I would like to have a more substantial fix. Is it possible to add the app to some sort of 'allow list'?

Also reproduced on Android 10 + AG v4.0 nightly 20 (61) with filters, DNS filtering, stealth mode and vpn turned off.

**Comment by TPS** [comment]
I'm also having this problem with Google Play updates, so it feels a lot like how https://github.com/AdguardTeam/AdguardForAndroid/issues/3355 was fixed.

**Comment by artemiv4nov** [comment]
There is an issue related to Android app downloads: it doesn't work on some Android versions if VPN is enabled. So, to make the audiobook app worked, you need to disable filtering of app downloads in the App management section.
