### ISSUE TITLE
Option to skip this app update

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#3947]
Right now, if I wish to skip an update version, I've no way to tell the app.

Depending on whether I'm on the update page or notification, my only options are <kbd>Update</kbd> or <kbd>Learn More</kbd>.

I propose another option <kbd>Skip</kbd> (this version) in _notification_ to keep app from notifying _every_ time it updates filterlists until _next_ version, but keep option to <kbd>Update</kbd> on update _page_ (just in case I change my mind).

**Comment by anastenko** [comment]
@TPS Hello.
We're not planning on implementing such feature, since we want the biggest amount of users to have the newest version available. Updates make the application better and fix the old bugs.

**Comment by TPS** [comment]
How about from 1 _nightly/beta_ version to the next?  Sometimes, you suspect such is causing a problem, so you need to avoid the update for some time.

**Comment by anastenko** [comment]
@TPS All updates are important for fixes and new features, so even if it causes some issues it might help to prevent bigger problems. 
Nightly version is unstable by default, so it wouldn't be a surprise one can cause problems sometimes. Release channel updates slower, so you can stick with this one.
