### ISSUE TITLE
air.com.freshplanet.games.SongPop2 shows untrusted certificate warning

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#395]
> SongPop 2, a.k.a. air.com.freshplanet.games.SongPop2, throws up cert warnings on start-up: The server that the application is connecting to is unverified.

> I have to click 'Trust for session' on about 20 such warnings before the game finally starts and is playable.

http://forum.xda-developers.com/showpost.php?p=66018724&postcount=867

**Comment by Revertron** [comment]
Works normally now, I think this is an old bug.

**Comment by Revertron** [comment]
Added 2 domains to ssl_exceptions:
megapop-prod.appspot.com
wam-mobile.appspot.com

**Comment by ameshkov** [comment]
That was not enough:( 

http://forum.xda-developers.com/showpost.php?p=66377524&postcount=1034

**Comment by ameshkov** [comment]
http://forum.xda-developers.com/showpost.php?p=66496640&postcount=1071

Added to default exceptions list.
