### ISSUE TITLE
hd.loginfilms.club app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3950]
@adguard-bot commented on [Sat Aug 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91908)

### Issue URL (Incorrect Blocking)
 [https://hd.loginfilms.club](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhd.loginfilms.club)
### Comment
> Здравствуйте! В приложении Filmsclub https://hd.loginfilms.club при включённой защите Adguard нет возможности просматривать контент(приложение не видит сеть).

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DVVlaIQ.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/28FzNV5.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.1.2
AdGuard product: | AdGuard for Android v3.6.2 RC 2 (22)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | disabled

**Comment by Alex-302** [comment]
Без фильтров и с гугловым DNS повторяется.
Ссылка на приложение: https://hd.loginfilms.club/media/FilmsClub.apk

**Comment by admitrevskiy** [comment]
Приложение не работает с любым активным ВПН. Завел задачу в их issue трэкере вконтакте, других не нашел: https://vk.com/topic-16906714_40901556

![rezist](https://user-images.githubusercontent.com/32459082/130796706-2c330acb-b96b-4d1a-9035-9b1c0bf481d7.jpg)

**Comment by Chinaski1** [comment]
@deartvonrud 

Видимо проблема на стороне приложения пока не была исправлена (Приложение не работает с любым активным ВПН).

**Comment by deartvonrud** [comment]
@Chinaski1 

Увидели комментарий на их трекере, спасибо! Передадим пользователю.
