### ISSUE TITLE
browser file adguard update error

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardForAndroid#3954]
![Screenshot_20210829-051850.jpg](https://user-images.githubusercontent.com/41585567/131237134-cf6f93cd-b17f-477d-9719-a3257030b81e.jpg)

![Screenshot_20210829-051905_1.jpg](https://user-images.githubusercontent.com/41585567/131237163-062a66f6-87cc-49c0-8f83-16c2f69018d7.jpg)

behavior issue:

when use browser file with adguard (cf picture) when do change inside file and do update adguard not get update files 

only past absolute path manualy work for get update change files 

thank you

**Comment by Chinaski1** [comment]
As far as I understand you make local changes in the script, then you update the AdGuard extensions?
These changes will not be taken into account by the application until you re-specify the script path.
So this is the expected behaviour of the app.

**Comment by Disqu3-mirOir-qt** [comment]
when use adguard browser update no take modification:

https://user-images.githubusercontent.com/41585567/131340921-0d170966-c7d8-4758-87a3-7c1dfac5eb44.mp4

-----

when not use adguard browser my modification take when update:

https://user-images.githubusercontent.com/41585567/131341166-0538951c-c3af-481f-9c17-7cda627962ca.mp4

**Comment by artemiv4nov** [comment]
When we add a filter by URL or some file picker, we place the file inside our application, so the external file changed will not be applied.
