### ISSUE TITLE
Шрифт

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3955]
Заметил вот что:

<a href="https://fastpic.org/view/115/2021/0829/82c4a72f60b18b97605c67c9c6ba2096.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0829/96/82c4a72f60b18b97605c67c9c6ba2096.jpeg" border="0"></a> <a href="https://fastpic.org/view/115/2021/0829/a5235f9d6caf186f33b220e79f6b28d1.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0829/d1/a5235f9d6caf186f33b220e79f6b28d1.jpeg" border="0"></a>

Отчетливо видно отличие в шрифте.

**Comment by Chinaski1** [comment]
Все верно. Количество заблокированных запросов специально выделено жирным шрифтом.

**Comment by GdeZsqyAY** [comment]
> Все верно. Количество заблокированных запросов специально выделено жирным шрифтом.

Что же Вы на главной странице тогда не выделяете количество заблокированной рекламы и счетчиков? Зато делаете выделение там, куда редко кто заходит.

Детский сад ей богу !!!
