### ISSUE TITLE
Conflict with Bypass Paywalls Clean Firefox Android addon

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#3958]
Adguard Android and Bypass Paywalls Clean (BPC) addon for Firefox Android (https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean) conflict somehow. Tested on both Firefox Android Nightly and Fennec, on ft.com and economist.com - my two go-to sites. Added BPC through Fenix addon collection (instruction in gitlab link above).

If Adguard Android is enabled, BPC will not work on ft.com (but still works on economist.com); and if Adguard Android is disabled, BPC works as expected on ft.com (as well as economist.com).

No conflict on desktop environment.

I've reported this to BPC too (https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean/-/issues/266). Hope a solution can be found.

--- _Btw, Adguard Android does not automatically filter https for Firefox Android Nightly and Fennec. I had to manually turn that on. Not sure if I need to submit another request for this._ ---

**Comment by snhv** [comment]
It seems there is a conflict between a certain Adguard setting and Bypass Paywalls Clean (BPC). BPC developer also uses Adguard and has no issue. I attach my Adguard logs here and my Adguard settings below FYI.
[adguard_logs_3.6.23_0509_094327.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/7111754/adguard_logs_3.6.23_0509_094327.zip)

{
  "advancedPreferences" : {
    "pref.vpn.capture" : false,
    "pref.vpn.disable.pause" : true,
    "pref.vpn.ipv6.force" : false,
    "pref.boot.startup.delay" : 10,
    "pref.har.capture" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.notify.on.unknown.ca" : true,
    "pref.vpn.tun.mtu" : 9000,
    "pref.root.set.oom_adj" : false,
    "pref.vpn.disable.reconfigure" : true,
    "pref.proxy.block.ipv6" : false,
    "pref.vpn.ipv6.disable" : false,
    "pref.root.clear.youtube" : true,
    "pref.enforce.paused.notification" : false,
    "pref.removed.html.log" : false,
    "pref.dns.blocking.type" : 1,
    "pref.samsungpay.autopause.enable" : false,
    "pref.proxy.disable.reconfigure" : true,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.vpn.android10.mitigate" : false,
    "pref.vpn.ipv4.bypass" : false,
    "pref.vpn.ipv6.bypass" : false
  },
  "androidVersion" : "8.0.0 (sdk=26)",
  "applicationId" : "340436a9d7b8a7cb",
  "autoStartEnabled" : true,
  "automationEnabled" : false,
  "browsingSecurityEnabled" : true,
  "contentScriptVersion" : "1.1.23",
  "coreLibsVersion" : "1.7.211",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "customFiltersEnabled" : true,
  "disabledDnsRules" : [ ],
  "disabledRules" : [ ],
  "disabledWhitelistRules" : [ ],
  "dnsBlocking" : true,
  "dnsEnabled" : true,
  "dnsLibsVersion" : "1.5.26",
  "dnsUpstreamSettings" : "Server(upstreams=[https://dns9.quad9.net:443/dns-query], name=Quad9 DNS doh, id=21, providerId=10019)",
  "dnsUserfilter" : "",
  "enabledDnsFilters" : [ "Name: AdGuard DNS filter; Id: 15; Subscription URL: https://filters.adtidy.org/android/filters/15_optimized.txt" ],
  "enabledFilterNames" : [ "AdGuard URL Tracking filter", "AdGuard Base filter", "AdGuard Tracking Protection filter", "AdGuard Social Media filter", "AdGuard Annoyances filter", "ABPVN List", "AdGuard Mobile Ads filter" ],
  "environment" : "release",
  "eventsEnabled" : true,
  "eventsLibVersion" : "1.1.1",
  "filterAppsTraffic" : true,
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "LOW_PRIORITY",
  "installerPackage" : "com.google.android.packageinstaller",
  "kernelVersion" : "3.18.71-perf-g1292dd379ef4",
  "kitLibVersion" : "2.0.74.1",
  "outboundProxyEnabled" : false,
  "outboundProxyList" : [ "Proxy id=2 name=Getflix Montreal  default=false settings=ca-mr2-smart.serverlocation.co:1080", "Proxy id=1 name=Getflix Toronto  default=true settings=ca-tor2-smart.serverlocation.co:1080" ],
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : true,
  "scriptletsLibraryVersion" : "1.3.14",
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-FF8fpM_MKBPlmDK9jgdBQg==/base.apk",
  "sslMitmConfiguration" : "{\"mitmListMode\":\"WHITELIST\",\"certificateStoreType\":\"USER\",\"filterEvCertificates\":true,\"mitmList\":\"3648 domains\",\"enforcedHttpsFilteringAppsHash\":1485181909,\"certificateHash\":-2008300819}",
  "stealthModeConfiguration" : {
    "blockLocation" : true,
    "blockPush" : true,
    "blockWebRtc" : true,
    "disableAuthorizationThirdPartyRequests" : true,
    "disableCacheThirdPartyRequest" : true,
    "firstPartyCookieValue" : 4320,
    "hideIpAddress" : true,
    "hideReferer" : true,
    "hideSearchQuery" : true,
    "hideUserAgent" : true,
    "ipAddress" : "",
    "referer" : "",
    "removeXClientDataHeader" : true,
    "selfDestructingFirstPartyCookie" : false,
    "selfDestructingThirdPartyCookie" : false,
    "sendDoNotTrackHeader" : false,
    "stripTrackingParameters" : false,
    "thirdPartyCookieValue" : 180,
    "trackingParametersList" : "utm_source utm_medium utm_term utm_content utm_campaign utm_referrer yclid gclid fbclid _openstat fb_action_ids fb_comment_id fb_action_types fb_ref fb_source action_object_map action_type_map action_ref_map",
    "userAgent" : ""
  },
  "stealthModeEnabled" : true,
  "stealthScriptVersion" : "1.1.2",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "userScriptWrapperVersion" : "1.2.6",
  "userfilter" : "",
  "userscriptsEnabled" : true,
  "userscriptsEnabledList" : [ "Name: AdGuard Extra; Version: 1.0.306; Subscription URL: https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js" ],
  "versionName" : "3.6.23",
  "versionTitle" : "3.6.2",
  "whitelist" : ""
}

**Comment by snhv** [comment]
Bypass Paywalls Clean (BPC) developer points out that Stealth mode is the culprit. I've tried multiple combinations within Stealth mode to no avail, so I leave Stealth mode disabled for now. Weird that I have no problem on the desktop.
I leave this issue open in case you want to find a fix for this particular use case. Sorry for the trouble.

**Comment by Chinaski1** [comment]
Hello @snhv 

Looks like that the reason for the compatibility conflict is that the `hide referer` function is switched on.

As for the need to manually enable HTTPS certificates in FF nightly, this is a [known case](https://kb.adguard.com/en/android/solving-problems/firefox-certificates).

**Comment by snhv** [comment]
> Looks like that the reason for the compatibility conflict is that the `hide referer` function is switched on.
Hi thanks @Chinaski1. BPC developer also told me to disable hideUserAgent & hideReferer. But I've actually found out for my case with ft.com, it is to disable hideReferer & hideSearchQuery.

> As for the need to manually enable HTTPS certificates in FF nightly, this is a [known case](https://kb.adguard.com/en/android/solving-problems/firefox-certificates).
I'm aware of this case. But even after those instructions, Adguard does not turn on https filtering for FF nightly automatically. I still need to turn it on manually in App Management. Small nuisance though. Thanks again.
