### ISSUE TITLE
Gas Buddy does not work with HTTPS filtering enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#396]
https://play.google.com/store/apps/details?id=gbis.gbandroid&hl=en

http://forum.adguard.com/showthread.php?9846-Adguard-for-Android-Beta-version-2-5-70&p=80092#post80092

Ticket ID:
SSU-532-32333

**Comment by Revertron** [comment]
I was unable to install it to my device - google says there is no eligible devices for me, may be it is restricted only for USA :-/
Added it to net_exclusions

**Comment by BooBerry** [comment]
You can manually download the .apk file for any app off the Play Store regardless of region restriction and manually install it by using this site: http://apps.evozi.com/apk-downloader/

**Comment by ameshkov** [comment]
@Revertron net_exclusions is anyway a wrong solution for this app. The problem is with https filtering only.

**Comment by Revertron** [comment]
Hmm, it's weird. I've installed it, created an account, logged in without problems. I don't see any problems there :-\

**Comment by ameshkov** [comment]
Are you sure it is removed from exlcusions in your case?:)

**Comment by Revertron** [comment]
@ameshkov You got me :)

**Comment by ameshkov** [comment]
@Revertron 
I see nothing suspicious in the user's log too (SSU-532-32333), but he claims that adding the app to exception resolved that issue.

Let's do it just in case.

**Comment by ameshkov** [comment]
Added

**Comment by Bohdan-SUP** [comment]
Should the ads be filtered in this case?
Just want to be 100% sure.

**Comment by ameshkov** [comment]
It should. The problem is that we forgot to remove gas buddy from net exclusions list that's why AG is missing ads in the current stable version.
