### ISSUE TITLE
Наведите порядок среди открытых и закрытых темах.

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3960]
Неужели Вам так тяжело закрывать темы которые уже исправлены?

Пример: Если верить этому списку

https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.6.3-beta-1

То моя тема по - The issue with changing the language in the DNS section - уже имеет решенную проблему, но если зайти сюда

https://github.com/AdguardTeam/AdguardForAndroid/issues?page=2&q=is%3Aissue+label%3A%22Version%3A+AdGuard+v3.6.3%22+is%3Aopen

То она является еще открытой.

Эта Ваша лень усложняет отслеживать актуальный статус той или иной темы.

**Comment by Chinaski1** [comment]
Задачи как правило закрываются только после выхода релиза(не беты).
