### ISSUE TITLE
User script is not update from a local file using "Reinstall" button

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3961]
Собственно сабж.

Не обновляется UserJS скрипт (ака расширение) из локального файла при его изменении по кнопке "переустановить".

Из-за этого замаялся тестировать свой скрипт.

Ещё момент. При указании пути до скрипта при установке, запилите указание пути до него без префикса "file://" (или пусть обрабатываются оба варианта).

Ведро 5.1, adguard 3.6.2

**Comment by Baltazar500** [comment]
@Chinaski1, и вправду. Забыл, что тикет по подобной проблеме открывал. Да просто снова "припекло" и на автомате создал тикет, дополнительно подразобрав вопрос. Проблему подтверждаете ? Фиксов ждать ?

**Comment by Chinaski1** [comment]
Да, исправим в v4.n.

**Comment by artemiv4nov** [comment]
В 4.0 переработали механизм переустановки, должно получше стать. Путь без file:// делать не будем.
