### ISSUE TITLE
Add oisd.nl list(s) to the filter lists

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3964]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

The lists on https://oisd.nl are curated from a large selection of lists found from all over the web. The list is also edited so as to not break anything. It's a powerful list to use in my opinion, and should be included.
### Proposed Solution

Add the options to include https://abp.oisd.nl/ &/or https://abp.oisd.nl/basic/ to the list of Filters.

**Comment by Chinaski1** [comment]
Hello @infinitewaveparticle 

As I understand filters that you mentioned are a universal set of rules aimed at a wide range of actions.
Many of the rules overlap with the lists already present in AdGuard's filters, so there is no apparent reason to add the specified list to the kit.

If you are interested, you can check [this article](https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository) for more information
Btw, you can always add any lists you like under the custom filters section.

**Comment by infinitewaveparticle** [comment]
I definitely added it as a custom filter. I just think it's a great addition for AdGuard because the maintainer puts a lot of work into prioritizing functionality over blocking while also maintaining one of the most comprehensive lists I've seen to date. Ideally it would be the only list to select for users who run into issues with enabling a bunch of other filters and could be added to the app with that explanation. In my opinion it's better than other lists that attempt to whitelist and fix broken sites.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment]
When adding third-party filters, we focus on the uniqueness of the content. 
This means that only those filters will be added that have no counterparts in AdGuard.
