### ISSUE TITLE
Дубликат

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3968]
Открыть - Настройки/Блокировка контента/Фильтры/Другие и выбрать DNS фильтр

<a href="https://fastpic.org/view/115/2021/0911/10301695480355a70b631b51d0f8a806.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0911/06/10301695480355a70b631b51d0f8a806.jpeg" border="0"></a>

Открыть - Настройки/Фильтрация DNS и выбрать DNS-фильтр AdGuard

<a href="https://fastpic.org/view/115/2021/0911/246d98bafb41071af8de2ad5c97f9891.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0911/91/246d98bafb41071af8de2ad5c97f9891.jpeg" border="0"></a>

Это один и тот же фильтр, если судить по **URL-адрес подписки**

<a href="https://fastpic.org/view/115/2021/0911/842026efe622eca008a279b85f075a94.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0911/94/842026efe622eca008a279b85f075a94.jpeg" border="0"></a> <a href="https://fastpic.org/view/115/2021/0911/efeccde1db179283a004d2a52417bbed.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0911/ed/efeccde1db179283a004d2a52417bbed.jpeg" border="0"></a>

Так же если выбрать - Настройки/Блокировка контента/Фильтры/Другие и выбрать DNS фильтр

<a href="https://fastpic.org/view/115/2021/0911/10301695480355a70b631b51d0f8a806.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0911/06/10301695480355a70b631b51d0f8a806.jpeg" border="0"></a>

и

Настройки/Фильтрация DNS и выбрать DNS-фильтр AdGuard

<a href="https://fastpic.org/view/115/2021/0911/246d98bafb41071af8de2ad5c97f9891.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0911/91/246d98bafb41071af8de2ad5c97f9891.jpeg" border="0"></a>

На один и тот же фильтр идет разная информация.

PS: Почему у одного и того же фильтра стоит разное время обновления баз?

PSS: В чем смысл добавлять один и тот же фильтр в разные разделы? Ведь у Вас есть специальный раздел для этого - Фильтрация DNS

**Comment by Birbber** [comment]
@GdeZsqyAY Приветствую!
- Этот фильтр был добавлен в оба раздела, так как полезен для каждого из них.
- Время обновления может отличаться, если один фильтр был активирован позже другого.
- Информация о фильтре немного разнится, потому что они находятся в разных разделах: для DNS фильтрации важно отметить количество правил и время обновления, а для Блокировки контента даётся более обширное описание.
