### ISSUE TITLE
Please support Anonymized DNS in Adguard

### ISSUE THREAD

**Issue by nkoc6a15** [AdguardTeam/AdguardForAndroid#3970]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

**Comment by Chinaski1** [comment]
I have moved the task you created earlier to the correct section.
Please do not reopen it in the AdGuard for Android repository.

https://github.com/AdguardTeam/DnsLibs/issues/120
