### ISSUE TITLE
Look like Adguard Android doesnt support HTTP3

### ISSUE THREAD

**Issue by nkoc6a15** [AdguardTeam/AdguardForAndroid#3973]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Problem Description

I have try disable Adguard DNS section in Adguard and use DoT in Android and see HTTP3 is back (Test with https://cloudflare-quic.com/) but when i enable Adguard DNS section again, HTTP3 gone. Can you guy support http3? Maybe in v4?

**Comment by Birbber** [comment]
We've closed this issue, since it's a duplicate of [#121](https://github.com/AdguardTeam/DnsLibs/issues/121).
