### ISSUE TITLE
APKPure

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#3974]
Сегодня заметил в приложении APKPure следующее

<a href="https://fastpic.org/view/115/2021/0920/35fb15ace10901d98cff423d479c8ed3.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0920/d3/35fb15ace10901d98cff423d479c8ed3.jpeg" border="0"></a>

Хотя установлено

<a href="https://fastpic.org/view/115/2021/0920/0f89f47f403ce2d83caecc62131c2143.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0920/43/0f89f47f403ce2d83caecc62131c2143.jpeg" border="0"></a>

Приложение APKPure установлено на двух телефонах и на обоих одинаковая ситуация.

Первый телефон - Android 10
Второй телефон - Android 9

Либо приложение APKPure некорректно выдает информацию, либо AdGuard мешает корректному определению установленной версии.

**Comment by Birbber** [comment]
@GdeZsqyAY Приветствую!
3.6.32 - это техническая версия. 3.6.4 - это публичная версия приложения, которая указана в самом приложении AdGuard.
