### ISSUE TITLE
com.rapido.passenger app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3976]
@adguard-bot commented on [Sat Sep 11 2021](https://github.com/AdguardTeam/AdguardFilters/issues/94365)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.rapido.passenger](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.rapido.passenger)
### Comment
Username: `@debmaj2`
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/G0QZ8XZ.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/FJKqFp1.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.3 (31)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing third-party cookies (0)
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>NoCoin Filter List, <br/>Spam404, <br/>Online Malicious URL Blocklist
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by Alex-302** [comment]
On my device it does not work even if all filters disabled, DNS - 1.1.1.1, ad blocking is disabled for this app.

**Comment by Chinaski1** [comment]
Checked by disabling all protection modules. 
The issue is still reproducing.
I have attached the logs to the task.
