### ISSUE TITLE
How to block the exchange of information between Mail.ru and Facebook

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#3978]
Hello there,

I've got brand new Lenovo tablet running Android 10 with the latest free version of Adguard. It also has the native Mail.Ru email client and Lite versions of Facebook app and its Messenger.

I've noticed from logs (see attached) that Mail.ru email client frequently sends some information to IP address that belongs to Facebook. So I am kinda curious what this may be all about, why this is happening and how to prevent the exchange of information without breaking the Facebook services completely on my tablet?

Thanks in advance.

Operating system: Android 10
AdGuard version: Always the latest
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter

![IMG_20210828_120857](https://user-images.githubusercontent.com/23212486/134442052-c431ec5d-d277-4621-9a06-8695573f77e0.jpg)

**Comment by Chinaski1** [comment]
Hello!

Actually, there are several methods you can try to use.

- Open Apps management -> find the desired applications -> deny them access to the network
- Use the` $network` rule to block network requests (192.168.10.10^$network)
But I still think they are using dynamic IP addresses, so it's not possible to block these requests completely.

**Comment by jbionic2016** [comment]
Hi there,

Thanks for your prompt response.

I would appreciate if Adguard team could come up with an appropriate wide-scale rule to completely block the exchange between 2 popular apps, instead of hiding the records from app's log. Otherwise this may arouse some suspicions that Adguard is actually participating in this game without doing anything to prevent the tracking and exchange of information between the platforms 🙂

**Comment by Chinaski1** [comment]
It doesn't really make much sense to create specific rules. Since we certainly don't know what the above queries contain.

If you want, you can block them using the tools in the filter log.

But the assumption that we are hiding any requests is wrong.

**Comment by jbionic2016** [comment]
Hi,

Why are you closing the issue, Konstantine? Do you recognize that there is no problem in allowing such data flow between the 2 apps to take place?

**Comment by Chinaski1** [comment]
We have no way of knowing what kind of traffic is being sent by applications.
Whether it is useful or whether it is advertising or trackers. 
That's why it's blocked.

**Comment by jbionic2016** [comment]
> We have no way of knowing what kind of traffic is being sent by applications.
> Whether it is useful or whether it is advertising or trackers.
> That's why it's blocked.

Lets approach the issue logically. What sort of use and for who could be incurred from unauthorized exchange of information between mail client and Facebook? 

I see from the log there is still no rule to block this sort of exchange between 2 apps.
