### ISSUE TITLE
Adguard supposedly causing issues with Play Market

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#398]
Здравствуйте! Опять начались проблемы с загрузкой приложений с плеймаркета. Ошибка 963, 907. На устройстве без adguard то же приложение скачивается без проблем. Для примера игра Мастера карт (Master of cards). Чистить кэш и данные плеймаркета и сервисов гугля пробовал. Перезагружать, выключить включить смартфон тоже пробовал. Samsung Galaxy E5 Android 5.1.1 Версия прошивки E500FXXU1BOI3 (официалная).

Да при отключении всех фильтров проблема остается.
То, что написано в статье проделал- бесполезно.
Проблему решил временно так- скачал на другом устройстве, сделал бэкап,
скопировал и установил в ручную без проблем.
Похоже надо ждать обновлений Плеймаркета...

logs: ANP-742-73647

**Comment by ameshkov** [comment]
Имеет смысл бета-версию протестировать

**Comment by ameshkov** [comment]
Еще можно менеджер загрузок в pref.net.exclusions добавить
