### ISSUE TITLE
Broken app ru.mobile.jivika

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3981]
@adguard-bot commented on [Tue Sep 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/95404)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=ru.mobile.jivika&hl=ru&gl=US](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dru.mobile.jivika%26hl%3Dru%26gl%3DUS)
### Comment
Username: `@Tim0fei`
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/bOyhoFB.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/seczfys.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.6.4 (32)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by Alex-302** [comment]
@zzebrum Please take a look.

**Comment by Chinaski1** [comment]
Indeed the issue is reproduced even if all protection modules are disabled

**Comment by grigorevmp** [comment]
Adguard app works fine in this case. The application "ru.mobile.jivika" breaks the first connection, and the second one is already going fine. You need to wait for the application to establish a connection
