### ISSUE TITLE
На ряде сайтов отвалилась фильтрация.

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3988]
На ряде сайтов (тот же рутрекер или пикабу) к чёрту отвалилась фильтрация (в статусе сайта фигурирует НЕ adguard'овский сертификат, а родной, сайта). На остальных всё пучком (тот же 4pda). Это случаем не связано с этим => https://habr.com/ru/post/580092/ ? Если связано, то как в случае adguard'а решать проблему ? Перегенерить сертификат ? AdGuard 3.6.4, Chrome 71.0.3578.99, ведро 5.1, режим ручного прокси, качественная фильтрация, сертификат в систему впилен. Вчера всё везде было пучком.

**Comment by Kusurisan** [comment]
У меня такая же проблема с моим телефоном Android с сегодняшнего дня. это началось без меня. я не менял никаких настроек.

https://github.com/AdguardTeam/AdguardForAndroid/issues/3987

(перевел этот текст с помощью Google Translate)

**Comment by sfionov** [comment]
Чтобы не ждать следующего релиза, вы можете починить это, установив https://letsencrypt.org/certs/isrgrootx1.der (нужно переименовать в .cer) в хралилище сертификатов.

**Comment by Baltazar500** [comment]
> Чтобы не ждать следующего релиза, вы можете починить это, установив https://letsencrypt.org/certs/isrgrootx1.der (в случае проблем можно переименовать в .cer) в хралилище сертификатов.

Спасибо, помогло. Впилил сразу в систему - воткнул в /system/etc/security/cacerts/, его subject_hash_old => 6187b673, т.е. имя сертификата - 6187b673.0

Зашуршало всё после перещапуска AdGuard'a

**Comment by sfionov** [comment]
Установка в юзерский стор через UI тоже помогает

**Comment by Baltazar500** [comment]
Закрывать или нет issue ? Для меня в принципе вопрос решён, но технически проблема ещё остаётся.

**Comment by Chinaski1** [comment]
Закрою как дубликат, задача будет решена в рамках https://github.com/AdguardTeam/CoreLibs/issues/1525.

**Comment by Spok1** [comment]
> Чтобы не ждать следующего релиза, вы можете починить это, установив https://letsencrypt.org/certs/isrgrootx1.der (в случае проблем можно переименовать в .cer) в хралилище сертификатов.

А чем данные сертификаты отличается от этих [ISRG Root X1: [Self-signed](https://letsencrypt.org/certs/isrgrootx1.der) и [ISRG Root OCSP X1 ](https://letsencrypt.org/certs/isrg-root-ocsp-x1.der)?

**Comment by Spok1** [comment]
@sfionov, я делал сброс сегодня и без этого сертификата блокируется реклама прекрасно! Имеет ли смысл его устанавливать или сертификат в приложении заменяет этот?

**Comment by sfionov** [comment]
В новых версиях AdGuard, выпущенных с октября 2021 года, сертификат этот уже имеется.

Сейчас сертификат имеет смысл устанавливать, только если отсутствие такового в системе ломает какие-то приложения, и вы хотите переместить его в систему.

**Comment by Spok1** [comment]
> Сейчас сертификат имеет смысл устанавливать, только если отсутствие такового в системе ломает какие-то приложения

Можно поподробней насчет этого?

**Comment by Baltazar500** [comment]
@Spok1, они просто могут обломаться при https - запросах вываливая в syslog, а то и в виде попапа ругань на невозможность достучаться туда-то и туда-то из-за ошибок ssl/tls.

**Comment by Spok1** [comment]
@Baltazar500, у тебя было такое? Хорошо, учту это, если появится подобного рода оповещение!

**Comment by Baltazar500** [comment]
> @Baltazar500, у тебя было такое? Хорошо, учту это, если появится подобного рода оповещение!

Пара приложений тупо в отказ ушли и не могли к сети подцепиться. Уведомлений не было, но они ругались в syslog (видно было по logcat). Втыкание сертификата проблему решило. Позднее разработчики выпустили фиксенные релизы. 

Втыкание сертификата не доставляет особых проблем, так что я его на всякий случай воткнул где только возможно во избежание предотвращения возможных проблем.

**Comment by Spok1** [comment]
Ясно,буду знать в случае чего с чем связано!

**Comment by Spok1** [comment]
@Baltazar500 ,недавно появилась проблема с сертификатом на некоторых страницах. Связано ли это с просрочкой корневого сертификата **ISRG Root X1** у меня, или же действительно проблемы с сертификатом на сервере?
![Screenshot_20230628-063851](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/273259eb-1ae1-47a0-be52-8a0a00f3c5cd)

![Screenshot_20230628-040845](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/b8299b00-3be8-4eca-a68b-0a84f3bc504e)
Вот один [сайт](https://itorrents-igruha.org/4534-diablo.html), а вот [другой](https://cxid.info/amp_171245_kosnetsya-vsex-vladelcev-bankovskix-kart-privatbanka-v-iyune.html).

**Comment by Baltazar500** [comment]
@Spok1,  ISRG Root X1 - это LetsEncrypt, у этих "Google Trust Services LLC; GTS CA 2P2", возможно он у вас и протух. Я не так давно обновил корневые сертификаты [отсюда](https://android.googlesource.com/platform/system/ca-certificates/+archive/master/files.tar.gz) и с сайтами с таким сертификатом у меня проблем нет. Тем не менее с этим сайтами есть пара нюансов. По первому линку - блокировка РКН/провайдера, по второму сидит cloudflare, причём на корне сайта этого не наблюдается. Что из всего этого ломает вам фильтрацию - ХЗ. Проверяйте.

**Comment by Spok1** [comment]
@sfionov, неделю назад отвалилась проверка обновлений фильтров приложения с сервера,на котором используется ssl от Let's Encrypt, как потом выяснилось, из-за протухшего **DST Root CA X3** в системе андроид 7. Потом вспомнил,что на крайний случай вы мне рекомендовали установить новый кроссовый ssl **ISRG Root X1** в центр сертификатов. Он-то и исправил ситуацию. Такой вопрос, более никаких ssl не нужно устанавливать? Типа ISRG Root X2!?

**Comment by Spok1** [comment]
@Baltazar500, у вас проблемы возникают с обновлением фильтров в версии 4.5.x? У меня не проходят обновления. Установлен  кроссовый сертификат ISRG Root X1.

**Comment by Baltazar500** [comment]
@Spok1, у меня как висел 3.6.x (3.6.11/54), так до сих пор и висит. Смарт всё тот же :D С ним проблем нет. Проверяйте источники фильтров на предмет блокировки или смотрите, как реагирует на них дефолтный браузер. Мб какой из базовый сертификатгв протух и надо весь пак сертификатов апдейтить.

**Comment by Spok1** [comment]
@Baltazar500, без сертификата обновления также не проходят на старой версии,однако на долго ли это. Срок доверия ISRG Root X1 до сентября 2024,вроде. Дальше будет видно.

**Comment by Baltazar500** [comment]
>Срок доверия ISRG Root X1 до сентября 2024,вроде.

@Spok1, если вкоряченные в саму апк-ку сертификаты протухнут и она не сможет обновлять фильтры, для меня это не будет особой пррблемой. Просто буду обновлять базы скриптом и им же вносить фиксы в sqlite.db, с помледующим перезапуском adguard, как это происходит сейчас на ещё более древнем смарте с android 4.2.2 и adguard 2.12.250

**Comment by Spok1** [comment]
@Baltazar500, 

> Просто буду обновлять базы скриптом и им же вносить фиксы в sqlite БД, с последующим перезапуском adguard

Для этого рут-права нужны?

**Comment by Baltazar500** [comment]
@Spok1, 
>Для этого рут-права нужны?

Естественно.

**Comment by Spok1** [comment]
@sfionov, можете предоставить решение  для обновления фильтров на версии 4.6 и старше для андроид 7. Прошу, радикальных мер по обновлению устройства не предлагать, ибо возможности нет, также перепрошить возможности нет, ибо рутированию устройство не полежит прошивки для него кроме офф нет. Какие нужно сертификаты установить?

**Comment by Spok1** [comment]
@sfionov, можете предоставить решение  для обновления фильтров на версии 4.6 и старше для андроид 7. Прошу, радикальных мер по обновлению устройства не предлагать, ибо возможности нет. Также перепрошить возможности нет, ибо рутированию устройство не полежит — прошивки для него кроме офф не существует.  Какие ещё можно сертификаты установить можно?

**Comment by Spok1** [comment]
@sfionov, можете предоставить решение  для обновления фильтров на версии 4.6 и старше для андроид 7. Прошу, радикальных мер по обновлению устройства не предлагать, ибо возможности нет. Также перепрошить возможности нет, ибо рутированию устройство не полежит — прошивки для него кроме офф не существует.  Какие ещё сертификаты установить можно?

**Comment by Baltazar500** [comment]
@Spok1, 

>можете предоставить решение для обновления фильтров на версии 4.6 и старше для андроид 7.

сомневаюсь, что вам в этом плане помогут. Тут спасение утопающих - дело рук самих утопающих.

>Также перепрошить возможности нет, ибо рутированию устройство не полежит — прошивки для него кроме офф не существует.

Плохо. Пространство для манёвра сужается.

>Какие ещё сертификаты установить можно?

Для начала надо выяснить, по какой линии у вас с получением данных затык, а потом маяться с сертификатами. По линии приложения или ОС. Если первое - то тут только владелец сможет выправить ситуацию. В теории могут помочь мододелы с 4pda. Если второе - без рута возможно ситуацию и не удастся решить т.к. возможно понадобится воткнуть сертификат как "системный".

На вскидку пока вижу 2 более-менее простых варианта: 

Первый: зашивание свежих базовых фильтров в apk'у с заменой исходных,  переподпись и переустановка приложения

Второй: разборка приложения до smali, подмена хостов обновлений в исходниках на свои (ещё помаяться с поиском конкретных smali придётся), локальные; пересборка, подписание и переустановка приложения с подъёмом локального http-сервера с подписками.
