### ISSUE TITLE
AGH probs and the relation to the expired LE Root Cert starting from 09/30

### ISSUE THREAD

**Issue by ralfi** [AdguardTeam/AdguardForAndroid#3989]
My config: AGH on docker with my own hetzner-based virtual server, a few weeks on latest, now on edge image. 

Works like a charme until 09/30 as central blocker/tracking protection for three android 10+ devices as private DNS-over-TLS server and for some firefox browsers on different devies as DNS-over-HTTPS server. Starting from 09/30 all android devices tells me that network - of course means internet - access is inaccessable. Switching "private DNS" to OFF on the effected android devices resolve the prob. DoH for the firefox browser works, see this in the AGH logs. It seems to me the error is related to the DoT config.

Based on the excellent work of my son for investigating the TLS chain i am able to solve the problem by removing the last SSL key (ONLY THE LAST) entry in the fullchain.pem. After restarting AGH on docker everything works as expected. I dont know if this is the solution for similar AGH configs (or another like a new LE CERT or anything) and if you adopt these PLEASE BE CAREFULL. But for AGH for me works again...

**Comment by ameshkov** [comment]
Yeah, this is a known issue caused by Let's Encrypt root cert expiration:
https://github.com/AdguardTeam/AdGuardHome/issues/3689
