### ISSUE TITLE
Sites to be added to HTTPs whitelist

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#399]
> Could not find any suitable forum topic where whitelist additions are 
> discussed so I'm sending you the ones I immediately added to my own 
> whitelist after installing the new Adguard for Android beta.

// Swedish Banks and other financial organizations
icabanken.se
sbab.se
santanderconsumer.se
forex.se
avanza.se
handelsbanken.se
swedbank.se
lansforsakringar.se
// Swedish state agencies, other services with sensitive personal 
information
skatteverket.se
kronofogden.se
bolagsverket.se

IKE-294-35216

**Comment by ameshkov** [comment]
Added to the lists here:
https://github.com/AdguardTeam/AdguardForWindows/issues/911
