### ISSUE TITLE
adguard app无法过滤华为视频广告

### ISSUE THREAD

**Issue by biange200** [AdguardTeam/AdguardForAndroid#3990]
![Screenshot_20211004_214835.jpg](https://user-images.githubusercontent.com/37582806/135874955-d58f46f4-6ae2-468b-bfc0-774e853171a5.jpg)

在用户过滤器里添加了
||cs02-pps-drcn.dbankcdn.com^
||sys.zhangyue.com^
可以过滤广告了 ![Screenshot_20211004_225309.jpg](https://user-images.githubusercontent.com/37582806/135875213-c2528765-74b3-4507-8d23-e3f82ca1e179.jpg)

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #96454](https://github.com/AdguardTeam/AdguardFilters/issues/96454) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Birbber** [comment]
Moved this issue to [Adguard Filters repository](https://github.com/AdguardTeam/AdguardFilters/issues/96454).
