### ISSUE TITLE
Add shortcuts to access the settings

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#3991]
Частенько приходится писать правила на самом ведре и в процессе приходится перескакивать с браузера на adguard, который зачастую может прыгать в основное меню, из-за чего приходится проходить квест а - ля "доберись до своих правил блокировки через дебри настроек". Попробовал я это дело решить через shell, выведя скрипто-кнопку на десктоп

> am start -n 'com.adguard.android/com.adguard.android.ui.UserFilterActivity'

но adguard'у от такой команды дурнеет и он хлопается. При этом, вполне успешно стартует

>am start -n 'com.adguard.android/com.adguard.android.ui.MainActivity'

или открывает настройки

>am start -n 'com.adguard.android/com.adguard.android.ui.SettingsActivity'

ЧЯДНТ ? Какие есть варианты быстрого доступа к саоим правилам блокировки рекламы ?

**Comment by Baltazar500** [comment]
>У приложения нет шорткатов для перехода в настройки, однако мы подумаем над этим при разработке 4.0 версии.

Было бы неплохо. Особенно, если будет возможность сразу попасть в раздел редаетирования правил блокировки рекламы. А "окольными" путями туда никак не попасть ? В настройки то я например через am захожу, а вот с "Блокировка контента -> Пользовательские правила" - облом. Мб я что не так делаю ? Или внешние вызовы таких глубоких настроек в программе в принципе не предусмотрены и поэтому она хлопается при использовании am ?

**Comment by artemiv4nov** [comment]
Задача перемещается в 3296
