### ISSUE TITLE
Add Android Auto to excluded apps by default

### ISSUE THREAD

**Issue by the4anoni** [AdguardTeam/AdguardForAndroid#3996]
#3986 # Issue Details

Please exclude Android Auto from AdGuard filtering by default. In current default configuration AdGuard breaks wireless Android Auto. Adding exception fixes problem.

- **AdGuard version:**
  - v. 4.0 nightly 24
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Galaxy S9 and S10
- **Operating system and version:**
  - Android 10 and 11
- **Root access:**
  - No

### Expected Behavior

Android Auto just works.

### Actual Behavior

It doesn't work out of the box.

**Comment by Chinaski1** [comment]
Closing this task as a duplicate.

You can follow the solution in  https://github.com/AdguardTeam/AdguardForAndroid/issues/3909
