### ISSUE TITLE
Samsung "Smart Anti-tracking" detects AG as a tracker

### ISSUE THREAD

**Issue by gimenes2008** [AdguardTeam/AdguardForAndroid#3997]
Hi!

This is not a report of a bug, but something that caught my attention in the Samsung browser. Well, in this browser there is a feature called 'Smart Anti-tracking', in 'Privacy and Security', and that curiously detects the AG as a tracker. Of course this isn't true, but then what can it be? Can this somehow affect AG filtering?

![Samsung Internet 1](https://user-images.githubusercontent.com/84917267/137603764-fc470fa5-4b16-4fe2-9230-2ced8c77d48f.png)

![Samsung Internet 2](https://user-images.githubusercontent.com/84917267/137603772-e10d7bdc-c5c9-4027-aa5d-943157030c6b.png)

**Comment by Chinaski1** [comment]
We sent a request to the developers of the Samsung Browser. 
But unfortunately, there has been no response so far. You can follow the decision by clicking on [this link](https://forum.developer.samsung.com/t/false-positive/16997).

**Comment by gimenes2008** [comment]
Ok! Perfect.

Em seg., 8 de nov. de 2021 6:16 AM, Konstantin ***@***.***>
escreveu:
