### ISSUE TITLE
Unreadable text in app menu on Android 4.X

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4]
![6687783](https://cloud.githubusercontent.com/assets/5947035/9439571/ef01f5fe-4a70-11e5-8a69-f8fa8c32dc0b.png)

![screenshot_2015-08-19-20-24-43](https://cloud.githubusercontent.com/assets/5947035/9439579/f329001e-4a70-11e5-83ca-7df66d4c7882.png)

**Comment by TPS** [comment]
I'm not seeing this in Latin letters.…  Only Cyrillic?

**Comment by Revertron** [comment]
It depends on Adnroid version. We are using compatibility library for Material Design on devices with Android < 5.0, and there is a bug somewhere...

**Comment by Revertron** [comment]
Fixed both problems.
