### ISSUE TITLE
Broken app: pyaterochka.app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4001]
@adguard-bot commented on [Sat Oct 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/96847)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=pyaterochka.app](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dpyaterochka.app)
### Comment
Username: @rakleed
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ImjFGuy.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/B7hAUuM.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.6.4 (32)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Hide your Referrer from third-parties (), <br>Hide your Referrer from third-parties, <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by rakleed** [comment]
@Chinaski1 @ameshkov please take a look.

**Comment by Birbber** [comment]
Нашей команде разработчиков потребуется некоторое время, чтобы дополнительно изучить эту проблему.

**Comment by rakleed** [comment]
@Birbber так откройте тогда issue, пожалуйста.

**Comment by Birbber** [comment]
@rakleed Для приложения pyaterochka было выпущено обновление. Похоже, что проблема была решена. Проверьте у себя, пожалуйста.

**Comment by rakleed** [comment]
Скорее они что-то изменили на стороне бэкенда, так как на iOS без
обновления приложения всё теперь работает корректно, как и на Android.

**Comment by rakleed** [comment]
@Birbber в Android приложении опять появилась эта проблема https://github.com/AdguardTeam/AdguardFilters/issues/103944#issue-1085686742, хотя в iOS всё нормально работает с включённом AdGuard.
