### ISSUE TITLE
api.samsungcloud.com blocked. Not in any filter. 

### ISSUE THREAD

**Issue by SyCoREAPER** [AdguardTeam/AdguardForAndroid#4004]
Latest Adguard Nightly
Android 11
Samsung S21 Ultra
Samsung Internet

In order to block ads properly, Samsung Internet must have HTTPs request box checked. HOWEVER, this breaks Samsung Internet Cloud Sync built into Samsung Internet. If I unchecked https for Samsung Internet in Adguard it works and if I turn it on, sync fails. 

I watched Adguard traffic and the sync specifically calls one address only: **api.samsungcloud.com**

I've tried adding it to the allow list and and also to the User rule as @@ || https://api.samsungcloud.com
Also tried @@ || api.samsungcloud.com ^ $ document

It still fails. I tried using Adguard ContentBlocker but that puts me at square one with Https requests not being fired correctly. 

Why is this whitefish filter not working?

**Comment by kongacute** [comment]
> @SyCoREAPER Tried doing so, but had no issue: it successfully updated the time. Could you send us the debug logs?
> 
> Here's what we need you to do:
> 
> 1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> 2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> 3. Send it to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

Could you check that with Samsung Internet Beta? I have same problem with beta which use sync independently from Samsung Cloud in Devices. The Samsung Internet stable use Samsung Cloud and it is has no issue with this.

**Comment by Birbber** [comment]
@kongacute Thanks, I was able to reproduce the issue on beta. Will pass it to our developer team.

**Comment by SyCoREAPER** [comment]
Sorry notifications were off for some reason. 

@kongacute You nailed it. Complete oversight on my part, I have the beta and That's been the issue for the past few months but didn't write that. **Sorry mods and admins**.

That's really odd and has peaked my interest. I wondered what's different in the beta from stable in regards to sync. They are nearly identical, beta is more like an RC than a beta. 

Well thank you for chiming in in my behalf I turned notifications back on. 

@Birbber Sorry Birbber for not responding. As above I don't know why notifications are off. It's fixed. If you need anything further please tag me and I'll follow up.

**Comment by Birbber** [comment]
@SyCoREAPER @kongacute The issue is reproducible on beta only. We recommend contacting Samsung support for further investigation, since the issue is not on AdGuard's side.

**Comment by SyCoREAPER** [comment]
@Birbber How is this on Samsung? Something in Adguard is blocking the sync. I even identified what's being blocked but don't know what's causing it. It's not filters, it's the application. I posted exactly what needs to be done in Adguard to fix it. So it is 100% Adguard. Adguard off, works fine. Adguard on, stops working. Adguard on with my fix, works fine. I'm understanding how you aren't seeing 1+1=2

And while this is a beta of the app I don't see why that matters. It's still a standalone app. 

Not to mention, as we all know, beta eventually becomes stable. So why would you want to push this off just because it's beta now and wait for Stable to have the same issue, which it eventually will.

**Comment by Birbber** [comment]
@SyCoREAPER If the issue is reproducible on beta only, Samsung team should figure it out themselves.

**Comment by SyCoREAPER** [comment]
No disrespectful but what is the adguad team not getting here? **It's your app that is breaking the sync.** Something in YOUR app is blocking the connection. Not the filters, not any rules, or white/blacklists. It shouldn't matter if it's a beta or not. It's a standalone app, an app that many use.  

I literally told you how to fix if.  
 _I'm asking that you add api.samsungcloud.com to the https whitelist by default_.

I don't understand your refusal to add this to the default whitelist. You've added dozens (hundreds?) of other addresses to that white list, why won't you add this one?

**Comment by SyCoREAPER** [comment]
^ @Chinaski1 
Can you please comment on why this is being considered a closed matter? I would like a second opinion.

**Comment by Birbber** [comment]
@SyCoREAPER We're releasing new nightly version this week. It will contain Corelibs updates that might solve the issue. Please try testing the behavior on that version.
