### ISSUE TITLE
Forwarding vpn traffic to downstream proxy will cause the connection to be interrupted

### ISSUE THREAD

**Issue by xxxsen** [AdguardTeam/AdguardForAndroid#4005]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Adguard config with socks proxy will cause frequent connection drops, especially in game app.

- **AdGuard version:**
  - 3.6.4(32)
- **Filtering mode:**
  - local vpn with a socks proxy as outbound
- **Device:**
  - OnePlus 7p
- **Operating system and version:**
  - android 11(lineage 18.1)
- **Root access:**
  - no

### Expected Behavior

connections won't be droped unexpectedly

### Actual Behavior

connections drop frequently

### Additional Information

this problem can be reproduced even after removing all filter rules. only represent when use a socks proxy. and it was not cause by socks proxy server(I test it with more than one proxy)

#### step to reproduce
1. install connectbot (android ssh tool)
2. setup adguard with socks proxy outbound
3. enable Adguard protection on connectbot(enable ad blocking only and don't enable https filter)
4. open connectbot and connect to you ssh server
5. when the password input box pops up, do not enter the password immediately but enter it slowly. After a few seconds, the connection will be disconnected

**Comment by kdurov** [comment]
still not fixed in ver. 3.67 Premium. 
any update?

Oddly enough, changing Adguard DNS from upstream SOCKS5 DNS to public DNS solved this issue temporarily.

**Comment by Chinaski1** [comment]
A tentative solution is scheduled for version 4.0.

Stay tuned :)

**Comment by kdurov** [comment]
and when is that happening?
It's a critical bug. An urgent fix is required :(
