### ISSUE TITLE
Error message in "com.minsvyaz.gosuslugi.stopcorona" while using vpn

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4007]
@adguard-bot commented on [Mon Oct 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98046)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.minsvyaz.gosuslugi.stopcorona](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.minsvyaz.gosuslugi.stopcorona)
### Comment
Username: @rakleed
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/LOzlNU8.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/U14vXPw.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.6.4 (32)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Hide your Referrer from third-parties (), <br>Hide your Referrer from third-parties, <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@Alex-302 commented on [Mon Oct 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98046#issuecomment-950808197)

У меня не устанавливается.
@zloyden @jellizaveta Проверьте у себя.

@rakleed Без фильтров и стелсмода то же самое? Если "да" - нужны логи и скопируй плз ишью сюда https://github.com/AdguardTeam/AdguardForAndroid/issues

---

@zloyden commented on [Mon Oct 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98046#issuecomment-950850213)

Не повторяется, спокойно зашел под своим аккаунтом.

---

@rakleed commented on [Mon Oct 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98046#issuecomment-950855245)

@zloyden В аккаунт можной войти, но всегда висит это красное предупреждение. И затем, если попытаться разблокировать приложение не с помощью отпечатка пальца, а с помощью пинкода, то будет отображаться белое окно вместо кнопок для ввода кода.

@Alex-302 попробую позже протестировать разные варианты.

---

@rakleed commented on [Tue Oct 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98046#issuecomment-951895749)

> @rakleed Без фильтров и стелсмода то же самое? Если "да" - нужны логи и скопируй плз ишью сюда [https://github.com/AdguardTeam/AdguardForAndroid/issues](https://github.com/AdguardTeam/AdguardForAndroid/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

@Alex-302 отключение фильтров и стелсмода не помогает. Можно решить проблему, только полностью отключив пропуск трафика через AdGuard для этого приложения. Также отправил в поддержку AdGuard логи с номером 547467.

И можете ли вы сами перенести issue в репозиторий https://github.com/AdguardTeam/AdguardForAndroid? Так как мне это нужно будет вручную делать, а вы можете автоматически это сделать.

**Comment by dnovitskyi** [comment]
Logs received and available in ticket Z547467.

**Comment by Birbber** [comment]
It will take some time until our developers investigate the issue.

**Comment by Birbber** [comment]
@rakleed
Результаты проведенного анализа:
- Основное приложение "госуслуги" и приложение "госуслуги СТОП коронавирус" используют один и тот же API;
- Основное приложение работает на всех версиях андроида при авторизации одинаково;
- "госуслуги СТОП коронавирус" корректно работает на андроидах 10+ ;
- "госуслуги СТОП коронавирус" позволяет авторизоваться по биометрии;
- "госуслуги СТОП коронавирус" позволяет авторизоваться при первом входе в приложение (хотя и показывает снекбар о недоступности интернета);

Из этого следует, что:

- В приложении полно яндекс трекеров, поэтому добавлять его по-умолчанию в исключения не самая лучшая идея, тем более, что теоретически оно может работать корректно.
- Приложению не удается что-то пропинговать на адроидах ниже 10, и оно просто отключает форму логина, хотя функционал сам по себе доступен (основываясь на последних 3 утверждениях);
- Разработчики из "Минцифры России" в состоянии написать свое приложение так, чтобы наличие VPN туннеля не ломало их работу (основываясь на первых 2 утверждениях), поэтому мы постараемся завести им задачу и надеемся, что они поправят работу приложения.
