### ISSUE TITLE
Ad in Adguard

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4011]
Good time of day. I have repeatedly asked you to remove the annoying sign advertising "Adguard VPN", but you have repeatedly refused me. As I see it, you don't give a shit about the opinion of users. Well, I have to inform you that today I canceled absolutely all subscriptions to all your services (and tomorrow I will cancel them from relatives as well) and switched to using free software (such as Block This in the form of an application + ublock origin in the form of an extension). Goodbye.

**Comment by Chinaski1** [comment]
I'm sorry to hear that such a little thing in a hidden interest can lead to such a decision.
I hope in the future you will be more tolerant of small things that do not even relate to the functionality of the application.

Anyway, I hope you change your mind and come back to us ;)
