### ISSUE TITLE
The inscription about the subscription is not hidden, despite the mask added to the subscription!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4016]
### Issue URL (Social Widget)
 [https://ichip.ru/tekhnologii/est-li-smysl-defragmentirovat-ssd-712132](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fichip.ru%2Ftekhnologii%2Fest-li-smysl-defragmentirovat-ssd-712132)
### Screenshots
<details>
  <summary>Screenshot 1</summary>

 ![image](https://user-images.githubusercontent.com/34476664/139775908-4fcd5f3e-ea8b-48f5-b245-1808f42b887c.png)

</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.0
Device model:|Z500M
Root:|No
AdGuard product: | AdGuard for Android v3.6.2 (23)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | disabled

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardFilters #98758](https://github.com/AdguardTeam/AdguardFilters/issues/98758) via [**ZenHub**](https://www.zenhub.com/)
