### ISSUE TITLE
Не скрываются пустые блоки!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4019]
### Issue URL (Ads)
 [https://www.048.ua/amp/news/3216412/rabota-v-odesse-s-zarplatoj-ot-8-do-26-tysac-griven](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.048.ua%2Famp%2Fnews%2F3216412%2Frabota-v-odesse-s-zarplatoj-ot-8-do-26-tysac-griven)
### Comment
Username: @Spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/XmPXTOQ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.0
AdGuard product: | AdGuard for Android v3.6.2 (23)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | disabled

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/95975#issuecomment-929695192_

**Comment by Yuki2718** [comment]
I think this is a filter issue, see https://github.com/AdguardTeam/AdguardFilters/issues/95975#issuecomment-961235146

**Comment by Spok1** [comment]
@Yuki2718,the same situation is observed [here](https://www.5692.com.ua/amp/news/3248431/samye-dobrye-ludi-kto-oni-po-znaku-zodiaka)!
