### ISSUE TITLE
Empty ad placeholders are visible in some apps with HTTPS filtering enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#402]
In some apps listed in this thread: http://forum.adguard.com/showthread.php?9905

ads are blocked with HTTPs filtering DSIABLED, and are present with HTTPs filtering ENABLED.

**Comment by ameshkov** [comment]
The issue name is misleading.

**Comment by ameshkov** [comment]
http://forum.adguard.com/showthread.php?9905-HTTPS-filtering-not-working&p=81053&viewfull=1#post81053
> Also I think I know the reason.

> You see, when it is disabled, the app cannot connect to the blocked domain.
> But when it's enabled, AG emulates an empty server response instead.

> Generally, the second way is safer. For instance, an app won't try to reload ads.

> Also I suppose the issue can be solved on the filters level. Instead of empty response AG may emulate a server error, it may help.

**Comment by TPS** [comment]
I suppose make it another option under `Filter HTTPS connections`:white_check_mark:, but I think those of us with `Filter DNS requests`:white_check_mark: are _used_ to the previous behavior.

**Comment by ameshkov** [comment]
No, why, it should not be done app-wide, I am talking about filter rules modifiers.

I suppose the ad network was blocked by a rule with an $empty modifier. Removing this modifier will change the way it works and instead of empty response AG will return "server error" response.

**Comment by ameshkov** [comment]
I suppose this issue will be solved with a new beta version (coming soon).

**Comment by ameshkov** [comment]
Nah, the issue is still here:
http://forum.xda-developers.com/showpost.php?p=66606720&postcount=1126

**Comment by ameshkov** [comment]
One more relevant forum thread:
https://forum.adguard.com/index.php?threads/resolved-trivia-crack-blank-black-screens-have-started-showing-android.9628/

**Comment by ameshkov** [comment]
One more relevant issue: BBC Sports app
http://forum.xda-developers.com/s7-edge/help/incompatibility-adguard-t3370652/post66666923#post66666923

**Comment by ameshkov** [comment]
No placeholders when we return error response instead of 204 no content.

**Comment by ameshkov** [comment]
One more app to check:
https://play.google.com/store/apps/details?id=me.sync.callerid

**Comment by ameshkov** [comment]
Caller ID also seems to be clean when we return status=500

**Comment by ameshkov** [comment]
https://play.google.com/store/apps/details?id=com.livecharger

![Uploading photo_2016-05-23_12-12-31.jpg…]()

**Comment by Revertron** [comment]
I think we need to send different responses to different requests. :-/

**Comment by ameshkov** [comment]
False alarm, user has disabled ad blocking for "Google Services framework" so metadata just was not blocked at all.
