### ISSUE TITLE
wifi calling/vowifi problem while adguard on

### ISSUE THREAD

**Issue by Titanposeidon** [AdguardTeam/AdguardForAndroid#4021]
I am running the latest version
I checked the documentation and found no answer
I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0.65
- **Filtering mode:**
  - automatic proxy mode on ( with root )
- **Device:**
  - < xiaomi mi 8 lite
- **Operating system and version:**
  - android 10
- **Root access:**
  - yes

### Expected Behavior

i have chamged my mobile operator fm Vodafone to Turkcell
i was making wifi calls on Vodafone without problem on same settings but after changed to Turkcell, vowifi icon dont appear n wifi calling do not work, when i pause Adguard app, it apeears and able to calls

i checked online documents n seen that Turkcell wifi calling ipv4 already in advanced settings  but do not work for me
one more info; i am using nextdns as a DNS provider and using it with Cloudflare workers script so my DNS going through ipv6, i guess may it needs to be added ipv6 too on advanced settings idk

pls advice and guard me 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Chinaski1** [comment]
Hello there!

First, you can try to make a call and then go to the filter log. Will there be blocked requests of a similar type?

![image](https://user-images.githubusercontent.com/49645813/140711484-f691a288-8465-4395-b02d-3ec1593d1061.png)

If there are similar entries, try adding these addresses to the `pref.dns.fallback.domains` in advanced settings of AdGuard.

**Comment by Titanposeidon** [comment]
i already tried it but there is not any entries on filtered logs
as i mentioned already my dns provider uses ipv6 so blocking should be by ipv6 log, on the other hand as i cant see ipv6 logs in adguard filtering log, there is no record 

i checked previous issues under "wifi call" #1679 issue same as mine

when the adguard app on vpn mode i am able to use wifi calling but ones i changed to root mode as automatic proxy mode ''vowifi icon"  lost, so as mentioned on #1679 i think i need to add my tel operator Turkcell' s  wifi calling ipv6 to excluded list  , but idont know its details 

just i saw ipv4 addreses same as below on adguard excluded list: 
Turkcell Wi-Fi calling
188.59.223.0/24
188.59.227.0/24
188.59.228.0/24

also i have another phone with same ipv6 provider settings and same operator Turkcell,  adguard using Vpn mode, wifi calling works proper

end of point all ways going through ipv6 and automatic proxy mode

**Comment by Titanposeidon** [comment]
well after making an online search for ipv6 range of Turkcell, i have found 2 addresses and after added below ones to ipv6 excluded list i have connection to vowifi/wifi calling
here the list if somebody faces with same issue :

2a02:4e0:10::/48
2a02:4e0:2::/48
2a02:4e0:10::/24
2a02:4e0:10::/28
2a02:4e0:10::/29
2a02:4e0:2::/24
2a02:4e0:2::/28
2a02:4e0:2::/29
