### ISSUE TITLE
a sign for `ipaddr`

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardForAndroid#4022]
![Screenshot](https://user-images.githubusercontent.com/75058881/140638313-fa7307f1-8358-4533-a101-009b83b15d77.png)

This is becoming more and more common, so I propose to add a new symbol for ip to allow users to block traffic connected directly by ip.

ByteDance (Tiktok) SDK, Alibaba (Taobao) SDK, Xiaomi Push SDK......

**Comment by c2xusnpq6** [comment]
`||IPADDR^$app=com.mi.global.shop` ?

**Comment by sfionov** [comment]
There is already [$network rules](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier) for that
