### ISSUE TITLE
Кликандер на странице!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4025]
Кликандер`https://ut.infoboom.life/ranging/10f446dc96/click/` на странице https://github.com/AdguardTeam/AdguardFilters/issues/98392 из данного топика! Проблема в том,что у работников подписок он никак не проявляется,а у меня он давно проявляется!

**Comment by Chinaski1** [comment]
Не совсем понятно, в чем состоит ваша проблема.
Вы не могли бы сформировать ваш запрос более корректно?

**Comment by Spok1** [comment]
Я не знаю,что не может быть неясного в том,что кликандер появляется при просмотре видео на странице! Мне писать некуда больше. В теме с подписками мне не помогли! Может разработчик поможет выявить от чего он и как заблокировать!

**Comment by Chinaski1** [comment]
Указанная вами проблема не имеет отношения к репозиторию AdGuard for Android и должна решаться в рамках https://github.com/AdguardTeam/AdguardFilters/issues
