### ISSUE TITLE
banner ad on Bundle app

### ISSUE THREAD

**Issue by Titanposeidon** [AdguardTeam/AdguardForAndroid#4027]
On bundle app i see attached banner ad 
I am using Adguard nightly 4.0.65 on Android

![Screenshot_20211110-215750~2](https://user-images.githubusercontent.com/93843527/141189386-523fe664-2382-4138-a1a8-ed6b2377f75b.png)

**Comment by Birbber** [comment]
@Titanposeidon Hi! Could you give us the full package name of the application?

**Comment by Titanposeidon** [comment]
hello, here the marked area full package name , and other infos if there is any need
![IMG_20211111_115549](https://user-images.githubusercontent.com/93843527/141283685-c6ed043b-23e3-4d38-89d7-5da9b43f7f2d.jpg)

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #99635](https://github.com/AdguardTeam/AdguardFilters/issues/99635) via [**ZenHub**](https://www.zenhub.com/)
