### ISSUE TITLE
Не блокируются кнопки виджетов соц.сетей в приложении!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4028]
Блокируется нормально несколькими правилами, в частности этим `vgtimes.ru##.share`. Проверь у себя.

_Originally posted by @zloyden in https://github.com/AdguardTeam/AdguardFilters/issues/98548#issuecomment-966990123_

**Comment by Chinaski1** [comment]
Не воспроизводится, виджеты соц. сетей были успешно заблокированы.

**Comment by Spok1** [comment]
@Chinaski1, а у меня не скрываются! Что делать дальше?

**Comment by Chinaski1** [comment]
Давайте попробуем собрать лог, может быть он прольет свет на происходящее.

1. Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
2. Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Отправьте полученный архив по адресу `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by dnovitskyi** [comment]
Логи получены и доступны в тикете 553440.

**Comment by Spok1** [comment]
@Chinaski1, что-то от вас не было давно вестей! Как продвигается работа по устранению?

**Comment by Chinaski1** [comment]
Пока занимаемся задачами с более высоким приоритетом, вернемся к рассмотрению данного обращения позже.

**Comment by Spok1** [comment]
Ничего себе, 4 месяца прошло уже и 0 решения!
