### ISSUE TITLE
popup that opens after clicking notification sometimes shows no data received

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#4029]
### Issue Details

- **AdGuard version:**
  - 4.0 Nightly 24
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Samsung Galaxy S7 Edge
- **Operating system and version:**
  -  8.0
- **Root access:**
  -  no

### Expected Behavior

 After clicking the adguard notification the popup should always show the data received.

### Actual Behavior

 Sometimes it just shows "MB" for the data received (no number).

### Screenshots

 
<summary>Screenshot:</summary>

<a href='https://postimg.cc/bGN8RBFG' target='_blank'><img src='https://i.postimg.cc/yN0d7qmT/notification-Error.jpg' border='0' alt='notification-Error'/></a></details>

### Additional Information

 This has been happening for quite some time... Since at least 4 nightly versions ago and likely longer.

**Comment by Birbber** [comment]
@infinitewaveparticle Hi! Could you give us the detailed steps to open this popup?

**Comment by infinitewaveparticle** [comment]
Yes, you simply pull down the notifications from the top of the screen and click the one that says Android System, Connected to AdGuard VPN. If the popup is a system popup and not one designed by AdGuard, then that's my bad. I hadn't noticed it with other apps setup using a VPN connection.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Birbber** [comment]
@infinitewaveparticle It definitely looks like a system notification. We have a notification with statistics which opens the application once tapped on (the one that you can use to disable the protection or open the assistant).
