### ISSUE TITLE
Какой уровень поддержки юзер-скриптов в AdGuard и насколько он кореллирует с greasmonkey и tampermonkey ?

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#4031]
Сабж.

Какой уровень поддержки юзер-скриптов в AdGuard и насколько он кореллирует с greasmonkey и tampermonkey ? Понадобилось воткнуть юзер-скрипт, который блюрит на pikabu.ru посты под тегом "жесть" (нужна регистрация и авторизация), но не прокатило. Скрипт на сайте не работает. Хром 71.0.3578.99 Safari/537.36 с параметрами запуска с мимикрией под десктоп

>chrome --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Safari/537.36" --force-device-scale-factor=1.60

[Pikabu-HARG-bloor.user.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/7538213/Pikabu-HARG-bloor.user.txt)

При этом в 52-м фоксе с greasmonkey (даже не tamper) всё работает на ура. Неужели настолько всё плохо в AdGuard'е с userjs ? Или скрипт надо как-то корректировать под нюансы AdGuard'a ? Скрипт в аттаче, расширение изменено на txt, т.к. он иначе не аттачился.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1552](https://github.com/AdguardTeam/CoreLibs/issues/1552) via [**ZenHub**](https://www.zenhub.com/)
