### ISSUE TITLE
com.graymatrix.did - app is broken by network filtering

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4032]
@adguard-bot commented on [Sun Nov 14 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100100)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.graymatrix.did](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.graymatrix.did)
### Comment
Username: @iamthelara
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DZAGWRU.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/jROBrNd.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.6.4 (32)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `quic://dns-unfiltered.adguard.com`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>Fanboy's Enhanced Tracking List, <br/>EasyPrivacy, <br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>I don't care about cookies, <br/>Adblock Warning Removal List, <br/>EasyList Cookie List, <br/>Fanboy's Annoyances<br/><br/><b>Other:</b><br/>AdGuard DNS
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | no

**Comment by Alex-302** [comment]
To reproduce enable Indian VPN, launch an app and press `Upcomin` button.
Reproduced with disabled all filters and without DNS filtering.

**Comment by Alex-302** [comment]
@iamthelara

**Comment by admitrevskiy** [comment]
@iamthelara Hi!
Sorry for a long-lasting response. Is this issue still actual?

**Comment by iamthelara** [comment]
no, not now..
