### ISSUE TITLE
block IP address range

### ISSUE THREAD

**Issue by Pantyhose-X** [AdguardTeam/AdguardForAndroid#4038]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ .] I am running the latest version
- [ .] I checked the documentation and found no answer
- [ .] I checked to make sure that this issue has not already been filed

### Problem Description
- Block the IP address rang held by dangerous companies
- Create an Access Control List to Block Countries or Continents

### Proposed Solution
AdGuard Settings > Extensions 
address range Format
- Apache .htaccess Deny
- Apache .htaccess Allow
- CIDR
- Cisco ACL
- Cisco bit bucket
- Decimal/CIDR
- IP Range
- Inverse Netmask
- Juniper Junos
- Linux iptables
- MicroTik
- Netmask
- Network-Object
- Peerguardian2
- web.config Deny
- web.config allow
- Custom CIDR
- Custom Netmask

**Comment by Chinaski1** [comment]
Actually, you can block IP address ranges/Applications using the tools that have already been implemented. 

For example, to block IP addresses, you can use [DNS blocklists](https://kb.adguard.com/en/general/dns-filtering-syntax)
If you want to restrict network access to some applications - use the Firewall (Apps management tab).

**Comment by Pantyhose-X** [comment]
> Actually, you can block IP address ranges/Applications using the tools that have already been implemented.
> 
> For example, to block IP addresses, you can use [DNS blocklists](https://kb.adguard.com/en/general/dns-filtering-syntax) If you want to restrict network access to some applications - use the Firewall (Apps management tab).


Add ip range rules syntax `" "`  `*`
- `"0.0.0.0/24"` -block access to ip range   domains  `0.0.0.0/24`
- `"0.0.0.*"` -block access to  ip range Incremental domains  `0.0.0.*` 
-  `"0.0.0.0"` -block access to all domains whose CNAME response returns this IP address

**Comment by sfionov** [comment]
@Pantyhose-X You may try `$network` rules.

Here are some examples:
```
11.22.*$network
1.2.3.4:443$network
/1\.2\.3\.4:(80(80)?|443)/$network
```

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier

**Comment by artemiv4nov** [comment]
I think we can close the task cause of answer is found.
