### ISSUE TITLE
[Feature request] - manage apps permissions, secure file transfer, bandwidth saving mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#404]
1. when it comes to mobile security adguard app should provide option in android to manage application permissions and block apps/adware apps from collecting user data/information

2. give us option to securely transfer files from one device to another over wifi/bluetooth from one device to another having adguard intalled. we should also able to access files such as audio, video and play them.

3. Can you give us a internet bandwidth saving mode such that when we load a website only text loads and all the graphics, images, videos are not loaded. it will help us save internet data usage. give this feature in both desktop and mobile app

XRV-380-60578

**Comment by TPS** [comment]
No. 3 seems to be #108, & the other 2 points are probably out of scope for AG, right, @all?

**Comment by ameshkov** [comment]
> when it comes to mobile security adguard app should provide option in android to manage application permissions and block apps/adware apps from collecting user data/information

AG already prevents apps from sending data to known trackers.

> give us option to securely transfer files from one device to another over wifi/bluetooth from one device to another having adguard intalled. we should also able to access files such as audio, video and play them.

@TPS is right, this is out of scope.
