### ISSUE TITLE
adguard支持QQ浏览器去广告？

### ISSUE THREAD

**Issue by biange200** [AdguardTeam/AdguardForAndroid#4043]
问下adguard支持QQ浏览器去广告？![Screenshot_2021-11-29-23-01-04-35_a93965f46c4a4b0ed1be737bdf2bc8fc.jpg](https://user-images.githubusercontent.com/37582806/143987990-e9af81d7-177b-4f2f-8936-53ba777ca42b.jpg)
不支持开启QQ浏览器打开https过滤 手机没root

**Comment by Chinaski1** [comment]
QQ browser does not trust user certificates. Therefore, you cannot enable HTTPS filtering for it.
