### ISSUE TITLE
3.6.5 или 4

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#4044]
Как вижу у Вас в разработке версия 3.6.5, но на телефоне у меня уже версия 4.26. Так понимаю, что когда выйдет версия 3.6.5 мне придется удалить AdGuard с телефона и установить заново или же автоматический отскок на более старую версию произойдет автоматически?

**Comment by Chinaski1** [comment]
Вы пользуетесь Nightly версией. Откатиться с неё можно только путём полного удаления и повторной установки релиза.

Если это необходимо, можно предварительно сделать экспорт настроек и перенести их в релизную версию.
При желании, можно оставаться на Nightly версии.
