### ISSUE TITLE
Malware detected in this app

### ISSUE THREAD

**Issue by SaberAkiyama** [AdguardTeam/AdguardForAndroid#4045]
I've saw on VirusTotal and this app has a malware detected
![Screenshot (228)](https://user-images.githubusercontent.com/48464326/144152875-ae30de6f-a135-42b4-a00f-662d9ae5d0d6.png)

I don't think you should fix this app. Here is a link:
https://www.virustotal.com/gui/file/79b2b387f20cd514a2aef0039f3eb0da15eedb62b983d0545af0ba219f176013/detection

**Comment by Chinaski1** [comment]
Hello there!

Last week we contacted SangforEngine Zero about a false positive trigger.
I think `Adguard.apk` will be removed from the list soon.
