### ISSUE TITLE
Some Public WiFi doesn't allow Alternate DNS

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#4047]
### Issue Details

- **AdGuard version:**
  -  v4.0n27 (68)
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  TCL 10L
- **Operating system and version:**
  -  Stock Android 11
- **Root access:**
  -  No

### Expected Behavior

My DNS server choice should work anyplace.

### Actual Behavior

Some public wifis don't allow any other DNS.

### Additional Information

Logs sent via app ticket# 559090 referencing back here.

**Comment by TPS** [comment]
Data point: this reinduces https://github.com/AdguardTeam/AdguardForAndroid/issues/3904 in FFUpdater's latest version.

**Comment by ameshkov** [comment]
Well, I am not sure we can do anything here. This indeed happens that public Wi-Fi limit what DNS servers can be used, they can even actively block other DNS servers.

**Comment by TPS** [comment]
How exactly does this break?  I thought that part of encrypted DNS is to prevent this kind of thing?

**Comment by dnovitskyi** [comment]
Logs received and available in ticket 559090.

**Comment by ameshkov** [comment]
@TPS when the user is not yet authenticated, using the hotspot's DNS may be necessary to resolve the captive portal's IP address. Everything else would be unavailable.

**Comment by TPS** [comment]
Depending on the wifi, that doesn't match what I experience:
- On some of these wifi, there's _no_ captive portal: keep default DNS, & just browse.
- On others, if using default DNS to complete captive portal, switching to different DNS afterwards kills wifi data flow, though connection is fully established.

**Comment by ameshkov** [comment]
Generally, when you're already authenticated or the network has no captive portal, there should be no issues unless the network administrator actively blocks known DNS providers.

**Comment by TPS** [comment]
> unless the network administrator actively blocks known DNS providers.

I don't remember specifically testing _this_.  OpenDNS _is_ well-known enough, I suppose, for this to be feasible. I think I saw the default for the logs' wifi was Google's, so next time I run into this, I'll try a different more obscure DNS.
