### ISSUE TITLE
http://play.ludigames.com/ - can't start a game

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#405]
http://play.ludigames.com/
при нажатии на любую игру - черный экран
http://prntscr.com/alf5xw
Отключение фильтров не помогает. Помогает полное отключение программы

WWS-825-72814

**Comment by Revertron** [comment]
Is it on Android???

**Comment by evgeniy-ADG** [comment]
The bug was spotted on windows, it still persists
![image](https://cloud.githubusercontent.com/assets/15856304/15354376/f1a6d8e4-1cf5-11e6-8c3f-61f7f346f37b.png)

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/ExperimentalFilter/issues/2177
