### ISSUE TITLE
pref.proxy.block.ipv6 does not work on cellular connection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4053]
Unfortunately, IPv6 stays connected.

It'd be better if we could somehow change APN settings automatically and block IPv6 there.

**Comment by techIndia-hacker** [comment]
Use root privileges

**Comment by lancelot-moon** [comment]
My phone is rooted.
Already moved AG certificate to system store by magisk.

After setting APN protocol to IPv4 only, local HTTP proxy auto mode works fine.

Is local HTTP proxy auto mode with IPv6 not overcome technically?

**Comment by techIndia-hacker** [comment]
Q:Is local HTTP proxy auto mode with IPv6 not overcome technically?
A: No, adguard root proxy can't filter in ipv6 mode, yet

**Comment by ameshkov** [comment]
Well, it actually works okay with IPv6 TCP, but there's a known limitation with DNS traffic that we cannot filter when it goes over V6.

**Comment by lancelot-moon** [comment]
In IPv6 only environment, what will it happen if enabling pref.proxy.block.ipv6?
No internet?
Thanks.

**Comment by techIndia-hacker** [comment]
Yes

**Comment by artemiv4nov** [comment]
This tasks have already been done a few days ago. Please follow the `v4.0` milestone.
