### ISSUE TITLE
Adguard cannot block m-indicator Android app ads

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4057]
@pushkargogte commented on [Mon Nov 29 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531)

### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

m-indicator

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track header

### Add your comment and screenshots

Adguard VPN cannot block m-indicator Android app ads but Blokada 5 VPN does block it.

### Privacy

- [X] I agree to follow this condition

---

@Alex-302 commented on [Mon Dec 06 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-987006880)

What is not blocked?

---

@pushkargogte commented on [Wed Dec 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-988362434)

![Screenshot_2021-12-08-05-35-53-87_aeb0ebc324083679b8394bd89c3a8fe3](https://user-images.githubusercontent.com/16486468/145125143-e4761f95-abdf-48b0-885f-8113ce427d8e.jpg)

This adscreen at exit is shown while exiting the app using Adguard but while using Blockada the app will exit without showing the ads screen

---

@Alex-302 commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989712927)

I don't see this window when exit.
This app? https://play.google.com/store/apps/details?id=com.mobond.mindicator
Please secord a video.

---

@Alex-302 commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989717293)

And what is blocked by Blokada?

---

@pushkargogte commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989728080)

The ads are blocked by Blokada. Yes the app you mentioned.

I'm sending you the video on telegram

---

@pushkargogte commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989731446)

Alex check your telegram message

---

@Alex-302 commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989863528)

@pushkargogte Please try with enabled DNS filtering. I don't see that dummy with our DNS.

---

@Alex-302 commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989864200)

Also please clear cache before cheking. They do not show popup everytime even without ad blocker.

---

@pushkargogte commented on [Thu Dec 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-989894007)

Please check the latest video, the issue Exists on my phone even with your instructions.

---

@Alex-302 commented on [Fri Dec 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101531#issuecomment-991089550)

I don't know why. We block the same domains.

**Comment by pushkargogte** [comment]
Adguard Android app stats that it's https certificate is not accepted by m-indicator app

**Comment by ameshkov** [comment]
The difference is in how the domain is blocked.

If it's blocked on the DNS level, the connection is prevented and there's no issue at all.
If it's blocked on the content blocker level, AdGuard emulates a server error, but the app still tries to show the ad (and ends up with an empty ad placeholder).
