### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#4059]
<a href="https://fastpic.org/view/116/2021/1214/a0cec931ab03ddff1c802112836f5283.jpg.html" target="_blank"><img src="https://i116.fastpic.org/thumb/2021/1214/83/a0cec931ab03ddff1c802112836f5283.jpeg" border="0"></a> <a href="https://fastpic.org/view/116/2021/1214/fd27251adead0548c6b7b02b358a7da5.jpg.html" target="_blank"><img src="https://i116.fastpic.org/thumb/2021/1214/a5/fd27251adead0548c6b7b02b358a7da5.jpeg" border="0"></a>

**Comment by Chinaski1** [comment]
Не имеет смысла заводить подобные задачи, если речь идет о Nightly версии продукта.
Переводы на различные языки появляются не сразу, а как правило ближе к релизу.
