### ISSUE TITLE
Galaxy S4 adguard doesn't autostart upon reboot

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#406]
my galaxy s4 is on lollipop and it doesn't auto restart the filter upon reboot. on my two other android phones it does. they are motorolas. is this a samsung bug? i am on latest adguard beta

**Comment by ameshkov** [comment]
@jo2dan23 this is definitely not a common issue.

Could you please send us AG logs?

To do it:

1. Reboot your device
2. Open AG, menu -> send feedback
3. Post here the ticket ID (you'll get it in an autoreply).

**Comment by jo2dan23** [comment]
i figured out what is happening. it prompts EVERY reboot to let adguard use the vpn.(i am not the one using this phone so the person who is using the phone must be hitting cancel instead of ok.) but on my motorola it doesn't prompt upon reboot it automatically starts. maybe this cant be changed and is only a samsung thing

**Comment by jo2dan23** [comment]
also the notification that says the connection is being filtered doesn't go away after disabling it in the adguard app and in the settings part on the phone. it does on my motorola phone though. again. maybe just a samsung bug

**Comment by ameshkov** [comment]
> i figured out what is happening. it prompts EVERY reboot to let adguard use the vpn

That's an old Android bug, they have fixed it in Android 5.0 (yet on some Samsung devices it is fixed since 5.1)

**Comment by ameshkov** [comment]
> also the notification that says the connection is being filtered doesn't go away after disabling it in the adguard app and in the settings part on the phon

Oh yeah, one more Samsung "feature" :)

**Comment by jo2dan23** [comment]
thanks for the quick response.
