### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#4060]
https://github.com/AdguardTeam/AdguardForAndroid/issues/4059

@Chinaski1

> Не имеет смысла заводить подобные задачи, если речь идет о Nightly версии продукта. Переводы на различные языки появляются не сразу, а как правило ближе к релизу.

Не думал, что версия **AdGuard 3.6.4** - это **Nightly**

Может Вы сначала версию **3.6.4** доделаете, а то уже бету версию **3.6.5** выложили?

**Comment by artemiv4nov** [comment]
@GdeZsqyAY Hi!
Could you please describe a bit what do you mean?

**Comment by GdeZsqyAY** [comment]
@artemiv4nov 

У меня установлена версия

<a href="https://fastpic.org/view/115/2021/0920/0f89f47f403ce2d83caecc62131c2143.jpg.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0920/43/0f89f47f403ce2d83caecc62131c2143.jpeg" border="0"></a>

и в ней 3 пункта не до перевели

<a href="https://fastpic.org/view/116/2021/1214/a0cec931ab03ddff1c802112836f5283.jpg.html" target="_blank"><img src="https://i116.fastpic.org/thumb/2021/1214/83/a0cec931ab03ddff1c802112836f5283.jpeg" border="0"></a> <a href="https://fastpic.org/view/116/2021/1214/fd27251adead0548c6b7b02b358a7da5.jpg.html" target="_blank"><img src="https://i116.fastpic.org/thumb/2021/1214/a5/fd27251adead0548c6b7b02b358a7da5.jpeg" border="0"></a>

**Comment by artemiv4nov** [comment]
We kept a few texts blocks untranslatable intently. It's not a bug.
