### ISSUE TITLE
Extreme drop in speed with Adguard enabled

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/AdguardForAndroid#4062]
Tested on Adguard (latest stable build) and 4.0 nightly build# 28

Local VPN filtering mode
Samsung z flip3 (tested on 2 of them)
Android 11 with Nov security update
No root access on either device

This started a few weeks ago and I sent in a support request via the app but didn't file a report here.

Essentially when Adguard is enabled my phone's internet speed is VERY slow.  Webpages take way too long to load.

On fast.com with Adguard disabled I get an average of 730Mbps over wifi.

With Adguard enabled I'm getting between 3Mbps to 24Mbps but website aren't loading like I'm getting those speeds.

I haven't changed any settings and I only updated to nightly builds because of this speed issue but it hasn't had any effect on speeds.

If there is any other info needed I will provide it.

**Comment by Chinaski1** [comment]
Hello!

First, I would recommend that you try selecting several different DNS servers. Will there be a noticeable difference in speed?
Also, be advisable if you open low-level settings (Under Advanced section) and change MTU value for example to `9000`

Btw we plan to investigate the issue of speed reduction in upcoming updates in Corelibs.
So I close this task,  if you have any questions follow the corresponding issue https://github.com/AdguardTeam/CoreLibs/issues/1561

**Comment by d0x360** [comment]
I have tried literally every DNS server and type in Adguard.  I've also
shut DNS filtering off and there was no effect.

MTU at any value hasn't helped.   Neither has disabling filtered
extensions... I've basically changed every setting in the app...

I've also uninstalled the app, cleared my system cache from recovery,
rebooted and installed Adguard again and it's the same.

I don't know exactly when it began but I'd guess 3-4 weeks ago maybe.

**Comment by d0x360** [comment]
I did a ton of testing today to try and figure out if it's a specific setting or filter that's absolutely destroying speeds.  Even websites take forever to load.

Anyways I found nothing useful. I disabled everything in Adguard except the the base filter and I still got really bad speeds.

So I'm completely out of ideas..
