### ISSUE TITLE
Websites won't stay logged in

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/AdguardForAndroid#4063]
Tested on Adguard (latest stable build) and 4.0 nightly build# 28

Local VPN filtering mode
Samsung z flip3 (tested on 2 of them)
Android 11 with Nov security update
No root access on either device

I don't know why but I'll login to a site and come back 20 min later and need to login again.

Destruction of 1st party cookies is disabled.  I did try to enable it and set it to 9999 but that didn't help.

Any further info can be provided.

**Comment by Chinaski1** [comment]
If the issue still recurs, let's analyze it in the context of this task  https://github.com/AdguardTeam/AdguardForAndroid/issues/4064
