### ISSUE TITLE
Certain websites not working. 

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/AdguardForAndroid#4064]
I've recently noticed multiple websites not working correctly when Adguard is enabled.  I'm going to compile a list as I come across them.  Essentially some part of the site is completely broken.  Should I add to this ticket or make new ones as I come across them?

- Xbox.com - Can't buy things/checkout
- Microsoft.com - Can't buy things/checkout
- epicgames.com/store/en-US/ - Can't use search feature
- Newegg.com - checkout issues
- CVS.com & the App - Errors when submitting orders/refill
- Amazon App - issues with chat support
- Comcast.net - issues with site when logged in, issues with chat.
- Answers.ea.com/t5/Answer-HQ-English - issues creating support tickets
- Kinja/Kotaku.com - login issues(don't fix this one 🤣)
- Packagedisablerpro.com - Website doesn't work after login
- Verizonwireless.com issues with forums, chat support
- Hulu.com support area, chat support

That's all I have for now but I know I've come across quite a few more and I'll start keeping track because I'm disabling Adguard quite a bit lately to get sites working properly. 

1. Android 12 w/latest security update (may 11th)
2. Adguard 3.6.5 but also happens with 3.6.4 and nightly builds 44-48.
3. Samsung zFlip3 & note 10+
4. VPN Filtering
5. NOT rooted
6. Gigabit connection with wifi6e router.

**Comment by Chinaski1** [comment]
Hello there!

In fact, there could be many reasons for this behavior.
For first you should try to disable Stealth-mode and third party filters.

**Comment by Chinaski1** [comment]
Also, To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send the received file to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by d0x360** [comment]
It's not stealth, I know that for sure because today I was doing testing for the massive speed loss issues posted about here https://github.com/AdguardTeam/CoreLibs/issues/1561#:~:text=I%20did%20a%20ton%20of%20testing%20today and I added some new info to the post today.

I will get you logs but I probably need a few days... My father passed away Thursday so... Well I'm sure you understand.

I do have another site or at least section of a site to add to the list and that's chat support on hulu.com

It works perfectly with Adguard disabled but not at all with it enabled.  I tested in chrome, edge, Firefox nightly and Opera GX.

So bare with me and I'll get you the info you need.  My only question is how many of the sites I've found to have problems should I gather logs for?  

I ask because some of them aren't just loading a page, some involve actually buying something or getting chat support.

Thanks

**Comment by Chinaski1** [comment]
Let's take a few sites that have the most issues and will research them.

https://github.com/AdguardTeam/AdguardForAndroid/issues/4063 regarding this issue, just curious did you try to disable [`Tracking methods`](https://uploads.adguard.com/Chinaskixes6a.png) column? Will it stop logging you out?

**Comment by d0x360** [comment]
I tried disabling everything in Adguard except the base filter in
adblocking and I was still being logged out of sites.  On the sites I would
always check the keep me logged in box if there was one but it never worked.

Like the sites Amazon, xbox, PayPal & more would constantly log out when
using a browser.  I tried multiple browser as well and I disabled any
AdBlock or anti tracking features in the browsers.

**Comment by Chinaski1** [comment]
Hello @d0x360 

Please send the log files when it is convenient for you.

**Comment by d0x360** [comment]
My apologies, my father's passing hit me much harder than I expected. 

I am still getting logged out all the time on any browser I test with.  Ive tried disabling everything except the base Adguard filter list.  

I've also still been having the same issues on the sites I listed in to the original post but I've had more problems like pages rendering incorrectly or not being able to scroll down even though I can see that the entire page is rendered.  Or rendering errors like the page is squished or missing or element that causes on side of the site to be in the middle instead of on the left or right.

These things happen in Chrome, Edge Firefox beta, and Opera GX.

I'll get you the logs and start documenting all the sites and the issue(s) with a screen shot but I won't post them all, I'll keep them saved on my phone in Clipto (a fantastic app) and if asked I can send the entire list or parts of it.

Thanks for your help and I appreciate your patience

**Comment by d0x360** [comment]
My fault... Obviously.  I just haven't felt like doing this kind of thing since my father's passing. I haven't even rooted my pixel 6 and I've been using this garbage zFlip3 for months.

Ok so off the top of my head, and mostly because it happens constantly even if I check the stay logged in checkbox...

https://store.steampowered.com/
https://www.cvs.com/account/login/
https://www.nexusmods.com
https://steamcommunity.com/
https://www.pcgamingwiki.com

I'll get some more as I come across them because there are definitely more and I've factory reset my phone, tried multiple browser, used only the base filter in Adguard and it has continued to happen.

Hell it just happened with steam.  I logged in to check something and then an hourish later I went back to redeem a code and had to login again. 

Also no they aren't all gaming related sites lol.

**Comment by d0x360** [comment]
Microsoft.com
Xbox.com
Amazon.com

**Comment by Chinaski1** [comment]
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by d0x360** [comment]
Ok, I'll have them to you within a couple days.  Id do it all now but it
happens completely at random but before visiting any of them from this
moment on I'll have it gathering all needed info in the logs.

It's Tuesday at 5:15am for me right now and I'm about to go to bed.  I'll
have logs ready by.. let's say Thursday at 8pm my time.  That will
hopefully allow me to get every site I've listed and probably a couple
more.

**Comment by d0x360** [comment]
Apologies again for the slow response.  Family stuff has to come first.

So I have logs for 1 site at the moment.  Although it's possible that any xbox.com items and Microsoft.com items might show me needing to login multiple times.

So this site loaded but if Adguard was enabled no matter how many times I tried to login the page wouldn't load.  I disabled Adguard, waited 5 seconds, clicked the link and it worked instantly.

https://support.halowaypoint.com/hc/en-us

Log file. 

https://drive.google.com/file/d/14RJai3CZMKiJWdhDvPcYrBg8oKcrT92v/view?usp=drivesdk

I'll try to speed up the process with logs.

**Comment by d0x360** [comment]
Here's another.  This applies to basically xbox.com, Microsoft.com etc.  It constantly makes me login even though I tell. It to stay logged in.

Logs attached

**Comment by d0x360** [comment]
Steam website.  Had just logged in and checked to remember the PC maybe 30 min to an hour (max) prior and like everything else listed so far I have to log in again..

I'm posting them as they happen.  I can't seem to find a pattern.  I'm likely going to be switching to a pixel 6 pro by mid week.  This is happening on a Samsung zFlip3.  I have factory reset it recently (twice) and the issue has persisted but if it just vanishes when I switch I'll close with comment.

Logs...

[adguard_logs_4.0.75_1405_160719.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/8693774/adguard_logs_4.0.75_1405_160719.zip)

**Comment by d0x360** [comment]
I know these aren't the more extensive logs that Adguard can make but leaving that running on my phone 24/7 is killing performance if my phone in general but it's also causing a wifi6e signal that I usually get about 650-800Mbps on with Adguard enabled and bringing it down to an averaged speed of 147Mbps on 2 different speed test sites but actual performance feels more like dial up and battery life is... Awful. 

Since the issue happens completely at random I can't enable the logging and reproduce.  I have no idea why it's even happening.

I have 6+ mobile devices with Adguard and 4-5 desktop/laptops running Win 10 Pro, Home, and 1 device running Win 11 Pro and the only device it happens on is Samsung's and only on Android 12.  On 11 it's fine.  I can't test 13 beta. 

I have to stop.

I'm missing important work email because for some reason the lag is causing email to come in at odd intervals and 50-100 at a time instead of immediately getting a notification when ive gotten 1-5.

Since this issue apparently effected nobody else I don't see any reason to keep going.

I'm going to remove the links to my logs for privacy sake.
