### ISSUE TITLE
$removeparam does not work

### ISSUE THREAD

**Issue by techIndia-hacker** [AdguardTeam/AdguardForAndroid#4065]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3 6.5
- **Filtering mode:**
  - Local Vpn
- **Device:**
  - Oneplus 7t
- **Operating system and version:**
  - Android 11
- **Root access:**
  - Yes

### Expected Behavior

$removeparam should remove given parameters from  specified domain URL

### Actual Behavior

 NO changes in the URL is observed in https post reqs

### Screenshots

<details>
So the ookla speedtest app sends sensitive data line IMEI no. device fingerprint, phone tower area code etc to their servers. I want to block this by stripping off the tracking parameters from the URL.
The rule I created is this:-
||speedtest.net^$removeparam=/^(fingerprint|build_id|imei)=/
But it doesn't work. The URL is unmodified as displayed in filtering logs.
@ameshkov said that adguard can only modify document type https data in POST reqs, and will be improved later

Request to please fix this as soon as possible

</details>

### Additional Information

Text me as "Ayan_c99" in telegram for screenshots. Although @ameshkov has all the info

**Comment by ameshkov** [comment]
Applying $removeparam to POST requests is technically possible, but might be dangerous.

This issue should be moved to the CoreLibs repo and triaged there.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1573](https://github.com/AdguardTeam/CoreLibs/issues/1573) via [**ZenHub**](https://www.zenhub.com/)

**Comment by techIndia-hacker** [comment]
But u said in telegram that it's already done in corelibs and will come
soon in adguard android too??

When is it coming?

Ayan
