### ISSUE TITLE
block custom ads on browser

### ISSUE THREAD

**Issue by bingoxo** [AdguardTeam/AdguardForAndroid#4066]
how can i block an ad on a webpage manually that wasn't picked up by the app ? (android premium)

**Comment by Chinaski1** [comment]
Hello there!

In this case, you can connect your smartphone to your computer, open `dev.tools` in the browser, highlight the desired item and send us a screenshot. We will help you to create a blocking rule.

But the easiest way is to [complaint](https://kb.adguard.com/en/technical-support/reporting-tool) to the filter developers. They will sort out the appeal and block the missing ads as soon as possible.

**Comment by bingoxo** [comment]
isn't there a way to do it like with desktop ?

**Comment by Chinaski1** [comment]
Unfortunately, the tools available in the mobile version of the browser are not enough.

That's why a connection to a PC is required.
