### ISSUE TITLE
Cloud sync for entire settings

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#4067]
### Problem Description

I have many devices using AdGuard for Android. Setting each devices settings for AdGuard for Android when we have a change can get quite cumbersome.

### Proposed Solution

Having a way to remotely push configuration changes would be of great benefit.

**Comment by maxikuzmin** [comment]
@jslawler new update 4.0 is coming out very soon. Please check this after the update and let us know the results.

**Comment by artemiv4nov** [comment]
Well, this feature request is popular, let's see how many likes the task will collect.

**Comment by artemiv4nov** [comment]
Closed as a dublicate of #134
