### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#4069]
Использую **AdGuard 3.6.5** на **Android 10**

В приложении **YouTube** выбрано качество видео **1080**, но при использовании Вашего совета по удалению рекламы https://www.comss.ru/page.php?id=8368 , то видео открывается в наихудшем качестве ( текст и видео не четкие ).

Как в Вашем совете открыть видео в желаемом качестве?

**Comment by Chinaski1** [comment]
На данном возможность выбора качества видео не предусмотрена.
Оно выбирается автоматически основываясь на скорости соединения.
В будущем мы планируем добавить такую возможность.
