### ISSUE TITLE
Profile Adguard https filtering and look for bottlenecks

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#407]
We now slow down YT metadata loading because of the way we do the filtering.

It takes pretty much time to read & edit meta data responses.

Example (first part of the video: AG with HTTPS filtering, second: AG without HTTPS filtering).
https://www.youtube.com/watch?v=F-Fv7le8JFg&feature=youtu.be

**Comment by Revertron** [comment]
I suspect that pictures are cached. Lets make reverse-test. Begin without HTTPS-filtering and then with HTTPS-filtering.

**Comment by ameshkov** [comment]
Maybe the issue is not about YT, user claims that HTTPS filtering is pretty slow for him in general.

Before release we should anyway check it with a profiler.

**Comment by Revertron** [comment]
The only bottleneck that I see is the math in crypto functions in BouncyCastle.

**Comment by ameshkov** [comment]
I suppose this means we should not advise using https filtering to everyone.

**Comment by TPS** [comment]
@ameshkov Does blacklist mode profile identically to having HTTPS-filtering _off_ for sites _not_ in the list?

**Comment by ameshkov** [comment]
@TPS basically yes. But take a note that we are talking about domains, not websites.

For instance, if you add youtube.com to the blacklist, AG will filter all connections to youtube.com domain. But if you look inside YT page code, you'll see that most of it's static content is loaded from ytimg.com domain which won't be filtered.

**Comment by TPS** [comment]
The reason I asked: I have a hunch that _Android_ has some effect overall on the network connection just because of having the AG root certificate _installed_.… Or is it all in my head?  I've removed the certificate, & things seem to normal again.

**Comment by ameshkov** [comment]
> I have a hunch that Android has some effect overall on the network connection just because of having the AG root certificate installed.… Or is it all in my head? I've removed the certificate, & things seem to be normal again.

No, that's just no possible, having an additional certificate has no impact, that's for sure.

**Comment by Revertron** [comment]
We can show some warning dialog to users with slow devices when they enter HTTPS-filtering fragment.
