### ISSUE TITLE
Adguard breaks Tesla App

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/AdguardForAndroid#4070]
### Issue Details

- **AdGuard version:**
 3.6.5, 4.0 nightly 29 
- **Filtering mode:**
Local VPN
- **Device:**
S10e and s21
- **Operating system and version:**
Android 11 and 12
- **Root access:**
no

### Expected Behavior

tesla app still works with adguard installed

### Actual Behavior

Tesla app completely broken, can not log in
This has been verified on multiple devices. And has been reported by another user as part of another issue https://github.com/AdguardTeam/AdguardForAndroid/issues/1776#issuecomment-930096021

### Additional Information

The problem can be solved by disabling filtering for the Tesla app in the apps management settings. This should be changed to the default.

**Comment by Chinaski1** [comment]
Hello there!

The issue is not reproduced on my side.
Can you export the settings and send them to support@adguard.com?
Please don't forget to mention the link to this task when sending an email to support.

**Comment by Chinaski1** [comment]
Closed due not reply.

Reopen the task if the issue is still reproduced.
