### ISSUE TITLE
Auto Disable AdGaurd When WiFi Disconnects

### ISSUE THREAD

**Issue by ThePieMonster** [AdguardTeam/AdguardForAndroid#4071]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Problem Description

On Android, when you disconnect from your home network, auto disconnect from AdGaurd VPN. 

I did not find this setting in the app, and it would be greatly appreciated.

**Comment by Chinaski1** [comment]
Hello there!

Could you be more specific, do you have the protection disabled when you disconnect from the home network?

Or would you like to add the ability to automatically disable the protection when disconnected from a particular network?

**Comment by ThePieMonster** [comment]
@Chinaski1 
`do you have the protection disabled when you disconnect from the home network?`

Correct, disabling protection when you leave your home network.

Example:
I leave my home wifi network, device switches to 4G LTE, AdGaurd sees its no longer connected to wifi and thus turns off the adgaurd protection.
![Screenshot_20211223-140035](https://user-images.githubusercontent.com/11359134/147286945-eb1aa405-81ae-4f8f-a3a6-1b6699c502e0.png).

**Comment by infinitewaveparticle** [comment]
i`m almost 100% certain this guy is asking for a feature request and isnt too keen on the jargon...

**Comment by trySometngNew** [comment]
Hi Everyone,
I am also facing same issue described here. Below are details for debugging purposes

------------------------------------------
AdguardForAndroid Version: v3.6.7 (41)
Mobile OS: Android (7.0 NRD90M)
Auto-start: enabled for Adguard
App Lock w.r.t. battery optimization: Enabled for Adguard (app will not be terminated/hibernated by OS for battery optimization purposes)
AdGuard License: No License
AdGuard Certificate Installed: Yes (Locally)
------------------------------------------

Issue Description: As soon as I disconnect WiFi and turn on mobile data, AdGuard stops. I need to manually start it. This has been observed at least on 2 consecutive days.

**Comment by artemiv4nov** [comment]
To disable the AdGuard protection automatically when you connect to Wi-Fi, you can use one of many Tasker-type applications. We provide an Automation section inside the settings, please try it.
