### ISSUE TITLE
com.whatsapp - calling issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4074]
@adguard-bot commented on [Fri Dec 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101902)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.whatsapp&hl=en](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.whatsapp%26hl%3Den)
### Comment
Username: @ihrubab
> After yesterday's update to v3.6.5 beta 1, whenever I call or receive a call from Facebook Messenger or the WhatsApp Messenger app, it gets stuck at "Connecting" and never connected. If I turn Off Adguard or disable Adguard Protection in app management, I can call and receive calls without any problems. 
> 
> This problem started happening after yesterday's Adguard update. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7Y5uHvI.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/NeNY9NO.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.5 beta 1 (35)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Block third-party Authorization header, <br>Self-destructing third-party cookies (180), <br>Block WebRTC, <br>Block Push API, <br>Hide your Referrer from third-parties (), <br>Hide your Referrer from third-parties, <br>Hide your IP address (209.141.53.254)
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>Peter Lowe's Blocklist, <br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>Fanboy's Anti-Facebook List, <br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Fanboy's Annoyances, <br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by Chinaski1** [comment]
`Block WebRTC` causes this issue.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1574](https://github.com/AdguardTeam/CoreLibs/issues/1574) via [**ZenHub**](https://www.zenhub.com/)
