### ISSUE TITLE
Unable to update filters in proxy mode

### ISSUE THREAD

**Issue by Zero456s** [AdguardTeam/AdguardForAndroid#4079]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  3.6.6
- **Filtering mode:**
  VPN
- **Device:**
  xiaomi6
- **Operating system and version:**
  Android11
- **Root access:**
  no

### Expected Behavior
The filters is updated normally in proxy mode

### Actual Behavior
The proxy was bypassed and the filters update failed

### Screenshots
![Screenshot_20211231-192837_Quickstep](https://user-images.githubusercontent.com/83749807/147821229-c7e40b9f-d787-4c61-b9ff-fb587ef30b18.png)

<details><summary>Screenshot:</summary>

</details>

### Additional Information
Some third-party filter update addresses need to be updated through a proxy

**Comment by Chinaski1** [comment]
Hello!

The issue does not occur when trying to update the standard filters used in AdGuard.
Can you send us links to the filters you use so that we can check the situation?

**Comment by Zero456s** [comment]
GitHub cannot be accessed normally in China, so the update of this rule will fail. For Chinese users, it can only be updated through the proxy, but I found that the filter cannot be updated when the proxy is turned on, and I suspect that the proxy is bypassed

https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt

**Comment by Chinaski1** [comment]
Unfortunately, we cant help you at this stage because we do not pass our own traffic through proxies. That`s why you are not able to update your own filters.
