### ISSUE TITLE
Update filters only WiFi setting is broken

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#4081]
Issue: [Обновление фильтров](https://forum.adguard.com/index.php?threads/%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2.46142/)
It looks like the filters are updated with mobile data turned on without WiFi is open

**Comment by Chinaski1** [comment]
The issue is not reproduced.
