### ISSUE TITLE
Кнопка "переустановить" в настройках userjs-скрипта "расширения" не обновляет его из исходного userjs-файла

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#4083]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
3.6.4(32)
- **Operating system and version:**
Android 5.1
- **Root access:**
Yes

### Actual Behavior

Нажатие кнопки "переустановить" в настройках userjs-скрипта "расширения" не обновляет его из исходного userjs-файла в случае изменения оного. Это видно и по поведению скрипта и по тому, что *.meta и *.source файлы скрипта в папке /data/data/com.adguard.android/files/userscripts/ не изменяются.

### Expected Behavior

Нажатие кнопки "переустановить" в настройках userjs-скрипта расширения должно обновлять его из исходного userjs-файла в случае изменения оного.

**Comment by Chinaski1** [comment]
Давайте рассмотрим данный вопрос в рамках созданной вами [ранее задаче](https://github.com/AdguardTeam/AdguardForAndroid/issues/3961).
