### ISSUE TITLE
Quora is broken

### ISSUE THREAD

**Issue by kamharry** [AdguardTeam/AdguardForAndroid#4084]
![IMG_20220107_232035](https://user-images.githubusercontent.com/72760738/148585586-fd10bd65-7748-45c2-8a4f-1b85be56e2d6.jpg)
### Issue Details
- **AdGuard version:**
  - v3.6.38
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Redmi k20
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

Quora is completely broken and is not working without disabling adguard.. i disabled dns filter and all content filter yet the site failed to open but as soon as i disable adguard protection the site works fine.
Please look into the matter.

**Comment by Chinaski1** [comment]
Hello!

The issue is not reproduced on my side.
Could you export the settings and send them to devteam@adguard.com?

- AdGuard settings -> General -> Export settings

Also, please specify Do you use third-party applications that might cause a compatibility conflict? For example, antivirus or something similar.

**Comment by Chinaski1** [comment]
Any updates?

**Comment by kamharry** [comment]
Settings emailed sir

**Comment by kamharry** [comment]
Chrome + adguard only nothing else..

**Comment by Chinaski1** [comment]
I was able to figure out that the issue is related to one of the low-level settings.

Open AdGuard settings - Advanced -> Low-level -> Reset.

**Comment by kamharry** [comment]
Resetting also not fixed the issue 🙄

**Comment by Chinaski1** [comment]
Also try disabling third-party extensions.

**Comment by kamharry** [comment]
low level settings issue + Adguad popup blocker extension was an issue ... Thankuh for the help sir
