### ISSUE TITLE
tokyomotion.net

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForAndroid#4085]
https://www.tokyomotion.net/video/1208570/%E3%81%8A%E3%82%86%E3%81%86%E3%81%8E%E3%81%AE%E3%81%86%E3%82%89

AdGuard causes this bunch of weird symbols at the bottom of this site, disabling of HTTPS-filtering helps only.

<details>
  <summary>Screenshot 1</summary>
<img src="https://i.imgur.com/0Vepc0x.jpeg" />
</details>

The original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/102948

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1584](https://github.com/AdguardTeam/CoreLibs/issues/1584) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1585](https://github.com/AdguardTeam/CoreLibs/issues/1585) via [**ZenHub**](https://www.zenhub.com/)
