### ISSUE TITLE
Unable to update ad rules and extensions in China

### ISSUE THREAD

**Issue by hacamer** [AdguardTeam/AdguardForAndroid#4086]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.6
- **Filtering mode:**
  - Local VPN
- **Device:**
  - 
- **Operating system and version:**
  - Android 6.0.1
- **Root access:**
  - Yes

### Expected Behavior

I want to update ad rules and extensions

### Actual Behavior

Unable to update ad rules and extensions

### Screenshots

<details><summary>Screenshot:</summary>

![2022-01-14 11 15 54](https://user-images.githubusercontent.com/73057402/149445649-7b0f7d1f-276d-4af1-b0ac-0b83b290a6be.png)

</details>

### Additional Information

In China，Rules(Filter) and Extensions are can't update . Please solve this problem

**Comment by Chinaski1** [comment]
Hello!

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Try to update filters
2. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
3. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
4. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by hacamer** [comment]
> Hello!
> 
> To troubleshoot this issue, we need to get additional logs.
> 
> Here's what we need you to do:
> 
> 1. Try to update filters
> 2. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> 3. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> 4. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

Hi sir. When I add the following fields to my device's hosts file
```
89.187.185.87 filters.adtidy.org
89.187.162.244 filters.adtidy.org
2a02:6ea0:d12f::1 filters.adtidy.org
89.187.185.87 adtidy.org
2606:4700:10::6816:42db sb.adtidy.org
2606:4700:10::6816:43db sb.adtidy.org
2606:4700:10::ac43:1585 sb.adtidy.org
104.22.66.219 sb.adtidy.org
104.22.67.219 sb.adtidy.org
172.67.21.133 sb.adtidy.org
```
My AdGuard was able to successfully update the rules
What's the problem?

**Comment by Chinaski1** [comment]
Some of the IP addresses may have been blocked.

We have changed these addresses, so it makes sense to check on the default settings.

**Comment by hacamer** [comment]
> Some of the IP addresses may have been blocked.
> 
> We have changed these addresses, so it makes sense to check on the default settings.

# Thank! 
Now I can successful to update filter  
very thank AdGuardTeam😘
