### ISSUE TITLE
Add notification: The size of the filter is too large to perform the update

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/AdguardForAndroid#4088]
无法更新大规则，大概是55m大的规则
https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adblock.txt

**Comment by Potterli20** [comment]
[adguard_logs_4.0.72_1801_145054.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/7886851/adguard_logs_4.0.72_1801_145054.zip)

**Comment by Chinaski1** [comment]
@Potterli20 

The size of the filter is too big to be updated through the app.
In the future we will add an appropriate notice not to confuse users.

**Comment by Potterli20** [comment]
> @Potterli20
> 
> The size of the filter is too big to be updated through the app. In the future we will add an appropriate notice not to confuse users.

okay

**Comment by artemiv4nov** [comment]
Well, I will think the problem is resolved, and will close the task
