### ISSUE TITLE
Add split tunneling to allowlist/blocklist which apps use the proxy 

### ISSUE THREAD

**Issue by bingoxo** [AdguardTeam/AdguardForAndroid#4093]
using adguard 3.6.6 (latest atm) , vpn mode (not rooted) , i wanted to encrypt my trafic and hide my ip , using another vpn alongside is not possible since adguard isusing the vpn slot , so i have to either use a proxy or adguard vpn , for proxies , it seems a lot of them are unencrypted (socks5 (which seems to be what adguard vpn is using !) socks 4 http) , i'm afraid that many people using them now don't know that , the only viable solution for me seems to be https proxy , i set one up and it worked , until i did a webrtc leak test and found my ip leaked , this can be mitigated with blocking webrtc but i would like that webrtc works but with my ip hidden (like how it works when adguard vpn is in compatibility mode aka socks5)

ps : is there a way to implement split tunneling to whitelist/blacklist which apps use the proxy ?
i noticed lan network is accessible using the proxy , is there a way to change it ? personally i like it this way but maybe others wouldn't

**Comment by Chinaski1** [comment]
Hello!

We are planning to make some changes. I can tell you for sure that we will most likely implement this part `is there a way to implement split tunneling to whitelist/blacklist which apps use the proxy ?`
