### ISSUE TITLE
Adguard app doesnt turn on after wifi off/mobile data on, or wifi cut off/on

### ISSUE THREAD

**Issue by Titanposeidon** [AdguardTeam/AdguardForAndroid#4094]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - <! nightly 4.0.72 
- **Filtering mode:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Titanposeidon** [comment]
previous msg i guess not view all, so here the issue :

while i am connected to wifi and adguard android is running, after wifi cutting off (transition 5 ghz to 2 ghz )  or passing wifi to mobile data then wifi again, adguard app turns off and not running automatically , so internet cut off

**Comment by Chinaski1** [comment]
Looks like this issue is closely related to https://github.com/AdguardTeam/AdguardForAndroid/issues/4092
I will close this task, all further discussions will be held at #4092
