### ISSUE TITLE
AdGuard DNS and AdGuard for Android not able to filter ads for SSG

### ISSUE THREAD

**Issue by tosouravbhor** [AdguardTeam/AdguardForAndroid#4097]
I have set up AdGuard for DNS and AdGuard for Android to block the Ads traffic to be loaded in SSG, but I fail to block ads every time. The default filters are not enough to detect and block the advertisements. Please resolve it ASAP.

**Comment by Chinaski1** [comment]
Hello there!

Please describe your issue in more detail. Which `SSG` are we talking about?

**Comment by tosouravbhor** [comment]
SSG or Step Set Go is an Indian fitness tracking app. It does have advertisements inside to which users get rewarded for the actions they ask us to take through in-app video ads. The ads themselves are very annoying, and being a premium member of AdGuard, I expect them to be blocked completely.

**Comment by Chinaski1** [comment]
Could you please provide a link to the application?

But usually, if you find a missed ad, it is advisable to [send a report](https://kb.adguard.com/en/technical-support/reporting-tool#Android) to the filter developers. They will review your complaint and block the missed ads.

**Comment by tosouravbhor** [comment]
Here is the link for the app, https://play.google.com/store/apps/details?id=com.pepkit.ssg and the website for the same to learn more is here, https://www.stepsetgo.com/

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardFilters #109103](https://github.com/AdguardTeam/AdguardFilters/issues/109103) via [**ZenHub**](https://www.zenhub.com/)
