### ISSUE TITLE
Google Play: com.teachmint.teachmint

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4098]
@adguard-bot commented on [Thu Jan 27 2022](https://github.com/AdguardTeam/AdguardFilters/issues/108323)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.teachmint.teachmint](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.teachmint.teachmint)
### Comment
Username: @Vishupal4185
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/SG7ERWT.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/XxmdfKz.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 8.1.0
AdGuard product: | AdGuard for Android v3.6.6 (38)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Block third-party Authorization header, <br>Self-destructing third-party cookies (180), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Hide your Referrer from third-parties (), <br>Hide your Referrer from third-parties
DNS filtering: | server: `https://dns.nextdns.io/63ebf9/vivo1801`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt, DnsUserRules`
Filters: | <b>Ad Blocking:</b><br/>EasyList, <br/>AdGuard Mobile Ads, <br/>Peter Lowe's Blocklist, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>Legitimate URL Shortener, <br/>AdGuard URL Tracking, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>Fanboy's Annoyances, <br/>EasyList Cookie List, <br/>Web Annoyances Ultralist, <br/>I don't care about cookies, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>NoCoin Filter List, <br/>Online Malicious URL Blocklist<br/><br/><b>Other:</b><br/>AdGuard DNS
Custom filters: | https://secure.fanboy.co.nz/fanboy-indian.txt
Userscripts: | https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js,<br>https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://greasyfork.org/scripts/423851-simple-youtube-age-restriction-bypass/code/Simple%20YouTube%20Age%20Restriction%20Bypass.user.js

---

@Alex-302 commented on [Thu Jan 27 2022](https://github.com/AdguardTeam/AdguardFilters/issues/108323#issuecomment-1023316526)

@vishupal4185 Too much filters. What break this app - filters, DNS, stealth mode? Also test when filters, dns filtering and stealth mode are disabled.

---

@vishupal4185 commented on [Sat Jan 29 2022](https://github.com/AdguardTeam/AdguardFilters/issues/108323#issuecomment-1024875701)

1. Added app to the allowlist ( DNS filterining and stealth mode enabled) : Doesn't work.
2. Turned DNS Filtering off ( only stealth mode enabled) : Doesn't work.
3. Turned off Stealth mode ( Adguard is running; App in Allowlist; DNS and stealth doisabled) : Doesn't work.
4. Disabled adguard completely: working fine.

**Comment by Alex-302** [comment]
@vishupal4185 Please collect *debug* level logs aтв send to support@adguard.com with the link of this issue.
[com.teachmint.teachmint](https://kb.adguard.com/en/android/solving-problems/log#collecting-debug-log)

**Comment by vishupal4185** [comment]
@Alex-302 How do I do that?

**Comment by Chinaski1** [comment]
@vishupal4185 

Any news?

**Comment by Eugene-Savenko** [comment]
Logs in Zendesk: 575552

**Comment by vishupal4185** [comment]
@Chinaski1 No. Working properly now.

**Comment by ngorskikh** [comment]
This looks very much like one of those apps that just won't work with a VPN on older versions of Android. The logs don't show any connections from the app. I was able to reproduce the issue on Android 8.0.0 with AdGuard, as well as a different VPN app. It works fine with AdGuard on Android 12, however.

**Comment by infinitewaveparticle** [comment]
@ngorskikh What is it about these apps that make them work on some versions of Android and not on others? I had the same experience with ESET Mobile Security; it works fine on Android 5 and Android 9, but not on Android 7 or 8. By "work" I mean "work with AdGuard enabled"... I had to stop using it on Android 8 (my main Android device) because any "fix" that involves excluding it from filtering won't work when you "Block connections without VPN" or use AdGuard VPN's kill switch.
