### ISSUE TITLE
4.0 N 25 thru most recent version are not working at all

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#4099]
### Issue Details

- **AdGuard version:**
  -  4.0 n 25 thru at least 31
- **Filtering mode:**
  -  local vpn
- **Device:**
  -  nvidia shield pro (not most recent model)
- **Operating system and version:**
  -  android 9
- **Root access:**
  -  no

### Expected Behavior
updating adguard to newer nightly versions should not cause adguard to completely fail

### Actual Behavior
after upgrading to 4.0 n 25 or newer the, with or without adguard vpn also running, the filtering log shows the same IP address over and over and over again from an app called root. no traffic or data ever actually loads and the only option is to uninstall and downgrade back to 4.0 n 24, the final working version

### Screenshots

![Screenshot_20211230-210134](https://user-images.githubusercontent.com/29090831/151982272-5577acd7-e069-40b2-af9d-8c44925caca8.png)

<details><summary>Screenshot:</summary>

</details>

### Additional Information
![Screenshot_20211230-210053](https://user-images.githubusercontent.com/29090831/151982273-01e189e8-4267-41d9-b562-5c7c93b2a8aa.png)
![Screenshot_20211230-210113](https://user-images.githubusercontent.com/29090831/151982275-19068fb6-c025-4b63-b2bc-413c176d92ab.png)

**Comment by infinitewaveparticle** [comment]
![Screenshot_20211230-210138](https://user-images.githubusercontent.com/29090831/151982638-7c649e76-d109-4fb2-bbd6-229381bb325b.png)
![Screenshot_20211230-210149](https://user-images.githubusercontent.com/29090831/151982640-2e3c53e3-d5b2-4e1b-b0a0-a906b3062852.png)
![Screenshot_20211230-210134](https://user-images.githubusercontent.com/29090831/151982642-1f12bb8c-be6a-4213-a627-f922f0ccf261.png)
![Screenshot_20211230-205956](https://user-images.githubusercontent.com/29090831/151982644-fc3aaaca-0d2f-4b1e-ad1e-60509af183ad.png)
![Screenshot_20211230-210011](https://user-images.githubusercontent.com/29090831/151982645-e3a29ad9-b4f1-452b-8040-a3ae8716603e.png)
![Screenshot_20211230-204426](https://user-images.githubusercontent.com/29090831/151982648-d67a4c79-9f09-4322-ad72-3722019e2b12.png)
![Screenshot_20211230-205943](https://user-images.githubusercontent.com/29090831/151982650-8883c357-7ca5-4706-89ad-725496e51b5f.png)
![Screenshot_20211230-210053](https://user-images.githubusercontent.com/29090831/151982652-75c4239b-7d03-410c-b216-54142352fb74.png)
![Screenshot_20211230-210113](https://user-images.githubusercontent.com/29090831/151982654-e3d79719-2753-469d-8bca-bbbbaa116760.png)
![Screenshot_20211230-210018](https://user-images.githubusercontent.com/29090831/151982655-07297b69-25b8-4fd0-a91a-a33c005e1a6c.png)
![Screenshot_20211230-210044](https://user-images.githubusercontent.com/29090831/151982657-3a234ccf-2733-48b4-90a4-864249d72e7e.png)

**Comment by infinitewaveparticle** [comment]
as you can see there are several connections made only by root and adguard vpn... unblocking any of them doesnt help. disabling adguard vpn doesnt help. no apps load data at all. its as if i have no internet access at all

**Comment by infinitewaveparticle** [comment]
logs sent to devteam

**Comment by Chinaski1** [comment]
Hello @infinitewaveparticle 

Can you try to reproduce the issue on a plain bootstrap DNS server?

**Comment by infinitewaveparticle** [comment]
Could you be more specific? I use https://1.1.1.1/dns-query (and 1.0.0.1) for my upstreams, AdGuard DOH for bootstrap, and none for fallback.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment]
You should try to use a server without encryption, for example `8.8.8.8` or `94.140.14.14`

**Comment by infinitewaveparticle** [comment]
That would defeat what I want to accomplish with adguard. I dont use unencrypted dns

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment]
As an experiment put plain DNS servers in bootstrap settings.
Will the issue reproduce with this combination of settings?

**Comment by infinitewaveparticle** [comment]
I will need to upgrade again and try again. And then uninstall and downgrade. I'll let you know once I've done that.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment]
Hello again!

Could you please clarify the status of the issue? 
Is it still reproducing when using encrypted servers? 
Have you checked with Plain DNS servers?

**Comment by ameshkov** [comment]
@infinitewaveparticle looks like an infinite loop with AdGuard VPN.

Could you please tell us how is it configured? Is it in automatic integration mode or have you configured outbound proxy manually?

**Comment by infinitewaveparticle** [comment]
Hi @ameshkov, I have it configured manually via SOCKS5 to both make use of the Kill Switch and also to avoid AdGuard's connection restarting when first connecting to a VPN server or even when reconnecting sometimes (AdGuard VPN disconnects on its own quite regularly on all my devices despite disabling Battery Optimization for the app when possible). I would also like to note that for 2 of my 4 devices (Android 7 & Android 9 [Android TV on my NVIDIA Shield]) this manual setup is failing (as in it will no longer connect at all unless I turn on Compatibility Mode). The two devices it still works for are running Android 5.1 and 8.0. Not sure if that's related or not.

I apologize for not trying the unencrypted DNS yet, as upgrading and reinstalling is a bit of a pain. I can't wait to upgrade and not experience any issues with the settings I desire.

I hope this helps somehow!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ameshkov** [comment]
@Chinaski1 could you please setup AdGuard + AG VPN as explained here and see if we can reproduce this: https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/110#issue-955586434

We should triage this task asap as we're now trying to plan the next minor update.

**Comment by infinitewaveparticle** [comment]
@ameshkov Let me know if you need anything else from me... Like any settings descriptions or further tests or logs. I can see the relationship between this and the Kill Switch issue, especially if you integrated the changes you mentioned into the Nightly 25 release.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
However, please remember that this issue also occurs without AdGuard VPN running at all...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
Furthermore, I have never seen an app called "root" in the Filtering Log before trying version N 25 thru at least N 31.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
For what it's worth I see the AdGuard VPN app in the Filtering Log attempting a bunch of connections to IPs when it's working properly too... I figured this was to establish the ping times for each server. This issue is primarily with the "root" app in the Filtering Log whether the AdGuard VPN app in is connected or not.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ameshkov** [comment]
@infinitewaveparticle quick question - which app do you have configured in Android's kill switch? Is it AdGuard VPN or AdGuard? Should be AdGuard VPN.

**Comment by infinitewaveparticle** [comment]
@ameshkov Honestly, this issue occurs on the devices I've tried upgrading, but for the device I first reported it and uploaded screenshots for the system VPN settings aren't accessible (nvidia shield running stock Android 9 which I believe is also "Android TV"). In my list of VPNs on the device that allows me to do the full "Kill Switch" steps (Android 8), the only app there is AdGuard. And with 4.0 N 24 it works as intended. In fact, with the other devices set up manually via SOCKS5 (but not able to choose either or both "Always On" and "Block connections..." in system Settings), when AdGuard VPN becomes disconnected there are no internet connections allowed until I reconnect AdGuard VPN to a server (so in reality it works with or without access to VPN system settings as long as the SOCKS5 connection is maintained when AdGuard VPN disconnects). When in Compatibility Mode, however, when AdGuard VPN disconnects it simply disables the SOCKS5 connection and continues allowing internet connections and exposing my IP. No matter if I use AdGuard VPN or not, when I upgrade to N 25 thru at least N 31, I see "root" repeating the same connections over and over again in the Filtering Log, and no app is able to connect to the internet.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by sfionov** [comment]
Hello! Can you please remove port 53 from "pref.vpn.filtered.ports" advanced options and say if it helps? It seems to conflict with AdGuard's DNS filtering.

**Comment by infinitewaveparticle** [comment]
@Chinaski1
@ameshkov
@sfionov

I finally tried some things with the most recent Nightly 4.0 32:

First of all I wanted to clarify that the "udp://198.18.53.53:53" repeating over and over again in the Filtering Log is actually done by "DNS" and not "root". The attempts by the root "app" are all blocked and are of many different IPs. Also, interestingly, there is one app that does work: YouTube Vanced (but there are no DNS entries in the Filtering Log, only regular https and some blocked quic and gquic attempts). It's as if the app is simply bypassing DNS filtering entirely.

That being said here are the results and follow-up questions/concerns:

1. Changing the bootstrap DNS setting to an unencrypted DNS server had no effect.

2. Removing port 53 from the list of filtered ports allowed data for all apps (and DNS filtering for YouTube Vanced) to work again, BUT this is very concerning to me:

If we're not filtering port 53 couldn't any app just use its own unencrypted DNS connections to bypass DNS filtering? I've already seen some apps attempt this (first time I saw it was with the Netflix app, but since then many others have been doing it in an attempt to evade DNS filtering) so I block that connection from succeeding - especially ones to Google's unencrypted DNS. If those connections aren't filtered and and blocked, then choosing encrypted DNS and using DNS filtering are both on their way to being useless. This is not good.

Prior to 4.0 Nightly 25 this wasn't an issue at all - what did you change beginning with Nightly 25 that caused this to be a problem? I personally see this as the issue that needs fixed so please use this update from me to allow users to once again filter port 53. Not only should port 53 be filtered, but in my opinion all ports should be filtered by default to ensure that no internet traffic evades AdGuard or any of its techniques. The low-level setting should instead be for users to specify ports to NOT filter.

Please tell me you agree and that you will allow port 53 to be filtered again like it was prior to 4.0 Nightly 25.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ngorskikh** [comment]
@infinitewaveparticle 
Plain DNS traffic of all apps is always redirected to the local DNS proxy when DNS protection is enabled. 

Adding port 53 to `pref.filtered.ports` causes DNS traffic to be redirected to the "main" proxy (which does TLS, HTTP, etc.) instead, which doesn't know what to do with it, so it simply tries to forward it to the original destination. That's why you see records like `udp://198.18.53.53:53` in the filtering log. Only `198.18.53.53` is a made-up address in a reserved subnet. Hence DNS is not working.

In general, port 53 should not be added to that list. To protect users from such a mistake, we've given DNS-proxy redirection rules higher priority than HTTP-proxy redirection rules. The change should go live soon, or maybe it already is.

This issue did not become apparent until the nightly 25 because we weren't redirecting UDP traffic to the main proxy until then, and DNS uses UDP 99% of the time.

**Comment by infinitewaveparticle** [comment]
So you're saying that it's now impossible for an app to avoid DNS filtering? For example if an app tries connecting to 8.8.8.8:53 and then uses that to connect to example.com without example.com showing up as a DNS attempt? Prior to the change you explain several apps were doing this... So what I do is filter port 53 and port 443 and block all their attempts to connect directly to any port 53 addresses or 8.8.x.x addresses. An example of an app that does this is co.peeksoft.stocks (but they just connect to 1.1.1.1:443, 8.8.4.4:43, and 8.8.8.8:443 instead of port 53 like the Netflix app does).

My question is: will the 8.8.8.8:53 attempt by Netflix still be blocked? Or will it be redirected to my chosen DNS automatically via DNS filtering?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
Nikita, By plain DNS requests do you mean a request to Netflix.com or a request to 8.8.8.8:53 (made by the Netflix app in an attempt by Netflix to evade DNS filtering)?

I'm wondering why I was always able to block these requests (by filtering port 53 and then blocking all port 53 requests with *:53$network -- and if they'll still be blocked now that I've had to remove port 53 from the list of filtered ports.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
p.s. I am also currently able to block apps from attempting connections to doh servers (8.8.8.8:443 or alidns.com, for example).

Sent from ProtonMail mobile

-------- Original Message --------
