### ISSUE TITLE
Moscow subway Wi-Fi authorization issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#41]
Infinite redirect:
https://login.wi-fi.ru/am/UI/Login?org=mac&service=coa&client_mac=xx-xx-xx-xx-xx-xx&ForceAuth=true&redirect=https://login.wi-fi.ru/am/UI/Login

From the log:

```
13:08:38.310 [pool-3-thread-99] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=205 Processing GET request to http://www.google.com/trends/hottrends/atom/hourly?pn=p14
13:08:38.350 [pool-3-thread-99] DEBUG c.a.f.proxy.BaseHttpProxyServer - TCP id=205 HTTP/1.1 200 OK
Location: https://login.wi-fi.ru/am/UI/Login?org=mac&service=coa&client_mac=c0-bd-d1-c2-9c-27&ForceAuth=true
Content-Length: 351
Content-Type: text/html
13:08:38.352 [pool-3-thread-99] DEBUG c.a.f.filters.HttpResponseFilter - Filtering fixed length response of http://www.google.com/trends/hottrends/atom/hourly?pn=p14
13:08:38.353 [pool-3-thread-99] DEBUG c.a.f.filters.HttpResponseFilter - Response of http://www.google.com/trends/hottrends/atom/hourly?pn=p14 is definitely HTML, filtering it
13:08:38.354 [pool-3-thread-99] DEBUG c.a.f.filters.HttpResponseFilter - Using ContentEditingHtmlParser to parse the response
```

My idea: that page code filtering breaks authrozation.
We should disable html code filtering if Location header is present.

**Comment by ameshkov** [comment]
I was wrong, that's not the problem.

Another strange thing in the log file: I see that DNS requests go to 8.8.8.8. Why is it used in Moscow subway?

Logs:
https://www.dropbox.com/s/l6ofv5cg64pwbvp/adguard%20%282%29.log?dl=0
https://www.dropbox.com/s/k6trq2c2rns54w7/adguard%20%283%29.log?dl=0

**Comment by ameshkov** [comment]
Ticket ID: TGX-483-73779

**Comment by Revertron** [comment]
Fixed.

**Comment by ameshkov** [comment]
Are you sure? He still has this issue

**Comment by Revertron** [comment]
In ticket MIW-787-84428 user says that he is using UC Browser. But adblock extension in UC is blocking authorization. In system browser he is connecting without problem.

**Comment by ameshkov** [comment]
User still has this problem:
TGX-483-73779

**Comment by ameshkov** [comment]
@Revertron extend logging in buildVpnService method in the next beta.
Let's log all connection properties including DNS servers (like what's done in addIpv4Routes)

**Comment by ameshkov** [comment]
Waiting for user's answer in TGX-483-73779

**Comment by vmalyuta** [comment]
1529154
1214655
1529108
open again

**Comment by ameshkov** [comment]
I am quite sure we should file a report to AdguardFilters.

Also, I am sure we will need a recorded HAR file.
