### ISSUE TITLE
Test Adguard HTTPS filtering and Android N

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#410]
It seems that there are some issues with it:
http://forum.xda-developers.com/showpost.php?p=66112312&postcount=904

**Comment by ameshkov** [comment]
@gshumihin install it on Nexus 7

**Comment by gshumihin** [comment]
Android N is not avaliable yet for nexus 7 (2013). 
List devices andoid N avaliable for:
- Nexus 6, Nexus 9, Nexus 5X, Nexus 6P, Nexus Player
- Pixel С
- General Mobile 4G (Android One)

**Comment by gshumihin** [comment]
We also can try it in android-sdk

**Comment by gshumihin** [comment]
Finally, I tested Adguard 2.5 and android N. The only one issue for me is chrome. Seems like chorme build for android N doesn't work with personal certificates. Chrome beta or chrome dev works fine.

**Comment by gshumihin** [comment]
Youtube app won't get filtered.

**Comment by ameshkov** [comment]
@gshumihin we need a log for this. Also I think this should be a separate issue.

**Comment by ameshkov** [comment]
@gshumihin ?

**Comment by gshumihin** [comment]
Opened new #486 issue for that.

**Comment by ameshkov** [comment]
Moving it to v2.6, we'll re-test when new version of Android N arrive.

**Comment by gshumihin** [comment]
Looks like they'll push updates every month:
http://developer.android.com/intl/ru/preview/overview.html

**Comment by ameshkov** [comment]
Done
