### ISSUE TITLE
Github release versions not corresponding to APK versions

### ISSUE THREAD

**Issue by archon810** [AdguardTeam/AdguardForAndroid#4101]
Hi,

This has been a puzzling behavior to me for a while - why are Adguard release versions on Github and versions of actual APKs completely different?

For example, the latest release is 3.6.7 https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.6.7, yet the APK it links to is 3.6.41, and there's no mention of 3.6.41 in the release notes.

Similarly, 3.6.7 beta1 https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.6.7-beta-1 is actually 3.6.40.

This is all very confusing. Can the releases actually follow APK versions?

**Comment by Chinaski1** [comment]
Hello there!

Don't let that embarrass you :)

3.6.41 - technical version number
3.6.7 - official version number

**Comment by archon810** [comment]
@Chinaski1 Sure, I get that, but you can see how it may be confusing? Is it possible to at least include a mention of the technical release version in the release notes so that they are cross-referenced?
