### ISSUE TITLE
YouTube video uploading doesn't works when quic/gquic is being blocked by Adguard.

### ISSUE THREAD

**Issue by paleparanoid** [AdguardTeam/AdguardForAndroid#4106]
### Issue Details

- **AdGuard version:**
  -  v4.0 Nightly 32 (73) - but version doesn't matter here, Adguard block completely all quic/gquic connections on all versions.
- **Filtering mode:**
  -  Local VPN
- **Device:**
  - Redmi Note 9s
- **Operating system and version:**
  Android 10.
- **Root access:**
  - No.

### Expected Behavior

I wanted to upload video to YouTube via official YouTube app. Often I uploaded video via PC, but this time I have to use phone for it. It should just upload this video.

### Actual Behavior

But It haven't. The uploading stopped on Preparing. As you can see, Adguard only blocks some gquic connections. If you disable protection in Adguard, everything will upload fine.

### Screenshots

![Screenshot_2022-02-09-09-36-55-267_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/86261854/153135704-e1087046-a138-400f-9156-d6bc4fc33b86.jpg)![Screenshot_2022-02-09-09-37-01-893_com.adguard.android.jpg](https://user-images.githubusercontent.com/86261854/153135713-1c6cf85a-11c9-416b-ba3e-09ee065e3092.jpg)

### Additional Information

 You should stop blocking QUIC and GQUIC for YouTube app (also YouTube Vanced and other mods on it). It's unrealistically to unblock all (g)quic connections, every time addresses are different. 
I completely don't understand why you decided to block all QUIC and GQUIC connections. This is a very stupid decision.

**Comment by sfionov** [comment]
Adguard blocks fallbackable protocols that can't filter, to not to bypass ads and tracking. But IETF QUIC is not on this list - AG for Android should bypass it and filter by SNI. Looks like a bug, we'll look into it.

As a workaround you may add youtube to `com.google.android.youtube` into `pref.quic.bypass.packages` advanced setting.

**Comment by paleparanoid** [comment]
> Adguard blocks fallbackable protocols that can't filter, to not to bypass ads and tracking. But IETF QUIC is not on this list - AG for Android should bypass it and filter by SNI. Looks like a bug, we'll look into it.
> 
> As a workaround you may add `com.google.android.youtube` into `pref.quic.bypass.packages` advanced setting.

Thanks, i'll try

**Comment by TPS** [comment]
> But IETF QUIC is not on this list - AG for Android should bypass it and filter by SNI.

@sfionov You _do_ mean this that just started appearing since the last updates?
![Pngpro_out_48cd796552286db12739fa73667c8382.png](https://user-images.githubusercontent.com/185902/153714954-c7205521-7358-4e5a-a59c-754164e3d942.png)

**Comment by TPS** [comment]
You must be seeing different logs than me, since I'm only seeing AG's UI log.  But, based on that, that's _not_ the (official app) YT behavior I see.  Just like @paleparanoid's screenshot above, I see YT choosing between, not falling back to, `QUIC` & `gQUIC`.  I'm aware they're different & have separate issues dealing their decoding/filtering.  What progress is there on `gQUIC`?

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1596](https://github.com/AdguardTeam/CoreLibs/issues/1596) via [**ZenHub**](https://www.zenhub.com/)
