### ISSUE TITLE
Websites reloading continuously

### ISSUE THREAD

**Issue by kamharry** [AdguardTeam/AdguardForAndroid#4108]
Many of the sites are reloading continuously like reload loop and not able to explore the content with adguard turned on, after disabling adguard the problem is solved.
Please look into this.

**Comment by kamharry** [comment]
Stealth mode is off from the beginning because I don't like it as it causes issues in login with some apps and sites..
Browser - Google Chrome And Brave

**Comment by Chinaski1** [comment]
Please specify the number of the request to the helpdesk so I can find your log.
The request number should be emailed to you after the logs are sent.
Something like that: 573980

**Comment by kamharry** [comment]
578549

**Comment by Chinaski1** [comment]
Can you send me some examples of sites where the issue is reproduced?
I will check and move the task to the appropriate repository.

**Comment by kamharry** [comment]
https://newsupdate.uk/snapdragon-695-vs-680-vs-mediatek-dimensity-810-performance-comparison-best-under-rs-20k-91mobiles-com/amp/

https://sparrowsnews.com/2022/02/08/xiaomi-l1-mega-cup-flagship-exposure/amp/

**Comment by kamharry** [comment]
These are the 2 sites which i opened now and they are reloading in loop i guess the issue is the amp !

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/DisableAMP #65](https://github.com/AdguardTeam/DisableAMP/issues/65) via [**ZenHub**](https://www.zenhub.com/)
