### ISSUE TITLE
AdGuard Breaking "Desktop site" View in Chrome for Many Sites

### ISSUE THREAD

**Issue by richaardvark** [AdguardTeam/AdguardForAndroid#4109]
AdGuard breaks the "Desktop site" view option for many sites in Chrome for Android. Often when I try to switch from the mobile view of a website to the full desktop view in Chrome when the AdGuard VPN is activated it seems that AdGuard is breaking the change of the user agent and I still only see the mobile view of a site. I don't experience this with every site but with a number of major sites such as google.com and reddit.com. If I want to actually see the desktop version of a site I have to first disable AdGuard but then of course all of the ads return. This is majorly frustrating. 

- [X] I am running the latest version (4.0 nightly 32)
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- AdGuard version: 4.0 nightly 32
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 8 (IN2015)
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior

I want to be able to load the desktop view/version of websites while still using AdGuard.

### Actual Behavior

For some (not all) sites changing to the desktop view only reloads a smaller version of the mobile view.

### Screenshots

![pixomatic_1122022153838905](https://user-images.githubusercontent.com/41244847/153729306-4e50615d-dd8b-4194-b37d-1c6de936755f.png)

### Additional Information

This doesn't happen for all websites but for a number of websites/major websites (Google.com, Reddit.com, others).

**Comment by Chinaski1** [comment]
Hello!

I just try to reproduce the specified issue but doesn't account for any difficulties with page type changing.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced, also, please don't forget to specify the Chrome version number.

**Comment by Chinaski1** [comment]
Any news?

**Comment by Chinaski1** [comment]
Closed due not reply.

**Comment by richaardvark** [comment]
Hi again,

I apologize for my delayed response. I was in hospital and unable to follow
up for a moment but I'm home now and am still experiencing this issue. I've
just sent the logs per your instructions above via email.

I am now experiencing a separate, new issue that I don't believe to be
related so I will open a separate ticket for this.

Thank you again for your help and I'm sorry it took me so long to get back
to you!

Richard

**Comment by Chinaski1** [comment]
@richaardvark 

While we look at the logs you sent me, I would like to ask you to describe second issue in more detail

**Comment by Chinaski1** [comment]
According to the log you are using `Stealth-mode`, and custom `user agent`.
This seems to be the setting that causes the described behavior.

Try disabling this setting and see if the issue reproduced.

**Comment by richaardvark** [comment]
Hello again :)  Disabling Stealth Mode from the AdGuard settings menu has
resolved the problem. 👍🏻🙂 I'm not certain how I enabled Stealth Mode in
the first place but now I know for the future that it will cause problems
with viewing mobile versions of websites and will keep it disabled. Thank
you so very much for your help!

**Comment by Chinaski1** [comment]
Glad to hear that issue is solved :)
