### ISSUE TITLE
DNS-фильтр

### ISSUE THREAD

**Issue by GdeZsqyAY** [AdguardTeam/AdguardForAndroid#4110]
Это один и тот же фильтр

![Screenshot_20220215_141414_com adguard android](https://user-images.githubusercontent.com/58640411/154053641-68fb1de8-050a-4c86-8eee-8d97826a8869.jpg)

Может стоит сделать одинаковое название, а не для каждого раздела свое?

**Comment by Chinaski1** [comment]
Нет, не думаю.

**Comment by GdeZsqyAY** [comment]
@Chinaski1 

> Нет, не думаю.

Значит Вы считаете, что это два разных фильтра?
