### ISSUE TITLE
Does not block in-app ads - Android 12 / Magisk ROOT

### ISSUE THREAD

**Issue by Camis** [AdguardTeam/AdguardForAndroid#4114]
### Issue Details

- **AdGuard version:**
  - 3.6.7
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Xiaomi Redmi Note 8T
- **Operating system and version:**
  - Android 12 (Custom ROM - ArrowOS)
- **Root access:**
  - Yes - Magisk 24.1

### Actual Behavior

Does not block in-app ads

### Screenshots

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/949667/154992456-3456a48e-7caf-4c45-b972-6b9824b742bf.png)
![2](https://user-images.githubusercontent.com/949667/154992464-b2f820a8-54b9-4a11-95e9-be234af1c858.png)
![3](https://user-images.githubusercontent.com/949667/154992467-c81d56bb-8e10-4d0e-babc-7f5e6d300635.png)
![4](https://user-images.githubusercontent.com/949667/154992470-3f451bb6-23f4-43cf-89c2-09af4c62fc05.png)
![5](https://user-images.githubusercontent.com/949667/154992473-4f40441b-3738-4004-beab-d4ba4811c48a.png)
![Screenshot_20220221-172027_AdGuard](https://user-images.githubusercontent.com/949667/154993231-bac87133-abf0-4e4c-a3a3-6c7b7e4d3b76.png)
![6](https://user-images.githubusercontent.com/949667/154992476-a8bf3b4a-d2d9-4491-be25-e0b0e73cb6c0.png)
![7](https://user-images.githubusercontent.com/949667/154992482-a7e5c012-0411-414f-ac98-ed0b822b8577.png)

</details>

### Additional Information

Logs sent to devteam

<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System configuration</h3>

Information | value
-- | --
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | Ad Blocking:EasyList,AdGuard Mobile Ads,AdGuard BasePrivacy:AdGuard Tracking ProtectionSocial Widgets:AdGuard Social MediaAnnoyances:Fanboy's Annoyances,AdGuard Annoyances,EasyList Cookie List,Adblock Warning Removal List,I don't care about cookiesSecurity:Online Malicious URL Blocklist,NoCoin Filter ListLanguage-specific:EasyList Polish,AlleBlock,Polish Annoyances Filters,Polish Social Filters,Polish Anti-Annoying Special Supplement,KAD - Anti-Scam,Polish Anti Adblock Filters,Official Polish filters for AdBlock, uBlock Origin & AdGuard,Polish GDPR-Cookies Filters
Userscripts: | disabled

</body>
</html>

**Comment by Chinaski1** [comment]
Hello!

For a clean experiment, I recommend you disable third-party filters. Leave only AdGuard filters (they are marked with an asterisk). Check if the issue with ads will recur in this configuration?

**Comment by Camis** [comment]
Yes, ads are still there.

![1](https://user-images.githubusercontent.com/949667/155112069-505342ee-6125-489a-b5d6-dd6c9cf1c3fe.png)
![2](https://user-images.githubusercontent.com/949667/155112072-ecd51da9-f8e7-4bf8-8b0e-28c6cea46b0f.png)
![Screenshot_20220222-111807_AdGuard](https://user-images.githubusercontent.com/949667/155112277-3ede6975-ab43-4f08-883f-36f76a3c4df0.png)

![4](https://user-images.githubusercontent.com/949667/155112074-843ee7fb-057b-48fb-af45-e61e75fffd4d.png)

**Comment by Camis** [comment]
Updated, issue still persists.



![tytgn7w](https://user-images.githubusercontent.com/949667/160803676-4a6c56f9-c095-406d-ba95-0f7261a02523.png)

![Screenshot_20220330-114700_AdGuard](https://user-images.githubusercontent.com/949667/160803754-58b626ef-e632-43de-a93a-887a98bc55df.png)

![Screenshot_20220330-114724_WatchLine Lodz](https://user-images.githubusercontent.com/949667/160803809-7874461d-ffd5-479f-9719-70191798c59f.png)

![Screenshot_20220330-114731_AdGuard](https://user-images.githubusercontent.com/949667/160803914-3e735542-8588-4b4a-85eb-2428ab40650c.png)

**Comment by Chinaski1** [comment]
Looks like the issue is related to this [task](https://github.com/AdguardTeam/AdguardForAndroid/issues/4153), please try to use the instructions that were suggested by @sfionov

**Comment by Camis** [comment]
I used this new module "adguardcert", now everything is working. 

Thanks.
