### ISSUE TITLE
Adguard blocks UDP connection on port 443

### ISSUE THREAD

**Issue by liushilive** [AdguardTeam/AdguardForAndroid#4116]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.7(41)
- **Filtering mode:**
  - VPN
- **Device:**
  - vivo iqoo3
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior

Adguard allow UDP connection on port 443
### Actual Behavior

Adguard blocks UDP connection on port 443

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20220223_150016](https://user-images.githubusercontent.com/13434707/155274078-c7660d5c-e4b3-438f-8de1-8d9b89f7a119.jpg)

</details>

**Comment by Chinaski1** [comment]
Hello there!
 
Initially, it looks like a blocked QUIC request.
Because the request was from an unknown package it was not marked that way.

Please specify on the screenshot the blocked request in the browser or in the application?

**Comment by liushilive** [comment]
Any UDP request through port 443 will be blocked

**Comment by sfionov** [comment]
@liushilive Do you have HTTPS filtering enabled for this app? Adguard can't MITM QUIC by now, so it is blocked when HTTPS filtering is enabled.

**Comment by Chinaski1** [comment]
@liushilive 

Any news?

**Comment by Chinaski1** [comment]
Closed due not reply.

Reopen the task if the issue still reproduced.

**Comment by Karmylr** [comment]
> @liushilive Do you have HTTPS filtering enabled for this app? Adguard can't MITM QUIC by now, so it is blocked when HTTPS filtering is enabled.

Is it possible to MitM QUIC?
