### ISSUE TITLE
AdGuard не фильтрует https через прокси

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#4123]
AdGuard (v3.6.7 (41)) не фильтрует трафик с хрома (87.0.4280.101) на MIUI 12.0.10, что на базе 10-го андроида по https даже при наличии установленного сертификата. Прокси задан через ключ --proxy-server="127.0.0.1:8080" в /data/local/tmp/chrome-command-line с активацией флага #enable-command-line-on-non-rooted-devices. http-сайты фильтруются. https-нет. В инфо сайтов видно их исходные сертификаты, а не сертификат AdGuard. В логе AdGuard'a видны туннелированные https-запросы, т.е. https трафик таки идёт через прокси, но не фильтруется. При всём при этом при активации локального VPN'a https фильтруется на ура. WTF ? Мне не нужна (по ряду причин) фильтрация всей системы через локальный VPN. Мне нужно фильтровать лишь конкретный браузер через прокси, но по непонятным причинам я вместо этого ловлю обломинго :(

**Comment by Baltazar500** [comment]
А вот и ответ, где собака порылась :

<details>

![2022 03 08_22 49 58](https://user-images.githubusercontent.com/12525093/157242590-59b5f937-b6db-45fc-a853-744e98b329ed.jpg)

![2022 03 08_22 49 24](https://user-images.githubusercontent.com/12525093/157242618-ac53d9ef-dec7-493d-a86e-dcd9ea3724d4.jpg)

</details>

AdGuard не воспринимает запросы от хрома через прокси, как запросы от хрома, а воспринимает их как запросы от ОС и без премиума отказывается фильтровать. На 5.1 запросы через прокси того же билда спокойно детектятся как хромовские и фильтруются. Ну и что с этим делать ?

**Comment by ngorskikh** [comment]
К сожалению, начиная с Android 10 без рута определить приложение, установившее соединение, может только VPN-сервис:
https://developer.android.com/about/versions/10/privacy/changes#proc-net-filesystem
https://developer.android.com/reference/android/net/ConnectivityManager#getConnectionOwnerUid(int,%20java.net.InetSocketAddress,%20java.net.InetSocketAddress) (раздел `Throws`)

Следовательно, в прокси-режиме без рута определение приложений не работает.

**Comment by Baltazar500** [comment]
@ngorskikh, другими словами, на 10-м андроиде без рута и без премиума при попытке использовать прокси - фильтрацию для https через плагины браузеров или иными методами (см. command-line), дабы не пропускать весь трафик через adguard, я и остальные пользователи, что попытаются так сделать "ловят обломинго" образно выражаясь ? Т.е. либо VPN, либо премиум ? Я правильно понимаю :/ ?

**Comment by Chinaski1** [comment]
@Baltazar500 

Да, получается так.
