### ISSUE TITLE
Replace the "Move certificate" with "AdGuard certificate" as a recommended Magisk module

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4126]
Check the problem description:
https://github.com/AdguardTeam/AdguardForAndroid/issues/4124

**edit**:
It seems that copying the certificate helped at least one user. If it does help, we should update the way we install the cert instead: https://github.com/AdguardTeam/AdguardForAndroid/issues/4124#issuecomment-1066031549 **Please read all comments there**.

If it does help, instead of warning the users we'll need to do the following:
1. Fork the magisk module that moves the certificate.
2. Change our method to copy the cert instead of moving it.
3. Change the "detection" procedure in AdGuard to reflect that the "system cert" state is when the cert is installed in both storages.

**edit 2**: this comment is important: https://github.com/AdguardTeam/AdguardForAndroid/issues/4124#issuecomment-1066181126

**Comment by LU-LEI** [comment]
In addition to changing the browser, is there a solution? Copying the certificate and using the zygisk function in magisk can really be used, But having to use magisk, it is really annoying.Is it possible to solve this problem in the future, or launch a browser that can synchronize chrome bookmarks?

**Comment by ameshkov** [comment]
@LU-LEI it seems the only viable option left is to use Magisk + copy the certificate.

We'll provide our own "AdGuard Certificate" module that will do the necessary steps.

**Comment by wefalltomorrow** [comment]
> @LU-LEI it seems the only viable option left is to use Magisk + copy the certificate.
> 
> We'll provide our own "AdGuard Certificate" module that will do the necessary steps.

Awesome! Is there a rough ETA on the module?

**Comment by sfionov** [comment]
@wefalltomorrow Hello! 

You may already try it: https://github.com/AdguardTeam/adguardcert 

Now it has exclusion list with Chrome packages hardcoded. This may be reviewed in the future.

You may also remove Zygisk module from prebuilt zip and customize exclusions by yourself in the Magisk settings.

**Comment by nekato** [comment]
It doesn't work for me. Chrome still shows ads, even though there is now notification about user store certificate.

**Comment by wefalltomorrow** [comment]
> For me it works in Chrome, however a few system apps that worked perfectly when the certificate was only in the system store (most notably, Google Play Services) now spams several "HTTPS filtering error: this app doesn't accept AdGuard's certificate" push notifications.

Did v1.1 fix this issue for you? https://github.com/AdguardTeam/adguardcert/releases/tag/v1.1

**Comment by mbc07** [comment]
Nope. Google Play Services still produces several HTTPS filtering errors after installing v1.1 of the module. Chrome works, though...

**Comment by ameshkov** [comment]
Google Play Services may be using certificate pinning and nothing will help with that.

Check the filtering log in AdGuard and see if HTTPS filtering is applied to non-browser apps.
If you see "HTTPS Tunnel" events, it means it was not applied. If you see "Web request" it works as intended.

**Comment by wefalltomorrow** [comment]
The module flat out doesn't work for me with Bromite, sadly. I have Zygisk enabled and installed the user cert first before installing the module. Still can't load pages with HTTPS Filtering enabled for Bromite, so I have to disable it to use the browser.

**Comment by mbc07** [comment]
> Google Play Services may be using certificate pinning and nothing will help with that.

It isn't. When the certificate is on the system store (without using the Magisk module), none of the HTTPS filtering errors happen. They immediately start happening once the module is installed, though...

**Comment by ameshkov** [comment]
Note that one more step is required for Bromite: https://github.com/AdguardTeam/AdguardForAndroid/issues/4124#issuecomment-1082700837

We may need to update the repo README to explain that.

**Comment by wefalltomorrow** [comment]
> Note that one more step is required for Bromite: [#4124 (comment)](https://github.com/AdguardTeam/AdguardForAndroid/issues/4124#issuecomment-1082700837)
> 
> We may need to update the repo README to explain that.

Thanks! That fixed it :)

**Comment by sfionov** [comment]
@mbc07 Can you please give more info about your configuration? What is your device name and Android version?

**Comment by wefalltomorrow** [comment]
> Nope. Google Play Services still produces several HTTPS filtering errors after installing v1.1 of the module. Chrome works, though...

Can confirm a similar issue, basically every app is spamming filtering errors which I hadn't encountered before with AdGuard in the system store. 

![image](https://user-images.githubusercontent.com/45746576/162162986-3bec5986-0c79-4adf-abfd-4b5ff5bdf484.png)
![image](https://user-images.githubusercontent.com/45746576/162163005-3e65db5c-bed7-4b88-b9f7-7793743b47ba.png)

**Comment by ngorskikh** [comment]
@wefalltomorrow @mbc07 Could you try the latest version? https://github.com/AdguardTeam/adguardcert/releases/latest
We've included some workarounds that we implemented in the android app a while back.

Regarding forging CT logs: highly unlikely that that's going to work. The whole point of CT is that the CT log should come from a well-known, trusted, and audited source. Otherwise, the issuers of fraudulent certificates could just as well issue fraudulent CT logs and the whole system would be pointless.

**Comment by anuraag488** [comment]
![IMG_20220411_205839](https://user-images.githubusercontent.com/7353086/162774620-6175fc1d-c9b5-425e-a9fb-6277c3dc7a2f.jpg)
@ngorskikh using 1.2

**Comment by mbc07** [comment]
Tested module v1.2 and no changes, Google Play Services still spams a lot of HTTPS Filtering Errors that doesn't happen when the AdGuard Certificate is only in the system store. Chrome works, though, no certificate transparency issues...

**Comment by ameshkov** [comment]
@mbc07 

Have you rebooted the device after updating the module?

@ngorskikh can we maybe add a little bit more logging to the module? Troubleshooting it now is quite problematic.

**Comment by mbc07** [comment]
> Have you rebooted the device after updating the module?

Yes. The issue isn't the module, rather Google Play Services not playing well when the certificate is present on both system and user stores...

**Comment by ameshkov** [comment]
Ah, that's possible indeed. Might be certificate pinning for some domains.

**Comment by mbc07** [comment]
I don't think certificate pinning is the issue, otherwise the HTTPS filtering errors that happen with Google Play Services when using the module would also occur when the AdGuard certificate is only on the system store, which isn't the case...

**Comment by ngorskikh** [comment]
@mbc07 We've released [version 1.3](https://github.com/AdguardTeam/adguardcert/releases/tag/v1.3) with one more small change. Could you please test if it will help?

**Comment by mbc07** [comment]
Tested v1.3 and unfortunately nothing changed, Chrome works but Play Services still spams HTTPS filtering errors...

**Comment by mbc07** [comment]
I've took a look at the "cacerts-removed" folder after installing the module and rebooting and it's always empty (even when using older module versions like v1.0 and v1.1), so the fixes done in v1.2 and v1.3 doesn't seem applicable on my phone?

**Comment by anuraag488** [comment]
Can't we have optional zygisk module to unpin ssl certificate validation so that adguard can filter all https traffic?

**Comment by ameshkov** [comment]
Are there any examples?

**Comment by anuraag488** [comment]
There is a [xposed module](https://modules.lsposed.org/module/io.github.tehcneko.sslunpinning/) which isn't maintained anymore but it works for most apps. On running apktool here is [source code](https://pastebin.com/E55HVfAg).

There is [another script](https://github.com/httptoolkit/frida-android-unpinning/blob/main/frida-script.js)  available not tested through.

**Comment by sfionov** [comment]
I think that providing cert unpinning as part of the product may cause legal issues. User may use third-party modules on their own risk.

**Comment by sfionov** [comment]
I think that providing cert unpinning as part of the product may cause legal issues. User may use third-party modules on their own risk.

**Comment by aliafshany** [comment]
hi
do i need to remove Move cert Module from magisk in order to install AdGuard Certificate?

**Comment by ameshkov** [comment]
@aliafshany yes, you do.

**Comment by aliafshany** [comment]
> 

yea i did that and it works great now.

best
