### ISSUE TITLE
data.videonow.ru cannot be blocked by URL blocking rule

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4128]
@adguard-bot commented on [Sun Mar 13 2022](https://github.com/AdguardTeam/AdguardFilters/issues/112783)

### Issue URL (Ads)
 [https://www.playground.ru/elder_scrolls_5_skyrim/news/babushka_skyrim_poluchila_novyj_podarok_ot_bethesda-1186030](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.playground.ru%2Felder_scrolls_5_skyrim%2Fnews%2Fbabushka_skyrim_poluchila_novyj_podarok_ot_bethesda-1186030)
### Comment
Username: @Spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dNerXeL.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 7.0
AdGuard product: | AdGuard for Android v3.6.7 (41)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | disabled

**Comment by Spok1** [comment]
@Alex-302, вопрос решается?

**Comment by Alex-302** [comment]
@Spok1 Не знаю. Но запроса сейчас на той странице не вижу.

**Comment by Coolhabit** [comment]
@Spok1 Добрый день! Подскажите пожалуйста, повторяется ли проблема?

**Comment by Spok1** [comment]
Не наблюдаю!
