### ISSUE TITLE
network loop with ClashForMagisk

### ISSUE THREAD

**Issue by CECoffee** [AdguardTeam/AdguardForAndroid#4129]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [√ ] I am running the latest version
- [ √] I checked the documentation and found no answer
- [√ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.7(41)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 8
- **Operating system and version:**
  - Android 11
- **Root access:**
  - Yes

### Expected Behavior

Bypass the uid 0 to avoid loopback with ClashForMagisk.

### Actual Behavior

I noticed the pref.excluded.packages you provided in the low-level settings in advanced settings. I tried to use it to exclude the executable file of a magisk module Clash_For_Magisk and its uid is 0. I added it, but it seems that adguard has not spared it. What I hope to do is that adguard VPN-->clash-->network. However, it did not bypass it, which caused the loopback of the network. I look forward to your reply. Thank you!

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20220318-111146](https://user-images.githubusercontent.com/40519811/158930551-67c7cea1-5948-4080-b2f5-0595ddad06e0.jpg)
![Screenshot_20220318-111230](https://user-images.githubusercontent.com/40519811/158930582-036abb17-3f88-4214-af27-68e820b73e41.jpg)

</details>

**Comment by Dimerbone** [comment]
i dont have spare time right now. I'll send the logs later

**Comment by Dimerbone** [comment]
I've sent the logs long ago. Haven't your team received it?

**Comment by Chinaski1** [comment]
Yes, thx for the info

**Comment by Dimerbone** [comment]
btw, i noticed that it doesn't loop with HTTP filtering mode, but CFM shows all the incoming connections are IPs instead of domain names. I've set the DNS server to CFM in ADG as it should be.

**Comment by sfionov** [comment]
@Dimerbone

Can you please try to add `root` to pref.excluded.packages?

**Comment by Dimerbone** [comment]
<details><summary>Like this?</summary>

![Screenshot_20220403-192848](https://user-images.githubusercontent.com/40519811/161425799-c705be62-c533-404b-91d4-292db47977ba.jpg)

</details>
It doesnt work either
> @Dimerbone
> 
> Can you please try to add `root` to pref.excluded.packages?

**Comment by reeceyng** [comment]
> Like this?
> It doesnt work either...

Is there any solution now?
