### ISSUE TITLE
Adguard conflicts with Windscribe

### ISSUE THREAD

**Issue by FireFlashie** [AdguardTeam/AdguardForAndroid#4130]
### Issue Details

- **AdGuard version:**
  - 3.6.7
  - 4.0 nightly 32
- **Filtering mode:**
  - HTTP Proxy (Auto)
  - HTTP Proxy (Manual)
- **Device:**
  - Xiaomi Mi 9T (davinci)
  - Pixel 6 Pro (raven)
- **Operating system and version:**
  - MIUI 12/Android 11
  - ArrowOS/Android 12
  - Android 12 (on pixel 6)
  - Android 12.1 (on pixel 6)
- **Root access:**
  - Yes

### Expected Behavior

Adguard in HTTP-proxy mode will work correctly with any VPN-applications on the Android system if you have root.
### Actual Behavior

If Adguard is active and the HTTP-proxy filtering mode is used (manual or automatic, any port number), Windscribe cannot establish a connection to servers using the wireguard protocol. However, if you disable Adguard, connect to a Windscribe server and then re-enable Adguard, the existing connection will not be broken and both applications will work as expected. Also, if you use the IKEv2 protocol to connect, the connection will be successful even with filtering enabled.

### Additional Information

This issue can also be reproduced on a free Windscribe account, which should be enough for Adguard developers to confirm the problem.

**Comment by FireFlashie** [comment]
By the way, I tried to disable Windscribe filtering in the Adguard firewall settings, but it didn't seem to make any difference.

**Comment by FireFlashie** [comment]
And no, this is not aggressive advertising of Windscribe for Adguard employees :rofl:

**Comment by Chinaski1** [comment]
Hello there!

Sorry for the late reply.
Please enable AdGuard in HTTP auto-proxy mode and collect the log files 

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by ameshkov** [comment]
@sfionov could it be an issue with proxying UDP?

**Comment by ameshkov** [comment]
@FireFlashie quick question: have you disabled filtering of the Windscribe app in the Apps Management settings?

**Comment by ameshkov** [comment]
@FireFlashie note that in the root+proxy mode we forcibly block all UDP traffic to port 443.

Could it be that Windscribe tries to use that port?

**Comment by ameshkov** [comment]
Tbh, I have no idea at this point, if AdGuard protection is enabled, AG shouldn't mess with it at all.

Just in case, please do `adb shell` to your device and show us the output of `iptables-save` so that we could check what exact iptables rules are applied.

**Comment by FireFlashie** [comment]
So, after further tests, it became clear that the first attempt to connect with Windscribe is always on port 443. Which, as mentioned above, is blocked by Adguard for some reason. If Windscribe manages to establish the first connection to the servers before the AdGuard local proxy starts, then Windscribe works later on without any problems.

**Comment by ameshkov** [comment]
The reason for this behaviour in proxy mode is that AdGuard wants to prevent QUIC traffic which it cannot filter at this moment. I am not entirely sure we'll ever be able to do that in proxy mode (in VPN mode we will, though). So the only option is fully prevent UDP to port 443.

**Comment by maxikuzmin** [comment]
@FireFlashie ping
