### ISSUE TITLE
Orbot doesn't work separately with Automatic proxy mode

### ISSUE THREAD

**Issue by RaXorX** [AdguardTeam/AdguardForAndroid#4132]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

While Adguard runs in Auto HTTP proxy (root) mode, Orbot doesn't work side by side with it. When AG runs in root mode, any other VPN should work alongside with it since Android's one VPN limitation doesn't apply in this case.

I want to use Orbot this way as adguard lacks the per app proxy solution at the moment, and I can easily specify which apps tor should filter within Orbot.

- **AdGuard version:**
  - v4.0 nightly 32 (73)
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - Xiaomi Mi 11x
- **Operating system and version:**
  - Android 11
- **Root access:**
  - Yes

### Expected Behavior

If Orbot is running in VPN mode then the specified apps should be filtered through it. If it is running in normal (not in vpn) mode then all traffic should be filtered through Tor as well as Aguard.

### Actual Behavior

No traffic is filtered through Orbot at all, regardless if it is in vpn mode or not.. https://check.torproject.org/ shows "Sorry, you're not using Tor." As soon as I stop Adguard, it sees tor and tells me that I'm on the Tor network but not using a tor browser.

**Comment by artemiv4nov** [comment]
Hello! Please follow the AdGuard 4.0 release, we changed the Automatic proxy mode, maybe it helps to you.
