### ISSUE TITLE
#include syntax does not work in filters added for dns filtering 

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [AdguardTeam/AdguardForAndroid#4134]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.7
- **Filtering mode:**
  -  local vpn
- **Device:** android
  - 
- **Operating system and version:**
  -  10 11 12
- **Root access:**
  - no

### Expected Behavior
Filters with #include statements should be available for dns filtering.

### Actual Behavior
#include syntax does not work in filters added for dns filtering 

### Screenshots
https://github.com/List-KR/List-KR/issues/259#issue-1178286304

<details><summary>Screenshot:</summary>
https://user-images.githubusercontent.com/34261355/159735777-ca112afd-f483-4659-944d-2cb07752ddb1.jpg

</details>

### Additional Information
https://github.com/List-KR/List-KR/issues/259

**Comment by Chinaski1** [comment]
This syntax does not seem to be supported by AdGuard DNS.

For more information about domain blocking with DNS, please refer to our [knowledge base.](https://kb.adguard.com/en/general/dns-filtering-syntax)

**Comment by 88Va2wFDcYd1CT** [comment]
> This syntax does not seem to be supported by AdGuard DNS.
> 
> For more information about domain blocking with DNS, please refer to our [knowledge base.](https://kb.adguard.com/en/general/dns-filtering-syntax)

@Chinaski1 
But in adguard windows it works.
It doesn't work on Android.
Is this the intended behavior?
https://github.com/List-KR/List-KR/issues/259#issuecomment-1076500170

**Comment by Chinaski1** [comment]
Could you please send me a link to the filter so I can check if it will operate in the Android app?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/4134#issuecomment-1086042400

```
https://github.com/List-KR/List-KR/raw/master/filter_DNS.txt
```

**Comment by Chinaski1** [comment]
This syntax is supported by the basic filters, but not by the DNS filters.

**Comment by piquark6046** [comment]
@Chinaski1 
Then, Is a bug that AdGuard for Windows can download entire content of List-KR of AdGuard for Windows?

<details>
<summary>Screenshot</summary>

![Screenshot from 2022-04-12 12-25-27](https://user-images.githubusercontent.com/98787049/162962049-5be60556-92b3-4f33-bfb2-77494119340e.png)

</details>
