### ISSUE TITLE
trovo.live app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4138]
@adguard-bot commented on [Mon Apr 11 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115236)

### Issue URL (Incorrect Blocking)
 [http://trovo.live](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Ftrovo.live)
### Comment
Username: `@iAndyPC`
> При включенном AdGuard приложение везде показывает эту ошибку 13, даже не войти в аккаунт, и восстановить пароль нельзя, пишет что отправил код восстановления на почту, а его нигде нет. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/L1XQlvR.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/LnigWLf.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 12
AdGuard product: | AdGuard for Android v3.6.7 (41)
Browser: | Firefox Mobile
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing third-party cookies (0)
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | Ничего такого нет

---

@Alex-302 commented on [Mon Apr 11 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115236#issuecomment-1094998599)

@iAndyPC Вроде работает нормально. Проблема с сайтом или их приложением?

---

@iAndyPC commented on [Mon Apr 11 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115236#issuecomment-1095002996)

> @iAndyPC Вроде работает нормально. Проблема с сайтом или их приложением?

Именно приложение на андроид

---

@Alex-302 commented on [Mon Apr 11 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115236#issuecomment-1095010215)

У меня всё работает. Можете проверить без фильтрации DNS и антитрекинга? Чтобы локализовать проблему.
Не включали ли самостоятельно фильтрацию HTTPS для этого приложения?(не общая, которая в главном меню)

---

@iAndyPC commented on [Mon Apr 11 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115236#issuecomment-1095145240)

> У меня всё работает. Можете проверить без фильтрации DNS и антитрекинга? Чтобы локализовать проблему.
> Не включали ли самостоятельно фильтрацию HTTPS для этого приложения?(не общая, которая в главном меню)

Отключил это все, перезагрузил телефон и тоже самое. А по второму вопросу я ничего кастомного не включал

**Comment by Chinaski1** [comment]
Подтверждаю, проблема повторяется при включенной защите даже с отключенными модулями Антибаннер и DNS фильтрацией.

Логи прикреплены к задаче (Время в логах 15:12-15:13).

В качестве временного решения вы можете исключить приложение из фильтрации.
Для этого откройте настройки AdGuard -> Расширенные -> Низкоуровневые -> Добавьте записать `com.tlive.madcat` в `pref.excluded.packages`.
