### ISSUE TITLE
Add banking apps to https exceptions list

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#414]
SE.NORDEA.MOBILEBANK
SE.BANKGIROT.SWISH
COM.BANKID.BUS

**Comment by Revertron** [comment]
Done.

**Comment by ameshkov** [comment]
Or maybe better to net exclusions?

**Comment by Bohdan-SUP** [comment]
Please add this one as well:
com.htsu.hsbcpersonalbanking

**Comment by Revertron** [comment]
Moved first pack to net_exclusions, added 2 other also.

**Comment by evgeniy-ADG** [comment]
Please can you add the banking domain sparkasse.at to your official HTTPS-whitelist?
LNJ-486-81500

**Comment by ameshkov** [comment]
@evgeniy-ADG it would be better to open a separate issue for this.
