### ISSUE TITLE
Разрешение имен через прокси (name resolution through proxy)

### ISSUE THREAD

**Issue by Tester17** [AdguardTeam/AdguardForAndroid#4143]
### Problem Description

При использовании прокси в Adguard, на прокси-сервер всегда приходят ip, а не имена хостов.
Пример:
`1650028477.750 SOCK5.3128 00000 user 1.2.3.4:47207 31.13.72.8:443 0 0 0 CONNECT_31.13.72.8:443`
Вместо
`1042454727.0296 SOCK5.3128 00000 user 1.2.3.4:47207 31.13.72.8:443 505 18735 1 GET http://example.com/ HTTP/1.1`
Имена хостов часто нужны для дальнейшего перенаправления трафика (в случае использования собственного прокси). Поэтому прошу добавить функцию разрешения имен через прокси.

### Proposed Solution

Добавить возможность разрешения имен через прокси

**Comment by sfionov** [comment]
Такая задача (поддержка socks5h) уже заведена, но на ближайшие релизы не запланирована.

Оригинальная задача https://github.com/AdguardTeam/AdguardForAndroid/issues/1346
Задача в CoreLibs https://github.com/AdguardTeam/CoreLibs/issues/1386
