### ISSUE TITLE
Google One Backup Fails

### ISSUE THREAD

**Issue by HoochieMamma72** [AdguardTeam/AdguardForAndroid#4146]
Hello 

I believe there is some issue with the Google Play Services component of Android when you try and manually backup a phone

If I disable AdGuard, it works fine works fine. If it's enabled it comes up with the below and not much information is showing in the logs of AdGuard. Nothing immediately showing blocked and google in the name

Problem is, in AdGuard for the Google Play Services it states "This package can be used by third party apps to load Google ads. Disabling ad blocking or filtering may result in unblocking some of the in-app ads" 

Is the Google One Backup function embedded too deeply in the Google Play Services and should I just disable filtering for this app or is this a bug? 

![Screenshot_20220420-110002](https://user-images.githubusercontent.com/61075600/164126628-f0c090ae-a5d3-45bd-96c3-72ca0c1db720.png)

**Comment by Chinaski1** [comment]
Hello there!

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send log files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@HoochieMamma72  please clarify, did you send the logs?

**Comment by maxikuzmin** [comment]
@HoochieMamma72 ping

**Comment by HoochieMamma72** [comment]
Hello

Yes, I sent the logs. It was on the 26th of April.

Thanks

**Comment by maxikuzmin** [comment]
@HoochieMamma72 sorry for the wait. Try to see which requests are blocked by AdGuard during a google services backup, and allow them with a custom rule

**Comment by HoochieMamma72** [comment]
I just disabled it completely on the Google Play services. Not the best way as this should be allowed by the adguard app as it's a important system function.

**Comment by maxikuzmin** [comment]
@HoochieMamma72 have you looked at which requests are blocked? have you allowed these requests?

**Comment by maxikuzmin** [comment]
@HoochieMamma72 ping

**Comment by HoochieMamma72** [comment]
Hello, yes. I sent it to the devteam email 4 data ago.

Thanks

**Comment by TPS** [comment]
Now #5617?
