### ISSUE TITLE
Network Layer 3 Isolation, UDP Port 53 Filter, Multicast Block

### ISSUE THREAD

**Issue by OpenSourceGhost** [AdguardTeam/AdguardForAndroid#4147]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

AdGuard for Android still doesn't have a feature to isolate clients on any network and/or block Multicast (UPnP, SSDP, etc).  

### Proposed Solution

Provide a way to isolate AdGuard for Android clients on Layer 3 of OSI, ability to block Multicast, and prevent discovery by other clients. Most VPN apps offer that.

### Additional Information

AdGuard for Android also does not filter UDP Port 53 by default. Forcing it to filter UDP Port 53 results in blocked cellular data connection. I am not sure why that is. Clients are supposed to be able to specify their own DNS, fully bypassing cellular data router.

**Comment by sfionov** [comment]
Hello!

UDP port 53 should not be added to filtered ports in advanced settings - DNS will be broken. 
Instead, for this purpose, use DNS filtering functionality in Adguard for Android app.

Blocking multicast traffic may technically be implemented. However, at this moment multicast is excluded unconditionally to not to break things.

**Comment by sfionov** [comment]
Hello!

UDP port 53 should not be added to filtered ports in advanced settings - DNS will be broken. 
Instead, for this purpose, use DNS filtering functionality in Adguard for Android app.

Blocking multicast traffic may technically be implemented. However, at this moment multicast is excluded unconditionally to not to break things.
