### ISSUE TITLE
Provide a method for adding local exclusions to HTTPS filtering exclusion list

### ISSUE THREAD

**Issue by bwoodnz** [AdguardTeam/AdguardForAndroid#4149]
A number of android (and possibly others) applications will now only allow connections to servers where the hostname is included in the first CN or one of the Subject-Alts of the SSL certificate. This means that AdGuard will break connections to these applications. These applications are typically used to connect to internal company or private domains so are not appropriate for adding to the compiled exception list.
My example is the HCL Verse android client, but I'm sure there are / will be others.
It would be good to be able to specify trusted domains to be excluded from SSL filtering to avoid issues with these applications.

**Comment by sfionov** [comment]
Hello! 

AdGuard usually generates MITM certs with proper CN / Subject alt names.

The first issue is that, starting from Android 7.0 Nougat, apps by default doesn't trust user CA's if that is not explicitly allowed in the manifest of application. Cert pinning may be another issue - app may have some Subject Public Key Hashes hardcoded, and they should match at least one cert in certificate chain.

In both cases AG received "unknown ca" TLS alert from application, and sequential connections should be succeed.

However, you may add some domains into HTTPS filtering exclusions, to eliminate extra connection attempts. Despite the fact that exclusions are built in, AdGuard allows to edit this list: see *Settings -> Network -> HTTPS filtering -> Allowlist*.

Another way is to turn off HTTPS filtering in particular app.

**Comment by maxikuzmin** [comment]
@bwoodnz did our advice help you? Is the issue still relevant?

**Comment by bwoodnz** [comment]
Thanks for your reply.
1. The certificate generated / presented by AdGuard had a cn=www.example,org (if your observation above is correct, should have been "traveler.corlett-wellstone.com"). Out of curiosity, how is the cert generated?
2. I will try your suggestion of editing the settings to add the domain to the exclusion list (this is what I wanted - sorry I missed the option...)
3. If that doesn't work I will try turning off filtering for the app - it's an internal email client so shouldn't have ads... Can you point me to the procedure for this?
Will keep you posted...

**Comment by maxikuzmin** [comment]
@bwoodnz is the question still relevant?

**Comment by maxikuzmin** [comment]
@bwoodnz ping
