### ISSUE TITLE
Фильтрация DNS

### ISSUE THREAD

**Issue by DA-FormMaker** [AdguardTeam/AdguardForAndroid#4150]
Фильтрация DNS отключена

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/101049895/165673218-83338502-fb41-467f-a78d-9b7e810064c3.jpg)

</details><br/>

Но фильтрация DNS у меня включена, а вот фильтры отключены

<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/101049895/165673356-f11a1f70-3a32-444c-8389-2e74fa966850.jpg)

</details><br/>

Отключение фильтрации и отключение фильтров на мой взгляд две разных вещи.

**Comment by Chinaski1** [comment]
В данном случае имеются ввиду как раз DNS фильтры.
