### ISSUE TITLE
Уведомление о новой версии

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#4151]
Стоит nightly 32 версия. Бесит, что в шторке уведомлений постоянно весит обновление с требованием обновиться до новой версии, которон никак нельзя убрать. Хватит навязывать людям обновления до новой версии. Если они захотят, то сами обновятся

**Comment by Chinaski1** [comment]
Здравствуйте!

Мы стараемся сделать наш продукт лучше с каждым обновлением, исправляя возникающие проблемы и добавляя новый функционал, поэтому установка обновлений необходима.

Если вы не желаете обновлять приложение, всегда можно оставить более старую версию. Однако уведомления при этом всё ещё будут появляться.
