### ISSUE TITLE
Adguard CA certificate installation fails

### ISSUE THREAD

**Issue by chortya** [AdguardTeam/AdguardForAndroid#4152]
Installed Adguard on my new Sony Xperia Pro-I with Android 12 update and can't install CA certificate for HTTPS filtering.
![Screenshot_20220430-165908](https://user-images.githubusercontent.com/33870775/166134100-0ed5def9-c646-46f5-b013-8418f88b7353.png)

**Comment by Chinaski1** [comment]
Hello there!

Could you tell us the full path to the certificate installation menu?

At first glance, it looks like you are trying to install it in the wrong way. 

Usually it is Security -> Encryption -> Install certificate -> Install CA certificate

**Comment by Birbber** [comment]
@chortya Hi! Any news?

**Comment by Birbber** [comment]
Good to know. In this case I'm closing the issue. Re-open if needed.
