### ISSUE TITLE
Android Chrome Version 101 breaks https filtering

### ISSUE THREAD

**Issue by terrytw** [AdguardTeam/AdguardForAndroid#4153]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.8
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Oneplus 5T
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

With the latest android chrome update 101, https filtering has been broken.

My screenshot is in Chinese, so I will not show it. Basically it says something along the lines of "CA certificate transparency is broken"
You can tap "advanced" and continue anyway, but it is cumbersome. 

I am fairly confident on this, because my wife's phone showed it first, because she's already updated to 101. I tried trouble shooting for a while, and my phone was fine because it was on 100. Then I tried to update my phone to 101 and the same problem shows up.

**Comment by Chinaski1** [comment]
Hello there!

I checked your appeal and did not encounter any problems with the security CA in Chrome 101.
Most likely you just need to reinstall the security certificate. 

1. Go to Android settings -> Security -> Trusted credentials.
2. Go to the "User" section.
3. Select "AdGuard Personal CA" (it might be the only certificate there).
4. In the opened dialog window scroll down and tap 'Remove'.
5. Open AdGuard app and install it again

**Comment by sfionov** [comment]
@terrytw Do you have cert into system storage? If it is, we have new [adguardcert](https://github.com/AdguardTeam/adguardcert) Magisk module which is supposed to be used instead of "Move cert(s)" modules.

**Comment by terrytw** [comment]
@sfionov Yes, yes, the new magisk module fixed it for me. Thanks!
