### ISSUE TITLE
Совместимость

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4154]
Здравствуйте!
Крайне необходима совместимость с ProtonVPN. Подскажите, пожалуйста, каким образом я могу её обеспечить?

Мне необходимо, чтобы всё работало по одной из этих схем:
AdGuard->ProtonVPN->Orbot
Либо
AdGuard->ProtonVPN->интернет

_**Интересует ИМЕННО работа через профиль OpenVPN (вот ссылка для более лучшего понимания меня: https://protonvpn.com/support/android-vpn-setup/)**_

Я уже писал в техподдержку, но мне написали полный бред связанный с прокси на WI-FI. Меня интересует _**ИСКЛЮЧИТЕЛЬНО**_ мобильный интернет.

—————————————————————

В приложении OpenVPN я нашёл следующую функцию:
![9C8AD39C-EC40-47E3-9937-246D9B0AE45D](https://user-images.githubusercontent.com/104867420/166563446-e186607c-05d5-4ab0-935e-952fd83c13a9.jpeg)
Поможет ли это мне?

**Comment by maxikuzmin** [comment]
Is the question still relevant?

**Comment by yu12qy** [comment]
Здравствуйте! Спасибо за ответ. Приношу извинения за столь длительный ответ. В указанной вами статье нет ни слова о ProtonVPN либо указанной мной выше конфигурации.

Меня интересует совместная работа именно с ProtonVPN **НЕ** на Wi-Fi

**Comment by maxikuzmin** [comment]
Одной из особенностей  Android является работа только с одним VPN-сервисом, поэтому необходимо получить root-права на телефоне, затем зайти в Adguard - Настройки -  Сеть - Режим фильтрации - Локальный HTTP-прокси, выбрать Автоматический режим локального прокси.

**Comment by maxikuzmin** [comment]
Инструкция помогла вам? Все в порядке?

**Comment by iltoo** [comment]
Благодарю за помощь. Все заработало должным образом! Большое спасибо :)
