### ISSUE TITLE
Protection hasn’t been started due Kill Switch is on

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4155]
Learn to handle the situation “Protection hasn’t been started due Kill Switch is on”

Well, we have a situation with the application protection when the Kill Switch functionality is on for another VPN profile.
We need to implement a custom scenario for this case to make more clarity in the protection behavior. Maybe we will show a dialog after the  VPN profile wasn’t created?

**Comment by artemiv4nov** [comment]
Well, I have rechecked on the new version, and now it works, I'll close the task.
