### ISSUE TITLE
Ability to hide VPN icon

### ISSUE THREAD

**Issue by ivanmood0** [AdguardTeam/AdguardForAndroid#4158]
If possible, it would be good to implement the function of hiding the VPN icon while the application is running.
![2022-05-09_12-58](https://user-images.githubusercontent.com/79835684/167388485-db28a493-9937-40b6-b3f1-5c76e6aa2bfc.png)

**Comment by Birbber** [comment]
@ivanmood0 It's a system icon which we can't affect in any way.
