### ISSUE TITLE
Add the ability to choose to have all applications turned off by default

### ISSUE THREAD

**Issue by ivanmood0** [AdguardTeam/AdguardForAndroid#4159]
Add the ability to manually select applications to which ad blocking is applied. Currently, blocking is automatically applied to most installed applications, and when installing new ones, they also fall into this list (undesirable behavior for banking applications, etc.).
It would be great to be able to choose the applications that AdGuard works with, rather than manually excluding applications so that AdGuard does not apply to them.
![2022-05-09_14-28](https://user-images.githubusercontent.com/79835684/167401545-7c79b6a8-5ce9-47ed-8ef8-74b70b87e113.png)

**Comment by Birbber** [comment]
@ivanmood0 Hi! Open `Apps Management` and tap on the additional menu (3 dots) --> Bulk change --> Configure it according to your needs. For example, by choosing 'AdGuard Protection' + 'Disabled' + 'Apps and browsers'.
