### ISSUE TITLE
soap4.me - video playback issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#416]
soap4.me 
На сайте soap4.me на устройстве c ОС Android при попытке просмотра онлайн видео минуты 2-3 идет воспроизведение, а потом останавливается. Продолжить возможно только после выключения защиты Adguard. Добавление soap4.me в белый список в настройках программы проблему не решает.

Сообщений об ошибке нет

logs APR-438-10849

Oтключение фильтров не помогло. Логи выслал. Начало
воспроизведения 21.25, остановка 21.27.

**Comment by ameshkov** [comment]
Просьба проверить работу вот этой сборки:
https://cdn.adguard.com/public/Adguard/github/AdguardForAndroid/issue416/adguard.apk

**Comment by evgeniy-ADG** [comment]
Здравствуйте. Проблема сохраняется. На 02.27 воспроизведение останавилось.

**Comment by ameshkov** [comment]
Новые логи есть?

**Comment by evgeniy-ADG** [comment]
Нет, к сожалению. Я дал бету, попросил еще раз воспроизвести и выслать лог со временем.
