### ISSUE TITLE
Mobile data with manual proxy setup

### ISSUE THREAD

**Issue by privacyguy123** [AdguardTeam/AdguardForAndroid#4161]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I have manually edited my APN to proxy through ```127.0.0.1:8080``` which is the proxy I have set up in Adguard with manual proxy mode (not rooted) - long story short it does not seem to be blocking any ads or using the adlists at all, is there something I'm missing here?

EDIT: In Adguard proxy settings "check connection" always fails.
EDIT2: I read this is a known broken thing since Android 10 because you cannot read /proc/net/tcp - is there going to be any attempt to fix this?

**Comment by Birbber** [comment]
@privacyguy123 Hi! Sorry for the late reply.
Try to set up a proxy server by creating a new one in AdGuard (not using a local http proxy), since you don't have a rooted device: Settings → Network → Proxy server → Add proxy server.
Let us know the result!

**Comment by Birbber** [comment]
@privacyguy123 Any news?

**Comment by Birbber** [comment]
I'm closing this one due to no reply. Please re-open if needed.
