### ISSUE TITLE
Cannot Install HTTPS Certificate on Samsung Galaxy S22 Ultra

### ISSUE THREAD

**Issue by stevelmartin56** [AdguardTeam/AdguardForAndroid#4162]
I have just got my new Galaxy S22 Ultra (Android Ver 12) and installed the latest version of Adguard for Android Ver 3.6.8 (46).  When it comes to installing the HTTPS filtering certificate, the .crt file is saved to "downloads". However, when I then try to install the CA certificate, the file is not seen in the Internal Storage area.  I have also tried downloading to Google Drive and OneDrive, but is not seen there either.

I recently installed the app on another Samsung A13 phone and it installed with no issue.  However, this is not the case with the Galaxy S22 Ultra.

Please repair the bug to allow installation.

**Comment by Birbber** [comment]
@stevelmartin56 Hello! Sorry for the late reply. Is this issue still reproducible?
It came to our notice that Samsung released an update for 'My files' application which helped users with similar issue.

**Comment by stevelmartin56** [comment]
Hi Anna

 

I wasn’t aware of the Samsung update and my version of My Files is 13.1.00.171.

 

However, I uninstalled the latest My Files update and went back to Version 13.0.01.92 and have now been able to install the certificate.

 

Thanks for the email and giving me the idea of uninstalling the recent update of My Files.  However, to answer your original question, the issue is still there.

 

Kind regards

 

Steve

**Comment by Birbber** [comment]
@stevelmartin56 I'm glad I was able to help at least by this. Our developers are aware of this issue, but it seems like it has nothing to do with our application. 
Will let you know if we get more information on this.

**Comment by artemiv4nov** [comment]
@stevelmartin56 Hi!
Please explain what do you mean with this phrase:
> However, when I then try to install the CA certificate, the file is not seen in the Internal Storage area

Can you make a video with your screen and send it to our devteam@adguard.com email?

**Comment by stevelmartin56** [comment]
A bit late now as I have solved the issue by re-installing an earlier version of Samsung’s My Files.  However, when I go to Biometrics and Security | Other Security Settings | Install from device storage |CA Certificate and then “Install anyway” the “select item” shows nothing, and even if I touch “Internal storage”, no file is seen.

 

Hope that helps.

**Comment by maxikuzmin** [comment]
@stevelmartin56 try deleting the last "My files" update and go back to version 13.0.01.92
Some users have been helped by this solution. Perhaps in the future they will release an update with a solution to this problem. In any case, the problem is in "My Files" and not on our side.

**Comment by stevelmartin56** [comment]
That is what I did to resolve the issue.  Love the way software companies blame each other rather than mutually try to resolve the problem!

**Comment by maxikuzmin** [comment]
Since the problem no longer appears, the issue is closed
