### ISSUE TITLE
What are the default (especially low-level) settings?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#4163]
### Problem Description

I've been running AGA for ages now (& AGW for a little while now, too) & it occurs to me that, over that time, I've probably messed around w/ nearly every setting in some version or other.  Most of the time, it's very easy to educated-guess what the default is (e.g., toggles).  However, in others (e.g., text fields & most of low-level), I've probably done things that now might be obsolete or non-optimal as the app has updated _many_ times since.  How do I know/revert any _**(not all!)**_ such setting to current AG default?

### Proposed Solution

I'd like a sensible, straightforward, reversible way to see what each default would be _w/o necessarily_ losing whatever custom value that's currently there.

### Alternatives Considered

- A link to a webpage for each settings page would be fine, but needs to be guarded from rot & how does 1 keep track of defaults for different vdrsions?
- It's very easy to wholesale revert _all_ of AG by wiping user data & rerunning the Quick Settings wizard, but that's definite overkill.

### Additional Information

Maybe it seems like a lot of extra work, but it'd probably help us debug whatever shenanigan we did to ourselves.

**Comment by Nzzyme** [comment]
@TPS : In the 'Low-level settings' page, the last option at the bottom is 'Reset'?

**Comment by maxikuzmin** [comment]
@TPS these are the default settings. This should help.

"pref.ipv4.routes.exclud" - "172.18.11.218"
"pref.ipv6.routes.excluded" - "2001:db8:ad:0:ff::
"pref.vpn.capture" - false
"pref.har.capture" - false
"pref.vpn.disable.pause" - false
"pref.proxy.disable.reconfigure " - true
"pref.proxy.block.ipv6" - false
"pref.filtered.ports" - 80:5221, 5299:49151
"pref.boot.startup.delay" - 10
"pref.enforce.paused.notification" - false
"pref.root.clear.youtube" - false
"pref.root.set.oom_adj" - false
"pref.removed.html.log" - false
"pref.samsungpay.autopause.enable" - false
"pref.dns.bootstrap" - empty
"pref.dns.fallback" - empty
"pref.dns.fallback.domains" - empty
"pref.dns.detect.search.domains" - false
"pref.dns.timeout" - 5000
"pref.dns.blocking.type" - 1
"pref.notify.on.unknown.ca" - true
"pref.https.ignored.errors" - empty
"pref.https.opportunistic" - true
"pref.quic.bypass.packages" - false

**Comment by TPS** [comment]
> @TPS these are the default settings. This should help.

@maxikuzmin Thanks!  For which version?  Difficulty would be to get a list that _stays_ current w/ each update I do.

**Comment by maxikuzmin** [comment]
for version 3.6.8 (46). Oh, you're right indeed. The copy is incomplete. 
for "pref.ipv4.routes.exclud" 

// Reserved subnets
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
172.16.0.0/12
192.0.0.0/24
192.168.0.0/16
224.0.0.0/4
240.0.0.0/4
255.255.255.255/32
// T-Mobile wi-fi calling (#233)
208.54.0.0/16
// AT&T wi-fi calling
129.192.166.0/24
// UK EE wi-fi calling (#582)
109.249.0.0/16
// Sprint wi-fi calling (#939)
68.31.26.0/24
// Verizon wi-fi calling (#1321)
141.207.0.0/16
// Orange PL wi-fi calling (#1796)
217.116.96.0/20
// IranCell Wi-Fi calling
92.42.49.0/24
// Jio Wi-Fi calling
49.44.59.0/24
49.45.63.0/24
// Mobile Communication Company of Iran Wi-Fi calling
5.106.2.0/24
// Aofei Data International Wi-Fi calling
5.182.63.0/24
185.232.56.0/24
185.232.57.0/24
// Bharti Airtel Limited Wi-Fi calling
106.200.64.0/24
106.200.65.0/24
223.180.224.0/24
117.96.89.0/24
// Velcom Wi-Fi calling
128.140.255.0/24
// MTS Wi-Fi calling
213.87.143.0/24
// T-mobile Netherlands Wi-Fi calling
84.241.238.0/24
// MTC-KSA (Mobile Telecommunications Co Saudi Arabia) Wi-Fi calling
79.170.52.0/24
79.170.53.0/24
185.5.152.0/24
// China Mobile communications corporation Wi-Fi calling
120.236.180.0/24
183.236.59.0/24
// DiGi Telecommunications Wi-Fi calling
115.164.123.0/24
115.164.251.0/24
// Turkcell Wi-Fi calling
188.59.223.0/24
188.59.227.0/24
188.59.228.0/24
// Cosmote Wi-Fi calling
94.143.176.0/24
94.143.177.0/24
94.143.178.0/24
// Vodafone Greece Wi-Fi calling
62.74.30.0/24

It's also obvious. "pref.excluded.packages"

// Disable for "radio": https://github.com/AdguardTeam/AdguardForAndroid/issues/1058
1001
// Disable for "system": https://github.com/AdguardTeam/AdguardForAndroid/issues/2550
1000
// Disable Downloads Manager https://github.com/AdguardTeam/AdguardForAndroid/issues/3355
com.android.providers.downloads
com.android.providers.downloads.ui
com.adguard.vpn
// Realme devices have their own Download Manager https://jira.adguard.com/browse/AG-8368
com.coloros.providers.downloads.ui

If there are not yet any settings, let me know

**Comment by TPS** [comment]
I'm on v4.0n34 (75).  See how this gets confusing if not built into the version 1's running?

**Comment by maxikuzmin** [comment]
@TPS the settings I sent you are up to date. Are there any other settings you're interested in?

**Comment by TPS** [comment]
Truly, this is difficult to compare.  Just having name/value pairs doesn't really make figuring this out simple, as nothing in any UI is setup for that.

**Comment by maxikuzmin** [comment]
@TPS  the settings I sent you are up to date now. You can compare the values you were interested in, or as already written before - just reset to "default settings".
Issue closed
