### ISSUE TITLE
[BUG] IPs showing in logs with Local HTTP Proxy mode, filter not working

### ISSUE THREAD

**Issue by SemiZhang** [AdguardTeam/AdguardForAndroid#4164]
### Issue Details
**From 3.6.2, with Local HTTP Proxy mode. About half of the web requests are not captured as URLs, but are processed as IP addresses, and therefore cannot be filtered by any filtering rule.**
Worked well with Local HTTP in 3.6.1.
Worked well with VPN mode in all version.

- **AdGuard version:**
  - From 3.6.2 to 3.6.8
- **Filtering mode:**
  - Local HTTP Proxy (Manual)
- **Device:**
  - Samsung N9500
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior
**Show domains and URLs in logs. Filtered by rules.**
![Screenshot_20220512-102128_AdGuard](https://user-images.githubusercontent.com/26916265/168028120-6901ab48-2877-4d0c-93a9-039c57b29792.jpg)

### Actual Behavior
**Showing ip:port in logs. Not being filtered.**
Around 50% of requests from Chrome are still OK, but worse for other apps.
![Screenshot_20220512-102241_AdGuard](https://user-images.githubusercontent.com/26916265/168028240-f8e0f736-952d-46bd-a2ca-3f16a85c1a53.jpg)

### Additional Information
My Local HTTP Proxy Settings
![Screenshot_20220512-102217_AdGuard](https://user-images.githubusercontent.com/26916265/168028327-cac316dc-b5bd-4f3d-9f0f-b03e7a772bb9.jpg)
![Screenshot_20220512-102206_Settings](https://user-images.githubusercontent.com/26916265/168028341-9c8c4db4-bd33-443f-a844-8099818cc00a.jpg)

**Comment by maxikuzmin** [comment]
@SemiZhang do you have DPI protection enabled?

**Comment by maxikuzmin** [comment]
@SemiZhang any news?
