### ISSUE TITLE
[Question] AdGuard security

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4171]
Hello!
I am considering starting to use your development. Please advise the following:
- Where can I view the source code of the application? If there is no such possibility, why should I trust you?
- I'm very suspicious about the cooperation between AdGuard and the VPN of the same name. With an HTTPS certificate, you can do whatever you want with the traffic on the server.
- The browser will see the AdGuard certificate. What if the site has an invalid certificate?

I feel very strongly that this is extremely insecure. AdGuard + AdGuard DNS + AdGuard VPN and all this with https certificate installed will allow you to do anything with the traffic on your servers. The intrusive prompt to install Adguard VPN the first time you run the program is especially embarrassing.

In essence, your servers can easily steal your credentials and even sell your activity to advertisers. Or am I wrong? I will be glad if you can prove otherwise.

And yes, I know that filtering happens LOCALLY. But what happens outside of it is very worrying.

**Comment by Birbber** [comment]
Hello!

> Where can I view the source code of the application? If there is no such possibility, why should I trust you?

The source code is available only for a part of AdGuard products. Briefly, all our free products are open source, paid are not:
https://adguard.com/en/blog/adguard-open-source-policy.html
Regarding the trust, we worked for over 10 years to earn our reputation and we've never betrayed the trust of our users.
We follow a strict privacy policy and the fact that our apps do follow them can be verified by any network monitoring tool.
> I'm very suspicious about the cooperation between AdGuard and the VPN of the same name. With an HTTPS certificate, you can do whatever you want with the traffic on the server.

That was one of the reasons for us to make a separate app (AdGuard VPN) and not add the VPN functionality to AdGuard.
It is transparent how the integration works:
- AdGuard does the filtering part (that involves HTTPS filtering if you enabled it)
- Then it routes the traffic through the AdGuard VPN app (at that moment the HTTPS is encrypted again).
- And then AdGuard VPN app routes it through the VPN tunnel.

At no point in this scheme we at AdGuard can see your decrypted traffic.
> The browser will see the AdGuard certificate. What if the site has an invalid certificate?

AdGuard does everything that the browser does to verify the certificate: https://kb.adguard.com/en/general/https-filtering
If AdGuard suspects that something is wrong with the certificate, it stops HTTPS filtering for that domain and lets your browser decide what to do.
