### ISSUE TITLE
If I downloaded APK update before, don't download it again

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#4172]
### Problem Description

If I downloaded the APK of an update, but then didn't install it, and then decided to install an update again, you download it again, and because of this, the internet traffic is wasted, and an update takes longer.

### Proposed Solution

If I downloaded the APK of an update, but then didn't install it, and then again decided to install an update, do not download it again, but offer to immediately install the downloaded version.

### Alternatives Considered

N/A

**Comment by Birbber** [comment]
@rakleed It depends on the firmware I guess, 'cause when I try to install the apk it says I already have one installed (on Honor). What phone do you use?
