### ISSUE TITLE
Mail.Ru app contains adverts 

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#4176]
Приветствую.

В приложение Mail.ru стала проникать навязчивая реклама банковских карт Тинькофф. Можно её убрать, чтоб не пришлось менять почтовый клиент на новый?

Заранее благодарю.

- **AdGuard version:**
- 3.6.8
 
- **Filtering mode:**
Local VPN

- **Device:**
Lenovo Tab 11
 
- **Operating system and version:**
  Android 11

- **Root access:**
No

Filters enabled:
AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyPrivacy, Online Malicious URL Blocklist

![IMG_20220526_211659](https://user-images.githubusercontent.com/23212486/170551871-00a5562c-1b4b-4f46-9b97-241ce3091903.jpg)

**Comment by Birbber** [comment]
Issue moved to [AdguardTeam/AdguardFilters #120046](https://github.com/AdguardTeam/AdguardFilters/issues/120046) via [**ZenHub**](https://www.zenhub.com/)
