### ISSUE TITLE
Twitter ads not filtered on Twitter Android

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardForAndroid#418]
Using AG 2.5 beta on my Galaxy Note 4 smartphone, after enabling https filtering, I still have Twitter sponsored tweets (which sometimes includes bandwith consuming videos).

I have cleared the data and the cache of the app before reloading it. I still have the ads.

**Comment by ameshkov** [comment]
Not sure if it's possible to filter https in the twitter app (we just have not check it yet).

Anyway, for blocking such complicated ads (when ad is a part of some feed) we need to first implement a $replace modifier: #239

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look at twitter app? How do they load ads?

**Comment by Alex-302** [comment]
This app ignores system proxy. ProxyDroid not work on my device.

**Comment by ameshkov** [comment]
@Alex-302 just use Adguard log for that.

**Comment by ameshkov** [comment]
Twitter app does not allow us to filter its HTTPS traffic :(

**Comment by ameshkov** [comment]
There is a way to turn off SSL pinning.

You need ROOT access to do it. We'll think about adding such an option to Adguard:
https://github.com/AdguardTeam/AdguardForAndroid/issues/472

Meanwhile the best option I see is to use SSLUnpinning xposed module:
https://github.com/ac-pm/SSLUnpinning_Xposed

But that's not all. Even with SSL pinning turned off AG won't remove twitter ads yet.
We'll need some time to do it.

**Comment by ameshkov** [comment]
If you decide to try unpinning, don't forget to remove twitter app from HTTPS apps exceptions.
