### ISSUE TITLE
Browser and other apps can't access web pages after a period of time after adguard set dns to a locally built dns service

### ISSUE THREAD

**Issue by Trustedinstall** [AdguardTeam/AdguardForAndroid#4184]
- [ Yes ] I am running the latest version
- [ Yes ] I checked the documentation and found no answer
- [ Yes ] I checked to make sure that this issue has not already been filed

- AdGuard version:
  - v3.6.8 (46)
- Filtering mode:
  - Local VPN
- Device:
  - OnePlus 3T
- Operating system and version:
  - Mokee Android 10
- Root access:
  - Yes

I use AdGuardHome to build a local dns service on port 5353.
After setting the dns server to 127.0.0.1:5353 in AdGuard and turning on protection, Kiwi browser can open web pages normally for a short period of time (maybe 3~5 minutes), but after that time it cannot open new web pages, the browser shows that it cannot resolve the domain name, and other apps cannot access the network.
Checking the AdGuardHome logs, I found that I received a dns query from 127.0.0.1 and had a normal dns response.

The desired behaviour should be to always have normal access to the network

[adguard_logs_3.6.46_0506_111439.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/8839288/adguard_logs_3.6.46_0506_111439.zip)

**Comment by Trustedinstall** [comment]
> 

Any URL is not accessible, the logs are under this issue.

**Comment by Trustedinstall** [comment]
> @Trustedinstall你好！这么晚才回复很抱歉。
> 
> 以下是我们需要您做的事情：
> 
> * 选择任何网址并关注它
> * 记住您访问它的时间
> * [收集](https://kb.adguard.com/en/android/solving-problems/log#debug)应用程序的调试日志
> * 将文件发送给我们并告诉我们确切的时间和确切的 url，以便我们可以在日志中找到它

Any URL is not accessible, the logs are under this issue.

**Comment by Trustedinstall** [comment]
> @Trustedinstall Hi! Sorry for the late reply.
> 
> Here's what we need you to do:
> 
> * Choose any url and follow it
> * Remember the time you visited it
> * [Collect the debug logs](https://kb.adguard.com/en/android/solving-problems/log#debug) of the application
> * Send us the file and tell the exact time and exact url, so we could find it in the logs

Any URL is not accessible, the logs are under this issue.

**Comment by Birbber** [comment]
@Trustedinstal We're gonna need the exact URL you followed and the exact time you tried to reach it. Otherwise we won't be able to find anything in the logs.

**Comment by Trustedinstall** [comment]
> @Trustedinstal We're gonna need the exact URL you followed and the exact time you tried to reach it. Otherwise we won't be able to find anything in the logs.

Take the website 6.ipw.cn for example, the problem occurred at 11:07.
