### ISSUE TITLE
Please support “V2ray Core” in Proxy section for restricted countries

### ISSUE THREAD

**Issue by Shikopat** [AdguardTeam/AdguardForAndroid#4187]
Hello 

In some restricted countries in Asia, only "V2Ray" proxy based protocol works in that region and only this protocol works properly in specific countries, but we need to be supported in AdGuard too! 

Here's the source code and documentation:
https://github.com/v2fly/v2ray-core

Please consider this issue and help us by adding this protocol in “Proxy settings” of AdGuard.

Regards.

**Comment by Birbber** [comment]
@Shikopat Hi! Thanks for your suggestion, but I'm afraid it's too hard to implement at this point. We'll think about it in future.
