### ISSUE TITLE
Версия 4.0

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4189]
Когда выйдет стабильная 4-я версия?

**Comment by artemiv4nov** [comment]
В этом году.

**Comment by Spok1** [comment]
@artemiv4nov,хотелось бы более развернутый ответ получить! Осенью или зимой?

**Comment by artemiv4nov** [comment]
Пожалуйста, ожидайте дальнейших анонсов в соц сетях компании.

**Comment by Spok1** [comment]
@artemiv4nov,надеюсь,там будут исправлены все проблемы,присущие текущей версии.
