### ISSUE TITLE
[Feature request] use more convenient format of HTTPs exclusions and pref.net.exclusions lists

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#419]
> Please when adding exceptions to the white list have everything as a line item instead of a big notebook. Kind of like the windows version it's one url per line. Also for apps exception you have manually enter the apk name which is awful. Please have it pull a list of apps from the phone kind of like the firewall area has apps listed.

**Comment by ameshkov** [comment]
We'll do it after the app redesign.
