### ISSUE TITLE
Feature to avoid redundant or almost identical filters

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4192]
Hey Team,

Can we develop a feature in AdGuard which will warn users if they are selecting the same or similar filters to avoid redundancy? I mean, I just went through details of filters recently on my Android App, and from 23 selected filters, I selected only 13 filters which worked best for my use after reading a short description of all filters and found that quite interesting to notify and request for a feature which will help users select only required filters and saving battery as well as even faster page load times due to avoidance of redundant filters.

**Comment by Birbber** [comment]
@tosouravbhor Thanks for the suggestion! We'll see how many upvotes it will take and after that will decide whether we should implement such a feature.

**Comment by vitek29** [comment]
@Birbber 
I suppose, the feature will be resource consuming and technically difficult to implement.
In case of fully identical filters - OK, no problem, good to have.
But how does the app should to know if these filters are almost identical? If there are 10 similar rules or 20, or may be 50%, and what if the same rule is in 3 or 5 filters?
The only way is to ignore identical rules when parsing all bunch of filters to virtual one which is used by AG engine when filtering actual web-requests. In that case redundant rules will be ignored.
Hope it's already implemented. (please check if it's true).

**Comment by artemiv4nov** [comment]
I think the implement could be really hard and useless.
Please re-open the task if it will gain more than 10 likes.
