### ISSUE TITLE
Incorrect blocking: Ritual App

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardForAndroid#4193]
Ritual Food App (https://play.google.com/store/apps/details?id=co.ritual.app&hl=en_CA&gl=US) cannot load when AdGuard Android is enabled.

**Comment by maxikuzmin** [comment]
@snhv I can't download this app. It is blocked for several countries. Which country are you from?
Could you give more details on exactly what problem is occurring when downloading?

**Comment by maxikuzmin** [comment]
@snhv ping

**Comment by snhv** [comment]
Hi @maxikuzmin sorry. I'm from Canada. Adguard seems to block certain connections as the app does not load after installation (but load if adguard is disabled). 
It's fine for me now because I whitelist the app in adguard and the app does not serve any ad.

**Comment by maxikuzmin** [comment]
@snhv  we're sorry you're having trouble. Did the whitelist solve the problem? 
If there are no more questions, I will close the issue

**Comment by snhv** [comment]
Yes whitelist solves the problem. I just wanted to let you know so that other users will not face the same issue. I'll close this one.
