### ISSUE TITLE
Assistant for mobile versions

### ISSUE THREAD

**Issue by gimenes2008** [AdguardTeam/AdguardForAndroid#4194]
Hi!

I suggest, if possible, an AG Assistant for the mobile versions similar to the PC browser Assistant.

**Comment by gimenes2008** [comment]
Unicorn Software's Samsung browser extension is an example of my suggestion.

![Screenshot_20220705-101259_Galaxy Store](https://user-images.githubusercontent.com/84917267/177336833-d81e3f79-6290-4a55-bb44-387d7bccc772.png)

_Image credits: Unicorn Software Inc_.

**Comment by TPS** [comment]
Duplicates #2163

**Comment by gimenes2008** [comment]
Hi, @TPS!

Great! This feature is already in progress, so I'm closing this issue.
