### ISSUE TITLE
Merger of AdGuard VPN with AdGuard App

### ISSUE THREAD

**Issue by tosouravbhor** [AdguardTeam/AdguardForAndroid#4196]
Hi Team,
I have been using both your services and found that it is causing a lot of battery drain as I keep both apps on. I moved from ExpressVPN and Nord VPN just because I could not use AdGuard properly on my Android. Still, as I started using both apps on Android after subscribing to AdGuard VPN, I could see the massive battery drain as both apps ran independently. If we can integrate both apps in a manner that if a user subscribes to both the services, then he can use either of the apps to get the benefits of your incredible services. Apart from battery drains, there are sometimes conflicts between both apps, and that causes me to restart either of them and then enjoy the seamless internet experience. This is the case where I turn off the internet, so logically, the AdGuard VPN closes, but AdGuard keeps running as I don't mind turning it off or, instead, too lazy to turn off both manually. After a while, when I turn on the internet again and try to connect to the internet via AdGuard VPN, sometimes a restart of both apps is required. So I feel there must be a universal app which serves both the purposes of quality ad filtering with Adguard VPN functionality.

**Comment by Birbber** [comment]
@tosouravbhor Hi!
It's not really possible to merge these two applications, and I don't think it will be done in the future.
Right now we're working on 4.0 version where the entire application would be reworked as well as the integration mode, so we hope we'll manage to get rid of some conflicts between apps and improve its efficiency.
