### ISSUE TITLE
Add filterlist Anti-Adblock Killer

### ISSUE THREAD

**Issue by reek** [AdguardTeam/AdguardForAndroid#420]
Hi,

I am the author of the project Anti-Adblock Killer and I just suggest you to add AakList to your predefined lists in AdGuard (for all your products), because I have some user who would like to use with AdGuard.

Thanks
Reek

Project
<code>https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek</code>

AakList
<code>https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt</code>

**Comment by TPS** [comment]
I already requested precisely this via #29, & the response was it will land via #34.

**Comment by reek** [comment]
I recently removed this clause, so you can include them without problem.

**Comment by TPS** [comment]
How useful is AAK _without_ the userscript support?  If "not so much," shouldn't @AdguardTeam wait 'til #34 lands _before_ including the AAK filterlist?

**Comment by reek** [comment]
the two are complementary and unlock different website, obviously with the
support of userscripts Aak would be more efficient.

2016-04-04 0:27 GMT+02:00 TPS <notifications@github.com>:

**Comment by ameshkov** [comment]
Hi @reek! Thank you, we'll do it in v2.5 update.

**Comment by reek** [comment]
@ameshkov 
Thank you :smile:

**Comment by ameshkov** [comment]
Done, will be available in the next beta version.

**Comment by reek** [comment]
Thanks :+1:
