### ISSUE TITLE
Подписка "Ru Ad List" ?

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#4200]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

А где подписка "Ru Ad List" в AdGuard ? EasyList есть, а "Ru Ad List" - нет. В языковых её тоже нема. Можно конечно добавить вручную, но для этого должна быть лицензия (у меня она есть, но тем не менее). Не раз и не два уже замечал, что на ура лочилось через "Ru Ad List" на десктопе, проскакивало мимо стандартных фильтров AdGuard. Включите эту подписку в стандартную поставку.

**Comment by bogachenko** [comment]
Поздравляю с подключением к Интернету!
https://github.com/AdguardTeam/AdguardForAndroid/issues/3935

PS: Не помощник Adguard.

**Comment by Baltazar500** [comment]
> Прочти https://github.com/AdguardTeam/AdguardForAndroid/issues/3935 и посмотри дату удаления [здесь](https://github.com/AdguardTeam/AdguardBrowserExtension/commit/085eb19f50f1c0ff32aef76b30a356b02824cfee#diff-dd84311334f95a45fe13f48d898567b43c85666301d7f8bf69c1b791d3bb5b81L599-L618).

@bogachenko, ну т.е. он "был" и через 9 дне "сплыл". Собственно этот пост https://github.com/AdguardTeam/AdguardForAndroid/issues/3935#issuecomment-895359264 про это и говорит (гуглотранслит)

>Мы решили удалить указанный фильтр из списка по умолчанию, так как его не рекомендуется использовать вместе с русским фильтром AdGuard.
>При желании вы можете установить его в разделе Пользовательские фильтры.

При желании. Угу. И при наличии лицензии.

@bogachenko, Спасибо за комментарий

**Comment by zzebrum** [comment]
@Baltazar500 пока что не планируем возвращать.
