### ISSUE TITLE
Пропуск рекламы 

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#4201]
Приложение ADM https://4pda.to/forum/index.php?showtopic=280941&st=1280
Стоит nightly34. Фильтрация качественная, локальный vpn, https, фильтр мобильной рекламы, галка на блок приложений, русский фильтр
![Screenshot_2022-07-05-22-33-26-780_com dv adm](https://user-images.githubusercontent.com/22351242/177403358-5148943d-38b4-4ff5-9631-a42653d513d3.jpg)

**Comment by ministr91** [comment]
@Alex-302 уже 20 дней прошло...

**Comment by Alex-302** [comment]
В этом репозитории и год проледать может, потому что написали не туда, куда следует.
https://kb.adguard.com/ru/technical-support/reporting-tool

**Comment by ministr91** [comment]
@Alex-302 @ameshkov я написал сюда, потому что у вас по прямой ссылке ничего не работает уже месяц и информация не обновляется. Что на 4пда, что тут 
https://kb.adguard.com/ru/technical-support/reporting-tool/agrd.io/report
![Screenshot_2022-07-29-06-56-20-731_com android chrome](https://user-images.githubusercontent.com/22351242/181679735-bd9d9b51-b142-482a-8ee5-32dad0e86dcf.jpg)

**Comment by ministr91** [comment]
![Screenshot_2022-07-29-06-57-05-799_com android chrome](https://user-images.githubusercontent.com/22351242/181679863-2e265729-b6ea-415b-844d-2246dd58f757.jpg)

**Comment by ameshkov** [comment]
Не понимаю, а по этой ссылке не переходит?
https://agrd.io/report

**Comment by ministr91** [comment]
@ameshkov по этой переходит, но на сайте то другая ссылка

**Comment by ameshkov** [comment]
А, понял. Это не супер принципиально - мы через месяцок новую базу знаний собираемся выкатывать вместо этой старой.
