### ISSUE TITLE
enabled HTTPS filtering by default for Soul browser

### ISSUE THREAD

**Issue by DiAnTTA** [AdguardTeam/AdguardForAndroid#4202]
### Prerequisites

- [x] I am running the latest version `3.6.9 (48)`
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Https filtering isn't enabled by default for Soul browser. 

### Proposed Solution
*add*:
```
com.mycompany.app.soulbrowser
```

### Additional Information

https://play.google.com/store/apps/details?id=com.mycompany.app.soulbrowser

**Comment by maxikuzmin** [comment]
@DiAnTTA your issue is in the works

**Comment by maxikuzmin** [comment]
@DiAnTTA  you're right, we'll be fixing that bug in the next updates.

**Comment by maxikuzmin** [comment]
@DiAnTTA  we solved your problem in the 3.6.11 Beta 1 update. Please update to this version and check it out. Let us know the result

**Comment by maxikuzmin** [comment]
@DiAnTTA for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by nightznero** [comment]
Does that mean now i can use HTTPS Filtering?
![Screenshot_20230127_001519_AdGuard](https://user-images.githubusercontent.com/61750641/214972253-7824fff8-2a1f-429b-adc4-fe18475e292c.jpg)
