### ISSUE TITLE
com.avito.android is partially broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4203]
@adguard-bot commented on [Fri Jul 08 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.avito.android](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.avito.android)
### Comment
Username: @neo1288
> При включенном фильтре часть картинок в Авито не видна

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/eEOVwlG.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/fAAWLtj.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.8 (46)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@Alex-302 commented on [Tue Jul 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1181684747)

@neo1288 У меня не повторяется, но возможную причину устранил.

---

@adguard-bot commented on [Wed Jul 13 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1182945926)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.avito.android](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.avito.android)
### Comment
> Adguard блокирует некоторые изображения товара/услуги на странице товара/услуги в приложении Avito

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/XhrAgQ9.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/zjb5DCZ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.8 (46)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>RU AdList: Counters
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | Отсутствуют

---

@neo1288 commented on [Thu Jul 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1183003614)

[Screenshot_2022-07-13-12-41-19-81_5228fc5d2ad2c517ecb981db677d9e34](https://user-images.githubusercontent.com/98756017/178703398-9a6c20aa-4495-4361-8d3a-94338c49fcf8.jpg)
П
[Screenshot_2022-07-13-12-41-09-59_5228fc5d2ad2c517ecb981db677d9e34](https://user-images.githubusercontent.com/98756017/178703407-5e9bf507-5396-4bd3-8f57-9af399d7c342.jpg)
Проблема никуда не ушла. Фильтры обновлены только что. 

---

@Sergey-Lyapin commented on [Wed Jul 13 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1183511870)

Не повторяется с теми же настройками, картинки загружаются нормально, рекламы нет

---

@neo1288 commented on [Thu Jul 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1183607175)

[Screenshot_2022-07-13-22-38-36-30_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/98756017/178817701-acdb88c1-6bb4-439e-ba1d-197d3afb47e6.jpg)
Какаято связь с вот этим. При добавлении разрешающего правила появляеются картинки на 2-3 страницах, включая текущую. Дальше опять нет.

---

@Alex-302 commented on [Thu Jul 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1183727643)

@neo1288 Проверьте после отключения всех групп фильтров, не отключая общую защиту. Если проблема уйдёт, включайте по одной группе с проверкой. Если найдёте ломающую - напишите нам.
Также будет желательно повторить проблему только с ломающей группой и сделать скрины журнала(там есть меню, где можно выключить отображение незаблокированных запросов). Только очистите его перед проверкой.

---

@neo1288 commented on [Thu Jul 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/123845#issuecomment-1184002845)

Неожиданный поворот - отключение всего, что только можно в программе, результатов не даёт. Изображения появляются только при отключении основной защиты. В журнали фильтрации заблокированных запросов при этом нет.

**Comment by Alex-302** [comment]
@neo1288 Запишите, пожалуйста, отладочный лог и отправьте на support@adguard.com (и напишите здесь, когда отправили, адрес почты указывать не нужно) Желательно поточнее указать время возникновения ошибки(незагрузившихся картинок)
https://kb.adguard.com/ru/android/solving-problems/log#debug

@Chinaski1

**Comment by neo1288** [comment]
Отправил в 12-15 по Москве. Время записи ошибки 12-12.

**Comment by maxikuzmin** [comment]
Since it's a duplicate, I'm closing this issue.

**Comment by maxikuzmin** [comment]
@neo1288 enabling DNS filtering or IPv6 traffic bypass fixes the issue. Please let me know the result

**Comment by neo1288** [comment]
> @neo1288 enabling DNS filtering or IPv6 traffic bypass fixes the issue. Please let me know the result

Enabling dns filtering fix problem.

**Comment by neo1288** [comment]
> @neo1288 enabling DNS filtering or IPv6 traffic bypass fixes the issue. Please let me know the result

Ipv6 bypass fix it too!
