### ISSUE TITLE
Userscripts cannot take effect in the built-in browsers of Tencent QQ and WeChat

### ISSUE THREAD

**Issue by leeyiding** [AdguardTeam/AdguardForAndroid#4204]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.46
- **Filtering mode:**
  - Auto
- **Device:**
  - Meizu 18s
- **Operating system and version:**
  - Android 11
- **Root access:**
  - Yes

Hello, I wrote a Userscripts to redirect a specific link. After testing, the script works in the Chrome browser, but in the built-in browsers of QQ (com.tencent.mobileqq) and WeChat (com.tencent.mm) It doesn't work, what's the reason?
Here is my script link
[https://raw.githubusercontent.com/leeyiding/AdGuardRules/main/scripts/redirect.js](https://raw.githubusercontent.com/leeyiding/AdGuardRules/main/scripts/redirect.js)

**Comment by maxikuzmin** [comment]
@leeyiding are you talking about the messengers QQ and WeChat? Do you use the web versions of these messengers? What browser do you use to try to use them?

**Comment by maxikuzmin** [comment]
@leeyiding ping

**Comment by leeyiding** [comment]
> 

Yes, I am talking about the messengers QQ and WeChat, I am using the APK version of Android, as far as I know the built-in browser used by these two software is based on the [Tencent X5 browser kernel](https://x5.tencent.com/)

**Comment by maxikuzmin** [comment]
@leeyiding probably the built-in browser does not support GM extensions, in this situation there is nothing we can do, you need to contact QQ or WeChat
