### ISSUE TITLE
Media playback (video or audio) stops when screen is off

### ISSUE THREAD

**Issue by PassionateG1t** [AdguardTeam/AdguardForAndroid#4205]
When adguard is enabled, when I turn off my phone to listen to a video on youtube or to a podcast on antennapod, it appears that the played media stops caching and eventually stops playing. 

When I turned off adguard, the issue was fixed. It might be the adguard dns filter responsible for this, who knows.

**Comment by maxikuzmin** [comment]
@PassionateG1t do you have a premium YouTube subscription?

**Comment by maxikuzmin** [comment]
@PassionateG1t what DNS server do you use?
