### ISSUE TITLE
Remove item

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4216]
Hello!
Please remove the annoying offer to install AdGuard VPN in the settings. Especially now that your VPN is banned in Russian Federation. This offer looks like a mockery and inducement to violate the law. Please remove the annoying advertising object from your settings.

**Comment by maxikuzmin** [comment]
We show information about VPN in the blocker because we want more users to get acquainted with it. We have only good intentions and do not suggest anyone to go against the law: the VPN is not banned in Russia. Our VPN works as usual and you can use it
