### ISSUE TITLE
AdGuard beta testing

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4217]
Здравствуйте!
В случае если я помогаю в разработке фильтров либо являюсь бета тестером, у вас на сайте указано, что вы готовы таких людей поощрять. Могу ли я поинтересоваться, на какой срок вы выдаёте лицензию таким пользователям?

**Comment by maxikuzmin** [comment]
Добрый день! Всю информацию о бета тестировании и подачи заявки вы можете найти по [ссылке](https://adguard.com/ru/beta.html) 
Также информацию о получении лицензии вы можете найти по этой [ссылке](https://adguard.com/ru/get-adguard-for-free.html)
