### ISSUE TITLE
The Tesla app is blocked with a "system down" error

### ISSUE THREAD

**Issue by haapyab** [AdguardTeam/AdguardForAndroid#4218]
I have a Samsung A10e and a Samsung Tab-A 8 (non-phone), both on Android 11, Adguard v3.6.9 (48). Everything works fine except for the Tesla app. 
This problem just started happening on 08/15/22 no changes to the devices. On the Tab-A no problem, on the A10e I intermittently get an error "system timed out". I tried, re-boot, uninstall/reinstall, etc. etc. 
What finally worked was to close the Tesla app, disconnect from the always on VPN, run the Tesla app and re-connect the VPN. Works every time until I get the time out message the next day. This happens on my wifes A10e at the same moment mine does.
Note: we turn our A10e's and Tab-A's off at night, reboot in the morning.
Let me know if you need any more info.
Thanks.
Andy

**Comment by maxikuzmin** [comment]
@haapyab at what intervals do you get the timeout message?

**Comment by haapyab** [comment]
Hi.
First off, I need to let you know that I have an Adguard ticket number
629524 as I did no know the proper place to report the problem.
Second the error is system timed out Or something to that effect., Not
down. I will try to capture the exact wording.
Third, it happens intermittently.
Fourth, I compared the A10e to the Tab-A Tesla settings and they are the
same. The devices are also on the same android versions 11.

If I can provide further info, let me know.

Thanks.
Andy

**Comment by maxikuzmin** [comment]
@haapyab could you be more specific about how often this error occurs? Once a week? Once a day? Could you still provide a link to the Tesla app as there are many such apps and they are different. It would also be nice if we had extended logs to see what is happening.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by haapyab** [comment]
When I use Tesla, I open it to check the Powerwall +, and close it when
done checking status.

This started on the 15th. I tried process of elimination - pressing the
session expired message, clearing cache, clearing data, rebooting,
uninstall, reinstall, it still gave me the session expired error.

Then I decided to stop Adguard and open Tesla and re started Adguard, it
worked from that point on until the next error. It happened several times
on the 15th and 16th as I kept trying it. Once on the 17th. After the 17th
event, it was good for the rest of the day and today it has been fine. Each
time I stopped Adguard, restarted Tesla and restarted Adguard.

Again, the 2 Tab-A devices did not fail, while both A10e devices did.

The Tesla app was downloaded from the Playstore. Search Tesla, only one app
comes up Tesla, Tesla, Inc. with the red Tesla logo.

I will go follow your instructions and get the logs in a subsequent email.

Thanks again.
Andy

**Comment by haapyab** [comment]
It may be awhile before I can get you the logs as the app is now working
consistently.

As I said, I go in and out of the app periodically throughout the day.

Perhaps the Tesla server update had something to do with this. Very
coincidental.

**Comment by maxikuzmin** [comment]
@haapyab I take it from your response in the mail that the problem is no longer relevant? Please let us know.

**Comment by haapyab** [comment]
Yes, it seems to have gone away.
The puzzling thing is that it occurred on the A10e devices, not the Tab-A
devices and the only fix that I could make was stopping Adguard protection,
restarting Tesla and restarting Adguard protection.

I appreciate your help and follow up.
Thank you.
Andy

**Comment by maxikuzmin** [comment]
@haapyab we're glad it worked out. Good luck!

**Comment by haapyab** [comment]
Thank you again.

**Comment by haapyab** [comment]
Update:

For 2 days now the A10e has been running the Tesla app without the “Session Expired” notification and the need to stop and start the Adguard protection.

I have started and closed the Tesla app multiple times during the day.

 

Coincidently, there was a Play Store update for the Tesla app today for both the A10e and Tab-A. 

After the update, it is still working.

 

Hopefully this  will continue to work.

 

I thank you for your support in this issue.

Andy
