### ISSUE TITLE
Расширить функционал встроенного файервола

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#4219]
Приветствую.

Мне кажется, в предыдущих версиях Adguard позволял видеть в Журнале фильтрации каким приложением был сгенерирован тот или иной исходящий запрос, а потом эта функция исчезла. Возможно ли ее вернуть либо сделать? 

Иногда возникает необходимость посмотреть от какого приложения тот или иной траффик.

Есть конечно другие готовые решения под Андроид типа Файервола от Grey Shirts, но "поженить" 2 приложения: Adguard и Firewall - для совместного использования невозможно. Придется отключать одно приложение, чтоб воспользоваться другим, что неудобно.

Заранее благодарю.

- [V ] I am running the latest version

**Comment by maxikuzmin** [comment]
@jbionic2016  в журнале фильтрации есть информация о том, каким приложением был сгенерирован тот или иной исходящий запрос, эта функция доступна с платной подпиской. В бесплатной версии эта информация отсутствует.

**Comment by maxikuzmin** [comment]
@jbionic2016 давайте разберемся, имеете ли вы бесплатную лицензию или платную, какие запросы вы имеете ввиду? В идеале было бы неплохо приложить снимок экрана, можно прикрепить прямо сюда. 

В бесплатной версии мы проводим фильтрацию только для браузеров, для обычных же приложений – не видно, как идет запрос и какой протокол внутри у запроса.

**Comment by jbionic2016** [comment]
У меня бесплатная. Раньше вроде такой функционал был в бесплатной тоже.
Какой смысл держать такой функционал в премиальный платной версии, если есть бесплатное приложение Firewall от Grey shirts?

**Comment by maxikuzmin** [comment]
@jbionic2016  на сколько мне известно, в этой области изменения не проводились. Такой функционал для бесплатной лицензии был всегда
