### ISSUE TITLE
VPN mode blocks all VOIP (UDP) traffic on OS 6.0.1

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#422]
1) It happens with both [Zoiper ](https://play.google.com/store/apps/details?id=com.zoiper.android.app&hl=ru)and [CSipSimple](https://play.google.com/store/apps/details?id=com.csipsimple&hl=ru): they can't register UDP transports in VPN mode while TCP ones goes normal. Zoiper try to play smart and falls back to TCP transport after few minutes, so it will be better to show honest CSipSimple.
2) I don't have DNS Filtering enabled and use Google DNS in my router.
3) CSipSimple screeen attached. First two accounts there are TCP, and last one failing is UDP.
The bug is gone swithcing to proxy mode instead of VPN.

![image](https://cloud.githubusercontent.com/assets/15856304/14245515/9ecd39a4-fa6a-11e5-9b7a-38fcd47d4186.png)

logs: FGD-169-28205

**Comment by ameshkov** [comment]
User comments (may be important):
> Alas, using ICE I can make csipsimple register, but any VOIP call failing.
> Could you made your VPN somehow completely not touch the phone IP address for UDP (not make it 172.16.16.1) to avoid double NAT problem?

> Connection to 188.246.162.118:5060 is failing reg.dc-tc.com due to timeout (no response from other side?)
> It seems you use personal subnet 172.16.16.1, so double NAT happens. I'll try to turn on ICE instead of STUN to bypass double nat.

**Comment by ameshkov** [comment]
Test build (changed VPN subnet to 172.16.209.xxx):
https://cdn.adguard.com/public/Adguard/github/AdguardForAndroid/issue422/adguard.apk

I guess we should add a low-level setting so that user could change it manually.

**Comment by ameshkov** [comment]
Seems the issue is not with the subnet. 

We should add these apps to default net exclusions:
com.zoiper.android.app
com.csipsimple

**Comment by Revertron** [comment]
Done.
