### ISSUE TITLE
Bypass QUIC traffic setting make IP block not work correctly .

### ISSUE THREAD

**Issue by lessload** [AdguardTeam/AdguardForAndroid#4220]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

Bypass QUIC traffic setting make IP block not work correctly 

- **AdGuard version:**
  - v3.6.9
- **Filtering mode:**
  - Local VPN 
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior

`8.8.8.8:433$network,app=com.instragram.android,important` should block instagram connect to TCP/UDP 8.8.8.8 even setting bypass quic.

### Actual Behavior

`8.8.8.8:433$network,app=com.instragram.android,important` block instagram connect to 8.8.8.8 only TCP

UDP still bypass the rule ( because of bypass quic ?)

**Comment by maxikuzmin** [comment]
@lessload issue in the works

**Comment by maxikuzmin** [comment]
@lessload that's right, if we bypass the connection, the rules do not apply, because the bypass is a higher priority

**Comment by maxikuzmin** [comment]
@issuex if we bypass the connection, the rules do not apply, because the bypass is a higher priority

**Comment by issuex** [comment]
User rule should overwrite all bypass rule. This is how app should be.
