### ISSUE TITLE
wolte and  vowifi not work when adguard active

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4223]
@elween07 commented on [Sat Aug 20 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127655)

### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.9

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

God know

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. <comment>

I use Chunghwa Telecom and Asia Pacific Telecom both of then vowifi not work and sometome event vowifi not work when adguard active, please check that, if need any log please let me know how to get that. my phone is asus zenfone9.  

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by elween07** [comment]
Hi,
here is log file for adguard, I test 12:34, when adguard active vowifi is lost and when adguard deactivate vowifi is  ok.
others  log file 133337 is my current setting, I deactivate adguard on most of service and app, only reserve on app had lot of ad on it, that work for me. so if you can tell me which app and service has something to do with vowifi and set deactivate on adguard, I think that's a good solution too.

Thanks 

[adguard_logs_3.6.48_2608_123452.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9430143/adguard_logs_3.6.48_2608_123452.zip)
[adguard_logs_3.6.48_2608_133337.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9430146/adguard_logs_3.6.48_2608_133337.zip)

**Comment by maxikuzmin** [comment]
@elween07 we're looking into the problem. Please wait

**Comment by maxikuzmin** [comment]
@elween07 did you send the logs? We didn't get anything

**Comment by maxikuzmin** [comment]
@elween07 please try updating to version 3.6.10 and repeat the problem. Is it still repeating with the new version?

**Comment by elween07** [comment]
No, 3.6.10 had same issue.
Now I turn off adguard in com.qualcomm.qti.cne at app management then look good so I will keep the setting, if you need more log please give me the test plan I can do that.

thanks

**Comment by maxikuzmin** [comment]
@elween07 I found an earlier mention of this problem. At this [link](https://github.com/AdguardTeam/AdguardForAndroid/issues/2550) you should find a solution to the problem. Please let me know if everything worked for you

**Comment by elween07** [comment]
I use Chunghwa Telecom LDM and excluded  
221.120.20.1/24
221.120.23.1/24

it NOT work for me

**Comment by maxikuzmin** [comment]
@elween07 did disabling adguard in com.qualcomm.qti.cne in app management help you?

**Comment by elween07** [comment]
Yes, everything is good

**Comment by maxikuzmin** [comment]
@elween07 glad to hear it. I'm closing the issue then.
