### ISSUE TITLE
org.thoughtcrime.securesms - link preview is broken in Signal messenger

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4226]
@adguard-bot commented on [Thu Aug 18 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dorg.thoughtcrime.securesms)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/yrJbSjz.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/7bZOf6a.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.6.9 (48)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing third-party cookies (0)
DNS filtering: | server: `quic://dns.adguard-dns.com`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@v-ba commented on [Sat Aug 20 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1221313958)

Also blocks preview for https://www.pravda.com.ua/news/2022/08/20/7364116/

---

@Alex-302 commented on [Tue Aug 23 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1224633697)

@v-ba Could you please describe how to reproduce this issue?
And what causes it - filters or DNS filtering?

---

@v-ba commented on [Wed Aug 24 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1224897548)

> @v-ba Could you please describe how to reproduce this issue? And what causes it - filters or DNS filtering?

Enable AdGuard for android. Copy the [link](https://www.pravda.com.ua/news/2022/08/20/7364116/) and paste it to message field in Signal messenger. Signal will try to load preview and will show message like “no preview available” above the pasted link like on the first screenshot. Then pause AdGuard. Try the same. Now, preview is loaded succesfully like on the second screenshot. 

---

@v-ba commented on [Wed Aug 24 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1224912268)

> 

Niether disabling of DNS, nor of some filters does not affect the discribed behaviour. At least for me. Only pausing Adguard allows to load a preview. 

---

@Alex-302 commented on [Wed Aug 24 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1225325872)

Checked on two devices - no preview or the message like on your first screenshot.
Is something should be changed in default settings?

---

@v-ba commented on [Wed Aug 24 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1225609091)

https://user-images.githubusercontent.com/75579352/186410442-86c8199c-41bb-401d-b65a-010d1332bb79.mp4

What default settings do you mean? 

---

@Alex-302 commented on [Wed Aug 24 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127477#issuecomment-1225747426)

> What default settings do you mean?

App's settings. But I understand now. Can't reproduce on my device:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/186434097-d5f4e1e9-1f0f-47de-b8d1-c1cc016b0ba9.png)

</details>

**Comment by maxikuzmin** [comment]
@v-ba we're looking into the problem. Please wait

**Comment by v-ba** [comment]
> @v-ba we're looking into the problem. Please wait

Looks like the issue is gone with the last Adguard update to 3.6.10.

**Comment by maxikuzmin** [comment]
@v-ba great news! Good luck!

**Comment by v-ba** [comment]
@maxikuzmin, I regret but the issue is back. Only disabling HTTPS-filtering or Adguard at all makes it possible to load a preview now again.
