### ISSUE TITLE
Content Blocking in some apps also block in other apps

### ISSUE THREAD

**Issue by issuex** [AdguardTeam/AdguardForAndroid#4227]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.9
- **Filtering mode:**
  - Local VPN
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior

Content Blocking by `||bit.ly^$app=com.instagram.android,important` should only block IG app from connect `bit.ly/xxx`.

### Actual Behavior

Content Blocking by `||bit.ly^$app=com.instagram.android,important` block IG app from connect `bit.ly/xxx` but after copy link `bit.ly/xxx` to open in Firefox, it also block Firefox to access `bit.ly/xxx`

### Additional Information

Need to wait long time to able access `bit.ly/xxx`

**Comment by maxikuzmin** [comment]
@issuex can you reproduce the steps and take screen shots so we can see what's going on?
Please send screen shots on email devteam@adguard.com

**Comment by maxikuzmin** [comment]
@issuex any news?

**Comment by maxikuzmin** [comment]
@issuex the issue is closed. If you can reproduce the steps and take screen shots, you can reopen the issue.

**Comment by issuex** [comment]
It randomly appear, hard to reproduce the steps.  When i to go `bit.ly/xxx` in firefox it got blocked and in the Adguard log show as i try access `bit.ly/xxx` by `com.instagram.android`. not sure why?
