### ISSUE TITLE
Telegram app freezes with Adguard enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#423]
User encounters infinite loading when starting Telegram with enabled Adguard:
http://i26i.imgup.net/pic5959.png

Originally from: http://forum.adguard.com/.php?10264

**Comment by ameshkov** [comment]
Duplicate

**Comment by Revertron** [comment]
The screenshot is from Windows.

**Comment by ameshkov** [comment]
@vbagirov windows eh?
