### ISSUE TITLE
Can't Update Adguard for Android to latest Version

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4230]
I tried updating Adguard For Android to version 3.6.10 which said it was updating but did not update at all after I opened Adgaurd back up and just said the same thing update.
![Screenshot_20220826-121608_AdGuard](https://user-images.githubusercontent.com/96619913/186958033-d1d112e8-e64c-4783-b22a-a18969210a2b.jpg)

**Comment by artemiv4nov** [comment]
This issue has already been fixed, please re-check the update

**Comment by Batman2814** [comment]
worked
