### ISSUE TITLE
AdGuard breaks connection to Proton VPN

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#4234]
### Issue Details

- **AdGuard version:**
  - 3.6.10
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - POCO X3 Pro
- **Operating system and version:**
  - Android 12L
- **Root access:**
  - Yes

### Expected Behavior

Connecting to Proton VPN is seamless.

### Actual Behavior

The connection to Proton VPN goes on forever, but it never connects.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

When AdGuard protection for Proton VPN is disabled, the connection works correctly. Sent logs to devteam@adguard.com.

**Comment by maxikuzmin** [comment]
@rakleed have you tried adding AdGuard to your Proton VPN exclusions?

**Comment by rakleed** [comment]
@maxikuzmin are you talking about split tunneling? I tried adding AdGuard to the exceptions in Proton VPN, and now Proton VPN connects normally. But why, if AdGuard works as a proxy and not a VPN?

**Comment by maxikuzmin** [comment]
@rakleed you may have selected VPN mode on AdGuard, so there was an app conflict. Only one VPN can work on Android

**Comment by rakleed** [comment]
@maxikuzmin In the description of the issue, I indicated that I have the HTTP Proxy (Auto) filtering mode.

**Comment by maxikuzmin** [comment]
@rakleed you may also have configured the PROTON VPN on the wrong port

**Comment by rakleed** [comment]
@maxikuzmin why did you close the issue?

In Proton VPN, I don't see any port settings anywhere. Also, I use the OpenVPN TCP protocol, since all others are blocked in Russia.

**Comment by rakleed** [comment]
@maxikuzmin @ameshkov please take a look

**Comment by ameshkov** [comment]
@rakleed if you don't add it to exceptions, there will be an infinite loop (Proton -> AdGuard -> Proton -> etc).

**Comment by rakleed** [comment]
@ameshkov why aren't AdGuard in auto proxy mode and Proton VPN compatible?

In the help https://kb.adguard.com/en/android/faq#vpn you just recommend using the proxy mode for compatibility with third-party VPN apps, but nowhere does it mention that in this mode AdGuard may be incompatible with a third-party VPN. Why?

**Comment by ameshkov** [comment]
It can, but you should not try to filter Proton VPN app itself to avoid infinite loops

**Comment by rakleed** [comment]
So maybe you should disable Proton VPN filtering by default to avoid this issue?

**Comment by ameshkov** [comment]
We probably could add it to the default list of exceptions. On the other hand, what if the app tracks you and this way you won't see anything.

@maxikuzmin we probably need a separate task where we track all apps that need to be excluded + the explanation of why we do that.
