### ISSUE TITLE
Snapchat Business domains not opening with AdGuard DNS 

### ISSUE THREAD

**Issue by kamharry** [AdguardTeam/AdguardForAndroid#4235]
https://business.snapchat.com/
https://ads.snapchat.com/select-business?r=create
https://profile.snapchat.com/?lang=en-US&_sid=PUBLICPROFILE

All these domains and similar are stuck at loading with adguard dns and adguard Android app .. but when we disable app protection and remove dns then these sites work perfectly

**Comment by maxikuzmin** [comment]
@kamharry we're looking into the problem

**Comment by jellizaveta** [comment]
Fixed the loading of the site in the browser, but unfortunately with the DNS enabled `ads-interfaces.sc-cdn.net` rule will block the page loading. Unfortunately, we can't remove this rule, as this resource is used to show ads on many sites. Please add `ads-interfaces.sc-cdn.net` domain to exceptions from DNS filtering or disable DNS filtering.

**Comment by kamharry** [comment]
The thing is i use adguard dns at router level 🥲

**Comment by jellizaveta** [comment]
You can use [Private AdGuard DNS](https://adguard-dns.io/kb/private-dns/overview/) to unblock the domain or use [Non-filtering DNS](https://adguard-dns.io/kb/general/dns-providers/#non-filtering)

**Comment by Alex-302** [comment]
Private DNS will solve your problem - you can block or unblock anything you want.
