### ISSUE TITLE
Filter auto-update problem

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#4237]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

### Issue Details

Filters are being auto-updated only after every system startup and then they freeze until I reboot the system or update them manually by hitting the “Check for updates” button at the top-right corner of the app’s home screen. The longest period I stayed patient in order to confirm that filters won’t update automatically was 7 days. I tested a lot of configuration tweaks trying to figure out what’s wrong (e.g. changing “Filter auto-update period” or “DNS Filtering” settings, turning on and off different filter groups, “Update on Wi-Fi only”, “Stealth mode” or “Firewall”, resetting “Low-level” and “Firewall” settings, etc.), but nothing worked. I also confirmed that all app permissions are active and none has been rejected, including unlimited battery and background data access settings even in data saver mode. Since at least May, AdGuard used 0B of background data, as verified by both Android and AdGuard Firewall report.

- **AdGuard version:**
  - v3.6.10
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy A51
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior

Filters update automatically according to applied settings (every 12 hours).

### Actual Behavior

Filters auto-update exclusively after system reboot (if set period has passed), otherwise they can only be updated manually.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Here’s my configuration file: https://bit.ly/3BfBdkz

**Comment by maxikuzmin** [comment]
@DimitrisKalaboukas we're looking into the problem

**Comment by maxikuzmin** [comment]
@DimitrisKalaboukas any news?

**Comment by DimitrisKalaboukas** [comment]
@maxikuzmin I’ll reach developer team via email, when I have relevant data to submit.

**Comment by DimitrisKalaboukas** [comment]
@maxikuzmin The issue has been solved in version 4.0.

**Comment by DimitrisKalaboukas** [comment]
@maxikuzmin The problem reoccurs periodically in versions 4.1 and 4.2, although I have applied all techniques recommended in [the respective troubleshooting guide](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/). Sometimes the update schedule is performed normally, but very often it unreasonably lags for a lot of days. The behavior is exactly the same in all my family’s Android devices from different manufacturers.
