### ISSUE TITLE
Problems with VoWiFi on Realme GT 2 Pro

### ISSUE THREAD

**Issue by boyedarat** [AdguardTeam/AdguardForAndroid#4244]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
v3.6.10
- **Filtering mode:**
Local VPN
- **Device:**
Realme GT 2 Pro
- **Operating system and version:**
Android 12
- **Root access:**
No

### Expected Behavior
When AdGuard is enabled and my phone is connected to WiFi, VoWiFi should be active and working.

### Actual Behavior
When AdGuard is enabled and my phone is connected to WiFi, VoWiFi stops working and it switches to VoLTE.
If AdGuard was disabled, VoWiFi works again as expected.

### Screenshots
None

### Additional Information
Activity logs attached. Issue occurred approximately 1.23pm.
[adguard_logs_3.6.51_1709_132420.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9591007/adguard_logs_3.6.51_1709_132420.zip)

**Comment by vitek29** [comment]
Hope this might help you with the problem #2550

**Comment by maxikuzmin** [comment]
@boyedarat indeed, @vitek29 is right. This link should help you. Let me know the result please.

**Comment by boyedarat** [comment]
@vitek29 Thanks!

Was able to get VoWiFi working with this setting:

1. Open AdGuard -> Go to Settings -> Advanced -> Low-level
2. Find `pref.ipv4.routes.excluded` and tap on it
3. Add the following new lines there:
> // Maxis VoWiFi Service
> 202.75.146.40/29

@maxikuzmin was able to receive and make VoWiFi calls using the above settings with my cellular provider.

Please add the above to AdGuard defaults, so I don't have to manually add it in future. Thanks!

**Comment by maxikuzmin** [comment]
@boyedarat great, thanks! Issue closed.
