### ISSUE TITLE
The "HTTPS filtering" menu lacks an option to recognise if a certificate was installed outside of AdGuard's wizard

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#4247]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.10 (51)
- **Filtering mode:**
  - Local HTTP Proxy, manual
- **Device:**
  - Windows Subsystem for Android
- **Operating system and version:**
  - Android 12L
- **Root access:**
  - No

While testing how well Android apps work in *Windows Subsystem for Android*, I realised there were some problems that caused considerable problems with getting AdGuard to at least technically speaking run. In particular, WSfA lack any VPN functionality (except for Private DNS). Additionally, when Android apps request to open the Android security settings, WSfA forces them to load the Windows security settings instead.

Although I'd perfectly understand it if you guys were to consider WSfA support to be a fruitless cause, it nevertheless exposed an unusual problem in general:

If the "HTTPS filtering" turn-on wizard gets interrupted after saving the certificate, and the same certificate is later installed from the system settings, AdGuard fails to recognise that it has been installed.

To reproduce on WSfA:
1) Do a fresh installation of `adguard.apk`
2) Attempt to turn on HTTPS Filtering, which opens the wizard for it.
3) After saving the certificate, WSfA opens the Windows security settings, and the app turns HTTPS Filtering off again.
4) Create a Windows shortcut that leads to `%LOCALAPPDATA%\Microsoft\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\WsaClient.exe /launch wsa://com.android.settings`. This will allow opening the actual Android settings in WSfA.
5) Follow `https://support.google.com/pixelphone/answer/2844832` to install the certificate that the wizard generated.
6) Open AdGuard again.
7) It still treats HTTPS Filtering as off and thinks that the certificate hasn't been installed.

To reproduce on a physical phone, I presume you can simply force-quit the wizard while in the certificate settings, and skip step 4.

### Expected Behavior

If an AdGuard-generated certificate has been installed after it had been saved but the wizard was interrupted, AdGuard's settings would acknowledge that it has been installed.

### Actual Behavior

AdGuard does recognise that an AdGuard-generated certificate has been installed without the wizard. Possibly with a "Check for installed AdGuard certificates" option.

### Screenshots

I'm currently unsure which things that'd be most useful to take screenshots of.

### Additional Information

Inter-app recognition between different apps in WSfA is rather shoddy and likely to be *very* buggy, especially when it comes to system apps.

**Comment by maxikuzmin** [comment]
@DandelionSprout this feature will be redesigned in version 4.0, no exact release date is known yet, but it will be very soon. Please wait for version 4.0. If this problem occurs in version 4.0, you can reopen this issue
