### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by nerd-architect** [AdguardTeam/AdguardForAndroid#4249]
We all know about the efforts that go into making suck apps work Adguard For Android was the best vpn on android loved it but since i live in iran i cant connect to it there is two problems 1 you can't sign in from a new account 2 even if you use and other vpn on sign in and find servers when you press connect it does absolutely nothing.
![Untitled-1](https://user-images.githubusercontent.com/97024936/193487546-e90187b9-8adc-42c6-8b8e-87b8796867ae.jpg)

**Comment by maxikuzmin** [comment]
@nerd-architect  could you be more specific about what exactly you see when you try to connect? Is there an error? It would be nice to record a video of the screen and attach it here. Either describe the steps and attach a screenshot of the error you see. You also mentioned "other VPNs". Maybe when you were experimenting, you connected a different VPN profile, that might have had some effect. As I know, VPN profiles on your phone are switched automatically, however, try to close other VPNs completely, or reboot your phone, and check again trying to connect to the servers

**Comment by maxikuzmin** [comment]
@nerd-architect the issue is closed. If you have a recurring problem in the future and more information about the problem becomes available, you can reopen the issue
