### ISSUE TITLE
Now breaks Google Image Search results/regular Google search results layout and UI

### ISSUE THREAD

**Issue by richaardvark** [AdguardTeam/AdguardForAndroid#4250]
Recent update now seems to break Google Image Search search results as well as regular Google search results when viewed in mobile view using Chrome for Android. With image search results the header is cut off and columns become a narrow weird dimension with the right column halfway cut off as you scroll down. For regular Google search results the header section (where you can select All, Images, Maps, Shopping, etc.) begins to flicker spastically now as you scroll down the page. 

- **AdGuard version:**
  - 4.0 nightly 35 (79)
- **Filtering mode:**
  - HTTPS Filtering, local VPN
- **Device:**
  - OnePlus 8 (IN2015)
- **Operating system and version:**
  - OxygenOS/Android 12
- **Root access:**
  - no

WITHOUT AdGuard enabled:
![Screenshot_2022-10-05-05-11-45-41_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41244847/194047071-d7e3560a-4f45-4079-9b0b-6270f485c81f.jpg)

WITH AdGuard enabled:
![Screenshot_2022-10-05-05-12-20-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41244847/194047188-3e6634ed-32f5-48c5-87af-bd6ab9105456.jpg)

**Comment by maxikuzmin** [comment]
@richaardvark I don't have this problem repeated. Could you unload your settings and email them to devteam@adguard.com? 
Also clarify how many filters are enabled now? Are there any additional filters installed?

**Comment by richaardvark** [comment]
> @richaardvark I don't have this problem repeated. Could you unload your settings and email them to [devteam@adguard.com](mailto:devteam@adguard.com)? Also clarify how many filters are enabled now? Are there any additional filters installed?

Hello, I have emailed my exported settings as requested. 
I have these 13 filters enabled:
  • AdGuard Base filter
  • AdGuard Mobile Ads filter
  • AdGuard Tracking Protection filter
  • AdGuard URL Tracking filter
  • Peter Lowe's Blocklist
  • AdGuard Social Media filter
  • Online Malicious URL Blocklist
  • NoCoin Filter List
  • AdGuard Annoyances filter
  • Adblock Warning Removal List
  • I don't care about cookies
  • Web Annoyances Ultralist
  • Fanboy's Annoyances

**Comment by richaardvark** [comment]
> @richaardvark I don't have this problem repeated. Could you unload your settings and email them to [devteam@adguard.com](mailto:devteam@adguard.com)? Also clarify how many filters are enabled now? Are there any additional filters installed?

Hello, I have emailed my exported settings as requested. 
I have these 13 filters enabled:
  • AdGuard Base filter
  • AdGuard Mobile Ads filter
  • AdGuard Tracking Protection filter
  • AdGuard URL Tracking filter
  • Peter Lowe's Blocklist
  • AdGuard Social Media filter
  • Online Malicious URL Blocklist
  • NoCoin Filter List
  • AdGuard Annoyances filter
  • Adblock Warning Removal List
  • I don't care about cookies
  • Web Annoyances Ultralist
  • Fanboy's Annoyances

Thank you for your help!

**Comment by richaardvark** [comment]
No updates? :-/

**Comment by maxikuzmin** [comment]
@richaardvark I don't have it repeated even with your settings. 
Have you tried disabling DNS, without DNS is the same problem?

**Comment by richaardvark** [comment]
> @richaardvark I don't have it repeated even with your settings. Have you tried disabling DNS, without DNS is the same problem?

I do have a warning message under DNS that I'd never noticed before about Android Private DNS conflicting with AdGuard DNS. The problem is still persisting though when I have all DNS disabled/turned off. :(

![Screenshot_2022-10-14-14-37-40-09_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/41244847/195928677-52cf5610-2921-4fb0-8069-7c7db1db72a9.jpg)

![Screenshot_2022-10-14-14-37-51-62_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/41244847/195928722-04520e36-498c-43d3-a5ad-642296394896.jpg)

![Screenshot_2022-10-14-14-37-55-47_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/41244847/195928787-d052b459-44ba-4653-8a90-b4607158e0f7.jpg)

![Screenshot_2022-10-14-14-42-52-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41244847/195929066-3557f7ff-1a8f-4c3e-9781-2900b0e92f31.jpg)

**Comment by maxikuzmin** [comment]
@richaardvark try with our filters only. Sometimes it happens that one filter conflicts with another because of its own rules. Most often the problem is this. Let me know about results

**Comment by maxikuzmin** [comment]
@richaardvark any news?

**Comment by richaardvark** [comment]
> @richaardvark any news?

Hi there, sorry for the delay. Removing non-AdGuard filters did the trick!  I will stick with only AdGuard filters from now on. I can close this issue now.
