### ISSUE TITLE
Proxy for AdGuard VPN

### ISSUE THREAD

**Issue by Anabh28** [AdguardTeam/AdguardForAndroid#4254]
Hello I want a proxy for adguard vpn please help me I am a Windows and web programmer 😭I can't wait connect to every site some of them blocked in my country

**Comment by maxikuzmin** [comment]
@Anabh28 how exactly do you see it? Directing traffic to a VPN? Or direct VPN traffic to another proxy?

**Comment by maxikuzmin** [comment]
@Anabh28 I'm closing the issue for now. If new questions arise, you can reopen the issue
