### ISSUE TITLE
Приложение с недавних под не разрешает вставить юрл страницы и предлагает вручную составить отчёт.

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4255]
![Screenshot_20221013-063005](https://user-images.githubusercontent.com/34476664/195494073-d87d5e03-fbee-4b7b-b0d6-5b02899e89b1.jpg)

**Comment by maxikuzmin** [comment]
@Spok1 спасибо! Вопрос в работе

**Comment by maxikuzmin** [comment]
@Spok1 проблема всё еще актуальна? Потому что у меня сейчас ваш адрес добавляется без каких-либо проблем.
Возможно были временные неполадки

**Comment by Spok1** [comment]
5 дней назад было актуально, сейчас исправно вставляются юрл. Реагировать скорей нужно.
