### ISSUE TITLE
Certificate Authority installed notification

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdguardForAndroid#4256]
Hello,

Why does the 'Certificate Authority installed by an unknown third party' notification appear?

I factory reset my phone for a family member. I installed Adguard and the certificate for HTTPS filtering and that notification appears. 
On my account nothing pops up (Google account) but with my family member it appears.

We have different Adguard accounts as well.

(Tried to ask on Telegram but no reply)

![PXL_20221015_143204782.jpg](https://user-images.githubusercontent.com/72349391/195992699-a5d2b72c-2d05-4161-a32c-dbe55d623dfe.jpg)

**Comment by maxikuzmin** [comment]
@Perfectlynk maybe the certificate was installed incorrectly. Try to remove the certificate via Network -> HTTPS Filtering -> Security Certificate -> Delete. Then you will get a notification on the main screen that your HTTPS filtering is not working and you can reinstall the certificate. Or just uninstall AdGuard and reinstall it. Please let me know about result

**Comment by maxikuzmin** [comment]
@Perfectlynk this notification will be shown if at least one user certificate (including ours) is installed on the system. If the user has only our user certificate installed, it can be simply wiped and ignored. There is no way to remove it, if our HTTPS-filtering is used - it will still appear after device reboot
