### ISSUE TITLE
Instagram photo is deleted for violating community rules with Adguard

### ISSUE THREAD

**Issue by cathan44** [AdguardTeam/AdguardForAndroid#4257]
While using adguard for android (adguard and content blocker for s), whenever i post a photo on instagram it gets flagged and removed for going against community guidelines. Turning adguard off/posting from desktop works. 

- **AdGuard version:** v2.7.0 & v3.6.10 (51)

- **Filtering mode:** Local VPN

- **Device:** Huawei P30
 
- **Operating system and version:** EMUI 12.0.0.134(C431E3R3P2)

**Root access:** No

### Expected Behavior

I expected to post a photo and for it go live

### Actual Behavior

I posted a photo and it got removed and flagged by Instagram as going against community guidelines.

### Screenshots

[https://i.imgur.com/1ZTgWoY.jpg](url)

**Comment by maxikuzmin** [comment]
@cathan44 as far as I know, Instagram only blocks a photo if it's against the rules. The blocking doesn't depend on traffic filtering. If you turn off AdGuard completely, this same photo is added without any problem? 
Can you record a video of the screen and repeat those steps that cause the photo to be deleted? Send it to devteam@adguard.com

**Comment by maxikuzmin** [comment]
@cathan44 any news?

**Comment by maxikuzmin** [comment]
@cathan44 for the moment, I'm closing this issue. You can reopen the issue in the future if the problem persists
