### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by jeffdumcum** [AdguardTeam/AdguardForAndroid#4258]
- 

### Problem Description
Right now, AdGuard for Android is not Material You color themed

### Proposed Solution
Add material you color theming

### Alternatives Considered
there are no alternatives to Material You

### Additional Information
It would make it look cool

**Comment by maxikuzmin** [comment]
@jeffdumcum thing is, green is AdGuard's corporate color. Anyway, we'll discuss the possibility of changing the color theme, thanks

**Comment by srccrow** [comment]
You will still be green Adguard, 

https://android-developers.googleblog.com/2022/02/material-you-coming-to-more-android.html

You will have to add a vector, and that will only be a feature on Android 13.

This is an example of how to do it for another app:

https://github.com/Kunzisoft/KeePassDX/pull/1404/commits/542daba20627ec47f7291b4adfc3208681968bb4#diff-dfc2d7560f38e02739eb7e67a1faefa0f60b6fa0c5c1faa614febbc952b95a5d
