### ISSUE TITLE
Can't set Custom NextDNS Configuration as DNS Provider in Android

### ISSUE THREAD

**Issue by akayashi-mika** [AdguardTeam/AdguardForAndroid#4259]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.10
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy A71
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior

Adguard will accept and use my own Custom NextDNS Configuration in the "My DNS servers" section when I add `tls://[redacted].dns.nextdns.io`

### Actual Behavior

Adguard returns the error `No connection`

### Screenshots

<details>Adguard throws error when I enter my custom NextDNS Configuration.<summary>Screenshot:</summary>

![Screenshot_20221023-151437_AdGuard](https://user-images.githubusercontent.com/78289561/197379317-1cb6616b-9663-4027-ae53-b7413c916d70.png)

</details>

### Additional Information

My custom NextDNS Configuration works fine in my other phone, and my laptop (All are using Adguard). Earlier, Adguard can still connect to NextDNS. But when I edited my DNS Server details to change my device name, it wouldn't save my server anymore. I tried just copying the endpoint without naming it, but it still wouldn't work. 

**Note**: The endpoint in the screenshot is just a temporary endpoint I made

**Comment by maxikuzmin** [comment]
@akayashi-mika for the moment, I'm closing this issue. You can reopen the issue in the future if the problem persists
