### ISSUE TITLE
Skype or Hangouts video calls statistic in the firewall is overestimated

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#426]
Basically what happens is that when I use Skype or hangouts to make audio
or video calls the app over estimates the data used. Even if I would only
speak for a few minutes the app claims I used way more data than I have
actually used.

I've attached the screenshot of the data from the firewall and another
screenshot of the Android data usage.

![image](https://cloud.githubusercontent.com/assets/15856304/14278266/6a877bee-fb2f-11e5-9f8a-6b859ec9ac08.png)
![image](https://cloud.githubusercontent.com/assets/15856304/14278275/7ba8cd4c-fb2f-11e5-8fee-889ce9ea776e.png)

WVP-908-38536

**Comment by ameshkov** [comment]
Please ask user to try the latest beta version.

We've fixed firewall stats calculation there.
