### ISSUE TITLE
Empty/blank space on all pages (efsyn.gr - excl. home page)

### ISSUE THREAD

**Issue by Gittyperson** [AdguardTeam/AdguardForAndroid#4260]
AdGuard 3.6.10 (51) (Premium)
Local VPN
Realme 7 Pro
Android 12 (September 2022 update)
Root access:  No

### Expected Behavior

No large white spaces.

### Actual Behavior

On all page articles (not the main/home page), a large white space appears between the article's titles and the main text. Example:

https://www.efsyn.gr/ellada/ekpaideysi/364385_nai-sti-morfosi-ohi-stis-oppi-apo-foitites-kai-mathites-stin-athina

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot](https://user-images.githubusercontent.com/7165208/197521580-45407fbd-7757-4db5-a32d-3e9dda9f5f84.jpg)

</details>

### Additional Information

Tried with the default settings. Also tried with additional filterlists, and tried disabling certain filterlists. Same results. Issue only goes away by disabling AdGuard (annoying ads appear in that space, of course). HTTPS Filtering is enabled (also tried disabling it).

Issue does not occur on desktop browser with similar AdGuard filterlists (Pale Moon + uBO - AdG extension not available).

**Comment by jellizaveta** [comment]
@Gittyperson Hello! Fixed in https://github.com/AdguardTeam/AdguardFilters/commit/8efc282942d146584fefa99c3924b386248f65dc, filters update should be available in 1-2 hours. After the filter update, please clear your browser cache, and check the site again. If the issue repeats, feel free to mention me.
