### ISSUE TITLE
RBL MoBank flags Adguard User Certificate as Malicious and doesn't allow usage

### ISSUE THREAD

**Issue by Jinestic** [AdguardTeam/AdguardForAndroid#4263]
### Issue Details

![IMG20221026201228_2](https://user-images.githubusercontent.com/35566052/198057996-74013cee-bf7e-465c-b4b6-89fbb3a693eb.jpg)

This gets flagged even when RBL is excluded from Adguard filtering. We can not use RBL app as long as Adguard CA certificate is installed, even if we uninstall Adguard app! The only way to bypass this is to remove Adguard User Certificate, which limits Adguard functionality quite a lot.

RBL MoBank (Indian Bank) App-> https://play.google.com/store/apps/details?id=com.rblbank.mobank&hl=en_IN&gl=US

- **AdGuard version:**
  -  3.6.51
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Mi 11x/POCO F3
- **Operating system and version:**
  -  Android 11/MIUI 12.5
- **Root access:**
  -  No

**Comment by sfionov** [comment]
Sound like a bug in banking app, not AdGuard

**Comment by Jinestic** [comment]
Not a bug. They have intentionally put this check.

**Comment by sfionov** [comment]
However, it is obviously an issue in banking app - it should check that connection is actually MITMed, not just check that user CA installed.

**Comment by maxikuzmin** [comment]
@Jinestic please contact the bank's support
