### ISSUE TITLE
Some user rules not working

### ISSUE THREAD

**Issue by issuex** [AdguardTeam/AdguardForAndroid#4264]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.6.10
- **Filtering mode:**
  -  Local VPN
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - No

### Expected Behavior

Adguard should block `XXX.XXX.XXX.XXX:80` or `http://` when user rule is
```
XXX.XXX.XXX.XXX:80$network,app=com.xxx.xxx
@@||some-domain-is-xxx-ip.com^$app=com.xxx.xxx
```

### Actual Behavior

In the real test when `some-domain-is-xxx-ip.com` is `XXX.XXX.XXX.XXX` IP
Adguard not block `http://` from `com.xxx.xxx` App.

My purpose is i want to block `http://` but allow `https://` to prevent some infomation that can leak to ISP.

**Comment by maxikuzmin** [comment]
@issuex please try this, it should work. Let me know about results.
``http://example.org/^$document,app=com.xxx.xxx``
``[http://xxx.xxx.xxx.xxx:80](http://xxx.xxx.xxx.xxx/)^$document,app=com.xxx.xxx``

**Comment by maxikuzmin** [comment]
@issuex any news?

**Comment by maxikuzmin** [comment]
@issuex for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
