### ISSUE TITLE
Make requests blocked by DNS servers in "DNS filtering" show up as "Blocked" in the filtering log

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#4270]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (3.6.9)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

When DNS blocking is enabled, the filtering log doesn't seem to consider DNS requests blocked by the DNS server as being "Blocked" for the purposes of the "Filter requests" feature, sometimes making it harder to detect why an app/site isn't working correctly.

### Proposed Solution

In "Filtering log", mark DNS requests that resulted in `A, 0.0.0.0` and `AAAA, ::` with the "Blocked" status or something similar, and with some kind of colour (e.g. the same red used for domains that are "Blocked" by normal filterlists).

### Alternatives Considered

None that'd seem practical to consider.

### Additional Information

None that I was aware of at the time of writing.

**Comment by maxikuzmin** [comment]
@DandelionSprout please wait for version 4.0, as we have reworked the filtering log there. This will happen soon. But if you have questions in version 4.0, you can reopen the issue in the future
