### ISSUE TITLE
Consider excluding com.irobot.home app

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardForAndroid#4273]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

`https://play.google.com/store/apps/details?id=com.irobot.home&hl=en&gl=US`
It seems the app has long been broken by AG:
https://github.com/AdguardTeam/AdguardFilters/issues/11075
https://github.com/AdguardTeam/AdguardFilters/issues/51195
https://forum.adguard.com/index.php?threads/resolved-irobot-roomba-home-app-doesnt-find-robot-while-adguard-is-on.38498/
https://forum.adguard.com/index.php?threads/iot-smart-home-apps-increasingly-breaking-due-to-adguard.26550/
https://www.reddit.com/r/roomba/comments/pcw9ly/comment/haoyxhr/
https://www.reddit.com/r/roomba/comments/uhspic/comment/i78rx11/
(Below this line are Japanese reports I could find)
https://katakake.com/post/10569#footnote_11_10569
https://twitter.com/srnkiri/status/1574924223080206336
https://twitter.com/thisissuree/status/1501438252032880645
https://twitter.com/emg_ty/status/1477228182319529986
https://twitter.com/progremaster/status/1308367871836188673
https://wikiwiki.jp/nanj-adguard/%E4%B8%8D%E5%85%B7%E5%90%88%E3%83%BB%E5%BA%83%E5%91%8A%E7%9B%B8%E8%AB%87%E6%89%80%EF%BC%88%E9%81%8E%E5%8E%BB%E3%83%AD%E3%82%B0-3%EF%BC%89#vd7f3865
https://lavender.5ch.net/test/read.cgi/kaden/1597226761/300
and nobody knows the cause. I installed the app and created an accout, but it seems checking the issue requires you to have real roomba. I asked a Twitter user and [according to him](https://twitter.com/cryptoporus_tes/status/1591743319855755265) whitelisting all blocked requests didn't solve the issue. Given the popularity of the app and the fact the only thing common in all the reports is that excluding the app solved the issue, I propose default-exclude the app until we get trustable details. An arguable point is that the app connects to `api.mixpanel.com` - a difficult test case for https://github.com/AdguardTeam/AdguardForAndroid/issues/4234#issuecomment-1262187304.

- **AdGuard version:**
NA
- **Filtering mode:**
NA
- **Device:**
NA
- **Operating system and version:**
NA
- **Root access:**
NA

### Expected Behavior

The app works normally.

### Actual Behavior

According to the reports, doesn't work.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by maxikuzmin** [comment]
@Yuki2718 your issue is in the works

**Comment by maxikuzmin** [comment]
@Yuki2718 we solved your problem in the 3.6.11 Beta 1 update. Please update to this version and check it out. Let us know the result

**Comment by Yuki2718** [comment]
Actually I can't check as:
> I installed the app and created an accout, but it seems checking the issue requires you to have real roomba.

**Comment by maxikuzmin** [comment]
@Yuki2718 have you updated? Is the problem still recurring?

**Comment by Yuki2718** [comment]
I mean I can't check the issue by myself as I don't have roomba. It's not really my issue, I just gahtered those user reports from the internet.

**Comment by maxikuzmin** [comment]
@Yuki2718 we fixed this problem, it should be resolved in the last update, but if it is still not resolved in version 3.6.11, please reopen the issue. 
For the moment, I’m closing this issue. 
Thank you very much for your work!
