### ISSUE TITLE
Increase "Trusted [User] Filter" Toggle's Usefulness 

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#4274]
### Problem Description

Right now, when importing/updating a user filter subscription, 1 has no idea whether leaving off the "Trusted Filter" does anything for _that_ list, though the description does explain what it does _generally_. 

### Proposed Solution

It'd be great, when that toggle is off, the UI would list what patterns are disabled/modified in that subscription.

**Comment by maxikuzmin** [comment]
@TPS we'll look into this in the future

**Comment by artemiv4nov** [comment]
@TPS Hello! You can handle the "Trusted filter" property when you add a filter. There is no other possibility to handle it.

**Comment by TPS** [comment]
> @TPS Hello! You can handle the "Trusted filter" property when you add a filter. There is no other possibility to handle it.

@artemiv4nov What do you mean?  & what if the ability changes on update?  Also, closing many old issues makes sense.  Why close this new 1 w/o proper response, like @maxikuzmin's above?
