### ISSUE TITLE
Hiding the YouTube player navigation bar in the landscape mode

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4275]
Is it possible to hide it automatically or add a button that'd be doing that? Some customers are not happy, because the bar also hide a top part of the videos

![image](https://user-images.githubusercontent.com/15856304/201638780-9a81b19e-3e2a-44d6-845c-16b9f3e522b0.png)

**Comment by maxikuzmin** [comment]
@Eugene-Savenko to hide it, you can recommend users to switch to full screen mode. If you switch to full screen mode, the navigation disappears
