### ISSUE TITLE
korabel.ru can't load on Android

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4276]
@adguard-bot commented on [Sun Nov 13 2022](https://github.com/AdguardTeam/AdguardFilters/issues/134770)

### Issue URL (Incorrect Blocking)
 [http://korabel.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fkorabel.ru)
### Comment
> Добрый день. Помогите добавить сайт в исключение. При установке на телефон адгуард, блокируется сайт

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dfDbct5.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/lukKc54.jpg)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/8UJujV4.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.10+(51)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by Alex-302** [comment]
В Макоси и Windows открывается нормально.

**Comment by ameshkov** [comment]
@Alex-302 браузер не хром, это что-то странное:
https://camo.githubusercontent.com/a1a860538098f817abb8c615663809ed38f36a4e0ee05a162c28ccf301af4169/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f6c756b4b6335342e6a7067
