### ISSUE TITLE
Still adroidacy.com detecting adguard 

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdguardForAndroid#4278]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ✓] I am running the latest version
- [✓ ] I checked the documentation and found no answer
- [ ✓] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
   (e.g. v3.6)
- **Filtering mode:**
  -Local VPN 
- **Device:**
  -  (OnePlus 6t)
- **Operating system and version:**
  -  (Android 13, November patch)
- **Root access:**
  - (yes, magisk )

### Expected Behavior
Went to the website and it should not display disable the adblock

### Actual Behavior

After I had received your mail saying that filter has been created, but still I am getting the same message disable the adguard.

### Screenshots

 ![Screenshot_20221118-212339_Vivaldi_Browser_Snapshot.png](https://user-images.githubusercontent.com/97349871/202767870-cefda238-82b0-4a99-ade4-21b83208ac58.png)

**Comment by kumar041** [comment]
Ok thanks for the update the filter rules, now it is working fine . I am not seeing the banner saying disable the adblock, thanks once again.👏👏👏

**Comment by maxikuzmin** [comment]
@kumar041 great!
