### ISSUE TITLE
Add Android 13 support 

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardForAndroid#4281]
Android 13 added new permissions such as Events, photos and music that, when disabled in AdGurd, the application will not remain active in the background.

The app according to Android keeps checking the devices nearby.

https://developer.android.com/about/versions/13/behavior-changes-13

![Screenshot_20221123_201044_Permission controller.jpg](https://user-images.githubusercontent.com/16819380/203661521-bbba3feb-ec11-4d30-8d84-83c286951eed.jpg)

**Comment by ameshkov** [comment]
@eduardoaddad could you please elaborate on both points?

> the application will not remain active in the background.

What application? I don't fully understand what it means.

> The app according to Android keeps checking the devices nearby.

You mean AdGuard?

**Comment by eduardoaddad** [comment]
If you disable photos/video and music/audio permission the app will crash and won't run in the background

According to the permissions management it is shown that Adgurd checks for nearby devices


> @eduardoaddad could you please elaborate on both points?
> 
> > the application will not remain active in the background.
> 
> What application? I don't fully understand what it means.
> 
> > The app according to Android keeps checking the devices nearby.
> 
> You mean AdGuard?

**Comment by eduardoaddad** [comment]
> @eduardoaddad this is specific to android 13. The thing is, 13 android defines "Files" in the same group to photo/video and music/audio as well - which you give access to when you create a certificate.
> If after disabling photo/video and music/audio permissions you turn AdGuard back on, it will continue to work (in the background too). 
> Maybe we'll revise this in the future.

In Android 13 the files were separated from the Images/Videos

**Comment by maxikuzmin** [comment]
@eduardoaddad note that if you remove the image/video permissions from the system settings, then file access is automatically removed from the permissions as well. Anyway, re-opening AdGuard and running the protection resumes the application. This is a feature of Android 13
