### ISSUE TITLE
Annoyance

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4282]
Hello! Please remove the annoying window asking you to install AdGuard VPN from your app settings. You should have been fighting evil, not joining it! Ads in the ad blocking app. Ridiculous absurdity!

I, for one, feel fine using SOCKS5 without the VPN service you imposed!

**Comment by Maxitheking** [comment]
Totally agree. It is really annoying. F*ck it away! We don’t need your VPN. We don’t need your another services. We paid fo ADBLOCK not for f*ucking stupid VPN.

VPN’s will never be private and anonymous.  How is your VPN better than Orbot? Or even ProtonVPN. Yes, ProtonVPN, too, is not anonymous, unlike Tor, but it, unlike you does not limit the speed and amount of traffic on free servers!

Those who don't want to use your VPN, like me, for example, won’t use in in any way. Those who want will use it without that banner.

**Comment by Maxitheking** [comment]
@Chinaski1 @slavaleleka will it be any comments?

**Comment by maxikuzmin** [comment]
@Maxitheking we understand your frustration, so the integration that we also have a product called AdGuard VPN is not often brought out. We have two compatible products, so we remind you of each if only one is installed. Having AdGuard  and Adguard VPN on board your phone is the ultimate protection. In any case, we're not forcing you to use only our VPN, if you have another VPN and don't want to change it, use it :) 
We just want to tell you about all our products and all the features. You decide which VPN you like better.
