### ISSUE TITLE
AdGuard breaking chat in Twitch app

### ISSUE THREAD

**Issue by spiritblackhole** [AdguardTeam/AdguardForAndroid#4283]
### Issue Details

- **AdGuard version:**
  - 3.6.10
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy S20 Ultra
- **Operating system and version:**
  - Android 13
- **Root access:**
  - No

### Expected Behavior

To be able to use the official Twitch app as before.

### Actual Behavior

The chat in the official Android Twitch app is not working properly:
- messages are not auto-refreshing, a manual scroll is needed to trigger the latest messages to appear
- the purple "send message" triangle is gone (the system keyboard "send" button still works)

**Comment by maxikuzmin** [comment]
@spiritblackhole any news?

**Comment by maxikuzmin** [comment]
@spiritblackhole for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
