### ISSUE TITLE
Usage Logs

### ISSUE THREAD

**Issue by PhantomNimbi** [AdguardTeam/AdguardForAndroid#4284]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

No issues yet. But last time I was in the program I was given some shade for not providing logs despite not having any issues. So this time I decided I'd send occasional logs in case there are things I'm simply not noticing.

- **AdGuard version:**
  - v4.0 nightly 35 (79-1.9.89cl)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Moto G Stylus
- **Operating system and version:**
  - Android 11 
- **Root access:**
  - No

<details><summary>Logs:</summary>

 - [adguard_logs_4.0.79_2611_113237.zip](https://drive.google.com/file/d/17J7KbbX_0Vq6c4ALUIHB6gqOPacTyABI/view?usp=drivesdk)

</details>

**Comment by maxikuzmin** [comment]
@PhantomNimbi I don't quite understand, are you having any problems with the AdGuard app right now?

**Comment by PhantomNimbi** [comment]
> @PhantomNimbi I don't quite understand, are you having any problems with the AdGuard app right now?

Nope. But the AdGuard team revoked my first beta license due to not sending logs to the GitHub. So I figured I'd occasional send logs so they don't revoke my new beta license.

**Comment by Versty** [comment]
@PhantomNimbi If you see no issues during active beta testing, there is no need to send logs. 
Your beta license might have been revoked by mistake or due to some technical issue. 
We hope you are enjoying your beta testing experience now!
