### ISSUE TITLE
WIFI exclusion function 

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardForAndroid#4285]
Can you add this option to android. Would really like it since home has already adblocking dns, so need to use dns protection service at home. The feature is really good in ios

![image](https://user-images.githubusercontent.com/46019727/204207544-995371e0-2169-46d2-80d9-beb4987bd378.png)

**Comment by Bhooty** [comment]
> @Bhooty that's interesting feature request. Let's see how many likes it will gain.

Sir requested for the same feature in windows application :)
That is also helpful especially for laptops

**Comment by maxikuzmin** [comment]
@Bhooty for now you can use "Automation" in "Advanced settings". This [link](https://kb.adguard.com/en/android/solving-problems/tasker#available-actions) will help you

**Comment by Bhooty** [comment]
> @Bhooty for now you can use "Automation" in "Advanced settings". This [link](https://kb.adguard.com/en/android/solving-problems/tasker#available-actions) will help you

Ok 
But This option will make the app easier to use

**Comment by Bhooty** [comment]
> 

I think they will close this issue after sometime and add won;t do :( and would argue it can be do via automation :| . Wanted this same feature for laptops so posted in windows version but it got closed :(

**Comment by Versty** [comment]
@Bhooty We consider the usefulness of every feature request for every platform separately.  
In Adguard for mobile repositories, the number of user likes strongly influences whether the feature will be implemented or not.

**Comment by artemiv4nov** [comment]
Well, this functionality could be processed through Tasker, Macrodroid or any other application that could use our Automation API.
Please use the Automation API to make your experience with AdGuard even better.
