### ISSUE TITLE
UDP filtering for SIP apps breaks calling

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4286]
Consider establishing a list of apps for which UDP is not filtered.

-------------------

Reported by: 635606 (w/ logs)

> When I create a SIP calling account with an app called AGEPhone and try to make a call, the call is disconnected with a 403 error when AdGuard is enabled. If I stop AdGuard it works fine. Also, even if AGEPhone is not protected by AdGuard, it will not work. 
> 
> None of the suggested methods (whitelisting the AGEPhone app, disabling the DNS module in AdGuard) worked. Either pattern disconnects with 403.

**Comment by artemiv4nov** [comment]
Likely with new app version it should work, I'll close the task.
