### ISSUE TITLE
Redirect is not recognised by filters 

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4287]
Новый редирект:
`https://previouseroute.com/bens/vinos.js?24698&mode=redir&subsite=EE549GN7CR`

_Originally posted by @Spok1 in https://github.com/AdguardTeam/AdguardFilters/issues/135849#issuecomment-1334687298_

**Comment by Versty** [comment]
@Spok1 Добрый день! 
Пожалуйста, опишите проблему в подробностях. 
А также, уточните информацию о версии приложения, которую вы используете, и версию операционной системы.

**Comment by Spok1** [comment]
@Versty, в рапорте в репозитории подписок из сообщения эта информация указана,просьба перейти туда!

**Comment by zloyden** [comment]
@Versty было также добавлено новое правило, проверьте у себя через пару часов обновление фильтров (открыть сайт, нажать на кнопку воспроизведения видео). У себя на андроиде попапов больше не наблюдаю.

**Comment by maxikuzmin** [comment]
@Spok1 есть какие-нибудь новости?

**Comment by Spok1** [comment]
@maxikuzmin , злойден исправил применив директиву **_!not_optimized_**.
