### ISSUE TITLE
DNS server problem

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdguardForAndroid#4288]
- [ √] I am running the latest version
- [√ ] I checked the documentation and found no answer
- [√ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
   (4.0 nightly) 
- **Filtering mode:**
  - ( Local VPN))
- **Device:**
  - (oneplus 6t) 
- **Operating system and version:**
  - (Android 13) -->
- **Root access:**
  - < (Yes ) 

### Expected Behavior
I have selected adguard dns, i can see only dns server of adguard.

### Actual Behavior
But when I select opendns address, I can see google dns address along with opendns address. So I do not understand it why opendns is using google dns server. Or adguard adblocker having problem in executing opendns address. 

### Screenshots
My ISP using google dns 
![Screenshot_20221203-002530_Vivaldi Browser Snapshot.png](https://user-images.githubusercontent.com/97349871/205365739-058eb178-800b-43f6-b06d-fba5b8f68797.png)
When I choose opendns address in adguard

![Screenshot_20221203-002904_Vivaldi Browser Snapshot.png](https://user-images.githubusercontent.com/97349871/205366230-28c62257-3c3b-4de0-a4f2-8b1db19a1d07.png)
![Screenshot_20221203-002545_Vivaldi Browser Snapshot.png](https://user-images.githubusercontent.com/97349871/205365846-733ae10c-8f26-4d66-aa7f-fbcc4874c624.png)

### Additional Information

Can you please explain why this happening even if I select quad9 dns address, I can see same google dns server address, I am not able to understanding it. May be due to  some reason they are using google infrastructure to support enquiry coning from India.

**Comment by maxikuzmin** [comment]
@kumar041 what resource are you using to check? Please try checking on several resources. Sometimes the problem may be with a resource

**Comment by kumar041** [comment]
I had used website called dnscheck.tools.
It listed all dns server. I have uploaded result of browserleaks.com/dns website to check again dns server list, when I am using cisco opendns.

Adguard with opendns

![Screenshot_20221205-222914_AdGuard.png](https://user-images.githubusercontent.com/97349871/205696859-36402749-4496-48d6-aa5b-e1ef37a900e5.png)

Browserleaks.com/dns (result)

![Screenshot_20221205-222733_Vivaldi Browser Snapshot.png](https://user-images.githubusercontent.com/97349871/205697028-32a4f11f-4534-4544-a950-0b00c1338e9f.png)

I am trying to understand why opendns using google india dns server. It should be opendns server alone should provide dns service but why google dns server included in the mixture. I try to understand it is opendns problem or something else. Anyway if it is opendns problem just let me know and you can close this case. 
 
Thanks you for looking into it.

Regards,
Rajkumar

**Comment by kumar041** [comment]
Ok close the case
