### ISSUE TITLE
adguard for android prevent a website, 'hdhub4u.gdn' to open due to a filter file '||gdn^$document'

### ISSUE THREAD

**Issue by spidy2356** [AdguardTeam/AdguardForAndroid#4297]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.10
- **Filtering mode:**
  - local vpn
- **Device:**
  - poco x2
- **Operating system and version:**
  - android 11
- **Root access:**
  - no

### Expected Behavior

the website 'hdhub4u.gdn' should open without any prevent notification pop up.

### Actual Behavior

whenever I open 'hdhub4u.gdn' website in my android device with enabling adguard adblocker, it shows a pop up message of 'Adguard has prevent this page from loading due to following filter rule '||gdn^$document''

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_2022-12-12-22-03-50-272_com android chrome](https://user-images.githubusercontent.com/101243689/207104581-dbe9554d-7579-4041-83ca-88cb040bd170.jpg)

</details>

**Comment by maxikuzmin** [comment]
@spidy2356 I don't have this problem. 
@Alex-302 what do you think?

**Comment by Alex-302** [comment]
This rule is in third-party filter - `Dandelion Sprout's Annoyances List`

**Comment by spidy2356** [comment]
> This rule is in third-party filter - `Dandelion Sprout's Annoyances List`, and this is expected result, not a bug.

ok. then I off the particular filter. but this is just a website domain, so this filter should not show this popup

**Comment by spidy2356** [comment]
thanks @Alex-302 , it solve now. but you should work on my another issue about sonyliv app, thanks

**Comment by maxikuzmin** [comment]
@spidy2356 I answered you on another issue. I'm closing this one.

**Comment by spidy2356** [comment]
yeah I just watch it and try the method.....I will confirm you if it works or not
