### ISSUE TITLE
AdGuard still makes background requests despite exiting the app, and not active VPN

### ISSUE THREAD

**Issue by jjp22191-cdfaq** [AdguardTeam/AdguardForAndroid#4299]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- Make sure Adguard is the active VPN.
- Also make it ignore battery optimizations, etc, to prevent it being killed.
- Turn off all updates, deselect all filter lists/updates, etc.
- In the app, go to the menu and choose exit.
- Make sure Always on VPN is turned off as well (or use another VPN app with Always on VPN).
- Wait around for ~3 hours.

- **AdGuard version:**
  - v3.6.51
- **Filtering mode:**
  - Local VPN DNS only
- **Device:**
  - Redmi Note 7
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No

### Expected Behavior

Adguard does nothing, as it has been exited from the app.

### Actual Behavior

Every 3 hours, it seems to make a request to adtidy.org, despite having exited the app, not being an active VPN, and filter updates all disabled.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by maxikuzmin** [comment]
@jjp22191-cdfaq this is an update check, no need to worry

**Comment by jjp22191-cdfaq** [comment]
> @jjp22191-cdfaq this is an update check, no need to worry

It shouldn't matter what it is.

If I disabled all updates, and exited the app from within the app, I would expect the app to not run until the next time I launch it.

**Comment by jjp22191-cdfaq** [comment]
Yup.

All the ones I could find in the settings and low level settings.

**Comment by maxikuzmin** [comment]
@jjp22191-cdfaq I checked this, but checking Safebrowsing, app updates and license status cannot be disabled. You can try in the phone's settings to set the app to not autostart. 
Checking these settings in the app is required, you cannot customize or disable this in the app.
