### ISSUE TITLE
Cannot access Facebook over IPv6

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#43]
Ticket ID: EMB-604-41646

Part of the log file:

    13:21:31.920 [Thread-11771] DEBUG c.a.a.filtering.commons.LogUtils - TCP id=24680 Creating new connection com.facebook.katana /fd12:1:1:1::1:60088 /2a03:2880:f003:c07:face:b00c:0:2:443 with packet TCP fd12:0001:0001:0001:0000:0000:0000:0001:60088 > 2a03:2880:f003:0c07:face:b00c:0000:0002:443 [SYN] seq=-1365913439 ack=0 win=65535 mss=4320 scale=7 len=0
    13:21:31.933 [pool-3-thread-4245] DEBUG c.a.a.f.f.FilteringHttpsProxyServer - TCP id=10944 TLS to domain api.facebook.com. Remote address /2a03:2880:f003:c07:face:b00c:0:2:443.
    13:21:31.939 [pool-3-thread-4245] WARN  c.a.a.f.f.FilteringHttpsProxyServer - TCP id=10944 Cannot connect to /2a03:2880:f003:c07:face:b00c:0:2:443

So, what's going on:
1. Device "thinks" that IPv6 is accessible (in fact - it is not)
2. Adguard sets up IPv6 filtering
3. Facebook app tries IPv6
4. Adguard **accepts** that connection and tries to proxify it (and fail to do it)

Without Adguard connection is not accepted and the app switches to IPv4.

**Comment by ameshkov** [comment]
One more ticket on the same issue: IAC-231-73690
Let's push it to 2.1.

**Comment by ameshkov** [comment]
Maybe something like this?

```    /**
     * Checks if IPv6 network is available
     *
     * @return true if available
     */
    public static boolean isIPv6Available() {

        SocketChannel socketChannel = null;
        Socket socket = null;
        try {
            socketChannel = SocketChannel.open();
            if (!socketChannel.isBlocking()) {
                socketChannel.configureBlocking(true);
            }
            socket = socketChannel.socket();
            VpnServiceHolder.getInstance().protectSocket(socketChannel.socket());
            InetSocketAddress socketAddress = new InetSocketAddress("ipv6.google.com", 80);
            // Trying to connect to IPv6 address for 3 seconds
            socket.connect(socketAddress, 3000);
            return true;
        } catch (UnknownHostException ex) {
            LOG.info("Cannot resolve ipv6 host, consider IPv6 unavailable");
            return false;
        } catch (IOException ex) {
            LOG.info("IPv6 is not available due to {}", LOG.isDebugEnabled() ? ex.toString() : ex.getMessage());
            return false;
        } finally {
            IOUtils.closeQuietly(socketChannel);
            IOUtils.closeQuietly(socket);
        }
    }
```

**Comment by ameshkov** [comment]
First we need more information - why IPv6 routes were enabled in the first place?
I've added logging to that place.

**Comment by ameshkov** [comment]
Waiting for user answer in YRV-505-60834

**Comment by ameshkov** [comment]
That's strange, current active connection is Wi-Fi, but there're IPv6 network also:

```Current Wi-Fi connection: "XXXXX" gateway=192.168.16.254 server=192.168.16.254 dns1=XXX dns2=XXX kernel=3.10.61-5358024
...
12:30:40.804 [Thread-60538] INFO  c.a.a.f.commons.NetworkUtils - Found IPv6 address for network [rmnet_data1][8][/2600:1003:b105:dbd:bc42:7f0e:e716:662b%8%8][/fe80::9ba3:dd19:ef26:d84e%rmnet_data1%8][/100.73.190.106]```

**Comment by Revertron** [comment]
The problem with TWO networks up at the same time was fixed. We will wait for user feedback.

**Comment by ameshkov** [comment]
Bad news here. By disabling IPv6 we have also broken Verizon sms.

**Comment by ameshkov** [comment]
What's going on (as I see it):
1. We have ignored **rmnet** network and didn't create routes for IPv6
2. When user tries to send SMS/MMS device needs IPv6 access to do it, but it is blocked by VPN routes.

We should distinguish three different cases.

**Case 1:** No IPv6 network is available
Just don't filter it.

**Case 2: IPv6 network is present and is used as default connection.**
That's also simple. Set up IPv6 filtering.

**Case 3: rmnet network is present, but device uses Wi-Fi connection instead.**
Set up routes for bypassing IPv6 traffic.

**Comment by ameshkov** [comment]
Anyway the problem with facebook may be annoying. For instance if Wi-Fi router provides you with IPv6 address without access. For now we will add a simple workaround blocking facebook app from accessing IPv6.
