### ISSUE TITLE
Firewall falsely blocks connection when set to allow it for a particular app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#430]
При использовании мобильного интернета делаю настройку в брандмауэре следующую, нажимая кнопку запрета мобильных данных для всех приложений и отдельно для гугл хрома ставлю разрешить. В этом случае Интернет в том же хроме не доступен, но если вручную выручить для всех приложений отдельно кроме хрома, то все работает. Проверял еще на севере и вацапе.

**Comment by evgeniy-ADG** [comment]
We managed to reproduce it on our side.

**Comment by TPS** [comment]
I had the opposite problem the other day: I default-block Chrome since a while ago, but tried it for a certain website. Worked fine until a few minutes later, when, suddenly, AG "remembered" block & Chrome stopped finding pages.  VPN-mode was active the whole time.

**Comment by ameshkov** [comment]
@evgeniy-ADG so it works that way for all apps?

Are you talking about stable or beta version?

**Comment by evgeniy-ADG** [comment]
@ameshkov 

> При отключении доступа к сетям в брандмауэре http://prntscr.com/aobb76 и включении отдельно доступа к сети только Браузеру - не работает инет в браузере
> При отключении доступа к сетям к каждому приложению отдельно и разрешенному доступу Браузеру - интернет в браузере работает

**Comment by Revertron** [comment]
In #535 is a solution, but we are planning to fix it in 3.0.

**Comment by Revertron** [comment]
Fixed.
