### ISSUE TITLE
exclude apps from quic filtering

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4300]
com.facebook.katana and com.facebook.orca should be added to next updated quic excluded list they block quic requests
![Screenshot_20221215_075316_AdGuard](https://user-images.githubusercontent.com/118186787/207881275-5462982d-af56-4708-a787-c5abcca3cc76.jpg)

**Comment by Merennor** [comment]
same, after update to Android 13 (OneUI 5) issue appeared

**Comment by jordanswrld94** [comment]
also in google play services its blocking legit domains. but its not quic so ud habe to disable filtering for google play services completely
![Screenshot_20221220_103921_AdGuard](https://user-images.githubusercontent.com/118186787/208719394-344b78a9-e665-4db7-82b2-c8e7638facc2.jpg)

**Comment by maxikuzmin** [comment]
@jordanswrld94 @Merennor thank you! We'll look into it.

**Comment by jordanswrld94** [comment]
im having the same problem with google maps. but its not quic its upd. i also had the same problem with google play services. 
![Screenshot_20221223_184456_AdGuard](https://user-images.githubusercontent.com/118186787/209415721-068afb43-028b-41c0-b398-460ac1fecb18.jpg)

**Comment by jordanswrld94** [comment]
![Screenshot_20221224_121536_AdGuard](https://user-images.githubusercontent.com/118186787/209447294-67a9f32b-a4b1-4b28-9854-61374208d3b6.jpg)

another oen

**Comment by maxikuzmin** [comment]
@jordanswrld94 @Merennor  we are dealing with this problem in another issue. Please stay tuned there for updates.
 Duplicate of <https://github.com/AdguardTeam/AdguardForAndroid/issues/2540>
