### ISSUE TITLE
Некорректная работа фильтров!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4302]
@Alex-302 , что скажешь?

_Originally posted by @Spok1 in https://github.com/AdguardTeam/AdguardFilters/issues/137182#issue-1490437765_

**Comment by Alex-302** [comment]
Некорректно оформленный баг-репорт.

**Comment by Spok1** [comment]
Так ч сослался же на пост,разве нет!🙄

**Comment by maxikuzmin** [comment]
@Spok1 пожалуйста, оформи баг-репорт по этому [примеру](https://github.com/AdguardTeam/AdguardForAndroid/issues/4299) в полном и развернутом виде, чтобы мы более точно понимали суть проблемы и могли помочь

**Comment by maxikuzmin** [comment]
@Spok1 я закрываю этот вопрос. Если возникнут в будущем какие-либо проблемы, вы можете создать новый вопрос. Пожалуйста, придерживайтесь того примера, ссылку на который я оставил выше
