### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by ipbenp** [AdguardTeam/AdguardForAndroid#4303]
- **AdGuard version:**
- Android x86_64, v11.
- Adguard  4.0.79beta

12-18 22:17:23.012  1381  1408 I ActivityManager: Start proc 4030:com.adguard.android/u0a134 for pre-top-activity {com.adguard.android/com.adguard.android.ui.MainActivity}
12-18 22:17:23.021  4030  4030 W adguard.androi: Unexpected CPU variant for X86 using defaults: x86_64
12-18 22:17:23.021  4030  4030 E libnb   : Unable to open /system/lib/libhoudini.so: dlopen failed: file offset for the library "/system/lib/libhoudini.so" >= file size: 0 >= 0
12-18 22:17:23.021  4030  4030 W libnb   : Native bridge is enabled but callbacks not found
12-18 22:17:23.039  1381  2125 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-18 22:17:23.054  1242  1290 I adbd    : jdwp connection from 4030
12-18 22:17:23.056  1381  2125 I SoundTriggerMiddlewareLogging: setCaptureState[this=com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareImpl@eb0be12, caller=1041/1484](false)
12-18 22:17:23.056  1381  2126 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-18 22:17:23.079  4030  4030 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
12-18 22:17:23.181  1381  1528 I SoundTriggerMiddlewareLogging: setCaptureState[this=com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareImpl@eb0be12, caller=1041/1484](false)
12-18 22:17:23.187  1381  2126 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-18 22:17:23.187  1381  2125 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-18 22:17:23.188  1381  2125 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-18 22:17:23.245  4030  4030 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
12-18 22:17:23.246  4030  4030 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
12-18 22:17:23.248  1484  1499 W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
12-18 22:17:23.249  1381  1528 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-18 22:17:23.249  2338  3688 I AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids={clid1006=2247992, clid1=2247990, clid1010=2247993, clid1003=2247991}, source=APP), candidates=[Candidate(clids={clid1006=2247992, clid1=2247990, clid1010=2247993, clid1003=2247991}, source=APP)])
12-18 22:17:23.265  2338  2463 I AppMetrica-Attribution: Choosing distribution data: ClidsInfo(chosen=Candidate(clids={clid1006=2247992, clid1=2247990, clid1010=2247993, clid1003=2247991}, source=APP), candidates=[Candidate(clids={clid1006=2247992, clid1=2247990, clid1010=2247993, clid1003=2247991}, source=APP)])
12-18 22:17:23.328  4030  4030 I MultiDex: VM with version 2.1.0 has multidex support
12-18 22:17:23.328  4030  4030 I MultiDex: Installing application
12-18 22:17:23.328  4030  4030 I MultiDex: VM has multidex support, MultiDex support library is disabled.
12-18 22:17:23.350  4030  4030 I TetheringManager: registerTetheringEventCallback:com.adguard.android
12-18 22:17:23.367  4030  4030 D AndroidRuntime: Shutting down VM
12-18 22:17:23.368  4030  4030 E AndroidRuntime: FATAL EXCEPTION: main
12-18 22:17:23.368  4030  4030 E AndroidRuntime: Process: com.adguard.android, PID: 4030
12-18 22:17:23.368  4030  4030 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~9euFeqjDxzkv4_o3OmVIDA==/com.adguard.android-0dXjjklxkKuXRURq9Ti6Uw==/lib/arm/libadguard-core.so" is for EM_ARM (40) instead of EM_386 (3)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at com.adguard.corelibs.CoreLibs.load(Unknown Source:95)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at com.adguard.corelibs.CoreLibs.<clinit>(Unknown Source:8)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at com.adguard.corelibs.CoreLibs.getCoreLibsVersions(Native Method)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at com.adguard.android.AdguardApplication.onCreate(Unknown Source:24)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-18 22:17:23.368  4030  4030 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-18 22:17:23.372  1381  4057 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-18 22:17:23.372  1381  1528 W ActivityTaskManager:   Force finishing activity com.adguard.android/.ui.MainActivity
12-18 22:17:23.379  4030  4030 I Process : Sending signal. PID: 4030 SIG: 9
12-18 22:17:23.389  1202  1202 I Zygote  : Process 4030 exited due to signal 9 (Killed)
12-18 22:17:23.390  1381  2397 I ActivityManager: Process com.adguard.android (pid 4030) has died: fg  TOP

**Comment by artemiv4nov** [comment]
@ipbenp Hello!
It looks like you have a cracked version instead of an official one. Please try our application from official website.
