### ISSUE TITLE
Allow setting the TTL for caching responses

### ISSUE THREAD

**Issue by jjp22191-cdfaq** [AdguardTeam/AdguardForAndroid#4305]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Allow the user to be able to set the TTL on responses, so that it could be cached.

The dnsproxy project (https://github.com/AdguardTeam/dnsproxy) can do something similar with it's cache options.

With caching enabled, the optimistic cache could also be enabled.

### Proposed Solution

This could be a few things in the low level settings, so only advanced users can set it up.

**Comment by maxikuzmin** [comment]
@jjp22191-cdfaq thanks, we'll get to that in the next updates

**Comment by artemiv4nov** [comment]
We already have this low-level setting in the new app version.
