### ISSUE TITLE
Expose a local DoH server for apps to connect to

### ISSUE THREAD

**Issue by jjp22191-cdfaq** [AdguardTeam/AdguardForAndroid#4306]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

Certain browsers such as Firefox allow the user to connect to a custom DoH server.

It would be good if AdGuard exposed on as well, so it can use the same filter lists/upstream servers as the DNS filtering.

### Proposed Solution

Something in the DNS Filtering part of the settings.

### Additional Information

The user would need to manually trust the HTTPS certificate in the app (e.g. Firefox) for it to connect to the DoH server.

Could the same one as the HTTPS filtering be used?

**Comment by maxikuzmin** [comment]
@jjp22191-cdfaq that’s interesting feature request. Let’s see how many likes it will gain.

**Comment by artemiv4nov** [comment]
As a mitigate solution, please use our Automation API to change DNS servers automatically on your way.
