### ISSUE TITLE
AG blocks internet connection after changing connection type

### ISSUE THREAD

**Issue by Iowerth** [AdguardTeam/AdguardForAndroid#4308]
### Issue Details

- **AdGuard version:**
  - v3.6.9
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - Poco F2 Pro
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Actual Behavior

After switching from 4G to Wi-Fi (or vice versa) internet connection stop working. And AG doesn't respond on turning protection off. I need to stop AG fully, then start protection after restarting AG. Then internet connection restores. It continues from 2020.
I got an advice to enable `pref.vpn.disable.pause` but it is not helpful.

### Expected Behavior

After switching from 4G to Wi-Fi (or vice versa) internet connection continues working. And no need to restart AG fully.

**Comment by maxikuzmin** [comment]
@Iowerth try upgrading to 3.6.10 and try again. Please let us know the result

**Comment by Iowerth** [comment]
> @Iowerth try updating to 3.6.10 version and try again. Please let us know the result

Ok, but it continues 2 years and appears seldom. I'll try and if I'll notice then I'll write here.

Могу на русском, если что.

**Comment by maxikuzmin** [comment]
@Iowerth мы знали об этой проблеме. На сколько я знаю, это проблему исправили. В последнем обновлении все должно быть в порядке. В любом случае понаблюдайте и дайте знать, появилась ли проблема снова

**Comment by Iowerth** [comment]
@maxikuzmin установил в тот же день, пока не было проблем. Если хотите, закройте. При возможном повторении открою новую со ссылкой на эту. Спасибо и с наступающим!

**Comment by maxikuzmin** [comment]
@Iowerth спасибо! Есть какие-нибудь новости? Проблема больше не появлялась?

**Comment by Iowerth** [comment]
@maxikuzmin ну, хвала богам, пока не было :) Закрываю, как я выше писал. Спасибо!

**Comment by Iowerth** [comment]
@maxikuzmin опять произошло :( Будучи вне дома, переключил с одного сотового оператора на другого и всё, интернет пропал. При этом, Telegram продолжает работать (соединение напрямую, без прокси). Чтобы интернет начал работать и в других приложениях, а также по wi-fi дома по возвращении, мне пришлось системно остановить зависший на попытке выключения защиты AdGuard. Лишь после системной остановки и запуска приложения вместе с защитой заново, интернет начал работать.
Что делать?

**Comment by maxikuzmin** [comment]
@Iowerth мы поработали над этой проблемой в обновлении 3.6.11 Бета 1. Пожалуйста, обновитесь до 3.6.11 Бета 1 и понаблюдайте еще раз. Если проблема повторится, дайте пожалуйста знать

**Comment by Iowerth** [comment]
@maxikuzmin спасибо, установил, буду наблюдать. Пока закрою, чтоб не мешало.
