### ISSUE TITLE
Checking the DNS server shows a connection to a distant location 

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdguardForAndroid#4311]
Hi,

I am using your adguard app in my android 13 phone, filtering the ads through vpn method, app version is 4.0 nightly. The issue is I have selected adguard dns over quic protocol, my closest dns server should be Singapore and it should be always connected to that server, but adguard always connected to Germany server, so I am getting around 200ms for dns query, sometimes it reaches 300ms too. So sometimes receiving sms based otp becomes delayed and even time out. When I have a German server opening a webpage too becomes delayed like 9 to 10 seconds. Kindly tell me how to troubleshoot this issue.

Connected to Germany dns server

![Screenshot_20221230-123349_Vivaldi Browser Snapshot.png](https://user-images.githubusercontent.com/97349871/210044625-12f8859c-5725-4b57-a3d1-2e6cb4dc93c6.png)

Application version

![Screenshot_20221230-124849_AdGuard.png](https://user-images.githubusercontent.com/97349871/210044741-dca9e442-2136-4b8a-98e4-503b82c2a598.png)

DNS settings

![Screenshot_20221230-124911_AdGuard.png](https://user-images.githubusercontent.com/97349871/210044762-76bead8c-9ae0-432f-99ec-321ad0ef4fac.png)

**Comment by kumar041** [comment]
Sorry I don't understand other resources, can you kindly tell me about it, So I can check with it. And post the results.

**Comment by maxikuzmin** [comment]
@kumar041 I wrote about did you check other sites location? I remember that we already discussed DNS leak test results and I recommended to check at www.maxmind.com 
Also please answer my question: do you have private DNS enabled in your system settings?

**Comment by kumar041** [comment]
Nope in network settings it says automatic,I am using adguard in vpn mode to filter so I think it takes care of it by default, I do remember that website address, I will check it again.
![Screenshot_20230116-170953_Settings.png](https://user-images.githubusercontent.com/97349871/212670032-a1176137-a303-46e1-bbf5-787973d2c693.png)

**Comment by maxikuzmin** [comment]
@kumar041 also, the load is distributed between the servers automatically, connection to Germany is possible if there is a large load and a large ping on the Singapore server. I think this is the main reason, but in anyway, it's better to check for www.maxmind.com

**Comment by kumar041** [comment]
Due to dns server many of the operations are failing mainly otp for bank transaction and adding money to wallet, think for one second due to load transfer adguard switch from Singapore to Germany, due to that delay many of the time transferring money got stuck in between, so almost I lost money due to that too. So better not to use your dns server for my safety.

**Comment by kumar041** [comment]
Hi,
May I know who is having priority using the dns server,  I think whomever purchased your dns service they have priority over others using the server. Load balancing means what I like to know about it.

**Comment by maxikuzmin** [comment]
@kumar041 I was talking about the fact that the load is automatically distributed between servers, a connection to Germany is possible if there is a large load and a high ping on the Singapore server. This happens automatically, there is no priority. The connection is made to the server where you will have the fastest connection.
What kind of problems did you have with the money transfer?

**Comment by kumar041** [comment]
Hi,

The money transfer problem is that I am using paytm so when I transfer my money from wallet to the bank it hangs in between, so due to failure money return to wallet after three banking working days. If I am paying you to any merchant using qrcode then it hangs in between, either it is not delivered to the merchant or return to my account. After checking with paytm money returns to me after 5 days. The main problem is when payment hangs i have to repay again, so sometimes it will be like double payment to the same merchant and those idiots never accept the double payment. So anyway I am thinking of going back to the default dns service provider. That will be better I think. So I will reconfigure my mobile to use the default dns service. Thanks for your patience in answering my questions.

Thanks,
Rajkumar

**Comment by maxikuzmin** [comment]
@kumar041 try adding the domains of this payment system to "pref.dns.fallback.domains" in Low-level settings, then the requests of these domains will go to the system DNS. Maybe it will help you.

There is also a more complicated way, when you set up dnsmasq/dnsproxy/AdGuard Home to redirect everything to AdGuard servers, except requests for domains of this payment system. Respectively, you do not configure all the devices directly to AdGuard DNS, but to this dnsmasq/dnsproxy/AdGuard Home.

**Comment by maxikuzmin** [comment]
@kumar041 any news?

**Comment by kumar041** [comment]
Hi,

I  changed my dns service provider to cloudflare for now, I don't have  any idea about how many address paytm having and I don't have any time to investigate about it. So if they are any application to capture these address then I will do it, for now you can close the case, because I am not using adguard dns now. So sorry.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kumar041** [comment]
Ok I will try, now I am started to using nightly build of both the adblocker and vpn so now I am having different issues. Thanks for the suggestions.😊
