### ISSUE TITLE
Missing elements on the page are not blocked

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4312]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v3.6.10 (51)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Asus z500m
- **Operating system and version:**
  - 7.0
- **Root access:**
  - No

### Expected Behavior

Чтобы пропущенные и раздражающие элементы были убраны!

### Actual Behavior

 Пропущенные остатки от рекламы.

### Screenshots

<details><summary>Screenshot:</summary>

![chrome_screenshot_1672436325269](https://user-images.githubusercontent.com/34476664/210113955-11fe0166-ceac-4ef2-91da-ffa242b9ef6c.png)

</details>

### Additional Information

Не блокируются пропущенные элементы на странице!

**Comment by maxikuzmin** [comment]
@Spok1 я уже ответил тебе в другом ишью. Я думаю, что причина может быть в старой версии андроида или браузера, в которых не поддерживается какие-либо правила.
Попробуй повторить это на другом устройстве или хотя бы браузере, в том числе проверь обновления в браузере

**Comment by Spok1** [comment]
@maxikuzmin, причина точно не в браузере,ибо обновления продолжаются  по ныне,а по поводу старой версии андроида тут уже вы мне скажите и сделайте с этим что-то!

**Comment by maxikuzmin** [comment]
@Spok1 очень похоже на то, что не включена https фильтрация. Проверь, включена ли https фильтрация. В том числе проверь это в управлении приложений отдельно для браузера. 
Будет неплохо, если ты также экспортируешь свои настройки и пришлешь на devteam@adguard.com

**Comment by maxikuzmin** [comment]
@Spok1 проблема всё еще повторяется на версии 3.6.11?

**Comment by Spok1** [comment]
Да

**Comment by maxikuzmin** [comment]
@Spok1 проверьте пожалуйста в браузере, работает ли у вас https фильтрация. Нажмите на замок слева от ссылки и проверьте, отображается ли там сертификат AdGuard

**Comment by maxikuzmin** [comment]
@Spok1 экспортируйте пожалуйста настройки и пришлите нам, может быть проблема в какой-либо настройке
Вы можете вложить сюда или отправить на почту [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by maxikuzmin** [comment]
@Spok1 также нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

- Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
- Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
- Дополнительно запишите [системный лог](https://developer.android.com/studio/debug/bug-report);
- Отправьте оба файла по адресу devteam@adguard.com. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by maxikuzmin** [comment]
@Spok1 есть новости?

**Comment by maxikuzmin** [comment]
@Spok1 на данный момент я закрываю это обсуждение. Если в будущем у вас повторится проблема, вы сможете переоткрыть ишью этой проблемы. Не забудьте приложить расширенные логи или отправить логи на почту [devteam@adguard.com](mailto:devteam@adguard.com)
