### ISSUE TITLE
Missing elements on the page are not blocked

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#4313]
### Issue Details

- **AdGuard version:**
  - v3.6.10 (51)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - z500m
- **Operating system and version:**
  - 7.0
- **Root access:**
  - No 

### Expected Behavior

Скрытие элементов с плеера.

### Actual Behavior

 Остатки от рекламы в плеере.

### Screenshots

<details><summary>Screenshot:</summary>

![chrome_screenshot_1672438191451](https://user-images.githubusercontent.com/34476664/210114855-13c14c16-f2db-4e57-a2e4-90d8825b5e4b.png)

</details>

### Additional Information

https://m.proporn.com/video/1409070/small-tit-teen-on-webcam

**Comment by maxikuzmin** [comment]
@Spok1 ты уже упоминал эту проблему [здесь](https://github.com/AdguardTeam/AdguardFilters/issues/136536), но она так и не повторяется у нас. Я думаю, что причина может быть в старой версии андроида или браузера, в которых не поддерживается какие-либо правила. 
Попробуй повторить это на другом устройстве или хотя бы браузере, в том числе проверь обновления в браузере

**Comment by maxikuzmin** [comment]
@Spok1 есть новости?

**Comment by Spok1** [comment]
@maxikuzmin, как я уже писал ранее,браузер не при чём: хром обновляется и по сей день. На Эдж тоже самое. На других не проверял.Это же ваше приложение,вот и сделайте всё,чтобы исправить это,даже на ретро-системах!

**Comment by maxikuzmin** [comment]
@Spok1 очень похоже на то, что не включена https фильтрация. Проверь, включена ли https фильтрация. В том числе проверь это в управлении приложений отдельно для браузера. 
Будет неплохо, если ты также экспортируешь свои настройки и пришлешь на devteam@adguard.com

**Comment by Spok1** [comment]
Отображается.

**Comment by maxikuzmin** [comment]
@Spok1 экспортируйте пожалуйста настройки и пришлите нам, может быть проблема в какой-либо настройке
Вы можете вложить сюда или отправить на почту [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by maxikuzmin** [comment]
@Spok1 также нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

- Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
- Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
- Дополнительно запишите [системный лог](https://developer.android.com/studio/debug/bug-report);
- Отправьте оба файла по адресу devteam@adguard.com. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by maxikuzmin** [comment]
@Spok1 есть новости?

**Comment by maxikuzmin** [comment]
@Spok1 на данный момент я закрываю это обсуждение. Если в будущем у вас повторится проблема, вы сможете переоткрыть ишью этой проблемы. Не забудьте приложить расширенные логи или отправить логи на почту [devteam@adguard.com](mailto:devteam@adguard.com)
