### ISSUE TITLE
Themed icons

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForAndroid#4317]
Please add Material You’s themed icons support for AdGuard and AdGuard VPN.

<details>
<summary>Themed icons</summary>
<img src="https://user-images.githubusercontent.com/18536328/211504829-0329ec0d-21a9-4923-98be-1466092f7cdd.png">
</details>

**Comment by Swapnil-jain** [comment]
I really hope this feature is added soon.
