### ISSUE TITLE
Automatic redirect does not work when there is a proxy server set in APN settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#432]
Initial user report:
http://forum.xda-developers.com/showpost.php?p=65983046&postcount=841

It appears that there is a proxy server set in the APN settings. Proxy port is 9041. The problem is that Adguard redirects ports 80 and 443, it just does not redirect traffic to port=9041.

**EDIT:** The issue is still here in v2.7.220:
Customer ID=1207562

Also I guess the issue is not with proxy port 9041, he has some other port set in the APN settings (which we don't see).

**Comment by Revertron** [comment]
Found a method to get current proxy port and make a redirect for that port, but HTTPS-filtration is not working yet...

**Comment by Revertron** [comment]
Okay, I've made it to work with outbound (APN or Wi-Fi) proxies, but the HTTPS filtering is not working for now. We will fix it in #51.

**Comment by ameshkov** [comment]
Let's leave it open just in case.

**Comment by ameshkov** [comment]
@Revertron with current implementation traffic it is possible to redirect Adguard into our own proxy

**Comment by Revertron** [comment]
Fixed the possibility of loop redirect.

**Comment by ameshkov** [comment]
Updated issue decription

**Comment by ameshkov** [comment]
This issue will be covered by https://github.com/AdguardTeam/AdguardForAndroid/issues/796
