### ISSUE TITLE
Couldn't enter "tls://"on Samsung phone

### ISSUE THREAD

**Issue by jidanni** [AdguardTeam/AdguardForAndroid#4321]
The instructions say:
>Select Private DNS provider hostname. Enter one of the servers below:

>Default server

>tls://dns.adguard-dns.com

That's great, but I had to remove the "tls://" in order to save it in Samsung Android 12 settings. Just wanted to let you know.

**Comment by jidanni** [comment]
Okay, yes, but your job is how to communicate that to the user who was reading that web page that tells him to put in the tls. I mean telling me is great but then there's always the next user is going to do the exact same thing. And end up thinking well why didn't they tell me I didn't need to put in the tls. So maybe that part of the web page should communicate both situations somehow.

**Comment by maxikuzmin** [comment]
@jidanni yes, you're right :) 
Do you have any more questions?

**Comment by maxikuzmin** [comment]
@jidanni I think this issue will come in handy in the future for users who have this issue. For now, I'm closing this issue
