### ISSUE TITLE
[Android] 3.6.11 beta 1 can't be installed

### ISSUE THREAD

**Issue by yochananmarqos** [AdguardTeam/AdguardForAndroid#4322]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.6.51
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Google Pixel 7
- **Operating system and version:**
  -  Android 13
- **Root access:**
  -  No

### Expected Behavior

I should be able to update from  3.6.51 to 3.6.11 beta 1

### Actual Behavior

The APK fails to install because 3.6.11 beta 1's versionCode is 3.6.50 and is <  3.6.51.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by maxikuzmin** [comment]
@yochananmarqos please try again, it should work now

**Comment by yochananmarqos** [comment]
Indeed. Thanks!
