### ISSUE TITLE
Adguard blocks outgoing echo request ICMP packets

### ISSUE THREAD

**Issue by Peter-maximus** [AdguardTeam/AdguardForAndroid#4323]
I have found that _**echo requests ICMP packets don't come through**_ from Android device where Adguard is installed.
That means I can't ping any server (even 8.8.8.8) from any app installed on such a device…
I tried to disable all filters in Adguard and still no joy.
The only workaroud is if I disable the Adguard protection for particular "pinging" app or turn off Adguard protection completely .

There is no issue with pinging the Android device with Adguard installed from outside, so it seems _**echo reply ICMP packets come through**_.

What I can do to enable outgoing echo request ICMP packets?

**Comment by sfionov** [comment]
@Peter-maximus Using ICMP sockets requires root permissions, which AdGuard usually doesn't have. So ICMP ping is emulated by doing TCP connect to port 80.

8.8.8.8 has this port firewalled, that's why you can't ping it. You may try pinging 1.1.1.1.

**Comment by Peter-maximus** [comment]
Is there any **_possibility to create the exception_** (e.g. rule atc.) **_to enable outcoming echo requests icmp packets_** (to not process them through Adguard = to not emulate them through TCP:80)?
I also found that several apps using this packets to check if internet connection is active and fail because of this emulation... The only workaround is again to disable Adguard completely for such an app.

**Comment by sfionov** [comment]
@Peter-maximus AdGuard uses Android's VPN API for traffic interception, and unfortunately, this API only allows excluding apps and/or IP ranges

**Comment by Peter-maximus** [comment]
So do I understand correctly if i want to pass the "real" icmp echo request packet through I have to completely disable Adguard filtering for such an app or to root the phone?
**_Or is there any other workaround (even complicated)?_**

**Comment by sfionov** [comment]
We'll recheck if something is changed in ICMP socket permissions in new Android versions.

BTW, AdGuard will not passthrough ICMP packets even on rooted phone in "Local VPN" mode because this is not implemented at this moment.

**Comment by Peter-maximus** [comment]
So in a nutshell the only possibility if i want to pass the "real" icmp echo request packet through I have to completely disable Adguard filtering for such an app. 
**_Is it correct?_**

Please also **_let me know the outcome of your "recheck"_** of Android ICMP socket permissions.
I will greatly appreciate any positive one ;-)
Thx a lot.

**Comment by sfionov** [comment]
@Peter-maximus Yes, that's correct

**Comment by Peter-maximus** [comment]
Are there any positine news?

Have you found anything during your "**_recheck if something changed in ICMP socket permissions_** in new Android versions"?

**Comment by sfionov** [comment]
@Peter-maximus Hello! No, never Android versions does not allow ICMP sockets for regular apps. Last Android version which allowed this was KitKat.
