### ISSUE TITLE
AdGuard VPN ads in the AdGuard app

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4326]
Hello!

I'm a little confused about what's going on. Why the fuck is there advertising in the app settings, even if it's your product?

Can you remove the annoying AdGuard VPN bar from your app settings?

I am using Tor. VPN will never be as secure as Tor. I don’t want to install or use your VPN. Why do I need to see this PERMANENT bar without any method to hide it?

Because of you I have to do unauthorized intervention in the application in order to remove the annoying element (and at the same time to make a free subscription, why should I pay if I am so disrespected? (Although I used to pay, but if already doing warez, then why not do more and free?))? And by the way, my mod is quite popular. So just for reference. Nobody likes the imposition of services.

(Account from which I'm writing now, I'll delete, just don't know how you'll react to it. I do not want to have legal problems. But you can be sure that I will read your response).

**Comment by maxikuzmin** [comment]
Hello! We understand your frustration, so the integration that we also have a product called AdGuard VPN is not often brought out. We have two compatible products, so we remind you of each if only one is installed. Having AdGuard and Adguard VPN on board your phone is the ultimate protection. In any case, we're not forcing you to use only our VPN, if you have another VPN and don't want to change it, use it :)
We just want to tell you about all our products and all the features. You decide which VPN you like better.
What about mods? We also check most new mods and test them. If you have your own mod, [send](devteam@adguard.com) it to us and we'll evaluate it :)
