### ISSUE TITLE
Only English is currently available 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4328]
#### Issue Details
The new version of the application currently has no translations for languages other than English.

#### Additional Information
We are planning to implement the translations as soon as they are ready. 
Feel free to join [Crowdin](https://crowdin.com/translate/adguard-applications/19609/en-en?filter=basic&value=0) to help us translate AdGuard for Android to your native language faster!

**Comment by Verbatix** [comment]
So when? Writing type soon tells me nothing.
Can you at least know the approximate date?
