### ISSUE TITLE
"Clear statistics" under "Companies" does not work

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4342]
**Issue Details**

In the "Statistics" section, if you select any component of the "Companies" block, then press on the "dots" in the upper right corner and press on "Clear statistics", you will see the notice "This function is not yet implemented".

Also, if you go to "Applications" and select some component of the "Companies" block, and also hit the dash in the upper right corner and press "Clear statistics" you will also see the notice "This function is not yet implemented". This function does not work.

**Additional Information**

We are monitoring this issue and are working on the solution.
If you are experiencing the same issue, please put the 👍 emoji on this post and leave a comment below.

**Comment by artemiv4nov** [comment]
To mark the task is closed, we have to remove the "Clear statistics" button from this screen.
