### ISSUE TITLE
Random SSL errors in Proxy+Manual filtering mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#435]
User reports:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=48668708
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=48683472

**UPD:** It seems that the issue is caused by AG app cache cleaning. We should move certs storage to the app data to avoid it.

**Comment by Bohdan-SUP** [comment]
Similar report from user with latest beta and VPN mode:
Errors appeared after enabling the https filtering, happens randomly, browser - default LG G2 one.
More details here COO-513-25531

**Comment by ameshkov** [comment]
@Bohdan-SUP log is empty in COO-513-25531

**Comment by ameshkov** [comment]
@Bohdan-SUP also it is not a proxy mode.

**Comment by ameshkov** [comment]
Ah, I know what's the problem.

Adguard certificates are stored in the app cache.
I guess user cleans up AG cache so all certificates are removed.

@Revertron what do you think about it? Maybe we should move certs storage to the app data?

**Comment by Revertron** [comment]
The CA certificate is stored in Preferences. And there is no point in guarding domain certificates. If they are cleared we just regenerate them.

**Comment by ameshkov** [comment]
I thought so too until these issues.

You see, there're lots of users using some cleaner apps like SD maid and CCleaner.
These apps can clean the cache of our app, therefore all existing SSL connections will be broken.

**Comment by Revertron** [comment]
Let's try to relocate, it is not so hard :)

**Comment by Revertron** [comment]
We need to remind users to clear cache of Adguard after update.
