### ISSUE TITLE
Kaa

### ISSUE THREAD

**Issue by Alikaabi1** [AdguardTeam/AdguardForAndroid#4353]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@Alikaabi1 This issue is empty.
Closed due to lack of information.
