### ISSUE TITLE
com.huawei.browser is broken by HTTPS filtering

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4358]
@adguard-bot commented on [Fri Jan 20 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140625)

### Issue URL (Incorrect Blocking)
 [https://appgallery.cloud.huawei.com/ag/n/app/C100170981?locale=ru_RU&source=appshare&subsource=C100170981&shareTo=com.huawei.notepad&shareFrom=appmarket&shareIds=594e43e3b04941cdb5044e746282e9ce_com.huawei.notepad&callType=SHARE](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fappgallery.cloud.huawei.com%2Fag%2Fn%2Fapp%2FC100170981%3Flocale%3Dru_RU%26source%3Dappshare%26subsource%3DC100170981%26shareTo%3Dcom.huawei.notepad%26shareFrom%3Dappmarket%26shareIds%3D594e43e3b04941cdb5044e746282e9ce_com.huawei.notepad%26callType%3DSHARE)
### Comment
Username: `@Koruy`
> Не обновляются новости на начальной странице браузера ошибка. В низкоуровневых настройках указано, что adguard фильтрует https трафик com.huawei.browser

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/n9Lmpv7.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/BGPahfd.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.6.10+(51)
Browser: | Huawei browser
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing third-party cookies (0)
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt, DnsUserRules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@Alex-302 commented on [Fri Jan 20 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140625#issuecomment-1398521588)

@Koruy Проверь с выкл. фильтрафи и выкл. фильтрацией DNS. Если не поможет - с выкл. фильтрацией HTTPS этого приложения. Какой `package_name` у приложения?

---

@Koruy commented on [Fri Jan 20 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140625#issuecomment-1398591950)

> @KoruyПроверь с выкл. фильтры и выкл. фильтрацией DNS. Если не поможет - с выкл. фильтрацией HTTPS этого приложения. Какие `package_name`у приложения?

Всё сделал, отключил все фильтры, отключил фильтрацию dns - не помогло. Отключил фильтрацию https для этого приложения - помогло новости обновляются.
Имя пакета: com.huawei.browser
Uid: 10093
Тип: User
Версия: 12.1.3.304 (120103304)
Целевой SDK: 30
Время установки: 07.08.2018 19:01
Время последнего обновления: 20.01.2023 13:09

**Comment by Alex-302** [comment]
I don't have a Huawey device and cannot check. User says than the app is broken when all filters and DNS filtering are disabled.

**Comment by maxikuzmin** [comment]
@Alex-302 I don't have this problem repeated. Browser version 12.1.3.304. Tested with AdGuard 3.6.11. It also works with filters and DNS filtering enabled

**Comment by Koruy** [comment]
Скиньте мне свои настройки adguard

**Comment by Koruy** [comment]
> Да, конечно. Попробуйте, и дайте знать о результате [adguard_settings_3.6.54_0302_202409.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10581286/adguard_settings_3.6.54_0302_202409.zip)

Всё равно сбой загрузки страницы, сайты открываются, но новости не обновляются. Сбой загрузки страницы.

**Comment by Alex-302** [comment]
@Koruy попробуй выключить фильтрацию HTTPS для этого приложения.

**Comment by maxikuzmin** [comment]
@Koruy в другом браузере это повторяется?

**Comment by Koruy** [comment]
Отключаю фильтрацию https навости обновляются на главной странице, включаю https фильтрацию - сбой загрузки страницы. При этом когда включаю https фильтрацию adguard пишет, что приложение не доверяет пользовательскому сертификату. При этом в низкоуровневых настройках adguard есть пункт pref.enforce.https.filtering список приложений для которых adguard  обеспечивает фильтрацию https и в нём указано приложение с названием пакета com.huawei.browser. Все сайты открывающиеся в этом браузере используют сертификат adguard это видно если нажать в адресной стоке на замочек и посмотреть сведения

**Comment by maxikuzmin** [comment]
@Koruy для диагностики и решения Вашей проблемы, нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

- Соберите отладочный лог [согласно данной инструкции](https://kb.adguard.com/ru/android/solving-problems/log#debug);
- Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
- Дополнительно запишите [системный лог](https://developer.android.com/studio/debug/bug-report);
- Отправьте оба файла по адресу devteam@adguard.com. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by maxikuzmin** [comment]
@Koruy мы получили логи, нам нужно некоторое время, чтобы разобраться в ситуации

**Comment by maxikuzmin** [comment]
@Koruy судя по всему браузер не доверяет нашему сертификату. Можно попробовать переустановить сертификат. Если не поможет - посмотреть в настройках браузера, возможно там есть низкоуровневые настройки, которые дадут возможность использовать пользовательские сертификаты.
Пожалуйста, дайте знать о результате

**Comment by Koruy** [comment]
К сожалению переустановка сертификата не помогла. Низкоуровневых настроек так же не найдено в данном браузере.

**Comment by maxikuzmin** [comment]
@Koruy прошу прощения за длительный ответ. Вы так и не уточнили, повторяется ли эта проблема в других браузерах?

**Comment by Koruy** [comment]
В яндекс браузере не повторяется, по другим браузерам сказать не могу

**Comment by maxikuzmin** [comment]
@Koruy нам нужно еще некоторое время для рассмотрения. Если удастся сравнить также с другими браузерами помимо яндекс браузера, пожалуйста, дайте знать

**Comment by maxikuzmin** [comment]
@Koruy ваш браузер не принимает пользовательские сертификаты. Необходимо  отправить репорт в хуавей браузер. К сожалению, мы не сможем помочь с нашей стороны
