### ISSUE TITLE
[Feature request] Change "Get Adguard Premium" and all corresponding messages to something like "Get a full version" or "Licensed version only"

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#436]
TICKET ID RDT-723-82818

"I feel it would be better understood by your customers to retype the
message in your trial Apps from "Premium version only" to "Licensed version
only". That would make more sense so when they arrive to purchase to license
they see the option for premium that states and extra license for desktop."

Here are the screenshots from trial version where you can see the word "Premium":
(https://cloud.githubusercontent.com/assets/17472907/14387208/e90a7524-fdb0-11e5-8cc5-570e70043150.png
(https://cloud.githubusercontent.com/assets/17472907/14387214/f4ab67da-fdb0-11e5-9f9e-0224f621e6a9.png)

Here is the "choose the license" page (it can be also an option to make some changes and\or add details here):
(https://cloud.githubusercontent.com/assets/17472907/14387217/f7c6ffba-fdb0-11e5-8496-c515f53858b2.png)

**Comment by ameshkov** [comment]
UI is different in v3.0 btw
