### ISSUE TITLE
Autostart option does not launch AdGuard at system startup on Android 8 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4361]
### Issue Details
- **Device:** Samsung Galaxy S7
- **Operating system and version:** Android 8.0.0
- **AdGuard version:** 4.0 Nightly 

Configured the system settings for AdGuard as described in the [instruction from the knowledge base.](https://kb.adguard.com/en/android/solving-problems/background-work#Samsung) 

### Additional Information
Autostart option works as intended with the same system setting using AdGuard version 3.6.11.

**Comment by TPS** [comment]
@Versty I've followed these steps, but am still having this issue w/ the new v4.0n40.  Besides UI, was anything else changed that would affect this?  I didn't experience this < v4.0n39 (which is when I last restarted).

**Comment by Versty** [comment]
@TPS Got it. What is your Android version and device model?

**Comment by TPS** [comment]
Android 12, 1+ N200 5G (DE2118), Stock, nonrooted

I didn't change anything on upgrade & verified system settings are correct.

**Comment by michael1900** [comment]
The problem can be the pref boot delay option? I can't found it in nightly.

**Comment by michael1900** [comment]
Fixed in today nightly at least for me!
