### ISSUE TITLE
Automation `proxy_state` only disables

### ISSUE THREAD

**Issue by tmknight** [AdguardTeam/AdguardForAndroid#4364]
### Issue Details

Using `Automate` or `Automateit` to execute a send broadcast intent results in disabling the outbound proxy, regardless of enable:true/false

- **AdGuard version:**
  - v3.6.11 (54)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - LG V30+ (H932)
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Enable as well as disable outbound Proxy

### Actual Behavior

Disable only

### Additional Information
The only other actions I've tried are pause and start, which do work.  So seems down to something with proxy_state

**Comment by maxikuzmin** [comment]
@tmknight this feature will be redesigned in version 4.0, no exact release date is known yet, but it will be very soon. Please wait for version 4.0
