### ISSUE TITLE
Pause AG protection automatically when tethering is turned on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#437]

**Comment by Bohdan-SUP** [comment]
Some ideas from a user (JXX-328-15660):
- make it as an option in settings (so you can enable/disable the switch);
- restore Adguard protection when tethering is turned off.

**Comment by ameshkov** [comment]
Fix will be available in the next beta version.

**Comment by carlylemiii** [comment]
This doesn't work for me on my Pixel 2 XL. I have to manually disable AdGuard protection. Is that expected behavior, maybe because of Oreo or anything like that?

**Comment by ameshkov** [comment]
@carlylemiii yep, this is expected for Nougat and newer. The Android's tethering bug is fixed now.
