### ISSUE TITLE
Proxi turns off when I complete Adguard

### ISSUE THREAD

**Issue by vladimirov-s** [AdguardTeam/AdguardForAndroid#4371]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11

### Environment

```markdown
- OS: Android 12
- Device: Realme GT Neo2T
- Firmware: Realme UI 3.0

Setting of proxy turns off when I complete Adguard
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, NoCoin Filter List

### Issue Details

Proxi settings turns off only when I complete Adguard. 

### Expected Behavior

any settings should not change! Even when I close the Adguard

### Screenshots

![Screenshot_2023-01-28-02-36-49-df2bc8fc](https://user-images.githubusercontent.com/101799674/215225825-645161bd-12cd-40c3-8e7f-dca97d93c413.jpg)
![Screenshot_2023-01-27-23-39-29-33fc](https://user-images.githubusercontent.com/101799674/215225827-e76a706f-fc56-4ca7-8f1f-f606d5250526.jpg)

### Additional Information

Adguard works good in background, consumption of the battery configured ok. In my opinion it's a bug

**Comment by maxikuzmin** [comment]
@vladimirov-s to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@vladimirov-s any news?

**Comment by vladimirov-s** [comment]
No, I can't get bug report from OS

ср, 8 февр. 2023 г. в 19:50, maximkuzmin ***@***.***>:

**Comment by maxikuzmin** [comment]
@vladimirov-s do you have some kind of error in the application? Let's look into it

**Comment by vladimirov-s** [comment]
@maxikuzmin, ok. I'll send the report from app in few minutes.

**Comment by vladimirov-s** [comment]
fsdf

**Comment by vladimirov-s** [comment]
@maxikuzmin yeah even twice. The system answered me ticket number 721303, second was fucked up. I'll do new attempt right now.

**Comment by vladimirov-s** [comment]
@maxikuzmin new attept with logs in ticket #722722

**Comment by maxikuzmin** [comment]
@vladimirov-s thank you! We'll check your logs

**Comment by maxikuzmin** [comment]
@vladimirov-s please clarify, do you observe this behavior only when you stop the application forcibly or when you simply close the application through the task manager?

**Comment by maxikuzmin** [comment]
@vladimirov-s any news?

**Comment by vladimirov-s** [comment]
@maxikuzmin I haven’t opened this functionality for a long time, now I tried to reproduce this problem and I came across the fact that Adguard does not filter anything at all in this mode.  I assumed that the port for the proxy is incorrectly configured.  I tried a couple of other numbers, but the protection stopped turning on at all.  As a result, it turns out that protection is enabled only on the standard port 9050 but does not filter absolutely anything.

**Comment by maxikuzmin** [comment]
@vladimirov-s please specify, what proxy are you using? Does "Check connection" show a working connection?

**Comment by maxikuzmin** [comment]
@vladimirov-s please specify, what proxy are you using? Does "Check connection" show a working connection?

**Comment by maxikuzmin** [comment]
@vladimirov-s any news?

**Comment by maxikuzmin** [comment]
@vladimirov-s for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
