### ISSUE TITLE
The remove button should not exist for the AdGuard DNS filter

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4374]
### Issue Details

Built-in AdGuard DNS filter has a remove button, but this filter can not be actually removed from the app. 

<details>
<summary>Screenshot</summary>

![](https://uploads.adguard.org/Screenshot_20230130-143823_AdGuard.jpg)

</details>

### Additional Information

If you have noticed the same, please put the 👍 emoji on this post and leave a comment below.

**Comment by Squall-Leonhart** [comment]
This button removes the current updated list of filters and reverts it to the version included in the apk.
