### ISSUE TITLE
Configuration wizard issues 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4375]
### Issue Details

1. The "Privacy" screen dropdown menu mismatch with the "Tracking protection" settings. 

Tracking protection levels are available: None (disabled), Standard, High, Ultimate. 
Dropdown profiles are available on the Privacy screen from the Configuration wizard: None, Standard, Extended. 

2. The "Security" screen from the configuration wizard does not affect corresponding in-app settings on the "Browsing security" screen.  

### Additional Information

If you have noticed the same, please put the 👍 emoji on this post and leave a comment below.

**Comment by U0101100** [comment]
Confirmation that bug 👍. I have the same result .
