### ISSUE TITLE
Launch AdGuard at system startup option is disabled by default 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4379]
### Issue Details

Launch AdGuard at system startup option is disabled by default after the clean installation. 
In addition, this option is automatically deactivated after updating from the previous nightly version. 

### Additional Information

We are monitoring this issue and are working on the solution.
If you are experiencing the same issue, please put the 👍 emoji on this post and leave a comment below.

**Comment by U0101100** [comment]
Set it up again on settings panel . Is propably not turn on automatically.

**Comment by TPS** [comment]
I don't know if my problem is related? 🤷🏾‍♂️  My toggle for this is _**on**_ (& all the appropriate system settings are correct), but AG v4.0n40 won't autostart;  I must open it myself.

**Comment by Versty** [comment]
@TPS It's not, but may be related to #4361. 
Please read the article linked in this issue.

**Comment by TPS** [comment]
@Versty Replying there.
