### ISSUE TITLE
Webpages occasionally start loading really slow unless Adguard is paused

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#4380]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11 (54)

### Environment

```markdown
- OS: Android 11
- Device: Lenovo Tab P11
- Firmware: Lenovo TB-J606F_S320243_221118_ROW
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies

### Issue Details

Hi there,

My Lenovo tablet occasionally starts loading webpages in Chrome (v.109.0.5414.118) really slow. But as soon as I set Adguard on pause, everything starts loading fast again. 

Is there anything I need to know to resolve this? Such as turning off Adguard DNS filter etc.

Thanks.

**Comment by jbionic2016** [comment]
I've switched from Adguard Family DNS filter to Cloudflare Family DNS, and now everything is working fast again

**Comment by Versty** [comment]
@jbionic2016 Nice one! This problem was definitely caused by temporary difficulties with the specified DNS server.
