### ISSUE TITLE
Centre switches with text rather than aligning to centre of heading

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#4381]
To give better uniformity with Android, the switches should be aligned with all the text and not just the headings to give the appearance that its top aligned.

See below for examples.

![image](https://user-images.githubusercontent.com/95468948/215589839-d7257aeb-2b56-474e-addf-df1bc7a1443d.jpeg)

![image](https://user-images.githubusercontent.com/95468948/215589871-a338fd30-fdcd-4256-8057-5af9727c3ce2.jpeg)

**Comment by Versty** [comment]
@jslawler Got it! Thank for the feedback. 
This issue will be fixed.

**Comment by artemiv4nov** [comment]
Actually, our application is the vision of our designers, not designers by Google:) So, we keep it as is.
