### ISSUE TITLE
Bring back the quick access tile 

### ISSUE THREAD

**Issue by AyuBBlack** [AdguardTeam/AdguardForAndroid#4382]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 
- Device: Samsung  
- Firmware: Galaxy S21 Plus
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Issue Details

The quick access button has disappeared from the control panel curtain.

**Comment by TPS** [comment]
Do you mean the Quick Access shortcut that's positionable?  Because that's what _I_'m missing.

**Comment by J4k-The-Reaper** [comment]
Yes that is also what I noticed after upgrading to this new nightly build. I have the Samsung galaxy s22 ultra and the quick notification toggle disappeared. Hope they fix or bring it back soon. It really came in handy. I loved having it.

**Comment by U0101100** [comment]
I confirmed that issue - I have the same bug . 
On 4.30 i have it on the panel and working normally.  
After updating to 4.39 i can't see it on panel.  
Note 10+. Android 12. Adguard 4.39 Nightly .

**Comment by SyCoREAPER** [comment]
Being someone who hates people who ask this very question because the answer is always "When it's ready" but...

When is the update coming out (approximately) to add it back?

**Comment by TPS** [comment]
This is marked <kbd>Resolved</kbd>, yet I can't locate this in the latest v4.0n54.  Which version will this be published?

**Comment by DrSuSE** [comment]
It's back in today's release (4.0.630).  I did notice, though, that long pressing it no longer takes you to the app like it used to.  Long pressing now takes you to the Android app settings (for like notifications and storage, etc).

**Comment by TPS** [comment]
Well, that's ½way there.  Here's hoping the rest of the functionality returns, too.
