### ISSUE TITLE
What a gorgeous UI!

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#4385]
@AdGuardTeam
I just wanted to say, Wow!   This is amazing!   I'm simply blown away by the work put into this very updated interface.  It fulfills so many wishes from over the years!
Thanks! 🙇🏾‍♂️

@Everyone Else
P.S.:  Yes, there's all kinds of nits & bugs.  (I've seen a few myself.)  Those don't impact anything I've expressed above.  If you've a complaint, please file in another issue.  This post isn't where to do that.  Give credit where it's due!

**Comment by Versty** [comment]
@TPS Thank you! We have shared your feedback with the design team.
