### ISSUE TITLE
Brazilian Portuguese language translation is missing from the app

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardForAndroid#4387]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X ]I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

 4.0 Nightly 39

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy S22
- Firmware: Android 13
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Social Blocking List

### Issue Details

Brazilian Portuguese language translation is missing from the app

### Screenshots

![Screenshot_20230130_232830_AdGuard](https://user-images.githubusercontent.com/16819380/215647867-105f9281-945a-4a02-940e-6fef44bf94bb.jpg)

**Comment by Versty** [comment]
@eduardoaddad Hi! Only English is available for now. 
Read more here #4328.
