### ISSUE TITLE
AdGuard Nightly 4.0ver Bugs

### ISSUE THREAD

**Issue by NoName926** [AdguardTeam/AdguardForAndroid#4388]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

Nightly 4.0.543

### Environment

```markdown
- OS:13
- Device:Samsung 
- Firmware:A53
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion, List-KR

### Issue Details

애드가드 나이틀리 4.0.543 버전에서 발견된 문제

1. 한국어가 아닌 영어로 나옴
2. DNS 보호에 DNS 서버를 시스템 기본 설정 외에 DNS 서버를 적용하면 애드가드 보호가 안 켜짐.

빠른 수정 부탁드립니다.

The problem found in version 4.0.543

1. Appears in English, not Korean
2. If you apply the DNS server to DNS protection, the DNS server other than the system default setting does not turn on the ad guard.

Please make a quick modification.

### Screenshots

![1](https://user-images.githubusercontent.com/99063049/215648613-bd42574c-6f2c-4c3f-a079-1c9d27a51e22.jpg)
![1-2](https://user-images.githubusercontent.com/99063049/215648622-32aa5f1e-6f93-4c73-9fbc-aaf2f2b3fd77.jpg)

![2](https://user-images.githubusercontent.com/99063049/215648626-fac780ec-7c45-4a4f-9356-2ad43d64d27f.jpg)
![2-2](https://user-images.githubusercontent.com/99063049/215648628-6617d1f8-1401-440a-8d03-4a22d60c86c9.jpg)

![other](https://user-images.githubusercontent.com/99063049/215649485-dac34ecb-3666-4bbb-a073-c3b7e670466c.jpg)

**Comment by Versty** [comment]
@NoName926 Hi! Thanks for the feedback. 
English is the only language available for this version #4328. 
For the second issue, the logs from your device would be much appreciated. 
Please [read this guide](https://kb.adguard.com/en/android/solving-problems/log) how to collect debug log and send it to `devteam@adguard.com` with the timestamp in the subject.

**Comment by artemiv4nov** [comment]
The issue is duplicated, please follow for the #4389 issue
