### ISSUE TITLE
Some bugs in v4.0 Nightly 39

### ISSUE THREAD

**Issue by honeytheyeon** [AdguardTeam/AdguardForAndroid#4389]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 Nightly 39

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, Adblock Warning Removal List, List-KR, YousList

### Issue Details

1. Adguard doesn't Work that Any other DNS servers.
2. Missing Other languages. It Only English comes out.
3. Ad blocking Protection is set  "m.dcinside.com" shown broken pages.

**Comment by aespapa** [comment]
and more thing.
Can't old version Installing after delete that exising version.

**Comment by Versty** [comment]
@aespapa Hi! Thank you for participation in nightly testing! 
English is the only language available for now #4328. 
Could you explain what do you mean by `Adguard doesn't Work that Any other DNS servers.`? 
Also, please attach the screenshots of the "m.dcinside.com" broken pages.

Is the problem with installing the old version resolved after restarting the device?

**Comment by aespapa** [comment]
It means only default(system) dns server working. apply other dns server and it will exit.
"m.dcinside.com" broken pages. it was resolved after reinstalling.

**Comment by artemiv4nov** [comment]
I think we have to update the DnsLibs module, and after you can play with a new version.
Will be fixes in a few days.

About languages: please follow for the 4328 issue.

**Comment by admitrevskiy** [comment]
@honeytheyeon Hi!
I see that you've closed the task. Does this mean that the problem is gone?

**Comment by honeytheyeon** [comment]
> Hi!
> I see that you've closed the task. Does this mean that the problem is gone?

I think so.
first problem (DNS server that Initialization after restart) is not recur for me.
and The language(korean) update has already been all translated. Now it's AdGuard's turn.
