### ISSUE TITLE
Can't enable the protection in Root mode.

### ISSUE THREAD

**Issue by Decem6er** [AdguardTeam/AdguardForAndroid#4393]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 39

### Environment

```markdown
- OS: Android 10
- Device: Oneplus 7
- Firmware: Hydrogen OS 10.0.10.GM57
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

Others

### Issue Details

I can't turn the switch on the Root routing mode.

It worked perfectly before I updated it to 4.0 and I have granted the Root permission for Adguard.

### Screenshots

I can't turn the button on.

![image](https://user-images.githubusercontent.com/16839570/215749654-0348b2c9-baca-4079-ac7d-627cb6b68463.png)

**Comment by artemiv4nov** [comment]
@Decem6er  Hello! It seems like ip6tables on your phone doesn't have a NAT table. On another hand, IPv6 can't be filtered in this situation (previously, we just skipped the IPv6 filtering and didn't communicate with user).
Please try to disable the IPv6 filtering in Low-Level settings.

**Comment by artemiv4nov** [comment]
Also, we could improve the current behavior, the update will be soon.

**Comment by Decem6er** [comment]
Thank you very much.
