### ISSUE TITLE
After manually installing the AdGuard Nightly 4.0 build, the "Release" update channel is selected by default

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4394]
After a clean installation of AdGuard Nightly 4.0, the "Release" update channel is selected by default
The same behavior is observed if you manually install AdGuard Nightly 4.0 on the old release version

**Expected Behavior**
After manually installing the AdGuard Nightly 4.0 build, the "Nightly" update channel is selected

**Actual Behavior**
After manually installing the AdGuard Nightly 4.0 build, the "Release" update channel is selected

**Comment by U0101100** [comment]
You can set it up for nightly on the same settings menu . 
Tap settings - general - app and filters updates - app update  channel- change it for nightly.  
Update the application and filters.
