### ISSUE TITLE
Problems with the "quick access tile", access to samfw and github

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#4396]
### Issue Details

_Logs have been deleted for privacy reasons._

After updating the application lost the icon from the top android panel. 

Adguard new setting panel is difficult to use and find someone's settings for ex: app management, filtered apps and setting up new rules for an app. 

Blocking is now a problem - I must pause protection from adguard to open and log in to GitHub on 
Chrome 109.0.5414.117  
Android 12; SM-N975F Build/SP1A.210812.016 . 

The second problem is not properly resolved to block adv and pop-up https://samfw.com/firmware/SM-N975F/XEO. 
Opening and using that site is impossible because popups, anti-adblock scripts and auto-refreshing make this impossible.  

How about DNS filtering from earlier app version . 

### Proposed solution

Add icon or substitute 
Fixing and reinterpretation settings panel , readability of settings, visual perception. 
Fix block advertisement .
DNS settings .

### Alternative solution

Adguard v.4.30

**Comment by maxikuzmin** [comment]
@U0101100 thank you! We know about the "quick access tile", it is mentioned here #4382
We have arranged the settings in such a way that they are more convenient and logical to use.
We understand that it is sometimes difficult to get used to the new interface, but we will not go back to the old layout of the settings :)
The problem with samfw and github does not recur to me. Try disabling all filters and trying again. Is the problem still recurring? Could you please attach screenshots of the pop-ups?
Also, please clarify what is wrong with DNS filtering?

**Comment by maxikuzmin** [comment]
@U0101100 any news?

**Comment by maxikuzmin** [comment]
@U0101100 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
