### ISSUE TITLE
Network type does not work correctly with android 7 

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4397]
### AdGuard version

4.0

### Environment

```markdown
- OS: Android 7
```

**Steps to reproduce**

Open AdGuard -> go to "Statistics" tab -> tap to "Any" next to Requests, Data usage, DNS statistics -> tap to Cellular or Wi-Fi
Statistics with the selected filter on Cellular or Wi-Fi are displayed in zero value

**Expected Behavior**
Statistics with the selected filter on Cellular or Wi-Fi is displayed depending on the spent traffic on the selected network

**Actual Behavior**
Statistics with the selected filter on Cellular or Wi-Fi is not displayed depending on the spent traffic on the selected network, a zero value is displayed

**Comment by U0101100** [comment]
Confirm.  Network connection not working properly when adguard is on .
Connection has been stopped working and  crashing . 
I must restarting phone and / or paused protection.  
Now I used the Quit function to get the connection back at all.
