### ISSUE TITLE
Adguard is unable to determine connection origin

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#440]
From the log of one user:

```
DEBUG c.a.a.filtering.commons.LogUtils - TCP id=51834 Creating new connection null with packet TCP 172.16.16.1:38534 > 31.13.72.8:443 [SYN] seq=1287587523 ack=0 win=65535 mss=8960 scale=8 len=0
```

After that we had an issue #344, but that was a simptome, not the cause. We need to fix determination of ConnectionInfo to work normally.

**Comment by ameshkov** [comment]
Why, it happens sometimes for instance when app closes this connection right after creation

**Comment by Revertron** [comment]
But I see many such connections in the log of some user. He claims that in this moment all aps and browsers refused to work.

**Comment by ameshkov** [comment]
> But I see many such connections in the log of some user. He claims that in this moment all aps and browsers refused to work.

Not sure if this is possible to fix. What we should check though is that AG does not block such connections on purpose.

**Comment by ameshkov** [comment]
CoreLibs
