### ISSUE TITLE
completely new interface design on adguard v4 android

### ISSUE THREAD

**Issue by lvtinh89** [AdguardTeam/AdguardForAndroid#4400]
### Issue Details

i tried first version of Adguard V4 on android . This design is available on ios, now it's on android, why don't you guys completely refresh with Material You interface like android 13

### Proposed solution

 you guys completely refresh with Material You interface like android 13

**Comment by BlazDT** [comment]
At least add an option to have the old interface.

**Comment by maxikuzmin** [comment]
@BlazDT I understand that sometimes it is difficult to get used to something new, but the option to switch to the old interface, we will not do.
I'm sure you will quickly get used to the new design, because it is more convenient and logical :)
