### ISSUE TITLE
DNS filters -> User rules gets deleted on app restart

### ISSUE THREAD

**Issue by crsag** [AdguardTeam/AdguardForAndroid#4401]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 39

### Environment

```markdown
- OS: Android 13
- Device: Pixel 4 XL
- Firmware: TP1A.221005.002
```

### Root access
No

### Issue Details

DNS protection -> DNS filters -> User rules gets deleted on app restart

**Steps** **to** **reproduce**

•Turn off Adguard Protection

•Go to DNS protection -> DNS filters -> User rules -> Add any rule

•exit the app -> clear app from recent apps (or Force stop app from App info)

•reopen the app and check DNS filters -> User rules.

### Expected Behavior

All the Filters stays saved

### Screenshots

[Screen recording ](https://youtube.com/shorts/6YO76dXlAxI?feature=share)

**Comment by crsag** [comment]
[Screen recording ](https://youtube.com/shorts/6YO76dXlAxI?feature=share)

**Comment by TigerBeanst** [comment]
same here
