### ISSUE TITLE
Drop "Browsing Security"

### ISSUE THREAD

**Issue by ch00xh** [AdguardTeam/AdguardForAndroid#4415]
### Issue Details

All major browsers have a built-in browsing security feature to block phishing and malware. Why keep this feature in AdGuard if it is redundant! The filters can be placed in the "Content Blocking" section.

**Comment by maxikuzmin** [comment]
@ch00xh in most cases third-party "phishing and malware" protection is more effective than standard browser protection. We have a database of suspicious domains from several sources and are regularly updated thanks to our users.
Also, anti-phishing in programs is triggered before filters.
You can read more about "how Browsing Security works" [here](https://adguard.com/kb/general/browsing-security/#how-does-a-check-work)
But if you trust the default browser protection more, you can always turn off "Browsing Security" :)
We are just trying to give more protection to our users
