### ISSUE TITLE
AdGuard disabled after updates

### ISSUE THREAD

**Issue by SyCoREAPER** [AdguardTeam/AdguardForAndroid#4421]
Not assisting anymore with wiseasses like these around. Issue closed.

**Comment by Disqu3-mirOir-qt** [comment]
#4419 duplicate

**Comment by SyCoREAPER** [comment]
> #4419 duplicate

My issue has nothing at all to do with 4419.

4419 talks about crashing after update. Mine does not crash, protection is disabled.

**Comment by SyCoREAPER** [comment]
@Versty

Please reopen. Github mod erroneously connected this to a completely different issue.

**Comment by Squall-Leonhart** [comment]
disable dns filtering for the time being, it is the cause of protection failing to enable.

**Comment by SyCoREAPER** [comment]
Never had an issue before. Been on nightlies for over 3 years.

**Comment by Squall-Leonhart** [comment]
> Never had an issue before. Been on nightlies for over 3 years.

this and the impossibility to auto update to nightly 41 are concerns.

**Comment by SyCoREAPER** [comment]
> > Never had an issue before. Been on nightlies for over 3 years.
> 
> this and the impossibility to auto update to nightly 41 are concerns.

Nightly isn't just one build you duncecap. And HTTP filtering has nothing to do with the apps ability to turn its toggle on and off.

You clearly have no idea what you are talking about so move along.

**Comment by Squall-Leonhart** [comment]
Adguard crashes when trying to start the Nightly 41 download, and the DNS Filtering is 100% why you can't start Protection.


Mind your mouth, brat.

**Comment by SyCoREAPER** [comment]
"brat" lol thought you were a boomer until I saw your Adult Cartoons aka Anime.

I don't have http filtering enabled so the joked on you 🤡

**Comment by SyCoREAPER** [comment]
"brat" lol thought you were a boomer until I saw your Adult Cartoons aka Anime.

I don't have http filtering enabled so the joked on you 🤡

**Comment by Versty** [comment]
@Squall-Leonhart Hi! We are working on the fix. This issue will be resolved as soon as possible. 
You can read more and discuss in #4419.
