### ISSUE TITLE
Real dark mode (not pitch black)

### ISSUE THREAD

**Issue by resiehnnes** [AdguardTeam/AdguardForAndroid#4426]
### Issue Details

Current dark theme in adguard has solid black background, which is usually referred as "Black" or "Amoled" theme in many android apps . Some people including me trying to avoid using pure black color themes on their smartphones because it makes eyes feel uncomfortable. 

### Proposed solution

Please consider adding additional theme with darker tones. Here is an example:

![adguard_darkmode](https://user-images.githubusercontent.com/52158526/216793948-a24d13d5-bb77-4210-9489-b206324f0b36.png)

**Comment by maxikuzmin** [comment]
@resiehnnes that’s interesting feature request. Let’s see how many likes it will gain.

**Comment by resiehnnes** [comment]
@yuukiAme This was a feature request, not an issue. And it looks like from the recent update Adguard has a true dark theme (not black as it was before) which is great. But I agree that it would be nice to give a user an option to use "Amoled" theme as a variation of "Dark" theme. You could create a new feature request for this.
