### ISSUE TITLE
Cosmetic issue on statistics (Dark Theme only)

### ISSUE THREAD

**Issue by McGyver1979** [AdguardTeam/AdguardForAndroid#4430]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.570

### Environment

```markdown
- OS: Android 12 (Magic UI 6.0)
- Device: Honor 50 5G
- Firmware: NTH-NX9
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Open Statistics area
2. Check colors

### Expected Behavior

I assume that labels' and bars' colors have to be coherent, depending on type

### Actual Behavior

Apparently not as expected. Marginal issue

### Screenshots

<details><summary>Screenshot 1:</summary>

![Adguard - Statistics](https://user-images.githubusercontent.com/124535721/217294001-136fac97-f205-4a65-a075-adef52b84ce2.jpeg)

</details>

**Comment by maxikuzmin** [comment]
@McGyver1979 got it! Thanks for the feedback.
This issue will be fixed.
