### ISSUE TITLE
Incorrect description for local IPv4/IPv6 in Local VPN section of low-level settings

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#4433]
Version: 4.0 nightly 43

This description seems to be same as for "Custom IPv4 address" in DNS section.

While setting is about local IP address on Local VPN interface.

The same is for IPv6 address setting in this section.

<img width=250 src=https://user-images.githubusercontent.com/47204/217458518-e3cc3b39-0839-4a6d-80b5-8f316af4a44c.png />

**Comment by maxikuzmin** [comment]
@sfionov got it! Thanks for the feedback.
This issue will be fixed.
