### ISSUE TITLE
Automation `proxy_state` does not affect proxy state (enable or disable)

### ISSUE THREAD

**Issue by tmknight** [AdguardTeam/AdguardForAndroid#4438]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0578

### Environment

```markdown
**Filtering mode:**
  - Local VPN
**Device:**
  - LG V30+ (H932)
**Operating system and version:**
  - Android 9
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Using `Automate` or `Automateit` to execute a send broadcast intent results in no action on the outbound proxy, regardless of enable:true/false

### Expected Behavior

Enable or disable outbound proxy depending on value passed

### Actual Behavior

No action is taken, other than the AdGuard local VPN "restarting" and last state of proxy remains unchanged

### Additional Information

This issue persists on 4.0 nightly (4.0578); I feel this should remain open to ensure it is correctly tracked.

**Comment by tmknight** [comment]
Indeed that did the trick.  Seems documentation needs updating (`receiver` vs `receivers`) or is this limited to proxy as I recall other API functions worked with `receivers`?

**Comment by Versty** [comment]
@tmknight Yes, this is new to 4.x versions and we will definitely update our guide before the release!
