### ISSUE TITLE
App frequently crash

### ISSUE THREAD

**Issue by kongacute** [AdguardTeam/AdguardForAndroid#4446]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.582

### Environment

```markdown
- OS:Android 13
- Device:Samsung Galaxy Z Fold3
- Firmware:One UI 5.0
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, ABPVN List

### Issue Details

Steps to reproduce:
1. Using device normally
2. Sometime app crashed.

### Expected Behavior

App not crashed

### Actual Behavior

App randomly crash

### Screenshots

<details><summary>Screenshot 1:</summary>

![SmartSelect_20230209_101701_Device care](https://user-images.githubusercontent.com/30176126/217710059-3839768b-e1ff-4fec-aec9-86b26e1cfd17.jpg)

</details>

**Comment by aespapa** [comment]
I second that. It keeps crashing in unspecified situations and close the Adguard

**Comment by crsag** [comment]
Same. I don't get notification but app restarts randomly in background.

**Comment by kongacute** [comment]
Look like forcing HTTPS filtering for apps not expected might make the app crash.

**Comment by maxikuzmin** [comment]
@kongacute @crsag @honeytheyeon we need your debug logs

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

Or you can attach debug logs right here

**Comment by crsag** [comment]
> @kongacute @crsag @honeytheyeon we need your debug logs
> 
> Here's what we need you to do:
> 
> * Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> * Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> * Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
> * Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.
> 
> Or you can attach debug logs right here

I already reported this issue via Adguard for android's in app bug report. They asked me for the same. I sent them extended bug report and all the timestamps. 

Ticket  718859.

**Comment by kongacute** [comment]
> @kongacute @crsag @honeytheyeon we need your debug logs
> 
> Here's what we need you to do:
> 
> - Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> - Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> - Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
> - Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.
> 
> Or you can attach debug logs right here

The app crashed around 10:30 AM (not sure as I woke the device up and the app already crashed and did not restart again).
The log files are larger than 35MB so I will upload them to OneDrive and the link shared below.
[https://1drv.ms/f/s!AjVM-TnmSFnqiaFAG5kFI6TA-YAkJw](Link to logs file via OneDrive)

**Comment by maxikuzmin** [comment]
@crsag @kongacute thank you! We'll look into your logs

**Comment by kongacute** [comment]
> @crsag @kongacute thank you! We'll look into your logs

[adguard_logs_4.0.601_1602_164805.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10754522/adguard_logs_4.0.601_1602_164805.zip)
Another crash log from my other devices. Take right after crashed (app crashed and I go into app to grab log).

**Comment by mevicks** [comment]
Logs for crashes on Vivo nex issue #4469 
Adguard Support Ticket R860DR-6QOWX

https://www.dropbox.com/s/h2b972xbwllcgzh/adguard_logs_4.0.570_0702_151019.zip?dl=0

https://www.dropbox.com/s/xk39g3h3sxsmkl3/adguard_logs_4.0.578_0802_102121.zip?dl=0

https://www.dropbox.com/s/1m84jzvd7z5bls3/adguard_logs_4.0.590_1302_144307.zip?dl=0

**Comment by maxikuzmin** [comment]
@crsag @kongacute @honeytheyeon please observe this problem on nightly version 50. 
Is it still repeating?

**Comment by kongacute** [comment]
> @crsag @kongacute @honeytheyeon please observe this problem on nightly version 50. 
> Is it still repeating?

1 day after using version 50, I didn't see any crashes so far.

**Comment by kongacute** [comment]
> @crsag @kongacute @honeytheyeon please observe this problem on nightly version 50. 
> Is it still repeating?

Just got crashed with version 51. Will change the log level and report back if it crashes again.

**Comment by crsag** [comment]
> @crsag @kongacute @honeytheyeon please observe this problem on nightly version 50. Is it still repeating?

I tested version 50 for only 1-2 days and it didn't crash for me, or I didn't notice any. 

After upgrading to version 51, it immediately started crashing after 30-40 minutes. But unlike before, it reconnects in just 1-2 seconds (before v50 it used to take 30-40 seconds to reconnect).

I noticed that the VPN 🗝️ icon disappears/reappears for a second, and the Adguard Protection notification shows this message for a sec.
![Screenshot_20230219-194627](https://user-images.githubusercontent.com/16190789/219968367-54a9daa7-d44a-41e2-811b-6789410ec7c1.png)


This happens every 20-40min.

I sent Adguard logs and timestamps to devteam@adguard.com

**Comment by maxikuzmin** [comment]
@kongacute I don't see your logs. Please send them again

**Comment by kongacute** [comment]
> @kongacute I don't see your logs. Please send them again

I sent OneDrive link via mail. Please check that.

**Comment by kongacute** [comment]
> @crsag it's really similar, but still "crashes" usually refers to a complete exit from the application or its suspension/application crash.
> @kongacute @honeytheyeon @mevicks could you clarify, do you mean a sudden complete exit from the application / suspension of the application? Or did you mean a randomly restart of protection?

It's crash. Like randomly, no matter the protection status. I tried 2 days to turn off protection and it still shows a system crash popup indicating that AdGuard crashed in the background. Ofc, I disabled battery optimization, and allow data connection while in data saver mode.

PS: I cannot use AdGuard Nightly anymore as it's crashed so much since version 48 (as I remember). Now back with the beta channel currently.

**Comment by michael1900** [comment]
> @crsag it's really similar, but still "crashes" usually refers to a complete exit from the application or its suspension/application crash.
> @kongacute @honeytheyeon @mevicks could you clarify, do you mean a sudden complete exit from the application / suspension of the application? Or did you mean a randomly restart of protection?

From all the logs posted still no possible to fix this bug?

**Comment by maxikuzmin** [comment]
@michael1900 @kongacute we are still looking into the problem

**Comment by michael1900** [comment]
> @michael1900 @kongacute we are still looking into the problem

Had the first "crash" today with last nightly, that with booting problem finally fixed. Go to unlock the phone and adguard was closed and also the vpn. Only one time for now, android 10, never happened on Stable version obviously. It's completely random so it's really impossibile to take log. But we are on the right track I think. Thanks

**Comment by honeytheyeon** [comment]
I think randomly restart of protection. 
 It works well when browsing or doing somthing else and then restarts. even i do not anything that restarted.

**Comment by maxikuzmin** [comment]
@michael1900 @honeytheyeon anyway, if you manage to catch this crash, unload the logs immediately. Don't forget to select "Debug" logging level. 
We are still dealing with this problem

**Comment by maxikuzmin** [comment]
@michael1900 @honeytheyeon any news?

**Comment by maxikuzmin** [comment]
@michael1900 @honeytheyeon for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
