### ISSUE TITLE
Automation (i.e. Tasker) Not Working

### ISSUE THREAD

**Issue by jwds1178** [AdguardTeam/AdguardForAndroid#4449]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 45

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy Z Flip4 (SM-F721W)
- Firmware: Build #TP1A.220624.014.F721WVLU1BVL9
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Enable automation within AdGuard via _Settings » General » Advanced » Automation_.
2. Create a task within Tasker to send the intents (i.e. start, stop) to AdGuard.

### Expected Behavior

AdGuard should be started or stopped as per the Tasker task.

### Actual Behavior

Nothing happens.

### Screenshots

<details>

**AdGuard - Settings:**
![Screenshot_20230208_124030_AdGuard](https://user-images.githubusercontent.com/68513920/217916606-a95eebb3-e20b-4dee-b11f-1138cfc1d12a.png)

**Tasker - Intent to Start:**
![Screenshot_20230208_124209_Tasker](https://user-images.githubusercontent.com/68513920/217916609-6bb1c0f5-be25-4661-82a9-88da5f75eee0.jpg)

**Tasker - Intent to Stop:**
![Screenshot_20230208_124146_Tasker](https://user-images.githubusercontent.com/68513920/217916608-e2918ffe-8d23-45c1-bb8d-67aa3efb26a5.jpg)

</details>

### Additional Information

AdGuard support request #720760 advised to create an issue here…

I'd use the intents fine with v3.x of AdGuard, but hadn't needed them in a while.  I've just recently found a need for them again.  However, they don't appear to be working with v4.x though.

Possibly, related to issue #4438?

**Comment by Versty** [comment]
@jwds1178 Hi! This issue is a duplicate, please continue the discussion in #4395.
