### ISSUE TITLE
Notification still show route traffic to proxy when proxy setting is turn off

### ISSUE THREAD

**Issue by kongacute** [AdguardTeam/AdguardForAndroid#4450]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.585

### Environment

```markdown
- OS:Android 13
- Device:Samsung Galaxy Z Fold3 5G
- Firmware:One UI 5.0
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, ABPVN List

### Issue Details

Steps to reproduce:
1. Setup manual Proxy routes.
2. Turn on proxy.
3. Turn off proxy.
4. Observe notification.

### Expected Behavior

Notification show disconnected from manual proxy with options to reconnect to proxy again.

### Actual Behavior

Notification still show route all traffics to manual proxy. No button to reconnect to proxy.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230210_091838_AdGuard](https://user-images.githubusercontent.com/30176126/217984538-0988e43a-cfe7-4c88-a8d4-ab1080d49fda.png)
![Screenshot_20230210_091853_AdGuard](https://user-images.githubusercontent.com/30176126/217984547-28d2c3a6-bf80-4d9e-8ce3-6191f582a381.png)

</details>

**Comment by maxikuzmin** [comment]
@kongacute I don't have this problem repeated.
Is this still repeated on the nightly version 48?

**Comment by kongacute** [comment]
> @kongacute I don't have this problem repeated.
> Is this still repeated on the nightly version 48?
> 

Look like it is fixed.

**Comment by maxikuzmin** [comment]
@kongacute for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
