### ISSUE TITLE
Add Mulch (us.spotco.mulch) to browsers list

### ISSUE THREAD

**Issue by statesecret** [AdguardTeam/AdguardForAndroid#4454]
### Issue Details

> https://gitlab.com/divested-mobile/mulch

> https://divestos.org/fdroid/official?fingerprint=E4BE8D6ABFA4D9D4FEEF03CDDA7FF62A73FD64B75566F6DD4E5E577550BE8467

latest apk for reference
> https://divestos.org/fdroid/official/Mulch-arm64-110.0.5481.64-1.apk

**Comment by maxikuzmin** [comment]
@statesecret got it! Thanks for the feedback.
This issue will be fixed.
At this point you can go to Settings -> Filtering -> Apps -> App management -> select Mulch browser -> enable HTTPS filtering
