### ISSUE TITLE
Turkish language in nightly version 4.0

### ISSUE THREAD

**Issue by senolfndk** [AdguardTeam/AdguardForAndroid#4457]
### Issue Details

can you add turkish language in app

**Comment by maxikuzmin** [comment]
@senolfndk of course! We will definitely add Turkish a little later, but right now the app only has English.
Please, just wait a bit :)
Read more here https://github.com/AdguardTeam/AdguardForAndroid/issues/4328.

**Comment by Verbatix** [comment]
> @senolfndk of course! We will definitely add Turkish a little later, but right now the app only has English. Please, just wait a bit :) Read more here #4328.

When will the Polish language in the nightly android version be available? An unofficial version with Polish is available online.

**Comment by senolfndk** [comment]
> > @senolfndkElbette! Biraz sonra mutlaka Türkçe ekleyeceğiz ama şu anda uygulamada sadece İngilizce var. Lütfen biraz bekleyin :) Daha fazlasını buradan okuyun #4328 .
> 
> Gecelik android sürümündeki Lehçe dili ne zaman kullanıma sunulacak? Lehçe ile resmi olmayan bir versiyonu çevrimiçi olarak mevcuttur.

ok

**Comment by Verbatix** [comment]
I personally have the latest version of nightly in Polish.
I'm not a programmer, but I added the Polish language myself.

**Comment by Verbatix** [comment]
[The latest version of nightly with Polish language!](https://ibb.co/PZfGrcV) 
Nightly version with amateur translation 😁
