### ISSUE TITLE
[v4.0] Make access to Allowlist and other features on Protection screen more obvious

### ISSUE THREAD

**Issue by anastler** [AdguardTeam/AdguardForAndroid#4459]
### Issue Details

On the Protection screen in v4.0 (nightly), it is not obvious that features themselves can be tapped, and that you can access their settings that way.

For instance, an important feature such as Allowlist could be hard to find because of this.

<img width="642" alt="protection-screen" src="https://user-images.githubusercontent.com/124886335/218384054-3738851a-97fa-4b70-9431-56dcb6943b3e.png">

### Proposed solution

Add a clear indication that not only toggles but the fields themselves can be tapped. For example, by adding ">" mark to the fields (like the one on the screenshot)

<img width="845" alt="indication" src="https://user-images.githubusercontent.com/124886335/218414285-b1e82cd8-5c8f-4a1b-bf9f-1dfd4a42f14f.png">

**Comment by maxikuzmin** [comment]
@anastler but that's why we separated toggles with a line :)
">" next to "AdGuard VPN" because there is no toggle
If ">" is next to toggles, it will point directly to toggles and confuse
I don't think we would add ">", but if you have any more suggestions, by all means start more issues
