### ISSUE TITLE
Missed ads in youtube and Tumblr app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#446]
HTTPs is on, but we still have ads in these two apps

HTTP log: UPA-505-15399

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/14476155/cb4e968a-010e-11e6-8583-81c0ba84f14b.png)
![image](https://cloud.githubusercontent.com/assets/15856304/14476160/d1cc8044-010e-11e6-93a8-66c0ac380a06.png)

**Comment by ameshkov** [comment]
@Alex-302 could you please take a look?
