### ISSUE TITLE
Adguard auto switch off

### ISSUE THREAD

**Issue by HB2244** [AdguardTeam/AdguardForAndroid#4460]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 46

### Environment

```markdown
- OS:Android 13
- Device:Samsung Note 20 Ultra
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Issue Details

Steps to reproduce:
1. Adguard switch to off after starting & every time I switch it to on it will go to off after few mints.
2.
3.

### Expected Behavior

Adguard will be on till I switch it off

### Actual Behavior

it switch off automatically

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@HB2244 please check if this problem recurs in the nightly 49 version?
If the problem still repeats, could you record a video of the screen and attach it right here?

**Comment by maxikuzmin** [comment]
@HB2244 any news?

**Comment by maxikuzmin** [comment]
@HB2244 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
