### ISSUE TITLE
v4: Add a traffic statistics page like v3

### ISSUE THREAD

**Issue by oldshensheep** [AdguardTeam/AdguardForAndroid#4461]
### Issue Details

v4
![Screenshot_20230214142940](https://user-images.githubusercontent.com/29306733/218658687-9099c654-f546-4267-a4db-f351311fcca1.png)
v3
![Screenshot_20230214143202](https://user-images.githubusercontent.com/29306733/218658852-84e5dab4-04ee-4a39-b69a-aa367c251239.png)

**Comment by maxikuzmin** [comment]
@oldshensheep if you click on any app from the list, you will see the necessary statistics, please try it

**Comment by oldshensheep** [comment]
Yes, I have tried.
But I think traffic usage is more important than the number of requests, because although some applications have many requests, none of the requests are blocked.
Showing traffic data can help me better understand data savings and help me identify which apps are using more data.
Currently, I have to click one by one, which is very annoying.

**Comment by maxikuzmin** [comment]
@oldshensheep at this point we won't change it, maybe in the future we'll improve it.
Thank you, we'll take your wishes into consideration anyway!
