### ISSUE TITLE
The filter update list is not displayed.

### ISSUE THREAD

**Issue by honeytheyeon** [AdguardTeam/AdguardForAndroid#4463]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

ver 4.0.594

### Environment

```markdown
- OS:aos13
- Device:galaxy
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

After updating a filter, the list of updated filters is not displayed.
In fact, this problem is about 2 weeks ago. 

### Actual Behavior

![Screenshot_20230214_191053_AdGuard](https://user-images.githubusercontent.com/92372212/218706322-36ed0614-b8bc-4dab-a17e-7e540e1edeb7.png)

**Comment by maxikuzmin** [comment]
@honeytheyeon in the screenshot it says that you are using the latest version of the filters. Please try including some additional filters that were not included before, then click on "update"
You will see how many filters have been updated, and after clicking on "Content blocker filters" you will see which filters have been updated

**Comment by honeytheyeon** [comment]
> @honeytheyeon 스크린 샷에는 최신 버전의 필터를 사용하고 있다고 나와 있습니다. 이전에 포함되지 않은 몇 가지 추가 필터를 포함시킨 다음 "업데이트"를 클릭하십시오. 얼마나 많은 필터가 업데이트되었는지 확인하고 "콘텐츠 차단 필터"를 클릭하면 어떤 필터가 업데이트되었는지 확인할 수 있습니다.

In the past, it was displayed which filters were updated.
but Now that a new version is released, even if update it, it says it's updated to the latest version.
It does not show which filters have been updated to the latest level.

**Comment by maxikuzmin** [comment]
@honeytheyeon if you have already updated the filters, there may not be a new filter update.
"_Please try including some additional filters that were not included before, then click on "update"
You will see how many filters have been updated, and after clicking on "Content blocker filters" you will see which filters have been updated_" - did you do this?

**Comment by maxikuzmin** [comment]
@honeytheyeon any news?

**Comment by honeytheyeon** [comment]
> @honeytheyeon any news?

still,,, but Anyway, Good Solution.
