### ISSUE TITLE
White splash and loading screens in the dark theme 4.0 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4464]
### AdGuard version

4.0 nightly

### Issue Details

Steps to reproduce:
1. Set the dark theme 
2. Quit AdGuard 
3. Launch AdGuard

<details><summary>Screencast</summary>

[Video](https://uploads.adguard.org/Screenrecorder-2023-02-14-14-49-52-432.mp4)

</details>

### Expected Behavior

Splash and loadings screens are black in the dark theme 

### Actual Behavior

Splash and loadings screens are white in the dark theme

**Comment by Numci** [comment]
It's ok right now. Maybe change it later

**Comment by TPS** [comment]
I'm sorry, _which_ version is this resolved within?

**Comment by Versty** [comment]
@TPS We decided to postpone this fix, for now splash and loading screens work similarly to AdGuard VPN for Android.
