### ISSUE TITLE
DNS filtering not working with DNS over DoH

### ISSUE THREAD

**Issue by Dogoo9** [AdguardTeam/AdguardForAndroid#4468]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.599

### Environment

```markdown
- OS: Android 13
- Device: Oneplus8T
- Firmware: F.15
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC

### Issue Details

Steps to reproduce:
1. Add any custom DNS over TLS or DNS over DoH server in DNS Protection.
2. Select the Custom DNS server.

### Expected Behavior

Expected for Adguard to start all protection modules and not immediately fail.

This was working prior to the 4.0 update 

### Actual Behavior

I added adguards DNS over TLS to the custom DNS servers as per the instructions in adguard DNS and it seems that anytime it is selected, it's causing a crash of the DNS protection module.

IPv4 DNS addresses still function normally.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

This happens regardless of snds:// or DoH query address's selected, wether it's adguard or mullvad or another service. 

Reinstalling the application doesn't resolve the issue either.

I'm assuming it's crashing the dnsproxy.so library when it's loaded. I'll provide logs if needed.

**Comment by Dogoo9** [comment]
Pasting in logs.
[adguard_logs_4.0.611_1902_031320.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10774701/adguard_logs_4.0.611_1902_031320.zip)

**Comment by sfionov** [comment]
@Dogoo9 Thank you for logs! Can you please collect logs with debug logging on?

1. Open AdGuard and go to "Settings".

2. Choose "Advanced".

3. Set "Logging level" to "Debug". It's desirable to close all background apps that don't concern the problem beforehand.

4. Turn on "Auto-report crashes".

5. Reproduce the problem and set the logging level back to "Default". Notice the exact time when it happened.

6. Tap "Export logs and system info", save and send logs to devteam@adguard.com

**Comment by Dogoo9** [comment]
> @Dogoo9 any news?

Sorry about taking so long with getting back to you, been busy with work and irl stuff. 

I've just sent the logs through now as per your instructions.

**Comment by maxikuzmin** [comment]
@Dogoo9 thank you! We'll look at your logs, we need some time

**Comment by Dogoo9** [comment]
Looks like the latest update fixed the issue, thanks for your help!

**Comment by Squall-Leonhart** [comment]
> Looks like the latest update fixed the issue, thanks for your help!

nah, still happens.

**Comment by maxikuzmin** [comment]
@Squall-Leonhart to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment]
@Squall-Leonhart any news?

**Comment by maxikuzmin** [comment]
@Squall-Leonhart for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
