### ISSUE TITLE
Latest 4.0 nightly keeps crashing on Android 10

### ISSUE THREAD

**Issue by mevicks** [AdguardTeam/AdguardForAndroid#4469]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

nightly 4.x

### Environment

```markdown
- OS: Android 10
- Device: Vivo Nex (1805)
- Firmware: PD1805F_EX_A_8.70.9
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
As mentioned to customer support the crashing is just random with the logs attached herewith. Most of the time it's during watching of long duration streams on Yotube in full-screen within Firefox browser, the app just stops randomly. 

As mentioned to support there is no option to disable battery optimization on the phone settings, so had to use adb to do it. Even after that the app kept crashing. Moreover the stable version 3 never required any sort of special treatment (disabing battery optimisation etc)

### Actual Behavior

App stops randomly

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@mevicks Hi! 
Seems like this issue is a duplicate. 
Please continue discussion in #4446

**Comment by michael1900** [comment]
Had the first "crash" today with last nightly, that with booting problem finally fixed. Go to unlock the phone and adguard was closed and also the vpn. Only one time for now, android 10, never happened on Stable version obviously. It's completely random so it's really impossibile to take log. But we are on the right track I think. Thanks
