### ISSUE TITLE
Yandex navigator & HTTPs filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#447]
После всех обновлений Яндекс.Навигатора, включая сегодняшнее 13.04.2016, при включённой фильтрации не подхватываются мои места из учётки Яндекса. Яндекс.Навигатор ругается на прослушку канала, что, в общем-то, логично. Всё подхватилось после временного отелючения AdGuard

WSR-311-92886

**Comment by Revertron** [comment]
I propose excluding domain "mobile.yandex.net" from HTTPS-filtering.

**Comment by ameshkov** [comment]
But as I understand this is already done.

**Comment by Revertron** [comment]
Apparently, yes. I thought that I've added it in my list only.
With that domain in whitelist we have no issues with Yandex apps.

**Comment by Revertron** [comment]
Done.

**Comment by vgavrish** [comment]
При поиске того или иного элемента или выбора избранных нет предложенных мест. 
Помогает отключение HTTPS
id 1073741
<details>
![screenshot_40](https://cloud.githubusercontent.com/assets/18548949/17076143/b80e4350-50b3-11e6-80f7-bcbcab6a30d7.jpg)
![screenshot_41](https://cloud.githubusercontent.com/assets/18548949/17076144/b814a74a-50b3-11e6-84a1-27ed44cc2718.jpg)

**Comment by ameshkov** [comment]
@nkartyshov смотри последний комментарий

**Comment by nkartyshov** [comment]
Добавил в исключения https
