### ISSUE TITLE
Protection is disabled after updating the app

### ISSUE THREAD

**Issue by edlefh** [AdguardTeam/AdguardForAndroid#4472]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 39

### Environment

```markdown
- OS:Android 10
- Device:Samsung Galaxy s9
- Firmware:N/A
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Dutch filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList, EasyList Dutch

### Issue Details

Steps to reproduce:
1. Update app (after message) while app is active
2. "Open" app instead of "ready"
3. App deactivated, manually activate

### Expected Behavior

After update reactivate

### Actual Behavior

After I gaot the message to update, I update app. After updating I go to open the app and see it is deactivated and stays that way. Previously it would restart after the update, but since version 4 I noticed the ads returning and concluded app is not working anymore. Had to manually activate again.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Konfetti030** [comment]
Same problem here. After updating the app protection is deactivated.

**Comment by anphucnguyen** [comment]
Even if activate protection manually, it's disabled after a while

**Comment by Batman2814** [comment]
Same here after updating Adguard for Android have to toggle the switch on manually.

**Comment by Konfetti030** [comment]
Same here. Plus that protection sometimes switches to disabled
