### ISSUE TITLE
Banking App Octo Mobile (id.co.cimbniaga.mobile.android) v3.0.0 Detects AdGuard

### ISSUE THREAD

**Issue by christantoan** [AdguardTeam/AdguardForAndroid#4481]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest stable version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v3.6.11+(54)

### Environment

```markdown
- OS: Android 11
- Device: OnePlus
- Firmware: Oxygen OS 11.0.9.1.GM21BA
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

_Not applicable_

### What Stealth Mode options do you have enabled?

_Not applicable_

### Issue Details

Steps to reproduce:
1. Install AdGuard's certificate
2. Run Octo Mobile app

### Expected Behavior

Octo Mobile app runs normally.

### Actual Behavior

Octo Mobile app v3.0.0 errors out with random error_ID number and "Fake SSL certificate detected" error message.

### Screenshots

<details><summary>Screenshot 1: error_ID:19</summary>

![Screenshot_20230218-094347](https://user-images.githubusercontent.com/7300310/219829450-269157a2-5608-4ee3-9256-57d53c3b0d2e.png)

</details>

<details><summary>Screenshot 2: error_ID:22</summary>

![Screenshot_20230218-095024](https://user-images.githubusercontent.com/7300310/219829477-11413c8b-502f-465f-8738-e1d3bddf4f0a.png)

</details>

### Additional Information

The app detects if an AdGuard certificate is installed in User store (though I haven't checked with other certificate installed there). It's okay if the cert is installed only to the System store (i.e. deleting the certificate from User store but not rebooted the device yet to apply changes to Zygisk module). The user and system stores I mentioned are the ones inside Trusted credentials page and not User credentials page.

I have also reported via ticket #724593.

I have since found a workaround but I'm not sure to share it here to prevent the developer from updating their detection logic.

**Comment by bogachenko** [comment]
It is better to disable https filtering for all banking applications.

a random person, not an employee of adguard.

**Comment by christantoan** [comment]
> It is better to disable https filtering for all banking applications.
> 
> _i am a random person, not an employee of adguard._

I know and I've done that for the app but it still detects and gives error.

**Comment by christantoan** [comment]
As of version 3.0.1, the app no longer detects AdGuard and no longer needs my workaround.

I'm attaching the [old version (3.0.0)](https://files.catbox.moe/92lje4.zip) (sorry for external link, the file's too big for GitHub) that detects AdGuard for investigation as it can be used to learn how apps detect AdGuard.

Not sure if I should close this issue.

**Comment by Versty** [comment]
@christantoan Thank you! Glad it is fixed.
We are currently working on the completely new version of AdGuard for Android and will take into account possible issues with the Octo Mobile app.
