### ISSUE TITLE
Root mode causes images in some apps to not be displayed

### ISSUE THREAD

**Issue by shugo-chara** [AdguardTeam/AdguardForAndroid#4483]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS:Andorid13
- Device: MIX FOLD 2
- Firmware:MIUI DEV
- Root mode: Magisk 25
- Power saving mode: off
- Background lock: On
- Background status: Normal
- OS: Completely reinstalled Android13
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

No filters

### Issue Details

After enabling filter protection, I noticed that some of the apps were affected in a strange way. None of the images in these apps were displayed correctly and some of them were even unable to connect to the network.

To troubleshoot the problem, I turned off each function one by one to test it, only until I had turned off all protection. Only the general filter switch was turned on and it still did not solve the problem.

After constant testing, the only way to solve the problem is to turn off adguard completely. even if you don't have any features enabled. Or exclude the affected apps from the filter.

### Actual Behavior

Take tinder for example：

You can notice that I have switched off all the protection modules and only switched on the main switch, theoretically the adguard will not have any filtering effect at this time.
![image](https://user-images.githubusercontent.com/20610965/219874012-12f6faaa-f020-47f7-b8d6-a712191c4e81.png)

![image](https://user-images.githubusercontent.com/20610965/219874192-e79aab44-e5b6-40aa-9270-4f4008848ba9.png)

Then this is how Tinder will appear：
![image](https://user-images.githubusercontent.com/20610965/219874110-8c6c51c9-1246-43eb-8947-7b261494f733.png)

As you can see, the images never load out properly. This problem has been present since the update to version 4.0.

Final solution.
Turn off the master switch, or turn off Tinder's filter switch so that affected apps bypass adguard's routing.

So I'm wondering if adguard is performing some sort of routing effect outside of the optional features that cause this to happen when the master switch is turned on. This almost never happens on version 3.x.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Rtizer-9** [comment]
@shugo-chara Did you turn off https filtering to check if it works or was it turned off by default.

Tinder doesn't trust user certificate and I don't know if it works after installing adguard certificate into system store.

Ideally as a root user one should install adguard certificate into system store to let it filter https traffic of as much apps as possible which non-root users can't.

If you've not installed latest adguard certificate into system store then I'd suggest to completely uninstall and reinstall adguard then install the certificate and then turn on https filtering for Tinder and then test. Reinstallation is not necessary but considering the recent bugs nightlies are facing it might be a good idea if things are not working as expected.

**Comment by shugo-chara** [comment]
@Rtizer-9 
do not accept third-party https certificates other than their own, I do not have adguard's https filtering turned on, and I do not have any https certificates installed.
The condition should not be related to https filtering

**Comment by Versty** [comment]
@shugo-chara When all protection modules from the Home tab are disabled, but the main switch is turned on, some filtering still exists. For example, browsing security, userscripts or tracking protection filters and all settings from the Advanced -> Low-level are applied.

This issue may be caused by IPv6 filtering. Could you check this for me? 
1. Enable main switch, but disable every protection module. 
2. Open Settings tab -> Advanced -> Low-level settings and disable IPv6 filtering option
3. Launch tinder or any related to the issue app 

Does the images in the app displayed properly in this case?

**Comment by shugo-chara** [comment]
@Versty 
Thank you for the suggestion. I disabled ipv6 filtering and tested it, but the problem still doesn't seem to be solved.

And from your suggestion I found a problem that has been bothering me for a long time. I noticed that after I turn on the general switch of adguard, even without any module enabled, my phone loses all ipv6 networks. I can't connect to the ipv6 network in any test, but as soon as I turn off the adguard, the ipv6 network is instantly connected again.
PS. Whether or not I turn on "Enable IPv6 filtering" in the low-level settings, I will not be able to connect to the IPv6 network with adguard on. It seems that adguard is completely blocking all ipv6 connections in root mode. This makes my device can only access the network in ipv4 and the speed becomes very slow.

**Comment by shugo-chara** [comment]
@Versty 
Is the issue no longer being followed up?
It has been there for me without being resolved.

**Comment by Versty** [comment]
@shugo-chara We are looking for the cause and possible solution, sorry for the delayed response. Tried to reproduce this issue on our side, but to no avail. 

Could you send the logs from your device? 

1. Open AdGuard and go to **Settings** tab -> **General**.
2. Tap the **Advanced** option.
3. Set the **Logging level** to **Debug**. It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the issue. Notice the exact time when it happened.
6. Use the **Export logs and system info** option to save the log file to the phone storage
7. Attach this file to the email and send it to devteam@adguard.com, mention the issue number `#4483` in the subject and the time when the issue was reproduced.

**Comment by shugo-chara** [comment]
@Versty 
I have sent the log file by email to devteam@adguard.com.
Also attached is a video of the operation, hope this helps.

**Comment by Versty** [comment]
@shugo-chara It would be much appreciated if you also provide the settings file from your device. We will try to reproduce the issue with images not loading correctly in applications again.  

1. Make sure the issue reproduces 
2. Open settings tab, then click the context menu in the top right corner -> Export 
3. Send this file to `devteam@adguard.com`and mention the issue number `#4483`

**Comment by shugo-chara** [comment]
@Versty 
I would like to know how the issue is progressing.

I thought I noticed that the same issue has been brought back recently. （#4591）
I am pretty sure that this issue has been around for at least a few years and for whatever reason it seems to have gone unnoticed and unresolved.

**Comment by Versty** [comment]
@shugo-chara It would be convenient to discuss the issue related to the images in the root mode here, and the issue related to ipv6 in the separate thread (#4591). Which we were able to reproduce thanks to the files you provided.

Does the issue with the images in the apps persists in the latest nightly? 
If so, please provide more examples of affected applications.

**Comment by Versty** [comment]
@shugo-chara Closed due to lack of activity. Please reopen if needed.
