### ISSUE TITLE
Third-party referrer and user-agent features cannot be customized

### ISSUE THREAD

**Issue by honeyuee** [AdguardTeam/AdguardForAndroid#4484]
AdGuard for Android v4.0 Nightly 51 version under the Tracking Protection tab under the Custom Mode Additional Options, hiding third-party references to prevent URLs, user-agent request identification cannot be customized.

The question screen is as follows, whether the setting is complete or the default option.

![Screenshot_20230219_153614_com.adguard.android_edit_14712916559731.png](https://user-images.githubusercontent.com/53884928/219935724-0a43a4f2-3ad6-4896-b2d1-d1356d213003.png)

**Comment by Versty** [comment]
@honeyuee Thanks for the feedback! This is clearly a bug. 

The thing is: possible to enter data, but impossible to save it. 

#### Tracking protection -> Custom
Affected options: 
- Self-destruction of third-party cookies 
- Self-destruct first-party cookies 
- Hide Referer from third parties
- Hide your User-Agent
- Mask your IP address
