### ISSUE TITLE
Can't change or delete user agent info in Hide User agent field.

### ISSUE THREAD

**Issue by vadu71** [AdguardTeam/AdguardForAndroid#4490]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.52 nightly

### Environment

```markdown
- OS:A13
- Device:Samsung 
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open Tracking protection.
2. Scroll to Hide your user agent.
3. Try to either delete or change the field.

### Expected Behavior

You are able either delete or change information in this field.

### Actual Behavior

You cannot delete or change anything. It looks like user agent is hardcoded.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@vadu71 Did the reinstallation solve the issue?

**Comment by vadu71** [comment]
> @vadu71 Did the reinstallation solve the issue?

Nope. Just playing around with Tracking Protection levels.
