### ISSUE TITLE
Adguard Filters Update

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#4494]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.52

### Environment

```markdown
- OS:Android 12
- Device:SM-N975F 
- Firmware:SP1A.210812.016.N975FXXS8HWA1

Can't automatically update filters on app nothing happened 
when tapping button update,the app showing error: can't 
update now, try again letter.
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.open app AdGuard 4.0.52 Nightly on Android
2. Tap update ring and go to update panel 
3. Content blocker filter showing red error :Failed to update 

### Expected Behavior

Fix updating script and connectivity to serwer .

### Actual Behavior

Can't update the app.  #4493 
[adguard_logs_4.0.543_3101_220430.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10794437/adguard_logs_4.0.543_3101_220430.zip)
[adguard_logs_4.0.617_2102_151216.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10794441/adguard_logs_4.0.617_2102_151216.zip)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![Screenshot_20230221-150920_AdGuard](https://user-images.githubusercontent.com/100161152/220372408-745b1b0f-a60c-4a52-b08f-7b7328a1ae36.jpg)
![Screenshot_20230221-150810_AdGuard](https://user-images.githubusercontent.com/100161152/220372413-d001b4b5-8266-4f4b-a38c-9f53c6a33b4b.jpg)

**Comment by Batman2814** [comment]
It's also showing fail to update filters in the stable version of Adguard for Android app

**Comment by jwds1178** [comment]
I just tried manually checking for updates with AdGuard for Android (Nightly) v4.0.621, a couple of times, and got the same "Failed to update" error for _Content blocker filters_.

**Comment by XBadFellaX** [comment]
Looks like the servers are down. The nightly website is not working as well. Unable to update adguard nightly currently.

**Comment by sxwzxc** [comment]
My app version is 4.0.617. It remain me to update to 4.0.621, but it always fail.

**Comment by XBadFellaX** [comment]
Quick update - whoever is unable to update app to current nightly download latest version using this link: https://we.tl/t-xHuN1syKEN

This will get rid of the update problem. The filter updates is something the adguard team will have to fix.

My phone was continuously showing the notification to update adguard which I wasn't able to and that was draining my battery.

So a workaround for now.

Cheers!

**Comment by Joomsy** [comment]
> Quick update - whoever is unable to update app to current nightly download latest version using this link: https://we.tl/t-xHuN1syKEN
> 
> This will get rid of the update problem. The filter updates is something the adguard team will have to fix.
> 
> My phone was continuously showing the notification to update adguard which I wasn't able to and that was draining my battery.
> 
> So a workaround for now.
> 
> Cheers!

Probably better to link the location you got this from, as it doesn't expire. :)
https://www.apkmirror.com/apk/adguard-software-limited/adguard/adguard-4-0-621-release/adguard-4-0-621-android-apk-download/

**Comment by Versty** [comment]
@U0101100 @sxwzxc @XBadFellaX @Batman2814 
It was a planned maintenance, we have changed some infrastructure. 
Please make sure the updates are now working.

**Comment by jwds1178** [comment]
> @U0101100 @sxwzxc @XBadFellaX @Batman2814 It was a planned maintenance, we have changed some infrastructure. Please make sure the updates are now working.

Seems to be working again for me.
