### ISSUE TITLE
Hiding license key

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4496]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 10, 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Need to hide the license key in the License tab, as in version 3.6.11.
It would also be better to add the function of "show" the key after clicking on it

### Expected Behavior

The license key is hidden

### Actual Behavior

The license key is not hidden

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@artemiv4nov 
1. For privacy: to prevent the key from being accidentally seen and then used by a third person. 
2. For better appearance: the key can be up to 25 characters, the license screen will look better if the key will fit one line.

**Comment by ihurin** [comment]
+1 `hide it like previous version because if someone has device they can easily copy or steal key`

**Comment by J-khatri** [comment]
implement 2FA
