### ISSUE TITLE
Adguard VPN issue playing music with both YouTube Music and Spotify

### ISSUE THREAD

**Issue by TechieFsn** [AdguardTeam/AdguardForAndroid#4499]
Have a subscription to both YouTube Music and Spotify.  Recently gifted a family member my iPhone Pro Max and bought a Samsung S23 Ultra.  Installed both music apps, both stop playing after one song when the screen is 'off'.  If the screen is on, they both work fine.  I also have Adguard Adblocker running.    Turn off Adguard VPN and they both play fine, with the screen off.  This happens on both wireless and mobile without wireless access.

Reformatted the phone twice.  Reset all apps configurations.  Checked all settings mentioned here https://www.guidingtech.com/fixes-music-stops-playing-samsung-when-phone-locks/        and several other sites and no suggested changes work.  Turn off Adguard VPN, music plays more than one song. Have it on, you play one song only then must unlock device to get next song to play (don't have to click anything, just unlock and it starts playing.)

Son also has a brand new S23 Ultra, also has Adguard Adblocker installed as well as Adguard VPN, and his does the exact same thing.  Adguard Adblocker works fine, including setting it to us using Adguard DNS and not my ISP DNS (obviously my location is still visible without Adguard VPN running though.)

I see several settings in Adguard Adblocker for both app's, but did not try changing any of them (Protection, Blocking, HTTPS filtering, Cellular, Wifi, etc.  All are set to out of box defaults.)

Please help, do want to run both Adblocker VPN and Adguard Adblocker as I have licenses for both and don't want to throw them away and go to NordVPN with their native adblocker (been there already, not near as good as Adguard Adblocker.)

**Comment by TechieFsn** [comment]
Went to Settings, Apps, Adguard, Mobile Data, and turned on Allow data usage while Data saver is on.  Hit back, and then picked Battery, and toggled on Unrestricted.  Repeated both steps for Android VPN.  Restarted device.  So far, it works!  Had done this, and 50 more changes for both Spotify and YouTube, but had never done it for Adguard/VPN.  Maybe this is what I was missing. Sure hope so.

**Comment by Versty** [comment]
@TechieFsn Looks like you've figured out the proper solution! 
Also, you can allow any application to use data in the background in the system settings.
`Settings` -> `Connections` -> `Data usage` -> `Data saver` -> `Allowed to use data while Data saver is on`
