### ISSUE TITLE
FarmVille 2 - can't login in FB(without filters and DNS filtrations)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#45]
https://play.google.com/store/apps/details?id=com.zynga.FarmVille2CountryEscape&hl=ru

**Comment by Alex-302** [comment]
Логи PCV-456-92605

**Comment by Revertron** [comment]
Added an exception for now.

**Comment by ameshkov** [comment]
@Revertron would be great if you post here research details (broken PUT request and such). May be useful in future.

**Comment by Revertron** [comment]
The PUT request was somehow broken indeed. Here is some log:

TCP id=90 Writing HTTP request to remote client
TCP id=90 PUT /storage/v1/app/5002607/blob/summary/user/71133265001 HTTP/1.1 writing body Content-Length: 247
TCP id=90 Reading HTTP response
TCP id=90 Read 402 bytes from socket channel
TCP id=90 HTTP/1.1 400 Bad Request
    Server: pbr-release-1.4.2-145/pbr-web-45.ca2
    Content-Length: 182
    Cache-Control: no-cache, no-store
    Request-Id: pbr-ab5171457db5c80b
    Connection: keep-alive
    Content-Type: application/json

**Comment by Revertron** [comment]
[farmville.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/7631/farmville.txt)
Full log.

**Comment by ameshkov** [comment]
I belive this is now fixed because it was also caused by #98 
We need to re-test it.

**Comment by ameshkov** [comment]
Fixed, thanks to #98

**Comment by ameshkov** [comment]
Not so fast:(

pcap:
https://yadi.sk/d/9gQoxyvmjnjoM

**Comment by ameshkov** [comment]
Finally fixed in 2.1.212
