### ISSUE TITLE
Adguard Can't use google's app

### ISSUE THREAD

**Issue by Extreme-Icer** [AdguardTeam/AdguardForAndroid#4500]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

to the latest nightly version

### Environment

```markdown
- OS:android10
- Device:SM-N950N
- Firmware:N950 Third-party frimware
```

### Root access

- [x] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, EasyList, EasyList China, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Adblock Warning Removal List, Online Malicious URL Blocklist, Polish GDPR-Cookies Filters, CJX's Annoyances List, I don't care about cookies, EasyList Spanish, KAD - Anti-Scam

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Disable WebRTC, Protect from DPI

### Issue Details

Steps to reproduce:
1.Open ADGuard
2.Open v2rayNG
3.set v2rayng ONLY PROXY mode
4.set adguard proxy->socks 127.0.0.1:XXXX
5.add proxy in ng(or use custom profile)
6.open seeting-google-account/google play/youtube

### Expected Behavior

google's app have good network

### Actual Behavior

Google's APP says I HAVN'T NETWORK,and fliter log have not a lot of about google domain names(such as google usercontent)

### Screenshots

<details><summary>Screenshots:

![Screenshot_20230225-210953_AdGuard](https://user-images.githubusercontent.com/59390954/221359051-bf26fdfa-3901-4d42-b04a-8875d28b15a7.jpg)

![Screenshot_20230225-211002_AdGuard](https://user-images.githubusercontent.com/59390954/221359056-f062230d-499e-4967-a034-28880604fe93.jpg)

![Screenshot_20230225-211032_v2rayNG](https://user-images.githubusercontent.com/59390954/221359059-72823769-d622-4d37-9021-60c653d8bd69.jpg)

![Screenshot_20230225-211119_Google Play services](https://user-images.githubusercontent.com/59390954/221359065-ddf37b0c-c547-4fb9-b431-115c6cb8f635.jpg)
</summary>

</details>

### Additional Information

my girlfriend phone(SM-S9080)android13 use same as me the v2rayNG config,adguard config,but her phone can use normally

**Comment by sfionov** [comment]
@Extreme-Icer Did you exclude v2rayNG from filtering in the Apps Management section? Usual issue with local proxies is route loop.

**Comment by Extreme-Icer** [comment]
no

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer Did you exclude v2rayNG from filtering in the Apps Management section? Usual issue with local proxies is route loop.

hey have any answer?

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer Did you exclude v2rayNG from filtering in the Apps Management section? Usual issue with local proxies is route loop.

Add some details:open Web google,youtube was ok
so i didn't know why,and the latest ver nightly in my device is so slow,i have to use nightly4.0.82.

**Comment by maxikuzmin** [comment]
@Extreme-Icer can you clarify please? In your screenshots you have version 3.6.11, but you mention nightly4.0.82. On which version is the problem?

**Comment by Extreme-Icer** [comment]
now version 4.0nightly38 but the latest version also have this problem

**Comment by Extreme-Icer** [comment]
add: when i enabled WLAN-HTTP proxy,the apps works normally.I search the issues,says ADGuard BAN UDP443,when i use http proxy,i can see quic log in AndroidOS.

**Comment by Extreme-Icer** [comment]
[adguard_logs_4.0.82_0903_102310.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10927065/adguard_logs_4.0.82_0903_102310.zip)
this is adguard log

**Comment by maxikuzmin** [comment]
@Extreme-Icer thank you! We'll look at your logs, we need some time

**Comment by maxikuzmin** [comment]
@Extreme-Icer is the problem still recurring? At the moment I don't have this problem repeated. I used to be able to reproduce it with Google's personal account, but now I log in there steadily with no problem. If the problem persists, with which Google apps? Can I ask you to email your settings to [devteam@adguard.com](mailto:devteam@adguard.com)? 
You need to go to the Settings tab and in the context menu (in the upper right corner) click "Export settings"

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer is the problem still recurring? At the moment I don't have this problem repeated. I used to be able to reproduce it with Google's personal account, but now I log in there steadily with no problem. If the problem persists, with which Google apps? Can I ask you to email your settings to [devteam@adguard.com](mailto:devteam@adguard.com)? You need to go to the Settings tab and in the context menu (in the upper right corner) click "Export settings"

emm did u say the latest nightly version? if yes i will test it

**Comment by Extreme-Icer** [comment]
please see email from g*******en@outlook.com, 2 eamils

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer any news?

I'm sorry I'm still tracking this problem, and the other device doesn't seem to be connected at the moment. I'll wait and see if I have time to re-flash the rom. Because we are in mainland China, whether Google can connect is a bit complicated.
 In addition, I have two questions: 1. The current AdGuard Android attempt to search on the filter log page will be very stuck, including the sliding log page; 2. What will happen if I write 1-65535 for the port range of the low-level settings? 3. Is there any update plan for the Magisk certificate stored by the system?

**Comment by maxikuzmin** [comment]
@Extreme-Icer 2. If you add the entire address range, it may break some applications or something in the system.
3. There is no plan to update the certificate for Magisk. Usually this certificate is issued for ten years.
Any news about main problem?

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer 2. If you add the entire address range, it may break some applications or something in the system. 3. There is no plan to update the certificate for Magisk. Usually this certificate is issued for ten years. Any news about main problem?

now the Android13 phone has the same problem.because this user turn off adguard so long time,and google think no network,even i turn on adguard the play store still say no network.the new flash rom can use adguard+v2rayNG access play store.I can't know what happened.

**Comment by maxikuzmin** [comment]
@Extreme-Icer were you able to update your magisk certificate? Have you tried doing it manually?

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer were you able to update your magisk certificate? Have you tried doing it manually?

magisk module can't auto move cert to system partition,so i use manually.
and can't open some website problem still not found what happened.if i use v2rayNG vpn mode,they can access.i see two software access log but not found what.but,some domains not access in adguard so v2rayNG can't route.if u need i can record video to team email.

**Comment by maxikuzmin** [comment]
@Extreme-Icer I don't quite understand what your problem is right now?
If we are talking about a certificate for magisk, there are no plans to renew the certificate for magisk. Usually this certificate is issued for ten years.
Are you having any difficulties using v2rayNG? As far as I know, when using AdGuard + v2rayNG, you have to disable "Route traffic through AdGuard" in App management
Could you please describe the problem in more detail, with video and v2rayNG setup, and if it does not apply to the originally opened issue, it would be better to open a new issue

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer I don't quite understand what your problem is right now? If we are talking about a certificate for magisk, there are no plans to renew the certificate for magisk. Usually this certificate is issued for ten years. Are you having any difficulties using v2rayNG? As far as I know, when using AdGuard + v2rayNG, you have to disable "Route traffic through AdGuard" in App management Could you please describe the problem in more detail, with video and v2rayNG setup, and if it does not apply to the originally opened issue, it would be better to open a new issue

I send a email to adgaurdteam,have a video to report what happened.

**Comment by maxikuzmin** [comment]
@Extreme-Icer to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Extreme-Icer** [comment]
Currently choose http hybrid proxy + v2rayNG VPN mode to alleviate this problem. Logs could not be captured, sorry. (already tried)

**Comment by maxikuzmin** [comment]
@Extreme-Icer glad to hear the problem is solved. If you manage to record logs in the future, please send it.

**Comment by madaono** [comment]
Same problem, I think it is because the Chinese phone ROM has some "special" logic with the Google apps
