### ISSUE TITLE
4.0 Nightly 59 doesn't boot like stable version, it's not autostart after reboot

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForAndroid#4509]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 59

### Environment

```markdown
- OS: emui 12 based on android 10 i think
- Device: huawei mate 20 pro
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. install standard 3 version, boots fine, no problem
2. install last nightly 4 version, can't boot
3. all huawei memory managment already "fixed" so they are not the problem, cause the phone is also old and no problem with "old" standard/beta adguard versions
4. tried also play with watchdog interval but no lucky
### Expected Behavior

Boots without problems

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Where is the pref boot startup delay in low level setting like in version 3?

**Comment by Rokcy98** [comment]
I can confirm this problem on A13 with nightly 59, also after "fixing" every boot management of my phone

**Comment by maxikuzmin** [comment]
@michael1900 @Rokcy98 please make sure that you have changed the system settings as specified in the [knowledge base](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/#Samsung). 
If you have done everything according to the instructions and the problem persists, you just have to wait a bit. 
We are already aware that some users have this problem and are trying to solve it in this [issue](https://github.com/AdguardTeam/AdguardForAndroid/issues/4361).

**Comment by Rokcy98** [comment]
Sure, thank you, just wanted to report that everything worked fine until nightly 59, if this can help you. Autostart was enabled and worked fine, now autostart is enabled but it won't work

**Comment by Rokcy98** [comment]
With nightly 61 the problem seems to be fixed for me

**Comment by michael1900** [comment]
> be

Really?

**Comment by michael1900** [comment]
> With nightly 61 the problem seems to be fixed for me

Can you confirm this after several reboot?

**Comment by michael1900** [comment]
> With nightly 61 the problem seems to be fixed for me

Can you confirm this after several reboot?

**Comment by michael1900** [comment]
Fixed in today nightly!
