### ISSUE TITLE
Protection is stopped when you go to HTTPS filtering settings

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#451]
**Steps to reproduce:**
1. Install AG certificate
2. Turn HTTPs filtering off
3. Start protection
4. Go to HTTPs filtering settings

**Expected result:**
Nothing should happen

**Actual result:**
"Filtering disabled" toast

**Comment by Revertron** [comment]
The serviceStatusEventHandler reacted on every service status change. Fixed.
