### ISSUE TITLE
Adguard 4.0 Nightly: Incorrect statistics values reported

### ISSUE THREAD

**Issue by flagadum** [AdguardTeam/AdguardForAndroid#4517]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.647

### Environment

```markdown
- OS: Android 8.0
- Device: CAT S41
- Firmware: Mediatek
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter

### Issue Details

Steps to reproduce:
1. Have a data-hungry app used since a few days (Video streaming app, web browser....)
2. Go to the Statistics tab.
3. Select this app in the Applications list

### Expected Behavior

Logically, the "downloaded" data amount should be far superior than the "uploaded" data amount.

### Actual Behavior

You will notice that the "uploaded" data amount is shown magnitudes higher that the "downloaded" data amount!
Note that the items from the Companies list seem affected in the same way.

This is also in contradiction with the global "Data usage" display, showing downloaded data far superior than uploaded.

### Additional Information

My guess: The values being displayed next to "uploaded" and "downloaded" should be switched, for item info panes both from Applications and Companies lists.

**Comment by maxikuzmin** [comment]
@flagadum thank you! You're right, we'll fix that.
