### ISSUE TITLE
Thorium Browser Support 

### ISSUE THREAD

**Issue by Anurag-redvelvetcake** [AdguardTeam/AdguardForAndroid#4518]
### Issue Details

Please add Adguard ad blocking support for Thorium browser for free users of Adguard android app.

Thorium browser builds for android can be found here - https://github.com/Alex313031/Thorium-Special/releases

### Proposed solution

Whitelist Thorium browser for ad blocking support just like native chrome browser on android.

**Comment by maxikuzmin** [comment]
@Anurag-redvelvetcake thank you! We'll fix that.
