### ISSUE TITLE
Udp being blocked on certian apps 

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4519]
Jw is this normal?
![Screenshot_20230315_112412_AdGuard](https://user-images.githubusercontent.com/118186787/225375097-d7688bcf-e914-4bdd-98d8-44d3f4600936.jpg)

![Screenshot_20230315_112135_AdGuard](https://user-images.githubusercontent.com/118186787/225375143-49326abb-c22d-45c2-a189-858b0d83fa07.jpg)

**Comment by maxikuzmin** [comment]
@jordanswrld94 yes, that's normal. UDP 443 - is QUICK, we only block it in applications that have HTTPS filtering enabled. The current version of AdGuard cannot filter HTTP/3, which works by quick.
So if HTTPS-filtering is enabled, then quick requests are blocked

**Comment by jordanswrld94** [comment]
> @jordanswrld94 yes, that's normal. UDP 443 - is QUICK, we only block it in applications that have HTTPS filtering enabled. The current version of AdGuard cannot filter HTTP/3, which works by quick. So if HTTPS-filtering is enabled, then quick requests are blocked

Https filtering isnt enabled in any apps except for samsung internet though. And udp is still being blocked. So this is normal your saying? Or should i add them to quic bypass list

**Comment by jordanswrld94** [comment]
@Alex-302
