### ISSUE TITLE
No way to exclude android OS anymore

### ISSUE THREAD

**Issue by androidacy-user** [AdguardTeam/AdguardForAndroid#4520]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 66

### Environment

```markdown
- OS: android 13 
- Device: Pixel 7 Pro
- Firmware: Stock
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Annoyances filter, Fanboy's Annoyances, Fanboy's Anti-Facebook List

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Strip URLs of tracking parameters, Protect from DPI

### Issue Details

Steps to reproduce:
1. Run an app like VPN hotspot that routes traffic via android os
2. Try excluding android system 
3. See android OS labelled traffic is still filtered

### Expected Behavior

Android system also excludes android OS 

### Actual Behavior

Android os filtering cannot be turned off. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@androidacy-user Let's try to disable all traffic filtering for the system apps.  
*Settings -> Filtering -> Apps -> App management -> System apps* 
Disable the **Route traffic through AdGuard** switch.

**Comment by Versty** [comment]
@androidacy-user Are you talking about iquic:// requests sent by Android OS?

**Comment by Versty** [comment]
@androidacy-user We have reproduced the issue on the latest nightly, but we don't see any notification while tethering. 
Would you mind providing a screenshot of this notification?
