### ISSUE TITLE
Connectivity loss on secondary SIM card

### ISSUE THREAD

**Issue by SebastianS3** [AdguardTeam/AdguardForAndroid#4523]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.671

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy S23 5G (SM-S911B/DS)
- Firmware: S911BXXU1AWBD
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, ROList, EasyPrivacy, Fanboy's Anti-Facebook List

### Issue Details

Steps to reproduce:
1. Change SIM card assigned to mobile data from primary to secondary
2. instantly lose connectivity, browser says "network changed" or "DNS error"
3. turn off Adguard to instantly fix it

### Expected Behavior

Internet connection keeps working

### Actual Behavior

All connectivity is lost, the little arrow by the 4G+ status icon just lights up, but not down.

**Comment by SebastianS3** [comment]
@Versty Done, awaiting further instructions.

**Comment by Versty** [comment]
@SebastianS3 Would you mind updating to the latest nightly version and check if the issue persists?

**Comment by SebastianS3** [comment]
Everything working as expected again, thank you!
