### ISSUE TITLE
Ads in the app about AdGuard VPN

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4526]
I apologize for the language, but...

What the fuck is this?!

It's an ad for a third-party product in an ad-blocking app?!

Why isn't there a "cross" button that allows you to close this ugly thing? Why is there no "don't show anymore" button?

What's with the imposition of useless developments?

![7DD80E8F-C45D-4A60-BCF2-208DAAE99E93](https://user-images.githubusercontent.com/128435733/226495875-41d01526-3556-43ac-bd9c-f10761bba2f8.jpeg)

**Comment by XBadFellaX** [comment]
Lol, dude. Adguard VPN is an Adguard application. Why you swearing lol, a simple google search would have told you that. That is for people who have a adguard VPN subscription and want to use that along side adguard ad blocker.

**Comment by Yftftdyvhc** [comment]
> Lol, dude. Adguard VPN is an Adguard application. Why you swearing lol, a simple google search would have told you that. That is for people who have a adguard VPN subscription and want to use that along side adguard ad blocker.
> 
> Check this out: https://www.reddit.com/r/Adguard/comments/11ucnf7

I know. But the advertising, even of your own product, is annoying. I would like to be able to hide this ugliness. I personally use Orbot and it's enough for me. Why do I need to see these ads all the time?
