### ISSUE TITLE
Adding the same rules to "User rules"

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4528]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: 12
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
Go to Protection tab -> Ad Blocking -> User Rules
The same rules with different letter sizes are added
For example:
||example.com^
||Example.com^
||eXample.com^

Also if you add rule ||example.com^ via "+", then open Rule editor and add ||example.com^ again, the rule will also be added and there will be 2 identical rules

### Expected Behavior

The same rules are not added

### Actual Behavior

The same rules are added

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by 7FoQc0oBicfT** [comment]
Two problems occurred.
1,Upper case letters in the filter are automatically converted to lower case.
2,Blank lines with only one "!" (comment out marker), cannot be added, more than 2.
