### ISSUE TITLE
Implement ‘ClearTop’ navigation for circular navigation issues

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4529]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: 12
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
Go to Settings -> Filtering -> Apps -> App management -> select an application -> click on App statistics in the context menu

Once in App statistics, click on the context menu and click on App management
There is an endless switching, circular navigation

 

### Expected Behavior

You can't switch through the context menu endless, we don't have a circular navigation.

### Actual Behavior

You can switch through the contextual menu endless, we have the circular navigation.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by artemiv4nov** [comment]
I don't think that behavior is not so good, closed.
