### ISSUE TITLE
Failed to connect to the private DNS server error if AdGuard in use

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdguardForAndroid#4530]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version 

AdGuard v4.0.636

### Environment

```markdown
- OS:Oxygen OS. Android 13 (latest patch) 
- Device:Oneplus 9 pro
- Firmware:
- System DNS: ControlD.com free DNS
- Network: Wi-Fi and Cellular
- AdGuard DNS module OFF
```

### Root access

- [] Yes, I have it. 

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Configure private DNS in Android system settings. ( ControlD.com free DNS in this case) 
2. Run AdGuard ( AdGuard DNS protection module must be disabled)
3. Connect to any Wi-Fi\Cellular 
4. An error appears, screenshot attached below ("Failed to connect to the private DNS" )

### Expected Behavior

 AdGuard proper functioning app without "couldn't connect to secure DNS" error pop-up. 

### Actual Behavior

OS's error screen >"couldn't connect to secure DNS" error 

### Screenshots

<details><summary>Screenshot 1:</summary>

![ZH_Vb5apa](https://user-images.githubusercontent.com/103937301/226638553-2981f278-449d-41b2-925d-a42a329fc772.png)

</details>

### Additional Information

Ticket: 730674 and 737626

**Comment by admitrevskiy** [comment]
@VladisLoveZh hi!
Could you try to reproduce the issue with the latest nightly version?

If issue still occurs:
- Enable debug log level (Settings -> General -> Advanced);
- Reproduce the issue;
- Export logs (Settings -> General -> Advanced) and send it to devteam@adguard.com;

**Comment by Versty** [comment]
@VladisLoveZh This "Tips" popup is provided by the Oxygen OS as a part of `Private DNS cannot be accessed` notification from the curtain.  If the tunnel is already created, but internet is turned off, this notification will be displayed anyway until you enable Wi-Fi or cellular data or disable AdGuard.
