### ISSUE TITLE
Text doesn't fit in the box in the DNS protection

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#4536]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 nightly 71

### Environment

```markdown
- OS:Android 8.1.0
- Device: Samsung
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Change Routing mode to Manual proxy.
2. Go to Protection -> DNS protection.

### Expected Behavior

Must fit in the box to read the full text.

### Actual Behavior

Text doesn't fit in the box so we can't read the full text.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Text](https://user-images.githubusercontent.com/35523759/227186734-32d5d40e-3414-489f-b3ce-450697149488.jpg)
</details>

**Comment by Versty** [comment]
@gork7777 Thank you for bringing this to our attention. We are aware of this issue and have some long-term plans to enhance the snacks.
