### ISSUE TITLE
Bandwidth it's very slow on mobile

### ISSUE THREAD

**Issue by Amby713** [AdguardTeam/AdguardForAndroid#4540]
version 4.0.697

com.adguard.android
versionCode 10054090

I updated my adguard for the latest one and noticed that all apps and websites take forever to load or not even load at all.

Works just fine on wifi, but other than that, mobile data is show.

I tried rebooting phone, cycling airplane mode

Android 13, Xiaomi m10t, and rooted

**Comment by jordanswrld94** [comment]
Have u tried a different dns server

**Comment by Amby713** [comment]
No, which dns should i use if not the adguard dns?

**Comment by Amby713** [comment]
I disabled dns entirely and it's still super slow

**Comment by jordanswrld94** [comment]
If u disabled dns and its still slow it means thats your phone providers issue. I use adguard server quic on mobile and wifi and both are fast
