### ISSUE TITLE
Add "Reset to default" for Tracking protection

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4543]
### Issue Details

Providing a situation where the user can change a lot of settings, it should be possible to do a Reset to default.
Undoubtedly changing the level to "Ultimate level" or "High level" will give a similar effect to the default setting, but sometimes users only need to use "Custom", and an incorrect setting of "Custom" can disrupt the application.

### Proposed solution

Add button "Reset to default" for Tracking protection

**Comment by artemiv4nov** [comment]
It has already been resolved in the v4.0 version but not like a real "reset to default" button but via one of points on the protection level.
