### ISSUE TITLE
Exclude Samsung Pay from filtering list by default

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardForAndroid#4544]
### Issue Details

Samsung Pay app detects that Android's VPN API is being used toward the app.
Package name of the app is `com.samsung.android.spay`.

https://drive.google.com/drive/folders/1s7i_7bYYaMCHlySneZ3vQf3GPuiK1ZM0?usp=sharing

### Proposed solution

Exclude Samsung Pay from filtering list by default.

### Alternative solution

None.

**Comment by admitrevskiy** [comment]
Hello! Did you try this feature? https://adguard.com/kb/adguard-for-android/solving-problems/samsungpay-with-adguard-in-south-korea/

**Comment by Versty** [comment]
@piquark6046 You can also add the `com.samsung.android.spay` package to the list of the excluded apps on your device. 
*Settings -> General -> Advanced -> Low-level settings -> Excluded apps*

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/4544#issuecomment-1488243655 That feature pauses AdGuard for Android entirely.

**Comment by Versty** [comment]
@piquark6046 We implemented the feature to temporarily stop protection due to #1209.
Does the Samsung Pay app work fine for Korean users when the VPN tunnel is established? 
For example, when the app is added to the exclusions list.

**Comment by piquark6046** [comment]
As you can see the video shared in Google Drive, excluding Samsung Pay from AdGuard's local VPN tunneling can resolve the issue without disabling AdGuard for Android entirely.

**Comment by artemiv4nov** [comment]
Hi! You can exclude the application disabling it in Settings -> Filtering -> Apps -> Apps management
