### ISSUE TITLE
AdGuard VPN promo 

### ISSUE THREAD

**Issue by ReMko57** [AdguardTeam/AdguardForAndroid#4547]
Здравствуйте!

Спасибо за то что вежливо послали меня на три веселых на вашем форуме.

Пишу сюда согласно сообщению вашего модератора:

https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B0-%D0%B2-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8-adguard.51975/post-228235

Я конечно все понимаю… Это ваш продукт и все дела… Но не могли бы вы хотя бы добавить кнопку «Больше не показывать»?

Эта плашка ужасно раздражает. Есть очень многие люди которые не используют именно ваш VPN. Например в пользу Tor, что значительно более безопасно. Так зачем им видеть рекламу вашего VPN в ПЛАТНОМ продукте?

Мы платим деньги не за то, чтобы видеть рекламу. Мы платим деньги зато, чтобы ее не было.

И мы не нуждаемся в «напоминаниях». Даже в самой противной рекламе в интернете есть кнопка «пропустить» или «закрыть». Почему на этой гадости ее нет?

![Sc](https://i.postimg.cc/0y51vT1f/04-E4-C65-C-9-A19-4623-A201-3-A901-A4-D7-BC5.jpg)

**Comment by Versty** [comment]
@ReMko57 
Добрый день! 
Мы понимаем ваши чувства и планируем в следующих версиях добавить возможность убирать из приложения отображение функций связанных с AdGuard VPN.
