### ISSUE TITLE
After updating Adguard Nightly Open Adguard message doesn't work

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4549]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard Nightly 4.0 Nightly 77

### Environment

```markdown
- OS:Android 13
- Device:samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.when update for Adguard is released
2.after installing the update message pops up saying, "Do you want to open Adguard
3. When pressing open, Adguard, nothing happens. You have to open it manually, by clicking on application. 

### Expected Behavior

Should have automatically open after clicking on open Adgaurd when the update is finished.

### Actual Behavior

After click on open Adguard after update is finished nothing happens.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

This is a bug that needs to be fixed.

**Comment by artemiv4nov** [comment]
Unfortunately, that's behavior we cannot control, it's from your Samsung firmware.

**Comment by Batman2814** [comment]
why is this issue closed after you labelled it a bug? I was on the same Samsung firmware for months where it was working up to the point I started testing Adguard for Android Nightly so the problem is with Adguard for Android Nightly.
