### ISSUE TITLE
Xiaomi Blocklist (and GoodbyeAds) doesn't apply.

### ISSUE THREAD

**Issue by MR-Diamond** [AdguardTeam/AdguardForAndroid#4550]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11

### Environment

```markdown
- OS:Android 13
- Device:Xiaomi Redmi Note 10 Pro
```
### What filters do you have enabled?

---Third-party filters---

### Issue Details

Steps to reproduce:
1. Go to https://github.com/jerryn70/GoodbyeAds and scroll to "Xiaomi Adblock"
2. Copy the link: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt
3. Insert this list inside AdGuard

1. scroll to "GoodbyeAds"
2. Copy the link: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt (this is indicated for Adguard)
3. Insert this list inside AdGuard

### Expected Behavior

The hosts inside such filter should be blocked, unable to ping.

### Actual Behavior

Despite the fact that I inserted and enable such filter, I can still access/ping hosts, like, eg. i.xiaomi.com or ping acrh.be (these hosts are inside the filters), especially the hosts inside https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt which its format is for AdGuard

### Screenshots

![Screenshot_2023-03-31-18-54-41-583_com adguard android](https://user-images.githubusercontent.com/32249442/229182855-c4ce6882-053f-413f-9c5a-71d0403bac04.jpg)

**EDIT:**
Occurs the same if I add:
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt

**EDIT 2:**
As I add this list: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt to uBlock Origin, in facts, I cannot access to i.xiaomi.com; but still, doesn't work on AdGuard.

**EDIT 3:**
In Blokada (v4) the filter works as expected.

**Comment by Disqu3-mirOir-qt** [comment]
it,s dns filter not adblock filter sure insert in dns filter instead custum filter

**Comment by Disqu3-mirOir-qt** [comment]
![Screenshot_20230401-134928.jpg](https://user-images.githubusercontent.com/41585567/229286946-85025a7b-a65f-4bad-be2f-feb4c1be90b4.jpg)

need insert here

**Comment by MR-Diamond** [comment]
> it,s dns filter not adblock filter sure insert in dns filter instead custum filter

But this one: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt is an adblock filter.

**Comment by Disqu3-mirOir-qt** [comment]
> > it,s dns filter not adblock filter sure insert in dns filter instead custum filter
> 
> But this one: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt is an adblock filter.

dns filter too

**Comment by maxikuzmin** [comment]
@MR-Diamond [this](https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt) filter really only works from "DNS filters". Please add the filter to "DNS filters".
Also, sometimes the site may get cached and open with the filter turned on, I recommend that you clean the cache sometimes

**Comment by MR-Diamond** [comment]
@Disqu3-mirOir-qt  and @maxikuzmin thank you. in "DNS filters" works as expected. So I close this ticket.
