### ISSUE TITLE
User rules with wildcard class selector do not work

### ISSUE THREAD

**Issue by a-tinsmith** [AdguardTeam/AdguardForAndroid#4551]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.7.0

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy S22+
- Browser: Samsung Internet 20.0.3.10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Create the following DOM:
```html
<div class=" abc abc-def">
  <p>some text</p>
</div>
```
2. Add new user rule: `domain.com##DIV[class*="abc"]` (use appropriate domain name for your environment)
4. Navigate to a page with the `div` element defined in step 1.

### Expected Behavior

The `div` element with a class that contains the substring "abc" should be blocked.

### Actual Behavior

The element is not blocked.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230429_084436_Samsung Internet](https://user-images.githubusercontent.com/17712566/235267094-0bff7601-eb44-4923-a908-18b8f437ae6f.jpg)

</details>

### Additional Information

Desktop version of AdGuard works perfectly with the exact same user rule.

**Comment by maxikuzmin** [comment]
@a-tinsmith I don't have this problem repeated, the added rule works.
Could you give me an example? What rule are you adding and for which site?

**Comment by a-tinsmith** [comment]
@maxikuzmin I'm using the following rule:

`livejournal.com##DIV[class*="threeposts"]`

The rule should remove the section "More posts from this journal". It works for the desktop version, but doesn't work for the mobile version.

**Comment by a-tinsmith** [comment]
@maxikuzmin Yes, version 2.7.0 is correct. This is what I can see in the "About" section of the app itself and in the "About this app" section on the Google Play site: https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker
I'm using it together with Samsung Interbet browser.

In the Samsung Galaxy Store there is even older version 2.6.1: https://galaxystore.samsung.com/detail/com.adguard.android.contentblocker

Maybe the real bug here is that the Google Play version is too old?

**Comment by maxikuzmin** [comment]
@a-tinsmith I apologize for the long reply. I get it, I thought you were using the mobile version of [AdGuard for Android ](https://adguard.com/en/adguard-android/overview.html) :)
I looked at the livejournal website, but unfortunately, I didn't see the button you're talking about. Could you take a screenshot and paste it here?

**Comment by a-tinsmith** [comment]
@maxikuzmin I updated the issued description with a screenshot. On the screenshot I selected the section with red rectangle.

**Comment by maxikuzmin** [comment]
@a-tinsmith sorry for the long wait. Syntactically the rule is without error. Can I ask you to send a report through the app describing this problem and your rule?
Go to Menu -> Send Feedback -> Bug report
This will allow you to quickly solve the problem.
Please let me know about the report and the result

**Comment by a-tinsmith** [comment]
Hi @maxikuzmin ,
If I report the bug through the app, then is redirects me to https://github.com/AdguardTeam/ContentBlocker
If you have write access to this repo and the destination one, then you can simply transfer the issue there.
Here is the guide: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by a-tinsmith** [comment]
Reference to the new issue: https://github.com/AdguardTeam/AdguardFilters/issues/153293

**Comment by maxikuzmin** [comment]
@a-tinsmith then I'm closing this issue here
