### ISSUE TITLE
Can not routed traffic for clone app (dual messenger in Samsung devices)  through local adguard vpn

### ISSUE THREAD

**Issue by huutaiprovn** [AdguardTeam/AdguardForAndroid#4552]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.79

### Environment

```markdown
- OS: Android 12
- Device: Samsung M515F
- Firmware: OneUI Core 4.1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1.  Enable dual messenger function and creat Facebook clone app through this function. 
2. Enable Adguard local vpn connect
3. Facebook clone app in step 1 is not routed traffic through a local VPN. 

### Actual Behavior

I have a Samsung phone model M515F, I have enabled dual messenger on this device to be able to use another clone facebook app.  However, the local Adguard filter (with VPN connection mode, not proxy mode) cannot filter and control the clone facebook app traffic generated by dual messenger function. Facebook clone app is not appeared in adguard application management. 
 Please tell me a workaround so that the local VPN server on the phone can filter the cloned apps similar to the cloned facebook.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@huutaiprovn this feature in Samsung works by creating a "separate space" for cloned apps, so AdGuard doesn't see your second cloned Facebook.
You could try to create a Secure folder and add AdGuard and Facebook there, being in the same space they will see each other and you can filter the other Facebook.
This is inconvenient, but there is no other way, this is a feature of the system.

**Comment by maxikuzmin** [comment]
@huutaiprovn any news?

**Comment by huutaiprovn** [comment]
Thanks for your information although this response is a bit delayed. I've
gotten it before.

Vào 00:16, T.3, 18 Th4, 2023 maximkuzmin ***@***.***> đã viết:

**Comment by maxikuzmin** [comment]
@huutaiprovn glad to hear that! Good luck!
