### ISSUE TITLE
Ability to uppercase letters and duplicate rules via "!"

### ISSUE THREAD

**Issue by 7FoQc0oBicfT** [AdguardTeam/AdguardForAndroid#4553]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS:10
- Device:
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Update to the latest version
2.Check existing user filters
3.

### Expected Behavior

Identical filters will be deleted

### Actual Behavior

You get the results you want, but you get side effects.
1,Upper case letters in the filter are automatically converted to lower case.
2, 
!
↑Blank lines like this one
cannot be added, more than 2.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by 7FoQc0oBicfT** [comment]
A small correction.
Domains are fine in lowercase only, but element values contain uppercase letters. Makes it difficult to create hidden rules.

**Comment by maxikuzmin** [comment]
@7FoQc0oBicfT yes, the current logic is that duplicates are not added. Also autocorrect to lower case is implemented, this is not a bug.
In general, we can add the ability to add a duplicate with "!"
