### ISSUE TITLE
Block Trackers and web analytics using Adguard Tracking Protection filter blocks website forbes.com

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4555]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard for Android 4.0 Nightly 79

### Environment

```markdown
- OS:Android 13
- Device:Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyPrivacy, Fanboy's Social Blocking List, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, I don't care about cookies, Dandelion Sprout's Annoyances List, Legitimate URL Shortener

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Go to Forbes.com
2. Go to the top of the hamburger bun symbol then scroll down to lists
3. Then you're at a blank screen 
4. 

### Expected Behavior

This should take you to the webpage for lists under for Forbes website.

### Actual Behavior

Shows blank screen when clicking on hamburger symbol then scrolling down to lists by clicking on it which shows you a black screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Found out that in Adguard for Android Nightly under Tracking pootection (Protects your online activity and personal data from web trackers). Set to custom under general settings where it shows "Block Trackers" when that is off I'm able to use forbes completely and going into b lists under that website.

**Comment by Batman2814** [comment]
No, it doesn't. The website works fine when it's disabled.

**Comment by jordanswrld94** [comment]
Website works fine for me

**Comment by Batman2814** [comment]
I checked again, and with that enabled blocks, part of the website. When you first go to Forbes.com, that is not blocked, but when you go to the category list, which is under the hamburger symbol, it is blocked.

**Comment by Batman2814** [comment]
This update says that the "Block Trackers" feature is still blocking parts of forbes.com under the list category where the hamburger symbol is in Adguard for the Android Nightly version.

**Comment by Versty** [comment]
@Batman2814 Got it. This issue may be caused by some rules from one of the privacy filters. 
Let's enable tracking protection module, but disable every filter in the `Privacy filters` list. 
*Settings -> Filtering -> Filters -> Privacy filters* 
Does the issue persist in this case?

**Comment by Versty** [comment]
@Batman2814 This issue is caused by `AdGuard Tracking Protection filter`.

@Alex-302 Could you check if there is a possibility to improve rules in this filter? 

Forbes.com -> click the hamburger menu -> scroll down to the Tips/Terms/Privacy  -> Click it
If the `AdGuard Tracking Protection filter` is enabled, the page is blank. 
The content is shown on the page If the `AdGuard Tracking Protection filter` is disabled.

**Comment by Alex-302** [comment]
Not a main content, we will not unblock analytics. For user filter only.
```
@@||googletagservices.com/tag/js/gpt.js$domain=forbes.com
@@||s.mnet-ad.net/px.gif$domain=forbes.com
```
