### ISSUE TITLE
Incorrect transition from the "Use license key" tab when entering a blocked key

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4562]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: 10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

Go to Settings tab-> License -> Activate -> Use license key -> enter the blocked key -> the "Something is wrong with this license" dialog box appears -> click "contact support" -> from the "Support" tab go to the Settings tab -> go back into the license -> Activate -> you are immediately taken to the "Use license key" with the key that was already filled in before, if you click "back" twice from this screen, you will exit the application directly from the "Activate license" tab

### Expected Behavior

After going to the "Support" tab from the "Use license key" tab, when you return to "License" -> Activate, you should see a list of login choices (email, google, etc.). The key entered should not be saved when going to other tabs.

### Actual Behavior

After switching to the "Support" tab from the "Use license key" tab, when you return to "License" -> Activate, the login selection list (email, google, etc.) is not displayed. The key you entered is saved when you go to another tab.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by artemiv4nov** [comment]
We have an issue when we go to Support page: navigation identifier is on the Home button but not on the Settings button. We have to fix it.
