### ISSUE TITLE
Statistics: Inconsistant colors on the Uploaded/Downloaded data bar for Apps and Companies items

### ISSUE THREAD

**Issue by flagadum** [AdguardTeam/AdguardForAndroid#4565]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.732

### Environment

```markdown
- OS: Android 8
- Device: CAT S41
- Firmware: Mediatek
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to the Statistics tab
2. Select an item in either Apps or Companies
3. Look at the colored bar below the Data usage figures

### Expected Behavior

We expect the bar sections to be colored grey for Uploaded and white for Downloaded, consistently to the color of the displayed values, and consistently to what is shown on the global Uploaded and Downloaded bar.

### Actual Behavior

Uploaded bar section is shown white and Downloaded bar section is shown grey.

Also, there seems to be an issue where the bar seems to extend past the left border of the screen, leading to the green (Saved) section to be truncated or not shown.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@flagadum Thank you for the feedback! 
Could you please provide a screenshot of the issue?

**Comment by flagadum** [comment]
![Scr-Global](https://user-images.githubusercontent.com/58535996/230713942-1c0648fc-7dd4-4233-9607-8ccb7d55470d.jpg)
![Scr-App](https://user-images.githubusercontent.com/58535996/230713949-9f24e0f4-c6d2-4bf3-91ba-8e6e896b6dcc.jpg)

**Comment by flagadum** [comment]
Showing correct colors for global bar, and wrong colors for app bar.
Also note the artifact on the left side of the bar.

**Comment by Versty** [comment]
@flagadum Thanks! 
This issue reproduces on our side and seems to be related to the dark theme. 
The bars will be improved.
