### ISSUE TITLE
Local Proxy Mode does not work with KernelSU root

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [AdguardTeam/AdguardForAndroid#4579]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS:Android13
- Device:Pixel6a
- Firmware:
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Install [KernelSU](https://github.com/tiann/KernelSU) on your device
2.Grant root privileges to Adguard for Android using KernelSU Manager
3.Open Adguard → Go Settings→Filler→Network

### Expected Behavior

Local Proxy can be used while giving root.

### Actual Behavior

It's looping without opening.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

It works fine in v3.x.
It also works in Magisk, so I think it is an implementation issue in v4.x

**Comment by Versty** [comment]
@Katsuyuki-Karasawa Hi. Thank you for the feedback. 
In order to investigate this issue, we would like to take a look into the logs from your device. Please follow the steps below. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Sent this file to devteam@adguard.com:
      - mention the `4579` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@Katsuyuki-Karasawa Did you send the logs?

**Comment by LordArrin** [comment]
Same bug with kernelsu on android 14, pixel f3.

**Comment by LordArrin** [comment]
[adguard_logs_4.2.118_1412_044107.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/13667327/adguard_logs_4.2.118_1412_044107.zip)

**Comment by LordArrin** [comment]
@adguard-bot help

**Comment by sfionov** [comment]
@LordArrin According to your log, DNS protection cannot start. This might happen when firewall restricts binding to 127.0.0.1, or when `lo` interface is down. Can you please try without DNS protection?

**Comment by LordArrin** [comment]
> @LordArrin According to your log, DNS protection cannot start. This might happen when firewall restricts binding to 127.0.0.1, or when `lo` interface is down. Can you please try without DNS protection?

Yeah, without dns all works fine.
