### ISSUE TITLE
HTTPS filtering compatibility issue with Facebook app

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#458]
Facebook package name: com.facebook.katana
Screenshot (what's actually happening):
<img src="https://cloud.githubusercontent.com/assets/8577547/14499200/fc6e75cc-01a5-11e6-8010-a18f46ebd09f.png" width="250">
And log: https://www.dropbox.com/s/w472d8xvk3fw2yd/adguard.log
I suppose the problem is not in our domain certificate, but in the fact that facebook uses client certificate authorization. (c) Ameshkov :)

**Comment by Revertron** [comment]
Or certificate pinning...

**Comment by Revertron** [comment]
Leaving it on the HTTPS-filtering exceptions list.

**Comment by ameshkov** [comment]
Wait a bit, I'd like to do some research too.

**Comment by ameshkov** [comment]
The only way to filter it's traffic is to turn off SSL pinning:
https://github.com/AdguardTeam/AdguardForAndroid/issues/472
