### ISSUE TITLE
Adguard  doesn't  block ads  after latest  version  update  in Samsung browser

### ISSUE THREAD

**Issue by Frankflash** [AdguardTeam/AdguardForAndroid#4580]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: android  13
- Device:
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Ads are not blocked  when new  alpha  version  comes out

### Actual Behavior

Sent email  to support.  about it and  they would  Pasa info on to developers 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Xophile** [comment]
I can confirm this!

Samsung Galaxu Note 9 with Android 10

**Comment by maxikuzmin** [comment]
@Frankflash could you please specify the support request number?
@Xophile @Frankflash could you be more specific, what do you mean? Are ads not blocked on certain sites or all of them? Do you see blocked requests for the site you're on in the filter log? Also check if your AdGuard certificate is displayed in your browser (usually you can check it next to the website address by clicking on the lock -> secure connection).

**Comment by Frankflash** [comment]
On certain  sites  eg appmirror.com

Stuff.co.nz.  and nzherald.co.nz

Sni doesn't  work properly   shows  up on

Https:// crypto.cloudflare.com/can_cigi/trace/

Shows plain text sni

Ticket  number  746884

**Comment by maxikuzmin** [comment]
@Frankflash I apologize for the long response. I don't see ads on these websites. Do you still have this recurring on the last nightly version 96?
If it is still repeating, could you take a screenshot and email devteam@adguard.com with a description of the problem?
Also please check if your website shows your AdGuard certificate (usually you can check it by clicking on the "lock" next to the link). When you are surfing these websites, also check the filter logs to see if you can see the blocked requests

**Comment by Frankflash** [comment]
Here's  Screenshots

**Comment by Frankflash** [comment]
Ads still  coming with latest  you  have to restart  to fix it

**Comment by maxikuzmin** [comment]
@Frankflash thank you! You sent a screenshot from the "Privacy info" tab, in this tab you need to click on the "lock" and see if the AdGuard certificate is displayed there. Also please check in the filter log to see if there are any requests from the site you are addressing.
It would also be a good idea to export your settings and send them to the mail as well [devteam@adguard.com](mailto:devteam@adguard.com).
To export settings:
Go to Settings tab -> the triple dot in the upper right corner-> Export settings

**Comment by maxikuzmin** [comment]
@Frankflash thanks for the long wait. I looked at all the sites you said with your settings. I don't have it repeated. I don't see ads when I turn the protection on. 
Try clearing cookies and also please clarify what browser are you using? 
Most browsers have a lock next to the link on the left, you can click on the lock -> Connection is secure -> Certificate information. 
Is your AdGuard certificate displayed there? 
Also check the Statistics tab -> Recent activity. Are there any requests for these websites?

Unfortunately I never got your logs, the last file you sent was "Settings". 
If you have AdGuard certificate displayed and there are requests for websites in Recent activity, could you re-record the logs as I wrote in the instructions above and send them?

**Comment by Frankflash** [comment]
[adguard_logs_4.0.895_0306_174119.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11641870/adguard_logs_4.0.895_0306_174119.zip)
 Samsung  browser   21.0.0.41.  No adguard certificate  shown  when  you click on  secure connection  padlock  certificate  is not displayed  it shows on Chrome  but not Samsung  browser  it all

**Comment by maxikuzmin** [comment]
@Frankflash thank you, we will look into it. 
Please answer: have you tried clearing cookies? Does Recent activity show blocked requests when you are on those sites?
Does the Chrome browser display the AdGuard certificate?

**Comment by Frankflash** [comment]
Yes yes  and yes chrome  shows adguard certificate  but Samsung browser
does not show it when you  click  on  the padlock  for secure connection

**Comment by Frankflash** [comment]
It's working!

**Comment by maxikuzmin** [comment]
@Frankflash glad to hear it! I'm closing this issue. It would be nice if you could clarify exactly what helped solve the problem. Maybe in the future users will have similar issues
