### ISSUE TITLE
Apps sometimes doesn't showed in app management

### ISSUE THREAD

**Issue by loca-lhost** [AdguardTeam/AdguardForAndroid#4582]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.752

### Environment

```markdown
- OS:Android 12
- Device:Note 11 Pro 5G
- Firmware:MIUI 13.0.7.0
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

I have excluded some apps from being filtered, especially https filtering. But often times and randomly it doesn't work. When I attempt to go through the list of apps it doesn't load all apps unless I quit the app and restart it then it loads all the app again and then the unrouted apps start working again.

### Expected Behavior

The apps are suppose to show. 

### Actual Behavior

The apps sometimes doesn't show unless you quit adguard and restart it before it shows!

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@loca-lhost I don't have this problem repeatedly. Does it happen with specific applications or with random applications?
Please select Logging level -> Debug, and try to catch this moment. Please make a recording of the screen where the problem repeats, then email your logs and screen recording to devteam@adguard.com

**Comment by maxikuzmin** [comment]
@loca-lhost any news?

**Comment by loca-lhost** [comment]
I updated to the latest version over the weekend so i haven't seen the behavior. Am monitoring it to see!

**Comment by loca-lhost** [comment]
So what i realized is. It does this after an update. After the update i tried searching and it didn't show my unrouted apps and https filtered apps. Unfortunately I couldn't capture. I will capture if an update drops today.

**Comment by maxikuzmin** [comment]
@loca-lhost any news?

**Comment by maxikuzmin** [comment]
@loca-lhost for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by loca-lhost** [comment]
Issue was resolved. Thanks
