### ISSUE TITLE
Typo for firewall strings

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#4584]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 nightly 88

### Environment

```markdown
- OS: Android 8.1.0
- Device: Samsung
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to the section where strings are used.

### Expected Behavior

Firewall should be used as uppercase in strings.

### Actual Behavior

Firewall is used as lowercase in strings.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/35523759/232127563-f85cfd1a-d7f5-4e89-9bf9-7c32fa200cf4.png)
</details>

<details><summary>Screenshot 2:</summary>

![image](https://user-images.githubusercontent.com/35523759/232127683-3c400575-c948-4586-bd26-734c6f291e51.png)
</details>

### Additional Information

You can find strings at the Crowdin website by searching for "firewall" in the adguard-for-android-v4 file and checking the unresolved issues option.

**Comment by Versty** [comment]
@gork7777 Hi! We decided to use a lowercase when the `firewall` is an adjective. So, this is by design.

**Comment by gork7777** [comment]
@Versty Did you checked all strings? Maybe there are a few that have been missed.

**Comment by Versty** [comment]
@gork7777 Yes, this sting is correct as well.
