### ISSUE TITLE
'Protect against DPI' breaks connection to Fiddler proxy

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4585]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 n88

### Environment

```markdown
- OS: Android 9
- Device: Sony
- Firmware: yes
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Protect from DPI

### Issue Details

Steps to reproduce:
1. Prepare Fiddler Classic on Windows 
2. Add new proxy with Fiddler's IP
3. Enable `Protect against DPI` option
4. Open any site.

### Expected Behavior

HTTP traffic captured by Fiddler.

### Actual Behavior

Fiddler cannot capture traffic, sites do not open. In Chrome I see ERR_CONNECTION_CLOSED error.

### Additional Information

Not sure if this is a bug, but in Windows I can't reproduce this issue.

**Comment by sfionov** [comment]
You may disable incompatible option when fiddler is used
