### ISSUE TITLE
Proxy apps can't connect to 443 port in auto-proxy mode

### ISSUE THREAD

**Issue by ibtb322** [AdguardTeam/AdguardForAndroid#4586]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11, 4.0 Nightly 88

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi Mi 6
- Firmware: LineageOS 20.0
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Enable auto-proxy mode
2. Enable DNS-filtering and select any server
3. Exclude proxy application from filtering list
4. Set VPN mode in proxy app (error doesnt occur in local proxy server mode)
5. Connect to the ss/vless/vmess/etc proxy server on port 443 in any app (v2rayng/shadowsocks/sagernet/etc)
6. Other AdGuard settings dont matter

### Expected Behavior

Successful connect to proxy

### Actual Behavior

Connection error, for example _Unable to resolve host 'cp.cloudflare.com', No address associated with hostname_
If you disable AdGuard, then connect to the proxy and re-enable AdGuard, connection wont be broken. 
Configurations with a port other than 443 work correctly.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

On android 11 it worked correctly.

**Comment by ibtb322** [comment]
Problem was due to DNS filtering, description was updated.

**Comment by ibtb322** [comment]
Problem not solved, the reason is dns filtering in autoproxy mode, serves doesnt matter.

**Comment by Versty** [comment]
@ibtb322 Hi! 
We are sorry for the long wait for a reply. Could you please collect the debug logs for further investigation of the issue? 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Sent this file to devteam@adguard.com:
      - mention the `4586` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@ibtb322 Any updates?
