### ISSUE TITLE
usability feedback for 4

### ISSUE THREAD

**Issue by meow-gh** [AdguardTeam/AdguardForAndroid#4590]
### Issue Details
In ag v4
It takes 2x times/more clicks to get to app management and to filtering log

In app management it's not easy to check easy firewall rule like with v3(eg app network or data access)

It's....very inconvenient 

### Proposed solution

Add shortcuts to home screen for app management and firewall management 

Improve UI to have a scrollable default firewall rule status to make it possible to skim check app statuses easily (eg internet blocked or mobile data blocked or proxy on off)

**Comment by Versty** [comment]
@meow-gh Thank you for the feedback. 
We are currently looking for the best option on where to place the App management. 
Please discuss this topic further in #4408

**Comment by Peter-maximus** [comment]
any update?

especially on:
_Improve UI to have a scrollable default firewall rule status to make it possible to skim check app statuses easily (eg internet blocked or mobile data blocked or proxy on off)_
