### ISSUE TITLE
No possibility to find rules that are responsible for removing HTML content

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#4600]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly

### Environment

```markdown
- OS: Android
- Device: Xiaomi
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Add `/learnadguard_img` rule to User rules
2. Go to https://learnadguard.pages.dev/staticbanner/
3. The images on that page should be removed
4. Check the filtering log afterwards

### Expected Behavior

In v3.6 we printed every removed HTML element to the filtering log and it made perfect sense, this way it is possible to understand what exact element has been removed.

### Actual Behavior

This type of events is completely missing from the filtering log now.

It is now not possible to figure out which filtering rules were applied and which elements were removed. 

### Screenshots

<details><summary>Screenshot 1:</summary>

![telegram-cloud-photo-size-4-5911408032493980773-y](https://user-images.githubusercontent.com/5947035/233364366-a81bab1f-cbbd-450c-b07d-4f7edfaccabe.jpg)

</details>

**Comment by Versty** [comment]
The corresponding rule and removed element are displayed correctly in the request details, if the `Log removed HTML events` option is enabled in the low-level settings.
