### ISSUE TITLE
Under Statistics Adguard for Android Nightly not showing images of companies (Nightly build)

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4601]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard for Android Version 4.0 Nightly 92

### Environment

```markdown
- OS:phone Android 13 and Tablet on Android 12
- Device:Samsung both
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Should show images for companies under Statistics.

### Actual Behavior

On my phone under statistics, it's not showing images of the companies.
On my tablet, it does show images for that company.

### Screenshots

![Screenshot_20230420_160438_AdGuard](https://user-images.githubusercontent.com/96619913/233489542-8ad9449b-760e-4a34-89cd-e3cf53119145.jpg)
![Screenshot_20230420_160415_AdGuard](https://user-images.githubusercontent.com/96619913/233489553-b9ea4ac8-c8c2-4c77-a2ac-3fb10fceedc6.jpg)

### Additional Information

I have the same settings on my tablet and phone. 100% the same settings.
![Screenshot_20230420_160438_AdGuard](https://user-images.githubusercontent.com/96619913/233489971-8735cf01-1a29-456b-9c96-7978f2eb1901.jpg)
![Screenshot_20230420_160415_AdGuard](https://user-images.githubusercontent.com/96619913/233489975-b2ae0b9a-e182-4c62-820b-e1c281488d43.jpg)

**Comment by Versty** [comment]
@Batman2814 Hi! This icons is provided by the domains. Does every company from the list have no icon on your phone?

**Comment by Batman2814** [comment]
Some of the companies have their symbol icon but others don't. About half of them don't have symbol icons. For example, some of them are Microsft Services, Amazon Advertising, DoubleClick, Integral AD Science, Adobe Audience Manager, Twitter Advertising, ContentSquare, reCAPTCHA, Tealium, Google Servers, Digital Window, Snapchat For Business, Adguard, Disqus, Adobe Dynamic Tag Management and there are other to that don't have the icon symbol.
