### ISSUE TITLE
Adguard Services check page not detecting Adguard for Android Nightly

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4606]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard Version 4.0 Nightly 92

### Environment

```markdown
- OS:Android 13 & 12
- Device:samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

The Adguard services check page not detecting Adguard for Android Nightly on both phones and tablets.

### Screenshots

![Screenshot_20230421_083050_Samsung Internet](https://user-images.githubusercontent.com/96619913/233650136-6b3a6269-76d3-42e3-b777-d275320868cc.jpg)
![Screenshot_20230421_082857_Samsung Internet](https://user-images.githubusercontent.com/96619913/233650147-5623aecc-a0e4-41ce-a6fd-f7e8be2ecef9.jpg)

**Comment by jordanswrld94** [comment]
![Uploading Screenshot_20230425_093842_Samsung Internet.jpg…]()

**Comment by jordanswrld94** [comment]
![Screenshot_20230425_093842_Samsung Internet](https://user-images.githubusercontent.com/118186787/234312317-b8cf9c8c-755a-445b-b285-c76b0488db54.jpg)

**Comment by Versty** [comment]
@Batman2814 Hi! 
This is not a bug. In order to be detected by the check page, HTTPS filtering should be enabled in the application along with the ad blocking module and the basic protection option.
