### ISSUE TITLE
Filtering log export

### ISSUE THREAD

**Issue by igorskyflyer** [AdguardTeam/AdguardForAndroid#4608]
### Issue Details

Hello, would it be possible to implement an export feature for the filtering log, i.e. exporting things like logged Web/DNS requests and their URLs, etc. That would help a lot filter-maintainers - like myself, to use AdGuard not just as an adblocker but as an ad collector as well! What I mean is that, I usually browse the internet then go through AdGuard's logs and track down (😏) the trackers then copy and paste each of them in a text file and then add them to my filter list.

There is already an option to export AdGuard logs but that just exports internal, runtime logs.

Thanks! 😁

**Comment by Versty** [comment]
@igorskyflyer Hi! This request duplicates #1327
If you would like to see this option in the app, please react with the thumbs up emoji on the original post.
