### ISSUE TITLE
"java.io.IOException: Input stream is closed" when trying to log in to rutracker.org

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#461]
Chrome browser with **Data Saver on**.
asus Asus ZenFone 4, Android 5
Please refer to ticket TDZ-848-90262 for http log

Probably some kind of misbehaving due to using data saving mode?

No success in reproducing it though. For me it works like this:

Sometimes it doesn't even let me see the main page, I instantly get "Уважаемые пользователи Приносим свои извинения, доступ к запрашиваемому ресурсу ограничен." when i go to rutracker.org.
Sometimes it actually lets me to the main page and to rutracker.org/forum/login.php, but after typing login\password and pressing "enter" i still get the same result (доступ к запрашиваемому ресурсу ограничен).

**Comment by vozersky** [comment]
![screenshot_2016-04-14-21-08-32](https://cloud.githubusercontent.com/assets/17472907/14572209/24b372d8-0356-11e6-919c-b1ad4d092412.jpg)

**Comment by ameshkov** [comment]
> Please refer to ticket TDZ-848-90262 for http log

I need debug log to troubleshoot this.
