### ISSUE TITLE
Log entries are out of timeline

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4611]
Entries arent realtime. Lag

https://user-images.githubusercontent.com/118186787/233866524-05463bf5-5b53-4ac3-931f-38c0431788da.mp4

**Comment by jordanswrld94** [comment]
Here is a good image. Lots of time it took to show log entries from 20 mins ago 
![Screenshot_20230424_114159_AdGuard](https://user-images.githubusercontent.com/118186787/234061814-7c3dc01e-e319-4c8d-b5e0-4b6565b3e971.jpg)

**Comment by jordanswrld94** [comment]
Issue still exists in latest

**Comment by Versty** [comment]
@jordanswrld94 Hi! 
Please check the elapsed time in the request details. Does it significantly higher than expected for the requests, which is out of the timeline?

**Comment by jordanswrld94** [comment]
Yes one is 182325 ms

**Comment by jordanswrld94** [comment]
Or are you saying is the timestamp the same? Because yes to that also

**Comment by Versty** [comment]
@jordanswrld94 The timestamp is the same as "Start time". When you see entries which is out of the timeline, you can easily detect the problematic requests, and change some settings for the apps if needed.

**Comment by jordanswrld94** [comment]
like what settings? this happens for a couple apps not just one
