### ISSUE TITLE
Notification category "protection" can be dismissed

### ISSUE THREAD

**Issue by Ali13798** [AdguardTeam/AdguardForAndroid#4612]
Hi, 

I noticed the notification category for "protection" status could not be dismissed before, much like how the "app updates" category is currently, but it can be now. Although it will appear again after being dismissed from the notification panel within a few seconds, I think it might be beneficial to make it behave like the update notification and remain in the panel when trying to manually clear it or after clicking the clear all button in the notification panel. 

The android version is 13
The app version is 4.0.785

Thanks!

**Comment by jordanswrld94** [comment]
Works fine for me. Can u send a screen record

**Comment by Versty** [comment]
@Ali13798 Thank you for the feedback. We are able to reproduce this issue on android 13, SCG09.
