### ISSUE TITLE
Proxy mode blocking network connectivity

### ISSUE THREAD

**Issue by anuraag488** [AdguardTeam/AdguardForAndroid#4614]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.788 Beta 1

### Environment

```markdown
- OS: Android 11 MIUI 13.0
- Device: Redmi Note 9 Pro Max 
- Firmware:
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Turn on proxy mode with root
2. some random apps can't access internet on mobile data. (Didn't test wifi). I have tested MiXPlorer with some cloud storage. None able to connect.
3.

### Actual Behavior

When using Proxy mode I'm unable to access internet for some apps. Internet works fine for bypassed apps. This problem even occurs if i switch to VPN mode. I have to reset network setting to resolve this issue. Toe it looks proxy mode messed up something in setting.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

 I have sent log file to devteam@adguard.com with issue number mentioned in subject.

**Comment by Versty** [comment]
@anuraag488 This issue is under investigation, we are sorry for the long wait. 
Your logs have been received as well. 
Have you replaced the HTTPS certificate to the system storage?

**Comment by Versty** [comment]
@anuraag488 Any updates? 

Does the issue persist on the latest nightly version?

**Comment by Versty** [comment]
@anuraag488 Closed due to lack of activity. 
If the problem still persists, please reopen this issue.
