### ISSUE TITLE
Whisper app broken by https filtering

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#462]
On whisper the latest section is broke among other things. Adding whisper.sh to https whitelist filter fixes the app: https://play.google.com/store/apps/details?id=sh.whisper

**Comment by Revertron** [comment]
Added to exceptions.

**Comment by jo2dan23** [comment]
only the whisper.sh domain needs to be whitelisted not the whole app. idk if thats what you meant by exceptions just wanted to make sure.

**Comment by ameshkov** [comment]
@jo2dan23 if one domain is enough, then we'd better add it to default ssl domains whitelist.
@Revertron could you please do it?

**Comment by Revertron** [comment]
Okay, done!
