### ISSUE TITLE
4.0 beta 1 and sagernet don't work together

### ISSUE THREAD

**Issue by pongfcnkl** [AdguardTeam/AdguardForAndroid#4620]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 beta 1

### Environment

```markdown
- OS:Android 12
- Device:Motorola
- Firmware:G100
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter

### Issue Details

v4.0 (BETA) cannot be used in proxy software such as shadowsocks android
Works fine in 3.6.11

**log**
[adguard_logs_4.0.788_2604_143513.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11329759/adguard_logs_4.0.788_2604_143513.zip)

 **screenshot  4.0beta 1**
![photo_2023-04-26_14-35-59](https://user-images.githubusercontent.com/24273319/234490670-b2b87ffd-a005-48ae-83d9-08f84094d276.jpg)
![photo_2023-04-26_14-41-06](https://user-images.githubusercontent.com/24273319/234490839-90d0ddd4-90a4-4fb7-86a1-6fd56c713cfa.jpg)
![photo_2023-04-26_14-35-59 (3)](https://user-images.githubusercontent.com/24273319/234491024-d1fcd895-aed0-4817-b907-78936dda0d73.jpg)

### Actual Behavior

4.0 beta 1 and sagernet don't work together

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by 2E98514DF5A395297392026440B30569** [comment]
Let me add a little detail:
Adguard can use Sagernet's DNS or SOCKS5 proxy alone, and it can access the Internet normally.
That is to say, dns service and SOCKS service are running normally.
However, using Sagernet's DNS and SOCKS5 proxy at the same time will cause the domain name resolution to be SERVFAIL, that is, the situation of directly disconnecting the network.

**Comment by sfionov** [comment]
@2E98514DF5A395297392026440B30569 

Seems that we have a bug, when 127.0.0.1 are redirected into a proxy.

To workaround this bug:
1) Open Settings -> General -> Advanced -> Low-level settings -> Outbound proxy -> Show the "Filter DNS requests" setting.
2) Go to outbound proxy setting and disable "Filter DNS requests" for proxy. This will disable DNS redirection into proxy.

**Comment by sfionov** [comment]
@pongfcnkl Okay, it is sad that workaround does not work for you. We will try to fix this issue in the next DnsLibs release.

BTW, I had to restart AdGuard to make this setting work.

Here's my settings:

![Screenshot_20230621-185058_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/47204/c7862afa-9f70-450f-9283-a56aea22481e)
![Screenshot_20230621-183956_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/47204/8cd74266-7c26-418a-9577-f68390026a89)
![Screenshot_20230621-184021_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/47204/b737704d-d270-4451-9c33-60c12ad282d6)
![Screenshot_20230621-183923_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/47204/67d0840f-96fd-45e9-9858-de01e3695a72)
![Screenshot_20230621-184715_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/47204/1bdc3cd0-9ccb-41c8-9c93-06ebca58862b)

**Comment by chenyue404** [comment]
> @2E98514DF5A395297392026440B30569
> 
> Seems that we have a bug, when 127.0.0.1 are redirected into a proxy.
> 
> To workaround this bug:
> 
>     1. Open Settings -> General -> Advanced -> Low-level settings -> Outbound proxy -> Show the "Filter DNS requests" setting.
> 
>     2. Go to outbound proxy setting and disable "Filter DNS requests" for proxy. This will disable DNS redirection into proxy.

works for me
