### ISSUE TITLE
Via browser CA certificate

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#4621]
hello, 

can I filter https in via browser to work with AG?
I'm unrooted and https certificate is in user store and
the message says that apps cannot be filtered in nougat+,
is there any solution?

**Comment by Versty** [comment]
@patrickdrd Seems like the Via browser doesn't support any CA certificates from the user store. We also do not see any option to place the certificate directly in the browser. 
Therefore, the only solution in this case is filtering over DNS protection module.
