### ISSUE TITLE
Some translations doesn't fit to the fields

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#4623]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 nightly 95

### Environment

```markdown
- OS: Android 8.1.0
- Device: Samsung
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Change app language to Turkish, Dutch, Portuguese or etc. for reproduce.
2. Go to settings.

### Expected Behavior

When the translation is long, it must fit in this field and users should be able to read the full text to understand this setting.

### Actual Behavior

When the translation is long, it doesn't fit in this field and cannot be read completely.

These strings are long for the titiles:

- Launch AdGuard at system startup
- Route app through proxy
- Route traffic through AdGuard
- Update filters via Wi-Fi only

### Screenshots

<details><summary>Screenshot 1:</summary>

![Bug](https://user-images.githubusercontent.com/35523759/234733910-bc04f13a-e469-4fff-8db2-102cda19a300.jpg)
</details>

<details><summary>Screenshot 2:</summary>

![Translate](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/20faf013-2999-4e4d-a64d-990b887159a8)
</details>

<details><summary>Screenshot 3:</summary>

![Screenshot_20230520-234214_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/3adcdd65-3358-46a0-84a3-6b8b2252f014)
</details>

**Comment by gork7777** [comment]
@Versty Could you please check them?

**Comment by Versty** [comment]
@gork7777 Thank you for reporting.
Yes, this issue is known and reproduces with other languages as well.
