### ISSUE TITLE
AdGuard does not launch when clicking the "Open" button in the package installer after being updated 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4624]
### Version
Adguard For Android 4.0 

### Environment
- Android 13, SCG09
- Android 11

### Prerequisites
Previous 4.0 nightly version is installed 

### Steps to reproduce 
1. Launch the app 
2. Check for the updates then click `Update the app`
3. Wait until the download is complete, 
4. Confirm the update in the package installer window 
5. Wait for the update to be installed, then click `Open` in the final package installer window 

### Expected behaviour 
AdGuard is launched 

### Actual behaviour
AdGuard is not launched

**Comment by ameshkov** [comment]
@Versty did you mean that it does not start protection automatically?

**Comment by Versty** [comment]
@ameshkov This issue is about interaction between the package installer and AdGuard.
I've made some improvements to the title for better understanding. Protection start is currently working as intended.

**Comment by Versty** [comment]
This is a native Android issue, reproduces on API 30 and above. We have reported this bug to the android developers and are currently waiting for a fix.
