### ISSUE TITLE
parallel resolving mode not working

### ISSUE THREAD

**Issue by tawayaka** [AdguardTeam/AdguardForAndroid#4626]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.799

### Environment

```markdown
- OS:Android 11
- Device:Xiaomi
- Firmware:eu rom
```

### Root access

- [ ] Yes, I have it.

### Issue Details

i have enabled all parallel resolving dns in custom dns section, but it doesn't work, it doesn't run parallel with other dns i added.

### Actual Behavior

enable parallel resolving in custom dns, it doesn't work with the dns i added.

### Screenshots

<details><summary>Screenshot 1:</summary>

![IMG_20230427_184644](https://user-images.githubusercontent.com/30314539/234853068-e8c3bbfd-181f-44e7-a4a1-a7af6dd1ebe1.jpg)
![IMG_20230427_184937](https://user-images.githubusercontent.com/30314539/234853369-561d118b-fe1f-46fe-b3db-2ccad865715c.jpg)

</details>

**Comment by Versty** [comment]
@tawayaka Hi! 
Two or more dns servers should be placed in the same address field to resolve together, each on a new line.
