### ISSUE TITLE
Test alternative certificate installs when no Adguard certificate installed in system.

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#463]
There were some crashes that were fixed, need to test on a new build.

**Comment by gshumihin** [comment]
Problem with android N: 
After certificate was installed, https filtering didn't turned on automatically. In other versions of android alternative certificate installation works fine.

**Comment by Revertron** [comment]
Okay, we will test it again when the N will release itself.

**Comment by ameshkov** [comment]
@gshumihin file an issue on this, we'll assign it to v2.6

**Comment by gshumihin** [comment]
opened issue #474 for that
