### ISSUE TITLE
HTTPS filtering breaks page loads in the browser

### ISSUE THREAD

**Issue by ISkIN-AI** [AdguardTeam/AdguardForAndroid#4639]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.9.804

### Environment

```markdown
- OS: Android 11
- Device: Xiaomi Poco X3 Pro
- Firmware: crDroid 7.21
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Enable https filtering for the browser
2. Surf the Internet

### Expected Behavior

Pages open without problems

### Actual Behavior

In most cases, pages do not open the first time. Depending on the browser, the page freezes at half of the loading bar or the loading stops, but nothing is actually displayed (see screenshots). After several attempts to reload the page and restart the browser, the page somehow loads. And it happens very often, about 80% of the time.
If you disable https filtering for the browser, the pages start loading quickly and correctly, but this is not an option, because in this case no ads are blocked.

### Screenshots

<details><summary>Screenshot (Yandex Browser):</summary>
The loading is frozen, the bar does not move

![image](https://user-images.githubusercontent.com/43850590/235291330-c1cc7049-698a-4108-a6b3-a8a1e6eee9e6.png)

</details>
<details><summary>Screenshot (Duckduckgo):</summary>

![image](https://user-images.githubusercontent.com/43850590/235291312-f58f0fec-9e98-47df-b931-06d1164602a6.png)

</details>

**Comment by Versty** [comment]
@ISkIN-AI Hi!
Please specify the routing mode: Local VPN, Auto or Manual proxy?

If you disable tracking protection module, does the issue persist?

**Comment by ISkIN-AI** [comment]
Routing mode: Local VPN
If I disable the anti-tracking module, the problem persists

**Comment by Mysticales** [comment]
I have the same issue. Pages half load and sometimes page element bars even are disconnected from where they should be. 
Example is ddwrt router admin pages.

**Comment by ISkIN-AI** [comment]
I also found that disabling filtering for the application (1 screenshot) removes problems (which is obvious), but disabling all filters does not (2 screenshot). Apparently, the problem is not with some filters, but with some general mechanism of handling traffic going through Adguard.

<details><summary>Screenshot 1:</summary>

![Screenshot_20230430-220003123](https://user-images.githubusercontent.com/43850590/236687140-eddb50e0-180f-4610-8d04-460c49f011b5.jpg)


</details>
<details><summary>Screenshot 2:</summary>

![screenshot2](https://user-images.githubusercontent.com/43850590/236687226-810da1aa-af82-41fc-b434-b6d8d48efe7f.png)


</details>


I understand that I have not provided enough information, and if it is not possible to repeat this behavior, it might be hard to localize the error, so please let me know if I need to provide any logs and additional information. This problem makes it impossible to use the browser with Adguard fully enabled.

**Comment by ISkIN-AI** [comment]
At the moment the problem does not recur, so I will close the issue for now

**Comment by Versty** [comment]
@ISkIN-AI We have made some adjustments, and we are glad it helped.
