### ISSUE TITLE
Musically app broken by https filtering.

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#464]
Made a test account:
Username: adguardtest

Password: adguard

**Comment by ameshkov** [comment]
This app?
https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically&hl=en

**Comment by jo2dan23** [comment]
yes. i pasted the link i don't know why it didn't save. my bad

**Comment by Revertron** [comment]
Adding "musical.ly" to ssl_exceptions fixes the problem.

**Comment by jo2dan23** [comment]
just wanted to make sure for this app also. that only the domain needs to whitelisted sorry if thats what you meant.
