### ISSUE TITLE
No https certificate related alert on 4.0

### ISSUE THREAD

**Issue by uaevuon** [AdguardTeam/AdguardForAndroid#4641]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 beta 1

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi Poco F3
- Firmware: Latest
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Install adguardcert magisk module for copying certificate on system.
2.  Open the app that does not accept adguard certificate

### Expected Behavior

Make a notification like on v3

### Actual Behavior

There is no notification about the app not accepting adguard certificate.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@uaevuon Thank you for the feedback. 
Could you provide some examples of applications where the notification is shown in version 3.6 but not in 4.0?

**Comment by uaevuon** [comment]
KB Pay(com.kbcard.cxh.appcard by kbcard)
KB Star Banking(com.kbstar.kbbank by kbbank)
O2(com.samsungpop.android.masset by samsung securities)
...

All apps that sent notification on 3.6 do not send notification on 4.0.

**Comment by Versty** [comment]
@uaevuon Hi! 
We have discussed this issue with development team. This type of notifications was removed intentionally as a part of application improvements. 
Currently, we have no plans to return the mentioned above custom type of notifications.
