### ISSUE TITLE
When backing out of log completely multiple times position is still saved

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4644]
Sometimes it saves sometimes it doesn't what is supposed to be the default behavior?

https://user-images.githubusercontent.com/118186787/235497840-2ec91cb9-b33d-43c1-ba26-42335fb48a5e.mp4

**Comment by Versty** [comment]
@jordanswrld94 Thank you for noticing! 
The position should be reset after returning to the Statistics tab.
