### ISSUE TITLE
When installing adguard "always-on vpn" option should be turned on

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4645]
![Screenshot_20230501_124200_Settings](https://user-images.githubusercontent.com/118186787/235499157-f76b5a66-aa54-452c-9c55-20dc223b509f.jpg)

**Comment by Versty** [comment]
@jordanswrld94 In this case, any other VPN client installed on the device will not be able to create a VPN tunnel. So this idea is not as good as it sounds.
