### ISSUE TITLE
Graphs are not displayed in some cases 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4646]
### Version
AdGuard for Android 4.0 nightly 97

### Environment
Any compatible android version

#### Steps to reproduce 
1. Install AdGuard 
2. Enable the protection and surf some internet 
3. Open the Statistics, the ads/trackers/requests data should be collected 
4. Make sure the graphs for this data is displayed 
5. Disable the protection 
6. Check the same graphs again 

#### Steps to reproduce 
1. Install AdGuard
2. Disable every protection feature except for the DNS protection module
3. Turn on the protection switch on the Home tab and surf some websites 
4. Disable the AdGuard's protection 
5. Go to the Statistics -> View all companies 
6. Click any company in the list 
7. Tap on any stats counter

### Expected behaviour for both cases 
Graphs are displayed

### Actual behaviour 
Graphs are not displayed 

| Case 1 | Case 2|
|-------|--------|
| ![tempFileForShare_20230501-132839](https://user-images.githubusercontent.com/107266340/235527223-684a4e40-e33d-45fb-b850-f9ce78ba3487.png) | ![tempFileForShare_20230430-091314 (1)](https://user-images.githubusercontent.com/107266340/235527460-33cdea06-29d8-45f9-94c9-d1b158dd209e.png) |

**Comment by Numci** [comment]
For case 1: 
It's normal, just collect more statistics and graphs will be showed

For case 2:
We can't represent statistics for apps if DNS protection only enabled.
