### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by random09456** [AdguardTeam/AdguardForAndroid#4649]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 97

### Environment

```markdown
- OS: Android 13, One UI 5.1
- Device: Samsung S23 Plus
- Firmware: S916BXXS1AWD1

I hope you can help me :)
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, Others

### Issue Details

Steps to reproduce:
1. Start mobile phone
2. After entering PIN /Unlocking AdGuard crashes on startup

I can launch and use the app normally after launching it manually. There is then no crash. Only when switching on or restarting the phone, the app crashes directly at startup.

*logs have been removed to protect your privacy*

### Expected Behavior

Normal startup behavior.

### Actual Behavior

Crashes on startup.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by random09456** [comment]
[adguard_logs_4.0.788_0505_102932.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11404539/adguard_logs_4.0.788_0505_102932.zip)
![AdGuard_Crash](https://user-images.githubusercontent.com/132367110/236413621-e2852f6e-806d-445c-a48a-dc09cce9a8fd.jpg)
![AdGuard Notification Panel](https://user-images.githubusercontent.com/132367110/236413625-795e28b5-0c1a-4d41-bd7c-aace960d6f48.jpg)

**Comment by Versty** [comment]
@random09456 Thank you for the details provided. This issue will be fixed.
