### ISSUE TITLE
Battery, is this normal?

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForAndroid#4650]
1) First screenshot: is it normal to have this battery incorrect behavior? 
2) Second screenshot: is it necessary to keep the app running in the background?

AdGuard 4.0 beta 1

Android 13

![2023-05-02 19 29 51](https://user-images.githubusercontent.com/1675875/235741792-0d645650-c62f-41e9-9874-2c7d4f49f0c4.jpg)

![2023-05-02 19 29 46](https://user-images.githubusercontent.com/1675875/235741755-998e8d73-cffc-4f83-acdc-c1eb276a488b.jpg)

**Comment by Versty** [comment]
@michael1900 Hi! 
The background work for AdGuard is necessary to maintain filtering of applications that are currently in the foreground.
Battery consumption in the backgroud also depends on the applications that are active and filtered by Adguard. Usually the consumption is low, but if you watch videos or scroll through the feed with a lot of ads and trackers, the consumption will be slightly higher than usual.
