### ISSUE TITLE
Bank app detect AdGuard as VPN and will not work.

### ISSUE THREAD

**Issue by githubuser013** [AdguardTeam/AdguardForAndroid#4656]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v3.6.11 (54) and v4.0 beta 1

### Environment

```markdown
- OS: android 13.1
- Device: Oneplus 10 pro
- Firmware: OxygenOS
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard DNS filter, Liste AR

### Issue Details

Steps to reproduce:
1. Download the SNB Mobile app (Bank App): https://play.google.com/store/apps/details?id=com.snb.alahlimobile&hl=en&gl=US&pli=1
2. open it
3. the app detect the VPN is active and it will not continue to work, The VPN is not allowed for app to work even the (route traffic through adguard) option is off.

### Expected Behavior

If the route traffic through adguard option is off the app should work fine.

### Actual Behavior

The VPN is detected anyway.

### Screenshots

<details><summary>Screenshot 1:</summary>

!-- ![Screenshot_2023-05-04-05-42-50-07_6bd7c270cf51f6de9ad7e3247db93059](https://user-images.githubusercontent.com/71437659/236104553-5049d7cc-1d27-4e97-8c75-18c003277911.jpg)

</details>

### Additional Information

Many mobile bank apps in my country now use this method.

**Comment by githubuser013** [comment]
I'm talking about adguard adblocker.

**Comment by uaevuon** [comment]
These kind of apps detect just VPN is on or off, not traffic going through vpn or not. Have to use NoVPNDetect LSPosed module if your device is rooted.
Not adguard bug.

**Comment by jordanswrld94** [comment]
U have to uncheck route traffic through adguard in app management settings

**Comment by githubuser013** [comment]
@uaevuon 
I rooted my device things got worse, the bank app won't start with root even if you hide the root.

@jordanswrld94 
Yep, I already did that with no success.

@Baeissa 
Not yet, I hope adguard had some thoughts or solution for that.

**Comment by Versty** [comment]
@githubuser013 Hi! 
Try adding `com.snb.alahlimobile` to the Excluded apps list, starting with a new line. 

*Settings -> General -> Advanced -> Low-level -> Excluded apps*

**Comment by githubuser013** [comment]
@Versty 
I tried to do that with no luck, still the same issue.

**Comment by githubuser013** [comment]
@Versty  @Baeissa 
The bank app updated two days ago and now it's working fine with adguard excluded apps.

**Comment by githubuser013** [comment]
@Versty  Thanks.

**Comment by artemiv4nov** [comment]
Well, the banking app exclude will not help because the problem is in internal checks by SNB. The AdGuard app is technically VPN, so for better experience I suppose to disable the protection via notification.
