### ISSUE TITLE
Preserve search field data after selecting an app in app management

### ISSUE THREAD

**Issue by Ali13798** [AdguardTeam/AdguardForAndroid#4658]
### Issue Details

When accessing the app management section (settings > filtering > apps > app management), the search field entry is cleared once an app is selected.

### Proposed solution

It would be beneficial to preserve the field's text after selecting an app, and pressing the back button. Note that this proposal is not to preserve the text indefinitely, rather only if the user goes back one page after selecting an app from the search results.
This way, the user does not have to type the same entry again. Since there exist a clear text "x" in the field, usability would not be hindered. 

### Alternative solution

Adding an option to the page's setting (by pressing the three dots in the top right corner of the screen), which enables or disables the preservation of the search field contents.

**Comment by Versty** [comment]
@Ali13798 Will be improved as a part of #4745 changes.
