### ISSUE TITLE
When clicking adguard dns filter in dns filters list the website should be pointed correctly.

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4659]
It points to https://adguard.com/kb/general/ad-filtering/adguard-filters/ instead of https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt

Is there a reason for this?

![Screenshot_20230504_102531_AdGuard](https://user-images.githubusercontent.com/118186787/236254706-d3d3fb44-a490-4695-9cf1-65718ce8edbf.jpg)

**Comment by Versty** [comment]
@jordanswrld94 We will make some adjustments on this screen in future versions.
