### ISSUE TITLE
Make icons on Homescreen customizable

### ISSUE THREAD

**Issue by loca-lhost** [AdguardTeam/AdguardForAndroid#4662]
### Issue Details

I don't want adguard vpn icon on my home screen. It's too unstable for my use and i hardly use it. 

### Proposed solution

Make the icons customizable, choosing the elements you want to appear and of greater use and importance. 

### Alternative solution

Make icons on Homescreen customizable

**Comment by Versty** [comment]
@loca-lhost We are looking for the better solution for the icons on Home tab. This request will be considered and discussed further in #4677
