### ISSUE TITLE
Statistics tab: Texts overlapping on the small screens 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4664]
### Version
AdGuard for Android 4.0 nightly 99 

### Environment
Android 8, Galaxy S7, 5.1-inch display

### Languages affected
FR, RU, PT-PT

### Screenshots 

| Dropdown menu and section title | ads/trackers/requests counters |
|-----|-----| 
| ![Screenshot_20230505-172939_AdGuard](https://user-images.githubusercontent.com/107266340/236509804-a727e534-a253-453d-aaf6-b2d52ebe3306.jpg) |  ![Screenshot_20230505-190623_AdGuard](https://user-images.githubusercontent.com/107266340/236509330-cc991ae0-073c-4299-890b-fb19620230db.jpg)  |
| ![IMG_20230501_113158](https://user-images.githubusercontent.com/107266340/236510521-7321df1d-7029-44f1-b850-7a6d3d29b7cb.jpg) |  |

**Comment by coldun** [comment]
И не только в окне статистики текст перекрывается или обрезается.
Samsung j7 2016 screen 1280x720
![photo_2023-05-26_19-56-14](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/f8eefc52-b3c1-4df2-b70b-6a822252f16a)
![photo_2023-05-26_19-57-03](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/ef8ca425-4510-484c-9029-dd4405f8ef61)
![photo_2023-05-26_19-57-09](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/6b64798f-0fcd-4356-bd95-30150178db0e)
![photo_2023-05-26_19-57-13](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/d5b42357-d79a-40c4-91d2-661bbcf5d07e)
![photo_2023-05-26_19-57-19](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/b0aaf888-6362-4138-b78d-6345a97eb40f)
![photo_2023-05-26_19-57-22](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/7319fb0c-0617-4321-8c50-752db27853fd)
![photo_2023-05-26_19-57-25](https://github.com/AdguardTeam/AdguardForAndroid/assets/38978645/4e23e49b-a6d1-44c6-bdec-410521b78615)

**Comment by coldun** [comment]
closed this as completed 1 minute ago 
facepalm:)
