### ISSUE TITLE
Le site internet me demande de désactiver adblock

### ISSUE THREAD

**Issue by Zardangus** [AdguardTeam/AdguardForAndroid#4667]
Bonjour,
J'utilise Adblock 3.6.4 sur Android EMUI 12.

Depuis quelques temps, certains sites l'affichent un message pour me demander de désactiver Adblock pour continuer. Si je ne désactive pas Adblock je suis bloqué je ne peux rien faire.

![Screenshot_20230508_100622_com android gallery3d](https://user-images.githubusercontent.com/67057008/236770664-c4cc4ebf-5a77-45f2-8c43-df46def06459.jpg)

J'avais déjà eu ce problème il y a un an, un admin ici m'avait aidé à résoudre ce problème avec cette règle :

ebookdz.com#%#//scriptlet("abort-current-inline-script", "document.createElement", "adblockInfo")

Mais cette règle ne fonctionne plus depuis ce matin.

Pourriez-vous m'aider s'il vous plaît ?

Regards.

**Comment by Zardangus** [comment]
Please help me to fixe this issue.
Thank you.

**Comment by Versty** [comment]
@Zardangus Hi! Seems like your issue is related to filters.
Please fill in the incorrect blocking report via this link https://reports.adguard.com/fr/new_issue.html
