### ISSUE TITLE
The icons on the home screen of the app are not informative

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardForAndroid#4668]
### Issue Details

Without any comments it is hard for users to understand the meaning and function of each button.

### Proposed solution

Please suggest more solutions to solve the issue.

**Comment by quailallstar** [comment]
Thanks for listening to my feedback. These icons are the ones I am referring to. ![Screenshot_2023-05-07-18-14-12-89_a93965f46c4a4b0ed1be737bdf2bc8fc.jpg](https://user-images.githubusercontent.com/39922893/236792004-ede63b7f-c08b-4e2a-958a-a37c6fbab91f.jpg)
