### ISSUE TITLE
DNS protection: "Automatic DNS" make the "DNS server for other cases" changeable manually

### ISSUE THREAD

**Issue by Lazyhms** [AdguardTeam/AdguardForAndroid#4669]
### Issue Details

"DNS server for other cases"  is configured in device settings, can't change. I want use "DOH" or "DOT" or "QUIC", so may make it changeable manually?

### Proposed solution

make it changeable manually

**Comment by Versty** [comment]
@Lazyhms Hi! 
Why would you prefer using automatic DNS rather than DNS servers from a list, or adding any custom DNS you like?

**Comment by Lazyhms** [comment]
@Versty  Thank you for listening!
1. I want to use some custom unpolluted DNS services。
2. I want to use both "Adguard For Android" and proxy app like "Clash For Android" and "v2rayN". If I can change it, I don't have to change DNS settings as often.

**Comment by Versty** [comment]
@Lazyhms How do you integrate the apps with each other? Like AdGuard and Clash. 
Android does not support two VPN tunnels at the same time, so one of the apps probably works as a proxy. 
Could you describe the whole scheme?

**Comment by Lazyhms** [comment]
@Versty Yes, Adguard uses VPN mode, Clash uses proxy-only mode，Here are the steps

1. Open Clash and go to Network -> Route System Traffic , disable it.
2. Open Adguard and go to Settings -> Filtering ->Apps -> App management , Chooses “Clash For Android” and disable Route traffic through Adguard.
2. Open Adguard and go to Settings -> Network->Proxy-> Proxy server , add one.
3. Open Adguard and go to DNS protection -> Automatic DNS -> DNS server for Integration mode or outbound proxy. add one
4. Start both Adguard and Clash.

**Comment by artemiv4nov** [comment]
As a good solution you can use our Automation API to change DNS servers on your way.
