### ISSUE TITLE
Self-destruction of first-party cookies doesn't work in Brave browser 

### ISSUE THREAD

**Issue by Gittyperson** [AdguardTeam/AdguardForAndroid#4672]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11 (54) (Premium)

### Environment

```markdown
- OS: Android 12
- Device: Realme 7 Pro
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, Filter unblocking search ads and self-promotion, EasyList, Fanboy's Anti-thirdparty Fonts

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

The "Self-destruction of first-party cookies" setting doesn't seem to work. Is it compatible with all browsers?

Steps to reproduce:
1. Enable Self-destruction of first-party cookies
2. Set TTL of first-party cookies to 1 min.
3. Wait 2 min. or more and use Brave Browser (v.1.51.110, Chromium 113.0.5672.77)

### Expected Behavior

I'd expect to be logged out of all websites I've previously logged in with my account, using username/password.

### Actual Behavior

I remain logged in to websites (e.g. Disqus, Kickstarter and all ones I've tried). Tried waiting a few minutes, restarting the browser and restarting the device. In Brave's privacy settings, I've set "Allow all cookies" to avoid interference.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Gittyperson** [comment]
After further tests, some logins are indeed cleared but definitely not all.

Don't know why. Perhaps websites use other means to maintain credentials, apart from cookies?

**Comment by maxikuzmin** [comment]
@Gittyperson thanks for the long wait! What version of AdGuard are you using? Is this still recurring on the latest version of AdGuard 4.0?

**Comment by maxikuzmin** [comment]
@Gittyperson any news?

**Comment by Gittyperson** [comment]
I will have to re-check with AdGuard 4.0. Might take a day or two.

**Comment by maxikuzmin** [comment]
@Gittyperson any news?

**Comment by maxikuzmin** [comment]
@Gittyperson we have had a few cases where we have had to contact Brave browser, they usually also handle all appeals and respond quickly, I would recommend doing so.
In this case there is no direct conflict between the two applications, the distrust of certificates is more of a general application policy that happens to affect us. Firefox also distrusted third-party certificates for security purposes for quite a while, but after a while they added a "allow third-party certificates" feature. If it weren't for user requests, they wouldn't have added this feature.
We can either wait for feedback from Brave browser and improvements, or at least temporarily change to a different browser.
I'm closing this issue for the moment
