### ISSUE TITLE
AdGuard does not recognise "tcp://" as a valid DNS server protocol

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#4673]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 Beta 1

### Environment

```markdown
- OS: Android 10
- Device: Motorola One Zoom
- Firmware: Official
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList Lithuania, Adblock List for Finland, Dandelion Sprout's Annoyances List, IndianList

### Issue Details

Steps to reproduce:
1. Go to Protection → DNS Protection → DNS server → Custom servers → Add DNS server → In "Server addresses, one per line", type in something like `tcp://192.1.2.3` → Try to press "Save".
2. The error message "Please enter a valid protocol" shows up.

Using `tcp://` for a DNS server is supported in AdGuard Home, and was supported in AdGuard for Android 3.x, so there seems to have been a feature regression that has occured.

### Expected Behavior

Specifying and using the `tcp://` protocol for a custom DNS server, is supported.

### Actual Behavior

The app does not seem to allow server addresses that specify the `tcp://` protocol 

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230510-003844](https://github.com/AdguardTeam/AdguardForAndroid/assets/22780683/9aab22e1-edd0-46c9-94c0-882a087256e8)

</details>

### Additional Information

Although very few professionally run DNS servers seem to officially support `tcp://` (although AdGuard Home supports it by default), I figure that since it's supported in other/earlier AdGuard products, then it would've been great to see it be supported in AdGuard for Android 4.x as well.

**Comment by Versty** [comment]
@DandelionSprout Thank you for reporting. 
This issue had dropped out of our radar, but now we have successfully reproduced the issue. 
Will do our best to restore the functionality.

**Comment by artemiv4nov** [comment]
Well, please use a plain DNS server add without "tcp://" and your DNS server will be added then.

**Comment by DandelionSprout** [comment]
It was supported in 3.x, it is still supported in AdGuard Home, so please don't try to do this kind of belittling passive-aggression on me.

I am definitely @-ing @ameshkov for a Second Opinion on this.

**Comment by ameshkov** [comment]
@DandelionSprout it's actually controlled by DnsLibs, opened a feature request there: https://github.com/AdguardTeam/DnsLibs/issues/208

**Comment by artemiv4nov** [comment]
@DandelionSprout Please follow rules and subscribe to another feature request.
