### ISSUE TITLE
Truncated list in https filtered apps and apps operating through proxy

### ISSUE THREAD

**Issue by loca-lhost** [AdguardTeam/AdguardForAndroid#4688]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.102

### Environment

```markdown
- OS:Android 12 
- Device:Xiaomi
- Firmware:MIUI
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Setting>Filtering>Apps>https filtered apps/apps operating through proxy
2. Scroll to the bottom and you won't find all your disabled apps for these sections

### Expected Behavior

All disabled apps are suppose to show on the list. 

### Actual Behavior

It's a truncated list. It doesn't show all disabled apps. 

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-05-14-06-53-17-559_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/35551569/691a152c-fb6f-44b1-8d72-811b76191551)

![Screenshot_2023-05-14-06-42-11-819_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/35551569/1ec95a55-ea31-4a88-85d3-3aea28977381)

</details>

**Comment by Versty** [comment]
@loca-lhost Thank you for noticing! 
This bug will be fixed.
