### ISSUE TITLE
Snapchat app broke by https filtering

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#469]
Randomly stop getting notifications and when i try to send a chat or snap it says cant send until i whitelist the app itself. I tried two domains in the https filter whitelist for Snapchat tbat i thought were breaking it and it still didn't fix it. So idk how i could see what's breaking it?

**Comment by ameshkov** [comment]
I'd like to check your AG log to see which domains we can whitelist.

**Comment by ameshkov** [comment]
Could you please record log with "Record HTTP requests" level

**Comment by jo2dan23** [comment]
its not a http request beign blocked tho. its https. once i add snapchat to the app exceptions list for https it fixes everything.

**Comment by ameshkov** [comment]
I understand, all requests will be in that log.

**Comment by jo2dan23** [comment]
i did a record everything and still couldn't find anything that shows its being blocked... maybe if someone else could test? im sure not many adguard users use snapchat

**Comment by ameshkov** [comment]
You won't see it as nothing is blocked, the problem may be in the snapchat app checking server certificate and not trusting AG cert. So we should look for errors there.

**Comment by jo2dan23** [comment]
sorry for the late reply. i did the http requests log level. should i be doing it with the app in the app exceptions list or not the exceptions list? since it is broke when not in app exceptions.

**Comment by jo2dan23** [comment]
here is log with snapchat not in https app exceptions list
http://d-h.st/3l9x

**Comment by jo2dan23** [comment]
this line is odd: Error while processing connection. Connection info: com.snapchat.android /172.16.209.1:42950 /23.236.53.204:443 10571

**Comment by jo2dan23** [comment]
whats weird is i have https filtering enabled and it sends messages now without failing. but if i disable adguard and reneable again it fails to send messages. idk what is going on. it must be a connection that is reached at random times that is failing to get the certificate for.

**Comment by jo2dan23** [comment]
the connection info line changes. now it says 172.16.209.1:53462 /216.58.216.81:443 100571

**Comment by jo2dan23** [comment]
here is my log: http://nopaste.linux-dev.org/?1075245

**Comment by jo2dan23** [comment]
Error while processing connection. Connection info: com.snapchat.android /172.16.209.1:50898 /23.236.53.204:443 10571

Error while processing connection. Connection info: com.snapchat.android /:::33710 /23.236.53.204:443 10571

Error while processing connection. Connection info: com.snapchat.android /172.16.209.1:35140 /74.125.207.141:443 10571

Error while processing connection. Connection info: com.snapchat.android /:::48255 /74.125.207.141:443 10571

Error while processing connection. Connection info: com.snapchat.android /:::34636 /74.125.207.141:443 10571


these look like the main problem

**Comment by ameshkov** [comment]
Could you please try adding these two domains to HTTPS whitelist and see if it helps?
```
chat.snapchat.com
app.snapchat.com
```

HTTPS settings -> Whitelist

**Comment by jo2dan23** [comment]
that didn't fix it. new log: http://nopaste.linux-dev.org/?1077398

**Comment by ameshkov** [comment]
@jo2dan23 not enough information in that log, could you please switch to "Record everything" level?

**Comment by jo2dan23** [comment]
http://nopaste.linux-dev.org/?1077399

**Comment by ameshkov** [comment]
@jo2dan23 hm, no issues in this new log. Also i don't see this chat.snapchat.com connection which was failing in the previous log

**Comment by jo2dan23** [comment]
i have added those to domains to whitelist that is why i think.

**Comment by ameshkov** [comment]
@jo2dan23 nope, I don't even see it trying to connect.

Here is a problematic connection which details I'd like to see:
Error while processing connection. Connection info: com.snapchat.android /172.16.209.1:35780 /23.236.53.204:443 10571

**Comment by jo2dan23** [comment]
here try this one. i i tried to reproudce the issue multiple times so hopefully it will show in log. http://nopaste.linux-dev.org/?1077417

**Comment by ameshkov** [comment]
Connection TCP id=102700 is what I am looking for, but the log is not full, half of the information there.

**Comment by jo2dan23** [comment]
http://nopaste.linux-dev.org/?1077418

**Comment by jo2dan23** [comment]
whats weird is i got to send a couple times sucessfully without the app in https exceptions. so it is a random connection that isn't appearing or something?

**Comment by ameshkov** [comment]
> so it is a random connection that isn't appearing or something?

When AG cannot establish a secure connection, it adds this endpoint to a temporary exceptions list and does not filter it further.

**Comment by jo2dan23** [comment]
so should i keep trying til it does that?

**Comment by ameshkov** [comment]
In theory we've already added chat.snapchat.com to exceptions, so AG should not even try to filter it.
But, for some unknown reason, it is not whitelisted and I saw a failed first connection in one of your logs.

To check it:
1. Force stop snapchat
2. Restart AG
3. Start snapchat and use it for a minute or so, navigate somewhere there

I hope this one minute log will be enough.

**Comment by jo2dan23** [comment]
http://nopaste.linux-dev.org/?1077470

**Comment by jo2dan23** [comment]
i got it to work after 20 times without whitelisting the whole app. problem is. if adguard is stopped and restarted it is broken again.

**Comment by ameshkov** [comment]
> if adguard is stopped and restarted it is broken again.

That's because this temporary exceptions cache is cleared on the app restart.

**Comment by ameshkov** [comment]
Ok, great, that's what I need:

```
12:05:51.740 [pool-2-thread-731] DEBUG com.adguard.filter.proxy.a.k - TCP id=102818 Establishing SSL proxy connection
12:05:51.741 [pool-2-thread-731] DEBUG com.adguard.filter.proxy.a.k - TCP id=102818 Received ClientHello:
TLS ClientHello
  Record Layer Version:
    0x0301
  Version:
    0x0303
  Random Bytes:
    [-88, 125, 58, -90, 61, -35, 90, 82, -68, -13, -1, 6, 103, 112, 26, 108, -21, 84, 102, 102, -120, 98, -68, -88, -90, 101, -8, -123, -125, 9, 77, -4]
  Cipher Suites:
    0xc013
    0xc02b
    0xc02c
    0xc02f
    0xc030
    0x009e
    0x009f
    0xc009
    0xc00a
    0xc014
    0x0033
    0x0039
    0x0032
    0x0038
    0xc007
    0xc011
    0x009c
    0x009d
    0x002f
    0x0035
    0x0005
    0x00ff
  Compression Methods:
    0x0000
  Extensions:
    0x000b -> [3, 0, 1, 2]
    0x000a -> [0, 50, 0, 14, 0, 13, 0, 25, 0, 11, 0, 12, 0, 24, 0, 9, 0, 10, 0, 22, 0, 23, 0, 8, 0, 6, 0, 7, 0, 20, 0, 21, 0, 4, 0, 5, 0, 18, 0, 19, 0, 1, 0, 2, 0, 3, 0, 15, 0, 16, 0, 17]
    0x000d -> [0, 30, 6, 1, 6, 2, 6, 3, 5, 1, 5, 2, 5, 3, 4, 1, 4, 2, 4, 3, 3, 1, 3, 2, 3, 3, 2, 1, 2, 2, 2, 3]

12:05:51.742 [pool-2-thread-731] DEBUG com.adguard.filter.proxy.a.l - TCP id=102818 Cipher suits count: 22
12:05:51.743 [pool-2-thread-731] DEBUG com.adguard.commons.a.r - TCP id=102818 Write 148 bytes to socket channel
12:05:51.761 [Thread-120] DEBUG com.adguard.commons.a.s - TCP id=102818 address=/23.236.53.204:443 Closing TCP connection
12:05:51.763 [pool-2-thread-731] DEBUG com.adguard.filter.proxy.a.l - TCP id=102818 Client alert raised. Level: fatal, Description: internal_error internal_error(80), Message: Failed to read record
12:05:51.764 [pool-2-thread-731] DEBUG com.adguard.commons.a.r - TCP id=102818 Write 7 bytes to socket channel
12:05:51.766 [pool-2-thread-731] ERROR com.adguard.filter.proxy.a - TCP id=102818 Error while processing connection. Connection info: com.snapchat.android /172.16.209.1:37828 /23.236.53.204:443 10571

java.nio.channels.ClosedChannelException: null
	at java.nio.SocketChannelImpl.checkOpenConnected(SocketChannelImpl.java:424) ~[na:0.0]
	at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:360) ~[na:0.0]
	at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
	at com.adguard.commons.a.r.write(Unknown Source) ~[na:0.0]
	at org.apache.commons.io.output.ProxyOutputStream.write(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.RecordStream.writeRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeWriteRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.raiseAlert(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.failWithError(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsProtocol.completeHandshake(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsClientProtocol.connect(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.o.i(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.k.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.k.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.filter.f.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.c.d.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.c.d$2.run(Unknown Source) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
12:05:51.766 [pool-2-thread-731] DEBUG com.adguard.filter.proxy.k - TCP id=102818 Closing TcpConnectionContext
12:05:51.767 [pool-2-thread-731] DEBUG com.adguard.filter.proxy.k - TCP id=102818 TcpConnectionContext has been closed
12:05:51.769 [Thread-120] DEBUG com.adguard.commons.a.s - TCP id=4666 address=/127.0.0.1:59191 Closing TCP connection
```

**Comment by jo2dan23** [comment]
cool so i finally got it to log what you were looking for?

**Comment by ameshkov** [comment]
Yes, thank you:)

**Comment by jo2dan23** [comment]
awesome. so is it something that needs to be fixed in adguard itself?

**Comment by ameshkov** [comment]
Ok, good news is that thanks to this issue we've added proper elliptic curves support to our HTTPS implementation (so excluding domains will now work properly).

Bad news is that Snapchat app uses SSL pinning ( #472 ) so it's better to simply turn it off for the whole app.

**Comment by jo2dan23** [comment]
thankyou for the fast reply.

**Comment by jo2dan23** [comment]
what is ellipic curves support if i may ask? just curious

**Comment by jo2dan23** [comment]
also. the app called vine shows me a connection error info in the logs.i was just testing apps to see if any of them also get the error. the app works fine it is just failing to get the certifiate for a domain which maybe what is going to be fixed by the new elliptic thing you talked about

**Comment by jo2dan23** [comment]
they all point to vineapp.com
