### ISSUE TITLE
add rewrites dns

### ISSUE THREAD

**Issue by tawayaka** [AdguardTeam/AdguardForAndroid#4692]
### Issue Details

Looks like adguard is anti dns hijacking, i cant use dns rewrite in nextdns when using adguard, so i hope adguard can add this functionality, thank

**Comment by Versty** [comment]
@tawayaka Hello there! 

DNS rewrites are already available in the AdGuard for Android application. You can create and use your own dns rewrite rules in the Protection tab -> DNS protection -> DNS filters -> User rules. 

[Read more about dns filtering rules syntax](https://adguard-dns.io/kb/general/dns-filtering-syntax/#dnsrewrite).
