### ISSUE TITLE
DNS requests are failing after switching networks until you disable and re-enable AdGuard

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4694]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.799

### Environment

```markdown
- OS: 13
- Device: Pixel 7
- Firmware: n/a
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1. Switch from Wi-Fi to mobile data
2. See SERVFAIL responses in the activity logs

### Expected Behavior

There are no SERVFAIL errors

### Actual Behavior

There are SERVFAIL errors in the log

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

> Switching DNS servers did not seem to help. I switched to a different DNS server and disconnected from WiFi. When I did I started getting DNS failures (i.e. SERVFAIL in the activity logs). It seems like there's an issue switching DNS servers when disconnecting from WiFi.
> 
> Additionally, switching DNS servers is not a viable option for me because I have services on my local network that can only be accessed when using my local DNS. Setting an alternate DNS server prevents me from accessing these services.

CRM ID w/ logs: 751221

**Comment by Eugene-Savenko** [comment]
Is this related?

> Adguard doesn't seem to report to apps when Android's internet is turned off. It keeps sending the SERVFAIL response when the internet is off. I believe that this causes installed apps to keep repeating their network calls, resulting in battery drain. This is probably an Android limitation with the way it handles VPNs, but it would be nice if Adguard reports correctly when the internet is off, if that is possible.

Logs in the helpdesk system: **760001**

**Comment by sfionov** [comment]
@Eugene-Savenko No, this is different case. SERVFAIL's may occur when switching networks because switching to new DNS servers takes some time, and some old requests may use old DNS servers and fail. 

However, if user does not want to receive SERVFAIL responses at all, he will be able to disable it in low-level settings after AdGuard 4.0 release.

**Comment by PHLAK** [comment]
The problem I (the original reporter) experienced is that DNS _continuously fails_ after switching from WiFi to cellular until I toggle Adguard off and on again (sometimes a few times).

This is particularly frustrating when I have my phone in my pocket after leaving the house and don't notice this until I realize I haven't been receiving Slack messages or open an app and get connection failures **for 30+ minutes**.

Not sure if you can see the original bug report but I submitted logs there.
