### ISSUE TITLE
AdGuard fails to import filters from an HTTPS server, importing from an HTTP one works fine

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4695]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6, 4.0

### Environment

```markdown
- OS: 12
- Device: Xiaomi 2201117TY
- Firmware: n/a
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Try adding a filer over https (https://www.yotta-zetta.com/android/adblock.txt)
2. Try adding the same one over http (http://www.yotta-zetta.com/android/adblock.txt)

### Expected Behavior

AdGuard must import both filters

### Actual Behavior

AdGuard fails on step 1, works on step 2, i.e. it fails to import a filter over https and throws the following errors:

```
14:31:53.375 [threadmanager-cached-pool-2-thread-77] WARN  c6.l - Error performing GET request to https://www.yotta-zetta.com/android/adblock.txt
javax.net.ssl.SSLHandshakeException: Chain validation failed
```

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

CRM ID w/ log files: [753012]

**Comment by Versty** [comment]
This issue reproduces on the AdGuard for Android 4.0 nightly 107 as well.

**Comment by Coolhabit** [comment]
@Eugene-Savenko Hi, Eugene!
Please check up the certificate, our app cannot do the certificate bypass, this is not safe action.
