### ISSUE TITLE
Autostart is broken in beta 2.0.106

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#47]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=42915934

**Comment by ameshkov** [comment]
Logs: YLA-498-44997
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=43018499

**Comment by Revertron** [comment]
Investigation shows that we can not start protection in autoproxy mode when user has no network connection for some time after boot.

**Comment by ameshkov** [comment]
But how autoproxy depends on active network connection?

**Comment by Revertron** [comment]
This is my first task for today.

**Comment by Revertron** [comment]
Finally, I've found a bug, this was my fault. Fixed.
