### ISSUE TITLE
Purposeful GPS/location tracking

### ISSUE THREAD

**Issue by metsuke0** [AdguardTeam/AdguardForAndroid#4703]
### Issue Details

I am looking for a trustworthy, secure solution to track my phone location, plot my route on a map, and store the history for later personal consumption.

I am currently using Nextcloud to host phone tracking data for my family and me. It not only allows us to be safe and check where are currently, but we can also look back over a vacation can remember where we have been or the route we took a previous time.
I am looking to move away from self-hosting over time, and so I am seeking cloud-based alternatives.

### Proposed solution

I already have the AdGuard app installed on my phone and everyone in my family, and I would much rather a company that I trust supply such functionality than the run-of-the-mill data sellers.

I realize this may be way outside the scope of the current AdGuard app though I don't know where else I would ask for this. And it may not be a good idea to meld this functionality with the current implementation, but I wanted to express my willingness to pay money to a company (like AdGuard) for such a product.

**Comment by Versty** [comment]
@metsuke0 Hi! 

This feature request is out of scope for our applications for sure. Our goal is to protect the privacy of the user, so we do not collect or store any sensitive data, such as geo location. And we don't have any plans to store that type of data in the future.
