### ISSUE TITLE
Whenever the VPN is active, most network request fail

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdguardForAndroid#4704]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0.788

### Environment

```markdown
- OS:Android 14
- Device:Pixel 7 Pro
- Firmware: 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

1.Upgrade to Android 14 beta
2.Enable local VPN in AdGuard app
3.Check any application

### Expected Behavior

The internet works, applications work.

### Actual Behavior

`most network request fail and no app seem to be able to access the internet`

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

A customer reported this case in ZD #759197

**Comment by ihurin** [comment]
`The issue happened while I was in Audible at 8:34`
[adguard_logs_4.0.788_1805_083535.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11513748/adguard_logs_4.0.788_1805_083535.zip)
Logs provided within this attachment.

**Comment by ihurin** [comment]
Logs provided within this attachment. The issue is with `Audible at 8:34`.
[adguard_logs_4.0.788_1805_083535.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11513759/adguard_logs_4.0.788_1805_083535.zip)

**Comment by maxikuzmin** [comment]
@ihurin I don't have this problem repeated. Let's see what's in the logs.

**Comment by maxikuzmin** [comment]
@ihurin it would also be good idea to check with the user if this is repeated in the latest update

**Comment by maxikuzmin** [comment]
@ihurin problem fixed with the latest version. Closing the issue
