### ISSUE TITLE
Adguard 4 nightly frequently restarts protection

### ISSUE THREAD

**Issue by meow-gh** [AdguardTeam/AdguardForAndroid#4707]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4 nightly 105

### Environment

```markdown
- OS:android 13 
- Device: s23 ultra 
- Firmware: latest stable over the last 2 month. Currently S918BXXS1AWD1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Block Flash, Turn off Advertising ID, Hide your IP address, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. See the adguard log 
2. Search for restart
3. A lot of it is seemingly without a reason and one after another without filter update or network change

### Expected Behavior

Protection is restarted only when filters update

### Actual Behavior

Check the restart logs.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I have agv and ag in socks mode configured

I have always on vpn without block connections without vpn on

Watchdog timer for ag is 60s I think

**Comment by loca-lhost** [comment]
I have been battling this ever since the first nightly it's less frequent now but it happens. Even today I have submitted logs

**Comment by ScathachSkadi** [comment]
This was happening for a long time. I am on S23U too.

**Comment by larena1** [comment]
Yeah it's restarting way more often starting a few months back. Even when using apps, protection will randomly restart with no network change or anything causing the app to fail. It was much better in AdGuard 3 and also 4 until a few months ago.

**Comment by Versty** [comment]
@jslawler @meow-gh  Hi!
Does the issue persists on the 4.0 release version? 
If so, please collect and send the debug logs to `devteam@adguard.com`, mention the `4707` number in the subject and the time of unexpected restarts.

**Comment by larena1** [comment]
I think it's fine now unless you removed the toast that notifies on protection restart.

**Comment by Versty** [comment]
@jslawler Logs from the latest nightly would be useful as well.

**Comment by L31FY** [comment]
I am not on nightly and do not use a proxy or any of those settings. It is simply crashing and restarting at random which introduces ads. I am on release version 4 that just came out. This happens every couple of minutes sometimes and I'm not getting a filter update that often surely.

**Comment by Eugene-Savenko** [comment]
More logs in 770719 (CRM ID). Setting watchdog to 120 didn't seem to help.

**Comment by 0xrxL** [comment]
@Versty Any update about this?

**Comment by Versty** [comment]
@0xrxL We are working on a solution. Thank you for your the patience.

**Comment by Versty** [comment]
@meow-gh 

> When ag restarts connection adguard fails open ( ie I can access internet without ag and agv)
If I turn always on vpn in android settings with block traffic without vpn on dns fails to resolve .

This behaviour is expected and completely normal. AdGuard filters traffic through a vpn-tunnel, so when the protection is being restarted, the vpn-tunnel does not work and the traffic goes without the tunnel. 
When the `Always on vpn` option is enabled, the Android system blocks any traffic flows without a tunnel.

**Comment by Versty** [comment]
@L31FY @meow-gh Do frequent restarts persist on the same device but on a different network?

**Comment by sssh7710** [comment]
Mine is Galaxy a33 Android 13, but the same problem occurs

**Comment by alexx7311** [comment]
770964 ticket(ZD) has the logs where AdGuard protection restarts for a 1-2 minutes.

**Comment by Coolhabit** [comment]
@meow-gh Hello!

The frequent restarts are fixed, changes will be published in today's nightly.

**Comment by 0xrxL** [comment]
New nightly is out! Anyone already tested it (with and without screen off) to understand if crashes are effectively fixed?

**Comment by jordanswrld94** [comment]
ive had one restart within past couple hours. i wouldnt say its completely fixed.

**Comment by ScathachSkadi** [comment]
I had one restart, and I don't know if it's a coincidence but it restarted when checking for adguard nightly updates. When I pressed the notification it was updating the filters in the background, too.

**Comment by L31FY** [comment]
I believe checking for updates is intended to trigger a restart, at least
it used to.

**Comment by ScathachSkadi** [comment]
@L31FY I didn't check updates myself. I got a notification that adguard nightly had an update, the local vpn immediately crashed, and when I pressed the notification it was updating the filters by itself. Yes, it is supposed to do that but not in the background.

**Comment by Versty** [comment]
@ScathachSkadi @L31FY This behavior is intentional, the protection should restart each time you check for updates.

**Comment by ScathachSkadi** [comment]
I didn't check updates myself this time. It crashed first and when I pressed the notification it was updating itself. And yes I am aware that updates restart the protection. This is what I was trying to say. It is quite stable I think haven't had any problems other than that.

**Comment by 0xrxL** [comment]
> I didn't check updates myself this time. It crashed first and when I pressed the notification it was updating itself. And yes I am aware that updates restart the protection. This is what I was trying to say. It is quite stable I think haven't had any problems other than that.

I've installed it 2 days ago, and can say it demonstrated to be really stable (at least until now).

No crash...neither with screen off.
