### ISSUE TITLE
Missing strings for localization

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#4709]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.0 Nightly 106

### Environment

```markdown
- OS: Android 8.1.0
- Device: Samsung
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Download latest nightly build and go to main screen.

### Expected Behavior

Add the strings so we can localize the strings.

### Actual Behavior

We can't localize these strings to our language. These are missing strings:

- Your data may be exposed
- data saved
- total blocked
- give us a moment
- Surf safely - we've got your back

### Screenshots

<details><summary>Screenshot 1:</summary>

![Bug](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/0a236fec-b800-4518-ad1c-6d2a583e4a45)
</details>

<details><summary>Screenshot 2:</summary>

![Bug1](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/537ca16b-8ef6-43d9-818b-65da5f522630)
</details>

<details><summary>Screenshot 3:</summary>

![Bug2](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/56f795a1-8358-447c-b682-c20a7b9e5c9f)
</details>

**Comment by Versty** [comment]
@gork7777 Hi! 
Thank you for noticing, this strings will be available for translation very soon.
