### ISSUE TITLE
The same custom filter can be added twice 

### ISSUE THREAD

**Issue by WinCHM** [AdguardTeam/AdguardForAndroid#4711]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11

### Environment

```markdown
- OS:Android 10
- Device:Huawei
- Firmware:Y6p
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Один и тот же фильтр можно установить и будут оба отображаться

### Actual Behavior

Дважды не должен отображаться

### Screenshots

![Screenshot_20230521_211603](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/b7c71ef1-4a3e-4083-b90c-32da655d2e29)

**Comment by Versty** [comment]
@WinCHM Добрый день! 
На данный момент это нормальное поведение приложения. Мы предоставляем возможность добавить столько одинаковых фильтров, сколько вам хочется.

**Comment by WinCHM** [comment]
@Versty 

> @WinCHM Добрый день! На данный момент это нормальное поведение приложения. Мы предоставляем возможность добавить столько одинаковых фильтров, сколько вам хочется.

А в чем смысл добавления одного и того же фильтра несколько раз?
