### ISSUE TITLE
CPU foreground/background is not counted on Android 9 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4721]
### Version
AdGuard for Android 4.0 nightly 106 

### Environment
Android 9, MCE16

### Steps to reproduce 
1. Install and launch AdGuard 
2. Enable the protection and surf some websites 
3. Go to Statistics tab -> Battery usage 

### Expected behaviour 
The values of the counters `CPU foreground` and `CPU background` are not equal to zero

### Actual behaviour
The counters `CPU foreground` and `CPU background` are 0 min 0 sec

<p align="left">
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/107266340/2bee5be8-892b-49ee-b09d-f14b88cef69a" width="300" height="550">
</p>

**Comment by Versty** [comment]
It actually starts to count, but after an hour or so after installation.

**Comment by artemiv4nov** [comment]
Well, it really can be like that and it's expected behavior: to calculate CPU time, we use API methods given by Android OS. So, if values from methods are incorrect, we just do not calculate the CPU time.
