### ISSUE TITLE
User made DNS filters not applied to firefox (release)

### ISSUE THREAD

**Issue by Atryx10** [AdguardTeam/AdguardForAndroid#4726]
I tried blocking all .zip and .mov domains so that I could guarantee never visiting sites under those TLDs, however, the (safe site) setup.zip was still allowed through despite this.
These are the filter forms I've tried using to block these domains (using tld instead of zip and mov to avoid repeating code):
```
/*.tld/
||*.tld^
||tld^$all
```
the latter two works on uBlock Origin, which is what I'm currently using to prevent bricking my stuff.
The firefox app I'm using is the release build version, or stable, whatever it's the app simply called FireFox.
Please fix this asap.

**Comment by maxikuzmin** [comment]
@Atryx10 thanks for the long wait! What version of AdGuard are you using? Is this still recurring on the latest version of AdGuard 4.0?

**Comment by Atryx10** [comment]
I was using 3.6.11, am now using 4.0, it is still happening. If I disable my uBlock extension on firefox, and I try to go to the .zip site I am not stopped by the Adguard apk at all, in any way. Just get brought straight to the site even though by all means it should be impossible :/

**Comment by maxikuzmin** [comment]
@Atryx10 the rules will block sites with .tld, based on your example. 
I tried adding your rules, replacing tld with zip, and there is no access to the site. 
Try replacing tld with zip
||*.zip^
||*.mov^

**Comment by Atryx10** [comment]
I am already using
||zip^$all
||mov^$all
Tried using what you told me to try. Was still redirected to the blog that the url links to.
I am using a Samsung Galaxy A52s, on firefox I'm using the Privacy Badger, Adnauseam, uBlock, Decentraleyes, and ClearURLs extensions.

**Comment by maxikuzmin** [comment]
@Atryx10 try disabling all extensions and only enable AdGuard, then clear cookies in Firefox and reopen setup.zip tab. Probably one of the extensions is conflicting. This happens when many rules are applied

**Comment by Atryx10** [comment]
Sadly, there's no way to delete cookies in the firefox app from what I can tell.
And, just disabling all the add-ons doesn't allow for it to work :/

**Comment by maxikuzmin** [comment]
@Atryx10 you can choose before clearing a cookie what to delete and what not to delete.
You can also download another Firefox, Playstore has many other versions nightly or beta. Just install there all the extensions you have and repeat the problem. I think that in "clean" Firefox the problem should not be there.
Or you could just try turning off all your extensions and repeat the problem without removing cookies, I think this should also show if any extensions are conflicting with each other

**Comment by Atryx10** [comment]
I do not get that choice option on firefox for my phone.
Anyways, deleted all cookies, disabled all the adblock related addons, restarted my browser, and I am still able to go to setup.zip

**Comment by maxikuzmin** [comment]
@Atryx10 thanks for waiting! 
If you want to block access to .zip, try the rules
||*.zip^
||*.mov^
I tried this, and it works for me, the rule works

**Comment by Atryx10** [comment]
Yeah, now it finally worked. Thank you for the help! 👍 
:D
