### ISSUE TITLE
Please bring back Minimize for Assistant notification icon in 4.0

### ISSUE THREAD

**Issue by Malechai** [AdguardTeam/AdguardForAndroid#4731]
### Issue Details

Recently installed the 4.0 beta and noticed that the Assistant notification cannot be set to minimized like it can in 3.x version.

The minimize feature is great because it leaves the assistant in the notfication pulldown but the notification icon isn't displayed constantly.  I realize I could disable this notification but then that takes away the ease of access of the Assistant.   Being able to minimize is the ideal solution to having Assistant available when needed but not having an icon constantly present.

I've attached a screenshot of the setting I'm referring to that has disappeared in 4.0
![Screenshot 2023-05-26 093959](https://github.com/AdguardTeam/AdguardForAndroid/assets/32441136/c1037b9a-5afa-4eb8-991d-e63705b5ec57)

### Proposed solution

Please add back the ability to Minimize the 4.0 assistant notification icon.

**Comment by Malechai** [comment]
Sorry I forgot to fill in the Alternative solution section.  I couldn't find one other than uninstalling 4.0 and returning to the latest 3.x version.

**Comment by DerpDicler** [comment]
I didn't have this issue with the first few betas but it started today for me after updating to RC1.

**Comment by Versty** [comment]
@Malechai @DerpDicler Hi there! This behaviour is intended.
Starting from version 4.0, the app uses the notification settings provided by the system, and we don't plan to revert the changes in the near future. 
However, we will add more options for easy access to the Assistant. Could be a tile, a shortcut or a widget.
