### ISSUE TITLE
won't block ads on spotify/youtube

### ISSUE THREAD

**Issue by singhh9596** [AdguardTeam/AdguardForAndroid#4736]
I'm being annoyed by the in apps ads in spotify, youtube. What's the point of buying subscription if it can't be use to block ads in my most used apps. It ruins all the listening/watching experience. How come adguard's extension is able to block ads on desktop but app can't.
Adguard v4.0 beta 2

**Comment by Versty** [comment]
@singhh9596 Please read the detailed explanation in #4827
