### ISSUE TITLE
"Filter compatible apps" does not work if the "Filter all apps" option was used before 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4742]
### Version
AdGuard for Android 4.0 nightly 110  

### Environment
Android 13, SCG09

### Steps to reproduce 
1. Launch AdGuard 
2. Open the Settings tab -> Filtering -> Apps -> Filtered apps/HTTPS-filtered apps 
3. Click the `Filter in all` option in the context menu 
4. Tap the `Filter all apps` button, then `Filter anyway`, all applications in the list are now filtered  
5. Click the `Filter in all` again -> `Filter compatible apps`

### Expected behaviour 
Only compatible apps is filtered 

### Actual behaviour
All apps is filtered 

### Additional info 

The same is applicable to App management screen (Route all through AdGuard option)

**Comment by Coolhabit** [comment]
Hello, @Versty !
This behavior does the same thing as "reset to default". Moreover, the user can select additional applications that he wants to filter, and the "filter compatible applications" function means that actions will be performed on compatible applications. If "reset to default" do not presence on some of the mentioned screens, it wil be added in the nearest future.
