### ISSUE TITLE
cloudflare+warp alongside with adguard

### ISSUE THREAD

**Issue by EslamGamalEssa** [AdguardTeam/AdguardForAndroid#4743]
hello
first of all i don't know if this the right place to post my issue
i have (rooted) samsung A52S 5G and have adguard routing mode set to automatic proxy and it working well by itself alone but when ever i turn on cloud flare (1.1.1.1) app its working but no ads filter working anymore is there something i miss or settings should be applied ?

Notes : first four screens show that adguard works fine with no problems in auto proxy route mode and it filter all ads and the other three screens show that (1.1.1.1) works as vpn connection without closing adguard (both working) but no ads filters

(working ads filters)

1: 
![1](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/837fdf4f-7abd-40de-a007-32cc3b216ec8)

2:
![2](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/c25cec0e-bc6b-4bad-a7f4-ad582fdae00e)

3:
![3](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/92ef3f75-1391-47a0-88b7-3de1015e9d59)

4:
![4](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/d8e6e3ce-d131-4ea0-b6c7-663fcf77ff0c)

(NOT working ads filters)

5:
![5](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/8c5e214a-9af8-47c7-8bbf-6ac69420f568)

6:
![6](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/4ee82fb2-5f4b-494f-a766-104a1550fea7)

7:
![7](https://github.com/AdguardTeam/AdguardForAndroid/assets/22161118/2feaeb87-84f5-4745-b4e8-a853635118fb)

what am i doing wrong ?
thanks in advance
regards

**Comment by Versty** [comment]
@EslamGamalEssa Hi!
Here is two things you can do to resolve this issue:  
1. Add AdGuard to the list of the excluded apps in WARP application. 
*Settings -> Advanced -> Connection options -> Manage excluded apps*

2. Disable DNS protection module in AdGuard. Keep `ad blocking`,` annoyance blocking` and `tracking protection` modules enabled for the best results. 

This issue may also be related to #4637 and will probably be gone after the fix.
