### ISSUE TITLE
DNS timeout problem

### ISSUE THREAD

**Issue by singhh9596** [AdguardTeam/AdguardForAndroid#4746]
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 beta 2

### Environment

```markdown
- OS: custom rom based on A13
- Device: Redmi K20 Pro
- Firmware:
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Enable adguard dns within the app.
2. Launch amazon.in, imdb and many more app/sites.
3. Blank or broken page with no images and messed up fonts will load.
![Screenshot_20230530-185043_Amazon](https://github.com/AdguardTeam/AdguardForAndroid/assets/31469965/e62f9f4c-084e-4533-b35e-e68bcc7b3533)

### Expected Behavior

![Screenshot_20230530-185214_Amazon](https://github.com/AdguardTeam/AdguardForAndroid/assets/31469965/4451724b-652c-4456-91e3-2d50b699992f)

Progress bar keeps on blinking for a while and end up throwing no connection error.

![Screenshot_20230530-185433_DuckDuckGo](https://github.com/AdguardTeam/AdguardForAndroid/assets/31469965/e0ecd2f6-6de4-4343-ab79-b2aa087b26e4)

![Screenshot_20230530-185452_DuckDuckGo](https://github.com/AdguardTeam/AdguardForAndroid/assets/31469965/181e12c3-953a-4bd7-8b43-85d69c3d0453)

### Actual Behavior

Pages must load properly as intended, with all action buttons working.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by singhh9596** [comment]
![Screenshot_20230530-185718_DuckDuckGo](https://github.com/AdguardTeam/AdguardForAndroid/assets/31469965/fb9a2f10-5dd1-4b77-bab0-0662e027af54)
![Uploading Screenshot_20230530-185718_DuckDuckGo.png…]()

**Comment by Versty** [comment]
@singhh9596 Hi! 
If you switch to a different dns or disable dns protection, would it work properly then?

**Comment by singhh9596** [comment]
> @singhh9596 Hi! If you switch to a different dns or disable dns protection, would it work properly then?

Yes it does work after switching to some other dns.

**Comment by Versty** [comment]
@singhh9596 Some dns servers may not be available in certain countries due to government restrictions or other temporary problems. Please use the dns that fits you best. Ads and trackers will be blocked anyway if you use any dns server you like along with AdGuard DNS filter.
