### ISSUE TITLE
clearing statistics doesnt clear apps and companies sections only resets their counters to zero

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4748]
### Details 

If protection is enabled, clearing statistics resets counters for companies and applications to zero, instead of removing them from the lists. 
If protection is disabled, companies and applications are removed from the lists correctly.  

### Steps to reproduce 
1. Enable protection, ad blocking and dns modules 
2. Surf some websites 
3. Go to the Statistics tab (some data for apps and companies sections should be collected at this point) 
4. Tap the context menu -> Clear statistics 

### Expected result 
The text "No stats yet - keep using AdGuard to view them" is displayed in both `Apps` and `Companies` sections 

###  Actual result
Applications and companies are still in the lists, but their counters are zeroed 

<details><summary>Video file</summary>
https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/f62c7e7f-17b7-48c8-a265-29dd61a65230
</details>

**Comment by Versty** [comment]
@jordanswrld94 Thanks for reporting! 
We have reproduced this issue on our side.
