### ISSUE TITLE
"Protection" notification disappears when minimized in RC1

### ISSUE THREAD

**Issue by DerpDicler** [AdguardTeam/AdguardForAndroid#4754]
I always silence the protection notification and set it to minimize so that is out of sight from my notifications until I swipe down. Suddenly on RC1 the notification is completely absent. Switching it back to default makes it visible again but it disappears immediately when set back to silent/minimize. This only started happening with today's update. This is happening on both devices I tested. Both are on Android 13 with the latest security update.

**Comment by Malechai** [comment]
I hope this gets fixed.  4.0 went live and this issue still exists.   Right now I just disabled the protection notification but thats not ideal.

**Comment by maxikuzmin** [comment]
@DerpDicler @Malechai thanks for the long wait. I switched the notification to "Silent" mode, and in the system settings I turned on the switch for "Minimize", but the notification does not go away. After restarting the application and restarting the phone, the notification is still visible.
Could you make a video of the screen with all the steps and repeat the disappearing update?

**Comment by maxikuzmin** [comment]
@DerpDicler @Malechai any news?

**Comment by Malechai** [comment]
Hi maxi, sorry I kept meaning to come back to this! thank you for the reminder.

Thanks for your time for looking into this.  I actually discovered the same thing you did, where changing the notification to silent mode first allowed me to select minimize.  Its working as it did prior to version 4.   All good for me!

Take care

**Comment by maxikuzmin** [comment]
@Malechai glad to hear that! 
Take care too :)
