### ISSUE TITLE
Adguard for Android 4.0 wrong and missed translations for Polish language

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardForAndroid#4755]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 RC1

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy A52s 5G SM-A528B/DS
- Firmware: TPI A.220624.014.A528BXXU3EWE1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Online Malicious URL Blocklist, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, KAD - Anti-Scam, NoCoin Filter List

### Issue Details

Steps to reproduce:
1. Launch Adguard for Android.
2. Navigate to Settings
3. See missing translations.

### Expected Behavior

Valid Polish language translations.

### Actual Behavior

Missing and wrong Polish language translations

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230602_080845_Settings_copy](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/1f0545db-f1a8-4041-9537-1cb91544f82f)
</details>

<details><summary>Screenshot 2:</summary>

![Screenshot_20230602_080853_Settings_copy](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/f9ab961a-4208-4c22-87ae-fffad1de44bf)
</details>

<details><summary>Screenshot 3:</summary>

![Screenshot_20230602_080916_AdGuard_copy](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/8f2800c8-862c-4318-8fdc-2a701098f3b7)
</details>

<details><summary>Screenshot 4:</summary>

![Screenshot_20230602_080955_AdGuard_copy](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/3b6a2f32-ffa1-4263-bce9-a7e0842b4003)
</details>

<details><summary>Screenshot 5:</summary>

![Screenshot_20230602_081013_AdGuard_copy](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/6a81ca6d-a3a2-42a9-9e93-887b88f0eea7)
</details>

### Additional Information

ENG - POL
Firewall - `Zapora`
Here is used word `Zasłona` - should be `Zapora`

Missed `General` translation. Should be `Ogólne`

**Comment by Versty** [comment]
@FadeMind Hi! 
The translation for `Firewall` is already fixed, the translation for `General` will be improved soon.
