### ISSUE TITLE
The requests stats text overlaps the graph on the statistics screen on 4.6" screen

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4757]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 n110

### Environment

```markdown
- OS: Android 9
- Device: Sony XZ1 compact (display 4.6")
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

.

### Actual Behavior

The requests stats text overlaps the graph on the statistics screen on 4.6" screen

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/8361299/6e0ae472-dc3f-4836-8a68-002b0e4e28b0)

</details>

**Comment by artemiv4nov** [comment]
Well, we will improve the statistics functionality after a few versions, please follow the updates, I'll close this task as a duplicate.
