### ISSUE TITLE
Provide in-app instructions for enabling HTTPS filtering for Google Family Link devices

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForAndroid#4759]
### Issue Details

When trying to enable HTTPS filtering on a device managed by Google Family Link, the certificate can not be installed by default as the install certificate setting is greyed out in Settings.

### Proposed solution

Provide in-app instructions for devices that use [Google Family Link](https://families.google/familylink/) or other services that use the [device administrator api](https://developer.android.com/guide/topics/admin/device-admin).

### Alternative solution

Provide the instructions above in the kb.

**Comment by Versty** [comment]
@jslawler Thank you for the suggestion. 
The instruction will be added to the knowledge base. https://github.com/AdguardTeam/KnowledgeBase/issues/159
