### ISSUE TITLE
pages do not load at all or load slowly 

### ISSUE THREAD

**Issue by nouvellevague0** [AdguardTeam/AdguardForAndroid#4767]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.910

### Environment

```markdown
- OS: miui 14.0.5
- Device: xiaomi pad 5
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard French filter, AdGuard Spanish/Portuguese filter, Greek AdBlock Filter

### Issue Details

Steps to reproduce:
1. open chrome to visit any website or open an app (especially reddit) to load content
2. website is not loading (error try checking your connection)
3. if Adguard is disabled, everything loads.

### Actual Behavior

Adguard blocks access to lots of webpages (ex. trapeza.iep.edu.gr) or the sites load very slowly or the apps refuse to load content. this happens more and more often, to the point where I had to disable Adguard completely. 
Generally, even if websites eventually load, Chrome becomes noticeably slower. Same with apps, especially Reddit. Disabling Adguard makes everything much faster on my tablet. 
Also, when I reopen Chrome after a while (which forces websites to reload the page automatically), I get the annoying message " error, connection timed out". 
This last problem was already present on Adguard 3.6.11. The other issues I described are specific to Adguard 4. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@nouvellevague0 Hi! 
High loading time and connection time out can be caused by DNS server, try switching to another one from the list. 

If you disable the DNS protection module, does the issue persist?

**Comment by nouvellevague0** [comment]
if I disable the DNS, the speed improves indeed, but the thing is that the stable app gives much faster load speeds with DNS enabled than the beta or alpha version with the same settings.

**Comment by nouvellevague0** [comment]
thanks, I will send the logs soon. I hope that the issue is clear, i do not say that the app is not working, but that it is very slow to the point that it makes surfing on the web a bit painful. I get "connection was interrupted" or pages that load indefinitely every twenty minutes or so. It would be ideal if you could block as many ads as you do now (it's impressive, really, no ads at all!) while providing faster load times.

**Comment by Versty** [comment]
@nouvellevague0 How is it going? 

You could also try a few different DNS servers from the list, the problem seems to be server-specific, so that might help.

**Comment by nouvellevague0** [comment]
yes I can confirm that this is the issue. I disabled DNS completely and the app is much faster, the connection is not interrupted. I have public Adguard DNS configured in the global phone settings, but the DNS is disabled in the app itself. The problem is gone with this combo.

**Comment by Versty** [comment]
@nouvellevague0 Got it!
