### ISSUE TITLE
Query-only rule with $domain does not trigger document blocking

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardForAndroid#4771]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11

### Environment

```markdown
- OS: Android 13
- Device: Pixel 6a
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Japanese filter

### Issue Details

Steps to reproduce:
1. Add `/?AC=*&IC=$document,domain=fun|online|site,badfilter` and `?AC=*&IC=$document,domain=fun|online|site`
2. Visit [dangerous and nsfw site] `http://ygcrausscj.site/?AC=dam02&IC=567&ID=9Jgwyx4b9Rr77XJ6aHN9` (probably short life)
3. See document blocking is not triggered. `?AC=*&IC=$document` works though.

### Expected Behavior

`?AC=*&IC=$document,domain=fun|online|site` should block the site.

### Actual Behavior

Not

### Additional Information

Found in https://github.com/AdguardTeam/AdguardFilters/issues/152604 and no such problem on extension

**Comment by Versty** [comment]
@Yuki2718 Hi! 
Please update to the latest release version. 
Does the issue persist on AdGuard For Android 4.0?

**Comment by Yuki2718** [comment]
> Does the issue persist on AdGuard For Android 4.0?

Confirmed it's correctly blocked on 4.0.
