### ISSUE TITLE
[Android TV] Fixed portrait, no landscape on TV since v4.0 

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#4773]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Beta

### Environment

```markdown
Android TV 11
```

### Root access

- [ ] Yes, I have it.

### Issue Details

The initial setup splashscreen upgrading to v4.0 is shown sidewise, and then the UI itself shows up as portrait but it should be landscape mode. It should be tablet mode, but it recognizes the TV as a phone (?). This also makes navigation more difficult.

### Expected Behavior

UI should be in landscape mode.

### Actual Behavior

UI is in portrait mode.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I have this same problem on an Android TV, as well as a Mibox 3 and another Android box.

**Comment by oroboros** [comment]
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/1668665/527a3bb5-f1c2-4109-a7b2-d46e74585c2c)

**Comment by Versty** [comment]
@oroboros Hi there! 
The official support for Android TV is not yet implemented. 
The behavior that you mentioned above will be improved as part of feature #3597.

**Comment by oroboros** [comment]
@Versty Thanks for this! It is a little annoying that this issue had been fixed in v3 and is now showing up in v4 again. The bug is small, but has a huge impact on Android TV users, I would suggest it being fast tracked and leaving other Android TV improvements as per https://github.com/AdguardTeam/AdguardForAndroid/issues/3597 until later.
