### ISSUE TITLE
No cosmetic filtering on https://cleantechnica.com/

### ISSUE THREAD

**Issue by arturstat** [AdguardTeam/AdguardForAndroid#4774]
On https://cleantechnica.com/ ads are blocked, but ad empty spaces are still shown.

**Comment by Versty** [comment]
@arturstat Hi! 

Please report the incorrect blocking via in-app option located in the *Settings tab -> Support -> Report incorrect blocking*.

**Comment by arturstat** [comment]
@Versty Hi!
I did as requested.
The issue is reported here:
https://github.com/AdguardTeam/AdguardFilters/issues/155135
