### ISSUE TITLE
ONECTA - Daikin app can't login

### ISSUE THREAD

**Issue by arturstat** [AdguardTeam/AdguardForAndroid#4775]
### Issue Details

When logging in to ONECTA -Daikin app, the user is redirected to a webpage using the default browser, first to cdc.daikin.eu, then to id.daikin.eu; however the webpage freezes, and user can't login.

For more information on ONECTA- Daikin app, see:
https://www.daikin.eu/en_us/product-group/control-systems/onecta.html

### Proposed solution

Adding cdc.daikin.eu to the HTTPS Allowlist fixes the issue. The domain in question seems to be used only for login purposes. So I don't see any inconvenient in adding it to the HTTPS Allowlist. I suggest adding cdc.daikin.eu to the HTTPS Allowlist by default in a future version of AdGuard for android, so that users don't face this issue. Many thanks.

**Comment by Versty** [comment]
@arturstat Thank you for the suggestion! 

Could you check if `HTTPS filtering' is disabled for the ONECTA application in the App management section and cdc.daikin.eu is NOT added o the HTTPS Allowlist, does the issue related to the login persist?

**Comment by arturstat** [comment]
HTTPS filtering is disabled for the ONECTA app. If I disable cdc.daikin.eu on the HTTPS Allowlist I cant login.
Anyway, HTTPS filtering is not needed on daikin.eu domain and subdomains, as there are no ads or trackers, so I just added daikin.eu instead of cdc.daikin.eu to the HTTPS Allowlist. But only cdc.daikin.eu is required!
Here, disabling HTTPS filtering on the ONECTA app does not fix the issue, because login is done through the web browser, in this case Google Chrome.
