### ISSUE TITLE
Instagram network strange statistics

### ISSUE THREAD

**Issue by XAlboX** [AdguardTeam/AdguardForAndroid#4776]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.910

### Environment

```markdown
- OS:Android 13
- Device:POCO F3
- Firmware:TQ2A.230505.002
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList Italy, EasyPrivacy, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies, EasyList Cookie List

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API

### Issue Details

Steps to reproduce:
1. Install Instagram
2. Enable Adguard VPN filtering
3. Wait some time

### Expected Behavior

The app should show real data usage(?)
I don't know how much data Instagram used.

### Actual Behavior

The app shows Instagram used 20+GB but I haven't even opened Instagram since I enabled Adguard.

### Screenshots

<details><summary>Screenshot 1 & 2:</summary>

![Screenshot_20230608-172707_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/80044603/de86b61c-79b5-43ca-8ac3-08622f5b89f1)

![Screenshot_20230608-172712_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/80044603/9161cb27-fd40-47a4-9ff0-ca6873d6040f)

</details>

**Comment by VladisLoveZh** [comment]
@XAlboX 
hi, 
please clarify one thing: 

Did you installed AdGuard 4.0 over 3.6 or was it a clean installation of 4.0 AdGuard?

**Comment by XAlboX** [comment]
Clean

**Comment by XAlboX** [comment]
I didn't understand point 2.

Also
Do I have to click "Export logs and system info" to save the logs and send them to that email?
