### ISSUE TITLE
Impossible so open and hear vocal messages in "Orange Téléphone" app

### ISSUE THREAD

**Issue by Azertixe** [AdguardTeam/AdguardForAndroid#4777]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.1.1

### Environment

```markdown
- OS: Android 12
- Device: Fairphone 4
- Firmware: Fairphone OS
- Last Android security patch : 5 may 2023
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter

### Issue Details

Steps to reproduce:
1. Open Orange Téléphone
2. Touch a new voice message

### Expected Behavior

Impossible to open and listen the voice messages

### Actual Behavior

Message error (see capture).
URL to : https://orangetelephone.zendesk.com/hc/fr/articles/5952302833820

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/52431679/3b6d1052-0cfc-4445-b7ea-9728f9bbb567)

</details>

### Additional Information

I can open, download and hear voice messages with Adguard disabled.
Once voice message downloaded, i can hear it with Adguard enabled.
I am in contact with Orange by mail.
I tried to add orange.fr in domain exceptions.
My Orange Téléphone app is up to date.

**Comment by Versty** [comment]
@Azertixe Hi! 
Please try to update the app to the latest version.
Does the issue persist on AdGuard for Android 4.0?

**Comment by Azertixe** [comment]
Hello. Yes it does. I finally added the app on exepcions...

**Comment by Versty** [comment]
@Azertixe Thanks for your help, it sounds like you found the solution. 
We will exclude the Orange Phone app from filtering by the default.
