### ISSUE TITLE
AdGuard notifications cause the screen to turn on in sleep mode on a locked screen

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4778]
### Issue Details

AdGuard notifications cause the screen to turn on in sleep mode. It has been noticed that if you turn on the protection and leave the phone in sleep mode, when you see notifications from AdGuard, the screen of the device turns on.

### Proposed solution

Ensure that AdGuard notifications appear so that the notifications do not trigger the screen from sleep mode, on the locked screen

### Alternative solution

In the Android system settings, turn off notifications on the locked screen

**Comment by mbutov** [comment]
Same thing after updating to AdGuard 4.0, Android 10.
Every few seconds the screen is turned on and displayng AdGuard notification.

**Comment by bdf74** [comment]
Yes, the same is happening to me on my Google Pixel 4a device, with Android 13. The phone goes into sleep mode (screen goes black), then after a few seconds the notification appears (the one with the stats of blocked ads / saved data), then it goes to sleep mode again... in a continuous loop. This didn't happen in the previous release.
I disabled that notification from the app preferences, but I'd really like to leave it there, as it's a very quick and easy way to open AdGuard.

**Comment by WagsFTW** [comment]
Same thing here. Opened support ticket, was linked to this post. And @maxikuzmin can you add the bug tag instead of the feature request?

**Comment by Versty** [comment]
@WagsFTW The type of this issue has been changed to bug.

**Comment by ihurin** [comment]
+1 CRM 781361

**Comment by jawz101** [comment]
just installed AdGuard yesterday & noticed this.  This is annoying.

**Comment by WagsFTW** [comment]
@Versty Do you have any updates on this? Still an issue, and it's on every version of Adguard including the nightly updates, stable updates etc. Very annoying persistent bug

**Comment by enakr** [comment]
+1 CRM 815086

**Comment by WagsFTW** [comment]
Really wish someone would assign this to get fixed 😞
![Screenshot_20230924-131856](https://github.com/AdguardTeam/AdguardForAndroid/assets/20032780/bfea0564-95b2-412a-b9bf-9b8a8297913d)

**Comment by Matt023** [comment]
A temporary fix for me is making it a silent notification.
![Screenshot_20230924-203638](https://github.com/AdguardTeam/AdguardForAndroid/assets/1770951/59ad81fb-8187-4ff2-8c09-a96ab8102dc9)

**Comment by WagsFTW** [comment]
> A temporary fix for me is making it a silent notification. ![Screenshot_20230924-203638](https://user-images.githubusercontent.com/1770951/270184935-59ad81fb-8187-4ff2-8c09-a96ab8102dc9.png)

Thank you very much for the tip! I'm having trouble locating the particular screen/setting your picture depicts. This is what I'm seeing...
![Screenshot_20230924-152059](https://github.com/AdguardTeam/AdguardForAndroid/assets/20032780/93ae401c-2f9d-4d2f-9ad9-f49b9e7f7dcf)

**Comment by WagsFTW** [comment]
> A temporary fix for me is making it a silent notification. ![Screenshot_20230924-203638](https://user-images.githubusercontent.com/1770951/270184935-59ad81fb-8187-4ff2-8c09-a96ab8102dc9.png)

Thank you very much! I just found and turned this off as well. I never thought about this! Good work around.

**Comment by Matt023** [comment]
> > A temporary fix for me is making it a silent notification. ![Screenshot_20230924-203638](https://user-images.githubusercontent.com/1770951/270184935-59ad81fb-8187-4ff2-8c09-a96ab8102dc9.png)
> 
> Thank you very much! I just found and turned this off as well. I never thought about this! Good work around.

Long press the notification of adguard in your notification panel. (it's not in settings)

**Comment by WagsFTW** [comment]
> > > A temporary fix for me is making it a silent notification. ![Screenshot_20230924-203638](https://user-images.githubusercontent.com/1770951/270184935-59ad81fb-8187-4ff2-8c09-a96ab8102dc9.png)
> > 
> > 
> > Thank you very much! I just found and turned this off as well. I never thought about this! Good work around.
> 
> Long press the notification of adguard in your notification panel. (it's not in settings)

Perfect, thank you!
