### ISSUE TITLE
Improve the sorting order for User rules 

### ISSUE THREAD

**Issue by sconim** [AdguardTeam/AdguardForAndroid#4779]
### Issue Details

In v.3.xx the user's blocking rules were automatically sorted in descending order (newer to older). From v.4.xx onwards, they are automatically sorted in ascending (older to newer) order. 

### Proposed solution

Add sorting and filtering capability. Over time I've accumulated over 200 user's rules and the new automatic ascending sorting is very inconvenient. Every time I add a rule, instead of being able to see it on top of the list, I need to scroll all the way down to the bottom of the list. Adding both manual sorting and filtering would also allow users to organize the list any way they want.

### Alternative solution

Added by @Versty:  
Return sorting in descending order (newer to older) for more convenient usage.

**Comment by Pocarai** [comment]
This is also my Request too

**Comment by kanoche** [comment]
How do you manage to view your user rules? For me, in Adguard 4 gui there is no possibility to access or view this rules. only way to create is with "block" in filter log, here i also can see my old migrated rules still applied.

**Comment by sconim** [comment]
> How do you manage to view your user rules? For me, in Adguard 4 gui there is no possibility to access or view this rules. only way to create is with "block" in filter log, here i also can see my old migrated rules still applied.

You can still block/unblock anything you want and add/remove filters:
- Ad Blocking: Protection > Ad blocking > User Rules.
- DNS: Protection > DNS Protection > DNS Filters > User Rules

Additionally, you can enable/disable any one of the built-in filters.

**Comment by kanoche** [comment]
thank you for your qick answer.
on both of my devices -OnePlus 7t and Lenovo Tab P11- with Adguard Android 4.0  there is _NO_ such setting. Nothing, nowhere. Scrolled up and down, clicked everywhere, absolute absence of this function/ setting
just uninstalled, reinstalled Version 3.6.11. 
By the way, main reason for upgrading was the promised IPv6 support for automatic proxy, but on my OP7t the manual proxy mode doesn't work at all in this "upgrade" Version, not possible to enable it. Still waiting for support

**Comment by sconim** [comment]
![Screenshot_20230625_102238_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/10010866/8bf145aa-2e6b-441d-96d0-5b484b500a36)
![Screenshot_20230625_102254_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/10010866/e6025d6d-b760-4da8-9289-015e80279c1c)
![Screenshot_20230625_102328_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/10010866/b616c45a-5b62-4d99-af04-75f8011fb2cc)

As for the proxy, why do you want to set up a manual proxy rather than an automatic connection? Will you only connect to one single (pre-set) Wi-Fi network? Regardless, in trying to set up a proxy, have you changed your low-level settings, especially the "fallback upstream" to none? This is NOT the only setting that will need to be changed for you to be able to switch over from Local VPN to a Proxy - but this is where also I'm stuck, still searching for a solution to connection instability when using an Automatic Proxy. 

No doubt, AdGuard 4.0 still has quirks and problems, but it does A WHOLE LOT MORE than 3.6. What users don't seem to want to accept is that if you want to benefit from all those extra features YOU NEED to put in the extra effort. So, read, research, understand, apply, try new things, curse and start over. No amount of complaining will ever get anyone in a better place. 

My take: AdGuard v.4.0 IS DEFINITELY better than v.3.6 but it still needs some work around the edges. Downgrading is not a solution since it's not going to allow you to keep up with the fixes, progress and new features. Keep on pushing and I almost guarantee that at some point you'll be happy for doing so.

**Comment by kanoche** [comment]
Hello, thank you for yor help, meanwhile I had an answer from support, stating more or les the same than you. My answer  in short: 
on my devices all the entries in "Protection" were not expandable, so i had no chance to find this settings

This is  my answer to Adguard Suppor (german):

Wo die Benutzerregeln zu finden sein sollten habe ich mittlerweile herausgefunden, nur ließen sich die ganzen Einträge ( auch Firewall usw) im "Schutz" - Tab nicht ausklappen, lediglich die An/ Aus - Schaltflächen waren bedienbar, daher für mich nicht zu finden.  Gleiches Verhalten auf zwei Geräten, allerdings bei beiden als Update von Installationen mit exakt gleichen importierten Einstellungen. Habe Adguard 4 runtergeschmissen und wieder Version 3.6.11 installiert, die funktioniert - außer halt  IPv6 mit automatischem Proxy, aber der funktioniert in der neuen Version auf meinem OnePlus 7t mal gleich komplett nicht. Da warte ich noch auf Antwort vom Support, vorher ist Version 4 für mich keine Sekunde Ärger mehr wert.
