### ISSUE TITLE
[Feature request] Highlight newly installed apps in firewall list

### ISSUE THREAD

**Issue by hertill** [AdguardTeam/AdguardForAndroid#478]
I often want to disable internet access for a newly installed app before launching it for the first time. Because of the lack of alphabetical sorting in the firewall view it can be a hassle to find the app in that list. 

It would be helpful to highlight and/or place all apps installed since the last launch of Adguard at the top of the firewall list.

**Comment by TPS** [comment]
@hertill Probably #384 in 1½ versions will do this for you. ☺

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/3379
