### ISSUE TITLE
cant switch to custom protection in tracking protection category

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#4782]
when i switch to custom in tracking protection category and back out the expected behvior is for vpn to restart, it doesnt, it also switches back to the previous tracking protection selection that i had before selecting custom when i go back in to check what option is selcted

**Comment by jordanswrld94** [comment]
https://www.udrop.com/8jnu/Screen_Recording_20230611_133213_AdGuard.mp4

since its not letting me upload video rn here is a link to it

**Comment by Versty** [comment]
@jordanswrld94 This behavior is expected if the tracking protection settings have not been changed after switching to the Custom level.
