### ISSUE TITLE
Incorrect number of devices on the license screen 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4787]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.0

### Environment

```markdown
- OS:Android 10
- Device:Huawei
- Firmware:Y6p
```

### Root access

- [ ] Yes, I have it.

### Issue Details

1) Как же так получается, что личный кабинет показывает вот это

![1](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/0b95757c-f636-45d8-b22f-205275c5fde6)

А программа показывает вот это

![Screenshot_20230615_081856_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/9488979f-94a6-4835-82e3-a8219f346e9c)

2) Так же полностью отображается ключ лицензии, на **AdGuard 3.6.11** такого не было

### Actual Behavior

1) Что бы отображалось корректно
2) Скрыть лицензионный ключ

**Comment by Versty** [comment]
@WinCHM Добрый день! 
Проблема действительно возникает в некоторых исключительных случаях, мы ее исследуем.
Напишите нам на почту `devteam@adguard.com` ваш емейл, на который была куплена лицензия, а в теме письма укажите номер `4787`.

**Comment by WinCHM** [comment]
@Versty 

> @WinCHM Добрый день! Проблема действительно возникает в некоторых исключительных случаях, мы ее исследуем. Напишите нам на почту `devteam@adguard.com` ваш емейл, на который была куплена лицензия, а в теме письма укажите номер `4787`.

Проверьте мои Логи из той темы - https://github.com/AdguardTeam/AdguardForAndroid/issues/4788 , там прописан нужный Вам емейл, его использовал для обратной связи.

**Comment by Versty** [comment]
@WinCHM Мы видим, что на данный момент у вас четыре различных ключа привязаны к одному емейлу, но ни один из этих ключей не рассчитан на 4 устройства. 

Было ли такое, то вы для уже существующей лицензии увеличивали лимит устройств через личный кабинет? 

Если в личном кабинете у вас отображается, что к одному ключу привязано более трех устройств, пожалуйста, отправьте нам снимок экрана личного кабинета на емейл `devteam@adguard.com`. В заголовке емейла укажите номер `4787`.

**Comment by WinCHM** [comment]
@Versty 

> @WinCHM Мы видим, что на данный момент у вас четыре различных ключа привязаны к одному емейлу, но ни один из этих ключей не рассчитан на 4 устройства.

Как быть тогда вот с этим?

![2023-06-20_18-04-13](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/71038b72-4c3a-4f6d-b745-c4dfe02b2a17)

Я же не сам выдумал про 4 устройства, а опирался на данные которые показывает личный кабинет.

> Было ли такое, то вы для уже существующей лицензии увеличивали лимит устройств через личный кабинет?

Нет не было такого.

**Comment by Versty** [comment]
@WinCHM Чтобы понять в каком месте возникает ошибка и разобраться в проблеме, нам нужно понять какой именно из четырех ваших ключей используется на скриншоте. 

Пожалуйста, пришлите ключ, который привязан к лицензии, нам на почту `devteam@adguard.com`, в заголовке письма упомяните `4787` или напишите ключ нам в саппорт и укажите здесь номер обращения.

**Comment by WinCHM** [comment]
@Versty 

> @WinCHM Чтобы понять в каком месте возникает ошибка и разобраться в проблеме, нам нужно понять какой именно из четырех ваших ключей используется на скриншоте.

Мы получили ваше обращение. Его номер – 770857.

В отправленном сообщении указал первую букву ключа который используется

**Comment by ihurin** [comment]
@Versty @WinCHM это премиальная лицензия на 2+2 устройства, отображение правильное.
