### ISSUE TITLE
Frequent protection restarts and crashes in the local VPN mode 

### ISSUE THREAD

**Issue by WinCHM** [AdguardTeam/AdguardForAndroid#4788]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.0

### Environment

```markdown
- OS:Android 10
- Device:Huawei
- Firmware:Y6p
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Программа самостоятельно закрывается, либо же перезапускается с изменением настроек ( которые не производил )

Отправил логи: Мы получили ваше обращение. Его номер – 768469.

### Actual Behavior

Достали уже эти постоянные перезапуске программы

### Screenshots

![Screenshot_20230615_091719_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/3b20dcca-7edd-47f7-9e15-92f82cc23d7a)
![Screenshot_20230615_084444_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/019342cb-c3fb-43ef-80c1-52ba76489bfc)

**Comment by Versty** [comment]
@WinCHM Добрый день, мы посмотрели файлы из вашего обращения. 
Похоже, что проблема дублирует уже ранее созданную другим пользователем. Поэтому давайте продолжим общение в теме https://github.com/AdguardTeam/AdguardForAndroid/issues/4456.

Хотелось бы получить более подробные файлы логов с вашего устройства, чтобы разобраться в проблеме. 

1. Убедитесь, что у вас включены опции `Отправлять отчеты о сбоях` и `Отправлять данные об использовании`. Если  необходимо - включите

2.  Включите подробное логирование: 
*Настройки -> Основные -> Расширенные -> Уровень логирования -> Подробный*

3. Включите защиту и подождите пока проблема возникнет, запомните точное время, когда она произошла

4. Соберите логи: 
*Настройки -> Основные -> Расширенные -> Экспортировать логи и информацию о системе* 

5. Отправьте сохраненный файл на почту devteam@adguard.com:
      - в теме письма укажите номер `4456` 
      - в письме укажите время воспроизведения проблемы

**Comment by jordanswrld94** [comment]
if you want to check progress go here: https://github.com/AdguardTeam/AdguardForAndroid/issues/4524
