### ISSUE TITLE
Improve the click area for back arrow buttons

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4789]
### Version
AdGuard For Android 4.0 

### Details 

The click area for the back arrows is currently too small to be comfortable. 
<p align="left">
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/107266340/4de4ddb0-66f3-4e87-b1fc-56addc0050ce" width="300" height="650">
</p>

### Solution
Enlarge the click area for back arrow buttons.

**Comment by Nzzyme** [comment]
Yes, the back button misses to register the tap many times. The button needs to be bigger
