### ISSUE TITLE
[Feature Request] Dark material theme

### ISSUE THREAD

**Issue by JonnyRedHed** [AdguardTeam/AdguardForAndroid#479]
Offer a dark material theme (as in dark grey with colour highlighting, medium/light grey font colour's).  

And also maybe also a Black AMOLED theme.

**Comment by ameshkov** [comment]
Hi! We are working on a new design for v3.0 and by default it will be dark.

**Comment by TPS** [comment]
@JonnyRedHed Officially keeping track via #104, so react & subscribe there to know when this lands.

**Comment by JonnyRedHed** [comment]
When are we seeing the Dark material themes for Android and the Windows software?  2018 now.

**Comment by ameshkov** [comment]
I am sorry that it takes so long to implement. The design was prepared a long time ago, but it's been delayed all the time in favour of adding new features/bugfixes.

**Comment by JonnyRedHed** [comment]
I wish MS would actual get their act together and finish then release a couple of proper fully dark themes for window 10.  I'd start to use it then.  Maybe then the rest of the software world would follow as a quicker pace.
