### ISSUE TITLE
After updating the filters, the updated filters are shown in one line

### ISSUE THREAD

**Issue by WinCHM** [AdguardTeam/AdguardForAndroid#4790]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.0

### Environment

```markdown
- OS:Android 10
- Device:Huawei
- Firmware:Y6p
```

### Root access

- [ ] Yes, I have it.

### Issue Details

В версии AdGuard 3.6.11 каждый обновленный фильтр начинался с новой строчки, теперь же в AdGuard 4.0 они идут в подряд, что не очень удобно просматривать какие обновились. Просто все сливается в единое целое.

### Actual Behavior

Раздельные строчки

### Screenshots

![Screenshot_20230615_105439_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/110057379/a24e5ccb-3432-47b0-b199-7e342a50d5ab)

**Comment by maxikuzmin** [comment]
@WinCHM спасибо за обратную связь! Мы исправим это в следующем обновлении
