### ISSUE TITLE
Recommended low-level settings for Automatic Proxy as default routing mode (root) 

### ISSUE THREAD

**Issue by sconim** [AdguardTeam/AdguardForAndroid#4791]
### Issue Details

Routing mode Local VPN.

### Proposed solution

Please specify the recommend low-level settings when default routing mode is changed to Automatic Proxy (root). 

[This page](https://adguard.com/kb/adguard-for-android/solving-problems/low-level-settings/) merely reviews all options without providing specific choices for this scenario. Most confusing to me are the choices than need to be made when fallback upstreams are disabled. What IPv4 / IPv6 addresses should I fill in under Blocking Rules for hosts rules?

### Alternative solution

N/A

**Comment by sconim** [comment]
Moved to issues

**Comment by Versty** [comment]
@sconim Hi! 
Treat the default values as recommended.
The low-level settings are implemented for low-key adjustments, different values can be used depending on the use case, so we believe that there is no silver bullet.
The page you mentioned gives a quick overview of the low-level settings to help you find the desired settings faster.
