### ISSUE TITLE
apps on Android 9 can not detect internet at all unless excluded from AdGuard

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdguardForAndroid#4795]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0

### Environment

```markdown
- OS: Android 9
- Device: Huawei
- Firmware: CLT-L04
```

### Root access

- [ ] Yes, I have it.

### Issue Details

There are some apps that simply do not work, as they do not detect an internet connection, unless completely excluded (AdGuard protection DISABLED) from AdGuard.

However this only seems to occurs on **Android 9**.

One such app is the Shell (the gas station) app (https://play.google.com/store/apps/details?id=com.shell.sitibv.motorist.america)
After you install and launch the app, it will give a "no internet connection" error. The homepage will load fine, but you can not do anything that requires you to log in. For example, can not pay with the app at the gas station. Can not add any payment method in the app. Can not even load personal profile in the app. It will say "NO internet connection"

Another app is Notesnook  (https://github.com/streetwriters/notesnook)
This app will not sync to their servers, with an error in logs "Internet not reachable".
But can log into personal profile just fine, the app can also check update just fine, just can't sync. (https://github.com/streetwriters/notesnook/issues/2729)

In order for these apps to function properly, I have to go into "Apps Management", and disable "AdGuard protection".
Disabling "Ad blocking" will not work, AdGuard has to be disabled completely for these.

However, on Android 11 with identical setup, (AdGuard v3.6.11 (54) + latest Notesnook), everything works fine without having to disable AdGuard Protection.

Is this a bug with AdGuard or the Android 9 system?

### Expected Behavior

apps should work

### Actual Behavior

apps do not work.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by thecodrr** [comment]
This might have something to do with AdGuard blocking WebSocket connections because Notesnook's sync uses WebSocket. Everything else (Login, updates etc.) are just simple HTTP request which work just fine.

**Comment by maxikuzmin** [comment]
@muchqs on 10 android this problem is not repeated. Later we will be able to check on android 9

**Comment by maxikuzmin** [comment]
@thecodrr AdGuard can block WebSocket connections, but it doesn't do so by default

**Comment by maxikuzmin** [comment]
@muchqs indeed, only repeats on android 9. We will look into it

**Comment by Peter-maximus** [comment]
any update?

**Comment by Proxwian** [comment]
After some research, found out that not only AdGuard VPN connection can make issues with these apps (Notesnook and Shell) on Android 9. Looks like developers of this apps not rightly implemented the way of detecting active internet connection when connected via VPN. So I opened a new ticket for the latest version of Notesnook app [right here](https://github.com/streetwriters/notesnook/issues/3757).

As a temporary fix, you can do that:
1. Go to Apps Management tab
2. Search for app and open it settings
3. Turn off toggle "Route traffic through AdGuard"

Please note that this option will stop blocking any ads in app.
