### ISSUE TITLE
AdGuard 1x1 Widget 

### ISSUE THREAD

**Issue by Tim3tripp3r** [AdguardTeam/AdguardForAndroid#4799]
### Issue Details

Please bring back the old 1x1 widget that was a simple on/off toggle. Pretty pretty please. 

### Proposed solution

As per above. 

### Alternative solution

None.

**Comment by Versty** [comment]
@Tim3tripp3r Hi! 
The widgets will be reworked in the future versions for sure. 

Let's see if this request receives enough votes from other users.

**Comment by ChandraSaiKarthik** [comment]
Much needed

**Comment by fejjj** [comment]
I need this feature

**Comment by MarosNik** [comment]
Please, bring back the old 1x1 widget that was a simple on/off toggle. 
Maros

**Comment by Versty** [comment]
@Tim3tripp3r Will be added as a part of https://github.com/AdguardTeam/AdguardForAndroid/issues/5050.

**Comment by Tim3tripp3r** [comment]
On what planet does a 3x1 widget equal a 1x1 widget?
Why has this been closed?
It has nothing to do with the issues being discussed in #5050. There was nothing mentioned in that thread that they would be making a 1x1 widget. Seriously wonder about the bot's ability to manage threads but that is a bigger separate issue.

**Comment by Versty** [comment]
@Tim3tripp3r 1x1 widget will be added along with other widget improvements.
