### ISSUE TITLE
Improve statistics detalization

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#48]
Make statistics show not '1Gb', '2Gb' etc., but more deatiled data.

*UPD:*
Something like: 1.52Gb

**Comment by ameshkov** [comment]
@vbagirov detailed like what?

**Comment by TPS** [comment]
Maybe show (like AB+ browser extensions) what ads blocked most, which filterlists have been most useful,  &/or #26.…  Might even help with problems like #50!

**Comment by ameshkov** [comment]
Yeah, we'd like to extend firewall per-app statistics to show top used domains and such.

But still I don't understand what exactly @vbagirov meant

**Comment by vbagirov** [comment]
Oops, my bad. I meant that some users would like to see less rough numbers. Like '1 143 Mb' instead of '1Gb'.

**Comment by ameshkov** [comment]
Ok, i've updated the issue text

**Comment by Revertron** [comment]
Done!
