### ISSUE TITLE
FairEmail Cannot Obtain Access Token For Gmail

### ISSUE THREAD

**Issue by christantoan** [AdguardTeam/AdguardForAndroid#4802]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 11
- Device: OnePlus
- Firmware: Oxygen OS 11.0.9.1.GM21BA
```

### Root access

- [X] Yes, I have it.

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Disable WebRTC, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Have a Gmail address added in FairEmail
2. Start AdGuard protection

### Expected Behavior

FairEmail continues to sync normally.

### Actual Behavior

After a few hours a synchronization error occurs (see details in screenshot)

### Screenshots

<details><summary>Screenshot 1:</summary>

![iMarkup_20230617_181152](https://github.com/AdguardTeam/AdguardForAndroid/assets/7300310/1baf91d6-d386-4845-8546-20356939d8e3)

</details>

### Additional Information

I have tried disabling tracking protection, HTTPS filtering for FairEmail and system apps category. It seems to work at first (i.e. FairEmail can get a new token) but after a few hours the error comes back.

In previous version, I can just disable HTTPS filtering for FairEmail and it works fine.

**Comment by christantoan** [comment]
Looks like DNS issue. I changed server from Quad9 to AdGuard No Filter and it has been working fine since.

**Comment by christantoan** [comment]
> Looks like DNS issue. I changed server from Quad9 to AdGuard No Filter and it has been working fine since.
> 
> Will reopen if there's more problem.

And right after I commented that, the problem came back.

**Comment by maxikuzmin** [comment]
@christantoan I will try to repeat your problem. It's going to take some time

**Comment by maxikuzmin** [comment]
@christantoan I have tried this on three devices with AdGuard DNS, AdGuard DNS Non-filtering, Quad9. I have not had this problem repeated.

It would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 4802 number in the subject
specify the exact time when the issue occurred

**Comment by christantoan** [comment]
Sorry for the lack of updates. Disabling HTTPS filtering for Google Play services and Google Services Framework seems to do the trick. I can even re-enable HTTPS filtering for FairEmail though I still enable it for System apps.

**Comment by maxikuzmin** [comment]
@christantoan great news! If the problem happens again, you can reopen the issue
