### ISSUE TITLE
AdGuard for Android v4.1 Nightly 5 - Opera web browser - hide rules for DIV with specific class do not work - ##.ad-container , ##.amp-ad-wrapper, etc

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#4803]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1 Nightly 5

### Environment

```markdown
- OS: Google Android 13
- Device: Google Pixel 7 Pro
- Firmware: stock , Security Patch 05 May 2023
- Opera web browser - 75.4.3978.72990 - both "Ad Blocking" and "Tracker Blocking" are disabled
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, EasyList, EasyList Hebrew, EasyPrivacy, Fanboy's Annoyances, Peter Lowe's Blocklist, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, Fanboy's Anti-Facebook List, I don't care about cookies

### What Stealth Mode options do you have enabled?

Self-destruction of third-party cookies, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

**Steps to reproduce:**
1. From the Google Play, install the Opera web browser - "Opera browser with AI" - https://play.google.com/store/apps/details?id=com.opera.browser
2. In the Opera web browser settings, disable both "Ad Blocking" and "Tracker Blocking"

**Issue # 1:**
1. In the Opera web browser, open https://www.businessinsider.com/how-to-fix-whatsapp-imessage-mistakes-2023-6
2. The DIV blocks with the class "ad-container" are NOT hidden (still appear), although there is a user-defined generic hide rule:
`##.ad-container`
See the attached screenshots = Screenshot_1.png + Screenshot_2.png

**Issue # 2:**
1. In the Opera web browser, open https://www.businessinsider.com/how-to-fix-whatsapp-imessage-mistakes-2023-6
2. The DIV blocks with the class "amp-ad-wrapper" are NOT hidden (still appear), although there is a user-defined generic hide rule:
`##.amp-ad-wrapper`

**Important Note** - This issue does NOT occur when I open the same web sites in the Google Chrome web browser - the DIV blocks with these classes do NOT appear

### Expected Behavior

The configured hide rules should work for the Opera web browser in the same way as they work for the Chrome browser on my smartphone
The same rule works correctly in the AdGuard extension for the Opera browser on my Desktop computer

### Actual Behavior

In the Opera web browser, the DIV blocks with the specified classes are NOT hidden (still appear), although there is a user-defined generic hide rule:

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/a544f4d7-684c-4540-9ba0-21926710f812)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/8867242d-173a-4380-9d63-10d9683ba8f4)

</details>

### Additional Information

I collected the Debug Logs while browsing in Opera and in Chrome
Let me how to upload them privately and securely

**Comment by maxikuzmin** [comment]
@SergeiShir could you: quit all apps -> clear "Recent activity" -> repeat steps -> take screenshots of Recent activity. 
It would be nice to see what happens in Recent activity.
You can email screenshots to devteam@adguard.com or attach them here

**Comment by SergeiShir** [comment]
I followed your instructions
1) closed all apps

2) made sure the Recent App list is empty

3) opened Opera

4) opened this page

[https://www.businessinsider.com/how-to-fix-whatsapp-imessage-mistakes-2023-6](https://www.businessinsider.com/how-to-fix-whatsapp-imessage-mistakes-2023-6) 

**Note - the list of Recent Apps shows only the Opera browser**

5) now, the behavior is a little bit different - 
the problematic blocks are not visible - 
the web page is blanks in those places - 
but there is a huge white space - see the attached screenshots "Opera_1" - "Opera_4" -
I took screenshot of the page while scrolling down

A)
![Opera_1](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/5cf8c7ef-f4d7-42fa-a2d6-58b26cd42623)

B)
![Opera_2](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/c9ff7c31-48b0-45b4-8f56-349e19e82f02)

C)
![Opera_3](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/a7114581-1db6-40e7-b422-e2785ab5e4b6)

D)
![Opera_4](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/c21fbcc0-b618-45e7-b367-e28e042dc2d4)

6) in Chrome, these blocks do NOT appear at all - the attachedal screenshot "Chrome"
![Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/17823400/e765bda6-da5f-4bba-9978-0243786104c8)

**Comment by maxikuzmin** [comment]
@SergeiShir 
>repeat steps -> take screenshots of Recent activity.
It would be nice to see what happens in Recent activity.

Unfortunately, I don't see screenshots in the mail. Did you send them?
This is to see which elements in your Recent activity are blocked.

I don't have this problem repeated, but I have the standard protection blocks and filters enabled. Maybe you have a conflict with some filters. Try to disable all protection blocks (Ad blocking, Tracking protection, Annoyance blocking, DNS protection) and repeat the problem steps -> there should be no problem with disabled protection blocks, then just enable protection blocks one by one and then we can find out what is the problem.

Please send screenshots of Recent activity, and record debug logs and send them along with the screenshots. Your logs will also help clarify the situation. Do you know how to write debug logs?

**Comment by SergeiShir** [comment]
Hi

I did not understand that "Recent Activity" referred to AdGuard Logs.

Please see the attached logs with the "Debug" level

I opened the same URL 3 times
You can see the screenshots in my previous comment

1) Opera

DIV blocks with the mentioned classes are NOT hidden completely

2) Opera

DIV blocks with the mentioned classes are NOT hidden completely

3) Chrome

DIV blocks with the mentioned classes ARE hidden completely

[Issue_4803_adguard_logs_4.1.58_03Jy2023_19h34m20s.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11938930/Issue_4803_adguard_logs_4.1.58_03Jy2023_19h34m20s.zip)

**Comment by maxikuzmin** [comment]
@SergeiShir I was talking about the screenshots of your "Recent activity" :)

In "Recent activity" it will be clearer what is happening with the requests.
Try to close all applications, clear "Recent activity", then disable all protection blocks (ad blocking, tracking protection, annoyance blocking, DNS protection) and repeat the steps on the problem -> there should be no problem with disabled protection blocks, then just enable protection blocks one by one and then we can figure out what the problem is.

Send screenshots from "Recent activity" by attaching them here or to devteam@adguard.com

**Comment by SergeiShir** [comment]
Hi

(1)
The Recent Activity does NOT show anything helpful.
See the attached ZIP with screenshots of the Recent Activity (spliced manually):
[Recent_Activity.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11984374/Recent_Activity.zip)

(2)
I am sorry, but your request is very strange.

(A)
With the same exact configuration, the blocking works perfectly in the Google Chrome browser.
So, the issue is between AdGuard app and the Opera browser - not with the enabled filters.

(B)
There are at least 20 filters loaded in my configuration + other enabled settings...
On a smartphone, it is super inconvenient and time-wasteful to disable them all and then enable one-by-one.

(C)
I am 100% sure AdGuard Support has an app simulator on a normal desktop computer (this is how Android developers can test their apps).
It will be much easier for AdGuard Support to make all the required tests in this app simulator.

Please use the provided configuration from my AdGuard to load it on your test Android environment.

**Comment by maxikuzmin** [comment]
@SergeiShir sorry if I confused you with the Recent activity question, basically the first thing we do is evaluate what requests are going through the Recent activity to see if items are being blocked. Thank you.
I originally tested on my device with https filtering enabled for Opera, but I missed the fact that https filtering is disabled by default for Opera.
Please try enabling https filtering for Opera in Apps management and check again, this should help

**Comment by SergeiShir** [comment]
The issue was resolved after enabling HTTPS Inspection for the Opera app
Thanks

**Comment by maxikuzmin** [comment]
@SergeiShir glad to hear that!
