### ISSUE TITLE
Tracking filters are disabled by default in free version 4

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#4804]
### Issue Details

Worried about privacy

### Proposed solution

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy must be back

### Alternative solution

AdBlock has them

**Comment by maxikuzmin** [comment]
@jbionic2016 I understand your frustration, but these features are only available for full versions. We have very frequent promotions, I'm sure you will be able to buy a subscription at a very favorable price in the future if necessary

**Comment by jbionic2016** [comment]
What is the point of having Adguard if it doesn't protect from online tracking? Does Adguard now officially sell our data to advert companies?

**Comment by maxikuzmin** [comment]
@jbionic2016 AdGuard has many other features besides online tracking :) 
We don't sell data to advertising companies

**Comment by superlex** [comment]
Hi,
I agree with [jbionic2016](https://github.com/jbionic2016).
I'm very disappointed that privacy filters are disabled in the free version.
I understand that devs want sell AdGuard license, but privacy is a key feature of using AdGuard and other adblocks, maybe even more important than removing ads.
I hope AG devs will change their decision.
They may lock less important features, e.g. user filter list, or annoyances, but not privacy.

**Comment by jbionic2016** [comment]
The word is that Adguard shares the data with the state. Nobody knows if it's true and how far government intervention in our privacy is gonna get
