### ISSUE TITLE
Incorrect Sorting for entries in the "Recent Activity"

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#4805]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 12
- Device: Poco M5
- Firmware: MIUI 13.0.12
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Enable AG
2. Navigate to the 'Recent Activity' page
3. Occasionally, you will see the timestamp on the entries are not sorted based on time (most recent on top).

### Expected Behavior

The entries on the "Recent Activity" page should be sorted based on time. That is, the most recent entries should be on the top.

### Actual Behavior

At times, some entries on the "Recent Activity" page include timestamps that are older (see screenshot).

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/6959116/f0b3c1cc-a5a0-47e4-8338-a82138b45314)

</details>

**Comment by maxikuzmin** [comment]
@Nzzyme thanks for your observation! The sorting is done by the initiation time of the event, so the end time may not be the same. This is not a bug
