### ISSUE TITLE
Choosing actions when trying to make a long tap (hold) by a shortcut (Toggle protection, AdGuard Assistant, Check for updates)

### ISSUE THREAD

**Issue by Insight16** [AdguardTeam/AdguardForAndroid#4806]
### Issue Details

Добрый день! Хотелось бы видеть в 4-й версии AdGuard возможность обновить фильтра или остановить/запустить защиту при удержании иконки (ярлыка) в меню приложений или на главном экране (если ярлык там присутствует), по аналогии, как это было реализовано, например, в последней актуальной 3-й версии Вашего приложения. Было очень удобно, почему этого нет в 4-й версии, не совсем понятно. Так же не хватает возможности отключить журнал фильтрации (помощник) в самом приложении. Опять же, такая фишка была в предыдущей 3-й версии... как минимум был выбор, так сказать

**Comment by maxikuzmin** [comment]
@Insight16 спасибо за ваш отзыв! В планах есть возврат шорткатов, а также их доработка. Мы обязательно вернем их в следующих обновлениях

**Comment by maxikuzmin** [comment]
дубликат https://github.com/AdguardTeam/AdguardForAndroid/issues/4780
