### ISSUE TITLE
Samsung Pay process is starting in the background along with AdGuard launch 

### ISSUE THREAD

**Issue by Insight16** [AdguardTeam/AdguardForAndroid#4807]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.912

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy S22 (SM-S901B) / Samsung Galaxy Tab S8 (SM-X700)
```

### Issue Details

AdGuard - Основные настройки - Расширенные - Низкоуровневые настройки - Обнаруживать Samsung Pay (отключено)

### Expected Behavior

Если в низкоуровневых настройках приложения AdGuard отключена функция обнаружения Samsung Pay, то она не должна быть запущена как процесс. На 3-й версии именно так и работало

### Actual Behavior

Настройки телефона - Параметры разработчика - Работающие службы - AdGuard - SamsungPayService (запушен и работает, как служба, вместе с LocalVpnService и ProtectionStateForegroundService)

Получается, SamsungPayService запущен постоянно невзависимости от того, включена ли функция обнаружения Samsung Pay в низкоуровневых настройкам или нет. Стоит отметить, что приложения Samsung Pay на планшете и на телефоне у меня нет в принципе

**Comment by Versty** [comment]
@Insight16 Добрый день! 

Настройка `Обнаруживать Samsung Pay` отвечает за остановку защиты, когда приложение Samsung Pay используется, и повторный запуск защиты, когда приложение Samsung Pay было закрыто. 

SamsungPayService можно обнаружить по пути `Настройки телефона - Параметры разработчика - Работающие службы - AdGuard - SamsungPayService` потому что это один из сервисов AdGuard. Он действительно запускается вместе с приложением и отвечает за проверку наличия Samsung Pay на устройстве. И, если вы в дальнейшем установите Samsung Pay, то благодаря этому сервису, AdGuard будет знать об этом.

Сервис использует незначительное количество ресурсов. Поэтому наличие этого сервиса никак не отражается быстродействии устройства.

**Comment by Insight16** [comment]
@Versty добрый день! Спасибо за ответ. Только вот не совсем понятно, чему на 3-й версии этот процесс не давал о себе знать, т.е. не висел в фоне. По мне так логично, если в низкоуровневых настройках включить эту опцию (обнаружения), тогда должен включатся и сам процесс, но если же опция отключена, то и процессу нет смысла работать и обнаружевать Samsung Pay в фоне, соответственно. Ну да ладно)
