### ISSUE TITLE
Create Adguard widget according to Android guidelines

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#481]
What we've done in #203 with widget is just a temporary solution.
We'll use this icons for #123 

http://developer.android.com/intl/ru/guide/practices/ui_guidelines/widget_design.html

**Comment by TPS** [comment]
Just FYI, from yesterday's beta, the temporary widget [states are still swapped](https://github.com/AdguardTeam/AdguardForAndroid/issues/203#issuecomment-211604087).

**Comment by ameshkov** [comment]
Why, no, it is in proper state now. Widget shows you a possible action, not a current state.

**Comment by TPS** [comment]
That, I think, is a change from previous behavior (please confirm!) & is rather jarring.  Shouldn't the notification bar show the same as widget?

**Comment by ameshkov** [comment]
That indeed a change from the previous behavior:)

> Shouldn't the notification bar show the same as widget?

Notification bar is for showing current state.
Widget is for actions, a bit different purpose.

New widget will look different, but it will have the same states (like this "player" widget):
<img src="http://developer.android.com/images/widget_design/music_example_layouts.png" />

**Comment by TPS** [comment]
I think, though, a utility app, like AG, shouldn't pattern widget _states_ after a media app, like a music player.  The other utility apps I'm familiar with use current status for widgets, especially since many have >2 rest states.

**Comment by ameshkov** [comment]
Something like that widget?
<img width="199" alt="2016-04-22_1815" src="https://cloud.githubusercontent.com/assets/5947035/14746005/457703bc-08b6-11e6-8ba0-34b8f377f2de.png">

**Comment by TPS** [comment]
Precisely!

**Comment by ameshkov** [comment]
This widget looks good indeed, but only when you place several actions on it.

**Comment by TPS** [comment]
The widget has the benefit of being 1×1, which, trust me, is both rare & excellent, so 1 really well-done action is plenty & even laudable.

**Comment by TPS** [comment]
@AdguardTeam Before releasing later on, are y'all keeping these _states_ as-is (a change from previous release), or reverting to previous states (of course, keeping the Material icons)?  I don't quite know where we left this.…

**Comment by ameshkov** [comment]
@TPS not sure yet, our designer will make the decision:)

**Comment by Zageron** [comment]
Hello, just dropping in to add my support for the widget showing the current state of the blocker, or perhaps having two widgets which display in opposite states.

:)

**Comment by ameshkov** [comment]
I'll show new widget image as soon as designer comes up with something

**Comment by ameshkov** [comment]
@Revertron 
**1x1 widget:** return the old widget, just use the right guides for its size. Example: pushbullet 1x1 widget
**shortcut:** use the current widget icon for the shortcut. Shortcut either stops or starts AG protection.

**1x4 widget:** in v2.7: https://github.com/AdguardTeam/AdguardForAndroid/issues/576

**Comment by TPS** [comment]
> __1x1 widget:__ return the old widget

Why?  Do you mean previous _states_ only? Or use old icons, too?

**Comment by ameshkov** [comment]
> Why? Do you mean previous states only? Or use old icons, too?

The old 1x1 widget was just like pushbullet widget:
<img width="425" alt="2016-05-23_1727" src="https://cloud.githubusercontent.com/assets/5947035/15474061/b9b1f8e6-210b-11e6-8b76-b7e21bbc8b7c.png">

**Comment by Revertron** [comment]
Made a shortcut:
![adguard_shortcut](https://cloud.githubusercontent.com/assets/105154/15746155/fdc3ea74-28dd-11e6-987a-8782abab7960.png)

**Comment by ameshkov** [comment]
@Revertron tapping on a shortcut should also bring up a toast message.
Something like: starting (or stopping) Adguard protection

**Comment by Revertron** [comment]
I think that current widget and new shortcut are great, closing this issue.
