### ISSUE TITLE
Add Teila (EE) VoWifi ipv4 tunnel exclusion CIDR

### ISSUE THREAD

**Issue by ZonD80** [AdguardTeam/AdguardForAndroid#4815]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.-

### Environment

```markdown
- OS: Android 13
- Device: ASUS
- Firmware: Doesn't matter
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

No filters

### What Stealth Mode options do you have enabled?

Hide your search queries

### Issue Details

No WiFi Calling is working inside **Telia (Estonia) network**

### Expected Behavior

It should work

### Actual Behavior

Creating this issue for you to add default exclusions to local VPN tunnel. I've got these IPs that are responsible for VoWiFi:
195.50.247.166, 195.50.247.169, 195.50.247.182, 195.50.247.185

Converted to nearest CIDR rule: 195.50.247.166/27, added it to ipv4  tunnel exclusion list in advanced settings - **wifi calling now works**

Please add this to your official default filters.

**Comment by maxikuzmin** [comment]
@ZonD80 thanks for the information! We will fix this in the next updates
