### ISSUE TITLE
Improve the frequency for floating notifications of the "protection" category

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4818]
### Details 
Floating notifications of the "protection" category pop up too frequently when traffic is actively filtered. 
For example, when watching a Youtube video. 

### Possible solution 
Show the floating protection notification when the protection state is changed. 
This means that this notification will be displayed in 3 cases: 
- When the protection has been enabled
- When the protection has been disabled
- When the protection is restarting

### Alternative solution 
Lower the popups frequency

**Comment by artemiv4nov** [comment]
Well, we reworked protection notifications nearly, please follow for updates.
