### ISSUE TITLE
Connection error vine app

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#482]
same kinda error as in this issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/469

log: http://nopaste.linux-dev.org/?1079650

**Comment by jo2dan23** [comment]
im guessing this has to do with elliptic curves support that was just added by ameshkov. i just got this same error in two more apps

**Comment by ameshkov** [comment]
Does it stop vine from working?

**Comment by jo2dan23** [comment]
No. Just get those errors constantly filling the logs. Do you want the other two apps logs also?

**Comment by jo2dan23** [comment]
Wait. I am seeing these errors even with the app in HTTPS whitelist.

**Comment by ameshkov** [comment]
Have you restarted AG protection after adding the app to whitelist?

**Comment by ameshkov** [comment]
> No. Just get those errors constantly filling the logs. Do you want the other two apps logs also?

Such errors are ok, these are not errors in fact (i suppose we should log it as warnings instead). It's just sometimes an app may close connection without actually using it. Browsers do this more often.

So, the main question is: does HTTPS filtering somehow interfere with Vine app functionality. If it's not then we'd better keep it out of the whitelist.

**Comment by ameshkov** [comment]
The same question for tumblr app: #483

**Comment by jo2dan23** [comment]
Oh.. My bad. No they don't break the apps at all.
