### ISSUE TITLE
App language settings are not applied correctly on Android 8 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4821]
### Version
AdGuard for Android 4.0

### Environment
Android 8

### Steps to reproduce 
1. Launch AdGuard
2. Go to the Settings tab -> General -> App language 
3. Switch the language a couple of times  

### Expected behaviour 
Each time you switch languages, the entire application is displayed in the selected language. 

### Actual behaviour
Each time you switch the language, the entire application is displayed in the language that was previously selected.

**Comment by artemiv4nov** [comment]
Well, there are some Android bugs we can't avoid. The only one solution is not to use Android 8.
