### ISSUE TITLE
Not able to Use my Banking website on Android any most from Saturday Morning 

### ISSUE THREAD

**Issue by Vibhu2212** [AdguardTeam/AdguardForAndroid#4822]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Not very Sure , But it worked till Saturday morning   

### Environment

```markdown
- OS: 9, 11, 10 , 12 , Its all the versions 
- Device: Mostly samsung , But also google and all 
- Firmware:NA
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

No filters

### What Stealth Mode options do you have enabled?

Hide your search queries

### Issue Details

Steps to reproduce:
1. Install Ad guard , 
2. Go to Network and settings tap and put the dns as adguard dns 
3. Visit the site https://www.my.commbank.com.au/netbank/Logon/Logon.aspx . 
4. You get an error connection not secure 

The same is happening when i use the banking app as well on android device . Every thing work on my iOS or another device 
![error commbank App](https://github.com/AdguardTeam/AdguardForAndroid/assets/137667734/fa882bfe-427d-4ae1-b318-81b71c4aa088)

### Expected Behavior

I should be able to login just like i used before Saturday . On Both my CommBank App and also the website without any error 

### Actual Behavior

![error commbank App](https://github.com/AdguardTeam/AdguardForAndroid/assets/137667734/859e4e7e-6c0b-4356-a17c-d4b7bfaa53c3)
I got this error 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

This is impacting lot of my friends so please help to fix so that we can continue our banking . I have also seen NY times and lot of other websites being blocked including facebook , So might be you need to see what is the problem

**Comment by maxikuzmin** [comment]
@Vibhu2212 I don't have this problem repeatedly. Could you please specify what browser you are using? What device?
 It would also be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 4822 number in the subject
specify the exact time when the issue occurred

**Comment by Vibhu2212** [comment]
Hi @maxikuzmin this is not required now , one of my mates reached out via Telegram to adguard and they have white listed the url , so the issue is no longer happening now , I will reach out if the issue happens again
