### ISSUE TITLE
Remove Trailing Period character for all DNS entries

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#4824]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 12
- Firmware: MIUI 13
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, Adblock Warning Removal List

### Issue Details

Steps to reproduce:
1. Navigate to the "Recent Activity" page
2. For any DNS entry, you will observe a period character (.) at the end of the domain

### Expected Behavior

Please remove the period character at the end of each DNS domain.

### Actual Behavior

Steps to reproduce:
1. Navigate to the "Recent Activity" page
2. For any DNS entry, you will observe a period character (.) at the end of the domain

### Screenshots

https://i.ibb.co/CKpFKwN/Screenshot-20230626195729.jpg

**Comment by maxikuzmin** [comment]
@Nzzyme thanks for your observation! We'll refine that in the next updates

**Comment by Nzzyme** [comment]
I see that this is marked as 'Fixed', but we still see the trailing period character in DNS requests. Can you please reopen and provide an update on this?
