### ISSUE TITLE
Unable to open a request's details if a request contains `*.`

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4826]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.912

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi model=23049RAD8C
- Firmware: n/a
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Locate an `*.example.org` request in Recent activity.
2. Tap on it.

### Expected Behavior

You either see a request details, or some kind of explanation why it can't be displayed

### Actual Behavior

The screen flashes and returns to the Recent activity list. See video:

### Screenshots

<details><summary>Video 1:</summary>

![Monosnap screencast 2023-06-27 10-44-14](https://github.com/AdguardTeam/AdguardForAndroid/assets/15856304/06a120c1-641d-4350-8743-0d7bd412d958)

</details>

**Comment by artemiv4nov** [comment]
I think this is a little bug between unstable versions. Now it cannot be reproduced.
