### ISSUE TITLE
random "please wait while we start protection"

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdguardForAndroid#4829]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0

### Environment

```markdown
- OS: Android 9
- Device: Huawei P20 Pro
- Firmware: CLT-L04
```

### Root access

- [ ] Yes, I have it.

### Issue Details

AdGuard notification sometimes show "please wait while we restart protection" when I wake up device. Happens randomly and not always. All power savings for the app are turned off. Battery Optimization turned off. App is set to always run in background. Even Huawei's power saver app is uninstalled via adb completely. But app still randomly restarts protection. Did not happen with v3.6.11

### Actual Behavior

AdGuard app should always be on.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by piquark6046** [comment]
Sent an related AdGuard log file reported from my friend to AdGuard Slack.

**Comment by Versty** [comment]
@muchqs Hi!
The "Please wait while we restart protection" notification is implemented to inform you about the state of the protection. 
Restarts happen from time to time depending on the network and other settings, which explains the inconsistency of restarts. 

We have plans to reduce the frequency of restarts in future versions. You can follow the progress of the improvement in issue #4707.
