### ISSUE TITLE
App won't run automatically after device restart

### ISSUE THREAD

**Issue by sssh7710** [AdguardTeam/AdguardForAndroid#4832]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 The official version

### Environment

```markdown
- OS:android 13(one ui 5.1)
- Device: Galaxy a33
- Firmware: A336NKSU4CWE1/A336NOKR4CWE1/A336NKOU4CWE1
```

### Root access

- [ ] Yes, I have it.

### What Stealth Mode options do you have enabled?

Protect from DPI

### Issue Details

Steps to reproduce:
1. Rebooted for Google Play system update
2. Waiting for full boot after initial unlock after reboot

### Expected Behavior

Filtering is turned on and also visible in the notification window

### Actual Behavior

Sometimes the adgard isn't working (filtering only tries to activate when you enter the app)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

First, I share the app log
I went into the app and saved the log
[adguard_logs_4.0.912_2906_125740.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11901887/adguard_logs_4.0.912_2906_125740.zip)

**Comment by Versty** [comment]
@sssh7710 Hi! 
Have you set up your device according [to this](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/#android-11) guide?

**Comment by sssh7710** [comment]
> @sssh7710 Hi! 
> Have you set up your device according [to this](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/#android-11) guide? 

Battery optimization excluded and RAM cleanup excluded, and when rebooted, version 3 worked fine

**Comment by sssh7710** [comment]
If you leave the screen on after booting, the app will start normally

**Comment by sssh7710** [comment]
> @sssh7710 Does the problem persist after a standard reboot (not a system update)? 

Yeah, that kind of bug sometimes appears in version 4.1

**Comment by sssh7710** [comment]
> @sssh7710 If you wait a bit longer after rebooting, will it be the case? 

It's the same even if it's over 10 minutes

**Comment by Versty** [comment]
@sssh7710 So the problem is gone?

**Comment by Versty** [comment]
@sssh7710 Any updates?
