### ISSUE TITLE
On/Off button in the Control panel is missing (Adguard 4.0, EMUI 12)

### ISSUE THREAD

**Issue by volodievna** [AdguardTeam/AdguardForAndroid#4834]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS:
- Device: Huawei P30 Pro
- Firmware: VOG-L29 EMUI 12.0.0.149
```

### Root access

- [ ] Yes, I have it.

### Issue Details

there was an on/off button in the Control panel. It disappeared in the latest version.

### Expected Behavior

![Screenshot_20220929_213008_com huawei android launcher 1](https://github.com/AdguardTeam/AdguardForAndroid/assets/138166588/d0704f6d-643a-413f-b2d4-a87cc9878dbd)

### Actual Behavior

there was an on/off button in the quick settings panel. It disappeared in the latest version.

### Screenshots

![Screenshot_20230629_161951_com huawei android launcher](https://github.com/AdguardTeam/AdguardForAndroid/assets/138166588/fe4ca486-9238-4782-b035-a051f97f18bf)
![Screenshot_20230629_162141_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/138166588/024d9d8c-0067-403f-a86d-f485cc477e22)
![Screenshot_20230629_162347_com android settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/138166588/db6a6870-f069-4d49-b18b-cfe17c2504c1)
![Screenshot_20230629_162412_com huawei android hwouc](https://github.com/AdguardTeam/AdguardForAndroid/assets/138166588/15d95eef-44a7-4f30-a97e-499f34460200)

**Comment by maxikuzmin** [comment]
@volodievna please click on "change" in the control panel next to the gear in the upper right corner, then add AdGuard and check that
