### ISSUE TITLE
Bug: blocked router admin panel access with ip address with adguard set as always-on vpn

### ISSUE THREAD

**Issue by Ali13798** [AdguardTeam/AdguardForAndroid#4837]
On Samsung phones with android 13, there is an option to select a VPN profile as always on, and force the system to block all network traffic that is not being routed through that vpn. This can be done by follwoing: 

Phone settings app > connections > more connection settings > vpn > gear icon next to adguard > toggle on both (1) always on vpn, and (2) block connections without vpn.

Though I tried adding custom rules to adguard to process connections to the router login page (192.168.0.1 or 192.168.1.1), network access is still blocked by the os because the traffic is not being routed through adguard still. 

I tried adding the following rules to ad blocking > user rules but have not been able to access the login page unless I disable the toggle (2) above.

@@192.168.0.1 
@@192.168.0.1^$network
||192.168.0.1 
||192.168.0.1^$network
||192.168.0.1^$network,important 

Versions:
Android 13
Adguard 4.1.58 (4.1 nightly 11) 

This very well might not be a bug but rather my misunderstanding, so do let me know if that's the case.

Thanks

**Comment by sfionov** [comment]
As a workaround, you may remove your local subnet from "IPv4 ranges excluded from filtering" in Protection section of Low-level settings.

**Comment by Ali13798** [comment]
Thank you for that tip. That's a useful one for me.

The issue I submitted tho was one of those classic examples of solving it a few minutes after posting. The solution that ended up working for me was adding the following to ad blocking's user rules: 

@@/192.168.(:?0|1).1/$network,document

I think the keyword document was what I was missing.
