### ISSUE TITLE
Excluded packages in the low-level setting does not effect.

### ISSUE THREAD

**Issue by cmv4f** [AdguardTeam/AdguardForAndroid#4838]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.912

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi k40 (alioth)
- Firmware: V14.0.7.0.TKHMIXM
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1. Start a binary program with the radio user. ( running proxy software clash by box4magisk module.)
2. Adguard forwards dns and proxy data to the port the program is listening on.
3. Routing loop, check the filtering log, it shows that radio is frantically making dns requests.

### Expected Behavior

Adguard excludes radio, i.e. 1001 users, according to low-level settings.

### Actual Behavior

Programs running as the radio user are routing Loop.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

It is not possible to set other package names that are not in the settings, only run the proxy program as a radio user, version 3.0 adguard can exclude the program properly.
But after updating to version 4.0, this method fails and there is no way to exclude proxy programs.

**Comment by oldshensheep** [comment]
I'm facing the same issue. I tried adding UID 0 to the Excluded packages in the low-level setting to avoid filtering the root, but it didn't work.

**Comment by maxikuzmin** [comment]
@cmv4f @oldshensheep thanks for waiting!
Could you please clarify which program specifically the radio user program AdGuard is filtering? What DNS and Proxy are you using? 
Could you please reproduce this case and send screen shots to devteam@adguard.com?

**Comment by maxikuzmin** [comment]
@cmv4f @oldshensheep it would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
mention the 4838 number in the subject
specify the exact time when the issue occurred

**Comment by maxikuzmin** [comment]
@cmv4f @oldshensheep any news?

**Comment by oldshensheep** [comment]
I just sent the email

**Comment by oldshensheep** [comment]
I forgot to send some info, I'm using the `Automatic Proxy` Routing mode, proxy enabled, HTTPS filter with magisk.

**Comment by maxikuzmin** [comment]
@oldshensheep I see your email, but you didn't put logs in the email.
Could you please replicate the case and send debug logs as instructed in the instructions above?

**Comment by maxikuzmin** [comment]
@oldshensheep @cmv4f does it show up when sending mms, or some other cases too?

**Comment by oldshensheep** [comment]
@maxikuzmin  I did some testing, and I think excluding by UID doesn't work at all. I tried excluding UID10196 (Edge browser), but Adguard still filters ads.

**Comment by maxikuzmin** [comment]
@oldshensheepcould you also attach a video of the screen with the problem so we can better understand the gist and send it to [devteam@adguard.com](mailto:devteam@adguard.com)?
Are you testing this by blocking the Edge browser?

**Comment by oldshensheep** [comment]
@maxikuzmin 
You should test it by yourself, following steps will show the issue.
1. Install AdGuard, install HTTPS cert, enable protection.
2. Find Chrome's UID (10131)
3. Add 10131 to the Excluded Apps list in the low-level settings.
4. Access https://adguard.com/en/test.html, and it should display as 'Running'.

**Comment by maxikuzmin** [comment]
@oldshensheep @cmv4f by the way the UID for each app is assigned differently on different devices. 
I checked this, if you add the UID to Excluded apps, the filtering does indeed continue, although this is strange because the UID is converted to the app's package name. That said, if you add the app package name to Excluded apps, the app is excluded from filtering. Use that package name as a solution for now, we'll figure out what the problem is. 
Do you know where you can see the package name? Package name of the application is in the same place as the UID - in the application's technical info

**Comment by artemiv4nov** [comment]
It works as well as always. Likely, a user just didn't use a package name of the app (not the name).

**Comment by reeceyng** [comment]
> It works as well as always. Likely, a user just didn't use a package name of the app (not the name).

Is there any way to exclude a program running with root (UID 0) ?
