### ISSUE TITLE
Yelp app crashes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#484]
http://forum.xda-developers.com/showpost.php?p=66484018&postcount=1062

> Using Beta 25B Version 2.5.123
> Yelp will always crash when clicking on a Restaurant.
> https://play.google.com/store/apps/details?id=com.yelp.android

**Comment by ameshkov** [comment]
HTTPS filtering is enabled.

**Comment by Revertron** [comment]
I'm unable to crash Yelp. May be they've updated it with some fix.
But there is a problem with sign on (by G+, for example), and this problem can't be fixed by whitelisting domain or app.

**Comment by ameshkov** [comment]
@Revertron could you please attach debug log?

**Comment by ameshkov** [comment]
Confirmed, crashes when I tap on a restaraunt.

**Comment by ameshkov** [comment]
Crashes because of blocking one of yelp requests:
```
GET ads=1 "http://auto-api.yelp.com/business/local_ads?biz_id=vgseXwt9c975jus_PBM-zA&biz_request_id=6a2236291b627190&time=1461598077&nonce=X%2B0Wdg%3D%3D&ywsid=Y3yWooClkisSbx32yJG5Ww&device_type=google%2Bangler%2FMMB29P&app_version=8.8.0&cc=US&lang=en&efs=PfzDRyGHM4V18XLWcyBaqc97hWzovrs1ONr6pCBhXMmdTSQOi9IrAlck0UI37y5Ew%2B1zjO20xoVb4DAW%2FvFkLifVZAiPZMj%2BdfnE9dSY1eQ%3D&signature=_itSMPAVDjGZDXrP7qepwLtrgkyQ%3D" 0 -1 9ms "null" "Version/1 Yelp/v8.8.0 Carrier/Beeline Model/angler OSBuild/MMB29P Android/6.0.1" com.yelp.android 0 0
```

**Comment by ameshkov** [comment]
Adding this rule to mobile ads filter fixes the issue:
```
@@||auto-api.yelp.com
```
