### ISSUE TITLE
`GreaseMonkey-Redirect` scripts not working

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4840]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1 nightly 11

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi Note 11
- Firmware: MIUI 14.0.2.0 (TGKMIXM)
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Add one of the `GreaseMonkey-Redirect` scripts to AG (https://codeberg.org/zortazert/GreaseMonkey-Redirect/src/branch/main/tiktok-to-proxitok.user.js for instance)
2. Go to tiktok
 

### Expected Behavior

It should redirect you to `https://proxitok.pabloferreiro.es/en/`, which is how it works w/ AdGuard for Mac

### Actual Behavior

Redirects don't happen

### Screenshots

<details><summary>Screenshot 1:</summary>

![TT SCRIPT ISSUE](https://github.com/AdguardTeam/AdguardForAndroid/assets/15856304/b233fe08-efc2-4719-8d0a-359e4bffdbc1)

</details>

**Comment by maxikuzmin** [comment]
@Eugene-Savenko indeed on macOS the link opens without problems, but on mobile device redirects to the link too. But on a mobile device the link does not open with the error "HTTP Code: 404 That endpoint doesn't exist".
This happens even without AdGuard enabled, even on ios. This is not related to AdGuard
