### ISSUE TITLE
Sometimes the switch on the home screen disappears for a while

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4841]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: 10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

After a change in AdGuard (e.g. adding a custom filter or changing the account) -> when switching to the Home screen the switch is missing for 2-3 seconds. The swich always appears back.
In some cases this time is longer.

### Expected Behavior

Swich does not disappear after a change triggering a protection restart

### Actual Behavior

Swich disappears after a change triggering a restart of the protection

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by 0xrxL** [comment]
@maxikuzmin @Versty Any update about this issue? I can repro it by updating filters and immediately returning to the main adguard page.

**Comment by Nzzyme** [comment]
I too have observed this issue. Briefly, the switch disappears for few seconds.

**Comment by artemiv4nov** [comment]
The problem should be gone with new version, please follow for updates.
