### ISSUE TITLE
Google Play: com.gpn.azs - app doesn't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#4845]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1 Nightly 16

### Environment

```markdown
- OS: Android 13
- Device: Samsung
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Related to - https://github.com/AdguardTeam/AdguardFilters/issues/155663

Steps to reproduce:
1. Install - [https://play.google.com/store/apps/details?id=com.gpn.azs](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.gpn.azs)
2. Open app

### Expected Behavior

App should works.

### Actual Behavior

If I understand correctly app doesn't work with AdGuard enabled (it detects VPN).

https://github.com/AdguardTeam/AdguardFilters/issues/155663
>При включённом AdGuard и выключенном приложении AdGuard VPN, приложение АЗС Газпромнефть требует выключить VPN, как видно из скриншотов. Работает только при выключенном приложении AdGuard

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/29142494/310e85be-a8ef-46a3-88f4-6241875bd92e)

</details>

**Comment by Versty** [comment]
@AdamWr The issue reproduces on our side as well. 
The app will be excluded from filtering by the default.
