### ISSUE TITLE
Exclude License Key from Email Response for Feature Requests

### ISSUE THREAD

**Issue by TUO1500** [AdguardTeam/AdguardForAndroid#4849]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.912

### Environment

```markdown
- OS:HarmonyOS 3.0.0.208 (Android 12)
- Device: Huawei nova 7 Pro 5G
- Firmware: JER-TN10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Send a feature request on AdGuard Android version 4.0.912.
2. Wait for the email response.
3. Check the email and observe the inclusion of link of the licence.txt file.
4. Open the licence.txt file and find the license information, including the license key.

### Expected Behavior

The email response should provide license information without including the sensitive license key.

### Actual Behavior

The email response provides license information including the sensitive license key.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/103294565/3aa3cc56-791a-45a0-9b3d-8b9dbca32771)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/103294565/4385e7ed-ad30-4286-b1f0-88499714e5c2)

</details>

### Additional Information

If including the license key in the email response is unavoidable for some reason, please provide an explanation as to why it is necessary. However, considering the potential security risks, it would be appreciated if AdGuard could find a secure alternative or omit the key altogether.

**Comment by maxikuzmin** [comment]
@TUO1500 thanks for waiting!
This file is generated automatically when you submit a ticket, when you mark "send diagnostic report". The License file is attached to the ticket, as we often need this information to answer the question correctly and help the user to understand. 
Globally, you can provide additional mail protection, for example, with the 2-FA key to minimize security risks. On our side we guarantee the safety of your key
