### ISSUE TITLE
Touch & hold on icon: toggle protection

### ISSUE THREAD

**Issue by Gittyperson** [AdguardTeam/AdguardForAndroid#4851]
### Issue Details

Version 4 removed the ability to touch and hold the main AdGuard icon and toggle protection. I no longer see this option, only regular Android actions are available (App info, Remove, Uninstall, Share).

I know there's a widget to toggle protection, but this was very handy. Please restore it if possible, thank you.

Android 12, realmeUI 3.0, AdGuard 4.0

### Proposed solution

Restore the previously available feature

### Alternative solution

The available Widget, but it requires additional and unnecessary screen space just for this one action.

**Comment by Versty** [comment]
@Gittyperson Thank you for asking! 

Shortcuts will be restored in the future version for sure. 

This issue duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/4780, therefore closed. 
Please upvote the linked issue.
