### ISSUE TITLE
AdGuard can't autostart due BootUpReceiver unable to start foreground service 

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdguardForAndroid#4852]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0+

### Environment

```markdown
- OS:11 
- Device:Xiaomi Redmi Note 8
- Firmware:(MIUI 12.5.2
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Enable AdGuard autostart 
2. reboot\ off-on device
3. AdGuard won't start on device start-up 

### Expected Behavior

AdGuard able to launch itself upon start up

### Actual Behavior

AdGuard remains off despite autostart option is enabled

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Giova84** [comment]
I've found the same with AdGuard 4.2: it no longer autostart, despite the fact that on my device (Android 13 - MIUI 14) AdGuard is set to autostart.
Was fine with AdGuard 4.1.

**Comment by artemiv4nov** [comment]
Please re-check your notification settings, they should be turned on for AdGuard. We can't reproduce the task.
