### ISSUE TITLE
Google Play: com.teboil.azs - the app does not work

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#4853]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 11
- Device: Xiaomi POCO F1
- Firmware:
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1. Install the app [https://play.google.com/store/apps/details?id=com.teboil.azs](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.teboil.azs)
2. Open it

### Expected Behavior

The app should work.

### Actual Behavior

According to [the report](https://github.com/AdguardTeam/AdguardFilters/issues/156745), the app does not work properly.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by max19-8** [comment]
Hello @zloyden , we have investigated and it seems that the application does not correctly determine whether the network is a vpn network or not. For example: the application can also recognize a wifi network as vpn. Unfortunately, we can't do anything about it until the team of this application writes a normal vpn network detector, we also noticed that many users of the teboil application complain about the same problems without VPN connection enabled, even when using mobile network. Therefore, we believe that you should wait for a fix in the teboil application and if the problem persists, we will consider it again
