### ISSUE TITLE
Data Usage statistics counter is zeroed after switching to GBs 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4855]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard Version 4.1 Nightly 23

### Environment

```markdown
- OS:Android 13
- Device:Samsung 
```

### Issue Details

When one of the counters in the Data Usage section reaches GB values, it is zeroed. At the same time, the other counter in the uploaded/downloaded pair increases drastically over time, while the first keeps displaying zero. 

#### Prerequisites 
- Statistics are cleared
- AdGuard is configured for HTTPS filtering 
- Device is connected to Wi-FI

1. Enable protection 
2. Open the Statistics tab 
3. Switch the data type for Data Usage section to `Wi-Fi only`
4. Surf some websites until one of the counters under "Data Usage" reaches GB value

### Expected Behavior

All counters in the Data Usage section display the correct amount of data 

### Actual Behavior

One of the counters displays zero, but another counter in the uploaded/downloaded pair increases drastically over time. 

<details><summary> Screenshots</summary>

![Screenshot_20230719_080630_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/96619913/4e74387b-da6f-4fe9-ac33-dacd172ce577)
</details>

### Additional Information

Applicable to `Wi-Fi only` and `Mobile data only` uploaded and downloaded counters. 
`All data` is fine.

**Comment by Versty** [comment]
@Batman2814 Thank you for reporting! 
We have managed to reproduce this issue on our side. Will be fixed.
