### ISSUE TITLE
License Key is showed in clear text in the application 

### ISSUE THREAD

**Issue by J-khatri** [AdguardTeam/AdguardForAndroid#4857]
### Issue Details

As subject line says, License key can be viewed clearly in Application, that's not convenient in anyway . It should ( must ?) not show the key in clear text. 

 If you ask me the scenario where it can create an issue. say I'm using smart lock feature of android where phone remains unlock based on location ( say in my office ) during that period if any one how have physical access to my phone can open the app and can copy or snap the license key and can activate in his/her mobile. 
 
 I've tested it with one of my office device , I just entered the key from my device to the office device and it got activated without any issue !!!! and my own personal device  got deactivated as the key was entered in new device.

### Proposed solution

Please bind license to device with key + email authentication ( my be OTP ? ). 

and in any case key should not be visible in clear text at all. 

### Alternative solution

to activate Adguard product user must have to - enter key + email to activate the product ![Screenshot_2023-07-19-23-07-43-52_a93965f46c4a4b0ed1be737bdf2bc8fc.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/57787001/123df1e1-16f4-444f-8395-f1c9207f075b)

**Comment by Versty** [comment]
@J-khatri, Hi! This issue is a duplicate. 

Please upvote the first post of discussion https://github.com/AdguardTeam/AdguardForAndroid/issues/4496.
