### ISSUE TITLE
HTTPS filtering does not work for Google domains (Android N)

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#486]
Missed both type of ads: banners and video ads. 
Here's log: https://www.dropbox.com/s/ovxoyne5ajkbq9a/youtube.log?dl=0

**UPD:** The problem is with all google domains.

**Comment by ameshkov** [comment]
So, what has happened:
1. Google has removed Equifax root certificate in Android N.
2. The problem is that AG did not try to use GeoTrust root to verify the certificate.

Relevant discussion:
https://www.mail-archive.com/openssl-dev@openssl.org/msg38674.html

**Comment by ameshkov** [comment]
Fixed

**Comment by Bohdan-SUP** [comment]
Adguard 2.6.67, Android N
YouTube ads still go through:
[youtube.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/300071/youtube.txt)

**Comment by ameshkov** [comment]
File a new bug report, it has nothing to do with this one.

**Comment by ameshkov** [comment]
@Bohdan-SUP i'll also need users HAR files:
http://forum.xda-developers.com/showpost.php?p=67186807&postcount=1302
