### ISSUE TITLE
Landscape view on tablets

### ISSUE THREAD

**Issue by bial654321** [AdguardTeam/AdguardForAndroid#4865]
### Issue Details

Hello. I personally use adguard every day to check my statistics, change same settings here and there on my tablet on which I have adguard installed. Would that be a problem if you guys implemented the landscape view for tablet users? I'd would make my life (and some of my familh member's) lifes easier thank you 😁

**Comment by Versty** [comment]
@bial654321 Hi! 

This issue duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/4817. 
Please vote for the feature request by putting the `thumbs up` emoji on the first post of the linked issue.
