### ISSUE TITLE
tTorrent app compatibility issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#487]
**Source report:**
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=49052182

App:
https://play.google.com/store/apps/details?id=hu.tagsoft.ttorrent.lite&hl=en

**Comment by Revertron** [comment]
It seems that torrent-client is causing low memory and Android it killing background services. There is nothing we can do.
