### ISSUE TITLE
com.uclive.edu app shows proxy error 

### ISSUE THREAD

**Issue by senseigit** [AdguardTeam/AdguardForAndroid#4872]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.101

### Environment

```markdown
- OS: Android 12
- Device:2201116PI
- Firmware:Miui 13
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Adblock Warning Removal List

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Block the third-party Authorization header, Disable WebRTC, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1.Install the app https://play.google.com/store/apps/details?id=com.uclive.edu
2. Launch app 
3. Not working
4. Tried removing app from filtering
5. But still not working 😞

### Expected Behavior

Install app https://play.google.com/store/apps/details?id=com.uclive.edu

On lauch, app works fine without any errors.

### Actual Behavior

App showing proxy error

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-07-27-12-51-13-252_com uclive edu](https://github.com/AdguardTeam/AdguardForAndroid/assets/118798328/39d37c50-0ac6-4d88-bb1a-5f5974d40785)

<
![Screenshot_2023-07-27-12-51-13-252_com uclive edu](https://github.com/AdguardTeam/AdguardForAndroid/assets/118798328/a4633e01-c82b-4567-9c38-d31f4a1bae38)
>

</details>

**Comment by Versty** [comment]
@senseigit Hi! 
Please try disabling the `Route traffic through AdGuard` switch for the UC LIVE app in the App management tab of the AdGuard app. This solution works on our side.

**Comment by senseigit** [comment]
Yes, that works but I want to use it with adguard enabled.
Is it not feasible?

**Comment by Versty** [comment]
@senseigit Unfortunately, the filtering is limited by UC LIVE app in this case. You can contact developers of the app and report the problem.

**Comment by senseigit** [comment]
Thanks for your response. However, issue is now gone for good😊.
