### ISSUE TITLE
"DNS Filters" Take Forever to Update

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#4873]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 12
- Device: 
- Firmware: MIUI 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open AG
2. Click on the icon on the top-right to update filters
3. Except the "DNS filters", all the other filters are updated

### Expected Behavior

All the filters in the list are supposed to be updated.

### Actual Behavior

The update animation on the "DNS filters" just keeps rotating. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Checked with:
1. Wi-Fi and
2. Mobile data of two mobile networks.

**Comment by Versty** [comment]
@Nzzyme, hi!  
For a better understanding, we would like to take a look at the logs from your device. 
Please follow the steps below to properly collect the logs. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `4873` number in the subject
      - specify the exact time when the issue occurred

**Comment by Nzzyme** [comment]
> @Nzzyme, hi! For a better understanding, we would like to take a look at the logs from your device. Please follow the steps below to properly collect the logs.
> 
> 1. Enable debug logging:
>    _Settings -> General -> Advanced -> Logging level -> Debug_
> 2. Reproduce the issue, then remember the exact time when it happened
> 3. Collect logs:
>    _Settings -> General -> Advanced -> Export logs and system info_
> 4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
>    
>    * mention the `4873` number in the subject
>    * specify the exact time when the issue occurred

I no longer observe this issue. Must be a temporary issue with checking & downloading the updates from the DNS server. You can close this for now. Thanks!
