### ISSUE TITLE
When quickly switching switches in Firewall rules, the rule list lines blink

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4885]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: 10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

Go to Protection tab -> Firewall -> Custom firewall rules -> Add app -> Add rules for app -> start quickly clicking on the rule switches

The lines on the interface next to each line start blinking

### Expected Behavior

Quick-click rules for "Custom firewall rules" do not create flickering lines on the interface

### Actual Behavior

Quick-click  rules for "Custom firewall rules" create flickering lines on the interface

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by nightznero** [comment]
Also for me Firewall in Stable version have more annoying bug where after few days most of apps are deleted from list(not all dunno why and which one) if anyone could provide its only me or.. ,before next stable release
