### ISSUE TITLE
When importing DNS user rules containing empty lines, these lines are added

### ISSUE THREAD

**Issue by ESurina** [AdguardTeam/AdguardForAndroid#4888]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0, 4.1

### Environment

```markdown
- OS:11, 12
- Device: Pixel, Xiaomi
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1. Protection ->DNS protection ->DNS filters ->User rules
2. Create a file containing some empty strings
3. Import this file to the user rules (3 dots -> Import)

### Expected Behavior

Empty strings are not imported

### Actual Behavior

Empty strings are added to the rules.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/138680450/66c75795-0217-4f1f-91f8-a1696dce0e23)

</details>

**Comment by superlex** [comment]
Hi guys,
just 2 suggestions:
- this bug regards Ads Blocker - User Rules too;
- commented lines should be added as well, but without  being selected.

Example:
<img width="346" alt="dd" src="https://github.com/AdguardTeam/AdguardForAndroid/assets/1375223/2497a38c-e1d0-4ae1-8a12-a0cc126bd247">
