### ISSUE TITLE
DNS Leak with v4.1

### ISSUE THREAD

**Issue by leacha69** [AdguardTeam/AdguardForAndroid#4889]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.101

### Environment

```markdown
- OS: Android 13
- Device: Samsung Galaxy Tab S7+
- Firmware: TP1A.220624.01 4.T970XXU3DWD3
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Cookie Notices filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Self-destruction of third-party cookies, Self-destruction of first-party cookies, Protect from DPI

### Issue Details

Steps to reproduce:
1. 
2.
3.

### Expected Behavior

AdGuard should resolve DNS IP through AdGuard VPN.

### Actual Behavior

AdGuard leaks actual IP from ISP.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Running AdGuard v4.1 with AdGuard VPN v2.4 used multiple online DNS leak sites and noticed my ISP address was leaked.

Downgraded to AdGuard v3.6 with AdGuard VPN v2.2 and... no leaks.

Upgraded to AdGuard v4.0 with AdGuard VPN v2.4 and... no leaks.

Upgraded back to AdGuard v4.1 with AdGuard VPN v2.4 and... leaks.

**Comment by Versty** [comment]
@leacha69 Hi!
Please specify the DNS server you are using in AdGuard. 
Are both apps running in integrated mode on your device?

**Comment by leacha69** [comment]
Hi! Please specify the DNS server you are using in AdGuard. 
> AdGuard Personal DNS server. (Protocol: "DNS-over-QUIC" Server: "dns2-dp-chi-1")

Are both apps running in integrated mode on your device?
> Yes

Does the issue persist on both Wi-Fi and cellular data?
> WiFi I do not have cellular.

I also noticed its limited to the Illinois datacamp DNS address the VPN links to.

**Comment by Versty** [comment]
@leacha69 Hi! 

> I also noticed its limited to the Illinois datacamp DNS address the VPN links to.

Does the leak persist if you change the location in AdGuard VPN?

**Comment by leacha69** [comment]
Yes, but I've only tried Denver and Dallas. I'll try with additional
locations. I've downgraded to 4.0 and no leaks.

**Comment by leacha69** [comment]
I've upgraded back to 4.1 and the leaks persist across multiple location
from east, central and west cost of the USA.

**Comment by leacha69** [comment]
So... Still leaking.

**Comment by Versty** [comment]
@leacha69 Got it. 
We have examined the logs from your device. Please try disabling the `Ignore unavailable outbound proxy` option in the low-level settings and check if the issue persists.

**Comment by leacha69** [comment]
I'm sorry but the issue still persists. Once again only on Android AdGuard v4.1. Version 4.0 does not show any leaks.

**Comment by Versty** [comment]
@leacha69 Got it. 
Could you check if the issue persists with different protocols? 
For example, DoH or Regular

**Comment by leacha69** [comment]
It does. I even disabled all filters, no DNS, private DNS, Google DNS, etc,
it leaks. Anytime AdGuard 4.1 is integrated with AdGuard VPN it leaks.
AdGuard 4.0 or less with integration, no leaks. Use AdGuard VPN without
integration, no leaks.

Thank you for all the work but I've basically given up using AdGuard 4.1
with AdGuard VPN. When AdGuard 4.1 gets an update I'll check again.

**Comment by Versty** [comment]
@leacha69 Could you check with AdGuard for Android 4.2 beta? 
The version is already available on the beta update channel.

**Comment by leacha69** [comment]
Installed 4.2 Beta, double checked settings and.... DNS leak showed up with
my IP. Sorry.

Prior to this, I've been running v3.6 and no leaks. So before 4.2 Beta, I
upgraded to 4.0 and no leaks. Upgraded to 4.1 and leak. 4.2 Beta, leak.

**Comment by leacha69** [comment]
What data is needed?

**Comment by Versty** [comment]
@leacha69 Hi! 
We have made some adjustments to DNSLibs in the latest stable version.
Could you reproduce this issue once again and provide the debug logs from the latest AdGuard for Android release version (4.3.194)? 

Please follow the steps from https://github.com/AdguardTeam/AdguardForAndroid/issues/4889#issuecomment-1679280377

**Comment by leacha69** [comment]
With the latest update (4.3.194), I do not have any DNS leaks.

Thank you!
