### ISSUE TITLE
AdGuard is unable to load pages with v2rayNG proxy 

### ISSUE THREAD

**Issue by liush6** [AdguardTeam/AdguardForAndroid#4893]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2 Nightly 9

### Environment

```markdown
- OS:harmonyOS 3
- Device:honor
- Firmware:honor V20
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard URL Tracking filter, AdGuard Mobile App Banners filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block the third-party Authorization header, Disable WebRTC, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1.v2rayNG 仅代理模式。代理链接可用
2.打开adguard，打开过滤->网络->代理，打开开关，socks5，127.0.0.1, port: 11999, 不过滤DNS
3.dns保护里面选择自动，那么没有任何流量经过，所有全是找不到IP，选择Google dns 常规，有流量经过，但非常非常慢，只能加载出文字的那种情况。

### Expected Behavior

正常的顺利的让流量经过。

### Actual Behavior

没有链接，没有流量，什么也没有。所以这段时间我没有打开过adguard，它的错误真的很久了。请看图一。

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230802_232907_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/67771742/bcb22c4e-3395-4447-bf4b-f34090b8f40f)

![Screenshot_20230802_235113_com huawei systemmanager](https://github.com/AdguardTeam/AdguardForAndroid/assets/67771742/12d21c84-dfa7-4e7d-b18c-2b3b1b2e4793)

![Screenshot_20230802_235143_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/67771742/76634198-a1a9-450b-9d9a-5c40d06621ee)

</details>

### Additional Information

另外，我发现我的手机充电时，过滤的统计信息不正常的激增，这个月我还没有打开过adguard，它的统计信息却比我所用的还要多几倍，这也是一个问题吧。请看图二、图三。

**Comment by YelenaKoroleva** [comment]
你好！
问题一、请问你有没有在AdGuard的【应用管理】中对v2rayNG禁用【通过AdGuard路由流量】？
问题二、这是一个已知问题，请访问此网页查看问题的进展：https://github.com/AdguardTeam/AdguardForAndroid/issues/4855

**Comment by liush6** [comment]
对于软件设置，我在以前的尝试中把 通过adguard路由 与下面选项的 通过代理 的选项都关闭，结果是不联通，不能使用代理。最近的尝试，我仅关闭了 通过adguard路由 ，结果没有变化。在您询问之后，我把两个选项都关闭，结果没有变化。以上是我的尝试，希望对你有帮助。
________________________________

**Comment by YelenaKoroleva** [comment]
你好！请尝试完全关闭【防护】中的【DNS保护功能】和【应用管理】-【v2rayNG】里的【通过AdGuard路由流量】选项。问题还是存在吗？

**Comment by YelenaKoroleva** [comment]
@liush6  你好，请问你有没有试过按照我们上次的建议操作？

**Comment by liush6** [comment]
感谢您的回访，其实您最后一个建议我在之前已经试验过了，但没有作用。我对此感到疑惑，也有些失望，也许错误不在这里，也许是v2rayng的错误，毕竟很长一段时间了，也许是我手机的错误，但我不想重置它。这就是我的回复，我现在没有结合使用的想法了，也许等我换新的手机，到时候使用自动代理就没有这些烦心事了。
________________________________

**Comment by YelenaKoroleva** [comment]
你好，感谢你的回复！为了确定这是AdGuard软件、v2rayNG还是手机的错误，我们需要查看应用程序的日志。请按照以下步骤导出AdGuard的调试日志：
1. 打开AdGuard → 前往【设置】→【通用】→【高级设置】→【日志级别】→ 选择【调试】。
2. 重现问题：先连选择自动的DNS以重现“没有任何流量经过，所有全是找不到IP”的问题，再连接到Google DNS以重现“有流量经过，但非常非常慢，只能加载出文字的那种情况”的问题。请在重现问题时，记下精确时间。
3. 返回到【通用】→【高级设置】→ 点击【导出日志和系统信息】。
4. 保存压缩包, 把日志记录和重现问题的时间发送到devteam@adguard.com，在邮件主题中输入GitHub问题的编号：#4893。
5. 在【高级设置】里把日志记录级别切换到【默认】 , 否则软件将继续记录日志，导致手机的内存满了。

**Comment by YelenaKoroleva** [comment]
@liush6 你好！请问，你有没有把日志记录发给devteam@adguard.com？期待你的回复～

**Comment by liush6** [comment]
***@***.******@***.***。
________________________________

**Comment by YelenaKoroleva** [comment]
@liush6 你好！我们看不到你的回复。你有没有把日志记录发给devteam@adguard.com？

**Comment by YelenaKoroleva** [comment]
问题因未得到回复自动关闭。如有需要，请重新打开这个问题。
