### ISSUE TITLE
Android version, product type and AdGuard version are incorrectly detected in the "Report incorrect blocking" form 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdguardForAndroid#4895]
### Version
AdGuard for Android 4.2 nightly 10

### Environment
Any compatible android version 

### Steps to reproduce 
1. Launch AdGuard 
2. Open the Settings tab -> Support
3. Click the `Report incorrect blocking`

### Expected behaviour 
Web report form has opened, product type is automatically set to `AdGuard for Android`
Version number is detected correctly. 

In step 4 of the form, the Android version is automatically filled in as well.

### Actual behaviour
Web report form has opened, product type is not detected. 
Version number is detected, but duplicated. 

In step 4 of the form, API level is used instead of Android version. 

<p align="left">
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/107266340/7f7643e6-a1a1-4d54-882c-7fddb8c901f3" width="300" height="600">
</p>

### Additional information 

Actually, we can improve the version type from technical version (for example, 4.2.20) to user-friendly version (4.2 nightly 10)

**Comment by Nzzyme** [comment]
Observed at my end too (I am still on 4.0.)

**Comment by Nzzyme** [comment]
Still observed in 4.2 release
