### ISSUE TITLE
AG does not report a new version update although the update channel is set as 'Release' 

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#4897]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 12
- Device:
- Firmware: MIUI 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open the app
2. Update the filters
3. On the updates page, AG does not report a new version update. It still says "Up to date"

### Expected Behavior

On the updates page, as there is already a new 'release' version available (4.1), the app should have reported a new version update.

### Actual Behavior

On the updates page, the app does not report a new version update although there is a new 'release' version available (4.1).

### Screenshots

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/6959116/7c46bb52-5d59-47f6-8167-fb9e5e9c41d3)

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/6959116/ca3f8488-c590-4289-b9e5-6a0d4a39bb84)

**Comment by Versty** [comment]
@Nzzyme Hi! 
This issue can be a part of https://github.com/AdguardTeam/AdguardForAndroid/issues/4873.
Therefore, it is important to collect the debug logs for a further investigation. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `4897` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@Nzzyme Does this problem still persist?

**Comment by Nzzyme** [comment]
> @Nzzyme Does this problem still persist?

I updated the app and since there are no new updates, the app reports no new updates. So you can close this for now.
