### ISSUE TITLE
Apps use cellular data when enabling cellular and Wi-Fi interfaces

### ISSUE THREAD

**Issue by MySoul182** [AdguardTeam/AdguardForAndroid#4899]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.82

### Environment

```markdown
- OS:7
- Device:XiaoMi
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

同时打开移动数据和Wifi会使用移动数据

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-08-07-12-59-54-940_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/95344231/6e051fe1-41ec-4af9-84b8-0235c1528563)
</details>

**Comment by YelenaKoroleva** [comment]
你好！应用软件本身决定使用Wi-Fi 或移动数据来连接到互联网。你可以在AdGuard的【设置】-【防护】-【防火墙】中确保一下你是否对Edge关闭【使用Wi-Fi】，也可以在【自定义防火墙规则】中对Edge关闭【使用移动数据】。

**Comment by MySoul182** [comment]
> 你好！应用软件本身决定使用Wi-Fi 或移动数据来连接到互联网。你可以在AdGuard的【设置】-【防护】-【防火墙】中确保一下你是否对Edge关闭【使用Wi-Fi】，也可以在【自定义防火墙规则】中对Edge关闭【使用移动数据】。

> 不，我没有开启自定义防火墙规则，而且是所有软件都在移动数据和Wifi同时开启的时候使用移动数据，这让我无法正常使用自定义防火墙规则。这个错误在单使用移动数据或Wifi的情况下并没有发现，并且这个错误我在4.0.912版本就已经发现到现在还没修复

https://github.com/AdguardTeam/AdguardForAndroid/assets/95344231/adbc35f3-bc43-475a-acc3-97f5e11b208b

**Comment by YelenaKoroleva** [comment]
你好，请在GitHub问题 #4925 查看问题的进展。
