### ISSUE TITLE
No way of accessing license on Android TV

### ISSUE THREAD

**Issue by oroboros** [AdguardTeam/AdguardForAndroid#4909]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
Android TV
```

### Root access

- [ ] Yes, I have it.

### Issue Details

I'm trying to input license via Google, via email, via license number.

### Expected Behavior

I should be able to at least access the text input fields.

### Actual Behavior

If I select input via Google it shows "no app installed". When I try to input via text my email or even my license, the keyboard doesn't show up.

Do note that up to version 3, despite Android TV wasn't officially supported, AdGuard was working perfectly fine with minor UI issues only (see https://github.com/AdguardTeam/AdguardForAndroid/issues/2154), and ever since the new version 4, everything has been broken.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Do note that up to version 3, despite Android TV wasn't officially supported, AdGuard was working perfectly fine with minor UI issues only (see https://github.com/AdguardTeam/AdguardForAndroid/issues/2154), and ever since the new version 4, everything has been broken.

**Comment by oroboros** [comment]
> @oroboros Thank you for reporting!
> 
> We are already working on the official support for Android TV. This behaviour will be improved for sure.

That's great news. I had bought a subscription back when it was working, and I finally bought a family subscription. It's disappointing that now I'm not able to apply the license. It's been years since Adguard said it was working on official support for Android TV, but it was working fine until version 4. As an early beta tester, it's disappointing that these issues weren't dealt with before launching the new version 4 (https://github.com/AdguardTeam/AdguardForAndroid/issues/4773)

Is there any way to least revert to when these bugs were introduced in version 4? 

Alternatively, would I be able to find an old v3 version to make use of the license we bought, or is there incompatibility with the new app and the scripts? Thanks!

**Comment by oroboros** [comment]
> @oroboros Thank you for reporting!
> 
> We are already working on the official support for Android TV. This behaviour will be improved for sure.

That's great news. I had bought a subscription back when it was working, and I finally bought a family subscription. It's disappointing that now I'm not able to apply the license. It's been years since Adguard said it was working on official support for Android TV, but it was working fine until version 4. As an early beta tester, it's disappointing that these issues weren't dealt with before launching the new version 4 (https://github.com/AdguardTeam/AdguardForAndroid/issues/4773)

Is there any way to least revert to when these bugs were introduced in version 4? 

Alternatively, would I be able to find an old v3 version to make use of the licence we bought

**Comment by Versty** [comment]
@oroboros We appreciate your willingness to help us as a beta tester.  
The best solution for now is to install the old version (3.6.11) on Android TV. Everything related to filtering should work as usual. 
We will send you the .apk file of the old version if you request it in the email to devteam@adguard.com.
Please mention the issue number `4909` in the subject line.

**Comment by Versty** [comment]
@oroboros This issue will be fixed as a part of https://github.com/AdguardTeam/AdguardForAndroid/issues/3597.
