### ISSUE TITLE
Add a filter to block porn sites on Android

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#491]
I want that you add a porn filter that blocks the access of porn sites in the mobile and any porn content in this app....which can be on and off by user...

PDH-971-67423

**Comment by ameshkov** [comment]
Hm, i suppose the issue will be sorted out when we add an option for adding custom filters by url

**Comment by TPS** [comment]
> Hm, i suppose the issue will be sorted out when we add an option for adding custom filters by url

@evgeniy-ADG #13 is where @AdguardTeam keeping track of this

**Comment by TPS** [comment]
Another way to do it (& probably more effectively) is, whenever #139 lands, configure with [OpenDNS FamilyShield](https://support.opendns.com/entries/46060260-FamilyShield-Router-Configuration-Instructions).  It's currently scheduled for v2.6, so likely will land _before_ #13.…

**Comment by TPS** [comment]
@evgeniy-ADG If you're running the most current ß, released in the last 24 hours, #139 has landed. Under Settings → Advanced → Low Level Settings → `pref.vpn.dns`, try 

208.67.222.123
208.67.220.123
::ffff:d043:de7b
::ffff:d043:dc7b

Report back after testing & tell whether it worked.… ☺

**Comment by ameshkov** [comment]
@TPS @evgeniy-ADG is a team member:)

Also thanks for the tip, nice:)

**Comment by TPS** [comment]
_(@ameshkov Well, it'd be nice if @evgeniy-ADG had <kbd>Adguard member</kbd> in the comment headers like you do, so we users **know** that!)_

& you're all welcome, of course! ☺

**Comment by evgeniy-ADG** [comment]
I do have that

![image](https://cloud.githubusercontent.com/assets/15856304/15508623/e28036c0-21d8-11e6-94a0-f304663a7d16.png)

**Comment by TPS** [comment]
> Will #13 handle `hosts`-lists like this?

@ameshkov Or must I file a separate issue to handle adding custom `dns`-blocklists, as well?

**Comment by TPS** [comment]
@evgeniy-ADG I see such for @ameshkov, but not you!

**Comment by ameshkov** [comment]
@evgeniy-ADG make it public here: https://github.com/orgs/AdguardTeam/people

**Comment by TPS** [comment]
Is this solved now, or is @AdguardTeam planning to make an official porn filterlist? _(Warning: If so, a huge, ongoing project.)_

**Comment by ameshkov** [comment]
@TPS spoiler alert: working on our own DNS servers which will provide "parental control" as well.

**Comment by TPS** [comment]
Wow, so something like OpenDNS, but with ad-blocking rolled in?  HUGE news! 🎆 :metal:

**Comment by ameshkov** [comment]
> Will it be public-facing, for those not running AG?

Yep, free of charge for personal use ad & tracking blocking DNS server.

**Comment by TPS** [comment]
Also customizable via a dashboard, like OpenDNS Free?

**Comment by ameshkov** [comment]
Not in the first version

**Comment by ameshkov** [comment]
Doable by enabling AG Family DNS
