### ISSUE TITLE
ESPN APP playback issues

### ISSUE THREAD

**Issue by Thiboodeaux** [AdguardTeam/AdguardForAndroid#4916]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: android 13
- Device: samsung 
- Firmware: 5.1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to reproduce:
1. When adguard enabled, videos do not play
2. When adgaurd disabled, videos play 
3. When adguard disabled and app closed the repopend and adguard re enabled vidoes play fine but when app is closed problem comes back 

### Expected Behavior

Video plays with no ad 

### Actual Behavior

Video buffers 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@Thiboodeaux Hi! 
Seems like the issue is caused by the HTTPS filtering. Please disable the `Filter HTTPS` option for ESPN application in the App management tab and let me know the result.

**Comment by Versty** [comment]
@Thiboodeaux Has the above solution helped?

**Comment by Versty** [comment]
@Thiboodeaux Closed due to inactivity. Please reopen if needed.
