### ISSUE TITLE
Blocks Internet access in all applications that require Internet access 

### ISSUE THREAD

**Issue by theadams** [AdguardTeam/AdguardForAndroid#4924]
i am using adguard latest nighly. and translate, web page display, even to display a sticker on telegram, adguard blocks internet access from the root, it seems to be fixed when I boot it again, and it's the same after a while. 

Android 13

Samsung note20u

**Comment by Versty** [comment]
@theadams Hi! 
Please fill in the bug report form from [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/new/choose), you  can also use the language you are most comfortable with.
