### ISSUE TITLE
Dark splash screen in the dark theme 

### ISSUE THREAD

**Issue by janowakps** [AdguardTeam/AdguardForAndroid#4928]
### Details

So the application supports dark mode but even if it is enabled splash screen is all white, I think it is right to make dark splash screen if this option is enabled.  

<details><Summary>Screenshot</summary>

![Screenshot_20230818-010519_AdGuard.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/36198623/f4d9cb03-4d52-4f2d-a0f5-e19cd2f5fa6d)

</details>

### Additional info
 Added by @Versty
 
The dark splash screen will clearly make the application more comfortable to use in dark environments.

Related issues:
- https://github.com/AdguardTeam/AdguardForAndroid/issues/4464 
- https://github.com/AdguardTeam/AdguardForAndroid/issues/2657

**Comment by Versty** [comment]
@janowakps Hi! 

Let's see if this feature will be requested by other users as well, and will be upvoted enough.

**Comment by Giova84** [comment]
I request this feature as well (I upvoted).

**Comment by janowakps** [comment]
> @janowakps Hi!
> 
> Let's see if this feature will be requested by other users as well, and will be upvoted enough.

seriously it takes that long to implement such a simple thing? somehow adguard VPN just has it

**Comment by FadeMind** [comment]
@ameshkov really annoying WHITE full screen adguard logo splash after restart Adguard Android App 🫤

**Comment by superlex** [comment]
Dark theme -> dark splash screen
White theme -> white splash screen

Infact I thought it was a bug 😅

**Comment by TPS** [comment]
@AdguardTeam Thanks for the dark splash in v4.3n8! 🙇🏾‍♂️

**Comment by TPS** [comment]
It's automatic based on system-wide dark mode & then related AG setting as System.

**Comment by Daviteusz** [comment]
I still have white splash in 4.3n16 with global dark theme and dark app.

**Comment by Giova84** [comment]
> I still have white splash

Same for me, on AdGuard 4.2

**Comment by Versty** [comment]
@janowakps @Daviteusz 
Please recheck the splash screen in AdGuard for Android 4.5 and let me know if the issue is eliminated.

**Comment by Daviteusz** [comment]
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/76b06c01-1955-4e45-a79f-a47bd978432b" width=30%>

Android 14

<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/e7bc29f5-7a17-4698-8763-570d23a9c966" width=37.5%>

Android 11

**Comment by Versty** [comment]
@janowakps @Daviteusz @TPS 
The color of splash screen is currently optimized for Android 12 and higher. 
We have also discussed the splash screen color for earlier versions of android and decided to leave it in its current state.
