### ISSUE TITLE
Oneplus theme store,community app login not working

### ISSUE THREAD

**Issue by SohanRay** [AdguardTeam/AdguardForAndroid#4929]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.1

### Environment

```markdown
- OS: Android 13
- Device: OnePlus Nord 3(India)
- Firmware: Oxygen OS 13.1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Disable WebRTC

### Issue Details

trying to view themes in theme store.
trying to login into OnePlus account in Oneplus community app.

### Actual Behavior

Unable to view themes online.
unable to login into Oneplus account.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@SohanRay Hi! 
Please try disabling HTTPS filtering for these applications in the App management tab and let me know the result.

**Comment by Versty** [comment]
@SohanRay How is it going?

**Comment by SohanRay** [comment]
Never enabled https filtering for these apps. Some wrong domains were being blocked at the time.
