### ISSUE TITLE
Https filtering doesn't persist if it was off by default and you manually turn it on and then disable the app.

### ISSUE THREAD

**Issue by Rtizer-9** [AdguardTeam/AdguardForAndroid#4930]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.30

### Environment

```markdown
OS : Android 13
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Turn on https filtering manually for an app for which ag has disabled it by default.
2. Disable/freeze the app using some battery saving app or manually (which means that you're actually using it regulary but just disable it for battery saving or some other reason only for no background activity.
3. Adguard https filtering again gets disabled for that app.

### Expected Behavior

1. Https filtering toggle should persist regardless of whether the app is enabled or not.

### Actual Behavior

Adguard https filtering again gets disabled for that app if it was off by default.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I've installed both System certificate and intermediate certificate using adguardcert module so I have complete capability to toggle https filtering for any app. (SSL pinned apps won't work I know but that won't turn off the https toggle by themselves in ag.

**Comment by Versty** [comment]
@Rtizer-9 Hi! 
We are trying to reproduce the problem on Android 13, but to no avail yet. 
Could you provide details about the operating mode (Local VPN or Automatic/Manual proxy) and device model?

**Comment by Rtizer-9** [comment]
It happens in both the modes. Device model shouldn't really matter because I'm on custom rom based on aosp.

I'll try explaining it in simple words - I've some apps for which ag filtering is turned off by default like Amazon, Facebook, Insta, Coursera. I understand the reason but when I've turned https filtering on manually I want it to be persistent.

Now to save battery I keep them frozen using an app called hail (foss, uses various methods for freezing or disabling, I'm using shizuku disable) which freeze (disable in my case) the selected apps after screen lock.


After they've been disabled the ag https filtering setting revert back to disabled for them again.

Now you can understand I don't want to manually turn it on again and again when I've manually turned it on once.

**Comment by Versty** [comment]
@Rtizer-9 Thank you for the details. Could be part of bug https://github.com/AdguardTeam/AdguardForAndroid/issues/5008, which will be fixed in AdGuard for Android 4.2 beta 2. 
Please let me know and reopen this issue if the problem persists on beta 2.
