### ISSUE TITLE
The firewall (most of the time) adds and deletes the wrong app

### ISSUE THREAD

**Issue by binarweb** [AdguardTeam/AdguardForAndroid#4933]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.0

### Environment

```markdown
- OS:Android 13
- Device: Samsung A14
- Firmware: idk
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, Fanboy's Annoyances, Fanboy's Social Blocking List

#### Setup

I'm using a fresh installation of Adguard.
If the Adguard was previously installed, I tap "Clear data" from Adguard storage app settings before I'm removing it completely.

#### Settings

The default settings for "Global firewall rules" is set to block all connections.
Another customization for the settings are the ones from the first time opening wizard.

#### Issue details

1. I start an internet connection via Wi-Fi of mobile data.
The Adguard is running and is prompting me (via notifications) to allow access to most of the apps that wants to access the internet. I disregard the notifications and I manually allow access to an app via "Quick actions" from "Firewall" or by "Custom firewall rules" and by adding it manually via "+ Add app". Then I'm checking all the "Applied custom rules" for the app.

2. **The issue is not always appearing, but most of the times (about 30% of the times).**
While the app has been added by the step above and the icon is clearly the app I wanted, the app doesn't have internet access while another app has internet access instead (the wrong app that has now access to the internet starts to show notifications).

3. If I have multiple apps added to the "Custom firewall rules" and I want to remove one, most of the times it removes the wrong app. The app I wanted internet access removed still has internet access, while another random app that was removed from the list doesn't.

### Expected Behavior

1. If the app that is allowed, it should have internet access.
2. If the app is removed, it shouldn't have internet access.

### Actual Behavior

1. If an app that is allowed, it doesn't have internet access.
2. If an app is removed, it doesn't have its internet access removed.

### Additional Information

This is a more complete description of the issue #4917

**Comment by ESurina** [comment]
Thank you! Your additions have been added to the issue [#4917](https://github.com/AdguardTeam/AdguardForAndroid/issues/4917).
