### ISSUE TITLE
AdGuard blocks VoLTE (Airtel India)

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#4934]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.1

### Environment

```markdown
- OS: 13
- Device: SM-S911B
- Firmware: n/a
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Try to call over LTE

### Expected Behavior

The call goes over LTE

### Actual Behavior

> В режиме фильтрации автоматический прокси - не работает volte. В режиме локальный VPN всё ок.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Поддержка решила проблему так:

> Пожалуйста, попробуйте в таком случае зайти в AdGuard - Настройки - Основные - Расширенные - Низкоуровневые настройки - Диапазоны IPv4-адресов, исключенные из фильтрации. Там необходимо будет внести следующий IP-адрес - `223.224.123.10/32`.

Клиент подтвердил, что решение помогло. Возможно, стоит внести исключения на нашей стороне.

**Comment by Versty** [comment]
@Eugene-Savenko Sure, the mentioned above CIDR range will be added to the list of exclusions. 

Related issue explaining this problem in detail https://github.com/AdguardTeam/AdguardForAndroid/issues/2550
