### ISSUE TITLE
Oneplus help and feedback present in native settings not working 

### ISSUE THREAD

**Issue by SohanRay** [AdguardTeam/AdguardForAndroid#4937]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.1

### Environment

```markdown
- OS:Android 13
- Device:OnePlus nord 3 
- FirmwareOxygen os 13.1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Disable WebRTC

### Issue Details

Steps to reproduce:
1. Open settings 
2.go to help and feedback
3.tap on compose button 

### Actual Behavior

No Internet connection available 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@SohanRay thanks for the long wait! Is this recurring without AdGuard protection enabled? Could you please clarify the steps to reproduce the problem?

**Comment by maxikuzmin** [comment]
@SohanRay any news?

**Comment by maxikuzmin** [comment]
@SohanRay for the moment, I'm closing this issue. You can reopen the issue in the future if the problem persists
