### ISSUE TITLE
Adguard closing randomly

### ISSUE THREAD

**Issue by Abhirup-99** [AdguardTeam/AdguardForAndroid#4938]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Latest

### Environment

```markdown
- OS:latest
- Device: google pixel 7
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.
It closes randomly.

### Expected Behavior

It shouldn't close.

### Actual Behavior

It closes.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@Abhirup-99 thanks for the long wait! Could you please clarify what exactly you mean by closing the app? Is AdGuard restarting or closing completely? How often does this happen? 
It would be nice to understand the steps to reproduce this case, please clarify the steps to reproduce this case

**Comment by Abhirup-99** [comment]
Adguard is closing and staying closed. It happens quite randomly. Also, an additional thing, the issue started happening after I upgraded to the latest edition.

**Comment by maxikuzmin** [comment]
@Abhirup-99 it would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 4938 number in the subject
specify the exact time when the issue occurred

**Comment by maxikuzmin** [comment]
@Abhirup-99 I got your logs. We will need some time, please wait

**Comment by maxikuzmin** [comment]
@Abhirup-99 unfortunately your logs don't show why the app is closing. Could you please [logcat logs](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) and repeat the problem again?

**Comment by maxikuzmin** [comment]
@Abhirup-99 any news?

**Comment by Abhirup-99** [comment]
@maxikuzmin sorry I missed the reply, would get back to you with a more detailed log shortly.

**Comment by maxikuzmin** [comment]
@Abhirup-99 did you make it? Any difficulties?

**Comment by maxikuzmin** [comment]
@Abhirup-99 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
