### ISSUE TITLE
Protection is not automatically enabled after an update

### ISSUE THREAD

**Issue by roninbz** [AdguardTeam/AdguardForAndroid#4939]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.2.44

### Environment

```markdown
- OS:Android 13
- Device: Samsung A71
- Firmware:4.14.190-25948257-abA715FXXUADWE1 (A715FXXUADWE1)
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Upgrade AdGuard 
2.
3.

### Expected Behavior

Re-enable protection 

### Actual Behavior

Not automatically enableing protection. Only after opening the app. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@roninbz thanks for the long wait! Could you please clarify steps for reproduce? 
I reproduced it and after checking for updates and tapping on "Install updates", the app closed and the update started. The system then asks in a dialog box - "Done" or "Open". If you click "Done", the update will just complete and nothing happens. If you click "Open", the AdGuard application will open and protection will resume automatically

**Comment by maxikuzmin** [comment]
@roninbz for the moment, I'm closing this issue. You can reopen the issue in the future if the problem persists
