### ISSUE TITLE
Ring App on Android logs out

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#4940]
The original issue is here https://github.com/AdguardTeam/AdguardFilters/issues/159350.
The user @bthomas24 can reproduce it with only protection enabled, but I don't see the same on my end.
Perhaps the app should be excluded from filtering.

**Comment by bthomas24** [comment]
![1000008972](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/5bc60ffa-28aa-437e-91b2-8d868f88198d)
![1000008975](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/55e9b8e6-55eb-448c-ad07-da91ed1850d1)
![1000008954](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/4b9133e4-41ce-4fbb-8915-dc64cc907f71)
![1000008952](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/600f8199-8aaa-4013-8b73-510a11acec59)
![1000008953](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/afac9d5d-af9b-4544-81bb-505802a56eb8)

Attaching screenshots shared to the original issue.

**Comment by maxikuzmin** [comment]
@bthomas24 I haven't problems with the Ring app either. 
I see that you have Firewall rules enabled to block the Ring app from accessing the internet? Why do you have them enabled? If you're restricting access with Firewall rules, you won't be able to log in to your account on the Ring app.
Please try disabling Firewall rules and try this again

**Comment by maxikuzmin** [comment]
@bthomas24 any news?

**Comment by bthomas24** [comment]
![Screenshot_20230919-104700](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/ce49f0bf-28dc-4290-ac4f-2aa02fe1bf4b)

**Comment by bthomas24** [comment]
Nonetheless, I'll attempt what you suggested

**Comment by bthomas24** [comment]
Looks like that didn't work. I'm logged out again
![Screenshot_20230919-104919](https://github.com/AdguardTeam/AdguardForAndroid/assets/74256584/736adb93-5344-495e-a225-3aee8e3deb8a)

**Comment by maxikuzmin** [comment]
@bthomas24 thanks for the long wait. What I meant was that the Firewall rules you have configured block access to the internet using the mobile and wifi networks. Do you have these Firewall rules only for the Ring application or are they global rules for all applications? 
In the screenshot, your Firewall rules are still red, which means internet access is blocked. The icons in the Firewall should be green in order for the app to have an internet connection.
As soon as you unblock Internet access by disabling the Firewall rules, the application will work correctly

**Comment by maxikuzmin** [comment]
@bthomas24 any news?

**Comment by bthomas24** [comment]
Still the same experience. Ring continues to log out with everything turned off in AdGuard AND asking the Ring app to bypass AdGuard.

________________________________
Benjamin Thomas
bthomas24.blogspot.com<http://bthomas24.blogspot.com>
________________________________

**Comment by maxikuzmin** [comment]
@bthomas24 could you send a screenshot of the Ring app showing the permissions you disabled?

**Comment by maxikuzmin** [comment]
@bthomas24 any news?

**Comment by maxikuzmin** [comment]
@bthomas24 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
