### ISSUE TITLE
AdGuard Browser Assistant for Android

### ISSUE THREAD

**Issue by hsp1020** [AdguardTeam/AdguardForAndroid#4941]
### Issue Details

If using AdGuard in Windows
AdGuard Browser Assistant is available

Can select elements from the page after clicking on the "Block ad on this website" menu item.
This makes it easy to block ads when don't want to see them while surfing the web.

However, Android does not have an AdGuard browser assistant. 
Therefore, it is difficult to block advertisements that don't want to see while surfing the web.

With features similar to AdGuard, Unicon Pro adblocker supports this feature in an Android browser.
This issue can be a fork of choosing between Unicorn Pro adblocker or AdGuard.

Please add this function.

**Comment by ESurina** [comment]
This request duplicates [#2163](https://github.com/AdguardTeam/AdguardForAndroid/issues/2163)
