### ISSUE TITLE
Google (Discovery Feed) bypass AdGuard

### ISSUE THREAD

**Issue by Birraque** [AdguardTeam/AdguardForAndroid#4944]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.101

### Environment

```markdown
- OS: Android 13 (MIUI 14)
- Device: Poco F3 (Redmi K40); Model: M2012K11AG; alioth
- Firmware: MIUI 14.0.23.4.17.DEV
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open the stock Google app v.14.34.19.28.arm64 from Home (Search Bar), Vault or installed apps list into the Laucher
2. Select the Discovery Tab and scroll down the feed
3. Two or Three Ads per page. AdGuard blocks the Ads contents but the blank square couldn't be removed since last week or Google app update.

### Expected Behavior

AdGuard blocking the Ads contents and removing the blank square as previously. 

### Actual Behavior

AdGuard blocks the Ads contents but the blank square still there since last week or Google app update.

### Screenshots

<details><summary>Screenshot 1:</summary>

![IMG_20230824_005224](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/443c47a9-ef5f-4bc8-8dff-4933ce8c6dd0)
![IMG_20230824_005649](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/7ec1eaa6-4994-4fe7-a74e-f13393caf912)
![IMG_20230824_003910](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/719f3088-6046-463a-b17c-3cd2f7e5b3a1)
![IMG_20230824_004341](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/4e7ddf4d-4d9a-44dc-a46a-14631586912e)
![IMG_20230824_004258](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/b8321d0b-2a86-4e6f-8d00-699701b2cece)
![IMG_20230824_003558](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/89b771e1-d8cb-4737-8093-43ef7156a88f)
![IMG_20230824_003319](https://github.com/AdguardTeam/AdguardForAndroid/assets/44372413/d98b6836-3170-49cf-b639-8bcb34887561)

</details>

### Additional Information

The AdGuard works flawless in the others apps and browser (Chrome Beta). The only issue is the report above (Google App).
How can we handle it?
Let me know if other inputs needed.
Thanks in advance, regards

**Comment by Versty** [comment]
@Birraque Thank you for the report! 
Seems like ad embedding mechanism in Google application has changed in the latest version of application. This issue reproduces on our side as well, and has been discussed with filter developers. 
Unfortunately, Google application is not a browser and can not be filtered with advanced CSS rules, which intended to hide empty spaces.
