### ISSUE TITLE
O2 CZ - VoWifi not worksing

### ISSUE THREAD

**Issue by qquiderr** [AdguardTeam/AdguardForAndroid#4945]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: android 13
- Device: Xiaomi redmi note 10 5G
- Firmware: miui global 14.0.5
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList, EasyList Czech and Slovak, Adblock Warning Removal List, Online Malicious URL Blocklist, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, EasyList Cookie List

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Flash, Turn off Advertising ID, Hide your Referrer from third-parties, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

If i want to make a call using VoWifi with czech O2 mobile operator, adguard blocked it. You have unblocked VoWifi for some mobile operators.
How can i generate log, to find operators addreses? Its possible to unblock VoWifi like other operators?

### Actual Behavior

VoWifi with czech o2 mobile operator not working.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

if i want to use VoWifi i must fully turn off adguard. You have unblocked VoWifi for many operators, but czech O2 its not here. How to get their addresses? I want to send you for unblock.

**Comment by ESurina** [comment]
We know about this problem. You should exclude IP range used by your mobile operator. Here are the details of the solution: https://github.com/AdguardTeam/AdguardForAndroid/issues/2550
