### ISSUE TITLE
AG Not Applying Custom Filters Always

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#4946]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: Android 12
- Device:
- Firmware: MIUI 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open AG and navigate to Settings > Filtering > Filters > Custom filters
2. Add a custom filter using URL ([HaGeZi's Threat Intelligence Feeds DNS Blocklist](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt))
3. Make sure that you enable the custom filter (switch is enabled)
4. Go back to the main page of AG and ensure that all the filters are updated (including the custom filter) & wait for protection to turn on completely.
5. Open Chrome web browser and visit one blocked domain that is included in the custom filter (Ex: 0-day.us)
6. Visit the 'Recent Activity' page and you will observe that there were connections being made to the domain although it was in the blocklist (custom filter).

### Expected Behavior

AG should block ALL connections to the domain that are in the block list of the custom filter.

### Actual Behavior

AG currently only blocks connections sometimes and allows at other times (see screenshot)

### Screenshots

https://ibb.co/947gC8X

### Additional Information

Chrome AG Settings:

Route traffic through AG: Enabled
Filter app content: Enabled
filter HTTPS: Enabled

You can also check with other blocked domains in the list.

**Comment by maxikuzmin** [comment]
@Nzzyme thanks for the long wait! If I understand correctly, this filter is a DNS filter.
You need to add it to: Protection tab -> DNS protection -> DNS filters -> Add DNS filter
Please test this and let me know the result

**Comment by Nzzyme** [comment]
> @Nzzyme thanks for the long wait! If I understand correctly, this filter is a DNS filter. You need to add it to: Protection tab -> DNS protection -> DNS filters -> Add DNS filter Please test this and let me know the result

I did that and it worked as a DNS filter. However, when added as a regular filter, it missed blocking so why did that happen when the syntax of a DNS filter rule is also valid for a regular filter rule? See screenshot.

Example:
||domain.com^

**Comment by maxikuzmin** [comment]
@Nzzyme could you clarify, are you trying to go to the site directly from the address field?
The thing is that if you add a filter to the Ad Blocking section, there is an auto-blocking option in case you need to go to a website blocked in the filter. 
If you want to block requests through the address bar, use the $all, $empty or $document modifier
DNS filtering does not have this feature. Filters added to DNS section will block domains in all cases, auto-blocking is not provided.

**Comment by maxikuzmin** [comment]
@Nzzyme any news?

**Comment by maxikuzmin** [comment]
@Nzzyme for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
