### ISSUE TITLE
Repeated Service Failures: unstable connection

### ISSUE THREAD

**Issue by Paladin-King** [AdguardTeam/AdguardForAndroid#4947]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS:Android 13
- UI: OneUI 5.1 with Microsoft Launcher 6.230601.0.1107840
- Device: Samsung S22 Ultra SM-S908U
- Firmware: Kernel 5.10.136
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, EasyList, Fanboy's Social Blocking List, NoCoin Filter List, Legitimate URL Shortener

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Self-destruction of third-party cookies

### Issue Details

Steps to reproduce:
1. Enable service (no noticed specific interactions)

### Expected Behavior

Always alive service. Configured as "always on" within Android UI for VPN service.

### Actual Behavior

Service randomly fails with no noticed intervals. Requires user interaction for resolution.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Reachout if logs/settings are needed.

**Comment by Paladin-King** [comment]
The AdGuard service repeatedly shuts down without user input throughout day. User intervention required to restart service. Approx.5-8 dropouts per day. The symptoms occur on both on AdGuard Classic and AdGuard VPN. VPN service is unable to find server locations and last connection shows a red lock left of server name.

**Comment by Versty** [comment]
@Paladin-King Hi! 
Let's see if enabling the `Restore VPN automatically` setting will help.
Please enable this option in the low-level settings and let me know the result. 
*Settings tab -> General -> Advanced -> Low-level settings*

**Comment by Paladin-King** [comment]
Thank you for reaching out Diana. I have already enabled this feature prior
to submitting the ticket. It is still currently enabled.

Thank you,
Paladin King

**Comment by Versty** [comment]
@Paladin-King 
Could also be the case with aggressive power saving settings on the device. 
Please make sure that all battery optimisation is disabled for AdGuard application. 
You can find relevant [useful information in the article](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/) from our knowledge base.

**Comment by Versty** [comment]
@Paladin-King If the correct powers settings won't help either, please enable the Watchdog option in the AdGuard application and keep me posted.
*Settings -> General -> Advanced -> Watchdog interval*

**Comment by Paladin-King** [comment]
Thank you for the idea, when I first configured the app I wanted to make
sure that the app was always running. I have verified that the app has been
set as excluded to memory optimization and sleeping/ deep sleeping app
rules for both AdGuard (previously set) and AdGuard VPN (newly set). Power
Saving has been set to not limit CPU usage.

I additionally reviewed the app issue history report and attached the
screenshots of the issues with the dates for additional information on the
case.
I have also enabled Crash Log pop-ups to verify app failure information to
send to you the next time it fails.

I will review AdGuard's behavior with AdGuard VPN also set with never
sleeping app exclusions.

I will reach out tomorrow if the behavior continues.

Paladin King

**Comment by AleksandrKalininAdGuard** [comment]
CRM №812080
[debug.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/12668041/debug.zip)

**Comment by Versty** [comment]
@AleksandrKalininAdGuard Unfortunately, these logs are not enough to identify what exactly went wrong.

**Comment by Versty** [comment]
@Paladin-King To find a root cause, we would like to take a look at the debug logs from your device.
Please follow the steps bellow to submit the logs.

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Wait for the issue to be reproduced, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `4947` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@Paladin-King Hi! 
Have you sent the logs as requested above?

**Comment by Paladin-King** [comment]
Logs are too large to attach for Issue #4947, is there another preferred
method to send logs? Reason: Logs contain past 3 days of data. Yesterday
generated 62mb.

Error occurred within the past 4 hours, exact time is uncertain.

Thank you,
Paladin King

**Comment by Paladin-King** [comment]
Removed AdGuard VPN integrated mode and the issue has become more frequent.
AdGuard requests the VPN to be changed. AdGuard VPN is the only VPN
connected.

Attached are the screenshots.

**Comment by Versty** [comment]
@Paladin-King Any updates?

**Comment by Paladin-King** [comment]
Since having uninstalled and reinstalled the application I have not seen it
re presente the same errors.

Looks like it might've been an app/ system communication issue that is
cleared with reinstalling and uploading previously saved configs.

Looks like we're good to close the case.

Thank you for your efforts,
PaladinKing
