### ISSUE TITLE
GoPro app compatibility with VPN

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#495]
https://play.google.com/store/apps/details?id=com.gopro.smarty

It seems that GoPro app should be added to net exclusions:
http://forum.xda-developers.com/showpost.php?p=66523465&postcount=1077
http://forum.xda-developers.com/showpost.php?p=66531603&postcount=1079
http://forum.xda-developers.com/showpost.php?p=66539594&postcount=1083

**Comment by Revertron** [comment]
Done.
