### ISSUE TITLE
Tooltips in the Firewall have no top border, and blends into the background

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4952]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2 n26

### Environment

```markdown
- OS: Android 13
- Device: pixel 6a
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Tooltips in the Firewall have no top border, and blends into the background

### Actual Behavior

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/8361299/7fc67f16-25e1-4cb8-9194-95b88a6a84d3)

</details>

**Comment by aadmitrevskiy** [comment]
There are no tooltips on this screen anymore
