### ISSUE TITLE
There is no notification about Firewall rules for Android 14 in the notification bar

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4962]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: 10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

Go to Protection tab -> Firewall -> add Global firewall rules or Custom firewall rules -> go to any app with blocked rules from Firewall -> you haven'n internet acces for this app

### Expected Behavior

In the notification bar, after blocked access to the Internet of any application, you can see a notification about the application of a rule from Firewall

### Actual Behavior

There are no notifications in the notification bar about blocked access for any application to which a Firewall rule has been applied

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by artemiv4nov** [comment]
Well, it depends on your system settings for AdGuard notifications. Please turn them on and be happy.

**Comment by artemiv4nov** [comment]
Well, it depends on your system settings for AdGuard notifications. Please turn them on and be happy.
