### ISSUE TITLE
"DNS Protection is disabled" message on the updates screen 

### ISSUE THREAD

**Issue by moonthinkerz** [AdguardTeam/AdguardForAndroid#4963]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: Android 12
- Device: samsung M31
- Firmware:SM-M315F
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

---Third-party filters---, Others

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Block Push API, Block Location API, Block Flash, Turn off Advertising ID, Hide your Referrer from third-parties, Remove X-client-Data header from HTTP request

### Issue Details

**Quick steps to reproduce:** 
1. Enable protection 
2. Enable DNS protection 
3. Go to Protection tab -> DNS Protection -> DNS server 
4. Select AdGuard DNS 
5. Open the Protection tab -> DNS Protection -> DNS filters 
6. Enable general DNS filter switch, disable user rules and each DNS filter in the list  
7. Return to Home tab and check for updates 

**Expected**: DNS Protection is operating 
**Actual result:** DNS Protection is operating, but Updates screen is reporting "DNS Protection is disabled" 

<details><summary>Original steps to reproduce</summary>

1.Enable third party dns providers (NextDns DoT) in parameters
2. Go to DnsFilters options, and i found AdguardDns filters (optimized) still enabled, right so, going to test on this site (https://d3ward.github.io/toolz/adblock.html) got 90 %, nice but internet browsing become slow.
3. So, i deactivate AdGuardDns filters (optimized), and test again and got 100%, and browsing are fast
4. i also check making dns leaktest and without AdguardDns filters (optimized) i have no leaks (NextDns do the job)
5. Problem is when i deactivate AdguardDns filters (optimized), when i check for update, the updater tell me that i ve no DNS filters enabled, but it's not true, NextDns is working.
</details>

### Expected Behavior

Automatically disabled AdguardDns filters (optimizes) when thirdparty dns providers is selected, ans stop warn, that's the DNS is disabled when checking for update

### Actual Behavior

Maybe a conflict between DNS filters if both AdguardDns filters (optimized) and NextDns are activates.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Maybe i'm totally wrong, so let me know please.

**Comment by Versty** [comment]
@moonthinkerz Hi! 
This is a bug for sure. DNS Protection is actually working in this case. 
Will be fixed in the future versions!

**Comment by moonthinkerz** [comment]
@Versty 
Hi,
Ok thanks for your answer, appreciate-it
