### ISSUE TITLE
Protection gets reset while filters are getting updated & not after filters have finished updating

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#4967]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: Android 12
- Device:
- Firmware: MIUI 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open AG after a few hours of recently updating the filters (say after 2 hours)
2. Tap on the check filters icon (top-right semi-circle arrow)
3. All the five categories of updates get checked for the latest updates (AG Version, Content blocker filters, Browsing Security database, DNS filters & Userscripts).
4. You will now notice that while the app is still checking for updates (animation still running), the protection already gets restarted (Check the VPN logo/icon in at the top of the phone Status bar getting disappeared which indicates protection reset)

### Expected Behavior

In the above steps, only after all the five categories of updates have been completely checked and the updates have been downloaded completely, only then the protection should restart once considering all the updates downloaded. That is after all the five categories have a check mark against them, then the protection should reset.

### Actual Behavior

See issue details

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/6959116/31a9cb46-41a1-4815-bd1c-63eea47bdaa7)
</details>

**Comment by maxikuzmin** [comment]
@Nzzyme this is normal. The restart happens because the configuration changes. Once the filters are updated, the protection is restored again. To avoid any leaks, you can configure Kill switch feature

**Comment by maxikuzmin** [comment]
@Nzzyme for the moment, I'm closing this issue

**Comment by Nzzyme** [comment]
> @Nzzyme this is normal. The restart happens because the configuration changes. Once the filters are updated, the protection is restored again. To avoid any leaks, you can configure Kill switch feature

The protection resets multiple times with a delay when several filter types are updated. I would strongly consider making all the updates first and then let AG reset once to apply all the changes.
