### ISSUE TITLE
 Add Fulguris browser to the list of browsers

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#4969]
### Issue Details

As of now, this browser does not seem to be filtered in the free mode

net.slions.fulguris.full.fdroid
net.slions.fulguris.full.playstore

### Proposed solution

Add it, so that non-paid users could have it filtered

**Comment by ESurina** [comment]
We will do it in the next versions!

**Comment by superlex** [comment]
Thanks @ESurina :)
