### ISSUE TITLE
Add com.duckduckgo.mobile.android browser to the list of browsers

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#4970]
### Issue Details

As of now, this browser does not seem to be filtered in the free mode

### Proposed solution

Add it, so that non-paid users could have it filtered

**Comment by ESurina** [comment]
Unfortunately, this browser does not support HTTPS filtering, so we will not be able to add it.

**Comment by superlex** [comment]
@ESurina 
Well, AG could enable content filtering without https, as for Firefox Focus:

![gh](https://github.com/AdguardTeam/AdguardForAndroid/assets/1375223/012aa800-c3ad-4f18-9082-b50830163b95)

If not, thanks anyway!
