### ISSUE TITLE
Request for OpenVPN Support in AdGuard VPN App

### ISSUE THREAD

**Issue by DlgshKurd** [AdguardTeam/AdguardForAndroid#4973]
### Issue Details

Currently, I encounter an issue when attempting to connect to my custom VPN using an OpenVPN configuration file (".ovpn") to access my NAS, etc. . Whenever I initiate the connection, the "AdGuard" app stops functioning.

![Screenshot_20230915_003304_One UI Home](https://github.com/AdguardTeam/AdguardForAndroid/assets/96995162/8274521f-abc8-4ebd-8916-7dc30b47c578)

### Proposed solution

To address this, I would like to propose the implementation of a feature that allows users to seamlessly connect to their custom VPNs using OpenVPN configuration files. This addition would not only improve the app's compatibility but also expand its functionality, catering to a broader user base.

I believe that incorporating OpenVPN support would be a valuable addition and aligns with AdGuard VPN's commitment to providing a comprehensive and user-friendly VPN solution.

**Comment by ESurina** [comment]
Thanks for your suggestion, but unfortunately we don't plan to add this feature yet
