### ISSUE TITLE
Pl Play Wi-Fi calling

### ISSUE THREAD

**Issue by emplos** [AdguardTeam/AdguardForAndroid#4975]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: Android 12
- Device: Samsung M51
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to reproduce:
Use Wi-Fi calling on PL Play

### Expected Behavior

Wi-Fi calling works

### Actual Behavior

Wi-Fi calling doesn't work

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Please add IP 89.108.200.112 do default exclusion list. It is server for Wi-Fi calling of Play on Poland.

**Comment by Versty** [comment]
@emplos Thank you! 
Will be added to the list in the future versions.
