### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForAndroid#4986]
### Issue Details

In the [README](https://github.com/AdguardTeam/AdguardForAndroid#readme), the logo is hard to see when using the dark theme on GitHub. Also, the app's screenshots look too bright with a light background.

<details><summary>Screenshots:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/19418601/dfb0beeb-6ada-4174-ba63-6317917faa03)

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/19418601/079bf7ae-099a-4c60-9332-1ae4b1bb11f0)

</details>

### Proposed solution

You need to add logo and screenshot options for the dark theme.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by Versty** [comment]
@rakleed Done!
