### ISSUE TITLE
$Important does not work as expected

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardForAndroid#4988]
### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Protect from DPI

### Issue Details

In the base filter there is a rule:
> @@||medium.com^$stealth

I want to use the Stealth mode for that domain to bypass DPI so I add:
> ||medium.com^$stealth,important 

But it doesn't work, the log tells the first rule above still takes effect. Is it a bug?

In fact this rule works:
> @@||medium.com^$stealth,badfilter

**Comment by Alex-302** [comment]
`$stealth` rules are unblocking only, for solving problems.
https://adguard.com/kb/general/ad-filtering/create-own-filters/#stealth-modifier
