### ISSUE TITLE
Cannot Add NextDNS 

### ISSUE THREAD

**Issue by Thetromboneman1** [AdguardTeam/AdguardForAndroid#4996]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS:Android 13
- Device:S23 Ultra
- Firmware: 13 with September Security Patch ??
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Disable WebRTC

### Issue Details

Steps to reproduce:
1. Select Protection 
2. Select DNS protection 
3. Select DNS server 
4. Select Add custom server 
5. Sever name type Next or anything ..
6. For server address add the many examples.. all of them time out.. 
I personally have tried tls and https both time out.. even adding the known dns provider fails https://dns.nextdns.io/dns-query

### Expected Behavior

Adding a custom NextDns server.. shouldn't time out 

### Actual Behavior

Times out see screenshot 

### Screenshots

![Screenshot_20230927_172337_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/38571121/054663b8-8628-4eb0-a105-7055e50cc6d8)

![Screenshot_20230927_173912_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/38571121/424bca6e-dac9-4786-bf1b-d6f24af8ee87)

![Screenshot_20230927_173912_AdGuard~2](https://github.com/AdguardTeam/AdguardForAndroid/assets/38571121/e255f4f9-d91c-4cf6-b53c-7b9f114264d0)

**Comment by FadeMind** [comment]
@Thetromboneman1  works for me
![Screenshot_20230929_211827_AdGuard (Średnie)](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/6482c5d6-6034-44c1-bf7a-975d5e6f4adf)
![Screenshot_20230929_211839_AdGuard (Średnie)](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/efebf00b-5cf6-4953-b64a-5bab21b23748)
![Screenshot_20230929_211925_Edge (Średnie)](https://github.com/AdguardTeam/AdguardForAndroid/assets/9846948/399a58a9-31c9-4e7d-b6ab-58d5e1e22ea7)

**Comment by Thetromboneman1** [comment]
Not working for me. Same results as before.
________________________________

**Comment by ESurina** [comment]
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [[devteam@adguard.com](mailto:devteam@adguard.com)](mailto:devteam@adguard.com):
    - mention the `NUMBER` number in the subject
    - specify the exact time when the issue occurred

**Comment by Thetromboneman1** [comment]
This can be closed.. it's working now magically.

Thanks,

Dan
________________________________
