### ISSUE TITLE
Enable HTTPS Filtering On Cromite For Free

### ISSUE THREAD

**Issue by PaidThaFossToBeDaBoss** [AdguardTeam/AdguardForAndroid#4997]
### Issue Details

Bromite is supported by Adguard, but the browser hasn't been updated in almost a year so most people have switched to a fork of it named Cromite. Unfortunately, Adguard doesn't seem to recognize Cromite as a browser so it doesn't offer free HTTPS Filtering. Please enable HTTPS Filtering for free on Cromite as you do on all other browsers.

**Comment by ESurina** [comment]
We will do it in the next versions!

**Comment by PaidThaFossToBeDaBoss** [comment]
> We will do it in the next versions!

That's awesome to hear!
