### ISSUE TITLE
Add ability to set the ttl value

### ISSUE THREAD

**Issue by Michael1297** [AdguardTeam/AdguardForAndroid#4998]
### Issue Details

Операторы сотовой связи с помощью ttl могут ограничивать раздачу интернета на тарифах с безлимитным интернетом. Если на пк эту проблему легко решить с помощью правки реестра, то на смартфоне без рут прав это может вызвать проблему. В гайдах в интернете упоминается 2 приложения для этого. Приложение "Terminal Emulator for Android" с большой вероятностью не сработает на многих устройствах, а приложение "TTL Master" требует рут права.

Я нашел похожую  проблему https://github.com/AdguardTeam/AdguardForAndroid/issues/3094, но в ней упоминается только о раздачи интернета с телефона. Сейчас существует много недорогих usb модемов, которые способны раздавать wifi, но ограничение на раздачу интернета делает эту фичу бесполезной. Было бы неплохо если бы на принимающим устройстве можно было легко сменить ttl чтобы обойти это ограничение.

### Proposed solution

Добавить возможность сменить ttl в качестве опции антитрекинга

**Comment by Versty** [comment]
@Michael1297 Добрый день! 
Мы обсудили ваше предложение с разработчиками. В текущей реализации для соединений фильтрующихся через AdGuard ttl сбрасывается, а значит обработка со стороны клиента уже есть. 
На сторону сервера мы, к сожалению, повлиять не можем, как замечено в #3094.

В данный момент мы сосредоточены на улучшении стабильности работы приложения. Поэтому, в ближайших версиях не планируем доработку для управления ttl. Возможно, мы вернемся к вашему запросу позже.
