### ISSUE TITLE
Improve HTTPS filtering speed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#501]
So, what can we do to improve the speed:

1. Change AES engine to a native implementation
2. Change SHA hashes implementation to native
3. Improve random generation speed

**Comment by Revertron** [comment]
I've implemented Sha256 digest class with native implementation and made some tests on real device.
The results are in:
```
HashTests﹕Starting sha256 tests...
HashTests﹕Elapsed in JNI: 15988 ms
HashTests﹕Hex from JNI: 6d58dd83d958bc6c7602ec9e278f5b0bf461ecba60340be0cd2feadc98f80d2c
HashTests﹕Elapsed in MessageDigest: 5439 ms
HashTests﹕Hex from MessageDigest: 6d58dd83d958bc6c7602ec9e278f5b0bf461ecba60340be0cd2feadc98f80d2c
HashTests﹕Elapsed in BC: 87701 ms
HashTests﹕Hex from BC: 6d58dd83d958bc6c7602ec9e278f5b0bf461ecba60340be0cd2feadc98f80d2c
```

**Comment by Revertron** [comment]
We need to say that our new native AES implementations are great.

**Comment by ameshkov** [comment]
Still slower than without us, guess we'll need to use AES NI to catch up with browser speed.

**Comment by ameshkov** [comment]
Done
