### ISSUE TITLE
The software is not fully supported in Chinese languages and displays other languages such as English

### ISSUE THREAD

**Issue by honeyuee** [AdguardTeam/AdguardForAndroid#5013]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

V4.3 Nightly 5

### Environment

```markdown
- OS:Android 13
- Device:Nubia
- Firmware:NX713J
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard DNS filter, EasyList, EasyList China, EasyPrivacy, AdBlockID, Fanboy's Social Blocking List, Web Annoyances Ultralist, Xfiles, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, CJX's Annoyances List, xinggsf

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API, Hide your IP address

### Issue Details

Steps to reproduce:
1.In the protection setting options, many detailed descriptions are displayed in English.
![Screenshot_20231009_172219](https://github.com/AdguardTeam/AdguardForAndroid/assets/53884928/846bc6a3-2451-4b2a-b83c-e3927115a7ea)
![Screenshot_20231009_173111](https://github.com/AdguardTeam/AdguardForAndroid/assets/53884928/2fce2a09-b7b9-4afe-9072-1e31387f91ea)

2.Of course, the same situation appears in the settings tab.
![Screenshot_20231009_172234](https://github.com/AdguardTeam/AdguardForAndroid/assets/53884928/42afcc48-1ff5-4836-acee-2e42ed7dca1d)

3.From time to time, the software also stops working unexpectedly, even in the most recently updated version.

### Actual Behavior

In the protection setting options, many detailed descriptions are displayed in English.Of course, the same situation appears in the settings tab.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by honeyuee** [comment]
> @honeyuee yes, we plan to finalize the translations of the app in upcoming updates. Could you clarify on the third point? How often do you have the app stop working? What do you mean by that? Does the protection get disabled or does the app stop working completely and close? Are there steps for the problem to recur?

Then I am really looking forward to the new version, I hope that the new version can improve the speed of opening and the restart speed of the software after adding rules. I can't reproduce the situation where the app stops working, because it also appears suddenly in my phone, with a low frequency, but it is really a headache. @maxikuzmin

**Comment by maxikuzmin** [comment]
@honeyuee please enable debug logs in the settings (Go to Protection tab -> General -> Advanced -> Logging level -> Debug). It would be nice to upload logs when the problem with the application stopping working is repeated. Also, please describe exactly what the problem looks like: does the protection get disabled or does the application stop working completely and close?

**Comment by honeyuee** [comment]
> @honeyuee please enable debug logs in the settings (Go to Protection tab -> General -> Advanced -> Logging level -> Debug). It would be nice to upload logs when the problem with the application stopping working is repeated. Also, please describe exactly what the problem looks like: does the protection get disabled or does the application stop working completely and close?
> 
> 
> 

This sudden stop is accidental, and unfortunately there is no way to reproduce it. However, when I update to the latest Nightly8 version, there will be a state that was originally running, but the notification bar has been restarting protection, and then the switch button has been turned on, and the protection cannot be performed.
![IMG_20231012_075003.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/53884928/f7c3337f-24a3-46d5-a327-5e77115da3fb)

![Screenshot_20231012_074920.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/53884928/709d1d21-7b81-4ceb-b853-db8e949fbb62)

If the work log of the software, if necessary, I can directly feedback in the APP by submitting errors.

**Comment by maxikuzmin** [comment]
@honeyuee could you be more specific, is this still recurring? Were you able to get the logs?

**Comment by maxikuzmin** [comment]
@honeyuee  for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
