### ISSUE TITLE
Add application filter by "Route traffic through AdGuard"

### ISSUE THREAD

**Issue by Peter-maximus** [AdguardTeam/AdguardForAndroid#5014]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1.101

### Environment

```markdown
- OS:Android 10
- Device: OnePlus
```

### Root access

- [ ] Yes, I have it.

### Issue Details

In Adguard 4.x in app list (tab app management) there is **no clear visibility which apps are excluded from filtering**.
You have to click each and every app in the list to open new window to show its filtering state.

In Adguard 3.x there was clear visibility of filtering state of particular app by small colorful icons near the app name. So to find excluded apps it was enough to scroll down the list of apps and find the apps with red icons.

### Expected Behavior

Please add back the previous feature or even better **enable filtering or at least sorting of apps in the app management list by its state** (excluded / included in filtering)

### Actual Behavior

See issue details.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@Peter-maximus in version 4 you can conveniently see filtered apps in the "HTTPS-filtered apps" list.
Just go to Settings tab -> Filtering -> Network -> HTTPS filtering -> HTTPS-filtered apps

**Comment by Peter-maximus** [comment]
Unfortunately it shows just state of HTTPS filtering for apps (thx for this hint to HTTPS filtering "secret" menu)
However **I need to see the state of AdGuard routing for each and every app** ("Route traffic through AdGuard checkbox").

Is anywhere such a "secret menu" for this state?

If not, please add back this view from v3.x or even better please enable filtering or at least sorting of apps in the app management list by its state (route traffic through AdGuard disabled / enabled)

**Comment by Peter-maximus** [comment]
any update please?

**Comment by maxikuzmin** [comment]
@Peter-maximus thanks for the long wait. We have changed the status of the issue to "Feature request", let's see how many likes this issue gets

**Comment by Peter-maximus** [comment]
apologize, but such a feature is crucial…

i believe it is very important to know which apps are routed through AdGuard and which not…

This was without any notice removed in the latest version, which should be better, not worse than previous one.

**Comment by artemiv4nov** [comment]
@Peter-maximus Hi! Try the following app path: Protection -> Ad blocking -> Filtered apps (or something like that). It's related to filtering (ad blocking) screen.

**Comment by Peter-maximus** [comment]
apologize, but i am talking about something completely different.

some apps doesn't work correctly if routed through adguard even if they are whitelisted for adblocking.

please read complete description of the issue above.

let me know if more info is needed.

thx a lot.

**Comment by artemiv4nov** [comment]
Ah, so you want not just an ad blocking filtering state but the routing state (complete filtering).
Well, we are working on app management improvements just like you imagine: maybe represented icons, maybe something else. Please follow the task updates.

**Comment by Peter-maximus** [comment]
the cleanest and easiest way would be to implement filter to app list view (e.g. by routing state). this way you don't need to add any addtional icons.

**Comment by aleclerc7** [comment]
+1
It would be nice indeed to have a color or icon to mark those apps that have special settings, and those that are completely bypassing the filter because altogether disabled. This would make it easy to see at a glance which app has specific behavior or is out of the filters. Thank you very much!

**Comment by PavelParkhomenko** [comment]
> Unfortunately it shows just state of HTTPS filtering for apps (thx for this hint to HTTPS filtering "secret" menu)
> However I need to see the state of AdGuard routing for each and every app ("Route traffic through AdGuard checkbox").
> 
> Is anywhere such a "secret menu" for this state?

Hello! Could you kindly review the menu by navigating through: Settings -> Filtering -> Network -> Proxy -> Apps operating through proxy? It appears to match your description precisely.

Additionally, we're actively exploring the possibility of introducing indicators for the status of individual apps within the "App management" section, as per your original suggestion.
