### ISSUE TITLE
Typo in Ad Blocking

### ISSUE THREAD

**Issue by Madagarian** [AdguardTeam/AdguardForAndroid#5022]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 Nightly 83

### Environment

```markdown
- OS: Android 13
- Device: Galaxy Fold 3
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Protection tab
2. Ad Blocking
3. Other ad blocking filters

### Expected Behavior

It should say ad, not ab.

### Actual Behavior

Screen shows:

 //*
 Other ab blocking filters

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@Madagarian Hi! 
This typo is already fixed, please update to the latest nightly version.
