### ISSUE TITLE
The Adguard notification can be swiped away on Android 14

### ISSUE THREAD

**Issue by seirdotexe** [AdguardTeam/AdguardForAndroid#5027]
As titled. This started to happen on Android 14 with Pixel 7 Pro. I'm using Adguard 4.1.
![](https://i.ibb.co/3S4hcBB/Screenshot-20231013-150923.png)

**Comment by seirdotexe** [comment]
No thanks, I'd rather just wait it out

**Comment by Versty** [comment]
@seirdotexe Please, keep this issue open.
We will improve the behaviour of notification in the future versions.

**Comment by seirdotexe** [comment]
Small enhancement: the notification reappears by itself

**Comment by sebastianjena** [comment]
@seirdotexe are you able to install 4.2 version on Pixel? I'm unable to install it on my 7 Pro Android 14

**Comment by seirdotexe** [comment]
> @seirdotexe are you able to install 4.2 version on Pixel? I'm unable to install it on my 7 Pro Android 14

It says I got an update to 4.2
![Screenshot_20231023-151126.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/80536518/adf4dde8-c341-42ad-8e34-7ed1b407c7a0)

Then I update
![Screenshot_20231023-151133.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/80536518/4b0473b4-59e5-4d0a-8047-c710696d0409)

![Screenshot_20231023-151138.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/80536518/ea75cbe2-ccf3-42c3-a453-bc24badabc35)

But then I'm still on 4.1
![Screenshot_20231023-151151.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/80536518/103fcc35-9245-44a4-ab41-f872185034b8)

@Versty seems like there's much more going on here 🫡

**Comment by sebastianjena** [comment]
So looks like it might be related to 64bit support -> https://github.com/AdguardTeam/AdguardForAndroid/issues/5041

**Comment by Versty** [comment]
@seirdotexe Thank you to keep us updated.

**Comment by seirdotexe** [comment]
@Versty Do you have an idea when this gets fixed? It's not in 4.3, and it's very annoying

**Comment by seirdotexe** [comment]
I can confirm that it's still an issue on 4.3

**Comment by Proxwian** [comment]
Actually, that's [intended behaviour](https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications) starts from android 14
