### ISSUE TITLE
AdGuard Protection Do not block ads when restarting

### ISSUE THREAD

**Issue by NoName926** [AdguardTeam/AdguardForAndroid#5030]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2 Beta 2

### Environment

```markdown
- OS: Android 13
- Device: Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Wait for the Adguard filter to be updated automatically.
2.When Protection is restarting appears, as illustrated below, navigate to the site where the advertisement appears.

### Actual Behavior

AdGuard Protection Restart does not block ads.

### Screenshots

![Screenshot_20231015_153525_Gallery](https://github.com/AdguardTeam/AdguardForAndroid/assets/99063049/174c7085-29c3-4325-869c-bc486211aeda)
![Screenshot_20231015_153457_Gallery](https://github.com/AdguardTeam/AdguardForAndroid/assets/99063049/673b9108-e018-4b02-8a47-f2444ef09634)

**Comment by Versty** [comment]
@NoName926 Hi! 
After updating the filters, the protection needs to be restarted to apply the new changes. 
At the moment the protection restarts, the rules do not apply. Therefore, this behaviour is expected. 

To browse ad-free, please wait until the protection restart is complete.
