### ISSUE TITLE
Can't hide an element in AdGuardForAndroid 4.3

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/AdguardForAndroid#5036]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS:Android 13
- Device:OnePlus Ace 2V
- Firmware:ColorOS 13.1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1.Open https://m.baidu.com/video/page?pd=video_page&nid=11315236961512985663&sign=4822683579608048132&word=%E4%BA%8C%E7%BA%A7%E8%B7%AF%E7%94%B1&oword=%E4%BA%8C%E7%BA%A7%E8%B7%AF%E7%94%B1&atn=index&frsrcid=48304&ext=%7B%22jsy%22%3A1%7D&top=%7B%22sfhs%22%3A1%2C%22_hold%22%3A2%7D&fr0=a&fr1=a&ms=1&lid=7534453422610204780&referlid=7534453422610204780&frorder=7&_t=1697546294344

### Expected Behavior

Ads be hidden

### Actual Behavior

Ads aren't hidden

### Screenshots

![Screenshot_2023-10-17-20-02-04-97_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/69903376/147fea8d-a151-48f5-aa9f-401f1bb5209c)

### Additional Information

This issue only appears on AdGuard with version numbers larger than 3.6.

**Comment by ESurina** [comment]
Please, write about this problem through the application:
Go to Settings -> Support -> Report incorrect blocking.

**Comment by Karmylr** [comment]
> Please, write about this problem through the application: Go to Settings -> Support -> Report incorrect blocking.

It's not a filter problem.
