### ISSUE TITLE
Add com.openbank to https exclusions

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#504]
com.openbank [link](https://play.google.com/store/apps/details?id=com.openbank)
"сразу после ввода кода доступа дли использования проги.
текст "ошибка подключения к серверу (#1)"
Log - QSQ-755-27686

**Comment by ameshkov** [comment]
@Revertron or maybe to net exclusions?

**Comment by Revertron** [comment]
Added to net_exclusions
