### ISSUE TITLE
AdGuard for Android Nightly restarts protection when using Instagram.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#5040]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard Nightly Version 4.3 Nightly 15

### Environment

```markdown
- OS:Android 13
- Device: Samsung Galaxy S22 Ultra 5G
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. AdGuard Adblocker & AdGuard VPN is enabled.
2. When opening Instagram to use it, then once done with it when closing the app tab, Adguard protection restarts. 
3. I have to open Adgaurd in order for it to fully connect again. 

### Expected Behavior

Should work without disabling adguard Adblocker when using Instagram. 

### Actual Behavior

Instagram is causing Adguard Adblocker to restart protection. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Thus, it has happened to me 3 times now, and I've just realized it happens when using Instagram.

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [[devteam@adguard.com](mailto:devteam@adguard.com)](mailto:devteam@adguard.com):
    - mention the `NUMBER` number in the subject
    - specify the exact time when the issue occurred

**Comment by Batman2814** [comment]
I'll try and reproduce the issue and send you guys the logs. Could you give me some time because? I have been on the Nighly Version since Version 4.0. So from Version 4.0 to now, version 4.3, as I said, happened three times, so I'll send the logs when I catch it or if I can't reproduce it, it was either fixed already in an update, and I'll close the issue myself.

**Comment by Batman2814** [comment]
I'm going to close this issue. Can't reproduce it anymore. Might be fixed in a Nightly update.
