### ISSUE TITLE
Can't upgrade from 4.2b2 to 4.2 stable (Android 14, Google Pixel 7 Pro)

### ISSUE THREAD

**Issue by sebastianjena** [AdguardTeam/AdguardForAndroid#5041]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2 Beta 2

### Environment

```markdown
- OS: Android
- Device: Pixel 7 Pro
- Firmware: 14 (October)
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. have 4.2 Beta 2 installed
2. try to update to stable 4.2 from the app updater

### Expected Behavior

Adguard gets updated

### Actual Behavior

Error while installing: something about application not installed because package seems to be incorrect. I can guess that's 64bit arch support missing, PIxel 7 Pro A14 supports only those

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by antek821** [comment]
I also cannot update from the stable version 4.1.

**Comment by superlex** [comment]
Yep, tried both upgrade that fresh install.
It looks like there is a issue in apk downloaded from release channel.

**Comment by szhu25** [comment]
Same. Tried to fresh install and now I got AdGuard v4.1 instead of v4.2, and the in app update kept telling me to update to v4.2, despite the APK downloaded is v4.1.

**Comment by sssh7710** [comment]
The official website can't be updated either

**Comment by sssh7710** [comment]
It's Android 13, oneui5.1

**Comment by sssh7710** [comment]
Everything's fine now

**Comment by sebastianjena** [comment]
Can confirm, looks like it wasn't 64bit after all, just broken .apk maybe?

**Comment by superlex** [comment]
Maybe 🤷🏻‍♂️
Btw, now it's ok also for me 😊

**Comment by Versty** [comment]
@sebastianjena Hi! 
So did the app eventually updated correctly on your device?

**Comment by sebastianjena** [comment]
@Versty yeah, I guess the .apk was corrupted on the beginning but was replaced a while after
