### ISSUE TITLE
Rules issue

### ISSUE THREAD

**Issue by Dusk0531** [AdguardTeam/AdguardForAndroid#5046]
### Issue Details

Unable to view domain names blocked by a certain blocking rule
There's no way to do a rule comparison to see how many of the same blocking rules there are so I can't tell if this rule is right for me.

### Proposed solution

Add the function of viewing corresponding intercepted domain names based on rules. For example, which domain names are intercepted by rule 1 and which domain names are intercepted by rule 2. You can compare the rules to see how many identical domain names are blocked by the two rules and how many different blocked domain names there are.

### Alternative solution

You can add the same gong n as adguardhome Use domain name to detect which rule is blocked

**Comment by ESurina** [comment]
Do you mean User rules?

**Comment by Dusk0531** [comment]
> Do you mean User rules?

yes

**Comment by Dusk0531** [comment]
> Do you mean User rules?
It would be better if you could compare it with the built-in rules. I'm in mainland China and your rules may not apply to me.

**Comment by Dusk0531** [comment]
> Do you mean User rules?
It would be better if you could compare it with the built-in rules. I'm in mainland China and your rules may not apply to me.

**Comment by ESurina** [comment]
What do you mean by built-in rules? Filters?

**Comment by Dusk0531** [comment]
> What do you mean by built-in rules? Filters?

Yes, it is the default rule of adguard

**Comment by Dusk0531** [comment]
> What do you mean by built-in rules? Filters?

Yes, it is the default rule of adguard

**Comment by ESurina** [comment]
You can view domain names blocked by a rule:
go to Settings -> Filtering -> Filters.
Choose here any set and then a certain filter and tap on Source.

**Comment by ESurina** [comment]
This is what you need?
