### ISSUE TITLE
Couldn't connect to private DNS

### ISSUE THREAD

**Issue by HattieJosh** [AdguardTeam/AdguardForAndroid#5047]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.10

### Environment

```markdown
- OS: Android 13
- Device: Samsung
- Firmware:N/A
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
Connect to dns.adguard-dns.com or dns-family.adguard.com or unfiltered.adguard-dns.com in DNS settings 

### Expected Behavior

Connection to the DNS server

### Actual Behavior

"Couldn't connect to private DNS" error notification 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I am attempting to use the public DNS server for Adguard on my Android phone but it will not connect on any server

**Comment by HattieJosh** [comment]
One hour later and it is working again

**Comment by Versty** [comment]
@HattieJosh Hi! 
Seems like you have faced temporary problems on the server side. 
Glad to hear that this is fixed now.
