### ISSUE TITLE
Improve the "Battery optimization" snack behaviour 

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#5048]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2

### Environment

```markdown
- OS: Android 13
- Device: Samsung S23 Ultra
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Do updates check.

### Expected Behavior

No warning for users who already disabled battery optimization for AG.

### Actual Behavior

A warning which lets users misunderstand there is something wrong with filters updates.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://i.imgur.com/sVKzxy8.jpg)

</details>

**Comment by ameshkov** [comment]
Why do we need this snack in general? I assume that's due to the job manager being affected by battery optimization, but I don't like the current solution, we basically say that something is wrong to every user.

We should make it smarter and only show the snack when we see that the filters are seriously out of sync (i.e. the filters update period is 24 hours, but according to our data they were updated 48+ hours ago).

**Comment by ameshkov** [comment]
Also, I don't like the word "properly". It's misleading, the user may think that the filters may be corrupted. We need to change the wording and make it clear that this is about filters being AUTO-updated not often enough.

**Comment by Versty** [comment]
It is important to note that we have this snack on both "Updates" and "App and filter updates" screens. Therefore, we should change the snack behaviour in both places. 

Also, the text on the snack is not fully visible for some languages. 

<details><summary>French version</summary>

<p align="left">
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/107266340/55d629c9-3054-48d1-8313-0343ef135812" width="300" >
</p>


</details>
