### ISSUE TITLE
HTTP/3 for DNS-over-HTTPS breaks AdGuard VPN

### ISSUE THREAD

**Issue by darkeyes84** [AdguardTeam/AdguardForAndroid#5049]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2 for AdGuard, 2.5.6 AdGuard VPN

### Environment

```markdown
- OS: Android 14
- Device: Pixel 7 Pro
- Firmware: ?
```

### Root access

- [x] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Enable HTTP/3 for DNS-over-HTTPS upstreams in the low-level settings
2. Connect AdGuard VPN (compatibility mode with AdGuard)

### Expected Behavior

Connection to the Internet should work as usual.

### Actual Behavior

There is no Internet connection. Disabling HTTP/3 for DNS-over-HTTPS fixes the connection.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@darkeyes84 Hi! 
I apologize for the long wait, this issue fell off our radar. 
Does the issue still reproduce with latest AdGuard (4.3.1) and AdGuard VPN (2.7) versions?
