### ISSUE TITLE
Unstable foreground detection code on Android 5.1

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#505]
Originally from this thread:
https://forum.adguard.com/index.php?threads/9859

**Comment by Revertron** [comment]
Dummy intent will be thrown on 5.0 and older versions of Android.

**Comment by ameshkov** [comment]
@Revertron that's another issue:)

**Comment by Revertron** [comment]
Hm, I'm unable to repeat this behavior on Skype on my Android 5.1.1.

**Comment by ameshkov** [comment]
It seems that we have the same issue in v4.4.

@gshumihin please test it on all Android versions.

**Comment by gshumihin** [comment]
Tested with next Android versions:

- 4.4
- 5.1
- 6.0.1
- 7.0
