### ISSUE TITLE
With DNS Filter - what should Android Private DNS be set to?

### ISSUE THREAD

**Issue by Utini2000** [AdguardTeam/AdguardForAndroid#5052]
### Issue Details

When enabling a DNS in AdGuard, what should the private DNS option in Android be set to?
Disabled, Automatic, 127.0.0.1,....?
I am rooted and use automated proxy mode.

### Proposed solution

Make clear explenation / guidance

**Comment by Versty** [comment]
@Utini2000 Hi! 
If you wish to use DNS protection in AdGuard, disable the Private DNS in the system settings for better experience.

**Comment by Utini2000** [comment]
> @Utini2000 Hi! If you wish to use DNS protection in AdGuard, please disable Private DNS in the system settings for better experience.

Hi @Versty , and if I then disable the usage of adguard for an app (as in not filtering and not passing through adguard by changing this in the app management within adguard) will th app still use the configured DNS server in adguard or will it then rely on the android settings (which would be disabled private dns)?
