### ISSUE TITLE
Low level settings MTU size

### ISSUE THREAD

**Issue by XAlboX** [AdguardTeam/AdguardForAndroid#5053]
### Issue Details

The current MTU value of 9000 makes pages slower to load.

### Proposed solution

Changing the MTU size from 9000 to 1500 could speed up the loading of web pages and images 🤔

**Comment by ESurina** [comment]
We are not planning to change MTU value. In the case of a local VPN, the higher the MTU value, the better.

**Comment by XAlboX** [comment]
It's not exactly like that...
And anyway Adguard site says to keep it between 1500 and 1900 💀.
https://adguard.com/kb/adguard-for-android/solving-problems/low-level-settings/#mtu
An MTU size of 1500 makes it more consistent.

**Comment by sfionov** [comment]
This is MTU of Local VPN, and Local VPN has no relation to physical network links.

**Comment by XAlboX** [comment]
A bigger MTU should be faster but if a user has slow internet (in my case 12Mbps, I don't know about faster internet networks) for some reason the images load slower...I bring this up as an example because it's the easiest thing to notice.
I would like to understand why 😐
Is it due to packet loss/fragmentation or something else ? 
I also read things in this post https://www.reddit.com/r/Adguard/comments/lhm8hw/i_think_i_might_have_found_the_reason_why_adguard/ and it seems I'm not the only one who thinks 1500 is better...although it's an old question, it's still relevant.
