### ISSUE TITLE
Add us.spotco.fennec_dos to the list of browsers

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#5054]
### Issue Details

As of now, this browser does not seem to be filtered in the free mode

`us.spotco.fennec_dos`

> [MULL] is a privacy oriented and deblobbed web browser based on Mozilla technology. It enables many features upstreamed by the [Tor uplift project](https://wiki.mozilla.org/Security/Tor_Uplift) using preferences from the [arkenfox-user.js project](https://github.com/arkenfox/user.js). It is compiled from source and proprietary blobs are removed using scripts by Relan

https://divestos.org/pages/our_apps

### Proposed solution

Add it, so that non-paid users could have it filtered

**Comment by ESurina** [comment]
Unfortunately we will not add this browser due to the fact that it does not support HTTPS-filtering.

**Comment by SkewedZeppelin** [comment]
@ESurina 
It does and I document how to enable it for users that want it: https://divestos.org/pages/broken#mull
> Mull has strict certificate pinning. If you are using a proxy or VPN that does HTTPS manipulation you'll encounter a "Secure Connection Failed" error. Navigate to about:config and change security.cert_pinning.enforcement_level from 2 to 1, this is however a security and privacy risk.

> Mull does not trust user-added CA certificates, you can optionally enable them at your own extreme risk: Settings > About Mull > Tap Mull logo until debug settings are enabled > back a menu > Secret Settings > Use third party CA certificates > Enabled, this is however a security and privacy risk.

**Comment by superlex** [comment]
> Mull does not trust user-added CA certificates, you can optionally enable them at your own extreme risk: Settings > About Mull > Tap Mull logo until debug settings are enabled > back a menu > Secret Settings > Use third party CA certificates > Enabled, this is however a security and privacy risk.

I confirm, this is the same process you do for Firefox, and it works:
![dd](https://github.com/AdguardTeam/AdguardForAndroid/assets/1375223/a3315698-5956-4633-b5f1-fdd2b5b8cb11)
