### ISSUE TITLE
Splash and setup wizard have white backgrounds when dark theme is enabled

### ISSUE THREAD

**Issue by Daviteusz** [AdguardTeam/AdguardForAndroid#5055]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.69 / 4.3 Nightly 21

### Environment

```markdown
- OS: Android 13
- Device: OnePlus 8T
- Firmware: Custom AOSP
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Set dark theme in system
2. Start Adguard
3. See the splash, welcome and configuration screens.

### Expected Behavior

Dark theme -> dark splash screen, dark setup wizard screens
White theme -> white splash screen, white setup wizard screens

### Actual Behavior

Dark theme -> white splash screens, white setup wizard screens, dark ad premium screens.
White theme -> white splash screens, white setup wizard screens, white ad premium screens.

### Additional Information

For me, the splash background should follow dark or white theme separately, because it is the first screen you see and you see it almost every time you launch Adguard.
I hope this will finally be fixed.

Related issues:
- #4928
- #4464
- #2657

### Screenshots

Dark theme in system enabled
Dark theme in apps enabled
<details><summary>Splash screen</summary>
Actual:
<img src=https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/b670697d-57c6-4141-8fdc-ad45a0a5f521 width=20%>
Should be:
<img src=https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/d293d571-e9ee-40f8-8780-abb88b268dfe width=20%>

</details>
<details><summary>First configuration screen - Adguard vs Adguard VPN</summary>

<img src=https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/e1e32ccf-a81b-4940-9969-b05bb7b25a97 width=20%>

<img src=https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/93e5aad2-e2cf-4583-915c-af3d176a9f78 width=20%>

</details>
<details><summary>Premium AD screen</summary>

<img src=https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/b9b03a66-26dc-4419-bf2d-604684791ee3 width=20%>

</details>
<details><summary>Setup wizard screens</summary>

<img src=https://github.com/AdguardTeam/AdguardForAndroid/assets/11527277/780650b5-3872-4d83-8d7c-4741d6e700b5 width=20%>

</detalis>

**Comment by ESurina** [comment]
We will fix it in future versions!
