### ISSUE TITLE
Browser excluded and ads still being blocked?

### ISSUE THREAD

**Issue by Utini2000** [AdguardTeam/AdguardForAndroid#5057]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2

### Environment

```markdown
- OS: Android 14
- Device: Pixel 8 Pro
- Firmware: Latest Google.October build
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies

### Issue Details

Steps to reproduce:
1. I have my browser (Firefox) excluded from AdGuard
2. This means it isn't routed through adguard / proxy-mode
3. I use uBlock with AdGuard + Easylist filterlist
4. AdGuard still registers (and most likely block) 13k requests per day. 
5. It cant tell me from which app thise requests come from
6. Probably because it comes from an app (Firefox) that is excluded?

### Expected Behavior

AdGuard shouldn't check / register any requests from Firefox when excluded.

### Actual Behavior

See above

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Utini2000** [comment]
Oh and here is a screenshot.
![Uploading Screenshot_20231101-214459.png…]()

**Comment by Utini2000** [comment]
![Screenshot_20231101-214459](https://github.com/AdguardTeam/AdguardForAndroid/assets/14877663/5ac01d9b-f2d5-4175-aa22-d21941ed4e67)

**Comment by Utini2000** [comment]
Additionally it means that the traffic from Firefox gets filtered (by DNS Filter) eventhough Firefox is excluded from AdGuard!

**Comment by ESurina** [comment]
> It cant tell me from which app thise requests come from
You can go to Statistics tab and see filtered apps or go to Recent activity and see filtered requests. 
You can also see if Firefox is filtering by adding user rule and checking if it applies or going to adguard.com/test.html

**Comment by Utini2000** [comment]
Filtered Apps: 
Won't show firefox because its excluded
Recent activity shows the filtered requests which come from DNS

So my guessing is that firefox is excluded from AdGuard (and not passed through AdGuard) but the DNS process is still being processed and filtered since that is a system wide process.

That means, even though I excluded Firefox, its requests will still go through AdGuard due to DNS?
And there is no way around it?
But this also means that the banking apps or anything on your adguard whitelist will all still go through adGuard (passively via DNS)?

**Comment by ESurina** [comment]
Try to add a custom DNS rule (for example, block any website) and check if it applies. This way you will see if Firefox's requests go through DNS.

**Comment by ESurina** [comment]
And if the list is enabled, does your rule apply? You can add a rule ||example.org^ and go to example.org and see if it's blocked

**Comment by Utini2000** [comment]
@ESurina Yes, when the list is enabled, it will apply the rule.

**Comment by ESurina** [comment]
How did you exclude Firefox? In what part of the settings?

**Comment by Utini2000** [comment]
@ESurina see screenshot.
Basically in AdGuard search for the app Firefox and disable all options.
Yet when opening a website I can see the DNS requests in adguards "recent activity" meaning it still routes through adguard.
![Screenshot_20231226-203556](https://github.com/AdguardTeam/AdguardForAndroid/assets/14877663/e715f76b-ecc2-482f-a575-25d0132de3c7)

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5057` number in the subject
    - specify the exact time when the issue occurred

**Comment by Utini2000** [comment]
@ESurina 

I just sent the logs but funnily I couldn't replicate the blocking of the custom DNS filter rules this time..how every Firefox traffic is still routes through adguard as it can be seen in the recent activity. 

I enabled advanced logging
Then enabled DNS filtering with 2 rules to block d2jsp.org and bestmail.ws
I opened those websites in my browser (they weren't blocked this time)
I also opened my banking apps easybank and DKB

While the custom DNS filter rules didn't apply this time (it did twice in the past when I tested it) the requests from Firefox and my banking apps were still routes through adguard as they can be seen in the "recent activity".

I will try to reproduce another log where the custom DNS filter rules will be applied even though Firefox is excluded as explained in the GitHub issue.

**Comment by Utini2000** [comment]
@ESurina 

I just sent another log.

this time I was able to reproduce the blocking of d2jsp.org with a custom rule in DNS filters although Firefox is excluded from AdGuard as described in the issue.

Bestmail.ws wasn't blocked though.

I enabled advanced logging, tried the websites, exported logs..all within the same 2-3 minutes

**Comment by ESurina** [comment]
Could you please specify the exact time when the issue occurred?

**Comment by Utini2000** [comment]
@AleksandrKalininAdGuard I made the logs just a few minutes (maybe 1-3 minutes) after the problem occured. Does that help?

**Comment by ESurina** [comment]
Yes, thank you

**Comment by Utini2000** [comment]
@ESurina hi, any news on this or anything else I can provide?

It is a huge privacy issue when the excluded apps are still being filtered.
AdGuard advertises with banking apps and other privacy required apps not to be fiddled with (e.g. with the https MITM attack/process) when in reality it does.

Additionally (and that is my main use case) I have some very very traffic/request heavy apps excluded because their traffic is no concern to ads/trackers/AdGuard and I don't want to waste system resources by AdGuard filtering them for nothing.

**Comment by ESurina** [comment]
We are investigating this issue. Please tell me if your DNS rule is applied in Firefox if you enable local VPN mode (Settings-> Filtering-> Network-> Routing mode)?

**Comment by Utini2000** [comment]
Okay, by trying to replicate this I managed to find all kind of weird stuff happening. I used my two personal domains which are now named "domain1" and "domain2".

First I tried it in Automatic Proxy Mode:
1. DNS Protection -> DNS Filter -> User Filters -> add "||domain1.com^" and also for testing add "||domain2.com^"
2. Enable DNS Filters
3. Website can be accessed via browser (which is excluded)
4. Domain can also be pinged via termux (which is NOT excluded)

Then I tried this in VPN Mode. Same thing happening.
I tried again in Automatic Proxy Mode. Same thing happening.
I tried again in VPN Mode and suddenly both domains could be opened in the browser but not be pinged in termux.
I tried again in Automatic Proxy Mode and suddenly domain 1 could be opened in browser and pinged but domain 2 was blocked. 
I tried again in VPN Mode and suddenly both domains could be pinged again.

So what ever I do, it randomly changes and I have no idea why and how it changes. 
I disabled adguard before changing from VPN to proxy mode (or vice versa) and the enabled adguard again.

Maybe I need to flush the DNS cache? If so, how can I do that? 

Anyway, in the last 7 days adguard logged a total of 37k requests.
It only shows about 19k requests when sorting the requests by apps because firefox is not listed (as it is excluded).
So the remaining 18k requests (which then all must come from the browser) were still tracked by adguard.
Maybe it doesn't track/filter all requests and maybe that is why my try to replicate the problem always shows different results?

**Comment by Utini2000** [comment]
@ESurina I have now also enabled nextdns logging. This could maybe (over time) give a comparison of the requests tracked by adguard app vs nextdns. 

If I calculate adguard requests (minus the amount of requests blocked by adguard) I should get a value that is a low lower than what nextdns is logging.
If however, both amount of requests are close to the same, then this again indicates that adguard is also registering the requests of the excluded browser.

But I think there is enough "proof" already that there is a problem with adguard app. And sadly I believe the nextdns logging won't help fixing the issue?

**Comment by Utini2000** [comment]
@ESurina 24 hours with AdGuard and NextDNS as resolver. I use Firefox with uBlock. All three adblockers have the same filters (NextDNS, AdGuard and uBlock).

The last 24h:
AdGuard reports: 5800 requests (130 blocked)
NextDNS reports: 1800 requests (60 blocked)

That is one more "proof" that AdGuard registers requests from Firefox even though it is excluded from AdGuard. It doesn't block anything from Firefox though as it seems. Everything seems to get blocked by uBlock in Firefox and only a few things bypass both do be end up being blocked by NextDNS.

**Comment by Utini2000** [comment]
@ESurina disabling DNS Protection will also stop "DNS" from being processed (filtered) by AdGuard. It basically fixes the issue I am reporting here. 

But enabling DNS Protection (but disabling DNS Filter) is not enough and will still cause this issue.

Basically AdGuard should default to not processing/filtering DNS when DNS Filtering is disabled and not just only when DNS Protection is disabled.

**Comment by Utini2000** [comment]
I have now uninstalled AdGuard because something is terribly wrong with it regarding this issue.

According to NextDNS there were about 2500 requests within the last 24 hours. AdGuard says it habe been 6900 requests with 200ads and 50 trackers. And that is with Firefox excluded in Adguard while NextDNS records all requests. Adding up all the requests from the "apps overview" sums a total of 3300 requests. Now idea where the other 3600 requests come from according to AdGuard since they aren't listed in the statistics. My guess: Firefox even though it is excluded. Well done for every banking app which is also supposed to be excluded.

**Comment by ESurina** [comment]
We, unfortunately, cannot reproduce this problem, and as soon as we can reproduce it or find another person with a similar problem, we will return to solving it!

**Comment by Utini2000** [comment]
And this is why you close an issue? Because you can't reproduce it? A major issue like this?
