### ISSUE TITLE
Santander and Sainsburys Bank apps broken with HTTPS Filtering on

### ISSUE THREAD

**Issue by privacyguy123** [AdguardTeam/AdguardForAndroid#5058]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2

### Environment

```markdown
- OS: Android 13
- Device: Samsung S20 FE 5G Snapdragon
- Firmware: Latest
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, EasyList, Fanboy's Annoyances, Peter Lowe's Blocklist, Fanboy's Enhanced Tracking List, I don't care about cookies

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Block Location API

### Issue Details

All these questions about filters and settings are irrelevant, it's HTTPS Filtering we are talking about.

It is insane to me that HTTPS Filtering is even defaulting to ON for BANKING apps?

Steps to reproduce:
1. Have HTTPS Filtering on FULLY DEFAULT (i.e. on for Santander and Sainsburys bank)
2. Try to open apps.
3. Apps won't open.

### Expected Behavior

Apps open.

They will open when turned off in HTTPS Filtering. Why are they even on by default in the first place?

### Actual Behavior

Satander gives generic connection error, Sainsburys gives more in depth "untrusted connection" - this makes sense as we're using 3rd party certs to get AdGuard working correctly. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention! We will make https filtering disabled by default for these applications in future versions.
