### ISSUE TITLE
Can't open StartPage.com with AdGuard enabled

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdguardForAndroid#5059]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.54

### Environment

```markdown
- OS: Android 9 and Android 11
- Device: Huawei phone and Lenovo tablet
```

### Root access

- [ ] Yes, I have it.

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Since about 2 days ago, startpage.com can't open unless I disable AdGuard.

1. The page would try to load, the spinning circle loading animation goes on and on but the page never fully loads.
https://i.imgur.com/Gv16m6u.jpg
2. Then after 2-3 mins, browser would report "Aw Snap something went wrong" error.
https://i.imgur.com/r8eGzDp.jpg
3. All I see in AdGuard filter log are the Stealth Settings like User Agent hidden, DNT header added etc.
https://i.imgur.com/H21InW6.jpg
https://i.imgur.com/UGiESXS.jpg
4. Disable AdGuard (I just disabled HTTPS filtering for the browser), and the site loads up instantly.
https://i.imgur.com/QpQjwQj.jpg

Screenshots are from a fresh install of the latest version of Brave Browser. But I experience the exact same behavior on Vivaldi Browser, Kiwi Browser, IceRaven.

### Expected Behavior

Webpage should open.

### Actual Behavior

Webpage doesn't open.

**Comment by piquark6046** [comment]
Maybe it is fixed by https://github.com/AdguardTeam/AdguardFilters/commit/2def624250c2f451d9d6e5e7dadbd0bab2d6e405. Please update filters.
