### ISSUE TITLE
Adguard crashing on statistic panel 

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#5063]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.90 Nightly 26

### Environment

```markdown
- OS:Android 12
- Device:SM-N975F 
- Firmware: SP1A.210812.016.N975FXXS9HWG9  
SE
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Open Adquard on the on the button bar, select the staristic panel
2.Select trackers
3.tap link - google.com or adobe.com or firebase.com and watch the application close and turn off

### Expected Behavior

No more shouting down application 
Fully Access to statistic data's 
Work with database statistic  .

### Actual Behavior

the application turns off after clicking the link in the statistics panel, causing the application to close and reset

### Screenshots

<details><summary>Screenshot 1:</summary>

 

</details>

**Comment by maxikuzmin** [comment]
@U0101100 any news?

**Comment by maxikuzmin** [comment]
@U0101100 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
