### ISSUE TITLE
Automation 

### ISSUE THREAD

**Issue by Hr-2** [AdguardTeam/AdguardForAndroid#5065]
### Issue Details

Add a new feature to make adguard automatically turn on when opening specific apps and turn off when closing those specific apps

**Comment by Versty** [comment]
@Hr-2 Hi! 
At the moment, AdGuard already supports automation. We highly recommend you try Tasker or any other application to set up your desired automation scenario. 

Please read more in [the article](https://adguard.com/kb/adguard-for-android/solving-problems/tasker/).
