### ISSUE TITLE
Recent activity of the selected company with two components is not displayed

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#5067]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2

### Environment

```markdown
- OS: 14
```

### Root access

- [ ] Yes, I have it.

### Issue Details

If in the "Companies" section we have a company name with two components with a space, such as "unity ads", then in recent company activity the search field autocompletes "unity_ads" and nothing shows up in the search results

Steps to reproduce:

Go to Statistics tab -> Companies -> View all companies -> tap on any company with double space name (e.g. unity ads) -> Recent activity 

"Recent activity" is empty 

### Expected Behavior

Recent activity of any selected company is displayed correctly

### Actual Behavior

Recent activity of the selected company with two components is not displayed

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jordanswrld94** [comment]
Can reproduce. Hope this is fixed soon
