### ISSUE TITLE
Error exporting settings: unable to save file with the same name after changing it

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdguardForAndroid#5069]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2; 4.3 Nightly 26

### Environment

```markdown
- OS: Android 14
- Device:Google Pixel 7 Pro
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1) Tap "Settings" icon at the bottom
2) Tap 3-dots in the top right corner and tap "Export Settings"
3) Change the name of the file to some string, for example XXX.zip
4) The settings are exported
5) Tap "Settings" - 3-dots - "Export Settings"
6) Change the file name to the previous string, in our example XXX.zip
7) Tap on "Save"

### Expected Behavior

The exported settings file should be saved as "name(1)" if attempting to overwrite an existing file with the same name.

### Actual Behavior

AdGuard fails to save the file: Failed to export settings. An internal error occurred (Screenshot 1)
AdGuard detected that a file with the specified name already exists, tried to create a file with the name "name (1)", but failed (Screenshot 2)

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/104919935/1635779c-db2c-43d7-bcb3-74ca4e63ffe4)
</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/104919935/3ef9e7ff-7e5e-4994-a86d-7cf1d2bf9735)
</details>

### Additional Information

Also important to note that after renaming and successful saving, the old file name is displayed on the `All done` popup dialog.

<details><summary>Screenshot</summary>

![tempFileForShare_20231127-103342](https://github.com/AdguardTeam/AdguardForAndroid/assets/107266340/b3da4ef3-9608-46a9-870f-770f2b9a4c4a)

</details>

**Comment by AntonVoronkin** [comment]
These are the problems of the android system, which cannot recognize where its file extension ends. File name in "All done" popup will be fixed.
