### ISSUE TITLE
App crash when clicking on a domain in company section

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5070]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS:android 13
- Device:galaxy s23 ultra
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to statistics tab
2. Click on a company
3. Click on any domain in company. App crashes

### Expected Behavior

App doesnt crash

### Actual Behavior

App crashes

### Screenshots

https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/00724465-8820-4c81-98af-9bfaf959791c

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [[devteam@adguard.com](mailto:devteam@adguard.com)](mailto:devteam@adguard.com):
    - mention the `NUMBER` number in the subject
    - specify the exact time when the issue occurred

**Comment by ESurina** [comment]
Could you please send us the logs again?

**Comment by jordanswrld94** [comment]
Sent

**Comment by ESurina** [comment]
Could you please send a .zip file and not a link?

**Comment by ESurina** [comment]
@jordanswrld94

**Comment by ESurina** [comment]
We fixed this problem in the version 4.3.1!
