### ISSUE TITLE
Wrong italian translation

### ISSUE THREAD

**Issue by 0xrxL** [AdguardTeam/AdguardForAndroid#5071]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.103

### Environment

```markdown
- OS: Android 13 One UI 5.1
- Device: Samsung Galaxy S21
- Firmware: U9EWH7
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Tap on ```search update``` button on top-right of screen, in the home tab.
2. Wait until some filters are updated.
3. Check the below screenshot.

### Expected Behavior

A replaced translation of phrase: ```Aggiornato al:```

with:

```Aggiornati:```

### Actual Behavior

The current translation is still the following : ```Aggiornato al:``` instead of ```Aggiornati:```

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20231109_040347_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/127248639/1ceb7815-1d25-4781-8af4-7fa400d1e793)

</details>

**Comment by ESurina** [comment]
We will fix it in the next version!
