### ISSUE TITLE
AdGuard Crashing or disabling/renabling self on Nov Pixel 7 Pro update

### ISSUE THREAD

**Issue by warmoans** [AdguardTeam/AdguardForAndroid#5072]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.118

### Environment

```markdown
- OS:A14
- Device:Pixel 7 Pro
- Firmware:UP1A.231105.003
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, ---Third-party filters---, EasyPrivacy, Adblock Warning Removal List

### What Stealth Mode options do you have enabled?

<p align="left">
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/37345461/15738048-98c0-4bac-8633-1f14edcaa207" width="300">
</p>

### Issue Details

Steps to reproduce:

Have Adguard enabled and the eventually VPN goes down and back up. 

### Expected Behavior

Adguard stays running

### Actual Behavior

Adguard disables and re-enables. I've attached a log cat taken shortly after it happened once. I'll try to be quicker about catching it in future. 
[logcat--2023-11-09--21-55.log](https://github.com/AdguardTeam/AdguardForAndroid/files/13314883/logcat--2023-11-09--21-55.log)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by warmoans** [comment]
I forgot to mention it's definitely happened more than once. Only since the November 2023 update was released.

**Comment by nightznero** [comment]
First stable version of v4 ADG was (well...) okey but after update to 4.2.118 its crashes on and on without any reason

**Comment by Versty** [comment]
@warmoans Does the problem occur with Local VPN routing mode?

**Comment by warmoans** [comment]
> @warmoans Does the problem occur with Local VPN routing mode? Could you please also check if the issue persists with the latest AdGuard for Android release version (4.3.1)?

It was an uncommon issue originally, but I haven't experienced it lately. I always update the app as soon as I get the notification there's an update. So I've been using 4.3.1 from within 24 hours of you releasing it.

**Comment by warmoans** [comment]
> @warmoans Good news! If the crash reoccurs, please reopen this issue to continue the investigation.

Ho
[logcat--2024-02-14--21-26.log](https://github.com/AdguardTeam/AdguardForAndroid/files/14290658/logcat--2024-02-14--21-26.log)
w do I reopen the issue? It happened twice recently. I've attached a log of the most recent. I don't see an option to reopen.
