### ISSUE TITLE
When adding filters other than adguard dns to dns filters it blocks sites that arent in the list

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5077]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS: android 13
- Device: galaxy s23 ultra
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1. Add adguard base filter to dns filter section
2. Visit duckduckgo.com
3. Site is blocked

### Expected Behavior

Site not be blocked

### Actual Behavior

Site blocked

### Screenshots

![Screenshot_20231112_150816_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/7f9798cc-b30d-469e-ac38-4618bb4943dc)

**Comment by jordanswrld94** [comment]
@maxikuzmin can you reproduce this?

**Comment by jordanswrld94** [comment]
Also.happens with easylist

**Comment by jordanswrld94** [comment]
I tried old versions. Looks like everything worked fine up until 4.3 nightly 23

**Comment by maxikuzmin** [comment]
@jordanswrld94 checked also on the latest nightly version, but I didn't have this problem again. I tried with AdGuard Base filter, without this filter, and also tried with adding another filter, but the site is not blocked. 
In your case access to the site is restricted for a long time, or it only happens for a short period of time?

**Comment by jordanswrld94** [comment]
Hmm thats so weird.. it happens even with a fresh set of settings. Its a permanent block. As long as i have other filters enabled it is blocked

**Comment by maxikuzmin** [comment]
@jordanswrld94 please also send debug logs with reproduction times to [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by jordanswrld94** [comment]
Sent

**Comment by jordanswrld94** [comment]
I found it. Its blocking because of a cosmetic rule? Thats so weird

**Comment by jordanswrld94** [comment]
The weird thing is that nightly 22 it doesnt do that. I will just stick with nightly 22 until it can be fixed. But i do see the only thing that changed code wise since nightly 22 is dns libs. So it has to do with that im guessing?

**Comment by maxikuzmin** [comment]
@jordanswrld94 could you please clarify which filter you are adding to the DNS filters module? 
You can post a link to add this filter

**Comment by jordanswrld94** [comment]
https://ibb.co/DYLfqNp
https://ibb.co/k6LsFzs

Here is a screenshot ofnthe filters im using

**Comment by maxikuzmin** [comment]
@jordanswrld94 I'm not quite following you. Are you adding basic AdGuard filters to the DNS section?

**Comment by jordanswrld94** [comment]
Yes just adding the ones from the adblocking filters section.

**Comment by maxikuzmin** [comment]
@jordanswrld94 why are you adding these filters to DNS filters? Those filters are in the Filters section, and you can enable them there

**Comment by jordanswrld94** [comment]
Because i want to block them on dns level aswell

**Comment by maxikuzmin** [comment]
@jordanswrld94 but including filters in "Filters" is enough. 
There is a DNS filter in the DNS section, Easylist and Basic filter are included there. 
The filters you add to the DNS section are not intended for DNS filtering, it will have no effect. It's most likely this combination that is blocking access to sites. 

[Here](https://github.com/AdguardTeam/HostlistsRegistry/tree/main/filters) is what will work for you. Don't forget to select RAW. 
You can read more about how DNS filters work [here](https://adguardteam.github.io/KnowledgeBaseDNS/en/general/dns-filtering/) and [here](https://adguard.com/en/blog/what-is-dns-filtering.html)
Read more about the syntax [here](https://adguard-dns.io/kb/general/dns-filtering-syntax/)

**Comment by jordanswrld94** [comment]
Ok. Thankyou.

**Comment by maxikuzmin** [comment]
@jordanswrld94 btw, maybe this is triggering the duplicate rules you opened another issue about. Please try leaving only DNS filters in the DNS section, and repeat that issue. Let me know the results in the issue about duplicate rules
