### ISSUE TITLE
Instant messengers status (FB Messenger, MS Teams, Skype...) not working

### ISSUE THREAD

**Issue by PifGadget92** [AdguardTeam/AdguardForAndroid#5078]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.118

### Environment

```markdown
- OS: Android 13
- Device: POCO F3
- Firmware: MIUI 14 (14.0.8.0.TKHMIXM)
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard French filter, AdGuard Russian filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard DNS filter, Liste FR

### What Stealth Mode options do you have enabled?

Hide your search queries, Self-destruction of third-party cookies

### Issue Details

Steps to reproduce:
1. Login to any instant messaging app
2. Wait for the status icons to be displayed
3. Nothing happens
4. Disable Adguard: Status icons appears instantly

### Expected Behavior

Instant messaging apps should work as if Adguard was not there. Adguard should not change other apps behaviour.

### Actual Behavior

Online status of messaging apps is not working.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5078` number in the subject
    - specify the exact time when the issue occurred

**Comment by ESurina** [comment]
Also could you please make a screenshot and draw an arrow showing what do you mean by status icons?

**Comment by ESurina** [comment]
@PifGadget92

**Comment by ESurina** [comment]
Reopen this issue if the problem persists.
