### ISSUE TITLE
Ability to block all fonts

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5079]
### Issue Details

I like how ublock has the ability to block all fonts. Is there a way to add support for font blocking? I have tried $font but i guess it isnt supported

**Comment by jordanswrld94** [comment]
Nvm i found a way sorry

**Comment by maxikuzmin** [comment]
@jordanswrld94 did you use `http$font` or `/.*/$font` ? 
There's also `$inline-font` for inline fonts
