### ISSUE TITLE
[Feature request] add ability to hide firewall notifications for a particular app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#508]
Предлагаю предусмотреть возможность включения/отключения уведомлений брендмауэра для каждого приложения. В программе предусмотрено только для всех одновременно. Поясню: если программа, которая постоянно ломится в интернет и мною заблокирована. Постоянно появляющееся уведомление надоедает. А то же время совсем их отключить нет возможности, т.к. для других программ они нужны, чтобы можно было разово разрешить им доступ в интернет.

I have set up the firewall filter for lot of apps I don't want to let them communicate with Internet. I keep getting notifications when I launch the app which is very distracting. How can I prevent this. I can block all notifications from your app but am not sure if it is wise

**Comment by TPS** [comment]
Also, _reset_ this setting when 1 manually goes & allows on firewall page.

**Comment by Revertron** [comment]
Done.
