### ISSUE TITLE
The new version of the UI interface operation is much slower than the previous version before the major change

### ISSUE THREAD

**Issue by dba007** [AdguardTeam/AdguardForAndroid#5081]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3 nightly 29

### Environment

```markdown
- OS:Android 13
- Device:xiaomi
```

### Root access

- [ ] Yes, I have it.

### Issue Details

The previous version referred to the menu called out in the upper right corner

The new version refers to the functional area at the bottom of the interface

Click on the function switch button at the bottom of the interface, and each one will have to wait for a while before the corresponding function is displayed on the interface, which is relatively slow.

### Expected Behavior

Can display the information in the corresponding interface immediately after clicking, as before.

### Actual Behavior

Click on the function switch button at the bottom of the interface, and each one will have to wait for a while before the corresponding function is displayed on the interface, which is relatively slow.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@dba007 could you please record a video of the screen and repeat the steps with a replay of the problem so I can understand it better?

**Comment by maxikuzmin** [comment]
@dba007 any news?

**Comment by dba007** [comment]
> @dba007 any news?

I have installed the new version now, and my phone prompts that I cannot install apps lower than the current version because I have many settings. You can try the previous version with an interface similar to my texture on your own (the functionality may not be as strong as the current version, but the interface operation response is fast)

![1](https://github.com/AdguardTeam/AdguardForAndroid/assets/33961789/43791c72-261c-4be8-9a31-47e28839621d)

**Comment by maxikuzmin** [comment]
@dba007 hope you enjoy all the changes and tweaks to the new version of the app, as we have only worked on improvements and tried to finalize many features of the app. I'm closing this issue for now
