### ISSUE TITLE
Add automation scripts for ad and annoyance closing or skipping in non-browser apps

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#5084]
### Issue Details

AdGuard for Android can only apply network (not cosmetic) filters in non-browser apps due to technical limitations.

### Proposed solution

Use automation tools like [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en_US) in order to develop scripts that would automatically close or skip ads and other annoyances in popular non-browser apps, like Facebook, Galaxy Store, OneDrive, Spotify, YouTube or YTMusic.

**Comment by maxikuzmin** [comment]
@DimitrisKalaboukas as far as I understand, Tasker can be customized without integration with AdGuard. That is, you can customize AdGuard + Tasker for your tasks. There are no plans to create a tool such as Tasker inside AdGuard yet

**Comment by DimitrisKalaboukas** [comment]
@maxikuzmin Average users don’t have the technical knowledge to do so themselves. Tasker offers the ability to create stand-alone automation scripts taking advantage of native Android features and integrate them into third-party apps. Installation of Tasker isn’t required for them to run properly.

**Comment by maxikuzmin** [comment]
@DimitrisKalaboukas okay, let's see how many likes this issue gets

**Comment by TPS** [comment]
Definitely should remember https://github.com/AdguardTeam/AdguardForAndroid/issues/4010 while implementing this.

**Comment by Versty** [comment]
@DimitrisKalaboukas this concept is described in detail in #5092, please continue in the linked issue.
