### ISSUE TITLE
Adgurad Crash when Switching the network

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForAndroid#5085]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.3 Nightly 35

### Environment

```markdown
- OS:Android 12
- Device: Galaxy S10
```

### Root access

- [x] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Connect to a network (cellular/Wi-Fi).
2. Run AdGuard.
3. Switch the network. or make a call.

### Expected Behavior

Adguard would crash

### Actual Behavior

Crashing during no connection time, such as when changing the network or receiving a call while on LTE (no VoLTE on).

### Screenshots

https://github.com/AdguardTeam/AdguardForAndroid/assets/40741745/2a8fb7d0-517c-4a59-b9bd-15a4bd91c11a

### Additional Information

I recorded the logs in debugging mode, and I will send the logs right away to [devteam@adguard.com](mailto:devteam@adguard.com)
Oh, forgot to tell you that I'm using V2rayNG in proxy mode, synced with Adguard.

**Comment by maxikuzmin** [comment]
@aliafshany I was able to reproduce this, but still I don't always have this problem. We'll look into your logs, thanks!

**Comment by aliafshany** [comment]
Dear @maxikuzmin,
This has become much more frequent for me. May I ask you to make this a priority?

**Comment by maxikuzmin** [comment]
@aliafshany we'll try to implement this in upcoming nightly versions

**Comment by maxikuzmin** [comment]
@aliafshany there is not enough data in the logs (even debug), looks like a native crash. Now I'm trying to reproduce this again, but I'm not having it happen again. Could you please reproduce this on your device and record [logcat](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/)?

**Comment by aliafshany** [comment]
> @aliafshany there is not enough data in the logs (even debug), looks like a native crash. Now I'm trying to reproduce this again, but I'm not having it happen again. Could you please reproduce this on your device and record [logcat](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/)?

I tried to reproduce that, and I haven't encountered that bug yet. So, I'll email the logs when it happens. Thank you for investigating this.

**Comment by maxikuzmin** [comment]
@aliafshany in that case, I will close the issue for now. If the problem recurs, please reopen the issue

**Comment by maxikuzmin** [comment]
@aliafshany we fixed this in version 4.3. Please check this

**Comment by aliafshany** [comment]
@maxikuzmin 
I recently updated to this version. I will let you know in a few days. It takes time to test.

I really appreciate you for investigating this.

**Comment by maxikuzmin** [comment]
@aliafshany any news?

**Comment by aliafshany** [comment]
@maxikuzmin 
Well, it seems that the problem has been solved thanks to you and your team. So, I think you may close this issue as it has been resolved. I will reopen it if anything happens, but for now, it's fixed.

**Comment by maxikuzmin** [comment]
@aliafshany glad to hear that! Good luck!
