### ISSUE TITLE
imo app video call issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#509]
При совершении звонка не видно видео собеседника,например при включении Адгарда,иногда когда собеседник звонит и не видит мое видеообращение.И тоже наоборот где у собеседника нет установленного приложения Адгарда.

https://play.google.com/store/apps/details?id=com.imo.android.imoim&hl=ru

Проестировали у себя, ситуация такая: раз через раз собеседник (где отключен адг) не видит моего видео. отключение фильтров не помогло, помогает только отключение защиты

**Comment by Revertron** [comment]
Надо разбираться, может там какая-то хитрая работа с UDP идет, которую мы ломаем. Хотя мы всё тестировали и всё было отлично.
