### ISSUE TITLE
AdGuard crashes when going through statistics 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#5093]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3 Nightly 38

### Environment

```markdown
- OS: Android 13
- Device: Samsung S22 Ultra
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, I don't care about cookies, NoCoin Filter List, Legitimate URL Shortener

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Open AdGuard Adblocker and go to Statistics tab 
2. Go to apps under statistics then click on companies and then click domains 
3. 

### Expected Behavior

Should not restart protection and kick you out of adguard app.

### Actual Behavior

It kicks you out of Adguard App and restarts protection and only opens it  and starts the enabling. 

### Screenshots

Na

**Comment by Batman2814** [comment]
Logs have been sent

**Comment by Batman2814** [comment]
I'll redo the logs and send them again.

**Comment by Batman2814** [comment]
Logs have been sent again.

**Comment by Batman2814** [comment]
By the way, my phone just got updated to Android 14, so it's not on Android 13 anymore.

**Comment by maxikuzmin** [comment]
@Batman2814 thanks for the info, we'll look into your logs

**Comment by maxikuzmin** [comment]
@Batman2814 please check this behavior without the system theme. Is this still recurring?
