### ISSUE TITLE
App cannot filter traffic of aagag.com

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardForAndroid#5098]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2

### Environment

```markdown
- OS: One UI 6.0 (Android 14)
- Device: Samsung A34 5G
- Google Chrome version: 119.0.6045.194
- Kiwi browser version: 120.0.6099.26
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, List-KR

### Issue Details

Steps to reproduce:
1. Enable HTTPS filtering for your web browsers.
2. Visit https://aagag.com

### Expected Behavior

AdGuard for Android can filter traffic of the website.

### Actual Behavior

AdGuard for Android cannot filter traffic of the website unlike other websites.

### Screenshots

<details><summary>Screenshot</summary>

![Screenshot_20231207_194809_Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/98787049/3c43e808-8046-4f3b-896e-74b2b75cbae4)

</details> 

### Additional Information

  - https://github.com/List-KR/List-KR/issues/769#issuecomment-1842871848
  - To find AdGuard debug log, please search `QUIC filtering issue on AdGuard for Android aagag` in AdGuard Slack.

**Comment by Yuki2718** [comment]
Another case https://github.com/AdguardTeam/AdguardFilters/issues/168288 May possibly be the same as https://github.com/AdguardTeam/AdguardForWindows/issues/4938

**Comment by Versty** [comment]
@piquark6046 
Please upgrade to the latest AdGuard for Android release versions (4.3.194) and check if this issue persists. 
Let me know the result.

**Comment by piquark6046** [comment]
OK. It works fine.
