### ISSUE TITLE
Tumblr app https errors

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#510]
adding these fixes the adding endpoint exceptions. don't add whole domain or it will whitelist trackers. these are the only ones needed.

media.tumblr.com
api.tumblr.com
vt.tumblr.com
static.tumblr.com

**Comment by ameshkov** [comment]
We'll check it, thank you!

**Comment by Revertron** [comment]
@gshumihin check the domains please.

**Comment by gshumihin** [comment]
Looks like tublr is ok with this exceptions. No ads and content loads fine.

**Comment by Revertron** [comment]
Done.
