### ISSUE TITLE
Banking app "Iris" detects adguard certificate and flags it as dangerous 

### ISSUE THREAD

**Issue by Shockshwat** [AdguardTeam/AdguardForAndroid#5102]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Nightly 40

### Environment

```markdown
- OS: Android 10
- Device: Redmi note 8 Pro 
- Firmware: MIUI
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to repr oduce:
1. Open Iris by yes bank
2. The app throws an error of invalid certificate

### Expected Behavior

The app should work as normal

### Actual Behavior

The app reports the certificate and closes

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/71540383/48f5053d-9e22-44e1-a2de-d6854cddff51)
</details>

**Comment by infinitewaveparticle** [comment]
Yikes. I hope other apps don't do this

**Comment by maxikuzmin** [comment]
@Shockshwat for banking apps often has certificate pinning, which prevents the app from working in conjunction with AdGuard. In the next updates, we will exclude filtering for Iris bank app.

As a temporary solution, you can exclude filtering manually using App Management for the bank app

**Comment by Shockshwat** [comment]
@maxikuzmin I have excluded iris app from adguard filtering, Previously the app showed that your device is connected to a VPN and your data might not be secure so i had to exclude it, Now it shows the invalid certificate error.

**Comment by maxikuzmin** [comment]
@Shockshwat could you please clarify how you excluded the app from filtering?

**Comment by Shockshwat** [comment]
@maxikuzmin I got to app management, clicked the app and then turned off Route Traffic Through Adguard

**Comment by infinitewaveparticle** [comment]
It sounds like the app is querying the User certificate storage and denying use of the app with an unknown certificate installed. This is not good.

Sent from Proton Mail mobile

-------- Original Message --------
