### ISSUE TITLE
Tesla app error

### ISSUE THREAD

**Issue by terrorist96** [AdguardTeam/AdguardForAndroid#5108]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.118

### Environment

```markdown
- OS: Android 14
- Device: Samsung S21U Ultra
- Firmware: One UI 6
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to reproduce:
1. Install Tesla app and Adguard 
2. After a few hours Tesla app gives 401 session expired error

### Expected Behavior

Nothing

### Actual Behavior

Tesla app 401 session expired error. I found another similar complaint here:
https://ask.metafilter.com/370487/Whitelisting-Tesla-on-Blokada
See also AdGuard Support Request #839023 for logs and further information.
Also: https://github.com/AdguardTeam/AdguardFilters/issues/168037

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Once the issue occurs I have to try to log back into my Tesla account in the app but am not able to successfully do it. No particular filter seems to be the issue but disabling "route traffic through Adguard" for the Tesla app has been the only solution I could find. Seems Adguard should Allowlist Tesla app by default similar to how other apps like Android Audio are allowlisted by default.

**Comment by ESurina** [comment]
The logs show that there are problems with IPv6. Try turning off IPv6 filtering and write if it gets better. Perhaps this is precisely the point.

**Comment by terrorist96** [comment]
How do I do that? I don't see it in settings. Or do you mean at the Wi-Fi router?

**Comment by ESurina** [comment]
Go to Settings -> General -> Advanced -> Low-level settings
And disable a switch next to *IPv6 filtering*

**Comment by terrorist96** [comment]
> Go to Settings -> General -> Advanced -> Low-level settings And disable a switch next to _IPv6 filtering_

Got it, thanks. I disabled it and then re-enabled filtering in the Tesla app. I'll report back in a few days or so if the error happens again or not.

**Comment by terrorist96** [comment]
@ESurina confirmed that the IPv6 filtering was the issue. Can the app be updated to not filter IPv6 for the Tesla app by default but keep it on otherwise?

**Comment by ESurina** [comment]
Unfortunately, we cannot do this technically.

**Comment by terrorist96** [comment]
@ESurina so is the better option to just whitelist the Tesla app instead of disabling IPv6 filtering globally?

**Comment by terrorist96** [comment]
@ESurina ?

**Comment by Versty** [comment]
@terrorist96 Yes, whitelisting the Tesla app would be better in this case.

**Comment by terrorist96** [comment]
@Versty thanks! Is it possible to have that done by default in a future version of Adguard? Similar to how Android Auto is whitelisted by default.

**Comment by terrorist96** [comment]
@Versty

**Comment by Versty** [comment]
@terrorist96 Adding the Tesla app to the global filtering exclusions by default doesn't seem like a good idea, since the problem is caused by ipv6 filtering, and some users with an ipv4-only network will use the Tesla app without any errors in this case.
