### ISSUE TITLE
Some apps repeat ad requests every second

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#511]
List of apps:
Play Music
Manga Rock

https://www.reddit.com/r/Android/comments/4guine/adguard_25_update_is_live_with_https_filtering/d2mg2t4

The same issue with Play Music.

**Comment by gshumihin** [comment]
Here's https log of a problem with play music:
[adguardlog.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/248619/adguardlog.txt)

**Comment by ameshkov** [comment]
@gshumihin don't forget about magna rock

**Comment by gshumihin** [comment]
Here's http request log: https://www.dropbox.com/s/s1pjhsvvzfijl7o/adguard.log
Application name: com.notabasement.mangarock.android.titan
Seems like app loads ads while being in background.

**Comment by ameshkov** [comment]
Play Music 

These are requests from GoogleTagManager:
https://developers.google.com/tag-manager/android/v4/#intro
https://support.google.com/dcm/partner/answer/4293719?hl=en

**Comment by ameshkov** [comment]
Instead of an empty response, we should return an error response (500 Internal Server Error for instance). I hope in this case they'll use their exponential backoff strategy:
https://developers.google.com/api-client-library/java/google-http-java-client/backoff#examples

**Comment by ameshkov** [comment]
It seems that for GoogleTagManager we should simply return 200 OK response otherwise it may sometimes react with constant request repeating.

**Comment by ameshkov** [comment]
We should also add two domains to SSL blacklist:
doubleclick.net
googleadservices.com

**Comment by TPS** [comment]
> We should also add two domains to SSL blacklist:
doubleclick.net
googleadservices.com

If #552 is already accomplished, why's this necessary?

**Comment by ameshkov** [comment]
> If #552 is already accomplished, why's this necessary?

GoogleTagManager **may (sometimes)** go crazy when we simply drop connections to these domains. And without https filtering this is what we do for these domains.

**Comment by evgeniy-ADG** [comment]
The app 'Next', lock screen one, by Microsoft, is being reported in Adguard as a huge ads traffic. Something like hundreds of thousands of requests (daily) to ads. The bandwidth 'saved' reach in about 1gb or so (daily as well).

The NEXON game 'Oz: Broken Kingdom' has the same issue.

Logs and stuff: 1441845

**Comment by ameshkov** [comment]
@gshumihin please take a look at it.

**Comment by ameshkov** [comment]
@evgeniy-ADG please ask user to record HTTP requests log, it's hard to reproduce this issue with MS apps on our side.

**Comment by carlylemiii** [comment]
Goodreads is another such app that goes absolutely nuts:

![screenshot_20170902-223402](https://user-images.githubusercontent.com/29067983/30000388-c0b921de-902f-11e7-8421-704c78240485.png)
![screenshot_20170902-223411](https://user-images.githubusercontent.com/29067983/30000387-c0b83bb6-902f-11e7-9d12-e2c0ee0f84a3.png)

https://www.dropbox.com/s/p6zquasjmud8kp4/adguard_logs_0209_2233.zip?dl=1

**Comment by TPS** [comment]
I find, since I use DNS-level blocking, I don't _see_ much of this.  Is there a way to enable DNS-blocking _per-app_, for those who don't want it globally?

**Comment by ameshkov** [comment]
@TPS unfortunately, dns-blocking is always system-wide

**Comment by TPS** [comment]
Duplicates #786, also?

I'm suddenly having this issue w/ `||csi.gstatic.com^` from the Mobile Ads subscription whenever I open GDrive: it & many related apps go nuts trying to find that server.  I even tried the `||csi.gstatic.com^$important` & (mentioned elseplace) `||csi.gstatic.com^$empty,important` versions.  This filter doesn't seem to block @ DNS-level, though it seems like an obvious candidate.  Logs attached:

[adguard_logs_1309_0518.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1298886/adguard_logs_1309_0518.zip)

**Comment by ameshkov** [comment]
Is can see it in your log file, but I cannot reproduce it

**Comment by ameshkov** [comment]
Does it still happen?

**Comment by TPS** [comment]
Yep, everytime I open GDrive: [adguard_logs_1709_1921.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1309464/adguard_logs_1709_1921.zip)

**Comment by TPS** [comment]
Would a different log level help?

**Comment by TPS** [comment]
Heh, `||csi.gstatic.com$important` (minus the `^`) fixes it!  It's properly blocked via DNS.  Maybe `^` precludes DNS processing, for some bug/parsing reason?

[adguard_logs_1709_1931.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1309466/adguard_logs_1709_1931.zip)

**Comment by ameshkov** [comment]
Hm, `||csi.gstatic.com^` should block it just okay

**Comment by ameshkov** [comment]
Huh, you're right:)

DNS question contains `csi.gstatic.com.` with a trailing dot. This is why it does not work properly.

**Comment by ameshkov** [comment]
Filed a bug report:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1453

**Comment by TPS** [comment]
If it's just the trailing `.` problem, why does `||csi.gstatic.com^` have it & `||csi.gstatic.com` not?

**Comment by TPS** [comment]
Also, same problem w/ other filters w/ `^`?

**Comment by TPS** [comment]
`||fls-na.amazon.com^` from Spyware subscription has same problem. `||fls-na.amazon.com$important` fixes it.

**Comment by TPS** [comment]
@ameshkov I'm _still_ having this problem, though I thought #1453/https://github.com/AdguardTeam/AdguardDNS/issues/185 was meant to fix it?!

[adguard_logs_2.10.104_2609_2323.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1335697/adguard_logs_2.10.104_2609_2323.zip)

**Comment by ameshkov** [comment]
It appears that these domains shouldn't be blocked on the DNS level as it may break some websites:
https://github.com/AdguardTeam/AdguardDNS/blob/5a6bdbc9ecb7187f63090e05b3fbdb6656e0c25b/Filters/exclusions.txt#L22

However, when you add them to the user filter, they are blocked as user filter is used for DNS filtering.

**Comment by TPS** [comment]
Ah, ok.  Now I understand the context of most of the above.  Carry on.

Why is this issue still open, though?

**Comment by ameshkov** [comment]
Just in case we encounter new issues like that
