### ISSUE TITLE
Adguard Software Has An Abnormal Crash

### ISSUE THREAD

**Issue by honeyuee** [AdguardTeam/AdguardForAndroid#5111]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard v4.3 Nightly 41 (10141990)  Kit v5.0.244 CoreLibs v1.13.79 DnsLibs v2.4.0

### Environment

```markdown
- OS:Android 13
- Device:Nubia 
- Firmware:MyOS13.5.19MR_NX713J
```

### Root access

- [ ] Yes, I have it.

### Issue Details

When the software is running, there are abnormal exits and frequent exits, especially when updating the interface, and when adding custom rules, the same situation occurs. Do not know is the setting of the situation or the software itself Bug, trouble to analyze, thank you.

Steps to reproduce:
1.The software crashed, quit the app

### Actual Behavior

![IMG_20231215_080130](https://github.com/AdguardTeam/AdguardForAndroid/assets/53884928/ad49b661-0742-4455-9eb0-12dd5ad99eb9)
Abnormal crash occurs during operation.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@honeyuee Hi! 
Does the crash reoccur when you repeat the same steps?

**Comment by honeyuee** [comment]
Yes, not only did it happen when I submitted the issue, but also when I updated to the latest version of Nightly.











🌤&nbsp; Be yourself and no one else.✨

---Original---
From: ***@***.***&gt;
Date: Mon, Dec 25, 2023 19:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AdguardTeam/AdguardForAndroid] Adguard Software Has An AbnormalCrash (Issue #5111)




 
@honeyuee Hi!
 Does the crash reoccur when you repeat the same steps?

**Comment by Versty** [comment]
@honeyuee We would like to take a look at the logs from your device to investigate this issue further.
Please follow the steps below.

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Wait for the crash to be reproduced, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Collect system bug report. Detailed instruction can be found in [the article](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) in our knowledge base.

5. Send both files to devteam@adguard.com:
      - mention the `5111` number in the subject
      - specify the exact time when the issue occurred

**Comment by honeyuee** [comment]
All right, I've got the email ***@***.*** Sent a message with a OneDrive link to the reserved mailbox ***@***.*** . Because the file is too large, it can only be sent as a OneDrive file. Check it carefully, thank you.













---Original---
From: ***@***.***&gt;
Date: Thu, Dec 28, 2023 19:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AdguardTeam/AdguardForAndroid] Adguard Software Has An AbnormalCrash (Issue #5111)




 
@honeyuee We would like to take a look at the logs from your device to investigate this issue further.
 Please follow the steps below.
  
 
Enable debug logging:
 Settings -&gt; General -&gt; Advanced -&gt; Logging level -&gt; Debug
 
 
 
Wait for the crash to be reproduced, then remember the exact time when it happened
 
 
 
Collect logs:
 Settings -&gt; General -&gt; Advanced -&gt; Export logs and system info
 
 
 
Collect system bug report. Detailed instruction can be found in the article in our knowledge base.
 
 
 
Send both files to ***@***.***:
  
mention the 5111 number in the subject
 
specify the exact time when the issue occurred

**Comment by Versty** [comment]
@honeyuee Thanks! Your logs have been provided to the developers for further investigation.

**Comment by Versty** [comment]
@honeyuee Could you recall the time when the crash occurred?

**Comment by Versty** [comment]
@honeyuee Any updates?

**Comment by Versty** [comment]
@honeyuee Closed due to lack of activity. 
We are currently working on resolving some crashes, so upgrade to the next version of the app when it becomes available to make sure the crash is gone.
