### ISSUE TITLE
Invalid SSL certificate error on some websites 

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#5112]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard v4.2

### Environment

```markdown
- OS:Android 7
- Device:Asus z500m
- Firmware:ZenUi
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1.Перейти на [сайт](https://www.048.ua/ru/news/3706087/rabota-v-odesse-vakansii-s-zarplatoj-ot-15-do-40-tysac-griven)
2.поссотреть,что имеются пропуски рекламы
3. Возможно,открыть информацию о подключении страницы и посмотреть какой сертификат используется.

### Expected Behavior

Фильтрация ssl отсутствует ввиду того,что сертификат от Эдгард не применяется к странице.

### Actual Behavior

Отсутствует фильтрация ssl ввиду описанного.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20231216-235030](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/0a9570e8-bf78-49da-b425-0b562033e093)
![Screenshot_20231216-234007](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/a984d6ef-7679-484c-9a76-1afd6ece3b72)

</details>

**Comment by sfionov** [comment]
@Spok1 В текущем релизе имеется проблема с проверкой сертификатов. Адгард производит те же проверки сертификатов, что и браузеры, чтобы безопасность соединения не понижалась при включенной HTTPS-фильтрации. Но одна проверка была реализована слишком строго, что и приводит к отсутствию фильтрации на некоторых сайтах.

Будет исправлено в релизе 4.3, который ожидается в ближайшее время, и уже присутствует в [4.3 beta 1](https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v4.3-beta-1)

**Comment by Spok1** [comment]
@sfionov , с версией 3.11 проблем нет,так почему же здесь есть?

**Comment by sfionov** [comment]
@Spok1 Проблемная проверка (на соответствие CT policy) появилась в версии 4.2

**Comment by Spok1** [comment]
@sfionov ,это не на всех страницах такое,лишь пока на нескольких мне встретилось. А с чем это связано?

**Comment by sfionov** [comment]
@Spok1 Проблема распространяется на сайты, сертификаты которых выданы после 4 декабря

**Comment by Spok1** [comment]
@sfionov ясно. Спасибо.

**Comment by Versty** [comment]
@Spok1 Добрый день! 
Установите последнее обновление из канала "Релиз", в версии 4.3.194 эта проблема должна быть решена. 

Если вдруг сайты по-прежнему будут показывать ошибку ssl-сертификата, то зайдите в настройки устройства -> Безопасность -> Другие настройки безопасности -> Посмотреть сертификаты безопасности -> Пользователь 
Из вкладки "Пользователь" удалите все сертификаты AdGuard, затем откройте приложение и установите сертификат для HTTPS фильтрации заново.

**Comment by Versty** [comment]
@Spok1 Помогло ли обновление?

**Comment by Spok1** [comment]
@Versty, не знаю, я откатился на версию 3.6! Не знаю, когда установлю версию 4+

**Comment by Spok1** [comment]
@Versty, да!
