### ISSUE TITLE
NOERROR requests not being blocked

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5119]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4

### Environment

```markdown
- OS:android 14
- Device: galaxy s23 ultra
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard DNS filter

### Expected Behavior

NOERROR request blocked

### Actual Behavior

NOERROR requests not blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20231222_160156_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/7604e07b-a493-458c-bcdc-a77d6d1e5593)

![Screenshot_20231222_160124_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/9df53ebc-f696-42a2-a33f-253db4afa5bf)

**Comment by infinitewaveparticle** [comment]
Try changing your blocking mode to NXDOMAIN in lower level settings. Not sure if that will help or not. Also, try these other low level settings (they work for me):

Set fallback upstreams to none
Disable "ignore unavailable outbound proxy"
Enable "try http3 for doh upstreams"
Disable "servfail failure response"
Disable "use fallback for all domains"
Enable "validate DNS upstreams"

**Comment by Versty** [comment]
@jordanswrld94 Hi! 
Please provide information about the DNS server and protocol you are using. 
It is also important to know about your DNS filters, are any DNS filters enabled?

**Comment by jordanswrld94** [comment]
> @jordanswrld94 Hi! Please provide information about the DNS server and protocol you are using. It is also important to know about your DNS filters, are any DNS filters enabled?

I am using nextdns quic. And yes dns filters are enabled but if i turn off my dns filters and just use adguard dns server it still does the same thing.

**Comment by jordanswrld94** [comment]
> Try changing your blocking mode to NXDOMAIN in lower level settings. Not sure if that will help or not. Also, try these other low level settings (they work for me):
> 
> Set fallback upstreams to none Disable "ignore unavailable outbound proxy" Enable "try http3 for doh upstreams" Disable "servfail failure response" Disable "use fallback for all domains" Enable "validate DNS upstreams"

Thanks for this. I have set it to refused mode and it seems to stop allowing through domains that should be blocked. This should be looked into still though as the regular adguard user may or may not have that setting set to refused.

**Comment by Versty** [comment]
@jordanswrld94 We have tried to reproduce this issue with REFUSED mode enabled, but to no avail.
Could you please collect the debug logs from your device and send it to our email? 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5119` number in the subject
      - specify the exact time when the issue occurred

**Comment by jordanswrld94** [comment]
Hi yes refused mode blocks them but not the other modes.`

**Comment by Versty** [comment]
@jordanswrld94 Have you sent the logs?

**Comment by jordanswrld94** [comment]
Just sent them sorry for delay

**Comment by Versty** [comment]
@jordanswrld94 Could you please check on the latest AdGuard for Android 4.4 nightly if the issue is gone?

**Comment by jordanswrld94** [comment]
It seems to be fixed. Will do more testing

**Comment by jordanswrld94** [comment]
Seems to be fixed :)
