### ISSUE TITLE
Cache size quickly grows to hundreds of MB or even gigabytes

### ISSUE THREAD

**Issue by Extreme-Icer** [AdguardTeam/AdguardForAndroid#5125]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

stable,4.3.194

### Environment

```markdown
- OS:oneui5.1,Android13
- Device:Galaxy note20 ultra
- Firmware:SM-N9860
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API

### Issue Details

Steps to reproduce:
1.open the system app setting
2.to the “storage”
3.see the cache

### Expected Behavior

cache maybe few MB

### Actual Behavior

It can result in hundreds of MB or even tens of GB of cache being taken up

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Since it has been cleaned up, screenshots will be added later.

**Comment by ameshkov** [comment]
Probably a relevant message in AdGuard Telegram chat:
https://t.me/adguard/176184/191741

The user has HUGE log files, who knows why. We'll look into it.

@Extreme-Icer could you please check if in your case the log files size is the culprit?

**Comment by Extreme-Icer** [comment]
In which directory are the log files located?

**Comment by ameshkov** [comment]
@Extreme-Icer 

May depend on the device. Check `/storage/emulated/0/Android/data/com.adguard.android/cache/log`

**Comment by MySoul182** [comment]
The log file is quite large
![Screenshot_2023-12-25-09-04-44-867_com google android documentsui](https://github.com/AdguardTeam/AdguardForAndroid/assets/95344231/c92ffb25-7a93-49e7-be0a-d707b07abbef)

**Comment by Versty** [comment]
@Extreme-Icer @MySoul182 
Thank you for reporting! 
We are aware of this issue and have already made some adjustments in the latest release version (4.3.194). 
So please upgrade to the latest stable version, then clear the cache and let us know the result after 12-24 hours of active usage.

**Comment by ameshkov** [comment]
@Extreme-Icer reports with the stable version.

@MySoul182 what exact version are you using? Could you please share the log file?

**Comment by Versty** [comment]
@ameshkov The cache may be transferred from a previous version if @Extreme-Icer used the nightly beta and then upgraded to the release, so we need more details. 

@Extreme-Icer please specify have you upgraded from 4.2 to 4.3 directly?

**Comment by MySoul182** [comment]
> 使用稳定版本的报告。
> 
> 您使用的确切版本是什么？你能分享一下日志文件吗？

I'm sorry, I've updated to the latest version 4.4.1, I can't provide the log file, and now it seems that there is no such bug, I used the 4.3.178 version

**Comment by MySoul182** [comment]
> 使用稳定版本的报告。
> 
> 您使用的确切版本是什么？你能分享一下日志文件吗？

I'm sorry, I've updated to the latest version 4.4.1, I can't provide the log file, and now it seems that there is no such bug, I used the 4.3.178 version

**Comment by Versty** [comment]
@MySoul182 AdGuard for Android 4.4 nightly 1, correct?

**Comment by MySoul182** [comment]
yes

**Comment by Extreme-Icer** [comment]
no
i update from 4.3nightly to stable

**Comment by Versty** [comment]
@Extreme-Icer That explains a lot. 
Please clear the cache and keep an eye on the size for a while, this issue should have already been fixed in 4.3 stable.

Reopen this issue and let me know if the cache size goes wild again.

**Comment by Spok1** [comment]
@Versty,@ameshkov, проблема актуальна на вчерашнем релизе 4.3.199
<details><summary>Details</summary>
<p>

![Screenshot_20231229-154054](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/4b104ac2-5bf0-49e4-87e2-0e9d26503173)
![Screenshot_20231229-153626](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/ecddc40b-4307-4f00-94a1-1b271c1a983f)


</p>
</details>

**Comment by Versty** [comment]
@Spok1 Добрый день! 
Подскажите, чистили ли вы кеш после обновления на версию 4.3.199?

**Comment by Spok1** [comment]
@Versty, я не обновлялся,я удалил прошлую и затем установил новую.

**Comment by Spok1** [comment]
@Versty, я не обновлялся,я удалил прошлую и затем установил новую.  В любом случая я обратно вернулся на версию 3.6,а вам отправил на почту письмо с логами! Анализируйте!

**Comment by Versty** [comment]
Reopened due to some users still reporting this issue after a clean install of AdGuard for Android release version 4.3.199.

**Comment by nightznero** [comment]
on previous version i had familiar issue,app weight was 650mb,updating to newest version X.199 didn't solve that but after _cleaning cache_ _cleaning date_ _uninstalling_ and check with _sdmaid_ that app is fully deleted,installed vX.199 with old settings app size is 250mb. Maybe clean install doesn't solve cuz some files are leftovers in some folders

**Comment by Spok1** [comment]
>Maybe clean install doesn't solve cuz some files are leftovers in some folders

No, uninstallation correctly removes everything, and besides, sdmaid without root rights works just like a regular package uninstaller. So the problem specifically occurs on older versions of Android, in particular Android 7, on which this happens most often.If it doesn’t matter to you, then you can roll back to the previous version 4.1.x, or 3.6.11, where this does not happen.

**Comment by Spok1** [comment]
@nightznero
>Maybe clean install doesn't solve cuz some files are leftovers in some folders

No, uninstallation correctly removes everything, and besides, sdmaid without root rights works just like a regular package uninstaller. So the problem specifically occurs on older versions of Android, in particular Android 7, on which this happens most often.If it doesn’t matter to you, then you can roll back to the previous version 4.1.x, or 3.6.11, where this does not happen.
