### ISSUE TITLE
"Stay always protected" card re-appears on Xiaomi devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#5126]
### Issue Details

"Battery optimization" on Xiaomi devices behaves weirdly and the OS can re-enable it automatically.

Now that we propose "disabling" battery optimization on the main screen, this re-enabling looks strange and causes lots of confusion.

<details>
    <summary>Screenshot</summary>

 ![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/5947035/e068cd9a-a32e-43ac-9db7-ab859e01a2c4)

</details>

### Proposed solution

1. We need to do a better research and see what can be done about that on Xiaomi devices. For example, it seems that on Xiaomi it is necessary to enable "Autostart" **before** disabling battery optimization, otherwise it will reset after reboot: https://www.reddit.com/r/Xiaomi/comments/qsbpv5/battery_optimization_settings_reset_after_reboot/
2. We need to see if this is specific to MIUI or there are more Android forks that can behave like that.

If AdGuard is running on such a device, we should provide the user with instruction on what to do.

**Comment by johnconner122** [comment]
It is gone if you set unrestricted mode on this page.
![Screenshot_2023-12-24-21-34-52-520-edit_com android settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/107796137/24a309df-ae4a-4131-b77b-095d5bacc38c)

**Comment by ameshkov** [comment]
@liveonloan 

> Adguard autostart is enabled

Do you have it enabled in MIUI own settings?

On MIUI 14, there is a new permission to start from the background for each app, in Settings > Apps > Your app > App permissions > Background autostart.

Also, on MIUI 12 there's another "Autostart" available from the app settings:
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/5947035/ec7dbb72-55f8-4e81-a422-c779e33b49aa)

> There was no such problem in previous release 4.2.

On v4.2 there was no background optimization mode detection in AdGuard in general.

**Comment by ameshkov** [comment]
Here's what I suggest to do for now in our app:
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/5947035/e0d5c10a-e3d0-4930-8fc8-f504ef40fb18)

*Important points:*

1. The information block should be clearly visible (maybe use a "warning" style for it)
2. It should only be shown to the users of MIUI.

Suggested text:
On MIUI you are required to additionally **manually** enable "Autostart" for the app in *Settings > Apps > AdGuard*. Starting from MIUI 14 there is also a new permission "Background autostart" available in *Settings > Apps > AdGuard > App permissions*.

**Comment by ameshkov** [comment]
Temporary solution in v4.3.1: don't show that card on MIUI devices.

Better solution is planned for v4.4: https://github.com/AdguardTeam/AdguardForAndroid/issues/5137
