### ISSUE TITLE
instagram app ssl pinning

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#513]
app link: https://play.google.com/store/apps/details?id=com.instagram.android&hl=en

https://nopaste.me/view/raw/dce47303

**Comment by jo2dan23** [comment]
i think this means ssl pinning is enabled or something has to be fixed in adguard itself?

**Comment by jo2dan23** [comment]
hmm. idk if it is just me. but it looks like other apps are producing errors also

**Comment by jo2dan23** [comment]
java.net.ConnectException: failed to connect to /2a03:2880:f00b:3:face:b00c:0:1 (port 443) after 5000ms: isConnected failed: EHOSTUNREACH (No route to host)

what is this

**Comment by jo2dan23** [comment]
![screenshot_2016-05-01-19-44-32](https://cloud.githubusercontent.com/assets/15130139/14945353/380a247c-0fd5-11e6-8d19-7d33e0f336dc.png)

**Comment by jo2dan23** [comment]
I dont know as to if that part is for the whole app or just using the login with facebook,method?,but adding instagram to ask,app,exceptions fixed the errors in the log and fixed direct messaging which is part of facebook.

**Comment by jo2dan23** [comment]
Ok so i tested the login with facebook,method with instagram not in,ssl app,exceptions and it works fine. So im guessing the whole app just needs to be in ssl exceptions.

**Comment by ameshkov** [comment]
I don't see signs of ssl pinning, closedchannelexception is expected in this case.

**Comment by ameshkov** [comment]
Take a look at the code, right before the closedchannelexception there is a line with "close_notify" alert. This means that server has alerted us, that connection is closing.
