### ISSUE TITLE
The application does not appear in the App management list 

### ISSUE THREAD

**Issue by FishMagic** [AdguardTeam/AdguardForAndroid#5132]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi Redmi K50
- Firmware: MIUI 14.0.23.9.18 DEV
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Launch Adguard

### Actual Behavior

In some cases, a part of the applications in the application list may be lost, such as Clash, which causes the rules set for this application to not take effect normally. At least one restart of Adguard is required to restore normal operation. In occasional cases, multiple restarts may be needed.

### Screenshots

<details><summary>Screenshot 1: Clash Not In Apps List</summary>

![图片](https://github.com/AdguardTeam/AdguardForAndroid/assets/31554762/dcfd2f03-c8f8-4da9-8adb-4da96c57b96f)

</details>

<details><summary>Screenshot 2: Clash Proxy by Adguard</summary>

![图片](https://github.com/AdguardTeam/AdguardForAndroid/assets/31554762/967fc6fc-5c88-4ed8-8600-11da01d20b0f)

</details>

**Comment by maxikuzmin** [comment]
@FishMagic this should be fixed in version 4.3 - 4.3.1, there is already an open issue on this bug. Please, if you still have this recurring on version 4.3, post it in the [Issue](https://github.com/AdguardTeam/AdguardForAndroid/issues/5089)

I'm closing this issue

**Comment by Versty** [comment]
@FishMagic Thank you for reporting! 
Let's discuss this problem further in the related issue #5089

**Comment by FishMagic** [comment]
@maxikuzmin @Versty 
The issue #5089 has been closed. So I will provide the log here again.
[adguard_logs_4.3.199_2912_092308.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/13790328/adguard_logs_4.3.199_2912_092308.zip)

**Comment by FishMagic** [comment]
<details><summary>Here is nothing in my application list now!</summary>

![Screenshot_2024-01-07-11-54-38-669_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/31554762/068c010c-d7b8-4749-90b5-eafc6098c1eb)

</details>

[adguard_logs_4.3.199_0701_115458.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/13852164/adguard_logs_4.3.199_0701_115458.zip)

**Comment by maxikuzmin** [comment]
@FishMagic we'll look into your logs, it'll take some time.

**Comment by maxikuzmin** [comment]
@FishMagic since we closed this issue as a duplicate, please keep an eye on [#5089 ](https://github.com/AdguardTeam/AdguardForAndroid/issues/5089)
