### ISSUE TITLE
Latest Nightlies killed Android TV functionality

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#5134]
### Issue Details

The problem is that Android TV users can no longer view the filtering log or type out Support requests from the Support section (we're forced to scan a QR code). We also can't see which filter lists are updating or what is new in the new version when updating.

### Proposed solution

While I like the new look you have removed useful features for Android TV users who have keyboards. I want to inspect my filtering log and also be able to email support right from the app.

### Alternative solution

Please stop removing features for the sake of "ease" for noobs. There are power users who want all the functionality of the regular Android app on their Android TV. If you want to keep the QR code as an option for support that's fine. But don't make it a requirement. Please just make everything in the Android app possible on Android TV. Thank you.

**Comment by infinitewaveparticle** [comment]
Also just noticed that I can only turn on tracking protection or turn it off. Why can't I pick which tracking protection features I want? I'm running a rooted NVIDIA Shield.

**Comment by infinitewaveparticle** [comment]
And I can't add custom filters or choose which filters I want anymore? This is just embarrassingly bad.

**Comment by infinitewaveparticle** [comment]
And app management no longer allows me to block certain pps from connecting to the Internet?!? By updating have I lost all of my settings from before? I sure hope not.

**Comment by infinitewaveparticle** [comment]
The AdGuard VPN tab doesn't even recognize that I already have AdGuard VPN! I wish I would have waited to fully explore how awful this app us now before typing this "feature request" -- it's more like a request to fire whoever thought killing a bunch of functionality was a good idea. You even removed the ability to connect to VPN apps via SOCKS5 and other ways. You removed HTTPS filtering... Hello?!? I PAY for AdGuard for this very reason! My Android TV is rooted!

**Comment by infinitewaveparticle** [comment]
@Versty can we please have an option to spoof our device so we can download the same AdGuard for Android apps as we use on mobile? Or perhaps have a toggle button we can click to open all the functionality that was lost? I'm not sure what to do at this point other than to uninstall and go back to the last version before you sacrificed all the paid functions of AdGuard for Android TV. Even for non-rooted Android TV devices there are still some apps that use http connections instead of https. This is a use case for having the filtering log available as well as the many other lost functions.

**Comment by Versty** [comment]
@infinitewaveparticle Hi! 
We have put a lot of effort to develop and release the first officially supported version of AdGuard for Android TV. Еven though this version does not contain as many features as the mobile version at the moment, we plan to implement more options in the future releases. 
AdGuard for Android TV will get better as the days go by, so stay tuned!

**Comment by infinitewaveparticle** [comment]
While I appreciate that you have actually destroyed it for me. Is there any way to get the mobile apk on Android TV right now? I will try this myself to see if it's possible.

Sent from Proton Mail mobile

-------- Original Message --------
