### ISSUE TITLE
Lots of apps not working 

### ISSUE THREAD

**Issue by SunnyLeu** [AdguardTeam/AdguardForAndroid#5135]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.194

### Environment

```markdown
- OS: Android 13
- Device: ZenFone 9
- Firmware: 33.0804.2060.142
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Disable all the protection, but keep AdGuard enable
2. Open Google One app, not working 
3. Disable AdGuard protection
4. Open Google One app, it works

### Actual Behavior

As above 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@SunnyLeu I don't have this problem repeatedly, Google One is working properly.  Could you please describe the problem in more detail? What exactly is not working? It would be nice if you could record a video of the screen describing the steps and the problem.

it would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 5135 number in the subject
specify the exact time when the issue occurred

**Comment by SunnyLeu** [comment]
> @SunnyLeu I don't have this problem repeatedly, Google One is working properly. Could you please describe the problem in more detail? What exactly is not working? It would be nice if you could record a video of the screen describing the steps and the problem.
> 
> it would be nice to get your logs.
> 
> * Enable debug logging:
> 
> Settings -> General -> Advanced -> Logging level -> Debug
> 
> * Reproduce the issue related to the button behaviour, then remember the exact time when it happened
> * Collect logs:
> 
> Settings -> General -> Advanced -> Export logs and system info
> 
> * Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
> 
> mention the 5135 number in the subject specify the exact time when the issue occurred

Email sent, please check

**Comment by Garry050** [comment]
Same here. after 4.3.x, lots of issues when turn on AdGuard. (seems not related VPN or Root proxy)

Should I send mail for that?

**Comment by SunnyLeu** [comment]
> Same here. after 4.3.x, lots of issues when turn on AdGuard with 3 devices. (Moto/Huawei/Pixel) seems not related VPN or Root proxy
> 
> Should I send mail for that?

I think you can also send logs to them

**Comment by maxikuzmin** [comment]
@Garry050 are you also having issues with Google One? How exactly are the apps not working? No internet access or some error appears?

**Comment by maxikuzmin** [comment]
@SunnyLeu thanks, I've got your logs, we'll need some time

**Comment by maxikuzmin** [comment]
@SunnyLeu could you clarify how the app is not working? Is nothing loading?

**Comment by SunnyLeu** [comment]
> @SunnyLeu could you clarify how the app is not working? Is nothing loading?

Yes, nothing is load

**Comment by maxikuzmin** [comment]
@SunnyLeu please try adding the application package to QUIC bypass packages and repeat the steps
Go to Settings tab -> General -> Advanced -> Low-level settings -> QUIC bypass packages -> add com.google.android.apps.subscriptions.red
Let me know about results

**Comment by SunnyLeu** [comment]
> @SunnyLeu please try adding the application package to QUIC bypass packages and repeat the steps Go to Settings tab -> General -> Advanced -> Low-level settings -> QUIC bypass packages -> add com.google.android.apps.subscriptions.red Let me know about results

Problem solved, Google One can be load successfully.

**Comment by maxikuzmin** [comment]
@SunnyLeu then I'm closing this issue. If you have any news about it, please let me know
