### ISSUE TITLE
Add more information about MIUI to "Stay always protected dialog"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#5137]
Here's what I suggest to do for now in our app:
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/5947035/e0d5c10a-e3d0-4930-8fc8-f504ef40fb18)

**Important points:**

1. The information block should be clearly visible (maybe use a "warning" style for it)
2. It should only be shown to the users of MIUI.

Suggested text:
On MIUI you are required to additionally **manually** enable "Autostart" in *Settings > Apps > AdGuard*. Starting from MIUI 14 there is also a new permission "Background autostart" available in *Settings > Apps > AdGuard > App permissions*, it should also be enabled.

_Originally posted by @ameshkov in https://github.com/AdguardTeam/AdguardForAndroid/issues/5126#issuecomment-1869471406_

**Comment by phre2** [comment]
If you need any logs or tester, let me know.

**Comment by phre2** [comment]
It's now a bug on AdGuard 2.7. Bug wasn't there with 2.6

**Comment by ameshkov** [comment]
Mm, what do you mean, there's no "Stay always protected dialog" in AdGuard VPN.

**Comment by phre2** [comment]
That's not the bug. The bug is that battery optimization turns automatically on even if we put it off once AdGuard services start.

**Comment by phre2** [comment]
UPDATE: after updating from MIUI to HyperOS the bug seems gone. I'll test it more.

Currently using the latest AdGuard Nightly.

**Comment by Benson2333** [comment]
据说是国内定制版MIUI有黑名单/白名单应用程序，比如微信是白名单，广告拦截和杀毒软件都属于黑名单。
Adguard VPN可开启“无限制电源”，但是Adguard总是失败。
只有解锁刷机到国际版MIUI，这个问题才会有所缓解。
我曾经下载了杀毒软件Dr.web，也出现被MIUI杀后台的现象，但是它提供了“设备管理应用”的权限设定，只要使用这项权限，它似乎是开启了系统策略，就像企业用户似的，MIUI的黑名单对它不再有效。
![20240515_200211](https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/4c3fc656-6e79-47a6-9f0e-f5ce2bdf5e7f)

**Comment by JeffreyChenTaiwan** [comment]
MIUI14 for Taiwan version also have same problem.
