### ISSUE TITLE
Taskbar icon style disharmony

### ISSUE THREAD

**Issue by TullyMonster** [AdguardTeam/AdguardForAndroid#5139]
### Issue Details

The new AdGuard taskbar icon size significantly exceeds the text height, which greatly affects the look and feel. And the icon is filled with a large area, when the taskbar icon is displayed in a dark color, it is particularly ugly. It is highly recommended that you use the icon style used in v4.2.
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/47771282/e582ee4b-bddc-4ff8-9b0d-0aa9f1fb9852)

### Proposed solution

I prefer smaller, hollowed-out icons for their sense of breathability.

**Comment by ESurina** [comment]
Thank you for sharing your thoughts. After careful consideration, we have decided to maintain our current design without implementing the suggested changes.
