### ISSUE TITLE
Can't logout on AndroidTV

### ISSUE THREAD

**Issue by Munskin** [AdguardTeam/AdguardForAndroid#5141]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.194

### Environment

```markdown
- OS: AndroidTV
- Device: Nvidia Shield
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Install the apk on AndroidTV
2. Login with an account with no active license
3. Free trial is active 

### Expected Behavior

Someway to logout and login with another account on AndroidTV

### Actual Behavior

1. Logged in while following the startup steps the first time opening the apk
2. Used the wrong account which doesn't have an active license
3. Now a 7 days free trial is active but can't remove this account from the app
4. Uninstalling and reinstalling the app doesn't work, I get the tutorial again but immediately are logged in again on the wrong account.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@Munskin thanks for the long wait. Unfortunately, it is not possible to skip the "Trial period of 7 days" as it is tied to the device id. Only after one week you will be able to enter your license. Have you managed to do it yet?
