### ISSUE TITLE
Adguard for Harmony Next

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/AdguardForAndroid#5144]
### Issue Details

Harmony Next is an operating system developed by Huawei. It cannot use Android software. I suggest you develop Harmony Next Adguard.Many companies in China have already started developing software based on Harmony Next, which will become the world's third-largest mobile operating system. For the average person, the operating system more, the average person can have one more choice, the operating system is competing with each other, this is a good thing for the average person.So I think we should support this new system

**Comment by TPS** [comment]
Previous _(incompatible)_ edition @ https://github.com/AdguardTeam/AdguardForAndroid/issues/3913.

**Comment by Versty** [comment]
@xiulou23 Thank you for bringing this to our attention. 
We will do our best to keep AdGuard application available to users with HarmonyOS NEXT.
