### ISSUE TITLE
disabling via the notification shade will auto enable itself upon re-opening the app

### ISSUE THREAD

**Issue by robifr** [AdguardTeam/AdguardForAndroid#5146]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.4 nightly 2

### Environment

```markdown
- OS: android 13
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. ensure adguard app is closed from the "recent apps", this one is a must,
2. click "off protection" from the notification shade,
3. adguard is now disabled until you re-open the app

### Expected Behavior

should be disabled when i re-open the app after disabling it via notification shade

### Actual Behavior

automatically re-enabling itself upon re-open the app

### Screenshots

<details><summary>Screenshot 1: disabling it via notification shade</summary>

![Screenshot_2024-01-01-02-50-16-284_com android chrome-edit](https://github.com/AdguardTeam/AdguardForAndroid/assets/78811448/969ae8be-33fe-49eb-8f37-39a3f61037b5)

</details>
<details><summary>Screenshot 2: adguard re-enabling itself upon re-opening the app</summary>

![Screenshot_2024-01-01-02-50-31-819_com adguard android-edit](https://github.com/AdguardTeam/AdguardForAndroid/assets/78811448/9616b1e6-e5a4-4992-a718-5d3ea1691814)

</details>
<details><summary>Screenshot 3: quick settings</summary>

![Screenshot_2024-01-01-02-55-32-768_com android ### chrome-edit](https://github.com/AdguardTeam/AdguardForAndroid/assets/78811448/81ba2a2a-f4fb-428c-b8c3-0d5ce4e3f2f6)

</details>

### Additional Information

this such behavior not happen when i disable it via "quick settings"

**Comment by ESurina** [comment]
We will fix it in the future versions!
