### ISSUE TITLE
Can't use over https traffic 

### ISSUE THREAD

**Issue by 0nahid** [AdguardTeam/AdguardForAndroid#5147]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

```markdown
- OS: realme 4.0
- Device: realme 9 se
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1. Enabled this filter inside the Adguard app.
2.
3.

### Actual Behavior

The internet on the Facebook app isn't working I've tried on this app only 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

![Screenshot_2024-01-01-07-16-55-21_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/41489906/d39a12f0-c589-4653-b8ba-f50f3f56ce8c)

**Comment by Versty** [comment]
@0nahid Hi! 
This issue is caused by the technical side of the Facebook app, we are currently looking for a workaround or some solution. 
You can read detailed explanation in #4827
