### ISSUE TITLE
Spotify errors

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#515]
22:31:35.593 [Thread-832] ERROR c.a.android.filtering.packet.d - UNKNOWN (2) over IPv4 is not implemented.
22:31:36.773 [Thread-832] ERROR c.a.android.filtering.packet.d - UNKNOWN (2) over IPv4 is not implemented.

What does this mean?

**Comment by ameshkov** [comment]
Adguard implements only the following protocols: TCP, UDP, it also can emulate ICMP for ping requests.
Other protocols cannot be implemented at all as Android does now allow to use raw sockets.

This particular packet is of IGMP:
https://en.wikipedia.org/wiki/Internet_Group_Management_Protocol

**Comment by Tetiana2020** [comment]
Can we change anything in the settings if there is such error in "debud"?

**Comment by ameshkov** [comment]
> Can we change anything in the settings if there is such error in "debud"?

We can try excluding addresses or the whole app from VPN in order to fix the issue.

**Comment by Tetiana2020** [comment]
ok. thank you.
