### ISSUE TITLE
Adguard Android incorrectly blocks Visible

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/AdguardForAndroid#5150]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4 nightly 2

### Environment

```markdown
- OS:Android 12
- Device: Samsung S10e
- Firmware: Oneui 4.1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1. Setup Visible Android app (https://play.google.com/store/apps/details?id=com.makevisible.visible)
2. Setup will freeze part way through 
3. Once adguard is disabled for the app it works
4.

### Expected Behavior

Setup to proceed as normal

### Actual Behavior

When entering details to create account after clicking submit app gets stuck on loading screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@Samuel12321 I have successfully installed the app, entered the data requested by the app and logged into the account. Could you please clarify at what stage you are having difficulties with the Visible app? Did I understand correctly that the problem occurs at the installation stage of the application and not at the configuration stage? What version of Visible are you using?

**Comment by maxikuzmin** [comment]
@Samuel12321 any news?

**Comment by maxikuzmin** [comment]
@Samuel12321 for the moment, I'm closing this issue. If the problem happens again, please reopen the issue
