### ISSUE TITLE
Forward all TCP forwarding to UDP 

### ISSUE THREAD

**Issue by Pantyhose-X** [AdguardTeam/AdguardForAndroid#5151]
### Issue Details

Forwarding all tcp forwarding to udp is a necessary option. 
Adguard local VPN Redirecting traffic to UDP outgoing This is not a difficult task.
UDP can avoid some network censorship.
Nowadays, browsers have also implemented http3 , which is based on udp.

### Proposed solution

an option: Enable and then disable “TCP forwarding to UDP ”

**Comment by Versty** [comment]
@Pantyhose-X Unfortunately, your suggestion is not technically possible.
