### ISSUE TITLE
Some bad GUI in version 4.0

### ISSUE THREAD

**Issue by Pantyhose-X** [AdguardTeam/AdguardForAndroid#5153]
### 1. slow to load  “Version 3.6 does not have this issue”
<details><summary>Screenshot</summary>

![1](https://github.com/AdguardTeam/AdguardForAndroid/assets/42504385/98bf4661-63e6-42d2-837f-b619adabbbc8)

</details>

### 2. Search bar and About , huge size wasting a lot of space, Wasted a few seconds of my time. Scroll down.

<details><summary>Screenshot</summary>

![2](https://github.com/AdguardTeam/AdguardForAndroid/assets/42504385/ddb3bbe2-1fec-487a-9d15-8e7e520cd9db)

</details>

### 3. Request details app icon no longer supports shortcuts to open HTTPS filtering, firewall settings, etc. Another waste of my time.

<details><summary>Screenshot</summary>

![3](https://github.com/AdguardTeam/AdguardForAndroid/assets/42504385/91a9f1e9-1299-46aa-9d14-fd73ae6de92e)

![4](https://github.com/AdguardTeam/AdguardForAndroid/assets/42504385/b08f2b59-fdcf-4f0b-a057-a372eafc5d82)

</details>

**Comment by maxikuzmin** [comment]
@Pantyhose-X thanks for your feedback! That's right, the interface compared to version 3.6 has been completely redesigned and differs quite a bit. 
1. The Statistics tab has been redesigned and has more functionality, so it requires this download. Do you have this happening for a long time? On my device, it takes no more than a second to load
2. What version of AdGuard are you using? In my version 4.3.1, the "Search bar and About" take up no more than 1/3 of the screen, just like other places in the app - are the same size and don't take up half of the screen for ease of use. Also, clarify what screen resolution are you using? 
3. These mechanics have been reworked and moved to App management, you made a good point in the second screenshot. 

Please, if you would like to change something in the app, open an Issue with a "Feature request" tag for each change to bring that change to a vote. We keep track of issues with a high number of likes and further refine the app.
(Please do not open an Issue with the tag "Feature request" with a list of changes, this will make it harder for other users to find your "Feature request" and support it with a like, there is one issue for each change)
