### ISSUE TITLE
Autorun does not work after rebooting Chromecast and Sony TV

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#5156]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

```markdown
Chromecast for Android TV
Sony TV
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
Install AdGuard for Android TV - check autorun in settings, autorun is enabled by default (Settings - General) - enable DNS protection (Protection - DNS-protection - select AdGuard DNS server) - check a [test site](https://adguard.com/en/test.html) to see if AdGuard protection works.
Go to TV System Settings - System - Restart
After rebooting, check the test site if AdGuard protection works - protection does not work. When logging into AdGuard after rebooting the device, the protection is disabled in the application, the switch is in the off position

It is also worth noticing that after turning on/off the device or after sleep mode - the protection is on and does not turn off, most likely the problem is in some resolutions on the TV device

### Expected Behavior

Protection auto-starts after device reboot

### Actual Behavior

Protection does not auto-start after device reboot

**Comment by DennisNishiura** [comment]
I did all the AdGuard installation procedures, but whenever I restart my Sony xbr-65x850f TV, AdGuard does not start and the launch options along with the TV become active.
