### ISSUE TITLE
Include com.nekki.shadowfightarena to QUIC bypass packages by default 

### ISSUE THREAD

**Issue by SohanRay** [AdguardTeam/AdguardForAndroid#5158]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.3.1

### Environment

```markdown
- OS: Android 14
- Device: Samsung Galaxy S23 
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, Online Malicious URL Blocklist, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Disable WebRTC

### Issue Details

Steps to reproduce:
1. Turn on AdGuard 
2. Open Shadow fight arena game
3. Go to vs mode gameplay and try starting a fight match

### Expected Behavior

should launch the vs mode fight against another player online.

### Actual Behavior

shows server connection error .

### Screenshots

<details><summary>Screenshot</summary>

![Screenshot_20240108_073115_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/97858423/8b01ab3a-c672-4be6-b462-0141dbcae9d7)

</details>

**Comment by SohanRay** [comment]
![Screenshot_20240108_073115_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/97858423/6dc3d135-e0e7-4e27-9012-73f014e48dfc)

**Comment by Versty** [comment]
@SohanRay Hi! 

We would like you to collect the debug logs from your device for further investigation. 
Please follow the steps below. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5158` number in the subject
      - specify the exact time when the issue occurred
      

_____

As temporary solution you can disable the `Route traffic through AdGuard` option for Shadow Fight 4 application in App management tab or add the `13.126.215.223/32` rule from a new line to the `IPv4 ranges excluded from filtering` list (*Settings tab -> General -> Advanced -> Low-level settings*).

**Comment by SohanRay** [comment]
Hi, the game app is now working fine as I added the app package name in Adguard android app, advanced - low level settings - QUIC bypass.
Seems it was blocking the QUIC connections. But my question is why does it block QUIC connections by default . And if users do want to block such connections , then they should be given such an option in the app settings(not low level).

**Comment by Versty** [comment]
@SohanRay AdGuard application blocks a QUIC connection only if it cannot recognize the start of a connection to perform a check for ad domains. We will include Shadow Fight application to QUIC bypass by default.

**Comment by SohanRay** [comment]
> @SohanRay AdGuard application blocks a QUIC connection only if it cannot recognize the start of a connection to perform a check for ad domains. We will include Shadow Fight application to QUIC bypass by default.

Sooo, ahh instead of blocking the  connection in such an event, what if it allows it and doesn't block by default ?
