### ISSUE TITLE
Add com.yik.yak app to the HTTPs exclusions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#516]
Add okcupid and YikYak to the list of apps that should be whitelisted from HTTPS filtering. YikYak won't load yaks and okcupid's visitors & likes features break with it enabled.

**Comment by jo2dan23** [comment]
The whole app doesn't need ro to be whitelisted change logging level to everything and look for errors

**Comment by jo2dan23** [comment]
Yikyak works fine

**Comment by jo2dan23** [comment]
and okcupid works fine also

**Comment by Revertron** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/wiki/Resolving-HTTPS-compatibility-issues

**Comment by gshumihin** [comment]
Okcupid works fine

**Comment by Revertron** [comment]
[Yik Yak Your Local Feed_v3.6.0_apkpure.com.apk-delete.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/308777/Yik.Yak.Your.Local.Feed_v3.6.0_apkpure.com.apk-delete.zip)

**Comment by gshumihin** [comment]
Here's domains to whitelist for yik-yak:
us-central-api.yikyakapi.net
notify.yikyakapi.net
content.yikyakapi.net

**Comment by Revertron** [comment]
Added them.
