### ISSUE TITLE
AdGuard on android TV killed in the background

### ISSUE THREAD

**Issue by misiek735** [AdguardTeam/AdguardForAndroid#5162]
### Issue Details

It is fantastic that you created the android tv version, so far it is working beautifully and I am happy to see that it was able to block the ads in the main home screen (launcher).
Unfortunately, for most of the TVs available in the market, the system has very low amount of ram memory available and it is very strict regarding the ram memory management. The adguard app is quite often killed in the background.

### Proposed solution

I own a Philips 58PUS7304 android tv version 11. In settings of the tv - android settings - device preferences - storage - internal shared storage - apps - go to the bottom and choose special app access - energy optimisation, I turned off the toggle for AdGuard (so the setting changed from "Optimising energy use" to "Not optimised").

I am not sure if this trick is the only available / possible solution. I am testing this app for at least a week and so far the app stayed active in the background. I could not find any other similar setting in my tv as there are in my phone, such as "always on vpn" for example. 

Perhaps there is some other adb solution?

### Alternative solution

At least in my tv, after activating the protection, I noticed that pushing the back button would indicate for the android tv system that it can kill the adguard app in case if it need to use the ram memory for opening other apps, like for example netflix or hbo.

But turning on the adguard protection and clicking the home button on the remote control (which indicate that I want to minimise the app), the system kind of "save" the app to be active in the background.

Perhaps including all mentioned steps in your instalation guide could help to some users with properly setting up the app?

**Comment by misiek735** [comment]
@maxikuzmin of course. 
At the moment of writing this answer, I opened adguard app and instead of using the home button on my remote, I used the back button (so I exited the app).
Then I turned on hbo max app, click home button, YouTube, click home button, mx player app, click home button and I turned on again the AdGuard app. The app loaded again, the protection was off for a few seconds, then it turned on again. That means that the app was killed to empty ram for all the other apps that I turned on. Once the app is killed, the protection doesn't work, because I am starting to see the advertisements on the home screen as well as in some other apps.

Just for your information, in developer options, the background process limit is set up to standard. I did not modified any settings there.

**Comment by maxikuzmin** [comment]
@misiek735 could you repeat the same steps without battery optimization, but before you start turn on the protection and wait 10-15 seconds for it to turn on? 
I suspect that because of the known problem with the long turn on of the protection, you minimize AdGuard too quickly and the protection does not have time to turn on. You need to wait for the information above the switch to show that the protection is enabled

**Comment by misiek735** [comment]
@maxikuzmin sorry for my late response. I decided to test it carefully to be absolutely sure if the issue comes back or not.
So far, after turning on the protection and waiting (just in case) approx. 1 minute, everything is ok and the protection is constantly active. Seems that we can close the topic :)

**Comment by maxikuzmin** [comment]
@misiek735 we are now actively looking into the issue of autorunning applications. I think this will solve some of the problems. It should be noted that disabling power optimization did not help in any way in this case. I also checked your case, but in my case the protection remained enabled. I am closing this issue at this time. If you have any news on this issue, please let me know.

**Comment by Ic3MaN8187** [comment]
Still happens on my tv and there's literally nothing I can't do to solve this problem.. waste of money

**Comment by foinf** [comment]
Still a problem. I understand low ram kills an app but having it restart itself would be great. I am experiencing this issue on my TCL 65P635 TV.

Android TV OS Version 11
Kernel Version 4.14.187
Android TV OS build RP1A.200622.001

Adguard dies atleast 3 times a day and we are not even switching through multiple apps.
