### ISSUE TITLE
adguard tv license

### ISSUE THREAD

**Issue by RobotsAreCrazy** [AdguardTeam/AdguardForAndroid#5163]
### Issue Details

Hi, please tell me i can use my current lifetime license to activate the android tv app?

**Comment by Versty** [comment]
@RobotsAreCrazy Yes, our licenses are universal and can be used on Android TV as well.

**Comment by RobotsAreCrazy** [comment]
That's amazing to hear, getting an error when trying to install on a chromecast 

![PXL_20240112_190112483.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/9435484/86244dbc-6581-475d-802d-0efe16b3fd65)

**Comment by RobotsAreCrazy** [comment]
got it installed eventually, i do wish my license covered the adguard vpn tho

**Comment by Versty** [comment]
@RobotsAreCrazy Please download the .apk file from [this link](https://agrd.io/tvapk) and try installing AdGuard again.

**Comment by Versty** [comment]
@RobotsAreCrazy Any updates?
