### ISSUE TITLE
Firewall doesn't held rules

### ISSUE THREAD

**Issue by nightznero** [AdguardTeam/AdguardForAndroid#5165]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

```markdown
A13
Samsung
OneUI 5.1
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Add app into _Firewall_ with custom rules,
(i have added over 200 apps but everytime they are lowered to 30 like it would be max that "NEW" ADG can hold) if there is more apps added after few days they gonna be resetted. its annoying asf cuz i add rules to apps thst i dont have already installed but if rules are reseted even on installed apps guess that are non installed are gone as well

### Expected Behavior

Hold rules as on old best v3 ADG. After update to v4 this bug is still live.

### Actual Behavior

After few days Rules going down like 20 per day or so to max rules 30

### Screenshots

I will update thread after few days with results.
2024.01.13 Apps Rules Counter: 92

https://github.com/AdguardTeam/AdguardForAndroid/assets/61750641/3b8a742a-5d3f-4a25-be69-ab7b221e7b24

### Additional Information

I was mention it in #4885 
(https://github.com/AdguardTeam/AdguardForAndroid/issues/4885#issuecomment-1858571987)
and on mail with devs i was told that its was fixed,spoiler-its doesn't.

**Comment by Versty** [comment]
@nightznero Thank you for reporting! 
We are currently trying to reproduce this issue on our side.

**Comment by nightznero** [comment]
Yesterday i added 3rules,results from today;
2024.01.15 Apps Rules Counter: 85

https://github.com/AdguardTeam/AdguardForAndroid/assets/61750641/99d15250-6878-404b-88b1-74ac622a366d

**Comment by nightznero** [comment]
I would like to share any logs that would be helpful but;
• new rewritten ADG is heavier(well...) for device and battery
• enabling Debug logs for few days non-stop to let them record the issue would fire my phone(legitimate,no joke)

**Comment by Versty** [comment]
@nightznero Hopefully, we will manage to reproduce this bug on our devices so you won't need to collect debug logs on your phone

**Comment by Versty** [comment]
@nightznero Unfortunately, this issue does not reproduce on our Samsung Galaxy, Android 13 with One UI 5.1 device. 
Therefore, we would like to take a look at the logs from your device for further investigation. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Wait for the issue to reproduce (at least one app is missing), then remember the time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5165` number in the subject
      - specify the time when the issue occurred

**Comment by nightznero** [comment]
> @nightznero 
> 
> 1.  Enable debug logging: 
> *Settings -> General -> Advanced -> Logging level -> Debug*
> 
> 2. Wait for the issue to reproduce (at least one app is missing), then remember the time when it happened 
> 
> 3. Collect logs: 
> *Settings -> General -> Advanced -> Export logs and system info* 
> 
> 4. Send this file to devteam@adguard.com:
>       - mention the `5165` number in the subject
>       - specify the time when the issue occurred

How to send logs? For constantly 2days straight have logging enabled at Debug level? and how to specify and verify the time of the issue? Is there any pre-step like maybe u could use my settings and maybe it's something wrong here? Cuz having Debug for 2days looks not so good for my :x

**Comment by Versty** [comment]
@nightznero The apps on your device are changing in some way, we need to find a definite reason for this odd behavior. 
Have you update your apps via store or as .apk installation? 

> i add rules to apps thst i dont have already installed

How have you managed to add a rule for an uninstalled application?

**Comment by nightznero** [comment]
> @nightznero The apps on your device are changing in some way, we need to find a definite reason for this odd behavior. Have you update your apps via store or as .apk installation?

via apk,

> 
> > i add rules to apps thst i dont have already installed
> 
> How have you managed to add a rule for not installed application?

I mean, i added rules to apps but they are already not installed on my device,for most apps i change rules to have in future "just in case" but when lossing a rules for installed apps i belive rules for uninstalled apps also gone as well

**Comment by Versty** [comment]
@nightznero When you uninstall an app, custom firewall rule for this app in AdGuard will be automatically deleted, due to package name does not exist in the system anymore. This behaviour is designed that way. 

Also important to know if you uninstalling the application prior to installing the newer version of this application as .apk, custom firewall rules will be removed in AdGuard as well. Is it your case?

**Comment by nightznero** [comment]
> @nightznero When you uninstall an app, custom firewall rule for this app in AdGuard will be automatically deleted, due to package name does not exist in the system anymore. This behaviour is designed that way.
> 
LOL,why AdGuard team decides to making that? On v3 ADG version before re-written,AdGuard held all of those rules without any issue and weight with that rules(guess like 500rules) still less than the new one version v4 so whats the point of it if for sure it's wasn't made to save storage? So if I switch phones(from X company to Y) all the rules gonna be deleted and only saved for apps that are pre-installed like only Facebook Netflix? Didn't expect to hear that and would know why ADG Team decided to make ADG works like this in re-written app.

> Also important to know if you uninstalling the application prior to installing the newer version of this application as .apk, custom firewall rules will be removed in AdGuard as well. Is it your case?

Hard to say bcs I didn't check that,but I dont think so cuz rules missing just over time,even without using ADG,I add rules,force stop to not working in background,starting using old ADG/RethinkDNS/Blokada/AdAway,after few days opens ADG just to check that rules are missing so

**Comment by Versty** [comment]
@nightznero In case you wish to transfer the list of custom firewall rules from one device to another, install desired apps and AdGuard to a new device. Then export the settings from the original device and import them to the new device, everything will be configured, including custom firewall rules. 


> Hard to say bcs I didn't check that,but I dont think so cuz rules missing just over time,even without using ADG,I add rules,force stop to not working in background,starting using old ADG/RethinkDNS/Blokada/AdAway,after few days opens ADG just to check that rules are missing so

Please pay your attention what happening with applications whose custom firewall rules are disappearing from AdGuard.
Have you reinstall them? Have you removed them? Have you updated them? 
Let me know the results of your observations for further investigation.

**Comment by nightznero** [comment]
> @nightznero In case you wish to transfer the list of custom firewall rules from one device to another, install desired apps and AdGuard to a new device.
> 
You see how new rewritten system is badly compare to old one? I have to install all those apps even when im using em time to time and uinstall them to safe space/battery. ADG Team shall re-think of revert that change cuz rules doesn't store much space in the app but changing that makes just user(s) annoyed
> 
> Please pay your attention what happening with applications whose custom firewall rules are disappearing from AdGuard.
> Have you reinstall them? Have you removed them? Have you updated them? 
> Let me know the results of your observations for further investigation. 
> 
Hmm, one apk has lost rules but was updated away from GP,one with same scenario but rules are stored normally,last app that was on my eye also lost all rules but scenario here was diff,the apk wasn't opened,not updated,didn't changed any of settings-battery,perms,notis.
So its randomly deleted cuz even if apk isn't used still lossing rules :X
Do You have sample device that could use with my setting? i would share all the settings without license and maybe You could verify just inside the file or after load them to app?I would set the rules to app that we both use like e.x fb,spoti,Git,and so on ?

**Comment by nightznero** [comment]
After sometime of not checking,that day become. In firewall 99% apps are gone. Revert to ADG v3 completely. Rewritten ADG v4 is a joke,unfunny in that case.
2024.02.18 Apps Rules Counter: 7
![Screenshot_20240218_140524_AdGuard.png](https://github.com/AdguardTeam/AdguardForAndroid/assets/61750641/f9948da9-4c22-4d34-b159-3e4af8fb5acb)

**Comment by Versty** [comment]
@nightznero Unfortunately, we can not reproduce this issue on our side. 
As long as we do not see reports from other users, this issue may be device or environment specific.

We will continue to investigate this issue if any other user runs into a similar issue.
