### ISSUE TITLE
App not working consistently after last android 14 security update

### ISSUE THREAD

**Issue by chrispoulsen** [AdguardTeam/AdguardForAndroid#5166]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

```markdown
- OS: Android 14 (Security update: January 5,2024) - The security update broke it
- Device: Pixel 6a
- Firmware: build number? UQ1A.240105.002
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

After update adguard does not start automatically.

If I start it manually, icons usually appear in the notification area and the app says it is running  - but it is like it is not started properly - there is 3 flashing dots on that page that never settle and the "on/off" toggle behaves weirdly (jumps  back to "on" automatically or goes to off, while the UI says "Protection is enabled".

If I start a game with ads just after messing with the adguard app, it seems like it is filtering - but after a short while all traces of the app is gone (no filtering, no icons in the notification area).

I tried setting the VPN to always on - That seems to keep (part of?) adguard going - but it is not filtering and when I open the app it says that it is "off"

### Expected Behavior

I expect the app to work. 

### Actual Behavior

Things broke after I installed the January 5 security update (adguard did not automatically start up after reboot and has been acting up ever since). See "issue details for more)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@chrispoulsen I tried repeating this, but I don't get this behavior again. Could you please clarify more exact steps? Are you rebooting/enabling the phone, then after a while the protection turns off or doesn't turn on at all? 
I tried rebooting the phone, then using other apps for a while, but the protection behaves stable and doesn't turn off. 
Please clarify, do you have battery optimization disabled in the phone's system settings for AdGuard?
It would be nice if you recorded a video of the screen with steps of repetition and description of the problem. Are you able to record a video of the screen and send it to devteam@adguard.com?

**Comment by chrispoulsen** [comment]
> @chrispoulsen I tried repeating this, but I don't get this behavior again. Could you please clarify more exact steps? Are you rebooting/enabling the phone, then after a while the protection turns off or doesn't turn on at all? 

The service does not start after reboot (I have tried rebooting a couple of times after the update was applied).

If I open the app and flip the "on/off" toggle, it behaves weird - It looks like it tries to start the background service, but something is not quite right (Sometimes I see the key and shield icons in the notification bar and then filtering seems to work for a short while - and then both icons disappear and filtering is not working anymore).

Battery optimization settings etc. are applied according to your docs and was working perfectly until I applied the Android upgrade.

If I put the VPN as "always on" it does seem to start (the "key" icon is there) but after a short while, I get a notification from the system that the "always on" VPN is not running.

> Please clarify, do you have battery optimization disabled in the phone's system settings for AdGuard? It would be nice if you recorded a video of the screen with steps of repetition and description of the problem. Are you able to record a video of the screen and send it to [devteam@adguard.com](mailto:devteam@adguard.com)?

My optimization settings seems to be correct (same as before the update). I'll try to see if I can get a usable video tonight.

**Comment by maxikuzmin** [comment]
@chrispoulsen hopefully manage to record a video. It would be better if you also attach the logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 5166 number in the subject
specify the exact time when the issue occurred

**Comment by chrispoulsen** [comment]
Did not manage to get anywhere, where I could get a video. 

What usually happens is that I open the app (either the toggle stays on disabled or it automatically jumps to enabled, then the 3 dots flashes on the screen for around 5 minutes and then the app usually crashes/closes. Sometimes with an error (see the attached screenshot, sometimes without error and in a very few cases it seems to actually be running, but then it usually crashes when I open a game and it has to filter ads.

[screenshots adguard-issue.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/13956126/adguard-issue.zip)

The log dump did not seem to complete, the app crashed... But there is a 184MB zip archive in my downloads, I dont think I can mail that?

**Comment by maxikuzmin** [comment]
@chrispoulsen you can mail me a link for a file sharing site where you can put your logs, or you can share the logs right here.
It would be great if you also upload [bugreport](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/#capture-a-bug-report-from-a-device) from the phone so we can see what's going on with the phone system
Please repeat the steps, upload debug logs, bugreport and send this (or attach it to a file share). Don't forget to include the time of the AdGuard crash

**Comment by chrispoulsen** [comment]
I ended up uninstalling and then re-installing, that brought things back in working order

**Comment by maxikuzmin** [comment]
@chrispoulsen if the problem happens again, please reopen the issue
