### ISSUE TITLE
Unable to start protection in root proxy mode with APatch

### ISSUE THREAD

**Issue by j7b3y** [AdguardTeam/AdguardForAndroid#5167]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

```markdown
- OS: Miui 14.0.10.0.TLCCNXM
- Device: Xiaomi 12
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Japanese filter, AdGuard Experimental filter, EasyList

### Issue Details

Steps to reproduce:
1. Grant root privileges to Adguard in Apatch Manager.
2.  Run Adguard.

### Expected Behavior

Protection begins.

### Actual Behavior

Stuck on starting protection.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

- Apatch
[https://github.com/bmax121/APatch](https://github.com/bmax121/APatch)
A kernel-based root solution similar to KernelSU.

I recently migrated to this, but Adguard's behavior is very unstable.
Protection often fails to start, and even when it does, it sometimes crashes.

When I looked at the error log, I found the following error:
```13:06:28.103 [Thread-15] ERROR Native - AGProxyServer: failed to resolve local.adguard.org (no address associated with nodename (7))```

I don't know if it's related, but I hope it helps.
I also attach the exported logs and system information.

[adguard_logs_4.3.199_1501_132702.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/13934952/adguard_logs_4.3.199_1501_132702.zip) (Default logging level)

**Comment by Versty** [comment]
@j7b3y Hi! 

To investigate this issue, we would like you to collect debug logs from your device. 
Please follow the steps below.  

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5167` number in the subject
      - specify the exact time when the issue occurred

**Comment by j7b3y** [comment]
Since then, I've brought in other models to test.
RedmiPad(Miui 14 Global)
Zenfone8(ZenUI)
My APatch solution did not have this problem.
Also, on Xiaomi 12, some apps other than Adguard did not work properly when root privileges were granted.
It wasn't an Adguard-specific issue.

We apologize for taking up your time.

P.S.
When I changed the Xiaomi12 root solution to KernelSU, this problem did not occur, so there may be a problem with APatch specific to Xiaomi12, or there may be something wrong with my environment.
