### ISSUE TITLE
Disable the HTTPS filtering for `jionews` and `jiotv` apps by default

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#5172]
https://github.com/AdguardTeam/AdguardFilters/issues/170599
https://github.com/AdguardTeam/AdguardFilters/issues/170603.
As the user said, there are some issues with apps when only HTTPS filtering is enabled.
I guess you could consider removing it by default for the following apps.
[play.google.com/store/apps/details?id=com.jio.media.jioxpressnews](https://play.google.com/store/apps/details?id=com.jio.media.jioxpressnews)
[play.google.com/store/apps/details?id=com.jio.jioplay.tv](https://play.google.com/store/apps/details?id=com.jio.jioplay.tv)

**Comment by d0x360** [comment]
Do you get a browser page warning you https isn't working on that site but it has a button that lets you proceed?
