### ISSUE TITLE
Днс-блокировка не снимается при использовании стороннего днс.

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#5178]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v3.6.11 (54-1.10.186cl)

### Environment

```markdown
- OS:Android 7
- Device:Asus Z500M
- Firmware:ZenUI
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1.Открыть страницу,которая имеет днс-блокировку, к примеру, в Украине это ya.ru
2.Получить отказ от днс-резолвера в виде **ERR_CONNECTION_RESET**
3.

### Expected Behavior

Чтобы при установленном  стороннем днс-сервера осуществлялся обход днс-блокировку.

### Actual Behavior

Обход днс-блокировку не происходит ввиду непонятных мне причин. Если прописывать днс публичный в браузере ,без включенного приложения Эдгард,тогда на ограниченные страницы заходит мигом,но не с Эдгард, а должно! Эта проблема давняя, и так и никто на это не обратил внимания.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20240118-003148](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/405ee517-5c72-45f4-8000-66724bb7a434)
![Screenshot_20240118-003214](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/541bb18e-c958-42c9-bfdf-070c9faccceb)

</details>

**Comment by NUser2018** [comment]
@Spok1 Эта функция не предназначена для обхода блокировки а только лишь для использования стороннего DNS сервера и шифрования DNS-запросов если это включено и используется в настройках AdGuard и поддерживается выбранным DNS-сервером. Это позволяет скрыть DNS-запоосы от провайдера и иных третьих сторон/лиц, если используется шифрование DNS-трафика. Однако этого может быть недостаточно для обхода блокировки провайдером доступа к тем или иным сайтам. Например в РФ использование этой функции также не позволяет обходить блокировки. То что сайт блокируется по адресу (хотя может блокироваться не только по названию/адресу сайта но и/или по ip-адресу) это не значит что блокировка идёт при помощи отслеживания и подмены/блокировки DNS-запроса. Скорее всего Ваш провайдер (как и большинство провайдеров из РФ у нас) отслеживает и блокирует не DNS-запросы, а мониторит и отслеживает сам весь трафик (при помощи систем контроля и анализа трафика типо DPI например) и когда его система видит в заголовках пакетов трафика от Вас заблокированный у вас ресурс то блокирует этот трафик. DNS это как телефонная книга которая позволяет Вам узнать по адресу сайта буквами текущий ip-адрес сайта даже если он изменился. Но Вам ещё нужно с этим адресом соединиться и это уже зависит от Вашего провайдера и он может этому мешать и блокировать доступ разными методами, в том числе и методом контроля всего трафика и отслеживания в пакетах трафика от Вас наличия адресов и/или ip-адресов заблокированных у вас ресурсов в заголовках пакетов трафика от Вас (а эти данные содержатся в каждом пакете (в его служебных заголовках) трафика от Вас а не только в DNS-запросе)! Поэтому только использование стороннего DNS даже с шифрованием DNS-трафика не гарантирует обход блокировок, хотя как минимум стоит проверить что Вы не только сменили DNS-на другой но и включили шифрование DNS-трафика если это поддерживается выбранным вами сторонним сервером...
Методов обхода блокировок не так уж много и хотя они могут зависеть от конкретной страны, провайдера и региона и используемых провайдером методов блокировки и наиболее эффективными способами обхода блокировки всё ещё остаётся использование прокси или VPN, хотя существуют и некоторые другие альтернативные методы и способы обхода блокировки. Кстати показанная Вами на скриншоте ошибка в браузере очень явно говорит что проблема/блокировка скорее всего не по DNS, а по трафику в целом, как я и предполагаю и подробно описал выше. Хотя вижу что Вы пишете что без AdGuard Вам помогает просто замена DNS в браузере. Вообщем странно конечно. Извините если что не так, просто написал чтобы поделиться своим опытом. Будет интересно что ответит команда AdGuard конечно.

**Comment by NUser2018** [comment]
@Spok1 Также проблема может быть в том что Вы используете старую неактаульную версию AdGuard. Понимаю что скорее всего это вызвано тем что у Вас старое устройство со старой версией Android. Сочувствую. Но нужно понимать что все новые функции, исправления и прочие изменения вносятся именно при выпуске новых версий любого приложения, при этом в старых неактуальных версиях приложений уже ничего не меняется. :(

**Comment by Spok1** [comment]
@NUser2018 
 Также проблема может быть в том что Вы используете старую неактуальную версию AdGuard. 

Такая же проблема была и когда эта версия была актуальная. Чтобы внести ясность,на 4-й версии также не пускает с публичными днс на ограниченный домен. 

>А если наоборот попробовать использовать сторонний DNS но не использовать шифрование DNS-трафика!?

Разницы нет в принципе. 

>Хотя вижу что Вы пишете что без AdGuard Вам помогает просто замена DNS в браузере.

Верно,и это несколько озадачивает,что подмена днс в браузере позволяет обойти днс-блокировку,а смена в приложении Эдгард—нет. И там и там используется шифрование DoH. Не для всех ограниченных доменов в Украине помогает публичный днс,однако для большинства,где ограничение лишь по домену.

**Comment by NUser2018** [comment]
@Spok1 Вот этот online-тест (https://dnsleaktest.com/) хотя бы позволяет проверить что замена DNS действительно работает и после замены действительно используется другой новый выбранный DNS. Лучше сразу проверять через расширенный (Extended) вариант теста. А то ведь провайдеры тем не менее могут и блокировать DNS и просто например перехватывать запросы к сторонним DNS и принудительно перенаправлять их на свой DNS. Когда я проверяю после замены DNS через AdGuard на смартфоне то по результатам этого теста сразу наглядно видно что вместо DNS от провайдера реально используется и применяется другой выбранный мною DNS, например от Google или другой.

**Comment by NUser2018** [comment]
@Spok1 Ещё причина разного поведения у Вас возможно может быть в том что некоторые браузеры помимо шифрования DNS при помощи DoH могут также использовать и шифрование "рукопожатий" при помощи Encrypted Client Hello (ECH). Более подробную информацию о том что это такое можно прочитать по ссылке ниже на примере Firefox, однако вполне возможно что такая фича может быть доступна и применяется и в каких-то других браузерах. Сам я это ни разу не использовал и не пробовал поэтому особо сильно в технические детали не углублялся до этого а только читал что и такое тоже есть. (["Что нужно знать об Encrypted Client Hello (ECH)"](https://support.mozilla.org/ru/kb/understand-encrypted-client-hello)). Но дело в том что AdGuard на данный момент насколько я понимаю и знаю эту технологию не поддерживает.

**Comment by Spok1** [comment]
@NUser2018 
>online-тест (https://dnsleaktest.com/) хотя бы позволяет проверить что замена DNS действительно работает

Да,мне известно про этот тест. Днс судя по тесту используется от гугл, находящейся в Варшаве. Такой же,как и прописанный в браузере,однако обход не происходит. Тема не раскрыта!😒

**Comment by Spok1** [comment]
`@NUser2018 
>online-тест (https://dnsleaktest.com/) хотя бы позволяет проверить что замена DNS действительно работает

Да,мне известно про этот тест. Днс,судя по тесту, используется от гугл, находящейся в Варшаве. Такой же,как и прописанный в браузере,однако обход не происходит. Тема не раскрыта!😒

**Comment by NUser2018** [comment]
@Spok1 Про тест DNS понятно. А другое моё сообщение про особую фичу в браузерах Вы прочитали? Может быть именно в этом причина разного поведения у Вас при замене DNS через браузер и через AdGuard? Какой браузер Вы используете?

**Comment by Spok1** [comment]
@NUser2018 ,читал. Хром в основном. В других форках хромиум также само блокировка обходится,если прописать. Оно-то и не мудрено,движок одинаковый ведь.😁

**Comment by NUser2018** [comment]
@Spok1 Хромом пользуюсь только на смартфоне но сильно с технической точки зрения в него не вникал и не копался, но вот в Интернете нашёл что вроде как ещё начиная с версии 107 Хром также поддерживает технологию Encrypted Client Hello (ECH) и ESNI (Encrypted Server Name Indication).

Подробнее об этом можно почитать по ссылкам ниже, но одна из них .ru так что возможно у Вас без применения средств обхода блокировок она не откроется, хотя я не знаю и возможно у вас заблокированы не все сайты .ru а только конкретные.

[Google Chrome получил экспериментальную поддержку Encrypted Client Hello (ECH)](https://www.comss.ru/page.php?id=11178&ysclid=lrkm8epe1p351699004)

[Вышел Chrome 107 / Хабр](https://habr.com/ru/news/695760/)

Возможно у Вас эта функция в Хроме включена и\или теперь уже она включена возможно у всех по умолчанию.

**Comment by maxikuzmin** [comment]
@NUser2018 спасибо вам за предоставленную информацию!
Идея с ЕСН имеет место быть. В низкоуровневых настройках последней версии 4.3.1 есть функция ECH, но я проверил и выяснил, что ya.ru не имеет ЕСН, поэтому это вряд ли поможет. 
@Spok1 не могли бы вы уточнить, какой ДНС вы используете в AdGuard? Он секьюрный (https://)?

**Comment by maxikuzmin** [comment]
@Spok1 насколько я знаю, в Украине трафик не особо фильтруют, блокируют либо ДНС либо IP. 
Проверили, с любым ДНС всё работает, даже с несекьюрным 1.1.1.1
Возможно ваш провайдер блокирует не только ДНС или IP. У вас есть возможность проверить это с другим провайдером?

**Comment by Spok1** [comment]
@maxikuzmin 
>Не могли бы вы уточнить, какой ДНС вы используете в AdGuard? Он секьюрный (https://)?

Doh от гугл

>Возможно ваш провайдер блокирует не только ДНС или IP. У вас есть возможность проверить это с другим провайдером?

Насколько я выяснил, то как раз днс в основном,ибо если по ip,то заглушка тот час же появляется. Где идёт по днс—ответ от сервера браузер не получает нулевой. На десктоп прописал днс в браузере и доступ разрешён к большинству страниц. С Эдгард же такой номер не прокатывает! Возможности проверить доступ через другого провайдера нет.

**Comment by maxikuzmin** [comment]
@Spok1 в первую очередь нам было бы неплохо взглянуть на ваши расширенные логи, чтобы убедиться в работоспособности блока ДНС. Отправьте их пожалуйста на devteam@adguard.com с указанием времени повторения.

Из дополнительного: было бы неплохо проверить поведение на 4.3.1, а также с другим провайдером, может переставить симку если она есть или подключиться к другому вайфаю

**Comment by maxikuzmin** [comment]
@Spok1 есть новости?

**Comment by Spok1** [comment]
@Spok1,отправил вам журнал,как вы просили ещё вчера. Проверяйте почту.

**Comment by Spok1** [comment]
@maxikuzmin, отправил вам журнал,как вы просили ещё вчера. Проверяйте почту.

**Comment by Spok1** [comment]
@maxikuzmin, отправил вам журнал как вы просили ещё вчера. Проверяйте почту.

**Comment by maxikuzmin** [comment]
@Spok1 вы пробовали повторить это на версии 4.3.1? На другом провайдере не удалось проверить?

**Comment by Spok1** [comment]
@maxikuzmin 

>Вы пробовали повторить это на версии 4.3.1? На другом провайдере не удалось проверить?

Да. Итог тот же.

>Также попробуйте добавить ДНС в AdGuard

В смысле? Днс и так прописаны там,просто выбираешь из списка! Или вы имели в виду что о другое?

>Есть ли ДНС запросы?

Запросы есть и ответы соответственно,однако на указанные домены не пускает.
<details><summary>Details</summary>
<p>

![Screenshot_20240221-122950](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/39f392fc-f064-4f7f-8026-94af952a8349)
![Screenshot_20240221-122955](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/402f858c-1058-42f0-a472-206b6be08714)
![Screenshot_20240221-123748](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/2bf0ef0a-5bdb-42a3-a957-5ddbcda6a230)
</p>
</details> 

>Также уточните, не включен ли у вас Private DNS?

Только в Эдгард.😀

**Comment by Spok1** [comment]
@maxikuzmin 

>Вы пробовали повторить это на версии 4.3.1? На другом провайдере не удалось проверить?

Да. Итог тот же. На мобильном провайдера от водафон всё также не пускает.

>Также попробуйте добавить ДНС в AdGuard

В смысле? Днс и так прописаны там,просто выбираешь из списка! Или вы имели в виду что-то другое?

>Есть ли ДНС запросы?

Запросы есть и ответы соответственно,однако на указанные домены не пускает.
<details><summary>Details</summary>
<p>

![Screenshot_20240221-122950](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/39f392fc-f064-4f7f-8026-94af952a8349)
![Screenshot_20240221-122955](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/402f858c-1058-42f0-a472-206b6be08714)
![Screenshot_20240221-123748](https://github.com/AdguardTeam/AdguardForAndroid/assets/34476664/2bf0ef0a-5bdb-42a3-a957-5ddbcda6a230)
</p>
</details> 

>Также уточните, не включен ли у вас Private DNS?

Только в Эдгард.😀

**Comment by maxikuzmin** [comment]
@Spok1 значит ДНС недостаточно для обхода блокировки. Если запросы от ДНС в журнале есть, значит ДНС идет через AdGuard и фильтрация работает. 
Хоть мы и проверили, что в ya.ru нет ЕСН, тем не менее можете попробовать включить ЕСН в версии 4.3.1 в низкоуровневых настройках, возможно это как то поможет

**Comment by Spok1** [comment]
@maxikuzmin, а почему тогда при прописанном адресе днс в браузере доступ к домену разрешён?

**Comment by maxikuzmin** [comment]
@Spok1 возможно проблема в ЕСН который есть в браузере. Тем не менее мы выяснили, что фильтрация ДНС в AdGuard работает. Как я уже упоминал ранее, мы проверили эту проблему, с нашей стороны эта проблема не воспроизводится.
Судя по логам, запросов к ya.ru у вас не было, возможно системный резолвер “негативно закэшировал” днс-блокировку, попробуйте очистить данные приложений и кэш, возможно это поможет
