### ISSUE TITLE
Filters do not update to the latest version 

### ISSUE THREAD

**Issue by NUser2018** [AdguardTeam/AdguardForAndroid#5179]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1 (4.3.199)

### Environment

```markdown
- OS: Android 13
- Device: realme C25S
- Firmware: RMX3195_11_F21
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Issue Details

Подробное описание проблемы см. далее ниже в секции для подробностей по проблеме.

### Expected Behavior

Фильтры как и ранее нормально обновляются и автоматически и вручную и версии фильтров в приложении не стоят на месте и не отстают сильно от актуальных версий фильтров в источниках фильтров.

### Actual Behavior

Фильтры не обновляются и автоматически и вручную и версии фильтров в приложении стоят на месте и отстают сильно от актуальных версий фильтров в источниках фильтров.

### Screenshots

<details>

![Screenshot_2024-01-18-12-39-19-19_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/7c5e07df-fbe5-4a56-bc38-3b5166a19cab)
![Screenshot_2024-01-18-12-40-15-62_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0ca1861c-9ca8-4403-8222-b3f5b65a7cb2)
![Screenshot_2024-01-18-12-40-48-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/297cbc89-ebd0-468b-95b2-dce256dbd6e4)
![Screenshot_2024-01-18-12-41-16-54_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/25e75028-5f22-4877-a6c4-d6123f5781ac)
![Screenshot_2024-01-18-12-41-34-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/8b523d57-5fd7-4a4f-92f0-0463234c0d17)
![Screenshot_2024-01-18-12-41-49-52_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/86c3f98d-b80d-4777-b005-083fb89113ed)
![Screenshot_2024-01-18-12-42-16-98_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/ea51ffab-db8e-490e-b2f6-d0fbbb49e68c)
![Screenshot_2024-01-18-12-42-45-12_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/37279e70-3c0a-4fc4-95fb-6380f3551e45)
![Screenshot_2024-01-18-12-43-16-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0f178f1a-627c-412c-8da3-894ecf23a7d2)
![Screenshot_2024-01-18-12-43-35-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0b6498b9-ca93-4c02-8ac2-5f388d81ba73)
![Screenshot_2024-01-18-12-44-06-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/f7f78fde-09bc-49a4-951a-a62ac18f9741)
![Screenshot_2024-01-18-12-44-24-15_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/2f63a68c-c59f-4baa-8955-f55db95d6e1a)
![Screenshot_2024-01-18-12-44-46-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0f409a6f-7f56-41a8-a38f-f851c048c570)

</details>

### Additional Information

Столкнулся с непонятной проблемой с фильтрами. И буквально вчера её ещё не было. Сначала подумал что сломалось автоматическое обновление фильтров. Переустановка приложения не помогла. Но в ходе исследования оказалось что проблема гораздо более интересная и странная. По умолчанию актуальная релизная версия 4.3.1 (4.3.199) идёт из коробки с фильтрами от 20-21 декабря 2023 года. После установки приложения при обновлении фильтров принудительно вручную фильтры обновляются (т.е. на блокировку чего-то нужного в РФ не похоже, применение VPN не требуется да и не помогает решить проблему!) но вовсе не до тех версий что лежат в официальных источниках по ссылкам из настроек фильтров в AdGuard. Т.е. фильтры в AdGuard обновляются но почему-то до более старых версий чем лежат в источниках по ссылкам. В дальнейшем автоматически фильтры не обновляются. И обновление фильтров принудительно вручную не помогает. При проверке обновления фильтров принудительно вручную пишет что фильтры актуальны и обновлений нет, однако сами фильтры не обновляются больше (после первого успешного обновления фильтров принудительно вручную) (даже при попытке обновить фильтры принудительно вручную!) и версии фильтров в приложении не соответствуют и сильно отстают от тех версий фильтров что лежат по ссылкам из AdGuard  на источники фильтров в официальных источниках. Скриншоты со сравнением версий фильтров в приложении и в источниках на сервере прилагаются. Мой часовой пояс GMT+04:00.

**Comment by NUser2018** [comment]
Добавлю что под ссылками на источники фильтров с которыми я сверяюсь и сравниваю свои фильтры в приложении и на сервере я имею ввиду вот такие ссылки из настроек фильтров в настройках AdGuard как на скриншоте далее где на скриншоте написано Источник и вот ссылку ниже я и открываю.
![Screenshot_2024-01-18-15-17-31-68_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/10d6d673-a63b-4f4b-937a-0d03686983cb)

**Comment by NUser2018** [comment]
Хм, странно, вроде заработало обновление фильтров. Теперь буду наблюдать как будет работать это дальше в автоматическом фоновом режиме. Поэтому пока прошу тем не менее эту задачу не закрывать. Позднее (но возможно уже только завтра) я сам ещё раз напишу о результатах наблюдений и либо добавлю новую информацию по проблеме если она снова будет происходить либо закрою сам эту задачу если проблема больше не будет повторятся в ближайшее время.

**Comment by NUser2018** [comment]
Попробовал переустановить приложение ещё раз и снова проблема повторяется. Даже при принудительной проверке обновлений вручную пишет что версии фильтров актуальные и обновлений нет, но по факту версии фильтров в приложении отстают (и не на одну а на несколько версий судя по номерам версии!) от версии фильтров по ссылкам на источники фильтров из настроек фильтров в приложении. Новые скриншоты сравнения прилагаются.

![Screenshot_2024-01-18-21-54-03-94_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/7dbc5ee1-8e99-4b5e-b9c8-198e46a42545)
![Screenshot_2024-01-18-21-54-32-66_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/c0a87c15-4986-4ad7-a224-29d76afa66be)
![Screenshot_2024-01-18-21-55-00-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/036575c8-0c7a-49b5-973a-95ab9cbcaa0f)
![Screenshot_2024-01-18-21-55-12-50_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/4d5ad460-6732-4567-b0a3-c6f8c2ae4c1e)
![Screenshot_2024-01-18-21-55-33-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/41b0fac5-da5f-42c6-84ed-a618b2742df1)
![Screenshot_2024-01-18-21-55-48-34_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/7cdc25d6-77bd-4048-a4e1-a8e57de40ddb)
![Screenshot_2024-01-18-21-56-09-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/14b24a96-4401-4534-b18e-68e6c4fb95c8)
![Screenshot_2024-01-18-21-56-40-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/bda9def3-7a56-4975-9286-8565b080b862)
![Screenshot_2024-01-18-21-57-03-86_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/530abb07-527b-4776-a510-1e0b1dbd81dd)
![Screenshot_2024-01-18-21-57-26-92_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/23106c6e-457a-4140-8cac-5df90d4b1448)
![Screenshot_2024-01-18-21-57-57-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/9f44bddd-ded4-4fb0-afef-488fe406c13a)
![Screenshot_2024-01-18-21-58-12-06_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/b1de5d9e-9b67-4700-909b-d88ebc1a0092)
![Screenshot_2024-01-18-21-58-27-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/f5b40015-394c-49d8-a23c-4f22c301b7b5)

**Comment by NUser2018** [comment]
Ещё новая порция сравнительных скриншотов. Даже после проверки обновлений фильтров принудительно вручную версии трёх фильтров в приложении и в источниках по ссылкам отличаются, в приложении более старые.
Хотя в целом обновление фильтров в приложении работает и автоматически и вручную, но версии фильтров в приложении почему-то теперь отстают от версий в источниках даже при проверке обновлений фильтров принудительно вручную.
![Screenshot_2024-01-19-10-14-14-83_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/40c520de-3405-47a0-b774-d8c1eca2f144)
![Screenshot_2024-01-19-10-14-23-21_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/92fa2d6d-e918-4d89-af8f-51643f6fadc5)
![Screenshot_2024-01-19-10-15-00-40_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/6ae3faa7-16e4-4a22-bd9c-4cf17f2c49ee)
![Screenshot_2024-01-19-10-15-22-11_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/5bfbe268-5eee-47c4-b9d3-92c5f97ef959)
![Screenshot_2024-01-19-10-15-36-72_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/37a84c02-6e33-4b0c-8a6c-296e4bff4fea)
![Screenshot_2024-01-19-10-15-55-36_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/534a8284-a1b0-4208-abd9-352f8d1216f8)
![Screenshot_2024-01-19-10-16-07-23_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/85d09120-3bbe-421b-9f1a-a5801d3eed8a)
![Screenshot_2024-01-19-10-16-23-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0ad27eaf-f78e-48fe-a1a7-6c1f6fd1bbe1)
![Screenshot_2024-01-19-10-16-54-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0975a88c-729a-4224-aa7c-b36c94dad96e)
![Screenshot_2024-01-19-10-17-09-65_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/94cc133f-3379-4bf8-9679-4e5849e2bc18)
![Screenshot_2024-01-19-10-17-25-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/bc5fa53a-2134-499b-bbf9-934ba4a0e6b2)
![Screenshot_2024-01-19-10-17-41-43_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/bb635774-97b5-4689-bd05-71925419720c)
![Screenshot_2024-01-19-10-17-58-42_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/0cc9cd54-399c-4b53-8662-d933db68e922)
![Screenshot_2024-01-19-10-18-11-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/AdguardTeam/AdguardForAndroid/assets/43743908/f32f1588-5c23-4274-8c14-02bfc9b3cc66)

**Comment by NUser2018** [comment]
На Windows сложнее проверить, потому что там в приложении в настройках фильтров нет прямых ссылок на источники фильтров. Но похоже и на Windows эта проблема есть тоже. Поскольку сейчас после включения компьютера и обновления фильтров в Adguard Базовый фильтр например таже имеет версию 2.3.18.50 А почему если по скриншотам выше явно видно что по ссылкам в источниках на сервере давно уже есть версия 2.3.18.52!?

**Comment by NUser2018** [comment]
Добавлю на всякий случай что набор фильтров на Android  и на Windows у меня немного отличается. Фильтр мобильной рекламы на Windows у меня естественно не используется. Плюс на Android (как видно на скриншотах выше) для раздражителей у меня используется несколько раздельных фильтров. А на Windows (по старой привычке и потому что когда-то так было по умолчанию) используется единый Фильтр раздражителей, который на Android соответственно отключен.

На Android интервал обновления фильтров стоит на "каждый час" у меня обычно, а на Windows стоит "3 часа".

**Comment by NUser2018** [comment]
Добавил ссылку на эту задачу в давнюю задачу по AdGuard для Windows которая возможно имеет что-то общее с этой моей новой проблемой по Android и в которой также разбиралась весьма странная логика обновления фильтров в Adguard. Самая последняя (на момент написания последнего поста там) раскладка этой логики приводится в [ЭТОМ](https://github.com/AdguardTeam/AdguardForWindows/issues/3718#issuecomment-1247037764) посте. Но существенным отличием на мой взгляд является то что в моём случае с AdGiard для Android не помогает даже принудительное обновление фильтров AdGuard вручную.

**Comment by Versty** [comment]
@NUser2018 Добрый день! 
После каждого удаления и повторной установки приложения AdGuard настройки энергосбережения для приложения сбрасываются в системе и требуется повторная настройка, чтобы фильтры могли обновляться стабильно и с заданным интервалом. 

Если проблема у вас продолжается, закройте AdGuard полностью. В настройках системы снимите любые ограничения энергосбережения для приложения AdGuard. Перезапустите устройство, запустите AdGuard и проверьте обновления фильтров.

**Comment by Versty** [comment]
@NUser2018 Решил ли мой совет проблему с обновлением фильтров?

**Comment by NUser2018** [comment]
@Versty Здравствуйте! То что в случае переустановки приложения по какой-то причине (в том числе для опытов и экспериментов и проверок) нужно заново перенастраивать и отключать в системе Android в настройках смартфона и настройки энергосбережения это понятно, я всегда так делал, делаю и буду делать...

Это на тот момент никак не влияло на ту странную проблему с фильтрами, причем фильтры обновлялись (и вручную и автоматически) но при этом версии фильтров указанные в приложении почему-то сильно отставали от версий фильтров по ссылкам из приложения на источники на сервере... И эта проблема продолжалась не один день... Но сколько точно сейчас уже не помню...

В чем было дело понять не удалось конечно, но я подозреваю что это была какая-то временная, но длительная проблема на стороне серверов с обновлениями фильтров, поскольку как я уже ранее писал даже принудительное обновление фильтров вручную по соответствующей кнопке в приложении не решало эту проблему, т.е. проблема была на этот раз не в том что не работало корректно автоматическое обновление фильтров в фоновом режиме...

На данный момент эта проблема к счастью уже давно не воспроизводится и отставание фильтров в приложении по версиям фильтров от фильтров по ссылкам из приложения в источниках на сервере если и бывает то минимальное в пределах допустимого с учётом интервала автоматического обновления фильтров установленного в настройках в приложении, в моём случае этот интервал установлен давно уже как "каждый час"...

Т.е. так как моменты обновления фильтров на сервере и в приложении разумеется не совпадают то в любом случае может быть такое что на сервере фильтры уже обновились, а в приложении фильтры обновятся только при следующем ближайшем обновлении фильтров когда сработает автоматическое обновление фильтров... Но соответственно эта разница по времени в нормальных условиях и когда всё и везде работает корректно не должна превышать по времени значение интервала автоматического обновления фильтров выбранное в настройках в приложении, т.е. в моём случае это не больше одного часа разницы по времени между обновлением фильтров на сервере (внутри у каждого фильтра к счастью указана метка даты и времени когда он последний раз был обновлен) и в приложении... И к счастью это давно уже так и есть снова как и было ранее до возникновения этой странной проблемы...

Извините что давно сюда ничего нового не писал и за задержку моего этого ответа Вам сейчас...
