### ISSUE TITLE
Wire app compatibility with HTTPS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#518]
https://www.reddit.com/r/Android/comments/4guine/adguard_25_update_is_live_with_https_filtering/d2ol8b6

https://play.google.com/store/apps/details?id=com.wire

**Comment by TPS** [comment]
Umm, #517?!

**Comment by ameshkov** [comment]
Yeah, I had very bad connection lately, made a duplicate

**Comment by Revertron** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/wiki/Resolving-HTTPS-compatibility-issues

**Comment by Revertron** [comment]
@gshumihin The wiki page explains what to do.

**Comment by gshumihin** [comment]
adding com.wire to https exceprions list helps

**Comment by gshumihin** [comment]
Adding prod-nginz-https.wire.com and prod-nginz-ssl.wire.com to exceptions helps.

**Comment by ameshkov** [comment]
Let's add the whole wire.com instead.

**Comment by Revertron** [comment]
Done.
