### ISSUE TITLE
Another language bug

### ISSUE THREAD

**Issue by 0xrxL** [AdguardTeam/AdguardForAndroid#5180]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.35

### Environment

```markdown
- OS: One Ui 6.0
- Device: Samsung Galaxy S23 Plus
- Firmware: BWL3
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open AdGuard app
2. Tap on updates button

### Expected Behavior

The phrase "Aggiornati al:" replaced by "Aggiornati:"

### Actual Behavior

"Aggiornati al:" appears in the DNS filters and userscript section.

![Screenshot_20240120_185426_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/127248639/ac475c8c-2176-4aa8-899c-8a2dde61b3a7)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@0xrxL Thank you! 
Will be fixed in the next version.
