### ISSUE TITLE
File Browser Returns Incorrect URI 

### ISSUE THREAD

**Issue by ncoleman** [AdguardTeam/AdguardForAndroid#5181]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

```markdown
- OS: Android 14
- Device: Pixel 7 Pro
- Firmware: current, all up to date
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to Settings, User Scripts, Add Userscript
2. Click Browse and select a local file
3. The URI to the file is returned in the text box above.

### Expected Behavior

The URI is a valid URI pointing to the correct location of the file.

### Actual Behavior

The URI path separators actually is a mix of single chars ("/") and unicodes for a separator.  The error detection does not appear to be able to handle this and returns an error.

I am unable to proceed past the validator.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20240122-150642](https://github.com/AdguardTeam/AdguardForAndroid/assets/594168/2977d709-b892-4eee-acd3-c7ad5a4da55a)

</details>
<details>

<summary>Screenshot 2:</summary>
![Screenshot_20240122-150650](https://github.com/AdguardTeam/AdguardForAndroid/assets/594168/4b35f103-d320-4142-b8c5-fb5b7a0b9005)

</details>

**Comment by maxikuzmin** [comment]
@ncoleman thanks for waiting! Could you please clarify what file format you're trying to add?

**Comment by maxikuzmin** [comment]
@ncoleman any news?

**Comment by maxikuzmin** [comment]
@ncoleman for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
