### ISSUE TITLE
VPN service integrated into the adbkock app on Android

### ISSUE THREAD

**Issue by zystemdanny** [AdguardTeam/AdguardForAndroid#5186]
### Issue Details

Greetings, I share this idea in which it will help many like me, that the VPN service is integrated within the ad blocker application and its corresponding functions, without depending on the two applications in which they are separated. The user like me for example, I want to use the ad blocker together with the adguard vpn, without depending on using two applications even though there is integration with each other, not only to save memory on the device, but an all-in-one help. The user who wants to use the VPN without the ad blocking application will use it separately as it currently comes, if he wants.

It would be great if you take this suggestion and **thank the adguard team to implement it, you will see that several users will be grateful.**

**Comment by Richiedevop** [comment]
@

**Comment by d0x360** [comment]
I'm the opposite, I wish it worked with other VPN clients but I understand why it doesn't unless it's in proxy mode.  They probably don't want to combine them because the number of people using the VPN is like significantly smaller so it's just added bloat

**Comment by Versty** [comment]
@zystemdanny Thank you for suggestion! 
AdGuard and AdGuard VPN are separate products, each of these applications is designed for specific purpose. 
Therefore, we have no plans to combine them into one application.
