### ISSUE TITLE
Cromite browser support

### ISSUE THREAD

**Issue by anuraganand-15** [AdguardTeam/AdguardForAndroid#5190]
### Issue Details

Cromite browser is a fork of popular Bromite browser which was discontinued.
Adguard doesn't supports ad blocking in cromite while it does in bromite browser.

### Proposed solution

Please add adblocking support for Cromite browser since Bromite is discontinued.

Cromite repository can be found here : https://github.com/uazo/cromite

**Comment by Versty** [comment]
@anuraganand-15 Working on Cromite support! 

Duplicate of #4997
