### ISSUE TITLE
Google News requires a tap-back-tap sequence to open a link instead of a single tap

### ISSUE THREAD

**Issue by colemar** [AdguardTeam/AdguardForAndroid#5192]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

```markdown
- OS: Android 14
- Device: Google Pixel 7 Pro
- Firmware: UQ1A.240105.004
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, Others

### Issue Details

Steps to reproduce:
1. Open Google News App
2. Tap on any news link
3. See a mostly black screen
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/3066000/0ab0eee4-6fb5-4e24-9aa6-7747a91e4050)

4. Go back (swipe to right from left screen border)
5. Tap on the same news link
6. See the news
![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/3066000/45b1224f-70e3-432d-95c3-acfbe2889043)
7. Go back
8. Tap on the same news link
9. See the news

Issue does not happen if AdGuard **HTTPS filter** is off (then I see too much ads).

### Expected Behavior

Only one tap and the news is on display.

### Actual Behavior

Seeing a news requires an additional attempt.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I got adguard_logs_4.3.199_2701_190603.zip
Does it contain personal information?
Should I upload it here?

**Comment by maxikuzmin** [comment]
@colemar I have checked this on my device, but I don't get this behavior. You can send logs to devteam@adguard.com with issue number 5192 and time of recurrence in the description. Also please specify the number of Google news update of app you are using and whether you have "Debug" logging level selected (Settings tab -> General -> Advanced -> Logging level -> Debug) ?

**Comment by colemar** [comment]
@maxikuzmin Email sent as suggested.

**Comment by colemar** [comment]
Logging level was Predefined (not Debug).
Google News version is 5.97.0.597036872

**Comment by maxikuzmin** [comment]
@colemar well, I have the same version of Google News. You need debug logs to investigate the problem. Could you please repeat the steps with debug logs and then send the logs? Don't forget to include the time the problem was repeated and the issue number

**Comment by colemar** [comment]
Sent a new email with debug logs.

**Comment by maxikuzmin** [comment]
@colemar thanks, it will take us some time, please wait

**Comment by maxikuzmin** [comment]
@colemar I noticed that you have HTTPS filtering enabled for Google news. Disabling HTTPS filtering will solve your problem, ads are blocked without HTTPS filtering for Google news

**Comment by maxikuzmin** [comment]
@colemar by default https filtering is enabled for browsers only, but you enabled filtering for Google News. Have you tried disabling https filtering for Google News?

**Comment by maxikuzmin** [comment]
@colemar could you clarify why you think Google News works like a browser? Is it because news opens with separate links?
When I tested this issue, the ads did not display for me, even without HTTPS filtering

**Comment by colemar** [comment]
@maxikuzmin I will better retest with https filtering off to see how many ads show up.
When I tap on a news link Google News directly opens the original web page (it does not open the default web browser app, i.e. Chrome or Firefox). Therefore I believe that setting the https filter off for Google News has the same effect as setting the filter off for Chrome and using Chrome to see the news web page (with many ads).

**Comment by colemar** [comment]
@maxikuzmin Ads in Google News are mostly blocked even with https filter off.
I can't explain why I had the opposite feeling before opening this issue.
However the behavior with the https filter active is strange.

**Comment by maxikuzmin** [comment]
@colemar some applications "breaks" when https filtering is forced, so by default https filtering is enabled for browsers only.
In that case, I'm closing this issue

**Comment by maxikuzmin** [comment]
@colemar before android 7 all apps trusted HTTPS certificates in user store by default, after android 7 apps need to additionally specify network security configuration, but most apps don't provide this option
