### ISSUE TITLE
HTTPS exclusions editing

### ISSUE THREAD

**Issue by Aeruja** [AdguardTeam/AdguardForAndroid#5196]
Hi sorry for hihacking this help section, i don't know where else to submit this..

i want to be able to edit the Android https filtering whitelist on my pc, adding and removing them one by one on my phone is too slow.. Where is the whitelist located on my android phone so i can move it to my pc directly?

**Comment by Versty** [comment]
@Aeruja You can use the `Export Settings` option to get the desired list of https exclusions, modify it on your pc, and then import it back into the application. 

Follow the steps below: 
1. Go to Settings tab -> tap the context menu -> Export settings 
2. Press the `Save` button in file manager 
3. Disable all checkboxes except for `Network settings` in the appeared popup menu
4. Tap the `Export` button 
5. Transfer the archive to your PC, then unzip it 
6. Go to json folder -> 1 
7. Carefully modify "HttpsAllowList" values, then save changes  
8. Zip the folder
9. Transfer it back to your device 
7. Import archive via in-app option (Settings -> Import settings)
