### ISSUE TITLE
Automatically transform rules of custom filters with unsupported syntax in order to be applicable by AdGuard

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#5199]
### Issue Details

Some syntax conventions used by other ad blocker developers like uBlock Origin aren’t supported by AdGuard.

### Proposed solution

Auto-convert unsupported rules in custom filters so that they can be applied by AdGuard: e.g. “##+js([...], [...], [...])” to “#%#//scriptlet('[...]', '[...]', '[...]')”.

**Comment by ESurina** [comment]
AdGuard support both of these syntaxes. Could you please give an example of a rule?

**Comment by DimitrisKalaboukas** [comment]
@ESurina I was under the impression that you automatically convert the supported third-party filters to match AdGuard's syntax, as uBlock Origin does the reverse for yours. But, if you also support rules like:

dropbox.com##+js(trusted-set-local-storage-item, dbx_previews_log_out_download_modal, 2147483647000)

no problem at all.

**Comment by ESurina** [comment]
Unfortunately, such a rule is not automatically converted and we will not be able to make it convert, since we did this on purpose.
