### ISSUE TITLE
Samsung SM-G318H invisible interface.

### ISSUE THREAD

**Issue by evgenievich** [AdguardTeam/AdguardForAndroid#52]
![7391660](https://cloud.githubusercontent.com/assets/11546432/9961436/3ed56478-5e29-11e5-9e09-179f090242b7.png)
http://forum.adguard.com/showthread.php?6824-Adguard-для-Android-Бета-версия-2-0-106&p=60868&viewfull=1#post60868

**Comment by Revertron** [comment]
He claims that this bug emerges after a few tests for updates.
I doubt we can do something about it. It's samsung and 4.4.4...

**Comment by ameshkov** [comment]
Ok, close it if you have no idea

**Comment by vbagirov** [comment]
SME-945-65340 - user with similar problem

Galaxy J1, ANdroid 4.4.4

**Comment by ameshkov** [comment]
Obsolete
