### ISSUE TITLE
Q/RFE: Possible to Disable WiFi/Mobile Connection until AG VPN active?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#520]
@AdguardTeam I know we've had [some discussion about this](https://github.com/AdguardTeam/AdguardForAndroid/issues/2#issuecomment-151726474), but is it possible to disable all data connections until the AG VPN is ready to go?  1 major advantage I see for proxy mode is that Android seems to fail _all_ (wifi) data connections until AG is active, & therefore filtering.  How is it possible to emulate this behavior w/ VPN?

Is it possible to run a sort of hybrid proxy/VPN mode, where all data connections fail until AG is active, then switches over to VPN when permission (via Android VPN prompt) is given for that?  I envision it as configuring AG for VPN, ___&___ also setting up for proxy in Android data settings, so as many connections are blocked as possible until AG VPN is fully functional.  Also, on AG shutdown (perhaps when device itself shuts down or when Android chooses to close AG, as well), disable data via Android wifi/mobile settings (maybe airplane :airplane: mode, but with calling enabled) until whenever AG restarted.

Is this kind of setup possible?  The biggest end-run around AG I find is during the critical times from when AG has been shutdown 'til the time it's active again.  Under proxy-mode, no real problem, as data is shutdown (nothing to proxy _through_), but VPN-mode, when _not_ active, allows an unfiltered, active connection, so many apps, especially, download ads to cache & display when AG is active, but the horse is already out of the barn, so to speak.

What's prompted this idea, in part, was the observation that AG seems to exist happily in :airplane: mode (doesn't need to disable or restart itself), but instantly filters whenever the data connection returns.

**Comment by ameshkov** [comment]
You can simply turn off the auto-pause in Adguard's low-level settings

**Comment by ameshkov** [comment]
pref.vpn.disable.pause

**Comment by ameshkov** [comment]
What's important is when AG VPN is down we can't do anything to the network connection. So all this is possible ONLY when VPN is active. It's possible to try different VPN configurations to achieve this though.

**Comment by TPS** [comment]
I _do_ use `pref.vpn.disable.pause` with great success — it's how to achieve `pref.vpn.disable.data.when.inactive` that's got me stymied.… :wink:

**Comment by ameshkov** [comment]
I just don't get the purpose of this feature request.

The only thing I can think of now is to automate it with tasker, turn plane mode when AG goes off.

**Comment by TPS** [comment]
I find there are a number of apps I use regularly (CleanMaster & family, mostly, but various others, also) that seem to poll ad servers regularly at times when I have an internet connection, but AG isn't yet active (usually bootup, but also when Android takes the initiative to boot it out of memory) to cache ads to display later.  Other apps, which _don't_ cache, are blocked perfectly, but these sneaky apps just keep displaying the same ads until I manually clear that cache _or_ until next time the ad cache can be refreshed with current ads.

**Comment by ameshkov** [comment]
Yep, I got it, but isn't `pref.vpn.disable.pause` enough in that case?

**Comment by ameshkov** [comment]
Also there always will be some race condition on device boot. Cleanmaster may start before AG and load something.

**Comment by TPS** [comment]
`pref.vpn.disable.pause` isn't enough _precisely_ because of the race condition (& related), though this is solved naturally on proxy-mode by Android's handling of such connections, so the above are a [couple of separate ideas](#issue-152706240) of how to plug that gap.

FYI, CleanMaster _always_ starts 1st of my user apps.

**Comment by ameshkov** [comment]
Proxy won't be enough as there're lots of apps ignoring proxy settings.

> FYI, CleanMaster always starts 1st of my user apps.

I doubt it, BOOT_COMPLETED is not an ordered event:
http://stackoverflow.com/questions/6038806/android-service-boot-order

**Comment by TPS** [comment]
I dunno where CM gets some of its "special powers" (maybe it's :alien: tech), but, without root, it _always_ loads even before my _launcher_ (which I manually choose each bootup), as evidenced by its notification bar icon.  Nothing else shows up there until some time after launcher, err, launch. :wink:

**Comment by ameshkov** [comment]
Or maybe your launcher needs more time for initialization, events processing is asynchronous.

**Comment by TPS** [comment]
>maybe your launcher needs more time for initialization

:confused:  I don't understand what you mean.  All I know is I can leave my tablet _overnight_ booted up, sitting at the "Which launcher?"-equivalent menu, & the only thing in the notification bar will be CM.…

**Comment by ameshkov** [comment]
> I don't understand what you mean.

Android sends BOOT_COMPLETED event to some app. This app starts a separate thread to process this event. The same happens for all apps.

For instance, your launcher may need 5 seconds to prepare everything and start, while CM needs 3 seconds and that's why it always seems to be first.  The problem is that you can't know which app has actually received this event first.

> I've not run into any myself, but CM-family, in particular, do seem to adhere to proxy settings.

You can't be sure for all third party components. For instance, mobile analytics SDK often don't use

**Comment by TPS** [comment]
>For instance, your launcher may need 5 seconds to prepare everything and start, while CM needs 3 seconds and that's why it always seems to be first.

As I said, CM is fully launched _before_ I even choose which launcher-shell to run.  I think I'm less sure that I'm reporting on how to solve that kind of race condition, & moreso how to get AG started earlier than other things.

For instance, here's the phenomenon that I reported earlier & can replicate across all my devices:

<details> 
 <summary>1:35am:</summary>
![screenshot_2016-05-16-01-35-20](https://cloud.githubusercontent.com/assets/185902/15293225/094a2278-1b55-11e6-93c8-7473231e01e2.png)
![screenshot_2016-05-16-01-35-05](https://cloud.githubusercontent.com/assets/185902/15293233/12b9630a-1b55-11e6-995e-34dd506433dd.png)
</details>

<details> 
 <summary>___10:27am!___:</summary>
![screenshot_2016-05-16-10-27-04](https://cloud.githubusercontent.com/assets/185902/15293294/4ff7fbbe-1b55-11e6-8a24-e6b117879e72.png)
![screenshot_2016-05-16-10-27-25](https://cloud.githubusercontent.com/assets/185902/15293295/537c65d6-1b55-11e6-942f-b63494ff2f70.png)
</details>

As you can tell, I think I prevented `BOOT_COMPLETED` (just as an extreme-case example) for ~9 _hours_, yet CM &, apparently, [BOINC](https://play.google.com/store/apps/details?id=edu.berkeley.boinc) (which I started running quite recently) startup & run quite happily.  Can AG do whatever _they_ do?  That would solve enough of this sufficiently that the above-mentioned data-disabling would be probably unnecessary?

**Comment by ameshkov** [comment]
> Can AG do whatever they do? That would solve enough of this sufficiently that the above-mentioned data-disabling would be probably unnecessary!

@TPS I am still sure that they don't do anything specific.

Can you get the logcat log just after the device boot?

**Comment by TPS** [comment]
:airplane:

**Comment by Revertron** [comment]
@TPS As a workaround you can try to set some fake DNS server for your Wi-Fi connection (like 1.2.3.4). After that in advanced settings in Adguard set true DNS servers (like from Google - 8.8.8.8, 8.8.4.4).
Then when your device boots up, and apps start, they will get errors like "No host found", but after Adguard starts you will get normal connections :)

**Comment by TPS** [comment]
@Revertron That's actually an ___excellent___ idea, but 1 of the reasons I was so excited by [`pref.vpn.dns`](https://github.com/AdguardTeam/AdguardForAndroid/issues/139) is that I've no exposed System GUI for _DHCP_ IP address __&__ _static/custom_ DNS.  Any other ideas?

**Comment by Revertron** [comment]
@TPS Don't you have them in wi-fi connections options interface?

**Comment by TPS** [comment]
@Revertron I've option for _either_ DHCP _or_ static (no mix/match for DHCP IP & static DNS on Android 4.4.2), & I need to use DHCP for my (common but) fussy router. :cry:

**Comment by TPS** [comment]
Just as a note:  This is 90% solved with the implementation & then proper configuration of #776, along with [an automated external app](https://github.com/AdguardTeam/AdguardForAndroid/issues/520#issuecomment-216907715).

**Comment by TPS** [comment]
~~#774→~~#760 solved this for me!
