### ISSUE TITLE
Custom Userscripts don't update

### ISSUE THREAD

**Issue by ESurina** [AdguardTeam/AdguardForAndroid#5203]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

- OS version: 11
- Device: ONEPLUS

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Make a file on GitHub with userscript
2. Add this userscript to AdGuard via link
3. Change name and version in the file
4. Tap on update button on the main screen of AG
5. It says the userscript is updated
6. Open the userscript's details

### Expected Behavior

Userscript's name and version were updated

### Actual Behavior

Userscript's name and version weren't updated

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Also **Reinstall** button on userscript's details tab doesn't make name and version update.

**Comment by acediat** [comment]
Closed because userscripts can’t change the name, as it serves as an identifier for the script.
