### ISSUE TITLE
Re: #5108

### ISSUE THREAD

**Issue by terrorist96** [AdguardTeam/AdguardForAndroid#5204]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Can I please get an answer to the question posted in #5108? I didn't want to have to make a new issue but it's been over 3 weeks now that I've been patiently waiting.

**Comment by Versty** [comment]
@terrorist96 I apologize for the long wait.
Excluding the Tesla application from filtering is better than completely disabling IPv6 filtering.
