### ISSUE TITLE
Google Play: one.belousov.wordgame - error `no internet`

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#5209]
https://github.com/AdguardTeam/AdguardFilters/issues/172507.
With AdGuard protection enabled, the app reports that there is no internet.
STR:
1. Disable all the modules in our app
2. Leave the global protection
3. Install the app [https://play.google.com/store/apps/details?id=one.belousov.wordgame](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Done.belousov.wordgame)
4. Open it
5. Skip the tutorial
6. Choose `слово дня`
7. You will see the same error as in [the first screenshot](https://cdn.adguard.info/sitereports/ozhy4zbgqw0g0g84www4o00ccgwgsc6ljs2sv1xc0w.png?nc=1) from the report.

**Comment by ESurina** [comment]
Some applications use special ways to protect their traffic and we are looking for a way to filter such applications.
Please take a look at this issue: [#4827](https://github.com/AdguardTeam/AdguardForAndroid/issues/4827)

**Comment by ESurina** [comment]
This error occurs due to HTTPS filtering. We will make it disabled by default for this application. In the meantime, you can go to App management -> click on this application in the list -> disable HTTPS filtering.
