### ISSUE TITLE
Instagram.com pages are randomly loaded blank

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#521]
User report:
> Sometimes, a site will load up blank, other times it loads fine. If it's blank and I refresh a few times, it loads. Other times, I keep refreshing and it stays blank. In this case, it's an Instagram page.

Default settings + HTTPS filtering turned ON

@gshumihin could you please test it?

Try refreshing it with a different period, 5-10-15-30-60 seconds.

**Comment by gshumihin** [comment]
Cannot reproduce this bug neither with 4G, nor with wi-fi. Tried with chrome stable. Do you have info about user's browser?

**Comment by ameshkov** [comment]
I've requested a log

**Comment by ameshkov** [comment]
Ticket ID: HNY-710-96397

**Comment by gshumihin** [comment]
There's nothing suspicious in user's logs. And i still cannot reproduce this issue.
