### ISSUE TITLE
Basic firewall 

### ISSUE THREAD

**Issue by efficientwrite** [AdguardTeam/AdguardForAndroid#5211]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Logs show what apps are making connection, is it possible to enable basic firewall without features like if they are used with screen off or in background without enabling usage access?.

**Comment by ESurina** [comment]
It's not possible to enable firewall without enabling usage access.
