### ISSUE TITLE
Some screens only load after locking and unlocking the screen

### ISSUE THREAD

**Issue by selpats** [AdguardTeam/AdguardForAndroid#5212]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.119

### Environment

- OS version: Android 13
- Device: Redmi Note 11 Pro 5G

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Открыть настройки фильтрации приложения или вкладку защита 
2.
3.

### Actual Behavior

Страница не открывается вне зависимости от времени ожидания, помогает только блокировка и разблокировка экрана

### Screenshots

<details><summary>Screenshot 1</summary>

https://github.com/AdguardTeam/AdguardForAndroid/assets/71388521/6a62cdb8-f2d0-4668-be48-c595b158d5c5

</details>

**Comment by maxikuzmin** [comment]
@selpats было бы неплохо получить ваши логи

- Включите ведение отладочных логов:

Настройки -> Основные -> Расширенные -> Уровень логирования -> Подробный

- Воспроизведите проблему, зафиксируйте точное время, когда это произошло

- Соберите логи:

Настройки -> Основные -> Расширенные -> Экспортировать логи и информацию о системе

- Отправьте этот файл по адресу devteam@adguard.com:

укажите номер 5212 в теме письма
укажите точное время, когда возникла проблема

**Comment by selpats** [comment]
Отправил логи

**Comment by maxikuzmin** [comment]
@selpats мы изучили ваши логи, но для более полного понимания, могу я вас попросить еще раз записать расширенные логи? 
Необходимо выставить расширенные логи -> закрыть приложение через кнопку "Выход" на вкладке настроек -> открыть приложение и повторить проблему
Отправьте логи на тот же адрес

**Comment by maxikuzmin** [comment]
@selpats есть новости?

**Comment by selpats** [comment]
@maxikuzmin 21ого с той же почты отправил, сюда отписать забыл, извините

**Comment by maxikuzmin** [comment]
@selpats спасибо, вернусь к вам чуть позже после изучения

**Comment by maxikuzmin** [comment]
@selpats в логах видно, что вы сначала приложение закрыли, потом выставили расширенные логи через час, затем повторили проблему.

Как я уже писал выше, необходимо идти по следующей последовательности:
выставить расширенные логи -> закрыть приложение через кнопку "Выход" на вкладке настроек -> открыть приложение и повторить проблему

Необходимо, чтобы старт приложения попал в расширенные логи, пожалуйста перезапишите логи

**Comment by selpats** [comment]
Не обновлял ни систему, ни приложение, но по какой-то причине проблема больше воспроизводится с прошлой недели примерно. Аналогичное поведение было как минимум в декабре, но тогда ещё и страница статистики не грузилась. Возможно, позже проблема вернётся.

**Comment by maxikuzmin** [comment]
@selpats я правильно понял, что проблема на данный момент не воспроизводится?

**Comment by selpats** [comment]
На данный момент да.

**Comment by maxikuzmin** [comment]
@selpats в таком случае я пока закрою ишью. Если проблема в будущем снова вернется, пожалуйста переоткройте ишью
