### ISSUE TITLE
Adguard Premium 4.3.1 and Bank of America Mobile app Camera for Deposits

### ISSUE THREAD

**Issue by ubiakamera** [AdguardTeam/AdguardForAndroid#5213]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

431

### Environment

- OS version:  Android 14
- Device: Samsung Tab S8 

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Installed apk to tablet Samsung Tab S8
2. Enabled and updated lists per prompts
3. Enabled Firewall
4. Opened BofA Mobile app to deposit checks, camera is black, had to toggle back and forth between Adguard on/off and back to BofA app without closing either app to be able to take image of front and back of check.

### Expected Behavior

Expected camera to work normal in Bank of America mobile app for deposits

### Actual Behavior

Camera was black, no image until back and forth toggle between Adguard on/off/on/off to be able to take front and back images of deposit checks

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ubiakamera** [comment]
To be able to take each image (front image, back image), AdGuard must be toggled off/on.

Then take deposit image on BofA mobile app.

Repeat once more for the 2nd image (front or back).

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5213` number in the subject
    - specify the exact time when the issue occurred

**Comment by ESurina** [comment]
Could you please go to App management -> tap on BofA app in the list -> disable HTTPS-filtering and let me know if the problem reoccurs?

**Comment by ubiakamera** [comment]
HTTPS Filtering IS already Disabled and has been from the outset, from initial setup

**Comment by ESurina** [comment]
Then could you please try to disable *Route traffic through AdGuard* switch for the app and let me know if the problem reoccurs?

**Comment by ubiakamera** [comment]
Where is this?

**Comment by ESurina** [comment]
Enable the main switch on the Home screen, then go to App management -> tap on BofA app in the list and disable *Route traffic through AdGuard* switch and let me know if the problem reoccurs.

**Comment by ubiakamera** [comment]
Did just so > disable Route traffic through AdGuard switch > Camera screen is black, no image on BofA app

**Comment by ubiakamera** [comment]
added com.infonow.bofa as instructed

one image (backside) worked, then front image was black and had to toggle adguard on.off.on

**Comment by ESurina** [comment]
Could you please leave the app in the list of excluded apps, enable debug logging, reproduce the issue and send us logs?

**Comment by ubiakamera** [comment]
sent to Devteam with same 5213 subject line

**Comment by ESurina** [comment]
If you enable any other VPN, does this problem occur?

**Comment by ubiakamera** [comment]
Unsure as I do not have any other VPN installed or available to test

**Comment by ESurina** [comment]
We can't fix this problem at the moment. We suspect that it is on the side of the banking application. We will be able to check this only if you have the opportunity to install a VPN or if another user with the same problem has this opportunity. If the banking application works properly with other VPNs, then please re-open the issue.
