### ISSUE TITLE
Export / Import settings in v.4.3.1

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardForAndroid#5217]
### Issue Details

I don't seem to be able to find export/import settings in Adguard v.4.3.1

### Proposed solution

Implement the feature

### Alternative solution

Install an older version

**Comment by Versty** [comment]
@jbionic2016 This option is already implemented and can be found in the context menu of the Settings tab. 

(Settings tab -> 3 dots in the upper right corner of the screen)
