### ISSUE TITLE
app still getting through firewall

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardForAndroid#522]
i disabled access to internet completely for an app and i look at my dns logs on my computer (using opendns) and it still allowed the data through even though it shows me a notification that the app was disallowed internet access. how is this possible if i blocked internet access for the app? 

app link: https://play.google.com/store/apps/details?id=com.alensw.PicFolder&hl=en

**Comment by ameshkov** [comment]
DNS requests are executed by a "system" app, not the app in question.
