### ISSUE TITLE
No details for failed filterlist update

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#5220]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v.4.0n39

### Environment

- OS version: Android 12
- Device: OnePlus Nord N200 5g

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Legitimate URL Shortener

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, I don't care about cookies

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter, RU AdList - Counters

### Other

AdGuard Experimental filter

### Which DNS server do you use?

Open DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Update from main screen
2. Wait for updates to complete
3. Note messages re: successful & failed filterlists.  When "successful", can be tapped to see which lists updated

### Expected Behavior

Tapping on "failed" message should reveal which filterlist(s) didn't update

### Actual Behavior

Nothing happens when "failed" message tapped

### Additional Information

This developed several nightly versions ago.  I just needed a chance to put together a whole new issue.  Sorry for the delay!

added by @Versty: this issue is also persist for failed update of userscripts

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention! We will fix this in the next versions.

**Comment by TPS** [comment]
@ESurina, @Versty: Is this still on the radar?  It seems relatively simple, but I haven't seen any nightlies that solve this.
