### ISSUE TITLE
Adguard randomly kills itself when automatic proxy is enabled 

### ISSUE THREAD

**Issue by TheWrathRF** [AdguardTeam/AdguardForAndroid#5221]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4 nighly 29

### Environment

- OS version: Crdroid 10.2 
- Device: Xiaomi Redmi Note 8

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Automatic proxy

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist

### Other

Filter unblocking search ads and self-promotion

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Steps to reproduce:
1. Automatic proxy is enabled without restrictions 
2.  Getting out from app
3. Chilling with other things doesn't matter what is it.

### Expected Behavior

Automatic proxy should work in background without killing itself randomly.  

### Actual Behavior

The service kills itself randomly it can happen in any time. The Adguard status notification disappears and all Adguard services stop immediately and the internet  connection does not work until I reopen the app. When you open the app again it enables the automatic proxy service again but then same thing happens. No restrictions or anything just happens when I go with automatic proxy service. VPN mode works without these issues.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Contact with me if you want some extra informations about it.

**Comment by maxikuzmin** [comment]
@TheWrathRF for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
