### ISSUE TITLE
Nested Settings Indicator

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#5225]
### Issue Details

Currently, there are some settings which have an indicator (arrow pointing right) which indicate that there are further settings within them (nested settings). See the screenshot below. The "General", "Content blocking" settings have this arrow as seen below:

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/6959116/1acb29e1-a54e-4f92-9e73-cda604e877ab)

However, this is not included for all the settings which have nested settings within them.

For example, navigate to the following page:

1. Open AdGuard and navigate to the second tab ("Protection" page).
On this page, you will see various options (Ad blocking, Tracking protection, Firewall, etc.). These all have nested settings under them but they do not have the indicator arrow on them.

Therefore, the user needs to know which settings are nested and which are not. Many times, when we click on a setting to see the settings under them and since there are none, the radio button besides that gets toggled by mistake thereby restarting protection.

An indicator arrow would indicate that there are further nested settings
A setting without any indicator would indicate that there are no further nested settings and that is the only setting.

### Proposed solution

Include the indicator arrow for all the settings in the app that have further settings under them (nested settings) on every page.

How the "Protection" page could instead look is shown below with the indicator included as an exampe:

https://ibb.co/YZtnpZd

### Alternative solution

The user would need to click on a particular setting not knowing if there are further nested settings under them or not.

**Comment by ESurina** [comment]
We are currently using another further settings indicator if the setting has a toggle. It is a vertical divider between the name and the switch.

![Screenshot_2024-02-27-11-23-51-856_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/138680450/21c45edf-b480-41b1-a937-4b7298c7d4e2)

**Comment by Nzzyme** [comment]
> We are currently using another further settings indicator if the setting has a toggle. It is a vertical divider between the name and the switch.
> 
> Well, the vertical bar looks to be like a seperator and a normal user would not know that there are further nested settings under that. Can you therefore replace the vertical bar with the original arrow (pointing right) as it conveys to the user that there are further settings. I think it should be easy to implement.

**Comment by ESurina** [comment]
Unfortunately we have objective reasons not to add these arrows, despite the fact that we wanted to do it.
