### ISSUE TITLE
Block .apk downloads, including 302 status code redirects

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardForAndroid#5229]
### Issue Details

Данная ветка появилась как продолжение данного тикета https://github.com/AdguardTeam/AdguardFilters/issues/173065 

Не помешала бы возможность блокировки загрузки apk-файлов через браузер(ы). В идеале было бы иметь блокировку любых файлов или файлов выборочных форматов/расширений.

### Proposed solution

Нужна возможность пресечения загрузки apk файлов или файлов указанных форматов. По возможности "тихо", без всяких алертов и уведомлений.

**Comment by sfionov** [comment]
@Baltazar500 `.apk^$important` не работает из-за неприятного [бага в CoreLibs](https://github.com/AdguardTeam/CoreLibs/issues/1863). В качестве воркэраунда можно использовать правило `.apk^$all`

**Comment by Baltazar500** [comment]
@sfionov, спасибо. Ссработало. И на appbazar и на github'e. Правда вышибает на заглушку

![2024 02 23_16 37 39~01](https://github.com/AdguardTeam/AdguardForAndroid/assets/12525093/b7e20cb4-5b44-44cd-8def-3afea61814e9)

где всё равно можно тыкнуть "продолжить", но это уже намного лучше, чем ничего :)

**Comment by Versty** [comment]
Solution: add the `.apk^$important` (currently not working due to the bug, will be fixed soon) or `.apk^$all` rule to ad blocking user rules.

**Comment by Baltazar500** [comment]
А может не стоило закрывать запрос ? Жёсткое пресечение загрузки apk (или даже списка указанных расширений) без какого - либо уведомления было бы уместно, чем такой костыль.
