### ISSUE TITLE
Re: #5108

### ISSUE THREAD

**Issue by terrorist96** [AdguardTeam/AdguardForAndroid#5230]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Can I please get an answer to the latest question posted in #5108? This is the second time I've had to make a new issue just to get attention back to the original issue. See #5204.

**Comment by Versty** [comment]
@terrorist96 Thank you.
The question from #5108 is answered.
