### ISSUE TITLE
Automatic Proxy (Root) does not work with mobile data connection

### ISSUE THREAD

**Issue by mitomenai** [AdguardTeam/AdguardForAndroid#5231]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

- OS version: Android 13
- Device: Pixel 5

### HTTPS filtering

- [ ] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Automatic proxy

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Enable Automatic Proxy routing.
2. Enable DNS filtering with Cloudflare DNS.
3. Turn off Wifi and switch to mobile data.

### Expected Behavior

AdGuard DNS continues to function and DNS lookups appear in recent activity. Visiting https://1.1.1.1/help should indicate that Cloudflare DoH.

### Actual Behavior

AdGuard DNS filtering is no longer functional and DNS lookups do not appear in recent activity. Visiting https://1.1.1.1/help indicates that the device is using the carrier's IPv6 DNS address.

### Additional Information

This is likely related to #4976 - Automatic Proxy functions on wifi and completely fails when switching over to mobile data. I believe it may be related to the fact that T-Mobile is only IPv6. VPN routing works pretty well, however my impression for when I purchased the $80 license was that I would be able to use root instead of VPN. After spending 12 hours fighting this problem, it appears to not be the case.

Is there any workaround for the carrier hijacking the DNS?

**Comment by Versty** [comment]
@mitomenai Thank you for reporting. 
We have tried to reproduce the described behaviour on our side, but to no avail. Therefore, we would like to take a look at the logs from your device. Please follow the steps below.

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5231` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@mitomenai Any updates?

**Comment by DrAnonym666** [comment]
Same here! With root a very bad connection. From page load errors to no connection at all. Xiaomi Redmi Note 10 Pro. Latest Magisk. Floor Rome.

**Comment by Versty** [comment]
@DrAnonym666 Have you sent the logs from your device as requested in the comment above?

**Comment by luxontw** [comment]
> @DrAnonym666 Have you sent the logs from your device as requested in the comment above?

A log of when this situation occurred has been sent to the specified email. Please check it. Thank you.

**Comment by Versty** [comment]
@luxontw Thank you! 
We received the logs and are investigating.

**Comment by harkirtancr7** [comment]
I thought I was the only one. this makes me happy

**Comment by harkirtancr7** [comment]
any updates would be appreciated!!

**Comment by harkirtancr7** [comment]
> > @DrAnonym666 Have you sent the logs from your device as requested in the comment above?
> 
> A log of when this situation occurred has been sent to the specified email. Please check it. Thank you.

you got it working yet?

**Comment by sfionov** [comment]
Hello! Can you please try with 4.6 release or the latest nightly?

**Comment by Versty** [comment]
@mitomenai Any updates on the issue with AdGuard for Android 4.6.1?

**Comment by Versty** [comment]
Closed due to no response from affected users @mitomenai @luxontw @harkirtancr7 @DrAnonym666. 
Please reopen if the issue still persists with AdGuard for Android 4.6.1

**Comment by harkirtancr7** [comment]
it's working flawlessly now! thank you
