### ISSUE TITLE
Language-specific filter "Other, Other" 

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5232]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Что это за фильтр такой еще

![Screenshot_20240223_100826_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/f08a6e18-83db-4581-83ee-37586cc7f312)

Да и зачем дважды писать **Прочее, Прочее**? Одного раза достаточно.

**Comment by Versty** [comment]
@Cursone Спасибо, что сообщили об ошибке, мы ее исправим. 
Опция включает фильтр `Dandelion Sprout's Serbo-Croatian List`.
