### ISSUE TITLE
Временной промежуток

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5234]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

На версии AdGuard 4.3.1

Если выбрать показывать за последние 24 часа, то не понятно за какой промежуток времени показывает

![1](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/62f93a16-b868-463f-ac5f-f549bcd51fb6)

На версии AdGuard 3.6.11

Данный промежуток был с 00:00:00 и до 23:59:59

**Comment by Versty** [comment]
@Cursone Добрый день! 

В данном случае статистика отображается за последние 24 часа. То есть, если отталкиваться от вашего скриншота, приложение отображает собранную статистику с 15:13 предыдущего дня до 15:13 текущего.
