### ISSUE TITLE
Самовольное отключение

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5235]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

У меня телефон - **Huawei Y6p**, на нем установлен браузер

![Screenshot_20240226_151108_com huawei browser](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/46280e2b-d34f-47a6-a938-8fa6adb4a60c)

Так вот, если запустить этот браузер, то **AdGuard 4.3.1** начинает как в не себя показывать количество заблокированного и просто отключается. Приходится заново запускать  **AdGuard 4.3.1**, так понимаю это происходит из за того что он физически не справляется с объёмом блокировки.

Если не пользоваться данным браузером, то AdGuard 4.3.1 не отключается и ведет себя корректно, но при использовании данного браузера самовольно отключается.

**Comment by ESurina** [comment]
Для диагностики и решения Вашей проблемы, нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Включите подробный уровень логирования:
*Настройки AdGuard  --> Основные  --> Расширенные  --> Уровень логирования  --> Подробный*
2. Воспроизведите проблему. Запомните точное время воспроизведения проблемы, оно понадобится нам, чтобы найти соответствующие записи в лог-файле;
3. Соберите логи:
*Настройки AdGuard  --> Основные  --> Расширенные  --> Экспортировать логи и информацию о системе*
4. Отправьте файл по адресу `devteam@adguard.com`. Также укажите номер задачи Github и время воспроизведения проблемы.

**Comment by ESurina** [comment]
К сожалению, не можем открыть ссылку, которую вы отправили. Пожалуйста, пришлите логи в форме вложения к письму в обращении или в формате файла на [devteam@adguard.com](mailto:devteam@adguard.com).

**Comment by ESurina** [comment]
@Cursone напоминаю вам, что мы ждем ваши логи

**Comment by ESurina** [comment]
Переоткройте, пожалуйста, задачу, если проблема снова повторится.
