### ISSUE TITLE
Crash with Indonesian language 

### ISSUE THREAD

**Issue by robifr** [AdguardTeam/AdguardForAndroid#5236]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4 nightly 33 (if im not mistaken)

### Environment

- OS version: android 13
- Device: redmi note 11

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### Issue Details
edited by @Versty 

Steps to reproduce:
- v4.4 nightly 34 is installed
1. Go to Settings tab -> General -> App language
2. Select the `Indonesia` language 

<details><summary>Original text</summary>

i'm not sure how it crashed, but it does happen since nightly 20 or so when i set the language to indonesia.

</details>

### Expected Behavior
The app works as usual, the language has changed to Indonesian

### Actual Behavior

The crash has occurred 

02-27 23:12:34.484 25524 25524 E AndroidRuntime: FATAL EXCEPTION: main
02-27 23:12:34.484 25524 25524 E AndroidRuntime: Process: com.adguard.android, PID: 25524
02-27 23:12:34.484 25524 25524 E AndroidRuntime: java.lang.IllegalStateException: Fragment NavHostFragment{f958b5c} (60895b02-7cb7-4624-9fb2-5fcf0f724b7d) has not been attached yet.
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:32)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at v7.a.s(AbstractRecyclerPackager.kt:34)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at v7.a.l(AbstractRecyclerPackager.kt:16)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at v7.a.w(AbstractRecyclerPackager.kt:61)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at v7.e0.b(LinearRecyclerPackager.kt:24)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at v7.e0.a(LinearRecyclerPackager.kt:27)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at com.adguard.android.ui.fragment.HomeFragment.e0(HomeFragment.kt:10)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at com.adguard.android.ui.fragment.HomeFragment.I(HomeFragment.kt:1)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at com.adguard.android.ui.fragment.HomeFragment$k$a.invoke(HomeFragment.kt:2)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at com.adguard.android.ui.fragment.HomeFragment$k$a.invoke(HomeFragment.kt:1)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at j8.a$f.invoke(Animation.kt:2)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1467)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:211)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:300)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8410)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
02-27 23:12:34.484 25524 25524 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information
i'm sorry i can't provide any extra detailed info here as i can't even access the app.  

added by @Versty 
This crash also occurs using the Hebrew language

**Comment by Versty** [comment]
@robifr Thank you for reporting! 
The crash reproduces on our side as well. Will be fixed soon. 

Test device: Redmi note 11, Android 12, MIUI 13.0.4
