### ISSUE TITLE
AG protection disables by itself followed with 'out of memory' error 

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdguardForAndroid#5238]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

* Samung Galaxy Tab S2, Android version 7.0
* model = SM-T813

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Run AdGuard
2. After a while a protection gets disabled
3. 

### Expected Behavior

AdGuard runs smooth and stable

### Actual Behavior

Protection disabled from time to time

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Based on tickets 
862943 
and a few others

**Comment by acediat** [comment]
Your report has been thoroughly reviewed, and unfortunately, no solution has been found at this time. Therefore, we are closing the task until we receive new information on this matter.
