### ISSUE TITLE
Adguard protection is on after device start even with no Internet connection

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#524]
Needs to be tested.

User was able to reproduce it with Adguard in proxy mode on rooted device.

Original post: 
https://forum.adguard.com/index.php?threads/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0.8223/#post-80426

**Comment by ameshkov** [comment]
That's expected behavior

**Comment by TPS** [comment]
@ameshkov Should it be expected behavior _iff_ `pref.vpn.disable.pause` is :ballot_box_with_check:ed?

**Comment by ameshkov** [comment]
One more important note on this: user has "proxy" mode

**Comment by ameshkov** [comment]
> Should it be expected behavior iff pref.vpn.disable.pause is :ballot_box_with_check:ed?

Guess soo
