### ISSUE TITLE
Ads on Netflix

### ISSUE THREAD

**Issue by Barzaquaa** [AdguardTeam/AdguardForAndroid#5240]
### Please answer the following questions for yourself before submitting a question.

- [x] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Hello,

I wanted to know if it's possible to block ads on the Netflix app? With the subscription with ads, Adguard doesn't block any.

**Comment by maxikuzmin** [comment]
@Barzaquaa could you please clarify, are we talking about Android TV? The Android TV version does not have an HTTPS certificate, so unfortunately this is not possible

**Comment by Barzaquaa** [comment]
Hello,

I'm speaking about Android Mobile, it doesn't filter any ads for Netflix.

**Comment by maxikuzmin** [comment]
@Barzaquaa If you mean the Netflix application, HTTPS filtering is disabled by default. If HTTPS filtering is enabled, Netflix app will not work correctly and will display an error about VPN or Proxy. 
HTTPS filtering works for browsers and should successfully deal with ads, I recommend using the browser
