### ISSUE TITLE
Adguard is disappeared on the list of battery optimization after app restart

### ISSUE THREAD

**Issue by l0001-repo** [AdguardTeam/AdguardForAndroid#5242]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4 Nightly 34

### Environment

- OS version: HyperOS1.0.7.0
- Device: Xiaomi 13 China

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Language-specific

AdGuard Chinese filter

### Other

AdGuard DNS filter

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Steps to reproduce:
1. To make sure that adguard is on the list in battery optimization
2. Force close adguard
3. reopen adguard app

### Expected Behavior

adguard should still have on the list in battery optimization

### Actual Behavior

adguard is missing on the list in battery optimization

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@l0001-repo We are aware of this bug occurring on Xiaomi devices with MIUI and HyperOS.
Unfortunately, battery optimization is mostly controlled by the OS itself, and the best solution here is to wait for Xiaomi developers to fix this problem.
