### ISSUE TITLE
The Norstatsurveys.com website is blocked by AdGuard DNS and AdGuard DNS filter as well 

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#5244]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.83 Nightly 

### Environment

- OS version: Android 12
- Device: SM-N975F 

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Peter Lowe's Blocklist

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, Adblock Warning Removal List, I don't care about cookies, EasyList Cookie List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish Social Filters

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Remove tracking parameters from URLs, Ask websits not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1.browser open link with active adguard protection https://webs.norstatsurveys.com/a/3a1107180683d18c4790805d38324204
2. Seen error page 
3. Turn off / temporary stops protection - normally opening site 

### Expected Behavior

Opening site without any of problems and with active non paused  protection 

### Actual Behavior

Must paused adguard protection . Not working edition , changing filters or firewall. 

### Screenshots

<details><summary>Screenshots</summary>

![SmartSelect_20240229_183758_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/100161152/16326b7d-4c7a-46ca-91c1-0c5cd788acdb)
![SmartSelect_20240229_182518_Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/100161152/f162f7dc-523d-4ebd-8e40-9dcaba6ffca6)

</details>

### Additional Information

CNAME, norstat-webs.azurewebsites.net.
CNAME, waws-prod-db3-013.vip.azurewebsites.windows.net.
CNAME, waws-prod-db3-013.northeurope.cloudapp.azure.com.

**Comment by Versty** [comment]
@U0101100 Hi! 
The `norstatsurveys.com` website is blocked by selected DNS server (AdGuard DNS) as well as the AdGuard DNS filter due to privacy concerns. 

If you wish to keep this website unfiltered, switch to AdGuard DNS Non-filtering and add the `@@||norstatsurveys.com^` rule to DNS user rules (Protection tab -> DNS Protection -> DNS filters -> User rules)
