### ISSUE TITLE
Дополнительная информация

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5246]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Произвел ручное обновление фильтров и получил следующий результат

![Screenshot_20240301_233540_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/ff57653b-0419-4101-9ff4-d9f03737bedc)

Решил получить дополнительную информацию и получил следующий результат

![Screenshot_20240303_100437_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/1d2b1e46-20c0-4568-ab3b-dd0f84bc4937)

Вы уж добавьте возможность пользователю поглядеть какой фильтр не был обновлен или же уберите эту информацию, раз пользователь не имеет возможности поглядеть какой фильтр не был обновлен.

**Comment by ESurina** [comment]
Duplicate of #5220
