### ISSUE TITLE
Websites not opening on mobile carrier with HTTPS filtering enabled

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardForAndroid#5247]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

- OS version: Android 10
- Device: ASUS ZENFONE MAX PRO M1

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Which DNS server do you use?

Automatic DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:

dropmaza.com, aagmaal.com, spankbang.com and many more sites opening on my mobile network, as soon as I enable adguard then the same websites does not open and gives this error message This site can’t be reacheddropmaza.com unexpectedly closed the connection.
Try:

Checking the connection
ERR_CONNECTION_CLOSED

Disabling or changing DNS did not solve the problem, but when I delete the adguard HTTPS filter certificate and enable adguard then only sites open but with lot of ads and popup ads.

I confirm that there is problem with adguard HTTPS filter certificate for mobile network internet.

Now I have given the exact source of problem, I hope your team could fix this issue.

### Actual Behavior

Websites not opening on mobile carrier with HTTPS filtering enabled.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by rajatmathurs** [comment]
Here is the screenshot attached, where the site is not opening with adguard enabled

![Screenshot_20240305-141739](https://github.com/AdguardTeam/AdguardForAndroid/assets/19775409/5dff953f-3710-4ca1-93eb-ed0a46dd4a0e)

**Comment by Frankflash** [comment]
It does  it with dns over TLS  cloudflare  on Samsung browser  as well  a pain in the  but sometimes

**Comment by rajatmathurs** [comment]
This problem was not there now It is happening everyday for past 1 month, I have reported just couple of sites but as a matter of fact there are very long list of websites that is not not opening with adguard enabled. I had to disable adguard, then sites opens with lot of ads and pop up.

Request you to fix this problem, otherwise I can't bear the ads. I hope you and your team will fix this problem until then what will I do as there are sites which I visit daily.

**Comment by Frankflash** [comment]
I have had a lot of web sites  do this  like eg www.newstalkzb.co.nz  has closed  unexpectedly  closed  the connection  try checking  the connection   or failed to load  happens on a lot of sites  using  Samsung  browsers  dns over TLS cloudflare

**Comment by rajatmathurs** [comment]
> I have had a lot of web sites do this like eg [www.newstalkzb.co.nz](http://www.newstalkzb.co.nz) has closed unexpectedly closed the connection try checking the connection or failed to load happens on a lot of sites using Samsung browsers dns over TLS cloudflare

The same site is opening with adguard enabled, but my above listed sites not opening with adguard enabled. There is a problem which needs to be addressed and fixed

**Comment by Frankflash** [comment]
I also get this www.newstalkzb.co.nz  can't be  reached  DNS address  can't be  found  diagnosing the problem  as well

**Comment by Frankflash** [comment]
> > I have had a lot of web sites do this like eg [www.newstalkzb.co.nz](http://www.newstalkzb.co.nz) has closed unexpectedly closed the connection try checking the connection or failed to load happens on a lot of sites using Samsung browsers dns over TLS cloudflare
> 
> The same site is opening with adguard enabled, but my above listed sites not opening with adguard enabled. There is a problem which needs to be addressed and fixed

**Comment by rajatmathurs** [comment]
This issue is not yet addressed, hoping for a solution sooner then later.

**Comment by Frankflash** [comment]
This happens  when  using  wifi as well

**Comment by Frankflash** [comment]
Here  are screen shots

**Comment by rajatmathurs** [comment]
That is why I have mentioned Websites not opening on mobile carrier with adguard enabled, on wifi the sites are opening.

**Comment by Frankflash** [comment]
Well I  get it on mobile  and wifi connection  as well  sometimes

**Comment by rajatmathurs** [comment]
For you sometimes, for me the sites don't open at all on mobile network with adguard enabled. This is a big problem??

**Comment by rajatmathurs** [comment]
adguard team could you check this bug.and fix this issue.

**Comment by Frankflash** [comment]
I just get site can't be reached  and sometimes  get closed unexpectedly
at times  just a pain in the  but

**Comment by rajatmathurs** [comment]
> @Frankflash Thank you for reporting!
> 
> We would like to take a look at the logs from your device. Please follow the steps below:
> 
> 1. Enable debug logging:
>    _Settings -> General -> Advanced -> Logging level -> Debug_
> 2. Reproduce the issue (open a couple of listed websites in the browser), then remember the exact time when it happened
> 3. Collect logs:
>    _Settings -> General -> Advanced -> Export logs and system info_
> 4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
>    
>    * mention the `5247` number in the subject
>    * specify the exact time when the issue occurred

@Versty I have opened this issue so I should be sending the logs from my device for your checking .Let me know, should I send the logs or not

**Comment by rajatmathurs** [comment]
@Versty 

I have send the log file, hope you will look into the problem that I am facing and resolve this issue. Waiting for your reply

**Comment by Frankflash** [comment]
Logs also  sent

**Comment by Frankflash** [comment]
This is not new  thing

**Comment by rajatmathurs** [comment]
Logs are provided, hope that this issue is fixed soon.

**Comment by Frankflash** [comment]
This also  happened  In nightly versions as well

**Comment by Versty** [comment]
@Frankflash Thank you, the logs are received. We're investigating.

**Comment by rajatmathurs** [comment]
> @Frankflash Thank you, the logs are received. We're investigating.

@Versty I have send you the logs, are you investigating the issue that I am facing. Waiting for your reply

**Comment by rajatmathurs** [comment]
@Versty you have only mentioned @Frankflash name what about me, I have opened this issue. This is not done, let me know have you received my logs and are you investigating it.

**Comment by Versty** [comment]
@rajatmathurs We actually received both logs, yes. I apologize for not mentioning you in a previous comment.

**Comment by Versty** [comment]
@Frankflash Seems like the issue on your device is not related to this one. Please report it separately, we will attach the logs from your device to the new issue.

**Comment by Frankflash** [comment]
What should  I report  it as

**Comment by Frankflash** [comment]
Opened  new issues   5268  dns  tls issues

**Comment by Versty** [comment]
@rajatmathurs Please, update to the latest version (4.4.1) and check if this issue is gone.
