### ISSUE TITLE
Как удалить или отредактировать правило? 

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5249]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Вам не кажется странным то, что отдельно нельзя удалить правило, а можно только все или ни одного?

<a href="https://fastpic.org/view/123/2024/0307/4b29a03645500e246b3668764c53a395.jpg.html" target="_blank"><img src="https://i123.fastpic.org/thumb/2024/0307/95/4b29a03645500e246b3668764c53a395.jpeg" border="0"></a> <a href="https://fastpic.org/view/123/2024/0307/c92366a1b8f12fd0017de2eaad6baa87.jpg.html" target="_blank"><img src="https://i123.fastpic.org/thumb/2024/0307/87/c92366a1b8f12fd0017de2eaad6baa87.jpeg" border="0"></a> <a href="https://fastpic.org/view/123/2024/0307/c05311f336bd39e79ee16c3485d7313f.jpg.html" target="_blank"><img src="https://i123.fastpic.org/thumb/2024/0307/3f/c05311f336bd39e79ee16c3485d7313f.jpeg" border="0"></a> <a href="https://fastpic.org/view/123/2024/0307/61ff4ecdead89e55de8b45e50620bdef.jpg.html" target="_blank"><img src="https://i123.fastpic.org/thumb/2024/0307/ef/61ff4ecdead89e55de8b45e50620bdef.jpeg" border="0"></a>

Дайте пользователю возможность удалять не нужное по отдельности, а не только все сразу.

**Comment by Versty** [comment]
@Cursone Добрый день! 
Чтобы удалить правило смахните его справа налево. 
Для редактирования смахните нужное правило слева направо.
