### ISSUE TITLE
Change statistics detalization for low-res devices

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#525]
For low-res devices we can strip the numbers after the floating point.

![e6c38023d14c](https://cloud.githubusercontent.com/assets/5947035/15010780/9a873fea-11f6-11e6-83b6-bebe57e6d4c2.png)

**Comment by ameshkov** [comment]
![screenshot_2016-05-04-22-43-18](https://cloud.githubusercontent.com/assets/5947035/15031601/a89ba99c-1262-11e6-8d08-67233f11f456.png)

**Comment by Revertron** [comment]
Done, I suppose.

**Comment by ameshkov** [comment]
Still there:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=49808965

**Comment by Revertron** [comment]
I've done some tuning in emulator, I think I've managed to determine needed modifiers and fixed it.
