### ISSUE TITLE
Samsung Internet Browser Beta not able to sync when AdGuard is active

### ISSUE THREAD

**Issue by SgtChrischi** [AdguardTeam/AdguardForAndroid#5251]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

- OS version: Android 14, OneUI 6.1
- Device: Samsung Galaxy S24 Ultra

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Enable AdGuard and enable HTTPS filtering
2. Open Samsung Internet Beta Browser
3. Try to sync browser data with cloud

### Expected Behavior

The browser would sync its data to the cloud.

### Actual Behavior

Instead of syncing it just gives an "sync failed" error. Even if I disable any protections inside Adguard. Only way to fix this is to disable HTTPS filtering completely or at least disable it for the Samsung Browser. After that it starts syncing again without error.

### Screenshots

<details><summary>Screenshot 1</summary>

![photo1709833797](https://github.com/AdguardTeam/AdguardForAndroid/assets/7974308/4baa6478-9986-47e6-a5e8-36853cafcdff)

</details>

**Comment by Versty** [comment]
@SgtChrischi Hi! 
Would the issue persist if you disable the `Route traffic through AdGuard` option for Samsung Cloud application in App management tab?

**Comment by SgtChrischi** [comment]
Hello @Versty 

Yes, it persists if I disable this.

I also asked about this issue on a German forum and some ppl confirmed that they have the same issue, also only on "Samsung Internet Beta". The default "Samsung Internet" works just fine.

**Comment by Versty** [comment]
@SgtChrischi We have tried to reproduce this issue on your side, but to no avail. Therefore, we would like to take a look at the logs from your device. Prior to reproduction, please close all non-relevant to this issue applications and follow the steps below.

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5251` number in the subject
      - specify the exact time when the issue occurred

**Comment by SgtChrischi** [comment]
Hello @Versty, thanks for your reply! I've just updated to the newest AdGuard for Android 4.4 Nightly 38 and the issue is gone now...

**Comment by Versty** [comment]
@SgtChrischi Good news! Let me know if the issue returns and reopen this issue.
