### ISSUE TITLE
Partially hide the license key 

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5252]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

В **AdGuard 3.6.11** ключ был скрыт звездочками от посторонних глаз, но теперь же он открыт.

![Screenshot_20240307_222047_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/072f4ba9-1ff1-4131-81df-d9353cfdc9bb)

Может скроете его от посторонних глаз для безопасности?

**Comment by Versty** [comment]
@Cursone Да, совсем скоро ключ снова будет частично скрыт. 

Дубликат https://github.com/AdguardTeam/AdguardForAndroid/issues/4496
