### ISSUE TITLE
"data saved" and "total blocked" in lowercase

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5253]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

По идеи эти слова должны быть с заглавной буквы

![Screenshot_20240307_222251_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/373dab2f-0405-4f9a-be6f-8ad476d8324a)

Скажите, что придираюсь но все же

**Comment by Versty** [comment]
@Cursone Слова "сэкономлено" и "заблокировано" в данном случае корректно написаны с маленькой буквы в соответствии с нашей задумкой.
