### ISSUE TITLE
WikiMedia icon

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5254]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

В разделе

![Screenshot_20240307_221850_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/65adc603-41ee-48cb-a5b5-7345f47ad990)

Отсутствует иконка, а у других присутствует

![Screenshot_20240307_221911_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/8ec97f90-48b0-4832-9a3e-4ffb0484218d)

Мелочь, но все же

**Comment by Versty** [comment]
@Cursone У WikiMedia иконка черного цвета. Если переключиться на светлую тему, вы заметите, что иконка отображается.
