### ISSUE TITLE
Текст "некорректная блокировка" 

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5255]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Раздел называется о некорректной блокировке, а под названием написано о пропущенной рекламе. 

![Screenshot_20240307_222014_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/3790c3ee-60d4-4f8f-9753-fd6d4d242689)

Мелочь, но измените название с **некорректная блокировка** на **пропущенную рекламу**

**Comment by Versty** [comment]
@Cursone "Некорректная блокировка (рекламы)" включает в себя пропущенную рекламу, так что перевод выглядит верным.
