### ISSUE TITLE
Android installation package signature exception

### ISSUE THREAD

**Issue by guxiaofeng2333** [AdguardTeam/AdguardForAndroid#5256]
- OS version: Android 12 (ColorOS 12.1)
- Device: OPPO PHA120(OPPO A96)
- As shown in the first image, on the website https://adguard.com/zh_cn/adguard-android/overview.html After downloading Adguard 4.3.1, when attempting to install, the application installation program prompts "abnormal installation package".
![Screenshot_2024-03-09-10-47-14-01_d0f6572af797fe1d932039816ed9c9bc](https://github.com/AdguardTeam/AdguardForAndroid/assets/162771658/c4041793-de7d-4bac-b607-b51f6fa62e25)

- As shown in the second image, try using the "MT Manager" to check the status of the installation package. The installation package signature status prompts "V2 signature scheme verification failed" (as shown in red font)

![Screenshot_2024-03-09-10-46-56-38_9e8df3d0c7c1f50248b6ee043a653d26~2](https://github.com/AdguardTeam/AdguardForAndroid/assets/162771658/54bd3bb9-9879-46bb-8298-a9ce737dc384)
- Although you can use the "APK Signature" feature of the "MT Manager" on your own to solve this problem, it should also be fixed in a timely manner
- By the way, after installing the adguard, the phone manager provided by the OPPO manufacturer indicated that the adguard was a "medium risk application" (confirmed to be installed from the official website), but the specific reason is unclear.
- The virus risk information provided by the mobile phone manager is as follows:
- Risk level: Medium
- risk name: Android.Virus.Gray.Nebula.A
- Description: Suspected existence of risk code, prone to privacy leakage

**Comment by Versty** [comment]
@guxiaofeng2333 Thank you for reporting! 
We are aware of this issue, the application signature will be improved in the future versions. 

Duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/5201
