### ISSUE TITLE
top eleven ads are blocked even if app is whitelisted

### ISSUE THREAD

**Issue by tuxnowar** [AdguardTeam/AdguardForAndroid#5257]
![Screenshot_20240309-152252](https://github.com/AdguardTeam/AdguardForAndroid/assets/99463588/cb3596e2-3f0b-4b11-921d-56abd4016781)
![Screenshot_20240309-152416](https://github.com/AdguardTeam/AdguardForAndroid/assets/99463588/3cc1e8b3-45cf-4a55-b4d5-29848c7eb867)
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

- OS version: Android 14
- Device: Xiaomi Redmi note 9 pro (joyeuse)

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Automatic proxy

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Social

AdGuard Social Media filter

### Language-specific

EasyList Italy

### Which DNS server do you use?

Google DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. (adguard disabled) open top eleven. promo video (watch this video and gain coins) are working
2. (adguard enabled) open top eleven. promo video (watch this video and gain coins) are not working
3. (adguard enabled, app whitelisted) open top eleven. promo video (watch this video and gain coins) are still not working
4. after every step i force close the app and clear cache, but the app works only if i disable adguard

### Actual Behavior

see issue detail

### Screenshots

<details><summary>Screenshot 1 (video not working)</summary>

</details>

<details><summary>Screenshot 2 (video working)</summary>

</details>

**Comment by maxikuzmin** [comment]
@tuxnowar it's not clear which website you're referring to. Could you please clarify the website?

**Comment by tuxnowar** [comment]
inside the app "top eleven" there are some video ads which give you
different in-game bonus. the app can't show them (the button is grayed
out). so it's not a site, but some video ads within an app

Il lun 11 mar 2024, 19:49 maximkuzmin ***@***.***> ha scritto:

**Comment by maxikuzmin** [comment]
@tuxnowar Top Eleven Football Manager?

**Comment by maxikuzmin** [comment]
@tuxnowar could you please clarify how you exclude the app from filtering?
I checked your case by disabling filtering for Top Eleven Football Manager app, and the videos are showing stable.
You need to go to:
App management -> Top Eleven app -> disable "Route traffic through AdGuard"

Please let me know the result

**Comment by tuxnowar** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/assets/99463588/cd6b19b1-12a7-463d-85da-391321430aeb

i made a video screen to show you. this is the case "app filtering, top eleven whitelisted" videos not showing

**Comment by maxikuzmin** [comment]
@tuxnowar ads are shown through Google. 
You can exclude the Google Services Framework app from filtering, this should help 
You need to go to:
App management -> Google Services Framework -> disable "Route traffic through AdGuard"

**Comment by tuxnowar** [comment]
thank you, but i just tried, and it's not working

**Comment by maxikuzmin** [comment]
@tuxnowar could you please take a video of the screen showing the filtering disabled for Google Services Framework and a repeat of the problem? Maybe something is still misconfigured though, as it solved the problem for me
You can send the video to email devteam@adguard.com

**Comment by maxikuzmin** [comment]
@tuxnowar any news?

**Comment by tuxnowar** [comment]
just sent the video, sorry for the delay :)
Unfortunately in the video you can see that the proposed solution does not work

**Comment by tuxnowar** [comment]
i sent the video to devteam@adguard.com some days ago, did it arrive?

**Comment by maxikuzmin** [comment]
@tuxnowar yes, thank you, I noticed that after disabling filtering for Google Services Framework you opened the Top eleven game from the tray. 
This is not quite right as the game may be cached and this will affect the application of the new AdGuard rules. 
Please first close the Top eleven game completely -> disable filtering for Google Services Framework -> start the Top eleven game -> check the video playback

**Comment by maxikuzmin** [comment]
@tuxnowar any news?

**Comment by tuxnowar** [comment]
unfortunately the proposed solution is not working, the only way to make videos working is to pause the whole app

**Comment by maxikuzmin** [comment]
@tuxnowar is filtering for top eleven disabled when doing this? 
Could you export your settings and email them to devteam@adguard.com? I'll try to reproduce this with your settings

**Comment by maxikuzmin** [comment]
@tuxnowar any news?

**Comment by maxikuzmin** [comment]
@tuxnowar for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
