### ISSUE TITLE
Adguard disables on Android 5.x when 'Notification icon' set to 'none'.

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#526]
1) Set 'notification icon' setting to 'none'
2) Swipe Adguard from 'recent apps'
3) Adguard is disabled

Happens on Android 4.x and 5.x, see original thread:
https://forum.adguard.com/index.php?threads/%D0%9E%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D0%B5%D1%82%D1%81%D1%8F-adguard-2-5-196.10065/

**Comment by ameshkov** [comment]
@Revertron I've recently turned off our dummy intent for Android L and newer.

I guess we should also check if notification icon is enabled or not.

**Comment by Revertron** [comment]
But on my device we continue working flawlessly when I swipe Adguard from recents.

**Comment by ameshkov** [comment]
We should check it on some test device with Android 5.X.

**Comment by Revertron** [comment]
We added warning dialog in #497, users will be aware of possible problems.
