### ISSUE TITLE
Same reason as #386

### ISSUE THREAD

**Issue by JBL595** [AdguardTeam/AdguardForAndroid#5261]
Same reason as #386 

@mklopp @shiftykey 
What are your phone model (and Android version)? 

Does it work if you switch to `disable mode` in the settings?

UAD should obviously not crash when adb crashes. I'll try to reproduce the crash by triggering an ADB crash

_Originally posted by @0x192 in https://github.com/0x192/universal-android-debloater/issues/377#issuecomment-1254348848_

**Comment by maxikuzmin** [comment]
@JBL595 could you please elaborate on the details of what exactly is the problem with AdGuard?
I'm not quite sure what the problem is and what the steps are

**Comment by maxikuzmin** [comment]
@JBL595 any news?

**Comment by maxikuzmin** [comment]
@JBL595  for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
