### ISSUE TITLE
Gmail images not displaying

### ISSUE THREAD

**Issue by arebelspy** [AdguardTeam/AdguardForAndroid#5267]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard v4.4 Nightly 37

### Environment

- OS version: Android OxygenOS 14.0
- Device: OnePlus 9

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Open Gmail app
2. Open email with image attachments
3. Images do not display inline (or at all). If attachment is clicked, a white box is shown instead of the attachment.

Other attachments (such as PDFs) work fine.

Logs don't show anything blocked (but when gmail app is not routed through AdGuard, it does show other traffic).

### Expected Behavior

Images should show in emails

### Actual Behavior

Images do not show

### Screenshots

<details><summary>See this discussion for multiple screenshots: https://github.com/AdguardTeam/AdguardFilters/issues/175363</summary>

</details>

### Additional Information

This was initally sent to the filter team, who diagnosed and couldn't solve.

Lots more information, and multiple screenshots, in this github report: https://github.com/AdguardTeam/AdguardFilters/issues/175363

**Comment by arebelspy** [comment]
It actually may be all attachments. Just tried to click a PDF attachment and it stuck on trying to download. Turned off AdGuard, worked just fine.

**Comment by arebelspy** [comment]
This appears to be working now for me. I do not know why/how.

**Comment by ESurina** [comment]
Please reopen the task if the problem repeats again.
