### ISSUE TITLE
DNS  TLS  ISSUES

### ISSUE THREAD

**Issue by Frankflash** [AdguardTeam/AdguardForAndroid#5268]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

433.199

### Environment

- OS version:
- Device:
Android  13. Galaxy s20fe 

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

DNS-over-TLS

### Issue Details

Steps to reproduce:
1.
2.
3.
You  have logs opening website 

### Actual Behavior

Dns errors TLS  errors 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by PavelParkhomenko** [comment]
Hello there!

Could you please provide a more detailed description of the issue? Are we correct in understanding that the problem occurs consistently when visiting the websites you mentioned (newstalkzb.co.nz, nzherald.co.nz, and apkmirror.com)?

Does the issue also occur when using other browsers on your smartphone?

Is it possible to reproduce the problem only while connected to a specific network, or does it occur in other networks as well?

Additionally, have you tried choosing DNS-over-HTTPS protocol or selecting another DNS server to see if it resolves the issue?

**Comment by PavelParkhomenko** [comment]
Based on the screenshot provided earlier, it seems that you are also using Avast antivirus on your smartphone. If this is indeed the case, could you please attempt to disable it temporarily and check if the issue persists?

**Comment by Frankflash** [comment]
It could be  to with Samsung browser  itself    doesn't  do it with  Chrome

**Comment by Frankflash** [comment]
It doesn't  do it  when  avast  disabled  but when  enabled  and reboot  phone  comes  back  again

**Comment by PavelParkhomenko** [comment]
> It doesn't do it when avast disabled but when enabled and reboot phone comes back again

This information suggests that the issue arises due to a conflict between our app and the Avast app. Such conflicts are relatively common and can occur on devices running other operating systems as well. Unfortunately, in this case, we can only recommend disabling either Avast or AdGuard protection to circumvent the issue described.
