### ISSUE TITLE
Do not start VPN when another VPN is in use

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#527]
It seems that Adguard starts it's VPN even when another VPN is in use.

https://forum.adguard.com/index.php?threads/disable-aggressive-vpn-policy.9701

**Comment by TPS** [comment]
Wouldn't it better to ask to convert to #51, whenever that lands?

**Comment by ameshkov** [comment]
That's just a bit different issue.

You see, AG is too "aggressive" now, starts its VPN even when some other vpn app is in use, hence stopping that vpn.

**Comment by TPS** [comment]
This is true, but user may not be aware that AG will have capability to run _both_ simultaneously at that point (milestone v2.6), right?

**Comment by ameshkov** [comment]
> to run both simultaneously at that point 

This is possible only with root and in proxy+automatic mode.

You just can't have two different VPNs on Android and we can't help it. #51 issue won't change it. However, at least user will be able to use an outbound proxy. For instance, PIA provides proxy along with a VPN.

**Comment by Revertron** [comment]
But how can we start our VPN without permission? When user gives one app permission to start VPN the VPN permission is revoked from other VPN apps.

**Comment by ameshkov** [comment]
@Revertron both apps already has permission.

**Comment by Revertron** [comment]
Fixed!
