### ISSUE TITLE
DNS Server for LAN devices

### ISSUE THREAD

**Issue by MSZ-MGS** [AdguardTeam/AdguardForAndroid#5272]
### Issue Details

Hi there, I want to have Adguard to have a feature to allow it to serve all devices in the LAN as a DNS Server.

I know that port 53 requires a root privilege, but it will be very awesome thing to have.

Best regards...

### Proposed solution

Adguard to act as a DNS Server for local devices.

**Comment by ESurina** [comment]
We cannot add this feature for technical reasons. You can use our other products that can serve all devices in the LAN as a DNS Server. These are AdGuard Home and Private AdGuard DNS.
