### ISSUE TITLE
Snapchat Ads

### ISSUE THREAD

**Issue by Paulchemouni** [AdguardTeam/AdguardForAndroid#5273]
### Issue Details

In the Android Snapchat app, ads can still appear on stories, even with https filtering and all the others filtering settings on.
![Screenshot_20240330-212420_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/87277848/1098b5fc-9a25-48d2-ad03-94c8e34f77f3)

### Proposed solution

Maybe the Ad server of Snapchat should be added to a filtering list?

**Comment by ESurina** [comment]
The problem is caused by the security method of the application. We are currently collecting the problematic applications to find a proper solution to handle traffic filtering in such apps.
Detailed explanation is available in #4827 

Snapchat app will be added to the linked table.
