### ISSUE TITLE
Fritz Fon App is blocked, but the App is excluded?

### ISSUE THREAD

**Issue by rampolino** [AdguardTeam/AdguardForAndroid#5278]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

- OS version:14
- Device:Pixel 8 Pro

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

Fritz Fon function normally...Fritz Fon do not function in local Wlan with VPN

### Actual Behavior

Under some circumstances Fritz Fon do not reach the router,

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

If I turn off Adguard and turn on, Fritz Fon ist function normally. If I turn on the Pixel or over night Fritz Fon do not function. I have excluded the App and Telefon Services etc.

**Comment by rampolino** [comment]
To clarify this. Fritz Fon app does not connect to the router in the local WiFi if a VPN is detected. Although the app is excluded from Adguard, it is blocked under certain circumstances. After a certain time (night) when the phone restarts. Then Fritz Fon app only works if Adguard is turned off and on again.

**Comment by PavelParkhomenko** [comment]
Hello! To troubleshoot the issue, we recommend excluding the app package name `de.avm.android.fritzapp` from the filtering. You can do this by navigating to 'Settings → General → Advanced → Low-level settings → Excluded apps'. Please give this a try and see if it resolves the issue.

**Comment by PavelParkhomenko** [comment]
@rampolino 
Just following up on our previous message regarding the steps we recommended. Have you had a chance to look into them? Let us know if you need any further assistance or clarification.

**Comment by rampolino** [comment]
Yes, it solved partvise. The call is arrived but in the Fon App the 
connection is not established. But mostly all function is normal. Thank 
you for your help!


------ Originalnachricht ------
Von "Pavel" ***@***.***>
An "AdguardTeam/AdguardForAndroid" 
***@***.***>
Cc "rampolino" ***@***.***>; "Mention" 
***@***.***>
Datum 02.05.2024 10:26:48
Betreff Re: [AdguardTeam/AdguardForAndroid] Fritz Fon App is blocked, 
but the App is excluded? (Issue #5278)

**Comment by PavelParkhomenko** [comment]
Thank you for your feedback!  If you require further assistance or have any new questions, don't hesitate to contact our support team directly through the app or reach out to us here.
