### ISSUE TITLE
MeetMe compatibility issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#528]
https://play.google.com/store/apps/details?id=com.myyearbook.m

With HTTPS filtering enabled, the following message is shown:

>Network Error!
>Could not connect to the data nertwork!
>You may need to try again later.

Original thread:
https://forum.adguard.com/index.php?threads/meetme-chat.9878/#post-80505

**Comment by Revertron** [comment]
Adding api.meetme.com to https exclusions.

**Comment by vbagirov** [comment]
This didn't help too much - no more "Network Error!" but when one tries to log in there is a neverending loop

**Comment by gshumihin** [comment]
Works fine for me.

**Comment by gshumihin** [comment]
Works fine for user too.
