### ISSUE TITLE
add privilege "Device admin apps" for adguard

### ISSUE THREAD

**Issue by Benson2333** [AdguardTeam/AdguardForAndroid#5285]
### Issue Details

Hopefully I'd like to add a feature to Adguard for android that allows users to give the highest privilege - "Device admin apps".
After granting this permission, you can avoid automatic cleaning of the system to the greatest extent, such as MIUI for China, EMUI for China and other customized Android systems used in China, their built-in "mobile manager" often mistakenly kills the background of third-party security software, including Adguard, Adguard content blocker, Firefox.
Personally, I think it's an offensive way for them to protect the system's ads, but there is no way for the average user to block it.
As consumers, we should have the right to ask the system to block ads, but due to the chaos of the Chinese market, we can only hope that Adguard will allow users to use an ad-free system.
Thank you!

### Proposed solution

allows users to give the highest privilege - "Device admin apps"

### Alternative solution

allows users to give the highest privilege - "Device admin apps"

**Comment by PavelParkhomenko** [comment]
Hello there! Granting such permission is unnecessary to prevent AdGuard from being closed by the System. We recommend following the instructions outlined in our Knowledge Base for your smartphone: [https://adguard.com/kb/adguard-for-android/solving-problems/background-work/](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/) 

If the issue persists on your device, please don't hesitate to reach out to our support team through the app or open a new issue on GitHub so we can thoroughly analyze the situation.

**Comment by Benson2333** [comment]
你好，你提供的解决方案仅仅对国内厂商生产的非国行安卓手机有效。
也就是说，对于在中国大陆销售国行安卓手机是无效的，这是由系统决定的。
以MIUI为例，它分为Global和China两种版本的系统，当你实际使用时，你会发现，MIUI Global更符合谷歌关于手机权限的设定，而MIUI China在权限管理上的定制化，使得用户不可能与系统争夺权限，很多影响厂商内置广告的行为都会被阻止。
著名杀毒软件Dr.Web for android，如果不开启 "Device admin apps”，它可能在下次重启手机时无缘无故提示用户“某项权限缺失，致某项安全进程无法运行”；这放在Adguard上也是成立的，比如我在Redmi note 8上安装的Adguard，曾多次在更新程序后被提示“自启动”缺失；多次由于长时间未关机，导致Adguard后台被清理；系统内置APP广告屏蔽失效。
如果中国大陆使用的是谷歌原生安卓、谷歌商店，这些问题可能授予常规权限就能解决；但，中国大陆用户使用的是深度定制的系统，这种能产生流氓软件360的软件生态，你能指望厂商遵守规矩？
从某种意义上而言，Adguard如果能准确拦截中国大陆的流氓广告，在世界范围内还有什么广告无法拦截？
希望考虑我的意见，面对流氓只有更流氓，只有提高权限，才能拦截系统级广告。

**Comment by PavelParkhomenko** [comment]
To better assist you, we'll require additional details such as app and system logs to thoroughly investigate the issue. Once we have this information, we can proceed to explore potential solutions. Please don't hesitate to contact our support team via the app on your Redmi Note 8 or alternatively, you can open a new issue on GitHub.

**Comment by TPS** [comment]
Now #5320.
