### ISSUE TITLE
Option to select the default state of "Route app through proxy" toggle for all apps

### ISSUE THREAD

**Issue by Debik5** [AdguardTeam/AdguardForAndroid#5288]
### Issue Details

Сейчас прокси автоматически включается для каждого нового приложения, которое устанавливается на устройство 
Это ставит под угрозу прокси сервер, ведь нежелательный трафик из России может помешать получать доступ к зарубежному контенту в дальнейшем 

### Proposed solution

Пожалуйста, добавьте опцию выбора режимов работы прокси и его поведение для приложений по умолчанию, как это обычно реализовано в vpn сервисах
Например, чтобы можно было пропускать через прокси все приложения кроме выбранных, либо не пропускать через прокси никакие приложения, кроме выбранных вручную

В качестве примера приведу скриншот, как эта функция реализована в V2rayNG
![Screenshot_20240417-191232_v2rayNG](https://github.com/AdguardTeam/AdguardForAndroid/assets/79472703/e38b7f68-4b52-427f-8c10-218e256c6486)

**Comment by Versty** [comment]
@Debik5 Добрый день! 
На текущий момент в AdGuard for Android реализовано управление проксированием приложений в разделе: _Настройки -> Фильтрация -> Сеть -> Прокси -> Приложения, работающие через прокси_ 

Для изменения настроек проксирования сразу для всех приложений, используйте опции в контекстном меню экрана "Приложения, работающие через прокси".

**Comment by Versty** [comment]
@Debik5 Изменение состояния настройки "Направлять трафик через прокси" для всех приложений по умолчанию может негативно отразиться на безопасности пользовательских данных, поэтому мы не планируем добавлять подобную опцию в AdGuard for Android.

**Comment by Debik5** [comment]
> @Debik5 Изменение состояния настройки "Направлять трафик через прокси" для всех приложений по умолчанию может негативно отразиться на безопасности пользовательских данных, поэтому мы не планируем добавлять подобную опцию в AdGuard for Android.

А почему пользователь не может сам решить как это отразится на его безопасности? Можно добавить окно с предупреждением, но лишать этого функционала вовсе как то неправильно.

**Comment by Debik5** [comment]
@Versty В свете последних событий в России и новостей по поводу новых методов выявления впн трафика и тарификации иностранного трафика, я бы хотел попросить ещё раз рассмотреть мое предложение по введению возможности по умолчанию отключить прокси для новых приложений. В текущем виде это может поставить под угрозу клиентские впн сервисы и прокси, ведь если забыть их отключить, то данные утекут регулятору и адрес прокси может быть заблокирован.
Также это может повлечь нежелательные расходы трафика и как следствие повысить расходы на мобильную связь.

Мне очень нравится Adguard на андроид, я использую его много лет, но сейчас его использование становится все более неудобным и компромиссным. Введение этой функции сильно помогло бы мне не волноваться о случайной утечке впн.
