### ISSUE TITLE
Farpost Кино fails to connect

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#529]
https://play.google.com/store/apps/details?id=com.farpost.android.kinovlru 
При запуске приложения появляется сообщение "Не удалось загрузить данные".

Отключение фильтров не решает проблему

логи тут: XBR-911-85341

**Comment by ameshkov** [comment]
HTTPS фильтрация?

**Comment by Revertron** [comment]
Приложение лезет на урл такой:
https://api-kino.vl.ru/api/mobile/v2.2/get.json?method=CityList&
И при этом сервер хочет клиентский сертификат. Иначе - 400 No required certificate was sent.

**Comment by Revertron** [comment]
Добавление api-kino.vl.ru в исключение https решает проблему. Сделал.
