### ISSUE TITLE
AdGuard Nightly doesn't honour case-sensitive device names (QUIC)

### ISSUE THREAD

**Issue by Fishawyyy** [AdguardTeam/AdguardForAndroid#5291]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.159 (4.4 Nightly 42)

### Environment

- OS version: Android 14 Stock
- Device: Pixel 7 Pro

### HTTPS filtering

- [ ] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Automatic proxy

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### Security

Online Malicious URL Blocklist

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### Custom DNS

NextDNS over QUIC

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Disable WebRTC, Protect against DPI

### Issue Details

Steps to reproduce:
1. AdGuard Nightly displays the device name in all lower-case when using DoQ only.
2. If I'm using quic://MyPixel-abc123.dns.nextdns.io for example, the device name in the logs shows as "mypixel" not "MyPixel".
3. Other protocols (DoH, DoT, and DoH3) display the name properly (MyPixel).
4. I downloaded the stable app (v4.3.199) and it displays the device name correctly using QUIC protocol. The issue is only with the nightly releases.
5. This was noticed few weeks ago, and I had a couple of nightly updates.

### Expected Behavior

Device name to show as "MyPixel".

### Actual Behavior

Device name shows as "mypixel".

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_20240419-142515](https://github.com/AdguardTeam/AdguardForAndroid/assets/125537310/cfece38c-e9a0-47d5-91f4-fba7ca138177)
![Screenshot_20240419-102354~2](https://github.com/AdguardTeam/AdguardForAndroid/assets/125537310/e5697312-98a1-4c92-a36d-102d657ec827)
![Screenshot_20240419-102614~2](https://github.com/AdguardTeam/AdguardForAndroid/assets/125537310/cf4c0eb3-8952-4f01-bf3e-7720df09a19c)

</details>

### Additional Information

3 screenshots attached:

1. Using DoQ on nightly, device name is "adguard".
2. Using DoH3 on nightly, device name is "AdGuard" as I typed it.
3. Using DoQ on stable, device name is "AdGuard" as I typed it.

**Comment by zzebrum** [comment]
@Fishawyyy thanks for report
Will be OK once DnsLibsv2.5.1 is released. [Duplicate](https://github.com/AdguardTeam/DnsLibs/issues/219)
