### ISSUE TITLE
WVGA800 800x480 - percents are trimmed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#53]
![6791946](https://cloud.githubusercontent.com/assets/5947035/9965391/d2466e62-5dea-11e5-912e-23879fe35d37.png)

Maybe we shouldn't show some of the elements on small screens?

**Comment by Revertron** [comment]
Resolved.

**Comment by ameshkov** [comment]
Still no good

![screenshot_2015-10-01-23-53-49](https://cloud.githubusercontent.com/assets/5947035/10241590/0249df6e-68f3-11e5-8e18-e651a2fe4753.png)

**Comment by Revertron** [comment]
Tuned a bit smallest screen size that will be hiding percents.
