### ISSUE TITLE
com.here.app.maps doesn't work if HTTPs filtering is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#530]
Android: App "HERE Maps" doesn't work correctly with HTTPS filtering 
I'm using the current final 2.5.196 for Android.

After adding the package name (com.here.app.maps) to the HTTPS whitelist, the app works again as intended. Maybe you could add that app to your default whitelist in one of the next versions (betas)?

**Comment by Revertron** [comment]
Need more info. It seems I've tried everything, and only loading of map was delayed for about 30 seconds, but eventually loaded and the app is working flawlessly.

**Comment by engelhro** [comment]
As I was the user originally sending in the problem report: some information got lost on the way from the actual ticket to the issue above.

I'll cite the relevant part:

>  when accessing the voice options for the navigation an „download of initial data failed“ message appears, and login into ones account (for synchronization of favourites etc.) is also not possible.

So the app works regarding map loading and navigation on the map, but other features like the voice downloads or (more important) the login (to sync favorites etc.) do not work while HTTPS filtering is activated.

Thanks for having another look!

**Comment by ameshkov** [comment]
@engelhro that's for the details, we'll take another look

**Comment by Revertron** [comment]
Okay, adding 'api.here.com' & 'data.here.com' to https exceptions will fix it. We will add it to the list.
