### ISSUE TITLE
Firewall blocking all mobile traffic upon new install 

### ISSUE THREAD

**Issue by morpheus092511** [AdguardTeam/AdguardForAndroid#5302]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Upon installing firewall when first activated was blocking all mobile browser traffic through Chrome. Only way to get it working was to set up a custom rule for Chrome allowing mobile data. A less experienced user wouldn't have known how to do this and would have just thought the program wasn't working. Possibly needs a tutorial or something showing that should happen or if this isn't supposed to happen then this should have been a bug report

**Comment by maxikuzmin** [comment]
@morpheus092511 did I understand you correctly that when you first enabled the Firewall feature, it blocked all browser traffic through Chrome (on the mobile network)?
Even though you didn't disable "Use mobile data" in Firewall?

**Comment by maxikuzmin** [comment]
@morpheus092511 I don't quite get it. Did you manually enable mobile data? 
Was mobile data turned off because Firewall was turned on? Is mobile data in Firewall or in android system? 
Also, what version of AdGuard are you using?

**Comment by maxikuzmin** [comment]
@morpheus092511 any news?
