### ISSUE TITLE
TV: Add an easier way of adding a custom DNS Server

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#5303]
### Issue Details

It’s quite laborious adding a custom DNS server to the AdGuard TV app having to individually type each character with the TV remote.

### Proposed solution

Unknown.

**Comment by maxikuzmin** [comment]
@jslawler-gh yes, but adding a DNS server requires entering the server name as well as the server address. 
Just like the mobile version, PC version and so on. 
What are you suggesting?

**Comment by maxikuzmin** [comment]
@jslawler-gh currently all products have a pre-configured list of AdGuard and third-party DNS servers. 
Also for other products there is export/import of settings, where you can "transfer" your settings, including DNS, but for the TV version this function is not implemented yet.

Anyway, if we are talking about settings in AdGuard for IOS and AdGuard for Android TV, for example, export/import is not yet possible. And it's impossible to link settings to an account for all operating systems "via cloud".

Have you considered synchronizing devices using Google, and putting the link of the DNS server address on the clipboard first on your device, and then pasting the link to the TV? Seems to me that might be a solution to your problem
