### ISSUE TITLE
TV: Add a way of exiting out of the custom DNS server entry box

### ISSUE THREAD

**Issue by jslawler-gh** [AdguardTeam/AdguardForAndroid#5304]
### Issue Details

When adding a custom DNS server, the window that pops up on an Amazon Fire Stick is unable to be exited without entering an address and completing the operation.

### Proposed solution

Add something like an X, to exit out of the custom DNS server entry.

**Comment by maxikuzmin** [comment]
@jslawler-gh as far as I know, the Amazon Fire Stick remote has a "back" button.
 The back button is to the left of the home button. 
Have you tried pressing this button? You can use the back button to exit from any setting

**Comment by maxikuzmin** [comment]
@jslawler-gh is the back button not working right now either?
