### ISSUE TITLE
TV: App icon doesn’t fill the entire icon box on Amazon Fire Stick

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#5305]
### Issue Details

The app icon for AdGuard doesn’t fit the whole app icon box on the Amazon fire stick.

![IMG_0651](https://github.com/AdguardTeam/AdguardForAndroid/assets/149243371/ad7cbe44-5ab2-45ed-a171-941fca29e39f)

### Proposed solution

Fill the whole app icon box.

**Comment by maxikuzmin** [comment]
@jslawler-gh could you please specify which version of the app you are using? 
Also please specify, are you using the TV version of the app? That would also make a difference

**Comment by emeritaacuity0u** [comment]
@maxikuzmin @Versty I am also seeing this with version 4.4.1, could this please be reopened.

**Comment by emeritaacuity0u** [comment]
@maxikuzmin @Versty Please reopen, this is still an issue.
