### ISSUE TITLE
Update Progress Bar has wrong colors

### ISSUE THREAD

**Issue by JustAAdGuardFan** [AdguardTeam/AdguardForAndroid#5308]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4 Nightly 45

### Environment

- OS version: Android 13
- Device: Galaxy A71

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Go to update menu
2. If there is a update click the update button
3. Update Progress Bar Inverted

### Expected Behavior

Update Progress Bar not inverted

### Actual Behavior

Update Progress Bar Inverted

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_20240503_115656_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/162761198/ecc956ae-1d52-4081-af03-c240dee655ab)

</details>

**Comment by ESurina** [comment]
Please describe the problem in more detail. Do the colors of progress bar seem wrong to you or is the loading bar moving from right to left?

**Comment by JustAAdGuardFan** [comment]
The colors of the progress bar seem wrong to me.

**Comment by ESurina** [comment]
We will fix it in the next versions!

**Comment by JustAAdGuardFan** [comment]
Awesome, thank you so much!
