### ISSUE TITLE
Ненужное сокращение

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5310]
### Issue Details

Место для отображения заблокированного предостаточно

![Screenshot_20240504_141652_com adguard android](https://github.com/AdguardTeam/AdguardForAndroid/assets/155391717/89d96c37-b2a0-4b44-bcc0-da9257b8cf1b)

### Proposed solution

Смысла укорачивать количество заблокированного нет совсем. Можно полноценную информацию давать.

**Comment by ESurina** [comment]
Доброго времени суток! При создании дизайна мы ориентируемся на минимальный возможный размер экрана, на котором полное число не влезло бы. Именно поэтому мы используем сокращенный формат, если число заблокированного превышает 999,999.
