### ISSUE TITLE
Interference between AGVPN and Adguard

### ISSUE THREAD

**Issue by khafan11** [AdguardTeam/AdguardForAndroid#5317]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4 Nightly 47

### Environment

- OS version: Android 14
- Device: vivo Y55 5G 

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Social

AdGuard Social Media filter

### Language-specific

Persian Blocker

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### Issue Details

Steps to reproduce:
1.Use AdguardVPN and Adguard  in Integrated mode 

### Expected Behavior

Should work without disruption and slowing down internet connection 

### Actual Behavior

If adguard is activated at the same time, the internet will slow down and not work properly.

### Screenshots

<details><summary>Screenshot 1</summary>

https://t.me/adguard/176184/206892

</details>

**Comment by ESurina** [comment]
Please try disabling battery optimization for both apps and let us know if this will fix the problem.

**Comment by khafan11** [comment]
@ESurina I had done this before, but it still had a problem
Unfortunately, the most severe restrictions have been implemented on Iran's Internet again since 4 days ago, and I can no longer use AGVPN (it does not connect).That's why I can't take more tests for now :(

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5317` number in the subject
    - specify the exact time when the issue occurred

**Comment by khafan11** [comment]
I sent it .
Unfortunately, it is rare to use Adguard and AdguardVPN at the same time
Although the VPN was connected (In VPN mode, not in Integration mode) during the last 24 hours without any problem

**Comment by ESurina** [comment]
Please send us also logs from AdGuard VPN if you manage to reproduce the problem again.
1. Enable debug logging:
*Settings -> General -> Advanced settings -> Logging level -> Extreme*
2. Reproduce the issue and remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced settings -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5317` number in the subject
    - specify the exact time when the issue occurred

**Comment by ESurina** [comment]
Could you please open a new issue and send us logs using the latest versions of apps and mentioning in the subject number of new issue?

**Comment by khafan11** [comment]
I opened a new issue in AdGuardVPNForAndroid I thought it was related to VPN
https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/465

**Comment by ESurina** [comment]
Thank you!
