### ISSUE TITLE
The application stops

### ISSUE THREAD

**Issue by Dreilk** [AdguardTeam/AdguardForAndroid#5318]
I use adguard daily, but out of nowhere the application when I review I start to see ads from other apps, I check and adguard ah stopped, I thought at first that it was because of the optimization of the battery, but it is not disabled, so some time passes and it stops. And to get it reactivated, I just have to open the app, but it appears active.

 Device: Realme GT Neo 3

 Android: 14 

App version: Adguard 4.4.167

**Comment by Versty** [comment]
@Dreilk Thank you for reporting! 
Obviously the same as #5314, please continue in the linked issue.

**Comment by Dreilk** [comment]
Hello, I would like to know if I can support your project in another way,
since I finished my beta tester license, but the program on my device
worked normally, so if I can support it in another way that would be great.
