### ISSUE TITLE
On MIUI China, it is not possible to keep “Unlimited power usage” all the time, causing “Self-start” to fail and blocking the background to be ineffective.

### ISSUE THREAD

**Issue by Benson2333** [AdguardTeam/AdguardForAndroid#5319]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

adguard nightly 4.4.177

### Environment

- OS version:Android 13
- Device:小米 11 lite 5G 国行

https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/238a4db2-1483-4372-91bc-4caab6cec8df

![Screenshot_20240515_130455_Settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/6ecdf576-6c64-49a1-a876-b55c217464ae)

![Screenshot_20240515_130504_Settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/52980f75-d541-434e-ac12-daaddab80a7f)

问题如录屏中说示，希望Adguard能提供解决方案，避免系统不必要的干扰，在用户需要时，能保持运行，不因其它原因中止。

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Chinese filter, EasyList China, EasyList Dutch, KAD - Anti-Scam

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1.检查过滤器更新
2.提示“fix it”
3.根据提示修改为“无限制使用电源”，并逐步操作
4.再次检查过滤器更新，复现之前的问题
5.检查“自启动”、“锁定后台”，保证都处于开启状态
6.关闭Adguard总开关，重新启用Adguard
7.再次复现问题
8.重启手机
9.Adguard无法在开机后自动运行，快捷通知栏的“adguard快捷方式”点击无效。
10.打开Adguard，问题复现。
11.之前Dr.web，也出现过类似问题，但是开启了截图中“设备管理应用”权限后，问题解决。
12.虽然这是MIUI的问题，但作为用户隐私的守卫者，我相信Adguard一定会有更好的解决方案的

#### ENG version
1. Check for filter updates
2. Prompt “fix it”.
3. Follow the prompts to change to “Unlimited power usage” and do it step by step.
4. Check the filter update again, and the previous problem is reproduced.
5. Check “Self-startup” and “Lock background” to make sure they are on.
6. Turn off the Adguard master switch and re-enable Adguard.
7. Repeat the problem again
8. Reboot the phone
9. Adguard can't run automatically after booting, and the “adguard shortcut” in the notification bar is invalid.
10. Open Adguard, the problem recurs.
11. Before Dr.web, there was a similar problem, but the problem was solved after opening the “Device Management Apps” permission in the screenshot.
12. Although this is a MIUI problem, as the guardian of user privacy, I believe Adguard will have a better solution!

</details>

https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/021b0682-40be-4934-a49b-aa98a2c28529

![Screenshot_20240515_130455_Settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/a176b18c-4495-4eaf-a5de-743825df3d0c)

![Screenshot_20240515_130504_Settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/afab592e-fb66-4164-a702-85d7f9bc8cf1)

### Expected Behavior

Adguard能平稳在后台运行，不再提示“fix it”，“无限制使用电源”不再决定Adguard能否正常运行。

https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/baf25ca6-a0df-42b3-8d19-5882eec98739

### Actual Behavior

“无限制使用电源”无法正常启用，无法保持后台运行

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

每次更新过滤器，后伴随adguard总开关的频繁重启。能否在更新全部过滤器后再统一重启。

**Comment by Versty** [comment]
@Benson2333 Thank you for reporting! 
We are aware of this issue, please enable the settings described in https://github.com/AdguardTeam/AdguardForAndroid/issues/5137 and let me know if it helps.

**Comment by Benson2333** [comment]
你好，官方提供的指导方案并没有实际效果。
由于我同时安装了Adguard、Adguard VPN，我发现一个很有趣的现象。
我的Adguard VPN能正常使用所有权限并保持后台运行，但是Adguard总是被系统恢复，造成运行失败。
据说是国内定制版MIUI的白名单/黑名单策略造成的。比如说，小爱同学、微信都属于白名单应用，系统一般不会禁用权限；但是，Adguard等隐私保护软件基本处于黑名单之内，我曾经安装的杀毒软件Dr.web、Eset、Mcafee都是因为被系统禁用权限导致防护失效。但是后来开启了“设备管理应用”，它们在一定程度上避免了黑名单策略的影响。
![20240515_200211](https://github.com/AdguardTeam/AdguardForAndroid/assets/134347283/71e8199b-794c-4efb-bc56-559a6edb0430)

**Comment by Versty** [comment]
@Benson2333 Thank you for provided details. 
We will consider this option, let's continue discussion in https://github.com/AdguardTeam/AdguardForAndroid/issues/5320
