### ISSUE TITLE
Translations don't fit in the field

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#5324]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.4 nightly 47

### Environment

- OS version: Android 8.10
- Device: Samsung J7 Prime

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Install AdGuard for Android nightly version
2. Create local VPN
3. And then 7 days trial screen will appear

### Expected Behavior

Translations should be fit in the description fields for those screens.

### Actual Behavior

Translations don't fit in the description fields. For the Turkish language, it doesn't fit only in a few screens. In other languages this may be different. This issue can occur in many languages, I think you need to test them all.

### Screenshots

<details><summary>Screenshot 1</summary>

![bug1](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/aedc018b-eec0-4a25-b004-f7ea7ae8f39f)
</details>

<details><summary>Screenshot 2</summary>

![bug2](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/640d80ff-a0c0-4993-80d7-b66cc4b99a57)
</details>

<details><summary>Screenshot 3</summary>

![bug3](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/a931a11d-7cfa-44be-bf53-69caf6dc3955)
</details>

<details><summary>Screenshot 4</summary>

![bug4](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/11f0b8bc-ad5d-4490-a608-c819e2534398)
</details>

**Comment by tengizmax** [comment]
«Thank you for bringing this defect to our attention. We have successfully reproduced the issue and are currently working on a solution. The problem will be resolved shortly, so stay tuned»
![Screenshot_20240517-184839_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/167526151/2fb1f7be-4839-4ede-93d3-c32f17f7c931)

**Comment by gork7777** [comment]
Looks like fixed now, thanks!
