### ISSUE TITLE
Notification Icon Is No Longer Material You Themed

### ISSUE THREAD

**Issue by TigerCraneStyle** [AdguardTeam/AdguardForAndroid#5329]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.4

### Environment

- OS version: Android 14
- Device: Google Pixel 8 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### Issue Details

Steps to reproduce:
1. Make sure Adguard is running.
2. Swipe down for the notification shade.
3.Here you'll see that the notification icon for Adguard is not themed to Material You like the icon would be if it were on the homescreen. It's like this on the lock screen also.

### Expected Behavior

The icon for Adguard Adblocker should be Material You themed in the notification shade and lock screen just like it is for Adguard VPN.

### Actual Behavior

The icon in the notification for Adguard Adblocker is its default dark green color instead of using the system's Material You theming. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

As you can see from the screenshots, the Adguard Adblocker icon should be the same color as the Adguard VPN icon in the notification shade and lock screen.
![Screenshot_20240522-091654](https://github.com/AdguardTeam/AdguardForAndroid/assets/131628729/34b8de1d-ed7a-43e0-bfb7-a25fcae638a7)
![Screenshot_20240522-090759](https://github.com/AdguardTeam/AdguardForAndroid/assets/131628729/0f6c95ae-1ff2-46b4-9329-a3e7f65b7870)

**Comment by Versty** [comment]
@TigerCraneStyle Thank you for reporting! 
Will be resolved in the next version.
