### ISSUE TITLE
[Feature Request] Search feature for User filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#533]
Originally from: 
https://forum.adguard.com/index.php?threads/issues-with-managing-the-user-filter.10029/

**Comment by dennisfong86** [comment]
Please implement this. This is a very much needed function!

**Comment by dennisfong86** [comment]
If this takes time to implement, can adguard at least sort the list with latest at the top. Hence we do not need to scroll all the way to the bottom list

**Comment by TPS** [comment]
> If this takes time to implement

@AdGuardTeam It'd be helpful if this were milestoned, so we users could know when to expect it.

**Comment by ameshkov** [comment]
There're some changes planned for user filter in v3.0, we'll take this feature request into account.

**Comment by TPS** [comment]
@ameshkov I use this constantly, so I suppose you could close this <kbd>Implemented</kbd>.

**Comment by ameshkov** [comment]
Yeah:)
