### ISSUE TITLE
Add direct app update wizard

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#5330]
### Issue Details

When an app update is available, we have to perform a full manual filter and database update in order to see the “Update app” button. In this case, after several app upgrades during the past 3 years, I have noticed that filter auto-update procedure gets stuck for a lot of days or even weeks when updating filters manually just before app update. (?)

### Proposed solution

Connect the notification for new version availability with direct download and install process, without having to do it through manual filter-database update screen.

**Comment by tengizmax** [comment]
Hi  @DimitrisKalaboukas , thanks for reaching out! We appreciate you taking the time to report this issue. 

We're investigating the issue you're experiencing with the app's filters not updating automatically. To help us pinpoint the cause, could you please tell us which power saving settings are active on your device, and if you have any battery optimization apps installed?  

Also, are you using root access on your device? This information might help us troubleshoot the issue."

**Comment by DimitrisKalaboukas** [comment]
@tengizmax I don’t use any battery/power optimization apps or modes, I have given AdGuard unlimited battery access, I have enabled “Watch Dog” and “Automatically restore local VPN” in low-level settings, and none of my family’s Samsung Galaxy devices is rooted.

**Comment by tengizmax** [comment]
Hi @DimitrisKalaboukas , thank you so much for your detailed feature request. Your idea is very interesting and we want to give it a thorough evaluation.

We'll need to carefully analyze how this feature would integrate with AdGuard's existing functionality, explore potential technical challenges, and consider its impact on overall app performance. We will keep you updated on our progress as we explore this possibility.

We will keep you updated on our progress as we explore this possibility.
We value your feedback and appreciate your continued support of AdGuard.

**Comment by tengizmax** [comment]
Hey there, @DimitrisKalaboukas 
 We're continuing to investigate the issue you're experiencing with. Can you please tell us a little more about your device:
* What version of Android is installed on your device? 
* What is the specific model of your Samsung Galaxy device? 
*  Do you leave the AdGuard app running in the background, even when you're not actively using it?

 Your answers will be extremely useful in helping us resolve this issue. Thank you for your cooperation 🤝 "

**Comment by DimitrisKalaboukas** [comment]
@tengizmax Hi,

My newest device is Samsung Galaxy A54, OneUI 6.1, Android 14. The app runs continuously in the background, as I mentioned above. I experience exactly the same behavior on the oldest ones. Also, I would like to point out that I have enabled 25 content blocking filters and 2 DNS filters.

I’m not sure if the problem is due to manual filter update or app upgrade process.

**Comment by DimitrisKalaboukas** [comment]
@tengizmax I accidentally discovered a trick that solves the problem. If I stay patient for the set auto-update time interval, disable the protection, and then turn it back on, filter auto-update process unfreezes instantly and keeps working fine.

**Comment by tengizmax** [comment]
@DimitrisKalaboukas , here we go again with some good news!
After painstaking analysis we decided to create the bug report #5362  based on your feature request , so resolve is on the way. Stay tuned !
