### ISSUE TITLE
Adguard with theme AMOLED true black

### ISSUE THREAD

**Issue by yuukiAme** [AdguardTeam/AdguardForAndroid#5333]
### Issue Details

Currently Theme settings only have 4 options

1. System
2. System dynamic
3. Light
4. Dark

I would like to have True Dark (AMOLED Black)

### Proposed solution

Add a 5th option for AMOLED True black

**Comment by tengizmax** [comment]
Hello, @yuukiAme. Thanks for feed-backing us! 
Hasten to inform, we've decided not to include your feature request in our upcoming AdGuard releases. 
We appreciate your ideas and are always open to suggestions.
