### ISSUE TITLE
Persistent snack about auto-update failure on Updates screen, MIUI 13

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#5334]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.1

### Environment

- OS version: MIUI 13 (Android 12)

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Open AG
2. Tap on the update filters icon (top-right). On the next page, we see the filters getting updated. On this same page, we see a message at the bottom saying "auto-updated may fail" with a "fix it" button.
3. Click on Fix it
4. On the next page, click on Allow button.
5. It redirects to system level battery optimisation settings. Select "No restriction". The page returns back and we still see the "Allow" button again.
6. 
7.
8.

### Expected Behavior

After clicking on Allow button it should take us to the system level battery optimisation page and when we select no restriction it should accept that and save it.

### Actual Behavior

It goes in a loop and ask us again and again to allow the battery optimisation settings as seen in the attached video.

Video: https://jmp.sh/s/qjYppMPO5zwgVDaHSTXc

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@Nzzyme Thank you for reporting! 
This behaviour is specific to MIUI and is controlled by the OS itself. 
We will remove the snack for Xiaomi devices.

**Comment by Schism86** [comment]
> @Nzzyme Thank you for reporting! This behaviour is specific to MIUI and is controlled by the OS itself. We will remove the snack for Xiaomi devices.

I have the same problem with Hyperos 1.0.1.0 on my Poco F3. 
However, it does not stop at this rather cosmetic problem, but there is also the following effect:
When I connect to a WLAN, my Internet connection does not work until I actively start Adguard.

**Comment by Nzzyme** [comment]
> @Nzzyme Thank you for reporting! This behaviour is specific to MIUI and is controlled by the OS itself. We will consider removing the snack for Xiaomi devices.

The snack bar should not be completely removed by default. The expected behavior is that it should be shown if AG is set to be optimized by the OS. If not, it should not be shown.

If AG is set to be optimized by the OS, then when we click on "Fix it" and then on "Allow" button, it should take us to the optimization page and when we select as "No restriction", it should save that value and then the snack bar should no longer be shown in the future.

**Comment by Nzzyme** [comment]
> > @Nzzyme Thank you for reporting! This behaviour is specific to MIUI and is controlled by the OS itself. We will remove the snack for Xiaomi devices.
> 
> I have the same problem with Hyperos 1.0.1.0 on my Poco F3. However, it does not stop at this rather cosmetic problem, but there is also the following effect: When I connect to a WLAN, my Internet connection does not work until I actively start Adguard.

It seems to be a different issue and not related to battery optimisation. Anyway, I think what you are going through is due to a setting in the MIUI Settings app. Try this:

1. Open system Settings app
2. Open the "VPN" settings. AG should be displayed there.
3.  Click on the settings icon against AG. (Do not click on AG but only on the Settings icon against AG).
4. Disable the option "Block connections without VPN" and enable the option "Always-on VPN"

That might fix it.

**Comment by Versty** [comment]
> If AG is set to be optimized by the OS, then when we click on "Fix it" and then on "Allow" button, it should take us to the optimization page and when we select as "No restriction", it should save that value and then the snack bar should no longer be shown in the future.

The battery optimisation settings are controlled by the OS. For some reason, when you select "No restriction" for the AdGuard application, MIUI automatically discards your action and sets the option to the default "Optimised" position.

> The snack bar should not be completely removed by default. The expected behavior is that it should be shown if AG is set to be optimized by the OS. If not, it should not be shown.

The snack is designed and is currently works this way. But due to OS behaviour on MIUI devices, the battery optimisation setting fails to be saved in "No restriction" position and the snack re-appears every time.

**Comment by Nzzyme** [comment]
> 
> The battery optimisation settings are controlled by the OS. For some reason, when you select "No restriction" for the AdGuard application, MIUI automatically discards your action and sets the option to the default "Optimised" position.
> 
> 
> The snack is designed and is currently works this way. But due to OS behaviour on MIUI devices, the battery optimisation setting fails to be saved in "No restriction" position and the snack re-appears every time.

Then how is it working fine with other apps (Example: Truecaller). I installed Truecaller and when the TC app ask for battery optimisation setting, I select "No restriction" and the setting is saved. without any problem. Hence, I don't think the issue with AG not saving the setting is due to MIUI. I believe this should be fixed within AG.

**Comment by Versty** [comment]
@Nzzyme To enable "no restrictions" mode for AdGuard application, please follow the steps below: 
1. Go to device Settings -> Apps -> Manage apps -> AdGuard and enable `Autostart`
2. In battery saver, tap `No restrictions`

**Comment by Versty** [comment]
@Nzzyme Did the solution above help?

**Comment by Nzzyme** [comment]
> @Nzzyme To enable "no restrictions" mode for AdGuard application, please follow the steps below:
> 
> 1. Go to device Settings -> Apps -> Manage apps -> AdGuard and enable `Autostart`
> 2. In battery saver, tap `No restrictions`

I did that and I still see the persistent snacks in AG.

**Comment by Versty** [comment]
@Nzzyme 
> So this is indeed an MIUI issue then

Unfortunately, yes, but we're still looking for workarounds. 
You can vote for this one https://github.com/AdguardTeam/AdguardForAndroid/issues/5320 if you believe that is the appropriate solution.

**Comment by Nzzyme** [comment]
@Versty : By the way, when I try the above steps now, I see that the setting is always set as "No restrictions"

1. Go to device Settings -> Apps -> Manage apps -> AdGuard and enable Autostart
2. In battery saver, tap No restrictions

So then it should be an issue with AG right?
