### ISSUE TITLE
Block Mobile app banners no longer work

### ISSUE THREAD

**Issue by Hr-2** [AdguardTeam/AdguardForAndroid#5335]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.4 nightly 48

### Environment

- OS version: Android 14
- Device: Oppo Reno8T

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1.enable Adguard protection 
2.open apps that has ads banners
3.you find out banners are still there 

### Expected Behavior

Before the nightly 48 update banners were completely blocked and not taking over the screen

### Actual Behavior

Banners now are either shown Normally with ads or they are shown as white banner with a weird icon or a blank white banner that never go away

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_2024-05-26-18-43-19-86_e1489033b7d39b6fecd3ecc39b887eec](https://github.com/AdguardTeam/AdguardForAndroid/assets/90532723/3330cdd9-8793-434e-a6a7-47432af345b9)
![Screenshot_2024-05-26-18-44-06-32_0c47faff67526709bf286e6c7b3f450f](https://github.com/AdguardTeam/AdguardForAndroid/assets/90532723/41459b54-664d-4507-a378-e5c8f2af60a6)

</details>

### Additional Information

Tried force stopping Adguard multiple times and restarting the protection

**Comment by ESurina** [comment]
We remind you that we are waiting for your logs.

**Comment by Hr-2** [comment]
Sorry i completely forgot about it, i enabled https filtering and it fixed
the issue, but after the update i disabled https filtering and it works
again all the banners are gone.

**Comment by ESurina** [comment]
Good news! If the problem happens again, reopen the issue.
