### ISSUE TITLE
Internet blocked but log shows nothing for some app/website

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdguardForAndroid#5339]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.1

### Environment

- OS version: Android 14
- Device: vivo x100 pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Try to open https://www.luckymobile.ca  || download and try to start the app https://play.google.com/store/apps/details?id=ca.luckymobile
2. Website can't open, shows internet not available || app won't start shows error code

### Actual Behavior

When I try to open https://www.luckymobile.ca
Browser gives error saying "internet not available". Tried on Vivaldi, Chrome, Firefox, all same error. AdGuard log shows nothing blocked.

When I try to start app https://play.google.com/store/apps/details?id=ca.luckymobile
The app can't even get to homepage and gives error code.
Adguard log shows blocked entries. I unblock everything until nothing shows up as blocked in log anymore, but app still won't start.

The only way to get the app to work is to turn off "Filter traffic" for the app in AdGuard apps setting.
Same for browser, disable "Filter traffic" for Firefox and website opens instantly.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@muchqs hmm, I checked the lucky mobile app as well as the website you mentioned. The app opens successfully, the steps to register are successful. I also checked the website opening in Chrome - the website opens successfully.

Maybe you have some custom settings or third party filters?

Could you send us your settings so we can make sure?
Go to Settings -> context menu -> Export settings
Send the settings file to devteam@adguard.com
mention the 5339 number in the subject

**Comment by maxikuzmin** [comment]
@muchqs hmm, I think the problem is with "Protect against DPI" enabled in Tracking protection section

try disabling "Protect against DPI" and try again

**Comment by maxikuzmin** [comment]
@muchqs great, glad to hear that! 
You can also use a custom rule to disable "Protection against DPI" only for the application you need. 
Use `@@||example.org^$stealth=dpi`
