### ISSUE TITLE
[Feature Request] Fix the rules order in user filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#534]
Now, when you add a new rule, it is added to the end of the list. But if you exit User filter and then open it again, the rule can be anywhere.

Let it stay at the end until another rule is added, or create a different way to standardize filter rules order.

Originally from: 
https://forum.adguard.com/index.php?threads/issues-with-managing-the-user-filter.10029/

**Comment by ameshkov** [comment]
Fixed in 2.9
