### ISSUE TITLE
Add common shortcuts at extended tap menu on AdGuard’s icon

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#5343]
### Issue Details

We have to open the app or find and extend AdGuard notification in order to access common tasks and functions like “Enable/Disable protection”, “Check for updates”, “Assistant” or “Developer tools”.

### Proposed solution

Add corresponding shortcuts at extended tap menu on AdGuard’s icon for quicker and easier access, as you did in version 3x.

**Comment by Versty** [comment]
@DimitrisKalaboukas If you wish this feature to be implemented, please vote by putting a `thumbs up` emoji in #4780
