### ISSUE TITLE
ping DNS

### ISSUE THREAD

**Issue by mahsamcse** [AdguardTeam/AdguardForAndroid#5345]
### Issue Details

There is not a very essential option
There is no ping check in the DNS settings section
As a result the user cannot detect the fastest DNS
Please add this option

### Proposed solution

As a result the user cannot detect the fastest DNS
Please add this option

**Comment by zzebrum** [comment]
@mahsamcse To be honest, it doesn't make sense because the speed of the DNS server depends on many things: how far away the server is physically located, server load, cache, etc. So basically you cannot use ping to guess which server is the fastest.
