### ISSUE TITLE
Automatically clear removed custom filter version info

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#5346]
### Issue Details

Regarding issue #5171, auto-removal of removed filter list version info hasn’t been fixed. For example, in uBlock Origin lists an invalid “! Version: %version%” line is periodically being added for a short time (probably due to a bug) and then removed completely from the list, but not from AdGuard’s Custom filters info.

### Proposed solution

Automatically clear custom filter version info, if the respective line has been removed from the list.

**Comment by ESurina** [comment]
We discussed your idea and came to the conclusion that we will not add this feature.
