### ISSUE TITLE
multiple DNS for different applications

### ISSUE THREAD

**Issue by mahsamcse** [AdguardTeam/AdguardForAndroid#5347]
### Issue Details

In the dns settings section
An option is needed so that the user can use multiple DNS for different applications
For example, it is possible to set program number 1 to use dns1, program number 2 to use dns2, and other programs and the system to use dns3.

### Proposed solution

For example, it is possible to set program number 1 to use dns1, program number 2 to use dns2, and other programs and the system to use dns3.

**Comment by ESurina** [comment]
We have reviewed your suggestion and unfortunately we will not be able to add this feature.

**Comment by mahsamcse** [comment]
Thank you for your review
Even similar to this program is not possible?
" YogaDNS "
