### ISSUE TITLE
Allow root user to make dns requests.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#535]
If firewall default network permissions are revoked, we block even the DNS requests from root.

**Comment by ameshkov** [comment]
What do you mean?

**Comment by Revertron** [comment]
If the user disabled all programs to go to internet (but enabled one browser, may be) we block even the DNS requests from root. But the browser will get errors on DNS resolving.

**Comment by ameshkov** [comment]
Ah, got it. I suppose this issue will be resolved in v3.0 when we rework the firewall permissions.

Our current implementation is really unclear to a user.
