### ISSUE TITLE
HTC battery optimization mode interferes with Adguard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#536]
http://www.htc.com/us/support/htc-one-m8/howto/696012.html#GUID-D0E37A62-8B95-4C21-A3F9-87E2326B739B

![image](https://cloud.githubusercontent.com/assets/15856304/15022146/e9542de0-1232-11e6-8460-3e568f60d16e.png)

IKG-440-76610
**1096732**

**Comment by ameshkov** [comment]
Is battery saver turned on by default on HTC?

**Comment by Revertron** [comment]
And what can we do about it? Tell the user to disable battery saving for Adguard or what?

**Comment by ameshkov** [comment]
@Revertron I suppose that when we receive a "battery saving" even we could check if network is really unavailable for Adguard app. If network is available then we should not pause protection.

**Comment by Bohdan-SUP** [comment]
Some logs:
VDF-752-59059
EMQ-109-95833
RFJ-568-16447
HIL-135-60806

**Comment by ameshkov** [comment]
@Bohdan-SUP please ask users to check it with this new build:
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.5.234-dev

**Comment by Bohdan-SUP** [comment]
Yup, emailed them.

**Comment by ameshkov** [comment]
@Bohdan-SUP any update on this?

**Comment by evgeniy-ADG** [comment]
@ameshkov 
EMQ-109-95833: Сутки прошли, работает. А нет, Только вам написал и заметил что вылетает защита...
No replies from other users.

**Comment by ameshkov** [comment]
@evgeniy-ADG нужен лог

**Comment by evgeniy-ADG** [comment]
Во время звонка пропадает интернет, программа уходит на паузу, после завершения звонка защита не восстанавливается. Хотя инет есть. лог вот тут PMH-145-99165

**Comment by ameshkov** [comment]
> Во время звонка пропадает интернет, программа уходит на паузу, после завершения звонка защита не восстанавливается. Хотя инет есть. лог вот тут PMH-145-99165

Это все же другая issue. Заведешь?

**Comment by evgeniy-ADG** [comment]
Заведу, это пришло в ответ на просьбу попробовать ту версию, то ты двал (10 days ago).

**Comment by ameshkov** [comment]
Вот билд на проверку:
[adguard-android.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/286303/adguard-android.apk.zip)

В нем все должно быть исправлено.
В следующую бета-версию войдет это исправление.

**Comment by vozersky** [comment]
Пользователь сообщает, что 2.6.23 не помогла, а в  2.6.67 - "программа встает на паузу через 10-15 секунд после запуска"

Логи - IZX-563-67436

**Comment by ameshkov** [comment]
Должно исправиться в следующей бете

**Comment by vozersky** [comment]
такая же проблема, HTC One M8, логи - 1142530

**Comment by ameshkov** [comment]
Relevant forum thread:
https://forum.adguard.com/index.php?threads/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%90%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0.11762/#post-91136

**Comment by ameshkov** [comment]
This version should fix it:
https://github.com/AdguardTeam/AdguardForAndroid/files/371503/adguard.apk.zip
