### ISSUE TITLE
Use Galaxy Store instead of installing APK directly if possible

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardForAndroid#5367]
### Issue Details

It seems that AdGuard for Android can be distributed at [Galaxy Store](https://galaxystore.samsung.com/detail/com.adguard.android).
Google disallows its distribution at Google Play store.
So, currently, AdGuard recommends installing it as APK file directly.
However, it is annoying and hard to install for some people.

### Proposed solution

If Galaxy Store is available on an user's device, Galaxy Store can be used for distributing and updating about AdGuard for Android instead of installing APK file directly.

**Comment by maxikuzmin** [comment]
@piquark6046 we have already recently published AdGuard in Galaxy store :) 
Check it out and try to download it
