### ISSUE TITLE
TPROXY IPv6 filtering method is broken in version 4.5

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#5370]
Seems that IPv6 is not filtered on older devices with does not have IPv6 NAT table.

They does not show AdGuard certificate.

To reproduce, you should use rooted device without `nat` table in `ip6tables`.

In this case AG fallbacks to older TPROXY method.

But seems that rules are created incorrectly:

`ip -6 rule` shows that AG uses two fwmarks - 0x1a and 0x1b:
```
8000:	from all fwmark 0x1a lookup 800 
8001:	from all fwmark 0x1b lookup 800 
```

But `ip6tables-save` show another marks:
```
-A ADGUARD_OUTPUT -p tcp -m tcp --dport 53 -j MARK --set-xmark 0x1b/0xffffffff
-A ADGUARD_OUTPUT -p tcp -m tcp --dport 80:5221 -j MARK --set-xmark 0x1c/0xffffffff
-A ADGUARD_OUTPUT -p tcp -m tcp --dport 5299:65535 -j MARK --set-xmark 0x1c/0xffffffff
-A ADGUARD_PREROUTING -p tcp -m mark --mark 0x1b -j TPROXY --on-port 1152 --on-ip ::1 --tproxy-mark 0x0/0x0
-A ADGUARD_PREROUTING -p tcp -m mark --mark 0x1c -j TPROXY --on-port 41551 --on-ip ::1 --tproxy-mark 0x0/0x0
-A ADGUARD_PREROUTING -p tcp -m mark --mark 0x1c -j TPROXY --on-port 41551 --on-ip ::1 --tproxy-mark 0x0/0x0
```

So, output traffic is marked as 0x1c which is not handled in `ip -6 rule`.

At some point, marks were desynchronized, breaking IPv6 filtering.

**Comment by Rtizer-9** [comment]
Hi, is there any update on this?

**Comment by Rtizer-9** [comment]
@Dondrejohnson5 vote the issue

**Comment by sfionov** [comment]
@Rtizer-9 @Dondrejohnson5 

Hello! TPROXY issue was fixed in AdGuard 4.6 release and the latest nightly.

**Comment by Dondrejohnson5** [comment]
@maxikuzmin I hear this underlying issue has been around for a few years but has gone undiscovered until recently? That would explain why the initial 4.0 announcement of ipv6 filtering in auto proxy not being what I had hoped it was

**Comment by Rtizer-9** [comment]
@sfionov yes I checked last night and it's working perfectly in root proxy mode.

Unlike before adguard is now able to capture and filter all the requests even when wireguard (official app) is on.

The only issues that remain are the ones that come with using root proxy like http3, quic not working but anyway wireguard, warp can now be used with adguard and that too in kernel module mode without any issues now.

Thanks a lot @sfionov
