### ISSUE TITLE
Telemetry removing

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#5371]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

How filtering and blocking  by adguard / remove telemetry and etc on any installed applications?

**Comment by tengizmax** [comment]
@U0101100, thanks for that question, after the detail handling we're coming with some info!
  Most telemetry features in applications based on making network requests to specific domains. AdGuard can effectively block these requests using its advanced filtering mechanisms:
* DNS Filtering: AdGuard maintains comprehensive DNS filter lists that include domains known for telemetry, tracking, and advertising. When an app attempts to send data to a blacklisted domain, AdGuard intercepts and blocks the request at the DNS level.
* URL Blocking: AdGuard can analyze the URLs of network requests and block those matching patterns associated with telemetry.
* HTTPS Filtering: To handle telemetry transmitted over HTTPS, AdGuard employs local HTTPS proxying and filtering. This allows it to inspect and block requests even within encrypted connections.
By using these methods, AdGuard can effectively disable or significantly reduce telemetry collection by various applications installed on your device.
