### ISSUE TITLE
Adguard crash immediately after start every time if device doesn't turn on logcat records

### ISSUE THREAD

**Issue by ajdgsu** [AdguardTeam/AdguardForAndroid#5372]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

since 4.xx

### Environment

- OS version: MIUI 14.07 (Android 13)
- Device: Xiaomi 13

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

EasyPrivacy

### Language-specific

AdGuard Chinese filter

### Other

Filter unblocking search ads and self-promotion

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.turn off the logcat records before install the adguard
2.install adguard
3.start app

### Expected Behavior

start normally

### Actual Behavior

crash immediately

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_2024-06-23-13-37-31-239_com android settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/45306865/d3b21d81-35e5-4c57-8752-75bea789d2fa)

</details>

### Additional Information

if device doesn't turn on the logcat records function (like in picture) before the adguard app installed, after install the app simply crash immediately when you trying to start, this behavior only happens  on 4.xx version (yes the last 3.xx version, which is 3.6.54 doesn't have this issue). after turn on logcat records then apps can start normally, and even turn of the logcat records again adguard can still running without problem.

ps: if user installed some magisk modules that disabled the logcat, this can also cause problems as well.

logs here: 
[adguard.zip](https://github.com/user-attachments/files/15942779/adguard.zip)

**Comment by ESurina** [comment]
There is no any error in your logs. Could you please collect logs again using this manual:
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5372` number in the subject
    - specify the exact time when the issue occurred
    
Also send us your system logs please. Here's how to do it: https://adguard.com/kb/adguard-for-android/solving-problems/logcat/

**Comment by ajdgsu** [comment]
logs here: 
[logs-2024-06-29-15-33-42.zip](https://github.com/user-attachments/files/16039222/logs-2024-06-29-15-33-42.zip)
And adguard seems also crash when the logcat records enabled, not sure what's going on.

**Comment by ESurina** [comment]
We suspect that the problem is with your phone's system. This problem does not occur on our side. We will investigate it again if more users complain about it.
