### ISSUE TITLE
Random and frequent no data internet connection.

### ISSUE THREAD

**Issue by TheWrathRF** [AdguardTeam/AdguardForAndroid#5375]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5

### Environment

- OS version: Android 14
- Device:  POCO X6 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, Dandelion Sprout's Annoyances List

### Language-specific

AdGuard Russian filter

### Other

Filter unblocking search ads and self-promotion

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Steps to reproduce:
1. Enable HTTPS filtering and DNS protection 
2. Surf the internet. It may occur in any time.

### Expected Behavior

Connection should be stable. Data loss shouldn't occur.

### Actual Behavior

Data is interrupted at frequent intervals, this continues for a few seconds and there is no internet connection during this time. For instance, while I am surfing on YouTube the contents stuck on loading for a few seconds, videos keep stuck on loading due to no data and while I am surfing on browser I cannot enter to the website.

### Additional Information

Logs if needed
[adguard.log](https://github.com/user-attachments/files/15974590/adguard.log)
[adguard_logs_4.5.17_2506_192350.zip](https://github.com/user-attachments/files/15974666/adguard_logs_4.5.17_2506_192350.zip)

**Comment by TheWrathRF** [comment]
> ### Please answer the following questions for yourself before submitting an issue
> * [x]  Filters were updated before reproducing an issue
> * [x]  I checked the [knowledge base](https://adguard.com/kb/) and found no answer
> * [x]  I checked to make sure that this issue has not already been filed
> 
> ### AdGuard version
> 4.5
> 
> ### Environment
> * OS version: Android 14
> * Device:  POCO X6 Pro
> 
> ### HTTPS filtering
> * [x]  yes, I do
> 
> ### Root access
> * [ ]  yes, I have it
> 
> ### Integration with AdGuard VPN
> * [ ]  yes, I do
> 
> ### Routing mode
> Local VPN
> 
> ### Ad Blocking
> AdGuard Base filter, AdGuard Mobile Ads filter
> 
> ### Privacy
> AdGuard Tracking Protection filter
> 
> ### Social
> AdGuard Social Media filter
> 
> ### Annoyances
> AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, Dandelion Sprout's Annoyances List
> 
> ### Security
> _No response_
> 
> ### Language-specific
> AdGuard Russian filter
> 
> ### Other
> Filter unblocking search ads and self-promotion
> 
> ### Which DNS server do you use?
> AdGuard DNS
> 
> ### DNS protocol
> DNS-over-QUIC
> 
> ### Custom DNS
> _No response_
> 
> ### What Stealth Mode options do you have enabled?
> Block trackers
> 
> ### Issue Details
> Steps to reproduce:
> 
> 1. Enable HTTPS filtering
> 2. Surf the internet. It may occur in any time.
> 
> ### Expected Behavior
> Connection should be stable. Data loss shouldn't occur.
> 
> ### Actual Behavior
> Data is interrupted at frequent intervals, this continues for a few seconds and there is no internet connection during this time. For instance, while I am surfing on YouTube the contents stuck on loading for a few seconds, videos keep stuck on loading due to no data and while I am surfing on browser I cannot enter to the website.
> 
> ### Screenshots
> _No response_
> 
> ### Additional Information
> Logs if needed [adguard.log](https://github.com/user-attachments/files/15974590/adguard.log) [adguard_logs_4.5.17_2506_192350.zip](https://github.com/user-attachments/files/15974666/adguard_logs_4.5.17_2506_192350.zip)

Edit: It looks like the same problem keeps occuring even the https filtering turned off but it became less consistent compared to HTTPS filtering on.

**Comment by TheWrathRF** [comment]
Yes I have tried all DNS settings even turning it off. The issue shows itself both on YouTube and browser.

**Comment by Versty** [comment]
@TheWrathRF Could you please enable the debug logging level and collect the data again? 
This will help a lot in further investigation. 

Here are the steps to follow: 
1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Wait for the issue to be reproduced, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5375` number in the subject
      - specify the exact time when the issue occurred

**Comment by TheWrathRF** [comment]
İncreasing MTU 9000 to 15000 did fix the issue.

**Comment by TheWrathRF** [comment]
İncreasing MTU 9000 to 15000 did fix the issue.

**Comment by flo-m** [comment]
any explanation why increasing the MTU to 15.000 fixes this?
Is it safe to just increase it to this high value?
