### ISSUE TITLE
What Does adding apps to the quic bypass really do?

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5377]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I have gathered a list and added it to quic bypass on apps that have udp/quic connections blocked. Should i not be doing this unless there are problems with the app?

**Comment by ESurina** [comment]
You shouldn't do it unless you have problems with the app.
