### ISSUE TITLE
Filter Updates Fail Often

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#5378]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5

### Environment

- OS version: MIUI 13 (Android 12)

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Open AG
2. Click on the update filters icon on the top-right
3. It tries to check for all available updates and then couple of them fail most of the times (not always)

See link for video

### Expected Behavior

The below sequence should be followed:

1. It should check for all available filter updates
2. Download all of them
3. Restart once to apply them

It seems that this sequence is not followed. While some are getting downloaded, some others are getting applied and protection restarts multiple times and this is causing updates to fail.

### Actual Behavior

See above Issue Details

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Video link: https://jmp.sh/s/WiUM0aJsJjCWPGAthIZg

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*
2. Reproduce the issue, then remember the exact time when it happened
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*
4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `5378` number in the subject
    - specify the exact time when the issue occurred

**Comment by Nzzyme** [comment]
Let me do that and send it to you.

**Comment by Nzzyme** [comment]
It's not been happening since I have raised this issue. I think we can close this for now.
