### ISSUE TITLE
Question on Tracking Protection

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardForAndroid#5380]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I have the Privacy Protection Level set to "Custom" on the "Tracking Protection" page and then I have enabled few options below under the sections: General settings, Tracking methods, Browser API, Misc

When I disable the main switch for "Tracking Protection", should all the options under "Custom" (General settings, Tracking methods, Browser API, Misc) also get disabled or should they continue to be enabled?

**Comment by ESurina** [comment]
The options should continue to be enabled, but they don't apply.

**Comment by Nzzyme** [comment]
That doesn't make any sense. Once the main switch for "Tracking Protection" is disabled, shouldn't all the other options under "Custom" be enabled but greyed out like the earlier version of AG? Currently, it allows the user to toggle the other options in spite of the main switch being disabled. This, in my opinion is not a good design of UI and needs to be 'fixed'.

See the below screenshot. The switches on that page need to be "Disabled but on"

https://i.sstatic.net/nT9K5.png
