### ISSUE TITLE
Translations are missing for Annoyances blocking notice

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#5388]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.6 nightly 11

### Environment

- OS version: Android 8.1.0
- Device: J7 Prime

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Go to the Annoyance blocking which is 3rd from the top at the homepage (from the first tab when opened app).
2. Enable Annoyance blocking (then notice popup will be appear).
3. And you can see filters names and descriptions are missing for translations.

### Expected Behavior

Add filter names and descriptions for the Crowdin or add the translations to the app.

### Actual Behavior

Strings are missing at the Crowdin probably or translations are didn't added to the app.

### Screenshots

<details><summary>Screenshot 1</summary>

![Bug](https://github.com/AdguardTeam/AdguardForAndroid/assets/35523759/cdf2b3fc-cc27-4db6-935b-91b620702a00)
</details>

**Comment by Versty** [comment]
@gork7777 Thank you for reporting! 
Will be fixed.

**Comment by gork7777** [comment]
Looks like fixed in the v4.6 nightly 14

**Comment by gork7777** [comment]
The issue still exists in v4.7 Nightly 17.
