### ISSUE TITLE
Cursor barely visible at search bars in the Dark theme

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#5397]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6 nightly 14

### Environment

- OS version: Android 8.1.0
- Device: J7 Prime

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Go to any search bars (or at least while activating licence).
2. Type anything and check the cursor in the Dark theme.

### Expected Behavior

Make (like more light green instead of dark green) more visible the cursor in the Dark theme.

### Actual Behavior

You barely see the cursor in the Dark theme at the search bars.

### Screenshots

<details><summary>Dark theme</summary>

![Cursor2](https://github.com/user-attachments/assets/857d2e9d-4e18-4153-a479-07daeaff0c21)
</details>

<details><summary>Light theme</summary>

![Cursor1](https://github.com/user-attachments/assets/9ebc58ac-c6fd-4443-a643-41ff6ed943cd)
</details>

**Comment by maxikuzmin** [comment]
@gork777777 thank you! We'll fix it in the next updates
