### ISSUE TITLE
Ads are not blocked for the Twitch app

### ISSUE THREAD

**Issue by Yapeeyaper** [AdguardTeam/AdguardForAndroid#5399]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5

### Environment

- OS version: android 13
- Device: samsung s20plus

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdBlockID

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

Regular

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Steps to reproduce:
1. Doesnt not block ads on twitch app
2.
3.

### Actual Behavior

Does not block ads on twitch

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@Yapeeyaper could you send me a screenshot of the ads you see on twitch?
Could you please clarify if you have "AdGuard Extra" userscript enabled?

**Comment by Yapeeyaper** [comment]
I dont have a screenshot and what is adguard extra

**Comment by maxikuzmin** [comment]
@Yapeeyaper could you please take a screenshot of the ads on Twitch so I understand what ads you're talking about and what exactly you're seeing?

AdGuard Extra userscript is located in: Settings -> Filtering -> Userscripts -> AdGuard Extra

**Comment by maxikuzmin** [comment]
@Yapeeyaper any news?

**Comment by maxikuzmin** [comment]
@Yapeeyaper for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by Yapeeyaper** [comment]
Hi,

See the screenshot attached ads been played on twitch

**Comment by maxikuzmin** [comment]
@Yapeeyaper I don't see screenshots in this issue. Re-send the screenshot by message here, or to our email [devteam@adguard.com](mailto:devteam@adguard.com).

**Comment by Yapeeyaper** [comment]
Hi please see image attached

**Comment by maxikuzmin** [comment]
@Yapeeyaper please send screenshots in our email [devteam@adguard.com](mailto:devteam@adguard.com).
Don't forget to mention the issue number 5399

**Comment by maxikuzmin** [comment]
@Yapeeyaper any news?

**Comment by Yapeeyaper** [comment]
I have emailed it 4 times

**Comment by maxikuzmin** [comment]
@Yapeeyaper I got your screenshots. Sorry for the delay. Unfortunately you can't block ads on Twitch for the app. Only in the browser, in the web version of Twitch. I didn't see that you were talking about the app, in this case it's recommended to use the web version of Twitch

**Comment by Yapeeyaper** [comment]
Hi


It doesnt work via web browser

**Comment by maxikuzmin** [comment]
@Yapeeyaper I checked this with myself and I have no ads showing in Twitch. Could you be more specific as to what country you are in? I think I saw a discussion a while back that Twitch allocates ads to specific countries. Also, to be sure, you can connect to a VPN and check it again

**Comment by Yapeeyaper** [comment]
I am based in the uk

**Comment by maxikuzmin** [comment]
@Yapeeyaper have you tried testing this with a VPN? Try connecting to a different location

**Comment by Yapeeyaper** [comment]
Hi

I dont have access to a vpn.

**Comment by maxikuzmin** [comment]
@Yapeeyaper you not answered, do you have Userscript AdGuard Extra enabled?
AdGuard Extra userscript is located in: Settings -> Filtering -> Userscripts -> AdGuard Extra
It is also better to check for updates and update all filters (Home tab -> top right corner)
Then try to check the ads again in the web version of Twitch
