### ISSUE TITLE
Notification categories not available on Android 14 tablet

### ISSUE THREAD

**Issue by GermanKiwi** [AdguardTeam/AdguardForAndroid#5402]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5

### Environment

- OS version: Android 14
- Device: Samsung Galaxy Tab S9+

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

I have a Samsung Galaxy S24 Ultra (phone), and a Samsung Galaxy Tab S9+ (tablet) - both are running AdGuard 4.5.

On my Galaxy S24 Ultra, I can go to **AdGuard Settings > General > App notifications** - and at the bottom there is **Notification categories** - which is a standard Android feature that most apps have.

However, on my Galaxy Tab S9+, if I go to **App notifications** there is no **Notification categories** at the bottom.

This means I'm unable to configure the individual notification categories according to my needs, as I can on my Galaxy S24.

Other apps on my tablet include notification categories, so I don't believe this is some limitation of the device itself.

### Expected Behavior

Expected behaviour is being able to view notification categories on all Android devices.

### Actual Behavior

No notification categories available on Galaxy Tab S9+.

### Screenshots

**Screenshot 1 - Galaxy Tab S9+ with no notification categories:**
<img src="https://github.com/user-attachments/assets/16d27a9b-d06a-40df-8431-4c1abe7b10ed" width="400px" />

**Screenshot 2 - Galaxy S24 with notification categories (expected behaviour):**
<img src="https://github.com/user-attachments/assets/8388dcbc-b4b0-44cd-b77c-1c2ccb254d4a" width="400px" />

**Screenshot 3 - Galaxy S24 with notification categories (expected behaviour):**
<img src="https://github.com/user-attachments/assets/146e2d23-1729-420b-8009-fc877c28b0b2" width="400px" />

**Comment by AlfredSpijker** [comment]
Are you sure:
"Other apps on my tablet include notification categories"?

Mayve this is caused by a recently added Samsung setting.  In Android settings, go to Notifications > Advanced settings > "Manage notification categories for each app" and enable this option.  Maybe this solves your priblem?

**Comment by GermanKiwi** [comment]
"Manage notification categories for each app" was indeed disabled - no idea how or when that setting was added - I've never seen it before. But this has fixed it - thanks! I'll close the issue then.
