### ISSUE TITLE
Adguard CA for HTTPS filtering is failing on Android 15

### ISSUE THREAD

**Issue by DenyDarko** [AdguardTeam/AdguardForAndroid#5403]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7 Build 1

### Environment

- OS version: OxygenOS based on Android 15, second DP
- Device: OnePlus 12

![Screenshot_2024-07-20-23-04-21-81_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/9517ea10-e616-4612-9b0c-2e5c8c40c75c)

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

Regular

### Issue Details

Steps to reproduce:
1. Get the CA obtained from the Adguard app.
2. Try to install it
3. Get a certificate is invalid message 

### Expected Behavior

CA Cert to be installed 

### Actual Behavior

CA Cert is failing to install.

### Screenshots

https://github.com/user-attachments/assets/226889d6-e1e8-450d-b971-8821be9548ae

**Comment by DenyDarko** [comment]
Attaching the CA used it the record.
[Uploading adguard_2007_223925.zip…]()

**Comment by Versty** [comment]
@DenyDarko We have tried to reproduce this issue on our Android 15 device, but to no avail. Therefore we would like you to collect the bug report from your device. 

Please follow the steps below: 
1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect the system bug report as described in [the article](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) 

4. Send this file to devteam@adguard.com:
      - mention the `5403` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment]
@DenyDarko Have you sent the system bug report?

**Comment by DenyDarko** [comment]
Unfortunately I've reverted back to Android 14 so I'm unable to provide more logs.
