### ISSUE TITLE
Filters update error on Android 7

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardForAndroid#5404]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard v4.5 (10186574)

### Environment

- OS version:Android 7
- Device: Asus z500m

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Social

AdGuard Social Media filter

### Language-specific

AdGuard Russian filter, AdGuard Ukrainian filter

### Other

Filter unblocking search ads and self-promotion

### Which DNS server do you use?

Google DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries

### Issue Details

Steps to reproduce:
1.Открыть приложение;
2.Нажать на кружочек для поиска обновлений
3.

### Expected Behavior

Чтобы обновились фильтры и всё работало как ожидается.

### Actual Behavior

Не удалось обновить фильтры.

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_20240721-145235](https://github.com/user-attachments/assets/cb81856d-2421-48d4-aec9-f5d225254349)

</details>

### Additional Information

Значит,дело было так: Всё началось с того,что я захотел обновить фильтры на старой версии приложения 3.11,потому что подумал,что проблема,по которой у меня не хочет срабатывать правило,касающееся одного сайта, может быть связана с устаревшими наборами corelibs. Вскоре пошёл проверять обновления,а там аналогичная ситуация: фильтры отказывались обновляться.бПоследнее обновление было за 8 июля. Думал,что проблема в приложении. Сделал сброс настроек,но ни к чему это не привело: по-прежнему была ошибка. "Ну,—думаю я.—Обновлю приложение!" Обновил,и картина такая же. Значит,это не связано с версиями приложений,ибо на другом гаджет с версией 3.11 проблем с обновлениями нет,а,следовательно,проблемы с версией ос. Разберитесь в этом вопросе, пожалуйста.

**Comment by Versty** [comment]
@Spok1 Добрый день! 

Чтобы разобраться в причинах возникшей ошибки, нам потребуются логи с вашего устройства. 
Пожалуйста, следуйте шагам ниже, чтобы собрать и отправить логи нам на почту. 

1.  Включите подробный уровень логирования:
*Настройки -> Основные -> Расширенные -> Уровень логирования -> Подробный*

2. Воспроизведите проблему, запомните точное время воспроизведения

3. Экспортируйте логи: 
*Настройки -> Основные -> Расширенные -> Экспортировать логи и информацию о системе* 

4. Отправьте файл на почту devteam@adguard.com:
      - упомяните `5404` номер в заголовке письма
      - укажите точное время воспроизведения проблемы

**Comment by Spok1** [comment]
@Versty, здравствуйте. Что-то там по поводу проблемы?

**Comment by Versty** [comment]
@Spok1 Добрый день! 
Логи с вашего устройства получили и в настоящей момент их изучаем, чтобы лучше понять причину появления проблемы.

**Comment by Spok1** [comment]
@Versty ,а ранее сервер же доверял ssl от Let's Encrypt! Аж до 8-го июля. В общем,я воткнул в систему новый кроссовый ssl от Iden Trust—ISRG Root X1 проблема устранилась. Обновления проходят.

**Comment by Spok1** [comment]
@Versty ,а ранее сервер же доверял ssl от Let's Encrypt! Аж до 8-го июля. В общем,я воткнул в систему новый кроссовый ssl от Iden Trust—ISRG Root X. Проблема устранилась. Обновления проходят.Прескорбно,что вы не смогли мне помочь,хотя это в вашей компетенции!😒

**Comment by Spok1** [comment]
@Versty, а ранее сервер же доверял ssl от Let's Encrypt! Аж до 8-го июля. В общем, я воткнул в систему новый кроссовый ssl от Iden Trust—ISRG Root X. Проблема устранилась. Обновления проходят. `Прискорбно, что` вы не смогли мне помочь, хотя это в вашей компетенции!😒

**Comment by Spok1** [comment]
@Versty ,а ранее сервер же доверял ssl от Let's Encrypt! Аж до 8-го июля. В общем, я воткнул в систему новый кроссовый ssl от Iden Trust—ISRG Root X1. Проблема устранилась. Обновления проходят для версии приложения 3.6.11. А Для версии 4.5.x нет. Сервер не уже не доверяет чёлочке ISRG ROOT Х1 или что? Какой сертификат ещё установить нужно, чтобы обновление проходило? Разве фильтры не на одном сервере находятся? Почу для старой версии приложения обновления проходят, а для новой нет?

**Comment by Spok1** [comment]
@Versty ,а ранее сервер же доверял ssl от Let's Encrypt! Аж до 8-го июля! В общем, я воткнул в систему новый кроссовый ssl от Iden Trust—ISRG Root X1. Проблема устранилась. Обновления проходят для версии приложения 3.6.11. А для версии 4.5.x нет. Сервер уже не доверяет цепочке ISRG ROOT Х1 или что? Какой сертификат ещё установить нужно, чтобы обновление проходило? Разве фильтры не на одном сервере находятся? Почу для старой версии приложения обновления проходят, а для новой нет? Вопросов больше, чем ответов!

**Comment by tachibana-shin** [comment]
I installed the X1 certificate and updated it successfully 
https://letsencrypt.org/certs/isrgrootx1.pem

More: https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

**Comment by Spok1** [comment]
@tachibana-shin, I have this certificate installed, and nevertheless filter updates to versions higher than 3.6 do not work. What else did you do to update filters?

**Comment by Spok1** [comment]
@tachibana-shin, I have this certificate installed, and nevertheless filter updates to versions higher than 3.6 do not work. What else did you do to update filters?

![Screenshot_20241220-221211_1](https://github.com/user-attachments/assets/825499f7-08e4-4de3-873c-51dd7a4100a6)

**Comment by tachibana-shin** [comment]
> @tachibana-shin, I have this certificate installed, and nevertheless filter updates to versions higher than 3.6 do not work. What else did you do to update filters?
> 
> ![Screenshot_20241220-221211_1](https://private-user-images.githubusercontent.com/34476664/397854262-825499f7-08e4-4de3-873c-51dd7a4100a6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3Njc4NzMsIm5iZiI6MTczNDc2NzU3MywicGF0aCI6Ii8zNDQ3NjY2NC8zOTc4NTQyNjItODI1NDk5ZjctMDhlNC00ZGUzLTg3M2MtNTFkZDdhNDEwMGE2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA3NTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NzVhNmM1ZTJjMWQ3Y2NmZTg2ZTdlOThhMjUxMzYzNGY4YTYyYWVkZmI4NDMwZDRkMDhhYzUxMzhhOTJjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x90B32pTQUVm5dvw2B5iZsZvDlZdYVP9ld4nQzV1rOA)

Try installing additional r3 certificates

- https://letsencrypt.org/certs/isrgrootx1.pem
- https://letsencrypt.org/certs/lets-encrypt-r3.pem

**Comment by Spok1** [comment]
@tachibana-shin, Isn't the R3 outdated? Its expiration date is until 2025.

**Comment by tachibana-shin** [comment]
> @tachibana-shin, Isn't the R3 outdated? Its expiration date is until 2025.

I didnt notice the expiration date but as of now if i dont have r3 my huawei tablet will not update the filter i think after christmas i will check it again

**Comment by Spok1** [comment]
@tachibana-shin,I installed R5, and the result was the same. In addition, the new version causes increased battery consumption, so I will have to go back to version 3.
