### ISSUE TITLE
AdGuard blocking some apps from connecting to internet

### ISSUE THREAD

**Issue by Gestrid** [AdguardTeam/AdguardForAndroid#5405]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6

### Environment

- OS version: Android 14
- Device: Google Pixel 6 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### Which DNS server do you use?

Automatic DNS

### DNS protocol

Regular

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Disable WebRTC, Hide your Referrer from third-parties, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1. Have AdGuard 4.6 running.
2. Open an affected app.
3. The app will fail to load or will not load properly.

### Expected Behavior

I expected the app to load properly.

### Actual Behavior

I attempted to open the app [AL-chan](https://play.google.com/store/apps/details?id=com.zen.alchan), a 3rd party app for the website AniList. It remained stuck trying to open until I disabled AdGuard. The app immediately started working after that.

Similarly, another app, [Aluminum](https://play.google.com/store/apps/details?id=moe.emi.aluminium), also a 3rd party app for AniList, stays stuck with its spinning loading symbol. Noticeably, images in the background behind the transparent loading screen layer fail to load. Again, the app begins working as soon as I disable AdGuard.

The Twitter app also seems to be affected. Images and profile pictures that haven't been cached will not load until AdGuard is disabled. Then they load immediately. Though it's worth noting I'm using v9.88.0-release.0 of the app, not the current version.

Also, an app distributed privately through my work fails to load as well. The app's pre-login screen loads, but, when I attempt to go to the login screen, it simply shows a white screen. The app uses a work account (ex. username@companydomain.com), and login is handled by Microsoft.

### Screenshots

<details><summary>Screenshots</summary>

AL-chan

![Screenshot_20240725-035240](https://github.com/user-attachments/assets/23ed7ad2-464e-4ff7-bf14-766b939814e0)

Aluminum

![Screenshot_20240725-035659](https://github.com/user-attachments/assets/4c1a26b9-80bb-4b11-8d89-e00d5e9eb141)

</details>

### Additional Information

This issue started immediately after I updated from v4.5 to v4.6.

The issue goes away if I either disable AdGuard or change its settings so specific apps don't have their traffic routed through AdGuard.

**Comment by CrimsonKnight13** [comment]
I've had this same issue on my Pixel 8 (Android 14). The issue went away when I rolled back to 4.5.

**Comment by wattsja** [comment]
This new version is broken (was in Nightly/Beta .. as is 4.7 Nightlys). Here are my troubleshooting steps thus far after the upgrade broke me.

So, saved my settings uninstalled and tried the following:

1. Uninstalled the app
2. Removed all the old Adguard CA certs
3. Installed the latest 4.6 release keeping only the default settings, only installing the freshly generated CA cert for HTTPS filtering.

**BROKEN**

4. Uninstalled APP and Removed User CA Trusted Certs again.
5. Installed the latest 4.7 nightly, again keeping ONLY the default settings and installing the freshly generated CA cert. 

**BROKEN**

6. Uninstalled APP and Removed User CA Trusted Certs again.
7. I installed v4.5.17 with default settings, only installing the freshly generated CA cert.

**WORKING**

8. Imported my saved settings and all is right and working.

I have sent my logs, and a similar rundown as above, to the support email. Things that I KNOW weren't working in my short test: The Weather Channel's official app won't load/refresh and the Grammarly companion says it can't connect to the internet. When I revert to 4.5, my apps and phone work great.
[adguard_logs_4.7.5_2507_081312.zip](https://github.com/user-attachments/files/16379860/adguard_logs_4.7.5_2507_081312.zip)

**Comment by WackyWRZ** [comment]
Can confirm this issue started on my Galaxy S23+ running latest OS updates after 4.6 update. Applications act like there is no internet connection at all. This problem seems to only happen while on WiFi, switching to cellular while leaving AdGuard on appears to work fine.

Confirmed issues with the following apps (all official apps, installed from play store):

- The Weather Channel
- UPS
- FedEx
- MS Teams

**Comment by Versty** [comment]
@Gestrid @CrimsonKnight13 @wattsja @WackyWRZ 
Thank you for reporting! 
We are investigating this issue.

**Comment by wattsja** [comment]
I have submitted logs, but I can also reload / try any test versions you need.

**Comment by SyCoREAPER** [comment]
Solution from my Issue report. 


In Low Level Settings disable/uncheck IPv6 filtering.

**Comment by CrimsonKnight13** [comment]
> Solution from my Issue report. 
> 
> 
> In Low Level Settings disable/uncheck IPv6 filtering. 

This worked perfectly with 4.6. Thanks!

**Comment by wattsja** [comment]
Can confirm disabling IPV6 filtering did resolve the issue. This should help Adguard with fixing it as this is just a band-aid.

To get to the setting:

Settings > General > Advanced > Low Level >IPv6 filtering Filters IPv6 networks if an IPv6.
(it a good ways down)

**Comment by Versty** [comment]
@Gestrid @wattsja @WackyWRZ @CrimsonKnight13 @SyCoREAPER 
We have found the root cause and are currently working on the fix.

**Comment by Versty** [comment]
@Gestrid @wattsja @WackyWRZ @CrimsonKnight13 @SyCoREAPER 
AdGuard for Android 4.6.1 is available! 
Please make sure that the issue is eliminated on your devices.

**Comment by wattsja** [comment]
Adguard Nightly v 4.7.5 is confirmed working. I have gone back in and re-enabled the IPv6 filtering and tested the apps I mentioned and they are working. 
Thanks for the speedy resolution!

**Comment by Gestrid** [comment]
AdGuard v4.6.1 also works correctly. All the apps I mentioned in my initial bug report are now working correctly.

Thank you for the quick response!

**Comment by pm0u** [comment]
I am still experiencing loading issues on 4.6.1 on a local wifi network using IPv6 with IPv6 filtering enabled. Amazon app fails to load completely. Strava as well.

Disabling IPv6 filtering fixes it. This did not fix it on 4.6, however.

**Comment by SyCoREAPER** [comment]
This is back again but I don't know whats causing it this time. 

It's Android 15 only. Other devices are fine. The email client isn't being routed through adguard but if adguard is turned off it works fine.
