### ISSUE TITLE
AdGuard YouTube player turns off the phone while playing a video after a while

### ISSUE THREAD

**Issue by Kariboupseudo** [AdguardTeam/AdguardForAndroid#5406]
### Issue Details

Whenever i play videos with AdGuard YouTube player on my Samsung S23 phone (Android 14/One UI 6.1) if i do not touch the phone's screen then it will be considered idle and will be turned off by the system.

### Proposed solution

I'd like AdGuard YouTube player on Android to be able to keep the system to turn off the display while it plays something.

**Comment by TPS** [comment]
Also an option that allows the video & screen to be _manually_ turned off while ad-free streaming (e.g., music, podcast, live whatever, &c) woukd be nice.

**Comment by maxikuzmin** [comment]
@Kariboupseudo I've tested this on several devices, but the screen won't turn off. 
Could you please elaborate more detailed steps to reproduce the problem?

**Comment by maxikuzmin** [comment]
@Kariboupseudo the screen doesn't turn off because the video is playing. 
This is how the video playback logic works on YouTube app, too. This is so that you can watch videos continuously instead of tapping the screen every minute.

**Comment by Kariboupseudo** [comment]
Just verified, 2 minutes and 8 seconds into a 54m29s video, my Galaxy S23 screen did turned off playing it from Adguard youtube video player.
When  i tried on the official Youtube app it didn't turned it off it's like if the android didn't considerate the Adguard video player as a video player...
I d'ont know how to give you more precise ways to replicate as it's pretty straightforward to do...

**Comment by Kariboupseudo** [comment]
I should have add it as a bug maybe instead of a feature request i don't know but it does prevent me to use the Adguard Youtube Video Player for sure. If it's about a android settings then it could be useful to indicate it in the appliucation documentation eventually...

**Comment by maxikuzmin** [comment]
@Kariboupseudo so the screen turns off? I apologize, I misunderstood you, I thought you wanted the screen to turn off. 

But I also tested this theory on several devices and the screen did not turn off in my case. What screen time limit do you have in your system settings?

**Comment by Kariboupseudo** [comment]
@maxikuzmin Sorry my description wasn't clear enough (english isn't my native language). Well i can't find any android/OneUI setting that would explain the symptoms as i don't have any parameter for screen time limit or anything like that.
I do have a criteria for screen going in sleep mode after 2 minutes being idle so it means that the application isn't considered active by the system so it does go in sleep mode eventhough it's active and playing a video.
Like i said Youtube application doesn't have this behavior and does prevent the screen to going in sleep mode.

**Comment by Kariboupseudo** [comment]
@maxikuzmin It has always been present, in 4.5 version and before. I signaled it through support canal first and waited for a new version to come out but since it has not been corrected yet i decided to adress it using github as well.
You do not reproduce it ? Even with a galaxy device ?

**Comment by Kariboupseudo** [comment]
@maxikuzmin I only have the choice to set sleep mode to 10 minutes max in the phone parameter, i can't disable sleep mode so it can't be an effective workaround...

**Comment by maxikuzmin** [comment]
@Kariboupseudo I tested it on android 10, 13 and 14.
Xiaomi, Samsung, Pixel.
But the problem does not recur. I even tried setting different intervals of going to sleep, but still the videos in YouTube player plays uninterrupted and the screen doesn't go off.
It sounds like you may have some setting on your system that is affecting this. Have you changed any permissions for AdGuard?

**Comment by Kariboupseudo** [comment]
@maxikuzmin I don't think so, i only followed the documentation:
https://adguard.com/kb/fr/adguard-for-android/installation/
https://adguard.com/kb/fr/adguard-for-android/solving-problems/manual-certificate/
My phone isn't rooted or anything like that.
It's a SM-S9110 model with the latest updates to date.

**Comment by maxikuzmin** [comment]
@Kariboupseudo Could you please record debug logs?

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce steps, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 5406 number in the subject
specify the exact time when the issue occurred

**Comment by Kariboupseudo** [comment]
@maxikuzmin I've just sent logs to the email you mentioned, thanks for the support.

**Comment by maxikuzmin** [comment]
@Kariboupseudo I don't see your logs in the mail. Could you please resend the logs? Don't forget to include the issue number (5406) and the time when the problem recurred

**Comment by Kariboupseudo** [comment]
Sorry, it wasn't sent after all, it should be fine now.

-------- Message d'origine --------

**Comment by maxikuzmin** [comment]
@Kariboupseudo thanks, I got your logs, but those logs look like you just clicked "Export logs" in the AdGuard app. Could you please write new logs as instructed in the [instructions](https://adguardteam.github.io/KnowledgeBase/adguard-for-android/solving-problems/logcat/)?
Don't forget to include the issue number (5406) and the time when the problem recurred

**Comment by Kariboupseudo** [comment]
Hi,
Last time i did reproduce after having launched the debug mode in the developer options, it should have record it, I don't understand why it didn't sorry.
The strange thing is that i can't reproduce the bug anymore with my phone. Video can be played more than 2 minutes now. I didn't change settings but it appears to be solved... Sorry for the trouble, i'll capture and transmit logs if it does appears again.

Best regards

Kevin

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------

**Comment by maxikuzmin** [comment]
@Kariboupseudo strange, maybe there was a system problem after all. I will close issue for now. If the problem occurs again, please reopen issue
