### ISSUE TITLE
BROKEN APPs - Multiple Users Reporting, I warned you 

### ISSUE THREAD

**Issue by SyCoREAPER** [AdguardTeam/AdguardForAndroid#5408]
#5361

4.6 (and nightlies) blocks internet access to various apps like Waze, banking, and countless other apps. 

Various Issues already in the queue reporting the exact same thing. 

I turned off EVERYTHING except the main AdGuard Switch. Still cannot connect. 

**One observation** 
This only seems to happen on WiFi

**Comment by SyCoREAPER** [comment]
@maxikuzmin

**Comment by maxikuzmin** [comment]
@SyCoREAPER unfortunately, without logs it is difficult for us to understand such problems. We are already looking into this issue. Are you also experiencing long loading or not loading data on reddit, twitch, the weather channel?
Also if you do manage to record logs for this problem, please send logs too

**Comment by SyCoREAPER** [comment]
Don't use any of those. However the Playstore is also broken. It will either get stuck at trying to download or downloading. 

What do you need, very specifically, and where do you want it sent?

Some logs I will modify for privacy reasons but leave the entailing data intact for example if i see my bank name, I'm going to edit it out and just put bank

**Comment by maxikuzmin** [comment]
@SyCoREAPER there seems to be a problem with ipv6. Please try to disable IPv6 filtering in low level settings and check applications

**Comment by Gunner82** [comment]
> @SyCoREAPER there seems to be a problem with ipv6. Please try to disable IPv6 filtering in low level settings and check applications
Sorry to highjack, but this did work. Does this affect the quality of ad blocking in any way?

**Comment by SyCoREAPER** [comment]
> @SyCoREAPER there seems to be a problem with ipv6. Please try to disable IPv6 filtering in low level settings and check applications

That is the fix. 

The question is why. It doesn't affect me as I'm not using IPv6 but it wasn't causing an issue before. 

On a side note, now that there is finally a bandaid, I can hop back on Nightlies.

**Comment by nicoleahmed** [comment]
Thank you the ipv6 fix worked for me. Many of my apps weren't functioning and I was about to downgrade to 4.5

This fix has returned all the apps back to normal.havent seen issues with filtering yet

**Comment by maxikuzmin** [comment]
@SyCoREAPER @nicoleahmed @Gunner82 please update to version 4.6.1 and check if the problem recurs

**Comment by gork7777** [comment]
@maxikuzmin Hey, looks fixed and working fine for me. I checked PlayStore, Instagram, WhatsApp and banking apps.

**Comment by pm0u** [comment]
Disabling IPv6 filtering on 4.6 did not resolve for me. Updating to 4.6.1 with IPv6 filtering disabled worked as expected.

I then enabled IPv6 filtering, disconnected all networks, connected to cell network, enabled wifi & connected and everything worked as expected across both connection types.

**Comment by SyCoREAPER** [comment]
> ~Disabling IPv6 filtering on 4.6 did not resolve for me. Updating to 4.6.1 with IPv6 filtering disabled worked as expected.~
> 
> ~I then enabled IPv6 filtering, disconnected all networks, connected to cell network, enabled wifi & connected and everything worked as expected across both connection types. Local network uses IPv4 - unsure of the cell network (Verizon if that matters)~
> 
> Added a comment on #5405 - this did not in fact fix the issue. I still have to disable IPv6 filtering with app version 4.6.1

You may have a different issue. May want to submit whateverogs they need to investigate. You're the only one to report it not working.
