### ISSUE TITLE
Cannot navigate to the relevant sections in the updates section

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#5411]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

V4.7 nightly 5

### Environment

- OS version: Android 8.1.0
- Device: Samsung J7 Prime

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Go to `Updates` section.
2. Click on the `DNS filters` and `Content blocker filters`. You'll see nothing happen and not going to the relevant section.

### Expected Behavior

When you click on the `DNS filters` and `Content blocker filters`, it should be go to the relevant sections. I think it should go to the following screens:

<details><summary>For DNS filters:</summary>

![Bug1](https://github.com/user-attachments/assets/58343747-3511-468a-a526-d6f5cf12ee9e)
</details>

<details><summary>For Content blocker filters:</summary>

![Bug2](https://github.com/user-attachments/assets/8721e6dc-fc27-4bca-9bd1-99c3ea165275)
</details>

### Actual Behavior

When you click on the `DNS filters` and `Content blocker filters`, nothing happens and not going to the relevant sections. When you click on the ones I have marked in green, you go to the relevant sections. When you click on the ones I have marked in red, you cannot go to the relevant sections.

### Screenshots

<details><summary>Screenshot 1</summary>

![Bug](https://github.com/user-attachments/assets/47ccc2e3-70c2-4b47-be80-bd17520bddcd)
</details>

**Comment by maxikuzmin** [comment]
@gork7777 hello!
Updates screen logic:
After updating filters you see the number of updated filters.
If you tap on the number of filters (for example Updated: 1) - you can see which filters have been updated. If you click again on the list of updated filters - the list is minimized.

This section does not provide redirect to the section screens of those filters that have been updated

**Comment by gork7777** [comment]
@maxikuzmin Hi! Thank you for explaining, I thought it was a bug.
