### ISSUE TITLE
Current Stable Release is not consistent with app Version. 

### ISSUE THREAD

**Issue by SyCoREAPER** [AdguardTeam/AdguardForAndroid#5413]
Current Stable is 4.6.1 however the manifest for app installer is 4.6.61 and shows as 4.6.61 once installed.

**Comment by Versty** [comment]
@SyCoREAPER That's correct. 4.6.1 is the version number and 4.6.61 is the technical version.

**Comment by SyCoREAPER** [comment]
That is an unusual approach (but it's your app to do as you see fit). 

I know this is a me problem and only very few would be affected but my updater app (and I tried various) sees the installed version is different from the GitHub Release and either shows conflicts or needing to update but since it's the same version, updating results in it still saying it needs to be updated because the versions still mismatch. 


I'm guessing there's no way you can just make the two match moving forward (ex 4.6.1) and inside the app have the tech-build number in long or short form?;
Build 4.6.1
Tech Build 4.6.16 or just 16


 Alternatively, the technical build being the release number on github would fix that too. 


I don't expect the answer to be yes to either of these but it can't hurt to ask.

**Comment by Versty** [comment]
@SyCoREAPER We use [semantic versioning](https://semver.org/#semantic-versioning-200) approach. 
Due to 3 separate update channels (nightly, beta, release) it is not currently possible to sync the version number with the technical version of the build.

**Comment by Versty** [comment]
@SyCoREAPER Does your updater app rely on the release version title on GitHub or the version tag?

**Comment by SyCoREAPER** [comment]
> @SyCoREAPER Does your updater app rely on the release version title on GitHub or the version tag? 

To work fully automated, yes, the build/version number on the releases page has to match the installed version number which in this case it's 3.6.1 vs 3.6.16 which it thinks is out of date and infinitely tries to update.

**Comment by Versty** [comment]
@SyCoREAPER Seems like the best solution in this case is to disable the Obtainiun updater for AdGuard and use AdGuard notifications to find out when a new version is available.
