### ISSUE TITLE
TCP keepalive for outgoing sockets screen doesn't scroll

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardForAndroid#5415]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

V4.7 nightly 5

### Environment

- OS version: Android 8.1.0
- Device: Samsung J7 Prime

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Go to the `TCP keepalive for outgoing sockets` setting from Advanced settings.
2. Scroll down and you will see that it doesn't fit on the screen.

### Expected Behavior

This option should be fit on the screen when you scroll down.

### Actual Behavior

When you go to this setting and scroll down, it doesn't fit on the screen for Turkish language. I haven't tried other languages, but probably the same problem in other languages.

### Screenshots

<details><summary>Screenshot 1</summary>

![Bug1](https://github.com/user-attachments/assets/db535762-d693-4078-8d8d-f7f9a6ecac5a)
</details>

**Comment by Versty** [comment]
@gork7777 This issue reproduces on our side as well, will be fixed.
