### ISSUE TITLE
YouTube плеер AdGuard

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5417]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Как известно в России YouTube имеет в данный момент проблемы с про грузкой видео, но если использовать VPN это делает возможность просмотра видео в более комфортных условиях.

Вот тут у Вас написано

![2024-07-31_12-19-37](https://github.com/user-attachments/assets/b58d2736-3c7e-4aa9-af6d-a2ca17a5732c)

Отсюда вопрос, где находятся сервера для воспроизведения видео? Так как зарубежные сервера дают нормальную возможность просмотра видео, а сервера в России нет.

**Comment by Versty** [comment]
@Cursone Добрый день! 
При использовании функции AdGuard Player в приложении AdGuard for Android видео по-прежнему грузятся с ближайших серверов YouTube, поэтому скорость загрузки никак не изменится.
