### ISSUE TITLE
com.vmn.android.comedycentral doesn't work with HTTPs filtering enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#542]
https://play.google.com/store/apps/details?id=com.vmn.android.comedycentral

![image](https://cloud.githubusercontent.com/assets/15856304/15092419/e130e0b8-1471-11e6-9cc0-ff6f435e3739.png)

Works fine once HTTPs is disabled.

**Comment by Revertron** [comment]
I'm unable to repeat this error. We will need HAR-file to determine the cause of problem.
It can be done by enabling har in low-level settings. (don't forget to disable it afterwards)

**Comment by ameshkov** [comment]
I am pretty sure log file should be enough.

**Comment by evgeniy-ADG** [comment]
Попросил

**Comment by Revertron** [comment]
@evgeniy-ADG Ну что там от юзера?

**Comment by ameshkov** [comment]
Reopen if new reports appear
