### ISSUE TITLE
Adguard player YouTube 

### ISSUE THREAD

**Issue by Wadi3002** [AdguardTeam/AdguardForAndroid#5421]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

is there a why to bypass YouTube's age verification . 
![Screenshot_2024-08-02-20-22-34-757_com adguard android-edit](https://github.com/user-attachments/assets/b56c42fc-589d-49b3-8e64-f570796539b8)
![Screenshot_2024-08-02-20-24-19-654_com.adguard.android.jpg](https://github.com/user-attachments/assets/ec54d145-8980-4f97-89b6-f758be75359a)

**Comment by Wadi3002** [comment]
![Screenshot_2024-08-02-20-24-19-654_com adguard android](https://github.com/user-attachments/assets/d011d3c7-4228-46b5-a982-4310abcf8922)

**Comment by maxikuzmin** [comment]
@Wadi3002 I don't think so. Age verification - not ads, it's a YouTube feature

**Comment by Wadi3002** [comment]
> @Wadi3002 I don't think so. Age verification - not ads, it's a YouTube feature

if I can't watch it with the adguard player that means I need to watch it on YouTube which will be with ads !!!

**Comment by maxikuzmin** [comment]
@Wadi3002 but there will be an age verification on YouTube as well
