### ISSUE TITLE
Incorrect translation of Fanboy's Annoyance List description

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5423]
### Issue Details

Некорректно подаваемая информация пользователю и введение его в заблуждение

![Screenshot_20240807_191148_com adguard android](https://github.com/user-attachments/assets/43de4638-babd-4e1c-9061-3d6a148b5dad)

### Proposed solution

У Вас написано - **Включает списки cookie-файлов Fanboy's Social Blocking и EasyList.**

А должно быть - **Включает списки EasyList Cookie List и Fanboy's Social Blocking List.**

Если Вы же не в курсе какие фильтры в ходят в **Fanboy's Annoyance List**, то информацию про это можете почитать тут - https://easylist.to/

Фильтра **cookie-файлов Fanboy's Social Blocking** не существует, а фильтр **EasyList** вообще не относится к фильтру **Fanboy's Annoyance List** ни каким боком.

Пишите оригинальные названия фильтров, а не пытайтесь их названия переводить на русский.

**Comment by Versty** [comment]
@Cursone Добрый день! 
Спасибо что сообщили о проблеме, мы исправим перевод.
