### ISSUE TITLE
AdGuard 4.6+ apk fails to be installed on Xiaomi (MIUI and HyperOS) devices

### ISSUE THREAD

**Issue by jax79sg** [AdguardTeam/AdguardForAndroid#5425]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6 and above

### Environment

- OS version: Xiaomi HyperOS 1.0.6.0.UMNMIXM
- Android version: 14 UKQ1.230804.001
- Device: POCO F5 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Which DNS server do you use?

Google DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Download adguard apk from github release page
2. Run adguard.apk, allow the permissions
3. Click update

### Expected Behavior

Adguard installed without hassles

### Actual Behavior

An error occured as in screenshot. The software cannot be installed.

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_2024-08-09-15-14-57-204_com miui bugreport](https://github.com/user-attachments/assets/8b271e61-5209-443d-994e-b7a7c5e99238)
</details>

### Additional Information

All versions of 4.6 and above are effected.

**Comment by Versty** [comment]
@jax79sg Thank you for reporting! 
If you uninstall AdGuard first, and then try installing the latest version, does the problem persist?

**Comment by jax79sg** [comment]
That works. Thanks!! 

    On Friday, 9 August 2024 at 07:30:24 pm SGT, Diana ***@***.***> wrote:  
 
 


@jax79sg Thank you for reporting!
If you uninstall AdGuard first, and then try installing the latest version, does the problem persist?

**Comment by jax79sg** [comment]
Hi. I've to uninstall the existing installation, and reinstall cleanly.

**Comment by Versty** [comment]
@jax79sg Did recent AdGuard updates or installs went smoothly on your device?

**Comment by jax79sg** [comment]
Yeah seems to work 

    On Monday, 18 November 2024 at 05:07:35 pm SGT, Diana ***@***.***> wrote:  
 
 


@jax79sg Did recent AdGuard updates or installs went smoothly on your device?
