### ISSUE TITLE
Almost all apps are no longer logged as filtered

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#5426]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7n6 updated to 4.7n7 → n9

### Environment

- OS version: Android 12 stock
- Device: 1+ N200 5g

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Legitimate URL Shortener, Peter Lowe's Blocklist

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, I don't care about cookies, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter, Polish Anti-Annoying Special Supplement, Polish GDPR-Cookies Filters, RU AdList - Counters

### Other

AdGuard Experimental filter

### Which DNS server do you use?

Open DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Protect against DPI

### Issue Details

Steps to reproduce:
1. Update to AGa v4.7n7 to n9
2. Browse via aEdge v127.0.2651.90 for some time
3. Check Assistant or Recent Activity

### Expected Behavior

Browser filtering should be logged

### Actual Behavior

No browser filtering logged, only DNS filtering

### Screenshots
<details><summary>The test page shows everything's as expected, so I'm hoping this is just a log glitch.</summary>

![AdGuard test page](https://github.com/user-attachments/assets/726816e9-2ce1-476b-8490-98ce366f8ebf)

</details>

<details><summary>The cosmetic filter block page is active.</summary>

![AG block page.16.png](https://github.com/user-attachments/assets/e24b1c3a-e4dc-417a-8adb-bc360ad05a49)

</details>

### Additional Information

Previous versions would log as filtering Edge.

**Comment by AdamWr** [comment]
I have the same issue but in my case I don't see requests from any browser Chrome/Edge/Firefox (it looks like that only DNS requests are visible in "Recent activity", but ad filtering works correctly).

**Comment by vonDubenshire** [comment]
I finally got fed up with this and came to see if it had been reported yet since it started a couple of Nightly updates ago, I guess .9

I'm on 4.7.11 and I haven't seen any browser appear in the list of apps inside the AdGuard Assistant since 4.7.9 as @TPS noted.  

@AdamWr yep same issue here. 

I'm attaching current screenshot. It doesn't show any browsing I did to get here. 
![Screenshot_20240810-053100](https://github.com/user-attachments/assets/2fcde544-3074-47f4-973a-a8d433fd3b79)
![Screenshot_20240810-053102](https://github.com/user-attachments/assets/8c50014c-c149-4fa5-9a23-9a8622864010)

**Comment by Rtizer-9** [comment]
I talked to the developer and Cosmetic Filtering IS applied which you can check in any browser or any app which is being filtered; it's just not shown in the filtering log due to a HTTP events not displaying in the filtering log.

**Comment by Vstory** [comment]
Not only the browser, but all application filters are not displayed, only DNS filtering requests are displayed.

**Comment by TPS** [comment]
Oddly, I still see _very_ few apps having some logs, such as some UDP from a comm app, or rarely element removal even from Edge, but, like others here, the sheer quantity of these app logs is probably ~100× less.

**Comment by ESurina** [comment]
We will fix this in future versions!

**Comment by TPS** [comment]
> Join tg group and you'll get answers to all of your queries from the dev team itself.

@Rtizer-9 Link?

**Comment by TPS** [comment]
This looks fixed in v4.7n12.  Y'all concur?

**Comment by smexyy** [comment]
> This looks fixed in v4.7n12. Y'all concur?

I think partially fixed.

**Comment by smexyy** [comment]
> > I think partially fixed.
> 
> What's yet missing?

It filter browser for 3 or 4 minutes, then only dns logs only. I cannot see https,tcp filtering for the browser

**Comment by TPS** [comment]
> It filter browser for 3 or 4 minutes, then only dns logs only. I cannot see https,tcp filtering for the browser

I don't see this at all, but everything WFM as before this broke.

@smexyy What's your environment (more specifically, the answers to the template questions from 1st post here)?

**Comment by smexyy** [comment]
> > It filter browser for 3 or 4 minutes, then only dns logs only. I cannot see https,tcp filtering for the browser
> 
> I don't see this at all, but everything WFM as before this broke.
> 
> @smexyy What's your environment (more specifically, the answers to the template questions from 1st post h

> > It filter browser for 3 or 4 minutes, then only dns logs only. I cannot see https,tcp filtering for the browser
> 
> I don't see this at all, but everything WFM as before this broke.
> 
> @smexyy What's your environment (more specifically, the answers to the template questions from 1st post here)?

I tested the latest release, and it seems to be running smoothly.
