### ISSUE TITLE
Android. User data is huge (38 GB)

### ISSUE THREAD

**Issue by vadimplSPb** [AdguardTeam/AdguardForAndroid#5430]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.61

### Environment

- OS version: MIUI Global 14.0.3.0 (SJWINXM)
- Android: 12 SKQ1.211019.001
- Device: Redmi Note 9 Pro
- Model: M2003J6A1G

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Russian filter

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Opened in phone "About phone", had seen full internal memory of device.
2. Info app "Aguard" - see savescreens
![Screenshot_2024-08-11-10-10-57-249-edit_com miui securitycenter](https://github.com/user-attachments/assets/e94183c8-4b83-41ba-bb76-5c4820f23663)
![Screenshot_2024-08-11-10-11-22-026-edit_com miui securitycenter](https://github.com/user-attachments/assets/b2ab26a5-0de6-4f00-a542-7b52028e9a01)

3. User data - **36GB**. Holy shit

### Actual Behavior

-

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@vadimplSPb Hi! 
Sounds like a known bug https://github.com/AdguardTeam/AdguardForAndroid/issues/5125, which has already been fixed. 
Clearing the application data and cache in system settings should help.

**Comment by vadimplSPb** [comment]
> Clearing

Done. Monitoring further

**Comment by Versty** [comment]
@vadimplSPb Has the issue been resolved?

**Comment by vadimplSPb** [comment]
> @vadimplSPb Has the issue been resolved?

A week after cleaning:
Total: 186 MB
User data: 81.35 MB

I think, it has been resolved
