### ISSUE TITLE
Parts of the UI displayed in system language instead of the language set in settings.

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdguardForAndroid#5436]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.2

### Environment

- OS version: Android 14
- Device: vivo x100 pro

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Please see the video
https://i.imgur.com/dy7rsyx.mp4

Language set in AdGuard app:
English

System language:
Chinese

AdGuard displays some parts of its UI in Chinese instead of English.

This seems to happen if I don't open the app for a while (ie. 2 days), then open the app and this happens.
(I usually open the app every day since AdGuard cannot update the filters automatically for some reason even though I have disabled battery optimization, set auto-start, and locked the app in app switcher.)

If I close the app and reopen, then all UI is displayed in English properly again. Then after a while the bug happens again.

I have no way to reliably recreate the bug.

not sure if it's related to https://github.com/AdguardTeam/AdguardForAndroid/issues/5168

### Actual Behavior

Parts of UI displayed in wrong language.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention! We will fix it in future versions.
