### ISSUE TITLE
Is http/3 supported?

### ISSUE THREAD

**Issue by 7FoQc0oBicfT** [AdguardTeam/AdguardForAndroid#5439]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I checked with cloudflare's http/3 test site.

https://cloudflare-quic.com/

adguard off => http/3

adguard on => http/2

Browser
samsung s23 android14 chrome

**Comment by zzebrum** [comment]
@7FoQc0oBicfT yes, it is. [Not](https://github.com/AdguardTeam/CoreLibs/issues/487#issuecomment-1702783835) in Chrome browser though. But I can confirm [it is working on FF](https://github.com/AdguardTeam/CoreLibs/issues/487#issuecomment-1741823691).

**Comment by 7FoQc0oBicfT** [comment]
I found that my adguard is working fine. Thank you.
