### ISSUE TITLE
Vpn Service not working bug

### ISSUE THREAD

**Issue by Cawca-Fr** [AdguardTeam/AdguardForAndroid#5445]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7.19

### Environment

- OS version: Android 14
- Device: Samsung S23 FE

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard French filter, AdGuard Turkish filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Open Adguard
2. Open statistics section or enable vpn
3.

### Expected Behavior

The vpn service should work without blocking the internet traffic and without crashing. Statistics section should show the statistics but app don't responds, same for the statistics shown in the main page. 

### Actual Behavior

The vpn service works for 1 minute before crashing and while working it's blocking the internet traffic, it's not related to blocked domains. The statistics section not working it gets stuck in the loading animation, same for the statistics shown on the main page just under the switch for enabling the protection. 

### Screenshots

<details><summary>Screenshot 1</summary>

](
![Screenshot_20240829_115526_AdGuard](https://github.com/user-attachments/assets/7d57db84-6860-461f-9612-3ab5b8ab6d17)
![Screenshot_20240829_115531_AdGuard](https://github.com/user-attachments/assets/c7e78c45-cdf0-4c0f-b92a-3853c37103dd))

</details>

### Additional Information

This issue didn't happen after an update to the app

**Comment by ESurina** [comment]
Since the problem does not recur, I will close the issue. If the problem occurs again, please re-open the issue.
