### ISSUE TITLE
Material you 3 Design update

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#5450]
### Issue Details

Hi. I love your app, but there's a problem with the ui/ux. The ui/ux is outdated

### Proposed solution

https://developer.android.com/develop/ui/compose/designsystems/material3

**Comment by Versty** [comment]
@jujubeja Hi! 
AdGuard applications are constructed with components from a unique custom library created by our designers. This library is well suited for both Android and iOS devices, so we currently have no plans to use Material 3.
