### ISSUE TITLE
Exclude browser apps from HTTPS filtering website allowlist

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardForAndroid#5452]
### Issue Details

If we access domains included in HTTPS filtering website allowlist from a browser, in order to avoid in-app ads and annoyances that can’t be blocked there, HTTPS encrypted elements are also allowed in the browser, although they are blacklisted and easily blockable. Furthermore, HTTPS filtering website allowlist is unsorted without searching capabilities (cf. #5289), not allowing us to find and disable exclusions that cause in-browser problems. On the other hand, browser extensions don’t present this issue.

### Proposed solution

Exclude browser apps that can be filtered by AdGuard (like Google Chrome, Microsoft Edge, Mozilla Firefox etc.) from HTTPS filtering website allowlist.

### Alternative solution

If this isn’t technically feasible, automatically enable relevant exclusions only if the respective app is installed.

**Comment by ESurina** [comment]
What issue are you talking about?

> On the other hand, browser extensions don’t present this issue.

That is, you want ads to be blocked in browsers on those sites that are listed in the HTTPS filtering website allowlist?

**Comment by DimitrisKalaboukas** [comment]
@ESurina Yes, exactly. Browser extensions don’t need to have HTTPS filtering allowlists, in other words they filter HTTPS traffic everywhere.

**Comment by ESurina** [comment]
What we could do is provide the ability to configure applications in HTTPS exception rules. You would be able to specify which apps the rule applies to.
For instance:
`example.org^$app=com.google.chrome` - applies exclusion to Chrome only. (This rule is already supported)
`example.org^$app=~com.google.chrome` - applies exclusion to all apps except for Chrome.
We will also likely add searching capabilities.
Are you satisfied with this solution?

**Comment by DimitrisKalaboukas** [comment]
@ESurina I would be, if you could provide a respective setting to exclude supported browser apps by automatically creating such exception rules for all websites in the HTTPS filtering allowlist, because it is very difficult for the user to do so manually.

**Comment by ESurina** [comment]
Unfortunately, we will not be doing this feature, as there are certain reasons why we added websites to the allowlist, which is applicable to browsers.
