### ISSUE TITLE
Youtube app error

### ISSUE THREAD

**Issue by lanevosbx** [AdguardTeam/AdguardForAndroid#5453]
### AdGuard version

4.6.81

### Environment

- OS version: Android 14

### Issue Details

Steps to reproduce:
When I open youtube app to adguard, this error happen "Failed to open the link in the player."

### Screenshots

![Screenshot_20240904_170641_AdGuard](https://github.com/user-attachments/assets/848f03d4-e9e5-4a56-86b6-593f59981dd0)

**Comment by maxikuzmin** [comment]
@lanevosbx it depends on the type of video, unfortunately you can't influence it. Please check if this is repeated with other videos?

**Comment by maxikuzmin** [comment]
@lanevosbx any news?

**Comment by maxikuzmin** [comment]
@lanevosbx glad to hear that. But again, often this error can appear depending on the type of video, unfortunately there is nothing you can do about it
