### ISSUE TITLE
Can't install CA certificate from SD card

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardForAndroid#5454]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.2

### Environment

- OS version: Android 14
- Device: Galaxy A14 5G

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Try to install CA certificate by following the steps in the app
2. When Adguard ask to choose location for certificate, choose SD card
3. Process is done without any message and then you find that https filtering it still off

### Actual Behavior

CA certificate should have installed but it didn't. It can be successfully installed from internal storage. And if something went wrong there when trying to install certificate from SD card, no error message at all.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@andris86 Could you record a screencast with problematic CA installation and sent it to our email qa@adguard.com? 
Please mention the `android` keyword and the `5454` issue number in the subject.

**Comment by Versty** [comment]
@andris86 Unfortunately, the issue doesn't reproduce on our side, so we would like to take a look at the video from your device.

**Comment by Versty** [comment]
@andris86 Essentially, you have two options: reinstall the AdGuard app or remove the certificate and install a new one.

**Comment by Versty** [comment]
@andris86 The linked comment is answered. 

If you manage to reproduce the problem with certificate installation from CD card, please reopen this issue.
