### ISSUE TITLE
Can you generate a dns address for adguard

### ISSUE THREAD

**Issue by qwerzxcva** [AdguardTeam/AdguardForAndroid#5455]
### Issue Details

When I use proxy software to coexist with adguard, adguard takes my Settings dns, The proxy software will also go through dns, I hope to solve this problem.

### Proposed solution

Since the dns of the proxy software can be customized, I decided to have adguard generate a new dns address. Then I fill it in to remote dns and local dns so that adguard can take over the dns of the proxy software. Can go less a layer of dns, this is what I can think of. My version is the latest version of nightly.

**Comment by ESurina** [comment]
Please specify in detail the steps of how and what you set up. This will help us interpret your request correctly.

**Comment by ESurina** [comment]
@qwerzxcva Please answer the question above.
