### ISSUE TITLE
How to use proxies in AdGuard? 

### ISSUE THREAD

**Issue by KirbyFan102** [AdguardTeam/AdguardForAndroid#5456]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I am trying to run an app through a proxy. Problem is, this is my first time doing something like this, so I'm not sure of all the steps.

I picked a random proxy server from an online list and wrote in the necessary information such as type and port where AdGuard asked for it, but it didn't seem to be enough. AdGuard simply said "unable to connect through TCP". I tried multiple server addresses with the same result. I'm not sure what else is necessary.

**Comment by ESurina** [comment]
Hello, you could use this [manual](https://adguard.com/kb/adguard-for-android/solving-problems/outbound-proxy/).
If you still have questions, then ask them.

**Comment by KirbyFan102** [comment]
I found a working proxy. But now I want to route certain addresses through the proxy, and I only find the option to route apps, which doesn't seem to be enough. Is there an option for using a proxy for websites and other such addresses anywhere in the settings?

**Comment by ESurina** [comment]
There is no option in our application to select the websites for which the proxy should work.

**Comment by KirbyFan102** [comment]
Well, then that's a problem, because I'm trying to route traffic for the X/Twitter app through the proxy using your app and it's not working.
