### ISSUE TITLE
Bleach: Brave Souls app unable to be whitelisted

### ISSUE THREAD

**Issue by KirbyFan102** [AdguardTeam/AdguardForAndroid#5457]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

- OS version: Android 10
- Device: Samsung Galaxy M31

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances, Dandelion Sprout's Annoyances List

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Login to Bleach Brave Souls app (BBS for short) with AdGuard protection, having made sure to previously exclude it from AdGuard protection. 
2. Move to the 'ad' section and attempt to watch an ad. All attempts will fail. 
3. Exit the app and disable AdGuard protection. 
4. Attempt to watch ad in-game again. It is necessary to wait for the ads to load, but eventually you will manage to watch one, unlike the first scenario. 

### Expected Behavior

BBS allowing me to watch ads even with AdGuard enabled. I have tried disabling the "route traffic through AdGuard option", white listing the app, and doing both at the same time. 

### Actual Behavior

BBS does not load ads with AdGuard enabled despite the above steps. I should note that other games, such as Sonic Forces: Speed Battle, work as expected when this is done, but not BBS. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@KirbyFan102 please specify the path of the advertisement section in the BBS application.
Please try to add the `com.klab.bleach` rule from a new line to the IPv4 ranges excluded from filtering list (Settings tab -> General -> Advanced -> Low-level settings)

**Comment by KirbyFan102** [comment]
@maxikuzmin, it's in the main menu under 'shop' and then 'ads/items'. You have to wait a bit after logging in for the ads to become available, though

Also, I tried to do that, but it just said "invalid address"

**Comment by maxikuzmin** [comment]
@KirbyFan102 I apologize for the long wait. I found out that Basic protection is affecting ads in the Bleach app. As a solution: Go to App management -&gt; Bleach -&gt; Route traffic - Off switch
Try this and let me know the result. It worked for me

**Comment by KirbyFan102** [comment]
Sorry for making you wait as well, for some reason I was not receiving GitHub email notifications until recently. Unfortunately, turning off that option doesn't work, it was one of the first things I tried. I just tried it out again just to make sure.

**Comment by maxikuzmin** [comment]
@KirbyFan102 any news?

**Comment by KirbyFan102** [comment]
> @KirbyFan102 any news?

Not yet, I haven't had the chance to try out those solutions, but I'll try to update you later today

**Comment by KirbyFan102** [comment]
> @KirbyFan102 strange why it worked in my case. Have you also tried disabling "Route traffic" completely? Also, if disabling "Route traffic" doesn't work for you, try disabling Basic protection (Protection tab -> Ad blocking -> Basic protection)

@maxikuzmin, Turning off basic protection doesn't work either. In fact, not even turning off ad blocking _entirely_ works. The only thing that has worked so far is turning off protection completely, which of course, is unacceptable. I want to be able to leave AdGuard on indefinitely.

As for route traffic, I don't know where I would go to "disable it completely", as I have already toggled it off for the app, and I can't find any other such option elsewhere (having a search function for the settings would be good).

**Comment by maxikuzmin** [comment]
@KirbyFan102 please clarify, did you also try disabling "Filter traffic" for the Bleach: Brave Souls app?
App management -> Bleach -> Filter traffic - Off switch

**Comment by KirbyFan102** [comment]
> @KirbyFan102 please clarify, did you also try disabling "Filter traffic" for the Bleach: Brave Souls app? App management -> Bleach -> Filter traffic - Off switch

@maxikuzmin, yes, though technically I should clarify that that option was never enabled to begin with. It is only available for users of the full version of AdGuard, which I do not have. As is the Filter HTTPS traffic option for the app.

**Comment by maxikuzmin** [comment]
@KirbyFan102 okay, we need some more time

**Comment by maxikuzmin** [comment]
@KirbyFan102 please try disabling all protection blocks (Ad blocking, Tracking protection, Annoyance blocking, DNS protection) on the Home tab and enable protection with the main switch, then try again with the Bleach app. 
Will the problem still recur? If the problem stops recurring, try turning on each protection block in turn, then check the app. Before each test, close Bleach completely with Force stop and reopen it again

**Comment by KirbyFan102** [comment]
@maxikuzmin, I did as you requested. The problem did not reoccur with the protection blocks disabled. I enabled Ad blocking, then annoyance blocking (which also seemed to enable tracking protection automatically, even though that's supposed to be premium only. Odd), which did not seem to cause any problems. The ads ran just fine and I was able to get my rewards.

It was only when I enabled DNS protection that the problem recurred.

**Comment by maxikuzmin** [comment]
@KirbyFan102 great, we seem to have found a potential cause. Please try enabling DNS protection and disabling DNS filter, then check Bleach again. Will the ads show?

**Comment by maxikuzmin** [comment]
@KirbyFan102 by the way, it would be nice to check Recent activity and see what requests are blocked. 
Also, disable all protection blocks, enable only DNS protection and check what requests are blocked. Open the details of the requests and send them to qa@adguard.com or just attach here. This way we will be able to understand what exactly is blocking the display of ads

**Comment by maxikuzmin** [comment]
@KirbyFan102 also clarify, are you using Automatic DNS and Routing mode - Local VPN?

**Comment by KirbyFan102** [comment]
@maxikuzmin yes, I am using Automatic DNS and Local VPN. I have just logged in to the app with the DNS filters disabled and could confirm that the ads showed normally.

How do I send the recent requests to you? Taking screenshots?

**Comment by maxikuzmin** [comment]
@KirbyFan102 actually I don't think it's necessary anymore, I see blocked DNS filter requests on my device. Globally, packet exclusion should help in this case, we'll look into it. As a temporary solution you can go to Recent activity, and allow blocked DNS filter requests for Bleach

**Comment by KirbyFan102** [comment]
@maxikuzmin, I tried going to recent activity, but nothing shows up there. I'm not sure how to allow blocked DNS filter requests here. 

![Screenshot_20241115-154516_AdGuard](https://github.com/user-attachments/assets/1534f84f-9eb7-47ad-8d91-5fd7402d080f)
