### ISSUE TITLE
4.6.3 APK in GitHub release is invalid

### ISSUE THREAD

**Issue by atommarvel** [AdguardTeam/AdguardForAndroid#5459]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.3

### Environment

- OS version: 14
- Device: pixel 8a

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Go to 4.6.3 GitHub release
2. Download the APK from the assets section (not from the release channel link)
3. Try to install the APK

### Expected Behavior

App updates / installs

### Actual Behavior

Get a "There was a problem parsing the package" system dialog.

### Screenshots

<details><summary>Screenshot of the different APK sizes</summary>

![Screenshot_20240910-101351](https://github.com/user-attachments/assets/f2f491fd-50e8-4486-ab2c-588ed2519997)

</details>

<details><summary>Screenshot of being unable to install the package</summary>

![Screenshot_20240910-102443](https://github.com/user-attachments/assets/047bee93-0b4e-46f0-ac86-5436c4b7ec02)

</details>

### Additional Information

Please continue to keep uploading the APK to release assets. It allows me to use Obtanium to manage updates: https://github.com/ImranR98/Obtainium

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention. We fixed it!
