### ISSUE TITLE
Angry Birds Friends - broken by HTTPS filtering(fails to start)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#546]
> https://play.google.com/store/apps/details?id=com.rovio.angrybirdsfriends&hl=en
> 
> При входе в игру и нажатии на Play, выходит сообщение - Check your internet connection
> Отключение всех фильтров не помогает, помогает отключение защиты
> 
> логи тут: RAQ-512-85178

https://github.com/AdguardTeam/ExperimentalFilter/issues/2094

**Comment by Revertron** [comment]
This shit doesn't work without Adguard. Beg Rovio to fix it.
