### ISSUE TITLE
Higher battery consumption since v4.6 ( NOT fixed yet ! )

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/AdguardForAndroid#5460]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.6.x

### Environment

- OS version: OneUI 6.1
- Device: Samsung S24, Samsung A25

### HTTPS filtering

- [x] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard German filter

### Other

AdGuard DNS filter

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

DNS-over-TLS

### Issue Details

Steps to reproduce:
1. Install v.4.6.x
2. wait a llittle and check battery drain with battery tools like GSAM, Samsung Battery Tracker
3. Adgaurd is top of the list

### Expected Behavior

When updating to v4.6 i expect same behaviour as with v4.5

### Actual Behavior

High battery drain

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Since the first version 4.6 I have noticed an increase in battery consumption.
Even the newer versions do not solve this problem. Only a downgrade to v4.5 helps me.
On Reddit you can read about some people who have the same problem.
I have this with a Samsung Galaxy S24 and Samsung Galaxy A25

**Comment by DBotThePony** [comment]
Don't know about 4.5, but im on 4.6 and was experiencing high battery drain during stand-by, disabling adguard drastically improved battery life while smartphone is on stand-by.

**Comment by TheWrathRF** [comment]
+1 having the same draining issue as well

**Comment by derKief** [comment]
@DBotThePony  and @TheWrathRF  what device are you using ?

**Comment by TheWrathRF** [comment]
> @DBotThePony and @TheWrathRF what device are you using ?

Using Poco X6 Pro. %20 of battery draining caused by Adguard.

**Comment by DBotThePony** [comment]
> what device are you using ?

Note 9 Pro

**Comment by Versty** [comment]
@derKief Thank you for reporting! 

@TheWrathRF @DBotThePony Could you provide a screenshot of `Battery usage` screen from AdGuard application on your device?  

_Note: Battery usage screen is located in Statistics tab._

**Comment by DBotThePony** [comment]
That's the catch - it doesn't report usage as originating from adguard itself.

**Comment by Versty** [comment]
@DBotThePony Can this drain be visible on the battery usage screen in the system settings? 

If screenshots contain any sensitive data, please sent it to our email qa@adguard.com, mention the `[android]` keyword and `5460` number in the subject line.

**Comment by 0xrxL** [comment]
Last nightly installed today 🫠

![Screenshot_20241008_002712_Device care](https://github.com/user-attachments/assets/e499a615-9711-440d-a3b7-499e514c02fd)

**Comment by 0xrxL** [comment]
3 hours of full CPU usage...really weird

![Screenshot_20241008_002850_Device care](https://github.com/user-attachments/assets/4b651d68-0e25-43f7-9c12-df247436b70b)

**Comment by 0xrxL** [comment]
@derKief @DBotThePony 

I downgraded to [this version](https://www.apkmirror.com/apk/adguard-software-limited/adguard/adguard-4-7-9-release/), install it you too and let me know if the battery drain is fixed.

**Comment by 0xrxL** [comment]
@Versty This issue is really annoying. All versions are affected, I can't install stable nor beta and nightly.

**Comment by derKief** [comment]
For me v4.5 Stable works without issues. Meanwhile i use that as a "dirty" workaround.
But as a paying customer I am disappointed how long it takes to fix this error.

**Comment by Versty** [comment]
@0xrxL @DBotThePony  Thank you! 
We are currently working on this issue. Will do our best to fix this bug in the upcoming version.

If you have any application logs to send to us, please mail it to qa@adguard.com. Mention the `[android]` keyword and `5460` number  in the subject.

**Comment by 0xrxL** [comment]
> @0xrxL @DBotThePony Thank you! We are currently working on this issue. Will do our best to fix this bug in the upcoming version.
> 
> If you have any application logs to send to us, please mail it to [qa@adguard.com](mailto:qa@adguard.com). Mention the `[android]` keyword and `5460` number in the subject.

Hope it will be available soon, because I'm currently surfing without adguard enabled...and its terrible.

**Comment by 0xrxL** [comment]
@derKief @Versty This is my current situation with 4.5 version. So, I can confirm the (infinitely) less drain.

![Screenshot_20241019_202707_Device care](https://github.com/user-attachments/assets/caa98811-191d-45f1-9033-1debbcb7c130)

**Comment by lupusthunder** [comment]
Same problem
Pixel 8 pro
Did a clean install yesterday and even over night got battery drain.  [Adguard turned off]

![1000015390](https://github.com/user-attachments/assets/42ea9029-0843-4bbc-a748-36930bdf8294)
![1000015389](https://github.com/user-attachments/assets/d2001d93-943d-4ec6-9c5e-a7e4f28eb235)

**Comment by khezuu** [comment]
I have this issue since a few days too. It drains about 30% battery every 4 hours. Uninstall app and battery gets me through the da again.

it started with 4.7 for me I think on Pixel 6a

**Comment by Versty** [comment]
@khezuu @lupusthunder @0xrxL @derKief @TheWrathRF 
Thank you for your patience. The fix is available in AdGuard for Android 4.7 nightly 39, we highly recommend to install this version and keep an eye on battery consumption. 

Please, let me know about any progress.

**Comment by lupusthunder** [comment]
Ok, installed. 
Will keep an eye on battery

**Comment by danielkoller** [comment]
Same for me with a Pixel 9XL Pro. I installed the latest Nightly. Let's hope that this fixes the issue. 
![Screenshot_20241028-140815](https://github.com/user-attachments/assets/d5aff923-54e6-40e0-9152-25c639cf8e2f)

**Comment by 0xrxL** [comment]
First partial results:

![Screenshot_20241028_223844_Device care](https://github.com/user-attachments/assets/6fe3664d-09d3-4e1b-adbe-e4142ade5f15)
![Screenshot_20241028_223925_AdGuard](https://github.com/user-attachments/assets/290ede51-6538-4c23-bf55-00ad3353d895)

1) The discharge graph remained linear for 4 hours (and it also increased during standby).

2) The device worked at normal temperatures (during this time was just became sightly warm, instead hotter).

3) AdGuard use percentage remained low, instead exceed 4% just after 10 minutes or few more.

I'll check if the following behavior can be replicated tomorrow, meanwhile other users post their results too

**Comment by lupusthunder** [comment]
Seems normal again 

![1000015406](https://github.com/user-attachments/assets/7ecb9400-5c11-438c-bc3b-d2b9ea5f909b)
![1000015405](https://github.com/user-attachments/assets/0670e10e-73f3-47d4-91cb-1e531e4ac415)

**Comment by danielkoller** [comment]
The latest Nightly also fixed the high battery drainage with my device (Pixel 9XL Pro).

**Comment by Smultie** [comment]
Fixed the issue for me too.
My curiosity is triggered though, what caused the issue?

**Comment by Guguloi** [comment]
Last week I've switched from P30 to Pixel 8 Pro. Same version of Adguard 4.6.3. On P30 never saw a problem with battery but on Pixel it was a problem so I switched to 4.5 version and battery is back to normal.
Yesterday evening I saw this Nightly version so I jump on it. Until now things looks normal with my battery.
![nightly](https://github.com/user-attachments/assets/ba00900d-e4f8-4457-b147-bff61eec66e8)

**Comment by 0xrxL** [comment]
After a full charge, I can say that battery consuption is totally different from before...but I would have expected less than 1% consumption, like on some older versions. 🤔

![Screenshot_20241029_171653_Device care](https://github.com/user-attachments/assets/9ebcbf58-6807-4047-bfbe-0882d5bb3f34)

**Comment by 0xrxL** [comment]
@Versty @artemi4nov

Battery drain is still here...unfortunately 😪

![Screenshot_20241030_224905_Device care](https://github.com/user-attachments/assets/e1a28794-9f22-43bd-a783-e0f715255eef)

**Comment by derKief** [comment]
I installed the new stable version 4.6.4 on both my devices today but unfortunately I quickly realized that the problem with the high battery consumption has not been resolved. On the contrary, I even have the feeling that it has gotten worse. Furthermore, new problems have arisen.
One of the two devices suddenly started charging very slowly and it felt very sluggish. After the downgrade to version 4.5 everything is fine again and the problems listed no longer exist.

For now I have gone back gain to version 4.5 on both devices. 

@Versty and @artemiv4nov please remove the tag Status: Resolved and Resolution: Fixed because unfortunately the problem does not seem to be solved and Fixed.
0xrxL also reported back that it is not resolved for him

**Comment by 0xrxL** [comment]
Downgraded back to 4.5, and the battery consuption returned to less 1% (with a high SoT):

![Screenshot_20241101_001312_Device care](https://github.com/user-attachments/assets/d847b28b-c09d-4b13-a31d-8e76f84969b2)

**Comment by derKief** [comment]
Why this is closed now ?
Issue is not solved resp. Fixed !!!!!
