### ISSUE TITLE
Receive error printing always, but works.

### ISSUE THREAD

**Issue by cocokola** [AdguardTeam/AdguardForAndroid#5463]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.3

### Environment

- OS version:
- Device:
Android 14z s24 ultra

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Social

AdGuard Social Media filter

### Other

AdGuard DNS filter

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

Regular

### Issue Details

Steps to reproduce:
1. Print anything. I'm printing ho 9110 deskjet
2. Check notifications from print spooler
3. Service name is print spooler, but unable to bypass this on app management.  If it's not shown.  
4. Note: formfill doesn't match beta options, difficult to ensure I've captured config.
![Screenshot_20240915_162110_AdGuard](https://github.com/user-attachments/assets/eb1ceab2-9a71-4a9d-8d3a-c2ff532f9fc9)

Same time as screen shot with error.

Thank you!

### Expected Behavior

No error producer, at best add the service to bypass local vpn

### Actual Behavior

Error shown in notifications. 
![Screenshot_20240915_162110_AdGuard](https://github.com/user-attachments/assets/8c493db5-eba1-47a5-85b3-cab9ce6392fb)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Unable to upload logs, too big.  I'll try to capture it again.

**Comment by ESurina** [comment]
In order to troubleshoot this issue, we need to get your application logs.
You could upload them to Google disk and then send us the link.

**Comment by cocokola** [comment]
I sent the logs through the app via this email.  Otherwise, here they are
again.
https://drive.google.com/file/d/1qc3G377EtbSJm5wJ7Pe1vU59mogAD8UW/view?usp=drivesdk

**Comment by ESurina** [comment]
Please, tell me which version of Print Spooler you have installed.

**Comment by cocokola** [comment]
I'm sorry, how can i get the version info especially if it is a system
process?

I am using hp smart printer, current version published to store.
Can you help me help you?

Samsung print service plug in
Version 3.10.240620

Hp smart
 Version 17.25.0.4906


That's all i can find.

**Comment by ESurina** [comment]
Go to settings -> Apps -> Tap on icon above the list, which opens screen *Filter and sort* -> Enable *Show system apps* -> Find Print Spooler and tap on it -> At the bottom of the screen there is a version of the app.

**Comment by ESurina** [comment]
Try adding com.android.printspooler to the exclusions. Here's how to do it:
1. Launch AdGuard
2. Go to Settings -> General -> Advanced -> Low-level settings -> Excluded apps
3. Add com.android.printspooler there and save changes

**Comment by ESurina** [comment]
If the problem happens again, please re-open the issue.
