### ISSUE TITLE
DPI Protection stopped working in Russia

### ISSUE THREAD

**Issue by UltraFeed** [AdguardTeam/AdguardForAndroid#5466]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.3

### Environment

- OS version: Android 14, Evolution X (6 September 2024 build)
- Device: Nothing Phone 2

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

RU AdList - Counters

### Other

AdGuard DNS filter

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

https://dns.controld.com/comss

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
Just try to watch YouTube video via app

### Expected Behavior

Work as it worked before - bypass YouTube slowdown, bypass yt3.ggpht.com block

### Actual Behavior

Not bypassing DPI anymore - videos and images are not loading

### Additional Information

Few days ago DPI protection stopped working, tried to change parameters - nothing worked. https://github.com/dovecoteescapee/ByeDPIAndroid is working perfectly

**Comment by ESurina** [comment]
Please note that the AdGuard ad blocker in general and the "DPI Protection" function are designed to ensure anonymity, and not to bypass locks. Therefore, gaining access to blocked sites in this case is rather a side effect, the stability of which cannot be guaranteed.
We recommend using more reliable and suitable tools for this task. For example, [AdGuard VPN](https://adguardvpn-help.com/ru/welcome.html) or any other VPN service.
