### ISSUE TITLE
Adguard AMP Extension not working.

### ISSUE THREAD

**Issue by AbhimanyuKhadse** [AdguardTeam/AdguardForAndroid#5469]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard 4.7 Nightly 26

### Environment

- OS version: Android 12
- Device: Realme 7 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Visit the site.
2. https://timesofindia.indiatimes.com/life-style/health-fitness/diet/beetroot-benefits-6-reasons-you-must-consume-this-vibrant-veggie-everyday/amp_articleshow/113660632.cms
3. I have installed bentasker amp script which usually redirect to original site. But on this particular site its not working. I tried enabling disabling adguard extension and app but nothing seems to work. But on other links bentasker amp works great but not adguard amp stable and beta extension userscript.

### Expected Behavior

It should redirect to non amp page.

### Actual Behavior

Not Redirecting to non amp page. And in url you will see (amp) word. And due to its amp nature empty ads space appears on entire site. And i have to manually remove it and then it works.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@AbhimanyuKhadse please update Adguard AMP Extension. In the top right corner of Home tab tap on the "Update" button and check the issue again

**Comment by maxikuzmin** [comment]
@AbhimanyuKhadse any news?

**Comment by AbhimanyuKhadse** [comment]
It worked sorry for late reply

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxikuzmin** [comment]
@AbhimanyuKhadse great news! I'll close the issue then. Good luck!
