### ISSUE TITLE
[Feature suggestion] Notifications/blog/news interface

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#547]
Add a 'What's new?' menu section, or, alternatively, a separate icon alongside with 'FAQ' button that would open a new window. 

In that window we could show latest news from blog, notifications about important forum threads, possibly some links to different polls etc.

The new section should be non-intrusive and visiting it should be completely volunteer to visit.

**Comment by Bohdan-SUP** [comment]
Maybe add this under About Adguard section?

**Comment by Revertron** [comment]
@Bohdan-SUP No, I think it must be apart from About. Separate section.

**Comment by ameshkov** [comment]
I don't think this is really necessary
