### ISSUE TITLE
Report incorrect blocking: 414 URI too long 

### ISSUE THREAD

**Issue by AbhimanyuKhadse** [AdguardTeam/AdguardForAndroid#5472]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard 4.7 Nightly 28 

### Environment

- OS version: Android 12
- Device: Realme 7 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

IndianList

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

Private

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Open Adguard App goto settings
2. Goto support section
3. Report incorrect blocking

### Expected Behavior

After selecting report incorrect blocking option. It should have open adguatd error reporting site

### Actual Behavior

After selecting report incorrect blocking option (request uri too long error)

### Screenshots

![Screenshot_2024-10-04-13-49-58-32_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/40e0ca70-aaef-49db-9fb2-b29d762a3bf8)

### Additional Information

When i disable entire adguatd extension service then site works normal.

**Comment by AbhimanyuKhadse** [comment]
Now in above screenshot you will see error and when i copy the url. That url contains this (https://reports.adguard.com/new_issue.html?android.method=High-quality&android.mode=VPN&android.system_root=false&browsing_security.enabled=true&custom_filters=https%3A%2F%2Fwww.i-dont-care-about-cookies.eu%2Fabp%2F%2Chttps%3A%2F%2Ffilters.adavoid.org%2Fultimate-ad-filter.txt%2Chttps%3A%2F%2Ffilters.adavoid.org%2Fultimate-privacy-filter.txt%2Chttps%3A%2F%2Ffilters.adavoid.org%2Fultimate-security-filter.txt%2Chttps%3A%2F%2Feasylist.to%2Feasylist%2Ffanboy-social.txt%2Chttps%3A%2F%2Feasylist.to%2Feasylist%2Ffanboy-annoyance.txt%2Chttps%3A%2F%2Feasylist-downloads.adblockplus.org%2Fabp-filters-anti-cv.txt%2Chttps%3A%2F%2Fgitflic.ru%2Fproject%2Fmagnolia1234%2Fbypass-paywalls-clean-filters%2Fblob%2Fraw%3Ffile%3Dbpc-paywall-filter.txt%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FAdguardTeam%2Fcname-trackers%2Fmaster%2Fdata%2Fcombined_disguised_trackers.txt%2Chttps%3A%2F%2Fraw.githubusercontent.com%2Fhoshsadiq%2Fadblock-nocoin-list%2Fmaster%2Fnocoin.txt%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FuBlockOrigin%2FuAssets%2Fmaster%2Ffilters%2Funbreak.txt&dns.enabled=true&dns.fallback_enabled=true&dns.filters=https%3A%2F%2Ffilters.adtidy.org%2Fandroid%2Ffilters%2F15_optimized.txt%2Chttps%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fhagezi%2Fdns-blocklists%40latest%2Fadblock%2Ftif.txt%2Chttps%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fhagezi%2Fdns-blocklists%40latest%2Fadblock%2Fultimate.txt%2Chttps%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fhagezi%2Fdns-blocklists%40latest%2Fadblock%2Fanti.piracy.txt%2Chttps%3A%2F%2Fbig.oisd.nl%2Chttps%3A%2F%2Fnsfw.oisd.nl%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FAdguardTeam%2Fcname-trackers%2Fmaster%2Fdata%2Fcombined_disguised_trackers.txt&dns.filters_enabled=true&dns.servers=https%3A%2F%2F9e67b3e9%3Az1%2A_Xw5J%40d.adguard-dns.com%2Fdns-query&dns.timeout=5000&filters=101.2.11.17.118.251.204.225.3.123.4.14.207.122.241.250.18.19.20.21.22.256.257.255.208.253.15.239&https.filtering=true&product_type=And&product_version=4.7+Nightly+28&stealth.DNT=true&stealth.block_third_party_auth=false&stealth.disable_third_party_cache=true&stealth.dpi=true&stealth.enabled=true&stealth.ext_hide_referrer=true&stealth.first_party_cookies=4320&stealth.hide_search_queries=true&stealth.ip=10.10.10.10&stealth.location=true&stealth.push=true&stealth.referrer=&stealth.third_party_cookies=60&stealth.user_agent=&stealth.webrtc=true&stealth.x_client=true&system_version=Android+12&userscripts=https%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fadguard-extra%2F1.0%2Fadguard-extra.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fassistant%2F4.3%2Fassistant.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fpopup-blocker%2F2.5%2Fpopupblocker.user.js%2Chttps%3A%2F%2FAdguardTeam.github.io%2FFingerprintingBlocker%2Ffingerprintingblocker.meta.js%2Chttps%3A%2F%2Fgithub.com%2FAdguardTeam%2FUserscripts%2Fraw%2Fmaster%2FdisableAutoplay%2Fdisable-autoplay.user.js%2Chttps%3A%2F%2Fgithub.com%2FAdguardTeam%2FUserscripts%2Fraw%2Fmaster%2FdisableAutofillPhishing%2Fdisable-autofill-phishing.user.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Fbeta%2Fdisable-amp%2F1.0%2Fdisable-amp.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fdisable-amp%2F1.0%2Fdisable-amp.meta.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F431691%2FBypass%2520All%2520Shortlinks.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Fbeta%2Fassistant%2F4.3%2Fassistant.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Fbeta%2Fadguard-extra%2F1.0%2Fadguard-extra.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Fbeta%2Fpopup-blocker%2F2.5%2Fpopupblocker.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Fbeta%2Fadguard-wot%2F1.0%2Fwot.meta.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fadguard-wot%2F1.0%2Fwot.meta.js%2Chttps%3A%2F%2Fgithub.com%2Fbentasker%2FRemoveAMP%2Fraw%2Fmaster%2Fredirect_to_non_amp_sites.user.js%2Chttps%3A%2F%2Fgithub.com%2Fbentasker%2FRemoveAMP%2Fraw%2Fmaster%2Fgreasemonkey_hook_googlesearch.user.js%2Chttps%3A%2F%2Fgithub.com%2Fbentasker%2FRemoveAMP%2Fraw%2Fmaster%2Fgreasemonkey_hook.user.js%2Chttps%3A%2F%2Fgitflic.ru%2Fproject%2Fmagnolia1234%2Fbypass-paywalls-clean-filters%2Fblob%2Fraw%3Ffile%3Duserscript%2Fbpc.en.user.js&utm_campaign=report)

And when extension service is off then it works. And the url is very short

**Comment by Versty** [comment]
@AbhimanyuKhadse This issue has been fixed recently, the link now leads to the fully operable page.
