### ISSUE TITLE
AdGuard for tv version can't play tencent video after turning on filtering (tv version is called cloudvision aurora)

### ISSUE THREAD

**Issue by x64bugreport** [AdguardTeam/AdguardForAndroid#5473]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.6

### Environment

- OS version:Android 11
- Device:station m2

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Mobile Ads filter

### Social

AdGuard Social Media filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.安装云试听极光
2.开启过滤(包括https过滤)
3.进入电影tab页 显示全部影片无法使用 播放电影卡住

### Actual Behavior

Steps to reproduce:
1.安装云试听极光
2.开启过滤(包括https过滤)
3.进入电影tab页 显示全部影片无法使用 播放电影卡住

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by x64bugreport** [comment]
https://tv.qq.com/   This is the apk link

**Comment by Versty** [comment]
@x64bugreport If you disable https filtering for this app, does the problem persist?

**Comment by x64bugreport** [comment]
> @x64bugreport If you disable https filtering for this app, does the problem persist?

Rentang cannot play it after turning off the https filtering. Filtering the logs through the app, I think it may be caused by blocking a certain quic protocol. Only when all filtering is turned off can the playback be normal.

**Comment by x64bugreport** [comment]
All filtering for this application must be turned off before it can be used normally, otherwise there will be no playback. I observed that multiple quic protocol requests were marked in red in the log. I'm not sure if this is the reason why the app is not working properly.

**Comment by x64bugreport** [comment]
Only turning off https filtering, keeping dns filtering, the app still doesn't work properly.

**Comment by Versty** [comment]
@x64bugreport 
The main reason why there are filtering issues in the app is because the mobile version of AdGuard is being used on TV. 
So we will try to solve this first. 

> After turning off the https filtering, it still cannot be played. By filtering the logs through the app, I think it may be caused by blocking a certain quic protocol. Only when all filtering is turned off can the playback be normal.

As a temporary solution, please add the package name of problematic app to the `QUIC bypass packages` list on the Low-level settings screen or disable the `Route traffic through AdGuard` switch for this app in the App management tab. 
Please let me know the result.

**Comment by x64bugreport** [comment]
> @x64bugreport The main reason why there are filtering issues in the app is because the mobile version of AdGuard is being used on TV. So we will try to solve this first.
> 
> > After turning off the https filtering, it still cannot be played. By filtering the logs through the app, I think it may be caused by blocking a certain quic protocol. Only when all filtering is turned off can the playback be normal.
> 
> As a temporary solution, please add the package name of problematic app to the `QUIC bypass packages` list on the Low-level settings screen or disable the `Route traffic through AdGuard` switch for this app in the App management tab. Please let me know the result.

I am glad to get your reply. After bypassing the specified package name QUIC, it can be played. But the channel list still fails to refresh. I think you may have an over-filtering problem. In addition, you said that the problem was caused by the mobile version I used. I use the station m2 player box. After installing the TV version, it is still the mobile version. I raised an issue, but your developers found a reason that made me laugh and closed my issue.

**Comment by x64bugreport** [comment]
I have reopened the issue of the TV version opening as the mobile version. I hope you will pay attention to it and not assign me a perfunctory developer to handle my issue.
https://github.com/AdguardTeam/AdguardForAndroid/issues/5483

**Comment by x64bugreport** [comment]
In addition, I am a lifetime paid member of adguard, and I hope you will not deal with my problem perfunctorily. After all, I paid, and I hope to have a good communication environment, rather than using a very perfunctory reason to close the issue.

**Comment by Versty** [comment]
@x64bugreport Thank you for all provided details. 

> After bypassing the specified package name QUIC, it can be played. But the channel list still fails to refresh. I think you may have an over-filtering problem.

I'm glad that the proposed solution has made things better. The channel list will probably be refreshed without any issues if you disable https filtering for this app. Please try it, then let me know the result. 

> I use the station m2 player box. After installing the TV version, it is still the mobile version. I raised an issue, but your developers give me a reason that made me laugh and closed my issue.

Mobile version of the app currently has a way more cool features compared to the TV version, including HTTPS filtering. 
Regardless of the fact that the app's interface doesn't look very suitable for TV on your device, I'd rather consider you as a lucky person in this case!

But let's continue to discuss this topic in the linked issue https://github.com/AdguardTeam/AdguardForAndroid/issues/5483

**Comment by x64bugreport** [comment]
> @x64bugreport Thank you for all provided details.
> 
> > After bypassing the specified package name QUIC, it can be played. But the channel list still fails to refresh. I think you may have an over-filtering problem.
> 
> I'm glad that the proposed solution has made things better. The channel list will probably be refreshed without any issues if you disable https filtering for this app. Please try it, then let me know the result.
> 
> > I use the station m2 player box. After installing the TV version, it is still the mobile version. I raised an issue, but your developers give me a reason that made me laugh and closed my issue.
> 
> Mobile version of the app currently has a way more cool features compared to the TV version, including HTTPS filtering. Regardless of the fact that the app's interface doesn't look very suitable for TV on your device, I'd rather consider you as a lucky person in this case!
> 
> But let's continue to discuss this topic in the linked issue #5483

After adding quic whitelist and removing https filtering, everything functions normally, but ads appear when the app opens, and some ads cannot be filtered.

**Comment by Versty** [comment]
@x64bugreport In this case, you can try enabling HTTPS filtering for the application, but instead add the specific domain responsible for loading the list of channels to HTTPS-filtered websites allowlist. 

*Settings tab -> Filtering -> Network -> HTTPS filtring -> HTTPS-filtered websites -> Website allowlist*
