### ISSUE TITLE
After the TV version is installed, the UI layout is still the mobile version.

### ISSUE THREAD

**Issue by x64bugreport** [AdguardTeam/AdguardForAndroid#5475]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.88

### Environment

- OS version:Android 11
- Device:Station M2

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Mobile Ads filter

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.download from agrd.io/tvapk
2.adb install adguard tv apk
3.After opening, the UI layout is still the mobile version.

### Expected Behavior

I hope that the TV version can be forced to set the TV layout without relying on the software to detect the model itself, and hope that the resolution can be adapted.

### Actual Behavior

Steps to reproduce:
1.download from agrd.io/tvapk
2.adb install adguard tv apk
3.After opening, the UI layout is still the mobile version.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

I hope that the TV version can be forced to set the TV layout without relying on the software to detect the model itself, and hope that the resolution can be adapted.

**Comment by x64bugreport** [comment]
I briefly looked at your conditions for judging TV UI through reverse engineering. I think this is not rigorous. On my station M2 device, the following function returned false and I was unable to use TV UI.

  public static final boolean b(Activity activity) {
        n.g(activity, "<this>");
        Object systemService = activity.getSystemService("uimode");
        n.e(systemService, "null cannot be cast to non-null type android.app.UiModeManager");
        int i = activity.getResources().getConfiguration().orientation;
        int currentModeType = ((UiModeManager) systemService).getCurrentModeType();
        if (currentModeType != 0) {
            if (currentModeType == 4) {
                return true;
            }
            return false;
        }
        if (activity.getPackageManager().hasSystemFeature("android.hardware.touchscreen")) {
            return false;
        }
        View decorView = activity.getWindow().getDecorView();
        n.f(decorView, "getDecorView(...)");
        if (i != 0) {
            if (i == 2) {
                return true;
            }
        } else if (decorView.getWidth() > decorView.getHeight()) {
            return true;
        }
        return false;
    }

**Comment by x64bugreport** [comment]
This function returned false on my device, but my device is indeed a box device. I hope you can provide an independent TV UI version program instead of deciding whether to display the TV UI through conditional judgment.

**Comment by x64bugreport** [comment]
If the official feels that the maintenance cost of developing two sets of apk is too high, I hope to add settings to force it to be set to TV UI. Currently, your adaptive UI logic turns out to be wrong on my device.

**Comment by x64bugreport** [comment]
We hope to provide an independent TV APK in the next update or force it to be displayed as TV UI through settings. Thank you!

**Comment by x64bugreport** [comment]
Here is the link to my device
https://en.t-firefly.com/product/industry/stationm2

**Comment by ESurina** [comment]
The fact is that your device is not a TV, so it displays the mobile interface of the application. Unfortunately, there is nothing we can do in this case.

**Comment by x64bugreport** [comment]
@ESurina 我是付费用户我对你的答复很不满意，我觉得你在敷衍我，怎么的横屏设备不属于TV是吧？？？
