### ISSUE TITLE
AMP Pages

### ISSUE THREAD

**Issue by AbhimanyuKhadse** [AdguardTeam/AdguardForAndroid#5482]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7.31

### Environment

- OS version:Android 12
- Device:Realme 7 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

Adguard Presonal

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Block ETag and If-None-Match headers, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1.Visit the ( https://indianexpress.com/article/cities/pune/pune-on-my-plate-a-favourite-eatery-that-die-hard-fans-brought-back-to-life-9616023/lite/
2. The site load as amp. You can see ( lite ) at end of url. If you remove that lite and load the page loads full
3. 

### Expected Behavior

It should load as a full page. But it loads as exact amp page.

### Actual Behavior

https://indianexpress.com/article/cities/pune/pune-on-my-plate-a-favourite-eatery-that-die-hard-fans-brought-back-to-life-9616023/lite/

It load as an amp page but if i remove (/lite) from url i.e
https://indianexpress.com/article/cities/pune/pune-on-my-plate-a-favourite-eatery-that-die-hard-fans-brought-back-to-life-9616023

It loads as full non amp page.

### Additional Information

I am using adguard amp userscript and beta version of it.

**Comment by AbhimanyuKhadse** [comment]
Here is the screenshot of the page. Long screenshot is of amp version and other one is non amp
![Screenshot_2024-10-12-18-06-35-14](https://github.com/user-attachments/assets/8119ad2b-051b-4919-a8eb-9c7406d90b3b)
![Screenshot_2024-10-12-18-08-57-82](https://github.com/user-attachments/assets/d564f534-6cc1-4e5e-a90a-2a70405279d3)

**Comment by Versty** [comment]
@AbhimanyuKhadse Hi!
Disable AMP scrips is designed to skip amp version if you enter the website from Google search. 

So, open google.com, enter `Pune on my plate: A favourite eatery that die-hard fans brought back to life` to the search field, then open a link to the article on https://indianexpress.com. The full version of website should be displayed.
