### ISSUE TITLE
Adguard Android Scene V4.0 has low speed in vpn&USE PROXY MODE

### ISSUE THREAD

**Issue by Extreme-Icer** [AdguardTeam/AdguardForAndroid#5485]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7.61

### Environment

- OS version:OneUI5.1
- Device:Samsung Galaxy N20U

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-TLS

### Custom DNS

*the dns server cant public *

### Issue Details

As the title suggests,if i use adguard vpn mode+proxy server,the direct speed is normal but the proxy speed is very low.What happened in this?
screen shot will send to email if support team provide email address.
Text description: I currently have a Gigabit broadband, and the downlink speed is still very high in the case of direct connection, but the speed will become less than 200Mbps when using a proxy. This phenomenon can be solved by switching the proxy software to VPN mode. It is well known that if you want to access the Internet smoothly in mainland China, you must use a proxy. I don't know why the speed is so slow.

### Expected Behavior

The speed is same as direct speed

### Actual Behavior

the downlink speed is still very high in the case of direct connection, but the speed will become less than 200Mbps when using a proxy

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@Extreme-Icer could you clarify, are you talking about "Routing mode" (Settings -&gt; Filtering -&gt; Network -&gt; Routing mode) : Manual proxy/Automatic proxy and Local VPN 
Or do you mean using Proxy (Settings -&gt; Filtering -&gt; Network -&gt; Proxy)? 
Could you export the settings and send the settings to [qa@adguard.com](mailto:qa@adguard.com)? 
Include `[android]` keyword and `ISSUE_NUMBER` in the subject of your email

**Comment by maxikuzmin** [comment]
@Extreme-Icer any news?

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer could you clarify, are you talking about "Routing mode" (Settings -> Filtering -> Network -> Routing mode) : Manual proxy/Automatic proxy and Local VPN Or do you mean using Proxy (Settings -> Filtering -> Network -> Proxy)? Could you export the settings and send the settings to [qa@adguard.com](mailto:qa@adguard.com)? Include keyword and in the subject of your email`[android]``ISSUE_NUMBER`

Adguard use VPN mode,v2rayNG use proxy mode,adguard connect v2rayng local proxy
but i use speedtest to test bandwidth is my contracted bandwidth very small.if i test local network(cn network)is normal.

**Comment by Extreme-Icer** [comment]
@maxikuzmin  any news?

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer globally, any proxy slows down the internet connection, but when you are actively connected the connection speed is usually slower, this is normal. Try some other proxy, maybe another proxy will be faster

As shown in the screenshot I sent in the email, if it is VPN+proxy, the speed of the proxy will be weakened, and if the proxy is in VPN mode, the speed will be normal.

**Comment by maxikuzmin** [comment]
@Extreme-Icer could you please clarify if you only use the v2rayNG app in VPN mode (without AdGuard), is the speed also reduced?

**Comment by Extreme-Icer** [comment]
only v2rayng speed is normal.
see email screenshot

**Comment by maxikuzmin** [comment]
@Extreme-Icer in your screenshots, as far as I can see, everything makes sense. 
So, what we have:
speed just with v2rayNG VPN mode - 447 mbps
speed just with adguard vpn mode - 668 mbps
speed with adguard vpn mode+v2rayng proxy mode - 108 mbps.

as I said, any proxy slows down the internet connection, but when you are actively connected, the connection speed is usually slower, this is normal
