### ISSUE TITLE
AdGuard Private browser crashes 

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#5486]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7N33

### Environment

- OS version:android 14
- Device:SM-N975F

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish GDPR-Cookies Filters, Polish Social Filters

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1.Open adguard, 
2.Tapp browser on down bar
3.Add site address - shutter down or blocking them 

### Expected Behavior

Worked browser 

### Actual Behavior

The browser is not working properly, crashing, not implementing for any functionality to control the browser, undoing the page turns off the browser, restart locks the address bar cannot open the page. Browser tests HTML5test.com,https://html5test.com, Basemark Web 3.0. https://web.basemark.com. Basemark Web 3.0 - Main page.
They were very average. You cannot open the website bbcnews24. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by TPS** [comment]
@U0101100 Do you also see bahaviors listed in https://github.com/AdguardTeam/AdguardForAndroid/issues/5488?

**Comment by Versty** [comment]
@TPS The work on the browser feature is still in progress. This will be drastically improved in future nightly versions.

**Comment by Versty** [comment]
@U0101100 @TPS 
This crash is addressed in nightly 34.
