### ISSUE TITLE
AGa Private Browser Bugs

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#5488]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7n33

### Environment

- OS version: Android 12 stock
- Device: 1+ N200 5g

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

?

### Privacy

?

### Social

?

### Annoyances

?

### Security

?

### Language-specific

?

### Which DNS server do you use?

Open DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

?

### Issue Details

Steps to reproduce:
1.  Enable Private Browser from option on 1st tab
2.  Attempt to open Private Browser from same option

### Expected Behavior

Private Browsing commences, but is not any kind of default

### Actual Behavior

AGa crashes consistently, & Private Browsing is setup as default embedded browser

### Screenshots

<details><summary>AGa Private Browsing option</summary>

↓ Is this showing?  I see in Android, but not in GH app. ↓
![AGa Private Browser](https://github.com/user-attachments/assets/9b797337-99a6-4fc4-9b29-74ebb436a0c9)

</details>

### Additional Information

_Idk why areas `?` above were labeled "No response" when I did.  Form broke?_

Sharing/calling URL directly opens blank browser & then must manually input URL, but ad-blocking inconsistent & no AG Recent Activity logs to debug! 😖

I _believe_ different bugs than https://github.com/AdguardTeam/AdguardForAndroid/issues/5486?

**Comment by Versty** [comment]
@TPS We are aware of this bugs, will be fixed!

**Comment by Versty** [comment]
@TPS Should be fixed on AdGuard for Android 4.7 beta 1. Please try it out! 
If you find any new bugs related to Private Browser, please let me know by creating separate bug reports for each one.

**Comment by TPS** [comment]
Yes, these bugs are fixed, but the browser is still so klunky & hard to debug.  As I use it, I'll file more bugs.
