### ISSUE TITLE
Proxy Support for Private Browser

### ISSUE THREAD

**Issue by tmby** [AdguardTeam/AdguardForAndroid#5490]
### Issue Details

In AdGuard v4.7 nightly 33, the new Private Browser feature was introduced, which is a great addition. However, users in regions like China often require a proxy to access certain services, and currently, the Private Browser does not utilize the proxy settings configured in AdGuard.

### Proposed solution

I propose that the Private Browser be enabled to use the proxy server settings already set up in AdGuard. This would allow users to access the internet more effectively while maintaining privacy.

### Alternative solution

If direct integration isn't feasible, consider adding an option in the Private Browser settings to configure a proxy manually.

Thank you for considering this feature request!

**Comment by maxikuzmin** [comment]
@tmby thanks for your observation! We are planning to provide Proxy support for Private Browser in the release version :)
Please wait until the release
