### ISSUE TITLE
Adding custom timestamp feature support for YouTube app

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardForAndroid#5491]
### Issue Details

YouTube has revealed an updated sharing mechanism in YouTube app for Android, and the app's share screen contains a toggle mentioning the time/duration, depending on where you've paused the video. But when the video is shared with AdGuard, it starts from the beginning, ignoring the timestamp.

### Proposed solution

If possible, please add the support of this timestamp feature in order to be able to watch the video after sharing with AdGuard from the specific moment.

**Comment by maxikuzmin** [comment]
@OlgaPetukhova unfortunately there is no possibility to analyze link parameters during sharing link in youtube player
