### ISSUE TITLE
WHITELISTING - Website allowlist in Ad blocking, User rules in Ad blocking, User rules in DNS filters: some web sites still detect an ad-blocker

### ISSUE THREAD

**Issue by colemar** [AdguardTeam/AdguardForAndroid#5495]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.3

### Environment

- OS version: Android 14
- Device: Pixel 7 Pro

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

EasyList Italy

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Check that Adguard is active
2. Open ubitennis.com or en.yifysubtitles.live/movies in Chrome
3. ubitennis: "Adblock detected!", yifysubtitles: "Please Disable ad blocker :("
4. Disable Adguard ("Protection is disabled")
5. Open ubitennis.com or en.yifysubtitles.live/movies in Chrome
6. The websites do not detect an ad-blocker

Other settings:
- Protection/Ad blocking/Website allowlist: `yifysubtitles.live`, `ubitennis.com`
- Protection/Ad blocking/User rules: `@@||yifysubtitles.live^`
- DNS protection/DNS filters/User rules: `@@||yifysubtitles.live^`,`@@||ubitennis.com^`,`@@||ue.flipboard.com^`

### Expected Behavior

Said web sites can be browsed without hassles.

### Actual Behavior

See above.

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/55a21e0b-5137-426a-8c7d-e73b7f214b79)

</details>
<details><summary>Screenshot 2</summary>

![image](https://github.com/user-attachments/assets/ba1a484d-a7e1-4ccd-bc32-247ff0d7525a)

</details>

**Comment by ESurina** [comment]
In order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*.
2. Reproduce the problem, then remember the exact time when it happened.
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*.
4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by colemar** [comment]
@ESurina Debug logs sent in email as requested.

**Comment by ESurina** [comment]
Rules don't help because the request is sent to another domain to show ads on websites. You can try to find out what domains are used through the recent activity or through devTools and then add rules for these domains.

**Comment by colemar** [comment]
@ESurina If you're saying that those web sites make the browser load ads from external domains, this is very common but has not be a problem for AdGuard afaik. What are they doing specifically?
