### ISSUE TITLE
HomeDepot (www. & m. ) don't load in Amazon APK, but do in website APK

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#55]
Ticket# VXP-866-81378

I noticed this since I installed Amazon version, both VPN & proxy.  (I'd just forgotten 'til now.…)  Is there anything in the later builds that may help?

**Comment by Revertron** [comment]
@TPS I've tested this in Firefox and Chrome on current dev version - there is no any problem on that website.
May be there was some sort of network glitch when you used Amazon APK?

**Comment by TPS** [comment]
It's still doing it for me (several weeks), but only on Ghostery browser under VPN.

```
The webpage is not available
The webpage at http://m.homedepot.com/ might be temporarily down or it may have moved to a new web address.

Here are some suggestions

Try reload this web page later.
Check the web page address to make sure you have entered it correctly.
Check your firewall settings. All connections should be allowed for Adguard.
Check your proxy settings if you use proxy server.

java.io.IOException: Input stream is closed

```

Oddly, works fine under CM Private Browsing on same device, or under Ghostery on my x86 tablet via proxy.  Did the log I sent show anything useful?

**Comment by ameshkov** [comment]
Let's re-test it on the next beta (we'll push it to Amazon tomorrow)

**Comment by TPS** [comment]
@ameshkov I've not yet seen the Amazon version update again.…  Is Amazon delaying it?

**Comment by ameshkov** [comment]
@TPS we have not yet pushed it, need more time on debugging:)

**Comment by TPS** [comment]
@ameshkov Since, as of right now you're releasing many beta versions, it would be worth releasing the Amazon beta versions at the same time, with all its & general fixes, else it will be a lot of changes to test at once.  Also, for whatever reason, Amazon apps tend not to get updated timely, & it'd be good to get in practice.  Finally, I really need the fix for #69, as it keeps spamming/tempting me for all the main beta releases!

**Comment by ameshkov** [comment]
@TPS it's not that simple. As I understand we need to re-send beta testers invitation for every beta release on Amazon. I don't understand why they have made it so difficult.

**Comment by Revertron** [comment]
@TPS We've unloaded new beta to amazon store. Can you try to repeat this bug?

**Comment by TPS** [comment]
@ameshkov I've updated my [Amazon App-tester odd notes](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-140069504) with that & an additional observation.… ☺

@Revertron Still there in .156 .  I have a hunch.  In the low-level settings, can you all add an option to clear AdGuard's internal caches, especially if there's a DNS cache?  I think sometimes my flaky wireless AP/router causes this problem (poisons DNS) & I suspect AdGuard keeps the poisoned entries more-or-less permanently.

**Comment by ameshkov** [comment]
Btw that is possible but only for manual proxy mode.

**Comment by ameshkov** [comment]
@Revertron let's clear DNS cache on every protection restart.
Look at DnsCache class.

**Comment by TPS** [comment]
@ameshkov @Revertron Of course, my problem is on my Amazon, VPN setup (though, if I switch to proxy, it's the same.)

**Comment by ameshkov** [comment]
@TPS In VPN mode we do not use own DNS cache so it can't be the cause of the issue.

**Comment by TPS** [comment]
Ok, it was worth a guess.  What now?

**Comment by ameshkov** [comment]
We now need the full log in "Record everything" mode, the log in ticket is not enough to understand what's causing it.

**Comment by TPS** [comment]
@ameshkov I've sent full "Record everything" log & will update with ticket when I receive confirmation e-mail.

**Comment by ameshkov** [comment]
@TPS your cookies size for homedepot is 18kb.

I don't know if it's ok or not, but I think clearing cookies is worth trying:)

**Comment by ameshkov** [comment]
In fact that's all I see, server simply drops the connection after we've finished sending request

**Comment by TPS** [comment]
Well, shoot, _that_ worked!  Thanks for the extracurricular debugging!  Is this the sort of problem that AG should automatically try to detect & mitigate/notify?  Else, I'm happy simply to close it.… :relieved:
