### ISSUE TITLE
Data speed reduced with HTTPs filtering enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#550]
I also noticed when https is enabled that my data speed is drastically reduced. I probably averaged about 2mb/s prior to enabling https filtering. Afterwards, it rarely exceeds 1mb/s. I monitor my bandwidth with the Android app 'network monitor pro'

logs: YKF-630-68684

**Comment by ameshkov** [comment]
Duplicate for #470 

Speed is much better in the dev build (apparently it will be good in beta that is coming soon)
