### ISSUE TITLE
Черная магия

### ISSUE THREAD

**Issue by Cursone** [AdguardTeam/AdguardForAndroid#5501]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 4.6.4

### Environment

**OS version:** Android 14
**Device:** Realme C67

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Issue Details

Выскочило сообщение на обновление

### Actual Behavior

Предлагает на саму себя же обновиться

### Screenshots

![Screenshot_20241104-195940](https://github.com/user-attachments/assets/d32139c4-0c35-4d42-a99e-7370d1881542)

**Comment by zzebrum** [comment]
@Cursone вчера был выпущен хотфикс, но версию приложения не поднимали. Поэтому так выглядит.
