### ISSUE TITLE
I seem to have found a bug

### ISSUE THREAD

**Issue by Shura23** [AdguardTeam/AdguardForAndroid#5502]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard v4.7 nightly 35

### Environment

- OS version: HarmonyOS 4.2 (Android 12)
- Device: Huawei Mate 30

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

https://dns.alidns.com/dns-query

### Issue Details

下面链接是我使用的DNS过滤器，我将这个过滤器在DNS保护中安装后，我发现有一些请求没有被过滤，但是我在自定义过滤器中订阅这个过滤器时就会有另一种情况。下面第一张和第二张截图可以看出来区别。
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt
我发现当我是在“DNS保护”中订阅这个过滤器时，有一些请求的url是以"dns"开头的，可以成功拦截，但是如果是以“https”开头，则无法拦截，但是这两个域名是一样的，过滤器中有规则可以阻止这个域名，但是显示没有规则。反过来，如果是在“自定义过滤器”中订阅这个过滤器，当请求是“dns”开头则无法过滤，当请求是“https”开头则可以过滤，刚好反过来了。
你们可以看一下第三张截图和第四张截图和第五张截图。

### Expected Behavior

我的预期应该是，当发出请求是A.com时，我的过滤器有阻止这个域名的规则，那么无论是在“自定义过滤器”中还是在“DNS保护”中都应该拦截这个域名，无论是dns://A.com  ，还是https://A.com，都应该拦截才对

### Actual Behavior

实际行为就在问题详细信息中

### Screenshots

![Screenshot_20241105_162635_com adguard android](https://github.com/user-attachments/assets/7eafc3b5-0c4d-4d82-80ff-cbe04a7f2ec8)
![Screenshot_20241105_154409_com adguard android](https://github.com/user-attachments/assets/66c1775c-e0e3-4d92-afcf-3f968b73f32c)
![Screenshot_20241105_132023_com adguard android](https://github.com/user-attachments/assets/3255d9b4-2f8e-414f-a716-1b8dd22b8b11)
![Screenshot_20241105_132114_com adguard android](https://github.com/user-attachments/assets/48ec9ee6-16ed-4e15-90c3-4c7cd98c36b1)
![Screenshot_20241105_132031_com adguard android](https://github.com/user-attachments/assets/3b1e457d-7b02-4668-bed5-36a550952926)

### Additional Information

截图在显示的域名，我使用的过滤器都有相应的规则，我还特地去询问了这个过滤器的开发者，的确是有规则的，而且我也将过滤器更新到最新了

**Comment by AbhimanyuKhadse** [comment]
Yes i am also having the same problem with hagezi ultimate. When i open realme app store ( hagezi installed as dns filter) no ads and tracker blocked. But when i install it as a custom filter it blocks.

**Comment by Versty** [comment]
@Shura23 @AbhimanyuKhadse DNS filtering and HTTPS filtering are two separate mechanisms of traffic filtering. 
Highly recommended to read more about HTTPS filtering in [the article](https://adguard.com/en/blog/everything-about-https-filtering.html). And [here ](https://adguard-dns.io/kb/general/dns-filtering/) you can find a detailed explanation on how DNS filtering works. 

According to the filer name the `HaGeZi's Ultimate DNS Blocklist` is designed for DNS protection module, but if it works for you as HTTPS filter without any issues, you can use it as custom ad blocking filter as well.
