### ISSUE TITLE
Option to turn off default behaviour of routing all apps

### ISSUE THREAD

**Issue by v5point0** [AdguardTeam/AdguardForAndroid#5506]
### Issue Details

Can you set default routing behaviour? I want all apps installed and future installs to not be routed to Adguard unless manually requested. Yes I can stop all but that only applies for apps already installed, what about future installed apps - it gets tedious to manually check every time you install an app. As for the reason, I only need Adguard on Chrome, don't need it for the other apps.

### Proposed solution

Enable an option to not auto route all apps by default including to be installed ones.

**Comment by Versty** [comment]
@v5point0 Hi! 

This feature request duplicates #4482. Please put the 👍 on the linked post, if you wish this feature to be implemented.

**Comment by v5point0** [comment]
Done, thank you
