### ISSUE TITLE
ВАЖНО! СРОЧНО!: Перестало работать обновление фильтров в Adguard для Android

### ISSUE THREAD

**Issue by NUser2018** [AdguardTeam/AdguardForAndroid#5507]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.4 (4.6.204)

### Environment

- OS version: Android 13
- Device: Realme C25S

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard Russian filter

### Which DNS server do you use?

Google DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Перестало работать обновление фильтров в Adguard для Android

### Expected Behavior

Обновление фильтров в блокировщике рекламы Adguard для Android на смартфоне как и ранее должно работать корректно как автоматически в фоновом режиме, так и при проверке обновления фильтров принудительно вручную пользователем.

### Actual Behavior

Обновление фильтров в блокировщике рекламы Adguard для Android на смартфоне внезапно перестало работать корректно как автоматически в фоновом режиме, так и при проверке обновления фильтров принудительно вручную пользователем.

### Screenshots

<details><summary>Screenshot 1</summary>

 
![Screenshot_2024-11-07-14-35-28-59](https://github.com/user-attachments/assets/653ad65b-c64f-4304-9510-5d1a872938a9)

</details>

<details><summary>Screenshot 2</summary>

 
![Screenshot_2024-11-07-14-37-44-89](https://github.com/user-attachments/assets/e5e44a54-bd01-44bf-aa30-5ba7f4f4a96c)

</details>

### Additional Information

**ВАЖНО! СРОЧНО!: Перестало работать обновление фильтров в Adguard для Android**

Здравствуйте! Новая срочная важная проблема в работе блокировщика рекламы в России!

Являюсь пользователеем платной лицензии\версии. Со вчерашнего дня (6 ноября) ближе к вечеру внезапно перестало работать корректно обновление фильтров в блокировщике рекламы (как автоматически так и при проверке принудительно вручную) AdGuard для Android на смартфоне через мобильный интернет от Мегафона.

При этом через WiFi через проводной домашний интернет через другого провайдера обновление фильтров работает по прежнему корректно.

Подозреваю что причина возникновения проблемы может быть связана с новыми действиями со стороны Роскомнадзора по массовой блокировке в России использования ECH (вообще или только для ресурсов использующих Cloudflare пока сложно сказать) (подробнее можно почитать в Интернете вообще или например по ссылке https://www.comss.ru/page.php?id=15036 ), однако т.к. я всё же не технический специалист то это только мои предположения конечно, может быть это и не связанные друг с другом вещи.

Однако факт на лицо что со вчерашнего дня обновление фильтров в блокировщике рекламы через указанного мною выше провайдера напрямую и без использования различных средств и методов борьбы с блокировками не работает. Также сайт с фильтрами напрямую в браузере по ссылкам из настроек приложения по фильтрам не открывается теперь.

Тогда как при использовании различных средств и методов борьбы с блокировками обновление фильтров в блокировщике рекламы от Adguard для Android снова начинает работать корректно... Например при применении сторонних VPN и сторонних средства обхода DPI

Однако например при применении дополнительно Adguard VPN обновление фильтров в блокировщике рекламы от AdGuard для Android тем не менее не начинает почему-то работать нормально и корректно, хотя сам Adguard VPN и интернет через него и различные сервисы и приложения работают корректно... Почему я не знаю конечно, ведь повторюсь я не настолько продвинутый в техническом смысле пользователь, тут уж команде Adguard виднее должно быть почему так происходит в данном случае в данной связке...

Однако применение дополнительных средств обхода блокировок для обеспечения нормальной работы обновления фильтров в блокировщике рекламы от AdGuard для Android это не выход (тем более если иметь в виду не периодическую проверку обновления фильтров принудительно вручную а именно возвращение нормальной работы автоматического обновления фильтров в фоновом режиме работы AdGuard) поскольку все, ну или почти все, подобные средства основаны на использовании VPN-соединения (настоящего или локального как и сам блокировщик рекламы например использует такое локальное VPN-соедиение для фильтрации трафика) и соответственно при включении подобных средств борьбы с блокировками тогда соответственно локальное VPN-соедиение от блокировщика рекламы отключается и фильтрация рекламы перестает работать в связи с тем что (из-за ограничений со стороны самого Android насколько я понимаю) одновременно два VPN-соединения в Android активны быть не могут.

Также дополнительно отправлю логи с воспроизведением проблемы и другую диагностическую информацию собранную через соответствующий штатный функционал приложения блокировщика рекламы от Adguard на Android на Вашу электронную почту ( devteam@adguard.com ) поскольку здесь в задаче на ГитХабе лучше конечно публично подобную информацию в целях безопасности и конфиденциальности не выкладывать наверное в общем доступе.

Прошу обратить внимание что ранее уже бывали случаи что мои письма к Вам на данную электронную почту не доходили в связи с тем что письма блокировались на Вашей стороне системой защиты от спама, потом эта проблема вроде бы как была исправлена на Вашей стороне, однако поскольку никогда нельзя наверное на 100% исключать вероятность повторения такой проблемы то прошу Вас сразу же как можно скорее подтвердить в ответном сообщении здесь в задаче на ГитХабе и/или в ответном письме мне на электронную почту что моё письмо с логами до Вас успешно дошло и Вы прикрепили логи к данной проблеме в Ваших внутренних системах в компании и приступите к их изучению. Ведь в противном случае (если вдруг моё письмо до Вас снова по какой-то причине не дойдет) нужно будет тогда поискать другое решение проблемы и возможно согласовать каким-то образом другой вариант/способ получения от меня Вами этих логов.

Обращаю Ваше внимание что файлы логов приложений AdGuard в системе Android были мною принудительно вручную удалены перед началом воспроизведения проблемы чтобы логи начали записыватся заново и имели как можно меньший размер и содержали в себе как можно меньше другой информации кроме той информации что относится непосредственно к воспроизведению проблемы и будет надеюсь максимально полезна для изучения проблемы и её решения.

Заранее спасибо. Жду Вашего ответа здесь в задаче на ГитХабе и/или на мою электронную почту с которой я сейчас чуть позже отправлю письмо с файлом с логами. Надеюсь что проблему удастся решить и как можно скорее. С уважением **NUser2018**.

P.S.: на эту задачу на ГитХабе я конечно же сейчас сразу подпишусь на уведомления и буду следить за ней. Также когда отправлю на Вашу электронную почту письмо с логами то обязательно здесь сразу напишу дополнительно сообщение об этом.

**Comment by NUser2018** [comment]
@Versty Письмо с логами отправил на электронную почту devteam@adguard.com Жду от  Вас подтверждения получения моего письма с логами.

**Comment by ameshkov** [comment]
Не кипишуйте, это РКН заблочил какой-то из IP-адресов CDN-сервера :)

**Comment by NUser2018** [comment]
@ameshkov Это я понимаю и это было очевидно, но просто другие варианты типа создания задачи здесь на ГитХабе ещё меньше подходили под эту проблему. А сообщить-то и вступить в переписку по этой проблеме мне же было как-то нужно команде AdGuard.

Конечно это не баг самого приложения, но задачу Вы зря закрыли уже, ведь проблема пока ещё не решена и возможно для её решения ещё потребуется здесь переписка между нами и обмен какой-то информацией.

Например письмо с логами и другой технической и диагностической информацией к Вам от меня пришло или нет? Вы так об этом ничего и не написали.

Врядли блокировка идёт по какому-то конкретному IP-адресу, поскольку в этом случае обычно помогают только VPN/прокси, а в данном случае помогают средства обхода DPI без VPN/прокси.

Сервера с которых идёт загрузка обновлений фильтров не используют Cloudflare? А ECH не используется? Сейчас Роскомнадзор крепко взялся похоже именно за это активно (см. по ссылке от меня в моём сообщении) и применяет тотальные ковровые блокировки не оглядываясь на последствия для других обычных легальных сайтов и сервисов и их обычных пользователей.

**Comment by NUser2018** [comment]
@ameshkov О результатах рассмотрения и решения этой проблемы Вы потом здесь и/или мне на электронную почту напишете? Иначе как я об этом узнаю, особенно в случае отрицательного результата? Да и в случае положительного результата тем не менее мне же нужно будет об этом узнать как-то чтобы проверить и подтвердить исправление проблемы.

**Comment by ameshkov** [comment]
Для фильтров мы используем CDN77, у них много разных IP-адресов, видимо какие-то попали под блокировку.

Мы им отписали про это и пока что отключили европейские серверы, должно полегчать.

**Comment by NUser2018** [comment]
@ameshkov Ясно. Спасибо за информацию. Буду ждать, наблюдать и надеятся. Если что напишу здесь ещё снова конечно.

Но повторюсь... Врядли блокировка идёт по IP-адресам, поскольку в этом случае обычно помогают только VPN/прокси, а в данном случае помогают и другие средства обхода блокировок, средства для обхода DPI без VPN/прокси. Например ByeDPI for Android.

**Comment by NUser2018** [comment]
@ameshkov пока к сожалению лучше не стало. Нужно какое-то время на вступление в силу сделанных вами технических изменений?

**Comment by NUser2018** [comment]
@ameshkov Пока ещё буду наблюдать для надёжности конечно. Но у меня через указанного оператора через мобильный интернет обновление фильтров вроде заработало. Будем надеятся что в ближайшее время хотя бы это снова не сломается. Если что пишите здесь на ГитХабе в этой задаче и/или на мою электронную почту с которой я вам сегодня отправлял письмо с логами. Спасибо за оперативность. Был рад помочь команде Adguard узнать об этой проблеме и исправить её.

**Comment by ameshkov** [comment]
@NUser2018 да честно говоря через раз там все работает, мы ж не контролируем какие IP-адреса пользователям будут возвращаться.

Если проблема вернется - посмотрите пожалуйста какой IP-адрес у `filters.adtidy.org` в вашем случае (надо будет какую-нибудь утилиту для DNS-запросов установить).

**Comment by ameshkov** [comment]
Московский сервер вроде. В общем давайте до завтра подождем чем пытаться догадаться что произошло. Может просто РКН где-то навертел лишнего с блокировками.

**Comment by ameshkov** [comment]
А можете вот на эту страницу зайти еще: https://debug.tools.cdn77.com/

И поскриншотить что она там выдаст

**Comment by NUser2018** [comment]
@ameshkov Врядли что изменится. Ведь со вчера уже это началось.

**Comment by NUser2018** [comment]
Сейчас уже другой результат показывает но всё-равно не работает.

<details><summary>Screenshot </summary>

 
![Screenshot_2024-11-07-21-25-36-56_414bc0c0a42eb797f7af1b1af0c1cd81](https://github.com/user-attachments/assets/eff55d75-0cd3-4573-9123-af6be6b95ce7)
</details>

**Comment by NUser2018** [comment]
> И поскриншотить что она там выдаст

@ameshkov Сделал. Сейчас сюда скриншотов набросаю.

**Comment by NUser2018** [comment]
<details><summary>Screenshot1</summary>

 
![1](https://github.com/user-attachments/assets/cbc6f7ff-4d02-429d-a975-0bad1d361cae)
</details>

<details><summary>Screenshot2</summary>

 
![2](https://github.com/user-attachments/assets/2249c925-e3df-48ea-813f-2d556e1ef253)
</details>

<details><summary>Screenshot3</summary>

 
![3](https://github.com/user-attachments/assets/caad2248-8d21-4924-b068-b8be1ddfe220)
</details>

<details><summary>Screenshot4</summary>

 
![4](https://github.com/user-attachments/assets/01cab8eb-8bc4-4b11-a884-7b4568444170)
</details>

<details><summary>Screenshot5</summary>

 
![5](https://github.com/user-attachments/assets/e40c01fa-365b-4c58-bbcc-17d01d92c5f5)
</details>

<details><summary>Screenshot6</summary>

 
![6](https://github.com/user-attachments/assets/3e0104e8-73cc-44b2-b2a6-ced85c90d965)
</details>

**Comment by NUser2018** [comment]
@ameshkov Набросал в сообщении выше скриншотов с результатами теста с указанной Вами ранее страницы. Это что-то даёт для понимания проблемы и её решения? Что? Заранее спасибо. Жду Вашего ответа. С уважением **NUser2018**.

**Comment by ameshkov** [comment]
У меня такое ощущение что проблема связана с Мегафоном кстати, в мониторинге МТС себя нормально ведет. В любом случае спасибо за скриншоты, передадим в CDN.

**Comment by NUser2018** [comment]
@ameshkov МТС Домашний или мобильный? У меня домашний проводной интернет как раз от МТС и через него через WiFi нормально работает.

**Comment by NUser2018** [comment]
@ameshkov Ну судя по тому что помогает не только использование стороннего VPN но и ByeDPI for Android то это больше похоже всё же на какую-то блокировку со стороны Роскомнадзора, возможно не специально а попутно до кучи при какой-то ковровой блокировке. Возможности проверить на каких-то других провайдерах и операторах кроме указанных мною у меня к сожалению нет.

**Comment by ameshkov** [comment]
МТС да любой, мобильный тоже ок. Возможно действительно РКН что-то лишнего сломал, в любом случае ребята из CDN-сервиса думаю смогут связаться с мегафоном и разобраться.

**Comment by NUser2018** [comment]
@ameshkov Хорошо. Будем надеятся. Правда не факт что в итоге всё будет хорошо. И неизвестно сколько времени это займет. В любом случае по возможности пожалуйста пишите здесь и/или на мою электронную почту (с которой я сегодня отправлял вам письмо с логами) если/когда у Вас будут какие-то новости по данной проблеме. Из CDN на ваш запрос они же должны в итоге в любом случае какой-то ответ прислать раз ваша компания является их клиентом? И я конечно буду здесь ещё писать обо всех изменениях и новостях которые увижу на своей стороне как конечного пользователя.

**Comment by NUser2018** [comment]
@ameshkov Роскомнадзор вот уже прямым текстом конкретные рекомендации (а по сути указания) раздает владельцам сайтов. :(
https://www.comss.ru/page.php?id=15044

**Comment by NUser2018** [comment]
@ameshkov Ещё потыкал в диагностической сетевой утилите и другие инструменты помимо DNS Nslookup. 

Получается что пинг до **filters.adtidy.org** проходит, а трассировка нет. Не знаю может быть конечно это нормально и так и должно быть, но на всякий случай решил Вам об этом здесь написать сейчас.

**Comment by NUser2018** [comment]
@ameshkov Нет никаких новостей по проблеме? Утро наступило, но к сожалению ожидаемо лучше не стало. :(

**Comment by NUser2018** [comment]
@ameshkov А загрузка новой версии приложения непосредственно из приложения на какой адрес и сервер завязана? Это похоже тоже не работает. :(
Например при переключении на тестовый канал обновления Nightly новую версию находит но загрузить не может. После нажатия на кнопку **Обновить** для загрузки обновления, кнопка становится неактивной но загрузка новой версии приложения не начинается и больше ничего не происходит даже если ждать очень долго .

При этом официальный сайт **adguard.info** нормально открывается и по ссылке из самого приложения и напрямую в браузере.

<details><summary>Screenshot </summary>

 
![Screenshot_2024-11-08-12-06-54-34_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/user-attachments/assets/f56272f5-8453-4edd-aa83-89eb8803b224)
</details>

**Comment by NUser2018** [comment]
@ameshkov К сожалению у меня есть мнение что т.к. CDN насколько я понимаю это иностранная компания то есть большая вероятность что Мегафон ничего вообще не ответит на их запрос, а в лучшем случае будет валить всё на Роскомнадзор. И в каком-то смысле будет даже прав, поскольку средствами ТСПУ (через которые сейчас и идут наверное уже большинство блокировок, если не все ещё) управляет же непосредственно напрямую сам Роскомнадзор и операторы скорее всего не имеют возможности ни юридически ни чисто технически и физически туда вмешиватся.

Поэтому у меня есть очень нехорошее ощущение что эта проблема будет тянутся ещё долго, если не останется вообще насовсем, если только команда Adguard не предпримет каких-то технических изменений со своей стороны, как возможно в самом приложении, так и возможно по смене/добавлению другой компании CDN. Ну тут уж Вам виднее конечно какие варианты решения этой проблемы могут быть вообще и непосредственно со стороны Adguard в частности.

Очень жду от Вас хороших новостей по проблеме, поскольку со своей стороны к сожалению пока никаких хороших новостей написать не могу, поскольку их нет. :(

**Comment by NUser2018** [comment]
@ameshkov Оказывается на форуме **4pda.to** эту проблему уже тоже обсуждают, в основном про Мегафон, но есть проблемы и жалобы от пользователей и с другими операторами и провайдерами.

Подробнее можно посмотреть и почитать на форуме начиная с поста по ссылке ниже, три страницы уже есть в профильной теме про Adguard для Android, но конечно немного вперемешку с другими сообщениями:

https://4pda.to/forum/index.php?showtopic=601691&view=findpost&p=133271015

**Comment by NUser2018** [comment]
@ameshkov Дополню что судя по сообщениям пользователей на форуме у некоторых пользователей есть проблемы и на МТС, плюс может похоже зависеть не только от оператора но и от конкретного региона, в частности на Мегафон несколько жалоб, но например один пользователь с Мегафона из Питера пишет что у него нормально работает. Вообщем как-то странно, но проблема есть и затрагивает многих пользователей и не только Мегафон.

**Comment by NUser2018** [comment]
@ameshkov Рекомендую читать тему на форуме начиная с поста по ссылке выше от меня и до конца темы и внимательно и регулярно следить за темой, поскольку даже у одних и тех же пользователей периодически ситуация меняется то в лучшую, то обратно в худшую сторону, о чём пользователи и пишут в теме снова.

**Comment by NUser2018** [comment]
@ameshkov тут мне один пользователь подсказал на форуме что похоже в России наряду с Cloudflare собираются ограничивать и такие CDN как как раз Ваш CDN77 и Akamai

Конечно в Интернете и в СМИ об этом пишут как о возможном в ближайшее время, но по факту на примере этой проблемы с обновлением фильтров в блокировщике рекламы от AdGuard мы видим что это уже происходит, ну или как минимум идёт техническая наладка и подготовка у некоторых операторов уже.

Так что к сожалению само оно вряд ли наладится как я и писал здесь уже ранее. Да и вообще без каких-то активных действий и изменений со стороны AdGuard получается вряд ли что-то сдвинется в лучшую сторону как я и предполагал и писал уже здесь до этого.

Очень ждём от Вас какой-то информации по этой проблеме (теперь получается не только я жду но и другие пользователи блокировщика рекламы от Adguard с того форума по ссылке от меня здесь выше ранее).

Пару ссылок на эту информацию в Интернете, но конечно есть и другие:

https://www.kommersant.ru/doc/7295900

https://t.me/webstrangler/3837

**Comment by NUser2018** [comment]
@ameshkov Если это действительно так и так пойдет и дальше и ситуация будет развиватся и дальше в худшую сторону то с очень большой вероятностью скоро это затронет всех пользователей блокировщика рекламы от AdGuard из России во всех регионах и на всех операторах и провайдерах и не только блокировщик рекламы от Adguard для Android но и для Windows, хотя если кто-то уже сейчас использует проблемного провайдера для доступа в Интернет и с компьютера то наверняка уже и сейчас в этом случае проблема затрагивает блокировщик рекламы не только на Android но и на Windows уже тоже.

Вообщем решать и что-то делать конечно команде Adguard, но похоже само не рассосётся и ситуация и проблема требует какого-то кардинального и оперативного решения.

Жду новых новостей от Вас по проблеме и очень надеюсь что хороших.

С уважением **NUser2018**.

**Comment by ameshkov** [comment]
Посмотрел новости, ну что ж, продолжают нагнетать. Ну видимо РКН экспериментирует выборочно на некоторых провайдерах с ограничениями CDN'ов.

У нас компания не российская и переезжать на национальные CDN'ы мы не будем. Борьба с ветряными мельницами честно говоря утомляет.

Мы посмотрим можно ли как-то более менее адекватно эту проблему решить, надеюсь что-то найдется. Но вполне может быть что эксперименты завершат и все само собой нормализуется.

**Comment by NUser2018** [comment]
@ameshkov Хорошо. Если что пишите. Будем ждать и надеятся. Для решения проблемы не обязательно же на российский хостинг переезжать, но иностранных же наверняка не три штуки, кроме перечисленных же наверняка полно ещё есть. Может быть можно сделать какое-то точечное индивидуальное решение тогда для пользователей из России? Надежда только на команду Adguard честно говоря. В противном случае врядли что-то изменится в лучшую сторону, скорее наоборот только в худшую. А в целом получается что пока непонятно как эту проблему можно решить и сколько ещё пользователи из России (а извините конечно но не стоит всё же забывать что насколько я знаю компания AdGuard и её продукты начинались именно в России? Разве нет?) будут сидеть с такими проблемами с обновлением фильтров в блокировщике рекламы?

Пожалуйста поймите меня правильно, это не претензия, ни в коем случае, но что-то же делать нужно, ведь продукты компании Adguard это очень хорошие и уникальные продукты и решения и я и многие другие пользователи из России пользуются ими уже очень много лет. Что-то же нужно сделать чтобы попытаться решить эту проблему!? Ждём от Вас новых сообщений и желательно с хорошим новостями.

Заранее спасибо. С уважением **NUser2018**

**Comment by NUser2018** [comment]
@ameshkov Если что-то нужно будет помочь и/или протестировать и проверить то всегда рад буду помочь насколько смогу конечно. Пишите здесь в задаче на ГитХабе и/или на мою электронную почту с которой я на днях отправлял Вам письмо с логами по этой проблеме с указанием на эту задачу на ГитХабе.

**Comment by NUser2018** [comment]
@ameshkov Про YouTube тоже многие сначала думали что это временно и в качестве эксперимента и довольно скоро всё отменят, но как показывает практика к сожалению это не так, хотя я изначально понимал что так и будет. :(

**Comment by NUser2018** [comment]
@ameshkov А как бы всё же можно попытаться попробовать определить блокировка идёт конкретно по/для **filters.adtidy.org** или же сам **filters.adtidy.org** не блокируется напрямую а блокируется только потому что используется CDN77? Если подскажете вариант/способ как это можно попробовать проверить то попробую это сделать у себя.

**Comment by ameshkov** [comment]
Мы уже проверили, это CDN77 блокируют.

**Comment by NUser2018** [comment]
@ameshkov Ясно. Ждём от Вас новостей по проблеме и очень надеемся что хороших.

**Comment by ameshkov** [comment]
@NUser2018 как у вас сейчас, открывается все?

**Comment by NUser2018** [comment]
@ameshkov Да, сейчас обновление через мобильный интернет заработало. Спасибо. Будем надеятся что не сломается снова хотя бы в ближайшее время. Если что я снова обязательно сюда напишу, наверное в эту же задачу чтобы вся цепочка и история были здесь. Поэтому если Вы подписаны на эту задачу и/или каким-то иным образом получаете в том или ином виде автоматические уведомления о новых сообщениях в этой задаче, то пожалуйста на всякий случай хотя бы ещё какое-то некоторое время не отписывайтесь от этой задачи/репорта.

Ещё раз БОЛЬШОЕ СПАСИБО! С уважением **NUser2018**.

**Comment by NUser2018** [comment]
@ameshkov Здравствуйте! Снова на днях перестало работать обновление фильтров в блокировщике рекламы от Adguard на смартфоне Android через мобильный интернет МегаФона. Запрос в службу поддержки Adguard уже есть **#1087018**
Однако судя по всему Ваше личное участие в рассмотрении запроса и в рассмотрении проблемы и ее решении было бы весьма нелишним. Честно говоря у меня уже только на Вас похоже и надежда. Заранее спасибо. С уважением **NUser2018**.

**Comment by ameshkov** [comment]
Да там РКН с ума сходит, в разных регионах блочит по-всякому. Я думаю надо просто ждать пока их попустит.

**Comment by NUser2018** [comment]
@ameshkov Я думаю что само может и не пройти к сожалению. Тенденция наоборот на закручивание гаек и ковровые блокировки целых протоколов и хостингов. :( Поэтому стоит подумать как это можно попробовать поправить со стороны компании Adguard. Но в любом случае спасибо за Ваши ответ и мнение. Если что пишите здесь и/или на электронную почту с которой был открыт указанный мною свежий запрос и ведётся переписка в рамках него со службой поддержки Adguard.

**Comment by NUser2018** [comment]
@ameshkov У меня проблема присутствует с 29 апреля и тенденции на улучшение пока к сожалению не наблюдается.

**Comment by NUser2018** [comment]
@ameshkov Здравствуйте! :) К сожалению улучшений в плане обновлений у блокировщика рекламы не наблюдается. :(

На мобильном интернете указанном ранее здесь и в запросе **#1087018** обновление фильтров и т.д. всё также работает лишь частично:

- проверка новой версии приложения и обновление базы данных Защиты от фишинга работают (тьфу-тьфу-тьфу) вроде бы стабильно, также как и открытие официального сайта adguard.info

- обновление Фильтров блокировки контента, DNS-фильтра и Расширений всё также не работает

Но теперь ещё в последние дни появились частично проблемы на компе на проводом интернете (провайдер другой, провайдера по моему также всё же указывал и упоминал ранее в ходе переписки по запросу): фильтры и т.д. к счастью пока на данный момент обновляются нормально (тьфу-тьфу-тьфу) но периодически наблюдаются проблемы с открытием официального сайта adguard.info и при проверке новой версии программы из самой программы как при автоматической проверке при запуске программы так и при проверке принудительно вручную.

Очень надеюсь что эта дополнительная информация будет полезна и поможет улучшить и ускорить изучение проблемы и ускорит её решение.

Очень надеюсь и очень жду хороших новостей по проблеме здесь в этой задаче на ГитХабе и/или на электронную почту использованную в рамках запроса (личный кабинет на официальном сайте Adguard также зарегистрирован на эту электронную почту).

Если что пишите. Заранее спасибо. С уважением **NUser2018**.

**Comment by ameshkov** [comment]
@NUser2018 а проверьте фильтры пожалуйста, все ли ок теперь?

**Comment by NUser2018** [comment]
> [@NUser2018](https://github.com/NUser2018) а проверьте фильтры пожалуйста, все ли ок теперь?

@ameshkov Здравствуйте! Проверил. Уж не знаю что и где вы там подкрутили но да, теперь обновление фильтров снова работает у меня и на смартфоне через всё тот же проблемный мобильный интернет! Для надежности конечно ещё понаблюдать нужно и неизвестно насколько этого снова хватит. Если что я конечно же обязательно снова напишу сюда. Но на данный момент снова работает!

БОЛЬШОЕ СПАСИБО ВСЕЙ КОМАНДЕ ADGUARD И КОНЕЧНО ЖЕ ЛИЧНО ВАМ!!! :)

C уважением **NUser2018**.

**Comment by NUser2018** [comment]
@ameshkov Дополню: сегодня с утра ещё точно не работало, а теперь работает! :)

**Comment by NUser2018** [comment]
@ameshkov И снова здравствуйте! :)
К сожалению снова есть некоторые проблемы с обновлением Adguard на Android. :(
А именно в последние дни наблюдается проблема что не обновляется База данных Защиты от фишинга. При проверке обновлений принудительно вручную у этого пункта индикатор крутится бесконечно. Скриншот прилагается.
К счастью по остальным пунктам (и это тоже можно увидеть на скриншоте) обновления Adguard на Android работают на данный момент нормально.
Касательно обновления Базы данных Защиты от фишинга то (на данный момент и во всяком случае у меня) это не работает ни через мобильный интернет ни по WiFi через домашний проводной интернет (провайдеры напомню два разные соответственно для мобильного интернета и для проводного). И на этот раз даже утилиты для обхода DPI не помогают. Помогает только временное использование стороннего VPN (временное соответственно потому что блокировщик рекламы не может работать параллельно одновременно вместе со соронним VPN), тогда этот пункт также обновляется.
Но это опять же не выход а временный костыль, тем более что VPN это не выход потому что в РФ они активно давятся и блокируются и сторонние VPN соответственно часто не работают или работают очень нестабильно.
Понимаю что причина этой новой небольшой проблемы не на стороне и не из-за компании Adguard и что учитывая симптомы проблемы вполне возможно её будет достаточно трудно решить/исправить и тем более максимально быстро... :(
Но тем не менее я (как и обещал ранее здесь же) решил Вам всё же об этом сообщить и обратить на это Ваше внимание. Может всё же снова получится исправить и эту проблему, хотя конечно она к счастью на этот раз не настолько критичная как полная неработоспособность обновления фильтров и т.д. которая была некоторое время назад.
Жду Вашего ответа. Заранее спасибо.
С уважением **NUser2018**.

<details><summary>Screenshot </summary>

![Image](https://github.com/user-attachments/assets/531d316b-765a-4362-9e0d-f34ded767824)

**Comment by NUser2018** [comment]
@ameshkov Ещё раз здравствуйте! Ситуация лучше не стала к сожалению. База данных Защиты от фишинга так и не обновляется через мобильный интернет МегаФона. Всё остальное к счастью обновляется нормально (тьфу-тьфу-тьфу) на данный момент. Так теперь ещё и сайт adguard.info не открывается и ещё Личный кабинет/аккаунт Adguard (adguardaccount.net). РКН похоже применяет теперь ковровые блокировки как минимум на некоторых операторах в некоторых регионах в отношении целых хостингов. И блокировки какие-то хитрые. Сайты/страницы судя по индикатору браузера начинают немного грузится но потом загрузка стопорится и продолжается бесконечно и безрезультатно. Такая же ситуация похоже и с учётной записью Adguard VPN. И обойти такие блокировки теперь не так-то просто и гораздо сложнее.

**Comment by ameshkov** [comment]
@NUser2018 да они многие CDN начали реально коврово блокировать без причины.

Можете developer tools в браузере открыть и посмотреть какие конкретно запросы не грузятся?

**Comment by NUser2018** [comment]
@ameshkov А в Гугл Хроме на Android это есть? Как и что нужно тогда сделать? Поясните конкретно и желательно поподробнее и пошагово по возможности. Постараюсь проверить и написать о результатах. Хотя думаю что проблема и причина не в неработоспособности отдельных запросов каких-то. Впечатление что просто через некоторое время после начала загрузки сайта/страницы скорость просто рубится практически в ноль и загрузка глохнет и можно ждать дальше бесконечно и бесполезно. Т.е. блокировка происходит как бы не сразу и поэтому её гораздо сложнее обойти. Ещё хуже то что в этих случаях как правило не помогают прочие средства обхода DPI, которые помогают при других более обычных методах блокировки. А в случае подобных блокировок на данный момент к сожалению помогают только VPN/прокси.

**UPDATE:** важный дополнительный вопрос. При проведении проверки о которой Вы писали ранее имеет ли значение будет ли при этом блокировщик рекламы от Adguard на смартфоне в этот момент работать или нет? Тогда лучше чтобы он в это время работал как обычно или лучше на время проведения проверки его временно выключить/выгрузить?

**Comment by ameshkov** [comment]
Да наверное не принципиально. Вообще мы с разных провайдеров проверяли доступность сайтов-зеркал и вроде бы сейчас все доступны.

**Comment by NUser2018** [comment]
@ameshkov К сожалению про мобильный интернет Мегафона (Поволжье) не могу такое сказать. Указанные мною пару дней назад адреса Adguard через этот интернет по прежнему не открываются.

Вот интересная статья про блокировку Cloudflare (https://www.comss.ru/page.php?id=16849) Но похоже что подобные методы применяются и к некоторым другим зарубежным хостингам, во всяком случае на некоторых провайдерах/операторах и/или в некоторых регионах России.

**Comment by NUser2018** [comment]
@ameshkov Здравствуйте! На данный момент не наблюдаю проблем в работе продуктов Adguard через указанный мною ранее мобильный интернет. Включая как обновление фильтров и т.д (причем заработало даже обновление Базы данных Защиты от фишинга которое долго время не работало через этого оператора)... Также на данный момент не наблюдается и проблем при открытии как официального сайта (adguard.info) так и аккаунта/личного кабинета по ссылкам из приложения. Хотя некоторе время несколько дней назад наблюдались проблемы и со входом в учётную запись и даже проблемы с активацией лицензии на блокировщик рекламы способом путём ввода ключа лицензии прямо в приложении.

**Comment by ameshkov** [comment]
Ну посмотрим сколько продержится:)

**Comment by NUser2018** [comment]
> Ну посмотрим сколько продержится:)

@ameshkov На данный момент через указанный мобильный интернет официальные сайты и Личный кабинет/аккаунт снова не открываются. Но в остальном в работе продуктов Adguard (блокировщик рекламы и VPN) проблем вроде как не наблюдается.
