### ISSUE TITLE
Adguard youtube player not working properly 

### ISSUE THREAD

**Issue by yazhamuthan-aruchamy** [AdguardTeam/AdguardForAndroid#5508]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.4

### Environment

- OS version: Android 14
- Device: Samsung Galaxy A35 5G

Uploading tinywow_Screen_Recording_20241106_121129_AdGuard_68719957.mp4…

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

Regular

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1.Open Google and type what you needed in the query
2. GO TO the videos tab and click on the any video
3. And it should automatically goto the adguard player and should play the video.
4. I was block and not working in there.

My own trackers list which I have been enabled in the custome filter list
[Trackerslist.txt](https://github.com/user-attachments/files/17662226/Trackerslist.txt)

### Expected Behavior

The video should play in the adguard player but it was not out of 10 only 2 videos are playing other not

### Actual Behavior

It should play the video in the adguard player 10 out of 10.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by yazhamuthan-aruchamy** [comment]
![VideoCapture_20241107-190954](https://github.com/user-attachments/assets/2c5a4e33-e0dd-40a9-9280-c63430077ce4)

This is the actual was display while playing the vdieo

**Comment by maxikuzmin** [comment]
@yazhamuthan-aruchamy could you clarify, are you trying to open a YouTube video?

**Comment by yazhamuthan-aruchamy** [comment]
Hi, yes when ever I try to open the youtube video it was showing the results like that in the image not everytime out of 10 / 6 videos are showing like that and some time the 10 also working fine. And some times the 10 also showing the same result like in the image.

**Comment by maxikuzmin** [comment]
@yazhamuthan-aruchamy could you update to version 4.7 and try again?

**Comment by yazhamuthan-aruchamy** [comment]
After updating to 4.7 it is working great thanks

**Comment by maxikuzmin** [comment]
@yazhamuthan-aruchamy glad to hear it! Closing this issue

**Comment by maxikuzmin** [comment]
@yazhamuthan-aruchamy glad to hear it! Closing this issue
