### ISSUE TITLE
AdGuard Browser not exiting

### ISSUE THREAD

**Issue by JustAAdGuardFan** [AdguardTeam/AdguardForAndroid#5509]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard v4.7 Nightly 45

### Environment

- OS version: Android 13
- Device: Samsung Galaxy A71

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Open AG browser in anywhere except for Private Browser tab
2. Try to exit it

### Expected Behavior

Exit

### Actual Behavior

Not exit

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@JustAAdGuardFan Any updates?
