### ISSUE TITLE
Adguard crashes after switching any option with disabled WiFi

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#551]
With enabled WiFi everything is fine. He uses Android 4.4.4 Based Rom - MIUI 7 Global Beta (Android Security Patch Level : 2016-05-01)

Originally from: 
https://forum.adguard.com/index.php?threads/10272

Video of the problem:
https://sendvid.com/6nxv5lq3

Logs can be found here:
EQE-130-21329

**Comment by Revertron** [comment]
After switching any option we show progress dialog while service is applying new settings. In the user's video I don't see that dialog. Something with firmware, I suppose.
