### ISSUE TITLE
Not able to login to Accounts in AdGuard Private Browser 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#5510]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 4.7 Nightly 46

### Environment

- OS version: Android 14 One 6.1
- Device: Samsung Galaxy S24 Ultra 

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Chinese filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Ukrainian filter

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Block Location API, Hide your Referrer from third-parties, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1.when using AdGuard Browser can't login to account example: AdGuard Private DNS, GitHub
2.
3.

### Actual Behavior

Says something went wrong.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@Batman2814 Hi! 
Does this issue persist with AdGuard for Android 4.7 beta 1?

**Comment by Batman2814** [comment]
It's fixed in AdGuard Adblocker Nightly for Android Version 4.7 Nightly 52 but was originally fixed in version 4.7 nightly 51

**Comment by Devadityakumar** [comment]
I think it is not a bug because getting logged into a account means that your data such as history will be saved even if you have started the option of not to collect the history. And it won't be private anymore.
