### ISSUE TITLE
After the TV version is installed, the UI layout is still the mobile version. (Force open adguard TV UI !!!)

### ISSUE THREAD

**Issue by x64bugreport** [AdguardTeam/AdguardForAndroid#5511]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.92

### Environment

OS version:Android 11
Device:Station M2

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.download from agrd.io/tvapk
2.adb install adguard tv apk
3.After opening, the UI layout is still the mobile version.

### Actual Behavior

I hope that the TV version can be forced to set the TV layout without relying on the software to detect the model itself, and hope that the resolution can be adapted.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Regarding this issue, please clearly tell me the repair cycle and why there has been no reply to messages. I am a life member. Please don't treat paying users arbitrarily.
https://github.com/AdguardTeam/AdguardForAndroid/issues/5483

**Comment by x64bugreport** [comment]
Don't always try to fool me. I will continue to pay attention until the problem is resolved.

**Comment by x64bugreport** [comment]
![adguard](https://github.com/user-attachments/assets/5e11b4e5-a7cb-410d-8b33-edc1f6e0c415)
In my device, currentModeType is not equal to 4. I hope you can adjust the order of judgment, move if(decorView.getWidth() > decorView.getHeight()) to the front, or combine multiple detection results in an OR relationship and then put returns instead of directly judging that it is not TV mode and returning false.

**Comment by x64bugreport** [comment]
Java.perform(function () {
    // 获取 UiModeManager 类
    var UiModeManager = Java.use("android.app.UiModeManager");
    UiModeManager.getCurrentModeType.implementation = function () {
        return 4;  // 强制返回4，表示电视模式
    };
});

I am disappointed with the attitude and efficiency of the arguard development team, this is a frida script used to trick adguard into forcing the TV UI solution on other devices with landscape screens.

**Comment by x64bugreport** [comment]
https://mega.nz/file/oJZigKTL#49eCzoPTJ2l3WwkDwuNpUZS7wp8voj5HtP109SXSRrM
unpack password is 123

This is an adguard mod version that forces the display of the TV UI on. I feel very sad about the arrogance and inefficiency of the official developers. As a paying user, I have no choice but to solve it myself.

**Comment by x64bugreport** [comment]
Either you are perfunctory or you don't assign the person responsible for the bug. I am extremely disappointed with your team's performance. To sum up, you can fix it as you like. If you don't fix it, I will fix it myself. The user experience is terrible, are you worthy of the money I paid?

**Comment by Versty** [comment]
@x64bugreport Hello! 

Our internal processes might not seem transparent for users, so let me explain. The previously created bug report https://github.com/AdguardTeam/AdguardForAndroid/issues/5483 is confirmed, prioritised and is waiting to be fixed according to priority. Then a developer will be assigned when work on the fix begins. 

If you have any additional details or suggestions, please add it to initial issue, so that the developer can take them into account.
