### ISSUE TITLE
Easy setup for blocking ads in YouTube

### ISSUE THREAD

**Issue by Devadityakumar** [AdguardTeam/AdguardForAndroid#5517]
### Issue Details

It is hard to set up ad blocker for YouTube and makes a lot of confusion.

### Proposed solution

There could a option for starting the ad blocker for YouTube which could stop every ad. If you want to include sponsors too that would be much better

### Alternative solution

IDK

**Comment by maxikuzmin** [comment]
@Devadityakumar are you using AdGuard player? All it takes is a tap on share button and select AdGuard player. Would you like to simplify the use of AdGuard  player?

**Comment by maxikuzmin** [comment]
@Devadityakumar I'm closing this issue at this time. Please, if you have any suggestions to improve YouTube player, describe in more detail what you would like to see
