### ISSUE TITLE
malicious certificate is being detected

### ISSUE THREAD

**Issue by singh9596** [AdguardTeam/AdguardForAndroid#5528]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7 RC2

### Environment

- OS version: 13
- Device: Samsung m42

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances

### Security

Online Malicious URL Blocklist

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Launch ICICI's iMobile app
2. Shows error
3. Skipping works but the point is the certificate is being detected

### Actual Behavior

Won't let me access the app

### Screenshots

![IMG_20241204_140228_1](https://github.com/user-attachments/assets/cd2895d6-4a66-42be-b7fa-d5c809290a2c)

**Comment by ESurina** [comment]
Unfortunately, we don't know why this application identifies our certificate as malicious. Perhaps it recognizes all user certificates this way. There's nothing we can do about it.
