### ISSUE TITLE
Adguard Diagnostic fails on Gecko based Browser

### ISSUE THREAD

**Issue by singh9596** [AdguardTeam/AdguardForAndroid#5530]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7

### Environment

- OS version: 13, 14
- Device: Samsunf m42, Pixel 8

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Automatic proxy

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist

### Other

AdGuard DNS filter

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

Regular

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. open mull or firefox
2. Run adguard diagnostic test on adguard.com/en/test.html
3. Shows app: running but adguard extra, tracking protection and other test fails. (HTTPS enabled and I tried reseting to default settings for adguard as well as my browser)

### Expected Behavior

Must pass all the tests just like it works on chromium based browser

### Actual Behavior

Shows HTTPS filtering is off and fails rests of the tests. Refer the attached images.

### Screenshots

![Screenshot_20241204-192629_Mull](https://github.com/user-attachments/assets/8ff92b5e-2b2e-4894-9c75-5c7b7a1738fe)
![Screenshot_20241204-192826_AdGuard](https://github.com/user-attachments/assets/92eb9168-9720-4bc9-99a7-3facb4600d56)

### Additional Information

I've rooted as well as non rooted device both are facing the same issue for so long. Today I decided to raise my concern.

**Comment by ESurina** [comment]
You need to follow the steps in this [manual](https://adguard.com/kb/adguard-for-android/solving-problems/firefox-certificates/) and also you have to update filters.

**Comment by singh9596** [comment]
> You need to follow the steps in this [manual](https://adguard.com/kb/adguard-for-android/solving-problems/firefox-certificates/) and also you have to update filters.

Still not working 
![Screenshot_20241205-151445_Firefox](https://github.com/user-attachments/assets/87848b08-e122-4a4f-a987-cfad7cf80676)
![Screenshot_20241205-151459_Firefox](https://github.com/user-attachments/assets/bcc35326-5d5d-47b3-8242-a874e8e22cca)

**Comment by singh9596** [comment]
Thanks it worked

**Comment by singh9596** [comment]
It sucks. With https enabled for mull, now many of the sites are inaccessible. Have no issue on brave whatsoever.
