### ISSUE TITLE
Adguard System Webview?

### ISSUE THREAD

**Issue by Nemisor** [AdguardTeam/AdguardForAndroid#5531]
### Issue Details

Not really a problem, but when I saw the announcement of the private browser feature, I immediately assumed it would be something similar to Vanadium (in GrapheneOS for instance).

### Proposed solution

If possible, could the new Adguard browser be configured as an alternative system webview? This way, filtration would work within _other_ apps, and not just through Adguard itself or by launching through a widget. I believe this would be a much more elegant solution than yet another browser, especially considering how much investment is involved in maintaining a fully featured browser.

### Alternative solution

If system webview is not possible, is it selectable as a chrome custom tab provider?

**Comment by Versty** [comment]
@Nemisor Hi!
Did you mean like “Other apps should use AdGuard Private Browser instead of Android Webview”?

**Comment by Peter-maximus** [comment]
it would be great feature to register it as an alternative browser, so user would have a choice when opening links from other apps to choose adguard browser to view it.

**Comment by Versty** [comment]
@Peter-maximus At this moment AdGuard Private browser can be set as default browser in the system settings. This means that the links from any app will be opened in AdGuard Private Browser by default. 

We also have a solution for those who use any other browser as default, but wish to use AdGuard Private Browser from time to time. You can open any link in AdGuard Private Browser using Share option: long tap on the link -> Share -> AdGuard -> AdGuard Browser.

**Comment by Versty** [comment]
@Nemisor We discussed this feature requests with development team. Implementation of AdGuard Webview and support of Chrome custom tabs are not planned for the short or medium term.
