### ISSUE TITLE
Update to v4.7 crashes Tab S8 Ultra

### ISSUE THREAD

**Issue by GlitchHopAnonymous** [AdguardTeam/AdguardForAndroid#5532]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7

### Environment

- OS version: 14
- Device: Samsung Tab S8 Ultra

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter, ABPindo, ABPVN List, Adblock List for Finland, Bulgarian list, CJX's Annoyances List, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Serbo-Croatian List, EasyList Czech and Slovak, EasyList Hebrew, EasyList Italy, EasyList Lithuania, EasyList Polish, EasyList Portuguese, EasyList Spanish, EasyList Thailand, Estonian List, Frellwit's Swedish Filter, Greek AdBlock Filter, Hungarian filter, Icelandic ABP List, IndianList, KAD - Anti-Scam, Latvian List, List-KR, Liste AR, Macedonian adBlock Filters, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Persian Blocker, Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish Social Filters, road-block light, ROList, ROLIST2, RU AdList - Counters, Xfiles, xinggsf, YousList

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### Custom DNS

quic://fd3beec4.d.adguard-dns.com

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Download v4.7 update
2. Install v4.7 update
3. try to open the updated AdGuard

### Expected Behavior

I expected the app to open.

### Actual Behavior

The app crashed.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

The update to v4.7 on my Galaxy S10+ went smoothly & did not crash upon opening after the update so clearly it is an issue specific to this device.

**Comment by maxikuzmin** [comment]
@GlitchHopAnonymous could you send us a [logcat](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/)?

Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `5532` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by maxikuzmin** [comment]
@GlitchHopAnonymous any news?

**Comment by GlitchHopAnonymous** [comment]
[AdGuard_v4.7.1_crash-com-adguard-android-December_12__2024_AD-12-18-01_4590_Part-1.zip](https://github.com/user-attachments/files/18105953/AdGuard_v4.7.1_crash-com-adguard-android-December_12__2024_AD-12-18-01_4590_Part-1.zip)
[AdGuard_v4.7.1_crash-com-adguard-android-December_12__2024_AD-12-18-06_1780-Part-2.zip](https://github.com/user-attachments/files/18105954/AdGuard_v4.7.1_crash-com-adguard-android-December_12__2024_AD-12-18-06_1780-Part-2.zip)

Here are the logs. FYI these crash logs are from the app crashing after updating to v4.7.1 not v4.7. It crashes upon opening after updating to both versions on my Tab S8 Ultra.

**Comment by GlitchHopAnonymous** [comment]
Sorry I did not notice the email request. I just sent the email you requested w/ the log files now in addition to what I posted above.

**Comment by maxikuzmin** [comment]
@GlitchHopAnonymous please clarify if the problem is recurring with version 4.7.1?

**Comment by GlitchHopAnonymous** [comment]
Yes the problem is recurring w/ v4.7.1 too.

**Comment by leacha69** [comment]
I'd like to add that I'm on a Samsung Tab S9 Ultra and I've noticed AdGuard (4.7. 179) would be disabled/crashed after a period of inactivity while charging or its sleep mode.

My settings are almost a clone of @GlitchHopAnonymous. Minus most stealth mode settings.

**Comment by maxikuzmin** [comment]
@leacha69 could you open a new issue? It looks like you have a slightly different case, please specify the steps to reproduce, preferably we should understand what is happening: disabling protection or crashing the application. Please observe the behavior with debug logs and attach the logs to the issue. If the application crashes consistently, then [logcat](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) will be needed.

**Comment by maxikuzmin** [comment]
@GlitchHopAnonymous we need a little more time

**Comment by GlitchHopAnonymous** [comment]
Ok no problem just lmk when you release the update that fixes the problem & I will lyk if it worked.

**Comment by maxikuzmin** [comment]
@GlitchHopAnonymous the issue is related to the system WebView, due to the recently added Private Browser. We have already fixed this issue in version 4.7.1, please check for WebView updates on your device system

**Comment by GlitchHopAnonymous** [comment]
Im sorry but this issue is not closed. I just tried upgrading to v4.7.1 again & it is still crashing. My Webview is completely up to date. Additionally, I downloaded the Beta, Dev, & Canary Builds of Webview to see if that worked & it still crashed.

I have a system record & debug log from when I tried upgrading again today. Where do you want me to send them?

**Comment by maxikuzmin** [comment]
@GlitchHopAnonymous I apologize for the long reply, let's continue the discussion in the new issue you opened on this topic

**Comment by GlitchHopAnonymous** [comment]
Its all good no worries. Sounds good will do.
