### ISSUE TITLE
Adguard fails to detect HTML on some websites

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#554]
More info here:
https://forum.adguard.com/index.php?threads/help-needed-with-ui-modification.10247/

http://m.comic.naver.com/webtoon/weekday.nhn?week=sun
m.naver.com

One more example:
http://www.jurnalu.ru/online-reading/comicsonline/injusticegodsamongus/injusticegodsamongusyeartwo52014021

**Comment by confessor-adguard** [comment]
And there are more examples:
https://github.com/AdguardTeam/AdguardForWindows/issues/1084

**Comment by ameshkov** [comment]
Done

Review ID:
CR-AG-767
