### ISSUE TITLE
Adguard compatibility with Transmission Remote GUI app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#555]
Adguard in proxy mode may interfere with Transmission Remote GUI apps work. Needs to be tested.

Originally from this thread: 
https://forum.adguard.com/index.php?threads/10249

**Comment by vbagirov** [comment]
Also might be issues with images uploading to Instagram, also needs checking.

**Comment by ameshkov** [comment]
Downloading

**Comment by vbagirov** [comment]
Wasn't able to reproduce.
