### ISSUE TITLE
Youtube player "Full screen is unavailable" snack

### ISSUE THREAD

**Issue by xKarlberg** [AdguardTeam/AdguardForAndroid#5550]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.7.1

### Environment

- OS version: Android 14
- Device: Oneplus 8T

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Share Youtube video from Youtube to Adguard player.
2. Tilt phone to enter fullscreen
3. Get "fullscreen not available" box

### Actual Behavior

I started using Adguard player instead of buying Youtube premium so I get no ads. But recently I've started getting a box when I tilt the phone to fullscreen that says "Fullscreen not available". To make it go away I need to exit fullscreen then make it fullscreen again. Really annoying and hope you guys can fix this.

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_2024-12-20-04-05-13-47_a93965f46c4a4b0ed1be737bdf2bc8fc](https://github.com/user-attachments/assets/7fd9df70-44ed-4f7e-be28-388efd67f345)

</details>

**Comment by maxikuzmin** [comment]
@xKarlberg this snack appears depending on the video: some videos have the snack, some videos don't. Globally - this snack is "Full screen is unavailable", it's YouTube content and we can't affect it, we stream all YouTube content and can't sort it
