### ISSUE TITLE
Need some filters to power up Adguard Ultimate.

### ISSUE THREAD

**Issue by p6797** [AdguardTeam/AdguardForAndroid#5552]
### Issue Details

Hey TeamAdguard, we need some Ublock Origin own filters not separate filters but in added filters in Adguard filters.
Note* I am want Ublock Origin own filters not Easy list, Easy privacy etc I'll mentioned later.

**Reason to add in Adguard Filters not to add Separate filters: Because Ublock Origin developer mentioned that it optimized with Easy list, **Also in my case I find too that it can't able to use all filters or even near all of the list I think these 5 filters have 58K something rule.**

Why we need Ublock Origin own:- 

Why?: 1. Because some websites still able to show ads like pop-up ads like 1337x where we are trying to click on specific file but because of it already load pop-up ads show when we click on that it, open a new tab :(
2. Even Adguard private browser which is introduced in latest version not able to block youtube ads in my case with default filters (Adguard Base, Mobile filters, Tracking protection, Adguard Social, Online malicious Block list)

But these problems solved in my case when I am using Ublock Origin Own filters.

### Proposed solution

Add Ublock Origin own filters to your list too, We don't need separate filters like Adguard added Ublock Origin Badware filters in security.

I am going to mentioned which Ublock Origin own filters need to be added to Adguard list too, because it is also open source.

1. Ublock Origin filters Ads
"https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/filters.txt"

2. Ublock Origin filters - Badware Risk
"https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/badware.txt"

3. Ublock Origin filters - Privacy 
"https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/privacy.txt"

4. Ublock Origin filters - Quick Fixes
"https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/quick-fixes.txt"

5. Ublock Origin filters - Unbreak
"https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/unbreak.txt"

**Comment by maxikuzmin** [comment]
@p6797 I checked the 1337x website, but I didn't see any ads. Maybe because of the added filters you have conflct, please try to export the settings, then do a "Reset to default" and check the 1337x website again? 
What about YouTube- now there is indeed a problem for Private Browser, this problem will be fixed in the 4.8 update

**Comment by p6797** [comment]
Thank you
