### ISSUE TITLE
Increased batter usage since 4.6.88, specifically overnight

### ISSUE THREAD

**Issue by Ali13798** [AdguardTeam/AdguardForAndroid#5553]
Hello Adguard team. I use the Adguard app on android 14 in VPN mode. The most recent version of the app where this issue is not present, to my knowledge, is 4.6.88. 

A few versions after 4.6.88  I updated the app which caused an increase to the battery usage, especially overnight when the screen is off for a long period of time (to a point that the battery went completely dead if not plugged in, whereas before it would only drop a few percentage points on a 5000 mAh battery). So I had to downgrade to the 4.6.88 version after uninstalling the app which fixed that issue. 

Recently I updated the app to the 4.7.179 version, where the same issue seems to be present. I realize it is not much to go on, but I wanted to point it out to you in case it has gone unnoticed otherwise. The existing issues suggest some battery usage problems are already fixed but I think this might still be unresolved. Anyways, thanks for your time and have a nice day.

**Comment by Versty** [comment]
@Ali13798 Thank you for reporting! 

We are aware of this issue and are investigating the cause. Please continue in the https://github.com/AdguardTeam/AdguardForAndroid/issues/5505
