### ISSUE TITLE
[HTTPs] MTS Music doesn't work when HTTPs is being filtered

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#559]
https://play.google.com/store/apps/details?id=ru.mts.music.android&hl=ru

Приложение ошибки не выдает, кеширование треков просто не начинается. Проблема появляется после включения фильтрации HTTPS.

XHJ-386-81450

**Comment by evgeniy-ADG** [comment]
решилось добавлением в преф.нет.эксклюжнс

**Comment by ameshkov** [comment]
А в https исключения?

**Comment by Revertron** [comment]
Client alert raised. Level: fatal, Description: protocol_version protocol_version(70), Message: Failed to read record
Adding endpoint ru.mts.music.android_213.180.193.201_443_social.yandex.ru to exceptions due to class java.io.IOException: Internal TLS error, this could be an attack

**Comment by Revertron** [comment]
Не могу проверить, ибо не клиент МТС :-/

**Comment by ameshkov** [comment]
@Revertron ну может в хттпс исключения пока что просто?

**Comment by Revertron** [comment]
Добавил.
