### ISSUE TITLE
[HTTPs] Outlook mobile app shows several 'Connection's failed' messages on startup

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#560]
https://play.google.com/store/apps/details?id=com.microsoft.office.outlook&hl=ru

![image](https://cloud.githubusercontent.com/assets/15856304/15337400/35eab3c6-1c84-11e6-971c-897b66cd48bb.png)

It's gone if you disable HTTPs filtering. Also it's gone if you retry 3-5 times.

**Comment by ameshkov** [comment]
I bet we should add "login.live.com" to the https exceptions list.

**Comment by Revertron** [comment]
login.live.com & apis.live.net

**Comment by TheHasagi** [comment]
duplicate #498
