### ISSUE TITLE
ServiceManager handle Critical error event: Deadlock

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#563]
"иногда возникает критическая ошибка,после перезапуска включается вновь"

please refer to TICKET ID QHU-650-54451 for logs

**Comment by ameshkov** [comment]
Log is empty in that ticket. Please ask user to send one more message.

**Comment by ameshkov** [comment]
Log is empty in that ticket. Please ask user to send one more message if this issue occurs.

**Comment by vozersky** [comment]
Ok, I've contacted user, thanks.

**Comment by ameshkov** [comment]
Any update on this?

**Comment by vozersky** [comment]
I'm afraid no, customer hasn't replied.

**Comment by vozersky** [comment]
outdated
