### ISSUE TITLE
Crashes on Xiaomi Redmi with a custom rom when open multiple links in FF

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#564]
Refer to MIT-164-69973, we have full logs there.

I want to report that adguard for android is automatically close while launching multiple urls using firefox. I notice it when firefox cannot establish connections and adguard disappeared in status bar. My current system: Xiaomi Redmi 1s Temasek 6.0.1 ROM Custom Kernel (Linux 3.4.0 god's Kernel) Please contact me in my email if you need any info. Thanks.

**Comment by ameshkov** [comment]
@evgeniy-ADG @vozersky 

Please contact user and ask the following questions:
1. What is the "notification icon" setting value? Could it be that it is set to "None"?
2. If it is **not None**, then I need to see logcat log.

It seems that the app is simply killed by Android, the question is why.

**Comment by vozersky** [comment]
Will do

**Comment by ameshkov** [comment]
Any update on this?

**Comment by vozersky** [comment]
Nope, user hasn't replied yet.
