### ISSUE TITLE
Compatibility issue with Feedly app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#566]
Source:
https://www.reddit.com/r/Nexus6P/comments/4k2uyx/thoughts_on_adguard/d3bx8x2

https://play.google.com/store/apps/details?id=com.devhd.feedly&hl=en

**Comment by Revertron** [comment]
It works perfectly for me. Authenticated by twitter, not google if it matters...

**Comment by ameshkov** [comment]
HTTPS?

**Comment by e13bb4dac2** [comment]
I have no issues with feedly (google log in) and Adguard. (galaxy S7 edge, filter adds enabled in fw, HTTPS filtering active, no feedly specific stuff in whitelist either)

**Comment by Revertron** [comment]
Okay, then we fixed it in 2.6, closing.
