### ISSUE TITLE
Amazon subscription issue. 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#568]
"I have a Amazon subscription i reinstalled the app and it says I don't have premium account, I tried restoring purchases still nothing, I tried to buy again to see if that worked and nothing.
I cleared data, reinstalled everything still not working if I go into Amazon account it says my subscription is active."

**Comment by vozersky** [comment]
Looks like we need to provide appropriate logging tool for Amazon subscription situations.

**Comment by vozersky** [comment]
Please refer to TICKET ID VOT-926-99829 for logs

**Comment by ameshkov** [comment]
Any update?

**Comment by TPS** [comment]
Just to ask an obvious question: do they have the _correct_ AG app installed?  Amazon has 2 — test & release — & subscriptions for each are independent!

**Comment by vozersky** [comment]
@TPS independent subscriptions? thanks for the tip

**Comment by TPS** [comment]
@vozersky https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-140069504 pt#5 details this. ☺

**Comment by TPS** [comment]
Any luck?  I got my recent issues resolved, & my subscription's still functional.…

**Comment by vozersky** [comment]
Well, no reply so far. 
Since there only was a single report of this kind, it could really be a confusion with test and release versions.

**Comment by ameshkov** [comment]
Let's close it then.
