### ISSUE TITLE
Fiddler can't decrypt HTTPS traffic through Adguard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#569]
The problem is that Adguard creates a HTTP CONNECT tunnel to the remote IP and the certificate created by Fiddler uses IP address as a domain name.

To fix this issue Adguard should somehow pass domain name to Fiddler.

**Comment by ameshkov** [comment]
To fix this issue you should change Fiddler settings:
1. Open View -> Tabs -> Preferences
2. Add or edit **fiddler.network.https.SetCNFromSNI**, set it to **True**
3. Profit

Relevant link:
http://www.telerik.com/forums/need-help-reading-https-traffic-from-android-app
