### ISSUE TITLE
com.automattic.simplenote won't sync when HTTPs is being filtered

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#570]
Суть проблемы в блокировании синхронизации контента.

Создаю заметку в Simplenote на смартфоне с Adguard 2.5
https://play.google.com/store/apps/details?id=com.automattic.simplenote
Она не синхронизируется с десктопным/веб-приложением Simplenote
https://app.simplenote.com

То же самое и в обратном направлении.
Как только выключаю Adguard — мгновенно происходит синхронизация.
Пробема возникла после включения фильтрации HTTPS.

**Comment by Revertron** [comment]
Adding domains `auth.simperium.com` and `api.simperium.com` fixes this issue.
