### ISSUE TITLE
Compatibility issue with Samsung Theme Store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#571]
Source:
http://forum.xda-developers.com/showpost.php?p=66943264&postcount=1202

Seems to be an issue with https filtering.

**Comment by Revertron** [comment]
Asked the user for packageName of this Store. I can't find it on Internet, and our G7 hasn't it.

**Comment by Revertron** [comment]
isu-odc.samsungapps.com

**Comment by ameshkov** [comment]
@Revertron are you sure?

According to the screenshot package name is different:
http://dl-1.va.us.xda-developers.com/3/7/5/9/7/4/5/Screenshot_2016-05-23-13-45-21.jpg?key=NjJ3klDXxwIpKTmHMqmPBA&ts=1464080543

**Comment by Revertron** [comment]
@ameshkov I've debugged it on or S7 and that was the domain (not package name).
And adding that domain really fixed the issue.
