### ISSUE TITLE
Changing DNS servers stops Adguard from blocking YT ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#572]
Adguard's latest beta version (2.6.23)
DNS servers were changed to 8.8.8.8, 8.8.4.4

Source:
http://forum.xda-developers.com/showpost.php?p=66959246&postcount=1214

**Comment by Revertron** [comment]
How can it be related in the first place? O_o

**Comment by ameshkov** [comment]
Who knows

**Comment by Revertron** [comment]
It may resolve IPv6 addresses for Googles domains. Since we don't know the filtering mode user uses I can assume that the problem was on root-proxy mode.

**Comment by ameshkov** [comment]
As he use AG to change DNS, apparently he uses VPN mode:)

Let's close this as "cannot reproduce" for now.
