### ISSUE TITLE
Limit the number of license check and filter update requests

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#574]
Currently they are too irritating with ~5 notifications a day.

Original request:
https://forum.adguard.com/index.php?threads/adguard-%D0%B4%D0%BB%D1%8F-android-%D0%91%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-2-6-23.10581/#post-83803

**UPD:** we don't have any "license expiring" notifications (why so btw?). So in this issue we'll do another useful thing: limit the number of license check requests.

Usually we do such request once in 12 or 24 hours. The problem is that currently when app is killed and restarted, timer is started over and first license check is scheduled on +5 min.

**Comment by Revertron** [comment]
But this is not our notification :-)
![screenshot_2016-05-23-12-20-39](https://cloud.githubusercontent.com/assets/105154/15704838/1196ffee-27f5-11e6-9c20-5077d9e96afb.png)
We do not have such icon and text.

**Comment by ameshkov** [comment]
Huh, do we have any notification?:)

**Comment by ameshkov** [comment]
Nevertheless, we should limit the number of any requests to our server.

Currently we just do it periodically once in 12 or 24 hours. The problem is that if our app is killed by Android, timer is started over and first request is scheduled on +5 mins.

**Comment by Revertron** [comment]
Nope. I think we should make some :)

**Comment by ameshkov** [comment]
Haha, nice:)

**Comment by ameshkov** [comment]
Let's schedule it on v2.7 release.

**Comment by ameshkov** [comment]
@Revertron not this issue, make a separate one.

This one is renamed to "Limit the number of license check and filter update requests"

**Comment by Revertron** [comment]
Ah, okay.

**Comment by TPS** [comment]
My 2¢:  If y'all don't mind (especially since #611 will probably increase server load some, anyway), but even 12 hours is probably too long an interval for a _manual_ check. I can sometimes request a filter update _1_ hour apart from my last 1, & get an update to _several_ lists.  (The English & German lists seem to have frequent updates!)  Limiting the _automatic_ checks ___only___ would be _my_ preference.

**Comment by ameshkov** [comment]
@TPS I mean the periodic automatic update check, manual have no limitations.

**Comment by Revertron** [comment]
Done!
