### ISSUE TITLE
Adguard automatically starts despite having autostart box unchecked in settings.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#577]
please refer to GHU-832-56315 for logs and details

**Comment by vozersky** [comment]
I've just got an update from the user.
After reinstalling Adguard (the same build 2.1.196) the issue was gone.

**Comment by ameshkov** [comment]
Yep, the issue was introduced in v2.5

**Comment by Revertron** [comment]
Didn't we fix it?

**Comment by ameshkov** [comment]
Nope

**Comment by ameshkov** [comment]
Closing as we cannot reproduce it.
