### ISSUE TITLE
Significant battery drain with Adguard 2.5 and 2.6 beta. No such problem in 2.1.

### ISSUE THREAD

**Issue by bentrop** [AdguardTeam/AdguardForAndroid#578]
As discussed here:

https://forum.adguard.com/index.php?threads/adguard-extremely-high-battery-use.9536/

Battery consumption of Adguard has increased massively in 2.5.x. It's consistently by far the highest consumer according to Android's battery stats. 35% and higher, far more than WiFi, cellular standby and display combined. It has a very notable impact on overall battery life and more than halves it for me.

Disabling https blocking does not fix the issue.
Disabling the firewall does not fix the issue.
Switching to High-Speed filtering does not fix the issue.
Enabling the DNS request filter does not fix the issue.
Upgrading to 2.6.63 beta does not fix the issue.

Downgrading to 2.1.359 fixes the problem instantly and battery life is back to normal.

This problem started with 2.5.x.

Affected device: Moto X Play, Android 6.0.1, stock, unmodified, not rooted.

**Comment by ameshkov** [comment]
@bentrop hi! answered you on a forum thread:
https://forum.adguard.com/index.php?threads/adguard-extremely-high-battery-use.9536/#post-83974

**Comment by ameshkov** [comment]
https://blog.adguard.com/en/ad-blocking-and-battery-usage/
https://blog.adguard.com/en/great-battery-saving-mode-of-adguard-for-android/
