### ISSUE TITLE
Add "renew license" button for non-lifetime licenses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#581]
Currently there is no way to renew the license.

**Comment by ameshkov** [comment]
Important points:
1. Do not show this button it when we don't have a license key saved in preferences
2. Do not show this button for lifetime license keys

**Comment by Revertron** [comment]
Done from client-side.

**Comment by ameshkov** [comment]
Serve side is out of this issue's scope, so closing it.
