### ISSUE TITLE
HTTPs filtering issues on Android N

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#583]
https filtering makes many websites unusable. many websites get blocked in Chrome ("not trustworthy" or something, but while I can tap on advanced and "visit this site anyway" on some websites, others (like https://www.google.com/url?sa=t&rct=j&source=web&q=&url=http://www.heise.de/newsticker/meldung/Google-I-O-Hintergrund-Updates-von-Android-N-beheben-nicht-die-Update-Problematik-3211383.html&usg=AFQjCNHiVs0ERU8eegOX7QwBaOTgLhp4Ww just now) cannot be visited because of them using HTSP. Whatever that is. disabling HTTPS filtering immediately solved the problem.

Logs: WYN-237-97069
Logs, screengrabs: IHZ-623-60526
The same issue: ANF-409-74964

**Comment by evgeniy-ADG** [comment]
Not sure, maybe it should be added to one of existing tasks. Please merge if needed.

**Comment by ameshkov** [comment]
Chrome that ships with Android N does not "trust" the user certificate. I suppose this issue will be fixed in future Android builds.

For instance, Chrome Beta or Chrome Dev from the play store work as they should (and both are newer than the Chrome inside DP3).
