### ISSUE TITLE
ru.rambler.mail

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#588]
https://play.google.com/store/apps/details?id=ru.rambler.mail
блокирует вход в почту рамблер и блокирует обновления писем:
http://prntscr.com/b859gt
http://prntscr.com/b859jm

Помогает только отключение защиты

Логи - ANP-629-18750

**Comment by ameshkov** [comment]
@Alex-302 можешь посмотреть?

**Comment by Alex-302** [comment]
Да, проверю.

**Comment by Alex-302** [comment]
@ameshkov похоже фильтрация HTTPS ломает.
Снял полный лог и HTTP запросов
[adguard_full.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/298782/adguard_full.txt)
[adguard_http.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/298783/adguard_http.txt)

**Comment by ameshkov** [comment]
Added ru.rambler.mail to ssl exceptions.
