### ISSUE TITLE
Add Fanboy's Vietnamese

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#589]
https://www.fanboy.co.nz/fanboy-vietnam.txt

**Comment by ameshkov** [comment]
@mmigi take care of the server side please

**Comment by mmigi** [comment]
Our server side feels better and Vietnamese filter joined to others.

**Comment by ameshkov** [comment]
That's not all, not it's time to add this to AG for Android.

**Comment by ameshkov** [comment]
Done
