### ISSUE TITLE
No automatic filters updates

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#59]
http://forum.adguard.com/showthread.php?6817-%D0%9D%D0%B5%D1%82-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9/page2

**Comment by Revertron** [comment]
Added logging about current network connection. We will see what is going on.
