### ISSUE TITLE
Between app https filtering incompatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#591]
https://play.google.com/store/apps/details?id=kr.co.vcnc.android.couple&hl=en

Source:
https://forum.adguard.com/index.php?threads/https-filtering-interrupts-messaging-in-between-app.10732/

> It does not load new messages nor send new messages.
> As I remember, there was no problem with this app when I was using Adguard 2.5.

**Comment by vbagirov** [comment]
I wasn't able to reproduce it, though - I could both send and receive messages with v.2.6.23 and HTTPs filtering enabled.

**Comment by vbagirov** [comment]
Happened to user again, here are logs:
http://pastebin.com/991B1wKK , http://pastebin.com/jvYetnw8

**Comment by Revertron** [comment]
We may add `api-between.vcnc.co.kr` to ssl exceptions and close it.

**Comment by vbagirov** [comment]
According to user, adding `api-between.vcnc.co.kr` to ssl exceptions doesn't help:
https://forum.adguard.com/index.php?threads/https-filtering-interrupts-messaging-in-between-app.10732/#post-85196

**Comment by ameshkov** [comment]
Disappeared again.
