### ISSUE TITLE
HTC One M8 - Adguard doesn't restore filtering after a voice call

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#592]
Во время звонка пропадает Интернет, программа уходит на паузу, после завершения звонка защита не восстанавливается. Хотя инет есть. 

Лог вот тут PMH-145-99165, попросили еще один с beta

**Comment by ameshkov** [comment]
Да, ты был прав, это связано с предыдущим исправлением. Закрою как дубликат все же.
