### ISSUE TITLE
Compatability and battery drain.

### ISSUE THREAD

**Issue by razz100** [AdguardTeam/AdguardForAndroid#596]
Please try to fix following issues in the new build:
1. Compatability with DBS bank app (Indian version). The app does not work when https is enabled.
2. Since version 2.5 to present beta, adguard sadly has become a major consumer of battery. The issue needs to be looked into and be fixed ASAP.

Thanks

**Comment by ameshkov** [comment]
Hi!

1. Could you please give a link to Google Play?
2. To find out the cause I need more info, details are here:
https://forum.adguard.com/index.php?threads/adguard-extremely-high-battery-use.9536/#post-83974

**Comment by razz100** [comment]
Thanks for the reply. :)

1. Here is the link of that bank https://play.google.com/store/apps/details?id=com.dbs.in.digitalbank&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Ddigibank+india&pcampaignid=APPU_19_BoFMV_KRBYXTvATQvb_ADw . 

Please look into why Adguard stops that bank app from working in HTTPS mode.

2. I will see how I can help here. But high battery usage is indeed a issue with latest version.

Thanks

**Comment by TPS** [comment]
_(Just FYI: Pt#2 is #578.)_

**Comment by ameshkov** [comment]
https://blog.adguard.com/en/ad-blocking-and-battery-usage/
https://blog.adguard.com/en/great-battery-saving-mode-of-adguard-for-android/
