### ISSUE TITLE
Add ability to add shortcut to toggle the adguard on/off

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#599]
User wants to put the shortcut in a home screen folder and that can't be done with widgets.

He suggests to parse the intent data for the "toggle shortcut" and if its already running stop it or visa versa. The "toggle shortcut" could be created from within the app itself to the home screen.

The toggle shortcut would just contain a flag so you'd know it was a toggle versus the regular shortcut.

More details here - YAX-575-57417

**Comment by ameshkov** [comment]
Duplicate for #123
