### ISSUE TITLE
Block IPv6 in proxy+auto filtering mode

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#601]
Since IPv6 can't be routed to our proxy in root-proxy mode as we see in #580 and we have a trouble with filtering IPv6 when there is IPv6 network on Wi-Fi and Mobile as in #142 we are introducing blocking IPv6 traffic.

We must add low-level settings for user to be able to control this behavior - pref.net.block_ipv6 and pref.net.always_filter_ipv6.

**Comment by ameshkov** [comment]
pref.proxy.block.ipv6

**Comment by Revertron** [comment]
Okay, I've made blocking of only external connections. Added the option to low-level group.
