### ISSUE TITLE
Opera Max

### ISSUE THREAD

**Issue by mark75to** [AdguardTeam/AdguardForAndroid#602]
Hi to all,
I have installed latest adguard beta release and it doesn't works with opera max.
Adguard is configured in proxy mode. If I disable OperaMax all works good.

**Comment by ameshkov** [comment]
Hi! You mean ads are not blocked when Opera Max is working?

**Comment by mark75to** [comment]
Yes, is correct. When Opera Max is active ads are not blocked.

**Comment by ameshkov** [comment]
Hm, you use Proxy+Automatic setup (with root), right?

**Comment by mark75to** [comment]
No. I’m use Proxy + Manual setup. My device is not rooted.
Proxy is setting on 8080
It works good if I disable opera max. There are no difference if I’m in Wi-Fi or 3G/4G

**Comment by ameshkov** [comment]
It won't work in manual setup as it is an app who makes the decision if proxy settings should be used or not.

Opera Max apparently decides to ignore proxy settings.

**Comment by mark75to** [comment]
uhmmm....if I understand correctly Adguard as a proxy + vpn works only with root devices...... the problem is that I don't think it is possible. 
I'm using Honor 6 with EMUI 4.0 on Marshmallow :-(

**Comment by TPS** [comment]
@mark75to Can you setup Opera Max as in #51?

**Comment by ameshkov** [comment]
> uhmmm....if I understand correctly Adguard as a proxy + vpn works only with root devices...... the problem is that I don't think it is possible. 

Yep, true, we can't help it without root.

> @mark75to Can you setup Opera Max as in #51?

You know, i've seen an instruction on how to use "Opera VPN" as a socks5 proxy:
https://www.helpnetsecurity.com/2016/04/22/opera-browser-vpn-proxy/

**Comment by vozersky** [comment]
obsolete
