### ISSUE TITLE
Couldn't complete a transaction with Yelp app 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#603]
Hi, I tried to order something with the Yelp app (can be downloaded here: https://play.google.com/store/apps/details?id=com.yelp.android ) but it said "something went wrong", then I disabled Adguard filtering and tried it again, and this time the order succeeded. 

**Here is a filtering log - I started an order around 2:00am. ( http://pastebin.com/tRuL1bRE )**

I have https filtering enabled, and using English filter, Spyware filter, Social media filter, Experimental filter, Mobile ads filter and some filters in user filter.

I don't want to completely turn off filtering for Yelp app, as I think there can be 
Not sure whether this failure of transaction is due to adguard or not, but if so I'd appreciate you give me instructions on how to avoid this or fix it in your side! Thank you.

**Comment by Revertron** [comment]
Ouch! It uses stripe to make transactions. Adding `stripe.com` to ssl_exceptions!
