### ISSUE TITLE
AdGuard for Android Only Speaks ... Polish?

### ISSUE THREAD

**Issue by lloy0076** [AdguardTeam/AdguardForAndroid#604]
My AdGuard for Android only speaks some foreign language:

> Zatista je iskljucena
> Protok Sacuvan
> Blokiranih Reklama

I can't seem to find a way to get it to go back to English.

> Verzija 2.5.196

**Comment by ameshkov** [comment]
Uh, weird. According to Google translate this is Croatian. 

Which language do you have on your device?

**Comment by ameshkov** [comment]
To change the language go to settings, then general (the very first item), then find language selector there (tap on items until you see a huge combobox with all available languages)

**Comment by lloy0076** [comment]
I can't find the settings to change the language...or I would have and I've clicked around a lot; as far as I can tell there is **no** such thing as a setting tab.

**Comment by ameshkov** [comment]
Open menu (top-right corner)
Tap settings (second item from the top)
General (top item)
Tap "Language" (6th item from the top)

**Comment by lloy0076** [comment]
Oh, there it is - I haven't a clue how it got into Croation...

**Comment by ameshkov** [comment]
So, what's your device language?:) I guess we could confuse the ISO codes, then we should fix it.

**Comment by lloy0076** [comment]
Language is "English (United Kingdom)" on the Language & input settings page.

**Comment by ameshkov** [comment]
Huh, weird. In the end it was not Croatian, but Serbian (not sure if there is any difference though).
Just checked the code. Frankly, I don't know how this is even possible:)

**Comment by lloy0076** [comment]
It's a Google Nexus 4.
