### ISSUE TITLE
Make a notification about expiring license

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#606]
If a user has not life-time license key and his key's expiring time is approaching - say 14 days are left, we should show some notification to user so that he/she can renew key.

It can look like this:
![screenshot_2016-05-23-12-20-39](https://cloud.githubusercontent.com/assets/105154/15705562/a218d85a-27f8-11e6-94fb-05beac1882f6.png)

Also, we need to save last time when notification is shown and show it every 2 days may be.

**Comment by TPS** [comment]
#605?

**Comment by ameshkov** [comment]
Yep, #605 is a duplicate, thank you:)

**Comment by ameshkov** [comment]
It should different for Trial period and for users who has purchases a license key.

So, for Trial period:
1. 3 days before trial period is expired.
2. 1 day before trial period is expired.
3. Expired

For "premium" users:
1. 14 days before license is expired
2. 1 day before license is expired
3. Expired

**Comment by ameshkov** [comment]
@nkartyshov one more note: all these notifications should lead to "Get Premium" activity (instead of the main activity as it does now).

**Comment by nkartyshov** [comment]
done

**Comment by TPS** [comment]
Ever since this landed, I get the notification _every_ day on [my tablet that I run in free proxy-mode](https://github.com/AdguardTeam/AdguardForAndroid/issues/50#issuecomment-142479859).  I could understand once a week or month, but every _day_ is a little (lot) obnoxious!

**Comment by ameshkov** [comment]
@TPS this is really bad. Could you please take a screenshot of that notification?

@Revertron please take a look at the code. What's wrong with it? Could it be that in case of Amazon version we are doing something wrong?

**Comment by Revertron** [comment]
Okay, I see 2 bugs there:
1. Our DateHelperUtils.getDaysDiff() is rounding **up** the difference in days.
2. The expired notification is shown every 12 hours.

What should I do?

**Comment by ameshkov** [comment]
> 2. The expired notification is shown every 12 hours.

You mean every 12 hours?

The notifications described in this comment must be shown once:
https://github.com/AdguardTeam/AdguardForAndroid/issues/606#issuecomment-232620274

There should be some sort of protection from showing such notification more than once.

**Comment by TPS** [comment]
I think (obviously) showing such a nagscreen… err, nag*notification* (?) every 12 hours is too often, but it honestly doesn't need to be once ever, either.  Tone it down to 1st&15th or 10th&24th of each month (just to split difference between weekly & monthly), & perhaps make the wording more fun/persuasive, & you all will drive ptemium subscriptions without driving users away.

Bonus:  If you put the nag info into an updating internal subscription, you can update 2× monthly it to include info on new features, promotions, &c, to make us want it more. :wink:

**Comment by ameshkov** [comment]
I meant it should be once for each of the key dates, e.g.: 14 days before expiration, 3 days, 1 day and one time after the expiration.

**Comment by Revertron** [comment]
New version is here, you cat test it, @TPS :
[adguard-2.7.212rc.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/407311/adguard-2.7.212rc.zip)

**Comment by TPS** [comment]
What should I be/not be looking for, precisely?  Is it set to notify once & never again, or periodically?

**Comment by ameshkov** [comment]
> What should I be/not be looking for, precisely? Is it set to notify once & never again, or periodically?

As I understand you should see this notification one time and no more after that.

**Comment by ameshkov** [comment]
@Revertron I wonder how we check on our side that now it is fixed for good (without waiting for a day)?

**Comment by Revertron** [comment]
1. Make a premium key for 1 day
2. Activate some device (with fixed rc version) with that key
3. Build new apk that will increment the date going from server by one day, install it over previous one.
4. Check license, get notification that license is expired
5. Make another build that will increment date from server by two-three days - check license again.

Does it sound like a plan?

**Comment by TPS** [comment]
@Revertron @ameshkov I've installed all ßs from last 36 hours or so:  Received "Expired" notification 1×.  I'll now wait 12 to 24 hours more, & see whether it repeats.

**Comment by vozersky** [comment]
id 1373702

"I had to uninstall the adguard from my phone since it started to inform
me daily that premium stuff is no longer available, even tho I never have
had the premium version of the adguard. This happened after moving from
normal release to the beta release."

**Comment by ameshkov** [comment]
@vozersky the issue is fixed in the latest RC.

**Comment by evgeniy-ADG** [comment]
Ok, I'll send him another follow up )

**Comment by TPS** [comment]
For the record: no more upgrade notifications!  Thanks, @AdGuardTeam.

**Comment by Revertron** [comment]
Okay.

**Comment by ameshkov** [comment]
@TPS thanks for testing it!
