### ISSUE TITLE
Add 'com.tmobile.pr.mytmobile' to default exclusions

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#607]
https://play.google.com/store/apps/details?id=com.tmobile.pr.mytmobile - does not work with Adguard unless added to 'pref.net.exclusions'

Original thread:
https://forum.adguard.com/index.php?threads/t-mobile-us-app-doesnt-work-solution-in-thread.10821/

**Comment by Revertron** [comment]
May be we need just exclude it from HTTPS filtration. Asked user on the forum, waiting for reply.

**Comment by Revertron** [comment]
Done.
