### ISSUE TITLE
Bluetooth tethering doesn't work with Adguard in VPN mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#608]
![image](https://cloud.githubusercontent.com/assets/15856304/15747862/4e6381cc-28e5-11e6-962d-f0426f96959e.png)

Works fine with proxy mode.

**Comment by ameshkov** [comment]
Yep, VPN limitation.

That's why we turn AG automatically when tethering is detected. However I am not sure if it is possible to detect bluetooth type of tethering.
