### ISSUE TITLE
com.jet.jet.app is broken with HTTPS filtering

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#612]
https://play.google.com/store/apps/details?id=com.jet.jet.app&hl=en
NNJ-794-74853

**Comment by gshumihin** [comment]
Might be jet.sc.omtrdc.net and m-batman-api.jet.com
Jet.jet.app doesn't work for me even without Adguard. Looks like this app won't work in Russia.

@Bohdan-SUP узнай у пользователя, пожалуйста, помогает ли добавление указанных доменов.

**Comment by Bohdan-SUP** [comment]
Отписал юзеру.

**Comment by shaurmanchic** [comment]
User reported that adding these domains doesn't seem to help. Jet still gives server error.

**Comment by gshumihin** [comment]
I think we should add com.jet.jet.app to application whitelist than.

**Comment by Revertron** [comment]
Added com.jet.jet.app to ssl exceptions.
