### ISSUE TITLE
Add Puffin to exceptions

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#614]
Puffin browser (pkg name: com.cloudmosa.puffin) connects to websites via middle-man servers in US, which made Adguard impossible to filter its traffic. 

User suggests that Puffin should be put into exception list.

User ID - 972462

**Comment by ameshkov** [comment]
Hm, I though Puffin is in "conflicting browsers" list already

**Comment by Bohdan-SUP** [comment]
It is, and Adguard gives me notification that it's not supported.
But I still have option to turn ad filtering on/off:
![screenshot_2016-06-06-08-14-22](https://cloud.githubusercontent.com/assets/14153331/15812560/0b8a9840-2bbf-11e6-9928-3834e69b314e.png)

**Comment by ameshkov** [comment]
Why not?
