### ISSUE TITLE
Add option to block data connection when device is locked.

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#616]
"Have the option to program the lock access of internet applications when the screen is off. The user
choose which applications are blocked from accessing the internet when the device screen is turned off. When the screen is activated again access is released. "

User 1252934

**Comment by ameshkov** [comment]
Duplicate for #268

**Comment by TPS** [comment]
More correctly, duplicate for #176, per #268. 😉

**Comment by Bohdan-SUP** [comment]
Oops, sorry.
