### ISSUE TITLE
Multiple proxy settings configurations

### ISSUE THREAD

**Issue by Snake87r** [AdguardTeam/AdguardForAndroid#617]
In setting Advance Proxy, add the possibility to Save Proxy configuration with a name, with this you can change the Proxy with only a click and not change every time the complete configuration.
Example: you can create many Proxy with a name like "USA Socks5 Proxy", "Sweden Socks5 Proxy" etc.. and change between them with only 1 click without have to change port, server address username and password..

**Comment by ameshkov** [comment]
Nice idea! There also should be some widget allowing a fast change between these configuration sets.

**Comment by TPS** [comment]
For clarity: Can this be renamed "[Enhancement] Save _Multiple_ Proxy Configurations"?  Excellent RFE, @Snake87r!

**Comment by ameshkov** [comment]
Done in v2.10
