### ISSUE TITLE
A page display delay on Android

### ISSUE THREAD

**Issue by Joss** [AdguardTeam/AdguardForAndroid#618]
Sometimes a page full loading takes a lot of time.
The example: [URL](http://4pda.ru/pages/go/?u=http%3A%2F%2Fsurfingbird.ru%2Fsurf%2Fkak-prigotovit-idealnyj-borshch--v8Vi7A66E%3F_auth%3D7ERpg_oq2UdHlkBDoXIoQg%242b6a25cc6d177e49db001584025a9925e6397b5e%26utm_campaign%3Dnewsletter_2016-06-03%26utm_content%3Dteaser5%26utm_medium%3Demail%26utm_source%3Dnewsletter&e=50126145)

w/o Adguard full page loading time ~ 3s.
with Adguard (with any settings, VPN/Proxy no matter) it takes about 15s (first part of page rendering within 2s, but you can scroll down the page only through 15s)

Adguard 2.6.67 beta 
Android 6.0.1, HTC One M8, Sense custom ROM.
[4pda link](http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=50126145)

**Comment by ameshkov** [comment]
You were right opening this issue in AdguardFilters repo. It seems that page scroll is messed up with AG filters. It goes normal after ~15sec.
