### ISSUE TITLE
Internet speed drop

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#62]
With Adguard in VPN mode WiFi speed drops (any app using WiFi suffers performance decline). Browser doesn't matter, user has McAfee antivirus and Security installed.

https://www.dropbox.com/s/2malg3dgh5h6l11/State_EXB-181-35381.txt?dl=0 - state.txt
https://www.dropbox.com/s/7wc53btk3xcwyub/Log_EXB-181-35381.txt?dl=0 - debug.txt

EXB-181-35381

**Comment by ameshkov** [comment]
I think we should introduce MTU setting in "Low level settings" section and ask user to test it with greater MTU values.

**Comment by Revertron** [comment]
The build is ready: https://cloud.jamm.me/index.php/s/eIfKpKhwV7tYvIn

**Comment by ameshkov** [comment]
You should also provide instructions on what user should do (which values he should try)

**Comment by ameshkov** [comment]
Closing this issue as "pref.vpn.mtu" is implemented already.

Further improvements are possible after we finish with this task:
https://github.com/AdguardTeam/AdguardForAndroid/issues/228
