### ISSUE TITLE
Yandex Maps do not show traffic information

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#620]
https://play.google.com/store/apps/details?id=ru.yandex.yandexmaps&hl=uk

Блокируется загрузка информации о состоянии дорог и объектах в Яндекс.Картах.
http://prntscr.com/bckt71
http://prntscr.com/bckt9s
http://prntscr.com/bcktc1

Помогает только отключение Защиты.
2.6.67

logs: AET-930-60299

**Comment by ameshkov** [comment]
Временное решение: отключить фильтрацию рекламы для этих приложений.
В следующей бете будет исправлено.
