### ISSUE TITLE
YouTube ads still go through

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#621]
Adguard 2.6.67, Android N
Logs - [youtube.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/300120/youtube.txt)
Asked for a HAR, will post here.

**Comment by ameshkov** [comment]
@Bohdan-SUP it's important to get ALL har files recorded since YT app cache and data were cleared.

**Comment by evgeniy-ADG** [comment]
огромное спасибо, после установки бета версии и настройки, реклама с ютуба пропала
  "deviceName" : "UMI IRON", qcrm id 1167711

**Comment by vgavrish** [comment]
versionName" : "2.6.67"
[add_youtube.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/304203/add_youtube.txt)
HAR - id 1134929
![screenshot_13](https://cloud.githubusercontent.com/assets/18548949/15885962/00694038-2d63-11e6-89dc-ebb2d628bd9f.jpg)

**Comment by ameshkov** [comment]
One har file is not enough.

My quote from xda: http://forum.xda-developers.com/showpost.php?p=67186807&postcount=1302

> Regarding the YT app ads, something has changed indeed, so for some users the ads are going through now. The problem is that we cannot reproduce this on our side, it seems that the way they serve ads depends on user location.

> So, to block these ads I need your help. If you see YT ads with the latest beta, please do the following:
> 1. Switch AG https filtering into a "whitelist" mode
> 2. Clear YT app cache and data
> 3. Record HAR files:
> https://kb.adguard.com/index.php?/Kn...android-device 
> 4. Send all har files to me. You can use PM or send it by email to devteam at adguard.com.

> What do i need to know:
> 1. What video were you trying to watch when the ad came up?
> 2. What was the ad about?

**Comment by ameshkov** [comment]
So, if there is a pre-roll ad, I need to get ALL har files recorded since YT app cache and data was cleared.

**Comment by evgeniy-ADG** [comment]
> Attached is the har file from YouTube. I installed the latest beta, went to
> youtube and an ad appeared. I followed the instructions to create the har
<details>
> file and went back to replay the video. I actually had to clear the video
> from my screen and then re-select it to see the ad. Just replaying it had
> no ad, but clearing it and choosing it did show the beginning ad.
> 
> This just started happening a few days ago, only on YouTube and not for
> every video.
> 
> The video is called, "American Gun Laws Facts, 20 Unbelievable Facts" on a
> channel called KYF. It happened first at 6:58 am after installing the
> latest beta. I then read and followed the har file instructions, and then
> re-produced the error.
</details>
Har in the ticket 1048123

**Comment by ameshkov** [comment]
This is no good.

Let's focus at this: I need to get **ALL har files recorded since YT app cache and data was cleared**.

**Comment by ameshkov** [comment]
> Har in the ticket 1048123

In this particular case in the HAR file I see how ad metadata is used, but I don't see how it was downloaded in the first place. It means that the ad metadata was downloaded & cached long before it was shown to user.

**Comment by evgeniy-ADG** [comment]
@ameshkov What do you mean saying "all har files"? Is there some specific instruction to collect them? 
Please check this ticket: 1194589 
Another user provided HAR and some screenshots.

**Comment by evgeniy-ADG** [comment]
1. No video in particular.. Randomly browsing really but noticed that ads appear on fewer viewed video(thousands) as opposed to popular ones (millions)
2. McDonald, Air New Zealand (I live in NZ), Daikin heatpump, KitKat from most to least

har files in are here: 1307066

**Comment by vozersky** [comment]
also here:  1048123

**Comment by ameshkov** [comment]
> What do you mean saying "all har files"?

There are lots of HAR files recorded in a "har" folder.
I mean that we should receive ALL of them to see the whole history.

**Comment by Bohdan-SUP** [comment]
HAR files, screenshots and details - 1315068

**Comment by evgeniy-ADG** [comment]
HAR and description: 1323519

**Comment by vozersky** [comment]
HAR and description also here: 1315082

**Comment by evgeniy-ADG** [comment]
HAR: 1104390
Deleting cache and data doesn't help.

**Comment by vgavrish** [comment]
HAR: 636610

**Comment by ajnao** [comment]
Когда же Вы нас избавите от рекламы в приложении Ютуб ? Столько времени прошло , а воз и ныне там .

**Comment by evgeniy-ADG** [comment]
And here: 1331585, July, 8

**Comment by ameshkov** [comment]
@ajnao сложно все с ютубом, похоже просто фильтрами проблему окончательно не решить.

**Comment by ameshkov** [comment]
@evgeniy-ADG @vbagirov @vozersky enough HAR files for now. The ball is in my court.

**Comment by onejackgold** [comment]
i have a sort turm solution untill the problem is sorted with the latest version. the simple idea is to use an older version of youtube (or use youtube in chrome) such as version 6 which is what im doing. just make sure you uninstall your current version and download extract the attached zip which contains version 6 apk, then sideload it then run adguard before opening youtube and then theres no video ads

[YouTube-com.google.android.youtube-6.0.11-60011301.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/405741/YouTube-com.google.android.youtube-6.0.11-60011301.zip)

**Comment by ameshkov** [comment]
Yeah, it seems that any YT version before May works ok.

For instance this one is ok:
http://www.apkmirror.com/apk/google-inc/youtube/youtube-11-13-55-release/

> just make sure you uninstall your current version

Uninstalling is often not an option (for instance for Nexus devices you can't simply uninstall YT).

In this case you can do the following:
1. Download the apk file
2. Install adb (for instance here is a simple instruction: http://forum.xda-developers.com/showthread.php?t=2317790)
3. Turn USB debugging ON
3. Connect your device and run the following command:
`adb install -r PATH_TO_YOUTUBE_APK`

**Comment by eender** [comment]
Any Updates?

**Comment by ameshkov** [comment]
@eender there are plenty of updates, but no good news yet.

Ads are now double-encrypted and we didn't find a good way to get rid of them.

**Comment by ministr91** [comment]
А сейчас как дела обстоят? Есть новости?

**Comment by 28Black** [comment]
I just updated my YouTube app because even in the older versions the ads started to appear. 
I wonder how the xposed module works to block the ads, it works flawlessly on my cellphone. But on my unrooted tablet I have to deal now with the annoying ads.
Are there any news regarding this ?

**Comment by ameshkov** [comment]
@28Black xpose module uses a very different approach to ad blocking.

We are considering using the same way to block YT ads at least for rooted users.

**Comment by 28Black** [comment]
Bad news, since I can't root my tablet (Samsung with eFuse-Chip). Older YouTube versions now also show ads, I really hope there'll be a suitable solution soon for us.

**Comment by Lupus-Dei** [comment]
Can confirm. The trick to install an older version of the YouTube app doesn't work anymore. Ads are shown throughout all versions I tested so far (11.07.59 - 11.41.56 arm64 nodpi)

**Comment by ameshkov** [comment]
Everything we know about this is in this post:
https://blog.adguard.com/en/how-to-block-ads-on-youtube-for-android/

The other way is using OGYoutube app.

At the moment, we can't find a better way to get rid of YT ads.
I'll keep this issue open just in case if we find a better solution.

**Comment by BooBerry** [comment]
Just an update, the OGYouTube app has ceased development, so it's not a dependable workaround anymore.

I've experimented with this a little but, but even with root access (and the cert moved to system on Android 7.0), ads in the YouTube app do keep happening. I rarely reboot my phone, so pref.root.clear.youtube isn't much help. What would help is if the pref had a timer to automatically close and clear the app's data, e.g. every day. While a little off topic, but while strangely enough after moving the cert to system 
some HTTPS site won't load correctly, e.g. github.com which I had to add the the HTTPS whitelist.

My workaround for YouTube on Android? Use YouTube in a web browser (Chrome). It works surprisingly well this way, so I don't have to use the YouTube app anymore.

**Comment by ameshkov** [comment]
> While a little off topic, but while strangely enough after moving the cert to system some HTTPS site won't load correctly, e.g. github.com which I had to add the the HTTPS whitelist.

Yeah, that's due to HTTP Public-Key-Pinning which does not work for user certificates, but starts working when you move cert into the system store.

You need browser to "forget" existing pins, so clear the browser data after moving the cert.

**Comment by Bluscream** [comment]
I still use the latest OGYT 3.5 and i hope it will continue to work a while. I heard there is a g+ community for "private" updates

**Comment by Bluscream** [comment]
I think the main issue AG should focus on is cert-pins bypassing at any cost.

**Comment by ameshkov** [comment]
> I still use the latest OGYT 3.5 and i hope it will continue to work a while. I heard there is a g+ community for "private" updates

Do they faced some kind of a legal issue?

**Comment by altokarev** [comment]
There is a report that Adguard does not block ads since yesterday.

Lenovo Yoga and Galaxy S3@Android 4.4. Adguard 2.9.136. High-quality method. Local HTTP Proxy mode.

Some screenshots here: https://forum.adguard.com/index.php?threads/ogyoutube.23698/#post-145996

Has the Google changed something or this issue is unique?

**Comment by jtechpro** [comment]
best of all is to use Youtube on Firefox with uBlock origin/Adguard for Firefox and add a shortcut to homescreen.

**Comment by Bluscream** [comment]
I just found out that google gets their pins from
https://www.gstatic.com/android/config_update/08202014-pins.txt
https://www.gstatic.com/android/config_update/08202014-metadata.txt

Can't you intercept and replace that?

**Comment by Revertron** [comment]
Did you try to just block these urls?

**Comment by Bluscream** [comment]
They're cached and i'm sure google has hardcoded backups

**Comment by Bluscream** [comment]
Also i have apps that unpin certs for me anyway ^^

**Comment by Bluscream** [comment]
They're cached and i'm sure google has hardcoded backups
Also i have apps that unpin certs for me anyway ^^

**Comment by BooBerry** [comment]
I guess it's safe to say Google/YouTube is using the newer player with the double-encrypted ads by default now, so the ads can't be removed anymore?

For the time being at least I added YouTube to a list of apps that AdGuard for Android can't filter and/or remove the ads from.

https://forum.adguard.com/index.php?forums/technical-support-adguard-for-android.77/

I'll wait for confirmation that it's indeed true before updating the thread(s) saying it can't be removed anymore for sure.

**Comment by BooBerry** [comment]
If indeed the ads can't be removed anymore from the YouTube app, it might be time to update and/or bump this blog post: https://blog.adguard.com/en/how-to-block-ads-on-youtube-for-android/

**Comment by vbagirov** [comment]
@BooBerry maybe it'd be better to re-do a research and post a new article.

**Comment by ameshkov** [comment]
I'd better create another issue when I finally find time on this.
