### ISSUE TITLE
mangarock app ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#623]
http://www.mangarockapp.com/definitive.html
http://files.nabstudio.com/mangarock/mangarock-definitive-v2.0.5-RELEASE.apk
Screens: <details>
![screenshot_20160603-082006](https://cloud.githubusercontent.com/assets/14153331/15785666/19f90222-29c1-11e6-80c6-29ab4806f63a.png)
![screenshot_20160603-082035](https://cloud.githubusercontent.com/assets/14153331/15785667/1b8a8232-29c1-11e6-9ae5-751f4b835f59.png)
</details>

**Comment by Alex-302** [comment]
@Revertron Could you please help to block this ad? I can't record a HAR file.
