### ISSUE TITLE
org.leetzone.android.yatsewidgetfree issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#629]
https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree&hl=en

When using any version of Adguard later than 2.1 the app Yatse shows my media center to be offline. Disabling ad filtering and adding to the HTTPs exceptions didn't help. Tried the latest beta but to no avail, sadly.

Logs in the ticket #1253402

**Comment by ameshkov** [comment]
pref.net.excepsions?

**Comment by calisro** [comment]
Weird. My yatse works fine  for 5 media centers.  local and remote. routing issue?

**Comment by ameshkov** [comment]
Yep, it may be a routing issue. By default AG excludes LAN routes from the VPN so it should work.
