### ISSUE TITLE
[Feature request] Add ability to block a particular URL

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#630]
Have the option for me block a url. You could paste or type this URL into the AdGuard to
this URL is blocked. You can enter these functions?

CRM ID 1252934

**Comment by TPS** [comment]
`User filter` setting _isn't_ sufficient for this?

**Comment by ameshkov** [comment]
@evgeniy-ADG what's wrong with user filter?
