### ISSUE TITLE
Web-sockets can't be blocked

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#631]
https://hi-tech.mail.ru/news/microsoft-detect-cancer/
Sample request
`wss://hi-tech.mail.ru/api-proxy/mimic/v1/ws/`
should be blocked by
`/mimic/v1/ws$domain=mail.ru`

**Comment by Alex-302** [comment]
Temporary added to mobile filter:
```
mail.ru#%#window.WebSocket = undefined;
```

**Comment by ameshkov** [comment]
That's too much, don't you think?

**Comment by ameshkov** [comment]
Reassigning to v2.7

**Comment by Alex-302** [comment]
>That's too much, don't you think?
I din't find another WS on mail.ru domains.

**Comment by ameshkov** [comment]
mail.ru and all subdomains?

**Comment by Alex-302** [comment]
>mail.ru and all subdomains?

yes

**Comment by ameshkov** [comment]
You can't test all the subdomains

**Comment by Alex-302** [comment]
I mean all mail.ru projects.
Should I remove this rule?

**Comment by ameshkov** [comment]
You can leave it but for high-tech subdomain only

**Comment by ameshkov** [comment]
@Revertron here is a plce where you can easily test it:
https://websocket.org/echo.html

**Comment by Revertron** [comment]
We filter WS as other requests.
