### ISSUE TITLE
Implement Filtered Apps settings section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#633]
1.) No more firewall Apps & Settings
2.) Instead of this section we add a new section named "Filtered Apps"

Layout is almost similar to the Firewall Apps and Settings, except some things:
1. Get rid of "global" buttons. These buttons are misleading.
2. Change buttons style on app details view. Use standard "switch style" buttons instead of our custom image buttons.

**App settings**
Filter Traffic [x] 
> (if this switch is disabled, gray out all other switches)

**Firewall Options:**
Mobile Data [x]
Wi-Fi [x]

**Ad Blocking Options**
Block Ads [x]
Filter HTTPS [x]

**Comment by ameshkov** [comment]
First mockups:
<img width="431" alt="2016-06-28_1445" src="https://cloud.githubusercontent.com/assets/5947035/16414207/1638efbc-3d3f-11e6-8140-a67737696cd1.png">
<img width="432" alt="2016-06-28_1446" src="https://cloud.githubusercontent.com/assets/5947035/16414209/166207c6-3d3f-11e6-997c-fc6c8abb0286.png">

**Comment by TPS** [comment]
These look fine!  I'm hoping, in the 1st pic, that the right-hand column icons (AG shield, wifi antenna, :signal_strength:) are _quick toggles_, & not just static state notifications.

**Comment by Revertron** [comment]
@TPS No, those are indicators, not buttons.

**Comment by TPS** [comment]
Is it practical to _make_ them buttons?

**Comment by Revertron** [comment]
They will be smaller, and there will be plenty of mis-clicks.

**Comment by TPS** [comment]
I understand, but it would be massively more convenientif it _could_ be worked out, especially if 1 needs to change _en masse_ a # of apps at once.

**Comment by Revertron** [comment]
@TPS I will think about it :)

**Comment by ameshkov** [comment]
@TPS we aren't re-designing an app yet, so too early for this.

**Comment by TPS** [comment]
>we aren't re-designing an app yet, so too early for this.

@ameshkov 😕 This is due for [v2.7](https://github.com/AdguardTeam/AdguardForAndroid/milestones/2.7), right?

**Comment by ameshkov** [comment]
@TPS, yep, this update is more about features, not the design

**Comment by TPS** [comment]
💡 Ahh, I missed the difference between this & #211! ☺

**Comment by ameshkov** [comment]
At the bottom of app details we should have a section with technical information about the app.

Here is what we need to see there:
package name
uid
app type (system or not system)
version
target sdk version
min sdk version
app permissions

Tapping on this block puts all the text to the clipboard (with a toast message)

**Comment by ameshkov** [comment]
We should also add "Reset settings" button to Firewall settings.

**Comment by ameshkov** [comment]
"Access blocked" notification should lead to the app details screen

**Comment by ameshkov** [comment]
Add "roaming" field to the database table (for future)

**Comment by ameshkov** [comment]
Reminder: blocking mobile data when screen is off does not work properly in the current dev build, we should test it more.

**Comment by ameshkov** [comment]
Reminder: check the list of excluded apps

**Comment by ameshkov** [comment]
@Revertron Tech info for "Android OS" app shows an error. We should not show this block at all.

**Comment by ameshkov** [comment]
@Revertron maybe it would be better if for "Android OS" we will have a simple description inside the Tech info". Something like that: "Meta package that represents system processes".

**Comment by ameshkov** [comment]
@Revertron wrong title, should be "Apps and Statistics", not "Firewall"

**Comment by ameshkov** [comment]
Done

**Comment by TPS** [comment]
Just got 2.7.151ß (Amazon).  Very nice work, folks!  Very clean & informative!  Just a couple of new minor suggestions/nits:

Right now, the panel is setup with some "implied" kind of UI relationships, e.g., if ad-filtering is disabled for a particular app, that immediately disables/grays out the HTTPS-filtering option for that app.
- I propose to extend these "implied" relationships further to the _converse_, e.g., attempting to enable HTTPS-filtering for an app where ad-filtering is disabled shouldn't fail — it should enable _both_ HTTPS- & ad-filtering, to make clear that requirement.
Further per-app relationships should be:
    - WiFi ↔ Wifi when screen off
    - Cellular data ↔ Cellular data when screen off
    - Firewall notifications when app traffic is routed through AG, but (inexplicably) no other notifiable options are enabled
- _Global_ ↔ per-app relationships should be shown a bit clearer, e.g., when HTTPS-filtering isn't enabled @ all, the per app settings shouldn't be disabled, but grayed out (potential to keep previous setting) to show it's being ignored.  Attempting to enable these _per-app_ shouldn't immediately enable the global setting, but put ↑ a box asking "Do you mean to <kbd>Turn on [e.g., HTTPS-filtering] for all apps</kbd>, <kbd>Leave previous per-app settings</kbd>, or <kbd>Cancel/Change nothing</kbd>.  Further relationships of this sort are the global ↔ per-app settings for wifi, cellular data, firewall itself, & app-traffic filtering.
- When doing such an ignoring/gray-out, it'd be helpful to put a note w/ the gray-out explaining *which* setting is causing the ignoring, e.g., "Global HTTPS-filtering is disabled" or "Wi-Fi data is disabled for this app."

**Comment by TPS** [comment]
Also, I forgot to mention: AG _itself_ still can be blocked from Wifi, or enabled for ad-blocking, &c., @ least according to the UI.…  Some part of that should be permanently gray-out with some sort of default setting, right?

**Comment by ameshkov** [comment]
> attempting to enable HTTPS-filtering for an app where ad-filtering is disabled shouldn't fail — it should enable both HTTPS- & ad-filtering, to make clear that requirement

It will look strange if we make grayed out item usable.

> WiFi ↔ Wifi when screen off
> Cellular data ↔ Cellular data when screen off

Yep, this should be done:
https://github.com/AdguardTeam/AdguardForAndroid/issues/697

> Firewall notifications when app traffic is routed through AG, but (inexplicably) no other notifiable options are enabled

Didn't get that point, what do you mean?

> when HTTPS-filtering isn't enabled @ all, the per app settings shouldn't be disabled, but grayed out (potential to keep previous setting) to show it's being ignored

https://github.com/AdguardTeam/AdguardForAndroid/issues/698

> Attempting to enable these per-app shouldn't immediately enable the global setting, but put ↑ a box asking

I guess this is about HTTPS filtering mostly. I think this feature is too complicated for such easy enabling:) So I suppose we should offer user to learn more about this feature instead of simply turning it on.

> When doing such an ignoring/gray-out, it'd be helpful to put a note w/ the gray-out explaining which setting is causing the ignoring, e.g., "Global HTTPS-filtering is disabled" or "Wi-Fi is disabled for this app."

Yep, you're right, thank you! Assigning this for future release:
https://github.com/AdguardTeam/AdguardForAndroid/issues/699

**Comment by TPS** [comment]
> It will look strange if we make grayed out item usable.

@ameshkov You're probably correct, & maybe #699 would be enough.  Still, it'd be a cool hack. 😉

& thanks for taking the rest so well! 😊

**Comment by TPS** [comment]
>>Firewall notifications when app traffic is routed through AG, but (inexplicably) no other notifiable options are enabled

>Didn't get that point, what do you mean?

@ameshkov I mean, if _both_ wifi _&_ mobile-data (& their -screen-equivalents) are _left_ enabled for an app, there's nothing to firewall-notify, right?  So the option should be grayed-out/ignored.

**Comment by TPS** [comment]
>I guess this is about HTTPS filtering mostly.

@ameshkov Since I don't use the HTTPS filtering myself, I was thinking of mobile data (blocked globally by me), & I could see others wanting such for wifi, as well.

**Comment by ameshkov** [comment]
> @ameshkov I mean, if both wifi & mobile-data (& their -screen-equivalents) are left enabled for an app, there's nothing to firewall-notify, right? So the option should be grayed-out/ignored.

You are right. I just keep in mind that we could add more "firewall-related" notifications in future and this setting should control them all.

**Comment by ameshkov** [comment]
> @ameshkov Since I don't use the HTTPS filtering myself, I was thinking of mobile data (blocked globally by me), & I could see others wanting such for wifi, as well.

Bringing up a dialog every time will be too annoying. However, it would be good to somehow mark that the value is overridden or got from defaults.
