### ISSUE TITLE
 2.6.101 spontaneous shutdown

### ISSUE THREAD

**Issue by Joss** [AdguardTeam/AdguardForAndroid#635]
On the latest RC the app spontaneously stops working. VPN icon and the app icons/notifications are disappear but the app has green status (turned on).

Some peoples says that it happens during the switch mobile network/WiFi.

Some logs were sent from User ID 1104390

[4pda](http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=50330768)

**Comment by Bohdan-SUP** [comment]
_Edit: removed your email from public access, changed to user ID._

**Comment by vozersky** [comment]
fixed in https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.6.104rc2
