### ISSUE TITLE
Consider changing update notification type or add option to choose how to notify

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#638]
Можно сделать уведомление об обновление менее
агрессивным, хотя бы в виде Push'а (так же как и уведомление о новой почте к
примеру). А то уже не в первый раз замечаю, занят чем нибудь важным а тут
оно. 

1311796

**Comment by TPS** [comment]
Duplicates #276?

**Comment by ameshkov** [comment]
@TPS No, this feature request is about update notification only.

**Comment by ameshkov** [comment]
As I understand, user'd like us to make this notification not so annoying, without sound, vibration and such.
