### ISSUE TITLE
More easily reachable statistics reset option

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#639]
For example, make it so when you hold the statistics frame, the dialog pops up that asks you to reset statistics.

https://forum.adguard.com/index.php?threads/clear-statistics-on-main-screen.11166/

**Comment by ameshkov** [comment]
We'll take care of it in the app redesign.

**Comment by KozelElena** [comment]
We've got a complaint about hard times to reach the statistics reset in our Beta. 
1537648

**Comment by mathiasbb** [comment]
How does one reset the statistics in 3.0?

**Comment by ameshkov** [comment]
Apps Management -> `...` button -> Reset statistics
