### ISSUE TITLE
Add mountainview and itau to https exclusions

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#641]
com.hopper.mountainview.play
com.itau.pers

"the apps will not work unless I add them to the HTTPS white list.
Once I list them there, they work just fine with HTTPS filtering enabled."

more details here - 1265822

**Comment by gshumihin** [comment]
com.hopper.mountainview.play works fine for me.

**Comment by gshumihin** [comment]
"Version 108 seems to have fixed the issue. Well done and thank you!
Best regards,
Tomaso"
