### ISSUE TITLE
Box app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#642]
https://play.google.com/store/apps/details?id=com.box.android
Downloads are Broken with HTTPs filtering enabled
![c510c6315515483b8e902e96ba9afb68](https://cloud.githubusercontent.com/assets/18548949/16170253/52e64712-3555-11e6-8d5e-c4223d7ceb0e.png)
id 1311060

**Comment by gshumihin** [comment]
Adding api.box.com solve this issue.

**Comment by Revertron** [comment]
Done.
