### ISSUE TITLE
Shortcut opens main UI on Android N

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#643]

**Comment by Revertron** [comment]
Working as expected on our Nexus 9 with Android N.

**Comment by ameshkov** [comment]
But not on my 6P. What do you need to diagnose this error?

**Comment by Revertron** [comment]
Do other shortcuts (from other apps) have this problem?

**Comment by ameshkov** [comment]
In fact I cannot reproduce it anymore in the latest beta. So all is good:)
