### ISSUE TITLE
Doesn't start automatically when OpenVPN is disconnected

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#648]
When using OpenVPN, it is constantly disconnected by AdGuard.

---

I updated to the beta and adguard no longer kills my vpn. This is good.
However, when I finish with the Vpn, adguard does not start again, I must
start it manually.

It would be good if adguard detected this and started again if the
protection was previously enabled.

1314896

**Comment by Revertron** [comment]
Constantly polling for TUN device disappearance will eat all of the battery juice. We will not do it.

**Comment by TPS** [comment]
Possible to ½-way do this with a _configurable_ notification (from when other VPN is started) as permanent-style notification: "Click here to reinstate AdGuard"?  I think that would be an efficient reminder.  Come to think of it, this might be useful thing _anytime_ AG is in memory, but not filtering, when temporarily disabling for _any_ reason!

**Comment by ameshkov** [comment]
@TPS for this kind of automation it is better to use Tasker.

**Comment by TPS** [comment]
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/59/9/tasker-app-configuration-to-work-with-adguard-for-android seems not to have sufficient info on how to _query_ AG as to when protection is active, only on how to tell AG to _start_ it up.…   Am I missing something?

**Comment by TPS** [comment]
@xdevs23 Do you have insight on this?
