### ISSUE TITLE
Check if there can be a connection loop when using manual proxy. 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#649]
please refer to user 1307897

Based on beginning on this log:
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/325603/debug.txt)

str:

- set up a manual proxy filtering mode
- use youtube app to watch videos

expected to get a message "Check your network connection" from the app

**Comment by gshumihin** [comment]
Wasn't able to reproduce this issue. Try to get more info about user's apps @vozersky please. This may be caused by some kind of antivirus or firewall.

**Comment by vozersky** [comment]
User replied, that he doesn't use any antivirus/firewall.
He was using port 8080 was used in Adguard and network connection proxy settings.

**Comment by gshumihin** [comment]
There is nothing suspicious it attached log and i wasn't able to reproduce this issue.
