### ISSUE TITLE
Protection is not started on device boot

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#65]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=43349323

Problem:
1. No net connection on device boot
2. Adguard does not start protection (that's ok)
3. When net connection appears - AG won't start anyway because of
``` 
BootUpReceiver
preferencesService.setNetworkReceiverEnabled(false);
```

**Comment by Revertron** [comment]
In ProtectionServiceImpl we now have:
```java
if (networkInfo == null && !preferencesService.isProxyMode()) {
  LOG.info("No need to start protection, there is no network connection");
  // Setting this to STARTED for NetworkStateReceiver to work properly on network connection
  preferencesService.setLastProtectionStatus(ProtectionServiceStatus.STARTED);
  return;
}
```

Tested now, it works flawlessly.

**Comment by ameshkov** [comment]
That's really bad solution.

You have simply broken the way the app handles status changes
