### ISSUE TITLE
Coursera - can't authorize / exit from account if HTTPs filtering is enabled

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#650]
https://play.google.com/store/apps/details?id=org.coursera.android&hl=en
When you first sign in to account:
http://prntscr.com/bjjj1a
When you exit from account:
http://prntscr.com/bjjjrd

log 
[debug (2).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/327808/debug.2.txt)

**Comment by Revertron** [comment]
Added to HTTPS exceptions.
