### ISSUE TITLE
New Google Prompt 2-Step Verification Blocked

### ISSUE THREAD

**Issue by kudiaborm** [AdguardTeam/AdguardForAndroid#651]
The new 2 step verification tool called Google Prompt detailed here:
http://googleappsupdates.blogspot.com/2016/06/new-settings-for-2-step-verification.html
(If you haven't heard you should check it out)

Is blocked unless I disable filtering for Google Play Services. 

I'm not sure if there is a filter that I can add/create/enable, or if specific intents can be filtered.

There seems to be no downside to disabling filtering for google play services, although I haven't tested to see if ingame ads can get through.

(Presumably) Associated Logcat
06-22 13:09:56.617 4373-4373/? I/Auth: [AuthDelegateWrapper] Service intent: Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDelegateService }.

**Comment by ameshkov** [comment]
@kudiaborm do you have https filtering enabled?

**Comment by kudiaborm** [comment]
I do indeed, just didn't know of this could be added the "useful ads" filter.

Considering how many Google apps I have to disable a built in " Google apps" whitelist filter check box would be nice.

Is the filter system open in such a way that I could create and share something like that? Or create a feature request?

**Comment by ameshkov** [comment]
> I do indeed, just didn't know of this could be added the "useful ads" filter.

I just don't think this is an ad or something like that. Something is just blocked incorrectly, we should find what exactly.

**Comment by kudiaborm** [comment]
Odd. I was able to replicate this issue on that day. There were a few updates. Perhaps they were related.

This issue doesn't occur anymore.

Please close this issue. If it happens again I'll let you know

**Comment by ameshkov** [comment]
@kudiaborm ok then, closing for now
