### ISSUE TITLE
Apps using Facebook ad network

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#654]
Here we'll keep track of the apps which use facebook ad network.
When #644 issue is done we will add specific rules for these apps.

**Comment by ameshkov** [comment]
https://play.google.com/store/apps/details?id=com.mobilefootie.wc2010

**Comment by ameshkov** [comment]
https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync

**Comment by Alex-302** [comment]
https://play.google.com/store/apps/details?id=com.ketchapp.donttouchthespikes&hl=en

**Comment by ameshkov** [comment]
@Alex-302 
Could you please check this app?
https://play.google.com/store/apps/details?id=com.mobilesrepublic.appy&hl=en

**Comment by Alex-302** [comment]
@ameshkov it works. What's Wrong?

**Comment by ameshkov** [comment]
@Alex-302 I meant check if facebook ad network is there

**Comment by Alex-302** [comment]
@ameshkov 
yes, I see requests to facebook ads
https://graph.facebook.com/network_ads_common/
but they are not loaded/displayed without Adguard. I think we should block them anyway.

**Comment by ameshkov** [comment]
@Alex-302 yep, we should.

**Comment by ameshkov** [comment]
@Alex-302 let's add the rules for these apps.

**Comment by Alex-302** [comment]
||facebook.com^$empty,app=
||facebook.com^$empty,app=
||facebook.com^$empty,app=

**Comment by Alex-302** [comment]
Added
```
||facebook.com^$empty,app=com.mobilefootie.wc2010
||facebook.com^$empty,app=com.laurencedawson.reddit_sync
||facebook.com^$empty,app=com.ketchapp.donttouchthespikes
||facebook.com^$empty,app=com.mobilesrepublic.appy
```

**Comment by Revertron** [comment]
Isn't it better to exclude only Facebook apps, and block this domain for all other apps?
The list of apps using FB ads will be unlimited...

**Comment by ameshkov** [comment]
@Revertron nah, we've tried that way before, it leads to hell of a lot broken apps.

**Comment by Alex-302** [comment]
https://play.google.com/store/apps/details?id=fr.meteo

**Comment by ameshkov** [comment]
@Alex-302 from now on just add the rules for these apps in mobile filter.
Closing this issue.

**Comment by Alex-302** [comment]
ok
