### ISSUE TITLE
Kaspersky AV compatibility issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#657]
KIS is somehow filters browsers traffic (I guess through a proxy of some sort). We should consider adding KIS to the browsers list.

**Comment by ameshkov** [comment]
@vozersky I need you to reproduce the issue with a free AG version.

**Comment by vozersky** [comment]
@ameshkov but what exactly is the issue? it seems they get along well with each other

**Comment by ameshkov** [comment]
As I understand, ads were not filtered when Kaspersky filters browsers traffic. I might be wrong tho.

**Comment by ameshkov** [comment]
@vozersky so, what with it?

**Comment by vozersky** [comment]
@ameshkov  It was all good. And I have re-tested it with our new 2.9.17 beta, works fine together with KIS Web protection. Ads are being filtered.

**Comment by ameshkov** [comment]
In a free version right?

**Comment by vozersky** [comment]
@ameshkov  I've tried both with and without prem. license
