### ISSUE TITLE
Smart appointments are blocked in Google Calendar

### ISSUE THREAD

**Issue by shaurmanchic** [AdguardTeam/AdguardForAndroid#658]
Adguard is blocking the smart appointments when creating a reminder in Google Calendar.

Open Google Calendar, click "+" > Goal/Reminder/Event. Type in anything, suggestions will come up, but they are absent if Adguard is on. Disabling ad filtering in Firewall seems to helps.

<details>
![](https://s32.postimg.org/dy4v5xz6p/3_Rz_CLq3_X.png)
</details>
<details>
![](https://s32.postimg.org/b5bnlwyu9/4_l_Rmdw9o.png)
</details>
<details>
![](https://s32.postimg.org/9mg9gxs9t/1_11e_XJX2.png)
</details>
<details>
![](https://s32.postimg.org/g1fadlyzl/2_7q_K9u_TF.png)
</details>
App version: 2.6.108
Noticed on Android 5.0.1 and 6.0.1

**Comment by nkartyshov** [comment]
done
