### ISSUE TITLE
by.euanpa.schedulegrodno

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#659]
https://play.google.com/store/apps/details?id=by.euanpa.schedulegrodno&hl=ru
При выборе именно города "Гомель" не грузится расписание:
![screenshot_11](https://cloud.githubusercontent.com/assets/18548949/16480157/39a13472-3ead-11e6-9ad6-3e52bc28744d.jpg)
На остальных городах расписание загружается. Помогает отключение HTTPS.

**Comment by Revertron** [comment]
Added to HTTPS exceptions.
