### ISSUE TITLE
Can't use SOCKS 5 proxy settings, all internet traffic is blocked.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#660]
"When using the PIA SOCKS5 proxy settings under advanced>proxy settings, all internet traffic is halted" 

id 1204283

Customer uses https://www.privateinternetaccess.com/  vpn service. They also provide SOCKS5 Proxy for subscribers. From their website:
"Although quite different from a VPN, we provide a SOCKS5 Proxy with all accounts in the event users require this feature.   proxy-nl.privateinternetaccess.com port 1080" 

@gshumihin could you please check if using outbound socks 5 proxy settings with username/password credentials in Adguard works fine

**Comment by evgeniy-ADG** [comment]
Пользователь настраивает АДГ совместно с pia vpn. В таком состоянии adguard пропускает всю рекламу.  Не могли бы подсказать, пож-та, правильно ли он настроил?

В программе adguard (2.7.211)
Настройки > Расширенные:
Режим фильтрации - локальный HTTP прокси;
Порт локального прокси - 8080;
Способ установки локального прокси - Ручной (рута нет)
Настройки прокси -
Тип прокси - SOKS5
Сервер прокси - proxy-nl.privateinternetaccess.com
Порт прокси - 1080
Логин и пароль генерировал через личный кабинет.

В программе PIA vpn отключил PIA mace (блокировщик рекламы) и Block local
network

**Comment by nkartyshov** [comment]
@vozersky Works is fine to last beta
@evgeniy-ADG Can be user forgot turn off the pia vpn?

**Comment by nkartyshov** [comment]
Done
