### ISSUE TITLE
Cortana voice recognition doesn't work with https filtering

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#661]
user id 1330038
https://play.google.com/store/apps/details?id=com.microsoft.cortana
 
It can't be installed in Ru, so i can't check it.

Suggested to add to apps exceptions list for now.

**Comment by vozersky** [comment]
I have requested more details. Looks like it doesn't work with filtering at all, not only https.

**Comment by evgeniy-ADG** [comment]
> Здравствуйте, если блокировать
> рекламу для Cortana то часто теряет связь
> и большой процент заблокированного
> трафика для этого приложения, хотя
> рекламных activity там нет

Попросили исключить из фильтрации HTTPS, диагн. отчет пользователь не прислал, потому ничего не бьіло видно.

**Comment by vozersky** [comment]
@evgeniy-ADG возможно, понадобится полностью исключить из фильтрации через низкоуровневые настройки

**Comment by evgeniy-ADG** [comment]
ок, дал пользователю линк на задачу.

Пользователь, если исключения из фильтрации HTTPs не поможет, зайдите в Настрйоки > Расширенные > Низкоуровневые > pref.net.exclusions и добавьте новой строкой com.microsoft.cortana, сохраните и перезапустите Adguard. :) Напишите нам в поддержку, помогло ли что-то из этого, если да, то что. Спасибо.

**Comment by Revertron** [comment]
Last version works great even with HTTPS filtering on.

**Comment by OlegSUP** [comment]
User ID: 1064370

Cortana (app for Android) can't hear me unless I add it to exceptions
on adguard (on firewall) I activated 'Logging level' to 'Record HTTP
requests' and reproduce the error about 22h28 - 22h29


[debug (12).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/850419/debug.12.txt)

**Comment by ameshkov** [comment]
@OlegSUP does it help to disable HTTPS filtering for the app?

**Comment by OlegSUP** [comment]
sent, waiting for reply from user

**Comment by deLumren** [comment]
User 1064370 states that HTTPS filtering exception solves the problem, but he's not satisfied with this fix and wants a more permanent solution working from the get-go with default settings.

**Comment by ameshkov** [comment]
Yep, we'll add it to the default list then:
