### ISSUE TITLE
Adguard closes if you swipe it with 'No icon' notification setting

### ISSUE THREAD

**Issue by Hobbix** [AdguardTeam/AdguardForAndroid#662]
Old commit here: https://github.com/AdguardTeam/AdguardForAndroid/issues/561
Not fixed, more info here: https://forum.adguard.com/index.php?threads/%D0%9E%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D0%B5%D1%82%D1%81%D1%8F-adguard-2-5-196.10065/page-2#post-88774

Video: http://rgho.st/private/7wRFlTnrH/aac02d9136ec13f351cbb787bb9afb49
Android 5.1

**Comment by Revertron** [comment]
Resolved in 2.7.
