### ISSUE TITLE
[Feature request] Automatically activate Adguard on mobile network and deactivate on wi-fi.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#663]
Or vice versa.
based on id 1325709

**Comment by ameshkov** [comment]
This type of automation is possible with Tasker. This is too specific to make it an app feature.

**Comment by didok3003** [comment]
Thank you very much I was the person that raised this question to support people. I actually have configured Tasker and it is perfect!
