### ISSUE TITLE
Internet access is blocked when using local http proxy filtering mode

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#664]
"Local Proxy Doesn't Work at all in my device. Only Adguard Check for upfates works. But Internet to Any browser is not working"

Asus ZenFone 5, Auto proxy mode, Adguard 2.6.108
please refer to id **1312445** for logs

Also:
"Before i can reproduce the issue, i have noticed in Super SU Log File that, if i enable Local Proxy and Start the Adguard then, there is two iptable errors. Iptables error and ip6tables error. I took these screen shot exact time of when enable Local Proxy WITHOUT ANY FIREWALL"

Screenshots: <details>
![screenshot_2016-06-23-21-01-58 1](https://cloud.githubusercontent.com/assets/17472907/16529271/9c4a025c-3fca-11e6-8ff9-d86c5f075e94.jpg)
![screenshot_2016-06-23-21-02-24 1](https://cloud.githubusercontent.com/assets/17472907/16529272/9c4b2696-3fca-11e6-8b12-68528daffe68.jpg)

</details>

**Comment by Rumbelagavi** [comment]
Asus Zenfone 5
Lollipop 5.0
Rooted
SIM:Airtel India 3G

Problem:
When filtering mode Set to "Local Proxy" Internet doesn't work at all in my device as i want to use Dr.Web firewall.
Rebooted so many times cleard adguard's cache and its settings, still no use.
Completely reset my device but same problem.
Trying to solve since from 2 month but i m unable to find out whats the wrong.
Local vpn is working fine but I need Proxy Mode to be work...
I want to know is anyone facing the same problem?

**Comment by ameshkov** [comment]
@Rumbelagavi how does this "not loading" look like? Is there some instant error or page is loading until timeout error fires?

**Comment by Rumbelagavi** [comment]
@ameshkov i receives following error.
Asus Browser: USER AUTHENTICATION FAILED ON PROXY.

TRIED MOZILLA Firefox ALSO.
AND


GOOGLE CHROME SAYS FOLLOWING ERROR:

You are offline.

There is something wrong with the proxy server, or the address is incorrect.

Try:

Contacting the system admin

ERR_PROXY_CONNECTION_FAILED

**Comment by ameshkov** [comment]
Yeah, so the issue is with an upstream proxy connection as I thought.

I see that you have proxy configured in your Wi-Fi settings:
  "currentWifiProxyConfiguration" : "host=127.0.0.1 port=3128 manual"

What's that proxy? DrWeb?

**Comment by Rumbelagavi** [comment]
Dear sir,
I never use WIFI as i don't have.
I always use MOBILE DATA ONLY.
I want to use Dr.Web Firewall to restrict per day/month data traffic and to calculate apps data usage.
I kept proxy setting type to NONE but didn't work.
And i don't its HTTP settings like host and port for MOBILE DATA USE
I want to use both apps but m trying from 2 months but I m unable to solve.

**Comment by ameshkov** [comment]
Well, I clearly see that you have a proxy settings somehow set. Maybe it is done by your cell provider.

@Rumbelagavi could you please collect and send debug logs one more time?

What to do:
1. Switch to "record everything" logging level
2. Open browser
3. Try opening Google website several times
4. Wait 10 seconds and then send the log through the app
5. Please report here when it's done

**Comment by Rumbelagavi** [comment]
Dear sir,
I have collected longs and sent it using app's feedback.

Sir, i want to tell you one thing that
I Enabled Local HTTP Proxy and rebooted device.
Then my device got 2G network at 7:30 PM and 2G internet worked till at 7:34 PM.
After my device got 3G network but after 7:34 in HSPDA network its not working at all.
Browser giving proxy error.
Now i had to set it to LOCAL VPN mode to report here sir.

**Comment by ameshkov** [comment]
Huh, ok, I got some news.

So, the thing is that Adguard has nothing to do with the browsers traffic. You see, your browser uses some local proxy on 127.0.0.1:3128. Meanwhile Adguard has a special rule for this sort of traffic, it just does not filter it.

So here is a question: does your browser work ok when AG is turned off?

**Comment by Rumbelagavi** [comment]
No sir, when i deactivate the AG internet never works.
If i want to use internet then AG should be turned on in my device. I don't know whats the issue.
Now What will you suggest me sir?
Should i factory reset again or should i visit to Service Center for Re-Installing Android OS?

**Comment by Rumbelagavi** [comment]
DEAR SIR, ITS WORKING NOW!
Sir as you told me twice about proxy saved in my mobile, I deleted current APN and rebooted.
I took new APN settings and tried with Local Proxy Settings and Dr.Web Firewall.
Now ITS COMPLETELY WORKING FINE SIR.
THANK YOU SO MUCH FOR YOUR WONDERFUL SUPPORT.
I Love AG.
I learnt Something New Today.
Thank You AG Team

**Comment by ameshkov** [comment]
@Rumbelagavi great, I am glad it has helped:)
