### ISSUE TITLE
Count DNS traffic towards a virtual package "DNS"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#668]
Currently it is counted as "Android OS" which is quite ok. However, I think it would be better to create a virtual package DNS so that user could understand how many DNS requests were blocked when "Filter DNS requests" feature is turned ON.

**Comment by TPS** [comment]
Would/could this also have some use when using `pref.vpn.dns`?  Maybe to show _which_ resolver(s) are being used how often or such?  Obviously, not really useful to _block_ DNS outright! 😉

**Comment by ameshkov** [comment]
> Obviously, not really useful to block DNS outright

This is not about blocking whole DNS. There is a "Filter DNS requests" feature which allows AG to block requests to ad servers on the dns level. The problem is that there is no place where you can see how many requests were blocked.

**Comment by Revertron** [comment]
Done.

**Comment by TPS** [comment]
@AdGuardTeam Now that this has been implemented a while, I'm completely confused by the stats I see.  For instance, my all-time #s read "↑ 1.3 MB ↓ 1.4 MB Ø 92 MB".…  Does this make sense in context?  I'm using OpenDNS's resolvers under my custom DNS settings.

**Comment by ameshkov** [comment]
I guess you also have DNS filtering enabled in AG?

I also suppose the "saved" value does not make any sense indeed. It should be way higher as blocking an ad host once means that ALL requests to this host will be blocked for an hour.

The problem here is that we can't even roughly estimate what will be the real savings.

**Comment by TPS** [comment]
Yes, DNS filtering is active, but not HTTPS filtering.

I don't understand at all why the Ø amount is something like 20× the combined ↑+↓ amount.  That means something like 95% of DNS requests are to ad servers?!

**Comment by ameshkov** [comment]
Nope, it's just we estimate a usual ad request as 10-30kb, while in case of DNS it is a lot smaller.

**Comment by TPS** [comment]
💡 OIC.…  Maybe you all may want to adjust ~~that estimation in this 1 place to get a better idea of what's done here.  Better yet, do~~ this 1 stat in terms of request #s, so: "↑17000 ↓15000 Ø 2000" or some such?

Also, it'd be helpful to have lists here re: Top 10 servers blocked, Last 10 servers blocked, &c

**Comment by ameshkov** [comment]
This anyway does not solve the precision issue.

As I've said, a host blocked once on the DNS level is equivalent to multiple ad requests blocked with the usual approach .

**Comment by TPS** [comment]
I meant it's fine to keep counting it the way it is toward the general ad-block count, but, the way it's setup now, it not clear how many DNS requests are blocked.

**Comment by ameshkov** [comment]
Why, you can see how many ad requests are blocked if you tap on the DNS app.

**Comment by TPS** [comment]
I mean, relatively; e.g., right now, it shows 4183 ads blocked per 1 day/month/all time (?), but out of how many total requests?

**Comment by ameshkov** [comment]
> I mean, relatively; e.g., right now, it shows 4183 ads blocked per 1 day/month/all time (?), but out of how many total requests? I've no sense of scale with just that #.

I must admin this is a great idea! 4183 is just a number it does not mean much without total requests number.
