### ISSUE TITLE
com.samsung.voiceserviceplatform - HTTPS issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#674]
I'm using Adguard for my Samsung Galaxy s7 and it is working great. But, there is a little problem with HTTPS filtering. There is an app on Samsung called "S Voice" and I use it a lot. But, everytime I enable the HTTPS filtering, it will interfere with that app and cause it to stop working. 

The package name according to the firewall is “com.samsung.voiceserviceplatform.” As you mentioned, adding this package to the whitelist in the HTTPS does also fix the problem. 

* User ID: 1213432

**Comment by evgeniy-ADG** [comment]
UPD:

> For some reason the problem is back. None of what I said earlier actually fixed to the problem. It did, only for a short period. Now, the problem is there and none of the solutions is working… The only thing that works is disabling the HTTPS and I don’t want to disable it. I don’t really now what to do now.

Waiting for logs

**Comment by Bohdan-SUP** [comment]
Adding com.samsung.voiceserviceplatform to pref.net.exclusions helped.
We should whitelist it on our side then.

**Comment by nkartyshov** [comment]
done
