### ISSUE TITLE
When user changes a default firewall setting, ask him if he wants to reset a per-app setting

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#675]
Currently we just change the default setting, but per-app settings stay the same. It would be easier to understand if we offer user a possibility to reset all per-app settings to the default.

For instance:
1. User switches "Cellular data" setting
2. We show a dialog window: "Do you want to reset this setting to default for all apps? Blahblah otherwise if you have changed it for some apps it stays the same blahblah".
3. User taps "Change"
4. We go through all apps and change "Cellular data" to `null` (means take it from defaults)

**Comment by Revertron** [comment]
Done.
