### ISSUE TITLE
Add Amazon apps to SSL exceptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#676]
Amazon Kindle
Amazon Underground

**Comment by TPS** [comment]
Don't forget the standard Amazon Appstore app (_com.amazon.venezia_)!  Many still use it, for various reasons, instead of Underground.

**Comment by Revertron** [comment]
Added these:

> com.amazon.kindle
> com.amazon.sellermobile.android
> com.amazon.mShop.android.shopping
> com.amazon.mShop.android
> uk.amazon.mShop.android
> com.amazon.windowshop
> com.amazon.drive
> com.amazon.clouddrive.photos
> com.amazon.venezia
