### ISSUE TITLE
Prepare beta and release build configurations

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#678]
New profiles:
1. local_release - for local builds with production environment
2. beta - for production builds from beta branch
3. release - for production builds from release branch
4. amazon - for amazon builds

**Comment by Revertron** [comment]
Done.

**Comment by TPS** [comment]
Just to verify, No. 4 above should be:
4. Amazon
4a. Beta
4b. Release

Correct?  (Sometimes, I think it isn't remembered that _Amazon_ treats these as related, for update/overwrite purposes, but separate, for licensing purposes.)

**Comment by ameshkov** [comment]
@TPS no, we won't divide Amazon builds into beta and release branches. The workflow on Amazon is a bit different, before going to release build first goes to testing and then when it's ready we "promote" it to release.

**Comment by TPS** [comment]
Then _Amazon_ handles it differently completely from _its_ end?  Huh.

**Comment by ameshkov** [comment]
It's just standard workflow for them. We could support two amazon build configurations and quickly get releases through testing stage, but I think would be an overkill.
