### ISSUE TITLE
SwiftKey updates are broken by HTTPS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#679]

**Comment by Alexey71** [comment]
Добавить в исключения и все, рекламы же нет в ней

**Comment by nkartyshov** [comment]
Добавил

**Comment by Alexey71** [comment]
Не добавили в исключения SwiftKey beta

**Comment by Alexey71** [comment]
Не помогает отключение блокировки в настройках. Если вобще отключить гвард,  работает
![screenshot_20160825-003431](https://cloud.githubusercontent.com/assets/10572914/17948937/d04d5e30-6a5b-11e6-8756-8f50c9619cc9.png)
![screenshot_20160825-003414](https://cloud.githubusercontent.com/assets/10572914/17948946/d966c556-6a5b-11e6-8842-b6eaaf7d9f02.png)
![screenshot_20160825-003401](https://cloud.githubusercontent.com/assets/10572914/17948962/e797f3fc-6a5b-11e6-8586-2ba245fab4e0.png)

**Comment by ameshkov** [comment]
Переоткрываю

**Comment by Alexey71** [comment]
Отрубил фильтрацию полностью для них, работает

**Comment by nkartyshov** [comment]
Добавил в исключения https
