### ISSUE TITLE
Lazada app compatibility issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#680]
HTTPS issues with this app.

**Steps to reproduce the problem**:

* Install Lazada app (https://play.google.com/store/apps/details?id=com.lazada.android)
*  Enable Adguard
*  Launch the app. It asks you to 'tap to connect'

These domains must be excluded:
```
mobapi.lazada.co.id
mobapi.lazada.sg
```

**Comment by vbagirov** [comment]
Issue created based on https://github.com/AdguardTeam/AdguardFilters/issues/2573

**Comment by Alex-302** [comment]
Other countries in this app should be tested too.

**Comment by nkartyshov** [comment]
done
