### ISSUE TITLE
AdGuard - считает себя рекламным продуктом , а так же занимается самонакруткой результата .

### ISSUE THREAD

**Issue by ajnao** [AdguardTeam/AdguardForAndroid#681]
А теперь все по порядку .

Включил телефон , сразу включил AdGuard . После включения AdGuard произвел обновление фильтров . До обновления фильтров показывало , что заблокировано 6003 баннера , пока фильтры обновлялись количество заблокированного увеличилось и стало теперь 6004 . Сам в себе блокирует рекламу . Интересно что Вы такого запихали в программу ?

Но это не главное , а главное то что он занимается накруткой заблокированного . Использую только Wi-Fi , на мобильный интернет настройки убрал . Так вот что удалось несколько раз заметить . Мой роутер был выключен , сбросил статистику и оставил телефон просто лежать . Минут через 20 включаю и что вижу : вместо 0 на заблокированном показывает более 10 заблокированных баннеров .

Чего он такого заблокировал если интернет отключен и телефон не использовался ?

**Comment by ameshkov** [comment]
Для того, чтобы посмотреть, что конкретно блокируется, надо включить уровень логгирования "записывать HTTP запросы" и почитать лог.
