### ISSUE TITLE
HTTPs filtering breaks Romeo Uncut

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#686]
https://www.planetromeo.com/app/uncut/en

It won't let you go through authorization and won't let you create an account if HTTPs filtering is enabled

![image](https://cloud.githubusercontent.com/assets/15856304/16851243/51ad1c5c-4a0b-11e6-831f-408fe1001148.png)

Works fine once HTTPs filtering is turned off.

**Comment by evgeniy-ADG** [comment]
Даже и не спрашивайте...

**Comment by Revertron** [comment]
Done.
