### ISSUE TITLE
Add HTTPS enforcing feature as in "HTTPS Everywhere" browser extension

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#689]
Most of android browsers does not have capability no install HTTPS enforcing extensions like "HTTPS Everywhere".

It may be a good idea to provide that on filtering level.

**Comment by zero77** [comment]
It may be a better solution to just send a upgrade-insecure-requests header.
w3.org/TR/upgrade-insecure-requests

**Comment by TPS** [comment]
Maybe (or perhaps in the interim) this is more reasonably a UserScript?  D'y'all know of any that would be compatible w/ AG?

**Comment by zsoltsandor** [comment]
This is a must have, it could also fix some poorly written apps that for some reason use http for certain functions, eg - horribile dictu - relaying notifications.

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1284](https://github.com/AdguardTeam/CoreLibs/issues/1284) via [**ZenHub**](https://www.zenhub.com/)
