### ISSUE TITLE
Adguard crashes when using Google Books

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#690]
[Andriod 5.0.2] v2.6.108 

Steps to reproduce:
1. Have Adguard installed on your device
2. Try to download a book from Google Books cloud
3. Open Google Books and start to read the book (go through pages)
4. After short time Adguard crashes

Originally from forum:
https://forum.adguard.com/index.php?threads/11924/

**Comment by Revertron** [comment]
Adguard crashes or Google Books?

**Comment by TPS** [comment]
_(*This* problem I don't have w/ GBooks, though I use it extensively, though I run into #186 sometimes.)_

**Comment by Revertron** [comment]
May be a duplicate for #719

**Comment by TPS** [comment]
As I mentioned earlier, *this* problem I don't have w/ GBooks, though I use it extensively (I run into #186 sometimes, randomly, as _that_ issue is :wink:), but it seems maybe it's OS version related.  I'm currently running Android 4.4.2, but I think the Nexus 5x (from https://github.com/AdguardTeam/AdguardForAndroid/issues/719#issue-167645131) runs only Android 5+, & the original report above is Android 5.0.2.

Pretty soon, it looks like I'll be upgrading to an Android 6+ device.…  Any reports on this problem with those?  If so, I'll hold off as long as possible, as GBooks is vital for me.

**Comment by ameshkov** [comment]
> Pretty soon, it looks like I'll be upgrading to an Android 6+ device.… Any reports on this problem with those?

Not really

**Comment by TPS** [comment]
GBooks has been updated recently, & I've noticed some major performance _increases_ (after some regressions, a few versions back).  Did this help any?

**Comment by TPS** [comment]
Any further reports of this?  Everything works fine for me on Android 4.4.2 ___&___ 7.1.1ß.
