### ISSUE TITLE
Fix the issue with dialog windows width

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardForAndroid#692]
Уменьшить ширину до нормального, или пусть берет размеры из системы
У меня например планшет 320dpi - xlarge ресурсы - 8.4 дюйма
![screenshot_2016-07-15-18-28-52](https://cloud.githubusercontent.com/assets/10572914/16879897/50ecb7c2-4abb-11e6-91cc-574388c8a101.png)
![screenshot_2016-07-15-18-35-03](https://cloud.githubusercontent.com/assets/10572914/16879896/50ebd690-4abb-11e6-99a6-fe4b6fe0a3d1.png)
![screenshot_2016-07-15-18-35-22](https://cloud.githubusercontent.com/assets/10572914/16879898/50ef0aea-4abb-11e6-90cb-57ecc19a2d6b.png)
![screenshot_2016-07-15-18-35-30](https://cloud.githubusercontent.com/assets/10572914/16879899/50f3db24-4abb-11e6-9851-b3aafdbc1c14.png)
Вот так должно для моего разрешения
![screenshot_2016-07-15-18-35-46](https://cloud.githubusercontent.com/assets/10572914/16879909/5d2b467a-4abb-11e6-992e-6e7e02e3c250.png)

**Comment by nkartyshov** [comment]
Done
