### ISSUE TITLE
Ads in Facebook lite 

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#693]
HTTPS enabled. Needed filters enabled. Version 2.6
![fbl1](https://cloud.githubusercontent.com/assets/20476168/16900225/91cc8b56-4c27-11e6-992d-f0ac1f58f076.jpg)
![fbl2](https://cloud.githubusercontent.com/assets/20476168/16900226/939809e2-4c27-11e6-8d26-678fde9f4d72.jpg)

**Comment by ameshkov** [comment]
@Fridrix эта реклама зашита в ленту фейсбука, простой блокировкой запросов мы ее не победим.

Можно попробовать модифицировать контент ленты, вырезать из нее рекламные посты. @Alex-302, скажи, это реально?

**Comment by Alex-302** [comment]
Не понятно, в HAR по фейсбуку ничего не пишется, и через комп с Фидлером не подключается
http://imagizer.imageshack.com/img921/7638/iR24Kv.png

**Comment by ameshkov** [comment]
Видимо не дают фильтровать HTTPS

**Comment by Alex-302** [comment]
Ничего не поделать с этим?

**Comment by ameshkov** [comment]
Неа
