### ISSUE TITLE
Adguard vs. TalkBack issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#695]
Just turn on Talkback, locate the widget AdGuard and check the problem.
When you find the widget and position in the single item of Widget, talkback says Button, unlabeled .
This existing item in the widget needs to be described by the developers.
It's just a button with this problem of accessibility that need a description.
I believe activate Talkback to check this problem, it does not take even two minutes.

**1263433**

**Comment by Revertron** [comment]
Added content description for widget.
