### ISSUE TITLE
Gray out HTTPS filtering item in the app details when HTTPS filtering isn't enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#698]
Based on:
https://github.com/AdguardTeam/AdguardForAndroid/issues/633#issuecomment-232982708

If user taps on this grayed out item, show an alert dialog:

**Warning**
In order to enable HTTPS filtering for this app, you should turn if on system wide.

Two buttons:
Cancel
Learn more (sends to HTTPS filtering settings)

**Comment by Revertron** [comment]
Done.
