### ISSUE TITLE
Inform user why this or that item is disabled/greyed out

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#699]
When user taps on a disabled item, we should show a toast explaining why it is disabled.

TODO: List these items here.

**Comment by nkartyshov** [comment]
Options can be disabled
```
AppManagement Settings
- Cellulat data
- Wi-Fi data
- Cellular data when screen is off
- Wi-Fi data when screen is off
- Firewall notifications

AppManagement App Info
- Ad blocking
- Https filtering
- Cellulat data
- Wi-Fi data
- Cellular data when screen is off
- Wi-Fi data when screen is off
- Firewall notifications

DNS main screen
- DNS requests blocking
- Choose a custom DNS server

Settings
- Local proxy port
- Local proxy setup mode

Outbound proxy
- Notification without icon

HTTPS filtering
- Which domains to filter?
- Blacklist
- Whitelist
- Do not filter websites with EV certificates
```

**Comment by nkartyshov** [comment]
done

**Comment by karina-archazh** [comment]
AppManagement Settings
- Cellulat data - doesn't work
- Wi-Fi data - doesn't work
- Cellular data when screen is off - - doesn't work
- Wi-Fi data when screen is off - doesn't work
- Firewall notifications - doesn't work

AppManagement App Info
- Ad blocking - doesn't work
- Https filtering - - doesn't work and also turned on/off after tapping 
- Cellulat data - doesn't work
- Wi-Fi data - doesn't work
- Cellular data when screen is off - doesn't work
- Wi-Fi data when screen is off - doesn't work
- Firewall notifications - doesn't work

DNS main screen
- DNS requests blocking
- Choose a custom DNS server

Settings
- Local proxy port - work
- Local proxy setup mode -- doesn't work

Outbound proxy
- Notification without icon - doesn't exist 

HTTPS filtering
- Which domains to filter? - doesn't exist 
- Blacklist - doesn't work
- Whitelist - doesn't work
- Do not filter websites with EV certificates - doesn't exist 

Tested on Android 9/8/6/5 and AdGuard 3.0.60

**Comment by nkartyshov** [comment]
Fixed

Options can be disabled:

Settings 
- General
    - Show icon
- Stealth Mode
   - All settings options  
- Network
   - Local proxy port
   - Local Proxy auto mode

AppManagement 
- Settings
   - Cellular data
   - Wi-Fi data
   - Cellular data when screen is off
   - Wi-Fi data when screen is off
   -  Firewall notifications
- App Info
   - Ad blocking
   - Https filtering
   - Cellulat data
   - Wi-Fi data
   - Cellular data when screen is off
   - Wi-Fi data when screen is off
   - Firewall notifications

HTTPS
- Filter websites with an Extended Validation Certificate
- Filter Blacklist only
- Whitelist
- Blacklist

DNS
- DNS requests blocking
- System default
- Custom DNS settings

**Comment by zzebrum** [comment]
not working for App info in App Management
