### ISSUE TITLE
Add "! Title: filter_name" in mobile filter 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#70]
It's useful when mobile filters added to AG6 for filtering Android apps
```
! Title: Russian Filter (mobile)
! Title: English Filter (mobile)
! Title: Spyware Filter (mobile)
! Title: Social Media Filter (mobile)
! Title: Experimental Filter (mobile)
```

**Comment by ameshkov** [comment]
@Mizzick it's simple, change filtercache properties in applicationContext.xml (there's an option to add ABP like header to the filter).

**Comment by Mizzick** [comment]
fixed

**Comment by Alex-302** [comment]
We need "! Title:", not "Name" and "NameEn"(they are not parsed)

**Comment by Alex-302** [comment]
Bump

**Comment by Mizzick** [comment]
Fixed
