### ISSUE TITLE
Add banking apps to exceptions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#702]
https://play.google.com/store/apps/details?id=de.dkb.portalapp
https://play.google.com/store/apps/details?id=com.starfinanz.mobile.android.dkbpushtan
https://play.google.com/store/apps/details?id=com.centralway.numbrs

**1079816**

**Comment by ameshkov** [comment]
@Revertron as I remember we turn ad blocking off for such apps.

**Comment by Revertron** [comment]
Done.
