### ISSUE TITLE
Adfly Blocked

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#703]
Screenshot: https://drive.google.com/file/d/0B4Fi2pUMJ_PrVU43clluX2xDenc/view?usp=drivesdk

**Comment by TPS** [comment]
@AdGuardTeam, should this be in https://github.com/AdguardTeam/AdguardFilters/issues, instead?

**Comment by ameshkov** [comment]
Yep:
https://github.com/AdguardTeam/AdguardFilters/issues/2414

**Comment by Bluscream** [comment]
You added the "Anti Adblock Script" Badge to the issue you referenced.

Can you tell me how i should install that in the Android App if you can't even install custom filterscripts?

**Comment by Bluscream** [comment]
So i just avoid adfly / whitelist it or wait for the next update?

**Comment by TPS** [comment]
@Bluscream They usually mean they need to add it to their Anti-AdBlock handling filters, & will handled via filter update when it's solved.  Stay tuned there! ☺

**Comment by TPS** [comment]
Also, they're working to get custom filter*sets* (#13), but 1 can add custom filters right _now_: AG » Settings » User Filter.

They also already include @reek's [Anti-AdBlock Killer](https://github.com/reek/anti-adblock-killer) filterset as a subscription (& will include his blockscript as soon as #34 lands), which handled this via https://github.com/reek/anti-adblock-killer/issues/1497.
