### ISSUE TITLE
Сlose existing connections when screen goes OFF (according to the firewall rules)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#704]
First let me elaborate on how this feature works right now.

If you uncheck "allow mobile when screen is off" for the app, Adguard will keep existing connections alive, but all new connections will be blocked.

On one hand this is ok as we won't break app functionality and allow it to finish with the current operation. On the other hand, we have whatsapp, telegram, instagram, etc which keep persistent connection all the time waiting for new messages.

The question is: what should we do?

**Option 1: keep existing connections.**

Pros: 
simplicity

Cons:
you'll still receive notifications from messengers until connection is reset

**Option 2: close existing connections.**

Pros: 
now you can be sure that after screen goes off all connections will be closed

Cons:
complexity
what if you turn screen off and on again in a short period of time? how can we be sure that you turned screen off for good?
what if some long-running operation is in process?

**Comment by Revertron** [comment]
Wait a minute and then reset connections?

There are two possibilities how we can close connections:
1. Simply restart protection (All connections are closed, allowed apps are reconnecting again - not the best variant)
2. Disconnect connections of disabled apps only. This is a better approach. But here we face the turn off-and-on complexity.

I propose:
On screen off we can start some traffic monitoring task for connections of disabled apps. If the traffic is significant enough (some file is downloading) we don't disconnect it at once. We set a timer for one-two minutes and disconnect after 1-2 minutes if the screen was not lit again.

**Comment by ameshkov** [comment]
> On screen off we can start some traffic monitoring task for connections of disabled apps. If the traffic is significant enough (some file is downloading) we don't disconnect it at once. We set a timer for one-two minutes and disconnect after 1-2 minutes if the screen was not lit again.

Yeah, that is what I meant by complexity:)

However, I was thinking about the same way. We could introduce a new preference in the "low level settings" section for the waiting period.

"pref.firewall.screen.off.timeout"

Values:
-1: keep existing connections
>=0: timeout in seconds

On the VPN level we can easily check if connection is idle or not.
But in proxy mode we can, so I suggest consider all connections idle:)

**Comment by ameshkov** [comment]
So, for the VPN mode we can implement this logic in method which is called periodically anyway:
`boolean shouldCleanUp(VpnTcpConnection vpnTcpConnection)`
Just do the app settings check inside.

For the proxy mode we can **do nothing**. We anyway have a 30 seconds keep-alive timeout there.

**Comment by Revertron** [comment]
Made first generation of this behavior: we close disallowed connections after 30 seconds when the screen is off. The pause is not configurable yet.
