### ISSUE TITLE
VK app video upload does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#706]
@gshumihin seems to be caused by HTTPs filtering. Please check it.

**Comment by ameshkov** [comment]
Чтобы повторить, нужно отключить опцию "сжимать отправляемые фотографии"

**Comment by gshumihin** [comment]
Wasn't able to reproduce this issue neither with VPN nor with local proxy (manual).

**Comment by nkartyshov** [comment]
От пользователя:

В приложение ВКонтакте, с включенным Adguard не загружаются файлы примерно больше 1 МБ, отображается индикация загрузки, потом доходит до конца и выдаёт ошибку, с небольшими файлами такой проблемы нет.

**Comment by gshumihin** [comment]
У меня на текущий момент вообще видео вообще не догружается до вконтакта. Что с адгардом, что без него. Ни ошибок, ничего, просто по кругу крутит полосу загрузки.
