### ISSUE TITLE
SOCKS 5 upstream proxy issue. 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#707]
id 1346046

"Не работает использование вышестоящего socks5 сервера. В браузере пишет о ошибке подключения к прокси, но при прямой настройке в браузере firefox на android, использования данного прокси, все работает"

"В моем случае SOCKS сервер поднимается на этом же устройстве, которое
использует приложение Adguard.
Используется только Firefox, ибо только он может использовать прокси
сервера (about:config) на андроидах.

Как действую:
1. Запускаю подключение к SSH серверу, с созданием SOCKS туннеля на порту
5060 используя приложение ConnectBot.
2. Настраиваю Adguard на использование вышестоящего прокси сервера (в моем
случае 127.0.0.1:5060)
3. В расширенных настройках Firefox указываю параметр network.proxy.type =
0 (в данном случае это *выключает* использование прокси серверов в
приложении, и он *обращается* к VPN созданный Adguard-ом)
4. Включаю Adguard.
5. Открываю страницу.
Соответственно я получаю страницу с ошибкой подключения.

По другому - убираются пункты 2 и 4.
1. Запускаю подключение к SSH серверу, с созданием SOCKS туннеля на порту
5060 используя приложение ConnectBot.
2. В расширенных настройках Firefox указываю параметр network.proxy.type =
1 (в данном случае это *включает* использование прокси серверов в
приложении, и он *НЕ обращается* к VPN созданный Adguard-ом)
3. Указываю параметры network.proxy.socks = 127.0.0.1 |
network.proxy.socks_port = 5060 | network.proxy,socks_version = 5
4. Открываю страницу.
Получаю страницу без фильтрации."

**Comment by vozersky** [comment]
possibly related to socks 5 problem here: #660

**Comment by atnaguzin** [comment]
Thanks for opening issue. I'll try to answer in that thread.
I havent premium account, ConnectBot must not be filtered by firewall with that settings.

**Comment by ameshkov** [comment]
ConnectBot - должен быть добавлен в сетевые исключения, чтобы Adguard не пытался фильтровать его трафик и мы не получили рекурсию.

Для этого на релизной версии: настройки - низкоуровневые - pref.net.exclusions - добавить package name 

На бета-версии: настройки - настройки приложений - connectbot - снять галку "включено" - перезапустить защиту

**Comment by nkartyshov** [comment]
Ошибка возникает из-за обрыва соединения в ConnectBot. При включение Adguard, система android прописывает маршруты роутинга и при включенной фильтрации трафика для приложения ConnectBot, соединение с ssh туннелем будет сброшено. Проблема является ограничение системы android.

Для решения просьба для бета версии в Настройки - Настройки приложений - ConnectBot - снять галку "включено" - перезапустить защиту. 
На релизной версии: Настройки - Низкоуровневые - pref.net.exclusions - Добавить package name org.connectbot

**Comment by atnaguzin** [comment]
Данное решение не помогло. ConnectBot был добавен в исключения (org.connectbot), подключение создается после запуска AdGuard.
При указывании FireFox-у использование прокси все работает,  и наоборот при использовании поключение создаваемым AG. Всё в точности как в тикете.

**Comment by nkartyshov** [comment]
Я использую последнюю бету.

Настраиваю AG для использования socks 5 прокси.
![oie_2122182trtzglh](https://cloud.githubusercontent.com/assets/3413799/17324898/78ba5954-58b1-11e6-91b1-979d91b9f4f3.png)

Запускаю защиту и после подключаюсь с помощью ConnectBot по ssh к socks 5 прокси и прописываю проброс порта 1080
![oie_212422y8e05hhh](https://cloud.githubusercontent.com/assets/3413799/17324957/b78c1a96-58b1-11e6-8594-459863d54e4d.png)

Перехожу в FF и прописываю network.proxy.type=0
![oie_212511nhy1uerz](https://cloud.githubusercontent.com/assets/3413799/17324992/e0638af8-58b1-11e6-82b2-8441b2d3e572.png)

После перехожу по ссылке на yandex.ru и получаю сайт без рекламы
![oie_212643nxqpub9z](https://cloud.githubusercontent.com/assets/3413799/17325034/13adf2c2-58b2-11e6-9d08-3f06939e4c6d.png)

**Comment by atnaguzin** [comment]
Сейчас скачал бету, испытаю.

**Comment by nkartyshov** [comment]
Странно. 
Можете прислать полный лог работы adguard для анализа.

Как это сделать написано в инструкции: [Сбор полного лога в Android-версии](https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/48/5/sbor-polnogo-log-v-android-versii)

**Comment by atnaguzin** [comment]
@nkartyshov, отправил на мыло техподдержки. Тема письма:"id 1346046"

**Comment by nkartyshov** [comment]
@atnaguzin, а у вас socks 5 прокси какой использует порт?

**Comment by atnaguzin** [comment]
SOCKS5 прокси поднимается в туннеле, Так же как и у вас на порту 1080 (на скрине же порт написан).
На стороне SSH сервера никаких прокси серверов не нужно. Почитайте насчет ssh туннелей и пробросов портов.
На стороне сервера Debian 8, на клиенте Android 4.4.2.

**Comment by nkartyshov** [comment]
Включенный VPN не позволяет приложениям принимать входящие соединения. Связано это с особенностями реализации VPN в Android.

В Android 5+ можно исключать приложения из VPN, и таким образом решать проблему.
В Android 4 этого делать нельзя. Но остается вариант с исключением из VPN определенных маршрутов.

В вашем случае могу посоветовать добавить в исключения vpn подсеть 127.0.0.1/8.

Для этого на перейти в Настройки -> Расширенные настройки -> Низкоуровненые настройки и выполнить 2 действия:
1. включить pref.vpn.ipv4.force.complex
2. добавить 127.0.0.1/8 в pref.vpn.ipv4.routes.excluded

**Comment by atnaguzin** [comment]
И снова ничего нового. Всё как прежде.

**Comment by nkartyshov** [comment]
@atnaguzin да

**Comment by atnaguzin** [comment]
@nkartyshov, отправил.

**Comment by nkartyshov** [comment]
@atnaguzin могу предложить только обновиться до версии андройд 5 и выше. 
В текущей версии решить проблему не получиться.

**Comment by atnaguzin** [comment]
Увы, нету еще 5й версии на мой телефон...

**Comment by ameshkov** [comment]
@atnaguzin ну если есть рут, то можно переключиться в режим локального прокси, в нем connectbot нормально исключится.

**Comment by atnaguzin** [comment]
Но в данном случае не будут фильтроваться все остальные приложения.

**Comment by ameshkov** [comment]
> Но в данном случае не будут фильтроваться все остальные приложения.

Почему, будут же.

**Comment by atnaguzin** [comment]
Filtering mode: Local HTTP Proxy
Local proxy setup mode: Automatic
Firefox: network.proxy.type = 0

Вот так сработало. Надеюсь в таком случае будут проксироваться все приложения.

@ameshkov, благодарю.
