### ISSUE TITLE
Full (not mobile) Amazon Cart broken

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#71]
https://smile.amazon.com/gp/cart/view.html/ref=nav_cart in full website mode (try on tablet or try link toward bottom of page) is broken in .153 in proxy mode, but not in .106 in VPN mode.

**Comment by ameshkov** [comment]
@Alex-302 check if the problem is in filter rules first please.

**Comment by TPS** [comment]
Solved in .156 ☺ Thanks!
