### ISSUE TITLE
com.grindrapp.android - HTTPS issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#710]
com.grindrapp.android app gets blocked by HTTPS filtering

![image](https://cloud.githubusercontent.com/assets/15856304/17057218/535f4f36-5021-11e6-82d8-3b8494e36daa.png)

Disabling HTTPS filtering DID work - the app launches without any issue.

**1356100**

**Comment by nkartyshov** [comment]
done
