### ISSUE TITLE
Ad blocking interferes with videos in ru.mail.mailnews

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#711]
based on ticket id 874098

app:
https://play.google.com/store/apps/details?id=ru.mail.mailnews&hl=ru

some videos can still be played though, but most of them can't, like in this article:

<details>
![screenshot_20160722-194159](https://cloud.githubusercontent.com/assets/17472907/17064663/5278d2c0-5046-11e6-8469-10cd6e98cd92.png)
</details>

if you click on video with https filtering on:
<details>
![screenshot_20160722-194208](https://cloud.githubusercontent.com/assets/17472907/17064662/527719e4-5046-11e6-9648-dd30abb38ad4.png)
</details>

**Tested with all filters off**, didn't help, only excluding from https filtering did.

**Comment by ameshkov** [comment]
@Alex-302 похоже проблема в блокировке рекламы, надо выяснить в чем именно

**Comment by Bohdan-SUP** [comment]
disabling https didn't help - "Увы, но это не помогло, по прежнему "ошибка интернет соединения". Проблема устраняется, лишь при полном отключение защиты."

**Comment by vozersky** [comment]
@ameshkov  Странно. Проверил еще раз пяток сегодняшних видео в этом приложении, у меня именно https-фильтрация ломает.

@Bohdan-SUP Нужен пример статьи, в которой видео ломает именно обычная фильтрация и где можно увидеть такое сообщение: "ошибка интернет соединения"

**Comment by Alex-302** [comment]
@vozersky 
ты точно с выключенными фильтрами проверял?

**Comment by vozersky** [comment]
@Alex-302 да.

**Comment by Alex-302** [comment]
Хм... С HTTPS, без фильтров, с упрощённой фильтрацией висит. Когда через Фидлер пускаю, то с десктопным Адгардом работает. А это правило подрезает рекламу
```
||newstube.ru/api/playera/getb?codePlacementId=$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/ 
```
@Revertron можешь глянуть в чём может быть дело?
Добавление newstube.ru в исключения https не помогает.

**Comment by ameshkov** [comment]
@Revertron any news on this?

**Comment by Revertron** [comment]
Checking...

**Comment by Revertron** [comment]
Added newstube.ru to ssl exceptions. It really weeps the llamas ass! (shows videos perfectly for me)
