### ISSUE TITLE
Two banks: SEB and Krediidipank not in whitelist

### ISSUE THREAD

**Issue by Jostikas** [AdguardTeam/AdguardForAndroid#712]
Domains:
ib.seb.se - SEB swedish
seb.ee - SEB estonian
ibank.ekp.lv - Krediidipank latvian
i-pank.krediidipank.ee - Krediidipank estonian

**Comment by ameshkov** [comment]
@Jostikas thank you!

Added to the default exceptions list:
https://github.com/AdguardTeam/AdguardForWindows/issues/911

@nkartyshov please update ssl exceptions list in the app

**Comment by nkartyshov** [comment]
done
