### ISSUE TITLE
App redesign

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#713]
So, we have to change a lot.

New design:
https://www.dropbox.com/sh/7rpxktts6j1g167/AAAkN4p4N1o4qeT2ovOZa3eJa?dl=0

**Comment by TPS** [comment]
This looks ___fantastic!___

**Comment by evgeniy-ADG** [comment]
On the third picture it asks if you want to log into account, does it mean there will be no need to type in an email every time we want to send a feedback or report an ad?

**Comment by ameshkov** [comment]
@evgeniy-ADG nope, it will be required for settings sync through an Adguard personal account.

**Comment by TPS** [comment]
@ameshkov: @evgeniy-ADG _does_ have a good idea, though, right?  @ least _pre-populate_ w/ that e-mail address, if account details are setup?  &/or pull customer/bug-reporter id# from that sync acct? (&/or, _please_ allow system auto-complete/-correct for that field?)

**Comment by ameshkov** [comment]
New design is finally ready, updated description.

Sneak peek:
![01-dashboard-onstart psd 2016-11-01 12-07-50](https://cloud.githubusercontent.com/assets/5947035/19885039/99f2a4b4-a02d-11e6-8d49-260ff3890f21.png)
![01-dashboard-onstart psd 2016-11-01 12-19-18](https://cloud.githubusercontent.com/assets/5947035/19885042/9d2eb83e-a02d-11e6-98d5-5b7ff4eda681.png)
![02-settings psd 2016-11-01 12-12-40](https://cloud.githubusercontent.com/assets/5947035/19885049/a103da02-a02d-11e6-824c-0e2604bf06f3.png)

**Comment by ameshkov** [comment]
Heh, here are some more then:)

**Apps management**
<details>
![32-app-management-cell psd 2016-11-01 16-19-57](https://cloud.githubusercontent.com/assets/5947035/19891070/79b3652c-a04f-11e6-982f-8ab145bf4e99.png)
</details>

**Filtering log** 🆕 
<details>
![21-log-filtering psd 2016-11-01 16-21-59](https://cloud.githubusercontent.com/assets/5947035/19891071/7bc8912a-a04f-11e6-8a95-f3b00eca4e53.png)
![21-log-filtering-details psd 2016-11-01 16-22-23](https://cloud.githubusercontent.com/assets/5947035/19891075/7d9f6514-a04f-11e6-80fc-49e423519d44.png)
</details>

**Comment by TPS** [comment]
Yesterday was Halloween (👻👹👺👽👾🗿💀🐲🐉👼👰💂:guardswoman:👮⛄️👸👶🚼🗽🐶🐕🐩🐱🦄🐨🐼🐯🐅🐧🐝😱🙀🎃🍬), but I'll get all my cavities today from all the _sweeeet_ teaser photos.   Good job, @AdGuardTeam!  But when do we get to play? :yum: :tongue:

**Comment by Bluscream** [comment]
Sadly the filtering log reminds me of the missing functionality to inspect element :(

**Comment by ameshkov** [comment]
> But when do we get to play?

It will take quite some time, I expect beta to arrive in January.
