### ISSUE TITLE
Apps with data allowed still can't connect

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#714]
STR:

1. Go to settings > firewall > disable connections for all apps
2. Restart filtering
3. Go to settings > apps and statistic and enable connection for chrome
4. Restart filtering
5. Chrome still has no access to the Internet

Please find the screen recording here: 1265212

Waiting for logs
state <details>
{
  "advancedPreferences" : {
    "pref.vpn.disable.pause" : false,
    "pref.har.capture" : false,
    "pref.vpn.ipv6.force" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.proxy.block.ipv6" : false,
    "pref.splash.enabled" : false,
    "pref.vpn.ipv6.disable" : false,
    "pref.vpn.capture" : false,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.vpn.ipv6.bypass" : false
  },
  "androidVersion" : "6.0.1 (sdk=23)",
  "appLanguage" : "fr",
  "applicationId" : "b54eeff3cee3086e",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "LGE LG-H850",
  "deviceSpeedRank" : 95,
  "dnsFilteringEnabled" : true,
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 5, 11, 113 ],
  "environment" : "beta",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "DEFAULT",
  "installedPackages" : [ "com.hy.system.fontserver;version=v4.20.6;system=true", "com.tmsoft.whitenoise.full;version=7.0.3;system=false", "com.android.LGSetupWizard;version=5.0.17;system=true", "com.skype.raider;version=7.08.0.557;system=false", "com.lge.videotool;version=5.0.9;system=true", "com.skvalex.callrecorder;version=2.2.7;system=false", "com.google.android.youtube;version=11.27.53;system=true", "com.vsco.cam;version=4.0.3;system=false", "com.nick.mowen.sceneplugin;version=8.4;system=false", "com.widmee.cipres.mycipres;version=1.0;system=false", "com.lge.sizechangable.weather.platform;version=5.0.14;system=true", "com.oasisfeng.greenify;version=2.9 beta 5;system=false", "com.android.providers.telephony;version=4.7.19;system=true", "com.miz.muzei.fivehundredpx;version=1.1;system=false", "com.IngDirectAndroid;version=4.3.0 12.05.2016;system=false", "net.monthorin.rttraffic16;version=2.0.22;system=false", "com.google.android.googlequicksearchbox;version=6.1.28.21.arm64;system=true", "com.android.providers.calendar;version=4.5.4;system=true", "com.utorrent.client;version=3.19;system=false", "com.gmail.heagoo.apkeditor;version=1.5.5;system=false", "com.syncedsynapse.eventflowwidget;version=1.6.4;system=false", "com.android.providers.media;version=6.0.1;system=true", "com.touchtype.swiftkey;version=6.3.8.73;system=false", "com.google.android.apps.docs.editors.docs;version=1.6.273.14.46;system=true", "com.lge.systemservice;version=6.0.1;system=true", "com.google.android.onetimeinitializer;version=6.0.1;system=true", "net.nurik.roman.muzei;version=2.1.1;system=false", "com.shazam.android;version=6.7.1-160719;system=false", "net.dinglisch.android.appfactory;version=4.8u5;system=false", "com.abcOrganizer;version=3.6.7.3;system=false", "com.qualcomm.shutdownlistner;version=6.0.1;system=true", "com.niksoftware.snapseed;version=2.7.0.125560650;system=false", "com.android.wallpapercropper;version=6.0.1;system=true", "com.teslacoilsw.launcher;version=4.3.1;system=false", "com.quicinc.cne.CNEService;version=1.0;system=true", "com.whi.android.DiskView;version=1.8;system=false", "com.roidapp.photogrid;version=5.213;system=false", "fr.francetv.pluzz;version=4.1.2;system=false", "com.lge.appbox.client;version=5.0.13;system=true", "de.stefanpledl.localcast;version=5.0.0.2-RC3;system=false", "com.lge.turkhiddenmenu;version=6.0.1;system=true", "com.samruston.flip;version=1.4.9;system=false", "com.lge.vrplayer;version=5.0.12;system=true", "com.lge.formmanager;version=4.70.5;system=true", "com.lge.lgdmsclient;version=2.4.1.1;system=true", "com.viber.voip;version=6.1.5.93;system=false", "com.viber.wink;version=1.0.0.223;system=false", "org.simalliance.openmobileapi.service;version=3.2.1;system=true", "keepass2android.keepass2android;version=1.0.0-d;system=false", "com.antutu.ABenchMark;version=6.1.4;system=false", "com.imdevgary.cinnamon;version=1.5.6;system=false", "com.android.documentsui;version=6.0.1;system=true", "com.lge.mirrorlink;version=1.1.2.6;system=true", "slide.cameraZoom.newcomposites;version=1.0.6;system=false", "com.android.externalstorage;version=6.0.1;system=true", "com.lge.android.atservice;version=6.0.1;system=true", "com.als.usagetimelines;version=1.12.1;system=false", "slide.cameraZoom.morecomposites;version=1.0.6;system=false", "com.android.htmlviewer;version=6.0.1;system=true", "com.rageconsulting.android.lightflow;version=3.65.05;system=false", "com.lge.wfd.spmirroring.source;version=1.0;system=true", "com.whatsapp;version=2.16.133;system=false", "com.lge.app.floating.res;version=2016-02-05;system=true", "com.picsart.studio;version=5.31.3;system=false", "fr.taxisg7.grandpublic;version=3.4.0;system=false", "fr.playsoft.teleloisirs;version=5.5.2;system=false", "com.lge.cloudhub;version=4.0.26;system=true", "slide.cameraZoom.composites;version=1.0.6;system=false", "com.android.mms.service;version=6.0.1;system=true", "com.lge.remote.lgairdrive;version=2.0.48;system=true", "com.google.android.apps.docs.editors.sheets;version=1.6.273.11.46;system=true", "com.lge.sui.widget;version=5.2.65;system=true", "com.google.android.apps.docs.editors.slides;version=1.6.273.10.46;system=true", "com.rhmsoft.edit;version=1.1.7;system=false", "com.android.providers.downloads;version=6.0.18;system=true", "com.lge.camera;version=5.0.83;system=true", "com.lge.touchcontrol;version=1.0;system=true", "org.kman.AquaMail;version=1.6.2.9;system=false", "com.paypal.android.p2pmobile;version=6.4.3;system=false", "ru.ming13.muzei.earthview;version=1.0.2;system=false", "com.insplisity.ultimatefullbodyworkouts;version=1.15;system=false", "ng.mekunu.soundload;version=1.0.2;system=false", "com.lge.eltest;version=1.0;system=true", "com.lge.LGSetupView;version=5.0.17;system=true", "com.hachette.vins;version=2.3;system=false", "com.lge.homeselector;version=5.0.6;system=true", "com.touchtype.swiftkey.beta;version=6.3.9.65;system=false", "finarea.MobileVoip;version=5.66;system=false", "com.lge.springcleaning;version=2.0.3;system=true", "com.koushikdutta.backup;version=1.1.4.2;system=false", "com.crucialtec.uaf;version=1.0;system=true", "com.qualcomm.qti.telephonyservice;version=6.0.1;system=true", "com.adobe.photoshopmix;version=1.2.512;system=false", "com.lge.gnsstest;version=6.0.1;system=true", "com.lge.fmradio;version=5.0.10;system=true", "com.noname81.lmt;version=2.6;system=false", "com.lge.miniclock.font.default;version=6.0.1;system=true", "eu.thedarken.sdm.unlocker;version=4.0.7;system=false", "com.google.android.configupdater;version=6.0.1;system=true", "com.microsoft.office.excel;version=16.0.7127.1010;system=false", "net.monthorin.autolaunch;version=1.0.9;system=false", "com.lge.lifetracker;version=5.0.19;system=true", "com.lge.smartshare.provider;version=1.0.19;system=true", "com.antutu.benchmark.full;version=6.1.1;system=false", "com.crucialsoft.fido.client;version=1.0.15;system=true", "com.android.defcontainer;version=6.0.1;system=true", "com.tssystems.photomate3;version=2.0;system=false", "org.zwanoo.android.speedtest;version=3.2.18;system=false", "com.android.providers.downloads.ui;version=6.0.9;system=true", "com.android.vending;version=6.7.13.E-all [0] 2920566;system=true", "com.android.pacprocessor;version=6.0.1;system=true", "com.qualcomm.cabl;version=1.0;system=true", "com.lge.myplace.engine;version=1.0.10.3;system=true", "vivino.web.app;version=8.10.4;system=false", "com.lge.shutdownmonitor;version=6.0.1;system=true", "com.lge.videoeditorres;version=6.0.1;system=true", "com.tktech.apps.apkmanager;version=2.2;system=false", "net.dinglisch.android.taskerm;version=4.8u5;system=false", "com.textra.emoji;version=2.0;system=false", "com.stupeflix.replay;version=1.1.0.1415-7c9f3d0;system=false", "com.android.certinstaller;version=6.0.1;system=true", "com.android.carrierconfig;version=1.0.0;system=true", "com.google.android.marvin.talkback;version=4.5.1;system=true", "com.urbandroid.lux;version=6.5;system=false", "com.lge.launcher2.theme.optimus;version=4.0.552;system=true", "com.lge.ia.task.smartcare;version=1.2.7;system=true", "com.symantec.familysafety;version=3.4.7.19;system=false", "com.customsolutions.android.utl;version=3.6;system=false", "com.asksven.betterbatterystats_xdaedition;version=2.2.0.0B6;system=false", "com.android.settingsaccessibility;version=5.00.31.2;system=true", "android;version=6.0.1;system=true", "com.hecorat.screenrecorder.free;version=4.0.1;system=false", "com.android.contacts;version=5.0.27;system=true", "com.eolwral.osmonitor;version=3.5.0.5;system=false", "eu.faircode.netguard;version=2.39;system=false", "com.qualcomm.wfd.service;version=2.0;system=true", "com.lge.smartshare;version=4.0.13;system=true", "com.lge.lockscreensettings;version=5.10.160215;system=true", "com.lge.lockscreen.livewallpaper.cat;version=5.0.3;system=true", "com.lge.gallery.vr.wallpaper;version=1.0.8;system=true", "com.qualcomm.qti.GBAHttpAuthentication.auth;version=6.0.1;system=true", "com.lge.ia.task.incalagent;version=2.1.3;system=true", "com.mightypocket.grocery.full;version=Full 4.0.151;system=false", "com.dporem.fiveadvancedconfig;version=1.3;system=false", "com.android.hotwordenrollment;version=6.0.1;system=true", "cast.meow.right.com.castformuzei;version=1.1;system=false", "com.android.mms;version=5.0.35;system=true", "com.android.nfc;version=6.0.1;system=true", "com.android.stk;version=2.0;system=true", "name.pilgr.appdialer;version=6.8-release;system=false", "com.android.backupconfirm;version=6.0.1;system=true", "ipnossoft.rma.free;version=4.1.3;system=false", "com.isaiasmatewos.texpand;version=1.5.6;system=false", "com.blackdivine.gleeden;version=2.1.9;system=false", "com.instagram.android;version=stub;system=true", "com.lge.iftttmanager;version=5.0.10;system=true", "uno.icon.pack.theme.marshmallow;version=4;system=false", "com.conducivetech.android.traveler;version=2.0.5;system=false", "com.lge.exchange;version=1.70.22;system=true", "com.cgollner.unclouded;version=2.3.2-play;system=false", "de.worldiety.athentech.perfectlyclear;version=4.1.1;system=false", "mobi.societegenerale.mobile.lappli;version=4.3;system=false", "org.coursera.android;version=2.2.5.1;system=false", "com.lge.wapservice;version=5.70.14;system=true", "com.android.statementservice;version=1.0;system=true", "com.lge.lockscreen.livewallpaper.kaleidoscope;version=5.0.2;system=true", "com.lge.mrg.service;version=5.0.2;system=true", "com.google.android.gm;version=6.4.120760496.release;system=true", "com.withings.wiscale2;version=2.16;system=false", "com.urbandroid.sleep.full.key;version=20141215;system=false", "kb2.soft.carexpenses;version=17.02;system=false", "com.playboxhd.cinema2;version=2.0.0;system=false", "com.android.calendar;version=5.0.13;system=true", "com.lge.ia.task.smartsetting;version=5.0.6;system=true", "com.lge.smartconfig;version=4.70.4;system=true", "com.coffeebeanventures.easyvoicerecorder;version=2.1;system=false", "com.joaomgcd.autoappshub;version=1.5.1;system=false", "com.audiomack;version=1.5;system=false", "com.lge.lgmapui;version=5.00.03;system=true", "uk.co.ashtonbrsc.android.intentintercept;version=2.2.3;system=false", "com.google.zxing.client.android;version=4.7.5;system=false", "com.lge.lgworld;version=5.0.5;system=true", "com.qualcomm.qti.auth.secureextauthservice;version=1.0;system=true", "com.sirma.mobile.bible.android;version=6.9.0;system=false", "com.google.android.setupwizard;version=2.0;system=true", "com.intangibleobject.securesettings.plugin;version=1.3.6;system=false", "com.qualcomm.qcrilmsgtunnel;version=6.0.1;system=true", "com.android.providers.settings;version=4.70.00;system=true", "net.ebt.appswitch;version=1.0.0.500;system=false", "com.android.sharedstoragebackup;version=6.0.1;system=true", "com.i7way.weighttracker;version=3.0.001;system=false", "slide.cameraZoom.coolborders;version=1.0.6;system=false", "com.google.android.music;version=6.7.2713Z.2790541;system=true", "com.android.printspooler;version=1;system=true", "radiotime.player;version=13.6.1;system=false", "com.uei.lg.quicksetsdk.irblaster;version=3.0.027;system=true", "com.tdo.showbox;version=4.65;system=false", "com.ti.server;version=1.0.0;system=true", "com.dvtonder.chronus;version=5.8.0.4;system=false", "dk.tacit.android.foldersync.full;version=2.9.6.124;system=false", "com.android.incallui;version=5.0.20.84;system=true", "com.android.frameworks.telresources;version=6.0.1;system=true", "com.lge.wfds.service.v3;version=3.1.8;system=true", "com.lge.drive.activator;version=1.2.17;system=true", "com.motionone.afterfocus_pro;version=1.3.3;system=false", "com.zvasvari.anmoneyp;version=1.15.5.20141101;system=false", "br.com.ctncardoso.ctncar;version=5.9;system=false", "com.lge.gnsspostest;version=2.0;system=true", "com.android.inputdevices;version=6.0.1;system=true", "com.rsupport.rs.activity.lge.allinone;version=5.0.7 (Build29);system=true", "com.orange.mysosh;version=2.12.0;system=false", "ca.sbstn.folderformuzei;version=2.0;system=false", "uk.co.nickfines.RealCalcPlus;version=2.3.1;system=false", "com.lge.gba.android;version=3.3.0;system=true", "aplicacionpago.tiempo;version=AP.1.3.0;system=false", "com.fb.glovebox;version=3.4.2.2;system=false", "com.lge.eula;version=5.0.8;system=true", "com.lge.gcuv;version=4.70.2;system=true", "com.lge.sync;version=5.0.2;system=true", "com.lge.task;version=5.0.3;system=true", "com.btows.photo;version=8.1;system=false", "com.adguard.android;version=2.7.153;system=false", "com.mxtech.videoplayer.ad;version=1.8.3;system=false", "com.lge.concierge;version=5.0.13;system=true", "com.google.android.apps.cloudprint;version=1.33b;system=false", "com.twitter.android;version=6.6.0;system=false", "mobi.beyondpod;version=4.2.11;system=false", "org.wikipedia;version=2.2.147-r-2016-06-06;system=false", "com.azumio.instantheartrate.full;version=2.5.7;system=false", "com.google.android.apps.docs;version=2.4.211.35.46;system=true", "com.google.android.apps.maps;version=9.32.1;system=true", "com.lge.sizechangable.weather.theme.optimus;version=5.0.14;system=true", "com.mobisystems.editor.office_registered;version=7.5.2129;system=false", "com.joaomgcd.autoapps;version=1.0.24;system=false", "com.adenclassifieds.android.cadremploi;version=4.5;system=false", "com.lge.qremote;version=5.0.17;system=true", "com.lge.gestureanswering;version=2.0;system=true", "com.datanasov.memoreminders;version=1.0.1;system=false", "com.microsoft.office.word;version=16.0.7127.1010;system=false", "org.fdroid.fdroid;version=0.100;system=false", "com.endomondo.android;version=16.6.2;system=false", "com.mobile_infographics_tools.mydrive;version=3.0.4.5;system=false", "com.urbandroid.sleep;version=20160718;system=false", "mobi.beyondpod.unlockkey;version=1.0.2;system=false", "com.android.cellbroadcastreceiver;version=5.0.7;system=true", "com.teslacoilsw.launcher.prime;version=D;system=false", "net.septime.capcaandroid;version=4.2.3;system=false", "com.google.android.webview;version=51.0.2704.81;system=true", "com.applay.overlay.pro;version=1.0.2;system=false", "com.yirgalab.dzzz;version=1.17;system=false", "com.microsoft.office.powerpoint;version=16.0.7127.1010;system=false", "com.lge.launcher3;version=5.1.11;system=true", "com.lge.musicshare;version=1.6.000;system=true", "com.android.server.telecom;version=5.0.20.84;system=true", "com.google.android.syncadapters.contacts;version=6.0.1;system=true", "com.lge.vragent;version=6.0.1;system=true", "com.android.facelock;version=6.0.1;system=true", "com.android.keychain;version=6.0.1;system=true", "com.intsig.ocrapi;version=1.0.3.20131207;system=false", "com.android.chrome;version=51.0.2704.81;system=true", "com.apec.jobboard;version=17.1.15;system=false", "digifit.virtuagym.foodtracker;version=1.7.3;system=false", "net.zedge.android;version=5.4.4;system=false", "com.android.gallery3d;version=5.1.17;system=true", "com.google.android.packageinstaller;version=6.0.1;system=true", "com.uzumapps.wakelockdetector.noroot;version=2.0.3;system=false", "com.google.android.gms;version=9.2.56 (440-124593566);system=true", "com.google.android.gsf;version=6.0.1;system=true", "com.google.android.tts;version=3.9.11;system=true", "com.lge.gnss.airtest;version=6.0.1;system=true", "com.lge.signboard.settings;version=5.00.160408-0;system=true", "com.lge.wifi.p2p;version=1.0.0;system=true", "com.android.calllogbackup;version=6.0.1;system=true", "air.com.adobe.pstouch;version=1.7.7;system=false", "com.lge.bluetoothsetting;version=5.0.27.1;system=true", "com.google.android.partnersetup;version=6.0.1;system=true", "ipnossoft.rma.oriental;version=2.5.1;system=false", "net.kosev.rulering;version=1.2.3;system=false", "com.google.android.videos;version=3.13.10;system=true", "com.gruebeltech.soundloaderpro;version=3.4.0;system=false", "com.lge.eodengine;version=4.53.6;system=true", "com.flavionet.android.camera.lite;version=3.2;system=false", "com.rageconsulting.android.lightflowlegacy;version=3.65.05;system=false", "com.android.proxyhandler;version=6.0.1;system=true", "com.lge.updatecenter;version=5.0.13;system=true", "com.urbandroid.mind.unlock;version=1.1;system=false", "com.dvtonder.chronus.modern;version=1.1;system=false", "com.coffitivity.coffitivity;version=1.0.2;system=false", "com.cloudmagic.mail;version=8.5.49;system=false", "com.google.android.feedback;version=6.0.1;system=true", "com.google.android.apps.photos;version=1.18.0.119671374;system=true", "com.google.android.syncadapters.calendar;version=5.2.3-99827563-release;system=true", "com.android.managedprovisioning;version=6.0.1;system=true", "com.remotefairy;version=4.1.5;system=false", "com.sika524.android.quickshortcut;version=2.4.0;system=false", "com.bongoman.apkrenamerholofree;version=2.0.1;system=false", "com.lge.voicerecorder;version=5.0.12;system=true", "com.lge.smartsharepush;version=5.0.23;system=true", "com.syntellia.fleksy.keyboard;version=8.3.2;system=false", "com.lge.filemanager;version=5.0.18;system=true", "com.freeman42.rutracker.client;version=1.6.3;system=false", "com.facebook.katana;version=stub;system=true", "ch.ethz.dcg.pancho2;version=0.97193;system=false", "com.modoohut.dialer;version=195;system=false", "com.acmeandroid.listen;version=4.4.1;system=false", "com.lge.intelligent;version=1.2.0205;system=true", "org.kman.AquaMail.UnlockerMarket;version=1.0.18;system=false", "com.cjb.listmasterpro;version=2.0.7;system=false", "com.joaomgcd.autovoice.unlock;version=1.0.7;system=false", "com.koushikdutta.backup.license;version=1.0.0.2;system=false", "com.android.providers.partnerbookmarks;version=5.70.15;system=true", "com.google.android.gsf.login;version=6.0.1;system=true", "com.kvadgroup.photostudio;version=1.33.3;system=false", "com.lge.qhelp.application;version=5.0.1;system=true", "com.android.wallpaper.livepicker;version=5.0.5;system=true", "fi.ohra.impetus;version=2.0.4;system=false", "com.indirvideo.net.mp3downloadonshazam;version=1.0;system=false", "com.modoohut.dialer.donate;version=81;system=false", "app.devgroup.com.amovies;version=8.0;system=false", "com.heetch;version=4.1.0;system=false", "com.android.apps.tag;version=1.1;system=true", "com.facebook.orca;version=80.0.0.15.69;system=false", "com.qualcomm.qti.seemp.service;version=6.0.1;system=true", "com.lge.easyhome;version=4.70.12;system=true", "asd.vector.indicators;version=2.15.4;system=false", "com.lge.hiddenmenu;version=6.0.1;system=true", "com.bigbro.ProcessProfiler;version=6.53;system=false", "com.lge;version=3.0.0;system=true", "com.house.noranuko.mediarescanner;version=1.0.49;system=false", "com.facebook.system;version=13.1;system=true", "com.gamelounge.chroomakeyboard;version=3.0.1;system=false", "in.blogspot.anselmbros.torchie;version=2.0;system=false", "com.iherb;version=5.1.22 R;system=false", "com.getkeepsafe.applock;version=2.2.1;system=false", "com.lge.networksettings;version=4.70.39.1;system=true", "com.lge.myplace;version=1.3.4;system=true", "com.boursorama.android.clients;version=4.0.9;system=false", "com.google.android.apps.translate;version=5.2.0.RC09.128106141;system=false", "com.lge.bnr.launcher;version=1.0.3;system=true", "com.adobe.psmobile;version=2.6.3;system=false", "com.google.android.backuptransport;version=6.0.1;system=true", "com.samruston.weather;version=1.6.6.4;system=false", "com.evernote;version=7.9.3;system=true", "com.lge.privacylock;version=5.0.16;system=true", "eu.thedarken.sdm;version=4.2.13;system=false", "com.lge.provider.signboard;version=5.00.160218-0;system=true", "com.oasisfeng.greenify.pro;version=2.3;system=false", "com.nextradiotv.bfmbusiness;version=2.4.2;system=false", "com.android.bookmarkprovider;version=6.0.1;system=true", "com.linkedin.android;version=4.0.53;system=false", "com.android.settings;version=5.0.20.0.25;system=true", "com.convertbee;version=1.3.1;system=false", "com.lge.lgfota.permission;version=6.0.1;system=true", "com.lge.lgaccount;version=3.8.20;system=true", "net.dinglisch.android.ipack.holdlightmd;version=1;system=false", "com.lge.sizechangable.weather;version=5.0.14;system=true", "com.teslacoilsw.notifier;version=5.0.6;system=false", "com.nitroxenon.terrarium;version=1.2.5;system=false", "com.quicinc.wbcserviceapp;version=1.0;system=true", "com.apptuners.keyplusapp;version=1.20;system=false", "com.textra;version=3.23;system=false", "com.urbandroid.lux.donate;version=1.6;system=false", "com.android.calculator2;version=5.0.8;system=true", "fr.tf1.mytf1;version=6.2.12;system=false", "com.qualcomm.location;version=1.0;system=true", "com.qualcomm.simcontacts;version=6.0.1;system=true", "com.sixtyfourthirtytwo.terra;version=2.1;system=false", "com.lge.NfcSettings;version=5.0.28;system=true", "pl.solidexplorer2;version=2.1.18;system=false", "cn.xender;version=3.2.0718;system=false", "ccc71.at;version=1.3.3;system=false", "com.google.android.apps.chromecast.app;version=1.16.7;system=false", "com.intsig.BizCardReader;version=5.6.5.20160701;system=false", "com.qualcomm.qti.tetherservice;version=1.0;system=true", "com.lge.eulaprovider;version=5.0.8;system=true", "com.lge.bnr;version=5.0.27;system=true", "com.lge.ime;version=6.6.22;system=true", "com.lge.lpd;version=4.52.20;system=true", "com.lge.mlt;version=5.0.5;system=true", "com.hybrid.stopwatch;version=2.0.8.4;system=false", "fr.m6.m6replay;version=4.2.3;system=false", "com.viadeo.android;version=3.5.2;system=false", "com.americanexpress.android.acctsvcs.fr;version=3.6.1;system=false", "com.lge.phonemanagement;version=5.0.11;system=true", "com.camsam.plus;version=2.7.5;system=false", "jp.co.recruit.mtl.beslim;version=3.1.6;system=false", "com.android.vpndialogs;version=6.0.1;system=true", "com.lge.videoplayer;version=5.0.16;system=true", "com.qualcomm.location.XT;version=1.0;system=true", "com.soundcloud.android;version=2016.07.13-release;system=false", "com.applay.overlay;version=2.5.4;system=false", "ru.mail;version=4.0;system=false", "com.lge.lgdrm.permission;version=6.0.1;system=true", "com.appgenix.bizcal;version=2.14.5;system=false", "com.lge.miniclock.font.aod_default;version=6.0.1;system=true", "com.lge.wifisettings;version=5.0.46.1;system=true", "com.google.android.talk;version=8.0.116581895;system=true", "com.quoord.tapatalkpro.activity;version=6.0.11;system=false", "com.urbandroid.mind;version=3.2;system=false", "com.lge.ime.theme.black;version=3.0.17;system=true", "com.android.phone;version=5.0.20.84;system=true", "com.android.shell;version=6.0.1;system=true", "nexbit.icons.moonshine;version=2.2;system=false", "com.lge.drmservice;version=6.0.1;system=true", "com.lge.videostudio;version=5.0.10;system=true", "com.lge.sizechangable.musicwidget.widget;version=5.0.6;system=true", "com.omichsoft.taskmanager;version=2.8.2.4;system=false", "slide.cameraZoom;version=6.2.1;system=false", "com.alensw.PicFolder;version=4.6.9.1479;system=false", "com.android.providers.userdictionary;version=6.0.1;system=true", "com.aviary.android.feather;version=4.6.2;system=false", "slide.cameraZoom.pictureframes;version=1.0.6;system=false", "com.lge.lteconfig;version=1.41223;system=true", "com.lge.ime.dictionary.xt9;version=9.9.6;system=true", "com.rahul.DownloadEverythingProo;version=13.1;system=false", "com.joaomgcd.autonotification;version=2.5.19;system=false", "com.lge.cic.eden.service;version=5.0.9;system=true", "de.hp.taskmanager;version=4.9;system=false", "com.customsolutions.android.utl_license;version=1.2;system=false", "com.intsig.camscanner;version=4.0.1.20160620;system=false", "com.lge.gnsslogcat;version=1.0;system=true", "com.android.location.fused;version=6.0.1;system=true", "com.android.systemui;version=5.10.160215;system=true", "com.lge.provider.systemui;version=6.0.1;system=true", "com.lge.ia.task.s4urecommender;version=4.24.4;system=true", "kellinwood.zipsigner2;version=3.4;system=false", "com.android.bluetoothmidiservice;version=6.0.1;system=true", "com.qualcomm.qti.confdialer;version=6.0.1;system=true", "com.lge.provider.lockscreensettings;version=6.0.1;system=true", "com.lge.aodex;version=5.0.7;system=true", "com.lge.clock;version=5.0.14;system=true", "com.lge.email;version=6.70.22;system=true", "com.fabernovel.ratp;version=3.4.3.15;system=false", "com.facebook.appmanager;version=13.1;system=true", "com.lge.leccp;version=2.1.17;system=true", "com.lge.music;version=5.0.18;system=true", "com.lge.qhelp;version=5.0.9;system=true", "com.ebay.mobile;version=5.2.0.25;system=false", "com.joaomgcd.autoinput;version=2.0;system=false", "org.withouthat.acalendarplus;version=1.9.1;system=false", "com.lge.ia.task.informant;version=4.24.5;system=true", "fr.cnamts.it.activity;version=7.5.1;system=false", "com.joaomgcd.autovoice;version=2.0.47;system=false", "com.lge.remote.setting;version=2.0.19;system=true", "co.thefabulous.app;version=3.16;system=false", "com.lge.inputdevices;version=6.0.1;system=true", "com.lge.friendsmanager;version=5.0.12;system=true", "com.cpuid.cpu_z;version=1.19;system=false", "com.lge.hiddenpersomenu;version=6.0.1;system=true", "ru.kinopoisk;version=3.6.0;system=false", "com.crucialsoft.asm;version=1.0;system=true", "com.lge.lginstallservies;version=5.0.8;system=true", "com.lge.signboard;version=5.00.160610-0;system=true", "fr.francetv.apps.info;version=4.9.1;system=false", "com.google.android.apps.adm;version=1.4.4;system=false", "com.android.bluetooth;version=6.0.1;system=true", "com.qualcomm.timeservice;version=6.0.1;system=true", "com.qualcomm.atfwd;version=6.0.1;system=true", "com.android.providers.contacts;version=5.0.27;system=true", "com.lge.snappage;version=5.0.12;system=true", "com.lge.servicemenu;version=1.0;system=true", "com.android.captiveportallogin;version=6.0.1;system=true", "com.phinxapps.pintasking;version=1.0.9;system=false", "net.cwfk.ig88.intents;version=1.2;system=false", "com.snapchat.android;version=9.35.1.0;system=false", "com.google.android.diskusage;version=3.7.1;system=false", "com.hp.android.printservice;version=2.13-2.1.1-11c-16.2.15-86;system=false", "com.kiwlm.mytoodle;version=6.0.0;system=false", "com.lge.qmemoplus;version=5.0.18;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.18.20-perf-g4952193-00001-g040cc73",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : false,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : "{\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:1; Blocked banners:171859; Traffic saved:4491313152;",
  "trial" : false,
  "updateChannel" : "BETA",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.7.153",
  "whitelist" : [ ]
}

**Comment by ameshkov** [comment]
@evgeniy-ADG this is because DNS requests are blocked. To fix this you should allow "Android OS" app to connect to the internet.

In the next beta version we will introduce a new "meta app" named DNS, so user could allow net access for mere DNS.
