### ISSUE TITLE
"Ongoing" notification messes with device sounds

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#716]
Check out this video:
https://www.dropbox.com/s/wu29tn5ol1modfw/VID_20160723_130629.mp4

It appears that when our notification is active, Android cease to play music.

**Comment by Revertron** [comment]
Samsung strikes back!
As I thought - our notifications with default flags are seen by samsungs "OS" as "long audio focus", not short one as it should be.
I've given a test build to the user - he can not repeat the problem on it.
The build has one difference:
`builder.setDefaults(Notification.DEFAULT_VIBRATE | Notification.DEFAULT_LIGHTS);` - without sound, and not the `builder.setDefaults(Notification.ALL);` as we were using for years.

**Comment by Revertron** [comment]
User has checked - it works perfectly.
