### ISSUE TITLE
Site with ads 

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#718]
http://pocketnow.com/2016/06/23/oneplus-3-ota
Just in Android version of the site.
![g9funxjqz40](https://cloud.githubusercontent.com/assets/20476168/17139433/0fa506c6-534d-11e6-9408-c38049eec8ab.jpg)
![g9funxjqz40](https://cloud.githubusercontent.com/assets/20476168/17139435/118242ce-534d-11e6-91ea-0c7f951679b8.jpg)

**Comment by ameshkov** [comment]
@Alex-302 please take a look

@Fridrix next time create an issue in https://github.com/AdguardTeam/AdguardFilters repo:)

**Comment by Alex-302** [comment]
Added to English filter
```
||asv.whatismyip.win^$third-party
```
Added to Experimental filter
```
pocketnow.com##div+center > small
```
