### ISSUE TITLE
[Feature request] Add an ability to blacklist specific YouTube channels

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#728]
Taken from https://forum.adguard.com/index.php?threads/major-issue-with-adguard-and-nplayer-app-remote-page.12238/

**Comment by ameshkov** [comment]
In Nougat we'll lose the ability of https decryption for YT app, so it will be impossible to do anyway.

**Comment by ameshkov** [comment]
"Always-ON VPN" is what you need
