### ISSUE TITLE
Idealo app has no connection with Aguard Enabled

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#729]
Link to the app
https://play.google.com/store/apps/details?id=de.idealo.android&hl=en
Screenshots
![hbn3s8xnlxs](https://cloud.githubusercontent.com/assets/20476168/17275619/1e150e04-5717-11e6-8e70-16467c4bd14e.jpg)
![9cn-u2asqii](https://cloud.githubusercontent.com/assets/20476168/17275620/1e179eee-5717-11e6-8fd8-b3971aac9a95.jpg)

**Comment by nkartyshov** [comment]
done
