### ISSUE TITLE
Blocking traffic some time after device reboot

### ISSUE THREAD

**Issue by 192848** [AdguardTeam/AdguardForAndroid#737]
id 1212839
После перезагрузки устройства спустя некоторое время блокируется весь трафик
И снова после перезагрузки устройства - все ок.
Видео:
https://drive.google.com/file/d/0B8GmXLzD8C-AVDFzMWJnTXBsX0k/view?usp=drivesdk
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/397364/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/397365/state.txt)

**Comment by ameshkov** [comment]
Видел эту проблему, на 4pda. Пока идей не особо, вот бы Android обновить

**Comment by TPS** [comment]
#520-ish, to my mind.

**Comment by ameshkov** [comment]
@TPS nope, the issue here is that all network traffic is blocked after VPN has started.

I have no clue why it's happening, looks like a firmware bug to me.

**Comment by TPS** [comment]
Oh, right, <kbd>Bug</kbd>, not <kbd>Enhancement</kbd>! Oops!

**Comment by ameshkov** [comment]
No updates on this issue, closing
