### ISSUE TITLE
Make a list for "Block data when screen is off" feature

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#739]
The feature to block cellular or wifi data when the screen is off
should work as a separated whitelist. I mean a list where I add the
apps that I want so it will be easier to know which apps are allowed
or blocked. Right now you have to go one by one and is not very
friendly. Either this or allow filters and sorting in the apps list.
The list should include as well small icons to know the status of this
settings. It is not clear what happens when a new app is installed I
guess it will be allowed by default, what if I want to change this
policy to default deny, there should be a setting as well.

https://github.com/AdguardTeam/AdguardForAndroid/issues/176

**1073860**

**Comment by lordraiden** [comment]
By the way I would try to make completely clear that is a very useful feature to save battery

**Comment by lordraiden** [comment]
And an option to delay x second the close of the connections after the screen is off

**Comment by ameshkov** [comment]
> I mean a list where I add the apps that I want so it will be easier to know which apps are allowed
or blocked. Right now you have to go one by one and is not very friendly
> The list should include as well small icons to know the status of this
settings

Makes sense, we'll try to take this into account in app redesign ( #211 )

> It is not clear what happens when a new app is installed I guess it will be allowed by default

It will use settings from the "defaults" section right after the installation.

**Comment by TPS** [comment]
This is actually true for almost _any_ of the settings now buried in the app firewall settings, where this wasn't true before the redesign.  Will _all_ these settings be incorporated in this/multiple table(s)?

Also, now there are multiple/redundant ways to get to firewall, but none from main AG screen.  Will this/these table(s) have quick accessibility, or will they be hidden, also?

**Comment by ameshkov** [comment]
Covered by the "batch actions" we added earlier.

UI markers for the "screen is off" settings are part of another issue.
