### ISSUE TITLE
Adguard closes after being swiped away on Huawei devices

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#742]
Notification settings are default, autostart enabled etc. 

Other details are available in forum thread:
https://forum.adguard.com/index.php?threads/12360/#post-94128

**Comment by Revertron** [comment]
Again, I am proposing starting some WatchDog service in another process that will take care of killed Adguard.

**Comment by ameshkov** [comment]
Dup for #1067
