### ISSUE TITLE
Installing certificate for Firefox as non-default browser in Andorid 6.0

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#744]
In android 6.0 if Firefox (or a firefox based browser) is not the default browser, it's not possible to install a user certificate for https filtering in Firefox. This is because Android hides all other browsers from the "open with" screens when a browser is set as default. Clearing defaults for Chrome every time is however tedious, and not everyone will think to clear defaults.
I was hoping it would be possible to find a way to detect browsers even if they're hidden like this.

**1140536**

**Comment by Revertron** [comment]
Just try to use "Alternative installation" - it will save certificate to sdcard.
Then, try to navigate to that file in Firefox: file:///sdcard/adguard.crt
