### ISSUE TITLE
Firewall 'Defaults' settings bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#745]
If you tap on any of the settings there (e.g. Cellular data), no matter which option you choose then ("No" or "Change"), the settings is changed.

Originally from https://forum.adguard.com/index.php?threads/adguard-for-android-v-2-7.12680/#post-95765

**Comment by ameshkov** [comment]
This is totally expected. The problem here is with the text we show. It is really unclear now what is it about.

**Comment by Revertron** [comment]
I think that the user didn't try to read the actual, well formulated, text in that dialog.
I don't think that we can formulate it any clearer.

**Comment by SlowMemory** [comment]
>I think that the user didn't try to read

To defend myself a bit, I think the UI is not user-friendly. Each checkbox should represent a single state, it is not intuitive to use it as a button. Just my opinion.
