### ISSUE TITLE
Allow user to select filters update check period

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#746]
To make it simple let's make just a simple combobox:
Default
1 hour
3 hours
6 hours
12 hours
24 hours
48 hours

@nkartyshov check how `FilterServiceImpl.UPDATE_INVALIDATE_PERIOD` is used.
Do not allow "too small" values for it. If preference value is lower than 1 hour, fallback to default.

**Comment by nkartyshov** [comment]
done

**Comment by ameshkov** [comment]
In order for it to work properly we should set the job period to 30 minutes:
https://forum.adguard.com/index.php?threads/filters-update-check-period-not-working-properly.15554/

**Comment by nkartyshov** [comment]
done

**Comment by TPS** [comment]
When this automatic check is done after period elapses, is there a toast (like for manual check) showing result, or is this completely silent?  I'd prefer a toast @ least anytime an update suceeds, & maybe even when there _isn't_ any change.

_(Just for future reference, https://github.com/AdguardTeam/AdguardForAndroid/issues/574#issuecomment-223562076 attempted to first requested customized interval, IIRC.)_

**Comment by ameshkov** [comment]
@TPS it is silent, toast on every update check would be just too annoying.

**Comment by TPS** [comment]
Should I open a _new_ issue to request an option for a toast on every _successful_ update?  *I*'d like the option.

**Comment by ameshkov** [comment]
> Should I open a new issue to request an option for a toast on every successful update? I'd like the option.

Yeah, it should be filed as a separate issue:)

**Comment by TPS** [comment]
This period seems not work anymore since last app update or 2 (e.g., "last update" message @ bottom of main screen isn't reflecting update every ➊ hour, as I've configured, though it does show time of last _manual_ update several hours earlier).
