### ISSUE TITLE
Some apps started to bypass Firewall after updating to 2.7

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#748]
id 1145740

HUAWEI PE-TL10

"Добрый день. Устройство подключено к спутниковому терминалу, в котором присутствует индикация количества данных в реальном времени. Все приложения, включая системные заблокированы брэндмауэром, за исключением необходимых. В версии 2.6 счетчик общего трафика совпадал со счетчиком на терминале. После обновления до версии 2.7 с сохранением настроек, на спутниковом терминале, была отмечена постоянная передача данных, чего быть не должно. Счетчик приложения показывает объем полученных данных в несколько раз ниже чем счетчик на терминале. После включения брэндмауэра "Доктор Вёб" проблема исчезает. Объем данных показанный счетчиком брэндмауэра Доктор Вёб" и терминалом совпадает. "

**Comment by ameshkov** [comment]
На форуме еще такая жалоба есть, что-то пролезает

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/765
