### ISSUE TITLE
App Google settings

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#749]
id 1394429
https://play.google.com/store/apps/details?id=com.google.android.gms&hl=ru
При входе  в приложение настройки Google -> Безопасность и вход (или раздел Настройки аккаунта) выходит сообщение, что "передача данных по сети недоступны".

Помогает полное отключение HTTPS (конкретно для приложения не помогает).
<details>
![screenshot_94](https://cloud.githubusercontent.com/assets/18548949/17676102/7dfbb406-6335-11e6-9d19-bd9374862902.jpg)
![screenshot_95](https://cloud.githubusercontent.com/assets/18548949/17676103/7dfe8f96-6335-11e6-9bb5-62e7777acc1e.jpg)

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/749
