### ISSUE TITLE
Can't open some of https websites while connected to mobile network.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#750]
**id 1394891** 

LGE LG-D855
Android 4.4.2
Adguard 2.7.220

"I have a problem with the use of HTTPS over the cellular network. I have set the program to filter out HTTPS traffic. When I use WiFi everything works well but when I use the networks of mobile connection I can't open pages HTTPS. I do not know what the problem is that by the mobile network can't be viewed pages (https)"

**logs here:** [logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/421009/logs.zip)

**Comment by vozersky** [comment]
pref.vpn.ipv6.force   didn't help

**Comment by ameshkov** [comment]
Does it help to turn HTTPS filtering off for these websites?

**Comment by vozersky** [comment]
@ameshkov 

"If you turn off HTTPS filtering that these pages open correctly. What is interesting is that the while the HTTPS filtering through WiFi network everything works properly. The problem occurs only when I use the mobile network. If you switch to the HTTP Proxy is also everything is working properly. The problem occurs only when I switched to the Local VPN (problem with mobile network)"

**Comment by ameshkov** [comment]
@vozersky it is not clear from the log what happens, I don't see any pages loaded while user was on cellular data.

Could you please ask user to reproduce the issue and record one more "debug"-level log. I need to know exact timing.

**Comment by vozersky** [comment]
@ameshkov will do

**Comment by vozersky** [comment]
@ameshkov New set of logs: [logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/442458/logs.zip) 
"event time 14.42 to 14.45"

**Comment by Revertron** [comment]
Mobile APN is internetipv6 - the user has ipv6 internet.
From the logs:
```
Interface: rmnet0 (rmnet0) [rmnet0][2][/2a00:f41:500b:749:5fac:e9e3:e03:c9fc%2%2][/fe80::5fac:e9e3:e03:c9fc%rmnet0%2] isUp = true
Found IPv6 address for network [rmnet0][2][/2a00:f41:500b:749:5fac:e9e3:e03:c9fc%2%2][/fe80::5fac:e9e3:e03:c9fc%rmnet0%2]
IPv6 does not work in Android 4.4.X with kernel 3.4: https://code.google.com/p/android/issues/detail?id=63349
```
We can not work with IPv6 on this device. Let the user use automatic proxy mode as he is using in the beginning of the log.
Issue is closed.
