### ISSUE TITLE
Pac proxy + Adguard

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardForAndroid#751]
Суть такова. В настройках WIFI прописан автопрокси - https://antizapret.prostovpn.org/proxy.pac для обхода блокировок сайтов. Реклама на примере rutracker.org проскакивает. 
![0b2461d8-63d7-11e6-9613-5650b59b7530](https://cloud.githubusercontent.com/assets/10572914/17728393/b71ccec2-6467-11e6-990c-a5c429822ca3.png)
![48b343c6-63d6-11e6-8639-8174a9eee70c](https://cloud.githubusercontent.com/assets/10572914/17728392/b71a91a2-6467-11e6-8a2c-0628cbba4da6.png)

**Comment by ameshkov** [comment]
I suggest two things:
1. Add new "low level" setting: `pref.ports` with the list of ports which are filtered by AG.
2. Default value should be 80, 443, 3128

**Comment by ameshkov** [comment]
Moved to a new issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/796

**Comment by vozersky** [comment]
still doesn't work
reproduced with the latest build

based on forum [topic](https://forum.adguard.com/index.php?threads/%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8-%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2-%D0%A0%D0%9A%D0%9D.15037/)

**Comment by vbagirov** [comment]
Still duplicate :)
