### ISSUE TITLE
All internet traffic is getting blocked after updating to 2.7.220

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#752]
id 1008894

"samsung SM-G930F"

please check the log files:  [Archive.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/423322/Archive.zip)

turning protection off solves the problem for user

**Comment by evgeniy-ADG** [comment]
Customer reinstalled Adguard, but it didn't help, unfortunately.

**Comment by vozersky** [comment]
same issue here:

id 1396817
[1396817.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/432495/1396817.zip)


id 1397036
[1397036.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/432496/1397036.zip)

**Comment by evgeniy-ADG** [comment]
>please look at time of 12.00 onwards. the incoming whatsapp call
was blocked and a new call was initiated by me. while the call was
ongoing adguard blocked the traffic flow and the call dropped. a new
call was then initiated by me.

[debug (1).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/442222/debug.1.txt.zip)

**Comment by ameshkov** [comment]
> id 1008894
> "samsung SM-G930F"

I guess something is not ok with the power saving mode:
`Device is in power saving mode`

**Comment by ameshkov** [comment]
> id 1396817 OnePlus ONEPLUS A3003
> 1396817.zip

@vozersky I see nothing suspicious in the log. I need to know exact timing of the issue.

**Comment by ameshkov** [comment]
> id 1397036 "samsung SM-G930F"
> 1397036.zip

@vozersky just like the original log, I don't see anything suspicious except that the device in power saving mode. However, I see that user has not turned off battery optimizations for our app.

**Comment by ameshkov** [comment]
> 1008894

@evgeniy-ADG this has nothing to do with the issue we discuss here.
Please advise user to turn AG off for whatsapp app.

**Comment by vozersky** [comment]
@evgeniy-ADG or at least https-filtering
