### ISSUE TITLE
Google Duo compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#753]
App:
https://play.google.com/store/apps/details?id=com.google.android.apps.tachyon&hl=en

Source:
http://forum.xda-developers.com/showpost.php?p=68233150&postcount=1553
http://forum.xda-developers.com/showpost.php?p=68240915&postcount=1555
http://forum.xda-developers.com/showpost.php?p=68242588&postcount=1556

It's possible to be caused by https filtering.

**Comment by Bohdan-SUP** [comment]
Yes, disabling HTTPS filtering helped me.

**Comment by Hostile** [comment]
sort it out

**Comment by nkartyshov** [comment]
Added
