### ISSUE TITLE
Google account settings issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#754]
Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=52182842

> [quote name="azazelo37" date="15.08.2016, 22:31" post="52194554"]
> Помогает полное отключение HTTPS (конкретно для приложения не помогает).
> [/quote]
> 
> Скорее всего запрос этот делается другим приложением (так часто у гугла бывает).
> Мы проверим и разберемся.

**Comment by Alex-302** [comment]
I can't fix it. It is caused by HTTPS filtering, tried to completely exclude  `com.google.android.syncadapters.contacts` but nothing.

**Comment by ameshkov** [comment]
Hm, could you reproduce this issue on your device?

**Comment by Alex-302** [comment]
Yes.

**Comment by ameshkov** [comment]
@Alex-302 could you please attach the full log?

**Comment by Alex-302** [comment]
[adguard.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/430547/adguard.txt)
done.
I made unnecessary start/stop protection in the end...

**Comment by ameshkov** [comment]
@Alex-302 does it help to add "android.clients.google.com" domain to the SSL whitelist?

**Comment by Alex-302** [comment]
Nothing.
Also tried to exclude accountsettingsmobile-pa.googleapis.com.
New full 
[adguard.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/442297/adguard.txt)
log

**Comment by ameshkov** [comment]
@Alex-302 excluding `accountsettingsmobile-pa.googleapis.com` is a good idea.

However, I see that in this log AG tries to filter HTTPs for it. Are you sure the log is recorded after you've excluded it?

**Comment by Alex-302** [comment]
Yes, the log was capltured before excluding `accountsettingsmobile-pa.googleapis.com`
But I can't reproduce this issue now without exclusions(also after reboot)...

**Comment by ameshkov** [comment]
Weeird. Anyway, we'd better exclude both domains just in case:
`accountsettingsmobile-pa.googleapis.com`
`android.clients.google.com`

**Comment by nkartyshov** [comment]
@Alex-302 Please, check the Google Settings

**Comment by Alex-302** [comment]
@nkartyshov The issue is still exists.

**Comment by nkartyshov** [comment]
@gshumihin Please, check work the Settings Google

**Comment by gshumihin** [comment]
For me Google Settings works just fine. And I never faced that issue.

**Comment by Alex-302** [comment]
@nkartyshov 
new log
https://mega.nz/#!QUlyzaYZ!WfbACL-ZxXSnMx6BGlo69WkEA1vgydSusR1EyICPi2A

**Comment by nkartyshov** [comment]
#850

**Comment by ameshkov** [comment]
@nkartyshov aside of the HTTP/2 issue, how comes that, according to the log, Adguard still filters HTTPS for `accountsettingsmobile-pa.googleapis.com` ?

**Comment by nkartyshov** [comment]
Adguard did not filters requests for accountsettingsmobile-pa.googleapis.com, but checks request for bypass.
