### ISSUE TITLE
Add List-KR to the list of filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#756]
@nkartyshov it should be default for Korean users.

**Comment by ameshkov** [comment]
Isn't it done?

**Comment by Revertron** [comment]
Yes, done.

**Comment by ameshkov** [comment]
@Revertron have you made it default for Korea?

**Comment by ameshkov** [comment]
@Revertron the filter is not present when you do clean install

**Comment by Revertron** [comment]
Arrrgh, precisely! I didn't set dns and this filters to export from database in prepare phase.
Fixed!
