### ISSUE TITLE
Adguard doesn't restart protection after connecting to network (Huawei)

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#758]
id 1373719
the same issue with both Adguard 2.6 and 2.7 on Huawei device, process is not killed, but Adguard doesn't restart protection after connecting to network.

please advise

**Comment by vozersky** [comment]
@ameshkov

**Comment by ameshkov** [comment]
@vozersky I am almost sure it is.

I could tell more if you get me debug-level log file along with exact timings of the issue.

**Comment by vozersky** [comment]
@ameshkov     here's what user have sent to us: 
[logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/442359/logs.zip)

**Comment by vozersky** [comment]
новый лог: 
[Archive.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/445508/Archive.zip)

"Примерно в 22-19 включение телефона,  adguard не реагирует.  В 22-21 вход в adguard после чего фильтрация восстановилась"

**Comment by ameshkov** [comment]
@vozersky the weird thing is that log starts at 22:21:26.858.

Also app was running all the time, maybe it was in some sort of a "hibernate" state?

**Comment by evgeniy-ADG** [comment]
> Телефон выключался как обычно - короткое нажатие кнопки питания (выключение экрана). Физически (долгое нажатие кнопки питания с последующим выбором "Выключить") не производилось.
Больше добавить нечего. По ощущениям, все как я писал - в 8 случаях из 10 возобновляет фильтрацию. Зависимости от времени, в течение которого телефон спал, я не заметил. Может всю ночь пролежать и утром нормально возобновить фильтрацию. А может через пол-часа сна не возобновить. Видео, как это происходит, я высылал.

**Comment by ameshkov** [comment]
@evgeniy-ADG

The problem is that the app does not receive any notifications of a device state change. We also cannot control it from the app. It seems as if it was somehow hibernated and locked.

Does it help to enable "pref.vpn.disable.pause"?

**Comment by vozersky** [comment]
seems to be an outdated issue
works fine on Huawei Nova (EMUI 5.0)
