### ISSUE TITLE
Always-on VPN feature doesn't work with Adguard

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#760]
https://www.privateinternetaccess.com/forum/discussion/18700/android-how-to-use-allways-on-vpn

> Why can't I use the 'always on VPN' feature of Android for Adguard? Is
> there a workaround?

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17896854/be697f48-695a-11e6-81fa-1cc08f94d856.png)

**Comment by TPS** [comment]
I previously discussed this w/ @ameshkov (a tiny bit 😉) @ https://github.com/AdguardTeam/AdguardForAndroid/issues/2#issuecomment-151726474.

**Comment by ameshkov** [comment]
Relevant discussion on our forum:
https://forum.adguard.com/index.php?threads/always-on-vpn-in-android-7.13186/

**Comment by Revertron** [comment]
That guy writes about VPN connections in android, that are done by system itself. NOT BY APP.
We can not do this.
If somebody wants Adguard to be always on, just let him use our advanced option - "pref.vpn.disable.pause".

**Comment by TPS** [comment]
@Revertron As mentioned in #520, `pref.vpn.disable.pause` doesn't consistently solve the problem _w/o_ external app workarounds.

I don't think any of us care about _how_ the solution is implemented, only that it's simple (even transparent) to the user — not messing about with arcane details — & doesn't involve messing around w/ 3<sup>rd</sup>-party apps.

**Comment by ameshkov** [comment]
Still `pref.vpn.disable.pause` is the only possible solution. This particular case is about classic VPN setup which is not applicable in our case.

**Comment by TPS** [comment]
<Summary>I think this should be reopened, as Android 7/Nougat opens this up for VPN apps, given correct configuration via <a target="_tab" href="https://goo.gl/yyKLWQ">`setAlwaysOnVpnPackage` (⚠️ Warning! Giant confusing webpage!  Click into new tab & let it load!) </a> & related functions, which AG doesn't (yet 🤞) have:
<Details>
![ag always-on-vpn fail](https://cloud.githubusercontent.com/assets/185902/25158177/5155b202-2474-11e7-9fdd-22fd88ea2b26.png)
</Details>
</Summary>

**Comment by TPS** [comment]
![ag always-on-vpn fail](https://cloud.githubusercontent.com/assets/185902/25158882/a71476d8-2479-11e7-987a-104a86ed3456.png)

There, that should work!

**Comment by ameshkov** [comment]
@TPS nice catch!

But this method is usable by the system apps only:
> Called by a device or profile owner to configure an always-on VPN connection through a specific application for the current user. This connection is automatically granted and persisted after a reboot.

**Comment by ameshkov** [comment]
Oh, it's usable by device admin apps, interesting.

**Comment by TPS** [comment]
[Yep, reportedly, OpenVPN _does_ have this included.](https://android.stackexchange.com/questions/163316/always-on-vpn-in-android-nougat-does-not-prevent-traffic-leakage)

**Comment by TPS** [comment]
@ameshkov You forgot to re-open.… 🤔

**Comment by ameshkov** [comment]
Just installed Android O Beta.

So, it appears that from now on you can now manually set it up:
![screenshot_20170526-190857](https://cloud.githubusercontent.com/assets/5947035/26502830/07c1a54c-4247-11e7-9a1e-89e17aacf623.png)

**Comment by ameshkov** [comment]
It is not exactly the same feature as requested, so I created a new issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1240

**Comment by TPS** [comment]
Amazon ß still stuck @ v2.9.70.  Did _AG_ RE: always-on VPN change from then 'til v2.9.98 (above), or is that purely #1240 (_Android O_ feature)?  I'm likely to be on N for foreseeable future, so I'm still hoping for a solution I can use.… :bow:

**Comment by ameshkov** [comment]
> Amazon ß still stuck @ v2.9.70

We will soon publish the new beta version.

> Did AG RE: always-on VPN change from then 'til v2.9.98 (above), or is that purely #1240 (Android O feature)? I'm likely to be on N for foreseeable future, so I'm still hoping for a solution I can use.… 

We'll first experiment with Android O and AG v2.9 and see how it works and what are the possible issues.

Then we may add the device admin features, but I can't yet give you an ETA on this, too many features are planned for the future:(

**Comment by TPS** [comment]
Delay's ok:  Some of your findings in #1240 are giving me concern.  I'd rather have it right,  than right now, especially since waiting all this time, anyway.  I'm glad both N & O are currently Google-supported, as that gives me hope issues will be resolved w/ less workarounds.

For the record, what _is_ the device you're testing all this on?

**Comment by ameshkov** [comment]
> For the record, what is the device you're testing all this on?

Pixel

**Comment by TPS** [comment]
I just installed today's 2.10.56 ß & I realized this is now active!  When did _this_ happen⁉️ 😄

**Comment by ameshkov** [comment]
Duplicate

**Comment by MR-Diamond** [comment]
Maybe I miss something (I see that this ticket has been closed as duplicate, but I cannot figure out which is the other ticket); I set - on Nougat - the VPN as "Always ON", and If I correctly understand, this option should "stop" the connection (wifi or mobile data) when the protection of AdGuard is turned off, but doesn't work as expected (If I stop AdGuard, I am still able to browse or use apps which relies on connection). Can someone give me some hints about?

**Comment by TPS** [comment]
#774 is the ticket for 7/Nougat, but I'm not sure that's how "Alway-on" is supposed to to work.  I _think_ it's to prevent any connections from _bypassing_ the VPN while it's _active_.
