### ISSUE TITLE
RFC/E: Compatibility w/ Android 7/Nougat's Direct Boot

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#761]
Many details @ https://developer.android.com/training/articles/direct-boot.html & http://www.androidauthority.com/direct-boot-711668-711668/.  Since messaging apps are specifically mentioned, I suppose that means networking is available & many ad-supported apps with on-boot loading will jump on the bandwagon.  I think AG should, then, as that's likely a large vector (as well as #760) to get ads loaded into the system when AG isn't there.

What d'you all think, @AdGuardTeam?

**Comment by ameshkov** [comment]
I don't think network is accessible during the direct boot stage. 

Also trying to set up a VPN connection during boot may lead to some random issues, that's why we currently delay it for 10-20 seconds.

Although I hope #760 might be a solution.

**Comment by TPS** [comment]
"Network" clearly seems available, per examples given, so I assume you mean "networking" in terms of low-level details that AG needs to setup VPN.

Is there anyway to have that delay configurable?  I'd happily test it.

**Comment by ameshkov** [comment]
> Is there anyway to have that delay configurable? I'd happily test it.

Yep, we should:
https://github.com/AdguardTeam/AdguardForAndroid/issues/776

**Comment by ameshkov** [comment]
> "Network" clearly seems available, per examples given

Hm, I still don't think so. I mean internet access, it may very well be unavailable.

**Comment by TPS** [comment]
OIC, the messaging apps mentioned are _SMS_; no mention of _networked_ messaging.

**Comment by TPS** [comment]
I'm running 7/Nougat now, so if you need testing/data/whatever, count me in. ☺️

**Comment by ameshkov** [comment]
Closing as the desired feature is doable via always-on vpn anyway

**Comment by TPS** [comment]
This isn't _quite_ the same idea as #760, but I can't think of a use-case for this  _that_ doesn't cover, so alright by me to close, anyway.
