### ISSUE TITLE
ru.yota.android does not work with HTTPS filtering

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#762]
id 705516
https://play.google.com/store/apps/details?id=ru.yota.android&hl=en
Не обновляется информация при входе в приложение. Помогает отключение HTTPS конкретно для приложения
<details>
![screenshot_13](https://cloud.githubusercontent.com/assets/18548949/17900519/4b2aeb08-6968-11e6-9ccc-0261d25b683c.jpg)

**Comment by nkartyshov** [comment]
Добавил

**Comment by vgavrish** [comment]
1394153
> При включенной защите в Adguard (фильтрация HTTPS включена), в чате
приложения Yota не удается связаться с поддержкой. Даже выключение фильтрации для Yota проблему не решает, помогает только полное выключения защиты. 
2.8.15
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19764678/efc3ff26-9c4c-11e6-9e55-bc4f8fd78bb9.png)

**Comment by nkartyshov** [comment]
fixed

**Comment by deLumren** [comment]
So, how it should be working atm? 
Do you need to manually add yota.ru domain to the whitelist in order to access the app without trouble?
User 1311060 suggests adding this domain to our default whitelist.

**Comment by ameshkov** [comment]
For now - just disable HTTPS filtering for this app. Will be resolved in v2.9.
