### ISSUE TITLE
Use swipe gestures to enable/disable options in the Apps and Statistics section

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#763]
Before, when inside the Apps and Stats page, I could simply tap on either the DATA or WIFI icons to enable or block network access for each app, but have noted that with this latest build, said icons are gone and am now forced to enter app details page in order to allow or deny access. Might I recommend per-app swipe gestures (a la Gmail) right from the Apps and Stats page? Example:

- Swipe left to enable Wi-Fi (swipe left again to disable)
- Swipe right to enable Data (swipe right again to disable)

- The above could even be implemented at a notification level to bypass having to add additional buttons to what could potentially become a clutter of notifications

**Comment by ameshkov** [comment]
We are in process of full app redesign: #713 

I am not sure if we allow swiping though. What I am sure is that we will allow fast settings change right from the apps list (without navigating to the app details page).
