### ISSUE TITLE
Adguard turns off unexpectedly

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#764]
id 1397457

"I changed to the beta release and also went into the lollipop app optimiser
on Galaxy s5 to turn off optimisation for adguard. I noticed that it no
longer drops after changing from data to wifi but it still turns off
sometimes. For example, when I start an app gallery for reddit or make
hangouts call. After opening these apps or starting the call, adguard has
turned off."

"I don't have antivirus or cleaner"

[logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/437269/logs.zip)

galaxys5, excluded from battery saving, icon type default, no

**Comment by ameshkov** [comment]
@vozersky please ask user if it goes to "protection paused" or it is completely turned off?

**Comment by vozersky** [comment]
@ameshkov Will do. According to log files that we already have, Adguard was killed.

**Comment by ameshkov** [comment]
Maybe notification icon is disabled or something like that?

**Comment by vozersky** [comment]
obsolete
