### ISSUE TITLE
Add a quick setting tile for Android 7 to toggle the VPN on/off

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#767]
**1401277**

http://android.wonderhowto.com/how-to/add-your-own-quick-settings-tiles-android-7-0-nougat-0173307/

> User 1298523 reminded of such a possibility in Nougat:
> "I've always dreamed of toggling Adguard from the notification shade lol. I don't know, but maybe having a toggle would eliminate the need for the persistent notification. That would be nice."

> Please check this:
> https://developer.android.com/about/versions/nougat/android-7.0.html#tile_api

**Comment by ameshkov** [comment]
@nkartyshov one important question about the custom tile: does it increase app process priority.

**Comment by nkartyshov** [comment]
https://developer.android.com/reference/android/service/quicksettings/TileService.html

**Comment by nkartyshov** [comment]
done
