### ISSUE TITLE
Opera Free VPN App

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#768]
>"No Apps can perform this function" error message when attempting to
launch...cannot turn Adguard on at all even after reboot...please advise

-------------

>When I had installed Opera Beta Browser and [Opera Free VPN App](http://drippler.com/drip/opera-brings-its-free-and-easy-use-vpn-service-android) for Android when I noticed that I couldn't get Adguard to work again AFTER attempting to shut Opera Free VPN down and turn Adguard back on.

**1400977**

**Comment by ameshkov** [comment]
Looks like a firmware issue to me.

I suggest trying newer Android version.
