### ISSUE TITLE
[Android] Top Eleven Football Manager connection problem

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#77]
Server connection problem in app while Adguard is on. Problem persists even if you disable all the filters but leave the protection on.

https://play.google.com/store/apps/details?id=eu.nordeus.topeleven.android

KCS-481-53405

**Comment by tuxnowar** [comment]
issue is still there

**Comment by Coolhabit** [comment]
@tuxnowar Hello!
Is this the same problem?
https://github.com/AdguardTeam/AdguardForAndroid/issues/5257

**Comment by tuxnowar** [comment]
yes same problem

**Comment by Coolhabit** [comment]
Ok, so we are closing this as a dublicate, all works will be here https://github.com/AdguardTeam/AdguardForAndroid/issues/5257

**Comment by tuxnowar** [comment]
ok thanks
