### ISSUE TITLE
Notification states that "Adguard filters all connections", "block ads in all apps" disabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#770]
![image](https://cloud.githubusercontent.com/assets/15856304/18019732/281b8eee-6be6-11e6-8536-3e91fe7b9213.png)

У меня в настройках не стоит галочка "фильтровать все интернет соединения", то есть фильтруются только браузеры, однако в панели уведомлений есть сообщение, что фильтруются все интернет соединения. Я не пойму кому верить. Предлагаю исправить этот дефект. 

1401198

**Comment by ameshkov** [comment]
Фильтровать != блокировать.

Функционал брандмауэра касается всех приложений, можно кому-то запретить доступ в сеть к примеру.
