### ISSUE TITLE
Google Duo does not work with HTTPS filtering

### ISSUE THREAD

**Issue by indywidualny** [AdguardTeam/AdguardForAndroid#771]
A few people tried to call me on Duo today and it wasn't possible to do so. I discovered that Adguard blocks Duo (https://play.google.com/store/apps/details?id=com.google.android.apps.tachyon&hl=en)

A workaround is to whitelist it. You should probably do it by default.

**Comment by ameshkov** [comment]
Closing as a duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/753

Anyway, thank you for reporting it! We'll fix it in v2.8 update.
