### ISSUE TITLE
"Always-on VPN" in Android 7

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#774]
Details:
https://forum.adguard.com/index.php?threads/always-on-vpn-in-android-7.13186/

**Comment by TPS** [comment]
#760, but specific to Nougat?

**Comment by ameshkov** [comment]
Who knows, I'll check it.

Closing this issue as a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/760

**Comment by TPS** [comment]
_(I mentioned this in https://github.com/AdguardTeam/AdguardForAndroid/issues/2#issuecomment-151726474, since I'm yet running Android 4/Kitkat, so the *option* is there, so anyway #760 is more appropriate.)_

**Comment by TPS** [comment]
Quoting myself from https://github.com/AdguardTeam/AdguardForAndroid/issues/760#issuecomment-295030130 & https://github.com/AdguardTeam/AdguardForAndroid/issues/760#issuecomment-295030352:
> I think this should be reopened, as Android 7/Nougat opens this up for VPN apps, given correct configuration via <a target="_tab" href="https://goo.gl/yyKLWQ">`setAlwaysOnVpnPackage` _(⚠️ Warning! Giant confusing webpage!  Click into new tab & let it load!)_</a> & related functions, which AG doesn't _(yet 🤞)_ have:
![ag always-on-vpn fail](https://cloud.githubusercontent.com/assets/185902/25158882/a71476d8-2479-11e7-987a-104a86ed3456.png)
