### ISSUE TITLE
Consider adding data compression as an optional feature 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#775]
Please add data compression support. I know Google has an open source
data compression protocol they both use in Chrome and Opera also has
one. Maybe one of those can be implemented in the app to save data
across all apps?

**623633**

**Comment by ameshkov** [comment]
@evgeniy-ADG this is too complicated task. Maybe in future though.

**Comment by evgeniy-ADG** [comment]
Yep, I've already wrote that to the customer, but decided to file it here.

**Comment by war59312** [comment]
Sounds like version 7 task. ;)

Perhaps Zstandard (https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/) could be used in some context.

**Comment by TPS** [comment]
This is [_definitely_ a moon-scale request](https://github.com/AdguardTeam/AdguardForAndroid/issues/108#issuecomment-149283877)!  Maybe the pebble, in this instance, is to _optionally_ ask for protocol-level compression on __all__ outbound requests, & go from there?

**Comment by defiler007** [comment]
+1 from me! Please implement this!

**Comment by ameshkov** [comment]
You see, this task is pretty easy to implement (as we already introduced outbound proxy settings, we could simply reuse it).

The real problem is the infrastructure required for fast and reliable data compression. Frankly, i'd better partner with some reputable service who already provides this feature.

**Comment by TPS** [comment]
> Frankly, [I]'d better partner with some reputable service who already provides this feature.

@ameshkov That's a _great_ idea!  Do you (or anyone else ;) know of any that allow 3rd-party app access to such a service?

**Comment by ameshkov** [comment]
> Do you (or anyone else ;) know of any that allow 3rd-party app access to such a service?

I guess if we do it, it won't be just a white-label (like what Opera VPN did with Surfeasy).

I see it like this: "here is a list of VPN providers we partner with. You can use any of them".

**Comment by TPS** [comment]
Just received this e-mail alert from a commercial provider of external VPN support (which is a lot of what this issue's morphed into):
>#### US Senate votes to let ISPs sell your browsing data
>On Thursday, March 23rd, the US Senate voted to let internet service providers (ISPs) sell your web browsing history without your permission.
>
>If you live in the US, your browsing habits can now be sold to advertisers and third parties. If you live somewhere else, it's unsettling that this is already a $24B industry.

… & then it goes on to extol the virtues of their product.

Still, food for thought, & shows the critical necessity for this. 😐

**Comment by ameshkov** [comment]
Yeah, VPN servers will be thriving on this.

My condolences on your privacy, this senate decision is outrageous.

**Comment by TPS** [comment]
Well, the new administration said they'd boost the economy by promoting industry growth, so _that_ fits.… It just may not have occurred to them _which_ industry! 🙃

**Comment by TPS** [comment]
_When recommending VPN services, _do_ keep in mind AA's articles on [rogue](http://www.androidauthority.com/vpn-scammers-761908/) & [recommended 1s](http://www.androidauthority.com/best-android-vpn-apps-577594/)._

**Comment by TPS** [comment]
[Russia banning VPNs seems relevant here. 😭](https://en.crimerussia.com/gromkie-dela/european-companies-warn-about-consequences-of-vpn-restriction-in-russia/)

**Comment by TPS** [comment]
Related: #1576

**Comment by TPS** [comment]
So, y'all dropped https://adguard.com/en/blog/adguard-vpn-announcement.html .…  Any support for Android (or its β-license folks 😁) @ the moment? Also, I'm hoping this thread's requests 👆 are someplace on the dev queue.

**Comment by artemiv4nov** [comment]
Well, our VPN app is on the way to be built, so wait for a little with beta-support, please.

**Comment by TPS** [comment]
It's to be a _separate_ app⁈  I thought it'd be another panel integrated into the _current_ app, leveraging the existing VPN support.

**Comment by ameshkov** [comment]
@TPS this will happen as well, but the first step is to publish a separate app so I guess we can close this issue:)

**Comment by TPS** [comment]
>> It's to be a _separate_ app⁈  I thought it'd be another panel integrated into the _current_ app, leveraging the existing VPN support.
> @TPS this will happen as well, but the first step is to publish a separate app so I guess we can close this issue:)

Is this no longer planned?  The AGA UI for it seems pretty… final 😢:

![Screenshot_2021-06-17-20-32-17-709.jpg](https://user-images.githubusercontent.com/185902/122491606-4e512080-cfb2-11eb-86a7-610971e76e79.jpg)

**Comment by Chinaski1** [comment]
@TPS 

In the end, it was decided to keep AdGuard VPN as a separate application

**Comment by TPS** [comment]
Much of the reason for wanting just 1 app is memory management.  After all, many of us have trouble keeping AG itself loaded, much less _another, overlapping_ app.

**Comment by TPS** [comment]
For those still following for compression (the original RFE!), I refiled that @ https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/102, & quoted our relevant bits there.  Please chime in! 🙇🏾‍♂️
