### ISSUE TITLE
Introduce a new low-level setting: "pref.boot.startup.delay"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#776]
On device boot Adguard waits for some time before starting protection. We should make this delay configurable.

https://github.com/AdguardTeam/AdguardForAndroid/issues/761#issuecomment-243170096

@nkartyshov look at "ServiceManager.AUTOSTART_DELAY". Use this new property instead of it. Don't forget to check that the property value is valid positive integer.

**Comment by TPS** [comment]
May impact #520 for me.…

**Comment by nkartyshov** [comment]
done

**Comment by TPS** [comment]
I just wanted to let y'all know that this solved about 90% of #520 for me. Thanks very much, @AdguardTeam!
