### ISSUE TITLE
Can't open websites in chrome if protection is paused

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#777]
id 1402751

Getting ERR_CONNECTION_REFUSED in chrome for https website if protection is paused.
Asked about http.

[logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/447605/logs.zip)

video:

[VID-20160830-WA0004.mp4.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/447606/VID-20160830-WA0004.mp4.zip)

**Comment by ameshkov** [comment]
@vozersky I am pretty sure this is a firmware bug.

Ask does it help to turn Wi-Fi off and on again?

**Comment by vozersky** [comment]
@ameshkov doesn't help, even uninstalling adguard doesn't help

**Comment by ameshkov** [comment]
@vozersky i have no clue, this is firmware issue for sure.

**Comment by vozersky** [comment]
no reply, outdated
