### ISSUE TITLE
Blocked ads and bandwidth saved counters are working nonstop

### ISSUE THREAD

**Issue by mozkan007** [AdguardTeam/AdguardForAndroid#778]
Hi I am using Adguard v2.7.220 on my android phone and my os version is v5.0.2.I have noticed for a while that  blocked ads and bandwidth saved counters where on main screen of the app are working nonstop(the numbers continue to increase) despite no app works at background or being open.I do not understand that it is a bug or usual thing.I wish you have a good works.Thanks.

**Comment by ameshkov** [comment]
Hi!

Could you please take a look at "Apps & Statistics" and find out which app is going mad?

**Comment by mozkan007** [comment]
Hi,

I am sorry that I gave you imperfect information.Actually I am using Greenify app that to hibernate background app and also I allowed to Outlook app to work on background.So after your question  I checked the app traffic and I noticed that Outlook app causes this issue.I disabled to ad blocking for this app immediately.Thus the counters stopped to count.Shortly I understand it is not a problem.You can close the topic.I am sorry to bother you and also I am really pleasant for your attention.Thank you and good work.

**Comment by ameshkov** [comment]
No worries and thank you for reporting it!

In fact it may be important, we'd better check what causes outlook app to misbehave. It'd be better if we fix this for everybody:
https://github.com/AdguardTeam/AdguardForAndroid/issues/786

Just one more question: do you have HTTPS filtering enabled or not?

**Comment by mozkan007** [comment]
Yes I have enabled HTTPS filtering.

**Comment by ameshkov** [comment]
Got it, thank you!
