### ISSUE TITLE
Robinhood App - No Connection On Sign-in and Verify Bank Account

### ISSUE THREAD

**Issue by war59312** [AdguardTeam/AdguardForAndroid#779]
Hi,

Robinhood app (robinhood.com) is being blocked while trying to sign into the app.

Also happen during "Verify Bank Account".

Simply get:

> No connection

Once signed in and bank account verified, Robinhood works fine with Adguard filtering on.

Thanks,

Will

**Comment by ameshkov** [comment]
Does it help to turn https filtering off for that app?

Also it seems that the app is financial and may contain sensitive personal information. Should we really try to block anything inside?

**Comment by war59312** [comment]
Indeed, should probably just go ahead and add to exclude list. I've done this myself.

But yes disable https filtering "fixes" it.
