### ISSUE TITLE
Daff Moon is not detected in Firewall

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#780]
STR:
1. Install Daff Moon - https://play.google.com/store/apps/details?id=com.dafftin.android.moon_phase
2. Go to any tab and switch the dates. Don't forget to tap updated in top right.
3. Open Adguard - Apps&Stats -> Daff Moon is not on the list.

Reported by user 1403769

**Comment by vozersky** [comment]
same here on my Nexus 5

**Comment by ameshkov** [comment]
Could it be that this app just does not have internet access permission?

**Comment by ameshkov** [comment]
Yep, it is so.
