### ISSUE TITLE
SoundHound app compatibility issue

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#781]
id 734231
https://play.google.com/store/apps/details?id=com.melodis.midomiMusicIdentifier.freemium&hl=en
При нажатии на значок SoundHound для прослушивания/определения музыки:
http://prntscr.com/c4pkve
Через некоторое время выходит сообщение:
http://prntscr.com/c4pks5
Отключение фильтров в Антибаннере, отключение HTTPS фильтрации - не помогает
Помогает отключение блокировки рекламы в приложении через "Настройки приложений".

Логи 
[debug (28).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/453236/debug.28.txt)
Время 22:37 - 22:39

**Comment by nkartyshov** [comment]
done

**Comment by Alex-302** [comment]
Снова та же проблема.

**Comment by nkartyshov** [comment]
Проблема решилась добавлением приложения в adblocking исключения.

**Comment by ameshkov** [comment]
Значит можно более гибко ее решить и разблокировать какой-то из рекламных урлов.

Какой конкретно?

**Comment by nkartyshov** [comment]
Похоже я ошибся, включение adblocking для приложения не сломало его.

**Comment by nkartyshov** [comment]
Проблему удалось решить удалением search.midomi.com из ssl whitelist, но надо протестировать.

**Comment by ameshkov** [comment]
@vozersky waiting for you

**Comment by vozersky** [comment]
removing search.midomi.com from ssl whitelist does not help

**Comment by nkartyshov** [comment]
Disabling ad blocking solves this problem.
