### ISSUE TITLE
VPN won't start on LG Optimus L7

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#782]
The error message: "Ваше устройство ещё не готово..." - http://prntscr.com/ccnbt5
Adguard 2.7.220, Android 4.4.2
Proxy mode works fine, no other VPNs at the same time. Other VPNs (NetGuard and NoRoot) work fine

Log - https://gist.github.com/Bohdan-SUP/92270aa185b52fb7ff2287f0732a447e
error at 7:42

User 1404288

**Comment by ameshkov** [comment]
Error happens somewhere inside android's own VpnService class:

```
07:42:05.775 [main] WARN  com.adguard.android.ServiceManager - Error preparing vpn service
java.lang.NullPointerException: null
	at android.os.Parcel.readException(Parcel.java:1471) ~[na:0.0]
	at android.os.Parcel.readException(Parcel.java:1419) ~[na:0.0]
	at android.net.IConnectivityManager$Stub$Proxy.prepareVpn(IConnectivityManager.java:1727) ~[na:0.0]
	at android.net.VpnService.prepare(VpnService.java:144) ~[na:0.0]
```

I suppose user's device simply lacks VPN support.

**Comment by Bohdan-SUP** [comment]
@ameshkov but the user has NoRoot Firewall and it works properly for him.

**Comment by vozersky** [comment]
@Bohdan-SUP 
Это странно, должно работать тогда.
А с NoRoot Firewall вообще не было такой ошибки? Ни разу?
А с нами как часто? Постоянно или иногда все-таки?
Нужно попробовать сразу после перезагрузки устройства запустить Adguard и проверить.

**Comment by vgavrish** [comment]
NetGuard работал без перебоев. NoRoot Firewall в работе не тестировал особо, я проверял только, запускается ли VPN - запустился без проблем.
Ошибки, которая возникает при попытке запустить в Adguadr в режиме VPN, никогда нет при запуске VPN через NetGuard и NoRoot Firewall.
Adguard в режиме прокси работает без нареканий. Перезагрузка устройства, переустановка начисто Adguard не помогает запустить его в режиме VPN. В этом режиме так ни разу и не запустился.

**Comment by Bohdan-SUP** [comment]
"NetGuard работал без перебоев. NoRoot Firewall в работе не тестировал особо, я проверял только, запускается ли VPN - запустился без проблем.

Ошибки, которая возникает при попытке запустить в Adguadr в режиме VPN, никогда не нет при запуске VPN через NetGuard и NoRoot Firewall.

Adguard в режиме прокси работает без нареканий. Перезагрузка устройства, переустановка начисто Adguard не помогает запустить его в режиме VPN. В этом режиме так ни разу и не запустился."

**Comment by Bohdan-SUP** [comment]
@vozersky @ameshkov anything we can check?
