### ISSUE TITLE
Improve HAR writer - make the current file valid

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#784]
It is always necessary to add `]}}` to the end of current har file manually.

We can fix HAR writer to have a valid current file, just add these characters for every record (and then overwrite when the next record is added).

Look at `HarWriter.writeHarEntry` and `HarWriter.writeFooter`

You can test HAR validity here:
http://www.softwareishard.com/har/viewer/

**Comment by nkartyshov** [comment]
done

**Comment by ameshkov** [comment]
Now you add extra `]}}` to every file

**Comment by nkartyshov** [comment]
fixed

**Comment by seanl-adg** [comment]
The issue is still occurring on me with 2.9.70 version.

**Comment by ameshkov** [comment]
@seanl-adg how come? you should always add these 3 characters?

Can you reproduce it reliably?
