### ISSUE TITLE
Count total requests count

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#785]
We currently count the number of blocked requests. Without total requests count this number does not mean much.

Thanks to @TPS for the idea:
https://github.com/AdguardTeam/AdguardForAndroid/issues/668#issuecomment-243311261

**Comment by TPS** [comment]
You're welcome, of course! 😊  This would be better if this is done *every*place any kind of statistics are displayed — i.e., not just main screen for ads, but threats (right now, it seems it counts only _blocked_ threats, not total, like when I "Continue Anyway") & each app individually on the firewall/stats screen, especially that Virtual DNS package, which is what #668 was about, anyway.

**Comment by TPS** [comment]
Also, for wherever the "Total Bandwidth Saved" stat ends up after #713, it also needs similar context. I suggest something like "Total Bandwidth Saved – AdGuard Bandwidth Consumed [from def updates, &c]/Total Bandwidth Processed."

**Comment by TPS** [comment]
On 3.0.56ƞ's App Management screen, individual app's stats are perfect.  Can we get this globally, here &  on main AG screen?
