### ISSUE TITLE
Apps go mad because of ad (or tracking) requests blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#786]
Which, in turn, causes blocked ads counter increment all the time.
### Outlook

A bit more details on the issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/778

We should find out what exact ad or tracking request causes it.

HTTPS filtering is enabled in user's case.
### TechMedia

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=52970592
### ES File Explorer

http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=52970592

@gshumihin please check if it is easy to reproduce it.

**Comment by SlowMemory** [comment]
This is caused by 
```
||pipe.aria.microsoft.com/Collector/$empty
```
I've reported it [here](https://forum.adguard.com/index.php?threads/resolved-skype-trackers.10646/) but it is not yet resolved.
Similar problem exists with OneNote app.

**Comment by ameshkov** [comment]
@SlowMemory thanks for clarification!

> 6420 ads have been blocked from microsoft powerpoint, and it says 160.41MB of bandwidth is saved. I am wondering whether this is normal, or should be fixed, by e.g.

In fact 6k for a month is not much. When we introduce the "blocked trackers" counter, situation will be more clear to user.

What we're trying to find out in this issue is if there is "play music"-like issue where an app could make hundreds of tracking requests in a second.

**Comment by SlowMemory** [comment]
Oh, I misunderstood the problem. Thank you for your answer!

**Comment by gshumihin** [comment]
> What we're trying to find out in this issue is if there is "play music"-like issue where an app could make hundreds of tracking requests in a second.

So far this never happened to me with listed apps.

**Comment by ameshkov** [comment]
Let's make this issue persistent, I'll add more apps here.

Here is one more potentially problematic app:
https://play.google.com/store/apps/details?id=com.microsoft.next

User says:
> It says it has saved 43.83 GB of bandwidth and blocked 1,802,231 ads.

@gshumihin please check it.

**Comment by gshumihin** [comment]
Tested this app for couple days.
There is no crazy stats for this period.
But this app destroyed my battery even being excluded from filtering.

**Comment by gshumihin** [comment]
While next is enabled, device losing over 15% of battery per hour.

**Comment by gshumihin** [comment]
After more than day got something like 1500 ads blocked. Seems pretty legal.

**Comment by evgeniy-ADG** [comment]
https://play.google.com/store/apps/details?id=com.microsoft.launcher&hl=ru -> has 300,000+ in ad blocking statistics.

**Comment by ameshkov** [comment]
@evgeniy-ADG log?
