### ISSUE TITLE
Bria / CSipSimple

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#787]
id 1396437
**Bria**
https://play.google.com/store/apps/details?id=com.bria.voip&hl=ru
**CSipSimple**
https://play.google.com/store/apps/details?id=com.csipsimple&hl=en

Bria / CSipSimple регистрируются в Asterisk (registered SIP 10), и
с этого номера можно звонить и получать входящие звонки.
Но через минуту (плюс минус секунды) сервер сообщает Peer 10 is
UNREACHABLE! 

<details>
![screenshot_32](https://cloud.githubusercontent.com/assets/18548949/18362083/1ab3f634-760d-11e6-930a-a1878175af69.jpg)

</details>

И входящие звонки более не проходят. Исходящие доступны
(при инициализации вызова учётные данные передаются снова серверу и
соединение устанавливается).
Данное поведение не зависит от того, используется WiFi или WCDMA / LTE.

Устанавливаете приложение, подключаетесь при помощи логина и пароля
к SIP-серверу, ждёте минуту-две - сервер потерял соединение с
приложением.

Вписывание IPv4 сервера 78.139.226.115/32 не помогает (исключение из
фильтрации локального трафика).
Отключение фильтрации для приложений также не помогает.

**Comment by ameshkov** [comment]
Дубликат вот этой задачи:
https://github.com/AdguardTeam/AdguardForAndroid/issues/422

По итогу мы добавили CSipSimple в список исключений по умолчанию.
@nkartyshov то же самое надо сделать для Bria.

Есть правда одна проблема: эти исключения корректно работают только начиная с Android 5.0 (а в случае некоторых производителей - вообще с 5.1). И есть ощущение, что в случае пользователя как раз это и происходит, потому что я вижу, что к нам приходят соединения от исключенного приложения:
```
UDP connect to /78.139.226.115:65500. Process info: com.bria.voip /0.0.0.0:39453 /0.0.0.0:0 10169
```

Не очень понятно как решать. Разве что прошивку обновить.

**Comment by nkartyshov** [comment]
done
