### ISSUE TITLE
Adguard turns off on Fly IQ4404

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#788]
Adguard 2.7.220, Android 4.2.2
iconType : DEFAULT

No other VPNs, task-killers, excluded from power savings, notifications are enabled.
Happens randomly, when simply opening websites.

Log, check 17:25 - https://gist.github.com/Bohdan-SUP/364c7aa751e7b31c4d576ed8667ebb67

**Comment by ameshkov** [comment]
It seems that the app is simply killed by Android.

There is no need in "record everything" log. What we need is logcat log.
