### ISSUE TITLE
Loosing connectivity when Wi-Fi is switched to Mobile

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#79]
Ticket ID = YRV-505-60834

```
adguard is not properly handling transition from WiFi to cell data. Has to be cycled off and on again or it blocks all network data. pretty consistent, I'd say 90% of the time when I lose WiFi and go to cell
```

We are able to detect Wi-Fi -> Mobile switch.
The only question is how to properly handle it and restart VPN.

**Comment by ameshkov** [comment]
Hm, I see that we already do restarting VPN on net switch.
Maybe we're wrong about it and there's no need in restart?

**Comment by Revertron** [comment]
The bug was found and exterminated relentlessly.
