### ISSUE TITLE
Take advantage of Quick Settings Tile API

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForAndroid#790]
User **1298523** reminded of such a possibility in Nougat:
"I've always dreamed of toggling Adguard from the notification shade lol. I don't know, but maybe having a toggle would eliminate the need for the persistent notification. That would be nice."

Pleaese check this:
https://developer.android.com/about/versions/nougat/android-7.0.html#tile_api

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/767

**Comment by ameshkov** [comment]
> maybe having a toggle would eliminate the need for the persistent notification

Not sure. Indeed it would be great if it increases process priority.
