### ISSUE TITLE
Apple Music is incompatible with SSL filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#792]
[Apple Music](https://play.google.com/store/apps/details?id=com.apple.android.music&hl=uk) с включенной защитой некорректно иногда работает! Обрывы в прослушивании, не показывает рекомендации во вкладке (для вас) приходится выключать защиту, перезпускать Apple Music, потом включать защиту обратно. Отключение HTTPS фильтрации помогает.

**Comment by nkartyshov** [comment]
добавил
