### ISSUE TITLE
Incompatible with samsung app store and samsung video

### ISSUE THREAD

**Issue by uuip** [AdguardTeam/AdguardForAndroid#795]
samsung S7 not root
com.sec.android.app.samsungapps
com.samsung.android.video
![708940440837367949](https://cloud.githubusercontent.com/assets/16631174/18621137/aec60f5a-7e51-11e6-80db-81fffaed39db.jpg)

I don't install the ssl cert and don't open the ssl filter switch.
Even if I unselect all the ads filters,samsung app store still appera error ，so I have to stop adguard.

**Comment by ameshkov** [comment]
@uuip hi! I cannot reproduce it on our side.

Could you please collect Adguard logs for me?

Here is how it could be done:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android

I'll also need to know your customer ID in order to find the ticket.

**Comment by uuip** [comment]
[adguard.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/500703/adguard.zip)

I copy the log from the log dir.
1. start adguard Vpn connect.
2. run  app  samsung video and samsung store.
3. close adguard.

**Comment by uuip** [comment]
[adguard-log2.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/500723/adguard-log2.zip)
@ameshkov 
Another log , Repeat the above procedure~~
I have not buy this app，because this problem.

**Comment by ameshkov** [comment]
@uuip what's weird is that I simply don't see any connection from the samsung store app.

I see just a few connections from:
`com.tencent.mm`
`com.bst.spamcall`

Have you got that connection error after running samsung store?

In theory you could solve this issue. Go to settings -> apps & statistics -> find samsung store app there and uncheck "Enabled" there. In this case it won't be routed through AG VPN anyway.

**Comment by uuip** [comment]
settings -> apps & statistics ->uncheck "Enabled".After then I run samsung store app ,it works well. 
settings -> apps & statistics ->check "Enabled" again, samsung store app get connection error again .

**Comment by uuip** [comment]
Just now,I have found the resaon of the problem. 
I use the AppManager to block Samsung app store and Samsung video using the network under 3G/4G data mode.
 I remove this rule,  and use Adguard with 'settings -> apps & statistics ->check "Enabled" again', Samsung app store works well.

**Comment by ameshkov** [comment]
Could you please take some screenshots of the settings screens? I still cannot reproduce the issue.

**Comment by uuip** [comment]
In China version Samsung s7, there is a app named "智能管理"----smart manager----this is the root reason cause this problem. 
let smart manager block Samsung app store to use mobile net, it will cause this problem.So adguard is ok.

**Comment by ameshkov** [comment]
@uuip ah, I got it, thank you for the clarification!
