### ISSUE TITLE
Introduce `pref.filtered.ports` low level setting

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#796]
Currently we filter only ports 80 and 443.

Check the following methods:
`FilteringVpnService.setupVpn`
`ProxyConfigurationServiceImpl.setupTransparentProxy`

Instead of hard-coding these two ports we should:
1. Use a low-level setting named `pref.filtered.ports`
2. Default value should be `80,443,3128`

**Comment by nkartyshov** [comment]
done

**Comment by TPS** [comment]
Just to confirm: this pref is functional for _both_ VPN _&_ proxy?

Also, does the pref handle ranges (e.g.: 80-88)?

**Comment by ameshkov** [comment]
> Just to confirm: this pref is functional for both VPN & proxy?

Yep, it does.

> Also, does the pref handle ranges (e.g.: 80-88)?

No, you'll have to set a coma separated list of ports.

**Comment by TPS** [comment]
Especially since it may be likely that port _ranges_ may be necessary, it this possible to implement that also, please?

**Comment by ameshkov** [comment]
@TPS i've filed a separate task for this:
https://github.com/AdguardTeam/AdguardForAndroid/issues/830

This could be difficult. This task is more about handling standard proxy ports and not websites which use non-standard ports. So implementing it will require additional testing

**Comment by TPS** [comment]
Is there a simple way _within_ Android to tell what apps are using what ports?  I know utilities that do so in Windows, but can't seem to find anything comparable for use _within_ Android.

**Comment by ameshkov** [comment]
The only easy way is to read Adguad's log and look for "Creating new connection" lines there.

**Comment by vbagirov** [comment]
The problem with pac.proxy is still present (see #751)
reproduced with the latest build

based on forum [topic](https://forum.adguard.com/index.php?threads/15037/)

**Comment by ameshkov** [comment]
It works
