### ISSUE TITLE
Rework "About" section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#797]
We should have the following links there:
1. Report issue on github
2. Discuss Adguard (leads to a page with the list of places with AG discussions: xda, official forum, etc).
3. Official website
4. ...

**Comment by Bohdan-SUP** [comment]
Official 4PDA thread (at least in Russian local)?

**Comment by ameshkov** [comment]
Yep, indeed

**Comment by TPS** [comment]
It _might_ be worth taking this opportunity to ~~funnel~~ recommend folks to 1 method _(each?)_ of external discussing/bug-reporting, rather you folks having to lurk on a dozen different avenues.

What do you all think?

**Comment by ameshkov** [comment]
@TPS we currently recommend using official website and github and still there are plenty of people using all other channels:)

In any case each channel leads to github after all:)

**Comment by nkartyshov** [comment]
done
