### ISSUE TITLE
Pros and Contras of ROOT / XPOSED with AdGuard?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#798]
Would adding a XPosed module / root request give the app any advantage of what the app can do / filter right now, if yes which? Also would root make ssl filtering work in nougat?

**Comment by ameshkov** [comment]
> Also would root make ssl filtering work in nougat?

Just having root is not a panacea from nougat issues. We can install root certificate in the system storage, but in this case we could face some issues with the websites using HTTP key pinning (like github). I am keeping track of possible issues in this task: #334 

XPosed module is the whole different story. Using it could give us a lot and I am seriously considering going this way.

**Comment by Bluscream** [comment]
@ameshkov wait, http pinning? I moved the Adguard Cert to system storage with [MoveCerts!](https://f-droid.org/repository/browse/?fdid=com.nutomic.zertman) but never had any problems with it until #793 came up. Do you think this is also related to AdGuard being in the system cert store?

**Comment by Bluscream** [comment]
Also @ameshkov if you start using a xposed module please keep it optional, cause on one of my devices (GT-I9295) XPOSED works flawlessly, but another (SM-T555) installing xposed reults in a bootloop... :(

**Comment by ameshkov** [comment]
> Do you think this is also related to AdGuard being in the system cert store?

Exactly, this is the consequence of moving cert to the system storage.

**Comment by ameshkov** [comment]
> Also @ameshkov if you start using a xposed module please keep it optional, cause on one of my devices (GT-I9295) XPOSED works flawlessly, but another (SM-T555) installing xposed reults in a bootloop... :(

Of course, xposed has a lots of issues, we won't require it.

**Comment by Bluscream** [comment]
I'd like to some kind of auto ssl unpinning except for some banking apps.

**Comment by Bluscream** [comment]
I'll close this now.
