### ISSUE TITLE
AdGuard doesn't launch automatically on Xiaomi Redmi 3S

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#799]
Суть:
1. AdGuard не запускается автоматически после перезагрузки системы на аппарате Xiaomi Redmi 3S (система Android 6.0.1, прошивка MultiROM 6.8.25 MIUI 8).
2. AdGuard c легкостью закрывается когда нажимаешь в меню "закрыть все".

При таких же настройках оптимизации батареи как у AdGuard прекрасно запускаются автоматически после перезагрузки телефона такие приложения как:
- Запись звонков CallRecorder: https://play.google.com/store/apps/details?id=com.skvalex.callrecorder 
- Приложение Hold Screen ON: https://play.google.com/store/apps/details?id=com.kkeyser.android.eyebuddy.paid 
- Приложение MyPhoneExplorer: https://play.google.com/store/apps/details?id=com.fjsoft.myphoneexplorer.client 

Кроме того процесс AdGuard c легкостью "прибивается" когда нажимаешь в меню "закрыть все" в окне открытых приложений (левая кнопка телефона -> список приложений -> закрыть все). У вышеперечисленных программ таких проблем НЕТ!

По моему скромному и далекому от программирования мнению, у вас в программе что-то неладно с приоритетом. Поэтому нет и автозапуска после перезагрузки и нет "иммунитета" от закрытия (в отличии от программ приведенных в списке выше).

**Comment by vozersky** [comment]
Посмотрели на mi4c. По пунктам:

1. Запустился, но остался в состоянии «ожидании сети»
2. Закрывается, но потом сразу же перезапускается и нормально работает в фоне и в этом списке приложений, где кнопка "закрыть все"не попадает, пока не зайдешь в приложение. 

Если отключить защиту, а потом убрать из списка процессов по пункту 2, то не перезапускается.

**Comment by ameshkov** [comment]
Заказали в офис xiaomi, посмотрим когда привезут.

**Comment by vgavrish** [comment]
id 1422333
При более длительном нахождении смартфона в режиме сна, ВПГ не восстанавливается.
Устройство постоянно находится в зоне Wi-Fi, или работает мобильная передача данных.
Уведомления для Адг включены, автозапуск включен, оптимизация отключена, энергосбережение отключено. Таск-киллеров, оптимизаторов, антивируса - нет.
От других приложений типа Вацап и Вайбер уведомления приходят.
Xiaomi redmi note 3 pro 3/32 os
miui 8 сборка 8.0.2.0 (lhomidg) Рута нет.
[debug (11).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/514113/debug.11.txt)
[state (60).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/514112/state.60.txt)

**Comment by ameshkov** [comment]
@gshumihin now when we finally acquired xiaomi phone you can test it.

**Comment by gshumihin** [comment]
I found the way to make Adguard working stable on xiaomi.

Here is instruction: https://github.com/gshumihin/test/blob/master/xiaomi_issuefix.md

**Comment by zebrum** [comment]
we have 3 or 4 same problems again. Double-checked  all the settings with screenshots-proof from users.
can not reproduce on our redmi 3S with MIUI 8.2.5.0 stable

@altokarev please put together those cases and post here.

we need to figure it out.

**Comment by ameshkov** [comment]
@zebrum please check what exact firmware do they all use.

**Comment by altokarev** [comment]
Xiaomi Mi4c@MiuiPro 6.8.25 (Android 5.1.1)
Xiaomi Redmi 4@MIUI 8.2.4.0 (Android 6.0.1)
Xiaomi Redmi 4 pro@MIUI 8.2.4.0 (Android 6.0.1)

**Comment by ameshkov** [comment]
Relevant bug in MIUI bug tracker:
http://en.miui.com/thread-280519-3-1.html

The only thing you can advise them is to try setting `Watchdog period` in AG advanced settings.

That's it, there's nothing else we can do.
