### ISSUE TITLE
"No connection" error in Google Play when manual proxy mode is used

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#8]
Linked forum thread:
http://forum.adguard.com/showthread.php?6547-Version-2-0-60-problems-remain&p=58456#post58456

**Comment by TPS** [comment]
I actually had this happen last night!  I rebooted & went on my way.…  Do you think the log will still be any good?  I'll send it in now, just in case.

**Comment by ameshkov** [comment]
Error line:

    TCP id=567 Error processing request https://play.googleapis.com:443: java.net.ConnectException failed to connect to /64.233.185.95 (port 443): connect failed: ENETUNREACH (Network is unreachable)

Seems that there were some problems with net connection, so I don't think this is somehow caused by Adguard.

**Comment by TPS** [comment]
Play store was only app with problem.  I could even get to GPlay on the *browser*, just not via app, but fixed on reboot.

**Comment by ameshkov** [comment]
For me it looks like GPlay problem very similar to Error 194 problem:
https://productforums.google.com/forum/#!topic/play/hIIJ1nauNf4

They had some problems with connections caching.

**Comment by TPS** [comment]
Mine resolves on reboot, though.…  The linked issue persists, & mine doesn't happen when AdGuard isn't running.

**Comment by Revertron** [comment]
Sooo, what we are doing? I've tested this back and forth and can't reproduce it at all.

**Comment by ameshkov** [comment]
Ok, let's close it.

I am pretty sure the problem was in Google Play and Google Play Services apps.
