### ISSUE TITLE
Notify users about "premium" websites with unusual tarification

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#80]
There are "premium" sites where usual tarification with monthly subscription doesn't work, and users loose money.

Example: http://www.mts.ru/mob_connect/entertainment/news_info/other/wap-services/

**Comment by TPS** [comment]
Since I don't speak Russian, the site provided doesn't help me know what this issue means.  Also, I don't understand your summary.  Are you referring to paid subscription sites?

**Comment by ameshkov** [comment]
@TPS, not exactly. When user downloads anything from the premium site, carrier charges him some additional price like $1/Mb.

**Comment by TPS** [comment]
Wow! I thought only [premium _SMS_](https://en.m.wikipedia.org/wiki/Reverse_SMS_billing) were a problem of this sort!  :+1: FTW on a fix! ☺

**Comment by ameshkov** [comment]
not that relevant in 2020 :)
