### ISSUE TITLE
VPN service issue with new Meizu firmware version and Opera Max OEM

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#800]
Support tickets: 1371591, 1416610

It appears that new Meizu phones are incompatible with any VPN app. This has started recently with a new firmware version.

For instance:
- Meizu M3s 5.1.5.2
- Meizu M3 Note 5.1.3.4

Direct link to the firmware:
https://yadi.sk/d/Jyh-Y3j4vA7Km
### Steps to reproduce
1. Install any VPN app.
   The issue affects literally any VPN-based app, not just Adguard. For instance, Hotspot Shield (over 10M installs): https://play.google.com/store/apps/details?id=hotspotshield.android.vpn
2. Open app, skip trial section and press "Connect" (which establishes a VPN connection)
3. Wait a few seconds (could be a few minutes).
### Expected result

VPN is up and running.
### Actual result

VPN is stopped shortly after turning ON.
You can see the following record in the logcat:

```
I/Vpn: Switched from hotspotshield.android.vpn to com.opera.max.oem.meizu
```
### Analysis

It seems that the root cause of this issue is the pre-installed Opera Max OEM app, which revokes VPN access rights from other apps.

I suppose that this is a mistake of Opera Max developers. The thing is that on Android other VPN app can easily mess with the other one by calling `VpnService.prepare` method. In order to fix this issue they could check other VPN presence before doing this call.

Here are some popular apps affected by this bug:
[Hola (over 10M installs)](https://play.google.com/store/apps/details?id=org.hola)
[HotSpot Shield (over 10M installs)](https://play.google.com/store/apps/details?id=hssb.android.free.app)
[OpenVPN Connect (over 10M installs)](https://play.google.com/store/apps/details?id=net.openvpn.openvpn)

**Also this issue effectively prevents Meizu phones from being used in an enterprise environment as companies often provide their own VPN.**

**Comment by ameshkov** [comment]
Reported to Meizu:
http://forum.flymeos.com/thread-8213-1-1.html

**Comment by ameshkov** [comment]
Reported to Opera:
https://plus.google.com/100208688342760686667/posts/JNEnqBQCUVn

**Comment by ameshkov** [comment]
From Opera Max devs:
> Fix for this problem will be merged with the next version of Opera Max.

**Comment by ameshkov** [comment]
The issue is resolved in Opera Max v2 which is already available in Google Play.

However, Meizu uses an older version.

**Comment by dpropp** [comment]
I had the same problem with Meizu M2, and I installed Opera Max V2, and stopped the default Opera Max V1 in app running as suggested in http://forum.flymeos.com/thread-19525-1-1.html. That helped for a few minutes, but then Opera Max V1 starting running again, and then disconnected the VPN (this keeps happening if I stop it). Any idea how I can cause it not to keep starting up again?
And is there a way to cause Opera Max V1 not to start up again after rebooting the device?

**Comment by ameshkov** [comment]
@dpropp as I recall, they have finally resolved this issue in the latest Meizu firmware: 5.1.12.1 (at least for Meizu M3S).

So, the easiest way would be to find and install the latest firmware.

The other option would be to acquire root access and freeze Opera Max app. It should be relatively easy on Meizu.

**Comment by dpropp** [comment]
Thanks!

However, I don't see any newer version than 5.1.12.0 in Meizu's site (http://www.flymeos.com/firmwarelist?modelId=33&type=1), neither for M2 (which I have) nor for M3S. Is there anywhere else I may find the 5.1.12.1 version, hopefully with fix?

Also, could you point to any guide on how to acquire root access and to freeze the app?

**Comment by ameshkov** [comment]
Here they are:
https://www.google.com/search?q=meizu+5.1.12.1+site:forum.meizufans.eu

Please note, that the website uses anti-adblocking script, we have not yet handled it (but we will soon).

**Comment by ameshkov** [comment]
You can acquire root access on Meizu in a few clicks:
http://www.phonearena.com/news/How-to-root-any-Meizu-Android-phone-one-click-Flyme-root-tutorial_id75673

Regarding freezing apps, people often use titanium backup app to do it.

**Comment by dpropp** [comment]
It seems there is no 5.1.12.1 image for m2 (not note). Am I missing something? If not available yet, any idea when it will be available for m2?

**Comment by ameshkov** [comment]
Not sure, really, I hope they will make it available as soon as possible.
