### ISSUE TITLE
FBReader sync issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#802]
"Не работает синхронизация в fbreader со включенным adguard. Adguard работает как прокси, сертификат https установлен. Приложение fbreader добавлено в исключение брандмауэра adguard, домен fbreader.org в белом списке.

Синхронизация работает только если явно добавить домен в исключения к
прокси-серверу в настройках wifi соединения: <details>
![screenshot_20160921-005655-01](https://cloud.githubusercontent.com/assets/17472907/18786555/293cb330-81a7-11e6-9f0b-47bb5ca8c6d8.jpeg)
</details>

Выключение/выключение приложения fbreader в настройках брандмауэра adguard'a тоже не помогает."

id 1412622

logs: 
[Archive.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/489711/Archive.zip)

**Comment by Revertron** [comment]
From the log:
```
Error processing request https://books.fbreader.org:443: java.net.ConnectException failed to connect to /2a01:7e00::f03c:91ff:fe73:55cb (port 443): connect failed: ECONNREFUSED (Connection refused)
```
Our proxy tries to connect to data.fbreader.org and books.fbreader.org through IPv6, but it is possible that user has no IPv6 network.

**Comment by Revertron** [comment]
Preliminary fix applied.
Needs some refactoring to increase reliability of manual proxy connections.
