### ISSUE TITLE
Google Allo app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#804]
Doesn't work with the HTTPS filtering.
https://play.google.com/store/apps/details?id=com.google.android.apps.fireball&hl=en

**Comment by evgeniy-ADG** [comment]
@Bohdan-SUP I was able to reproduce, it allows you to create an acc only when you disable Adguard. You can enable it back then and it'll work without problems.

**Comment by nkartyshov** [comment]
done
