### ISSUE TITLE
Soundhound - error while search

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#805]
**Steps to reproduce the problem**:
* install SoundHound - https://play.google.com/store/apps/details?id=com.melodis.midomiMusicIdentifier.freemium
* When app tries to search song details an error message appear. If you press Retry it works.

**Adguard version**: 2.7.220

**Operating system**: Android 6.0.1

HTTP log - 
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/491472/debug.9.txt)
**********
Tried to exclude these domains, but no result. HTTPS filtering was disabled, algorithm is simplified, VPN and proxy, all filters are disabled.
Full log
[adguard (2).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/491604/adguard.2.txt)
```
@@||midomi.com^$document
@@||static.midomi.com^$document
!https
secureapi.midomi.com
data.midomi.com
clientlog.midomi.com
```

**Comment by ameshkov** [comment]
Some error occurs indeed:

```
TCP id=114102 Error processing request http://search.midomi.com/v2/?method=search&type=identify&prebuffer=4.992: java.nio.channels.ClosedChannelException null
```

**Comment by nkartyshov** [comment]
done
