### ISSUE TITLE
Waze app is broken by AG

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#807]
Source:
https://forum.adguard.com/index.php?threads/adguard-breaks-waze-on-android.14207/

**Comment by TPS** [comment]
The fix for #733 is related?

**Comment by vbagirov** [comment]
According to user, these filters were enabled for him:

> ALL US including annoyance/facebook.
> Russian
> China
> Poland
> Korea
> Czech
> Romania

**Comment by ameshkov** [comment]
Cannot confirm this issue, Waze works ok.
