### ISSUE TITLE
VK app authorization issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#809]
User has this problem: when he tries to open the app, he gets this error message:
https://forum.adguard.com/index.php?attachments/screenshot_2016-09-22-14-13-20-png.5374/

If Adguard is disabled, the app opens normally.

Logs are available through the helpdesk at user ID 1418098.

Original forum thread with some more information:
https://forum.adguard.com/index.php?threads/14138/

**Comment by Bohdan-SUP** [comment]
Log - 
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/495221/debug.txt)

**Comment by Revertron** [comment]
ABP Japanese Filter has the rule that is blocking oauth.vk.com: ||vk.com^$domain=~vk.com|~vkontakte.ru

**Comment by ameshkov** [comment]
Guys, let's remove ABP Japanese at least from Android version.

**Comment by Revertron** [comment]
Done in 2.8-beta1
