### ISSUE TITLE
Adguard does not detect if device is in wi-fi hotspot mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#81]
If VPN is enabled, AG should detect it and inform user that hotspot/tethering can't be used when VPN is on. 

http://forum.xda-developers.com/showpost.php?p=63165828&postcount=268
http://forum.xda-developers.com/showpost.php?p=63166909&postcount=271

**Comment by Revertron** [comment]
Fixed.
