### ISSUE TITLE
se.feomedia.quizkampen.ru.lite - adguard breaks login

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#811]
Authorization is broken by HTTPS filtering. I can't reproduce it.

Related link
https://github.com/AdguardTeam/AdguardFilters/issues/3039

**Comment by ministr91** [comment]
http://dropmefiles.com/B0YvM
22:11
Я нашел более быстрый способ сохранения логов, не требует рут прав http://4pda.ru/forum/index.php?showtopic=222864&st=0#entry18805145 Интерфейс на русском, есть приложение в гугл плей. Если можете, то добавьте этот способ сюда https://kb.adguard.com/index.php?/Knowledgebase/Article/View/63/5/kk-poluchit-log-logcat-n-ustrojjstve-android

**Comment by ministr91** [comment]
Извиняюсь, не тот лог выложил. Вот тот лог 
http://dropmefiles.com/u3stu
Вот ссылка на программу: http://4pda.ru/forum/index.php?showtopic=260024
Нужны рут права. Вот инструкция: 
1. Запускаем CatLog.
2. Нажимаем кнопку меню. Там выбираем Запись/Record. Появится диалог выбора имени лога. Можно переименовать файл или просто нажать ОК. После этого можно нажать кнопку домой. CatLog продолжит записывать лог в фоновом режиме.
3. Переходите в нужное приложение. Воспроизводите там ошибку/нужные действия.
4. Переключаемся в CatLog, нажимаем меню, выбираем Остановить запись/Stop record. При этом будет сообщено имя файла, куда был сохранен лог.
5. Полученный лог отправляем кому и куда надо.

**Comment by ministr91** [comment]
Сделал еще 1 лог именно ошибки программы по инструкции http://4pda.ru/forum/index.php?showtopic=260024&view=findpost&p=52718828 , он короче, советую посмотреть именно его сначала http://dropmefiles.com/jHodG

**Comment by nkartyshov** [comment]
@ministr91 Попробуй добавить feoquizserver.com в pref.https.domains.whilelist 
Для этого надо зайти в Настройки -> Расширенные -> Низкоуровневые настройки -> pref.https.domains.whilelist.

После обязательно перезагрузить службу Adguard.

**Comment by ministr91** [comment]
Проблема решилась

**Comment by ministr91** [comment]
Вы потом в обнову автоматически это внесете? Можно удалять строчку?

**Comment by nkartyshov** [comment]
@ministr91 Да, внесем, но лучше оставить)

**Comment by ministr91** [comment]
А инструкцию в шапке обновите? https://kb.adguard.com/index.php?/Knowledgebase/Article/View/63/5/kk-poluchit-log-logcat-n-ustrojjstve-android
Я нашел более короткий способ получения лога

**Comment by ministr91** [comment]
Он проще,  быстрее

**Comment by ministr91** [comment]
@nkartyshov точно внесете?

**Comment by ministr91** [comment]
Забыли (
