### ISSUE TITLE
Implement "Knox" filtering mode for Samsung devices

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#813]
Hello! I just curious if it's possible for Adguard to run under
Samsung Knox instead of Vpn. This would be similar to the app
Disconnect Pro. Disconnect seems to be able to run inside Knox for
Samsung phones allowing not touching the VPN. This seems to be quite
an interesting method of controlling the Internet connections!

**Comment by war59312** [comment]
That would be pretty sweet. Then I could continue to use Adguard with VPN, in theory.

**Comment by ameshkov** [comment]
Nice idea, never heard about it before.

I'll store all the information I found about Samsung Knox here.
https://www.samsungknox.com/en/knox-technology/white-papers
https://www.samsungknox.com/en/knox-technology/tech-notes

Looks like some enterprise technology to me, I can't yet understand how we can use it for traffic filtering purposes.

**Comment by SlowMemory** [comment]
Someone in a Korean forum reported that he/she was able to run Adguard in Knox, and it has an advantage that Adguard was not showing in Android system's battery usage statistics so it (seems to be) reflecting the actual battery usage. I couldn't reproduce it, if I run Adguard inside Knox it does not filter traffic for apps outside Knox. It may differ among devices.

**Comment by ameshkov** [comment]
So Knox works like some sort of sandbox?

**Comment by SlowMemory** [comment]
I guess so, in https://www2.samsungknox.com/en/faq/what-my-knox it states that "you can view and store confidential work information in a safe virtualized sandbox, without having to worry about data leaks." But laymen like me use Knox to use two messenger accounts on one phone at the same time.

**Comment by boo85** [comment]
It is what Disconnect Pro for Samsung devices is doing using Knox v2.6 and above. This software can be found in the Galaxy App store. 

[https://disconnect.me](https://disconnect.me/)

From what I understand, for devices without Knox v2.6 will be using VPN. However for Samsung devices with Knox v2.6 (S7, S6, Note5 and Note7), Disconnect have the capability to function filtering trackers using Knox to assist in the filtering without needing to use VPN. 

Note that Disconnect is not running as an app inside the Knox's separated work space system, but just making use of Knox to assist in the filtering without VPN.

**Comment by ameshkov** [comment]
Information about Knox (Russian): https://habrahabr.ru/post/314116/
Simple knox-based ad blocker: https://github.com/adhell/android

Here is what we can use:
https://seap.samsung.com/api-references/android-standard/reference/android/app/enterprise/FirewallPolicy.html

So, we can replace `iptables` with `FirewallPolicy.setIptablesRerouteRules`

Great thing!

**Comment by Bluscream** [comment]
> This class is deprecated.
Use [Firewall](https://seap.samsung.com/api-references/android-standard)

**Comment by ameshkov** [comment]
@Bluscream i guess we'll need to support old Knox versions as well.

**Comment by Bluscream** [comment]
Yes, sorry if it sounded more like a correction then a addition ♥

**Comment by ameshkov** [comment]
Knox implementation is finished. Now we're waiting for Samsung to accept our "partner application".

**Comment by Bluscream** [comment]
Awesome!

**Comment by boo85** [comment]
Ohhh.. Nice! You all are way faster then I thought! Cant wait to try it out!

**Comment by ameshkov** [comment]
Samsung's answer:

> Thank you for your interest in SEAP. We were unable to upgrade your account to Partner status for the following reason:
> Thank you for applying to become a SEAP partner. Unfortunately your upgrade request has been declined due to the following reason(s):
> - As per SEAP policy, we can only accept SEAP partner requests from a B2B-focused corporation developing mobile solutions. Regrettably we can no longer approve B2C focused enterprises as SEAP partners
> If your status changes, and you feel that you meet the requirements, feel free to apply for a partner account again.
> Thank you,
> The SEAP Team

**Comment by boo85** [comment]
Ohh.. Thats sad! That means u won't be able put that feature into the adguard?

**Comment by Bluscream** [comment]
I mean it's not on the market anyway ;)

**Comment by ameshkov** [comment]
> Ohh.. Thats sad! That means u won't be able put that feature into the adguard?

Yup, we can't do it without an API key, which they won't provide us to be used in a B2C app.

I am fairly disappointed, we have spent quite some time on implementing & testing Knox, and now it's all for nothing.

**Comment by boo85** [comment]
Sorry to hear that too. How do they classify b2b and b2c apps anyway?

**Comment by ameshkov** [comment]
These are literally translated as:
> B2B = business to business
> B2C = business to consumers

So, we could be classified as a B2B if our customers were companies.

**Comment by Bluscream** [comment]
Thats bullshit, please provide a hidden knox version <3

**Comment by Revertron** [comment]
> Thats bullshit

Does Samsung do something else?

**Comment by ameshkov** [comment]
That's off-topic, but I must say that Galaxy S7 phones are pretty good.

**Comment by vozersky** [comment]
Same here. Looks like S7 became a decent phone with recent Nougat update, before that it was meh.

**Comment by Revertron** [comment]
Yep, that's off-topic, but distorted image on the edges of the screen because of curvature are pretty good? :) All other OEMs (Apple, Sony) are doing it normal - let some bezels be, but the Shamesung can't see this bug.

**Comment by ameshkov** [comment]
This issue is now an official Samsung vs others holy war thread

/s

**Comment by Steve2Go** [comment]
Would releasing a version "Adguard for business" (in reality a bulk licencing of the same product or something of the sort not make you a B2B company? 

All it would cost you is a web page on your site.
Just thinking outside the square.

**Comment by ameshkov** [comment]
@Steve2Go as I understand from their answer, they accept requests from "a B2B-focused corporation". I don't think we can fool them to think that we're all about B2B with a single page :(
