### ISSUE TITLE
Add support for exception rules `#@%#` and `#@$#`

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#815]
Android version currently does not implement it:
https://adguard.com/en/filterrules.html#html-filtering-rules-exceptions
https://adguard.com/en/filterrules.html#javascript-rules-exceptions

**Comment by Bluscream** [comment]
I would port whole userscripts into JS rules xD

**Comment by ameshkov** [comment]
Done, review ID: AJC-CR-159
