### ISSUE TITLE
IMO.IM android app.. Still ads are visible

### ISSUE THREAD

**Issue by GSM789** [AdguardTeam/AdguardForAndroid#816]
App name : **imo**
https://play.google.com/store/apps/details?id=com.imo.android.imoim

Most of the normal ads are blocked..but still few remaining...

> **DETAILS :** HTTPS filtering enabled, imo app cache and data cleared..  but it doesn't help...
> Already checked the log file by the developer and no new ads found... But still ads are visible...
> ...

![d](https://cloud.githubusercontent.com/assets/22278693/18910974/0e326054-8598-11e6-99a4-8fed7dbb672e.png)

**LOG FILE**
[imolognewhttps.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/497819/imolognewhttps.txt)

Need a solution.. ..

**Comment by ameshkov** [comment]
Weird, I see that google ad network is blocked and still it manages to get to it somehow (downloads data from googleusercontent.com).

Let's try to block it for this single app. To do it add the following rule to your user filter:
`||googleusercontent.com^$app=com.imo.android.imoim`

I also suggest clearing cache of the google play services app as it could loading ads as well.

**Comment by GSM789** [comment]
Dir ameshkov , 
I did all the things now.. but no changes... (applied the rule, Https enabled, cleared cache of play service, store & imo)....
Then how it happened!!!! Any idea...!!! 
Is that rule work without https filtering or not??(bcz i need to run Adguard without installing https certificate for secure banking!!)

![screenshot_2016-09-29-06-49-48](https://cloud.githubusercontent.com/assets/22278693/18937871/cae72d32-8611-11e6-9f91-56ece21616d0.png)

.....

![screenshot_2016-09-29-06-28-58](https://cloud.githubusercontent.com/assets/22278693/18937846/8fa5c56c-8611-11e6-9b09-9027bb12fe97.png)

..

**Comment by ameshkov** [comment]
> Is that rule work without https filtering or not

In fact it should work even without https filtering. However, it's ok that it didn't help, it was just an idea.

I suppose these ads are from google ad network and they are somehow cached in one of Google own apps. Try clearing cache & data for google apps as well.

One more question: could it be that you have disabled AG for any app manually?

**Comment by GSM789** [comment]
Dir ameshkov.,
  thanks for the rule... 
I need some more ideas from u to block this ads... Haha..

Actually I disabled few apps from Adguard filtering MANUALLY.... (Some Google apps and few other-for banking).. but enabled with play service....
Is this really a matter!!!! If so ,pls tell me which Google app must be add to Adguard.

**Comment by ameshkov** [comment]
> Is this really a matter!!!! If so ,pls tell me which Google app must be add to Adguard.

It does matter as Google ads could be downloaded by their own apps.

Frankly, I don't remember which app exactly does it. The package name is usually `com.google.android.gms`

**Comment by GSM789** [comment]
I found that, com.gms is Google play service....

![_20160929_170438](https://cloud.githubusercontent.com/assets/22278693/18952344/dd88aac4-8666-11e6-92d3-29c1dd302c8b.jpg)

Its blocked... Any other app !!???

**Comment by ameshkov** [comment]
For instance, 'Android OS', it includes a lot of packages

**Comment by GSM789** [comment]
Really,,,
Ohhh im sorry.. i simply disabled it from Adguard....(i thought there is a matter of security)..
I will check it... And comment soon...
Thank you...

**Comment by GSM789** [comment]
Can u provide me any rules for Android OS and Play service!!!????????

**Comment by ameshkov** [comment]
You need no rules, ads will be blocked.

It's just they already downloaded and cached so you should wait a bit (or clear cache & data for all these apps).

**Comment by GSM789** [comment]
Ok... Thanks.. i will clear cache and check it....
