### ISSUE TITLE
AT&T wi-fi calling

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#817]
Here are the details:
https://github.com/AdguardTeam/AdguardForAndroid/issues/171#issuecomment-248324910

We should exclude `129.192.166.0/24` subnet from the VPN in order for Wi-Fi calling to work.

**Comment by ameshkov** [comment]
> id 1411932 

@vozersky regarding this ticket, please ask user to do the following:
1. Open Adguard
2. Settings -> Advanced -> Low-level settings
3. Open `pref.vpn.ipv4.routes.excluded`
4. Add new line there: `129.192.166.0/24`

**Comment by vozersky** [comment]
@ameshkov that worked fine, got a confirmation from user

**Comment by ameshkov** [comment]
Great, thank you!

This route will be excluded by default in v2.8
