### ISSUE TITLE
Сбор LogCat - Предложение

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardForAndroid#818]
Предлагаю обновить инструкцию. Я нашел более быстрый способ получения лога https://kb.adguard.com/index.php?/Knowledgebase/Article/View/63/5/kk-poluchit-log-logcat-n-ustrojjstve-android
Вот ссылка на программу: http://4pda.ru/forum/index.php?showtopic=260024
Нужны рут права. Вот инструкция: 
1. Запускаем CatLog.
2. Нажимаем кнопку меню. Там выбираем Запись/Record. Появится диалог выбора имени лога. Можно переименовать файл или просто нажать ОК. После этого можно нажать кнопку домой. CatLog продолжит записывать лог в фоновом режиме.
3. Переходите в нужное приложение. Воспроизводите там ошибку/нужные действия.
4. Переключаемся в CatLog, нажимаем меню, выбираем Остановить запись/Stop record. При этом будет сообщено имя файла, куда был сохранен лог.
5. Полученный лог отправляем кому и куда надо.
Или вот еще инструкция для создания не полного лога, а только для отдельного приложения http://4pda.ru/forum/index.php?showtopic=260024&view=findpost&p=52718828

**Comment by ameshkov** [comment]
Ох, ну это точно не быстрее.

А еще есть несколько моментов, почему нам с программой удобнее:

1. Вместе с логами отправляются настройки программы и общие данные о системе.
2. Нужны рут права, у большей части пользователей их нет.

**Comment by ministr91** [comment]
Вы инструкцию видели? Там столько всего нужно сделать, так что с прогой гораздо быстрее. Я предлагаю добавить этот способ в альтернативный для тех, у кого есть рут. 
http://4pda.ru/forum/index.php?showtopic=260024 эта программа как раз и позволяет собрать как и полный лог, так и отдельного приложения.

**Comment by ameshkov** [comment]
Да у нас для этого отдельная инструкция есть (про логкат)

@vozersky в нее имеет смысл добавить

**Comment by ministr91** [comment]
Да, это хорошо. А ссылку можете кинуть на эту инструкцию?

**Comment by ameshkov** [comment]
Вот:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/63/5/kk-poluchit-log-logcat-n-ustrojjstve-android

**Comment by ministr91** [comment]
Пока не добавили (

**Comment by ameshkov** [comment]
@vozersky посмотри плз

**Comment by vozersky** [comment]
Добавили в статью
