### ISSUE TITLE
Use Android settings for time format

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardForAndroid#819]
Привет, обновление правил показывает в 12 часовом формате. В настройках стоит 24 часа
![screenshot_20160929-012255](https://cloud.githubusercontent.com/assets/10572914/18934764/5be11d44-85e4-11e6-9d7d-cdea62fb7cdc.png)
![screenshot_20160929-012534](https://cloud.githubusercontent.com/assets/10572914/18934769/637fb29a-85e4-11e6-9de6-648a1ad04922.png)

**Comment by nkartyshov** [comment]
fixed
