### ISSUE TITLE
User filter import: no restrictions on the file type

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardForAndroid#820]
User can use a binary file.

**Original text:**

> Настройки - собственный фильтр -  импорт -  обзор. Можно выбрать апк в качестве правил и он его автоматом импортирует как тект) , наврено любой файл туда можно. Не знаю баг это или нет,  если можно,  сделать импорт только по  текстовому файлу

**Comment by ameshkov** [comment]
Duplicate
