### ISSUE TITLE
$replace rules are occasionally not applied

### ISSUE THREAD

**Issue by SlowMemory** [AdguardTeam/AdguardForAndroid#821]
Sample: http://play.rmcnmv.naver.com/vod/play/v2.0/E00EB3DF9B07E3D70E4F1D941F95CD8DA045?key=V12344f2b59e690d9cf356ac265f0176e6ecc2b5254dc737c1878320fdf634ad794846ac265f0176e6ecc&pid=rmcPlayer_14751789832674830&sid=2010&ver=2.0&devt=html5_mo&doct=json&ptc=http&cpt=vtt&ctrls=%7B%22visible%22%3A%7B%22expand%22%3Afalse%2C%22logoDimmed%22%3Atrue%2C%22badge%22%3Atrue%2C%22scrap%22%3Afalse%2C%22logo%22%3Afalse%2C%22seekingTime%22%3Atrue%2C%22playCount%22%3Atrue%2C%22commentCount%22%3Atrue%2C%22fullscreen%22%3Atrue%2C%22title%22%3Atrue%2C%22writer%22%3Atrue%2C%22linkCount%22%3Afalse%2C%22createTime%22%3Afalse%2C%22thumbnail%22%3Atrue%7D%2C%22clicked%22%3A%7B%22expand%22%3Afalse%2C%22subtitles%22%3Afalse%7D%7D&lc=ko_KR&adi=%5B%7B%22adSystem%22%3A%22AMS%22%7D%5D&adu=http%3A%2F%2Fams.rmcnmv.naver.com%2Fitem%2Fcreate%2F2010%2FNAVER%3Fams_ctgr%3DLIFE%26ams_chnl%3Dmutsister%26ams_videoId%3DE00EB3DF9B07E3D70E4F1D941F95CD8DA045%26ams_cp%3D1952%26navervodtype%3DRMC%26unit%3D1104A%26cp%3D1952%26st%3D2143%26chl%3Dmutsister%26cat%3DLIFE%26cl%3D1136745%26svc%3Dtvcast%26cc%3DN%26ctry%3DKR%26v_theme%3DNA%26ams_rule%3D%255B%257B%2522type%2522%253A%2522pre%2522%252C%2522exposure%2522%253Atrue%252C%2522replayExposure%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522mid%2522%252C%2522exposure%2522%253Atrue%252C%2522replayExposure%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522post%2522%252C%2522exposure%2522%253Atrue%252C%2522replayExposure%2522%253Atrue%257D%255D&sm=tvcast&cv=NAVER

A rule 
```
||play.rmcnmv.naver.com/vod/play/v2.0/*&devt=html5_mo*&ctrls=*&adi=%5B%7B$replace=/"advertise"(.|\s)*?}\s*\,\s*("share")/\$2/
```
 is not applied. It IS applied in Adguard for Windows.

+)Above link expires as time goes, if you visit http://m.tvcast.naver.com/v/1136745 with mobile UA a similar request will appear.

Forum link:
https://forum.adguard.com/index.php?threads/some-replace-rules-are-not-applied.14280/

**Comment by ameshkov** [comment]
Btw, it's pretty hard to match json nested object properly.

Will it work if you simply replace `"advertise":{` with `"somerandomname":{`?

**Comment by SlowMemory** [comment]
```
||play.rmcnmv.naver.com/vod/play/v2.0/*&devt=html5_mo*&ctrls=*&adi=%5B%7B$replace=/"advertise"[\s\S]*?}\s*\,\s*("share")/\$1/
```
is still not being applied in Android. 
>>Will it work if you simply replace "advertise":{ with "somerandomname":{?

I guess it should, but I can't test until this is resolved :(

**Comment by ameshkov** [comment]
The rule text is invalid, you forgot to escape `}` symbol.

```
/"advertise"[\s\S]*?}\s*\,\s*("share")/\$1/
```

Currently the only way to understand that the rule is invalid is to check the app log:
```
Invalid filter rule: ||play.rmcnmv.naver.com/vod/play/v2.0/*&devt=html5_mo*&ctrls=*&adi=%5B%7B$replace=/"advertise"[\s\S]*?}\s*\,\s*("share")/\$1/
                                                                          java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 20
                                                                          "advertise"[\s\S]*?}\s*,\s*("share")
                                                                                              ^
```

**Comment by SlowMemory** [comment]
Oops, sorry for a trivial mistake.
