### ISSUE TITLE
Https filtering does not work on https://www.opennet.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#822]
https://forum.adguard.com/index.php?threads/%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-https-%D0%BD%D0%B0-https-www-opennet-ru.14356/

**Comment by Revertron** [comment]
From the logs:
```
Client alert raised. Level: fatal, Description: protocol_version protocol_version(70), Message: Failed to read record
```

**Comment by ameshkov** [comment]
Hm, so what is in server hello?

**Comment by Revertron** [comment]
Okay, from the traffic capture it seams that opennet.ru uses only old version of TLS (1.0), it tries to fallback every connect with higher TLS version to 1.0.
We get an error on this unsecure fallback to old version and add it to temporary exceptions. If the browsers want to deal with such servers and unsecure fallback it will be on their conscience.
