### ISSUE TITLE
Adguard protection spontaneously disables

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#824]
Happens after 20-30 minutes of work.

Android 5.1, Flyme 5.1.3.4G, Meizu M3 Note

Forum thread: https://forum.adguard.com/index.php?threads/14469/

Logs: support user ID 1423308

**Comment by ameshkov** [comment]
@vbagirov please read here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/800
