### ISSUE TITLE
Firewall notification issue on Samsung device

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#825]
**634830**

Samsung SM-N910C
Android 6.0.1
Adguard version 2.7.220

User can't tap on the message about blocked app to let it one-time access - he can, but doesn't get the needed option
Screenshot:
<details>
![1](https://cloud.githubusercontent.com/assets/20476168/19083895/cfc8083a-8a6c-11e6-97a6-c8e47432ea6c.png)
</details>
 In previous version he could do it. 
Screenshot
<details>
![2](https://cloud.githubusercontent.com/assets/20476168/19083875/bac76b6a-8a6c-11e6-9109-1c6bf6fc940c.png)
</details>
Logs attached.
<details>
[debug (5).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/509061/debug.5.txt)
</details>

**Comment by evgeniy-ADG** [comment]
I confirm.

**Comment by vozersky** [comment]
@evgeniy-ADG on what device were you able to reproduce it?

**Comment by evgeniy-ADG** [comment]
Samsung A5 2016, Android 6. Blocked Viber, but was unable to unblock it by tapping on that notification.

**Comment by vozersky** [comment]
@evgeniy-ADG and the vendor firmware version?

**Comment by Revertron** [comment]
If you have more notifications Android is contracting them to be narrow. You can swipe them from their center down and they will become full sized. Anyway, normal devices do such thing, I dunno about Samsung.

**Comment by evgeniy-ADG** [comment]
<details>
![Uploading Screen Shot 2016-10-05 at 3.36.48 PM.png…]()

**Comment by vozersky** [comment]
@Fridrix  you have to specify ticket id in first message

it's 634830 here

**Comment by vozersky** [comment]
@Revertron 

This is actually what I suggested first.

On my nexus 5 and samsung galaxy s 7 it works fine:

narrow space: https://dl.dropboxusercontent.com/u/57517781/screenshots/Screenshot_20161001-140958.png

full notification is shown: https://dl.dropboxusercontent.com/u/57517781/screenshots/Screenshot_20161001-141010.png

@evgeniy-ADG it looks like it doesn't work on some samsung firmwares? could you please try to move it with different gestures as @Revertron suggested in his comment? It has to become full-size, really.

**Comment by vozersky** [comment]
let's keep 1 issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/966
