### ISSUE TITLE
Protection had not gone on pause after SPM was activated

### ISSUE THREAD

**Issue by gshumihin** [AdguardTeam/AdguardForAndroid#827]
**_Steps to reproduce:_**
1. Activate Power saving mode.
2. Go to any browser and try to open any page

**_Expected result:_**
1. Adguard goes on pause after Power saving mode was enabled
2. Pages loads fine
3. Ads are not blocked

**_Actual result:_**
1. When Power saving mode activated protection doesn't go on pause.
2. When Power saving mode activated Adguard blocks all internet connections:
<img src="https://cloud.githubusercontent.com/assets/8577547/19113558/ed1ade7a-8b12-11e6-8507-42756008c5a6.png" width="200">
3. Adguard go on pause after Power saving mode turned off

**Comment by TPS** [comment]
Maybe AG, instead of just deactivating (or blocking everything 😱), maybe should do [DNS-blocking _only_](https://blog.adguard.com/en/great-battery-saving-mode-of-adguard-for-android/)?

**Comment by ameshkov** [comment]
Oh, actually this issue is already resolved in newer Samsung devices.
