### ISSUE TITLE
Let users sort User filter rules

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#828]
E.g. by alphabet, by addition time etc.

**Comment by TPS** [comment]
Related requests(s): https://github.com/AdguardTeam/AdguardForAndroid/issues/308#issuecomment-184274805

**Comment by Revertron** [comment]
We do not save editing, adding or deletion time for user rules. The only way to sort may be alphabetical.

**Comment by TPS** [comment]
Is alphabetical sorting implemented, then?

**Comment by The-Commissioner** [comment]
@TPS I have it sorted out now in alphabetical order and frankly that should be the default too as it helps in speeding up things. I even sorted out their own filter list in alphabetical order. Filtering is marginally fast now on my end. I used notepad ++ for this function. :-)

**Comment by ameshkov** [comment]
Guys, I am pretty sure that sorting filters in a user filter is a bad idea and that's why I marked it as "won't fix".

However, we provided an "edit" mode so that you could re-sort the rules in any order.

**Comment by The-Commissioner** [comment]
Now you got me curious, I'm interested in knowing why it's a bad idea to sort it?

**Comment by ameshkov** [comment]
Filter is basically a text file, and not a "table", filters devs usually maintain their own structure inside of a file and any kind of sorting breaks this structure.

**Comment by The-Commissioner** [comment]
> Filter is basically a text file, and not a "table", filters devs usually maintain their own structure inside of a file and any kind of sorting breaks this structure.
I think the structure that you speak of, is related to maintaining their own convenience rather than the functional aspect of it. 

In user filter, the user is the developer. So I don't know how it would break their structure.

**Comment by TPS** [comment]
> … filters devs usually maintain their own structure inside of a file and any kind of sorting breaks this structure

@ameshkov _We're_ the filter devs, so _allowing_ us to sort w/o having copy/paste in-&-out is a major convenience.
