### ISSUE TITLE
Adguard crashes on Oxygen OS

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#829]
After the 3.2.7 Oxygen OS update Adguard keeps getting disabled.

Logs (regular and logcat) will be available in this thread:
https://forum.adguard.com/index.php?threads/14468/

**Comment by Revertron** [comment]
@vbagirov need logcat to see what is going on...

**Comment by vbagirov** [comment]
No answer from user so far.
