### ISSUE TITLE
Make `pref.filtered.ports` understand port ranges

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#830]
Syntax could be like:
`1-3,4,5,6,80:8080`

Source:
https://github.com/AdguardTeam/AdguardForAndroid/issues/796#issuecomment-251839912

We should also test that websites using non-standard ports continue to work ok.

**Comment by TPS** [comment]
I think maybe limiting the _length_ of the range (via warning?) to 10 or 100 may be smart.…  Else, there'll be 1 of us knuckleheads filing a report stating "AG broke my phone" after inputting `0-65536` or [`80-8080`](https://github.com/AdguardTeam/AdguardForAndroid/issues/830#issue-181364686). 😜

**Comment by ameshkov** [comment]
More information about this issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/996#issuecomment-275139435

In case of VPN it's easy.
In case of Proxy+Auto, mind that iptables `--dport` supports setting port ranges.

**Comment by ameshkov** [comment]
Done, review ID: AJC-CR-164

@Revertron we need to test it on a rooted device. Could you please do it?

**Comment by ameshkov** [comment]
@nkartyshov confirmed, that it works ok on a rooted device.

Now we need take some time to check if it causes any issues.
Current setting value:
`80,443,1024:65535`

**Comment by TPS** [comment]
> `1024:65535`

@ameshkov Are you _sure_ you want to allow such wide port ranges?  If so, you might want a complementary  `pref.UNfiltered.ports` option to whitelist some that _shouldn't_ be filtered.…

**Comment by Revertron** [comment]
We could use syntax like this: `80,443,8123,5000:65535,-22,-110` - the minuses will mean exclusion :)

**Comment by ameshkov** [comment]
> @ameshkov Are you sure you want to allow such wide port ranges?

We'll see, that's what beta test is for:)

> We could use syntax like this: 80,443,8123,5000:65535,-22,-110 - the minuses will mean exclusion :)

It would be redundant as we can exclude any port using the current syntax by **not including** it.
