### ISSUE TITLE
ua.com.rozetka.shop does not work with HTTPS filtering

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#831]
https://play.google.com/store/apps/details?id=ua.com.rozetka.shop&hl=en
При входе ошибка сети
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19162832/29f0d63e-8c02-11e6-9294-4e949c6b67b7.png)

**Comment by nkartyshov** [comment]
added
