### ISSUE TITLE
Add $important modifier

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#833]
`$important` modifier applied to a rule increases its priority over any other rule without $important modifier. Even over basic exception rules.
#### Example 1:

```
||example.org^$important
@@||example.org^
```

`||example.org^$important` will block all requests despite of the exception rule.
#### Example 2:

```
||example.org^$important
@@||example.org^$important
```

Now exception rule also has `$important` modifier, so it will be applied.
#### Example 3:

`$important` modifier will be ignored if document-level exception rule is applied to the document.

```
||example.org^$important
@@||test.org^$document
```

If request to `example.org` is sent from `test.org`, the rule won't be applied despite it has `$important` modifier.

**Comment by ameshkov** [comment]
@Alex-302 please note, that after implementing this `$replace` and `$protobuf` rules will loose their priority over other basic rules. So, you'll have to add `$important` modifier to them.

Also older AG versions will ignore rules with unknown modifiers, so you'll have to keep old rules for some time.

**Comment by TPS** [comment]
If this is added, will this also solve the issue of anti-adblockers abusing `!important` (such as [f***adblock](https://www.npmjs.com/package/fuckadblock)) to mess up such users — or is this not related @ all?

**Comment by ameshkov** [comment]
@TPS no, that's not related.

The purpose is to allow us to change particular rules priority.

**Comment by ameshkov** [comment]
@Alex-302 it's time to add duplicate rules with $important modifier.

We need to do this for $replace and $protobuf rules.

**Comment by ameshkov** [comment]
Done

**Comment by Alex-302** [comment]
> We need to do this for $replace and $protobuf rules.

done

**Comment by ameshkov** [comment]
Just found a bug, $replace rules could cause elements removal from the page code.

**Comment by ameshkov** [comment]
Resolved
