### ISSUE TITLE
Adguard crashes due to "Too many open files" error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#834]
Problematic app: **Popcorn Time**
Actually we have this issue with some torrent clients as well.

Source:
http://forum.xda-developers.com/showpost.php?p=69001863&postcount=1689

Apps create too many open UDP connections which leads to "Too many open files" error (more than 1024 open file descriptors).

The easiest way to fix this is to limit maximum number of open UDP connections. We will set the limit to 100.

**Comment by nkartyshov** [comment]
В приложение можно использовать VPN. Есть предположение, что падает из-за использования vpn.
Так как приложение не падает если смотреть видео без vpn.

**Comment by nkartyshov** [comment]
fixed
