### ISSUE TITLE
Bug with Updato app when Adguard enabled.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#836]
Updato app (https://play.google.com/store/apps/details?id=samsungupdate.com&hl=en) can't  update device because of Adguard. After entering device model and choosing update and download options app redirects to page, which says that we can't proceed it because of Adblocker.

Samsung-N910P
Android 6.0.1
Ver. 2.7.220
Logs
<details>[adguard.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/520125/adguard.zip)</details>
Video guide
<details>[SCR_20161006_175304 (1).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/520126/SCR_20161006_175304.1.zip)</details>
Ticket code 1138191

**Comment by nkartyshov** [comment]
@gshumihin Можешь проверить скачивание архивов с прошивкой с адгардом и без него.

**Comment by gshumihin** [comment]
Works fine with latest beta. Tested on Samsung S7.

**Comment by nkartyshov** [comment]
fixed
