### ISSUE TITLE
Crunchyroll compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#837]
https://play.google.com/store/apps/details?id=com.crunchyroll.crunchyroid&hl=en

**Comment by Revertron** [comment]
This app does not load its content - is it some manga cartoons or what? I can see the catalog without problem, but I can not see real content.

**Comment by ameshkov** [comment]
> Content availability varies by region.

I guess you should search for what's available for you

**Comment by Revertron** [comment]
I can not find anything working there.

**Comment by ameshkov** [comment]
@gshumihin could you please check it?

**Comment by Bluscream** [comment]
Broken here, too

**Comment by nkartyshov** [comment]
Fixed add api.crunchyroll.com to ssl whitelist
