### ISSUE TITLE
Make "paused" notification visible even when "notification type" set to none

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#838]
Here is the thing with it:
1. It seems that VPN is enough to keep our process priority equal to foreground
2. However, when protection is paused due to the network access, there's no VPN nor icon to keep process alive
3. When network access is back, protection is not started.

**I may be wrong**. I've got the issue after a long phone call.

**We need to test it first and find a way to reproduce the issue.**

**Comment by Revertron** [comment]
[adguard-test-issue-838.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/534274/adguard-test-issue-838.zip)
Let's test this build!

**Comment by ameshkov** [comment]
I'll check it, thank you!

**Comment by Revertron** [comment]
Added to low level options, will test it in beta.
