### ISSUE TITLE
Adguard cannot handle HTTP CONNECT request properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#839]
**Steps to reproduce:**
1. Enable HTTPS filtering
2. Set up a proxy server in the wi-fi settings. Use this proxy: https://forum.adguard.com/index.php?threads/%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B8-%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2-%D0%A0%D0%9A%D0%9D.15037/
3. Make sure that the proxy port is listed in `pref.filtered.ports` (3128,3148)
4. Go to rutracker.org.
5. Refresh the page.

**Expected result:**
Website is filtered ok.

**Actual result:**
SSL error.

**Also I didn't test it with disabled HTTPS filtering.** There is a possibility that we have the same issue in this case.

**Comment by ameshkov** [comment]
User's log:
[adguard.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/525821/adguard.txt)

**Comment by Revertron** [comment]
Yes, we are not sending CONNECT request to proxy when we are CONNECTing in `SslProxyRemoteEndPoint.connect()`, I will try to think of something...

**Comment by Revertron** [comment]
Fixed!
