### ISSUE TITLE
Certificate installation is not detected

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#841]
**Steps to reproduce:**
1. Install the app (or clear app data)
2. Clear android credentials
3. Settings -> HTTPS filtering
4. Install the certificate
5. Now clear android credentials again
6. Go to HTTPS filtering

**Expected result 1:**
Adguard detects that certificate is not installed anymore

**Actual result 1:**
It is not detected.
1. Exit app and go to https filtering again. Now it detects status properly.
2. Install certificate again

**Expected result 2:**
Adguard detects that certificate is installed and enables https filtering.

**Actual result 2:**
Nothing happens.

**Comment by Revertron** [comment]
Checked 3 times - unable to repeat.
Do you have "Please wait" dialogs when you go to https filtering fragment?

**Comment by Revertron** [comment]
![photo_2016-10-14_18-24-55](https://cloud.githubusercontent.com/assets/105154/19394940/89f31f94-923b-11e6-9c57-5da6f74faa10.jpg)
Do you have such dialog?

**Comment by ameshkov** [comment]
> Do you have such dialog?

Nope

**Comment by ameshkov** [comment]
It seems that this dialog appears one time only for me.

There is no loading dialog whenever I go to https filtering again.

**Comment by Revertron** [comment]
This is weird, as I in onResume() I have this code: `new CheckTask().execute();` - it MUST show dialog and perform the task with checking for certificate...

**Comment by ameshkov** [comment]
Got it, i'll try to debug it on my side.

**Comment by ameshkov** [comment]
It appears to be by design. List of accepted issuers is cached inside of the trustmanager and we do nothing with it.
