### ISSUE TITLE
Anews app images are broken in proxy mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#842]
https://play.google.com/store/apps/details?id=anews.com&hl=en

Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=54044349

**Comment by ameshkov** [comment]
Customer ID:
1430067

**Comment by vgavrish** [comment]
Пришли логи от пользователя. 
VPN Adguarg. Dr.Web vpn отключен. Приложение Anews режет фото.
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/531616/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/531617/state.txt)

**Comment by nkartyshov** [comment]
fixed
