### ISSUE TITLE
Foursquare app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#846]
Source:
https://forum.adguard.com/index.php?threads/%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83-adguard-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D0%B5%D1%82-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D1%83-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%B8-%D0%B2-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-foursquare.14869/

**Comment by nkartyshov** [comment]
Проблема не в фильтрах, у пользователя версия старая версия android.

**Comment by nkartyshov** [comment]
User answered:
```
Версия Андроида у меня указана в подписи - 4.2.2
А версия Adguard - 2.7.220
Планшет ASUS MemoPad ME302KL FHD 10 LTE
```

**Comment by nkartyshov** [comment]
Пользователь нашел решение проблемы.
