### ISSUE TITLE
Turkish is not comleted

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardForAndroid#847]
![screenshot_2016-10-18-19-13-21](https://cloud.githubusercontent.com/assets/19608513/19487191/c2da464a-9572-11e6-8cee-5af67ccd5953.png)

![screenshot_2016-10-18-19-13-41](https://cloud.githubusercontent.com/assets/19608513/19487194/c713acf6-9572-11e6-9984-138d2d9414ea.png)

![screenshot_2016-10-18-19-18-28](https://cloud.githubusercontent.com/assets/19608513/19487201/cfb71d02-9572-11e6-88d1-bdb8b965c3ff.png)

![screenshot_2016-10-18-19-20-24](https://cloud.githubusercontent.com/assets/19608513/19487216/dd8f34aa-9572-11e6-9dbf-5f4d815835f3.png)

![screenshot_2016-10-18-19-22-35](https://cloud.githubusercontent.com/assets/19608513/19487238/f45be5f2-9572-11e6-866d-0c6b4d4064bd.png)

![screenshot_2016-10-18-19-23-34](https://cloud.githubusercontent.com/assets/19608513/19487247/fb59ec64-9572-11e6-9b81-42d31f9f8ac4.png)

**Comment by vbagirov** [comment]
@thislife81 Hi! I fixed the translation errors you pointed out, but the parts which are not translated at all are a bit trickier. We translate Adguard on a volunteer basis, meaning that anyone who wishes to help us can translate phrases into his language on OneSkyApp. We provide free licenses as a little bonus for those who help us with translations.

In case you would like to finish the Turkish translations, you can register on OneSkyApp (or use your GitHub account to log in there). Let us know if you do, we will provide you with a free license :)

**Comment by thislife81** [comment]
I already registered on OneSkyApp with this Github account and started to help you finishing Turkish and Russian languages. :)

**Comment by ameshkov** [comment]
@nkartyshov please take a look, language name cannot be changed in oneskyapp, so you should change it manually in the code.

**Comment by nkartyshov** [comment]
updated
