### ISSUE TITLE
We need an article on kb.adguard.com describing "Low Level Settings"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#85]
@Revertron, @vbagirov will need your help to do this.

**Comment by vbagirov** [comment]
Done.

**Comment by TPS** [comment]
Would you link it here, please? :bow:

**Comment by vbagirov** [comment]
@TPS 
[Sure!](https://kb.adguard.com/index.php?/Knowledgebase/Article/View/64/9/low-level-settings-guide-for-adguard-for-android)
