### ISSUE TITLE
Change the way we use to block IPv6

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#853]
I am talking about `pref.block.ipv6` low-level setting.

Relevant discussion:
https://forum.adguard.com/index.php?threads/email-not-syncing-since-upgrade-to-7.14862/

https://play.google.com/store/apps/details?id=de.lennartschoch.disableipv6&hl=en
http://forum.xda-developers.com/general/networking/guide-disable-ipv6-android-t3298659

**Comment by TPS** [comment]
Is this relevant at all for apps we block _individually_ via firewall that may use IPv6?  Or _just_ globally?

**Comment by Revertron** [comment]
This is for prevention of loading ads by IPv6.

**Comment by ameshkov** [comment]
This is for disabling IPv6 *globally*.

You see, when user uses "proxy" filtering mode with automatic setup, IPv6 connections may slip through us. The easiest solution is to disable IPv6 globally.

**Comment by TPS** [comment]
& then filter normally when/if the IPv6→IPv4 translation happens.

When this setting  (& maybe when the `.dns` setting) is on, does AG specifically request IPv4 addresses/records _only_, then?

**Comment by ameshkov** [comment]
You can change DNS when AG is in VPN mode, and we have no issues with VPN.

The issue exists in proxy+automatic mode only as `iptables` cannot control IPv6 traffic.
And `ip6tables` does not provide a good way for traffic redirection, so here we are, providing an option for blocking whole IPv6 instead:)

**Comment by Revertron** [comment]
Done.
