### ISSUE TITLE
Google Pixel "now on tap" feature does not work when Adguard is on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#856]
Customer ID:
1434869

I see massive UDP traffic there. 

```
09:33:26.116 [Thread-3] DEBUG com.adguard.android.filtering.vpn.i - UDP connect to /74.125.21.105:443. Process info: com.google.android.googlequicksearchbox /172.16.209.1:50821 /74.125.21.105:443 10045
```

**EDIT:** solution below doesn't work after all..

Temporary solution would be to disable Adguard for `com.google.android.googlequicksearchbox`:
1. Go to settings -> apps and statistics
2. Find `Google App` there
3. Uncheck "Enabled"
4. Restart Adguard protection

**Comment by ameshkov** [comment]
It appears that this issue exists with OpenVPN as well. I wonder what causes it:(

**Comment by ameshkov** [comment]
We should try excluding `com.google.android.backuptransport`, i'll look into it later.

**Comment by ameshkov** [comment]
It seems that it works ok in "Google App Beta"

**Comment by evgeniy-ADG** [comment]
>Google app is updated and it shows I am a tester now and still having the same problem as before. 

>Uninstalled all software then downloaded from the link provided and reinstalled. Still nothing. Are there any other permissions I'm missing when I need to enable the app? 

1456163 

Please advise.

**Comment by evgeniy-ADG** [comment]
false alarm
