### ISSUE TITLE
List system packages in the "Tech info" section of "Android OS" details screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#857]
I am talking about "Apps Management" section.

**Comment by Revertron** [comment]
Do you mean "packages" from ReservedApps? Or what?

**Comment by ameshkov** [comment]
Nah.

I mean we now have a section "Tech info" in the bottom of the "App Details" view.
For "Android OS" we have just "This is a system package" string there (or something like that).

Instead we should list all included packages there.

**Comment by Revertron** [comment]
But we store there traffic from ReservedApps and Unknown apps (in case that connection  is undetermined). We do not store "packages" of system apps or something else.

**Comment by ameshkov** [comment]
Here it is:
```
        if (!AppRulesManager.getInstance().isTrafficFilteringAndroidOs()) {
            packageInfoList.addAll(PackageUtils.getInstalledReservedPackages(this));
        }
```

The wording is a bit confusing though, `getInstalledReservedPackages` returns system apps as well.

**Comment by Revertron** [comment]
![device-2016-10-31-090500](https://cloud.githubusercontent.com/assets/105154/19847743/457017ee-9f49-11e6-8c42-339bdb67bfbc.png)

**Comment by ameshkov** [comment]
1. `Package names:` --> `Included packages:`
2. Add a new line between `meta package` and `included packages`
3. Sort package names

**Comment by Revertron** [comment]
Done.
