### ISSUE TITLE
Round icons support for Android 7.1

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#859]
http://android-developers.blogspot.ru/2016/10/android71-dev-preview-available.html

**Comment by TPS** [comment]
[Seriously, can't Google leave well enough alone?!  😡 😠](https://github.com/AdguardTeam/AdguardForAndroid/issues/203)

**Comment by TPS** [comment]
I'm running 7/Nougat now, so if you need testing/data/whatever, count me in. ☺️

Also, should I open another issue for my colorless AG VPN  notification icon?  I've a colored icon for another app still & it seems Nougat allows customizing what icon shows when the VPN is engaged (instead of just the :key:).  Is it worth looking into?  I really dislike all the bland notifications. 😢

**Comment by ameshkov** [comment]
> I've a colored icon for another app still & it seems Nougat allows customizing what icon shows when the VPN is engaged (instead of just the 🔑). Is it worth looking into? I really dislike all the bland notifications. 😢

Yeah, that is interesting! Where've you read about VPN icon customization?

**Comment by TPS** [comment]
<Summary>I didn't *read* about it; I ***see*** it on my screen:
<Details>

![screenshot_20161205-190633](https://cloud.githubusercontent.com/assets/185902/20907809/92a86fac-bb1e-11e6-80d6-26417c065f94.png)

</Details>

If you notice, in the notification bar @ top, among others, I've a yellow sun (☀️) & black-&-white AdGuard on the left side, & VPN lock (🔑) on the right.
</Summary>

**Comment by ameshkov** [comment]
Ah, I misunderstood you, I thought you meant that we can replace *key icon* with something else.

**Comment by TPS** [comment]
Oops, I apologize for my unclarity.  All I'm really asking for, under Nougat VPN _or_ proxy, always allow that list option to choose which AG icon shows in the notification bar. :bow:

**Comment by ameshkov** [comment]
@TPS filed a feature request:
https://github.com/AdguardTeam/AdguardForAndroid/issues/976

We'd better research this.

**Comment by ameshkov** [comment]
@nkartyshov updated resources:
https://www.dropbox.com/sh/j0yyv1yr8ggv4vj/AAALE0FfCmToTI2AQkR1jYuna?dl=0

Round icons:
https://www.dropbox.com/sh/pjciyor0hz4ef2l/AACRxad647xNRxUEQvt1c4kma?dl=0

**Comment by nkartyshov** [comment]
Done, review AFA-CR-64

**Comment by ameshkov** [comment]
Also please review the notification icons:
[notification_icons.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1190175/notification_icons.zip)

For some of them, we have just 48x48 for some reason.

**Comment by nkartyshov** [comment]
We didn't have notification icons for xxhdpi.

**Comment by nkartyshov** [comment]
done
