### ISSUE TITLE
Full page advertisement missed on http://filext.com/…

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#86]
It's missed on both VPN & proxy, just FYI.

**Comment by ameshkov** [comment]
It's better to create missed ads reports in ExperimentalFilter project:
https://github.com/AdguardTeam/ExperimentalFilter/issues/837

**Comment by TPS** [comment]
Thanks!  I was hesitant to do so, though, because I don't run any other platform.…  Is there a simple way to tell which missing ad is specific to Android?  Or should I _always_ file such in https://github.com/AdguardTeam/ExperimentalFilter/issues/ ?

**Comment by ameshkov** [comment]
Yep, everything about missed ads or broken pages and such should be reported there.
