### ISSUE TITLE
OpenSource

### ISSUE THREAD

**Issue by niclasdh** [AdguardTeam/AdguardForAndroid#861]
"such project needs to be transparent" - https://blog.adguard.com/en/adguard-open-source-policy/

As allready mentioned on your Webpage an Application which spoofs the complete user's network activity should be OpenSource. The iOS Application is already OpenSource. Why is the Sourcecode of the Android App not OpenSource?

**Comment by ameshkov** [comment]
The policy is pretty simple:

* Freeware apps must be open source ([Adguard for iOS](https://github.com/AdguardTeam/AdguardForiOS), [Browser extensions](https://github.com/AdguardTeam/AdguardBrowserExtension), [Adguard Content Blocker](https://github.com/AdguardTeam/ContentBlocker)).
* Paid apps cannot.

**Comment by TPS** [comment]
No paid version for iOS, like for Android & (I believe) Windows?  _That_ seems to be the oversight! 😜

Seriously, though, @niclasdh, if you want open-source adblocking software, take your pick out there.  I've been through many, but just couldn't put up with them or the teams behind them.  Have you tried working w/ or on any of those? 😨

**Comment by niclasdh** [comment]
I accept that this is a shareholder's Business decision. But I just wanted to notice that I am probably not the only one who have a bad feeling, when he is logging into his Bank Account and he knows there is an Application which is able to Scan all this data. So nobody knows what this wonderful Application does in the Background and what it is sending to the mothership. 

It's a question of how much effort the "evil guy" will investigate to disable the license check. I agree that it's much easier for a Developer to remove this license check on an OpenSource Application, than on one, which he have to be decompile first. But I think the most of your Customers don't want to pull the git repo, change the code and compile again for each Update of the Application.

In my opinion they want a good working Application which Updates itself without much effort and they will pay for it.

@TPS I know they are some alternatives. But I didn't found one which is working that stable and which does not require root.

**Comment by TPS** [comment]
@niclasdh I had a beautiful response typed all out… & then my phone crashed. :hurtrealbad:

In short, neither did I, which is why, _sometimes_, a dedicated, paid full-time small team developing a closed-source software can beat all the open-source in the world.  Many of us users _trust_-but-verify these folks, who are transparent as can be while still making a living.  Besides, in many open-source projects, with millions of users, who's ___actually___ auditing?

**Comment by TPS** [comment]
@niclasdh Also, there's actually no code in this repo. From https://github.com/AdguardTeam/AdguardForAndroid/blob/master/README.md:
>> Disclaimer: Adguard for Android is not an open-source project. We use GitHub as an open bug tracker for users to see what developers are working on.

**Comment by ameshkov** [comment]
> It's a question of how much effort the "evil guy" will investigate to disable the license check

In fact we aren't really concerned about various "cracked" versions of the app.

What we fear most are copycats. It is really very easy to take an open source code and convert to a "new" competitor app. It'd be hard for us to use GPL as protection, lawyers are pretty expensive nowadays.

So, we've decided to keep paid apps closed source as it's the only viable "protection" at the moment. However, I'd really like to make it open one day.

> So nobody knows what this wonderful Application does in the Background and what it is sending to the mothership.

This is exactly why I am afraid of freeware closed source apps and why we make our free apps open. What for paid apps, the least we can do is providing a privacy policy: https://adguard.com/en/privacy.html#android

Also being paid more or less ensures customers that we don't need any shady monetization, so popular among free products today.

**Comment by TPS** [comment]
> However, I'd really like to make it open one day.

@ameshkov Maybe then you all would like to milestone _this_ issue for version 999, for when you all are fatcat zillionaires lounging all day on individual private islands. 😜

**Comment by TPS** [comment]
No milestone for v.999?! 😜
