### ISSUE TITLE
Start using new filters server instead of AG backend

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#863]
### Metadata

`https://filters.adtidy.org/[platform]/filters.json`
### Translations

`https://filters.adtidy.org/[platform]/filters_i18n.json`
### Filters

`https://filters.adtidy.org/[platform]/filters/[filterId].txt`

For instance:
`https://filters.adtidy.org/[platform]/filters/2.txt`
`https://filters.adtidy.org/[platform]/filters/[filterId]_optimized.txt`

`_optimized` suffix stands for "mobile optimized" filters versions.
We use it by default in case of `iOS` and `Android` apps.
### `[platform]` possible values:
- `windows` - Adguard for Windows
- `mac` - Adguard for Mac
- `android` - Adguard for Android
- `ios` - Adguard for iOS
- `extension/chromium` - Chromium browser extension
- `extension/firefox` - Firefox extension
- `extension/safari` - Safari extension

I suppose we could ignore `Checksum:` field for now as anyway we use https.

**Comment by TPS** [comment]
@gorhill, this is likely relevant to uBlock, as several builtin filterlists are from AdGuard.

**Comment by ameshkov** [comment]
Yep, indeed.

@gorhill it would be better if you switch to this server instead of using `adguard.com`.

Russian filter:
https://filters.adtidy.org/extension/chromium/filters/1.txt

English filter:
https://filters.adtidy.org/extension/chromium/filters/2.txt

Filters updates requests create a huge load, so moving filters to a CDN will help us with unloading the website.

**Comment by gorhill** [comment]
Ok I will change -- but can't just now, because of early design choice years ago -- the key for a list is the URL itself, so there currently no way for me to change the URL without losing a user's selection of the list. Do you plan to redirect the old URLs to the new ones server-side?

**Comment by ameshkov** [comment]
> Do you plan to redirect the old URLs to the new ones server-side?

Oh, didn't think about it until you've mentioned it:)

Yep, we will definitely do it.

**Comment by ameshkov** [comment]
> the key for a list is the URL itself

What are you planning to do with EasyList? They've also changed URLs recently.

**Comment by gorhill** [comment]
I plan/started to locally fix this, to no longer use the URL as a key.

**Comment by TPS** [comment]
> ### `[platform]` possible values:
…
- `extension/firefox` - Firefox ___Safari___ extension

@ameshkov That can't be correct, right? 😜

@gorhill Based on the above, the _current_ Ff version of uBo would need the `extension/firefox` URLs, I think, though after https://github.com/gorhill/uBlock/issues/622 (@ameshkov, I think this discussion is relevant to AG Ff, also) becomes _required_ by a stable Ff version, I think _then_ you'd switch over to `extension/chromium` URLs, though I hope you'd keep up current uBo for those of us on legacy platforms (e.g., Pale Moon). :pray:

**Comment by ameshkov** [comment]
> @ameshkov That can't be correct, right? 😜

Just a typo, thanks for noticing it:)

In fact there's no difference between `extension/firefox` and `extension/chromium`, we've divided it just in case:)

**Comment by ameshkov** [comment]
> @ameshkov, I think this discussion is relevant to AG Ff, also

Just recently tested it. I think we'll wait a bit more until WebExtensions API becomes more reliable.

**Comment by Revertron** [comment]
Done.
