### ISSUE TITLE
Ads are not filtered in News Republic app

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#866]
samsung SM-T813
Ver. 2.8.15
Android 6.0.1 
HTTPS enabled
Tried to reproduce the issue. Everything is ok on my side.
News Republic app(https://play.google.com/store/apps/details?id=com.mobilesrepublic.appy).
Screenshot
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19694322/7ded83ba-9ae7-11e6-8d84-925eb18047b9.png)
</details>
Har file:
[har.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/551128/har.zip)

**Comment by ameshkov** [comment]
So this is outbrain ads.

@Fridrix please ask user to test this rule:
`||outbrain.com^$app=com.mobilesrepublic.appy`
