### ISSUE TITLE
Blocking internet connection in some app on Lenovo A630

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#867]
id 1358890
Android: 4.04. Прошивка официальная
Прошивка модуля связи: A630.V5.2012/12/17 16:15
Номер сборки: Lenovo A630_S008_130111

Не загружаются никакие страницы во встроенном браузере (версия 4.04-eng.).
При попытке загрузить страницу в браузере по какому-либо адресу в окне браузера выводится сообщение следующего типа:
Got the error: Server Error while trying to obtain http://ya.ru/ Connected refused

Других браузеров не установлено. Проблемы на всех версиях Adguard (2.5, 2.6, 2.7, 2.8.15)

При отключении защиты проблемы не наблюдается.
Кроме браузеров, проблема с интернет-соединением наблюдается в приложении Одноклассники. При загрузке приложения в его окне выводится сообщение: Connection
refused. 
В приложении ВКонтакте с доступом к интернету с включённой защитой новой
бета-версии Adguard всё в порядке.

Проблема при постоянной Wi-Fi (мобильную сеть не исп). 
Режима энергосбережения нет. Доступ ко всем сетям для Adguard разрешен. антивирус Dr. Web. Уведомления не отключались. Очистка данных приложения не помогла.

**Comment by ameshkov** [comment]
Стопудово проблема прошивки. Кроме новой прошивки вряд ли что-то поможет.

**Comment by Chme-Alex** [comment]
У меня нет желания осуществлять перепрошивку смартфона, потому как все данные при этом могут быть потеряны. 
При перепрошивке смартфона с ним могут возникнуть проблемы, поэтому я не могу на это пойти.

**Comment by ameshkov** [comment]
@Chme-Alex да я понимаю, просто отвечаю в чем может быть проблема и какие варианты решения.

Если прошивка рутованная, есть еще возможность переключиться на другой режим фильтрации (в расширенных настройках, режим "локальной прокси").

**Comment by Chme-Alex** [comment]
Да, судя по всему прошивка рутированная, потому как зашёл в расширенные настройки и переключил «Режим фильтрации» с «Локального VPN» на «Локальный HTTP прокси». И после этого при включенной защите Adguard с доступом в интернет во всех приложениях, где доступа раньше не было, всё теперь в порядке.
Огромное Вам Спасибо за помощь в разрешении данной проблемы!

**Comment by ameshkov** [comment]
Нет проблем:)
