### ISSUE TITLE
Google assistant always offline on VPN mode - Nougat 7.0 / 7.1

### ISSUE THREAD

**Issue by bharathkeshav12** [AdguardTeam/AdguardForAndroid#868]
**Phone:** Pixel XL / any phone where in you can activate google assistant by the various means available.
**App Version:** 2.8.15-beta

**Steps to recreate:** 

1. Turn on vpn mode, open google assistant. It's always offline.
2. Turn off vpn mode, google assistant is back online.

**Note:**
This issue is not present in HTTP server mode.

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/856

It appears that the issue is caused by mere VPN presence and is not specific to Adguard.
