### ISSUE TITLE
Packet capture/sniffer feature

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#869]
hi, is adguard has a feature of packet capture/sniffer per app? I like
the adguard but is to use other app to see what ads still running, the
app I using is packet capture, i wish add this feature this is very
helpful

1430037

**Comment by ameshkov** [comment]
@evgeniy-ADG please give user a link to the "HAR files capture" instruction. I guess this is what he need.
