### ISSUE TITLE
Certificate issue when using Device with different user than the one that has AdGuard installed.

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#870]
Hello, i am using AdGuard for Android 2.8.15ß on a Samsung Galaxy Tab A (SM-T555) with Android 6.0.1.

When i use my browser (Chrome for example) everything works fine when 'logged in' to the main user.
But as soon as i switch to a different user (that at the moment doesn't ''have'' AdGuard installed i get i certificate error when trying to get beyond the google homepage. Same applies with the "Guest" account.

Maybe you'll want to rethink https://github.com/AdguardTeam/AdguardForAndroid/issues/173#issuecomment-155771540

**Comment by Bluscream** [comment]
Thinks i could try if you want:

- Moving the cert to system storage (https://github.com/AdguardTeam/AdguardForAndroid/issues/798#issuecomment-249851440)
- Installing AdGuard for every user (Which doesn't work for the Guest user OFC)

**Comment by ameshkov** [comment]
Wow, that's a good one:)

So, which user actually "runs" Adguard at that moment?

**Comment by ameshkov** [comment]
@Revertron could you please take a look? do you see an easy way of fixing this?

**Comment by Bluscream** [comment]
> So, which user actually "runs" Adguard at that moment?

The main one. And i'm trying to access the web from a secondary user.

**Comment by ameshkov** [comment]
Huh, so it appears secondary user has a separate certificates storage...

I wonder if we can detect which user runs the browser.

**Comment by UMXs** [comment]
@Bluscream rooted phone /w AG in iptables mode?
try exporting the cert as Dr. Jekyll and installing it as Mr. Hide.

**Comment by Bluscream** [comment]
I no longer have the multi user device, just keeping this open since it's still an open issue for multi-user devices until it's clearly unreproducable or fixed

**Comment by ameshkov** [comment]
It's not a bug, that's for sure. Just a thing to remember about when you're in multi-ser env
