### ISSUE TITLE
Making changes in Apps management section requires protection restart

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#871]
Is it possible to implement changes so that protection will restart automatically?

**Comment by ameshkov** [comment]
It is pretty complicated, planned for v3.0

**Comment by TPS** [comment]
> Is it possible to implement changes so that protection will restart automatically?

Even better, so that restart is no longer _necessary_?

**Comment by ameshkov** [comment]
> Even better, so that restart is no longer necessary?

We should rework it so that it is not necessary anymore.

**Comment by TPS** [comment]
>> @TPS: Even better, so that restart is no longer necessary?
>
> @ameshkov: We should rework it so that it is not necessary anymore

@vozersky This part isn't accomplished.  Is there a separate tracking issue or should this issue be kept open for it?

**Comment by vozersky** [comment]
@TPS yeah, you are right, it's better to keep it open

**Comment by ameshkov** [comment]
It's one in v2.11

**Comment by TPS** [comment]
@ameshkov Are you saying this is done in next ß?

**Comment by ameshkov** [comment]
It is done in the current stable version -- any change causes an automatic protection restart
