### ISSUE TITLE
Not blocking Pop Up & Vibrating ads

### ISSUE THREAD

**Issue by jerryn70** [AdguardTeam/AdguardForAndroid#872]
is there any way to block pop up ads and vibrating ads? 
I mean when i try to download files from some sites (https://uplod.ws ,  https://dailyuploads.net/ ,
https://filescdn.com/ , http://ul.to/ , https://dropapk.com/ , https://userscloud.com/ ) etc
my phone starts vibrating and a pop up will come like saying your phone is in danger or phn got virus scan now/install antivirus or maybe install this app to remove virus from your phone, click here to download games and movies etc like pop up and vibrations

**Comment by ameshkov** [comment]
@jerryn70 yep, i guess it's possible.

One question: do you have HTTPS filtering enabled?

**Comment by ameshkov** [comment]
Also it'd be better to report such issues to this repo next time: https://github.com/AdguardTeam/AdguardFilters

**Comment by jerryn70** [comment]
@ameshkov
No not unabled https, because I'm a user who doesn't like to set password on my phone.

**Comment by ameshkov** [comment]
Then let's hope these websites use third party ad servers and we'll be able to block them.

**Comment by Alex-302** [comment]
@jerryn70 please provide download links. Popups are not shown on the main pages.
You can do it just here:
https://github.com/AdguardTeam/AdguardFilters

**Comment by jerryn70** [comment]
@Alex-302

Check here https://github.com/AdguardTeam/AdguardFilters/issues/3320

**Comment by Alex-302** [comment]
@jerryn70 
thanks. Closed here.
