### ISSUE TITLE
Add "Adguard DNS filter" to the list of available filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#876]
As soon as it is available on our filters server:
https://github.com/AdguardTeam/AdguardDNS/issues/77

**Comment by TPS** [comment]
It's now available (my laptop uBo installation picked it↑ some point yesterday or before, I think), but what precisely is the difference between _this_ filter & `Filter DNS Requests`:ballot_box_with_check:?  Is there an advantage of 1 over the other, or having both enabled?

**Comment by Revertron** [comment]
Done.
@TPS, it would be better to use this filter in addition to our normal filters if you use DNS filtering.
