### ISSUE TITLE
Check if encrypted connection underlying protocol is supported

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#877]
Issue description: https://forum.adguard.com/index.php?threads/azar-android.15433/
Play store link: https://play.google.com/store/apps/details?id=com.azarlive.android
Log: https://dl2.pushbulletusercontent.com/QYf4D4f6477WfYyra8WHBCPPnecOu93c/adguard.log

> 02:52:05.435 [pool-4-thread-7] DEBUG com.adguard.filter.proxy.a - TCP id=100008 Cannot read HTTP request Http base line violates protocol: CONNECT
>02:52:05.435 [pool-4-thread-7] DEBUG com.adguard.filter.proxy.a - TCP id=100008 Closing HTTP connection
>
> AG should have detected that it is not a valid HTTP request

**Comment by ameshkov** [comment]
In the end it appears to be a complicated issue. Reassigned to v3.0.

Meanwhile, @nkartyshov please add `com.azarlive.android` to SSL exceptions.

**Comment by nkartyshov** [comment]
added

**Comment by ameshkov** [comment]
@nkartyshov this issue shouldn't be closed, though:)

**Comment by ameshkov** [comment]
CoreLibs
