### ISSUE TITLE
escape issue in replace modifier

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#878]
Steps to observe the issue: add the following rule
```
||example.com$replace=/^(.|\s)*?\$/\{\[\(\.\\/
```
then go to  #example.com. Then the output is different in different platforms of Adguard. It should be consistent.
Adguard for Windows: `\{\[\(\.\/`
Adguard for Android: `{[(.`

**Comment by ameshkov** [comment]
1. You'd better use `[\s\S]*` instead of `(.|\s)*`, the first one does not work properly.
2. What result do you want to achieve? Seems to be a platform-specific regular expression issue.

Also I suppose it works properly in Android's case, we'd better move it to windows repo.

**Comment by ameshkov** [comment]
Filed a new issue in Windows repo:
https://github.com/AdguardTeam/AdguardForWindows/issues/1358
