### ISSUE TITLE
Google+ app does not work when AG is in proxy+manual mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#879]
User reports:
> I set AG as a proxy, pointed WiFi at the Proxy, and Google+ couldn't load anything new.

**Comment by Revertron** [comment]
Okay, on my device it works both in manual and automatic proxy.
It can be the problem with our proxy, when it tries to connect to only one of IPs again and again, but it is dead. It may depend on location, I think.

**Comment by ameshkov** [comment]
Maybe it is IPv6 issue? It prefers IPv6 instead of IPv4.

**Comment by ameshkov** [comment]
Closing as a duplicate
