### ISSUE TITLE
Virgin Media TV Anywhere app issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#883]
>I'm having trouble using the [Virgin Media TVAnywhere](https://play.google.com/store/apps/details?id=com.virginmedia.tvanywhere&hl=en) app with Adguard enabled. The app will run but continually reconnect then log out. If I turn off Adguard the app logs in and functions correctly. Is this something I can help get whitelisted? It doesn't seem to be affected by any of the filter list.

HTTPS filtering is disabled:
<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "6.0 (sdk=23)",
  "appLanguage" : "en",
  "applicationId" : "94cfc557292dace0",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "LGE LG-H815",
  "deviceSpeedRank" : 61,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 14, 11 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "LOW_PRIORITY",
  "installedPackages" : [ "com.amazon.mShop.android.shopping;version=8.8.0.100;system=false", "com.hy.system.fontserver;version=v4.20.4;system=true", "com.android.LGSetupWizard;version=4.70.0;system=true", "com.lge.videotool;version=4.70.4;system=true", "com.google.android.youtube;version=11.41.56;system=true", "com.lge.sizechangable.weather.platform;version=4.70.7;system=true", "com.android.providers.telephony;version=4.7.19;system=true", "com.google.android.googlequicksearchbox;version=6.8.14.21.arm64;system=true", "com.android.providers.calendar;version=4.4.7;system=true", "com.facebook.mlite;version=1.1;system=false", "com.android.providers.media;version=6.0-162730011d883;system=true", "com.google.android.apps.docs.editors.docs;version=1.6.412.11.46;system=true", "com.qti.service.colorservice;version=1.0;system=true", "com.lge.systemservice;version=6.0-162730011d883;system=true", "com.google.android.onetimeinitializer;version=6.0.1;system=true", "com.shazam.android;version=7.1.0-160923;system=false", "com.hy.app.FontSettings.NotoSans_Regular;version=1.0;system=false", "com.qualcomm.shutdownlistner;version=6.0-162730011d883;system=true", "com.niksoftware.snapseed;version=2.11.0.135454541;system=false", "com.android.wallpapercropper;version=6.0-162730011d883;system=true", "com.thisisglobal.player.xfm;version=4.10.2b;system=false", "com.lge.appbox.client;version=4.70.16;system=true", "com.lge.smartshare.dlna;version=3.7.93;system=true", "com.lge.formmanager;version=4.70.4;system=true", "com.lge.lgdmsclient;version=2.3.3.1;system=true", "com.lge.splitwindow;version=20151106M;system=true", "org.simalliance.openmobileapi.service;version=3.2.1;system=true", "com.google.android.apps.paidtasks;version=20161004;system=false", "com.android.documentsui;version=6.0-162730011d883;system=true", "com.android.externalstorage;version=6.0-162730011d883;system=true", "com.lge.android.atservice;version=6.0-162730011d883;system=true", "com.android.htmlviewer;version=6.0-162730011d883;system=true", "com.whatsapp;version=2.16.310;system=false", "com.lge.app.floating.res;version=2015-10-06;system=true", "com.lge.cloudhub;version=3.30.9;system=true", "com.android.mms.service;version=6.0-162730011d883;system=true", "com.lge.remote.lgairdrive;version=1.2.16;system=true", "com.google.android.apps.docs.editors.sheets;version=1.6.412.09.46;system=true", "com.lge.sui.widget;version=5.2.42;system=true", "com.google.android.apps.docs.editors.slides;version=1.6.412.17.46;system=true", "com.android.providers.downloads;version=5.70.25;system=true", "com.google.android.apps.authenticator2;version=4.74;system=false", "com.lge.camera;version=4.70.33.1;system=true", "com.lge.touchcontrol;version=1.0;system=true", "com.paypal.android.p2pmobile;version=6.6.1;system=false", "com.lge.eltest;version=1.0;system=true", "com.lge.homeselector;version=4.70.8;system=true", "com.lge.springcleaning;version=2.0.3;system=true", "com.qualcomm.qti.telephonyservice;version=6.0-162730011d883;system=true", "com.android.browser;version=5.70.7;system=true", "com.lge.gnsstest;version=6.0-162730011d883;system=true", "com.lge.fmradio;version=4.70.5;system=false", "com.google.android.configupdater;version=6.0.1;system=true", "com.lge.smartshare.provider;version=1.0.19;system=true", "com.android.defcontainer;version=6.0-162730011d883;system=true", "com.lge.matics;version=1.0;system=true", "uk.co.o2.android.myo2;version=7.9.5;system=false", "com.android.providers.downloads.ui;version=5.70.2;system=true", "com.lge.bioitplatform.sdservice.service;version=1.4.05;system=true", "com.android.vending;version=7.0.17.H-all [0];system=true", "com.android.pacprocessor;version=6.0-162730011d883;system=true", "com.qualcomm.cabl;version=1.0;system=true", "com.lge.myplace.engine;version=1.0.8;system=true", "com.lge.shutdownmonitor;version=6.0-162730011d883;system=true", "uk.co.dominos.android;version=2.11.0.184;system=false", "com.android.certinstaller;version=6.0-162730011d883;system=true", "com.android.carrierconfig;version=1.0.0;system=true", "com.google.android.marvin.talkback;version=5.0.4;system=true", "com.lge.launcher2.theme.optimus;version=4.0.552;system=true", "com.qti.qualcomm.datastatusnotification;version=6.0-162730011d883;system=true", "com.android.settingsaccessibility;version=4.70.12;system=true", "android;version=6.0-162730011d883;system=true", "com.android.contacts;version=4.70.49;system=true", "com.lge.smartcover;version=4.70.9;system=true", "com.qualcomm.wfd.service;version=2.0;system=true", "com.lge.smartshare;version=3.8.8;system=true", "com.lge.lockscreensettings;version=4.70.151006;system=true", "com.lge.ia.task.incalagent;version=1.1.8;system=true", "com.lge.sizechangable.favoritecontacts;version=4.70.5;system=true", "com.htsu.hsbcpersonalbanking;version=1.5.15.0;system=false", "com.android.mms;version=4.70.34;system=true", "com.android.nfc;version=6.0-162730011d883;system=true", "com.android.stk;version=2.0;system=true", "com.microsoft.rdc.android;version=8.1.39.158;system=false", "com.android.backupconfirm;version=6.0-162730011d883;system=true", "com.instagram.android;version=9.7.0;system=false", "com.lge.iftttmanager;version=4.70.6;system=true", "com.lge.exchange;version=1.67.23;system=true", "com.lge.wapservice;version=5.70.14;system=true", "com.lge.settings.easy;version=4.50.0;system=true", "com.android.statementservice;version=1.0;system=true", "com.lge.mrg.service;version=4.70.3;system=true", "com.google.android.gm;version=6.10.9.136347105.release;system=true", "com.android.calendar;version=4.70.9;system=true", "com.lge.ia.task.smartsetting;version=4.70.1.4;system=true", "com.lge.smartconfig;version=4.70.3;system=true", "com.privateinternetaccess.android;version=1.3;system=false", "com.microsoft.office.outlook;version=2.1.98;system=false", "com.lge.lgmapui;version=4.70.7;system=true", "com.lge.lgworld;version=5.2.9;system=false", "com.google.android.setupwizard;version=2.0;system=true", "com.qualcomm.qcrilmsgtunnel;version=6.0-162730011d883;system=true", "com.android.providers.settings;version=4.70.00;system=true", "com.lge.doyouknow;version=4.70.2;system=true", "com.android.sharedstoragebackup;version=6.0-162730011d883;system=true", "com.google.android.music;version=6.16.3624-0.I.3421865;system=true", "com.android.printspooler;version=1;system=true", "com.rsupport.rsperm;version=3.0.1.18 (Build 318);system=true", "com.uei.lg.quicksetsdk.irblaster;version=3.0.026;system=true", "com.ti.server;version=1.0.0;system=true", "com.lge.gmstimezone;version=1.0.3;system=true", "com.android.incallui;version=4.70.34.63;system=true", "com.lge.wfds.service.v3;version=3.1.8;system=true", "com.lge.drive.activator;version=1.2.11;system=true", "com.lge.gnsspostest;version=2.0;system=true", "com.android.inputdevices;version=6.0-162730011d883;system=true", "com.lge.gba.android;version=3.3.0;system=true", "com.android.providers.calllogbackup;version=6.0-162730011d883;system=true", "com.lge.eula;version=4.70.2;system=true", "com.lge.gcuv;version=4.70.2;system=true", "com.lge.sync;version=4.70.3;system=true", "com.lge.task;version=4.70.5;system=true", "com.adguard.android;version=2.7.220;system=false", "com.lge.livewallpaper.multiphoto;version=4.70.2;system=true", "com.lge.concierge;version=4.70.8;system=true", "com.qti.xdivert;version=6.0-162730011d883;system=true", "com.google.android.apps.docs;version=2.4.382.19.46;system=true", "com.google.android.apps.maps;version=9.39.2;system=true", "com.google.android.apps.plus;version=9.0.0.136781392;system=true", "com.lge.sizechangable.weather.theme.optimus;version=4.70.7;system=false", "com.lge.qremote;version=4.70.6;system=false", "com.lge.gestureanswering;version=2.0;system=true", "com.google.android.webview;version=54.0.2840.68;system=true", "com.lge.sptab_connectctl_source;version=1.0;system=true", "com.lge.launcher2;version=4.70.29;system=true", "com.lge.musicshare;version=1.0;system=true", "com.google.android.apps.fitness;version=1.59.15-109;system=false", "com.android.server.telecom;version=4.70.34.63;system=true", "com.google.android.syncadapters.contacts;version=6.0.1;system=true", "com.lge.systemupdater;version=2147483647;system=true", "com.android.facelock;version=6.0.1;system=true", "com.android.keychain;version=6.0-162730011d883;system=true", "com.android.chrome;version=51.0.2704.81;system=true", "com.android.gallery3d;version=4.70.21;system=true", "com.google.android.packageinstaller;version=6.0.1;system=true", "com.google.android.gms;version=9.8.77 (440-135396225);system=true", "com.google.android.gsf;version=6.0.1;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.lge.gnss.airtest;version=6.0-162730011d883;system=true", "com.google.android.apps.walletnfcrel;version=1.8.135831409;system=false", "com.lge.wifi.p2p;version=1.0.0;system=true", "com.lge.bluetoothsetting;version=4.70.17;system=true", "com.google.android.partnersetup;version=6.0.1;system=true", "com.lge.pcsyncui;version=4.70.7;system=true", "com.google.android.videos;version=3.19.11;system=true", "com.lge.eodengine;version=4.53.1;system=true", "org.xbmc.kodi;version=16.1;system=false", "com.android.proxyhandler;version=6.0-162730011d883;system=true", "com.lge.updatecenter;version=4.70.16;system=true", "com.google.android.feedback;version=6.0.1;system=true", "com.google.android.apps.photos;version=2.3.0.137536389;system=true", "com.rubenmayayo.reddit;version=1.1.0;system=false", "com.google.android.syncadapters.calendar;version=5.2.3-99827563-release;system=true", "com.android.managedprovisioning;version=6.0-162730011d883;system=true", "com.spotify.music;version=6.5.0.1816;system=false", "com.lge.voicerecorder;version=4.70.8;system=true", "com.lge.smartsharepush;version=4.70.13;system=true", "com.lge.filemanager;version=4.70.7;system=true", "com.android.providers.partnerbookmarks;version=5.70.7;system=true", "com.google.android.gsf.login;version=6.0.1;system=true", "net.darksky.darksky;version=1.1.6;system=false", "com.virginmedia.tvanywhere;version=2.2.5;system=false", "com.android.wallpaper.livepicker;version=4.70.2;system=true", "se.anyro.nfc_reader;version=0.13;system=false", "com.android.apps.tag;version=1.1;system=true", "com.lge.easyhome;version=4.70.3;system=true", "com.lge.hiddenmenu;version=6.0-162730011d883;system=true", "com.lge;version=3.0.0;system=true", "com.lge.wv.hidden;version=6.0-162730011d883;system=true", "com.lge.ia;version=0.8.23;system=true", "com.lge.networksettings;version=4.70.11;system=true", "com.lge.myplace;version=1.3.4;system=true", "com.lge.bnr.launcher;version=1.0.2;system=true", "com.google.android.backuptransport;version=6.0.1;system=true", "com.lge.privacylock;version=4.70.21;system=true", "com.android.settings;version=4.70.54;system=true", "com.lge.lgfota.permission;version=6.0-162730011d883;system=true", "com.lge.lgaccount;version=3.8.09;system=true", "com.lge.sizechangable.weather;version=4.70.7;system=false", "com.quicinc.wbcserviceapp;version=1.0;system=true", "com.android.calculator2;version=4.70.5;system=true", "com.google.android.apps.books;version=3.10.27;system=true", "com.qualcomm.location;version=1.0;system=true", "com.lge.NfcSettings;version=4.70.28;system=true", "com.google.android.wearable.app;version=1.5.0.3329214.gms;system=false", "com.google.android.apps.chromecast.app;version=1.19.26;system=false", "com.qualcomm.qti.tetherservice;version=1.0;system=true", "com.lge.eulaprovider;version=4.70.1;system=true", "com.lge.bnr;version=5.38.13;system=true", "com.lge.ime;version=6.4.11;system=true", "com.lge.lpd;version=4.50.42;system=true", "com.lge.mlt;version=4.70.7;system=true", "com.lge.wernicke;version=2.3.1;system=true", "com.android.vpndialogs;version=6.0-162730011d883;system=true", "com.lge.videoplayer;version=4.70.11;system=true", "com.lge.lgdrm.permission;version=6.0-162730011d883;system=true", "com.lge.wifisettings;version=4.70.12;system=true", "com.google.android.keep;version=3.3.431.0;system=false", "com.google.android.talk;version=13.0.134811930;system=true", "com.lge.ime.theme.black;version=3.0.16;system=true", "com.android.phone;version=4.70.34.63;system=true", "com.android.shell;version=6.0-162730011d883;system=true", "com.lge.drmservice;version=6.0-162730011d883;system=true", "com.lge.sizechangable.musicwidget.widget;version=4.70.7;system=true", "com.lge.lgsetupwizard.eula;version=4.50.37;system=true", "com.android.providers.userdictionary;version=6.0-162730011d883;system=true", "com.lge.lteconfig;version=1.41223;system=true", "com.lge.ime.dictionary.xt9;version=9.9.7;system=true", "com.lge.cic.eden.service;version=4.70.16;system=true", "com.lge.gnsslogcat;version=1.0;system=true", "com.android.location.fused;version=6.0-162730011d883;system=true", "com.android.systemui;version=4.70.151006;system=true", "com.lge.provider.systemui;version=6.0-162730011d883;system=true", "com.lge.ia.task.s4urecommender;version=4.22.20;system=true", "com.android.bluetoothmidiservice;version=6.0-162730011d883;system=true", "com.lge.provider.lockscreensettings;version=6.0-162730011d883;system=true", "com.lge.clock;version=4.70.5;system=true", "com.lge.email;version=6.67.23;system=true", "com.lge.leccp;version=1.1.3;system=true", "com.lge.music;version=4.70.9.1;system=true", "es.tid.gconnect;version=2.51.0.107;system=false", "com.ebay.mobile;version=5.5.1.17;system=false", "com.lge.ia.task.informant;version=4.22.28;system=true", "com.google.android.play.games;version=3.7.24 (3051774-040);system=true", "com.lge.hiddenpersomenu;version=6.0-162730011d883;system=true", "com.lge.lginstallservies;version=4.70.9;system=true", "com.google.android.apps.magazines;version=3.5.3;system=true", "com.android.bluetooth;version=6.0-162730011d883;system=true", "com.qualcomm.timeservice;version=6.0-162730011d883;system=true", "com.qualcomm.atfwd;version=6.0-162730011d883;system=true", "com.android.providers.contacts;version=4.70.49;system=true", "com.lge.snappage;version=4.70.2;system=true", "com.lge.servicemenu;version=6.0-162730011d883;system=true", "com.android.captiveportallogin;version=6.0-162730011d883;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.10.84-g88c20fd",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : null,
  "statisticsInfo" : "Blocked threats:0; Blocked banners:8916; Traffic saved:230450176;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.7.220",
  "whitelist" : [ ]
}
</details>

Please see logs here: 1257627

**Comment by ameshkov** [comment]
@evgeniy-ADG we'll check what's wrong with it, thank you!

Does it help to disable ad blocking for that app specifically?

**Comment by nkartyshov** [comment]
I added in ad blocking exclusion, but I did not know how check this app.

**Comment by ameshkov** [comment]
> I added in ad blocking exclusion, but I did not know how check this app.

Wait for user answer before doing anything.

@evgeniy-ADG any update on this?

**Comment by nkartyshov** [comment]
User say that app perfectly works in last beta.
