### ISSUE TITLE
com.plexapp.android doesnt work when adguard is on

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#884]
1442904
https://play.google.com/store/apps/details?id=com.plexapp.android&hl=en
 the app doesnt see any player in local network
Adg off - http://prntscr.com/d2i400
on - http://prntscr.com/d2i4c1
disabling HTTPS doesn't help
2.7.220

**Comment by nkartyshov** [comment]
Waiting a log file from user

**Comment by vgavrish** [comment]
Лог приложения при открытии Plex с 08:23 до 08:24
[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/583840/debug.1.txt)

**Comment by nkartyshov** [comment]
Проблема решилась включение опции pref.vpn.ipv4.force.complex в настройках низкого уровня
