### ISSUE TITLE
No 4G connection after WiFi is disabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#886]
Mobile network is 'on' while WiFi is enabled; when WiFi gets disabled, we do not receive the information about the active network change:

`07:33:23.651 [main] INFO  c.a.a.r.NetworkStateReceiver - Start NetworkStateReceiver on action android.net.wifi.WIFI_STATE_CHANGED
07:33:23.661 [main] INFO  c.a.android.filtering.filter.e - handleWiFiChanged: oldState = 3, newState = 0`

We should restart the protection to reestablish DNS servers. 

Support ID 1442121

**Comment by ameshkov** [comment]
@Revertron disagree, we should only refresh VPN settings if connected network type has changed.

**Comment by Revertron** [comment]
But the WI-FI's state was changed from WIFI_STATE_ENABLED to WIFI_STATE_DISABLING, and then we can not connect to routers 192.168.0.1:53 to redirect DNS requests. That is the problem.

**Comment by ameshkov** [comment]
So we don't need to restart VPN, we should just fix `refreshDnsServers` servers (it reacts on connectivity change only)

**Comment by Revertron** [comment]
Done.
