### ISSUE TITLE
System apps are not listed in Apps management section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#888]
The thing is that some of these system apps (like Google Backup transport or CaptivePortalLogin) do use network despite not having necessary permissions.

We should re-think the criteria for listing apps there.

**Comment by Revertron** [comment]
Google Backup Transport requests these permissions:
android.permission.MODIFY_NETWORK_ACCOUNTING,
android.permission.READ_SYNC_SETTINGS,
android.permission.WRITE_SETTINGS,
android.permission.ACCESS_NETWORK_STATE,
android.permission.GET_ACCOUNTS,
android.permission.BACKUP,
com.google.android.providers.gsf.permission.READ_GSERVICES,
android.permission.USE_CREDENTIALS

Captive Portal Login requests these:
android.permission.INTERNET, - as you can see, it must be listed in our list
android.permission.ACCESS_NETWORK_STATE

But I recommend widening of permissions check to these permissions:
android.permission.INTERNET,
android.permission.ACCESS_NETWORK_STATE,
android.permission.CHANGE_NETWORK_STATE,
android.permission.CHANGE_WIFI_STATE.
Methinks it will be sufficient for this.

**Comment by ameshkov** [comment]
> android.permission.INTERNET, - as you can see, it must be listed in our list

Not in my case, though

**Comment by Revertron** [comment]
Done, needs test on 6.0+

**Comment by ameshkov** [comment]
It seems that the issue is resolved now
