### ISSUE TITLE
com.android.captiveportallogin traffics are not shown to VPN

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#892]
Related forum thread: https://forum.adguard.com/index.php?threads/block-ads-in-wifi-sign-in-screen.13464/
HTTP request log with local HTTP proxy mode: https://dl2.pushbulletusercontent.com/uBfcq95fxB6WGR9Zw8feAeHZfCz0uQD0/adguard.log
Also, even with local http proxy mode element hiding rules were not applied to wifi sign-in screen.

**Comment by ameshkov** [comment]
@seanl-adg still I'd like to get the "record everything" level log with proxy+manual.

In order to understand why element hiding rules weren't applied.

**Comment by ameshkov** [comment]
Here is how the login page looks like:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Redirecting...</title>
	<meta charset="utf-8">
	<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
	<meta name="msapplication-config" content="none"/>
</head>
<body>
<form method="post" action="https://auth.spcnetworks.kr/login?res=notyet&uamip=10.1.0.1&uamport=3990&challenge=9dd2fab431defc4d8f3f03ff66b6b3d8&called=14-CC-20-99-7D-CA&mac=00-AE-FA-E2-4D-3C&ip=10.1.0.116&nasid=14CC20997DCA&sessionid=5821818700000002&userurl=http%3a%2f%2fus.sb.adtidy.org%2fsafebrowsing-lookup-hash.html%3fprefixes%3d66FCC01F%2fD5FCAA2A%2f&md=23F0909A3C79580449D40B137D5E7FA2">
<input type="hidden" name="signed_request" value="B3IaBaS9OKFHrkVKf3ooplpbVJ3y84JQ9e01kF5xwj6NcEVUzIRVLqbJQ_nf8Lvof3Bg5tgFFvG1XqMYoM0EHiYWFzqlX2_tdXMQkureXOyMhKt0VApS7Zq-yM1sIuhQFPbeEWn-AZBAUVbV8fhUSUmnuTS6zZKenQxMvgiMCQ7xf1vYXn6R95h5p5VlWlFspjm5RPLTjZalnsmdhRsnBogBB_RvgzIFakrisCAH8HAFrY1jeeNj3n2PdI-RJkg5BbhzFRdK1_KQHmlwMmx4TaSJOCrnuNlRG_x2TVYBDqOG58WIuXLURjKHSajdtrTtrJ0UBv32aNSCDk9kJYVnq7yHzYpqETQKvgf8Hr9LkaVIvNCuX3eCCn_XSFr1DiKH6nsMGNuLioV6LKy-z8SHMeTS2hkOxeNVAqUiG6wT0M-yLgLdo9HfQoCY-KzxQtNcbkIKNg7OKRXZUWy_9EVhHiCVC7J8gGWQU61wR4fRxO7NDtRwlYS8t0YJl6obMoux">
<noscript>JavaScript-enabled web browser required.<br>
please <input type="submit" value="Click here"> to continue.</noscript>
</form>
</body>
<script type="text/javascript">
	window.onload = function() {
		f=document.forms[0];
		if (f.signed_request.value != "" && f.signed_request.value != "\{signed_request\}") f.submit();
		else window.location.href = "http://www.spc.co.kr";
	};
</script>
</html>
```

That page above submits form immediately to the `POST https://auth.spcnetworks.kr/login` page. 

Here is what happens else:
1. AG receives `CONNECT injections.adguard.com`
2. It tries to establish an encrypted connection with `injections.adguard.com` (it does it once for the very first attempt, all consequent connections to injections domain stay local, that's the downside of current TLS filtering implementation).
3. It fails to do it as you are not yet authorised.

**So, here is what we should do:**
Change `SslMitmManager`, supply constant `SslEndPointProperties` instance for `injections.adguard.com` domain. In this case we won't need to establish that first connection.
