### ISSUE TITLE
Chrome Canary - all ads go through

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#893]
I am using google chrome "canary" channel
https://play.google.com/store/apps/details?id=com.chrome.canary

And all websites I visit have all the regular ads (screenshots attached). Whether they Are inline ads or screen takeover ads.(I was getting those before, but didn't experience any this morning to screenshot)

![image](https://cloud.githubusercontent.com/assets/15856304/20036483/35c0747e-a412-11e6-8471-93643b580e23.png)

I do have data saver off in chrome canary settings. Just in case that was bypassing Adguard in some way. Adguard works just like it is supposed to in regular chrome . When I switch back and forth between the two versions simultaneously. Canary has ads and regular chrome is ad Free.

Google must be doing something behind the scenes with chrome canary.

I've also attached a screenshot of my notification pulldown. You'll see Adguard running

Websites I screenshot for you. PhoneArena.com washable.com my post.com

**Comment by ameshkov** [comment]
Weird, we'll check it.

**Comment by ameshkov** [comment]
Chrome Canary was not in the "browsers list". Added it there now.
