### ISSUE TITLE
kde.kdeconnect_tp not correct work when Adguard is ON

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#894]
1442904
https://play.google.com/store/apps/details?id=org.kde.kdeconnect_tp&hl=en
Нет доступа к файловой системе телефона из компьютера если Adguard включен.

Ошибка на скриншоте в обозревателе Dolphin стрелочка на красном поле. Т. е.
корневую директорию он видит (Android и Фотографии камеры), а внутрь этих
директорий зайти не может.
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20055887/11935f50-a4ec-11e6-89d9-ae1d227194e6.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20055893/17a0ebd8-a4ec-11e6-985b-b41ce9912c58.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20055900/1cedafc2-a4ec-11e6-9a5f-e5400bbdd09f.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20055910/272ff954-a4ec-11e6-80a2-e63617a4405c.png)

</details>

Последовательность такова при включенном Adguard.

1. Скачиваем из Google Play программу KDE Connect
2. Запускаем и синхронизируем с любым дистрибутивом Linux имеющего в своем
составе окружение KDE 5 и выше
3. Заходим в обозреватель файлов Dolphin и слева выбираем подключенное
устройство (у меня LeEco на скриншоте)
4. Видим в корне 2 директории (зависит от устройства)
5. Пытаемся зайти в любую. Ошибка (как на скриншоте)

При выключенном Adguard войти в данные директории позволяет, а также
проводить файловые операции. Остальные функции KDE Connect работают без
ошибок при включенном Adguard

**Comment by nkartyshov** [comment]
Ошибка связана с входящими UDP соединениями. Adguard не может отправить такое соединение дальше. 

Решение только одно, отключить Adguard при работе с приложением.
