### ISSUE TITLE
Divider between 'Autoupdate filters' and 'Filters autoupdate period' is displaced on some devices

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#896]
https://forum.adguard.com/index.php?threads/14778/#post-110695

Screenshot:
http://i83.fastpic.ru/big/2016/1104/09/a9792f8968e5b5eb86021d5915434a09.png

**Comment by ameshkov** [comment]
@nkartyshov it appears you've messed it up

**Comment by ameshkov** [comment]
@nkartyshov also you should print "Current: value" there, just like we do for other comboboxes.

**Comment by ameshkov** [comment]
It is named "Autoupdate filter period" instead of "Autoupdate filters period"

**Comment by vbagirov** [comment]
@nkartyshov @ameshkov it should had been named 'Filters autoupdate period' in first place to be grammatically correct, I fixed the OneSky translation for this phrase (#27199047).

**Comment by nkartyshov** [comment]
fixed
