### ISSUE TITLE
Battery drain in version 2.0.62

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#9]
Linked forum thread:
http://forum.xda-developers.com/android/apps-games/adguard-ad-blocker-doesnt-require-root-t2958895/post62479867#post62479867

Can't reproduce it on our devices though.

At least we should do some CPU profiling, maybe we've missed something?

**Comment by Revertron** [comment]
The profiling shows really nothing. Profiled in two modes - idle on the table and under heavy page loads in a browser. There is nothing to be afraid of.

**Comment by ameshkov** [comment]
Have you profiled it on mobile phone or tablet? People who complaints mostly use phones.

**Comment by Revertron** [comment]
On my phone - Sony Xperia Z1 Compact.

**Comment by Revertron** [comment]
Closing this as there is no evidence for it.
