### ISSUE TITLE
It is possible to make Adguard in Proxy mode restart protection on network reconnect just like the VPN

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#90]
Steps to reproduce:
1. Start in VPN mode
2. Switch filtering mode to proxy
3. That's it

networkReceiverEnabled is set to true, so Adguard will try restarting protection.

**Comment by TPS** [comment]
AFAIK, this already happens for me… or is this in a specific circumstance?

**Comment by Revertron** [comment]
I've made NetworkStateReceiver to start ProxyService if it is not started, but no restarting or stopping will be done.

**Comment by ameshkov** [comment]
Hm, so that was intentional? Ok, got it.
