### ISSUE TITLE
FlymeOS 5.1.11.0G breaks Adguard functionality

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#901]
After the new Flyme update, Adguard disables network connection.

version: 2.7.220
device: Meizu M3s

Judging from logs there is no OperaMax.

Waiting for full app logs.

**Comment by ameshkov** [comment]
Known issue, no need in logs.

The problem is Meizu traffic control. They restrict network access for Adguard after just a minute being in background.

I'll come up with a temporary solution today.

We also need to report this issue to Flyme OS devs as this behaviour is definitely not normal for Android.

**Comment by ameshkov** [comment]
Reported bug to Flyme:
http://forum.flymeos.com/thread-10861-1-1.html

**Comment by ameshkov** [comment]
### Temporary solution

Temporary solution is to use Adguard as a DNS-level ad blocker.
Here is what should be done to do it.

This is not yet available in Adguard's stable version. Use this build:
[adguard_2.8.49.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/583474/adguard_2.8.49.apk.zip) 

1. Open Adguard
2. Go to Settings -> Advanced -> Low-level settings
3. Find and check `pref.vpn.ipv4.bypass` and `pref.vpn.ipv6.bypass`
4. Go to Settings -> Advanced
5. Enable "Filter DNS requests"
6. Go to Settings -> Ad Blocker
7. Find and enable "Adguard DNS" filter
8. Return to Meizu homescreen
9. Run "Security" app
10. Open "Power", then tap "Standby management"
11. Find Adguard and check it there (it will place it to a whitelist).

**Comment by ameshkov** [comment]
### Temporary solution (Russian description)

Временное решение - использовать Adguard как DNS-фильтр. В таком режиме он будет несколько ограничен в возможностях, но хотя бы будет блокировать рекламу.

Итак, вот что нужно сделать.

Не все необходимые функции доступны в стабильной версии Adguard. Используйте этот билд (пока версия 2.8 не стала стабильной):
[adguard_2.8.49.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/583474/adguard_2.8.49.apk.zip) 

1. Откройте Adguard
2. Откройте Настройки -> Расширенные -> Низкоуровневые настройки
3. Найдите и включите `pref.vpn.ipv4.bypass` и `pref.vpn.ipv6.bypass`
4. Откройте Настройки -> Расширенные
5. Включите "Фильтровать DNS запросы"
6. Откройте Настройки -> Антибаннер
7. Найдите и включите фильтр "Adguard DNS"
8. Вернитесь к главному экрану Meizu
9. Запустите приложение "Безопасность"
10. Откройте "Управление питанием", затем "Управление спящим режимом"
11. Найдите Adguard и включите его там (это поместит его в список исключений).

**Comment by ameshkov** [comment]
Fixed
