### ISSUE TITLE
Samsung Galaxy S7 with Nougat compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#903]
Here is a problem reported by user:
https://forum.adguard.com/index.php?threads/samsung-s7-edge-nougat.16077/

@gshumihin please test it.

**Comment by ameshkov** [comment]
Ticket ID:
1449319

**Comment by ameshkov** [comment]
It appears that samsung now uses SIP protocol (for some unknown reason):
```
UDP connect to /2001:4888:3:7120:c0:104:0:6e:5060. Process info: system /2600:1005:8016:dc49:0:22:e193:c201:5060 /:::0 1000
```

**Comment by ameshkov** [comment]
```
UDP connect to /2001:4430:5:405::23:5071. Process info: system /:::6201 /:::0 1000
```

**Comment by ameshkov** [comment]
Quote from xda:

> I've checked one more log from a guy reporting similar issue with S7 and Nougat.

> Here is a quick analysis:
> 1. Samsung appears to be using SIP for some unknown reason.
> 2. SIP is broken by the mere VPN presence, you should run into this issue with any other VPN app. > So I guess this issue should be reported to Samsung as well.
> 3. Here are some things you can try:
> 3.1. Try disabling Adguard for "Android OS"
> 3.2. If it does not work, try blocking IPv6 in AG low-level settings (pref.vpn.ipv6.disable).
> 3.3. The last thing to try is to bypass IPv6 (uncheck pref.vpn.ipv6.disable, check pref.vpn.ipv6.bypass)

**Comment by gshumihin** [comment]
And no issues for me :(

**Comment by evgeniy-ADG** [comment]
Logs: 1449319

**Comment by ameshkov** [comment]
@evgeniy-ADG temporary fix: `pref.vpn.ipv6.bypass`.

Please ask users what are their mobile carriers.

**Comment by vozersky** [comment]
Samsung firmware issue. Gone.
