### ISSUE TITLE
AdUps SpyWare

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#908]
@AdGuardTeam I'm not sure whether this belongs here or https://github.com/AdguardTeam/AdguardFilters/issues (sorry, @Alex-302, if so), but this (currently) seems to be focused specifically on Android:

[KryptoWire](http://www.kryptowire.com/adups_security_analysis.html) (via [AndroidPolice](http://www.androidpolice.com/2016/11/15/security-firm-reportedly-finds-spyware-on-chinese-android-phones-including-blu-devices-sold-in-the-us/)) reports that the AdUps malware ([like CarrierIQ [which I hope you folks _already_ block] on steroids](http://www.kryptowire.com/adups_security_analysis_figure1.png)) ___system___ packages:
````
com.adups.fota.sysoper
com.adups.fota
````
are pure spyware, reporting & receiving to servers:
````
bigdata.adups.com
bigdata.adsunflower.com
bigdata.adfuture.cn
bigdata.advmob.cn
221.228.214.101
rebootv5.adsunflower.com
61.160.47.15
````
Can all these be blocked in whichever list(s) & in whatever manner?

I guess this is related to #888, #857, & ~~#249~~→#2094.

**Comment by ameshkov** [comment]
It appears these domains are blocked by mobile ads filter for quite some time

**Comment by TPS** [comment]
These servers should be in `Spyware` & perhaps `DNS` filters, too, no?

Also, I was hoping that the AG firewall would block the __packages__
directly, if detected.
-- 

https://zhjf9h10ji3.ting.com/

**Comment by ameshkov** [comment]
> These servers should be in Spyware & perhaps DNS filters, too, no?

It is in DNS already, compiled along with mobile ads filter.

Mobile ads filter actually is "stronger" than the spyware filter. Some people may be ok with analytics requests, but they never disable mobile ads filter on their own.

**Comment by TPS** [comment]
How about default complete-blocking these packages?  Is that feasible?

**Comment by ameshkov** [comment]
> How about default complete-blocking these packages? Is that feasible?

Actually it is:
`|http*$app=com.adups.fota.sysoper|com.adups.fota`

@seanl-adg let's add it to mobile ads filter.

**Comment by TPS** [comment]
OIC, I was expecting something to be visible in the Firewall UI showing that. Does this accomplish that, or can I request that, also?

**Comment by ameshkov** [comment]
> OIC, I was expecting something to be visible in the Firewall UI showing that. Does this accomplish that, or can I request that, also?

Nope, you won't be able to see it in UI. The only difference is that you'll see that all requests from these apps are blocked in apps mgmt section

**Comment by Alex-302** [comment]
```
|http*$app=com.adups.fota.sysoper|com.adups.fota
```
removed, because of an issue with current release version.

**Comment by TPS** [comment]
Then this should be Re<kbd>Open</kbd>ed, yes?  What happened?  What about my idea of just blocking it completely via firewall/"App Management"?

**Comment by Alex-302** [comment]
We will add it again when AG for Adnroid 2.8 will be released.

**Comment by TPS** [comment]
> We will add it again when AG for Adnroid 2.8 will be released.

@Alex-302 Just to follow-up, this was re-introduced w/ [v2.8](https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.8.76) on Dec 8, 2016?

**Comment by Alex-302** [comment]
Remind me, please, tomorrow. We had some issue with this rule and it was removed. I am waiting for confirmationd from user.

**Comment by TPS** [comment]
Here's your reminder, @Alex-302, as requested. ☺

**Comment by Alex-302** [comment]
An issue is still exists(but not for all users)
https://github.com/AdguardTeam/AdguardForAndroid/issues/1030

**Comment by Alex-302** [comment]
@TPS Added:)

**Comment by ameshkov** [comment]
@Alex-302 this rule is still too dangerous. We should wait unless more users are updated to v2.8.

**Comment by Alex-302** [comment]
Well, ok..

**Comment by TPS** [comment]
@ameshkov @Alex-302 For cases like this, do you all serve different versions of the subscription lists based on the requesting AG client (addon, app, whatever) version?  If not, it might a good way to ß-test different subscription updates.…  Just an idea. 🤔💭

**Comment by ameshkov** [comment]
We do serve different lists to different clients, but we don't yet do it for different versions.

**Comment by TPS** [comment]
While this is rolling out, would adding `*$important,app=com.adups.fota.sysoper|com.adups.fota` _guarantee_ blocking traffic that AG knows about through these apps? Or is it just `$important,app=com.adups.fota.sysoper|com.adups.fota` (w/o the `*`)?

**Comment by ameshkov** [comment]
`*` does not matter, both rules will block *everything* from these apps

**Comment by TPS** [comment]
> this rule is still too dangerous. We should wait unless more users are updated to v2.8.

@ameshkov Ok to enable now?

**Comment by ameshkov** [comment]
Nope:(

**Comment by TPS** [comment]
Wow!  😱  Is there someplace 1 can access those stats, like http://www.ie6death.com/ for IE6?

**Comment by ameshkov** [comment]
I am judging by the number of requests for filters updates coming to the old server.

**Comment by TPS** [comment]
I hate to ask, @ameshkov, but time _now_⁉️  Or waiting for v3, perhaps?

This is now going on ~2 years! 😶

**Comment by TPS** [comment]
Is it possibly time to implement now?  Else, it'll be closed via @StaleBot.…

**Comment by ameshkov** [comment]
I've just checked how many requests are to the old filters update API there (which is used by the old AG for Android versions), there are still approximately ~50-100k users on the old versions:( 

I guess the only way is to stop serving filters updates to the old apps. Once we do it, we'll be finally able to do package-level blocking.

**Comment by TPS** [comment]
Are y'all sure that's all AG instances? I suspect a lot of other adblock software which include AG (non-CDN⁈) lists by default (due to your fantastic licensing 🙇🏾‍♂️) & don't have a _reason_ to update.

Anyway, enough's enough‼️  Isn't it time (so many _years!_) to cut that off?  Make some general announcements (_especially_ include non-AG platforms, e.g., Filterlist hub), & then shut 'em down!

&, then, finally, could we get all these improvements merged⁈

**Comment by ameshkov** [comment]
> Are y'all sure that's all AG instances? I suspect a lot of other adblock software which include AG (non-CDN⁈) lists by default (due to your fantastic licensing 🙇🏾‍♂️) & don't have a reason to update.

I am 100% sure, unfortunately :(

Old AdGuard versions weren't using a CDN (like the new ones) and were requesting filters updates from our API server. That's why I can estimate their count, they still create some server load :)

As I've said, we're going to stop serving newer filter lists to them, and this will help with the issue.

**Comment by ameshkov** [comment]
Done
