### ISSUE TITLE
We should flush DnsCache on protection start

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#91]
Look at HttpRemoteEndPoint class, DNS cache is used there as a static variable.
It can cause lots of issues when user is in Manual proxy mode as cache is never flushed.

**Comment by Revertron** [comment]
Done.

**Comment by ameshkov** [comment]
UPD: we should also clear it on network reconnect.

**Comment by Revertron** [comment]
Done.
