### ISSUE TITLE
Configurable Toast/Notification for Automatic Filters Updates

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#910]
Replicating https://github.com/AdguardTeam/AdguardForAndroid/issues/746#issuecomment-260023836 & https://github.com/AdguardTeam/AdguardForAndroid/issues/746#issuecomment-260818947:
> When automatic check is done after period elapses, is there a toast (like for manual check) showing result, or is this completely silent?  I'd prefer a toast @ least anytime an update succeeds, & maybe even when there _isn't_ any change.

>  *I*'d like … to request an option for a toast on every _successful_ update.

**Comment by ameshkov** [comment]
Let's get back to this discussion.

Actually, I find a toast to be pretty annoying. What if we make Adguard's notification more "rich" and print the last update time there?

**Comment by TPS** [comment]
>Actually, I find a toast to be pretty annoying.

Hence, configurable, but defaulted how it is now…
>What if we make Adguard's notification more "rich" and print the last update time there?

… with that addition, it'd be _extra_ useful, but I'd still like the "every update" toast optionally. ☺

**Comment by ameshkov** [comment]
What I fear about toasts is that it shows up above any app you use, hence, people won't understand that this is Adguard's toast. So, it might be confusing people.

Configurable status notifications maybe? Like what Kaspersky and Avast do?

**Comment by TPS** [comment]
> Configurable status notifications maybe (not ongoing, but new notifications on such an event)?

*That*'s not bad (though I've no idea what those AV do — never used them):  Something like that AG update icon (AG shield w/ ♻️ in corner) appearing-&-then-automatically-disappearing from notification bar would be great!

Though simply putting that AG-colored toast as "AdGuard: No filterlists need updating now", "AdGuard: 5 filterlists updating", "AdGuard: Won't update filterlists on mobile data", "AdGuard: Can't update filterlists offline", &c, would give me all the same warm fuzzy feelings, too. ☺

**Comment by vozersky** [comment]
merged into #3378
