### ISSUE TITLE
Select all option for apps 

### ISSUE THREAD

**Issue by bharathkeshav12** [AdguardTeam/AdguardForAndroid#911]
By default, all apps' data are routed via adguard. If I wish to make adguard only work for chrome, that means i'll have to disable routing data via adguard for the remaining apps on the phone. This can sometimes become a tiring process, given that there could be a lot of apps. can there be a feature to select all --> enable / disable?

**Comment by TPS** [comment]
In this use case, why don't you just untick `Settings → General → Block ads in all apps`, which will then block only in browsers (as described) & then just deselect whichever browsers you _don't_ want filtered?  I'd think a global de/select-all for the firewall would be inherently dangerous.…

**Comment by bharathkeshav12** [comment]
@TPS - I'm sorry about not being very specific. I'm talking about the part where it says `route traffic through adguard` under `settings -->  app deatails`

**Comment by ameshkov** [comment]
Makes sense.

We'll implement it in v3.0 through the context menu in apps management seciton.

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/1063
