### ISSUE TITLE
Samsung Theme store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#916]
The old issue appeared again: https://github.com/AdguardTeam/AdguardForAndroid/issues/571
http://forum.xda-developers.com/showpost.php?p=69658140&postcount=1852

Add Samsung Theme store to the default https exclusions
https://github.com/AdguardTeam/AdguardForAndroid/issues/571

**Comment by nkartyshov** [comment]
Added, but the problem not reproduced on Samsung S7.

**Comment by ameshkov** [comment]
@nkartyshov is it done?

**Comment by nkartyshov** [comment]
yes
