### ISSUE TITLE
Autostart doesn't work

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#924]
id 1450410

adg 2.8.53

[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/611311/state.txt)
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/611315/debug.txt)

Не работает автостарт программы.
"Когда включаю телефон и если успеваю нажать 2 раза на уведомление программы (адг фильтрует все соединения) то показывает что программа работает, а жму как всегда на стрелочку "выхода" на панели телефона и уведомление пропадает и через меню в неё захожу,а она уже не работает. Не успел нажать ни чего не увижу. "
В программе автостарт стоит, оптимизаторы, таск-киллеры не установлены, в стамине он в исключении

**Comment by s-knysh** [comment]
User: "После того как отключил автоматический перезапуск в низкоуровневых настройках всегда загружается, правда вроде с небольшой задержкой. После последнего обновления попробовал снять галку - не запускается, буду пока так"

**Comment by ameshkov** [comment]
Вот такая строчка сигнализирует, что нас "вытесняет" другое VPN-based приложение:
```
21:24:09.264 [Binder_1] INFO  c.a.android.vpn.AdguardVpnService - Start revoking VPN service
```

**Comment by vgavrish** [comment]
говорит "почему тогда на 2.7.220 запускается без проблем?"

>  У менядругого нет приложения с VPN-СЕРВЕРОМ. Ближайшее это OPERA где сжатие всегда выключено и ESET NOD32 Mobile Security с выключенным антифишингом. 
![image](https://cloud.githubusercontent.com/assets/18548949/20665043/a1d59a94-b566-11e6-86e5-9b31897053c2.png)

**Comment by ameshkov** [comment]
А нет ли какого-нибудь предустановленного "сжимателя" трафика в самой прошивке?

В общем лог недвусмысленно указывает на причину - проблема совместимости.

**Comment by vgavrish** [comment]
можно ли как-то исправить "проблему совместимости"?
попросила если что еще один лог

**Comment by vgavrish** [comment]
> Прошивка официальная, ничего нет. Сейчас кстати намного реже стал вылетать, а когда ставлю записывать всё - так вообще не могу поймать этот момент. В настройках у себя отключил - отключить функционал автоматического перезапуска.

**Comment by ameshkov** [comment]
А до версии 2.8.76 уже обновился пользователь?

Вообще чтобы разобраться полностью нам нужно системный LOGCAT-лог запрашивать. По нему будет видно, какое именно приложение вырубает нам VPN.

**Comment by vgavrish** [comment]
да, обновился
попросила logcat

**Comment by vgavrish** [comment]
@ameshkov 
[logcat (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/659342/logcat.1.txt)
Раза наверное с 3-4 вышло всё же что не загрузился, лог приложил, время загрузки 21.55 В этот раз (иногда так бывает) при тапе по экрану и чуток тянешь в верх, видны уведомления и Adguard
там был как бы запущен, дёргаю шторку вверх, ввожу графический ключ и всё..он уже пропал.. Через меню в программе тоже отключен.

**Comment by zebrum** [comment]
id 1064543
Sony Z5 compact
android 6.0
adguard 2.8.76
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/660712/debug.txt)

**Comment by ameshkov** [comment]
Stamina mode?

**Comment by zebrum** [comment]
@ameshkov 
касперский удалили, стамину проверили - добавили.

**Comment by ameshkov** [comment]
> logcat (1).txt

Судя по этому логу о включении девайса андроид нас оповестил сильно позже, чем на самом деле включился:
```
12-17 21:56:52.863  5098  5098 I com.adguard.android.receivers.BootUpReceiver: [main] Receiver got an action android.intent.action.BOOT_COMPLETED
```

**Comment by vgavrish** [comment]
> Судя по этому логу о включении девайса андроид нас оповестил сильно позже, чем на самом деле включился
получается проблема в прошивке?

**Comment by ameshkov** [comment]
> получается проблема в прошивке?

Предполагаю что да, ей просто негде еще быть

**Comment by ameshkov** [comment]
При этом, возможно, проблема комплексная. Например возникает из-за того, что мы зарегистрированы на несколько системных событий, например на сетевые.

Мне интересно, а что если нас поставить в автостарт с помощью tasker?
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/58/0/nstrojjk-tasker-dlja-rboty-s-adguard-dlja-android

**Comment by vgavrish** [comment]
сейчас отпишу

**Comment by vgavrish** [comment]
>  я чего вот вспомнил. Когда настраивал интернет года три назад. У меня через компьютер выдает на модем. уже и Айпад 4 постоянно терял связь. Я в модеме в этой настройки поменял на только через Соединенные Штаты Америки. это может влиять?
Но опять же предыдущая стабильная версия работала хорошо.

за автостарт он не захотел делать, решил быть с включенной опцией pref.pvn.disable.pause

**Comment by vgavrish** [comment]
@ameshkov "за текст выше" может это быть причиной?

**Comment by ameshkov** [comment]
@vgavrish не могу сказать, нужно методом тыка проверять

**Comment by vgavrish** [comment]
@ameshkov пробовали запустить Tasker, но не поняли где именно настройки вводить
может версия изменилась и не совсем понятно
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21742129/f81f5d8c-d4f0-11e6-8b2e-de363356c64b.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21742133/01873fc0-d4f1-11e6-9e2a-16e210b816ff.png)

**Comment by vozersky** [comment]
obsolete
