### ISSUE TITLE
Via app issue

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#925]
https://play.google.com/store/apps/details?id=via.rider

App hangs on the splash screen when Adguard is enabled. 

@gshumihin was able to reproduce (please attach the log in the comments)

Original thread:
https://forum.adguard.com/index.php?threads/via-app-not-working-with-adguard-enabled.16541/#post-114287

**Comment by gshumihin** [comment]
Here's log:
https://www.dropbox.com/s/etwh6kv9i5twkow/adguard.log

**Comment by vozersky** [comment]
[http log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/616447/http.log.txt)
[full log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/616448/full.log.txt)

look like it's not about https filtering 
also, if you run the app at least once without Adguard, it (probably gets the settings from domain) works fine afterwards

**Comment by Alex-302** [comment]
added to mobile filter
```
@@||config2.mparticle.com^$app=via.rider
```
