### ISSUE TITLE
[Feature request] Multiple choice in Apps Management

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#928]
"Could you add an "unchecked all" and "check all" feature for the apps and statistics screen. It takes a long time to go through and manually uncheck all apps I don't want going through adguard"

id1298794

Thanks.

**Comment by ameshkov** [comment]
We will definitely do it in v3.0

**Comment by TPS** [comment]
#911?

**Comment by ameshkov** [comment]
@TPS yeah, we'll conduct issues review after v2.9 release.

**Comment by ameshkov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardForAndroid/issues/1063
