### ISSUE TITLE
KakaoTalk compatibility issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#929]
https://forum.adguard.com/index.php?threads/https-issue-with-kakaotalk.14658/

@seanl-adg we need your help in fixing this issue. First of all, we need the debug-level AG log of the issue.

**Comment by seanl-adg** [comment]
Here is it: https://dl2.pushbulletusercontent.com/VAWerjTRoPK49DBmsIAGFfw4OgtJ5lIK/adguard.log

I took steps 1~5 indicated in the original forum thread.

**Comment by ameshkov** [comment]
Important records from the log:

```
01:26:01.631 [pool-3-thread-496] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=101371 Server alert received. Level: fatal, Description: certificate_unknown certificate_unknown(46)
01:26:01.632 [pool-3-thread-496] INFO  com.adguard.filter.proxy.ssl.k - TCP id=101371 Adding endpoint com.kakao.talk_110.76.141.80_443_clog-aggregator.kakao.com to exceptions due to class java.io.IOException: Internal TLS error, this could be an attack
```

`certificate_unknown` indicates that app uses SSL pinning.

**Comment by ameshkov** [comment]
Same issue here:
```
01:26:10.266 [pool-3-thread-497] DEBUG com.adguard.filter.proxy.ssl.q - TCP id=101377 Server alert received. Level: fatal, Description: certificate_unknown certificate_unknown(46)
01:26:10.266 [pool-3-thread-497] INFO  com.adguard.filter.proxy.ssl.k - TCP id=101377 Adding endpoint com.kakao.talk_113.29.186.39_443_pf-api.kakao.com to exceptions due to class java.io.IOException: Internal TLS error, this could be an attack
```

**Comment by ameshkov** [comment]
@seanl-adg please check if it's enough to add the following domain names to the ssl exclusions list:
```
clog-aggregator.kakao.com
api.kakao.com
```

**Comment by seanl-adg** [comment]
I've added above two domains to pref.https.domains.whitelist, but the problem wasn't resolved. [Here](https://dl2.pushbulletusercontent.com/dQ3BS3pbv8zCqoZAJYEPB1Y0GvoWZ0Wn/adguard.log) is a full log while reproducing steps 1-5 with above two domains in pref.https.domains.whitelist.

**Comment by nkartyshov** [comment]
Added

**Comment by ameshkov** [comment]
@seanl-adg what's the final list?

It that it?
```
clog-aggregator.kakao.com
api.kakao.com
ac-talk.kakao.com
channel.kakao.com
pf-api.kakao.com
```

**Comment by seanl-adg** [comment]
On my end, adding only 3 domains
```
ac-talk.kakao.com
channel.kakao.com
pf-api.kakao.com
```
fixes all annoyance that I experience in the app, is it desirable to add all domains that cause the error you've indicated?

**Comment by ameshkov** [comment]
> is it desirable to add all domains that cause the error you've indicated?

I suppose it'd be better to add all 5 as the app checks ssl certificate for them anyway.
@nkartyshov

**Comment by nkartyshov** [comment]
added
