### ISSUE TITLE
Activate same subscription lengths on both website & Amazon versions, & keep track of all licenses on AdGuard.Com

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#93]
@ameshkov 

> [Do you really think it's important to users to have an annual subscription?](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-148347055)

For parity with [website](https://m.adguard.com/en/purchase.html) & Amazon versions, _each_ should include both monthly & yearly licenses (same pricing!), &, if 1 purchases from Amazon, the license should reflect in 1's AdGuard.Com account.  This will forestall complaints, as well as expand # of options for customers, which in turn should equate to increased sales. ☺

Also, you actually promise access to the yearly subscription in the Amazon description:

> Pricing and Availability:
> Adguard for Android is available on Adguard official website. Basic program scope is free; the additional functions are available after activation of the application with a Mobile license (which can be purchased on adguard.com as well). Cost: $9.95 for a year.

You all are more likely to have yearly subscribers if offered alongside the monthly directly.

**Comment by ameshkov** [comment]
> each should include both monthly & yearly licenses (same pricing!)

But that's impossible. Amazon's subscription is different from the license keys as it covers all your devices.

> Also, you actually promise access to the yearly subscription in the Amazon description:

Ops, this is mistake, we'll fix this.

**Comment by ameshkov** [comment]
> if 1 purchases from Amazon, the license should reflect in 1's AdGuard.Com account

This is a good idea, but we have no access to buyer's email address.

I was thinking about a bit different way. In future we want to implement Adguard settings synchronization through Adguard account (including user filter and whitelist sync).

So, to use this sync feature you'll have to authorize the app. Thus we'll be able to link your subscription to the Adguard account.

**Comment by TPS** [comment]
Hmm, I also just realized you offer a lifetime per device license, too.  Amazon has no way of signifying such a license for apps?!  It certainly does so for books, & precisely limits to a particular # of devices per purchase.  Is it possible to rework the Amazon licenses to be exactly same as what the AG website has?  Or are all those the options you're given?

The sync method should be perfect to get the Amazon license into the website account.

**Comment by ameshkov** [comment]
It would be really hard to make the license system the same for Amazon and for the website. The problem here is that the license keys system is shared with desktop versions of Adguard and there's no such possibility for Amazon.

In these conditions having two absolutely different licensing systems looks better than trying to somehow combine them. Anyways that's not possible.

> Amazon has no way of signifying such a license for apps?!

Not for subscriptions. We may simply make the app paid, but in this case users won't have a trial period.

**Comment by TPS** [comment]
@ameshkov 
> Not for subscriptions. We may simply make the app paid, but in this case users won't have a trial period.

Now, _this_ is an intriguing possibility.  Many apps do have (& are allowed by Amazon rules, apparently) multiple versions based on, e.g., paid ad-free, free ad-supported, __*&*__ Underground.  I know it's a further headache, but having, _in addition_, a full-paid version would answer my "lifetime equivalent single payment" for a personal site license idea (although $45 as I mentioned above _does_ seem steep, on a general basis — maybe $44.99 is better? :stuck_out_tongue_winking_eye:).  & leaving an existing version as is, maybe with an additional tweaked yearly option, would solve the trial-version issue.

Re: the desktop license, I'm not even hoping Amazon can sync _all_ AdGuard website licenses. Just (& only just) the opposite, that the AdGuard account website knows all licenses that the user purchased anyplace.

**Comment by ameshkov** [comment]
> I know it's a further headache

You're right there:)

For now I'd like to wait and see how many users use Amazon Appstore. I mean of course we can do it, but I'd like to sure that it is worth doing:)

**Comment by TPS** [comment]
Of course, let's give it some time & see how many bite. ☺

**Comment by TPS** [comment]
> For now I'd like to wait and see how many users use Amazon Appstore. I mean of course we can do it, but I'd like to sure that it is worth doing :)

@ameshkov If you can believe it, it's been ~1 year since you've been offering Amazon AG licences.  Without divulging anything privileged, how's it working out?  I get the feeling [v3.0](https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v3.0) will land about that anniversary time, & I'm quite curious if the Amazon launch was worth the effort to y'all. ☺

**Comment by ameshkov** [comment]
@TPS actually there are not many Amazon users. However, I suppose it was worth it anyway, it's the return of investments took some time:)

**Comment by TPS** [comment]
I*M*HO, Amazon is deprecating paid & subscription apps in favor of [Underground](https://github.com/AdguardTeam/AdguardForAndroid/issues/17#issuecomment-146405212), which seems to be some kind of ad-supported version (ironically).  Is there a _possibility_ of such, together with the current version, or it that too hypocritical? :stuck_out_tongue_winking_eye:

**Comment by ameshkov** [comment]
> Is there a possibility of such, together with the current version, or it that too hypocritical? 😜

Nah, that's definitely not our way:)

**Comment by TPS** [comment]
DOA due to #1893. :sob:
