### ISSUE TITLE
Still randomly appearing SSLPinned error

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#930]
![screenshot_20161126-221854](https://cloud.githubusercontent.com/assets/3318223/20643983/4a2e5514-b427-11e6-83a9-5e752d5ec877.png)

Can't you just modify the headers so they don't include the pinned part?

- https://github.com/ac-pm/SSLUnpinning_Cydia
- https://github.com/ac-pm/SSLUnpinning_Xposed
- https://github.com/iSECPartners/Android-SSL-TrustKiller

**Comment by ameshkov** [comment]
We do it in case if certificate is moved to the system storage.
Did you do it?

**Comment by Bluscream** [comment]
Where can i check tha?. I thought that issue was fixed already it just appeared randomly today. What can i do about it? Neither Xposed nor Caydia works on this device so can i do it with just root permissions?

**Comment by ameshkov** [comment]
> I thought that issue was fixed already it just appeared randomly today.

`Public-Key-Pins` is the header you should look for.

To check if it operates properly open github.com in some newly installed browser and check response headers with `chrome://inspect`.

**Comment by Bluscream** [comment]
![screenshot_20161128-002341](https://cloud.githubusercontent.com/assets/3318223/20652804/fd8d6c60-b500-11e6-86b5-46d6464830bb.png)

**Comment by ameshkov** [comment]
@Bluscream 
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by Bluscream** [comment]
Had no issues with SSL pinning after that.
