### ISSUE TITLE
dcinside missed ad

### ISSUE THREAD

**Issue by odudnyk** [AdguardTeam/AdguardForAndroid#931]
Missed AD in app.

Link at PlayMarket
https://play.google.com/store/apps/details?id=com.dcinside.app&hl=en

<details/>
https://pp.vk.me/c638926/v638926269/dff4/RQYuy6ldmiE.jpg
<details>

**Comment by ameshkov** [comment]
Thank you!

It'd be better to report missed ads to AdguardFilters repo:
https://github.com/AdguardTeam/AdguardFilters/issues/3570

**Comment by seanl-adg** [comment]
@odudnyk Hi, what Adguard version and filter lists are you using? Are you subscribed to List-KR filter?
