### ISSUE TITLE
Ads in Application. GO Keyboard

### ISSUE THREAD

**Issue by s-knysh** [AdguardTeam/AdguardForAndroid#932]
![screenshot_2016-11-27-18-23-24](https://cloud.githubusercontent.com/assets/23573693/20647273/e693ccec-b498-11e6-8406-8ade42d86d7e.png)

У пользователя включена Https фильтрация.
 "enabledFilterIds" : [ 2, 3, 4, 1, 11 ]
У нас повторилась проблема.

**Comment by ameshkov** [comment]
@s-knysh это нужно репортить в AdguardFilters:
https://github.com/AdguardTeam/AdguardFilters/issues/3571
