### ISSUE TITLE
Missed ads in Nekto.me app

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardForAndroid#933]
The issue appears every time when the conversation is over. 

![screenshot_20161127-082727](https://cloud.githubusercontent.com/assets/17504743/20650542/bb8ac92e-b4d9-11e6-8301-c639a83dd8ae.png)

App version: 2.8.58

Filters: 
English
Spyware
Social media
Annoyances
Russian
Experimental
Mobile Ads

Reproduced the issue.

Customer ID: 1455313

**Comment by ameshkov** [comment]
Please report this type of issues to AdguardFilters repo:
https://github.com/AdguardTeam/AdguardFilters/issues/3572

**Comment by Alex-302** [comment]
@Tetiana2020 please ask for HTTP log. Don't forget to clear app's cache.

**Comment by Tetiana2020** [comment]
@Alex-302 , Logs in ticket 1455313

**Comment by Alex-302** [comment]
All requests are blocked.

**Comment by ameshkov** [comment]
@Alex-302 so you can't reproduce this issue on your side? Or is blocking requests is not enough to remove that placeholder?

**Comment by Alex-302** [comment]
I don't know, because can't reproduce this issue and don't see ads without AG..
