### ISSUE TITLE
PocketCasts compatibility issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#935]
https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts&hl=en

> PocketCasts cannot connect to server to stream when Adguard is on

http://forum.xda-developers.com/showpost.php?p=69822544&postcount=1891

**Comment by nkartyshov** [comment]
@vozersky Please, test it. I cannot reproduce.

**Comment by vozersky** [comment]
Was not able to reproduce. Could be a specific filtering rule problem?

**Comment by nkartyshov** [comment]
No, it isn't filters. 
@ameshkov Can close this task?
