### ISSUE TITLE
Adguard prevents FTP access from LAN

### ISSUE THREAD

**Issue by sviperz** [AdguardTeam/AdguardForAndroid#936]
Adguard version: **2.8.58** (wasn't an issue on the previous versions, not sure which ones exactly)
Smartphone: **Nexus 6P, Android 7.1.1 DP2**
FTP access software: any, for example **FX File Explorer**, **Solid Explorer**

When enabled, Adguard prevents FTP access from LAN (FTP server on Keenetic Ultra II). Nothing I can disable or use separately in the app addresses the issue (firewall, whitelist, filtering method, different low level settings), only switching off Adguard completely resolves the issue.

Please fix.

**Comment by ameshkov** [comment]
Does it help to turn on "pref.vpn.ipv4.force.complex"?

**Comment by Bluscream** [comment]
For me it doesnt block sftp and it doesnt completely block ftp, i can connect but it doesnt show me any files or folders
My Setup:
<details>
Samsung Galaxy Tab 9.3 (SM-T555)

Android 6.0.1 Build: MMB29M (Stock Touchwiz ROM)

Rooted with superSU

AdGuard BETA 2.8.58

Google Chrome 56.0.2919.3 (Official Build) dev (32-Bit)
</details>

**Comment by sviperz** [comment]
@Bluscream yes, the same for me as well. Somehow apps report that FTP is available, but whenever I'm trying to connect nothing happens except spinning circle representing connection process (though the system log of the router reports successful connection).

@ameshkov will be able to check later today.

**Comment by Bluscream** [comment]
I was using the SFTP and FTP plugins for total commander btw

**Comment by sviperz** [comment]
> Does it help to turn on pref.vpn.ipv4.force.complex in Adguard's low level settings?
No, it doesn't help. I've tried every checkbox in low level settings, nothing helps.

**Comment by ameshkov** [comment]
What's FTP server IP address?

**Comment by sviperz** [comment]
It can be _my.keenetic.net_ (in LAN) or any of router's IP, for example _192.168.1.1_. It has no defference, it doesn't work in both cases.

**Comment by ameshkov** [comment]
@sviperz do you use VPN mode or proxy mode?

I may need to take a look at the full log, could you please collect it for me?

**Comment by sviperz** [comment]
I use VPN mode. The issue doesn't show itself in proxy mode, but it isn't a good solution anyway.

Are there any ways to get the full log without creating a bug report within the app? I know how to collect it, but it requires sending a bug report from the app which disconnect that bug report from this issue thread.

**Comment by ameshkov** [comment]
It appears that the whole routes exclusion is messed up in the stable version. We're preparing to publish a hotfix.

Could you please try the newer build?

Here it is:
https://github.com/AdguardTeam/AdguardForAndroid/issues/939#issuecomment-265127509

**Comment by sviperz** [comment]
OK, good to hear there is a possible fix. Will try and report back later today. Thanks!

**Comment by sviperz** [comment]
> Could you please try the newer build?

v2.8.71 doesn't address the issue, unfortunately.

@Bluscream could you please check new test version as well? ^^

**Comment by ameshkov** [comment]
@sviperz could you collect the logs then?

> Are there any ways to get the full log without creating a bug report within the app? 

There's a list of possible log locations in the end of the article:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android

**Comment by sviperz** [comment]
Here is the log from _record everything_ mode.
[adguard.log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/634833/adguard.log.zip)

**Comment by ameshkov** [comment]
It seems that FTP server is not in LAN in your case.

I see an FTP connection to `78.47.125.180` in the log

**Comment by ameshkov** [comment]
You can exclude it from VPN routes.

Go to settings -> advanced -> low level
Edit `pref.vpn.ipv4.routes.excluded`
Add `78.47.125.0/24` there

**Comment by sviperz** [comment]
Seems like it works. Thanks for solution. Is it a thing I have to setup as a workaround or it will be added to future versions by default?

**Comment by ameshkov** [comment]
> Seems like it works. Thanks for solution. Is it a thing I have to setup as a workaround or it will be added to future versions by default?

Yep, you should set it up manually. This is just too specific to be added to the default routes exclusions.
