### ISSUE TITLE
Can't copy\paste into "settings" -> "userfilter" -> "import" field

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#937]
on Xperia Z1 with Android 5

" При выделении текста кнопки копировать, вставить и.тд скрыты оверлеем и не нажимаются например когда выделяешь в поле импорта своего фильтра"

Вот как это выглядит:
<details>

![img_0003](https://cloud.githubusercontent.com/assets/17472907/20664968/aeaad5c4-b56e-11e6-82af-0a6bdc035d6a.JPG)

**Comment by vozersky** [comment]
@Alex-302  since you are able to reproduce it please cooperate with this one, if possible

**Comment by Alex-302** [comment]
Ok.

**Comment by ameshkov** [comment]
Guys? Do we still have this issue?

**Comment by Alex-302** [comment]
No. It is displayed in the foreground now.
