### ISSUE TITLE
WiFi calling doesn't work

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#939]
id 1309176

Android 7 
Adg - beta

WiFi calling is no longer working with Adguard enabled running the new Android 7 update for the Sprint LG G5
I've tried the suggested turning on
pref.VPN.bypass.ipv6 and that didn't help.

tried the pref.VPN.ipv4.routes.excluded adding the 68.31.26.2/24 with no change
still not working. turned WiFi Calling on at 11:15am no connect. tried again at 11:17am

logs:
[Архив 2.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/616190/2.zip)

**Comment by ameshkov** [comment]
@vozersky 
There was a mistake in routes exclusion string:

```
11:09:36.982 [Thread-4] INFO  c.a.android.vpn.AdguardVpnService - Excluding // Reserved subnets
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
172.16.0.0/12
192.0.0.0/24
192.168.0.0/16
224.0.0.0/4
240.0.0.0/4
255.255.255.255/32


// T-Mobile wi-fi calling (#233)
208.54.0.0/16

// AT&T wi-fi calling
129.192.166.0/24

// UK EE wi-fi calling (#582)
109.249.0.0/16

68.31.26.2/24 ranges from VPN routes
```

This string shouldn't be there: "ranges from VPN routes" 
Also it would be better to enter `68.31.0.0/24` just in case.

**Comment by ameshkov** [comment]
I'll add sprint gateway ip to the default routes exclusion in v2.8 so after release it should be enough to simply reset low-level settings.

**Comment by vozersky** [comment]
@zebrum please inform our user

**Comment by Bohdan-SUP** [comment]
> WiFi Calling is still broken on latest build on Sprint using Android 7. tried at 9:26am and again at 9:27. Will not connect. It's fine with adguard turned off.
Log - [debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/627611/debug.txt)

Other user reports that mere any VPN affect this - 1219568

**Comment by evgeniy-ADG** [comment]
> Checked a few other VPN apps, Seems it's broken at the Android level now
> maybe? As it failed with them also.

1309176

**Comment by ameshkov** [comment]
This is pretty much ok to be broken with other VPN apps.
However, it is not ok to be broken with our app as we handle this it by excluding wifi calling routes.

**Comment by ameshkov** [comment]
@Bohdan-SUP in reply to 1309176: after updating to v2.8 he must reset low-level settings in order for the problem to be fixed. I can see it in the log, that he didn't do it yet.

**Comment by ameshkov** [comment]
@Bohdan-SUP in reply to 1219568: we really need to get new log from him.

**Comment by Bohdan-SUP** [comment]
Informed both, I'll update later.

**Comment by Bohdan-SUP** [comment]
**1309176**: "reset low level settings, rebooted phone and restarted service just to be sure. can see your entry for the exclusion up the Sprint WiFi Calling IP in the excludes list. however WiFi Calling is still not working with Adguard is active. first try 12:13, 2nd 12:15pm"

[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/631988/debug.txt)

And here is the log from **1219568** - 
[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/631990/debug.1.txt)

**Comment by ameshkov** [comment]
Weird, it looks as if routes exclusion didn't actually work.

**Comment by ameshkov** [comment]
Ok, found a bug.

**Comment by ameshkov** [comment]
@Bohdan-SUP same issue, it appears we need to push a hotfix for this specific issue.

**Comment by Bohdan-SUP** [comment]
Glad to hear you found a reason :)

**Comment by ameshkov** [comment]
@Bohdan-SUP please ask both guys to test this new build:
[adguard_2.8.71.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/633685/adguard_2.8.71.apk.zip)

If it is ok, this build will be soon pushed to release (as the problem appears to be serious).

**Comment by Bohdan-SUP** [comment]
Emailed both.

**Comment by Yana-SUP** [comment]
**1309176** 
"Very happy to report it is now working!!!
Great work guys! And much thanks!"

**Comment by ameshkov** [comment]
Great, thanks for checking it! We can finally close this issue then.

Update is available through beta channel.
Tomorrow we'll make it available through release channel as well.

**Comment by gpioneer** [comment]
Is pref.vpn.ipv4.bypass taken out after this update? I am now missing this option (want to try DNS-level filtering and this one is missing.)

**Comment by ameshkov** [comment]
That's super weird, but you're right, it is missing.

**Comment by TPS** [comment]
I think I'd a related problem to this issue until installing this ß: my system wifi notification would always say "no internet" though I got online just fine with everything besides Hangouts wifi calling.  Did anyone else see that?

**Comment by ameshkov** [comment]
@gpioneer new build is available: https://adguard.com/apkb

**Comment by gpioneer** [comment]
It's back :)

**Comment by gpioneer** [comment]
It's back :)

**Comment by evgeniy-ADG** [comment]
>2.8.71 version also have a same problem.

1208287

**Comment by ameshkov** [comment]
@evgeniy-ADG I need to get AG log and cellular provider name & region.

It'd be better if you open a new ticket instead of reopening this one.

**Comment by evgeniy-ADG** [comment]
ok
