### ISSUE TITLE
When I change low-level integer setting it is not changed on the screen

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#94]

**Comment by Revertron** [comment]
Done.

**Comment by ameshkov** [comment]
There is a bug now.

Steps to reproduce:
1. Tap on pref.vpn.tun.mtu
2. Tap "Cancel"
3. Value will change to -1

**Comment by Revertron** [comment]
Yes, there was a small bug. Fixed.
