### ISSUE TITLE
eu.battle.net - site is broken by Adguard injection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#940]
URL: http://eu.battle.net/en/
Screenstot
<details>

![photo40300305659835614](https://cloud.githubusercontent.com/assets/23258533/20660549/e984c086-b552-11e6-858e-613835e2b447.jpg)
</details>
Line 10 content:

`<script type="text/javascript" src="//injections.adguard.com/adguard/injections/content-script.js?ts=1480342747733&domain=eu.battle.net&css=1&js=1&generic=1"></script>`

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/3575

**Comment by ameshkov** [comment]
To fix this we should use `&amp;` instead of `&`

**Comment by nkartyshov** [comment]
fixed

**Comment by ameshkov** [comment]
@nkartyshov review?
