### ISSUE TITLE
Microsoft Solitaire Collection: can't sync when adguard is active

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#942]
Disabling https filtering for MS solitaire helps.

"Full log of connection error in Microsoft solitaire collection,
connection attempt starts at 21:16, and returns an error at 21:17"

[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/617089/debug.1.txt)

[state (13).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/617218/state.13.txt)

user ID: 1140536

**Comment by nkartyshov** [comment]
added in http exclusion
