### ISSUE TITLE
mega.nz not working

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#949]
I don't know if this is a filter related bug or not. I encountered the same thing on my PC when Adguard way enabled but i thought it was because of one of my userescripts there.

![screenshot_20161130-000703](https://cloud.githubusercontent.com/assets/3318223/20732944/625133ac-b691-11e6-9959-140d67677f4f.png)

Example URL: https://mega.nz/#!c4AByLRY!ntrKDNP6UGumGj6Ic8coTBPjuMYIKfmDA

<details>http://valid.x86.fr/a/4ylsyy

Samsung Galaxy Tab 9.3 (SM-T555)

Android 6.0.1 Build: MMB29M (Stock Touchwiz ROM)

Rooted with superSU

AdGuard BETA 2.8.58

Google Chrome 56.0.2919.3 (Official Build) dev (32-Bit)
</details>

**Comment by ameshkov** [comment]
There was a similar issue in Windows version, caused by the fact that we were loosing the very last byte while filtering: https://github.com/AdguardTeam/AdguardForWindows/issues/744

I wonder if it is the same issue

**Comment by ameshkov** [comment]
@vozersky I need you to test this issue.

**Comment by vozersky** [comment]
Can't rep. 

Mega.nz links doesn't work in mobile browser at all, but if you request a desktop version it downloads and saves just fine. (tried Adguard Adguard 2.8.76 and 2.8.83)

@Bluscream  Can you still reproduce such issue? 

<details>

![photo_2017-02-21_17-38-09](https://cloud.githubusercontent.com/assets/17472907/23169412/b96dd304-f85c-11e6-9c7d-810375d7bc97.jpg)

![photo_2017-02-21_17-38-06](https://cloud.githubusercontent.com/assets/17472907/23169415/bd180754-f85c-11e6-93a5-0c974eadb4e5.jpg)
</details>
