### ISSUE TITLE
Firewall notification when Internet is turned off when browser try to open page(pref.vpn.disable.pause is enabled)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#95]

**Comment by ameshkov** [comment]
But pref.vpn.disable.pause has nothing to do with this?

**Comment by Alex-302** [comment]
![screenshot_2015-10-16-16-01-50](https://cloud.githubusercontent.com/assets/8361299/10542236/75649f7a-741f-11e5-9ea9-402c557b3978.png)

**Comment by Alex-302** [comment]
![155165](https://cloud.githubusercontent.com/assets/8361299/10542248/9821c2ea-741f-11e5-9c9c-0948389acede.png)
