### ISSUE TITLE
New Adguard update false positive on Avast!

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#950]
![tmp_19217-screenshot_20161130-103124-1297785073](https://cloud.githubusercontent.com/assets/3318223/20746974/7be4cac0-b6e8-11e6-83df-74f0ecaf714e.png)

**Comment by ameshkov** [comment]
@vbagirov please report it to Avast

**Comment by Bluscream** [comment]
It's that stupid reputation system invented by antivir devs

**Comment by vbagirov** [comment]
Reported the false positive, waiting for their reply.

**Comment by ameshkov** [comment]
@vbagirov you should report it again for the new build

**Comment by Bluscream** [comment]
No issues so far :)
