### ISSUE TITLE
Can't attach files to github issues with Chrome Dev

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#951]
![tmp_19217-screenshot_20161130-1041141322562901](https://cloud.githubusercontent.com/assets/3318223/20747210/943d29b8-b6e9-11e6-904a-c8710005c496.png)

Works fine when disabling the Adguard VPN

**Comment by ameshkov** [comment]
@vozersky I need you to test this issue.

**Comment by vozersky** [comment]
can't reproduce with standard filters
what file exactly were you trying to upload? .zip?
