### ISSUE TITLE
Error connection in chrome 

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#952]
id 1105802

Alcatel One Touch POP 3
adguard 2.8.58

постоянно на разных сайтах где используется https в браузере возникает ошибка "соединение прервано" Похоже, вы подключились к другой сети, через 2-5 сек сайт открывается

Включение pref.vpn.disable.pause не помогло
оптимизации батареи нет

`<details>
![screenshot_2016-11-29-21-59-21](https://cloud.githubusercontent.com/assets/23637588/20751479/070471fe-b70d-11e6-8c7e-7f621ddfd507.png)
![screenshot_2016-11-29-21-59-10](https://cloud.githubusercontent.com/assets/23637588/20751472/f6b491f8-b70c-11e6-828e-57db1359147a.png)
</details>`

свежие логи: 
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/621705/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/621706/state.txt)

время: 21:59

в firefox проблемы нет

**Comment by ameshkov** [comment]
Насколько я понимаю, проблема воспроизвелась при переходе вот по такой ссылке:
https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fdl.maxthon.com%2Fmx5%2Fmx5.0.1.3000.exe

Стабильно ли эта ситуация воспроизводится, если по этой ссылке попробовать перейти еще несколько раз?

По логу ничего подозрительного не видно, происходит нормальная загрузка страниц.

**Comment by vgavrish** [comment]
@ameshkov 

> Ссылки могут быть разными, главное что бы было https, могут открываться без ошибки могут с ошибками, ошибки возникают через раз, и это не только у меня у знакомого такая же проблема на asus, так же установлен adguard.

**Comment by vgavrish** [comment]
новые логи 
[debug (4).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/639203/debug.4.txt)
ошибки за 8.12 в 12:16, 12:19, 12:33

+ Первая ошибка что "соединение прервано" появилась 08.12.2016 в 12:16 (мск).
 Открыл приложение gmail, открыл ваше письмо и открыл ссылку https://github.com/
AdguardTeam/AdguardForAndroid/issues/952 появилась ошибка.
+ Если ссылку вставлять сразу в браузер то повторить ошибку не смог.
+ Повторил открытие ссылки https://github.com/
AdguardTeam/AdguardForAndroid/issues/952 как и первый раз через приложение
gmail (почта), и в браузере google chrome снова ошибка "соединение прервано" (время возникновения 08.12.2016 в 12:19 мск). 
+ Решил еще по тестировать открыл https://forum.adguard.com/index.php все открылось без
проблем, перешел в раздел https://forum.adguard.com/index.php?categories/adguard-%D0%B4%D0%BB%D1%8F-android.32/
, далее https://forum.adguard.com/index.php?forums/%D0%9E%D0%B1%D1%89%D0%B8%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-adguard-%D0%B4%D0%BB%D1%8F-android.34/
+ все данные ссылки открылись нормально, но как только я решил открыть раздел
"жрёт аккумулятор" по ссылке https://forum.adguard.com/index.php?threads/%D0%96%D1%80%D0%B5%D1%82-%D0%B0%D0%BA%D0%BA%D1%83%D0%BC%D1%83%D0%BB%D1%8F%D1%82%D0%BE%D1%80.7835/ вышло сразу что "соединение прервано" (время возникновения 08.12.2016 в
12:33 мск). 
+ Как и раньше я указывал какой то закономерности нет, то все открывает то выходят ошибки и только в браузерах на основе chrome, так же до этого было и в yandex браузере. Проблем нет в браузерах mozilla и в стандартном браузере android.

**Comment by zebrum** [comment]
@ameshkov please take a look

**Comment by ameshkov** [comment]
Хром постоянно пытается открыть `http://check.googlezip.net/connect`, это сигнализирует о том, что в нем включено "сжатие".

Так ли это?

**Comment by vgavrish** [comment]
Все тоже самое, экономия трафика отключена,ошибка как была так и осталась, отключение экономии трафика не помогает в решении проблемы.
Протестировал ещё с браузером opera проблем с открытием страниц нет все работает, получается проблема в браузерах google chrome и yandex

**Comment by zebrum** [comment]
@ameshkov any news?

**Comment by ameshkov** [comment]
@zebrum не, раз сжатие данных выключено, тогда я не понимаю, что может быть причиной такого поведения.
