### ISSUE TITLE
'Filters autoupdate period' greying out bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#956]
Steps to reproduce:

1. Disable filters autoupdate (period selection item greys out)
2. Tap 'back'
3. Go to Settings again
4. Now check for updates period selection item is active and will grey out when you enable filters autoupdate

Original thread:
https://forum.adguard.com/index.php?threads/16814/#post-115600

**Comment by nkartyshov** [comment]
fixed
