### ISSUE TITLE
Meta-RFC/E: Regularly use Accessibility Auditor/Scanner before releases

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#957]
@AdGuardTeam https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor is Google's tool to help developers enhance their apps for accessibility problems.  Given the trouble that was had in such situations ( #151/#203, #519, #695, &c), maybe this'd be a helpful tool for y'all?

**Comment by ameshkov** [comment]
Nice tool! We should use it while testing v3.0 ( @vozersky plz take a look)

**Comment by vozersky** [comment]
Oh, we should put it into use, I will check it, thanks!

**Comment by TPS** [comment]
@ameshkov @vozersky You're welcome!  🤓 Just FYI, I do find the tool a bit cumbersome (1 has to go through each & every screen manually, I think, & definitely have to recheck everytime the GUI is fiddled with), but the suggestions I saw were quite reasonable, I believe.  Maybe you want to recruit some of the folks who worked with the above-mentioned issues to help double-check your work on this?

**Comment by ameshkov** [comment]
Added to the release checklsit

**Comment by TPS** [comment]
Here's [Kontrast (A Color Contrast Checker)](https://f-droid.org/packages/org.kde.kontrast/), another such a11y tool.

**Comment by Versty** [comment]
> Here's [Kontrast (A Color Contrast Checker)](https://f-droid.org/packages/org.kde.kontrast/), another such a11y (but FOSS!) tool.

The link leads to a 404 error page. Could you please provide the correct one?

**Comment by TPS** [comment]
Sorry, @Versty, I've updated the instructions to access it.  It's suprisingly difficult to find a direct list of APKs. 

> Here's [Kontrast (A Color Contrast Checker)](https://f-droid.org/packages/org.kde.kontrast/), another such a11y (but FOSS!) tool, which 1 has to add the [KDE Android repo](https://cdn.kde.org/android/stable-releases/fdroid/repo/?fingerprint=13784ba6c80ff4e2181e55c56f961eed5844cea16870d3b38d58780b85e1158f) to view & install via a compatible F-Droid viewer.

**Comment by Versty** [comment]
@TPS Thank you! 
We discussed this tool with our design team, we actually use a similar one and we're basically aiming for AA contrast levels in AdGuard applications.
