### ISSUE TITLE
Can't start protection on Verizon Pixel

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#958]
Using a Verizon Google Pixel and I can't get your app enabled. It won't let me set up a VPN connection.

I try to enable the app and it will not let me enable. Pushing the button turns it green but as soon as I release it goes back to grey and the text underneath does not change. Hope the log helps.

Logs, Nov 30: 1456163

**Comment by ameshkov** [comment]
@evgeniy-ADG does he use any "overlay" app? "night mode", "f.lux" or anything like that?

It seems that Android does not show VPN permission dialog to him, and this is the only idea i have.

**Comment by Bohdan-SUP** [comment]
Asked the user.

**Comment by Yana-SUP** [comment]
another user with the same issue

device: Google Pixel XL
Android: 7.1.1

disabled build-in Night mode, but still no luck
trial worked fine

waiting for logs

User ID: **1469844**

**Comment by ameshkov** [comment]
> trial worked fine

That's just not possible, there's literally no difference.
What has changed in device configuration?

**Comment by Tetiana2020** [comment]
[debug (12).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/669593/debug.12.txt)

It's possible that there is one vpn application which interferes with AG. I'll update this task as soon as we have reply concerning that app.

**Comment by Yana-SUP** [comment]
Solved for **1469844**
He disabled Google's Wi-Fi assistant and this allowed him to enable Adguard.

**Comment by ameshkov** [comment]
> Google's Wi-Fi assistant

Yeah, that is a known issue indeed as Wi-Fi Assistant also uses VPN API.
