### ISSUE TITLE
zaycev.net not working with enable adguard

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#959]
1458413
http://zaycev.net/artist/19433
Не работают активные кнопки (Поделиться) и кнопки быстрого воспроизведения музыки
Отключение фильтров, HTTPS фильтрации - не помогает
Помогает только отключение защиты
лог
[debug (5).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/628772/debug.5.txt)
время логирования 19:58-19:59

**Comment by nkartyshov** [comment]
Проблема в фильтрах. 

@Alex-302 Посмотри в чем проблема.

**Comment by Alex-302** [comment]
@nkartyshov У меня и без Адгарда там ничего не работает, только белый оверлей при попытке воспроизвести.
@vozersky можешь у себя проверить? Хотя бы ломающий фильтр вычислить и с ним лог снять.

**Comment by ameshkov** [comment]
Closed as invalid
