### ISSUE TITLE
In-app ads are not blocked when DNS filtering is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#961]
In-app ads are not blocked when DNS filtering is enabled: News Republic, Appy
Geek

All issues are gone when the DNS filtering is disabled (ipv4, ipv6 bypass disabled,
Filer DNSrequest, Simplified Domain names Filtering disabled)

Screenshots:

<details>

![screenshot_20161203-125453](https://cloud.githubusercontent.com/assets/15856304/20865277/6235ec40-ba16-11e6-8f5c-2e2861fde922.png)

![screenshot_20161203-125453](https://cloud.githubusercontent.com/assets/15856304/20865278/6a2a310e-ba16-11e6-9265-4cb722fa1869.png)

</details>

[debug (2).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/629381/debug.2.txt)

[state (27).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/629382/state.27.txt)

1457368

**Comment by evgeniy-ADG** [comment]
Also, there're some placeholders on apkmirror.com and other sites when the said filter is enabled:

<details>

![screenshot_20161203-121855](https://cloud.githubusercontent.com/assets/15856304/20865293/b233a26e-ba16-11e6-99b2-96e60dab6a66.png)


![screenshot_20161203-123453](https://cloud.githubusercontent.com/assets/15856304/20865294/b2dedba2-ba16-11e6-9748-2f3297b11ad9.png)

**Comment by ameshkov** [comment]
@evgeniy-ADG look into state.txt:

User has enabled both `pref.vpn.ipv4.bypass` and `pref.vpn.ipv6.bypass`, which leaves him with DNS filtering only.

First of all, DNS-level ad blocking is not as good as what Adguard does usually. It's just better for the battery.

Second, if he wants to try DNS-level only, `simplified domain names` filter is mandatory.

**Comment by evgeniy-ADG** [comment]
Oh, thatnks.
