### ISSUE TITLE
cityguide.probki.net doesn't work correctly when Adguard is ON

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#962]
1459261
⁣https://play.google.com/store/apps/details?id=cityguide.probki.net

Не работает обновление и установка карт Ситигида. Процесс установки висит на 0.00%
отключение HTTPS не помогает
Помогает полное отключение Adguard или исключение из фильтруемых
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20882159/4fb2b454-bae8-11e6-9831-42b19e911eda.png)

**Comment by ameshkov** [comment]
Помогает ли просто отключение блокировки рекламы для этого приложения?
Без полного отключения?

**Comment by vgavrish** [comment]
Отключение блокировки рекламы не помогает

**Comment by ameshkov** [comment]
Значит это таки дефект, оставляем его на версии 2.9.

**Comment by nkartyshov** [comment]
Отключил фильтрацию полностью для прилоежния, т.к. vpn Не может принимать входящие ftp соединения.

**Comment by ameshkov** [comment]
Есть ли реклама в этом приложении?

**Comment by nkartyshov** [comment]
Рекламы нету.
