### ISSUE TITLE
Twitter sponsored ads not filtered

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardForAndroid#963]
https://github.com/AdguardTeam/AdguardFilters/issues/3625

**Comment by Bluscream** [comment]
So a app with a pjnned cert can force all traffic to go through adguard?

**Comment by Bluscream** [comment]
I've read https://security.stackexchange.com/questions/29988/what-is-certificate-pinning but i still don't get why adguard should be unable to block it :x

**Comment by ameshkov** [comment]
Because twitter app checks the server certificate and does not allow to use a cert different from the original one.

**Comment by Bluscream** [comment]
So i would have to tamper the app to change the accepted certificates? Can i do that with LuckyPatcher or would i need to go deeper (APK editor/recompile)?

**Comment by ameshkov** [comment]
Not sure, it may be enough to use options listed here: https://github.com/AdguardTeam/AdguardForAndroid/issues/472

**Comment by Bluscream** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/930
