### ISSUE TITLE
In proxy mode disabling Adguard for an app does not unblock UDP to port 443

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#964]
"Здравствуйте, после обновления перестал соединиться vpn по udp на 443 порт vps при включенной программе. 2 разных клиента впнов добавил как пропускать трафик мимо, не помогло, может я еще чего в настройках пропустил? до обновления все работало из коробки."

User ID: 1226048

**Comment by Alex-302** [comment]
Отключение фильтров помогает?

**Comment by ameshkov** [comment]
Это - дефект, внесенный в версии 2.8. Пока что единственный вариант исправления - использовать другой порт.

**Comment by ameshkov** [comment]
Resolved. In new build it will be enough to uncheck "Enabled" flag in the app option, so that Adguard was not messing with app UDP traffic anymore.
