### ISSUE TITLE
com.google.android.youtube.tv

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#965]
User complaint:
http://forum.xda-developers.com/android/apps-games/adguard-ad-blocker-doesnt-require-root-t2958895/post69932793#post69932793

https://play.google.com/store/apps/details?id=com.google.android.youtube.tv&hl=en
http://forum.xda-developers.com/showpost.php?p=69959599&postcount=1938

**Comment by nkartyshov** [comment]
Done
