### ISSUE TITLE
Firewall temporary allowance notification is not displayed

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#966]
Reproduced on Samsung s7

Could be a foreground detection issue.

### Here's what we should do

In order to detect if the app is in foreground or not, we should be using the UsageStatsManager: https://developer.android.com/reference/android/app/usage/UsageStatsManager.html

The only question is when should we ask for the necessary permissions. I suggest doing it every time user decides to block network access for some app (or a list of apps via the batch action).

### More info

`queryEvents` can be slow, we have to test it.

https://github.com/ricvalerio/foregroundappchecker
https://medium.com/@quiro91/show-app-usage-with-usagestatsmanager-d47294537dab

**Comment by ameshkov** [comment]
@vozersky can you reproduce it with Nougat?

**Comment by vozersky** [comment]
@ameshkov yes, same story with Nougat

**Comment by vozersky** [comment]
@ameshkov @Revertron @nkartyshov 

Looks like it became a common issue for all devices with Android 6 and 7.
Firewall temporary allowance notification doesn't work anymore.

**Comment by nkartyshov** [comment]
This problem is not solve now. Android 7 restrict access to folder /proc for other processes, but solve this problem help use UsageStatsManager.

Information about UsageStatsManager: https://developer.android.com/reference/android/app/usage/UsageStatsManager.html.

**Comment by ameshkov** [comment]
Delayed to v3.0 as this UsageStatsManager integration will take quite some time, and I'd like v2.9 to be released as soon as possible.

**Comment by vozersky** [comment]
more complains about the bug: id 583184

**Comment by kbahlyk** [comment]
Same issue on Android 7.1.1.
Ticket ID: 1556849

**Comment by Wiredframe** [comment]
Great to see you're working on fixing this issue. The notification feature was great, hope it'll be back in the future. Good luck.

**Comment by evgeniy-ADG** [comment]
Here too, MIUI 8.5 on Android 7.0: 1589286

**Comment by ameshkov** [comment]
Done
