### ISSUE TITLE
Improve outbound proxy support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#968]
## UI

Raw mockup:
https://app.moqups.com/ameshkov/lfmli7Cikw/view/page/afeaa413a

### Main screen

<details>
<summary>Main screen</summary>

![adguard for android - outbound proxy moqups 2017-07-06 12-12-53](https://user-images.githubusercontent.com/5947035/27904267-d040922c-6244-11e7-8106-617cb515e0f3.png)
</details>

#### Description

1. `Show notification icon` -- changes notification priority. Enabled by default. When it's enabled, notification priority is high, so the icon is visible in the notifications bar. When it's disabled, notification depends on the next setting value.
2. `Show notification only` -- disables or enables outbound proxy notification. Enabled by default. This setting is visible in case if the previous setting is disabled.
3. `Always connect to the default proxy` -- if enabled, AdGuard will use the default proxy every time when it starts protection. This means that AdGuard will show the proxy notification and route traffic through that proxy.
4. `Known proxy and VPN providers` -- leads to https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy. That article should be soon updated: https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/87
5. Help icon - leads to the same article.
6. Tapping on `Add proxy` item brings up a "New proxy" dialog:

<details>
<summary>New proxy dialog</summary>

![adguard for android - outbound proxy moqups 2017-07-06 12-13-01](https://user-images.githubusercontent.com/5947035/27904268-d19df948-6244-11e7-9e36-9fd4d8618391.png)
</details>

### Proxy servers list

<details>
<summary>Proxy servers list</summary>

![adguard for android - outbound proxy moqups 2017-07-06 12-13-10](https://user-images.githubusercontent.com/5947035/27904269-d2ef178c-6244-11e7-8b2a-985e824239db.png)
</details>

#### Description
1. Connected proxy is always the first item of the list and separated from others with a border.
2. Tap on a list item brings up a dialog with possible options: `Connect/Disconnect`, `Edit`, `Delete`
3. There should be confirmation dialog when user tries to delete a proxy item.

### Notifications

When protection is started and a proxy is connected, we should a permanent notification:
![adguard for android - outbound proxy moqups 2017-07-06 12-13-19](https://user-images.githubusercontent.com/5947035/27904272-d443cb6e-6244-11e7-8429-bc3fa57404b0.png)

If user taps "Disconnect", we show a regular "swipeable" notification:
![adguard for android - outbound proxy moqups 2017-07-06 12-13-25](https://user-images.githubusercontent.com/5947035/27904274-d58fe732-6244-11e7-93ee-b1444a96cb18.png)

Old mockups (deprecated):
<details>

It should look and feel just like Wi-Fi.

### Disabled state

<details>

![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-41-14](https://cloud.githubusercontent.com/assets/5947035/21021693/9e5897b4-bd8a-11e6-979f-a9af87300746.png)
</details>

### Enabled state

List of pre-defined proxy providers.
Also user can add a custom proxy.

<details>

![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-41-31](https://cloud.githubusercontent.com/assets/5947035/21021694/a0709ae2-bd8a-11e6-9af0-535be83c77f2.png)
</details>

### Known proxy provider setup guide

We should make it easier for user to setup outbound proxy for known/popular proxy providers like Orbot or PIA.

<details>

![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-41-50](https://cloud.githubusercontent.com/assets/5947035/21021698/a41ef49a-bd8a-11e6-9224-35bcd1313767.png)
![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-42-34](https://cloud.githubusercontent.com/assets/5947035/21021701/a6c9b27a-bd8a-11e6-8ca0-898e7f7c16c4.png)
![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-43-00](https://cloud.githubusercontent.com/assets/5947035/21021704/a8f3907a-bd8a-11e6-99d6-fc19be065893.png)
</details>

### Custom proxy settings

<details>

![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-47-36](https://cloud.githubusercontent.com/assets/5947035/21021706/ab88a82a-bd8a-11e6-8242-6ba8af6ac31d.png)
</details>

### Quick settings

<details>

![online mockup wireframe ui prototyping tool moqups 2016-12-08 20-53-56](https://cloud.githubusercontent.com/assets/5947035/21021713/ade34e36-bd8a-11e6-9cb7-1661f53e1ee4.png)
</details>

### Global outbound proxy settings

<details>

![online mockup wireframe ui prototyping tool moqups 2016-12-08 21-08-41](https://cloud.githubusercontent.com/assets/5947035/21021716/b13b18ca-bd8a-11e6-9091-f0caca35466d.png)
</details>

</details>

**Comment by ameshkov** [comment]
Design:
https://www.dropbox.com/sh/hbyij2eshltb562/AAAetr29wADYBC0Uscw027WVa?dl=0

Ignore the text there, it's just a stub.

**Comment by ameshkov** [comment]
Icons:
https://www.dropbox.com/s/qvee9embji7p2d8/outbound_proxy_icons.zip?dl=0

**Comment by ameshkov** [comment]
### Issues with the current implementation.

1. Outbound Proxy should be a separate settings section.
2. There should be a mandatory "Name" field in the Proxy Settings.
3. There should be a placeholder when the list of proxies is empty. Just like in the User filter.
4. Proxy notification should be permanent when the module is enabled (even when it is not connected to a proxy). Tap on it leads to the "Outbound Proxy" settings.
5. "Proxy type" must be a mandatory field. You cannot save proxy with type equal to "None".
6. In the "Add proxy" screen you should divide manual proxy from the proxy templates. "Enter manually" and "Known proxy providers".

**Comment by nkartyshov** [comment]
@ameshkov fixed all the items. Added committo review: AJC-CR-151.

**Comment by nkartyshov** [comment]
New review in android repo: AFA-CR-37

**Comment by ameshkov** [comment]
I was thinking lately, maybe we should add a seamless Tor/Orbot integration?

It looks, that it is quite easy to achieve using this: https://github.com/guardianproject/NetCipher
`OrbotHelper` checks if Tor is installed and also able to start it automatically. Once it's started, we can re-route traffic through the Orbot's proxy.

**Comment by ameshkov** [comment]
Review ID: AFA-CR-51 (credits to @Revertron)

**Comment by ameshkov** [comment]
TODO: When DNS filtering is enabled, we should also route UDP through proxy (in case of a socks proxy)

**Comment by ameshkov** [comment]
@Revertron issues with the current implementation:

1. Outbound proxy settings screen does not react to changes via Notification (subscribe to the events) and via edit dialog (switching default flag);
2. No quick settings tile;
3. Edit dialog is too narrow (that's a common issue on all smartphones btw, @nkartyshov had something in mind about it)

**Comment by ameshkov** [comment]
A bit more issues:

1. No confirmation dialog on proxy deletion
2. Context menu position when you tap on a proxy
3. There should be a border between "Known proxy ..." and Settings

**Comment by ameshkov** [comment]
More issues:
1. If no default proxy is configured, tap on the tile should bring up the proxy settings activity
2. Long tap on the tile should open proxy settings (not main activity)

**Comment by Revertron** [comment]
Long tap on tile can not know what tile was long-tapped (our main or proxy).

**Comment by Revertron** [comment]
All the issues are done.

**Comment by Revertron** [comment]
Everything is done and merged.

**Comment by TPS** [comment]
@ameshkov This is such a minor nit, I'm not sure it warrants a new issue:

The seamless Orbot integration mentioned above gives a _direct_ link to GPlay's Orbot.  That's probably normally fine, but, since AG is normally either sideloaded, or installed from Amazon Appstore, wouldn't it be better to provide both _indirect_ link, which would be caught be any relevant app-provider (GPlay, F-droid, &c) ***&*** direct link to https://guardianproject.info/releases/orbot-latest.apk ?

I'd suppose many of the folks using AG & Orbot would prefer not or can't use GPlay, &, the way AG is setup now, it forces them solely to GPlay.  N.B.:  I came here to ask for the Amazon version to link the [Appstore's](https://smile.amazon.com/gp/product/B00E7TIFGQ), but that seems permanently abandoned @ a 2012 version. 😭

**Comment by ameshkov** [comment]
@TPS it will use F-Droid or Play depending on which one is detected first.

**Comment by TPS** [comment]
It seems to do it oddly:  Normally, when the intent is hit on my devices, I get a list of apps that can open it.  AG seems to request the apps _directly_.  It'd be better to do the intent, IMHO, or @ least change the order to call F-droid 1st.  Also, does it (lastly) pull https://guardianproject.info/releases/orbot-latest.apk if neither is detected?
