### ISSUE TITLE
Left-sidebar navigation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#969]
Can't wait till v3.0, we need it earlier:)

* No more right-top menu.
* "Check updates" button -> make it the same as in "Adguard Content Blocker" (right-top corner image button)
* Menu items just like we're planning for v3.0:

```
Dashboard ---> rename to "Home" (as it is not yet a dashboard).
Apps Management
-----
Settings
-----
Send feedback
Activate license (or "Manage license")
About
-----
Exit
```

* Put protection status to the profile part of the menu: https://monosnap.com/file/FoasOVGmpJBimnJMqgwuld5V9vssNg

* Don't forget to handle the case when protection status is too long (which is unlikely, but who knows with all these translations).

Icons (48px):
[Adguard 2.9 Navigation.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/637628/Adguard.2.9.Navigation.zip)

Icons (24px):
[Adguard 2.9 Navigation (1).zip](https://github.com/AdguardTeam/AdguardForAndroid/files/637632/Adguard.2.9.Navigation.1.zip)

**Comment by Revertron** [comment]
Done!

**Comment by ameshkov** [comment]
Not yet, I'll add notes to this task

**Comment by ameshkov** [comment]
Here is a list of activities, where we should get rid of the old action bar menu.

1. Settings (and subsettings)
2. FAQ (list)
3. FAQ (answer)
4. Apps Management
5. App details
6. License status
7. Send Feedback
8. About

**Comment by ameshkov** [comment]
### **Apps Management** 

It should have its own action bar menu.

**Menu items**

* Firewall defaults --> Leads to the Firewall settings activity
* Reset settings ---> Resets settings to default. Please note, that this action is executed asynchronously and leads to the whole apps management section refresh.

**Comment by ameshkov** [comment]
"License status" is weird, it is visible how it goes through "Subscription status".

There was no such issue in v2.8

**Comment by Revertron** [comment]
Done, review - AJC-CR-153

**Comment by deLumren** [comment]
In 2.9. "Clear statistics" button is harder to reach than now:
You need to go to Apps Management - top-right corner - Clear Statistics.
WiIl this be changed before going live?

**Comment by ameshkov** [comment]
@deLumren nope, why? Context menu is a good for place for this kind of actions.
