### ISSUE TITLE
1tv.app - некорректная прогрузка видео

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardForAndroid#970]
https://play.google.com/store/apps/details?id=com.ipspirates.ort&hl=ru

видео недогружается после 3-х минут
Пробовал vpn и прокси, проблема остается
помогает только полное отключение защиты
повторилось
отключение HTTPS, фильтров, "блокировки рекламы" и отключение фильтрации для приложения - не помогает

 **Time** 20.51.

[debug (1).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/639131/debug.1.txt)

**User id** 638690

**Comment by Alex-302** [comment]
@Yana-SUP Лучше сперва в фильтрах создавать, т.к. скорее всего ложное срабатывание.

**Comment by Alex-302** [comment]
> видео недогружается после 3-х минут

что это означает - три минуты ждал и видео не запустилось, или остановилось со временем?

**Comment by vgavrish** [comment]
@Alex-302 Я проверяла, отключение фильтров не помогло
Идет загрузка и проигрывание видео до 3-04 минуты http://prntscr.com/dgubkn
Далее просто идет переключение на следующее видео
Необходимо чтобы видео самостоятельно проигрывалось, вручную при прокрутке видео проблемы нет

**Comment by Alex-302** [comment]
Т.е. не прямой эфир, а старые видео? Так?
В этом случае у меня не повторилось(режим VPN). Забуферизировало сразу 6 минут, потом по мере воспроизведения подгружает.

**Comment by vgavrish** [comment]
да, старые в разделе "Новости"
ну у меня до сих пор проблема
обязательно нужно не нажимать на перемотку/прокрутку видео, а то в таком случае оно его все буферизирует

**Comment by Alex-302** [comment]
Странно. У меня ролики играют нормально.
Тогда наверное конфликт какой-то.
А если в файерволе выключить фильтрацию приложения?

**Comment by vgavrish** [comment]
Да, отключение фильтрации помогает в настройках

**Comment by ameshkov** [comment]
@vgavrish а если кэш приложения почистить?

@vozersky можешь проверить как у тебя?

**Comment by vozersky** [comment]
Can't reproduce on Android device (Nexus 9)
Please note that the customer uses an unofficial Nougat build for Nexus 5.  
@ameshkov Could this be a root of the problem?

**Comment by vgavrish** [comment]
С очисткой кеша, без рут прав, андроид 6.0.1, у меня еще наблюдается проблема

**Comment by ameshkov** [comment]
> отключение HTTPS, фильтров, "блокировки рекламы" и отключение фильтрации для приложения - не помогает

Вот это что-то уже очень странное. Если фильтрация для приложения отключена, мы никак на его трафик не влияем

**Comment by vgavrish** [comment]
сори, там отключение фильтрации помогает

**Comment by ameshkov** [comment]
> сори, там отключение фильтрации помогает

Ну давай тогда это оставим как временное решение и подождем других жалоб.
