### ISSUE TITLE
Add ability to set start/end date in Apps Management 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardForAndroid#972]
**Description:** 
"When you use your app management data for a month
I want to be able to specify a start date"

**User id:** 1455209

**Comment by ameshkov** [comment]
Will be covered in v3.0

**Comment by ameshkov** [comment]
We couldn't do it as a part of v3.0. Postponed to v3.2 as we don't plan to do any serious UI changes in v3.1

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/AdguardForAndroid/issues/972
