### ISSUE TITLE
Slow connection speed via wi-fi / mobile network

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#975]
id 1327628
HTC One, android 5.0.2
Adguard 2.8.67 (and 2.8.58)

медленная загрузка данных в приложениях. (chrome)
в no root firewall VPN работает 
[debug (3).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/645686/debug.3.txt.zip)

**Comment by ameshkov** [comment]
Please ask does it help to change `pref.vpn.mtu` value in the low level settings?
Ask user to try smaller value (4000 or even 2000)

**Comment by ameshkov** [comment]
@zebrum any update on this?

**Comment by zebrum** [comment]
@ameshkov there was no answer from user

**Comment by zebrum** [comment]
couple weeks later user did factory reset and after that Adguard start working as it should.
