### ISSUE TITLE
Colored icon support in Nougat

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#976]
It seems that colored icons are supported again in Nougat:
https://github.com/AdguardTeam/AdguardForAndroid/issues/859#issuecomment-264599505

**Comment by TPS** [comment]
Sign me ↑ to test this, also. ☺

**Comment by ameshkov** [comment]
Delayed to v3.0, it'd better to do it along with the redesign.

**Comment by TPS** [comment]
Another related detail: apps like Ff Focus/Klar & F-droid have monochrome notification _bar_ icons, but full-color notification _flyout/list_ icons.

**Comment by ameshkov** [comment]
@nkartyshov check if this is possible, I can't see it in the docs yet (maybe limited to apps targeting old SDK?)

**Comment by TPS** [comment]
Just FYI, this still works in Oreo/8.1.

**Comment by nkartyshov** [comment]
i don't understand what your mean @TPS. 
Android 8+ doesn't support the colorized icon on status bar.

**Comment by TPS** [comment]
@nkartyshov 🤷‍♂️ The above screenshot was taken w/ 7/Nougat, but is identical to how it looks when my device upgraded to 8/Oreo.

**Comment by ameshkov** [comment]
In the end, we didn't find any way to use colored icons on modern Androids.

**Comment by TPS** [comment]
This is now fixed in ≥ v4.0n39, but is a bit faint.  Possible to increase contrast via increasing brightness &/or line thickness?

**Comment by artemiv4nov** [comment]
Hello! We use our standard logo in all cases, and it cannot be changed.

**Comment by TPS** [comment]
> Hello! We use our standard logo in all cases, and it cannot be changed.

@artemiv4nov That's a bit of a non sequitur, considering I'm requesting that your logo be made easier to see.  As it is, it fades a bit too much into the background.

**Comment by TPS** [comment]
#5044 now tracks this
