### ISSUE TITLE
Make persistent notification without icon smaller

### ISSUE THREAD

**Issue by delmicio** [AdguardTeam/AdguardForAndroid#977]
Hi,
I'm using the notification without icon only to have the persistent feature (using os 7.1).

But it seems to me that It could be smaller than three lines, may be one line:
(app + title : status/message)

Or two:
(app
title : status/message)

Instead of current three:
(app
title
status/message)

what do you think? could this be made?

**Comment by ameshkov** [comment]
I doubt it's possible to make a 1-line notification.
2-line should be possible though.

@Revertron what do you think

**Comment by Revertron** [comment]
I'm sure that we can't make it smaller than minimal size impozed by system.

**Comment by delmicio** [comment]
I've this application with a smaller notification for the same purpose as
Adguard, to make it persistent.

Here is a screenshot:

**Comment by ameshkov** [comment]
> smaller than minimal size impozed by system.

What's that min size?

> Here is a screenshot:
> ![imagen](https://cloud.githubusercontent.com/assets/2908209/21318322/70739b86-c5e7-11e6-9f45-e90e3c07865d.png)

I guess if we leave only 1 string notification size will be pretty much the same.
I wonder how will it look like on KitKat though.
