### ISSUE TITLE
Wifi automatically disconnecting

### ISSUE THREAD

**Issue by jerryn70** [AdguardTeam/AdguardForAndroid#978]
My wifi gets automatically disconnect and reconnect frequently but some times it occurs only occasionally. 

●Adguard version : Facing this issue on all adguard versions 

● Phone : moto x play (indian )

●Wifi router : Netgear N150

●Note : i tried other ad blocking apps adclear,dsn66 and blokada. While using these I'm not getting that disconnection issue. But the connection speed too slow , it takes more time to load pages in apps / sites .

**Comment by ameshkov** [comment]
> My wifi gets automatically disconnect and reconnect frequently but some times it occurs only occasionally.

How does it look like visually? Does wifi icon disappear or change state?

Please try checking `pref.vpn.disable.pause` in AG settings. Does it change anything?

**Comment by jerryn70** [comment]
@ameshkov

Phone drops the wifi network then reconnect it again

**Comment by ameshkov** [comment]
@jerryn70 what or the setting, any change when you enable it?

**Comment by jerryn70** [comment]
@ameshkov 
I have changed the settings but I'm getting the same issue .

**Comment by ameshkov** [comment]
@jerryn70 weird. ok then, it seems I need to take a look at the log file.

Could you please record logcat log as it is described here?
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/62/0/how-to-get-logcat-log-from-android-device

I'll also need to know exact timing, when did the issue happen.

**Comment by jerryn70** [comment]
@ameshkov i don't have my lap with me to take log is there other way to take log ?

**Comment by ameshkov** [comment]
@jerryn70 do you have root acces?

**Comment by jerryn70** [comment]
@ameshkov No . 
Is it possible to take log using adguard settings-advanced - logging level

**Comment by ameshkov** [comment]
@jerryn70 this log will be helpful, but not as good as logcat, we won't see the real cause of the issue.

Anyway, it'd be good if you record it.

**Comment by jerryn70** [comment]
@ameshkov ok i will try to get logcat. Plz give me 1 week time.  I need to get my lap back.

**Comment by ameshkov** [comment]
No worries! It's just we're on long NY vacation, so it may take some time to process it on our side as well.

**Comment by ameshkov** [comment]
Um, sorry for not getting back to you that time:(

Please reopen if the issue still happens.
