### ISSUE TITLE
HTTPS filtering in apps targeting Nougat

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#979]
1. We should ensure that HTTPS filtering works in Nougat WHEN user moved certificate to the system store.
2. We should come up with a better instruction on how to overcome this restriction on rooted devices.
3. HTTPS filtering in apps details should be grayed out unless certificate is installed to the system store.

**Comment by ameshkov** [comment]
@vozersky we need to test it on a rooted device with Nougat.

**Comment by ameshkov** [comment]
I've tested it on Android 5.1 using Move Certs app and found&fixed a couple of issues: AJC-CR-196

Please test it on Nougat now, what we need to check is if HTTPS filtering actually works for apps targeting API 24 when the certificate is moved to the system store.

**Comment by Revertron** [comment]
Works without any problem, mitm and filtering is going well.
