### ISSUE TITLE
TCP retransmissions are broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#98]
Finally I've narrowed that old bug down.

Affected: download any large file.

We use byte array pool to store TCP packets data. After TCP packet is sent to TUN, we release byte array with packets data and return it back to pool. Along with this we place packet into retransmission queue. When client asks for retransmission, we send packet to TUN again, but the array with packet data may be filled with another packet data.

**Comment by TPS** [comment]
This also bit updating in Amazon Appstore (even updating AdGuard)!

**Comment by ameshkov** [comment]
Do you use any low-level settings? I've broken MTU setting in the previous beta (fixed in 2.1.260 which is available now)

**Comment by TPS** [comment]
Nope, left all that default while chasing this. ☺

**Comment by ameshkov** [comment]
And what was the AG version?

**Comment by TPS** [comment]
I was having this in .231 (I think).

**Comment by ameshkov** [comment]
Ah, the old one:)

**Comment by ameshkov** [comment]
It could affect any download, does not depend on the app starting it.

**Comment by TPS** [comment]
Sorta Catch-22. ☺  Sometimes, the brain works. :wink:

**Comment by TPS** [comment]
I'm _still_ having GPlay (& presumably, Appstore) updating & downloading problems in .260 VPN, but _not_  in .261 proxy.  Help!  I'm having to disconnect AG & reset wifi connection to make these work. :disappointed:

**Comment by ameshkov** [comment]
I must say that is something new. I need to see the log first.

**Comment by TPS** [comment]
Can you replicate via link provided?  Else, I'll send log.

**Comment by ameshkov** [comment]
Let me try

**Comment by ameshkov** [comment]
> http://m.costco.com/wcsstore/CostcoUSBCCatalogAssetStore/Attachment/Kitchen_Install_Requirements.pdf

I see Access denied page instead

**Comment by TPS** [comment]
Still WFM & http://isup.me/m.costco.com.…  Does http://m.costco.com/ work?

**Comment by ameshkov** [comment]
Nope, also 403 Access Denied

**Comment by TPS** [comment]
@ameshkov Default log sent via ticket# OSD-284-64641 .…  Let me know if you need more detail, another log, whatever. ☺

**Comment by ameshkov** [comment]
> @ameshkov Default log sent via ticket# OSD-284-64641 .… Let me know if you need more detail, another log, whatever. ☺

Yep, I'll need a detailed log, no errors in default on.

**Comment by TPS** [comment]
Detailed log sent via ticket# GYK-145-70458 .…  I also hit the PCAP option, but don't know if that's sent the ticket; do you need that sent separately?

**Comment by TPS** [comment]
@ameshkov I just got back to this — it's been a rather busy few days — but I can't replicate anymore:  GPlay is "normal" (weird UI, but that's on Google) & that Costco PDF downloads fine.  I suspect somebody fixed some filters.  Good on you all! ☺

**Comment by TPS** [comment]
The [problem](
https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-153383133)
has relapsed.  I'm sending everything log, PCAP, *&* a screenshot showing
timeouts.  The logs are very long (~½ hour)  because timeouts seem to be
around 10 minutes, & I wanted to make sure I didn't miss *anything*!

On Thu, Nov 5, 2015, 3:46 AM Andrey Meshkov <notifications@github.com>
wrote:

> @ameshkov <https://github.com/ameshkov> Default log sent via ticket#
> OSD-284-64641 .… Let me know if you need more detail, another log,
> whatever. ☺
>
> Yep, I'll need a detailed log, no errors in default on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-153990939>
> .
>
-- 

https://zhjf9h10ji3.ting.com/

**Comment by TPS** [comment]
@ameshkov 

> Does download fail in any browser or in Ghostery Browser only?

As [mentioned](https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-153383133), download technically fails in Download Manager, as all the Chrome-based browsers (as Ghostery is) seem to hand off to it.  The only other 1 I run on this device (CM Private Browsing) exhibits the same behavior.

> Update error notification - is it from Google Play or Amazon?

This is GPlay — Amazon seems to work fine.

**Comment by ameshkov** [comment]
The weird thing is that I don't see any trace of the "com.android.providers.downloads" in the log file.

**Comment by ameshkov** [comment]
In the same time I see there was an attempt to download that "pdf" file by ghostery browser:
```
10:52:33.585 [pool-2-thread-288] DEBUG com.adguard.android.FilteringLog - TCP id=433 got connection com.ghostery.android.ghostery /XXX:37441 /XXX:80 10114
10:52:34.010 [pool-2-thread-288] DEBUG com.adguard.android.FilteringLog - TCP id=433 GET "http://m.costco.com/wcsstore/CostcoUSBCCatalogAssetStore/Attachment/Kitchen_Install_Requirements.pdf" 200 2151184 387ms "null" "Mozilla/5.0 (Linux; Android 4.4.2; 306SH Build/S7232) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"
```

**Comment by ameshkov** [comment]
So, the main question is: where is the Download Manager?:) Could you please use a Logcat instead of our log?
One more thing - switch Adguard logging level to default, I believe this issue is not just some AG bug, but something more "complex" and involving other apps.

**Comment by TPS** [comment]
I've no capability for logcat — no root nor external PC to do so.

Let me try disabling Ad Filtering in the firewall — or should this be done via pref.net.exclusions — & report back.  Is there anyway particular reason why this isn't excluded _by default_?

**Comment by ameshkov** [comment]
> Is there anyway particular reason why this isn't excluded by default?
Download manager? For us to be able to block malware files download for instance.

> I've no capability for logcat — no root nor external PC to do so.
@TPS that's bad, i can't troubleshoot it without logcat log.

The problem is obviously linked with AG, it's just not directly caused by ad blocking.

By the way, have you tried disabling DNS filtering?

**Comment by TPS** [comment]
>Download manager? For us to be able to block malware files download for instance.

Excellent reason! ☺
>@TPS that's bad, i can't troubleshoot it without logcat log.

I hope to resolve lack of PC in 30 days.… :pray:  Then logcat for many pending issues!
>By the way, have you tried disabling DNS filtering?

Sadly, doesn't help.…

**Comment by ameshkov** [comment]
Then let's wait, the bug is weird, but as I know you're the only one facing it for now.

We can do one more check meanwhile.
Next time you'll run into that - please go and clean Download Manager cache and data and retry the download. If it help then something is wrong with the current download manager state. If it does not help then it is much more weird than I thought:).

**Comment by TPS** [comment]
>Next time you'll run into that - please go and clean Download Manager cache and data and retry the download.

I can induce it anytime by either clicking that Costco link above &/or updating/installing — either / both will timeout in ~10 minutes.
Wiping both Downloads & Download Manager didn't help. :disappointed: 


Is it possible to have a new label: "Pending logcat"?  It'd help me later on to find these issues when I'm setup for them.…

**Comment by ameshkov** [comment]
I think it would be better to create a separate issue (as anyway I don't think it has something to do with the current one:) )
