### ISSUE TITLE
WealthSimple (finance app) not working correctly when AdGuard is enabled.

### ISSUE THREAD

**Issue by salimnanji** [AdguardTeam/AdguardForAndroid#982]
WealthSimple uses security measure called "certificate pinning" so the app is sure they are talking to Wealthsimple servers even over untrusted internet.

With HTTPS Filtering toggled on, the app does not work correctly and will not launch (seems like a request isnt being sent through the servers correctly, and the app thinks it is out of date).

**Comment by salimnanji** [comment]
Whoops. Closed by accident.

**Comment by war59312** [comment]
I added to the list.

Can close this after all ;)

**Comment by salimnanji** [comment]
You're the man. Thanks!

**Comment by war59312** [comment]
No problem.

**Comment by Revertron** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/911#issuecomment-196888685
