### ISSUE TITLE
No internet in apps through mobile connection

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#983]
id 1468119
android 5.1.1
adguard 2.8.76
время ~ 15.25

[debug (7).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/657169/debug.7.txt.zip)

**Comment by ameshkov** [comment]
Forum discussion:
https://forum.adguard.com/index.php?threads/%D0%9D%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BD%D0%B0-%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%D1%85.17622/#post-118243

**Comment by ameshkov** [comment]
Problem solved (forum)
