### ISSUE TITLE
Gboard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#984]
https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=en

doesn't work unless you disable the HTTPS filtering for it.

**Comment by nkartyshov** [comment]
@evgeniy-ADG App work fine in last beta with https filter. What's the problem?

**Comment by evgeniy-ADG** [comment]
The problem is that it didn't work on Dec 18, when the customer reported the bug and I was able to reproduce it. Glad to know if works.

**Comment by ameshkov** [comment]
Still there're some issues with it:
> Имеется проблема: при включенном пропускании трафика приложения Gboard через Adguard, Gboard пишет, что нет соединения с интернетом (если искать какую-либо информацию через клавиатуру). Поиск начинает работать только при отключении этой галочки.

**Comment by nkartyshov** [comment]
Added googleapis.com in ssl white list. Other google apps should work fine after this.

**Comment by ameshkov** [comment]
googleapis might be used for ads serving

**Comment by nkartyshov** [comment]
Changed on gboard-pa.googleapis.com

**Comment by ameshkov** [comment]
Maybe it would be better to disable https filtering for it?

**Comment by nkartyshov** [comment]
Added in https exclusions
