### ISSUE TITLE
Filter Mobile Data using Proxy without root 

### ISSUE THREAD

**Issue by jpdasma** [AdguardTeam/AdguardForAndroid#985]
Hello, this is not an issue or a bug report. This is more of a guide. I noticed that you state in your website that it is impossible to filter mobile data using Adguard in Proxy mode without root. However, there is a way to do this.

Go to Settings -> Cellular networks -> Access Point Names -> (Currently used APN)
You will see a page that will look like this.

http://i.imgur.com/BE8OZkj.png

In the Proxy Field, type 127.0.0.1
In the Port Field, type 8080 (or whatever is set in Adguard)

After doing this, you can now filter using proxy mode without root.

Actually, with this, Adguard in proxy mode is usable even though it is not automatic. You only need to set it once for mobile data. For wifi, you just need to set it every time you connect to a new network.

**Comment by ameshkov** [comment]
Yeah, I am aware of this way. However, depending on your celullar provider, APN settings may be locked.

Anyway, i suppose this guide is worth being in our knowledge base, thank you!
