### ISSUE TITLE
Latest Galaxy S7 Nougat beta issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#986]
There are some reports about YT app crashes after the latest S7 Nougat beta update.

@vozersky try installing beta. I remember there were some issues with it before.
@seanl-adg please post here when you get any new information from affected users.

**Comment by ameshkov** [comment]
@vozersky one more complaint:
https://blog.adguard.com/en/adguard-android-2-8/#comment-3062331524

**Comment by ameshkov** [comment]
Customer ID: 1472005

**Comment by ameshkov** [comment]
Here is a rule to test:
`@@||googleadservices.com^$app=com.google.android.youtube`

**Comment by ameshkov** [comment]
Added this rule to mobile ads filter.

However, it may still be problematic if user has DNS-level ad blocking enabled.
We should keep this issue open.

**Comment by ameshkov** [comment]
Not good:

https://blog.adguard.com/en/adguard-android-2-8/#comment-3062571264
> The only other apps that crash with Adguard on are Microsoft Outlook and Microsoft Authenticator.

We should really test it on our side.

**Comment by evgeniy-ADG** [comment]
The customer provided logs: 1471972

>hello, Adguard seems to be the reason for the app crashes on galaxy s7
edge running nougat beta. Disabling adguard stops the crashes. Unsure
if it is because of the OS or adguard.

**Comment by ameshkov** [comment]
@evgeniy-ADG temporary solution is to disable Adguard for certain app (in apps management settings section).

We can't tell more unless we get this beta on our test device (which we currently can't do due to beta test limitations).

**Comment by vozersky** [comment]
Should be fine on release version.
