### ISSUE TITLE
com.poloniumarts.svyaznoy app - HTTPS compatibility

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#987]
com.poloniumarts.svyaznoy

![c7jnsqio0qi](https://cloud.githubusercontent.com/assets/15856304/21398350/b525a854-c7af-11e6-9d39-de445af8685d.jpg)

Disabling the HTTPS filtering for this app helps.

**Comment by ameshkov** [comment]
@evgeniy-ADG i am pretty sure it should be enough to disable https filtering for that app.

**Comment by nkartyshov** [comment]
added
