### ISSUE TITLE
Profile app memory usage

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#99]
After fixing #98 we should check if everything is good with memory usage

**Comment by ameshkov** [comment]
@Revertron look at VpnProxyService.cleanUpConnections method.
It is called every 250ms and creates some empty collections.

**Comment by Revertron** [comment]
cleanUp reworked, it will not create such collections on timer.

**Comment by ameshkov** [comment]
And what does profiling show? What about memory allocations?

**Comment by Revertron** [comment]
I am unable to make it eat more than 40mb.

**Comment by ameshkov** [comment]
Hey @Revertron , the question is more about memory allocations.
You know, the app may consume 40mb and spend 10% time in GC in the same time.

**Comment by Revertron** [comment]
If we have done the PacketPool instead of ByteArrayPool, than we could be less intensive on GC.
But now I now see that there is an increase in memory allocation (about 10mb) while speedtest is downloading data and there are regular GC runs that are collecting this spikes.
