### ISSUE TITLE
Adguard DNS does not work on mobile data

### ISSUE THREAD

**Issue by mozkan007** [AdguardTeam/AdguardForAndroid#992]
Hi,
I am using Adguard app and Adguard DNS on my android system.Both of them are  awesome about adblocking.I am using Adguard DNS on wifi and it is working great and because of this I want to use it on mobile data(3g/4g connections).So is there a way to use Adguard DNS on mobile data or could you integrate any option about that to Adguard app?Thanks.

**Comment by TPS** [comment]
Try configuring #139 in conjunction w/ AG in VPN mode.

**Comment by mozkan007** [comment]
Yes  I already tried this way but anyway it does not work on mobile data.

**Comment by TPS** [comment]
That's supposed to work!

@AdGuardTeam? @ameshkov?

**Comment by ameshkov** [comment]
@TPS why? As I understand @mozkan007 said that it works:)

**Comment by mozkan007** [comment]
Sorry after a while I noticed that it is not working to use pref.vpn.dns .Is there anything else that I can try?

@TPS  @ameshkov

**Comment by ameshkov** [comment]
> I tried adding adguard dns using comma, using space and also writing each dns for each line 

You should enter one on each line. Something like this:
```
176.103.130.130
176.103.130.131
```

> but all of them is not working .Is there anything else that I can try?

Huh, how exactly do you check if it works or not?

It works perfectly in my case.

**Comment by mozkan007** [comment]
@ameshkov  I am saying it is not working because When I connect to mobile data despite using pref dns with adguard ads in apps are not blocked.But When I connect by to wifi  internet and app ads are blocked.I think this issue is just occuring for me.Thanks.

**Comment by ameshkov** [comment]
@mozkan007 got it. So, this issue should be marked as a bug then.

For further troubleshooting, we need you to collect Adguard's full log. Could you please do it?

Here is an instruction:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android

**Comment by mozkan007** [comment]
@ameshkov I reproduced the issue and I send you the feedback as what you said.Thank you for your attention.

**Comment by zebrum** [comment]
@mozkan007 please tell me userID which you can find in an automatic response letter from our support team.

**Comment by mozkan007** [comment]
@zebrum  User ID**: 1481496

**Comment by zebrum** [comment]
thank you @mozkan007 
@ameshkov 
logs:
[debug (3).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/696810/debug.3.txt)

**Comment by mozkan007** [comment]
@zebrum I thank you too.

**Comment by ameshkov** [comment]
@mozkan007 please try adding a few rules to the user filter:
```
||liftoff.io^
```

Does it help with English Phrasebook ads?
Is there any other app you see ads inside?

**Comment by mozkan007** [comment]
@ameshkov I checked up again adding the rule above to the user filter but it did not work.The app ads which I have mentioned you are still appearing.

**Comment by ameshkov** [comment]
@mozkan007 could you please collect AG log one more time?

**Comment by mozkan007** [comment]
I attached the log file above.

[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/708629/adguard.log.txt)

**Comment by ameshkov** [comment]
Oh I see, you've disabled AG for `com.google.android.gms`, that's the culprit.
`17:21:21.741 [Thread-15219] INFO  c.a.android.vpn.AdguardVpnService - Excluding app from VPN: com.google.android.gms`

Google ads are downloaded by this app.

**Comment by ameshkov** [comment]
@mozkan007 could you please try the latest AG beta version and check if this issue exists there?

Download link: https://adguard.com/apkb

**Comment by mozkan007** [comment]
@ameshkov Hi again. I appreciate you.Finally my problem is solved completely thanks to you.Thank you very much.

**Comment by ameshkov** [comment]
Yay! Thanks for checking it!

**Comment by mozkan007** [comment]
Hi @ameshkov I am sorry to reopened this issue.You have solved it but it happens again.I am using Adguard v2.9.70 and it blocks app ads and website ads on chrome successfully on wifi mode.However when I use Adguard on mobile data mode, it blocks website ads on chrome in the same way but it does not block any app ads.I enabled Adguard DNS on pref. setting and also I use filtering log to block domains which cause this issue but the case does not change.

**Comment by Revertron** [comment]
May be your mobile operator is routing all DNS requests to his own DNS servers?

**Comment by ameshkov** [comment]
@mozkan007 I'll need to take a look at the log

**Comment by mozkan007** [comment]
@ameshkov    here it is the log file

[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1022199/adguard.log.txt)

**Comment by ameshkov** [comment]
@mozkan007 everything seems to be okay in the log.

How do the ads look like?

**Comment by mozkan007** [comment]
@ameshkov  The ads look just like that below

![quickmemo _2017-05-23-16-24-57](https://cloud.githubusercontent.com/assets/16270347/26357159/1dbe43fe-3fd7-11e7-8e93-a38f13dfe883.png)
![quickmemo _2017-05-23-16-26-26](https://cloud.githubusercontent.com/assets/16270347/26357160/1dbf0a82-3fd7-11e7-9c85-b6be8a7a4c4a.png)

**Comment by mozkan007** [comment]
@ameshkov  This is really interesting problem but actually I do not want to bother you anymore for this silly problem because you did everything that you could do.Thank you for everything.From now on if I come across any other real problem, I will report to you.Have a nice works.

**Comment by ameshkov** [comment]
@mozkan007 huh, it might be important, though. 

I see that you have AG disabled for `com.google.android.gms` again, could it be the culprit?

**Comment by mozkan007** [comment]
I have not changed  anything. I just installed the latest adguard.apk file.I already do not know how to disable com.google.android.gms.

**Comment by mozkan007** [comment]
@ameshkov  I guess my problem is solved completely.Google play services which installed on my phone had not been up-to-date.My phone gave me a warning and updated it to the its latest version a few minutes ago.Then I reboot my phone and everything is working fine especially my bleeding problem disappeared.Also my phone is working so much fast.I think this was the culprit.But I am very happy so much.So you can abort your workings relative with my issue.
