### ISSUE TITLE
Globus VPN won't work along with Adguard in the proxy mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#993]
https://play.google.com/store/apps/details?id=com.globus.vpn&hl=en

It returns the authentification error while connecting. Once you remove the proxy from APN or Wi-Fi settings,  it connects fine.

1170007

**Comment by evgeniy-ADG** [comment]
>Adguard proxy mode is interfering with OpenVPN connection which use
remote port 80 and 443. Is this something that can be fixed? Thanks

can these two issues be related? what info do you need to troubleshoot it? thx

**Comment by ameshkov** [comment]
> can these two issues be related? what info do you need to troubleshoot it? thx

Nah, this one is different.

**Comment by nkartyshov** [comment]
@vozersky Please, test it. I cannot reproduce.

**Comment by nkartyshov** [comment]
@vozersky I reproduce. Disabling the filter resolved the problem.

**Comment by ameshkov** [comment]
This is a VPN app, so it makes sense to disable AG completely for this app.

What have you done? Ad blocking or filtering?

**Comment by nkartyshov** [comment]
@ameshkov  I disabled the filtering completely for the application
