### ISSUE TITLE
AndFTP app. Blocking FTP traffic

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#994]
1409042
https://play.google.com/store/apps/details?id=lysesoft.andftp&hl=ru

рубит трафик по ftp в AndFTP

[debug (32).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/672869/debug.32.txt)
лог проблем с AndFTP в 13:29

Отключение фильтрации для приложения AndFTP  не дало положительного результата. Программа Adguard была перезапущена, как было сказано в зеленом уведомлении. Только полное отключение защиты в программе позволяет прохождение ftp трафика.

**Comment by ameshkov** [comment]
По большому счету это ожидаемо, VPN в Android не позволяет нормально функционировать FTP.

Единственное решение - это добавить IP адрес FTP сервера в исключения роутинга.

Настройка `pref.vpn.ipv4.routes.excluded`
Туда с новой строки нужно добавить `x.x.x.x/32`, где `x.x.x.x` - это IP адрес FTP сервера

**Comment by KozelElena** [comment]
При использовании  http proxy фильтрации и адреса серверов часто меняются. Это поможет? И можно ли прописать диапазон типа 192.168.xxx.xxx в 
исключения? И еще используется https фильтрация, это не может влиять?

**Comment by ameshkov** [comment]
А какие проблемы с http proxy фильтрацией? Она не должна мешать использвовать FTP.

> И можно ли прописать диапазон типа 192.168.xxx.xxx в исключения?

Да, вот так:
`192.168.0.0/16`

**Comment by shaman4ik** [comment]
У меня почему-то мешает. Без https фильтрации все равно мешает.

**Comment by ameshkov** [comment]
@shaman4ik да хттпс или нет это без разницы, главное, что VPN как таковой мешает работе FTP-протокола.

Тут мало что поделаешь - только отключать фильтрацию полностью для приложения (будет работать в Android 5+) либо исключать подсеть FTP-сервера.

**Comment by shaman4ik** [comment]
Так а при чем vpn, если я использую режим фильтрации http proxy?

**Comment by ameshkov** [comment]
Вот это хороший вопрос:) Значит лог приложенный к задаче не ваш по ходу.

Расскажите пожалуйста подробнее как проблема выглядит

**Comment by shaman4ik** [comment]
Пытаюсь подключиться к локальному ftp серверу, происходит авторизация, но когда пытаюсь открывать папки, это редко удается. Очень долгое ожидание, редко успешное.

**Comment by shaman4ik** [comment]
Лог не мой, это меня в этот топик отправили после обращения в тех поддержку по этому вопросу

**Comment by shaman4ik** [comment]
Сейчас еще раз проверил. Открывается стартовая директория. А дальше никуда зайти не могу.

**Comment by ameshkov** [comment]
> Сейчас еще раз проверил. Открывается стартовая директория. А дальше никуда зайти не могу.

Нам точно нужно лог посмотреть, вот такой:
https://kb.adguard.com/ru/android/solving-problems/log

Еще должно помочь отключение фильтрации для этого приложения в настройках приложений в Adguard.

**Comment by shaman4ik** [comment]
Отключение фильтрации для приложения не помогло. Отправил еще раз лог в техподдержку

**Comment by zebrum** [comment]
ticket id 1265945

[debug.txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1035346/debug.txt.zip)

**Comment by ameshkov** [comment]
@shaman4ik 

Нужно отключить для приложения FTP Plugin for Total Commander

**Comment by shaman4ik** [comment]
Помогло. Спасибо.

**Comment by ameshkov** [comment]
> Помогло. Спасибо.

Рекламы никакой не появилось? Может нам стоит в список по-умолчанию добавить его тогда

**Comment by shaman4ik** [comment]
Рекламы не заметил. Еще и AndFTP добавил в исключения. Может и стоит по умолчанию добавит.
