### ISSUE TITLE
net.probki.geonet doesn't work correctly when Adguard is ON

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForAndroid#995]
1475129
Та же проблема, что и в cityguide
Адг блокирует загрузку данных (навигационных карт) 
GeoNet https://play.google.com/store/apps/details?id=net.probki.geonet&hl=ru 
Мы для этого используем FTP. Вы режете порты которые назначаются клиентам нашими серверами (например 56839, 60182, 52897, 56842 и т.п.).

**Comment by ameshkov** [comment]
Айайай, мы не режем порты, а вот FTP не работоспособен из-за наличия VPN как такового.

Проблема в том, что протоколу FTP нужны "входящие соединения", а они не будут работать при включенном VPN.

По идее, проблема должна повторяться при любом включенном VPN. С каким-нибудь No Root Firewall или Opera Max должна повторяться.

**Comment by vgavrish** [comment]
Проверила с No Root Firewall и Opera Max, загрузка карт работает

**Comment by ameshkov** [comment]
@vgavrish ну тогда нужно нам будет потратить чуть больше времени на этот дефект:)

**Comment by nkartyshov** [comment]
Не могу понять почему не грузятся карты в режиме VPN, в логах заметил только то, что входящие соединение от: 84.52.88.204:52010, 84.52.88.204:52013, 84.52.88.195:51991 не может определить протокол. Больше проблем и ошибок в логах не нашел.

В режиме прокси карты загружаются.

**Comment by nkartyshov** [comment]
Отключил фильтрацию полностью для прилоежния, т.к. vpn Не может принимать входящие ftp соединения.

**Comment by ameshkov** [comment]
А рекламы в приложении нет?

**Comment by nkartyshov** [comment]
Рекламы нету.
