### ISSUE TITLE
Certain apps may use non-standard ports to load ads

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardForAndroid#996]
com.imbc.mini - loads `http://miximg.nasmedia.co.kr/library/admixer_0.617.apk` 
https://apkscan.nviso.be/report/show/83b3ec1c4526b89766d0cf28f5b4f128
They may be using 10606,10616,10101 ports.

**Comment by ameshkov** [comment]
@Revertron @nkartyshov 
We'd better discuss this, I am not sure yet what we should do about it.

Simply processing port range may cause more compatibility issues.

**Comment by TPS** [comment]
This is now #796 & #830, I think, so _this_ is duplicate, correct?

**Comment by ameshkov** [comment]
Yeah, thank you! #830 will solve the issue, so let's mark it dup then.
