### ISSUE TITLE
cityguide.probki.net - Adguard breaks updates downloading

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#998]
Apps affected by this bug:
net.probki.bgeo
net.probki.geonet
cityguide.probki.net

We once had such an issue with WS protocol, but it was fixed a long time ago: https://github.com/AdguardTeam/AdguardForAndroid/issues/248

We should check what's wrong now.

User's report:
> Да, получается, точно повторяется:

> - не загружаются аттачи на сервера (фотографии в радио-чат, например)
> - не скачиваются карты

> Была еще одна проблема с пропаданием данных по маршруту, если включен Adguard, но ее так просто воспроизвести не удается.

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/998

**Comment by TPS** [comment]
If duplicate, should be closed?
