### ISSUE TITLE
Filters update check period does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#999]
Linking @TPS comment:
https://github.com/AdguardTeam/AdguardForAndroid/issues/746#issuecomment-269103447

@vozersky please check it

**Comment by vozersky** [comment]
Well, for now i can only confirm that:

""last update" message @ bottom of main screen isn't reflecting update every ➊ hour" if you set a an update period to 1 hour. 
 
But for many people who use 24 hour update period and actually NEVER check for filter updates manually it works fine.

@nkartyshov 
- Could the issue be connected to network unavailability at the time Adguard tried to update the filters? I've made sure that "keep wi-fi on during sleep" is enabled though.

- or it could be the particular (1 hour) update problem?

**Comment by TPS** [comment]
Just randomly, I decided to check this on my 4/Kitkat phone (which I haven't touched in a week or so —  I've on my 7/Nougat phone since 1½ months now). The setting's been @ 1 hour since the option existed, but, when I did a manual update just now, I'd 21 filter updates.  On my current phone, I'd 17, after last manually updating sometime in the last 24 hours, likely w/in the last 10.

This is strongly indicative that the automatic updating is kaput over a number of OS versions & devices.

**Comment by TPS** [comment]
I also tried disabling 7/Nougat's Battery Optimization for AG for ~1 week, just in case, but that didn't help, either.

**Comment by ameshkov** [comment]
I can confirm this bug as well

**Comment by nkartyshov** [comment]
fixed

**Comment by TPS** [comment]
I'll be very happy to test this when released!  Thanks, @nkartyshov! 👏

**Comment by ameshkov** [comment]
@TPS actually filters were updated just ok. The problem is that it was not rendered on the UI side.

**Comment by TPS** [comment]
@ameshkov Is it true, then, on average, the majority of filters will have an update of _any_ kind _every_ hour?  Else (as detailed above), this unlikely solely a UI issue… unless you mean the toast shows all changes since last _toast_ instead of last _update_.

**Comment by ameshkov** [comment]
Nah, what should be updated every time is "last update check time" field. It does not mean that filters actually have updates.

**Comment by TPS** [comment]
@ameshkov So, IUC, when filters were updated in background, the "last update" timestamp wasn't always updated w/ them, which caused the toast to have an artificially excessive list?

**Comment by ameshkov** [comment]
@TPS got it.

> which I haven't touched in a week

Could it be that AG was not running for some part of the week? It'd explain this behavior.

**Comment by TPS** [comment]
No, I've Tasker-like app forcing AG activation (via intent) every minute, so that solves that.

**Comment by ameshkov** [comment]
Ok, that's weird. If it happens with the upcoming beta version, could you please send AG logs?

**Comment by TPS** [comment]
> If it happens with the upcoming beta version, could you please send AG logs?

@ameshkov Sent just now: UserID 1122984.  Always online for 9 hours continuously, but running list update toward end showed 5 (I think) lists updated, though, when I immediately re-updated, no lists updated.

**Comment by zebrum** [comment]
[debug (6).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/831388/debug.6.txt)

**Comment by ameshkov** [comment]
@TPS how it goes with the latest AG beta? There was a change regarding this issue, should've helped.

**Comment by TPS** [comment]
Huh, I didn't notice anything in changelog about this, else I'd paid more attention.  I tried an update ~1 hour ago, & that came up w/ many (>10, don't remember precisely) updates after overnight wifi, so I'm not convinced.

Another note: Did any1 verify whether `Update over Wi-Fi only ☑️` has any effect on this?  I always have this ✔️ed.  Or whether if the phone's in standby?  Maybe that `Watchdog` service should be co-opted for this, too?

**Comment by deLumren** [comment]
Similiar complaint from user 1527483.

**Comment by TPS** [comment]
Just now verified this _not_ working: continuous wifi for 6 hours, but manual update had 16 updates.

**Comment by ameshkov** [comment]
@TPS could you please send a log file again?

**Comment by TPS** [comment]
Just sent after a 12-filterlist update now; should be user 1122984.

**Comment by nkartyshov** [comment]
@TPS When updating filters from the server, their current version is requested, and if it differs from the current one, an update is performed. Because of this, not all filters can be updated.

**Comment by ameshkov** [comment]
@nkartyshov the problem is that there're too many filter updates for 6 hours.

**Comment by ameshkov** [comment]
@TPS we have finally found the culprit:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1121

**Comment by TPS** [comment]
Is there an Intent for filter updates like [for AG Start/Stop](https://kb.adguard.com/en/android/solving-problems/tasker)?

**Comment by ameshkov** [comment]
> Is there an Intent for filter updates like for AG Start/Stop?

Nope
